Terraria Decompiled: System.Reflection.CustomAttributeData.Equals
Equals()
override bool System.Reflection.CustomAttributeData.Equals (object obj) inline
Definition at line 178 of file CustomAttributeData.cs.
        {
            CustomAttributeData customAttributeData = obj as CustomAttributeData;
            if (customAttributeData == null || customAttributeData.ctorInfo != this.ctorInfo || customAttributeData.ctorArgs.Count != this.ctorArgs.Count || customAttributeData.namedArgs.Count != this.namedArgs.Count)
            {
                return false;
            }
            for (int i = 0; i < this.ctorArgs.Count; i++)
            {
                if (this.ctorArgs[i].Equals(customAttributeData.ctorArgs[i]))
                {
                    return false;
                }
            }
            for (int j = 0; j < this.namedArgs.Count; j++)
            {
                bool flag = false;
                for (int k = 0; k < customAttributeData.namedArgs.Count; k++)
                {
                    if (this.namedArgs[j].Equals(customAttributeData.namedArgs[k]))
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    return false;
                }
            }
            return true;
        }
References System.Reflection.CustomAttributeData.ctorArgs, System.Reflection.CustomAttributeData.ctorInfo, System.Reflection.CustomAttributeData.CustomAttributeData(), System.Reflection.CustomAttributeData.Equals(), System.Reflection.CustomAttributeData.namedArgs, and System.obj.
Referenced by System.Reflection.CustomAttributeData.Equals().