Terraria Decompiled: System.Reflection.CustomAttributeData.ToString
ToString()
override string System.Reflection.CustomAttributeData.ToString () inline
Definition at line 137 of file CustomAttributeData.cs.
        {
            this.ResolveArguments();
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("[" + this.ctorInfo.DeclaringType.FullName + "(");
            for (int i = 0; i < this.ctorArgs.Count; i++)
            {
                stringBuilder.Append(this.ctorArgs[i].ToString());
                if (i + 1 < this.ctorArgs.Count)
                {
                    stringBuilder.Append(", ");
                }
            }
            if (this.namedArgs.Count > 0)
            {
                stringBuilder.Append(", ");
            }
            for (int j = 0; j < this.namedArgs.Count; j++)
            {
                stringBuilder.Append(this.namedArgs[j].ToString());
                if (j + 1 < this.namedArgs.Count)
                {
                    stringBuilder.Append(", ");
                }
            }
            stringBuilder.AppendFormat(")]", Array.Empty<object>());
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendFormat(), System.Reflection.CustomAttributeData.ctorArgs, System.Reflection.CustomAttributeData.ctorInfo, System.Reflection.MemberInfo.DeclaringType, System.Type.FullName, System.Reflection.CustomAttributeData.namedArgs, System.Reflection.CustomAttributeData.ResolveArguments(), System.Reflection.CustomAttributeData.ToString(), and System.Text.StringBuilder.ToString().
Referenced by System.Reflection.CustomAttributeData.ToString().