Terraria Decompiled: System.Runtime.Remoting.SingleCallIdentity.SyncObjectProcessMessage
SyncObjectProcessMessage()
override IMessage System.Runtime.Remoting.SingleCallIdentity.SyncObjectProcessMessage (IMessage msg) inline
Definition at line 17 of file SingleCallIdentity.cs.
        {
            MarshalByRefObject marshalByRefObject = (MarshalByRefObject)Activator.CreateInstance(this._objectType, true);
            if (marshalByRefObject.ObjectIdentity == null)
            {
                marshalByRefObject.ObjectIdentity = this;
            }
            IMessage message = this._context.CreateServerObjectSinkChain(marshalByRefObject, false).SyncProcessMessage(msg);
            if (marshalByRefObject is IDisposable)
            {
                ((IDisposable)marshalByRefObject).Dispose();
            }
            return message;
        }
References System.Runtime.Remoting.ServerIdentity._context, System.Activator.CreateInstance(), System.Runtime.Remoting.Contexts.Context.CreateServerObjectSinkChain(), System.MarshalByRefObject.ObjectIdentity, and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().