Terraria Decompiled: Terraria.ID.ItemID.FromLegacyName
FromLegacyName()
static short Terraria.ID.ItemID.FromLegacyName (string name, int release) inline static
Definition at line 779 of file ItemID.cs.
        {
            if (ItemID._legacyItemLookup == null)
            {
                ItemID._legacyItemLookup = ItemID.GenerateLegacyItemDictionary();
            }
            if (release <= 4)
            {
                if (name == "Cobalt Helmet")
                {
                    name = "Jungle Hat";
                }
                else if (name == "Cobalt Breastplate")
                {
                    name = "Jungle Shirt";
                }
                else if (name == "Cobalt Greaves")
                {
                    name = "Jungle Pants";
                }
            }
            if (release <= 13 && name == "Jungle Rose")
            {
                name = "Jungle Spores";
            }
            if (release <= 20)
            {
                if (name == "Gills potion")
                {
                    name = "Gills Potion";
                }
                else if (name == "Thorn Chakrum")
                {
                    name = "Thorn Chakram";
                }
                else if (name == "Ball 'O Hurt")
                {
                    name = "Ball O' Hurt";
                }
            }
            if (release <= 41 && name == "Iron Chain")
            {
                name = "Chain";
            }
            if (release <= 44 && name == "Orb of Light")
            {
                name = "Shadow Orb";
            }
            if (release <= 46)
            {
                if (name == "Black Dye")
                {
                    name = "Black Thread";
                }
                if (name == "Green Dye")
                {
                    name = "Green Thread";
                }
            }
            short num;
            if (ItemID._legacyItemLookup.TryGetValue(name, out num))
            {
                return num;
            }
            return 0;
        }
References Terraria.ID.ItemID._legacyItemLookup, Terraria.ID.ItemID.GenerateLegacyItemDictionary(), System.name, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.Player.Deserialize(), and Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88().