Terraria Decompiled: System.Runtime.Remoting.SingleCallIdentity.AsyncObjectProcessMessage
AsyncObjectProcessMessage()
override IMessageCtrl System.Runtime.Remoting.SingleCallIdentity.AsyncObjectProcessMessage (IMessage msg, IMessageSink replySink) inline
Definition at line 33 of file SingleCallIdentity.cs.
        {
            MarshalByRefObject marshalByRefObject = (MarshalByRefObject)Activator.CreateInstance(this._objectType, true);
            IMessageSink messageSink = this._context.CreateServerObjectSinkChain(marshalByRefObject, false);
            if (marshalByRefObject is IDisposable)
            {
                replySink = new DisposerReplySink(replySink, (IDisposable)marshalByRefObject);
            }
            return messageSink.AsyncProcessMessage(msg, replySink);
        }
References System.Runtime.Remoting.ServerIdentity._context, System.Runtime.Remoting.Messaging.IMessageSink.AsyncProcessMessage(), System.Activator.CreateInstance(), and System.Runtime.Remoting.Contexts.Context.CreateServerObjectSinkChain().