Terraria Decompiled: System.Collections.Generic.LowLevelList.RemoveAll
RemoveAll()
int System.Collections.Generic.LowLevelList< T >.RemoveAll (Predicate< T > match) inline
Definition at line 294 of file LowLevelList.cs.
        {
            if (match == null)
            {
                throw new ArgumentNullException("match");
            }
            int num = 0;
            while (num < this._size && !match(this._items[num]))
            {
                num++;
            }
            if (num >= this._size)
            {
                return 0;
            }
            int i = num + 1;
            while (i < this._size)
            {
                while (i < this._size && match(this._items[i]))
                {
                    i++;
                }
                if (i < this._size)
                {
                    this._items[num++] = this._items[i++];
                }
            }
            Array.Clear(this._items, num, this._size - num);
            int num2 = this._size - num;
            this._size = num;
            this._version++;
            return num2;
        }
References System.Collections.Generic.LowLevelList< T >._items, System.Collections.Generic.LowLevelList< T >._size, System.Collections.Generic.LowLevelList< T >._version, System.Array.Clear(), and System.match.
Referenced by System.Threading.Tasks.Task< TResult >.AddTaskContinuationComplex(), and System.Threading.Tasks.Task< TResult >.Finish().