Terraria Decompiled: System.Collections.Generic.LowLevelList.InsertRange
InsertRange()
void System.Collections.Generic.LowLevelList< T >.InsertRange (int index, IEnumerable< T > collection) inline
Definition at line 236 of file LowLevelList.cs.
        {
            if (collection == null)
            {
                throw new ArgumentNullException("collection");
            }
            if (index > this._size)
            {
                throw new ArgumentOutOfRangeException("index");
            }
            ICollection<T> collection2 = collection as ICollection<T>;
            if (collection2 != null)
            {
                int count = collection2.Count;
                if (count > 0)
                {
                    this.EnsureCapacity(this._size + count);
                    if (index < this._size)
                    {
                        Array.Copy(this._items, index, this._items, index + count, this._size - index);
                    }
                    if (this == collection2)
                    {
                        Array.Copy(this._items, 0, this._items, index, index);
                        Array.Copy(this._items, index + count, this._items, index * 2, this._size - index);
                    }
                    else
                    {
                        T[] array = new T[count];
                        collection2.CopyTo(array, 0);
                        Array.Copy(array, 0, this._items, index, count);
                    }
                    this._size += count;
                }
            }
            else
            {
                foreach (T t in collection)
                {
                    this.Insert(index++, t);
                }
            }
            this._version++;
        }
References System.Collections.Generic.LowLevelList< T >._items, System.Collections.Generic.LowLevelList< T >._size, System.Collections.Generic.LowLevelList< T >._version, System.array, System.collection, System.Array.Copy(), System.Collections.Generic.ICollection< T >.CopyTo(), System.Collections.Generic.ICollection< T >.Count, System.count, System.Collections.Generic.LowLevelList< T >.EnsureCapacity(), System.index, and System.Insert.
Referenced by System.Collections.Generic.LowLevelList< T >.AddRange().