Terraria Decompiled: Terraria.Utilities.FastRandom.Next
Next() [1/2]
int Terraria.Utilities.FastRandom.Next (int max) inline
Definition at line 84 of file FastRandom.cs.
        {
            if ((max & -max) == max)
            {
                return (int)((long)max * (long)this.NextBits(31) >> 31);
            }
            int num;
            int num2;
            do
            {
                num = this.NextBits(31);
                num2 = num % max;
            }
            while (num - num2 + (max - 1) < 0);
            return num2;
        }
References long, and Terraria.Utilities.FastRandom.NextBits().
Referenced by Terraria.GameContent.Skies.AmbientSky.AirBalloonSkyEntity.AirBalloonSkyEntity(), Terraria.GameContent.Skies.AmbientSky.AirshipSkyEntity.AirshipSkyEntity(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.BatsGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.BirdsPackSkyEntity.BirdsPackSkyEntity(), Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.ButterfliesSkyEntity(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.CreateGroup(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.CreateGroup(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode0_Swipe(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode1_Swipe(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.EOCSkyEntity(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.GastropodGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.HellBatsGoupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.LostKiteSkyEntity(), Terraria.GameContent.Skies.AmbientSky.MeteorSkyEntity.MeteorSkyEntity(), Terraria.Utilities.FastRandom.Next(), Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.PegasusSkyEntity(), Terraria.GameContent.Skies.AmbientSky.PixiePosseSkyEntity.PixiePosseSkyEntity(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.Main.ResetWindCounter(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.SeagullsGroupSkyEntity(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.SlimeBalloonGroupSkyEntity(), Terraria.Star.SpawnStars(), Terraria.GameContent.Skies.AmbientSky.VultureSkyEntity.VultureSkyEntity(), and Terraria.GameContent.Skies.AmbientSky.WyvernSkyEntity.WyvernSkyEntity().