Terraria Decompiled: Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract
JsonDictionaryContract()
Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract (Type underlyingType) inline
Definition at line 137 of file JsonDictionaryContract.cs.
            : base(underlyingType)
        {
            this.ContractType = JsonContractType.Dictionary;
            Type type;
            Type type2;
            if (ReflectionUtils.ImplementsGenericDefinition(underlyingType, typeof(IDictionary), out this._genericCollectionDefinitionType))
            {
                type = this._genericCollectionDefinitionType.GetGenericArguments()[0];
                type2 = this._genericCollectionDefinitionType.GetGenericArguments()[1];
                if (ReflectionUtils.IsGenericDefinition(base.UnderlyingType, typeof(IDictionary)))
                {
                    base.CreatedType = typeof(Dictionary).MakeGenericType(new Type[] { type, type2 });
                }
            }
            else
            {
                ReflectionUtils.GetDictionaryKeyValueTypes(base.UnderlyingType, out type, out type2);
                if (base.UnderlyingType == typeof(IDictionary))
                {
                    base.CreatedType = typeof(Dictionary<object, object>);
                }
            }
            if (type != null && type2 != null)
            {
                this._parameterizedConstructor = CollectionUtils.ResolveEnumerableCollectionConstructor(base.CreatedType, typeof(KeyValuePair).MakeGenericType(new Type[] { type, type2 }), typeof(IDictionary).MakeGenericType(new Type[] { type, type2 }));
                if (!this.HasParameterizedCreatorInternal && underlyingType.Name == "FSharpMap`2")
                {
                    FSharpUtils.EnsureInitialized(underlyingType.Assembly());
                    this._parameterizedCreator = FSharpUtils.CreateMap(type, type2);
                }
            }
            this.ShouldCreateWrapper = !typeof(IDictionary).IsAssignableFrom(base.CreatedType);
            this.DictionaryKeyType = type;
            this.DictionaryValueType = type2;
        }
References Newtonsoft.Json.Serialization.JsonDictionaryContract._genericCollectionDefinitionType, System.Type.Assembly, Newtonsoft.Json.Utilities.FSharpUtils.CreateMap(), Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(), System.Type.GetGenericArguments(), Newtonsoft.Json.Serialization.JsonDictionaryContract.HasParameterizedCreatorInternal, Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.IsGenericDefinition(), System.Type.MakeGenericType(), System.Reflection.MemberInfo.Name, and Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor().