Terraria Decompiled: Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper
CreateWrapper()
IWrappedDictionary Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper (object dictionary) inline package
Definition at line 175 of file JsonDictionaryContract.cs.
        {
            if (this._genericWrapperCreator == null)
            {
                this._genericWrapperType = typeof(DictionaryWrapper<, >).MakeGenericType(new Type[] { this.DictionaryKeyType, this.DictionaryValueType });
                ConstructorInfo constructor = this._genericWrapperType.GetConstructor(new Type[] { this._genericCollectionDefinitionType });
                this._genericWrapperCreator = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(constructor);
            }
            return (IWrappedDictionary)this._genericWrapperCreator(new object[] { dictionary });
        }
References Newtonsoft.Json.Serialization.JsonDictionaryContract._genericWrapperCreator, Newtonsoft.Json.Serialization.JsonDictionaryContract._genericWrapperType, Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Serialization.JsonDictionaryContract.DictionaryKeyType, System.Type.GetConstructor(), and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue().