Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenShapeRoom
GenShapeRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenShapeRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 144 of file GenShapeDungeonRoom.cs.
        {
            new UnifiedRandom(this.settings.RandomSeed);
            GenShapeDungeonRoomSettings genShapeDungeonRoomSettings = (GenShapeDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Vector2D vector2D;
            vector2D..ctor((double)i, (double)j);
            if (base.Processed)
            {
                vector2D = base.Center;
            }
            this.InnerBounds.SetBounds((int)vector2D.X, (int)vector2D.Y, (int)vector2D.X, (int)vector2D.Y);
            this.OuterBounds.SetBounds((int)vector2D.X, (int)vector2D.Y, (int)vector2D.X, (int)vector2D.Y);
            GenAction genAction = new Actions.Blank();
            if (genShapeDungeonRoomSettings.OverridePaintTile == 0)
            {
                genAction = new Actions.ClearTilePaint();
            }
            else if (genShapeDungeonRoomSettings.OverridePaintTile > 0)
            {
                genAction = new Actions.SetTilePaint((byte)genShapeDungeonRoomSettings.OverridePaintTile);
            }
            GenAction genAction2 = new Actions.Blank();
            if (genShapeDungeonRoomSettings.OverridePaintWall == 0)
            {
                genAction2 = new Actions.ClearWallPaint();
            }
            else if (genShapeDungeonRoomSettings.OverridePaintWall > 0)
            {
                genAction2 = new Actions.SetWallPaint((byte)genShapeDungeonRoomSettings.OverridePaintWall);
            }
            WorldUtils.Gen(vector2D.ToPoint(), genShapeDungeonRoomSettings.OuterShape, Actions.Chain(new GenAction[]
            {
                new Modifiers.Expand(1),
                new Actions.UpdateBounds(data.dungeonBounds).Output(this._outerShapeData),
                new Actions.UpdateBounds(this.OuterBounds),
                new Modifiers.Conditions(new GenCondition[]
                {
                    new Conditions.BoolCheck(generating)
                }),
                new Actions.ClearTile(false),
                new Actions.SetTile(brickTileType, false, false, false),
                genAction
            }));
            if (generating)
            {
                WorldUtils.Gen(vector2D.ToPoint(), genShapeDungeonRoomSettings.OuterShape, Actions.Chain(new GenAction[]
                {
                    new Actions.SetWall(brickWallType, false, false, false),
                    genAction2
                }));
            }
            WorldUtils.Gen(vector2D.ToPoint(), genShapeDungeonRoomSettings.InnerShape, Actions.Chain(new GenAction[]
            {
                new Actions.UpdateBounds(data.dungeonBounds).Output(this._innerShapeData),
                new Actions.UpdateBounds(this.InnerBounds),
                new Modifiers.Conditions(new GenCondition[]
                {
                    new Conditions.BoolCheck(generating)
                }),
                new Actions.Clear(),
                new Actions.SetWall(brickWallType, false, false, false),
                genAction2
            }));
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
            this._floodedTileCount = DungeonUtils.CalculateFloodedTileCountFromShapeData(this.InnerBounds, this._innerShapeData);
        }
References Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoomSettings.OuterShape, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenerateRoom().