Terraria Decompiled: Terraria.Utilities.TileSnapshot.SaveTiles
SaveTiles()
static void Terraria.Utilities.TileSnapshot.SaveTiles () inline static private
Definition at line 49 of file TileSnapshot.cs.
        {
            Array.Resize<TileSnapshot.TileStruct>(ref TileSnapshot._tiles, Main.maxTilesX * Main.maxTilesY);
            FastParallel.For(0, Main.maxTilesX, delegate(int x0, int x1, object _)
            {
                Tile[,] tile = Main.tile;
                TileSnapshot.TileStruct[] tiles = TileSnapshot._tiles;
                int maxTilesY = Main.maxTilesY;
                for (int i = x0; i < x1; i++)
                {
                    for (int j = 0; j < maxTilesY; j++)
                    {
                        tiles[i * maxTilesY + j] = TileSnapshot.TileStruct.From(tile[i, j]);
                    }
                }
            }, null);
        }
References Terraria.Utilities.TileSnapshot._tiles, ReLogic.Threading.FastParallel.For(), Terraria.Utilities.TileSnapshot.TileStruct.From(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, and Terraria.Main.tile.
Referenced by Terraria.Utilities.TileSnapshot.Create().