Terraria Decompiled: System.Threading.Tasks.Task.DelayPromise.Complete
Complete()
void System.Threading.Tasks.Task< TResult >.DelayPromise.Complete () inline package
Definition at line 3111 of file Task.2.cs.
            {
                bool flag;
                if (this.Token.IsCancellationRequested)
                {
                    flag = base.TrySetCanceled(this.Token);
                }
                else
                {
                    if (DebuggerSupport.LoggingOn)
                    {
                        DebuggerSupport.TraceOperationCompletion(CausalityTraceLevel.Required, this, AsyncStatus.Completed);
                    }
                    DebuggerSupport.RemoveFromActiveTasks(this);
                    flag = base.TrySetResult(default(VoidTaskResult));
                }
                if (flag)
                {
                    if (this.Timer != null)
                    {
                        this.Timer.Dispose();
                    }
                    this.Registration.Dispose();
                }
            }
References System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.Timer.Dispose(), System.Threading.CancellationToken.IsCancellationRequested, System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.Task< TResult >.DelayPromise.Registration, System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasks(), System.Threading.Tasks.Task< TResult >.DelayPromise.Token, and System.Threading.Tasks.DebuggerSupport.TraceOperationCompletion().