Terraria Decompiled: Terraria.Utilities.TileSnapshot.Swap
Swap()
static void Terraria.Utilities.TileSnapshot.Swap () inline static
Definition at line 226 of file TileSnapshot.cs.
        {
            TileSnapshot._worldFile = Main.ActiveWorldFileData;
            TileSnapshot.SwapTiles();
            List<TileEntity> tileEntities = TileSnapshot._tileEntities;
            TileSnapshot._tileEntities = null;
            TileSnapshot.SaveTileEntities(false);
            TileSnapshot.RestoreTileEntities(tileEntities, false);
            List<Chest> chests = TileSnapshot._chests;
            TileSnapshot._chests = null;
            TileSnapshot.SaveChests(false);
            TileSnapshot.RestoreChests(chests, false);
            if (Main.dedServ)
            {
                NetMessage.ResyncTiles(new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY));
                return;
            }
            Main.sectionManager.SetAllSectionsLoaded();
        }
References Terraria.Utilities.TileSnapshot._chests, Terraria.Utilities.TileSnapshot._tileEntities, Terraria.Main.ActiveWorldFileData, Terraria.Main.dedServ, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.TileSnapshot.RestoreChests(), Terraria.Utilities.TileSnapshot.RestoreTileEntities(), Terraria.NetMessage.ResyncTiles(), Terraria.Utilities.TileSnapshot.SaveChests(), Terraria.Utilities.TileSnapshot.SaveTileEntities(), Terraria.Main.sectionManager, Terraria.WorldSections.SetAllSectionsLoaded(), and Terraria.Utilities.TileSnapshot.SwapTiles().
Referenced by Terraria.Testing.ChatCommands.ToolkitDebugCommands.SwapCommand().