Terraria Decompiled: Terraria.Utilities.TileSnapshot.Compare
Compare()
static IEnumerable< Point > Terraria.Utilities.TileSnapshot.Compare () inline static
Definition at line 123 of file TileSnapshot.cs.
        {
            bool any = false;
            int num;
            for (int x = 0; x < Main.maxTilesX; x = num + 1)
            {
                for (int y = 0; y < Main.maxTilesY; y = num + 1)
                {
                    TileSnapshot.TileStruct tileStruct = TileSnapshot.TileStruct.From(Main.tile[x, y]);
                    TileSnapshot.TileStruct tileStruct2 = TileSnapshot._tiles[x * Main.maxTilesY + y];
                    if (!(tileStruct == tileStruct2))
                    {
                        any = true;
                        Main.NewText(string.Concat(new object[] { "Mismatch at ", x, ", ", y, " world vs snap" }), byte.MaxValue, byte.MaxValue, byte.MaxValue);
                        Main.NewText(tileStruct.ToString(), byte.MaxValue, byte.MaxValue, byte.MaxValue);
                        Main.NewText(tileStruct2.ToString(), byte.MaxValue, byte.MaxValue, byte.MaxValue);
                        yield return new Point(x, y);
                    }
                    num = y;
                }
                num = x;
            }
            Main.NewText(any ? "No more differences" : "Snapshot matches identically", byte.MaxValue, byte.MaxValue, byte.MaxValue);
            yield break;
        }
References Terraria.Utilities.TileSnapshot._tiles, Terraria.Utilities.TileSnapshot.TileStruct.From(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.NewText(), Terraria.Main.tile, and Terraria.Utilities.TileSnapshot.TileStruct.ToString().
Referenced by Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotDiffCommand().