Terraria Decompiled: Terraria.Utilities.TileSnapshot.Clone
Clone()
static TileEntity Terraria.Utilities.TileSnapshot.Clone (TileEntity ent) inline static private
Definition at line 150 of file TileSnapshot.cs.
        {
            TileSnapshot._tempStream.Position = 0L;
            TileEntity.Write(TileSnapshot._tempWriter, ent, false);
            TileSnapshot._tempStream.Position = 0L;
            return TileEntity.Read(TileSnapshot._tempReader, 319, false);
        }
References Terraria.Utilities.TileSnapshot._tempReader, Terraria.Utilities.TileSnapshot._tempWriter, System.L, Terraria.DataStructures.TileEntity.Read(), and Terraria.DataStructures.TileEntity.Write().
Referenced by Terraria.Utilities.TileSnapshot.RestoreTileEntities(), and Terraria.Utilities.TileSnapshot.SaveTileEntities().