Terraria Decompiled: Terraria.Utilities.TileSnapshot.Load
Load() [1/2]
static void Terraria.Utilities.TileSnapshot.Load (BinaryReader reader, object context = null) inline static
Definition at line 316 of file TileSnapshot.cs.
        {
            if (reader.ReadInt32() != Marshal.SizeOf(typeof(TileSnapshot.TileStruct)))
            {
                throw new Exception("TileSnapshot was saved with a different value of #define SNAPSHOT_RUNTIME_DATA");
            }
            TileSnapshot.Context = context;
            TileSnapshot._worldFile = Main.ActiveWorldFileData;
            Array.Resize<TileSnapshot.TileStruct>(ref TileSnapshot._tiles, Main.maxTilesX * Main.maxTilesY);
            for (int i = 0; i < TileSnapshot._tiles.Length; i++)
            {
                TileSnapshot._tiles[i] = TileSnapshot.TileStruct.Read(reader);
            }
            if (TileSnapshot._tileEntities == null)
            {
                TileSnapshot._tileEntities = new List<TileEntity>();
            }
            TileSnapshot._tileEntities.Clear();
            int num = reader.ReadInt32();
            for (int j = 0; j < num; j++)
            {
                TileSnapshot._tileEntities.Add(TileEntity.Read(reader, 319, false));
            }
            if (TileSnapshot._chests == null)
            {
                TileSnapshot._chests = new List<Chest>();
            }
            TileSnapshot._chests.Clear();
            num = reader.ReadInt32();
            for (int k = 0; k < num; k++)
            {
                Chest chest = Chest.CreateOutOfArray(reader.ReadInt32(), reader.ReadInt32(), reader.ReadInt32(), reader.ReadInt32());
                chest.name = reader.ReadString();
                chest.FillWithEmptyInstances();
                for (int l = 0; l < chest.maxItems; l++)
                {
                    int num2 = (int)reader.ReadUInt16();
                    if (num2 != 0)
                    {
                        Item item = chest.item[l];
                        item.SetDefaults(num2, null);
                        item.stack = (int)reader.ReadUInt16();
                        item.Prefix((int)reader.ReadByte());
                    }
                }
                TileSnapshot._chests.Add(chest);
            }
        }
References Terraria.Utilities.TileSnapshot._chests, Terraria.Utilities.TileSnapshot._tileEntities, Terraria.Utilities.TileSnapshot._tiles, Terraria.Main.ActiveWorldFileData, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), Terraria.Chest.CreateOutOfArray(), Terraria.Chest.FillWithEmptyInstances(), int, System.item, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.maxTilesY, Terraria.Utilities.TileSnapshot.TileStruct.Read(), Terraria.DataStructures.TileEntity.Read(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt16(), Terraria.Item.SetDefaults(), and System.Runtime.InteropServices.Marshal.SizeOf().
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.Load(), Terraria.Utilities.TileSnapshot.Load(), and Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotLoadCommand().