Terraria Decompiled: Terraria.Utilities.TileSnapshot.Save
Save() [1/2]
static void Terraria.Utilities.TileSnapshot.Save (BinaryWriter writer) inline static
Definition at line 278 of file TileSnapshot.cs.
        {
            writer.Write(Marshal.SizeOf(typeof(TileSnapshot.TileStruct)));
            foreach (TileSnapshot.TileStruct tileStruct in TileSnapshot._tiles)
            {
                tileStruct.Write(writer);
            }
            writer.Write(TileSnapshot._tileEntities.Count);
            foreach (TileEntity tileEntity in TileSnapshot._tileEntities)
            {
                TileEntity.Write(writer, tileEntity, false);
            }
            writer.Write(TileSnapshot._chests.Count);
            foreach (Chest chest in TileSnapshot._chests)
            {
                writer.Write(chest.index);
                writer.Write(chest.x);
                writer.Write(chest.y);
                writer.Write(chest.maxItems);
                writer.Write(chest.name);
                for (int j = 0; j < chest.maxItems; j++)
                {
                    Item item = chest.item[j];
                    if (item.IsAir)
                    {
                        writer.Write(0);
                    }
                    else
                    {
                        writer.Write((ushort)item.type);
                        writer.Write((ushort)item.stack);
                        writer.Write(item.prefix);
                    }
                }
            }
        }
References Terraria.Utilities.TileSnapshot._chests, Terraria.Utilities.TileSnapshot._tileEntities, Terraria.Utilities.TileSnapshot._tiles, System.Collections.Generic.List< T >.Count, Terraria.Chest.index, System.item, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Chest.name, System.Runtime.InteropServices.Marshal.SizeOf(), Terraria.DataStructures.TileEntity.Write(), System.IO.BinaryWriter.Write(), Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.Create(), Terraria.Utilities.TileSnapshot.Save(), and Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotSaveCommand().