Terraria Decompiled: Terraria.Utilities.TileSnapshot.Restore
Restore() [1/2]
static void Terraria.Utilities.TileSnapshot.Restore () inline static
Definition at line 159 of file TileSnapshot.cs.
        {
            TileSnapshot.RestoreTiles();
            TileSnapshot.RestoreTileEntities(TileSnapshot._tileEntities, true);
            TileSnapshot.RestoreChests(TileSnapshot._chests, true);
            if (Main.dedServ)
            {
                NetMessage.ResyncTiles(new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY));
                return;
            }
            Main.sectionManager.SetAllSectionsLoaded();
        }
References Terraria.Utilities.TileSnapshot._chests, Terraria.Utilities.TileSnapshot._tileEntities, Terraria.Main.dedServ, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.TileSnapshot.RestoreChests(), Terraria.Utilities.TileSnapshot.RestoreTileEntities(), Terraria.Utilities.TileSnapshot.RestoreTiles(), Terraria.NetMessage.ResyncTiles(), Terraria.Main.sectionManager, and Terraria.WorldSections.SetAllSectionsLoaded().
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.Restore(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.RestoreCommand(), Terraria.Utilities.TileSnapshot.RestoreTileEntities(), and Terraria.GameContent.UI.States.UIWorldGenDebug.TestHiddenTileData().