Terraria Decompiled: System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage
GetNeutralResourcesLanguage()
static CultureInfo System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage (Assembly a, ref UltimateResourceFallbackLocation fallbackLocation) inline static package
Definition at line 99 of file ManifestBasedResourceGroveler.cs.
        {
            string text = null;
            short num = 0;
            if (!ManifestBasedResourceGroveler.GetNeutralResourcesLanguageAttribute(a, ref text, ref num))
            {
                fallbackLocation = UltimateResourceFallbackLocation.MainAssembly;
                return CultureInfo.InvariantCulture;
            }
            if (num < 0 || num > 1)
            {
                throw new ArgumentException(Environment.GetResourceString("The NeutralResourcesLanguageAttribute specifies an invalid or unrecognized ultimate resource fallback location: \"{0}\".", new object[] { num }));
            }
            fallbackLocation = (UltimateResourceFallbackLocation)num;
            CultureInfo cultureInfo;
            try
            {
                cultureInfo = CultureInfo.GetCultureInfo(text);
            }
            catch (ArgumentException ex)
            {
                if (!(a == typeof(object).Assembly))
                {
                    throw new ArgumentException(Environment.GetResourceString("The NeutralResourcesLanguageAttribute on the assembly \"{0}\" specifies an invalid culture name: \"{1}\".", new object[]
                    {
                        a.ToString(),
                        text
                    }), ex);
                }
                cultureInfo = CultureInfo.InvariantCulture;
            }
            return cultureInfo;
        }
References System.Globalization.CultureInfo.GetCultureInfo(), System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguageAttribute(), System.Environment.GetResourceString(), System.Globalization.CultureInfo.InvariantCulture, and System.text.
Referenced by System.Resources.ResourceManager.CommonAssemblyInit(), System.Resources.ResourceManager.GetNeutralResourcesLanguage(), and System.Resources.ResourceManager.OnDeserialized().