Terraria Decompiled: System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly
GetSatelliteAssembly()
RuntimeAssembly System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly (CultureInfo lookForCulture, ref StackCrawlMark stackMark) inline private
Definition at line 274 of file ManifestBasedResourceGroveler.cs.
        {
            if (!this._mediator.LookedForSatelliteContractVersion)
            {
                this._mediator.SatelliteContractVersion = this._mediator.ObtainSatelliteContractVersion(this._mediator.MainAssembly);
                this._mediator.LookedForSatelliteContractVersion = true;
            }
            RuntimeAssembly runtimeAssembly = null;
            string satelliteAssemblyName = this.GetSatelliteAssemblyName();
            try
            {
                runtimeAssembly = this._mediator.MainAssembly.InternalGetSatelliteAssembly(satelliteAssemblyName, lookForCulture, this._mediator.SatelliteContractVersion, false, ref stackMark);
            }
            catch (FileLoadException)
            {
            }
            catch (BadImageFormatException)
            {
            }
            return runtimeAssembly;
        }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssemblyName(), System.Reflection.Assembly.InternalGetSatelliteAssembly(), and System.Resources.ResourceManager.MainAssembly.
Referenced by System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet().