Terraria Decompiled: System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup
CaseInsensitiveManifestResourceStreamLookup()
Stream System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup (RuntimeAssembly satellite, string name) inline private
Definition at line 228 of file ManifestBasedResourceGroveler.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            if (this._mediator.LocationInfo != null)
            {
                string @namespace = this._mediator.LocationInfo.Namespace;
                if (@namespace != null)
                {
                    stringBuilder.Append(@namespace);
                    if (name != null)
                    {
                        stringBuilder.Append(Type.Delimiter);
                    }
                }
            }
            stringBuilder.Append(name);
            string text = stringBuilder.ToString();
            CompareInfo compareInfo = CultureInfo.InvariantCulture.CompareInfo;
            string text2 = null;
            foreach (string text3 in satellite.GetManifestResourceNames())
            {
                if (compareInfo.Compare(text3, text, CompareOptions.IgnoreCase) == 0)
                {
                    if (text2 != null)
                    {
                        throw new MissingManifestResourceException(Environment.GetResourceString("A case-insensitive lookup for resource file \"{0}\" in assembly \"{1}\" found multiple entries. Remove the duplicates or specify the exact case.", new object[]
{
                            text,
                            satellite.ToString()
                        }));
                    }
                    text2 = text3;
                }
            }
            if (text2 == null)
            {
                return null;
            }
            bool flag = this._mediator.MainAssembly == satellite && this._mediator.CallingAssembly == this._mediator.MainAssembly;
            StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMyCaller;
            return satellite.GetManifestResourceStream(text2, ref stackCrawlMark, flag);
        }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.Text.StringBuilder.Append(), System.Globalization.CultureInfo.CompareInfo, System.Type.Delimiter, System.Reflection.RuntimeAssembly.GetManifestResourceNames(), System.Reflection.RuntimeAssembly.GetManifestResourceStream(), System.Environment.GetResourceString(), System.Globalization.CultureInfo.InvariantCulture, System.Resources.ResourceManager.MainAssembly, System.name, System.text, and System.Text.StringBuilder.ToString().
Referenced by System.Resources.ManifestBasedResourceGroveler.GetManifestResourceStream().