Terraria Decompiled: System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing
HandleSatelliteMissing()
void System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing () inline private
Definition at line 316 of file ManifestBasedResourceGroveler.cs.
        {
            string text = this._mediator.MainAssembly.GetSimpleName() + ".resources.dll";
            if (this._mediator.SatelliteContractVersion != null)
            {
                text = text + ", Version=" + this._mediator.SatelliteContractVersion.ToString();
            }
            AssemblyName assemblyName = new AssemblyName();
            assemblyName.SetPublicKey(this._mediator.MainAssembly.GetPublicKey());
            byte[] publicKeyToken = assemblyName.GetPublicKeyToken();
            int num = publicKeyToken.Length;
            StringBuilder stringBuilder = new StringBuilder(num * 2);
            for (int i = 0; i < num; i++)
            {
                stringBuilder.Append(publicKeyToken[i].ToString("x", CultureInfo.InvariantCulture));
            }
            string text2 = text;
            string text3 = ", PublicKeyToken=";
            StringBuilder stringBuilder2 = stringBuilder;
            text = text2 + text3 + ((stringBuilder2 != null) ? stringBuilder2.ToString() : null);
            string text4 = this._mediator.NeutralResourcesCulture.Name;
            if (text4.Length == 0)
            {
                text4 = "<invariant>";
            }
            throw new MissingSatelliteAssemblyException(Environment.GetResourceString("The satellite assembly named \"{1}\" for fallback culture \"{0}\" either could not be found or could not be loaded. This is generally a setup problem. Please consider reinstalling or repairing the application.", new object[]
            {
                this._mediator.NeutralResourcesCulture,
                text
            }), text4);
        }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.Text.StringBuilder.Append(), System.Reflection.Assembly.GetPublicKey(), System.Reflection.AssemblyName.GetPublicKeyToken(), System.Environment.GetResourceString(), System.Reflection.Assembly.GetSimpleName(), System.Globalization.CultureInfo.InvariantCulture, System.Resources.ResourceManager.MainAssembly, System.Reflection.AssemblyName.SetPublicKey(), System.text, System.Text.StringBuilder.ToString(), and System.ToString.
Referenced by System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet().