Terraria Decompiled: System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet
GrovelForResourceSet()
ResourceSet System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet (CultureInfo culture, Dictionary< string, ResourceSet > localResourceSets, bool tryParents, bool createIfNotExists, ref StackCrawlMark stackMark) inline
Implements System.Resources.IResourceGroveler.
Definition at line 25 of file ManifestBasedResourceGroveler.cs.
        {
            ResourceSet resourceSet = null;
            Stream stream = null;
            RuntimeAssembly runtimeAssembly = null;
            CultureInfo cultureInfo = this.UltimateFallbackFixup(culture);
            if (cultureInfo.HasInvariantCultureName && this._mediator.FallbackLoc == UltimateResourceFallbackLocation.MainAssembly)
            {
                runtimeAssembly = this._mediator.MainAssembly;
            }
            else
            {
                runtimeAssembly = this.GetSatelliteAssembly(cultureInfo, ref stackMark);
                if (runtimeAssembly == null && (culture.HasInvariantCultureName && this._mediator.FallbackLoc == UltimateResourceFallbackLocation.Satellite))
                {
                    this.HandleSatelliteMissing();
                }
            }
            string resourceFileName = this._mediator.GetResourceFileName(cultureInfo);
            if (runtimeAssembly != null)
            {
                lock (localResourceSets)
                {
                    localResourceSets.TryGetValue(culture.Name, out resourceSet);
                }
                stream = this.GetManifestResourceStream(runtimeAssembly, resourceFileName, ref stackMark);
            }
            if (createIfNotExists && stream != null && resourceSet == null)
            {
                resourceSet = this.CreateResourceSet(stream, runtimeAssembly);
            }
            else if (stream == null && tryParents && culture.HasInvariantCultureName)
            {
                this.HandleResourceStreamMissing(resourceFileName);
            }
            return resourceSet;
        }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), System.culture, System.Resources.ManifestBasedResourceGroveler.GetManifestResourceStream(), System.Resources.ResourceManager.GetResourceFileName(), System.Resources.ManifestBasedResourceGroveler.GetSatelliteAssembly(), System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(), System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing(), System.Globalization.CultureInfo.HasInvariantCultureName, System.Resources.ResourceManager.MainAssembly, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.Resources.ManifestBasedResourceGroveler.UltimateFallbackFixup().