Terraria Decompiled: System.Resources.ManifestBasedResourceGroveler.CreateResourceSet
CreateResourceSet()
ResourceSet System.Resources.ManifestBasedResourceGroveler.CreateResourceSet (Stream store, Assembly assembly) inline package
Definition at line 135 of file ManifestBasedResourceGroveler.cs.
        {
            if (store.CanSeek && store.Length > 4L)
            {
                long position = store.Position;
                BinaryReader binaryReader = new BinaryReader(store);
                if (binaryReader.ReadInt32() == ResourceManager.MagicNumber)
                {
                    int num = binaryReader.ReadInt32();
                    string text;
                    string text2;
                    if (num == ResourceManager.HeaderVersionNumber)
                    {
                        binaryReader.ReadInt32();
                        text = binaryReader.ReadString();
                        text2 = binaryReader.ReadString();
                    }
                    else
                    {
                        if (num <= ResourceManager.HeaderVersionNumber)
{
                            throw new NotSupportedException(Environment.GetResourceString("Found an obsolete .resources file in assembly '{0}'. Rebuild that .resources file then rebuild that assembly.", new object[] { this._mediator.MainAssembly.GetSimpleName() }));
                        }
                        int num2 = binaryReader.ReadInt32();
                        long num3 = binaryReader.BaseStream.Position + (long)num2;
                        text = binaryReader.ReadString();
                        text2 = binaryReader.ReadString();
                        binaryReader.BaseStream.Seek(num3, SeekOrigin.Begin);
                    }
                    store.Position = position;
                    if (this.CanUseDefaultResourceClasses(text, text2))
                    {
                        return new RuntimeResourceSet(store);
                    }
                    IResourceReader resourceReader = (IResourceReader)Activator.CreateInstance(Type.GetType(text, true), new object[] { store });
                    object[] array = new object[] { resourceReader };
                    Type type;
                    if (this._mediator.UserResourceSet == null)
                    {
                        type = Type.GetType(text2, true, false);
                    }
                    else
                    {
                        type = this._mediator.UserResourceSet;
                    }
                    return (ResourceSet)Activator.CreateInstance(type, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.CreateInstance, null, array, null, null);
                }
                else
                {
                    store.Position = position;
                }
            }
            if (this._mediator.UserResourceSet == null)
            {
                return new RuntimeResourceSet(store);
            }
            object[] array2 = new object[] { store, assembly };
            ResourceSet resourceSet;
            try
            {
                try
                {
                    return (ResourceSet)Activator.CreateInstance(this._mediator.UserResourceSet, array2);
                }
                catch (MissingMethodException)
                {
                }
                array2 = new object[] { store };
                resourceSet = (ResourceSet)Activator.CreateInstance(this._mediator.UserResourceSet, array2);
            }
            catch (MissingMethodException ex)
            {
                throw new InvalidOperationException(Environment.GetResourceString("'{0}': ResourceSet derived classes must provide a constructor that takes a String file name and a constructor that takes a Stream.", new object[] { this._mediator.UserResourceSet.AssemblyQualifiedName }), ex);
            }
            return resourceSet;
        }
References System.Resources.ManifestBasedResourceGroveler._mediator, System.array, System.IO.BinaryReader.BaseStream, System.IO.Stream.CanSeek, System.Resources.ManifestBasedResourceGroveler.CanUseDefaultResourceClasses(), System.Activator.CreateInstance(), System.Environment.GetResourceString(), System.Type.GetType(), System.Resources.ResourceManager.HeaderVersionNumber, System.L, System.IO.Stream.Length, long, System.Resources.ResourceManager.MagicNumber, System.IO.Stream.Position, System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.IO.Stream.Seek(), and System.text.
Referenced by System.Resources.ManifestBasedResourceGroveler.GrovelForResourceSet().