Terraria Decompiled: System.Resources.ResourceManager.AddResourceSet
AddResourceSet()
static void System.Resources.ResourceManager.AddResourceSet (Dictionary< string, ResourceSet > localResourceSets, string cultureName, ref ResourceSet rs) inline static private
Definition at line 470 of file ResourceManager.cs.
        {
            lock (localResourceSets)
            {
                ResourceSet resourceSet;
                if (localResourceSets.TryGetValue(cultureName, out resourceSet))
                {
                    if (resourceSet != rs)
                    {
                        if (!localResourceSets.ContainsValue(rs))
{
                            rs.Dispose();
                        }
                        rs = resourceSet;
                    }
                }
                else
                {
                    localResourceSets.Add(cultureName, rs);
                }
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsValue(), System.Resources.ResourceSet.Dispose(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Resources.ResourceManager.GetResourceSet(), and System.Resources.ResourceManager.InternalGetResourceSet().