Terraria Decompiled: System.Resources.ResourceManager.GetObject
GetObject() [3/3]
object System.Resources.ResourceManager.GetObject (string name, CultureInfo culture, bool wrapUnmanagedMemStream) inline private
Definition at line 677 of file ResourceManager.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (culture == null)
            {
                culture = Thread.CurrentThread.GetCurrentUICultureNoAppX();
            }
            ResourceSet resourceSet = this.GetFirstResourceSet(culture);
            if (resourceSet != null)
            {
                object @object = resourceSet.GetObject(name, this._ignoreCase);
                if (@object != null)
                {
                    UnmanagedMemoryStream unmanagedMemoryStream = @object as UnmanagedMemoryStream;
                    if (unmanagedMemoryStream != null && wrapUnmanagedMemStream)
                    {
                        return new UnmanagedMemoryStreamWrapper(unmanagedMemoryStream);
                    }
                    return @object;
                }
            }
            foreach (CultureInfo cultureInfo in new ResourceFallbackManager(culture, this._neutralResourcesCulture, true))
            {
                ResourceSet resourceSet2 = this.InternalGetResourceSet(cultureInfo, true, true);
                if (resourceSet2 == null)
                {
                    break;
                }
                if (resourceSet2 != resourceSet)
                {
                    object object2 = resourceSet2.GetObject(name, this._ignoreCase);
                    if (object2 != null)
                    {
                        if (this._lastUsedResourceCache != null)
{
                            ResourceManager.CultureNameResourceSetPair lastUsedResourceCache = this._lastUsedResourceCache;
                            lock (lastUsedResourceCache)
{
                                this._lastUsedResourceCache.lastCultureName = cultureInfo.Name;
                                this._lastUsedResourceCache.lastResourceSet = resourceSet2;
                            }
                        }
                        UnmanagedMemoryStream unmanagedMemoryStream2 = object2 as UnmanagedMemoryStream;
                        if (unmanagedMemoryStream2 != null && wrapUnmanagedMemStream)
{
                            return new UnmanagedMemoryStreamWrapper(unmanagedMemoryStream2);
                        }
                        return object2;
                    }
                    else
                    {
                        resourceSet = resourceSet2;
                    }
                }
            }
            return null;
        }
References System.Resources.ResourceManager._ignoreCase, System.Resources.ResourceManager._lastUsedResourceCache, System.Resources.ResourceManager._neutralResourcesCulture, System.culture, System.Threading.Thread.CurrentThread, System.Threading.Thread.GetCurrentUICultureNoAppX(), System.Resources.ResourceManager.GetFirstResourceSet(), System.Resources.ResourceSet.GetObject(), System.Resources.ResourceManager.InternalGetResourceSet(), System.name, and System.Globalization.CultureInfo.Name.