Terraria Decompiled: System.Resources.ResourceManager.ResourceManager
ResourceManager() [5/6]
System.Resources.ResourceManager.ResourceManager (Type resourceSource) inline
Definition at line 137 of file ResourceManager.cs.
        {
            if (null == resourceSource)
            {
                throw new ArgumentNullException("resourceSource");
            }
            if (!(resourceSource is RuntimeType))
            {
                throw new ArgumentException(Environment.GetResourceString("Type must be a runtime Type object."));
            }
            this._locationInfo = resourceSource;
            this.MainAssembly = this._locationInfo.Assembly;
            this.BaseNameField = resourceSource.Name;
            this.SetAppXConfiguration();
            this.CommonAssemblyInit();
            try
            {
                this.m_callingAssembly = (RuntimeAssembly)Assembly.GetCallingAssembly();
                if (this.MainAssembly == typeof(object).Assembly && this.m_callingAssembly != this.MainAssembly)
                {
                    this.m_callingAssembly = null;
                }
            }
            catch
            {
            }
        }
References System.Resources.ResourceManager._locationInfo, System.Reflection.Assembly.Assembly(), System.Type.Assembly, System.Resources.ResourceManager.CommonAssemblyInit(), System.Reflection.Assembly.GetCallingAssembly(), System.Environment.GetResourceString(), System.Resources.ResourceManager.MainAssembly, System.Reflection.MemberInfo.Name, and System.Resources.ResourceManager.SetAppXConfiguration().