Terraria Decompiled: System.Resources.ResourceManager.GetSatelliteContractVersion
GetSatelliteContractVersion()
static Version System.Resources.ResourceManager.GetSatelliteContractVersion (Assembly a) inline static protected
Definition at line 494 of file ResourceManager.cs.
        {
            if (a == null)
            {
                throw new ArgumentNullException("a", Environment.GetResourceString("Assembly cannot be null."));
            }
            string text = null;
            if (a.ReflectionOnly)
            {
                foreach (CustomAttributeData customAttributeData in CustomAttributeData.GetCustomAttributes(a))
                {
                    if (customAttributeData.Constructor.DeclaringType == typeof(SatelliteContractVersionAttribute))
                    {
                        text = (string)customAttributeData.ConstructorArguments[0].Value;
                        break;
                    }
                }
                if (text == null)
                {
                    return null;
                }
            }
            else
            {
                object[] customAttributes = a.GetCustomAttributes(typeof(SatelliteContractVersionAttribute), false);
                if (customAttributes.Length == 0)
                {
                    return null;
                }
                text = ((SatelliteContractVersionAttribute)customAttributes[0]).Version;
            }
            Version version;
            try
            {
                version = new Version(text);
            }
            catch (ArgumentOutOfRangeException ex)
            {
                if (a == typeof(object).Assembly)
                {
                    return null;
                }
                throw new ArgumentException(Environment.GetResourceString("Satellite contract version attribute on the assembly '{0}' specifies an invalid version: {1}.", new object[]
                {
                    a.ToString(),
                    text
                }), ex);
            }
            return version;
        }
References System.Reflection.CustomAttributeData.Constructor, System.Reflection.CustomAttributeData.ConstructorArguments, System.Reflection.MemberInfo.DeclaringType, System.Reflection.CustomAttributeData.GetCustomAttributes(), System.Reflection.Assembly.GetCustomAttributes(), System.Environment.GetResourceString(), System.Reflection.Assembly.ReflectionOnly, and System.text.
Referenced by System.Resources.ResourceManager.ResourceManagerMediator.ObtainSatelliteContractVersion().