Terraria Decompiled: System.Resources.ResourceManager.GetFirstResourceSet
GetFirstResourceSet()
ResourceSet System.Resources.ResourceManager.GetFirstResourceSet (CultureInfo culture) inline package
Definition at line 329 of file ResourceManager.cs.
        {
            if (this._neutralResourcesCulture != null && culture.Name == this._neutralResourcesCulture.Name)
            {
                culture = CultureInfo.InvariantCulture;
            }
            if (this._lastUsedResourceCache != null)
            {
                ResourceManager.CultureNameResourceSetPair cultureNameResourceSetPair = this._lastUsedResourceCache;
                lock (cultureNameResourceSetPair)
                {
                    if (culture.Name == this._lastUsedResourceCache.lastCultureName)
                    {
                        return this._lastUsedResourceCache.lastResourceSet;
                    }
                }
            }
            Dictionary<string, ResourceSet> resourceSets = this._resourceSets;
            ResourceSet resourceSet = null;
            if (resourceSets != null)
            {
                Dictionary<string, ResourceSet> dictionary = resourceSets;
                lock (dictionary)
                {
                    resourceSets.TryGetValue(culture.Name, out resourceSet);
                }
            }
            if (resourceSet != null)
            {
                if (this._lastUsedResourceCache != null)
                {
                    ResourceManager.CultureNameResourceSetPair cultureNameResourceSetPair = this._lastUsedResourceCache;
                    lock (cultureNameResourceSetPair)
                    {
                        this._lastUsedResourceCache.lastCultureName = culture.Name;
                        this._lastUsedResourceCache.lastResourceSet = resourceSet;
                    }
                }
                return resourceSet;
            }
            return null;
        }
References System.Resources.ResourceManager._lastUsedResourceCache, System.Resources.ResourceManager._neutralResourcesCulture, System.Resources.ResourceManager._resourceSets, System.culture, System.dictionary, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.CultureInfo.Name, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Resources.ResourceManager.GetObject(), and System.Resources.ResourceManager.GetString().