Terraria Decompiled: System.Resources.ResourceManager.GetResourceSet
GetResourceSet()
virtual ResourceSet System.Resources.ResourceManager.GetResourceSet (CultureInfo culture, bool createIfNotExists, bool tryParents) inline virtual
Definition at line 375 of file ResourceManager.cs.
        {
            if (culture == null)
            {
                throw new ArgumentNullException("culture");
            }
            Dictionary<string, ResourceSet> resourceSets = this._resourceSets;
            if (resourceSets != null)
            {
                Dictionary<string, ResourceSet> dictionary = resourceSets;
                lock (dictionary)
                {
                    ResourceSet resourceSet;
                    if (resourceSets.TryGetValue(culture.Name, out resourceSet))
                    {
                        return resourceSet;
                    }
                }
            }
            StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMyCaller;
            if (this.UseManifest && culture.HasInvariantCultureName)
            {
                string resourceFileName = this.GetResourceFileName(culture);
                Stream manifestResourceStream = ((RuntimeAssembly)this.MainAssembly).GetManifestResourceStream(this._locationInfo, resourceFileName, this.m_callingAssembly == this.MainAssembly, ref stackCrawlMark);
                if (createIfNotExists && manifestResourceStream != null)
                {
                    ResourceSet resourceSet = ((ManifestBasedResourceGroveler)this.resourceGroveler).CreateResourceSet(manifestResourceStream, this.MainAssembly);
                    ResourceManager.AddResourceSet(resourceSets, culture.Name, ref resourceSet);
                    return resourceSet;
                }
            }
            return this.InternalGetResourceSet(culture, createIfNotExists, tryParents);
        }
References System.Resources.ResourceManager._locationInfo, System.Resources.ResourceManager._resourceSets, System.Resources.ResourceManager.AddResourceSet(), System.culture, System.dictionary, System.Resources.ResourceManager.GetResourceFileName(), System.Globalization.CultureInfo.HasInvariantCultureName, System.Resources.ResourceManager.InternalGetResourceSet(), System.Resources.ResourceManager.m_callingAssembly, System.Resources.ResourceManager.MainAssembly, System.Resources.ResourceManager.resourceGroveler, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.Resources.ResourceManager.UseManifest.