Terraria Decompiled: Dav1dfile.Bindings.df_fopen
df_fopen()
static unsafe int Dav1dfile.Bindings.df_fopen (string fname, out IntPtr context) inline static
Definition at line 73 of file Bindings.cs.
        {
            int num;
            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
            {
                num = Bindings.INTERNAL_df_fopen(fname, out context);
            }
            else
            {
                byte* ptr = Bindings.Utf8Encode(fname);
                num = Bindings.INTERNAL_df_fopen(ptr, out context);
                Marshal.FreeHGlobal((IntPtr)((void*)ptr));
            }
            return num;
        }
References System.Runtime.InteropServices.Marshal.FreeHGlobal(), Dav1dfile.Bindings.INTERNAL_df_fopen(), and Dav1dfile.Bindings.Utf8Encode().
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerAV1.Play(), and Microsoft.Xna.Framework.Media.VideoPlayerAV1.ReadInfo().