Terraria Decompiled: System.Runtime.Remoting.Messaging.IllogicalCallContext.CreateCopy
CreateCopy()
IllogicalCallContext System.Runtime.Remoting.Messaging.IllogicalCallContext.CreateCopy () inline
Definition at line 68 of file IllogicalCallContext.cs.
        {
            IllogicalCallContext illogicalCallContext = new IllogicalCallContext();
            illogicalCallContext.HostContext = this.HostContext;
            if (this.HasUserData)
            {
                IDictionaryEnumerator enumerator = this.m_Datastore.GetEnumerator();
                while (enumerator.MoveNext())
                {
                    illogicalCallContext.Datastore[(string)enumerator.Key] = enumerator.Value;
                }
            }
            return illogicalCallContext;
        }
References System.Runtime.Remoting.Messaging.IllogicalCallContext.Datastore, System.Collections.Hashtable.GetEnumerator(), System.Runtime.Remoting.Messaging.IllogicalCallContext.HasUserData, System.Runtime.Remoting.Messaging.IllogicalCallContext.HostContext, System.Runtime.Remoting.Messaging.IllogicalCallContext.IllogicalCallContext(), System.Collections.IDictionaryEnumerator.Key, System.Runtime.Remoting.Messaging.IllogicalCallContext.m_Datastore, System.Collections.IEnumerator.MoveNext(), and System.Collections.IDictionaryEnumerator.Value.
Referenced by System.Threading.ExecutionContext.CreateMutableCopy().