Terraria Decompiled: rail.IRailLeaderboardEntriesImpl.GetLeaderboardEntry
GetLeaderboardEntry()
virtual RailResult rail.IRailLeaderboardEntriesImpl.GetLeaderboardEntry (int index, LeaderboardEntry leaderboard_entry) inline virtual
Implements rail.IRailLeaderboardEntries.
Definition at line 76 of file IRailLeaderboardEntriesImpl.cs.
        {
            IntPtr intPtr = ((leaderboard_entry == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_LeaderboardEntry__SWIG_0());
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailLeaderboardEntries_GetLeaderboardEntry(this.swigCPtr_, index, intPtr);
            }
            finally
            {
                if (leaderboard_entry != null)
                {
                    RailConverter.Cpp2Csharp(intPtr, leaderboard_entry);
                }
                RAIL_API_PINVOKE.delete_LeaderboardEntry(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Cpp2Csharp(), rail.RAIL_API_PINVOKE.delete_LeaderboardEntry(), System.index, rail.RAIL_API_PINVOKE.IRailLeaderboardEntries_GetLeaderboardEntry(), rail.RAIL_API_PINVOKE.new_LeaderboardEntry__SWIG_0(), and System.IntPtr.Zero.