Terraria Decompiled: ReLogic.Content.Sources.XnaDirectContentSource.OpenStream
OpenStream()
Stream ReLogic.Content.Sources.XnaDirectContentSource.OpenStream (string assetName) inline
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 74 of file XnaDirectContentSource.cs.
        {
            string text = Path.Combine(this._rootDirectory, assetName) + ".xnb";
            Stream stream;
            try
            {
                stream = File.OpenRead(text);
            }
            catch (Exception ex)
            {
                throw AssetLoadException.FromMissingAsset(assetName, ex);
            }
            return stream;
        }
References ReLogic.Content.Sources.XnaDirectContentSource._rootDirectory, System.IO.Path.Combine(), ReLogic.Content.AssetLoadException.FromMissingAsset(), System.IO.File.OpenRead(), and System.text.