Terraria Decompiled: System.Runtime.Remoting.Activation.ContextLevelActivator.Activate
Activate()
IConstructionReturnMessage System.Runtime.Remoting.Activation.ContextLevelActivator.Activate (IConstructionCallMessage ctorCall) inline
Implements System.Runtime.Remoting.Activation.IActivator.
Definition at line 43 of file ContextLevelActivator.cs.
        {
            ServerIdentity serverIdentity = RemotingServices.CreateContextBoundObjectIdentity(ctorCall.ActivationType);
            RemotingServices.SetMessageTargetIdentity(ctorCall, serverIdentity);
            ConstructionCall constructionCall = ctorCall as ConstructionCall;
            if (constructionCall == null || !constructionCall.IsContextOk)
            {
                serverIdentity.Context = Context.CreateNewContext(ctorCall);
                Context context = Context.SwitchToContext(serverIdentity.Context);
                try
                {
                    return this.m_NextActivator.Activate(ctorCall);
                }
                finally
                {
                    Context.SwitchToContext(context);
                }
            }
            return this.m_NextActivator.Activate(ctorCall);
        }
References System.Runtime.Remoting.Activation.IActivator.Activate(), System.Runtime.Remoting.Activation.IConstructionCallMessage.ActivationType, System.Runtime.Remoting.ServerIdentity.Context, System.Runtime.Remoting.RemotingServices.CreateContextBoundObjectIdentity(), System.Runtime.Remoting.Contexts.Context.CreateNewContext(), System.Runtime.Remoting.Messaging.ConstructionCall.IsContextOk, System.Runtime.Remoting.Activation.ContextLevelActivator.m_NextActivator, System.Runtime.Remoting.RemotingServices.SetMessageTargetIdentity(), and System.Runtime.Remoting.Contexts.Context.SwitchToContext().