Terraria Decompiled: System.Reflection.EventInfo.CreateAddEventDelegate
CreateAddEventDelegate()
static EventInfo.AddEventAdapter System.Reflection.EventInfo.CreateAddEventDelegate (MethodInfo method) inline static private
Definition at line 237 of file EventInfo.cs.
        {
            Type[] array;
            Type type;
            string text;
            if (method.IsStatic)
            {
                array = new Type[] { method.GetParametersInternal()[0].ParameterType };
                type = typeof(EventInfo.StaticAddEvent<>);
                text = "StaticAddEventAdapterFrame";
            }
            else
            {
                array = new Type[]
                {
                    method.DeclaringType,
                    method.GetParametersInternal()[0].ParameterType
                };
                type = typeof(EventInfo.AddEvent<, >);
                text = "AddEventFrame";
            }
            object obj = Delegate.CreateDelegate(type.MakeGenericType(array), method);
            MethodInfo methodInfo = typeof(EventInfo).GetMethod(text, BindingFlags.Static | BindingFlags.NonPublic);
            methodInfo = methodInfo.MakeGenericMethod(array);
            return (EventInfo.AddEventAdapter)Delegate.CreateDelegate(typeof(EventInfo.AddEventAdapter), obj, methodInfo, true);
        }
References System.Reflection.EventInfo.AddEventAdapter(), System.array, System.Delegate.CreateDelegate(), System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Reflection.MethodBase.GetParametersInternal(), System.Reflection.MethodBase.IsStatic, System.Reflection.MethodInfo.MakeGenericMethod(), System.Type.MakeGenericType(), System.obj, System.Reflection.ParameterInfo.ParameterType, and System.text.
Referenced by System.Reflection.EventInfo.AddEventHandler().