Terraria Decompiled: System.Reflection.EventInfo.AddEventHandler
AddEventHandler()
virtual void System.Reflection.EventInfo.AddEventHandler (object target, Delegate handler) inline virtual
Definition at line 186 of file EventInfo.cs.
        {
            if (this.cached_add_event == null)
            {
                MethodInfo addMethod = this.GetAddMethod();
                if (addMethod == null)
                {
                    throw new InvalidOperationException("Cannot add the event handler since no public add method exists for the event.");
                }
                if (addMethod.DeclaringType.IsValueType)
                {
                    if (target == null && !addMethod.IsStatic)
                    {
                        throw new TargetException("Cannot add a handler to a non static event with a null target");
                    }
                    addMethod.Invoke(target, new object[] { handler });
                    return;
                }
                else
                {
                    this.cached_add_event = EventInfo.CreateAddEventDelegate(addMethod);
                }
            }
            this.cached_add_event(target, handler);
        }
References System.Reflection.EventInfo.cached_add_event, System.Reflection.EventInfo.CreateAddEventDelegate(), System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Reflection.EventInfo.GetAddMethod(), System.Reflection.MethodInfo.Invoke(), System.Reflection.MethodBase.IsStatic, and System.Type.IsValueType.