Terraria Decompiled: System.Threading.Tasks.ValueTask.AsTask
AsTask() [1/2]
Task< TResult > System.Threading.Tasks.ValueTask< TResult >.AsTask () inline
Definition at line 106 of file ValueTask.2.cs.
        {
            object obj = this._obj;
            if (obj == null)
            {
                return AsyncTaskMethodBuilder<TResult>.GetTaskForResult(this._result);
            }
            Task<TResult> task = obj as Task<TResult>;
            if (task != null)
            {
                return task;
            }
            return this.GetTaskForValueTaskSource(Unsafe.As<IValueTaskSource<TResult>>(obj));
        }
References System.Threading.Tasks.ValueTask< TResult >._obj, System.Threading.Tasks.ValueTask< TResult >._result, System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetTaskForResult(), System.Threading.Tasks.ValueTask< TResult >.GetTaskForValueTaskSource(), System.obj, and System.task.
Referenced by System.Threading.Tasks.ValueTask< TResult >.Preserve(), and System.IO.StreamReader.ReadBlockAsync().