Terraria Decompiled: Microsoft.Xna.Framework.MathHelper.Clamp
Clamp() [1/2]
static float Microsoft.Xna.Framework.MathHelper.Clamp (float value, float min, float max) inline static
Definition at line 23 of file MathHelper.cs.
        {
            value = ((value > max) ? max : value);
            value = ((value < min) ? min : value);
            return value;
        }
References System.value.
Referenced by Terraria.Graphics.Capture.CaptureCamera._Capture(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_166_Dove(), Terraria.Projectile.AI_174_MultisegmentPet(), Terraria.Utils.AngleTowards(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_WeatherVane(), Microsoft.Xna.Framework.Input.GamePadThumbSticks.ApplySquareClamp(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.SceneState.ApplyVisuals(), Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColorAlongGradientBasedOnHeight(), Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.Utils.CheckForGoodTeleportationSpot(), Microsoft.Xna.Framework.Vector2.Clamp(), Microsoft.Xna.Framework.Vector3.Clamp(), Microsoft.Xna.Framework.Vector4.Clamp(), Microsoft.Xna.Framework.Vector2.Clamp(), Microsoft.Xna.Framework.Vector3.Clamp(), Microsoft.Xna.Framework.Vector4.Clamp(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Microsoft.Xna.Framework.Color.Color(), Terraria.Utils.ConstrainedToPointInRectangle(), Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.Player.Deserialize(), Terraria.Audio.ActiveSound.DetermineIntendedVolume(), Terraria.GameContent.Golf.FancyGolfPredictionLine.Draw(), Terraria.Mount.Draw(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBackgroundBlackFill(), Terraria.Main.DrawBG_ModifyBGFarBackLayerAlpha(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_6_TileGridOption(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawInvasionProgress(), Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_QueenSlimeWings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ChippysHeadband(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar(), Terraria.Main.DrawProjDirect(), Terraria.UI.ItemSlot.DrawRadialCircular(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Microsoft.Xna.Framework.Input.GamePadTriggers.GamePadTriggers(), Microsoft.Xna.Framework.Input.GamePadTriggers.GamePadTriggers(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnRandomly(), Terraria.WorldGen.GenerateSkyBlockWorld(), Terraria.MessageBuffer.GetData(), Terraria.UI.UIElement.GetDimensionsBasedOnParentDimensions(), Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Terraria.GameContent.Animations.Segments.Panning.GetPanAmount(), Terraria.ID.TorchID.ShimmerTorchLight.GetRGB(), Terraria.Item.GetVisualCritChance(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput(), Terraria.Player.HorizontalMovement(), Terraria.Mount.Hover(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.Projectile.KiteLogic(), Terraria.GameContent.UI.Elements.UIScrollbar.LeftMouseDown(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.GameContent.ShopHelper.LimitAndRoundMultiplier(), Terraria.Player.LoadPlayer_LastMinuteFixes(), Terraria.Main.LoadSettings(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.Player.NebulaLevelup(), Microsoft.Xna.Framework.Media.MediaPlayer.NextSong(), Terraria.Main.OldDrawBackground(), Terraria.GameContent.Golf.GolfHelper.ContactListener.OnCollision(), Microsoft.Xna.Framework.Graphics.PackedVector.Alpha8.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.NormalizedByte2.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.NormalizedShort2.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Rg32.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Short2.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Bgr565.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Bgra4444.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Bgra5551.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Byte4.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.NormalizedByte4.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.NormalizedShort4.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Rgba1010102.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Rgba64.Pack(), Microsoft.Xna.Framework.Graphics.PackedVector.Short4.Pack(), Terraria.Audio.LegacySoundPlayer.PlaySound(), Terraria.GameInput.PlayerInput.PostInput(), Terraria.Graphics.Effects.SkyManager.ProcessCloudAlpha(), Terraria.GameContent.RGB.CavernShader.ProcessHighDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.DD2Shader.ProcessHighDetail(), Terraria.GameContent.RGB.DrowningShader.ProcessHighDetail(), Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail(), Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.PlanteraShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenBeeShader.ProcessHighDetail(), Terraria.GameContent.RGB.SkullShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessHighDetail(), Terraria.GameContent.RGB.VineShader.ProcessHighDetail(), Terraria.GameContent.RGB.WormShader.ProcessHighDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessLowDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessLowDetail(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChangeAndSetSlider(), Terraria.NetMessage.SendData(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadTriggerVibration(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetGamePadTriggerVibration(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadVibration(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetGamePadVibration(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIManageControls.SetupGamepadPoints(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.GameContent.UI.Elements.UIColoredImageButton.SetVisibility(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.Utils.SmoothStep(), Microsoft.Xna.Framework.MathHelper.SmoothStep(), Terraria.Player.Teleport(), Terraria.Player.TorchAttack(), Terraria.Player.TryBouncingBlocks(), Terraria.GameContent.MinecartDiggerHelper.TryDigging(), Terraria.GameContent.RGB.SkyShader.Update(), Terraria.FrameSkipTest.Update(), Terraria.GameContent.Skies.CreditsRollSky.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Update(), Terraria.Graphics.Renderers.GasParticle.Update(), Terraria.Graphics.Renderers.ShockIconParticle.Update(), Terraria.Mount.UpdateEffects(), Terraria.GameContent.BackgroundChangeFlashInfo.UpdateFlashValues(), Terraria.GameContent.Events.Sandstorm.UpdateSeverity(), Terraria.Main.UpdateTime(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo(), and Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects().