Terraria Decompiled: Microsoft.Xna.Framework.MathHelper.WithinEpsilon
WithinEpsilon()
static bool Microsoft.Xna.Framework.MathHelper.WithinEpsilon (float floatA, float floatB) inline static package
Definition at line 135 of file MathHelper.cs.
        {
            return Math.Abs(floatA - floatB) < MathHelper.MachineEpsilonFloat;
        }
References System.Math.Abs(), and Microsoft.Xna.Framework.MathHelper.MachineEpsilonFloat.
Referenced by Microsoft.Xna.Framework.Curve.ComputeTangent(), Microsoft.Xna.Framework.Matrix.Decompose(), Microsoft.Xna.Framework.MathHelper.Hermite(), Microsoft.Xna.Framework.Ray.Intersects(), Microsoft.Xna.Framework.Input.GamePadTriggers.operator==(), Microsoft.Xna.Framework.Graphics.Viewport.Project(), and Microsoft.Xna.Framework.Graphics.Viewport.Unproject().