Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateGet< T >
CreateGet< T >() [1/2]
override Func< T, object > Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateGet< T > (FieldInfo fieldInfo) inline
Definition at line 232 of file DynamicReflectionDelegateFactory.cs.
        {
            if (fieldInfo.IsLiteral)
            {
                object constantValue = fieldInfo.GetValue(null);
                return (T o) => constantValue;
            }
            DynamicMethod dynamicMethod = DynamicReflectionDelegateFactory.CreateDynamicMethod("Get" + fieldInfo.Name, typeof(T), new Type[] { typeof(object) }, fieldInfo.DeclaringType);
            ILGenerator ilgenerator = dynamicMethod.GetILGenerator();
            this.GenerateCreateGetFieldIL(fieldInfo, ilgenerator);
            return (Func<T, object>)dynamicMethod.CreateDelegate(typeof(Func<T, object>));
        }
References System.Reflection.Emit.DynamicMethod.CreateDelegate(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateDynamicMethod(), System.Reflection.MemberInfo.DeclaringType, Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateGetFieldIL(), System.Reflection.Emit.DynamicMethod.GetILGenerator(), System.Reflection.FieldInfo.GetValue(), System.Reflection.FieldInfo.IsLiteral, and System.Reflection.MemberInfo.Name.