Terraria Decompiled: Microsoft.Xna.Framework.MathHelper.Lerp
Lerp()
static float Microsoft.Xna.Framework.MathHelper.Lerp (float value1, float value2, float amount) inline static
Definition at line 63 of file MathHelper.cs.
        {
            return value1 + (value2 - value1) * amount;
        }
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_157_SharpTears(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_171_HallowBossRainbowStreak(), Terraria.Projectile.AI_172_HallowBossRainbowPelletStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_181_FairyQueenRangedItemShot(), Terraria.Projectile.AI_182_FinalFractal(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_196_Petal(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.Utils.AngleLerp(), Terraria.GameContent.Animations.Actions.Players.Fade.ApplyTo(), Terraria.GameContent.Animations.Actions.Sprites.Fade.ApplyTo(), Terraria.SceneState.ApplyVisuals(), Terraria.Graphics.Renderers.FakeFishParticle.BeRepelled(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.CalculateExpirationTime(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.UI.BannerClaimingUI.DrawBannersList_Move(), Terraria.Main.DrawInfernoRings(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_6_TileGridOption(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawKite(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_09_Wings(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_36_CTG(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FairyQueenRangedItemShot(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_StardustGuardianPunching(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.Main.DrawWhip_MeteorWhip(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.Main.DrawWhip_SlimeWhip(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Projectile.FillWhipControlPoints(), Terraria.NPC.FindFrame(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_GetFallbackSpawn(), Terraria.NPC.GetAlpha(), Terraria.Player.GetAnglerReward_Decoration(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Terraria.Projectile.GetLastPrismHue(), Terraria.Mount.GetMinecartMechPoint(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.KiteLogic(), Microsoft.Xna.Framework.Color.Lerp(), Terraria.Utilities.Terraria.Utilities.FloatRange.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Microsoft.Xna.Framework.Vector3.Lerp(), Microsoft.Xna.Framework.Vector4.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Microsoft.Xna.Framework.Vector3.Lerp(), Microsoft.Xna.Framework.Vector4.Lerp(), Terraria.Utils.MultiLerp(), Terraria.TimeLogger.DataSeries.Quantile(), Terraria.GameContent.UI.UIDust.QuickBox(), Terraria.Dust.QuickBox(), Terraria.Utils.Remap(), Terraria.Player.RollerSkateMovement(), Terraria.Main.SetBackColor(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.Graphics.FlameLashDrawer.StripWidth(), Terraria.Graphics.MagicMissileDrawer.StripWidth(), Terraria.Graphics.RainbowRodDrawer.StripWidth(), Terraria.GameContent.LeashedEntities.LeashedKite.Update(), Terraria.GameContent.Shaders.SepiaScreenShaderData.Update(), Terraria.GameContent.UI.States.UIWorldLoad.Update(), Terraria.Main.UpdateAudio(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateInfoFromSliderValueCache(), Terraria.Gore.UpdateLightningBunnySparks(), Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects(), Terraria.Graphics.StormLightningDrawer.WaveTransition(), Terraria.Utils.WrappedLerp(), and Terraria.Player.Yoraiz0rEye().