Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateDefaultConstructorIL
GenerateCreateDefaultConstructorIL()
void Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateDefaultConstructorIL (Type type, ILGenerator generator, Type delegateType) inline private
Definition at line 182 of file DynamicReflectionDelegateFactory.cs.
        {
            if (type.IsValueType())
            {
                generator.DeclareLocal(type);
                generator.Emit(OpCodes.Ldloc_0);
                if (type != delegateType)
                {
                    generator.Emit(OpCodes.Box, type);
                }
            }
            else
            {
                ConstructorInfo constructor = type.GetConstructor(52, null, ReflectionUtils.EmptyTypes, null);
                if (constructor == null)
                {
                    throw new ArgumentException("Could not get constructor for {0}.".FormatWith(CultureInfo.InvariantCulture, type));
                }
                generator.Emit(OpCodes.Newobj, constructor);
            }
            generator.Return();
        }
References System.Reflection.Emit.OpCodes.Box, System.Reflection.Emit.ILGenerator.DeclareLocal(), System.Reflection.Emit.ILGenerator.Emit(), Newtonsoft.Json.Utilities.ReflectionUtils.EmptyTypes, System.Type.GetConstructor(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsValueType, System.Reflection.Emit.OpCodes.Ldloc_0, and System.Reflection.Emit.OpCodes.Newobj.
Referenced by Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateDefaultConstructor< T >().