Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateMethodCallIL
GenerateCreateMethodCallIL()
void Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateMethodCallIL (MethodBase method, ILGenerator generator, int argsIndex) inline private
Definition at line 56 of file DynamicReflectionDelegateFactory.cs.
        {
            ParameterInfo[] parameters = method.GetParameters();
            Label label = generator.DefineLabel();
            generator.Emit(OpCodes.Ldarg, argsIndex);
            generator.Emit(OpCodes.Ldlen);
            generator.Emit(OpCodes.Ldc_I4, parameters.Length);
            generator.Emit(OpCodes.Beq, label);
            generator.Emit(OpCodes.Newobj, typeof(TargetParameterCountException).GetConstructor(ReflectionUtils.EmptyTypes));
            generator.Emit(OpCodes.Throw);
            generator.MarkLabel(label);
            if (!method.IsConstructor && !method.IsStatic)
            {
                generator.PushInstance(method.DeclaringType);
            }
            LocalBuilder localBuilder = generator.DeclareLocal(typeof(IConvertible));
            LocalBuilder localBuilder2 = generator.DeclareLocal(typeof(object));
            for (int i = 0; i < parameters.Length; i++)
            {
                ParameterInfo parameterInfo = parameters[i];
                Type type = parameterInfo.ParameterType;
                if (type.IsByRef)
                {
                    type = type.GetElementType();
                    LocalBuilder localBuilder3 = generator.DeclareLocal(type);
                    if (!parameterInfo.IsOut)
                    {
                        generator.PushArrayInstance(argsIndex, i);
                        if (type.IsValueType())
{
                            Label label2 = generator.DefineLabel();
                            Label label3 = generator.DefineLabel();
                            generator.Emit(OpCodes.Brtrue_S, label2);
                            generator.Emit(OpCodes.Ldloca_S, localBuilder3);
                            generator.Emit(OpCodes.Initobj, type);
                            generator.Emit(OpCodes.Br_S, label3);
                            generator.MarkLabel(label2);
                            generator.PushArrayInstance(argsIndex, i);
                            generator.UnboxIfNeeded(type);
                            generator.Emit(OpCodes.Stloc_S, localBuilder3);
                            generator.MarkLabel(label3);
                        }
                        else
{
                            generator.UnboxIfNeeded(type);
                            generator.Emit(OpCodes.Stloc_S, localBuilder3);
                        }
                    }
                    generator.Emit(OpCodes.Ldloca_S, localBuilder3);
                }
                else if (type.IsValueType())
                {
                    generator.PushArrayInstance(argsIndex, i);
                    generator.Emit(OpCodes.Stloc_S, localBuilder2);
                    Label label4 = generator.DefineLabel();
                    Label label5 = generator.DefineLabel();
                    generator.Emit(OpCodes.Ldloc_S, localBuilder2);
                    generator.Emit(OpCodes.Brtrue_S, label4);
                    LocalBuilder localBuilder4 = generator.DeclareLocal(type);
                    generator.Emit(OpCodes.Ldloca_S, localBuilder4);
                    generator.Emit(OpCodes.Initobj, type);
                    generator.Emit(OpCodes.Ldloc_S, localBuilder4);
                    generator.Emit(OpCodes.Br_S, label5);
                    generator.MarkLabel(label4);
                    if (type.IsPrimitive())
                    {
                        MethodInfo method2 = typeof(IConvertible).GetMethod("To" + type.Name, new Type[] { typeof(IFormatProvider) });
                        if (method2 != null)
{
                            Label label6 = generator.DefineLabel();
                            generator.Emit(OpCodes.Ldloc_S, localBuilder2);
                            generator.Emit(OpCodes.Isinst, type);
                            generator.Emit(OpCodes.Brtrue_S, label6);
                            generator.Emit(OpCodes.Ldloc_S, localBuilder2);
                            generator.Emit(OpCodes.Isinst, typeof(IConvertible));
                            generator.Emit(OpCodes.Stloc_S, localBuilder);
                            generator.Emit(OpCodes.Ldloc_S, localBuilder);
                            generator.Emit(OpCodes.Brfalse_S, label6);
                            generator.Emit(OpCodes.Ldloc_S, localBuilder);
                            generator.Emit(OpCodes.Ldnull);
                            generator.Emit(OpCodes.Callvirt, method2);
                            generator.Emit(OpCodes.Br_S, label5);
                            generator.MarkLabel(label6);
                        }
                    }
                    generator.Emit(OpCodes.Ldloc_S, localBuilder2);
                    generator.UnboxIfNeeded(type);
                    generator.MarkLabel(label5);
                }
                else
                {
                    generator.PushArrayInstance(argsIndex, i);
                    generator.UnboxIfNeeded(type);
                }
            }
            if (method.IsConstructor)
            {
                generator.Emit(OpCodes.Newobj, (ConstructorInfo)method);
            }
            else
            {
                generator.CallMethod((MethodInfo)method);
            }
            Type type2 = (method.IsConstructor ? method.DeclaringType : ((MethodInfo)method).ReturnType);
            if (type2 != typeof(void))
            {
                generator.BoxIfNeeded(type2);
            }
            else
            {
                generator.Emit(OpCodes.Ldnull);
            }
            generator.Return();
        }
References System.Reflection.Emit.OpCodes.Beq, System.Reflection.Emit.OpCodes.Br_S, System.Reflection.Emit.OpCodes.Brfalse_S, System.Reflection.Emit.OpCodes.Brtrue_S, System.Reflection.Emit.OpCodes.Callvirt, System.Reflection.Emit.ILGenerator.DeclareLocal(), System.Reflection.MemberInfo.DeclaringType, System.Reflection.Emit.ILGenerator.DefineLabel(), System.Reflection.Emit.ILGenerator.Emit(), Newtonsoft.Json.Utilities.ReflectionUtils.EmptyTypes, System.Type.GetElementType(), System.Reflection.MethodBase.GetParameters(), System.Reflection.Emit.OpCodes.Initobj, System.Type.IsByRef, System.Reflection.MethodBase.IsConstructor, System.Reflection.Emit.OpCodes.Isinst, System.Reflection.ParameterInfo.IsOut, System.Type.IsPrimitive, System.Reflection.MethodBase.IsStatic, System.Type.IsValueType, System.Reflection.Emit.OpCodes.Ldarg, System.Reflection.Emit.OpCodes.Ldc_I4, System.Reflection.Emit.OpCodes.Ldlen, System.Reflection.Emit.OpCodes.Ldloc_S, System.Reflection.Emit.OpCodes.Ldloca_S, System.Reflection.Emit.OpCodes.Ldnull, System.Reflection.Emit.ILGenerator.MarkLabel(), System.Reflection.MemberInfo.Name, System.Reflection.Emit.OpCodes.Newobj, System.Reflection.ParameterInfo.ParameterType, System.Reflection.Emit.OpCodes.Stloc_S, and System.Reflection.Emit.OpCodes.Throw.
Referenced by Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateMethodCall< T >(), and Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.CreateParameterizedConstructor().