Terraria Decompiled: Interop.ThrowExceptionForIoErrno
ThrowExceptionForIoErrno()
static void Interop.ThrowExceptionForIoErrno (Interop::ErrorInfo errorInfo, string path, bool isDirectory, Func< Interop::ErrorInfo, Interop::ErrorInfo > errorRewriter) inline static private
Definition at line 13 of file Interop.cs.
    {
        if (errorRewriter != null)
        {
            errorInfo = errorRewriter(errorInfo);
        }
        throw Interop.GetExceptionForIoErrno(errorInfo, path, isDirectory);
    }
References GetExceptionForIoErrno().
Referenced by CheckIo(), CheckIo(), and CheckIo< TSafeHandle >().