Terraria Decompiled: Terraria.GameContent.CoinLossRevengeSystem.CacheEnemy
CacheEnemy()
void Terraria.GameContent.CoinLossRevengeSystem.CacheEnemy (NPC npc) inline
Definition at line 61 of file CoinLossRevengeSystem.cs.
        {
            if (npc.boss || (npc.realLife != -1 && npc.realLife != npc.whoAmI) || npc.rarity > 0 || npc.extraValue < CoinLossRevengeSystem.MinimumCoinsForCaching)
            {
                return;
            }
            if (npc.position.X < Main.leftWorld + 640f + 16f || npc.position.X + (float)npc.width > Main.rightWorld - 640f - 32f || npc.position.Y < Main.topWorld + 640f + 16f || npc.position.Y > Main.bottomWorld - 640f - 32f - (float)npc.height)
            {
                return;
            }
            int num = npc.netID;
            int num2;
            if (NPCID.Sets.RespawnEnemyID.TryGetValue(num, out num2))
            {
                num = num2;
            }
            if (num == 0)
            {
                return;
            }
            CoinLossRevengeSystem.RevengeMarker revengeMarker = new CoinLossRevengeSystem.RevengeMarker(npc.Center, num, npc.GetLifePercent(), npc.type, npc.aiStyle, npc.extraValue, npc.value, npc.SpawnedFromStatue, this._gameTime, -1);
            this.AddMarker(revengeMarker);
            if (Main.netMode == 2)
            {
                NetMessage.SendCoinLossRevengeMarker(revengeMarker, -1, -1);
            }
            if (CoinLossRevengeSystem.DisplayCaching)
            {
                Main.NewText("Cached " + npc.GivenOrTypeName, byte.MaxValue, byte.MaxValue, byte.MaxValue);
            }
        }
References Terraria.GameContent.CoinLossRevengeSystem.AddMarker(), Terraria.NPC.aiStyle, Terraria.NPC.boss, Terraria.Main.bottomWorld, Terraria.Entity.Center, Terraria.GameContent.CoinLossRevengeSystem.DisplayCaching, Terraria.NPC.extraValue, Terraria.NPC.GetLifePercent(), Terraria.NPC.GivenOrTypeName, Terraria.Entity.height, Terraria.Main.leftWorld, Terraria.GameContent.CoinLossRevengeSystem.MinimumCoinsForCaching, Terraria.NPC.netID, Terraria.Main.netMode, Terraria.Main.NewText(), Terraria.Entity.position, Terraria.NPC.rarity, Terraria.NPC.realLife, Terraria.ID.NPCID.Sets.RespawnEnemyID, Terraria.Main.rightWorld, Terraria.NetMessage.SendCoinLossRevengeMarker(), Terraria.NPC.SpawnedFromStatue, Terraria.Main.topWorld, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.NPC.type, Terraria.NPC.value, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.CheckActive().