Terraria Decompiled: Terraria.GameContent.CoinLossRevengeSystem.AddMarkerFromReader
AddMarkerFromReader()
void Terraria.GameContent.CoinLossRevengeSystem.AddMarkerFromReader (BinaryReader reader) inline
Definition at line 19 of file CoinLossRevengeSystem.cs.
        {
            int num = reader.ReadInt32();
            Vector2 vector = reader.ReadVector2();
            int num2 = reader.ReadInt32();
            float num3 = reader.ReadSingle();
            int num4 = reader.ReadInt32();
            int num5 = reader.ReadInt32();
            int num6 = reader.ReadInt32();
            float num7 = reader.ReadSingle();
            bool flag = reader.ReadBoolean();
            CoinLossRevengeSystem.RevengeMarker revengeMarker = new CoinLossRevengeSystem.RevengeMarker(vector, num2, num3, num4, num5, num6, num7, flag, this._gameTime, num);
            this.AddMarker(revengeMarker);
        }
References Terraria.GameContent.CoinLossRevengeSystem._gameTime, Terraria.GameContent.CoinLossRevengeSystem.AddMarker(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadInt32(), and System.IO.BinaryReader.ReadSingle().