Terraria Decompiled: Terraria.SceneMetrics.CalculateZones
CalculateZones()
void Terraria.SceneMetrics.CalculateZones () inline private
Definition at line 1363 of file SceneMetrics.cs.
        {
            Tile tileSafely = Framing.GetTileSafely(this.TileCenter);
            this.BehindBackwall = tileSafely.wall > 0;
            this.ZoneSkyHeight = (double)this.TileCenter.Y <= Main.worldSurface * 0.3499999940395355;
            this.ZoneOverworldHeight = (double)this.TileCenter.Y <= Main.worldSurface && (double)this.TileCenter.Y > Main.worldSurface * 0.3499999940395355;
            this.BelowSurface = (double)this.TileCenter.Y > Main.worldSurface;
            this.ZoneDirtLayerHeight = (double)this.TileCenter.Y <= Main.rockLayer && (double)this.TileCenter.Y > Main.worldSurface;
            this.ZoneRockLayerHeight = this.TileCenter.Y <= Main.UnderworldLayer && (double)this.TileCenter.Y > Main.rockLayer;
            this.ZoneUnderworldHeight = this.TileCenter.Y > Main.UnderworldLayer;
            this.ZoneCorrupt = this.EnoughTilesForCorruption;
            this.ZoneCrimson = this.EnoughTilesForCrimson;
            this.ZoneHallow = this.EnoughTilesForHallow;
            this.ZoneJungle = this.EnoughTilesForJungle && !this.ZoneUnderworldHeight;
            this.ZoneSnow = this.EnoughTilesForSnow;
            this.ZoneDesert = this.EnoughTilesForDesert;
            this.ZoneGlowshroom = this.EnoughTilesForGlowingMushroom;
            this.ZoneMeteor = this.EnoughTilesForMeteor;
            this.ZoneGraveyard = this.EnoughTilesForGraveyard;
            this.ZoneDungeon = this.EnoughTilesForDungeon && this.BelowSurface && Main.wallDungeon[(int)tileSafely.wall];
            this.ZoneLihzhardTemple = tileSafely.wall == 87;
            this.ZoneGranite = tileSafely.wall == 184 || tileSafely.wall == 180;
            this.ZoneMarble = tileSafely.wall == 183 || tileSafely.wall == 178;
            this.ZoneHive = tileSafely.wall == 108 || tileSafely.wall == 86;
            this.ZoneGemCave = tileSafely.wall >= 48 && tileSafely.wall <= 53;
            this.ZoneBeach = WorldGen.oceanDepths(this.TileCenter.X, this.TileCenter.Y);
            this.ZoneUndergroundDesert = this.ZoneDesert && this.BelowSurface && (WallID.Sets.Conversion.Sandstone[(int)tileSafely.wall] || WallID.Sets.Conversion.HardenedSand[(int)tileSafely.wall] || tileSafely.wall == 223) && !Main.wallHouse[(int)tileSafely.wall];
            this.SurfaceAtmospherics = WorldGen.IsSurfaceForAtmospherics(this.TileCenter);
            if (Main.remixWorld && this.ZoneDungeon)
            {
                this.SurfaceAtmospherics = false;
            }
            this.ZoneRain = Main.raining && this.SurfaceAtmospherics;
            this.ZoneSandstorm = this.ZoneDesert && this.SurfaceAtmospherics && Sandstorm.Happening;
            if (this.ZoneSandstorm)
            {
                this.ZoneRain = false;
            }
            this.UndergroundForShimmering = (double)this.TileCenter.Y > Main.worldSurface + 84.0 && this.TileCenter.Y < Main.maxTilesY - 396;
            this.ZoneShimmer = this.EnoughTilesForShimmer && this.UndergroundForShimmering && !this.ZoneDungeon;
            this.ZoneWaterCandle = this.WaterCandleCount > 0;
            this.ZonePeaceCandle = this.PeaceCandleCount > 0;
            this.ZoneShadowCandle = this.ShadowCandleCount > 0;
            if (Main.dualDungeonsSeed && this.BelowSurface && !this.ZoneUnderworldHeight)
            {
                NPCSpawningFlagsForDualDungeons npcspawningFlagsForDualDungeons = default(NPCSpawningFlagsForDualDungeons);
                Point point = new Point(this.TileCenter.X, this.TileCenter.Y);
                int num = 0;
                int num2 = 0;
                for (int i = 0; i < 300; i++)
                {
                    Tile tileSafely2 = Framing.GetTileSafely(point);
                    if (npcspawningFlagsForDualDungeons.CanScan(tileSafely2) && npcspawningFlagsForDualDungeons.ScanZonesFor(true, point.X, point.Y, (int)tileSafely2.type, (int)tileSafely2.wall, true))
                    {
                        Tile tileSafely3 = Framing.GetTileSafely(new Point(point.X, point.Y - 1));
                        num = (int)tileSafely2.type;
                        num2 = (int)tileSafely3.wall;
                        break;
                    }
                    point.Y++;
                }
                npcspawningFlagsForDualDungeons.ScanZonesFor(false, point.X, point.Y, num, num2, true);
                this.ZoneDungeon = npcspawningFlagsForDualDungeons.ZoneDungeon;
                this.ZoneSnow = npcspawningFlagsForDualDungeons.ZoneSnow;
                this.ZoneGlowshroom = npcspawningFlagsForDualDungeons.ZoneGlowshroom;
                this.ZoneCorrupt = npcspawningFlagsForDualDungeons.ZoneCorrupt;
                this.ZoneCrimson = npcspawningFlagsForDualDungeons.ZoneCrimson;
                this.ZoneJungle = npcspawningFlagsForDualDungeons.ZoneJungle;
                this.ZoneHallow = npcspawningFlagsForDualDungeons.ZoneHallow;
                this.ZoneLihzhardTemple = npcspawningFlagsForDualDungeons.ZoneLihzhardTemple;
                this.ZoneUndergroundDesert = npcspawningFlagsForDualDungeons.ZoneUndergroundDesert;
            }
        }
References Terraria.NPCSpawningFlagsForDualDungeons.CanScan(), Terraria.Main.dualDungeonsSeed, Terraria.SceneMetrics.EnoughTilesForCorruption, Terraria.SceneMetrics.EnoughTilesForCrimson, Terraria.SceneMetrics.EnoughTilesForDesert, Terraria.SceneMetrics.EnoughTilesForGlowingMushroom, Terraria.SceneMetrics.EnoughTilesForGraveyard, Terraria.SceneMetrics.EnoughTilesForHallow, Terraria.SceneMetrics.EnoughTilesForMeteor, Terraria.SceneMetrics.EnoughTilesForSnow, Terraria.Framing.GetTileSafely(), Terraria.GameContent.Events.Sandstorm.Happening, Terraria.ID.WallID.Sets.Conversion.HardenedSand, int, Terraria.WorldGen.IsSurfaceForAtmospherics(), Terraria.Main.maxTilesY, Terraria.WorldGen.oceanDepths(), Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.ID.WallID.Sets.Conversion.Sandstone, Terraria.NPCSpawningFlagsForDualDungeons.ScanZonesFor(), Terraria.SceneMetrics.SurfaceAtmospherics, Terraria.SceneMetrics.TileCenter, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.Main.wallHouse, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, Terraria.NPCSpawningFlagsForDualDungeons.ZoneCorrupt, Terraria.NPCSpawningFlagsForDualDungeons.ZoneCrimson, Terraria.NPCSpawningFlagsForDualDungeons.ZoneDungeon, Terraria.SceneMetrics.ZoneDungeon, Terraria.NPCSpawningFlagsForDualDungeons.ZoneGlowshroom, Terraria.NPCSpawningFlagsForDualDungeons.ZoneHallow, Terraria.NPCSpawningFlagsForDualDungeons.ZoneJungle, Terraria.NPCSpawningFlagsForDualDungeons.ZoneLihzhardTemple, Terraria.SceneMetrics.ZoneSandstorm, Terraria.NPCSpawningFlagsForDualDungeons.ZoneSnow, Terraria.NPCSpawningFlagsForDualDungeons.ZoneUndergroundDesert, and Terraria.SceneMetrics.ZoneUnderworldHeight.
Referenced by Terraria.SceneMetrics.Scan().