Terraria Decompiled: Terraria.SceneMetrics.ScanNPCPositions
ScanNPCPositions()
void Terraria.SceneMetrics.ScanNPCPositions () inline private
Definition at line 1438 of file SceneMetrics.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc.active)
                {
                    Vector2 vector = this.ClosestNPCPosition[npc.type];
                    if (vector == Vector2.Zero || Vector2.DistanceSquared(this.Center, npc.Center) < Vector2.DistanceSquared(this.Center, vector))
                    {
                        this.ClosestNPCPosition[npc.type] = npc.Center;
                    }
                    if (npc.townNPC && Utils.CenteredRectangle(this.Center, SceneMetrics.TownNPCRectSize).Contains(npc.Center.ToPoint()))
                    {
                        int townNPCCount = this.TownNPCCount;
                        this.TownNPCCount = townNPCCount + 1;
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.SceneMetrics.ClosestNPCPosition, Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Vector2.DistanceSquared(), Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.NPC.townNPC, Terraria.SceneMetrics.TownNPCCount, Terraria.SceneMetrics.TownNPCRectSize, Terraria.NPC.type, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.SceneMetrics.Scan().