Terraria Decompiled: Terraria.SceneMetrics.Scan
Scan()
void Terraria.SceneMetrics.Scan (SceneMetricsScanSettings settings) inline
Definition at line 994 of file SceneMetrics.cs.
        {
            if (this.LastScanTime == Main.GameUpdateCount && this.Center == settings.BiomeScanCenterPositionInWorld)
            {
                return;
            }
            this.Reset();
            this.LastScanTime = Main.GameUpdateCount;
            this.Center = settings.BiomeScanCenterPositionInWorld;
            this.TileCenter = this.Center.ToTileCoordinates().ClampedInWorld(0);
            this.ScanTiles();
            if (settings.VisualScanArea != null)
            {
                this.ScanOnScreenTiles(settings.VisualScanArea.Value);
            }
            if (settings.ScanNPCPositions)
            {
                this.ScanNPCPositions();
            }
            this.AggregateTileCounts();
            this.CalculateZones();
            if (settings.PerspectivePlayer != null)
            {
                this.AddPlayerEffects(settings.PerspectivePlayer);
            }
            this.CanPlayCreditsRoll = this.ActiveMusicBox == 85;
        }
References Terraria.SceneMetrics.AddPlayerEffects(), Terraria.SceneMetrics.AggregateTileCounts(), Terraria.SceneMetricsScanSettings.BiomeScanCenterPositionInWorld, Terraria.SceneMetrics.CalculateZones(), Terraria.SceneMetrics.Center, Terraria.Main.GameUpdateCount, Terraria.SceneMetrics.LastScanTime, Terraria.SceneMetricsScanSettings.PerspectivePlayer, Terraria.SceneMetrics.Reset(), Terraria.SceneMetrics.ScanNPCPositions(), Terraria.SceneMetricsScanSettings.ScanNPCPositions, Terraria.SceneMetrics.ScanOnScreenTiles(), Terraria.SceneMetrics.ScanTiles(), and Terraria.SceneMetricsScanSettings.VisualScanArea.
Referenced by Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.Main.UpdateSceneMetrics(), and Terraria.Player.UpdateSceneMetrics().