Terraria Decompiled: Terraria.SceneMetrics.ScanOnScreenTiles
ScanOnScreenTiles()
void Terraria.SceneMetrics.ScanOnScreenTiles (Rectangle visualScanArea) inline private
Definition at line 1128 of file SceneMetrics.cs.
        {
            visualScanArea = WorldUtils.ClampToWorld(visualScanArea, 0);
            for (int i = visualScanArea.Left; i < visualScanArea.Right; i++)
            {
                for (int j = visualScanArea.Top; j < visualScanArea.Bottom; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active())
                    {
                        if (tile.type == 104)
{
                            this.HasClock = true;
                        }
                        ushort type = tile.type;
                        if (type <= 509)
{
                            if (type <= 207)
{
                                if (type != 139)
{
                                    if (type == 207)
{
                                        if (tile.frameY >= 72)
{
                                            switch (tile.frameX / 36)
{
                                            case 0:
                                                this.ActiveFountainColor = 0;
                                                break;
                                            case 1:
                                                this.ActiveFountainColor = 12;
                                                break;
                                            case 2:
                                                this.ActiveFountainColor = 3;
                                                break;
                                            case 3:
                                                this.ActiveFountainColor = 5;
                                                break;
                                            case 4:
                                                this.ActiveFountainColor = 2;
                                                break;
                                            case 5:
                                                this.ActiveFountainColor = 10;
                                                break;
                                            case 6:
                                                this.ActiveFountainColor = 4;
                                                break;
                                            case 7:
                                                this.ActiveFountainColor = 9;
                                                break;
                                            case 8:
                                                this.ActiveFountainColor = 8;
                                                break;
                                            case 9:
                                                this.ActiveFountainColor = 6;
                                                break;
                                            default:
                                                this.ActiveFountainColor = -1;
                                                break;
                                            }
                                        }
                                    }
                                }
                                else if (tile.frameX >= 36)
{
                                    int num = (int)(tile.frameY / 36);
                                    if (num == 100)
{
                                        this.MusicBoxSilence = true;
                                    }
                                    else
{
                                        this.ActiveMusicBox = num;
                                    }
                                }
                            }
                            else if (type != 410)
{
                                if (type != 480)
{
                                    if (type == 509)
{
                                        if (tile.frameY >= 56)
{
                                            this.ActiveMonolithType = 4;
                                        }
                                    }
                                }
                                else if (tile.frameY >= 54)
{
                                    this.BloodMoonMonolith = true;
                                }
                            }
                            else if (tile.frameY >= 56)
{
                                int num2 = (int)(tile.frameX / 36);
                                this.ActiveMonolithType = num2;
                            }
                        }
                        else if (type <= 720)
{
                            if (type != 657)
{
                                if (type != 658)
{
                                    if (type == 720)
{
                                        if (tile.frameY >= 54)
{
                                            this.CRTMonolith = true;
                                        }
                                    }
                                }
                                else
{
                                    int num3 = (int)(tile.frameY / 54);
                                    this.ShimmerMonolithState = num3;
                                }
                            }
                            else if (tile.frameY >= 54)
{
                                this.EchoMonolith = true;
                            }
                        }
                        else if (type != 721)
{
                            if (type != 725)
{
                                if (type == 733)
{
                                    if (tile.frameY >= 54)
{
                                        this.RadioThingMonolith = true;
                                    }
                                }
                            }
                            else if (tile.frameY >= 54)
{
                                this.NoirMonolith = true;
                            }
                        }
                        else if (tile.frameY >= 54)
{
                            this.RetroMonolith = true;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Microsoft.Xna.Framework.Rectangle.Left, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, and Terraria.Tile.type.
Referenced by Terraria.SceneMetrics.Scan().