Terraria Decompiled: Terraria.SceneMetrics.ScanTiles
ScanTiles()
void Terraria.SceneMetrics.ScanTiles () inline private
Definition at line 1023 of file SceneMetrics.cs.
        {
            Rectangle rectangle = Utils.CenteredRectangle(this.TileCenter, SceneMetrics.ZoneScanSize);
            rectangle = WorldUtils.ClampToWorld(rectangle, 0);
            for (int i = rectangle.Left; i < rectangle.Right; i++)
            {
                for (int j = rectangle.Top; j < rectangle.Bottom; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null)
                    {
                        if (!tile.active())
{
                            if (tile.liquid > 0)
{
                                this._liquidCounts[(int)tile.liquidType()]++;
                            }
                        }
                        else
{
                            this._tileCounts[(int)tile.type]++;
                            if (TileID.Sets.isDesertBiomeSand[(int)tile.type] && WorldGen.oceanDepths(i, j))
{
                                int num = this.OceanSandTileCount;
                                this.OceanSandTileCount = num + 1;
                            }
                            if (TileID.Sets.Campfires[(int)tile.type] && tile.frameY < 36)
{
                                this.HasCampfire = true;
                            }
                            if (tile.type == 49 && tile.frameX < 18)
{
                                int num = this.WaterCandleCount;
                                this.WaterCandleCount = num + 1;
                            }
                            if (tile.type == 372 && tile.frameX < 18)
{
                                int num = this.PeaceCandleCount;
                                this.PeaceCandleCount = num + 1;
                            }
                            if (tile.type == 646 && tile.frameX < 18)
{
                                int num = this.ShadowCandleCount;
                                this.ShadowCandleCount = num + 1;
                            }
                            if (tile.type == 405 && tile.frameX < 54)
{
                                this.HasCampfire = true;
                            }
                            if (tile.type == 506 && tile.frameX < 72)
{
                                this.HasCatBast = true;
                            }
                            if (tile.type == 42 && tile.frameY >= 324 && tile.frameY <= 358)
{
                                this.HasHeartLantern = true;
                            }
                            if (tile.type == 42 && tile.frameY >= 252 && tile.frameY <= 286)
{
                                this.HasStarInBottle = true;
                            }
                            if (tile.type == 91)
{
                                int num2 = (int)(tile.frameX / 18);
                                for (short num3 = tile.frameY; num3 >= 54; num3 -= 54)
{
                                    num2 += 111;
                                }
                                bool flag = false;
                                if ((tile.frameX < 396 && tile.frameY < 54) || num2 == 311 || num2 == 312)
{
                                    flag = true;
                                }
                                if (!flag)
{
                                    int num4 = (int)(tile.frameX / 18 - 21);
                                    for (int k = (int)tile.frameY; k >= 54; k -= 54)
{
                                        num4 += 90;
                                        num4 += 21;
                                    }
                                    if (num2 >= 311)
{
                                        num4--;
                                    }
                                    if (num2 >= 312)
{
                                        num4--;
                                    }
                                    int num5 = BannerSystem.BannerToItem(num4);
                                    if (ItemID.Sets.BannerStrength.IndexInRange(num5) && ItemID.Sets.BannerStrength[num5].Enabled)
{
                                        this.NPCBannerBuff[num4] = true;
                                        this.hasBanner = true;
                                    }
                                }
                            }
                            this.UpdateOreFinder(new Point(i, j), tile);
                        }
                    }
                }
            }
        }
References Terraria.SceneMetrics._liquidCounts, Terraria.SceneMetrics._tileCounts, Terraria.Tile.active(), Terraria.ID.ItemID.Sets.BannerStrength, Terraria.GameContent.BannerSystem.BannerToItem(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.ID.TileID.Sets.Campfires, Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.ID.TileID.Sets.isDesertBiomeSand, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.SceneMetrics.NPCBannerBuff, Terraria.WorldGen.oceanDepths(), Terraria.SceneMetrics.OceanSandTileCount, Terraria.SceneMetrics.PeaceCandleCount, Microsoft.Xna.Framework.Rectangle.Right, Terraria.SceneMetrics.ShadowCandleCount, Terraria.Main.tile, Terraria.SceneMetrics.TileCenter, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.type, Terraria.SceneMetrics.UpdateOreFinder(), Terraria.SceneMetrics.WaterCandleCount, and Terraria.SceneMetrics.ZoneScanSize.
Referenced by Terraria.SceneMetrics.Scan().