Terraria Decompiled: Terraria.SceneMetrics.Reset
Reset()
void Terraria.SceneMetrics.Reset () inline
Definition at line 1496 of file SceneMetrics.cs.
        {
            this.LastScanTime = uint.MaxValue;
            Array.Clear(this._tileCounts, 0, this._tileCounts.Length);
            Array.Clear(this._liquidCounts, 0, this._liquidCounts.Length);
            Array.Clear(this.ClosestNPCPosition, 0, this.ClosestNPCPosition.Length);
            this.SandTileCount = 0;
            this.EvilTileCount = 0;
            this.BloodTileCount = 0;
            this.GraveyardTileCount = 0;
            this.DesertSandTileCount = 0;
            this.MushroomTileCount = 0;
            this.SnowTileCount = 0;
            this.HolyTileCount = 0;
            this.HoneyBlockCount = 0;
            this.ShimmerTileCount = 0;
            this.MeteorTileCount = 0;
            this.JungleTileCount = 0;
            this.DungeonTileCount = 0;
            this.OceanSandTileCount = 0;
            this.HasCampfire = false;
            this.HasSunflower = false;
            this.HasGardenGnome = false;
            this.HasStarInBottle = false;
            this.HasHeartLantern = false;
            this.HasClock = false;
            this.HasCatBast = false;
            this.ActiveMusicBox = -1;
            this.MusicBoxSilence = false;
            this.WaterCandleCount = 0;
            this.PeaceCandleCount = 0;
            this.ShadowCandleCount = 0;
            this.ActiveFountainColor = -1;
            this.ActiveMonolithType = -1;
            this.PartyMonolithCount = 0;
            this.BloodMoonMonolith = false;
            this.MoonLordMonolith = false;
            this.EchoMonolith = false;
            this.ShimmerMonolithState = 0;
            this.CRTMonolith = false;
            this.RetroMonolith = false;
            this.NoirMonolith = false;
            this.RadioThingMonolith = false;
            this.BehindBackwall = false;
            this.BelowSurface = false;
            this.ZoneSkyHeight = false;
            this.ZoneOverworldHeight = false;
            this.ZoneDirtLayerHeight = false;
            this.ZoneRockLayerHeight = false;
            this.ZoneUnderworldHeight = false;
            this.ZoneCorrupt = false;
            this.ZoneCrimson = false;
            this.ZoneHallow = false;
            this.ZoneJungle = false;
            this.ZoneSnow = false;
            this.ZoneDesert = false;
            this.ZoneGlowshroom = false;
            this.ZoneMeteor = false;
            this.ZoneGraveyard = false;
            this.ZoneDungeon = false;
            this.ZoneLihzhardTemple = false;
            this.ZoneGranite = false;
            this.ZoneMarble = false;
            this.ZoneHive = false;
            this.ZoneGemCave = false;
            this.ZoneBeach = false;
            this.ZoneUndergroundDesert = false;
            this.SurfaceAtmospherics = false;
            this.ZoneRain = false;
            this.ZoneSandstorm = false;
            this.UndergroundForShimmering = false;
            this.ZoneShimmer = false;
            this.ZoneWaterCandle = false;
            this.ZonePeaceCandle = false;
            this.ZoneShadowCandle = false;
            this.InTorchGodMinigame = false;
            Array.Clear(this.NPCBannerBuff, 0, this.NPCBannerBuff.Length);
            this.hasBanner = false;
            this.CanPlayCreditsRoll = false;
            this.BestOreType = -1;
            this.BestOrePosition = default(Point);
            this._bestOreDistSq = int.MaxValue;
            this.TownNPCCount = 0;
            this.PerspectivePlayer = SceneMetrics._dummyPlayer;
        }
References Terraria.SceneMetrics._dummyPlayer, Terraria.SceneMetrics._liquidCounts, Terraria.SceneMetrics._tileCounts, System.Array.Clear(), Terraria.SceneMetrics.ClosestNPCPosition, Microsoft.Xna.Framework.Vector2.Length(), and Terraria.SceneMetrics.NPCBannerBuff.
Referenced by Terraria.Main.DrawMenu(), Terraria.SceneMetrics.Scan(), and Terraria.SceneMetrics.SceneMetrics().