Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.OnPassCompleted
OnPassCompleted()
void Terraria.WorldBuilding.WorldGenerator.Controller.OnPassCompleted () inline package
Definition at line 425 of file WorldGenerator.cs.
            {
                int num = WorldGenerator.PassResults.Count - 1;
                GenPassResult genPassResult = WorldGenerator.PassResults[num];
                WorldGenSnapshot snapshot = this.GetSnapshot(this.CurrentPass);
                GenPass genPass = this.Passes.Skip(WorldGenerator.PassResults.Count).FirstOrDefault<GenPass>();
                if (UIWorldGenDebug.ActiveInstance != null || genPass == null)
                {
                    genPassResult.Hash = new uint?(WorldGenerator.HashWorld());
                }
                Trace.WriteLine(genPassResult);
                foreach (GenPass genPass2 in this.Passes.Skip(num))
                {
                    WorldGenSnapshot snapshot2 = this.GetSnapshot(genPass2);
                    if (snapshot2 != null && !snapshot2.GenPassResults[num].Matches(genPassResult))
                    {
                        this._snapshots.Remove(genPass2);
                    }
                }
                bool flag = this.SnapshotFrequency == WorldGenerator.SnapshotFrequency.Always || (this.SnapshotFrequency == WorldGenerator.SnapshotFrequency.Automatic && (this.MsSinceLastSnapshot() > 500 || (genPass != null && genPass == this.PauseAfterPass)));
                if (genPassResult.Skipped)
                {
                    flag = false;
                }
                if (this.QueuedAbort)
                {
                    flag = false;
                }
                if (snapshot != null && snapshot.IsValidHistoryOf(WorldGen.Manifest))
                {
                    flag = false;
                    if (snapshot.Outdated)
                    {
                        snapshot.ResaveForCurrentVersion();
                    }
                }
                if (flag)
                {
                    this.TryCreateSnapshot();
                }
                this.CheckLatestPassResultAgainstManifest(num, genPassResult, snapshot);
                if (this.PauseAfterPass == this.CurrentPass)
                {
                    this.Paused = true;
                }
                if (!Main.gameMenu)
                {
                    Main.QueueMainThreadAction(new Action(Main.sectionManager.SetAllFramedSectionsAsNeedingRefresh));
                }
            }
References Terraria.WorldBuilding.WorldGenerator.Controller._snapshots, System.Action(), Terraria.GameContent.UI.States.UIWorldGenDebug.ActiveInstance, Terraria.WorldBuilding.WorldGenerator.Controller.CheckLatestPassResultAgainstManifest(), Terraria.WorldBuilding.WorldGenerator.Controller.CurrentPass, Terraria.Main.gameMenu, Terraria.WorldBuilding.WorldGenSnapshot.GenPassResults, Terraria.WorldBuilding.WorldGenerator.Controller.GetSnapshot(), Terraria.WorldBuilding.WorldGenerator.HashWorld(), Terraria.WorldGen.Manifest, Terraria.WorldBuilding.WorldGenerator.Controller.MsSinceLastSnapshot(), Terraria.WorldBuilding.WorldGenerator.PassResults, Terraria.WorldBuilding.WorldGenerator.Controller.PauseAfterPass, Terraria.WorldBuilding.WorldGenerator.Controller.QueuedAbort, Terraria.Main.QueueMainThreadAction(), Terraria.Main.sectionManager, Terraria.WorldSections.SetAllFramedSectionsAsNeedingRefresh(), System.Trace, and Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot().