Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.TryRunToEndOfPass
TryRunToEndOfPass()
bool Terraria.WorldBuilding.WorldGenerator.Controller.TryRunToEndOfPass (GenPass pass, bool useSnapshots = true, bool mustRunPass = true) inline
Definition at line 636 of file WorldGenerator.cs.
            {
                if (!pass.Enabled)
                {
                    return false;
                }
                int passIndex = this.Passes.IndexOf(pass);
                Func<GenPass, bool> <>9__1;
                if (this.TryOperateInControlLock(delegate
                {
                    IEnumerable<GenPass> enumerable = this.Passes.Take(passIndex + (mustRunPass ? 0 : 1)).Reverse<GenPass>();
                    Func<GenPass, bool> func;
                    if ((func = <>9__1) == null)
                    {
                        func = (<>9__1 = (GenPass p) => this.GetSnapshot(p) != null && !this.GetSnapshot(p).Outdated);
                    }
                    GenPass genPass = enumerable.FirstOrDefault(func);
                    bool flag = passIndex < WorldGenerator.PassResults.Count;
                    if (useSnapshots && genPass != null && (flag || this.Passes.IndexOf(genPass) >= WorldGenerator.PassResults.Count))
                    {
                        this.TryResetToSnapshot(genPass);
                    }
                    else if (flag)
                    {
                        this.TryReset();
                    }
                    if (WorldGenerator.PassResults.Count == passIndex + 1)
                    {
                        this.Paused = true;
                        return;
                    }
                    this.PauseAfterPass = pass;
                    this.Paused = false;
                }))
                {
                    return true;
                }
                if (pass == this.CurrentPass || passIndex > WorldGenerator.PassResults.Count)
                {
                    this.PauseAfterPass = pass;
                    return true;
                }
                return false;
            }
References Terraria.WorldBuilding.WorldGenerator.Controller.CurrentPass, Terraria.WorldBuilding.GenPass.Enabled, Terraria.WorldBuilding.WorldGenerator.Controller.GetSnapshot(), Terraria.WorldBuilding.WorldGenSnapshot.Outdated, Terraria.WorldBuilding.WorldGenerator.PassResults, Terraria.WorldBuilding.WorldGenerator.Controller.TryOperateInControlLock(), Terraria.WorldBuilding.WorldGenerator.Controller.TryReset(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryResetToSnapshot().
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.TryResetToPreviousPass().