Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.SetGenerator
SetGenerator()
void Terraria.WorldBuilding.WorldGenerator.Controller.SetGenerator (WorldGenerator generator) inline package
Definition at line 391 of file WorldGenerator.cs.
            {
                this._generator = generator;
                this._snapshots = WorldGenSnapshot.LoadSnapshots(this._previousManifest, this.Passes);
                if (this._previousManifest != null)
                {
                    using (IEnumerator<GenPassResult> enumerator = this._previousManifest.GenPassResults.Where((GenPassResult r) => r.Skipped).GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            GenPassResult r = enumerator.Current;
                            GenPass genPass = this.Passes.SingleOrDefault((GenPass p) => p.Name == r.Name);
                            if (genPass != null)
{
                                genPass.Disable();
                            }
                        }
                    }
                }
                if (this.OnPassesLoaded != null)
                {
                    this.OnPassesLoaded(this);
                }
            }
References Terraria.WorldBuilding.WorldGenerator.Controller._previousManifest, System.Collections.Generic.IEnumerator< out T >.Current, Terraria.WorldBuilding.GenPass.Disable(), Terraria.WorldBuilding.WorldManifest.GenPassResults, Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots(), System.Collections.IEnumerator.MoveNext(), Terraria.WorldBuilding.GenPassResult.Name, Terraria.WorldBuilding.WorldGenerator.Controller.OnPassesLoaded, and Terraria.WorldBuilding.GenPassResult.Skipped.