Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.UpdatePreviousManifest
UpdatePreviousManifest()
void Terraria.WorldBuilding.WorldGenerator.Controller.UpdatePreviousManifest () inline private
Definition at line 608 of file WorldGenerator.cs.
            {
                if (this._previousManifest == null || WorldGenerator.PassResults.Count > this._previousManifest.GenPassResults.Count)
                {
                    this._previousManifest = WorldGen.Manifest;
                }
            }
References Terraria.WorldBuilding.WorldGenerator.Controller._previousManifest, Terraria.WorldGen.Manifest, and Terraria.WorldBuilding.WorldGenerator.PassResults.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__46_0(), Terraria.WorldBuilding.WorldGenerator.Controller.TryReset(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryResetToSnapshot().