Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.CheckLatestPassResultAgainstManifest
CheckLatestPassResultAgainstManifest()
void Terraria.WorldBuilding.WorldGenerator.Controller.CheckLatestPassResultAgainstManifest (int currentPassIndex, GenPassResult result, WorldGenSnapshot prevSnapshot) inline private
Definition at line 477 of file WorldGenerator.cs.
            {
                if (this._previousManifest == null)
                {
                    return;
                }
                if (currentPassIndex >= this._previousManifest.GenPassResults.Count)
                {
                    return;
                }
                if (this._previousManifest.GenPassResults[currentPassIndex].Matches(result))
                {
                    return;
                }
                this._previousManifest = null;
                string text = string.Format("{0} output changed since last gen.", this.CurrentPass.Name);
                if (this.PauseOnHashMismatch && prevSnapshot != null)
                {
                    try
                    {
                        prevSnapshot.Load();
                        this.ReportException(text + " The previous output has been loaded as a snapshot (use /swap and /snapshotdiff to compare)", null);
                        goto IL_0096;
                    }
                    catch (Exception ex)
                    {
                        this.ReportException(text + "An attempt was made to load a snapshot of the previous output, but an exception occurred", ex);
                        goto IL_0096;
                    }
                }
                this.ReportException(text, null);
                IL_0096:
                if (this.PauseOnHashMismatch)
                {
                    this.Paused = true;
                    this.PausedDueToHashMismatch = true;
                }
            }
References Terraria.WorldBuilding.WorldGenerator.Controller._previousManifest, Terraria.WorldBuilding.WorldGenerator.Controller.CurrentPass, Terraria.WorldBuilding.WorldManifest.GenPassResults, Terraria.WorldBuilding.WorldGenSnapshot.Load(), Terraria.WorldBuilding.GenPass.Name, Terraria.WorldBuilding.WorldGenerator.Controller.PauseOnHashMismatch, Terraria.WorldBuilding.WorldGenerator.Controller.ReportException(), and System.text.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.OnPassCompleted().