Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot
TryCreateSnapshot()
bool Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot () inline
Definition at line 565 of file WorldGenerator.cs.
            {
                return this.TryOperateInControlLock(delegate
                {
                    if (WorldGen.Manifest.FinalHash == null)
                    {
                        Main.NewText("Pass was not run with worldgen debugging enabled, please re-run", 240, 30, 30);
                        return;
                    }
                    uint? finalHash = WorldGen.Manifest.FinalHash;
                    uint num = WorldGenerator.HashWorld();
                    if (!((finalHash.GetValueOrDefault() == num) & (finalHash != null)))
                    {
                        Main.NewText("World has been modified since last gen pass completed. Please rerun or use /snapshot instead", 240, 30, 30);
                        return;
                    }
                    try
                    {
                        this._snapshots[this.LastCompletedPass] = WorldGenSnapshot.Create();
                    }
                    catch (Exception ex)
                    {
                        this.ReportException("Exception occured while creating snapshot", ex);
                    }
                });
            }
References Terraria.WorldBuilding.WorldGenerator.Controller._snapshots, Terraria.WorldBuilding.WorldGenSnapshot.Create(), Terraria.WorldBuilding.WorldGenerator.HashWorld(), Terraria.WorldBuilding.WorldGenerator.Controller.LastCompletedPass, Terraria.WorldGen.Manifest, Terraria.Main.NewText(), Terraria.WorldBuilding.WorldGenerator.Controller.ReportException(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryOperateInControlLock().
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.OnPassCompleted().