Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.ReportException
ReportException()
void Terraria.WorldBuilding.WorldGenerator.Controller.ReportException (string message, Exception ex = null) inline package
Definition at line 694 of file WorldGenerator.cs.
            {
                Trace.WriteLine((ex != null) ? ex.ToString() : message);
                if (!DebugOptions.enableDebugCommands)
                {
                    return;
                }
                this.Paused = true;
                WorldGenerator.SetDebugWorldGenUIVisibility(true);
                UIWorldGenDebug.ActiveInstance.UnhideChat();
                Main.NewText(message, byte.MaxValue, 0, 0);
            }
References Terraria.GameContent.UI.States.UIWorldGenDebug.ActiveInstance, Terraria.Testing.DebugOptions.enableDebugCommands, Terraria.Main.NewText(), Terraria.WorldBuilding.WorldGenerator.SetDebugWorldGenUIVisibility(), System.Trace, and Terraria.GameContent.UI.States.UIWorldGenDebug.UnhideChat().
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__45_0(), Terraria.WorldBuilding.WorldGenerator.Controller.CheckLatestPassResultAgainstManifest(), Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryResetToSnapshot().