Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.Controller.ForceUpdateProgress
ForceUpdateProgress()
void Terraria.WorldBuilding.WorldGenerator.Controller.ForceUpdateProgress () inline
Definition at line 548 of file WorldGenerator.cs.
            {
                GenerationProgress progress = this._generator._progress;
                progress.Message = ((WorldGenerator.PassResults.Count == 0) ? "World Cleared" : ("Paused after " + this.Passes[WorldGenerator.PassResults.Count - 1].Name));
                progress.TotalWeight = this.Passes.Where((GenPass p) => p.Enabled).Sum((GenPass p) => p.Weight);
                progress.TotalWeightedProgress = (from p in this.Passes.Take(WorldGenerator.PassResults.Count)
                    where p.Enabled
                    select p).Sum((GenPass p) => p.Weight);
            }
References Terraria.WorldBuilding.WorldGenerator.Controller._generator, Terraria.WorldBuilding.WorldGenerator._progress, Terraria.WorldBuilding.GenPass.Enabled, Terraria.WorldBuilding.WorldGenerator.PassResults, and Terraria.WorldBuilding.GenPass.Weight.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__46_0(), Terraria.WorldBuilding.WorldGenerator.Controller.OnPaused(), Terraria.WorldBuilding.WorldGenerator.Controller.TryReset(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryResetToSnapshot().