Terraria Decompiled: System.Security.Cryptography.RSACryptoServiceProvider.OnKeyGenerated
OnKeyGenerated()
void System.Security.Cryptography.RSACryptoServiceProvider.OnKeyGenerated (object sender, EventArgs e) inline private
Definition at line 593 of file RSACryptoServiceProvider.cs.
        {
            if (this.persistKey && !this.persisted)
            {
                this.store.KeyValue = this.ToXmlString(!this.rsa.PublicOnly);
                this.store.Save();
                this.persisted = true;
            }
        }
References System.Security.Cryptography.RSACryptoServiceProvider.persisted, System.Security.Cryptography.RSACryptoServiceProvider.persistKey, Mono.Security.Cryptography.RSAManaged.PublicOnly, System.Security.Cryptography.RSACryptoServiceProvider.rsa, Mono.Security.Cryptography.KeyPairPersistence.Save(), System.Security.Cryptography.RSACryptoServiceProvider.store, and System.Security.Cryptography.RSA.ToXmlString().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.Common().