Terraria Decompiled: System.Security.Cryptography.RSACryptoServiceProvider.Common
Common() [2/2]
void System.Security.Cryptography.RSACryptoServiceProvider.Common (int dwKeySize, bool parameters) inline private
Definition at line 210 of file RSACryptoServiceProvider.cs.
        {
            this.LegalKeySizesValue = new KeySizes[1];
            this.LegalKeySizesValue[0] = new KeySizes(384, 16384, 8);
            base.KeySize = dwKeySize;
            this.rsa = new RSAManaged(this.KeySize);
            this.rsa.KeyGenerated += this.OnKeyGenerated;
            this.persistKey = parameters;
            if (parameters)
            {
                return;
            }
            CspParameters cspParameters = new CspParameters(1);
            if (RSACryptoServiceProvider.UseMachineKeyStore)
            {
                cspParameters.Flags |= CspProviderFlags.UseMachineKeyStore;
            }
            this.store = new KeyPairPersistence(cspParameters);
        }
References System.Security.Cryptography.RSACryptoServiceProvider.KeySize, System.Security.Cryptography.AsymmetricAlgorithm.LegalKeySizesValue, System.Security.Cryptography.RSACryptoServiceProvider.OnKeyGenerated(), and System.Security.Cryptography.RSACryptoServiceProvider.UseMachineKeyStore.
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.RSACryptoServiceProvider(), and System.Security.Cryptography.RSACryptoServiceProvider.RSACryptoServiceProvider().