Terraria Decompiled: System.Security.Cryptography.RSACryptoServiceProvider.SignHash
SignHash() [3/3]
byte[] System.Security.Cryptography.RSACryptoServiceProvider.SignHash (byte[] rgbHash, string str) inline
Definition at line 498 of file RSACryptoServiceProvider.cs.
        {
            if (rgbHash == null)
            {
                throw new ArgumentNullException("rgbHash");
            }
            HashAlgorithm hashAlgorithm = HashAlgorithm.Create((str == null) ? "SHA1" : this.GetHashNameFromOID(str));
            return PKCS1.Sign_v15(this, hashAlgorithm, rgbHash);
        }
References System.Security.Cryptography.HashAlgorithm.Create(), System.Security.Cryptography.RSACryptoServiceProvider.GetHashNameFromOID(), and Mono.Security.Cryptography.PKCS1.Sign_v15().