Terraria Decompiled: System.Security.Cryptography.RSACryptoServiceProvider.ImportCspBlob
ImportCspBlob()
void System.Security.Cryptography.RSACryptoServiceProvider.ImportCspBlob (byte[] keyBlob) inline
Implements System.Security.Cryptography.ICspAsymmetricAlgorithm.
Definition at line 633 of file RSACryptoServiceProvider.cs.
        {
            if (keyBlob == null)
            {
                throw new ArgumentNullException("keyBlob");
            }
            RSA rsa = CryptoConvert.FromCapiKeyBlob(keyBlob);
            if (rsa is RSACryptoServiceProvider)
            {
                RSAParameters rsaparameters = rsa.ExportParameters(!(rsa as RSACryptoServiceProvider).PublicOnly);
                this.ImportParameters(rsaparameters);
            }
            else
            {
                try
                {
                    RSAParameters rsaparameters2 = rsa.ExportParameters(true);
                    this.ImportParameters(rsaparameters2);
                }
                catch
                {
                    RSAParameters rsaparameters3 = rsa.ExportParameters(false);
                    this.ImportParameters(rsaparameters3);
                }
            }
            CspParameters cspParameters = new CspParameters(1);
            cspParameters.KeyNumber = ((keyBlob[5] == 36) ? 2 : 1);
            if (RSACryptoServiceProvider.UseMachineKeyStore)
            {
                cspParameters.Flags |= CspProviderFlags.UseMachineKeyStore;
            }
            this.store = new KeyPairPersistence(cspParameters);
        }
References Mono.Security.Cryptography.RSAManaged.ExportParameters(), Mono.Security.Cryptography.CryptoConvert.FromCapiKeyBlob(), System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(), System.Security.Cryptography.RSACryptoServiceProvider.PublicOnly, System.Security.Cryptography.RSACryptoServiceProvider.rsa, and System.Security.Cryptography.RSACryptoServiceProvider.UseMachineKeyStore.