Terraria Decompiled: System.Security.Cryptography.RSACryptoServiceProvider.InternalHashToHashAlgorithm
InternalHashToHashAlgorithm()
static HashAlgorithm System.Security.Cryptography.RSACryptoServiceProvider.InternalHashToHashAlgorithm (int calgHash) inline static private
Definition at line 515 of file RSACryptoServiceProvider.cs.
        {
            if (calgHash == 32771)
            {
                return MD5.Create();
            }
            if (calgHash == 32772)
            {
                return SHA1.Create();
            }
            switch (calgHash)
            {
            case 32780:
                return SHA256.Create();
            case 32781:
                return SHA384.Create();
            case 32782:
                return SHA512.Create();
            default:
                throw new NotImplementedException(calgHash.ToString());
            }
        }
References System.Security.Cryptography.MD5.Create(), System.Security.Cryptography.SHA1.Create(), System.Security.Cryptography.SHA256.Create(), System.Security.Cryptography.SHA384.Create(), and System.Security.Cryptography.SHA512.Create().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.SignHash(), and System.Security.Cryptography.RSACryptoServiceProvider.VerifyHash().