Terraria Decompiled: System.Security.Cryptography.RSACryptoServiceProvider.GetHash
GetHash()
HashAlgorithm System.Security.Cryptography.RSACryptoServiceProvider.GetHash (object halg) inline private
Definition at line 395 of file RSACryptoServiceProvider.cs.
        {
            if (halg == null)
            {
                throw new ArgumentNullException("halg");
            }
            HashAlgorithm hashAlgorithm;
            if (halg is string)
            {
                hashAlgorithm = this.GetHashFromString((string)halg);
            }
            else if (halg is HashAlgorithm)
            {
                hashAlgorithm = (HashAlgorithm)halg;
            }
            else
            {
                if (!(halg is Type))
                {
                    throw new ArgumentException("halg");
                }
                hashAlgorithm = (HashAlgorithm)Activator.CreateInstance((Type)halg);
            }
            if (hashAlgorithm == null)
            {
                throw new ArgumentException("Could not find provider for halg='" + ((halg != null) ? halg.ToString() : null) + "'.", "halg");
            }
            return hashAlgorithm;
        }
References System.Activator.CreateInstance(), and System.Security.Cryptography.RSACryptoServiceProvider.GetHashFromString().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), and System.Security.Cryptography.RSACryptoServiceProvider.VerifyData().