Terraria Decompiled: Ionic.BZip2.BZip2Compressor.sendMTFValues1
sendMTFValues1()
int Ionic.BZip2.BZip2Compressor.sendMTFValues1 (int nGroups, int alphaSize) inline private
Definition at line 1126 of file BZip2Compressor.cs.
        {
            BZip2Compressor.CompressionState compressionState = this.cstate;
            int[][] sendMTFValues_rfreq = compressionState.sendMTFValues_rfreq;
            int[] sendMTFValues_fave = compressionState.sendMTFValues_fave;
            short[] sendMTFValues_cost = compressionState.sendMTFValues_cost;
            char[] sfmap = compressionState.sfmap;
            byte[] selector = compressionState.selector;
            byte[][] sendMTFValues_len = compressionState.sendMTFValues_len;
            byte[] array = sendMTFValues_len[0];
            byte[] array2 = sendMTFValues_len[1];
            byte[] array3 = sendMTFValues_len[2];
            byte[] array4 = sendMTFValues_len[3];
            byte[] array5 = sendMTFValues_len[4];
            byte[] array6 = sendMTFValues_len[5];
            int num = this.nMTF;
            int num2 = 0;
            for (int i = 0; i < BZip2.N_ITERS; i++)
            {
                int num3 = nGroups;
                while (--num3 >= 0)
                {
                    sendMTFValues_fave[num3] = 0;
                    int[] array7 = sendMTFValues_rfreq[num3];
                    int num4 = alphaSize;
                    while (--num4 >= 0)
                    {
                        array7[num4] = 0;
                    }
                }
                num2 = 0;
                int num5;
                for (int j = 0; j < this.nMTF; j = num5 + 1)
                {
                    num5 = Math.Min(j + BZip2.G_SIZE - 1, num - 1);
                    if (nGroups == BZip2.NGroups)
                    {
                        int[] array8 = new int[6];
                        for (int k = j; k <= num5; k++)
{
                            int num6 = (int)sfmap[k];
                            array8[0] += (int)(array[num6] & byte.MaxValue);
                            array8[1] += (int)(array2[num6] & byte.MaxValue);
                            array8[2] += (int)(array3[num6] & byte.MaxValue);
                            array8[3] += (int)(array4[num6] & byte.MaxValue);
                            array8[4] += (int)(array5[num6] & byte.MaxValue);
                            array8[5] += (int)(array6[num6] & byte.MaxValue);
                        }
                        sendMTFValues_cost[0] = (short)array8[0];
                        sendMTFValues_cost[1] = (short)array8[1];
                        sendMTFValues_cost[2] = (short)array8[2];
                        sendMTFValues_cost[3] = (short)array8[3];
                        sendMTFValues_cost[4] = (short)array8[4];
                        sendMTFValues_cost[5] = (short)array8[5];
                    }
                    else
                    {
                        int num7 = nGroups;
                        while (--num7 >= 0)
{
                            sendMTFValues_cost[num7] = 0;
                        }
                        for (int l = j; l <= num5; l++)
{
                            int num8 = (int)sfmap[l];
                            int num9 = nGroups;
                            while (--num9 >= 0)
{
                                short[] array9 = sendMTFValues_cost;
                                int num10 = num9;
                                array9[num10] += (short)(sendMTFValues_len[num9][num8] & byte.MaxValue);
                            }
                        }
                    }
                    int num11 = -1;
                    int num12 = nGroups;
                    int num13 = 999999999;
                    while (--num12 >= 0)
                    {
                        int num14 = (int)sendMTFValues_cost[num12];
                        if (num14 < num13)
{
                            num13 = num14;
                            num11 = num12;
                        }
                    }
                    sendMTFValues_fave[num11]++;
                    selector[num2] = (byte)num11;
                    num2++;
                    int[] array10 = sendMTFValues_rfreq[num11];
                    for (int m = j; m <= num5; m++)
                    {
                        array10[(int)sfmap[m]]++;
                    }
                }
                for (int n = 0; n < nGroups; n++)
                {
                    BZip2Compressor.hbMakeCodeLengths(sendMTFValues_len[n], sendMTFValues_rfreq[n], this.cstate, alphaSize, 20);
                }
            }
            return num2;
        }
References System.array, Ionic.BZip2.BZip2Compressor.cstate, Ionic.BZip2.BZip2.G_SIZE, Ionic.BZip2.BZip2Compressor.hbMakeCodeLengths(), int, System.Math.Min(), Ionic.BZip2.BZip2.N_ITERS, Ionic.BZip2.BZip2.NGroups, Ionic.BZip2.BZip2Compressor.nMTF, Ionic.BZip2.BZip2Compressor.CompressionState.selector, Ionic.BZip2.BZip2Compressor.CompressionState.sendMTFValues_cost, Ionic.BZip2.BZip2Compressor.CompressionState.sendMTFValues_fave, Ionic.BZip2.BZip2Compressor.CompressionState.sendMTFValues_len, Ionic.BZip2.BZip2Compressor.CompressionState.sendMTFValues_rfreq, and Ionic.BZip2.BZip2Compressor.CompressionState.sfmap.
Referenced by Ionic.BZip2.BZip2Compressor.sendMTFValues().