Terraria Decompiled: Ionic.BZip2.BZip2Compressor.blockSort
blockSort()
void Ionic.BZip2.BZip2Compressor.blockSort () inline private
Definition at line 405 of file BZip2Compressor.cs.
        {
            this.workLimit = BZip2Compressor.WORK_FACTOR * this.last;
            this.workDone = 0;
            this.blockRandomised = false;
            this.firstAttempt = true;
            this.mainSort();
            if (this.firstAttempt && this.workDone > this.workLimit)
            {
                this.randomiseBlock();
                this.workLimit = (this.workDone = 0);
                this.firstAttempt = false;
                this.mainSort();
            }
            int[] fmap = this.cstate.fmap;
            this.origPtr = -1;
            int i = 0;
            int num = this.last;
            while (i <= num)
            {
                if (fmap[i] == 0)
                {
                    this.origPtr = i;
                    return;
                }
                i++;
            }
        }
References Ionic.BZip2.BZip2Compressor.cstate, Ionic.BZip2.BZip2Compressor.firstAttempt, Ionic.BZip2.BZip2Compressor.last, Ionic.BZip2.BZip2Compressor.mainSort(), Ionic.BZip2.BZip2Compressor.randomiseBlock(), Ionic.BZip2.BZip2Compressor.workDone, and Ionic.BZip2.BZip2Compressor.workLimit.
Referenced by Ionic.BZip2.BZip2Compressor.CompressAndWrite().