Terraria Decompiled: Ionic.BZip2.BZip2Compressor.sendMTFValues
sendMTFValues()
void Ionic.BZip2.BZip2Compressor.sendMTFValues () inline private
Definition at line 931 of file BZip2Compressor.cs.
        {
            byte[][] sendMTFValues_len = this.cstate.sendMTFValues_len;
            int num = this.nInUse + 2;
            int num2 = BZip2.NGroups;
            while (--num2 >= 0)
            {
                byte[] array = sendMTFValues_len[num2];
                int num3 = num;
                while (--num3 >= 0)
                {
                    array[num3] = BZip2Compressor.GREATER_ICOST;
                }
            }
            int num4 = ((this.nMTF < 200) ? 2 : ((this.nMTF < 600) ? 3 : ((this.nMTF < 1200) ? 4 : ((this.nMTF < 2400) ? 5 : 6))));
            this.sendMTFValues0(num4, num);
            int num5 = this.sendMTFValues1(num4, num);
            this.sendMTFValues2(num4, num5);
            this.sendMTFValues3(num4, num);
            this.sendMTFValues4();
            this.sendMTFValues5(num4, num5);
            this.sendMTFValues6(num4, num);
            this.sendMTFValues7(num5);
        }
References System.array, Ionic.BZip2.BZip2Compressor.cstate, Ionic.BZip2.BZip2Compressor.GREATER_ICOST, Ionic.BZip2.BZip2.NGroups, Ionic.BZip2.BZip2Compressor.sendMTFValues0(), Ionic.BZip2.BZip2Compressor.sendMTFValues1(), Ionic.BZip2.BZip2Compressor.sendMTFValues2(), Ionic.BZip2.BZip2Compressor.sendMTFValues3(), Ionic.BZip2.BZip2Compressor.sendMTFValues4(), Ionic.BZip2.BZip2Compressor.sendMTFValues5(), Ionic.BZip2.BZip2Compressor.sendMTFValues6(), and Ionic.BZip2.BZip2Compressor.sendMTFValues7().
Referenced by Ionic.BZip2.BZip2Compressor.moveToFrontCodeAndSend().