Terraria Decompiled: Ionic.BZip2.BZip2Compressor.mainQSort3
mainQSort3()
void Ionic.BZip2.BZip2Compressor.mainQSort3 (BZip2Compressor::CompressionState dataShadow, int loSt, int hiSt, int dSt) inline private
Definition at line 693 of file BZip2Compressor.cs.
        {
            int[] stack_ll = dataShadow.stack_ll;
            int[] stack_hh = dataShadow.stack_hh;
            int[] stack_dd = dataShadow.stack_dd;
            int[] fmap = dataShadow.fmap;
            byte[] block = dataShadow.block;
            stack_ll[0] = loSt;
            stack_hh[0] = hiSt;
            stack_dd[0] = dSt;
            int num = 1;
            while (--num >= 0)
            {
                int num2 = stack_ll[num];
                int num3 = stack_hh[num];
                int num4 = stack_dd[num];
                if (num3 - num2 < BZip2Compressor.SMALL_THRESH || num4 > BZip2Compressor.DEPTH_THRESH)
                {
                    if (this.mainSimpleSort(dataShadow, num2, num3, num4))
                    {
                        return;
                    }
                }
                else
                {
                    int num5 = num4 + 1;
                    int num6 = (int)(BZip2Compressor.med3(block[fmap[num2] + num5], block[fmap[num3] + num5], block[fmap[num2 + num3 >> 1] + num5]) & byte.MaxValue);
                    int i = num2;
                    int num7 = num3;
                    int num8 = num2;
                    int num9 = num3;
                    for (;;)
                    {
                        if (i <= num7)
{
                            int num10 = (int)(block[fmap[i] + num5] & byte.MaxValue) - num6;
                            if (num10 == 0)
{
                                int num11 = fmap[i];
                                fmap[i++] = fmap[num8];
                                fmap[num8++] = num11;
                                continue;
                            }
                            if (num10 < 0)
{
                                i++;
                                continue;
                            }
                        }
                        while (i <= num7)
{
                            int num12 = (int)(block[fmap[num7] + num5] & byte.MaxValue) - num6;
                            if (num12 == 0)
{
                                int num13 = fmap[num7];
                                fmap[num7--] = fmap[num9];
                                fmap[num9--] = num13;
                            }
                            else
{
                                if (num12 <= 0)
{
                                    break;
                                }
                                num7--;
                            }
                        }
                        if (i > num7)
{
                            break;
                        }
                        int num14 = fmap[i];
                        fmap[i++] = fmap[num7];
                        fmap[num7--] = num14;
                    }
                    if (num9 < num8)
                    {
                        stack_ll[num] = num2;
                        stack_hh[num] = num3;
                        stack_dd[num] = num5;
                        num++;
                    }
                    else
                    {
                        int num15 = ((num8 - num2 < i - num8) ? (num8 - num2) : (i - num8));
                        BZip2Compressor.vswap(fmap, num2, i - num15, num15);
                        int num16 = ((num3 - num9 < num9 - num7) ? (num3 - num9) : (num9 - num7));
                        BZip2Compressor.vswap(fmap, i, num3 - num16 + 1, num16);
                        num15 = num2 + i - num8 - 1;
                        num16 = num3 - (num9 - num7) + 1;
                        stack_ll[num] = num2;
                        stack_hh[num] = num15;
                        stack_dd[num] = num4;
                        num++;
                        stack_ll[num] = num15 + 1;
                        stack_hh[num] = num16 - 1;
                        stack_dd[num] = num5;
                        num++;
                        stack_ll[num] = num16;
                        stack_hh[num] = num3;
                        stack_dd[num] = num4;
                        num++;
                    }
                }
            }
        }
References Ionic.BZip2.BZip2Compressor.DEPTH_THRESH, int, Ionic.BZip2.BZip2Compressor.mainSimpleSort(), Ionic.BZip2.BZip2Compressor.med3(), and Ionic.BZip2.BZip2Compressor.vswap().
Referenced by Ionic.BZip2.BZip2Compressor.mainSort().