Terraria Decompiled: Ionic.BZip2.BZip2Compressor.AddRunToOutputBlock
AddRunToOutputBlock()
bool Ionic.BZip2.BZip2Compressor.AddRunToOutputBlock (bool final) inline private
Definition at line 151 of file BZip2Compressor.cs.
        {
            this.runs++;
            int num = this.last;
            if (num >= this.outBlockFillThreshold && !final)
            {
                string text = string.Format("block overrun(final={2}): {0} >= threshold ({1})", num, this.outBlockFillThreshold, final);
                throw new Exception(text);
            }
            byte b = (byte)this.currentByte;
            byte[] block = this.cstate.block;
            this.cstate.inUse[(int)b] = true;
            int num2 = this.runLength;
            this.crc.UpdateCRC(b, num2);
            switch (num2)
            {
            case 1:
                block[num + 2] = b;
                this.last = num + 1;
                break;
            case 2:
                block[num + 2] = b;
                block[num + 3] = b;
                this.last = num + 2;
                break;
            case 3:
                block[num + 2] = b;
                block[num + 3] = b;
                block[num + 4] = b;
                this.last = num + 3;
                break;
            default:
                num2 -= 4;
                this.cstate.inUse[num2] = true;
                block[num + 2] = b;
                block[num + 3] = b;
                block[num + 4] = b;
                block[num + 5] = b;
                block[num + 6] = (byte)num2;
                this.last = num + 5;
                break;
            }
            return this.last >= this.outBlockFillThreshold;
        }
References Ionic.BZip2.BZip2Compressor.crc, Ionic.BZip2.BZip2Compressor.cstate, Ionic.BZip2.BZip2Compressor.currentByte, int, Ionic.BZip2.BZip2Compressor.last, Ionic.BZip2.BZip2Compressor.outBlockFillThreshold, Ionic.BZip2.BZip2Compressor.runLength, Ionic.BZip2.BZip2Compressor.runs, System.text, and Ionic.Crc.CRC32.UpdateCRC().
Referenced by Ionic.BZip2.BZip2Compressor.CompressAndWrite(), and Ionic.BZip2.BZip2Compressor.write0().