Terraria Decompiled: Ionic.BZip2.BZip2Compressor.sendMTFValues7
sendMTFValues7()
void Ionic.BZip2.BZip2Compressor.sendMTFValues7 (int nSelectors) inline private
Definition at line 1376 of file BZip2Compressor.cs.
        {
            byte[][] sendMTFValues_len = this.cstate.sendMTFValues_len;
            int[][] sendMTFValues_code = this.cstate.sendMTFValues_code;
            byte[] selector = this.cstate.selector;
            char[] sfmap = this.cstate.sfmap;
            int num = this.nMTF;
            int num2 = 0;
            int i = 0;
            while (i < num)
            {
                int num3 = Math.Min(i + BZip2.G_SIZE - 1, num - 1);
                int num4 = (int)(selector[num2] & byte.MaxValue);
                int[] array = sendMTFValues_code[num4];
                byte[] array2 = sendMTFValues_len[num4];
                while (i <= num3)
                {
                    int num5 = (int)sfmap[i];
                    int num6 = (int)(array2[num5] & byte.MaxValue);
                    this.bw.WriteBits(num6, (uint)array[num5]);
                    i++;
                }
                i = num3 + 1;
                num2++;
            }
        }
References System.array, Ionic.BZip2.BZip2Compressor.bw, Ionic.BZip2.BZip2Compressor.cstate, Ionic.BZip2.BZip2.G_SIZE, int, System.Math.Min(), Ionic.BZip2.BZip2Compressor.nMTF, and Ionic.BZip2.BitWriter.WriteBits().
Referenced by Ionic.BZip2.BZip2Compressor.sendMTFValues().