Terraria Decompiled: System.Char.IsSymbol
IsSymbol() [1/2]
static bool System.Char.IsSymbol (char c) inline static
Definition at line 607 of file Char.cs.
        {
            if (char.IsLatin1(c))
            {
                return char.CheckSymbol(char.GetLatin1UnicodeCategory(c));
            }
            return char.CheckSymbol(CharUnicodeInfo.GetUnicodeCategory(c));
        }
References System.Char.GetLatin1UnicodeCategory(), System.Globalization.CharUnicodeInfo.GetUnicodeCategory(), and System.Char.IsLatin1().