Terraria Decompiled: Terraria.GameContent.TreeTopsInfo.Load
Load()
void Terraria.GameContent.TreeTopsInfo.Load (BinaryReader reader, int loadVersion) inline
Definition at line 22 of file TreeTopsInfo.cs.
        {
            if (loadVersion < 211)
            {
                this.CopyExistingWorldInfo();
                return;
            }
            int num = reader.ReadInt32();
            int num2 = 0;
            while (num2 < num && num2 < this._variations.Length)
            {
                this._variations[num2] = reader.ReadInt32();
                num2++;
            }
        }
References Terraria.GameContent.TreeTopsInfo._variations, Terraria.GameContent.TreeTopsInfo.CopyExistingWorldInfo(), and System.IO.BinaryReader.ReadInt32().
Referenced by Terraria.IO.WorldFile.LoadHeader().