Terraria Decompiled: System.Collections.Generic.ArrayBuilder.EnsureCapacity
EnsureCapacity()
void System.Collections.Generic.ArrayBuilder< T >.EnsureCapacity (int minimum) inline private
Definition at line 104 of file ArrayBuilder.cs.
        {
            int capacity = this.Capacity;
            int num = ((capacity == 0) ? 4 : (2 * capacity));
            if (num > 2146435071)
            {
                num = Math.Max(capacity + 1, 2146435071);
            }
            num = Math.Max(num, minimum);
            T[] array = new T[num];
            if (this._count > 0)
            {
                Array.Copy(this._array, 0, array, 0, this._count);
            }
            this._array = array;
        }
References System.Collections.Generic.ArrayBuilder< T >._array, System.Collections.Generic.ArrayBuilder< T >._count, System.array, System.Collections.Generic.ArrayBuilder< T >.Capacity, System.capacity, System.Array.Copy(), and System.Math.Max().
Referenced by System.Collections.Generic.ArrayBuilder< T >.Add().