Terraria Decompiled: Terraria.GameContent.UI.States.UIReportsPage.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIReportsPage.BuildPage () inline private
Definition at line 36 of file UIReportsPage.cs.
        {
            base.RemoveAllChildren();
            UIElement uielement = new UIElement();
            uielement.Width.Set(0f, 0.8f);
            uielement.MaxWidth.Set(500f, 0f);
            uielement.MinWidth.Set(300f, 0f);
            uielement.Top.Set(230f, 0f);
            uielement.Height.Set(-uielement.Top.Pixels, 1f);
            uielement.HAlign = 0.5f;
            base.Append(uielement);
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set(-110f, 1f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
            uielement.Append(uipanel);
            UIElement uielement2 = new UIElement
            {
                Width = StyleDimension.Fill,
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f)
            };
            uipanel.Append(uielement2);
            UIElement uielement3 = new UIElement
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(28f, 0f)
            };
            uielement3.SetPadding(0f);
            uielement2.Append(uielement3);
            uielement3.Append(new UIText(Language.GetTextValue("UI.ReportsPage"), 0.7f, true)
            {
                HAlign = 0.5f,
                VAlign = 0f
            });
            UIElement uielement4 = new UIElement
            {
                HAlign = 0.5f,
                VAlign = 1f,
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-40f, 1f),
                Top = new StyleDimension(-2f, 0f)
            };
            uielement2.Append(uielement4);
            this._container = uielement4;
            float num = 0f;
            UISlicedImage uislicedImage = new UISlicedImage(Main.Assets.Request<Texture2D>("Images/UI/CharCreation/CategoryPanelHighlight", 1))
            {
                HAlign = 0.5f,
                VAlign = 1f,
                Width = StyleDimension.FromPixelsAndPercent(-num * 2f, 1f),
                Left = StyleDimension.FromPixels(-num),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Top = StyleDimension.FromPixels(2f)
            };
            uislicedImage.SetSliceDepths(10);
            uislicedImage.Color = Color.LightGray * 0.5f;
            uielement4.Append(uislicedImage);
            UIList uilist = new UIList
            {
                HAlign = 0.5f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                PaddingRight = 20f
            };
            uilist.ListPadding = 40f;
            uilist.ManualSortMethod = new Action<List<UIElement>>(this.ManualIfnoSortingMethod);
            UIElement uielement5 = new UIElement();
            uilist.Add(uielement5);
            this.PopulateLogs(uilist);
            uielement4.Append(uilist);
            this._list = uilist;
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue);
            uiscrollbar.SetView(100f, 1000f);
            uiscrollbar.Height.Set(0f, 1f);
            uiscrollbar.HAlign = 1f;
            this._scrollbar = uiscrollbar;
            uilist.SetScrollbar(uiscrollbar);
            uiscrollbar.GoToBottom();
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("UI.Back"), 0.7f, true);
            uitextPanel.Width.Set(-10f, 0.5f);
            uitextPanel.Height.Set(50f, 0f);
            uitextPanel.VAlign = 1f;
            uitextPanel.HAlign = 0.5f;
            uitextPanel.Top.Set(-45f, 0f);
            uitextPanel.OnMouseOver += UIReportsPage.FadedMouseOver;
            uitextPanel.OnMouseOut += UIReportsPage.FadedMouseOut;
            uitextPanel.OnLeftClick += this.GoBackClick;
            uitextPanel.SetSnapPoint("GoBack", 0, null, null);
            uielement.Append(uitextPanel);
        }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UIReportsPage.FadedMouseOut(), Terraria.GameContent.UI.States.UIReportsPage.FadedMouseOver(), Terraria.UI.StyleDimension.Fill, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.UI.States.UIReportsPage.GoBackClick(), Terraria.GameContent.UI.Elements.UIScrollbar.GoToBottom(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIReportsPage.ManualIfnoSortingMethod(), Terraria.UI.UIElement.MaxWidth, Terraria.UI.UIElement.MinWidth, Terraria.UI.UIElement.PaddingRight, Terraria.UI.StyleDimension.Pixels, Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UISlicedImage.SetSliceDepths(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIReportsPage.OnInitialize().