Terraria Decompiled: Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs
PopulateLogs()
void Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs (UIList listContents) inline private
Definition at line 134 of file UIReportsPage.cs.
        {
            List<IssueReport> list = (from report in this._reporters.SelectMany((IProvideReports reporter) => reporter.GetReports())
                orderby report.timeReported
                select report).ToList<IssueReport>();
            if (list.Count == 0)
            {
                UIText uitext = new UIText(Language.GetTextValue("Workshop.ReportLogsInitialMessage"), 1f, false)
                {
                    HAlign = 0f,
                    VAlign = 0f,
                    Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                    Height = StyleDimension.FromPixelsAndPercent(0f, 0f),
                    IsWrapped = true,
                    WrappedTextBottomPadding = 0f,
                    TextOriginX = 0.5f,
                    TextColor = Color.Gray
                };
                listContents.Add(uitext);
            }
            for (int i = 0; i < list.Count; i++)
            {
                UIText uitext2 = new UIText(list[i].reportText, 1f, false)
                {
                    HAlign = 0f,
                    VAlign = 0f,
                    Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
                    Height = StyleDimension.FromPixelsAndPercent(0f, 0f),
                    IsWrapped = true,
                    WrappedTextBottomPadding = 0f,
                    TextOriginX = 0f
                };
                listContents.Add(uitext2);
                Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Divider", 1);
                UIImage uiimage = new UIImage(asset)
                {
                    Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                    Height = StyleDimension.FromPixels((float)asset.Height()),
                    ScaleToFit = true,
                    VAlign = 1f
                };
                uitext2.Append(uiimage);
            }
            UIElement uielement = new UIElement();
            listContents.Add(uielement);
        }
References Terraria.GameContent.UI.States.UIReportsPage._reporters, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.DataStructures.IProvideReports.GetReports(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, System.list, Terraria.UI.UIElement.UIElement(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIReportsPage.BuildPage().