Terraria Decompiled: System.Buffer.Memcpy
Memcpy() [1/3]
static unsafe void System.Buffer.Memcpy (byte * dest, byte * src, int len) inline static package
Definition at line 344 of file Buffer.cs.
        {
            if (len > 32)
            {
                Buffer.InternalMemcpy(dest, src, len);
                return;
            }
            if (((dest | src) & 3) != 0)
            {
                if ((dest & 1) != 0 && (src & 1) != 0 && len >= 1)
                {
                    *dest = *src;
                    dest++;
                    src++;
                    len--;
                }
                if ((dest & 2) != 0 && (src & 2) != 0 && len >= 2)
                {
                    *(short*)dest = *(short*)src;
                    dest += 2;
                    src += 2;
                    len -= 2;
                }
                if (((dest | src) & 1) != 0)
                {
                    Buffer.memcpy1(dest, src, len);
                    return;
                }
                if (((dest | src) & 2) != 0)
                {
                    Buffer.memcpy2(dest, src, len);
                    return;
                }
            }
            Buffer.memcpy4(dest, src, len);
        }
References System.Buffer.InternalMemcpy(), System.Buffer.memcpy1(), System.Buffer.memcpy2(), and System.Buffer.memcpy4().