Terraria Decompiled: Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal
NewTextInternal()
void Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal (string newText, byte R = 255, byte G = 255, byte B = 255, bool force = false) inline
Definition at line 84 of file LegacyChatMonitor.cs.
        {
            int num = 80;
            if (!force && newText.Length > num)
            {
                string text = this.TrimIntoMultipleLines(R, G, B, num, newText);
                if (text.Length > 0)
                {
                    this.NewTextInternal(text, R, G, B, true);
                }
                return;
            }
            for (int i = this.numChatLines - 1; i > 0; i--)
            {
                this.chatLine[i].Copy(this.chatLine[i - 1]);
            }
            this.chatLine[0].color = new Color((int)R, (int)G, (int)B);
            this.chatLine[0].originalText = newText;
            this.chatLine[0].parsedText = ChatManager.ParseMessage(this.chatLine[0].originalText, this.chatLine[0].color).ToArray();
            this.chatLine[0].showTime = this.chatLength;
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
        }
References System.B, Terraria.GameContent.UI.Chat.LegacyChatMonitor.chatLength, Terraria.GameContent.UI.Chat.LegacyChatMonitor.chatLine, Terraria.UI.Chat.ChatLine.color, Terraria.UI.Chat.ChatLine.Copy(), System.G, Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.numChatLines, Terraria.UI.Chat.ChatLine.originalText, Terraria.UI.Chat.ChatLine.parsedText, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.Audio.SoundEngine.PlaySound(), System.R, Terraria.UI.Chat.ChatLine.showTime, System.text, and Terraria.GameContent.UI.Chat.LegacyChatMonitor.TrimIntoMultipleLines().
Referenced by Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal(), and Terraria.GameContent.UI.Chat.LegacyChatMonitor.TrimIntoMultipleLines().