Terraria Decompiled: Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewText
NewText() [1/2]
void Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewText (List< TextSnippet > snippets) inline
Definition at line 178 of file LegacyChatMonitor.cs.
        {
            for (int i = this.numChatLines - 1; i > 0; i--)
            {
                this.chatLine[i].Copy(this.chatLine[i - 1]);
            }
            this.chatLine[0].originalText = "this is a hack because draw checks length is higher than 0";
            this.chatLine[0].parsedText = snippets.ToArray();
            this.chatLine[0].showTime = this.chatLength;
            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
        }
References Terraria.GameContent.UI.Chat.LegacyChatMonitor.chatLength, Terraria.GameContent.UI.Chat.LegacyChatMonitor.chatLine, Terraria.UI.Chat.ChatLine.Copy(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.numChatLines, Terraria.UI.Chat.ChatLine.originalText, Terraria.UI.Chat.ChatLine.parsedText, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Chat.ChatLine.showTime, and System.Collections.Generic.List< T >.ToArray().