Terraria Decompiled: Terraria.Social.WeGame.IPCServer.CheckFlagAndFireEvent
CheckFlagAndFireEvent()
void Terraria.Social.WeGame.IPCServer.CheckFlagAndFireEvent () inline private
Definition at line 166 of file IPCServer.cs.
        {
            this.ProcessClientAccessEvent();
            this.ProcessDataArriveEvent();
            this.ProcessPipeBrokenEvent();
        }
References Terraria.Social.WeGame.IPCServer.ProcessClientAccessEvent(), Terraria.Social.WeGame.IPCBase.ProcessDataArriveEvent(), and Terraria.Social.WeGame.IPCServer.ProcessPipeBrokenEvent().
Referenced by Terraria.Social.WeGame.IPCServer.Tick().