Terraria Decompiled: System.Enum.InternalFlagsFormat
InternalFlagsFormat()
static string System.Enum.InternalFlagsFormat (RuntimeType eT, object value) inline static private
Definition at line 81 of file Enum.cs.
        {
            ulong num = Enum.ToUInt64(value);
            Enum.ValuesAndNames cachedValuesAndNames = Enum.GetCachedValuesAndNames(eT, true);
            string[] names = cachedValuesAndNames.Names;
            ulong[] values = cachedValuesAndNames.Values;
            int num2 = values.Length - 1;
            StringBuilder stringBuilder = new StringBuilder();
            bool flag = true;
            ulong num3 = num;
            while (num2 >= 0 && (num2 != 0 || values[num2] != 0UL))
            {
                if ((num & values[num2]) == values[num2])
                {
                    num -= values[num2];
                    if (!flag)
                    {
                        stringBuilder.Insert(0, ", ");
                    }
                    stringBuilder.Insert(0, names[num2]);
                    flag = false;
                }
                num2--;
            }
            if (num != 0UL)
            {
                return value.ToString();
            }
            if (num3 != 0UL)
            {
                return stringBuilder.ToString();
            }
            if (values.Length != 0 && values[0] == 0UL)
            {
                return names[0];
            }
            return "0";
        }
References System.Enum.GetCachedValuesAndNames(), System.Text.StringBuilder.Insert(), System.Enum.ValuesAndNames.Names, System.Text.StringBuilder.ToString(), System.Enum.ToUInt64(), System.value, System.Enum.ValuesAndNames.Values, and System.values.
Referenced by System.Enum.Format(), System.Enum.InternalFormat(), and System.Enum.ToString().