Terraria Decompiled: System.Enum.TryParseEnum
TryParseEnum()
static bool System.Enum.TryParseEnum (Type enumType, string value, bool ignoreCase, ref Enum::EnumResult parseResult) inline static private
Definition at line 203 of file Enum.cs.
        {
            if (enumType == null)
            {
                throw new ArgumentNullException("enumType");
            }
            RuntimeType runtimeType = enumType as RuntimeType;
            if (runtimeType == null)
            {
                throw new ArgumentException(Environment.GetResourceString("Type must be a type provided by the runtime."), "enumType");
            }
            if (!enumType.IsEnum)
            {
                throw new ArgumentException(Environment.GetResourceString("Type provided must be an Enum."), "enumType");
            }
            if (value == null)
            {
                parseResult.SetFailure(Enum.ParseFailureKind.ArgumentNull, "value");
                return false;
            }
            value = value.Trim();
            if (value.Length == 0)
            {
                parseResult.SetFailure(Enum.ParseFailureKind.Argument, "Must specify valid information for parsing in the string.", null);
                return false;
            }
            ulong num = 0UL;
            if (char.IsDigit(value[0]) || value[0] == '-' || value[0] == '+')
            {
                Type underlyingType = Enum.GetUnderlyingType(enumType);
                try
                {
                    object obj = Convert.ChangeType(value, underlyingType, CultureInfo.InvariantCulture);
                    parseResult.parsedEnum = Enum.ToObject(enumType, obj);
                    return true;
                }
                catch (FormatException)
                {
                }
                catch (Exception ex)
                {
                    if (parseResult.canThrow)
                    {
                        throw;
                    }
                    parseResult.SetFailure(ex);
                    return false;
                }
            }
            string[] array = value.Split(Enum.enumSeperatorCharArray);
            Enum.ValuesAndNames cachedValuesAndNames = Enum.GetCachedValuesAndNames(runtimeType, true);
            string[] names = cachedValuesAndNames.Names;
            ulong[] values = cachedValuesAndNames.Values;
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = array[i].Trim();
                bool flag = false;
                int j = 0;
                while (j < names.Length)
                {
                    if (ignoreCase)
                    {
                        if (string.Compare(names[j], array[i], StringComparison.OrdinalIgnoreCase) == 0)
{
                            goto IL_0158;
                        }
                    }
                    else if (names[j].Equals(array[i]))
                    {
                        goto IL_0158;
                    }
                    j++;
                    continue;
                    IL_0158:
                    ulong num2 = values[j];
                    num |= num2;
                    flag = true;
                    break;
                }
                if (!flag)
                {
                    parseResult.SetFailure(Enum.ParseFailureKind.ArgumentWithParameter, "Requested value '{0}' was not found.", value);
                    return false;
                }
            }
            bool flag2;
            try
            {
                parseResult.parsedEnum = Enum.ToObject(enumType, num);
                flag2 = true;
            }
            catch (Exception ex2)
            {
                if (parseResult.canThrow)
                {
                    throw;
                }
                parseResult.SetFailure(ex2);
                flag2 = false;
            }
            return flag2;
        }
References System.array, System.Convert.ChangeType(), System.Enum.enumSeperatorCharArray, System.Enum.Equals(), System.Enum.GetCachedValuesAndNames(), System.Environment.GetResourceString(), System.Enum.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsEnum, System.Enum.ValuesAndNames.Names, System.obj, System.Enum.ToObject(), System.value, System.Enum.ValuesAndNames.Values, and System.values.
Referenced by System.Enum.Parse(), System.Enum.Parse< TEnum >(), System.Enum.TryParse(), and System.Enum.TryParse< TEnum >().