Terraria Decompiled: NVorbis.Ogg.PacketProvider.SeekTo
SeekTo()
long NVorbis.Ogg.PacketProvider.SeekTo (long granulePos, int preRoll, GetPacketGranuleCount getPacketGranuleCount) inline
Definition at line 80 of file PacketProvider.cs.
        {
            if (this._reader == null)
            {
                throw new ObjectDisposedException("PacketProvider");
            }
            int num;
            int num2;
            if (granulePos == 0L)
            {
                num = this._reader.FirstDataPageIndex;
                num2 = 0;
            }
            else
            {
                num = this._reader.FindPage(granulePos);
                if (this._reader.HasAllPages)
                {
                    long? maxGranulePosition = this._reader.MaxGranulePosition;
                    long num3 = granulePos;
                    if ((maxGranulePosition.GetValueOrDefault() == num3) & (maxGranulePosition != null))
                    {
                        this._lastPacket = null;
                        this._pageIndex = num;
                        this._packetIndex = 0;
                        return granulePos;
                    }
                }
                num2 = this.FindPacket(num, ref granulePos, getPacketGranuleCount);
                num2 -= preRoll;
            }
            if (!this.NormalizePacketIndex(ref num, ref num2))
            {
                throw new ArgumentOutOfRangeException("granulePos");
            }
            if (num < this._reader.FirstDataPageIndex)
            {
                num = this._reader.FirstDataPageIndex;
                num2 = 0;
            }
            this._lastPacket = null;
            this._pageIndex = num;
            this._packetIndex = num2;
            return granulePos;
        }
References NVorbis.Ogg.PacketProvider._reader, NVorbis.Ogg.PacketProvider.FindPacket(), NVorbis.Contracts.Ogg.IStreamPageReader.FindPage(), NVorbis.Contracts.Ogg.IStreamPageReader.FirstDataPageIndex, NVorbis.Contracts.Ogg.IStreamPageReader.HasAllPages, System.L, NVorbis.Contracts.Ogg.IStreamPageReader.MaxGranulePosition, and NVorbis.Ogg.PacketProvider.NormalizePacketIndex().