Terraria Decompiled: System.Globalization.DateTimeFormatInfoScanner.ScanDateWord
ScanDateWord()
void System.Globalization.DateTimeFormatInfoScanner.ScanDateWord (string pattern) inline package
Definition at line 236 of file DateTimeFormatInfoScanner.cs.
        {
            this._ymdFlags = DateTimeFormatInfoScanner.FoundDatePattern.None;
            for (int i = 0; i < pattern.Length; i++)
            {
                char c = pattern[i];
                if (c <= 'M')
                {
                    if (c == '\'')
                    {
                        i = this.AddDateWords(pattern, i + 1, null);
                        continue;
                    }
                    if (c == '.')
                    {
                        if (this._ymdFlags == DateTimeFormatInfoScanner.FoundDatePattern.FoundYMDPatternFlag)
{
                            this.AddIgnorableSymbols(".");
                            this._ymdFlags = DateTimeFormatInfoScanner.FoundDatePattern.None;
                        }
                        i++;
                        continue;
                    }
                    if (c == 'M')
                    {
                        int num;
                        i = DateTimeFormatInfoScanner.ScanRepeatChar(pattern, 'M', i, out num);
                        if (num >= 4 && i < pattern.Length && pattern[i] == '\'')
{
                            i = this.AddDateWords(pattern, i + 1, "MMMM");
                        }
                        this._ymdFlags |= DateTimeFormatInfoScanner.FoundDatePattern.FoundMonthPatternFlag;
                        continue;
                    }
                }
                else
                {
                    if (c == '\\')
                    {
                        i += 2;
                        continue;
                    }
                    if (c != 'd')
                    {
                        if (c == 'y')
{
                            int num;
                            i = DateTimeFormatInfoScanner.ScanRepeatChar(pattern, 'y', i, out num);
                            this._ymdFlags |= DateTimeFormatInfoScanner.FoundDatePattern.FoundYearPatternFlag;
                            continue;
                        }
                    }
                    else
                    {
                        int num;
                        i = DateTimeFormatInfoScanner.ScanRepeatChar(pattern, 'd', i, out num);
                        if (num <= 2)
{
                            this._ymdFlags |= DateTimeFormatInfoScanner.FoundDatePattern.FoundDayPatternFlag;
                            continue;
                        }
                        continue;
                    }
                }
                if (this._ymdFlags == DateTimeFormatInfoScanner.FoundDatePattern.FoundYMDPatternFlag && !char.IsWhiteSpace(c))
                {
                    this._ymdFlags = DateTimeFormatInfoScanner.FoundDatePattern.None;
                }
            }
        }
References System.Globalization.DateTimeFormatInfoScanner._ymdFlags, System.Globalization.DateTimeFormatInfoScanner.AddDateWords(), System.Globalization.DateTimeFormatInfoScanner.AddIgnorableSymbols(), and System.Globalization.DateTimeFormatInfoScanner.ScanRepeatChar().
Referenced by System.Globalization.DateTimeFormatInfoScanner.GetDateWordsOfDTFI().