Terraria Decompiled: NVorbis.Ogg.PacketProvider.CreatePacket
CreatePacket()
Packet NVorbis.Ogg.PacketProvider.CreatePacket (ref int pageIndex, ref int packetIndex, bool advance, long granulePos, bool isResync, bool isContinued, int packetCount, int pageOverhead) inline private
Definition at line 262 of file PacketProvider.cs.
        {
            Memory<byte> memory = this._reader.GetPagePackets(pageIndex)[packetIndex];
            List<int> list = new List<int>(2);
            list.Add((pageIndex << 8) | packetIndex);
            List<int> list2 = list;
            int num = pageIndex;
            bool flag;
            bool flag3;
            if (isContinued && packetIndex == packetCount - 1)
            {
                flag = true;
                if (packetIndex > 0)
                {
                    pageOverhead = 0;
                }
                int num2 = pageIndex;
                while (isContinued)
                {
                    bool flag2;
                    int num3;
                    if (!this._reader.GetPage(++num2, out granulePos, out isResync, out flag2, out isContinued, out packetCount, out num3))
                    {
                        return null;
                    }
                    pageOverhead += num3;
                    if (!flag2 || isResync)
                    {
                        break;
                    }
                    if (isContinued && packetCount > 1)
                    {
                        isContinued = false;
                    }
                    list2.Add(num2 << 8);
                }
                flag3 = packetCount == 1;
                num = num2;
            }
            else
            {
                flag = packetIndex == 0;
                flag3 = packetIndex == packetCount - 1;
            }
            Packet packet = new Packet(list2, this, memory)
            {
                IsResync = isResync
            };
            if (flag)
            {
                packet.ContainerOverheadBits = pageOverhead * 8;
            }
            if (flag3)
            {
                packet.GranulePosition = new long?(granulePos);
                if (this._reader.HasAllPages && num == this._reader.PageCount - 1)
                {
                    packet.IsEndOfStream = true;
                }
            }
            if (advance)
            {
                if (num != pageIndex)
                {
                    pageIndex = num;
                    packetIndex = 0;
                }
                if (packetIndex == packetCount - 1)
                {
                    pageIndex++;
                    packetIndex = 0;
                }
                else
                {
                    packetIndex++;
                }
            }
            return packet;
        }
References NVorbis.Ogg.PacketProvider._reader, System.Collections.Generic.List< T >.Add(), NVorbis.Contracts.Ogg.IStreamPageReader.GetPage(), NVorbis.Contracts.Ogg.IStreamPageReader.GetPagePackets(), NVorbis.Contracts.Ogg.IStreamPageReader.HasAllPages, System.list, and System.Packet.
Referenced by NVorbis.Ogg.PacketProvider.FindPacket(), and NVorbis.Ogg.PacketProvider.GetNextPacket().