Terraria Decompiled: System.Enum.CompareTo
CompareTo()
int System.Enum.CompareTo (object target) inline
Implements System.IComparable< in T >.
Definition at line 527 of file Enum.cs.
        {
            if (this == null)
            {
                throw new NullReferenceException();
            }
            int num = Enum.InternalCompareTo(this, target);
            if (num < 2)
            {
                return num;
            }
            if (num == 2)
            {
                Type type = base.GetType();
                Type type2 = target.GetType();
                throw new ArgumentException(Environment.GetResourceString("Object must be the same type as the enum. The type passed in was '{0}'; the enum type was '{1}'.", new object[]
                {
                    type2.ToString(),
                    type.ToString()
                }));
            }
            throw new InvalidOperationException(Environment.GetResourceString("Unknown enum type."));
        }
References System.Environment.GetResourceString(), System.Type.GetType(), and System.Enum.InternalCompareTo().