Terraria Decompiled: System.Globalization.DateTimeFormatInfoScanner.AddDateWords
AddDateWords()
int System.Globalization.DateTimeFormatInfoScanner.AddDateWords (string pattern, int index, string formatPostfix) inline package
Definition at line 164 of file DateTimeFormatInfoScanner.cs.
        {
            int num = DateTimeFormatInfoScanner.SkipWhiteSpacesAndNonLetter(pattern, index);
            if (num != index && formatPostfix != null)
            {
                formatPostfix = null;
            }
            index = num;
            StringBuilder stringBuilder = new StringBuilder();
            while (index < pattern.Length)
            {
                char c = pattern[index];
                if (c == '\'')
                {
                    this.AddDateWordOrPostfix(formatPostfix, stringBuilder.ToString());
                    index++;
                    break;
                }
                if (c == '\\')
                {
                    index++;
                    if (index < pattern.Length)
                    {
                        stringBuilder.Append(pattern[index]);
                        index++;
                    }
                }
                else if (char.IsWhiteSpace(c))
                {
                    this.AddDateWordOrPostfix(formatPostfix, stringBuilder.ToString());
                    if (formatPostfix != null)
                    {
                        formatPostfix = null;
                    }
                    stringBuilder.Length = 0;
                    index++;
                }
                else
                {
                    stringBuilder.Append(c);
                    index++;
                }
            }
            return index;
        }
References System.Globalization.DateTimeFormatInfoScanner.AddDateWordOrPostfix(), System.Text.StringBuilder.Append(), System.index, System.Globalization.DateTimeFormatInfoScanner.SkipWhiteSpacesAndNonLetter(), and System.Text.StringBuilder.ToString().
Referenced by System.Globalization.DateTimeFormatInfoScanner.ScanDateWord().