Terraria Decompiled: System.Globalization.DateTimeFormatInfoScanner.AddDateWordOrPostfix
AddDateWordOrPostfix()
void System.Globalization.DateTimeFormatInfoScanner.AddDateWordOrPostfix (string formatPostfix, string str) inline package
Definition at line 119 of file DateTimeFormatInfoScanner.cs.
        {
            if (str.Length > 0)
            {
                if (str.Equals("."))
                {
                    this.AddIgnorableSymbols(".");
                    return;
                }
                string text;
                if (!DateTimeFormatInfoScanner.KnownWords.TryGetValue(str, out text))
                {
                    if (this.m_dateWords == null)
                    {
                        this.m_dateWords = new List<string>();
                    }
                    if (formatPostfix == "MMMM")
                    {
                        string text2 = "\ue000" + str;
                        if (!this.m_dateWords.Contains(text2))
{
                            this.m_dateWords.Add(text2);
                            return;
                        }
                    }
                    else
                    {
                        if (!this.m_dateWords.Contains(str))
{
                            this.m_dateWords.Add(str);
                        }
                        if (str[str.Length - 1] == '.')
{
                            string text3 = str.Substring(0, str.Length - 1);
                            if (!this.m_dateWords.Contains(text3))
{
                                this.m_dateWords.Add(text3);
                            }
                        }
                    }
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), System.Globalization.DateTimeFormatInfoScanner.AddIgnorableSymbols(), System.Collections.Generic.List< T >.Contains(), System.Globalization.DateTimeFormatInfoScanner.KnownWords, System.Globalization.DateTimeFormatInfoScanner.m_dateWords, System.text, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Globalization.DateTimeFormatInfoScanner.AddDateWords().