Terraria Decompiled: System.Enum.Format
Format()
static string System.Enum.Format (Type enumType, object value, string format) inline static
Definition at line 410 of file Enum.cs.
        {
            if (enumType == null)
            {
                throw new ArgumentNullException("enumType");
            }
            if (!enumType.IsEnum)
            {
                throw new ArgumentException(Environment.GetResourceString("Type provided must be an Enum."), "enumType");
            }
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            if (format == null)
            {
                throw new ArgumentNullException("format");
            }
            RuntimeType runtimeType = enumType as RuntimeType;
            if (runtimeType == null)
            {
                throw new ArgumentException(Environment.GetResourceString("Type must be a type provided by the runtime."), "enumType");
            }
            Type type = value.GetType();
            Type underlyingType = Enum.GetUnderlyingType(enumType);
            if (type.IsEnum)
            {
                Type underlyingType2 = Enum.GetUnderlyingType(type);
                if (!type.IsEquivalentTo(enumType))
                {
                    throw new ArgumentException(Environment.GetResourceString("Object must be the same type as the enum. The type passed in was '{0}'; the enum type was '{1}'.", new object[]
                    {
                        type.ToString(),
                        enumType.ToString()
                    }));
                }
                value = ((Enum)value).GetValue();
            }
            else if (type != underlyingType)
            {
                throw new ArgumentException(Environment.GetResourceString("Enum underlying type and the object must be same type or object. Type passed in was '{0}'; the enum underlying type was '{1}'.", new object[]
                {
                    type.ToString(),
                    underlyingType.ToString()
                }));
            }
            if (format.Length != 1)
            {
                throw new FormatException(Environment.GetResourceString("Format String can be only \"G\", \"g\", \"X\", \"x\", \"F\", \"f\", \"D\" or \"d\"."));
            }
            char c = format[0];
            if (c == 'D' || c == 'd')
            {
                return value.ToString();
            }
            if (c == 'X' || c == 'x')
            {
                return Enum.InternalFormattedHexString(value);
            }
            if (c == 'G' || c == 'g')
            {
                return Enum.InternalFormat(runtimeType, value);
            }
            if (c == 'F' || c == 'f')
            {
                return Enum.InternalFlagsFormat(runtimeType, value);
            }
            throw new FormatException(Environment.GetResourceString("Format String can be only \"G\", \"g\", \"X\", \"x\", \"F\", \"f\", \"D\" or \"d\"."));
        }
References System.Enum.Enum(), System.format, System.Environment.GetResourceString(), System.Type.GetType(), System.Enum.GetUnderlyingType(), System.Enum.InternalFlagsFormat(), System.Enum.InternalFormat(), System.Enum.InternalFormattedHexString(), System.Type.IsEnum, System.Type.IsEquivalentTo(), and System.value.