Terraria Decompiled: System.Enum.ToUInt64
ToUInt64() [2/2]
static ulong System.Enum.ToUInt64 (object value) inline static package
Definition at line 121 of file Enum.cs.
        {
            ulong num;
            switch (Convert.GetTypeCode(value))
            {
            case TypeCode.Boolean:
            case TypeCode.Char:
            case TypeCode.Byte:
            case TypeCode.UInt16:
            case TypeCode.UInt32:
            case TypeCode.UInt64:
                num = Convert.ToUInt64(value, CultureInfo.InvariantCulture);
                break;
            case TypeCode.SByte:
            case TypeCode.Int16:
            case TypeCode.Int32:
            case TypeCode.Int64:
                num = (ulong)Convert.ToInt64(value, CultureInfo.InvariantCulture);
                break;
            default:
                throw new InvalidOperationException(Environment.GetResourceString("Unknown enum type."));
            }
            return num;
        }
References System.Environment.GetResourceString(), System.Convert.GetTypeCode(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToInt64(), System.Convert.ToUInt64(), and System.value.
Referenced by System.Type.BinarySearch(), System.RuntimeType.GetEnumName(), System.Enum.InternalFlagsFormat(), and System.RuntimeType.IsEnumDefined().