Terraria Decompiled: System.Enum.InternalFormattedHexString
InternalFormattedHexString()
static string System.Enum.InternalFormattedHexString (object value) inline static private
Definition at line 36 of file Enum.cs.
        {
            switch (Convert.GetTypeCode(value))
            {
            case TypeCode.Boolean:
                return Convert.ToByte((bool)value).ToString("X2", null);
            case TypeCode.Char:
                return ((ushort)((char)value)).ToString("X4", null);
            case TypeCode.SByte:
                return ((byte)((sbyte)value)).ToString("X2", null);
            case TypeCode.Byte:
                return ((byte)value).ToString("X2", null);
            case TypeCode.Int16:
                return ((ushort)((short)value)).ToString("X4", null);
            case TypeCode.UInt16:
                return ((ushort)value).ToString("X4", null);
            case TypeCode.Int32:
                return ((uint)((int)value)).ToString("X8", null);
            case TypeCode.UInt32:
                return ((uint)value).ToString("X8", null);
            case TypeCode.Int64:
                return ((ulong)((long)value)).ToString("X16", null);
            case TypeCode.UInt64:
                return ((ulong)value).ToString("X16", null);
            default:
                throw new InvalidOperationException(Environment.GetResourceString("Unknown enum type."));
            }
        }
References System.Environment.GetResourceString(), System.Convert.GetTypeCode(), System.Convert.ToByte(), and System.value.
Referenced by System.Enum.Format(), and System.Enum.ToString().