Terraria Decompiled: NVorbis.Ogg.PacketProvider.FindPacket
FindPacket()
int NVorbis.Ogg.PacketProvider.FindPacket (int pageIndex, ref long granulePos, GetPacketGranuleCount getPacketGranuleCount) inline private
Definition at line 127 of file PacketProvider.cs.
        {
            int num = 0;
            long num2;
            bool flag;
            bool flag2;
            bool flag3;
            int num3;
            int num4;
            if (!this._reader.GetPage(pageIndex - 1, out num2, out flag, out flag2, out flag3, out num3, out num4))
            {
                throw new InvalidDataException("Could not get page?!");
            }
            if (flag3)
            {
                num = 1;
            }
            long num5;
            bool flag4;
            bool flag5;
            int num6;
            if (!this._reader.GetPage(pageIndex, out num5, out flag4, out flag5, out flag3, out num6, out num4))
            {
                throw new InvalidDataException("Could not get found page?!");
            }
            if (flag3)
            {
                num6--;
            }
            int num7 = num6;
            bool flag6 = !flag3;
            long num8 = num5;
            while (num8 > granulePos && --num7 >= num)
            {
                Packet packet = this.CreatePacket(ref pageIndex, ref num7, false, num5, num7 == 0 && flag4, flag3, num6, 0);
                if (packet == null)
                {
                    throw new InvalidDataException("Could not find end of continuation!");
                }
                num8 -= (long)getPacketGranuleCount(packet, flag6);
                flag6 = false;
            }
            if (num7 >= num)
            {
                granulePos = num8;
                return num7;
            }
            int num9 = pageIndex;
            int num10 = -1;
            if (!this.NormalizePacketIndex(ref num9, ref num10))
            {
                throw new InvalidDataException("Failed to normalize packet index?");
            }
            Packet packet2 = this.CreatePacket(ref num9, ref num10, false, num8, false, flag5, num10 + 1, 0);
            if (packet2 == null)
            {
                throw new InvalidDataException("Could not load previous packet!");
            }
            granulePos = num8 - (long)getPacketGranuleCount(packet2, false);
            return -1;
        }
References NVorbis.Ogg.PacketProvider._reader, NVorbis.Ogg.PacketProvider.CreatePacket(), NVorbis.Contracts.Ogg.IStreamPageReader.GetPage(), long, and NVorbis.Ogg.PacketProvider.NormalizePacketIndex().
Referenced by NVorbis.Ogg.PacketProvider.SeekTo().