Terraria Decompiled: NVorbis.Ogg.PacketProvider.NormalizePacketIndex
NormalizePacketIndex()
bool NVorbis.Ogg.PacketProvider.NormalizePacketIndex (ref int pageIndex, ref int packetIndex) inline private
Definition at line 190 of file PacketProvider.cs.
        {
            long num;
            bool flag;
            bool flag2;
            bool flag3;
            int num2;
            int num3;
            if (!this._reader.GetPage(pageIndex, out num, out flag, out flag2, out flag3, out num2, out num3))
            {
                return false;
            }
            int num4 = pageIndex;
            int i;
            bool flag4;
            int num5;
            for (i = packetIndex; i < (flag2 ? 1 : 0); i += num5 - (flag4 ? 1 : 0))
            {
                if (flag2 && flag)
                {
                    return false;
                }
                flag4 = flag2;
                bool flag5;
                if (!this._reader.GetPage(--num4, out num, out flag, out flag2, out flag5, out num5, out num3))
                {
                    return false;
                }
                if (flag4 && !flag5)
                {
                    return false;
                }
            }
            pageIndex = num4;
            packetIndex = i;
            return true;
        }
References NVorbis.Ogg.PacketProvider._reader, and NVorbis.Contracts.Ogg.IStreamPageReader.GetPage().
Referenced by NVorbis.Ogg.PacketProvider.FindPacket(), and NVorbis.Ogg.PacketProvider.SeekTo().