Terraria Decompiled: Terraria.GameContent.Shaders.WaterShaderData.InitRenderTargets
InitRenderTargets()
void Terraria.GameContent.Shaders.WaterShaderData.InitRenderTargets (int width, int height) inline private
Definition at line 356 of file WaterShaderData.cs.
        {
            this._lastScreenWidth = width;
            this._lastScreenHeight = height;
            width = (int)((float)width * 0.25f);
            height = (int)((float)height * 0.25f);
            try
            {
                this._noDistortionTexture = new Texture2D(Main.instance.GraphicsDevice, 1, 1, false, SurfaceFormat.Color);
                this._noDistortionTexture.SetData<Color>(new Color[]
                {
                    new Color(0.5f, 0.5f, 0f, 1f)
                });
                this._distortionTarget = new RenderTarget2D(Main.instance.GraphicsDevice, width, height, false, SurfaceFormat.Color, DepthFormat.None, 0, RenderTargetUsage.PreserveContents);
                this._distortionTargetSwap = new RenderTarget2D(Main.instance.GraphicsDevice, width, height, false, SurfaceFormat.Color, DepthFormat.None, 0, RenderTargetUsage.PreserveContents);
                this._usingRenderTargets = true;
                this._clearNextFrame = true;
            }
            catch (Exception ex)
            {
                Lighting.Mode = LightMode.Retro;
                this._usingRenderTargets = false;
                Console.WriteLine("Failed to create water distortion render targets. " + ex);
            }
        }
References Terraria.GameContent.Shaders.WaterShaderData._noDistortionTexture, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Game.GraphicsDevice, Terraria.Main.instance, int, Microsoft.Xna.Framework.Graphics.Texture2D, and System.Console.WriteLine().
Referenced by Terraria.GameContent.Shaders.WaterShaderData.ValidateRenderTargets(), and Terraria.GameContent.Shaders.WaterShaderData.WaterShaderData().