Terraria Decompiled: Terraria.GameContent.Shaders.WaterShaderData.ReleaseRenderTargets
ReleaseRenderTargets()
void Terraria.GameContent.Shaders.WaterShaderData.ReleaseRenderTargets () inline private
Definition at line 383 of file WaterShaderData.cs.
        {
            try
            {
                if (this._distortionTarget != null)
                {
                    this._distortionTarget.Dispose();
                }
                if (this._distortionTargetSwap != null)
                {
                    this._distortionTargetSwap.Dispose();
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error disposing of water distortion render targets. " + ex);
            }
            this._distortionTarget = null;
            this._distortionTargetSwap = null;
            this._usingRenderTargets = false;
        }
References Terraria.GameContent.Shaders.WaterShaderData._distortionTarget, Terraria.GameContent.Shaders.WaterShaderData._distortionTargetSwap, Microsoft.Xna.Framework.Graphics.RenderTarget2D.Dispose(), and System.Console.WriteLine().
Referenced by Terraria.GameContent.Shaders.WaterShaderData.ValidateRenderTargets(), and Terraria.GameContent.Shaders.WaterShaderData.WaterShaderData().