Terraria Decompiled: System.LocalDataStore.SetData
SetData()
void System.LocalDataStore.SetData (LocalDataStoreSlot slot, object data) inline
Definition at line 49 of file LocalDataStore.cs.
        {
            this.m_Manager.ValidateSlot(slot);
            int slot2 = slot.Slot;
            if (slot2 >= 0)
            {
                LocalDataStoreElement localDataStoreElement = ((slot2 < this.m_DataTable.Length) ? this.m_DataTable[slot2] : null);
                if (localDataStoreElement == null)
                {
                    localDataStoreElement = this.PopulateElement(slot);
                }
                if (localDataStoreElement.Cookie == slot.Cookie)
                {
                    localDataStoreElement.Value = data;
                    return;
                }
            }
            throw new InvalidOperationException(Environment.GetResourceString("LocalDataStoreSlot storage has been freed."));
        }
References System.LocalDataStoreElement.Cookie, System.LocalDataStoreSlot.Cookie, System.Environment.GetResourceString(), System.LocalDataStore.m_DataTable, System.LocalDataStore.m_Manager, System.LocalDataStore.PopulateElement(), System.LocalDataStoreSlot.Slot, and System.LocalDataStoreMgr.ValidateSlot().
Referenced by System.Threading.Thread.SetData().