Terraria Decompiled: System.LocalDataStore.PopulateElement
PopulateElement()
LocalDataStoreElement System.LocalDataStore.PopulateElement (LocalDataStoreSlot slot) inline private
Definition at line 85 of file LocalDataStore.cs.
        {
            bool flag = false;
            RuntimeHelpers.PrepareConstrainedRegions();
            LocalDataStoreElement localDataStoreElement;
            try
            {
                Monitor.Enter(this.m_Manager, ref flag);
                int slot2 = slot.Slot;
                if (slot2 < 0)
                {
                    throw new InvalidOperationException(Environment.GetResourceString("LocalDataStoreSlot storage has been freed."));
                }
                if (slot2 >= this.m_DataTable.Length)
                {
                    LocalDataStoreElement[] array = new LocalDataStoreElement[this.m_Manager.GetSlotTableLength()];
                    Array.Copy(this.m_DataTable, array, this.m_DataTable.Length);
                    this.m_DataTable = array;
                }
                if (this.m_DataTable[slot2] == null)
                {
                    this.m_DataTable[slot2] = new LocalDataStoreElement(slot.Cookie);
                }
                localDataStoreElement = this.m_DataTable[slot2];
            }
            finally
            {
                if (flag)
                {
                    Monitor.Exit(this.m_Manager);
                }
            }
            return localDataStoreElement;
        }
References System.array, System.LocalDataStoreSlot.Cookie, System.Array.Copy(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Environment.GetResourceString(), System.LocalDataStoreMgr.GetSlotTableLength(), System.LocalDataStore.m_DataTable, System.LocalDataStore.m_Manager, System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), and System.LocalDataStoreSlot.Slot.
Referenced by System.LocalDataStore.SetData().