Terraria Decompiled: Terraria.Utilities.CrashWatcher.Inititialize
Inititialize()
static void Terraria.Utilities.CrashWatcher.Inititialize () inline static
Definition at line 93 of file CrashWatcher.cs.
        {
            Console.WriteLine("Error Logging Enabled.");
            AppDomain.CurrentDomain.FirstChanceException += delegate(object sender, FirstChanceExceptionEventArgs exceptionArgs)
            {
                if (Main.IsFullScreenThatWouldBeStuckOnCrashMessage())
                {
                    return;
                }
                if (CrashWatcher.LogAllExceptions && !false)
                {
                    string text = CrashWatcher.PrintException(exceptionArgs.Exception);
                    Console.Write("================\r\n" + string.Format("{0}: First-Chance Exception\r\nThread: {1} [{2}]\r\nCulture: {3}\r\nException: {4}\r\n", new object[]
                    {
                        DateTime.Now,
                        Thread.CurrentThread.ManagedThreadId,
                        Thread.CurrentThread.Name,
                        Thread.CurrentThread.CurrentCulture.Name,
                        text
                    }) + "================\r\n\r\n");
                }
            };
            AppDomain.CurrentDomain.UnhandledException += delegate(object sender, UnhandledExceptionEventArgs exceptionArgs)
            {
                if (Main.IsFullScreenThatWouldBeStuckOnCrashMessage())
                {
                    return;
                }
                string text2 = CrashWatcher.PrintException((Exception)exceptionArgs.ExceptionObject);
                Console.Write("================\r\n" + string.Format("{0}: Unhandled Exception\r\nThread: {1} [{2}]\r\nCulture: {3}\r\nException: {4}\r\n", new object[]
                {
                    DateTime.Now,
                    Thread.CurrentThread.ManagedThreadId,
                    Thread.CurrentThread.Name,
                    Thread.CurrentThread.CurrentCulture.Name,
                    text2
                }) + "================\r\n");
                if (CrashWatcher.DumpOnCrash)
                {
                    CrashDump.WriteException(CrashWatcher.CrashDumpOptions, CrashWatcher.DumpPath);
                }
            };
        }
References Terraria.Utilities.CrashWatcher.CrashDumpOptions, System.Threading.Thread.CurrentCulture, System.Threading.Thread.CurrentThread, Terraria.Utilities.CrashWatcher.DumpOnCrash, Terraria.Utilities.CrashWatcher.DumpPath, System.Runtime.ExceptionServices.FirstChanceExceptionEventArgs.Exception, System.UnhandledExceptionEventArgs.ExceptionObject, System.Format, Terraria.Main.IsFullScreenThatWouldBeStuckOnCrashMessage(), Terraria.Utilities.CrashWatcher.LogAllExceptions, System.Threading.Thread.ManagedThreadId, System.Threading.Thread.Name, System.DateTime.Now, Terraria.Utilities.CrashWatcher.PrintException(), System.text, System.Console.Write(), Terraria.Utilities.CrashDump.WriteException(), and System.Console.WriteLine().
Referenced by Terraria.Program.SetupLogging().