Terraria Decompiled: Newtonsoft.Json.Converters.EntityKeyMemberConverter.WriteJson
WriteJson()
override void Newtonsoft.Json.Converters.EntityKeyMemberConverter.WriteJson (JsonWriter writer, object value, JsonSerializer serializer) inline
Definition at line 12 of file EntityKeyMemberConverter.cs.
        {
            EntityKeyMemberConverter.EnsureReflectionObject(value.GetType());
            DefaultContractResolver defaultContractResolver = serializer.ContractResolver as DefaultContractResolver;
            string text = (string)EntityKeyMemberConverter._reflectionObject.GetValue(value, "Key");
            object value2 = EntityKeyMemberConverter._reflectionObject.GetValue(value, "Value");
            Type type = ((value2 != null) ? value2.GetType() : null);
            writer.WriteStartObject();
            writer.WritePropertyName((defaultContractResolver != null) ? defaultContractResolver.GetResolvedPropertyName("Key") : "Key");
            writer.WriteValue(text);
            writer.WritePropertyName((defaultContractResolver != null) ? defaultContractResolver.GetResolvedPropertyName("Type") : "Type");
            writer.WriteValue((type != null) ? type.FullName : null);
            writer.WritePropertyName((defaultContractResolver != null) ? defaultContractResolver.GetResolvedPropertyName("Value") : "Value");
            if (type != null)
            {
                string text2;
                if (JsonSerializerInternalWriter.TryConvertToString(value2, type, out text2))
                {
                    writer.WriteValue(text2);
                }
                else
                {
                    writer.WriteValue(value2);
                }
            }
            else
            {
                writer.WriteNull();
            }
            writer.WriteEndObject();
        }
References Newtonsoft.Json.Converters.EntityKeyMemberConverter._reflectionObject, Newtonsoft.Json.Converters.EntityKeyMemberConverter.EnsureReflectionObject(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetResolvedPropertyName(), Newtonsoft.Json.Utilities.ReflectionObject.GetValue(), System.text, Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.TryConvertToString(), System.value, Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WriteNull(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.JsonWriter.WriteValue().