Terraria Decompiled: Newtonsoft.Json.Utilities.DictionaryWrapper.Remove
Remove() [1/3]
bool Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.Remove (KeyValuePair< TKey, TValue > item) inline
Definition at line 218 of file DictionaryWrapper.cs.
        {
            if (this._dictionary == null)
            {
                return this._genericDictionary.Remove(item);
            }
            if (!this._dictionary.Contains(item.Key))
            {
                return true;
            }
            if (object.Equals(this._dictionary[item.Key], item.Value))
            {
                this._dictionary.Remove(item.Key);
                return true;
            }
            return false;
        }
References Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >._dictionary, Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >._genericDictionary, System.Collections.Generic.ICollection< T >.Contains(), System.item, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.Collections.IDictionary.Remove(), and System.Collections.Generic.IDictionary< TKey, TValue >.Remove().