Terraria Decompiled: Mono.Security.Cryptography.RSAManaged.ToXmlString
ToXmlString()
override string Mono.Security.Cryptography.RSAManaged.ToXmlString (bool includePrivateParameters) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 394 of file RSAManaged.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            RSAParameters rsaparameters = this.ExportParameters(includePrivateParameters);
            try
            {
                stringBuilder.Append("<RSAKeyValue>");
                stringBuilder.Append("<Modulus>");
                stringBuilder.Append(Convert.ToBase64String(rsaparameters.Modulus));
                stringBuilder.Append("</Modulus>");
                stringBuilder.Append("<Exponent>");
                stringBuilder.Append(Convert.ToBase64String(rsaparameters.Exponent));
                stringBuilder.Append("</Exponent>");
                if (includePrivateParameters)
                {
                    if (rsaparameters.P != null)
                    {
                        stringBuilder.Append("<P>");
                        stringBuilder.Append(Convert.ToBase64String(rsaparameters.P));
                        stringBuilder.Append("</P>");
                    }
                    if (rsaparameters.Q != null)
                    {
                        stringBuilder.Append("<Q>");
                        stringBuilder.Append(Convert.ToBase64String(rsaparameters.Q));
                        stringBuilder.Append("</Q>");
                    }
                    if (rsaparameters.DP != null)
                    {
                        stringBuilder.Append("<DP>");
                        stringBuilder.Append(Convert.ToBase64String(rsaparameters.DP));
                        stringBuilder.Append("</DP>");
                    }
                    if (rsaparameters.DQ != null)
                    {
                        stringBuilder.Append("<DQ>");
                        stringBuilder.Append(Convert.ToBase64String(rsaparameters.DQ));
                        stringBuilder.Append("</DQ>");
                    }
                    if (rsaparameters.InverseQ != null)
                    {
                        stringBuilder.Append("<InverseQ>");
                        stringBuilder.Append(Convert.ToBase64String(rsaparameters.InverseQ));
                        stringBuilder.Append("</InverseQ>");
                    }
                    stringBuilder.Append("<D>");
                    stringBuilder.Append(Convert.ToBase64String(rsaparameters.D));
                    stringBuilder.Append("</D>");
                }
                stringBuilder.Append("</RSAKeyValue>");
            }
            catch
            {
                if (rsaparameters.P != null)
                {
                    Array.Clear(rsaparameters.P, 0, rsaparameters.P.Length);
                }
                if (rsaparameters.Q != null)
                {
                    Array.Clear(rsaparameters.Q, 0, rsaparameters.Q.Length);
                }
                if (rsaparameters.DP != null)
                {
                    Array.Clear(rsaparameters.DP, 0, rsaparameters.DP.Length);
                }
                if (rsaparameters.DQ != null)
                {
                    Array.Clear(rsaparameters.DQ, 0, rsaparameters.DQ.Length);
                }
                if (rsaparameters.InverseQ != null)
                {
                    Array.Clear(rsaparameters.InverseQ, 0, rsaparameters.InverseQ.Length);
                }
                if (rsaparameters.D != null)
                {
                    Array.Clear(rsaparameters.D, 0, rsaparameters.D.Length);
                }
                throw;
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Array.Clear(), System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, System.Security.Cryptography.RSAParameters.Exponent, Mono.Security.Cryptography.RSAManaged.ExportParameters(), System.Security.Cryptography.RSAParameters.InverseQ, System.Security.Cryptography.RSAParameters.Modulus, System.Security.Cryptography.RSAParameters.P, System.Security.Cryptography.RSAParameters.Q, System.Convert.ToBase64String(), and System.Text.StringBuilder.ToString().