Terraria Decompiled: Mono.Security.Cryptography.RSAManaged.ExportParameters
ExportParameters()
override RSAParameters Mono.Security.Cryptography.RSAManaged.ExportParameters (bool includePrivateParameters) inline
Definition at line 201 of file RSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException(Locale.GetText("Keypair was disposed"));
            }
            if (!this.keypairGenerated)
            {
                this.GenerateKeyPair();
            }
            RSAParameters rsaparameters = default(RSAParameters);
            rsaparameters.Exponent = this.e.GetBytes();
            rsaparameters.Modulus = this.n.GetBytes();
            if (includePrivateParameters)
            {
                if (this.d == null)
                {
                    throw new CryptographicException("Missing private key");
                }
                rsaparameters.D = this.d.GetBytes();
                if (rsaparameters.D.Length != rsaparameters.Modulus.Length)
                {
                    byte[] array = new byte[rsaparameters.Modulus.Length];
                    Buffer.BlockCopy(rsaparameters.D, 0, array, array.Length - rsaparameters.D.Length, rsaparameters.D.Length);
                    rsaparameters.D = array;
                }
                if (this.p != null && this.q != null && this.dp != null && this.dq != null && this.qInv != null)
                {
                    int num = this.KeySize >> 4;
                    rsaparameters.P = this.GetPaddedValue(this.p, num);
                    rsaparameters.Q = this.GetPaddedValue(this.q, num);
                    rsaparameters.DP = this.GetPaddedValue(this.dp, num);
                    rsaparameters.DQ = this.GetPaddedValue(this.dq, num);
                    rsaparameters.InverseQ = this.GetPaddedValue(this.qInv, num);
                }
            }
            return rsaparameters;
        }
References System.array, System.Buffer.BlockCopy(), Mono.Security.Cryptography.RSAManaged.d, System.Security.Cryptography.RSAParameters.D, Mono.Security.Cryptography.RSAManaged.dp, Mono.Security.Cryptography.RSAManaged.dq, Mono.Security.Cryptography.RSAManaged.e, Mono.Security.Cryptography.RSAManaged.GenerateKeyPair(), Mono.Math.BigInteger.GetBytes(), Mono.Security.Cryptography.RSAManaged.GetPaddedValue(), Locale.GetText(), Mono.Security.Cryptography.RSAManaged.keypairGenerated, Mono.Security.Cryptography.RSAManaged.m_disposed, System.Security.Cryptography.RSAParameters.Modulus, Mono.Security.Cryptography.RSAManaged.n, Mono.Security.Cryptography.RSAManaged.p, Mono.Security.Cryptography.RSAManaged.q, and Mono.Security.Cryptography.RSAManaged.qInv.
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.ExportParameters(), System.Security.Cryptography.RSACryptoServiceProvider.ImportCspBlob(), and Mono.Security.Cryptography.RSAManaged.ToXmlString().