Terraria Decompiled: Mono.Security.Cryptography.RSAManaged.EncryptValue
EncryptValue()
override byte[] Mono.Security.Cryptography.RSAManaged.EncryptValue (byte[] rgb) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 182 of file RSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException("public key");
            }
            if (!this.keypairGenerated)
            {
                this.GenerateKeyPair();
            }
            BigInteger bigInteger = new BigInteger(rgb);
            BigInteger bigInteger2 = bigInteger.ModPow(this.e, this.n);
            byte[] paddedValue = this.GetPaddedValue(bigInteger2, this.KeySize >> 3);
            bigInteger.Clear();
            bigInteger2.Clear();
            return paddedValue;
        }
References Mono.Math.BigInteger.Clear(), Mono.Security.Cryptography.RSAManaged.e, Mono.Security.Cryptography.RSAManaged.GenerateKeyPair(), Mono.Security.Cryptography.RSAManaged.GetPaddedValue(), Mono.Security.Cryptography.RSAManaged.keypairGenerated, Mono.Security.Cryptography.RSAManaged.KeySize, Mono.Security.Cryptography.RSAManaged.m_disposed, Mono.Math.BigInteger.ModPow(), and Mono.Security.Cryptography.RSAManaged.n.
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.EncryptValue().