Terraria Decompiled: Terraria.GameContent.UI.States.UITextWrappingTest.UITextWrappingTest
UITextWrappingTest() [1/2]
Terraria.GameContent.UI.States.UITextWrappingTest.UITextWrappingTest () inline
Definition at line 19 of file UITextWrappingTest.cs.
        {
            UIPanel uipanel = new UIPanel
            {
                Top = StyleDimension.FromPixels(100f),
                Left = StyleDimension.FromPixelsAndPercent(-400f, 0.5f),
                Width = StyleDimension.FromPixels(300f),
                Height = StyleDimension.FromPixels(40f),
                BackgroundColor = new Color(43, 56, 101),
                BorderColor = Color.Transparent
            };
            this.modeText = new UIText(this.mode.ToString(), 0.8f, false)
            {
                TextOriginX = 0f,
                Width = StyleDimension.FromPercent(1f),
                Height = StyleDimension.FromPercent(1f)
            };
            uipanel.Append(this.modeText);
            uipanel.OnLeftClick += delegate(UIMouseEvent e, UIElement sender)
            {
                this.CycleMode(1);
            };
            uipanel.OnRightClick += delegate(UIMouseEvent e, UIElement sender)
            {
                this.CycleMode(-1);
            };
            base.Append(uipanel);
            this.scaleText = new UIText(this.ScaleText, 0.8f, false)
            {
                TextOriginX = 0f,
                Top = StyleDimension.FromPixels(150f),
                Left = StyleDimension.FromPixelsAndPercent(-400f, 0.5f),
                Width = StyleDimension.FromPixels(300f),
                Height = StyleDimension.FromPixels(40f)
            };
            base.Append(this.scaleText);
            this.langText = new UIText(this.LangText, 0.8f, false)
            {
                TextOriginX = 1f,
                HAlign = 1f,
                Top = StyleDimension.FromPixels(150f),
                Left = StyleDimension.FromPixelsAndPercent(400f, -0.5f),
                Width = StyleDimension.FromPixels(300f),
                Height = StyleDimension.FromPixels(40f)
            };
            base.Append(this.langText);
            UIList uilist = new UIList();
            uilist.Top = StyleDimension.FromPixels(200f);
            uilist.Left = StyleDimension.FromPixelsAndPercent(-400f, 0.5f);
            uilist.Width = StyleDimension.FromPixels(300f);
            uilist.Height = StyleDimension.FromPixelsAndPercent(-200f, 1f);
            uilist.ListPadding = 5f;
            uilist.ManualSortMethod = delegate(List<UIElement> _)
            {
            };
            this.list = uilist;
            this.list.SetPadding(0f);
            base.Append(this.list);
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue);
            uiscrollbar.SetView(100f, 1000f);
            uiscrollbar.Height.Set(-20f, 1f);
            uiscrollbar.HAlign = 1f;
            uiscrollbar.VAlign = 0.5f;
            uiscrollbar.Left.Set(6f, 0f);
            this.list.SetScrollbar(uiscrollbar);
            this.ResetList();
        }
References Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.UITextWrappingTest.CycleMode(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UITextWrappingTest.LangText, Terraria.GameContent.UI.States.UITextWrappingTest.langText, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UITextWrappingTest.list, Terraria.GameContent.UI.States.UITextWrappingTest.mode, Terraria.GameContent.UI.States.UITextWrappingTest.modeText, Terraria.GameContent.UI.States.UITextWrappingTest.ResetList(), Terraria.GameContent.UI.States.UITextWrappingTest.ScaleText, Terraria.GameContent.UI.States.UITextWrappingTest.scaleText, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UITextWrappingTest.UIText, and Terraria.UI.UIElement.Width.