Terraria Decompiled: Terraria.GameContent.UI.States.UITextWrappingTest.MakeElement
MakeElement()
UIElement Terraria.GameContent.UI.States.UITextWrappingTest.MakeElement (string value) inline private
Definition at line 158 of file UITextWrappingTest.cs.
        {
            UIElement container = new UIPanel
            {
                Width = StyleDimension.FromPercent(1f),
                Height = StyleDimension.FromPixels((float)(50 * this.scale)),
                BackgroundColor = new Color(43, 56, 101),
                BorderColor = Color.Transparent
            };
            container.SetPadding(UITextWrappingTest.TextPadding);
            if (this.mode == UITextWrappingTest.Mode.UIText)
            {
                UIText text3 = new UIText(value, (float)this.scale / 100f, false)
                {
                    TextOriginX = 0f,
                    HAlign = 0f,
                    VAlign = 0f,
                    Width = StyleDimension.FromPercent(1f),
                    Height = StyleDimension.FromPercent(1f),
                    IsWrapped = true
                };
                text3.OnInternalTextChange += delegate
                {
                    container.Height = new StyleDimension(text3.MinHeight.Pixels, 0f);
                };
                container.Append(text3);
            }
            else
            {
                UITextWrappingTest.TestElement text = new UITextWrappingTest.TestElement(value, (float)this.scale / 100f, this.mode)
                {
                    Width = StyleDimension.FromPercent(1f)
                };
                UITextWrappingTest.TestElement text2 = text;
                text2.OnHeightUpdate = (Action)Delegate.Combine(text2.OnHeightUpdate, new Action(delegate
                {
                    container.Height = new StyleDimension(text.MinHeight.Pixels + container.PaddingTop + container.PaddingBottom, 0f);
                }));
                container.Append(text);
            }
            return container;
        }
References System.Action(), Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, System.Delegate.Combine(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.MinHeight, Terraria.GameContent.UI.States.UITextWrappingTest.mode, Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.OnHeightUpdate, Terraria.UI.UIElement.PaddingBottom, Terraria.UI.UIElement.PaddingTop, Terraria.UI.StyleDimension.Pixels, Terraria.GameContent.UI.States.UITextWrappingTest.scale, Terraria.UI.UIElement.SetPadding(), System.text, Terraria.GameContent.UI.States.UITextWrappingTest.TextPadding, Terraria.GameContent.UI.States.UITextWrappingTest.UIText, Terraria.UI.UIElement.VAlign, System.value, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UITextWrappingTest.ResetList().