Terraria Decompiled: Terraria.GameContent.UI.States.UITextWrappingTest.ResetList
ResetList()
void Terraria.GameContent.UI.States.UITextWrappingTest.ResetList () inline private
Definition at line 116 of file UITextWrappingTest.cs.
        {
            this.modeText.SetText(this.mode.ToString());
            this.list.Clear();
            this.list.Add(this.MakeElement("A test string in english.\nSecond line.\n\n^ Double line break\nLooooooooooooooonglinewithnospaces"));
            this.list.Add(this.MakeElement("Ends with newline\n"));
            this.list.Add(this.MakeElement("Non-breaking space: с\u00a0микротранзакциями\n"));
            this.list.Add(this.MakeElement("Thin\u2009Space\nHair\u200aSpace\nZero\u200bWidth\u200bSpace"));
            this.list.Add(this.NewSeparator());
            this.list.Add(this.MakeElement("せいなる スライムが がったいして できた 生き物。ごうまんで 力づよく きらめく けっしょうに おおわれている。つばさが 生える という うわさも ある。"));
            this.list.Add(this.MakeElement("정화된 슬라임들이 모두 통합되어, 눈부신 수정으로 장식된 거만하고 압도적인 힘이 되었습니다. 날개가 돋아난다는 소문도 있습니다. "));
            this.list.Add(this.MakeElement("Святые слизни объединяются в величественную всесокрушающую массу, украшенную превосходными кристаллами. Говорят, она даже может отрастить крылья."));
            this.list.Add(this.MakeElement("神圣史莱姆合并成了一种高傲的粉碎性力量，这种力量佩戴着闪耀的水晶。传说她会长出翅膀。"));
            this.list.Add(this.MakeElement("神聖史萊姆融合後，會點綴著閃耀的水晶，擁有傲視一切的粉碎性力量。傳說她會長出翅膀。"));
            this.list.Add(this.NewSeparator());
            this.list.Add(this.MakeElement("fullwidth terminators。bang！comma，fullstop。rcomma、colon：question？"));
            this.list.Add(this.MakeElement("Chinese separation〈聖聖聖聖〉《聖聖》「聖聖」『聖聖』【聖聖〔聖聖】〖聖聖〗!%),.:;?]}$100,25.24%"));
            this.list.Add(this.NewSeparator());
            this.list.Add(this.MakeElement(new LocalizedText("", "Keybind glyph support {InputTrigger_UseOrAttack} and {InputTrigger_InteractWithTile}").Value));
            this.list.Add(this.MakeElement("[c/FF0000:SomeRedText] [c/00FF00:SomeGreenText] [c/0000FF:SomeBlueText]"));
            this.list.Add(this.MakeElement("[c/FF0000:SomeRedText][c/00FF00:SomeGreenText][c/0000FF:SomeBlueText]"));
            this.list.Add(this.MakeElement("[c/0000FF:Long colored text, with escaped square brackets [\\] inside]"));
            this.list.Add(this.MakeElement("Items[i:1][i:2][i:3][i:4][i:5][i:6][i:7][i:100][i:1000]"));
            this.list.Add(this.MakeElement("ItemsOnSeparateLines\n[i:1]\n[i:2]\n[i:3]"));
            this.list.Add(this.MakeElement("Items and text [i:1] then stuff [i:2] and some more [i:3] etc"));
            this.list.Add(this.MakeElement("nospacebetweenitems[i:6]andtext[i:7]nospacebetweenitems[i:8]andtext[i:9]"));
            this.list.Add(this.MakeElement("[g:0][g:1][g:2][g:3][g:4][g:5][g:6][g:7][g:8][g:9][g:10][g:11][g:12][g:13][g:14][g:15][g:16][g:17][g:18][g:19][g:20][g:21][g:22][g:23][g:24][g:25]"));
            this.list.Add(this.MakeElement(Language.GetTextValue("Achievements.Completed", "[a:TRANSMUTE_ITEM]")));
            this.list.Add(this.MakeElement("[a:TO_INFINITY_AND_BEYOND][a:PURIFY_ENTIRE_WORLD][a:TO_INFINITY_AND_BEYOND][a:TRANSMUTE_ITEM][a:OBTAIN_HAMMER][a:BENCHED][a:HEAVY_METAL][a:GET_GOLDEN_DELIGHT][a:MINER_FOR_FIRE][a:HEAD_IN_THE_CLOUDS][a:GET_TERRASPARK_BOOTS]"));
        }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.UI.States.UITextWrappingTest.list, Terraria.GameContent.UI.States.UITextWrappingTest.MakeElement(), Terraria.GameContent.UI.States.UITextWrappingTest.mode, Terraria.GameContent.UI.States.UITextWrappingTest.modeText, Terraria.GameContent.UI.States.UITextWrappingTest.NewSeparator(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UITextWrappingTest.CycleMode(), Terraria.GameContent.UI.States.UITextWrappingTest.UITextWrappingTest(), and Terraria.GameContent.UI.States.UITextWrappingTest.Update().