Terraria Decompiled: Mono.Security.Cryptography.RSAManaged.DecryptValue
DecryptValue()
override byte[] Mono.Security.Cryptography.RSAManaged.DecryptValue (byte[] rgb) inline virtual
Reimplemented from System.Security.Cryptography.RSA.
Definition at line 129 of file RSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException("private key");
            }
            if (!this.keypairGenerated)
            {
                this.GenerateKeyPair();
            }
            BigInteger bigInteger = new BigInteger(rgb);
            BigInteger bigInteger2 = null;
            if (this.keyBlinding)
            {
                bigInteger2 = BigInteger.GenerateRandom(this.n.BitCount());
                bigInteger = bigInteger2.ModPow(this.e, this.n) * bigInteger % this.n;
            }
            BigInteger bigInteger6;
            if (this.isCRTpossible)
            {
                BigInteger bigInteger3 = bigInteger.ModPow(this.dp, this.p);
                BigInteger bigInteger4 = bigInteger.ModPow(this.dq, this.q);
                if (bigInteger4 > bigInteger3)
                {
                    BigInteger bigInteger5 = this.p - (bigInteger4 - bigInteger3) * this.qInv % this.p;
                    bigInteger6 = bigInteger4 + this.q * bigInteger5;
                }
                else
                {
                    BigInteger bigInteger5 = (bigInteger3 - bigInteger4) * this.qInv % this.p;
                    bigInteger6 = bigInteger4 + this.q * bigInteger5;
                }
            }
            else
            {
                if (this.PublicOnly)
                {
                    throw new CryptographicException(Locale.GetText("Missing private key to decrypt value."));
                }
                bigInteger6 = bigInteger.ModPow(this.d, this.n);
            }
            if (this.keyBlinding)
            {
                bigInteger6 = bigInteger6 * bigInteger2.ModInverse(this.n) % this.n;
                bigInteger2.Clear();
            }
            byte[] paddedValue = this.GetPaddedValue(bigInteger6, this.KeySize >> 3);
            bigInteger.Clear();
            bigInteger6.Clear();
            return paddedValue;
        }
References Mono.Math.BigInteger.BitCount(), Mono.Math.BigInteger.Clear(), Mono.Security.Cryptography.RSAManaged.d, Mono.Security.Cryptography.RSAManaged.dp, Mono.Security.Cryptography.RSAManaged.dq, Mono.Security.Cryptography.RSAManaged.e, Mono.Security.Cryptography.RSAManaged.GenerateKeyPair(), Mono.Math.BigInteger.GenerateRandom(), Mono.Security.Cryptography.RSAManaged.GetPaddedValue(), Locale.GetText(), Mono.Security.Cryptography.RSAManaged.isCRTpossible, Mono.Security.Cryptography.RSAManaged.keyBlinding, Mono.Security.Cryptography.RSAManaged.keypairGenerated, Mono.Security.Cryptography.RSAManaged.KeySize, Mono.Security.Cryptography.RSAManaged.m_disposed, Mono.Math.BigInteger.ModInverse(), Mono.Math.BigInteger.ModPow(), Mono.Security.Cryptography.RSAManaged.n, Mono.Security.Cryptography.RSAManaged.p, Mono.Security.Cryptography.RSAManaged.PublicOnly, Mono.Security.Cryptography.RSAManaged.q, and Mono.Security.Cryptography.RSAManaged.qInv.
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.DecryptValue().