Terraria Decompiled: Mono.Security.Cryptography.RSAManaged.ImportParameters
ImportParameters()
override void Mono.Security.Cryptography.RSAManaged.ImportParameters (RSAParameters parameters) inline
Definition at line 241 of file RSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException(Locale.GetText("Keypair was disposed"));
            }
            if (parameters.Exponent == null)
            {
                throw new CryptographicException(Locale.GetText("Missing Exponent"));
            }
            if (parameters.Modulus == null)
            {
                throw new CryptographicException(Locale.GetText("Missing Modulus"));
            }
            this.e = new BigInteger(parameters.Exponent);
            this.n = new BigInteger(parameters.Modulus);
            this.d = (this.dp = (this.dq = (this.qInv = (this.p = (this.q = null)))));
            if (parameters.D != null)
            {
                this.d = new BigInteger(parameters.D);
            }
            if (parameters.DP != null)
            {
                this.dp = new BigInteger(parameters.DP);
            }
            if (parameters.DQ != null)
            {
                this.dq = new BigInteger(parameters.DQ);
            }
            if (parameters.InverseQ != null)
            {
                this.qInv = new BigInteger(parameters.InverseQ);
            }
            if (parameters.P != null)
            {
                this.p = new BigInteger(parameters.P);
            }
            if (parameters.Q != null)
            {
                this.q = new BigInteger(parameters.Q);
            }
            this.keypairGenerated = true;
            bool flag = this.p != null && this.q != null && this.dp != null;
            this.isCRTpossible = flag && this.dq != null && this.qInv != null;
            if (!flag)
            {
                return;
            }
            bool flag2 = this.n == this.p * this.q;
            if (flag2)
            {
                BigInteger bigInteger = this.p - 1;
                BigInteger bigInteger2 = this.q - 1;
                BigInteger bigInteger3 = bigInteger * bigInteger2;
                BigInteger bigInteger4 = this.e.ModInverse(bigInteger3);
                flag2 = this.d == bigInteger4;
                if (!flag2 && this.isCRTpossible)
                {
                    flag2 = this.dp == bigInteger4 % bigInteger && this.dq == bigInteger4 % bigInteger2 && this.qInv == this.q.ModInverse(this.p);
                }
            }
            if (!flag2)
            {
                throw new CryptographicException(Locale.GetText("Private/public key mismatch"));
            }
        }
References System.Security.Cryptography.RSAParameters.D, System.Security.Cryptography.RSAParameters.DP, System.Security.Cryptography.RSAParameters.DQ, Mono.Security.Cryptography.RSAManaged.e, System.Security.Cryptography.RSAParameters.Exponent, Locale.GetText(), System.Security.Cryptography.RSAParameters.InverseQ, Mono.Security.Cryptography.RSAManaged.isCRTpossible, Mono.Security.Cryptography.RSAManaged.m_disposed, Mono.Math.BigInteger.ModInverse(), System.Security.Cryptography.RSAParameters.Modulus, Mono.Security.Cryptography.RSAManaged.p, System.Security.Cryptography.RSAParameters.P, Mono.Security.Cryptography.RSAManaged.q, and System.Security.Cryptography.RSAParameters.Q.
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.ImportParameters(), Mono.Security.Cryptography.CryptoConvert.TryImportCapiPrivateKeyBlob(), and Mono.Security.Cryptography.CryptoConvert.TryImportCapiPublicKeyBlob().