Terraria Decompiled: Terraria.GameContent.UI.States.UITextWrappingTest.Update
Update()
override void Terraria.GameContent.UI.States.UITextWrappingTest.Update (GameTime gameTime) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 213 of file UITextWrappingTest.cs.
        {
            if (Main.keyState.IsKeyDown(Keys.Escape))
            {
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                Main.menuMode = 0;
            }
            int num = 0;
            if (Main.keyState.IsKeyDown(Keys.Down) && Main.oldKeyState.IsKeyUp(Keys.Down))
            {
                num = -10;
            }
            if (Main.keyState.IsKeyDown(Keys.Up) && Main.oldKeyState.IsKeyUp(Keys.Up))
            {
                num = 10;
            }
            if (num != 0)
            {
                this.scale = Utils.Clamp<int>(this.scale + num, 50, 150);
                this.ResetList();
                this.scaleText.SetText(this.ScaleText);
            }
            this.langText.SetText(this.LangText);
            if (Main.mouseLeft)
            {
                Point point = Main.MouseScreen.ToPoint();
                CalculatedStyle dimensions = this.list.GetDimensions();
                if ((float)point.X > dimensions.X && (float)point.Y > dimensions.Y)
                {
                    this.list.Width = StyleDimension.FromPixels((float)point.X - dimensions.X);
                }
            }
            base.Update(gameTime);
        }
References Terraria.Utils.Clamp(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.GetDimensions(), Microsoft.Xna.Framework.Input.KeyboardState.IsKeyDown(), Microsoft.Xna.Framework.Input.KeyboardState.IsKeyUp(), Terraria.Main.keyState, Terraria.GameContent.UI.States.UITextWrappingTest.LangText, Terraria.GameContent.UI.States.UITextWrappingTest.langText, Terraria.GameContent.UI.States.UITextWrappingTest.list, Terraria.Main.mouseLeft, Terraria.Main.MouseScreen, Terraria.Main.oldKeyState, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.States.UITextWrappingTest.ResetList(), Terraria.GameContent.UI.States.UITextWrappingTest.ScaleText, Terraria.GameContent.UI.States.UITextWrappingTest.scaleText, Terraria.GameContent.UI.Elements.UIText.SetText(), Microsoft.Xna.Framework.Point.X, Terraria.UI.CalculatedStyle.X, Microsoft.Xna.Framework.Point.Y, and Terraria.UI.CalculatedStyle.Y.