Terraria Decompiled: Newtonsoft.Json.JsonSerializationException.Create
Create() [2/3]
static JsonSerializationException Newtonsoft.Json.JsonSerializationException.Create (JsonReader reader, string message) inline static package
Definition at line 34 of file JsonSerializationException.cs.
        {
            return JsonSerializationException.Create(reader, message, null);
        }
References Newtonsoft.Json.JsonSerializationException.Create().
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.AddAttribute(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CalculatePropertyValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateDocumentType(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateDynamic(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateInstruction(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(), Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EndProcessProperty(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureArrayContract(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(), Newtonsoft.Json.Converters.DataTableConverter.GetColumnDataType(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.GetReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateDictionary(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(), Newtonsoft.Json.JsonConvert.PopulateObject(), Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadAttributeElements(), Newtonsoft.Json.Converters.BinaryConverter.ReadByteArray(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadElement(), Newtonsoft.Json.Converters.BinaryConverter.ReadJson(), Newtonsoft.Json.Converters.DataTableConverter.ReadJson(), Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson(), Newtonsoft.Json.Converters.IsoDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(), Newtonsoft.Json.Converters.RegexConverter.ReadJson(), Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(), Newtonsoft.Json.Converters.VersionConverter.ReadJson(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadJson(), Newtonsoft.Json.Converters.ExpandoObjectConverter.ReadList(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(), Newtonsoft.Json.Converters.ExpandoObjectConverter.ReadObject(), Newtonsoft.Json.Converters.RegexConverter.ReadRegexObject(), Newtonsoft.Json.Converters.ExpandoObjectConverter.ReadValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetExtensionData(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ThrowUnexpectedEndException(), and Newtonsoft.Json.Converters.StringEnumConverter.WriteJson().