Terraria Decompiled: System.Reflection.PropertyInfo.GetGetMethod
GetGetMethod() [1/2]
MethodInfo System.Reflection.PropertyInfo.GetGetMethod () inline
Definition at line 75 of file PropertyInfo.cs.
        {
            return this.GetGetMethod(false);
        }
References System.Reflection.PropertyInfo.GetGetMethod().
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.CanReadMemberValue(), CsvHelper.CsvWriter.CanWrite(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateGetPropertyIL(), System.Reflection.Emit.PropertyOnTypeBuilderInst.GetAccessors(), Newtonsoft.Json.Utilities.ReflectionUtils.GetBaseDefinition(), System.Reflection.PropertyInfo.GetGetMethod(), System.Reflection.Emit.PropertyOnTypeBuilderInst.GetGetMethod(), System.Reflection.Emit.PropertyOnTypeBuilderInst.GetIndexParameters(), System.Reflection.RuntimePropertyInfo.GetValue(), System.Reflection.RuntimePropertyInfo.GetValue(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Initialize(), System.RuntimeType.InvokeMember(), Newtonsoft.Json.Utilities.ReflectionUtils.IsPublic(), Newtonsoft.Json.Utilities.ReflectionUtils.IsVirtual(), and FullSerializer.Internal.fsIEnumerableConverter.TryGetExistingSize().