Terraria Decompiled: Terraria.Graphics.Shaders.ShaderData.Apply
Apply()
virtual void Terraria.Graphics.Shaders.ShaderData.Apply () inline virtual
Reimplemented in Terraria.GameContent.Shaders.BlizzardShaderData, Terraria.GameContent.Shaders.MoonLordScreenShaderData, Terraria.GameContent.Shaders.SandstormShaderData, Terraria.GameContent.Shaders.WaterShaderData, and Terraria.Graphics.Shaders.ScreenShaderData.
Definition at line 35 of file ShaderData.cs.
        {
            if (this._effect == null || this._effect != this.Shader)
            {
                this._effect = this.Shader;
                this._effectPass = this.Shader.CurrentTechnique.Passes[this._passName];
            }
            this._effectPass.Apply();
        }
References Terraria.Graphics.Shaders.ShaderData._effect, Terraria.Graphics.Shaders.ShaderData._effectPass, Terraria.Graphics.Shaders.ShaderData._passName, Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, and Terraria.Graphics.Shaders.ShaderData.Shader.
Referenced by Terraria.Graphics.Shaders.ScreenShaderData.Apply(), Terraria.Graphics.Shaders.MiscShaderData.Apply(), Terraria.GameContent.Dyes.ReflectiveArmorShaderData.Apply(), Terraria.Graphics.Shaders.ArmorShaderData.Apply(), and Terraria.Graphics.Shaders.HairShaderData.Apply().