Terraria Decompiled: Mono.DataConverter.PackOne
PackOne()
static bool Mono.DataConverter.PackOne (DataConverter::PackContext b, object oarg) inline static private
Definition at line 286 of file DataConverter.cs.
        {
            char c = b.description[b.i];
            if (c <= 'S')
            {
                if (c <= 'C')
                {
                    switch (c)
                    {
                    case '!':
                        b.align = -1;
                        return false;
                    case '"':
                    case '#':
                    case '&':
                    case '\'':
                    case '(':
                    case ')':
                    case '+':
                    case ',':
                    case '-':
                    case '.':
                    case '/':
                    case '0':
                        goto IL_0457;
                    case '$':
                        break;
                    case '%':
                        b.conv = DataConverter.Native;
                        return false;
                    case '*':
                        b.repeat = int.MaxValue;
                        return false;
                    case '1':
                    case '2':
                    case '3':
                    case '4':
                    case '5':
                    case '6':
                    case '7':
                    case '8':
                    case '9':
                        b.repeat = (int)((short)b.description[b.i] - 48);
                        return false;
                    default:
                        if (c != 'C')
{
                            goto IL_0457;
                        }
                        b.Add(new byte[] { Convert.ToByte(oarg) });
                        return true;
                    }
                }
                else
                {
                    if (c == 'I')
                    {
                        b.Add(b.conv.GetBytes(Convert.ToUInt32(oarg)));
                        return true;
                    }
                    if (c == 'L')
                    {
                        b.Add(b.conv.GetBytes(Convert.ToUInt64(oarg)));
                        return true;
                    }
                    if (c != 'S')
                    {
                        goto IL_0457;
                    }
                    b.Add(b.conv.GetBytes(Convert.ToUInt16(oarg)));
                    return true;
                }
            }
            else if (c <= 'l')
            {
                switch (c)
                {
                case '[':
                {
                    int num = -1;
                    int num2 = b.i + 1;
                    while (num2 < b.description.Length && b.description[num2] != ']')
                    {
                        int num3 = (int)((short)b.description[num2] - 48);
                        if (num3 >= 0 && num3 <= 9)
{
                            if (num == -1)
{
                                num = num3;
                            }
                            else
{
                                num = num * 10 + num3;
                            }
                        }
                        num2++;
                    }
                    if (num == -1)
                    {
                        throw new ArgumentException("invalid size specification");
                    }
                    b.i = num2;
                    b.repeat = num;
                    return false;
                }
                case '\\':
                case ']':
                case '`':
                case 'a':
                case 'e':
                case 'g':
                case 'h':
                    goto IL_0457;
                case '^':
                    b.conv = DataConverter.BigEndian;
                    return false;
                case '_':
                    b.conv = DataConverter.LittleEndian;
                    return false;
                case 'b':
                    b.Add(new byte[] { Convert.ToByte(oarg) });
                    return true;
                case 'c':
                    b.Add(new byte[] { (byte)Convert.ToSByte(oarg) });
                    return true;
                case 'd':
                    b.Add(b.conv.GetBytes(Convert.ToDouble(oarg)));
                    return true;
                case 'f':
                    b.Add(b.conv.GetBytes(Convert.ToSingle(oarg)));
                    return true;
                case 'i':
                    b.Add(b.conv.GetBytes(Convert.ToInt32(oarg)));
                    return true;
                default:
                    if (c != 'l')
                    {
                        goto IL_0457;
                    }
                    b.Add(b.conv.GetBytes(Convert.ToInt64(oarg)));
                    return true;
                }
            }
            else
            {
                if (c == 's')
                {
                    b.Add(b.conv.GetBytes(Convert.ToInt16(oarg)));
                    return true;
                }
                if (c == 'x')
                {
                    b.Add(new byte[1]);
                    return false;
                }
                if (c != 'z')
                {
                    goto IL_0457;
                }
            }
            bool flag = b.description[b.i] == 'z';
            b.i++;
            if (b.i >= b.description.Length)
            {
                throw new ArgumentException("$ description needs a type specified", "description");
            }
            char c2 = b.description[b.i];
            Encoding encoding;
            switch (c2)
            {
            case '3':
            {
                encoding = Encoding.GetEncoding(12000);
                int num3 = 4;
                goto IL_0423;
            }
            case '4':
            {
                encoding = Encoding.GetEncoding(12001);
                int num3 = 4;
                goto IL_0423;
            }
            case '5':
                break;
            case '6':
            {
                encoding = Encoding.Unicode;
                int num3 = 2;
                goto IL_0423;
            }
            case '7':
            {
                encoding = Encoding.UTF7;
                int num3 = 1;
                goto IL_0423;
            }
            case '8':
            {
                encoding = Encoding.UTF8;
                int num3 = 1;
                goto IL_0423;
            }
            default:
                if (c2 == 'b')
                {
                    encoding = Encoding.BigEndianUnicode;
                    int num3 = 2;
                    goto IL_0423;
                }
                break;
            }
            throw new ArgumentException("Invalid format for $ specifier", "description");
            IL_0423:
            if (b.align == -1)
            {
                b.align = 4;
            }
            b.Add(encoding.GetBytes(Convert.ToString(oarg)));
            if (flag)
            {
                int num3;
                b.Add(new byte[num3]);
                return true;
            }
            return true;
            IL_0457:
            throw new ArgumentException(string.Format("invalid format specified `{0}'", b.description[b.i]));
        }
References Mono.DataConverter.BigEndian, System.Text.Encoding.BigEndianUnicode, System.Format, System.Text.Encoding.GetBytes(), System.Text.Encoding.GetEncoding(), int, Mono.DataConverter.LittleEndian, Mono.DataConverter.Native, System.Convert.ToByte(), System.Convert.ToDouble(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Convert.ToSByte(), System.Convert.ToSingle(), System.Convert.ToString(), System.Convert.ToUInt16(), System.Convert.ToUInt32(), System.Convert.ToUInt64(), System.Text.Encoding.Unicode, System.Text.Encoding.UTF7, and System.Text.Encoding.UTF8.
Referenced by Mono.DataConverter.Pack(), and Mono.DataConverter.PackEnumerable().