Terraria Decompiled: Mono.DataConverter.Unpack
Unpack()
static IList Mono.DataConverter.Unpack (string description, byte[] buffer, int startIndex) inline static
Definition at line 532 of file DataConverter.cs.
        {
            DataConverter dataConverter = DataConverter.CopyConv;
            List<object> list = new List<object>();
            int num = startIndex;
            bool flag = false;
            int num2 = 0;
            int num3 = 0;
            while (num3 < description.Length && num < buffer.Length)
            {
                int num4 = num3;
                char c = description[num3];
                if (c <= 'S')
                {
                    if (c <= 'C')
                    {
                        switch (c)
{
                        case '!':
                            flag = true;
                            break;
                        case '"':
                        case '#':
                        case '&':
                        case '\'':
                        case '(':
                        case ')':
                        case '+':
                        case ',':
                        case '-':
                        case '.':
                        case '/':
                        case '0':
                            goto IL_05C2;
                        case '$':
                            goto IL_03E0;
                        case '%':
                            dataConverter = DataConverter.Native;
                            break;
                        case '*':
                            num2 = int.MaxValue;
                            break;
                        case '1':
                        case '2':
                        case '3':
                        case '4':
                        case '5':
                        case '6':
                        case '7':
                        case '8':
                        case '9':
                            num2 = (int)((short)description[num3] - 48);
                            num4 = num3 + 1;
                            break;
                        default:
                            if (c != 'C')
{
                                goto IL_05C2;
                            }
                            goto IL_0303;
                        }
                    }
                    else if (c != 'I')
                    {
                        if (c != 'L')
{
                            if (c != 'S')
{
                                goto IL_05C2;
                            }
                            if (DataConverter.Prepare(buffer, ref num, 2, ref flag))
{
                                list.Add(dataConverter.GetUInt16(buffer, num));
                                num += 2;
                            }
                        }
                        else if (DataConverter.Prepare(buffer, ref num, 8, ref flag))
{
                            list.Add(dataConverter.GetUInt64(buffer, num));
                            num += 8;
                        }
                    }
                    else if (DataConverter.Prepare(buffer, ref num, 4, ref flag))
                    {
                        list.Add(dataConverter.GetUInt32(buffer, num));
                        num += 4;
                    }
                }
                else if (c <= 'l')
                {
                    switch (c)
                    {
                    case '[':
                    {
                        int num5 = -1;
                        int num6 = num3 + 1;
                        while (num6 < description.Length && description[num6] != ']')
{
                            int num7 = (int)((short)description[num6] - 48);
                            if (num7 >= 0 && num7 <= 9)
{
                                if (num5 == -1)
{
                                    num5 = num7;
                                }
                                else
{
                                    num5 = num5 * 10 + num7;
                                }
                            }
                            num6++;
                        }
                        if (num5 == -1)
{
                            throw new ArgumentException("invalid size specification");
                        }
                        num3 = num6;
                        num4 = num3 + 1;
                        num2 = num5;
                        break;
                    }
                    case '\\':
                    case ']':
                    case '`':
                    case 'a':
                    case 'e':
                    case 'g':
                    case 'h':
                        goto IL_05C2;
                    case '^':
                        dataConverter = DataConverter.BigEndian;
                        break;
                    case '_':
                        dataConverter = DataConverter.LittleEndian;
                        break;
                    case 'b':
                        if (DataConverter.Prepare(buffer, ref num, 1, ref flag))
{
                            list.Add(buffer[num]);
                            num++;
                        }
                        break;
                    case 'c':
                        goto IL_0303;
                    case 'd':
                        if (DataConverter.Prepare(buffer, ref num, 8, ref flag))
{
                            list.Add(dataConverter.GetDouble(buffer, num));
                            num += 8;
                        }
                        break;
                    case 'f':
                        if (DataConverter.Prepare(buffer, ref num, 4, ref flag))
{
                            list.Add(dataConverter.GetFloat(buffer, num));
                            num += 4;
                        }
                        break;
                    case 'i':
                        if (DataConverter.Prepare(buffer, ref num, 4, ref flag))
{
                            list.Add(dataConverter.GetInt32(buffer, num));
                            num += 4;
                        }
                        break;
                    default:
                        if (c != 'l')
{
                            goto IL_05C2;
                        }
                        if (DataConverter.Prepare(buffer, ref num, 8, ref flag))
{
                            list.Add(dataConverter.GetInt64(buffer, num));
                            num += 8;
                        }
                        break;
                    }
                }
                else if (c != 's')
                {
                    if (c != 'x')
                    {
                        if (c != 'z')
{
                            goto IL_05C2;
                        }
                        goto IL_03E0;
                    }
                    else
                    {
                        num++;
                    }
                }
                else if (DataConverter.Prepare(buffer, ref num, 2, ref flag))
                {
                    list.Add(dataConverter.GetInt16(buffer, num));
                    num += 2;
                }
                IL_05DF:
                if (num2 <= 0)
                {
                    num3++;
                    continue;
                }
                if (--num2 > 0)
                {
                    num3 = num4;
                    continue;
                }
                continue;
                IL_0303:
                if (DataConverter.Prepare(buffer, ref num, 1, ref flag))
                {
                    char c2;
                    if (description[num3] == 'c')
                    {
                        c2 = (char)((sbyte)buffer[num]);
                    }
                    else
                    {
                        c2 = (char)buffer[num];
                    }
                    list.Add(c2);
                    num++;
                    goto IL_05DF;
                }
                goto IL_05DF;
                IL_03E0:
                num3++;
                if (num3 >= description.Length)
                {
                    throw new ArgumentException("$ description needs a type specified", "description");
                }
                char c3 = description[num3];
                if (flag)
                {
                    num = DataConverter.Align(num, 4);
                    flag = false;
                }
                if (num < buffer.Length)
                {
                    int num7;
                    Encoding encoding;
                    switch (c3)
                    {
                    case '3':
                        encoding = Encoding.GetEncoding(12000);
                        num7 = 4;
                        break;
                    case '4':
                        encoding = Encoding.GetEncoding(12001);
                        num7 = 4;
                        break;
                    case '5':
                        goto IL_049C;
                    case '6':
                        encoding = Encoding.Unicode;
                        num7 = 2;
                        break;
                    case '7':
                        encoding = Encoding.UTF7;
                        num7 = 1;
                        break;
                    case '8':
                        encoding = Encoding.UTF8;
                        num7 = 1;
                        break;
                    default:
                        if (c3 != 'b')
{
                            goto IL_049C;
                        }
                        encoding = Encoding.BigEndianUnicode;
                        num7 = 2;
                        break;
                    }
                    int i = num;
                    switch (num7)
                    {
                    case 1:
                        while (i < buffer.Length && buffer[i] != 0)
{
                            i++;
                        }
                        list.Add(encoding.GetChars(buffer, num, i - num));
                        if (i == buffer.Length)
{
                            num = i;
                            goto IL_05DF;
                        }
                        num = i + 1;
                        goto IL_05DF;
                    case 2:
                        while (i < buffer.Length)
{
                            if (i + 1 == buffer.Length)
{
                                i++;
                                break;
                            }
                            if (buffer[i] == 0 && buffer[i + 1] == 0)
{
                                break;
                            }
                            i++;
                        }
                        list.Add(encoding.GetChars(buffer, num, i - num));
                        if (i == buffer.Length)
{
                            num = i;
                            goto IL_05DF;
                        }
                        num = i + 2;
                        goto IL_05DF;
                    case 3:
                        goto IL_05DF;
                    case 4:
                        while (i < buffer.Length)
{
                            if (i + 3 >= buffer.Length)
{
                                i = buffer.Length;
                                break;
                            }
                            if (buffer[i] == 0 && buffer[i + 1] == 0 && buffer[i + 2] == 0 && buffer[i + 3] == 0)
{
                                break;
                            }
                            i++;
                        }
                        list.Add(encoding.GetChars(buffer, num, i - num));
                        if (i == buffer.Length)
{
                            num = i;
                            goto IL_05DF;
                        }
                        num = i + 4;
                        goto IL_05DF;
                    default:
                        goto IL_05DF;
                    }
                    IL_049C:
                    throw new ArgumentException("Invalid format for $ specifier", "description");
                }
                goto IL_05DF;
                IL_05C2:
                throw new ArgumentException(string.Format("invalid format specified `{0}'", description[num3]));
            }
            return list;
        }
References Mono.DataConverter.Align(), Mono.DataConverter.BigEndian, System.Text.Encoding.BigEndianUnicode, Mono.DataConverter.CopyConv, System.Format, System.Text.Encoding.GetChars(), Mono.DataConverter.GetDouble(), System.Text.Encoding.GetEncoding(), Mono.DataConverter.GetFloat(), Mono.DataConverter.GetInt16(), Mono.DataConverter.GetInt32(), Mono.DataConverter.GetInt64(), Mono.DataConverter.GetUInt16(), Mono.DataConverter.GetUInt32(), Mono.DataConverter.GetUInt64(), int, System.list, Mono.DataConverter.LittleEndian, Mono.DataConverter.Native, Mono.DataConverter.Prepare(), System.startIndex, System.Text.Encoding.Unicode, System.Text.Encoding.UTF7, and System.Text.Encoding.UTF8.