Terraria Decompiled: Terraria.HitTile.HitTileObject.Clear
Clear()
void Terraria.HitTile.HitTileObject.Clear () inline
Definition at line 467 of file HitTile.cs.
            {
                this.X = 0;
                this.Y = 0;
                this.damage = 0;
                this.type = 0;
                this.timeToLive = 0;
                if (HitTile.rand == null)
                {
                    HitTile.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
                }
                this.crackStyle = HitTile.rand.Next(4);
                while (this.crackStyle == HitTile.lastCrack)
                {
                    this.crackStyle = HitTile.rand.Next(4);
                }
                HitTile.lastCrack = this.crackStyle;
            }
References Terraria.HitTile.HitTileObject.crackStyle, Terraria.HitTile.lastCrack, Terraria.Utilities.UnifiedRandom.Next(), System.DateTime.Now, Terraria.HitTile.rand, and System.DateTime.Ticks.
Referenced by Terraria.HitTile.HitTileObject.HitTileObject(), and Terraria.HitTile.Prune().