Terraria Decompiled: Terraria.Graphics.Effects.OverlayManager.Draw
Draw()
void Terraria.Graphics.Effects.OverlayManager.Draw (SpriteBatch spriteBatch, RenderLayers layer) inline
Definition at line 88 of file OverlayManager.cs.
        {
            if (this._overlayCount == 0)
            {
                return;
            }
            bool flag = false;
            for (int i = 0; i < this._activeOverlays.Length; i++)
            {
                for (LinkedListNode<Overlay> linkedListNode = this._activeOverlays[i].First; linkedListNode != null; linkedListNode = linkedListNode.Next)
                {
                    Overlay value = linkedListNode.Value;
                    if (value.Layer == layer && value.IsVisible())
                    {
                        if (!flag)
{
                            spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.Default, RasterizerState.CullNone, null, Main.Transform);
                            flag = true;
                        }
                        value.Draw(spriteBatch);
                    }
                }
            }
            if (flag)
            {
                spriteBatch.End();
            }
        }
References Terraria.Graphics.Effects.OverlayManager._activeOverlays, Terraria.Graphics.Effects.OverlayManager._overlayCount, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullNone, Microsoft.Xna.Framework.Graphics.DepthStencilState.Default, Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Terraria.Main.Transform, and System.value.
Referenced by Terraria.Main.DoDraw_WallsAndBlacks().