Terraria Decompiled: Terraria.Graphics.Effects.OverlayManager.Update
Update()
void Terraria.Graphics.Effects.OverlayManager.Update (GameTime gameTime) inline
Definition at line 49 of file OverlayManager.cs.
        {
            for (int i = 0; i < this._activeOverlays.Length; i++)
            {
                LinkedListNode<Overlay> next;
                for (LinkedListNode<Overlay> linkedListNode = this._activeOverlays[i].First; linkedListNode != null; linkedListNode = next)
                {
                    Overlay value = linkedListNode.Value;
                    next = linkedListNode.Next;
                    value.Update(gameTime);
                    switch (value.Mode)
                    {
                    case OverlayMode.FadeIn:
                        value.Opacity += (float)gameTime.ElapsedGameTime.TotalSeconds * 1f;
                        if (value.Opacity >= 1f)
{
                            value.Opacity = 1f;
                            value.Mode = OverlayMode.Active;
                        }
                        break;
                    case OverlayMode.Active:
                        value.Opacity = Math.Min(1f, value.Opacity + (float)gameTime.ElapsedGameTime.TotalSeconds * 1f);
                        break;
                    case OverlayMode.FadeOut:
                        value.Opacity -= (float)gameTime.ElapsedGameTime.TotalSeconds * 1f;
                        if (value.Opacity <= 0f)
{
                            value.Opacity = 0f;
                            value.Mode = OverlayMode.Inactive;
                            this._activeOverlays[i].Remove(linkedListNode);
                            this._overlayCount--;
                        }
                        break;
                    }
                }
            }
        }
References Terraria.Graphics.Effects.OverlayManager._activeOverlays, Terraria.Graphics.Effects.OverlayManager._overlayCount, Microsoft.Xna.Framework.GameTime.ElapsedGameTime, System.Math.Min(), System.TimeSpan.TotalSeconds, Terraria.Graphics.Effects.Overlay.Update(), and System.value.
Referenced by Terraria.Main.DoUpdate().