Terraria Decompiled: NVorbis.Mapping.Init
Init()
void NVorbis.Mapping.Init (IPacket packet, int channels, IFloor[] floors, IResidue[] residues, IMdct mdct) inline
Implements NVorbis.Contracts.IMapping.
Definition at line 11 of file Mapping.cs.
        {
            int num = 1;
            if (packet.ReadBit())
            {
                num += (int)packet.ReadBits(4);
            }
            int num2 = 0;
            if (packet.ReadBit())
            {
                num2 = (int)packet.ReadBits(8) + 1;
            }
            int num3 = Utils.ilog(channels - 1);
            this._couplingAngle = new int[num2];
            this._couplingMangitude = new int[num2];
            for (int i = 0; i < num2; i++)
            {
                int num4 = (int)packet.ReadBits(num3);
                int num5 = (int)packet.ReadBits(num3);
                if (num4 == num5 || num4 > channels - 1 || num5 > channels - 1)
                {
                    throw new InvalidDataException("Invalid magnitude or angle in mapping header!");
                }
                this._couplingAngle[i] = num5;
                this._couplingMangitude[i] = num4;
            }
            if (packet.ReadBits(2) != 0UL)
            {
                throw new InvalidDataException("Reserved bits not 0 in mapping header.");
            }
            int[] array = new int[channels];
            if (num > 1)
            {
                for (int j = 0; j < channels; j++)
                {
                    array[j] = (int)packet.ReadBits(4);
                    if (array[j] > num)
                    {
                        throw new InvalidDataException("Invalid channel mux submap index in mapping header!");
                    }
                }
            }
            this._submapFloor = new IFloor[num];
            this._submapResidue = new IResidue[num];
            for (int k = 0; k < num; k++)
            {
                packet.SkipBits(8);
                int num6 = (int)packet.ReadBits(8);
                if (num6 >= floors.Length)
                {
                    throw new InvalidDataException("Invalid floor number in mapping header!");
                }
                int num7 = (int)packet.ReadBits(8);
                if (num7 >= residues.Length)
                {
                    throw new InvalidDataException("Invalid residue number in mapping header!");
                }
                this._submapFloor[k] = floors[num6];
                this._submapResidue[k] = residues[num7];
            }
            this._channelFloor = new IFloor[channels];
            this._channelResidue = new IResidue[channels];
            for (int l = 0; l < channels; l++)
            {
                this._channelFloor[l] = this._submapFloor[array[l]];
                this._channelResidue[l] = this._submapResidue[array[l]];
            }
            this._mdct = mdct;
        }
References NVorbis.Mapping._channelFloor, NVorbis.Mapping._channelResidue, NVorbis.Mapping._couplingAngle, NVorbis.Mapping._couplingMangitude, NVorbis.Mapping._submapFloor, NVorbis.Mapping._submapResidue, System.array, NVorbis.Utils.ilog(), int, NVorbis.Contracts.IPacket.ReadBits(), and NVorbis.Contracts.IPacket.SkipBits().