Terraria Decompiled: System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature
CreateSignature()
override byte[] System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature (byte[] rgbHash) inline
Definition at line 23 of file RSAPKCS1SignatureFormatter.cs.
        {
            if (this.rsa == null)
            {
                throw new CryptographicUnexpectedOperationException(Locale.GetText("No key pair available."));
            }
            if (this.hash == null)
            {
                throw new CryptographicUnexpectedOperationException(Locale.GetText("Missing hash algorithm."));
            }
            if (rgbHash == null)
            {
                throw new ArgumentNullException("rgbHash");
            }
            return PKCS1.Sign_v15(this.rsa, this.hash, rgbHash);
        }
References Locale.GetText(), System.Security.Cryptography.RSAPKCS1SignatureFormatter.hash, System.Security.Cryptography.RSAPKCS1SignatureFormatter.rsa, and Mono.Security.Cryptography.PKCS1.Sign_v15().
Referenced by Mono.Security.StrongName.Sign().