Terraria Decompiled: NVorbis.Mapping.DecodePacket
DecodePacket()
void NVorbis.Mapping.DecodePacket (IPacket packet, int blockSize, int channels, float buffer[][]) inline
Implements NVorbis.Contracts.IMapping.
Definition at line 82 of file Mapping.cs.
        {
            int num = blockSize >> 1;
            IFloorData[] array = new IFloorData[this._channelFloor.Length];
            bool[] array2 = new bool[this._channelFloor.Length];
            for (int i = 0; i < this._channelFloor.Length; i++)
            {
                array[i] = this._channelFloor[i].Unpack(packet, blockSize, i);
                array2[i] = !array[i].ExecuteChannel;
                Array.Clear(buffer[i], 0, num);
            }
            for (int j = 0; j < this._couplingAngle.Length; j++)
            {
                if (array[this._couplingAngle[j]].ExecuteChannel || array[this._couplingMangitude[j]].ExecuteChannel)
                {
                    array[this._couplingAngle[j]].ForceEnergy = true;
                    array[this._couplingMangitude[j]].ForceEnergy = true;
                }
            }
            for (int k = 0; k < this._submapFloor.Length; k++)
            {
                for (int l = 0; l < this._channelFloor.Length; l++)
                {
                    if (this._submapFloor[k] != this._channelFloor[l] || this._submapResidue[k] != this._channelResidue[l])
                    {
                        array[l].ForceNoEnergy = true;
                    }
                }
                this._submapResidue[k].Decode(packet, array2, blockSize, buffer);
            }
            for (int m = this._couplingAngle.Length - 1; m >= 0; m--)
            {
                if (array[this._couplingAngle[m]].ExecuteChannel || array[this._couplingMangitude[m]].ExecuteChannel)
                {
                    float[] array3 = buffer[this._couplingMangitude[m]];
                    float[] array4 = buffer[this._couplingAngle[m]];
                    for (int n = 0; n < num; n++)
                    {
                        float num2 = array3[n];
                        float num3 = array4[n];
                        float num4;
                        float num5;
                        if (num2 > 0f)
{
                            if (num3 > 0f)
{
                                num4 = num2;
                                num5 = num2 - num3;
                            }
                            else
{
                                num5 = num2;
                                num4 = num2 + num3;
                            }
                        }
                        else if (num3 > 0f)
{
                            num4 = num2;
                            num5 = num2 + num3;
                        }
                        else
{
                            num5 = num2;
                            num4 = num2 - num3;
                        }
                        array3[n] = num4;
                        array4[n] = num5;
                    }
                }
            }
            for (int num6 = 0; num6 < this._channelFloor.Length; num6++)
            {
                if (array[num6].ExecuteChannel)
                {
                    this._channelFloor[num6].Apply(array[num6], blockSize, buffer[num6]);
                    this._mdct.Reverse(buffer[num6], blockSize);
                }
                else
                {
                    Array.Clear(buffer[num6], num, num);
                }
            }
        }
References NVorbis.Mapping._channelFloor, NVorbis.Mapping._channelResidue, NVorbis.Mapping._couplingAngle, NVorbis.Mapping._couplingMangitude, NVorbis.Mapping._mdct, NVorbis.Mapping._submapFloor, NVorbis.Mapping._submapResidue, NVorbis.Contracts.IFloor.Apply(), System.array, System.Array.Clear(), NVorbis.Contracts.IResidue.Decode(), NVorbis.Contracts.IMdct.Reverse(), and NVorbis.Contracts.IFloor.Unpack().