Terraria Decompiled: System.Reflection.AssemblyName.GetAssemblyName
GetAssemblyName()
static unsafe AssemblyName System.Reflection.AssemblyName.GetAssemblyName (string assemblyFile) inline static
Definition at line 521 of file AssemblyName.cs.
        {
            if (assemblyFile == null)
            {
                throw new ArgumentNullException("assemblyFile");
            }
            AssemblyName assemblyName = new AssemblyName();
            MonoAssemblyName monoAssemblyName;
            string text;
            Assembly.InternalGetAssemblyName(Path.GetFullPath(assemblyFile), out monoAssemblyName, out text);
            try
            {
                assemblyName.FillName(&monoAssemblyName, text, true, false, true, false);
            }
            finally
            {
                RuntimeMarshal.FreeAssemblyName(ref monoAssemblyName, false);
            }
            return assemblyName;
        }
References System.Reflection.AssemblyName.AssemblyName(), System.Reflection.AssemblyName.FillName(), Mono.RuntimeMarshal.FreeAssemblyName(), System.IO.Path.GetFullPath(), System.Reflection.Assembly.InternalGetAssemblyName(), and System.text.
Referenced by System.Reflection.AssemblyNameProxy.GetAssemblyName(), and Mono.Security.StrongName.IsAssemblyStrongnamed().