Terraria Decompiled: System.Reflection.AssemblyName.ComputePublicKeyToken
ComputePublicKeyToken()
unsafe byte[] System.Reflection.AssemblyName.ComputePublicKeyToken () inline private
Definition at line 407 of file AssemblyName.cs.
        {
            byte[] array2;
            byte[] array = (array2 = new byte[8]);
            byte* ptr;
            if (array == null || array2.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &array2[0];
            }
            byte[] array3;
            byte* ptr2;
            if ((array3 = this.publicKey) == null || array3.Length == 0)
            {
                ptr2 = null;
            }
            else
            {
                ptr2 = &array3[0];
            }
            AssemblyName.get_public_token(ptr, ptr2, this.publicKey.Length);
            array3 = null;
            array2 = null;
            return array;
        }
References System.array, System.Reflection.AssemblyName.get_public_token(), and System.Reflection.AssemblyName.publicKey.
Referenced by System.Reflection.AssemblyName.GetPublicKeyToken(), and System.Reflection.AssemblyName.InternalGetPublicKeyToken().