Terraria Decompiled: System.Reflection.AssemblyName.FillName
FillName()
unsafe void System.Reflection.AssemblyName.FillName (MonoAssemblyName * native, string codeBase, bool addVersion, bool addPublickey, bool defaultToken, bool assemblyRef) inline package
Definition at line 611 of file AssemblyName.cs.
        {
            this.name = RuntimeMarshal.PtrToUtf8String(native->name);
            this.major = (int)native->major;
            this.minor = (int)native->minor;
            this.build = (int)native->build;
            this.revision = (int)native->revision;
            this.flags = (AssemblyNameFlags)native->flags;
            this.hashalg = (AssemblyHashAlgorithm)native->hash_alg;
            this.versioncompat = AssemblyVersionCompatibility.SameMachine;
            this.processor_architecture = (ProcessorArchitecture)native->arch;
            if (addVersion)
            {
                this.version = new Version(this.major, this.minor, this.build, this.revision);
            }
            this.codebase = codeBase;
            if (native->culture != IntPtr.Zero)
            {
                this.cultureinfo = CultureInfo.CreateCulture(RuntimeMarshal.PtrToUtf8String(native->culture), assemblyRef);
            }
            if (native->public_key != IntPtr.Zero)
            {
                this.publicKey = RuntimeMarshal.DecodeBlobArray(native->public_key);
                this.flags |= AssemblyNameFlags.PublicKey;
            }
            else if (addPublickey)
            {
                this.publicKey = EmptyArray<byte>.Value;
                this.flags |= AssemblyNameFlags.PublicKey;
            }
            if (native->public_key_token.FixedElementField != 0)
            {
                byte[] array = new byte[8];
                int i = 0;
                int num = 0;
                while (i < 8)
                {
                    array[i] = (byte)(RuntimeMarshal.AsciHexDigitValue((int)(*((ref native->public_key_token.FixedElementField) + num++))) << 4);
                    byte[] array2 = array;
                    int num2 = i;
                    array2[num2] |= (byte)RuntimeMarshal.AsciHexDigitValue((int)(*((ref native->public_key_token.FixedElementField) + num++)));
                    i++;
                }
                this.keyToken = array;
                return;
            }
            if (defaultToken)
            {
                this.keyToken = EmptyArray<byte>.Value;
            }
        }
References Mono.MonoAssemblyName.arch, System.array, Mono.RuntimeMarshal.AsciHexDigitValue(), Mono.MonoAssemblyName.build, System.Reflection.AssemblyName.build, System.Globalization.CultureInfo.CreateCulture(), Mono.MonoAssemblyName.culture, Mono.RuntimeMarshal.DecodeBlobArray(), Mono.MonoAssemblyName.flags, Mono.MonoAssemblyName.hash_alg, int, Mono.MonoAssemblyName.major, System.Reflection.AssemblyName.major, Mono.MonoAssemblyName.minor, System.Reflection.AssemblyName.minor, Mono.MonoAssemblyName.name, System.Reflection.AssemblyName.ProcessorArchitecture, Mono.RuntimeMarshal.PtrToUtf8String(), Mono.MonoAssemblyName.public_key, Mono.MonoAssemblyName.public_key_token, Mono.MonoAssemblyName.revision, System.Reflection.AssemblyName.revision, System.EmptyArray< T >.Value, System.Reflection.AssemblyName.Version, and System.IntPtr.Zero.
Referenced by System.Reflection.AssemblyName.AssemblyName(), System.Reflection.AssemblyName.Create(), System.Reflection.AssemblyName.GetAssemblyName(), and System.Reflection.Assembly.GetReferencedAssemblies().