Terraria Decompiled: System.Reflection.AssemblyName.AssemblyName
AssemblyName() [3/3]
System.Reflection.AssemblyName.AssemblyName (SerializationInfo si, StreamingContext sc) inline package
Definition at line 81 of file AssemblyName.cs.
        {
            this.name = si.GetString("_Name");
            this.codebase = si.GetString("_CodeBase");
            this.version = (Version)si.GetValue("_Version", typeof(Version));
            this.publicKey = (byte[])si.GetValue("_PublicKey", typeof(byte[]));
            this.keyToken = (byte[])si.GetValue("_PublicKeyToken", typeof(byte[]));
            this.hashalg = (AssemblyHashAlgorithm)si.GetValue("_HashAlgorithm", typeof(AssemblyHashAlgorithm));
            this.keypair = (StrongNameKeyPair)si.GetValue("_StrongNameKeyPair", typeof(StrongNameKeyPair));
            this.versioncompat = (AssemblyVersionCompatibility)si.GetValue("_VersionCompatibility", typeof(AssemblyVersionCompatibility));
            this.flags = (AssemblyNameFlags)si.GetValue("_Flags", typeof(AssemblyNameFlags));
            int @int = si.GetInt32("_CultureInfo");
            if (@int != -1)
            {
                this.cultureinfo = new CultureInfo(@int);
            }
        }
References System.Reflection.AssemblyName.CultureInfo, System.Runtime.Serialization.SerializationInfo.GetInt32(), System.Runtime.Serialization.SerializationInfo.GetString(), System.Runtime.Serialization.SerializationInfo.GetValue(), and System.Reflection.AssemblyName.Version.