Terraria Decompiled: System.Reflection.AssemblyName.AssemblyName
AssemblyName() [2/3]
unsafe System.Reflection.AssemblyName.AssemblyName (string assemblyName) inline
Definition at line 35 of file AssemblyName.cs.
        {
            if (assemblyName == null)
            {
                throw new ArgumentNullException("assemblyName");
            }
            if (assemblyName.Length < 1)
            {
                throw new ArgumentException("assemblyName cannot have zero length.");
            }
            using (SafeStringMarshal safeStringMarshal = RuntimeMarshal.MarshalString(assemblyName))
            {
                MonoAssemblyName monoAssemblyName;
                bool flag;
                bool flag2;
                if (!AssemblyName.ParseAssemblyName(safeStringMarshal.Value, out monoAssemblyName, out flag, out flag2))
                {
                    throw new FileLoadException("The assembly name is invalid.");
                }
                try
                {
                    this.FillName(&monoAssemblyName, null, flag, false, flag2, false);
                }
                finally
                {
                    RuntimeMarshal.FreeAssemblyName(ref monoAssemblyName, false);
                }
            }
        }
References System.Reflection.AssemblyName.FillName(), Mono.RuntimeMarshal.FreeAssemblyName(), Mono.RuntimeMarshal.MarshalString(), System.Reflection.AssemblyName.ParseAssemblyName(), and Mono.SafeStringMarshal.Value.