Terraria Decompiled: Terraria.GameContent.Golf.FancyGolfPredictionLine.GetPosition
GetPosition()
Vector2 Terraria.GameContent.Golf.FancyGolfPredictionLine.GetPosition (float indexProgress) inline private
Definition at line 130 of file FancyGolfPredictionLine.cs.
        {
            int num = (int)Math.Floor((double)indexProgress);
            int num2 = num + 1;
            if (num2 >= this._positions.Count)
            {
                num2 = this._positions.Count - 1;
            }
            float num3 = indexProgress - (float)num;
            return Vector2.Lerp(this._positions[num], this._positions[num2], num3);
        }
References Terraria.GameContent.Golf.FancyGolfPredictionLine._positions, System.Collections.Generic.List< T >.Count, System.Math.Floor(), int, and Microsoft.Xna.Framework.Vector2.Lerp().
Referenced by Terraria.GameContent.Golf.FancyGolfPredictionLine.Draw().