Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddSchema
AddSchema()
JsonSchemaNode Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddSchema (JsonSchemaNode existingNode, JsonSchema schema) inline
Definition at line 21 of file JsonSchemaModelBuilder.cs.
        {
            string text;
            if (existingNode != null)
            {
                if (existingNode.Schemas.Contains(schema))
                {
                    return existingNode;
                }
                text = JsonSchemaNode.GetId(Enumerable.Union<JsonSchema>(existingNode.Schemas, new JsonSchema[] { schema }));
            }
            else
            {
                text = JsonSchemaNode.GetId(new JsonSchema[] { schema });
            }
            if (this._nodes.Contains(text))
            {
                return this._nodes[text];
            }
            JsonSchemaNode jsonSchemaNode = ((existingNode != null) ? existingNode.Combine(schema) : new JsonSchemaNode(schema));
            this._nodes.Add(jsonSchemaNode);
            this.AddProperties(schema.Properties, jsonSchemaNode.Properties);
            this.AddProperties(schema.PatternProperties, jsonSchemaNode.PatternProperties);
            if (schema.Items != null)
            {
                for (int i = 0; i < schema.Items.Count; i++)
                {
                    this.AddItem(jsonSchemaNode, i, schema.Items[i]);
                }
            }
            if (schema.AdditionalItems != null)
            {
                this.AddAdditionalItems(jsonSchemaNode, schema.AdditionalItems);
            }
            if (schema.AdditionalProperties != null)
            {
                this.AddAdditionalProperties(jsonSchemaNode, schema.AdditionalProperties);
            }
            if (schema.Extends != null)
            {
                foreach (JsonSchema jsonSchema in schema.Extends)
                {
                    jsonSchemaNode = this.AddSchema(jsonSchemaNode, jsonSchema);
                }
            }
            return jsonSchemaNode;
        }
References Newtonsoft.Json.Schema.JsonSchemaModelBuilder._nodes, Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddAdditionalItems(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddAdditionalProperties(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddItem(), Newtonsoft.Json.Schema.JsonSchema.AdditionalItems, Newtonsoft.Json.Schema.JsonSchema.AdditionalProperties, Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddProperties(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddSchema(), Newtonsoft.Json.Schema.JsonSchemaNode.Combine(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.Contains(), Newtonsoft.Json.Schema.JsonSchema.Extends, Newtonsoft.Json.Schema.JsonSchemaNode.GetId(), Newtonsoft.Json.Schema.JsonSchema.Items, Newtonsoft.Json.Schema.JsonSchema.PatternProperties, Newtonsoft.Json.Schema.JsonSchemaNode.PatternProperties, Newtonsoft.Json.Schema.JsonSchema.Properties, Newtonsoft.Json.Schema.JsonSchemaNode.Properties, Newtonsoft.Json.Schema.JsonSchemaNode.Schemas, and System.text.
Referenced by Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddAdditionalItems(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddAdditionalProperties(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddItem(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddProperty(), Newtonsoft.Json.Schema.JsonSchemaModelBuilder.AddSchema(), and Newtonsoft.Json.Schema.JsonSchemaModelBuilder.Build().