Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaModelBuilder.BuildNodeModel
BuildNodeModel()
JsonSchemaModel Newtonsoft.Json.Schema.JsonSchemaModelBuilder.BuildNodeModel (JsonSchemaNode node) inline private
Definition at line 115 of file JsonSchemaModelBuilder.cs.
        {
            JsonSchemaModel jsonSchemaModel;
            if (this._nodeModels.TryGetValue(node, ref jsonSchemaModel))
            {
                return jsonSchemaModel;
            }
            jsonSchemaModel = JsonSchemaModel.Create(node.Schemas);
            this._nodeModels[node] = jsonSchemaModel;
            foreach (KeyValuePair<string, JsonSchemaNode> keyValuePair in node.Properties)
            {
                if (jsonSchemaModel.Properties == null)
                {
                    jsonSchemaModel.Properties = new Dictionary<string, JsonSchemaModel>();
                }
                jsonSchemaModel.Properties[keyValuePair.Key] = this.BuildNodeModel(keyValuePair.Value);
            }
            foreach (KeyValuePair<string, JsonSchemaNode> keyValuePair2 in node.PatternProperties)
            {
                if (jsonSchemaModel.PatternProperties == null)
                {
                    jsonSchemaModel.PatternProperties = new Dictionary<string, JsonSchemaModel>();
                }
                jsonSchemaModel.PatternProperties[keyValuePair2.Key] = this.BuildNodeModel(keyValuePair2.Value);
            }
            foreach (JsonSchemaNode jsonSchemaNode in node.Items)
            {
                if (jsonSchemaModel.Items == null)
                {
                    jsonSchemaModel.Items = new List<JsonSchemaModel>();
                }
                jsonSchemaModel.Items.Add(this.BuildNodeModel(jsonSchemaNode));
            }
            if (node.AdditionalProperties != null)
            {
                jsonSchemaModel.AdditionalProperties = this.BuildNodeModel(node.AdditionalProperties);
            }
            if (node.AdditionalItems != null)
            {
                jsonSchemaModel.AdditionalItems = this.BuildNodeModel(node.AdditionalItems);
            }
            return jsonSchemaModel;
        }
References Newtonsoft.Json.Schema.JsonSchemaModelBuilder._nodeModels, Newtonsoft.Json.Schema.JsonSchemaModelBuilder.BuildNodeModel(), Newtonsoft.Json.Schema.JsonSchemaModel.Create(), Newtonsoft.Json.Schema.JsonSchemaNode.Items, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Newtonsoft.Json.Schema.JsonSchemaNode.Schemas, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Newtonsoft.Json.Schema.JsonSchemaModelBuilder.Build(), and Newtonsoft.Json.Schema.JsonSchemaModelBuilder.BuildNodeModel().