Terraria Decompiled: System.Buffers.Utilities.SelectBucketIndex
SelectBucketIndex()
static int System.Buffers.Utilities.SelectBucketIndex (int bufferSize) inline static package
Definition at line 11 of file Utilities.cs.
        {
            uint num = (uint)(bufferSize - 1) >> 4;
            int num2 = 0;
            if (num > 65535U)
            {
                num >>= 16;
                num2 = 16;
            }
            if (num > 255U)
            {
                num >>= 8;
                num2 += 8;
            }
            if (num > 15U)
            {
                num >>= 4;
                num2 += 4;
            }
            if (num > 3U)
            {
                num >>= 2;
                num2 += 2;
            }
            if (num > 1U)
            {
                num >>= 1;
                num2++;
            }
            return num2 + (int)num;
        }
References int, and System.U.
Referenced by System.Buffers.ConfigurableArrayPool< T >.ConfigurableArrayPool(), System.Buffers.ConfigurableArrayPool< T >.Rent(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Rent(), System.Buffers.ConfigurableArrayPool< T >.Return(), and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Return().