Terraria Decompiled: System.Array.SorterGenericArray.IntrospectiveSort
IntrospectiveSort()
void System.Array.SorterGenericArray.IntrospectiveSort (int left, int length) inline private
Definition at line 2674 of file Array.cs.
            {
                if (length < 2)
                {
                    return;
                }
                try
                {
                    this.IntroSort(left, length + left - 1, 2 * IntrospectiveSortUtilities.FloorLog2PlusOne(this.keys.Length));
                }
                catch (IndexOutOfRangeException)
                {
                    IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(this.comparer);
                }
                catch (Exception ex)
                {
                    throw new InvalidOperationException("Failed to compare two elements in the array.", ex);
                }
            }
References System.Collections.Generic.IntrospectiveSortUtilities.FloorLog2PlusOne(), System.Array.SorterGenericArray.IntroSort(), System.length, and System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer().
Referenced by System.Array.SorterGenericArray.Sort().