Terraria Decompiled: System.Array.SorterGenericArray.IntroSort
IntroSort()
void System.Array.SorterGenericArray.IntroSort (int lo, int hi, int depthLimit) inline private
Definition at line 2695 of file Array.cs.
            {
                while (hi > lo)
                {
                    int num = hi - lo + 1;
                    if (num <= 16)
                    {
                        if (num == 1)
{
                            return;
                        }
                        if (num == 2)
{
                            this.SwapIfGreaterWithItems(lo, hi);
                            return;
                        }
                        if (num == 3)
{
                            this.SwapIfGreaterWithItems(lo, hi - 1);
                            this.SwapIfGreaterWithItems(lo, hi);
                            this.SwapIfGreaterWithItems(hi - 1, hi);
                            return;
                        }
                        this.InsertionSort(lo, hi);
                        return;
                    }
                    else
                    {
                        if (depthLimit == 0)
{
                            this.Heapsort(lo, hi);
                            return;
                        }
                        depthLimit--;
                        int num2 = this.PickPivotAndPartition(lo, hi);
                        this.IntroSort(num2 + 1, hi, depthLimit);
                        hi = num2 - 1;
                    }
                }
            }
References System.Array.SorterGenericArray.Heapsort(), System.Array.SorterGenericArray.InsertionSort(), System.Array.SorterGenericArray.IntroSort(), System.Array.SorterGenericArray.PickPivotAndPartition(), and System.Array.SorterGenericArray.SwapIfGreaterWithItems().
Referenced by System.Array.SorterGenericArray.IntroSort(), and System.Array.SorterGenericArray.IntrospectiveSort().