Terraria Decompiled: System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.CreateKeyExchange
CreateKeyExchange() [1/2]
override byte[] System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.CreateKeyExchange (byte[] rgbData) inline
Definition at line 62 of file RSAPKCS1KeyExchangeFormatter.cs.
        {
            if (rgbData == null)
            {
                throw new ArgumentNullException("rgbData");
            }
            if (this._rsaKey == null)
            {
                throw new CryptographicUnexpectedOperationException(Environment.GetResourceString("No asymmetric key object has been associated with this formatter object."));
            }
            byte[] array;
            if (this.OverridesEncrypt)
            {
                array = this._rsaKey.Encrypt(rgbData, RSAEncryptionPadding.Pkcs1);
            }
            else
            {
                int num = this._rsaKey.KeySize / 8;
                if (rgbData.Length + 11 > num)
                {
                    throw new CryptographicException(Environment.GetResourceString("The data to be encrypted exceeds the maximum for this modulus of {0} bytes.", new object[] { num - 11 }));
                }
                byte[] array2 = new byte[num];
                if (this.RngValue == null)
                {
                    this.RngValue = RandomNumberGenerator.Create();
                }
                this.Rng.GetNonZeroBytes(array2);
                array2[0] = 0;
                array2[1] = 2;
                array2[num - rgbData.Length - 1] = 0;
                Buffer.InternalBlockCopy(rgbData, 0, array2, num - rgbData.Length, rgbData.Length);
                array = this._rsaKey.EncryptValue(array2);
            }
            return array;
        }
References System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter._rsaKey, System.array, System.Security.Cryptography.RandomNumberGenerator.Create(), System.Security.Cryptography.RSA.Encrypt(), System.Security.Cryptography.RSA.EncryptValue(), System.Security.Cryptography.RandomNumberGenerator.GetNonZeroBytes(), System.Environment.GetResourceString(), System.Buffer.InternalBlockCopy(), System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.OverridesEncrypt, System.Security.Cryptography.RSAEncryptionPadding.Pkcs1, System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.Rng, and System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.RngValue.
Referenced by System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.CreateKeyExchange().