Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName
GetTypeByName()
Type Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName (TypeNameKey typeNameKey) inline private
Definition at line 112 of file DefaultSerializationBinder.cs.
        {
            return this._typeCache.Get(typeNameKey);
        }
References Newtonsoft.Json.Serialization.DefaultSerializationBinder._typeCache, and Newtonsoft.Json.Utilities.ThreadSafeStore< TKey, TValue >.Get().
Referenced by Newtonsoft.Json.Serialization.DefaultSerializationBinder.BindToType(), and Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetGenericTypeFromTypeName().