Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetGenericTypeFromTypeName
GetGenericTypeFromTypeName()
Type Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetGenericTypeFromTypeName (string typeName, Assembly assembly) inline private
Definition at line 67 of file DefaultSerializationBinder.cs.
        {
            Type type = null;
            int num = typeName.IndexOf('[');
            if (num >= 0)
            {
                string text = typeName.Substring(0, num);
                Type type2 = assembly.GetType(text);
                if (type2 != null)
                {
                    List<Type> list = new List<Type>();
                    int num2 = 0;
                    int num3 = 0;
                    int num4 = typeName.Length - 1;
                    for (int i = num + 1; i < num4; i++)
                    {
                        char c = typeName.get_Chars(i);
                        if (c != '[')
{
                            if (c == ']')
{
                                num2--;
                                if (num2 == 0)
{
                                    TypeNameKey typeNameKey = ReflectionUtils.SplitFullyQualifiedTypeName(typeName.Substring(num3, i - num3));
                                    list.Add(this.GetTypeByName(typeNameKey));
                                }
                            }
                        }
                        else
{
                            if (num2 == 0)
{
                                num3 = i + 1;
                            }
                            num2++;
                        }
                    }
                    type = type2.MakeGenericType(list.ToArray());
                }
            }
            return type;
        }
References System.Reflection.Assembly.GetType(), Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeByName(), System.list, System.Type.MakeGenericType(), Newtonsoft.Json.Utilities.ReflectionUtils.SplitFullyQualifiedTypeName(), and System.text.
Referenced by Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetTypeFromTypeNameKey().