Terraria Decompiled: System.Resources.Win32VersionResource.WriteTo
WriteTo()
override void System.Resources.Win32VersionResource.WriteTo (Stream ms) inline
Definition at line 312 of file Win32VersionResource.cs.
        {
            using (BinaryWriter binaryWriter = new BinaryWriter(ms, Encoding.Unicode))
            {
                binaryWriter.Write(0);
                binaryWriter.Write(52);
                binaryWriter.Write(0);
                binaryWriter.Write("VS_VERSION_INFO".ToCharArray());
                binaryWriter.Write(0);
                this.emit_padding(binaryWriter);
                binaryWriter.Write((uint)this.signature);
                binaryWriter.Write(this.struct_version);
                binaryWriter.Write((int)(this.file_version >> 32));
                binaryWriter.Write((int)(this.file_version & (long)((ulong)(-1))));
                binaryWriter.Write((int)(this.product_version >> 32));
                binaryWriter.Write((int)(this.product_version & (long)((ulong)(-1))));
                binaryWriter.Write(this.file_flags_mask);
                binaryWriter.Write(this.file_flags);
                binaryWriter.Write(this.file_os);
                binaryWriter.Write(this.file_type);
                binaryWriter.Write(this.file_subtype);
                binaryWriter.Write((int)(this.file_date >> 32));
                binaryWriter.Write((int)(this.file_date & (long)((ulong)(-1))));
                this.emit_padding(binaryWriter);
                long position = ms.Position;
                binaryWriter.Write(0);
                binaryWriter.Write(0);
                binaryWriter.Write(1);
                binaryWriter.Write("VarFileInfo".ToCharArray());
                binaryWriter.Write(0);
                if (ms.Position % 4L != 0L)
                {
                    binaryWriter.Write(0);
                }
                long position2 = ms.Position;
                binaryWriter.Write(0);
                binaryWriter.Write(4);
                binaryWriter.Write(0);
                binaryWriter.Write("Translation".ToCharArray());
                binaryWriter.Write(0);
                if (ms.Position % 4L != 0L)
                {
                    binaryWriter.Write(0);
                }
                binaryWriter.Write((short)this.file_lang);
                binaryWriter.Write((short)this.file_codepage);
                this.patch_length(binaryWriter, position2);
                this.patch_length(binaryWriter, position);
                long position3 = ms.Position;
                binaryWriter.Write(0);
                binaryWriter.Write(0);
                binaryWriter.Write(1);
                binaryWriter.Write("StringFileInfo".ToCharArray());
                this.emit_padding(binaryWriter);
                long position4 = ms.Position;
                binaryWriter.Write(0);
                binaryWriter.Write(0);
                binaryWriter.Write(1);
                binaryWriter.Write(string.Format("{0:x4}{1:x4}", this.file_lang, this.file_codepage).ToCharArray());
                this.emit_padding(binaryWriter);
                foreach (object obj in this.properties.Keys)
                {
                    string text = (string)obj;
                    string text2 = (string)this.properties[text];
                    long position5 = ms.Position;
                    binaryWriter.Write(0);
                    binaryWriter.Write((short)(text2.ToCharArray().Length + 1));
                    binaryWriter.Write(1);
                    binaryWriter.Write(text.ToCharArray());
                    binaryWriter.Write(0);
                    this.emit_padding(binaryWriter);
                    binaryWriter.Write(text2.ToCharArray());
                    binaryWriter.Write(0);
                    this.emit_padding(binaryWriter);
                    this.patch_length(binaryWriter, position5);
                }
                this.patch_length(binaryWriter, position4);
                this.patch_length(binaryWriter, position3);
                this.patch_length(binaryWriter, 0L);
            }
        }
References System.Resources.Win32VersionResource.emit_padding(), System.Resources.Win32VersionResource.file_codepage, System.Resources.Win32VersionResource.file_date, System.Resources.Win32VersionResource.file_flags, System.Resources.Win32VersionResource.file_flags_mask, System.Resources.Win32VersionResource.file_lang, System.Resources.Win32VersionResource.file_os, System.Resources.Win32VersionResource.file_subtype, System.Resources.Win32VersionResource.file_type, System.Resources.Win32VersionResource.file_version, System.Format, System.Collections.Hashtable.Keys, System.L, System.obj, System.Resources.Win32VersionResource.patch_length(), System.IO.Stream.Position, System.Resources.Win32VersionResource.product_version, System.Resources.Win32VersionResource.properties, System.Resources.Win32VersionResource.signature, System.Resources.Win32VersionResource.struct_version, System.text, System.Text.Encoding.Unicode, and System.IO.BinaryWriter.Write().