Terraria Decompiled: System.Globalization.CalendricalCalculationsHelper.PersianNewYearOnOrBefore
PersianNewYearOnOrBefore()
static long System.Globalization.CalendricalCalculationsHelper.PersianNewYearOnOrBefore (long numberOfDays) inline static package
Definition at line 292 of file CalendricalCalculationsHelper.cs.
        {
            double num = (double)numberOfDays;
            long num2 = (long)Math.Floor(CalendricalCalculationsHelper.EstimatePrior(0.0, CalendricalCalculationsHelper.MiddayAtPersianObservationSite(num))) - 1L;
            long num3 = num2 + 3L;
            long num4;
            for (num4 = num2; num4 != num3; num4 += 1L)
            {
                double num5 = CalendricalCalculationsHelper.Compute(CalendricalCalculationsHelper.MiddayAtPersianObservationSite((double)num4));
                if (0.0 <= num5 && num5 <= 2.0)
                {
                    break;
                }
            }
            return num4 - 1L;
        }
References System.Globalization.CalendricalCalculationsHelper.Compute(), System.Globalization.CalendricalCalculationsHelper.EstimatePrior(), System.Math.Floor(), System.L, long, and System.Globalization.CalendricalCalculationsHelper.MiddayAtPersianObservationSite().
Referenced by System.Globalization.PersianCalendar.GetAbsoluteDatePersian(), and System.Globalization.PersianCalendar.GetDatePart().