Terraria Decompiled: System.Globalization.CalendricalCalculationsHelper.Compute
Compute()
static double System.Globalization.CalendricalCalculationsHelper.Compute (double time) inline static
Definition at line 267 of file CalendricalCalculationsHelper.cs.
        {
            double num = CalendricalCalculationsHelper.JulianCenturies(time);
            return CalendricalCalculationsHelper.InitLongitude(282.7771834 + 36000.76953744 * num + 5.729577951308232E-06 * CalendricalCalculationsHelper.SumLongSequenceOfPeriodicTerms(num) + CalendricalCalculationsHelper.Aberration(num) + CalendricalCalculationsHelper.Nutation(num));
        }
References System.Globalization.CalendricalCalculationsHelper.Aberration(), System.E, System.Globalization.CalendricalCalculationsHelper.InitLongitude(), System.Globalization.CalendricalCalculationsHelper.JulianCenturies(), System.Globalization.CalendricalCalculationsHelper.Nutation(), and System.Globalization.CalendricalCalculationsHelper.SumLongSequenceOfPeriodicTerms().
Referenced by System.Globalization.CalendricalCalculationsHelper.EstimatePrior(), and System.Globalization.CalendricalCalculationsHelper.PersianNewYearOnOrBefore().