Terraria Decompiled: System.Globalization.CalendricalCalculationsHelper.GetGregorianYear
GetGregorianYear()
static int System.Globalization.CalendricalCalculationsHelper.GetGregorianYear (double numberOfDays) inline static private
Definition at line 51 of file CalendricalCalculationsHelper.cs.
        {
            return new DateTime(Math.Min((long)(Math.Floor(numberOfDays) * 864000000000.0), DateTime.MaxValue.Ticks)).Year;
        }
References System.DateTime, System.Math.Floor(), System.DateTime.MaxValue, System.Math.Min(), and System.DateTime.Ticks.
Referenced by System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection().