Terraria Decompiled: System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection
EphemerisCorrection()
static double System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection (double time) inline static private
Definition at line 141 of file CalendricalCalculationsHelper.cs.
        {
            int gregorianYear = CalendricalCalculationsHelper.GetGregorianYear(time);
            CalendricalCalculationsHelper.EphemerisCorrectionAlgorithmMap[] ephemerisCorrectionTable = CalendricalCalculationsHelper.EphemerisCorrectionTable;
            int i = 0;
            while (i < ephemerisCorrectionTable.Length)
            {
                CalendricalCalculationsHelper.EphemerisCorrectionAlgorithmMap ephemerisCorrectionAlgorithmMap = ephemerisCorrectionTable[i];
                if (ephemerisCorrectionAlgorithmMap._lowestYear <= gregorianYear)
                {
                    switch (ephemerisCorrectionAlgorithmMap._algorithm)
                    {
                    case CalendricalCalculationsHelper.CorrectionAlgorithm.Default:
                        return CalendricalCalculationsHelper.DefaultEphemerisCorrection(gregorianYear);
                    case CalendricalCalculationsHelper.CorrectionAlgorithm.Year1988to2019:
                        return CalendricalCalculationsHelper.EphemerisCorrection1988to2019(gregorianYear);
                    case CalendricalCalculationsHelper.CorrectionAlgorithm.Year1900to1987:
                        return CalendricalCalculationsHelper.EphemerisCorrection1900to1987(gregorianYear);
                    case CalendricalCalculationsHelper.CorrectionAlgorithm.Year1800to1899:
                        return CalendricalCalculationsHelper.EphemerisCorrection1800to1899(gregorianYear);
                    case CalendricalCalculationsHelper.CorrectionAlgorithm.Year1700to1799:
                        return CalendricalCalculationsHelper.EphemerisCorrection1700to1799(gregorianYear);
                    case CalendricalCalculationsHelper.CorrectionAlgorithm.Year1620to1699:
                        return CalendricalCalculationsHelper.EphemerisCorrection1620to1699(gregorianYear);
                    default:
                        goto IL_007F;
                    }
                }
                else
                {
                    i++;
                }
            }
            IL_007F:
            return CalendricalCalculationsHelper.DefaultEphemerisCorrection(gregorianYear);
        }
References System.Globalization.CalendricalCalculationsHelper.EphemerisCorrectionAlgorithmMap._algorithm, System.Globalization.CalendricalCalculationsHelper.EphemerisCorrectionAlgorithmMap._lowestYear, System.Globalization.CalendricalCalculationsHelper.DefaultEphemerisCorrection(), System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1620to1699(), System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1700to1799(), System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1800to1899(), System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1900to1987(), System.Globalization.CalendricalCalculationsHelper.EphemerisCorrection1988to2019(), System.Globalization.CalendricalCalculationsHelper.EphemerisCorrectionTable, and System.Globalization.CalendricalCalculationsHelper.GetGregorianYear().
Referenced by System.Globalization.CalendricalCalculationsHelper.JulianCenturies().