Terraria Decompiled: System.Globalization.CalendricalCalculationsHelper.EquationOfTime
EquationOfTime()
static double System.Globalization.CalendricalCalculationsHelper.EquationOfTime (double time) inline static private
Definition at line 201 of file CalendricalCalculationsHelper.cs.
        {
            double num = CalendricalCalculationsHelper.JulianCenturies(time);
            double num2 = CalendricalCalculationsHelper.PolynomialSum(CalendricalCalculationsHelper.LambdaCoefficients, num);
            double num3 = CalendricalCalculationsHelper.PolynomialSum(CalendricalCalculationsHelper.AnomalyCoefficients, num);
            double num4 = CalendricalCalculationsHelper.PolynomialSum(CalendricalCalculationsHelper.EccentricityCoefficients, num);
            double num5 = CalendricalCalculationsHelper.TanOfDegree(CalendricalCalculationsHelper.Obliquity(num) / 2.0);
            double num6 = num5 * num5;
            double num7 = num6 * CalendricalCalculationsHelper.SinOfDegree(2.0 * num2) - 2.0 * num4 * CalendricalCalculationsHelper.SinOfDegree(num3) + 4.0 * num4 * num6 * CalendricalCalculationsHelper.SinOfDegree(num3) * CalendricalCalculationsHelper.CosOfDegree(2.0 * num2) - 0.5 * Math.Pow(num6, 2.0) * CalendricalCalculationsHelper.SinOfDegree(4.0 * num2) - 1.25 * Math.Pow(num4, 2.0) * CalendricalCalculationsHelper.SinOfDegree(2.0 * num3);
            double num8 = 6.283185307179586;
            double num9 = num7 / num8;
            return CalendricalCalculationsHelper.CopySign(Math.Min(Math.Abs(num9), 0.5), num9);
        }
References System.Math.Abs(), System.Globalization.CalendricalCalculationsHelper.AnomalyCoefficients, System.Globalization.CalendricalCalculationsHelper.CopySign(), System.Globalization.CalendricalCalculationsHelper.CosOfDegree(), System.Globalization.CalendricalCalculationsHelper.EccentricityCoefficients, System.Globalization.CalendricalCalculationsHelper.JulianCenturies(), System.Globalization.CalendricalCalculationsHelper.LambdaCoefficients, System.Math.Min(), System.Globalization.CalendricalCalculationsHelper.Obliquity(), System.Globalization.CalendricalCalculationsHelper.PolynomialSum(), System.Math.Pow(), System.Globalization.CalendricalCalculationsHelper.SinOfDegree(), and System.Globalization.CalendricalCalculationsHelper.TanOfDegree().
Referenced by System.Globalization.CalendricalCalculationsHelper.AsLocalTime().