Terraria Decompiled: Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollFemale
LoadDisplayDollFemale()
static void Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollFemale () inline static private
Definition at line 150 of file PlayerDataInitializer.cs.
        {
            PlayerDataInitializer.CopyVariant(11, 10);
            PlayerDataInitializer.LoadVariant(11, new int[] { 3, 5, 7, 9, 10 });
            Asset<Texture2D> asset = TextureAssets.Players[10, 2];
            TextureAssets.Players[11, 2] = asset;
            TextureAssets.Players[11, 1] = asset;
            TextureAssets.Players[11, 4] = asset;
            TextureAssets.Players[11, 6] = asset;
            TextureAssets.Players[11, 11] = asset;
            TextureAssets.Players[11, 12] = asset;
            TextureAssets.Players[11, 13] = asset;
            TextureAssets.Players[11, 8] = asset;
            TextureAssets.Players[11, 15] = asset;
        }
References Terraria.Initializers.PlayerDataInitializer.CopyVariant(), Terraria.Initializers.PlayerDataInitializer.LoadVariant(), and Terraria.GameContent.TextureAssets.Players.
Referenced by Terraria.Initializers.PlayerDataInitializer.Load().