Terraria Decompiled: Terraria.Initializers.PlayerDataInitializer.LoadVariant
LoadVariant()
static void Terraria.Initializers.PlayerDataInitializer.LoadVariant (int ID, int[] pieceIDs) inline static private
Definition at line 31 of file PlayerDataInitializer.cs.
        {
            for (int i = 0; i < pieceIDs.Length; i++)
            {
                TextureAssets.Players[ID, pieceIDs[i]] = Main.Assets.Request<Texture2D>(string.Concat(new object[]
                {
                    "Images/Player_",
                    ID,
                    "_",
                    pieceIDs[i]
                }), 2);
            }
        }
References Terraria.Main.Assets, and Terraria.GameContent.TextureAssets.Players.
Referenced by Terraria.Initializers.PlayerDataInitializer.LoadCoatFemale(), Terraria.Initializers.PlayerDataInitializer.LoadCoatMale(), Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollFemale(), Terraria.Initializers.PlayerDataInitializer.LoadDisplayDollMale(), Terraria.Initializers.PlayerDataInitializer.LoadDressFemale(), Terraria.Initializers.PlayerDataInitializer.LoadDressMale(), Terraria.Initializers.PlayerDataInitializer.LoadGangsterFemale(), Terraria.Initializers.PlayerDataInitializer.LoadGangsterMale(), Terraria.Initializers.PlayerDataInitializer.LoadStarterFemale(), Terraria.Initializers.PlayerDataInitializer.LoadStarterMale(), Terraria.Initializers.PlayerDataInitializer.LoadStickerFemale(), and Terraria.Initializers.PlayerDataInitializer.LoadStickerMale().