Terraria Decompiled: Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar
DrawValueBar()
float Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar (SpriteBatch sb, Vector2 drawPosition, float drawScale, float sliderPosition, int lockMode, out bool wasInBar, Func< float, Color > blipColorFunc) inline private
Definition at line 119 of file UIColoredSlider.cs.
        {
            Texture2D value = TextureAssets.ColorBar.Value;
            Vector2 vector = new Vector2((float)value.Width, (float)value.Height) * drawScale;
            drawPosition.X -= (float)((int)vector.X);
            Rectangle rectangle = new Rectangle((int)drawPosition.X, (int)drawPosition.Y - (int)vector.Y / 2, (int)vector.X, (int)vector.Y);
            Rectangle rectangle2 = rectangle;
            sb.Draw(value, rectangle, Color.White);
            float num = (float)rectangle.X + 5f * drawScale;
            float num2 = (float)rectangle.Y + 4f * drawScale;
            for (float num3 = 0f; num3 < 167f; num3 += 1f)
            {
                float num4 = num3 / 167f;
                Color color = blipColorFunc(num4);
                sb.Draw(TextureAssets.ColorBlip.Value, new Vector2(num + num3 * drawScale, num2), null, color, 0f, Vector2.Zero, drawScale, SpriteEffects.None, 0f);
            }
            rectangle.X = (int)num - 2;
            rectangle.Y = (int)num2;
            rectangle.Width -= 4;
            rectangle.Height -= 8;
            bool flag = rectangle.Contains(new Point(Main.mouseX, Main.mouseY));
            this._isReallyMouseOvered = flag;
            if (this.IgnoresMouseInteraction)
            {
                flag = false;
            }
            if (lockMode == 2)
            {
                flag = false;
            }
            if (flag || lockMode == 1)
            {
                sb.Draw(TextureAssets.ColorHighlight.Value, rectangle2, Main.OurFavoriteColor);
                if (!this._alreadyHovered)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                this._alreadyHovered = true;
            }
            else
            {
                this._alreadyHovered = false;
            }
            wasInBar = false;
            if (!this.IgnoresMouseInteraction)
            {
                sb.Draw(TextureAssets.ColorSlider.Value, new Vector2(num + 167f * drawScale * sliderPosition, num2 + 4f * drawScale), null, Color.White, 0f, new Vector2(0.5f * (float)TextureAssets.ColorSlider.Value.Width, 0.5f * (float)TextureAssets.ColorSlider.Value.Height), drawScale, SpriteEffects.None, 0f);
                if (Main.mouseX >= rectangle.X && Main.mouseX <= rectangle.X + rectangle.Width)
                {
                    wasInBar = flag;
                    return (float)(Main.mouseX - rectangle.X) / (float)rectangle.Width;
                }
            }
            if (rectangle.X >= Main.mouseX)
            {
                return 0f;
            }
            return 1f;
        }
References Terraria.GameContent.UI.Elements.UIColoredSlider._alreadyHovered, Terraria.GameContent.TextureAssets.ColorBar, Terraria.GameContent.TextureAssets.ColorBlip, Terraria.GameContent.TextureAssets.ColorHighlight, Terraria.GameContent.TextureAssets.ColorSlider, Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.UIElement.IgnoresMouseInteraction, int, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.OurFavoriteColor, Terraria.Audio.SoundEngine.PlaySound(), Microsoft.Xna.Framework.Graphics.Point, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf().