Terraria Decompiled: Terraria.Localization.NetworkText.FromKey
FromKey()
static NetworkText Terraria.Localization.NetworkText.FromKey (string key, params object[] substitutions) inline static
Definition at line 48 of file NetworkText.cs.
        {
            return new NetworkText(key, NetworkText.Mode.LocalizationKey)
            {
                _substitutions = NetworkText.ConvertSubstitutionsToNetworkText(substitutions)
            };
        }
References Terraria.Localization.NetworkText._substitutions, Terraria.Localization.NetworkText.ConvertSubstitutionsToNetworkText(), System.key, and Terraria.Localization.NetworkText.NetworkText().
Referenced by Terraria.GameContent.BannerSystem.AddNPCKillBy(), Terraria.NPC.AI(), Terraria.NPC.checkDead(), Terraria.Main.CheckForMoonEventsScoreDisplay(), Terraria.Main.CheckForMoonEventsStartingTemporarySeasons(), Terraria.GameContent.Events.BirthdayParty.CheckNight(), Terraria.WorldGen.CheckOrb(), Terraria.GameContent.Events.DD2Event.CheckProgress(), Terraria.Lang.CreateDeathMessage(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_CelebrateBossDeath(), Terraria.GameContent.Events.DD2Event.FailureMessage(), Terraria.MessageBuffer.GetData(), Terraria.NPC.GetFullNetName(), Terraria.Lang.GetInvasionWaveText(), Terraria.GameContent.NPCDamageTracker.GetReport(), Terraria.NPC.GetTypeNetName(), Terraria.NetMessage.greetPlayer(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.Main.InvasionWarning(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.GameContent.Events.DD2Event.LoseInvasionMessage(), Terraria.WorldGen.MessageLunarApocalypse(), Terraria.WorldGen.meteor(), Terraria.GameContent.Events.BirthdayParty.NaturalAttempt(), Terraria.NPC.NewNPC(), Terraria.NPC.NPCLoot(), Terraria.Netplay.OnConnectionAccepted(), Terraria.Chat.Commands.AllDeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.AllPVPDeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.DeathCommand.ProcessIncomingMessage(), Terraria.Chat.Commands.PVPDeathCommand.ProcessIncomingMessage(), Terraria.GameContent.Golf.GolfHelper.ContactListener.PutBallInCup_TextAndEffects(), Terraria.WorldGen.SmashAltar(), Terraria.RemoteClient.SpamUpdate(), Terraria.NPC.SpawnBoss(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.NPC.SpawnOnPlayer(), Terraria.NPC.SpawnSkeletron(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.NPC.SpawnWOF(), Terraria.Main.startDedInputCallBack(), Terraria.WorldGen.StartImpendingDoom(), Terraria.GameContent.Events.DD2Event.StartInvasion(), Terraria.WorldGen.StartMeteorShower(), Terraria.Main.StartRain(), Terraria.NetMessage.SyncOnePlayer(), Terraria.Localization.LocalizedText.ToNetworkText(), Terraria.Localization.LocalizedText.ToNetworkText(), Terraria.NPC.UnlockOrExchangePet(), Terraria.WorldGen.UnspawnHomelessNPC(), Terraria.WorldGen.UnspawnTravelNPC(), Terraria.Main.UpdateSlimeRainWarning(), Terraria.GameContent.Events.BirthdayParty.UpdateTime(), and Terraria.GameContent.Events.DD2Event.WinInvasionInternal().