Terraria Decompiled: Terraria.Localization.NetworkText.ToString
ToString()
override string Terraria.Localization.NetworkText.ToString () inline
Definition at line 123 of file NetworkText.cs.
        {
            try
            {
                switch (this._mode)
                {
                case NetworkText.Mode.Literal:
                    return this._text;
                case NetworkText.Mode.Formattable:
                {
                    string text = this._text;
                    object[] array = this._substitutions;
                    return string.Format(text, array);
                }
                case NetworkText.Mode.LocalizationKey:
                {
                    string text2 = this._text;
                    object[] array = this._substitutions;
                    return Language.GetTextValue(text2, array);
                }
                default:
                    return this._text;
                }
            }
            catch (Exception ex)
            {
                "NetworkText.ToString() threw an exception.\n" + this.ToDebugInfoString("") + "\n" + "Exception: " + ex;
                this.SetToEmptyLiteral();
            }
            return this._text;
        }
References Terraria.Localization.NetworkText._mode, Terraria.Localization.NetworkText._substitutions, Terraria.Localization.NetworkText._text, System.array, Terraria.Localization.Language.GetTextValue(), Terraria.Localization.NetworkText.SetToEmptyLiteral(), System.text, and Terraria.Localization.NetworkText.ToDebugInfoString().
Referenced by Terraria.Localization.NetworkText.ConvertSubstitutionsToNetworkText(), Terraria.Player.DropTombstone(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Items.ItemVariant.ToString(), and Terraria.GameContent.Items.ItemVariantCondition.ToString().