Terraria Decompiled: Terraria.Localization.NetworkText.Deserialize
Deserialize()
static NetworkText Terraria.Localization.NetworkText.Deserialize (BinaryReader reader) inline static
Definition at line 79 of file NetworkText.cs.
        {
            NetworkText.Mode mode = (NetworkText.Mode)reader.ReadByte();
            NetworkText networkText = new NetworkText(reader.ReadString(), mode);
            networkText.DeserializeSubstitutionList(reader);
            return networkText;
        }
References Terraria.Localization.NetworkText.DeserializeSubstitutionList(), System.mode, Terraria.Localization.NetworkText.NetworkText(), System.IO.BinaryReader.ReadByte(), and System.IO.BinaryReader.ReadString().
Referenced by Terraria.GameContent.NetModules.NetTextModule.DeserializeAsClient(), Terraria.Localization.NetworkText.DeserializeSubstitutionList(), and Terraria.MessageBuffer.GetData().