Terraria Decompiled: Terraria.Localization.NetworkText.ToDebugInfoString
ToDebugInfoString()
string Terraria.Localization.NetworkText.ToDebugInfoString (string linePrefix = "") inline private
Definition at line 156 of file NetworkText.cs.
        {
            string text = string.Format("{0}Mode: {1}\n{0}Text: {2}\n", linePrefix, this._mode, this._text);
            if (this._mode == NetworkText.Mode.LocalizationKey)
            {
                text += string.Format("{0}Localized Text: {1}\n", linePrefix, Language.GetTextValue(this._text));
            }
            if (this._mode != NetworkText.Mode.Literal)
            {
                for (int i = 0; i < this._substitutions.Length; i++)
                {
                    text += string.Format("{0}Substitution {1}:\n", linePrefix, i);
                    text += this._substitutions[i].ToDebugInfoString(linePrefix + "\t");
                }
            }
            return text;
        }
References Terraria.Localization.NetworkText._mode, Terraria.Localization.NetworkText._substitutions, Terraria.Localization.NetworkText._text, Terraria.Localization.Language.GetTextValue(), System.text, and Terraria.Localization.NetworkText.ToDebugInfoString().
Referenced by Terraria.Localization.NetworkText.ToDebugInfoString(), and Terraria.Localization.NetworkText.ToString().