Terraria Decompiled: Terraria.Localization.NetworkText.ConvertSubstitutionsToNetworkText
ConvertSubstitutionsToNetworkText()
static NetworkText[] Terraria.Localization.NetworkText.ConvertSubstitutionsToNetworkText (object[] substitutions) inline static private
Definition at line 17 of file NetworkText.cs.
        {
            NetworkText[] array = new NetworkText[substitutions.Length];
            for (int i = 0; i < substitutions.Length; i++)
            {
                NetworkText networkText = substitutions[i] as NetworkText;
                if (networkText == null)
                {
                    networkText = NetworkText.FromLiteral(substitutions[i].ToString());
                }
                array[i] = networkText;
            }
            return array;
        }
References System.array, Terraria.Localization.NetworkText.FromLiteral(), Terraria.Localization.NetworkText.NetworkText(), and Terraria.Localization.NetworkText.ToString().
Referenced by Terraria.Localization.NetworkText.FromFormattable(), and Terraria.Localization.NetworkText.FromKey().