Terraria Decompiled: Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren
BuildChildren()
void Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren () inline private
Definition at line 68 of file UIResourcePack.cs.
        {
            StyleDimension styleDimension = StyleDimension.FromPixels(77f);
            StyleDimension styleDimension2 = StyleDimension.FromPixels(4f);
            UIText uitext = new UIText(this.ResourcePack.Name, 1f, false)
            {
                Left = styleDimension,
                Top = styleDimension2
            };
            base.Append(uitext);
            styleDimension2.Pixels += uitext.GetOuterDimensions().Height + 6f;
            UIText uitext2 = new UIText(Language.GetTextValue("UI.Author", this.ResourcePack.Author), 0.7f, false)
            {
                Left = styleDimension,
                Top = styleDimension2
            };
            base.Append(uitext2);
            styleDimension2.Pixels += uitext2.GetOuterDimensions().Height + 10f;
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Divider", 1);
            UIImage uiimage = new UIImage(asset)
            {
                Left = StyleDimension.FromPixels(72f),
                Top = styleDimension2,
                Height = StyleDimension.FromPixels((float)asset.Height()),
                Width = StyleDimension.FromPixelsAndPercent(-80f, 1f),
                ScaleToFit = true
            };
            this.Recalculate();
            base.Append(uiimage);
            styleDimension2.Pixels += uiimage.GetOuterDimensions().Height + 5f;
            UIElement uielement = new UIElement
            {
                Left = styleDimension,
                Top = styleDimension2,
                Height = StyleDimension.FromPixels(92f - styleDimension2.Pixels),
                Width = StyleDimension.FromPixelsAndPercent(-styleDimension.Pixels, 1f)
            };
            base.Append(uielement);
            this.ContentPanel = uielement;
        }
References Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.GetOuterDimensions(), Terraria.Localization.Language.GetTextValue(), Terraria.UI.CalculatedStyle.Height, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.IO.ResourcePack.Name, Terraria.UI.StyleDimension.Pixels, Terraria.UI.UIElement.Recalculate(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIResourcePack.UIResourcePack().