Terraria Decompiled: Terraria.Audio.SoundEngine.PlayTrackedSound
PlayTrackedSound() [2/2]
static SlotId Terraria.Audio.SoundEngine.PlayTrackedSound (SoundStyle style, Vector2 position, SoundPlayOverrides overrides = default(SoundPlayOverrides)) inline static
Definition at line 144 of file SoundEngine.cs.
        {
            if (Main.dedServ || !SoundEngine.IsAudioSupported)
            {
                return SlotId.Invalid;
            }
            if (style.MaxTrackedInstances > 0 && SoundEngine.SoundPlayer.GetActiveSoundCount(style) >= style.MaxTrackedInstances)
            {
                return SlotId.Invalid;
            }
            return SoundEngine.SoundPlayer.Play(style, position, overrides);
        }
References Terraria.Main.dedServ, Terraria.Audio.SoundPlayer.GetActiveSoundCount(), ReLogic.Utilities.SlotId.Invalid, Terraria.Audio.SoundEngine.IsAudioSupported, Terraria.Audio.SoundStyle.MaxTrackedInstances, Terraria.Audio.SoundPlayer.Play(), and Terraria.Audio.SoundEngine.SoundPlayer.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_134_Ballista(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_143_MonkStaffT2Ghast(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.SceneState.ApplyVisuals(), Terraria.Initializers.AchievementInitializer.OnAchievementCompleted(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsMushroomBoiExplosion().