Terraria Decompiled: Terraria.Audio.SoundEngine.TestAudioSupport
TestAudioSupport()
static bool Terraria.Audio.SoundEngine.TestAudioSupport () inline static private
Definition at line 220 of file SoundEngine.cs.
        {
            byte[] array = new byte[]
            {
                82, 73, 70, 70, 158, 0, 0, 0, 87, 65,
                86, 69, 102, 109, 116, 32, 16, 0, 0, 0,
                1, 0, 1, 0, 68, 172, 0, 0, 136, 88,
                1, 0, 2, 0, 16, 0, 76, 73, 83, 84,
                26, 0, 0, 0, 73, 78, 70, 79, 73, 83,
                70, 84, 14, 0, 0, 0, 76, 97, 118, 102,
                53, 54, 46, 52, 48, 46, 49, 48, 49, 0,
                100, 97, 116, 97, 88, 0, 0, 0, 0, 0,
                126, 4, 240, 8, 64, 13, 95, 17, 67, 21,
                217, 24, 23, 28, 240, 30, 94, 33, 84, 35,
                208, 36, 204, 37, 71, 38, 64, 38, 183, 37,
                180, 36, 58, 35, 79, 33, 1, 31, 86, 28,
                92, 25, 37, 22, 185, 18, 42, 15, 134, 11,
                222, 7, 68, 4, 196, 0, 112, 253, 86, 250,
                132, 247, 6, 245, 230, 242, 47, 241, 232, 239,
                25, 239, 194, 238, 231, 238, 139, 239, 169, 240,
                61, 242, 67, 244, 180, 246
            };
            try
            {
                using (MemoryStream memoryStream = new MemoryStream(array))
                {
                    SoundEffect.FromStream(memoryStream);
                }
            }
            catch (NoAudioHardwareException)
            {
                Console.WriteLine("No audio hardware found. Disabling all audio.");
                return false;
            }
            catch
            {
                return false;
            }
            return true;
        }
References System.array, Microsoft.Xna.Framework.Audio.SoundEffect.FromStream(), and System.Console.WriteLine().
Referenced by Terraria.Audio.SoundEngine.Initialize().