Terraria Decompiled: Terraria.Audio.SoundEngine.PlaySound
PlaySound() [2/4]
static void Terraria.Audio.SoundEngine.PlaySound (int type, Vector2 position, int style = 1, float pitchOffset = 0f) inline static
Definition at line 102 of file SoundEngine.cs.
        {
            SoundEngine.PlaySound(type, (int)position.X, (int)position.Y, style, 1f, pitchOffset);
        }
References Terraria.Audio.SoundEngine.PlaySound(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.UI.ItemSlot.AfterItemSwap(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_002_FloatingEye(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_015_HandleMovementCollision(), Terraria.Projectile.AI_015_HandleMovementCollision_Old(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.Projectile.AI_061_FishingBobber_DoASplash(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_100_Medusa(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_122_PirateGhost(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.NPC.AI_126_StatueMimic(), Terraria.NPC.AI_127_Pal(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Projectile.AI_157_SharpTears(), Terraria.Projectile.AI_164_StormTigerGem(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_170_FairyGlowstick(), Terraria.Projectile.AI_178_FireExplosion(), Terraria.Projectile.AI_180_FairyQueenSunDance(), Terraria.Projectile.AI_182_FinalFractal(), Terraria.Projectile.AI_184_BadTorchLuck(), Terraria.Projectile.AI_188_LightsBane(), Terraria.Projectile.AI_189_Volcano(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_193_Flamethrower(), Terraria.Projectile.AI_196_Petal(), Terraria.Projectile.AI_197_HandleTileCollision(), Terraria.Projectile.AI_198_Flint(), Terraria.Projectile.AI_202_TorchGodHelper(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Projectile.AI_204_Digtoise(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.Main.Ambience(), Terraria.NPC.ApplyEelWhipDoT(), Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyWilsonBeard(), Terraria.UI.ItemSlot.ArmorSwap(), Terraria.GameContent.UI.IssueReportsIndicator.AttemptLettingPlayerKnow(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_14(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_17(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_18(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_2(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_5(), Terraria.GameContent.UI.States.UIVirtualKeyboard.b__49_9(), Terraria.GameContent.UI.States.UIVirtualKeyboard.BackSpace(), Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.bottomText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.bottomText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.bottomText_OnClick(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.bottomText_OnClick(), Terraria.GameContent.UI.States.UIVirtualKeyboard.BuildSpaceBarArea(), Terraria.DelegateMethods.Minecart.BumperSound(), Terraria.DelegateMethods.Minecart.BumperSoundFart(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOut(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.Button_OnMouseOver(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.Button_OnMouseOver(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.button_OnMouseOver(), Terraria.Main.BuyHairWindow(), Terraria.GameContent.UI.States.UIVirtualKeyboard.Cancel(), Terraria.Main.CancelClothesWindow(), Terraria.Main.CanceledGivingServerPassword(), Terraria.Main.CancelHairWindow(), Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage(), Terraria.WorldGen.Check2x1(), Terraria.NPC.checkDead(), Terraria.Player.CheckDrowning(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPot(), Terraria.GameInput.PlayerInput.CheckRebindingProcessGamepad(), Terraria.GameInput.PlayerInput.CheckRebindingProcessKeyboard(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharClothStyle(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CharInfo(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ClothStyles(), Terraria.GameContent.UI.States.UICharacterCreation.Click_ColorPicker(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CopyHex(), Terraria.GameContent.UI.States.UICharacterCreation.Click_CopyPlayerTemplate(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Expert(), Terraria.GameContent.UI.States.UIBestiaryTest.Click_GoBack(), Terraria.GameContent.UI.States.UICharacterCreation.Click_HairStyles(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.Click_Info(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Journey(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Master(), Terraria.GameContent.UI.States.UICharacterCreation.Click_Naming(), Terraria.GameContent.UI.States.UICharacterCreation.Click_NamingAndCreating(), Terraria.GameContent.UI.States.UIWorldCreation.Click_NamingAndCreating(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Click_Normal(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenResourcePackPublishMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenResourcePacksMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenWorldImportMenu(), Terraria.GameContent.UI.States.UIWorkshopHub.Click_OpenWorldPublishMenu(), Terraria.GameContent.UI.States.UICharacterCreation.Click_PasteHex(), Terraria.GameContent.UI.States.UICharacterCreation.Click_PastePlayerTemplate(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizePlayer(), Terraria.GameContent.UI.States.UICharacterCreation.Click_RandomizeSingleColor(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.Click_SetPreviewImage(), Terraria.GameContent.UI.States.UICharacterCreation.Click_VoicePitch(), Terraria.IngameOptions.Close(), Terraria.UI.IngameFancyUI.Close(), Terraria.GameContent.UI.NewCraftingUI.Close(), Terraria.UI.IngameUIWindows.CloseAll(), Terraria.WorldGen.CloseDoor(), Terraria.Main.CloseNPCChatOrSign(), Terraria.Player.CloseSign(), Terraria.NPC.Collision_WaterCollision(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackInfoButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CursorLeft(), Terraria.GameContent.UI.States.UIVirtualKeyboard.CursorRight(), Terraria.DataStructures.RejectionMenuInfo.DefaultExitAction(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteButtonClick(), Terraria.UI.ChestUI.DepositAll(), Terraria.UI.ChestUI.DepositAll_IntoLocalChest(), Terraria.UI.ChestUI.DepositAll_IntoWorldChest(), Terraria.Graphics.Renderers.FakeFishParticle.DoStandardWaterSplash(), Terraria.Main.DoStatefulTickSound(), Terraria.Main.DoStatefulTickSound(), Terraria.Main.DoUpdate_Enter_ToggleChat(), Terraria.Main.DoUpdate_F10_ToggleFPS(), Terraria.Main.DoUpdate_F11_ToggleUI(), Terraria.Main.DoUpdate_F7_ToggleGraphicsDiagnostics(), Terraria.Main.DoUpdate_F8_ToggleNetDiagnostics(), Terraria.Main.DoUpdate_F9_ToggleLighting(), Terraria.Main.DoUpdate_HandleChat(), Terraria.IngameOptions.Draw(), Terraria.Map.TeleportPylonsMapLayer.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.UI.BannerClaimingUI.DrawBannersGrid(), Terraria.UI.BannerClaimingUI.DrawBannersList_Move(), Terraria.Main.DrawBestiaryIcon(), Terraria.Main.DrawBlockReplacementIcon(), Terraria.Main.DrawBuilderAccToggles(), Terraria.GameContent.UI.NPCChatPanel.DrawButtons(), Terraria.Main.DrawClothesWindow(), Terraria.UI.CraftingUI.DrawCraftFromNearbyChestsToggle(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.UI.BannerClaimingUI.DrawGridToggle(), Terraria.UI.CraftingUI.DrawGridToggle(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawHotbarLockIcon(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInventory(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawNPCChatButtons(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.UI.AchievementAdvisor.DrawOneAchievement(), Terraria.Main.DrawPageIcons(), Terraria.Main.DrawPVPIcons(), Terraria.UI.CraftingUI.DrawRecipes_AdjustRecipeOffset(), Terraria.UI.CraftingUI.DrawRecipes_AdjustRecipeOffsetSnappy(), Terraria.UI.CraftingUI.DrawRecipesGrid(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterNameButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIClothStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawSelf(), Terraria.GameContent.UI.Elements.UIDifficultyButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.Main.DrawSettingButton(), Terraria.Main.DrawStar(), Terraria.Main.DrawTorchBiomeSwapIcon(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.Cinematics.DD2Film.DryadPortalFade(), Terraria.Cinematics.DD2Film.DryadPortalKnock(), Terraria.Main.DryadText_WorldPurityOrStardewValleyBit(), Terraria.UI.ItemSlot.DyeSwap(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.Player.EmitMaxManaEffect(), Terraria.WorldGen.SecretSeed.Enable(), Terraria.GameInput.PlayerInput.EnterBuildingMode(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorFormal(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorFuneral(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorGold(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorHallowed(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorNone(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorSilver(), Terraria.GameContent.UI.States.UICharacterCreation.EquipArmorSwimming(), Terraria.UI.ItemSlot.EquipSwap(), Terraria.GameInput.PlayerInput.ExitBuildingMode(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.FadedMouseOver(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FadedMouseOver(), Terraria.GameContent.UI.States.UIAchievementsMenu.FadedMouseOver(), Terraria.GameContent.UI.States.UIBestiaryTest.FadedMouseOver(), Terraria.GameContent.UI.States.UICharacterCreation.FadedMouseOver(), Terraria.GameContent.UI.States.UICharacterSelect.FadedMouseOver(), Terraria.GameContent.UI.States.UIDebugCommandsList.FadedMouseOver(), Terraria.GameContent.UI.States.UIEmotesMenu.FadedMouseOver(), Terraria.GameContent.UI.States.UIManageControls.FadedMouseOver(), Terraria.GameContent.UI.States.UIReportsPage.FadedMouseOver(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.FadedMouseOver(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.FadedMouseOver(), Terraria.GameContent.UI.States.UIVirtualKeyboard.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorkshopHub.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorldCreation.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.FadedMouseOver(), Terraria.GameContent.UI.States.UIWorldSelect.FadedMouseOver(), Terraria.NPC.FairyEffects(), Terraria.Initializers.UILinksInitializer.FancyExit(), Terraria.Player.FillAmmo(), Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList(), Terraria.NPC.FindFrame(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.Player.GetItem_FillEmptyInventorySlot(), Terraria.Player.GetItem_FillEmptyInventorySlot_VoidBag(), Terraria.Player.GetItem_FillIntoOccupiedSlot(), Terraria.Player.GetItem_FillIntoOccupiedSlot_VoidBag(), Terraria.IO.WorldFileData.GetRenameCallback(), Terraria.GameContent.UI.States.UICharacterCreation.GoBack(), Terraria.GameContent.UI.States.UIWorldCreation.GoBack(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.GoBack(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.GoBack(), Terraria.GameContent.UI.States.UICharacterSelect.GoBackClick(), Terraria.GameContent.UI.States.UIReportsPage.GoBackClick(), Terraria.GameContent.UI.States.UIWorkshopHub.GoBackClick(), Terraria.GameContent.UI.States.UIWorldSelect.GoBackClick(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.GoBackHere(), Terraria.GameContent.UI.States.UIWorkshopHub.GoLogsClick(), Terraria.GameContent.UI.States.UICharacterCreation.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopHub.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.HandleBackButtonUsage(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.HandleBackButtonUsage(), Terraria.Player.HandleBeingInChestRange(), Terraria.GameContent.UI.NewCraftingUI.HandleCraftSlot(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleOptionsSpecials(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Player.HandleSpectatingControls(), Terraria.NPC.HitEffect(), Terraria.Wiring.HitSwitch(), Terraria.Player.HorizontalMovement(), Terraria.Main.HoverOverCraftingItemButton(), Terraria.Main.HoverOverNPCs(), Terraria.NPC.IdleSounds(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Terraria.GameContent.NPCInteractions.Actions.StardewValleyBit.Interact(), Terraria.GameContent.NPCInteractions.Actions.DryadPurification.Interact(), Terraria.GameContent.NPCInteractions.Actions.GuideTip.Interact(), Terraria.GameContent.NPCInteractions.Actions.ReportHappiness.Interact(), Terraria.GameContent.NPCInteractions.Actions.RequestHome.Interact(), Terraria.GameContent.UI.States.UIVirtualKeyboard.InternalSubmit(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_ManageRightClickFeatures(), Terraria.Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.Player.ItemCheck_StartActualUse(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.DelegateMethods.Minecart.JumpingSoundFart(), Terraria.Player.JumpMovement(), Terraria.WorldGen.JustQuit(), Terraria.WorldGen.KillActuator(), Terraria.WorldGen.KillTile_PlaySounds(), Terraria.WorldGen.KillWall_PlaySounds(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.Projectile.KiteLogic(), Terraria.DelegateMethods.Minecart.LandingSound(), Terraria.DelegateMethods.Minecart.LandingSoundFart(), Terraria.UI.ItemSlot.LeftClick(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.LeftMouseDown(), Terraria.GameContent.UI.Elements.UIDifficultyButton.LeftMouseDown(), Terraria.GameContent.UI.Elements.UIHairStyleButton.LeftMouseDown(), Terraria.GameContent.UI.Elements.UIIconTextButton.LeftMouseDown(), Terraria.Chest.Lock(), Terraria.Player.MakeFloorDust(), Terraria.Mount.MeowcartBumperSound(), Terraria.Mount.MeowcartLandingSound(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.middleText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.middleText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.middleText_OnClick(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.middleText_OnClick(), Terraria.NPC.moneyPing(), Terraria.GameContent.UI.Elements.EmoteButton.MouseOver(), Terraria.GameContent.UI.Elements.UIColoredImageButton.MouseOver(), Terraria.GameContent.UI.Elements.UIImageButton.MouseOver(), Terraria.GameContent.UI.Elements.UISearchBar.MouseOver(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.MouseOver(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.MouseOver(), Terraria.UI.ChestUI.MoveCoins(), Terraria.WorldItem.MoveInWorld(), Terraria.UI.BannerClaimingUI.NavigatePipsGrid(), Terraria.UI.BannerClaimingUI.NavigatePipsList(), Terraria.GameContent.UI.States.UICharacterSelect.NewCharacterClick(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewText(), Terraria.Main.NewText(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextInternal(), Terraria.Main.NewTextMultiline(), Terraria.GameContent.UI.States.UIWorldSelect.NewWorldClick(), Terraria.Main.NPCChatText_DoAnglerQuest(), Terraria.Main.NPCChatText_DoNurseHeal(), Terraria.Main.NPCChatText_DyeTraderRarePlant(), Terraria.Main.NPCChatText_GuideReverseCrafting(), Terraria.Main.NPCChatText_PartyGirlSwapMusic(), Terraria.Main.NPCChatText_TavernkeepAdvice(), Terraria.Main.NPCChatText_TinkererReforge(), Terraria.Cinematics.DD2Film.OgreSwingSound(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.OnPlayerUpdate(), Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerUpdate(), Terraria.Main.OnSubmitServerIP(), Terraria.IngameOptions.Open(), Terraria.GameContent.UI.NewCraftingUI.Open(), Terraria.GameContent.UI.NewCraftingUI.OpenCloseFilter(), Terraria.Main.OpenClothesWindow(), Terraria.WorldGen.OpenDoor(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OpenFoldersClick(), Terraria.Main.OpenHairWindow(), Terraria.Player.OpenInventory(), Terraria.GameContent.UI.States.UIWorldCreation.OpenSeedInputMenu(), Terraria.Main.OpenShop(), Terraria.Player.OpenSign(), Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.Player.PetMount(), Terraria.Player.PickupItem(), Terraria.WorldGen.PlaceActuator(), Terraria.WorldGen.PlaceObject(), Terraria.Player.PlaceThing_ItemInExtractinator(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceWall(), Terraria.WorldGen.PlaceWire(), Terraria.WorldGen.PlaceWire2(), Terraria.WorldGen.PlaceWire3(), Terraria.WorldGen.PlaceWire4(), Terraria.Player.PlayDeathSound(), Terraria.Player.PlayDrums(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame(), Terraria.Player.PlayGuitarChord(), Terraria.Player.PlayHurtSound(), Terraria.Main.PlayInteractiveProjectileOpenCloseSound(), Terraria.WorldGen.PlayLiquidChangeSound(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.LucyAxeMessage.PlaySound(), Terraria.WorldGen.playWorldCallBack(), Terraria.WorldGen.PoundTile(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.PressButton(), Terraria.GameContent.UI.States.UIVirtualKeyboard.PressSpace(), Terraria.Player.QuickBuff(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickHeal(), Terraria.Player.QuickMana(), Terraria.Player.QuickMount(), Terraria.UI.ChestUI.QuickStack(), Terraria.GameContent.UI.States.UIManageControls.RadialButtonClick(), Terraria.Projectile.RainbowBoulder_CheckBounce(), Terraria.NPC.ReflectProjectile(), Terraria.Main.ReforgeItemInReforgeSlot(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.RejectionMenuExitAction(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameButtonClick(), Terraria.UI.ChestUI.RenameChestCancel(), Terraria.UI.ChestUI.RenameChestSubmit(), Terraria.GameContent.Events.DD2Event.RequestToSkipWaitTime(), Terraria.Player.ResetEffects(), Terraria.UI.ChestUI.Restock(), Terraria.UI.ItemSlot.RightClick(), Terraria.WorldGen.SaveAndQuit(), Terraria.WorldGen.SaveAndQuitCallBack(), Terraria.Main.SaveClothesWindow(), Terraria.UI.ChestUI.Scroll(), Terraria.UI.BannerClaimingUI.ScrollCraftingGrid(), Terraria.UI.CraftingUI.ScrollCraftingGrid(), Terraria.Graphics.Capture.CaptureInterface.Scrolling(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.searchCancelButton_OnClick(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.searchCancelButton_OnMouseOver(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SecretSeedButton_OnLeftClick(), Terraria.Player.SelectedItemState.Select(), Terraria.Main.SelectPlayer(), Terraria.UI.BannerClaimingUI.SendRequestForBanner(), Terraria.WorldGen.serverLoadWorldCallBack(), Terraria.Projectile.SetFishingCheckResults(), Terraria.DataStructures.TileEntity.SetInteractionAnchor(), Terraria.Mount.SetMount(), Terraria.WorldGen.ShiftTallGate(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldItem.ShimmerEffect(), Terraria.WorldGen.SlopeTile(), Terraria.GameContent.UI.States.UIManageControls.SnapButtonClick(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsBarnacleShotFiring(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FlyMeal(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_GasTrap(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_HeroicisSetSpawnSound(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_InScreenDungeonSpawn(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammerShockwave(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_SlapHand(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_VampireOnFire(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_WaffleIron(), Terraria.GameContent.CraftingEffects.SpawnEffects_BeforeGrantingItem(), Terraria.Player.SpawnFastRunParticles(), Terraria.Graphics.Capture.CaptureInterface.StartCamera(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.steamDisclaimerText_OnMouseOver(), Terraria.WorldGen.StopWaterfallAmbienceAudio(), Terraria.NPC.StrikeNPC(), Terraria.Main.SubmitSignText(), Terraria.UI.ItemSlot.SwapVanityEquip(), Terraria.Player.Teleport(), Terraria.Main.TeleportEffect(), Terraria.Player.TileInteractionsUse(), Terraria.Graphics.Capture.CaptureInterface.ToggleCamera(), Terraria.Player.ToggleInv(), Terraria.GameContent.Creative.CreativeUI.ToggleMenu(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.topText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.topText_OnClick(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.topText_OnClick(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.topText_OnClick(), Terraria.NPC.TransformVisuals(), Terraria.Wiring.TryAddingToEmptySlot(), Terraria.DataStructures.TitleLinkButton.TryClicking(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.TryFitting(), Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting(), Terraria.Main.TryInteractingWithVoidLens(), Terraria.Main.TryMovingNPC(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.TryMovingToRejectionMenuIfNeeded(), Terraria.GameContent.UI.Elements.UIWorldListItem.TryMovingToRejectionMenuIfNeeded(), Terraria.UI.ItemSlot.TryOpenContainer(), Terraria.Player.TryOpeningFullscreenMap(), Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.Main.TryRemovingBuff(), Terraria.UI.ItemSlot.TryResearchingItem(), Terraria.Player.TrySwitchingLoadout(), Terraria.Player.TryToToggleSmartCursor(), Terraria.Player.TryUsingFoxsparksAbility(), Terraria.GameContent.UI.States.UIVirtualKeyboard.TypeText(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.Chest.Unlock(), Terraria.WorldGen.UnlockDoor(), Terraria.GameContent.UI.Minimap.MinimapFrame.Update(), Terraria.Gore.Update(), Terraria.GameContent.UI.States.UITextWrappingTest.Update(), Terraria.GameContent.UI.States.UIWorldLoad.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.GameContent.DontStarveDarknessDamageDealer.Update(), Terraria.Graphics.Capture.CaptureInterface.UpdateButtons(), Terraria.Chest.UpdateChestFrames(), Terraria.UI.ChestUI.UpdateHover(), Terraria.Player.UpdateHungerBuffs(), Terraria.Player.UpdateManaRegen(), Terraria.NPC.UpdateNPC_CritterSounds(), Terraria.Player.UpdatePet(), Terraria.Player.UpdatePetLight(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateVisualFrame(), Terraria.Main.UpdateWeather(), Terraria.Mount.UseAbility(), Terraria.Player.WingFrame(), Terraria.Player.WOFTongue(), Terraria.WorldGen.worldGenCallback(), and Terraria.GameContent.UI.States.UIVirtualKeyboard.Write().