Terraria Decompiled: System.Collections.IList.IndexOf
IndexOf()
int System.Collections.IList.IndexOf (object value)
Implemented in System.Collections.SortedList.KeyList, System.Collections.ArrayList, System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList.Range, System.Collections.CollectionBase, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.SortedList.ValueList, and Newtonsoft.Json.Utilities.CollectionWrapper< T >.
Referenced by System.Collections.ArrayList.IListWrapper.IndexOf(), System.Collections.ArrayList.SyncIList.IndexOf(), System.Collections.ArrayList.FixedSizeList.IndexOf(), System.Collections.ArrayList.ReadOnlyList.IndexOf(), System.Collections.ObjectModel.Collection< T >.IndexOf(), System.Collections.ObjectModel.ReadOnlyCollection< T >.IndexOf(), and System.Collections.ObjectModel.Collection< T >.Remove().