Terraria Decompiled: System.Collections.IList.Contains
Contains()
bool System.Collections.IList.Contains (object value)
Implemented in System.Collections.ArrayList, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.Range, System.Collections.SortedList.KeyList, System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.CollectionBase, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.SortedList.ValueList, and Newtonsoft.Json.Utilities.CollectionWrapper< T >.
Referenced by System.Collections.ArrayList.SyncIList.Contains(), System.Collections.ArrayList.IListWrapper.Contains(), System.Collections.ArrayList.FixedSizeList.Contains(), System.Collections.ArrayList.ReadOnlyList.Contains(), System.Collections.ObjectModel.Collection< T >.Contains(), and System.Collections.ObjectModel.ReadOnlyCollection< T >.Contains().