Terraria Decompiled: System.Collections.IList.Add
Add()
int System.Collections.IList.Add (object value)
Implemented in System.Collections.SortedList.KeyList, System.Collections.SortedList.ValueList, System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.Range, System.Collections.CollectionBase, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, and Newtonsoft.Json.Utilities.CollectionWrapper< T >.
Referenced by System.Collections.ArrayList.IListWrapper.Add(), System.Collections.ArrayList.SyncIList.Add(), System.Runtime.Remoting.ProviderData.CopyFrom(), System.Runtime.Remoting.Activation.RemoteActivationAttribute.GetPropertiesForNewContext(), and System.Runtime.Remoting.ConfigHandler.ReadCustomProviderData().