Terraria Decompiled: System.Collections.IList.Insert
Insert()
void System.Collections.IList.Insert (int index, object value)
Implemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.FixedSizeList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.SyncIList, System.Collections.ArrayList.Range, System.Collections.CollectionBase, System.Collections.ObjectModel.Collection< T >, System.Collections.ObjectModel.ReadOnlyCollection< T >, System.Collections.SortedList.KeyList, System.Collections.SortedList.ValueList, and Newtonsoft.Json.Utilities.CollectionWrapper< T >.
Referenced by System.Collections.ArrayList.IListWrapper.Insert(), System.Collections.ArrayList.SyncIList.Insert(), System.Collections.ObjectModel.Collection< T >.InsertItem(), and System.Collections.ArrayList.IListWrapper.InsertRange().