Terraria Decompiled: Newtonsoft.Json.JsonWriter.WriteToken
WriteToken() [3/5]
virtual void Newtonsoft.Json.JsonWriter.WriteToken (JsonReader reader, bool writeChildren, bool writeDateConstructorAsDate, bool writeComments) inline package virtual
Reimplemented in Newtonsoft.Json.Linq.JTokenWriter.
Definition at line 531 of file JsonWriter.cs.
        {
            int num = this.CalculateWriteTokenDepth(reader);
            do
            {
                if (writeDateConstructorAsDate && reader.TokenType == JsonToken.StartConstructor && string.Equals(reader.Value.ToString(), "Date", 4))
                {
                    this.WriteConstructorDate(reader);
                }
                else if (writeComments || reader.TokenType != JsonToken.Comment)
                {
                    this.WriteToken(reader.TokenType, reader.Value);
                }
            }
            while (num - 1 < reader.Depth - (JsonTokenUtils.IsEndToken(reader.TokenType) ? 1 : 0) && writeChildren && reader.Read());
        }
References Newtonsoft.Json.JsonWriter.CalculateWriteTokenDepth(), Newtonsoft.Json.JsonReader.Depth, Newtonsoft.Json.Utilities.JsonTokenUtils.IsEndToken(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.JsonReader.Value, Newtonsoft.Json.JsonWriter.WriteConstructorDate(), and Newtonsoft.Json.JsonWriter.WriteToken().