Terraria Decompiled: Newtonsoft.Json.JsonWriter.WriteValue
WriteValue() [22/39]
static void Newtonsoft.Json.JsonWriter.WriteValue (JsonWriter writer, PrimitiveTypeCode typeCode, object value) inline static package
Definition at line 1142 of file JsonWriter.cs.
        {
            switch (typeCode)
            {
            case PrimitiveTypeCode.Char:
                writer.WriteValue((char)value);
                return;
            case PrimitiveTypeCode.CharNullable:
                writer.WriteValue((value == null) ? default(char?) : new char?((char)value));
                return;
            case PrimitiveTypeCode.Boolean:
                writer.WriteValue((bool)value);
                return;
            case PrimitiveTypeCode.BooleanNullable:
                writer.WriteValue((value == null) ? default(bool?) : new bool?((bool)value));
                return;
            case PrimitiveTypeCode.SByte:
                writer.WriteValue((sbyte)value);
                return;
            case PrimitiveTypeCode.SByteNullable:
                writer.WriteValue((value == null) ? default(sbyte?) : new sbyte?((sbyte)value));
                return;
            case PrimitiveTypeCode.Int16:
                writer.WriteValue((short)value);
                return;
            case PrimitiveTypeCode.Int16Nullable:
                writer.WriteValue((value == null) ? default(short?) : new short?((short)value));
                return;
            case PrimitiveTypeCode.UInt16:
                writer.WriteValue((ushort)value);
                return;
            case PrimitiveTypeCode.UInt16Nullable:
                writer.WriteValue((value == null) ? default(ushort?) : new ushort?((ushort)value));
                return;
            case PrimitiveTypeCode.Int32:
                writer.WriteValue((int)value);
                return;
            case PrimitiveTypeCode.Int32Nullable:
                writer.WriteValue((value == null) ? default(int?) : new int?((int)value));
                return;
            case PrimitiveTypeCode.Byte:
                writer.WriteValue((byte)value);
                return;
            case PrimitiveTypeCode.ByteNullable:
                writer.WriteValue((value == null) ? default(byte?) : new byte?((byte)value));
                return;
            case PrimitiveTypeCode.UInt32:
                writer.WriteValue((uint)value);
                return;
            case PrimitiveTypeCode.UInt32Nullable:
                writer.WriteValue((value == null) ? default(uint?) : new uint?((uint)value));
                return;
            case PrimitiveTypeCode.Int64:
                writer.WriteValue((long)value);
                return;
            case PrimitiveTypeCode.Int64Nullable:
                writer.WriteValue((value == null) ? default(long?) : new long?((long)value));
                return;
            case PrimitiveTypeCode.UInt64:
                writer.WriteValue((ulong)value);
                return;
            case PrimitiveTypeCode.UInt64Nullable:
                writer.WriteValue((value == null) ? default(ulong?) : new ulong?((ulong)value));
                return;
            case PrimitiveTypeCode.Single:
                writer.WriteValue((float)value);
                return;
            case PrimitiveTypeCode.SingleNullable:
                writer.WriteValue((value == null) ? default(float?) : new float?((float)value));
                return;
            case PrimitiveTypeCode.Double:
                writer.WriteValue((double)value);
                return;
            case PrimitiveTypeCode.DoubleNullable:
                writer.WriteValue((value == null) ? default(double?) : new double?((double)value));
                return;
            case PrimitiveTypeCode.DateTime:
                writer.WriteValue((DateTime)value);
                return;
            case PrimitiveTypeCode.DateTimeNullable:
                writer.WriteValue((value == null) ? default(DateTime?) : new DateTime?((DateTime)value));
                return;
            case PrimitiveTypeCode.DateTimeOffset:
                writer.WriteValue((DateTimeOffset)value);
                return;
            case PrimitiveTypeCode.DateTimeOffsetNullable:
                writer.WriteValue((value == null) ? default(DateTimeOffset?) : new DateTimeOffset?((DateTimeOffset)value));
                return;
            case PrimitiveTypeCode.Decimal:
                writer.WriteValue((decimal)value);
                return;
            case PrimitiveTypeCode.DecimalNullable:
                writer.WriteValue((value == null) ? default(decimal?) : new decimal?((decimal)value));
                return;
            case PrimitiveTypeCode.Guid:
                writer.WriteValue((Guid)value);
                return;
            case PrimitiveTypeCode.GuidNullable:
                writer.WriteValue((value == null) ? default(Guid?) : new Guid?((Guid)value));
                return;
            case PrimitiveTypeCode.TimeSpan:
                writer.WriteValue((TimeSpan)value);
                return;
            case PrimitiveTypeCode.TimeSpanNullable:
                writer.WriteValue((value == null) ? default(TimeSpan?) : new TimeSpan?((TimeSpan)value));
                return;
            case PrimitiveTypeCode.BigInteger:
                writer.WriteValue((BigInteger)value);
                return;
            case PrimitiveTypeCode.BigIntegerNullable:
                writer.WriteValue((value == null) ? default(BigInteger?) : new BigInteger?((BigInteger)value));
                return;
            case PrimitiveTypeCode.Uri:
                writer.WriteValue((Uri)value);
                return;
            case PrimitiveTypeCode.String:
                writer.WriteValue((string)value);
                return;
            case PrimitiveTypeCode.Bytes:
                writer.WriteValue((byte[])value);
                return;
            case PrimitiveTypeCode.DBNull:
                writer.WriteNull();
                return;
            default:
            {
                IConvertible convertible = value as IConvertible;
                if (convertible != null)
                {
                    TypeInformation typeInformation = ConvertUtils.GetTypeInformation(convertible);
                    PrimitiveTypeCode primitiveTypeCode = ((typeInformation.TypeCode == PrimitiveTypeCode.Object) ? PrimitiveTypeCode.String : typeInformation.TypeCode);
                    Type type = ((typeInformation.TypeCode == PrimitiveTypeCode.Object) ? typeof(string) : typeInformation.Type);
                    object obj = convertible.ToType(type, CultureInfo.InvariantCulture);
                    JsonWriter.WriteValue(writer, primitiveTypeCode, obj);
                    return;
                }
                throw JsonWriter.CreateUnsupportedTypeException(writer, value);
            }
            }
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonWriter.CreateUnsupportedTypeException(), Newtonsoft.Json.DateTime, Newtonsoft.Json.DateTimeOffset, Newtonsoft.Json.Utilities.ConvertUtils.GetTypeInformation(), Newtonsoft.Json.Utilities.Guid, int, System.Globalization.CultureInfo.InvariantCulture, long, System.obj, Newtonsoft.Json.Utilities.TimeSpan, System.IConvertible.ToType(), Newtonsoft.Json.Utilities.TypeInformation.Type, Newtonsoft.Json.Utilities.TypeInformation.TypeCode, System.value, Newtonsoft.Json.JsonWriter.WriteNull(), and Newtonsoft.Json.JsonWriter.WriteValue().