Terraria Decompiled: Newtonsoft.Json.JsonWriter.AutoComplete
AutoComplete()
void Newtonsoft.Json.JsonWriter.AutoComplete (JsonToken tokenBeingWritten) inline package
Definition at line 722 of file JsonWriter.cs.
        {
            JsonWriter.State state = JsonWriter.StateArray[(int)tokenBeingWritten][(int)this._currentState];
            if (state == JsonWriter.State.Error)
            {
                throw JsonWriterException.Create(this, "Token {0} in state {1} would result in an invalid JSON object.".FormatWith(CultureInfo.InvariantCulture, tokenBeingWritten.ToString(), this._currentState.ToString()), null);
            }
            if ((this._currentState == JsonWriter.State.Object || this._currentState == JsonWriter.State.Array || this._currentState == JsonWriter.State.Constructor) && tokenBeingWritten != JsonToken.Comment)
            {
                this.WriteValueDelimiter();
            }
            if (this._formatting == Formatting.Indented)
            {
                if (this._currentState == JsonWriter.State.Property)
                {
                    this.WriteIndentSpace();
                }
                if (this._currentState == JsonWriter.State.Array || this._currentState == JsonWriter.State.ArrayStart || this._currentState == JsonWriter.State.Constructor || this._currentState == JsonWriter.State.ConstructorStart || (tokenBeingWritten == JsonToken.PropertyName && this._currentState != JsonWriter.State.Start))
                {
                    this.WriteIndent();
                }
            }
            this._currentState = state;
        }
References Newtonsoft.Json.JsonWriter._currentState, Newtonsoft.Json.JsonWriter._formatting, Newtonsoft.Json.JsonWriterException.Create(), int, System.Globalization.CultureInfo.InvariantCulture, System.state, Newtonsoft.Json.JsonWriter.StateArray, Newtonsoft.Json.JsonWriter.WriteIndent(), Newtonsoft.Json.JsonWriter.WriteIndentSpace(), and Newtonsoft.Json.JsonWriter.WriteValueDelimiter().
Referenced by Newtonsoft.Json.JsonWriter.InternalWriteComment(), Newtonsoft.Json.JsonWriter.InternalWritePropertyName(), Newtonsoft.Json.JsonWriter.InternalWriteStart(), Newtonsoft.Json.JsonWriter.InternalWriteValue(), and Newtonsoft.Json.JsonWriter.WriteRawValue().