Terraria Decompiled: Newtonsoft.Json.JsonWriter.InternalWriteWhitespace
InternalWriteWhitespace()
void Newtonsoft.Json.JsonWriter.InternalWriteWhitespace (string ws) inline package
Definition at line 1374 of file JsonWriter.cs.
        {
            if (ws != null && !StringUtils.IsWhiteSpace(ws))
            {
                throw JsonWriterException.Create(this, "Only white space characters should be used.", null);
            }
        }
References Newtonsoft.Json.JsonWriterException.Create(), and Newtonsoft.Json.Utilities.StringUtils.IsWhiteSpace().
Referenced by Newtonsoft.Json.JsonWriter.WriteWhitespace().