Terraria Decompiled: Newtonsoft.Json.JsonWriter.WriteConstructorDate
WriteConstructorDate()
void Newtonsoft.Json.JsonWriter.WriteConstructorDate (JsonReader reader) inline private
Definition at line 564 of file JsonWriter.cs.
        {
            if (!reader.Read())
            {
                throw JsonWriterException.Create(this, "Unexpected end when reading date constructor.", null);
            }
            if (reader.TokenType != JsonToken.Integer)
            {
                throw JsonWriterException.Create(this, "Unexpected token when reading date constructor. Expected Integer, got " + reader.TokenType, null);
            }
            DateTime dateTime = DateTimeUtils.ConvertJavaScriptTicksToDateTime((long)reader.Value);
            if (!reader.Read())
            {
                throw JsonWriterException.Create(this, "Unexpected end when reading date constructor.", null);
            }
            if (reader.TokenType != JsonToken.EndConstructor)
            {
                throw JsonWriterException.Create(this, "Unexpected token when reading date constructor. Expected EndConstructor, got " + reader.TokenType, null);
            }
            this.WriteValue(dateTime);
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.ConvertJavaScriptTicksToDateTime(), Newtonsoft.Json.JsonWriterException.Create(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.JsonReader.Value, and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.JsonWriter.WriteToken().