Terraria Decompiled: Newtonsoft.Json.JsonWriter.AutoCompleteClose
AutoCompleteClose()
void Newtonsoft.Json.JsonWriter.AutoCompleteClose (JsonContainerType type) inline private
Definition at line 631 of file JsonWriter.cs.
        {
            int num = this.CalculateLevelsToComplete(type);
            for (int i = 0; i < num; i++)
            {
                JsonToken closeTokenForType = this.GetCloseTokenForType(this.Pop());
                if (this._currentState == JsonWriter.State.Property)
                {
                    this.WriteNull();
                }
                if (this._formatting == Formatting.Indented && this._currentState != JsonWriter.State.ObjectStart && this._currentState != JsonWriter.State.ArrayStart)
                {
                    this.WriteIndent();
                }
                this.WriteEnd(closeTokenForType);
                this.UpdateCurrentState();
            }
        }
References Newtonsoft.Json.JsonWriter._currentState, Newtonsoft.Json.JsonWriter._formatting, Newtonsoft.Json.JsonWriter.CalculateLevelsToComplete(), Newtonsoft.Json.JsonWriter.GetCloseTokenForType(), Newtonsoft.Json.JsonWriter.Pop(), Newtonsoft.Json.JsonWriter.UpdateCurrentState(), Newtonsoft.Json.JsonWriter.WriteEnd(), Newtonsoft.Json.JsonWriter.WriteIndent(), and Newtonsoft.Json.JsonWriter.WriteNull().
Referenced by Newtonsoft.Json.JsonWriter.InternalWriteEnd().