Terraria Decompiled: Newtonsoft.Json.JsonWriter.WriteToken
WriteToken() [5/5]
void Newtonsoft.Json.JsonWriter.WriteToken (JsonToken token, object value) inline
Definition at line 424 of file JsonWriter.cs.
        {
            switch (token)
            {
            case JsonToken.None:
                return;
            case JsonToken.StartObject:
                this.WriteStartObject();
                return;
            case JsonToken.StartArray:
                this.WriteStartArray();
                return;
            case JsonToken.StartConstructor:
                ValidationUtils.ArgumentNotNull(value, "value");
                this.WriteStartConstructor(value.ToString());
                return;
            case JsonToken.PropertyName:
                ValidationUtils.ArgumentNotNull(value, "value");
                this.WritePropertyName(value.ToString());
                return;
            case JsonToken.Comment:
                this.WriteComment((value != null) ? value.ToString() : null);
                return;
            case JsonToken.Raw:
                this.WriteRawValue((value != null) ? value.ToString() : null);
                return;
            case JsonToken.Integer:
                ValidationUtils.ArgumentNotNull(value, "value");
                if (value is BigInteger)
                {
                    this.WriteValue((BigInteger)value);
                    return;
                }
                this.WriteValue(Convert.ToInt64(value, CultureInfo.InvariantCulture));
                return;
            case JsonToken.Float:
                ValidationUtils.ArgumentNotNull(value, "value");
                if (value is decimal)
                {
                    this.WriteValue((decimal)value);
                    return;
                }
                if (value is double)
                {
                    this.WriteValue((double)value);
                    return;
                }
                if (value is float)
                {
                    this.WriteValue((float)value);
                    return;
                }
                this.WriteValue(Convert.ToDouble(value, CultureInfo.InvariantCulture));
                return;
            case JsonToken.String:
                ValidationUtils.ArgumentNotNull(value, "value");
                this.WriteValue(value.ToString());
                return;
            case JsonToken.Boolean:
                ValidationUtils.ArgumentNotNull(value, "value");
                this.WriteValue(Convert.ToBoolean(value, CultureInfo.InvariantCulture));
                return;
            case JsonToken.Null:
                this.WriteNull();
                return;
            case JsonToken.Undefined:
                this.WriteUndefined();
                return;
            case JsonToken.EndObject:
                this.WriteEndObject();
                return;
            case JsonToken.EndArray:
                this.WriteEndArray();
                return;
            case JsonToken.EndConstructor:
                this.WriteEndConstructor();
                return;
            case JsonToken.Date:
                ValidationUtils.ArgumentNotNull(value, "value");
                if (value is DateTimeOffset)
                {
                    this.WriteValue((DateTimeOffset)value);
                    return;
                }
                this.WriteValue(Convert.ToDateTime(value, CultureInfo.InvariantCulture));
                return;
            case JsonToken.Bytes:
                ValidationUtils.ArgumentNotNull(value, "value");
                if (value is Guid)
                {
                    this.WriteValue((Guid)value);
                    return;
                }
                this.WriteValue((byte[])value);
                return;
            default:
                throw MiscellaneousUtils.CreateArgumentOutOfRangeException("token", token, "Unexpected token type.");
            }
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.Utilities.MiscellaneousUtils.CreateArgumentOutOfRangeException(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToBoolean(), System.Convert.ToDateTime(), System.Convert.ToDouble(), System.Convert.ToInt64(), System.value, Newtonsoft.Json.JsonWriter.WriteComment(), Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WriteEndConstructor(), Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WriteNull(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteRawValue(), Newtonsoft.Json.JsonWriter.WriteStartArray(), Newtonsoft.Json.JsonWriter.WriteStartConstructor(), Newtonsoft.Json.JsonWriter.WriteStartObject(), Newtonsoft.Json.JsonWriter.WriteUndefined(), and Newtonsoft.Json.JsonWriter.WriteValue().