Terraria Decompiled: Newtonsoft.Json.JsonWriter.WriteEnd
WriteEnd() [2/3]
void Newtonsoft.Json.JsonWriter.WriteEnd (JsonContainerType type) inline private
Definition at line 587 of file JsonWriter.cs.
        {
            switch (type)
            {
            case JsonContainerType.Object:
                this.WriteEndObject();
                return;
            case JsonContainerType.Array:
                this.WriteEndArray();
                return;
            case JsonContainerType.Constructor:
                this.WriteEndConstructor();
                return;
            default:
                throw JsonWriterException.Create(this, "Unexpected type when writing end: " + type, null);
            }
        }
References Newtonsoft.Json.JsonWriterException.Create(), Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WriteEndConstructor(), and Newtonsoft.Json.JsonWriter.WriteEndObject().