Terraria Decompiled: Newtonsoft.Json.JsonWriter.WriteValue
WriteValue() [25/39]
virtual void Newtonsoft.Json.JsonWriter.WriteValue (object value) inline virtual
Reimplemented in Newtonsoft.Json.Bson.BsonWriter, Newtonsoft.Json.JsonTextWriter, Newtonsoft.Json.Linq.JTokenWriter, and Newtonsoft.Json.Serialization.TraceJsonWriter.
Definition at line 1099 of file JsonWriter.cs.
        {
            if (value == null)
            {
                this.WriteNull();
                return;
            }
            if (value is BigInteger)
            {
                throw JsonWriter.CreateUnsupportedTypeException(this, value);
            }
            JsonWriter.WriteValue(this, ConvertUtils.GetTypeCode(value.GetType()), value);
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonWriter.CreateUnsupportedTypeException(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), System.value, Newtonsoft.Json.JsonWriter.WriteNull(), and Newtonsoft.Json.JsonWriter.WriteValue().