Terraria Decompiled: Newtonsoft.Json.JsonWriter.UpdateCurrentState
UpdateCurrentState()
void Newtonsoft.Json.JsonWriter.UpdateCurrentState () inline private
Definition at line 679 of file JsonWriter.cs.
        {
            JsonContainerType jsonContainerType = this.Peek();
            switch (jsonContainerType)
            {
            case JsonContainerType.None:
                this._currentState = JsonWriter.State.Start;
                return;
            case JsonContainerType.Object:
                this._currentState = JsonWriter.State.Object;
                return;
            case JsonContainerType.Array:
                this._currentState = JsonWriter.State.Array;
                return;
            case JsonContainerType.Constructor:
                this._currentState = JsonWriter.State.Array;
                return;
            default:
                throw JsonWriterException.Create(this, "Unknown JsonType: " + jsonContainerType, null);
            }
        }
References Newtonsoft.Json.JsonWriterException.Create(), and Newtonsoft.Json.JsonWriter.Peek().
Referenced by Newtonsoft.Json.JsonWriter.AutoCompleteClose().