Terraria Decompiled: Newtonsoft.Json.JsonWriter.SetWriteState
SetWriteState()
void Newtonsoft.Json.JsonWriter.SetWriteState (JsonToken token, object value) inline protected
Definition at line 1290 of file JsonWriter.cs.
        {
            switch (token)
            {
            case JsonToken.StartObject:
                this.InternalWriteStart(token, JsonContainerType.Object);
                return;
            case JsonToken.StartArray:
                this.InternalWriteStart(token, JsonContainerType.Array);
                return;
            case JsonToken.StartConstructor:
                this.InternalWriteStart(token, JsonContainerType.Constructor);
                return;
            case JsonToken.PropertyName:
                if (!(value is string))
                {
                    throw new ArgumentException("A name is required when setting property name state.", "value");
                }
                this.InternalWritePropertyName((string)value);
                return;
            case JsonToken.Comment:
                this.InternalWriteComment();
                return;
            case JsonToken.Raw:
                this.InternalWriteRaw();
                return;
            case JsonToken.Integer:
            case JsonToken.Float:
            case JsonToken.String:
            case JsonToken.Boolean:
            case JsonToken.Null:
            case JsonToken.Undefined:
            case JsonToken.Date:
            case JsonToken.Bytes:
                this.InternalWriteValue(token);
                return;
            case JsonToken.EndObject:
                this.InternalWriteEnd(JsonContainerType.Object);
                return;
            case JsonToken.EndArray:
                this.InternalWriteEnd(JsonContainerType.Array);
                return;
            case JsonToken.EndConstructor:
                this.InternalWriteEnd(JsonContainerType.Constructor);
                return;
            default:
                throw new ArgumentOutOfRangeException("token");
            }
        }
References Newtonsoft.Json.JsonWriter.InternalWriteComment(), Newtonsoft.Json.JsonWriter.InternalWriteEnd(), Newtonsoft.Json.JsonWriter.InternalWritePropertyName(), Newtonsoft.Json.JsonWriter.InternalWriteRaw(), Newtonsoft.Json.JsonWriter.InternalWriteStart(), Newtonsoft.Json.JsonWriter.InternalWriteValue(), and System.value.