Terraria Decompiled: Microsoft.Xna.Framework.Input.KeyboardState.GetPressedKeys
GetPressedKeys()
Keys[] Microsoft.Xna.Framework.Input.KeyboardState.GetPressedKeys () inline
Definition at line 75 of file KeyboardState.cs.
        {
            uint num = KeyboardState.CountBits(this.keys0) + KeyboardState.CountBits(this.keys1) + KeyboardState.CountBits(this.keys2) + KeyboardState.CountBits(this.keys3) + KeyboardState.CountBits(this.keys4) + KeyboardState.CountBits(this.keys5) + KeyboardState.CountBits(this.keys6) + KeyboardState.CountBits(this.keys7);
            if (num == 0U)
            {
                return KeyboardState.empty;
            }
            Keys[] array = new Keys[num];
            int num2 = 0;
            if (this.keys0 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys0, 0, array, num2);
            }
            if (this.keys1 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys1, 32, array, num2);
            }
            if (this.keys2 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys2, 64, array, num2);
            }
            if (this.keys3 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys3, 96, array, num2);
            }
            if (this.keys4 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys4, 128, array, num2);
            }
            if (this.keys5 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys5, 160, array, num2);
            }
            if (this.keys6 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys6, 192, array, num2);
            }
            if (this.keys7 != 0U)
            {
                num2 = KeyboardState.AddKeysToArray(this.keys7, 224, array, num2);
            }
            return array;
        }
References Microsoft.Xna.Framework.Input.KeyboardState.AddKeysToArray(), System.array, Microsoft.Xna.Framework.Input.KeyboardState.CountBits(), Microsoft.Xna.Framework.Input.KeyboardState.empty, Microsoft.Xna.Framework.Input.KeyboardState.keys0, Microsoft.Xna.Framework.Input.KeyboardState.keys1, Microsoft.Xna.Framework.Input.KeyboardState.keys2, Microsoft.Xna.Framework.Input.KeyboardState.keys3, Microsoft.Xna.Framework.Input.KeyboardState.keys4, Microsoft.Xna.Framework.Input.KeyboardState.keys5, Microsoft.Xna.Framework.Input.KeyboardState.keys6, Microsoft.Xna.Framework.Input.KeyboardState.keys7, and Microsoft.Xna.Framework.Input.U.
Referenced by Terraria.GameInput.PlayerInput.GetPressedKeys().