Terraria Decompiled: Terraria.IO.WorldFileData.FromInvalidWorld
FromInvalidWorld()
static WorldFileData Terraria.IO.WorldFileData.FromInvalidWorld (string path, bool cloudSave, int statusCode, Exception exception) inline static
Definition at line 369 of file WorldFileData.cs.
        {
            WorldFileData worldFileData = new WorldFileData(path, cloudSave);
            worldFileData.GameMode = 0;
            worldFileData.SetSeedToEmpty();
            worldFileData.WorldGeneratorVersion = 0UL;
            worldFileData.Metadata = FileMetadata.FromCurrentSettings(FileType.World);
            worldFileData.SetWorldSize(1, 1);
            worldFileData.HasCorruption = true;
            worldFileData.IsHardMode = false;
            worldFileData.LoadStatus = statusCode;
            worldFileData.LoadException = exception;
            worldFileData.Name = FileUtilities.GetFileName(path, false);
            worldFileData.UniqueId = Guid.Empty;
            if (!cloudSave)
            {
                worldFileData.CreationTime = File.GetCreationTime(path);
            }
            else
            {
                worldFileData.CreationTime = DateTime.Now;
            }
            return worldFileData;
        }
References System.Guid.Empty, System.exception, Terraria.IO.FileMetadata.FromCurrentSettings(), System.IO.File.GetCreationTime(), Terraria.Utilities.FileUtilities.GetFileName(), System.DateTime.Now, Terraria.IO.WorldFileData.SetSeedToEmpty(), Terraria.IO.WorldFileData.SetWorldSize(), and Terraria.IO.WorldFileData.WorldFileData().
Referenced by Terraria.IO.WorldFile.GetAllMetadata().