Terraria Decompiled: Terraria.IO.WorldFileData.CopyToLocal
CopyToLocal()
void Terraria.IO.WorldFileData.CopyToLocal (string newDisplayName, Action onCompleted) inline
Definition at line 487 of file WorldFileData.cs.
        {
            if (base.IsCloudSave)
            {
                return;
            }
            string worldPathFromName = Main.GetWorldPathFromName(Guid.NewGuid().ToString(), false);
            FileUtilities.Copy(base.Path, worldPathFromName, false);
            this._path = worldPathFromName;
            WorldGen.RenameWorld(this, newDisplayName, this.GetRenameCallback(onCompleted));
        }
References Terraria.Utilities.FileUtilities.Copy(), Terraria.IO.WorldFileData.GetRenameCallback(), Terraria.Main.GetWorldPathFromName(), System.Guid.NewGuid(), Terraria.WorldGen.RenameWorld(), and System.Guid.ToString().
Referenced by Terraria.Social.Steam.WorkshopSocialModule.ImportDownloadedWorldToLocalSaves().