Terraria Decompiled: Terraria.IO.WorldFileData.SetWorldSize
SetWorldSize()
void Terraria.IO.WorldFileData.SetWorldSize (int x, int y) inline
Definition at line 346 of file WorldFileData.cs.
        {
            this.WorldSizeX = x;
            this.WorldSizeY = y;
            if (x == 4200)
            {
                this._worldSizeName = Language.GetText("UI.WorldSizeSmall");
                return;
            }
            if (x == 6400)
            {
                this._worldSizeName = Language.GetText("UI.WorldSizeMedium");
                return;
            }
            if (x != 8400)
            {
                this._worldSizeName = Language.GetText("UI.WorldSizeUnknown");
                return;
            }
            this._worldSizeName = Language.GetText("UI.WorldSizeLarge");
        }
References Terraria.Localization.Language.GetText().
Referenced by Terraria.IO.WorldFileData.FromInvalidWorld(), and Terraria.IO.WorldFile.GetAllMetadata().