Terraria Decompiled: Terraria.IO.WorldFileData.SetSeedToRandomWithCurrentEvents
SetSeedToRandomWithCurrentEvents()
void Terraria.IO.WorldFileData.SetSeedToRandomWithCurrentEvents () inline
Definition at line 429 of file WorldFileData.cs.
        {
            this.SetSeedToRandom();
            if (Main.isHalloweenDateNow())
            {
                WorldGen.SecretSeed.Enable(WorldGen.SecretSeed.halloweenGen, false);
                this.SetSeed("pumpkinseason|" + this.SeedText);
            }
        }
References Terraria.WorldGen.SecretSeed.Enable(), Terraria.WorldGen.SecretSeed.halloweenGen, Terraria.Main.isHalloweenDateNow(), Terraria.IO.WorldFileData.SeedText, Terraria.IO.WorldFileData.SetSeed(), and Terraria.IO.WorldFileData.SetSeedToRandom().
Referenced by Terraria.Main.DedServ(), and Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld().