Terraria Decompiled: Terraria.IO.WorldFileData.TranslateSeed
TranslateSeed()
static int Terraria.IO.WorldFileData.TranslateSeed (string seedText) inline static
Definition at line 408 of file WorldFileData.cs.
        {
            int num;
            if (!int.TryParse(seedText, out num))
            {
                return Crc32.Calculate(seedText);
            }
            if (num != -2147483648)
            {
                return Math.Abs(num);
            }
            return int.MaxValue;
        }
References System.Math.Abs(), and ReLogic.Utilities.Crc32.Calculate().
Referenced by Terraria.WorldBuilding.WorldGenerationOptions.GetOptionFromSeedText(), and Terraria.IO.WorldFileData.SetSeed().