Terraria Decompiled: Terraria.IO.WorldFileData.MoveToCloud
MoveToCloud()
override void Terraria.IO.WorldFileData.MoveToCloud () inline
Definition at line 440 of file WorldFileData.cs.
        {
            if (base.IsCloudSave)
            {
                return;
            }
            string worldPathFromName = Main.GetWorldPathFromName(this.Name, true);
            if (FileUtilities.MoveToCloud(base.Path, worldPathFromName))
            {
                Main.LocalFavoriteData.ClearEntry(this);
                this._isCloudSave = true;
                this._path = worldPathFromName;
                Main.CloudFavoritesData.SaveFavorite(this);
            }
        }
References Terraria.Main.CloudFavoritesData, Terraria.Main.GetWorldPathFromName(), Terraria.Main.LocalFavoriteData, Terraria.Utilities.FileUtilities.MoveToCloud(), and Terraria.IO.FileData.Name.
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick().