Terraria Decompiled: ReLogic.Peripherals.RGB.ChromaShader.BindProcessors
BindProcessors()
void ReLogic.Peripherals.RGB.ChromaShader.BindProcessors () inline private
Definition at line 45 of file ChromaShader.cs.
        {
            foreach (MethodInfo methodInfo in base.GetType().GetMethods(54))
            {
                RgbProcessorAttribute rgbProcessorAttribute = (RgbProcessorAttribute)Attribute.GetCustomAttribute(methodInfo, typeof(RgbProcessorAttribute));
                if (rgbProcessorAttribute != null)
                {
                    ChromaShader.Processor processor = (ChromaShader.Processor)Delegate.CreateDelegate(typeof(ChromaShader.Processor), this, methodInfo, false);
                    if (processor != null)
                    {
                        this.BindProcessor(processor, rgbProcessorAttribute);
                    }
                }
            }
        }
References ReLogic.Peripherals.RGB.ChromaShader.BindProcessor(), System.Delegate.CreateDelegate(), System.Attribute.GetCustomAttribute(), System.Type.GetMethods(), System.Reflection.MethodInfo.GetType(), and ReLogic.Peripherals.RGB.ChromaShader.Processor().
Referenced by ReLogic.Peripherals.RGB.ChromaShader.ChromaShader().