Terraria Decompiled: Terraria.Netplay.InitializeServer
InitializeServer()
static void Terraria.Netplay.InitializeServer () inline static private
Definition at line 236 of file Netplay.cs.
        {
            Netplay.Connection.ResetSpecialFlags();
            Netplay.ResetNetDiag();
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
            }
            Main.myPlayer = 255;
            Netplay.ServerIP = IPAddress.Any;
            Main.menuMode = 14;
            Main.statusText = Lang.menu[8].Value;
            Main.netMode = 2;
            Netplay.Disconnect = false;
            for (int i = 0; i < 256; i++)
            {
                Netplay.Clients[i] = new RemoteClient();
                Netplay.Clients[i].Reset();
                Netplay.Clients[i].Id = i;
                Netplay.Clients[i].ReadBuffer = new byte[1024];
            }
            Netplay.TcpListener = new TcpSocket();
            if (!Netplay.Disconnect)
            {
                if (!Netplay.StartListening())
                {
                    Main.statusText = Language.GetTextValue("Error.TriedToRunServerTwice");
                    Netplay.SaveOnServerExit = false;
                    Netplay.Disconnect = true;
                }
                Main.statusText = Language.GetTextValue("CLI.ServerStarted");
            }
            if (!Netplay.UseUPNP)
            {
                return;
            }
            try
            {
                Netplay.OpenPort(Netplay.ListenPort);
            }
            catch (Exception)
            {
            }
        }
References Terraria.Netplay.Clients, Terraria.Netplay.Connection, Terraria.Netplay.Disconnect, Terraria.Localization.Language.GetTextValue(), Terraria.RemoteClient.Id, Terraria.Netplay.ListenPort, Terraria.Lang.menu, System.DateTime.Now, Terraria.Netplay.OpenPort(), Terraria.Main.rand, Terraria.RemoteClient.ReadBuffer, Terraria.RemoteClient.Reset(), Terraria.Netplay.ResetNetDiag(), Terraria.RemoteServer.ResetSpecialFlags(), Terraria.Netplay.StartListening(), System.DateTime.Ticks, Terraria.Netplay.UseUPNP, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Netplay.StartServer().