Terraria Decompiled: Terraria.Netplay.AddBan
AddBan()
static void Terraria.Netplay.AddBan (int plr) inline static
Definition at line 96 of file Netplay.cs.
        {
            RemoteAddress remoteAddress = Netplay.Clients[plr].Socket.GetRemoteAddress();
            using (StreamWriter streamWriter = new StreamWriter(Netplay.BanFilePath, true))
            {
                streamWriter.WriteLine("//" + Main.player[plr].name);
                streamWriter.WriteLine(remoteAddress.GetIdentifier());
            }
        }
References Terraria.Netplay.BanFilePath, Terraria.Netplay.Clients, Terraria.Net.RemoteAddress.GetIdentifier(), Terraria.Net.Sockets.ISocket.GetRemoteAddress(), Terraria.Player.name, Terraria.Main.player, Terraria.RemoteClient.Socket, and System.IO.StreamWriter.WriteLine().
Referenced by Terraria.Main.startDedInputCallBack().