Terraria Decompiled: Terraria.Netplay.SetRemoteIPAsync
SetRemoteIPAsync()
static void Terraria.Netplay.SetRemoteIPAsync (string remoteAddress, Action successCallBack) inline static
Definition at line 701 of file Netplay.cs.
        {
            try
            {
                IPAddress ipaddress;
                if (IPAddress.TryParse(remoteAddress, out ipaddress))
                {
                    Netplay.ServerIP = ipaddress;
                    Netplay.ServerIPText = ipaddress.ToString();
                    successCallBack();
                }
                else
                {
                    Netplay.InvalidateAllOngoingIPSetAttempts();
                    Dns.BeginGetHostAddresses(remoteAddress, new AsyncCallback(Netplay.SetRemoteIPAsyncCallback), new Netplay.SetRemoteIPRequestInfo
                    {
                        RequestId = Netplay._currentRequestId,
                        SuccessCallback = successCallBack,
                        RemoteAddress = remoteAddress
                    });
                }
            }
            catch (Exception)
            {
            }
        }
References System.AsyncCallback(), Terraria.Netplay.InvalidateAllOngoingIPSetAttempts(), and Terraria.Netplay.SetRemoteIPAsyncCallback().
Referenced by Terraria.Main.DrawMenu(), and Terraria.Main.OnSubmitServerPort().