Terraria Decompiled: Terraria.Netplay.InnerClientLoop
InnerClientLoop()
static void Terraria.Netplay.InnerClientLoop () inline static private
Definition at line 476 of file Netplay.cs.
        {
            try
            {
                NetMessage.buffer[256].Reset();
                int num = -1;
                while (!Netplay.Disconnect)
                {
                    if (Netplay.Connection.IsActive && Netplay.Connection.ServerWantsToRunCheckBytesInClientLoopThread)
                    {
                        NetMessage.CheckBytes(256);
                    }
                    if (Netplay.Connection.IsConnected())
                    {
                        Netplay.Connection.IsActive = true;
                        if (Netplay.Connection.State == 0)
{
                            Main.statusText = Language.GetTextValue("Net.FoundServer");
                            Netplay.Connection.State = 1;
                            NetMessage.SendData(1, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                            Ping.Reset();
                        }
                        if (Netplay.Connection.State == 2 && num != Netplay.Connection.State)
{
                            Main.statusText = Language.GetTextValue("Net.SendingPlayerData");
                        }
                        if (Netplay.Connection.State == 3 && num != Netplay.Connection.State)
{
                            Main.statusText = Language.GetTextValue("Net.RequestingWorldInformation");
                        }
                        if (Netplay.Connection.State == 4)
{
                            WorldGen.worldCleared = false;
                            Netplay.Connection.State = 5;
                            if (Main.cloudBGActive >= 1f)
{
                                Main.cloudBGAlpha = 1f;
                            }
                            else
{
                                Main.cloudBGAlpha = 0f;
                            }
                            Main.windSpeedCurrent = Main.windSpeedTarget;
                            Cloud.resetClouds();
                            Main.cloudAlpha = Main.maxRaining;
                            Main.ToggleGameplayUpdates(false);
                            WorldGen.clearWorld();
                            if (Main.mapEnabled)
{
                                Main.Map.Load();
                            }
                        }
                        if (Netplay.Connection.State == 5 && Main.loadMapLock)
{
                            float num2 = (float)Main.loadMapLastX / (float)Main.maxTilesX;
                            Main.statusText = string.Concat(new object[]
{
                                Lang.gen[68].Value,
                                " ",
                                (int)(num2 * 100f + 1f),
                                "%"
                            });
                        }
                        else if (Netplay.Connection.State == 5 && WorldGen.worldCleared)
{
                            Netplay.Connection.State = 6;
                            Main.player[Main.myPlayer].FindSpawn();
                            NetMessage.SendData(8, -1, -1, null, Main.player[Main.myPlayer].SpawnX, (float)Main.player[Main.myPlayer].SpawnY, (float)Main.player[Main.myPlayer].team, 0f, 0, 0, 0);
                        }
                        if (Netplay.Connection.State == 6 && num != Netplay.Connection.State)
{
                            Main.statusText = Language.GetTextValue("Net.RequestingTileData");
                        }
                        if (!Netplay.Connection.IsReading && !Netplay.Disconnect && Netplay.Connection.Socket.IsDataAvailable() && !Netplay.Connection.ReadBufferFull)
{
                            Netplay.Connection.IsReading = true;
                            Netplay.Connection.Socket.AsyncReceive(Netplay.Connection.ReadBuffer, 0, Netplay.Connection.ReadBuffer.Length, new SocketReceiveCallback(Netplay.Connection.ClientReadCallBack), null);
                        }
                        if (Netplay.Connection.StatusMax > 0 && Netplay.Connection.StatusText != "")
{
                            if (Netplay.Connection.StatusCount >= Netplay.Connection.StatusMax)
{
                                Main.statusText = Language.GetTextValue("Net.StatusComplete", Netplay.Connection.StatusText);
                                Netplay.Connection.StatusText = "";
                                Netplay.Connection.StatusMax = 0;
                                Netplay.Connection.StatusCount = 0;
                            }
                            else
{
                                int num3;
                                int num4;
                                Main.ActiveNetDiagnosticsUI.GetLastSentRecvBytes(out num3, out num4);
                                Main.statusText = string.Format("{0}: {1}% ({2:0.0} kB/s)", Netplay.Connection.StatusText, Netplay.Connection.StatusCount * 100 / Netplay.Connection.StatusMax, (double)num4 / 1024.0);
                            }
                        }
                        Thread.Sleep(1);
                    }
                    num = Netplay.Connection.State;
                }
                try
                {
                    Netplay.Connection.IsActive = false;
                    Netplay.Connection.Socket.Close();
                }
                catch
                {
                }
                if (!Main.gameMenu)
                {
                    Main.gameMenu = true;
                    Main.SwitchNetMode(0);
                    MapHelper.noStatusText = true;
                    Player.SavePlayer(Main.ActivePlayerFileData, false);
                    Player.ClearPlayerTempInfo();
                    Main.ActivePlayerFileData.StopPlayTimer();
                    SoundEngine.StopTrackedSounds();
                    MapHelper.noStatusText = false;
                    Main.menuMode = 14;
                }
                NetMessage.buffer[256].Reset();
                if (Main.menuMode == 15 && Main.statusText == Language.GetTextValue("Net.LostConnection"))
                {
                    Main.menuMode = 14;
                }
                if (Netplay.Connection.StatusText != "" && Netplay.Connection.StatusText != null)
                {
                    Main.statusText = Language.GetTextValue("Net.LostConnection");
                }
                Netplay.Connection.StatusCount = 0;
                Netplay.Connection.StatusMax = 0;
                Netplay.Connection.StatusText = "";
                Main.SwitchNetMode(0);
            }
            catch (Exception ex)
            {
                try
                {
                    using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", true))
                    {
                        streamWriter.WriteLine(DateTime.Now);
                        streamWriter.WriteLine(ex);
                        streamWriter.WriteLine("");
                    }
                }
                catch
                {
                }
                Netplay.Disconnect = true;
            }
            if (Netplay.OnDisconnect != null)
            {
                Netplay.OnDisconnect();
            }
        }
References Terraria.Main.ActiveNetDiagnosticsUI, Terraria.Main.ActivePlayerFileData, Terraria.Net.Sockets.ISocket.AsyncReceive(), Terraria.NetMessage.buffer, Terraria.NetMessage.CheckBytes(), Terraria.Player.ClearPlayerTempInfo(), Terraria.WorldGen.clearWorld(), Terraria.RemoteServer.ClientReadCallBack(), Terraria.Net.Sockets.ISocket.Close(), Terraria.Main.cloudBGActive, Terraria.Netplay.Connection, Terraria.Netplay.Disconnect, Terraria.Player.FindSpawn(), Terraria.Main.gameMenu, Terraria.Lang.gen, Terraria.Localization.Language.GetTextValue(), int, Terraria.RemoteServer.IsActive, Terraria.RemoteServer.IsConnected(), Terraria.Net.Sockets.ISocket.IsDataAvailable(), Terraria.RemoteServer.IsReading, Terraria.Map.WorldMap.Load(), Terraria.Main.loadMapLastX, Terraria.Main.loadMapLock, Terraria.Main.Map, Terraria.Main.mapEnabled, Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.menuMode, Terraria.Main.myPlayer, System.DateTime.Now, Terraria.Netplay.OnDisconnect, Terraria.Main.player, Terraria.RemoteServer.ReadBuffer, Terraria.RemoteServer.ReadBufferFull, Terraria.MessageBuffer.Reset(), Terraria.Net.Ping.Reset(), Terraria.Cloud.resetClouds(), Terraria.Player.SavePlayer(), Terraria.NetMessage.SendData(), Terraria.RemoteServer.ServerWantsToRunCheckBytesInClientLoopThread, System.Threading.Thread.Sleep(), Terraria.RemoteServer.Socket, Terraria.Net.Sockets.SocketReceiveCallback(), Terraria.Player.SpawnX, Terraria.Player.SpawnY, Terraria.RemoteServer.State, Terraria.RemoteServer.StatusCount, Terraria.RemoteServer.StatusMax, Terraria.Main.statusText, Terraria.RemoteServer.StatusText, Terraria.Audio.SoundEngine.StopTrackedSounds(), Terraria.Main.SwitchNetMode(), Terraria.Player.team, Terraria.Main.ToggleGameplayUpdates(), Terraria.Localization.LocalizedText.Value, Terraria.Main.windSpeedTarget, Terraria.WorldGen.worldCleared, and System.IO.StreamWriter.WriteLine().
Referenced by Terraria.Netplay.SocialClientLoop(), and Terraria.Netplay.TcpClientLoop().