Terraria Decompiled: Terraria.Netplay.BroadcastThread
BroadcastThread()
static void Terraria.Netplay.BroadcastThread () inline static private
Definition at line 830 of file Netplay.cs.
        {
            Netplay.BroadcastClient = new UdpClient();
            new IPEndPoint(IPAddress.Any, 0);
            Netplay.BroadcastClient.EnableBroadcast = true;
            new DateTime(0L);
            int num = 0;
            byte[] array;
            using (MemoryStream memoryStream = new MemoryStream())
            {
                using (BinaryWriter binaryWriter = new BinaryWriter(memoryStream))
                {
                    int num2 = 1010;
                    binaryWriter.Write(num2);
                    binaryWriter.Write(Netplay.ListenPort);
                    binaryWriter.Write(Main.worldName);
                    string text = Dns.GetHostName();
                    if (text == "localhost")
                    {
                        text = Environment.MachineName;
                    }
                    binaryWriter.Write(text);
                    binaryWriter.Write((ushort)Main.maxTilesX);
                    binaryWriter.Write(Main.ActiveWorldFileData.HasCrimson);
                    binaryWriter.Write(Main.ActiveWorldFileData.GameMode);
                    binaryWriter.Write((byte)Main.maxNetPlayers);
                    num = (int)memoryStream.Position;
                    binaryWriter.Write(0);
                    binaryWriter.Write(Main.ActiveWorldFileData.IsHardMode);
                    binaryWriter.Flush();
                    array = memoryStream.ToArray();
                }
            }
            for (;;)
            {
                int num3 = 0;
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active)
                    {
                        num3++;
                    }
                }
                array[num] = (byte)num3;
                try
                {
                    Netplay.BroadcastClient.Send(array, array.Length, new IPEndPoint(IPAddress.Broadcast, 8888));
                }
                catch
                {
                }
                Thread.Sleep(1000);
            }
        }
References Terraria.Player.active, Terraria.Main.ActiveWorldFileData, System.array, Terraria.Netplay.BroadcastClient, System.DateTime, System.IO.BinaryWriter.Flush(), int, System.L, Terraria.Netplay.ListenPort, Terraria.Main.maxNetPlayers, Terraria.Main.maxTilesX, Terraria.Main.player, System.IO.MemoryStream.Position, System.Threading.Thread.Sleep(), System.text, System.IO.MemoryStream.ToArray(), Terraria.Main.worldName, and System.IO.BinaryWriter.Write().
Referenced by Terraria.Netplay.StartBroadCasting().