Terraria Decompiled: Terraria.Netplay.AddCurrentServerToRecentList
AddCurrentServerToRecentList()
static void Terraria.Netplay.AddCurrentServerToRecentList () inline static
Definition at line 375 of file Netplay.cs.
        {
            if (Netplay.Connection.Socket.GetRemoteAddress().Type != AddressType.Tcp)
            {
                return;
            }
            for (int i = 0; i < Main.maxMP; i++)
            {
                if (Main.recentIP[i].ToLower() == Netplay.ServerIPText.ToLower() && Main.recentPort[i] == Netplay.ListenPort)
                {
                    for (int j = i; j < Main.maxMP - 1; j++)
                    {
                        Main.recentIP[j] = Main.recentIP[j + 1];
                        Main.recentPort[j] = Main.recentPort[j + 1];
                        Main.recentWorld[j] = Main.recentWorld[j + 1];
                    }
                }
            }
            for (int k = Main.maxMP - 1; k > 0; k--)
            {
                Main.recentIP[k] = Main.recentIP[k - 1];
                Main.recentPort[k] = Main.recentPort[k - 1];
                Main.recentWorld[k] = Main.recentWorld[k - 1];
            }
            Main.recentIP[0] = Netplay.ServerIPText;
            Main.recentPort[0] = Netplay.ListenPort;
            Main.recentWorld[0] = Main.worldName;
            Main.SaveRecent();
        }
References Terraria.Netplay.Connection, Terraria.Net.Sockets.ISocket.GetRemoteAddress(), Terraria.Netplay.ListenPort, Terraria.Main.maxMP, Terraria.Main.recentIP, Terraria.Main.recentPort, Terraria.Main.recentWorld, Terraria.Main.SaveRecent(), Terraria.Netplay.ServerIPText, Terraria.RemoteServer.Socket, Terraria.Net.RemoteAddress.Type, and Terraria.Main.worldName.
Referenced by Terraria.Player.Spawn().