Terraria Decompiled: System.Globalization.GlobalizationMode.Invariant
Invariant
bool System.Globalization.GlobalizationMode.Invariant = GlobalizationMode.GetGlobalizationInvariantMode() static get package
Definition at line 11 of file GlobalizationMode.cs.
        {
            [CompilerGenerated]
            get
            {
                return GlobalizationMode.<Invariant>k__BackingField;
            }
        } = GlobalizationMode.GetGlobalizationInvariantMode();
Referenced by System.Globalization.CalendarData.CalendarData(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.CompareOptionIgnoreCase(), System.Globalization.CompareInfo.CompareOptionNone(), System.Globalization.CultureInfo.ConstructCurrentCulture(), System.DateTimeParse.DoStrictParse(), System.SpanHelpers.EndsWithCultureHelper(), System.SpanHelpers.EndsWithCultureIgnoreCaseHelper(), System.DateTimeFormat.FormatCustomized(), System.Globalization.CompareInfo.GetHashCodeOfString(), System.DateTimeParse.GetJapaneseCalendarDefaultInstance(), System.Globalization.CalendarData.GetJapaneseEnglishEraNames(), System.Globalization.CalendarData.GetJapaneseEraNames(), System.Globalization.CompareInfo.GetSortKey(), System.Globalization.CompareInfo.GetSortKey(), System.DateTimeParse.GetTaiwanCalendarDefaultInstance(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.Globalization.CompareInfo.IndexOf(), System.SpanHelpers.IndexOfCultureHelper(), System.SpanHelpers.IndexOfCultureIgnoreCaseHelper(), System.Globalization.CompareInfo.IndexOfOrdinal(), System.SpanHelpers.IndexOfOrdinalHelper(), System.Globalization.CalendarData.InitializeAbbreviatedEraNames(), System.Globalization.CompareInfo.IsPrefix(), System.Globalization.CompareInfo.IsSortable(), System.Globalization.CompareInfo.IsSuffix(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOf(), System.Globalization.CompareInfo.LastIndexOfOrdinal(), System.DateTimeParse.Lex(), System.Globalization.NumberFormatInfo.NumberFormatInfo(), System.DateTimeParse.ProcessHebrewTerminalState(), System.SpanHelpers.StartsWithCultureHelper(), System.SpanHelpers.StartsWithCultureIgnoreCaseHelper(), System.MemoryExtensions.ToLower(), System.MemoryExtensions.ToLowerInvariant(), System.MemoryExtensions.ToUpper(), System.MemoryExtensions.ToUpperInvariant(), and System.DateTimeParse.TryParse().