Terraria Decompiled: System.Security.AccessControl.GenericAce.CreateFromSddlForm
CreateFromSddlForm()
static GenericAce System.Security.AccessControl.GenericAce.CreateFromSddlForm (string sddlForm, ref int pos) inline static package
Definition at line 248 of file GenericAce.cs.
        {
            if (sddlForm[pos] != '(')
            {
                throw new ArgumentException("Invalid SDDL string.", "sddlForm");
            }
            int num = sddlForm.IndexOf(')', pos);
            if (num < 0)
            {
                throw new ArgumentException("Invalid SDDL string.", "sddlForm");
            }
            int num2 = num - (pos + 1);
            string[] array = sddlForm.Substring(pos + 1, num2).ToUpperInvariant().Split(';', StringSplitOptions.None);
            if (array.Length != 6)
            {
                throw new ArgumentException("Invalid SDDL string.", "sddlForm");
            }
            ObjectAceFlags objectAceFlags = ObjectAceFlags.None;
            AceType aceType = GenericAce.ParseSddlAceType(array[0]);
            AceFlags aceFlags = GenericAce.ParseSddlAceFlags(array[1]);
            int num3 = GenericAce.ParseSddlAccessRights(array[2]);
            Guid empty = Guid.Empty;
            if (!string.IsNullOrEmpty(array[3]))
            {
                empty = new Guid(array[3]);
                objectAceFlags |= ObjectAceFlags.ObjectAceTypePresent;
            }
            Guid empty2 = Guid.Empty;
            if (!string.IsNullOrEmpty(array[4]))
            {
                empty2 = new Guid(array[4]);
                objectAceFlags |= ObjectAceFlags.InheritedObjectAceTypePresent;
            }
            SecurityIdentifier securityIdentifier = new SecurityIdentifier(array[5]);
            if (aceType == AceType.AccessAllowedCallback || aceType == AceType.AccessDeniedCallback)
            {
                throw new NotImplementedException("Conditional ACEs not supported");
            }
            pos = num + 1;
            if (GenericAce.IsObjectType(aceType))
            {
                return new ObjectAce(aceType, aceFlags, num3, securityIdentifier, objectAceFlags, empty, empty2, null);
            }
            if (objectAceFlags != ObjectAceFlags.None)
            {
                throw new ArgumentException("Invalid SDDL string.", "sddlForm");
            }
            return new CommonAce(aceType, aceFlags, num3, securityIdentifier, null);
        }
References System.array, System.Guid.Empty, System.Security.AccessControl.GenericAce.IsObjectType(), System.Security.AccessControl.GenericAce.ParseSddlAccessRights(), System.Security.AccessControl.GenericAce.ParseSddlAceFlags(), and System.Security.AccessControl.GenericAce.ParseSddlAceType().
Referenced by System.Security.AccessControl.RawAcl.ParseSddlForm().