Terraria Decompiled: Terraria.GameContent.CraftingEffects.CreateBubbleParticles
CreateBubbleParticles()
static void Terraria.GameContent.CraftingEffects.CreateBubbleParticles (int n) inline static private
Definition at line 104 of file CraftingEffects.cs.
        {
            for (float num = 0f; num < 2f; num += 0.083333336f)
            {
                float num2 = 15f;
                float num3 = 6.2831855f * (num + Main.rand.NextFloat());
                FadingParticle fadingParticle = ParticleOrchestrator._poolFading.RequestParticle();
                fadingParticle.SetBasicInfo(TextureAssets.Bubble, null, num3.ToRotationVector2() * (2f + 3f * Main.rand.NextFloat()), Main.MouseScreen + num3.ToRotationVector2() * (10f + 40f * Main.rand.NextFloat()));
                fadingParticle.SetTypeInfo(num2, true);
                fadingParticle.AccelerationPerFrame = fadingParticle.Velocity * (-1f / num2);
                fadingParticle.LocalPosition -= fadingParticle.Velocity * 4f;
                fadingParticle.FadeInNormalizedTime = 0.2f;
                fadingParticle.FadeOutNormalizedTime = 0.7f;
                fadingParticle.Scale = Vector2.One;
                Main.ParticleSystem_OverInventory.Add(fadingParticle);
            }
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator._poolFading, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.GameContent.TextureAssets.Bubble, Terraria.Main.MouseScreen, Microsoft.Xna.Framework.Vector2.One, Terraria.Main.ParticleSystem_OverInventory, Terraria.Main.rand, Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), and Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo().