Terraria Decompiled: Terraria.Social.Steam.NetClientSocialModule.SendAuthTicket
SendAuthTicket()
void Terraria.Social.Steam.NetClientSocialModule.SendAuthTicket (CSteamID address) inline private
Definition at line 219 of file NetClientSocialModule.cs.
        {
            WeGameHelper.WriteDebugString(" SendAuthTicket", new object[0]);
            if (this._authTicket == HAuthTicket.Invalid)
            {
                SteamNetworkingIdentity steamNetworkingIdentity = default(SteamNetworkingIdentity);
                steamNetworkingIdentity.SetSteamID(address);
                this._authTicket = SteamUser.GetAuthSessionTicket(this._authData, this._authData.Length, ref this._authDataLength, ref steamNetworkingIdentity);
            }
            int num = (int)(this._authDataLength + 3U);
            byte[] array = new byte[num];
            array[0] = (byte)(num & 255);
            array[1] = (byte)((num >> 8) & 255);
            array[2] = 93;
            int num2 = 0;
            while ((long)num2 < (long)((ulong)this._authDataLength))
            {
                array[num2 + 3] = this._authData[num2];
                num2++;
            }
            SteamNetworking.SendP2PPacket(address, array, (uint)num, 2, 1);
        }
References Terraria.Social.Steam.NetClientSocialModule._authData, Terraria.Social.Steam.NetClientSocialModule._authDataLength, Terraria.Social.Steam.NetClientSocialModule._authTicket, System.array, Steamworks.SteamUser.GetAuthSessionTicket(), int, Steamworks.HAuthTicket.Invalid, long, Steamworks.SteamNetworking.SendP2PPacket(), Steamworks.SteamNetworkingIdentity.SetSteamID(), System.U, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.Steam.NetClientSocialModule.OnLobbyEntered().