Terraria Decompiled: Terraria.Social.Steam.NetClientSocialModule.OnP2PSessionRequest
OnP2PSessionRequest()
void Terraria.Social.Steam.NetClientSocialModule.OnP2PSessionRequest (P2PSessionRequest_t result) inline private
Definition at line 273 of file NetClientSocialModule.cs.
        {
            WeGameHelper.WriteDebugString(" OnP2PSessionRequest", new object[0]);
            CSteamID steamIDRemote = result.m_steamIDRemote;
            if (this._connectionStateMap.ContainsKey(steamIDRemote) && this._connectionStateMap[steamIDRemote] != NetSocialModule.ConnectionState.Inactive)
            {
                SteamNetworking.AcceptP2PSessionWithUser(steamIDRemote);
            }
        }
References Terraria.Social.Steam.NetSocialModule._connectionStateMap, Steamworks.SteamNetworking.AcceptP2PSessionWithUser(), Steamworks.P2PSessionRequest_t.m_steamIDRemote, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.Steam.NetClientSocialModule.Initialize().