Terraria Decompiled: System.Security.Permissions.PrincipalPermission.IsSubsetOf
IsSubsetOf()
bool System.Security.Permissions.PrincipalPermission.IsSubsetOf (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 171 of file PrincipalPermission.cs.
        {
            PrincipalPermission principalPermission = this.Cast(target);
            if (principalPermission == null)
            {
                return this.IsEmpty();
            }
            if (this.IsUnrestricted())
            {
                return principalPermission.IsUnrestricted();
            }
            if (principalPermission.IsUnrestricted())
            {
                return true;
            }
            foreach (object obj in this.principals)
            {
                PrincipalPermission.PrincipalInfo principalInfo = (PrincipalPermission.PrincipalInfo)obj;
                bool flag = false;
                foreach (object obj2 in principalPermission.principals)
                {
                    PrincipalPermission.PrincipalInfo principalInfo2 = (PrincipalPermission.PrincipalInfo)obj2;
                    if ((principalInfo.Name == principalInfo2.Name || principalInfo2.Name == null) && (principalInfo.Role == principalInfo2.Role || principalInfo2.Role == null) && principalInfo.IsAuthenticated == principalInfo2.IsAuthenticated)
                    {
                        flag = true;
                    }
                }
                if (!flag)
                {
                    return false;
                }
            }
            return true;
        }
References System.Security.Permissions.PrincipalPermission.Cast(), System.Security.Permissions.PrincipalPermission.PrincipalInfo.IsAuthenticated, System.Security.Permissions.PrincipalPermission.IsEmpty(), System.Security.Permissions.PrincipalPermission.IsUnrestricted(), System.Security.Permissions.PrincipalPermission.PrincipalInfo.Name, System.obj, and System.Security.Permissions.PrincipalPermission.principals.