Terraria Decompiled: System.Security.Permissions.PrincipalPermission.FromXml
FromXml()
void System.Security.Permissions.PrincipalPermission.FromXml (SecurityElement elem) inline
Implements System.Security.ISecurityEncodable.
Definition at line 79 of file PrincipalPermission.cs.
        {
            this.CheckSecurityElement(elem, "elem", 1, 1);
            this.principals.Clear();
            if (elem.Children != null)
            {
                foreach (object obj in elem.Children)
                {
                    SecurityElement securityElement = (SecurityElement)obj;
                    if (securityElement.Tag != "Identity")
                    {
                        throw new ArgumentException("not IPermission/Identity");
                    }
                    string text = securityElement.Attribute("ID");
                    string text2 = securityElement.Attribute("Role");
                    string text3 = securityElement.Attribute("Authenticated");
                    bool flag = false;
                    if (text3 != null)
                    {
                        try
{
                            flag = bool.Parse(text3);
                        }
                        catch
{
                        }
                    }
                    PrincipalPermission.PrincipalInfo principalInfo = new PrincipalPermission.PrincipalInfo(text, text2, flag);
                    this.principals.Add(principalInfo);
                }
            }
        }
References System.Collections.ArrayList.Add(), System.Security.SecurityElement.Attribute(), System.Security.Permissions.PrincipalPermission.CheckSecurityElement(), System.Security.SecurityElement.Children, System.Collections.ArrayList.Clear(), System.obj, System.Security.Permissions.PrincipalPermission.principals, System.Security.SecurityElement.Tag, and System.text.