Terraria Decompiled: System.Security.Permissions.PrincipalPermission.Intersect
Intersect()
IPermission System.Security.Permissions.PrincipalPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 113 of file PrincipalPermission.cs.
        {
            PrincipalPermission principalPermission = this.Cast(target);
            if (principalPermission == null)
            {
                return null;
            }
            if (this.IsUnrestricted())
            {
                return principalPermission.Copy();
            }
            if (principalPermission.IsUnrestricted())
            {
                return this.Copy();
            }
            PrincipalPermission principalPermission2 = new PrincipalPermission(PermissionState.None);
            foreach (object obj in this.principals)
            {
                PrincipalPermission.PrincipalInfo principalInfo = (PrincipalPermission.PrincipalInfo)obj;
                foreach (object obj2 in principalPermission.principals)
                {
                    PrincipalPermission.PrincipalInfo principalInfo2 = (PrincipalPermission.PrincipalInfo)obj2;
                    if (principalInfo.IsAuthenticated == principalInfo2.IsAuthenticated)
                    {
                        string text = null;
                        if (principalInfo.Name == principalInfo2.Name || principalInfo2.Name == null)
{
                            text = principalInfo.Name;
                        }
                        else if (principalInfo.Name == null)
{
                            text = principalInfo2.Name;
                        }
                        string text2 = null;
                        if (principalInfo.Role == principalInfo2.Role || principalInfo2.Role == null)
{
                            text2 = principalInfo.Role;
                        }
                        else if (principalInfo.Role == null)
{
                            text2 = principalInfo2.Role;
                        }
                        if (text != null || text2 != null)
{
                            PrincipalPermission.PrincipalInfo principalInfo3 = new PrincipalPermission.PrincipalInfo(text, text2, principalInfo.IsAuthenticated);
                            principalPermission2.principals.Add(principalInfo3);
                        }
                    }
                }
            }
            if (principalPermission2.principals.Count <= 0)
            {
                return null;
            }
            return principalPermission2;
        }
References System.Security.Permissions.PrincipalPermission.Cast(), System.Security.Permissions.PrincipalPermission.Copy(), System.Security.Permissions.PrincipalPermission.PrincipalInfo.IsAuthenticated, System.Security.Permissions.PrincipalPermission.IsUnrestricted(), System.Security.Permissions.PrincipalPermission.PrincipalInfo.Name, System.obj, System.Security.Permissions.PrincipalPermission.PrincipalPermission(), System.Security.Permissions.PrincipalPermission.principals, System.Security.Permissions.PrincipalPermission.PrincipalInfo.Role, and System.text.