Terraria Decompiled: System.Security.Permissions.PrincipalPermission.PrincipalPermission
PrincipalPermission() [1/4]
System.Security.Permissions.PrincipalPermission.PrincipalPermission (PermissionState state) inline
Definition at line 15 of file PrincipalPermission.cs.
        {
            this.principals = new ArrayList();
            if (CodeAccessPermission.CheckPermissionState(state, true) == PermissionState.Unrestricted)
            {
                PrincipalPermission.PrincipalInfo principalInfo = new PrincipalPermission.PrincipalInfo(null, null, true);
                this.principals.Add(principalInfo);
            }
        }
References System.Collections.ArrayList.Add(), System.Security.CodeAccessPermission.CheckPermissionState(), System.Security.Permissions.PrincipalPermission.principals, and System.state.
Referenced by System.Security.Permissions.PrincipalPermission.Cast(), System.Security.Permissions.PrincipalPermission.Copy(), System.Security.Permissions.PrincipalPermission.Equals(), System.Security.Permissions.PrincipalPermission.Intersect(), and System.Security.Permissions.PrincipalPermission.Union().