Terraria Decompiled: System.Security.Permissions.PrincipalPermission.Union
Union()
IPermission System.Security.Permissions.PrincipalPermission.Union (IPermission other) inline
Implements System.Security.IPermission.
Definition at line 255 of file PrincipalPermission.cs.
        {
            PrincipalPermission principalPermission = this.Cast(other);
            if (principalPermission == null)
            {
                return this.Copy();
            }
            if (this.IsUnrestricted() || principalPermission.IsUnrestricted())
            {
                return new PrincipalPermission(PermissionState.Unrestricted);
            }
            PrincipalPermission principalPermission2 = new PrincipalPermission(this.principals);
            foreach (object obj in principalPermission.principals)
            {
                PrincipalPermission.PrincipalInfo principalInfo = (PrincipalPermission.PrincipalInfo)obj;
                principalPermission2.principals.Add(principalInfo);
            }
            return principalPermission2;
        }
References System.Security.Permissions.PrincipalPermission.Cast(), System.Security.Permissions.PrincipalPermission.Copy(), System.Security.Permissions.PrincipalPermission.IsUnrestricted(), System.obj, System.Security.Permissions.PrincipalPermission.PrincipalPermission(), and System.Security.Permissions.PrincipalPermission.principals.