Terraria Decompiled: System.Security.Permissions.PrincipalPermission.ToXml
ToXml()
SecurityElement System.Security.Permissions.PrincipalPermission.ToXml () inline
Implements System.Security.ISecurityEncodable.
Definition at line 227 of file PrincipalPermission.cs.
        {
            SecurityElement securityElement = new SecurityElement("Permission");
            Type type = base.GetType();
            securityElement.AddAttribute("class", type.FullName + ", " + type.Assembly.ToString().Replace('"', '\''));
            securityElement.AddAttribute("version", 1.ToString());
            foreach (object obj in this.principals)
            {
                PrincipalPermission.PrincipalInfo principalInfo = (PrincipalPermission.PrincipalInfo)obj;
                SecurityElement securityElement2 = new SecurityElement("Identity");
                if (principalInfo.Name != null)
                {
                    securityElement2.AddAttribute("ID", principalInfo.Name);
                }
                if (principalInfo.Role != null)
                {
                    securityElement2.AddAttribute("Role", principalInfo.Role);
                }
                if (principalInfo.IsAuthenticated)
                {
                    securityElement2.AddAttribute("Authenticated", "true");
                }
                securityElement.AddChild(securityElement2);
            }
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Type.Assembly, System.Type.FullName, System.Type.GetType(), System.Security.Permissions.PrincipalPermission.PrincipalInfo.IsAuthenticated, System.Security.Permissions.PrincipalPermission.PrincipalInfo.Name, System.obj, System.Security.Permissions.PrincipalPermission.principals, System.Security.Permissions.PrincipalPermission.PrincipalInfo.Role, and System.Security.Permissions.PrincipalPermission.ToString().
Referenced by System.Security.Permissions.PrincipalPermission.ToString().