Terraria Decompiled: Terraria.GameContent.AssetSourceController.UseResourcePacks
UseResourcePacks()
void Terraria.GameContent.AssetSourceController.UseResourcePacks (ResourcePackList resourcePacks) inline
Definition at line 86 of file AssetSourceController.cs.
        {
            if (this.OnResourcePackChange != null)
            {
                this.OnResourcePackChange(resourcePacks);
            }
            this.ActiveResourcePackList = resourcePacks;
            List<IContentSource> list = new List<IContentSource>(from pack in resourcePacks.EnabledPacks
                orderby pack.SortingOrder
                select pack.GetContentSource());
            list.AddRange(this._staticSources);
            foreach (IContentSource contentSource in list)
            {
                contentSource.ClearRejections();
            }
            List<IContentSource> list2 = new List<IContentSource>();
            for (int i = list.Count - 1; i >= 0; i--)
            {
                list2.Add(list[i]);
            }
            this._assetRepository.SetSources(list, 1);
            LanguageManager.Instance.UseSources(list2);
            Main.audioSystem.UseSources(list2);
            SoundEngine.Reload();
            Main.changeTheTitle = true;
        }
References Terraria.GameContent.AssetSourceController._assetRepository, Terraria.GameContent.AssetSourceController._staticSources, System.Collections.Generic.List< T >.Add(), Terraria.Main.audioSystem, ReLogic.Content.Sources.IContentSource.ClearRejections(), Terraria.IO.ResourcePackList.EnabledPacks, Terraria.Localization.LanguageManager.Instance, System.list, Terraria.GameContent.AssetSourceController.OnResourcePackChange, Terraria.Audio.SoundEngine.Reload(), ReLogic.Content.IAssetRepository.SetSources(), Terraria.Audio.IAudioSystem.UseSources(), and Terraria.Localization.LanguageManager.UseSources().
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.ApplyListChanges(), Terraria.Main.LoadContent(), and Terraria.GameContent.AssetSourceController.Refresh().