Terraria Decompiled: System.RuntimeTypeHandle.GetTypeByName
GetTypeByName()
static RuntimeType System.RuntimeTypeHandle.GetTypeByName (string typeName, bool throwOnError, bool ignoreCase, bool reflectionOnly, ref StackCrawlMark stackMark, bool loadTypeFromPartialName) inline static package
Definition at line 304 of file RuntimeTypeHandle.cs.
        {
            if (typeName == null)
            {
                throw new ArgumentNullException("typeName");
            }
            if (typeName == string.Empty)
            {
                if (throwOnError)
                {
                    throw new TypeLoadException("A null or zero length string does not represent a valid Type.");
                }
                return null;
            }
            else if (reflectionOnly)
            {
                int num = typeName.IndexOf(',');
                if (num < 0 || num == 0 || num == typeName.Length - 1)
                {
                    throw new ArgumentException("Assembly qualifed type name is required", "typeName");
                }
                string text = typeName.Substring(num + 1);
                Assembly assembly;
                try
                {
                    assembly = Assembly.ReflectionOnlyLoad(text);
                }
                catch
                {
                    if (throwOnError)
                    {
                        throw;
                    }
                    return null;
                }
                return (RuntimeType)assembly.GetType(typeName.Substring(0, num), throwOnError, ignoreCase);
            }
            else
            {
                RuntimeType runtimeType = RuntimeTypeHandle.internal_from_name(typeName, ref stackMark, null, throwOnError, ignoreCase, false);
                if (throwOnError && runtimeType == null)
                {
                    throw new TypeLoadException("Error loading '" + typeName + "'");
                }
                return runtimeType;
            }
        }
References System.Reflection.Assembly.GetType(), System.RuntimeTypeHandle.internal_from_name(), System.Reflection.Assembly.ReflectionOnlyLoad(), and System.text.
Referenced by System.RuntimeType.GetType().