Terraria Decompiled: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start< TStateMachine >
Start< TStateMachine >() [2/2]
void System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.Start< TStateMachine > (ref TStateMachine stateMachine) inline
Type Constraints
TStateMachine : IAsyncStateMachine
Definition at line 23 of file AsyncTaskMethodBuilder.cs.
                                                                                             : IAsyncStateMachine
        {
            if (stateMachine == null)
            {
                throw new ArgumentNullException("stateMachine");
            }
            ExecutionContextSwitcher executionContextSwitcher = default(ExecutionContextSwitcher);
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                ExecutionContext.EstablishCopyOnWriteScope(ref executionContextSwitcher);
                stateMachine.MoveNext();
            }
            finally
            {
                executionContextSwitcher.Undo();
            }
        }
References System.Threading.ExecutionContext.EstablishCopyOnWriteScope(), System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), and System.Threading.ExecutionContextSwitcher.Undo().