Terraria Decompiled: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.GetTaskForResult
GetTaskForResult()
static Task< TResult > System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetTaskForResult (TResult result) inline static package
Definition at line 175 of file AsyncTaskMethodBuilder.2.cs.
        {
            if (default(TResult) != null)
            {
                if (typeof(TResult) == typeof(bool))
                {
                    return JitHelpers.UnsafeCast<Task<TResult>>(((bool)((object)result)) ? AsyncTaskCache.TrueTask : AsyncTaskCache.FalseTask);
                }
                if (typeof(TResult) == typeof(int))
                {
                    int num = (int)((object)result);
                    if (num < 9 && num >= -1)
                    {
                        return JitHelpers.UnsafeCast<Task<TResult>>(AsyncTaskCache.Int32Tasks[num - -1]);
                    }
                }
                else if ((typeof(TResult) == typeof(uint) && (uint)((object)result) == 0U) || (typeof(TResult) == typeof(byte) && (byte)((object)result) == 0) || (typeof(TResult) == typeof(sbyte) && (sbyte)((object)result) == 0) || (typeof(TResult) == typeof(char) && (char)((object)result) == '\0') || (typeof(TResult) == typeof(long) && (long)((object)result) == 0L) || (typeof(TResult) == typeof(ulong) && (ulong)((object)result) == 0UL) || (typeof(TResult) == typeof(short) && (short)((object)result) == 0) || (typeof(TResult) == typeof(ushort) && (ushort)((object)result) == 0) || (typeof(TResult) == typeof(IntPtr) && (IntPtr)0 == (IntPtr)((object)result)) || (typeof(TResult) == typeof(UIntPtr) && (UIntPtr)0 == (UIntPtr)((object)result)))
                {
                    return AsyncTaskMethodBuilder<TResult>.s_defaultResultTask;
                }
            }
            else if (result == null)
            {
                return AsyncTaskMethodBuilder<TResult>.s_defaultResultTask;
            }
            return new Task<TResult>(result);
        }
References System.Runtime.CompilerServices.AsyncTaskCache.FalseTask, int, System.Runtime.CompilerServices.AsyncTaskCache.Int32Tasks, System.L, long, System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.s_defaultResultTask, and System.U.
Referenced by System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.Threading.Tasks.ValueTask< TResult >.GetTaskForValueTaskSource(), and System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetResult().