Terraria Decompiled: System.Runtime.CompilerServices.AsyncTaskMethodBuilder.SetResult
SetResult() [3/3]
void System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetResult (TResult result) inline
Definition at line 105 of file AsyncTaskMethodBuilder.2.cs.
        {
            Task<TResult> task = this.m_task;
            if (task == null)
            {
                this.m_task = AsyncTaskMethodBuilder<TResult>.GetTaskForResult(result);
                return;
            }
            if (AsyncCausalityTracer.LoggingOn)
            {
                AsyncCausalityTracer.TraceOperationCompletion(CausalityTraceLevel.Required, task.Id, AsyncCausalityStatus.Completed);
            }
            if (global::System.Threading.Tasks.Task.s_asyncDebuggingEnabled)
            {
                global::System.Threading.Tasks.Task.RemoveFromActiveTasks(task.Id);
            }
            if (!task.TrySetResult(result))
            {
                throw new InvalidOperationException(Environment.GetResourceString("An attempt was made to transition a task to a final state when it had already completed."));
            }
        }
References System.Environment.GetResourceString(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.GetTaskForResult(), System.Threading.Tasks.AsyncCausalityTracer.LoggingOn, System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.m_task, System.task, and System.Threading.Tasks.AsyncCausalityTracer.TraceOperationCompletion().
Referenced by System.Runtime.CompilerServices.AsyncIteratorMethodBuilder.Complete(), and System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetResult().