Terraria Decompiled: Steamworks.SteamUserStats.GetStat
GetStat() [2/2]
static bool Steamworks.SteamUserStats.GetStat (string pchName, out int pData) inline static
Definition at line 17 of file SteamUserStats.cs.
        {
            InteropHelp.TestIfAvailableClient();
            bool flag;
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle(pchName))
            {
                flag = NativeMethods.ISteamUserStats_GetStatInt32(CSteamAPIContext.GetSteamUserStats(), utf8StringHandle, out pData);
            }
            return flag;
        }
References Steamworks.CSteamAPIContext.GetSteamUserStats(), Steamworks.NativeMethods.ISteamUserStats_GetStatInt32(), and Steamworks.InteropHelp.TestIfAvailableClient().
Referenced by Terraria.Social.Steam.AchievementsSocialModule.GetFloatStat(), and Terraria.Social.Steam.AchievementsSocialModule.GetIntStat().