Terraria Decompiled: System.IO.Stream.ReadWriteTask.Invoke
Invoke()
void ITaskCompletionAction. System.IO.Stream.ReadWriteTask.Invoke (Task completingTask) inline private
Implements System.Threading.Tasks.ITaskCompletionAction.
Definition at line 786 of file Stream.cs.
            {
                ExecutionContext context = this._context;
                if (context == null)
                {
                    AsyncCallback callback = this._callback;
                    this._callback = null;
                    callback(completingTask);
                    return;
                }
                this._context = null;
                ContextCallback contextCallback = Stream.ReadWriteTask.s_invokeAsyncCallback;
                if (contextCallback == null)
                {
                    contextCallback = (Stream.ReadWriteTask.s_invokeAsyncCallback = new ContextCallback(Stream.ReadWriteTask.InvokeAsyncCallback));
                }
                ExecutionContext.RunInternal(context, contextCallback, this);
            }
References System.IO.Stream.ReadWriteTask._callback, System.IO.Stream.ReadWriteTask._context, System.Threading.ContextCallback(), System.IO.Stream.ReadWriteTask.InvokeAsyncCallback(), System.Threading.ExecutionContext.RunInternal(), and System.IO.Stream.ReadWriteTask.s_invokeAsyncCallback.