Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight
TryUpdatingMapWithLight()
void Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight () inline private
Definition at line 223 of file LegacyLighting.cs.
        {
            Main.mapTime = Main.mapTimeMax;
            int num = 40;
            Vector2 unscaledPosition = this._camera.UnscaledPosition;
            int num2 = (int)this._camera.ScaledSize.X;
            int num3 = (int)this._camera.ScaledSize.Y;
            Vector2 vector = unscaledPosition + Main.GameViewMatrix.Translation;
            int num4 = (int)Math.Floor((double)(vector.X / 16f));
            int num5 = (int)Math.Floor((double)((vector.X + (float)num2) / 16f)) + 1;
            int num6 = (int)Math.Floor((double)(vector.Y / 16f));
            int num7 = (int)Math.Floor((double)((vector.Y + (float)num3) / 16f)) + 1;
            num4 = Utils.Clamp<int>(num4, Lighting.OffScreenTiles, Main.maxTilesX - Lighting.OffScreenTiles);
            num5 = Utils.Clamp<int>(num5, Lighting.OffScreenTiles, Main.maxTilesX - Lighting.OffScreenTiles);
            num6 = Utils.Clamp<int>(num6, Lighting.OffScreenTiles, Main.maxTilesY - Lighting.OffScreenTiles);
            num7 = Utils.Clamp<int>(num7, Lighting.OffScreenTiles, Main.maxTilesY - Lighting.OffScreenTiles);
            int num8 = Utils.Clamp<int>(this._requestedRectLeft, num, Main.maxTilesX - num);
            int num9 = Utils.Clamp<int>(this._requestedRectRight, num, Main.maxTilesX - num);
            int num10 = Utils.Clamp<int>(this._requestedRectTop, num, Main.maxTilesY - num);
            int num11 = Utils.Clamp<int>(this._requestedRectBottom, num, Main.maxTilesY - num);
            num8 = Utils.Clamp<int>(num8, num4, num5);
            num9 = Utils.Clamp<int>(num9, num4, num5);
            num10 = Utils.Clamp<int>(num10, num6, num7);
            num11 = Utils.Clamp<int>(num11, num6, num7);
            int offScreenTiles = Lighting.OffScreenTiles;
            for (int i = num8; i < num9; i++)
            {
                LegacyLighting.LightingState[] array = this._states[i - this._requestedRectLeft + offScreenTiles];
                for (int j = num10; j < num11; j++)
                {
                    LegacyLighting.LightingState lightingState = array[j - this._requestedRectTop + offScreenTiles];
                    Tile tile = Main.tile[i, j];
                    float num12 = 0f;
                    if (lightingState.R > num12)
                    {
                        num12 = lightingState.R;
                    }
                    if (lightingState.G > num12)
                    {
                        num12 = lightingState.G;
                    }
                    if (lightingState.B > num12)
                    {
                        num12 = lightingState.B;
                    }
                    if (this.IsColorOrWhiteMode)
                    {
                        num12 *= 1.5f;
                    }
                    byte b = (byte)Math.Min(255f, num12 * 255f);
                    if ((double)j < Main.worldSurface && !tile.active() && tile.wall == 0 && tile.liquid == 0)
                    {
                        b = 22;
                    }
                    if ((b > 18 || Main.Map[i, j].Light > 0) && b < 22)
                    {
                        b = 22;
                    }
                    Main.Map.UpdateLighting(i, j, b);
                }
            }
            Main.updateMap = new Rectangle?(new Rectangle(num8, num10, num9 - num8, num11 - num10));
        }
References Terraria.Graphics.Light.LegacyLighting._camera, Terraria.Graphics.Light.LegacyLighting._requestedRectBottom, Terraria.Graphics.Light.LegacyLighting._requestedRectLeft, Terraria.Graphics.Light.LegacyLighting._requestedRectRight, Terraria.Graphics.Light.LegacyLighting._requestedRectTop, Terraria.Graphics.Light.LegacyLighting._states, Terraria.Tile.active(), System.array, Terraria.Graphics.Light.LegacyLighting.LightingState.B, Terraria.Utils.Clamp(), System.Math.Floor(), Terraria.Graphics.Light.LegacyLighting.LightingState.G, Terraria.Main.GameViewMatrix, int, Terraria.Graphics.Light.LegacyLighting.IsColorOrWhiteMode, Terraria.Main.Map, Terraria.Main.mapTimeMax, System.Math.Min(), Terraria.Lighting.OffScreenTiles, Terraria.Graphics.Light.LegacyLighting.LightingState.R, Terraria.Graphics.Camera.ScaledSize, Terraria.Main.tile, Terraria.Graphics.Camera.UnscaledPosition, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Light.LegacyLighting.ProcessArea().