Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.ProcessArea
ProcessArea()
void Terraria.Graphics.Light.LegacyLighting.ProcessArea (Rectangle area) inline
Implements Terraria.Graphics.Light.ILightingEngine.
Definition at line 153 of file LegacyLighting.cs.
        {
            this._oldSkyColor = this._skyColor;
            float num = (float)Main.tileColor.R / 255f;
            float num2 = (float)Main.tileColor.G / 255f;
            float num3 = (float)Main.tileColor.B / 255f;
            this._skyColor = (num + num2 + num3) / 3f;
            if (this.IsColorOrWhiteMode)
            {
                this._offScreenTiles2 = 34;
                Lighting.OffScreenTiles = 40;
            }
            else
            {
                this._offScreenTiles2 = 18;
                Lighting.OffScreenTiles = 23;
            }
            this._requestedRectLeft = area.Left;
            this._requestedRectRight = area.Right;
            this._requestedRectTop = area.Top;
            this._requestedRectBottom = area.Bottom;
            this._expandedRectLeft = this._requestedRectLeft - Lighting.OffScreenTiles;
            this._expandedRectTop = this._requestedRectTop - Lighting.OffScreenTiles;
            this._expandedRectRight = this._requestedRectRight + Lighting.OffScreenTiles;
            this._expandedRectBottom = this._requestedRectBottom + Lighting.OffScreenTiles;
            Main.renderCount++;
            int num4 = (int)this._camera.UnscaledSize.X / 16 + Lighting.OffScreenTiles * 2;
            int num5 = (int)this._camera.UnscaledSize.Y / 16 + Lighting.OffScreenTiles * 2;
            if (Main.renderCount < 3)
            {
                this.DoColors();
            }
            if (Main.renderCount == 2)
            {
                this.CopyFullyProcessedDataOver(num4, num5);
            }
            else if (this._lastCameraPosition != null)
            {
                this.ShiftUnProcessedDataOver(num4, num5);
                if (Netplay.Connection.StatusMax > 0)
                {
                    Main.mapTime = 1;
                }
                if (Main.mapDelay > 0)
                {
                    Main.mapDelay--;
                }
                else if (Main.mapTime == 0 && Main.mapEnabled && Main.renderCount == 3)
                {
                    try
                    {
                        this.TryUpdatingMapWithLight();
                    }
                    catch
                    {
                    }
                }
                if (this._oldSkyColor != this._skyColor)
                {
                    this.UpdateLightToSkyColor(num, num2, num3);
                }
            }
            if (Main.renderCount > LegacyLighting.RenderPhases)
            {
                this.PreRenderPhase();
            }
            this._lastCameraPosition = new Vector2?(Main.Camera.UnscaledPosition);
        }
References Terraria.Graphics.Light.LegacyLighting._camera, Terraria.Graphics.Light.LegacyLighting._lastCameraPosition, Terraria.Graphics.Light.LegacyLighting._oldSkyColor, Terraria.Graphics.Light.LegacyLighting._skyColor, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Main.Camera, Terraria.Netplay.Connection, Terraria.Graphics.Light.LegacyLighting.CopyFullyProcessedDataOver(), Terraria.Graphics.Light.LegacyLighting.DoColors(), int, Terraria.Graphics.Light.LegacyLighting.IsColorOrWhiteMode, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.mapDelay, Terraria.Main.mapEnabled, Terraria.Main.mapTime, Terraria.Lighting.OffScreenTiles, Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.Main.renderCount, Terraria.Graphics.Light.LegacyLighting.RenderPhases, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Graphics.Light.LegacyLighting.ShiftUnProcessedDataOver(), Terraria.RemoteServer.StatusMax, Terraria.Main.tileColor, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight(), Terraria.Graphics.Camera.UnscaledSize, Terraria.Graphics.Light.LegacyLighting.UpdateLightToSkyColor(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.