Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.PreRenderPhase
PreRenderPhase()
void Terraria.Graphics.Light.LegacyLighting.PreRenderPhase () inline private
Definition at line 502 of file LegacyLighting.cs.
        {
            float num = (float)Main.tileColor.R / 255f;
            float num2 = (float)Main.tileColor.G / 255f;
            float num3 = (float)Main.tileColor.B / 255f;
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            int num4 = 0;
            int num5 = (int)this._camera.UnscaledSize.X / 16 + Lighting.OffScreenTiles * 2 + 10;
            int num6 = 0;
            int num7 = (int)this._camera.UnscaledSize.Y / 16 + Lighting.OffScreenTiles * 2 + 10;
            this._minX = num5;
            this._maxX = num4;
            this._minY = num7;
            this._maxY = num6;
            this._rgb = this.Mode == 0 || this.Mode == 3;
            for (int i = num4; i < num5; i++)
            {
                LegacyLighting.LightingState[] array = this._states[i];
                for (int j = num6; j < num7; j++)
                {
                    LegacyLighting.LightingState lightingState = array[j];
                    lightingState.R2 = 0f;
                    lightingState.G2 = 0f;
                    lightingState.B2 = 0f;
                    lightingState.CrackedLight = false;
                    lightingState.StopLight = false;
                    lightingState.WetLight = false;
                    lightingState.HoneyLight = false;
                }
            }
            if (Main.wofNPCIndex >= 0 && Main.player[Main.myPlayer].gross)
            {
                try
                {
                    int num8 = (int)this._camera.UnscaledPosition.Y / 16 - 10;
                    int num9 = (int)(this._camera.UnscaledPosition.Y + this._camera.UnscaledSize.Y) / 16 + 10;
                    int num10 = (int)Main.npc[Main.wofNPCIndex].position.X / 16;
                    if (Main.npc[Main.wofNPCIndex].direction > 0)
                    {
                        num10 -= 3;
                    }
                    else
                    {
                        num10 += 2;
                    }
                    int num11 = num10 + 8;
                    float num12 = 0.5f * Main.demonTorch + 1f * (1f - Main.demonTorch);
                    float num13 = 0.3f;
                    float num14 = 1f * Main.demonTorch + 0.5f * (1f - Main.demonTorch);
                    num12 *= 0.2f;
                    num13 *= 0.1f;
                    num14 *= 0.3f;
                    for (int k = num10; k <= num11; k++)
                    {
                        LegacyLighting.LightingState[] array2 = this._states[k - num10];
                        for (int l = num8; l <= num9; l++)
{
                            LegacyLighting.LightingState lightingState2 = array2[l - this._expandedRectTop];
                            if (lightingState2.R2 < num12)
{
                                lightingState2.R2 = num12;
                            }
                            if (lightingState2.G2 < num13)
{
                                lightingState2.G2 = num13;
                            }
                            if (lightingState2.B2 < num14)
{
                                lightingState2.B2 = num14;
                            }
                        }
                    }
                }
                catch
                {
                }
            }
            num4 = Utils.Clamp<int>(this._expandedRectLeft, 5, Main.maxTilesX - 1);
            num5 = Utils.Clamp<int>(this._expandedRectRight, 5, Main.maxTilesX - 1);
            num6 = Utils.Clamp<int>(this._expandedRectTop, 5, Main.maxTilesY - 1);
            num7 = Utils.Clamp<int>(this._expandedRectBottom, 5, Main.maxTilesY - 1);
            Main.UpdateSceneMetrics();
            this._tileScanner.Update();
            this._tileScanner.ExportTo(new Rectangle(num4, num6, num5 - num4, num7 - num6), this._lightMap, new TileLightScannerOptions
            {
                DrawInvisibleWalls = Main.ShouldShowInvisibleBlocksAndWalls()
            });
            for (int m = num4; m < num5; m++)
            {
                LegacyLighting.LightingState[] array3 = this._states[m - this._expandedRectLeft];
                for (int n = num6; n < num7; n++)
                {
                    LegacyLighting.LightingState lightingState3 = array3[n - this._expandedRectTop];
                    if (Main.tile[m, n] == null)
                    {
                        Tile tile = new Tile();
                        Main.tile[m, n] = tile;
                    }
                    Vector3 vector;
                    this._lightMap.GetLight(m - num4, n - num6, out vector);
                    if (this._rgb)
                    {
                        lightingState3.R2 = vector.X;
                        lightingState3.G2 = vector.Y;
                        lightingState3.B2 = vector.Z;
                    }
                    else
                    {
                        float num15 = (vector.X + vector.Y + vector.Z) / 3f;
                        lightingState3.R2 = num15;
                        lightingState3.G2 = num15;
                        lightingState3.B2 = num15;
                    }
                    switch (this._lightMap.GetMask(m - num4, n - num6))
                    {
                    case LightMaskMode.Solid:
                        lightingState3.StopLight = true;
                        break;
                    case LightMaskMode.Water:
                        lightingState3.WetLight = true;
                        break;
                    case LightMaskMode.Honey:
                        lightingState3.WetLight = true;
                        lightingState3.HoneyLight = true;
                        break;
                    case LightMaskMode.CrackedBricks:
                        lightingState3.CrackedLight = true;
                        break;
                    }
                    if (lightingState3.R2 > 0f || (this._rgb && (lightingState3.G2 > 0f || lightingState3.B2 > 0f)))
                    {
                        int num16 = m - this._expandedRectLeft;
                        int num17 = n - this._expandedRectTop;
                        if (this._minX > num16)
{
                            this._minX = num16;
                        }
                        if (this._maxX < num16 + 1)
{
                            this._maxX = num16 + 1;
                        }
                        if (this._minY > num17)
{
                            this._minY = num17;
                        }
                        if (this._maxY < num17 + 1)
{
                            this._maxY = num17 + 1;
                        }
                    }
                }
            }
            foreach (KeyValuePair<Point16, LegacyLighting.ColorTriplet> keyValuePair in this._tempLights)
            {
                int num18 = (int)keyValuePair.Key.X - this._requestedRectLeft + Lighting.OffScreenTiles;
                int num19 = (int)keyValuePair.Key.Y - this._requestedRectTop + Lighting.OffScreenTiles;
                if (num18 >= 0 && (float)num18 < this._camera.UnscaledSize.X / 16f + (float)(Lighting.OffScreenTiles * 2) + 10f && num19 >= 0 && (float)num19 < this._camera.UnscaledSize.Y / 16f + (float)(Lighting.OffScreenTiles * 2) + 10f)
                {
                    LegacyLighting.LightingState lightingState4 = this._states[num18][num19];
                    if (lightingState4.R2 < keyValuePair.Value.R)
                    {
                        lightingState4.R2 = keyValuePair.Value.R;
                    }
                    if (lightingState4.G2 < keyValuePair.Value.G)
                    {
                        lightingState4.G2 = keyValuePair.Value.G;
                    }
                    if (lightingState4.B2 < keyValuePair.Value.B)
                    {
                        lightingState4.B2 = keyValuePair.Value.B;
                    }
                    if (this._minX > num18)
                    {
                        this._minX = num18;
                    }
                    if (this._maxX < num18 + 1)
                    {
                        this._maxX = num18 + 1;
                    }
                    if (this._minY > num19)
                    {
                        this._minY = num19;
                    }
                    if (this._maxY < num19 + 1)
                    {
                        this._maxY = num19 + 1;
                    }
                }
            }
            if (!Main.gamePaused && !CaptureManager.Instance.IsCapturing)
            {
                this._tempLights.Clear();
            }
            this._minX += this._expandedRectLeft;
            this._maxX += this._expandedRectLeft;
            this._minY += this._expandedRectTop;
            this._maxY += this._expandedRectTop;
            this._minBoundArea.Set(this._minX, this._maxX, this._minY, this._maxY);
            this._requestedArea.Set(this._requestedRectLeft, this._requestedRectRight, this._requestedRectTop, this._requestedRectBottom);
            this._expandedArea.Set(this._expandedRectLeft, this._expandedRectRight, this._expandedRectTop, this._expandedRectBottom);
            this._offScreenTiles2ExpandedArea.Set(this._requestedRectLeft - this._offScreenTiles2, this._requestedRectRight + this._offScreenTiles2, this._requestedRectTop - this._offScreenTiles2, this._requestedRectBottom + this._offScreenTiles2);
            this._scrX = (int)Math.Floor((double)(this._camera.UnscaledPosition.X / 16f));
            this._scrY = (int)Math.Floor((double)(this._camera.UnscaledPosition.Y / 16f));
            Main.renderCount = 0;
            TimeLogger.LightingInit.AddTime(startTimestamp);
            this.DoColors();
        }
References Terraria.Graphics.Light.LegacyLighting._camera, Terraria.Graphics.Light.LegacyLighting._expandedArea, Terraria.Graphics.Light.LegacyLighting._expandedRectBottom, Terraria.Graphics.Light.LegacyLighting._expandedRectLeft, Terraria.Graphics.Light.LegacyLighting._expandedRectRight, Terraria.Graphics.Light.LegacyLighting._expandedRectTop, Terraria.Graphics.Light.LegacyLighting._lightMap, Terraria.Graphics.Light.LegacyLighting._maxX, Terraria.Graphics.Light.LegacyLighting._maxY, Terraria.Graphics.Light.LegacyLighting._minBoundArea, Terraria.Graphics.Light.LegacyLighting._minX, Terraria.Graphics.Light.LegacyLighting._minY, Terraria.Graphics.Light.LegacyLighting._offScreenTiles2, Terraria.Graphics.Light.LegacyLighting._offScreenTiles2ExpandedArea, Terraria.Graphics.Light.LegacyLighting._requestedArea, Terraria.Graphics.Light.LegacyLighting._requestedRectBottom, Terraria.Graphics.Light.LegacyLighting._requestedRectLeft, Terraria.Graphics.Light.LegacyLighting._requestedRectRight, Terraria.Graphics.Light.LegacyLighting._requestedRectTop, Terraria.Graphics.Light.LegacyLighting._rgb, Terraria.Graphics.Light.LegacyLighting._states, Terraria.Graphics.Light.LegacyLighting._tempLights, Terraria.Graphics.Light.LegacyLighting._tileScanner, System.array, Terraria.Graphics.Light.LegacyLighting.LightingState.B2, Terraria.Utils.Clamp(), Terraria.Main.demonTorch, Terraria.Entity.direction, Terraria.Graphics.Light.LegacyLighting.DoColors(), Terraria.Graphics.Light.TileLightScanner.ExportTo(), System.Math.Floor(), Terraria.Graphics.Light.LegacyLighting.LightingState.G2, Terraria.Main.gamePaused, Terraria.Graphics.Light.LightMap.GetLight(), Terraria.Graphics.Light.LightMap.GetMask(), Terraria.Player.gross, Terraria.Graphics.Capture.CaptureManager.Instance, int, Terraria.Graphics.Capture.CaptureManager.IsCapturing, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.TimeLogger.LightingInit, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Lighting.OffScreenTiles, Terraria.Main.player, Terraria.Entity.position, Terraria.Graphics.Light.LegacyLighting.LightingState.R2, Terraria.Main.ShouldShowInvisibleBlocksAndWalls(), Terraria.TimeLogger.Start(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileColor, Terraria.Graphics.Camera.UnscaledPosition, Terraria.Graphics.Camera.UnscaledSize, Terraria.Graphics.Light.TileLightScanner.Update(), Terraria.Main.UpdateSceneMetrics(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Terraria.Main.wofNPCIndex, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Graphics.Light.LegacyLighting.ProcessArea().