Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.UpdateLightToSkyColor
UpdateLightToSkyColor()
void Terraria.Graphics.Light.LegacyLighting.UpdateLightToSkyColor (float tileR, float tileG, float tileB) inline private
Definition at line 288 of file LegacyLighting.cs.
        {
            int num = Utils.Clamp<int>(this._expandedRectLeft, 0, Main.maxTilesX - 1);
            int num2 = Utils.Clamp<int>(this._expandedRectRight, 0, Main.maxTilesX - 1);
            int num3 = Utils.Clamp<int>(this._expandedRectTop, 0, Main.maxTilesY - 1);
            int num4 = Utils.Clamp<int>(this._expandedRectBottom, 0, (int)Main.worldSurface - 1);
            if ((double)num3 < Main.worldSurface)
            {
                for (int i = num; i < num2; i++)
                {
                    LegacyLighting.LightingState[] array = this._states[i - this._expandedRectLeft];
                    for (int j = num3; j < num4; j++)
                    {
                        LegacyLighting.LightingState lightingState = array[j - this._expandedRectTop];
                        Tile tile = Main.tile[i, j];
                        if (tile == null)
{
                            tile = new Tile();
                            Main.tile[i, j] = tile;
                        }
                        if ((!tile.active() || !Main.tileNoSunLight[(int)tile.type]) && lightingState.R < this._skyColor && tile.liquid < 200 && (Main.wallLight[(int)tile.wall] || tile.wall == 73))
{
                            lightingState.R = tileR;
                            if (lightingState.G < this._skyColor)
{
                                lightingState.G = tileG;
                            }
                            if (lightingState.B < this._skyColor)
{
                                lightingState.B = tileB;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Graphics.Light.LegacyLighting._expandedRectBottom, Terraria.Graphics.Light.LegacyLighting._expandedRectLeft, Terraria.Graphics.Light.LegacyLighting._expandedRectRight, Terraria.Graphics.Light.LegacyLighting._expandedRectTop, Terraria.Graphics.Light.LegacyLighting._states, Terraria.Tile.active(), System.array, Terraria.Graphics.Light.LegacyLighting.LightingState.B, Terraria.Utils.Clamp(), Terraria.Graphics.Light.LegacyLighting.LightingState.G, int, Terraria.Tile.liquid, Terraria.Graphics.Light.LegacyLighting.LightingState.R, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileNoSunLight, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallLight, and Terraria.Main.worldSurface.
Referenced by Terraria.Graphics.Light.LegacyLighting.ProcessArea().