Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.doColors_Mode0_Swipe
doColors_Mode0_Swipe()
void Terraria.Graphics.Light.LegacyLighting.doColors_Mode0_Swipe (int outerLoopStart, int outerLoopEnd, object context) inline private
Definition at line 959 of file LegacyLighting.cs.
        {
            LegacyLighting.LightingSwipeData lightingSwipeData = context as LegacyLighting.LightingSwipeData;
            FastRandom fastRandom = default(FastRandom);
            try
            {
                bool flag = true;
                for (;;)
                {
                    int num;
                    int num2;
                    int num3;
                    if (flag)
                    {
                        num = 1;
                        num2 = lightingSwipeData.InnerLoop1Start;
                        num3 = lightingSwipeData.InnerLoop1End;
                    }
                    else
                    {
                        num = -1;
                        num2 = lightingSwipeData.InnerLoop2Start;
                        num3 = lightingSwipeData.InnerLoop2End;
                    }
                    for (int i = outerLoopStart; i < outerLoopEnd; i++)
                    {
                        LegacyLighting.LightingState[] array = lightingSwipeData.JaggedArray[i];
                        float num4 = 0f;
                        float num5 = 0f;
                        float num6 = 0f;
                        int num7 = Math.Min(array.Length - 1, Math.Max(0, num2));
                        int num8 = Math.Min(array.Length - 1, Math.Max(0, num3));
                        int num9 = num7;
                        while (num9 != num8)
{
                            LegacyLighting.LightingState lightingState = array[num9];
                            LegacyLighting.LightingState lightingState2 = array[num9 + num];
                            bool flag3;
                            bool flag2 = (flag3 = false);
                            if (lightingState.R2 > num4)
{
                                num4 = lightingState.R2;
                            }
                            else if ((double)num4 <= 0.0185)
{
                                flag3 = true;
                            }
                            else if (lightingState.R2 < num4)
{
                                lightingState.R2 = num4;
                            }
                            if (lightingState.WetLight)
{
                                fastRandom = LegacyLighting._swipeRandom.WithModifier((ulong)((long)(i * 1000 + num9)));
                            }
                            if (!flag3 && lightingState2.R2 <= num4)
{
                                if (lightingState.StopLight)
{
                                    num4 *= this._negLight2;
                                }
                                else if (lightingState.CrackedLight)
{
                                    num4 *= this._negLight3;
                                }
                                else if (lightingState.WetLight)
{
                                    if (lightingState.HoneyLight)
{
                                        num4 *= this._honeyLightR * (float)fastRandom.Next(98, 100) * 0.01f;
                                    }
                                    else
{
                                        num4 *= this._wetLightR * (float)fastRandom.Next(98, 100) * 0.01f;
                                    }
                                }
                                else
{
                                    num4 *= this._negLight;
                                }
                            }
                            if (lightingState.G2 > num5)
{
                                num5 = lightingState.G2;
                            }
                            else if ((double)num5 <= 0.0185)
{
                                flag2 = true;
                            }
                            else
{
                                lightingState.G2 = num5;
                            }
                            if (!flag2 && lightingState2.G2 <= num5)
{
                                if (lightingState.StopLight)
{
                                    num5 *= this._negLight2;
                                }
                                else if (lightingState.CrackedLight)
{
                                    num5 *= this._negLight3;
                                }
                                else if (lightingState.WetLight)
{
                                    if (lightingState.HoneyLight)
{
                                        num5 *= this._honeyLightG * (float)fastRandom.Next(97, 100) * 0.01f;
                                    }
                                    else
{
                                        num5 *= this._wetLightG * (float)fastRandom.Next(97, 100) * 0.01f;
                                    }
                                }
                                else
{
                                    num5 *= this._negLight;
                                }
                            }
                            if (lightingState.B2 > num6)
{
                                num6 = lightingState.B2;
                                goto IL_02A8;
                            }
                            if ((double)num6 > 0.0185)
{
                                lightingState.B2 = num6;
                                goto IL_02A8;
                            }
                            IL_033F:
                            num9 += num;
                            continue;
                            IL_02A8:
                            if (lightingState2.B2 >= num6)
{
                                goto IL_033F;
                            }
                            if (lightingState.StopLight)
{
                                num6 *= this._negLight2;
                                goto IL_033F;
                            }
                            if (lightingState.CrackedLight)
{
                                num6 *= this._negLight3;
                                goto IL_033F;
                            }
                            if (!lightingState.WetLight)
{
                                num6 *= this._negLight;
                                goto IL_033F;
                            }
                            if (lightingState.HoneyLight)
{
                                num6 *= this._honeyLightB * (float)fastRandom.Next(97, 100) * 0.01f;
                                goto IL_033F;
                            }
                            num6 *= this._wetLightB * (float)fastRandom.Next(97, 100) * 0.01f;
                            goto IL_033F;
                        }
                    }
                    if (!flag)
                    {
                        break;
                    }
                    flag = false;
                }
            }
            catch
            {
            }
        }
References Terraria.Graphics.Light.LegacyLighting._negLight, Terraria.Graphics.Light.LegacyLighting._negLight2, Terraria.Graphics.Light.LegacyLighting._negLight3, Terraria.Graphics.Light.LegacyLighting._swipeRandom, System.array, Terraria.Graphics.Light.LegacyLighting.LightingState.B2, Terraria.Graphics.Light.LegacyLighting.LightingState.CrackedLight, Terraria.Graphics.Light.LegacyLighting.LightingState.G2, Terraria.Graphics.Light.LegacyLighting.LightingState.HoneyLight, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop1End, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop1Start, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop2End, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop2Start, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.JaggedArray, long, System.Math.Max(), System.Math.Min(), Terraria.Utilities.FastRandom.Next(), Terraria.Graphics.Light.LegacyLighting.LightingState.R2, Terraria.Graphics.Light.LegacyLighting.LightingState.StopLight, Terraria.Graphics.Light.LegacyLighting.LightingState.WetLight, and Terraria.Utilities.FastRandom.WithModifier().
Referenced by Terraria.Graphics.Light.LegacyLighting.DoColors().