Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.DoColors
DoColors()
void Terraria.Graphics.Light.LegacyLighting.DoColors () inline private
Definition at line 711 of file LegacyLighting.cs.
        {
            if (this.IsColorOrWhiteMode)
            {
                this._blueWave += (float)this._blueDir * 0.0001f;
                if (this._blueWave > 1f)
                {
                    this._blueWave = 1f;
                    this._blueDir = -1;
                }
                else if (this._blueWave < 0.97f)
                {
                    this._blueWave = 0.97f;
                    this._blueDir = 1;
                }
                if (this._rgb)
                {
                    this._negLight = 0.91f;
                    this._negLight2 = 0.56f;
                    this._negLight3 = 0.8f;
                    this._honeyLightG = 0.7f * this._negLight * this._blueWave;
                    this._honeyLightR = 0.75f * this._negLight * this._blueWave;
                    this._honeyLightB = 0.6f * this._negLight * this._blueWave;
                    switch (Main.waterStyle)
                    {
                    case 0:
                    case 1:
                    case 7:
                    case 8:
                        this._wetLightG = 0.96f * this._negLight * this._blueWave;
                        this._wetLightR = 0.88f * this._negLight * this._blueWave;
                        this._wetLightB = 1.015f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 2:
                        this._wetLightG = 0.85f * this._negLight * this._blueWave;
                        this._wetLightR = 0.94f * this._negLight * this._blueWave;
                        this._wetLightB = 1.01f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 3:
                        this._wetLightG = 0.95f * this._negLight * this._blueWave;
                        this._wetLightR = 0.84f * this._negLight * this._blueWave;
                        this._wetLightB = 1.015f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 4:
                        this._wetLightG = 0.86f * this._negLight * this._blueWave;
                        this._wetLightR = 0.9f * this._negLight * this._blueWave;
                        this._wetLightB = 1.01f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 5:
                        this._wetLightG = 0.99f * this._negLight * this._blueWave;
                        this._wetLightR = 0.84f * this._negLight * this._blueWave;
                        this._wetLightB = 1.01f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 6:
                        this._wetLightR = 0.83f * this._negLight * this._blueWave;
                        this._wetLightG = 0.93f * this._negLight * this._blueWave;
                        this._wetLightB = 0.98f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 9:
                        this._wetLightG = 0.88f * this._negLight * this._blueWave;
                        this._wetLightR = 1f * this._negLight * this._blueWave;
                        this._wetLightB = 0.84f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 10:
                        this._wetLightG = 1f * this._negLight * this._blueWave;
                        this._wetLightR = 0.83f * this._negLight * this._blueWave;
                        this._wetLightB = 1f * this._negLight * this._blueWave;
                        goto IL_044D;
                    case 12:
                        this._wetLightG = 0.98f * this._negLight * this._blueWave;
                        this._wetLightR = 0.95f * this._negLight * this._blueWave;
                        this._wetLightB = 0.85f * this._negLight * this._blueWave;
                        goto IL_044D;
                    }
                    this._wetLightG = 0f;
                    this._wetLightR = 0f;
                    this._wetLightB = 0f;
                }
                else
                {
                    this._negLight = 0.9f;
                    this._negLight2 = 0.54f;
                    this._negLight3 = 0.8f;
                    this._wetLightR = 0.95f * this._negLight * this._blueWave;
                }
                IL_044D:
                if (Main.player[Main.myPlayer].nightVision)
                {
                    this._negLight *= 1.03f;
                    this._negLight2 *= 1.03f;
                    this._negLight3 *= 1.03f;
                }
                if (Main.player[Main.myPlayer].blind)
                {
                    this._negLight *= 0.95f;
                    this._negLight2 *= 0.95f;
                    this._negLight3 *= 0.95f;
                }
                if (Main.player[Main.myPlayer].blackout)
                {
                    this._negLight *= 0.85f;
                    this._negLight2 *= 0.85f;
                    this._negLight3 *= 0.85f;
                }
                if (Main.player[Main.myPlayer].headcovered)
                {
                    this._negLight *= 0.85f;
                    this._negLight2 *= 0.85f;
                    this._negLight3 *= 0.85f;
                }
            }
            else
            {
                this._negLight = 0.04f;
                this._negLight2 = 0.16f;
                this._negLight3 = 0.08f;
                if (Main.player[Main.myPlayer].nightVision)
                {
                    this._negLight -= 0.013f;
                    this._negLight2 -= 0.04f;
                    this._negLight3 -= 0.04f;
                }
                if (Main.player[Main.myPlayer].blind)
                {
                    this._negLight += 0.03f;
                    this._negLight2 += 0.06f;
                    this._negLight3 += 0.06f;
                }
                if (Main.player[Main.myPlayer].blackout)
                {
                    this._negLight += 0.09f;
                    this._negLight2 += 0.18f;
                    this._negLight3 += 0.18f;
                }
                if (Main.player[Main.myPlayer].headcovered)
                {
                    this._negLight += 0.09f;
                    this._negLight2 += 0.18f;
                    this._negLight3 += 0.18f;
                }
                this._wetLightR = this._negLight * 1.2f;
                this._wetLightG = this._negLight * 1.1f;
            }
            int num;
            int num2;
            switch (Main.renderCount)
            {
            case 0:
                num = 0;
                num2 = 1;
                break;
            case 1:
                num = 1;
                num2 = 3;
                break;
            case 2:
                num = 3;
                num2 = 4;
                break;
            default:
                num = 0;
                num2 = 0;
                break;
            }
            int left = this._expandedArea.Left;
            int top = this._expandedArea.Top;
            for (int i = num; i < num2; i++)
            {
                TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
                int num3 = 0;
                int num4 = 0;
                switch (i)
                {
                case 0:
                    this._swipe.InnerLoop1Start = this._minBoundArea.Top - top;
                    this._swipe.InnerLoop2Start = this._minBoundArea.Bottom - top;
                    this._swipe.InnerLoop1End = this._requestedArea.Bottom + LegacyLighting.RenderPhases - top;
                    this._swipe.InnerLoop2End = this._requestedArea.Top - LegacyLighting.RenderPhases - top;
                    num3 = this._minBoundArea.Left - left;
                    num4 = this._minBoundArea.Right - left;
                    this._swipe.JaggedArray = this._states;
                    break;
                case 1:
                    this._swipe.InnerLoop1Start = this._expandedArea.Left - left;
                    this._swipe.InnerLoop2Start = this._expandedArea.Right - left;
                    this._swipe.InnerLoop1End = this._requestedArea.Right + LegacyLighting.RenderPhases - left;
                    this._swipe.InnerLoop2End = this._requestedArea.Left - LegacyLighting.RenderPhases - left;
                    num3 = this._expandedArea.Top - top;
                    num4 = this._expandedArea.Bottom - top;
                    this._swipe.JaggedArray = this._axisFlipStates;
                    break;
                case 2:
                    this._swipe.InnerLoop1Start = this._offScreenTiles2ExpandedArea.Top - top;
                    this._swipe.InnerLoop2Start = this._offScreenTiles2ExpandedArea.Bottom - top;
                    this._swipe.InnerLoop1End = this._requestedArea.Bottom + LegacyLighting.RenderPhases - top;
                    this._swipe.InnerLoop2End = this._requestedArea.Top - LegacyLighting.RenderPhases - top;
                    num3 = this._offScreenTiles2ExpandedArea.Left - left;
                    num4 = this._offScreenTiles2ExpandedArea.Right - left;
                    this._swipe.JaggedArray = this._states;
                    break;
                case 3:
                    this._swipe.InnerLoop1Start = this._offScreenTiles2ExpandedArea.Left - left;
                    this._swipe.InnerLoop2Start = this._offScreenTiles2ExpandedArea.Right - left;
                    this._swipe.InnerLoop1End = this._requestedArea.Right + LegacyLighting.RenderPhases - left;
                    this._swipe.InnerLoop2End = this._requestedArea.Left - LegacyLighting.RenderPhases - left;
                    num3 = this._offScreenTiles2ExpandedArea.Top - top;
                    num4 = this._offScreenTiles2ExpandedArea.Bottom - top;
                    this._swipe.JaggedArray = this._axisFlipStates;
                    break;
                }
                if (this._swipe.InnerLoop1Start > this._swipe.InnerLoop1End)
                {
                    this._swipe.InnerLoop1Start = this._swipe.InnerLoop1End;
                }
                if (this._swipe.InnerLoop2Start < this._swipe.InnerLoop2End)
                {
                    this._swipe.InnerLoop2Start = this._swipe.InnerLoop2End;
                }
                if (num3 > num4)
                {
                    num3 = num4;
                }
                ParallelForAction parallelForAction;
                switch (this.Mode)
                {
                case 0:
                    parallelForAction = new ParallelForAction(this.doColors_Mode0_Swipe);
                    break;
                case 1:
                    parallelForAction = new ParallelForAction(this.doColors_Mode1_Swipe);
                    break;
                case 2:
                    parallelForAction = new ParallelForAction(this.doColors_Mode2_Swipe);
                    break;
                case 3:
                    parallelForAction = new ParallelForAction(this.doColors_Mode3_Swipe);
                    break;
                default:
                    parallelForAction = new ParallelForAction(this.doColors_Mode0_Swipe);
                    break;
                }
                FastParallel.For(num3, num4, parallelForAction, this._swipe);
                LegacyLighting._swipeRandom.NextSeed();
                TimeLogger.LightingByPass[i].AddTime(startTimestamp);
            }
        }
References Terraria.Graphics.Light.LegacyLighting._axisFlipStates, Terraria.Graphics.Light.LegacyLighting._blueDir, Terraria.Graphics.Light.LegacyLighting._blueWave, Terraria.Graphics.Light.LegacyLighting._expandedArea, Terraria.Graphics.Light.LegacyLighting._rgb, Terraria.Graphics.Light.LegacyLighting._states, Terraria.Graphics.Light.LegacyLighting._swipe, Terraria.Graphics.Light.LegacyLighting._swipeRandom, Terraria.Player.blackout, Terraria.Player.blind, Terraria.Graphics.Light.LegacyLighting.doColors_Mode0_Swipe(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode1_Swipe(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode2_Swipe(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode3_Swipe(), ReLogic.Threading.FastParallel.For(), Terraria.Player.headcovered, Terraria.Graphics.Light.LegacyLighting.IsColorOrWhiteMode, Terraria.TimeLogger.LightingByPass, Terraria.Graphics.Light.LegacyLighting.Mode, Terraria.Main.myPlayer, Terraria.Utilities.FastRandom.NextSeed(), Terraria.Player.nightVision, ReLogic.Threading.ParallelForAction(), Terraria.Main.player, Terraria.Main.renderCount, Terraria.TimeLogger.Start(), and Terraria.Main.waterStyle.
Referenced by Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), and Terraria.Graphics.Light.LegacyLighting.ProcessArea().