Terraria Decompiled: Terraria.Graphics.Light.LegacyLighting.doColors_Mode1_Swipe
doColors_Mode1_Swipe()
void Terraria.Graphics.Light.LegacyLighting.doColors_Mode1_Swipe (int outerLoopStart, int outerLoopEnd, object context) inline private
Definition at line 1133 of file LegacyLighting.cs.
        {
            LegacyLighting.LightingSwipeData lightingSwipeData = context as LegacyLighting.LightingSwipeData;
            FastRandom fastRandom = default(FastRandom);
            try
            {
                bool flag = true;
                for (;;)
                {
                    int num;
                    int num2;
                    int num3;
                    if (flag)
                    {
                        num = 1;
                        num2 = lightingSwipeData.InnerLoop1Start;
                        num3 = lightingSwipeData.InnerLoop1End;
                    }
                    else
                    {
                        num = -1;
                        num2 = lightingSwipeData.InnerLoop2Start;
                        num3 = lightingSwipeData.InnerLoop2End;
                    }
                    for (int i = outerLoopStart; i < outerLoopEnd; i++)
                    {
                        LegacyLighting.LightingState[] array = lightingSwipeData.JaggedArray[i];
                        float num4 = 0f;
                        int num5 = num2;
                        while (num5 != num3)
{
                            LegacyLighting.LightingState lightingState = array[num5];
                            if (lightingState.R2 > num4)
{
                                num4 = lightingState.R2;
                                goto IL_009E;
                            }
                            if ((double)num4 > 0.0185)
{
                                if (lightingState.R2 < num4)
{
                                    lightingState.R2 = num4;
                                    goto IL_009E;
                                }
                                goto IL_009E;
                            }
                            IL_0155:
                            num5 += num;
                            continue;
                            IL_009E:
                            if (array[num5 + num].R2 > num4)
{
                                goto IL_0155;
                            }
                            if (lightingState.StopLight)
{
                                num4 *= this._negLight2;
                                goto IL_0155;
                            }
                            if (lightingState.CrackedLight)
{
                                num4 *= this._negLight3;
                                goto IL_0155;
                            }
                            if (!lightingState.WetLight)
{
                                num4 *= this._negLight;
                                goto IL_0155;
                            }
                            fastRandom = LegacyLighting._swipeRandom.WithModifier((ulong)((long)(i * 1000 + num5)));
                            if (lightingState.HoneyLight)
{
                                num4 *= this._honeyLightR * (float)fastRandom.Next(98, 100) * 0.01f;
                                goto IL_0155;
                            }
                            num4 *= this._wetLightR * (float)fastRandom.Next(98, 100) * 0.01f;
                            goto IL_0155;
                        }
                    }
                    if (!flag)
                    {
                        break;
                    }
                    flag = false;
                }
            }
            catch
            {
            }
        }
References Terraria.Graphics.Light.LegacyLighting._negLight, Terraria.Graphics.Light.LegacyLighting._negLight2, Terraria.Graphics.Light.LegacyLighting._negLight3, Terraria.Graphics.Light.LegacyLighting._swipeRandom, System.array, Terraria.Graphics.Light.LegacyLighting.LightingState.CrackedLight, Terraria.Graphics.Light.LegacyLighting.LightingState.HoneyLight, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop1End, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop1Start, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop2End, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.InnerLoop2Start, Terraria.Graphics.Light.LegacyLighting.LightingSwipeData.JaggedArray, Terraria.Utilities.FastRandom.Next(), Terraria.Graphics.Light.LegacyLighting.LightingState.R2, Terraria.Graphics.Light.LegacyLighting.LightingState.StopLight, Terraria.Graphics.Light.LegacyLighting.LightingState.WetLight, and Terraria.Utilities.FastRandom.WithModifier().
Referenced by Terraria.Graphics.Light.LegacyLighting.DoColors().