Terraria Decompiled: ReLogic.Peripherals.RGB.ChromaPipeline.ProcessDevice
ProcessDevice()
void ReLogic.Peripherals.RGB.ChromaPipeline.ProcessDevice (RgbDevice device, IEnumerable< ShaderOperation > shaders, float time) inline private
Definition at line 62 of file ChromaPipeline.cs.
        {
            Fragment fragment = device.Rasterize();
            if (shaders != null)
            {
                foreach (ShaderOperation shaderOperation in shaders)
                {
                    shaderOperation.Process(device, fragment, time);
                    device.Render(fragment, shaderOperation.BlendState);
                }
            }
            if (this._hotkeys != null)
            {
                RgbKeyboard rgbKeyboard = device as RgbKeyboard;
                if (rgbKeyboard != null)
                {
                    rgbKeyboard.Render(Enumerable.Where<RgbKey>(this._hotkeys, (RgbKey key) => key.IsVisible));
                }
            }
            if (this.PostProcessingEvents != null)
            {
                fragment.Clear();
                this.PostProcessingEvents(device, fragment, time);
                device.Render(fragment, new ShaderBlendState(BlendMode.PerPixelOpacity, 1f));
            }
        }
References ReLogic.Peripherals.RGB.ChromaPipeline._hotkeys, ReLogic.Peripherals.RGB.ShaderOperation.BlendState, ReLogic.Peripherals.RGB.Fragment.Clear(), System.key, ReLogic.Peripherals.RGB.ChromaPipeline.PostProcessingEvents, ReLogic.Peripherals.RGB.ShaderOperation.Process(), ReLogic.Peripherals.RGB.RgbDevice.Rasterize(), ReLogic.Peripherals.RGB.RgbDevice.Render(), and ReLogic.Peripherals.RGB.RgbKeyboard.Render().
Referenced by ReLogic.Peripherals.RGB.ChromaPipeline.Process().