Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadVibration
SetGamePadVibration()
static bool Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadVibration (int index, float leftMotor, float rightMotor) inline static
Definition at line 1168 of file SDL2_FNAPlatform.cs.
        {
            IntPtr intPtr = SDL2_FNAPlatform.INTERNAL_devices[index];
            return !(intPtr == IntPtr.Zero) && SDL.SDL_GameControllerRumble(intPtr, (ushort)(MathHelper.Clamp(leftMotor, 0f, 1f) * 65535f), (ushort)(MathHelper.Clamp(rightMotor, 0f, 1f) * 65535f), 0U) == 0;
        }
References Microsoft.Xna.Framework.MathHelper.Clamp(), System.index, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_devices, SDL2.SDL.SDL_GameControllerRumble(), Microsoft.Xna.Framework.Input.U, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().