Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.UpdateTouchPanelState
UpdateTouchPanelState()
static unsafe void Microsoft.Xna.Framework.SDL2_FNAPlatform.UpdateTouchPanelState () inline static
Definition at line 1407 of file SDL2_FNAPlatform.cs.
        {
            long num = SDL.SDL_GetTouchDevice(0);
            for (int i = 0; i < 8; i++)
            {
                SDL.SDL_Finger* ptr = (SDL.SDL_Finger*)(void*)SDL.SDL_GetTouchFinger(num, i);
                if (ptr == null)
                {
                    TouchPanel.SetFinger(i, -1, Vector2.Zero);
                }
                else
                {
                    TouchPanel.SetFinger(i, (int)ptr->id, new Vector2((float)Math.Round((double)(ptr->x * (float)TouchPanel.DisplayWidth)), (float)Math.Round((double)(ptr->y * (float)TouchPanel.DisplayHeight))));
                }
            }
        }
References Microsoft.Xna.Framework.Input.Touch.TouchPanel.DisplayHeight, Microsoft.Xna.Framework.Input.Touch.TouchPanel.DisplayWidth, System.Math.Round(), SDL2.SDL.SDL_GetTouchDevice(), SDL2.SDL.SDL_GetTouchFinger(), Microsoft.Xna.Framework.Input.Touch.TouchPanel.SetFinger(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().