Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.DisposeWindow
DisposeWindow()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.DisposeWindow (GameWindow window) inline static
Definition at line 207 of file SDL2_FNAPlatform.cs.
        {
            SDL.SDL_SetHintWithPriority("SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS", "0", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            if (Mouse.WindowHandle == window.Handle)
            {
                Mouse.WindowHandle = IntPtr.Zero;
            }
            if (TouchPanel.WindowHandle == window.Handle)
            {
                TouchPanel.WindowHandle = IntPtr.Zero;
            }
            if (TextInputEXT.WindowHandle == window.Handle)
            {
                TextInputEXT.WindowHandle = IntPtr.Zero;
            }
            SDL.SDL_DestroyWindow(window.Handle);
        }
References Microsoft.Xna.Framework.GameWindow.Handle, SDL2.SDL.SDL_DestroyWindow(), SDL2.SDL.SDL_SetHintWithPriority(), Microsoft.Xna.Framework.Input.Mouse.WindowHandle, Microsoft.Xna.Framework.Input.TextInputEXT.WindowHandle, Microsoft.Xna.Framework.Input.Touch.TouchPanel.WindowHandle, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().