Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadState
GetGamePadState()
static GamePadState Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadState (int index, GamePadDeadZone deadZoneMode) inline static
Definition at line 1050 of file SDL2_FNAPlatform.cs.
        {
            IntPtr intPtr = SDL2_FNAPlatform.INTERNAL_devices[index];
            if (intPtr == IntPtr.Zero)
            {
                return default(GamePadState);
            }
            Vector2 vector = new Vector2((float)SDL.SDL_GameControllerGetAxis(intPtr, SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_LEFTX) / 32767f, (float)SDL.SDL_GameControllerGetAxis(intPtr, SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_LEFTY) / -32767f);
            Vector2 vector2 = new Vector2((float)SDL.SDL_GameControllerGetAxis(intPtr, SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_RIGHTX) / 32767f, (float)SDL.SDL_GameControllerGetAxis(intPtr, SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_RIGHTY) / -32767f);
            float num = (float)SDL.SDL_GameControllerGetAxis(intPtr, SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_TRIGGERLEFT) / 32767f;
            float num2 = (float)SDL.SDL_GameControllerGetAxis(intPtr, SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_TRIGGERRIGHT) / 32767f;
            Buttons buttons = (Buttons)0;
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_A) != 0)
            {
                buttons |= Buttons.A;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_B) != 0)
            {
                buttons |= Buttons.B;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_X) != 0)
            {
                buttons |= Buttons.X;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_Y) != 0)
            {
                buttons |= Buttons.Y;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_BACK) != 0)
            {
                buttons |= Buttons.Back;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_GUIDE) != 0)
            {
                buttons |= Buttons.BigButton;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_START) != 0)
            {
                buttons |= Buttons.Start;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_LEFTSTICK) != 0)
            {
                buttons |= Buttons.LeftStick;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_RIGHTSTICK) != 0)
            {
                buttons |= Buttons.RightStick;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_LEFTSHOULDER) != 0)
            {
                buttons |= Buttons.LeftShoulder;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_RIGHTSHOULDER) != 0)
            {
                buttons |= Buttons.RightShoulder;
            }
            ButtonState buttonState = ButtonState.Released;
            ButtonState buttonState2 = ButtonState.Released;
            ButtonState buttonState3 = ButtonState.Released;
            ButtonState buttonState4 = ButtonState.Released;
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_UP) != 0)
            {
                buttons |= Buttons.DPadUp;
                buttonState = ButtonState.Pressed;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_DOWN) != 0)
            {
                buttons |= Buttons.DPadDown;
                buttonState2 = ButtonState.Pressed;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_LEFT) != 0)
            {
                buttons |= Buttons.DPadLeft;
                buttonState3 = ButtonState.Pressed;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_RIGHT) != 0)
            {
                buttons |= Buttons.DPadRight;
                buttonState4 = ButtonState.Pressed;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_MISC1) != 0)
            {
                buttons |= Buttons.Misc1EXT;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE1) != 0)
            {
                buttons |= Buttons.Paddle1EXT;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE2) != 0)
            {
                buttons |= Buttons.Paddle2EXT;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE3) != 0)
            {
                buttons |= Buttons.Paddle3EXT;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE4) != 0)
            {
                buttons |= Buttons.Paddle4EXT;
            }
            if (SDL.SDL_GameControllerGetButton(intPtr, SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_TOUCHPAD) != 0)
            {
                buttons |= Buttons.TouchPadEXT;
            }
            GamePadState gamePadState = new GamePadState(new GamePadThumbSticks(vector, vector2, deadZoneMode), new GamePadTriggers(num, num2, deadZoneMode), new GamePadButtons(buttons), new GamePadDPad(buttonState, buttonState2, buttonState3, buttonState4))
            {
                IsConnected = true,
                PacketNumber = SDL2_FNAPlatform.INTERNAL_states[index].PacketNumber
            };
            if (gamePadState != SDL2_FNAPlatform.INTERNAL_states[index])
            {
                gamePadState.PacketNumber++;
                SDL2_FNAPlatform.INTERNAL_states[index] = gamePadState;
            }
            return gamePadState;
        }
References System.index, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_devices, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_states, Microsoft.Xna.Framework.Input.GamePadState.PacketNumber, SDL2.SDL.SDL_GameControllerGetAxis(), SDL2.SDL.SDL_GameControllerGetButton(), Microsoft.Xna.Framework.Graphics.Vector2, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().