Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.SetRelativeMouseMode
SetRelativeMouseMode()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.SetRelativeMouseMode (IntPtr window, bool enable) inline static
Definition at line 837 of file SDL2_FNAPlatform.cs.
        {
            SDL.SDL_SetRelativeMouseMode(enable ? SDL.SDL_bool.SDL_TRUE : SDL.SDL_bool.SDL_FALSE);
            if (enable)
            {
                int num;
                SDL.SDL_GetRelativeMouseState(out num, out num);
            }
        }
References SDL2.SDL.SDL_GetRelativeMouseState(), and SDL2.SDL.SDL_SetRelativeMouseMode().
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().