Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMouseState
GetMouseState()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMouseState (IntPtr window, out int x, out int y, out ButtonState left, out ButtonState middle, out ButtonState right, out ButtonState x1, out ButtonState x2) inline static
Definition at line 797 of file SDL2_FNAPlatform.cs.
        {
            uint num;
            if (SDL2_FNAPlatform.GetRelativeMouseMode(window))
            {
                num = SDL.SDL_GetRelativeMouseState(out x, out y);
            }
            else if (SDL2_FNAPlatform.SupportsGlobalMouse)
            {
                num = SDL.SDL_GetGlobalMouseState(out x, out y);
                int num2 = 0;
                int num3 = 0;
                SDL.SDL_GetWindowPosition(window, out num2, out num3);
                x -= num2;
                y -= num3;
            }
            else
            {
                num = SDL.SDL_GetMouseState(out x, out y);
            }
            left = (ButtonState)(num & SDL.SDL_BUTTON_LMASK);
            middle = (ButtonState)((num & SDL.SDL_BUTTON_MMASK) >> 1);
            right = (ButtonState)((num & SDL.SDL_BUTTON_RMASK) >> 2);
            x1 = (ButtonState)((num & SDL.SDL_BUTTON_X1MASK) >> 3);
            x2 = (ButtonState)((num & SDL.SDL_BUTTON_X2MASK) >> 4);
        }
References Microsoft.Xna.Framework.SDL2_FNAPlatform.GetRelativeMouseMode(), SDL2.SDL.SDL_BUTTON_LMASK, SDL2.SDL.SDL_BUTTON_MMASK, SDL2.SDL.SDL_BUTTON_RMASK, SDL2.SDL.SDL_BUTTON_X1MASK, SDL2.SDL.SDL_BUTTON_X2MASK, SDL2.SDL.SDL_GetGlobalMouseState(), SDL2.SDL.SDL_GetMouseState(), SDL2.SDL.SDL_GetRelativeMouseState(), SDL2.SDL.SDL_GetWindowPosition(), and Microsoft.Xna.Framework.SDL2_FNAPlatform.SupportsGlobalMouse.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().