Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetKeyFromScancode
GetKeyFromScancode()
static Keys Microsoft.Xna.Framework.SDL2_FNAPlatform.GetKeyFromScancode (Keys scancode) inline static
Definition at line 1468 of file SDL2_FNAPlatform.cs.
        {
            if (SDL2_FNAPlatform.UseScancodes)
            {
                return scancode;
            }
            SDL.SDL_Scancode sdl_Scancode;
            if (SDL2_FNAPlatform.INTERNAL_xnaMap.TryGetValue((int)scancode, out sdl_Scancode))
            {
                SDL.SDL_Keycode sdl_Keycode = SDL.SDL_GetKeyFromScancode(sdl_Scancode);
                Keys keys;
                if (SDL2_FNAPlatform.INTERNAL_keyMap.TryGetValue((int)sdl_Keycode, out keys))
                {
                    return keys;
                }
                FNALoggerEXT.LogWarn("KEYCODE MISSING FROM SDL2->XNA DICTIONARY: " + sdl_Keycode.ToString());
            }
            else
            {
                FNALoggerEXT.LogWarn("SCANCODE MISSING FROM XNA->SDL2 DICTIONARY: " + scancode.ToString());
            }
            return Keys.None;
        }
References Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_keyMap, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_xnaMap, Microsoft.Xna.Framework.FNALoggerEXT.LogWarn, SDL2.SDL.SDL_GetKeyFromScancode(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and Microsoft.Xna.Framework.SDL2_FNAPlatform.UseScancodes.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().