Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGraphicsAdapters
GetGraphicsAdapters()
static GraphicsAdapter[] Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGraphicsAdapters () inline static
Definition at line 754 of file SDL2_FNAPlatform.cs.
        {
            SDL.SDL_DisplayMode sdl_DisplayMode = default(SDL.SDL_DisplayMode);
            GraphicsAdapter[] array = new GraphicsAdapter[SDL.SDL_GetNumVideoDisplays()];
            for (int i = 0; i < array.Length; i++)
            {
                List<DisplayMode> list = new List<DisplayMode>();
                for (int j = SDL.SDL_GetNumDisplayModes(i) - 1; j >= 0; j--)
                {
                    SDL.SDL_GetDisplayMode(i, j, out sdl_DisplayMode);
                    bool flag = false;
                    foreach (DisplayMode displayMode in list)
                    {
                        if (sdl_DisplayMode.w == displayMode.Width && sdl_DisplayMode.h == displayMode.Height)
{
                            flag = true;
                        }
                    }
                    if (!flag)
                    {
                        list.Add(new DisplayMode(sdl_DisplayMode.w, sdl_DisplayMode.h, SurfaceFormat.Color));
                    }
                }
                array[i] = new GraphicsAdapter(new DisplayModeCollection(list), "\\\\.\\DISPLAY" + (i + 1).ToString(), SDL.SDL_GetDisplayName(i));
            }
            return array;
        }
References System.array, SDL2.SDL.SDL_DisplayMode.h, Microsoft.Xna.Framework.Graphics.DisplayMode.Height, System.list, SDL2.SDL.SDL_GetDisplayMode(), SDL2.SDL.SDL_GetDisplayName(), SDL2.SDL.SDL_GetNumDisplayModes(), SDL2.SDL.SDL_GetNumVideoDisplays(), System.ToString, SDL2.SDL.SDL_DisplayMode.w, and Microsoft.Xna.Framework.Graphics.DisplayMode.Width.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().