Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetWindowBounds
GetWindowBounds()
static Rectangle Microsoft.Xna.Framework.SDL2_FNAPlatform.GetWindowBounds (IntPtr window) inline static
Definition at line 313 of file SDL2_FNAPlatform.cs.
        {
            Rectangle rectangle;
            if ((SDL.SDL_GetWindowFlags(window) & 1U) != 0U)
            {
                SDL.SDL_DisplayMode sdl_DisplayMode;
                SDL.SDL_GetCurrentDisplayMode(SDL.SDL_GetWindowDisplayIndex(window), out sdl_DisplayMode);
                rectangle.X = 0;
                rectangle.Y = 0;
                rectangle.Width = sdl_DisplayMode.w;
                rectangle.Height = sdl_DisplayMode.h;
            }
            else
            {
                SDL.SDL_GetWindowPosition(window, out rectangle.X, out rectangle.Y);
                SDL.SDL_GetWindowSize(window, out rectangle.Width, out rectangle.Height);
            }
            return rectangle;
        }
References SDL2.SDL.SDL_DisplayMode.h, Microsoft.Xna.Framework.Rectangle.Height, SDL2.SDL.SDL_GetCurrentDisplayMode(), SDL2.SDL.SDL_GetWindowDisplayIndex(), SDL2.SDL.SDL_GetWindowFlags(), SDL2.SDL.SDL_GetWindowPosition(), SDL2.SDL.SDL_GetWindowSize(), Microsoft.Xna.Framework.Input.U, SDL2.SDL.SDL_DisplayMode.w, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.ApplyWindowChanges(), and Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().