Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents
PollEvents()
static unsafe void Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents (Game game, ref GraphicsAdapter currentAdapter, bool[] textInputControlDown, ref bool textInputSuppress) inline static
Definition at line 510 of file SDL2_FNAPlatform.cs.
        {
            char* ptr = stackalloc char[(UIntPtr)64];
            SDL.SDL_Event sdl_Event;
            while (SDL.SDL_PollEvent(out sdl_Event) == 1)
            {
                if (sdl_Event.type == SDL.SDL_EventType.SDL_KEYDOWN)
                {
                    Keys keys = SDL2_FNAPlatform.ToXNAKey(ref sdl_Event.key.keysym);
                    if (!Keyboard.keys.Contains(keys))
                    {
                        Keyboard.keys.Add(keys);
                        int num;
                        if (FNAPlatform.TextInputBindings.TryGetValue(keys, out num))
{
                            textInputControlDown[num] = true;
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[num]);
                        }
                        else if ((Keyboard.keys.Contains(Keys.LeftControl) || Keyboard.keys.Contains(Keys.RightControl)) && keys == Keys.V)
{
                            textInputControlDown[6] = true;
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[6]);
                            textInputSuppress = true;
                        }
                    }
                    else if (sdl_Event.key.repeat > 0)
                    {
                        int num2;
                        if (FNAPlatform.TextInputBindings.TryGetValue(keys, out num2))
{
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[num2]);
                        }
                        else if ((Keyboard.keys.Contains(Keys.LeftControl) || Keyboard.keys.Contains(Keys.RightControl)) && keys == Keys.V)
{
                            TextInputEXT.OnTextInput(FNAPlatform.TextInputCharacters[6]);
                        }
                    }
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_KEYUP)
                {
                    Keys keys2 = SDL2_FNAPlatform.ToXNAKey(ref sdl_Event.key.keysym);
                    if (Keyboard.keys.Remove(keys2))
                    {
                        int num3;
                        if (FNAPlatform.TextInputBindings.TryGetValue(keys2, out num3))
{
                            textInputControlDown[num3] = false;
                        }
                        else if ((!Keyboard.keys.Contains(Keys.LeftControl) && !Keyboard.keys.Contains(Keys.RightControl) && textInputControlDown[6]) || keys2 == Keys.V)
{
                            textInputControlDown[6] = false;
                            textInputSuppress = false;
                        }
                    }
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_MOUSEBUTTONDOWN)
                {
                    Mouse.INTERNAL_onClicked((int)(sdl_Event.button.button - 1));
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_MOUSEWHEEL)
                {
                    Mouse.INTERNAL_MouseWheel += sdl_Event.wheel.y * 120;
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_FINGERDOWN)
                {
                    TouchPanel.TouchDeviceExists = true;
                    TouchPanel.INTERNAL_onTouchEvent((int)sdl_Event.tfinger.fingerId, TouchLocationState.Pressed, sdl_Event.tfinger.x, sdl_Event.tfinger.y, 0f, 0f);
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_FINGERMOTION)
                {
                    TouchPanel.INTERNAL_onTouchEvent((int)sdl_Event.tfinger.fingerId, TouchLocationState.Moved, sdl_Event.tfinger.x, sdl_Event.tfinger.y, sdl_Event.tfinger.dx, sdl_Event.tfinger.dy);
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_FINGERUP)
                {
                    TouchPanel.INTERNAL_onTouchEvent((int)sdl_Event.tfinger.fingerId, TouchLocationState.Released, sdl_Event.tfinger.x, sdl_Event.tfinger.y, 0f, 0f);
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_WINDOWEVENT)
                {
                    if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_FOCUS_GAINED)
                    {
                        game.IsActive = true;
                        if (SDL.SDL_GetCurrentVideoDriver() == "x11")
{
                            SDL.SDL_SetWindowFullscreen(game.Window.Handle, game.GraphicsDevice.PresentationParameters.IsFullScreen ? 4097U : 0U);
                        }
                        SDL.SDL_DisableScreenSaver();
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_FOCUS_LOST)
                    {
                        game.IsActive = false;
                        if (SDL.SDL_GetCurrentVideoDriver() == "x11")
{
                            SDL.SDL_SetWindowFullscreen(game.Window.Handle, 0U);
                        }
                        SDL.SDL_EnableScreenSaver();
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_SIZE_CHANGED)
                    {
                        Mouse.INTERNAL_WindowWidth = sdl_Event.window.data1;
                        Mouse.INTERNAL_WindowHeight = sdl_Event.window.data2;
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_RESIZED)
                    {
                        uint num4 = SDL.SDL_GetWindowFlags(game.Window.Handle);
                        if ((num4 & 32U) != 0U && (num4 & 1536U) != 0U)
{
                            ((FNAWindow)game.Window).INTERNAL_ClientSizeChanged();
                        }
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_EXPOSED)
                    {
                        game.RedrawWindow();
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_MOVED)
                    {
                        int num5 = SDL.SDL_GetWindowDisplayIndex(game.Window.Handle);
                        if (num5 >= GraphicsAdapter.Adapters.Count)
{
                            GraphicsAdapter.AdaptersChanged();
                        }
                        if (GraphicsAdapter.Adapters[num5] != currentAdapter)
{
                            currentAdapter = GraphicsAdapter.Adapters[num5];
                            game.GraphicsDevice.Reset(game.GraphicsDevice.PresentationParameters, currentAdapter);
                        }
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_ENTER)
                    {
                        SDL.SDL_DisableScreenSaver();
                    }
                    else if (sdl_Event.window.windowEvent == SDL.SDL_WindowEventID.SDL_WINDOWEVENT_LEAVE)
                    {
                        SDL.SDL_EnableScreenSaver();
                    }
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_DISPLAYEVENT)
                {
                    GraphicsAdapter.AdaptersChanged();
                    int num6 = SDL.SDL_GetWindowDisplayIndex(game.Window.Handle);
                    currentAdapter = GraphicsAdapter.Adapters[num6];
                    if (sdl_Event.display.displayEvent == SDL.SDL_DisplayEventID.SDL_DISPLAYEVENT_ORIENTATION)
                    {
                        if (SDL2_FNAPlatform.SupportsOrientationChanges())
{
                            SDL2_FNAPlatform.INTERNAL_HandleOrientationChange(SDL2_FNAPlatform.INTERNAL_ConvertOrientation((SDL.SDL_DisplayOrientation)sdl_Event.display.data1), game.GraphicsDevice, currentAdapter, (FNAWindow)game.Window);
                        }
                    }
                    else
                    {
                        game.GraphicsDevice.QuietlyUpdateAdapter(currentAdapter);
                    }
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_CONTROLLERDEVICEADDED)
                {
                    SDL2_FNAPlatform.INTERNAL_AddInstance(sdl_Event.cdevice.which);
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_CONTROLLERDEVICEREMOVED)
                {
                    SDL2_FNAPlatform.INTERNAL_RemoveInstance(sdl_Event.cdevice.which);
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_TEXTINPUT && !textInputSuppress)
                {
                    int num7 = SDL2_FNAPlatform.MeasureStringLength(&sdl_Event.text.text.FixedElementField);
                    if (num7 > 0)
                    {
                        int chars = Encoding.UTF8.GetChars(&sdl_Event.text.text.FixedElementField, num7, ptr, num7);
                        for (int i = 0; i < chars; i++)
{
                            TextInputEXT.OnTextInput(ptr[i]);
                        }
                    }
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_TEXTEDITING)
                {
                    int num8 = SDL2_FNAPlatform.MeasureStringLength(&sdl_Event.edit.text.FixedElementField);
                    if (num8 > 0)
                    {
                        int chars2 = Encoding.UTF8.GetChars(&sdl_Event.edit.text.FixedElementField, num8, ptr, num8);
                        TextInputEXT.OnTextEditing(new string(ptr, 0, chars2), sdl_Event.edit.start, sdl_Event.edit.length);
                    }
                    else
                    {
                        TextInputEXT.OnTextEditing(null, 0, 0);
                    }
                }
                else if (sdl_Event.type == SDL.SDL_EventType.SDL_QUIT)
                {
                    game.RunApplication = false;
                    return;
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.Adapters, Microsoft.Xna.Framework.Graphics.GraphicsAdapter.AdaptersChanged(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Contains(), System.Text.Encoding.GetChars(), Microsoft.Xna.Framework.Game.GraphicsDevice, Microsoft.Xna.Framework.GameWindow.Handle, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_AddInstance(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_ConvertOrientation(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_HandleOrientationChange(), Microsoft.Xna.Framework.Input.Mouse.INTERNAL_onClicked(), Microsoft.Xna.Framework.Input.Touch.TouchPanel.INTERNAL_onTouchEvent(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_RemoveInstance(), Microsoft.Xna.Framework.Graphics.PresentationParameters.IsFullScreen, Microsoft.Xna.Framework.Input.Keyboard.keys, Microsoft.Xna.Framework.SDL2_FNAPlatform.MeasureStringLength(), Microsoft.Xna.Framework.Input.TextInputEXT.OnTextEditing(), Microsoft.Xna.Framework.Input.TextInputEXT.OnTextInput(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, Microsoft.Xna.Framework.Graphics.GraphicsDevice.QuietlyUpdateAdapter(), Microsoft.Xna.Framework.Game.RedrawWindow(), System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Reset(), SDL2.SDL.SDL_DisableScreenSaver(), SDL2.SDL.SDL_EnableScreenSaver(), SDL2.SDL.SDL_GetCurrentVideoDriver(), SDL2.SDL.SDL_GetWindowDisplayIndex(), SDL2.SDL.SDL_GetWindowFlags(), SDL2.SDL.SDL_PollEvent(), SDL2.SDL.SDL_SetWindowFullscreen(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SupportsOrientationChanges(), Microsoft.Xna.Framework.FNAPlatform.TextInputBindings, Microsoft.Xna.Framework.FNAPlatform.TextInputCharacters, Microsoft.Xna.Framework.SDL2_FNAPlatform.ToXNAKey(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Input.U, System.Text.Encoding.UTF8, and Microsoft.Xna.Framework.Game.Window.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().