Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_AddInstance
INTERNAL_AddInstance()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_AddInstance (int dev) inline static private
Definition at line 1249 of file SDL2_FNAPlatform.cs.
        {
            int num = -1;
            for (int i = 0; i < SDL2_FNAPlatform.INTERNAL_devices.Length; i++)
            {
                if (SDL2_FNAPlatform.INTERNAL_devices[i] == IntPtr.Zero)
                {
                    num = i;
                    break;
                }
            }
            if (num == -1)
            {
                return;
            }
            SDL.SDL_ClearError();
            SDL2_FNAPlatform.INTERNAL_devices[num] = SDL.SDL_GameControllerOpen(dev);
            IntPtr intPtr = SDL.SDL_GameControllerGetJoystick(SDL2_FNAPlatform.INTERNAL_devices[num]);
            int num2 = SDL.SDL_JoystickInstanceID(intPtr);
            if (SDL2_FNAPlatform.INTERNAL_instanceList.ContainsKey(num2))
            {
                SDL2_FNAPlatform.INTERNAL_devices[num] = IntPtr.Zero;
                return;
            }
            SDL2_FNAPlatform.INTERNAL_instanceList.Add(num2, num);
            SDL2_FNAPlatform.INTERNAL_states[num] = default(GamePadState);
            SDL2_FNAPlatform.INTERNAL_states[num].IsConnected = true;
            bool flag = SDL.SDL_GameControllerRumble(SDL2_FNAPlatform.INTERNAL_devices[num], 0, 0, 0U) == 0;
            bool flag2 = SDL.SDL_GameControllerRumbleTriggers(SDL2_FNAPlatform.INTERNAL_devices[num], 0, 0, 0U) == 0;
            GamePadCapabilities gamePadCapabilities = default(GamePadCapabilities);
            gamePadCapabilities.IsConnected = true;
            gamePadCapabilities.GamePadType = SDL2_FNAPlatform.INTERNAL_gamepadType[(int)SDL.SDL_JoystickGetType(intPtr)];
            gamePadCapabilities.HasAButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_A).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasBButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_B).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasXButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_X).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasYButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_Y).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasBackButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_BACK).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasBigButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_GUIDE).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasStartButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_START).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasLeftStickButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_LEFTSTICK).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasRightStickButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_RIGHTSTICK).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasLeftShoulderButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_LEFTSHOULDER).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasRightShoulderButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_RIGHTSHOULDER).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasDPadUpButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_UP).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasDPadDownButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_DOWN).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasDPadLeftButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_LEFT).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasDPadRightButton = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_DPAD_RIGHT).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasLeftXThumbStick = SDL.SDL_GameControllerGetBindForAxis(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_LEFTX).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasLeftYThumbStick = SDL.SDL_GameControllerGetBindForAxis(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_LEFTY).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasRightXThumbStick = SDL.SDL_GameControllerGetBindForAxis(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_RIGHTX).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasRightYThumbStick = SDL.SDL_GameControllerGetBindForAxis(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_RIGHTY).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasLeftTrigger = SDL.SDL_GameControllerGetBindForAxis(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_TRIGGERLEFT).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasRightTrigger = SDL.SDL_GameControllerGetBindForAxis(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerAxis.SDL_CONTROLLER_AXIS_TRIGGERRIGHT).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasLeftVibrationMotor = flag;
            gamePadCapabilities.HasRightVibrationMotor = flag;
            gamePadCapabilities.HasVoiceSupport = false;
            gamePadCapabilities.HasLightBarEXT = SDL.SDL_GameControllerHasLED(SDL2_FNAPlatform.INTERNAL_devices[num]) == SDL.SDL_bool.SDL_TRUE;
            gamePadCapabilities.HasTriggerVibrationMotorsEXT = flag2;
            gamePadCapabilities.HasMisc1EXT = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_MISC1).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasPaddle1EXT = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE1).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasPaddle2EXT = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE2).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasPaddle3EXT = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE3).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasPaddle4EXT = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_PADDLE4).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasTouchPadEXT = SDL.SDL_GameControllerGetBindForButton(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_GameControllerButton.SDL_CONTROLLER_BUTTON_TOUCHPAD).bindType > SDL.SDL_GameControllerBindType.SDL_CONTROLLER_BINDTYPE_NONE;
            gamePadCapabilities.HasGyroEXT = SDL.SDL_GameControllerHasSensor(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_SensorType.SDL_SENSOR_GYRO) == SDL.SDL_bool.SDL_TRUE;
            gamePadCapabilities.HasAccelerometerEXT = SDL.SDL_GameControllerHasSensor(SDL2_FNAPlatform.INTERNAL_devices[num], SDL.SDL_SensorType.SDL_SENSOR_ACCEL) == SDL.SDL_bool.SDL_TRUE;
            SDL2_FNAPlatform.INTERNAL_capabilities[num] = gamePadCapabilities;
            ushort num3 = SDL.SDL_JoystickGetVendor(intPtr);
            ushort num4 = SDL.SDL_JoystickGetProduct(intPtr);
            if (num3 == 0 && num4 == 0)
            {
                SDL2_FNAPlatform.INTERNAL_guids[num] = "xinput";
            }
            else
            {
                SDL2_FNAPlatform.INTERNAL_guids[num] = string.Format("{0:x2}{1:x2}{2:x2}{3:x2}", new object[]
                {
                    (int)(num3 & 255),
                    num3 >> 8,
                    (int)(num4 & 255),
                    num4 >> 8
                });
            }
            if (num3 == 10462)
            {
                SDL.SDL_GameControllerType sdl_GameControllerType = SDL.SDL_GameControllerGetType(SDL2_FNAPlatform.INTERNAL_devices[num]);
                if (sdl_GameControllerType == SDL.SDL_GameControllerType.SDL_CONTROLLER_TYPE_XBOX360 || sdl_GameControllerType == SDL.SDL_GameControllerType.SDL_CONTROLLER_TYPE_XBOXONE)
                {
                    SDL2_FNAPlatform.INTERNAL_guids[num] = "xinput";
                }
                else if (sdl_GameControllerType == SDL.SDL_GameControllerType.SDL_CONTROLLER_TYPE_PS4)
                {
                    SDL2_FNAPlatform.INTERNAL_guids[num] = "4c05c405";
                }
                else if (sdl_GameControllerType == SDL.SDL_GameControllerType.SDL_CONTROLLER_TYPE_PS5)
                {
                    SDL2_FNAPlatform.INTERNAL_guids[num] = "4c05e60c";
                }
            }
            string text = SDL.SDL_GameControllerMapping(SDL2_FNAPlatform.INTERNAL_devices[num]);
            string text2;
            if (string.IsNullOrEmpty(text))
            {
                text2 = "Mapping not found";
            }
            else
            {
                text2 = "Mapping: " + text;
            }
            FNALoggerEXT.LogInfo(string.Concat(new string[]
            {
                "Controller ",
                num.ToString(),
                ": ",
                SDL.SDL_GameControllerName(SDL2_FNAPlatform.INTERNAL_devices[num]),
                ", GUID: ",
                SDL2_FNAPlatform.INTERNAL_guids[num],
                ", ",
                text2
            }));
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), int, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_capabilities, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_devices, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_gamepadType, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_guids, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_instanceList, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_states, Microsoft.Xna.Framework.Input.GamePadState.IsConnected, Microsoft.Xna.Framework.FNALoggerEXT.LogInfo, SDL2.SDL.SDL_ClearError(), SDL2.SDL.SDL_GameControllerGetBindForAxis(), SDL2.SDL.SDL_GameControllerGetBindForButton(), SDL2.SDL.SDL_GameControllerGetJoystick(), SDL2.SDL.SDL_GameControllerGetType(), SDL2.SDL.SDL_GameControllerHasLED(), SDL2.SDL.SDL_GameControllerHasSensor(), SDL2.SDL.SDL_GameControllerMapping(), SDL2.SDL.SDL_GameControllerName(), SDL2.SDL.SDL_GameControllerOpen(), SDL2.SDL.SDL_GameControllerRumble(), SDL2.SDL.SDL_GameControllerRumbleTriggers(), SDL2.SDL.SDL_JoystickGetProduct(), SDL2.SDL.SDL_JoystickGetType(), SDL2.SDL.SDL_JoystickGetVendor(), SDL2.SDL.SDL_JoystickInstanceID(), System.text, Microsoft.Xna.Framework.Input.U, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), and Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit().