Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMicrophones
GetMicrophones()
static Microphone[] Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMicrophones () inline static
Definition at line 983 of file SDL2_FNAPlatform.cs.
        {
            if (!SDL2_FNAPlatform.micInit)
            {
                SDL.SDL_InitSubSystem(16U);
                SDL2_FNAPlatform.micInit = true;
            }
            int num = SDL.SDL_GetNumAudioDevices(1);
            if (num < 1)
            {
                return new Microphone[0];
            }
            Microphone[] array = new Microphone[num + 1];
            SDL.SDL_AudioSpec sdl_AudioSpec = default(SDL.SDL_AudioSpec);
            sdl_AudioSpec.freq = 44100;
            sdl_AudioSpec.format = 32784;
            sdl_AudioSpec.channels = 1;
            sdl_AudioSpec.samples = 4096;
            SDL.SDL_AudioSpec sdl_AudioSpec2;
            array[0] = new Microphone(SDL.SDL_OpenAudioDevice(null, 1, ref sdl_AudioSpec, out sdl_AudioSpec2, 0), "Default Device");
            for (int i = 0; i < num; i++)
            {
                string text = SDL.SDL_GetAudioDeviceName(i, 1);
                array[i + 1] = new Microphone(SDL.SDL_OpenAudioDevice(text, 1, ref sdl_AudioSpec, out sdl_AudioSpec2, 0), text);
            }
            return array;
        }
References System.array, Microsoft.Xna.Framework.SDL2_FNAPlatform.micInit, SDL2.SDL.SDL_GetAudioDeviceName(), SDL2.SDL.SDL_GetNumAudioDevices(), SDL2.SDL.SDL_InitSubSystem(), SDL2.SDL.SDL_OpenAudioDevice(), System.text, and Microsoft.Xna.Framework.Input.U.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().