Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.MonoPathRootWorkaround
MonoPathRootWorkaround()
static string Microsoft.Xna.Framework.SDL2_FNAPlatform.MonoPathRootWorkaround (string storageRoot) inline static private
Definition at line 920 of file SDL2_FNAPlatform.cs.
        {
            if (Environment.OSVersion.Platform == PlatformID.Win32NT)
            {
                return Path.GetPathRoot(storageRoot);
            }
            if (storageRoot == null)
            {
                return null;
            }
            if (storageRoot.Trim().Length == 0)
            {
                throw new ArgumentException("The specified path is not of a legal form.");
            }
            if (!Path.IsPathRooted(storageRoot) && !storageRoot.Contains(":"))
            {
                return string.Empty;
            }
            int num = -1;
            int num2 = 0;
            string[] logicalDrives = Environment.GetLogicalDrives();
            for (int i = 0; i < logicalDrives.Length; i++)
            {
                if (!string.IsNullOrEmpty(logicalDrives[i]))
                {
                    string text = logicalDrives[i];
                    if (text[text.Length - 1] != Path.DirectorySeparatorChar)
                    {
                        text += Path.DirectorySeparatorChar.ToString();
                    }
                    if (storageRoot.StartsWith(text) && text.Length > num2)
                    {
                        num = i;
                        num2 = text.Length;
                    }
                }
            }
            if (num >= 0)
            {
                return logicalDrives[num];
            }
            return Path.GetPathRoot(storageRoot);
        }
References System.IO.Path.DirectorySeparatorChar, System.IO.Path.GetPathRoot(), System.IO.Path.IsPathRooted(), and System.text.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.GetDriveInfo().