Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_SetIcon
INTERNAL_SetIcon()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_SetIcon (IntPtr window, string title) inline static private
Definition at line 370 of file SDL2_FNAPlatform.cs.
        {
            string text = string.Empty;
            try
            {
                text = SDL2_FNAPlatform.INTERNAL_GetIconName(title + ".png");
                if (!string.IsNullOrEmpty(text))
                {
                    IntPtr intPtr;
                    IntPtr intPtr2;
                    using (Stream stream = TitleContainer.OpenStream(text))
                    {
                        int num;
                        int num2;
                        int num3;
                        intPtr = FNA3D.ReadImageStream(stream, out num, out num2, out num3, -1, -1, false);
                        intPtr2 = SDL.SDL_CreateRGBSurfaceFrom(intPtr, num, num2, 32, num * 4, 255U, 65280U, 16711680U, 4278190080U);
                    }
                    SDL.SDL_SetWindowIcon(window, intPtr2);
                    SDL.SDL_FreeSurface(intPtr2);
                    FNA3D.FNA3D_Image_Free(intPtr);
                    return;
                }
            }
            catch (DllNotFoundException)
            {
            }
            text = SDL2_FNAPlatform.INTERNAL_GetIconName(title + ".bmp");
            if (!string.IsNullOrEmpty(text))
            {
                IntPtr intPtr3 = SDL.SDL_LoadBMP(text);
                SDL.SDL_SetWindowIcon(window, intPtr3);
                SDL.SDL_FreeSurface(intPtr3);
            }
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_Image_Free(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_GetIconName(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream(), SDL2.SDL.SDL_CreateRGBSurfaceFrom(), SDL2.SDL.SDL_FreeSurface(), SDL2.SDL.SDL_LoadBMP(), SDL2.SDL.SDL_SetWindowIcon(), System.text, and Microsoft.Xna.Framework.Input.U.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow().