Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow
CreateWindow()
static GameWindow Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow () inline static
Definition at line 168 of file SDL2_FNAPlatform.cs.
        {
            SDL.SDL_WindowFlags sdl_WindowFlags = (SDL.SDL_WindowFlags)(1544U | FNA3D.FNA3D_PrepareWindowAttributes());
            if ((sdl_WindowFlags & SDL.SDL_WindowFlags.SDL_WINDOW_VULKAN) == SDL.SDL_WindowFlags.SDL_WINDOW_VULKAN && SDL.SDL_GetHint("FNA3D_VULKAN_PIPELINE_CACHE_FILE_NAME") == null)
            {
                string text2;
                if (SDL2_FNAPlatform.OSVersion.Equals("Windows") || SDL2_FNAPlatform.OSVersion.Equals("Mac OS X") || SDL2_FNAPlatform.OSVersion.Equals("Linux") || SDL2_FNAPlatform.OSVersion.Equals("FreeBSD") || SDL2_FNAPlatform.OSVersion.Equals("OpenBSD") || SDL2_FNAPlatform.OSVersion.Equals("NetBSD"))
                {
                    string text = Path.GetFileNameWithoutExtension(AppDomain.CurrentDomain.FriendlyName).Replace(".vshost", "");
                    text2 = Path.Combine(SDL.SDL_GetPrefPath(null, "FNA3D"), text + "_Vulkan_PipelineCache.blob");
                }
                else
                {
                    text2 = string.Empty;
                }
                SDL.SDL_SetHint("FNA3D_VULKAN_PIPELINE_CACHE_FILE_NAME", text2);
            }
            if (Environment.GetEnvironmentVariable("FNA_GRAPHICS_ENABLE_HIGHDPI") == "1")
            {
                sdl_WindowFlags |= SDL.SDL_WindowFlags.SDL_WINDOW_ALLOW_HIGHDPI;
            }
            string defaultWindowTitle = AssemblyHelper.GetDefaultWindowTitle();
            IntPtr intPtr = SDL.SDL_CreateWindow(defaultWindowTitle, 805240832, 805240832, GraphicsDeviceManager.DefaultBackBufferWidth, GraphicsDeviceManager.DefaultBackBufferHeight, sdl_WindowFlags);
            if (intPtr == IntPtr.Zero)
            {
                throw new NoSuitableGraphicsDeviceException(SDL.SDL_GetError());
            }
            SDL2_FNAPlatform.INTERNAL_SetIcon(intPtr, defaultWindowTitle);
            SDL.SDL_DisableScreenSaver();
            SDL2_FNAPlatform.OnIsMouseVisibleChanged(false);
            sdl_WindowFlags = (SDL.SDL_WindowFlags)SDL.SDL_GetWindowFlags(intPtr);
            if ((sdl_WindowFlags & SDL.SDL_WindowFlags.SDL_WINDOW_ALLOW_HIGHDPI) == (SDL.SDL_WindowFlags)0U)
            {
                Environment.SetEnvironmentVariable("FNA_GRAPHICS_ENABLE_HIGHDPI", "0");
            }
            return new FNAWindow(intPtr, "\\\\.\\DISPLAY" + (SDL.SDL_GetWindowDisplayIndex(intPtr) + 1).ToString());
        }
References System.IO.Path.Combine(), System.AppDomain.CurrentDomain, Microsoft.Xna.Framework.GraphicsDeviceManager.DefaultBackBufferHeight, Microsoft.Xna.Framework.GraphicsDeviceManager.DefaultBackBufferWidth, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_PrepareWindowAttributes(), System.AppDomain.FriendlyName, MonoGame.Utilities.AssemblyHelper.GetDefaultWindowTitle(), System.IO.Path.GetFileNameWithoutExtension(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_SetIcon(), Microsoft.Xna.Framework.SDL2_FNAPlatform.OnIsMouseVisibleChanged(), Microsoft.Xna.Framework.SDL2_FNAPlatform.OSVersion, SDL2.SDL.SDL_CreateWindow(), SDL2.SDL.SDL_DisableScreenSaver(), SDL2.SDL.SDL_GetError(), SDL2.SDL.SDL_GetHint(), SDL2.SDL.SDL_GetPrefPath(), SDL2.SDL.SDL_GetWindowDisplayIndex(), SDL2.SDL.SDL_GetWindowFlags(), SDL2.SDL.SDL_SetHint(), System.text, System.IntPtr.ToString(), Microsoft.Xna.Framework.Input.U, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().