Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit
ProgramInit()
static unsafe string Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit (LaunchParameters args) inline static
Definition at line 21 of file SDL2_FNAPlatform.cs.
        {
            try
            {
                SDL2_FNAPlatform.OSVersion = SDL.SDL_GetPlatform();
            }
            catch (DllNotFoundException)
            {
                FNALoggerEXT.LogError("SDL2 was not found! Do you have fnalibs?");
                throw;
            }
            catch (BadImageFormatException ex)
            {
                string text = string.Format("This process is {0}-bit, the DLL is {1}-bit!", (IntPtr.Size == 4) ? "32" : "64", (IntPtr.Size == 4) ? "64" : "32");
                FNALoggerEXT.LogError(text);
                throw new BadImageFormatException(text, ex);
            }
            SDL.SDL_SetMainReady();
            if (SDL2_FNAPlatform.OSVersion.Equals("Windows") && Debugger.IsAttached)
            {
                SDL.SDL_SetHint("SDL_WINDOWS_DISABLE_THREAD_NAMING", "1");
            }
            string baseDirectory = SDL2_FNAPlatform.GetBaseDirectory();
            string text2 = Path.Combine(baseDirectory, "gamecontrollerdb.txt");
            if (File.Exists(text2))
            {
                SDL.SDL_SetHint("SDL_GAMECONTROLLERCONFIG_FILE", text2);
            }
            string text3 = ((Environment.GetEnvironmentVariable("FNA_GAMEPAD_IGNORE_PHYSICAL_LAYOUT") == "1") ? "1" : "0");
            SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_USE_BUTTON_LABELS", text3, SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            if (Environment.GetEnvironmentVariable("FNA_NUKE_STEAM_INPUT") == "1")
            {
                SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_IGNORE_DEVICES", "0x28DE/0x11FF", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_IGNORE_DEVICES_EXCEPT", "", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                SDL.SDL_SetHintWithPriority("SDL_GAMECONTROLLER_ALLOW_STEAM_VIRTUAL_GAMEPAD", "0", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            string text4;
            if (args.TryGetValue("glprofile", out text4))
            {
                if (text4 == "es3")
                {
                    SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_ES3", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                }
                else if (text4 == "core")
                {
                    SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_CORE_PROFILE", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                }
                else if (text4 == "compatibility")
                {
                    SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_COMPATIBILITY_PROFILE", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                }
            }
            if (args.TryGetValue("angle", out text4) && text4 == "1")
            {
                SDL.SDL_SetHintWithPriority("FNA3D_OPENGL_FORCE_ES3", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
                SDL.SDL_SetHintWithPriority("SDL_OPENGL_ES_DRIVER", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            if (args.TryGetValue("forcemailboxvsync", out text4) && text4 == "1")
            {
                SDL.SDL_SetHintWithPriority("FNA3D_VULKAN_FORCE_MAILBOX_VSYNC", "1", SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            if (args.TryGetValue("audiodriver", out text4))
            {
                SDL.SDL_SetHintWithPriority("SDL_AUDIODRIVER", text4, SDL.SDL_HintPriority.SDL_HINT_OVERRIDE);
            }
            if (SDL.SDL_Init(8224U) != 0)
            {
                throw new Exception("SDL_Init failed: " + SDL.SDL_GetError());
            }
            string text5 = SDL.SDL_GetCurrentVideoDriver();
            SDL2_FNAPlatform.SupportsGlobalMouse = SDL2_FNAPlatform.OSVersion.Equals("Windows") || SDL2_FNAPlatform.OSVersion.Equals("Mac OS X") || text5.Equals("x11");
            if (Environment.GetEnvironmentVariable("FNA_MOUSE_DISABLE_GLOBAL_ACCESS") == "1")
            {
                SDL2_FNAPlatform.SupportsGlobalMouse = false;
            }
            SDL2_FNAPlatform.SupportsOrientations = SDL2_FNAPlatform.OSVersion.Equals("iOS") || SDL2_FNAPlatform.OSVersion.Equals("Android");
            if (!text5.Equals("wayland") && !text5.Equals("cocoa") && !text5.Equals("uikit"))
            {
                SDL.SDL_SetHintWithPriority("SDL_VIDEO_HIGHDPI_DISABLED", "1", SDL.SDL_HintPriority.SDL_HINT_NORMAL);
            }
            if (SDL2_FNAPlatform.OSVersion.Equals("Windows"))
            {
                SDL.SDL_SetHint("SDL_VIDEO_MINIMIZE_ON_FOCUS_LOSS", "1");
            }
            if (string.IsNullOrEmpty(SDL.SDL_GetHint("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS")))
            {
                SDL.SDL_SetHint("SDL_JOYSTICK_ALLOW_BACKGROUND_EVENTS", "1");
            }
            SDL.SDL_SetHint("SDL_IOS_ORIENTATIONS", "LandscapeLeft LandscapeRight Portrait");
            SDL.SDL_Event[] array = new SDL.SDL_Event[1];
            SDL.SDL_PumpEvents();
            while (SDL.SDL_PeepEvents(array, 1, SDL.SDL_eventaction.SDL_GETEVENT, SDL.SDL_EventType.SDL_CONTROLLERDEVICEADDED, SDL.SDL_EventType.SDL_CONTROLLERDEVICEADDED) == 1)
            {
                SDL2_FNAPlatform.INTERNAL_AddInstance(array[0].cdevice.which);
            }
            if (SDL2_FNAPlatform.OSVersion.Equals("Windows") && SDL.SDL_GetHint("FNA_WIN32_IGNORE_WM_PAINT") != "1")
            {
                IntPtr intPtr;
                SDL.SDL_GetEventFilter(out SDL2_FNAPlatform.prevEventFilter, out intPtr);
                SDL.SDL_SetEventFilter(SDL2_FNAPlatform.win32OnPaint, intPtr);
            }
            if (SDL.SDL_GetHint("SteamTesla") == "1")
            {
                IntPtr intPtr2 = SDL.SDL_LoadBMP("tesla.bmp");
                if (intPtr2 != IntPtr.Zero)
                {
                    SDL.SDL_Surface* ptr = (SDL.SDL_Surface*)(void*)intPtr2;
                    int w = ptr->w;
                    int h = ptr->h;
                    IntPtr intPtr3 = SDL.SDL_CreateWindow(null, 0, 0, w, h, (SDL.SDL_WindowFlags)0U);
                    if (intPtr3 != IntPtr.Zero)
                    {
                        ulong num = SDL.SDL_GetTicks64() + 2000UL;
                        do
{
                            IntPtr intPtr4 = SDL.SDL_GetWindowSurface(intPtr3);
                            SDL.SDL_BlitSurface(intPtr2, IntPtr.Zero, intPtr4, IntPtr.Zero);
                            SDL.SDL_UpdateWindowSurface(intPtr3);
                        }
                        while (SDL.SDL_GetTicks64() - num <= 0UL);
                        SDL.SDL_DestroyWindow(intPtr3);
                    }
                    SDL.SDL_FreeSurface(intPtr2);
                }
            }
            return baseDirectory;
        }
References System.array, System.IO.Path.Combine(), System.IO.File.Exists(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetBaseDirectory(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_AddInstance(), System.Diagnostics.Debugger.IsAttached, Microsoft.Xna.Framework.FNALoggerEXT.LogError, Microsoft.Xna.Framework.SDL2_FNAPlatform.OSVersion, Microsoft.Xna.Framework.SDL2_FNAPlatform.prevEventFilter, SDL2.SDL.SDL_BlitSurface(), SDL2.SDL.SDL_CreateWindow(), SDL2.SDL.SDL_DestroyWindow(), SDL2.SDL.SDL_FreeSurface(), SDL2.SDL.SDL_GetCurrentVideoDriver(), SDL2.SDL.SDL_GetError(), SDL2.SDL.SDL_GetEventFilter(), SDL2.SDL.SDL_GetHint(), SDL2.SDL.SDL_GetPlatform(), SDL2.SDL.SDL_GetTicks64(), SDL2.SDL.SDL_GetWindowSurface(), SDL2.SDL.SDL_Init(), SDL2.SDL.SDL_LoadBMP(), SDL2.SDL.SDL_PeepEvents(), SDL2.SDL.SDL_PumpEvents(), SDL2.SDL.SDL_SetEventFilter(), SDL2.SDL.SDL_SetHint(), SDL2.SDL.SDL_SetHintWithPriority(), SDL2.SDL.SDL_SetMainReady(), SDL2.SDL.SDL_UpdateWindowSurface(), System.IntPtr.Size, System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Input.U, Microsoft.Xna.Framework.SDL2_FNAPlatform.win32OnPaint, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().