Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadAccelerometer
GetGamePadAccelerometer()
static unsafe bool Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadAccelerometer (int index, out Vector3 accel) inline static
Definition at line 1224 of file SDL2_FNAPlatform.cs.
        {
            IntPtr intPtr = SDL2_FNAPlatform.INTERNAL_devices[index];
            if (intPtr == IntPtr.Zero)
            {
                accel = Vector3.Zero;
                return false;
            }
            if (SDL.SDL_GameControllerIsSensorEnabled(intPtr, SDL.SDL_SensorType.SDL_SENSOR_ACCEL) == SDL.SDL_bool.SDL_FALSE)
            {
                SDL.SDL_GameControllerSetSensorEnabled(intPtr, SDL.SDL_SensorType.SDL_SENSOR_ACCEL, SDL.SDL_bool.SDL_TRUE);
            }
            float* ptr = stackalloc float[(UIntPtr)12];
            if (SDL.SDL_GameControllerGetSensorData(intPtr, SDL.SDL_SensorType.SDL_SENSOR_ACCEL, (IntPtr)((void*)ptr), 3) < 0)
            {
                accel = Vector3.Zero;
                return false;
            }
            accel.X = *ptr;
            accel.Y = ptr[1];
            accel.Z = ptr[2];
            return true;
        }
References System.index, Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_devices, SDL2.SDL.SDL_GameControllerGetSensorData(), SDL2.SDL.SDL_GameControllerIsSensorEnabled(), SDL2.SDL.SDL_GameControllerSetSensorEnabled(), Microsoft.Xna.Framework.Vector3.Zero, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().