Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.GetDriveInfo
GetDriveInfo()
static DriveInfo Microsoft.Xna.Framework.SDL2_FNAPlatform.GetDriveInfo (string storageRoot) inline static
Definition at line 904 of file SDL2_FNAPlatform.cs.
        {
            DriveInfo driveInfo;
            try
            {
                driveInfo = new DriveInfo(SDL2_FNAPlatform.MonoPathRootWorkaround(storageRoot));
            }
            catch (Exception ex)
            {
                FNALoggerEXT.LogError("Failed to get DriveInfo: " + ex.ToString());
                driveInfo = null;
            }
            return driveInfo;
        }
References Microsoft.Xna.Framework.FNALoggerEXT.LogError, Microsoft.Xna.Framework.SDL2_FNAPlatform.MonoPathRootWorkaround(), and System.Exception.ToString().
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().