Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.ScaleForWindow
ScaleForWindow()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.ScaleForWindow (IntPtr window, bool invert, ref int w, ref int h) inline static
Definition at line 291 of file SDL2_FNAPlatform.cs.
        {
            int num;
            int num2;
            SDL.SDL_GetWindowSize(window, out num, out num2);
            int num3;
            int num4;
            FNA3D.FNA3D_GetDrawableSize(window, out num3, out num4);
            if (num != 0 && num2 != 0 && num3 != 0 && num4 != 0 && (num != num3 || num2 != num4))
            {
                if (invert)
                {
                    w = (int)((float)w * ((float)num3 / (float)num));
                    h = (int)((float)h * ((float)num4 / (float)num2));
                    return;
                }
                w = (int)((float)w / ((float)num3 / (float)num));
                h = (int)((float)h / ((float)num4 / (float)num2));
            }
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetDrawableSize(), int, and SDL2.SDL.SDL_GetWindowSize().
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.ApplyWindowChanges(), and Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().