Terraria Decompiled: Microsoft.Xna.Framework.SDL2_FNAPlatform.ApplyWindowChanges
ApplyWindowChanges()
static void Microsoft.Xna.Framework.SDL2_FNAPlatform.ApplyWindowChanges (IntPtr window, int clientWidth, int clientHeight, bool wantsFullscreen, string screenDeviceName, ref string resultDeviceName) inline static
Definition at line 226 of file SDL2_FNAPlatform.cs.
        {
            bool flag = false;
            SDL2_FNAPlatform.ScaleForWindow(window, false, ref clientWidth, ref clientHeight);
            if (!wantsFullscreen)
            {
                bool flag2;
                if ((SDL.SDL_GetWindowFlags(window) & 1U) != 0U)
                {
                    SDL.SDL_SetWindowFullscreen(window, 0U);
                    flag2 = true;
                }
                else
                {
                    int num;
                    int num2;
                    SDL.SDL_GetWindowSize(window, out num, out num2);
                    flag2 = clientWidth != num || clientHeight != num2;
                }
                if (flag2)
                {
                    SDL.SDL_RestoreWindow(window);
                    SDL.SDL_SetWindowSize(window, clientWidth, clientHeight);
                    flag = true;
                }
            }
            int num3 = 0;
            for (int i = 0; i < GraphicsAdapter.Adapters.Count; i++)
            {
                if (screenDeviceName == GraphicsAdapter.Adapters[i].DeviceName)
                {
                    num3 = i;
                    break;
                }
            }
            if (resultDeviceName != screenDeviceName)
            {
                SDL.SDL_SetWindowFullscreen(window, 0U);
                resultDeviceName = screenDeviceName;
                flag = true;
            }
            if (flag)
            {
                int num4 = SDL.SDL_WINDOWPOS_CENTERED_DISPLAY(num3);
                SDL.SDL_SetWindowPosition(window, num4, num4);
            }
            if (wantsFullscreen)
            {
                if ((SDL.SDL_GetWindowFlags(window) & 4U) == 0U)
                {
                    SDL.SDL_DisplayMode sdl_DisplayMode;
                    SDL.SDL_GetCurrentDisplayMode(num3, out sdl_DisplayMode);
                    SDL.SDL_SetWindowSize(window, sdl_DisplayMode.w, sdl_DisplayMode.h);
                }
                SDL.SDL_SetWindowFullscreen(window, 4097U);
            }
            if (Mouse.WindowHandle == window)
            {
                Rectangle windowBounds = SDL2_FNAPlatform.GetWindowBounds(window);
                Mouse.INTERNAL_WindowWidth = windowBounds.Width;
                Mouse.INTERNAL_WindowHeight = windowBounds.Height;
            }
        }
References Microsoft.Xna.Framework.Graphics.GraphicsAdapter.Adapters, Microsoft.Xna.Framework.SDL2_FNAPlatform.GetWindowBounds(), SDL2.SDL.SDL_DisplayMode.h, Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.SDL2_FNAPlatform.ScaleForWindow(), SDL2.SDL.SDL_GetCurrentDisplayMode(), SDL2.SDL.SDL_GetWindowFlags(), SDL2.SDL.SDL_GetWindowSize(), SDL2.SDL.SDL_RestoreWindow(), SDL2.SDL.SDL_SetWindowFullscreen(), SDL2.SDL.SDL_SetWindowPosition(), SDL2.SDL.SDL_SetWindowSize(), SDL2.SDL.SDL_WINDOWPOS_CENTERED_DISPLAY(), Microsoft.Xna.Framework.Input.U, SDL2.SDL.SDL_DisplayMode.w, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Input.Mouse.WindowHandle.
Referenced by Microsoft.Xna.Framework.FNAPlatform.FNAPlatform().