Terraria Decompiled: Ionic.Zlib.InflateCodes.Process
Process()
int Ionic.Zlib.InflateCodes.Process (InflateBlocks blocks, int r) inline package
Definition at line 27 of file InflateCodes.cs.
        {
            ZlibCodec codec = blocks._codec;
            int num = codec.NextIn;
            int num2 = codec.AvailableBytesIn;
            int num3 = blocks.bitb;
            int i = blocks.bitk;
            int num4 = blocks.writeAt;
            int num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
            for (;;)
            {
                int num6;
                switch (this.mode)
                {
                case 0:
                    if (num5 >= 258 && num2 >= 10)
                    {
                        blocks.bitb = num3;
                        blocks.bitk = i;
                        codec.AvailableBytesIn = num2;
                        codec.TotalBytesIn += (long)(num - codec.NextIn);
                        codec.NextIn = num;
                        blocks.writeAt = num4;
                        r = this.InflateFast((int)this.lbits, (int)this.dbits, this.ltree, this.ltree_index, this.dtree, this.dtree_index, blocks, codec);
                        num = codec.NextIn;
                        num2 = codec.AvailableBytesIn;
                        num3 = blocks.bitb;
                        i = blocks.bitk;
                        num4 = blocks.writeAt;
                        num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                        if (r != 0)
{
                            this.mode = ((r == 1) ? 7 : 9);
                            continue;
                        }
                    }
                    this.need = (int)this.lbits;
                    this.tree = this.ltree;
                    this.tree_index = this.ltree_index;
                    this.mode = 1;
                    goto IL_01AA;
                case 1:
                    goto IL_01AA;
                case 2:
                    num6 = this.bitsToGet;
                    while (i < num6)
                    {
                        if (num2 == 0)
{
                            goto IL_036A;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    this.len += num3 & InternalInflateConstants.InflateMask[num6];
                    num3 >>= num6;
                    i -= num6;
                    this.need = (int)this.dbits;
                    this.tree = this.dtree;
                    this.tree_index = this.dtree_index;
                    this.mode = 3;
                    goto IL_0434;
                case 3:
                    goto IL_0434;
                case 4:
                    num6 = this.bitsToGet;
                    while (i < num6)
                    {
                        if (num2 == 0)
{
                            goto IL_05C3;
                        }
                        r = 0;
                        num2--;
                        num3 |= (int)(codec.InputBuffer[num++] & byte.MaxValue) << i;
                        i += 8;
                    }
                    this.dist += num3 & InternalInflateConstants.InflateMask[num6];
                    num3 >>= num6;
                    i -= num6;
                    this.mode = 5;
                    goto IL_0669;
                case 5:
                    goto IL_0669;
                case 6:
                    if (num5 == 0)
                    {
                        if (num4 == blocks.end && blocks.readAt != 0)
{
                            num4 = 0;
                            num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                        }
                        if (num5 == 0)
{
                            blocks.writeAt = num4;
                            r = blocks.Flush(r);
                            num4 = blocks.writeAt;
                            num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                            if (num4 == blocks.end && blocks.readAt != 0)
{
                                num4 = 0;
                                num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                            }
                            if (num5 == 0)
{
                                goto Block_44;
                            }
                        }
                    }
                    r = 0;
                    blocks.window[num4++] = (byte)this.lit;
                    num5--;
                    this.mode = 0;
                    continue;
                case 7:
                    goto IL_0913;
                case 8:
                    goto IL_09C4;
                case 9:
                    goto IL_0A11;
                }
                break;
                IL_01AA:
                num6 = this.need;
                while (i < num6)
                {
                    if (num2 == 0)
                    {
                        goto IL_01BC;
                    }
                    r = 0;
                    num2--;
                    num3 |= (int)(codec.InputBuffer[num++] & byte.MaxValue) << i;
                    i += 8;
                }
                int num7 = (this.tree_index + (num3 & InternalInflateConstants.InflateMask[num6])) * 3;
                num3 >>= this.tree[num7 + 1];
                i -= this.tree[num7 + 1];
                int num8 = this.tree[num7];
                if (num8 == 0)
                {
                    this.lit = this.tree[num7 + 2];
                    this.mode = 6;
                    continue;
                }
                if ((num8 & 16) != 0)
                {
                    this.bitsToGet = num8 & 15;
                    this.len = this.tree[num7 + 2];
                    this.mode = 2;
                    continue;
                }
                if ((num8 & 64) == 0)
                {
                    this.need = num8;
                    this.tree_index = num7 / 3 + this.tree[num7 + 2];
                    continue;
                }
                if ((num8 & 32) != 0)
                {
                    this.mode = 7;
                    continue;
                }
                goto IL_02F6;
                IL_0434:
                num6 = this.need;
                while (i < num6)
                {
                    if (num2 == 0)
                    {
                        goto IL_0446;
                    }
                    r = 0;
                    num2--;
                    num3 |= (int)(codec.InputBuffer[num++] & byte.MaxValue) << i;
                    i += 8;
                }
                num7 = (this.tree_index + (num3 & InternalInflateConstants.InflateMask[num6])) * 3;
                num3 >>= this.tree[num7 + 1];
                i -= this.tree[num7 + 1];
                num8 = this.tree[num7];
                if ((num8 & 16) != 0)
                {
                    this.bitsToGet = num8 & 15;
                    this.dist = this.tree[num7 + 2];
                    this.mode = 4;
                    continue;
                }
                if ((num8 & 64) == 0)
                {
                    this.need = num8;
                    this.tree_index = num7 / 3 + this.tree[num7 + 2];
                    continue;
                }
                goto IL_054F;
                IL_0669:
                int j;
                for (j = num4 - this.dist; j < 0; j += blocks.end)
                {
                }
                while (this.len != 0)
                {
                    if (num5 == 0)
                    {
                        if (num4 == blocks.end && blocks.readAt != 0)
{
                            num4 = 0;
                            num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                        }
                        if (num5 == 0)
{
                            blocks.writeAt = num4;
                            r = blocks.Flush(r);
                            num4 = blocks.writeAt;
                            num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                            if (num4 == blocks.end && blocks.readAt != 0)
{
                                num4 = 0;
                                num5 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
                            }
                            if (num5 == 0)
{
                                goto Block_32;
                            }
                        }
                    }
                    blocks.window[num4++] = blocks.window[j++];
                    num5--;
                    if (j == blocks.end)
                    {
                        j = 0;
                    }
                    this.len--;
                }
                this.mode = 0;
            }
            r = -2;
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_01BC:
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_02F6:
            this.mode = 9;
            codec.Message = "invalid literal/length code";
            r = -3;
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_036A:
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_0446:
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_054F:
            this.mode = 9;
            codec.Message = "invalid distance code";
            r = -3;
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_05C3:
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            Block_32:
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            Block_44:
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_0913:
            if (i > 7)
            {
                i -= 8;
                num2++;
                num--;
            }
            blocks.writeAt = num4;
            r = blocks.Flush(r);
            num4 = blocks.writeAt;
            int num9 = ((num4 < blocks.readAt) ? (blocks.readAt - num4 - 1) : (blocks.end - num4));
            if (blocks.readAt != blocks.writeAt)
            {
                blocks.bitb = num3;
                blocks.bitk = i;
                codec.AvailableBytesIn = num2;
                codec.TotalBytesIn += (long)(num - codec.NextIn);
                codec.NextIn = num;
                blocks.writeAt = num4;
                return blocks.Flush(r);
            }
            this.mode = 8;
            IL_09C4:
            r = 1;
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
            IL_0A11:
            r = -3;
            blocks.bitb = num3;
            blocks.bitk = i;
            codec.AvailableBytesIn = num2;
            codec.TotalBytesIn += (long)(num - codec.NextIn);
            codec.NextIn = num;
            blocks.writeAt = num4;
            return blocks.Flush(r);
        }
References Ionic.Zlib.InflateBlocks._codec, Ionic.Zlib.ZlibCodec.AvailableBytesIn, Ionic.Zlib.InflateBlocks.bitb, Ionic.Zlib.InflateBlocks.bitk, Ionic.Zlib.InflateCodes.bitsToGet, Ionic.Zlib.InflateCodes.dbits, Ionic.Zlib.InflateCodes.dist, Ionic.Zlib.InflateCodes.dtree, Ionic.Zlib.InflateCodes.dtree_index, Ionic.Zlib.InflateBlocks.end, Ionic.Zlib.InflateBlocks.Flush(), Ionic.Zlib.InflateCodes.InflateFast(), Ionic.Zlib.InternalInflateConstants.InflateMask, Ionic.Zlib.ZlibCodec.InputBuffer, int, Ionic.Zlib.InflateCodes.lbits, Ionic.Zlib.InflateCodes.len, Ionic.Zlib.InflateCodes.lit, long, Ionic.Zlib.InflateCodes.ltree, Ionic.Zlib.InflateCodes.ltree_index, Ionic.Zlib.InflateCodes.mode, Ionic.Zlib.InflateCodes.need, Ionic.Zlib.ZlibCodec.NextIn, Ionic.Zlib.InflateBlocks.readAt, Ionic.Zlib.InflateCodes.tree, Ionic.Zlib.InflateBlocks.window, and Ionic.Zlib.InflateBlocks.writeAt.
Referenced by Ionic.Zlib.InflateBlocks.Process().