Terraria Decompiled: Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetGridParameters
GetGridParameters()
void Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetGridParameters (out int startX, out int startY, out int startItemIndex, out int endItemIndex) inline private
Definition at line 91 of file UIDynamicItemCollection.2.cs.
        {
            Rectangle rectangle = base.GetDimensions().ToRectangle();
            Rectangle viewCullingArea = base.Parent.GetViewCullingArea();
            int x = rectangle.Center.X;
            startX = x - (int)((float)(44 * this._itemsPerLine) * 0.5f);
            startY = rectangle.Top;
            startItemIndex = 0;
            endItemIndex = this._contents.Count;
            int num = (Math.Min(viewCullingArea.Top, rectangle.Top) - viewCullingArea.Top) / 44;
            startY += -num * 44;
            startItemIndex += -num * this._itemsPerLine;
            int num2 = (int)Math.Ceiling((double)((float)viewCullingArea.Height / 44f)) * this._itemsPerLine;
            if (endItemIndex > num2 + startItemIndex + this._itemsPerLine)
            {
                endItemIndex = num2 + startItemIndex + this._itemsPerLine;
            }
        }
References Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >._contents, Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >._itemsPerLine, System.Math.Ceiling(), Microsoft.Xna.Framework.Rectangle.Center, Microsoft.Xna.Framework.Rectangle.Height, int, System.Math.Min(), Microsoft.Xna.Framework.Rectangle.Top, and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.DrawSelf(), and Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetSnapPoints().