Terraria Decompiled: Terraria.GameContent.UI.Elements.UIDynamicItemCollection.GetSnapPoints
GetSnapPoints()
override List< SnapPoint > Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetSnapPoints () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 142 of file UIDynamicItemCollection.2.cs.
        {
            List<SnapPoint> list = new List<SnapPoint>();
            int num;
            int num2;
            int num3;
            int num4;
            this.GetGridParameters(out num, out num2, out num3, out num4);
            int itemsPerLine = this._itemsPerLine;
            Rectangle viewCullingArea = base.Parent.GetViewCullingArea();
            int num5 = num4 - num3;
            while (this._dummySnapPoints.Count < num5)
            {
                this._dummySnapPoints.Add(new SnapPoint("DynamicItemCollectionSlot", 0, Vector2.Zero, Vector2.Zero));
            }
            int num6 = 0;
            Vector2 vector = base.GetDimensions().Position();
            for (int i = num3; i < num4; i++)
            {
                Point center = this.GetItemSlotHitbox(num, num2, num3, i).Center;
                if (viewCullingArea.Contains(center))
                {
                    SnapPoint snapPoint = this._dummySnapPoints[num6];
                    snapPoint.ThisIsAHackThatChangesTheSnapPointsInfo(Vector2.Zero, center.ToVector2() - vector, i);
                    snapPoint.Calculate(this);
                    num6++;
                    list.Add(snapPoint);
                }
            }
            foreach (UIElement uielement in this.Elements)
            {
                list.AddRange(uielement.GetSnapPoints());
            }
            return list;
        }
References Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >._dummySnapPoints, Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >._itemsPerLine, Terraria.UI.SnapPoint.Calculate(), Microsoft.Xna.Framework.Rectangle.Center, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetGridParameters(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetItemSlotHitbox(), Terraria.UI.UIElement.GetSnapPoints(), System.list, Terraria.UI.SnapPoint.ThisIsAHackThatChangesTheSnapPointsInfo(), and Microsoft.Xna.Framework.Vector2.Zero.