Terraria Decompiled: FullSerializer.fsSerializer.InternalDeserialize_5_Converter
InternalDeserialize_5_Converter()
fsResult FullSerializer.fsSerializer.InternalDeserialize_5_Converter (Type overrideConverterType, fsData data, Type resultType, ref object result) inline private
Definition at line 634 of file fsSerializer.cs.
        {
            if (fsSerializer.IsWrappedData(data))
            {
                data = data.AsDictionary["$content"];
            }
            return this.GetConverter(resultType, overrideConverterType).TryDeserialize(data, ref result, resultType);
        }
References FullSerializer.fsData.AsDictionary, FullSerializer.fsSerializer.GetConverter(), FullSerializer.fsSerializer.IsWrappedData(), and FullSerializer.fsBaseConverter.TryDeserialize().
Referenced by FullSerializer.fsSerializer.InternalDeserialize_4_Cycles().