Terraria Decompiled: Terraria.GameContent.Tile_Entities.TELogicSensor.GetState
GetState()
static bool Terraria.GameContent.Tile_Entities.TELogicSensor.GetState (int x, int y, TELogicSensor::LogicCheckType type, TELogicSensor instance = null) inline static
Definition at line 195 of file TELogicSensor.cs.
        {
            switch (type)
            {
            case TELogicSensor.LogicCheckType.Day:
                return Main.dayTime;
            case TELogicSensor.LogicCheckType.Night:
                return !Main.dayTime;
            case TELogicSensor.LogicCheckType.PlayerAbove:
            {
                bool flag = false;
                Rectangle rectangle = new Rectangle(x * 16 - 32 - 1, y * 16 - 160 - 1, 82, 162);
                foreach (KeyValuePair<int, Rectangle> keyValuePair in TELogicSensor.playerBox)
                {
                    if (keyValuePair.Value.Intersects(rectangle))
                    {
                        flag = true;
                        break;
                    }
                }
                return flag;
            }
            case TELogicSensor.LogicCheckType.Water:
            case TELogicSensor.LogicCheckType.Lava:
            case TELogicSensor.LogicCheckType.Honey:
            case TELogicSensor.LogicCheckType.Liquid:
            {
                if (instance == null)
                {
                    return false;
                }
                Tile tile = Main.tile[x, y];
                bool flag2 = true;
                if (tile == null || tile.liquid == 0)
                {
                    flag2 = false;
                }
                if (!tile.lava() && type == TELogicSensor.LogicCheckType.Lava)
                {
                    flag2 = false;
                }
                if (!tile.honey() && type == TELogicSensor.LogicCheckType.Honey)
                {
                    flag2 = false;
                }
                if ((tile.honey() || tile.lava() || tile.shimmer()) && type == TELogicSensor.LogicCheckType.Water)
                {
                    flag2 = false;
                }
                if (!flag2 && instance.On)
                {
                    if (instance.CountedData == 0)
                    {
                        instance.CountedData = 15;
                    }
                    else if (instance.CountedData > 0)
                    {
                        instance.CountedData--;
                    }
                    flag2 = instance.CountedData > 0;
                }
                return flag2;
            }
            default:
                return false;
            }
        }
References Terraria.Main.dayTime, Terraria.Tile.honey(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.GameContent.Tile_Entities.TELogicSensor.playerBox, Terraria.Tile.shimmer(), Terraria.Main.tile, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckType(), and Terraria.GameContent.Tile_Entities.TELogicSensor.Update().