Terraria Decompiled: Terraria.GameContent.Tile_Entities.TELogicSensor.ChangeState
ChangeState()
void Terraria.GameContent.Tile_Entities.TELogicSensor.ChangeState (bool onState, bool TripWire) inline
Definition at line 120 of file TELogicSensor.cs.
        {
            if (onState != this.On && !TELogicSensor.SanityCheck((int)this.Position.X, (int)this.Position.Y))
            {
                return;
            }
            Main.tile[(int)this.Position.X, (int)this.Position.Y].frameX = (onState ? 18 : 0);
            this.On = onState;
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, (int)this.Position.X, (int)this.Position.Y, TileChangeType.None);
            }
            if (TripWire && Main.netMode != 1)
            {
                TELogicSensor.tripPoints.Add(Tuple.Create<Point16, bool>(this.Position, this.logicCheck == TELogicSensor.LogicCheckType.PlayerAbove));
            }
        }
References System.Collections.Generic.List< T >.Add(), Terraria.Tile.frameX, int, Terraria.Main.netMode, Terraria.GameContent.Tile_Entities.TELogicSensor.On, Terraria.GameContent.Tile_Entities.TELogicSensor.SanityCheck(), Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, and Terraria.GameContent.Tile_Entities.TELogicSensor.tripPoints.
Referenced by Terraria.GameContent.Tile_Entities.TELogicSensor.Update().