Terraria Decompiled: FullSerializer.fsSerializer.InternalDeserialize_2_Version
InternalDeserialize_2_Version()
fsResult FullSerializer.fsSerializer.InternalDeserialize_2_Version (Type overrideConverterType, fsData data, Type storageType, ref object result, out List< fsObjectProcessor > processors) inline private
Definition at line 545 of file fsSerializer.cs.
        {
            if (fsSerializer.IsVersioned(data))
            {
                string asString = data.AsDictionary["$version"].AsString;
                fsOption<fsVersionedType> versionedType = fsVersionManager.GetVersionedType(storageType);
                if (versionedType.HasValue && versionedType.Value.VersionString != asString)
                {
                    fsResult fsResult = fsResult.Success;
                    List<fsVersionedType> list;
                    fsResult += fsVersionManager.GetVersionImportPath(asString, versionedType.Value, out list);
                    if (fsResult.Failed)
                    {
                        processors = this.GetProcessors(storageType);
                        return fsResult;
                    }
                    fsResult += this.InternalDeserialize_3_Inheritance(overrideConverterType, data, list[0].ModelType, ref result, out processors);
                    if (fsResult.Failed)
                    {
                        return fsResult;
                    }
                    for (int i = 1; i < list.Count; i++)
                    {
                        result = list[i].Migrate(result);
                    }
                    if (fsSerializer.IsObjectDefinition(data))
                    {
                        int num = int.Parse(data.AsDictionary["$id"].AsString);
                        this._references.AddReferenceWithId(num, result);
                    }
                    processors = this.GetProcessors(fsResult.GetType());
                    return fsResult;
                }
            }
            return this.InternalDeserialize_3_Inheritance(overrideConverterType, data, storageType, ref result, out processors);
        }
References FullSerializer.fsSerializer._references, FullSerializer.Internal.fsCyclicReferenceManager.AddReferenceWithId(), FullSerializer.fsData.AsDictionary, FullSerializer.fsResult.Failed, FullSerializer.fsSerializer.GetProcessors(), FullSerializer.Internal.fsVersionManager.GetVersionedType(), FullSerializer.Internal.fsVersionManager.GetVersionImportPath(), FullSerializer.Internal.fsOption< T >.HasValue, FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance(), FullSerializer.fsSerializer.IsObjectDefinition(), FullSerializer.fsSerializer.IsVersioned(), System.list, FullSerializer.fsResult.Success, and FullSerializer.Internal.fsOption< T >.Value.
Referenced by FullSerializer.fsSerializer.InternalDeserialize_1_CycleReference().