Terraria Decompiled: FullSerializer.fsSerializer.InternalSerialize_1_ProcessCycles
InternalSerialize_1_ProcessCycles()
fsResult FullSerializer.fsSerializer.InternalSerialize_1_ProcessCycles (Type storageType, Type overrideConverterType, object instance, out fsData data) inline private
Definition at line 411 of file fsSerializer.cs.
        {
            fsResult fsResult;
            try
            {
                this._references.Enter();
                if (!this.GetConverter(instance.GetType(), overrideConverterType).RequestCycleSupport(instance.GetType()))
                {
                    fsResult = this.InternalSerialize_2_Inheritance(storageType, overrideConverterType, instance, out data);
                }
                else if (this._references.IsReference(instance))
                {
                    data = fsData.CreateDictionary();
                    this._lazyReferenceWriter.WriteReference(this._references.GetReferenceId(instance), data.AsDictionary);
                    fsResult = fsResult.Success;
                }
                else
                {
                    this._references.MarkSerialized(instance);
                    fsResult fsResult2 = this.InternalSerialize_2_Inheritance(storageType, overrideConverterType, instance, out data);
                    if (fsResult2.Failed)
                    {
                        fsResult = fsResult2;
                    }
                    else
                    {
                        this._lazyReferenceWriter.WriteDefinition(this._references.GetReferenceId(instance), data);
                        fsResult = fsResult2;
                    }
                }
            }
            finally
            {
                if (this._references.Exit())
                {
                    this._lazyReferenceWriter.Clear();
                }
            }
            return fsResult;
        }
References FullSerializer.fsSerializer._lazyReferenceWriter, FullSerializer.fsSerializer._references, FullSerializer.fsData.CreateDictionary(), FullSerializer.Internal.fsCyclicReferenceManager.Enter(), FullSerializer.Internal.fsCyclicReferenceManager.Exit(), FullSerializer.fsResult.Failed, FullSerializer.fsSerializer.GetConverter(), FullSerializer.Internal.fsCyclicReferenceManager.GetReferenceId(), FullSerializer.fsSerializer.InternalSerialize_2_Inheritance(), FullSerializer.Internal.fsCyclicReferenceManager.IsReference(), FullSerializer.Internal.fsCyclicReferenceManager.MarkSerialized(), FullSerializer.fsBaseConverter.RequestCycleSupport(), and FullSerializer.fsResult.Success.
Referenced by FullSerializer.fsSerializer.TrySerialize().