Terraria Decompiled: Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckType
FigureCheckType()
static TELogicSensor.LogicCheckType Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckType (int x, int y, out bool on) inline static
Definition at line 153 of file TELogicSensor.cs.
        {
            on = false;
            if (!WorldGen.InWorld(x, y, 0))
            {
                return TELogicSensor.LogicCheckType.None;
            }
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return TELogicSensor.LogicCheckType.None;
            }
            TELogicSensor.LogicCheckType logicCheckType = TELogicSensor.LogicCheckType.None;
            switch (tile.frameY / 18)
            {
            case 0:
                logicCheckType = TELogicSensor.LogicCheckType.Day;
                break;
            case 1:
                logicCheckType = TELogicSensor.LogicCheckType.Night;
                break;
            case 2:
                logicCheckType = TELogicSensor.LogicCheckType.PlayerAbove;
                break;
            case 3:
                logicCheckType = TELogicSensor.LogicCheckType.Water;
                break;
            case 4:
                logicCheckType = TELogicSensor.LogicCheckType.Lava;
                break;
            case 5:
                logicCheckType = TELogicSensor.LogicCheckType.Honey;
                break;
            case 6:
                logicCheckType = TELogicSensor.LogicCheckType.Liquid;
                break;
            }
            on = TELogicSensor.GetState(x, y, logicCheckType, null);
            return logicCheckType;
        }
References Terraria.Tile.frameY, Terraria.GameContent.Tile_Entities.TELogicSensor.GetState(), Terraria.WorldGen.InWorld(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckState(), and Terraria.GameContent.Tile_Entities.TELogicSensor.Hook_AfterPlacement().