Terraria Decompiled: FullSerializer.fsSerializer.InternalDeserialize_4_Cycles
InternalDeserialize_4_Cycles()
fsResult FullSerializer.fsSerializer.InternalDeserialize_4_Cycles (Type overrideConverterType, fsData data, Type resultType, ref object result) inline private
Definition at line 623 of file fsSerializer.cs.
        {
            if (fsSerializer.IsObjectDefinition(data))
            {
                int num = int.Parse(data.AsDictionary["$id"].AsString);
                this._references.AddReferenceWithId(num, result);
            }
            return this.InternalDeserialize_5_Converter(overrideConverterType, data, resultType, ref result);
        }
References FullSerializer.fsSerializer._references, FullSerializer.Internal.fsCyclicReferenceManager.AddReferenceWithId(), FullSerializer.fsData.AsDictionary, FullSerializer.fsSerializer.InternalDeserialize_5_Converter(), and FullSerializer.fsSerializer.IsObjectDefinition().
Referenced by FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance().