Terraria Decompiled: FullSerializer.fsSerializer.GetConverter
GetConverter()
fsBaseConverter FullSerializer.fsSerializer.GetConverter (Type type, Type overrideConverterType) inline private
Definition at line 319 of file fsSerializer.cs.
        {
            if (overrideConverterType != null)
            {
                fsBaseConverter fsBaseConverter;
                if (!this._cachedConverterTypeInstances.TryGetValue(overrideConverterType, ref fsBaseConverter))
                {
                    fsBaseConverter = (fsBaseConverter)Activator.CreateInstance(overrideConverterType);
                    fsBaseConverter.Serializer = this;
                    this._cachedConverterTypeInstances[overrideConverterType] = fsBaseConverter;
                }
                return fsBaseConverter;
            }
            fsBaseConverter fsBaseConverter2;
            if (this._cachedConverters.TryGetValue(type, ref fsBaseConverter2))
            {
                return fsBaseConverter2;
            }
            fsObjectAttribute attribute = fsPortableReflection.GetAttribute<fsObjectAttribute>(type);
            if (attribute != null && attribute.Converter != null)
            {
                fsBaseConverter2 = (fsBaseConverter)Activator.CreateInstance(attribute.Converter);
                fsBaseConverter2.Serializer = this;
                return this._cachedConverters[type] = fsBaseConverter2;
            }
            fsForwardAttribute attribute2 = fsPortableReflection.GetAttribute<fsForwardAttribute>(type);
            if (attribute2 != null)
            {
                fsBaseConverter2 = new fsForwardConverter(attribute2);
                fsBaseConverter2.Serializer = this;
                return this._cachedConverters[type] = fsBaseConverter2;
            }
            if (!this._cachedConverters.TryGetValue(type, ref fsBaseConverter2))
            {
                if (this._availableDirectConverters.ContainsKey(type))
                {
                    fsBaseConverter2 = this._availableDirectConverters[type];
                    return this._cachedConverters[type] = fsBaseConverter2;
                }
                for (int i = 0; i < this._availableConverters.Count; i++)
                {
                    if (this._availableConverters[i].CanProcess(type))
                    {
                        fsBaseConverter2 = this._availableConverters[i];
                        return this._cachedConverters[type] = fsBaseConverter2;
                    }
                }
            }
            throw new InvalidOperationException("Internal error -- could not find a converter for " + type);
        }
References FullSerializer.fsSerializer._availableConverters, FullSerializer.fsSerializer._availableDirectConverters, FullSerializer.fsSerializer._cachedConverters, FullSerializer.fsSerializer._cachedConverterTypeInstances, FullSerializer.fsObjectAttribute.Converter, System.Activator.CreateInstance(), and FullSerializer.Internal.fsPortableReflection.GetAttribute().
Referenced by FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance(), FullSerializer.fsSerializer.InternalDeserialize_5_Converter(), FullSerializer.fsSerializer.InternalSerialize_1_ProcessCycles(), and FullSerializer.fsSerializer.InternalSerialize_4_Converter().