Terraria Decompiled: FullSerializer.fsSerializer.TrySerialize
TrySerialize() [2/2]
fsResult FullSerializer.fsSerializer.TrySerialize (Type storageType, Type overrideConverterType, object instance, out fsData data) inline
Definition at line 395 of file fsSerializer.cs.
        {
            List<fsObjectProcessor> processors = this.GetProcessors((instance == null) ? storageType : instance.GetType());
            fsSerializer.Invoke_OnBeforeSerialize(processors, storageType, instance);
            if (instance == null)
            {
                data = new fsData();
                fsSerializer.Invoke_OnAfterSerialize(processors, storageType, instance, ref data);
                return fsResult.Success;
            }
            fsResult fsResult = this.InternalSerialize_1_ProcessCycles(storageType, overrideConverterType, instance, out data);
            fsSerializer.Invoke_OnAfterSerialize(processors, storageType, instance, ref data);
            return fsResult;
        }
References FullSerializer.fsSerializer.GetProcessors(), FullSerializer.fsSerializer.InternalSerialize_1_ProcessCycles(), FullSerializer.fsSerializer.Invoke_OnAfterSerialize(), FullSerializer.fsSerializer.Invoke_OnBeforeSerialize(), and FullSerializer.fsResult.Success.