Terraria Decompiled: FullSerializer.fsSerializer.InternalSerialize_3_ProcessVersioning
InternalSerialize_3_ProcessVersioning()
fsResult FullSerializer.fsSerializer.InternalSerialize_3_ProcessVersioning (Type overrideConverterType, object instance, out fsData data) inline private
Definition at line 469 of file fsSerializer.cs.
        {
            fsOption<fsVersionedType> versionedType = fsVersionManager.GetVersionedType(instance.GetType());
            if (!versionedType.HasValue)
            {
                return this.InternalSerialize_4_Converter(overrideConverterType, instance, out data);
            }
            fsVersionedType value = versionedType.Value;
            fsResult fsResult = this.InternalSerialize_4_Converter(overrideConverterType, instance, out data);
            if (fsResult.Failed)
            {
                return fsResult;
            }
            fsSerializer.EnsureDictionary(data);
            data.AsDictionary["$version"] = new fsData(value.VersionString);
            return fsResult;
        }
References FullSerializer.fsSerializer.EnsureDictionary(), FullSerializer.fsResult.Failed, FullSerializer.Internal.fsVersionManager.GetVersionedType(), FullSerializer.Internal.fsOption< T >.HasValue, FullSerializer.fsSerializer.InternalSerialize_4_Converter(), System.value, and FullSerializer.Internal.fsOption< T >.Value.
Referenced by FullSerializer.fsSerializer.InternalSerialize_2_Inheritance().