Terraria Decompiled: FullSerializer.fsSerializer.InternalDeserialize_1_CycleReference
InternalDeserialize_1_CycleReference()
fsResult FullSerializer.fsSerializer.InternalDeserialize_1_CycleReference (Type overrideConverterType, fsData data, Type storageType, ref object result, out List< fsObjectProcessor > processors) inline private
Definition at line 532 of file fsSerializer.cs.
        {
            if (fsSerializer.IsObjectReference(data))
            {
                int num = int.Parse(data.AsDictionary["$ref"].AsString);
                result = this._references.GetReferenceObject(num);
                processors = this.GetProcessors(result.GetType());
                return fsResult.Success;
            }
            return this.InternalDeserialize_2_Version(overrideConverterType, data, storageType, ref result, out processors);
        }
References FullSerializer.fsSerializer._references, FullSerializer.fsData.AsDictionary, FullSerializer.fsSerializer.GetProcessors(), FullSerializer.Internal.fsCyclicReferenceManager.GetReferenceObject(), FullSerializer.fsSerializer.InternalDeserialize_2_Version(), FullSerializer.fsSerializer.IsObjectReference(), and FullSerializer.fsResult.Success.
Referenced by FullSerializer.fsSerializer.TryDeserialize().