Terraria Decompiled: FullSerializer.fsSerializer.GetProcessors
GetProcessors()
List< fsObjectProcessor > FullSerializer.fsSerializer.GetProcessors (Type type) inline private
Definition at line 267 of file fsSerializer.cs.
        {
            fsObjectAttribute attribute = fsPortableReflection.GetAttribute<fsObjectAttribute>(type);
            List<fsObjectProcessor> list;
            if (attribute != null && attribute.Processor != null)
            {
                fsObjectProcessor fsObjectProcessor = (fsObjectProcessor)Activator.CreateInstance(attribute.Processor);
                list = new List<fsObjectProcessor>();
                list.Add(fsObjectProcessor);
                this._cachedProcessors[type] = list;
            }
            else if (!this._cachedProcessors.TryGetValue(type, ref list))
            {
                list = new List<fsObjectProcessor>();
                for (int i = 0; i < this._processors.Count; i++)
                {
                    fsObjectProcessor fsObjectProcessor2 = this._processors[i];
                    if (fsObjectProcessor2.CanProcess(type))
                    {
                        list.Add(fsObjectProcessor2);
                    }
                }
                this._cachedProcessors[type] = list;
            }
            return list;
        }
References FullSerializer.fsSerializer._cachedProcessors, FullSerializer.fsSerializer._processors, FullSerializer.fsObjectProcessor.CanProcess(), System.Activator.CreateInstance(), FullSerializer.Internal.fsPortableReflection.GetAttribute(), System.list, and FullSerializer.fsObjectAttribute.Processor.
Referenced by FullSerializer.fsSerializer.InternalDeserialize_1_CycleReference(), FullSerializer.fsSerializer.InternalDeserialize_2_Version(), FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance(), FullSerializer.fsSerializer.TryDeserialize(), and FullSerializer.fsSerializer.TrySerialize().