Terraria Decompiled: FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance
InternalDeserialize_3_Inheritance()
fsResult FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance (Type overrideConverterType, fsData data, Type storageType, ref object result, out List< fsObjectProcessor > processors) inline private
Definition at line 583 of file fsSerializer.cs.
        {
            fsResult success = fsResult.Success;
            Type type = storageType;
            if (fsSerializer.IsTypeSpecified(data))
            {
                fsData fsData = data.AsDictionary["$type"];
                if (!fsData.IsString)
                {
                    success.AddMessage("$type value must be a string (in " + data + ")");
                }
                else
                {
                    string asString = fsData.AsString;
                    Type type2 = fsTypeCache.GetType(asString);
                    if (type2 == null)
                    {
                        success.AddMessage("Unable to locate specified type \"" + asString + "\"");
                    }
                    else if (!storageType.IsAssignableFrom(type2))
                    {
                        success.AddMessage(string.Concat(new object[] { "Ignoring type specifier; a field/property of type ", storageType, " cannot hold an instance of ", type2 }));
                    }
                    else
                    {
                        type = type2;
                    }
                }
            }
            processors = this.GetProcessors(type);
            fsSerializer.Invoke_OnBeforeDeserialize(processors, storageType, ref data);
            if (result == null || result.GetType() != type)
            {
                result = this.GetConverter(type, overrideConverterType).CreateInstance(data, type);
            }
            fsSerializer.Invoke_OnBeforeDeserializeAfterInstanceCreation(processors, storageType, result, ref data);
            return success + this.InternalDeserialize_4_Cycles(overrideConverterType, data, type, ref result);
        }
References FullSerializer.fsResult.AddMessage(), FullSerializer.fsData.AsDictionary, FullSerializer.fsData.AsString, FullSerializer.fsBaseConverter.CreateInstance(), FullSerializer.fsSerializer.GetConverter(), FullSerializer.fsSerializer.GetProcessors(), FullSerializer.Internal.fsTypeCache.GetType(), FullSerializer.fsSerializer.InternalDeserialize_4_Cycles(), FullSerializer.fsSerializer.Invoke_OnBeforeDeserialize(), FullSerializer.fsSerializer.Invoke_OnBeforeDeserializeAfterInstanceCreation(), System.Type.IsAssignableFrom(), FullSerializer.fsData.IsString, FullSerializer.fsSerializer.IsTypeSpecified(), and FullSerializer.fsResult.Success.
Referenced by FullSerializer.fsSerializer.InternalDeserialize_2_Version().