Terraria Decompiled: FullSerializer.fsSerializer.fsSerializer
fsSerializer() [2/2]
FullSerializer.fsSerializer.fsSerializer () inline
Definition at line 172 of file fsSerializer.cs.
        {
            this._cachedConverterTypeInstances = new Dictionary<Type, fsBaseConverter>();
            this._cachedConverters = new Dictionary<Type, fsBaseConverter>();
            this._cachedProcessors = new Dictionary<Type, List<fsObjectProcessor>>();
            this._references = new fsCyclicReferenceManager();
            this._lazyReferenceWriter = new fsSerializer.fsLazyCycleDefinitionWriter();
            List<fsConverter> list = new List<fsConverter>();
            list.Add(new fsNullableConverter
            {
                Serializer = this
            });
            list.Add(new fsGuidConverter
            {
                Serializer = this
            });
            list.Add(new fsTypeConverter
            {
                Serializer = this
            });
            list.Add(new fsDateConverter
            {
                Serializer = this
            });
            list.Add(new fsEnumConverter
            {
                Serializer = this
            });
            list.Add(new fsPrimitiveConverter
            {
                Serializer = this
            });
            list.Add(new fsArrayConverter
            {
                Serializer = this
            });
            list.Add(new fsDictionaryConverter
            {
                Serializer = this
            });
            list.Add(new fsIEnumerableConverter
            {
                Serializer = this
            });
            list.Add(new fsKeyValuePairConverter
            {
                Serializer = this
            });
            list.Add(new fsWeakReferenceConverter
            {
                Serializer = this
            });
            list.Add(new fsReflectedConverter
            {
                Serializer = this
            });
            this._availableConverters = list;
            this._availableDirectConverters = new Dictionary<Type, fsDirectConverter>();
            List<fsObjectProcessor> list2 = new List<fsObjectProcessor>();
            list2.Add(new fsSerializationCallbackProcessor());
            this._processors = list2;
            this.Context = new fsContext();
            this.Config = new fsConfig();
            foreach (Type type in fsConverterRegistrar.Converters)
            {
                this.AddConverter((fsBaseConverter)Activator.CreateInstance(type));
            }
        }
References System.Collections.Generic.List< T >.Add(), FullSerializer.fsSerializer.AddConverter(), FullSerializer.fsConverterRegistrar.Converters, System.Activator.CreateInstance(), and System.list.