Terraria Decompiled: FullSerializer.fsSerializer.ConvertLegacyData
ConvertLegacyData()
static void FullSerializer.fsSerializer.ConvertLegacyData (ref fsData data) inline static private
Definition at line 76 of file fsSerializer.cs.
        {
            if (!data.IsDictionary)
            {
                return;
            }
            Dictionary<string, fsData> asDictionary = data.AsDictionary;
            if (asDictionary.Count > 2)
            {
                return;
            }
            string text = "ReferenceId";
            string text2 = "SourceId";
            string text3 = "Data";
            string text4 = "Type";
            string text5 = "Data";
            if (asDictionary.Count == 2 && asDictionary.ContainsKey(text4) && asDictionary.ContainsKey(text5))
            {
                data = asDictionary[text5];
                fsSerializer.EnsureDictionary(data);
                fsSerializer.ConvertLegacyData(ref data);
                data.AsDictionary["$type"] = asDictionary[text4];
                return;
            }
            if (asDictionary.Count == 2 && asDictionary.ContainsKey(text2) && asDictionary.ContainsKey(text3))
            {
                data = asDictionary[text3];
                fsSerializer.EnsureDictionary(data);
                fsSerializer.ConvertLegacyData(ref data);
                data.AsDictionary["$id"] = asDictionary[text2];
                return;
            }
            if (asDictionary.Count == 1 && asDictionary.ContainsKey(text))
            {
                data = fsData.CreateDictionary();
                data.AsDictionary["$ref"] = asDictionary[text];
            }
        }
References FullSerializer.fsData.AsDictionary, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), FullSerializer.fsSerializer.ConvertLegacyData(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, FullSerializer.fsData.CreateDictionary(), FullSerializer.fsSerializer.EnsureDictionary(), and System.text.
Referenced by FullSerializer.fsSerializer.ConvertLegacyData(), and FullSerializer.fsSerializer.TryDeserialize().