Terraria Decompiled: FullSerializer.fsSerializer.TryDeserialize
TryDeserialize() [2/2]
fsResult FullSerializer.fsSerializer.TryDeserialize (fsData data, Type storageType, Type overrideConverterType, ref object result) inline
Definition at line 501 of file fsSerializer.cs.
        {
            if (data.IsNull)
            {
                result = null;
                List<fsObjectProcessor> processors = this.GetProcessors(storageType);
                fsSerializer.Invoke_OnBeforeDeserialize(processors, storageType, ref data);
                fsSerializer.Invoke_OnAfterDeserialize(processors, storageType, null);
                return fsResult.Success;
            }
            fsSerializer.ConvertLegacyData(ref data);
            fsResult fsResult2;
            try
            {
                this._references.Enter();
                List<fsObjectProcessor> list;
                fsResult fsResult = this.InternalDeserialize_1_CycleReference(overrideConverterType, data, storageType, ref result, out list);
                if (fsResult.Succeeded)
                {
                    fsSerializer.Invoke_OnAfterDeserialize(list, storageType, result);
                }
                fsResult2 = fsResult;
            }
            finally
            {
                this._references.Exit();
            }
            return fsResult2;
        }
References FullSerializer.fsSerializer._references, FullSerializer.fsSerializer.ConvertLegacyData(), FullSerializer.Internal.fsCyclicReferenceManager.Enter(), FullSerializer.Internal.fsCyclicReferenceManager.Exit(), FullSerializer.fsSerializer.GetProcessors(), FullSerializer.fsSerializer.InternalDeserialize_1_CycleReference(), FullSerializer.fsSerializer.Invoke_OnAfterDeserialize(), FullSerializer.fsSerializer.Invoke_OnBeforeDeserialize(), FullSerializer.fsData.IsNull, System.list, FullSerializer.fsResult.Succeeded, and FullSerializer.fsResult.Success.