Terraria Decompiled: FullSerializer.fsSerializer.InternalSerialize_4_Converter
InternalSerialize_4_Converter()
fsResult FullSerializer.fsSerializer.InternalSerialize_4_Converter (Type overrideConverterType, object instance, out fsData data) inline private
Definition at line 488 of file fsSerializer.cs.
        {
            Type type = instance.GetType();
            return this.GetConverter(type, overrideConverterType).TrySerialize(instance, out data, type);
        }
References FullSerializer.fsSerializer.GetConverter(), and FullSerializer.fsBaseConverter.TrySerialize().
Referenced by FullSerializer.fsSerializer.InternalSerialize_3_ProcessVersioning().