Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.IsOverridenGenericMember
IsOverridenGenericMember()
static bool Newtonsoft.Json.Utilities.ReflectionUtils.IsOverridenGenericMember (MemberInfo memberInfo, BindingFlags bindingAttr) inline static private
Definition at line 487 of file ReflectionUtils.cs.
        {
            if (memberInfo.MemberType() != 16)
            {
                return false;
            }
            PropertyInfo propertyInfo = (PropertyInfo)memberInfo;
            if (!propertyInfo.IsVirtual())
            {
                return false;
            }
            Type declaringType = propertyInfo.DeclaringType;
            if (!declaringType.IsGenericType())
            {
                return false;
            }
            Type genericTypeDefinition = declaringType.GetGenericTypeDefinition();
            if (genericTypeDefinition == null)
            {
                return false;
            }
            MemberInfo[] member = genericTypeDefinition.GetMember(propertyInfo.Name, bindingAttr);
            return member.Length != 0 && ReflectionUtils.GetMemberUnderlyingType(member[0]).IsGenericParameter;
        }
References System.Reflection.MemberInfo.DeclaringType, System.Type.GetGenericTypeDefinition(), System.Type.GetMember(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberUnderlyingType(), System.Type.IsGenericParameter, System.Type.IsGenericType, System.Reflection.MemberInfo.MemberType, and System.Reflection.MemberInfo.Name.
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.GetFieldsAndProperties().