Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.SplitFullyQualifiedTypeName
SplitFullyQualifiedTypeName()
static TypeNameKey Newtonsoft.Json.Utilities.ReflectionUtils.SplitFullyQualifiedTypeName (string fullyQualifiedTypeName) inline static
Definition at line 600 of file ReflectionUtils.cs.
        {
            int? assemblyDelimiterIndex = ReflectionUtils.GetAssemblyDelimiterIndex(fullyQualifiedTypeName);
            string text;
            string text2;
            if (assemblyDelimiterIndex != null)
            {
                text = fullyQualifiedTypeName.Trim(0, assemblyDelimiterIndex.GetValueOrDefault());
                text2 = fullyQualifiedTypeName.Trim(assemblyDelimiterIndex.GetValueOrDefault() + 1, fullyQualifiedTypeName.Length - assemblyDelimiterIndex.GetValueOrDefault() - 1);
            }
            else
            {
                text = fullyQualifiedTypeName;
                text2 = null;
            }
            return new TypeNameKey(text2, text);
        }
References Newtonsoft.Json.Utilities.ReflectionUtils.GetAssemblyDelimiterIndex(), and System.text.
Referenced by Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetGenericTypeFromTypeName(), and Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName().