Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType
IsNullableType()
static bool Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType (Type t) inline static
Definition at line 175 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(t, "t");
            return t.IsGenericType() && t.GetGenericTypeDefinition() == typeof(Nullable);
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Type.GetGenericTypeDefinition(), and System.Type.IsGenericType.
Referenced by Newtonsoft.Json.Converters.KeyValuePairConverter.CanConvert(), Newtonsoft.Json.Converters.StringEnumConverter.CanConvert(), Newtonsoft.Json.Linq.Extensions.Convert< T, U >(), Newtonsoft.Json.Utilities.ReflectionUtils.EnsureNotNullableType(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), Newtonsoft.Json.Utilities.CollectionWrapper< T >.IsCompatibleObject(), Newtonsoft.Json.Serialization.DefaultContractResolver.IsIConvertible(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Serialization.JsonContract.JsonContract(), Newtonsoft.Json.Converters.BinaryConverter.ReadJson(), Newtonsoft.Json.Converters.IsoDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson(), Newtonsoft.Json.Converters.KeyValuePairConverter.ReadJson(), Newtonsoft.Json.Converters.StringEnumConverter.ReadJson(), and Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal().