Terraria Decompiled: Terraria.Testing.DetailedFPS.DrawFPSBox
DrawFPSBox()
static void Terraria.Testing.DetailedFPS.DrawFPSBox (Rectangle r) inline static private
Definition at line 195 of file DetailedFPS.cs.
        {
            Color white = Color.White;
            DetailedFPS.DrawRect(new Rectangle(r.Left, r.Y, 2, r.Height), white);
            DetailedFPS.DrawRect(new Rectangle(r.Right, r.Y, 2, r.Height), white);
            DetailedFPS.DrawRect(new Rectangle(r.Left, r.Y, r.Width, 1), white);
            int num = 24;
            DetailedFPS.OperationCategory operationCategory = DetailedFPS.OperationCategory.Idle;
            while (operationCategory <= DetailedFPS.OperationCategory.GC)
            {
                if (operationCategory != DetailedFPS.OperationCategory.GC || !(DetailedFPS.LastGCPauseTime == TimeSpan.Zero))
                {
                    DetailedFPS.DrawRect(new Rectangle(r.Right + 8, r.Bottom - num + 8, 8, 8), DetailedFPS.GetColor(operationCategory));
                    DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, operationCategory.ToString(), new Vector2((float)(r.Right + 20), (float)(r.Bottom - num)), Color.White);
                }
                operationCategory++;
                num += 24;
            }
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Testing.DetailedFPS.DrawRect(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Testing.DetailedFPS.GetColor(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Testing.DetailedFPS.LastGCPauseTime, Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.FontAssets.MouseText, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.Y, and System.TimeSpan.Zero.
Referenced by Terraria.Testing.DetailedFPS.Draw().