Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberInfoFromType
GetMemberInfoFromType()
static MemberInfo Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberInfoFromType (Type targetType, MemberInfo memberInfo) inline static
Definition at line 648 of file ReflectionUtils.cs.
        {
            MemberTypes memberTypes = memberInfo.MemberType();
            if (memberTypes == 16)
            {
                PropertyInfo propertyInfo = (PropertyInfo)memberInfo;
                Type[] array = Enumerable.ToArray<Type>(Enumerable.Select<ParameterInfo, Type>(propertyInfo.GetIndexParameters(), (ParameterInfo p) => p.ParameterType));
                return targetType.GetProperty(propertyInfo.Name, 60, null, propertyInfo.PropertyType, array, null);
            }
            return Enumerable.SingleOrDefault<MemberInfo>(targetType.GetMember(memberInfo.Name, memberInfo.MemberType(), 60));
        }
References System.array, System.Reflection.PropertyInfo.GetIndexParameters(), System.Type.GetMember(), System.Type.GetProperty(), System.Reflection.MemberInfo.MemberType, System.Reflection.MemberInfo.Name, System.Reflection.ParameterInfo.ParameterType, and System.Reflection.PropertyInfo.PropertyType.
Referenced by Newtonsoft.Json.Serialization.JsonTypeReflector.GetAttribute< T >(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataMemberAttribute(), and Newtonsoft.Json.Utilities.ReflectionUtils.GetProperties().