Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetProperties
GetProperties()
static IEnumerable< PropertyInfo > Newtonsoft.Json.Utilities.ReflectionUtils.GetProperties (Type targetType, BindingFlags bindingAttr) inline static
Definition at line 684 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(targetType, "targetType");
            List<PropertyInfo> list = new List<PropertyInfo>(targetType.GetProperties(bindingAttr));
            if (targetType.IsInterface())
            {
                foreach (Type type in targetType.GetInterfaces())
                {
                    list.AddRange(type.GetProperties(bindingAttr));
                }
            }
            ReflectionUtils.GetChildPrivateProperties(list, targetType, bindingAttr);
            for (int j = 0; j < list.Count; j++)
            {
                PropertyInfo propertyInfo = list[j];
                if (propertyInfo.DeclaringType != targetType)
                {
                    PropertyInfo propertyInfo2 = (PropertyInfo)ReflectionUtils.GetMemberInfoFromType(propertyInfo.DeclaringType, propertyInfo);
                    list[j] = propertyInfo2;
                }
            }
            return list;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Reflection.MemberInfo.DeclaringType, Newtonsoft.Json.Utilities.ReflectionUtils.GetChildPrivateProperties(), System.Type.GetInterfaces(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberInfoFromType(), System.Type.GetProperties(), System.Type.IsInterface, and System.list.
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.GetFieldsAndProperties().