Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetFields
GetFields()
static IEnumerable< FieldInfo > Newtonsoft.Json.Utilities.ReflectionUtils.GetFields (Type targetType, BindingFlags bindingAttr) inline static
Definition at line 661 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(targetType, "targetType");
            List<MemberInfo> list = new List<MemberInfo>(targetType.GetFields(bindingAttr));
            ReflectionUtils.GetChildPrivateFields(list, targetType, bindingAttr);
            return Enumerable.Cast<FieldInfo>(list);
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Utilities.ReflectionUtils.GetChildPrivateFields(), System.Type.GetFields(), and System.list.
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.GetFieldsAndProperties().