Terraria Decompiled: Terraria.Testing.DetailedFPS.DrawFrame
DrawFrame()
static void Terraria.Testing.DetailedFPS.DrawFrame (int x, DetailedFPS::Frame frame) inline static private
Definition at line 216 of file DetailedFPS.cs.
        {
            if (frame.events.Count < 2)
            {
                return;
            }
            int num = 0;
            DetailedFPS.Frame.Event @event = frame.events[0];
            long timestamp = @event.timestamp;
            for (int i = 1; i < frame.events.Count; i++)
            {
                DetailedFPS.Frame.Event event2 = frame.events[i];
                int num2 = (int)(Utils.SWTicksToTimeSpan(@event.timestamp - timestamp).TotalMilliseconds * 6.0);
                int num3 = (int)(Utils.SWTicksToTimeSpan(event2.timestamp - timestamp).TotalMilliseconds * 6.0);
                DetailedFPS.DrawRect(new Rectangle(x, Main.screenHeight - num3, 2, num3 - num2), DetailedFPS.GetColor(@event.category));
                @event = event2;
                num = num3;
            }
            num = Math.Max(num, 100);
            for (int j = 0; j <= GC.MaxGeneration; j++)
            {
                for (int k = 0; k < frame.CollectionCount[j]; k++)
                {
                    DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, DetailedFPS._gcGenText[j], new Vector2((float)(x - 10), (float)(Main.screenHeight - num - 15)), Color.White, 0f, Vector2.Zero, 0.75f, SpriteEffects.None, 0f, null, null);
                    num += 10;
                }
            }
        }
References Terraria.Testing.DetailedFPS._gcGenText, Terraria.Testing.DetailedFPS.DrawRect(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Testing.DetailedFPS.GetColor(), int, System.Math.Max(), System.GC.MaxGeneration, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.screenHeight, Terraria.Main.spriteBatch, Terraria.Utils.SWTicksToTimeSpan(), Terraria.Testing.DetailedFPS.Frame.Event.timestamp, System.TimeSpan.TotalMilliseconds, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Testing.DetailedFPS.Draw().