Terraria Decompiled: Terraria.Testing.DetailedFPS.Draw
Draw()
static void Terraria.Testing.DetailedFPS.Draw () inline static
Definition at line 171 of file DetailedFPS.cs.
        {
            Rectangle rectangle = new Rectangle((Main.screenWidth - DetailedFPS.Frames.Length * 2) / 2, Main.screenHeight - 100, DetailedFPS.Frames.Length * 2, 100);
            DetailedFPS.DrawFPSBox(rectangle);
            int num = 0;
            long num2 = 0L;
            foreach (DetailedFPS.Frame frame in DetailedFPS.EnumerateFrames())
            {
                num++;
                DetailedFPS.DrawFrame(rectangle.Right - num * 2, frame);
                num2 += frame.Allocated;
            }
            if (num2 > 0L)
            {
                long num3 = num2 / (long)num;
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, string.Format("Avg Alloc: {0,5} bytes/frame", num3), new Vector2((float)((Main.screenWidth - DetailedFPS.Frames.Length * 2) / 2 - 240), (float)(Main.screenHeight - 24)), Color.White);
            }
            if (Main.keyState.PressingAlt())
            {
                DynamicSpriteFontExtensionMethods.DrawString(Main.spriteBatch, FontAssets.MouseText.Value, string.Format("Time Acc: {0,5:0.0} ms", Main.UpdateTimeAccumulator * 1000.0), new Vector2((float)(Main.screenWidth - 200), (float)(Main.screenHeight - 24)), Color.White);
            }
        }
References Terraria.Testing.DetailedFPS.DrawFPSBox(), Terraria.Testing.DetailedFPS.DrawFrame(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Testing.DetailedFPS.EnumerateFrames(), Terraria.Testing.DetailedFPS.Frames, Terraria.Main.keyState, System.L, long, Terraria.GameContent.FontAssets.MouseText, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Main.spriteBatch, Terraria.Main.UpdateTimeAccumulator, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.