Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.IsGenericDefinition
IsGenericDefinition()
static bool Newtonsoft.Json.Utilities.ReflectionUtils.IsGenericDefinition (Type type, Type genericInterfaceDefinition) inline static
Definition at line 192 of file ReflectionUtils.cs.
        {
            return type.IsGenericType() && type.GetGenericTypeDefinition() == genericInterfaceDefinition;
        }
References System.Type.GetGenericTypeDefinition(), and System.Type.IsGenericType.
Referenced by Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract(), Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract(), and Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates().