Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType
GetCollectionItemType()
static Type Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType (Type type) inline static
Definition at line 278 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(type, "type");
            if (type.IsArray)
            {
                return type.GetElementType();
            }
            Type type2;
            if (ReflectionUtils.ImplementsGenericDefinition(type, typeof(IEnumerable), out type2))
            {
                if (type2.IsGenericTypeDefinition())
                {
                    throw new Exception("Type {0} is not a collection.".FormatWith(CultureInfo.InvariantCulture, type));
                }
                return type2.GetGenericArguments()[0];
            }
            else
            {
                if (typeof(IEnumerable).IsAssignableFrom(type))
                {
                    return null;
                }
                throw new Exception("Type {0} is not a collection.".FormatWith(CultureInfo.InvariantCulture, type));
            }
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Type.GetElementType(), System.Type.GetGenericArguments(), Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsArray, and System.Type.IsGenericTypeDefinition.
Referenced by Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(), and Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract().