Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition
ImplementsGenericDefinition() [2/2]
static bool Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition (Type type, Type genericInterfaceDefinition, out Type implementingType) inline static
Definition at line 205 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(type, "type");
            ValidationUtils.ArgumentNotNull(genericInterfaceDefinition, "genericInterfaceDefinition");
            if (!genericInterfaceDefinition.IsInterface() || !genericInterfaceDefinition.IsGenericTypeDefinition())
            {
                throw new ArgumentNullException("'{0}' is not a generic interface definition.".FormatWith(CultureInfo.InvariantCulture, genericInterfaceDefinition));
            }
            if (type.IsInterface() && type.IsGenericType())
            {
                Type genericTypeDefinition = type.GetGenericTypeDefinition();
                if (genericInterfaceDefinition == genericTypeDefinition)
                {
                    implementingType = type;
                    return true;
                }
            }
            foreach (Type type2 in type.GetInterfaces())
            {
                if (type2.IsGenericType())
                {
                    Type genericTypeDefinition2 = type2.GetGenericTypeDefinition();
                    if (genericInterfaceDefinition == genericTypeDefinition2)
                    {
                        implementingType = type2;
                        return true;
                    }
                }
            }
            implementingType = null;
            return false;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Type.GetGenericTypeDefinition(), System.Type.GetInterfaces(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsGenericType, System.Type.IsGenericTypeDefinition, and System.Type.IsInterface.