Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetChildPrivateProperties
GetChildPrivateProperties()
static void Newtonsoft.Json.Utilities.ReflectionUtils.GetChildPrivateProperties (IList< PropertyInfo > initialProperties, Type targetType, BindingFlags bindingAttr) inline static private
Definition at line 719 of file ReflectionUtils.cs.
        {
            while ((targetType = targetType.BaseType()) != null)
            {
                foreach (PropertyInfo propertyInfo in targetType.GetProperties(bindingAttr))
                {
                    ReflectionUtils.<>c__DisplayClass43_0 CS$<>8__locals1 = new ReflectionUtils.<>c__DisplayClass43_0();
                    CS$<>8__locals1.subTypeProperty = propertyInfo;
                    if (!CS$<>8__locals1.subTypeProperty.IsVirtual())
                    {
                        if (!ReflectionUtils.IsPublic(CS$<>8__locals1.subTypeProperty))
{
                            int num = initialProperties.IndexOf((PropertyInfo p) => p.Name == CS$<>8__locals1.subTypeProperty.Name);
                            if (num == -1)
{
                                initialProperties.Add(CS$<>8__locals1.subTypeProperty);
                            }
                            else if (!ReflectionUtils.IsPublic(initialProperties[num]))
{
                                initialProperties[num] = CS$<>8__locals1.subTypeProperty;
                            }
                        }
                        else if (initialProperties.IndexOf((PropertyInfo p) => p.Name == CS$<>8__locals1.subTypeProperty.Name && p.DeclaringType == CS$<>8__locals1.subTypeProperty.DeclaringType) == -1)
{
                            initialProperties.Add(CS$<>8__locals1.subTypeProperty);
                        }
                    }
                    else
                    {
                        ReflectionUtils.<>c__DisplayClass43_1 CS$<>8__locals2 = new ReflectionUtils.<>c__DisplayClass43_1();
                        CS$<>8__locals2.CS$<>8__locals1 = CS$<>8__locals1;
                        ReflectionUtils.<>c__DisplayClass43_1 CS$<>8__locals3 = CS$<>8__locals2;
                        MethodInfo baseDefinition = CS$<>8__locals2.CS$<>8__locals1.subTypeProperty.GetBaseDefinition();
                        CS$<>8__locals3.subTypePropertyDeclaringType = ((baseDefinition != null) ? baseDefinition.DeclaringType : null) ?? CS$<>8__locals2.CS$<>8__locals1.subTypeProperty.DeclaringType;
                        if (initialProperties.IndexOf(delegate(PropertyInfo p)
{
                            if (p.Name == CS$<>8__locals2.CS$<>8__locals1.subTypeProperty.Name && p.IsVirtual())
{
                                MethodInfo baseDefinition2 = p.GetBaseDefinition();
                                return (((baseDefinition2 != null) ? baseDefinition2.DeclaringType : null) ?? p.DeclaringType).IsAssignableFrom(CS$<>8__locals2.subTypePropertyDeclaringType);
                            }
                            return false;
                        }) == -1)
{
                            initialProperties.Add(CS$<>8__locals2.CS$<>8__locals1.subTypeProperty);
                        }
                    }
                }
            }
        }
References System.Collections.Generic.ICollection< T >.Add(), System.Type.BaseType, System.Reflection.MemberInfo.DeclaringType, System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Type.DeclaringType, System.Reflection.MethodInfo.GetBaseDefinition(), System.Type.GetProperties(), System.Collections.Generic.IList< T >.IndexOf(), Newtonsoft.Json.Utilities.ReflectionUtils.IsPublic(), and System.Reflection.MemberInfo.Name.
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.GetProperties().