Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes
GetAttributes()
static Attribute[] Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes (object attributeProvider, Type attributeType, bool inherit) inline static
Definition at line 542 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(attributeProvider, "attributeProvider");
            Type type = attributeProvider as Type;
            if (type != null)
            {
                return Enumerable.ToArray<Attribute>(Enumerable.Cast<Attribute>((attributeType != null) ? type.GetCustomAttributes(attributeType, inherit) : type.GetCustomAttributes(inherit)));
            }
            Assembly assembly = attributeProvider as Assembly;
            if (assembly != null)
            {
                if (!(attributeType != null))
                {
                    return Attribute.GetCustomAttributes(assembly);
                }
                return Attribute.GetCustomAttributes(assembly, attributeType);
            }
            else
            {
                MemberInfo memberInfo = attributeProvider as MemberInfo;
                if (memberInfo != null)
                {
                    if (!(attributeType != null))
                    {
                        return Attribute.GetCustomAttributes(memberInfo, inherit);
                    }
                    return Attribute.GetCustomAttributes(memberInfo, attributeType, inherit);
                }
                else
                {
                    Module module = attributeProvider as Module;
                    if (module != null)
                    {
                        if (!(attributeType != null))
{
                            return Attribute.GetCustomAttributes(module, inherit);
                        }
                        return Attribute.GetCustomAttributes(module, attributeType, inherit);
                    }
                    else
                    {
                        ParameterInfo parameterInfo = attributeProvider as ParameterInfo;
                        if (parameterInfo == null)
{
                            ICustomAttributeProvider customAttributeProvider = (ICustomAttributeProvider)attributeProvider;
                            return (Attribute[])((attributeType != null) ? customAttributeProvider.GetCustomAttributes(attributeType, inherit) : customAttributeProvider.GetCustomAttributes(inherit));
                        }
                        if (!(attributeType != null))
{
                            return Attribute.GetCustomAttributes(parameterInfo, inherit);
                        }
                        return Attribute.GetCustomAttributes(parameterInfo, attributeType, inherit);
                    }
                }
            }
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Assembly, System.Reflection.ICustomAttributeProvider.GetCustomAttributes(), System.Reflection.MemberInfo.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), and System.Module.
Referenced by Newtonsoft.Json.Serialization.JsonTypeReflector.GetAssociateMetadataTypeFromAttribute(), Newtonsoft.Json.Utilities.ReflectionUtils.GetAttribute< T >(), Newtonsoft.Json.Serialization.ReflectionAttributeProvider.GetAttributes(), Newtonsoft.Json.Serialization.ReflectionAttributeProvider.GetAttributes(), and Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes< T >().