Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.CanReadMemberValue
CanReadMemberValue()
static bool Newtonsoft.Json.Utilities.ReflectionUtils.CanReadMemberValue (MemberInfo member, bool nonPublic) inline static
Definition at line 420 of file ReflectionUtils.cs.
        {
            MemberTypes memberTypes = member.MemberType();
            if (memberTypes == 4)
            {
                FieldInfo fieldInfo = (FieldInfo)member;
                return nonPublic || fieldInfo.IsPublic;
            }
            if (memberTypes != 16)
            {
                return false;
            }
            PropertyInfo propertyInfo = (PropertyInfo)member;
            return propertyInfo.CanRead && (nonPublic || propertyInfo.GetGetMethod(nonPublic) != null);
        }
References System.Reflection.PropertyInfo.GetGetMethod(), System.Reflection.FieldInfo.IsPublic, and System.Reflection.MemberInfo.MemberType.
Referenced by Newtonsoft.Json.Utilities.ReflectionObject.Create(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateProperty(), and Newtonsoft.Json.Serialization.DefaultContractResolver.GetExtensionDataMemberForType().