Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable
IsNullable()
static bool Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable (Type t) inline static
Definition at line 168 of file ReflectionUtils.cs.
        {
            ValidationUtils.ArgumentNotNull(t, "t");
            return !t.IsValueType() || ReflectionUtils.IsNullableType(t);
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), and System.Type.IsValueType.
Referenced by Newtonsoft.Json.Utilities.ConvertUtils.ConvertOrCast(), Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GetJsonSchemaType(), Newtonsoft.Json.Serialization.JsonContract.JsonContract(), Newtonsoft.Json.Converters.BinaryConverter.ReadJson(), Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson(), Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryConvert(), and Newtonsoft.Json.Utilities.ConvertUtils.TryConvertInternal().