Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue
GetDefaultValue()
static object Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultValue (Type type) inline static
Definition at line 777 of file ReflectionUtils.cs.
        {
            if (!type.IsValueType())
            {
                return null;
            }
            PrimitiveTypeCode typeCode = ConvertUtils.GetTypeCode(type);
            switch (typeCode)
            {
            case PrimitiveTypeCode.Char:
            case PrimitiveTypeCode.SByte:
            case PrimitiveTypeCode.Int16:
            case PrimitiveTypeCode.UInt16:
            case PrimitiveTypeCode.Int32:
            case PrimitiveTypeCode.Byte:
            case PrimitiveTypeCode.UInt32:
                return 0;
            case PrimitiveTypeCode.CharNullable:
            case PrimitiveTypeCode.BooleanNullable:
            case PrimitiveTypeCode.SByteNullable:
            case PrimitiveTypeCode.Int16Nullable:
            case PrimitiveTypeCode.UInt16Nullable:
            case PrimitiveTypeCode.Int32Nullable:
            case PrimitiveTypeCode.ByteNullable:
            case PrimitiveTypeCode.UInt32Nullable:
            case PrimitiveTypeCode.Int64Nullable:
            case PrimitiveTypeCode.UInt64Nullable:
            case PrimitiveTypeCode.SingleNullable:
            case PrimitiveTypeCode.DoubleNullable:
            case PrimitiveTypeCode.DateTimeNullable:
            case PrimitiveTypeCode.DateTimeOffsetNullable:
            case PrimitiveTypeCode.DecimalNullable:
                break;
            case PrimitiveTypeCode.Boolean:
                return false;
            case PrimitiveTypeCode.Int64:
            case PrimitiveTypeCode.UInt64:
                return 0L;
            case PrimitiveTypeCode.Single:
                return 0f;
            case PrimitiveTypeCode.Double:
                return 0.0;
            case PrimitiveTypeCode.DateTime:
                return default(DateTime);
            case PrimitiveTypeCode.DateTimeOffset:
                return default(DateTimeOffset);
            case PrimitiveTypeCode.Decimal:
                return 0m;
            case PrimitiveTypeCode.Guid:
                return default(Guid);
            default:
                if (typeCode == PrimitiveTypeCode.BigInteger)
                {
                    return default(BigInteger);
                }
                break;
            }
            if (ReflectionUtils.IsNullable(type))
            {
                return null;
            }
            return Activator.CreateInstance(type);
        }
References Newtonsoft.Json.Utilities.BigInteger, System.Activator.CreateInstance(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), System.Type.IsValueType, and System.L.
Referenced by Newtonsoft.Json.Serialization.JsonProperty.GetResolvedDefaultValue(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteDynamicProperty().