Terraria Decompiled: Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition
ImplementsGenericDefinition() [1/2]
static bool Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition (Type type, Type genericInterfaceDefinition) inline static
Definition at line 198 of file ReflectionUtils.cs.
        {
            Type type2;
            return ReflectionUtils.ImplementsGenericDefinition(type, genericInterfaceDefinition, out type2);
        }
References Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition().
Referenced by Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetExtensionDataMemberForType(), Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(), Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract(), Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract(), and Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates().