Terraria Decompiled: System.String.Concat< T >
Concat< T >()
static string System.String.Concat< T > (IEnumerable< T > values) inline static
Definition at line 807 of file String.cs.
        {
            if (values == null)
            {
                throw new ArgumentNullException("values");
            }
            if (typeof(T) == typeof(char))
            {
                using (IEnumerator<char> enumerator = Unsafe.As<IEnumerable<char>>(values).GetEnumerator())
                {
                    if (!enumerator.MoveNext())
                    {
                        return string.Empty;
                    }
                    char c = enumerator.Current;
                    if (!enumerator.MoveNext())
                    {
                        return string.CreateFromChar(c);
                    }
                    StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
                    stringBuilder.Append(c);
                    do
                    {
                        c = enumerator.Current;
                        stringBuilder.Append(c);
                    }
                    while (enumerator.MoveNext());
                    return StringBuilderCache.GetStringAndRelease(stringBuilder);
                }
            }
            string text;
            using (IEnumerator<T> enumerator2 = values.GetEnumerator())
            {
                if (!enumerator2.MoveNext())
                {
                    text = string.Empty;
                }
                else
                {
                    T t = enumerator2.Current;
                    string text2 = ((t != null) ? t.ToString() : null);
                    if (!enumerator2.MoveNext())
                    {
                        text = text2 ?? string.Empty;
                    }
                    else
                    {
                        StringBuilder stringBuilder2 = StringBuilderCache.Acquire(16);
                        stringBuilder2.Append(text2);
                        do
{
                            t = enumerator2.Current;
                            if (t != null)
{
                                stringBuilder2.Append(t.ToString());
                            }
                        }
                        while (enumerator2.MoveNext());
                        text = StringBuilderCache.GetStringAndRelease(stringBuilder2);
                    }
                }
            }
            return text;
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Collections.Generic.IEnumerator< out T >.Current, System.String.GetEnumerator(), System.Text.StringBuilderCache.GetStringAndRelease(), System.Collections.IEnumerator.MoveNext(), System.text, and System.values.