Terraria Decompiled: System.String.IndexOfAny
IndexOfAny() [5/5]
int System.String.IndexOfAny (char[] anyOf, int startIndex, int count) inline
Definition at line 2445 of file String.cs.
        {
            if (anyOf == null)
            {
                throw new ArgumentNullException("anyOf");
            }
            if (startIndex > this.Length)
            {
                throw new ArgumentOutOfRangeException("startIndex", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            if (count > this.Length - startIndex)
            {
                throw new ArgumentOutOfRangeException("count", "Count must be positive and count must refer to a location within the string/array/collection.");
            }
            if (anyOf.Length == 2)
            {
                return this.IndexOfAny(anyOf[0], anyOf[1], startIndex, count);
            }
            if (anyOf.Length == 3)
            {
                return this.IndexOfAny(anyOf[0], anyOf[1], anyOf[2], startIndex, count);
            }
            if (anyOf.Length > 3)
            {
                return this.IndexOfCharArray(anyOf, startIndex, count);
            }
            if (anyOf.Length == 1)
            {
                return this.IndexOf(anyOf[0], startIndex, count);
            }
            return -1;
        }
References System.count, System.String.IndexOf(), System.String.IndexOfAny(), System.String.IndexOfCharArray(), System.String.Length, and System.startIndex.