Terraria Decompiled: System.String.JoinCore
JoinCore() [1/2]
static unsafe string System.String.JoinCore (char * separator, int separatorLength, object[] values) inline static private
Definition at line 1259 of file String.cs.
        {
            if (values == null)
            {
                throw new ArgumentNullException("values");
            }
            if (values.Length == 0)
            {
                return string.Empty;
            }
            object obj = values[0];
            string text = ((obj != null) ? obj.ToString() : null);
            if (values.Length == 1)
            {
                return text ?? string.Empty;
            }
            StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
            stringBuilder.Append(text);
            for (int i = 1; i < values.Length; i++)
            {
                stringBuilder.Append(separator, separatorLength);
                object obj2 = values[i];
                if (obj2 != null)
                {
                    stringBuilder.Append(obj2.ToString());
                }
            }
            return StringBuilderCache.GetStringAndRelease(stringBuilder);
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Text.StringBuilderCache.GetStringAndRelease(), System.obj, System.text, and System.values.