Terraria Decompiled: System.String.SplitInternal
SplitInternal() [3/3]
unsafe string[] System.String.SplitInternal (string separator, string[] separators, int count, StringSplitOptions options) inline private
Definition at line 1857 of file String.cs.
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Count cannot be less than zero.");
            }
            if (options < StringSplitOptions.None || options > StringSplitOptions.RemoveEmptyEntries)
            {
                throw new ArgumentException(SR.Format("Illegal enum value: {0}.", (int)options));
            }
            bool flag = options == StringSplitOptions.RemoveEmptyEntries;
            bool flag2 = separator != null;
            if (!flag2 && (separators == null || separators.Length == 0))
            {
                return this.SplitInternal(null, count, options);
            }
            if (count == 0 || (flag && this.Length == 0))
            {
                return Array.Empty<string>();
            }
            if (count == 1 || (flag2 && separator.Length == 0))
            {
                return new string[] { this };
            }
            if (flag2)
            {
                return this.SplitInternal(separator, count, options);
            }
            Span<int> span = new Span<int>(stackalloc byte[(UIntPtr)512], 128);
            ValueListBuilder<int> valueListBuilder = new ValueListBuilder<int>(span);
            Span<int> span2 = new Span<int>(stackalloc byte[(UIntPtr)512], 128);
            ValueListBuilder<int> valueListBuilder2 = new ValueListBuilder<int>(span2);
            this.MakeSeparatorList(separators, ref valueListBuilder, ref valueListBuilder2);
            ReadOnlySpan<int> readOnlySpan = valueListBuilder.AsSpan();
            ReadOnlySpan<int> readOnlySpan2 = valueListBuilder2.AsSpan();
            if (readOnlySpan.Length == 0)
            {
                return new string[] { this };
            }
            string[] array = (flag ? this.SplitOmitEmptyEntries(readOnlySpan, readOnlySpan2, 0, count) : this.SplitKeepEmptyEntries(readOnlySpan, readOnlySpan2, 0, count));
            valueListBuilder.Dispose();
            valueListBuilder2.Dispose();
            return array;
        }
References System.array, System.Collections.Generic.ValueListBuilder< T >.AsSpan(), System.count, System.Collections.Generic.ValueListBuilder< T >.Dispose(), SR.Format(), System.ReadOnlySpan< T >.Length, System.String.Length, System.String.MakeSeparatorList(), System.options, System.String.SplitInternal(), System.String.SplitKeepEmptyEntries(), and System.String.SplitOmitEmptyEntries().