Terraria Decompiled: System.String.Replace
Replace() [2/4]
unsafe string System.String.Replace (string oldValue, string newValue) inline
Definition at line 1688 of file String.cs.
        {
            if (oldValue == null)
            {
                throw new ArgumentNullException("oldValue");
            }
            if (oldValue.Length == 0)
            {
                throw new ArgumentException("String cannot be of zero length.", "oldValue");
            }
            if (newValue == null)
            {
                newValue = string.Empty;
            }
            Span<int> span = new Span<int>(stackalloc byte[(UIntPtr)512], 128);
            ValueListBuilder<int> valueListBuilder = new ValueListBuilder<int>(span);
            fixed (char* ptr = &this._firstChar)
            {
                char* ptr2 = ptr;
                int i = 0;
                int num = this.Length - oldValue.Length;
                IL_00B6:
                while (i <= num)
                {
                    char* ptr3 = ptr2 + i;
                    for (int j = 0; j < oldValue.Length; j++)
                    {
                        if (ptr3[j] != oldValue[j])
{
                            i++;
                            goto IL_00B6;
                        }
                    }
                    valueListBuilder.Append(i);
                    i += oldValue.Length;
                }
            }
            if (valueListBuilder.Length == 0)
            {
                return this;
            }
            string text = this.ReplaceHelper(oldValue.Length, newValue, valueListBuilder.AsSpan());
            valueListBuilder.Dispose();
            return text;
        }
References System.String._firstChar, System.Collections.Generic.ValueListBuilder< T >.Append(), System.Collections.Generic.ValueListBuilder< T >.AsSpan(), System.Collections.Generic.ValueListBuilder< T >.Dispose(), System.Collections.Generic.ValueListBuilder< T >.Length, System.String.ReplaceHelper(), and System.text.