Terraria Decompiled: System.String.StartsWith
StartsWith() [4/4]
bool System.String.StartsWith (string value, StringComparison comparisonType) inline
Definition at line 635 of file String.cs.
        {
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            if (this == value)
            {
                string.CheckStringComparison(comparisonType);
                return true;
            }
            if (value.Length == 0)
            {
                string.CheckStringComparison(comparisonType);
                return true;
            }
            switch (comparisonType)
            {
            case StringComparison.CurrentCulture:
                return CultureInfo.CurrentCulture.CompareInfo.IsPrefix(this, value, CompareOptions.None);
            case StringComparison.CurrentCultureIgnoreCase:
                return CultureInfo.CurrentCulture.CompareInfo.IsPrefix(this, value, CompareOptions.IgnoreCase);
            case StringComparison.InvariantCulture:
                return CompareInfo.Invariant.IsPrefix(this, value, CompareOptions.None);
            case StringComparison.InvariantCultureIgnoreCase:
                return CompareInfo.Invariant.IsPrefix(this, value, CompareOptions.IgnoreCase);
            case StringComparison.Ordinal:
                return this.Length >= value.Length && this._firstChar == value._firstChar && (value.Length == 1 || SpanHelpers.SequenceEqual(Unsafe.As<char, byte>(this.GetRawStringData()), Unsafe.As<char, byte>(value.GetRawStringData()), (ulong)((long)value.Length * 2L)));
            case StringComparison.OrdinalIgnoreCase:
                return this.Length >= value.Length && CompareInfo.CompareOrdinalIgnoreCase(this, 0, value.Length, value, 0, value.Length) == 0;
            default:
                throw new ArgumentException("The string comparison type passed in is currently not supported.", "comparisonType");
            }
        }
References System.Globalization.CultureInfo.CompareInfo, System.Globalization.CompareInfo.CompareOrdinalIgnoreCase(), System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.Globalization.CompareInfo.Invariant, System.Globalization.CompareInfo.IsPrefix(), System.L, System.SpanHelpers.SequenceEqual(), and System.value.