Terraria Decompiled: System.String.SplitInternal
SplitInternal() [1/3]
unsafe string[] System.String.SplitInternal (ReadOnlySpan< char > separators, int count, StringSplitOptions options) inline private
Definition at line 1800 of file String.cs.
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Count cannot be less than zero.");
            }
            if (options < StringSplitOptions.None || options > StringSplitOptions.RemoveEmptyEntries)
            {
                throw new ArgumentException(SR.Format("Illegal enum value: {0}.", options));
            }
            bool flag = options == StringSplitOptions.RemoveEmptyEntries;
            if (count == 0 || (flag && this.Length == 0))
            {
                return Array.Empty<string>();
            }
            if (count == 1)
            {
                return new string[] { this };
            }
            Span<int> span = new Span<int>(stackalloc byte[(UIntPtr)512], 128);
            ValueListBuilder<int> valueListBuilder = new ValueListBuilder<int>(span);
            this.MakeSeparatorList(separators, ref valueListBuilder);
            ReadOnlySpan<int> readOnlySpan = valueListBuilder.AsSpan();
            if (readOnlySpan.Length == 0)
            {
                return new string[] { this };
            }
            string[] array = (flag ? this.SplitOmitEmptyEntries(readOnlySpan, default(ReadOnlySpan<int>), 1, count) : this.SplitKeepEmptyEntries(readOnlySpan, default(ReadOnlySpan<int>), 1, count));
            valueListBuilder.Dispose();
            return array;
        }
References System.array, System.Collections.Generic.ValueListBuilder< T >.AsSpan(), System.count, System.Collections.Generic.ValueListBuilder< T >.Dispose(), SR.Format(), System.ReadOnlySpan< T >.Length, System.String.Length, System.String.MakeSeparatorList(), System.options, System.String.SplitKeepEmptyEntries(), and System.String.SplitOmitEmptyEntries().
Referenced by System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), System.String.Split(), and System.String.SplitInternal().