Terraria Decompiled: System.String.TrimHelper
TrimHelper()
unsafe string System.String.TrimHelper (char * trimChars, int trimCharsLength, string::TrimType trimType) inline private
Definition at line 2301 of file String.cs.
        {
            int i = this.Length - 1;
            int j = 0;
            if (trimType != string.TrimType.Tail)
            {
                for (j = 0; j < this.Length; j++)
                {
                    char c = this[j];
                    int num = 0;
                    while (num < trimCharsLength && trimChars[num] != c)
                    {
                        num++;
                    }
                    if (num == trimCharsLength)
                    {
                        break;
                    }
                }
            }
            if (trimType != string.TrimType.Head)
            {
                for (i = this.Length - 1; i >= j; i--)
                {
                    char c2 = this[i];
                    int num2 = 0;
                    while (num2 < trimCharsLength && trimChars[num2] != c2)
                    {
                        num2++;
                    }
                    if (num2 == trimCharsLength)
                    {
                        break;
                    }
                }
            }
            return this.CreateTrimmedString(j, i);
        }
References System.String.CreateTrimmedString(), and System.String.Length.
Referenced by System.String.Trim(), System.String.Trim(), System.String.TrimEnd(), System.String.TrimEnd(), System.String.TrimStart(), and System.String.TrimStart().