Terraria Decompiled: System.String.MakeSeparatorList
MakeSeparatorList() [1/3]
unsafe void System.String.MakeSeparatorList (ReadOnlySpan< char > separators, ref ValueListBuilder< int > sepListBuilder) inline private
Definition at line 1991 of file String.cs.
        {
            switch (separators.Length)
            {
            case 0:
            {
                for (int i = 0; i < this.Length; i++)
                {
                    if (char.IsWhiteSpace(this[i]))
                    {
                        sepListBuilder.Append(i);
                    }
                }
                return;
            }
            case 1:
            {
                char c = (char)(*separators[0]);
                for (int j = 0; j < this.Length; j++)
                {
                    if (this[j] == c)
                    {
                        sepListBuilder.Append(j);
                    }
                }
                return;
            }
            case 2:
            {
                char c = (char)(*separators[0]);
                char c2 = (char)(*separators[1]);
                for (int k = 0; k < this.Length; k++)
                {
                    char c3 = this[k];
                    if (c3 == c || c3 == c2)
                    {
                        sepListBuilder.Append(k);
                    }
                }
                return;
            }
            case 3:
            {
                char c = (char)(*separators[0]);
                char c2 = (char)(*separators[1]);
                char c4 = (char)(*separators[2]);
                for (int l = 0; l < this.Length; l++)
                {
                    char c5 = this[l];
                    if (c5 == c || c5 == c2 || c5 == c4)
                    {
                        sepListBuilder.Append(l);
                    }
                }
                return;
            }
            default:
            {
                string.ProbabilisticMap probabilisticMap = default(string.ProbabilisticMap);
                uint* ptr = (uint*)(&probabilisticMap);
                string.InitializeProbabilisticMap(ptr, separators);
                for (int m = 0; m < this.Length; m++)
                {
                    char c6 = this[m];
                    if (string.IsCharBitSet(ptr, (byte)c6) && string.IsCharBitSet(ptr, (byte)(c6 >> 8)) && separators.Contains(c6))
                    {
                        sepListBuilder.Append(m);
                    }
                }
                return;
            }
            }
        }
References System.String.IsCharBitSet(), System.ReadOnlySpan< T >.Length, and System.String.Length.
Referenced by System.String.SplitInternal(), System.String.SplitInternal(), and System.String.SplitInternal().