Terraria Decompiled: System.String.SplitInternal
SplitInternal() [2/3]
unsafe string[] System.String.SplitInternal (string separator, int count, StringSplitOptions options) inline private
Definition at line 1903 of file String.cs.
        {
            Span<int> span = new Span<int>(stackalloc byte[(UIntPtr)512], 128);
            ValueListBuilder<int> valueListBuilder = new ValueListBuilder<int>(span);
            this.MakeSeparatorList(separator, ref valueListBuilder);
            ReadOnlySpan<int> readOnlySpan = valueListBuilder.AsSpan();
            if (readOnlySpan.Length == 0)
            {
                return new string[] { this };
            }
            string[] array = ((options == StringSplitOptions.RemoveEmptyEntries) ? this.SplitOmitEmptyEntries(readOnlySpan, default(ReadOnlySpan<int>), separator.Length, count) : this.SplitKeepEmptyEntries(readOnlySpan, default(ReadOnlySpan<int>), separator.Length, count));
            valueListBuilder.Dispose();
            return array;
        }
References System.array, System.Collections.Generic.ValueListBuilder< T >.AsSpan(), System.count, System.Collections.Generic.ValueListBuilder< T >.Dispose(), System.ReadOnlySpan< T >.Length, System.String.MakeSeparatorList(), System.options, System.String.SplitKeepEmptyEntries(), and System.String.SplitOmitEmptyEntries().