Terraria Decompiled: System.String.ReplaceCore
ReplaceCore()
unsafe string System.String.ReplaceCore (string oldValue, string newValue, CultureInfo culture, CompareOptions options) inline private
Definition at line 1585 of file String.cs.
        {
            if (oldValue == null)
            {
                throw new ArgumentNullException("oldValue");
            }
            if (oldValue.Length == 0)
            {
                throw new ArgumentException("String cannot be of zero length.", "oldValue");
            }
            if (newValue == null)
            {
                newValue = string.Empty;
            }
            CultureInfo cultureInfo = culture ?? CultureInfo.CurrentCulture;
            StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
            int num = 0;
            int num2 = 0;
            bool flag = false;
            CompareInfo compareInfo = cultureInfo.CompareInfo;
            for (;;)
            {
                int num3 = compareInfo.IndexOf(this, oldValue, num, this.Length - num, options, &num2);
                if (num3 >= 0)
                {
                    stringBuilder.Append(this, num, num3 - num);
                    stringBuilder.Append(newValue);
                    num = num3 + num2;
                    flag = true;
                }
                else
                {
                    if (!flag)
                    {
                        break;
                    }
                    stringBuilder.Append(this, num, this.Length - num);
                }
                if (num3 < 0)
                {
                    goto Block_7;
                }
            }
            StringBuilderCache.Release(stringBuilder);
            return this;
            Block_7:
            return StringBuilderCache.GetStringAndRelease(stringBuilder);
        }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.Globalization.CultureInfo.CompareInfo, System.culture, System.Globalization.CultureInfo.CurrentCulture, System.Text.StringBuilderCache.GetStringAndRelease(), System.Globalization.CompareInfo.IndexOf(), System.String.Length, System.options, and System.Text.StringBuilderCache.Release().
Referenced by System.String.Replace(), and System.String.Replace().