Terraria Decompiled: System.Buffers.Text.Base64.EncodeToUtf8
EncodeToUtf8()
static OperationStatus System.Buffers.Text.Base64.EncodeToUtf8 (ReadOnlySpan< byte > bytes, Span< byte > utf8, out int bytesConsumed, out int bytesWritten, bool isFinalBlock = true) inline static
Definition at line 258 of file Base64.cs.
        {
            ref byte reference = ref MemoryMarshal.GetReference<byte>(bytes);
            ref byte reference2 = ref MemoryMarshal.GetReference<byte>(utf8);
            int length = bytes.Length;
            int length2 = utf8.Length;
            int num;
            if (length <= 1610612733 && length2 >= Base64.GetMaxEncodedToUtf8Length(length))
            {
                num = length - 2;
            }
            else
            {
                num = (length2 >> 2) * 3 - 2;
            }
            int i = 0;
            int num2 = 0;
            ref byte ptr = ref Base64.s_encodingMap[0];
            while (i < num)
            {
                int num3 = Base64.Encode(Unsafe.Add<byte>(ref reference, i), ref ptr);
                Unsafe.WriteUnaligned<int>(Unsafe.Add<byte>(ref reference2, num2), num3);
                num2 += 4;
                i += 3;
            }
            if (num != length - 2)
            {
                bytesConsumed = i;
                bytesWritten = num2;
                return OperationStatus.DestinationTooSmall;
            }
            if (isFinalBlock)
            {
                if (i == length - 1)
                {
                    int num3 = Base64.EncodeAndPadTwo(Unsafe.Add<byte>(ref reference, i), ref ptr);
                    Unsafe.WriteUnaligned<int>(Unsafe.Add<byte>(ref reference2, num2), num3);
                    num2 += 4;
                    i++;
                }
                else if (i == length - 2)
                {
                    int num3 = Base64.EncodeAndPadOne(Unsafe.Add<byte>(ref reference, i), ref ptr);
                    Unsafe.WriteUnaligned<int>(Unsafe.Add<byte>(ref reference2, num2), num3);
                    num2 += 4;
                    i += 2;
                }
                bytesConsumed = i;
                bytesWritten = num2;
                return OperationStatus.Done;
            }
            bytesConsumed = i;
            bytesWritten = num2;
            return OperationStatus.NeedMoreData;
        }
References System.Buffers.Text.Base64.Encode(), System.Buffers.Text.Base64.EncodeAndPadOne(), System.Buffers.Text.Base64.EncodeAndPadTwo(), System.Buffers.Text.Base64.GetMaxEncodedToUtf8Length(), System.length, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, and System.Buffers.Text.Base64.s_encodingMap.