Terraria Decompiled: System.MonoCustomAttrs.GetCustomAttributes
GetCustomAttributes() [2/2]
static object[] System.MonoCustomAttrs.GetCustomAttributes (ICustomAttributeProvider obj, Type attributeType, bool inherit) inline static package
Definition at line 151 of file MonoCustomAttrs.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj");
            }
            if (attributeType == null)
            {
                throw new ArgumentNullException("attributeType");
            }
            if (attributeType == typeof(MonoCustomAttrs))
            {
                attributeType = null;
            }
            object[] array = MonoCustomAttrs.GetCustomAttributesBase(obj, attributeType, false);
            if (!inherit && array.Length == 1)
            {
                if (array[0] == null)
                {
                    throw new CustomAttributeFormatException("Invalid custom attribute format");
                }
                object[] array2;
                if (attributeType != null)
                {
                    if (attributeType.IsAssignableFrom(array[0].GetType()))
                    {
                        array2 = (object[])Array.CreateInstance(attributeType, 1);
                        array2[0] = array[0];
                    }
                    else
                    {
                        array2 = (object[])Array.CreateInstance(attributeType, 0);
                    }
                }
                else
                {
                    array2 = (object[])Array.CreateInstance(array[0].GetType(), 1);
                    array2[0] = array[0];
                }
                return array2;
            }
            else
            {
                if (inherit && MonoCustomAttrs.GetBase(obj) == null)
                {
                    inherit = false;
                }
                if (attributeType != null && attributeType.IsSealed && inherit && !MonoCustomAttrs.RetrieveAttributeUsage(attributeType).Inherited)
                {
                    inherit = false;
                }
                int num = Math.Max(array.Length, 16);
                ICustomAttributeProvider customAttributeProvider = obj;
                List<object> list;
                object[] array4;
                if (inherit)
                {
                    Dictionary<Type, MonoCustomAttrs.AttributeInfo> dictionary = new Dictionary<Type, MonoCustomAttrs.AttributeInfo>(num);
                    int num2 = 0;
                    list = new List<object>(num);
                    for (;;)
                    {
                        foreach (object obj2 in array)
{
                            if (obj2 == null)
{
                                goto Block_22;
                            }
                            Type type = obj2.GetType();
                            if (!(attributeType != null) || attributeType.IsAssignableFrom(type))
{
                                MonoCustomAttrs.AttributeInfo attributeInfo;
                                AttributeUsageAttribute attributeUsageAttribute;
                                if (dictionary.TryGetValue(type, out attributeInfo))
{
                                    attributeUsageAttribute = attributeInfo.Usage;
                                }
                                else
{
                                    attributeUsageAttribute = MonoCustomAttrs.RetrieveAttributeUsage(type);
                                }
                                if ((num2 == 0 || attributeUsageAttribute.Inherited) && (attributeUsageAttribute.AllowMultiple || attributeInfo == null || (attributeInfo != null && attributeInfo.InheritanceLevel == num2)))
{
                                    list.Add(obj2);
                                }
                                if (attributeInfo == null)
{
                                    dictionary.Add(type, new MonoCustomAttrs.AttributeInfo(attributeUsageAttribute, num2));
                                }
                            }
                        }
                        if ((customAttributeProvider = MonoCustomAttrs.GetBase(customAttributeProvider)) != null)
{
                            num2++;
                            array = MonoCustomAttrs.GetCustomAttributesBase(customAttributeProvider, attributeType, true);
                        }
                        if (!inherit || customAttributeProvider == null)
{
                            goto IL_02CF;
                        }
                    }
                    Block_22:
                    throw new CustomAttributeFormatException("Invalid custom attribute format");
                    IL_02CF:
                    if (attributeType == null || attributeType.IsValueType)
                    {
                        object[] array3 = new Attribute[list.Count];
                        array4 = array3;
                    }
                    else
                    {
                        array4 = Array.CreateInstance(attributeType, list.Count) as object[];
                    }
                    list.CopyTo(array4, 0);
                    return array4;
                }
                if (attributeType == null)
                {
                    object[] array3 = array;
                    for (int i = 0; i < array3.Length; i++)
                    {
                        if (array3[i] == null)
{
                            throw new CustomAttributeFormatException("Invalid custom attribute format");
                        }
                    }
                    Attribute[] array5 = new Attribute[array.Length];
                    array.CopyTo(array5, 0);
                    return array5;
                }
                list = new List<object>(num);
                foreach (object obj3 in array)
                {
                    if (obj3 == null)
                    {
                        throw new CustomAttributeFormatException("Invalid custom attribute format");
                    }
                    Type type2 = obj3.GetType();
                    if (!(attributeType != null) || attributeType.IsAssignableFrom(type2))
                    {
                        list.Add(obj3);
                    }
                }
                if (attributeType == null || attributeType.IsValueType)
                {
                    object[] array3 = new Attribute[list.Count];
                    array4 = array3;
                }
                else
                {
                    array4 = Array.CreateInstance(attributeType, list.Count) as object[];
                }
                list.CopyTo(array4, 0);
                return array4;
            }
        }
References System.AttributeUsageAttribute.AllowMultiple, System.array, System.Array.CopyTo(), System.Array.CreateInstance(), System.dictionary, System.MonoCustomAttrs.GetBase(), System.MonoCustomAttrs.GetCustomAttributesBase(), System.MonoCustomAttrs.AttributeInfo.InheritanceLevel, System.AttributeUsageAttribute.Inherited, System.Type.IsAssignableFrom(), System.Type.IsSealed, System.Type.IsValueType, System.list, System.Math.Max(), System.obj, System.MonoCustomAttrs.RetrieveAttributeUsage(), and System.MonoCustomAttrs.AttributeInfo.Usage.
Referenced by System.Reflection.Emit.AssemblyBuilder.GetCustomAttributes(), System.Reflection.Emit.FieldBuilder.GetCustomAttributes(), System.Reflection.Emit.MethodBuilder.GetCustomAttributes(), System.Reflection.MonoArrayMethod.GetCustomAttributes(), System.Reflection.RuntimeAssembly.GetCustomAttributes(), System.Reflection.RuntimeConstructorInfo.GetCustomAttributes(), System.Reflection.RuntimeEventInfo.GetCustomAttributes(), System.Reflection.RuntimeFieldInfo.GetCustomAttributes(), System.Reflection.RuntimeMethodInfo.GetCustomAttributes(), System.Reflection.RuntimeModule.GetCustomAttributes(), System.Reflection.RuntimeParameterInfo.GetCustomAttributes(), System.Reflection.RuntimePropertyInfo.GetCustomAttributes(), System.RuntimeType.GetCustomAttributes(), System.MonoCustomAttrs.GetCustomAttributes(), System.Reflection.Emit.AssemblyBuilder.GetCustomAttributes(), System.Reflection.Emit.FieldBuilder.GetCustomAttributes(), System.Reflection.Emit.MethodBuilder.GetCustomAttributes(), System.Reflection.MonoArrayMethod.GetCustomAttributes(), System.Reflection.RuntimeAssembly.GetCustomAttributes(), System.Reflection.RuntimeConstructorInfo.GetCustomAttributes(), System.Reflection.RuntimeEventInfo.GetCustomAttributes(), System.Reflection.RuntimeFieldInfo.GetCustomAttributes(), System.Reflection.RuntimeMethodInfo.GetCustomAttributes(), System.Reflection.RuntimeModule.GetCustomAttributes(), System.Reflection.RuntimeParameterInfo.GetCustomAttributes(), System.Reflection.RuntimePropertyInfo.GetCustomAttributes(), System.RuntimeType.GetCustomAttributes(), System.Attribute.InternalGetCustomAttributes(), System.Attribute.InternalGetCustomAttributes(), and System.MonoCustomAttrs.RetrieveAttributeUsageNoCache().