Terraria Decompiled: System.MonoCustomAttrs.GetCustomAttributesDataBase
GetCustomAttributesDataBase()
static IList< CustomAttributeData > System.MonoCustomAttrs.GetCustomAttributesDataBase (ICustomAttributeProvider obj, Type attributeType, bool inheritedOnly) inline static package
Definition at line 474 of file MonoCustomAttrs.cs.
        {
            CustomAttributeData[] array;
            if (MonoCustomAttrs.IsUserCattrProvider(obj))
            {
                array = Array.Empty<CustomAttributeData>();
            }
            else
            {
                array = MonoCustomAttrs.GetCustomAttributesDataInternal(obj);
            }
            if (!inheritedOnly)
            {
                CustomAttributeData[] pseudoCustomAttributesData = MonoCustomAttrs.GetPseudoCustomAttributesData(obj, attributeType);
                if (pseudoCustomAttributesData != null)
                {
                    if (array.Length == 0)
                    {
                        return Array.AsReadOnly<CustomAttributeData>(pseudoCustomAttributesData);
                    }
                    CustomAttributeData[] array2 = new CustomAttributeData[array.Length + pseudoCustomAttributesData.Length];
                    Array.Copy(array, array2, array.Length);
                    Array.Copy(pseudoCustomAttributesData, 0, array2, array.Length, pseudoCustomAttributesData.Length);
                    return Array.AsReadOnly<CustomAttributeData>(array2);
                }
            }
            return Array.AsReadOnly<CustomAttributeData>(array);
        }
References System.array, System.Array.Copy(), System.MonoCustomAttrs.GetCustomAttributesDataInternal(), System.MonoCustomAttrs.GetPseudoCustomAttributesData(), System.MonoCustomAttrs.IsUserCattrProvider(), and System.obj.
Referenced by System.MonoCustomAttrs.GetCustomAttributesData(), and System.MonoCustomAttrs.GetCustomAttributesData().