Terraria Decompiled: System.MonoCustomAttrs.IsDefined
IsDefined()
static bool System.MonoCustomAttrs.IsDefined (ICustomAttributeProvider obj, Type attributeType, bool inherit) inline static package
Definition at line 590 of file MonoCustomAttrs.cs.
        {
            if (attributeType == null)
            {
                throw new ArgumentNullException("attributeType");
            }
            AttributeUsageAttribute attributeUsageAttribute = null;
            while (!MonoCustomAttrs.IsUserCattrProvider(obj))
            {
                if (MonoCustomAttrs.IsDefinedInternal(obj, attributeType))
                {
                    return true;
                }
                object[] pseudoCustomAttributes = MonoCustomAttrs.GetPseudoCustomAttributes(obj, attributeType);
                if (pseudoCustomAttributes != null)
                {
                    for (int i = 0; i < pseudoCustomAttributes.Length; i++)
                    {
                        if (attributeType.IsAssignableFrom(pseudoCustomAttributes[i].GetType()))
{
                            return true;
                        }
                    }
                }
                if (attributeUsageAttribute == null)
                {
                    if (!inherit)
                    {
                        return false;
                    }
                    attributeUsageAttribute = MonoCustomAttrs.RetrieveAttributeUsage(attributeType);
                    if (!attributeUsageAttribute.Inherited)
                    {
                        return false;
                    }
                }
                obj = MonoCustomAttrs.GetBase(obj);
                if (obj == null)
                {
                    return false;
                }
            }
            return obj.IsDefined(attributeType, inherit);
        }
References System.MonoCustomAttrs.GetBase(), System.MonoCustomAttrs.GetPseudoCustomAttributes(), System.AttributeUsageAttribute.Inherited, System.Type.IsAssignableFrom(), System.Reflection.ICustomAttributeProvider.IsDefined(), System.MonoCustomAttrs.IsDefinedInternal(), System.MonoCustomAttrs.IsUserCattrProvider(), System.obj, and System.MonoCustomAttrs.RetrieveAttributeUsage().
Referenced by System.Attribute.InternalIsDefined(), System.Attribute.InternalIsDefined(), System.Reflection.Emit.AssemblyBuilder.IsDefined(), System.Reflection.Emit.TypeBuilder.IsDefined(), System.Reflection.MonoArrayMethod.IsDefined(), System.Reflection.RuntimeAssembly.IsDefined(), System.Reflection.RuntimeConstructorInfo.IsDefined(), System.Reflection.RuntimeEventInfo.IsDefined(), System.Reflection.RuntimeFieldInfo.IsDefined(), System.Reflection.RuntimeMethodInfo.IsDefined(), System.Reflection.RuntimeModule.IsDefined(), System.Reflection.RuntimeParameterInfo.IsDefined(), System.Reflection.RuntimePropertyInfo.IsDefined(), and System.RuntimeType.IsDefined().