Terraria Decompiled: System.MonoCustomAttrs.GetCustomAttributesData
GetCustomAttributesData() [2/2]
static IList< CustomAttributeData > System.MonoCustomAttrs.GetCustomAttributesData (ICustomAttributeProvider obj, Type attributeType, bool inherit) inline static package
Definition at line 344 of file MonoCustomAttrs.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj");
            }
            if (attributeType == null)
            {
                throw new ArgumentNullException("attributeType");
            }
            if (attributeType == typeof(MonoCustomAttrs))
            {
                attributeType = null;
            }
            IList<CustomAttributeData> list = MonoCustomAttrs.GetCustomAttributesDataBase(obj, attributeType, false);
            if (!inherit && list.Count == 1)
            {
                if (list[0] == null)
                {
                    throw new CustomAttributeFormatException("Invalid custom attribute data format");
                }
                IList<CustomAttributeData> list2;
                if (attributeType != null)
                {
                    if (attributeType.IsAssignableFrom(list[0].AttributeType))
                    {
                        list2 = new CustomAttributeData[] { list[0] };
                    }
                    else
                    {
                        list2 = Array.Empty<CustomAttributeData>();
                    }
                }
                else
                {
                    list2 = new CustomAttributeData[] { list[0] };
                }
                return list2;
            }
            else
            {
                if (inherit && MonoCustomAttrs.GetBase(obj) == null)
                {
                    inherit = false;
                }
                if (attributeType != null && attributeType.IsSealed && inherit && !MonoCustomAttrs.RetrieveAttributeUsage(attributeType).Inherited)
                {
                    inherit = false;
                }
                int num = Math.Max(list.Count, 16);
                List<CustomAttributeData> list3 = null;
                ICustomAttributeProvider customAttributeProvider = obj;
                if (inherit)
                {
                    Dictionary<Type, MonoCustomAttrs.AttributeInfo> dictionary = new Dictionary<Type, MonoCustomAttrs.AttributeInfo>(num);
                    int num2 = 0;
                    list3 = new List<CustomAttributeData>(num);
                    do
                    {
                        foreach (CustomAttributeData customAttributeData in list)
{
                            if (customAttributeData == null)
{
                                throw new CustomAttributeFormatException("Invalid custom attribute data format");
                            }
                            Type attributeType2 = customAttributeData.AttributeType;
                            if (!(attributeType != null) || attributeType.IsAssignableFrom(attributeType2))
{
                                MonoCustomAttrs.AttributeInfo attributeInfo;
                                AttributeUsageAttribute attributeUsageAttribute;
                                if (dictionary.TryGetValue(attributeType2, out attributeInfo))
{
                                    attributeUsageAttribute = attributeInfo.Usage;
                                }
                                else
{
                                    attributeUsageAttribute = MonoCustomAttrs.RetrieveAttributeUsage(attributeType2);
                                }
                                if ((num2 == 0 || attributeUsageAttribute.Inherited) && (attributeUsageAttribute.AllowMultiple || attributeInfo == null || (attributeInfo != null && attributeInfo.InheritanceLevel == num2)))
{
                                    list3.Add(customAttributeData);
                                }
                                if (attributeInfo == null)
{
                                    dictionary.Add(attributeType2, new MonoCustomAttrs.AttributeInfo(attributeUsageAttribute, num2));
                                }
                            }
                        }
                        if ((customAttributeProvider = MonoCustomAttrs.GetBase(customAttributeProvider)) != null)
{
                            num2++;
                            list = MonoCustomAttrs.GetCustomAttributesDataBase(customAttributeProvider, attributeType, true);
                        }
                    }
                    while (inherit && customAttributeProvider != null);
                    return list3.ToArray();
                }
                if (attributeType == null)
                {
                    using (IEnumerator<CustomAttributeData> enumerator = list.GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            if (enumerator.Current == null)
{
                                throw new CustomAttributeFormatException("Invalid custom attribute data format");
                            }
                        }
                    }
                    CustomAttributeData[] array = new CustomAttributeData[list.Count];
                    list.CopyTo(array, 0);
                    return array;
                }
                list3 = new List<CustomAttributeData>(num);
                foreach (CustomAttributeData customAttributeData2 in list)
                {
                    if (customAttributeData2 == null)
                    {
                        throw new CustomAttributeFormatException("Invalid custom attribute data format");
                    }
                    if (attributeType.IsAssignableFrom(customAttributeData2.AttributeType))
                    {
                        list3.Add(customAttributeData2);
                    }
                }
                return list3.ToArray();
            }
        }
References System.Collections.Generic.List< T >.Add(), System.AttributeUsageAttribute.AllowMultiple, System.array, System.Reflection.CustomAttributeData.AttributeType, System.Collections.Generic.IEnumerator< out T >.Current, System.dictionary, System.MonoCustomAttrs.GetBase(), System.MonoCustomAttrs.GetCustomAttributesDataBase(), System.MonoCustomAttrs.AttributeInfo.InheritanceLevel, System.AttributeUsageAttribute.Inherited, System.Type.IsAssignableFrom(), System.Type.IsSealed, System.list, System.Math.Max(), System.Collections.IEnumerator.MoveNext(), System.obj, System.MonoCustomAttrs.RetrieveAttributeUsage(), System.Collections.Generic.List< T >.ToArray(), and System.MonoCustomAttrs.AttributeInfo.Usage.