Terraria Decompiled: System.MonoCustomAttrs.GetCustomAttributesBase
GetCustomAttributesBase()
static object[] System.MonoCustomAttrs.GetCustomAttributesBase (ICustomAttributeProvider obj, Type attributeType, bool inheritedOnly) inline static package
Definition at line 123 of file MonoCustomAttrs.cs.
        {
            object[] array;
            if (MonoCustomAttrs.IsUserCattrProvider(obj))
            {
                array = obj.GetCustomAttributes(attributeType, true);
            }
            else
            {
                object[] array2 = MonoCustomAttrs.GetCustomAttributesInternal(obj, attributeType, false);
                array = array2;
            }
            if (!inheritedOnly)
            {
                object[] pseudoCustomAttributes = MonoCustomAttrs.GetPseudoCustomAttributes(obj, attributeType);
                if (pseudoCustomAttributes != null)
                {
                    object[] array2 = new Attribute[array.Length + pseudoCustomAttributes.Length];
                    object[] array3 = array2;
                    Array.Copy(array, array3, array.Length);
                    Array.Copy(pseudoCustomAttributes, 0, array3, array.Length, pseudoCustomAttributes.Length);
                    return array3;
                }
            }
            return array;
        }
References System.array, System.Array.Copy(), System.MonoCustomAttrs.GetCustomAttributesInternal(), System.MonoCustomAttrs.GetPseudoCustomAttributes(), System.MonoCustomAttrs.IsUserCattrProvider(), and System.obj.
Referenced by System.MonoCustomAttrs.GetCustomAttributes(), and System.MonoCustomAttrs.GetCustomAttributes().