Terraria Decompiled: System.MonoCustomAttrs.GetPseudoCustomAttributes
GetPseudoCustomAttributes() [1/2]
static object[] System.MonoCustomAttrs.GetPseudoCustomAttributes (ICustomAttributeProvider obj, Type attributeType) inline static package
Definition at line 37 of file MonoCustomAttrs.cs.
        {
            object[] array = null;
            RuntimeMethodInfo runtimeMethodInfo = obj as RuntimeMethodInfo;
            if (runtimeMethodInfo != null)
            {
                array = runtimeMethodInfo.GetPseudoCustomAttributes();
            }
            else
            {
                RuntimeFieldInfo runtimeFieldInfo = obj as RuntimeFieldInfo;
                if (runtimeFieldInfo != null)
                {
                    array = runtimeFieldInfo.GetPseudoCustomAttributes();
                }
                else
                {
                    RuntimeParameterInfo runtimeParameterInfo = obj as RuntimeParameterInfo;
                    if (runtimeParameterInfo != null)
                    {
                        array = runtimeParameterInfo.GetPseudoCustomAttributes();
                    }
                    else
                    {
                        Type type = obj as Type;
                        if (type != null)
{
                            array = MonoCustomAttrs.GetPseudoCustomAttributes(type);
                        }
                    }
                }
            }
            if (attributeType != null && array != null)
            {
                int i = 0;
                while (i < array.Length)
                {
                    if (attributeType.IsAssignableFrom(array[i].GetType()))
                    {
                        if (array.Length == 1)
{
                            return array;
                        }
                        return new object[] { array[i] };
                    }
                    else
                    {
                        i++;
                    }
                }
                return Array.Empty<object>();
            }
            return array;
        }
References System.array, System.Reflection.FieldInfo.GetPseudoCustomAttributes(), System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes(), System.Reflection.RuntimeParameterInfo.GetPseudoCustomAttributes(), System.MonoCustomAttrs.GetPseudoCustomAttributes(), System.Type.IsAssignableFrom(), and System.obj.
Referenced by System.MonoCustomAttrs.GetCustomAttributesBase(), System.MonoCustomAttrs.GetPseudoCustomAttributes(), and System.MonoCustomAttrs.IsDefined().