Terraria Decompiled: System.MonoCustomAttrs.GetPseudoCustomAttributesData
GetPseudoCustomAttributesData() [1/2]
static CustomAttributeData[] System.MonoCustomAttrs.GetPseudoCustomAttributesData (ICustomAttributeProvider obj, Type attributeType) inline static package
Definition at line 504 of file MonoCustomAttrs.cs.
        {
            CustomAttributeData[] array = null;
            RuntimeMethodInfo runtimeMethodInfo = obj as RuntimeMethodInfo;
            if (runtimeMethodInfo != null)
            {
                array = runtimeMethodInfo.GetPseudoCustomAttributesData();
            }
            else
            {
                RuntimeFieldInfo runtimeFieldInfo = obj as RuntimeFieldInfo;
                if (runtimeFieldInfo != null)
                {
                    array = runtimeFieldInfo.GetPseudoCustomAttributesData();
                }
                else
                {
                    RuntimeParameterInfo runtimeParameterInfo = obj as RuntimeParameterInfo;
                    if (runtimeParameterInfo != null)
                    {
                        array = runtimeParameterInfo.GetPseudoCustomAttributesData();
                    }
                    else
                    {
                        Type type = obj as Type;
                        if (type != null)
{
                            array = MonoCustomAttrs.GetPseudoCustomAttributesData(type);
                        }
                    }
                }
            }
            if (attributeType != null && array != null)
            {
                int i = 0;
                while (i < array.Length)
                {
                    if (attributeType.IsAssignableFrom(array[i].AttributeType))
                    {
                        if (array.Length == 1)
{
                            return array;
                        }
                        return new CustomAttributeData[] { array[i] };
                    }
                    else
                    {
                        i++;
                    }
                }
                return Array.Empty<CustomAttributeData>();
            }
            return array;
        }
References System.array, System.Reflection.FieldInfo.GetPseudoCustomAttributesData(), System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributesData(), System.Reflection.RuntimeParameterInfo.GetPseudoCustomAttributesData(), System.MonoCustomAttrs.GetPseudoCustomAttributesData(), System.Type.IsAssignableFrom(), and System.obj.
Referenced by System.MonoCustomAttrs.GetCustomAttributesDataBase(), and System.MonoCustomAttrs.GetPseudoCustomAttributesData().