Terraria Decompiled: System.MonoCustomAttrs.RetrieveAttributeUsageNoCache
RetrieveAttributeUsageNoCache()
static AttributeUsageAttribute System.MonoCustomAttrs.RetrieveAttributeUsageNoCache (Type attributeType) inline static private
Definition at line 747 of file MonoCustomAttrs.cs.
        {
            if (attributeType == typeof(AttributeUsageAttribute))
            {
                return new AttributeUsageAttribute(AttributeTargets.Class);
            }
            AttributeUsageAttribute attributeUsageAttribute = null;
            object[] customAttributes = MonoCustomAttrs.GetCustomAttributes(attributeType, typeof(AttributeUsageAttribute), false);
            if (customAttributes.Length == 0)
            {
                if (attributeType.BaseType != null)
                {
                    attributeUsageAttribute = MonoCustomAttrs.RetrieveAttributeUsage(attributeType.BaseType);
                }
                if (attributeUsageAttribute != null)
                {
                    return attributeUsageAttribute;
                }
                return MonoCustomAttrs.DefaultAttributeUsage;
            }
            else
            {
                if (customAttributes.Length > 1)
                {
                    throw new FormatException("Duplicate AttributeUsageAttribute cannot be specified on an attribute type.");
                }
                return (AttributeUsageAttribute)customAttributes[0];
            }
        }
References System.Type.BaseType, System.MonoCustomAttrs.DefaultAttributeUsage, System.MonoCustomAttrs.GetCustomAttributes(), and System.MonoCustomAttrs.RetrieveAttributeUsage().
Referenced by System.MonoCustomAttrs.RetrieveAttributeUsage().