Terraria Decompiled: System.MonoCustomAttrs.GetBase
GetBase()
static ICustomAttributeProvider System.MonoCustomAttrs.GetBase (ICustomAttributeProvider obj) inline static private
Definition at line 696 of file MonoCustomAttrs.cs.
        {
            if (obj == null)
            {
                return null;
            }
            if (obj is Type)
            {
                return ((Type)obj).BaseType;
            }
            MethodInfo methodInfo = null;
            if (obj is RuntimePropertyInfo)
            {
                return MonoCustomAttrs.GetBasePropertyDefinition((RuntimePropertyInfo)obj);
            }
            if (obj is RuntimeEventInfo)
            {
                return MonoCustomAttrs.GetBaseEventDefinition((RuntimeEventInfo)obj);
            }
            if (obj is RuntimeMethodInfo)
            {
                methodInfo = (MethodInfo)obj;
            }
            RuntimeParameterInfo runtimeParameterInfo = obj as RuntimeParameterInfo;
            if (runtimeParameterInfo != null)
            {
                MemberInfo member = runtimeParameterInfo.Member;
                if (member is MethodInfo)
                {
                    methodInfo = (MethodInfo)member;
                    MethodInfo baseMethod = ((RuntimeMethodInfo)methodInfo).GetBaseMethod();
                    if (baseMethod == methodInfo)
                    {
                        return null;
                    }
                    return baseMethod.GetParameters()[runtimeParameterInfo.Position];
                }
            }
            if (methodInfo == null || !methodInfo.IsVirtual)
            {
                return null;
            }
            MethodInfo baseMethod2 = ((RuntimeMethodInfo)methodInfo).GetBaseMethod();
            if (baseMethod2 == methodInfo)
            {
                return null;
            }
            return baseMethod2;
        }
References System.MonoCustomAttrs.GetBaseEventDefinition(), System.MonoCustomAttrs.GetBasePropertyDefinition(), System.Reflection.MethodBase.GetParameters(), System.Reflection.MethodBase.IsVirtual, System.Reflection.ParameterInfo.Member, System.obj, and System.Reflection.ParameterInfo.Position.
Referenced by System.MonoCustomAttrs.GetCustomAttributes(), System.MonoCustomAttrs.GetCustomAttributesData(), and System.MonoCustomAttrs.IsDefined().