Terraria Decompiled: System.MonoCustomAttrs.GetBaseEventDefinition
GetBaseEventDefinition()
static EventInfo System.MonoCustomAttrs.GetBaseEventDefinition (RuntimeEventInfo evt) inline static private
Definition at line 670 of file MonoCustomAttrs.cs.
        {
            MethodInfo methodInfo = evt.GetAddMethod(true);
            if (methodInfo == null || !methodInfo.IsVirtual)
            {
                methodInfo = evt.GetRaiseMethod(true);
            }
            if (methodInfo == null || !methodInfo.IsVirtual)
            {
                methodInfo = evt.GetRemoveMethod(true);
            }
            if (methodInfo == null || !methodInfo.IsVirtual)
            {
                return null;
            }
            MethodInfo baseMethod = ((RuntimeMethodInfo)methodInfo).GetBaseMethod();
            if (baseMethod != null && baseMethod != methodInfo)
            {
                BindingFlags bindingFlags = (methodInfo.IsPublic ? BindingFlags.Public : BindingFlags.NonPublic);
                bindingFlags |= (methodInfo.IsStatic ? BindingFlags.Static : BindingFlags.Instance);
                return baseMethod.DeclaringType.GetEvent(evt.Name, bindingFlags);
            }
            return null;
        }
References System.Runtime.InteropServices._MethodInfo.DeclaringType, System.Reflection.RuntimeEventInfo.GetAddMethod(), System.Type.GetEvent(), System.Reflection.RuntimeEventInfo.GetRaiseMethod(), System.Reflection.RuntimeEventInfo.GetRemoveMethod(), System.Reflection.MethodBase.IsVirtual, and System.Reflection.RuntimeEventInfo.Name.
Referenced by System.MonoCustomAttrs.GetBase().