Terraria Decompiled: NVorbis.Ogg.StreamPageReader.FindPage
FindPage()
int NVorbis.Ogg.StreamPageReader.FindPage (long granulePos) inline
Implements NVorbis.Contracts.Ogg.IStreamPageReader.
Definition at line 123 of file StreamPageReader.cs.
        {
            int num = -1;
            if (granulePos == 0L)
            {
                num = this.FindFirstDataPage();
            }
            else
            {
                int num2 = this._pageOffsets.Count - 1;
                long num3;
                if (this.GetPageRaw(num2, out num3))
                {
                    if (granulePos < num3)
                    {
                        num = this.FindPageBisection(granulePos, this.FindFirstDataPage(), num2, num3);
                    }
                    else if (granulePos > num3)
                    {
                        num = this.FindPageForward(num2, num3, granulePos);
                    }
                    else
                    {
                        num = num2 + 1;
                    }
                }
            }
            if (num == -1)
            {
                throw new ArgumentOutOfRangeException("granulePos");
            }
            return num;
        }
References NVorbis.Ogg.StreamPageReader.FindFirstDataPage(), NVorbis.Ogg.StreamPageReader.FindPageBisection(), NVorbis.Ogg.StreamPageReader.FindPageForward(), NVorbis.Ogg.StreamPageReader.GetPageRaw(), and System.L.