Terraria Decompiled: NVorbis.Ogg.StreamPageReader.GetPage
GetPage()
bool NVorbis.Ogg.StreamPageReader.GetPage (int pageIndex, out long granulePos, out bool isResync, out bool isContinuation, out bool isContinued, out int packetCount, out int pageOverhead) inline
Implements NVorbis.Contracts.Ogg.IStreamPageReader.
Definition at line 292 of file StreamPageReader.cs.
        {
            if (this._lastPageIndex == pageIndex)
            {
                granulePos = this._lastPageGranulePos;
                isResync = this._lastPageIsResync;
                isContinuation = this._lastPageIsContinuation;
                isContinued = this._lastPageIsContinued;
                packetCount = this._lastPagePacketCount;
                pageOverhead = this._lastPageOverhead;
                return true;
            }
            this._reader.Lock();
            try
            {
                while (pageIndex >= this._pageOffsets.Count && !this.HasAllPages && this._reader.ReadNextPage())
                {
                    if (pageIndex < this._pageOffsets.Count)
                    {
                        isResync = this._reader.IsResync.Value;
                        this.ReadPageData(pageIndex, out granulePos, out isContinuation, out isContinued, out packetCount, out pageOverhead);
                        return true;
                    }
                }
            }
            finally
            {
                this._reader.Release();
            }
            if (pageIndex < this._pageOffsets.Count)
            {
                long num = this._pageOffsets[pageIndex];
                if (num < 0L)
                {
                    isResync = true;
                    num = -num;
                }
                else
                {
                    isResync = false;
                }
                this._reader.Lock();
                try
                {
                    if (this._reader.ReadPageAt(num))
                    {
                        this._lastPageIsResync = isResync;
                        this.ReadPageData(pageIndex, out granulePos, out isContinuation, out isContinued, out packetCount, out pageOverhead);
                        return true;
                    }
                }
                finally
                {
                    this._reader.Release();
                }
            }
            granulePos = 0L;
            isResync = false;
            isContinuation = false;
            isContinued = false;
            packetCount = 0;
            pageOverhead = 0;
            return false;
        }
References NVorbis.Ogg.StreamPageReader._lastPageGranulePos, NVorbis.Ogg.StreamPageReader._lastPageIndex, NVorbis.Ogg.StreamPageReader._lastPageIsContinuation, NVorbis.Ogg.StreamPageReader._lastPageIsContinued, NVorbis.Ogg.StreamPageReader._lastPageIsResync, NVorbis.Ogg.StreamPageReader._lastPageOverhead, NVorbis.Ogg.StreamPageReader._lastPagePacketCount, NVorbis.Ogg.StreamPageReader._pageOffsets, NVorbis.Ogg.StreamPageReader._reader, System.Collections.Generic.List< T >.Count, NVorbis.Contracts.Ogg.IPageData.IsResync, System.L, NVorbis.Contracts.Ogg.IPageReader.Lock(), NVorbis.Contracts.Ogg.IPageReader.ReadPageAt(), NVorbis.Ogg.StreamPageReader.ReadPageData(), and NVorbis.Contracts.Ogg.IPageReader.Release().