Terraria Decompiled: NVorbis.Ogg.StreamPageReader.GetNextPageGranulePos
GetNextPageGranulePos()
bool NVorbis.Ogg.StreamPageReader.GetNextPageGranulePos (out long granulePos) inline private
Definition at line 199 of file StreamPageReader.cs.
        {
            int count = this._pageOffsets.Count;
            while (count == this._pageOffsets.Count && !this.HasAllPages)
            {
                this._reader.Lock();
                try
                {
                    if (!this._reader.ReadNextPage())
                    {
                        this.HasAllPages = true;
                    }
                    else if (count < this._pageOffsets.Count)
                    {
                        granulePos = this._reader.GranulePosition;
                        return true;
                    }
                }
                finally
                {
                    this._reader.Release();
                }
            }
            granulePos = 0L;
            return false;
        }
References NVorbis.Ogg.StreamPageReader._pageOffsets, NVorbis.Ogg.StreamPageReader._reader, System.Collections.Generic.List< T >.Count, System.count, NVorbis.Contracts.Ogg.IPageData.GranulePosition, System.L, NVorbis.Contracts.Ogg.IPageReader.Lock(), NVorbis.Contracts.Ogg.IPageReader.ReadNextPage(), and NVorbis.Contracts.Ogg.IPageReader.Release().
Referenced by NVorbis.Ogg.StreamPageReader.FindPageForward().