Terraria Decompiled: NVorbis.Ogg.StreamPageReader.FindPageForward
FindPageForward()
int NVorbis.Ogg.StreamPageReader.FindPageForward (int pageIndex, long pageGranulePos, long granulePos) inline private
Definition at line 172 of file StreamPageReader.cs.
        {
            while (pageGranulePos <= granulePos)
            {
                if (++pageIndex == this._pageOffsets.Count)
                {
                    if (!this.GetNextPageGranulePos(out pageGranulePos))
                    {
                        long? maxGranulePosition = this.MaxGranulePosition;
                        if ((maxGranulePosition.GetValueOrDefault() < granulePos) & (maxGranulePosition != null))
{
                            pageIndex = -1;
                            break;
                        }
                        break;
                    }
                }
                else if (!this.GetPageRaw(pageIndex, out pageGranulePos))
                {
                    pageIndex = -1;
                    break;
                }
            }
            return pageIndex;
        }
References NVorbis.Ogg.StreamPageReader._pageOffsets, System.Collections.Generic.List< T >.Count, NVorbis.Ogg.StreamPageReader.GetNextPageGranulePos(), NVorbis.Ogg.StreamPageReader.GetPageRaw(), and NVorbis.Ogg.StreamPageReader.MaxGranulePosition.
Referenced by NVorbis.Ogg.StreamPageReader.FindPage().