Terraria Decompiled: NVorbis.Ogg.StreamPageReader.GetPagePackets
GetPagePackets()
Memory< byte >[] NVorbis.Ogg.StreamPageReader.GetPagePackets (int pageIndex) inline
Implements NVorbis.Contracts.Ogg.IStreamPageReader.
Definition at line 92 of file StreamPageReader.cs.
        {
            if (this._cachedPagePackets != null && this._lastPageIndex == pageIndex)
            {
                return this._cachedPagePackets;
            }
            long num = this._pageOffsets[pageIndex];
            if (num < 0L)
            {
                num = -num;
            }
            this._reader.Lock();
            Memory<byte>[] array;
            try
            {
                this._reader.ReadPageAt(num);
                Memory<byte>[] packets = this._reader.GetPackets();
                if (pageIndex == this._lastPageIndex)
                {
                    this._cachedPagePackets = packets;
                }
                array = packets;
            }
            finally
            {
                this._reader.Release();
            }
            return array;
        }
References NVorbis.Ogg.StreamPageReader._cachedPagePackets, NVorbis.Ogg.StreamPageReader._lastPageIndex, NVorbis.Ogg.StreamPageReader._pageOffsets, NVorbis.Ogg.StreamPageReader._reader, System.array, NVorbis.Contracts.Ogg.IPageData.GetPackets(), System.L, NVorbis.Contracts.Ogg.IPageReader.Lock(), NVorbis.Contracts.Ogg.IPageReader.ReadPageAt(), and NVorbis.Contracts.Ogg.IPageReader.Release().