Terraria Decompiled: ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.AddDeviceIfSupported
AddDeviceIfSupported()
void ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.AddDeviceIfSupported (int deviceIndex, CorsairDeviceInfo deviceInfo) inline private
Definition at line 95 of file CorsairDeviceGroup.cs.
        {
            if ((deviceInfo.CapsMask & CorsairDeviceCaps.CDC_Lighting) == CorsairDeviceCaps.CDC_None)
            {
                return;
            }
            RgbDevice rgbDevice = null;
            try
            {
                switch (deviceInfo.Type)
                {
                case CorsairDeviceType.CDT_Mouse:
                    rgbDevice = CorsairMouse.Create(deviceIndex, deviceInfo, this._colorProfiles.Mouse);
                    break;
                case CorsairDeviceType.CDT_Keyboard:
                    rgbDevice = CorsairKeyboard.Create(deviceIndex, this._colorProfiles.Keyboard);
                    break;
                case CorsairDeviceType.CDT_Headset:
                    rgbDevice = CorsairHeadset.Create(deviceIndex, this._colorProfiles.Headset);
                    break;
                case CorsairDeviceType.CDT_MouseMat:
                    rgbDevice = CorsairMousepad.Create(deviceIndex, this._colorProfiles.Mousepad);
                    break;
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Corsair RGB failed to create device: " + ex);
                rgbDevice = null;
            }
            if (rgbDevice != null && rgbDevice.LedCount > 0)
            {
                this._devices.Add(rgbDevice);
                this._state = CorsairDeviceGroup.State.AnyDevicesAdded;
            }
        }
References ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup._colorProfiles, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup._devices, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceInfo.CapsMask, ReLogic.Peripherals.RGB.Corsair.CorsairMouse.Create(), ReLogic.Peripherals.RGB.Corsair.CorsairHeadset.Create(), ReLogic.Peripherals.RGB.Corsair.CorsairKeyboard.Create(), ReLogic.Peripherals.RGB.Corsair.CorsairMousepad.Create(), ReLogic.Peripherals.RGB.VendorColorProfile.Headset, ReLogic.Peripherals.RGB.VendorColorProfile.Keyboard, ReLogic.Peripherals.RGB.RgbDevice.LedCount, ReLogic.Peripherals.RGB.VendorColorProfile.Mouse, ReLogic.Peripherals.RGB.VendorColorProfile.Mousepad, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceInfo.Type, and System.Console.WriteLine().
Referenced by ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup.Initialize().