Terraria Decompiled: Newtonsoft.Json.JsonReaderException.Create
Create() [2/3]
static JsonReaderException Newtonsoft.Json.JsonReaderException.Create (JsonReader reader, string message) inline static package
Definition at line 77 of file JsonReaderException.cs.
        {
            return JsonReaderException.Create(reader, message, null);
        }
References Newtonsoft.Json.JsonReaderException.Create().
Referenced by Newtonsoft.Json.JsonTextReader.ConvertUnicode(), Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonReader.CreateUnexpectedEndException(), Newtonsoft.Json.JsonReader.GetTypeForCloseToken(), Newtonsoft.Json.Linq.JArray.Load(), Newtonsoft.Json.Linq.JConstructor.Load(), Newtonsoft.Json.Linq.JObject.Load(), Newtonsoft.Json.Linq.JProperty.Load(), Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseConstructor(), Newtonsoft.Json.JsonTextReader.ParseFalse(), Newtonsoft.Json.JsonTextReader.ParseNull(), Newtonsoft.Json.JsonTextReader.ParseNumberNaN(), Newtonsoft.Json.JsonTextReader.ParseNumberNegativeInfinity(), Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseProperty(), Newtonsoft.Json.JsonTextReader.ParseTrue(), Newtonsoft.Json.JsonTextReader.ParseUndefined(), Newtonsoft.Json.JsonTextReader.ParseUnquotedProperty(), Newtonsoft.Json.JsonReader.Push(), Newtonsoft.Json.Bson.BsonReader.Read(), Newtonsoft.Json.JsonTextReader.Read(), Newtonsoft.Json.JsonReader.ReadArrayElementIntoByteArrayReportDone(), Newtonsoft.Json.JsonReader.ReadAsBoolean(), Newtonsoft.Json.JsonTextReader.ReadAsBoolean(), Newtonsoft.Json.JsonReader.ReadAsBytes(), Newtonsoft.Json.JsonTextReader.ReadAsBytes(), Newtonsoft.Json.JsonReader.ReadAsDateTime(), Newtonsoft.Json.JsonReader.ReadAsDateTimeOffset(), Newtonsoft.Json.JsonReader.ReadAsDecimal(), Newtonsoft.Json.JsonReader.ReadAsDouble(), Newtonsoft.Json.JsonReader.ReadAsInt32(), Newtonsoft.Json.JsonReader.ReadAsString(), Newtonsoft.Json.JsonReader.ReadBooleanString(), Newtonsoft.Json.JsonReader.ReadDateTimeOffsetString(), Newtonsoft.Json.JsonReader.ReadDateTimeString(), Newtonsoft.Json.JsonReader.ReadDecimalString(), Newtonsoft.Json.JsonReader.ReadDoubleString(), Newtonsoft.Json.JsonTextReader.ReadFinished(), Newtonsoft.Json.Linq.JToken.ReadFrom(), Newtonsoft.Json.JsonReader.ReadInt32String(), Newtonsoft.Json.JsonReader.ReadIntoWrappedTypeObject(), Newtonsoft.Json.Bson.BsonReader.ReadNormal(), Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer(), Newtonsoft.Json.JsonTextReader.ReadNumberValue(), Newtonsoft.Json.Bson.BsonReader.ReadReference(), Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(), Newtonsoft.Json.JsonTextReader.ReadStringValue(), Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(), Newtonsoft.Json.JsonTextReader.ReadUnquotedPropertyReportIfDone(), Newtonsoft.Json.JsonReader.SetStateBasedOnCurrent(), Newtonsoft.Json.JsonTextReader.ThrowReaderError(), and Newtonsoft.Json.JsonReader.ValidateEnd().