Terraria Decompiled: Terraria.Net.Ping.Update
Update()
static void Terraria.Net.Ping.Update () inline static
Definition at line 38 of file Ping.cs.
        {
            if (Ping._waitingForResponse)
            {
                Ping.CurrentPing = Math.Max(Ping.CurrentPing, (int)Ping._stopwatch.ElapsedMilliseconds);
                return;
            }
            if (Ping._stopwatch.ElapsedMilliseconds >= 250L)
            {
                NetMessage.SendData(154, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                Ping._waitingForResponse = true;
                Ping._stopwatch.Restart();
            }
        }
References Terraria.Net.Ping._stopwatch, Terraria.Net.Ping._waitingForResponse, Terraria.Net.Ping.CurrentPing, System.L, System.Math.Max(), and Terraria.NetMessage.SendData().
Referenced by Terraria.Main.DoUpdateInWorld().