Terraria Decompiled: Terraria.Mount.DoFailedDismountDust
DoFailedDismountDust()
void Terraria.Mount.DoFailedDismountDust (Player mountedPlayer, int dustAmount) inline
Definition at line 6394 of file Mount.cs.
        {
            if (Main.netMode == 2)
            {
                return;
            }
            Color color = Color.Transparent;
            if (this._type == 56)
            {
                color = Color.Black;
            }
            if (this._type == 61)
            {
                color = Projectile.GetFairyQueenWeaponsColorFull(mountedPlayer.whoAmI, mountedPlayer.Center, 0.27f, 1f, 0.15f, 1f, 0.7f);
            }
            Rectangle hitbox = mountedPlayer.Hitbox;
            hitbox.Inflate(10, 10);
            for (int i = 0; i < dustAmount; i++)
            {
                int spawnDust = this._data.spawnDust;
                float num = 1f;
                int num2 = 0;
                int num3 = Dust.NewDust(hitbox.TopLeft(), hitbox.Width, hitbox.Height, spawnDust, 0f, 0f, num2, color, num);
                Main.dust[num3].scale += (float)Main.rand.Next(-10, 21) * 0.01f;
                if (this._type == 56)
                {
                    Dust dust = Main.dust[num3];
                    dust.scale = 0.7f;
                    dust.velocity *= 0.4f;
                    dust.velocity.Y = dust.velocity.Y + mountedPlayer.gravDir * 0.5f;
                }
                if (this._type == 61)
                {
                    Dust dust2 = Main.dust[num3];
                    dust2.scale *= 1f + 0.3f * Main.rand.NextFloat();
                    dust2.velocity += mountedPlayer.velocity * Main.rand.NextFloat();
                }
                if (this._data.spawnDustNoGravity)
                {
                    Main.dust[num3].noGravity = true;
                }
                else if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num3].scale *= 1.3f;
                    Main.dust[num3].noGravity = true;
                }
                else
                {
                    Main.dust[num3].velocity *= 0.5f;
                }
                Main.dust[num3].velocity += mountedPlayer.velocity * 0.8f;
            }
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.Entity.Center, Terraria.Main.dust, Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Color.Transparent, Terraria.Dust.velocity, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Rectangle.Width.
Referenced by Terraria.Player.QuickMount().