Terraria Decompiled: Terraria.Mount.StartAbilityCharge
StartAbilityCharge()
void Terraria.Mount.StartAbilityCharge (Player mountedPlayer) inline
Definition at line 2631 of file Mount.cs.
        {
            if (Main.myPlayer == mountedPlayer.whoAmI)
            {
                int num = this._type;
                if (num == 9)
                {
                    int num2 = 441;
                    float num3 = Main.screenPosition.X + (float)Main.mouseX;
                    float num4 = Main.screenPosition.Y + (float)Main.mouseY;
                    float num5 = num3 - mountedPlayer.position.X;
                    float num6 = num4 - mountedPlayer.position.Y;
                    Projectile.NewProjectile(this.GetProjectileSpawnSource(mountedPlayer), num3, num4, 0f, 0f, num2, 0, 0f, mountedPlayer.whoAmI, num5, num6, 0f, null);
                    this._abilityCharging = true;
                    return;
                }
            }
            else
            {
                int num = this._type;
                if (num == 9)
                {
                    this._abilityCharging = true;
                }
            }
        }
References Terraria.Mount._type, Terraria.Mount.GetProjectileSpawnSource(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Entity.position, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI().