Terraria Decompiled: Terraria.Mount.DrillSmartCursor_Blocks
DrillSmartCursor_Blocks()
Point16 Terraria.Mount.DrillSmartCursor_Blocks (Player mountedPlayer, Mount::DrillMountData data) inline private
Definition at line 2924 of file Mount.cs.
        {
            Vector2 vector;
            if (mountedPlayer.whoAmI == Main.myPlayer)
            {
                vector = Main.screenPosition + new Vector2((float)Main.mouseX, (float)Main.mouseY);
            }
            else
            {
                vector = data.crosshairPosition;
            }
            Vector2 center = mountedPlayer.Center;
            Vector2 vector2 = vector - center;
            float num = vector2.Length();
            if (num > 224f)
            {
                num = 224f;
            }
            num += 32f;
            vector2.Normalize();
            Vector2 vector3 = center;
            Vector2 vector4 = center + vector2 * num;
            Point16 tilePoint = new Point16(-1, -1);
            if (!Utils.PlotTileLine(vector3, vector4, 65.6f, delegate(int x, int y)
            {
                tilePoint = new Point16(x, y);
                for (int i = 0; i < data.beams.Length; i++)
                {
                    if (data.beams[i].curTileTarget == tilePoint && data.beams[i].lastPurpose == 0)
                    {
                        return true;
                    }
                }
                return !WorldGen.CanKillTile(x, y) || Main.tile[x, y] == null || Main.tile[x, y].inActive() || !Main.tile[x, y].active();
            }))
            {
                return tilePoint;
            }
            return new Point16(-1, -1);
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanKillTile(), Terraria.Entity.Center, Terraria.Tile.inActive(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Utils.PlotTileLine(), Terraria.Main.tile, Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Entity.whoAmI.
Referenced by Terraria.Mount.UseDrill().