Terraria Decompiled: Terraria.Mount.Hover
Hover()
bool Terraria.Mount.Hover (Player mountedPlayer) inline
Definition at line 3106 of file Mount.cs.
        {
            bool flag = this.DoesHoverIgnoresFatigue();
            bool flag2 = this._frameState == 2 || this._frameState == 4;
            if (this._type == 49)
            {
                flag2 = this._frameState == 4;
            }
            if (this._type == 56)
            {
                flag2 = this._frameState == 2 || this._frameState == 3;
            }
            if (this._type == 61)
            {
                flag2 = this._frameState == 2 || this._frameState == 3 || this._frameState == 4;
            }
            if (flag2)
            {
                bool flag3 = true;
                float num = 1f;
                float num2 = mountedPlayer.gravity / Player.defaultGravity;
                if (mountedPlayer.slowFall)
                {
                    num2 /= 3f;
                }
                if (num2 < 0.25f)
                {
                    num2 = 0.25f;
                }
                if (!flag)
                {
                    if (this._flyTime > 0)
                    {
                        this._flyTime--;
                    }
                    else if (this._fatigue < this._fatigueMax)
                    {
                        this._fatigue += num2;
                    }
                    else
                    {
                        flag3 = false;
                    }
                }
                if (this._type == 12 && !mountedPlayer.MountFishronSpecial)
                {
                    num = 0.5f;
                }
                float num3 = this._fatigue / this._fatigueMax;
                if (flag)
                {
                    num3 = 0f;
                }
                bool flag4 = true;
                if (this._type == 48)
                {
                    flag4 = false;
                }
                float num4 = 4f * num3;
                float num5 = 4f * num3;
                bool flag5 = false;
                if (this._type == 48)
                {
                    num4 = 0f;
                    num5 = 0f;
                    if (!flag3)
                    {
                        flag5 = true;
                    }
                    if (mountedPlayer.controlDown)
                    {
                        num5 = 8f;
                    }
                }
                if (num4 == 0f)
                {
                    num4 = -0.001f;
                }
                if (num5 == 0f)
                {
                    num5 = -0.001f;
                }
                float num6 = mountedPlayer.velocity.Y;
                if (flag4 && (mountedPlayer.controlUp || mountedPlayer.controlJump) && flag3)
                {
                    num4 = -2f - 6f * (1f - num3);
                    if (this._type == 48)
                    {
                        num4 /= 3f;
                    }
                    if (this._type == 56 || this._type == 61)
                    {
                        num4 = -this._data.dashSpeed;
                    }
                    num6 -= this._data.acceleration * num;
                }
                else if (mountedPlayer.controlDown)
                {
                    num5 = 8f;
                    if (this._type == 56 || this._type == 61)
                    {
                        num5 = this._data.dashSpeed;
                    }
                    num6 += this._data.acceleration * num;
                }
                else if (flag5)
                {
                    float num7 = mountedPlayer.gravity * mountedPlayer.gravDir;
                    num6 += num7;
                    num5 = 4f;
                }
                else
                {
                    int jump = mountedPlayer.jump;
                }
                if (num6 < num4)
                {
                    if (num4 - num6 < this._data.acceleration)
                    {
                        num6 = num4;
                    }
                    else
                    {
                        num6 += this._data.acceleration * num;
                    }
                }
                else if (num6 > num5)
                {
                    if (num6 - num5 < this._data.acceleration)
                    {
                        num6 = num5;
                    }
                    else
                    {
                        num6 -= this._data.acceleration * num;
                    }
                }
                if (this._type == 56 || this._type == 61)
                {
                    if (num4 != -0.001f)
                    {
                        num6 = MathHelper.Max(num6, num4);
                    }
                    if (num5 != -0.001f)
                    {
                        num6 = MathHelper.Min(num6, num5);
                    }
                }
                mountedPlayer.velocity.Y = num6;
                if (num4 == -0.001f && num5 == -0.001f && num6 == -0.001f)
                {
                    mountedPlayer.position.Y = mountedPlayer.position.Y - -0.001f;
                    Mount.TryStabilizingSmallMountPositionBetweenSlopes(mountedPlayer);
                }
                mountedPlayer.fallStart = (int)(mountedPlayer.position.Y / 16f);
            }
            else if (!flag)
            {
                mountedPlayer.velocity.Y = mountedPlayer.velocity.Y + mountedPlayer.gravity * mountedPlayer.gravDir;
            }
            else if (mountedPlayer.velocity.Y == 0f)
            {
                Vector2 vector = Vector2.UnitY * mountedPlayer.gravDir * 1f;
                if (Collision.TileCollision(mountedPlayer.position, vector, mountedPlayer.width, mountedPlayer.height, false, false, (int)mountedPlayer.gravDir, false, false, true).Y != 0f || mountedPlayer.controlDown)
                {
                    mountedPlayer.velocity.Y = 0.001f;
                }
            }
            else if (mountedPlayer.velocity.Y == -0.001f)
            {
                mountedPlayer.velocity.Y = mountedPlayer.velocity.Y - -0.001f;
            }
            if (this._type == 7)
            {
                float num8 = mountedPlayer.velocity.X / this._data.dashSpeed;
                if ((double)num8 > 0.95)
                {
                    num8 = 0.95f;
                }
                if ((double)num8 < -0.95)
                {
                    num8 = -0.95f;
                }
                float num9 = 0.7853982f * num8 / 2f;
                float num10 = Math.Abs(2f - (float)this._frame / 2f) / 2f;
                Lighting.AddLight((int)(mountedPlayer.position.X + (float)(mountedPlayer.width / 2)) / 16, (int)(mountedPlayer.position.Y + (float)(mountedPlayer.height / 2)) / 16, 0.4f, 0.2f * num10, 0f);
                mountedPlayer.fullRotation = num9;
            }
            else if (this._type == 8)
            {
                float num11 = mountedPlayer.velocity.X / this._data.dashSpeed;
                if ((double)num11 > 0.95)
                {
                    num11 = 0.95f;
                }
                if ((double)num11 < -0.95)
                {
                    num11 = -0.95f;
                }
                float num12 = 0.7853982f * num11 / 2f;
                mountedPlayer.fullRotation = num12;
                Mount.DrillMountData drillMountData = (Mount.DrillMountData)this._mountSpecificData;
                float num13 = drillMountData.outerRingRotation;
                num13 += mountedPlayer.velocity.X / 80f;
                if (num13 > 3.1415927f)
                {
                    num13 -= 6.2831855f;
                }
                else if (num13 < -3.1415927f)
                {
                    num13 += 6.2831855f;
                }
                drillMountData.outerRingRotation = num13;
            }
            else if (this._type == 23)
            {
                float num14 = -mountedPlayer.velocity.Y / this._data.dashSpeed;
                num14 = MathHelper.Clamp(num14, -1f, 1f);
                float num15 = mountedPlayer.velocity.X / this._data.dashSpeed;
                num15 = MathHelper.Clamp(num15, -1f, 1f);
                float num16 = -0.19634955f * num14 * (float)mountedPlayer.direction;
                float num17 = 0.19634955f * num15;
                float num18 = num16 + num17;
                mountedPlayer.fullRotation = num18;
                mountedPlayer.fullRotationOrigin = new Vector2((float)(mountedPlayer.width / 2), (float)mountedPlayer.height);
            }
            return true;
        }
References Terraria.Mount._data, Terraria.Mount._fatigue, Terraria.Mount._fatigueMax, Terraria.Mount._flyTime, Terraria.Mount._mountSpecificData, Terraria.Mount._type, System.Math.Abs(), Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Player.controlDown, Terraria.Player.controlJump, Terraria.Player.controlUp, Terraria.Player.defaultGravity, Terraria.Entity.direction, Terraria.Mount.DoesHoverIgnoresFatigue(), Terraria.Player.gravDir, Terraria.Entity.height, int, Terraria.Player.jump, Microsoft.Xna.Framework.MathHelper.Max(), Microsoft.Xna.Framework.MathHelper.Min(), Terraria.Player.MountFishronSpecial, Terraria.Mount.DrillMountData.outerRingRotation, Terraria.Entity.position, Terraria.Player.slowFall, Terraria.Collision.TileCollision(), Terraria.Mount.TryStabilizingSmallMountPositionBetweenSlopes(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.Y, and System.Y.