Terraria Decompiled: Terraria.Mount.Dismount
Dismount()
void Terraria.Mount.Dismount (Player mountedPlayer, bool ignoreEffect = false) inline
Definition at line 6195 of file Mount.cs.
        {
            if (!this._active)
            {
                return;
            }
            bool cart = this.Cart;
            this._active = false;
            mountedPlayer.ClearBuff(this._data.buff);
            this._mountSpecificData = null;
            int type = this._type;
            if (type - 55 <= 1 && mountedPlayer.noItems && !mountedPlayer.cursed)
            {
                mountedPlayer.noItems = false;
            }
            if (cart)
            {
                mountedPlayer.cartFlip = false;
                mountedPlayer.lastBoost = Vector2.Zero;
            }
            mountedPlayer.fullRotation = 0f;
            mountedPlayer.fullRotationOrigin = Vector2.Zero;
            if (mountedPlayer.petting.isPetting && mountedPlayer.petting.mount)
            {
                mountedPlayer.StopPettingAnimal();
            }
            if (!ignoreEffect)
            {
                this.DoSpawnDust(mountedPlayer, true);
            }
            this.Reset();
            if (!mountedPlayer.isDisplayDollOrInanimate && mountedPlayer.whoAmI == Main.myPlayer)
            {
                NetMessage.SendData(13, -1, -1, null, mountedPlayer.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
            Rectangle rectangle;
            if (Collision.TryChangingSizeFromBottomCenter(mountedPlayer.Hitbox, 20, 42, out rectangle))
            {
                Vector2 vector = rectangle.TopLeft() - mountedPlayer.position;
                mountedPlayer.position += vector;
                mountedPlayer.width = 20;
                mountedPlayer.height = 42;
                for (int i = 0; i < mountedPlayer.shadowPos.Length; i++)
                {
                    mountedPlayer.shadowPos[i] += vector;
                }
                return;
            }
            mountedPlayer.position.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
            mountedPlayer.width = 20;
            mountedPlayer.height = 42;
            mountedPlayer.position.Y = mountedPlayer.position.Y - (float)mountedPlayer.height;
        }
References Terraria.Player.ClearBuff(), Terraria.Player.cursed, Terraria.Entity.height, Terraria.Entity.Hitbox, Terraria.Player.isDisplayDollOrInanimate, Terraria.GameContent.PlayerPettingInfo.isPetting, Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.PlayerPettingInfo.mount, Terraria.Main.myPlayer, Terraria.Player.noItems, Terraria.Player.petting, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Player.shadowPos, Terraria.Player.StopPettingAnimal(), Terraria.Collision.TryChangingSizeFromBottomCenter(), Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.MessageBuffer.GetData(), and Terraria.Player.QuickMount().