Terraria Decompiled: Terraria.Mount.SetMount
SetMount()
void Terraria.Mount.SetMount (int m, Player mountedPlayer) inline
Definition at line 6250 of file Mount.cs.
        {
            if (this._type == m || m <= -1 || m >= MountID.Count)
            {
                return;
            }
            if (m == 5 && mountedPlayer.wet)
            {
                return;
            }
            if (this._active)
            {
                mountedPlayer.ClearBuff(this._data.buff);
                if (this.AnyTrackRider)
                {
                    mountedPlayer.cartFlip = false;
                    mountedPlayer.lastBoost = Vector2.Zero;
                }
                mountedPlayer.fullRotation = 0f;
                mountedPlayer.fullRotationOrigin = Vector2.Zero;
                this._mountSpecificData = null;
            }
            else
            {
                this._active = true;
            }
            this._flyTime = 0;
            this._type = m;
            this._data = Mount.mounts[m];
            this._fatigueMax = (float)this._data.fatigueMax;
            if (!mountedPlayer.isDisplayDollOrInanimate && mountedPlayer.whoAmI == Main.myPlayer)
            {
                NetMessage.SendData(13, -1, -1, null, mountedPlayer.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
            mountedPlayer.AddBuff(this._data.buff, 3600, false);
            this._flipDraw = false;
            if (this._type == 44)
            {
                mountedPlayer.velocity *= 0.2f;
                mountedPlayer.dash = 0;
                mountedPlayer.dashType = 0;
                mountedPlayer.dashDelay = 0;
                mountedPlayer.dashTime = 0;
            }
            if (this._type == 9 && this._abilityCooldown < 20)
            {
                this._abilityCooldown = 20;
            }
            if (this._type == 46 && this._abilityCooldown < 40)
            {
                this._abilityCooldown = 40;
            }
            Mount.MountDelegatesData.OverrideSizeMethod playerSize = this._data.delegations.PlayerSize;
            Vector2? vector;
            if (playerSize != null && playerSize(mountedPlayer, out vector) && vector != null)
            {
                Vector2 value = vector.Value;
                Vector2 bottom = mountedPlayer.Bottom;
                mountedPlayer.position = mountedPlayer.Bottom;
                for (int i = 0; i < mountedPlayer.shadowPos.Length; i++)
                {
                    Vector2[] shadowPos = mountedPlayer.shadowPos;
                    int num = i;
                    shadowPos[num].X = shadowPos[num].X + (float)(mountedPlayer.width / 2);
                    Vector2[] shadowPos2 = mountedPlayer.shadowPos;
                    int num2 = i;
                    shadowPos2[num2].Y = shadowPos2[num2].Y + (float)mountedPlayer.height;
                }
                mountedPlayer.width = (int)value.X;
                mountedPlayer.height = (int)value.Y;
                mountedPlayer.position = new Vector2(bottom.X - value.X / 2f, bottom.Y - (float)mountedPlayer.height);
                for (int j = 0; j < mountedPlayer.shadowPos.Length; j++)
                {
                    Vector2[] shadowPos3 = mountedPlayer.shadowPos;
                    int num3 = j;
                    shadowPos3[num3].X = shadowPos3[num3].X - (float)(mountedPlayer.width / 2);
                    Vector2[] shadowPos4 = mountedPlayer.shadowPos;
                    int num4 = j;
                    shadowPos4[num4].Y = shadowPos4[num4].Y - (float)mountedPlayer.height;
                }
            }
            else
            {
                mountedPlayer.position.Y = mountedPlayer.position.Y + (float)mountedPlayer.height;
                for (int k = 0; k < mountedPlayer.shadowPos.Length; k++)
                {
                    Vector2[] shadowPos5 = mountedPlayer.shadowPos;
                    int num5 = k;
                    shadowPos5[num5].Y = shadowPos5[num5].Y + (float)mountedPlayer.height;
                }
                mountedPlayer.height = 42 + this._data.heightBoost;
                mountedPlayer.position.Y = mountedPlayer.position.Y - (float)mountedPlayer.height;
                for (int l = 0; l < mountedPlayer.shadowPos.Length; l++)
                {
                    Vector2[] shadowPos6 = mountedPlayer.shadowPos;
                    int num6 = l;
                    shadowPos6[num6].Y = shadowPos6[num6].Y - (float)mountedPlayer.height;
                }
            }
            mountedPlayer.ResetAdvancedShadows();
            if (this._type == 7 || this._type == 8)
            {
                mountedPlayer.fullRotationOrigin = new Vector2((float)(mountedPlayer.width / 2), (float)(mountedPlayer.height / 2));
            }
            int type = this._type;
            if (type - 62 <= 1)
            {
                SoundEngine.PlaySound(SoundID.PalChillet, mountedPlayer.Center, 0f, 1f);
            }
            if (this._type == 8)
            {
                this._mountSpecificData = new Mount.DrillMountData();
            }
            if (this._type == 35)
            {
                this._mountSpecificData = new Mount.ExtraFrameMountData();
            }
            if (this._type == 54)
            {
                this._mountSpecificData = new Mount.SelectiveFlyingMountData();
            }
            this.FinalizeMountData(m, mountedPlayer);
            this.DoSpawnDust(mountedPlayer, false);
            if (this._type == 38 && mountedPlayer.whoAmI == Main.myPlayer)
            {
                AchievementsHelper.NotifyProgressionEvent(32);
            }
        }
References Terraria.Player.AddBuff(), Terraria.Entity.Bottom, Terraria.Entity.Center, Terraria.Player.ClearBuff(), Terraria.ID.MountID.Count, Terraria.Entity.height, int, Terraria.Player.isDisplayDollOrInanimate, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Mount.mounts, Terraria.Main.myPlayer, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.ID.SoundID.PalChillet, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.ResetAdvancedShadows(), Terraria.NetMessage.SendData(), Terraria.Player.shadowPos, System.value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.wet, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.MessageBuffer.GetData(), Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad(), and Terraria.Player.QuickMount().