Terraria Decompiled: Terraria.Mount.TryDismount
TryDismount()
bool Terraria.Mount.TryDismount (Player mountedPlayer) inline
Definition at line 6189 of file Mount.cs.
        {
            return this.TryDismountWithResult(mountedPlayer) == Mount.DismountCheckResult.Succeeded;
        }
Referenced by Terraria.Player.QuickGrapple(), Terraria.GameContent.PlayerSittingHelper.SitDown(), Terraria.GameContent.PlayerSleepingHelper.StartSleeping(), and Terraria.Main.TryRemovingBuff().