Terraria Decompiled: Terraria.Mount.DoExhaustMinecartEffect
DoExhaustMinecartEffect()
void Terraria.Mount.DoExhaustMinecartEffect (Player mountedPlayer, int dustType) inline private
Definition at line 4679 of file Mount.cs.
        {
            float num = mountedPlayer.velocity.Length();
            if (num < 1f && Main.rand.Next(4) != 0)
            {
                return;
            }
            int i = 1 + (int)num / 6;
            while (i > 0)
            {
                i--;
                Vector2 vector = Main.rand.NextVector2Square(-1f, 1f) * new Vector2(3f, 3f);
                Vector2 vector2 = new Vector2(-18f, 20f) * mountedPlayer.Directions;
                if (num > 6f)
                {
                    vector2.X += (float)(4 * mountedPlayer.direction);
                }
                if (i > 0)
                {
                    vector2 += mountedPlayer.velocity * (float)(i / 3);
                }
                Vector2 vector3 = mountedPlayer.Center + vector2 + vector;
                vector3 = mountedPlayer.RotatedRelativePoint(vector3, false, true);
                Dust dust = Dust.NewDustPerfect(vector3, dustType, null, 0, default(Color), 1f);
                dust.noGravity = true;
                dust.fadeIn = 0.6f;
                dust.scale = 1.2f;
                dust.velocity *= 0.2f;
                if (num < 1f)
                {
                    Dust dust2 = dust;
                    dust2.velocity.X = dust2.velocity.X - 0.5f * (float)mountedPlayer.direction;
                }
                dust.shader = GameShaders.Armor.GetSecondaryShader(mountedPlayer.cMinecart, mountedPlayer);
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Player.cMinecart, Terraria.Entity.direction, Terraria.Player.Directions, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetSecondaryShader(), int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Dust.NewDustPerfect(), Terraria.Main.rand, Terraria.Player.RotatedRelativePoint(), Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Entity.velocity.