Terraria Decompiled: Terraria.Mount.EmitGolfCartlight
EmitGolfCartlight()
static void Terraria.Mount.EmitGolfCartlight (Vector2 worldLocation, int playerDirection) inline static private
Definition at line 4578 of file Mount.cs.
        {
            float num = 0f;
            if (playerDirection == -1)
            {
                num = 3.1415927f;
            }
            float num2 = 0.09817477f;
            int num3 = 5;
            float num4 = 200f;
            DelegateMethods.v2_1 = worldLocation.ToTileCoordinates().ToVector2();
            DelegateMethods.f_1 = num4 / 16f;
            DelegateMethods.v3_1 = new Vector3(0.7f, 0.7f, 0.7f);
            for (float num5 = 0f; num5 < (float)num3; num5 += 1f)
            {
                Vector2 vector = (num + num2 * (num5 - (float)(num3 / 2))).ToRotationVector2();
                Utils.PlotTileLine(worldLocation, worldLocation + vector * num4, 8f, new Utils.TileActionAttempt(DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance));
            }
        }
References Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.Utils.PlotTileLine(), Terraria.Utils.TileActionAttempt(), and Microsoft.Xna.Framework.Graphics.Vector3.
Referenced by Terraria.Mount.UpdateFrame_GolfCart().