Terraria Decompiled: Terraria.Mount.TryEarlyDismount
TryEarlyDismount()
void Terraria.Mount.TryEarlyDismount (Player player) inline
Definition at line 6718 of file Mount.cs.
        {
            if (!this.Active)
            {
                return;
            }
            if (!this._data.dismountsOnItemUse)
            {
                return;
            }
            if (!this.CanDismount(player))
            {
                return;
            }
            this.Dismount(player, false);
        }
Referenced by Terraria.Player.QuickBuff(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickHeal(), and Terraria.Player.QuickMana().