Terraria Decompiled: Terraria.Mount.DoSpawnDust
DoSpawnDust()
void Terraria.Mount.DoSpawnDust (Player mountedPlayer, bool isDismounting) inline private
Definition at line 6449 of file Mount.cs.
        {
            if (Main.netMode == 2)
            {
                return;
            }
            if (this._type == 52)
            {
                for (int i = 0; i < 100; i++)
                {
                    int spawnDust = this._data.spawnDust;
                    Dust dust = Dust.NewDustDirect(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), mountedPlayer.width + 40, mountedPlayer.height, 267, 0f, 0f, 60, new Color(130, 60, 255, 70), 1f);
                    dust.scale += (float)Main.rand.Next(-10, 21) * 0.01f;
                    dust.noGravity = true;
                    dust.velocity += mountedPlayer.velocity * 0.8f;
                    dust.velocity *= Main.rand.NextFloat();
                    Dust dust2 = dust;
                    dust2.velocity.Y = dust2.velocity.Y + 2f * Main.rand.NextFloatDirection();
                    dust.noLight = true;
                    if (Main.rand.Next(3) == 0)
                    {
                        Dust dust3 = Dust.CloneDust(dust);
                        dust3.color = Color.White;
                        dust3.scale *= 0.5f;
                        dust3.alpha = 0;
                    }
                }
                return;
            }
            if (this._type == 62 || this._type == 63)
            {
                for (int j = 0; j < 100; j++)
                {
                    int spawnDust2 = this._data.spawnDust;
                    Dust dust4 = Dust.NewDustDirect(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), mountedPlayer.width + 40, mountedPlayer.height, 306, 0f, 0f, 60, new Color(100, 227, 255, 127), 2f);
                    dust4.scale += (float)Main.rand.Next(-10, 21) * 0.01f;
                    dust4.noGravity = true;
                    dust4.velocity += mountedPlayer.velocity * 0.8f;
                    dust4.velocity *= Main.rand.NextFloat();
                    Dust dust5 = dust4;
                    dust5.velocity.Y = dust5.velocity.Y + 4f * Main.rand.NextFloatDirection();
                    dust4.noLight = true;
                    if (Main.rand.Next(3) == 0)
                    {
                        Dust dust6 = Dust.CloneDust(dust4);
                        dust6.color = Color.White;
                        dust6.scale *= 0.5f;
                        dust6.alpha = 0;
                    }
                }
                return;
            }
            Color color = Color.Transparent;
            if (this._type == 23)
            {
                color = new Color(255, 255, 0, 255);
            }
            if (this._type == 56)
            {
                color = Color.Black;
            }
            if (this._type == 61)
            {
                color = Projectile.GetFairyQueenWeaponsColorFull(mountedPlayer.whoAmI, mountedPlayer.Center, 0.27f, 1f, 0.15f, 1f, 0.7f);
            }
            int num = 100;
            if (this._type > 0 && MountID.Sets.IsRollerSkates[this._type])
            {
                num = 40;
            }
            Rectangle hitbox = new Rectangle((int)mountedPlayer.position.X - 20, (int)mountedPlayer.position.Y, mountedPlayer.width + 40, mountedPlayer.height);
            if (this._type == 56 || this._type == 61)
            {
                if (isDismounting)
                {
                    Vector2 bottom = mountedPlayer.Bottom;
                    hitbox = new Rectangle((int)bottom.X - (int)mountedPlayer.DefaultSize.X / 2, (int)bottom.Y - (int)mountedPlayer.DefaultSize.Y, (int)mountedPlayer.DefaultSize.X, (int)mountedPlayer.DefaultSize.Y);
                }
                else
                {
                    hitbox = mountedPlayer.Hitbox;
                }
                hitbox.Inflate(10, 10);
            }
            if (this._type > 0 && MountID.Sets.IsRollerSkates[this._type])
            {
                int num2 = 10;
                int num3 = mountedPlayer.width / 2;
                int num4 = 10;
                hitbox = new Rectangle((int)mountedPlayer.Center.X - num3 - num2, (int)mountedPlayer.Bottom.Y - num4, Math.Max(1, num3 + num2 * 2), num4);
            }
            for (int k = 0; k < num; k++)
            {
                if (MountID.Sets.Cart[this._type])
                {
                    if (k % 10 == 0)
                    {
                        int num5 = Main.rand.Next(61, 64);
                        int num6 = Gore.NewGore(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), Vector2.Zero, num5, 1f);
                        Main.gore[num6].alpha = 100;
                        Main.gore[num6].velocity = Vector2.Transform(new Vector2(1f, 0f), Matrix.CreateRotationZ((float)(Main.rand.NextDouble() * 6.2831854820251465)));
                    }
                }
                else
                {
                    int num7 = this._data.spawnDust;
                    float num8 = 1f;
                    int num9 = 0;
                    if (this._type == 40 || this._type == 41 || this._type == 42)
                    {
                        if (Main.rand.Next(2) == 0)
{
                            num7 = 31;
                        }
                        else
{
                            num7 = 16;
                        }
                        num8 = 0.9f;
                        num9 = 50;
                        if (this._type == 42)
{
                            num7 = 31;
                        }
                        if (this._type == 41)
{
                            num7 = 16;
                        }
                    }
                    if (this._type != 61 || Main.rand.Next(isDismounting ? 2 : 5) == 0)
                    {
                        int num10 = Dust.NewDust(hitbox.TopLeft(), hitbox.Width, hitbox.Height, num7, 0f, 0f, num9, color, num8);
                        Main.dust[num10].scale += (float)Main.rand.Next(-10, 21) * 0.01f;
                        if (this._type > 0 && MountID.Sets.IsRollerSkates[this._type])
{
                            Dust dust7 = Main.dust[num10];
                            dust7.velocity *= 0.8f;
                            dust7.velocity.Y = dust7.velocity.Y * 0.75f;
                            dust7.velocity.Y = dust7.velocity.Y + mountedPlayer.gravDir * 0.25f;
                            dust7.noLightEmittance = true;
                            dust7.noGravity = true;
                        }
                        if (this._type == 56)
{
                            Dust dust8 = Main.dust[num10];
                            dust8.scale = 0.7f;
                            dust8.velocity *= 0.4f;
                            dust8.velocity.Y = dust8.velocity.Y + mountedPlayer.gravDir * 0.5f;
                        }
                        if (this._type == 61)
{
                            Dust dust9 = Main.dust[num10];
                            dust9.scale *= 1f + 0.3f * Main.rand.NextFloat();
                            if (!isDismounting)
{
                                dust9.position = Vector2.Lerp(dust9.position, hitbox.Center.ToVector2(), 0.7f);
                                dust9.velocity *= -2f;
                                Dust dust10 = dust9;
                                dust10.velocity.Y = dust10.velocity.Y - 1f;
                            }
                            dust9.velocity += mountedPlayer.velocity * Main.rand.NextFloat();
                        }
                        if (this._data.spawnDustNoGravity)
{
                            Main.dust[num10].noGravity = true;
                        }
                        else if (Main.rand.Next(2) == 0)
{
                            Main.dust[num10].scale *= 1.3f;
                            Main.dust[num10].noGravity = true;
                        }
                        else
{
                            Main.dust[num10].velocity *= 0.5f;
                        }
                        Main.dust[num10].velocity += mountedPlayer.velocity * 0.8f;
                        if (this._type == 40 || this._type == 41 || this._type == 42)
{
                            Main.dust[num10].velocity *= Main.rand.NextFloat();
                        }
                    }
                }
            }
            if (this._type == 40 || this._type == 41 || this._type == 42)
            {
                for (int l = 0; l < 5; l++)
                {
                    int num11 = Main.rand.Next(61, 64);
                    if (this._type == 41 || (this._type == 40 && Main.rand.Next(2) == 0))
                    {
                        num11 = Main.rand.Next(11, 14);
                    }
                    int num12 = Gore.NewGore(new Vector2(mountedPlayer.position.X + (float)(mountedPlayer.direction * 8), mountedPlayer.position.Y + 20f), Vector2.Zero, num11, 1f);
                    Main.gore[num12].alpha = 100;
                    Main.gore[num12].velocity = Vector2.Transform(new Vector2(1f, 0f), Matrix.CreateRotationZ((float)(Main.rand.NextDouble() * 6.2831854820251465))) * 1.4f;
                }
            }
            if (this._type == 23)
            {
                for (int m = 0; m < 4; m++)
                {
                    int num13 = Main.rand.Next(61, 64);
                    int num14 = Gore.NewGore(new Vector2(mountedPlayer.position.X - 20f, mountedPlayer.position.Y), Vector2.Zero, num13, 1f);
                    Main.gore[num14].alpha = 100;
                    Main.gore[num14].velocity = Vector2.Transform(new Vector2(1f, 0f), Matrix.CreateRotationZ((float)(Main.rand.NextDouble() * 6.2831854820251465)));
                }
            }
        }
References Terraria.Gore.alpha, Microsoft.Xna.Framework.Color.Black, Terraria.Entity.Bottom, Terraria.ID.MountID.Sets.Cart, Microsoft.Xna.Framework.Rectangle.Center, Terraria.Entity.Center, Terraria.Dust.CloneDust(), Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Terraria.Player.DefaultSize, Terraria.Main.dust, Terraria.Projectile.GetFairyQueenWeaponsColorFull(), Terraria.Main.gore, Microsoft.Xna.Framework.Rectangle.Height, Terraria.Entity.height, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.ID.MountID.Sets.IsRollerSkates, Microsoft.Xna.Framework.Vector2.Lerp(), System.Math.Max(), Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Gore.NewGore(), Terraria.Dust.noGravity, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Color.Transparent, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Terraria.Gore.velocity, Microsoft.Xna.Framework.Color.White, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.