Terraria Decompiled: Terraria.Mount.Initialize
Initialize()
static void Terraria.Mount.Initialize () inline static
Definition at line 70 of file Mount.cs.
        {
            Mount.mounts = new Mount.MountData[MountID.Count];
            Mount.MountData mountData = new Mount.MountData();
            Mount.mounts[0] = mountData;
            mountData.spawnDust = 57;
            mountData.spawnDustNoGravity = false;
            mountData.buff = 90;
            mountData.heightBoost = 20;
            mountData.flightTimeMax = 160;
            mountData.runSpeed = 5.5f;
            mountData.dashSpeed = 12f;
            mountData.acceleration = 0.09f;
            mountData.jumpHeight = 17;
            mountData.jumpSpeed = 5.31f;
            mountData.totalFrames = 12;
            int[] array = new int[mountData.totalFrames];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = 30;
            }
            array[1] += 2;
            array[11] += 2;
            mountData.playerYOffsets = array;
            mountData.xOffset = 13;
            mountData.bodyFrame = 3;
            mountData.yOffset = -7;
            mountData.playerHeadOffset = 22;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 6;
            mountData.flyingFrameCount = 6;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 6;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.idleFrameCount = 4;
            mountData.idleFrameDelay = 30;
            mountData.idleFrameStart = 2;
            mountData.idleFrameLoop = true;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.RudolphMount[0];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.RudolphMount[1];
                mountData.frontTextureExtra = TextureAssets.RudolphMount[2];
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[2] = mountData;
            mountData.spawnDust = 58;
            mountData.buff = 129;
            mountData.heightBoost = 20;
            mountData.flightTimeMax = 160;
            mountData.runSpeed = 5f;
            mountData.dashSpeed = 9f;
            mountData.acceleration = 0.08f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 6.01f;
            mountData.totalFrames = 16;
            array = new int[mountData.totalFrames];
            for (int j = 0; j < array.Length; j++)
            {
                array[j] = 22;
            }
            array[12] += 2;
            array[13] += 4;
            array[14] += 2;
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 8;
            mountData.playerHeadOffset = 22;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 7;
            mountData.runningFrameCount = 5;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 11;
            mountData.flyingFrameCount = 6;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 1;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 3;
            mountData.idleFrameDelay = 20;
            mountData.idleFrameStart = 8;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.PigronMount;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[1] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 128;
            mountData.heightBoost = 20;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.8f;
            mountData.runSpeed = 4f;
            mountData.dashSpeed = 7.8f;
            mountData.acceleration = 0.13f;
            mountData.jumpHeight = 15;
            mountData.jumpSpeed = 5.01f;
            mountData.totalFrames = 7;
            array = new int[mountData.totalFrames];
            for (int k = 0; k < array.Length; k++)
            {
                array[k] = 14;
            }
            array[2] += 2;
            array[3] += 4;
            array[4] += 8;
            array[5] += 8;
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 4;
            mountData.playerHeadOffset = 22;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 6;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 1;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 5;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.BunnyMount;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[3] = mountData;
            mountData.spawnDust = 56;
            mountData.buff = 130;
            mountData.heightBoost = 20;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.5f;
            mountData.extraFall = 10;
            mountData.runSpeed = 4f;
            mountData.dashSpeed = 4f;
            mountData.acceleration = 0.18f;
            mountData.jumpHeight = 12;
            mountData.jumpSpeed = 8.25f;
            mountData.constantJump = true;
            mountData.totalFrames = 4;
            array = new int[mountData.totalFrames];
            for (int l = 0; l < array.Length; l++)
            {
                array[l] = 20;
            }
            array[1] += 2;
            array[3] -= 2;
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 11;
            mountData.playerHeadOffset = 22;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 4;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.SlimeMount;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[6] = mountData;
            mountData.Minecart = true;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.Sparks);
            mountData.spawnDust = 213;
            mountData.buff = 118;
            mountData.heightBoost = 10;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 1f;
            mountData.runSpeed = 13f;
            mountData.dashSpeed = 13f;
            mountData.acceleration = 0.04f;
            mountData.jumpHeight = 15;
            mountData.jumpSpeed = 5.15f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 3;
            array = new int[mountData.totalFrames];
            for (int m = 0; m < array.Length; m++)
            {
                array[m] = 8;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 13;
            mountData.playerHeadOffset = 14;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 3;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 0;
            mountData.inAirFrameDelay = 0;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.MinecartMount;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[15] = mountData;
            Mount.SetAsMinecart(mountData, 208, TextureAssets.DesertMinecartMount, 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[18] = mountData;
            Mount.SetAsMinecart(mountData, 220, TextureAssets.Extra[108], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[19] = mountData;
            Mount.SetAsMinecart(mountData, 222, TextureAssets.Extra[109], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[20] = mountData;
            Mount.SetAsMinecart(mountData, 224, TextureAssets.Extra[110], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[21] = mountData;
            Mount.SetAsMinecart(mountData, 226, TextureAssets.Extra[111], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[22] = mountData;
            Mount.SetAsMinecart(mountData, 228, TextureAssets.Extra[112], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[24] = mountData;
            Mount.SetAsMinecart(mountData, 231, TextureAssets.Extra[115], 0, 0);
            mountData.frontTextureGlow = TextureAssets.Extra[116];
            mountData = new Mount.MountData();
            Mount.mounts[25] = mountData;
            Mount.SetAsMinecart(mountData, 233, TextureAssets.Extra[117], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[26] = mountData;
            Mount.SetAsMinecart(mountData, 235, TextureAssets.Extra[118], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[27] = mountData;
            Mount.SetAsMinecart(mountData, 237, TextureAssets.Extra[119], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[28] = mountData;
            Mount.SetAsMinecart(mountData, 239, TextureAssets.Extra[120], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[29] = mountData;
            Mount.SetAsMinecart(mountData, 241, TextureAssets.Extra[121], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[30] = mountData;
            Mount.SetAsMinecart(mountData, 243, TextureAssets.Extra[122], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[31] = mountData;
            Mount.SetAsMinecart(mountData, 245, TextureAssets.Extra[123], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[32] = mountData;
            Mount.SetAsMinecart(mountData, 247, TextureAssets.Extra[124], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[33] = mountData;
            Mount.SetAsMinecart(mountData, 249, TextureAssets.Extra[125], 0, 0);
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.SparksMeow);
            mountData.delegations.MinecartLandingSound = new Action<Player, Vector2, int, int>(Mount.MeowcartLandingSound);
            mountData.delegations.MinecartBumperSound = new Action<Player, Vector2, int, int>(Mount.MeowcartBumperSound);
            mountData = new Mount.MountData();
            Mount.mounts[34] = mountData;
            Mount.SetAsMinecart(mountData, 251, TextureAssets.Extra[126], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[35] = mountData;
            Mount.SetAsMinecart(mountData, 253, TextureAssets.Extra[127], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[36] = mountData;
            Mount.SetAsMinecart(mountData, 255, TextureAssets.Extra[128], 0, 0);
            mountData = new Mount.MountData();
            Mount.mounts[38] = mountData;
            Mount.SetAsMinecart(mountData, 269, TextureAssets.Extra[150], 0, 0);
            if (Main.netMode != 2)
            {
                mountData.backTexture = mountData.frontTexture;
            }
            mountData = new Mount.MountData();
            Mount.mounts[39] = mountData;
            Mount.SetAsMinecart(mountData, 272, TextureAssets.Extra[155], 0, 0);
            mountData.yOffset -= 2;
            if (Main.netMode != 2)
            {
                mountData.frontTextureExtra = TextureAssets.Extra[165];
            }
            mountData.runSpeed = 6f;
            mountData.dashSpeed = 6f;
            mountData.acceleration = 0.02f;
            mountData = new Mount.MountData();
            Mount.mounts[16] = mountData;
            mountData.Minecart = true;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.Sparks);
            mountData.spawnDust = 213;
            mountData.buff = 210;
            mountData.heightBoost = 10;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 1f;
            mountData.runSpeed = 13f;
            mountData.dashSpeed = 13f;
            mountData.acceleration = 0.04f;
            mountData.jumpHeight = 15;
            mountData.jumpSpeed = 5.15f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 3;
            array = new int[mountData.totalFrames];
            for (int n = 0; n < array.Length; n++)
            {
                array[n] = 8;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 13;
            mountData.playerHeadOffset = 14;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 3;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 0;
            mountData.inAirFrameDelay = 0;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.FishMinecartMount;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[51] = mountData;
            Mount.SetAsMinecart(mountData, 338, TextureAssets.Extra[246], -10, -8);
            mountData.spawnDust = 211;
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.SparksFart);
            mountData.delegations.MinecartBumperSound = new Action<Player, Vector2, int, int>(DelegateMethods.Minecart.BumperSoundFart);
            mountData.delegations.MinecartLandingSound = new Action<Player, Vector2, int, int>(DelegateMethods.Minecart.LandingSoundFart);
            mountData.delegations.MinecartJumpingSound = new Action<Player, Vector2, int, int>(DelegateMethods.Minecart.JumpingSoundFart);
            mountData = new Mount.MountData();
            Mount.mounts[53] = mountData;
            Mount.SetAsMinecart(mountData, 346, TextureAssets.Extra[251], -10, -8);
            mountData.spawnDust = 211;
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.SparksTerraFart);
            mountData.delegations.MinecartBumperSound = new Action<Player, Vector2, int, int>(DelegateMethods.Minecart.BumperSoundFart);
            mountData.delegations.MinecartLandingSound = new Action<Player, Vector2, int, int>(DelegateMethods.Minecart.LandingSoundFart);
            mountData.delegations.MinecartJumpingSound = new Action<Player, Vector2, int, int>(DelegateMethods.Minecart.JumpingSoundFart);
            mountData = new Mount.MountData();
            Mount.mounts[4] = mountData;
            mountData.spawnDust = 56;
            mountData.buff = 131;
            mountData.heightBoost = 26;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 1f;
            mountData.runSpeed = 2f;
            mountData.dashSpeed = 5f;
            mountData.swimSpeed = 10f;
            mountData.acceleration = 0.08f;
            mountData.jumpHeight = 12;
            mountData.jumpSpeed = 3.7f;
            mountData.totalFrames = 12;
            array = new int[mountData.totalFrames];
            for (int num = 0; num < array.Length; num++)
            {
                array[num] = 26;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 13;
            mountData.playerHeadOffset = 28;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 3;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = 6;
            mountData.swimFrameDelay = 12;
            mountData.swimFrameStart = 6;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.TurtleMount;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[5] = mountData;
            mountData.spawnDust = 152;
            mountData.buff = 132;
            mountData.heightBoost = 16;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.runSpeed = 2f;
            mountData.dashSpeed = 2f;
            mountData.acceleration = 0.16f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 4f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 12;
            array = new int[mountData.totalFrames];
            for (int num2 = 0; num2 < array.Length; num2++)
            {
                array[num2] = 16;
            }
            array[8] = 18;
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 4;
            mountData.playerHeadOffset = 18;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 5;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 3;
            mountData.flyingFrameDelay = 12;
            mountData.flyingFrameStart = 5;
            mountData.inAirFrameCount = 3;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 5;
            mountData.idleFrameCount = 4;
            mountData.idleFrameDelay = 12;
            mountData.idleFrameStart = 8;
            mountData.idleFrameLoop = true;
            mountData.swimFrameCount = 0;
            mountData.swimFrameDelay = 12;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.BeeMount[0];
                mountData.backTextureExtra = TextureAssets.BeeMount[1];
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[7] = mountData;
            mountData.spawnDust = 226;
            mountData.spawnDustNoGravity = true;
            mountData.buff = 141;
            mountData.heightBoost = 16;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.runSpeed = 8f;
            mountData.dashSpeed = 8f;
            mountData.acceleration = 0.16f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 4f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 8;
            array = new int[mountData.totalFrames];
            for (int num3 = 0; num3 < array.Length; num3++)
            {
                array[num3] = 16;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 4;
            mountData.playerHeadOffset = 18;
            mountData.standingFrameCount = 8;
            mountData.standingFrameDelay = 4;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 8;
            mountData.runningFrameDelay = 4;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 8;
            mountData.flyingFrameDelay = 4;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 8;
            mountData.inAirFrameDelay = 4;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 12;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = true;
            mountData.swimFrameCount = 0;
            mountData.swimFrameDelay = 12;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.UfoMount[0];
                mountData.frontTextureExtra = TextureAssets.UfoMount[1];
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[8] = mountData;
            mountData.spawnDust = 226;
            mountData.buff = 142;
            mountData.heightBoost = 16;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 1f;
            mountData.usesHover = true;
            mountData.swimSpeed = 4f;
            mountData.runSpeed = 6f;
            mountData.dashSpeed = 4f;
            mountData.acceleration = 0.16f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 4f;
            mountData.blockExtraJumps = true;
            mountData.emitsLight = true;
            mountData.lightColor = new Vector3(0.3f, 0.3f, 0.4f);
            mountData.totalFrames = 1;
            array = new int[mountData.totalFrames];
            for (int num4 = 0; num4 < array.Length; num4++)
            {
                array[num4] = 4;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 4;
            mountData.playerHeadOffset = 18;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 1;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 1;
            mountData.flyingFrameDelay = 12;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 12;
            mountData.idleFrameStart = 8;
            mountData.swimFrameCount = 0;
            mountData.swimFrameDelay = 12;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.DrillMount[0];
                mountData.backTextureGlow = TextureAssets.DrillMount[3];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.backTextureExtraGlow = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.DrillMount[1];
                mountData.frontTextureGlow = TextureAssets.DrillMount[4];
                mountData.frontTextureExtra = TextureAssets.DrillMount[2];
                mountData.frontTextureExtraGlow = TextureAssets.DrillMount[5];
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            Mount.drillTextureSize = new Vector2(80f, 80f);
            if (!Main.dedServ)
            {
                Vector2 vector = new Vector2((float)mountData.textureWidth, (float)(mountData.textureHeight / mountData.totalFrames));
                if (Mount.drillTextureSize != vector)
                {
                    throw new Exception(string.Concat(new object[] { "Be sure to update the Drill texture origin to match the actual texture size of ", mountData.textureWidth, ", ", mountData.textureHeight, "." }));
                }
            }
            mountData = new Mount.MountData();
            Mount.mounts[9] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 143;
            mountData.heightBoost = 16;
            mountData.flightTimeMax = 0;
            mountData.fatigueMax = 0;
            mountData.fallDamage = 0f;
            mountData.abilityChargeMax = 40;
            mountData.abilityCooldown = 20;
            mountData.abilityDuration = 0;
            mountData.runSpeed = 8f;
            mountData.dashSpeed = 8f;
            mountData.acceleration = 0.4f;
            mountData.jumpHeight = 22;
            mountData.jumpSpeed = 10.01f;
            mountData.blockExtraJumps = false;
            mountData.totalFrames = 12;
            array = new int[mountData.totalFrames];
            for (int num5 = 0; num5 < array.Length; num5++)
            {
                array[num5] = 16;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 6;
            mountData.playerHeadOffset = 18;
            mountData.standingFrameCount = 6;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 6;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 12;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 12;
            mountData.idleFrameStart = 6;
            mountData.idleFrameLoop = true;
            mountData.swimFrameCount = 0;
            mountData.swimFrameDelay = 12;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.ScutlixMount[0];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.ScutlixMount[1];
                mountData.frontTextureExtra = TextureAssets.ScutlixMount[2];
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            Mount.scutlixEyePositions = new Vector2[10];
            Mount.scutlixEyePositions[0] = new Vector2(60f, 2f);
            Mount.scutlixEyePositions[1] = new Vector2(70f, 6f);
            Mount.scutlixEyePositions[2] = new Vector2(68f, 6f);
            Mount.scutlixEyePositions[3] = new Vector2(76f, 12f);
            Mount.scutlixEyePositions[4] = new Vector2(80f, 10f);
            Mount.scutlixEyePositions[5] = new Vector2(84f, 18f);
            Mount.scutlixEyePositions[6] = new Vector2(74f, 20f);
            Mount.scutlixEyePositions[7] = new Vector2(76f, 24f);
            Mount.scutlixEyePositions[8] = new Vector2(70f, 34f);
            Mount.scutlixEyePositions[9] = new Vector2(76f, 34f);
            Mount.scutlixTextureSize = new Vector2(45f, 54f);
            if (!Main.dedServ)
            {
                Vector2 vector2 = new Vector2((float)(mountData.textureWidth / 2), (float)(mountData.textureHeight / mountData.totalFrames));
                if (Mount.scutlixTextureSize != vector2)
                {
                    throw new Exception(string.Concat(new object[] { "Be sure to update the Scutlix texture origin to match the actual texture size of ", mountData.textureWidth, ", ", mountData.textureHeight, "." }));
                }
            }
            for (int num6 = 0; num6 < Mount.scutlixEyePositions.Length; num6++)
            {
                Mount.scutlixEyePositions[num6] -= Mount.scutlixTextureSize;
            }
            mountData = new Mount.MountData();
            Mount.mounts[10] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 162;
            mountData.heightBoost = 34;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.2f;
            mountData.runSpeed = 4f;
            mountData.dashSpeed = 12f;
            mountData.acceleration = 0.3f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 8.01f;
            mountData.totalFrames = 16;
            array = new int[mountData.totalFrames];
            for (int num7 = 0; num7 < array.Length; num7++)
            {
                array[num7] = 28;
            }
            array[3] += 2;
            array[4] += 2;
            array[7] += 2;
            array[8] += 2;
            array[12] += 2;
            array[13] += 2;
            array[15] += 4;
            mountData.playerYOffsets = array;
            mountData.xOffset = 5;
            mountData.bodyFrame = 3;
            mountData.yOffset = 1;
            mountData.playerHeadOffset = 34;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 15;
            mountData.runningFrameStart = 1;
            mountData.dashingFrameCount = 6;
            mountData.dashingFrameDelay = 40;
            mountData.dashingFrameStart = 9;
            mountData.flyingFrameCount = 6;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 1;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 15;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.UnicornMount;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[11] = mountData;
            mountData.Minecart = true;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.SparksMech);
            mountData.spawnDust = 213;
            mountData.buff = 166;
            mountData.heightBoost = 12;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 1f;
            mountData.runSpeed = 13f;
            mountData.dashSpeed = 13f;
            mountData.acceleration = 0.04f;
            mountData.jumpHeight = 15;
            mountData.jumpSpeed = 5.15f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 3;
            array = new int[mountData.totalFrames];
            for (int num8 = 0; num8 < array.Length; num8++)
            {
                array[num8] = 9;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = -1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 11;
            mountData.playerHeadOffset = 14;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 3;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 0;
            mountData.inAirFrameDelay = 0;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.MinecartMechMount[0];
                mountData.frontTextureGlow = TextureAssets.MinecartMechMount[1];
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[12] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 168;
            mountData.heightBoost = 14;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.runSpeed = 2f;
            mountData.dashSpeed = 1f;
            mountData.acceleration = 0.2f;
            mountData.jumpHeight = 4;
            mountData.jumpSpeed = 3f;
            mountData.swimSpeed = 16f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 23;
            array = new int[mountData.totalFrames];
            for (int num9 = 0; num9 < array.Length; num9++)
            {
                array[num9] = 12;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 2;
            mountData.bodyFrame = 3;
            mountData.yOffset = 16;
            mountData.playerHeadOffset = 16;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 8;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 14;
            mountData.runningFrameStart = 8;
            mountData.flyingFrameCount = 8;
            mountData.flyingFrameDelay = 16;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 8;
            mountData.inAirFrameDelay = 6;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = 8;
            mountData.swimFrameDelay = 4;
            mountData.swimFrameStart = 15;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.CuteFishronMount[0];
                mountData.backTextureGlow = TextureAssets.CuteFishronMount[1];
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[13] = mountData;
            mountData.Minecart = true;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MinecartDust = new Action<Vector2>(DelegateMethods.Minecart.Sparks);
            mountData.spawnDust = 213;
            mountData.buff = 184;
            mountData.heightBoost = 10;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 1f;
            mountData.runSpeed = 10f;
            mountData.dashSpeed = 10f;
            mountData.acceleration = 0.03f;
            mountData.jumpHeight = 12;
            mountData.jumpSpeed = 5.15f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 3;
            array = new int[mountData.totalFrames];
            for (int num10 = 0; num10 < array.Length; num10++)
            {
                array[num10] = 8;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 13;
            mountData.playerHeadOffset = 14;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 3;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 0;
            mountData.inAirFrameDelay = 0;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.MinecartWoodMount;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[14] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 193;
            mountData.heightBoost = 8;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.2f;
            mountData.runSpeed = 8f;
            mountData.acceleration = 0.25f;
            mountData.jumpHeight = 20;
            mountData.jumpSpeed = 8.01f;
            mountData.totalFrames = 8;
            array = new int[mountData.totalFrames];
            for (int num11 = 0; num11 < array.Length; num11++)
            {
                array[num11] = 8;
            }
            array[1] += 2;
            array[3] += 2;
            array[6] += 2;
            mountData.playerYOffsets = array;
            mountData.xOffset = 4;
            mountData.bodyFrame = 3;
            mountData.yOffset = 9;
            mountData.playerHeadOffset = 10;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 30;
            mountData.runningFrameStart = 2;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.BasiliskMount;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[17] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 212;
            mountData.heightBoost = 16;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.2f;
            mountData.runSpeed = 8f;
            mountData.acceleration = 0.25f;
            mountData.jumpHeight = 20;
            mountData.jumpSpeed = 8.01f;
            mountData.totalFrames = 4;
            array = new int[mountData.totalFrames];
            for (int num12 = 0; num12 < array.Length; num12++)
            {
                array[num12] = 8;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 2;
            mountData.bodyFrame = 3;
            mountData.yOffset = 17 - mountData.heightBoost;
            mountData.playerHeadOffset = 18;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 4;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[97];
                mountData.backTextureExtra = TextureAssets.Extra[96];
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTextureExtra.Width();
                mountData.textureHeight = mountData.backTextureExtra.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[23] = mountData;
            mountData.spawnDust = 43;
            mountData.spawnDustNoGravity = true;
            mountData.buff = 230;
            mountData.heightBoost = 0;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.runSpeed = 9f;
            mountData.dashSpeed = 9f;
            mountData.acceleration = 0.16f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 4f;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 6;
            array = new int[mountData.totalFrames];
            for (int num13 = 0; num13 < array.Length; num13++)
            {
                array[num13] = 6;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = -2;
            mountData.bodyFrame = 0;
            mountData.yOffset = 8;
            mountData.playerHeadOffset = 0;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 0;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 1;
            mountData.runningFrameDelay = 0;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 1;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 6;
            mountData.inAirFrameDelay = 8;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = true;
            mountData.swimFrameCount = 0;
            mountData.swimFrameDelay = 0;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[113];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[37] = mountData;
            mountData.spawnDust = 282;
            mountData.buff = 265;
            mountData.heightBoost = 12;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.2f;
            mountData.runSpeed = 6f;
            mountData.acceleration = 0.15f;
            mountData.jumpHeight = 14;
            mountData.jumpSpeed = 6.01f;
            mountData.totalFrames = 10;
            array = new int[mountData.totalFrames];
            for (int num14 = 0; num14 < array.Length; num14++)
            {
                array[num14] = 20;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 5;
            mountData.bodyFrame = 4;
            mountData.yOffset = 1;
            mountData.playerHeadOffset = 20;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 20;
            mountData.runningFrameStart = 2;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.runningFrameCount;
            mountData.swimFrameDelay = 10;
            mountData.swimFrameStart = mountData.runningFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[149];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[40] = mountData;
            Mount.SetAsHorse(mountData, 275, TextureAssets.Extra[161]);
            mountData = new Mount.MountData();
            Mount.mounts[41] = mountData;
            Mount.SetAsHorse(mountData, 276, TextureAssets.Extra[162]);
            mountData = new Mount.MountData();
            Mount.mounts[42] = mountData;
            Mount.SetAsHorse(mountData, 277, TextureAssets.Extra[163]);
            mountData = new Mount.MountData();
            Mount.mounts[43] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 278;
            mountData.heightBoost = 12;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.25f;
            mountData.extraFall = 20;
            mountData.runSpeed = 5f;
            mountData.acceleration = 0.1f;
            mountData.jumpHeight = 8;
            mountData.jumpSpeed = 8f;
            mountData.constantJump = true;
            mountData.totalFrames = 4;
            array = new int[mountData.totalFrames];
            for (int num15 = 0; num15 < array.Length; num15++)
            {
                array[num15] = 14;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 5;
            mountData.bodyFrame = 4;
            mountData.yOffset = 10;
            mountData.playerHeadOffset = 10;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 5;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 4;
            mountData.runningFrameDelay = 5;
            mountData.runningFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 5;
            mountData.inAirFrameStart = 0;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = 1;
            mountData.swimFrameDelay = 5;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[164];
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[44] = mountData;
            mountData.spawnDust = 228;
            mountData.buff = 279;
            mountData.heightBoost = 24;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.runSpeed = 3f;
            mountData.dashSpeed = 6f;
            mountData.acceleration = 0.12f;
            mountData.jumpHeight = 3;
            mountData.jumpSpeed = 1f;
            mountData.swimSpeed = mountData.runSpeed;
            mountData.blockExtraJumps = true;
            mountData.totalFrames = 10;
            array = new int[mountData.totalFrames];
            for (int num16 = 0; num16 < array.Length; num16++)
            {
                array[num16] = 9;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 0;
            mountData.bodyFrame = 3;
            mountData.yOffset = 8;
            mountData.playerHeadOffset = 16;
            mountData.runningFrameCount = 10;
            mountData.runningFrameDelay = 8;
            mountData.runningFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[166];
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[45] = mountData;
            mountData.spawnDust = 6;
            mountData.buff = 280;
            mountData.heightBoost = 25;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.1f;
            mountData.runSpeed = 12f;
            mountData.dashSpeed = 16f;
            mountData.acceleration = 0.5f;
            mountData.jumpHeight = 14;
            mountData.jumpSpeed = 7f;
            mountData.emitsLight = true;
            mountData.lightColor = new Vector3(0.6f, 0.4f, 0.35f);
            mountData.totalFrames = 8;
            array = new int[mountData.totalFrames];
            for (int num17 = 0; num17 < array.Length; num17++)
            {
                array[num17] = 30;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 0;
            mountData.bodyFrame = 0;
            mountData.xOffset = 2;
            mountData.yOffset = 1;
            mountData.playerHeadOffset = 20;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 20;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 20;
            mountData.runningFrameStart = 2;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 20;
            mountData.inAirFrameStart = 1;
            mountData.swimFrameCount = mountData.runningFrameCount;
            mountData.swimFrameDelay = 20;
            mountData.swimFrameStart = mountData.runningFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[167];
                mountData.backTextureGlow = TextureAssets.GlowMask[283];
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[46] = mountData;
            mountData.spawnDust = 15;
            mountData.buff = 281;
            mountData.heightBoost = 0;
            mountData.flightTimeMax = 0;
            mountData.fatigueMax = 0;
            mountData.fallDamage = 0f;
            mountData.abilityChargeMax = 40;
            mountData.abilityCooldown = 40;
            mountData.abilityDuration = 0;
            mountData.runSpeed = 8f;
            mountData.dashSpeed = 8f;
            mountData.acceleration = 0.4f;
            mountData.jumpHeight = 8;
            mountData.jumpSpeed = 9.01f;
            mountData.blockExtraJumps = false;
            mountData.totalFrames = 27;
            array = new int[mountData.totalFrames];
            for (int num18 = 0; num18 < array.Length; num18++)
            {
                array[num18] = 4;
                if (num18 == 1 || num18 == 2 || num18 == 7 || num18 == 8)
                {
                    array[num18] += 2;
                }
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = 1;
            mountData.playerHeadOffset = 2;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 11;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 0;
            mountData.inAirFrameCount = 11;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 1;
            mountData.swimFrameCount = mountData.runningFrameCount;
            mountData.swimFrameDelay = mountData.runningFrameDelay;
            mountData.swimFrameStart = mountData.runningFrameStart;
            Mount.santankTextureSize = new Vector2(23f, 2f);
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[168];
                mountData.frontTextureExtra = TextureAssets.Extra[168];
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[47] = mountData;
            mountData.spawnDust = 5;
            mountData.buff = 282;
            mountData.heightBoost = 34;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.2f;
            mountData.runSpeed = 4f;
            mountData.dashSpeed = 12f;
            mountData.acceleration = 0.3f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 8.01f;
            mountData.totalFrames = 16;
            array = new int[mountData.totalFrames];
            for (int num19 = 0; num19 < array.Length; num19++)
            {
                array[num19] = 30;
            }
            array[3] += 2;
            array[4] += 2;
            array[7] += 2;
            array[8] += 2;
            array[12] += 2;
            array[13] += 2;
            array[15] += 4;
            mountData.playerYOffsets = array;
            mountData.xOffset = 5;
            mountData.bodyFrame = 3;
            mountData.yOffset = -1;
            mountData.playerHeadOffset = 34;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 15;
            mountData.runningFrameStart = 1;
            mountData.dashingFrameCount = 6;
            mountData.dashingFrameDelay = 40;
            mountData.dashingFrameStart = 9;
            mountData.flyingFrameCount = 6;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 1;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 15;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[169];
                mountData.backTextureGlow = TextureAssets.GlowMask[284];
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[48] = mountData;
            mountData.spawnDust = 62;
            mountData.buff = 283;
            mountData.heightBoost = 14;
            mountData.flightTimeMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.runSpeed = 8f;
            mountData.dashSpeed = 8f;
            mountData.acceleration = 0.2f;
            mountData.jumpHeight = 5;
            mountData.jumpSpeed = 6f;
            mountData.swimSpeed = mountData.runSpeed;
            mountData.totalFrames = 6;
            array = new int[mountData.totalFrames];
            for (int num20 = 0; num20 < array.Length; num20++)
            {
                array[num20] = 9;
            }
            array[0] += 6;
            array[1] += 6;
            array[2] += 4;
            array[3] += 4;
            array[4] += 4;
            array[5] += 6;
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 0;
            mountData.yOffset = 16;
            mountData.playerHeadOffset = 16;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 8;
            mountData.runningFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[170];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[49] = mountData;
            mountData.spawnDust = 35;
            mountData.buff = 305;
            mountData.heightBoost = 8;
            mountData.runSpeed = 2f;
            mountData.dashSpeed = 1f;
            mountData.acceleration = 0.4f;
            mountData.jumpHeight = 4;
            mountData.jumpSpeed = 3f;
            mountData.swimSpeed = 14f;
            mountData.blockExtraJumps = true;
            mountData.flightTimeMax = 0;
            mountData.fatigueMax = 320;
            mountData.usesHover = true;
            mountData.emitsLight = true;
            mountData.lightColor = new Vector3(0.3f, 0.15f, 0.1f);
            mountData.totalFrames = 8;
            array = new int[mountData.totalFrames];
            for (int num21 = 0; num21 < array.Length; num21++)
            {
                array[num21] = 10;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 2;
            mountData.bodyFrame = 3;
            mountData.yOffset = 1;
            mountData.playerHeadOffset = 16;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 4;
            mountData.runningFrameCount = 4;
            mountData.runningFrameDelay = 14;
            mountData.runningFrameStart = 4;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 6;
            mountData.inAirFrameStart = 4;
            mountData.swimFrameCount = 4;
            mountData.swimFrameDelay = 16;
            mountData.swimFrameStart = 0;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[172];
                mountData.backTextureGlow = TextureAssets.GlowMask[285];
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[50] = mountData;
            mountData.spawnDust = 243;
            mountData.buff = 318;
            mountData.heightBoost = 20;
            mountData.flightTimeMax = 80;
            mountData.fallDamage = 0.5f;
            mountData.runSpeed = 5.5f;
            mountData.dashSpeed = 5.5f;
            mountData.acceleration = 0.2f;
            mountData.jumpHeight = 10;
            mountData.jumpSpeed = 7.25f;
            mountData.constantJump = true;
            mountData.totalFrames = 8;
            array = new int[mountData.totalFrames];
            for (int num22 = 0; num22 < array.Length; num22++)
            {
                array[num22] = 20;
            }
            array[1] += 2;
            array[4] += 2;
            array[5] += 2;
            mountData.playerYOffsets = array;
            mountData.xOffset = 1;
            mountData.bodyFrame = 3;
            mountData.yOffset = -1;
            mountData.playerHeadOffset = 22;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 5;
            mountData.runningFrameDelay = 16;
            mountData.runningFrameStart = 0;
            mountData.flyingFrameCount = 0;
            mountData.flyingFrameDelay = 0;
            mountData.flyingFrameStart = 0;
            mountData.inAirFrameCount = 1;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 5;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            if (Main.netMode != 2)
            {
                mountData.backTexture = TextureAssets.Extra[204];
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.backTexture.Width();
                mountData.textureHeight = mountData.backTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[52] = mountData;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MouthPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.WolfMouthPosition);
            mountData.delegations.HandPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.spawnDust = 31;
            mountData.buff = 342;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.1f;
            mountData.runSpeed = 9.5f;
            mountData.acceleration = 0.18f;
            mountData.jumpHeight = 18;
            mountData.jumpSpeed = 9.01f;
            mountData.totalFrames = 15;
            array = new int[mountData.totalFrames];
            for (int num23 = 0; num23 < array.Length; num23++)
            {
                array[num23] = 0;
            }
            array[1] += -14;
            array[2] += -10;
            array[3] += -8;
            array[4] += 18;
            array[5] += -2;
            int[] array2 = array;
            int num24 = 6;
            array2[num24] = array2[num24];
            array[7] += 2;
            array[8] += 4;
            array[9] += 4;
            array[10] += 2;
            int[] array3 = array;
            int num25 = 11;
            array3[num25] = array3[num25];
            array[12] += 4;
            array[13] += 2;
            array[14] += -4;
            mountData.playerYOffsets = array;
            mountData.xOffset = 4;
            mountData.bodyFrame = 3;
            mountData.yOffset = -1;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 6;
            mountData.runningFrameDelay = 20;
            mountData.runningFrameStart = 5;
            mountData.inAirFrameCount = 3;
            mountData.inAirFrameDelay = 12;
            mountData.inAirFrameStart = 12;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[253];
                mountData.frontTextureExtra = TextureAssets.Extra[254];
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[54] = mountData;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MouthPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.VelociraptorMouthPosition);
            mountData.delegations.HandPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.spawnDust = 31;
            mountData.buff = 370;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.1f;
            mountData.runSpeed = 4.5f;
            mountData.dashSpeed = 7.5f;
            mountData.acceleration = 0.15f;
            mountData.jumpHeight = 15;
            mountData.jumpSpeed = 6.01f;
            mountData.totalFrames = 21;
            array = new int[mountData.totalFrames];
            for (int num26 = 0; num26 < array.Length; num26++)
            {
                array[num26] = 0;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 4;
            mountData.bodyFrame = 0;
            mountData.yOffset = -4;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 20;
            mountData.runningFrameStart = 8;
            mountData.inAirFrameCount = 2;
            mountData.inAirFrameDelay = 6;
            mountData.inAirFrameStart = 5;
            mountData.flyingFrameCount = 5;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 16;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[271];
                mountData.frontTextureExtra = TextureAssets.Extra[272];
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[55] = mountData;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MouthPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.delegations.HandPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.delegations.PlayerSize = new Mount.MountDelegatesData.OverrideSizeMethod(DelegateMethods.Mount.RatPlayerSize);
            mountData.spawnDust = 31;
            mountData.buff = 374;
            mountData.flightTimeMax = 0;
            mountData.fallDamage = 0.1f;
            mountData.dismountsOnItemUse = true;
            mountData.runSpeed = 4.5f;
            mountData.dashSpeed = 7.5f;
            mountData.acceleration = 0.15f;
            mountData.jumpHeight = 15;
            mountData.jumpSpeed = 6.01f;
            mountData.totalFrames = 16;
            array = new int[mountData.totalFrames];
            for (int num27 = 0; num27 < array.Length; num27++)
            {
                array[num27] = 0;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = 0;
            mountData.bodyFrame = 3;
            mountData.yOffset = -2;
            mountData.playerHeadOffset = -30;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 12;
            mountData.standingFrameStart = 0;
            mountData.runningFrameCount = 7;
            mountData.runningFrameDelay = 12;
            mountData.runningFrameStart = 4;
            mountData.dashingFrameCount = 5;
            mountData.dashingFrameDelay = 16;
            mountData.dashingFrameStart = 11;
            mountData.inAirFrameCount = 3;
            mountData.inAirFrameDelay = 6;
            mountData.inAirFrameStart = 12;
            mountData.idleFrameCount = 4;
            mountData.idleFrameDelay = 16;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.swimFrameCount = mountData.inAirFrameCount;
            mountData.swimFrameDelay = mountData.inAirFrameDelay;
            mountData.swimFrameStart = mountData.inAirFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[273];
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[56] = mountData;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MouthPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.delegations.HandPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.delegations.PlayerSize = new Mount.MountDelegatesData.OverrideSizeMethod(DelegateMethods.Mount.BatPlayerSize);
            mountData.delegations.DashDust = new Mount.MountDelegatesData.AdjustDashDustMethod(DelegateMethods.Mount.BatDashDust);
            mountData.spawnDust = 31;
            mountData.buff = 377;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.dismountsOnItemUse = true;
            mountData.blockExtraJumps = true;
            mountData.dashSpeed = 4.5f;
            mountData.runSpeed = mountData.dashSpeed;
            mountData.acceleration = 0.2f;
            mountData.jumpHeight = 8;
            mountData.jumpSpeed = 5f;
            mountData.totalFrames = 16;
            array = new int[mountData.totalFrames];
            for (int num28 = 0; num28 < array.Length; num28++)
            {
                array[num28] = 0;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = -4;
            mountData.bodyFrame = 3;
            mountData.yOffset = -1;
            mountData.playerHeadOffset = -24;
            mountData.standingFrameCount = 1;
            mountData.standingFrameDelay = 6;
            mountData.standingFrameStart = 0;
            mountData.dashingFrameCount = 6;
            mountData.dashingFrameDelay = 40;
            mountData.dashingFrameStart = 9;
            mountData.flyingFrameCount = 8;
            mountData.flyingFrameDelay = 5;
            mountData.flyingFrameStart = 1;
            mountData.idleFrameCount = 0;
            mountData.idleFrameDelay = 0;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = false;
            mountData.runningFrameCount = mountData.flyingFrameCount;
            mountData.runningFrameDelay = mountData.flyingFrameDelay;
            mountData.runningFrameStart = mountData.flyingFrameStart;
            mountData.inAirFrameCount = mountData.flyingFrameCount;
            mountData.inAirFrameDelay = mountData.flyingFrameDelay;
            mountData.inAirFrameStart = mountData.flyingFrameStart;
            mountData.swimFrameCount = mountData.flyingFrameCount;
            mountData.swimFrameDelay = mountData.flyingFrameDelay;
            mountData.swimFrameStart = mountData.flyingFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[274];
                mountData.frontTextureGlow = TextureAssets.GlowMask[370];
                mountData.frontTextureExtra = Asset<Texture2D>.Empty;
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[61] = mountData;
            mountData.delegations = new Mount.MountDelegatesData();
            mountData.delegations.MouthPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.delegations.HandPosition = new Mount.MountDelegatesData.OverridePositionMethod(DelegateMethods.Mount.NoPosition);
            mountData.delegations.PlayerSize = new Mount.MountDelegatesData.OverrideSizeMethod(DelegateMethods.Mount.PixiePlayerSize);
            mountData.delegations.DashDust = new Mount.MountDelegatesData.AdjustDashDustMethod(DelegateMethods.Mount.PixieDashDust);
            mountData.spawnDust = 43;
            mountData.spawnDustNoGravity = true;
            mountData.buff = 384;
            mountData.flightTimeMax = 320;
            mountData.fatigueMax = 320;
            mountData.fallDamage = 0f;
            mountData.usesHover = true;
            mountData.dismountsOnItemUse = true;
            mountData.blockExtraJumps = true;
            mountData.dashSpeed = 4.5f;
            mountData.runSpeed = mountData.dashSpeed;
            mountData.acceleration = 0.2f;
            mountData.jumpHeight = 8;
            mountData.jumpSpeed = 5f;
            mountData.totalFrames = 4;
            array = new int[mountData.totalFrames];
            for (int num29 = 0; num29 < array.Length; num29++)
            {
                array[num29] = 0;
            }
            mountData.playerYOffsets = array;
            mountData.xOffset = -2;
            mountData.yOffset = -1;
            mountData.bodyFrame = 0;
            mountData.playerHeadOffset = -24;
            mountData.standingFrameCount = 4;
            mountData.standingFrameDelay = 8;
            mountData.standingFrameStart = 0;
            mountData.dashingFrameCount = 4;
            mountData.dashingFrameDelay = 2;
            mountData.dashingFrameStart = 0;
            mountData.flyingFrameCount = 4;
            mountData.flyingFrameDelay = 6;
            mountData.flyingFrameStart = 0;
            mountData.idleFrameCount = 4;
            mountData.idleFrameDelay = 8;
            mountData.idleFrameStart = 0;
            mountData.idleFrameLoop = true;
            mountData.runningFrameCount = mountData.flyingFrameCount;
            mountData.runningFrameDelay = mountData.flyingFrameDelay;
            mountData.runningFrameStart = mountData.flyingFrameStart;
            mountData.inAirFrameCount = mountData.flyingFrameCount;
            mountData.inAirFrameDelay = mountData.flyingFrameDelay;
            mountData.inAirFrameStart = mountData.flyingFrameStart;
            mountData.swimFrameCount = mountData.flyingFrameCount;
            mountData.swimFrameDelay = mountData.flyingFrameDelay;
            mountData.swimFrameStart = mountData.flyingFrameStart;
            if (Main.netMode != 2)
            {
                mountData.backTexture = Asset<Texture2D>.Empty;
                mountData.backTextureExtra = Asset<Texture2D>.Empty;
                mountData.frontTexture = TextureAssets.Extra[290];
                mountData.frontTextureGlow = Asset<Texture2D>.Empty;
                mountData.frontTextureExtra = TextureAssets.Extra[291];
                mountData.textureWidth = mountData.frontTexture.Width();
                mountData.textureHeight = mountData.frontTexture.Height();
            }
            mountData = new Mount.MountData();
            Mount.mounts[57] = mountData;
            Mount.SetAsRollerSkate(mountData, 378);
            mountData = new Mount.MountData();
            Mount.mounts[58] = mountData;
            Mount.SetAsRollerSkate(mountData, 379);
            mountData = new Mount.MountData();
            Mount.mounts[59] = mountData;
            Mount.SetAsRollerSkate(mountData, 380);
            mountData = new Mount.MountData();
            Mount.mounts[60] = mountData;
            Mount.SetAsRollerSkate(mountData, 381);
            mountData = new Mount.MountData();
            Mount.mounts[62] = mountData;
            Mount.SetAsChillet(mountData, 387, TextureAssets.Extra[301]);
            mountData = new Mount.MountData();
            Mount.mounts[63] = mountData;
            Mount.SetAsChillet(mountData, 388, TextureAssets.Extra[302]);
        }
References Terraria.Mount.MountDelegatesData.AdjustDashDustMethod(), System.array, Terraria.Mount.MountData.backTexture, Terraria.Mount.MountData.backTextureExtra, Terraria.GameContent.TextureAssets.BasiliskMount, Terraria.DelegateMethods.Mount.BatDashDust(), Terraria.DelegateMethods.Mount.BatPlayerSize(), Terraria.GameContent.TextureAssets.BeeMount, Terraria.DelegateMethods.Minecart.BumperSoundFart(), Terraria.GameContent.TextureAssets.BunnyMount, Terraria.ID.MountID.Count, Terraria.GameContent.TextureAssets.CuteFishronMount, Terraria.Mount.MountData.dashSpeed, Terraria.Main.dedServ, Terraria.GameContent.TextureAssets.DesertMinecartMount, Terraria.GameContent.TextureAssets.DrillMount, Terraria.Mount.drillTextureSize, ReLogic.Content.Asset< T >.Empty, Terraria.GameContent.TextureAssets.Extra, Terraria.GameContent.TextureAssets.FishMinecartMount, Terraria.Mount.MountData.flyingFrameCount, Terraria.Mount.MountData.flyingFrameDelay, Terraria.Mount.MountData.flyingFrameStart, Terraria.Mount.MountData.frontTexture, Terraria.GameContent.TextureAssets.GlowMask, Terraria.Mount.MountData.heightBoost, Terraria.Mount.MountData.inAirFrameCount, Terraria.Mount.MountData.inAirFrameDelay, Terraria.Mount.MountData.inAirFrameStart, Terraria.DelegateMethods.Minecart.JumpingSoundFart(), Terraria.DelegateMethods.Minecart.LandingSoundFart(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Mount.MeowcartBumperSound(), Terraria.Mount.MeowcartLandingSound(), Terraria.GameContent.TextureAssets.MinecartMechMount, Terraria.GameContent.TextureAssets.MinecartMount, Terraria.GameContent.TextureAssets.MinecartWoodMount, Terraria.Mount.mounts, Terraria.Main.netMode, Terraria.DelegateMethods.Mount.NoPosition(), Terraria.Mount.MountDelegatesData.OverridePositionMethod(), Terraria.Mount.MountDelegatesData.OverrideSizeMethod(), Terraria.GameContent.TextureAssets.PigronMount, Terraria.DelegateMethods.Mount.PixieDashDust(), Terraria.DelegateMethods.Mount.PixiePlayerSize(), Terraria.DelegateMethods.Mount.RatPlayerSize(), Terraria.GameContent.TextureAssets.RudolphMount, Terraria.Mount.MountData.runningFrameCount, Terraria.Mount.MountData.runningFrameDelay, Terraria.Mount.MountData.runningFrameStart, Terraria.Mount.MountData.runSpeed, Terraria.Mount.scutlixEyePositions, Terraria.GameContent.TextureAssets.ScutlixMount, Terraria.Mount.scutlixTextureSize, Terraria.Mount.SetAsChillet(), Terraria.Mount.SetAsHorse(), Terraria.Mount.SetAsMinecart(), Terraria.Mount.SetAsRollerSkate(), Terraria.GameContent.TextureAssets.SlimeMount, Terraria.DelegateMethods.Minecart.Sparks(), Terraria.DelegateMethods.Minecart.SparksFart(), Terraria.DelegateMethods.Minecart.SparksMech(), Terraria.DelegateMethods.Minecart.SparksMeow(), Terraria.DelegateMethods.Minecart.SparksTerraFart(), Terraria.Mount.MountData.textureHeight, Terraria.Mount.MountData.textureWidth, Terraria.Mount.MountData.totalFrames, Terraria.GameContent.TextureAssets.TurtleMount, Terraria.GameContent.TextureAssets.UfoMount, Terraria.GameContent.TextureAssets.UnicornMount, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Vector3, Terraria.DelegateMethods.Mount.VelociraptorMouthPosition(), and Terraria.DelegateMethods.Mount.WolfMouthPosition().
Referenced by Terraria.Main.Initialize_AlmostEverything(), and Terraria.Main.PostContentLoadInitialize().