Terraria Decompiled: Terraria.Mount.TryPettingMount
TryPettingMount()
void Terraria.Mount.TryPettingMount (Player player) inline private
Definition at line 6135 of file Mount.cs.
        {
            if (Main.gameMenu || Main.gamePaused)
            {
                return;
            }
            if (Math.Abs(player.velocity.X) >= 1f)
            {
                return;
            }
            Vector2 vector = Main.ReverseGravitySupport(Main.MouseScreen, 0f) + Main.screenPosition;
            bool flag = Utils.CenteredRectangle(player.Bottom + new Vector2((float)(player.direction * 26), -54f), new Vector2(24f, 24f)).Contains(vector.ToPoint());
            bool flag2 = flag & !player.lastMouseInterface;
            if (!Main.SmartCursorIsUsed)
            {
                bool flag3 = !PlayerInput.UsingGamepad;
            }
            if (!flag2)
            {
                return;
            }
            if (flag)
            {
                player.noThrow = 4;
                player.cursorItemIconEnabled = true;
                player.cursorItemIconID = ((this._type == 63) ? 5666 : 5665);
            }
            if (PlayerInput.UsingGamepad)
            {
                player.GamepadEnableGrappleCooldown();
            }
            if (Main.mouseRight && Main.mouseRightRelease && Player.BlockInteractionWithProjectiles == 0)
            {
                Main.mouseRightRelease = false;
                player.tileInteractAttempted = true;
                player.tileInteractionHappened = true;
                player.releaseUseTile = false;
                player.PetMount(new PlayerPettingInfo(this._type, false));
                EmoteBubble.NewBubble(0, new WorldUIAnchor(Main.LocalPlayer), 60);
            }
        }
References System.Math.Abs(), Terraria.Player.BlockInteractionWithProjectiles, Terraria.Entity.Bottom, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Entity.direction, Terraria.Main.gameMenu, Terraria.Player.GamepadEnableGrappleCooldown(), Terraria.Main.gamePaused, Terraria.Player.lastMouseInterface, Terraria.Main.LocalPlayer, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Main.MouseScreen, Terraria.GameContent.UI.EmoteBubble.NewBubble(), Terraria.Player.PetMount(), Terraria.Main.ReverseGravitySupport(), Terraria.Main.screenPosition, Terraria.Main.SmartCursorIsUsed, Terraria.GameInput.PlayerInput.UsingGamepad, Terraria.Entity.velocity, and Microsoft.Xna.Framework.Vector2.X.