Terraria Decompiled: Terraria.Utilities.PlatformUtilities.SavePng
SavePng()
static unsafe void Terraria.Utilities.PlatformUtilities.SavePng (string path, int width, int height, byte[] data) inline static
Definition at line 11 of file PlatformUtilities.cs.
        {
            if (width * height * 4 > data.Length)
            {
                throw new IndexOutOfRangeException();
            }
            fixed (byte[] array = data)
            {
                byte* ptr;
                if (data == null || array.Length == 0)
                {
                    ptr = null;
                }
                else
                {
                    ptr = &array[0];
                }
                IntPtr intPtr = SDL.SDL_CreateSurfaceFrom(width, height, SDL.SDL_PixelFormat.SDL_PIXELFORMAT_ABGR8888, (IntPtr)((void*)ptr), width * 4);
                if (intPtr == IntPtr.Zero)
                {
                    throw new IOException("Failed to create SDL surface: " + SDL.SDL_GetError());
                }
                try
                {
                    IntPtr intPtr2 = SDL.SDL_IOFromFile(path, "wb");
                    if (intPtr2 == IntPtr.Zero)
                    {
                        throw new IOException("Failed to open file for writing: " + SDL.SDL_GetError());
                    }
                    if (!SDL.SDL_SavePNG_IO(intPtr, intPtr2, true))
                    {
                        throw new IOException("Failed to save PNG: " + SDL.SDL_GetError());
                    }
                }
                finally
                {
                    SDL.SDL_DestroySurface(intPtr);
                }
            }
        }
References System.array, SDL3.SDL.SDL_CreateSurfaceFrom(), SDL3.SDL.SDL_DestroySurface(), SDL3.SDL.SDL_GetError(), SDL3.SDL.SDL_IOFromFile(), SDL3.SDL.SDL_SavePNG_IO(), and System.IntPtr.Zero.
Referenced by Terraria.Graphics.Capture.CaptureCamera.SaveImage(), and Terraria.Graphics.Capture.CaptureCamera.SaveImage().