Terraria Decompiled: System.Security.NamedPermissionSet.ToXml
ToXml()
override SecurityElement System.Security.NamedPermissionSet.ToXml () inline virtual
Reimplemented from System.Security.PermissionSet.
Definition at line 107 of file NamedPermissionSet.cs.
        {
            SecurityElement securityElement = base.ToXml();
            if (this.name != null)
            {
                securityElement.AddAttribute("Name", this.name);
            }
            if (this.description != null)
            {
                securityElement.AddAttribute("Description", this.description);
            }
            return securityElement;
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.NamedPermissionSet.description, System.Security.NamedPermissionSet.name, and System.Security.SecurityElement.ToXml().
Referenced by System.Security.Policy.PolicyLevel.ToXml().