Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D
Texture2D() [2/2]
Microsoft.Xna.Framework.Graphics.Texture2D.Texture2D (GraphicsDevice graphicsDevice, int width, int height, bool mipMap, SurfaceFormat format) inline
Definition at line 62 of file Texture2D.cs.
        {
            if (graphicsDevice == null)
            {
                throw new ArgumentNullException("graphicsDevice");
            }
            base.GraphicsDevice = graphicsDevice;
            this.Width = width;
            this.Height = height;
            base.LevelCount = (mipMap ? Texture.CalculateMipLevels(width, height, 0) : 1);
            if (this is IRenderTarget)
            {
                if (format == SurfaceFormat.ColorSrgbEXT)
                {
                    if (FNA3D.FNA3D_SupportsSRGBRenderTargets(base.GraphicsDevice.GLDevice) == 0)
                    {
                        base.Format = SurfaceFormat.Color;
                    }
                    else
                    {
                        base.Format = format;
                    }
                }
                else if (format != SurfaceFormat.Color && format != SurfaceFormat.Rgba1010102 && format != SurfaceFormat.Rg32 && format != SurfaceFormat.Rgba64 && format != SurfaceFormat.Single && format != SurfaceFormat.Vector2 && format != SurfaceFormat.Vector4 && format != SurfaceFormat.HalfSingle && format != SurfaceFormat.HalfVector2 && format != SurfaceFormat.HalfVector4 && format != SurfaceFormat.HdrBlendable && format != SurfaceFormat.ByteEXT && format != SurfaceFormat.UShortEXT)
                {
                    base.Format = SurfaceFormat.Color;
                }
                else
                {
                    base.Format = format;
                }
            }
            else
            {
                base.Format = format;
            }
            this.texture = FNA3D.FNA3D_CreateTexture2D(base.GraphicsDevice.GLDevice, base.Format, this.Width, this.Height, base.LevelCount, (this is IRenderTarget) ? 1 : 0);
        }
References Microsoft.Xna.Framework.Graphics.Texture.CalculateMipLevels(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_CreateTexture2D(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SupportsSRGBRenderTargets(), System.format, and Microsoft.Xna.Framework.Graphics.GraphicsResource.graphicsDevice.