Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture2D.GetData< T >
GetData< T >() [1/3]
void Microsoft.Xna.Framework.Graphics.Texture2D.GetData< T > (int level, Rectangle? rect, T[] data, int startIndex, int elementCount) inline
Type Constraints
T : struct
Definition at line 199 of file Texture2D.cs.
                                                                                                               : struct
        {
            if (data == null || data.Length == 0)
            {
                throw new ArgumentException("data cannot be null");
            }
            if (data.Length < startIndex + elementCount)
            {
                throw new ArgumentException(string.Concat(new string[]
                {
                    "The data passed has a length of ",
                    data.Length.ToString(),
                    " but ",
                    elementCount.ToString(),
                    " pixels have been requested."
                }));
            }
            int num = MarshalHelper.SizeOf<T>();
            Texture.ValidateGetDataFormat(base.Format, num);
            GCHandle gchandle = GCHandle.Alloc(data, GCHandleType.Pinned);
            this.GetDataPointerEXT(level, rect, gchandle.AddrOfPinnedObject() + startIndex * num, elementCount * num);
            gchandle.Free();
        }
References System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject(), System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.GCHandle.Free(), Microsoft.Xna.Framework.Graphics.Texture2D.GetDataPointerEXT(), System.startIndex, and Microsoft.Xna.Framework.Graphics.Texture.ValidateGetDataFormat().