Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStreamEXT
TextureDataFromStreamEXT()
static void Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStreamEXT (Stream stream, out int width, out int height, out byte[] pixels, int requestedWidth = -1, int requestedHeight = -1, bool zoom = false) inline static
Definition at line 316 of file Texture2D.cs.
        {
            if (stream.CanSeek && stream.Position == stream.Length)
            {
                stream.Seek(0L, SeekOrigin.Begin);
            }
            int num;
            IntPtr intPtr = FNA3D.ReadImageStream(stream, out width, out height, out num, requestedWidth, requestedHeight, zoom);
            pixels = new byte[num];
            Marshal.Copy(intPtr, pixels, 0, num);
            FNA3D.FNA3D_Image_Free(intPtr);
        }
References System.IO.Stream.CanSeek, System.Runtime.InteropServices.Marshal.Copy(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_Image_Free(), System.L, System.IO.Stream.Length, System.IO.Stream.Position, Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream(), and System.IO.Stream.Seek().