Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture2D.FromStream
FromStream() [1/2]
static Texture2D Microsoft.Xna.Framework.Graphics.Texture2D.FromStream (GraphicsDevice graphicsDevice, Stream stream) inline static
Definition at line 274 of file Texture2D.cs.
        {
            if (stream.CanSeek && stream.Position == stream.Length)
            {
                stream.Seek(0L, SeekOrigin.Begin);
            }
            int num;
            int num2;
            int num3;
            IntPtr intPtr = FNA3D.ReadImageStream(stream, out num, out num2, out num3, -1, -1, false);
            if (intPtr == IntPtr.Zero || num <= 0 || num2 <= 0)
            {
                throw new Exception("Decoding image failed!");
            }
            Texture2D texture2D = new Texture2D(graphicsDevice, num, num2);
            texture2D.SetDataPointerEXT(0, null, intPtr, num3);
            FNA3D.FNA3D_Image_Free(intPtr);
            return texture2D;
        }
References System.IO.Stream.CanSeek, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_Image_Free(), Microsoft.Xna.Framework.Graphics.GraphicsResource.graphicsDevice, System.L, System.IO.Stream.Length, System.IO.Stream.Position, Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream(), System.IO.Stream.Seek(), Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT(), Microsoft.Xna.Framework.Graphics.Texture2D, and System.IntPtr.Zero.
Referenced by ReLogic.Content.Readers.PngReader.FromStream< T >(), Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview().