Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsJpeg
SaveAsJpeg()
void Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsJpeg (Stream stream, int width, int height) inline
Definition at line 248 of file Texture2D.cs.
        {
            string environmentVariable = Environment.GetEnvironmentVariable("FNA_GRAPHICS_JPEG_SAVE_QUALITY");
            int num;
            if (string.IsNullOrEmpty(environmentVariable) || !int.TryParse(environmentVariable, out num))
            {
                num = 100;
            }
            int num2 = this.Width * this.Height * Texture.GetFormatSizeEXT(base.Format);
            IntPtr intPtr = FNAPlatform.Malloc(num2);
            FNA3D.FNA3D_GetTextureData2D(base.GraphicsDevice.GLDevice, this.texture, 0, 0, this.Width, this.Height, 0, intPtr, num2);
            FNA3D.WriteJPGStream(stream, this.Width, this.Height, width, height, intPtr, num);
            FNAPlatform.Free(intPtr);
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_GetTextureData2D(), Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Graphics.Texture.GetFormatSizeEXT(), Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.FNAPlatform.Malloc, Microsoft.Xna.Framework.Graphics.Texture2D.Width, and Microsoft.Xna.Framework.Graphics.FNA3D.WriteJPGStream().