Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT
SetDataPointerEXT()
void Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT (int level, Rectangle? rect, IntPtr data, int dataLength) inline
Definition at line 159 of file Texture2D.cs.
        {
            if (data == IntPtr.Zero)
            {
                throw new ArgumentNullException("data");
            }
            int num;
            int num2;
            int num3;
            int num4;
            if (rect != null)
            {
                num = rect.Value.X;
                num2 = rect.Value.Y;
                num3 = rect.Value.Width;
                num4 = rect.Value.Height;
            }
            else
            {
                num = 0;
                num2 = 0;
                num3 = Math.Max(this.Width >> level, 1);
                num4 = Math.Max(this.Height >> level, 1);
            }
            FNA3D.FNA3D_SetTextureData2D(base.GraphicsDevice.GLDevice, this.texture, num, num2, num3, num4, level, data, dataLength);
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetTextureData2D(), Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Rectangle.Height, System.Math.Max(), Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Rectangle.Y, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), and Microsoft.Xna.Framework.Media.VideoPlayerAV1.UploadDataToTexture().