Terraria Decompiled: System.IO.FileSystem.DirectoryExists
DirectoryExists() [1/2]
static bool System.IO.FileSystem.DirectoryExists (ReadOnlySpan< char > fullPath) inline static
Definition at line 358 of file FileSystem.cs.
        {
            Interop.ErrorInfo errorInfo;
            return FileSystem.DirectoryExists(fullPath, out errorInfo);
        }
References System.IO.FileSystem.DirectoryExists().
Referenced by System.IO.FileSystem.CopyFile(), System.IO.FileSystem.CreateDirectory(), System.IO.FileSystem.DirectoryExists(), System.IO.Directory.Exists(), System.IO.Directory.Move(), and System.IO.DirectoryInfo.MoveTo().