Terraria Decompiled: System.IO.FileSystem.DeleteFile
DeleteFile()
static void System.IO.FileSystem.DeleteFile (string fullPath) inline static
Definition at line 128 of file FileSystem.cs.
        {
            if (Interop.Sys.Unlink(fullPath) < 0)
            {
                Interop.ErrorInfo errorInfo = Interop.Sys.GetLastErrorInfo();
                Interop.Error error = errorInfo.Error;
                if (error != Interop.Error.EISDIR)
                {
                    if (error == Interop.Error.ENOENT)
                    {
                        return;
                    }
                    if (error == Interop.Error.EROFS)
                    {
                        Interop.ErrorInfo errorInfo2;
                        if (!FileSystem.FileExists(PathInternal.TrimEndingDirectorySeparator(fullPath), 32768, out errorInfo2) && errorInfo2.Error == Interop.Error.ENOENT)
{
                            return;
                        }
                    }
                }
                else
                {
                    errorInfo = Interop.Error.EACCES.Info();
                }
                throw Interop.GetExceptionForIoErrno(errorInfo, fullPath, false);
            }
        }
References Interop.ErrorInfo.Error, System.IO.FileSystem.FileExists(), Interop.GetExceptionForIoErrno(), and System.IO.PathInternal.TrimEndingDirectorySeparator().
Referenced by System.IO.FileInfo.Delete(), System.IO.File.Delete(), System.IO.FileSystem.MoveFile(), and System.IO.FileSystem.RemoveDirectoryInternal().