Terraria Decompiled: System.IO.FileSystem.RemoveDirectoryInternal
RemoveDirectoryInternal()
static void System.IO.FileSystem.RemoveDirectoryInternal (DirectoryInfo directory, bool recursive, bool throwOnTopLevelDirectoryNotFound) inline static private
Definition at line 275 of file FileSystem.cs.
        {
            Exception ex = null;
            if ((directory.Attributes & FileAttributes.ReparsePoint) != (FileAttributes)0)
            {
                FileSystem.DeleteFile(directory.FullName);
                return;
            }
            if (recursive)
            {
                try
                {
                    foreach (string text in Directory.EnumerateFileSystemEntries(directory.FullName))
                    {
                        if (!FileSystem.ShouldIgnoreDirectory(Path.GetFileName(text)))
{
                            try
{
                                DirectoryInfo directoryInfo = new DirectoryInfo(text);
                                if (directoryInfo.Exists)
{
                                    FileSystem.RemoveDirectoryInternal(directoryInfo, recursive, false);
                                }
                                else
{
                                    FileSystem.DeleteFile(text);
                                }
                            }
                            catch (Exception ex2)
{
                                if (ex != null)
{
                                    ex = ex2;
                                }
                            }
                        }
                    }
                }
                catch (Exception ex3)
                {
                    if (ex != null)
                    {
                        ex = ex3;
                    }
                }
                if (ex != null)
                {
                    throw ex;
                }
            }
            if (Interop.Sys.RmDir(directory.FullName) < 0)
            {
                Interop.ErrorInfo lastErrorInfo = Interop.Sys.GetLastErrorInfo();
                Interop.Error error = lastErrorInfo.Error;
                if (error <= Interop.Error.EISDIR)
                {
                    if (error != Interop.Error.EACCES && error != Interop.Error.EISDIR)
                    {
                        goto IL_0106;
                    }
                }
                else if (error != Interop.Error.ENOENT)
                {
                    if (error != Interop.Error.EPERM && error != Interop.Error.EROFS)
                    {
                        goto IL_0106;
                    }
                }
                else
                {
                    if (!throwOnTopLevelDirectoryNotFound)
                    {
                        return;
                    }
                    goto IL_0106;
                }
                throw new IOException(SR.Format("Access to the path '{0}' is denied.", directory.FullName));
                IL_0106:
                throw Interop.GetExceptionForIoErrno(lastErrorInfo, directory.FullName, true);
            }
        }
References System.IO.FileSystemInfo.Attributes, System.IO.FileSystem.DeleteFile(), System.IO.Directory.EnumerateFileSystemEntries(), Interop.ErrorInfo.Error, System.IO.FileSystemInfo.Exists, SR.Format(), System.IO.FileSystemInfo.FullName, System.IO.Path.GetFileName(), System.IO.FileSystem.RemoveDirectoryInternal(), System.IO.FileSystem.ShouldIgnoreDirectory(), and System.text.
Referenced by System.IO.FileSystem.RemoveDirectory(), and System.IO.FileSystem.RemoveDirectoryInternal().