Terraria Decompiled: System.IO.FileSystem.LinkOrCopyFile
LinkOrCopyFile()
static void System.IO.FileSystem.LinkOrCopyFile (string sourceFullPath, string destFullPath) inline static private
Definition at line 50 of file FileSystem.cs.
        {
            if (FileSystem.CopyDanglingSymlink(sourceFullPath, destFullPath))
            {
                return;
            }
            if (Interop.Sys.Link(sourceFullPath, destFullPath) >= 0)
            {
                return;
            }
            Interop.ErrorInfo lastErrorInfo = Interop.Sys.GetLastErrorInfo();
            if (lastErrorInfo.Error == Interop.Error.EXDEV || lastErrorInfo.Error == Interop.Error.EACCES || lastErrorInfo.Error == Interop.Error.EPERM || lastErrorInfo.Error == Interop.Error.ENOTSUP || lastErrorInfo.Error == Interop.Error.EMLINK || lastErrorInfo.Error == Interop.Error.ENOSYS)
            {
                FileSystem.CopyFile(sourceFullPath, destFullPath, false);
                return;
            }
            string text = null;
            bool flag = false;
            if (lastErrorInfo.Error == Interop.Error.ENOENT)
            {
                if (!Directory.Exists(Path.GetDirectoryName(destFullPath)))
                {
                    text = destFullPath;
                    flag = true;
                }
                else
                {
                    text = sourceFullPath;
                }
            }
            else if (lastErrorInfo.Error == Interop.Error.EEXIST)
            {
                text = destFullPath;
            }
            throw Interop.GetExceptionForIoErrno(lastErrorInfo, text, flag);
        }
References System.IO.FileSystem.CopyDanglingSymlink(), System.IO.FileSystem.CopyFile(), Interop.ErrorInfo.Error, System.IO.Directory.Exists(), System.IO.Path.GetDirectoryName(), and System.text.
Referenced by System.IO.FileSystem.MoveFile(), and System.IO.FileSystem.ReplaceFile().