Terraria Decompiled: System.IO.FileSystem.CreateDirectory
CreateDirectory()
static void System.IO.FileSystem.CreateDirectory (string fullPath) inline static
Definition at line 158 of file FileSystem.cs.
        {
            int num = fullPath.Length;
            if (num >= 2 && PathInternal.EndsInDirectorySeparator(fullPath))
            {
                num--;
            }
            if (num == 2 && PathInternal.IsDirectorySeparator(fullPath[1]))
            {
                throw new IOException(SR.Format("The specified directory '{0}' cannot be created.", fullPath));
            }
            if (FileSystem.DirectoryExists(fullPath))
            {
                return;
            }
            bool flag = false;
            Stack<string> stack = new Stack<string>();
            int rootLength = PathInternal.GetRootLength(fullPath);
            if (num > rootLength)
            {
                int num2 = num - 1;
                while (num2 >= rootLength && !flag)
                {
                    string text = fullPath.Substring(0, num2 + 1);
                    if (!FileSystem.DirectoryExists(text))
                    {
                        stack.Push(text);
                    }
                    else
                    {
                        flag = true;
                    }
                    while (num2 > rootLength && !PathInternal.IsDirectorySeparator(fullPath[num2]))
                    {
                        num2--;
                    }
                    num2--;
                }
            }
            if (stack.Count == 0 && !flag)
            {
                if (!FileSystem.DirectoryExists(Directory.InternalGetDirectoryRoot(fullPath)))
                {
                    throw Interop.GetExceptionForIoErrno(Interop.Error.ENOENT.Info(), fullPath, true);
                }
                return;
            }
            else
            {
                int num3 = 0;
                Interop.ErrorInfo errorInfo = default(Interop.ErrorInfo);
                string text2 = fullPath;
                while (stack.Count > 0)
                {
                    string text3 = stack.Pop();
                    num3 = Interop.Sys.MkDir(text3, 511);
                    if (num3 < 0 && errorInfo.Error == Interop.Error.SUCCESS)
                    {
                        Interop.ErrorInfo lastErrorInfo = Interop.Sys.GetLastErrorInfo();
                        if (lastErrorInfo.Error != Interop.Error.EEXIST)
{
                            errorInfo = lastErrorInfo;
                        }
                        else if (FileSystem.FileExists(text3) || (!FileSystem.DirectoryExists(text3, out lastErrorInfo) && lastErrorInfo.Error == Interop.Error.EACCES))
{
                            errorInfo = lastErrorInfo;
                            text2 = text3;
                        }
                    }
                }
                if (num3 < 0 && errorInfo.Error != Interop.Error.SUCCESS)
                {
                    throw Interop.GetExceptionForIoErrno(errorInfo, text2, true);
                }
                return;
            }
        }
References System.IO.FileSystem.DirectoryExists(), System.IO.PathInternal.EndsInDirectorySeparator(), Interop.ErrorInfo.Error, System.IO.FileSystem.FileExists(), SR.Format(), System.IO.PathInternal.GetRootLength(), System.IO.Directory.InternalGetDirectoryRoot(), System.IO.PathInternal.IsDirectorySeparator(), System.stack, and System.text.
Referenced by System.IO.DirectoryInfo.Create(), System.IO.DirectoryInfo.Create(), System.IO.Directory.CreateDirectory(), and System.IO.DirectoryInfo.CreateSubdirectory().