Terraria Decompiled: System.IO.FileSystem.MoveDirectory
MoveDirectory()
static void System.IO.FileSystem.MoveDirectory (string sourceFullPath, string destFullPath) inline static
Definition at line 237 of file FileSystem.cs.
        {
            if (FileSystem.FileExists(sourceFullPath))
            {
                if (PathInternal.EndsInDirectorySeparator(sourceFullPath))
                {
                    throw new IOException(SR.Format("Could not find a part of the path '{0}'.", sourceFullPath));
                }
                destFullPath = PathInternal.TrimEndingDirectorySeparator(destFullPath);
                if (FileSystem.FileExists(destFullPath))
                {
                    throw new IOException("Cannot create a file when that file already exists.");
                }
            }
            if (Interop.Sys.Rename(sourceFullPath, destFullPath) >= 0)
            {
                return;
            }
            Interop.ErrorInfo lastErrorInfo = Interop.Sys.GetLastErrorInfo();
            if (lastErrorInfo.Error == Interop.Error.EACCES)
            {
                throw new IOException(SR.Format("Access to the path '{0}' is denied.", sourceFullPath), lastErrorInfo.RawErrno);
            }
            throw Interop.GetExceptionForIoErrno(lastErrorInfo, sourceFullPath, true);
        }
References System.IO.PathInternal.EndsInDirectorySeparator(), Interop.ErrorInfo.Error, System.IO.FileSystem.FileExists(), SR.Format(), Interop.ErrorInfo.RawErrno, and System.IO.PathInternal.TrimEndingDirectorySeparator().
Referenced by System.IO.Directory.Move(), and System.IO.DirectoryInfo.MoveTo().