Terraria Decompiled: System.IO.FileSystem.CopyFile
CopyFile()
static void System.IO.FileSystem.CopyFile (string sourceFullPath, string destFullPath, bool overwrite) inline static
Definition at line 30 of file FileSystem.cs.
        {
            if (FileSystem.DirectoryExists(destFullPath))
            {
                destFullPath = Path.Combine(destFullPath, Path.GetFileName(sourceFullPath));
            }
            if (FileSystem.CopyDanglingSymlink(sourceFullPath, destFullPath))
            {
                return;
            }
            using (FileStream fileStream = new FileStream(sourceFullPath, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, FileOptions.None))
            {
                using (FileStream fileStream2 = new FileStream(destFullPath, overwrite ? FileMode.Create : FileMode.CreateNew, FileAccess.ReadWrite, FileShare.None, 4096, FileOptions.None))
                {
                    Interop.CheckIo(Interop.Sys.CopyFile(fileStream.SafeFileHandle, fileStream2.SafeFileHandle), null, false, null);
                }
            }
        }
References System.IO.Path.Combine(), System.IO.FileSystem.CopyDanglingSymlink(), System.IO.FileSystem.DirectoryExists(), System.IO.Path.GetFileName(), and System.IO.FileStream.SafeFileHandle.
Referenced by System.IO.File.Copy(), System.IO.FileInfo.CopyTo(), and System.IO.FileSystem.LinkOrCopyFile().