Terraria Decompiled: System.Globalization.TimeSpanParse.ParseExactMultiple
ParseExactMultiple()
static TimeSpan System.Globalization.TimeSpanParse.ParseExactMultiple (ReadOnlySpan< char > input, string[] formats, IFormatProvider formatProvider, TimeSpanStyles styles) inline static package
Definition at line 115 of file TimeSpanParse.cs.
        {
            TimeSpanParse.TimeSpanResult timeSpanResult = new TimeSpanParse.TimeSpanResult(true);
            TimeSpanParse.TryParseExactMultipleTimeSpan(input, formats, formatProvider, styles, ref timeSpanResult);
            return timeSpanResult.parsedTimeSpan;
        }
References System.input, System.Globalization.TimeSpanParse.TimeSpanResult.parsedTimeSpan, and System.Globalization.TimeSpanParse.TryParseExactMultipleTimeSpan().
Referenced by System.TimeSpan.ParseExact(), System.TimeSpan.ParseExact(), and System.TimeSpan.ParseExact().