Terraria Decompiled: System.Globalization.TimeSpanParse.Pow10
Pow10()
static long System.Globalization.TimeSpanParse.Pow10 (int pow) inline static package
Definition at line 10 of file TimeSpanParse.cs.
        {
            switch (pow)
            {
            case 0:
                return 1L;
            case 1:
                return 10L;
            case 2:
                return 100L;
            case 3:
                return 1000L;
            case 4:
                return 10000L;
            case 5:
                return 100000L;
            case 6:
                return 1000000L;
            case 7:
                return 10000000L;
            default:
                return (long)Math.Pow(10.0, (double)pow);
            }
        }
References System.L, and System.Math.Pow().
Referenced by System.Globalization.TimeSpanFormat.FormatCustomized(), System.Globalization.TimeSpanFormat.FormatStandard(), System.Globalization.TimeSpanParse.TimeSpanToken.IsInvalidFraction(), System.DateTimeParse.ParseFractionExact(), and System.Globalization.TimeSpanParse.TryTimeToTicks().