Terraria Decompiled: System.Globalization.TimeSpanParse.TryParseExactMultipleTimeSpan
TryParseExactMultipleTimeSpan()
static bool System.Globalization.TimeSpanParse.TryParseExactMultipleTimeSpan (ReadOnlySpan< char > input, string[] formats, IFormatProvider formatProvider, TimeSpanStyles styles, ref TimeSpanParse::TimeSpanResult result) inline static private
Definition at line 843 of file TimeSpanParse.cs.
        {
            if (formats == null)
            {
                return result.SetFailure(TimeSpanParse.ParseFailureKind.ArgumentNull, "String reference not set to an instance of a String.", null, "formats");
            }
            if (input.Length == 0)
            {
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
            }
            if (formats.Length == 0)
            {
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Format specifier was invalid.", null, null);
            }
            for (int i = 0; i < formats.Length; i++)
            {
                if (formats[i] == null || formats[i].Length == 0)
                {
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Format specifier was invalid.", null, null);
                }
                TimeSpanParse.TimeSpanResult timeSpanResult = new TimeSpanParse.TimeSpanResult(false);
                if (TimeSpanParse.TryParseExactTimeSpan(input, formats[i], formatProvider, styles, ref timeSpanResult))
                {
                    result.parsedTimeSpan = timeSpanResult.parsedTimeSpan;
                    return true;
                }
            }
            return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
        }
References System.input, System.Globalization.TimeSpanParse.TimeSpanResult.parsedTimeSpan, and System.Globalization.TimeSpanParse.TryParseExactTimeSpan().
Referenced by System.Globalization.TimeSpanParse.ParseExactMultiple(), and System.Globalization.TimeSpanParse.TryParseExactMultiple().