Terraria Decompiled: System.Globalization.TimeSpanParse.ProcessTerminalState
ProcessTerminalState()
static bool System.Globalization.TimeSpanParse.ProcessTerminalState (ref TimeSpanParse::TimeSpanRawInfo raw, TimeSpanParse::TimeSpanStandardStyles style, ref TimeSpanParse::TimeSpanResult result) inline static private
Definition at line 159 of file TimeSpanParse.cs.
        {
            if (raw._lastSeenTTT == TimeSpanParse.TTT.Num)
            {
                TimeSpanParse.TimeSpanToken timeSpanToken = default(TimeSpanParse.TimeSpanToken);
                timeSpanToken._ttt = TimeSpanParse.TTT.Sep;
                if (!raw.ProcessToken(ref timeSpanToken, ref result))
                {
                    return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
                }
            }
            switch (raw._numCount)
            {
            case 1:
                return TimeSpanParse.ProcessTerminal_D(ref raw, style, ref result);
            case 2:
                return TimeSpanParse.ProcessTerminal_HM(ref raw, style, ref result);
            case 3:
                return TimeSpanParse.ProcessTerminal_HM_S_D(ref raw, style, ref result);
            case 4:
                return TimeSpanParse.ProcessTerminal_HMS_F_D(ref raw, style, ref result);
            case 5:
                return TimeSpanParse.ProcessTerminal_DHMSF(ref raw, style, ref result);
            default:
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
            }
        }
References System.Globalization.TimeSpanParse.ProcessTerminal_D(), System.Globalization.TimeSpanParse.ProcessTerminal_DHMSF(), System.Globalization.TimeSpanParse.ProcessTerminal_HM(), System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(), and System.Globalization.TimeSpanParse.ProcessTerminal_HMS_F_D().
Referenced by System.Globalization.TimeSpanParse.TryParseTimeSpan().