Terraria Decompiled: System.Globalization.TimeSpanParse.TryParseByFormat
TryParseByFormat()
static unsafe bool System.Globalization.TimeSpanParse.TryParseByFormat (ReadOnlySpan< char > input, ReadOnlySpan< char > format, TimeSpanStyles styles, ref TimeSpanParse::TimeSpanResult result) inline static private
Definition at line 627 of file TimeSpanParse.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            int num4 = 0;
            int num5 = 0;
            int num6 = 0;
            int i = 0;
            int num7 = 0;
            TimeSpanParse.TimeSpanTokenizer timeSpanTokenizer = new TimeSpanParse.TimeSpanTokenizer(input, -1);
            while (i < format.Length)
            {
                char c = (char)(*format[i]);
                if (c <= 'F')
                {
                    if (c <= '%')
                    {
                        if (c != '"')
{
                            if (c != '%')
{
                                goto IL_02E1;
                            }
                            int num8 = DateTimeFormat.ParseNextChar(format, i);
                            if (num8 >= 0 && num8 != 37)
{
                                num7 = 1;
                                goto IL_02F0;
                            }
                            return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                        }
                    }
                    else if (c != '\'')
                    {
                        if (c != 'F')
{
                            goto IL_02E1;
                        }
                        num7 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                        if (num7 > 7 || flag5)
{
                            return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                        }
                        TimeSpanParse.ParseExactDigits(ref timeSpanTokenizer, num7, num7, out num5, out num6);
                        flag5 = true;
                        goto IL_02F0;
                    }
                    StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
                    if (!DateTimeParse.TryParseQuoteString(format, i, stringBuilder, out num7))
                    {
                        StringBuilderCache.Release(stringBuilder);
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.FormatWithParameter, "Cannot find a matching quote character for the character '{0}'.", c, null);
                    }
                    if (!TimeSpanParse.ParseExactLiteral(ref timeSpanTokenizer, stringBuilder))
                    {
                        StringBuilderCache.Release(stringBuilder);
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                    }
                    StringBuilderCache.Release(stringBuilder);
                }
                else if (c <= 'h')
                {
                    if (c != '\\')
                    {
                        switch (c)
{
                        case 'd':
{
                            num7 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            int num9 = 0;
                            if (num7 > 8 || flag || !TimeSpanParse.ParseExactDigits(ref timeSpanTokenizer, (num7 < 2) ? 1 : num7, (num7 < 2) ? 8 : num7, out num9, out num))
{
                                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                            }
                            flag = true;
                            break;
                        }
                        case 'e':
                        case 'g':
                            goto IL_02E1;
                        case 'f':
                            num7 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            if (num7 > 7 || flag5 || !TimeSpanParse.ParseExactDigits(ref timeSpanTokenizer, num7, num7, out num5, out num6))
{
                                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                            }
                            flag5 = true;
                            break;
                        case 'h':
                            num7 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            if (num7 > 2 || flag2 || !TimeSpanParse.ParseExactDigits(ref timeSpanTokenizer, num7, out num2))
{
                                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                            }
                            flag2 = true;
                            break;
                        default:
                            goto IL_02E1;
                        }
                    }
                    else
                    {
                        int num8 = DateTimeFormat.ParseNextChar(format, i);
                        if (num8 < 0 || timeSpanTokenizer.NextChar != (char)num8)
{
                            return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                        }
                        num7 = 2;
                    }
                }
                else if (c != 'm')
                {
                    if (c != 's')
                    {
                        goto IL_02E1;
                    }
                    num7 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                    if (num7 > 2 || flag4 || !TimeSpanParse.ParseExactDigits(ref timeSpanTokenizer, num7, out num4))
                    {
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                    }
                    flag4 = true;
                }
                else
                {
                    num7 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                    if (num7 > 2 || flag3 || !TimeSpanParse.ParseExactDigits(ref timeSpanTokenizer, num7, out num3))
                    {
                        return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
                    }
                    flag3 = true;
                }
                IL_02F0:
                i += num7;
                continue;
                IL_02E1:
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Input string was not in a correct format.", null, null);
            }
            if (!timeSpanTokenizer.EOL)
            {
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "String was not recognized as a valid TimeSpan.", null, null);
            }
            bool flag6 = (styles & TimeSpanStyles.AssumeNegative) == TimeSpanStyles.None;
            long num10;
            if (TimeSpanParse.TryTimeToTicks(flag6, new TimeSpanParse.TimeSpanToken(num), new TimeSpanParse.TimeSpanToken(num2), new TimeSpanParse.TimeSpanToken(num3), new TimeSpanParse.TimeSpanToken(num4), new TimeSpanParse.TimeSpanToken(num6, num5), out num10))
            {
                if (!flag6)
                {
                    num10 = -num10;
                }
                result.parsedTimeSpan = new TimeSpan(num10);
                return true;
            }
            return result.SetFailure(TimeSpanParse.ParseFailureKind.Overflow, "The TimeSpan could not be parsed because at least one of the numeric components is out of range or contains too many digits.", null, null);
        }
References System.Text.StringBuilderCache.Acquire(), System.Globalization.TimeSpanParse.TimeSpanTokenizer.EOL, System.format, System.input, System.Globalization.TimeSpanParse.TimeSpanTokenizer.NextChar, System.Globalization.TimeSpanParse.ParseExactDigits(), System.Globalization.TimeSpanParse.ParseExactLiteral(), System.DateTimeFormat.ParseNextChar(), System.DateTimeFormat.ParseRepeatPattern(), System.Text.StringBuilderCache.Release(), System.DateTimeParse.TryParseQuoteString(), and System.Globalization.TimeSpanParse.TryTimeToTicks().
Referenced by System.Globalization.TimeSpanParse.TryParseExactTimeSpan().