Terraria Decompiled: System.Globalization.TimeSpanParse.TryTimeToTicks
TryTimeToTicks()
static bool System.Globalization.TimeSpanParse.TryTimeToTicks (bool positive, TimeSpanParse::TimeSpanToken days, TimeSpanParse::TimeSpanToken hours, TimeSpanParse::TimeSpanToken minutes, TimeSpanParse::TimeSpanToken seconds, TimeSpanParse::TimeSpanToken fraction, out long result) inline static private
Definition at line 36 of file TimeSpanParse.cs.
        {
            if (days._num > 10675199 || hours._num > 23 || minutes._num > 59 || seconds._num > 59 || fraction.IsInvalidFraction())
            {
                result = 0L;
                return false;
            }
            long num = ((long)days._num * 3600L * 24L + (long)hours._num * 3600L + (long)minutes._num * 60L + (long)seconds._num) * 1000L;
            if (num > 922337203685477L || num < -922337203685477L)
            {
                result = 0L;
                return false;
            }
            long num2 = (long)fraction._num;
            if (num2 != 0L)
            {
                long num3 = 1000000L;
                if (fraction._zeroes > 0)
                {
                    long num4 = TimeSpanParse.Pow10(fraction._zeroes);
                    num3 /= num4;
                }
                while (num2 < num3)
                {
                    num2 *= 10L;
                }
            }
            result = num * 10000L + num2;
            if (positive && result < 0L)
            {
                result = 0L;
                return false;
            }
            return true;
        }
References System.L, long, and System.Globalization.TimeSpanParse.Pow10().
Referenced by System.Globalization.TimeSpanParse.ProcessTerminal_D(), System.Globalization.TimeSpanParse.ProcessTerminal_DHMSF(), System.Globalization.TimeSpanParse.ProcessTerminal_HM(), System.Globalization.TimeSpanParse.ProcessTerminal_HM_S_D(), System.Globalization.TimeSpanParse.ProcessTerminal_HMS_F_D(), and System.Globalization.TimeSpanParse.TryParseByFormat().