Terraria Decompiled: System.Globalization.TimeSpanParse.TryParseExactTimeSpan
TryParseExactTimeSpan()
static unsafe bool System.Globalization.TimeSpanParse.TryParseExactTimeSpan (ReadOnlySpan< char > input, ReadOnlySpan< char > format, IFormatProvider formatProvider, TimeSpanStyles styles, ref TimeSpanParse::TimeSpanResult result) inline static private
Definition at line 588 of file TimeSpanParse.cs.
        {
            if (format.Length == 0)
            {
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Format specifier was invalid.", null, null);
            }
            if (format.Length == 1)
            {
                char c = (char)(*format[0]);
                if (c <= 'T')
                {
                    if (c == 'G')
                    {
                        return TimeSpanParse.TryParseTimeSpan(input, TimeSpanParse.TimeSpanStandardStyles.Localized | TimeSpanParse.TimeSpanStandardStyles.RequireFull, formatProvider, ref result);
                    }
                    if (c != 'T')
                    {
                        goto IL_006C;
                    }
                }
                else if (c != 'c')
                {
                    if (c == 'g')
                    {
                        return TimeSpanParse.TryParseTimeSpan(input, TimeSpanParse.TimeSpanStandardStyles.Localized, formatProvider, ref result);
                    }
                    if (c != 't')
                    {
                        goto IL_006C;
                    }
                }
                return TimeSpanParse.TryParseTimeSpanConstant(input, ref result);
                IL_006C:
                return result.SetFailure(TimeSpanParse.ParseFailureKind.Format, "Format specifier was invalid.", null, null);
            }
            return TimeSpanParse.TryParseByFormat(input, format, styles, ref result);
        }
References System.format, System.input, System.Globalization.TimeSpanParse.TryParseByFormat(), System.Globalization.TimeSpanParse.TryParseTimeSpan(), and System.Globalization.TimeSpanParse.TryParseTimeSpanConstant().
Referenced by System.Globalization.TimeSpanParse.ParseExact(), System.Globalization.TimeSpanParse.TryParseExact(), and System.Globalization.TimeSpanParse.TryParseExactMultipleTimeSpan().