Terraria Decompiled: Mono.Globalization.Unicode.MSCompatUnicodeTable.FillCJKCore
FillCJKCore()
static unsafe void Mono.Globalization.Unicode.MSCompatUnicodeTable.FillCJKCore (string culture, ref CodePointIndexer cjkIndexer, ref byte * catTable, ref byte * lv1Table, ref CodePointIndexer cjkLv2Indexer, ref byte * lv2Table) inline static private
Definition at line 617 of file MSCompatUnicodeTable.cs.
        {
            if (!MSCompatUnicodeTable.IsReady)
            {
                return;
            }
            string text = null;
            if (!(culture == "zh-CHS"))
            {
                if (!(culture == "zh-CHT"))
                {
                    if (!(culture == "ja"))
                    {
                        if (culture == "ko")
{
                            text = "cjkKO";
                            catTable = MSCompatUnicodeTable.cjkKOcategory;
                            lv1Table = MSCompatUnicodeTable.cjkKOlv1;
                        }
                    }
                    else
                    {
                        text = "cjkJA";
                        catTable = MSCompatUnicodeTable.cjkJAcategory;
                        lv1Table = MSCompatUnicodeTable.cjkJAlv1;
                    }
                }
                else
                {
                    text = "cjkCHT";
                    catTable = MSCompatUnicodeTable.cjkCHTcategory;
                    lv1Table = MSCompatUnicodeTable.cjkCHTlv1;
                }
            }
            else
            {
                text = "cjkCHS";
                catTable = MSCompatUnicodeTable.cjkCHScategory;
                lv1Table = MSCompatUnicodeTable.cjkCHSlv1;
            }
            if (text == null || lv1Table != (IntPtr)((UIntPtr)0))
            {
                return;
            }
            uint num = 0U;
            IntPtr intPtr = MSCompatUnicodeTable.GetResource(string.Format("collation.{0}.bin", text));
            if (intPtr == IntPtr.Zero)
            {
                return;
            }
            byte* ptr = (byte*)(void*)intPtr;
            num += 1U;
            uint num2 = MSCompatUnicodeTable.UInt32FromBytePtr(ptr, num);
            num += 4U;
            catTable = ptr + num;
            lv1Table = ptr + num + num2;
            if (!(culture == "zh-CHS"))
            {
                if (!(culture == "zh-CHT"))
                {
                    if (!(culture == "ja"))
                    {
                        if (culture == "ko")
{
                            MSCompatUnicodeTable.cjkKOcategory = catTable;
                            MSCompatUnicodeTable.cjkKOlv1 = lv1Table;
                        }
                    }
                    else
                    {
                        MSCompatUnicodeTable.cjkJAcategory = catTable;
                        MSCompatUnicodeTable.cjkJAlv1 = lv1Table;
                    }
                }
                else
                {
                    MSCompatUnicodeTable.cjkCHTcategory = catTable;
                    MSCompatUnicodeTable.cjkCHTlv1 = lv1Table;
                }
            }
            else
            {
                MSCompatUnicodeTable.cjkCHScategory = catTable;
                MSCompatUnicodeTable.cjkCHSlv1 = lv1Table;
            }
            if (text != "cjkKO")
            {
                return;
            }
            intPtr = MSCompatUnicodeTable.GetResource("collation.cjkKOlv2.bin");
            if (intPtr == IntPtr.Zero)
            {
                return;
            }
            ptr = (byte*)(void*)intPtr;
            num = 5U;
            MSCompatUnicodeTable.cjkKOlv2 = ptr + num;
            lv2Table = MSCompatUnicodeTable.cjkKOlv2;
        }
References Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkCHScategory, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkCHSlv1, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkCHTcategory, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkCHTlv1, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkJAcategory, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkJAlv1, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkKOcategory, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkKOlv1, Mono.Globalization.Unicode.MSCompatUnicodeTable.cjkKOlv2, System.culture, System.Globalization.Format, Mono.Globalization.Unicode.MSCompatUnicodeTable.GetResource(), Mono.Globalization.Unicode.MSCompatUnicodeTable.IsReady, System.text, System.U, Mono.Globalization.Unicode.MSCompatUnicodeTable.UInt32FromBytePtr(), and System.IntPtr.Zero.
Referenced by Mono.Globalization.Unicode.MSCompatUnicodeTable.FillCJK().