Terraria Decompiled: Mono.Globalization.Unicode.MSCompatUnicodeTable.IsJapaneseSmallLetter
IsJapaneseSmallLetter()
static bool Mono.Globalization.Unicode.MSCompatUnicodeTable.IsJapaneseSmallLetter (char c) inline static
Definition at line 411 of file MSCompatUnicodeTable.cs.
        {
            if ('ｧ' <= c && c <= 'ｯ')
            {
                return true;
            }
            if ('\u3040' < c && c < 'ヺ')
            {
                if (c <= 'ォ')
                {
                    if (c <= 'っ')
                    {
                        switch (c)
{
                        case 'ぁ':
                        case 'ぃ':
                        case 'ぅ':
                        case 'ぇ':
                        case 'ぉ':
                            break;
                        case 'あ':
                        case 'い':
                        case 'う':
                        case 'え':
                            return false;
                        default:
                            if (c != 'っ')
{
                                return false;
                            }
                            break;
                        }
                    }
                    else
                    {
                        switch (c)
{
                        case 'ゃ':
                        case 'ゅ':
                        case 'ょ':
                            break;
                        case 'や':
                        case 'ゆ':
                            return false;
                        default:
                            if (c != 'ゎ')
{
                                switch (c)
{
                                case 'ァ':
                                case 'ィ':
                                case 'ゥ':
                                case 'ェ':
                                case 'ォ':
                                    break;
                                case 'ア':
                                case 'イ':
                                case 'ウ':
                                case 'エ':
                                    return false;
                                default:
                                    return false;
                                }
                            }
                            break;
                        }
                    }
                }
                else if (c <= 'ョ')
                {
                    if (c != 'ッ')
                    {
                        switch (c)
{
                        case 'ャ':
                        case 'ュ':
                        case 'ョ':
                            break;
                        case 'ヤ':
                        case 'ユ':
                            return false;
                        default:
                            return false;
                        }
                    }
                }
                else if (c != 'ヮ' && c != 'ヵ' && c != 'ヶ')
                {
                    return false;
                }
                return true;
            }
            return false;
        }
Referenced by Mono.Globalization.Unicode.SimpleCollator.CompareInternal(), Mono.Globalization.Unicode.SimpleCollator.FillSortKeyRaw(), and Mono.Globalization.Unicode.SimpleCollator.MatchesPrimitive().