Terraria Decompiled: Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables
BuildTailoringTables()
static unsafe void Mono.Globalization.Unicode.MSCompatUnicodeTable.BuildTailoringTables (CultureInfo culture, TailoringInfo t, ref Contraction[] contractions, ref Level2Map[] diacriticals) inline static
Definition at line 27 of file MSCompatUnicodeTable.cs.
        {
            List<Contraction> list = new List<Contraction>();
            List<Level2Map> list2 = new List<Level2Map>();
            int num = 0;
            char[] array;
            char* ptr;
            if ((array = MSCompatUnicodeTable.tailoringArr) == null || array.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &array[0];
            }
            int i = t.TailoringIndex;
            int num2 = i + t.TailoringCount;
            while (i < num2)
            {
                int num3 = i + 1;
                switch (ptr[i])
                {
                case '\u0001':
                {
                    i++;
                    while (ptr[num3] != '\0')
                    {
                        num3++;
                    }
                    char[] array2 = new char[num3 - i];
                    Marshal.Copy((IntPtr)((void*)(ptr + i)), array2, 0, num3 - i);
                    byte[] array3 = new byte[4];
                    for (int j = 0; j < 4; j++)
                    {
                        array3[j] = (byte)ptr[num3 + 1 + j];
                    }
                    list.Add(new Contraction(num, array2, null, array3));
                    i = num3 + 6;
                    num++;
                    break;
                }
                case '\u0002':
                    list2.Add(new Level2Map((byte)ptr[i + 1], (byte)ptr[i + 2]));
                    i += 3;
                    break;
                case '\u0003':
                {
                    i++;
                    while (ptr[num3] != '\0')
                    {
                        num3++;
                    }
                    char[] array2 = new char[num3 - i];
                    Marshal.Copy((IntPtr)((void*)(ptr + i)), array2, 0, num3 - i);
                    num3++;
                    int num4 = num3;
                    while (ptr[num4] != '\0')
                    {
                        num4++;
                    }
                    string text = new string(ptr, num3, num4 - num3);
                    list.Add(new Contraction(num, array2, text, null));
                    i = num4 + 1;
                    num++;
                    break;
                }
                default:
                    throw new NotImplementedException(string.Format("Mono INTERNAL ERROR (Should not happen): Collation tailoring table is broken for culture {0} ({1}) at 0x{2:X}", culture.LCID, culture.Name, i));
                }
            }
            array = null;
            list.Sort(ContractionComparer.Instance);
            list2.Sort((Level2Map a, Level2Map b) => (int)(a.Source - b.Source));
            contractions = list.ToArray();
            diacriticals = list2.ToArray();
        }
References System.Collections.Generic.List< T >.Add(), System.array, System.Runtime.InteropServices.Marshal.Copy(), System.culture, System.Globalization.Format, Mono.Globalization.Unicode.ContractionComparer.Instance, System.list, System.Collections.Generic.List< T >.Sort(), Mono.Globalization.Unicode.Level2Map.Source, Mono.Globalization.Unicode.MSCompatUnicodeTable.tailoringArr, Mono.Globalization.Unicode.TailoringInfo.TailoringCount, Mono.Globalization.Unicode.TailoringInfo.TailoringIndex, System.text, and System.Collections.Generic.List< T >.ToArray().
Referenced by Mono.Globalization.Unicode.SimpleCollator.SimpleCollator().