Terraria Decompiled: Microsoft.Xna.Framework.Graphics.EffectParameter.BuildElementList
BuildElementList()
void Microsoft.Xna.Framework.Graphics.EffectParameter.BuildElementList () inline package
Definition at line 207 of file EffectParameter.cs.
        {
            int num = 0;
            List<EffectParameter> list = new List<EffectParameter>(this.elementCount);
            EffectParameterCollection structureMembers = this.StructureMembers;
            for (int i = 0; i < this.elementCount; i++)
            {
                EffectParameterCollection effectParameterCollection = null;
                if (structureMembers != null)
                {
                    List<EffectParameter> list2 = new List<EffectParameter>();
                    for (int j = 0; j < structureMembers.Count; j++)
                    {
                        int num2 = 0;
                        if (structureMembers[j].Elements != null)
{
                            num2 = structureMembers[j].Elements.Count;
                        }
                        int num3 = structureMembers[j].RowCount * 4;
                        if (num2 > 0)
{
                            num3 *= num2;
                        }
                        list2.Add(new EffectParameter(structureMembers[j].Name, structureMembers[j].Semantic, structureMembers[j].RowCount, structureMembers[j].ColumnCount, num2, structureMembers[j].ParameterClass, structureMembers[j].ParameterType, IntPtr.Zero, structureMembers[j].Annotations, new IntPtr(this.values.ToInt64() + (long)num), (uint)(num3 * 4), this.outer));
                        num += num3 * 4;
                    }
                    effectParameterCollection = new EffectParameterCollection(list2);
                }
                list.Add(new EffectParameter(null, null, this.RowCount, this.ColumnCount, 0, this.ParameterClass, this.ParameterType, effectParameterCollection, null, new IntPtr(this.values.ToInt64() + (long)(i * this.RowCount * 16)), 0U, this.outer));
            }
            this.elements = new EffectParameterCollection(list);
        }
References System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Graphics.EffectParameter.ColumnCount, Microsoft.Xna.Framework.Graphics.EffectParameterCollection.Count, Microsoft.Xna.Framework.Graphics.EffectParameter.EffectParameter(), Microsoft.Xna.Framework.Graphics.EffectParameter.elementCount, System.list, Microsoft.Xna.Framework.Graphics.EffectParameter.Name, Microsoft.Xna.Framework.Graphics.EffectParameter.ParameterClass, Microsoft.Xna.Framework.Graphics.EffectParameter.ParameterType, Microsoft.Xna.Framework.Graphics.EffectParameter.RowCount, Microsoft.Xna.Framework.Graphics.EffectParameter.Semantic, Microsoft.Xna.Framework.Graphics.EffectParameter.StructureMembers, System.IntPtr.ToInt64(), System.U, Microsoft.Xna.Framework.Graphics.EffectParameter.values, and System.IntPtr.Zero.