Terraria Decompiled: System.Threading.CancellationTokenSource.ExecuteCallbackHandlers
ExecuteCallbackHandlers()
void System.Threading.CancellationTokenSource.ExecuteCallbackHandlers (bool throwOnFirstException) inline private
Definition at line 326 of file CancellationTokenSource.cs.
        {
            LowLevelListWithIList<Exception> lowLevelListWithIList = null;
            SparselyPopulatedArray<CancellationCallbackInfo>[] registeredCallbacksLists = this._registeredCallbacksLists;
            if (registeredCallbacksLists == null)
            {
                Interlocked.Exchange(ref this._state, 3);
                return;
            }
            try
            {
                for (int i = 0; i < registeredCallbacksLists.Length; i++)
                {
                    SparselyPopulatedArray<CancellationCallbackInfo> sparselyPopulatedArray = Volatile.Read<SparselyPopulatedArray<CancellationCallbackInfo>>(ref registeredCallbacksLists[i]);
                    if (sparselyPopulatedArray != null)
                    {
                        for (SparselyPopulatedArrayFragment<CancellationCallbackInfo> sparselyPopulatedArrayFragment = sparselyPopulatedArray.Tail; sparselyPopulatedArrayFragment != null; sparselyPopulatedArrayFragment = sparselyPopulatedArrayFragment.Prev)
{
                            for (int j = sparselyPopulatedArrayFragment.Length - 1; j >= 0; j--)
{
                                this._executingCallback = sparselyPopulatedArrayFragment[j];
                                if (this._executingCallback != null)
{
                                    CancellationCallbackCoreWorkArguments cancellationCallbackCoreWorkArguments = new CancellationCallbackCoreWorkArguments(sparselyPopulatedArrayFragment, j);
                                    try
{
                                        CancellationCallbackInfo.WithSyncContext withSyncContext = this._executingCallback as CancellationCallbackInfo.WithSyncContext;
                                        if (withSyncContext != null)
{
                                            withSyncContext.TargetSyncContext.Send(new SendOrPostCallback(this.CancellationCallbackCoreWork_OnSyncContext), cancellationCallbackCoreWorkArguments);
                                            this.ThreadIDExecutingCallbacks = Environment.CurrentManagedThreadId;
                                        }
                                        else
{
                                            this.CancellationCallbackCoreWork(cancellationCallbackCoreWorkArguments);
                                        }
                                    }
                                    catch (Exception ex)
{
                                        if (throwOnFirstException)
{
                                            throw;
                                        }
                                        if (lowLevelListWithIList == null)
{
                                            lowLevelListWithIList = new LowLevelListWithIList<Exception>();
                                        }
                                        lowLevelListWithIList.Add(ex);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            finally
            {
                this._state = 3;
                this._executingCallback = null;
                Interlocked.MemoryBarrier();
            }
            if (lowLevelListWithIList != null)
            {
                throw new AggregateException(lowLevelListWithIList);
            }
        }
References System.Threading.CancellationTokenSource._executingCallback, System.Threading.CancellationTokenSource._registeredCallbacksLists, System.Threading.CancellationTokenSource._state, System.Collections.Generic.LowLevelList< T >.Add(), System.Threading.CancellationTokenSource.CancellationCallbackCoreWork(), System.Threading.CancellationTokenSource.CancellationCallbackCoreWork_OnSyncContext(), System.Threading.Interlocked.Exchange(), System.Threading.Interlocked.MemoryBarrier(), System.Threading.Volatile.Read(), System.Threading.SynchronizationContext.Send(), System.Threading.SendOrPostCallback(), System.Threading.SparselyPopulatedArray< T >.Tail, and System.Threading.CancellationCallbackInfo.WithSyncContext.TargetSyncContext.
Referenced by System.Threading.CancellationTokenSource.NotifyCancellation().