Terraria Decompiled: System.Runtime.CompilerServices.ContractHelper.TriggerFailureImplementation
TriggerFailureImplementation()
static void System.Runtime.CompilerServices.ContractHelper.TriggerFailureImplementation (ContractFailureKind kind, string displayMessage, string userMessage, string conditionText, Exception innerException) inline static private
Definition at line 93 of file ContractHelper.cs.
        {
            if (Environment.IsCLRHosted)
            {
                ContractHelper.TriggerCodeContractEscalationPolicy(kind, displayMessage, conditionText, innerException);
                throw new ContractException(kind, displayMessage, userMessage, conditionText, innerException);
            }
            if (!Environment.UserInteractive)
            {
                throw new ContractException(kind, displayMessage, userMessage, conditionText, innerException);
            }
            string resourceString = Environment.GetResourceString(ContractHelper.GetResourceNameForFailure(kind, false));
            Assert.Fail(conditionText, displayMessage, resourceString, -2146233022, StackTrace.TraceFormat.Normal, 2);
        }
References System.Diagnostics.Assert.Fail(), System.Runtime.CompilerServices.ContractHelper.GetResourceNameForFailure(), System.Environment.GetResourceString(), and System.Runtime.CompilerServices.ContractHelper.TriggerCodeContractEscalationPolicy().
Referenced by System.Runtime.CompilerServices.ContractHelper.TriggerFailure().