Terraria Decompiled: System.Runtime.CompilerServices.ContractHelper.GetDisplayMessage
GetDisplayMessage()
static string System.Runtime.CompilerServices.ContractHelper.GetDisplayMessage (ContractFailureKind failureKind, string userMessage, string conditionText) inline static private
Definition at line 168 of file ContractHelper.cs.
        {
            string resourceNameForFailure = ContractHelper.GetResourceNameForFailure(failureKind, !string.IsNullOrEmpty(conditionText));
            string text;
            if (!string.IsNullOrEmpty(conditionText))
            {
                text = Environment.GetResourceString(resourceNameForFailure, new object[] { conditionText });
            }
            else
            {
                text = Environment.GetResourceString(resourceNameForFailure);
            }
            if (!string.IsNullOrEmpty(userMessage))
            {
                return text + "  " + userMessage;
            }
            return text;
        }
References System.Runtime.CompilerServices.ContractHelper.GetResourceNameForFailure(), System.Environment.GetResourceString(), and System.text.
Referenced by System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEventImplementation().