Terraria Decompiled: System.Threading.CancellationTokenSource.CancelAfter
CancelAfter() [1/2]
void System.Threading.CancellationTokenSource.CancelAfter (int millisecondsDelay) inline
Definition at line 169 of file CancellationTokenSource.cs.
        {
            this.ThrowIfDisposed();
            if (millisecondsDelay < -1)
            {
                throw new ArgumentOutOfRangeException("millisecondsDelay");
            }
            if (this.IsCancellationRequested)
            {
                return;
            }
            if (this._timer == null)
            {
                Timer timer = new Timer(CancellationTokenSource.s_timerCallback, this, -1, -1);
                if (Interlocked.CompareExchange<Timer>(ref this._timer, timer, null) != null)
                {
                    timer.Dispose();
                }
            }
            try
            {
                this._timer.Change(millisecondsDelay, -1);
            }
            catch (ObjectDisposedException)
            {
            }
        }
References System.Threading.CancellationTokenSource._timer, System.Threading.Timer.Change(), System.Threading.Interlocked.CompareExchange(), System.Threading.Timer.Dispose(), System.Threading.CancellationTokenSource.IsCancellationRequested, System.Threading.CancellationTokenSource.s_timerCallback, and System.Threading.CancellationTokenSource.ThrowIfDisposed().