Terraria Decompiled: System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEventImplementation
RaiseContractFailedEventImplementation()
static void System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEventImplementation (ContractFailureKind failureKind, string userMessage, string conditionText, Exception innerException, ref string resultFailureMessage) inline static private
Definition at line 33 of file ContractHelper.cs.
        {
            if (failureKind < ContractFailureKind.Precondition || failureKind > ContractFailureKind.Assume)
            {
                throw new ArgumentException(Environment.GetResourceString("Illegal enum value: {0}.", new object[] { failureKind }), "failureKind");
            }
            string text = "contract failed.";
            ContractFailedEventArgs contractFailedEventArgs = null;
            RuntimeHelpers.PrepareConstrainedRegions();
            string text2;
            try
            {
                text = ContractHelper.GetDisplayMessage(failureKind, userMessage, conditionText);
                EventHandler<ContractFailedEventArgs> eventHandler = ContractHelper.contractFailedEvent;
                if (eventHandler != null)
                {
                    contractFailedEventArgs = new ContractFailedEventArgs(failureKind, text, conditionText, innerException);
                    foreach (EventHandler<ContractFailedEventArgs> eventHandler2 in eventHandler.GetInvocationList())
                    {
                        try
{
                            eventHandler2(null, contractFailedEventArgs);
                        }
                        catch (Exception ex)
{
                            contractFailedEventArgs.thrownDuringHandler = ex;
                            contractFailedEventArgs.SetUnwind();
                        }
                    }
                    if (contractFailedEventArgs.Unwind)
                    {
                        if (Environment.IsCLRHosted)
{
                            ContractHelper.TriggerCodeContractEscalationPolicy(failureKind, text, conditionText, innerException);
                        }
                        if (innerException == null)
{
                            innerException = contractFailedEventArgs.thrownDuringHandler;
                        }
                        throw new ContractException(failureKind, text, userMessage, conditionText, innerException);
                    }
                }
            }
            finally
            {
                if (contractFailedEventArgs != null && contractFailedEventArgs.Handled)
                {
                    text2 = null;
                }
                else
                {
                    text2 = text;
                }
            }
            resultFailureMessage = text2;
        }
References System.Runtime.CompilerServices.ContractHelper.contractFailedEvent, System.Runtime.CompilerServices.ContractHelper.GetDisplayMessage(), System.Environment.GetResourceString(), System.Diagnostics.Contracts.ContractFailedEventArgs.Handled, System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Diagnostics.Contracts.ContractFailedEventArgs.SetUnwind(), System.text, System.Diagnostics.Contracts.ContractFailedEventArgs.thrownDuringHandler, System.Runtime.CompilerServices.ContractHelper.TriggerCodeContractEscalationPolicy(), and System.Diagnostics.Contracts.ContractFailedEventArgs.Unwind.
Referenced by System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEvent().