Terraria Decompiled: System.Threading.CancellationTokenSource.Dispose
Dispose() [2/2]
virtual void System.Threading.CancellationTokenSource.Dispose (bool disposing) inline protected virtual
Reimplemented in System.Threading.CancellationTokenSource.Linked1CancellationTokenSource, System.Threading.CancellationTokenSource.Linked2CancellationTokenSource, and System.Threading.CancellationTokenSource.LinkedNCancellationTokenSource.
Definition at line 225 of file CancellationTokenSource.cs.
        {
            if (disposing && !this._disposed)
            {
                Timer timer = this._timer;
                if (timer != null)
                {
                    timer.Dispose();
                }
                this._registeredCallbacksLists = null;
                if (this._kernelEvent != null)
                {
                    ManualResetEvent manualResetEvent = Interlocked.Exchange<ManualResetEvent>(ref this._kernelEvent, null);
                    if (manualResetEvent != null && this._state != 2)
                    {
                        manualResetEvent.Dispose();
                    }
                }
                this._disposed = true;
            }
        }
References System.Threading.CancellationTokenSource._disposed, System.Threading.CancellationTokenSource._kernelEvent, System.Threading.CancellationTokenSource._state, System.Threading.CancellationTokenSource._timer, System.Threading.Timer.Dispose(), System.Threading.WaitHandle.Dispose(), and System.Threading.Interlocked.Exchange().