Terraria Decompiled: Newtonsoft.Json.JsonConvert.ToString
ToString() [4/30]
static string Newtonsoft.Json.JsonConvert.ToString (DateTime value) inline static
Definition at line 35 of file JsonConvert.cs.
        {
            return JsonConvert.ToString(value, DateFormatHandling.IsoDateFormat, DateTimeZoneHandling.RoundtripKind);
        }
References Newtonsoft.Json.JsonConvert.ToString(), and System.value.
Referenced by Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonValidatingReader.ValidateFloat(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), and Newtonsoft.Json.JsonTextWriter.WriteValue().