Terraria Decompiled: Newtonsoft.Json.JsonConvert.ToString
ToString() [7/30]
static string Newtonsoft.Json.JsonConvert.ToString (DateTimeOffset value, DateFormatHandling format) inline static
Definition at line 62 of file JsonConvert.cs.
        {
            string text;
            using (StringWriter stringWriter = StringUtils.CreateStringWriter(64))
            {
                stringWriter.Write('"');
                DateTimeUtils.WriteDateTimeOffsetString(stringWriter, value, format, null, CultureInfo.InvariantCulture);
                stringWriter.Write('"');
                text = stringWriter.ToString();
            }
            return text;
        }
References Newtonsoft.Json.Utilities.StringUtils.CreateStringWriter(), System.format, System.Globalization.CultureInfo.InvariantCulture, System.text, System.IO.StringWriter.ToString(), System.value, System.IO.StringWriter.Write(), and Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffsetString().