Terraria Decompiled: System.Collections.ObjectModel.Collection.CopyTo
CopyTo() [1/2]
void ICollection. System.Collections.ObjectModel.Collection< T >.CopyTo (Array array, int index) inline private
Implements System.Collections.ICollection.
Definition at line 225 of file Collection.cs.
        {
            if (array == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
            }
            if (array.Rank != 1)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_RankMultiDimNotSupported);
            }
            if (array.GetLowerBound(0) != 0)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_NonZeroLowerBound);
            }
            if (index < 0)
            {
                ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
            }
            if (array.Length - index < this.Count)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall);
            }
            T[] array2 = array as T[];
            if (array2 != null)
            {
                this.items.CopyTo(array2, index);
                return;
            }
            Type elementType = array.GetType().GetElementType();
            Type typeFromHandle = typeof(T);
            if (!elementType.IsAssignableFrom(typeFromHandle) && !typeFromHandle.IsAssignableFrom(elementType))
            {
                ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
            }
            object[] array3 = array as object[];
            if (array3 == null)
            {
                ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
            }
            int count = this.items.Count;
            try
            {
                for (int i = 0; i < count; i++)
                {
                    array3[index++] = this.items[i];
                }
            }
            catch (ArrayTypeMismatchException)
            {
                ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
            }
        }
References System.array, System.count, System.Type.GetElementType(), System.Type.GetType(), System.index, System.Type.IsAssignableFrom(), System.Collections.ObjectModel.Collection< T >.items, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException().