Terraria Decompiled: System.Collections.ObjectModel.Collection.Insert
Insert() [2/2]
void System.Collections.ObjectModel.Collection< T >.Insert (int index, T item) inline
Definition at line 116 of file Collection.cs.
        {
            if (this.items.IsReadOnly)
            {
                ThrowHelper.ThrowNotSupportedException(ExceptionResource.NotSupported_ReadOnlyCollection);
            }
            if (index > this.items.Count)
            {
                ThrowHelper.ThrowArgumentOutOfRange_IndexException();
            }
            this.InsertItem(index, item);
        }
References System.index, System.Collections.ObjectModel.Collection< T >.InsertItem(), System.Collections.IList.IsReadOnly, System.item, System.Collections.ObjectModel.Collection< T >.items, System.ThrowHelper.ThrowArgumentOutOfRange_IndexException(), and System.ThrowHelper.ThrowNotSupportedException().
Referenced by Newtonsoft.Json.JsonSerializer.ApplySerializerSettings().