Terraria Decompiled: System.Collections.ObjectModel.Collection.Remove
Remove() [2/2]
bool System.Collections.ObjectModel.Collection< T >.Remove (T item) inline
Definition at line 130 of file Collection.cs.
        {
            if (this.items.IsReadOnly)
            {
                ThrowHelper.ThrowNotSupportedException(ExceptionResource.NotSupported_ReadOnlyCollection);
            }
            int num = this.items.IndexOf(item);
            if (num < 0)
            {
                return false;
            }
            this.RemoveItem(num);
            return true;
        }
References System.Collections.IList.IndexOf(), System.Collections.IList.IsReadOnly, System.Collections.ObjectModel.Collection< T >.items, System.Collections.ObjectModel.Collection< T >.RemoveItem(), and System.ThrowHelper.ThrowNotSupportedException().
Referenced by System.Collections.ObjectModel.Collection< T >.Remove().