Terraria Decompiled: System.Collections.ObjectModel.Collection.RemoveItem
RemoveItem()
virtual void System.Collections.ObjectModel.Collection< T >.RemoveItem (int index) inline protected virtual
Reimplemented in Microsoft.Xna.Framework.GameComponentCollection, System.Collections.ObjectModel.KeyedCollection< TKey, TItem >, and Newtonsoft.Json.Linq.JPropertyKeyedCollection.
Definition at line 172 of file Collection.cs.
        {
            this.items.RemoveAt(index);
        }
References System.Collections.ObjectModel.Collection< T >.items, and System.Collections.IList.RemoveAt().
Referenced by System.Collections.ObjectModel.Collection< T >.Remove(), and System.Collections.ObjectModel.Collection< T >.RemoveAt().