Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write
Write()
void System.Runtime.Serialization.Formatters.Binary.BinaryArray.Write (__BinaryWriter sout) inline
Implements System.Runtime.Serialization.Formatters.Binary.IStreamable.
Definition at line 52 of file BinaryArray.cs.
        {
            switch (this.binaryHeaderEnum)
            {
            case BinaryHeaderEnum.ArraySinglePrimitive:
                sout.WriteByte((byte)this.binaryHeaderEnum);
                sout.WriteInt32(this.objectId);
                sout.WriteInt32(this.lengthA[0]);
                sout.WriteByte((byte)((InternalPrimitiveTypeE)this.typeInformation));
                return;
            case BinaryHeaderEnum.ArraySingleObject:
                sout.WriteByte((byte)this.binaryHeaderEnum);
                sout.WriteInt32(this.objectId);
                sout.WriteInt32(this.lengthA[0]);
                return;
            case BinaryHeaderEnum.ArraySingleString:
                sout.WriteByte((byte)this.binaryHeaderEnum);
                sout.WriteInt32(this.objectId);
                sout.WriteInt32(this.lengthA[0]);
                return;
            default:
            {
                sout.WriteByte((byte)this.binaryHeaderEnum);
                sout.WriteInt32(this.objectId);
                sout.WriteByte((byte)this.binaryArrayTypeEnum);
                sout.WriteInt32(this.rank);
                for (int i = 0; i < this.rank; i++)
                {
                    sout.WriteInt32(this.lengthA[i]);
                }
                if (this.binaryArrayTypeEnum == BinaryArrayTypeEnum.SingleOffset || this.binaryArrayTypeEnum == BinaryArrayTypeEnum.JaggedOffset || this.binaryArrayTypeEnum == BinaryArrayTypeEnum.RectangularOffset)
                {
                    for (int j = 0; j < this.rank; j++)
                    {
                        sout.WriteInt32(this.lowerBoundA[j]);
                    }
                }
                sout.WriteByte((byte)this.binaryTypeEnum);
                BinaryConverter.WriteTypeInfo(this.binaryTypeEnum, this.typeInformation, this.assemId, sout);
                return;
            }
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryArray.assemId, System.Runtime.Serialization.Formatters.Binary.BinaryArray.binaryArrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray.binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray.binaryTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray.lengthA, System.Runtime.Serialization.Formatters.Binary.BinaryArray.lowerBoundA, System.Runtime.Serialization.Formatters.Binary.BinaryArray.objectId, System.Runtime.Serialization.Formatters.Binary.BinaryArray.rank, System.Runtime.Serialization.Formatters.Binary.BinaryArray.typeInformation, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32(), and System.Runtime.Serialization.Formatters.Binary.BinaryConverter.WriteTypeInfo().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteJaggedArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteRectangleArray(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingleArray().