Terraria Decompiled: System.Globalization.GregorianCalendar.GetAbsoluteDate
GetAbsoluteDate()
static long System.Globalization.GregorianCalendar.GetAbsoluteDate (int year, int month, int day) inline static package
Definition at line 162 of file GregorianCalendar.cs.
        {
            if (year >= 1 && year <= 9999 && month >= 1 && month <= 12)
            {
                int[] array = ((year % 4 == 0 && (year % 100 != 0 || year % 400 == 0)) ? GregorianCalendar.DaysToMonth366 : GregorianCalendar.DaysToMonth365);
                if (day >= 1 && day <= array[month] - array[month - 1])
                {
                    int num = year - 1;
                    return (long)(num * 365 + num / 4 - num / 100 + num / 400 + array[month - 1] + day - 1);
                }
            }
            throw new ArgumentOutOfRangeException(null, Environment.GetResourceString("Year, Month, and Day parameters describe an un-representable DateTime."));
        }
References System.array, System.Globalization.GregorianCalendar.DaysToMonth365, and System.Environment.GetResourceString().
Referenced by System.Globalization.GregorianCalendar.DateToTicks(), System.Globalization.UmAlQuraCalendar.GetAbsoluteDateUmAlQura(), and System.Globalization.HebrewCalendar.GetDatePart().