Terraria Decompiled: System.Globalization.GregorianCalendar.IsLeapDay
IsLeapDay()
override bool System.Globalization.GregorianCalendar.IsLeapDay (int year, int month, int day, int era) inline
Definition at line 318 of file GregorianCalendar.cs.
        {
            if (month < 1 || month > 12)
            {
                throw new ArgumentOutOfRangeException("month", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[] { 1, 12 }));
            }
            if (era != 0 && era != 1)
            {
                throw new ArgumentOutOfRangeException("era", Environment.GetResourceString("Era value was not valid."));
            }
            if (year < 1 || year > 9999)
            {
                throw new ArgumentOutOfRangeException("year", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[] { 1, 9999 }));
            }
            if (day < 1 || day > this.GetDaysInMonth(year, month))
            {
                throw new ArgumentOutOfRangeException("day", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[]
                {
                    1,
                    this.GetDaysInMonth(year, month)
                }));
            }
            return this.IsLeapYear(year) && (month == 2 && day == 29);
        }
References System.Globalization.GregorianCalendar.GetDaysInMonth(), System.Environment.GetResourceString(), and System.Globalization.GregorianCalendar.IsLeapYear().