Terraria Decompiled: SR.Format
Format() [5/5]
static string SR.Format (string resourceFormat, params object[] args) inline static package
Definition at line 32 of file SR.cs.
    {
        if (args != null)
        {
            return string.Format(CultureInfo.InvariantCulture, resourceFormat, args);
        }
        return resourceFormat;
    }
References System.Globalization.CultureInfo.InvariantCulture.
Referenced by System.Collections.ListDictionaryInternal.Add(), System.Collections.SortedList.Add(), System.Collections.Generic.LowLevelDictionary< TKey, TValue >.Add(), System.Collections.ObjectModel.KeyedCollection< TKey, TItem >.AddKey(), System.Collections.ArrayList.ArrayList(), System.Collections.BitArray.BitArray(), System.Collections.BitArray.BitArray(), System.IO.BufferedStream.BufferedStream(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CompareTo(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CompareTo(), System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.CompareTo(), System.Char.ConvertToUtf32(), System.Text.StringBuilder.CopyTo(), System.Numerics.Vector< T >.CopyTo(), System.ThrowHelper.CreateArgumentException_InvalidTypeWithPointersNotSupported(), System.ThrowHelper.CreateArgumentOutOfRangeException_PrecisionTooLarge(), System.IO.FileSystem.CreateDirectory(), System.IO.DirectoryInfo.CreateSubdirectory(), System.Security.Cryptography.CryptoStream.CryptoStream(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.DateTime.DateTime(), System.Text.DecoderReplacementFallback.DecoderReplacementFallback(), System.Text.EncoderFallbackException.EncoderFallbackException(), System.Text.EncoderReplacementFallback.EncoderReplacementFallback(), System.Text.EncoderExceptionFallbackBuffer.Fallback(), System.Text.EncoderExceptionFallbackBuffer.Fallback(), System.Text.EncoderReplacementFallbackBuffer.Fallback(), System.Text.InternalEncoderBestFitFallbackBuffer.Fallback(), System.TimeZoneInfo.FindSystemTimeZoneById(), System.IO.FileLoadException.FormatFileLoadExceptionMessage(), System.TimeZoneInfo.FromSerializedString(), System.DateTimeOffset.FromUnixTimeMilliseconds(), System.DateTimeOffset.FromUnixTimeSeconds(), System.ThrowHelper.GetAddingDuplicateWithKeyArgumentException(), System.Text.ASCIIEncoding.GetByteCount(), System.Text.UTF8Encoding.GetByteCount(), System.Text.UnicodeEncoding.GetByteCount(), System.Text.UTF32Encoding.GetByteCount(), System.Text.UTF8Encoding.GetBytes(), System.Text.ASCIIEncoding.GetBytes(), System.Text.UnicodeEncoding.GetBytes(), System.Text.UTF32Encoding.GetBytes(), System.DateTimeParse.GetDateTimeParseException(), System.CurrentSystemTimeZone.GetDaylightChanges(), Interop.GetExceptionForIoErrno(), System.Guid.GuidResult.GetGuidParseException(), System.ThrowHelper.GetKeyNotFoundException(), System.TimeZoneInfo.StringSerializer.GetNextStringValue(), System.Guid.Guid(), System.Guid.Guid(), System.Collections.Hashtable.Hashtable(), System.Collections.Hashtable.Insert(), System.Type.IsEnumDefined(), System.IO.Directory.Move(), System.IO.File.Move(), System.IO.FileSystem.MoveDirectory(), System.IO.DirectoryInfo.MoveTo(), System.IO.FileInfo.MoveTo(), System.Resources.NeutralResourcesLanguageAttribute.NeutralResourcesLanguageAttribute(), System.Random.Next(), System.Random.Next(), System.TimeZoneInfo.OnDeserialization(), System.Security.Cryptography.Rfc2898DeriveBytes.OpenHmac(), System.OperatingSystem.OperatingSystem(), System.Buffers.StandardFormat.ParseHelper(), System.Collections.Queue.Queue(), System.IO.UnmanagedMemoryAccessor.Read< T >(), System.IO.FileSystem.RemoveDirectoryInternal(), System.Math.Round(), System.MathF.Round(), System.Decimal.Round(), System.Globalization.TimeSpanParse.TimeSpanResult.SetFailure(), System.String.SplitInternal(), System.String.SplitInternal(), System.Text.StringBuilder.StringBuilder(), System.Text.StringBuilder.StringBuilder(), System.Text.DecoderExceptionFallbackBuffer.Throw(), System.Buffers.ArrayBufferWriter< T >.ThrowInvalidOperationException_AdvancedTooFar(), System.ThrowHelper.ThrowInvalidTypeWithPointersNotSupported(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ThrowKeyNotFoundException(), System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive(), System.Text.EncoderFallbackBuffer.ThrowLastCharRecursive(), System.Math.ThrowMinMaxException< T >(), System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(), System.Char.ToBoolean(), System.DateTime.ToBoolean(), System.DateTime.ToByte(), System.Version.ToCachedStringBuilder(), System.Boolean.ToChar(), System.DateTime.ToChar(), System.Decimal.ToChar(), System.Double.ToChar(), System.Single.ToChar(), System.Boolean.ToDateTime(), System.Byte.ToDateTime(), System.Char.ToDateTime(), System.Decimal.ToDateTime(), System.Double.ToDateTime(), System.Int16.ToDateTime(), System.Int32.ToDateTime(), System.Int64.ToDateTime(), System.SByte.ToDateTime(), System.Single.ToDateTime(), System.UInt16.ToDateTime(), System.UInt32.ToDateTime(), System.UInt64.ToDateTime(), System.Char.ToDecimal(), System.DateTime.ToDecimal(), System.Char.ToDouble(), System.DateTime.ToDouble(), System.DateTime.ToInt16(), System.DateTime.ToInt32(), System.DateTime.ToInt64(), System.DateTime.ToSByte(), System.Char.ToSingle(), System.DateTime.ToSingle(), System.BadImageFormatException.ToString(), System.IO.FileLoadException.ToString(), System.IO.FileNotFoundException.ToString(), System.BitConverter.ToString(), System.DateTime.ToUInt16(), System.DateTime.ToUInt32(), System.DateTime.ToUInt64(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), System.TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule(), System.Security.Cryptography.X509Certificates.X509Certificate.ValidateKeyStorageFlags(), System.TimeZoneInfo.ValidateTimeZoneInfo(), System.Numerics.Vector< T >.Vector(), System.Numerics.Vector< T >.Vector(), System.TimeZoneInfo.StringSerializer.VerifyIsEscapableCharacter(), and System.IO.UnmanagedMemoryAccessor.Write< T >().