Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile
CopyFile() [2/2]
void System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile (string sourceFileName, string destinationFileName, bool overwrite) inline
Definition at line 617 of file IsolatedStorageFile.cs.
        {
            if (sourceFileName == null)
            {
                throw new ArgumentNullException("sourceFileName");
            }
            if (destinationFileName == null)
            {
                throw new ArgumentNullException("destinationFileName");
            }
            if (sourceFileName.Trim().Length == 0)
            {
                throw new ArgumentException("An empty file name is not valid.", "sourceFileName");
            }
            if (destinationFileName.Trim().Length == 0)
            {
                throw new ArgumentException("An empty file name is not valid.", "destinationFileName");
            }
            this.CheckOpen();
            string text = Path.Combine(this.directory.FullName, sourceFileName);
            string text2 = Path.Combine(this.directory.FullName, destinationFileName);
            if (!this.IsPathInStorage(text) || !this.IsPathInStorage(text2))
            {
                throw new IsolatedStorageException("Operation not allowed.");
            }
            if (!Directory.Exists(Path.GetDirectoryName(text)))
            {
                throw new DirectoryNotFoundException("Could not find a part of path '" + sourceFileName + "'.");
            }
            if (!File.Exists(text))
            {
                throw new FileNotFoundException("Could not find a part of path '" + sourceFileName + "'.");
            }
            if (File.Exists(text2) && !overwrite)
            {
                throw new IsolatedStorageException("Operation not allowed.");
            }
            try
            {
                File.Copy(text, text2, overwrite);
            }
            catch (IOException ex)
            {
                throw new IsolatedStorageException("Operation not allowed.", ex);
            }
            catch (UnauthorizedAccessException ex2)
            {
                throw new IsolatedStorageException("Operation not allowed.", ex2);
            }
        }
References System.IO.IsolatedStorage.IsolatedStorageFile.CheckOpen(), System.IO.Path.Combine(), System.IO.File.Copy(), System.IO.IsolatedStorage.IsolatedStorageFile.directory, System.IO.Directory.Exists(), System.IO.File.Exists(), System.IO.FileSystemInfo.FullName, System.IO.Path.GetDirectoryName(), System.IO.IsolatedStorage.IsolatedStorageFile.IsPathInStorage(), and System.text.