Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile
DeleteFile()
void System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile (string file) inline
Definition at line 693 of file IsolatedStorageFile.cs.
        {
            if (file == null)
            {
                throw new ArgumentNullException("file");
            }
            if (!File.Exists(Path.Combine(this.directory.FullName, file)))
            {
                throw new IsolatedStorageException(Locale.GetText("Could not delete file '{0}'", new object[] { file }));
            }
            try
            {
                File.Delete(Path.Combine(this.directory.FullName, file));
            }
            catch
            {
                throw new IsolatedStorageException(Locale.GetText("Could not delete file '{0}'", new object[] { file }));
            }
        }
References System.IO.Path.Combine(), System.IO.File.Delete(), System.IO.File.Exists(), and Locale.GetText().