Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetDirectoryNames
GetDirectoryNames() [2/2]
string[] System.IO.IsolatedStorage.IsolatedStorageFile.GetDirectoryNames (string searchPattern) inline
Definition at line 810 of file IsolatedStorageFile.cs.
        {
            if (searchPattern == null)
            {
                throw new ArgumentNullException("searchPattern");
            }
            if (searchPattern.Contains(".."))
            {
                throw new ArgumentException("Search pattern cannot contain '..' to move up directories.", "searchPattern");
            }
            string directoryName = Path.GetDirectoryName(searchPattern);
            string fileName = Path.GetFileName(searchPattern);
            DirectoryInfo[] array = null;
            if (directoryName == null || directoryName.Length == 0)
            {
                array = this.directory.GetDirectories(searchPattern);
            }
            else
            {
                DirectoryInfo directoryInfo = this.directory.GetDirectories(directoryName)[0];
                if (directoryInfo.FullName.IndexOf(this.directory.FullName) >= 0)
                {
                    array = directoryInfo.GetDirectories(fileName);
                    string[] array2 = directoryName.Split(new char[] { Path.DirectorySeparatorChar }, StringSplitOptions.RemoveEmptyEntries);
                    for (int i = array2.Length - 1; i >= 0; i--)
                    {
                        if (directoryInfo.Name != array2[i])
{
                            array = null;
                            break;
                        }
                        directoryInfo = directoryInfo.Parent;
                    }
                }
            }
            if (array == null)
            {
                throw new SecurityException();
            }
            FileSystemInfo[] array3 = array;
            return this.GetNames(array3);
        }
References System.array, System.IO.IsolatedStorage.IsolatedStorageFile.directory, System.IO.FileSystemInfo.FullName, System.IO.DirectoryInfo.GetDirectories(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), System.IO.IsolatedStorage.IsolatedStorageFile.GetNames(), System.IO.FileSystemInfo.Name, and System.IO.DirectoryInfo.Parent.