Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForApplication
GetUserStoreForApplication()
static IsolatedStorageFile System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForApplication () inline static
Definition at line 204 of file IsolatedStorageFile.cs.
        {
            IsolatedStorageScope isolatedStorageScope = IsolatedStorageScope.User | IsolatedStorageScope.Application;
            IsolatedStorageFile isolatedStorageFile = new IsolatedStorageFile(isolatedStorageScope);
            isolatedStorageFile.InitStore(isolatedStorageScope, null);
            isolatedStorageFile._fullEvidences = Assembly.GetCallingAssembly().UnprotectedGetEvidence();
            isolatedStorageFile.PostInit();
            return isolatedStorageFile;
        }
References System.Reflection.Assembly.GetCallingAssembly(), System.IO.IsolatedStorage.IsolatedStorage.InitStore(), System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), System.IO.IsolatedStorage.IsolatedStorageFile.PostInit(), and System.Reflection.Assembly.UnprotectedGetEvidence().