Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.PostInit
PostInit()
void System.IO.IsolatedStorage.IsolatedStorageFile.PostInit () inline private
Definition at line 397 of file IsolatedStorageFile.cs.
        {
            string text = IsolatedStorageFile.GetIsolatedStorageRoot(base.Scope);
            string text2;
            if (this._applicationIdentity != null)
            {
                text2 = string.Format("a{0}{1}", this.SeparatorInternal, this.GetNameFromIdentity(this._applicationIdentity));
            }
            else if (this._domainIdentity != null)
            {
                text2 = string.Format("d{0}{1}{0}{2}", this.SeparatorInternal, this.GetNameFromIdentity(this._domainIdentity), this.GetNameFromIdentity(this._assemblyIdentity));
            }
            else
            {
                if (this._assemblyIdentity == null)
                {
                    throw new IsolatedStorageException(Locale.GetText("No code identity available."));
                }
                text2 = string.Format("d{0}none{0}{1}", this.SeparatorInternal, this.GetNameFromIdentity(this._assemblyIdentity));
            }
            text = Path.Combine(text, text2);
            this.directory = new DirectoryInfo(text);
            if (!this.directory.Exists)
            {
                try
                {
                    this.directory.Create();
                    this.SaveIdentities(text);
                }
                catch (IOException)
                {
                }
            }
        }
References System.IO.IsolatedStorage.IsolatedStorage._applicationIdentity, System.IO.IsolatedStorage.IsolatedStorage._assemblyIdentity, System.IO.IsolatedStorage.IsolatedStorage._domainIdentity, System.IO.Path.Combine(), System.IO.DirectoryInfo.Create(), System.IO.IsolatedStorage.IsolatedStorageFile.directory, System.IO.FileSystemInfo.Exists, System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageRoot(), System.IO.IsolatedStorage.IsolatedStorageFile.GetNameFromIdentity(), Locale.GetText(), System.IO.IsolatedStorage.IsolatedStorageFile.SaveIdentities(), System.IO.IsolatedStorage.IsolatedStorage.SeparatorInternal, and System.text.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForApplication(), System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForAssembly(), System.IO.IsolatedStorage.IsolatedStorageFile.GetMachineStoreForDomain(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForApplication(), System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForAssembly(), and System.IO.IsolatedStorage.IsolatedStorageFile.GetUserStoreForDomain().