Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageRoot
GetIsolatedStorageRoot()
static string System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageRoot (IsolatedStorageScope scope) inline static package
Definition at line 265 of file IsolatedStorageFile.cs.
        {
            string text = null;
            if ((scope & IsolatedStorageScope.User) != IsolatedStorageScope.None)
            {
                if ((scope & IsolatedStorageScope.Roaming) != IsolatedStorageScope.None)
                {
                    text = Environment.UnixGetFolderPath(Environment.SpecialFolder.LocalApplicationData, Environment.SpecialFolderOption.Create);
                }
                else
                {
                    text = Environment.UnixGetFolderPath(Environment.SpecialFolder.ApplicationData, Environment.SpecialFolderOption.Create);
                }
            }
            else if ((scope & IsolatedStorageScope.Machine) != IsolatedStorageScope.None)
            {
                text = Environment.UnixGetFolderPath(Environment.SpecialFolder.CommonApplicationData, Environment.SpecialFolderOption.Create);
            }
            if (text == null)
            {
                throw new IsolatedStorageException(string.Format(Locale.GetText("Couldn't access storage location for '{0}'."), scope));
            }
            return Path.Combine(text, ".isolated-storage");
        }
References System.IO.Path.Combine(), System.Format, Locale.GetText(), and System.text.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.GetEnumerator(), System.IO.IsolatedStorage.IsolatedStorageFile.PostInit(), and System.IO.IsolatedStorage.IsolatedStorageFile.Remove().