Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.SaveIdentities
SaveIdentities()
void System.IO.IsolatedStorage.IsolatedStorageFile.SaveIdentities (string root) inline private
Definition at line 1150 of file IsolatedStorageFile.cs.
        {
            IsolatedStorageFile.Identities identities = new IsolatedStorageFile.Identities(this._applicationIdentity, this._assemblyIdentity, this._domainIdentity);
            BinaryFormatter binaryFormatter = new BinaryFormatter();
            IsolatedStorageFile.mutex.WaitOne();
            try
            {
                using (FileStream fileStream = File.Create(root + ".storage"))
                {
                    binaryFormatter.Serialize(fileStream, identities);
                }
            }
            finally
            {
                IsolatedStorageFile.mutex.ReleaseMutex();
            }
        }
References System.IO.IsolatedStorage.IsolatedStorage._applicationIdentity, System.IO.IsolatedStorage.IsolatedStorage._assemblyIdentity, System.IO.IsolatedStorage.IsolatedStorage._domainIdentity, System.IO.File.Create(), System.IO.IsolatedStorage.IsolatedStorageFile.mutex, System.Threading.Mutex.ReleaseMutex(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), and System.Threading.WaitHandle.WaitOne().
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.PostInit().