Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetStore
GetStore() [3/5]
static IsolatedStorageFile System.IO.IsolatedStorage.IsolatedStorageFile.GetStore (IsolatedStorageScope scope, object domainIdentity, object assemblyIdentity) inline static
Definition at line 82 of file IsolatedStorageFile.cs.
        {
            IsolatedStorageFile.Demand(scope);
            if ((scope & IsolatedStorageScope.Domain) != IsolatedStorageScope.None && domainIdentity == null)
            {
                throw new ArgumentNullException("domainIdentity");
            }
            bool flag = (scope & IsolatedStorageScope.Assembly) > IsolatedStorageScope.None;
            if (flag && assemblyIdentity == null)
            {
                throw new ArgumentNullException("assemblyIdentity");
            }
            IsolatedStorageFile isolatedStorageFile = new IsolatedStorageFile(scope);
            if (flag)
            {
                isolatedStorageFile._fullEvidences = Assembly.GetCallingAssembly().UnprotectedGetEvidence();
            }
            isolatedStorageFile._domainIdentity = domainIdentity;
            isolatedStorageFile._assemblyIdentity = assemblyIdentity;
            isolatedStorageFile.PostInit();
            return isolatedStorageFile;
        }
References System.IO.IsolatedStorage.IsolatedStorageFile.Demand(), System.Reflection.Assembly.GetCallingAssembly(), System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), System.IO.IsolatedStorage.IsolatedStorageFile.PostInit(), and System.Reflection.Assembly.UnprotectedGetEvidence().