Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames
GetFileNames() [2/2]
string[] System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames (string searchPattern) inline
Definition at line 872 of file IsolatedStorageFile.cs.
        {
            if (searchPattern == null)
            {
                throw new ArgumentNullException("searchPattern");
            }
            if (searchPattern.Contains(".."))
            {
                throw new ArgumentException("Search pattern cannot contain '..' to move up directories.", "searchPattern");
            }
            string directoryName = Path.GetDirectoryName(searchPattern);
            string fileName = Path.GetFileName(searchPattern);
            FileInfo[] array;
            if (directoryName == null || directoryName.Length == 0)
            {
                array = this.directory.GetFiles(searchPattern);
            }
            else
            {
                DirectoryInfo[] directories = this.directory.GetDirectories(directoryName);
                if (directories.Length != 1)
                {
                    throw new SecurityException();
                }
                if (!directories[0].FullName.StartsWith(this.directory.FullName))
                {
                    throw new SecurityException();
                }
                if (directories[0].FullName.Substring(this.directory.FullName.Length + 1) != directoryName)
                {
                    throw new SecurityException();
                }
                array = directories[0].GetFiles(fileName);
            }
            FileSystemInfo[] array2 = array;
            return this.GetNames(array2);
        }
References System.array, System.IO.IsolatedStorage.IsolatedStorageFile.directory, System.FullName, System.IO.DirectoryInfo.GetDirectories(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), System.IO.DirectoryInfo.GetFiles(), and System.IO.IsolatedStorage.IsolatedStorageFile.GetNames().