Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetNameFromIdentity
GetNameFromIdentity()
string System.IO.IsolatedStorage.IsolatedStorageFile.GetNameFromIdentity (object identity) inline private
Definition at line 1099 of file IsolatedStorageFile.cs.
        {
            byte[] bytes = Encoding.UTF8.GetBytes(identity.ToString());
            Array array = SHA1.Create().ComputeHash(bytes, 0, bytes.Length);
            byte[] array2 = new byte[10];
            Buffer.BlockCopy(array, 0, array2, 0, array2.Length);
            return CryptoConvert.ToHex(array2);
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.SHA1.Create(), System.Text.Encoding.GetBytes(), Mono.Security.Cryptography.CryptoConvert.ToHex(), and System.Text.Encoding.UTF8.
Referenced by System.IO.IsolatedStorage.IsolatedStorageFile.PostInit().