Terraria Decompiled: System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime
GetLastWriteTime()
DateTimeOffset System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime (string path) inline
Definition at line 790 of file IsolatedStorageFile.cs.
        {
            if (path == null)
            {
                throw new ArgumentNullException("path");
            }
            if (path.Trim().Length == 0)
            {
                throw new ArgumentException("An empty path is not valid.");
            }
            this.CheckOpen();
            string text = Path.Combine(this.directory.FullName, path);
            if (File.Exists(text))
            {
                return File.GetLastWriteTime(text);
            }
            return Directory.GetLastWriteTime(text);
        }
References System.IO.IsolatedStorage.IsolatedStorageFile.CheckOpen(), System.IO.Path.Combine(), System.IO.IsolatedStorage.IsolatedStorageFile.directory, System.IO.File.Exists(), System.IO.FileSystemInfo.FullName, System.IO.Directory.GetLastWriteTime(), System.IO.File.GetLastWriteTime(), and System.text.