Terraria Decompiled: Newtonsoft.Json.Utilities.EnumUtils.GetFlagsValues< T >
GetFlagsValues< T >()
static IList< T > Newtonsoft.Json.Utilities.EnumUtils.GetFlagsValues< T > (T value) inline static
Type Constraints
T : struct
Definition at line 33 of file EnumUtils.cs.
                                                                  : struct
        {
            Type typeFromHandle = typeof(T);
            if (!typeFromHandle.IsDefined(typeof(FlagsAttribute), false))
            {
                throw new ArgumentException("Enum type {0} is not a set of flags.".FormatWith(CultureInfo.InvariantCulture, typeFromHandle));
            }
            Type underlyingType = Enum.GetUnderlyingType(value.GetType());
            ulong num = Convert.ToUInt64(value, CultureInfo.InvariantCulture);
            IList<EnumValue<ulong>> namesAndValues = EnumUtils.GetNamesAndValues<T>();
            IList<T> list = new List<T>();
            foreach (EnumValue<ulong> enumValue in namesAndValues)
            {
                if ((num & enumValue.Value) == enumValue.Value && enumValue.Value != 0UL)
                {
                    list.Add((T)((object)Convert.ChangeType(enumValue.Value, underlyingType, CultureInfo.CurrentCulture)));
                }
            }
            if (list.Count == 0)
            {
                if (Enumerable.SingleOrDefault<EnumValue<ulong>>(namesAndValues, (EnumValue<ulong> v) => v.Value == 0UL) != null)
                {
                    list.Add(default(T));
                }
            }
            return list;
        }
References System.Convert.ChangeType(), System.Globalization.CultureInfo.CurrentCulture, System.Enum.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, System.Reflection.MemberInfo.IsDefined(), System.list, System.Convert.ToUInt64(), System.value, and Newtonsoft.Json.Utilities.EnumValue< T >.Value.