Terraria Decompiled: Newtonsoft.Json.Utilities.EnumUtils.GetNamesAndValues< TUnderlyingType >
GetNamesAndValues< TUnderlyingType >()
static IList< EnumValue< TUnderlyingType > > Newtonsoft.Json.Utilities.EnumUtils.GetNamesAndValues< TUnderlyingType > (Type enumType) inline static
Type Constraints
TUnderlyingType : struct
Definition at line 68 of file EnumUtils.cs.
                                                                                                                                : struct
        {
            if (enumType == null)
            {
                throw new ArgumentNullException("enumType");
            }
            if (!enumType.IsEnum())
            {
                throw new ArgumentException("Type {0} is not an enum.".FormatWith(CultureInfo.InvariantCulture, enumType.Name), "enumType");
            }
            IList<object> values = EnumUtils.GetValues(enumType);
            IList<string> names = EnumUtils.GetNames(enumType);
            IList<EnumValue<TUnderlyingType>> list = new List<EnumValue<TUnderlyingType>>();
            for (int i = 0; i < values.Count; i++)
            {
                try
                {
                    list.Add(new EnumValue<TUnderlyingType>(names[i], (TUnderlyingType)((object)Convert.ChangeType(values[i], typeof(TUnderlyingType), CultureInfo.CurrentCulture))));
                }
                catch (OverflowException ex)
                {
                    throw new InvalidOperationException("Value from enum with the underlying type of {0} cannot be added to dictionary with a value type of {1}. Value was too large: {2}".FormatWith(CultureInfo.InvariantCulture, Enum.GetUnderlyingType(enumType), typeof(TUnderlyingType), Convert.ToUInt64(values[i], CultureInfo.InvariantCulture)), ex);
                }
            }
            return list;
        }
References System.Collections.Generic.List< T >.Add(), System.Convert.ChangeType(), System.Globalization.CultureInfo.CurrentCulture, Newtonsoft.Json.Utilities.EnumUtils.GetNames(), System.Enum.GetUnderlyingType(), Newtonsoft.Json.Utilities.EnumUtils.GetValues(), System.Globalization.CultureInfo.InvariantCulture, System.list, System.Globalization.CultureInfo.Name, System.Convert.ToUInt64(), and System.values.