Terraria Decompiled: Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName
ParseEnumName()
static object Newtonsoft.Json.Utilities.EnumUtils.ParseEnumName (string enumText, bool isNullable, bool disallowValue, Type t) inline static
Definition at line 128 of file EnumUtils.cs.
        {
            if (enumText == string.Empty && isNullable)
            {
                return null;
            }
            BidirectionalDictionary<string, string> bidirectionalDictionary = EnumUtils.EnumMemberNamesPerType.Get(t);
            string text;
            string text2;
            if (EnumUtils.TryResolvedEnumName(bidirectionalDictionary, enumText, out text))
            {
                text2 = text;
            }
            else if (enumText.IndexOf(',') != -1)
            {
                string[] array = enumText.Split(new char[] { ',' });
                for (int i = 0; i < array.Length; i++)
                {
                    string text3 = array[i].Trim();
                    array[i] = (EnumUtils.TryResolvedEnumName(bidirectionalDictionary, text3, out text) ? text : text3);
                }
                text2 = string.Join(", ", array);
            }
            else
            {
                text2 = enumText;
                if (disallowValue)
                {
                    bool flag = true;
                    for (int j = 0; j < text2.Length; j++)
                    {
                        if (!char.IsNumber(text2.get_Chars(j)))
{
                            flag = false;
                            break;
                        }
                    }
                    if (flag)
                    {
                        throw new FormatException("Integer string '{0}' is not allowed.".FormatWith(CultureInfo.InvariantCulture, enumText));
                    }
                }
            }
            return Enum.Parse(t, text2, true);
        }
References System.array, Newtonsoft.Json.Utilities.EnumUtils.EnumMemberNamesPerType, System.Globalization.CultureInfo.InvariantCulture, System.Enum.Parse(), System.text, and Newtonsoft.Json.Utilities.EnumUtils.TryResolvedEnumName().
Referenced by Newtonsoft.Json.Converters.StringEnumConverter.ReadJson().