Terraria Decompiled: Newtonsoft.Json.Converters.DataTableConverter.CreateRow
CreateRow()
static void Newtonsoft.Json.Converters.DataTableConverter.CreateRow (JsonReader reader, DataTable dt, JsonSerializer serializer) inline static private
Definition at line 73 of file DataTableConverter.cs.
        {
            DataRow dataRow = dt.NewRow();
            reader.ReadAndAssert();
            while (reader.TokenType == JsonToken.PropertyName)
            {
                string text = (string)reader.Value;
                reader.ReadAndAssert();
                DataColumn dataColumn = dt.Columns[text];
                if (dataColumn == null)
                {
                    Type columnDataType = DataTableConverter.GetColumnDataType(reader);
                    dataColumn = new DataColumn(text, columnDataType);
                    dt.Columns.Add(dataColumn);
                }
                if (dataColumn.DataType == typeof(DataTable))
                {
                    if (reader.TokenType == JsonToken.StartArray)
                    {
                        reader.ReadAndAssert();
                    }
                    DataTable dataTable = new DataTable();
                    while (reader.TokenType != JsonToken.EndArray)
                    {
                        DataTableConverter.CreateRow(reader, dataTable, serializer);
                        reader.ReadAndAssert();
                    }
                    dataRow[text] = dataTable;
                }
                else if (dataColumn.DataType.IsArray && dataColumn.DataType != typeof(byte[]))
                {
                    if (reader.TokenType == JsonToken.StartArray)
                    {
                        reader.ReadAndAssert();
                    }
                    List<object> list = new List<object>();
                    while (reader.TokenType != JsonToken.EndArray)
                    {
                        list.Add(reader.Value);
                        reader.ReadAndAssert();
                    }
                    Array array = Array.CreateInstance(dataColumn.DataType.GetElementType(), list.Count);
                    list.CopyTo(array, 0);
                    dataRow[text] = array;
                }
                else
                {
                    object obj = ((reader.Value != null) ? (serializer.Deserialize(reader, dataColumn.DataType) ?? DBNull.Value) : DBNull.Value);
                    dataRow[text] = obj;
                }
                reader.ReadAndAssert();
            }
            dataRow.EndEdit();
            dt.Rows.Add(dataRow);
        }
References System.array, System.Array.CopyTo(), System.Array.CreateInstance(), Newtonsoft.Json.Converters.DataTableConverter.CreateRow(), Newtonsoft.Json.JsonSerializer.Deserialize(), Newtonsoft.Json.Converters.DataTableConverter.GetColumnDataType(), System.list, System.obj, Newtonsoft.Json.JsonReader.ReadAndAssert(), System.text, Newtonsoft.Json.JsonReader.TokenType, System.DBNull.Value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Converters.DataTableConverter.CreateRow(), and Newtonsoft.Json.Converters.DataTableConverter.ReadJson().