Terraria Decompiled: Newtonsoft.Json.Converters.DataTableConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.DataTableConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 39 of file DataTableConverter.cs.
        {
            if (reader.TokenType == JsonToken.Null)
            {
                return null;
            }
            DataTable dataTable = existingValue as DataTable;
            if (dataTable == null)
            {
                dataTable = ((objectType == typeof(DataTable)) ? new DataTable() : ((DataTable)Activator.CreateInstance(objectType)));
            }
            if (reader.TokenType == JsonToken.PropertyName)
            {
                dataTable.TableName = (string)reader.Value;
                reader.ReadAndAssert();
                if (reader.TokenType == JsonToken.Null)
                {
                    return dataTable;
                }
            }
            if (reader.TokenType != JsonToken.StartArray)
            {
                throw JsonSerializationException.Create(reader, "Unexpected JSON token when reading DataTable. Expected StartArray, got {0}.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
            }
            reader.ReadAndAssert();
            while (reader.TokenType != JsonToken.EndArray)
            {
                DataTableConverter.CreateRow(reader, dataTable, serializer);
                reader.ReadAndAssert();
            }
            return dataTable;
        }
References Newtonsoft.Json.JsonSerializationException.Create(), System.Activator.CreateInstance(), Newtonsoft.Json.Converters.DataTableConverter.CreateRow(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Converters.DataSetConverter.ReadJson().