Terraria Decompiled: System.IO.File.d__81.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.File.d__81.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1910 of file File.cs.
            {
                int num2;
                int num = num2;
                try
                {
                    if (num > 1)
                    {
                        buffer = null;
                    }
                    try
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                        if (num != 0)
{
                            if (num != 1)
{
                                buffer = ArrayPool<char>.Shared.Rent(4096);
                                count = contents.Length;
                                index = 0;
                                goto IL_0121;
                            }
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_019F;
                        }
                        else
{
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                        }
                        IL_0107:
                        configuredTaskAwaiter.GetResult();
                        index += batchSize;
                        IL_0121:
                        if (index >= count)
{
                            cancellationToken.ThrowIfCancellationRequested();
                            configuredTaskAwaiter = sw.FlushAsync().ConfigureAwait(false).GetAwaiter();
                            if (!configuredTaskAwaiter.IsCompleted)
{
                                num = (num2 = 1);
                                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, File.<InternalWriteAllTextAsync>d__81>(ref configuredTaskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            batchSize = Math.Min(4096, count - index);
                            contents.CopyTo(index, buffer, 0, batchSize);
                            configuredTaskAwaiter = sw.WriteAsync(new ReadOnlyMemory<char>(buffer, 0, batchSize), cancellationToken).ConfigureAwait(false).GetAwaiter();
                            if (!configuredTaskAwaiter.IsCompleted)
{
                                num = (num2 = 0);
                                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, File.<InternalWriteAllTextAsync>d__81>(ref configuredTaskAwaiter, ref this);
                                return;
                            }
                            goto IL_0107;
                        }
                        IL_019F:
                        configuredTaskAwaiter.GetResult();
                    }
                    finally
                    {
                        if (num < 0)
{
                            sw.Dispose();
                            if (buffer != null)
{
                                ArrayPool<char>.Shared.Return(buffer, false);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    buffer = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                buffer = null;
                this.<>t__builder.SetResult();
            }
References System.count, System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.index, System.IO.File.InternalWriteAllTextAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Math.Min(), and System.Buffers.ArrayPool< T >.Shared.