Terraria Decompiled: System.Math.Max
Max() [1/11]
static byte System.Math.Max (byte val1, byte val2) inline static
Definition at line 415 of file Math.cs.
        {
            if (val1 < val2)
            {
                return val2;
            }
            return val1;
        }
Referenced by Mono.DataConverter.PackContext.Add(), Terraria.Cinematics.Film.AddKeyFrame(), Terraria.Cinematics.Film.AddSequence(), ReLogic.Utilities.MultiTimer.TimerData.AddTick(), Terraria.PopupText.AddToCoinValue(), Terraria.SceneMetrics.AggregateTileCounts(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_019_Spears_GetSpearOffsetRelativeToPlayer(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_118_Seahorses(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_170_FairyGlowstick(), Terraria.Projectile.AI_174_MultisegmentPet(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_204_Digtoise(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks(), Terraria.NPC.AI_FindNearbyBook(), Terraria.WorldGen.AnyLiquidAt(), System.Reflection.Emit.SignatureHelper.AppendArrayAt(), Terraria.Cinematics.Film.AppendKeyFrames(), Terraria.Cinematics.Film.AppendSequences(), Terraria.WorldBuilding.Modifiers.RadialDither.Apply(), Terraria.Player.ApplyAttackCooldown(), Terraria.Collision.ApplyConveyorBeltMovementToVelocity(), Terraria.Player.ApplyItemTime(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), Terraria.SceneState.ApplyVisuals(), Terraria.Chest.AskForChestToEatItem(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners(), Terraria.Item.BestPrefixValue(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColor(), Ionic.Zlib.Tree.build_tree(), Terraria.Collision.BuildTileContacts(), Microsoft.Xna.Framework.Graphics.Texture.CalculateDDSLevelSize(), Terraria.GameContent.Biomes.DitherSnakePass.CalculateDungeonDitherSnake(), Microsoft.Xna.Framework.Graphics.Texture.CalculateMipLevels(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom(), Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.Main.ChangeRain(), System.Buffers.ArrayBufferWriter< T >.CheckAndResizeBuffer(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Clear(), Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd(), ReLogic.Content.AssetPathHelper.CollapseParentDirectory(), Terraria.WaterfallManager.Configuration_OnLoad(), ReLogic.Peripherals.RGB.Fragment.CreateCanvasPositions(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.CreateFragment(), Microsoft.Xna.Framework.BoundingBox.CreateMerged(), Microsoft.Xna.Framework.BoundingSphere.CreateMerged(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Player.DashMovement(), Terraria.Main.DedServ(), Terraria.Graphics.Light.LegacyLighting.doColors_Mode0_Swipe(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.Mount.DoSpawnDust(), Terraria.Main.DoUpdate_HandleChat(), Terraria.GameContent.UI.NPCChatPanel.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.Main.DrawBlack(), Terraria.GameContent.UI.NPCChatPanel.DrawButtons(), Terraria.UI.Chat.ChatManager.DrawColorCodedString(), Terraria.Testing.DetailedFPS.DrawFrame(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost(), Terraria.Main.DrawIMEPanel(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawProjDirect(), Terraria.UI.ChestUI.DrawSlots(), Terraria.Main.DrawSplash_LoadingFlower(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawSurfaceBG_GetFogPower(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawUnderworldBackgroundLayer(), Terraria.Main.DrawWaters(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.Cinematics.DD2Film.DryadPortalFade(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.GameContent.EmergencyStacking.EmergencyStackItemsToMakeSpace(), Mono.Security.Cryptography.PKCS1.Encode_v15(), Mono.Security.Cryptography.PKCS1.Encrypt_v15(), System.Collections.Generic.ArrayBuilder< T >.EnsureCapacity(), Terraria.GameContent.UI.States.UIWorldCreation.EstablishUpDownRelationship(), Newtonsoft.Json.Linq.JsonPath.ArraySliceFilter.ExecuteFilter(), System.Text.StringBuilder.ExpandByABlock(), Terraria.Graphics.Light.LightingEngine.ExportToMiniMap(), Terraria.Utils.FactorAcceleration(), Terraria.WorldGen.FillWallHolesInArea(), Terraria.WorldGen.FillWallHolesInColumn(), Terraria.NPC.FindFrame(), Terraria.Collision.FindOverlapPoints(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FixBestiaryRange(), ReLogic.Threading.FastParallel.For(), System.NumberFormatter.FormatHexadecimal(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateFloatingRocksInArea(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.GenerateHallway(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GeneratePreHallwaysDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateRockPlatform(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateShimmerPool(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothemsInArea(), Terraria.NPC.GetAlpha(), Terraria.WorldBuilding.ShapeData.GetBounds(), Terraria.Utils.GetChaseResults(), Terraria.GameContent.Skies.AmbientSky.VultureSkyEntity.GetColor(), System.MonoCustomAttrs.GetCustomAttributes(), System.MonoCustomAttrs.GetCustomAttributesData(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Drawing.BackgroundGradientDrawer.GetGradientRect(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetGradientRect(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.GetHallwayConnectionPoints(), Terraria.Main.GetInfoAccIconPosition(), System.Runtime.Serialization.FormatterServices.GetParentTypes(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetRandomizedRoomCountInABigAbandonedHouse(), System.IO.Path.GetRelativePath(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture(), System.Text.ValueStringBuilder.Grow(), Terraria.WorldGen.GrowLivingTree_MakePassage(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable(), Terraria.Player.HardcoreDeathPenalty(), Terraria.Utils.Including(), System.Runtime.Serialization.Formatters.Binary.IntSizedArray.IncreaseCapacity(), System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(), System.TermInfoDriver.Init(), NVorbis.Residue0.Init(), System.IO.FileStream.InitBuffer(), System.Number.Int32ToHexStr(), System.Number.Int64ToHexStr(), Microsoft.Xna.Framework.GraphicsDeviceManager.INTERNAL_CreateGraphicsDeviceInformation(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_HandleOrientationChange(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_HandleOrientationChange(), ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), System.IO.File.InternalReadAllBytesUnknownLengthAsync(), Microsoft.Xna.Framework.Rectangle.Intersect(), System.ParseNumbers.IntToString(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStripRightSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips(), Terraria.Localization.LanguageManager.LoadLanguageFromFileTextCsv(), System.ParseNumbers.LongToString(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHallSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings(), FullSerializer.fsJsonParser.MakeFailure(), System.Text.StringBuilder.MakeRoom(), System.Security.Permissions.StrongNameIdentityPermission.Match(), System.Security.Permissions.UrlIdentityPermission.Match(), Newtonsoft.Json.Utilities.MathUtils.Max(), System.MathF.Max(), Newtonsoft.Json.Utilities.MathUtils.Max(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), ReLogic.Graphics.DynamicSpriteFont.MeasureString(), Terraria.WorldBuilding.TileFont.MeasureString(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), Terraria.Projectile.Minion_FindTargetInRange(), System.IO.File.d__72.MoveNext(), Terraria.SceneState.MoveTowards(), Terraria.UI.BannerClaimingUI.NavigatePipsGrid(), System.Number.NegativeInt32ToDecStr(), System.Number.NegativeInt64ToDecStr(), Terraria.Rain.NewRain(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings(), Terraria.GameContent.Generation.Dungeon.DungeonShapes.HourglassRoom.Perform(), Terraria.GameContent.Generation.ShapeRunner.Perform(), Terraria.GameContent.Generation.ShapeBranch.PerformSegment(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPlatforms.Platforms(), Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData(), Terraria.GameContent.RGB.SkyShader.ProcessAnyDetail(), Terraria.GameContent.RGB.BrainShader.ProcessHighDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.DrippingShader.ProcessHighDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessHighDetail(), Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.IceShader.ProcessHighDetail(), Terraria.GameContent.RGB.JungleShader.ProcessHighDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.RainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SkullShader.ProcessHighDetail(), Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail(), Terraria.GameContent.RGB.TempleShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundHallowShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundMushroomShader.ProcessHighDetail(), Terraria.GameContent.RGB.WallOfFleshShader.ProcessHighDetail(), Terraria.GameContent.RGB.BrainShader.ProcessLowDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessLowDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessLowDetail(), Terraria.GameContent.RGB.GolemShader.ProcessLowDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessLowDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessLowDetail(), Terraria.GameContent.RGB.MoonShader.ProcessLowDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessLowDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail(), Terraria.GameContent.RGB.WormShader.ProcessLowDetail(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ProvideUIElement(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.Dust.QuickCircle(), Terraria.GameContent.UI.UIDust.QuickCircle(), Terraria.Player.QuickGrapple(), Microsoft.Xna.Framework.Content.Texture3DReader.Read(), System.IO.File.ReadAllBytesUnknownLength(), Ionic.Zip.ZipFile.ReadIntoInstance(), Terraria.Social.Steam.SteamP2PReader.ReadTick(), Terraria.Social.WeGame.WeGameP2PReader.ReadTick(), Terraria.Testing.PacketHistory.Record(), Terraria.GameContent.RGB.EmpressShader.RedsVersion(), System.Text.StringBuilder.Replace(), Terraria.UI.UserInterface.ResetState(), Terraria.Main.rgbToHsl(), Terraria.Player.RollerSkateMovement(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.SelectGoodRoomForHallway(), Terraria.NetMessage.SendData(), Microsoft.Xna.Framework.Graphics.TextureCube.SetData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.SetData< T >(), Microsoft.Xna.Framework.Graphics.TextureCube.SetDataPointerEXT(), Microsoft.Xna.Framework.Graphics.Texture2D.SetDataPointerEXT(), Terraria.Main.SetDisplayMode(), Terraria.NPC.setFireFlyChance(), Terraria.Player.SetItemAnimation(), Terraria.GameContent.Drawing.WindGrid.SetSize(), Terraria.GameContent.UI.Elements.UIIconTextButton.SetText(), ReLogic.Peripherals.RGB.Fragment.SetupCanvasBounds(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonDataVariables(), Terraria.GameContent.Biomes.GraniteBiome.SimulatePressure(), Terraria.Collision.SolidFullTiles(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.Spikes(), Terraria.DelegateMethods.SpreadTile(), Terraria.Main.startDedInputCallBack(), Terraria.Physics.BallCollision.Step(), ReLogic.Utilities.MultiTimer.StopAndPrint(), System.Text.StringBuilder.StringBuilder(), System.Text.StringBuilder.StringBuilder(), Terraria.Recipe.SubtractOwnedItem(), Terraria.GameContent.Biomes.Desert.SurfaceMap.SurfaceMap(), Microsoft.Xna.Framework.Game.Tick(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.DataStructures.ActiveSections.TimeTillInactive(), Microsoft.Xna.Framework.BoundingSphere.Transform(), Microsoft.Xna.Framework.BoundingSphere.Transform(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64X(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), System.Number.TryInt32ToHexStr(), System.Number.TryInt64ToHexStr(), System.Number.TryNegativeInt32ToDecStr(), System.Number.TryNegativeInt64ToDecStr(), Terraria.WorldGen.TryPlacingChilletEgg(), System.Number.TryUInt32ToDecStr(), System.Number.TryUInt64ToDecStr(), System.Number.UInt32ToDecStr(), System.Number.UInt64ToDecStr(), Microsoft.Xna.Framework.Rectangle.Union(), Microsoft.Xna.Framework.Rectangle.Union(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update(), Terraria.Net.Ping.Update(), Terraria.UI.Gamepad.UILinkPointNavigator.Update(), Terraria.GameContent.RGB.SkyShader.Update(), ReLogic.Peripherals.RGB.RgbKey.Update(), Terraria.GameContent.Skies.LanternSky.Update(), Terraria.GameContent.Skies.MoonLordSky.Update(), Terraria.GameContent.Skies.NebulaSky.Update(), Terraria.GameContent.Skies.SolarSky.Update(), Terraria.GameContent.Skies.StardustSky.Update(), Terraria.GameContent.Skies.VortexSky.Update(), Terraria.Graphics.Effects.FilterManager.Update(), Terraria.UI.UserInterface.Update(), Terraria.Player.Update(), Terraria.Main.updateCloudLayer(), Terraria.Dust.UpdateDust(), Terraria.Player.UpdateJumpHeight(), Terraria.Map.WorldMap.UpdateLighting(), Terraria.Player.UpdateNetOffset(), Terraria.NPC.UpdateNPC_TeleportVisuals(), Terraria.NPC.UpdateProtectedSpawnSlots(), Terraria.GameContent.Events.MysticLogFairiesEvent.UpdateTime(), ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.UpdateVisibility(), Terraria.WorldGen.WavyCaverer(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom().