Terraria Decompiled: System.Math.Pow
Pow()
static double System.Math.Pow (double x, double y)
Referenced by Terraria.Projectile.AI_203_StormLightning(), Terraria.Player.ApplyRangeCompensation(), Terraria.Utils.BounceEaseOut(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms(), NVorbis.Utils.ConvertFromVorbisFloat32(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.CreatePowerTable(), System.Globalization.CalendricalCalculationsHelper.DefaultEphemerisCorrection(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIIIDecoder.DequantizeSample(), Terraria.Graphics.Renderers.StormLightningParticle.Draw(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawSunAndMoon(), Terraria.Utils.EaseOutCirc(), System.Globalization.CalendricalCalculationsHelper.EquationOfTime(), System.DateTimeFormat.FormatCustomized(), XPT.Core.Audio.MP3Sharp.Decoding.Equalizer.GetBandFactor(), Terraria.NPC.LadyBugLuck(), NVorbis.Codebook.lookup1_values(), Terraria.Rain.NewRain(), System.Globalization.TimeSpanParse.Pow10(), Terraria.Audio.ASoundEffectBasedAudioTrack.ReMapVolumeToMatchXact(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.Main.snowing(), Terraria.Main.UpdateAudio(), Terraria.Player.UpdateCoinLuck(), and Microsoft.Xna.Framework.Audio.SoundEffectInstance.UpdatePitch().