Terraria Decompiled: System.Math.Floor
Floor() [1/2]
static decimal System.Math.Floor (decimal d) inline static
Definition at line 346 of file Math.cs.
        {
            return decimal.Floor(d);
        }
Referenced by Terraria.Graphics.Capture.CaptureCamera._Capture(), Terraria.Projectile.AI(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_WeatherVane(), Terraria.GameContent.Drawing.NextHorizonRenderer.BlendColorAlongGradientBasedOnHeight(), Terraria.Graphics.Light.LegacyLighting.CopyFullyProcessedDataOver(), ReLogic.Peripherals.RGB.Corsair.CorsairHelper.CreateFragment(), Terraria.Main.DrawBlack(), Terraria.Main.DrawProjDirect(), Newtonsoft.Json.JsonValidatingReader.FloatingPointRemainder(), Terraria.Graphics.Capture.CaptureInterface.FullScreenArea(), Terraria.Main.GetAreaToLight(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor2(), System.Globalization.PersianCalendar.GetDatePart(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), System.Globalization.CalendricalCalculationsHelper.GetGregorianYear(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetPosition(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Terraria.Physics.BallCollision.GetTileBounds(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Graphics.Shaders.MiscShaderData.IsPowerOfTwo(), NVorbis.Codebook.lookup1_values(), System.Globalization.CalendricalCalculationsHelper.PersianNewYearOnOrBefore(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.TimeLogger.DataSeries.Quantile(), System.Globalization.CalendricalCalculationsHelper.Reminder(), Terraria.Graphics.Light.LegacyLighting.ShiftUnProcessedDataOver(), Terraria.Collision.StepDown(), Terraria.GameContent.Shaders.WaterShaderData.StepLiquids(), NVorbis.Floor0.SynthesizeBarkCurve(), and Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight().