Terraria Decompiled: System.Math.Ceiling
Ceiling() [1/2]
static decimal System.Math.Ceiling (decimal d) inline static
Definition at line 126 of file Math.cs.
        {
            return decimal.Ceiling(d);
        }
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_066_TryInterceptingTarget(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.Deserialize_SyncEveryone(), Terraria.Main.DrawBackground_DrawMagmaLayer(), Terraria.Main.DrawDefenseCounter(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.UI.ChestUI.DrawSlots(), Terraria.Main.DrawUnderworldBackgroundLayer(), Terraria.Main.FakeLoadInvasionStart(), Terraria.Utils.FloodFillTile(), Terraria.Graphics.Capture.CaptureInterface.FullScreenArea(), Terraria.Projectile.GasTrapCheck(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.GenerateHallway(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetGridParameters(), Terraria.Main.GetInfoAccIconPosition(), Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), Terraria.DataStructures.TileReachCheckSettings.GetTileRegion(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Graphics.Shaders.MiscShaderData.IsPowerOfTwo(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.UI.BannerClaimingUI.NavigatePipsGrid(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.OnPlayerJoining(), Terraria.Graphics.Renderers.StormLightningParticle.Prepare(), Terraria.GameContent.UI.NPCChatPanel.PrepareInteractions(), Terraria.TimeLogger.DataSeries.Quantile(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), Terraria.Collision.SolidFullTiles(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.Stairwell(), Terraria.Physics.BallCollision.Step(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.UpdateSize(), and Terraria.WorldGen.WavyCaverer().