Terraria Decompiled: System.Math.Abs
Abs() [7/7]
static short System.Math.Abs (short value) inline static
Definition at line 13 of file Math.cs.
        {
            if (value < 0)
            {
                value = -value;
                if (value < 0)
                {
                    Math.ThrowAbsOverflow();
                }
            }
            return value;
        }
References System.Math.ThrowAbsOverflow(), and System.value.
Referenced by System.MathF.Abs(), System.Numerics.Vector< T >.Abs(), Terraria.WorldGen.AddPasses(), Terraria.Collision.AdvancedTileCollision(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.AdvanceTargetPosition(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_FindGoodRestingSpot(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_IsInAGoodRestingSpot(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_015_HandleMovementCollision(), Terraria.Projectile.AI_015_HandleMovementCollision_Old(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_047_MagnetSphere(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_053_HandleSentryNPCTargeting(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_1_Counterweights(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_105_SporeSac(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_119_Dandelion(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.NPC.AI_124_DeerclopsLeg(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.NPC.AI_126_StatueMimic(), Terraria.Projectile.AI_130_FlameBurstTower_FindTarget(), Terraria.Projectile.AI_134_Ballista_FindTarget(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_148_StarSpawner(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_153_ToiletPop(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_163_Chum(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_174_MultisegmentPet(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_204_Digtoise(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.Projectile.AI_AdjustPlayerItemRotationToFaceProjectile(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks(), Terraria.Main.Ambience(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_WeatherVane(), Terraria.Collision.AnyWallOfTypeOnLine(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), Terraria.SceneState.ApplyVisuals(), Newtonsoft.Json.Utilities.MathUtils.ApproxEquals(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Utils.BounceEaseOut(), Terraria.Collision.BuildTileContacts(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformAndDoorsOnHallway(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.GameContent.Biomes.DungeonControlLine.CanPaint(), Terraria.NPC.Spawner.CanSpawnDevourer(), Terraria.Player.CanSpawnWalkingEffects(), Terraria.Player.CarpetMovement(), Terraria.Mount.CastSuperCartLaser(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.ChasmRunner(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.WorldGen.Check3x3(), Terraria.Collision.CheckAABBvLineCollision(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckOrb(), Terraria.Mount.ClampToDeadZone(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.NPC.Collision_MoveSlopesAndStairFall(), Terraria.Player.CommandForbiddenStorm(), Newtonsoft.Json.Linq.JValue.CompareBigInteger(), Microsoft.Xna.Framework.Curve.ComputeTangent(), Terraria.Utils.ConstrainedToPointInRectangle(), Terraria.WorldGen.Convert(), Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.CreateOutlines(), Terraria.Graphics.Renderers.MapHeadRenderer.CreateOutlines(), Terraria.WorldGen.CrimEnt(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.CrimVein(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.digTunnel(), Terraria.WorldGen.DirtyRockRunner(), Microsoft.Xna.Framework.MathHelper.Distance(), Terraria.GameContent.EmergencyStacking.DistanceBetween(), Terraria.Collision.DistFromSeg(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere(), Terraria.Player.DoDeadCellsBeheadedParticles(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.Mount.DoSteamMinecartEffect(), Terraria.Main.DoUpdate(), Terraria.Utilities.NPCUtils.SearchFilters.DownwindFromNPC(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DragBounds(), Terraria.Mount.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.UI.BannerClaimingUI.DrawBannersList(), Terraria.Utils.DrawCursorSingle(), Terraria.TimeLogger.DrawDelta(), Terraria.Main.DrawDust(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.Main.DrawInfernoRings(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawItem(), Terraria.Main.DrawKite(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.Main.DrawProj_FishingLine(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProjDirect(), Terraria.UI.CraftingUI.DrawRecipesList(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Terraria.Main.DrawSunAndMoon(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Main.DrawWithOutlines(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion(), Terraria.GameContent.Golf.GolfHelper.ContactListener.EmitGolfballExplosion_v1(), Terraria.Graphics.Renderers.FakeFishParticle.EmitWaterPulse(), FullSerializer.fsData.Equals(), System.Globalization.CalendricalCalculationsHelper.EquationOfTime(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.Projectile.ExplodeTiles(), Terraria.Player.FindClosest(), Terraria.NPC.FindFrame(), Terraria.WorldItem.FindOwner(), Terraria.Player.FindPulley(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindTiles(), Terraria.GameContent.Golf.GolfHelper.FindVectorOnOval(), Terraria.WorldGen.FloatingIsland(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateDungeonSquareHall(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.GenerateHallway(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothemsInArea(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.WorldGen.GERunner(), Terraria.Graphics.Capture.CaptureInterface.GetArea(), Terraria.Player.GetAutoDoorVelocityContribution(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoiseInternal(), Terraria.Player.GetFarthestSpawnPositionOnLine(), Terraria.UI.BannerClaimingUI.GetItemSlotColors(), Terraria.UI.CraftingUI.GetItemSlotColors(), Terraria.Mount.GetMinecartMechPoint(), Terraria.GameContent.Drawing.HorizonHelper.GetMoonStrength(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetMoonStrength(), Terraria.WorldSections.GetNextMapDraw(), Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), Terraria.GameInput.SmartSelectGamepadPointer.GetPointerPosition(), Terraria.Player.GetRespawnTime(), Terraria.Projectile.GetScarabBombDigDirectionSnap8(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.Projectile.ghostHurt(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Gore.Gore_UpdateSail(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowSpike(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.GameContent.Events.Sandstorm.HasSufficientWind(), Terraria.WorldGen.HellHouse(), ReLogic.Utilities.Vector2D.Hermite(), Terraria.NPC.HitEffect(), Terraria.Collision.HitLine(), Terraria.Collision.HitLineWall(), Terraria.Player.HorizontalMovement(), Terraria.Mount.Hover(), System.Math.IEEERemainder(), Terraria.GameContent.UI.WorldUIAnchor.InRange(), Microsoft.Xna.Framework.Ray.Intersects(), Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid(), Terraria.GameContent.Biomes.DungeonControlLine.IsSelfIntersecting(), Terraria.GameContent.UI.Minimap.MinimapFrame.Button.IsTouchingPoint(), Newtonsoft.Json.JsonValidatingReader.IsZero(), Terraria.Player.ItemCheck_Shoot(), Terraria.Mount.JumpHeight(), Terraria.Mount.JumpSpeed(), Terraria.Projectile.KiteLogic(), Terraria.WorldGen.Lakinater(), Terraria.Collision.LaserScan(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate(), Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes(), Terraria.Projectile.MakeBoulderOfEarthExplosion(), Terraria.Player.MakeFloorDust(), Terraria.Rain.MakeRain(), Terraria.Wiring.MassWireOperationInner(), Terraria.WorldGen.mayanTrap(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), Terraria.WorldGen.meteor(), Terraria.Player.MoonLeechRope(), Terraria.WorldGen.Mountinater(), Terraria.WorldItem.MoveInWorld(), Terraria.WorldGen.MudWallRunner(), Terraria.WorldGen.neonMossBiome(), Terraria.NPC.NPCLoot_DropMoney(), Terraria.WorldGen.oceanCave(), Terraria.Main.oldDrawWater(), Terraria.Collision.OneDimensionalIntersection(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnMoved(), FullSerializer.fsData.operator==(), Terraria.WorldGen.OreRunner(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings(), Terraria.GameContent.Generation.ShapeRunner.Perform(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.DunesBiome.PlaceCurvedLine(), Terraria.WorldGen.PlaceOasis(), Terraria.GameContent.Biomes.DunesBiome.PlaceSingle(), Microsoft.Xna.Framework.Media.VideoPlayerAV1.Play(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.Play(), Terraria.Player.PlayerFrame(), Terraria.Utils.PlotLine(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.Projectile.RainbowBoulder_CheckBounce(), System.Random.Random(), NVorbis.Floor1.RenderLineMulti(), NVorbis.Floor1.RenderPoint(), Terraria.Mount.ResetFlightTime(), Terraria.Player.RollerSkateMovement(), System.Math.Round(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway(), Terraria.WorldGen.ScoreRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreStairwell(), Terraria.WorldGen.SeaOatWaterCheck(), Terraria.StrayMethods.SendWalker(), Terraria.Player.SetArmorEffectVisuals(), Terraria.Utilities.UnifiedRandom.SetSeed(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.NPC.Spawner.ShouldSpawnInvasionEnemies(), Terraria.Projectile.ShouldWallExplode(), Terraria.WorldGen.ShroomPatch(), Terraria.WorldGen.SkyblockIsland(), Terraria.Collision.SlopeCollision(), Terraria.Player.SlopingCollision(), Terraria.Player.SmartSelectLookup(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Main.snowing(), Terraria.WorldGen.SonOfLakinater(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_Digestion(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.Star.SpawnStars(), Terraria.Projectile.SpawnWebs(), Terraria.WorldGen.SpiderWallRemover(), Terraria.DelegateMethods.SpreadTile(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.Stairwell(), Terraria.Star.StarFall(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Collision.StepConveyorBelt(), Terraria.Player.StickyMovement(), Terraria.Collision.StickyTiles(), Terraria.NPC.StreamUpdatesToNearbyPlayers(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TileRunner(), Terraria.Minecart.TrackCollision(), Terraria.IO.WorldFileData.TranslateSeed(), Terraria.Player.TryBouncingBlocks(), Terraria.WorldItem.TryCombiningIntoNearbyItems(), System.Buffers.Text.Utf8Formatter.TryFormat(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.Mount.TryPettingMount(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryStartJump(), Terraria.NPC.TryTrackingTarget(), Terraria.Map.WorldMap.UnlockMapTilePretty(), Terraria.GameContent.Drawing.TileDrawing.Update(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.Update(), Terraria.Gore.Update(), Terraria.UI.Gamepad.UILinkPointNavigator.Update(), Terraria.GameContent.LeashedEntities.LeashedKite.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Mount.UpdateAfterEquips(), Terraria.Main.UpdateAudio(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.GameContent.Drawing.TileDrawing.UpdateLeafFrequency(), Terraria.NPC.UpdateNPC(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.NPC.UpdateNPC_CritterSounds(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UpdateOffsetDown(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.UpdateSliderAndShowMultiplierMouseOver(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing(), Terraria.Star.UpdateStars(), Terraria.Player.UpdateTouchingTiles(), Terraria.GameContent.Skies.AmbientSky.ButterfliesSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.LostKiteSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.PegasusSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.VultureSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.PixiePosseSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.BirdsPackSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.WyvernSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.AirshipSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.AirBalloonSkyEntity.UpdateVelocity(), Terraria.Main.UpdateWeather(), Terraria.Main.UpdateWindyDayState(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), Terraria.Collision.WalkDownSlope(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants(), Microsoft.Xna.Framework.MathHelper.WithinEpsilon(), Newtonsoft.Json.Utilities.DateTimeUtils.WriteDateTimeOffset(), and Terraria.Player.Yoraiz0rEye().