Terraria Decompiled: System.Math.Sign
Sign() [1/7]
static int System.Math.Sign (decimal value) inline static
Definition at line 747 of file Math.cs.
        {
            return decimal.Sign(ref value);
        }
References System.value.
Referenced by Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.AdvanceTargetPosition(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_100_Medusa(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.NPC.AI_124_DeerclopsLeg(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.Projectile.AI_130_FlameBurstTower(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_134_Ballista(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_156_BatOfLight(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_194_HorsemanPumpkin(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_WeatherVane(), Terraria.Collision.AnyWallOfTypeOnLine(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms(), Terraria.Collision.CanHitLine(), Terraria.Player.CanParryAgainst(), Terraria.Player.CanSnapToPosition(), Terraria.Mount.CastSuperCartLaser(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ChasePlayerTop(), Terraria.Projectile.Colliding(), System.Threading.Timer.TimerComparer.Compare(), Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.Projectile.CutTiles(), Terraria.Player.DashMovement(), Microsoft.Xna.Framework.Matrix.Decompose(), Terraria.Main.DoScrollingInInventory(), Terraria.Mount.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawNPCExtras(), Terraria.Main.DrawProjDirect(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Mount.EmitGolfCartSmoke(), Terraria.Graphics.Renderers.FakeFishParticle.EmitWaterPulse(), Terraria.NPC.FindFrame(), Terraria.Player.GetAutoDoorVelocityContribution(), Terraria.Player.GetGrapplingForces(), Terraria.Mount.GetMinecartMechPoint(), Terraria.GameContent.DoorOpeningHelper.GetPlayerInfoForOpeningDoor(), Terraria.WorldGen.GrowPalmTree(), Terraria.Projectile.HandleMovement(), Terraria.Initializers.UILinksInitializer.HandleSliderHorizontalInput(), Terraria.Initializers.UILinksInitializer.HandleSliderVerticalInput(), Terraria.Collision.HitLine(), Terraria.Collision.HitLineWall(), Terraria.Player.HorizontalMovement(), System.Math.IEEERemainder(), System.Globalization.CalendricalCalculationsHelper.IsNegative(), Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate(), Terraria.Wiring.MassWireOperationInner(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move(), Terraria.Utils.MoveTowards(), Terraria.Player.PetAnimal(), Terraria.Player.RollerSkateMovement(), System.Math.Round(), Terraria.GameContent.Drawing.WindGrid.ScanPlayer(), Terraria.Graphics.Renderers.FakeFishParticle.SetAndGetLatchDetails(), System.MathF.Sign(), System.Math.Sign(), System.Math.Sign(), Terraria.Main.snowing(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Collision.StepConveyorBelt(), Terraria.Player.TileInteractionsUse(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryGetReachableTile(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryStartJump(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Update(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.Player.UpdatePettingAnimal(), Terraria.GameContent.Events.Sandstorm.UpdateSeverity(), Terraria.Player.UpdateTouchingTiles(), Terraria.GameContent.Skies.AmbientSky.SeagullsGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.GastropodGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.SlimeBalloonGroupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.HellBatsGoupSkyEntity.UpdateVelocity(), Terraria.GameContent.Skies.AmbientSky.BatsGroupSkyEntity.UpdateVelocity(), Terraria.Main.UpdateWeather(), and Terraria.Player.Yoraiz0rEye().