Terraria Decompiled: System.Math.Sin
Sin()
static double System.Math.Sin (double a)
Referenced by Terraria.WorldGen.AddPasses(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_075(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_166_Dove(), Terraria.Projectile.AI_196_Petal(), Terraria.Graphics.Light.TileLightScanner.ApplyHellLight(), Terraria.Utils.BounceEaseOut(), NVorbis.Mode.CalcWindows(), Microsoft.Xna.Framework.Matrix.CreateFromAxisAngle(), Microsoft.Xna.Framework.Quaternion.CreateFromAxisAngle(), Microsoft.Xna.Framework.Quaternion.CreateFromYawPitchRoll(), Microsoft.Xna.Framework.Matrix.CreateRotationX(), Microsoft.Xna.Framework.Matrix.CreateRotationY(), Microsoft.Xna.Framework.Matrix.CreateRotationZ(), Terraria.GameContent.Generation.ShapeRoot.DoRoot(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.Main.DrawDefenseCounter(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawGlowRing(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawKite(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.Main.DrawMenu(), Terraria.Main.DrawMurderAurora(), Terraria.Utils.DrawNotificationIcon(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawNPCPortrait(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_25_Shield(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Main.DrawSmartCursor(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.PopupText.EmitFancyFlashDust(), Terraria.Graphics.TileBatch.FillVertexBuffer(), Terraria.Projectile.GetAlpha(), Terraria.Player.GetBackHandPosition(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.GetBobbingOffset(), Terraria.Player.GetFrontHandPosition(), Terraria.WorldGen.GetRainbowPaintIDForPosition(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterOpacity(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerWave(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.GameContent.Skies.MartianSky.ZipBehavior.InitializeUfo(), Terraria.Projectile.KiteLogic(), NVorbis.Mdct.MdctImpl.MdctImpl(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.GameContent.RGB.BrainShader.ProcessHighDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.DesertShader.ProcessHighDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessHighDetail(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.GameContent.RGB.PillarShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenBeeShader.ProcessHighDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail(), Terraria.GameContent.RGB.BrainShader.ProcessLowDetail(), Terraria.GameContent.RGB.CavernShader.ProcessLowDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessLowDetail(), Terraria.GameContent.RGB.DeathShader.ProcessLowDetail(), Terraria.GameContent.RGB.DrippingShader.ProcessLowDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessLowDetail(), Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessLowDetail(), Terraria.GameContent.RGB.GolemShader.ProcessLowDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessLowDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessLowDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessLowDetail(), Terraria.GameContent.RGB.PillarShader.ProcessLowDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessLowDetail(), Terraria.GameContent.RGB.PlanteraShader.ProcessLowDetail(), Terraria.GameContent.RGB.QueenBeeShader.ProcessLowDetail(), Terraria.GameContent.RGB.SkullShader.ProcessLowDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessLowDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessLowDetail(), Terraria.GameContent.RGB.UndergroundHallowShader.ProcessLowDetail(), Terraria.GameContent.RGB.UndergroundMushroomShader.ProcessLowDetail(), Terraria.GameContent.RGB.UnderworldShader.ProcessLowDetail(), Terraria.GameContent.RGB.WormShader.ProcessLowDetail(), Terraria.DataStructures.SpriteDrawBuffer.QueueSprite(), Terraria.Utils.RotatedBy(), Terraria.Utils.RotatedBy(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway(), Terraria.GameContent.Generation.ShapeBranch.ShapeBranch(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), System.Globalization.CalendricalCalculationsHelper.SinOfDegree(), Microsoft.Xna.Framework.Quaternion.Slerp(), Terraria.Utils.ToRotationVector2(), Terraria.Utils.ToRotationVector2D(), Terraria.UI.Gamepad.GamepadMainMenuHandler.Update(), Terraria.GameContent.RGB.EyeballShader.Update(), Terraria.GameContent.Skies.LanternSky.Update(), Terraria.Projectile.Update(), Terraria.Dust.UpdateDust(), ReLogic.Peripherals.RGB.RgbKey.UpdateFlashingEffect(), Terraria.GameContent.UI.States.UIWorldLoad.UpdateGamepadSquiggle(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing(), Terraria.Main.UpdateTime(), Terraria.Mount.UseDrill(), Terraria.GameContent.Golf.GolfHelper.ValidateShot(), and Terraria.WorldGen.WavyCaverer().