Terraria Decompiled: Terraria.GameContent.UI.EmoteBubble.MakeLocalPlayerEmote
MakeLocalPlayerEmote()
static void Terraria.GameContent.UI.EmoteBubble.MakeLocalPlayerEmote (int emoteId) inline static
Definition at line 282 of file EmoteBubble.cs.
        {
            if (Main.netMode != 2 && Main.LocalPlayer.dead)
            {
                return;
            }
            if (Main.netMode == 0)
            {
                EmoteBubble.NewBubble(emoteId, new WorldUIAnchor(Main.LocalPlayer), 360);
                EmoteBubble.CheckForNPCsToReactToEmoteBubble(emoteId, Main.LocalPlayer);
                return;
            }
            NetMessage.SendData(120, -1, -1, null, Main.myPlayer, (float)emoteId, 0f, 0f, 0, 0, 0);
        }
References Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble(), Terraria.Player.dead, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.GameContent.UI.EmoteBubble.NewBubble(), and Terraria.NetMessage.SendData().
Referenced by Terraria.GameContent.UI.Elements.EmoteButton.LeftClick(), Terraria.GameContent.LucyAxeMessage.SpawnEmoteBubble(), Terraria.Player.UpdateHungerBuffs(), and Terraria.Player.UpdateStarvingState().