Terraria Decompiled: Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble
CheckForNPCsToReactToEmoteBubble()
static void Terraria.GameContent.UI.EmoteBubble.CheckForNPCsToReactToEmoteBubble (int emoteID, Player player) inline static
Definition at line 135 of file EmoteBubble.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc != null && npc.active && npc.aiStyle == 7 && npc.townNPC && npc.ai[0] < 2f && ((player.CanBeTalkedTo && player.Distance(npc.Center) < 200f) || !Collision.CanHitLine(npc.Top, 0, 0, player.Top, 0, 0)))
                {
                    int num = (npc.position.X < player.position.X).ToDirectionInt();
                    npc.ai[0] = 19f;
                    npc.ai[1] = 220f;
                    npc.ai[2] = (float)player.whoAmI;
                    npc.direction = num;
                    npc.netUpdate = true;
                }
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.NPC.aiStyle, Terraria.Player.CanBeTalkedTo, Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Entity.Distance(), Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Entity.position, Terraria.Entity.Top, Terraria.NPC.townNPC, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.GameContent.UI.EmoteBubble.MakeLocalPlayerEmote(), Terraria.Chat.Commands.EmojiCommand.ProcessOutgoingMessage(), and Terraria.Chat.Commands.RockPaperScissorsCommand.ProcessOutgoingMessage().