Terraria Decompiled: Terraria.GameContent.LeashedEntity.DrawEntities
DrawEntities()
static void Terraria.GameContent.LeashedEntity.DrawEntities () inline static
Definition at line 274 of file LeashedEntity.cs.
        {
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            Rectangle rectangle = new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth, Main.screenHeight);
            rectangle.Inflate(512, 512);
            foreach (LeashedEntity.SectionEntityList sectionEntityList in LeashedEntity.ActiveSectionList)
            {
                LeashedEntity[] list = sectionEntityList.list;
                int count = sectionEntityList.count;
                for (int i = 0; i < count; i++)
                {
                    LeashedEntity leashedEntity = list[i];
                    if (leashedEntity != null && rectangle.Contains(leashedEntity.Center.ToPoint()))
                    {
                        leashedEntity.Draw();
                    }
                }
            }
            TimeLogger.LeashedEntities.AddTime(startTimestamp);
        }
References Terraria.GameContent.LeashedEntity.ActiveSectionList, Terraria.GameContent.LeashedEntity.Center, Microsoft.Xna.Framework.Rectangle.Contains(), System.count, Terraria.GameContent.LeashedEntity.Draw(), Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.TimeLogger.LeashedEntities, System.list, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.TimeLogger.Start(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawNPCs().