Terraria Decompiled: Terraria.GameContent.LeashedEntity.RecheckActiveSections
RecheckActiveSections()
static void Terraria.GameContent.LeashedEntity.RecheckActiveSections () inline static private
Definition at line 209 of file LeashedEntity.cs.
        {
            int num = 0;
            for (int i = 0; i < LeashedEntity.ActiveSectionList.Count; i++)
            {
                LeashedEntity.SectionEntityList sectionEntityList = LeashedEntity.ActiveSectionList[i];
                sectionEntityList.CompactIfNecesary();
                if (!ActiveSections.IsSectionActive(sectionEntityList.coordinates))
                {
                    sectionEntityList.Deactivate();
                }
                else
                {
                    LeashedEntity.ActiveSectionList[num++] = sectionEntityList;
                }
            }
            LeashedEntity.ActiveSectionList.RemoveRange(num, LeashedEntity.ActiveSectionList.Count - num);
        }
References Terraria.GameContent.LeashedEntity.ActiveSectionList, Terraria.GameContent.LeashedEntity.SectionEntityList.CompactIfNecesary(), Terraria.GameContent.LeashedEntity.SectionEntityList.coordinates, Terraria.GameContent.LeashedEntity.SectionEntityList.Deactivate(), and Terraria.DataStructures.ActiveSections.IsSectionActive().
Referenced by Terraria.GameContent.LeashedEntity.UpdateEntities().