Terraria Decompiled: Terraria.GameContent.LeashedEntity.AddNewEntity
AddNewEntity() [2/2]
static void Terraria.GameContent.LeashedEntity.AddNewEntity (LeashedEntity e, Point16 anchorPos, int slot) inline static private
Definition at line 144 of file LeashedEntity.cs.
        {
            e.AnchorPosition = anchorPos;
            e.active = true;
            e.whoAmI = slot;
            LeashedEntity.ByWhoAmI[slot] = e;
            LeashedEntity.SectionEntityList section = LeashedEntity.GetSection(e.SectionCoordinates);
            section.Add(e);
            if (Main.netMode != 1 && section.active)
            {
                e.Spawn(true);
            }
            if (Main.netMode == 2)
            {
                LeashedEntity.NetModule.Sync(e, true, -1);
            }
        }
References Terraria.GameContent.LeashedEntity.SectionEntityList.active, Terraria.GameContent.LeashedEntity.SectionEntityList.Add(), Terraria.GameContent.LeashedEntity.ByWhoAmI, Terraria.GameContent.LeashedEntity.GetSection(), Terraria.Main.netMode, Terraria.GameContent.LeashedEntity.SectionCoordinates, Terraria.GameContent.LeashedEntity.Spawn(), and Terraria.GameContent.LeashedEntity.NetModule.Sync().