Terraria Decompiled: Terraria.GameContent.LeashedEntity.Remove
Remove()
static void Terraria.GameContent.LeashedEntity.Remove (LeashedEntity e) inline static private
Definition at line 174 of file LeashedEntity.cs.
        {
            e.active = false;
            LeashedEntity.ByWhoAmI[e.whoAmI] = null;
            while (LeashedEntity.ByWhoAmI.Count > 0 && LeashedEntity.ByWhoAmI[LeashedEntity.ByWhoAmI.Count - 1] == null)
            {
                LeashedEntity.ByWhoAmI.RemoveAt(LeashedEntity.ByWhoAmI.Count - 1);
            }
            LeashedEntity.GetSection(e.SectionCoordinates).Remove(e);
            if (Main.netMode == 2)
            {
                LeashedEntity.NetModule.Remove(e.whoAmI);
            }
        }
References Terraria.GameContent.LeashedEntity.ByWhoAmI, Terraria.GameContent.LeashedEntity.GetSection(), Terraria.Main.netMode, Terraria.GameContent.LeashedEntity.NetModule.Remove(), Terraria.GameContent.LeashedEntity.Remove(), Terraria.GameContent.LeashedEntity.SectionCoordinates, and Terraria.GameContent.LeashedEntity.whoAmI.
Referenced by Terraria.GameContent.LeashedEntity._UpdateEntities(), Terraria.GameContent.LeashedEntity.NetModule.HandleRemove(), and Terraria.GameContent.LeashedEntity.Remove().