Terraria Decompiled: FullSerializer.fsBaseConverter.DeserializeMember< T >
DeserializeMember< T >()
fsResult FullSerializer.fsBaseConverter.DeserializeMember< T > (Dictionary< string, fsData > data, Type overrideConverterType, string name, out T value) inline protected
Definition at line 116 of file fsBaseConverter.cs.
        {
            fsData fsData;
            if (!data.TryGetValue(name, ref fsData))
            {
                value = default(T);
                return fsResult.Fail("Unable to find member \"" + name + "\"");
            }
            object obj = null;
            fsResult fsResult = this.Serializer.TryDeserialize(fsData, typeof(T), overrideConverterType, ref obj);
            value = (T)((object)obj);
            return fsResult;
        }
References FullSerializer.fsResult.Fail(), System.name, System.obj, FullSerializer.fsBaseConverter.Serializer, System.T, FullSerializer.fsSerializer.TryDeserialize(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and System.value.