Terraria Decompiled: System.Reflection.Emit.ConstructorOnTypeBuilderInst.GetParametersInternal
GetParametersInternal()
override ParameterInfo[] System.Reflection.Emit.ConstructorOnTypeBuilderInst.GetParametersInternal () inline package virtual
Reimplemented from System.Reflection.MethodBase.
Definition at line 93 of file ConstructorOnTypeBuilderInst.cs.
        {
            ParameterInfo[] array;
            if (this.cb is ConstructorBuilder)
            {
                ConstructorBuilder constructorBuilder = (ConstructorBuilder)this.cb;
                array = new ParameterInfo[constructorBuilder.parameters.Length];
                for (int i = 0; i < constructorBuilder.parameters.Length; i++)
                {
                    Type type = this.instantiation.InflateType(constructorBuilder.parameters[i]);
                    ParameterInfo[] array2 = array;
                    int num = i;
                    ParameterBuilder[] pinfo = constructorBuilder.pinfo;
                    array2[num] = RuntimeParameterInfo.New((pinfo != null) ? pinfo[i] : null, type, this, i + 1);
                }
            }
            else
            {
                ParameterInfo[] parameters = this.cb.GetParameters();
                array = new ParameterInfo[parameters.Length];
                for (int j = 0; j < parameters.Length; j++)
                {
                    Type type2 = this.instantiation.InflateType(parameters[j].ParameterType);
                    array[j] = RuntimeParameterInfo.New(parameters[j], type2, this, j + 1);
                }
            }
            return array;
        }
References System.array, System.Reflection.Emit.ConstructorOnTypeBuilderInst.cb, System.Reflection.MethodBase.GetParameters(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), System.Reflection.Emit.ConstructorOnTypeBuilderInst.instantiation, System.Reflection.RuntimeParameterInfo.New(), System.Reflection.Emit.ConstructorBuilder.parameters, and System.Reflection.Emit.ConstructorBuilder.pinfo.
Referenced by System.Reflection.Emit.ConstructorOnTypeBuilderInst.GetParameters().