Terraria Decompiled: Terraria.GameContent.AmbientWindSystem.SpawnFloorCloud
SpawnFloorCloud()
void Terraria.GameContent.AmbientWindSystem.SpawnFloorCloud (int x, int y) inline private
Definition at line 139 of file AmbientWindSystem.cs.
        {
            Vector2 vector = new Point(x, y - 1).ToWorldCoordinates(8f, 8f);
            int num = this._random.Next(1087, 1090);
            float num2 = 16f * this._random.NextFloat();
            vector.Y -= num2;
            if (num2 < 4f)
            {
                num = 1090;
            }
            float num3 = 0.4f;
            float num4 = 0.8f + this._random.NextFloat() * 0.2f;
            Gore.NewGorePerfect(vector, Vector2.UnitX * num3 * Main.WindForVisuals, num, num4);
        }
References Terraria.GameContent.AmbientWindSystem._random, Terraria.Gore.NewGorePerfect(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.UnitX, and Terraria.Main.WindForVisuals.
Referenced by Terraria.GameContent.AmbientWindSystem.TrySpawningWind().