Terraria Decompiled: Terraria.GameContent.AmbientWindSystem.TestAirCloud
TestAirCloud()
void Terraria.GameContent.AmbientWindSystem.TestAirCloud (int x, int y) inline private
Definition at line 155 of file AmbientWindSystem.cs.
        {
            if (this._random.Next(120000) != 0)
            {
                return;
            }
            for (int i = -2; i <= 2; i++)
            {
                if (i != 0)
                {
                    Tile tile = Main.tile[x + i, y];
                    if (!this.DoesTileAllowWind(tile))
                    {
                        return;
                    }
                    tile = Main.tile[x, y + i];
                    if (!this.DoesTileAllowWind(tile))
                    {
                        return;
                    }
                }
            }
            this._spotsForAirboneWind.Add(new Point(x, y));
        }
References Terraria.GameContent.AmbientWindSystem._random, Terraria.GameContent.AmbientWindSystem._spotsForAirboneWind, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.AmbientWindSystem.DoesTileAllowWind(), Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.tile.
Referenced by Terraria.GameContent.AmbientWindSystem.TrySpawningWind().