Terraria Decompiled: Terraria.GameContent.AmbientWindSystem.SpawnAirborneCloud
SpawnAirborneCloud()
void Terraria.GameContent.AmbientWindSystem.SpawnAirborneCloud (int x, int y) inline private
Definition at line 93 of file AmbientWindSystem.cs.
        {
            int num = this._random.Next(2, 6);
            float num2 = 1.1f;
            float num3 = 2.2f;
            float num4 = 0.023561945f * this._random.NextFloatDirection();
            float num5 = 0.023561945f * this._random.NextFloatDirection();
            while (num5 > -0.011780973f && num5 < 0.011780973f)
            {
                num5 = 0.023561945f * this._random.NextFloatDirection();
            }
            if (this._random.Next(4) == 0)
            {
                num = this._random.Next(9, 16);
                num2 = 1.1f;
                num3 = 1.2f;
            }
            else if (this._random.Next(4) == 0)
            {
                num = this._random.Next(9, 16);
                num2 = 1.1f;
                num3 = 0.2f;
            }
            Vector2 vector = new Vector2(-10f, 0f);
            Vector2 vector2 = new Point(x, y).ToWorldCoordinates(8f, 8f);
            num4 -= num5 * (float)num * 0.5f;
            float num6 = num4;
            for (int i = 0; i < num; i++)
            {
                if (Main.rand.Next(10) == 0)
                {
                    num5 *= this._random.NextFloatDirection();
                }
                Vector2 vector3 = this._random.NextVector2Circular(4f, 4f);
                int num7 = 1091 + this._random.Next(2) * 2;
                float num8 = 1.4f;
                float num9 = num2 + this._random.NextFloat() * num3;
                float num10 = num6 + num5;
                Vector2 vector4 = Vector2.UnitX.RotatedBy((double)num10, default(Vector2)) * num8;
                Gore.NewGorePerfect(vector2 + vector3 - vector, vector4 * Main.WindForVisuals, num7, num9);
                vector2 += vector4 * 6.5f * num9;
                num6 = num10;
            }
        }
References Terraria.GameContent.AmbientWindSystem._random, Terraria.Gore.NewGorePerfect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Microsoft.Xna.Framework.Vector2.UnitX, and Terraria.Main.WindForVisuals.
Referenced by Terraria.GameContent.AmbientWindSystem.SpawnAirborneWind().