Terraria Decompiled: System.ApplicationId.Equals
Equals()
override bool System.ApplicationId.Equals (object o) inline
Definition at line 155 of file ApplicationId.cs.
        {
            ApplicationId applicationId = o as ApplicationId;
            if (applicationId == null)
            {
                return false;
            }
            if (!object.Equals(this.Name, applicationId.Name) || !object.Equals(this.Version, applicationId.Version) || !object.Equals(this.ProcessorArchitecture, applicationId.ProcessorArchitecture) || !object.Equals(this.Culture, applicationId.Culture))
            {
                return false;
            }
            if (this._publicKeyToken.Length != applicationId._publicKeyToken.Length)
            {
                return false;
            }
            for (int i = 0; i < this._publicKeyToken.Length; i++)
            {
                if (this._publicKeyToken[i] != applicationId._publicKeyToken[i])
                {
                    return false;
                }
            }
            return true;
        }
References System.ApplicationId._publicKeyToken, System.ApplicationId.ApplicationId(), System.ApplicationId.Culture, System.ApplicationId.Equals(), System.ApplicationId.Name, System.ApplicationId.ProcessorArchitecture, and System.ApplicationId.Version.
Referenced by System.ApplicationId.Equals().