Terraria Decompiled: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.Return
Return()
override void System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Return (T[] array, bool clearArray = false) inline
Definition at line 100 of file TlsOverPerCoreLockedStacksArrayPool.cs.
        {
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            int num = Utilities.SelectBucketIndex(array.Length);
            if (num < this._buckets.Length)
            {
                if (clearArray)
                {
                    Array.Clear(array, 0, array.Length);
                }
                if (array.Length != this._bucketArraySizes[num])
                {
                    throw new ArgumentException("The buffer is not associated with this pool and may not be returned to it.", "array");
                }
                T[][] array2 = TlsOverPerCoreLockedStacksArrayPool<T>.t_tlsBuckets;
                if (array2 == null)
                {
                    array2 = (TlsOverPerCoreLockedStacksArrayPool<T>.t_tlsBuckets = new T[17][]);
                    array2[num] = array;
                    if (TlsOverPerCoreLockedStacksArrayPool<T>.s_trimBuffers)
                    {
                        TlsOverPerCoreLockedStacksArrayPool<T>.s_allTlsBuckets.Add(array2, null);
                        if (Interlocked.Exchange(ref this._callbackCreated, 1) != 1)
{
                            Gen2GcCallback.Register(new Func<object, bool>(TlsOverPerCoreLockedStacksArrayPool<T>.Gen2GcCallbackFunc), this);
                        }
                    }
                }
                else
                {
                    T[] array3 = array2[num];
                    array2[num] = array;
                    if (array3 != null)
                    {
                        (this._buckets[num] ?? this.CreatePerCoreLockedStacks(num)).TryPush(array3);
                    }
                }
            }
            ArrayPoolEventSource log = ArrayPoolEventSource.Log;
            if (log.IsEnabled())
            {
                log.BufferReturned(array.GetHashCode(), array.Length, this.Id);
            }
        }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._buckets, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Add(), System.array, System.Buffers.ArrayPoolEventSource.BufferReturned(), System.Array.Clear(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.CreatePerCoreLockedStacks(), System.Threading.Interlocked.Exchange(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Gen2GcCallbackFunc(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Id, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Buffers.ArrayPoolEventSource.Log, System.Gen2GcCallback.Register(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.s_allTlsBuckets, System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.s_trimBuffers, System.Buffers.Utilities.SelectBucketIndex(), and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.t_tlsBuckets.