Terraria Decompiled: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.Rent
Rent()
override T[] System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Rent (int minimumLength) inline
Definition at line 41 of file TlsOverPerCoreLockedStacksArrayPool.cs.
        {
            if (minimumLength < 0)
            {
                throw new ArgumentOutOfRangeException("minimumLength");
            }
            if (minimumLength == 0)
            {
                return Array.Empty<T>();
            }
            ArrayPoolEventSource log = ArrayPoolEventSource.Log;
            int num = Utilities.SelectBucketIndex(minimumLength);
            T[] array2;
            if (num < this._buckets.Length)
            {
                T[][] array = TlsOverPerCoreLockedStacksArrayPool<T>.t_tlsBuckets;
                if (array != null)
                {
                    array2 = array[num];
                    if (array2 != null)
                    {
                        array[num] = null;
                        if (log.IsEnabled())
{
                            log.BufferRented(array2.GetHashCode(), array2.Length, this.Id, num);
                        }
                        return array2;
                    }
                }
                TlsOverPerCoreLockedStacksArrayPool<T>.PerCoreLockedStacks perCoreLockedStacks = this._buckets[num];
                if (perCoreLockedStacks != null)
                {
                    array2 = perCoreLockedStacks.TryPop();
                    if (array2 != null)
                    {
                        if (log.IsEnabled())
{
                            log.BufferRented(array2.GetHashCode(), array2.Length, this.Id, num);
                        }
                        return array2;
                    }
                }
                array2 = new T[this._bucketArraySizes[num]];
            }
            else
            {
                array2 = new T[minimumLength];
            }
            if (log.IsEnabled())
            {
                int hashCode = array2.GetHashCode();
                int num2 = -1;
                log.BufferRented(hashCode, array2.Length, this.Id, num2);
                log.BufferAllocated(hashCode, array2.Length, this.Id, num2, (num >= this._buckets.Length) ? ArrayPoolEventSource.BufferAllocatedReason.OverMaximumSize : ArrayPoolEventSource.BufferAllocatedReason.PoolExhausted);
            }
            return array2;
        }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._bucketArraySizes, System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >._buckets, System.array, System.Buffers.ArrayPoolEventSource.BufferAllocated(), System.Buffers.ArrayPoolEventSource.BufferRented(), System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.Id, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Buffers.ArrayPoolEventSource.Log, System.Buffers.Utilities.SelectBucketIndex(), and System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.t_tlsBuckets.