Terraria Decompiled: System.TimeZoneInfo.ConvertTime
ConvertTime() [4/5]
static DateTime System.TimeZoneInfo.ConvertTime (DateTime dateTime, TimeZoneInfo sourceTimeZone, TimeZoneInfo destinationTimeZone, TimeZoneInfoOptions flags, TimeZoneInfo::CachedData cachedData) inline static private
Definition at line 1516 of file TimeZoneInfo.cs.
        {
            if (sourceTimeZone == null)
            {
                throw new ArgumentNullException("sourceTimeZone");
            }
            if (destinationTimeZone == null)
            {
                throw new ArgumentNullException("destinationTimeZone");
            }
            DateTimeKind correspondingKind = cachedData.GetCorrespondingKind(sourceTimeZone);
            if ((flags & TimeZoneInfoOptions.NoThrowOnInvalidTime) == (TimeZoneInfoOptions)0 && dateTime.Kind != DateTimeKind.Unspecified && dateTime.Kind != correspondingKind)
            {
                throw new ArgumentException("The conversion could not be completed because the supplied DateTime did not have the Kind property set correctly.  For example, when the Kind property is DateTimeKind.Local, the source time zone must be TimeZoneInfo.Local.", "sourceTimeZone");
            }
            int? num;
            TimeZoneInfo.AdjustmentRule adjustmentRuleForTime = sourceTimeZone.GetAdjustmentRuleForTime(dateTime, out num);
            TimeSpan timeSpan = sourceTimeZone.BaseUtcOffset;
            if (adjustmentRuleForTime != null)
            {
                timeSpan += adjustmentRuleForTime.BaseUtcOffsetDelta;
                if (adjustmentRuleForTime.HasDaylightSaving)
                {
                    DaylightTimeStruct daylightTime = sourceTimeZone.GetDaylightTime(dateTime.Year, adjustmentRuleForTime, num);
                    if ((flags & TimeZoneInfoOptions.NoThrowOnInvalidTime) == (TimeZoneInfoOptions)0 && TimeZoneInfo.GetIsInvalidTime(dateTime, adjustmentRuleForTime, daylightTime))
                    {
                        throw new ArgumentException("The supplied DateTime represents an invalid time.  For example, when the clock is adjusted forward, any time in the period that is skipped is invalid.", "dateTime");
                    }
                    bool isDaylightSavings = TimeZoneInfo.GetIsDaylightSavings(dateTime, adjustmentRuleForTime, daylightTime, flags);
                    timeSpan += (isDaylightSavings ? adjustmentRuleForTime.DaylightDelta : TimeSpan.Zero);
                }
            }
            DateTimeKind correspondingKind2 = cachedData.GetCorrespondingKind(destinationTimeZone);
            if (dateTime.Kind != DateTimeKind.Unspecified && correspondingKind != DateTimeKind.Unspecified && correspondingKind == correspondingKind2)
            {
                return dateTime;
            }
            bool flag;
            DateTime dateTime2 = TimeZoneInfo.ConvertUtcToTimeZone(dateTime.Ticks - timeSpan.Ticks, destinationTimeZone, out flag);
            if (correspondingKind2 == DateTimeKind.Local)
            {
                return new DateTime(dateTime2.Ticks, DateTimeKind.Local, flag);
            }
            return new DateTime(dateTime2.Ticks, correspondingKind2);
        }
References System.TimeZoneInfo.BaseUtcOffset, System.TimeZoneInfo.AdjustmentRule.BaseUtcOffsetDelta, System.TimeZoneInfo.ConvertUtcToTimeZone(), System.DateTime, System.TimeZoneInfo.GetAdjustmentRuleForTime(), System.TimeZoneInfo.GetDaylightTime(), System.TimeZoneInfo.GetIsDaylightSavings(), System.TimeZoneInfo.GetIsInvalidTime(), System.TimeZoneInfo.AdjustmentRule.HasDaylightSaving, System.DateTime.Kind, System.DateTime.Ticks, System.TimeSpan.Ticks, System.DateTime.Year, and System.TimeSpan.Zero.