Terraria Decompiled: System.TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat
TZif_CreateAdjustmentRuleForPosixFormat()
static TimeZoneInfo.AdjustmentRule System.TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat (string posixFormat, DateTime startTransitionDate, TimeSpan timeZoneBaseUtcOffset) inline static private
Definition at line 705 of file TimeZoneInfo.cs.
        {
            string text;
            string text2;
            string text3;
            string text4;
            string text5;
            string text6;
            string text7;
            string text8;
            if (TimeZoneInfo.TZif_ParsePosixFormat(posixFormat, out text, out text2, out text3, out text4, out text5, out text6, out text7, out text8))
            {
                TimeSpan? timeSpan = TimeZoneInfo.TZif_ParseOffsetString(text2);
                if (timeSpan != null)
                {
                    TimeSpan timeSpan2 = timeSpan.Value.Negate();
                    timeSpan2 = TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(timeSpan2, timeZoneBaseUtcOffset);
                    if (!string.IsNullOrEmpty(text3))
                    {
                        TimeSpan? timeSpan3 = TimeZoneInfo.TZif_ParseOffsetString(text4);
                        TimeSpan timeSpan4;
                        if (timeSpan3 == null)
{
                            timeSpan4 = new TimeSpan(1, 0, 0);
                        }
                        else
{
                            timeSpan4 = timeSpan3.Value.Negate();
                            timeSpan4 = TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(timeSpan4, timeZoneBaseUtcOffset);
                            timeSpan4 = TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(timeSpan4, timeSpan2);
                        }
                        TimeZoneInfo.TransitionTime transitionTime = TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule(text5, text6);
                        TimeZoneInfo.TransitionTime transitionTime2 = TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule(text7, text8);
                        return TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(startTransitionDate, DateTime.MaxValue, timeSpan4, transitionTime, transitionTime2, timeSpan2, false);
                    }
                    return TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(startTransitionDate, DateTime.MaxValue, TimeSpan.Zero, default(TimeZoneInfo.TransitionTime), default(TimeZoneInfo.TransitionTime), timeSpan2, true);
                }
            }
            return null;
        }
References System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.DateTime.MaxValue, System.TimeSpan.Negate(), System.text, System.TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(), System.TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule(), System.TimeZoneInfo.TZif_ParseOffsetString(), System.TimeZoneInfo.TZif_ParsePosixFormat(), and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.TZif_GenerateAdjustmentRule().