Terraria Decompiled: System.TimeZoneInfo.TZif_ParsePosixFormat
TZif_ParsePosixFormat()
static bool System.TimeZoneInfo.TZif_ParsePosixFormat (string posixFormat, out string standardName, out string standardOffset, out string daylightSavingsName, out string daylightSavingsOffset, out string start, out string startTime, out string end, out string endTime) inline static private
Definition at line 885 of file TimeZoneInfo.cs.
        {
            standardName = null;
            standardOffset = null;
            daylightSavingsName = null;
            daylightSavingsOffset = null;
            start = null;
            startTime = null;
            end = null;
            endTime = null;
            int num = 0;
            standardName = TimeZoneInfo.TZif_ParsePosixName(posixFormat, ref num);
            standardOffset = TimeZoneInfo.TZif_ParsePosixOffset(posixFormat, ref num);
            daylightSavingsName = TimeZoneInfo.TZif_ParsePosixName(posixFormat, ref num);
            if (!string.IsNullOrEmpty(daylightSavingsName))
            {
                daylightSavingsOffset = TimeZoneInfo.TZif_ParsePosixOffset(posixFormat, ref num);
                if (num < posixFormat.Length && posixFormat[num] == ',')
                {
                    num++;
                    TimeZoneInfo.TZif_ParsePosixDateTime(posixFormat, ref num, out start, out startTime);
                    if (num < posixFormat.Length && posixFormat[num] == ',')
                    {
                        num++;
                        TimeZoneInfo.TZif_ParsePosixDateTime(posixFormat, ref num, out end, out endTime);
                    }
                }
            }
            return !string.IsNullOrEmpty(standardName) && !string.IsNullOrEmpty(standardOffset);
        }
References System.start, System.TimeZoneInfo.TZif_ParsePosixDateTime(), System.TimeZoneInfo.TZif_ParsePosixName(), and System.TimeZoneInfo.TZif_ParsePosixOffset().
Referenced by System.TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat().