Terraria Decompiled: System.TimeZoneInfo.GetUtcOffset
GetUtcOffset() [4/6]
static TimeSpan System.TimeZoneInfo.GetUtcOffset (DateTime time, TimeZoneInfo zone, TimeZoneInfoOptions flags) inline static private
Definition at line 2247 of file TimeZoneInfo.cs.
        {
            TimeSpan timeSpan = zone.BaseUtcOffset;
            int? num;
            TimeZoneInfo.AdjustmentRule adjustmentRuleForTime = zone.GetAdjustmentRuleForTime(time, out num);
            if (adjustmentRuleForTime != null)
            {
                timeSpan += adjustmentRuleForTime.BaseUtcOffsetDelta;
                if (adjustmentRuleForTime.HasDaylightSaving)
                {
                    DaylightTimeStruct daylightTime = zone.GetDaylightTime(time.Year, adjustmentRuleForTime, num);
                    bool isDaylightSavings = TimeZoneInfo.GetIsDaylightSavings(time, adjustmentRuleForTime, daylightTime, flags);
                    timeSpan += (isDaylightSavings ? adjustmentRuleForTime.DaylightDelta : TimeSpan.Zero);
                }
            }
            return timeSpan;
        }
References System.TimeZoneInfo.BaseUtcOffset, System.TimeZoneInfo.AdjustmentRule.BaseUtcOffsetDelta, System.TimeZoneInfo.GetAdjustmentRuleForTime(), System.TimeZoneInfo.GetDaylightTime(), System.TimeZoneInfo.GetIsDaylightSavings(), System.TimeZoneInfo.AdjustmentRule.HasDaylightSaving, System.DateTime.Year, and System.TimeSpan.Zero.