Terraria Decompiled: System.TimeZoneInfo.GetIsAmbiguousTime
GetIsAmbiguousTime()
static bool System.TimeZoneInfo.GetIsAmbiguousTime (DateTime time, TimeZoneInfo::AdjustmentRule rule, DaylightTimeStruct daylightTime) inline static private
Definition at line 2135 of file TimeZoneInfo.cs.
        {
            bool flag = false;
            if (rule == null || rule.DaylightDelta == TimeSpan.Zero)
            {
                return flag;
            }
            DateTime dateTime;
            DateTime dateTime2;
            if (rule.DaylightDelta > TimeSpan.Zero)
            {
                if (rule.IsEndDateMarkerForEndOfYear())
                {
                    return false;
                }
                dateTime = daylightTime.End;
                dateTime2 = daylightTime.End - rule.DaylightDelta;
            }
            else
            {
                if (rule.IsStartDateMarkerForBeginningOfYear())
                {
                    return false;
                }
                dateTime = daylightTime.Start;
                dateTime2 = daylightTime.Start + rule.DaylightDelta;
            }
            flag = time >= dateTime2 && time < dateTime;
            if (!flag && dateTime.Year != dateTime2.Year)
            {
                try
                {
                    DateTime dateTime3 = dateTime.AddYears(1);
                    DateTime dateTime4 = dateTime2.AddYears(1);
                    flag = time >= dateTime4 && time < dateTime3;
                }
                catch (ArgumentOutOfRangeException)
                {
                }
                if (!flag)
                {
                    try
                    {
                        DateTime dateTime3 = dateTime.AddYears(-1);
                        DateTime dateTime4 = dateTime2.AddYears(-1);
                        flag = time >= dateTime4 && time < dateTime3;
                    }
                    catch (ArgumentOutOfRangeException)
                    {
                    }
                }
            }
            return flag;
        }
References System.DateTime.AddYears(), System.Globalization.DaylightTimeStruct.End, System.Globalization.DaylightTimeStruct.Start, System.DateTime.Year, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetIsDaylightSavings(), and System.TimeZoneInfo.IsAmbiguousTime().