Terraria Decompiled: System.TimeZoneInfo.GetIsDaylightSavingsFromUtc
GetIsDaylightSavingsFromUtc()
static bool System.TimeZoneInfo.GetIsDaylightSavingsFromUtc (DateTime time, int year, TimeSpan utc, TimeZoneInfo::AdjustmentRule rule, int? ruleIndex, out bool isAmbiguousLocalDst, TimeZoneInfo zone) inline static private
Definition at line 2006 of file TimeZoneInfo.cs.
        {
            isAmbiguousLocalDst = false;
            if (rule == null)
            {
                return false;
            }
            DaylightTimeStruct daylightTime = zone.GetDaylightTime(year, rule, ruleIndex);
            bool flag = false;
            TimeSpan daylightSavingsStartOffsetFromUtc = zone.GetDaylightSavingsStartOffsetFromUtc(utc, rule, ruleIndex);
            DateTime dateTime;
            if (rule.IsStartDateMarkerForBeginningOfYear() && daylightTime.Start.Year > DateTime.MinValue.Year)
            {
                int? num;
                TimeZoneInfo.AdjustmentRule adjustmentRuleForTime = zone.GetAdjustmentRuleForTime(new DateTime(daylightTime.Start.Year - 1, 12, 31), out num);
                if (adjustmentRuleForTime != null && adjustmentRuleForTime.IsEndDateMarkerForEndOfYear())
                {
                    dateTime = zone.GetDaylightTime(daylightTime.Start.Year - 1, adjustmentRuleForTime, num).Start - utc - adjustmentRuleForTime.BaseUtcOffsetDelta;
                    flag = true;
                }
                else
                {
                    dateTime = new DateTime(daylightTime.Start.Year, 1, 1, 0, 0, 0) - daylightSavingsStartOffsetFromUtc;
                }
            }
            else
            {
                dateTime = daylightTime.Start - daylightSavingsStartOffsetFromUtc;
            }
            TimeSpan daylightSavingsEndOffsetFromUtc = zone.GetDaylightSavingsEndOffsetFromUtc(utc, rule);
            DateTime dateTime2;
            if (rule.IsEndDateMarkerForEndOfYear() && daylightTime.End.Year < DateTime.MaxValue.Year)
            {
                int? num2;
                TimeZoneInfo.AdjustmentRule adjustmentRuleForTime2 = zone.GetAdjustmentRuleForTime(new DateTime(daylightTime.End.Year + 1, 1, 1), out num2);
                if (adjustmentRuleForTime2 != null && adjustmentRuleForTime2.IsStartDateMarkerForBeginningOfYear())
                {
                    if (adjustmentRuleForTime2.IsEndDateMarkerForEndOfYear())
                    {
                        dateTime2 = new DateTime(daylightTime.End.Year + 1, 12, 31) - utc - adjustmentRuleForTime2.BaseUtcOffsetDelta - adjustmentRuleForTime2.DaylightDelta;
                    }
                    else
                    {
                        dateTime2 = zone.GetDaylightTime(daylightTime.End.Year + 1, adjustmentRuleForTime2, num2).End - utc - adjustmentRuleForTime2.BaseUtcOffsetDelta - adjustmentRuleForTime2.DaylightDelta;
                    }
                    flag = true;
                }
                else
                {
                    dateTime2 = new DateTime(daylightTime.End.Year + 1, 1, 1, 0, 0, 0).AddTicks(-1L) - daylightSavingsEndOffsetFromUtc;
                }
            }
            else
            {
                dateTime2 = daylightTime.End - daylightSavingsEndOffsetFromUtc;
            }
            DateTime dateTime3;
            DateTime dateTime4;
            if (daylightTime.Delta.Ticks > 0L)
            {
                dateTime3 = dateTime2 - daylightTime.Delta;
                dateTime4 = dateTime2;
            }
            else
            {
                dateTime3 = dateTime;
                dateTime4 = dateTime - daylightTime.Delta;
            }
            bool flag2 = TimeZoneInfo.CheckIsDst(dateTime, time, dateTime2, flag, rule);
            if (flag2)
            {
                isAmbiguousLocalDst = time >= dateTime3 && time < dateTime4;
                if (!isAmbiguousLocalDst && dateTime3.Year != dateTime4.Year)
                {
                    try
                    {
                        dateTime3.AddYears(1);
                        dateTime4.AddYears(1);
                        isAmbiguousLocalDst = time >= dateTime3 && time < dateTime4;
                    }
                    catch (ArgumentOutOfRangeException)
                    {
                    }
                    if (!isAmbiguousLocalDst)
                    {
                        try
{
                            dateTime3.AddYears(-1);
                            dateTime4.AddYears(-1);
                            isAmbiguousLocalDst = time >= dateTime3 && time < dateTime4;
                        }
                        catch (ArgumentOutOfRangeException)
{
                        }
                    }
                }
            }
            return flag2;
        }
References System.DateTime.AddTicks(), System.DateTime.AddYears(), System.TimeZoneInfo.AdjustmentRule.BaseUtcOffsetDelta, System.TimeZoneInfo.CheckIsDst(), System.DateTime, System.TimeZoneInfo.AdjustmentRule.DaylightDelta, System.Globalization.DaylightTimeStruct.Delta, System.Globalization.DaylightTimeStruct.End, System.TimeZoneInfo.GetAdjustmentRuleForTime(), System.TimeZoneInfo.GetDaylightSavingsEndOffsetFromUtc(), System.TimeZoneInfo.GetDaylightSavingsStartOffsetFromUtc(), System.TimeZoneInfo.GetDaylightTime(), System.TimeZoneInfo.AdjustmentRule.IsEndDateMarkerForEndOfYear(), System.TimeZoneInfo.AdjustmentRule.IsStartDateMarkerForBeginningOfYear(), System.L, System.DateTime.MaxValue, System.DateTime.MinValue, System.Globalization.DaylightTimeStruct.Start, System.TimeSpan.Ticks, and System.DateTime.Year.
Referenced by System.TimeZoneInfo.GetUtcOffsetFromUtc().