Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.GenerateEarlyDungeonFeaturesInRoom
GenerateEarlyDungeonFeaturesInRoom()
override void Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.GenerateEarlyDungeonFeaturesInRoom (DungeonData data) inline virtual
Reimplemented from Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.
Definition at line 42 of file BiomeStructuredDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            BiomeDungeonRoomSettings biomeDungeonRoomSettings = (BiomeDungeonRoomSettings)this.settings;
            byte style = this.settings.StyleData.Style;
            int x = this.InnerBounds.Center.X;
            int y = this.InnerBounds.Center.Y;
            float width = (float)this.InnerBounds.Width;
            int height = this.InnerBounds.Height;
            int bottom = this.InnerBounds.Bottom;
            int num = (int)(width * 0.25f);
            int num2 = unifiedRandom.Next(2);
            if (num2 == 1 && !biomeDungeonRoomSettings.StyleData.CanGenerateFeatureAt(data, this, null, x, y))
            {
                num2 = 0;
            }
            if (num2 == 0 || num2 != 1)
            {
                DungeonWindowBasicSettings dungeonWindowBasicSettings = new DungeonWindowBasicSettings
                {
                    Style = this.settings.StyleData,
                    Width = 9,
                    Height = height / 5,
                    Closed = (unifiedRandom.Next(3) != 0)
                };
                new DungeonWindowBasic(dungeonWindowBasicSettings).GenerateFeature(data, x, y);
                dungeonWindowBasicSettings.Width = 7;
                dungeonWindowBasicSettings.Height = height / 5 - 4;
                new DungeonWindowBasic(dungeonWindowBasicSettings).GenerateFeature(data, x - num, y + 3);
                new DungeonWindowBasic(dungeonWindowBasicSettings).GenerateFeature(data, x + num, y + 3);
                return;
            }
            int num3 = 4;
            DungeonPillarSettings dungeonPillarSettings = new DungeonPillarSettings();
            dungeonPillarSettings.Style = this.settings.StyleData;
            dungeonPillarSettings.OverridePaintTile = this.settings.OverridePaintTile;
            dungeonPillarSettings.OverridePaintWall = this.settings.OverridePaintWall;
            dungeonPillarSettings.PillarType = PillarType.BlockActuatedSolidTop;
            dungeonPillarSettings.Width = 10;
            dungeonPillarSettings.Height = bottom - y + 5;
            dungeonPillarSettings.CrowningOnTop = true;
            dungeonPillarSettings.CrowningOnBottom = false;
            dungeonPillarSettings.CrowningStopsAtPillar = true;
            dungeonPillarSettings.AlwaysPlaceEntirePillar = false;
            new DungeonPillar(dungeonPillarSettings).GenerateFeature(data, x + 1, bottom + num3);
            dungeonPillarSettings.Width = 7;
            dungeonPillarSettings.Height = bottom - y;
            new DungeonPillar(dungeonPillarSettings).GenerateFeature(data, x - num + 1, bottom + num3);
            new DungeonPillar(dungeonPillarSettings).GenerateFeature(data, x + num, bottom + num3);
        }
References Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.CanGenerateFeatureAt(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Height, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Width, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.