Terraria Decompiled: System.TimeZoneInfo.ValidateTimeZoneInfo
ValidateTimeZoneInfo()
static void System.TimeZoneInfo.ValidateTimeZoneInfo (string id, TimeSpan baseUtcOffset, TimeZoneInfo::AdjustmentRule[] adjustmentRules, out bool adjustmentRulesSupportDst) inline static private
Definition at line 2412 of file TimeZoneInfo.cs.
        {
            if (id == null)
            {
                throw new ArgumentNullException("id");
            }
            if (id.Length == 0)
            {
                throw new ArgumentException(SR.Format("The specified ID parameter '{0}' is not supported.", id), "id");
            }
            if (TimeZoneInfo.UtcOffsetOutOfRange(baseUtcOffset))
            {
                throw new ArgumentOutOfRangeException("baseUtcOffset", "The TimeSpan parameter must be within plus or minus 14.0 hours.");
            }
            if (baseUtcOffset.Ticks % 600000000L != 0L)
            {
                throw new ArgumentException("The TimeSpan parameter cannot be specified more precisely than whole minutes.", "baseUtcOffset");
            }
            adjustmentRulesSupportDst = false;
            if (adjustmentRules != null && adjustmentRules.Length != 0)
            {
                adjustmentRulesSupportDst = true;
                TimeZoneInfo.AdjustmentRule adjustmentRule = null;
                for (int i = 0; i < adjustmentRules.Length; i++)
                {
                    TimeZoneInfo.AdjustmentRule adjustmentRule2 = adjustmentRule;
                    adjustmentRule = adjustmentRules[i];
                    if (adjustmentRule == null)
                    {
                        throw new InvalidTimeZoneException("The AdjustmentRule array cannot contain null elements.");
                    }
                    if (!TimeZoneInfo.IsValidAdjustmentRuleOffest(baseUtcOffset, adjustmentRule))
                    {
                        throw new InvalidTimeZoneException("The sum of the BaseUtcOffset and DaylightDelta properties must within plus or minus 14.0 hours.");
                    }
                    if (adjustmentRule2 != null && adjustmentRule.DateStart <= adjustmentRule2.DateEnd)
                    {
                        throw new InvalidTimeZoneException("The elements of the AdjustmentRule array must be in chronological order and must not overlap.");
                    }
                }
            }
        }
References System.TimeZoneInfo.AdjustmentRule.DateEnd, System.TimeZoneInfo.AdjustmentRule.DateStart, SR.Format(), System.TimeZoneInfo.IsValidAdjustmentRuleOffest(), System.L, System.TimeSpan.Ticks, and System.TimeZoneInfo.UtcOffsetOutOfRange().
Referenced by System.TimeZoneInfo.OnDeserialization(), System.TimeZoneInfo.TimeZoneInfo(), and System.TimeZoneInfo.TimeZoneInfo().