Terraria Decompiled: System.TimeZoneInfo.FindSystemTimeZoneById
FindSystemTimeZoneById()
static TimeZoneInfo System.TimeZoneInfo.FindSystemTimeZoneById (string id) inline static
Definition at line 534 of file TimeZoneInfo.cs.
        {
            if (string.Equals(id, "UTC", StringComparison.OrdinalIgnoreCase))
            {
                return TimeZoneInfo.Utc;
            }
            if (id == null)
            {
                throw new ArgumentNullException("id");
            }
            if (id.Length == 0 || id.Contains('\0'))
            {
                throw new TimeZoneNotFoundException(SR.Format("The time zone ID '{0}' was not found on the local computer.", id));
            }
            TimeZoneInfo.CachedData cachedData = TimeZoneInfo.s_cachedData;
            TimeZoneInfo.CachedData cachedData2 = cachedData;
            TimeZoneInfo timeZoneInfo;
            Exception ex;
            TimeZoneInfo.TimeZoneInfoResult timeZoneInfoResult;
            lock (cachedData2)
            {
                timeZoneInfoResult = TimeZoneInfo.TryGetTimeZone(id, false, out timeZoneInfo, out ex, cachedData, true);
            }
            if (timeZoneInfoResult == TimeZoneInfo.TimeZoneInfoResult.Success)
            {
                return timeZoneInfo;
            }
            if (timeZoneInfoResult == TimeZoneInfo.TimeZoneInfoResult.InvalidTimeZoneException)
            {
                throw ex;
            }
            if (timeZoneInfoResult == TimeZoneInfo.TimeZoneInfoResult.SecurityException)
            {
                throw new SecurityException(SR.Format("The time zone ID '{0}' was found on the local computer, but the application does not have permission to read the file.", id), ex);
            }
            throw new TimeZoneNotFoundException(SR.Format("The time zone ID '{0}' was not found on the local computer.", id), ex);
        }
References SR.Format(), System.TimeZoneInfo.s_cachedData, System.TimeZoneInfo.TryGetTimeZone(), and System.TimeZoneInfo.Utc.
Referenced by System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), and System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId().