Terraria Decompiled: System.TimeZoneInfo.IsDaylightSavingTime
IsDaylightSavingTime() [3/4]
bool System.TimeZoneInfo.IsDaylightSavingTime (DateTime dateTime, TimeZoneInfoOptions flags, TimeZoneInfo::CachedData cachedData) inline private
Definition at line 1377 of file TimeZoneInfo.cs.
        {
            if (!this._supportsDaylightSavingTime || this._adjustmentRules == null)
            {
                return false;
            }
            DateTime dateTime2;
            if (dateTime.Kind == DateTimeKind.Local)
            {
                dateTime2 = TimeZoneInfo.ConvertTime(dateTime, cachedData.Local, this, flags, cachedData);
            }
            else if (dateTime.Kind == DateTimeKind.Utc)
            {
                if (cachedData.GetCorrespondingKind(this) == DateTimeKind.Utc)
                {
                    return false;
                }
                bool flag;
                TimeZoneInfo.GetUtcOffsetFromUtc(dateTime, this, out flag);
                return flag;
            }
            else
            {
                dateTime2 = dateTime;
            }
            int? num;
            TimeZoneInfo.AdjustmentRule adjustmentRuleForTime = this.GetAdjustmentRuleForTime(dateTime2, out num);
            if (adjustmentRuleForTime != null && adjustmentRuleForTime.HasDaylightSaving)
            {
                DaylightTimeStruct daylightTime = this.GetDaylightTime(dateTime2.Year, adjustmentRuleForTime, num);
                return TimeZoneInfo.GetIsDaylightSavings(dateTime2, adjustmentRuleForTime, daylightTime, flags);
            }
            return false;
        }
References System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.GetIsDaylightSavings(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.TimeZoneInfo.AdjustmentRule.HasDaylightSaving, System.DateTime.Kind, and System.DateTime.Year.