Terraria Decompiled: System.TimeZoneInfo.ConvertTime
ConvertTime() [5/5]
static DateTimeOffset System.TimeZoneInfo.ConvertTime (DateTimeOffset dateTimeOffset, TimeZoneInfo destinationTimeZone) inline static
Definition at line 1467 of file TimeZoneInfo.cs.
        {
            if (destinationTimeZone == null)
            {
                throw new ArgumentNullException("destinationTimeZone");
            }
            DateTime utcDateTime = dateTimeOffset.UtcDateTime;
            TimeSpan utcOffsetFromUtc = TimeZoneInfo.GetUtcOffsetFromUtc(utcDateTime, destinationTimeZone);
            long num = utcDateTime.Ticks + utcOffsetFromUtc.Ticks;
            if (num > DateTimeOffset.MaxValue.Ticks)
            {
                return DateTimeOffset.MaxValue;
            }
            if (num >= DateTimeOffset.MinValue.Ticks)
            {
                return new DateTimeOffset(num, utcOffsetFromUtc);
            }
            return DateTimeOffset.MinValue;
        }
References System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.DateTimeOffset.MaxValue, System.DateTimeOffset.MinValue, System.DateTimeOffset.Ticks, System.TimeSpan.Ticks, and System.DateTimeOffset.UtcDateTime.
Referenced by System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), System.TimeZoneInfo.ConvertTimeBySystemTimeZoneId(), System.TimeZoneInfo.ConvertTimeFromUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.ConvertTimeToUtc(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetAmbiguousTimeOffsets(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.IsAmbiguousTime(), System.TimeZoneInfo.IsAmbiguousTime(), and System.TimeZoneInfo.IsDaylightSavingTime().