Terraria Decompiled: System.TimeZoneInfo.TryGetTimeZone
TryGetTimeZone()
static TimeZoneInfo.TimeZoneInfoResult System.TimeZoneInfo.TryGetTimeZone (string id, bool dstDisabled, out TimeZoneInfo value, out Exception e, TimeZoneInfo::CachedData cachedData, bool alwaysFallbackToLocalMachine = false) inline static private
Definition at line 2358 of file TimeZoneInfo.cs.
        {
            TimeZoneInfo.TimeZoneInfoResult timeZoneInfoResult = TimeZoneInfo.TimeZoneInfoResult.Success;
            e = null;
            TimeZoneInfo timeZoneInfo = null;
            if (cachedData._systemTimeZones != null && cachedData._systemTimeZones.TryGetValue(id, out timeZoneInfo))
            {
                if (dstDisabled && timeZoneInfo._supportsDaylightSavingTime)
                {
                    value = TimeZoneInfo.CreateCustomTimeZone(timeZoneInfo._id, timeZoneInfo._baseUtcOffset, timeZoneInfo._displayName, timeZoneInfo._standardDisplayName);
                }
                else
                {
                    value = new TimeZoneInfo(timeZoneInfo._id, timeZoneInfo._baseUtcOffset, timeZoneInfo._displayName, timeZoneInfo._standardDisplayName, timeZoneInfo._daylightDisplayName, timeZoneInfo._adjustmentRules, false);
                }
                return timeZoneInfoResult;
            }
            if (!cachedData._allSystemTimeZonesRead || alwaysFallbackToLocalMachine)
            {
                timeZoneInfoResult = TimeZoneInfo.TryGetTimeZoneFromLocalMachine(id, dstDisabled, out value, out e, cachedData);
            }
            else
            {
                timeZoneInfoResult = TimeZoneInfo.TimeZoneInfoResult.TimeZoneNotFoundException;
                value = null;
            }
            return timeZoneInfoResult;
        }
References System.TimeZoneInfo._adjustmentRules, System.TimeZoneInfo._baseUtcOffset, System.TimeZoneInfo._daylightDisplayName, System.TimeZoneInfo._displayName, System.TimeZoneInfo._id, System.TimeZoneInfo._standardDisplayName, System.TimeZoneInfo._supportsDaylightSavingTime, System.TimeZoneInfo.CreateCustomTimeZone(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), and System.value.
Referenced by System.TimeZoneInfo.FindSystemTimeZoneById(), and System.TimeZoneInfo.PopulateAllSystemTimeZones().