Terraria Decompiled: System.TimeZoneInfo.GetTimeZoneIds
GetTimeZoneIds()
static List< string > System.TimeZoneInfo.GetTimeZoneIds (string timeZoneDirectory) inline static private
Definition at line 155 of file TimeZoneInfo.cs.
        {
            List<string> list = new List<string>();
            try
            {
                using (StreamReader streamReader = new StreamReader(Path.Combine(timeZoneDirectory, "zone.tab"), Encoding.UTF8))
                {
                    string text;
                    while ((text = streamReader.ReadLine()) != null)
                    {
                        if (!string.IsNullOrEmpty(text) && text[0] != '#')
{
                            int num = text.IndexOf('\t');
                            if (num != -1)
{
                                int num2 = text.IndexOf('\t', num + 1);
                                if (num2 != -1)
{
                                    int num3 = num2 + 1;
                                    int num4 = text.IndexOf('\t', num3);
                                    string text2;
                                    if (num4 != -1)
{
                                        int num5 = num4 - num3;
                                        text2 = text.Substring(num3, num5);
                                    }
                                    else
{
                                        text2 = text.Substring(num3);
                                    }
                                    if (!string.IsNullOrEmpty(text2))
{
                                        list.Add(text2);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
            return list;
        }
References System.IO.Path.Combine(), System.list, System.IO.StreamReader.ReadLine(), System.text, and System.Text.Encoding.UTF8.
Referenced by System.TimeZoneInfo.PopulateAllSystemTimeZones().