Terraria Decompiled: System.TimeZoneInfo.CheckIsDst
CheckIsDst()
static bool System.TimeZoneInfo.CheckIsDst (DateTime startTime, DateTime time, DateTime endTime, bool ignoreYearAdjustment, TimeZoneInfo::AdjustmentRule rule) inline static private
Definition at line 2107 of file TimeZoneInfo.cs.
        {
            if (!ignoreYearAdjustment && !rule.NoDaylightTransitions)
            {
                int year = startTime.Year;
                int year2 = endTime.Year;
                if (year != year2)
                {
                    endTime = endTime.AddYears(year - year2);
                }
                int year3 = time.Year;
                if (year != year3)
                {
                    time = time.AddYears(year - year3);
                }
            }
            if (startTime > endTime)
            {
                return time < endTime || time >= startTime;
            }
            if (rule.NoDaylightTransitions)
            {
                return time >= startTime && time <= endTime;
            }
            return time >= startTime && time < endTime;
        }
References System.DateTime.AddYears(), and System.DateTime.Year.
Referenced by System.TimeZoneInfo.GetIsDaylightSavings(), and System.TimeZoneInfo.GetIsDaylightSavingsFromUtc().