Terraria Decompiled: System.TimeZoneInfo.TryLoadTzFile
TryLoadTzFile()
static bool System.TimeZoneInfo.TryLoadTzFile (string tzFilePath, ref byte[] rawData, ref string id) inline static private
Definition at line 243 of file TimeZoneInfo.cs.
        {
            if (File.Exists(tzFilePath))
            {
                try
                {
                    rawData = File.ReadAllBytes(tzFilePath);
                    if (string.IsNullOrEmpty(id))
                    {
                        id = TimeZoneInfo.FindTimeZoneIdUsingReadLink(tzFilePath);
                        if (string.IsNullOrEmpty(id))
{
                            id = TimeZoneInfo.FindTimeZoneId(rawData);
                        }
                    }
                    return true;
                }
                catch (IOException)
                {
                }
                catch (SecurityException)
                {
                }
                catch (UnauthorizedAccessException)
                {
                }
                return false;
            }
            return false;
        }
References System.IO.File.Exists(), System.TimeZoneInfo.FindTimeZoneId(), System.TimeZoneInfo.FindTimeZoneIdUsingReadLink(), and System.IO.File.ReadAllBytes().
Referenced by System.TimeZoneInfo.TryGetLocalTzFile().