Terraria Decompiled: System.TimeZoneInfo.TimeZoneInfo
TimeZoneInfo() [1/4]
System.TimeZoneInfo.TimeZoneInfo (byte[] data, string id, bool dstDisabled) inline private
Definition at line 20 of file TimeZoneInfo.cs.
        {
            TimeZoneInfo.TZifHead tzifHead;
            DateTime[] array;
            byte[] array2;
            TimeZoneInfo.TZifType[] array3;
            string text;
            bool[] array4;
            bool[] array5;
            string text2;
            TimeZoneInfo.TZif_ParseRaw(data, out tzifHead, out array, out array2, out array3, out text, out array4, out array5, out text2);
            this._id = id;
            this._displayName = "Local";
            this._baseUtcOffset = TimeSpan.Zero;
            DateTime utcNow = DateTime.UtcNow;
            int num = 0;
            while (num < array.Length && array[num] <= utcNow)
            {
                int num2 = (int)array2[num];
                if (!array3[num2].IsDst)
                {
                    this._baseUtcOffset = array3[num2].UtcOffset;
                    this._standardDisplayName = TimeZoneInfo.TZif_GetZoneAbbreviation(text, (int)array3[num2].AbbreviationIndex);
                }
                else
                {
                    this._daylightDisplayName = TimeZoneInfo.TZif_GetZoneAbbreviation(text, (int)array3[num2].AbbreviationIndex);
                }
                num++;
            }
            if (array.Length == 0)
            {
                for (int i = 0; i < array3.Length; i++)
                {
                    if (!array3[i].IsDst)
                    {
                        this._baseUtcOffset = array3[i].UtcOffset;
                        this._standardDisplayName = TimeZoneInfo.TZif_GetZoneAbbreviation(text, (int)array3[i].AbbreviationIndex);
                    }
                    else
                    {
                        this._daylightDisplayName = TimeZoneInfo.TZif_GetZoneAbbreviation(text, (int)array3[i].AbbreviationIndex);
                    }
                }
            }
            this._displayName = this._standardDisplayName;
            if (this._baseUtcOffset.Ticks % 600000000L != 0L)
            {
                this._baseUtcOffset = new TimeSpan(this._baseUtcOffset.Hours, this._baseUtcOffset.Minutes, 0);
            }
            if (!dstDisabled)
            {
                TimeZoneInfo.TZif_GenerateAdjustmentRules(out this._adjustmentRules, this._baseUtcOffset, array, array2, array3, array4, array5, text2);
            }
            TimeZoneInfo.ValidateTimeZoneInfo(this._id, this._baseUtcOffset, this._adjustmentRules, out this._supportsDaylightSavingTime);
        }
References System.TimeZoneInfo._adjustmentRules, System.TimeZoneInfo._baseUtcOffset, System.TimeZoneInfo._id, System.TimeZoneInfo._standardDisplayName, System.TimeZoneInfo._supportsDaylightSavingTime, System.array, System.TimeSpan.Hours, int, System.L, System.text, System.TimeSpan.Ticks, System.TimeZoneInfo.TZif_GenerateAdjustmentRules(), System.TimeZoneInfo.TZif_GetZoneAbbreviation(), System.TimeZoneInfo.TZif_ParseRaw(), System.DateTime.UtcNow, System.TimeZoneInfo.ValidateTimeZoneInfo(), and System.TimeSpan.Zero.