Terraria Decompiled: System.TimeZoneInfo.GetAdjustmentRules
GetAdjustmentRules()
TimeZoneInfo.AdjustmentRule[] System.TimeZoneInfo.GetAdjustmentRules () inline
Definition at line 78 of file TimeZoneInfo.cs.
        {
            if (this._adjustmentRules == null)
            {
                return Array.Empty<TimeZoneInfo.AdjustmentRule>();
            }
            TimeZoneInfo.AdjustmentRule[] array = new TimeZoneInfo.AdjustmentRule[this._adjustmentRules.Length];
            for (int i = 0; i < this._adjustmentRules.Length; i++)
            {
                TimeZoneInfo.AdjustmentRule adjustmentRule = this._adjustmentRules[i];
                DateTime dateTime = ((adjustmentRule.DateStart.Kind == DateTimeKind.Utc) ? new DateTime(adjustmentRule.DateStart.Ticks + this._baseUtcOffset.Ticks, DateTimeKind.Unspecified) : adjustmentRule.DateStart);
                DateTime dateTime2 = ((adjustmentRule.DateEnd.Kind == DateTimeKind.Utc) ? new DateTime(adjustmentRule.DateEnd.Ticks + this._baseUtcOffset.Ticks + adjustmentRule.DaylightDelta.Ticks, DateTimeKind.Unspecified) : adjustmentRule.DateEnd);
                TimeZoneInfo.TransitionTime transitionTime = TimeZoneInfo.TransitionTime.CreateFixedDateRule(new DateTime(1, 1, 1, dateTime.Hour, dateTime.Minute, dateTime.Second), dateTime.Month, dateTime.Day);
                TimeZoneInfo.TransitionTime transitionTime2 = TimeZoneInfo.TransitionTime.CreateFixedDateRule(new DateTime(1, 1, 1, dateTime2.Hour, dateTime2.Minute, dateTime2.Second), dateTime2.Month, dateTime2.Day);
                array[i] = TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(dateTime.Date, dateTime2.Date, adjustmentRule.DaylightDelta, transitionTime, transitionTime2);
            }
            return array;
        }
References System.TimeZoneInfo._adjustmentRules, System.array, System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.TimeZoneInfo.TransitionTime.CreateFixedDateRule(), System.DateTime.Date, System.TimeZoneInfo.AdjustmentRule.DateEnd, System.TimeZoneInfo.AdjustmentRule.DateStart, System.DateTime, System.DateTime.Day, System.TimeZoneInfo.AdjustmentRule.DaylightDelta, System.DateTime.Hour, System.DateTime.Minute, System.DateTime.Month, System.DateTime.Second, System.DateTime.Ticks, and System.TimeSpan.Ticks.
Referenced by System.CurrentSystemTimeZone.CreateDaylightChanges(), and System.TimeZoneInfo.StringSerializer.GetSerializedString().