Terraria Decompiled: System.TimeZoneInfo.NormalizeAdjustmentRuleOffset
NormalizeAdjustmentRuleOffset()
static void System.TimeZoneInfo.NormalizeAdjustmentRuleOffset (TimeSpan baseUtcOffset, ref TimeZoneInfo::AdjustmentRule adjustmentRule) inline static private
Definition at line 2474 of file TimeZoneInfo.cs.
        {
            TimeSpan utcOffset = TimeZoneInfo.GetUtcOffset(baseUtcOffset, adjustmentRule);
            TimeSpan timeSpan = TimeSpan.Zero;
            if (utcOffset > TimeZoneInfo.MaxOffset)
            {
                timeSpan = TimeZoneInfo.MaxOffset - utcOffset;
            }
            else if (utcOffset < TimeZoneInfo.MinOffset)
            {
                timeSpan = TimeZoneInfo.MinOffset - utcOffset;
            }
            if (timeSpan != TimeSpan.Zero)
            {
                adjustmentRule = TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(adjustmentRule.DateStart, adjustmentRule.DateEnd, adjustmentRule.DaylightDelta, adjustmentRule.DaylightTransitionStart, adjustmentRule.DaylightTransitionEnd, adjustmentRule.BaseUtcOffsetDelta + timeSpan, adjustmentRule.NoDaylightTransitions);
            }
        }
References System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.MaxOffset, System.TimeZoneInfo.MinOffset, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.TZif_GenerateAdjustmentRule().