Terraria Decompiled: System.TimeZoneInfo.FindTimeZoneId
FindTimeZoneId()
static string System.TimeZoneInfo.FindTimeZoneId (byte[] rawData) inline static private
Definition at line 394 of file TimeZoneInfo.cs.
        {
            string id = "Local";
            string timeZoneDirectory = TimeZoneInfo.GetTimeZoneDirectory();
            string localtimeFilePath = Path.Combine(timeZoneDirectory, "localtime");
            string posixrulesFilePath = Path.Combine(timeZoneDirectory, "posixrules");
            byte[] buffer = new byte[rawData.Length];
            try
            {
                TimeZoneInfo.EnumerateFilesRecursively(timeZoneDirectory, delegate(string filePath)
                {
                    if (!string.Equals(filePath, localtimeFilePath, StringComparison.OrdinalIgnoreCase) && !string.Equals(filePath, posixrulesFilePath, StringComparison.OrdinalIgnoreCase) && TimeZoneInfo.CompareTimeZoneFile(filePath, buffer, rawData))
                    {
                        id = filePath;
                        if (id.StartsWith(timeZoneDirectory, StringComparison.Ordinal))
{
                            id = id.Substring(timeZoneDirectory.Length);
                        }
                        return true;
                    }
                    return false;
                });
            }
            catch (IOException)
            {
            }
            catch (SecurityException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
            return id;
        }
References System.IO.Path.Combine(), System.TimeZoneInfo.CompareTimeZoneFile(), System.TimeZoneInfo.EnumerateFilesRecursively(), System.TimeZoneInfo.Equals(), and System.TimeZoneInfo.GetTimeZoneDirectory().
Referenced by System.TimeZoneInfo.TryLoadTzFile().