Terraria Decompiled: System.TimeZoneInfo.GetIsDaylightSavings
GetIsDaylightSavings()
static bool System.TimeZoneInfo.GetIsDaylightSavings (DateTime time, TimeZoneInfo::AdjustmentRule rule, DaylightTimeStruct daylightTime, TimeZoneInfoOptions flags) inline static private
Definition at line 1961 of file TimeZoneInfo.cs.
        {
            if (rule == null)
            {
                return false;
            }
            DateTime dateTime;
            DateTime dateTime2;
            if (time.Kind == DateTimeKind.Local)
            {
                dateTime = (rule.IsStartDateMarkerForBeginningOfYear() ? new DateTime(daylightTime.Start.Year, 1, 1, 0, 0, 0) : (daylightTime.Start + daylightTime.Delta));
                dateTime2 = (rule.IsEndDateMarkerForEndOfYear() ? new DateTime(daylightTime.End.Year + 1, 1, 1, 0, 0, 0).AddTicks(-1L) : daylightTime.End);
            }
            else
            {
                bool flag = rule.DaylightDelta > TimeSpan.Zero;
                dateTime = (rule.IsStartDateMarkerForBeginningOfYear() ? new DateTime(daylightTime.Start.Year, 1, 1, 0, 0, 0) : (daylightTime.Start + (flag ? rule.DaylightDelta : TimeSpan.Zero)));
                dateTime2 = (rule.IsEndDateMarkerForEndOfYear() ? new DateTime(daylightTime.End.Year + 1, 1, 1, 0, 0, 0).AddTicks(-1L) : (daylightTime.End + (flag ? (-rule.DaylightDelta) : TimeSpan.Zero)));
            }
            bool flag2 = TimeZoneInfo.CheckIsDst(dateTime, time, dateTime2, false, rule);
            if (flag2 && time.Kind == DateTimeKind.Local && TimeZoneInfo.GetIsAmbiguousTime(time, rule, daylightTime))
            {
                flag2 = time.IsAmbiguousDaylightSavingTime();
            }
            return flag2;
        }
References System.TimeZoneInfo.CheckIsDst(), System.DateTime, System.Globalization.DaylightTimeStruct.Delta, System.Globalization.DaylightTimeStruct.End, System.TimeZoneInfo.GetIsAmbiguousTime(), System.DateTime.IsAmbiguousDaylightSavingTime(), System.DateTime.Kind, System.L, System.Globalization.DaylightTimeStruct.Start, System.DateTime.Year, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.GetUtcOffset(), and System.TimeZoneInfo.IsDaylightSavingTime().