Terraria Decompiled: System.TimeZoneInfo.GetTimeZoneDirectory
GetTimeZoneDirectory()
static string System.TimeZoneInfo.GetTimeZoneDirectory () inline static private
Definition at line 519 of file TimeZoneInfo.cs.
        {
            string text = Environment.GetEnvironmentVariable("TZDIR");
            if (text == null)
            {
                text = "/usr/share/zoneinfo/";
            }
            else if (!text.EndsWith(Path.DirectorySeparatorChar))
            {
                text += Path.DirectorySeparatorChar.ToString();
            }
            return text;
        }
References System.IO.Path.DirectorySeparatorChar, and System.text.
Referenced by System.TimeZoneInfo.FindTimeZoneId(), System.TimeZoneInfo.FindTimeZoneIdUsingReadLink(), System.TimeZoneInfo.PopulateAllSystemTimeZones(), System.TimeZoneInfo.TryGetLocalTzFile(), and System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine().