Terraria Decompiled: System.TimeZoneInfo.GetDaylightTime
GetDaylightTime()
DaylightTimeStruct System.TimeZoneInfo.GetDaylightTime (int year, TimeZoneInfo::AdjustmentRule rule, int? ruleIndex) inline private
Definition at line 1941 of file TimeZoneInfo.cs.
        {
            TimeSpan daylightDelta = rule.DaylightDelta;
            DateTime dateTime;
            DateTime dateTime2;
            if (rule.NoDaylightTransitions)
            {
                TimeZoneInfo.AdjustmentRule previousAdjustmentRule = this.GetPreviousAdjustmentRule(rule, ruleIndex);
                dateTime = this.ConvertFromUtc(rule.DateStart, previousAdjustmentRule.DaylightDelta, previousAdjustmentRule.BaseUtcOffsetDelta);
                dateTime2 = this.ConvertFromUtc(rule.DateEnd, rule.DaylightDelta, rule.BaseUtcOffsetDelta);
            }
            else
            {
                dateTime = TimeZoneInfo.TransitionTimeToDateTime(year, rule.DaylightTransitionStart);
                dateTime2 = TimeZoneInfo.TransitionTimeToDateTime(year, rule.DaylightTransitionEnd);
            }
            return new DaylightTimeStruct(dateTime, dateTime2, daylightDelta);
        }
References System.TimeZoneInfo.AdjustmentRule.BaseUtcOffsetDelta, System.TimeZoneInfo.AdjustmentRule.DaylightDelta, and System.TimeZoneInfo.TransitionTimeToDateTime().
Referenced by System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.GetIsDaylightSavingsFromUtc(), and System.TimeZoneInfo.GetUtcOffset().