Terraria Decompiled: System.TimeZoneInfo.GetLocalUtcOffset
GetLocalUtcOffset()
static TimeSpan System.TimeZoneInfo.GetLocalUtcOffset (DateTime dateTime, TimeZoneInfoOptions flags) inline static package
Definition at line 1292 of file TimeZoneInfo.cs.
        {
            TimeZoneInfo.CachedData cachedData = TimeZoneInfo.s_cachedData;
            return cachedData.Local.GetUtcOffset(dateTime, flags, cachedData);
        }
References System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.CachedData.Local, and System.TimeZoneInfo.s_cachedData.
Referenced by System.DateTimeOffset.DateTimeOffset(), System.DateTimeOffset.DateTimeOffset(), System.DateTimeParse.DateTimeOffsetTimeZonePostProcessing(), System.DateTimeParse.DetermineTimeZoneAdjustments(), System.DateTimeFormat.FormatCustomizedRoundripTimeZone(), System.DateTimeFormat.FormatCustomizedTimeZone(), System.DateTime.FromBinary(), and System.DateTime.ToBinary().