Terraria Decompiled: System.TimeZoneInfo.PopulateAllSystemTimeZones
PopulateAllSystemTimeZones()
static void System.TimeZoneInfo.PopulateAllSystemTimeZones (TimeZoneInfo::CachedData cachedData) inline static private
Definition at line 98 of file TimeZoneInfo.cs.
        {
            foreach (string text in TimeZoneInfo.GetTimeZoneIds(TimeZoneInfo.GetTimeZoneDirectory()))
            {
                TimeZoneInfo timeZoneInfo;
                Exception ex;
                TimeZoneInfo.TryGetTimeZone(text, false, out timeZoneInfo, out ex, cachedData, true);
            }
        }
References System.TimeZoneInfo.GetTimeZoneDirectory(), System.TimeZoneInfo.GetTimeZoneIds(), System.text, and System.TimeZoneInfo.TryGetTimeZone().
Referenced by System.TimeZoneInfo.GetSystemTimeZones().