Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom
BiomeRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 94 of file BiomeStructuredDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            BiomeDungeonRoomSettings biomeDungeonRoomSettings = (BiomeDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Vector2 position = new Vector2((float)i, (float)j);
            int num = BiomeDungeonRoom.GetBiomeRoomInnerSize(biomeDungeonRoomSettings.StyleData);
            int num2 = 8;
            int num3 = BiomeDungeonRoom.GetBiomeRoomOuterSize(biomeDungeonRoomSettings.StyleData);
            if (this.calculated)
            {
                position = this.Position;
                num = this.RoomInnerSize;
                num3 = this.RoomOuterSize;
                num2 = this.WallDepth;
            }
            int num4 = 20;
            int num5 = Math.Max(num4 + num2, Math.Min(Main.maxTilesX - num4 - num2, (int)position.X - num));
            int num6 = Math.Max(num4 + num2, Math.Min(Main.maxTilesX - num4 - num2, (int)position.X + num));
            int num7 = Math.Max(num4 + num2, Math.Min(Main.maxTilesY - num4 - num2, (int)position.Y - num));
            int num8 = Math.Max(num4 + num2, Math.Min(Main.maxTilesY - num4 - num2, (int)position.Y + num));
            int num9 = Math.Max(num4, Math.Min(Main.maxTilesX - num4, (int)position.X - num3));
            int num10 = Math.Max(num4, Math.Min(Main.maxTilesX - num4, (int)position.X + num3));
            int num11 = Math.Max(num4, Math.Min(Main.maxTilesY - num4, (int)position.Y - num3));
            int num12 = Math.Max(num4, Math.Min(Main.maxTilesY - num4, (int)position.Y + num3));
            this.InnerBounds.SetBounds(num5, num7, num6 - 1, num8 - 1);
            this.OuterBounds.SetBounds(num9, num11, num10 - 1, num12 - 1);
            data.dungeonBounds.UpdateBounds(num9, num11, num10 - 1, num12 - 1);
            int num13 = num10 - num9;
            int num14 = num12 - num11;
            Point center = this.OuterBounds.Center;
            Point center2 = this.OuterBounds.Center;
            int num15 = unifiedRandom.Next(4);
            int num16 = 1;
            for (int k = num9; k < num10; k++)
            {
                int num17 = k;
                float num18 = Math.Max(0f, Math.Min(1f, (float)(k - num9) / Math.Max(1f, (float)(num10 - 1 - num9))));
                float num19 = this.BiomeRoom_GetYPercent(unifiedRandom, num15, num18);
                float num20 = (float)Math.Max(1, num14 / 16) + (float)Math.Max(1, num14 / 4) * num19;
                float num21 = (float)num7 + num20;
                float num22 = num21 - (float)num2;
                float num23 = (float)num8 - num20 - 1f;
                float num24 = num23 + (float)num2;
                for (int l = num11; l < num12; l++)
                {
                    int num25 = l;
                    float num26 = Math.Max(0f, Math.Min(1f, (float)(l - num11) / Math.Max(1f, (float)(num12 - 1 - num11))));
                    float num27 = this.BiomeRoom_GetXPercent(unifiedRandom, num15, num26);
                    float num28 = (float)Math.Max(1, num13 / 4) * num27;
                    float num29 = (float)num5 + num28;
                    float num30 = num29 - (float)num2;
                    float num31 = (float)num6 - num28 - 1f;
                    float num32 = num31 + (float)num2;
                    Tile tile = Main.tile[num17, num25];
                    Main.tile[num17, num25 - 1];
                    Main.tile[num17, num25 + 1];
                    Main.tile[num17, num25 + 2];
                    if (generating && (tile.type == 484 || tile.type == 485))
                    {
                        tile.active(false);
                    }
                    if ((float)l >= num22 && (float)l <= num24 && (float)k >= num30 && (float)k <= num32)
                    {
                        if (k <= num9 + num2 - 1 || k >= num10 - num2 + 1 || ((float)l >= num22 && (float)l <= num21) || ((float)l >= num23 && (float)l <= num24) || ((float)k >= num30 && (float)k <= num29) || ((float)k >= num31 && (float)k <= num32))
{
                            if (!generating)
{
                                this._outerShapeData.Add(num17 - (int)position.X + num16, num25 - (int)position.Y + num16);
                            }
                            else
{
                                DungeonUtils.ChangeTileType(tile, brickTileType, false, biomeDungeonRoomSettings.OverridePaintTile);
                                if (tile.liquid > 0)
{
                                    tile.liquid = 0;
                                    tile.liquidType(0);
                                }
                                DungeonUtils.ChangeWallType(tile, brickWallType, false, biomeDungeonRoomSettings.OverridePaintWall);
                            }
                        }
                        else if (this.InnerBounds.Contains(num17, num25))
{
                            if (!generating)
{
                                this._innerShapeData.Add(num17 - (int)position.X + num16, num25 - (int)position.Y + num16);
                                this._outerShapeData.Add(num17 - (int)position.X + num16, num25 - (int)position.Y + num16);
                            }
                            else
{
                                if (tile.liquid > 0)
{
                                    tile.liquid = 0;
                                    tile.liquidType(0);
                                }
                                DungeonUtils.ChangeWallType(tile, brickWallType, false, biomeDungeonRoomSettings.OverridePaintWall);
                                tile.active(false);
                                tile.ClearBlockPaintAndCoating();
                            }
                        }
                        else if (!generating)
{
                            this._outerShapeData.Add(num17 - (int)position.X + num16, num25 - (int)position.Y + num16);
                        }
                        else
{
                            bool flag = k == num9 || k == num10 - 1 || l == num11 || l == num12 - 1 || k == num5 - 1 || k == num6 || l == num7 - 1 || l == num8;
                            if (tile.liquid > 0)
{
                                tile.liquid = 0;
                                tile.liquidType(0);
                            }
                            DungeonUtils.ChangeTileType(tile, brickTileType, true, biomeDungeonRoomSettings.OverridePaintTile);
                            if (!flag)
{
                                DungeonUtils.ChangeWallType(tile, brickWallType, false, biomeDungeonRoomSettings.OverridePaintWall);
                            }
                        }
                    }
                }
            }
            base.BiomeRoom_AddHallwaySpace(position, num5, num6, num7, num8, num16, brickWallType, this.settings.OverridePaintWall, generating);
            base.BiomeRoom_FinishRoom(unifiedRandom, num9, num10, num11, num12, false);
            this.RoomInnerSize = num;
            this.RoomOuterSize = num3;
            this.WallDepth = num2;
            this.Position = position;
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom._innerShapeData, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom._outerShapeData, Terraria.Tile.active(), Terraria.WorldBuilding.ShapeData.Add(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom_GetXPercent(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom_GetYPercent(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.calculated, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.GetBiomeRoomInnerSize(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.GetBiomeRoomOuterSize(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, int, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintWall, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.Position, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.RoomInnerSize, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.RoomOuterSize, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.WallDepth, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.GenerateRoom().