Terraria Decompiled: System.TimeZoneInfo.TZif_GenerateAdjustmentRule
TZif_GenerateAdjustmentRule()
static void System.TimeZoneInfo.TZif_GenerateAdjustmentRule (ref int index, TimeSpan timeZoneBaseUtcOffset, List< TimeZoneInfo::AdjustmentRule > rulesList, DateTime[] dts, byte[] typeOfLocalTime, TimeZoneInfo::TZifType[] transitionTypes, bool[] StandardTime, bool[] GmtTime, string futureTransitionsPosixFormat) inline static private
Definition at line 600 of file TimeZoneInfo.cs.
        {
            while (index < dts.Length && dts[index] == DateTime.MinValue)
            {
                index++;
            }
            if (rulesList.Count == 0 && index < dts.Length)
            {
                TimeZoneInfo.TZifType tzifType = TimeZoneInfo.TZif_GetEarlyDateTransitionType(transitionTypes);
                DateTime dateTime = dts[index];
                TimeSpan timeSpan = TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(tzifType.UtcOffset, timeZoneBaseUtcOffset);
                TimeSpan timeSpan2 = (tzifType.IsDst ? timeSpan : TimeSpan.Zero);
                TimeSpan timeSpan3 = (tzifType.IsDst ? TimeSpan.Zero : timeSpan);
                TimeZoneInfo.AdjustmentRule adjustmentRule = TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(DateTime.MinValue, dateTime.AddTicks(-1L), timeSpan2, default(TimeZoneInfo.TransitionTime), default(TimeZoneInfo.TransitionTime), timeSpan3, true);
                if (!TimeZoneInfo.IsValidAdjustmentRuleOffest(timeZoneBaseUtcOffset, adjustmentRule))
                {
                    TimeZoneInfo.NormalizeAdjustmentRuleOffset(timeZoneBaseUtcOffset, ref adjustmentRule);
                }
                rulesList.Add(adjustmentRule);
            }
            else if (index < dts.Length)
            {
                DateTime dateTime2 = dts[index - 1];
                TimeZoneInfo.TZifType tzifType2 = transitionTypes[(int)typeOfLocalTime[index - 1]];
                DateTime dateTime3 = dts[index];
                TimeSpan timeSpan4 = TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(tzifType2.UtcOffset, timeZoneBaseUtcOffset);
                TimeSpan timeSpan5 = (tzifType2.IsDst ? timeSpan4 : TimeSpan.Zero);
                TimeSpan timeSpan6 = (tzifType2.IsDst ? TimeSpan.Zero : timeSpan4);
                TimeZoneInfo.TransitionTime transitionTime;
                if (tzifType2.IsDst)
                {
                    transitionTime = TimeZoneInfo.TransitionTime.CreateFixedDateRule(DateTime.MinValue.AddMilliseconds(2.0), 1, 1);
                }
                else
                {
                    transitionTime = default(TimeZoneInfo.TransitionTime);
                }
                TimeZoneInfo.AdjustmentRule adjustmentRule2 = TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(dateTime2, dateTime3.AddTicks(-1L), timeSpan5, transitionTime, default(TimeZoneInfo.TransitionTime), timeSpan6, true);
                if (!TimeZoneInfo.IsValidAdjustmentRuleOffest(timeZoneBaseUtcOffset, adjustmentRule2))
                {
                    TimeZoneInfo.NormalizeAdjustmentRuleOffset(timeZoneBaseUtcOffset, ref adjustmentRule2);
                }
                rulesList.Add(adjustmentRule2);
            }
            else
            {
                DateTime dateTime4 = dts[index - 1];
                if (!string.IsNullOrEmpty(futureTransitionsPosixFormat))
                {
                    TimeZoneInfo.AdjustmentRule adjustmentRule3 = TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat(futureTransitionsPosixFormat, dateTime4, timeZoneBaseUtcOffset);
                    if (adjustmentRule3 != null)
                    {
                        if (!TimeZoneInfo.IsValidAdjustmentRuleOffest(timeZoneBaseUtcOffset, adjustmentRule3))
{
                            TimeZoneInfo.NormalizeAdjustmentRuleOffset(timeZoneBaseUtcOffset, ref adjustmentRule3);
                        }
                        rulesList.Add(adjustmentRule3);
                    }
                }
                else
                {
                    TimeZoneInfo.TZifType tzifType3 = transitionTypes[(int)typeOfLocalTime[index - 1]];
                    TimeSpan timeSpan7 = TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(tzifType3.UtcOffset, timeZoneBaseUtcOffset);
                    TimeSpan timeSpan8 = (tzifType3.IsDst ? timeSpan7 : TimeSpan.Zero);
                    TimeSpan timeSpan9 = (tzifType3.IsDst ? TimeSpan.Zero : timeSpan7);
                    TimeZoneInfo.AdjustmentRule adjustmentRule4 = TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(dateTime4, DateTime.MaxValue, timeSpan8, default(TimeZoneInfo.TransitionTime), default(TimeZoneInfo.TransitionTime), timeSpan9, true);
                    if (!TimeZoneInfo.IsValidAdjustmentRuleOffest(timeZoneBaseUtcOffset, adjustmentRule4))
                    {
                        TimeZoneInfo.NormalizeAdjustmentRuleOffset(timeZoneBaseUtcOffset, ref adjustmentRule4);
                    }
                    rulesList.Add(adjustmentRule4);
                }
            }
            index++;
        }
References System.Collections.Generic.List< T >.Add(), System.DateTime.AddMilliseconds(), System.DateTime.AddTicks(), System.Collections.Generic.List< T >.Count, System.TimeZoneInfo.AdjustmentRule.CreateAdjustmentRule(), System.TimeZoneInfo.TransitionTime.CreateFixedDateRule(), System.index, int, System.TimeZoneInfo.TZifType.IsDst, System.TimeZoneInfo.IsValidAdjustmentRuleOffest(), System.L, System.DateTime.MaxValue, System.DateTime.MinValue, System.TimeZoneInfo.NormalizeAdjustmentRuleOffset(), System.TimeZoneInfo.TZif_CalculateTransitionOffsetFromBase(), System.TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat(), System.TimeZoneInfo.TZif_GetEarlyDateTransitionType(), System.TimeZoneInfo.TZifType.UtcOffset, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.TZif_GenerateAdjustmentRules().