Terraria Decompiled: System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine
TryGetTimeZoneFromLocalMachine() [2/2]
static TimeZoneInfo.TimeZoneInfoResult System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine (string id, out TimeZoneInfo value, out Exception e) inline static private
Definition at line 115 of file TimeZoneInfo.cs.
        {
            value = null;
            e = null;
            string text = Path.Combine(TimeZoneInfo.GetTimeZoneDirectory(), id);
            byte[] array;
            try
            {
                array = File.ReadAllBytes(text);
            }
            catch (UnauthorizedAccessException ex)
            {
                e = ex;
                return TimeZoneInfo.TimeZoneInfoResult.SecurityException;
            }
            catch (FileNotFoundException ex2)
            {
                e = ex2;
                return TimeZoneInfo.TimeZoneInfoResult.TimeZoneNotFoundException;
            }
            catch (DirectoryNotFoundException ex3)
            {
                e = ex3;
                return TimeZoneInfo.TimeZoneInfoResult.TimeZoneNotFoundException;
            }
            catch (IOException ex4)
            {
                e = new InvalidTimeZoneException(SR.Format("The time zone ID '{0}' was found on the local computer, but the file at '{1}' was corrupt.", id, text), ex4);
                return TimeZoneInfo.TimeZoneInfoResult.InvalidTimeZoneException;
            }
            value = TimeZoneInfo.GetTimeZoneFromTzData(array, id);
            if (value == null)
            {
                e = new InvalidTimeZoneException(SR.Format("The time zone ID '{0}' was found on the local computer, but the file at '{1}' was corrupt.", id, text));
                return TimeZoneInfo.TimeZoneInfoResult.InvalidTimeZoneException;
            }
            return TimeZoneInfo.TimeZoneInfoResult.Success;
        }
References System.array, System.IO.Path.Combine(), SR.Format(), System.TimeZoneInfo.GetTimeZoneDirectory(), System.TimeZoneInfo.GetTimeZoneFromTzData(), System.TimeZoneInfo.InvalidTimeZoneException, System.IO.File.ReadAllBytes(), System.text, and System.value.
Referenced by System.TimeZoneInfo.TryGetTimeZone(), and System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine().