Terraria Decompiled: System.TimeZoneInfo.TZif_ParseRaw
TZif_ParseRaw()
static void System.TimeZoneInfo.TZif_ParseRaw (byte[] data, out TimeZoneInfo::TZifHead t, out DateTime[] dts, out byte[] typeOfLocalTime, out TimeZoneInfo::TZifType[] transitionType, out string zoneAbbreviations, out bool[] StandardTime, out bool[] GmtTime, out string futureTransitionsPosixFormat) inline static private
Definition at line 1035 of file TimeZoneInfo.cs.
        {
            dts = null;
            typeOfLocalTime = null;
            transitionType = null;
            zoneAbbreviations = string.Empty;
            StandardTime = null;
            GmtTime = null;
            futureTransitionsPosixFormat = null;
            int num = 0;
            t = new TimeZoneInfo.TZifHead(data, num);
            num += 44;
            int num2 = 4;
            if (t.Version != TimeZoneInfo.TZVersion.V1)
            {
                num += (int)((long)num2 * (long)((ulong)t.TimeCount) + (long)((ulong)t.TimeCount) + (long)((ulong)(6U * t.TypeCount)) + (long)(num2 + 4) * (long)((ulong)t.LeapCount) + (long)((ulong)t.IsStdCount) + (long)((ulong)t.IsGmtCount) + (long)((ulong)t.CharCount));
                t = new TimeZoneInfo.TZifHead(data, num);
                num += 44;
                num2 = 8;
            }
            dts = new DateTime[t.TimeCount];
            typeOfLocalTime = new byte[t.TimeCount];
            transitionType = new TimeZoneInfo.TZifType[t.TypeCount];
            zoneAbbreviations = string.Empty;
            StandardTime = new bool[t.TypeCount];
            GmtTime = new bool[t.TypeCount];
            int num3 = 0;
            while ((long)num3 < (long)((ulong)t.TimeCount))
            {
                long num4 = TimeZoneInfo.TZif_ToUnixTime(data, num, t.Version);
                dts[num3] = TimeZoneInfo.TZif_UnixTimeToDateTime(num4);
                num += num2;
                num3++;
            }
            int num5 = 0;
            while ((long)num5 < (long)((ulong)t.TimeCount))
            {
                typeOfLocalTime[num5] = data[num];
                num++;
                num5++;
            }
            int num6 = 0;
            while ((long)num6 < (long)((ulong)t.TypeCount))
            {
                transitionType[num6] = new TimeZoneInfo.TZifType(data, num);
                num += 6;
                num6++;
            }
            Encoding utf = Encoding.UTF8;
            zoneAbbreviations = utf.GetString(data, num, (int)t.CharCount);
            num += (int)t.CharCount;
            num += (int)((ulong)t.LeapCount * (ulong)((long)(num2 + 4)));
            int num7 = 0;
            while ((long)num7 < (long)((ulong)t.IsStdCount) && (long)num7 < (long)((ulong)t.TypeCount) && num < data.Length)
            {
                StandardTime[num7] = data[num++] > 0;
                num7++;
            }
            int num8 = 0;
            while ((long)num8 < (long)((ulong)t.IsGmtCount) && (long)num8 < (long)((ulong)t.TypeCount) && num < data.Length)
            {
                GmtTime[num8] = data[num++] > 0;
                num8++;
            }
            if (t.Version != TimeZoneInfo.TZVersion.V1 && data[num++] == 10 && data[data.Length - 1] == 10)
            {
                futureTransitionsPosixFormat = utf.GetString(data, num, data.Length - num - 1);
            }
        }
References System.Text.Encoding.GetString(), int, long, System.TimeZoneInfo.TZif_ToUnixTime(), System.TimeZoneInfo.TZif_UnixTimeToDateTime(), System.U, and System.Text.Encoding.UTF8.
Referenced by System.TimeZoneInfo.TimeZoneInfo().