Terraria Decompiled: System.TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule
TZif_CreateTransitionTimeFromPosixRule()
static TimeZoneInfo.TransitionTime System.TimeZoneInfo.TZif_CreateTransitionTimeFromPosixRule (string date, string time) inline static private
Definition at line 801 of file TimeZoneInfo.cs.
        {
            if (string.IsNullOrEmpty(date))
            {
                return default(TimeZoneInfo.TransitionTime);
            }
            if (date[0] == 'M')
            {
                int num;
                int num2;
                DayOfWeek dayOfWeek;
                if (!TimeZoneInfo.TZif_ParseMDateRule(date, out num, out num2, out dayOfWeek))
                {
                    throw new InvalidTimeZoneException(SR.Format("'{0}' is not a valid POSIX-TZ-environment-variable MDate rule.  A valid rule has the format 'Mm.w.d'.", date));
                }
                return TimeZoneInfo.TransitionTime.CreateFloatingDateRule(TimeZoneInfo.ParseTimeOfDay(time), num, num2, dayOfWeek);
            }
            else
            {
                if (date[0] != 'J')
                {
                    throw new InvalidTimeZoneException("Julian n day in POSIX strings is not supported.");
                }
                int num3;
                int num4;
                TimeZoneInfo.TZif_ParseJulianDay(date, out num3, out num4);
                return TimeZoneInfo.TransitionTime.CreateFixedDateRule(TimeZoneInfo.ParseTimeOfDay(time), num3, num4);
            }
        }
References System.TimeZoneInfo.TransitionTime.CreateFixedDateRule(), System.TimeZoneInfo.TransitionTime.CreateFloatingDateRule(), SR.Format(), System.TimeZoneInfo.ParseTimeOfDay(), System.TimeZoneInfo.TZif_ParseJulianDay(), and System.TimeZoneInfo.TZif_ParseMDateRule().
Referenced by System.TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat().