Terraria Decompiled: System.TimeZoneInfo.GetUtcOffset
GetUtcOffset() [3/6]
TimeSpan System.TimeZoneInfo.GetUtcOffset (DateTime dateTime, TimeZoneInfoOptions flags, TimeZoneInfo::CachedData cachedData) inline private
Definition at line 1305 of file TimeZoneInfo.cs.
        {
            if (dateTime.Kind == DateTimeKind.Local)
            {
                if (cachedData.GetCorrespondingKind(this) != DateTimeKind.Local)
                {
                    return TimeZoneInfo.GetUtcOffsetFromUtc(TimeZoneInfo.ConvertTime(dateTime, cachedData.Local, TimeZoneInfo.s_utcTimeZone, flags), this);
                }
            }
            else if (dateTime.Kind == DateTimeKind.Utc)
            {
                if (cachedData.GetCorrespondingKind(this) == DateTimeKind.Utc)
                {
                    return this._baseUtcOffset;
                }
                return TimeZoneInfo.GetUtcOffsetFromUtc(dateTime, this);
            }
            return TimeZoneInfo.GetUtcOffset(dateTime, this, flags);
        }
References System.TimeZoneInfo.ConvertTime(), System.TimeZoneInfo.GetUtcOffset(), System.TimeZoneInfo.GetUtcOffsetFromUtc(), System.DateTime.Kind, and System.TimeZoneInfo.s_utcTimeZone.