Terraria Decompiled: System.TimeZoneInfo.TransitionTimeToDateTime
TransitionTimeToDateTime()
static DateTime System.TimeZoneInfo.TransitionTimeToDateTime (int year, TimeZoneInfo::TransitionTime transitionTime) inline static package
Definition at line 2316 of file TimeZoneInfo.cs.
        {
            DateTime timeOfDay = transitionTime.TimeOfDay;
            DateTime dateTime;
            if (transitionTime.IsFixedDateRule)
            {
                int num = DateTime.DaysInMonth(year, transitionTime.Month);
                dateTime = new DateTime(year, transitionTime.Month, (num < transitionTime.Day) ? num : transitionTime.Day, timeOfDay.Hour, timeOfDay.Minute, timeOfDay.Second, timeOfDay.Millisecond);
            }
            else if (transitionTime.Week <= 4)
            {
                dateTime = new DateTime(year, transitionTime.Month, 1, timeOfDay.Hour, timeOfDay.Minute, timeOfDay.Second, timeOfDay.Millisecond);
                int dayOfWeek = (int)dateTime.DayOfWeek;
                int num2 = transitionTime.DayOfWeek - (DayOfWeek)dayOfWeek;
                if (num2 < 0)
                {
                    num2 += 7;
                }
                num2 += 7 * (transitionTime.Week - 1);
                if (num2 > 0)
                {
                    dateTime = dateTime.AddDays((double)num2);
                }
            }
            else
            {
                int num3 = DateTime.DaysInMonth(year, transitionTime.Month);
                dateTime = new DateTime(year, transitionTime.Month, num3, timeOfDay.Hour, timeOfDay.Minute, timeOfDay.Second, timeOfDay.Millisecond);
                int num4 = dateTime.DayOfWeek - transitionTime.DayOfWeek;
                if (num4 < 0)
                {
                    num4 += 7;
                }
                if (num4 > 0)
                {
                    dateTime = dateTime.AddDays((double)(-(double)num4));
                }
            }
            return dateTime;
        }
References System.DateTime.AddDays(), System.DateTime, System.DateTime.DayOfWeek, System.DateTime.DaysInMonth(), System.DateTime.Hour, int, System.DateTime.Millisecond, System.DateTime.Minute, System.DateTime.Second, and System.DateTime.TimeOfDay.
Referenced by System.CurrentSystemTimeZone.CreateDaylightChanges(), and System.TimeZoneInfo.GetDaylightTime().