Terraria Decompiled: Terraria.SceneState.UpdateLightDecay
UpdateLightDecay()
void Terraria.SceneState.UpdateLightDecay (SceneMetrics metrics) inline private
Definition at line 257 of file SceneState.cs.
        {
            float num = 1f;
            float num2 = 1f;
            num *= 1f - Main.shimmerAlpha * 0f;
            num2 *= 1f - Main.shimmerAlpha * 0.3f;
            if (Main.getGoodWorld)
            {
                if (metrics.WithinRangeOfNPC(245, 2000.0))
                {
                    num *= 0.6f;
                    num2 *= 0.6f;
                }
                else if (metrics.ZoneLihzhardTemple)
                {
                    num *= 0.88f;
                    num2 *= 0.88f;
                }
                else if (metrics.ZoneDungeon)
                {
                    num *= 0.94f;
                    num2 *= 0.94f;
                }
            }
            this.MoveTowards(ref this.airLightDecay, num, 0.005f);
            this.MoveTowards(ref this.solidLightDecay, num2, 0.005f);
        }
References Terraria.SceneState.airLightDecay, Terraria.Main.getGoodWorld, Terraria.SceneState.MoveTowards(), Terraria.SceneState.solidLightDecay, Terraria.SceneMetrics.WithinRangeOfNPC(), Terraria.SceneMetrics.ZoneDungeon, and Terraria.SceneMetrics.ZoneLihzhardTemple.
Referenced by Terraria.SceneState.ApplyVisuals().