Terraria Decompiled: Terraria.SceneState.UpdateGraveyard
UpdateGraveyard()
void Terraria.SceneState.UpdateGraveyard (SceneMetrics metrics) inline private
Definition at line 376 of file SceneState.cs.
        {
            float lerpValue = Utils.GetLerpValue((float)SceneMetrics.GraveyardTileMin, (float)SceneMetrics.GraveyardTileMax, (float)metrics.GraveyardTileCount, true);
            this.MoveTowards(ref Main.GraveyardVisualIntensity, lerpValue, 0.02f, 0.1f);
        }
References Terraria.Utils.GetLerpValue(), Terraria.SceneMetrics.GraveyardTileCount, Terraria.SceneMetrics.GraveyardTileMax, Terraria.SceneMetrics.GraveyardTileMin, Terraria.Main.GraveyardVisualIntensity, and Terraria.SceneState.MoveTowards().
Referenced by Terraria.SceneState.ApplyVisuals().