Terraria Decompiled: Terraria.SceneState.ApplyVisuals
ApplyVisuals()
void Terraria.SceneState.ApplyVisuals (SceneMetrics metrics) inline private
Definition at line 45 of file SceneState.cs.
        {
            if (Main.dedServ)
            {
                return;
            }
            Player perspectivePlayer = metrics.PerspectivePlayer;
            this.UpdateRGBPeriheralProbe(metrics);
            this.UpdateGraveyard(metrics);
            this.UpdateShimmer(metrics);
            this.UpdateLightDecay(metrics);
            ScreenObstruction.Update(this, metrics);
            ScreenDarkness.Update(this, metrics);
            MoonlordDeathDrama.Update(this, metrics);
            bool flag = metrics.ZoneRain && metrics.ZoneSnow;
            bool flag2 = metrics.TileCenter.Y > Main.maxTilesY - 320;
            bool flag3 = (double)metrics.TileCenter.Y < Main.worldSurface && metrics.ZoneDesert && !metrics.ZoneRain && !metrics.ZoneSandstorm;
            this.ManageSpecialBiomeVisuals("Stardust", metrics.CloseEnoughToStardustTower, metrics.ClosestNPCPosition[493] - new Vector2(0f, 10f), false);
            this.ManageSpecialBiomeVisuals("Nebula", metrics.CloseEnoughToNebulaTower, metrics.ClosestNPCPosition[507] - new Vector2(0f, 10f), false);
            this.ManageSpecialBiomeVisuals("Vortex", metrics.CloseEnoughToVortexTower, metrics.ClosestNPCPosition[422] - new Vector2(0f, 10f), false);
            this.ManageSpecialBiomeVisuals("Solar", metrics.CloseEnoughToSolarTower, metrics.ClosestNPCPosition[517] - new Vector2(0f, 10f), false);
            this.ManageSpecialBiomeVisuals("MoonLord", metrics.ClosestNPCPosition[398] != Vector2.Zero, default(Vector2), false);
            bool flag4 = metrics.CloseEnoughToSolarTower || metrics.CloseEnoughToVortexTower || metrics.CloseEnoughToNebulaTower || metrics.CloseEnoughToStardustTower;
            this.ManageSpecialBiomeVisuals("MonolithVortex", (!flag4 && metrics.ActiveMonolithType == 0) || perspectivePlayer.vortexMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("MonolithNebula", (!flag4 && metrics.ActiveMonolithType == 1) || perspectivePlayer.nebulaMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("MonolithStardust", (!flag4 && metrics.ActiveMonolithType == 2) || perspectivePlayer.stardustMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("MonolithSolar", (!flag4 && metrics.ActiveMonolithType == 3) || perspectivePlayer.solarMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("MonolithMoonLord", (!flag4 && metrics.ActiveMonolithType == 4) || perspectivePlayer.moonLordMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("BloodMoon", Main.bloodMoon || metrics.BloodMoonMonolith || perspectivePlayer.bloodMoonMonolithShader, default(Vector2), false);
            bool flag5 = Main.UseStormEffects && flag;
            bool flag6 = !Main.dayTime && !flag5 && Main.GraveyardVisualIntensity < 0.5f;
            this.ManageSpecialBiomeVisuals("Aurora", metrics.ZoneSnow && flag6, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("Blizzard", Main.UseStormEffects && flag, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("Sandstorm", Main.UseStormEffects && Sandstorm.ShowSandstormVisuals(), default(Vector2), false);
            bool flag7 = flag2 || flag3 || perspectivePlayer.sunScorchCounter > 0;
            this.ManageSpecialBiomeVisuals("HeatDistortion", Main.UseHeatDistortion && flag7, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("Graveyard", Main.GraveyardVisualIntensity > 0f, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("Sepia", Main.onlyDontStarveWorld ^ (perspectivePlayer.dontStarveShader || metrics.RadioThingMonolith), default(Vector2), false);
            this.ManageSpecialBiomeVisuals("Noir", metrics.NoirMonolith || perspectivePlayer.noirShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("CRT", metrics.CRTMonolith || perspectivePlayer.CRTMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("Test2", metrics.RetroMonolith || perspectivePlayer.retroMonolithShader, default(Vector2), false);
            this.ManageSpecialBiomeVisuals("WaterDistortion", Main.WaveQuality > 0, default(Vector2), false);
            bool flag8 = metrics.TownNPCCount > 0 || metrics.PartyMonolithCount > 0;
            this.MoveTowards(ref SkyManager.Instance["Party"].Opacity, (float)(flag8 ? 1 : 0), 0.01f);
            if (Filters.Scene["Graveyard"].IsActive())
            {
                float num = MathHelper.Lerp(0f, 0.75f, Main.GraveyardVisualIntensity);
                ScreenShaderData shader = Filters.Scene["Graveyard"].GetShader();
                shader.UseTargetPosition(metrics.Center);
                shader.UseProgress(num);
                shader.UseIntensity(1.2f);
            }
            if (Filters.Scene["Noir"].IsActive())
            {
                float num2 = 0.1f;
                float num3 = Utils.Remap(Vector3.Dot(Main.tileColor.ToVector3(), new Vector3(0.33333334f)), 0.5f, 0.1f, 0f, 0.2f, true);
                float num4 = Utils.Remap((float)((int)Main.worldSurface - metrics.TileCenter.Y), -40f, 40f, 0f, 1f, true);
                num2 = MathHelper.Lerp(num2, num3, num4);
                float num5 = 0.15f;
                float num6 = Utils.Remap((float)(metrics.TileCenter.Y - Main.UnderworldLayer), -40f, 40f, 0f, 1f, true);
                num2 = MathHelper.Lerp(num2, num5, num6);
                Random random = new Random((int)(Main.GlobalTimeWrappedHourly * 10f));
                float num7 = (float)random.NextDouble();
                float num8 = (float)random.NextDouble();
                ScreenShaderData shader2 = Filters.Scene["Noir"].GetShader();
                shader2.UseTargetPosition(metrics.Center);
                shader2.UseIntensity(num2);
                shader2.UseImageOffset(new Vector2(num7, num8));
            }
            if (Filters.Scene["WaterDistortion"].IsActive())
            {
                float num9 = (float)Main.maxTilesX * 0.5f - Math.Abs((float)metrics.TileCenter.X - (float)Main.maxTilesX * 0.5f);
                float num10 = 1f;
                float num11 = Math.Abs(Main.windSpeedCurrent);
                num10 += num11 * 1.25f;
                float num12 = MathHelper.Clamp(Main.maxRaining, 0f, 1f);
                num10 += num12 * 1.25f;
                float num13 = -(MathHelper.Clamp((num9 - 380f) / 100f, 0f, 1f) * 0.5f - 0.25f);
                num10 += num13;
                float num14 = 1f - MathHelper.Clamp(3f * ((float)((double)metrics.TileCenter.Y - Main.worldSurface) / (float)(Main.rockLayer - Main.worldSurface)), 0f, 1f);
                num10 *= num14;
                float num15 = 0.9f - MathHelper.Clamp((float)(Main.maxTilesY - metrics.TileCenter.Y - 200) / 300f, 0f, 1f) * 0.9f;
                num10 += num15;
                num10 += (1f - num14) * 0.75f;
                num10 = MathHelper.Clamp(num10, 0f, 2.5f);
                Filters.Scene["WaterDistortion"].GetShader().UseIntensity(num10);
            }
            this.MoveTowards(ref this._outsideWeatherEffectIntensityBackingValue, metrics.BehindBackwall ? (-0.1f) : 1.1f, 0.005f);
            this.outsideWeatherEffectIntensity = Utils.Clamp<float>(this._outsideWeatherEffectIntensityBackingValue, 0f, 1f);
            if (Filters.Scene["Sandstorm"].IsActive())
            {
                Filters.Scene["Sandstorm"].GetShader().UseIntensity(this.outsideWeatherEffectIntensity * 0.4f * Math.Min(1f, Sandstorm.Severity));
                Filters.Scene["Sandstorm"].GetShader().UseOpacity(Math.Min(1f, Sandstorm.Severity * 1.5f) * this.outsideWeatherEffectIntensity);
                ((SimpleOverlay)Overlays.Scene["Sandstorm"]).GetShader().UseOpacity(Math.Min(1f, Sandstorm.Severity * 1.5f) * (1f - this.outsideWeatherEffectIntensity));
            }
            Filter filter = Filters.Scene["HeatDistortion"];
            if (filter.IsActive())
            {
                float num16 = 0f;
                if (perspectivePlayer.sunScorchCounter > 0)
                {
                    float num17 = Utils.GetLerpValue(0f, 300f, (float)perspectivePlayer.sunScorchCounter, true) * 4f;
                    num16 = Math.Max(num16, num17);
                }
                if (flag2)
                {
                    float num18 = (float)(metrics.TileCenter.Y - (Main.maxTilesY - 320)) / 120f;
                    num18 = Math.Min(1f, num18) * 2f;
                    num16 = Math.Max(num16, num18);
                }
                else if (flag3)
                {
                    Vector3 vector = Main.tileColor.ToVector3();
                    float num19 = (vector.X + vector.Y + vector.Z) / 3f;
                    float num20 = this.outsideWeatherEffectIntensity * 4f * Math.Max(0f, 0.5f - Main.cloudAlpha) * num19;
                    num16 = Math.Max(num16, num20);
                }
                filter.GetShader().UseIntensity(num16);
                filter.IsHidden = num16 <= 0f;
            }
            if (!this._disabledBlizzardGraphic)
            {
                try
                {
                    if (flag)
                    {
                        float num21 = Main.cloudAlpha;
                        if (Main.remixWorld)
{
                            num21 = 0.4f;
                        }
                        this.MoveTowards(ref this._deerclopsBlizzardSmoothedEffect, (float)(NPC.IsADeerclopsNearScreen() ? 1 : 0), 0.0033333334f);
                        float num22 = Math.Min(1f, num21 * 2f) * this.outsideWeatherEffectIntensity;
                        float num23 = this.outsideWeatherEffectIntensity * 0.4f * Math.Min(1f, num21 * 2f) * 0.9f + 0.1f;
                        num23 = MathHelper.Lerp(num23, num23 * 0.5f, this._deerclopsBlizzardSmoothedEffect);
                        num22 = MathHelper.Lerp(num22, num22 * 0.5f, this._deerclopsBlizzardSmoothedEffect);
                        Filters.Scene["Blizzard"].GetShader().UseIntensity(num23);
                        Filters.Scene["Blizzard"].GetShader().UseOpacity(num22);
                        ((SimpleOverlay)Overlays.Scene["Blizzard"]).GetShader().UseOpacity(1f - num22);
                    }
                }
                catch
                {
                    this._disabledBlizzardGraphic = true;
                }
            }
            if (!this._disabledBlizzardSound)
            {
                try
                {
                    if (flag)
                    {
                        bool activeSound = SoundEngine.GetActiveSound(this._strongBlizzardSound) != null;
                        ActiveSound activeSound2 = SoundEngine.GetActiveSound(this._insideBlizzardSound);
                        if (!activeSound)
{
                            this._strongBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardStrongLoop);
                        }
                        if (activeSound2 == null)
{
                            this._insideBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardInsideBuildingLoop);
                        }
                        SoundEngine.GetActiveSound(this._strongBlizzardSound);
                        activeSound2 = SoundEngine.GetActiveSound(this._insideBlizzardSound);
                    }
                    this.MoveTowards(ref this._blizzardSoundVolume, (float)(flag ? 1 : 0), 0.01f);
                    float num24 = Math.Min(1f, Main.cloudAlpha * 2f) * this.outsideWeatherEffectIntensity;
                    ActiveSound activeSound3 = SoundEngine.GetActiveSound(this._strongBlizzardSound);
                    ActiveSound activeSound4 = SoundEngine.GetActiveSound(this._insideBlizzardSound);
                    if (this._blizzardSoundVolume > 0f)
                    {
                        if (activeSound3 == null)
{
                            this._strongBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardStrongLoop);
                            activeSound3 = SoundEngine.GetActiveSound(this._strongBlizzardSound);
                        }
                        activeSound3.Volume = num24 * this._blizzardSoundVolume;
                        if (activeSound4 == null)
{
                            this._insideBlizzardSound = SoundEngine.PlayTrackedSound(SoundID.BlizzardInsideBuildingLoop);
                            activeSound4 = SoundEngine.GetActiveSound(this._insideBlizzardSound);
                        }
                        activeSound4.Volume = (1f - num24) * this._blizzardSoundVolume;
                    }
                    else
                    {
                        if (activeSound3 != null)
{
                            activeSound3.Volume = 0f;
                        }
                        else
{
                            this._strongBlizzardSound = SlotId.Invalid;
                        }
                        if (activeSound4 != null)
{
                            activeSound4.Volume = 0f;
                        }
                        else
{
                            this._insideBlizzardSound = SlotId.Invalid;
                        }
                    }
                }
                catch
                {
                    this._disabledBlizzardSound = true;
                }
            }
        }
References Terraria.SceneState._blizzardSoundVolume, Terraria.SceneState._deerclopsBlizzardSmoothedEffect, Terraria.SceneState._disabledBlizzardGraphic, Terraria.SceneState._disabledBlizzardSound, Terraria.SceneState._insideBlizzardSound, Terraria.SceneState._outsideWeatherEffectIntensityBackingValue, Terraria.SceneState._strongBlizzardSound, System.Math.Abs(), Terraria.SceneMetrics.ActiveMonolithType, Terraria.SceneMetrics.BehindBackwall, Terraria.ID.SoundID.BlizzardInsideBuildingLoop, Terraria.ID.SoundID.BlizzardStrongLoop, Terraria.Main.bloodMoon, Terraria.SceneMetrics.BloodMoonMonolith, Terraria.Player.bloodMoonMonolithShader, Terraria.SceneMetrics.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utils.Clamp(), Terraria.SceneMetrics.CloseEnoughToNebulaTower, Terraria.SceneMetrics.CloseEnoughToSolarTower, Terraria.SceneMetrics.CloseEnoughToStardustTower, Terraria.SceneMetrics.CloseEnoughToVortexTower, Terraria.SceneMetrics.ClosestNPCPosition, Terraria.Main.cloudAlpha, Terraria.SceneMetrics.CRTMonolith, Terraria.Player.CRTMonolithShader, Terraria.Main.dedServ, Terraria.Player.dontStarveShader, Microsoft.Xna.Framework.Vector3.Dot(), Terraria.Audio.SoundEngine.GetActiveSound(), Terraria.Utils.GetLerpValue(), Terraria.Graphics.Effects.Filter.GetShader(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.GraveyardVisualIntensity, Terraria.Graphics.Effects.SkyManager.Instance, ReLogic.Utilities.SlotId.Invalid, Terraria.Graphics.Effects.Filter.IsActive(), Terraria.NPC.IsADeerclopsNearScreen(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.SceneState.ManageSpecialBiomeVisuals(), System.Math.Max(), Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Player.moonLordMonolithShader, Terraria.SceneState.MoveTowards(), Terraria.Player.nebulaMonolithShader, System.Random.NextDouble(), Terraria.SceneMetrics.NoirMonolith, Terraria.Player.noirShader, Terraria.Main.onlyDontStarveWorld, Terraria.SceneState.outsideWeatherEffectIntensity, Terraria.SceneMetrics.PerspectivePlayer, Terraria.Audio.SoundEngine.PlayTrackedSound(), Terraria.SceneMetrics.RadioThingMonolith, Terraria.Utils.Remap(), Terraria.Main.remixWorld, Terraria.SceneMetrics.RetroMonolith, Terraria.Player.retroMonolithShader, Terraria.Main.rockLayer, Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.Effects.Overlays.Scene, Terraria.GameContent.Events.Sandstorm.Severity, Terraria.GameContent.Events.Sandstorm.ShowSandstormVisuals(), Terraria.Player.solarMonolithShader, Terraria.Player.stardustMonolithShader, Terraria.Player.sunScorchCounter, Terraria.SceneMetrics.TileCenter, Terraria.Main.tileColor, Terraria.Main.UnderworldLayer, Terraria.GameContent.Events.MoonlordDeathDrama.Update(), Terraria.GameContent.Events.ScreenDarkness.Update(), Terraria.GameContent.Events.ScreenObstruction.Update(), Terraria.SceneState.UpdateGraveyard(), Terraria.SceneState.UpdateLightDecay(), Terraria.SceneState.UpdateRGBPeriheralProbe(), Terraria.SceneState.UpdateShimmer(), Terraria.Main.UseHeatDistortion, Terraria.Graphics.Shaders.ScreenShaderData.UseImageOffset(), Terraria.Graphics.Shaders.ScreenShaderData.UseIntensity(), Terraria.Graphics.Shaders.ScreenShaderData.UseProgress(), Terraria.Main.UseStormEffects, Terraria.Graphics.Shaders.ScreenShaderData.UseTargetPosition(), Terraria.Player.vortexMonolithShader, Terraria.Main.WaveQuality, Terraria.Main.windSpeedCurrent, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector3.Z, Microsoft.Xna.Framework.Vector2.Zero, Terraria.SceneMetrics.ZoneDesert, Terraria.SceneMetrics.ZoneRain, Terraria.SceneMetrics.ZoneSandstorm, and Terraria.SceneMetrics.ZoneSnow.
Referenced by Terraria.SceneState.Update().