Terraria Decompiled: Terraria.SceneState.ManageSpecialBiomeVisuals
ManageSpecialBiomeVisuals()
void Terraria.SceneState.ManageSpecialBiomeVisuals (string biomeName, bool inZone, Vector2 activationSource = default(Vector2), bool alwaysInstant = false) inline private
Definition at line 318 of file SceneState.cs.
        {
            if (SkyManager.Instance[biomeName] != null && inZone != SkyManager.Instance[biomeName].IsActive())
            {
                if (inZone)
                {
                    SkyManager.Instance.Activate(biomeName, activationSource, new object[0]);
                }
                else
                {
                    SkyManager.Instance.Deactivate(biomeName, new object[0]);
                }
            }
            Filter filter = Filters.Scene[biomeName];
            Overlay overlay = Overlays.Scene[biomeName];
            if (filter != null)
            {
                if (inZone != Filters.Scene[biomeName].IsActive())
                {
                    if (inZone)
                    {
                        Filters.Scene.Activate(biomeName, activationSource, new object[0]);
                    }
                    else
                    {
                        filter.Deactivate(new object[0]);
                    }
                }
                else if (inZone)
                {
                    filter.GetShader().UseTargetPosition(activationSource);
                }
            }
            if (overlay != null && inZone != (Overlays.Scene[biomeName].Mode != OverlayMode.Inactive))
            {
                if (inZone)
                {
                    Overlays.Scene.Activate(biomeName, activationSource, new object[0]);
                }
                else
                {
                    overlay.Deactivate(new object[0]);
                }
            }
            if (alwaysInstant || this.skipTransitions)
            {
                if (filter != null)
                {
                    filter.Opacity = (inZone ? 1f : 0f);
                }
                if (overlay != null)
                {
                    overlay.Opacity = (inZone ? 1f : 0f);
                }
            }
        }
References Terraria.Graphics.Effects.EffectManager< T >.Activate(), Terraria.Graphics.Effects.Filter.Deactivate(), Terraria.Graphics.Effects.GameEffect.Deactivate(), Terraria.Graphics.Effects.EffectManager< T >.Deactivate(), Terraria.Graphics.Effects.Filter.GetShader(), Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Graphics.Effects.Filters.Scene, Terraria.Graphics.Effects.Overlays.Scene, Terraria.SceneState.skipTransitions, and Terraria.Graphics.Shaders.ScreenShaderData.UseTargetPosition().
Referenced by Terraria.SceneState.ApplyVisuals().