Terraria Decompiled: System.Collections.ArrayList.InsertRange
InsertRange()
virtual void System.Collections.ArrayList.InsertRange (int index, ICollection c) inline virtual
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 412 of file ArrayList.cs.
        {
            if (c == null)
            {
                throw new ArgumentNullException("c", "Collection cannot be null.");
            }
            if (index < 0 || index > this._size)
            {
                throw new ArgumentOutOfRangeException("index", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            int count = c.Count;
            if (count > 0)
            {
                this.EnsureCapacity(this._size + count);
                if (index < this._size)
                {
                    Array.Copy(this._items, index, this._items, index + count, this._size - index);
                }
                object[] array = new object[count];
                c.CopyTo(array, 0);
                array.CopyTo(this._items, index);
                this._size += count;
                this._version++;
            }
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.array, System.Array.Copy(), System.Collections.ICollection.CopyTo(), System.Collections.ICollection.Count, System.count, System.Collections.ArrayList.EnsureCapacity(), and System.index.
Referenced by System.Collections.ArrayList.AddRange(), System.Collections.ArrayList.Range.AddRange(), System.Collections.ArrayList.IListWrapper.InsertRange(), System.Collections.ArrayList.SyncArrayList.InsertRange(), and System.Collections.ArrayList.Range.InsertRange().