Terraria Decompiled: System.Collections.ArrayList.Add
Add()
virtual int System.Collections.ArrayList.Add (object value) inline virtual
Implements System.Collections.IList.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList.SyncArrayList, and System.Collections.ArrayList.Range.
Definition at line 175 of file ArrayList.cs.
        {
            if (this._size == this._items.Length)
            {
                this.EnsureCapacity(this._size + 1);
            }
            this._items[this._size] = value;
            this._version++;
            int size = this._size;
            this._size = size + 1;
            return size;
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.Collections.ArrayList.EnsureCapacity(), and System.value.
Referenced by System.Security.Policy.ApplicationTrustCollection.Add(), Mono.Security.ASN1.Add(), System.Security.Principal.IdentityReferenceCollection.Add(), System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.Add(), System.Collections.ArrayList.SyncArrayList.Add(), System.Collections.CollectionBase.Add(), System.Security.Policy.Evidence.AddAssembly(), System.Security.SecurityElement.AddAttribute(), System.Security.Policy.CodeGroup.AddChild(), System.Security.SecurityElement.AddChild(), System.Security.Policy.PolicyLevel.AddFullTrustAssembly(), System.Security.Policy.Evidence.AddHost(), System.Security.Permissions.FileIOPermission.AddPathInternal(), System.Security.Permissions.EnvironmentPermission.AddPathList(), System.Security.PermissionSet.AddPermission(), System.Security.Policy.ApplicationTrustCollection.AddRange(), System.Security.Policy.ApplicationTrustCollection.AddRange(), System.Runtime.Remoting.Messaging.CADMethodReturnMessage.CADMethodReturnMessage(), Terraria.Utils.ConvertMonoArgsToDotNet(), System.Runtime.Remoting.ChannelData.CopyFrom(), System.Security.Policy.PolicyLevel.CreateDefaultFullTrustAssemblies(), System.Security.Policy.PolicyLevel.CreateDefaultNamedPermissionSets(), System.Reflection.Emit.AssemblyBuilder.DefineResource(), System.Security.Permissions.StrongNameIdentityPermission.FromXml(), System.Security.Policy.PolicyLevel.FromXml(), System.Security.Permissions.PrincipalPermission.FromXml(), System.Security.PermissionSet.FromXml(), System.Security.SecurityDocument.GetChildrenPositionForElement(), System.Reflection.Emit.ILGenerator.MarkSequencePoint(), System.Runtime.Remoting.ConfigHandler.ParseElement(), System.Security.PermissionSet.PermissionSet(), System.Security.PermissionSet.PermissionSet(), System.Security.Permissions.PrincipalPermission.PrincipalPermission(), System.Security.Permissions.PrincipalPermission.PrincipalPermission(), System.Runtime.Remoting.ConfigHandler.ReadChannel(), System.Runtime.Remoting.ConfigHandler.ReadClientActivated(), System.Runtime.Remoting.ConfigHandler.ReadClientWellKnown(), System.Resources.Win32ResFileReader.ReadResources(), System.Runtime.Remoting.ConfigHandler.ReadServiceActivated(), System.Runtime.Remoting.ConfigHandler.ReadServiceWellKnown(), System.Runtime.Remoting.Lifetime.Lease.Register(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig(), System.Runtime.Remoting.Contexts.DynamicPropertyCollection.RegisterDynamicProperty(), System.Runtime.Remoting.Services.TrackingServices.RegisterTrackingHandler(), System.Collections.ArrayList.Repeat(), System.Security.Permissions.StrongNameIdentityPermission.ResetToDefault(), System.Security.SecurityManager.ResolvePolicyGroups(), System.Security.Permissions.EnvironmentPermission.SetPathList(), System.Security.Permissions.RegistryPermission.SetPathList(), System.Security.PermissionSet.SetPermission(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.StoreUserPropertiesForMethodMessage(), System.Security.Permissions.StrongNameIdentityPermission.StrongNameIdentityPermission(), System.Security.Permissions.StrongNameIdentityPermission.StrongNameIdentityPermission(), System.Security.Permissions.StrongNameIdentityPermission.StrongNameIdentityPermission(), System.Runtime.Remoting.Lifetime.LeaseManager.TrackLifetime(), and FullSerializer.Internal.fsArrayConverter.TryDeserialize().