Terraria Decompiled: System.Collections.ArrayList.RemoveAt
RemoveAt()
virtual void System.Collections.ArrayList.RemoveAt (int index) inline virtual
Implements System.Collections.IList.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 503 of file ArrayList.cs.
        {
            if (index < 0 || index >= this._size)
            {
                throw new ArgumentOutOfRangeException("index", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            this._size--;
            if (index < this._size)
            {
                Array.Copy(this._items, index + 1, this._items, index, this._size - index);
            }
            this._items[this._size] = null;
            this._version++;
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, and System.Array.Copy().
Referenced by System.Collections.CollectionBase.Add(), System.Collections.CollectionBase.Insert(), System.Runtime.Remoting.Lifetime.LeaseManager.ManageLeases(), System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.Remove(), System.Collections.ArrayList.Remove(), System.Collections.CollectionBase.Remove(), System.Security.Policy.ApplicationTrustCollection.RemoveAllInstances(), System.Collections.ArrayList.SyncArrayList.RemoveAt(), System.Collections.ArrayList.Range.RemoveAt(), System.Collections.CollectionBase.RemoveAt(), System.Security.Policy.Evidence.RemoveType(), System.Runtime.Remoting.Lifetime.Lease.Unregister(), System.Runtime.Remoting.Channels.ChannelServices.UnregisterChannel(), System.Runtime.Remoting.Contexts.DynamicPropertyCollection.UnregisterDynamicProperty(), and System.Runtime.Remoting.Services.TrackingServices.UnregisterTrackingHandler().