Terraria Decompiled: System.Collections.ArrayList.Insert
Insert()
virtual void System.Collections.ArrayList.Insert (int index, object value) inline virtual
Implements System.Collections.IList.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, System.Collections.ArrayList.SyncArrayList, and System.Collections.ArrayList.Range.
Definition at line 392 of file ArrayList.cs.
        {
            if (index < 0 || index > this._size)
            {
                throw new ArgumentOutOfRangeException("index", "Insertion index was out of range. Must be non-negative and less than or equal to size.");
            }
            if (this._size == this._items.Length)
            {
                this.EnsureCapacity(this._size + 1);
            }
            if (index < this._size)
            {
                Array.Copy(this._items, index, this._items, index + 1, this._size - index);
            }
            this._items[index] = value;
            this._size++;
            this._version++;
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.Array.Copy(), System.Collections.ArrayList.EnsureCapacity(), System.index, and System.value.
Referenced by System.Collections.ArrayList.Range.Add(), System.Collections.ArrayList.SyncArrayList.Insert(), System.Collections.ArrayList.Range.Insert(), System.Collections.CollectionBase.Insert(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel(), System.Collections.CollectionBase.Remove(), and System.Collections.CollectionBase.RemoveAt().