Terraria Decompiled: System.Collections.ArrayList.LastIndexOf
LastIndexOf() [1/3]
virtual int System.Collections.ArrayList.LastIndexOf (object value) inline virtual
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 439 of file ArrayList.cs.
        {
            return this.LastIndexOf(value, this._size - 1, this._size);
        }
References System.Collections.ArrayList._size, and System.Collections.ArrayList.LastIndexOf().
Referenced by System.Collections.ArrayList.LastIndexOf(), System.Collections.ArrayList.SyncArrayList.LastIndexOf(), System.Collections.ArrayList.FixedSizeArrayList.LastIndexOf(), System.Collections.ArrayList.ReadOnlyArrayList.LastIndexOf(), System.Collections.ArrayList.Range.LastIndexOf(), System.Collections.ArrayList.LastIndexOf(), System.Collections.ArrayList.SyncArrayList.LastIndexOf(), System.Collections.ArrayList.FixedSizeArrayList.LastIndexOf(), System.Collections.ArrayList.ReadOnlyArrayList.LastIndexOf(), System.Collections.ArrayList.SyncArrayList.LastIndexOf(), System.Collections.ArrayList.FixedSizeArrayList.LastIndexOf(), System.Collections.ArrayList.ReadOnlyArrayList.LastIndexOf(), and System.Collections.ArrayList.Range.LastIndexOf().