Terraria Decompiled: System.Collections.ArrayList.RemoveRange
RemoveRange()
virtual void System.Collections.ArrayList.RemoveRange (int index, int count) inline virtual
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 519 of file ArrayList.cs.
        {
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (this._size - index < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            if (count > 0)
            {
                int i = this._size;
                this._size -= count;
                if (index < this._size)
                {
                    Array.Copy(this._items, index + count, this._items, index, this._size - index);
                }
                while (i > this._size)
                {
                    this._items[--i] = null;
                }
                this._version++;
            }
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.Array.Copy(), System.count, and System.index.
Referenced by System.Collections.ArrayList.Range.Clear(), System.Collections.ArrayList.SyncArrayList.RemoveRange(), and System.Collections.ArrayList.Range.RemoveRange().