Terraria Decompiled: System.Collections.ArrayList.Clone
Clone()
virtual object System.Collections.ArrayList.Clone () inline virtual
Implements System.ICloneable.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 236 of file ArrayList.cs.
        {
            ArrayList arrayList = new ArrayList(this._size);
            arrayList._size = this._size;
            arrayList._version = this._version;
            Array.Copy(this._items, 0, arrayList._items, 0, this._size);
            return arrayList;
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, System.Collections.ArrayList.ArrayList(), and System.Array.Copy().
Referenced by System.Collections.ArrayList.SyncArrayList.Clone(), System.Collections.ArrayList.FixedSizeArrayList.Clone(), System.Collections.ArrayList.ReadOnlyArrayList.Clone(), System.Collections.ArrayList.Range.Clone(), System.Threading.CompressedStack.CompressedStack(), System.Security.Permissions.FileIOPermission.Copy(), and System.Security.Permissions.PrincipalPermission.PrincipalPermission().