Terraria Decompiled: System.Collections.ArrayList.Clear
Clear()
virtual void System.Collections.ArrayList.Clear () inline virtual
Implements System.Collections.IList.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, System.Collections.ArrayList.ReadOnlyArrayList, and System.Collections.ArrayList.Range.
Definition at line 225 of file ArrayList.cs.
        {
            if (this._size > 0)
            {
                Array.Clear(this._items, 0, this._size);
                this._size = 0;
            }
            this._version++;
        }
References System.Collections.ArrayList._items, System.Collections.ArrayList._size, System.Collections.ArrayList._version, and System.Array.Clear().
Referenced by System.Collections.ArrayList.SyncArrayList.Clear(), System.Collections.CollectionBase.Clear(), System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.Clear(), System.Security.PermissionSet.Clear(), System.Security.Policy.ApplicationTrustCollection.Clear(), System.Security.Policy.Evidence.Clear(), System.Security.Principal.IdentityReferenceCollection.Clear(), System.Security.Permissions.FileIOPermission.Clear(), System.Security.Policy.PolicyLevel.CreateDefaultFullTrustAssemblies(), System.Security.Policy.PolicyLevel.CreateDefaultNamedPermissionSets(), System.Security.Permissions.StrongNameIdentityPermission.FromXml(), System.Security.Policy.PolicyLevel.FromXml(), System.Security.Policy.CodeGroup.FromXml(), System.Security.Permissions.PrincipalPermission.FromXml(), System.Security.PermissionSet.FromXml(), System.Security.Policy.PolicyLevel.Reset(), System.Security.Permissions.StrongNameIdentityPermission.ResetToDefault(), System.Security.Permissions.EnvironmentPermission.SetPathList(), and System.Security.Permissions.RegistryPermission.SetPathList().