Terraria Decompiled: System.Collections.ArrayList.Remove
Remove()
virtual void System.Collections.ArrayList.Remove (object obj) inline virtual
Implements System.Collections.IList.
Reimplemented in System.Collections.ArrayList.IListWrapper, System.Collections.ArrayList.SyncArrayList, System.Collections.ArrayList.FixedSizeArrayList, and System.Collections.ArrayList.ReadOnlyArrayList.
Definition at line 493 of file ArrayList.cs.
        {
            int num = this.IndexOf(obj);
            if (num >= 0)
            {
                this.RemoveAt(num);
            }
        }
References System.Collections.ArrayList.IndexOf(), and System.Collections.ArrayList.RemoveAt().
Referenced by System.Runtime.Remoting.Channels.ChannelServices.CreateClientChannelSinkChain(), System.Collections.ArrayList.SyncArrayList.Remove(), System.Security.Policy.CodeGroup.RemoveChild(), and System.Runtime.Remoting.Lifetime.LeaseManager.StopTrackingLifetime().