Terraria Decompiled: System.Text.Latin1Encoding.GetByteCount
GetByteCount()
unsafe override int System.Text.Latin1Encoding.GetByteCount (char * chars, int charCount, EncoderNLS encoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 35 of file Latin1Encoding.cs.
        {
            char c = '\0';
            EncoderReplacementFallback encoderReplacementFallback;
            if (encoder != null)
            {
                c = encoder._charLeftOver;
                encoderReplacementFallback = encoder.Fallback as EncoderReplacementFallback;
            }
            else
            {
                encoderReplacementFallback = base.EncoderFallback as EncoderReplacementFallback;
            }
            if (encoderReplacementFallback != null && encoderReplacementFallback.MaxCharCount == 1)
            {
                if (c > '\0')
                {
                    charCount++;
                }
                return charCount;
            }
            int num = 0;
            char* ptr = chars + charCount;
            EncoderFallbackBuffer encoderFallbackBuffer = null;
            if (c > '\0')
            {
                encoderFallbackBuffer = encoder.FallbackBuffer;
                encoderFallbackBuffer.InternalInitialize(chars, ptr, encoder, false);
                char* ptr2 = chars;
                encoderFallbackBuffer.InternalFallback(c, ref ptr2);
                chars = ptr2;
            }
            char c2;
            while ((c2 = ((encoderFallbackBuffer == null) ? '\0' : encoderFallbackBuffer.InternalGetNextChar())) != '\0' || chars < ptr)
            {
                if (c2 == '\0')
                {
                    c2 = *chars;
                    chars++;
                }
                if (c2 > 'ÿ')
                {
                    if (encoderFallbackBuffer == null)
                    {
                        if (encoder == null)
{
                            encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
                        }
                        else
{
                            encoderFallbackBuffer = encoder.FallbackBuffer;
                        }
                        encoderFallbackBuffer.InternalInitialize(ptr - charCount, ptr, encoder, false);
                    }
                    char* ptr2 = chars;
                    encoderFallbackBuffer.InternalFallback(c2, ref ptr2);
                    chars = ptr2;
                }
                else
                {
                    num++;
                }
            }
            return num;
        }
References System.Text.EncoderNLS._charLeftOver, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.FallbackBuffer, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.EncoderFallbackBuffer.InternalInitialize(), and System.Text.EncoderReplacementFallback.MaxCharCount.