Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom
RegularRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 38 of file RegularDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            RegularDungeonRoomSettings regularDungeonRoomSettings = (RegularDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Point center = new Point(i, j);
            if (base.Processed)
            {
                center = this.InnerBounds.Center;
            }
            int num = 6 + unifiedRandom.Next(7);
            int num2 = 8;
            if (regularDungeonRoomSettings.OverrideInnerBoundsSize > 0)
            {
                num = regularDungeonRoomSettings.OverrideInnerBoundsSize;
            }
            if (regularDungeonRoomSettings.OverrideOuterBoundsSize > 0)
            {
                num2 = regularDungeonRoomSettings.OverrideOuterBoundsSize;
            }
            if (base.Processed)
            {
                num = this._innerBoundsSize;
            }
            int num3 = num + num2;
            this.InnerBounds.SetBounds(center.X, center.Y, center.X, center.Y);
            this.OuterBounds.SetBounds(center.X, center.Y, center.X, center.Y);
            this.OuterBounds.UpdateBounds(center.X - num3, center.Y - num3, center.X + num3, center.Y + num3);
            this.InnerBounds.UpdateBounds(this.OuterBounds.Left + num2, this.OuterBounds.Top + num2, this.OuterBounds.Right - num2, this.OuterBounds.Bottom - num2);
            base.GenerateDungeonSquareRoom(data, this.InnerBounds, this.OuterBounds, center, brickTileType, brickWallType, num, num3, generating, generating);
            this._innerBoundsSize = num;
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom._innerBoundsSize, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoomSettings.OverrideInnerBoundsSize, Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoomSettings.OverrideOuterBoundsSize, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.GenerateRoom().