Terraria Decompiled: Terraria.DataStructures.SpriteFrame.GetSourceRectangle
GetSourceRectangle()
Rectangle Terraria.DataStructures.SpriteFrame.GetSourceRectangle (Texture2D texture) inline
Definition at line 72 of file SpriteFrame.cs.
        {
            int num = texture.Width / (int)this.ColumnCount;
            int num2 = texture.Height / (int)this.RowCount;
            return new Rectangle((int)this.CurrentColumn * num, (int)this.CurrentRow * num2, num - ((this.ColumnCount == 1) ? 0 : this.PaddingX), num2 - ((this.RowCount == 1) ? 0 : this.PaddingY));
        }
References Terraria.DataStructures.SpriteFrame.ColumnCount, Terraria.DataStructures.SpriteFrame.CurrentColumn, Terraria.DataStructures.SpriteFrame.CurrentRow, int, Terraria.DataStructures.SpriteFrame.PaddingX, Terraria.DataStructures.SpriteFrame.PaddingY, and Terraria.DataStructures.SpriteFrame.RowCount.
Referenced by Terraria.Map.MapOverlayDrawContext.Draw(), Terraria.Map.MapOverlayDrawContext.Draw(), Terraria.Map.MapOverlayDrawContext.DrawClamped(), Terraria.Main.DrawGore(), Terraria.Main.DrawGoreBehind(), Terraria.Map.MapOverlayDrawContext.GetClampedDrawRegion(), and Terraria.Map.MapOverlayDrawContext.GetUnclampedDrawRegion().