Terraria Decompiled: System.Version.CompareTo
CompareTo() [1/2]
int System.Version.CompareTo (object version) inline
Implements System.IComparable< in T >.
Definition at line 164 of file Version.cs.
        {
            if (version == null)
            {
                return 1;
            }
            Version version2 = version as Version;
            if (version2 == null)
            {
                throw new ArgumentException("Object must be of type Version.");
            }
            return this.CompareTo(version2);
        }
References System.Version.CompareTo(), and System.Version.Version().
Referenced by System.Version.CompareTo(), System.Version.operator<(), and System.Version.operator<=().