Terraria Decompiled: System.Version.ParseVersion
ParseVersion()
static Version System.Version.ParseVersion (ReadOnlySpan< char > input, bool throwOnFailure) inline static private
Definition at line 408 of file Version.cs.
        {
            int num = input.IndexOf('.');
            if (num < 0)
            {
                if (throwOnFailure)
                {
                    throw new ArgumentException("Version string portion was too short or too long.", "input");
                }
                return null;
            }
            else
            {
                int num2 = -1;
                int num3 = input.Slice(num + 1).IndexOf('.');
                if (num3 != -1)
                {
                    num3 += num + 1;
                    num2 = input.Slice(num3 + 1).IndexOf('.');
                    if (num2 != -1)
                    {
                        num2 += num3 + 1;
                        if (input.Slice(num2 + 1).IndexOf('.') != -1)
{
                            if (throwOnFailure)
{
                                throw new ArgumentException("Version string portion was too short or too long.", "input");
                            }
                            return null;
                        }
                    }
                }
                int num4;
                if (!Version.TryParseComponent(input.Slice(0, num), "input", throwOnFailure, out num4))
                {
                    return null;
                }
                if (num3 != -1)
                {
                    int num5;
                    if (!Version.TryParseComponent(input.Slice(num + 1, num3 - num - 1), "input", throwOnFailure, out num5))
                    {
                        return null;
                    }
                    if (num2 != -1)
                    {
                        int num6;
                        int num7;
                        if (!Version.TryParseComponent(input.Slice(num3 + 1, num2 - num3 - 1), "build", throwOnFailure, out num6) || !Version.TryParseComponent(input.Slice(num2 + 1), "revision", throwOnFailure, out num7))
{
                            return null;
                        }
                        return new Version(num4, num5, num6, num7);
                    }
                    else
                    {
                        int num6;
                        if (!Version.TryParseComponent(input.Slice(num3 + 1), "build", throwOnFailure, out num6))
{
                            return null;
                        }
                        return new Version(num4, num5, num6);
                    }
                }
                else
                {
                    int num5;
                    if (!Version.TryParseComponent(input.Slice(num + 1), "input", throwOnFailure, out num5))
                    {
                        return null;
                    }
                    return new Version(num4, num5);
                }
            }
        }
References System.input, System.Version.TryParseComponent(), and System.Version.Version().
Referenced by System.Version.Parse(), System.Version.Parse(), System.Version.TryParse(), and System.Version.TryParse().