Terraria Decompiled: System.Version.ToCachedStringBuilder
ToCachedStringBuilder()
StringBuilder System.Version.ToCachedStringBuilder (int fieldCount) inline private
Definition at line 327 of file Version.cs.
        {
            if (fieldCount == 2)
            {
                StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
                stringBuilder.Append(this._Major);
                stringBuilder.Append('.');
                stringBuilder.Append(this._Minor);
                return stringBuilder;
            }
            if (this._Build == -1)
            {
                throw new ArgumentException(SR.Format("Argument must be between {0} and {1}.", "0", "2"), "fieldCount");
            }
            if (fieldCount == 3)
            {
                StringBuilder stringBuilder2 = StringBuilderCache.Acquire(16);
                stringBuilder2.Append(this._Major);
                stringBuilder2.Append('.');
                stringBuilder2.Append(this._Minor);
                stringBuilder2.Append('.');
                stringBuilder2.Append(this._Build);
                return stringBuilder2;
            }
            if (this._Revision == -1)
            {
                throw new ArgumentException(SR.Format("Argument must be between {0} and {1}.", "0", "3"), "fieldCount");
            }
            if (fieldCount == 4)
            {
                StringBuilder stringBuilder3 = StringBuilderCache.Acquire(16);
                stringBuilder3.Append(this._Major);
                stringBuilder3.Append('.');
                stringBuilder3.Append(this._Minor);
                stringBuilder3.Append('.');
                stringBuilder3.Append(this._Build);
                stringBuilder3.Append('.');
                stringBuilder3.Append(this._Revision);
                return stringBuilder3;
            }
            throw new ArgumentException(SR.Format("Argument must be between {0} and {1}.", "0", "4"), "fieldCount");
        }
References System.Version._Build, System.Version._Major, System.Version._Minor, System.Version._Revision, System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), and SR.Format().
Referenced by System.Version.ToString(), and System.Version.TryFormat().