Terraria Decompiled: System.Version.Equals
Equals() [1/2]
override bool System.Version.Equals (object obj) inline
Definition at line 234 of file Version.cs.
        {
            return this.Equals(obj as Version);
        }
References System.Version.Equals().
Referenced by System.Security.Policy.StrongNameMembershipCondition.Check(), System.Security.Permissions.StrongNameIdentityPermission.Contains(), System.Security.Policy.StrongName.Equals(), System.Security.Policy.StrongNameMembershipCondition.Equals(), System.Version.Equals(), System.Security.Permissions.StrongNameIdentityPermission.Intersect(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Security.Permissions.StrongNameIdentityPermission.SNIP.IsSubsetOf(), and System.Version.operator==().