Terraria Decompiled: System.Version.TryFormat
TryFormat() [1/3]
bool System.Version.TryFormat (Span< char > destination, int fieldCount, out int charsWritten) inline
Definition at line 278 of file Version.cs.
        {
            if (fieldCount == 0)
            {
                charsWritten = 0;
                return true;
            }
            if (fieldCount == 1)
            {
                return this._Major.TryFormat(destination, out charsWritten, default(ReadOnlySpan<char>), null);
            }
            StringBuilder stringBuilder = this.ToCachedStringBuilder(fieldCount);
            if (stringBuilder.Length <= destination.Length)
            {
                stringBuilder.CopyTo(0, destination, stringBuilder.Length);
                StringBuilderCache.Release(stringBuilder);
                charsWritten = stringBuilder.Length;
                return true;
            }
            StringBuilderCache.Release(stringBuilder);
            charsWritten = 0;
            return false;
        }
References System.Version._Major, System.Text.StringBuilder.CopyTo(), System.destination, System.Text.StringBuilder.Length, System.Text.StringBuilderCache.Release(), and System.Version.ToCachedStringBuilder().