Terraria Decompiled: rail.IRailFloatingWindowImpl.SetNotifyWindowPosition
SetNotifyWindowPosition()
virtual RailResult rail.IRailFloatingWindowImpl.SetNotifyWindowPosition (EnumRailNotifyWindowType window_type, RailWindowLayout layout) inline virtual
Implements rail.IRailFloatingWindow.
Definition at line 32 of file IRailFloatingWindowImpl.cs.
        {
            IntPtr intPtr = ((layout == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailWindowLayout__SWIG_0());
            if (layout != null)
            {
                RailConverter.Csharp2Cpp(layout, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailFloatingWindow_SetNotifyWindowPosition(this.swigCPtr_, (int)window_type, intPtr);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailWindowLayout(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailWindowLayout(), rail.RAIL_API_PINVOKE.IRailFloatingWindow_SetNotifyWindowPosition(), rail.RAIL_API_PINVOKE.new_RailWindowLayout__SWIG_0(), and System.IntPtr.Zero.