Terraria Decompiled: Terraria.WorldGen.Hooks.Initialize
Initialize()
static void Terraria.WorldGen.Hooks.Initialize () inline static
Definition at line 91793 of file WorldGen.cs.
            {
                Player.Hooks.OnEnterWorld += delegate(Player player)
                {
                    if (player.whoAmI == Main.myPlayer)
                    {
                        WorldGen.Hooks.WorldLoaded();
                        if (Main.netMode != 1)
{
                            Main.FixUIScale();
                        }
                    }
                };
                WorldGen.Hooks.OnWorldLoad += WorldGen.mysticLogsEvent.StartWorld;
                WorldGen.Hooks.OnWorldLoad += Main.checkHalloween;
                WorldGen.Hooks.OnWorldLoad += Main.checkXMas;
            }
References Terraria.Main.checkHalloween(), Terraria.Main.checkXMas(), Terraria.Main.FixUIScale(), Terraria.Main.myPlayer, Terraria.WorldGen.mysticLogsEvent, Terraria.Main.netMode, Terraria.GameContent.Events.MysticLogFairiesEvent.StartWorld(), Terraria.Entity.whoAmI, and Terraria.WorldGen.Hooks.WorldLoaded().
Referenced by Terraria.Main.Initialize_AlmostEverything().