Terraria Decompiled: ReLogic.Content.AssetRepository.SetSources
SetSources()
void ReLogic.Content.AssetRepository.SetSources (IEnumerable< IContentSource > sources, AssetRequestMode mode = AssetRequestMode::ImmediateLoad) inline
Implements ReLogic.Content.IAssetRepository.
Definition at line 172 of file AssetRepository.cs.
        {
            this.ThrowIfDisposed();
            object requestLock = this._requestLock;
            lock (requestLock)
            {
                while (this._asyncLoader.Remaining > 0)
                {
                    this._asyncLoader.TransferCompleted();
                }
                this._sources = Enumerable.ToList<IContentSource>(sources);
                this.ReloadAssetsIfSourceChanged(mode);
            }
            if (this._changeWatcher != null)
            {
                this._changeWatcher.UpdateSources(sources);
            }
        }
References ReLogic.Content.AssetRepository._asyncLoader, ReLogic.Content.AssetRepository._changeWatcher, ReLogic.Content.AssetRepository._requestLock, ReLogic.Content.AssetRepository.mode, ReLogic.Content.AssetRepository.ReloadAssetsIfSourceChanged(), ReLogic.Content.IAsyncAssetLoader.Remaining, ReLogic.Content.AssetRepository.ThrowIfDisposed(), ReLogic.Content.IAsyncAssetLoader.TransferCompleted(), and ReLogic.Content.AssetChangeWatcher.UpdateSources().