Terraria Decompiled: ReLogic.Content.AssetRepository.Request< T >
Request< T >()
Asset< T > ReLogic.Content.AssetRepository.Request< T > (string assetName, AssetRequestMode mode = AssetRequestMode::ImmediateLoad) inline
Implements ReLogic.Content.IAssetRepository.
Type Constraints
T : class
Definition at line 192 of file AssetRepository.cs.
                                                                                                                     : class
        {
            this.ThrowIfDisposed();
            assetName = AssetPathHelper.CleanPath(assetName);
            object requestLock = this._requestLock;
            Asset<T> asset3;
            lock (requestLock)
            {
                Asset<T> asset = null;
                IAsset asset2;
                if (this._assets.TryGetValue(assetName, ref asset2))
                {
                    asset = asset2 as Asset<T>;
                }
                if (asset == null)
                {
                    asset = new Asset<T>(assetName);
                    this._assets[assetName] = asset;
                }
                else if (asset.State != AssetState.NotLoaded)
                {
                    return asset;
                }
                this.LoadAsset<T>(asset, mode);
                asset3 = asset;
            }
            return asset3;
        }
References ReLogic.Content.AssetRepository._assets, ReLogic.Content.AssetRepository._requestLock, ReLogic.Content.AssetRepository.asset, ReLogic.Content.AssetPathHelper.CleanPath(), ReLogic.Content.AssetRepository.LoadAsset< T >(), ReLogic.Content.AssetRepository.mode, and ReLogic.Content.AssetRepository.ThrowIfDisposed().