Terraria Decompiled: ReLogic.Content.AssetRepository.UpdateWatchedAsset
UpdateWatchedAsset()
bool ReLogic.Content.AssetRepository.UpdateWatchedAsset (IContentSource source, string path, string fullPath) inline private
Definition at line 261 of file AssetRepository.cs.
        {
            string extension = Path.GetExtension(path);
            string text = path.Substring(0, path.Length - extension.Length);
            object requestLock = this._requestLock;
            bool flag2;
            lock (requestLock)
            {
                if (!source.HasAsset(text))
                {
                    source.Refresh();
                }
                IAsset asset;
                if (!this._assets.TryGetValue(text, ref asset))
                {
                    flag2 = false;
                }
                else if (!asset.IsLoaded)
                {
                    flag2 = true;
                }
                else
                {
                    IContentSource source2 = asset.Source;
                    if (source != asset.Source && source != this.FindSourceForAsset(asset.Name))
                    {
                        flag2 = true;
                    }
                    else
                    {
                        try
{
                            if (!this.UpdateAssetValue(asset, source, extension, () => File.OpenRead(fullPath)))
{
                                return false;
                            }
                            if (this.AssetWatcherValueUpdatedHandler != null)
{
                                this.AssetWatcherValueUpdatedHandler(asset);
                            }
                        }
                        catch (Exception ex)
{
                            if (this.AssetWatcherUpdateFailedHandler != null)
{
                                this.AssetWatcherUpdateFailedHandler(asset, ex);
                            }
                        }
                        flag2 = true;
                    }
                }
            }
            return flag2;
        }
References ReLogic.Content.AssetRepository._assets, ReLogic.Content.AssetRepository._requestLock, ReLogic.Content.AssetRepository.asset, ReLogic.Content.AssetRepository.AssetWatcherUpdateFailedHandler, ReLogic.Content.AssetRepository.AssetWatcherValueUpdatedHandler, System.IO.Path.GetExtension(), ReLogic.Content.Sources.IContentSource.HasAsset(), System.IO.File.OpenRead(), ReLogic.Content.Sources.IContentSource.Refresh(), ReLogic.Content.AssetRepository.source, System.text, and ReLogic.Content.AssetRepository.UpdateAssetValue().
Referenced by ReLogic.Content.AssetRepository.UpdateWatchedAssetChanges().