Terraria Decompiled: ReLogic.Content.AssetRepository.UpdateAssetValue< T >
UpdateAssetValue< T >()
bool ReLogic.Content.AssetRepository.UpdateAssetValue< T > (IAsset asset, IContentSource source, string extension, Func< Stream > getStream) inline private
Type Constraints
T : class
Definition at line 480 of file AssetRepository.cs.
                                                                                                                                : class
        {
            T t;
            if (!this._loader.TryLoad<T>(extension, getStream, out t))
            {
                return false;
            }
            IContentValidator contentValidator = source.ContentValidator;
            IRejectionReason rejectionReason;
            if (contentValidator != null && !contentValidator.AssetIsValid<T>(t, asset.Name, out rejectionReason))
            {
                throw AssetLoadException.RejectedByValidator(rejectionReason);
            }
            this.SubmitLoadedContent<T>((Asset<T>)asset, t, source);
            return true;
        }
References ReLogic.Content.AssetRepository._loader, ReLogic.Content.AssetRepository.asset, ReLogic.Content.Sources.IContentSource.ContentValidator, ReLogic.Content.AssetLoadException.RejectedByValidator(), ReLogic.Content.AssetRepository.source, and ReLogic.Content.AssetRepository.SubmitLoadedContent< T >().
Referenced by ReLogic.Content.AssetRepository.EnsureTypeSpecificActionsExist< T >().