Terraria Decompiled: ReLogic.Content.AssetRepository.ReloadAssetsIfSourceChanged
ReloadAssetsIfSourceChanged()
void ReLogic.Content.AssetRepository.ReloadAssetsIfSourceChanged (AssetRequestMode mode) inline private
Definition at line 317 of file AssetRepository.cs.
        {
            foreach (IAsset asset2 in Enumerable.Where<IAsset>(this._assets.Values, (IAsset asset) => asset.IsLoaded))
            {
                IContentSource contentSource = this.FindSourceForAsset(asset2.Name);
                if (contentSource == null)
                {
                    this.ForceReloadAsset(asset2, AssetRequestMode.DoNotLoad);
                }
                else if (asset2.Source != contentSource)
                {
                    this.ForceReloadAsset(asset2, (asset2.State == AssetState.NotLoaded) ? AssetRequestMode.DoNotLoad : mode);
                }
            }
        }
References ReLogic.Content.AssetRepository.asset, ReLogic.Content.AssetRepository.FindSourceForAsset(), ReLogic.Content.AssetRepository.ForceReloadAsset(), ReLogic.Content.AssetRepository.mode, ReLogic.Content.IAsset.Name, ReLogic.Content.IAsset.Source, and ReLogic.Content.IAsset.State.
Referenced by ReLogic.Content.AssetRepository.SetSources().