Terraria Decompiled: ReLogic.Content.AssetRepository.TryLoadingAsset< T >
TryLoadingAsset< T >()
void ReLogic.Content.AssetRepository.TryLoadingAsset< T > (Asset< T > asset, AssetRequestMode mode) inline private
Type Constraints
T : class
Definition at line 359 of file AssetRepository.cs.
                                                                                       : class
        {
            IContentSource source = this.FindSourceForAsset(asset.Name);
            AssetRequestMode mode2 = mode;
            if (mode2 == AssetRequestMode.ImmediateLoad)
            {
                bool flag = true;
                IRejectionReason rejectionReason = null;
                T t;
                try
                {
                    if (!this._loader.TryLoad<T>(asset.Name, source, out t))
                    {
                        source.RejectAsset(asset.Name, new ContentRejectionFromFailedLoad_ByAssetExtensionType());
                        this.TryLoadingAsset<T>(asset, mode);
                        return;
                    }
                }
                catch (Exception ex)
                {
                    bool flag2 = false;
                    if (ex is UnauthorizedAccessException)
                    {
                        flag2 = true;
                    }
                    if (ex is FileNotFoundException)
                    {
                        flag2 = true;
                    }
                    if (ex is DirectoryNotFoundException)
                    {
                        flag2 = true;
                    }
                    if (ex is AssetLoadException)
                    {
                        flag2 = true;
                    }
                    if (flag2)
                    {
                        throw;
                    }
                    throw AssetLoadException.FromAssetException(asset.Name, ex);
                }
                if (source.ContentValidator != null)
                {
                    flag = source.ContentValidator.AssetIsValid<T>(t, asset.Name, out rejectionReason);
                }
                if (flag)
                {
                    this.SubmitLoadedContent<T>(asset, t, source);
                    int loadedAssets = this.LoadedAssets;
                    this.LoadedAssets = loadedAssets + 1;
                    return;
                }
                source.RejectAsset(asset.Name, rejectionReason);
                this.TryLoadingAsset<T>(asset, mode);
                return;
            }
            if (mode2 != AssetRequestMode.AsyncLoad)
            {
                throw new ArgumentOutOfRangeException("mode", mode, null);
            }
            this._asyncLoader.Load<T>(asset.Name, source, delegate(bool proper, T content)
            {
                if (!proper)
                {
                    source.RejectAsset(asset.Name, new ContentRejectionFromFailedLoad_ByAssetExtensionType());
                    this.TryLoadingAsset<T>(asset, mode);
                    return;
                }
                bool flag3 = true;
                IRejectionReason rejectionReason2 = null;
                if (source.ContentValidator != null)
                {
                    flag3 = source.ContentValidator.AssetIsValid<T>(content, asset.Name, out rejectionReason2);
                }
                if (flag3)
                {
                    this.SubmitLoadedContent<T>(asset, content, source);
                    int loadedAssets2 = this.LoadedAssets;
                    this.LoadedAssets = loadedAssets2 + 1;
                    return;
                }
                source.RejectAsset(asset.Name, rejectionReason2);
                this.TryLoadingAsset<T>(asset, mode);
            });
        }
References ReLogic.Content.AssetRepository._asyncLoader, ReLogic.Content.AssetRepository._loader, ReLogic.Content.AssetRepository.asset, ReLogic.Content.AssetRepository.content, ReLogic.Content.Sources.IContentSource.ContentValidator, ReLogic.Content.AssetRepository.FindSourceForAsset(), ReLogic.Content.AssetLoadException.FromAssetException(), ReLogic.Content.AssetRepository.LoadedAssets, ReLogic.Content.AssetRepository.mode, ReLogic.Content.Sources.IContentSource.RejectAsset(), ReLogic.Content.AssetRepository.source, ReLogic.Content.AssetRepository.SubmitLoadedContent< T >(), and ReLogic.Content.AssetRepository.TryLoadingAsset< T >().
Referenced by ReLogic.Content.AssetRepository.LoadAsset< T >(), and ReLogic.Content.AssetRepository.TryLoadingAsset< T >().