Terraria Decompiled: Terraria.IO.PlayerFileData.MoveToCloud
MoveToCloud()
override void Terraria.IO.PlayerFileData.MoveToCloud () inline
Definition at line 99 of file PlayerFileData.cs.
        {
            if (base.IsCloudSave || SocialAPI.Cloud == null)
            {
                return;
            }
            string playerPathFromName = Main.GetPlayerPathFromName(this.Name, true);
            if (FileUtilities.MoveToCloud(base.Path, playerPathFromName))
            {
                string fileName = base.GetFileName(false);
                string text = Main.PlayerPath + global::System.IO.Path.DirectorySeparatorChar.ToString() + fileName + global::System.IO.Path.DirectorySeparatorChar.ToString();
                string text2 = playerPathFromName.Substring(0, playerPathFromName.Length - 4);
                if (Directory.Exists(text))
                {
                    string[] files = Directory.GetFiles(text);
                    for (int i = 0; i < files.Length; i++)
                    {
                        string text3 = text2 + "/" + FileUtilities.GetFileName(files[i], true);
                        FileUtilities.MoveToCloud(files[i], text3);
                    }
                }
                Main.LocalFavoriteData.ClearEntry(this);
                this._isCloudSave = true;
                this._path = playerPathFromName;
                Main.CloudFavoritesData.SaveFavorite(this);
            }
        }
References Terraria.Social.SocialAPI.Cloud, Terraria.Main.CloudFavoritesData, System.IO.Directory.Exists(), Terraria.Utilities.FileUtilities.GetFileName(), System.IO.Directory.GetFiles(), Terraria.Main.GetPlayerPathFromName(), Terraria.Main.LocalFavoriteData, Terraria.Utilities.FileUtilities.MoveToCloud(), Terraria.IO.FileData.Name, and System.text.
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.CloudButtonClick().