Terraria Decompiled: ReLogic.Content.AssetRepository.EnsureTypeSpecificActionsExist< T >
EnsureTypeSpecificActionsExist< T >()
void ReLogic.Content.AssetRepository.EnsureTypeSpecificActionsExist< T > () inline private
Type Constraints
T : class
Definition at line 459 of file AssetRepository.cs.
                                                                 : class
        {
            this._typeSpecificReloadActions[typeof(Asset<T>)] = new Action<IAsset, AssetRequestMode>(this.ForceReloadAsset<T>);
            this._typeSpecificUpdateActions[typeof(Asset<T>)] = new Func<IAsset, IContentSource, string, Func<Stream>, bool>(this.UpdateAssetValue<T>);
        }
References ReLogic.Content.AssetRepository._typeSpecificReloadActions, ReLogic.Content.AssetRepository._typeSpecificUpdateActions, ReLogic.Content.AssetRepository.ForceReloadAsset< T >(), and ReLogic.Content.AssetRepository.UpdateAssetValue< T >().
Referenced by ReLogic.Content.AssetRepository.LoadAsset< T >().