Terraria Decompiled: ReLogic.Content.AssetRepository.LoadAsset< T >
LoadAsset< T >()
void ReLogic.Content.AssetRepository.LoadAsset< T > (Asset< T > asset, AssetRequestMode mode) inline private
Type Constraints
T : class
Definition at line 334 of file AssetRepository.cs.
                                                                                 : class
        {
            if (mode == AssetRequestMode.DoNotLoad)
            {
                return;
            }
            this.EnsureTypeSpecificActionsExist<T>();
            int totalAssets = this.TotalAssets;
            this.TotalAssets = totalAssets + 1;
            asset.SetToLoadingState();
            try
            {
                this.TryLoadingAsset<T>(asset, mode);
            }
            catch (Exception ex)
            {
                if (this.AssetLoadFailHandler != null)
                {
                    this.AssetLoadFailHandler(asset.Name, ex);
                }
                throw;
            }
        }
References ReLogic.Content.AssetRepository.asset, ReLogic.Content.AssetRepository.AssetLoadFailHandler, ReLogic.Content.AssetRepository.EnsureTypeSpecificActionsExist< T >(), ReLogic.Content.AssetRepository.mode, ReLogic.Content.AssetRepository.TotalAssets, and ReLogic.Content.AssetRepository.TryLoadingAsset< T >().
Referenced by ReLogic.Content.AssetRepository.ForceReloadAsset< T >(), and ReLogic.Content.AssetRepository.Request< T >().