Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.GrowTable
GrowTable()
void System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable (ConcurrentDictionary< TKey, TValue >::Tables tables) inline private
Definition at line 1114 of file ConcurrentDictionary.cs.
        {
            int num = 0;
            try
            {
                this.AcquireLocks(0, 1, ref num);
                if (tables == this._tables)
                {
                    long num2 = 0L;
                    for (int i = 0; i < tables._countPerLock.Length; i++)
                    {
                        num2 += (long)tables._countPerLock[i];
                    }
                    if (num2 < (long)(tables._buckets.Length / 4))
                    {
                        this._budget = 2 * this._budget;
                        if (this._budget < 0)
{
                            this._budget = int.MaxValue;
                        }
                    }
                    else
                    {
                        int num3 = 0;
                        bool flag = false;
                        object[] array;
                        checked
{
                            try
{
                                num3 = tables._buckets.Length * 2 + 1;
                                while (num3 % 3 == 0 || num3 % 5 == 0 || num3 % 7 == 0)
{
                                    num3 += 2;
                                }
                                if (num3 > 2146435071)
{
                                    flag = true;
                                }
                            }
                            catch (OverflowException)
{
                                flag = true;
                            }
                            if (flag)
{
                                num3 = 2146435071;
                                this._budget = int.MaxValue;
                            }
                            this.AcquireLocks(1, tables._locks.Length, ref num);
                            array = tables._locks;
                        }
                        if (this._growLockArray && tables._locks.Length < 1024)
{
                            array = new object[tables._locks.Length * 2];
                            Array.Copy(tables._locks, 0, array, 0, tables._locks.Length);
                            for (int j = tables._locks.Length; j < array.Length; j++)
{
                                array[j] = new object();
                            }
                        }
                        ConcurrentDictionary<TKey, TValue>.Node[] array2 = new ConcurrentDictionary<TKey, TValue>.Node[num3];
                        int[] array3 = new int[array.Length];
                        for (int k = 0; k < tables._buckets.Length; k++)
{
                            checked
{
                                ConcurrentDictionary<TKey, TValue>.Node next;
                                for (ConcurrentDictionary<TKey, TValue>.Node node = tables._buckets[k]; node != null; node = next)
{
                                    next = node._next;
                                    int num4;
                                    int num5;
                                    ConcurrentDictionary<TKey, TValue>.GetBucketAndLockNo(node._hashcode, out num4, out num5, array2.Length, array.Length);
                                    array2[num4] = new ConcurrentDictionary<TKey, TValue>.Node(node._key, node._value, node._hashcode, array2[num4]);
                                    array3[num5]++;
                                }
                            }
                        }
                        this._budget = Math.Max(1, array2.Length / array.Length);
                        this._tables = new ConcurrentDictionary<TKey, TValue>.Tables(array2, array, array3);
                    }
                }
            }
            finally
            {
                this.ReleaseLocks(0, num);
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._budget, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._growLockArray, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireLocks(), System.array, System.Array.Copy(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetBucketAndLockNo(), System.L, long, System.Math.Max(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAddInternal().