Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.ToArray
ToArray()
KeyValuePair< TKey, TValue >[] System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ToArray () inline
Definition at line 380 of file ConcurrentDictionary.cs.
        {
            int num = 0;
            checked
            {
                KeyValuePair<TKey, TValue>[] array;
                try
                {
                    this.AcquireAllLocks(ref num);
                    int num2 = 0;
                    for (int i = 0; i < this._tables._locks.Length; i++)
                    {
                        num2 += this._tables._countPerLock[i];
                    }
                    if (num2 == 0)
                    {
                        array = Array.Empty<KeyValuePair<TKey, TValue>>();
                    }
                    else
                    {
                        KeyValuePair<TKey, TValue>[] array2 = new KeyValuePair<TKey, TValue>[num2];
                        this.CopyToPairs(array2, 0);
                        array = array2;
                    }
                }
                finally
                {
                    this.ReleaseLocks(0, num);
                }
                return array;
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._countPerLock, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._locks, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks(), System.array, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyToPairs(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.OnSerializing().