Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.CopyTo
CopyTo() [2/2]
void ICollection< KeyValuePair< TKey, TValue > >. System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo (KeyValuePair< TKey, TValue >[] array, int index) inline private
Definition at line 346 of file ConcurrentDictionary.cs.
        {
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index", "The index argument is less than zero.");
            }
            int num = 0;
            try
            {
                this.AcquireAllLocks(ref num);
                int num2 = 0;
                int num3 = 0;
                while (num3 < this._tables._locks.Length && num2 >= 0)
                {
                    num2 += this._tables._countPerLock[num3];
                    num3++;
                }
                if (array.Length - num2 < index || num2 < 0)
                {
                    throw new ArgumentException("The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.");
                }
                this.CopyToPairs(array, index);
            }
            finally
            {
                this.ReleaseLocks(0, num);
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._countPerLock, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks(), System.array, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyToPairs(), System.index, and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks().