Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.ContainsKey
ContainsKey()
bool System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ContainsKey (TKey key) inline
Implements System.Collections.Generic.IReadOnlyDictionary< TKey, TValue >.
Definition at line 159 of file ConcurrentDictionary.cs.
        {
            if (key == null)
            {
                ConcurrentDictionary<TKey, TValue>.ThrowKeyNullException();
            }
            TValue tvalue;
            return this.TryGetValue(key, out tvalue);
        }
References System.key, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ThrowKeyNullException(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValue().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Contains().