Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.GetValues
GetValues()
ReadOnlyCollection< TValue > System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetValues () inline private
Definition at line 1299 of file ConcurrentDictionary.cs.
        {
            int num = 0;
            ReadOnlyCollection<TValue> readOnlyCollection;
            try
            {
                this.AcquireAllLocks(ref num);
                int countInternal = this.GetCountInternal();
                if (countInternal < 0)
                {
                    throw new OutOfMemoryException();
                }
                List<TValue> list = new List<TValue>(countInternal);
                for (int i = 0; i < this._tables._buckets.Length; i++)
                {
                    for (ConcurrentDictionary<TKey, TValue>.Node node = this._tables._buckets[i]; node != null; node = node._next)
                    {
                        list.Add(node._value);
                    }
                }
                readOnlyCollection = new ReadOnlyCollection<TValue>(list);
            }
            finally
            {
                this.ReleaseLocks(0, num);
            }
            return readOnlyCollection;
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._buckets, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetCountInternal(), System.list, and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks().