Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.TryGetValueInternal
TryGetValueInternal()
bool System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValueInternal (TKey key, int hashcode, out TValue value) inline private
Definition at line 243 of file ConcurrentDictionary.cs.
        {
            ConcurrentDictionary<TKey, TValue>.Tables tables = this._tables;
            int bucket = ConcurrentDictionary<TKey, TValue>.GetBucket(hashcode, tables._buckets.Length);
            for (ConcurrentDictionary<TKey, TValue>.Node node = Volatile.Read<ConcurrentDictionary<TKey, TValue>.Node>(ref tables._buckets[bucket]); node != null; node = node._next)
            {
                if (hashcode == node._hashcode && this._comparer.Equals(node._key, key))
                {
                    value = node._value;
                    return true;
                }
            }
            value = default(TValue);
            return false;
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetBucket(), System.key, System.Threading.Volatile.Read(), and System.value.
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate< TArg >(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd< TArg >(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValue().