Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.InitializeFromCollection
InitializeFromCollection()
void System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.InitializeFromCollection (IEnumerable< KeyValuePair< TKey, TValue > > collection) inline private
Definition at line 93 of file ConcurrentDictionary.cs.
        {
            foreach (KeyValuePair<TKey, TValue> keyValuePair in collection)
            {
                if (keyValuePair.Key == null)
                {
                    ConcurrentDictionary<TKey, TValue>.ThrowKeyNullException();
                }
                TValue tvalue;
                if (!this.TryAddInternal(keyValuePair.Key, this._comparer.GetHashCode(keyValuePair.Key), keyValuePair.Value, false, false, out tvalue))
                {
                    throw new ArgumentException("The source argument contains duplicate keys.");
                }
            }
            if (this._budget == 0)
            {
                this._budget = this._tables._buckets.Length / this._tables._locks.Length;
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._budget, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._locks, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.collection, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ThrowKeyNullException(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAddInternal(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ConcurrentDictionary(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ConcurrentDictionary(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.OnDeserialized().