Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.TryUpdateInternal
TryUpdateInternal()
bool System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryUpdateInternal (TKey key, int hashcode, TValue newValue, TValue comparisonValue) inline private
Definition at line 270 of file ConcurrentDictionary.cs.
        {
            IEqualityComparer<TValue> @default = EqualityComparer<TValue>.Default;
            bool flag2;
            for (;;)
            {
                ConcurrentDictionary<TKey, TValue>.Tables tables = this._tables;
                int num;
                int num2;
                ConcurrentDictionary<TKey, TValue>.GetBucketAndLockNo(hashcode, out num, out num2, tables._buckets.Length, tables._locks.Length);
                object obj = tables._locks[num2];
                lock (obj)
                {
                    if (tables != this._tables)
                    {
                        continue;
                    }
                    ConcurrentDictionary<TKey, TValue>.Node node = null;
                    ConcurrentDictionary<TKey, TValue>.Node node2 = tables._buckets[num];
                    while (node2 != null)
                    {
                        if (hashcode == node2._hashcode && this._comparer.Equals(node2._key, key))
{
                            if (@default.Equals(node2._value, comparisonValue))
{
                                if (ConcurrentDictionary<TKey, TValue>.s_isValueWriteAtomic)
{
                                    node2._value = newValue;
                                }
                                else
{
                                    ConcurrentDictionary<TKey, TValue>.Node node3 = new ConcurrentDictionary<TKey, TValue>.Node(node2._key, newValue, hashcode, node2._next);
                                    if (node == null)
{
                                        Volatile.Write<ConcurrentDictionary<TKey, TValue>.Node>(ref tables._buckets[num], node3);
                                    }
                                    else
{
                                        node._next = node3;
                                    }
                                }
                                return true;
                            }
                            return false;
                        }
                        else
{
                            node = node2;
                            node2 = node2._next;
                        }
                    }
                    flag2 = false;
                }
                break;
            }
            return flag2;
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Node._next, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Generic.EqualityComparer< T >.Default, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetBucketAndLockNo(), System.key, System.obj, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.s_isValueWriteAtomic, and System.Threading.Volatile.Write().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate< TArg >(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryUpdate().