Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.CopyTo
CopyTo() [1/2]
void ICollection. System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo (Array array, int index) inline private
Implements System.Collections.ICollection.
Definition at line 1038 of file ConcurrentDictionary.cs.
        {
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index", "The index argument is less than zero.");
            }
            int num = 0;
            try
            {
                this.AcquireAllLocks(ref num);
                ConcurrentDictionary<TKey, TValue>.Tables tables = this._tables;
                int num2 = 0;
                int num3 = 0;
                while (num3 < tables._locks.Length && num2 >= 0)
                {
                    num2 += tables._countPerLock[num3];
                    num3++;
                }
                if (array.Length - num2 < index || num2 < 0)
                {
                    throw new ArgumentException("The index is equal to or greater than the length of the array, or the number of elements in the dictionary is greater than the available space from index to the end of the destination array.");
                }
                KeyValuePair<TKey, TValue>[] array2 = array as KeyValuePair<TKey, TValue>[];
                if (array2 != null)
                {
                    this.CopyToPairs(array2, index);
                }
                else
                {
                    DictionaryEntry[] array3 = array as DictionaryEntry[];
                    if (array3 != null)
                    {
                        this.CopyToEntries(array3, index);
                    }
                    else
                    {
                        object[] array4 = array as object[];
                        if (array4 == null)
{
                            throw new ArgumentException("The array is multidimensional, or the type parameter for the set cannot be cast automatically to the type of the destination array.", "array");
                        }
                        this.CopyToObjects(array4, index);
                    }
                }
            }
            finally
            {
                this.ReleaseLocks(0, num);
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks(), System.array, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyToEntries(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyToObjects(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyToPairs(), System.index, and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks().