Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.TryAddInternal
TryAddInternal()
bool System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAddInternal (TKey key, int hashcode, TValue value, bool updateIfExists, bool acquireLock, out TValue resultingValue) inline private
Definition at line 474 of file ConcurrentDictionary.cs.
        {
            checked
            {
                ConcurrentDictionary<TKey, TValue>.Tables tables;
                bool flag;
                for (;;)
                {
                    tables = this._tables;
                    int num;
                    int num2;
                    ConcurrentDictionary<TKey, TValue>.GetBucketAndLockNo(hashcode, out num, out num2, tables._buckets.Length, tables._locks.Length);
                    flag = false;
                    bool flag2 = false;
                    try
                    {
                        if (acquireLock)
{
                            Monitor.Enter(tables._locks[num2], ref flag2);
                        }
                        if (tables != this._tables)
{
                            continue;
                        }
                        ConcurrentDictionary<TKey, TValue>.Node node = null;
                        for (ConcurrentDictionary<TKey, TValue>.Node node2 = tables._buckets[num]; node2 != null; node2 = node2._next)
{
                            if (hashcode == node2._hashcode && this._comparer.Equals(node2._key, key))
{
                                if (updateIfExists)
{
                                    if (ConcurrentDictionary<TKey, TValue>.s_isValueWriteAtomic)
{
                                        node2._value = value;
                                    }
                                    else
{
                                        ConcurrentDictionary<TKey, TValue>.Node node3 = new ConcurrentDictionary<TKey, TValue>.Node(node2._key, value, hashcode, node2._next);
                                        if (node == null)
{
                                            Volatile.Write<ConcurrentDictionary<TKey, TValue>.Node>(ref tables._buckets[num], node3);
                                        }
                                        else
{
                                            node._next = node3;
                                        }
                                    }
                                    resultingValue = value;
                                }
                                else
{
                                    resultingValue = node2._value;
                                }
                                return false;
                            }
                            node = node2;
                        }
                        Volatile.Write<ConcurrentDictionary<TKey, TValue>.Node>(ref tables._buckets[num], new ConcurrentDictionary<TKey, TValue>.Node(key, value, hashcode, tables._buckets[num]));
                        tables._countPerLock[num2]++;
                        if (tables._countPerLock[num2] > this._budget)
{
                            flag = true;
                        }
                    }
                    finally
                    {
                        if (flag2)
{
                            Monitor.Exit(tables._locks[num2]);
                        }
                    }
                    break;
                }
                if (flag)
                {
                    this.GrowTable(tables);
                }
                resultingValue = value;
                return true;
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Node._value, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetBucketAndLockNo(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable(), System.key, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.s_isValueWriteAtomic, System.value, and System.Threading.Volatile.Write().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate< TArg >(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetOrAdd< TArg >(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.InitializeFromCollection(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAdd().