Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.ReleaseLocks
ReleaseLocks()
void System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks (int fromInclusive, int toExclusive) inline private
Definition at line 1260 of file ConcurrentDictionary.cs.
        {
            for (int i = fromInclusive; i < toExclusive; i++)
            {
                Monitor.Exit(this._tables._locks[i]);
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._locks, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, and System.Threading.Monitor.Exit().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Clear(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetKeys(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetValues(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ToArray().