Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.TryRemoveInternal
TryRemoveInternal()
bool System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryRemoveInternal (TKey key, out TValue value, bool matchValue, TValue oldValue) inline private
Definition at line 180 of file ConcurrentDictionary.cs.
        {
            int hashCode = this._comparer.GetHashCode(key);
            for (;;)
            {
                ConcurrentDictionary<TKey, TValue>.Tables tables = this._tables;
                int num;
                int num2;
                ConcurrentDictionary<TKey, TValue>.GetBucketAndLockNo(hashCode, out num, out num2, tables._buckets.Length, tables._locks.Length);
                object obj = tables._locks[num2];
                lock (obj)
                {
                    if (tables != this._tables)
                    {
                        continue;
                    }
                    ConcurrentDictionary<TKey, TValue>.Node node = null;
                    ConcurrentDictionary<TKey, TValue>.Node node2 = tables._buckets[num];
                    while (node2 != null)
                    {
                        if (hashCode == node2._hashcode && this._comparer.Equals(node2._key, key))
{
                            if (matchValue && !EqualityComparer<TValue>.Default.Equals(oldValue, node2._value))
{
                                value = default(TValue);
                                return false;
                            }
                            if (node == null)
{
                                Volatile.Write<ConcurrentDictionary<TKey, TValue>.Node>(ref tables._buckets[num], node2._next);
                            }
                            else
{
                                node._next = node2._next;
                            }
                            value = node2._value;
                            tables._countPerLock[num2]--;
                            return true;
                        }
                        else
{
                            node = node2;
                            node2 = node2._next;
                        }
                    }
                }
                break;
            }
            value = default(TValue);
            return false;
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._comparer, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Node._next, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Node._value, System.Default, System.Collections.Generic.EqualityComparer< T >.Equals(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetBucketAndLockNo(), System.Collections.IEqualityComparer.GetHashCode(), System.key, System.obj, System.value, and System.Threading.Volatile.Write().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Remove(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryRemove().