Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.Clear
Clear()
void System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Clear () inline
Implements System.Collections.IDictionary.
Definition at line 329 of file ConcurrentDictionary.cs.
        {
            int num = 0;
            try
            {
                this.AcquireAllLocks(ref num);
                ConcurrentDictionary<TKey, TValue>.Tables tables = new ConcurrentDictionary<TKey, TValue>.Tables(new ConcurrentDictionary<TKey, TValue>.Node[31], this._tables._locks, new int[this._tables._countPerLock.Length]);
                this._tables = tables;
                this._budget = Math.Max(1, tables._buckets.Length / tables._locks.Length);
            }
            finally
            {
                this.ReleaseLocks(0, num);
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._locks, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks(), System.Math.Max(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ReleaseLocks().