Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.AcquireAllLocks
AcquireAllLocks()
void System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks (ref int locksAcquired) inline private
Definition at line 1228 of file ConcurrentDictionary.cs.
        {
            if (CDSCollectionETWBCLProvider.Log.IsEnabled())
            {
                CDSCollectionETWBCLProvider.Log.ConcurrentDictionary_AcquiringAllLocks(this._tables._buckets.Length);
            }
            this.AcquireLocks(0, 1, ref locksAcquired);
            this.AcquireLocks(1, this._tables._locks.Length, ref locksAcquired);
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._buckets, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._locks, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireLocks(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentDictionary_AcquiringAllLocks(), System.Diagnostics.Tracing.EventSource.IsEnabled(), and System.Collections.Concurrent.CDSCollectionETWBCLProvider.Log.
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Clear(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.CopyTo(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetKeys(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GetValues(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ToArray().