Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.AddOrUpdate
AddOrUpdate() [1/2]
TValue System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AddOrUpdate (TKey key, Func< TKey, TValue > addValueFactory, Func< TKey, TValue, TValue > updateValueFactory) inline
Definition at line 719 of file ConcurrentDictionary.cs.
        {
            if (key == null)
            {
                ConcurrentDictionary<TKey, TValue>.ThrowKeyNullException();
            }
            if (addValueFactory == null)
            {
                throw new ArgumentNullException("addValueFactory");
            }
            if (updateValueFactory == null)
            {
                throw new ArgumentNullException("updateValueFactory");
            }
            int hashCode = this._comparer.GetHashCode(key);
            TValue tvalue2;
            for (;;)
            {
                TValue tvalue;
                TValue tvalue3;
                if (this.TryGetValueInternal(key, hashCode, out tvalue))
                {
                    tvalue2 = updateValueFactory(key, tvalue);
                    if (this.TryUpdateInternal(key, hashCode, tvalue2, tvalue))
                    {
                        break;
                    }
                }
                else if (this.TryAddInternal(key, hashCode, addValueFactory(key), false, true, out tvalue3))
                {
                    return tvalue3;
                }
            }
            return tvalue2;
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._comparer, System.Collections.IEqualityComparer.GetHashCode(), System.key, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.ThrowKeyNullException(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryAddInternal(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryGetValueInternal(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryUpdateInternal().