Terraria Decompiled: System.Collections.Concurrent.ConcurrentDictionary.AcquireLocks
AcquireLocks()
void System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireLocks (int fromInclusive, int toExclusive, ref int locksAcquired) inline private
Definition at line 1239 of file ConcurrentDictionary.cs.
        {
            object[] locks = this._tables._locks;
            for (int i = fromInclusive; i < toExclusive; i++)
            {
                bool flag = false;
                try
                {
                    Monitor.Enter(locks[i], ref flag);
                }
                finally
                {
                    if (flag)
                    {
                        locksAcquired++;
                    }
                }
            }
        }
References System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.Tables._locks, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >._tables, and System.Threading.Monitor.Enter().
Referenced by System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.AcquireAllLocks(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.GrowTable().