Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_GrowGrass
LateDualDungeonFeatures_GrowGrass() [1/2]
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_GrowGrass (DungeonRoom room) inline private
Definition at line 152 of file DungeonGlobalLateDualDungeonFeatures.cs.
        {
            if (room == null || room.settings.StyleData.BrickGrassTileType == null)
            {
                return;
            }
            this.LateDualDungeonFeatures_GrowGrass(room, room.settings.StyleData.BrickTileType, room.settings.StyleData.BrickGrassTileType.Value);
        }
References Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickGrassTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_GrowGrass(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, and Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_GrowGrass().