Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures
LateDualDungeonFeatures()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures (DungeonData data) inline
Definition at line 28 of file DungeonGlobalLateDualDungeonFeatures.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            for (int i = 0; i < data.genVars.dungeonGenerationStyles.Count; i++)
            {
                DungeonGenerationStyleData dungeonGenerationStyleData = data.genVars.dungeonGenerationStyles[i];
                byte style = dungeonGenerationStyleData.Style;
                DungeonBounds dungeonBounds = data.outerProgressionBounds[i];
                if ((style == 8 || style == 7) && dungeonGenerationStyleData.BrickGrassTileType != null)
                {
                    ushort value = dungeonGenerationStyleData.BrickGrassTileType.Value;
                    for (int j = dungeonBounds.Left; j <= dungeonBounds.Right; j++)
                    {
                        for (int k = dungeonBounds.Top; k <= dungeonBounds.Bottom; k++)
{
                            Tile tile = Main.tile[j, k];
                            if (tile.active() && tile.type == 59 && WorldGen.TileIsExposedToAir(j, k))
{
                                tile.type = value;
                            }
                        }
                    }
                }
            }
            List<BiomeDungeonRoom> list = new List<BiomeDungeonRoom>();
            for (int l = 0; l < data.dungeonRooms.Count; l++)
            {
                DungeonRoom dungeonRoom = data.dungeonRooms[l];
                if (dungeonRoom is BiomeDungeonRoom)
                {
                    list.Add((BiomeDungeonRoom)dungeonRoom);
                }
            }
            while (list.Count > 0)
            {
                BiomeDungeonRoom biomeDungeonRoom = list[0];
                this.LateDualDungeonFeatures_CleanOutEntrancesOfLiquids(biomeDungeonRoom);
                if (biomeDungeonRoom.settings.StyleData.Style == 8)
                {
                    this.LateDualDungeonFeatures_GrowGrass(biomeDungeonRoom);
                }
                list.Remove(biomeDungeonRoom);
            }
            for (int m = 0; m < data.dungeonRooms.Count; m++)
            {
                data.dungeonRooms[m].GenerateLateDungeonFeaturesInRoom(data);
            }
        }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickGrassTileType, System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_CleanOutEntrancesOfLiquids(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_GrowGrass(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, System.list, Terraria.GameContent.Generation.Dungeon.DungeonData.outerProgressionBounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.Main.tile, Terraria.WorldGen.TileIsExposedToAir(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, and System.value.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.GenerateFeature().