Terraria Decompiled: System.MemoryExtensions.IndexOf
IndexOf()
static int System.MemoryExtensions.IndexOf (this ReadOnlySpan< char > span, ReadOnlySpan< char > value, StringComparison comparisonType) inline static
Definition at line 96 of file MemoryExtensions.cs.
        {
            string.CheckStringComparison(comparisonType);
            if (value.Length == 0)
            {
                return 0;
            }
            if (span.Length == 0)
            {
                return -1;
            }
            switch (comparisonType)
            {
            case StringComparison.CurrentCulture:
                return SpanHelpers.IndexOfCultureHelper(span, value, CultureInfo.CurrentCulture.CompareInfo);
            case StringComparison.CurrentCultureIgnoreCase:
                return SpanHelpers.IndexOfCultureIgnoreCaseHelper(span, value, CultureInfo.CurrentCulture.CompareInfo);
            case StringComparison.InvariantCulture:
                return SpanHelpers.IndexOfCultureHelper(span, value, CompareInfo.Invariant);
            case StringComparison.InvariantCultureIgnoreCase:
                return SpanHelpers.IndexOfCultureIgnoreCaseHelper(span, value, CompareInfo.Invariant);
            case StringComparison.Ordinal:
                return SpanHelpers.IndexOfOrdinalHelper(span, value, false);
            case StringComparison.OrdinalIgnoreCase:
                return SpanHelpers.IndexOfOrdinalHelper(span, value, true);
            default:
                return -1;
            }
        }
References System.Globalization.CultureInfo.CompareInfo, System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.SpanHelpers.IndexOfCultureHelper(), System.SpanHelpers.IndexOfCultureIgnoreCaseHelper(), System.SpanHelpers.IndexOfOrdinalHelper(), System.Globalization.CompareInfo.Invariant, System.ReadOnlySpan< T >.Length, and System.value.