Terraria Decompiled: System.MemoryExtensions.StartsWith
StartsWith()
static bool System.MemoryExtensions.StartsWith (this ReadOnlySpan< char > span, ReadOnlySpan< char > value, StringComparison comparisonType) inline static
Definition at line 234 of file MemoryExtensions.cs.
        {
            if (value.Length == 0)
            {
                string.CheckStringComparison(comparisonType);
                return true;
            }
            switch (comparisonType)
            {
            case StringComparison.CurrentCulture:
                return SpanHelpers.StartsWithCultureHelper(span, value, CultureInfo.CurrentCulture.CompareInfo);
            case StringComparison.CurrentCultureIgnoreCase:
                return SpanHelpers.StartsWithCultureIgnoreCaseHelper(span, value, CultureInfo.CurrentCulture.CompareInfo);
            case StringComparison.InvariantCulture:
                return SpanHelpers.StartsWithCultureHelper(span, value, CompareInfo.Invariant);
            case StringComparison.InvariantCultureIgnoreCase:
                return SpanHelpers.StartsWithCultureIgnoreCaseHelper(span, value, CompareInfo.Invariant);
            case StringComparison.Ordinal:
                return span.StartsWith(value);
            case StringComparison.OrdinalIgnoreCase:
                return SpanHelpers.StartsWithOrdinalIgnoreCaseHelper(span, value);
            default:
                throw new ArgumentException("The string comparison type passed in is currently not supported.", "comparisonType");
            }
        }
References System.Globalization.CultureInfo.CompareInfo, System.comparisonType, System.Globalization.CultureInfo.CurrentCulture, System.Globalization.CompareInfo.Invariant, System.SpanHelpers.StartsWithCultureHelper(), System.SpanHelpers.StartsWithCultureIgnoreCaseHelper(), System.SpanHelpers.StartsWithOrdinalIgnoreCaseHelper(), and System.value.