Terraria Decompiled: System.MemoryExtensions.AsMemory
AsMemory() [5/5]
static ReadOnlyMemory< char > System.MemoryExtensions.AsMemory (this string text, Range range) inline static
Definition at line 446 of file MemoryExtensions.cs.
        {
            if (text == null)
            {
                Index start = range.Start;
                Index end = range.End;
                if (!start.Equals(Index.Start) || !end.Equals(Index.Start))
                {
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.text);
                }
                return default(ReadOnlyMemory<char>);
            }
            ValueTuple<int, int> offsetAndLength = range.GetOffsetAndLength(text.Length);
            int item = offsetAndLength.Item1;
            int item2 = offsetAndLength.Item2;
            return new ReadOnlyMemory<char>(text, item, item2);
        }
References System.Range.End, System.Index.Equals(), System.Range.GetOffsetAndLength(), System.item, System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, System.start, System.Index.Start, System.Range.Start, System.text, and System.ThrowHelper.ThrowArgumentNullException().