Terraria Decompiled: System.MemoryExtensions.AsMemory< T >
AsMemory< T >() [8/8]
static Memory< T > System.MemoryExtensions.AsMemory< T > (this T[] array, Range range) inline static
Definition at line 1047 of file MemoryExtensions.cs.
        {
            if (array == null)
            {
                Index start = range.Start;
                Index end = range.End;
                if (!start.Equals(Index.Start) || !end.Equals(Index.Start))
                {
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
                }
                return default(Memory<T>);
            }
            ValueTuple<int, int> offsetAndLength = range.GetOffsetAndLength(array.Length);
            int item = offsetAndLength.Item1;
            int item2 = offsetAndLength.Item2;
            return new Memory<T>(array, item, item2);
        }
References System.array, System.Range.End, System.Index.Equals(), System.Range.GetOffsetAndLength(), System.item, System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, System.start, System.Index.Start, System.Range.Start, and System.ThrowHelper.ThrowArgumentNullException().