Terraria Decompiled: System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >
GetSubArray< T >()
static T[] System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T > (T[] array, Range range) inline static
Definition at line 168 of file RuntimeHelpers.cs.
        {
            Type elementType = array.GetType().GetElementType();
            Span<T> span = array.AsSpan(range);
            if (elementType.IsValueType)
            {
                return span.ToArray();
            }
            T[] array2 = (T[])Array.CreateInstance(elementType, span.Length);
            span.CopyTo(array2);
            return array2;
        }
References System.array, System.Span< T >.CopyTo(), System.Array.CreateInstance(), System.Type.GetElementType(), System.Type.GetType(), System.Type.IsValueType, System.Span< T >.Length, and System.Span< T >.ToArray().