Terraria Decompiled: Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest
HandleUseRequest()
override void Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest (GraphicsDevice device, SpriteBatch spriteBatch) inline protected
Definition at line 14 of file PlayerRainbowWingsTextureContent.cs.
        {
            Asset<Texture2D> asset = TextureAssets.Extra[171];
            base.PrepareARenderTarget_AndListenToEvents(ref this._target, device, asset.Width(), asset.Height(), RenderTargetUsage.PreserveContents);
            device.SetRenderTarget(this._target);
            device.Clear(Color.Transparent);
            DrawData drawData = new DrawData(asset.Value, Vector2.Zero, Color.White);
            spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
            GameShaders.Misc["HallowBoss"].Apply(new DrawData?(drawData));
            drawData.Draw(spriteBatch);
            spriteBatch.End();
            device.SetRenderTarget(null);
            this._wasPrepared = true;
        }
References Terraria.GameContent.ARenderTargetContentByRequest._target, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Terraria.DataStructures.DrawData.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.TextureAssets.Extra, Terraria.Graphics.Shaders.GameShaders.Misc, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Microsoft.Xna.Framework.Color.Transparent, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.