Terraria Decompiled: System.Guid.TryParseGuidWithNoStyle
TryParseGuidWithNoStyle()
static unsafe bool System.Guid.TryParseGuidWithNoStyle (ReadOnlySpan< char > guidString, ref Guid::GuidResult result) inline static private
Definition at line 590 of file Guid.cs.
        {
            int num = 0;
            int num2 = 0;
            if (guidString.Length != 32)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).");
                return false;
            }
            for (int i = 0; i < guidString.Length; i++)
            {
                char c = (char)(*guidString[i]);
                if (c < '0' || c > '9')
                {
                    char c2 = char.ToUpperInvariant(c);
                    if (c2 < 'A' || c2 > 'F')
                    {
                        result.SetFailure(Guid.ParseFailureKind.Format, "Guid string should only contain hexadecimal characters.");
                        return false;
                    }
                }
            }
            if (!Guid.StringToInt(guidString.Slice(num, 8), -1, 4096, out result._parsedGuid._a, ref result))
            {
                return false;
            }
            num += 8;
            if (!Guid.StringToShort(guidString.Slice(num, 4), -1, 4096, out result._parsedGuid._b, ref result))
            {
                return false;
            }
            num += 4;
            if (!Guid.StringToShort(guidString.Slice(num, 4), -1, 4096, out result._parsedGuid._c, ref result))
            {
                return false;
            }
            num += 4;
            int num3;
            if (!Guid.StringToInt(guidString.Slice(num, 4), -1, 4096, out num3, ref result))
            {
                return false;
            }
            num += 4;
            num2 = num;
            long num4;
            if (!Guid.StringToLong(guidString, ref num2, 8192, out num4, ref result))
            {
                return false;
            }
            if (num2 - num != 12)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).");
                return false;
            }
            result._parsedGuid._d = (byte)(num3 >> 8);
            result._parsedGuid._e = (byte)num3;
            num3 = (int)(num4 >> 32);
            result._parsedGuid._f = (byte)(num3 >> 8);
            result._parsedGuid._g = (byte)num3;
            num3 = (int)num4;
            result._parsedGuid._h = (byte)(num3 >> 24);
            result._parsedGuid._i = (byte)(num3 >> 16);
            result._parsedGuid._j = (byte)(num3 >> 8);
            result._parsedGuid._k = (byte)num3;
            return true;
        }
References int, System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), System.Guid.StringToInt(), System.Guid.StringToLong(), and System.Guid.StringToShort().
Referenced by System.Guid.TryParseGuid().