Terraria Decompiled: System.Guid.TryParseExact
TryParseExact() [2/2]
static bool System.Guid.TryParseExact (string input, string format, out Guid result) inline static
Definition at line 281 of file Guid.cs.
        {
            if (input == null)
            {
                result = default(Guid);
                return false;
            }
            return Guid.TryParseExact(input, format, out result);
        }
References System.format, System.input, and System.Guid.TryParseExact().
Referenced by Newtonsoft.Json.Utilities.ConvertUtils.TryConvertGuid(), and System.Guid.TryParseExact().