Terraria Decompiled: System.Guid.NewGuid
NewGuid()
static unsafe Guid System.Guid.NewGuid () inline static
Definition at line 14 of file Guid.cs.
        {
            Guid guid;
            Interop.GetRandomBytes((byte*)(&guid), sizeof(Guid));
            guid._c = (short)(((int)guid._c & -61441) | 16384);
            guid._d = (byte)(((int)guid._d & -193) | 128);
            return guid;
        }
References System.Guid._c.
Referenced by Terraria.Main.ClientInitialize(), Terraria.IO.WorldFileData.CopyToLocal(), Terraria.IO.WorldFile.CreateMetadata(), Terraria.Utilities.FastRandom.CreateWithRandomSeed(), System.IO.PathInternal.GetIsCaseSensitive(), System.AppDomain.GetProcessGuid(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Main.Main(), and System.Runtime.Remoting.RemotingServices.NewUri().