Terraria Decompiled: System.Guid.Guid
Guid() [6/7]
System.Guid.Guid (string g) inline
Definition at line 111 of file Guid.cs.
        {
            if (g == null)
            {
                throw new ArgumentNullException("g");
            }
            Guid.GuidResult guidResult = default(Guid.GuidResult);
            guidResult.Init(Guid.GuidParseThrowStyle.All);
            if (Guid.TryParseGuid(g, Guid.GuidStyles.Any, ref guidResult))
            {
                this = guidResult._parsedGuid;
                return;
            }
            throw guidResult.GetGuidParseException();
        }
References System.Guid.GuidResult._parsedGuid, System.Guid.GuidResult.GetGuidParseException(), System.Guid.GuidResult.Init(), and System.Guid.TryParseGuid().