Terraria Decompiled: System.Guid.TryParseGuidWithDashes
TryParseGuidWithDashes()
static unsafe bool System.Guid.TryParseGuidWithDashes (ReadOnlySpan< char > guidString, ref Guid::GuidResult result) inline static private
Definition at line 658 of file Guid.cs.
        {
            int num = 0;
            int num2 = 0;
            if (*guidString[0] == 123)
            {
                if (guidString.Length != 38 || *guidString[37] != 125)
                {
                    result.SetFailure(Guid.ParseFailureKind.Format, "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).");
                    return false;
                }
                num = 1;
            }
            else if (*guidString[0] == 40)
            {
                if (guidString.Length != 38 || *guidString[37] != 41)
                {
                    result.SetFailure(Guid.ParseFailureKind.Format, "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).");
                    return false;
                }
                num = 1;
            }
            else if (guidString.Length != 36)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).");
                return false;
            }
            if (*guidString[8 + num] != 45 || *guidString[13 + num] != 45 || *guidString[18 + num] != 45 || *guidString[23 + num] != 45)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Dashes are in the wrong position for GUID parsing.");
                return false;
            }
            num2 = num;
            int num3;
            if (!Guid.StringToInt(guidString, ref num2, 8, 8192, out num3, ref result))
            {
                return false;
            }
            result._parsedGuid._a = num3;
            num2++;
            if (!Guid.StringToInt(guidString, ref num2, 4, 8192, out num3, ref result))
            {
                return false;
            }
            result._parsedGuid._b = (short)num3;
            num2++;
            if (!Guid.StringToInt(guidString, ref num2, 4, 8192, out num3, ref result))
            {
                return false;
            }
            result._parsedGuid._c = (short)num3;
            num2++;
            if (!Guid.StringToInt(guidString, ref num2, 4, 8192, out num3, ref result))
            {
                return false;
            }
            num2++;
            num = num2;
            long num4;
            if (!Guid.StringToLong(guidString, ref num2, 8192, out num4, ref result))
            {
                return false;
            }
            if (num2 - num != 12)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Guid should contain 32 digits with 4 dashes (xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx).");
                return false;
            }
            result._parsedGuid._d = (byte)(num3 >> 8);
            result._parsedGuid._e = (byte)num3;
            num3 = (int)(num4 >> 32);
            result._parsedGuid._f = (byte)(num3 >> 8);
            result._parsedGuid._g = (byte)num3;
            num3 = (int)num4;
            result._parsedGuid._h = (byte)(num3 >> 24);
            result._parsedGuid._i = (byte)(num3 >> 16);
            result._parsedGuid._j = (byte)(num3 >> 8);
            result._parsedGuid._k = (byte)num3;
            return true;
        }
References int, System.ReadOnlySpan< T >.Length, System.Guid.StringToInt(), and System.Guid.StringToLong().
Referenced by System.Guid.TryParseGuid().