Terraria Decompiled: System.Guid.ToByteArray
ToByteArray()
byte[] System.Guid.ToByteArray () inline
Definition at line 895 of file Guid.cs.
        {
            byte[] array = new byte[16];
            this.WriteByteHelper(array);
            return array;
        }
References System.array, and System.Guid.WriteByteHelper().
Referenced by Newtonsoft.Json.JsonTextReader.ParseReadString(), Newtonsoft.Json.JsonReader.ReadAsBytes(), and System.Security.AccessControl.ObjectAce.WriteGuid().