Terraria Decompiled: System.Guid.TryFormat
TryFormat() [2/2]
unsafe bool System.Guid.TryFormat (Span< char > destination, out int charsWritten, ReadOnlySpan< char > format = default(ReadOnlySpan<char>)) inline
Definition at line 1210 of file Guid.cs.
        {
            if (format.Length == 0)
            {
                format = "D";
            }
            if (format.Length != 1)
            {
                throw new FormatException("Format String can be only 'D', 'd', 'N', 'n', 'P', 'p', 'B', 'b', 'X' or 'x'.");
            }
            bool flag = true;
            bool flag2 = false;
            int num = 0;
            char c = (char)(*format[0]);
            if (c <= 'X')
            {
                if (c <= 'D')
                {
                    if (c == 'B')
                    {
                        goto IL_009D;
                    }
                    if (c != 'D')
                    {
                        goto IL_00C2;
                    }
                }
                else
                {
                    if (c == 'N')
                    {
                        goto IL_0096;
                    }
                    if (c == 'P')
                    {
                        goto IL_00A8;
                    }
                    if (c != 'X')
                    {
                        goto IL_00C2;
                    }
                    goto IL_00B3;
                }
            }
            else if (c <= 'd')
            {
                if (c == 'b')
                {
                    goto IL_009D;
                }
                if (c != 'd')
                {
                    goto IL_00C2;
                }
            }
            else
            {
                if (c == 'n')
                {
                    goto IL_0096;
                }
                if (c == 'p')
                {
                    goto IL_00A8;
                }
                if (c != 'x')
                {
                    goto IL_00C2;
                }
                goto IL_00B3;
            }
            int num2 = 36;
            goto IL_00CD;
            IL_0096:
            flag = false;
            num2 = 32;
            goto IL_00CD;
            IL_009D:
            num = 8192123;
            num2 = 38;
            goto IL_00CD;
            IL_00A8:
            num = 2687016;
            num2 = 38;
            goto IL_00CD;
            IL_00B3:
            num = 8192123;
            flag = false;
            flag2 = true;
            num2 = 68;
            goto IL_00CD;
            IL_00C2:
            throw new FormatException("Format String can be only 'D', 'd', 'N', 'n', 'P', 'p', 'B', 'b', 'X' or 'x'.");
            IL_00CD:
            if (destination.Length < num2)
            {
                charsWritten = 0;
                return false;
            }
            fixed (char* reference = MemoryMarshal.GetReference<char>(destination))
            {
                char* ptr = reference;
                if (num != 0)
                {
                    *(ptr++) = (char)num;
                }
                if (flag2)
                {
                    *(ptr++) = '0';
                    *(ptr++) = 'x';
                    ptr += Guid.HexsToChars(ptr, this._a >> 24, this._a >> 16);
                    ptr += Guid.HexsToChars(ptr, this._a >> 8, this._a);
                    *(ptr++) = ',';
                    *(ptr++) = '0';
                    *(ptr++) = 'x';
                    ptr += Guid.HexsToChars(ptr, this._b >> 8, (int)this._b);
                    *(ptr++) = ',';
                    *(ptr++) = '0';
                    *(ptr++) = 'x';
                    ptr += Guid.HexsToChars(ptr, this._c >> 8, (int)this._c);
                    *(ptr++) = ',';
                    *(ptr++) = '{';
                    ptr += Guid.HexsToCharsHexOutput(ptr, (int)this._d, (int)this._e);
                    *(ptr++) = ',';
                    ptr += Guid.HexsToCharsHexOutput(ptr, (int)this._f, (int)this._g);
                    *(ptr++) = ',';
                    ptr += Guid.HexsToCharsHexOutput(ptr, (int)this._h, (int)this._i);
                    *(ptr++) = ',';
                    ptr += Guid.HexsToCharsHexOutput(ptr, (int)this._j, (int)this._k);
                    *(ptr++) = '}';
                }
                else
                {
                    ptr += Guid.HexsToChars(ptr, this._a >> 24, this._a >> 16);
                    ptr += Guid.HexsToChars(ptr, this._a >> 8, this._a);
                    if (flag)
                    {
                        *(ptr++) = '-';
                    }
                    ptr += Guid.HexsToChars(ptr, this._b >> 8, (int)this._b);
                    if (flag)
                    {
                        *(ptr++) = '-';
                    }
                    ptr += Guid.HexsToChars(ptr, this._c >> 8, (int)this._c);
                    if (flag)
                    {
                        *(ptr++) = '-';
                    }
                    ptr += Guid.HexsToChars(ptr, (int)this._d, (int)this._e);
                    if (flag)
                    {
                        *(ptr++) = '-';
                    }
                    ptr += Guid.HexsToChars(ptr, (int)this._f, (int)this._g);
                    ptr += Guid.HexsToChars(ptr, (int)this._h, (int)this._i);
                    ptr += Guid.HexsToChars(ptr, (int)this._j, (int)this._k);
                }
                if (num != 0)
                {
                    *(ptr++) = (char)(num >> 16);
                }
            }
            charsWritten = num2;
            return true;
        }
References System.Guid._a, System.Guid._b, System.Guid._c, System.Guid._d, System.Guid._e, System.Guid._f, System.Guid._g, System.Guid._h, System.Guid._i, System.Guid._j, System.Guid._k, System.destination, System.format, System.Guid.HexsToChars(), System.Guid.HexsToCharsHexOutput(), and int.
Referenced by System.Guid.ToString(), and System.Guid.TryFormat().