Terraria Decompiled: System.Guid.TryParseGuidWithHexPrefix
TryParseGuidWithHexPrefix()
static unsafe bool System.Guid.TryParseGuidWithHexPrefix (ReadOnlySpan< char > guidString, ref Guid::GuidResult result) inline static private
Definition at line 466 of file Guid.cs.
        {
            guidString = Guid.EatAllWhitespace(guidString);
            if (guidString.Length == 0 || *guidString[0] != 123)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Expected {0xdddddddd, etc}.");
                return false;
            }
            if (!Guid.IsHexPrefix(guidString, 1))
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Expected hex 0x in '{0}'.", "{0xdddddddd, etc}");
                return false;
            }
            int num = 3;
            int num2 = guidString.Slice(num).IndexOf(',');
            if (num2 <= 0)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Could not find a comma, or the length between the previous token and the comma was zero (i.e., '0x,'etc.).");
                return false;
            }
            if (!Guid.StringToInt(guidString.Slice(num, num2), -1, 4096, out result._parsedGuid._a, ref result))
            {
                return false;
            }
            if (!Guid.IsHexPrefix(guidString, num + num2 + 1))
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Expected hex 0x in '{0}'.", "{0xdddddddd, 0xdddd, etc}");
                return false;
            }
            num = num + num2 + 3;
            num2 = guidString.Slice(num).IndexOf(',');
            if (num2 <= 0)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Could not find a comma, or the length between the previous token and the comma was zero (i.e., '0x,'etc.).");
                return false;
            }
            if (!Guid.StringToShort(guidString.Slice(num, num2), -1, 4096, out result._parsedGuid._b, ref result))
            {
                return false;
            }
            if (!Guid.IsHexPrefix(guidString, num + num2 + 1))
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Expected hex 0x in '{0}'.", "{0xdddddddd, 0xdddd, 0xdddd, etc}");
                return false;
            }
            num = num + num2 + 3;
            num2 = guidString.Slice(num).IndexOf(',');
            if (num2 <= 0)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Could not find a comma, or the length between the previous token and the comma was zero (i.e., '0x,'etc.).");
                return false;
            }
            if (!Guid.StringToShort(guidString.Slice(num, num2), -1, 4096, out result._parsedGuid._c, ref result))
            {
                return false;
            }
            if (guidString.Length <= num + num2 + 1 || *guidString[num + num2 + 1] != 123)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Expected {0xdddddddd, etc}.");
                return false;
            }
            num2++;
            Span<byte> span = new Span<byte>(stackalloc byte[(UIntPtr)8], 8);
            for (int i = 0; i < span.Length; i++)
            {
                if (!Guid.IsHexPrefix(guidString, num + num2 + 1))
                {
                    result.SetFailure(Guid.ParseFailureKind.Format, "Expected hex 0x in '{0}'.", "{... { ... 0xdd, ...}}");
                    return false;
                }
                num = num + num2 + 3;
                if (i < 7)
                {
                    num2 = guidString.Slice(num).IndexOf(',');
                    if (num2 <= 0)
                    {
                        result.SetFailure(Guid.ParseFailureKind.Format, "Could not find a comma, or the length between the previous token and the comma was zero (i.e., '0x,'etc.).");
                        return false;
                    }
                }
                else
                {
                    num2 = guidString.Slice(num).IndexOf('}');
                    if (num2 <= 0)
                    {
                        result.SetFailure(Guid.ParseFailureKind.Format, "Could not find a brace, or the length between the previous token and the brace was zero (i.e., '0x,'etc.).");
                        return false;
                    }
                }
                int num3;
                if (!Guid.StringToInt(guidString.Slice(num, num2), -1, 4096, out num3, ref result))
                {
                    return false;
                }
                uint num4 = (uint)num3;
                if (num4 > 255U)
                {
                    result.SetFailure(Guid.ParseFailureKind.Format, "Value was either too large or too small for an unsigned byte.");
                    return false;
                }
                *span[i] = (byte)num4;
            }
            result._parsedGuid._d = *span[0];
            result._parsedGuid._e = *span[1];
            result._parsedGuid._f = *span[2];
            result._parsedGuid._g = *span[3];
            result._parsedGuid._h = *span[4];
            result._parsedGuid._i = *span[5];
            result._parsedGuid._j = *span[6];
            result._parsedGuid._k = *span[7];
            if (num + num2 + 1 >= guidString.Length || *guidString[num + num2 + 1] != 125)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Could not find the ending brace.");
                return false;
            }
            if (num + num2 + 1 != guidString.Length - 1)
            {
                result.SetFailure(Guid.ParseFailureKind.Format, "Additional non-parsable characters are at the end of the string.");
                return false;
            }
            return true;
        }
References System.Guid.EatAllWhitespace(), System.Guid.IsHexPrefix(), System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.ReadOnlySpan< T >.Slice(), System.Guid.StringToInt(), System.Guid.StringToShort(), and System.U.
Referenced by System.Guid.TryParseGuid().