Terraria Decompiled: System.Guid.CompareTo
CompareTo() [2/2]
int System.Guid.CompareTo (object value) inline
Implements System.IComparable< in T >.
Definition at line 953 of file Guid.cs.
        {
            if (value == null)
            {
                return 1;
            }
            if (!(value is Guid))
            {
                throw new ArgumentException("Object must be of type GUID.", "value");
            }
            Guid guid = (Guid)value;
            if (guid._a != this._a)
            {
                return this.GetResult((uint)this._a, (uint)guid._a);
            }
            if (guid._b != this._b)
            {
                return this.GetResult((uint)this._b, (uint)guid._b);
            }
            if (guid._c != this._c)
            {
                return this.GetResult((uint)this._c, (uint)guid._c);
            }
            if (guid._d != this._d)
            {
                return this.GetResult((uint)this._d, (uint)guid._d);
            }
            if (guid._e != this._e)
            {
                return this.GetResult((uint)this._e, (uint)guid._e);
            }
            if (guid._f != this._f)
            {
                return this.GetResult((uint)this._f, (uint)guid._f);
            }
            if (guid._g != this._g)
            {
                return this.GetResult((uint)this._g, (uint)guid._g);
            }
            if (guid._h != this._h)
            {
                return this.GetResult((uint)this._h, (uint)guid._h);
            }
            if (guid._i != this._i)
            {
                return this.GetResult((uint)this._i, (uint)guid._i);
            }
            if (guid._j != this._j)
            {
                return this.GetResult((uint)this._j, (uint)guid._j);
            }
            if (guid._k != this._k)
            {
                return this.GetResult((uint)this._k, (uint)guid._k);
            }
            return 0;
        }
References System.Guid._a, System.Guid._b, System.Guid._c, System.Guid._d, System.Guid._e, System.Guid._f, System.Guid._g, System.Guid._h, System.Guid._i, System.Guid._j, System.Guid._k, System.Guid.GetResult(), System.Guid.Guid(), and System.value.
Referenced by Newtonsoft.Json.Linq.JValue.Compare().