Terraria Decompiled: System.Guid.ParseExact
ParseExact() [1/2]
static unsafe Guid System.Guid.ParseExact (ReadOnlySpan< char > input, ReadOnlySpan< char > format) inline static
Definition at line 190 of file Guid.cs.
        {
            if (format.Length != 1)
            {
                throw new FormatException("Format String can be only 'D', 'd', 'N', 'n', 'P', 'p', 'B', 'b', 'X' or 'x'.");
            }
            char c = (char)(*format[0]);
            if (c <= 'X')
            {
                if (c <= 'D')
                {
                    if (c == 'B')
                    {
                        goto IL_0071;
                    }
                    if (c != 'D')
                    {
                        goto IL_0083;
                    }
                }
                else
                {
                    if (c == 'N')
                    {
                        goto IL_006D;
                    }
                    if (c == 'P')
                    {
                        goto IL_0076;
                    }
                    if (c != 'X')
                    {
                        goto IL_0083;
                    }
                    goto IL_007B;
                }
            }
            else if (c <= 'd')
            {
                if (c == 'b')
                {
                    goto IL_0071;
                }
                if (c != 'd')
                {
                    goto IL_0083;
                }
            }
            else
            {
                if (c == 'n')
                {
                    goto IL_006D;
                }
                if (c == 'p')
                {
                    goto IL_0076;
                }
                if (c != 'x')
                {
                    goto IL_0083;
                }
                goto IL_007B;
            }
            Guid.GuidStyles guidStyles = Guid.GuidStyles.RequireDashes;
            goto IL_008E;
            IL_006D:
            guidStyles = Guid.GuidStyles.None;
            goto IL_008E;
            IL_0071:
            guidStyles = Guid.GuidStyles.BraceFormat;
            goto IL_008E;
            IL_0076:
            guidStyles = Guid.GuidStyles.ParenthesisFormat;
            goto IL_008E;
            IL_007B:
            guidStyles = Guid.GuidStyles.HexFormat;
            goto IL_008E;
            IL_0083:
            throw new FormatException("Format String can be only 'D', 'd', 'N', 'n', 'P', 'p', 'B', 'b', 'X' or 'x'.");
            IL_008E:
            Guid.GuidResult guidResult = default(Guid.GuidResult);
            guidResult.Init(Guid.GuidParseThrowStyle.AllButOverflow);
            if (Guid.TryParseGuid(input, guidStyles, ref guidResult))
            {
                return guidResult._parsedGuid;
            }
            throw guidResult.GetGuidParseException();
        }
References System.Guid.GuidResult._parsedGuid, System.format, System.Guid.GuidResult.GetGuidParseException(), System.Guid.GuidResult.Init(), System.input, and System.Guid.TryParseGuid().