Terraria Decompiled: System.Guid.StringToLong
StringToLong()
static bool System.Guid.StringToLong (ReadOnlySpan< char > str, ref int parsePos, int flags, out long result, ref Guid::GuidResult parseResult) inline static private
Definition at line 803 of file Guid.cs.
        {
            result = 0L;
            try
            {
                result = ParseNumbers.StringToLong(str, 16, flags, ref parsePos);
            }
            catch (OverflowException ex)
            {
                if (parseResult._throwStyle == Guid.GuidParseThrowStyle.All)
                {
                    throw;
                }
                if (parseResult._throwStyle == Guid.GuidParseThrowStyle.AllButOverflow)
                {
                    throw new FormatException("Unrecognized Guid format.", ex);
                }
                parseResult.SetFailure(ex);
                return false;
            }
            catch (Exception ex2)
            {
                if (parseResult._throwStyle == Guid.GuidParseThrowStyle.None)
                {
                    parseResult.SetFailure(ex2);
                    return false;
                }
                throw;
            }
            return true;
        }
References System.L, and System.ParseNumbers.StringToLong().
Referenced by System.Guid.TryParseGuidWithDashes(), and System.Guid.TryParseGuidWithNoStyle().