Terraria Decompiled: System.Threading.Tasks.TaskFactory.FromAsyncCoreLogic
FromAsyncCoreLogic()
static void System.Threading.Tasks.TaskFactory< TResult >.FromAsyncCoreLogic (IAsyncResult iar, Func< IAsyncResult, TResult > endFunction, Action< IAsyncResult > endAction, Task< TResult > promise, bool requiresSynchronization) inline static private
Definition at line 168 of file TaskFactory.cs.
        {
            Exception ex = null;
            OperationCanceledException ex2 = null;
            TResult tresult = default(TResult);
            try
            {
                if (endFunction != null)
                {
                    tresult = endFunction(iar);
                }
                else
                {
                    endAction(iar);
                }
            }
            catch (OperationCanceledException ex2)
            {
            }
            catch (Exception ex)
            {
            }
            finally
            {
                if (ex2 != null)
                {
                    promise.TrySetCanceled(ex2.CancellationToken, ex2);
                }
                else if (ex != null)
                {
                    promise.TrySetException(ex);
                }
                else
                {
                    if (DebuggerSupport.LoggingOn)
                    {
                        DebuggerSupport.TraceOperationCompletion(CausalityTraceLevel.Required, promise, AsyncStatus.Completed);
                    }
                    DebuggerSupport.RemoveFromActiveTasks(promise);
                    if (requiresSynchronization)
                    {
                        promise.TrySetResult(tresult);
                    }
                    else
                    {
                        promise.DangerousSetResult(tresult);
                    }
                }
            }
        }
References System.OperationCanceledException.CancellationToken, System.Threading.Tasks.Task< TResult >.DangerousSetResult(), System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasks(), System.Threading.Tasks.DebuggerSupport.TraceOperationCompletion(), System.Threading.Tasks.Task< TResult >.TrySetCanceled(), System.Threading.Tasks.Task< TResult >.TrySetException(), and System.Threading.Tasks.Task< TResult >.TrySetResult().
Referenced by System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 >(), and System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2, TArg3 >().