Terraria Decompiled: System.Threading.Tasks.TaskFactory.CommonCWAnyLogic
CommonCWAnyLogic()
static Task< Task > System.Threading.Tasks.TaskFactory< TResult >.CommonCWAnyLogic (IList< Task > tasks) inline static package
Definition at line 585 of file TaskFactory.2.cs.
        {
            TaskFactory.CompleteOnInvokePromise completeOnInvokePromise = new TaskFactory.CompleteOnInvokePromise(tasks);
            bool flag = false;
            int count = tasks.Count;
            for (int i = 0; i < count; i++)
            {
                Task task = tasks[i];
                if (task == null)
                {
                    throw new ArgumentException("The tasks argument included a null value.", "tasks");
                }
                if (!flag)
                {
                    if (completeOnInvokePromise.IsCompleted)
                    {
                        flag = true;
                    }
                    else if (task.IsCompleted)
                    {
                        completeOnInvokePromise.Invoke(task);
                        flag = true;
                    }
                    else
                    {
                        task.AddCompletionAction(completeOnInvokePromise);
                        if (completeOnInvokePromise.IsCompleted)
{
                            task.RemoveContinuation(completeOnInvokePromise);
                        }
                    }
                }
            }
            return completeOnInvokePromise;
        }
References System.Collections.Generic.ICollection< T >.Count, System.count, System.Threading.Tasks.TaskFactory< TResult >.CompleteOnInvokePromise.Invoke(), System.Threading.Tasks.Task< TResult >.IsCompleted, and System.task.
Referenced by System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAnyImpl< TAntecedentResult >(), System.Threading.Tasks.Task< TResult >.WaitAny(), System.Threading.Tasks.Task< TResult >.WhenAny(), and System.Threading.Tasks.Task< TResult >.WhenAny().