Terraria Decompiled: System.Threading.Tasks.TaskFactory.ContinueWhenAllImpl
ContinueWhenAllImpl() [2/2]
static Task< TResult > System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl (Task[] tasks, Func< Task[], TResult > continuationFunction, TaskContinuationOptions continuationOptions, CancellationToken cancellationToken, TaskScheduler scheduler) inline static package
Definition at line 656 of file TaskFactory.cs.
        {
            TaskFactory.CheckMultiTaskContinuationOptions(continuationOptions);
            if (tasks == null)
            {
                throw new ArgumentNullException("tasks");
            }
            if (scheduler == null)
            {
                throw new ArgumentNullException("scheduler");
            }
            Task[] array = TaskFactory.CheckMultiContinuationTasksAndCopy(tasks);
            if (cancellationToken.IsCancellationRequested && (continuationOptions & TaskContinuationOptions.LazyCancellation) == TaskContinuationOptions.None)
            {
                return TaskFactory<TResult>.CreateCanceledTask(continuationOptions, cancellationToken);
            }
            return TaskFactory.CommonCWAllLogic(array).ContinueWith<TResult>(delegate(Task<Task[]> completedTasks, object state)
            {
                completedTasks.NotifyDebuggerOfWaitCompletionIfNecessary();
                return ((Func<Task[], TResult>)state)(completedTasks.Result);
            }, continuationFunction, scheduler, cancellationToken, continuationOptions);
        }
References System.array, System.Threading.Tasks.TaskFactory< TResult >.CheckMultiContinuationTasksAndCopy(), System.Threading.Tasks.TaskFactory< TResult >.CheckMultiTaskContinuationOptions(), System.Threading.Tasks.TaskFactory< TResult >.CommonCWAllLogic(), System.Threading.Tasks.Task< TResult >.ContinueWith(), System.Threading.Tasks.TaskFactory< TResult >.CreateCanceledTask(), System.Threading.CancellationToken.IsCancellationRequested, and System.state.
Referenced by System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult, TResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult, TResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult, TResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TAntecedentResult, TResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TResult >(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TResult >(), and System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAll< TResult >().