Terraria Decompiled: System.Threading.Tasks.TaskFactory.CheckFromAsyncOptions
CheckFromAsyncOptions()
static void System.Threading.Tasks.TaskFactory< TResult >.CheckFromAsyncOptions (TaskCreationOptions creationOptions, bool hasBeginMethod) inline static package
Definition at line 369 of file TaskFactory.2.cs.
        {
            if (hasBeginMethod)
            {
                if ((creationOptions & TaskCreationOptions.LongRunning) != TaskCreationOptions.None)
                {
                    throw new ArgumentOutOfRangeException("creationOptions", "It is invalid to specify TaskCreationOptions.LongRunning in calls to FromAsync.");
                }
                if ((creationOptions & TaskCreationOptions.PreferFairness) != TaskCreationOptions.None)
                {
                    throw new ArgumentOutOfRangeException("creationOptions", "It is invalid to specify TaskCreationOptions.PreferFairness in calls to FromAsync.");
                }
            }
            if ((creationOptions & ~(TaskCreationOptions.PreferFairness | TaskCreationOptions.LongRunning | TaskCreationOptions.AttachedToParent | TaskCreationOptions.DenyChildAttach | TaskCreationOptions.HideScheduler)) != TaskCreationOptions.None)
            {
                throw new ArgumentOutOfRangeException("creationOptions");
            }
        }
Referenced by System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1 >(), System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 >(), and System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2, TArg3 >().