Terraria Decompiled: System.Threading.Tasks.TaskFactory.FromAsyncImpl< TArg1, TArg2 >
FromAsyncImpl< TArg1, TArg2 >()
static Task< TResult > System.Threading.Tasks.TaskFactory< TResult >.FromAsyncImpl< TArg1, TArg2 > (Func< TArg1, TArg2, AsyncCallback, object, IAsyncResult > beginMethod, Func< IAsyncResult, TResult > endFunction, Action< IAsyncResult > endAction, TArg1 arg1, TArg2 arg2, object state, TaskCreationOptions creationOptions) inline static package
Definition at line 413 of file TaskFactory.cs.
        {
            if (beginMethod == null)
            {
                throw new ArgumentNullException("beginMethod");
            }
            if (endFunction == null && endAction == null)
            {
                throw new ArgumentNullException("endMethod");
            }
            TaskFactory.CheckFromAsyncOptions(creationOptions, true);
            Task<TResult> promise = new Task<TResult>(state, creationOptions);
            if (DebuggerSupport.LoggingOn)
            {
                DebuggerSupport.TraceOperationCreation(CausalityTraceLevel.Required, promise, "TaskFactory.FromAsync: " + ((beginMethod != null) ? beginMethod.ToString() : null), 0UL);
            }
            DebuggerSupport.AddToActiveTasks(promise);
            try
            {
                IAsyncResult asyncResult = beginMethod(arg1, arg2, delegate(IAsyncResult iar)
                {
                    if (!iar.CompletedSynchronously)
                    {
                        TaskFactory<TResult>.FromAsyncCoreLogic(iar, endFunction, endAction, promise, true);
                    }
                }, state);
                if (asyncResult.CompletedSynchronously)
                {
                    TaskFactory<TResult>.FromAsyncCoreLogic(asyncResult, endFunction, endAction, promise, false);
                }
            }
            catch
            {
                if (DebuggerSupport.LoggingOn)
                {
                    DebuggerSupport.TraceOperationCompletion(CausalityTraceLevel.Required, promise, AsyncStatus.Error);
                }
                DebuggerSupport.RemoveFromActiveTasks(promise);
                promise.TrySetResult(default(TResult));
                throw;
            }
            return promise;
        }
References System.Threading.Tasks.DebuggerSupport.AddToActiveTasks(), System.Threading.Tasks.TaskFactory< TResult >.CheckFromAsyncOptions(), System.IAsyncResult.CompletedSynchronously, System.Threading.Tasks.TaskFactory< TResult >.FromAsyncCoreLogic(), System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasks(), System.state, System.Threading.Tasks.DebuggerSupport.TraceOperationCompletion(), System.Threading.Tasks.DebuggerSupport.TraceOperationCreation(), and System.Threading.Tasks.Task< TResult >.TrySetResult().