Terraria Decompiled: System.Threading.Tasks.TaskFactory.CommonCWAllLogic
CommonCWAllLogic()
static Task< Task[]> System.Threading.Tasks.TaskFactory< TResult >.CommonCWAllLogic (Task[] tasksCopy) inline static package
Definition at line 389 of file TaskFactory.2.cs.
        {
            TaskFactory.CompleteOnCountdownPromise completeOnCountdownPromise = new TaskFactory.CompleteOnCountdownPromise(tasksCopy);
            for (int i = 0; i < tasksCopy.Length; i++)
            {
                if (tasksCopy[i].IsCompleted)
                {
                    completeOnCountdownPromise.Invoke(tasksCopy[i]);
                }
                else
                {
                    tasksCopy[i].AddCompletionAction(completeOnCountdownPromise);
                }
            }
            return completeOnCountdownPromise;
        }
References System.Threading.Tasks.Task< TResult >.AddCompletionAction(), and System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.Invoke().
Referenced by System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl(), System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl< TAntecedentResult >(), and System.Threading.Tasks.TaskFactory< TResult >.ContinueWhenAllImpl< TAntecedentResult >().