Terraria Decompiled: System.Reflection.Emit.ConstructorBuilder.ConstructorBuilder
ConstructorBuilder()
System.Reflection.Emit.ConstructorBuilder.ConstructorBuilder (TypeBuilder tb, MethodAttributes attributes, CallingConventions callingConvention, Type[] parameterTypes, Type paramModReq[][], Type paramModOpt[][]) inline package
Definition at line 44 of file ConstructorBuilder.cs.
        {
            this.attrs = attributes | MethodAttributes.SpecialName | MethodAttributes.RTSpecialName;
            this.call_conv = callingConvention;
            if (parameterTypes != null)
            {
                for (int i = 0; i < parameterTypes.Length; i++)
                {
                    if (parameterTypes[i] == null)
                    {
                        throw new ArgumentException("Elements of the parameterTypes array cannot be null", "parameterTypes");
                    }
                }
                this.parameters = new Type[parameterTypes.Length];
                Array.Copy(parameterTypes, this.parameters, parameterTypes.Length);
            }
            this.type = tb;
            this.paramModReq = paramModReq;
            this.paramModOpt = paramModOpt;
            this.table_idx = this.get_next_table_index(this, 6, 1);
            ((ModuleBuilder)tb.Module).RegisterToken(this, this.GetToken().Token);
        }
References System.Array.Copy(), System.Reflection.Emit.ConstructorBuilder.get_next_table_index(), System.Reflection.Emit.ConstructorBuilder.GetToken(), System.Reflection.Emit.TypeBuilder.Module, System.Reflection.Emit.ConstructorBuilder.parameters, System.Reflection.Emit.ConstructorBuilder.paramModOpt, System.Reflection.Emit.ConstructorBuilder.paramModReq, and System.Reflection.Emit.MethodToken.Token.