Terraria Decompiled: System.Reflection.Emit.ConstructorBuilder.GenerateDebugInfo
GenerateDebugInfo()
void System.Reflection.Emit.ConstructorBuilder.GenerateDebugInfo (ISymbolWriter symbolWriter) inline package
Definition at line 476 of file ConstructorBuilder.cs.
        {
            if (this.ilgen != null && this.ilgen.HasDebugInfo)
            {
                SymbolToken symbolToken = new SymbolToken(this.GetToken().Token);
                symbolWriter.OpenMethod(symbolToken);
                symbolWriter.SetSymAttribute(symbolToken, "__name", Encoding.UTF8.GetBytes(this.Name));
                this.ilgen.GenerateDebugInfo(symbolWriter);
                symbolWriter.CloseMethod();
            }
        }
References System.Diagnostics.SymbolStore.ISymbolWriter.CloseMethod(), System.Reflection.Emit.ILGenerator.GenerateDebugInfo(), System.Text.Encoding.GetBytes(), System.Reflection.Emit.ConstructorBuilder.GetToken(), System.Reflection.Emit.ILGenerator.HasDebugInfo, System.Reflection.Emit.ConstructorBuilder.ilgen, System.Diagnostics.SymbolStore.ISymbolWriter.OpenMethod(), System.Diagnostics.SymbolStore.ISymbolWriter.SetSymAttribute(), and System.Text.Encoding.UTF8.
Referenced by System.Reflection.Emit.TypeBuilder.GenerateDebugInfo().