Terraria Decompiled: System.Reflection.Emit.ConstructorBuilder.AddDeclarativeSecurity
AddDeclarativeSecurity()
void System.Reflection.Emit.ConstructorBuilder.AddDeclarativeSecurity (SecurityAction action, PermissionSet pset) inline
Definition at line 247 of file ConstructorBuilder.cs.
        {
            if (pset == null)
            {
                throw new ArgumentNullException("pset");
            }
            if (action == SecurityAction.RequestMinimum || action == SecurityAction.RequestOptional || action == SecurityAction.RequestRefuse)
            {
                throw new ArgumentOutOfRangeException("action", "Request* values are not permitted");
            }
            this.RejectIfCreated();
            if (this.permissions != null)
            {
                RefEmitPermissionSet[] array = this.permissions;
                for (int i = 0; i < array.Length; i++)
                {
                    if (array[i].action == action)
                    {
                        throw new InvalidOperationException("Multiple permission sets specified with the same SecurityAction.");
                    }
                }
                RefEmitPermissionSet[] array2 = new RefEmitPermissionSet[this.permissions.Length + 1];
                this.permissions.CopyTo(array2, 0);
                this.permissions = array2;
            }
            else
            {
                this.permissions = new RefEmitPermissionSet[1];
            }
            this.permissions[this.permissions.Length - 1] = new RefEmitPermissionSet(action, pset.ToXml().ToString());
            this.attrs |= MethodAttributes.HasSecurity;
        }
References System.action, System.array, System.Reflection.Emit.ConstructorBuilder.permissions, System.Reflection.Emit.ConstructorBuilder.RejectIfCreated(), System.Security.SecurityElement.ToString(), and System.Security.PermissionSet.ToXml().