Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.Update
Update()
void Terraria.Graphics.Capture.CaptureInterface.Update (CaptureInterface::SelectionContext context) inline
Definition at line 82 of file CaptureInterface.cs.
        {
            CaptureInterface._selectionContext = context;
            if (CaptureInterface.CameraLock)
            {
                return;
            }
            PlayerInput.SetZoom_UI();
            bool toggleCameraMode = PlayerInput.Triggers.Current.ToggleCameraMode;
            if (toggleCameraMode && !this.KeyToggleActiveHeld && (Main.mouseItem.type == 0 || this.Active) && !Main.CaptureModeDisabled && !Main.player[Main.myPlayer].dead && !Main.player[Main.myPlayer].ghost)
            {
                this.ToggleCamera(!this.Active);
            }
            this.KeyToggleActiveHeld = toggleCameraMode;
            if (!this.Active)
            {
                return;
            }
            Main.blockMouse = true;
            if (CaptureInterface.JustActivated && Main.mouseLeftRelease && !Main.mouseLeft)
            {
                CaptureInterface.JustActivated = false;
            }
            Vector2 vector = new Vector2((float)Main.mouseX, (float)Main.mouseY);
            if (this.UpdateButtons(vector) && Main.mouseLeft)
            {
                return;
            }
            foreach (KeyValuePair<int, CaptureInterface.CaptureInterfaceMode> keyValuePair in CaptureInterface.Modes)
            {
                keyValuePair.Value.Selected = keyValuePair.Key == this.SelectedMode;
                keyValuePair.Value.Update();
            }
            PlayerInput.SetZoom_Unscaled();
        }
References Terraria.Graphics.Capture.CaptureInterface.Active, Terraria.Graphics.Capture.CaptureInterface.CameraLock, Terraria.Main.CaptureModeDisabled, Terraria.GameInput.TriggersPack.Current, Terraria.Player.dead, Terraria.Player.ghost, Terraria.Graphics.Capture.CaptureInterface.JustActivated, Terraria.Graphics.Capture.CaptureInterface.KeyToggleActiveHeld, Terraria.Graphics.Capture.CaptureInterface.Modes, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Graphics.Capture.CaptureInterface.SelectedMode, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.GameInput.PlayerInput.SetZoom_Unscaled(), Terraria.Graphics.Capture.CaptureInterface.ToggleCamera(), Terraria.GameInput.TriggersSet.ToggleCameraMode, Terraria.GameInput.PlayerInput.Triggers, Terraria.Item.type, Terraria.Graphics.Capture.CaptureInterface.UpdateButtons(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Graphics.Capture.CaptureManager.Update().