Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.FullScreenArea
FullScreenArea()
static Rectangle Terraria.Graphics.Capture.CaptureInterface.FullScreenArea () inline static
Definition at line 250 of file CaptureInterface.cs.
        {
            int screenWidth = Main.screenWidth;
            int screenHeight = Main.screenHeight;
            Main.screenWidth = PlayerInput.RealScreenWidth;
            Main.screenHeight = PlayerInput.RealScreenHeight;
            Rectangle rectangle;
            try
            {
                Vector2 vector = Main.Camera.ScaledPosition / 16f;
                Vector2 vector2 = (Main.Camera.ScaledPosition + Main.Camera.ScaledSize) / 16f;
                Point point = new Point((int)Math.Ceiling((double)vector.X), (int)Math.Ceiling((double)vector.Y));
                Point point2 = new Point((int)Math.Floor((double)vector2.X), (int)Math.Floor((double)vector2.Y));
                rectangle = new Rectangle(point.X, point.Y, point2.X - point.X, point2.Y - point.Y);
            }
            finally
            {
                Main.screenWidth = screenWidth;
                Main.screenHeight = screenHeight;
            }
            return rectangle;
        }
References Terraria.Main.Camera, System.Math.Ceiling(), System.Math.Floor(), Microsoft.Xna.Framework.Graphics.Point, Terraria.GameInput.PlayerInput.RealScreenHeight, Terraria.GameInput.PlayerInput.RealScreenWidth, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot(), and Terraria.Graphics.Capture.CaptureInterface.StartCamera().