Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.UpdateButtons
UpdateButtons()
bool Terraria.Graphics.Capture.CaptureInterface.UpdateButtons (Vector2 mouse) inline private
Definition at line 172 of file CaptureInterface.cs.
        {
            this.HoveredMode = -1;
            bool flag = !Main.graphics.IsFullScreen;
            int num = 9;
            for (int i = 0; i < num; i++)
            {
                Rectangle rectangle = new Rectangle(24 + 46 * i, 24, 42, 42);
                if (rectangle.Contains(mouse.ToPoint()))
                {
                    this.HoveredMode = i;
                    bool flag2 = Main.mouseLeft && Main.mouseLeftRelease;
                    int num2 = 0;
                    if (i == num2++ && flag2)
                    {
                        CaptureInterface.QuickScreenshot();
                    }
                    if (i == num2++ && flag2 && CaptureInterface.EdgeAPinned && CaptureInterface.EdgeBPinned)
                    {
                        CaptureSettings captureSettings = new CaptureSettings();
                        captureSettings.Area = CaptureInterface.GetArea();
                        captureSettings.Biome = CaptureBiome.GetCaptureBiome(CaptureInterface.Settings.BiomeChoiceIndex);
                        captureSettings.CaptureBackground = !CaptureInterface.Settings.TransparentBackground;
                        captureSettings.CaptureEntities = CaptureInterface.Settings.IncludeEntities;
                        captureSettings.UseScaling = CaptureInterface.Settings.PackImage;
                        captureSettings.CaptureMech = WiresUI.Settings.DrawWires;
                        if (captureSettings.Biome.WaterStyle != 13)
{
                            Main.liquidAlpha[13] = 0f;
                        }
                        CaptureInterface.StartCamera(captureSettings);
                    }
                    if (i == num2++ && flag2 && this.SelectedMode != 0)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        this.SelectedMode = 0;
                        this.ToggleCamera(true);
                    }
                    if (i == num2++ && flag2 && this.SelectedMode != 1)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        this.SelectedMode = 1;
                        this.ToggleCamera(true);
                    }
                    if (i == num2++ && flag2)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        CaptureInterface.ResetFocus();
                    }
                    if (i == num2++ && flag2 && Main.mapEnabled)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        Main.mapFullscreen = !Main.mapFullscreen;
                    }
                    if (i == num2++ && flag2 && this.SelectedMode != 2)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        this.SelectedMode = 2;
                        this.ToggleCamera(true);
                    }
                    if (i == num2++ && (flag2 && flag))
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        Utils.OpenFolder(Path.Combine(Main.SavePath, "Captures"));
                    }
                    if (i == num2++ && flag2)
                    {
                        this.ToggleCamera(false);
                        Main.blockMouse = true;
                        Main.mouseLeftRelease = false;
                    }
                    return true;
                }
            }
            return false;
        }
References Terraria.Graphics.Capture.CaptureSettings.Biome, Terraria.Graphics.Capture.CaptureInterface.Settings.BiomeChoiceIndex, System.IO.Path.Combine(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.UI.WiresUI.Settings.DrawWires, Terraria.Graphics.Capture.CaptureInterface.EdgeAPinned, Terraria.Graphics.Capture.CaptureInterface.EdgeBPinned, Terraria.Graphics.Capture.CaptureInterface.GetArea(), Terraria.Graphics.Capture.CaptureBiome.GetCaptureBiome(), Terraria.Main.graphics, Terraria.Graphics.Capture.CaptureInterface.Settings.IncludeEntities, Microsoft.Xna.Framework.GraphicsDeviceManager.IsFullScreen, Terraria.Main.liquidAlpha, Terraria.Main.mapEnabled, Terraria.Main.mapFullscreen, Terraria.Main.mouseLeftRelease, Terraria.Utils.OpenFolder(), Terraria.Graphics.Capture.CaptureInterface.Settings.PackImage, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Graphics.Capture.CaptureInterface.QuickScreenshot(), Terraria.Graphics.Capture.CaptureInterface.ResetFocus(), Terraria.Main.SavePath, Terraria.Graphics.Capture.CaptureInterface.SelectedMode, Terraria.Graphics.Capture.CaptureInterface.StartCamera(), Terraria.Graphics.Capture.CaptureInterface.ToggleCamera(), Terraria.Graphics.Capture.CaptureInterface.Settings.TransparentBackground, and Terraria.Graphics.Capture.CaptureBiome.WaterStyle.
Referenced by Terraria.Graphics.Capture.CaptureInterface.Update().