Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.Draw
Draw()
void Terraria.Graphics.Capture.CaptureInterface.Draw (SpriteBatch sb) inline
Definition at line 119 of file CaptureInterface.cs.
        {
            if (!this.Active)
            {
                return;
            }
            sb.End();
            sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
            PlayerInput.SetZoom_UI();
            foreach (CaptureInterface.CaptureInterfaceMode captureInterfaceMode in CaptureInterface.Modes.Values)
            {
                captureInterfaceMode.Draw(sb);
            }
            sb.End();
            sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
            PlayerInput.SetZoom_UI();
            Main.mouseText = false;
            Main.instance.GUIBarsDraw();
            this.DrawButtons(sb);
            Main.instance.DrawMouseOver();
            sb.End();
            sb.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
            Utils.DrawBorderStringBig(sb, Lang.inter[81].Value, new Vector2((float)Main.screenWidth * 0.5f, 100f), Color.White, 1f, 0.5f, 0.5f, -1);
            Utils.DrawCursorSingle(sb, Main.cursorColor, float.NaN, Main.cursorScale, default(Vector2), 0, 0);
            this.DrawCameraLock(sb);
            sb.End();
            sb.Begin();
        }
References Terraria.Graphics.Capture.CaptureInterface.Active, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.Main.cursorColor, Terraria.Main.cursorScale, Terraria.Utils.DrawBorderStringBig(), Terraria.Graphics.Capture.CaptureInterface.DrawButtons(), Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock(), Terraria.Utils.DrawCursorSingle(), Terraria.Main.DrawMouseOver(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Main.GUIBarsDraw(), Terraria.Main.instance, Terraria.Lang.inter, Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, Terraria.Graphics.Capture.CaptureInterface.Modes, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.Main.screenWidth, Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Main.UIScaleMatrix, Terraria.Localization.LocalizedText.Value, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Graphics.Capture.CaptureManager.Draw().