Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.ToggleCamera
ToggleCamera()
void Terraria.Graphics.Capture.CaptureInterface.ToggleCamera (bool On = true) inline
Definition at line 149 of file CaptureInterface.cs.
        {
            if (CaptureInterface.CameraLock)
            {
                return;
            }
            bool active = this.Active;
            this.Active = CaptureInterface.Modes.ContainsKey(this.SelectedMode) && On;
            if (active != this.Active)
            {
                SoundEngine.PlaySound(On ? 10 : 11, -1, -1, 1, 1f, 0f);
            }
            foreach (KeyValuePair<int, CaptureInterface.CaptureInterfaceMode> keyValuePair in CaptureInterface.Modes)
            {
                keyValuePair.Value.ToggleActive(this.Active && keyValuePair.Key == this.SelectedMode);
            }
            if (On && !active)
            {
                CaptureInterface.JustActivated = true;
            }
        }
References Terraria.Graphics.Capture.CaptureInterface.Active, Terraria.Graphics.Capture.CaptureInterface.CameraLock, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.Graphics.Capture.CaptureInterface.Modes, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Graphics.Capture.CaptureInterface.SelectedMode, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.Graphics.Capture.CaptureInterface.Update(), and Terraria.Graphics.Capture.CaptureInterface.UpdateButtons().