Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.DrawButtons
DrawButtons()
void Terraria.Graphics.Capture.CaptureInterface.DrawButtons (SpriteBatch sb) inline private
Definition at line 288 of file CaptureInterface.cs.
        {
            new Vector2((float)Main.mouseX, (float)Main.mouseY);
            int num = 9;
            for (int i = 0; i < num; i++)
            {
                Texture2D texture2D = TextureAssets.InventoryBack.Value;
                float num2 = 0.8f;
                Vector2 vector = new Vector2((float)(24 + 46 * i), 24f);
                Color color = Main.inventoryBack * 0.8f;
                if (this.SelectedMode == 0 && i == 2)
                {
                    texture2D = TextureAssets.InventoryBack14.Value;
                }
                else if (this.SelectedMode == 1 && i == 3)
                {
                    texture2D = TextureAssets.InventoryBack14.Value;
                }
                else if (this.SelectedMode == 2 && i == 6)
                {
                    texture2D = TextureAssets.InventoryBack14.Value;
                }
                else if (i >= 2 && i <= 3)
                {
                    texture2D = TextureAssets.InventoryBack2.Value;
                }
                sb.Draw(texture2D, vector, null, color, 0f, default(Vector2), num2, SpriteEffects.None, 0f);
                switch (i)
                {
                case 0:
                    texture2D = TextureAssets.Camera[7].Value;
                    break;
                case 1:
                    texture2D = TextureAssets.Camera[0].Value;
                    break;
                case 2:
                case 3:
                case 4:
                    texture2D = TextureAssets.Camera[i].Value;
                    break;
                case 5:
                    texture2D = (Main.mapFullscreen ? TextureAssets.MapIcon[0].Value : TextureAssets.MapIcon[4].Value);
                    break;
                case 6:
                    texture2D = TextureAssets.Camera[1].Value;
                    break;
                case 7:
                    texture2D = TextureAssets.Camera[6].Value;
                    break;
                case 8:
                    texture2D = TextureAssets.Camera[5].Value;
                    break;
                }
                sb.Draw(texture2D, vector + new Vector2(26f) * num2, null, Color.White, 0f, texture2D.Size() / 2f, 1f, SpriteEffects.None, 0f);
                bool flag = false;
                if (i != 1)
                {
                    if (i != 5)
                    {
                        if (i == 7)
{
                            if (Main.graphics.IsFullScreen)
{
                                flag = true;
                            }
                        }
                    }
                    else if (!Main.mapEnabled)
                    {
                        flag = true;
                    }
                }
                else if (!CaptureInterface.EdgeAPinned || !CaptureInterface.EdgeBPinned)
                {
                    flag = true;
                }
                if (flag)
                {
                    sb.Draw(TextureAssets.Cd.Value, vector + new Vector2(26f) * num2, null, Color.White * 0.65f, 0f, TextureAssets.Cd.Value.Size() / 2f, 1f, SpriteEffects.None, 0f);
                }
            }
            string text = "";
            switch (this.HoveredMode)
            {
            case -1:
                break;
            case 0:
                text = Lang.inter[111].Value;
                break;
            case 1:
                text = Lang.inter[67].Value;
                break;
            case 2:
                text = Lang.inter[69].Value;
                break;
            case 3:
                text = Lang.inter[70].Value;
                break;
            case 4:
                text = Lang.inter[78].Value;
                break;
            case 5:
                text = (Main.mapFullscreen ? Lang.inter[109].Value : Lang.inter[108].Value);
                break;
            case 6:
                text = Lang.inter[68].Value;
                break;
            case 7:
                text = Lang.inter[110].Value;
                break;
            case 8:
                text = Lang.inter[71].Value;
                break;
            default:
                text = "???";
                break;
            }
            int hoveredMode = this.HoveredMode;
            if (hoveredMode != 1)
            {
                if (hoveredMode != 5)
                {
                    if (hoveredMode == 7)
                    {
                        if (Main.graphics.IsFullScreen)
{
                            text = text + "\n" + Lang.inter[113].Value;
                        }
                    }
                }
                else if (!Main.mapEnabled)
                {
                    text = text + "\n" + Lang.inter[114].Value;
                }
            }
            else if (!CaptureInterface.EdgeAPinned || !CaptureInterface.EdgeBPinned)
            {
                text = text + "\n" + Lang.inter[112].Value;
            }
            if (text != "")
            {
                Main.instance.MouseText(text, 0, 0, -1, -1, -1, -1, 0);
            }
        }
References Terraria.GameContent.TextureAssets.Camera, Terraria.GameContent.TextureAssets.Cd, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Capture.CaptureInterface.EdgeAPinned, Terraria.Graphics.Capture.CaptureInterface.EdgeBPinned, Terraria.Main.graphics, Terraria.Graphics.Capture.CaptureInterface.HoveredMode, Terraria.Main.instance, Terraria.Lang.inter, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.GameContent.TextureAssets.InventoryBack14, Terraria.GameContent.TextureAssets.InventoryBack2, Microsoft.Xna.Framework.GraphicsDeviceManager.IsFullScreen, Terraria.Main.mapEnabled, Terraria.GameContent.TextureAssets.MapIcon, Terraria.Main.MouseText(), Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Graphics.Capture.CaptureInterface.SelectedMode, System.text, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Graphics.Capture.CaptureInterface.Draw().