Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable.RemoveEventHandlerNoLock
RemoveEventHandlerNoLock()
void System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.RemoveEventHandlerNoLock (EventRegistrationToken token) inline private
Definition at line 152 of file EventRegistrationTokenTable.cs.
        {
            T t;
            if (this.m_tokens.TryGetValue(token, out t))
            {
                this.m_tokens.Remove(token);
                Delegate @delegate = (Delegate)((object)this.m_invokeList);
                @delegate = Delegate.Remove(@delegate, (Delegate)((object)t));
                this.m_invokeList = (T)((object)@delegate);
            }
        }
References System.Delegate, System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.m_invokeList, System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.m_tokens, System.Delegate.Remove(), and System.T.
Referenced by System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.ExtractHandler(), System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.RemoveEventHandler(), and System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.RemoveEventHandler().