Terraria Decompiled: System.ValueTuple.Create
Create()
static ValueTuple System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Create () inline static
Definition at line 114 of file ValueTuple.cs.
        {
            return default(ValueTuple);
        }
Referenced by System.ValueTuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Create< T1, T2, T3, T4, T5, T6, T7, T8 >(), System.TupleExtensions.ToValueTuple< T1 >(), System.TupleExtensions.ToValueTuple< T1, T2 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19 >(), System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20 >(), and System.TupleExtensions.ToValueTuple< T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15, T16, T17, T18, T19, T20, T21 >().