Terraria Decompiled: Terraria.GameContent.Biomes.DungeonControlLine.CacheNormals
CacheNormals()
void Terraria.GameContent.Biomes.DungeonControlLine.CacheNormals () inline private
Definition at line 43 of file DungeonControlLine.cs.
        {
            this.StartNormal = new Vector2D(this.StartTangent.Y, -this.StartTangent.X);
            this.EndNormal = new Vector2D(-this.EndTangent.Y, this.EndTangent.X);
            this.CrossTangent = Vector2D.Cross(this.StartTangent, this.EndTangent);
        }
References ReLogic.Utilities.Vector2D.Cross(), Terraria.GameContent.Biomes.DungeonControlLine.EndTangent, Terraria.GameContent.Biomes.DungeonControlLine.StartTangent, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.DungeonControlLine.IsSelfIntersecting(), and Terraria.GameContent.Biomes.DungeonControlLine.Paint().