Terraria Decompiled: Terraria.GameContent.Biomes.DungeonControlLine.IsSelfIntersecting
IsSelfIntersecting()
bool Terraria.GameContent.Biomes.DungeonControlLine.IsSelfIntersecting () inline
Definition at line 204 of file DungeonControlLine.cs.
        {
            this.CacheNormals();
            double num = Vector2D.Cross(this.StartNormal, this.EndNormal);
            Vector2D vector2D = this.End - this.Start;
            double num2 = Vector2D.Cross(vector2D, this.EndNormal) / num;
            double num3 = Vector2D.Cross(vector2D, this.StartNormal) / num;
            return Math.Abs(num2) < this.StartRadius || Math.Abs(num3) < this.EndRadius;
        }
References System.Math.Abs(), Terraria.GameContent.Biomes.DungeonControlLine.CacheNormals(), ReLogic.Utilities.Vector2D.Cross(), Terraria.GameContent.Biomes.DungeonControlLine.EndNormal, Terraria.GameContent.Biomes.DungeonControlLine.EndRadius, Terraria.GameContent.Biomes.DungeonControlLine.Start, and Terraria.GameContent.Biomes.DungeonControlLine.StartNormal.
Referenced by Terraria.GameContent.Biomes.DungeonControlLine.AdjustTangentsToPreventSelfIntersection().