Terraria Decompiled: Terraria.GameContent.Biomes.DungeonControlLine.GetPotentialRoomPosition
GetPotentialRoomPosition()
Vector2D Terraria.GameContent.Biomes.DungeonControlLine.GetPotentialRoomPosition (double normalizedDistanceAlong, double normalizedOffset, int roomRadius) inline
Definition at line 245 of file DungeonControlLine.cs.
        {
            Vector2D vector2D = Vector2D.Lerp(this.StartNormal, this.EndNormal, normalizedDistanceAlong).SafeNormalize(default(Vector2D));
            double num = Utils.Lerp(this.StartRadius, this.EndRadius, normalizedDistanceAlong) * DungeonControlLine.NormalizedDistanceSafeFromDither - 4.0 - (double)roomRadius;
            return Vector2D.Lerp(this.Start, this.End, normalizedDistanceAlong) + vector2D * num * normalizedOffset;
        }
References Terraria.GameContent.Biomes.DungeonControlLine.End, Terraria.GameContent.Biomes.DungeonControlLine.EndNormal, Terraria.GameContent.Biomes.DungeonControlLine.EndRadius, Terraria.Utils.Lerp(), ReLogic.Utilities.Vector2D.Lerp(), Terraria.GameContent.Biomes.DungeonControlLine.Start, Terraria.GameContent.Biomes.DungeonControlLine.StartNormal, and Terraria.GameContent.Biomes.DungeonControlLine.StartRadius.
Referenced by Terraria.GameContent.Biomes.DitherSnake.GetRoomPositionInsideBorder().