Terraria Decompiled: Terraria.GameContent.Biomes.DungeonControlLine.Paint
Paint() [2/2]
void Terraria.GameContent.Biomes.DungeonControlLine.Paint (Rectangle dungeonBounds) inline
Definition at line 185 of file DungeonControlLine.cs.
        {
            this.CacheNormals();
            double num = Utils.Max<double>(new double[] { this.StartRadius, this.EndRadius });
            Point point = this.Start.ToPoint();
            Point point2 = this.End.ToPoint();
            Rectangle rectangle = Rectangle.Union(new Rectangle(point.X, point.Y, 1, 1), new Rectangle(point2.X, point2.Y, 1, 1));
            rectangle.Inflate((int)num, (int)num);
            Rectangle rectangle2 = Rectangle.Intersect(rectangle, dungeonBounds);
            for (int i = rectangle2.Left; i <= rectangle2.Right; i++)
            {
                for (int j = rectangle2.Top; j <= rectangle2.Bottom; j++)
                {
                    this.Paint(i, j);
                }
            }
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.GameContent.Biomes.DungeonControlLine.CacheNormals(), Terraria.GameContent.Biomes.DungeonControlLine.End, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Microsoft.Xna.Framework.Rectangle.Intersect(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.Biomes.DungeonControlLine.Paint(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.GameContent.Biomes.DungeonControlLine.Start, Terraria.GameContent.Biomes.DungeonControlLine.StartRadius, Microsoft.Xna.Framework.Rectangle.Top, Microsoft.Xna.Framework.Rectangle.Union(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.