Terraria Decompiled: Terraria.GameContent.Biomes.DungeonControlLine.CanPaint
CanPaint()
bool Terraria.GameContent.Biomes.DungeonControlLine.CanPaint (int x, int y, out double distance, out double normalizedLineProgress) inline
Definition at line 51 of file DungeonControlLine.cs.
        {
            distance = 0.0;
            normalizedLineProgress = 0.0;
            Vector2D vector2D;
            vector2D..ctor((double)x, (double)y);
            Vector2D vector2D2 = vector2D - this.Start;
            double num = Vector2D.Dot(vector2D2, this.StartTangent);
            if (num < 0.0)
            {
                if (this.Prev != null)
                {
                    return false;
                }
                normalizedLineProgress = 0.0;
                distance = vector2D2.Length();
                return true;
            }
            else
            {
                Vector2D vector2D3 = vector2D - this.End;
                double num2 = Vector2D.Dot(vector2D3, this.EndTangent);
                if (num2 >= 0.0)
                {
                    double num3 = Vector2D.Dot(vector2D2, this.StartNormal);
                    double num4 = Vector2D.Dot(vector2D3, this.EndNormal);
                    double num5 = (num + num2) / 2.0;
                    num *= num;
                    num2 *= num2;
                    double num6 = num / (num + num2);
                    double num7 = num3 * (1.0 - num6) + num4 * num6 - num5 * this.CrossTangent * num6 * (1.0 - num6);
                    distance = Math.Abs(num7);
                    normalizedLineProgress = num6;
                    return true;
                }
                if (this.Next != null)
                {
                    return false;
                }
                normalizedLineProgress = 1.0;
                distance = vector2D3.Length();
                return true;
            }
        }
References System.Math.Abs(), Terraria.GameContent.Biomes.DungeonControlLine.CrossTangent, ReLogic.Utilities.Vector2D.Dot(), Terraria.GameContent.Biomes.DungeonControlLine.End, Terraria.GameContent.Biomes.DungeonControlLine.EndNormal, Terraria.GameContent.Biomes.DungeonControlLine.EndTangent, ReLogic.Utilities.Vector2D.Length(), Terraria.GameContent.Biomes.DungeonControlLine.Next, Terraria.GameContent.Biomes.DungeonControlLine.Prev, Terraria.GameContent.Biomes.DungeonControlLine.Start, Terraria.GameContent.Biomes.DungeonControlLine.StartNormal, and Terraria.GameContent.Biomes.DungeonControlLine.StartTangent.
Referenced by Terraria.GameContent.Biomes.DitherSnake.GetPositionAlongSnake(), Terraria.GameContent.Biomes.DungeonControlLine.IsInsideBorder(), and Terraria.GameContent.Biomes.DungeonControlLine.Paint().