Terraria Decompiled: Mono.Security.Cryptography.MACAlgorithm.Core
Core()
void Mono.Security.Cryptography.MACAlgorithm.Core (byte[] rgb, int ib, int cb) inline
Definition at line 32 of file MACAlgorithm.cs.
        {
            int num = Math.Min(this.blockSize - this.blockCount, cb);
            Array.Copy(rgb, ib, this.block, this.blockCount, num);
            this.blockCount += num;
            if (this.blockCount == this.blockSize)
            {
                this.enc.TransformBlock(this.block, 0, this.blockSize, this.block, 0);
                int num2 = (cb - num) / this.blockSize;
                for (int i = 0; i < num2; i++)
                {
                    this.enc.TransformBlock(rgb, num, this.blockSize, this.block, 0);
                    num += this.blockSize;
                }
                this.blockCount = cb - num;
                if (this.blockCount > 0)
                {
                    Array.Copy(rgb, num, this.block, 0, this.blockCount);
                }
            }
        }
References Mono.Security.Cryptography.MACAlgorithm.block, Mono.Security.Cryptography.MACAlgorithm.blockCount, Mono.Security.Cryptography.MACAlgorithm.blockSize, System.Array.Copy(), Mono.Security.Cryptography.MACAlgorithm.enc, System.Math.Min(), and System.Security.Cryptography.ICryptoTransform.TransformBlock().