Terraria Decompiled: Mono.Security.Cryptography.HMACAlgorithm.Final
Final()
byte[] Mono.Security.Cryptography.HMACAlgorithm.Final () inline
Definition at line 116 of file HMACAlgorithm.cs.
        {
            this.block.Final();
            byte[] array = this.algo.Hash;
            byte[] array2 = this.KeySetup(this.key, 92);
            this.algo.Initialize();
            this.algo.TransformBlock(array2, 0, array2.Length, array2, 0);
            this.algo.TransformFinalBlock(array, 0, array.Length);
            this.hash = this.algo.Hash;
            this.algo.Clear();
            Array.Clear(array2, 0, array2.Length);
            Array.Clear(array, 0, array.Length);
            return this.hash;
        }
References Mono.Security.Cryptography.HMACAlgorithm.algo, System.array, Mono.Security.Cryptography.HMACAlgorithm.block, System.Array.Clear(), System.Security.Cryptography.HashAlgorithm.Clear(), Mono.Security.Cryptography.BlockProcessor.Final(), Mono.Security.Cryptography.HMACAlgorithm.hash, System.Security.Cryptography.HashAlgorithm.Hash, System.Security.Cryptography.HashAlgorithm.Initialize(), Mono.Security.Cryptography.HMACAlgorithm.key, Mono.Security.Cryptography.HMACAlgorithm.KeySetup(), System.Security.Cryptography.HashAlgorithm.TransformBlock(), and System.Security.Cryptography.HashAlgorithm.TransformFinalBlock().