Terraria Decompiled: Terraria.GameContent.UI.ItemRarity.Initialize
Initialize()
static void Terraria.GameContent.UI.ItemRarity.Initialize () inline static
Definition at line 12 of file ItemRarity.cs.
        {
            ItemRarity._rarities.Clear();
            ItemRarity._rarities.Add(-11, Colors.RarityAmber);
            ItemRarity._rarities.Add(-1, Colors.RarityTrash);
            ItemRarity._rarities.Add(1, Colors.RarityBlue);
            ItemRarity._rarities.Add(2, Colors.RarityGreen);
            ItemRarity._rarities.Add(3, Colors.RarityOrange);
            ItemRarity._rarities.Add(4, Colors.RarityRed);
            ItemRarity._rarities.Add(5, Colors.RarityPink);
            ItemRarity._rarities.Add(6, Colors.RarityPurple);
            ItemRarity._rarities.Add(7, Colors.RarityLime);
            ItemRarity._rarities.Add(8, Colors.RarityYellow);
            ItemRarity._rarities.Add(9, Colors.RarityCyan);
        }
References Terraria.GameContent.UI.ItemRarity._rarities, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.ID.Colors.RarityAmber, Terraria.ID.Colors.RarityBlue, Terraria.ID.Colors.RarityCyan, Terraria.ID.Colors.RarityGreen, Terraria.ID.Colors.RarityLime, Terraria.ID.Colors.RarityOrange, Terraria.ID.Colors.RarityPink, Terraria.ID.Colors.RarityPurple, Terraria.ID.Colors.RarityRed, Terraria.ID.Colors.RarityTrash, and Terraria.ID.Colors.RarityYellow.
Referenced by Terraria.Main.Initialize_AlmostEverything().