Terraria Decompiled: System.Threading.EventWaitHandle.OpenExistingWorker
OpenExistingWorker()
static WaitHandle.OpenExistingResult System.Threading.EventWaitHandle.OpenExistingWorker (string name, EventWaitHandleRights rights, out EventWaitHandle result) inline static private
Definition at line 149 of file EventWaitHandle.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name", Environment.GetResourceString("Parameter '{0}' cannot be null."));
            }
            if (name.Length == 0)
            {
                throw new ArgumentException(Environment.GetResourceString("Empty name is not legal."), "name");
            }
            if (name != null && 260 < name.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("The name can be no more than 260 characters in length.", new object[] { name }));
            }
            result = null;
            int num;
            SafeWaitHandle safeWaitHandle = new SafeWaitHandle(NativeEventCalls.OpenEvent_internal(name, rights, out num), true);
            if (safeWaitHandle.IsInvalid)
            {
                if (2 == num || 123 == num)
                {
                    return WaitHandle.OpenExistingResult.NameNotFound;
                }
                if (3 == num)
                {
                    return WaitHandle.OpenExistingResult.PathNotFound;
                }
                if (name != null && name.Length != 0 && 6 == num)
                {
                    return WaitHandle.OpenExistingResult.NameInvalid;
                }
                __Error.WinIOError(num, "");
            }
            result = new EventWaitHandle(safeWaitHandle);
            return WaitHandle.OpenExistingResult.Success;
        }
References System.Threading.EventWaitHandle.EventWaitHandle(), System.Environment.GetResourceString(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.name, System.Threading.NativeEventCalls.OpenEvent_internal(), System.Threading.WaitHandle.SafeWaitHandle, System.Threading.WaitHandle.safeWaitHandle, and System.IO.__Error.WinIOError().
Referenced by System.Threading.EventWaitHandle.OpenExisting(), System.Threading.EventWaitHandle.TryOpenExisting(), and System.Threading.EventWaitHandle.TryOpenExisting().