Terraria Decompiled: System.Threading.EventWaitHandle.Reset
Reset()
bool System.Threading.EventWaitHandle.Reset () inline
Definition at line 188 of file EventWaitHandle.cs.
        {
            bool flag = NativeEventCalls.ResetEvent(this.safeWaitHandle);
            if (!flag)
            {
                throw new IOException();
            }
            return flag;
        }
References System.Threading.NativeEventCalls.ResetEvent(), and System.Threading.WaitHandle.safeWaitHandle.
Referenced by System.Threading.ManualResetEventSlim.Reset(), System.Threading.Timer.Scheduler.SchedulerThread(), System.Threading.SemaphoreSlim.Wait(), System.Threading.SemaphoreSlim.WaitAsync(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.WaitOnEvent().