Terraria Decompiled: System.Threading.EventWaitHandle.EventWaitHandle
EventWaitHandle() [4/5]
System.Threading.EventWaitHandle.EventWaitHandle (bool initialState, EventResetMode mode, string name, out bool createdNew, EventWaitHandleSecurity eventSecurity) inline
Definition at line 66 of file EventWaitHandle.cs.
        {
            if (name != null && 260 < name.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("The name can be no more than 260 characters in length.", new object[] { name }));
            }
            bool flag;
            if (mode != EventResetMode.AutoReset)
            {
                if (mode != EventResetMode.ManualReset)
                {
                    throw new ArgumentException(Environment.GetResourceString("Value of flags is invalid.", new object[] { name }));
                }
                flag = true;
            }
            else
            {
                flag = false;
            }
            int num;
            SafeWaitHandle safeWaitHandle = new SafeWaitHandle(NativeEventCalls.CreateEvent_internal(flag, initialState, name, out num), true);
            if (safeWaitHandle.IsInvalid)
            {
                safeWaitHandle.SetHandleAsInvalid();
                if (name != null && name.Length != 0 && 6 == num)
                {
                    throw new WaitHandleCannotBeOpenedException(Environment.GetResourceString("A WaitHandle with system-wide name '{0}' cannot be created. A WaitHandle of a different type might have the same name.", new object[] { name }));
                }
                __Error.WinIOError(num, name);
            }
            createdNew = num != 183;
            base.SetHandleInternal(safeWaitHandle);
        }
References System.Threading.NativeEventCalls.CreateEvent_internal(), System.Environment.GetResourceString(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.mode, System.name, System.Threading.WaitHandle.SafeWaitHandle, System.Threading.WaitHandle.safeWaitHandle, System.Runtime.InteropServices.SafeHandle.SetHandleAsInvalid(), and System.IO.__Error.WinIOError().