Terraria Decompiled: System.Buffers.TlsOverPerCoreLockedStacksArrayPool.LockedStack.Trim
Trim()
void System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.LockedStack.Trim (uint tickCount, int id, TlsOverPerCoreLockedStacksArrayPool< T >::MemoryPressure pressure, int bucketSize) inline
Definition at line 386 of file TlsOverPerCoreLockedStacksArrayPool.cs.
            {
                if (this._count == 0)
                {
                    return;
                }
                uint num = ((pressure == TlsOverPerCoreLockedStacksArrayPool<T>.MemoryPressure.High) ? 10000U : 60000U);
                lock (this)
                {
                    if ((this._count > 0 && this._firstStackItemMS > tickCount) || tickCount - this._firstStackItemMS > num)
                    {
                        ArrayPoolEventSource log = ArrayPoolEventSource.Log;
                        int num2 = 1;
                        if (pressure != TlsOverPerCoreLockedStacksArrayPool<T>.MemoryPressure.Medium)
{
                            if (pressure == TlsOverPerCoreLockedStacksArrayPool<T>.MemoryPressure.High)
{
                                num2 = 8;
                                if (bucketSize > 16384)
{
                                    num2++;
                                }
                                if (Unsafe.SizeOf<T>() > 16)
{
                                    num2++;
                                }
                                if (Unsafe.SizeOf<T>() > 32)
{
                                    num2++;
                                }
                            }
                        }
                        else
{
                            num2 = 2;
                        }
                        while (this._count > 0 && num2-- > 0)
{
                            T[][] arrays = this._arrays;
                            int num3 = this._count - 1;
                            this._count = num3;
                            T[] array = arrays[num3];
                            this._arrays[this._count] = null;
                            if (log.IsEnabled())
{
                                log.BufferTrimmed(array.GetHashCode(), array.Length, id);
                            }
                        }
                        if (this._count > 0 && this._firstStackItemMS < 4294952295U)
{
                            this._firstStackItemMS += 15000U;
                        }
                    }
                }
            }
References System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.LockedStack._arrays, System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.LockedStack._count, System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.LockedStack._firstStackItemMS, System.array, System.Buffers.ArrayPoolEventSource.BufferTrimmed(), System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Buffers.ArrayPoolEventSource.Log, and System.U.
Referenced by System.Buffers.TlsOverPerCoreLockedStacksArrayPool< T >.PerCoreLockedStacks.Trim().