Terraria Decompiled: System.Security.Cryptography.SHA1Internal.HashCore
HashCore()
void System.Security.Cryptography.SHA1Internal.HashCore (byte[] rgb, int ibStart, int cbSize) inline
Definition at line 18 of file SHA1Internal.cs.
        {
            if (this._ProcessingBufferCount != 0)
            {
                if (cbSize < 64 - this._ProcessingBufferCount)
                {
                    Buffer.BlockCopy(rgb, ibStart, this._ProcessingBuffer, this._ProcessingBufferCount, cbSize);
                    this._ProcessingBufferCount += cbSize;
                    return;
                }
                int i = 64 - this._ProcessingBufferCount;
                Buffer.BlockCopy(rgb, ibStart, this._ProcessingBuffer, this._ProcessingBufferCount, i);
                this.ProcessBlock(this._ProcessingBuffer, 0U);
                this._ProcessingBufferCount = 0;
                ibStart += i;
                cbSize -= i;
            }
            for (int i = 0; i < cbSize - cbSize % 64; i += 64)
            {
                this.ProcessBlock(rgb, (uint)(ibStart + i));
            }
            if (cbSize % 64 != 0)
            {
                Buffer.BlockCopy(rgb, cbSize - cbSize % 64 + ibStart, this._ProcessingBuffer, 0, cbSize % 64);
                this._ProcessingBufferCount = cbSize % 64;
            }
        }
References System.Security.Cryptography.SHA1Internal._ProcessingBuffer, System.Security.Cryptography.SHA1Internal._ProcessingBufferCount, System.Buffer.BlockCopy(), System.Security.Cryptography.SHA1Internal.ProcessBlock(), and System.U.
Referenced by System.Security.Cryptography.SHA1CryptoServiceProvider.HashCore().