Terraria Decompiled: ReLogic.IO.ConsoleOutputMirror.ToFile
ToFile()
static void ReLogic.IO.ConsoleOutputMirror.ToFile (string path) inline static
Definition at line 12 of file ConsoleOutputMirror.cs.
        {
            if (ConsoleOutputMirror._instance != null)
            {
                ConsoleOutputMirror._instance.Dispose();
                ConsoleOutputMirror._instance = null;
            }
            try
            {
                ConsoleOutputMirror._instance = new ConsoleOutputMirror(path);
            }
            catch (Exception ex)
            {
                Console.WriteLine("Unable to bind console output to file: {0}\r\nException: {1}", path, ex);
            }
        }
References ReLogic.IO.ConsoleOutputMirror._instance, ReLogic.IO.ConsoleOutputMirror.ConsoleOutputMirror(), ReLogic.IO.ConsoleOutputMirror.Dispose(), and System.Console.WriteLine().
Referenced by Terraria.Program.SetupLogging().