Terraria Decompiled: ReLogic.IO.ConsoleOutputMirror.Dispose
Dispose() [2/2]
virtual void ReLogic.IO.ConsoleOutputMirror.Dispose (bool disposing) inline protected virtual
Definition at line 45 of file ConsoleOutputMirror.cs.
        {
            if (!this._disposedValue)
            {
                if (disposing)
                {
                    Console.SetOut(this._oldConsoleOutput);
                    if (this._fileWriter != null)
                    {
                        this._fileWriter.Flush();
                        this._fileWriter.Close();
                        this._fileWriter = null;
                    }
                    if (this._fileStream != null)
                    {
                        this._fileStream.Close();
                        this._fileStream = null;
                    }
                }
                this._disposedValue = true;
            }
        }
References ReLogic.IO.ConsoleOutputMirror._disposedValue, ReLogic.IO.ConsoleOutputMirror._fileStream, ReLogic.IO.ConsoleOutputMirror._fileWriter, ReLogic.IO.ConsoleOutputMirror._oldConsoleOutput, System.IO.Stream.Close(), System.IO.StreamWriter.Close(), System.IO.StreamWriter.Flush(), and System.Console.SetOut().
Referenced by ReLogic.IO.ConsoleOutputMirror.ToFile().