Terraria Decompiled: ReLogic.IO.ConsoleOutputMirror.ConsoleOutputMirror
ConsoleOutputMirror()
ReLogic.IO.ConsoleOutputMirror.ConsoleOutputMirror (string path) inline private
Definition at line 30 of file ConsoleOutputMirror.cs.
        {
            this._oldConsoleOutput = Console.Out;
            Directory.CreateDirectory(Directory.GetParent(path).FullName);
            this._fileStream = File.Create(path);
            this._fileWriter = new StreamWriter(this._fileStream)
            {
                AutoFlush = true
            };
            this._newConsoleOutput = new ConsoleOutputMirror.DoubleWriter(this._fileWriter, this._oldConsoleOutput);
            Console.SetOut(this._newConsoleOutput);
        }
References ReLogic.IO.ConsoleOutputMirror._fileStream, ReLogic.IO.ConsoleOutputMirror._fileWriter, ReLogic.IO.ConsoleOutputMirror._newConsoleOutput, ReLogic.IO.ConsoleOutputMirror._oldConsoleOutput, System.IO.File.Create(), System.IO.Directory.CreateDirectory(), System.IO.FileSystemInfo.FullName, System.IO.Directory.GetParent(), System.Console.Out, and System.Console.SetOut().
Referenced by ReLogic.IO.ConsoleOutputMirror.ToFile().