Terraria Decompiled: Mono.Security.Cryptography.KeyPairPersistence.ToXml
ToXml()
string Mono.Security.Cryptography.KeyPairPersistence.ToXml () inline private
Definition at line 379 of file KeyPairPersistence.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendFormat("<KeyPair>{0}\t<Properties>{0}\t\t<Provider ", Environment.NewLine);
            if (this._params.ProviderName != null && this._params.ProviderName.Length != 0)
            {
                stringBuilder.AppendFormat("Name=\"{0}\" ", this._params.ProviderName);
            }
            stringBuilder.AppendFormat("Type=\"{0}\" />{1}\t\t<Container ", this._params.ProviderType, Environment.NewLine);
            stringBuilder.AppendFormat("Name=\"{0}\" />{1}\t</Properties>{1}\t<KeyValue", this.ContainerName, Environment.NewLine);
            if (this._params.KeyNumber != -1)
            {
                stringBuilder.AppendFormat(" Id=\"{0}\" ", this._params.KeyNumber);
            }
            stringBuilder.AppendFormat(">{1}\t\t{0}{1}\t</KeyValue>{1}</KeyPair>{1}", this.KeyValue, Environment.NewLine);
            return stringBuilder.ToString();
        }
References Mono.Security.Cryptography.KeyPairPersistence._params, System.Text.StringBuilder.AppendFormat(), Mono.Security.Cryptography.KeyPairPersistence.ContainerName, System.Security.Cryptography.CspParameters.KeyNumber, Mono.Security.Cryptography.KeyPairPersistence.KeyValue, System.Security.Cryptography.CspParameters.ProviderName, System.Security.Cryptography.CspParameters.ProviderType, and System.Text.StringBuilder.ToString().
Referenced by Mono.Security.Cryptography.KeyPairPersistence.Save().