Terraria Decompiled: Mono.Security.Cryptography.KeyPairPersistence.FromXml
FromXml()
void Mono.Security.Cryptography.KeyPairPersistence.FromXml (string xml) inline private
Definition at line 363 of file KeyPairPersistence.cs.
        {
            SecurityParser securityParser = new SecurityParser();
            securityParser.LoadXml(xml);
            SecurityElement securityElement = securityParser.ToXml();
            if (securityElement.Tag == "KeyPair")
            {
                SecurityElement securityElement2 = securityElement.SearchForChildByTag("KeyValue");
                if (securityElement2.Children.Count > 0)
                {
                    this._keyvalue = securityElement2.Children[0].ToString();
                }
            }
        }
References System.Security.SecurityElement.Children, Mono.Xml.SecurityParser.LoadXml(), System.Security.SecurityElement.SearchForChildByTag(), System.Security.SecurityElement.Tag, and Mono.Xml.SecurityParser.ToXml().
Referenced by Mono.Security.Cryptography.KeyPairPersistence.Load().