Terraria Decompiled: Mono.Security.Cryptography.KeyPairPersistence.Load
Load()
bool Mono.Security.Cryptography.KeyPairPersistence.Load () inline
Definition at line 83 of file KeyPairPersistence.cs.
        {
            bool flag = File.Exists(this.Filename);
            if (flag)
            {
                using (StreamReader streamReader = File.OpenText(this.Filename))
                {
                    this.FromXml(streamReader.ReadToEnd());
                }
            }
            return flag;
        }
References System.IO.File.Exists(), Mono.Security.Cryptography.KeyPairPersistence.Filename, Mono.Security.Cryptography.KeyPairPersistence.FromXml(), System.IO.File.OpenText(), and System.IO.StreamReader.ReadToEnd().
Referenced by System.Security.Cryptography.RSACryptoServiceProvider.Common(), and System.Security.Cryptography.DSACryptoServiceProvider.Common().