Terraria Decompiled: System.BitConverter.ToString
ToString() [3/3]
static unsafe string System.BitConverter.ToString (byte[] value, int startIndex, int length) inline static
Definition at line 392 of file BitConverter.cs.
        {
            if (value == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.value);
            }
            if (startIndex < 0 || (startIndex >= value.Length && startIndex > 0))
            {
                ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument.startIndex, ExceptionResource.ArgumentOutOfRange_Index);
            }
            if (length < 0)
            {
                throw new ArgumentOutOfRangeException("length", "Value must be positive.");
            }
            if (startIndex > value.Length - length)
            {
                ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall, ExceptionArgument.value);
            }
            if (length == 0)
            {
                return string.Empty;
            }
            if (length > 715827882)
            {
                throw new ArgumentOutOfRangeException("length", SR.Format("The specified length exceeds the maximum value of {0}.", 715827882));
            }
            return string.Create<ValueTuple<byte[], int, int>>(length * 3 - 1, new ValueTuple<byte[], int, int>(value, startIndex, length), delegate(Span<char> dst, [TupleElementNames(new string[] { "value", "startIndex", "length" })] ValueTuple<byte[], int, int> state)
            {
                ReadOnlySpan<byte> readOnlySpan = new ReadOnlySpan<byte>(state.Item1, state.Item2, state.Item3);
                int i = 0;
                int num = 0;
                byte b = *readOnlySpan[i++];
                *dst[num++] = "0123456789ABCDEF"[b >> 4];
                *dst[num++] = "0123456789ABCDEF"[(int)(b & 15)];
                while (i < readOnlySpan.Length)
                {
                    b = *readOnlySpan[i++];
                    *dst[num++] = '-';
                    *dst[num++] = "0123456789ABCDEF"[b >> 4];
                    *dst[num++] = "0123456789ABCDEF"[(int)(b & 15)];
                }
            });
        }
References SR.Format(), int, System.length, System.ReadOnlySpan< T >.Length, System.startIndex, System.state, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), and System.value.
Referenced by System.BitConverter.ToString(), and System.BitConverter.ToString().