Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting
TryFitting()
bool Terraria.GameContent.Tile_Entities.TEHatRack.TryFitting (Item[] inv, int slot) inline private
Definition at line 344 of file TEHatRack.cs.
        {
            Item item = inv[slot];
            int num = -1;
            for (int i = 0; i < this._items.Length; i++)
            {
                if (this._items[i].IsAir)
                {
                    num = i;
                    TEHatRack.hatTargetSlot = i;
                    break;
                }
            }
            if (num == -1)
            {
                num = TEHatRack.hatTargetSlot;
            }
            if (item.stack > 1 && !this._items[num].IsAir)
            {
                return true;
            }
            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
            if (item.stack > 1)
            {
                this._items[num] = item.Clone();
                this._items[num].stack = 1;
                item.stack--;
            }
            else
            {
                Utils.Swap<Item>(ref this._items[num], ref inv[slot]);
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(124, -1, -1, null, Main.myPlayer, (float)this.ID, (float)num, 0f, 0, 0, 0);
            }
            TEHatRack.hatTargetSlot++;
            if (TEHatRack.hatTargetSlot >= this._items.Length)
            {
                TEHatRack.hatTargetSlot = 0;
            }
            return true;
        }
References Terraria.GameContent.Tile_Entities.TEHatRack._items, Terraria.Item.Clone(), Terraria.GameContent.Tile_Entities.TEHatRack.hatTargetSlot, System.item, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), and Terraria.Item.stack.
Referenced by Terraria.GameContent.Tile_Entities.TEHatRack.PerformShiftClickAction().