Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerInteraction
OnPlayerInteraction()
static void Terraria.GameContent.Tile_Entities.TEHatRack.OnPlayerInteraction (Player player, int clickX, int clickY) inline static
Definition at line 236 of file TEHatRack.cs.
        {
            int num = clickX - (int)(Main.tile[clickX, clickY].frameX % 54 / 18);
            int num2 = clickY - (int)(Main.tile[num, clickY].frameY / 18);
            int num3 = TileEntityType<TEHatRack>.Find(num, num2);
            if (num3 != -1)
            {
                num2++;
                num++;
                TEHatRack.hatTargetSlot = 0;
                TileEntity.BasicOpenCloseInteraction(player, num, num2, num3);
            }
        }
References Terraria.DataStructures.TileEntity.BasicOpenCloseInteraction(), Terraria.DataStructures.TileEntityType< T >.Find(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, and Terraria.Main.tile.
Referenced by Terraria.Player.TileInteractionsUse().