Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEHatRack.Draw
Draw()
void Terraria.GameContent.Tile_Entities.TEHatRack.Draw (int tileLeftX, int tileTopY) inline
Definition at line 167 of file TEHatRack.cs.
        {
            Player dollPlayer = this._dollPlayer;
            dollPlayer.direction = -1;
            dollPlayer.Male = true;
            if (Framing.GetTileSafely(tileLeftX, tileTopY).frameX % 216 == 54)
            {
                dollPlayer.direction = 1;
            }
            dollPlayer.isDisplayDollOrInanimate = true;
            dollPlayer.isHatRackDoll = true;
            dollPlayer.armor[0] = this._items[0];
            dollPlayer.dye[0] = this._dyes[0];
            dollPlayer.ResetEffects();
            dollPlayer.ResetVisibleAccessories();
            dollPlayer.invis = true;
            dollPlayer.UpdateDyes();
            dollPlayer.DisplayDollUpdate();
            dollPlayer.PlayerFrame();
            Vector2 vector = new Vector2((float)tileLeftX + 1.5f, (float)(tileTopY + 4)) * 16f;
            dollPlayer.direction *= -1;
            Vector2 vector2 = new Vector2((float)(-(float)dollPlayer.width / 2), (float)(-(float)dollPlayer.height - 6)) + new Vector2((float)(dollPlayer.direction * 14), -2f);
            dollPlayer.position = vector + vector2;
            Main.PlayerRenderer.DrawPlayer(Main.Camera, dollPlayer, dollPlayer.position, 0f, dollPlayer.fullRotationOrigin, 0f, 1f);
            dollPlayer.armor[0] = this._items[1];
            dollPlayer.dye[0] = this._dyes[1];
            dollPlayer.ResetEffects();
            dollPlayer.ResetVisibleAccessories();
            dollPlayer.invis = true;
            dollPlayer.UpdateDyes();
            dollPlayer.DisplayDollUpdate();
            dollPlayer.skipAnimatingValuesInPlayerFrame = true;
            dollPlayer.PlayerFrame();
            dollPlayer.skipAnimatingValuesInPlayerFrame = false;
            dollPlayer.direction *= -1;
            vector2 = new Vector2((float)(-(float)dollPlayer.width / 2), (float)(-(float)dollPlayer.height - 6)) + new Vector2((float)(dollPlayer.direction * 12), 16f);
            dollPlayer.position = vector + vector2;
            Main.PlayerRenderer.DrawPlayer(Main.Camera, dollPlayer, dollPlayer.position, 0f, dollPlayer.fullRotationOrigin, 0f, 1f);
        }
References Terraria.GameContent.Tile_Entities.TEHatRack._dollPlayer, Terraria.GameContent.Tile_Entities.TEHatRack._dyes, Terraria.GameContent.Tile_Entities.TEHatRack._items, Terraria.Player.armor, Terraria.Main.Camera, Terraria.Entity.direction, Terraria.Player.DisplayDollUpdate(), Terraria.Player.dye, Terraria.Tile.frameX, Terraria.Player.fullRotationOrigin, Terraria.Framing.GetTileSafely(), Terraria.Entity.height, Terraria.Player.PlayerFrame(), Terraria.Main.PlayerRenderer, Terraria.Entity.position, Terraria.Player.ResetEffects(), Terraria.Player.ResetVisibleAccessories(), Terraria.Player.UpdateDyes(), Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Entity.width.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks().