Terraria Decompiled: Mono.Security.ASN1.Decode
Decode()
void Mono.Security.ASN1.Decode (byte[] asn1, ref int anPos, int anLength) inline protected
Definition at line 252 of file ASN1.cs.
        {
            while (anPos < anLength - 1)
            {
                byte b;
                int num;
                byte[] array;
                this.DecodeTLV(asn1, ref anPos, out b, out num, out array);
                if (b != 0)
                {
                    ASN1 asn2 = this.Add(new ASN1(b, array));
                    if ((b & 32) == 32)
                    {
                        int num2 = anPos;
                        asn2.Decode(asn1, ref num2, num2 + num);
                    }
                    anPos += num;
                }
            }
        }
References System.Add, System.array, Mono.Security.ASN1.ASN1(), Mono.Security.ASN1.Decode(), and Mono.Security.ASN1.DecodeTLV().
Referenced by Mono.Security.ASN1.ASN1(), and Mono.Security.ASN1.Decode().