Terraria Decompiled: Mono.Security.ASN1.ToString
ToString()
override string Mono.Security.ASN1.ToString () inline
Definition at line 354 of file ASN1.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendFormat("Tag: {0} {1}", this.m_nTag.ToString("X2"), Environment.NewLine);
            stringBuilder.AppendFormat("Length: {0} {1}", this.Value.Length, Environment.NewLine);
            stringBuilder.Append("Value: ");
            stringBuilder.Append(Environment.NewLine);
            for (int i = 0; i < this.Value.Length; i++)
            {
                stringBuilder.AppendFormat("{0} ", this.Value[i].ToString("X2"));
                if ((i + 1) % 16 == 0)
                {
                    stringBuilder.AppendFormat(Environment.NewLine, Array.Empty<object>());
                }
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendFormat(), Mono.Security.ASN1.m_nTag, Mono.Security.ASN1.ToString(), System.Text.StringBuilder.ToString(), and Mono.Security.ASN1.Value.
Referenced by Mono.Security.ASN1.ToString().