Terraria Decompiled: Mono.Security.ASN1.GetBytes
GetBytes()
virtual byte[] Mono.Security.ASN1.GetBytes () inline virtual
Definition at line 163 of file ASN1.cs.
        {
            byte[] array = null;
            if (this.Count > 0)
            {
                int num = 0;
                ArrayList arrayList = new ArrayList();
                foreach (object obj in this.elist)
                {
                    byte[] bytes = ((ASN1)obj).GetBytes();
                    arrayList.Add(bytes);
                    num += bytes.Length;
                }
                array = new byte[num];
                int num2 = 0;
                for (int i = 0; i < this.elist.Count; i++)
                {
                    byte[] array2 = (byte[])arrayList[i];
                    Buffer.BlockCopy(array2, 0, array, num2, array2.Length);
                    num2 += array2.Length;
                }
            }
            else if (this.m_aValue != null)
            {
                array = this.m_aValue;
            }
            int num3 = 0;
            byte[] array3;
            if (array != null)
            {
                int num4 = array.Length;
                if (num4 > 127)
                {
                    if (num4 <= 255)
                    {
                        array3 = new byte[3 + num4];
                        Buffer.BlockCopy(array, 0, array3, 3, num4);
                        num3 = 129;
                        array3[2] = (byte)num4;
                    }
                    else if (num4 <= 65535)
                    {
                        array3 = new byte[4 + num4];
                        Buffer.BlockCopy(array, 0, array3, 4, num4);
                        num3 = 130;
                        array3[2] = (byte)(num4 >> 8);
                        array3[3] = (byte)num4;
                    }
                    else if (num4 <= 16777215)
                    {
                        array3 = new byte[5 + num4];
                        Buffer.BlockCopy(array, 0, array3, 5, num4);
                        num3 = 131;
                        array3[2] = (byte)(num4 >> 16);
                        array3[3] = (byte)(num4 >> 8);
                        array3[4] = (byte)num4;
                    }
                    else
                    {
                        array3 = new byte[6 + num4];
                        Buffer.BlockCopy(array, 0, array3, 6, num4);
                        num3 = 132;
                        array3[2] = (byte)(num4 >> 24);
                        array3[3] = (byte)(num4 >> 16);
                        array3[4] = (byte)(num4 >> 8);
                        array3[5] = (byte)num4;
                    }
                }
                else
                {
                    array3 = new byte[2 + num4];
                    Buffer.BlockCopy(array, 0, array3, 2, num4);
                    num3 = num4;
                }
                if (this.m_aValue == null)
                {
                    this.m_aValue = array;
                }
            }
            else
            {
                array3 = new byte[2];
            }
            array3[0] = this.m_nTag;
            array3[1] = (byte)num3;
            return array3;
        }
References System.array, Mono.Security.ASN1.ASN1(), System.Buffer.BlockCopy(), Mono.Security.ASN1.Count, Mono.Security.ASN1.elist, Mono.Security.ASN1.m_aValue, Mono.Security.ASN1.m_nTag, and System.obj.
Referenced by Mono.Security.Cryptography.PKCS1.Encode_v15(), Mono.Security.ASN1.Equals(), and Mono.Security.ASN1.SaveToFile().