Terraria Decompiled: Mono.Security.ASN1.SaveToFile
SaveToFile()
void Mono.Security.ASN1.SaveToFile (string filename) inline
Definition at line 373 of file ASN1.cs.
        {
            if (filename == null)
            {
                throw new ArgumentNullException("filename");
            }
            using (FileStream fileStream = File.Create(filename))
            {
                byte[] bytes = this.GetBytes();
                fileStream.Write(bytes, 0, bytes.Length);
            }
        }
References System.IO.File.Create(), Mono.Security.ASN1.GetBytes(), and System.IO.FileStream.Write().