Terraria Decompiled: Terraria.Framing.SelfFrame8Way
SelfFrame8Way()
static void Terraria.Framing.SelfFrame8Way (int i, int j, Tile centerTile, bool resetFrame) inline static
Definition at line 167 of file Framing.cs.
        {
            if (!centerTile.active())
            {
                return;
            }
            Framing.BlockStyle blockStyle = Framing.FindBlockStyle(centerTile);
            int num = 0;
            Framing.BlockStyle blockStyle2 = default(Framing.BlockStyle);
            if (blockStyle.top)
            {
                Tile tileSafely = Framing.GetTileSafely(i, j - 1);
                if (tileSafely.active() && Framing.WillItBlend(centerTile.type, tileSafely.type))
                {
                    blockStyle2 = Framing.FindBlockStyle(tileSafely);
                    if (blockStyle2.bottom)
                    {
                        num |= 1;
                    }
                    else
                    {
                        blockStyle2.Clear();
                    }
                }
            }
            Framing.BlockStyle blockStyle3 = default(Framing.BlockStyle);
            if (blockStyle.left)
            {
                Tile tileSafely2 = Framing.GetTileSafely(i - 1, j);
                if (tileSafely2.active() && Framing.WillItBlend(centerTile.type, tileSafely2.type))
                {
                    blockStyle3 = Framing.FindBlockStyle(tileSafely2);
                    if (blockStyle3.right)
                    {
                        num |= 2;
                    }
                    else
                    {
                        blockStyle3.Clear();
                    }
                }
            }
            Framing.BlockStyle blockStyle4 = default(Framing.BlockStyle);
            if (blockStyle.right)
            {
                Tile tileSafely3 = Framing.GetTileSafely(i + 1, j);
                if (tileSafely3.active() && Framing.WillItBlend(centerTile.type, tileSafely3.type))
                {
                    blockStyle4 = Framing.FindBlockStyle(tileSafely3);
                    if (blockStyle4.left)
                    {
                        num |= 4;
                    }
                    else
                    {
                        blockStyle4.Clear();
                    }
                }
            }
            Framing.BlockStyle blockStyle5 = default(Framing.BlockStyle);
            if (blockStyle.bottom)
            {
                Tile tileSafely4 = Framing.GetTileSafely(i, j + 1);
                if (tileSafely4.active() && Framing.WillItBlend(centerTile.type, tileSafely4.type))
                {
                    blockStyle5 = Framing.FindBlockStyle(tileSafely4);
                    if (blockStyle5.top)
                    {
                        num |= 8;
                    }
                    else
                    {
                        blockStyle5.Clear();
                    }
                }
            }
            if (blockStyle2.left && blockStyle3.top)
            {
                Tile tileSafely5 = Framing.GetTileSafely(i - 1, j - 1);
                if (tileSafely5.active() && Framing.WillItBlend(centerTile.type, tileSafely5.type))
                {
                    Framing.BlockStyle blockStyle6 = Framing.FindBlockStyle(tileSafely5);
                    if (blockStyle6.right && blockStyle6.bottom)
                    {
                        num |= 16;
                    }
                }
            }
            if (blockStyle2.right && blockStyle4.top)
            {
                Tile tileSafely6 = Framing.GetTileSafely(i + 1, j - 1);
                if (tileSafely6.active() && Framing.WillItBlend(centerTile.type, tileSafely6.type))
                {
                    Framing.BlockStyle blockStyle7 = Framing.FindBlockStyle(tileSafely6);
                    if (blockStyle7.left && blockStyle7.bottom)
                    {
                        num |= 32;
                    }
                }
            }
            if (blockStyle5.left && blockStyle3.bottom)
            {
                Tile tileSafely7 = Framing.GetTileSafely(i - 1, j + 1);
                if (tileSafely7.active() && Framing.WillItBlend(centerTile.type, tileSafely7.type))
                {
                    Framing.BlockStyle blockStyle8 = Framing.FindBlockStyle(tileSafely7);
                    if (blockStyle8.right && blockStyle8.top)
                    {
                        num |= 64;
                    }
                }
            }
            if (blockStyle5.right && blockStyle4.bottom)
            {
                Tile tileSafely8 = Framing.GetTileSafely(i + 1, j + 1);
                if (tileSafely8.active() && Framing.WillItBlend(centerTile.type, tileSafely8.type))
                {
                    Framing.BlockStyle blockStyle9 = Framing.FindBlockStyle(tileSafely8);
                    if (blockStyle9.left && blockStyle9.top)
                    {
                        num |= 128;
                    }
                }
            }
            if (resetFrame)
            {
                centerTile.frameNumber((byte)WorldGen.genRand.Next(0, 3));
            }
            Point16 point = Framing.selfFrame8WayLookup[num][(int)centerTile.frameNumber()];
            centerTile.frameX = point.X;
            centerTile.frameY = point.Y;
        }
References Terraria.Tile.active(), Terraria.Framing.BlockStyle.bottom, Terraria.Framing.BlockStyle.Clear(), Terraria.Framing.FindBlockStyle(), Terraria.Tile.frameNumber(), Terraria.WorldGen.genRand, Terraria.Framing.GetTileSafely(), int, Terraria.Framing.BlockStyle.left, Terraria.Framing.BlockStyle.right, Terraria.Framing.selfFrame8WayLookup, Terraria.Framing.BlockStyle.top, Terraria.Tile.type, Terraria.Framing.WillItBlend(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.WorldGen.TileFrameCosmetic().