Terraria Decompiled: Terraria.Framing.Initialize
Initialize()
static void Terraria.Framing.Initialize () inline static
Definition at line 12 of file Framing.cs.
        {
            Framing.selfFrame8WayLookup = new Point16[256][];
            Framing.frameSize8Way = new Point16(18, 18);
            Framing.Add8WayLookup(0, 9, 3, 10, 3, 11, 3);
            Framing.Add8WayLookup(1, 6, 3, 7, 3, 8, 3);
            Framing.Add8WayLookup(2, 12, 0, 12, 1, 12, 2);
            Framing.Add8WayLookup(3, 15, 2);
            Framing.Add8WayLookup(4, 9, 0, 9, 1, 9, 2);
            Framing.Add8WayLookup(5, 13, 2);
            Framing.Add8WayLookup(6, 6, 4, 7, 4, 8, 4);
            Framing.Add8WayLookup(7, 14, 2);
            Framing.Add8WayLookup(8, 6, 0, 7, 0, 8, 0);
            Framing.Add8WayLookup(9, 5, 0, 5, 1, 5, 2);
            Framing.Add8WayLookup(10, 15, 0);
            Framing.Add8WayLookup(11, 15, 1);
            Framing.Add8WayLookup(12, 13, 0);
            Framing.Add8WayLookup(13, 13, 1);
            Framing.Add8WayLookup(14, 14, 0);
            Framing.Add8WayLookup(15, 14, 1);
            Framing.Add8WayLookup(19, 1, 4, 3, 4, 5, 4);
            Framing.Add8WayLookup(23, 16, 3);
            Framing.Add8WayLookup(27, 17, 0);
            Framing.Add8WayLookup(31, 13, 4);
            Framing.Add8WayLookup(37, 0, 4, 2, 4, 4, 4);
            Framing.Add8WayLookup(39, 17, 3);
            Framing.Add8WayLookup(45, 16, 0);
            Framing.Add8WayLookup(47, 12, 4);
            Framing.Add8WayLookup(55, 1, 2, 2, 2, 3, 2);
            Framing.Add8WayLookup(63, 6, 2, 7, 2, 8, 2);
            Framing.Add8WayLookup(74, 1, 3, 3, 3, 5, 3);
            Framing.Add8WayLookup(75, 17, 1);
            Framing.Add8WayLookup(78, 16, 2);
            Framing.Add8WayLookup(79, 13, 3);
            Framing.Add8WayLookup(91, 4, 0, 4, 1, 4, 2);
            Framing.Add8WayLookup(95, 11, 0, 11, 1, 11, 2);
            Framing.Add8WayLookup(111, 17, 4);
            Framing.Add8WayLookup(127, 14, 3);
            Framing.Add8WayLookup(140, 0, 3, 2, 3, 4, 3);
            Framing.Add8WayLookup(141, 16, 1);
            Framing.Add8WayLookup(142, 17, 2);
            Framing.Add8WayLookup(143, 12, 3);
            Framing.Add8WayLookup(159, 16, 4);
            Framing.Add8WayLookup(173, 0, 0, 0, 1, 0, 2);
            Framing.Add8WayLookup(175, 10, 0, 10, 1, 10, 2);
            Framing.Add8WayLookup(191, 15, 3);
            Framing.Add8WayLookup(206, 1, 0, 2, 0, 3, 0);
            Framing.Add8WayLookup(207, 6, 1, 7, 1, 8, 1);
            Framing.Add8WayLookup(223, 14, 4);
            Framing.Add8WayLookup(239, 15, 4);
            Framing.Add8WayLookup(255, 1, 1, 2, 1, 3, 1);
            Framing.blockStyleLookup = new Framing.BlockStyle[6];
            Framing.blockStyleLookup[0] = new Framing.BlockStyle(true, true, true, true);
            Framing.blockStyleLookup[1] = new Framing.BlockStyle(false, true, true, true);
            Framing.blockStyleLookup[2] = new Framing.BlockStyle(false, true, true, false);
            Framing.blockStyleLookup[3] = new Framing.BlockStyle(false, true, false, true);
            Framing.blockStyleLookup[4] = new Framing.BlockStyle(true, false, true, false);
            Framing.blockStyleLookup[5] = new Framing.BlockStyle(true, false, false, true);
            Framing.phlebasTileFrameNumberLookup = new int[][]
            {
                new int[] { 2, 4, 2 },
                new int[] { 1, 3, 1 },
                new int[] { 2, 2, 4 },
                new int[] { 1, 1, 3 }
            };
            Framing.lazureTileFrameNumberLookup = new int[][]
            {
                new int[] { 1, 3 },
                new int[] { 2, 4 }
            };
            int[][] array = new int[3][];
            int num = 0;
            int[] array2 = new int[3];
            array2[0] = 2;
            array[num] = array2;
            array[1] = new int[] { 0, 1, 4 };
            int num2 = 2;
            int[] array3 = new int[3];
            array3[1] = 3;
            array[num2] = array3;
            Framing.centerWallFrameLookup = array;
            Framing.wallFrameLookup = new Point16[20][];
            Framing.wallFrameSize = new Point16(36, 36);
            Framing.AddWallFrameLookup(0, 9, 3, 10, 3, 11, 3, 6, 6);
            Framing.AddWallFrameLookup(1, 6, 3, 7, 3, 8, 3, 4, 6);
            Framing.AddWallFrameLookup(2, 12, 0, 12, 1, 12, 2, 12, 5);
            Framing.AddWallFrameLookup(3, 1, 4, 3, 4, 5, 4, 3, 6);
            Framing.AddWallFrameLookup(4, 9, 0, 9, 1, 9, 2, 9, 5);
            Framing.AddWallFrameLookup(5, 0, 4, 2, 4, 4, 4, 2, 6);
            Framing.AddWallFrameLookup(6, 6, 4, 7, 4, 8, 4, 5, 6);
            Framing.AddWallFrameLookup(7, 1, 2, 2, 2, 3, 2, 3, 5);
            Framing.AddWallFrameLookup(8, 6, 0, 7, 0, 8, 0, 6, 5);
            Framing.AddWallFrameLookup(9, 5, 0, 5, 1, 5, 2, 5, 5);
            Framing.AddWallFrameLookup(10, 1, 3, 3, 3, 5, 3, 1, 6);
            Framing.AddWallFrameLookup(11, 4, 0, 4, 1, 4, 2, 4, 5);
            Framing.AddWallFrameLookup(12, 0, 3, 2, 3, 4, 3, 0, 6);
            Framing.AddWallFrameLookup(13, 0, 0, 0, 1, 0, 2, 0, 5);
            Framing.AddWallFrameLookup(14, 1, 0, 2, 0, 3, 0, 1, 5);
            Framing.AddWallFrameLookup(15, 1, 1, 2, 1, 3, 1, 2, 5);
            Framing.AddWallFrameLookup(16, 6, 1, 7, 1, 8, 1, 7, 5);
            Framing.AddWallFrameLookup(17, 6, 2, 7, 2, 8, 2, 8, 5);
            Framing.AddWallFrameLookup(18, 10, 0, 10, 1, 10, 2, 10, 5);
            Framing.AddWallFrameLookup(19, 11, 0, 11, 1, 11, 2, 11, 5);
        }
References Terraria.Framing.Add8WayLookup(), Terraria.Framing.AddWallFrameLookup(), System.array, and Terraria.Framing.blockStyleLookup.
Referenced by Terraria.Main.Initialize_AlmostEverything().