Terraria Decompiled: Terraria.Framing.GetTileSafely
GetTileSafely() [4/4]
static Tile Terraria.Framing.GetTileSafely (Vector2 position) inline static
Definition at line 386 of file Framing.cs.
        {
            position /= 16f;
            return Framing.GetTileSafely((int)position.X, (int)position.Y);
        }
References Terraria.Framing.GetTileSafely(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_FreakingPirates_HitIntention(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_149_GolfBall(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.GameContent.MinecartDiggerHelper.AlreadyLeadsIntoWantedTrack(), Terraria.SceneMetrics.CalculateZones(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.CanPlaceSink(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.CheckAnchor(), Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Events.CultistRitual.CheckFloor2(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckLilyPad(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldGen.CheckOasisPlant(), Terraria.WorldGen.CheckStinkbugBlocker(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTileAnchors(), Terraria.WorldGen.CheckTileFrames(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.GameContent.MinecartDiggerHelper.CorrectTrackConnections(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.Player.DamageTileWithShovel(), Terraria.GameContent.LeashedEntities.LeashedCritter.Draw(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.GameContent.Tile_Entities.TEHatRack.Draw(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawInfoAccs(), Terraria.TileObject.DrawPreview(), Terraria.Mount.EmitGolfCartWheelDust(), Terraria.NPC.FindFrame(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.GetDrawOffset(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.GetDrawOffset(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.GetDrawOffset(), Terraria.GameContent.LeashedEntities.WaterStriderLeashedCritter.GetDrawOffset(), Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo(), Terraria.GameContent.PlayerSleepingHelper.GetSleepingTargetInfo(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.Framing.GetTileSafely(), Terraria.Framing.GetTileSafely(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.GetTopLeftAndStyles(), Terraria.WorldGen.GetTreeBottom(), Terraria.WorldGen.GetVineTop(), Terraria.Collision.GetWaterLineIterate(), Terraria.GameContent.TeleportPylonsSystem.HandleTeleportRequest(), Terraria.WorldGen.IsTileALeafyTreeTop(), Terraria.Chest.Lock(), Terraria.Player.MowTheLawn(), Terraria.Chest.NearOtherChests(), Terraria.NPC.NPCCanStickToWalls(), Terraria.WorldGen.OpenDoor(), Terraria.TileObject.Place(), Terraria.WorldGen.Place2x2(), Terraria.Player.PlaceThing_LockChest(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.Player.QuickGrapple(), Terraria.Player.QuickMinecart(), Terraria.Player.QuickMinecartSnap(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyleBasedOnWorldPosition(), Terraria.WorldGen.ReplaceTile(), Terraria.Framing.SelfFrame8Way(), Terraria.WorldGen.ShiftTallGate(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.GameContent.Events.DD2Event.SummonCrystalDirect(), Terraria.Player.TileInteractionsUse(), Terraria.WorldGen.ToggleGemLock(), Terraria.GameContent.MinecartDiggerHelper.TryDigging(), Terraria.Minecart.TryFittingTileOrientation(), Terraria.GameContent.PlayerSittingHelper.TryGetSittingBlock(), Terraria.Player.TryLandingOnDetonator(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Player.TryUsingDiggerCart(), Terraria.Chest.Unlock(), Terraria.Map.WorldMap.UnlockMapTilePretty(), Terraria.Player.UpdateBiomes(), Terraria.Player.UpdateBlacklistedTilesForGrappling(), Terraria.Dust.UpdateDust(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().