Terraria Decompiled: Steamworks.CSteamAPIContext.Init
Init()
static bool Steamworks.CSteamAPIContext.Init () inline static package
Definition at line 43 of file CSteamAPIContext.cs.
        {
            HSteamUser hsteamUser = SteamAPI.GetHSteamUser();
            HSteamPipe hsteamPipe = SteamAPI.GetHSteamPipe();
            if (hsteamPipe == (HSteamPipe)0)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle("SteamClient021"))
            {
                CSteamAPIContext.m_pSteamClient = NativeMethods.SteamInternal_CreateInterface(utf8StringHandle);
            }
            if (CSteamAPIContext.m_pSteamClient == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamUser = SteamClient.GetISteamUser(hsteamUser, hsteamPipe, "SteamUser023");
            if (CSteamAPIContext.m_pSteamUser == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamFriends = SteamClient.GetISteamFriends(hsteamUser, hsteamPipe, "SteamFriends017");
            if (CSteamAPIContext.m_pSteamFriends == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamUtils = SteamClient.GetISteamUtils(hsteamPipe, "SteamUtils010");
            if (CSteamAPIContext.m_pSteamUtils == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamMatchmaking = SteamClient.GetISteamMatchmaking(hsteamUser, hsteamPipe, "SteamMatchMaking009");
            if (CSteamAPIContext.m_pSteamMatchmaking == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamMatchmakingServers = SteamClient.GetISteamMatchmakingServers(hsteamUser, hsteamPipe, "SteamMatchMakingServers002");
            if (CSteamAPIContext.m_pSteamMatchmakingServers == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamUserStats = SteamClient.GetISteamUserStats(hsteamUser, hsteamPipe, "STEAMUSERSTATS_INTERFACE_VERSION012");
            if (CSteamAPIContext.m_pSteamUserStats == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamApps = SteamClient.GetISteamApps(hsteamUser, hsteamPipe, "STEAMAPPS_INTERFACE_VERSION008");
            if (CSteamAPIContext.m_pSteamApps == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamNetworking = SteamClient.GetISteamNetworking(hsteamUser, hsteamPipe, "SteamNetworking006");
            if (CSteamAPIContext.m_pSteamNetworking == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamRemoteStorage = SteamClient.GetISteamRemoteStorage(hsteamUser, hsteamPipe, "STEAMREMOTESTORAGE_INTERFACE_VERSION016");
            if (CSteamAPIContext.m_pSteamRemoteStorage == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamScreenshots = SteamClient.GetISteamScreenshots(hsteamUser, hsteamPipe, "STEAMSCREENSHOTS_INTERFACE_VERSION003");
            if (CSteamAPIContext.m_pSteamScreenshots == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamGameSearch = SteamClient.GetISteamGameSearch(hsteamUser, hsteamPipe, "SteamMatchGameSearch001");
            if (CSteamAPIContext.m_pSteamGameSearch == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamHTTP = SteamClient.GetISteamHTTP(hsteamUser, hsteamPipe, "STEAMHTTP_INTERFACE_VERSION003");
            if (CSteamAPIContext.m_pSteamHTTP == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamUGC = SteamClient.GetISteamUGC(hsteamUser, hsteamPipe, "STEAMUGC_INTERFACE_VERSION020");
            if (CSteamAPIContext.m_pSteamUGC == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamMusic = SteamClient.GetISteamMusic(hsteamUser, hsteamPipe, "STEAMMUSIC_INTERFACE_VERSION001");
            if (CSteamAPIContext.m_pSteamMusic == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamMusicRemote = SteamClient.GetISteamMusicRemote(hsteamUser, hsteamPipe, "STEAMMUSICREMOTE_INTERFACE_VERSION001");
            if (CSteamAPIContext.m_pSteamMusicRemote == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamHTMLSurface = SteamClient.GetISteamHTMLSurface(hsteamUser, hsteamPipe, "STEAMHTMLSURFACE_INTERFACE_VERSION_005");
            if (CSteamAPIContext.m_pSteamHTMLSurface == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamInventory = SteamClient.GetISteamInventory(hsteamUser, hsteamPipe, "STEAMINVENTORY_INTERFACE_V003");
            if (CSteamAPIContext.m_pSteamInventory == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamVideo = SteamClient.GetISteamVideo(hsteamUser, hsteamPipe, "STEAMVIDEO_INTERFACE_V007");
            if (CSteamAPIContext.m_pSteamVideo == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamParentalSettings = SteamClient.GetISteamParentalSettings(hsteamUser, hsteamPipe, "STEAMPARENTALSETTINGS_INTERFACE_VERSION001");
            if (CSteamAPIContext.m_pSteamParentalSettings == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamInput = SteamClient.GetISteamInput(hsteamUser, hsteamPipe, "SteamInput006");
            if (CSteamAPIContext.m_pSteamInput == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamParties = SteamClient.GetISteamParties(hsteamUser, hsteamPipe, "SteamParties002");
            if (CSteamAPIContext.m_pSteamParties == IntPtr.Zero)
            {
                return false;
            }
            CSteamAPIContext.m_pSteamRemotePlay = SteamClient.GetISteamRemotePlay(hsteamUser, hsteamPipe, "STEAMREMOTEPLAY_INTERFACE_VERSION002");
            if (CSteamAPIContext.m_pSteamRemotePlay == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle2 = new InteropHelp.UTF8StringHandle("SteamNetworkingUtils004"))
            {
                CSteamAPIContext.m_pSteamNetworkingUtils = ((NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle2) != IntPtr.Zero) ? NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle2) : NativeMethods.SteamInternal_FindOrCreateGameServerInterface(hsteamUser, utf8StringHandle2));
            }
            if (CSteamAPIContext.m_pSteamNetworkingUtils == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle3 = new InteropHelp.UTF8StringHandle("SteamNetworkingSockets012"))
            {
                CSteamAPIContext.m_pSteamNetworkingSockets = NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle3);
            }
            if (CSteamAPIContext.m_pSteamNetworkingSockets == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle4 = new InteropHelp.UTF8StringHandle("SteamNetworkingMessages002"))
            {
                CSteamAPIContext.m_pSteamNetworkingMessages = NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle4);
            }
            if (CSteamAPIContext.m_pSteamNetworkingMessages == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle5 = new InteropHelp.UTF8StringHandle("STEAMTIMELINE_INTERFACE_V001"))
            {
                CSteamAPIContext.m_pSteamTimeline = NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle5);
            }
            return !(CSteamAPIContext.m_pSteamTimeline == IntPtr.Zero);
        }
References Steamworks.SteamAPI.GetHSteamPipe(), Steamworks.SteamAPI.GetHSteamUser(), Steamworks.SteamClient.GetISteamApps(), Steamworks.SteamClient.GetISteamFriends(), Steamworks.SteamClient.GetISteamGameSearch(), Steamworks.SteamClient.GetISteamHTMLSurface(), Steamworks.SteamClient.GetISteamHTTP(), Steamworks.SteamClient.GetISteamInput(), Steamworks.SteamClient.GetISteamInventory(), Steamworks.SteamClient.GetISteamMatchmaking(), Steamworks.SteamClient.GetISteamMatchmakingServers(), Steamworks.SteamClient.GetISteamMusic(), Steamworks.SteamClient.GetISteamMusicRemote(), Steamworks.SteamClient.GetISteamNetworking(), Steamworks.SteamClient.GetISteamParentalSettings(), Steamworks.SteamClient.GetISteamParties(), Steamworks.SteamClient.GetISteamRemotePlay(), Steamworks.SteamClient.GetISteamRemoteStorage(), Steamworks.SteamClient.GetISteamScreenshots(), Steamworks.SteamClient.GetISteamUGC(), Steamworks.SteamClient.GetISteamUser(), Steamworks.SteamClient.GetISteamUserStats(), Steamworks.SteamClient.GetISteamUtils(), Steamworks.SteamClient.GetISteamVideo(), Steamworks.CSteamAPIContext.m_pSteamApps, Steamworks.CSteamAPIContext.m_pSteamClient, Steamworks.CSteamAPIContext.m_pSteamFriends, Steamworks.CSteamAPIContext.m_pSteamGameSearch, Steamworks.CSteamAPIContext.m_pSteamHTMLSurface, Steamworks.CSteamAPIContext.m_pSteamHTTP, Steamworks.CSteamAPIContext.m_pSteamInput, Steamworks.CSteamAPIContext.m_pSteamInventory, Steamworks.CSteamAPIContext.m_pSteamMatchmaking, Steamworks.CSteamAPIContext.m_pSteamMatchmakingServers, Steamworks.CSteamAPIContext.m_pSteamMusic, Steamworks.CSteamAPIContext.m_pSteamMusicRemote, Steamworks.CSteamAPIContext.m_pSteamNetworking, Steamworks.CSteamAPIContext.m_pSteamNetworkingMessages, Steamworks.CSteamAPIContext.m_pSteamNetworkingSockets, Steamworks.CSteamAPIContext.m_pSteamNetworkingUtils, Steamworks.CSteamAPIContext.m_pSteamParentalSettings, Steamworks.CSteamAPIContext.m_pSteamParties, Steamworks.CSteamAPIContext.m_pSteamRemotePlay, Steamworks.CSteamAPIContext.m_pSteamRemoteStorage, Steamworks.CSteamAPIContext.m_pSteamScreenshots, Steamworks.CSteamAPIContext.m_pSteamUGC, Steamworks.CSteamAPIContext.m_pSteamUser, Steamworks.CSteamAPIContext.m_pSteamUserStats, Steamworks.CSteamAPIContext.m_pSteamUtils, Steamworks.CSteamAPIContext.m_pSteamVideo, Steamworks.NativeMethods.SteamInternal_CreateInterface(), Steamworks.NativeMethods.SteamInternal_FindOrCreateGameServerInterface(), Steamworks.NativeMethods.SteamInternal_FindOrCreateUserInterface(), and System.IntPtr.Zero.
Referenced by Steamworks.SteamAPI.InitEx(), and Steamworks.InteropHelp.TestIfAvailableClient().