Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamRemoteStorage
GetSteamRemoteStorage()
static IntPtr Steamworks.CSteamAPIContext.GetSteamRemoteStorage () inline static package
Definition at line 255 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamRemoteStorage;
        }
References Steamworks.CSteamAPIContext.m_pSteamRemoteStorage.
Referenced by Steamworks.SteamRemoteStorage.BeginFileWriteBatch(), Steamworks.SteamRemoteStorage.CommitPublishedFileUpdate(), Steamworks.SteamRemoteStorage.CreatePublishedFileUpdateRequest(), Steamworks.SteamRemoteStorage.DeletePublishedFile(), Steamworks.SteamRemoteStorage.EndFileWriteBatch(), Steamworks.SteamRemoteStorage.EnumeratePublishedFilesByUserAction(), Steamworks.SteamRemoteStorage.EnumeratePublishedWorkshopFiles(), Steamworks.SteamRemoteStorage.EnumerateUserPublishedFiles(), Steamworks.SteamRemoteStorage.EnumerateUserSharedWorkshopFiles(), Steamworks.SteamRemoteStorage.EnumerateUserSubscribedFiles(), Steamworks.SteamRemoteStorage.FileDelete(), Steamworks.SteamRemoteStorage.FileExists(), Steamworks.SteamRemoteStorage.FileForget(), Steamworks.SteamRemoteStorage.FilePersisted(), Steamworks.SteamRemoteStorage.FileRead(), Steamworks.SteamRemoteStorage.FileReadAsync(), Steamworks.SteamRemoteStorage.FileReadAsyncComplete(), Steamworks.SteamRemoteStorage.FileShare(), Steamworks.SteamRemoteStorage.FileWrite(), Steamworks.SteamRemoteStorage.FileWriteAsync(), Steamworks.SteamRemoteStorage.FileWriteStreamCancel(), Steamworks.SteamRemoteStorage.FileWriteStreamClose(), Steamworks.SteamRemoteStorage.FileWriteStreamOpen(), Steamworks.SteamRemoteStorage.FileWriteStreamWriteChunk(), Steamworks.SteamRemoteStorage.GetCachedUGCCount(), Steamworks.SteamRemoteStorage.GetCachedUGCHandle(), Steamworks.SteamRemoteStorage.GetFileCount(), Steamworks.SteamRemoteStorage.GetFileNameAndSize(), Steamworks.SteamRemoteStorage.GetFileSize(), Steamworks.SteamRemoteStorage.GetFileTimestamp(), Steamworks.SteamRemoteStorage.GetLocalFileChange(), Steamworks.SteamRemoteStorage.GetLocalFileChangeCount(), Steamworks.SteamRemoteStorage.GetPublishedFileDetails(), Steamworks.SteamRemoteStorage.GetPublishedItemVoteDetails(), Steamworks.SteamRemoteStorage.GetQuota(), Steamworks.SteamRemoteStorage.GetSyncPlatforms(), Steamworks.SteamRemoteStorage.GetUGCDetails(), Steamworks.SteamRemoteStorage.GetUGCDownloadProgress(), Steamworks.SteamRemoteStorage.GetUserPublishedItemVoteDetails(), Steamworks.SteamRemoteStorage.IsCloudEnabledForAccount(), Steamworks.SteamRemoteStorage.IsCloudEnabledForApp(), Steamworks.SteamRemoteStorage.PublishVideo(), Steamworks.SteamRemoteStorage.PublishWorkshopFile(), Steamworks.SteamRemoteStorage.SetCloudEnabledForApp(), Steamworks.SteamRemoteStorage.SetSyncPlatforms(), Steamworks.SteamRemoteStorage.SetUserPublishedFileAction(), Steamworks.SteamRemoteStorage.SubscribePublishedFile(), Steamworks.SteamRemoteStorage.UGCDownload(), Steamworks.SteamRemoteStorage.UGCDownloadToLocation(), Steamworks.SteamRemoteStorage.UGCRead(), Steamworks.SteamRemoteStorage.UnsubscribePublishedFile(), Steamworks.SteamRemoteStorage.UpdatePublishedFileDescription(), Steamworks.SteamRemoteStorage.UpdatePublishedFileFile(), Steamworks.SteamRemoteStorage.UpdatePublishedFilePreviewFile(), Steamworks.SteamRemoteStorage.UpdatePublishedFileSetChangeDescription(), Steamworks.SteamRemoteStorage.UpdatePublishedFileTags(), Steamworks.SteamRemoteStorage.UpdatePublishedFileTitle(), Steamworks.SteamRemoteStorage.UpdatePublishedFileVisibility(), and Steamworks.SteamRemoteStorage.UpdateUserPublishedItemVote().