Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamClient
GetSteamClient()
static IntPtr Steamworks.CSteamAPIContext.GetSteamClient () inline static package
Definition at line 201 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamClient;
        }
References Steamworks.CSteamAPIContext.m_pSteamClient.
Referenced by Steamworks.SteamClient.BReleaseSteamPipe(), Steamworks.SteamClient.BShutdownIfAllPipesClosed(), Steamworks.SteamClient.ConnectToGlobalUser(), Steamworks.SteamClient.CreateLocalUser(), Steamworks.SteamClient.CreateSteamPipe(), Steamworks.SteamClient.GetIPCCallCount(), Steamworks.SteamClient.GetISteamApps(), Steamworks.SteamClient.GetISteamController(), Steamworks.SteamClient.GetISteamFriends(), Steamworks.SteamClient.GetISteamGameSearch(), Steamworks.SteamClient.GetISteamGameServer(), Steamworks.SteamClient.GetISteamGameServerStats(), Steamworks.SteamClient.GetISteamGenericInterface(), Steamworks.SteamClient.GetISteamHTMLSurface(), Steamworks.SteamClient.GetISteamHTTP(), Steamworks.SteamClient.GetISteamInput(), Steamworks.SteamClient.GetISteamInventory(), Steamworks.SteamClient.GetISteamMatchmaking(), Steamworks.SteamClient.GetISteamMatchmakingServers(), Steamworks.SteamClient.GetISteamMusic(), Steamworks.SteamClient.GetISteamMusicRemote(), Steamworks.SteamClient.GetISteamNetworking(), Steamworks.SteamClient.GetISteamParentalSettings(), Steamworks.SteamClient.GetISteamParties(), Steamworks.SteamClient.GetISteamRemotePlay(), Steamworks.SteamClient.GetISteamRemoteStorage(), Steamworks.SteamClient.GetISteamScreenshots(), Steamworks.SteamClient.GetISteamUGC(), Steamworks.SteamClient.GetISteamUser(), Steamworks.SteamClient.GetISteamUserStats(), Steamworks.SteamClient.GetISteamUtils(), Steamworks.SteamClient.GetISteamVideo(), Steamworks.SteamClient.ReleaseUser(), Steamworks.SteamClient.SetLocalIPBinding(), Steamworks.SteamClient.SetWarningMessageHook(), and Steamworks.InteropHelp.TestIfAvailableClient().