Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamNetworkingSockets
GetSteamNetworkingSockets()
static IntPtr Steamworks.CSteamAPIContext.GetSteamNetworkingSockets () inline static package
Definition at line 351 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamNetworkingSockets;
        }
References Steamworks.CSteamAPIContext.m_pSteamNetworkingSockets.
Referenced by Steamworks.SteamNetworkingSockets.AcceptConnection(), Steamworks.SteamNetworkingSockets.BeginAsyncRequestFakeIP(), Steamworks.SteamNetworkingSockets.CloseConnection(), Steamworks.SteamNetworkingSockets.CloseListenSocket(), Steamworks.SteamNetworkingSockets.ConfigureConnectionLanes(), Steamworks.SteamNetworkingSockets.ConnectByIPAddress(), Steamworks.SteamNetworkingSockets.ConnectP2P(), Steamworks.SteamNetworkingSockets.ConnectP2PCustomSignaling(), Steamworks.SteamNetworkingSockets.ConnectToHostedDedicatedServer(), Steamworks.SteamNetworkingSockets.CreateFakeUDPPort(), Steamworks.SteamNetworkingSockets.CreateHostedDedicatedServerListenSocket(), Steamworks.SteamNetworkingSockets.CreateListenSocketIP(), Steamworks.SteamNetworkingSockets.CreateListenSocketP2P(), Steamworks.SteamNetworkingSockets.CreateListenSocketP2PFakeIP(), Steamworks.SteamNetworkingSockets.CreatePollGroup(), Steamworks.SteamNetworkingSockets.CreateSocketPair(), Steamworks.SteamNetworkingSockets.DestroyPollGroup(), Steamworks.SteamNetworkingSockets.FindRelayAuthTicketForServer(), Steamworks.SteamNetworkingSockets.FlushMessagesOnConnection(), Steamworks.SteamNetworkingSockets.GetAuthenticationStatus(), Steamworks.SteamNetworkingSockets.GetCertificateRequest(), Steamworks.SteamNetworkingSockets.GetConnectionInfo(), Steamworks.SteamNetworkingSockets.GetConnectionName(), Steamworks.SteamNetworkingSockets.GetConnectionRealTimeStatus(), Steamworks.SteamNetworkingSockets.GetConnectionUserData(), Steamworks.SteamNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamNetworkingSockets.GetFakeIP(), Steamworks.SteamNetworkingSockets.GetGameCoordinatorServerLogin(), Steamworks.SteamNetworkingSockets.GetHostedDedicatedServerAddress(), Steamworks.SteamNetworkingSockets.GetHostedDedicatedServerPOPID(), Steamworks.SteamNetworkingSockets.GetHostedDedicatedServerPort(), Steamworks.SteamNetworkingSockets.GetIdentity(), Steamworks.SteamNetworkingSockets.GetListenSocketAddress(), Steamworks.SteamNetworkingSockets.GetRemoteFakeIPForConnection(), Steamworks.SteamNetworkingSockets.InitAuthentication(), Steamworks.SteamNetworkingSockets.ReceivedP2PCustomSignal(), Steamworks.SteamNetworkingSockets.ReceivedRelayAuthTicket(), Steamworks.SteamNetworkingSockets.ReceiveMessagesOnConnection(), Steamworks.SteamNetworkingSockets.ReceiveMessagesOnPollGroup(), Steamworks.SteamNetworkingSockets.ResetIdentity(), Steamworks.SteamNetworkingSockets.RunCallbacks(), Steamworks.SteamNetworkingSockets.SendMessages(), Steamworks.SteamNetworkingSockets.SendMessageToConnection(), Steamworks.SteamNetworkingSockets.SetCertificate(), Steamworks.SteamNetworkingSockets.SetConnectionName(), Steamworks.SteamNetworkingSockets.SetConnectionPollGroup(), and Steamworks.SteamNetworkingSockets.SetConnectionUserData().