Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamFriends
GetSteamFriends()
static IntPtr Steamworks.CSteamAPIContext.GetSteamFriends () inline static package
Definition at line 213 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamFriends;
        }
References Steamworks.CSteamAPIContext.m_pSteamFriends.
Referenced by Steamworks.SteamFriends.ActivateGameOverlay(), Steamworks.SteamFriends.ActivateGameOverlayInviteDialog(), Steamworks.SteamFriends.ActivateGameOverlayInviteDialogConnectString(), Steamworks.SteamFriends.ActivateGameOverlayRemotePlayTogetherInviteDialog(), Steamworks.SteamFriends.ActivateGameOverlayToStore(), Steamworks.SteamFriends.ActivateGameOverlayToUser(), Steamworks.SteamFriends.ActivateGameOverlayToWebPage(), Steamworks.SteamFriends.BHasEquippedProfileItem(), Steamworks.SteamFriends.ClearRichPresence(), Steamworks.SteamFriends.CloseClanChatWindowInSteam(), Steamworks.SteamFriends.DownloadClanActivityCounts(), Steamworks.SteamFriends.EnumerateFollowingList(), Steamworks.SteamFriends.GetChatMemberByIndex(), Steamworks.SteamFriends.GetClanActivityCounts(), Steamworks.SteamFriends.GetClanByIndex(), Steamworks.SteamFriends.GetClanChatMemberCount(), Steamworks.SteamFriends.GetClanChatMessage(), Steamworks.SteamFriends.GetClanCount(), Steamworks.SteamFriends.GetClanName(), Steamworks.SteamFriends.GetClanOfficerByIndex(), Steamworks.SteamFriends.GetClanOfficerCount(), Steamworks.SteamFriends.GetClanOwner(), Steamworks.SteamFriends.GetClanTag(), Steamworks.SteamFriends.GetCoplayFriend(), Steamworks.SteamFriends.GetCoplayFriendCount(), Steamworks.SteamFriends.GetFollowerCount(), Steamworks.SteamFriends.GetFriendByIndex(), Steamworks.SteamFriends.GetFriendCoplayGame(), Steamworks.SteamFriends.GetFriendCoplayTime(), Steamworks.SteamFriends.GetFriendCount(), Steamworks.SteamFriends.GetFriendCountFromSource(), Steamworks.SteamFriends.GetFriendFromSourceByIndex(), Steamworks.SteamFriends.GetFriendGamePlayed(), Steamworks.SteamFriends.GetFriendMessage(), Steamworks.SteamFriends.GetFriendPersonaName(), Steamworks.SteamFriends.GetFriendPersonaNameHistory(), Steamworks.SteamFriends.GetFriendPersonaState(), Steamworks.SteamFriends.GetFriendRelationship(), Steamworks.SteamFriends.GetFriendRichPresence(), Steamworks.SteamFriends.GetFriendRichPresenceKeyByIndex(), Steamworks.SteamFriends.GetFriendRichPresenceKeyCount(), Steamworks.SteamFriends.GetFriendsGroupCount(), Steamworks.SteamFriends.GetFriendsGroupIDByIndex(), Steamworks.SteamFriends.GetFriendsGroupMembersCount(), Steamworks.SteamFriends.GetFriendsGroupMembersList(), Steamworks.SteamFriends.GetFriendsGroupName(), Steamworks.SteamFriends.GetFriendSteamLevel(), Steamworks.SteamFriends.GetLargeFriendAvatar(), Steamworks.SteamFriends.GetMediumFriendAvatar(), Steamworks.SteamFriends.GetNumChatsWithUnreadPriorityMessages(), Steamworks.SteamFriends.GetPersonaName(), Steamworks.SteamFriends.GetPersonaState(), Steamworks.SteamFriends.GetPlayerNickname(), Steamworks.SteamFriends.GetProfileItemPropertyString(), Steamworks.SteamFriends.GetProfileItemPropertyUint(), Steamworks.SteamFriends.GetSmallFriendAvatar(), Steamworks.SteamFriends.GetUserRestrictions(), Steamworks.SteamFriends.HasFriend(), Steamworks.SteamFriends.InviteUserToGame(), Steamworks.SteamFriends.IsClanChatAdmin(), Steamworks.SteamFriends.IsClanChatWindowOpenInSteam(), Steamworks.SteamFriends.IsClanOfficialGameGroup(), Steamworks.SteamFriends.IsClanPublic(), Steamworks.SteamFriends.IsFollowing(), Steamworks.SteamFriends.IsUserInSource(), Steamworks.SteamFriends.JoinClanChatRoom(), Steamworks.SteamFriends.LeaveClanChatRoom(), Steamworks.SteamFriends.OpenClanChatWindowInSteam(), Steamworks.SteamFriends.RegisterProtocolInOverlayBrowser(), Steamworks.SteamFriends.ReplyToFriendMessage(), Steamworks.SteamFriends.RequestClanOfficerList(), Steamworks.SteamFriends.RequestEquippedProfileItems(), Steamworks.SteamFriends.RequestFriendRichPresence(), Steamworks.SteamFriends.RequestUserInformation(), Steamworks.SteamFriends.SendClanChatMessage(), Steamworks.SteamFriends.SetInGameVoiceSpeaking(), Steamworks.SteamFriends.SetListenForFriendsMessages(), Steamworks.SteamFriends.SetPersonaName(), Steamworks.SteamFriends.SetPlayedWith(), and Steamworks.SteamFriends.SetRichPresence().