Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamMusicRemote
GetSteamMusicRemote()
static IntPtr Steamworks.CSteamAPIContext.GetSteamMusicRemote () inline static package
Definition at line 297 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamMusicRemote;
        }
References Steamworks.CSteamAPIContext.m_pSteamMusicRemote.
Referenced by Steamworks.SteamMusicRemote.BActivationSuccess(), Steamworks.SteamMusicRemote.BIsCurrentMusicRemote(), Steamworks.SteamMusicRemote.CurrentEntryDidChange(), Steamworks.SteamMusicRemote.CurrentEntryIsAvailable(), Steamworks.SteamMusicRemote.CurrentEntryWillChange(), Steamworks.SteamMusicRemote.DeregisterSteamMusicRemote(), Steamworks.SteamMusicRemote.EnableLooped(), Steamworks.SteamMusicRemote.EnablePlaylists(), Steamworks.SteamMusicRemote.EnablePlayNext(), Steamworks.SteamMusicRemote.EnablePlayPrevious(), Steamworks.SteamMusicRemote.EnableQueue(), Steamworks.SteamMusicRemote.EnableShuffled(), Steamworks.SteamMusicRemote.PlaylistDidChange(), Steamworks.SteamMusicRemote.PlaylistWillChange(), Steamworks.SteamMusicRemote.QueueDidChange(), Steamworks.SteamMusicRemote.QueueWillChange(), Steamworks.SteamMusicRemote.RegisterSteamMusicRemote(), Steamworks.SteamMusicRemote.ResetPlaylistEntries(), Steamworks.SteamMusicRemote.ResetQueueEntries(), Steamworks.SteamMusicRemote.SetCurrentPlaylistEntry(), Steamworks.SteamMusicRemote.SetCurrentQueueEntry(), Steamworks.SteamMusicRemote.SetDisplayName(), Steamworks.SteamMusicRemote.SetPlaylistEntry(), Steamworks.SteamMusicRemote.SetPNGIcon_64x64(), Steamworks.SteamMusicRemote.SetQueueEntry(), Steamworks.SteamMusicRemote.UpdateCurrentEntryCoverArt(), Steamworks.SteamMusicRemote.UpdateCurrentEntryElapsedSeconds(), Steamworks.SteamMusicRemote.UpdateCurrentEntryText(), Steamworks.SteamMusicRemote.UpdateLooped(), Steamworks.SteamMusicRemote.UpdatePlaybackStatus(), Steamworks.SteamMusicRemote.UpdateShuffled(), and Steamworks.SteamMusicRemote.UpdateVolume().