Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamUser
GetSteamUser()
static IntPtr Steamworks.CSteamAPIContext.GetSteamUser () inline static package
Definition at line 207 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamUser;
        }
References Steamworks.CSteamAPIContext.m_pSteamUser.
Referenced by Steamworks.SteamUser.AdvertiseGame(), Steamworks.SteamUser.BeginAuthSession(), Steamworks.SteamUser.BIsBehindNAT(), Steamworks.SteamUser.BIsPhoneIdentifying(), Steamworks.SteamUser.BIsPhoneRequiringVerification(), Steamworks.SteamUser.BIsPhoneVerified(), Steamworks.SteamUser.BIsTwoFactorEnabled(), Steamworks.SteamUser.BLoggedOn(), Steamworks.SteamUser.BSetDurationControlOnlineState(), Steamworks.SteamUser.CancelAuthTicket(), Steamworks.SteamUser.DecompressVoice(), Steamworks.SteamUser.EndAuthSession(), Steamworks.SteamUser.GetAuthSessionTicket(), Steamworks.SteamUser.GetAuthTicketForWebApi(), Steamworks.SteamUser.GetAvailableVoice(), Steamworks.SteamUser.GetDurationControl(), Steamworks.SteamUser.GetEncryptedAppTicket(), Steamworks.SteamUser.GetGameBadgeLevel(), Steamworks.SteamUser.GetHSteamUser(), Steamworks.SteamUser.GetMarketEligibility(), Steamworks.SteamUser.GetPlayerSteamLevel(), Steamworks.SteamUser.GetSteamID(), Steamworks.SteamUser.GetUserDataFolder(), Steamworks.SteamUser.GetVoice(), Steamworks.SteamUser.GetVoiceOptimalSampleRate(), Steamworks.SteamUser.InitiateGameConnection_DEPRECATED(), Steamworks.SteamUser.RequestEncryptedAppTicket(), Steamworks.SteamUser.RequestStoreAuthURL(), Steamworks.SteamUser.StartVoiceRecording(), Steamworks.SteamUser.StopVoiceRecording(), Steamworks.SteamUser.TerminateGameConnection_DEPRECATED(), Steamworks.SteamUser.TrackAppUsageEvent(), and Steamworks.SteamUser.UserHasLicenseForApp().