Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamInput
GetSteamInput()
static IntPtr Steamworks.CSteamAPIContext.GetSteamInput () inline static package
Definition at line 327 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamInput;
        }
References Steamworks.CSteamAPIContext.m_pSteamInput.
Referenced by Steamworks.SteamInput.ActivateActionSet(), Steamworks.SteamInput.ActivateActionSetLayer(), Steamworks.SteamInput.BNewDataAvailable(), Steamworks.SteamInput.BWaitForData(), Steamworks.SteamInput.DeactivateActionSetLayer(), Steamworks.SteamInput.DeactivateAllActionSetLayers(), Steamworks.SteamInput.EnableActionEventCallbacks(), Steamworks.SteamInput.EnableDeviceCallbacks(), Steamworks.SteamInput.GetActionOriginFromXboxOrigin(), Steamworks.SteamInput.GetActionSetHandle(), Steamworks.SteamInput.GetActiveActionSetLayers(), Steamworks.SteamInput.GetAnalogActionData(), Steamworks.SteamInput.GetAnalogActionHandle(), Steamworks.SteamInput.GetAnalogActionOrigins(), Steamworks.SteamInput.GetConnectedControllers(), Steamworks.SteamInput.GetControllerForGamepadIndex(), Steamworks.SteamInput.GetCurrentActionSet(), Steamworks.SteamInput.GetDeviceBindingRevision(), Steamworks.SteamInput.GetDigitalActionData(), Steamworks.SteamInput.GetDigitalActionHandle(), Steamworks.SteamInput.GetDigitalActionOrigins(), Steamworks.SteamInput.GetGamepadIndexForController(), Steamworks.SteamInput.GetGlyphForActionOrigin_Legacy(), Steamworks.SteamInput.GetGlyphForXboxOrigin(), Steamworks.SteamInput.GetGlyphPNGForActionOrigin(), Steamworks.SteamInput.GetGlyphSVGForActionOrigin(), Steamworks.SteamInput.GetInputTypeForHandle(), Steamworks.SteamInput.GetMotionData(), Steamworks.SteamInput.GetRemotePlaySessionID(), Steamworks.SteamInput.GetSessionInputConfigurationSettings(), Steamworks.SteamInput.GetStringForActionOrigin(), Steamworks.SteamInput.GetStringForAnalogActionName(), Steamworks.SteamInput.GetStringForDigitalActionName(), Steamworks.SteamInput.GetStringForXboxOrigin(), Steamworks.SteamInput.Init(), Steamworks.SteamInput.Legacy_TriggerHapticPulse(), Steamworks.SteamInput.Legacy_TriggerRepeatedHapticPulse(), Steamworks.SteamInput.RunFrame(), Steamworks.SteamInput.SetDualSenseTriggerEffect(), Steamworks.SteamInput.SetInputActionManifestFilePath(), Steamworks.SteamInput.SetLEDColor(), Steamworks.SteamInput.ShowBindingPanel(), Steamworks.SteamInput.Shutdown(), Steamworks.SteamInput.StopAnalogActionMomentum(), Steamworks.SteamInput.TranslateActionOrigin(), Steamworks.SteamInput.TriggerSimpleHapticEvent(), Steamworks.SteamInput.TriggerVibration(), and Steamworks.SteamInput.TriggerVibrationExtended().