Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamApps
GetSteamApps()
static IntPtr Steamworks.CSteamAPIContext.GetSteamApps () inline static package
Definition at line 237 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamApps;
        }
References Steamworks.CSteamAPIContext.m_pSteamApps.
Referenced by Steamworks.SteamApps.BGetDLCDataByIndex(), Steamworks.SteamApps.BIsAppInstalled(), Steamworks.SteamApps.BIsCybercafe(), Steamworks.SteamApps.BIsDlcInstalled(), Steamworks.SteamApps.BIsLowViolence(), Steamworks.SteamApps.BIsSubscribed(), Steamworks.SteamApps.BIsSubscribedApp(), Steamworks.SteamApps.BIsSubscribedFromFamilySharing(), Steamworks.SteamApps.BIsSubscribedFromFreeWeekend(), Steamworks.SteamApps.BIsTimedTrial(), Steamworks.SteamApps.BIsVACBanned(), Steamworks.SteamApps.GetAppBuildId(), Steamworks.SteamApps.GetAppInstallDir(), Steamworks.SteamApps.GetAppOwner(), Steamworks.SteamApps.GetAvailableGameLanguages(), Steamworks.SteamApps.GetBetaInfo(), Steamworks.SteamApps.GetCurrentBetaName(), Steamworks.SteamApps.GetCurrentGameLanguage(), Steamworks.SteamApps.GetDLCCount(), Steamworks.SteamApps.GetDlcDownloadProgress(), Steamworks.SteamApps.GetEarliestPurchaseUnixTime(), Steamworks.SteamApps.GetFileDetails(), Steamworks.SteamApps.GetInstalledDepots(), Steamworks.SteamApps.GetLaunchCommandLine(), Steamworks.SteamApps.GetLaunchQueryParam(), Steamworks.SteamApps.GetNumBetas(), Steamworks.SteamApps.InstallDLC(), Steamworks.SteamApps.MarkContentCorrupt(), Steamworks.SteamApps.RequestAllProofOfPurchaseKeys(), Steamworks.SteamApps.RequestAppProofOfPurchaseKey(), Steamworks.SteamApps.SetActiveBeta(), Steamworks.SteamApps.SetDlcContext(), and Steamworks.SteamApps.UninstallDLC().