Terraria Decompiled: Steamworks.CSteamAPIContext.GetSteamUGC
GetSteamUGC()
static IntPtr Steamworks.CSteamAPIContext.GetSteamUGC () inline static package
Definition at line 285 of file CSteamAPIContext.cs.
        {
            return CSteamAPIContext.m_pSteamUGC;
        }
References Steamworks.CSteamAPIContext.m_pSteamUGC.
Referenced by Steamworks.SteamUGC.AddAppDependency(), Steamworks.SteamUGC.AddContentDescriptor(), Steamworks.SteamUGC.AddDependency(), Steamworks.SteamUGC.AddExcludedTag(), Steamworks.SteamUGC.AddItemKeyValueTag(), Steamworks.SteamUGC.AddItemPreviewFile(), Steamworks.SteamUGC.AddItemPreviewVideo(), Steamworks.SteamUGC.AddItemToFavorites(), Steamworks.SteamUGC.AddRequiredKeyValueTag(), Steamworks.SteamUGC.AddRequiredTag(), Steamworks.SteamUGC.AddRequiredTagGroup(), Steamworks.SteamUGC.BInitWorkshopForGameServer(), Steamworks.SteamUGC.CreateItem(), Steamworks.SteamUGC.CreateQueryAllUGCRequest(), Steamworks.SteamUGC.CreateQueryAllUGCRequest(), Steamworks.SteamUGC.CreateQueryUGCDetailsRequest(), Steamworks.SteamUGC.CreateQueryUserUGCRequest(), Steamworks.SteamUGC.DeleteItem(), Steamworks.SteamUGC.DownloadItem(), Steamworks.SteamUGC.GetAppDependencies(), Steamworks.SteamUGC.GetItemDownloadInfo(), Steamworks.SteamUGC.GetItemInstallInfo(), Steamworks.SteamUGC.GetItemState(), Steamworks.SteamUGC.GetItemUpdateProgress(), Steamworks.SteamUGC.GetNumSubscribedItems(), Steamworks.SteamUGC.GetNumSupportedGameVersions(), Steamworks.SteamUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamUGC.GetQueryUGCChildren(), Steamworks.SteamUGC.GetQueryUGCContentDescriptors(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCMetadata(), Steamworks.SteamUGC.GetQueryUGCNumAdditionalPreviews(), Steamworks.SteamUGC.GetQueryUGCNumKeyValueTags(), Steamworks.SteamUGC.GetQueryUGCNumTags(), Steamworks.SteamUGC.GetQueryUGCPreviewURL(), Steamworks.SteamUGC.GetQueryUGCResult(), Steamworks.SteamUGC.GetQueryUGCStatistic(), Steamworks.SteamUGC.GetQueryUGCTag(), Steamworks.SteamUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamUGC.GetSubscribedItems(), Steamworks.SteamUGC.GetSupportedGameVersionData(), Steamworks.SteamUGC.GetUserContentDescriptorPreferences(), Steamworks.SteamUGC.GetUserItemVote(), Steamworks.SteamUGC.GetWorkshopEULAStatus(), Steamworks.SteamUGC.ReleaseQueryUGCRequest(), Steamworks.SteamUGC.RemoveAllItemKeyValueTags(), Steamworks.SteamUGC.RemoveAppDependency(), Steamworks.SteamUGC.RemoveContentDescriptor(), Steamworks.SteamUGC.RemoveDependency(), Steamworks.SteamUGC.RemoveItemFromFavorites(), Steamworks.SteamUGC.RemoveItemKeyValueTags(), Steamworks.SteamUGC.RemoveItemPreview(), Steamworks.SteamUGC.RequestUGCDetails(), Steamworks.SteamUGC.SendQueryUGCRequest(), Steamworks.SteamUGC.SetAdminQuery(), Steamworks.SteamUGC.SetAllowCachedResponse(), Steamworks.SteamUGC.SetAllowLegacyUpload(), Steamworks.SteamUGC.SetCloudFileNameFilter(), Steamworks.SteamUGC.SetItemContent(), Steamworks.SteamUGC.SetItemDescription(), Steamworks.SteamUGC.SetItemMetadata(), Steamworks.SteamUGC.SetItemPreview(), Steamworks.SteamUGC.SetItemTags(), Steamworks.SteamUGC.SetItemTitle(), Steamworks.SteamUGC.SetItemUpdateLanguage(), Steamworks.SteamUGC.SetItemVisibility(), Steamworks.SteamUGC.SetLanguage(), Steamworks.SteamUGC.SetMatchAnyTag(), Steamworks.SteamUGC.SetRankedByTrendDays(), Steamworks.SteamUGC.SetRequiredGameVersions(), Steamworks.SteamUGC.SetReturnAdditionalPreviews(), Steamworks.SteamUGC.SetReturnChildren(), Steamworks.SteamUGC.SetReturnKeyValueTags(), Steamworks.SteamUGC.SetReturnLongDescription(), Steamworks.SteamUGC.SetReturnMetadata(), Steamworks.SteamUGC.SetReturnOnlyIDs(), Steamworks.SteamUGC.SetReturnPlaytimeStats(), Steamworks.SteamUGC.SetReturnTotalOnly(), Steamworks.SteamUGC.SetSearchText(), Steamworks.SteamUGC.SetTimeCreatedDateRange(), Steamworks.SteamUGC.SetTimeUpdatedDateRange(), Steamworks.SteamUGC.SetUserItemVote(), Steamworks.SteamUGC.ShowWorkshopEULA(), Steamworks.SteamUGC.StartItemUpdate(), Steamworks.SteamUGC.StartPlaytimeTracking(), Steamworks.SteamUGC.StopPlaytimeTracking(), Steamworks.SteamUGC.StopPlaytimeTrackingForAllItems(), Steamworks.SteamUGC.SubmitItemUpdate(), Steamworks.SteamUGC.SubscribeItem(), Steamworks.SteamUGC.SuspendDownloads(), Steamworks.SteamUGC.UnsubscribeItem(), Steamworks.SteamUGC.UpdateItemPreviewFile(), and Steamworks.SteamUGC.UpdateItemPreviewVideo().