Terraria Decompiled: Terraria.GameContent.LootSimulation.LootSimulator.TryGettingLootFor
TryGettingLootFor()
bool Terraria.GameContent.LootSimulation.LootSimulator.TryGettingLootFor (int npcNetId, int timesMultiplier, out string outputText) inline private
Definition at line 91 of file LootSimulator.cs.
        {
            SimulatorInfo simulatorInfo = new SimulatorInfo();
            NPC npc = new NPC();
            npc.SetDefaults(npcNetId, default(NPCSpawnParams));
            simulatorInfo.npcVictim = npc;
            LootSimulationItemCounter lootSimulationItemCounter = new LootSimulationItemCounter();
            simulatorInfo.itemCounter = lootSimulationItemCounter;
            foreach (ISimulationConditionSetter simulationConditionSetter in this._neededTestConditions)
            {
                simulationConditionSetter.Setup(simulatorInfo);
                int num = simulationConditionSetter.GetTimesToRunMultiplier(simulatorInfo) * timesMultiplier;
                for (int i = 0; i < num; i++)
                {
                    npc.NPCLoot();
                }
                lootSimulationItemCounter.IncreaseTimesAttempted(num, simulatorInfo.runningExpertMode);
                simulationConditionSetter.TearDown(simulatorInfo);
                this.SetCleanSlateWorldConditions();
            }
            lootSimulationItemCounter.Exclude(this._excludedItemIds.ToArray<int>());
            string text = lootSimulationItemCounter.PrintCollectedItems(false);
            string text2 = lootSimulationItemCounter.PrintCollectedItems(true);
            string name = NPCID.Search.GetName(npcNetId);
            string text3 = string.Format("FindEntryByNPCID(NPCID.{0})", name);
            if (text.Length > 0)
            {
                text3 = string.Format("{0}\n.AddDropsNormalMode({1})", text3, text);
            }
            if (text2.Length > 0)
            {
                text3 = string.Format("{0}\n.AddDropsExpertMode({1})", text3, text2);
            }
            text3 += ";";
            outputText = text3;
            return text.Length > 0 || text2.Length > 0;
        }
References Terraria.GameContent.LootSimulation.LootSimulator._excludedItemIds, Terraria.GameContent.LootSimulation.LootSimulator._neededTestConditions, Terraria.GameContent.LootSimulation.ISimulationConditionSetter.GetTimesToRunMultiplier(), System.name, Terraria.ID.NPCID.Search, Terraria.GameContent.LootSimulation.LootSimulator.SetCleanSlateWorldConditions(), Terraria.NPC.SetDefaults(), Terraria.GameContent.LootSimulation.ISimulationConditionSetter.Setup(), Terraria.GameContent.LootSimulation.ISimulationConditionSetter.TearDown(), and System.text.
Referenced by Terraria.GameContent.LootSimulation.LootSimulator.Run().