Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.GetEventRegistrationTokenTable
GetEventRegistrationTokenTable()
static Dictionary< object, WindowsRuntimeMarshal.EventRegistrationTokenList > System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.GetEventRegistrationTokenTable (object instance, Action< EventRegistrationToken > removeMethod) inline static private
Definition at line 401 of file WindowsRuntimeMarshal.cs.
            {
                ConditionalWeakTable<object, Dictionary<MethodInfo, Dictionary<object, WindowsRuntimeMarshal.EventRegistrationTokenList>>> conditionalWeakTable = WindowsRuntimeMarshal.ManagedEventRegistrationImpl.s_eventRegistrations;
                Dictionary<object, WindowsRuntimeMarshal.EventRegistrationTokenList> dictionary3;
                lock (conditionalWeakTable)
                {
                    Dictionary<MethodInfo, Dictionary<object, WindowsRuntimeMarshal.EventRegistrationTokenList>> dictionary = null;
                    if (!WindowsRuntimeMarshal.ManagedEventRegistrationImpl.s_eventRegistrations.TryGetValue(instance, out dictionary))
                    {
                        dictionary = new Dictionary<MethodInfo, Dictionary<object, WindowsRuntimeMarshal.EventRegistrationTokenList>>();
                        WindowsRuntimeMarshal.ManagedEventRegistrationImpl.s_eventRegistrations.Add(instance, dictionary);
                    }
                    Dictionary<object, WindowsRuntimeMarshal.EventRegistrationTokenList> dictionary2 = null;
                    if (!dictionary.TryGetValue(removeMethod.Method, out dictionary2))
                    {
                        dictionary2 = new Dictionary<object, WindowsRuntimeMarshal.EventRegistrationTokenList>();
                        dictionary.Add(removeMethod.Method, dictionary2);
                    }
                    dictionary3 = dictionary2;
                }
                return dictionary3;
            }
References System.dictionary, and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.s_eventRegistrations.
Referenced by System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.AddEventHandler< T >(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.RemoveAllEventHandlers(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.ManagedEventRegistrationImpl.RemoveEventHandler< T >().