Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormatUInt64N
TryFormatUInt64N()
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormatUInt64N (ulong value, byte precision, Span< byte > destination, bool insertNegationSign, out int bytesWritten) inline static private
Definition at line 1159 of file Utf8Formatter.cs.
        {
            int num = FormattingHelpers.CountDigits(value);
            int num2 = (num - 1) / 3;
            int num3 = (int)((precision == byte.MaxValue) ? 2 : precision);
            int num4 = num + num2;
            if (num3 > 0)
            {
                num4 += num3 + 1;
            }
            if (insertNegationSign)
            {
                num4++;
            }
            if (num4 > destination.Length)
            {
                bytesWritten = 0;
                return false;
            }
            bytesWritten = num4;
            if (insertNegationSign)
            {
                *destination[0] = 45;
                destination = destination.Slice(1);
            }
            FormattingHelpers.WriteDigitsWithGroupSeparator(value, destination.Slice(0, num + num2));
            if (num3 > 0)
            {
                *destination[num + num2] = 46;
                FormattingHelpers.FillWithAsciiZeros(destination.Slice(num + num2 + 1, num3));
            }
            return true;
        }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Buffers.Text.FormattingHelpers.FillWithAsciiZeros(), int, System.value, and System.Buffers.Text.FormattingHelpers.WriteDigitsWithGroupSeparator().
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatInt64N(), and System.Buffers.Text.Utf8Formatter.TryFormatUInt64().