Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [1/16]
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormat (bool value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 13 of file Utf8Formatter.cs.
        {
            char symbolOrDefault = FormattingHelpers.GetSymbolOrDefault(in format, 'G');
            if (value)
            {
                if (symbolOrDefault == 'G')
                {
                    if (!BinaryPrimitives.TryWriteUInt32BigEndian(destination, 1416787301U))
                    {
                        goto IL_007E;
                    }
                }
                else
                {
                    if (symbolOrDefault != 'l')
                    {
                        goto IL_0083;
                    }
                    if (!BinaryPrimitives.TryWriteUInt32BigEndian(destination, 1953658213U))
                    {
                        goto IL_007E;
                    }
                }
                bytesWritten = 4;
                return true;
            }
            if (symbolOrDefault == 'G')
            {
                if (4 >= destination.Length)
                {
                    goto IL_007E;
                }
                BinaryPrimitives.WriteUInt32BigEndian(destination, 1180789875U);
            }
            else
            {
                if (symbolOrDefault != 'l')
                {
                    goto IL_0083;
                }
                if (4 >= destination.Length)
                {
                    goto IL_007E;
                }
                BinaryPrimitives.WriteUInt32BigEndian(destination, 1717660787U);
            }
            *destination[4] = 101;
            bytesWritten = 5;
            return true;
            IL_007E:
            bytesWritten = 0;
            return false;
            IL_0083:
            return ThrowHelper.TryFormatThrowFormatException(out bytesWritten);
        }
References System.destination, System.format, System.Buffers.Text.FormattingHelpers.GetSymbolOrDefault(), System.ThrowHelper.TryFormatThrowFormatException(), System.Buffers.Binary.BinaryPrimitives.TryWriteUInt32BigEndian(), System.U, System.value, and System.Buffers.Binary.BinaryPrimitives.WriteUInt32BigEndian().