Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormatUInt64Default
TryFormatUInt64Default()
static bool System.Buffers.Text.Utf8Formatter.TryFormatUInt64Default (ulong value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 1029 of file Utf8Formatter.cs.
        {
            if (value < 10UL)
            {
                return Utf8Formatter.TryFormatUInt32SingleDigit((uint)value, destination, out bytesWritten);
            }
            if (IntPtr.Size == 8)
            {
                return Utf8Formatter.TryFormatUInt64MultipleDigits(value, destination, out bytesWritten);
            }
            if (value <= (ulong)(-1))
            {
                return Utf8Formatter.TryFormatUInt32MultipleDigits((uint)value, destination, out bytesWritten);
            }
            if (value <= 4294967295000000000UL)
            {
                return Utf8Formatter.TryFormatUInt64LessThanBillionMaxUInt(value, destination, out bytesWritten);
            }
            return Utf8Formatter.TryFormatUInt64MoreThanBillionMaxUInt(value, destination, out bytesWritten);
        }
References System.destination, System.IntPtr.Size, System.Buffers.Text.Utf8Formatter.TryFormatUInt32MultipleDigits(), System.Buffers.Text.Utf8Formatter.TryFormatUInt32SingleDigit(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64LessThanBillionMaxUInt(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64MoreThanBillionMaxUInt(), System.Buffers.Text.Utf8Formatter.TryFormatUInt64MultipleDigits(), and System.value.
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatUInt64().