Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [4/16]
static bool System.Buffers.Text.Utf8Formatter.TryFormat (DateTimeOffset value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 263 of file Utf8Formatter.cs.
        {
            TimeSpan timeSpan = Utf8Constants.s_nullUtcOffset;
            char c = format.Symbol;
            if (format.IsDefault)
            {
                c = 'G';
                timeSpan = value.Offset;
            }
            if (c <= 'O')
            {
                if (c == 'G')
                {
                    return Utf8Formatter.TryFormatDateTimeG(value.DateTime, timeSpan, destination, out bytesWritten);
                }
                if (c == 'O')
                {
                    return Utf8Formatter.TryFormatDateTimeO(value.DateTime, value.Offset, destination, out bytesWritten);
                }
            }
            else
            {
                if (c == 'R')
                {
                    return Utf8Formatter.TryFormatDateTimeR(value.UtcDateTime, destination, out bytesWritten);
                }
                if (c == 'l')
                {
                    return Utf8Formatter.TryFormatDateTimeL(value.UtcDateTime, destination, out bytesWritten);
                }
            }
            return ThrowHelper.TryFormatThrowFormatException(out bytesWritten);
        }
References System.destination, System.format, System.Buffers.Text.Utf8Constants.s_nullUtcOffset, System.Buffers.Text.Utf8Formatter.TryFormatDateTimeG(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeL(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO(), System.Buffers.Text.Utf8Formatter.TryFormatDateTimeR(), System.ThrowHelper.TryFormatThrowFormatException(), and System.value.