Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO
TryFormatDateTimeO()
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormatDateTimeO (DateTime value, TimeSpan offset, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 157 of file Utf8Formatter.cs.
        {
            int num = 27;
            DateTimeKind dateTimeKind = DateTimeKind.Local;
            if (offset == Utf8Constants.s_nullUtcOffset)
            {
                dateTimeKind = value.Kind;
                if (dateTimeKind == DateTimeKind.Local)
                {
                    offset = TimeZoneInfo.Local.GetUtcOffset(value);
                    num += 6;
                }
                else if (dateTimeKind == DateTimeKind.Utc)
                {
                    num++;
                }
            }
            else
            {
                num += 6;
            }
            if (destination.Length < num)
            {
                bytesWritten = 0;
                return false;
            }
            bytesWritten = num;
            ref byte ptr = ref destination[26];
            FormattingHelpers.WriteFourDecimalDigits((uint)value.Year, destination, 0);
            *destination[4] = 45;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value.Month, destination, 5);
            *destination[7] = 45;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value.Day, destination, 8);
            *destination[10] = 84;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value.Hour, destination, 11);
            *destination[13] = 58;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value.Minute, destination, 14);
            *destination[16] = 58;
            FormattingHelpers.WriteTwoDecimalDigits((uint)value.Second, destination, 17);
            *destination[19] = 46;
            FormattingHelpers.WriteDigits((uint)(value.Ticks % 10000000L), destination.Slice(20, 7));
            if (dateTimeKind == DateTimeKind.Local)
            {
                byte b;
                if (offset < default(TimeSpan))
                {
                    b = 45;
                    offset = TimeSpan.FromTicks(-offset.Ticks);
                }
                else
                {
                    b = 43;
                }
                FormattingHelpers.WriteTwoDecimalDigits((uint)offset.Minutes, destination, 31);
                *destination[30] = 58;
                FormattingHelpers.WriteTwoDecimalDigits((uint)offset.Hours, destination, 28);
                *destination[27] = b;
            }
            else if (dateTimeKind == DateTimeKind.Utc)
            {
                *destination[27] = 90;
            }
            return true;
        }
References System.destination, System.TimeSpan.FromTicks(), System.TimeZoneInfo.GetUtcOffset(), System.L, System.TimeZoneInfo.Local, System.offset, System.Buffers.Text.Utf8Constants.s_nullUtcOffset, System.value, System.Buffers.Text.FormattingHelpers.WriteDigits(), System.Buffers.Text.FormattingHelpers.WriteFourDecimalDigits(), and System.Buffers.Text.FormattingHelpers.WriteTwoDecimalDigits().
Referenced by System.Buffers.Text.Utf8Formatter.TryFormat(), and System.Buffers.Text.Utf8Formatter.TryFormat().