Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [8/16]
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormat (Guid value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 658 of file Utf8Formatter.cs.
        {
            char symbolOrDefault = FormattingHelpers.GetSymbolOrDefault(in format, 'D');
            int num;
            if (symbolOrDefault <= 'D')
            {
                if (symbolOrDefault == 'B')
                {
                    num = -2139260122;
                    goto IL_004B;
                }
                if (symbolOrDefault == 'D')
                {
                    num = -2147483612;
                    goto IL_004B;
                }
            }
            else
            {
                if (symbolOrDefault == 'N')
                {
                    num = 32;
                    goto IL_004B;
                }
                if (symbolOrDefault == 'P')
                {
                    num = -2144786394;
                    goto IL_004B;
                }
            }
            return ThrowHelper.TryFormatThrowFormatException(out bytesWritten);
            IL_004B:
            if ((int)((byte)num) > destination.Length)
            {
                bytesWritten = 0;
                return false;
            }
            bytesWritten = (int)((byte)num);
            num >>= 8;
            if ((byte)num != 0)
            {
                *destination[0] = (byte)num;
                destination = destination.Slice(1);
            }
            num >>= 8;
            Utf8Formatter.DecomposedGuid decomposedGuid = default(Utf8Formatter.DecomposedGuid);
            decomposedGuid.Guid = value;
            ref byte ptr = ref destination[8];
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte03, destination, 0, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte02, destination, 2, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte01, destination, 4, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte00, destination, 6, FormattingHelpers.HexCasing.Lowercase);
            if (num < 0)
            {
                *destination[8] = 45;
                destination = destination.Slice(9);
            }
            else
            {
                destination = destination.Slice(8);
            }
            ref byte ptr2 = ref destination[4];
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte05, destination, 0, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte04, destination, 2, FormattingHelpers.HexCasing.Lowercase);
            if (num < 0)
            {
                *destination[4] = 45;
                destination = destination.Slice(5);
            }
            else
            {
                destination = destination.Slice(4);
            }
            ref byte ptr3 = ref destination[4];
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte07, destination, 0, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte06, destination, 2, FormattingHelpers.HexCasing.Lowercase);
            if (num < 0)
            {
                *destination[4] = 45;
                destination = destination.Slice(5);
            }
            else
            {
                destination = destination.Slice(4);
            }
            ref byte ptr4 = ref destination[4];
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte08, destination, 0, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte09, destination, 2, FormattingHelpers.HexCasing.Lowercase);
            if (num < 0)
            {
                *destination[4] = 45;
                destination = destination.Slice(5);
            }
            else
            {
                destination = destination.Slice(4);
            }
            ref byte ptr5 = ref destination[11];
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte10, destination, 0, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte11, destination, 2, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte12, destination, 4, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte13, destination, 6, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte14, destination, 8, FormattingHelpers.HexCasing.Lowercase);
            FormattingHelpers.WriteHexByte(decomposedGuid.Byte15, destination, 10, FormattingHelpers.HexCasing.Lowercase);
            if ((byte)num != 0)
            {
                *destination[12] = (byte)num;
            }
            return true;
        }
References System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte00, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte01, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte02, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte03, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte04, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte05, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte06, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte07, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte08, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte09, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte10, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte11, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte12, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte13, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte14, System.Buffers.Text.Utf8Formatter.DecomposedGuid.Byte15, System.destination, System.format, System.Buffers.Text.FormattingHelpers.GetSymbolOrDefault(), int, System.ThrowHelper.TryFormatThrowFormatException(), System.value, and System.Buffers.Text.FormattingHelpers.WriteHexByte().