Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [13/16]
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormat (TimeSpan value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 1337 of file Utf8Formatter.cs.
        {
            char c = FormattingHelpers.GetSymbolOrDefault(in format, 'c');
            if (c <= 'T')
            {
                if (c == 'G')
                {
                    goto IL_0036;
                }
                if (c != 'T')
                {
                    goto IL_002F;
                }
            }
            else
            {
                if (c == 'c' || c == 'g')
                {
                    goto IL_0036;
                }
                if (c != 't')
                {
                    goto IL_002F;
                }
            }
            c = 'c';
            goto IL_0036;
            IL_002F:
            return ThrowHelper.TryFormatThrowFormatException(out bytesWritten);
            IL_0036:
            int num = 8;
            long num2 = value.Ticks;
            uint num3;
            ulong num4;
            if (num2 < 0L)
            {
                num2 = -num2;
                if (num2 < 0L)
                {
                    num3 = 4775808U;
                    num4 = 922337203685UL;
                    goto IL_0082;
                }
            }
            ulong num5;
            num4 = FormattingHelpers.DivMod((ulong)Math.Abs(value.Ticks), 10000000UL, out num5);
            num3 = (uint)num5;
            IL_0082:
            int num6 = 0;
            if (c == 'c')
            {
                if (num3 != 0U)
                {
                    num6 = 7;
                }
            }
            else if (c == 'G')
            {
                num6 = 7;
            }
            else if (num3 != 0U)
            {
                num6 = 7 - FormattingHelpers.CountDecimalTrailingZeros(num3, out num3);
            }
            if (num6 != 0)
            {
                num += num6 + 1;
            }
            ulong num7 = 0UL;
            ulong num8 = 0UL;
            if (num4 > 0UL)
            {
                num7 = FormattingHelpers.DivMod(num4, 60UL, out num8);
            }
            ulong num9 = 0UL;
            ulong num10 = 0UL;
            if (num7 > 0UL)
            {
                num9 = FormattingHelpers.DivMod(num7, 60UL, out num10);
            }
            uint num11 = 0U;
            uint num12 = 0U;
            if (num9 > 0UL)
            {
                num11 = FormattingHelpers.DivMod((uint)num9, 24U, out num12);
            }
            int num13 = 2;
            if (num12 < 10U && c == 'g')
            {
                num13--;
                num--;
            }
            int num14 = 0;
            if (num11 == 0U)
            {
                if (c == 'G')
                {
                    num += 2;
                    num14 = 1;
                }
            }
            else
            {
                num14 = FormattingHelpers.CountDigits(num11);
                num += num14 + 1;
            }
            if (value.Ticks < 0L)
            {
                num++;
            }
            if (destination.Length < num)
            {
                bytesWritten = 0;
                return false;
            }
            bytesWritten = num;
            int num15 = 0;
            if (value.Ticks < 0L)
            {
                *destination[num15++] = 45;
            }
            if (num14 > 0)
            {
                FormattingHelpers.WriteDigits(num11, destination.Slice(num15, num14));
                num15 += num14;
                *destination[num15++] = ((c == 'c') ? 46 : 58);
            }
            FormattingHelpers.WriteDigits(num12, destination.Slice(num15, num13));
            num15 += num13;
            *destination[num15++] = 58;
            FormattingHelpers.WriteDigits((uint)num10, destination.Slice(num15, 2));
            num15 += 2;
            *destination[num15++] = 58;
            FormattingHelpers.WriteDigits((uint)num8, destination.Slice(num15, 2));
            num15 += 2;
            if (num6 > 0)
            {
                *destination[num15++] = 46;
                FormattingHelpers.WriteDigits(num3, destination.Slice(num15, num6));
                num15 += num6;
            }
            return true;
        }
References System.Math.Abs(), System.Buffers.Text.FormattingHelpers.CountDecimalTrailingZeros(), System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Buffers.Text.FormattingHelpers.DivMod(), System.format, System.Buffers.Text.FormattingHelpers.GetSymbolOrDefault(), System.L, System.ThrowHelper.TryFormatThrowFormatException(), System.U, System.value, and System.Buffers.Text.FormattingHelpers.WriteDigits().