Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormatInt32MultipleDigits
TryFormatInt32MultipleDigits()
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormatInt32MultipleDigits (int value, Span< byte > destination, out int bytesWritten) inline static private
Definition at line 829 of file Utf8Formatter.cs.
        {
            if (value >= 0)
            {
                return Utf8Formatter.TryFormatUInt32MultipleDigits((uint)value, destination, out bytesWritten);
            }
            value = -value;
            int num = FormattingHelpers.CountDigits((uint)value);
            if (num >= destination.Length)
            {
                bytesWritten = 0;
                return false;
            }
            *destination[0] = 45;
            bytesWritten = num + 1;
            FormattingHelpers.WriteDigits((uint)value, destination.Slice(1, num));
            return true;
        }
References System.Buffers.Text.FormattingHelpers.CountDigits(), System.destination, System.Buffers.Text.Utf8Formatter.TryFormatUInt32MultipleDigits(), System.value, and System.Buffers.Text.FormattingHelpers.WriteDigits().
Referenced by System.Buffers.Text.Utf8Formatter.TryFormatInt32Default(), and System.Buffers.Text.Utf8Formatter.TryFormatInt64Default().