Terraria Decompiled: System.Buffers.Text.Utf8Formatter.TryFormat
TryFormat() [5/16]
static unsafe bool System.Buffers.Text.Utf8Formatter.TryFormat (decimal value, Span< byte > destination, out int bytesWritten, StandardFormat format = default(StandardFormat)) inline static
Definition at line 542 of file Utf8Formatter.cs.
        {
            if (format.IsDefault)
            {
                format = 'G';
            }
            char symbol = format.Symbol;
            switch (symbol)
            {
            case 'E':
                goto IL_00DD;
            case 'F':
                goto IL_0097;
            case 'G':
                break;
            default:
                switch (symbol)
                {
                case 'e':
                    goto IL_00DD;
                case 'f':
                    goto IL_0097;
                case 'g':
                    break;
                default:
                    return ThrowHelper.TryFormatThrowFormatException(out bytesWritten);
                }
                break;
            }
            if (format.Precision != 255)
            {
                throw new NotSupportedException("The 'G' format combined with a precision is not supported.");
            }
            NumberBuffer numberBuffer = default(NumberBuffer);
            Number.DecimalToNumber(value, ref numberBuffer);
            if (*numberBuffer.Digits[0] == 0)
            {
                numberBuffer.IsNegative = false;
            }
            return Utf8Formatter.TryFormatDecimalG(ref numberBuffer, destination, out bytesWritten);
            IL_0097:
            NumberBuffer numberBuffer2 = default(NumberBuffer);
            Number.DecimalToNumber(value, ref numberBuffer2);
            byte b = ((format.Precision == byte.MaxValue) ? 2 : format.Precision);
            Number.RoundNumber(ref numberBuffer2, numberBuffer2.Scale + (int)b);
            return Utf8Formatter.TryFormatDecimalF(ref numberBuffer2, destination, out bytesWritten, b);
            IL_00DD:
            NumberBuffer numberBuffer3 = default(NumberBuffer);
            Number.DecimalToNumber(value, ref numberBuffer3);
            byte b2 = ((format.Precision == byte.MaxValue) ? 6 : format.Precision);
            Number.RoundNumber(ref numberBuffer3, (int)(b2 + 1));
            return Utf8Formatter.TryFormatDecimalE(ref numberBuffer3, destination, out bytesWritten, b2, (byte)format.Symbol);
        }
References System.Buffers.Text.Number.DecimalToNumber(), System.destination, System.Buffers.Text.NumberBuffer.Digits, System.format, System.Buffers.Text.Number.RoundNumber(), System.Buffers.Text.NumberBuffer.Scale, System.Buffers.Text.Utf8Formatter.TryFormatDecimalE(), System.Buffers.Text.Utf8Formatter.TryFormatDecimalF(), System.Buffers.Text.Utf8Formatter.TryFormatDecimalG(), System.ThrowHelper.TryFormatThrowFormatException(), and System.value.