Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch
Lights_GenerateSwitch()
Point Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch (int x, int y) inline private
Definition at line 150 of file DungeonGlobalLights.cs.
        {
            Point zero = Point.Zero;
            for (int i = 0; i < 1000; i++)
            {
                int num = x + WorldGen.genRand.Next(-12, 13);
                int num2 = y + WorldGen.genRand.Next(3, 21);
                if (!Main.tile[num, num2].active() && !Main.tile[num, num2 + 1].active() && DungeonUtils.IsConsideredDungeonTile((int)Main.tile[num - 1, num2].type, false) && DungeonUtils.IsConsideredDungeonTile((int)Main.tile[num + 1, num2].type, false) && Collision.CanHit(new Point(num * 16, num2 * 16), 16, 16, new Point(x * 16, y * 16 + 1), 16, 16))
                {
                    if (((WorldGen.SolidTile(num - 1, num2, false) && Main.tile[num - 1, num2].type != 10) || (WorldGen.SolidTile(num + 1, num2, false) && Main.tile[num + 1, num2].type != 10) || WorldGen.SolidTile(num, num2 + 1, false)) && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num, num2].wall, false) && (DungeonUtils.IsConsideredDungeonTile((int)Main.tile[num - 1, num2].type, false) || DungeonUtils.IsConsideredDungeonTile((int)Main.tile[num + 1, num2].type, false)))
                    {
                        WorldGen.PlaceTile(num, num2, 136, true, false, -1, 0);
                        zero = new Point(num, num2);
                    }
                    if (Main.tile[num, num2].active())
                    {
                        while (num != x || num2 != y)
{
                            Main.tile[num, num2].wire(true);
                            if (num > x)
{
                                num--;
                            }
                            if (num < x)
{
                                num++;
                            }
                            Main.tile[num, num2].wire(true);
                            if (num2 > y)
{
                                num2--;
                            }
                            if (num2 < y)
{
                                num2++;
                            }
                            Main.tile[num, num2].wire(true);
                        }
                        if (WorldGen.genRand.Next(3) > 0)
{
                            Main.tile[x, y].frameX = 18;
                            Main.tile[x, y + 1].frameX = 18;
                            break;
                        }
                        break;
                    }
                }
            }
            return zero;
        }
References Terraria.Tile.active(), Terraria.Collision.CanHit(), Terraria.Tile.frameX, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wire(), and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights().