Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights
Lights()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights (DungeonData data) inline
Definition at line 29 of file DungeonGlobalLights.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            float num = (float)Main.maxTilesX / 4200f;
            int num2 = 0;
            int num3 = 1000;
            int i = 0;
            int num4 = (int)((double)(28f * num) * data.globalFeatureScalar);
            while (i < num4)
            {
                num2++;
                int num5 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                int num6 = genRand.Next(data.dungeonBounds.Top, data.dungeonBounds.Bottom);
                if (DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num5, num6].wall, false))
                {
                    for (int j = num6; j > data.dungeonBounds.Top; j--)
                    {
                        if (Main.tile[num5, j - 1].active() && DungeonUtils.IsConsideredDungeonTile((int)Main.tile[num5, j - 1].type, false) && data.CanGenerateFeatureAt(this, num5, j) && (data.dungeonEntrance.Bounds.Contains(num5, j) || DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num5, j].wall, false)))
{
                            bool flag = false;
                            for (int k = num5 - 15; k < num5 + 15; k++)
{
                                for (int l = j - 15; l < j + 15; l++)
{
                                    if (k > 0 && k < Main.maxTilesX && l > 0 && l < Main.maxTilesY && (Main.tile[k, l].type == 42 || Main.tile[k, l].type == 34))
{
                                        flag = true;
                                        break;
                                    }
                                }
                            }
                            if (Main.tile[num5 - 1, j].active() || Main.tile[num5 + 1, j].active() || Main.tile[num5 - 1, j + 1].active() || Main.tile[num5 + 1, j + 1].active() || Main.tile[num5, j + 2].active())
{
                                flag = true;
                            }
                            if (flag)
{
                                break;
                            }
                            bool flag2 = false;
                            if (!flag2 && genRand.Next(7) == 0)
{
                                bool flag3 = false;
                                for (int m = 0; m < 15; m++)
{
                                    if (WorldGen.SolidTile(num5, j + m, false))
{
                                        flag3 = true;
                                        break;
                                    }
                                }
                                if (!flag3)
{
                                    DungeonGenerationStyleData styleForWall = DungeonGenerationStyles.GetStyleForWall(data.genVars.dungeonGenerationStyles, (int)Main.tile[num5, j].wall);
                                    if (styleForWall != null && styleForWall.ChandelierItemTypes != null)
{
                                        int num7 = ((styleForWall.ChandelierItemTypes.Length == 0 || styleForWall.Style == 0) ? data.chandelierItemType : styleForWall.ChandelierItemTypes[genRand.Next(styleForWall.ChandelierItemTypes.Length)]);
                                        PlacementDetails placementDetails = ItemID.Sets.DerivedPlacementDetails[num7];
                                        if (placementDetails.tileType >= 0)
{
                                            WorldGen.PlaceChand(num5, j, (ushort)placementDetails.tileType, (int)placementDetails.tileStyle);
                                            if (Main.tile[num5, j].type == 34)
{
                                                flag2 = true;
                                                num2 = 0;
                                                i++;
                                                this.Lights_GenerateSwitch(num5, j);
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag2)
{
                                break;
                            }
                            DungeonGenerationStyleData styleForWall2 = DungeonGenerationStyles.GetStyleForWall(data.genVars.dungeonGenerationStyles, (int)Main.tile[num5, j].wall);
                            ushort num8 = 42;
                            if (styleForWall2 == null || styleForWall2.LanternItemTypes != null)
{
                                int num9;
                                if (styleForWall2 == null || styleForWall2.Style == 0 || styleForWall2.LanternItemTypes.Length == 0)
{
                                    num9 = data.lanternStyles[0];
                                    if ((int)Main.tile[num5, j].wall == data.wallVariants[1])
{
                                        num9 = data.lanternStyles[1];
                                    }
                                    if ((int)Main.tile[num5, j].wall == data.wallVariants[2])
{
                                        num9 = data.lanternStyles[2];
                                    }
                                }
                                else
{
                                    PlacementDetails placementDetails2 = ItemID.Sets.DerivedPlacementDetails[styleForWall2.LanternItemTypes[genRand.Next(styleForWall2.LanternItemTypes.Length)]];
                                    num8 = (ushort)placementDetails2.tileType;
                                    num9 = (int)placementDetails2.tileStyle;
                                }
                                WorldGen.Place1x2Top(num5, j, num8, num9);
                                if (Main.tile[num5, j].type == num8)
{
                                    num2 = 0;
                                    i++;
                                    this.Lights_GenerateSwitch(num5, j);
                                    break;
                                }
                                break;
                            }
                        }
                    }
                }
                if (num2 > num3)
                {
                    i++;
                    num2 = 0;
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt(), Terraria.GameContent.Generation.Dungeon.DungeonData.chandelierItemType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.ChandelierItemTypes, Terraria.ID.ItemID.Sets.DerivedPlacementDetails, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonEntrance, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall(), Terraria.GameContent.Generation.Dungeon.DungeonData.globalFeatureScalar, int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.LanternItemTypes, Terraria.GameContent.Generation.Dungeon.DungeonData.lanternStyles, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.PlaceChand(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.WorldGen.SolidTile(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.Main.tile, Terraria.DataStructures.PlacementDetails.tileStyle, Terraria.DataStructures.PlacementDetails.tileType, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.GameContent.Generation.Dungeon.DungeonData.wallVariants.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.GenerateFeature().