Terraria Decompiled: Terraria.GameContent.Generation.TrackGenerator.FindPath
FindPath()
bool Terraria.GameContent.Generation.TrackGenerator.FindPath (int minLength, int maxLength) inline private
Definition at line 122 of file TrackGenerator.cs.
        {
            int num = this._length;
            while (this._length < this._history.Length - 100)
            {
                TrackGenerator.TrackSlope trackSlope = ((this._history[this._length - 1].Slope == TrackGenerator.TrackSlope.Up) ? TrackGenerator.TrackSlope.Straight : TrackGenerator.TrackSlope.Down);
                this.AppendToHistory(trackSlope, TrackGenerator.TrackMode.Normal);
                TrackGenerator.TrackPlacementState trackPlacementState = this.TryRewriteHistoryToAvoidTiles();
                if (trackPlacementState == TrackGenerator.TrackPlacementState.Invalid)
                {
                    break;
                }
                num = this._length;
                TrackGenerator.TrackPlacementState trackPlacementState2 = trackPlacementState;
                while (trackPlacementState2 != TrackGenerator.TrackPlacementState.Available)
                {
                    trackPlacementState2 = this.CreateTunnel();
                    if (trackPlacementState2 == TrackGenerator.TrackPlacementState.Invalid)
                    {
                        break;
                    }
                    num = this._length;
                }
                if (this._length >= maxLength)
                {
                    break;
                }
            }
            this._length = Math.Min(maxLength, num);
            if (this._length < minLength)
            {
                return false;
            }
            this.SmoothTrack();
            return this.GetHistorySegmentPlacementState(0, this._length) != TrackGenerator.TrackPlacementState.Invalid;
        }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator._length, Terraria.GameContent.Generation.TrackGenerator.AppendToHistory(), Terraria.GameContent.Generation.TrackGenerator.CreateTunnel(), Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState(), System.Math.Min(), Terraria.GameContent.Generation.TrackGenerator.SmoothTrack(), and Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles().
Referenced by Terraria.GameContent.Generation.TrackGenerator.Place().