Terraria Decompiled: Terraria.GameContent.Generation.TrackGenerator.CreateTunnel
CreateTunnel()
TrackGenerator.TrackPlacementState Terraria.GameContent.Generation.TrackGenerator.CreateTunnel () inline private
Definition at line 160 of file TrackGenerator.cs.
        {
            TrackGenerator.TrackSlope trackSlope = TrackGenerator.TrackSlope.Straight;
            int num = 10;
            TrackGenerator.TrackPlacementState trackPlacementState = TrackGenerator.TrackPlacementState.Invalid;
            int x = (int)this._history[this._length - 1].X;
            int y = (int)this._history[this._length - 1].Y;
            for (TrackGenerator.TrackSlope trackSlope2 = TrackGenerator.TrackSlope.Up; trackSlope2 <= TrackGenerator.TrackSlope.Down; trackSlope2 += 1)
            {
                TrackGenerator.TrackPlacementState trackPlacementState2 = TrackGenerator.TrackPlacementState.Invalid;
                for (int i = 1; i < num; i++)
                {
                    trackPlacementState2 = TrackGenerator.CalculateStateForLocation(x + i * this._xDirection, y + i * (int)trackSlope2);
                    if (trackPlacementState2 == TrackGenerator.TrackPlacementState.Invalid)
                    {
                        break;
                    }
                    if (trackPlacementState2 != TrackGenerator.TrackPlacementState.Obstructed)
                    {
                        trackSlope = trackSlope2;
                        num = i;
                        trackPlacementState = trackPlacementState2;
                        break;
                    }
                }
                if (trackPlacementState != TrackGenerator.TrackPlacementState.Available && trackPlacementState2 == TrackGenerator.TrackPlacementState.Obstructed && (trackPlacementState != TrackGenerator.TrackPlacementState.Obstructed || trackSlope != TrackGenerator.TrackSlope.Straight))
                {
                    trackSlope = trackSlope2;
                    num = 10;
                    trackPlacementState = trackPlacementState2;
                }
            }
            if (this._length == 0 || !TrackGenerator.CanSlopesTouch(this._history[this._length - 1].Slope, trackSlope))
            {
                this.RewriteSlopeDirection(this._length - 1, TrackGenerator.TrackSlope.Straight);
            }
            this._history[this._length - 1].Mode = TrackGenerator.TrackMode.Tunnel;
            for (int j = 1; j < num; j++)
            {
                this.AppendToHistory(trackSlope, TrackGenerator.TrackMode.Tunnel);
            }
            return trackPlacementState;
        }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator._length, Terraria.GameContent.Generation.TrackGenerator._xDirection, Terraria.GameContent.Generation.TrackGenerator.AppendToHistory(), Terraria.GameContent.Generation.TrackGenerator.CalculateStateForLocation(), Terraria.GameContent.Generation.TrackGenerator.CanSlopesTouch(), int, Terraria.GameContent.Generation.TrackGenerator.RewriteSlopeDirection(), System.X, and System.Y.
Referenced by Terraria.GameContent.Generation.TrackGenerator.FindPath().