Terraria Decompiled: Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState
GetHistorySegmentPlacementState()
TrackGenerator.TrackPlacementState Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState (int startIndex, int length) inline private
Definition at line 272 of file TrackGenerator.cs.
        {
            TrackGenerator.TrackPlacementState trackPlacementState = TrackGenerator.TrackPlacementState.Available;
            for (int i = startIndex; i < startIndex + length; i++)
            {
                TrackGenerator.TrackPlacementState trackPlacementState2 = TrackGenerator.CalculateStateForLocation((int)this._history[i].X, (int)this._history[i].Y);
                if (trackPlacementState2 != TrackGenerator.TrackPlacementState.Obstructed)
                {
                    if (trackPlacementState2 == TrackGenerator.TrackPlacementState.Invalid)
                    {
                        return trackPlacementState2;
                    }
                }
                else if (this._history[i].Mode != TrackGenerator.TrackMode.Tunnel)
                {
                    trackPlacementState = trackPlacementState2;
                }
            }
            return trackPlacementState;
        }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator.CalculateStateForLocation(), System.length, System.startIndex, System.X, and System.Y.
Referenced by Terraria.GameContent.Generation.TrackGenerator.FindPath(), and Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles().