Terraria Decompiled: Terraria.GameContent.Generation.TrackGenerator.PlacePath
PlacePath()
void Terraria.GameContent.Generation.TrackGenerator.PlacePath () inline private
Definition at line 30 of file TrackGenerator.cs.
        {
            bool[] array = new bool[this._length];
            for (int i = 0; i < this._length; i++)
            {
                if (WorldGen.genRand.Next(7) == 0)
                {
                    this.playerHeight = WorldGen.genRand.Next(5, 9);
                }
                for (int j = 0; j < this.playerHeight; j++)
                {
                    TrackGenerator.TrackHistory trackHistory = this._history[i];
                    if (Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j - 1].wall == 244)
                    {
                        Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j - 1].wall = 0;
                    }
                    if (Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j].wall == 244)
                    {
                        Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j].wall = 0;
                    }
                    if (Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j + 1].wall == 244)
                    {
                        Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j + 1].wall = 0;
                    }
                    if (Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j].active() && Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j].type == 135)
                    {
                        array[i] = true;
                    }
                    if (Main.tile[(int)trackHistory.X, (int)trackHistory.Y - j].type != 379)
                    {
                        WorldGen.KillTile((int)trackHistory.X, (int)trackHistory.Y - j, false, false, true);
                    }
                }
            }
            for (int k = 0; k < this._length; k++)
            {
                if (WorldGen.genRand.Next(7) == 0)
                {
                    this.playerHeight = WorldGen.genRand.Next(5, 9);
                }
                TrackGenerator.TrackHistory trackHistory2 = this._history[k];
                Tile.SmoothSlope((int)trackHistory2.X, (int)(trackHistory2.Y + 1), true, false);
                if (!Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y - this.playerHeight].active() || Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y - this.playerHeight].type != 379)
                {
                    Tile.SmoothSlope((int)trackHistory2.X, (int)trackHistory2.Y - this.playerHeight, true, false);
                }
                bool flag = Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire();
                bool flag2 = Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire2();
                bool flag3 = Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire3();
                bool flag4 = Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire4();
                if (array[k] && k < this._length && k > 0 && this._history[k - 1].Y == trackHistory2.Y && this._history[k + 1].Y == trackHistory2.Y)
                {
                    Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].ClearEverything();
                    WorldGen.PlaceTile((int)trackHistory2.X, (int)trackHistory2.Y, 314, false, true, -1, 1);
                }
                else
                {
                    Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].ResetToType(314);
                }
                Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire(flag);
                Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire2(flag2);
                Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire3(flag3);
                Main.tile[(int)trackHistory2.X, (int)trackHistory2.Y].wire4(flag4);
                if (k != 0)
                {
                    for (int l = 0; l < 8; l++)
                    {
                        WorldUtils.TileFrame((int)this._history[k - 1].X, (int)this._history[k - 1].Y - l, true);
                    }
                    if (k == this._length - 1)
                    {
                        for (int m = 0; m < this.playerHeight; m++)
{
                            WorldUtils.TileFrame((int)trackHistory2.X, (int)trackHistory2.Y - m, true);
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator._length, Terraria.Tile.active(), System.array, Terraria.Tile.ClearEverything(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.KillTile(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Generation.TrackGenerator.playerHeight, Terraria.Tile.ResetToType(), Terraria.Tile.SmoothSlope(), Terraria.Main.tile, Terraria.WorldBuilding.WorldUtils.TileFrame(), Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), Terraria.Tile.wire4(), Terraria.GameContent.Generation.TrackGenerator.TrackHistory.X, System.Y, and Terraria.GameContent.Generation.TrackGenerator.TrackHistory.Y.
Referenced by Terraria.GameContent.Generation.TrackGenerator.Place().