Terraria Decompiled: Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid
IsLocationInvalid()
static bool Terraria.GameContent.Generation.TrackGenerator.IsLocationInvalid (int x, int y) inline static private
Definition at line 389 of file TrackGenerator.cs.
        {
            if (y > Main.UnderworldLayer || x < 5 || y < (int)Main.worldSurface || x > Main.maxTilesX - 5)
            {
                return true;
            }
            if (Math.Abs((double)x - GenVars.shimmerPosition.X) < (double)(WorldGen.shimmerSafetyDistance / 2) && Math.Abs((double)y - GenVars.shimmerPosition.Y) < (double)(WorldGen.shimmerSafetyDistance / 2))
            {
                return true;
            }
            if (WorldGen.oceanDepths(x, y))
            {
                return true;
            }
            if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(x, y, 0, false))
            {
                return true;
            }
            ushort wall = Main.tile[x, y].wall;
            for (int i = 0; i < TrackGenerator.InvalidWalls.Length; i++)
            {
                if (wall == TrackGenerator.InvalidWalls[i] && (!WorldGen.notTheBees || wall != 108))
                {
                    return true;
                }
            }
            int num = (Main.tile[x, y].active() ? ((int)Main.tile[x, y].type) : (-1));
            for (int j = 0; j < TrackGenerator.InvalidTiles.Length; j++)
            {
                if (num == (int)TrackGenerator.InvalidTiles[j])
                {
                    return true;
                }
            }
            for (int k = -1; k <= 1; k++)
            {
                if (Main.tile[x + k, y].active() && (Main.tile[x + k, y].type == 314 || !TileID.Sets.GeneralPlacementTiles[(int)Main.tile[x + k, y].type]) && (!WorldGen.notTheBees || Main.tile[x + k, y].type != 225))
                {
                    return true;
                }
            }
            return false;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.ID.TileID.Sets.GeneralPlacementTiles, Terraria.GameContent.Generation.Dungeon.DungeonUtils.InAnyPotentialDungeonBounds(), int, Terraria.GameContent.Generation.TrackGenerator.InvalidTiles, Terraria.GameContent.Generation.TrackGenerator.InvalidWalls, Terraria.Main.maxTilesX, Terraria.WorldGen.notTheBees, Terraria.WorldGen.oceanDepths(), Terraria.WorldBuilding.GenVars.shimmerPosition, Terraria.WorldGen.shimmerSafetyDistance, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Generation.TrackGenerator.CalculateStateForLocation().