Terraria Decompiled: Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles
TryRewriteHistoryToAvoidTiles()
TrackGenerator.TrackPlacementState Terraria.GameContent.Generation.TrackGenerator.TryRewriteHistoryToAvoidTiles () inline private
Definition at line 213 of file TrackGenerator.cs.
        {
            int i = this._length - 1;
            int num = Math.Min(this._length, this._rewriteHistory.Length);
            for (int j = 0; j < num; j++)
            {
                this._rewriteHistory[j] = this._history[i - j];
            }
            while (i >= this._length - num)
            {
                if (this._history[i].Slope == TrackGenerator.TrackSlope.Down)
                {
                    TrackGenerator.TrackPlacementState historySegmentPlacementState = this.GetHistorySegmentPlacementState(i, this._length - i);
                    if (historySegmentPlacementState == TrackGenerator.TrackPlacementState.Available)
                    {
                        return historySegmentPlacementState;
                    }
                    this.RewriteSlopeDirection(i, TrackGenerator.TrackSlope.Straight);
                }
                i--;
            }
            if (this.GetHistorySegmentPlacementState(i + 1, this._length - (i + 1)) == TrackGenerator.TrackPlacementState.Available)
            {
                return TrackGenerator.TrackPlacementState.Available;
            }
            for (i = this._length - 1; i >= this._length - num + 1; i--)
            {
                if (this._history[i].Slope == TrackGenerator.TrackSlope.Straight)
                {
                    TrackGenerator.TrackPlacementState historySegmentPlacementState2 = this.GetHistorySegmentPlacementState(this._length - num, num);
                    if (historySegmentPlacementState2 == TrackGenerator.TrackPlacementState.Available)
                    {
                        return historySegmentPlacementState2;
                    }
                    this.RewriteSlopeDirection(i, TrackGenerator.TrackSlope.Up);
                }
            }
            for (int k = 0; k < num; k++)
            {
                this._history[this._length - 1 - k] = this._rewriteHistory[k];
            }
            this.RewriteSlopeDirection(this._length - 1, TrackGenerator.TrackSlope.Straight);
            return this.GetHistorySegmentPlacementState(i + 1, this._length - (i + 1));
        }
References Terraria.GameContent.Generation.TrackGenerator._history, Terraria.GameContent.Generation.TrackGenerator._length, Terraria.GameContent.Generation.TrackGenerator._rewriteHistory, Terraria.GameContent.Generation.TrackGenerator.GetHistorySegmentPlacementState(), System.Math.Min(), and Terraria.GameContent.Generation.TrackGenerator.RewriteSlopeDirection().
Referenced by Terraria.GameContent.Generation.TrackGenerator.FindPath().