Terraria Decompiled: System.Threading.LazyInitializer.EnsureInitializedCore< T >
EnsureInitializedCore< T >() [3/5]
static T System.Threading.LazyInitializer.EnsureInitializedCore< T > (ref T target, ref bool initialized, ref object syncLock) inline static private
Definition at line 67 of file LazyInitializer.cs.
        {
            object obj = LazyInitializer.EnsureLockInitialized(ref syncLock);
            lock (obj)
            {
                if (!Volatile.Read(ref initialized))
                {
                    try
                    {
                        target = Activator.CreateInstance<T>();
                    }
                    catch (MissingMethodException)
                    {
                        throw new MissingMemberException("The lazily-initialized type does not have a public, parameterless constructor.");
                    }
                    Volatile.Write(ref initialized, true);
                }
            }
            return target;
        }
References System.Activator.CreateInstance(), System.Threading.LazyInitializer.EnsureLockInitialized(), System.obj, System.Threading.Volatile.Read(), and System.Threading.Volatile.Write().