Terraria Decompiled: System.Numerics.Vector.DotProduct
DotProduct()
static T System.Numerics.Vector< T >.DotProduct (Vector< T > left, Vector< T > right) inline static package
Definition at line 4314 of file Vector.cs.
        {
            if (Vector.IsHardwareAccelerated)
            {
                T t = default(T);
                for (int i = 0; i < Vector<T>.Count; i++)
                {
                    t = Vector<T>.ScalarAdd(t, Vector<T>.ScalarMultiply(left[i], right[i]));
                }
                return t;
            }
            if (typeof(T) == typeof(byte))
            {
                return (T)((object)(0 + left.register.byte_0 * right.register.byte_0 + left.register.byte_1 * right.register.byte_1 + left.register.byte_2 * right.register.byte_2 + left.register.byte_3 * right.register.byte_3 + left.register.byte_4 * right.register.byte_4 + left.register.byte_5 * right.register.byte_5 + left.register.byte_6 * right.register.byte_6 + left.register.byte_7 * right.register.byte_7 + left.register.byte_8 * right.register.byte_8 + left.register.byte_9 * right.register.byte_9 + left.register.byte_10 * right.register.byte_10 + left.register.byte_11 * right.register.byte_11 + left.register.byte_12 * right.register.byte_12 + left.register.byte_13 * right.register.byte_13 + left.register.byte_14 * right.register.byte_14 + left.register.byte_15 * right.register.byte_15));
            }
            if (typeof(T) == typeof(sbyte))
            {
                return (T)((object)(0 + left.register.sbyte_0 * right.register.sbyte_0 + left.register.sbyte_1 * right.register.sbyte_1 + left.register.sbyte_2 * right.register.sbyte_2 + left.register.sbyte_3 * right.register.sbyte_3 + left.register.sbyte_4 * right.register.sbyte_4 + left.register.sbyte_5 * right.register.sbyte_5 + left.register.sbyte_6 * right.register.sbyte_6 + left.register.sbyte_7 * right.register.sbyte_7 + left.register.sbyte_8 * right.register.sbyte_8 + left.register.sbyte_9 * right.register.sbyte_9 + left.register.sbyte_10 * right.register.sbyte_10 + left.register.sbyte_11 * right.register.sbyte_11 + left.register.sbyte_12 * right.register.sbyte_12 + left.register.sbyte_13 * right.register.sbyte_13 + left.register.sbyte_14 * right.register.sbyte_14 + left.register.sbyte_15 * right.register.sbyte_15));
            }
            if (typeof(T) == typeof(ushort))
            {
                return (T)((object)(0 + left.register.uint16_0 * right.register.uint16_0 + left.register.uint16_1 * right.register.uint16_1 + left.register.uint16_2 * right.register.uint16_2 + left.register.uint16_3 * right.register.uint16_3 + left.register.uint16_4 * right.register.uint16_4 + left.register.uint16_5 * right.register.uint16_5 + left.register.uint16_6 * right.register.uint16_6 + left.register.uint16_7 * right.register.uint16_7));
            }
            if (typeof(T) == typeof(short))
            {
                return (T)((object)(0 + left.register.int16_0 * right.register.int16_0 + left.register.int16_1 * right.register.int16_1 + left.register.int16_2 * right.register.int16_2 + left.register.int16_3 * right.register.int16_3 + left.register.int16_4 * right.register.int16_4 + left.register.int16_5 * right.register.int16_5 + left.register.int16_6 * right.register.int16_6 + left.register.int16_7 * right.register.int16_7));
            }
            if (typeof(T) == typeof(uint))
            {
                return (T)((object)(0U + left.register.uint32_0 * right.register.uint32_0 + left.register.uint32_1 * right.register.uint32_1 + left.register.uint32_2 * right.register.uint32_2 + left.register.uint32_3 * right.register.uint32_3));
            }
            if (typeof(T) == typeof(int))
            {
                return (T)((object)(0 + left.register.int32_0 * right.register.int32_0 + left.register.int32_1 * right.register.int32_1 + left.register.int32_2 * right.register.int32_2 + left.register.int32_3 * right.register.int32_3));
            }
            if (typeof(T) == typeof(ulong))
            {
                return (T)((object)(0UL + left.register.uint64_0 * right.register.uint64_0 + left.register.uint64_1 * right.register.uint64_1));
            }
            if (typeof(T) == typeof(long))
            {
                return (T)((object)(0L + left.register.int64_0 * right.register.int64_0 + left.register.int64_1 * right.register.int64_1));
            }
            if (typeof(T) == typeof(float))
            {
                return (T)((object)(0f + left.register.single_0 * right.register.single_0 + left.register.single_1 * right.register.single_1 + left.register.single_2 * right.register.single_2 + left.register.single_3 * right.register.single_3));
            }
            if (typeof(T) == typeof(double))
            {
                return (T)((object)(0.0 + left.register.double_0 * right.register.double_0 + left.register.double_1 * right.register.double_1));
            }
            throw new NotSupportedException("Specified type is not supported");
        }
References System.Numerics.Register.byte_0, System.Numerics.Register.byte_1, System.Numerics.Register.byte_10, System.Numerics.Register.byte_11, System.Numerics.Register.byte_12, System.Numerics.Register.byte_13, System.Numerics.Register.byte_14, System.Numerics.Register.byte_15, System.Numerics.Register.byte_2, System.Numerics.Register.byte_3, System.Numerics.Register.byte_4, System.Numerics.Register.byte_5, System.Numerics.Register.byte_6, System.Numerics.Register.byte_7, System.Numerics.Register.byte_8, System.Numerics.Register.byte_9, System.Numerics.Register.double_0, System.Numerics.Register.double_1, System.Numerics.Register.int16_0, System.Numerics.Register.int16_1, System.Numerics.Register.int16_2, System.Numerics.Register.int16_3, System.Numerics.Register.int16_4, System.Numerics.Register.int16_5, System.Numerics.Register.int16_6, System.Numerics.Register.int16_7, System.Numerics.Register.int32_0, System.Numerics.Register.int32_1, System.Numerics.Register.int32_2, System.Numerics.Register.int32_3, System.Numerics.Register.int64_0, System.Numerics.Register.int64_1, System.Numerics.Vector< T >.IsHardwareAccelerated, System.L, System.Numerics.Vector< T >.register, System.Numerics.Register.sbyte_0, System.Numerics.Register.sbyte_1, System.Numerics.Register.sbyte_10, System.Numerics.Register.sbyte_11, System.Numerics.Register.sbyte_12, System.Numerics.Register.sbyte_13, System.Numerics.Register.sbyte_14, System.Numerics.Register.sbyte_15, System.Numerics.Register.sbyte_2, System.Numerics.Register.sbyte_3, System.Numerics.Register.sbyte_4, System.Numerics.Register.sbyte_5, System.Numerics.Register.sbyte_6, System.Numerics.Register.sbyte_7, System.Numerics.Register.sbyte_8, System.Numerics.Register.sbyte_9, System.Numerics.Vector< T >.ScalarAdd(), System.Numerics.Vector< T >.ScalarMultiply(), System.Numerics.Register.single_0, System.Numerics.Register.single_1, System.Numerics.Register.single_2, System.Numerics.Register.single_3, System.U, System.Numerics.Register.uint16_0, System.Numerics.Register.uint16_1, System.Numerics.Register.uint16_2, System.Numerics.Register.uint16_3, System.Numerics.Register.uint16_4, System.Numerics.Register.uint16_5, System.Numerics.Register.uint16_6, System.Numerics.Register.uint16_7, System.Numerics.Register.uint32_0, System.Numerics.Register.uint32_1, System.Numerics.Register.uint32_2, System.Numerics.Register.uint32_3, System.Numerics.Register.uint64_0, and System.Numerics.Register.uint64_1.
Referenced by System.Numerics.Vector< T >.Dot< T >().