Terraria Decompiled: System.Numerics.Vector.GreaterThan
GreaterThan() [5/5]
static unsafe Vector< T > System.Numerics.Vector< T >.GreaterThan (Vector< T > left, Vector< T > right) inline static package
Definition at line 3400 of file Vector.cs.
        {
            if (Vector.IsHardwareAccelerated)
            {
                if (typeof(T) == typeof(byte))
                {
                    byte* ptr = stackalloc byte[(UIntPtr)Vector<T>.Count];
                    for (int i = 0; i < Vector<T>.Count; i++)
                    {
                        ptr[i] = (Vector<T>.ScalarGreaterThan(left[i], right[i]) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    }
                    return new Vector<T>((void*)ptr);
                }
                if (typeof(T) == typeof(sbyte))
                {
                    sbyte* ptr2 = stackalloc sbyte[(UIntPtr)Vector<T>.Count];
                    for (int j = 0; j < Vector<T>.Count; j++)
                    {
                        ptr2[j] = (Vector<T>.ScalarGreaterThan(left[j], right[j]) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    }
                    return new Vector<T>((void*)ptr2);
                }
                if (typeof(T) == typeof(ushort))
                {
                    ushort* ptr3;
                    checked
                    {
                        ptr3 = stackalloc ushort[unchecked((UIntPtr)Vector<T>.Count) * 2];
                    }
                    for (int k = 0; k < Vector<T>.Count; k++)
                    {
                        ptr3[k] = (Vector<T>.ScalarGreaterThan(left[k], right[k]) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    }
                    return new Vector<T>((void*)ptr3);
                }
                if (typeof(T) == typeof(short))
                {
                    short* ptr4;
                    checked
                    {
                        ptr4 = stackalloc short[unchecked((UIntPtr)Vector<T>.Count) * 2];
                    }
                    for (int l = 0; l < Vector<T>.Count; l++)
                    {
                        ptr4[l] = (Vector<T>.ScalarGreaterThan(left[l], right[l]) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    }
                    return new Vector<T>((void*)ptr4);
                }
                if (typeof(T) == typeof(uint))
                {
                    uint* ptr5;
                    checked
                    {
                        ptr5 = stackalloc uint[unchecked((UIntPtr)Vector<T>.Count) * 4];
                    }
                    for (int m = 0; m < Vector<T>.Count; m++)
                    {
                        ptr5[m] = (Vector<T>.ScalarGreaterThan(left[m], right[m]) ? ConstantHelper.GetUInt32WithAllBitsSet() : 0U);
                    }
                    return new Vector<T>((void*)ptr5);
                }
                if (typeof(T) == typeof(int))
                {
                    int* ptr6;
                    checked
                    {
                        ptr6 = stackalloc int[unchecked((UIntPtr)Vector<T>.Count) * 4];
                    }
                    for (int n = 0; n < Vector<T>.Count; n++)
                    {
                        ptr6[n] = (Vector<T>.ScalarGreaterThan(left[n], right[n]) ? ConstantHelper.GetInt32WithAllBitsSet() : 0);
                    }
                    return new Vector<T>((void*)ptr6);
                }
                if (typeof(T) == typeof(ulong))
                {
                    ulong* ptr7;
                    checked
                    {
                        ptr7 = stackalloc ulong[unchecked((UIntPtr)Vector<T>.Count) * 8];
                    }
                    for (int num = 0; num < Vector<T>.Count; num++)
                    {
                        ptr7[num] = (Vector<T>.ScalarGreaterThan(left[num], right[num]) ? ConstantHelper.GetUInt64WithAllBitsSet() : 0UL);
                    }
                    return new Vector<T>((void*)ptr7);
                }
                if (typeof(T) == typeof(long))
                {
                    long* ptr8;
                    checked
                    {
                        ptr8 = stackalloc long[unchecked((UIntPtr)Vector<T>.Count) * 8];
                    }
                    for (int num2 = 0; num2 < Vector<T>.Count; num2++)
                    {
                        ptr8[num2] = (Vector<T>.ScalarGreaterThan(left[num2], right[num2]) ? ConstantHelper.GetInt64WithAllBitsSet() : 0L);
                    }
                    return new Vector<T>((void*)ptr8);
                }
                if (typeof(T) == typeof(float))
                {
                    float* ptr9;
                    checked
                    {
                        ptr9 = stackalloc float[unchecked((UIntPtr)Vector<T>.Count) * 4];
                    }
                    for (int num3 = 0; num3 < Vector<T>.Count; num3++)
                    {
                        ptr9[num3] = (Vector<T>.ScalarGreaterThan(left[num3], right[num3]) ? ConstantHelper.GetSingleWithAllBitsSet() : 0f);
                    }
                    return new Vector<T>((void*)ptr9);
                }
                if (typeof(T) == typeof(double))
                {
                    double* ptr10;
                    checked
                    {
                        ptr10 = stackalloc double[unchecked((UIntPtr)Vector<T>.Count) * 8];
                    }
                    for (int num4 = 0; num4 < Vector<T>.Count; num4++)
                    {
                        ptr10[num4] = (Vector<T>.ScalarGreaterThan(left[num4], right[num4]) ? ConstantHelper.GetDoubleWithAllBitsSet() : 0.0);
                    }
                    return new Vector<T>((void*)ptr10);
                }
                throw new NotSupportedException("Specified type is not supported");
            }
            else
            {
                Register register = default(Register);
                if (typeof(T) == typeof(byte))
                {
                    register.byte_0 = ((left.register.byte_0 > right.register.byte_0) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_1 = ((left.register.byte_1 > right.register.byte_1) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_2 = ((left.register.byte_2 > right.register.byte_2) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_3 = ((left.register.byte_3 > right.register.byte_3) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_4 = ((left.register.byte_4 > right.register.byte_4) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_5 = ((left.register.byte_5 > right.register.byte_5) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_6 = ((left.register.byte_6 > right.register.byte_6) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_7 = ((left.register.byte_7 > right.register.byte_7) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_8 = ((left.register.byte_8 > right.register.byte_8) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_9 = ((left.register.byte_9 > right.register.byte_9) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_10 = ((left.register.byte_10 > right.register.byte_10) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_11 = ((left.register.byte_11 > right.register.byte_11) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_12 = ((left.register.byte_12 > right.register.byte_12) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_13 = ((left.register.byte_13 > right.register.byte_13) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_14 = ((left.register.byte_14 > right.register.byte_14) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    register.byte_15 = ((left.register.byte_15 > right.register.byte_15) ? ConstantHelper.GetByteWithAllBitsSet() : 0);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(sbyte))
                {
                    register.sbyte_0 = ((left.register.sbyte_0 > right.register.sbyte_0) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_1 = ((left.register.sbyte_1 > right.register.sbyte_1) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_2 = ((left.register.sbyte_2 > right.register.sbyte_2) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_3 = ((left.register.sbyte_3 > right.register.sbyte_3) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_4 = ((left.register.sbyte_4 > right.register.sbyte_4) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_5 = ((left.register.sbyte_5 > right.register.sbyte_5) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_6 = ((left.register.sbyte_6 > right.register.sbyte_6) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_7 = ((left.register.sbyte_7 > right.register.sbyte_7) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_8 = ((left.register.sbyte_8 > right.register.sbyte_8) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_9 = ((left.register.sbyte_9 > right.register.sbyte_9) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_10 = ((left.register.sbyte_10 > right.register.sbyte_10) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_11 = ((left.register.sbyte_11 > right.register.sbyte_11) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_12 = ((left.register.sbyte_12 > right.register.sbyte_12) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_13 = ((left.register.sbyte_13 > right.register.sbyte_13) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_14 = ((left.register.sbyte_14 > right.register.sbyte_14) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    register.sbyte_15 = ((left.register.sbyte_15 > right.register.sbyte_15) ? ConstantHelper.GetSByteWithAllBitsSet() : 0);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(ushort))
                {
                    register.uint16_0 = ((left.register.uint16_0 > right.register.uint16_0) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_1 = ((left.register.uint16_1 > right.register.uint16_1) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_2 = ((left.register.uint16_2 > right.register.uint16_2) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_3 = ((left.register.uint16_3 > right.register.uint16_3) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_4 = ((left.register.uint16_4 > right.register.uint16_4) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_5 = ((left.register.uint16_5 > right.register.uint16_5) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_6 = ((left.register.uint16_6 > right.register.uint16_6) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    register.uint16_7 = ((left.register.uint16_7 > right.register.uint16_7) ? ConstantHelper.GetUInt16WithAllBitsSet() : 0);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(short))
                {
                    register.int16_0 = ((left.register.int16_0 > right.register.int16_0) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_1 = ((left.register.int16_1 > right.register.int16_1) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_2 = ((left.register.int16_2 > right.register.int16_2) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_3 = ((left.register.int16_3 > right.register.int16_3) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_4 = ((left.register.int16_4 > right.register.int16_4) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_5 = ((left.register.int16_5 > right.register.int16_5) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_6 = ((left.register.int16_6 > right.register.int16_6) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    register.int16_7 = ((left.register.int16_7 > right.register.int16_7) ? ConstantHelper.GetInt16WithAllBitsSet() : 0);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(uint))
                {
                    register.uint32_0 = ((left.register.uint32_0 > right.register.uint32_0) ? ConstantHelper.GetUInt32WithAllBitsSet() : 0U);
                    register.uint32_1 = ((left.register.uint32_1 > right.register.uint32_1) ? ConstantHelper.GetUInt32WithAllBitsSet() : 0U);
                    register.uint32_2 = ((left.register.uint32_2 > right.register.uint32_2) ? ConstantHelper.GetUInt32WithAllBitsSet() : 0U);
                    register.uint32_3 = ((left.register.uint32_3 > right.register.uint32_3) ? ConstantHelper.GetUInt32WithAllBitsSet() : 0U);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(int))
                {
                    register.int32_0 = ((left.register.int32_0 > right.register.int32_0) ? ConstantHelper.GetInt32WithAllBitsSet() : 0);
                    register.int32_1 = ((left.register.int32_1 > right.register.int32_1) ? ConstantHelper.GetInt32WithAllBitsSet() : 0);
                    register.int32_2 = ((left.register.int32_2 > right.register.int32_2) ? ConstantHelper.GetInt32WithAllBitsSet() : 0);
                    register.int32_3 = ((left.register.int32_3 > right.register.int32_3) ? ConstantHelper.GetInt32WithAllBitsSet() : 0);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(ulong))
                {
                    register.uint64_0 = ((left.register.uint64_0 > right.register.uint64_0) ? ConstantHelper.GetUInt64WithAllBitsSet() : 0UL);
                    register.uint64_1 = ((left.register.uint64_1 > right.register.uint64_1) ? ConstantHelper.GetUInt64WithAllBitsSet() : 0UL);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(long))
                {
                    register.int64_0 = ((left.register.int64_0 > right.register.int64_0) ? ConstantHelper.GetInt64WithAllBitsSet() : 0L);
                    register.int64_1 = ((left.register.int64_1 > right.register.int64_1) ? ConstantHelper.GetInt64WithAllBitsSet() : 0L);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(float))
                {
                    register.single_0 = ((left.register.single_0 > right.register.single_0) ? ConstantHelper.GetSingleWithAllBitsSet() : 0f);
                    register.single_1 = ((left.register.single_1 > right.register.single_1) ? ConstantHelper.GetSingleWithAllBitsSet() : 0f);
                    register.single_2 = ((left.register.single_2 > right.register.single_2) ? ConstantHelper.GetSingleWithAllBitsSet() : 0f);
                    register.single_3 = ((left.register.single_3 > right.register.single_3) ? ConstantHelper.GetSingleWithAllBitsSet() : 0f);
                    return new Vector<T>(ref register);
                }
                if (typeof(T) == typeof(double))
                {
                    register.double_0 = ((left.register.double_0 > right.register.double_0) ? ConstantHelper.GetDoubleWithAllBitsSet() : 0.0);
                    register.double_1 = ((left.register.double_1 > right.register.double_1) ? ConstantHelper.GetDoubleWithAllBitsSet() : 0.0);
                    return new Vector<T>(ref register);
                }
                throw new NotSupportedException("Specified type is not supported");
            }
        }
References System.Numerics.Register.byte_0, System.Numerics.Register.byte_1, System.Numerics.Register.byte_10, System.Numerics.Register.byte_11, System.Numerics.Register.byte_12, System.Numerics.Register.byte_13, System.Numerics.Register.byte_14, System.Numerics.Register.byte_15, System.Numerics.Register.byte_2, System.Numerics.Register.byte_3, System.Numerics.Register.byte_4, System.Numerics.Register.byte_5, System.Numerics.Register.byte_6, System.Numerics.Register.byte_7, System.Numerics.Register.byte_8, System.Numerics.Register.byte_9, System.Numerics.Vector< T >.Count, System.Numerics.Register.double_0, System.Numerics.Register.double_1, System.Numerics.ConstantHelper.GetByteWithAllBitsSet(), System.Numerics.ConstantHelper.GetDoubleWithAllBitsSet(), System.Numerics.ConstantHelper.GetInt16WithAllBitsSet(), System.Numerics.ConstantHelper.GetInt32WithAllBitsSet(), System.Numerics.ConstantHelper.GetInt64WithAllBitsSet(), System.Numerics.ConstantHelper.GetSByteWithAllBitsSet(), System.Numerics.ConstantHelper.GetSingleWithAllBitsSet(), System.Numerics.ConstantHelper.GetUInt16WithAllBitsSet(), System.Numerics.ConstantHelper.GetUInt32WithAllBitsSet(), System.Numerics.ConstantHelper.GetUInt64WithAllBitsSet(), System.Numerics.Register.int16_0, System.Numerics.Register.int16_1, System.Numerics.Register.int16_2, System.Numerics.Register.int16_3, System.Numerics.Register.int16_4, System.Numerics.Register.int16_5, System.Numerics.Register.int16_6, System.Numerics.Register.int16_7, System.Numerics.Register.int32_0, System.Numerics.Register.int32_1, System.Numerics.Register.int32_2, System.Numerics.Register.int32_3, System.Numerics.Register.int64_0, System.Numerics.Register.int64_1, System.Numerics.Vector< T >.IsHardwareAccelerated, System.L, System.Numerics.Vector< T >.register, System.Numerics.Register.sbyte_0, System.Numerics.Register.sbyte_1, System.Numerics.Register.sbyte_10, System.Numerics.Register.sbyte_11, System.Numerics.Register.sbyte_12, System.Numerics.Register.sbyte_13, System.Numerics.Register.sbyte_14, System.Numerics.Register.sbyte_15, System.Numerics.Register.sbyte_2, System.Numerics.Register.sbyte_3, System.Numerics.Register.sbyte_4, System.Numerics.Register.sbyte_5, System.Numerics.Register.sbyte_6, System.Numerics.Register.sbyte_7, System.Numerics.Register.sbyte_8, System.Numerics.Register.sbyte_9, System.Numerics.Vector< T >.ScalarGreaterThan(), System.Numerics.Register.single_0, System.Numerics.Register.single_1, System.Numerics.Register.single_2, System.Numerics.Register.single_3, System.U, System.Numerics.Register.uint16_0, System.Numerics.Register.uint16_1, System.Numerics.Register.uint16_2, System.Numerics.Register.uint16_3, System.Numerics.Register.uint16_4, System.Numerics.Register.uint16_5, System.Numerics.Register.uint16_6, System.Numerics.Register.uint16_7, System.Numerics.Register.uint32_0, System.Numerics.Register.uint32_1, System.Numerics.Register.uint32_2, System.Numerics.Register.uint32_3, System.Numerics.Register.uint64_0, and System.Numerics.Register.uint64_1.