Terraria Decompiled: System.Numerics.Vector.GetAllBitsSetValue
GetAllBitsSetValue()
static T System.Numerics.Vector< T >.GetAllBitsSetValue () inline static private
Definition at line 4988 of file Vector.cs.
        {
            if (typeof(T) == typeof(byte))
            {
                return (T)((object)ConstantHelper.GetByteWithAllBitsSet());
            }
            if (typeof(T) == typeof(sbyte))
            {
                return (T)((object)ConstantHelper.GetSByteWithAllBitsSet());
            }
            if (typeof(T) == typeof(ushort))
            {
                return (T)((object)ConstantHelper.GetUInt16WithAllBitsSet());
            }
            if (typeof(T) == typeof(short))
            {
                return (T)((object)ConstantHelper.GetInt16WithAllBitsSet());
            }
            if (typeof(T) == typeof(uint))
            {
                return (T)((object)ConstantHelper.GetUInt32WithAllBitsSet());
            }
            if (typeof(T) == typeof(int))
            {
                return (T)((object)ConstantHelper.GetInt32WithAllBitsSet());
            }
            if (typeof(T) == typeof(ulong))
            {
                return (T)((object)ConstantHelper.GetUInt64WithAllBitsSet());
            }
            if (typeof(T) == typeof(long))
            {
                return (T)((object)ConstantHelper.GetInt64WithAllBitsSet());
            }
            if (typeof(T) == typeof(float))
            {
                return (T)((object)ConstantHelper.GetSingleWithAllBitsSet());
            }
            if (typeof(T) == typeof(double))
            {
                return (T)((object)ConstantHelper.GetDoubleWithAllBitsSet());
            }
            throw new NotSupportedException("Specified type is not supported");
        }
References System.Numerics.ConstantHelper.GetByteWithAllBitsSet(), System.Numerics.ConstantHelper.GetDoubleWithAllBitsSet(), System.Numerics.ConstantHelper.GetInt16WithAllBitsSet(), System.Numerics.ConstantHelper.GetInt32WithAllBitsSet(), System.Numerics.ConstantHelper.GetInt64WithAllBitsSet(), System.Numerics.ConstantHelper.GetSByteWithAllBitsSet(), System.Numerics.ConstantHelper.GetSingleWithAllBitsSet(), System.Numerics.ConstantHelper.GetUInt16WithAllBitsSet(), System.Numerics.ConstantHelper.GetUInt32WithAllBitsSet(), and System.Numerics.ConstantHelper.GetUInt64WithAllBitsSet().