Terraria Decompiled: System.Numerics.Vector.GetHashCode
GetHashCode()
override int System.Numerics.Vector< T >.GetHashCode () inline
Definition at line 1391 of file Vector.cs.
        {
            int num = 0;
            if (Vector.IsHardwareAccelerated)
            {
                if (typeof(T) == typeof(byte))
                {
                    for (int i = 0; i < Vector<T>.Count; i++)
                    {
                        num = HashHelpers.Combine(num, ((byte)((object)this[i])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(sbyte))
                {
                    for (int j = 0; j < Vector<T>.Count; j++)
                    {
                        num = HashHelpers.Combine(num, ((sbyte)((object)this[j])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(ushort))
                {
                    for (int k = 0; k < Vector<T>.Count; k++)
                    {
                        num = HashHelpers.Combine(num, ((ushort)((object)this[k])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(short))
                {
                    for (int l = 0; l < Vector<T>.Count; l++)
                    {
                        num = HashHelpers.Combine(num, ((short)((object)this[l])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(uint))
                {
                    for (int m = 0; m < Vector<T>.Count; m++)
                    {
                        num = HashHelpers.Combine(num, ((uint)((object)this[m])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(int))
                {
                    for (int n = 0; n < Vector<T>.Count; n++)
                    {
                        num = HashHelpers.Combine(num, ((int)((object)this[n])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(ulong))
                {
                    for (int num2 = 0; num2 < Vector<T>.Count; num2++)
                    {
                        num = HashHelpers.Combine(num, ((ulong)((object)this[num2])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(long))
                {
                    for (int num3 = 0; num3 < Vector<T>.Count; num3++)
                    {
                        num = HashHelpers.Combine(num, ((long)((object)this[num3])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(float))
                {
                    for (int num4 = 0; num4 < Vector<T>.Count; num4++)
                    {
                        num = HashHelpers.Combine(num, ((float)((object)this[num4])).GetHashCode());
                    }
                    return num;
                }
                if (typeof(T) == typeof(double))
                {
                    for (int num5 = 0; num5 < Vector<T>.Count; num5++)
                    {
                        num = HashHelpers.Combine(num, ((double)((object)this[num5])).GetHashCode());
                    }
                    return num;
                }
                throw new NotSupportedException("Specified type is not supported");
            }
            else
            {
                if (typeof(T) == typeof(byte))
                {
                    num = HashHelpers.Combine(num, this.register.byte_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_2.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_3.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_4.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_5.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_6.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_7.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_8.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_9.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_10.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_11.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_12.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_13.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.byte_14.GetHashCode());
                    return HashHelpers.Combine(num, this.register.byte_15.GetHashCode());
                }
                if (typeof(T) == typeof(sbyte))
                {
                    num = HashHelpers.Combine(num, this.register.sbyte_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_2.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_3.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_4.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_5.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_6.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_7.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_8.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_9.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_10.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_11.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_12.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_13.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.sbyte_14.GetHashCode());
                    return HashHelpers.Combine(num, this.register.sbyte_15.GetHashCode());
                }
                if (typeof(T) == typeof(ushort))
                {
                    num = HashHelpers.Combine(num, this.register.uint16_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint16_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint16_2.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint16_3.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint16_4.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint16_5.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint16_6.GetHashCode());
                    return HashHelpers.Combine(num, this.register.uint16_7.GetHashCode());
                }
                if (typeof(T) == typeof(short))
                {
                    num = HashHelpers.Combine(num, this.register.int16_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int16_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int16_2.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int16_3.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int16_4.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int16_5.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int16_6.GetHashCode());
                    return HashHelpers.Combine(num, this.register.int16_7.GetHashCode());
                }
                if (typeof(T) == typeof(uint))
                {
                    num = HashHelpers.Combine(num, this.register.uint32_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint32_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.uint32_2.GetHashCode());
                    return HashHelpers.Combine(num, this.register.uint32_3.GetHashCode());
                }
                if (typeof(T) == typeof(int))
                {
                    num = HashHelpers.Combine(num, this.register.int32_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int32_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.int32_2.GetHashCode());
                    return HashHelpers.Combine(num, this.register.int32_3.GetHashCode());
                }
                if (typeof(T) == typeof(ulong))
                {
                    num = HashHelpers.Combine(num, this.register.uint64_0.GetHashCode());
                    return HashHelpers.Combine(num, this.register.uint64_1.GetHashCode());
                }
                if (typeof(T) == typeof(long))
                {
                    num = HashHelpers.Combine(num, this.register.int64_0.GetHashCode());
                    return HashHelpers.Combine(num, this.register.int64_1.GetHashCode());
                }
                if (typeof(T) == typeof(float))
                {
                    num = HashHelpers.Combine(num, this.register.single_0.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.single_1.GetHashCode());
                    num = HashHelpers.Combine(num, this.register.single_2.GetHashCode());
                    return HashHelpers.Combine(num, this.register.single_3.GetHashCode());
                }
                if (typeof(T) == typeof(double))
                {
                    num = HashHelpers.Combine(num, this.register.double_0.GetHashCode());
                    return HashHelpers.Combine(num, this.register.double_1.GetHashCode());
                }
                throw new NotSupportedException("Specified type is not supported");
            }
        }
References System.Numerics.Hashing.HashHelpers.Combine(), System.Numerics.Vector< T >.GetHashCode(), and System.Numerics.Vector< T >.IsHardwareAccelerated.
Referenced by System.Numerics.Vector< T >.GetHashCode().