Terraria Decompiled: System.Numerics.Vector.ToString
ToString() [3/3]
string System.Numerics.Vector< T >.ToString (string format, IFormatProvider formatProvider) inline
Implements System.IFormattable.
Definition at line 1593 of file Vector.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            string numberGroupSeparator = NumberFormatInfo.GetInstance(formatProvider).NumberGroupSeparator;
            stringBuilder.Append('<');
            for (int i = 0; i < Vector<T>.Count - 1; i++)
            {
                stringBuilder.Append(((IFormattable)((object)this[i])).ToString(format, formatProvider));
                stringBuilder.Append(numberGroupSeparator);
                stringBuilder.Append(' ');
            }
            stringBuilder.Append(((IFormattable)((object)this[Vector<T>.Count - 1])).ToString(format, formatProvider));
            stringBuilder.Append('>');
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Numerics.Vector< T >.Count, System.format, System.Globalization.NumberFormatInfo.GetInstance(), System.Globalization.NumberFormatInfo.NumberGroupSeparator, System.Numerics.Vector< T >.ToString(), and System.Text.StringBuilder.ToString().