Terraria Decompiled: System.Runtime.InteropServices.FieldOffsetAttribute.GetCustomAttribute
GetCustomAttribute()
static Attribute System.Runtime.InteropServices.FieldOffsetAttribute.GetCustomAttribute (RuntimeFieldInfo field) inline static package
Definition at line 14 of file FieldOffsetAttribute.cs.
        {
            int fieldOffset;
            if (field.DeclaringType != null && (fieldOffset = field.GetFieldOffset()) >= 0)
            {
                return new FieldOffsetAttribute(fieldOffset);
            }
            return null;
        }
References System.Reflection.RuntimeFieldInfo.DeclaringType, System.Runtime.InteropServices.FieldOffsetAttribute.FieldOffsetAttribute(), and System.Reflection.RuntimeFieldInfo.GetFieldOffset().
Referenced by System.Runtime.InteropServices.FieldOffsetAttribute.IsDefined().