Terraria Decompiled: System.Security.Permissions.FileDialogPermission.Union
Union()
override IPermission System.Security.Permissions.FileDialogPermission.Union (IPermission target) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 120 of file FileDialogPermission.cs.
        {
            FileDialogPermission fileDialogPermission = this.Cast(target);
            if (fileDialogPermission == null)
            {
                return this.Copy();
            }
            if (this.IsUnrestricted() || fileDialogPermission.IsUnrestricted())
            {
                return new FileDialogPermission(PermissionState.Unrestricted);
            }
            return new FileDialogPermission(this._access | fileDialogPermission._access);
        }
References System.Security.Permissions.FileDialogPermission._access, System.Security.Permissions.FileDialogPermission.Cast(), System.Security.Permissions.FileDialogPermission.Copy(), System.Security.Permissions.FileDialogPermission.FileDialogPermission(), and System.Security.Permissions.FileDialogPermission.IsUnrestricted().