Terraria Decompiled: Terraria.GameContent.UI.Chat.RemadeChatMonitor.DrawChat
DrawChat()
void Terraria.GameContent.UI.Chat.RemadeChatMonitor.DrawChat (bool drawingPlayerChat) inline
Implements Terraria.GameContent.UI.Chat.IChatMonitor.
Definition at line 47 of file RemadeChatMonitor.cs.
        {
            int num = this._startChatLine;
            int num2 = 0;
            int num3 = 0;
            while (num > 0 && num2 < this._messages.Count)
            {
                int num4 = Math.Min(num, this._messages[num2].LineCount);
                num -= num4;
                num3 += num4;
                if (num3 == this._messages[num2].LineCount)
                {
                    num3 = 0;
                    num2++;
                }
            }
            int num5 = 0;
            int? num6 = null;
            int num7 = -1;
            int? num8 = null;
            int num9 = -1;
            while (num5 < this._showCount && num2 < this._messages.Count)
            {
                ChatMessageContainer chatMessageContainer = this._messages[num2];
                if (!chatMessageContainer.Prepared || !(drawingPlayerChat | chatMessageContainer.CanBeShownWhenChatIsClosed))
                {
                    break;
                }
                TextSnippet[] snippetWithInversedIndex = chatMessageContainer.GetSnippetWithInversedIndex(num3);
                ChatManager.DrawColorCodedStringWithShadow(Main.spriteBatch, FontAssets.MouseText.Value, snippetWithInversedIndex, new Vector2(88f, (float)(Main.screenHeight - 30 - 28 - num5 * 22)), 0f, Vector2.Zero, Vector2.One, out num9, -1f, 2f);
                if (num9 >= 0)
                {
                    num8 = new int?(num9);
                    num6 = new int?(num2);
                    num7 = num3;
                }
                num5++;
                num3++;
                if (num3 >= chatMessageContainer.LineCount)
                {
                    num3 = 0;
                    num2++;
                }
            }
            if (num6 != null && num8 != null && !PlayerInput.IgnoreMouseInterface)
            {
                TextSnippet[] snippetWithInversedIndex2 = this._messages[num6.Value].GetSnippetWithInversedIndex(num7);
                snippetWithInversedIndex2[num8.Value].OnHover();
                Main.LocalPlayer.mouseInterface = true;
                if (Main.mouseLeft && Main.mouseLeftRelease)
                {
                    snippetWithInversedIndex2[num8.Value].OnClick();
                }
            }
        }
References Terraria.GameContent.UI.Chat.RemadeChatMonitor._messages, Terraria.GameContent.UI.Chat.RemadeChatMonitor._showCount, Terraria.GameContent.UI.Chat.RemadeChatMonitor._startChatLine, Terraria.UI.Chat.ChatMessageContainer.CanBeShownWhenChatIsClosed, System.Collections.Generic.List< T >.Count, Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.Chat.ChatMessageContainer.GetSnippetWithInversedIndex(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.UI.Chat.ChatMessageContainer.LineCount, System.Math.Min(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.UI.Chat.TextSnippet.OnClick(), Microsoft.Xna.Framework.Vector2.One, Terraria.UI.Chat.TextSnippet.OnHover(), Terraria.UI.Chat.ChatMessageContainer.Prepared, Terraria.Main.screenHeight, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Vector2.Zero.