Terraria Decompiled: NVorbis.Ogg.PageReader.AddPage
AddPage()
override bool NVorbis.Ogg.PageReader.AddPage (int streamSerial, byte[] pageBuf, bool isResync) inline protected
Definition at line 149 of file PageReader.cs.
        {
            this.PageOffset = base.StreamPosition - (long)pageBuf.Length;
            this.ParsePageHeader(pageBuf, new int?(streamSerial), new bool?(isResync));
            if (this.PacketCount == 0)
            {
                return false;
            }
            this._packets = PageReader.ReadPackets((int)this.PacketCount, new Span<byte>(pageBuf, 27, (int)pageBuf[26]), new Memory<byte>(pageBuf, (int)(27 + pageBuf[26]), pageBuf.Length - 27 - (int)pageBuf[26]));
            IStreamPageReader streamPageReader;
            if (this._streamReaders.TryGetValue(streamSerial, ref streamPageReader))
            {
                streamPageReader.AddPage();
                if ((this.PageFlags & PageFlags.EndOfStream) == PageFlags.EndOfStream)
                {
                    this._streamReaders.Remove(this.StreamSerial);
                }
            }
            else
            {
                IStreamPageReader streamPageReader2 = PageReader.CreateStreamPageReader.Invoke(this, this.StreamSerial);
                streamPageReader2.AddPage();
                this._streamReaders.Add(this.StreamSerial, streamPageReader2);
                if (!this._newStreamCallback.Invoke(streamPageReader2.PacketProvider))
                {
                    this._streamReaders.Remove(this.StreamSerial);
                    return false;
                }
            }
            return true;
        }
References NVorbis.Ogg.PageReader._newStreamCallback, NVorbis.Ogg.PageReader._streamReaders, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), NVorbis.Contracts.Ogg.IStreamPageReader.AddPage(), NVorbis.Ogg.PageReader.CreateStreamPageReader, long, NVorbis.Ogg.PageReader.PacketCount, NVorbis.Contracts.Ogg.IStreamPageReader.PacketProvider, NVorbis.Ogg.PageReader.ParsePageHeader(), NVorbis.Ogg.PageReader.ReadPackets(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), NVorbis.Ogg.PageReader.StreamSerial, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().