Terraria Decompiled: Ionic.BZip2.BitWriter.WriteBits
WriteBits()
void Ionic.BZip2.BitWriter.WriteBits (int nbits, uint value) inline
Definition at line 56 of file BitWriter.cs.
        {
            int i = this.nAccumulatedBits;
            uint num = this.accumulator;
            while (i >= 8)
            {
                this.output.WriteByte((byte)((num >> 24) & 255U));
                this.totalBytesWrittenOut++;
                num <<= 8;
                i -= 8;
            }
            this.accumulator = num | (value << 32 - i - nbits);
            this.nAccumulatedBits = i + nbits;
        }
References Ionic.BZip2.BitWriter.accumulator, Ionic.BZip2.BitWriter.nAccumulatedBits, Ionic.BZip2.BitWriter.output, Ionic.BZip2.BitWriter.totalBytesWrittenOut, System.U, System.value, and System.IO.Stream.WriteByte().
Referenced by Ionic.BZip2.BZip2Compressor.CompressAndWrite(), Ionic.BZip2.BitWriter.Flush(), Ionic.BZip2.BZip2Compressor.moveToFrontCodeAndSend(), Ionic.BZip2.BZip2Compressor.sendMTFValues4(), Ionic.BZip2.BZip2Compressor.sendMTFValues5(), Ionic.BZip2.BZip2Compressor.sendMTFValues6(), Ionic.BZip2.BZip2Compressor.sendMTFValues7(), Ionic.BZip2.BitWriter.WriteByte(), and Ionic.BZip2.BitWriter.WriteInt().