Terraria Decompiled: Ionic.BZip2.BitWriter.FinishAndPad
FinishAndPad()
void Ionic.BZip2.BitWriter.FinishAndPad () inline
Definition at line 93 of file BitWriter.cs.
        {
            this.Flush();
            if (this.NumRemainingBits > 0)
            {
                byte b = (byte)((this.accumulator >> 24) & 255U);
                this.output.WriteByte(b);
                this.totalBytesWrittenOut++;
            }
        }
References Ionic.BZip2.BitWriter.accumulator, Ionic.BZip2.BitWriter.Flush(), Ionic.BZip2.BitWriter.NumRemainingBits, Ionic.BZip2.BitWriter.output, Ionic.BZip2.BitWriter.totalBytesWrittenOut, System.U, and System.IO.Stream.WriteByte().
Referenced by Ionic.BZip2.BZip2OutputStream.EmitTrailer().