Terraria Decompiled: NVorbis.Ogg.PageReader.ParsePageHeader
ParsePageHeader()
ushort NVorbis.Ogg.PageReader.ParsePageHeader (byte[] pageBuf, int? streamSerial, bool? isResync) inline private
Definition at line 39 of file PageReader.cs.
        {
            byte b = pageBuf[26];
            int num = 0;
            int num2 = 0;
            bool flag = false;
            int num3 = 0;
            int i = 0;
            int num4 = 27;
            while (i < (int)b)
            {
                byte b2 = pageBuf[num4];
                num3 += (int)b2;
                num += (int)b2;
                if (b2 < 255)
                {
                    if (num3 > 0)
                    {
                        num2++;
                    }
                    num3 = 0;
                }
                i++;
                num4++;
            }
            if (num3 > 0)
            {
                flag = pageBuf[(int)(b + 26)] == byte.MaxValue;
                num2++;
            }
            this.StreamSerial = streamSerial ?? BitConverter.ToInt32(pageBuf, 14);
            this.SequenceNumber = BitConverter.ToInt32(pageBuf, 18);
            this.PageFlags = (PageFlags)pageBuf[5];
            this.GranulePosition = BitConverter.ToInt64(pageBuf, 6);
            this.PacketCount = (short)num2;
            this.IsResync = isResync;
            this.IsContinued = flag;
            this.PageOverhead = (int)(27 + b);
            return (ushort)(this.PageOverhead + num);
        }
References int, NVorbis.Ogg.PageReader.PageFlags, System.BitConverter.ToInt32(), and System.BitConverter.ToInt64().
Referenced by NVorbis.Ogg.PageReader.AddPage(), and NVorbis.Ogg.PageReader.ReadPageAt().