Terraria Decompiled: System.GC.ReRegisterForFinalize
ReRegisterForFinalize()
static void System.GC.ReRegisterForFinalize (object obj) inline static
Definition at line 213 of file GC.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj");
            }
            GC._ReRegisterForFinalize(obj);
        }
References System.GC._ReRegisterForFinalize(), and System.obj.
Referenced by System.Gen2GcCallback.Finalize(), System.Threading.Tasks.TaskExceptionHolder.MarkAsUnhandled(), Microsoft.Xna.Framework.Audio.Cue.~Cue(), Microsoft.Xna.Framework.Audio.SoundBank.~SoundBank(), Microsoft.Xna.Framework.Audio.SoundEffect.~SoundEffect(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.~SoundEffectInstance(), and Microsoft.Xna.Framework.Audio.WaveBank.~WaveBank().