Terraria Decompiled: NVorbis.StreamDecoder.StreamDecoder
StreamDecoder() [2/3]
NVorbis.StreamDecoder.StreamDecoder (IPacketProvider packetProvider, IFactory factory) inline package
Definition at line 36 of file StreamDecoder.cs.
        {
            if (packetProvider == null)
            {
                throw new ArgumentNullException("packetProvider");
            }
            this._packetProvider = packetProvider;
            if (factory == null)
            {
                throw new ArgumentNullException("factory");
            }
            this._factory = factory;
            this._stats = new StreamStats();
            this._currentPosition = 0L;
            this.ClipSamples = true;
            IPacket packet = this._packetProvider.PeekNextPacket();
            if (!this.ProcessHeaderPackets(packet))
            {
                this._packetProvider = null;
                packet.Reset();
                throw StreamDecoder.GetInvalidStreamException(packet);
            }
        }
References NVorbis.StreamDecoder._packetProvider, NVorbis.StreamDecoder.GetInvalidStreamException(), System.L, NVorbis.StreamDecoder.ProcessHeaderPackets(), and NVorbis.Contracts.IPacket.Reset().