Terraria Decompiled: NVorbis.StreamDecoder.DecodeNextPacket
DecodeNextPacket()
float[][] NVorbis.StreamDecoder.DecodeNextPacket (out int packetStartindex, out int packetValidLength, out int packetTotalLength, out bool isEndOfStream, out long? samplePosition, out int bitsRead, out int bitsRemaining, out int containerOverheadBits) inline private
Definition at line 418 of file StreamDecoder.cs.
        {
            IPacket packet = null;
            float[][] array;
            try
            {
                if ((packet = this._packetProvider.GetNextPacket()) == null)
                {
                    isEndOfStream = true;
                }
                else
                {
                    isEndOfStream = packet.IsEndOfStream;
                    if (packet.IsResync)
                    {
                        this._hasPosition = false;
                    }
                    containerOverheadBits = packet.ContainerOverheadBits;
                    if (packet.ReadBit())
                    {
                        bitsRemaining = packet.BitsRemaining + 1;
                    }
                    else
                    {
                        IMode mode = this._modes[(int)packet.ReadBits(this._modeFieldBits)];
                        if (this._nextPacketBuf == null)
{
                            this._nextPacketBuf = new float[(int)this._channels][];
                            for (int i = 0; i < (int)this._channels; i++)
{
                                this._nextPacketBuf[i] = new float[this._block1Size];
                            }
                        }
                        if (mode.Decode(packet, this._nextPacketBuf, out packetStartindex, out packetValidLength, out packetTotalLength))
{
                            samplePosition = packet.GranulePosition;
                            bitsRead = packet.BitsRead;
                            bitsRemaining = packet.BitsRemaining;
                            return this._nextPacketBuf;
                        }
                        bitsRemaining = packet.BitsRead + packet.BitsRemaining;
                    }
                }
                packetStartindex = 0;
                packetValidLength = 0;
                packetTotalLength = 0;
                samplePosition = default(long?);
                bitsRead = 0;
                bitsRemaining = 0;
                containerOverheadBits = 0;
                array = null;
            }
            finally
            {
                if (packet != null)
                {
                    packet.Done();
                }
            }
            return array;
        }
References NVorbis.StreamDecoder._block1Size, NVorbis.StreamDecoder._channels, NVorbis.StreamDecoder._modes, NVorbis.StreamDecoder._nextPacketBuf, NVorbis.StreamDecoder._packetProvider, System.array, NVorbis.Contracts.IPacket.BitsRead, NVorbis.Contracts.IPacket.BitsRemaining, NVorbis.Contracts.IPacket.ContainerOverheadBits, NVorbis.Contracts.IMode.Decode(), NVorbis.Contracts.IPacket.Done(), NVorbis.Contracts.IPacket.GranulePosition, int, NVorbis.Contracts.IPacket.IsEndOfStream, NVorbis.Contracts.IPacket.IsResync, System.mode, and NVorbis.Contracts.IPacket.ReadBits().
Referenced by NVorbis.StreamDecoder.ReadNextPacket().