Terraria Decompiled: NVorbis.StreamDecoder.GetPacketGranules
GetPacketGranules()
int NVorbis.StreamDecoder.GetPacketGranules (IPacket curPacket, bool isLastInPage) inline private
Definition at line 570 of file StreamDecoder.cs.
        {
            if (curPacket.IsResync)
            {
                return 0;
            }
            if (curPacket.ReadBit())
            {
                return 0;
            }
            int num = (int)curPacket.ReadBits(this._modeFieldBits);
            if (num < 0 || num >= this._modes.Length)
            {
                return 0;
            }
            return this._modes[num].GetPacketSampleCount(curPacket, isLastInPage);
        }
References NVorbis.StreamDecoder._modes, NVorbis.Contracts.IMode.GetPacketSampleCount(), int, NVorbis.Contracts.IPacket.IsResync, and NVorbis.Contracts.IPacket.ReadBits().
Referenced by NVorbis.StreamDecoder.SeekTo().