Terraria Decompiled: NVorbis.StreamDecoder.Read
Read()
int NVorbis.StreamDecoder.Read (float[] buffer, int offset, int count) inline
Implements NVorbis.Contracts.IStreamDecoder.
Definition at line 279 of file StreamDecoder.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (offset < 0 || offset + count > buffer.Length)
            {
                throw new ArgumentOutOfRangeException("offset");
            }
            if (count % (int)this._channels != 0)
            {
                throw new ArgumentOutOfRangeException("count", "Must be a multiple of Channels!");
            }
            if (this._packetProvider == null)
            {
                throw new ObjectDisposedException("StreamDecoder");
            }
            if (count == 0)
            {
                return 0;
            }
            int i = offset;
            int num = offset + count;
            while (i < num)
            {
                if (this._prevPacketStart == this._prevPacketEnd)
                {
                    if (this._eosFound)
                    {
                        this._nextPacketBuf = null;
                        this._prevPacketBuf = null;
                        break;
                    }
                    long? num2;
                    if (!this.ReadNextPacket((i - offset) / (int)this._channels, out num2))
                    {
                        this._prevPacketEnd = this._prevPacketStop;
                    }
                    if (num2 != null && !this._hasPosition)
                    {
                        this._hasPosition = true;
                        this._currentPosition = num2.Value - (long)(this._prevPacketEnd - this._prevPacketStart) - (long)((i - offset) / (int)this._channels);
                    }
                }
                int num3 = Math.Min((num - i) / (int)this._channels, this._prevPacketEnd - this._prevPacketStart);
                if (num3 > 0)
                {
                    if (this.ClipSamples)
                    {
                        i += this.ClippingCopyBuffer(buffer, i, num3);
                    }
                    else
                    {
                        i += this.CopyBuffer(buffer, i, num3);
                    }
                }
            }
            count = i - offset;
            this._currentPosition += (long)(count / (int)this._channels);
            return count;
        }
References NVorbis.StreamDecoder._channels, NVorbis.StreamDecoder._eosFound, NVorbis.StreamDecoder._hasPosition, NVorbis.StreamDecoder._packetProvider, NVorbis.StreamDecoder._prevPacketEnd, NVorbis.StreamDecoder._prevPacketStart, NVorbis.StreamDecoder._prevPacketStop, NVorbis.StreamDecoder.ClippingCopyBuffer(), NVorbis.StreamDecoder.ClipSamples, NVorbis.StreamDecoder.CopyBuffer(), System.count, int, long, System.Math.Min(), System.offset, and NVorbis.StreamDecoder.ReadNextPacket().