Terraria Decompiled: NVorbis.StreamDecoder.SeekTo
SeekTo() [2/2]
void NVorbis.StreamDecoder.SeekTo (TimeSpan timePosition, SeekOrigin seekOrigin = 0) inline
Implements NVorbis.Contracts.IStreamDecoder.
Definition at line 495 of file StreamDecoder.cs.
        {
            this.SeekTo((long)((double)this.SampleRate * timePosition.TotalSeconds), seekOrigin);
        }
References NVorbis.StreamDecoder.SampleRate, NVorbis.StreamDecoder.SeekTo(), and System.TimeSpan.TotalSeconds.
Referenced by NVorbis.StreamDecoder.SeekTo(), and NVorbis.StreamDecoder.SeekTo().