Terraria Decompiled: NVorbis.StreamDecoder.LoadComments
LoadComments()
bool NVorbis.StreamDecoder.LoadComments (IPacket packet) inline private
Definition at line 199 of file StreamDecoder.cs.
        {
            if (!StreamDecoder.ValidateHeader(packet, StreamDecoder.PacketSignatureComments))
            {
                return false;
            }
            this._vendor = StreamDecoder.ReadString(packet);
            this._comments = new string[packet.ReadBits(32)];
            for (int i = 0; i < this._comments.Length; i++)
            {
                this._comments[i] = StreamDecoder.ReadString(packet);
            }
            this._stats.AddPacket(-1, packet.BitsRead, packet.BitsRemaining, packet.ContainerOverheadBits);
            return true;
        }
References NVorbis.StreamDecoder._comments, NVorbis.StreamDecoder._stats, NVorbis.StreamStats.AddPacket(), NVorbis.Contracts.IPacket.BitsRead, NVorbis.Contracts.IPacket.BitsRemaining, NVorbis.Contracts.IPacket.ContainerOverheadBits, NVorbis.StreamDecoder.PacketSignatureComments, NVorbis.Contracts.IPacket.ReadBits(), NVorbis.StreamDecoder.ReadString(), and NVorbis.StreamDecoder.ValidateHeader().