Terraria Decompiled: NVorbis.StreamDecoder.GetInvalidStreamException
GetInvalidStreamException()
static Exception NVorbis.StreamDecoder.GetInvalidStreamException (IPacket packet) inline static private
Definition at line 61 of file StreamDecoder.cs.
        {
            Exception ex;
            try
            {
                ulong num = packet.ReadBits(64);
                if (num == 7233173838382854223UL)
                {
                    ex = new ArgumentException("Found OPUS bitstream.");
                }
                else if ((num & 255UL) == 127UL)
                {
                    ex = new ArgumentException("Found FLAC bitstream.");
                }
                else if (num == 2314885909937746003UL)
                {
                    ex = new ArgumentException("Found Speex bitstream.");
                }
                else if (num == 28254585843050854UL)
                {
                    ex = new ArgumentException("Found Skeleton metadata bitstream.");
                }
                else if ((num & 72057594037927680UL) == 27428895509214208UL)
                {
                    ex = new ArgumentException("Found Theora bitsream.");
                }
                else
                {
                    ex = new ArgumentException("Could not find Vorbis data to decode.");
                }
            }
            finally
            {
                packet.Reset();
            }
            return ex;
        }
References NVorbis.Contracts.IPacket.ReadBits(), and NVorbis.Contracts.IPacket.Reset().
Referenced by NVorbis.StreamDecoder.StreamDecoder().