Terraria Decompiled: NVorbis.StreamDecoder.ProcessHeaderPackets
ProcessHeaderPackets()
bool NVorbis.StreamDecoder.ProcessHeaderPackets (IPacket packet) inline private
Definition at line 100 of file StreamDecoder.cs.
        {
            if (!StreamDecoder.ProcessHeaderPacket(packet, new Func<IPacket, bool>(this.LoadStreamHeader), delegate(IPacket _)
            {
                this._packetProvider.GetNextPacket().Done();
            }))
            {
                return false;
            }
            if (!StreamDecoder.ProcessHeaderPacket(this._packetProvider.GetNextPacket(), new Func<IPacket, bool>(this.LoadComments), delegate(IPacket pkt)
            {
                pkt.Done();
            }))
            {
                return false;
            }
            if (!StreamDecoder.ProcessHeaderPacket(this._packetProvider.GetNextPacket(), new Func<IPacket, bool>(this.LoadBooks), delegate(IPacket pkt)
            {
                pkt.Done();
            }))
            {
                return false;
            }
            this._currentPosition = 0L;
            this.ResetDecoder();
            return true;
        }
References NVorbis.StreamDecoder._packetProvider, NVorbis.Contracts.IPacket.Done(), System.L, NVorbis.StreamDecoder.ProcessHeaderPacket(), and NVorbis.StreamDecoder.ResetDecoder().
Referenced by NVorbis.StreamDecoder.StreamDecoder().