Terraria Decompiled: NVorbis.StreamDecoder.LoadBooks
LoadBooks()
bool NVorbis.StreamDecoder.LoadBooks (IPacket packet) inline private
Definition at line 216 of file StreamDecoder.cs.
        {
            if (!StreamDecoder.ValidateHeader(packet, StreamDecoder.PacketSignatureBooks))
            {
                return false;
            }
            IMdct mdct = this._factory.CreateMdct();
            IHuffman huffman = this._factory.CreateHuffman();
            ICodebook[] array = new ICodebook[packet.ReadBits(8) + 1UL];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = this._factory.CreateCodebook();
                array[i].Init(packet, huffman);
            }
            int num = (int)packet.ReadBits(6) + 1;
            packet.SkipBits(16 * num);
            IFloor[] array2 = new IFloor[packet.ReadBits(6) + 1UL];
            for (int j = 0; j < array2.Length; j++)
            {
                array2[j] = this._factory.CreateFloor(packet);
                array2[j].Init(packet, (int)this._channels, this._block0Size, this._block1Size, array);
            }
            IResidue[] array3 = new IResidue[packet.ReadBits(6) + 1UL];
            for (int k = 0; k < array3.Length; k++)
            {
                array3[k] = this._factory.CreateResidue(packet);
                array3[k].Init(packet, (int)this._channels, array);
            }
            IMapping[] array4 = new IMapping[packet.ReadBits(6) + 1UL];
            for (int l = 0; l < array4.Length; l++)
            {
                array4[l] = this._factory.CreateMapping(packet);
                array4[l].Init(packet, (int)this._channels, array2, array3, mdct);
            }
            this._modes = new IMode[packet.ReadBits(6) + 1UL];
            for (int m = 0; m < this._modes.Length; m++)
            {
                this._modes[m] = this._factory.CreateMode();
                this._modes[m].Init(packet, (int)this._channels, this._block0Size, this._block1Size, array4);
            }
            if (!packet.ReadBit())
            {
                throw new InvalidDataException("Book packet did not end on correct bit!");
            }
            this._modeFieldBits = Utils.ilog(this._modes.Length - 1);
            this._stats.AddPacket(-1, packet.BitsRead, packet.BitsRemaining, packet.ContainerOverheadBits);
            return true;
        }
References NVorbis.StreamDecoder._block0Size, NVorbis.StreamDecoder._block1Size, NVorbis.StreamDecoder._channels, NVorbis.StreamDecoder._factory, NVorbis.StreamDecoder._modes, NVorbis.StreamDecoder._stats, NVorbis.StreamStats.AddPacket(), System.array, NVorbis.Contracts.IPacket.BitsRead, NVorbis.Contracts.IPacket.BitsRemaining, NVorbis.Contracts.IPacket.ContainerOverheadBits, NVorbis.Contracts.IFactory.CreateCodebook(), NVorbis.Contracts.IFactory.CreateFloor(), NVorbis.Contracts.IFactory.CreateHuffman(), NVorbis.Contracts.IFactory.CreateMapping(), NVorbis.Contracts.IFactory.CreateMdct(), NVorbis.Contracts.IFactory.CreateMode(), NVorbis.Contracts.IFactory.CreateResidue(), NVorbis.Utils.ilog(), NVorbis.Contracts.ICodebook.Init(), NVorbis.Contracts.IResidue.Init(), NVorbis.Contracts.IMapping.Init(), NVorbis.Contracts.IFloor.Init(), NVorbis.Contracts.IMode.Init(), int, NVorbis.StreamDecoder.PacketSignatureBooks, NVorbis.Contracts.IPacket.ReadBits(), NVorbis.Contracts.IPacket.SkipBits(), and NVorbis.StreamDecoder.ValidateHeader().