Terraria Decompiled: NVorbis.StreamDecoder.ReadNextPacket
ReadNextPacket()
bool NVorbis.StreamDecoder.ReadNextPacket (int bufferedSamples, out long? samplePosition) inline private
Definition at line 375 of file StreamDecoder.cs.
        {
            int num;
            int num2;
            int num3;
            bool flag;
            int num4;
            int num5;
            int num6;
            float[][] array = this.DecodeNextPacket(out num, out num2, out num3, out flag, out samplePosition, out num4, out num5, out num6);
            this._eosFound = this._eosFound || flag;
            if (array == null)
            {
                this._stats.AddPacket(0, num4, num5, num6);
                return false;
            }
            if (samplePosition != null && flag)
            {
                long num7 = this._currentPosition + (long)bufferedSamples + (long)num2 - (long)num;
                int num8 = (int)(samplePosition.Value - num7);
                if (num8 < 0)
                {
                    num2 += num8;
                }
            }
            if (this._prevPacketEnd > 0)
            {
                StreamDecoder.OverlapBuffers(this._prevPacketBuf, array, this._prevPacketStart, this._prevPacketStop, num, (int)this._channels);
                this._prevPacketStart = num;
            }
            else if (this._prevPacketBuf == null)
            {
                this._prevPacketStart = num2;
            }
            this._stats.AddPacket(num2 - this._prevPacketStart, num4, num5, num6);
            this._nextPacketBuf = this._prevPacketBuf;
            this._prevPacketEnd = num2;
            this._prevPacketStop = num3;
            this._prevPacketBuf = array;
            return true;
        }
References NVorbis.StreamDecoder._channels, NVorbis.StreamDecoder._prevPacketBuf, NVorbis.StreamDecoder._prevPacketEnd, NVorbis.StreamDecoder._prevPacketStart, NVorbis.StreamDecoder._prevPacketStop, NVorbis.StreamDecoder._stats, NVorbis.StreamStats.AddPacket(), System.array, NVorbis.StreamDecoder.DecodeNextPacket(), int, long, and NVorbis.StreamDecoder.OverlapBuffers().
Referenced by NVorbis.StreamDecoder.Read(), and NVorbis.StreamDecoder.SeekTo().