Terraria Decompiled: NVorbis.StreamDecoder.LoadStreamHeader
LoadStreamHeader()
bool NVorbis.StreamDecoder.LoadStreamHeader (IPacket packet) inline private
Definition at line 176 of file StreamDecoder.cs.
        {
            if (!StreamDecoder.ValidateHeader(packet, StreamDecoder.PacketSignatureStream))
            {
                return false;
            }
            this._channels = (byte)packet.ReadBits(8);
            this._sampleRate = (int)packet.ReadBits(32);
            this.UpperBitrate = (int)packet.ReadBits(32);
            this.NominalBitrate = (int)packet.ReadBits(32);
            this.LowerBitrate = (int)packet.ReadBits(32);
            this._block0Size = 1 << (int)packet.ReadBits(4);
            this._block1Size = 1 << (int)packet.ReadBits(4);
            if (this.NominalBitrate == 0 && this.UpperBitrate > 0 && this.LowerBitrate > 0)
            {
                this.NominalBitrate = (this.UpperBitrate + this.LowerBitrate) / 2;
            }
            this._stats.SetSampleRate(this._sampleRate);
            this._stats.AddPacket(-1, packet.BitsRead, packet.BitsRemaining, packet.ContainerOverheadBits);
            return true;
        }
References NVorbis.StreamDecoder._sampleRate, NVorbis.StreamDecoder._stats, NVorbis.StreamStats.AddPacket(), NVorbis.Contracts.IPacket.BitsRead, NVorbis.Contracts.IPacket.BitsRemaining, NVorbis.Contracts.IPacket.ContainerOverheadBits, int, NVorbis.StreamDecoder.LowerBitrate, NVorbis.StreamDecoder.NominalBitrate, NVorbis.StreamDecoder.PacketSignatureStream, NVorbis.Contracts.IPacket.ReadBits(), NVorbis.StreamStats.SetSampleRate(), NVorbis.StreamDecoder.UpperBitrate, and NVorbis.StreamDecoder.ValidateHeader().