Terraria Decompiled: System.Threading.SpinLock.ContinueTryEnterWithThreadTracking
ContinueTryEnterWithThreadTracking()
void System.Threading.SpinLock.ContinueTryEnterWithThreadTracking (int millisecondsTimeout, uint startTime, ref bool lockTaken) inline private
Definition at line 194 of file SpinLock.cs.
        {
            int num = 0;
            int managedThreadId = Thread.CurrentThread.ManagedThreadId;
            if (this.m_owner == managedThreadId)
            {
                throw new LockRecursionException(Environment.GetResourceString("The calling thread already holds the lock."));
            }
            SpinWait spinWait = default(SpinWait);
            for (;;)
            {
                spinWait.SpinOnce();
                if (this.m_owner == num)
                {
                    Thread.BeginCriticalRegion();
                    if (Interlocked.CompareExchange(ref this.m_owner, managedThreadId, num, ref lockTaken) == num)
                    {
                        break;
                    }
                    Thread.EndCriticalRegion();
                }
                if (millisecondsTimeout == 0 || (millisecondsTimeout != -1 && spinWait.NextSpinWillYield && TimeoutHelper.UpdateTimeOut(startTime, millisecondsTimeout) <= 0))
                {
                    return;
                }
            }
        }
References System.Threading.Thread.BeginCriticalRegion(), System.Threading.Interlocked.CompareExchange(), System.Threading.Thread.CurrentThread, System.Threading.Thread.EndCriticalRegion(), System.Environment.GetResourceString(), System.Threading.SpinLock.m_owner, System.Threading.Thread.ManagedThreadId, System.Threading.SpinWait.NextSpinWillYield, System.Threading.SpinWait.SpinOnce(), and System.Threading.TimeoutHelper.UpdateTimeOut().
Referenced by System.Threading.SpinLock.ContinueTryEnter().