Terraria Decompiled: System.Threading.SpinLock.Enter
Enter()
void System.Threading.SpinLock.Enter (ref bool lockTaken) inline
Definition at line 27 of file SpinLock.cs.
        {
            Thread.BeginCriticalRegion();
            int owner = this.m_owner;
            if (lockTaken || (owner & -2147483647) != -2147483648 || Interlocked.CompareExchange(ref this.m_owner, owner | 1, owner, ref lockTaken) != owner)
            {
                this.ContinueTryEnter(-1, ref lockTaken);
            }
        }
References System.Threading.Thread.BeginCriticalRegion(), System.Threading.Interlocked.CompareExchange(), System.Threading.SpinLock.ContinueTryEnter(), and System.Threading.SpinLock.m_owner.
Referenced by System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush(), System.Buffers.ConfigurableArrayPool< T >.Bucket.Rent(), and System.Buffers.ConfigurableArrayPool< T >.Bucket.Return().