Terraria Decompiled: System.Threading.SpinLock.ContinueTryEnter
ContinueTryEnter()
void System.Threading.SpinLock.ContinueTryEnter (int millisecondsTimeout, ref bool lockTaken) inline private
Definition at line 66 of file SpinLock.cs.
        {
            Thread.EndCriticalRegion();
            if (lockTaken)
            {
                lockTaken = false;
                throw new ArgumentException(Environment.GetResourceString("The tookLock argument must be set to false before calling this method."));
            }
            if (millisecondsTimeout < -1)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout", millisecondsTimeout, Environment.GetResourceString("The timeout must be a value between -1 and Int32.MaxValue, inclusive."));
            }
            uint num = 0U;
            if (millisecondsTimeout != -1 && millisecondsTimeout != 0)
            {
                num = TimeoutHelper.GetTime();
            }
            if (this.IsThreadOwnerTrackingEnabled)
            {
                this.ContinueTryEnterWithThreadTracking(millisecondsTimeout, num, ref lockTaken);
                return;
            }
            int num2 = int.MaxValue;
            int num3 = this.m_owner;
            if ((num3 & 1) == 0)
            {
                Thread.BeginCriticalRegion();
                if (Interlocked.CompareExchange(ref this.m_owner, num3 | 1, num3, ref lockTaken) == num3)
                {
                    return;
                }
                Thread.EndCriticalRegion();
            }
            else if ((num3 & 2147483646) != SpinLock.MAXIMUM_WAITERS)
            {
                num2 = (Interlocked.Add(ref this.m_owner, 2) & 2147483646) >> 1;
            }
            if (millisecondsTimeout == 0 || (millisecondsTimeout != -1 && TimeoutHelper.UpdateTimeOut(num, millisecondsTimeout) <= 0))
            {
                this.DecrementWaiters();
                return;
            }
            int processorCount = PlatformHelper.ProcessorCount;
            if (num2 < processorCount)
            {
                int num4 = 1;
                for (int i = 1; i <= num2 * 100; i++)
                {
                    Thread.SpinWait((num2 + i) * 100 * num4);
                    if (num4 < processorCount)
                    {
                        num4++;
                    }
                    num3 = this.m_owner;
                    if ((num3 & 1) == 0)
                    {
                        Thread.BeginCriticalRegion();
                        int num5 = (((num3 & 2147483646) == 0) ? (num3 | 1) : ((num3 - 2) | 1));
                        if (Interlocked.CompareExchange(ref this.m_owner, num5, num3, ref lockTaken) == num3)
{
                            return;
                        }
                        Thread.EndCriticalRegion();
                    }
                }
            }
            if (millisecondsTimeout != -1 && TimeoutHelper.UpdateTimeOut(num, millisecondsTimeout) <= 0)
            {
                this.DecrementWaiters();
                return;
            }
            int num6 = 0;
            for (;;)
            {
                num3 = this.m_owner;
                if ((num3 & 1) == 0)
                {
                    Thread.BeginCriticalRegion();
                    int num7 = (((num3 & 2147483646) == 0) ? (num3 | 1) : ((num3 - 2) | 1));
                    if (Interlocked.CompareExchange(ref this.m_owner, num7, num3, ref lockTaken) == num3)
                    {
                        break;
                    }
                    Thread.EndCriticalRegion();
                }
                if (num6 % 40 == 0)
                {
                    Thread.Sleep(1);
                }
                else if (num6 % 10 == 0)
                {
                    Thread.Sleep(0);
                }
                else
                {
                    Thread.Yield();
                }
                if (num6 % 10 == 0 && millisecondsTimeout != -1 && TimeoutHelper.UpdateTimeOut(num, millisecondsTimeout) <= 0)
                {
                    goto Block_25;
                }
                num6++;
            }
            return;
            Block_25:
            this.DecrementWaiters();
        }
References System.Threading.Interlocked.Add(), System.Threading.Thread.BeginCriticalRegion(), System.Threading.Interlocked.CompareExchange(), System.Threading.SpinLock.ContinueTryEnterWithThreadTracking(), System.Threading.SpinLock.DecrementWaiters(), System.Threading.Thread.EndCriticalRegion(), System.Environment.GetResourceString(), System.Threading.TimeoutHelper.GetTime(), System.Threading.SpinLock.IsThreadOwnerTrackingEnabled, System.Threading.SpinLock.m_owner, System.Threading.SpinLock.MAXIMUM_WAITERS, System.Threading.PlatformHelper.ProcessorCount, System.Threading.Thread.Sleep(), System.Threading.Thread.SpinWait(), System.U, System.Threading.TimeoutHelper.UpdateTimeOut(), and System.Threading.Thread.Yield().
Referenced by System.Threading.SpinLock.Enter(), and System.Threading.SpinLock.TryEnter().