Terraria Decompiled: System.Threading.SpinLock.ExitSlowPath
ExitSlowPath()
void System.Threading.SpinLock.ExitSlowPath (bool useMemoryBarrier) inline private
Definition at line 254 of file SpinLock.cs.
        {
            bool flag = (this.m_owner & int.MinValue) == 0;
            if (flag && !this.IsHeldByCurrentThread)
            {
                throw new SynchronizationLockException(Environment.GetResourceString("The calling thread does not hold the lock."));
            }
            if (useMemoryBarrier)
            {
                if (flag)
                {
                    Interlocked.Exchange(ref this.m_owner, 0);
                    return;
                }
                Interlocked.Decrement(ref this.m_owner);
                return;
            }
            else
            {
                if (flag)
                {
                    this.m_owner = 0;
                    return;
                }
                int owner = this.m_owner;
                this.m_owner = owner & -2;
                return;
            }
        }
References System.Threading.Interlocked.Decrement(), System.Threading.Interlocked.Exchange(), System.Environment.GetResourceString(), System.Threading.SpinLock.IsHeldByCurrentThread, and System.Threading.SpinLock.m_owner.
Referenced by System.Threading.SpinLock.Exit(), and System.Threading.SpinLock.Exit().