Terraria Decompiled: FullSerializer.Internal.fsCyclicReferenceManager.GetReferenceId
GetReferenceId()
int FullSerializer.Internal.fsCyclicReferenceManager.GetReferenceId (object item) inline
Definition at line 51 of file fsCyclicReferenceManager.cs.
        {
            int num;
            if (!this._objectIds.TryGetValue(item, ref num))
            {
                int nextId = this._nextId;
                this._nextId = nextId + 1;
                num = nextId;
                this._objectIds[item] = num;
            }
            return num;
        }
References FullSerializer.Internal.fsCyclicReferenceManager._nextId, FullSerializer.Internal.fsCyclicReferenceManager._objectIds, System.item, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by FullSerializer.fsSerializer.InternalSerialize_1_ProcessCycles(), FullSerializer.Internal.fsCyclicReferenceManager.IsReference(), and FullSerializer.Internal.fsCyclicReferenceManager.MarkSerialized().