Terraria Decompiled: System.Security.AccessControl.RawAcl.GetSddlForm
GetSddlForm()
override string System.Security.AccessControl.RawAcl.GetSddlForm (ControlFlags sdFlags, bool isDacl) inline package
Definition at line 145 of file RawAcl.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            if (isDacl)
            {
                if ((sdFlags & ControlFlags.DiscretionaryAclProtected) != ControlFlags.None)
                {
                    stringBuilder.Append("P");
                }
                if ((sdFlags & ControlFlags.DiscretionaryAclAutoInheritRequired) != ControlFlags.None)
                {
                    stringBuilder.Append("AR");
                }
                if ((sdFlags & ControlFlags.DiscretionaryAclAutoInherited) != ControlFlags.None)
                {
                    stringBuilder.Append("AI");
                }
            }
            else
            {
                if ((sdFlags & ControlFlags.SystemAclProtected) != ControlFlags.None)
                {
                    stringBuilder.Append("P");
                }
                if ((sdFlags & ControlFlags.SystemAclAutoInheritRequired) != ControlFlags.None)
                {
                    stringBuilder.Append("AR");
                }
                if ((sdFlags & ControlFlags.SystemAclAutoInherited) != ControlFlags.None)
                {
                    stringBuilder.Append("AI");
                }
            }
            foreach (GenericAce genericAce in this.list)
            {
                stringBuilder.Append(genericAce.GetSddlForm());
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Security.AccessControl.GenericAce.GetSddlForm(), System.Security.AccessControl.RawAcl.list, and System.Text.StringBuilder.ToString().
Referenced by System.Security.AccessControl.CommonAcl.GetSddlForm().