Terraria Decompiled: System.Security.AccessControl.RawAcl.GetBinaryForm
GetBinaryForm()
override void System.Security.AccessControl.RawAcl.GetBinaryForm (byte[] binaryForm, int offset) inline
Definition at line 105 of file RawAcl.cs.
        {
            if (binaryForm == null)
            {
                throw new ArgumentNullException("binaryForm");
            }
            if (offset < 0 || offset > binaryForm.Length - this.BinaryLength)
            {
                throw new ArgumentException("Offset out of range", "offset");
            }
            binaryForm[offset] = this.Revision;
            binaryForm[offset + 1] = 0;
            this.WriteUShort((ushort)this.BinaryLength, binaryForm, offset + 2);
            this.WriteUShort((ushort)this.list.Count, binaryForm, offset + 4);
            this.WriteUShort(0, binaryForm, offset + 6);
            int num = offset + 8;
            foreach (GenericAce genericAce in this.list)
            {
                genericAce.GetBinaryForm(binaryForm, num);
                num += genericAce.BinaryLength;
            }
        }
References System.Security.AccessControl.GenericAce.BinaryLength, System.Security.AccessControl.RawAcl.BinaryLength, System.Security.AccessControl.GenericAce.GetBinaryForm(), System.Security.AccessControl.RawAcl.list, System.offset, System.Security.AccessControl.RawAcl.Revision, and System.Security.AccessControl.RawAcl.WriteUShort().
Referenced by System.Security.AccessControl.CommonAcl.CommonAcl(), and System.Security.AccessControl.CommonAcl.GetBinaryForm().