Terraria Decompiled: ReLogic.Reflection.IdDictionary.Create
Create()
static IdDictionary ReLogic.Reflection.IdDictionary.Create (Type idClass, Type idType) inline static
Definition at line 86 of file IdDictionary.cs.
        {
            int num = int.MaxValue;
            FieldInfo fieldInfo = Enumerable.FirstOrDefault<FieldInfo>(idClass.GetFields(), (FieldInfo field) => field.Name == "Count");
            if (fieldInfo != null)
            {
                num = Convert.ToInt32(fieldInfo.GetValue(null));
                if (num == 0)
                {
                    throw new Exception("IdDictionary cannot be created before Count field is initialized. Move to bottom of static class");
                }
            }
            IdDictionary dictionary = new IdDictionary(num);
            Enumerable.ToList<FieldInfo>(Enumerable.Where<FieldInfo>(idClass.GetFields(24), (FieldInfo f) => f.FieldType == idType)).ForEach(delegate(FieldInfo field)
            {
                int num2 = Convert.ToInt32(field.GetValue(null));
                if (num2 < dictionary.Count)
                {
                    dictionary._nameToId.Add(field.Name, num2);
                }
            });
            dictionary._idToName = Enumerable.ToDictionary<KeyValuePair<string, int>, int, string>(dictionary._nameToId, (KeyValuePair<string, int> kp) => kp.Value, (KeyValuePair<string, int> kp) => kp.Key);
            return dictionary;
        }
References System.dictionary, System.Reflection.FieldInfo.FieldType, System.Type.GetFields(), System.Reflection.FieldInfo.GetValue(), ReLogic.Reflection.IdDictionary.IdDictionary(), int, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.Reflection.MemberInfo.Name, and System.Convert.ToInt32().
Referenced by ReLogic.Reflection.IdDictionary.Create< IdClass, IdType >().