Terraria Decompiled: Terraria.Localization.VariableText.TryCreate
TryCreate()
static bool Terraria.Localization.VariableText.TryCreate (string s, out VariableText text) inline static
Definition at line 23 of file VariableText.cs.
        {
            if (!VariableText._substitutionRegex.IsMatch(s))
            {
                text = null;
                return false;
            }
            List<string> variables = new List<string>();
            List<VariableText.Condition> conditions = new List<VariableText.Condition>();
            string text2 = VariableText._substitutionRegex.Replace(s, delegate(Match match)
            {
                string text3 = match.Groups[2].ToString();
                string text4 = match.Groups[1].ToString();
                if (text4 != "")
                {
                    conditions.Add(new VariableText.Condition
                    {
                        Name = text3,
                        RequiredValue = (text4 == "?")
                    });
                    return "";
                }
                int num = variables.IndexOf(text3);
                if (num < 0)
                {
                    num = variables.Count;
                    variables.Add(text3);
                }
                return "{" + num + "}";
            });
            text = new VariableText(s, text2, conditions.ToArray(), variables.ToArray());
            return true;
        }
References Terraria.Localization.VariableText._substitutionRegex, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Count, System.Collections.Generic.List< T >.IndexOf(), System.match, System.s, System.text, System.Collections.Generic.List< T >.ToArray(), and Terraria.Localization.VariableText.VariableText().
Referenced by Terraria.Localization.LocalizedText.SetValue().