Terraria Decompiled: System.Security.Util.Tokenizer.GetTokens
GetTokens()
void System.Security.Util.Tokenizer.GetTokens (TokenizerStream stream, int maxNum, bool endAfterKet) inline package
Definition at line 148 of file Tokenizer.cs.
        {
            while (maxNum == -1 || stream.GetTokenCount() < maxNum)
            {
                int num = 0;
                bool flag = false;
                bool flag2 = false;
                Tokenizer.StringMaker maker = this._maker;
                maker._outStringBuilder = null;
                maker._outIndex = 0;
                int num2;
                for (;;)
                {
                    if (this._inSavedCharacter != -1)
                    {
                        num2 = this._inSavedCharacter;
                        this._inSavedCharacter = -1;
                    }
                    else
                    {
                        switch (this._inTokenSource)
{
                        case Tokenizer.TokenSource.UnicodeByteArray:
                            if (this._inIndex + 1 >= this._inSize)
{
                                goto Block_3;
                            }
                            num2 = ((int)this._inBytes[this._inIndex + 1] << 8) + (int)this._inBytes[this._inIndex];
                            this._inIndex += 2;
                            break;
                        case Tokenizer.TokenSource.UTF8ByteArray:
{
                            if (this._inIndex >= this._inSize)
{
                                goto Block_4;
                            }
                            byte[] inBytes = this._inBytes;
                            int num3 = this._inIndex;
                            this._inIndex = num3 + 1;
                            num2 = inBytes[num3];
                            if ((num2 & 128) != 0)
{
                                switch ((num2 & 240) >> 4)
{
                                case 8:
                                case 9:
                                case 10:
                                case 11:
                                    goto IL_012D;
                                case 12:
                                case 13:
                                    num2 &= 31;
                                    num = 2;
                                    break;
                                case 14:
                                    num2 &= 15;
                                    num = 3;
                                    break;
                                case 15:
                                    goto IL_014B;
                                }
                                if (this._inIndex >= this._inSize)
{
                                    goto Block_7;
                                }
                                byte[] inBytes2 = this._inBytes;
                                num3 = this._inIndex;
                                this._inIndex = num3 + 1;
                                byte b = inBytes2[num3];
                                if ((b & 192) != 128)
{
                                    goto Block_8;
                                }
                                num2 = (num2 << 6) | (int)(b & 63);
                                if (num != 2)
{
                                    if (this._inIndex >= this._inSize)
{
                                        goto Block_10;
                                    }
                                    byte[] inBytes3 = this._inBytes;
                                    num3 = this._inIndex;
                                    this._inIndex = num3 + 1;
                                    b = inBytes3[num3];
                                    if ((b & 192) != 128)
{
                                        goto Block_11;
                                    }
                                    num2 = (num2 << 6) | (int)(b & 63);
                                }
                            }
                            break;
                        }
                        case Tokenizer.TokenSource.ASCIIByteArray:
{
                            if (this._inIndex >= this._inSize)
{
                                goto Block_12;
                            }
                            byte[] inBytes4 = this._inBytes;
                            int num3 = this._inIndex;
                            this._inIndex = num3 + 1;
                            num2 = inBytes4[num3];
                            break;
                        }
                        case Tokenizer.TokenSource.CharArray:
{
                            if (this._inIndex >= this._inSize)
{
                                goto Block_13;
                            }
                            char[] inChars = this._inChars;
                            int num3 = this._inIndex;
                            this._inIndex = num3 + 1;
                            num2 = inChars[num3];
                            break;
                        }
                        case Tokenizer.TokenSource.String:
{
                            if (this._inIndex >= this._inSize)
{
                                goto Block_14;
                            }
                            string inString = this._inString;
                            int num3 = this._inIndex;
                            this._inIndex = num3 + 1;
                            num2 = (int)inString[num3];
                            break;
                        }
                        case Tokenizer.TokenSource.NestedStrings:
{
                            int num3;
                            if (this._inNestedSize != 0)
{
                                if (this._inNestedIndex < this._inNestedSize)
{
                                    string inNestedString = this._inNestedString;
                                    num3 = this._inNestedIndex;
                                    this._inNestedIndex = num3 + 1;
                                    num2 = (int)inNestedString[num3];
                                    break;
                                }
                                this._inNestedSize = 0;
                            }
                            if (this._inIndex >= this._inSize)
{
                                goto Block_17;
                            }
                            string inString2 = this._inString;
                            num3 = this._inIndex;
                            this._inIndex = num3 + 1;
                            num2 = (int)inString2[num3];
                            if (num2 == 123)
{
                                for (int i = 0; i < this._searchStrings.Length; i++)
{
                                    if (string.Compare(this._searchStrings[i], 0, this._inString, this._inIndex - 1, this._searchStrings[i].Length, StringComparison.Ordinal) == 0)
{
                                        this._inNestedString = this._replaceStrings[i];
                                        this._inNestedSize = this._inNestedString.Length;
                                        this._inNestedIndex = 1;
                                        num2 = (int)this._inNestedString[0];
                                        this._inIndex += this._searchStrings[i].Length - 1;
                                        break;
                                    }
                                }
                            }
                            break;
                        }
                        default:
                            num2 = this._inTokenReader.Read();
                            if (num2 == -1)
{
                                goto Block_21;
                            }
                            break;
                        }
                    }
                    if (!flag)
                    {
                        if (num2 <= 34)
{
                            switch (num2)
{
                            case 9:
                            case 13:
                                continue;
                            case 10:
                                this.LineNo++;
                                continue;
                            case 11:
                            case 12:
                                break;
                            default:
                                switch (num2)
{
                                case 32:
                                    continue;
                                case 33:
                                    if (this._inProcessingTag != 0)
{
                                        goto Block_32;
                                    }
                                    break;
                                case 34:
                                    flag = true;
                                    flag2 = true;
                                    continue;
                                }
                                break;
                            }
                        }
                        else if (num2 != 45)
{
                            if (num2 != 47)
{
                                switch (num2)
{
                                case 60:
                                    goto IL_048A;
                                case 61:
                                    goto IL_04C0;
                                case 62:
                                    goto IL_04A4;
                                case 63:
                                    if (this._inProcessingTag != 0)
{
                                        goto Block_31;
                                    }
                                    break;
                                }
                            }
                            else if (this._inProcessingTag != 0)
{
                                goto Block_30;
                            }
                        }
                        else if (this._inProcessingTag != 0)
{
                            goto Block_33;
                        }
                    }
                    else if (num2 <= 34)
                    {
                        switch (num2)
{
                        case 9:
                        case 13:
                            break;
                        case 10:
                            this.LineNo++;
                            if (!flag2)
{
                                goto Block_46;
                            }
                            goto IL_062F;
                        case 11:
                        case 12:
                            goto IL_062F;
                        default:
                            if (num2 != 32)
{
                                if (num2 != 34)
{
                                    goto IL_062F;
                                }
                                if (flag2)
{
                                    goto Block_44;
                                }
                                goto IL_062F;
                            }
                            break;
                        }
                        if (!flag2)
{
                            goto Block_45;
                        }
                    }
                    else
                    {
                        if (num2 != 47)
{
                            if (num2 != 60)
{
                                if (num2 - 61 > 1)
{
                                    goto IL_062F;
                                }
                            }
                            else
{
                                if (!flag2)
{
                                    goto Block_41;
                                }
                                goto IL_062F;
                            }
                        }
                        if (!flag2 && this._inProcessingTag != 0)
{
                            goto Block_43;
                        }
                    }
                    IL_062F:
                    flag = true;
                    if (maker._outIndex < 512)
                    {
                        char[] outChars = maker._outChars;
                        Tokenizer.StringMaker stringMaker = maker;
                        int num3 = stringMaker._outIndex;
                        stringMaker._outIndex = num3 + 1;
                        outChars[num3] = (ushort)num2;
                    }
                    else
                    {
                        if (maker._outStringBuilder == null)
{
                            maker._outStringBuilder = new StringBuilder();
                        }
                        maker._outStringBuilder.Append(maker._outChars, 0, 512);
                        maker._outChars[0] = (char)num2;
                        maker._outIndex = 1;
                    }
                }
                IL_048A:
                this._inProcessingTag++;
                stream.AddToken(0);
                continue;
                Block_3:
                stream.AddToken(-1);
                return;
                IL_04A4:
                this._inProcessingTag--;
                stream.AddToken(1);
                if (endAfterKet)
                {
                    return;
                }
                continue;
                IL_04C0:
                stream.AddToken(4);
                continue;
                Block_30:
                stream.AddToken(2);
                continue;
                Block_31:
                stream.AddToken(5);
                continue;
                Block_32:
                stream.AddToken(6);
                continue;
                Block_33:
                stream.AddToken(7);
                continue;
                Block_41:
                this._inSavedCharacter = num2;
                stream.AddToken(3);
                stream.AddString(this.GetStringToken());
                continue;
                Block_43:
                this._inSavedCharacter = num2;
                stream.AddToken(3);
                stream.AddString(this.GetStringToken());
                continue;
                Block_44:
                stream.AddToken(3);
                stream.AddString(this.GetStringToken());
                continue;
                Block_45:
                stream.AddToken(3);
                stream.AddString(this.GetStringToken());
                continue;
                Block_46:
                stream.AddToken(3);
                stream.AddString(this.GetStringToken());
                continue;
                Block_4:
                stream.AddToken(-1);
                return;
                IL_012D:
                throw new XmlSyntaxException(this.LineNo);
                IL_014B:
                throw new XmlSyntaxException(this.LineNo);
                Block_7:
                throw new XmlSyntaxException(this.LineNo, Environment.GetResourceString("Unexpected end of file."));
                Block_8:
                throw new XmlSyntaxException(this.LineNo);
                Block_10:
                throw new XmlSyntaxException(this.LineNo, Environment.GetResourceString("Unexpected end of file."));
                Block_11:
                throw new XmlSyntaxException(this.LineNo);
                Block_12:
                stream.AddToken(-1);
                return;
                Block_13:
                stream.AddToken(-1);
                return;
                Block_14:
                stream.AddToken(-1);
                return;
                Block_17:
                stream.AddToken(-1);
                return;
                Block_21:
                stream.AddToken(-1);
                return;
            }
        }
References System.Security.Util.Tokenizer._inBytes, System.Security.Util.Tokenizer._inChars, System.Security.Util.Tokenizer._inIndex, System.Security.Util.Tokenizer._inNestedIndex, System.Security.Util.Tokenizer._inNestedSize, System.Security.Util.Tokenizer._inNestedString, System.Security.Util.Tokenizer._inProcessingTag, System.Security.Util.Tokenizer._inSavedCharacter, System.Security.Util.Tokenizer._inSize, System.Security.Util.Tokenizer._inString, System.Security.Util.Tokenizer._inTokenReader, System.Security.Util.Tokenizer._inTokenSource, System.Security.Util.Tokenizer._maker, System.Security.Util.Tokenizer.StringMaker._outChars, System.Security.Util.Tokenizer.StringMaker._outIndex, System.Security.Util.Tokenizer.StringMaker._outStringBuilder, System.Security.Util.Tokenizer._replaceStrings, System.Security.Util.Tokenizer._searchStrings, System.Security.Util.TokenizerStream.AddString(), System.Security.Util.TokenizerStream.AddToken(), System.Text.StringBuilder.Append(), System.Environment.GetResourceString(), System.Security.Util.Tokenizer.GetStringToken(), System.Security.Util.TokenizerStream.GetTokenCount(), int, and System.Security.Util.Tokenizer.LineNo.
Referenced by System.Security.Util.Parser.DetermineFormat(), and System.Security.Util.Parser.ParseContents().