Terraria Decompiled: Terraria.Localization.VariableText.TryFormat
TryFormat()
bool Terraria.Localization.VariableText.TryFormat (Func< string, object > lookup, out string formatted) inline
Definition at line 86 of file VariableText.cs.
        {
            if (!this.CheckConditionsAndLoadArgs(lookup))
            {
                formatted = null;
                return false;
            }
            this._formatBuffer.AppendFormat(this._format, this._formatArgBuffer);
            formatted = this._formatBuffer.ToString();
            this._formatBuffer.Clear();
            return true;
        }
References Terraria.Localization.VariableText._format, Terraria.Localization.VariableText._formatArgBuffer, Terraria.Localization.VariableText._formatBuffer, System.Text.StringBuilder.AppendFormat(), Terraria.Localization.VariableText.CheckConditionsAndLoadArgs(), System.Text.StringBuilder.Clear(), and System.Text.StringBuilder.ToString().
Referenced by Terraria.Localization.LocalizedText.GetValueIfConditionsMet(), Terraria.Localization.LocalizedText.TryFormatWith(), and Terraria.Localization.LocalizedText.TryFormatWith().