Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.Read
Read()
void System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.Read (__BinaryParser input) inline package
Definition at line 139 of file BinaryMethodCall.cs.
        {
            this.messageEnum = (MessageEnum)input.ReadInt32();
            this.methodName = (string)IOUtil.ReadWithCode(input);
            this.typeName = (string)IOUtil.ReadWithCode(input);
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ContextInline))
            {
                this.scallContext = (string)IOUtil.ReadWithCode(input);
                this.callContext = new LogicalCallContext
                {
                    RemotingData =
                    {
                        LogicalCallID = this.scallContext
                    }
                };
            }
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInline))
            {
                this.args = IOUtil.ReadArgs(input);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.IOUtil.FlagTest(), System.input, System.Runtime.Serialization.Formatters.Binary.IOUtil.ReadArgs(), and System.Runtime.Serialization.Formatters.Binary.IOUtil.ReadWithCode().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMethodObject().