Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.WriteArray
WriteArray()
object[] System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.WriteArray (string uri, string methodName, string typeName, Type[] instArgs, object[] args, object methodSignature, object callContext, object[] properties) inline package
Definition at line 12 of file BinaryMethodCall.cs.
        {
            this.uri = uri;
            this.methodName = methodName;
            this.typeName = typeName;
            this.instArgs = instArgs;
            this.args = args;
            this.methodSignature = methodSignature;
            this.callContext = callContext;
            this.properties = properties;
            int num = 0;
            if (args == null || args.Length == 0)
            {
                this.messageEnum = MessageEnum.NoArgs;
            }
            else
            {
                this.argTypes = new Type[args.Length];
                this.bArgsPrimitive = true;
                for (int i = 0; i < args.Length; i++)
                {
                    if (args[i] != null)
                    {
                        this.argTypes[i] = args[i].GetType();
                        if ((Converter.ToCode(this.argTypes[i]) <= InternalPrimitiveTypeE.Invalid && this.argTypes[i] != Converter.typeofString) || args[i] is ISerializable)
{
                            this.bArgsPrimitive = false;
                            break;
                        }
                    }
                }
                if (this.bArgsPrimitive)
                {
                    this.messageEnum = MessageEnum.ArgsInline;
                }
                else
                {
                    num++;
                    this.messageEnum = MessageEnum.ArgsInArray;
                }
            }
            if (instArgs != null)
            {
                num++;
                this.messageEnum |= MessageEnum.GenericMethod;
            }
            if (methodSignature != null)
            {
                num++;
                this.messageEnum |= MessageEnum.MethodSignatureInArray;
            }
            if (callContext == null)
            {
                this.messageEnum |= MessageEnum.NoContext;
            }
            else if (callContext is string)
            {
                this.messageEnum |= MessageEnum.ContextInline;
            }
            else
            {
                num++;
                this.messageEnum |= MessageEnum.ContextInArray;
            }
            if (properties != null)
            {
                num++;
                this.messageEnum |= MessageEnum.PropertyInArray;
            }
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInArray) && num == 1)
            {
                this.messageEnum ^= MessageEnum.ArgsInArray;
                this.messageEnum |= MessageEnum.ArgsIsArray;
                return args;
            }
            if (num > 0)
            {
                int num2 = 0;
                this.callA = new object[num];
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInArray))
                {
                    this.callA[num2++] = args;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.GenericMethod))
                {
                    this.callA[num2++] = instArgs;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.MethodSignatureInArray))
                {
                    this.callA[num2++] = methodSignature;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ContextInArray))
                {
                    this.callA[num2++] = callContext;
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.PropertyInArray))
                {
                    this.callA[num2] = properties;
                }
                return this.callA;
            }
            return null;
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.args, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.argTypes, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.bArgsPrimitive, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.callA, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.callContext, System.Runtime.Serialization.Formatters.Binary.IOUtil.FlagTest(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.instArgs, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.methodName, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.methodSignature, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.properties, System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.typeName, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, and System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.uri.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteCallArray().