Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.ReadArray
ReadArray()
IMethodCallMessage System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.ReadArray (object[] callA, object handlerObject) inline package
Definition at line 163 of file BinaryMethodCall.cs.
        {
            if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsIsArray))
            {
                this.args = callA;
            }
            else
            {
                int num = 0;
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ArgsInArray))
                {
                    if (callA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.args = (object[])callA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.GenericMethod))
                {
                    if (callA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.instArgs = (Type[])callA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.MethodSignatureInArray))
                {
                    if (callA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.methodSignature = callA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.ContextInArray))
                {
                    if (callA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.callContext = callA[num++];
                }
                if (IOUtil.FlagTest(this.messageEnum, MessageEnum.PropertyInArray))
                {
                    if (callA.Length < num)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid MethodCall or MethodReturn stream format."));
                    }
                    this.properties = callA[num++];
                }
            }
            return new MethodCall(handlerObject, new BinaryMethodCallMessage(this.uri, this.methodName, this.typeName, this.instArgs, this.args, this.methodSignature, (LogicalCallContext)this.callContext, (object[])this.properties));
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.args, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.callA, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.callContext, System.Runtime.Serialization.Formatters.Binary.IOUtil.FlagTest(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.instArgs, System.Runtime.Serialization.Formatters.Binary.MethodCall, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.methodName, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.methodSignature, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.properties, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.typeName, and System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.uri.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize().