Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonShapes.HourglassRoom.Perform
Perform()
override bool Terraria.GameContent.Generation.Dungeon.DungeonShapes.HourglassRoom.Perform (Point origin, GenAction action) inline
Definition at line 134 of file DungeonShapes.cs.
            {
                int num = this._height / 2;
                for (int i = -num; i <= num; i++)
                {
                    int num2 = origin.Y + i;
                    float num3 = ((float)i + (float)num) / (float)this._height;
                    float num4 = Math.Max(0f, Math.Min(1f, Utils.MultiLerp(Utils.WrappedLerp(0f, 1f, num3), new float[] { 1f, 1f, 0.75f, 0.65f, 0.45f, 0.4f, 0.35f, 0.35f }) + this._percentileAddon));
                    int num5 = (int)((float)this._width * num4) / 2;
                    for (int j = -num5; j <= num5; j++)
                    {
                        int num6 = origin.X + j;
                        if (!base.UnitApply(action, origin, num6, num2, new object[0]) && this._quitOnFail)
{
                            return false;
                        }
                    }
                }
                return true;
            }
References Terraria.GameContent.Generation.Dungeon.DungeonShapes.HourglassRoom._height, Terraria.GameContent.Generation.Dungeon.DungeonShapes.HourglassRoom._percentileAddon, Terraria.WorldBuilding.GenShape._quitOnFail, System.action, int, System.Math.Max(), System.Math.Min(), Terraria.Utils.MultiLerp(), and Terraria.Utils.WrappedLerp().