Terraria Decompiled: System.MathF.IEEERemainder
IEEERemainder()
static float System.MathF.IEEERemainder (float x, float y) inline static
Definition at line 17 of file MathF.cs.
        {
            if (float.IsNaN(x))
            {
                return x;
            }
            if (float.IsNaN(y))
            {
                return y;
            }
            float num = x % y;
            if (float.IsNaN(num))
            {
                return float.NaN;
            }
            if (num == 0f && float.IsNegative(x))
            {
                return -0f;
            }
            float num2 = num - MathF.Abs(y) * (float)MathF.Sign(x);
            if (MathF.Abs(num2) == MathF.Abs(num))
            {
                float num3 = x / y;
                if (MathF.Abs(MathF.Round(num3)) > MathF.Abs(num3))
                {
                    return num2;
                }
                return num;
            }
            else
            {
                if (MathF.Abs(num2) < MathF.Abs(num))
                {
                    return num2;
                }
                return num;
            }
        }
References System.MathF.Abs(), System.MathF.Round(), and System.MathF.Sign().