Terraria Decompiled: System.Threading.ExecutionContextSwitcher.Undo
Undo()
void System.Threading.ExecutionContextSwitcher.Undo () inline package
Definition at line 31 of file ExecutionContextSwitcher.cs.
        {
            if (this.thread == null)
            {
                return;
            }
            Thread thread = this.thread;
            ExecutionContext.Reader executionContextReader = thread.GetExecutionContextReader();
            thread.SetExecutionContext(this.outerEC, this.outerECBelongsToScope);
            this.thread = null;
            ExecutionContext.OnAsyncLocalContextChanged(executionContextReader.DangerousGetRawExecutionContext(), this.outerEC.DangerousGetRawExecutionContext());
        }
References System.Threading.ExecutionContext.Reader.DangerousGetRawExecutionContext(), System.Threading.Thread.GetExecutionContextReader(), System.Threading.ExecutionContext.OnAsyncLocalContextChanged(), System.Threading.ExecutionContextSwitcher.outerEC, System.Threading.ExecutionContextSwitcher.outerECBelongsToScope, System.Threading.Thread.SetExecutionContext(), and System.Threading.ExecutionContextSwitcher.thread.
Referenced by System.Threading.ExecutionContext.RunInternal(), System.Threading.ExecutionContext.RunInternal< TState >(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start< TStateMachine >(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.Start< TStateMachine >(), System.Runtime.CompilerServices.AsyncVoidMethodBuilder.Start< TStateMachine >(), and System.Threading.ExecutionContextSwitcher.UndoNoThrow().