Terraria Decompiled: Terraria.Audio.LegacySoundPlayer.CreateAllSoundInstances
CreateAllSoundInstances()
void Terraria.Audio.LegacySoundPlayer.CreateAllSoundInstances () inline
Definition at line 118 of file LegacySoundPlayer.cs.
        {
            foreach (SoundEffectInstance soundEffectInstance in this._trackedInstances)
            {
                soundEffectInstance.Dispose();
            }
            this._trackedInstances.Clear();
            this.SoundInstanceMech[0] = this.CreateInstance(this.SoundMech[0]);
            this.SoundInstanceGrab = this.CreateInstance(this.SoundGrab);
            this.SoundInstancePixie = this.CreateInstance(this.SoundGrab);
            this.SoundInstanceDig[0] = this.CreateInstance(this.SoundDig[0]);
            this.SoundInstanceDig[1] = this.CreateInstance(this.SoundDig[1]);
            this.SoundInstanceDig[2] = this.CreateInstance(this.SoundDig[2]);
            this.SoundInstanceTink[0] = this.CreateInstance(this.SoundTink[0]);
            this.SoundInstanceTink[1] = this.CreateInstance(this.SoundTink[1]);
            this.SoundInstanceTink[2] = this.CreateInstance(this.SoundTink[2]);
            this.SoundInstancePlayerHit[0] = this.CreateInstance(this.SoundPlayerHit[0]);
            this.SoundInstancePlayerHit[1] = this.CreateInstance(this.SoundPlayerHit[1]);
            this.SoundInstancePlayerHit[2] = this.CreateInstance(this.SoundPlayerHit[2]);
            this.SoundInstanceFemaleHit[0] = this.CreateInstance(this.SoundFemaleHit[0]);
            this.SoundInstanceFemaleHit[1] = this.CreateInstance(this.SoundFemaleHit[1]);
            this.SoundInstanceFemaleHit[2] = this.CreateInstance(this.SoundFemaleHit[2]);
            this.SoundInstancePlayerKilled = this.CreateInstance(this.SoundPlayerKilled);
            this.SoundInstanceChat = this.CreateInstance(this.SoundChat);
            this.SoundInstanceGrass = this.CreateInstance(this.SoundGrass);
            this.SoundInstanceDoorOpen = this.CreateInstance(this.SoundDoorOpen);
            this.SoundInstanceDoorClosed = this.CreateInstance(this.SoundDoorClosed);
            this.SoundInstanceMenuTick = this.CreateInstance(this.SoundMenuTick);
            this.SoundInstanceMenuOpen = this.CreateInstance(this.SoundMenuOpen);
            this.SoundInstanceMenuClose = this.CreateInstance(this.SoundMenuClose);
            this.SoundInstanceShatter = this.CreateInstance(this.SoundShatter);
            this.SoundInstanceCamera = this.CreateInstance(this.SoundCamera);
            this.SoundInstanceSplash[0] = this.CreateInstance(this.SoundRoar[0]);
            this.SoundInstanceSplash[1] = this.CreateInstance(this.SoundSplash[1]);
            this.SoundInstanceDoubleJump = this.CreateInstance(this.SoundRoar[0]);
            this.SoundInstanceRun = this.CreateInstance(this.SoundRun);
            this.SoundInstanceCoins = this.CreateInstance(this.SoundCoins);
            this.SoundInstanceUnlock = this.CreateInstance(this.SoundUnlock);
            this.SoundInstanceMaxMana = this.CreateInstance(this.SoundMaxMana);
            this.SoundInstanceDrown = this.CreateInstance(this.SoundDrown);
            this.SoundInstanceMoonlordCry = this.CreateInstance(this.SoundNpcKilled[10]);
            for (int i = 0; i < this.SoundThunder.Length; i++)
            {
                this.SoundInstanceThunder[i] = this.CreateInstance(this.SoundThunder[i]);
            }
            for (int j = 0; j < this.SoundResearch.Length; j++)
            {
                this.SoundInstanceResearch[j] = this.CreateInstance(this.SoundResearch[j]);
            }
            for (int k = 0; k < this.SoundCoin.Length; k++)
            {
                this.SoundInstanceCoin[k] = this.CreateInstance(this.SoundCoin[k]);
            }
            for (int l = 0; l < this.SoundDrip.Length; l++)
            {
                this.SoundInstanceDrip[l] = this.CreateInstance(this.SoundDrip[l]);
            }
            for (int m = 0; m < this.SoundZombie.Length; m++)
            {
                this.SoundInstanceZombie[m] = this.CreateInstance(this.SoundZombie[m]);
            }
            for (int n = 0; n < this.SoundLiquid.Length; n++)
            {
                this.SoundInstanceLiquid[n] = this.CreateInstance(this.SoundLiquid[n]);
            }
            for (int num = 0; num < this.SoundRoar.Length; num++)
            {
                this.SoundInstanceRoar[num] = this.CreateInstance(this.SoundRoar[num]);
            }
            for (int num2 = 1; num2 < this.SoundItem.Length; num2++)
            {
                this.SoundInstanceItem[num2] = this.CreateInstance(this.SoundItem[num2]);
            }
            for (int num3 = 1; num3 < this.SoundNpcHit.Length; num3++)
            {
                this.SoundInstanceNpcHit[num3] = this.CreateInstance(this.SoundNpcHit[num3]);
            }
            for (int num4 = 1; num4 < this.SoundNpcKilled.Length; num4++)
            {
                this.SoundInstanceNpcKilled[num4] = this.CreateInstance(this.SoundNpcKilled[num4]);
            }
            for (int num5 = 0; num5 < this.TrackableSounds.Length; num5++)
            {
                this.TrackableSoundInstances[num5] = this.CreateInstance(this.TrackableSounds[num5]);
            }
        }
References Terraria.Audio.LegacySoundPlayer._trackedInstances, Terraria.Audio.LegacySoundPlayer.CreateInstance(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.Dispose(), Terraria.Audio.LegacySoundPlayer.SoundCamera, Terraria.Audio.LegacySoundPlayer.SoundChat, Terraria.Audio.LegacySoundPlayer.SoundCoin, Terraria.Audio.LegacySoundPlayer.SoundCoins, Terraria.Audio.LegacySoundPlayer.SoundDig, Terraria.Audio.LegacySoundPlayer.SoundDoorClosed, Terraria.Audio.LegacySoundPlayer.SoundDoorOpen, Terraria.Audio.LegacySoundPlayer.SoundDrip, Terraria.Audio.LegacySoundPlayer.SoundDrown, Terraria.Audio.LegacySoundPlayer.SoundFemaleHit, Terraria.Audio.LegacySoundPlayer.SoundGrab, Terraria.Audio.LegacySoundPlayer.SoundGrass, Terraria.Audio.LegacySoundPlayer.SoundInstanceCoin, Terraria.Audio.LegacySoundPlayer.SoundInstanceDig, Terraria.Audio.LegacySoundPlayer.SoundInstanceDrip, Terraria.Audio.LegacySoundPlayer.SoundInstanceFemaleHit, Terraria.Audio.LegacySoundPlayer.SoundInstanceItem, Terraria.Audio.LegacySoundPlayer.SoundInstanceLiquid, Terraria.Audio.LegacySoundPlayer.SoundInstanceMech, Terraria.Audio.LegacySoundPlayer.SoundInstanceNpcHit, Terraria.Audio.LegacySoundPlayer.SoundInstanceNpcKilled, Terraria.Audio.LegacySoundPlayer.SoundInstancePlayerHit, Terraria.Audio.LegacySoundPlayer.SoundInstanceResearch, Terraria.Audio.LegacySoundPlayer.SoundInstanceRoar, Terraria.Audio.LegacySoundPlayer.SoundInstanceSplash, Terraria.Audio.LegacySoundPlayer.SoundInstanceThunder, Terraria.Audio.LegacySoundPlayer.SoundInstanceTink, Terraria.Audio.LegacySoundPlayer.SoundInstanceZombie, Terraria.Audio.LegacySoundPlayer.SoundItem, Terraria.Audio.LegacySoundPlayer.SoundLiquid, Terraria.Audio.LegacySoundPlayer.SoundMaxMana, Terraria.Audio.LegacySoundPlayer.SoundMech, Terraria.Audio.LegacySoundPlayer.SoundMenuClose, Terraria.Audio.LegacySoundPlayer.SoundMenuOpen, Terraria.Audio.LegacySoundPlayer.SoundMenuTick, Terraria.Audio.LegacySoundPlayer.SoundNpcHit, Terraria.Audio.LegacySoundPlayer.SoundNpcKilled, Terraria.Audio.LegacySoundPlayer.SoundPlayerHit, Terraria.Audio.LegacySoundPlayer.SoundPlayerKilled, Terraria.Audio.LegacySoundPlayer.SoundResearch, Terraria.Audio.LegacySoundPlayer.SoundRoar, Terraria.Audio.LegacySoundPlayer.SoundRun, Terraria.Audio.LegacySoundPlayer.SoundShatter, Terraria.Audio.LegacySoundPlayer.SoundSplash, Terraria.Audio.LegacySoundPlayer.SoundThunder, Terraria.Audio.LegacySoundPlayer.SoundTink, Terraria.Audio.LegacySoundPlayer.SoundUnlock, Terraria.Audio.LegacySoundPlayer.SoundZombie, Terraria.Audio.LegacySoundPlayer.TrackableSoundInstances, and Terraria.Audio.LegacySoundPlayer.TrackableSounds.
Referenced by Terraria.Audio.LegacySoundPlayer.Reload().