Terraria Decompiled: System.RuntimeType.GetGenericTypeDefinition
GetGenericTypeDefinition()
override Type System.RuntimeType.GetGenericTypeDefinition () inline
Definition at line 1419 of file RuntimeType.cs.
        {
            if (!this.IsGenericType)
            {
                throw new InvalidOperationException(Environment.GetResourceString("This operation is only valid on generic types."));
            }
            return RuntimeTypeHandle.GetGenericTypeDefinition(this);
        }
References System.RuntimeTypeHandle.GetGenericTypeDefinition(), System.Environment.GetResourceString(), and System.RuntimeType.IsGenericType.
Referenced by System.Collections.Generic.Comparer< T >.CreateComparer(), System.Collections.Generic.EqualityComparer< T >.CreateComparer(), and System.UnitySerializationHolder.GetUnitySerializationInfo().