Terraria Decompiled: System.RuntimeType.IsEquivalentTo
IsEquivalentTo()
override bool System.RuntimeType.IsEquivalentTo (Type other) inline
Definition at line 981 of file RuntimeType.cs.
        {
            RuntimeType runtimeType = other as RuntimeType;
            return runtimeType != null && (runtimeType == this || RuntimeTypeHandle.IsEquivalentTo(this, runtimeType));
        }
References System.RuntimeTypeHandle.IsEquivalentTo(), and System.RuntimeType.RuntimeType().
Referenced by System.RuntimeType.IsEnumDefined().