Terraria Decompiled: System.RuntimeType.GetSerializationCtor
GetSerializationCtor()
RuntimeConstructorInfo System.RuntimeType.GetSerializationCtor () inline package
Definition at line 2191 of file RuntimeType.cs.
        {
            if (this.m_serializationCtor == null)
            {
                Type[] array = new Type[]
                {
                    typeof(SerializationInfo),
                    typeof(StreamingContext)
                };
                this.m_serializationCtor = base.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, CallingConventions.Any, array, null) as RuntimeConstructorInfo;
            }
            return this.m_serializationCtor;
        }
References System.array, System.Type.GetConstructor(), and System.RuntimeType.m_serializationCtor.
Referenced by System.Runtime.Serialization.ObjectManager.GetConstructor(), and System.Runtime.Serialization.SafeSerializationManager.GetRealObject().