Terraria Decompiled: System.RuntimeType.CreateInstanceMono
CreateInstanceMono()
object System.RuntimeType.CreateInstanceMono (bool nonPublic, bool wrapExceptions) inline private
Definition at line 2216 of file RuntimeType.cs.
        {
            RuntimeConstructorInfo runtimeConstructorInfo = this.GetDefaultConstructor();
            if (!nonPublic && runtimeConstructorInfo != null && !runtimeConstructorInfo.IsPublic)
            {
                runtimeConstructorInfo = null;
            }
            if (runtimeConstructorInfo == null)
            {
                Type rootElementType = base.GetRootElementType();
                if (rootElementType == typeof(TypedReference) || rootElementType == typeof(RuntimeArgumentHandle))
                {
                    throw new NotSupportedException(Environment.GetResourceString("Cannot create boxed TypedReference, ArgIterator, or RuntimeArgumentHandle Objects."));
                }
                if (base.IsValueType)
                {
                    return RuntimeType.CreateInstanceInternal(this);
                }
                throw new MissingMethodException("Default constructor not found for type " + this.FullName);
            }
            else
            {
                if (base.IsAbstract)
                {
                    throw new MissingMethodException("Cannot create an abstract class '{0}'.", this.FullName);
                }
                return runtimeConstructorInfo.InternalInvoke(null, null, wrapExceptions);
            }
        }
References System.RuntimeType.CreateInstanceInternal(), System.RuntimeType.FullName, System.RuntimeType.GetDefaultConstructor(), System.Environment.GetResourceString(), System.Type.GetRootElementType(), System.Reflection.RuntimeConstructorInfo.InternalInvoke(), and System.Reflection.MethodBase.IsPublic.
Referenced by System.RuntimeType.CreateInstanceSlow().