Terraria Decompiled: System.RuntimeType.GetMember
GetMember()
override MemberInfo[] System.RuntimeType.GetMember (string name, MemberTypes type, BindingFlags bindingAttr) inline
Definition at line 776 of file RuntimeType.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException();
            }
            RuntimeType.ListBuilder<MethodInfo> listBuilder = default(RuntimeType.ListBuilder<MethodInfo>);
            RuntimeType.ListBuilder<ConstructorInfo> listBuilder2 = default(RuntimeType.ListBuilder<ConstructorInfo>);
            RuntimeType.ListBuilder<PropertyInfo> listBuilder3 = default(RuntimeType.ListBuilder<PropertyInfo>);
            RuntimeType.ListBuilder<EventInfo> listBuilder4 = default(RuntimeType.ListBuilder<EventInfo>);
            RuntimeType.ListBuilder<FieldInfo> listBuilder5 = default(RuntimeType.ListBuilder<FieldInfo>);
            RuntimeType.ListBuilder<Type> listBuilder6 = default(RuntimeType.ListBuilder<Type>);
            int num = 0;
            if ((type & MemberTypes.Method) != (MemberTypes)0)
            {
                listBuilder = this.GetMethodCandidates(name, bindingAttr, CallingConventions.Any, null, -1, true);
                if (type == MemberTypes.Method)
                {
                    return listBuilder.ToArray();
                }
                num += listBuilder.Count;
            }
            if ((type & MemberTypes.Constructor) != (MemberTypes)0)
            {
                listBuilder2 = this.GetConstructorCandidates(name, bindingAttr, CallingConventions.Any, null, true);
                if (type == MemberTypes.Constructor)
                {
                    return listBuilder2.ToArray();
                }
                num += listBuilder2.Count;
            }
            if ((type & MemberTypes.Property) != (MemberTypes)0)
            {
                listBuilder3 = this.GetPropertyCandidates(name, bindingAttr, null, true);
                if (type == MemberTypes.Property)
                {
                    return listBuilder3.ToArray();
                }
                num += listBuilder3.Count;
            }
            if ((type & MemberTypes.Event) != (MemberTypes)0)
            {
                listBuilder4 = this.GetEventCandidates(name, bindingAttr, true);
                if (type == MemberTypes.Event)
                {
                    return listBuilder4.ToArray();
                }
                num += listBuilder4.Count;
            }
            if ((type & MemberTypes.Field) != (MemberTypes)0)
            {
                listBuilder5 = this.GetFieldCandidates(name, bindingAttr, true);
                if (type == MemberTypes.Field)
                {
                    return listBuilder5.ToArray();
                }
                num += listBuilder5.Count;
            }
            if ((type & (MemberTypes.TypeInfo | MemberTypes.NestedType)) != (MemberTypes)0)
            {
                listBuilder6 = this.GetNestedTypeCandidates(name, bindingAttr, true);
                if (type == MemberTypes.NestedType || type == MemberTypes.TypeInfo)
                {
                    return listBuilder6.ToArray();
                }
                num += listBuilder6.Count;
            }
            MemberInfo[] array;
            if (type != (MemberTypes.Constructor | MemberTypes.Method))
            {
                array = new MemberInfo[num];
            }
            else
            {
                MemberInfo[] array2 = new MethodBase[num];
                array = array2;
            }
            MemberInfo[] array3 = array;
            int num2 = 0;
            object[] array4 = array3;
            listBuilder.CopyTo(array4, num2);
            num2 += listBuilder.Count;
            array4 = array3;
            listBuilder2.CopyTo(array4, num2);
            num2 += listBuilder2.Count;
            array4 = array3;
            listBuilder3.CopyTo(array4, num2);
            num2 += listBuilder3.Count;
            array4 = array3;
            listBuilder4.CopyTo(array4, num2);
            num2 += listBuilder4.Count;
            array4 = array3;
            listBuilder5.CopyTo(array4, num2);
            num2 += listBuilder5.Count;
            array4 = array3;
            listBuilder6.CopyTo(array4, num2);
            num2 += listBuilder6.Count;
            return array3;
        }
References System.array, System.RuntimeType.GetConstructorCandidates(), System.RuntimeType.GetEventCandidates(), System.RuntimeType.GetFieldCandidates(), System.RuntimeType.GetMethodCandidates(), System.RuntimeType.GetNestedTypeCandidates(), System.RuntimeType.GetPropertyCandidates(), and System.name.
Referenced by System.Reflection.MemberInfoSerializationHolder.GetRealObject(), and System.RuntimeType.InvokeMember().