Terraria Decompiled: System.RuntimeType.GetInterface
GetInterface()
override Type System.RuntimeType.GetInterface (string fullname, bool ignoreCase) inline
Definition at line 695 of file RuntimeType.cs.
        {
            if (fullname == null)
            {
                throw new ArgumentNullException();
            }
            BindingFlags bindingFlags = BindingFlags.Public | BindingFlags.NonPublic;
            bindingFlags &= ~BindingFlags.Static;
            if (ignoreCase)
            {
                bindingFlags |= BindingFlags.IgnoreCase;
            }
            string text;
            string text2;
            RuntimeType.SplitName(fullname, out text, out text2);
            RuntimeType.MemberListType memberListType;
            RuntimeType.FilterHelper(bindingFlags, ref text, out ignoreCase, out memberListType);
            List<RuntimeType> list = null;
            StringComparison stringComparison = (ignoreCase ? StringComparison.OrdinalIgnoreCase : StringComparison.Ordinal);
            foreach (RuntimeType runtimeType in this.GetInterfaces())
            {
                if (string.Equals(runtimeType.Name, text, stringComparison))
                {
                    if (list == null)
                    {
                        list = new List<RuntimeType>(2);
                    }
                    list.Add(runtimeType);
                }
            }
            if (list == null)
            {
                return null;
            }
            RuntimeType[] array = list.ToArray();
            RuntimeType runtimeType2 = null;
            foreach (RuntimeType runtimeType3 in array)
            {
                if (RuntimeType.FilterApplyType(runtimeType3, bindingFlags, text, false, text2))
                {
                    if (runtimeType2 != null)
                    {
                        throw new AmbiguousMatchException(Environment.GetResourceString("Ambiguous match found."));
                    }
                    runtimeType2 = runtimeType3;
                }
            }
            return runtimeType2;
        }
References System.array, System.RuntimeType.Equals(), System.RuntimeType.FilterApplyType(), System.RuntimeType.FilterHelper(), System.RuntimeType.GetInterfaces(), System.Environment.GetResourceString(), System.list, System.RuntimeType.Name, System.RuntimeType.SplitName(), and System.text.