Terraria Decompiled: System.RuntimeType.ActivationCreateInstance
ActivationCreateInstance()
object System.RuntimeType.ActivationCreateInstance (MethodBase invokeMethod, BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes) inline private
Definition at line 2087 of file RuntimeType.cs.
        {
            object obj = ActivationServices.CreateProxyFromAttributes(this, activationAttributes);
            if (obj != null)
            {
                invokeMethod.Invoke(obj, bindingAttr, binder, args, culture);
            }
            return obj;
        }
References System.Runtime.Remoting.Activation.ActivationServices.CreateProxyFromAttributes(), System.culture, System.Reflection.MethodBase.Invoke(), and System.obj.
Referenced by System.RuntimeType.CreateInstanceImpl().