Terraria Decompiled: System.RuntimeType.FilterApplyMethodBase
FilterApplyMethodBase()
static bool System.RuntimeType.FilterApplyMethodBase (MethodBase methodBase, BindingFlags methodFlags, BindingFlags bindingFlags, CallingConventions callConv, Type[] argumentTypes) inline static private
Definition at line 248 of file RuntimeType.cs.
        {
            bindingFlags ^= BindingFlags.DeclaredOnly;
            if ((callConv & CallingConventions.Any) == (CallingConventions)0)
            {
                if ((callConv & CallingConventions.VarArgs) != (CallingConventions)0 && (methodBase.CallingConvention & CallingConventions.VarArgs) == (CallingConventions)0)
                {
                    return false;
                }
                if ((callConv & CallingConventions.Standard) != (CallingConventions)0 && (methodBase.CallingConvention & CallingConventions.Standard) == (CallingConventions)0)
                {
                    return false;
                }
            }
            if (argumentTypes != null)
            {
                ParameterInfo[] parametersNoCopy = methodBase.GetParametersNoCopy();
                if (argumentTypes.Length != parametersNoCopy.Length)
                {
                    if ((bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.CreateInstance | BindingFlags.GetProperty | BindingFlags.SetProperty)) == BindingFlags.Default)
                    {
                        return false;
                    }
                    bool flag = false;
                    if (argumentTypes.Length > parametersNoCopy.Length)
                    {
                        if ((methodBase.CallingConvention & CallingConventions.VarArgs) == (CallingConventions)0)
{
                            flag = true;
                        }
                    }
                    else if ((bindingFlags & BindingFlags.OptionalParamBinding) == BindingFlags.Default)
                    {
                        flag = true;
                    }
                    else if (!parametersNoCopy[argumentTypes.Length].IsOptional)
                    {
                        flag = true;
                    }
                    if (flag)
                    {
                        if (parametersNoCopy.Length == 0)
{
                            return false;
                        }
                        if (argumentTypes.Length < parametersNoCopy.Length - 1)
{
                            return false;
                        }
                        ParameterInfo parameterInfo = parametersNoCopy[parametersNoCopy.Length - 1];
                        if (!parameterInfo.ParameterType.IsArray)
{
                            return false;
                        }
                        if (!parameterInfo.IsDefined(typeof(ParamArrayAttribute), false))
{
                            return false;
                        }
                    }
                }
                else if ((bindingFlags & BindingFlags.ExactBinding) != BindingFlags.Default && (bindingFlags & BindingFlags.InvokeMethod) == BindingFlags.Default)
                {
                    for (int i = 0; i < parametersNoCopy.Length; i++)
                    {
                        if (argumentTypes[i] != null && !argumentTypes[i].MatchesParameterTypeExactly(parametersNoCopy[i]))
{
                            return false;
                        }
                    }
                }
            }
            return true;
        }
References System.Reflection.MethodBase.CallingConvention, System.Reflection.MethodBase.GetParametersNoCopy(), System.Type.IsArray, System.Reflection.ParameterInfo.IsDefined(), System.Reflection.ParameterInfo.IsOptional, and System.Reflection.ParameterInfo.ParameterType.
Referenced by System.RuntimeType.FilterApplyConstructorInfo(), and System.RuntimeType.FilterApplyMethodInfo().