Terraria Decompiled: System.RuntimeType.SanityCheckGenericArguments
SanityCheckGenericArguments()
static void System.RuntimeType.SanityCheckGenericArguments (RuntimeType[] genericArguments, RuntimeType[] genericParamters) inline static package
Definition at line 44 of file RuntimeType.cs.
        {
            if (genericArguments == null)
            {
                throw new ArgumentNullException();
            }
            for (int i = 0; i < genericArguments.Length; i++)
            {
                if (genericArguments[i] == null)
                {
                    throw new ArgumentNullException();
                }
                RuntimeType.ThrowIfTypeNeverValidGenericArgument(genericArguments[i]);
            }
            if (genericArguments.Length != genericParamters.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("The type or method has {1} generic parameter(s), but {0} generic argument(s) were provided. A generic argument must be provided for each generic parameter.", new object[] { genericArguments.Length, genericParamters.Length }));
            }
        }
References System.Environment.GetResourceString(), and System.RuntimeType.ThrowIfTypeNeverValidGenericArgument().
Referenced by System.RuntimeType.MakeGenericType().