Terraria Decompiled: System.RuntimeType.GetConstructorImpl
GetConstructorImpl()
override ConstructorInfo System.RuntimeType.GetConstructorImpl (BindingFlags bindingAttr, Binder binder, CallingConventions callConvention, Type[] types, ParameterModifier[] modifiers) inline protected
Definition at line 555 of file RuntimeType.cs.
        {
            RuntimeType.ListBuilder<ConstructorInfo> constructorCandidates = this.GetConstructorCandidates(null, bindingAttr, CallingConventions.Any, types, false);
            if (constructorCandidates.Count == 0)
            {
                return null;
            }
            if (types.Length == 0 && constructorCandidates.Count == 1)
            {
                ConstructorInfo constructorInfo = constructorCandidates[0];
                ParameterInfo[] parametersNoCopy = constructorInfo.GetParametersNoCopy();
                if (parametersNoCopy == null || parametersNoCopy.Length == 0)
                {
                    return constructorInfo;
                }
            }
            MethodBase[] array;
            if ((bindingAttr & BindingFlags.ExactBinding) != BindingFlags.Default)
            {
                array = constructorCandidates.ToArray();
                return global::System.DefaultBinder.ExactBinding(array, types, modifiers) as ConstructorInfo;
            }
            if (binder == null)
            {
                binder = Type.DefaultBinder;
            }
            Binder binder2 = binder;
            array = constructorCandidates.ToArray();
            return binder2.SelectMethod(bindingAttr, array, types, modifiers) as ConstructorInfo;
        }
References System.array, System.Type.DefaultBinder, System.RuntimeType.GetConstructorCandidates(), System.Reflection.MethodBase.GetParametersNoCopy(), and System.Reflection.Binder.SelectMethod().