Terraria Decompiled: System.RuntimeType.TryConvertToType
TryConvertToType()
object System.RuntimeType.TryConvertToType (object value, ref bool failed) inline private
Definition at line 2267 of file RuntimeType.cs.
        {
            if (this.IsInstanceOfType(value))
            {
                return value;
            }
            if (base.IsByRef)
            {
                Type elementType = this.GetElementType();
                if (value == null || elementType.IsInstanceOfType(value))
                {
                    return value;
                }
            }
            if (value == null)
            {
                return value;
            }
            if (this.IsEnum)
            {
                if (Enum.GetUnderlyingType(this) == value.GetType())
                {
                    return value;
                }
                object obj = RuntimeType.IsConvertibleToPrimitiveType(value, this);
                if (obj != null)
                {
                    return obj;
                }
            }
            else if (base.IsPrimitive)
            {
                object obj2 = RuntimeType.IsConvertibleToPrimitiveType(value, this);
                if (obj2 != null)
                {
                    return obj2;
                }
            }
            else if (base.IsPointer)
            {
                Type type = value.GetType();
                if (type == typeof(IntPtr) || type == typeof(UIntPtr))
                {
                    return value;
                }
            }
            failed = true;
            return null;
        }
References System.RuntimeType.GetElementType(), System.Type.GetType(), System.Enum.GetUnderlyingType(), System.RuntimeType.IsConvertibleToPrimitiveType(), System.RuntimeType.IsEnum, System.RuntimeType.IsInstanceOfType(), System.Type.IsInstanceOfType(), System.obj, and System.value.
Referenced by System.RuntimeType.CheckValue().