Terraria Decompiled: System.RuntimeType.GetMethodsByName
GetMethodsByName()
RuntimeMethodInfo[] System.RuntimeType.GetMethodsByName (string name, BindingFlags bindingAttr, RuntimeType::MemberListType listType, RuntimeType reflectedType) inline package
Definition at line 2596 of file RuntimeType.cs.
        {
            RuntimeTypeHandle runtimeTypeHandle = new RuntimeTypeHandle(reflectedType);
            RuntimeMethodInfo[] array2;
            using (SafeStringMarshal safeStringMarshal = new SafeStringMarshal(name))
            {
                using (SafeGPtrArrayHandle safeGPtrArrayHandle = new SafeGPtrArrayHandle(this.GetMethodsByName_native(safeStringMarshal.Value, bindingAttr, listType)))
                {
                    int length = safeGPtrArrayHandle.Length;
                    RuntimeMethodInfo[] array = new RuntimeMethodInfo[length];
                    for (int i = 0; i < length; i++)
                    {
                        RuntimeMethodHandle runtimeMethodHandle = new RuntimeMethodHandle(safeGPtrArrayHandle[i]);
                        array[i] = (RuntimeMethodInfo)RuntimeMethodInfo.GetMethodFromHandleNoGenericCheck(runtimeMethodHandle, runtimeTypeHandle);
                    }
                    array2 = array;
                }
            }
            return array2;
        }
References System.array, System.Reflection.RuntimeMethodInfo.GetMethodFromHandleNoGenericCheck(), System.RuntimeType.GetMethodsByName_native(), Mono.SafeGPtrArrayHandle.Length, System.length, System.name, and Mono.SafeStringMarshal.Value.
Referenced by System.RuntimeType.GetMethodCandidates(), System.RuntimeType.GetMethodCandidates(), and System.Runtime.Remoting.RemotingServices.IsMethodOverloaded().