Terraria Decompiled: System.RuntimeType.GetNestedType
GetNestedType()
override Type System.RuntimeType.GetNestedType (string fullname, BindingFlags bindingAttr) inline
Definition at line 746 of file RuntimeType.cs.
        {
            if (fullname == null)
            {
                throw new ArgumentNullException();
            }
            bindingAttr &= ~BindingFlags.Static;
            string text;
            string text2;
            RuntimeType.SplitName(fullname, out text, out text2);
            bool flag;
            RuntimeType.MemberListType memberListType;
            RuntimeType.FilterHelper(bindingAttr, ref text, out flag, out memberListType);
            RuntimeType[] nestedTypes_internal = this.GetNestedTypes_internal(text, bindingAttr, memberListType);
            RuntimeType runtimeType = null;
            foreach (RuntimeType runtimeType2 in nestedTypes_internal)
            {
                if (RuntimeType.FilterApplyType(runtimeType2, bindingAttr, text, false, text2))
                {
                    if (runtimeType != null)
                    {
                        throw new AmbiguousMatchException(Environment.GetResourceString("Ambiguous match found."));
                    }
                    runtimeType = runtimeType2;
                }
            }
            return runtimeType;
        }
References System.RuntimeType.FilterApplyType(), System.RuntimeType.FilterHelper(), System.RuntimeType.GetNestedTypes_internal(), System.Environment.GetResourceString(), System.RuntimeType.SplitName(), and System.text.