Terraria Decompiled: System.RuntimeType.GetMethodCandidates
GetMethodCandidates() [1/2]
RuntimeType.ListBuilder< MethodInfo > System.RuntimeType.GetMethodCandidates (string name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, int genericParamCount, bool allowPrefixLookup) inline private
Definition at line 344 of file RuntimeType.cs.
        {
            bool flag;
            bool flag2;
            RuntimeType.MemberListType memberListType;
            RuntimeType.FilterHelper(bindingAttr, ref name, allowPrefixLookup, out flag, out flag2, out memberListType);
            RuntimeMethodInfo[] methodsByName = this.GetMethodsByName(name, bindingAttr, memberListType, this);
            RuntimeType.ListBuilder<MethodInfo> listBuilder = new RuntimeType.ListBuilder<MethodInfo>(methodsByName.Length);
            int i = 0;
            while (i < methodsByName.Length)
            {
                RuntimeMethodInfo runtimeMethodInfo = methodsByName[i];
                if (genericParamCount == -1)
                {
                    goto IL_005E;
                }
                bool isGenericMethod = runtimeMethodInfo.IsGenericMethod;
                if ((genericParamCount != 0 || !isGenericMethod) && (genericParamCount <= 0 || isGenericMethod) && runtimeMethodInfo.GetGenericArguments().Length == genericParamCount)
                {
                    goto IL_005E;
                }
                IL_0082:
                i++;
                continue;
                IL_005E:
                if (RuntimeType.FilterApplyMethodInfo(runtimeMethodInfo, bindingAttr, callConv, types) && (!flag || RuntimeType.FilterApplyPrefixLookup(runtimeMethodInfo, name, flag2)))
                {
                    listBuilder.Add(runtimeMethodInfo);
                    goto IL_0082;
                }
                goto IL_0082;
            }
            return listBuilder;
        }
References System.RuntimeType.FilterApplyMethodInfo(), System.RuntimeType.FilterApplyPrefixLookup(), System.RuntimeType.FilterHelper(), System.Reflection.RuntimeMethodInfo.GetGenericArguments(), System.RuntimeType.GetMethodsByName(), System.Reflection.RuntimeMethodInfo.IsGenericMethod, and System.name.
Referenced by System.RuntimeType.GetMember(), System.RuntimeType.GetMembers(), System.RuntimeType.GetMethodImplCommon(), and System.RuntimeType.GetMethods().