Terraria Decompiled: System.RuntimeType.MakeGenericType
MakeGenericType() [1/2]
override Type System.RuntimeType.MakeGenericType (params Type[] instantiation) inline
Definition at line 1325 of file RuntimeType.cs.
        {
            if (instantiation == null)
            {
                throw new ArgumentNullException("instantiation");
            }
            RuntimeType[] array = new RuntimeType[instantiation.Length];
            if (!this.IsGenericTypeDefinition)
            {
                throw new InvalidOperationException(Environment.GetResourceString("{0} is not a GenericTypeDefinition. MakeGenericType may only be called on a type for which Type.IsGenericTypeDefinition is true.", new object[] { this }));
            }
            if (this.GetGenericArguments().Length != instantiation.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("The number of generic arguments provided doesn't equal the arity of the generic type definition."), "instantiation");
            }
            int i = 0;
            while (i < instantiation.Length)
            {
                Type type = instantiation[i];
                if (type == null)
                {
                    throw new ArgumentNullException();
                }
                RuntimeType runtimeType = type as RuntimeType;
                if (runtimeType == null)
                {
                    if (type.IsSignatureType)
                    {
                        return Type.MakeGenericSignatureType(this, instantiation);
                    }
                    Type[] array2 = new Type[instantiation.Length];
                    for (int j = 0; j < instantiation.Length; j++)
                    {
                        array2[j] = instantiation[j];
                    }
                    instantiation = array2;
                    if (!RuntimeFeature.IsDynamicCodeSupported)
                    {
                        throw new PlatformNotSupportedException();
                    }
                    return RuntimeType.MakeTypeBuilderInstantiation(this, instantiation);
                }
                else
                {
                    array[i] = runtimeType;
                    i++;
                }
            }
            RuntimeType[] genericArgumentsInternal = this.GetGenericArgumentsInternal();
            RuntimeType.SanityCheckGenericArguments(array, genericArgumentsInternal);
            Type[] array3 = array;
            Type type2 = RuntimeType.MakeGenericType(this, array3);
            if (type2 == null)
            {
                throw new TypeLoadException();
            }
            return type2;
        }
References System.array, System.RuntimeType.GetGenericArguments(), System.RuntimeType.GetGenericArgumentsInternal(), System.Environment.GetResourceString(), System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported, System.RuntimeType.IsGenericTypeDefinition, System.Type.IsSignatureType, System.Type.MakeGenericSignatureType(), System.RuntimeType.MakeGenericType(), System.RuntimeType.MakeTypeBuilderInstantiation, System.RuntimeType.RuntimeType(), and System.RuntimeType.SanityCheckGenericArguments().
Referenced by System.RuntimeType.CreateInstanceForAnotherGenericParameter(), and System.RuntimeType.MakeGenericType().