Terraria Decompiled: System.RuntimeType.IsEnumDefined
IsEnumDefined()
override bool System.RuntimeType.IsEnumDefined (object value) inline
Definition at line 1231 of file RuntimeType.cs.
        {
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            RuntimeType runtimeType = (RuntimeType)value.GetType();
            if (runtimeType.IsEnum)
            {
                if (!runtimeType.IsEquivalentTo(this))
                {
                    throw new ArgumentException(Environment.GetResourceString("Object must be the same type as the enum. The type passed in was '{0}'; the enum type was '{1}'.", new object[]
                    {
                        runtimeType.ToString(),
                        this.ToString()
                    }));
                }
                runtimeType = (RuntimeType)runtimeType.GetEnumUnderlyingType();
            }
            if (runtimeType == RuntimeType.StringType)
            {
                object[] array = Enum.InternalGetNames(this);
                return Array.IndexOf<object>(array, value) >= 0;
            }
            if (Type.IsIntegerType(runtimeType))
            {
                RuntimeType runtimeType2 = Enum.InternalGetUnderlyingType(this);
                if (runtimeType2 != runtimeType)
                {
                    throw new ArgumentException(Environment.GetResourceString("Enum underlying type and the object must be same type or object must be a String. Type passed in was '{0}'; the enum underlying type was '{1}'.", new object[]
                    {
                        runtimeType.ToString(),
                        runtimeType2.ToString()
                    }));
                }
                ulong[] array2 = Enum.InternalGetValues(this);
                ulong num = Enum.ToUInt64(value);
                return Array.BinarySearch<ulong>(array2, num) >= 0;
            }
            else
            {
                if (CompatibilitySwitches.IsAppEarlierThanWindowsPhone8)
                {
                    throw new ArgumentException(Environment.GetResourceString("Enum underlying type and the object must be same type or object must be a String. Type passed in was '{0}'; the enum underlying type was '{1}'.", new object[]
                    {
                        runtimeType.ToString(),
                        this.GetEnumUnderlyingType()
                    }));
                }
                throw new InvalidOperationException(Environment.GetResourceString("Unknown enum type."));
            }
        }
References System.array, System.Array.BinarySearch(), System.RuntimeType.GetEnumUnderlyingType(), System.Environment.GetResourceString(), System.RuntimeType.GetType(), System.Array.IndexOf(), System.Enum.InternalGetNames(), System.Enum.InternalGetUnderlyingType(), System.Enum.InternalGetValues(), System.CompatibilitySwitches.IsAppEarlierThanWindowsPhone8, System.RuntimeType.IsEnum, System.RuntimeType.IsEquivalentTo(), System.Type.IsIntegerType(), System.RuntimeType.RuntimeType(), System.RuntimeType.StringType, System.Enum.ToUInt64(), and System.value.