Terraria Decompiled: System.RuntimeType.GetConstructorCandidates
GetConstructorCandidates()
RuntimeType.ListBuilder< ConstructorInfo > System.RuntimeType.GetConstructorCandidates (string name, BindingFlags bindingAttr, CallingConventions callConv, Type[] types, bool allowPrefixLookup) inline private
Definition at line 380 of file RuntimeType.cs.
        {
            bool flag;
            bool flag2;
            RuntimeType.MemberListType memberListType;
            RuntimeType.FilterHelper(bindingAttr, ref name, allowPrefixLookup, out flag, out flag2, out memberListType);
            if ((!flag && name != null && name.Length == 0) || (!string.IsNullOrEmpty(name) && name != ConstructorInfo.ConstructorName && name != ConstructorInfo.TypeConstructorName))
            {
                return new RuntimeType.ListBuilder<ConstructorInfo>(0);
            }
            RuntimeConstructorInfo[] constructors_internal = this.GetConstructors_internal(bindingAttr, this);
            RuntimeType.ListBuilder<ConstructorInfo> listBuilder = new RuntimeType.ListBuilder<ConstructorInfo>(constructors_internal.Length);
            foreach (RuntimeConstructorInfo runtimeConstructorInfo in constructors_internal)
            {
                if (RuntimeType.FilterApplyConstructorInfo(runtimeConstructorInfo, bindingAttr, callConv, types) && (!flag || RuntimeType.FilterApplyPrefixLookup(runtimeConstructorInfo, name, flag2)))
                {
                    listBuilder.Add(runtimeConstructorInfo);
                }
            }
            return listBuilder;
        }
References System.Reflection.ConstructorInfo.ConstructorName, System.RuntimeType.FilterApplyConstructorInfo(), System.RuntimeType.FilterApplyPrefixLookup(), System.RuntimeType.FilterHelper(), System.RuntimeType.GetConstructors_internal(), System.name, and System.Reflection.ConstructorInfo.TypeConstructorName.
Referenced by System.RuntimeType.GetConstructorImpl(), System.RuntimeType.GetConstructors(), System.RuntimeType.GetMember(), and System.RuntimeType.GetMembers().