Terraria Decompiled: System.RuntimeType.GetGenericArguments
GetGenericArguments()
override Type[] System.RuntimeType.GetGenericArguments () inline
Definition at line 1313 of file RuntimeType.cs.
        {
            Type[] array = this.GetGenericArgumentsInternal(false);
            if (array == null)
            {
                array = Array.Empty<Type>();
            }
            return array;
        }
References System.array, and System.RuntimeType.GetGenericArgumentsInternal().
Referenced by System.Collections.Generic.Comparer< T >.CreateComparer(), System.Collections.Generic.EqualityComparer< T >.CreateComparer(), System.UnitySerializationHolder.GetUnitySerializationInfo(), and System.RuntimeType.MakeGenericType().