Terraria Decompiled: System.RuntimeType.IsConvertibleToPrimitiveType
IsConvertibleToPrimitiveType()
static object System.RuntimeType.IsConvertibleToPrimitiveType (object value, Type targetType) inline static private
Definition at line 2318 of file RuntimeType.cs.
        {
            Type type = value.GetType();
            if (type.IsEnum)
            {
                type = Enum.GetUnderlyingType(type);
                if (type == targetType)
                {
                    return value;
                }
            }
            TypeCode typeCode = Type.GetTypeCode(type);
            switch (Type.GetTypeCode(targetType))
            {
            case TypeCode.Char:
                if (typeCode == TypeCode.Byte)
                {
                    return (char)((byte)value);
                }
                if (typeCode == TypeCode.UInt16)
                {
                    return value;
                }
                break;
            case TypeCode.Int16:
                if (typeCode == TypeCode.SByte)
                {
                    return (short)((sbyte)value);
                }
                if (typeCode == TypeCode.Byte)
                {
                    return (short)((byte)value);
                }
                break;
            case TypeCode.UInt16:
                if (typeCode == TypeCode.Char)
                {
                    return value;
                }
                if (typeCode == TypeCode.Byte)
                {
                    return (ushort)((byte)value);
                }
                break;
            case TypeCode.Int32:
                switch (typeCode)
                {
                case TypeCode.Char:
                    return (int)((char)value);
                case TypeCode.SByte:
                    return (int)((sbyte)value);
                case TypeCode.Byte:
                    return (int)((byte)value);
                case TypeCode.Int16:
                    return (int)((short)value);
                case TypeCode.UInt16:
                    return (int)((ushort)value);
                }
                break;
            case TypeCode.UInt32:
                switch (typeCode)
                {
                case TypeCode.Char:
                    return (uint)((char)value);
                case TypeCode.Byte:
                    return (uint)((byte)value);
                case TypeCode.UInt16:
                    return (uint)((ushort)value);
                }
                break;
            case TypeCode.Int64:
                switch (typeCode)
                {
                case TypeCode.Char:
                    return (long)((ulong)((char)value));
                case TypeCode.SByte:
                    return (long)((sbyte)value);
                case TypeCode.Byte:
                    return (long)((ulong)((byte)value));
                case TypeCode.Int16:
                    return (long)((short)value);
                case TypeCode.UInt16:
                    return (long)((ulong)((ushort)value));
                case TypeCode.Int32:
                    return (long)((int)value);
                case TypeCode.UInt32:
                    return (long)((ulong)((uint)value));
                }
                break;
            case TypeCode.UInt64:
                switch (typeCode)
                {
                case TypeCode.Char:
                    return (ulong)((char)value);
                case TypeCode.Byte:
                    return (ulong)((byte)value);
                case TypeCode.UInt16:
                    return (ulong)((ushort)value);
                case TypeCode.UInt32:
                    return (ulong)((uint)value);
                }
                break;
            case TypeCode.Single:
                switch (typeCode)
                {
                case TypeCode.Char:
                    return (float)((char)value);
                case TypeCode.SByte:
                    return (float)((sbyte)value);
                case TypeCode.Byte:
                    return (float)((byte)value);
                case TypeCode.Int16:
                    return (float)((short)value);
                case TypeCode.UInt16:
                    return (float)((ushort)value);
                case TypeCode.Int32:
                    return (float)((int)value);
                case TypeCode.UInt32:
                    return (uint)value;
                case TypeCode.Int64:
                    return (float)((long)value);
                case TypeCode.UInt64:
                    return (ulong)value;
                }
                break;
            case TypeCode.Double:
                switch (typeCode)
                {
                case TypeCode.Char:
                    return (double)((char)value);
                case TypeCode.SByte:
                    return (double)((sbyte)value);
                case TypeCode.Byte:
                    return (double)((byte)value);
                case TypeCode.Int16:
                    return (double)((short)value);
                case TypeCode.UInt16:
                    return (double)((ushort)value);
                case TypeCode.Int32:
                    return (double)((int)value);
                case TypeCode.UInt32:
                    return (uint)value;
                case TypeCode.Int64:
                    return (double)((long)value);
                case TypeCode.UInt64:
                    return (ulong)value;
                case TypeCode.Single:
                    return (double)((float)value);
                }
                break;
            }
            return null;
        }
References System.Type.GetType(), System.Type.GetTypeCode(), System.Enum.GetUnderlyingType(), int, System.Type.IsEnum, long, and System.value.
Referenced by System.RuntimeType.TryConvertToType().