Terraria Decompiled: System.RuntimeType.GetEnumValues
GetEnumValues()
override Array System.RuntimeType.GetEnumValues () inline
Definition at line 1204 of file RuntimeType.cs.
        {
            if (!this.IsEnum)
            {
                throw new ArgumentException(Environment.GetResourceString("Type provided must be an Enum."), "enumType");
            }
            ulong[] array = Enum.InternalGetValues(this);
            Array array2 = Array.CreateInstance(this, array.Length);
            for (int i = 0; i < array.Length; i++)
            {
                object obj = Enum.ToObject(this, array[i]);
                array2.SetValue(obj, i);
            }
            return array2;
        }
References System.array, System.Array.CreateInstance(), System.Environment.GetResourceString(), System.Enum.InternalGetValues(), System.RuntimeType.IsEnum, System.obj, System.Array.SetValue(), and System.Enum.ToObject().