Terraria Decompiled: System.RuntimeType.GetPropertyCandidates
GetPropertyCandidates()
RuntimeType.ListBuilder< PropertyInfo > System.RuntimeType.GetPropertyCandidates (string name, BindingFlags bindingAttr, Type[] types, bool allowPrefixLookup) inline private
Definition at line 403 of file RuntimeType.cs.
        {
            bool flag;
            bool flag2;
            RuntimeType.MemberListType memberListType;
            RuntimeType.FilterHelper(bindingAttr, ref name, allowPrefixLookup, out flag, out flag2, out memberListType);
            RuntimePropertyInfo[] propertiesByName = this.GetPropertiesByName(name, bindingAttr, memberListType, this);
            bindingAttr ^= BindingFlags.DeclaredOnly;
            RuntimeType.ListBuilder<PropertyInfo> listBuilder = new RuntimeType.ListBuilder<PropertyInfo>(propertiesByName.Length);
            foreach (RuntimePropertyInfo runtimePropertyInfo in propertiesByName)
            {
                if ((bindingAttr & runtimePropertyInfo.BindingFlags) == runtimePropertyInfo.BindingFlags && (!flag || RuntimeType.FilterApplyPrefixLookup(runtimePropertyInfo, name, flag2)) && (types == null || runtimePropertyInfo.GetIndexParameters().Length == types.Length))
                {
                    listBuilder.Add(runtimePropertyInfo);
                }
            }
            return listBuilder;
        }
References System.Reflection.RuntimePropertyInfo.BindingFlags, System.RuntimeType.FilterApplyPrefixLookup(), System.RuntimeType.FilterHelper(), System.Reflection.RuntimePropertyInfo.GetIndexParameters(), System.RuntimeType.GetPropertiesByName(), and System.name.
Referenced by System.RuntimeType.GetMember(), System.RuntimeType.GetMembers(), System.RuntimeType.GetProperties(), and System.RuntimeType.GetPropertyImpl().