Terraria Decompiled: System.RuntimeType.InvokeMember
InvokeMember()
override object System.RuntimeType.InvokeMember (string name, BindingFlags bindingFlags, Binder binder, object target, object[] providedArgs, ParameterModifier[] modifiers, CultureInfo culture, string[] namedParams) inline
Definition at line 1468 of file RuntimeType.cs.
        {
            if (this.IsGenericParameter)
            {
                throw new InvalidOperationException(Environment.GetResourceString("Method must be called on a Type for which Type.IsGenericParameter is false."));
            }
            if ((bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.CreateInstance | BindingFlags.GetField | BindingFlags.SetField | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty)) == BindingFlags.Default)
            {
                throw new ArgumentException(Environment.GetResourceString("Must specify binding flags describing the invoke operation required (BindingFlags.InvokeMethod CreateInstance GetField SetField GetProperty SetProperty)."), "bindingFlags");
            }
            if ((bindingFlags & (BindingFlags)255) == BindingFlags.Default)
            {
                bindingFlags |= BindingFlags.Instance | BindingFlags.Public;
                if ((bindingFlags & BindingFlags.CreateInstance) == BindingFlags.Default)
                {
                    bindingFlags |= BindingFlags.Static;
                }
            }
            if (namedParams != null)
            {
                if (providedArgs != null)
                {
                    if (namedParams.Length > providedArgs.Length)
                    {
                        throw new ArgumentException(Environment.GetResourceString("Named parameter array cannot be bigger than argument array."), "namedParams");
                    }
                }
                else if (namedParams.Length != 0)
                {
                    throw new ArgumentException(Environment.GetResourceString("Named parameter array cannot be bigger than argument array."), "namedParams");
                }
            }
            if (target != null && target.GetType().IsCOMObject)
            {
                if ((bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty)) == BindingFlags.Default)
                {
                    throw new ArgumentException(Environment.GetResourceString("Must specify property Set or Get or method call for a COM Object."), "bindingFlags");
                }
                if ((bindingFlags & BindingFlags.GetProperty) != BindingFlags.Default && (bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty) & ~(BindingFlags.InvokeMethod | BindingFlags.GetProperty)) != BindingFlags.Default)
                {
                    throw new ArgumentException(Environment.GetResourceString("Cannot specify both Get and Set on a property."), "bindingFlags");
                }
                if ((bindingFlags & BindingFlags.InvokeMethod) != BindingFlags.Default && (bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty) & ~(BindingFlags.InvokeMethod | BindingFlags.GetProperty)) != BindingFlags.Default)
                {
                    throw new ArgumentException(Environment.GetResourceString("Cannot specify Set on a property and Invoke on a method."), "bindingFlags");
                }
                if ((bindingFlags & BindingFlags.SetProperty) != BindingFlags.Default && (bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty) & ~BindingFlags.SetProperty) != BindingFlags.Default)
                {
                    throw new ArgumentException(Environment.GetResourceString("Only one of the following binding flags can be set: BindingFlags.SetProperty, BindingFlags.PutDispProperty,  BindingFlags.PutRefDispProperty."), "bindingFlags");
                }
                if ((bindingFlags & BindingFlags.PutDispProperty) != BindingFlags.Default && (bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty) & ~BindingFlags.PutDispProperty) != BindingFlags.Default)
                {
                    throw new ArgumentException(Environment.GetResourceString("Only one of the following binding flags can be set: BindingFlags.SetProperty, BindingFlags.PutDispProperty,  BindingFlags.PutRefDispProperty."), "bindingFlags");
                }
                if ((bindingFlags & BindingFlags.PutRefDispProperty) != BindingFlags.Default && (bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetProperty | BindingFlags.SetProperty | BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty) & ~BindingFlags.PutRefDispProperty) != BindingFlags.Default)
                {
                    throw new ArgumentException(Environment.GetResourceString("Only one of the following binding flags can be set: BindingFlags.SetProperty, BindingFlags.PutDispProperty,  BindingFlags.PutRefDispProperty."), "bindingFlags");
                }
                if (RemotingServices.IsTransparentProxy(target))
                {
                    throw new NotImplementedException();
                }
                if (name == null)
                {
                    throw new ArgumentNullException("name");
                }
                throw new NotImplementedException();
            }
            else
            {
                if (namedParams != null && Array.IndexOf<string>(namedParams, null) != -1)
                {
                    throw new ArgumentException(Environment.GetResourceString("Named parameter value must not be null."), "namedParams");
                }
                int num = ((providedArgs != null) ? providedArgs.Length : 0);
                if (binder == null)
                {
                    binder = Type.DefaultBinder;
                }
                if ((bindingFlags & BindingFlags.CreateInstance) != BindingFlags.Default)
                {
                    if ((bindingFlags & BindingFlags.CreateInstance) != BindingFlags.Default && (bindingFlags & (BindingFlags.InvokeMethod | BindingFlags.GetField | BindingFlags.SetField | BindingFlags.GetProperty | BindingFlags.SetProperty)) != BindingFlags.Default)
                    {
                        throw new ArgumentException(Environment.GetResourceString("Cannot specify both CreateInstance and another access type."), "bindingFlags");
                    }
                    return Activator.CreateInstance(this, bindingFlags, binder, providedArgs, culture);
                }
                else
                {
                    if ((bindingFlags & (BindingFlags.PutDispProperty | BindingFlags.PutRefDispProperty)) != BindingFlags.Default)
                    {
                        bindingFlags |= BindingFlags.SetProperty;
                    }
                    if (name == null)
                    {
                        throw new ArgumentNullException("name");
                    }
                    if (name.Length == 0 || name.Equals("[DISPID=0]"))
                    {
                        name = this.GetDefaultMemberName();
                        if (name == null)
{
                            name = "ToString";
                        }
                    }
                    bool flag = (bindingFlags & BindingFlags.GetField) > BindingFlags.Default;
                    bool flag2 = (bindingFlags & BindingFlags.SetField) > BindingFlags.Default;
                    if (flag || flag2)
                    {
                        if (flag)
{
                            if (flag2)
{
                                throw new ArgumentException(Environment.GetResourceString("Cannot specify both Get and Set on a field."), "bindingFlags");
                            }
                            if ((bindingFlags & BindingFlags.SetProperty) != BindingFlags.Default)
{
                                throw new ArgumentException(Environment.GetResourceString("Cannot specify both GetField and SetProperty."), "bindingFlags");
                            }
                        }
                        else
{
                            if (providedArgs == null)
{
                                throw new ArgumentNullException("providedArgs");
                            }
                            if ((bindingFlags & BindingFlags.GetProperty) != BindingFlags.Default)
{
                                throw new ArgumentException(Environment.GetResourceString("Cannot specify both SetField and GetProperty."), "bindingFlags");
                            }
                            if ((bindingFlags & BindingFlags.InvokeMethod) != BindingFlags.Default)
{
                                throw new ArgumentException(Environment.GetResourceString("Cannot specify Set on a Field and Invoke on a method."), "bindingFlags");
                            }
                        }
                        FieldInfo fieldInfo = null;
                        FieldInfo[] array = this.GetMember(name, MemberTypes.Field, bindingFlags) as FieldInfo[];
                        if (array.Length == 1)
{
                            fieldInfo = array[0];
                        }
                        else if (array.Length != 0)
{
                            fieldInfo = binder.BindToField(bindingFlags, array, flag ? Empty.Value : providedArgs[0], culture);
                        }
                        if (fieldInfo != null)
{
                            if (fieldInfo.FieldType.IsArray || fieldInfo.FieldType == typeof(Array))
{
                                int num2;
                                if ((bindingFlags & BindingFlags.GetField) != BindingFlags.Default)
{
                                    num2 = num;
                                }
                                else
{
                                    num2 = num - 1;
                                }
                                if (num2 > 0)
{
                                    int[] array2 = new int[num2];
                                    for (int i = 0; i < num2; i++)
{
                                        try
{
                                            array2[i] = ((IConvertible)providedArgs[i]).ToInt32(null);
                                        }
                                        catch (InvalidCastException)
{
                                            throw new ArgumentException(Environment.GetResourceString("All indexes must be of type Int32."));
                                        }
                                    }
                                    Array array3 = (Array)fieldInfo.GetValue(target);
                                    if ((bindingFlags & BindingFlags.GetField) != BindingFlags.Default)
{
                                        return array3.GetValue(array2);
                                    }
                                    array3.SetValue(providedArgs[num2], array2);
                                    return null;
                                }
                            }
                            if (flag)
{
                                if (num != 0)
{
                                    throw new ArgumentException(Environment.GetResourceString("No arguments can be provided to Get a field value."), "bindingFlags");
                                }
                                return fieldInfo.GetValue(target);
                            }
                            else
{
                                if (num != 1)
{
                                    throw new ArgumentException(Environment.GetResourceString("Only the field value can be specified to set a field value."), "bindingFlags");
                                }
                                fieldInfo.SetValue(target, providedArgs[0], bindingFlags, binder, culture);
                                return null;
                            }
                        }
                        else if ((bindingFlags & (BindingFlags)16773888) == BindingFlags.Default)
{
                            throw new MissingFieldException(this.FullName, name);
                        }
                    }
                    bool flag3 = (bindingFlags & BindingFlags.GetProperty) > BindingFlags.Default;
                    bool flag4 = (bindingFlags & BindingFlags.SetProperty) > BindingFlags.Default;
                    if (flag3 || flag4)
                    {
                        if (flag3)
{
                            if (flag4)
{
                                throw new ArgumentException(Environment.GetResourceString("Cannot specify both Get and Set on a property."), "bindingFlags");
                            }
                        }
                        else if ((bindingFlags & BindingFlags.InvokeMethod) != BindingFlags.Default)
{
                            throw new ArgumentException(Environment.GetResourceString("Cannot specify Set on a property and Invoke on a method."), "bindingFlags");
                        }
                    }
                    MethodInfo[] array4 = null;
                    MethodInfo methodInfo = null;
                    if ((bindingFlags & BindingFlags.InvokeMethod) != BindingFlags.Default)
                    {
                        MethodInfo[] array5 = this.GetMember(name, MemberTypes.Method, bindingFlags) as MethodInfo[];
                        List<MethodInfo> list = null;
                        foreach (MethodInfo methodInfo2 in array5)
{
                            if (RuntimeType.FilterApplyMethodInfo((RuntimeMethodInfo)methodInfo2, bindingFlags, CallingConventions.Any, new Type[num]))
{
                                if (methodInfo == null)
{
                                    methodInfo = methodInfo2;
                                }
                                else
{
                                    if (list == null)
{
                                        list = new List<MethodInfo>(array5.Length);
                                        list.Add(methodInfo);
                                    }
                                    list.Add(methodInfo2);
                                }
                            }
                        }
                        if (list != null)
{
                            array4 = new MethodInfo[list.Count];
                            list.CopyTo(array4);
                        }
                    }
                    if ((methodInfo == null && flag3) || flag4)
                    {
                        PropertyInfo[] array6 = this.GetMember(name, MemberTypes.Property, bindingFlags) as PropertyInfo[];
                        List<MethodInfo> list2 = null;
                        for (int k = 0; k < array6.Length; k++)
{
                            MethodInfo methodInfo3;
                            if (flag4)
{
                                methodInfo3 = array6[k].GetSetMethod(true);
                            }
                            else
{
                                methodInfo3 = array6[k].GetGetMethod(true);
                            }
                            if (!(methodInfo3 == null) && RuntimeType.FilterApplyMethodInfo((RuntimeMethodInfo)methodInfo3, bindingFlags, CallingConventions.Any, new Type[num]))
{
                                if (methodInfo == null)
{
                                    methodInfo = methodInfo3;
                                }
                                else
{
                                    if (list2 == null)
{
                                        list2 = new List<MethodInfo>(array6.Length);
                                        list2.Add(methodInfo);
                                    }
                                    list2.Add(methodInfo3);
                                }
                            }
                        }
                        if (list2 != null)
{
                            array4 = new MethodInfo[list2.Count];
                            list2.CopyTo(array4);
                        }
                    }
                    if (!(methodInfo != null))
                    {
                        throw new MissingMethodException(this.FullName, name);
                    }
                    if (array4 == null && num == 0 && methodInfo.GetParametersNoCopy().Length == 0 && (bindingFlags & BindingFlags.OptionalParamBinding) == BindingFlags.Default)
                    {
                        return methodInfo.Invoke(target, bindingFlags, binder, providedArgs, culture);
                    }
                    if (array4 == null)
                    {
                        array4 = new MethodInfo[] { methodInfo };
                    }
                    if (providedArgs == null)
                    {
                        providedArgs = Array.Empty<object>();
                    }
                    object obj = null;
                    MethodBase methodBase = null;
                    try
                    {
                        Binder binder2 = binder;
                        BindingFlags bindingFlags2 = bindingFlags;
                        MethodBase[] array7 = array4;
                        methodBase = binder2.BindToMethod(bindingFlags2, array7, ref providedArgs, modifiers, culture, namedParams, out obj);
                    }
                    catch (MissingMethodException)
                    {
                    }
                    if (methodBase == null)
                    {
                        throw new MissingMethodException(this.FullName, name);
                    }
                    object obj2 = ((MethodInfo)methodBase).Invoke(target, bindingFlags, binder, providedArgs, culture);
                    if (obj != null)
                    {
                        binder.ReorderArgumentArray(ref providedArgs, obj);
                    }
                    return obj2;
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), System.array, System.Reflection.Array, System.Reflection.Binder.BindToField(), System.Reflection.Binder.BindToMethod(), System.Collections.Generic.List< T >.CopyTo(), System.Collections.Generic.List< T >.Count, System.Activator.CreateInstance(), System.culture, System.Type.DefaultBinder, System.Reflection.FieldInfo.FieldType, System.RuntimeType.FilterApplyMethodInfo(), System.RuntimeType.FullName, System.RuntimeType.GetDefaultMemberName(), System.Reflection.PropertyInfo.GetGetMethod(), System.RuntimeType.GetMember(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Environment.GetResourceString(), System.Reflection.PropertyInfo.GetSetMethod(), System.Array.GetValue(), System.Reflection.FieldInfo.GetValue(), System.Array.IndexOf(), System.Reflection.MethodInfo.Invoke(), System.Type.IsArray, System.RuntimeType.IsGenericParameter, System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.list, System.name, System.obj, System.Reflection.Binder.ReorderArgumentArray(), System.Reflection.FieldInfo.SetValue(), System.Array.SetValue(), and System.Empty.Value.