Terraria Decompiled: System.RuntimeType.CreateInstanceImpl
CreateInstanceImpl()
object System.RuntimeType.CreateInstanceImpl (BindingFlags bindingAttr, Binder binder, object[] args, CultureInfo culture, object[] activationAttributes, ref StackCrawlMark stackMark) inline package
Definition at line 1958 of file RuntimeType.cs.
        {
            this.CreateInstanceCheckThis();
            object obj = null;
            try
            {
                try
                {
                    if (activationAttributes != null)
                    {
                        ActivationServices.PushActivationAttributes(this, activationAttributes);
                    }
                    if (args == null)
                    {
                        args = Array.Empty<object>();
                    }
                    int num = args.Length;
                    if (binder == null)
                    {
                        binder = Type.DefaultBinder;
                    }
                    bool flag = (bindingAttr & BindingFlags.NonPublic) == BindingFlags.Default;
                    bool flag2 = (bindingAttr & BindingFlags.DoNotWrapExceptions) == BindingFlags.Default;
                    if (num == 0 && (bindingAttr & BindingFlags.Public) != BindingFlags.Default && (bindingAttr & BindingFlags.Instance) != BindingFlags.Default && (this.IsGenericCOMObjectImpl() || base.IsValueType))
                    {
                        obj = this.CreateInstanceDefaultCtor(flag, false, true, flag2, ref stackMark);
                    }
                    else
                    {
                        ConstructorInfo[] constructors = this.GetConstructors(bindingAttr);
                        List<MethodBase> list = new List<MethodBase>(constructors.Length);
                        Type[] array = new Type[num];
                        for (int i = 0; i < num; i++)
{
                            if (args[i] != null)
{
                                array[i] = args[i].GetType();
                            }
                        }
                        for (int j = 0; j < constructors.Length; j++)
{
                            if (RuntimeType.FilterApplyConstructorInfo((RuntimeConstructorInfo)constructors[j], bindingAttr, CallingConventions.Any, array))
{
                                list.Add(constructors[j]);
                            }
                        }
                        MethodBase[] array2 = new MethodBase[list.Count];
                        list.CopyTo(array2);
                        if (array2 != null && array2.Length == 0)
{
                            array2 = null;
                        }
                        if (array2 == null)
{
                            if (activationAttributes != null)
{
                                ActivationServices.PopActivationAttributes(this);
                                activationAttributes = null;
                            }
                            throw new MissingMethodException(Environment.GetResourceString("Constructor on type '{0}' not found.", new object[] { this.FullName }));
                        }
                        object obj2 = null;
                        MethodBase methodBase;
                        try
{
                            methodBase = binder.BindToMethod(bindingAttr, array2, ref args, null, culture, null, out obj2);
                        }
                        catch (MissingMethodException)
{
                            methodBase = null;
                        }
                        if (methodBase == null)
{
                            if (activationAttributes != null)
{
                                ActivationServices.PopActivationAttributes(this);
                                activationAttributes = null;
                            }
                            throw new MissingMethodException(Environment.GetResourceString("Constructor on type '{0}' not found.", new object[] { this.FullName }));
                        }
                        if (methodBase.GetParametersNoCopy().Length == 0)
{
                            if (args.Length != 0)
{
                                throw new NotSupportedException(string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Vararg calling convention not supported."), Array.Empty<object>()));
                            }
                            if (activationAttributes != null && activationAttributes.Length != 0)
{
                                obj = this.ActivationCreateInstance(methodBase, bindingAttr, binder, args, culture, activationAttributes);
                            }
                            else
{
                                obj = Activator.CreateInstance(this, true, flag2);
                            }
                        }
                        else
{
                            if (activationAttributes != null && activationAttributes.Length != 0)
{
                                obj = this.ActivationCreateInstance(methodBase, bindingAttr, binder, args, culture, activationAttributes);
                            }
                            else
{
                                obj = ((ConstructorInfo)methodBase).Invoke(bindingAttr, binder, args, culture);
                            }
                            if (obj2 != null)
{
                                binder.ReorderArgumentArray(ref args, obj2);
                            }
                        }
                    }
                }
                finally
                {
                    if (activationAttributes != null)
                    {
                        ActivationServices.PopActivationAttributes(this);
                        activationAttributes = null;
                    }
                }
            }
            catch (Exception)
            {
                throw;
            }
            return obj;
        }
References System.RuntimeType.ActivationCreateInstance(), System.array, System.Reflection.Binder.BindToMethod(), System.Activator.CreateInstance(), System.RuntimeType.CreateInstanceCheckThis(), System.RuntimeType.CreateInstanceDefaultCtor(), System.culture, System.Globalization.CultureInfo.CurrentCulture, System.Type.DefaultBinder, System.RuntimeType.FilterApplyConstructorInfo(), System.Format, System.RuntimeType.GetConstructors(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Environment.GetResourceString(), System.list, System.obj, System.Runtime.Remoting.Activation.ActivationServices.PopActivationAttributes(), System.Runtime.Remoting.Activation.ActivationServices.PushActivationAttributes(), and System.Reflection.Binder.ReorderArgumentArray().
Referenced by System.Activator.CreateInstance().