Terraria Decompiled: System.RuntimeType.GetConstructors_internal
GetConstructors_internal()
RuntimeConstructorInfo[] System.RuntimeType.GetConstructors_internal (BindingFlags bindingAttr, RuntimeType reflectedType) inline private
Definition at line 2626 of file RuntimeType.cs.
        {
            RuntimeTypeHandle runtimeTypeHandle = new RuntimeTypeHandle(reflectedType);
            RuntimeConstructorInfo[] array2;
            using (SafeGPtrArrayHandle safeGPtrArrayHandle = new SafeGPtrArrayHandle(this.GetConstructors_native(bindingAttr)))
            {
                int length = safeGPtrArrayHandle.Length;
                RuntimeConstructorInfo[] array = new RuntimeConstructorInfo[length];
                for (int i = 0; i < length; i++)
                {
                    RuntimeMethodHandle runtimeMethodHandle = new RuntimeMethodHandle(safeGPtrArrayHandle[i]);
                    array[i] = (RuntimeConstructorInfo)RuntimeMethodInfo.GetMethodFromHandleNoGenericCheck(runtimeMethodHandle, runtimeTypeHandle);
                }
                array2 = array;
            }
            return array2;
        }
References System.array, System.RuntimeType.GetConstructors_native(), System.Reflection.RuntimeMethodInfo.GetMethodFromHandleNoGenericCheck(), Mono.SafeGPtrArrayHandle.Length, and System.length.
Referenced by System.RuntimeType.GetConstructorCandidates().