Terraria Decompiled: System.RuntimeType.IsAssignableFrom
IsAssignableFrom() [2/2]
override bool System.RuntimeType.IsAssignableFrom (Type c) inline
Definition at line 939 of file RuntimeType.cs.
        {
            if (c == null)
            {
                return false;
            }
            if (c == this)
            {
                return true;
            }
            RuntimeType runtimeType = c.UnderlyingSystemType as RuntimeType;
            if (runtimeType != null)
            {
                return RuntimeTypeHandle.CanCastTo(runtimeType, this);
            }
            if (RuntimeFeature.IsDynamicCodeSupported && c is TypeBuilder)
            {
                if (c.IsSubclassOf(this))
                {
                    return true;
                }
                if (base.IsInterface)
                {
                    return c.ImplementInterface(this);
                }
                if (this.IsGenericParameter)
                {
                    Type[] genericParameterConstraints = this.GetGenericParameterConstraints();
                    for (int i = 0; i < genericParameterConstraints.Length; i++)
                    {
                        if (!genericParameterConstraints[i].IsAssignableFrom(c))
{
                            return false;
                        }
                    }
                    return true;
                }
            }
            return false;
        }
References System.RuntimeTypeHandle.CanCastTo(), System.RuntimeType.GetGenericParameterConstraints(), System.Type.ImplementInterface(), System.RuntimeType.IsAssignableFrom(), System.Runtime.CompilerServices.RuntimeFeature.IsDynamicCodeSupported, System.RuntimeType.IsGenericParameter, System.Type.IsSubclassOf(), and System.RuntimeType.RuntimeType().