Terraria Decompiled: System.RuntimeType.FilterApplyType
FilterApplyType()
static bool System.RuntimeType.FilterApplyType (Type type, BindingFlags bindingFlags, string name, bool prefixLookup, string ns) inline static private
Definition at line 228 of file RuntimeType.cs.
        {
            bool flag = type.IsNestedPublic || type.IsPublic;
            bool flag2 = false;
            return RuntimeType.FilterApplyBase(type, bindingFlags, flag, type.IsNestedAssembly, flag2, name, prefixLookup) && (ns == null || !(ns != type.Namespace));
        }
References System.RuntimeType.FilterApplyBase(), System.Type.IsNestedAssembly, System.Type.IsPublic, System.name, and System.Type.Namespace.
Referenced by System.RuntimeType.GetInterface(), System.RuntimeType.GetNestedType(), and System.RuntimeType.GetNestedTypeCandidates().