Terraria Decompiled: System.RuntimeType.GetPropertyImpl
GetPropertyImpl()
override PropertyInfo System.RuntimeType.GetPropertyImpl (string name, BindingFlags bindingAttr, Binder binder, Type returnType, Type[] types, ParameterModifier[] modifiers) inline protected
Definition at line 587 of file RuntimeType.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException();
            }
            RuntimeType.ListBuilder<PropertyInfo> propertyCandidates = this.GetPropertyCandidates(name, bindingAttr, types, false);
            if (propertyCandidates.Count == 0)
            {
                return null;
            }
            if (types == null || types.Length == 0)
            {
                if (propertyCandidates.Count == 1)
                {
                    PropertyInfo propertyInfo = propertyCandidates[0];
                    if (returnType != null && !returnType.IsEquivalentTo(propertyInfo.PropertyType))
                    {
                        return null;
                    }
                    return propertyInfo;
                }
                else if (returnType == null)
                {
                    throw new AmbiguousMatchException(Environment.GetResourceString("Ambiguous match found."));
                }
            }
            if ((bindingAttr & BindingFlags.ExactBinding) != BindingFlags.Default)
            {
                return global::System.DefaultBinder.ExactPropertyBinding(propertyCandidates.ToArray(), returnType, types, modifiers);
            }
            if (binder == null)
            {
                binder = Type.DefaultBinder;
            }
            return binder.SelectProperty(bindingAttr, propertyCandidates.ToArray(), returnType, types, modifiers);
        }
References System.Type.DefaultBinder, System.RuntimeType.GetPropertyCandidates(), System.Environment.GetResourceString(), System.Type.IsEquivalentTo(), System.name, System.Reflection.PropertyInfo.PropertyType, and System.Reflection.Binder.SelectProperty().