Terraria Decompiled: System.RuntimeType.GetEvents_internal
GetEvents_internal()
RuntimeEventInfo[] System.RuntimeType.GetEvents_internal (string name, BindingFlags bindingAttr, RuntimeType::MemberListType listType, RuntimeType reflectedType) inline private
Definition at line 2853 of file RuntimeType.cs.
        {
            RuntimeTypeHandle runtimeTypeHandle = new RuntimeTypeHandle(reflectedType);
            RuntimeEventInfo[] array2;
            using (SafeStringMarshal safeStringMarshal = new SafeStringMarshal(name))
            {
                using (SafeGPtrArrayHandle safeGPtrArrayHandle = new SafeGPtrArrayHandle(this.GetEvents_native(safeStringMarshal.Value, listType)))
                {
                    int length = safeGPtrArrayHandle.Length;
                    RuntimeEventInfo[] array = new RuntimeEventInfo[length];
                    for (int i = 0; i < length; i++)
                    {
                        RuntimeEventHandle runtimeEventHandle = new RuntimeEventHandle(safeGPtrArrayHandle[i]);
                        array[i] = (RuntimeEventInfo)EventInfo.GetEventFromHandle(runtimeEventHandle, runtimeTypeHandle);
                    }
                    array2 = array;
                }
            }
            return array2;
        }
References System.array, System.Reflection.EventInfo.GetEventFromHandle(), System.RuntimeType.GetEvents_native(), Mono.SafeGPtrArrayHandle.Length, System.length, System.name, and Mono.SafeStringMarshal.Value.
Referenced by System.RuntimeType.GetEvent(), and System.RuntimeType.GetEventCandidates().