Terraria Decompiled: System.RuntimeType.GetEnumName
GetEnumName()
override string System.RuntimeType.GetEnumName (object value) inline
Definition at line 1285 of file RuntimeType.cs.
        {
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            Type type = value.GetType();
            if (!type.IsEnum && !Type.IsIntegerType(type))
            {
                throw new ArgumentException(Environment.GetResourceString("The value passed in must be an enum base or an underlying type for an enum, such as an Int32."), "value");
            }
            ulong[] array = Enum.InternalGetValues(this);
            ulong num = Enum.ToUInt64(value);
            int num2 = Array.BinarySearch<ulong>(array, num);
            if (num2 >= 0)
            {
                return Enum.InternalGetNames(this)[num2];
            }
            return null;
        }
References System.array, System.Array.BinarySearch(), System.Environment.GetResourceString(), System.Type.GetType(), System.Enum.InternalGetNames(), System.Enum.InternalGetValues(), System.Type.IsEnum, System.Type.IsIntegerType(), System.Enum.ToUInt64(), and System.value.