Terraria Decompiled: System.RuntimeType.GetNestedTypes_internal
GetNestedTypes_internal()
RuntimeType[] System.RuntimeType.GetNestedTypes_internal (string displayName, BindingFlags bindingAttr, RuntimeType::MemberListType listType) inline private
Definition at line 2883 of file RuntimeType.cs.
        {
            string text = null;
            if (displayName != null)
            {
                text = TypeIdentifiers.FromDisplay(displayName).InternalName;
            }
            RuntimeType[] array2;
            using (SafeStringMarshal safeStringMarshal = new SafeStringMarshal(text))
            {
                using (SafeGPtrArrayHandle safeGPtrArrayHandle = new SafeGPtrArrayHandle(this.GetNestedTypes_native(safeStringMarshal.Value, bindingAttr, listType)))
                {
                    int length = safeGPtrArrayHandle.Length;
                    RuntimeType[] array = new RuntimeType[length];
                    for (int i = 0; i < length; i++)
                    {
                        RuntimeTypeHandle runtimeTypeHandle = new RuntimeTypeHandle(safeGPtrArrayHandle[i]);
                        array[i] = (RuntimeType)Type.GetTypeFromHandle(runtimeTypeHandle);
                    }
                    array2 = array;
                }
            }
            return array2;
        }
References System.array, System.TypeIdentifiers.FromDisplay(), System.RuntimeType.GetNestedTypes_native(), System.Type.GetTypeFromHandle(), System.TypeIdentifier.InternalName, Mono.SafeGPtrArrayHandle.Length, System.length, System.RuntimeType.RuntimeType(), System.text, and Mono.SafeStringMarshal.Value.
Referenced by System.RuntimeType.GetNestedType(), and System.RuntimeType.GetNestedTypeCandidates().