Terraria Decompiled: System.RuntimeType.FilterHelper
FilterHelper() [1/2]
static void System.RuntimeType.FilterHelper (BindingFlags bindingFlags, ref string name, bool allowPrefixLookup, out bool prefixLookup, out bool ignoreCase, out RuntimeType::MemberListType listType) inline static private
Definition at line 117 of file RuntimeType.cs.
        {
            prefixLookup = false;
            ignoreCase = false;
            if (name != null)
            {
                if ((bindingFlags & BindingFlags.IgnoreCase) != BindingFlags.Default)
                {
                    name = name.ToLower(CultureInfo.InvariantCulture);
                    ignoreCase = true;
                    listType = RuntimeType.MemberListType.CaseInsensitive;
                }
                else
                {
                    listType = RuntimeType.MemberListType.CaseSensitive;
                }
                if (allowPrefixLookup && name.EndsWith("*", StringComparison.Ordinal))
                {
                    name = name.Substring(0, name.Length - 1);
                    prefixLookup = true;
                    listType = RuntimeType.MemberListType.All;
                    return;
                }
            }
            else
            {
                listType = RuntimeType.MemberListType.All;
            }
        }
References System.Globalization.CultureInfo.InvariantCulture, and System.name.
Referenced by System.RuntimeType.FilterHelper(), System.RuntimeType.GetConstructorCandidates(), System.RuntimeType.GetEvent(), System.RuntimeType.GetEventCandidates(), System.RuntimeType.GetField(), System.RuntimeType.GetFieldCandidates(), System.RuntimeType.GetInterface(), System.RuntimeType.GetMethodCandidates(), System.RuntimeType.GetMethodCandidates(), System.RuntimeType.GetNestedType(), System.RuntimeType.GetNestedTypeCandidates(), and System.RuntimeType.GetPropertyCandidates().