Terraria Decompiled: System.RuntimeType.FormatTypeName
FormatTypeName()
override string System.RuntimeType.FormatTypeName (bool serialization) inline package
Definition at line 1880 of file RuntimeType.cs.
        {
            if (serialization)
            {
                return this.GetCachedName(TypeNameKind.SerializationName);
            }
            Type rootElementType = base.GetRootElementType();
            if (rootElementType.IsNested)
            {
                return this.Name;
            }
            string text = this.ToString();
            if (rootElementType.IsPrimitive || rootElementType == typeof(void) || rootElementType == typeof(TypedReference))
            {
                text = text.Substring("System.".Length);
            }
            return text;
        }
References System.RuntimeType.GetCachedName(), System.Type.GetRootElementType(), System.Type.IsNested, System.Type.IsPrimitive, System.RuntimeType.Name, System.text, and System.RuntimeType.ToString().