Terraria Decompiled: System.RuntimeType.GetEventCandidates
GetEventCandidates()
RuntimeType.ListBuilder< EventInfo > System.RuntimeType.GetEventCandidates (string name, BindingFlags bindingAttr, bool allowPrefixLookup) inline private
Definition at line 423 of file RuntimeType.cs.
        {
            bool flag;
            bool flag2;
            RuntimeType.MemberListType memberListType;
            RuntimeType.FilterHelper(bindingAttr, ref name, allowPrefixLookup, out flag, out flag2, out memberListType);
            RuntimeEventInfo[] events_internal = this.GetEvents_internal(name, bindingAttr, memberListType, this);
            bindingAttr ^= BindingFlags.DeclaredOnly;
            RuntimeType.ListBuilder<EventInfo> listBuilder = new RuntimeType.ListBuilder<EventInfo>(events_internal.Length);
            foreach (RuntimeEventInfo runtimeEventInfo in events_internal)
            {
                if ((bindingAttr & runtimeEventInfo.BindingFlags) == runtimeEventInfo.BindingFlags && (!flag || RuntimeType.FilterApplyPrefixLookup(runtimeEventInfo, name, flag2)))
                {
                    listBuilder.Add(runtimeEventInfo);
                }
            }
            return listBuilder;
        }
References System.Reflection.RuntimeEventInfo.BindingFlags, System.RuntimeType.FilterApplyPrefixLookup(), System.RuntimeType.FilterHelper(), System.RuntimeType.GetEvents_internal(), and System.name.
Referenced by System.RuntimeType.GetEvents(), System.RuntimeType.GetMember(), and System.RuntimeType.GetMembers().