Terraria Decompiled: System.RuntimeType.GetTypeFromCLSIDImpl
GetTypeFromCLSIDImpl()
static Type System.RuntimeType.GetTypeFromCLSIDImpl (Guid clsid, string server, bool throwOnError) inline static package
Definition at line 2725 of file RuntimeType.cs.
        {
            if (RuntimeType.clsid_types == null)
            {
                Dictionary<Guid, Type> dictionary = new Dictionary<Guid, Type>();
                Interlocked.CompareExchange<Dictionary<Guid, Type>>(ref RuntimeType.clsid_types, dictionary, null);
            }
            Dictionary<Guid, Type> dictionary2 = RuntimeType.clsid_types;
            Type type2;
            lock (dictionary2)
            {
                Type type;
                if (RuntimeType.clsid_types.TryGetValue(clsid, out type))
                {
                    type2 = type;
                }
                else
                {
                    if (RuntimeType.clsid_assemblybuilder == null)
                    {
                        RuntimeType.clsid_assemblybuilder = new AssemblyBuilder(new AssemblyName
{
                            Name = "GetTypeFromCLSIDDummyAssembly"
                        }, null, AssemblyBuilderAccess.Run, true);
                    }
                    TypeBuilder typeBuilder = RuntimeType.clsid_assemblybuilder.DefineDynamicModule(clsid.ToString()).DefineType("System.__ComObject", TypeAttributes.Public, typeof(__ComObject));
                    Type[] array = new Type[] { typeof(string) };
                    CustomAttributeBuilder customAttributeBuilder = new CustomAttributeBuilder(typeof(GuidAttribute).GetConstructor(array), new object[] { clsid.ToString() });
                    typeBuilder.SetCustomAttribute(customAttributeBuilder);
                    customAttributeBuilder = new CustomAttributeBuilder(typeof(ComImportAttribute).GetConstructor(Type.EmptyTypes), new object[0]);
                    typeBuilder.SetCustomAttribute(customAttributeBuilder);
                    type = typeBuilder.CreateType();
                    RuntimeType.clsid_types.Add(clsid, type);
                    type2 = type;
                }
            }
            return type2;
        }
References System.array, System.RuntimeType.clsid_assemblybuilder, System.RuntimeType.clsid_types, System.Threading.Interlocked.CompareExchange(), System.Reflection.Emit.TypeBuilder.CreateType(), System.Reflection.Emit.AssemblyBuilder.DefineDynamicModule(), System.Reflection.Emit.ModuleBuilder.DefineType(), System.dictionary, System.Type.EmptyTypes, System.RuntimeType.GetConstructor(), System.RuntimeType.Name, System.Reflection.Emit.TypeBuilder.SetCustomAttribute(), and System.Guid.ToString().
Referenced by System.Type.GetTypeFromCLSID().