Terraria Decompiled: Terraria.DataStructures.NPCFollowState.Update
Update()
void Terraria.DataStructures.NPCFollowState.Update () inline
Definition at line 102 of file NPCFollowState.cs.
        {
            if (!this.IsFollowingPlayer)
            {
                return;
            }
            Player playerBeingFollowed = this.PlayerBeingFollowed;
            if (!playerBeingFollowed.active || playerBeingFollowed.dead)
            {
                this.StopFollowing();
                return;
            }
            this.UpdateBreadcrumbs(playerBeingFollowed);
            Dust.QuickDust(this._floorBreadcrumb, Color.Red);
        }
References Terraria.DataStructures.NPCFollowState._floorBreadcrumb, Terraria.Player.active, Terraria.Player.dead, Terraria.DataStructures.NPCFollowState.IsFollowingPlayer, Terraria.DataStructures.NPCFollowState.PlayerBeingFollowed, Terraria.Dust.QuickDust(), Microsoft.Xna.Framework.Color.Red, Terraria.DataStructures.NPCFollowState.StopFollowing(), and Terraria.DataStructures.NPCFollowState.UpdateBreadcrumbs().