Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated
MakeDungeon_GenerateNextEntranceHall_Precalculated()
static void Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated (DungeonData data, UnifiedRandom genRand, double dist, Vector2D entrancePos, ref int amountPassed, ref Vector2D currentPos) inline static
Definition at line 529 of file DungeonCrawler.cs.
        {
            int num = genRand.Next(10, 30);
            if ((double)num > dist - (double)amountPassed)
            {
                num = Math.Max(1, (int)dist - amountPassed);
            }
            Vector2D vector2D = Vector2D.Lerp(currentPos, entrancePos, (double)amountPassed / dist);
            DungeonHall dungeonHall = DungeonCrawler.MakeDungeon_GetHall(new LegacyEntranceDungeonHallSettings
            {
                HallType = DungeonHallType.LegacyEntrance,
                StyleData = data.genVars.dungeonStyle,
                RandomSeed = WorldGen.genRand.Next(),
                OverrideSteps = num,
                UsePrecalculatedEntrance = true
            }, true);
            dungeonHall.CalculateHall(data, currentPos, vector2D);
            dungeonHall.GenerateHall(data);
            amountPassed -= num;
            currentPos = vector2D;
            if (amountPassed <= 0)
            {
                data.createdDungeonEntranceOnSurface = true;
            }
        }
References Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CalculateHall(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateHall(), Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, ReLogic.Utilities.Vector2D.Lerp(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall(), System.Math.Max(), and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon().