Terraria Decompiled: Microsoft.Xna.Framework.Content.ReflectiveReader.Read
Read()
override object Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Read (ContentReader input, object existingInstance) inline package
Definition at line 63 of file ReflectiveReader.cs.
        {
            T t;
            if (existingInstance != null)
            {
                t = (T)((object)existingInstance);
            }
            else if (this.constructor == null)
            {
                t = (T)((object)Activator.CreateInstance(typeof(T)));
            }
            else
            {
                t = (T)((object)this.constructor.Invoke(null));
            }
            if (this.baseTypeReader != null)
            {
                this.baseTypeReader.Read(input, t);
            }
            object obj = t;
            foreach (ReflectiveReader<T>.ReadElement readElement in this.readers)
            {
                readElement(input, obj);
            }
            t = (T)((object)obj);
            return t;
        }
References Microsoft.Xna.Framework.Content.ReflectiveReader< T >.baseTypeReader, Microsoft.Xna.Framework.Content.ReflectiveReader< T >.constructor, System.Activator.CreateInstance(), System.input, System.Reflection.ConstructorInfo.Invoke(), System.obj, Microsoft.Xna.Framework.Content.ContentTypeReader< T >.Read(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.ReadElement(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.readers, and System.T.