Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall
MakeDungeon_GetHall()
static DungeonHall Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall (DungeonHallSettings settings, bool addToData = true) inline static
Definition at line 926 of file DungeonCrawler.cs.
        {
            DungeonHall dungeonHall;
            switch (settings.HallType)
            {
            default:
                dungeonHall = new LegacyDungeonHall(settings);
                break;
            case DungeonHallType.LegacyEntrance:
                dungeonHall = new LegacyEntranceDungeonHall(settings);
                break;
            case DungeonHallType.Regular:
                dungeonHall = new RegularDungeonHall(settings);
                break;
            case DungeonHallType.Stairwell:
                dungeonHall = new StairwellDungeonHall((StairwellDungeonHallSettings)settings);
                break;
            case DungeonHallType.Sine:
                dungeonHall = new SineDungeonHall(settings);
                break;
            }
            if (addToData && dungeonHall != null)
            {
                DungeonCrawler.CurrentDungeonData.dungeonHalls.Add(dungeonHall);
            }
            return dungeonHall;
        }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.CurrentDungeonData, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonHalls, and Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.HallType.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceHall(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Legacy(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall_Legacy(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.MakeHall().