Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonGenVarVariables
SetupDungeonGenVarVariables()
static void Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonGenVarVariables (DungeonGenVars genVars, UnifiedRandom genRand) inline static
Definition at line 58 of file DungeonCrawler.cs.
        {
            int num = genRand.Next(3);
            if (WorldGen.remixWorldGen)
            {
                if (WorldGen.crimson)
                {
                    num = 2;
                }
                else
                {
                    num = 0;
                }
            }
            switch (num)
            {
            case 0:
                genVars.dungeonColor = DungeonColor.Blue;
                genVars.brickTileType = 41;
                genVars.brickWallType = 7;
                genVars.brickCrackedTileType = 481;
                genVars.windowGlassWallType = 91;
                genVars.windowClosedGlassWallType = 96;
                genVars.windowEdgeWallType = 8;
                genVars.windowPlatformItemTypes = new int[] { 1386 };
                goto IL_0120;
            case 1:
                genVars.dungeonColor = DungeonColor.Green;
                genVars.brickTileType = 43;
                genVars.brickWallType = 8;
                genVars.brickCrackedTileType = 482;
                genVars.windowGlassWallType = 92;
                genVars.windowClosedGlassWallType = 94;
                genVars.windowEdgeWallType = 9;
                genVars.windowPlatformItemTypes = new int[] { 1385 };
                goto IL_0120;
            }
            genVars.dungeonColor = DungeonColor.Pink;
            genVars.brickTileType = 44;
            genVars.brickWallType = 9;
            genVars.brickCrackedTileType = 483;
            genVars.windowGlassWallType = 90;
            genVars.windowClosedGlassWallType = 98;
            genVars.windowEdgeWallType = 7;
            genVars.windowPlatformItemTypes = new int[] { 1384 };
            IL_0120:
            if (WorldGen.drunkWorldGen)
            {
                switch (genRand.Next(3))
                {
                case 0:
                    genVars.brickWallType = 7;
                    goto IL_015D;
                case 1:
                    genVars.brickWallType = 8;
                    goto IL_015D;
                }
                genVars.brickWallType = 9;
            }
            IL_015D:
            DungeonUtils.CreatePotentialDungeonBounds(out genVars.innerPotentialDungeonBounds, out genVars.outerPotentialDungeonBounds, genVars.dungeonSide == (int)DungeonSide.Left, 0.10000000149011612, 0.05000000074505806, -1.0, -1.0, 10);
            genVars.dungeonStyle = DungeonGenerationStyles.GetCurrentDungeonStyle();
            if (WorldGen.SecretSeed.dualDungeons.Enabled)
            {
                int num2 = GenVars.CurrentDungeon % 2;
                if (num2 == 0 || num2 != 1)
                {
                    genVars.dungeonGenerationStyles.Add(DungeonGenerationStyles.Cavern);
                    genVars.dungeonGenerationStyles.Add(WorldGen.crimson ? DungeonGenerationStyles.Crimson : DungeonGenerationStyles.Corruption);
                    genVars.dungeonGenerationStyles.Add(DungeonGenerationStyles.Jungle);
                    genVars.dungeonGenerationStyles.Add(genVars.dungeonStyle);
                }
                else
                {
                    genVars.dungeonGenerationStyles.Add(DungeonGenerationStyles.Snow);
                    genVars.dungeonGenerationStyles.Add(DungeonGenerationStyles.Desert);
                    genVars.dungeonGenerationStyles.Add(DungeonGenerationStyles.Hallow);
                    genVars.dungeonGenerationStyles.Add(DungeonGenerationStyles.Temple);
                }
            }
            else
            {
                genVars.dungeonGenerationStyles.Add(genVars.dungeonStyle);
            }
            genVars.isDungeonTile = Main.tileDungeon;
            genVars.isCrackedBrick = TileID.Sets.CrackedBricks;
            genVars.isPitTrapTile = TileID.Sets.CrackedBricks;
            genVars.isDungeonWall = Main.wallDungeon;
            genVars.isDungeonWallGlass = WallID.Sets.Glass;
            if (WorldGen.SecretSeed.dualDungeons.Enabled)
            {
                genVars.isDungeonTile = (bool[])genVars.isDungeonTile.Clone();
                genVars.isCrackedBrick = (bool[])genVars.isCrackedBrick.Clone();
                genVars.isPitTrapTile = (bool[])genVars.isPitTrapTile.Clone();
                genVars.isDungeonWall = (bool[])genVars.isDungeonWall.Clone();
                genVars.isDungeonWallGlass = (bool[])genVars.isDungeonWallGlass.Clone();
                List<DungeonGenerationStyleData> list = new List<DungeonGenerationStyleData>(genVars.dungeonGenerationStyles);
                foreach (DungeonGenerationStyleData dungeonGenerationStyleData in genVars.dungeonGenerationStyles)
                {
                    if (dungeonGenerationStyleData.SubStyles != null)
                    {
                        list.AddRange(dungeonGenerationStyleData.SubStyles);
                    }
                }
                foreach (DungeonGenerationStyleData dungeonGenerationStyleData2 in list)
                {
                    genVars.isDungeonTile[(int)dungeonGenerationStyleData2.BrickTileType] = true;
                    if (dungeonGenerationStyleData2.BrickGrassTileType != null)
                    {
                        genVars.isDungeonTile[(int)dungeonGenerationStyleData2.BrickGrassTileType.Value] = true;
                    }
                    genVars.isCrackedBrick[(int)dungeonGenerationStyleData2.BrickCrackedTileType] = true;
                    genVars.isPitTrapTile[(int)dungeonGenerationStyleData2.PitTrapTileType] = true;
                    genVars.isDungeonWall[(int)dungeonGenerationStyleData2.BrickWallType] = true;
                    genVars.isDungeonWallGlass[(int)dungeonGenerationStyleData2.WindowGlassWallType] = true;
                    genVars.isDungeonWallGlass[(int)dungeonGenerationStyleData2.WindowClosedGlassWallType] = true;
                }
            }
            DungeonEntranceType dungeonEntranceType = DungeonEntranceType.Legacy;
            bool flag = false;
            int num3 = 50;
            while (!flag)
            {
                num3--;
                if (num3 <= 0)
                {
                    dungeonEntranceType = DungeonEntranceType.Legacy;
                    break;
                }
                dungeonEntranceType = DungeonEntranceType.Legacy;
                if (genRand.Next(3) == 0)
                {
                    dungeonEntranceType = DungeonEntranceType.Dome;
                }
                if (genRand.Next(3) == 0)
                {
                    dungeonEntranceType = DungeonEntranceType.Tower;
                }
                flag = true;
                if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled && dungeonEntranceType == DungeonEntranceType.Tower)
                {
                    flag = false;
                }
            }
            genVars.preGenDungeonEntranceSettings = (PreGenDungeonEntranceSettings)DungeonCrawler.MakeDungeon_GetEntranceSettings(dungeonEntranceType, genVars.dungeonStyle, null);
        }
References Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickGrassTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Cavern, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Corruption, Terraria.ID.TileID.Sets.CrackedBricks, Terraria.GameContent.Generation.Dungeon.DungeonUtils.CreatePotentialDungeonBounds(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Crimson, Terraria.WorldGen.crimson, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Desert, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonSide, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetCurrentDungeonStyle(), Terraria.ID.WallID.Sets.Glass, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Hallow, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.innerPotentialDungeonBounds, int, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.isCrackedBrick, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.isDungeonTile, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.isDungeonWall, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.isDungeonWallGlass, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.isPitTrapTile, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Jungle, Terraria.WorldBuilding.DungeonSide.Left, System.list, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.outerPotentialDungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.PitTrapTileType, Terraria.WorldGen.remixWorldGen, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Snow, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.SubStyles, Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Temple, Terraria.Main.tileDungeon, Terraria.Main.wallDungeon, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WindowClosedGlassWallType, and Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.WindowGlassWallType.
Referenced by Terraria.WorldGen.AddPasses().