Terraria Decompiled: Microsoft.Xna.Framework.Content.ReflectiveReader.Initialize
Initialize()
override void Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Initialize (ContentTypeReaderManager manager) inline package virtual
Reimplemented from Microsoft.Xna.Framework.Content.ContentTypeReader< T >.
Definition at line 28 of file ReflectiveReader.cs.
        {
            base.Initialize(manager);
            Type baseType = base.TargetType.BaseType;
            if (baseType != null && baseType != typeof(object))
            {
                this.baseTypeReader = manager.GetTypeReader(baseType);
            }
            this.constructor = base.TargetType.GetDefaultConstructor();
            PropertyInfo[] properties = base.TargetType.GetProperties(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            FieldInfo[] fields = base.TargetType.GetFields(BindingFlags.DeclaredOnly | BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            this.readers = new List<ReflectiveReader<T>.ReadElement>(fields.Length + properties.Length);
            foreach (PropertyInfo propertyInfo in properties)
            {
                MethodInfo getMethod = propertyInfo.GetGetMethod(true);
                if (!(getMethod == null) && !(getMethod != getMethod.GetBaseDefinition()))
                {
                    ReflectiveReader<T>.ReadElement elementReader = ReflectiveReader<T>.GetElementReader(manager, propertyInfo);
                    if (elementReader != null)
                    {
                        this.readers.Add(elementReader);
                    }
                }
            }
            foreach (FieldInfo fieldInfo in fields)
            {
                ReflectiveReader<T>.ReadElement elementReader2 = ReflectiveReader<T>.GetElementReader(manager, fieldInfo);
                if (elementReader2 != null)
                {
                    this.readers.Add(elementReader2);
                }
            }
        }
References System.Type.BaseType, System.Reflection.MethodInfo.GetBaseDefinition(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.GetElementReader(), System.Reflection.PropertyInfo.GetGetMethod(), Microsoft.Xna.Framework.Content.ContentTypeReaderManager.GetTypeReader(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.ReadElement(), Microsoft.Xna.Framework.Content.ReflectiveReader< T >.readers, and Microsoft.Xna.Framework.Content.ContentTypeReader< T >.TargetType.