Terraria Decompiled: System.UnitySerializationHolder.GetRealObject
GetRealObject()
virtual object System.UnitySerializationHolder.GetRealObject (StreamingContext context) inline virtual
Implements System.Runtime.Serialization.IObjectReference.
Definition at line 169 of file UnitySerializationHolder.cs.
        {
            switch (this.m_unityType)
            {
            case 1:
                return Empty.Value;
            case 2:
                return DBNull.Value;
            case 3:
                return Missing.Value;
            case 4:
                if (this.m_data == null || this.m_data.Length == 0)
                {
                    this.ThrowInsufficientInformation("Data");
                }
                if (this.m_assemblyName == null)
                {
                    this.ThrowInsufficientInformation("AssemblyName");
                }
                if (this.m_assemblyName.Length == 0)
                {
                    return Type.GetType(this.m_data, true, false);
                }
                return Assembly.Load(this.m_assemblyName).GetType(this.m_data, true, false);
            case 5:
            {
                if (this.m_data == null || this.m_data.Length == 0)
                {
                    this.ThrowInsufficientInformation("Data");
                }
                if (this.m_assemblyName == null)
                {
                    this.ThrowInsufficientInformation("AssemblyName");
                }
                Module module = Assembly.Load(this.m_assemblyName).GetModule(this.m_data);
                if (module == null)
                {
                    throw new SerializationException(Environment.GetResourceString("The given module {0} cannot be found within the assembly {1}.", new object[] { this.m_data, this.m_assemblyName }));
                }
                return module;
            }
            case 6:
                if (this.m_data == null || this.m_data.Length == 0)
                {
                    this.ThrowInsufficientInformation("Data");
                }
                if (this.m_assemblyName == null)
                {
                    this.ThrowInsufficientInformation("AssemblyName");
                }
                return Assembly.Load(this.m_assemblyName);
            case 7:
                if (this.m_declaringMethod == null && this.m_declaringType == null)
                {
                    this.ThrowInsufficientInformation("DeclaringMember");
                }
                if (this.m_declaringMethod != null)
                {
                    return this.m_declaringMethod.GetGenericArguments()[this.m_genericParameterPosition];
                }
                return this.MakeElementTypes(this.m_declaringType.GetGenericArguments()[this.m_genericParameterPosition]);
            case 8:
            {
                this.m_unityType = 4;
                Type type = this.GetRealObject(context) as Type;
                this.m_unityType = 8;
                if (this.m_instantiation[0] == null)
                {
                    return null;
                }
                return this.MakeElementTypes(type.MakeGenericType(this.m_instantiation));
            }
            default:
                throw new ArgumentException(Environment.GetResourceString("Invalid Unity type."));
            }
        }
References System.Reflection.MethodBase.GetGenericArguments(), System.Type.GetGenericArguments(), System.Reflection.Assembly.GetModule(), System.UnitySerializationHolder.GetRealObject(), System.Environment.GetResourceString(), System.Type.GetType(), System.Reflection.Assembly.GetType(), System.Reflection.Assembly.Load(), System.UnitySerializationHolder.m_assemblyName, System.UnitySerializationHolder.m_data, System.UnitySerializationHolder.m_declaringMethod, System.UnitySerializationHolder.m_declaringType, System.UnitySerializationHolder.m_genericParameterPosition, System.UnitySerializationHolder.m_instantiation, System.UnitySerializationHolder.m_unityType, System.UnitySerializationHolder.MakeElementTypes(), System.Type.MakeGenericType(), System.UnitySerializationHolder.ThrowInsufficientInformation(), System.DBNull.Value, System.Empty.Value, and System.Reflection.Missing.Value.
Referenced by System.UnitySerializationHolder.GetRealObject().