Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings
MakeDungeon_GetEntranceSettings() [2/2]
static DungeonEntranceSettings Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings (PreGenDungeonEntranceSettings preSettings, DungeonData data) inline static
Definition at line 792 of file DungeonCrawler.cs.
        {
            DungeonEntranceSettings dungeonEntranceSettings = DungeonCrawler.MakeDungeon_GetEntranceSettings(preSettings.EntranceType, preSettings.StyleData, data);
            dungeonEntranceSettings.RandomSeed = preSettings.RandomSeed;
            return dungeonEntranceSettings;
        }
References Terraria.GameContent.Generation.Dungeon.Entrances.DungeonEntranceSettings.EntranceType, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings(), Terraria.GameContent.Generation.Dungeon.Entrances.DungeonEntranceSettings.RandomSeed, and Terraria.GameContent.Generation.Dungeon.Entrances.DungeonEntranceSettings.StyleData.
Referenced by Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonDataVariables(), and Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonGenVarVariables().