Terraria Decompiled: System.UnitySerializationHolder.GetUnitySerializationInfo
GetUnitySerializationInfo() [4/4]
static void System.UnitySerializationHolder.GetUnitySerializationInfo (SerializationInfo info, RuntimeType type) inline static package
Definition at line 84 of file UnitySerializationHolder.cs.
        {
            if (type.GetRootElementType().IsGenericParameter)
            {
                type = UnitySerializationHolder.AddElementTypes(info, type);
                info.SetType(typeof(UnitySerializationHolder));
                info.AddValue("UnityType", 7);
                info.AddValue("GenericParameterPosition", type.GenericParameterPosition);
                info.AddValue("DeclaringMethod", type.DeclaringMethod, typeof(MethodBase));
                info.AddValue("DeclaringType", type.DeclaringType, typeof(Type));
                return;
            }
            int num = 4;
            if (!type.IsGenericTypeDefinition && type.ContainsGenericParameters)
            {
                num = 8;
                type = UnitySerializationHolder.AddElementTypes(info, type);
                info.AddValue("GenericArguments", type.GetGenericArguments(), typeof(Type[]));
                type = (RuntimeType)type.GetGenericTypeDefinition();
            }
            UnitySerializationHolder.GetUnitySerializationInfo(info, num, type.FullName, type.GetRuntimeAssembly());
        }
References System.UnitySerializationHolder.AddElementTypes(), System.RuntimeType.ContainsGenericParameters, System.RuntimeType.DeclaringMethod, System.RuntimeType.DeclaringType, System.RuntimeType.FullName, System.RuntimeType.GenericParameterPosition, System.RuntimeType.GetGenericArguments(), System.RuntimeType.GetGenericTypeDefinition(), System.RuntimeType.GetRuntimeAssembly(), System.UnitySerializationHolder.GetUnitySerializationInfo(), System.info, System.RuntimeType.IsGenericParameter, and System.RuntimeType.IsGenericTypeDefinition.