Terraria Decompiled: Microsoft.Xna.Framework.Content.ReflectiveReader.GetElementReader
GetElementReader()
static ReflectiveReader< T >.ReadElement Microsoft.Xna.Framework.Content.ReflectiveReader< T >.GetElementReader (ContentTypeReaderManager manager, MemberInfo member) inline static private
Definition at line 92 of file ReflectiveReader.cs.
        {
            PropertyInfo property = member as PropertyInfo;
            FieldInfo fieldInfo = member as FieldInfo;
            if (property != null)
            {
                if (!property.CanRead)
                {
                    return null;
                }
                if (property.GetIndexParameters().Length != 0)
                {
                    return null;
                }
            }
            if (Attribute.GetCustomAttribute(member, typeof(ContentSerializerIgnoreAttribute)) != null)
            {
                return null;
            }
            ContentSerializerAttribute contentSerializerAttribute = Attribute.GetCustomAttribute(member, typeof(ContentSerializerAttribute)) as ContentSerializerAttribute;
            if (contentSerializerAttribute == null)
            {
                if (property != null)
                {
                    MethodInfo getMethod = property.GetGetMethod(true);
                    if (getMethod != null && !getMethod.IsPublic)
                    {
                        return null;
                    }
                    MethodInfo setMethod = property.GetSetMethod(true);
                    if (setMethod != null && !setMethod.IsPublic)
                    {
                        return null;
                    }
                    if (!property.CanWrite)
                    {
                        ContentTypeReader typeReader = manager.GetTypeReader(property.PropertyType);
                        if (typeReader == null || !typeReader.CanDeserializeIntoExistingObject)
{
                            return null;
                        }
                    }
                }
                else
                {
                    if (!fieldInfo.IsPublic)
                    {
                        return null;
                    }
                    if (fieldInfo.IsInitOnly)
                    {
                        return null;
                    }
                }
            }
            Action<object, object> setter;
            Type type;
            if (property != null)
            {
                type = property.PropertyType;
                if (property.CanWrite)
                {
                    setter = delegate(object o, object v)
                    {
                        property.SetValue(o, v, null);
                    };
                }
                else
                {
                    setter = delegate(object o, object v)
                    {
                    };
                }
            }
            else
            {
                type = fieldInfo.FieldType;
                setter = new Action<object, object>(fieldInfo.SetValue);
            }
            if (contentSerializerAttribute != null && contentSerializerAttribute.SharedResource)
            {
                return delegate(ContentReader input, object parent)
                {
                    Action<object> action = delegate(object value)
                    {
                        setter(parent, value);
                    };
                    input.ReadSharedResource<object>(action);
                };
            }
            ContentTypeReader reader = manager.GetTypeReader(type);
            if (reader == null)
            {
                throw new ContentLoadException(string.Format("Content reader could not be found for {0} type.", type.FullName));
            }
            Func<object, object> construct = (object parent) => null;
            if (property != null && !property.CanWrite)
            {
                construct = (object parent) => property.GetValue(parent, null);
            }
            return delegate(ContentReader input, object parent)
            {
                object obj = construct(parent);
                object obj2 = input.ReadObject<object>(reader, obj);
                setter(parent, obj2);
            };
        }
References System.action, Microsoft.Xna.Framework.Content.ContentTypeReader< T >.CanDeserializeIntoExistingObject, System.Reflection.FieldInfo.FieldType, System.Format, System.Type.FullName, System.Attribute.GetCustomAttribute(), Microsoft.Xna.Framework.Content.ContentTypeReaderManager.GetTypeReader(), System.input, System.Reflection.FieldInfo.IsInitOnly, System.Reflection.FieldInfo.IsPublic, System.Reflection.MethodBase.IsPublic, System.obj, System.Reflection.FieldInfo.SetValue(), Microsoft.Xna.Framework.Content.ContentSerializerAttribute.SharedResource, and System.value.
Referenced by Microsoft.Xna.Framework.Content.ReflectiveReader< T >.Initialize().