Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings
MakeDungeon_GetRoomSettings()
static DungeonRoomSettings Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings (DungeonRoomType roomType, DungeonData data, DungeonControlLine line) inline static
Definition at line 556 of file DungeonCrawler.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int progressionStage = line.ProgressionStage;
            DungeonGenerationStyleData style = line.Style;
            Vector2D normalizedLineDirection = line.NormalizedLineDirection;
            bool curveLine = line.CurveLine;
            int num = (int)(15.0 * data.roomStrengthScalar);
            int num2 = genRand.Next(13);
            int num3 = genRand.Next(13);
            int num4 = 6;
            int num5 = genRand.Next(12);
            int num6 = genRand.Next(12);
            float num7 = 1f;
            if (data.Type == DungeonType.DualDungeon)
            {
                num7 = 1.25f;
            }
            if ((roomType == DungeonRoomType.GenShapeDoughnut || roomType == DungeonRoomType.GenShapeQuadCircle) && curveLine)
            {
                roomType = DungeonRoomType.GenShapeCircle;
            }
            DungeonRoomSettings dungeonRoomSettings;
            switch (roomType)
            {
            default:
                dungeonRoomSettings = new LegacyDungeonRoomSettings
                {
                    OverrideStrength = num + num2,
                    OverrideSteps = num4 + num5,
                    OverrideVelocity = normalizedLineDirection.SafeNormalize(Vector2D.UnitY)
                };
                break;
            case DungeonRoomType.Regular:
                num = (int)((double)num * 0.8);
                num2 = (int)((double)num2 * 0.8);
                dungeonRoomSettings = new RegularDungeonRoomSettings
                {
                    OverrideOuterBoundsSize = 8,
                    OverrideInnerBoundsSize = num + num2
                };
                break;
            case DungeonRoomType.Wormlike:
            {
                int num8 = num4 * 3 + num5;
                int num9 = num4 * 3 + num6;
                dungeonRoomSettings = new WormlikeDungeonRoomSettings
                {
                    FirstSideIterations = num8,
                    SecondSideIterations = num9
                };
                break;
            }
            case DungeonRoomType.LivingTree:
            {
                num = (int)((double)num * 0.3);
                num2 = (int)((double)num2 * 0.5);
                int num10 = num + num2;
                int num11 = num4 * 6 + num5;
                int num12 = 4 + genRand.Next(3);
                int num13 = (num11 + num12 + num12) / 2;
                dungeonRoomSettings = new LivingTreeDungeonRoomSettings
                {
                    InnerWidth = num10,
                    InnerHeight = num11,
                    Depth = num12,
                    BoundingRadius = num13,
                    ForceStyleForDoorsAndPlatforms = true
                };
                break;
            }
            case DungeonRoomType.BiomeSquare:
            case DungeonRoomType.BiomeRugged:
            case DungeonRoomType.BiomeStructured:
                dungeonRoomSettings = new BiomeDungeonRoomSettings();
                break;
            case DungeonRoomType.GenShapeCircle:
            {
                num = (int)((double)num * 0.8);
                num2 = (int)((double)num2 * 0.8);
                if (num7 != 1f && genRand.Next(3) == 0)
                {
                    num = (int)((float)num * num7);
                    num2 = (int)((float)num2 * num7);
                }
                int num14 = num;
                int num15 = num14 + 8;
                DungeonShapes.CircleRoom circleRoom = new DungeonShapes.CircleRoom(num14 + num2);
                DungeonShapes.CircleRoom circleRoom2 = new DungeonShapes.CircleRoom(num15 + num2);
                dungeonRoomSettings = new GenShapeDungeonRoomSettings
                {
                    ShapeType = GenShapeType.Circle,
                    InnerShape = circleRoom,
                    OuterShape = circleRoom2,
                    BoundingRadius = num15 + num2,
                    HallwayPointAdjuster = new int?(10)
                };
                break;
            }
            case DungeonRoomType.GenShapeMound:
            {
                if (num7 != 1f && genRand.Next(3) == 0)
                {
                    num = (int)((float)num * num7);
                    num2 = (int)((float)num2 * num7);
                }
                int num16 = num + num2;
                int num17 = num16 + 8;
                DungeonShapes.MoundRoom moundRoom = new DungeonShapes.MoundRoom(num16, (int)((double)num16 * 1.5));
                DungeonShapes.MoundRoom moundRoom2 = new DungeonShapes.MoundRoom(num17, (int)((double)num17 * 1.5));
                dungeonRoomSettings = new GenShapeDungeonRoomSettings
                {
                    ShapeType = GenShapeType.Mound,
                    InnerShape = moundRoom,
                    OuterShape = moundRoom2,
                    BoundingRadius = (int)((double)num17 * 1.2)
                };
                break;
            }
            case DungeonRoomType.GenShapeHourglass:
            {
                if (num7 != 1f && genRand.Next(3) == 0)
                {
                    num = (int)((float)num * num7);
                    num2 = (int)((float)num2 * num7);
                }
                int num18 = num + num2 + 10;
                int num19 = num + num3 + 10;
                int num20 = num18 + 16;
                int num21 = num19 + 16;
                DungeonShapes.HourglassRoom hourglassRoom = new DungeonShapes.HourglassRoom(num18, num19, 0f);
                DungeonShapes.HourglassRoom hourglassRoom2 = new DungeonShapes.HourglassRoom(num20, num21, 0.4f);
                dungeonRoomSettings = new GenShapeDungeonRoomSettings
                {
                    ShapeType = GenShapeType.Hourglass,
                    InnerShape = hourglassRoom,
                    OuterShape = hourglassRoom2,
                    BoundingRadius = ((num20 > num21) ? (num20 / 2) : (num21 / 2)) + 5,
                    HallwayPointAdjuster = new int?(5)
                };
                break;
            }
            case DungeonRoomType.GenShapeDoughnut:
            {
                num = (int)((double)num * 0.8);
                num2 = (int)((double)num2 * 0.8);
                int num22 = num + num2;
                int num23 = num + num3;
                int num24 = num22 + 8;
                int num25 = num23 + 8;
                DungeonShapes.CircleRoom circleRoom3 = new DungeonShapes.CircleRoom(num22, num23);
                DungeonShapes.CircleRoom circleRoom4 = new DungeonShapes.CircleRoom(num24, num25);
                dungeonRoomSettings = new GenShapeDungeonRoomSettings
                {
                    ShapeType = GenShapeType.Doughnut,
                    InnerShape = circleRoom3,
                    OuterShape = circleRoom4,
                    BoundingRadius = ((num24 > num25) ? num24 : num25) + 5,
                    HallwayPointAdjuster = new int?(5)
                };
                break;
            }
            case DungeonRoomType.GenShapeQuadCircle:
            {
                if (num7 != 1f && genRand.Next(3) == 0)
                {
                    num = (int)((float)num * 1.5f);
                    num2 = (int)((float)num2 * 1.5f);
                }
                int num26 = Math.Max(5, (int)((float)(num + num2) * 0.5f * 0.75f));
                int num27 = num26 + 8;
                int num28 = (int)((float)num26 * 1.5f);
                DungeonShapes.QuadCircleRoom quadCircleRoom = new DungeonShapes.QuadCircleRoom(num26, num28);
                DungeonShapes.QuadCircleRoom quadCircleRoom2 = new DungeonShapes.QuadCircleRoom(num27, num28);
                dungeonRoomSettings = new GenShapeDungeonRoomSettings
                {
                    ShapeType = GenShapeType.QuadCircle,
                    InnerShape = quadCircleRoom,
                    OuterShape = quadCircleRoom2,
                    BoundingRadius = num27 / 2 + num28 + 4,
                    HallwayPointAdjuster = new int?(5)
                };
                break;
            }
            }
            dungeonRoomSettings.RandomSeed = genRand.Next();
            dungeonRoomSettings.RoomType = roomType;
            dungeonRoomSettings.ProgressionStage = progressionStage;
            dungeonRoomSettings.StyleData = style;
            dungeonRoomSettings.OnCurvedLine = curveLine;
            dungeonRoomSettings.Orientation = SnakeOrientation.Unknown;
            dungeonRoomSettings.ControlLine = line;
            return dungeonRoomSettings;
        }
References Terraria.GameContent.Biomes.DungeonControlLine.CurveLine, Terraria.WorldGen.genRand, int, System.Math.Max(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Biomes.DungeonControlLine.NormalizedLineDirection, Terraria.GameContent.Biomes.DungeonControlLine.ProgressionStage, Terraria.GameContent.Generation.Dungeon.DungeonData.roomStrengthScalar, Terraria.GameContent.Biomes.DungeonControlLine.Style, Terraria.GameContent.Generation.Dungeon.DungeonData.Type, and ReLogic.Utilities.Vector2D.UnitY.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateBiomeRooms(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedRooms(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.TryMakeRegularRoomOnLine().