Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonDataVariables
SetupDungeonDataVariables()
static void Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonDataVariables (int iteration, UnifiedRandom genRand) inline static
Definition at line 206 of file DungeonCrawler.cs.
        {
            DungeonData dungeonData = DungeonCrawler.dungeonData[iteration];
            dungeonData.wallVariants = new int[3];
            switch (dungeonData.genVars.brickWallType)
            {
            default:
                dungeonData.wallVariants[0] = 7;
                dungeonData.wallVariants[1] = 94;
                dungeonData.wallVariants[2] = 95;
                break;
            case 8:
                dungeonData.wallVariants[0] = 8;
                dungeonData.wallVariants[1] = 98;
                dungeonData.wallVariants[2] = 99;
                break;
            case 9:
                dungeonData.wallVariants[0] = 9;
                dungeonData.wallVariants[1] = 96;
                dungeonData.wallVariants[2] = 97;
                break;
            }
            dungeonData.platformItemType = 1384;
            dungeonData.chandelierItemType = 2652;
            dungeonData.doorItemType = 1411;
            switch (dungeonData.genVars.dungeonColor)
            {
            default:
                dungeonData.platformItemType = 1384;
                dungeonData.chandelierItemType = 2652;
                dungeonData.doorItemType = 1411;
                break;
            case DungeonColor.Green:
                dungeonData.platformItemType = 1386;
                dungeonData.chandelierItemType = 2653;
                dungeonData.doorItemType = 1412;
                break;
            case DungeonColor.Pink:
                dungeonData.platformItemType = 1385;
                dungeonData.chandelierItemType = 2654;
                dungeonData.doorItemType = 1413;
                break;
            }
            dungeonData.shelfStyles = new int[3];
            dungeonData.shelfStyles[0] = genRand.Next(9, 13);
            dungeonData.shelfStyles[1] = genRand.Next(9, 13);
            while (dungeonData.shelfStyles[1] == dungeonData.shelfStyles[0])
            {
                dungeonData.shelfStyles[1] = genRand.Next(9, 13);
            }
            dungeonData.shelfStyles[2] = genRand.Next(9, 13);
            while (dungeonData.shelfStyles[2] == dungeonData.shelfStyles[0] || dungeonData.shelfStyles[2] == dungeonData.shelfStyles[1])
            {
                dungeonData.shelfStyles[2] = genRand.Next(9, 13);
            }
            dungeonData.lanternStyles = new int[3];
            dungeonData.lanternStyles[0] = genRand.Next(7);
            dungeonData.lanternStyles[1] = genRand.Next(7);
            while (dungeonData.lanternStyles[1] == dungeonData.lanternStyles[0])
            {
                dungeonData.lanternStyles[1] = genRand.Next(7);
            }
            dungeonData.lanternStyles[2] = genRand.Next(7);
            while (dungeonData.lanternStyles[2] == dungeonData.lanternStyles[0] || dungeonData.lanternStyles[2] == dungeonData.lanternStyles[1])
            {
                dungeonData.lanternStyles[2] = genRand.Next(7);
            }
            dungeonData.bannerStyles = new int[6];
            dungeonData.bannerStyles[0] = 10;
            dungeonData.bannerStyles[1] = 11;
            dungeonData.bannerStyles[2] = 12;
            dungeonData.bannerStyles[3] = 13;
            dungeonData.bannerStyles[4] = 14;
            dungeonData.bannerStyles[5] = 15;
            dungeonData.useSkewedDungeonEntranceHalls = genRand.Next(4) == 0;
            if (dungeonData.genVars.preGenDungeonEntranceSettings.PrecalculateEntrancePosition)
            {
                int num = dungeonData.genVars.dungeonLocation;
                int num2 = 0;
                bool flag = false;
                int num3 = 100;
                int num4 = 3000;
                while (!flag)
                {
                    num4--;
                    if (num4 <= 0)
                    {
                        break;
                    }
                    num = dungeonData.genVars.dungeonLocation - num3 + genRand.Next(num3 * 2);
                    if (num > WorldGen.beachDistance && num < Main.maxTilesX - WorldGen.beachDistance)
                    {
                        num2 = 10;
                        if (SpecialSeedFeatures.DungeonEntranceIsBuried)
{
                            num2 = (int)Main.worldSurface - 10 + GenVars.CurrentDungeonGenVars.preGenDungeonEntranceSettings.BuriedEntranceYOffset;
                        }
                        if (SpecialSeedFeatures.DungeonEntranceIsUnderground)
{
                            if (SpecialSeedFeatures.DungeonEntranceHasATree)
{
                                num2 = (int)GenVars.rockLayer - 20;
                            }
                            else if (dungeonData.Type == DungeonType.DualDungeon)
{
                                num2 = (int)GenVars.worldSurfaceHigh - 20;
                            }
                            else
{
                                num2 = (int)GenVars.rockLayer - 20;
                            }
                        }
                        Tile tile = Main.tile[num, num2];
                        while (tile != null && !tile.active() && tile.liquid <= 0 && tile.wall <= 0)
{
                            num2++;
                            tile = Main.tile[num, num2];
                        }
                        if (!WorldGen.AreAnyTilesInSetNearby(num, num2, TileID.Sets.Clouds, 15) && !WorldGen.AreAnyTilesInSetNearby(num, Math.Max(50, num2 - 50), TileID.Sets.Clouds, 50) && num2 - 40 - dungeonData.genVars.preGenDungeonEntranceSettings.RoughHeight > 0)
{
                            flag = true;
                        }
                    }
                }
                if (flag)
                {
                    dungeonData.genVars.dungeonLocation = num + 25 - genRand.Next(50);
                    dungeonData.genVars.dungeonEntrancePosition = new Vector2D((double)num, (double)num2);
                    return;
                }
                dungeonData.genVars.preGenDungeonEntranceSettings = (PreGenDungeonEntranceSettings)DungeonCrawler.MakeDungeon_GetEntranceSettings(DungeonEntranceType.Legacy, dungeonData.genVars.preGenDungeonEntranceSettings.StyleData, null);
                dungeonData.genVars.dungeonEntrancePosition = Vector2D.Zero;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AreAnyTilesInSetNearby(), Terraria.WorldGen.beachDistance, Terraria.ID.TileID.Sets.Clouds, Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.dungeonData, Terraria.GameContent.SpecialSeedFeatures.DungeonEntranceHasATree, Terraria.GameContent.SpecialSeedFeatures.DungeonEntranceIsBuried, Terraria.GameContent.SpecialSeedFeatures.DungeonEntranceIsUnderground, int, Terraria.Tile.liquid, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldBuilding.GenVars.rockLayer, Terraria.Main.tile, Terraria.Tile.wall, Terraria.Main.worldSurface, Terraria.WorldBuilding.GenVars.worldSurfaceHigh, and ReLogic.Utilities.Vector2D.Zero.
Referenced by Terraria.WorldGen.AddPasses().