Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon
MakeDungeon()
static void Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon (int x, int y, GenerationProgress progress = null) inline static
Definition at line 342 of file DungeonCrawler.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            DungeonData currentDungeonData = DungeonCrawler.CurrentDungeonData;
            DungeonFeatureSettings dungeonFeatureSettings = new DungeonFeatureSettings();
            currentDungeonData.genVars.GeneratingDungeon = true;
            DungeonUtils.UpdateDungeonProgress(progress, 0f, Language.GetTextValue("WorldGeneration.DungeonVariableSetup"), false);
            ushort brickTileType = currentDungeonData.genVars.brickTileType;
            ushort brickCrackedTileType = currentDungeonData.genVars.brickCrackedTileType;
            ushort brickWallType = currentDungeonData.genVars.brickWallType;
            WorldGen.SetCrackedBrickSolidity(false);
            currentDungeonData.makeNextPitTrapFlooded = true;
            currentDungeonData.genVars.generatingDungeonPositionX = x;
            currentDungeonData.genVars.generatingDungeonPositionY = y;
            currentDungeonData.dungeonBounds.SetBounds(x, y, x, y);
            currentDungeonData.dungeonEntranceStrengthX = (double)genRand.Next(25, 30);
            currentDungeonData.dungeonEntranceStrengthY = (double)genRand.Next(20, 25);
            currentDungeonData.dungeonEntranceStrengthX2 = (double)genRand.Next(35, 50);
            currentDungeonData.dungeonEntranceStrengthY2 = (double)genRand.Next(10, 15);
            int num = Main.maxTilesX / 60;
            num += genRand.Next(0, num / 3);
            num = (int)((double)num * currentDungeonData.dungeonStepScalar);
            int num2 = num;
            int num3 = 5;
            currentDungeonData.globalFeatureScalar = 1.0;
            if (currentDungeonData.Type == DungeonType.DualDungeon)
            {
                new DualDungeonLayoutProvider(new DualDungeonLayoutProviderSettings
                {
                    StyleData = currentDungeonData.genVars.dungeonStyle
                }).ProvideLayout(currentDungeonData, progress, genRand, ref num3);
                currentDungeonData.globalFeatureScalar = Math.Max(1.0, (double)currentDungeonData.dungeonRooms.Count / 20.0);
            }
            else
            {
                new LegacyDungeonLayoutProvider(new LegacyDungeonLayoutProviderSettings
                {
                    StyleData = currentDungeonData.genVars.dungeonStyle,
                    Steps = num,
                    MaxSteps = num2
                }).ProvideLayout(currentDungeonData, progress, genRand, ref num3);
            }
            DungeonBounds dungeonBounds = currentDungeonData.dungeonRooms[0].InnerBounds;
            Vector2 vector = new Vector2((float)dungeonBounds.Center.X, (float)dungeonBounds.Top);
            float num4 = vector.X;
            float num5 = vector.Y;
            if (currentDungeonData.Type == DungeonType.Default)
            {
                for (int i = 1; i < currentDungeonData.dungeonRooms.Count; i++)
                {
                    if (currentDungeonData.dungeonRooms[i].generated)
                    {
                        dungeonBounds = currentDungeonData.dungeonRooms[i].InnerBounds;
                        vector = new Vector2((float)dungeonBounds.Center.X, (float)dungeonBounds.Top);
                        if (vector.Y < num5)
{
                            num4 = vector.X;
                            num5 = vector.Y;
                        }
                    }
                }
            }
            currentDungeonData.genVars.generatingDungeonPositionX = (int)num4;
            currentDungeonData.genVars.generatingDungeonPositionY = (int)num5;
            currentDungeonData.genVars.generatingDungeonTopX = (int)num4;
            DungeonUtils.UpdateDungeonProgress(progress, 0.65f, Language.GetTextValue("WorldGeneration.DungeonEntranceHallway"), false);
            currentDungeonData.createdDungeonEntranceOnSurface = false;
            num3 = 5;
            Vector2D dungeonEntrancePosition = currentDungeonData.genVars.dungeonEntrancePosition;
            bool flag = dungeonEntrancePosition != Vector2D.Zero;
            if (flag && WorldGen.SecretSeed.surfaceIsDesert.Enabled && currentDungeonData.Type == DungeonType.DualDungeon)
            {
                currentDungeonData.createdDungeonEntranceOnSurface = true;
            }
            if (WorldGen.drunkWorldGen || WorldGen.SecretSeed.noSurface.Enabled)
            {
                currentDungeonData.createdDungeonEntranceOnSurface = true;
            }
            Vector2D vector2D;
            vector2D..ctor((double)currentDungeonData.genVars.generatingDungeonPositionX, (double)currentDungeonData.genVars.generatingDungeonPositionY);
            double num6 = (flag ? dungeonEntrancePosition.Distance(vector2D) : 0.0);
            int num7 = (int)num6;
            int num8 = 100;
            while (!currentDungeonData.createdDungeonEntranceOnSurface)
            {
                num8--;
                if (num8 <= 0)
                {
                    break;
                }
                if (num3 > 0)
                {
                    num3--;
                }
                if (num3 == 0 && genRand.Next(5) == 0 && (double)currentDungeonData.genVars.generatingDungeonPositionY > Main.worldSurface + 100.0)
                {
                    num3 = 10;
                    int generatingDungeonPositionX = currentDungeonData.genVars.generatingDungeonPositionX;
                    int generatingDungeonPositionY = currentDungeonData.genVars.generatingDungeonPositionY;
                    DungeonCrawler.MakeDungeon_GetHall_Legacy((LegacyDungeonHallSettings)DungeonCrawler.MakeDungeon_GetHallSettings(DungeonHallType.Legacy, currentDungeonData, Vector2.Zero, Vector2.Zero, currentDungeonData.genVars.dungeonStyle)).GenerateHall(currentDungeonData, currentDungeonData.genVars.generatingDungeonPositionX, currentDungeonData.genVars.generatingDungeonPositionY);
                    DungeonCrawler.MakeDungeon_GetRoom(new LegacyDungeonRoomSettings
                    {
                        RoomPosition = new Point(currentDungeonData.genVars.generatingDungeonPositionX, currentDungeonData.genVars.generatingDungeonPositionY),
                        RandomSeed = genRand.Next(),
                        StyleData = currentDungeonData.genVars.dungeonStyle
                    }, true).GenerateRoom(currentDungeonData);
                    currentDungeonData.genVars.generatingDungeonPositionX = generatingDungeonPositionX;
                    currentDungeonData.genVars.generatingDungeonPositionY = generatingDungeonPositionY;
                }
                if (flag)
                {
                    DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated(currentDungeonData, genRand, num6, dungeonEntrancePosition, ref num7, ref vector2D);
                }
                else
                {
                    DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Legacy(currentDungeonData, currentDungeonData.genVars.generatingDungeonPositionX, currentDungeonData.genVars.generatingDungeonPositionY);
                }
            }
            DungeonCrawler.MakeDungeon_GetEntrance(DungeonCrawler.MakeDungeon_GetEntranceSettings(currentDungeonData.genVars.preGenDungeonEntranceSettings, currentDungeonData), true).GenerateEntrance(currentDungeonData, currentDungeonData.genVars.generatingDungeonPositionX, currentDungeonData.genVars.generatingDungeonPositionY);
            if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
            {
                currentDungeonData.dungeonBounds.Top = 25;
            }
            DungeonUtils.UpdateDungeonProgress(progress, 0.675f, Language.GetTextValue("WorldGeneration.DungeonFindingDoorsAndPlatforms"), false);
            for (int j = 0; j < currentDungeonData.dungeonRooms.Count; j++)
            {
                DungeonRoom dungeonRoom = currentDungeonData.dungeonRooms[j];
                if (dungeonRoom.Processed)
                {
                    dungeonRoom.CalculatePlatformsAndDoors(currentDungeonData);
                }
            }
            for (int k = 0; k < currentDungeonData.dungeonHalls.Count; k++)
            {
                DungeonHall dungeonHall = currentDungeonData.dungeonHalls[k];
                if (dungeonHall.Processed)
                {
                    dungeonHall.CalculatePlatformsAndDoors(currentDungeonData);
                }
            }
            DungeonUtils.UpdateDungeonProgress(progress, 0.7f, Language.GetTextValue("WorldGeneration.DungeonEarly"), false);
            new DungeonGlobalEarlyDualDungeonFeatures(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.75f, Language.GetTextValue("WorldGeneration.DungeonSpikes"), false);
            new DungeonGlobalSpikes(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.8f, Language.GetTextValue("WorldGeneration.DungeonDoors"), false);
            new DungeonGlobalDoors(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.825f, Language.GetTextValue("WorldGeneration.DungeonWallVariants"), false);
            new DungeonGlobalWallVariants(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.85f, Language.GetTextValue("WorldGeneration.DungeonPlatforms"), false);
            new DungeonGlobalPlatforms(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.875f, Language.GetTextValue("WorldGeneration.DungeonBiomeChests"), false);
            new DungeonGlobalBiomeChests(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.9f, Language.GetTextValue("WorldGeneration.DungeonBookshelves"), false);
            new DungeonGlobalBookshelves(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.92f, Language.GetTextValue("WorldGeneration.DungeonChests"), false);
            new DungeonGlobalBasicChests(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.935f, Language.GetTextValue("WorldGeneration.DungeonArea"), false);
            int num9 = 25;
            currentDungeonData.dungeonBounds.Inflate(num9);
            DungeonUtils.UpdateDungeonProgress(progress, 0.94f, Language.GetTextValue("WorldGeneration.DungeonLights"), false);
            new DungeonGlobalLights(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.95f, Language.GetTextValue("WorldGeneration.DungeonTraps"), false);
            new DungeonGlobalTraps(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.96f, Language.GetTextValue("WorldGeneration.DungeonFurniture"), false);
            new DungeonGlobalGroundFurniture(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.97f, Language.GetTextValue("WorldGeneration.DungeonPictures"), false);
            new DungeonGlobalPaintings(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.98f, Language.GetTextValue("WorldGeneration.DungeonBanners"), false);
            new DungeonGlobalBanners(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 0.99f, Language.GetTextValue("WorldGeneration.DungeonLate"), false);
            new DungeonGlobalLateDualDungeonFeatures(dungeonFeatureSettings).GenerateFeature(currentDungeonData);
            DungeonUtils.UpdateDungeonProgress(progress, 1f, Language.GetTextValue("WorldGeneration.DungeonComplete"), false);
            currentDungeonData.genVars.GeneratingDungeon = false;
        }
References Terraria.GameContent.Generation.Dungeon.DungeonGenVars.brickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.brickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.brickWallType, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CalculatePlatformsAndDoors(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculatePlatformsAndDoors(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Center, System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonData.createdDungeonEntranceOnSurface, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.CurrentDungeonData, ReLogic.Utilities.Vector2D.Distance(), Terraria.WorldGen.drunkWorldGen, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonEntrancePosition, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonHalls, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonStepScalar, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBasicChests.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPlatforms.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalTraps.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.GenerateFeature(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionX, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionY, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Inflate(), int, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Legacy(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntrance(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall_Legacy(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHallSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), System.Math.Max(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.preGenDungeonEntranceSettings, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.Processed, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.Processed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.WorldGen.SetCrackedBrickSolidity(), Terraria.WorldGen.SecretSeed.surfaceIsDesert, Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.GameContent.Generation.Dungeon.DungeonData.Type, Terraria.GameContent.Generation.Dungeon.DungeonUtils.UpdateDungeonProgress(), Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector2.Zero, and ReLogic.Utilities.Vector2D.Zero.
Referenced by Terraria.WorldGen.AddPasses().