Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom
MakeDungeon_GetRoom()
static DungeonRoom Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom (DungeonRoomSettings settings, bool addToData = true) inline static
Definition at line 878 of file DungeonCrawler.cs.
        {
            DungeonRoom dungeonRoom;
            switch (settings.RoomType)
            {
            default:
                dungeonRoom = new LegacyDungeonRoom(settings);
                break;
            case DungeonRoomType.Regular:
                dungeonRoom = new RegularDungeonRoom(settings);
                break;
            case DungeonRoomType.Wormlike:
                dungeonRoom = new WormlikeDungeonRoom(settings);
                break;
            case DungeonRoomType.LivingTree:
                dungeonRoom = new LivingTreeDungeonRoom(settings);
                break;
            case DungeonRoomType.BiomeSquare:
                dungeonRoom = new BiomeSquareDungeonRoom(settings);
                break;
            case DungeonRoomType.BiomeRugged:
                dungeonRoom = new BiomeRuggedDungeonRoom(settings);
                break;
            case DungeonRoomType.BiomeStructured:
                dungeonRoom = new BiomeStructuredDungeonRoom(settings);
                break;
            case DungeonRoomType.GenShapeCircle:
            case DungeonRoomType.GenShapeMound:
            case DungeonRoomType.GenShapeHourglass:
            case DungeonRoomType.GenShapeDoughnut:
            case DungeonRoomType.GenShapeQuadCircle:
                dungeonRoom = new GenShapeDungeonRoom(settings);
                break;
            }
            if (addToData && dungeonRoom != null)
            {
                DungeonCrawler.CurrentDungeonData.dungeonRooms.Add(dungeonRoom);
            }
            return dungeonRoom;
        }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.CurrentDungeonData, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, and Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RoomType.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateBiomeRooms(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateStartingRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedRooms(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.LegacyDungeonLayoutProvider.LegacyDungeonLayout(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), and Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_TryRoom().