Terraria Decompiled: System.UnitySerializationHolder.AddElementTypes
AddElementTypes()
static RuntimeType System.UnitySerializationHolder.AddElementTypes (SerializationInfo info, RuntimeType type) inline static package
Definition at line 21 of file UnitySerializationHolder.cs.
        {
            List<int> list = new List<int>();
            while (type.HasElementType)
            {
                if (type.IsSzArray)
                {
                    list.Add(3);
                }
                else if (type.IsArray)
                {
                    list.Add(type.GetArrayRank());
                    list.Add(2);
                }
                else if (type.IsPointer)
                {
                    list.Add(1);
                }
                else if (type.IsByRef)
                {
                    list.Add(4);
                }
                type = (RuntimeType)type.GetElementType();
            }
            info.AddValue("ElementTypes", list.ToArray(), typeof(int[]));
            return type;
        }
References System.RuntimeType.GetArrayRank(), System.RuntimeType.GetElementType(), System.info, System.RuntimeType.IsSzArray, and System.list.
Referenced by System.UnitySerializationHolder.GetUnitySerializationInfo().