Terraria Decompiled: Terraria.Graphics.Renderers.FadingPlayerShaderParticle.Draw
Draw()
override void Terraria.Graphics.Renderers.FadingPlayerShaderParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 28 of file FadingPlayerShaderParticle.cs.
        {
            if (this._player == null || this._shader == 0)
            {
                base.Draw(ref settings, spritebatch);
                return;
            }
            Effect pixelShader = Main.pixelShader;
            Color color = (this.fullbright ? this.ColorTint : this.ColorTint.MultiplyRGB(Lighting.GetColor(this.LocalPosition.ToTileCoordinates()))) * Utils.GetLerpValue(0f, this.FadeInNormalizedTime, this.timeSinceSpawn / this.timeTolive, true) * Utils.GetLerpValue(1f, this.FadeOutNormalizedTime, this.timeSinceSpawn / this.timeTolive, true);
            DrawData drawData = default(DrawData);
            drawData.texture = this._texture.Value;
            drawData.sourceRect = new Rectangle?(this._texture.Frame(1, 1, 0, 0, 0, 0));
            drawData.shader = this._shader;
            PlayerDrawHelper.SetShaderForData(this._player, this._shader, ref drawData);
            spritebatch.Draw(this._texture.Value, settings.AnchorPosition + this.LocalPosition, new Rectangle?(this._frame), color, this.Rotation, this._origin, this.Scale, SpriteEffects.None, 0f);
            pixelShader.CurrentTechnique.Passes[0].Apply();
        }
References Terraria.Graphics.Renderers.ABasicParticle._origin, Terraria.Graphics.Renderers.FadingPlayerShaderParticle._player, Terraria.Graphics.Renderers.FadingPlayerShaderParticle._shader, Terraria.Graphics.Renderers.ABasicParticle._texture, Terraria.Graphics.Renderers.FadingParticle.ColorTint, Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Graphics.Renderers.FadingParticle.FadeOutNormalizedTime, Terraria.Lighting.GetColor(), Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.Graphics.Renderers.ABasicParticle.Rotation, Terraria.Graphics.Renderers.ABasicParticle.Scale, Terraria.DataStructures.PlayerDrawHelper.SetShaderForData(), Terraria.Graphics.Renderers.FadingParticle.timeSinceSpawn, Terraria.Graphics.Renderers.FadingParticle.timeTolive, and ReLogic.Content.Asset< T >.Value.