Terraria Decompiled: Terraria.Testing.QuickLoad.TryRead
TryRead()
static bool Terraria.Testing.QuickLoad.TryRead (out QuickLoad config) inline static
Definition at line 86 of file QuickLoad.cs.
        {
            config = null;
            bool flag;
            try
            {
                if (!File.Exists(QuickLoad.FilePath))
                {
                    flag = false;
                }
                else
                {
                    config = QuickLoad.Deserialize(File.ReadAllText(QuickLoad.FilePath));
                    flag = true;
                }
            }
            catch (Exception)
            {
                flag = false;
            }
            return flag;
        }
References Terraria.Testing.QuickLoad.Deserialize(), System.IO.File.Exists(), Terraria.Testing.QuickLoad.FilePath, and System.IO.File.ReadAllText().
Referenced by Terraria.Testing.QuickLoad.Load().