Terraria Decompiled: Terraria.Testing.QuickLoad.ShiftHeldX11
ShiftHeldX11()
static bool Terraria.Testing.QuickLoad.ShiftHeldX11 () inline static private
Definition at line 189 of file QuickLoad.cs.
        {
            IntPtr intPtr = QuickLoad.XOpenDisplay(IntPtr.Zero);
            if (intPtr == IntPtr.Zero)
            {
                return false;
            }
            bool flag3;
            try
            {
                int num = QuickLoad.XKeysymToKeycode(intPtr, 65505UL);
                int num2 = QuickLoad.XKeysymToKeycode(intPtr, 65506UL);
                byte[] array = new byte[32];
                QuickLoad.XQueryKeymap(intPtr, array);
                bool flag = ((int)array[num / 8] & (1 << num % 8)) != 0;
                bool flag2 = ((int)array[num2 / 8] & (1 << num2 % 8)) != 0;
                flag3 = flag || flag2;
            }
            finally
            {
                QuickLoad.XCloseDisplay(intPtr);
            }
            return flag3;
        }
References System.array, int, Terraria.Testing.QuickLoad.XCloseDisplay(), Terraria.Testing.QuickLoad.XKeysymToKeycode(), Terraria.Testing.QuickLoad.XOpenDisplay(), Terraria.Testing.QuickLoad.XQueryKeymap(), and System.IntPtr.Zero.
Referenced by Terraria.Testing.QuickLoad.ShiftHeld().