Terraria Decompiled: System.Security.Policy.ApplicationDirectory.ToString
ToString()
override string System.Security.Policy.ApplicationDirectory.ToString () inline
Definition at line 61 of file ApplicationDirectory.cs.
        {
            this.ThrowOnInvalid(this.Directory);
            SecurityElement securityElement = new SecurityElement("System.Security.Policy.ApplicationDirectory");
            securityElement.AddAttribute("version", "1");
            securityElement.AddChild(new SecurityElement("Directory", this.directory));
            return securityElement.ToString();
        }
References System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.Security.Policy.ApplicationDirectory.directory, System.Security.Policy.ApplicationDirectory.ThrowOnInvalid(), and System.Security.SecurityElement.ToString().