Terraria Decompiled: System.Security.Permissions.PermissionSetAttribute.CreatePermissionSet
CreatePermissionSet()
PermissionSet System.Security.Permissions.PermissionSetAttribute.CreatePermissionSet () inline
Definition at line 143 of file PermissionSetAttribute.cs.
        {
            PermissionSet permissionSet = null;
            if (base.Unrestricted)
            {
                permissionSet = new PermissionSet(PermissionState.Unrestricted);
            }
            else
            {
                permissionSet = new PermissionSet(PermissionState.None);
                if (this.name != null)
                {
                    return PolicyLevel.CreateAppDomainLevel().GetNamedPermissionSet(this.name);
                }
                if (this.file != null)
                {
                    Encoding encoding = (this.isUnicodeEncoded ? Encoding.Unicode : Encoding.ASCII);
                    using (StreamReader streamReader = new StreamReader(this.file, encoding))
                    {
                        return this.CreateFromXml(streamReader.ReadToEnd());
                    }
                }
                if (this.xml != null)
                {
                    permissionSet = this.CreateFromXml(this.xml);
                }
                else if (this.hex != null)
                {
                    Encoding ascii = Encoding.ASCII;
                    byte[] array = CryptoConvert.FromHex(this.hex);
                    permissionSet = this.CreateFromXml(ascii.GetString(array, 0, array.Length));
                }
            }
            return permissionSet;
        }
References System.array, System.Text.Encoding.ASCII, System.Security.Policy.PolicyLevel.CreateAppDomainLevel(), System.Security.Permissions.PermissionSetAttribute.CreateFromXml(), System.Security.Permissions.PermissionSetAttribute.file, Mono.Security.Cryptography.CryptoConvert.FromHex(), System.Security.Policy.PolicyLevel.GetNamedPermissionSet(), System.Text.Encoding.GetString(), System.Security.Permissions.PermissionSetAttribute.hex, System.Security.Permissions.PermissionSetAttribute.name, System.IO.StreamReader.ReadToEnd(), and System.Security.Permissions.PermissionSetAttribute.xml.