Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom
WormlikeRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 90 of file WormlikeDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            WormlikeDungeonRoomSettings wormlikeDungeonRoomSettings = (WormlikeDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickCrackedTileType = this.settings.StyleData.BrickCrackedTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Point point = new Point(i, j);
            if (base.Processed)
            {
                point = this.Positions[0].ToPoint();
            }
            int num = 9 + unifiedRandom.Next(3);
            int num2 = Math.Max(4, num / 5);
            if (base.Processed)
            {
                num = this.InnerBoundsSizeMax;
                num2 = this.InnerBoundsSizeMin;
            }
            int num3 = 8;
            int num4 = num + num3;
            this.InnerBounds.SetBounds(point.X, point.Y, point.X, point.Y);
            this.OuterBounds.SetBounds(point.X, point.Y, point.X, point.Y);
            Vector2 vector = point.ToVector2();
            Vector2 vector2 = vector;
            List<Vector2> list = new List<Vector2>();
            if (base.Processed)
            {
                list.AddRange(this.Positions);
            }
            vector = vector2;
            Vector2 vector3 = unifiedRandom.NextVector2CircularEdge(1f, 1f);
            Vector2 vector4 = vector3;
            int num5 = wormlikeDungeonRoomSettings.FirstSideIterations;
            int num6 = 0;
            for (int k = 0; k < num5; k++)
            {
                float num7 = (float)k / (float)num5;
                int num8 = (int)Utils.Lerp((double)num, (double)num2, (double)num7);
                num4 = num8 + num3;
                Point point2 = vector.ToPoint();
                this.OuterBounds.UpdateBounds(point2.X - num4, point2.Y - num4, point2.X + num4, point2.Y + num4);
                this.InnerBounds.UpdateBounds(point2.X - num8, point2.Y - num8, point2.X + num8, point2.Y + num8);
                this._outerShapeData.AddBounds(point2.X - num4 - (int)vector2.X, point2.Y - num4 - (int)vector2.Y, point2.X + num4 - (int)vector2.X, point2.Y + num4 - (int)vector2.Y);
                this._innerShapeData.AddBounds(point2.X - num8 - (int)vector2.X, point2.Y - num8 - (int)vector2.Y, point2.X + num8 - (int)vector2.X, point2.Y + num8 - (int)vector2.Y);
                if (!base.Processed)
                {
                    list.Add(vector);
                }
                if (generating)
                {
                    base.GenerateDungeonSquareRoom(data, point2, brickTileType, brickCrackedTileType, brickWallType, num8, num3, false);
                }
                if (base.Processed)
                {
                    num6++;
                    if (num6 < this.Positions.Length)
                    {
                        vector = this.Positions[num6];
                    }
                }
                else
                {
                    vector += vector3;
                    vector3 = vector4.RotatedBy(Utils.Lerp(0.0, 1.5707963705062866, (double)num7), default(Vector2));
                }
            }
            vector = vector2;
            vector3 = vector4.RotatedBy(3.1415927410125732, Vector2.Zero).RotatedByRandom(0.7853981852531433);
            vector4 = vector3;
            num5 = wormlikeDungeonRoomSettings.SecondSideIterations;
            for (int l = 0; l < num5; l++)
            {
                float num9 = (float)l / (float)num5;
                int num8 = (int)Utils.Lerp((double)num, (double)num2, (double)num9);
                num4 = num8 + num3;
                Point point3 = vector.ToPoint();
                this.OuterBounds.UpdateBounds(point3.X - num4, point3.Y - num4, point3.X + num4, point3.Y + num4);
                this.InnerBounds.UpdateBounds(point3.X - num8, point3.Y - num8, point3.X + num8, point3.Y + num8);
                this._outerShapeData.AddBounds(point3.X - num4 - (int)vector2.X, point3.Y - num4 - (int)vector2.Y, point3.X + num4 - (int)vector2.X, point3.Y + num4 - (int)vector2.Y);
                this._innerShapeData.AddBounds(point3.X - num8 - (int)vector2.X, point3.Y - num8 - (int)vector2.Y, point3.X + num8 - (int)vector2.X, point3.Y + num8 - (int)vector2.Y);
                if (!base.Processed)
                {
                    list.Add(vector);
                }
                if (generating)
                {
                    base.GenerateDungeonSquareRoom(data, point3, brickTileType, brickCrackedTileType, brickWallType, num8, num3, false);
                }
                if (base.Processed)
                {
                    num6++;
                    if (num6 < this.Positions.Length)
                    {
                        vector = this.Positions[num6];
                    }
                }
                else
                {
                    vector += vector3;
                    vector3 = vector4.RotatedBy(Utils.Lerp(0.0, 1.5707963705062866, (double)num9), default(Vector2));
                }
            }
            this.Positions = list.ToArray<Vector2>();
            this.InnerBoundsSizeMin = num2;
            this.InnerBoundsSizeMax = num;
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
            this._floodedTileCount = DungeonUtils.CalculateFloodedTileCountFromShapeData(this.InnerBounds, this._innerShapeData);
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom._innerShapeData, Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom._outerShapeData, Terraria.WorldBuilding.ShapeData.AddBounds(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculateFloodedTileCountFromShapeData(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoomSettings.FirstSideIterations, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.InnerBoundsSizeMax, Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.InnerBoundsSizeMin, int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Utils.Lerp(), System.list, System.Math.Max(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.Positions, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoomSettings.SecondSideIterations, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.GenerateRoom().