Terraria Decompiled: ReLogic.Content.Sources.XnaContentSource.GetTitleLocationPath
GetTitleLocationPath()
static string ReLogic.Content.Sources.XnaContentSource.GetTitleLocationPath () inline static
Definition at line 92 of file XnaContentSource.cs.
        {
            string text = string.Empty;
            Assembly assembly = Assembly.GetEntryAssembly();
            if (assembly == null)
            {
                assembly = Assembly.GetCallingAssembly();
            }
            if (assembly != null)
            {
                text = Path.GetDirectoryName(assembly.Location);
            }
            return text;
        }
References System.Reflection.Assembly.GetCallingAssembly(), System.IO.Path.GetDirectoryName(), System.Reflection.Assembly.GetEntryAssembly(), System.Reflection.Assembly.Location, and System.text.