Terraria Decompiled: Terraria.GameContent.Drawing.DrawBlackHelper.EndStrip
EndStrip()
void Terraria.GameContent.Drawing.DrawBlackHelper.EndStrip () inline
Definition at line 34 of file DrawBlackHelper.cs.
        {
            if (this.startX == this.endX)
            {
                return;
            }
            Vector2 vector = new Vector2((float)(this.startX << 4), (float)(this.y << 4)) - Main.screenPosition + this.drawOffset;
            Main.tileBatch.SetLayer(this.layer, 0);
            Main.tileBatch.Draw(TextureAssets.BlackTile.Value, new Vector4(vector.X, vector.Y, (float)(this.endX - this.startX << 4), 16f), Color.Black);
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BlackTile, Terraria.GameContent.Drawing.DrawBlackHelper.drawOffset, Terraria.GameContent.Drawing.DrawBlackHelper.endX, Terraria.GameContent.Drawing.DrawBlackHelper.layer, Terraria.GameContent.Drawing.DrawBlackHelper.startX, Terraria.Main.tileBatch, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.GameContent.Drawing.DrawBlackHelper.y.
Referenced by Terraria.GameContent.Drawing.TileDrawing.Draw(), Terraria.GameContent.Drawing.DrawBlackHelper.DrawBlack(), and Terraria.GameContent.Drawing.WallDrawing.DrawWalls().