Terraria Decompiled: Microsoft.Xna.Framework.Content.Texture3DReader.Read
Read()
override Texture3D Microsoft.Xna.Framework.Content.Texture3DReader.Read (ContentReader reader, Texture3D existingInstance) inline package
Definition at line 10 of file Texture3DReader.cs.
        {
            SurfaceFormat surfaceFormat = (SurfaceFormat)reader.ReadInt32();
            int num = reader.ReadInt32();
            int num2 = reader.ReadInt32();
            int num3 = reader.ReadInt32();
            int num4 = reader.ReadInt32();
            Texture3D texture3D;
            if (existingInstance == null)
            {
                texture3D = new Texture3D(reader.ContentManager.GetGraphicsDevice(), num, num2, num3, num4 > 1, surfaceFormat);
            }
            else
            {
                texture3D = existingInstance;
            }
            for (int i = 0; i < num4; i++)
            {
                int num5 = reader.ReadInt32();
                byte[] array = reader.ReadBytes(num5);
                texture3D.SetData<byte>(i, 0, 0, num, num2, 0, num3, array, 0, num5);
                num = Math.Max(num >> 1, 1);
                num2 = Math.Max(num2 >> 1, 1);
                num3 = Math.Max(num3 >> 1, 1);
            }
            return texture3D;
        }
References System.array, Microsoft.Xna.Framework.Content.ContentReader.ContentManager, Microsoft.Xna.Framework.Content.ContentManager.GetGraphicsDevice(), System.Math.Max(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), and Microsoft.Xna.Framework.Graphics.Texture3D.