Terraria Decompiled: Terraria.GameContent.Biomes.JunglePass.ApplyPass
ApplyPass()
override void Terraria.GameContent.Biomes.JunglePass.ApplyPass (GenerationProgress progress, GameConfiguration configuration) inline protected
Definition at line 20 of file JunglePass.cs.
        {
            progress.Message = Lang.gen[11].Value;
            this._worldScale = (double)Main.maxTilesX / 4200.0 * 1.5;
            double worldScale = this._worldScale;
            Point point = this.CreateStartPoint();
            int num = point.X;
            int num2 = point.Y;
            Point zero = Point.Zero;
            this.ApplyRandomMovement(ref num, ref num2, 100, 100);
            zero.X += num;
            zero.Y += num2;
            this.PlaceFirstPassMud(num, num2, 3);
            this.PlaceGemsAt(num, num2, 63, 2);
            progress.Set(0.15);
            this.ApplyRandomMovement(ref num, ref num2, 250, 150);
            zero.X += num;
            zero.Y += num2;
            this.PlaceFirstPassMud(num, num2, 0);
            this.PlaceGemsAt(num, num2, 65, 2);
            progress.Set(0.3);
            int num3 = num;
            int num4 = num2;
            this.ApplyRandomMovement(ref num, ref num2, 400, 150);
            zero.X += num;
            zero.Y += num2;
            this.PlaceFirstPassMud(num, num2, -3);
            this.PlaceGemsAt(num, num2, 67, 2);
            progress.Set(0.45);
            num = zero.X / 3;
            num2 = zero.Y / 3;
            int num5 = GenBase._random.Next((int)(400.0 * worldScale), (int)(600.0 * worldScale));
            int num6 = (int)(25.0 * worldScale);
            num = Utils.Clamp<int>(num, GenVars.leftBeachEnd + num5 / 2 + num6, GenVars.rightBeachStart - num5 / 2 - num6);
            GenVars.mudWall = true;
            WorldGen.TileRunner(num, num2, (double)num5, 10000, 59, false, 0.0, -20.0, true, true, -1);
            if (!WorldGen.SecretSeed.extraLiquid.Enabled)
            {
                this.GenerateTunnelToSurface(num, num2);
            }
            GenVars.mudWall = false;
            progress.Set(0.6);
            this.GenerateHolesInMudWalls();
            this.GenerateFinishingTouches(progress, num3, num4);
        }
References Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.JunglePass._worldScale, Terraria.GameContent.Biomes.JunglePass.ApplyRandomMovement(), Terraria.Utils.Clamp(), Terraria.GameContent.Biomes.JunglePass.CreateStartPoint(), Terraria.WorldGen.SecretSeed.extraLiquid, Terraria.Lang.gen, Terraria.GameContent.Biomes.JunglePass.GenerateFinishingTouches(), Terraria.GameContent.Biomes.JunglePass.GenerateHolesInMudWalls(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), int, Terraria.Main.maxTilesX, Terraria.GameContent.Biomes.JunglePass.PlaceFirstPassMud(), Terraria.GameContent.Biomes.JunglePass.PlaceGemsAt(), Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.TileRunner(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Point.Zero.