Terraria Decompiled: Terraria.GameContent.Biomes.JunglePass.GenerateFinishingTouches
GenerateFinishingTouches()
void Terraria.GameContent.Biomes.JunglePass.GenerateFinishingTouches (GenerationProgress progress, int oldX, int oldY) inline private
Definition at line 218 of file JunglePass.cs.
        {
            int num = oldX;
            int num2 = oldY;
            double worldScale = this._worldScale;
            int num3 = 0;
            while ((double)num3 <= 20.0 * worldScale)
            {
                progress.Set((60.0 + (double)num3 / worldScale) * 0.01);
                num += GenBase._random.Next((int)(-5.0 * worldScale), (int)(6.0 * worldScale));
                num2 += GenBase._random.Next((int)(-5.0 * worldScale), (int)(6.0 * worldScale));
                WorldGen.TileRunner(num, num2, (double)GenBase._random.Next(40, 100), GenBase._random.Next(300, 500), 59, false, 0.0, 0.0, false, true, -1);
                num3++;
            }
            int num4 = 0;
            while ((double)num4 <= 10.0 * worldScale)
            {
                progress.Set((80.0 + (double)num4 / worldScale * 2.0) * 0.01);
                num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
                num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
                while (num < 1 || num >= Main.maxTilesX - 1 || num2 < 1 || num2 >= Main.maxTilesY - 1 || Main.tile[num, num2].type != 59)
                {
                    num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
                    num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
                }
                int num5 = 0;
                while ((double)num5 < 8.0 * worldScale)
                {
                    num += GenBase._random.Next(-30, 31);
                    num2 += GenBase._random.Next(-30, 31);
                    int num6 = -1;
                    if (GenBase._random.Next(7) == 0)
                    {
                        num6 = -2;
                    }
                    WorldGen.TileRunner(num, num2, (double)GenBase._random.Next(10, 20), GenBase._random.Next(30, 70), num6, false, 0.0, 0.0, false, true, -1);
                    num5++;
                }
                num4++;
            }
            int num7 = 0;
            while ((double)num7 <= 300.0 * worldScale)
            {
                num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
                num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
                while (num < 1 || num >= Main.maxTilesX - 1 || num2 < 1 || num2 >= Main.maxTilesY - 1 || Main.tile[num, num2].type != 59)
                {
                    num = oldX + GenBase._random.Next((int)(-600.0 * worldScale), (int)(600.0 * worldScale));
                    num2 = oldY + GenBase._random.Next((int)(-200.0 * worldScale), (int)(200.0 * worldScale));
                }
                WorldGen.TileRunner(num, num2, (double)GenBase._random.Next(4, 10), GenBase._random.Next(5, 30), 1, false, 0.0, 0.0, false, true, -1);
                if (GenBase._random.Next(4) == 0)
                {
                    int num8 = GenBase._random.Next(63, 69);
                    WorldGen.TileRunner(num + GenBase._random.Next(-1, 2), num2 + GenBase._random.Next(-1, 2), (double)GenBase._random.Next(3, 7), GenBase._random.Next(4, 8), num8, false, 0.0, 0.0, false, true, -1);
                }
                num7++;
            }
        }
References Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.JunglePass._worldScale, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.Main.tile, Terraria.WorldGen.TileRunner(), and Terraria.Tile.type.
Referenced by Terraria.GameContent.Biomes.JunglePass.ApplyPass().