Terraria Decompiled: Terraria.Testing.GitStatus.Init
Init()
static void Terraria.Testing.GitStatus.Init () inline static private
Definition at line 24 of file GitStatus.cs.
        {
            if (GitStatus._init)
            {
                return;
            }
            GitStatus._init = true;
            if (!GitStatus.HasGitFolder())
            {
                return;
            }
            try
            {
                GitStatus._gitSHA = GitStatus.GitRevParse();
            }
            catch (Exception ex)
            {
                MessageBox.Show(ex.Message, "git command failed", MessageBoxButtons.OK, MessageBoxIcon.Error);
            }
        }
References Terraria.Testing.GitStatus._init, Terraria.Testing.GitStatus.GitRevParse(), Terraria.Testing.GitStatus.HasGitFolder(), System.Exception.Message, and Terraria.Utilities.MessageBox.Show().