Terraria Decompiled: ReLogic.OS.Windows.NativeMethods.FlashInfo.CreateStop
CreateStop()
static NativeMethods.FlashInfo ReLogic.OS.Windows.NativeMethods.FlashInfo.CreateStop (IntPtr hWnd) inline static
Definition at line 204 of file NativeMethods.cs.
            {
                return new NativeMethods.FlashInfo
                {
                    _cbSize = Convert.ToUInt32(Marshal.SizeOf(typeof(NativeMethods.FlashInfo))),
                    _hWnd = hWnd,
                    _dwFlags = NativeMethods.FlashFlags.Stop,
                    _uCount = uint.MaxValue,
                    _dwTimeout = 0U
                };
            }
References ReLogic.OS.Windows.NativeMethods.FlashInfo._cbSize, ReLogic.OS.Windows.NativeMethods.FlashInfo._dwFlags, ReLogic.OS.Windows.NativeMethods.FlashInfo._dwTimeout, ReLogic.OS.Windows.NativeMethods.FlashInfo._hWnd, ReLogic.OS.Windows.NativeMethods.FlashInfo._uCount, System.Runtime.InteropServices.Marshal.SizeOf(), System.Convert.ToUInt32(), and System.U.
Referenced by ReLogic.OS.Windows.WindowService.StopFlashingIcon().