Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.ValidatePropertyName
ValidatePropertyName()
void Newtonsoft.Json.JsonValidatingReader.ValidatePropertyName (JsonSchemaModel schema) inline private
Definition at line 855 of file JsonValidatingReader.cs.
        {
            if (schema == null)
            {
                return;
            }
            string text = Convert.ToString(this._reader.Value, CultureInfo.InvariantCulture);
            if (this._currentScope.RequiredProperties.ContainsKey(text))
            {
                this._currentScope.RequiredProperties[text] = true;
            }
            if (!schema.AllowAdditionalProperties && !this.IsPropertyDefinied(schema, text))
            {
                this.RaiseError("Property '{0}' has not been defined and the schema does not allow additional properties.".FormatWith(CultureInfo.InvariantCulture, text), schema);
            }
            this._currentScope.CurrentPropertyName = text;
        }
References Newtonsoft.Json.JsonValidatingReader._currentScope, Newtonsoft.Json.JsonValidatingReader._reader, Newtonsoft.Json.Schema.JsonSchemaModel.AllowAdditionalProperties, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonValidatingReader.RaiseError(), System.text, System.Convert.ToString(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken().