Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.WriteToken
WriteToken()
void Newtonsoft.Json.JsonValidatingReader.WriteToken (IList< JsonSchemaModel > schemas) inline private
Definition at line 576 of file JsonValidatingReader.cs.
        {
            foreach (JsonValidatingReader.SchemaScope schemaScope in this._stack)
            {
                bool flag = schemaScope.TokenType == JTokenType.Array && schemaScope.IsUniqueArray && schemaScope.ArrayItemCount > 0;
                if (!flag)
                {
                    if (!Enumerable.Any<JsonSchemaModel>(schemas, (JsonSchemaModel s) => s.Enum != null))
                    {
                        continue;
                    }
                }
                if (schemaScope.CurrentItemWriter == null)
                {
                    if (JsonTokenUtils.IsEndToken(this._reader.TokenType))
                    {
                        continue;
                    }
                    schemaScope.CurrentItemWriter = new JTokenWriter();
                }
                schemaScope.CurrentItemWriter.WriteToken(this._reader, false);
                if (schemaScope.CurrentItemWriter.Top == 0 && this._reader.TokenType != JsonToken.PropertyName)
                {
                    JToken token = schemaScope.CurrentItemWriter.Token;
                    schemaScope.CurrentItemWriter = null;
                    if (flag)
                    {
                        if (Enumerable.Contains<JToken>(schemaScope.UniqueArrayItems, token, JToken.EqualityComparer))
{
                            this.RaiseError("Non-unique array item at index {0}.".FormatWith(CultureInfo.InvariantCulture, schemaScope.ArrayItemCount - 1), Enumerable.First<JsonSchemaModel>(schemaScope.Schemas, (JsonSchemaModel s) => s.UniqueItems));
                        }
                        schemaScope.UniqueArrayItems.Add(token);
                    }
                    else if (Enumerable.Any<JsonSchemaModel>(schemas, (JsonSchemaModel s) => s.Enum != null))
                    {
                        foreach (JsonSchemaModel jsonSchemaModel in schemas)
{
                            if (jsonSchemaModel.Enum != null && !jsonSchemaModel.Enum.ContainsValue(token, JToken.EqualityComparer))
{
                                StringWriter stringWriter = new StringWriter(CultureInfo.InvariantCulture);
                                token.WriteTo(new JsonTextWriter(stringWriter), new JsonConverter[0]);
                                this.RaiseError("Value {0} is not defined in enum.".FormatWith(CultureInfo.InvariantCulture, stringWriter.ToString()), jsonSchemaModel);
                            }
                        }
                    }
                }
            }
        }
References Newtonsoft.Json.JsonValidatingReader._reader, Newtonsoft.Json.Schema.JsonSchemaModel.Enum, Newtonsoft.Json.Linq.JToken.EqualityComparer, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.JsonTokenUtils.IsEndToken(), Newtonsoft.Json.JsonValidatingReader.RaiseError(), System.s, System.IO.StringWriter.ToString(), and Newtonsoft.Json.Linq.JToken.WriteTo().
Referenced by Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken().