Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.RaiseError
RaiseError()
void Newtonsoft.Json.JsonValidatingReader.RaiseError (string message, JsonSchemaModel schema) inline private
Definition at line 226 of file JsonValidatingReader.cs.
        {
            string text = (((IJsonLineInfo)this).HasLineInfo() ? (message + " Line {0}, position {1}.".FormatWith(CultureInfo.InvariantCulture, ((IJsonLineInfo)this).LineNumber, ((IJsonLineInfo)this).LinePosition)) : message);
            this.OnValidationEvent(new JsonSchemaException(text, null, this.Path, ((IJsonLineInfo)this).LineNumber, ((IJsonLineInfo)this).LinePosition));
        }
References System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonValidatingReader.LineNumber, Newtonsoft.Json.JsonValidatingReader.LinePosition, Newtonsoft.Json.JsonValidatingReader.OnValidationEvent(), and System.text.
Referenced by Newtonsoft.Json.JsonValidatingReader.ProcessValue(), Newtonsoft.Json.JsonValidatingReader.TestType(), Newtonsoft.Json.JsonValidatingReader.ValidateEndArray(), Newtonsoft.Json.JsonValidatingReader.ValidateEndObject(), Newtonsoft.Json.JsonValidatingReader.ValidateFloat(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), Newtonsoft.Json.JsonValidatingReader.ValidateNotDisallowed(), Newtonsoft.Json.JsonValidatingReader.ValidatePropertyName(), Newtonsoft.Json.JsonValidatingReader.ValidateString(), and Newtonsoft.Json.JsonValidatingReader.WriteToken().