Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.ValidateFloat
ValidateFloat()
void Newtonsoft.Json.JsonValidatingReader.ValidateFloat (JsonSchemaModel schema) inline private
Definition at line 802 of file JsonValidatingReader.cs.
        {
            if (schema == null)
            {
                return;
            }
            if (!this.TestType(schema, JsonSchemaType.Float))
            {
                return;
            }
            this.ValidateNotDisallowed(schema);
            double num = Convert.ToDouble(this._reader.Value, CultureInfo.InvariantCulture);
            if (schema.Maximum != null)
            {
                if (num > schema.Maximum)
                {
                    this.RaiseError("Float {0} exceeds maximum value of {1}.".FormatWith(CultureInfo.InvariantCulture, JsonConvert.ToString(num), schema.Maximum), schema);
                }
                if (schema.ExclusiveMaximum && num == schema.Maximum)
                {
                    this.RaiseError("Float {0} equals maximum value of {1} and exclusive maximum is true.".FormatWith(CultureInfo.InvariantCulture, JsonConvert.ToString(num), schema.Maximum), schema);
                }
            }
            if (schema.Minimum != null)
            {
                if (num < schema.Minimum)
                {
                    this.RaiseError("Float {0} is less than minimum value of {1}.".FormatWith(CultureInfo.InvariantCulture, JsonConvert.ToString(num), schema.Minimum), schema);
                }
                if (schema.ExclusiveMinimum && num == schema.Minimum)
                {
                    this.RaiseError("Float {0} equals minimum value of {1} and exclusive minimum is true.".FormatWith(CultureInfo.InvariantCulture, JsonConvert.ToString(num), schema.Minimum), schema);
                }
            }
            if (schema.DivisibleBy != null && !JsonValidatingReader.IsZero(JsonValidatingReader.FloatingPointRemainder(num, schema.DivisibleBy.GetValueOrDefault())))
            {
                this.RaiseError("Float {0} is not evenly divisible by {1}.".FormatWith(CultureInfo.InvariantCulture, JsonConvert.ToString(num), schema.DivisibleBy), schema);
            }
        }
References Newtonsoft.Json.JsonValidatingReader._reader, Newtonsoft.Json.Schema.JsonSchemaModel.DivisibleBy, Newtonsoft.Json.Schema.JsonSchemaModel.ExclusiveMaximum, Newtonsoft.Json.Schema.JsonSchemaModel.ExclusiveMinimum, Newtonsoft.Json.JsonValidatingReader.FloatingPointRemainder(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonValidatingReader.IsZero(), Newtonsoft.Json.Schema.JsonSchemaModel.Maximum, Newtonsoft.Json.Schema.JsonSchemaModel.Minimum, Newtonsoft.Json.JsonValidatingReader.RaiseError(), Newtonsoft.Json.JsonValidatingReader.TestType(), System.Convert.ToDouble(), Newtonsoft.Json.JsonConvert.ToString(), Newtonsoft.Json.JsonValidatingReader.ValidateNotDisallowed(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken().