Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken
ValidateCurrentToken()
void Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken () inline private
Definition at line 414 of file JsonValidatingReader.cs.
        {
            if (this._model == null)
            {
                JsonSchemaModelBuilder jsonSchemaModelBuilder = new JsonSchemaModelBuilder();
                this._model = jsonSchemaModelBuilder.Build(this._schema);
                if (!JsonTokenUtils.IsStartToken(this._reader.TokenType))
                {
                    this.Push(new JsonValidatingReader.SchemaScope(JTokenType.None, this.CurrentMemberSchemas));
                }
            }
            switch (this._reader.TokenType)
            {
            case JsonToken.None:
                return;
            case JsonToken.StartObject:
            {
                this.ProcessValue();
                IList<JsonSchemaModel> list = Enumerable.ToList<JsonSchemaModel>(Enumerable.Where<JsonSchemaModel>(this.CurrentMemberSchemas, new Func<JsonSchemaModel, bool>(this.ValidateObject)));
                this.Push(new JsonValidatingReader.SchemaScope(JTokenType.Object, list));
                this.WriteToken(this.CurrentSchemas);
                return;
            }
            case JsonToken.StartArray:
            {
                this.ProcessValue();
                IList<JsonSchemaModel> list2 = Enumerable.ToList<JsonSchemaModel>(Enumerable.Where<JsonSchemaModel>(this.CurrentMemberSchemas, new Func<JsonSchemaModel, bool>(this.ValidateArray)));
                this.Push(new JsonValidatingReader.SchemaScope(JTokenType.Array, list2));
                this.WriteToken(this.CurrentSchemas);
                return;
            }
            case JsonToken.StartConstructor:
                this.ProcessValue();
                this.Push(new JsonValidatingReader.SchemaScope(JTokenType.Constructor, null));
                this.WriteToken(this.CurrentSchemas);
                return;
            case JsonToken.PropertyName:
            {
                this.WriteToken(this.CurrentSchemas);
                using (IEnumerator<JsonSchemaModel> enumerator = this.CurrentSchemas.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        JsonSchemaModel jsonSchemaModel = enumerator.Current;
                        this.ValidatePropertyName(jsonSchemaModel);
                    }
                    return;
                }
                break;
            }
            case JsonToken.Comment:
                goto IL_03BD;
            case JsonToken.Raw:
                break;
            case JsonToken.Integer:
            {
                this.ProcessValue();
                this.WriteToken(this.CurrentMemberSchemas);
                using (IEnumerator<JsonSchemaModel> enumerator = this.CurrentMemberSchemas.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        JsonSchemaModel jsonSchemaModel2 = enumerator.Current;
                        this.ValidateInteger(jsonSchemaModel2);
                    }
                    return;
                }
                goto IL_01D6;
            }
            case JsonToken.Float:
                goto IL_01D6;
            case JsonToken.String:
                goto IL_0222;
            case JsonToken.Boolean:
                goto IL_026E;
            case JsonToken.Null:
                goto IL_02BA;
            case JsonToken.Undefined:
            case JsonToken.Date:
            case JsonToken.Bytes:
                this.WriteToken(this.CurrentMemberSchemas);
                return;
            case JsonToken.EndObject:
                goto IL_0306;
            case JsonToken.EndArray:
                this.WriteToken(this.CurrentSchemas);
                foreach (JsonSchemaModel jsonSchemaModel3 in this.CurrentSchemas)
                {
                    this.ValidateEndArray(jsonSchemaModel3);
                }
                this.Pop();
                return;
            case JsonToken.EndConstructor:
                this.WriteToken(this.CurrentSchemas);
                this.Pop();
                return;
            default:
                goto IL_03BD;
            }
            this.ProcessValue();
            return;
            IL_01D6:
            this.ProcessValue();
            this.WriteToken(this.CurrentMemberSchemas);
            using (IEnumerator<JsonSchemaModel> enumerator = this.CurrentMemberSchemas.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    JsonSchemaModel jsonSchemaModel4 = enumerator.Current;
                    this.ValidateFloat(jsonSchemaModel4);
                }
                return;
            }
            IL_0222:
            this.ProcessValue();
            this.WriteToken(this.CurrentMemberSchemas);
            using (IEnumerator<JsonSchemaModel> enumerator = this.CurrentMemberSchemas.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    JsonSchemaModel jsonSchemaModel5 = enumerator.Current;
                    this.ValidateString(jsonSchemaModel5);
                }
                return;
            }
            IL_026E:
            this.ProcessValue();
            this.WriteToken(this.CurrentMemberSchemas);
            using (IEnumerator<JsonSchemaModel> enumerator = this.CurrentMemberSchemas.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    JsonSchemaModel jsonSchemaModel6 = enumerator.Current;
                    this.ValidateBoolean(jsonSchemaModel6);
                }
                return;
            }
            IL_02BA:
            this.ProcessValue();
            this.WriteToken(this.CurrentMemberSchemas);
            using (IEnumerator<JsonSchemaModel> enumerator = this.CurrentMemberSchemas.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    JsonSchemaModel jsonSchemaModel7 = enumerator.Current;
                    this.ValidateNull(jsonSchemaModel7);
                }
                return;
            }
            IL_0306:
            this.WriteToken(this.CurrentSchemas);
            foreach (JsonSchemaModel jsonSchemaModel8 in this.CurrentSchemas)
            {
                this.ValidateEndObject(jsonSchemaModel8);
            }
            this.Pop();
            return;
            IL_03BD:
            throw new ArgumentOutOfRangeException();
        }
References Newtonsoft.Json.JsonValidatingReader._model, Newtonsoft.Json.JsonValidatingReader._reader, Newtonsoft.Json.JsonValidatingReader._schema, Newtonsoft.Json.Schema.JsonSchemaModelBuilder.Build(), System.Collections.Generic.IEnumerator< out T >.Current, Newtonsoft.Json.JsonValidatingReader.CurrentMemberSchemas, Newtonsoft.Json.JsonValidatingReader.CurrentSchemas, Newtonsoft.Json.Utilities.JsonTokenUtils.IsStartToken(), System.list, System.Collections.IEnumerator.MoveNext(), Newtonsoft.Json.JsonValidatingReader.Pop(), Newtonsoft.Json.JsonValidatingReader.ProcessValue(), Newtonsoft.Json.JsonValidatingReader.Push(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.JsonValidatingReader.ValidateArray(), Newtonsoft.Json.JsonValidatingReader.ValidateBoolean(), Newtonsoft.Json.JsonValidatingReader.ValidateEndArray(), Newtonsoft.Json.JsonValidatingReader.ValidateEndObject(), Newtonsoft.Json.JsonValidatingReader.ValidateFloat(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), Newtonsoft.Json.JsonValidatingReader.ValidateNull(), Newtonsoft.Json.JsonValidatingReader.ValidateObject(), Newtonsoft.Json.JsonValidatingReader.ValidatePropertyName(), Newtonsoft.Json.JsonValidatingReader.ValidateString(), and Newtonsoft.Json.JsonValidatingReader.WriteToken().
Referenced by Newtonsoft.Json.JsonValidatingReader.Read(), Newtonsoft.Json.JsonValidatingReader.ReadAsBoolean(), Newtonsoft.Json.JsonValidatingReader.ReadAsBytes(), Newtonsoft.Json.JsonValidatingReader.ReadAsDateTime(), Newtonsoft.Json.JsonValidatingReader.ReadAsDateTimeOffset(), Newtonsoft.Json.JsonValidatingReader.ReadAsDecimal(), Newtonsoft.Json.JsonValidatingReader.ReadAsDouble(), Newtonsoft.Json.JsonValidatingReader.ReadAsInt32(), and Newtonsoft.Json.JsonValidatingReader.ReadAsString().