Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.ValidateString
ValidateString()
void Newtonsoft.Json.JsonValidatingReader.ValidateString (JsonSchemaModel schema) inline private
Definition at line 690 of file JsonValidatingReader.cs.
        {
            if (schema == null)
            {
                return;
            }
            if (!this.TestType(schema, JsonSchemaType.String))
            {
                return;
            }
            this.ValidateNotDisallowed(schema);
            string text = this._reader.Value.ToString();
            if (schema.MaximumLength != null && text.Length > schema.MaximumLength)
            {
                this.RaiseError("String '{0}' exceeds maximum length of {1}.".FormatWith(CultureInfo.InvariantCulture, text, schema.MaximumLength), schema);
            }
            if (schema.MinimumLength != null && text.Length < schema.MinimumLength)
            {
                this.RaiseError("String '{0}' is less than minimum length of {1}.".FormatWith(CultureInfo.InvariantCulture, text, schema.MinimumLength), schema);
            }
            if (schema.Patterns != null)
            {
                foreach (string text2 in schema.Patterns)
                {
                    if (!Regex.IsMatch(text, text2))
                    {
                        this.RaiseError("String '{0}' does not match regex pattern '{1}'.".FormatWith(CultureInfo.InvariantCulture, text, text2), schema);
                    }
                }
            }
        }
References Newtonsoft.Json.JsonValidatingReader._reader, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Schema.JsonSchemaModel.MaximumLength, Newtonsoft.Json.Schema.JsonSchemaModel.MinimumLength, Newtonsoft.Json.Schema.JsonSchemaModel.Patterns, Newtonsoft.Json.JsonValidatingReader.RaiseError(), Newtonsoft.Json.JsonValidatingReader.TestType(), System.text, Newtonsoft.Json.JsonValidatingReader.ValidateNotDisallowed(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken().