Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.ValidateInteger
ValidateInteger()
void Newtonsoft.Json.JsonValidatingReader.ValidateInteger (JsonSchemaModel schema) inline private
Definition at line 723 of file JsonValidatingReader.cs.
        {
            if (schema == null)
            {
                return;
            }
            if (!this.TestType(schema, JsonSchemaType.Integer))
            {
                return;
            }
            this.ValidateNotDisallowed(schema);
            object value = this._reader.Value;
            if (schema.Maximum != null)
            {
                if (JValue.Compare(JTokenType.Integer, value, schema.Maximum) > 0)
                {
                    this.RaiseError("Integer {0} exceeds maximum value of {1}.".FormatWith(CultureInfo.InvariantCulture, value, schema.Maximum), schema);
                }
                if (schema.ExclusiveMaximum && JValue.Compare(JTokenType.Integer, value, schema.Maximum) == 0)
                {
                    this.RaiseError("Integer {0} equals maximum value of {1} and exclusive maximum is true.".FormatWith(CultureInfo.InvariantCulture, value, schema.Maximum), schema);
                }
            }
            if (schema.Minimum != null)
            {
                if (JValue.Compare(JTokenType.Integer, value, schema.Minimum) < 0)
                {
                    this.RaiseError("Integer {0} is less than minimum value of {1}.".FormatWith(CultureInfo.InvariantCulture, value, schema.Minimum), schema);
                }
                if (schema.ExclusiveMinimum && JValue.Compare(JTokenType.Integer, value, schema.Minimum) == 0)
                {
                    this.RaiseError("Integer {0} equals minimum value of {1} and exclusive minimum is true.".FormatWith(CultureInfo.InvariantCulture, value, schema.Minimum), schema);
                }
            }
            if (schema.DivisibleBy != null)
            {
                bool flag;
                if (value is BigInteger)
                {
                    BigInteger bigInteger = (BigInteger)value;
                    if (!Math.Abs(schema.DivisibleBy.Value - Math.Truncate(schema.DivisibleBy.Value)).Equals(0.0))
                    {
                        flag = bigInteger != 0L;
                    }
                    else
                    {
                        flag = bigInteger % new BigInteger(schema.DivisibleBy.Value) != 0L;
                    }
                }
                else
                {
                    flag = !JsonValidatingReader.IsZero((double)Convert.ToInt64(value, CultureInfo.InvariantCulture) % schema.DivisibleBy.GetValueOrDefault());
                }
                if (flag)
                {
                    this.RaiseError("Integer {0} is not evenly divisible by {1}.".FormatWith(CultureInfo.InvariantCulture, JsonConvert.ToString(value), schema.DivisibleBy), schema);
                }
            }
        }
References Newtonsoft.Json.JsonValidatingReader._reader, System.Math.Abs(), Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.Linq.JValue.Compare(), Newtonsoft.Json.Schema.JsonSchemaModel.DivisibleBy, Newtonsoft.Json.Schema.JsonSchemaModel.ExclusiveMaximum, Newtonsoft.Json.Schema.JsonSchemaModel.ExclusiveMinimum, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonValidatingReader.IsZero(), System.L, Newtonsoft.Json.Schema.JsonSchemaModel.Maximum, Newtonsoft.Json.Schema.JsonSchemaModel.Minimum, Newtonsoft.Json.JsonValidatingReader.RaiseError(), Newtonsoft.Json.JsonValidatingReader.TestType(), System.Convert.ToInt64(), Newtonsoft.Json.JsonConvert.ToString(), System.Math.Truncate(), Newtonsoft.Json.JsonValidatingReader.ValidateNotDisallowed(), System.value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonValidatingReader.ValidateCurrentToken().