Terraria Decompiled: Newtonsoft.Json.JsonValidatingReader.ValidateNotDisallowed
ValidateNotDisallowed()
void Newtonsoft.Json.JsonValidatingReader.ValidateNotDisallowed (JsonSchemaModel schema) inline private
Definition at line 298 of file JsonValidatingReader.cs.
        {
            if (schema == null)
            {
                return;
            }
            JsonSchemaType? currentNodeSchemaType = this.GetCurrentNodeSchemaType();
            if (currentNodeSchemaType != null && JsonSchemaGenerator.HasFlag(new JsonSchemaType?(schema.Disallow), currentNodeSchemaType.GetValueOrDefault()))
            {
                this.RaiseError("Type {0} is disallowed.".FormatWith(CultureInfo.InvariantCulture, currentNodeSchemaType), schema);
            }
        }
References Newtonsoft.Json.Schema.JsonSchemaModel.Disallow, Newtonsoft.Json.JsonValidatingReader.GetCurrentNodeSchemaType(), Newtonsoft.Json.Schema.JsonSchemaGenerator.HasFlag(), System.Globalization.CultureInfo.InvariantCulture, and Newtonsoft.Json.JsonValidatingReader.RaiseError().
Referenced by Newtonsoft.Json.JsonValidatingReader.ValidateBoolean(), Newtonsoft.Json.JsonValidatingReader.ValidateFloat(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), Newtonsoft.Json.JsonValidatingReader.ValidateNull(), and Newtonsoft.Json.JsonValidatingReader.ValidateString().