Terraria Decompiled: Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.JavaScriptDateTimeConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 32 of file JavaScriptDateTimeConverter.cs.
        {
            if (reader.TokenType == JsonToken.Null)
            {
                if (!ReflectionUtils.IsNullable(objectType))
                {
                    throw JsonSerializationException.Create(reader, "Cannot convert null value to {0}.".FormatWith(CultureInfo.InvariantCulture, objectType));
                }
                return null;
            }
            else
            {
                if (reader.TokenType != JsonToken.StartConstructor || !string.Equals(reader.Value.ToString(), "Date", 4))
                {
                    throw JsonSerializationException.Create(reader, "Unexpected token or value when parsing date. Token: {0}, Value: {1}".FormatWith(CultureInfo.InvariantCulture, reader.TokenType, reader.Value));
                }
                reader.Read();
                if (reader.TokenType != JsonToken.Integer)
                {
                    throw JsonSerializationException.Create(reader, "Unexpected token parsing date. Expected Integer, got {0}.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
                }
                DateTime dateTime = DateTimeUtils.ConvertJavaScriptTicksToDateTime((long)reader.Value);
                reader.Read();
                if (reader.TokenType != JsonToken.EndConstructor)
                {
                    throw JsonSerializationException.Create(reader, "Unexpected token parsing date. Expected EndConstructor, got {0}.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
                }
                if ((ReflectionUtils.IsNullableType(objectType) ? Nullable.GetUnderlyingType(objectType) : objectType) == typeof(DateTimeOffset))
                {
                    return new DateTimeOffset(dateTime);
                }
                return dateTime;
            }
        }
References Newtonsoft.Json.Utilities.DateTimeUtils.ConvertJavaScriptTicksToDateTime(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.DateTimeOffset, System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.