Terraria Decompiled: Terraria.GameContent.Tile_Entities.TETrainingDummy.Activate
Activate()
void Terraria.GameContent.Tile_Entities.TETrainingDummy.Activate () inline private
Definition at line 126 of file TETrainingDummy.cs.
        {
            int num = NPC.NewNPC(new EntitySource_TileEntity(this), (int)(this.Position.X * 16 + 16), (int)(this.Position.Y * 16 + 48), 488, 100, 0f, 0f, 0f, 0f, 255);
            if (num == Main.maxNPCs)
            {
                TETrainingDummy.npcSlotsFull = true;
                return;
            }
            Main.npc[num].ai[0] = (float)this.Position.X;
            Main.npc[num].ai[1] = (float)this.Position.Y;
            Main.npc[num].netUpdate = true;
            this.npc = num;
            if (Main.netMode != 1)
            {
                NetMessage.SendData(86, -1, -1, null, this.ID, (float)this.Position.X, (float)this.Position.Y, 0f, 0, 0, 0);
            }
        }
References Terraria.NPC.ai, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Main.npc, and Terraria.NetMessage.SendData().
Referenced by Terraria.GameContent.Tile_Entities.TETrainingDummy.Update().