Terraria Decompiled: Terraria.GameContent.Tile_Entities.TETrainingDummy.Update
Update()
override void Terraria.GameContent.Tile_Entities.TETrainingDummy.Update () inline
Definition at line 41 of file TETrainingDummy.cs.
        {
            if (this.npc != -1)
            {
                if (!Main.npc[this.npc].active || Main.npc[this.npc].type != 488 || Main.npc[this.npc].ai[0] != (float)this.Position.X || Main.npc[this.npc].ai[1] != (float)this.Position.Y)
                {
                    this.Deactivate();
                    return;
                }
            }
            else if (!TETrainingDummy.npcSlotsFull)
            {
                TETrainingDummy.FillPlayerHitboxes();
                Rectangle rectangle = new Rectangle((int)(this.Position.X * 16), (int)(this.Position.Y * 16), 32, 48);
                rectangle.Inflate(1600, 1600);
                bool flag = false;
                foreach (Rectangle rectangle2 in TETrainingDummy.playerBoxes)
                {
                    if (rectangle2.Intersects(rectangle))
                    {
                        flag = true;
                        break;
                    }
                }
                if (flag)
                {
                    this.Activate();
                }
            }
        }
References Terraria.GameContent.Tile_Entities.TETrainingDummy.Activate(), Terraria.NPC.active, Terraria.NPC.ai, Terraria.GameContent.Tile_Entities.TETrainingDummy.Deactivate(), Terraria.GameContent.Tile_Entities.TETrainingDummy.FillPlayerHitboxes(), Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.GameContent.Tile_Entities.TETrainingDummy.npc, Terraria.Main.npc, Terraria.GameContent.Tile_Entities.TETrainingDummy.npcSlotsFull, Terraria.GameContent.Tile_Entities.TETrainingDummy.playerBoxes, and Terraria.NPC.type.