Terraria Decompiled: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent
PublishContent()
void Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent (WorkshopHelper::UGCBased::PublishedItemsFinder finder, WorkshopIssueReporter issueReporter, WorkshopHelper::UGCBased::APublisherInstance::FinishedPublishingAction endAction, string itemTitle, string itemDescription, string contentFolderPath, string previewImagePath, WorkshopItemPublicSettingId publicity, string[] tags) inline
Definition at line 267 of file WorkshopHelper.cs.
                {
                    this._issueReporter = issueReporter;
                    this._endAction = endAction;
                    this._createItemHook = CallResult<CreateItemResult_t>.Create(new CallResult<CreateItemResult_t>.APIDispatchDelegate(this.CreateItemResult));
                    this._updateItemHook = CallResult<SubmitItemUpdateResult_t>.Create(new CallResult<SubmitItemUpdateResult_t>.APIDispatchDelegate(this.UpdateItemResult));
                    ERemoteStoragePublishedFileVisibility visibility = this.GetVisibility(publicity);
                    this._entryData = new WorkshopHelper.UGCBased.SteamWorkshopItem
                    {
                        Title = itemTitle,
                        Description = itemDescription,
                        ContentFolderPath = contentFolderPath,
                        Tags = tags,
                        PreviewImagePath = previewImagePath,
                        Visibility = new ERemoteStoragePublishedFileVisibility?(visibility)
                    };
                    ulong? num = null;
                    FoundWorkshopEntryInfo foundWorkshopEntryInfo;
                    if (AWorkshopEntry.TryReadingManifest(contentFolderPath + Path.DirectorySeparatorChar.ToString() + "workshop.json", out foundWorkshopEntryInfo))
                    {
                        num = new ulong?(foundWorkshopEntryInfo.workshopEntryId);
                    }
                    if (num != null && finder.HasItemOfId(num.Value))
                    {
                        this._publishedFileID = new PublishedFileId_t(num.Value);
                        this.PreventUpdatingCertainThings();
                        this.UpdateItem();
                        return;
                    }
                    this.CreateItem();
                }
References Steamworks.CallResult< T >.Create(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.CreateItemResult(), System.IO.Path.DirectorySeparatorChar, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.GetVisibility(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PreventUpdatingCertainThings(), Terraria.Social.Base.AWorkshopEntry.TryReadingManifest(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem(), Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItemResult(), and Terraria.Social.Base.FoundWorkshopEntryInfo.workshopEntryId.
Referenced by Terraria.Social.Steam.WorkshopSocialModule.PublishResourcePack(), and Terraria.Social.Steam.WorkshopSocialModule.PublishWorld().