Terraria Decompiled: Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.TryWritingManifestToFolder
TryWritingManifestToFolder()
bool Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.TryWritingManifestToFolder (string folderPath, string manifestText) inline private
Definition at line 442 of file WorkshopHelper.cs.
                {
                    string text = folderPath + Path.DirectorySeparatorChar.ToString() + "workshop.json";
                    bool flag = true;
                    try
                    {
                        File.WriteAllText(text, manifestText);
                    }
                    catch (Exception ex)
                    {
                        this._issueReporter.ReportManifestCreationProblem("Workshop.ReportIssue_CouldNotCreateResourcePackManifestFile", ex);
                        flag = false;
                    }
                    return flag;
                }
References Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance._issueReporter, System.IO.Path.DirectorySeparatorChar, Terraria.Social.Base.WorkshopIssueReporter.ReportManifestCreationProblem(), System.text, and System.IO.File.WriteAllText().
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.UpdateItem().