Terraria Decompiled: System.Convert.FromBase64CharArray
FromBase64CharArray()
static unsafe byte[] System.Convert.FromBase64CharArray (char[] inArray, int offset, int length) inline static
Definition at line 3336 of file Convert.cs.
        {
            if (inArray == null)
            {
                throw new ArgumentNullException("inArray");
            }
            if (length < 0)
            {
                throw new ArgumentOutOfRangeException("length", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Value must be positive.");
            }
            if (offset > inArray.Length - length)
            {
                throw new ArgumentOutOfRangeException("offset", "Offset and length must refer to a position in the string.");
            }
            if (inArray.Length == 0)
            {
                return Array.Empty<byte>();
            }
            fixed (char* ptr = &inArray[0])
            {
                return Convert.FromBase64CharPtr(ptr + offset, length);
            }
        }
References System.Convert.FromBase64CharPtr(), System.length, and System.offset.
Referenced by Newtonsoft.Json.JsonTextReader.ParseReadString(), System.Security.Cryptography.FromBase64Transform.TransformBlock(), and System.Security.Cryptography.FromBase64Transform.TransformFinalBlock().