Terraria Decompiled: System.Convert.ToInt64
ToInt64() [10/19]
static long System.Convert.ToInt64 (object value) inline static
Definition at line 1757 of file Convert.cs.
        {
            if (value != null)
            {
                return ((IConvertible)value).ToInt64(null);
            }
            return 0L;
        }
References System.L, and System.value.
Referenced by Newtonsoft.Json.Linq.JValue.Compare(), Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), System.DateTime.DateTime(), System.Security.Cryptography.CryptoConfig.EncodeOID(), Terraria.Lang.FillNameCacheArray< IdClass, IdType >(), Newtonsoft.Json.Linq.JValue.Operation(), Newtonsoft.Json.Linq.JToken.operator long(), Newtonsoft.Json.Linq.JToken.operator long?(), Mono.DataConverter.PackOne(), Newtonsoft.Json.JsonTextReader.ParseReadNumber(), System.Security.PermissionSet.ProcessAttribute(), Microsoft.Win32.Win32RegistryApi.SetValue(), Microsoft.Win32.KeyHandler.SetValue(), System.Convert.ToInt64(), System.Boolean.ToInt64(), System.Byte.ToInt64(), System.Char.ToInt64(), System.Decimal.ToInt64(), System.Double.ToInt64(), System.Enum.ToInt64(), System.Int16.ToInt64(), System.Int32.ToInt64(), System.SByte.ToInt64(), System.Single.ToInt64(), System.String.ToInt64(), System.UInt16.ToInt64(), System.UInt32.ToInt64(), System.UInt64.ToInt64(), System.Enum.ToUInt64(), FullSerializer.Internal.fsEnumConverter.TrySerialize(), Newtonsoft.Json.JsonValidatingReader.ValidateInteger(), System.Runtime.Serialization.Formatter.WriteMember(), Newtonsoft.Json.Linq.JValue.WriteTo(), Newtonsoft.Json.JsonWriter.WriteToken(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue().