Terraria Decompiled: System.Convert.ChangeType
ChangeType() [2/4]
static object System.Convert.ChangeType (object value, Type conversionType, IFormatProvider provider) inline static
Definition at line 326 of file Convert.cs.
        {
            if (conversionType == null)
            {
                throw new ArgumentNullException("conversionType");
            }
            if (value == null)
            {
                if (conversionType.IsValueType)
                {
                    throw new InvalidCastException("Null object cannot be converted to a value type.");
                }
                return null;
            }
            else
            {
                IConvertible convertible = value as IConvertible;
                if (convertible == null)
                {
                    if (value.GetType() == conversionType)
                    {
                        return value;
                    }
                    throw new InvalidCastException("Object must implement IConvertible.");
                }
                else
                {
                    if (conversionType == Convert.ConvertTypes[3])
                    {
                        return convertible.ToBoolean(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[4])
                    {
                        return convertible.ToChar(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[5])
                    {
                        return convertible.ToSByte(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[6])
                    {
                        return convertible.ToByte(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[7])
                    {
                        return convertible.ToInt16(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[8])
                    {
                        return convertible.ToUInt16(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[9])
                    {
                        return convertible.ToInt32(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[10])
                    {
                        return convertible.ToUInt32(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[11])
                    {
                        return convertible.ToInt64(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[12])
                    {
                        return convertible.ToUInt64(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[13])
                    {
                        return convertible.ToSingle(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[14])
                    {
                        return convertible.ToDouble(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[15])
                    {
                        return convertible.ToDecimal(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[16])
                    {
                        return convertible.ToDateTime(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[18])
                    {
                        return convertible.ToString(provider);
                    }
                    if (conversionType == Convert.ConvertTypes[1])
                    {
                        return value;
                    }
                    return convertible.ToType(conversionType, provider);
                }
            }
        }
References System.Convert.ConvertTypes, System.Type.IsValueType, System.IConvertible.ToBoolean(), System.IConvertible.ToByte(), System.IConvertible.ToChar(), System.IConvertible.ToDateTime(), System.IConvertible.ToDecimal(), System.IConvertible.ToDouble(), System.IConvertible.ToInt16(), System.IConvertible.ToInt32(), System.IConvertible.ToInt64(), System.IConvertible.ToSByte(), System.IConvertible.ToSingle(), System.IConvertible.ToString(), System.IConvertible.ToType(), System.IConvertible.ToUInt16(), System.IConvertible.ToUInt32(), System.IConvertible.ToUInt64(), and System.value.