Terraria Decompiled: System.Convert.DefaultToType
DefaultToType()
static object System.Convert.DefaultToType (IConvertible value, Type targetType, IFormatProvider provider) inline static package
Definition at line 230 of file Convert.cs.
        {
            if (targetType == null)
            {
                throw new ArgumentNullException("targetType");
            }
            if (value.GetType() == targetType)
            {
                return value;
            }
            if (targetType == Convert.ConvertTypes[3])
            {
                return value.ToBoolean(provider);
            }
            if (targetType == Convert.ConvertTypes[4])
            {
                return value.ToChar(provider);
            }
            if (targetType == Convert.ConvertTypes[5])
            {
                return value.ToSByte(provider);
            }
            if (targetType == Convert.ConvertTypes[6])
            {
                return value.ToByte(provider);
            }
            if (targetType == Convert.ConvertTypes[7])
            {
                return value.ToInt16(provider);
            }
            if (targetType == Convert.ConvertTypes[8])
            {
                return value.ToUInt16(provider);
            }
            if (targetType == Convert.ConvertTypes[9])
            {
                return value.ToInt32(provider);
            }
            if (targetType == Convert.ConvertTypes[10])
            {
                return value.ToUInt32(provider);
            }
            if (targetType == Convert.ConvertTypes[11])
            {
                return value.ToInt64(provider);
            }
            if (targetType == Convert.ConvertTypes[12])
            {
                return value.ToUInt64(provider);
            }
            if (targetType == Convert.ConvertTypes[13])
            {
                return value.ToSingle(provider);
            }
            if (targetType == Convert.ConvertTypes[14])
            {
                return value.ToDouble(provider);
            }
            if (targetType == Convert.ConvertTypes[15])
            {
                return value.ToDecimal(provider);
            }
            if (targetType == Convert.ConvertTypes[16])
            {
                return value.ToDateTime(provider);
            }
            if (targetType == Convert.ConvertTypes[18])
            {
                return value.ToString(provider);
            }
            if (targetType == Convert.ConvertTypes[1])
            {
                return value;
            }
            if (targetType == Convert.EnumType)
            {
                return (Enum)value;
            }
            if (targetType == Convert.ConvertTypes[2])
            {
                throw new InvalidCastException("Object cannot be cast to DBNull.");
            }
            if (targetType == Convert.ConvertTypes[0])
            {
                throw new InvalidCastException("Object cannot be cast to Empty.");
            }
            throw new InvalidCastException(string.Format("Invalid cast from '{0}' to '{1}'.", value.GetType().FullName, targetType.FullName));
        }
References System.Convert.ConvertTypes, System.Convert.EnumType, System.Format, System.Type.FullName, and System.value.
Referenced by System.Boolean.ToType(), System.Byte.ToType(), System.Char.ToType(), System.DateTime.ToType(), System.DBNull.ToType(), System.Decimal.ToType(), System.Double.ToType(), System.Enum.ToType(), System.Int16.ToType(), System.Int32.ToType(), System.Int64.ToType(), System.SByte.ToType(), System.Single.ToType(), System.String.ToType(), System.UInt16.ToType(), System.UInt32.ToType(), and System.UInt64.ToType().