Terraria Decompiled: System.Convert.ChangeType
ChangeType() [4/4]
static object System.Convert.ChangeType (object value, TypeCode typeCode, IFormatProvider provider) inline static
Definition at line 176 of file Convert.cs.
        {
            if (value == null && (typeCode == TypeCode.Empty || typeCode == TypeCode.String || typeCode == TypeCode.Object))
            {
                return null;
            }
            IConvertible convertible = value as IConvertible;
            if (convertible == null)
            {
                throw new InvalidCastException("Object must implement IConvertible.");
            }
            switch (typeCode)
            {
            case TypeCode.Empty:
                throw new InvalidCastException("Object cannot be cast to Empty.");
            case TypeCode.Object:
                return value;
            case TypeCode.DBNull:
                throw new InvalidCastException("Object cannot be cast to DBNull.");
            case TypeCode.Boolean:
                return convertible.ToBoolean(provider);
            case TypeCode.Char:
                return convertible.ToChar(provider);
            case TypeCode.SByte:
                return convertible.ToSByte(provider);
            case TypeCode.Byte:
                return convertible.ToByte(provider);
            case TypeCode.Int16:
                return convertible.ToInt16(provider);
            case TypeCode.UInt16:
                return convertible.ToUInt16(provider);
            case TypeCode.Int32:
                return convertible.ToInt32(provider);
            case TypeCode.UInt32:
                return convertible.ToUInt32(provider);
            case TypeCode.Int64:
                return convertible.ToInt64(provider);
            case TypeCode.UInt64:
                return convertible.ToUInt64(provider);
            case TypeCode.Single:
                return convertible.ToSingle(provider);
            case TypeCode.Double:
                return convertible.ToDouble(provider);
            case TypeCode.Decimal:
                return convertible.ToDecimal(provider);
            case TypeCode.DateTime:
                return convertible.ToDateTime(provider);
            case TypeCode.String:
                return convertible.ToString(provider);
            }
            throw new ArgumentException("Unknown TypeCode value.");
        }
References System.IConvertible.ToBoolean(), System.IConvertible.ToByte(), System.IConvertible.ToChar(), System.IConvertible.ToDateTime(), System.IConvertible.ToDecimal(), System.IConvertible.ToDouble(), System.IConvertible.ToInt16(), System.IConvertible.ToInt32(), System.IConvertible.ToInt64(), System.IConvertible.ToSByte(), System.IConvertible.ToSingle(), System.IConvertible.ToString(), System.IConvertible.ToUInt16(), System.IConvertible.ToUInt32(), System.IConvertible.ToUInt64(), and System.value.