Terraria Decompiled: System.Convert.ToDouble
ToDouble() [10/18]
static double System.Convert.ToDouble (object value) inline static
Definition at line 2179 of file Convert.cs.
        {
            if (value != null)
            {
                return ((IConvertible)value).ToDouble(null);
            }
            return 0.0;
        }
References System.value.
Referenced by Newtonsoft.Json.Linq.JValue.CompareBigInteger(), Newtonsoft.Json.Linq.JValue.CompareFloat(), Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), Newtonsoft.Json.Linq.JValue.Operation(), Newtonsoft.Json.Linq.JToken.operator double(), Newtonsoft.Json.Linq.JToken.operator double?(), Mono.DataConverter.PackOne(), Newtonsoft.Json.JsonTextReader.ParseReadNumber(), System.Security.PermissionSet.ProcessAttribute(), Newtonsoft.Json.JsonReader.ReadAsDouble(), System.Boolean.ToDouble(), System.Byte.ToDouble(), System.Decimal.ToDouble(), System.Enum.ToDouble(), System.Int16.ToDouble(), System.Int32.ToDouble(), System.Int64.ToDouble(), System.SByte.ToDouble(), System.Single.ToDouble(), System.String.ToDouble(), System.UInt16.ToDouble(), System.UInt32.ToDouble(), System.UInt64.ToDouble(), Newtonsoft.Json.JsonValidatingReader.ValidateFloat(), Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals(), System.Runtime.Serialization.Formatter.WriteMember(), Newtonsoft.Json.Linq.JValue.WriteTo(), Newtonsoft.Json.JsonWriter.WriteToken(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue().