Terraria Decompiled: System.Convert.TryDecodeFromUtf16
TryDecodeFromUtf16()
static unsafe bool System.Convert.TryDecodeFromUtf16 (ReadOnlySpan< char > utf16, Span< byte > bytes, out int consumed, out int written) inline static private
Definition at line 12 of file Convert.cs.
        {
            ref char reference = ref MemoryMarshal.GetReference<char>(utf16);
            ref byte reference2 = ref MemoryMarshal.GetReference<byte>(bytes);
            int num = utf16.Length & -4;
            int length = bytes.Length;
            int i = 0;
            int num2 = 0;
            if (utf16.Length != 0)
            {
                ref sbyte ptr = ref Convert.s_decodingMap[0];
                int num3;
                if (length >= (num >> 2) * 3)
                {
                    num3 = num - 4;
                }
                else
                {
                    num3 = length / 3 * 4;
                }
                while (i < num3)
                {
                    int num4 = Convert.Decode(Unsafe.Add<char>(ref reference, i), ref ptr);
                    if (num4 < 0)
                    {
                        IL_0201:
                        consumed = i;
                        written = num2;
                        return false;
                    }
                    Convert.WriteThreeLowOrderBytes(Unsafe.Add<byte>(ref reference2, num2), num4);
                    num2 += 3;
                    i += 4;
                }
                if (num3 != num - 4 || i == num)
                {
                    goto IL_0201;
                }
                int num5 = (int)(*Unsafe.Add<char>(ref reference, num - 4));
                int num6 = (int)(*Unsafe.Add<char>(ref reference, num - 3));
                int num7 = (int)(*Unsafe.Add<char>(ref reference, num - 2));
                int num8 = (int)(*Unsafe.Add<char>(ref reference, num - 1));
                if (((long)(num5 | num6 | num7 | num8) & (long)((ulong)(-256))) != 0L)
                {
                    goto IL_0201;
                }
                num5 = (int)(*Unsafe.Add<sbyte>(ref ptr, num5));
                num6 = (int)(*Unsafe.Add<sbyte>(ref ptr, num6));
                num5 <<= 18;
                num6 <<= 12;
                num5 |= num6;
                if (num8 != 61)
                {
                    num7 = (int)(*Unsafe.Add<sbyte>(ref ptr, num7));
                    num8 = (int)(*Unsafe.Add<sbyte>(ref ptr, num8));
                    num7 <<= 6;
                    num5 |= num8;
                    num5 |= num7;
                    if (num5 < 0 || num2 > length - 3)
                    {
                        goto IL_0201;
                    }
                    Convert.WriteThreeLowOrderBytes(Unsafe.Add<byte>(ref reference2, num2), num5);
                    num2 += 3;
                }
                else if (num7 != 61)
                {
                    num7 = (int)(*Unsafe.Add<sbyte>(ref ptr, num7));
                    num7 <<= 6;
                    num5 |= num7;
                    if (num5 < 0 || num2 > length - 2)
                    {
                        goto IL_0201;
                    }
                    *Unsafe.Add<byte>(ref reference2, num2) = (byte)(num5 >> 16);
                    *Unsafe.Add<byte>(ref reference2, num2 + 1) = (byte)(num5 >> 8);
                    num2 += 2;
                }
                else
                {
                    if (num5 < 0 || num2 > length - 1)
                    {
                        goto IL_0201;
                    }
                    *Unsafe.Add<byte>(ref reference2, num2) = (byte)(num5 >> 16);
                    num2++;
                }
                i += 4;
                if (num != utf16.Length)
                {
                    goto IL_0201;
                }
            }
            consumed = i;
            written = num2;
            return true;
        }
References System.Convert.Decode(), int, System.L, System.length, System.ReadOnlySpan< T >.Length, System.Span< T >.Length, System.Convert.s_decodingMap, and System.Convert.WriteThreeLowOrderBytes().
Referenced by System.Convert.TryFromBase64Chars().