Terraria Decompiled: System.Text.StringBuilder.ToString
ToString() [1/2]
unsafe override string System.Text.StringBuilder.ToString () inline
Definition at line 251 of file StringBuilder.cs.
        {
            if (this.Length == 0)
            {
                return string.Empty;
            }
            string text = string.FastAllocateString(this.Length);
            StringBuilder stringBuilder = this;
            fixed (string text2 = text)
            {
                char* ptr = text2;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                for (;;)
                {
                    if (stringBuilder.m_ChunkLength > 0)
                    {
                        char[] chunkChars = stringBuilder.m_ChunkChars;
                        int chunkOffset = stringBuilder.m_ChunkOffset;
                        int chunkLength = stringBuilder.m_ChunkLength;
                        if (chunkLength + chunkOffset > text.Length || chunkLength > chunkChars.Length)
{
                            break;
                        }
                        fixed (char* ptr2 = &chunkChars[0])
{
                            char* ptr3 = ptr2;
                            string.wstrcpy(ptr + chunkOffset, ptr3, chunkLength);
                        }
                    }
                    stringBuilder = stringBuilder.m_ChunkPrevious;
                    if (stringBuilder == null)
                    {
                        return text;
                    }
                }
                throw new ArgumentOutOfRangeException("chunkLength", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
        }
References System.Text.StringBuilder.Length, System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_ChunkLength, System.Text.StringBuilder.m_ChunkOffset, System.Text.StringBuilder.m_ChunkPrevious, and System.text.
Referenced by System.Globalization.DateTimeFormatInfoScanner.AddDateWords(), CsvHelper.ExceptionHelper.AddExceptionDataMessage(), System.Text.StringBuilder.AppendCore(), System.Text.StringBuilder.AppendFormatHelper(), System.Text.StringBuilder.AppendJoinCore< T >(), ReLogic.Text.WrappedTextBuilder.Build(), Newtonsoft.Json.JsonPosition.BuildPath(), System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup(), System.Text.Normalization.Compose(), FullSerializer.fsJsonPrinter.CompressedJson(), System.RuntimeMethodHandle.ConstructInstantiation(), System.Globalization.Bootstring.Decode(), System.Text.Normalization.Decompose(), Terraria.Testing.PacketHistory.Dump(), System.Globalization.Bootstring.Encode(), Terraria.TimeLogger.EndDrawFrame(), System.Security.SecurityElement.Escape(), System.TypeSpec.EscapeDisplayName(), FullSerializer.fsJsonPrinter.EscapeString(), Mono.Security.Uri.EscapeString(), System.ParameterizedStrings.EvaluateInternal(), Microsoft.Win32.ExpandString.Expand(), System.NumberFormatter.CustomInfo.Format(), System.Reflection.Emit.TypeBuilderInstantiation.format_name(), System.Reflection.Emit.ArrayType.FormatName(), System.Reflection.MethodBase.FormatNameAndSig(), System.Reflection.RuntimeMethodInfo.FormatNameAndSig(), System.Reflection.RuntimePropertyInfo.FormatNameAndSig(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForArray(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForNonArrayTypes(), System.TypeSpec.GetDisplayFullName(), CsvHelper.ExceptionHelper.GetErrorMessage(), System.IO.Path.GetFullPathName(), Mono.Security.Uri.GetLeftPart(), System.Reflection.Assembly.GetManifestResourceStream(), System.Text.StringBuilder.GetObjectData(), System.IO.Path.GetRandomFileName(), Terraria.GameContent.NPCDamageTracker.GetReport(), System.Resources.ResourceManager.GetResourceFileName(), System.Security.AccessControl.GenericAce.GetSddlAceFlags(), System.Security.AccessControl.GenericSecurityDescriptor.GetSddlForm(), System.Security.AccessControl.RawAcl.GetSddlForm(), Newtonsoft.Json.Bson.BsonReader.GetString(), System.Text.StringBuilderCache.GetStringAndRelease(), Mono.Xml.SmallXmlParser.HandleBufferedContent(), System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing(), System.Globalization.TimeSpanFormat.FormatLiterals.Init(), Steamworks.SteamAPI.InitEx(), Steamworks.GameServer.InitEx(), System.Enum.InternalFlagsFormat(), System.IO.File.InternalReadAllTextAsync(), System.Security.Util.Tokenizer.StringMaker.MakeString(), System.Runtime.Versioning.VersioningHelper.MakeVersionSafeName(), System.TypeSpec.ModifierString(), System.IO.PathInternal.NormalizeDirectorySeparators(), FullSerializer.fsJsonPrinter.PrettyJson(), System.IO.StreamReader.ReadLine(), System.IO.TextReader.ReadLine(), System.WindowsConsoleDriver.ReadLine(), System.IO.StreamReader.ReadLineAsyncInternal(), Newtonsoft.Json.Linq.JsonPath.JPath.ReadQuotedString(), Newtonsoft.Json.Bson.BsonReader.ReadString(), System.IO.StreamReader.ReadToEnd(), System.IO.TextReader.ReadToEnd(), System.IO.TextReader.ReadToEndAsync(), System.IO.StreamReader.ReadToEndAsyncInternal(), Mono.Xml.SmallXmlParser.ReadUntil(), ReLogic.Text.StringReaderWrapExtension.ReadUntilBreakable(), System.TermInfoDriver.ReadUntilConditionInternal(), Newtonsoft.Json.Utilities.ReflectionUtils.RemoveAssemblyDetails(), ReLogic.OS.Base.Clipboard.SanitizeClipboardText(), Terraria.UI.FancyErrorPrinter.ShowDirectoryCreationFailError(), Terraria.UI.FancyErrorPrinter.ShowFailedToLoadAssetError(), Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError(), System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive(), System.Security.Cryptography.X509Certificates.X509Helper.ToHexString(), Mono.Security.ASN1Convert.ToOid(), Newtonsoft.Json.Utilities.StringUtils.ToSnakeCase(), Microsoft.Xna.Framework.BoundingFrustum.ToString(), Microsoft.Xna.Framework.Color.ToString(), Microsoft.Xna.Framework.Vector3.ToString(), XPT.Core.Audio.MP3Sharp.Decoding.Header.ToString(), Mono.Security.ASN1.ToString(), System.AggregateException.ToString(), System.ArraySpec.ToString(), System.Buffers.Text.NumberBuffer.ToString(), System.Diagnostics.StackFrame.ToString(), System.Diagnostics.StackTrace.ToString(), System.IO.StringWriter.ToString(), System.PointerSpec.ToString(), System.Reflection.CustomAttributeData.ToString(), System.Reflection.Emit.MethodOnTypeBuilderInst.ToString(), System.Reflection.SignatureConstructedGenericType.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapHexBinary.ToString(), System.Security.Permissions.StrongNamePublicKeyBlob.ToString(), System.Security.Policy.Hash.ToString(), System.Security.Policy.StrongNameMembershipCondition.ToString(), System.Security.SecurityElement.ToString(), System.Security.SecurityException.ToString(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.ToString(), Terraria.Recipe.ToString(), Terraria.Utilities.Vertical64BitStrips.ToString(), System.Security.Cryptography.X509Certificates.X509Certificate.ToString(), System.Globalization.HebrewNumber.ToString(), System.Numerics.Vector< T >.ToString(), System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.ToString(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDuration.ToString(), System.Globalization.TextInfo.ToTitleCase(), Mono.Security.Cryptography.KeyPairPersistence.ToXml(), Mono.Security.Cryptography.RSAManaged.ToXmlString(), System.Security.Cryptography.DSA.ToXmlString(), System.Security.Cryptography.RSA.ToXmlString(), Newtonsoft.Json.Serialization.MemoryTraceWriter.Trace(), Terraria.Localization.VariableText.TryFormat(), FullSerializer.fsJsonParser.TryParseString(), Newtonsoft.Json.Linq.JsonPath.JPath.TryParseValue(), System.Security.SecurityElement.Unescape(), Mono.Security.Uri.Unescape(), System.TypeSpec.UnescapeInternalName(), and System.Globalization.CultureData.UnescapeNlsString().