Terraria Decompiled: System.Text.StringBuilder.AppendCore
AppendCore()
StringBuilder System.Text.StringBuilder.AppendCore (StringBuilder value, int startIndex, int count) inline private
Definition at line 657 of file StringBuilder.cs.
        {
            if (value == this)
            {
                return this.Append(value.ToString(startIndex, count));
            }
            if (this.Length + count > this.m_MaxCapacity)
            {
                throw new ArgumentOutOfRangeException("Capacity", "Capacity exceeds maximum capacity.");
            }
            while (count > 0)
            {
                int num = Math.Min(this.m_ChunkChars.Length - this.m_ChunkLength, count);
                if (num == 0)
                {
                    this.ExpandByABlock(count);
                    num = Math.Min(this.m_ChunkChars.Length - this.m_ChunkLength, count);
                }
                value.CopyTo(startIndex, new Span<char>(this.m_ChunkChars, this.m_ChunkLength, num), num);
                this.m_ChunkLength += num;
                startIndex += num;
                count -= num;
            }
            return this;
        }
References System.Text.StringBuilder.Append(), System.count, System.Text.StringBuilder.ExpandByABlock(), System.Text.StringBuilder.Length, System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_ChunkLength, System.Text.StringBuilder.m_MaxCapacity, System.Math.Min(), System.startIndex, System.Text.StringBuilder.ToString(), and System.value.
Referenced by System.Text.StringBuilder.Append(), and System.Text.StringBuilder.Append().