Terraria Decompiled: System.Text.StringBuilder.AppendJoinCore< T >
AppendJoinCore< T >() [2/2]
unsafe StringBuilder System.Text.StringBuilder.AppendJoinCore< T > (char * separator, int separatorLength, T[] values) inline private
Definition at line 1051 of file StringBuilder.cs.
        {
            if (values == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.values);
            }
            if (values.Length == 0)
            {
                return this;
            }
            if (values[0] != null)
            {
                this.Append(values[0].ToString());
            }
            for (int i = 1; i < values.Length; i++)
            {
                this.Append(separator, separatorLength);
                if (values[i] != null)
                {
                    this.Append(values[i].ToString());
                }
            }
            return this;
        }
References System.Text.StringBuilder.Append(), System.ThrowHelper.ThrowArgumentNullException(), System.Text.StringBuilder.ToString(), and System.values.