Terraria Decompiled: System.Convert.TryFromBase64Chars
TryFromBase64Chars()
static unsafe bool System.Convert.TryFromBase64Chars (ReadOnlySpan< char > chars, Span< byte > bytes, out int bytesWritten) inline static
Definition at line 3238 of file Convert.cs.
        {
            Span<char> span = new Span<char>(stackalloc byte[(UIntPtr)8], 4);
            bytesWritten = 0;
            while (chars.Length != 0)
            {
                int num;
                int num2;
                bool flag = Convert.TryDecodeFromUtf16(chars, bytes, out num, out num2);
                bytesWritten += num2;
                if (flag)
                {
                    return true;
                }
                chars = chars.Slice(num);
                bytes = bytes.Slice(num2);
                if (((char)(*chars[0])).IsSpace())
                {
                    int num3 = 1;
                    while (num3 != chars.Length && ((char)(*chars[num3])).IsSpace())
                    {
                        num3++;
                    }
                    chars = chars.Slice(num3);
                    if (num2 % 3 != 0 && chars.Length != 0)
                    {
                        bytesWritten = 0;
                        return false;
                    }
                }
                else
                {
                    int num4;
                    int num5;
                    Convert.CopyToTempBufferWithoutWhiteSpace(chars, span, out num4, out num5);
                    if ((num5 & 3) != 0)
                    {
                        bytesWritten = 0;
                        return false;
                    }
                    span = span.Slice(0, num5);
                    int num6;
                    int num7;
                    if (!Convert.TryDecodeFromUtf16(span, bytes, out num6, out num7))
                    {
                        bytesWritten = 0;
                        return false;
                    }
                    bytesWritten += num7;
                    chars = chars.Slice(num4);
                    bytes = bytes.Slice(num7);
                    if (num7 % 3 != 0)
                    {
                        for (int i = 0; i < chars.Length; i++)
{
                            if (!((char)(*chars[i])).IsSpace())
{
                                bytesWritten = 0;
                                return false;
                            }
                        }
                        return true;
                    }
                }
            }
            return true;
        }
References System.Convert.CopyToTempBufferWithoutWhiteSpace(), System.Convert.IsSpace(), System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), and System.Convert.TryDecodeFromUtf16().
Referenced by System.Convert.FromBase64CharPtr(), and System.Convert.TryFromBase64String().