Terraria Decompiled: System.Text.StringBuilder.StringBuilder
StringBuilder() [5/9]
unsafe System.Text.StringBuilder.StringBuilder (string value, int startIndex, int length, int capacity) inline
Definition at line 42 of file StringBuilder.cs.
        {
            if (capacity < 0)
            {
                throw new ArgumentOutOfRangeException("capacity", SR.Format("'{0}' must be greater than zero.", "capacity"));
            }
            if (length < 0)
            {
                throw new ArgumentOutOfRangeException("length", SR.Format("'{0}' must be non-negative.", "length"));
            }
            if (startIndex < 0)
            {
                throw new ArgumentOutOfRangeException("startIndex", "StartIndex cannot be less than zero.");
            }
            if (value == null)
            {
                value = string.Empty;
            }
            if (startIndex > value.Length - length)
            {
                throw new ArgumentOutOfRangeException("length", "Index and length must refer to a location within the string.");
            }
            this.m_MaxCapacity = int.MaxValue;
            if (capacity == 0)
            {
                capacity = 16;
            }
            capacity = Math.Max(capacity, length);
            this.m_ChunkChars = new char[capacity];
            this.m_ChunkLength = length;
            fixed (string text = value)
            {
                char* ptr = text;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                StringBuilder.ThreadSafeCopy(ptr + startIndex, this.m_ChunkChars, 0, length);
            }
        }
References System.capacity, SR.Format(), System.length, System.Text.StringBuilder.m_ChunkChars, System.Math.Max(), System.startIndex, System.text, System.Text.StringBuilder.ThreadSafeCopy(), and System.value.