Terraria Decompiled: System.Text.StringBuilder.Insert
Insert() [17/20]
unsafe StringBuilder System.Text.StringBuilder.Insert (int index, string value, int count) inline
Definition at line 754 of file StringBuilder.cs.
        {
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            int length = this.Length;
            if (index > length)
            {
                throw new ArgumentOutOfRangeException("index", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            if (string.IsNullOrEmpty(value) || count == 0)
            {
                return this;
            }
            long num = (long)value.Length * (long)count;
            if (num > (long)(this.MaxCapacity - this.Length))
            {
                throw new OutOfMemoryException();
            }
            StringBuilder stringBuilder;
            int num2;
            this.MakeRoom(index, (int)num, out stringBuilder, out num2, false);
            char* ptr = value;
            if (ptr != null)
            {
                ptr += RuntimeHelpers.OffsetToStringData / 2;
            }
            while (count > 0)
            {
                this.ReplaceInPlaceAtChunk(ref stringBuilder, ref num2, ptr, value.Length);
                count--;
            }
            return this;
        }
References System.count, System.length, System.Text.StringBuilder.Length, long, System.Text.StringBuilder.MakeRoom(), System.Text.StringBuilder.ReplaceInPlaceAtChunk(), and System.value.
Referenced by System.Globalization.Bootstring.Decode(), System.NumberFormatter.CustomInfo.Format(), System.NumberFormatter.FormatCustom(), System.Enum.InternalFlagsFormat(), and System.Globalization.HebrewNumber.ToString().