Terraria Decompiled: System.Text.StringBuilder.Replace
Replace() [4/4]
StringBuilder System.Text.StringBuilder.Replace (string oldValue, string newValue, int startIndex, int count) inline
Definition at line 1670 of file StringBuilder.cs.
        {
            int length = this.Length;
            if (startIndex > length)
            {
                throw new ArgumentOutOfRangeException("startIndex", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            if (count < 0 || startIndex > length - count)
            {
                throw new ArgumentOutOfRangeException("count", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            if (oldValue == null)
            {
                throw new ArgumentNullException("oldValue");
            }
            if (oldValue.Length == 0)
            {
                throw new ArgumentException("Empty name is not legal.", "oldValue");
            }
            newValue = newValue ?? string.Empty;
            int length2 = newValue.Length;
            int length3 = oldValue.Length;
            int[] array = null;
            int num = 0;
            StringBuilder stringBuilder = this.FindChunkForIndex(startIndex);
            int num2 = startIndex - stringBuilder.m_ChunkOffset;
            while (count > 0)
            {
                if (this.StartsWith(stringBuilder, num2, count, oldValue))
                {
                    if (array == null)
                    {
                        array = new int[5];
                    }
                    else if (num >= array.Length)
                    {
                        Array.Resize<int>(ref array, array.Length * 3 / 2 + 4);
                    }
                    array[num++] = num2;
                    num2 += oldValue.Length;
                    count -= oldValue.Length;
                }
                else
                {
                    num2++;
                    count--;
                }
                if (num2 >= stringBuilder.m_ChunkLength || count == 0)
                {
                    int num3 = num2 + stringBuilder.m_ChunkOffset;
                    this.ReplaceAllInChunk(array, num, stringBuilder, oldValue.Length, newValue);
                    num3 += (newValue.Length - oldValue.Length) * num;
                    num = 0;
                    stringBuilder = this.FindChunkForIndex(num3);
                    num2 = num3 - stringBuilder.m_ChunkOffset;
                }
            }
            return this;
        }
References System.array, System.count, System.Text.StringBuilder.FindChunkForIndex(), System.length, System.Text.StringBuilder.Length, System.Text.StringBuilder.m_ChunkLength, System.Text.StringBuilder.m_ChunkOffset, System.Text.StringBuilder.ReplaceAllInChunk(), System.startIndex, and System.Text.StringBuilder.StartsWith().