Terraria Decompiled: System.Convert.ConvertToBase64Array
ConvertToBase64Array()
static unsafe int System.Convert.ConvertToBase64Array (char * outChars, byte * inData, int offset, int length, bool insertLineBreaks) inline static private
Definition at line 3130 of file Convert.cs.
        {
            int num = length % 3;
            int num2 = offset + (length - num);
            int num3 = 0;
            int num4 = 0;
            fixed (char* ptr = &Convert.base64Table[0])
            {
                char* ptr2 = ptr;
                int i;
                for (i = offset; i < num2; i += 3)
                {
                    if (insertLineBreaks)
                    {
                        if (num4 == 76)
{
                            outChars[num3++] = '\r';
                            outChars[num3++] = '\n';
                            num4 = 0;
                        }
                        num4 += 4;
                    }
                    outChars[num3] = ptr2[(inData[i] & 252) >> 2];
                    outChars[num3 + 1] = ptr2[((int)(inData[i] & 3) << 4) | ((inData[i + 1] & 240) >> 4)];
                    outChars[num3 + 2] = ptr2[((int)(inData[i + 1] & 15) << 2) | ((inData[i + 2] & 192) >> 6)];
                    outChars[num3 + 3] = ptr2[inData[i + 2] & 63];
                    num3 += 4;
                }
                i = num2;
                if (insertLineBreaks && num != 0 && num4 == 76)
                {
                    outChars[num3++] = '\r';
                    outChars[num3++] = '\n';
                }
                if (num != 1)
                {
                    if (num == 2)
                    {
                        outChars[num3] = ptr2[(inData[i] & 252) >> 2];
                        outChars[num3 + 1] = ptr2[((int)(inData[i] & 3) << 4) | ((inData[i + 1] & 240) >> 4)];
                        outChars[num3 + 2] = ptr2[(inData[i + 1] & 15) << 2];
                        outChars[num3 + 3] = ptr2[64];
                        num3 += 4;
                    }
                }
                else
                {
                    outChars[num3] = ptr2[(inData[i] & 252) >> 2];
                    outChars[num3 + 1] = ptr2[(inData[i] & 3) << 4];
                    outChars[num3 + 2] = ptr2[64];
                    outChars[num3 + 3] = ptr2[64];
                    num3 += 4;
                }
            }
            return num3;
        }
References System.Convert.base64Table, int, System.length, and System.offset.
Referenced by System.Convert.ToBase64CharArray(), System.Convert.ToBase64String(), and System.Convert.TryToBase64Chars().