Terraria Decompiled: System.Text.StringBuilder.MakeRoom
MakeRoom()
unsafe void System.Text.StringBuilder.MakeRoom (int index, int count, out StringBuilder chunk, out int indexInChunk, bool doNotMoveFollowingChars) inline private
Definition at line 2047 of file StringBuilder.cs.
        {
            if (count + this.Length > this.m_MaxCapacity || count + this.Length < count)
            {
                throw new ArgumentOutOfRangeException("requiredLength", "capacity was less than the current size.");
            }
            chunk = this;
            while (chunk.m_ChunkOffset > index)
            {
                chunk.m_ChunkOffset += count;
                chunk = chunk.m_ChunkPrevious;
            }
            indexInChunk = index - chunk.m_ChunkOffset;
            if (!doNotMoveFollowingChars && chunk.m_ChunkLength <= 32 && chunk.m_ChunkChars.Length - chunk.m_ChunkLength >= count)
            {
                int i = chunk.m_ChunkLength;
                while (i > indexInChunk)
                {
                    i--;
                    chunk.m_ChunkChars[i + count] = chunk.m_ChunkChars[i];
                }
                chunk.m_ChunkLength += count;
                return;
            }
            StringBuilder stringBuilder = new StringBuilder(Math.Max(count, 16), chunk.m_MaxCapacity, chunk.m_ChunkPrevious);
            stringBuilder.m_ChunkLength = count;
            int num = Math.Min(count, indexInChunk);
            if (num > 0)
            {
                fixed (char* ptr = &chunk.m_ChunkChars[0])
                {
                    char* ptr2 = ptr;
                    StringBuilder.ThreadSafeCopy(ptr2, stringBuilder.m_ChunkChars, 0, num);
                    int num2 = indexInChunk - num;
                    if (num2 >= 0)
                    {
                        StringBuilder.ThreadSafeCopy(ptr2 + num, chunk.m_ChunkChars, 0, num2);
                        indexInChunk = num2;
                    }
                }
            }
            chunk.m_ChunkPrevious = stringBuilder;
            chunk.m_ChunkOffset += count;
            if (num < count)
            {
                chunk = stringBuilder;
                indexInChunk = num;
            }
        }
References System.count, System.index, System.Text.StringBuilder.Length, System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_MaxCapacity, System.Math.Max(), System.Math.Min(), System.Text.StringBuilder.StringBuilder(), and System.Text.StringBuilder.ThreadSafeCopy().
Referenced by System.Text.StringBuilder.Insert(), System.Text.StringBuilder.Insert(), and System.Text.StringBuilder.ReplaceAllInChunk().