Terraria Decompiled: System.Convert.ToBoolean
ToBoolean() [10/18]
static bool System.Convert.ToBoolean (object value) inline static
Definition at line 486 of file Convert.cs.
        {
            return value != null && ((IConvertible)value).ToBoolean(null);
        }
References System.value.
Referenced by Newtonsoft.Json.Linq.JValue.Compare(), Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), Newtonsoft.Json.Linq.JToken.operator bool(), Newtonsoft.Json.Linq.JToken.operator bool?(), System.Security.PermissionSet.ProcessAttribute(), Newtonsoft.Json.JsonReader.ReadAsBoolean(), Newtonsoft.Json.JsonTextReader.ReadAsBoolean(), Newtonsoft.Json.Bson.BsonReader.ReadType(), System.Byte.ToBoolean(), System.Decimal.ToBoolean(), System.Double.ToBoolean(), System.Enum.ToBoolean(), System.Int16.ToBoolean(), System.Int32.ToBoolean(), System.Int64.ToBoolean(), System.SByte.ToBoolean(), System.Single.ToBoolean(), System.String.ToBoolean(), System.UInt16.ToBoolean(), System.UInt32.ToBoolean(), System.UInt64.ToBoolean(), System.Runtime.Serialization.Formatter.WriteMember(), Newtonsoft.Json.Linq.JValue.WriteTo(), Newtonsoft.Json.JsonWriter.WriteToken(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue().