Terraria Decompiled: System.Text.StringBuilder.ReplaceInPlaceAtChunk
ReplaceInPlaceAtChunk()
unsafe void System.Text.StringBuilder.ReplaceInPlaceAtChunk (ref StringBuilder chunk, ref int indexInChunk, char * value, int count) inline private
Definition at line 1908 of file StringBuilder.cs.
        {
            if (count != 0)
            {
                for (;;)
                {
                    int num = Math.Min(chunk.m_ChunkLength - indexInChunk, count);
                    StringBuilder.ThreadSafeCopy(value, chunk.m_ChunkChars, indexInChunk, num);
                    indexInChunk += num;
                    if (indexInChunk >= chunk.m_ChunkLength)
                    {
                        chunk = this.Next(chunk);
                        indexInChunk = 0;
                    }
                    count -= num;
                    if (count == 0)
                    {
                        break;
                    }
                    value += num;
                }
            }
        }
References System.count, System.Math.Min(), System.Text.StringBuilder.Next(), System.Text.StringBuilder.ThreadSafeCopy(), and System.value.
Referenced by System.Text.StringBuilder.Insert(), System.Text.StringBuilder.Insert(), and System.Text.StringBuilder.ReplaceAllInChunk().