Terraria Decompiled: System.Text.StringBuilder.AppendFormatHelper
AppendFormatHelper()
StringBuilder System.Text.StringBuilder.AppendFormatHelper (IFormatProvider provider, string format, ParamsArray args) inline package
Definition at line 1328 of file StringBuilder.cs.
        {
            if (format == null)
            {
                throw new ArgumentNullException("format");
            }
            int num = 0;
            int length = format.Length;
            char c = '\0';
            StringBuilder stringBuilder = null;
            ICustomFormatter customFormatter = null;
            if (provider != null)
            {
                customFormatter = (ICustomFormatter)provider.GetFormat(typeof(ICustomFormatter));
            }
            for (;;)
            {
                if (num < length)
                {
                    c = format[num];
                    num++;
                    if (c == '}')
                    {
                        if (num < length && format[num] == '}')
{
                            num++;
                        }
                        else
{
                            StringBuilder.FormatError();
                        }
                    }
                    if (c == '{')
                    {
                        if (num >= length || format[num] != '{')
{
                            num--;
                            goto IL_0091;
                        }
                        num++;
                    }
                    this.Append(c);
                    continue;
                }
                IL_0091:
                if (num == length)
                {
                    return this;
                }
                num++;
                if (num == length || (c = format[num]) < '0' || c > '9')
                {
                    StringBuilder.FormatError();
                }
                int num2 = 0;
                do
                {
                    num2 = num2 * 10 + (int)c - 48;
                    num++;
                    if (num == length)
                    {
                        StringBuilder.FormatError();
                    }
                    c = format[num];
                }
                while (c >= '0' && c <= '9' && num2 < 1000000);
                if (num2 >= args.Length)
                {
                    break;
                }
                while (num < length && (c = format[num]) == ' ')
                {
                    num++;
                }
                bool flag = false;
                int num3 = 0;
                if (c == ',')
                {
                    num++;
                    while (num < length && format[num] == ' ')
                    {
                        num++;
                    }
                    if (num == length)
                    {
                        StringBuilder.FormatError();
                    }
                    c = format[num];
                    if (c == '-')
                    {
                        flag = true;
                        num++;
                        if (num == length)
{
                            StringBuilder.FormatError();
                        }
                        c = format[num];
                    }
                    if (c < '0' || c > '9')
                    {
                        StringBuilder.FormatError();
                    }
                    do
                    {
                        num3 = num3 * 10 + (int)c - 48;
                        num++;
                        if (num == length)
{
                            StringBuilder.FormatError();
                        }
                        c = format[num];
                        if (c < '0' || c > '9')
{
                            break;
                        }
                    }
                    while (num3 < 1000000);
                }
                while (num < length && (c = format[num]) == ' ')
                {
                    num++;
                }
                object obj = args[num2];
                string text = null;
                ReadOnlySpan<char> readOnlySpan = default(ReadOnlySpan<char>);
                if (c == ':')
                {
                    num++;
                    int num4 = num;
                    for (;;)
                    {
                        if (num == length)
{
                            StringBuilder.FormatError();
                        }
                        c = format[num];
                        num++;
                        if (c == '}' || c == '{')
{
                            if (c == '{')
{
                                if (num < length && format[num] == '{')
{
                                    num++;
                                }
                                else
{
                                    StringBuilder.FormatError();
                                }
                            }
                            else
{
                                if (num >= length || format[num] != '}')
{
                                    break;
                                }
                                num++;
                            }
                            if (stringBuilder == null)
{
                                stringBuilder = new StringBuilder();
                            }
                            stringBuilder.Append(format, num4, num - num4 - 1);
                            num4 = num;
                        }
                    }
                    num--;
                    if (stringBuilder == null || stringBuilder.Length == 0)
                    {
                        if (num4 != num)
{
                            readOnlySpan = format.AsSpan(num4, num - num4);
                        }
                    }
                    else
                    {
                        stringBuilder.Append(format, num4, num - num4);
                        readOnlySpan = (text = stringBuilder.ToString());
                        stringBuilder.Clear();
                    }
                }
                if (c != '}')
                {
                    StringBuilder.FormatError();
                }
                num++;
                string text2 = null;
                if (customFormatter != null)
                {
                    if (readOnlySpan.Length != 0 && text == null)
                    {
                        text = new string(readOnlySpan);
                    }
                    text2 = customFormatter.Format(text, obj, provider);
                }
                if (text2 == null)
                {
                    ISpanFormattable spanFormattable = obj as ISpanFormattable;
                    int num5;
                    if (spanFormattable != null && (flag || num3 == 0) && spanFormattable.TryFormat(this.RemainingCurrentChunk, out num5, readOnlySpan, provider))
                    {
                        this.m_ChunkLength += num5;
                        int num6 = num3 - num5;
                        if (flag && num6 > 0)
{
                            this.Append(' ', num6);
                            continue;
                        }
                        continue;
                    }
                    else
                    {
                        IFormattable formattable = obj as IFormattable;
                        if (formattable != null)
{
                            if (readOnlySpan.Length != 0 && text == null)
{
                                text = new string(readOnlySpan);
                            }
                            text2 = formattable.ToString(text, provider);
                        }
                        else if (obj != null)
{
                            text2 = obj.ToString();
                        }
                    }
                }
                if (text2 == null)
                {
                    text2 = string.Empty;
                }
                int num7 = num3 - text2.Length;
                if (!flag && num7 > 0)
                {
                    this.Append(' ', num7);
                }
                this.Append(text2);
                if (flag && num7 > 0)
                {
                    this.Append(' ', num7);
                }
            }
            throw new FormatException("Index (zero based) must be greater than or equal to zero and less than the size of the argument list.");
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.Clear(), System.format, System.ICustomFormatter.Format(), System.Text.StringBuilder.FormatError(), System.IFormatProvider.GetFormat(), int, System.length, System.ParamsArray.Length, System.ReadOnlySpan< T >.Length, System.Text.StringBuilder.Length, System.obj, System.Text.StringBuilder.StringBuilder(), System.text, System.Text.StringBuilder.ToString(), System.IFormattable.ToString(), and System.ISpanFormattable.TryFormat().
Referenced by System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), System.Text.StringBuilder.AppendFormat(), and System.String.FormatHelper().