Terraria Decompiled: System.Text.StringBuilder.AppendJoinCore< T >
AppendJoinCore< T >() [1/2]
unsafe StringBuilder System.Text.StringBuilder.AppendJoinCore< T > (char * separator, int separatorLength, IEnumerable< T > values) inline private
Definition at line 1020 of file StringBuilder.cs.
        {
            if (values == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.values);
            }
            using (IEnumerator<T> enumerator = values.GetEnumerator())
            {
                if (!enumerator.MoveNext())
                {
                    return this;
                }
                T t = enumerator.Current;
                if (t != null)
                {
                    this.Append(t.ToString());
                }
                while (enumerator.MoveNext())
                {
                    this.Append(separator, separatorLength);
                    t = enumerator.Current;
                    if (t != null)
                    {
                        this.Append(t.ToString());
                    }
                }
            }
            return this;
        }
References System.Text.StringBuilder.Append(), System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.IEnumerator.MoveNext(), System.ThrowHelper.ThrowArgumentNullException(), and System.values.
Referenced by System.Text.StringBuilder.AppendJoin< T >(), and System.Text.StringBuilder.AppendJoin< T >().