Terraria Decompiled: System.Text.StringBuilder.ReplaceAllInChunk
ReplaceAllInChunk()
unsafe void System.Text.StringBuilder.ReplaceAllInChunk (int[] replacements, int replacementsCount, StringBuilder sourceChunk, int removeCount, string value) inline private
Definition at line 1828 of file StringBuilder.cs.
        {
            if (replacementsCount <= 0)
            {
                return;
            }
            fixed (string text = value)
            {
                char* ptr = text;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                int num = (value.Length - removeCount) * replacementsCount;
                StringBuilder stringBuilder = sourceChunk;
                int num2 = replacements[0];
                if (num > 0)
                {
                    this.MakeRoom(stringBuilder.m_ChunkOffset + num2, num, out stringBuilder, out num2, true);
                }
                int num3 = 0;
                for (;;)
                {
                    this.ReplaceInPlaceAtChunk(ref stringBuilder, ref num2, ptr, value.Length);
                    int num4 = replacements[num3] + removeCount;
                    num3++;
                    if (num3 >= replacementsCount)
                    {
                        break;
                    }
                    int num5 = replacements[num3];
                    if (num != 0)
                    {
                        fixed (char* ptr2 = &sourceChunk.m_ChunkChars[num4])
{
                            char* ptr3 = ptr2;
                            this.ReplaceInPlaceAtChunk(ref stringBuilder, ref num2, ptr3, num5 - num4);
                        }
                    }
                    else
                    {
                        num2 += num5 - num4;
                    }
                }
                if (num < 0)
                {
                    this.Remove(stringBuilder.m_ChunkOffset + num2, -num, out stringBuilder, out num2);
                }
            }
        }
References System.Text.StringBuilder.m_ChunkChars, System.Text.StringBuilder.m_ChunkOffset, System.Text.StringBuilder.MakeRoom(), System.Text.StringBuilder.Remove(), System.Text.StringBuilder.ReplaceInPlaceAtChunk(), System.text, and System.value.
Referenced by System.Text.StringBuilder.Replace().