Terraria Decompiled: System.Convert.FromBase64CharPtr
FromBase64CharPtr()
static unsafe byte[] System.Convert.FromBase64CharPtr (char * inputPtr, int inputLength) inline static private
Definition at line 3365 of file Convert.cs.
        {
            while (inputLength > 0)
            {
                int num = (int)inputPtr[inputLength - 1];
                if (num != 32 && num != 10 && num != 13 && num != 9)
                {
                    break;
                }
                inputLength--;
            }
            byte[] array = new byte[Convert.FromBase64_ComputeResultLength(inputPtr, inputLength)];
            int num2;
            if (!Convert.TryFromBase64Chars(new ReadOnlySpan<char>((void*)inputPtr, inputLength), array, out num2))
            {
                throw new FormatException("The input is not a valid Base-64 string as it contains a non-base 64 character, more than two padding characters, or an illegal character among the padding characters.");
            }
            return array;
        }
References System.array, System.Convert.FromBase64_ComputeResultLength(), int, and System.Convert.TryFromBase64Chars().
Referenced by System.Convert.FromBase64CharArray(), and System.Convert.FromBase64String().