Terraria Decompiled: System.Convert.ToInt32
ToInt32() [10/19]
static int System.Convert.ToInt32 (object value) inline static
Definition at line 1414 of file Convert.cs.
        {
            if (value != null)
            {
                return ((IConvertible)value).ToInt32(null);
            }
            return 0;
        }
References System.value.
Referenced by ReLogic.Reflection.IdDictionary.Create(), Terraria.Main.DedServ(), Terraria.Main.DrawMenu(), FullSerializer.fsJsonPrinter.EscapeString(), System.Security.Policy.Site.IsValid(), Terraria.Main.LoadDedConfig(), Terraria.Initializers.LaunchInitializer.LoadServerParameters(), System.Runtime.Remoting.ObjRef.ObjRef(), Newtonsoft.Json.Linq.JToken.operator int(), Newtonsoft.Json.Linq.JToken.operator int?(), Mono.DataConverter.PackOne(), Newtonsoft.Json.Linq.JsonPath.JPath.ParseArrayIndexer(), Newtonsoft.Json.JsonTextReader.ParseReadNumber(), System.Security.PermissionSet.ProcessAttribute(), Newtonsoft.Json.JsonReader.ReadAsInt32(), Terraria.Main.setServerWorldRollbacks(), Microsoft.Win32.Win32RegistryApi.SetValue(), Microsoft.Win32.KeyHandler.SetValue(), System.Convert.ToByte(), System.Convert.ToInt16(), System.Convert.ToInt32(), System.Boolean.ToInt32(), System.Byte.ToInt32(), System.Char.ToInt32(), System.Decimal.ToInt32(), System.Double.ToInt32(), System.Enum.ToInt32(), System.Int16.ToInt32(), System.Int64.ToInt32(), System.Single.ToInt32(), System.String.ToInt32(), System.UInt16.ToInt32(), System.UInt32.ToInt32(), System.UInt64.ToInt32(), System.Convert.ToSByte(), System.Convert.ToUInt16(), System.Runtime.Serialization.Formatter.WriteMember(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue().