Terraria Decompiled: System.Convert.ToByte
ToByte() [10/19]
static byte System.Convert.ToByte (object value) inline static
Definition at line 924 of file Convert.cs.
        {
            if (value != null)
            {
                return ((IConvertible)value).ToByte(null);
            }
            return 0;
        }
References System.value.
Referenced by System.Security.Cryptography.CryptoConfig.EncodeLongNumber(), System.Security.Cryptography.CryptoConfig.EncodeOID(), System.Security.Permissions.StrongNamePublicKeyBlob.FromString(), System.Enum.InternalFormattedHexString(), Newtonsoft.Json.Linq.JToken.operator byte(), Newtonsoft.Json.Linq.JToken.operator byte?(), Mono.DataConverter.PackOne(), System.Security.PermissionSet.ProcessAttribute(), Newtonsoft.Json.JsonReader.ReadArrayElementIntoByteArrayReportDone(), Newtonsoft.Json.Converters.BinaryConverter.ReadByteArray(), System.Convert.ToByte(), System.Convert.ToByte(), System.Boolean.ToByte(), System.Char.ToByte(), System.Decimal.ToByte(), System.Double.ToByte(), System.Enum.ToByte(), System.Int16.ToByte(), System.Int32.ToByte(), System.Int64.ToByte(), System.SByte.ToByte(), System.Single.ToByte(), System.String.ToByte(), System.UInt16.ToByte(), System.UInt32.ToByte(), System.UInt64.ToByte(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue().