Terraria Decompiled: System.Convert.ToDecimal
ToDecimal() [10/18]
static decimal System.Convert.ToDecimal (object value) inline static
Definition at line 2307 of file Convert.cs.
        {
            if (value != null)
            {
                return ((IConvertible)value).ToDecimal(null);
            }
            return 0m;
        }
References System.value.
Referenced by Newtonsoft.Json.Linq.JValue.Compare(), Newtonsoft.Json.Linq.JValue.Operation(), Newtonsoft.Json.Linq.JToken.operator decimal(), Newtonsoft.Json.Linq.JToken.operator decimal?(), Newtonsoft.Json.JsonTextReader.ParseReadNumber(), Newtonsoft.Json.JsonReader.ReadAsDecimal(), Newtonsoft.Json.Bson.BsonReader.ReadType(), System.Boolean.ToDecimal(), System.Byte.ToDecimal(), System.Double.ToDecimal(), System.Enum.ToDecimal(), System.Int16.ToDecimal(), System.Int32.ToDecimal(), System.Int64.ToDecimal(), System.SByte.ToDecimal(), System.Single.ToDecimal(), System.String.ToDecimal(), System.UInt16.ToDecimal(), System.UInt32.ToDecimal(), System.UInt64.ToDecimal(), Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals(), System.Runtime.Serialization.Formatter.WriteMember(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue().