Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.RunPass
RunPass()
GenPassResult Terraria.WorldBuilding.WorldGenerator.RunPass (GenPass pass) inline private
Definition at line 117 of file WorldGenerator.cs.
        {
            if (!pass.Enabled)
            {
                return new GenPassResult
                {
                    Name = pass.Name,
                    Skipped = true
                };
            }
            Stopwatch stopwatch = Stopwatch.StartNew();
            Main.rand = new UnifiedRandom(this._seed);
            this._progress.Start(pass.Weight);
            try
            {
                pass.Apply(this._progress, this._configuration.GetPassConfiguration(pass.Name));
            }
            catch (Exception ex)
            {
                this._controller.ReportException("Exception in Pass: " + pass.Name, ex);
            }
            this._progress.End();
            return new GenPassResult
            {
                Name = pass.Name,
                DurationMs = (int)stopwatch.ElapsedMilliseconds,
                RandNext = WorldGen.genRand.Next()
            };
        }
References Terraria.WorldBuilding.WorldGenerator._configuration, Terraria.WorldBuilding.WorldGenerator._controller, Terraria.WorldBuilding.WorldGenerator._progress, Terraria.WorldBuilding.WorldGenerator._seed, Terraria.WorldBuilding.GenPass.Apply(), Terraria.WorldBuilding.GenPass.Enabled, Terraria.WorldBuilding.GenerationProgress.End(), Terraria.WorldGen.genRand, Terraria.WorldBuilding.WorldGenConfiguration.GetPassConfiguration(), int, System.Name, Terraria.WorldBuilding.GenPass.Name, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldBuilding.GenerationProgress.Start(), and Terraria.WorldBuilding.GenPass.Weight.
Referenced by Terraria.WorldBuilding.WorldGenerator.GenerateWorld().