Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.GenerateWorld
GenerateWorld()
bool Terraria.WorldBuilding.WorldGenerator.GenerateWorld () inline
Definition at line 43 of file WorldGenerator.cs.
        {
            WorldGenerator._hashTime.Reset();
            this._controller.SetGenerator(this);
            WorldGenerator.CurrentController = this._controller;
            this._progress.TotalWeight = this._passes.Where((GenPass p) => p.Enabled).Sum((GenPass p) => p.Weight);
            WorldGenerator.CurrentGenerationProgress = this._progress;
            if (this._controller.PauseAfterPass != null)
            {
                WorldGenerator.SetDebugWorldGenUIVisibility(true);
            }
            bool flag = false;
            while (!this._controller.QueuedAbort)
            {
                if (!this._controller.Paused)
                {
                    object controlLock = this._controlLock;
                    lock (controlLock)
                    {
                        if (WorldGenerator.PassResults.Count != this._passes.Count)
{
                            this._currentPass = this._passes[WorldGenerator.PassResults.Count];
                            GenPass currentPass = this._currentPass;
                            lock (currentPass)
{
                                WorldGenerator.PassResults.Add(this.RunPass(this._currentPass));
                                this._controller.OnPassCompleted();
                            }
                            this._currentPass = null;
                            continue;
                        }
                    }
                    IL_0163:
                    string text = string.Join<GenPassResult>("\n", WorldGenerator.PassResults);
                    string text2 = "\nFinished world - Seed: {0} Width: {1}, Height: {2}, Evil: {3}, Difficulty: {4}\nTotal Generation Time: {5}\n";
                    object[] array = new object[6];
                    array[0] = Main.ActiveWorldFileData.SeedText;
                    array[1] = Main.maxTilesX;
                    array[2] = Main.maxTilesY;
                    array[3] = WorldGen.WorldGenParam_Evil;
                    array[4] = Main.GameMode;
                    array[5] = WorldGenerator.PassResults.Sum((GenPassResult r) => r.DurationMs);
                    Trace.WriteLine(text + string.Format(text2, array));
                    WorldGenerator.SetDebugWorldGenUIVisibility(false);
                    WorldGenerator.CurrentGenerationProgress = null;
                    WorldGenerator.CurrentController = null;
                    return !flag;
                }
                this._controller.OnPaused();
            }
            flag = true;
            goto IL_0163;
        }
References Terraria.WorldBuilding.WorldGenerator._controller, Terraria.WorldBuilding.WorldGenerator._controlLock, Terraria.WorldBuilding.WorldGenerator._currentPass, Terraria.WorldBuilding.WorldGenerator._hashTime, Terraria.WorldBuilding.WorldGenerator._passes, Terraria.WorldBuilding.WorldGenerator._progress, Terraria.Main.ActiveWorldFileData, System.array, Terraria.WorldBuilding.GenPassResult.DurationMs, Terraria.WorldBuilding.GenPass.Enabled, System.Format, Terraria.Main.GameMode, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.WorldGenerator.PassResults, Terraria.WorldBuilding.WorldGenerator.RunPass(), Terraria.WorldBuilding.WorldGenerator.SetDebugWorldGenUIVisibility(), System.text, System.Trace, Terraria.WorldBuilding.GenPass.Weight, and Terraria.WorldGen.WorldGenParam_Evil.
Referenced by Terraria.WorldGen.GenerateWorld().