Terraria Decompiled: Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 54 of file UIDebugCommandItem.cs.
        {
            string name = this.Command.Name;
            string text = this.Command.Description ?? "";
            string helpText = this.Command.HelpText;
            "Authority:  " + this.Command.Requirements;
            base.DrawSelf(spriteBatch);
            if (base.IsMouseHovering)
            {
                Item item = Main.DisplayAndGetFakeItem(ItemRarityColor.StrongRed10);
                item.SetNameOverride(name);
                item.ToolTip = this._preparedTooltip;
            }
            CalculatedStyle innerDimensions = base.GetInnerDimensions();
            Vector2 vector = innerDimensions.Position() - innerDimensions.Position();
            float num = 6f;
            float num2 = vector.X + num;
            float num3 = 21f;
            FontAssets.MouseText.Value.MeasureString(name);
            Color color = Color.White;
            Color color2 = Color.Gold;
            if (!this.CanCurrentlyBeUsed())
            {
                color = Color.DarkGray;
                color2 = Color.DarkGray;
            }
            Utils.DrawBorderString(spriteBatch, name, innerDimensions.Position() + new Vector2(num2 + 6f, vector.Y - 2f), color, 1.1f, 0f, 0f, -1);
            Utils.DrawBorderString(spriteBatch, text, innerDimensions.Position() + new Vector2(num2 + 6f + 180f + 16f, vector.Y + 2f + num3), color2, 0.8f, 0f, 1f, -1);
        }
References Terraria.GameContent.UI.Elements.UIDebugCommandItem._preparedTooltip, Terraria.GameContent.UI.Elements.UIDebugCommandItem.CanCurrentlyBeUsed(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.Command, Microsoft.Xna.Framework.Color.DarkGray, Terraria.Main.DisplayAndGetFakeItem(), Terraria.Utils.DrawBorderString(), Microsoft.Xna.Framework.Color.Gold, Terraria.Testing.ChatCommands.IDebugCommand.HelpText, System.item, Terraria.GameContent.FontAssets.MouseText, System.name, Terraria.Testing.ChatCommands.IDebugCommand.Name, Terraria.UI.CalculatedStyle.Position(), Terraria.Testing.ChatCommands.IDebugCommand.Requirements, Terraria.Item.SetNameOverride(), System.text, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Y.