Terraria Decompiled: Terraria.WorldBuilding.WorldGenerator.HashWorld
HashWorld()
static uint Terraria.WorldBuilding.WorldGenerator.HashWorld () inline static
Definition at line 148 of file WorldGenerator.cs.
        {
            WorldGenerator._hashTime.Start();
            uint[] line_hashes = new uint[Main.maxTilesX];
            FastParallel.For(0, Main.maxTilesX, delegate(int x0, int x1, object _)
            {
                Tile[,] tile = Main.tile;
                int maxTilesY = Main.maxTilesY;
                for (int j = x0; j < x1; j++)
                {
                    uint num3 = 0U;
                    for (int k = 0; k < maxTilesY; k++)
                    {
                        num3 ^= (uint)TileSnapshot.TileStruct.From(tile[j, k]).GetHashCode();
                        num3 = (num3 << 13) | (num3 >> 19);
                        num3 = num3 * 5U + 3864292196U;
                    }
                    line_hashes[j] = num3;
                }
            }, null);
            uint num = 0U;
            foreach (uint num2 in line_hashes)
            {
                num ^= num2;
                num = (num << 13) | (num >> 19);
                num = num * 5U + 3864292196U;
            }
            WorldGenerator._hashTime.Stop();
            return num;
        }
References Terraria.WorldBuilding.WorldGenerator._hashTime, ReLogic.Threading.FastParallel.For(), Terraria.Utilities.TileSnapshot.TileStruct.From(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, and System.U.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__45_0(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.HashCommand(), Terraria.WorldBuilding.WorldGenerator.Controller.OnPassCompleted(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot().