Terraria Decompiled: System.Collections.Concurrent.Partitioner.DynamicPartitionEnumeratorForIndexRange_Abstract.GrabNextChunk
GrabNextChunk()
override bool System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >.GrabNextChunk (int requestedChunkSize) inline protected
Definition at line 743 of file Partitioner.2.cs.
            {
                while (!this.HasNoElementsLeft)
                {
                    long num = Volatile.Read(ref this._sharedIndex.Value);
                    if (this.HasNoElementsLeft)
                    {
                        return false;
                    }
                    long num2 = Math.Min((long)(this.SourceCount - 1), num + (long)requestedChunkSize);
                    if (Interlocked.CompareExchange(ref this._sharedIndex.Value, num2, num) == num)
                    {
                        this._currentChunkSize.Value = (int)(num2 - num);
                        this._localOffset.Value = -1;
                        this._startIndex = (int)(num + 1L);
                        return true;
                    }
                }
                return false;
            }
References System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumerator_Abstract< TSource, TSourceReader >._sharedIndex, System.Threading.Interlocked.CompareExchange(), System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >.HasNoElementsLeft, System.Collections.Concurrent.Partitioner< TSource >.int, System.L, System.Math.Min(), System.Threading.Volatile.Read(), and System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionEnumeratorForIndexRange_Abstract< TSource, TSourceReader >.SourceCount.