Terraria Decompiled: Ionic.Zlib.Tree.DistanceCode
DistanceCode()
static int Ionic.Zlib.Tree.DistanceCode (int dist) inline static package
Definition at line 9 of file Tree.cs.
        {
            if (dist >= 256)
            {
                return (int)Tree._dist_code[256 + SharedUtils.URShift(dist, 7)];
            }
            return (int)Tree._dist_code[dist];
        }
References Ionic.Zlib.Tree._dist_code, and Ionic.Zlib.SharedUtils.URShift().
Referenced by Ionic.Zlib.DeflateManager._tr_tally(), and Ionic.Zlib.DeflateManager.send_compressed_block().