Terraria Decompiled: Ionic.Zlib.Tree.build_tree
build_tree()
void Ionic.Zlib.Tree.build_tree (DeflateManager s) inline package
Definition at line 102 of file Tree.cs.
        {
            short[] array = this.dyn_tree;
            short[] treeCodes = this.staticTree.treeCodes;
            int elems = this.staticTree.elems;
            int num = -1;
            s.heap_len = 0;
            s.heap_max = Tree.HEAP_SIZE;
            for (int i = 0; i < elems; i++)
            {
                if (array[i * 2] != 0)
                {
                    num = (s.heap[++s.heap_len] = i);
                    s.depth[i] = 0;
                }
                else
                {
                    array[i * 2 + 1] = 0;
                }
            }
            int num2;
            while (s.heap_len < 2)
            {
                num2 = (s.heap[++s.heap_len] = ((num < 2) ? (++num) : 0));
                array[num2 * 2] = 1;
                s.depth[num2] = 0;
                s.opt_len--;
                if (treeCodes != null)
                {
                    s.static_len -= (int)treeCodes[num2 * 2 + 1];
                }
            }
            this.max_code = num;
            for (int i = s.heap_len / 2; i >= 1; i--)
            {
                s.pqdownheap(array, i);
            }
            num2 = elems;
            do
            {
                int i = s.heap[1];
                s.heap[1] = s.heap[s.heap_len--];
                s.pqdownheap(array, 1);
                int num3 = s.heap[1];
                s.heap[--s.heap_max] = i;
                s.heap[--s.heap_max] = num3;
                array[num2 * 2] = array[i * 2] + array[num3 * 2];
                s.depth[num2] = (sbyte)(Math.Max((byte)s.depth[i], (byte)s.depth[num3]) + 1);
                array[i * 2 + 1] = (array[num3 * 2 + 1] = (short)num2);
                s.heap[1] = num2++;
                s.pqdownheap(array, 1);
            }
            while (s.heap_len >= 2);
            s.heap[--s.heap_max] = s.heap[1];
            this.gen_bitlen(s);
            Tree.gen_codes(array, num, s.bl_count);
        }
References System.array, Ionic.Zlib.Tree.dyn_tree, Ionic.Zlib.StaticTree.elems, Ionic.Zlib.Tree.gen_bitlen(), Ionic.Zlib.Tree.gen_codes(), Ionic.Zlib.Tree.HEAP_SIZE, int, System.Math.Max(), System.s, Ionic.Zlib.Tree.staticTree, and Ionic.Zlib.StaticTree.treeCodes.
Referenced by Ionic.Zlib.DeflateManager._tr_flush_block(), and Ionic.Zlib.DeflateManager.build_bl_tree().