Terraria Decompiled: System.Security.Policy.ApplicationDirectoryMembershipCondition.Check
Check()
bool System.Security.Policy.ApplicationDirectoryMembershipCondition.Check (Evidence evidence) inline
Implements System.Security.Policy.IMembershipCondition.
Definition at line 21 of file ApplicationDirectoryMembershipCondition.cs.
        {
            if (evidence == null)
            {
                return false;
            }
            string codeBase = Assembly.GetCallingAssembly().CodeBase;
            Uri uri = new Uri(codeBase);
            Url url = new Url(codeBase);
            bool flag = false;
            bool flag2 = false;
            IEnumerator hostEnumerator = evidence.GetHostEnumerator();
            while (hostEnumerator.MoveNext())
            {
                object obj = hostEnumerator.Current;
                if (!flag && obj is ApplicationDirectory)
                {
                    string directory = (obj as ApplicationDirectory).Directory;
                    flag = string.Compare(directory, 0, uri.ToString(), 0, directory.Length, true, CultureInfo.InvariantCulture) == 0;
                }
                else if (!flag2 && obj is Url)
                {
                    flag2 = url.Equals(obj);
                }
                if (flag && flag2)
                {
                    return true;
                }
            }
            return false;
        }
References System.Runtime.InteropServices.ApplicationDirectory, System.Reflection.Assembly.CodeBase, System.Collections.IEnumerator.Current, System.Security.Policy.Url.Equals(), System.Reflection.Assembly.GetCallingAssembly(), System.Security.Policy.Evidence.GetHostEnumerator(), System.Globalization.CultureInfo.InvariantCulture, System.Collections.IEnumerator.MoveNext(), System.obj, and Mono.Security.Uri.ToString().