Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.ReadArrayElements
ReadArrayElements()
void Newtonsoft.Json.Converters.XmlNodeConverter.ReadArrayElements (JsonReader reader, IXmlDocument document, string propertyName, IXmlNode currentNode, XmlNamespaceManager manager) inline private
Definition at line 707 of file XmlNodeConverter.cs.
        {
            string prefix = MiscellaneousUtils.GetPrefix(propertyName);
            IXmlElement xmlElement = this.CreateElement(propertyName, document, prefix, manager);
            currentNode.AppendChild(xmlElement);
            int num = 0;
            while (reader.Read() && reader.TokenType != JsonToken.EndArray)
            {
                this.DeserializeValue(reader, document, manager, propertyName, xmlElement);
                num++;
            }
            if (this.WriteArrayAttribute)
            {
                this.AddJsonArrayAttribute(xmlElement, document);
            }
            if (num == 1 && this.WriteArrayAttribute)
            {
                foreach (IXmlNode xmlNode in xmlElement.ChildNodes)
                {
                    IXmlElement xmlElement2 = xmlNode as IXmlElement;
                    if (xmlElement2 != null && xmlElement2.LocalName == propertyName)
                    {
                        this.AddJsonArrayAttribute(xmlElement2, document);
                        break;
                    }
                }
            }
        }
References Newtonsoft.Json.Converters.XmlNodeConverter.AddJsonArrayAttribute(), Newtonsoft.Json.Converters.IXmlNode.AppendChild(), Newtonsoft.Json.Converters.IXmlNode.ChildNodes, Newtonsoft.Json.Converters.XmlNodeConverter.CreateElement(), Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeValue(), Newtonsoft.Json.Utilities.MiscellaneousUtils.GetPrefix(), Newtonsoft.Json.Converters.IXmlNode.LocalName, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.Converters.XmlNodeConverter.WriteArrayAttribute.
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeValue().