Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeValue
DeserializeValue()
void Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeValue (JsonReader reader, IXmlDocument document, XmlNamespaceManager manager, string propertyName, IXmlNode currentNode) inline private
Definition at line 527 of file XmlNodeConverter.cs.
        {
            if (propertyName == "#text")
            {
                currentNode.AppendChild(document.CreateTextNode(this.ConvertTokenToXmlValue(reader)));
                return;
            }
            if (propertyName == "#cdata-section")
            {
                currentNode.AppendChild(document.CreateCDataSection(this.ConvertTokenToXmlValue(reader)));
                return;
            }
            if (propertyName == "#whitespace")
            {
                currentNode.AppendChild(document.CreateWhitespace(this.ConvertTokenToXmlValue(reader)));
                return;
            }
            if (propertyName == "#significant-whitespace")
            {
                currentNode.AppendChild(document.CreateSignificantWhitespace(this.ConvertTokenToXmlValue(reader)));
                return;
            }
            if (!string.IsNullOrEmpty(propertyName) && propertyName.get_Chars(0) == '?')
            {
                this.CreateInstruction(reader, document, currentNode, propertyName);
                return;
            }
            if (string.Equals(propertyName, "!DOCTYPE", 5))
            {
                this.CreateDocumentType(reader, document, currentNode);
                return;
            }
            if (reader.TokenType == JsonToken.StartArray)
            {
                this.ReadArrayElements(reader, document, propertyName, currentNode, manager);
                return;
            }
            this.ReadElement(reader, document, currentNode, propertyName, manager);
        }
References Newtonsoft.Json.Converters.IXmlNode.AppendChild(), Newtonsoft.Json.Converters.IXmlDocument.CreateCDataSection(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateDocumentType(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateInstruction(), Newtonsoft.Json.Converters.IXmlDocument.CreateSignificantWhitespace(), Newtonsoft.Json.Converters.IXmlDocument.CreateTextNode(), Newtonsoft.Json.Converters.IXmlDocument.CreateWhitespace(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadArrayElements(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadElement(), and Newtonsoft.Json.JsonReader.TokenType.
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode(), and Newtonsoft.Json.Converters.XmlNodeConverter.ReadArrayElements().