Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.SerializeGroupedNodes
SerializeGroupedNodes()
void Newtonsoft.Json.Converters.XmlNodeConverter.SerializeGroupedNodes (JsonWriter writer, IXmlNode node, XmlNamespaceManager manager, bool writePropertyName) inline private
Definition at line 194 of file XmlNodeConverter.cs.
        {
            int count = node.ChildNodes.Count;
            if (count != 0)
            {
                if (count == 1)
                {
                    string propertyName = this.GetPropertyName(node.ChildNodes[0], manager);
                    this.WriteGroupedNodes(writer, manager, writePropertyName, node.ChildNodes, propertyName);
                    return;
                }
                Dictionary<string, object> dictionary = null;
                string text = null;
                for (int i = 0; i < node.ChildNodes.Count; i++)
                {
                    IXmlNode xmlNode = node.ChildNodes[i];
                    string propertyName2 = this.GetPropertyName(xmlNode, manager);
                    object obj;
                    if (dictionary == null)
                    {
                        if (text == null)
{
                            text = propertyName2;
                        }
                        else if (!(propertyName2 == text))
{
                            dictionary = new Dictionary<string, object>();
                            if (i > 1)
{
                                List<IXmlNode> list = new List<IXmlNode>(i);
                                for (int j = 0; j < i; j++)
{
                                    list.Add(node.ChildNodes[j]);
                                }
                                dictionary.Add(text, list);
                            }
                            else
{
                                dictionary.Add(text, node.ChildNodes[0]);
                            }
                            dictionary.Add(propertyName2, xmlNode);
                        }
                    }
                    else if (!dictionary.TryGetValue(propertyName2, ref obj))
                    {
                        dictionary.Add(propertyName2, xmlNode);
                    }
                    else
                    {
                        List<IXmlNode> list2 = obj as List<IXmlNode>;
                        if (list2 == null)
{
                            List<IXmlNode> list3 = new List<IXmlNode>();
                            list3.Add((IXmlNode)obj);
                            list2 = list3;
                            dictionary[propertyName2] = list2;
                        }
                        list2.Add(xmlNode);
                    }
                }
                if (dictionary == null)
                {
                    this.WriteGroupedNodes(writer, manager, writePropertyName, node.ChildNodes, text);
                    return;
                }
                foreach (KeyValuePair<string, object> keyValuePair in dictionary)
                {
                    List<IXmlNode> list4 = keyValuePair.Value as List<IXmlNode>;
                    if (list4 != null)
                    {
                        this.WriteGroupedNodes(writer, manager, writePropertyName, list4, keyValuePair.Key);
                    }
                    else
                    {
                        this.WriteGroupedNodes(writer, manager, writePropertyName, (IXmlNode)keyValuePair.Value, keyValuePair.Key);
                    }
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Converters.IXmlNode.ChildNodes, System.count, System.dictionary, Newtonsoft.Json.Converters.XmlNodeConverter.GetPropertyName(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.list, System.obj, System.text, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, and Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes().
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode().