Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes
WriteGroupedNodes() [1/2]
void Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes (JsonWriter writer, XmlNamespaceManager manager, bool writePropertyName, IXmlNode node, string elementNames) inline private
Definition at line 295 of file XmlNodeConverter.cs.
        {
            if (!this.IsArray(node))
            {
                this.SerializeNode(writer, node, manager, writePropertyName);
                return;
            }
            if (writePropertyName)
            {
                writer.WritePropertyName(elementNames);
            }
            writer.WriteStartArray();
            this.SerializeNode(writer, node, manager, false);
            writer.WriteEndArray();
        }
References Newtonsoft.Json.Converters.XmlNodeConverter.IsArray(), Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode(), Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.JsonWriter.WriteStartArray().