Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.ReadAttributeElements
ReadAttributeElements()
Dictionary< string, string > Newtonsoft.Json.Converters.XmlNodeConverter.ReadAttributeElements (JsonReader reader, XmlNamespaceManager manager) inline private
Definition at line 747 of file XmlNodeConverter.cs.
        {
            JsonToken jsonToken = reader.TokenType;
            switch (jsonToken)
            {
            case JsonToken.StartConstructor:
            case JsonToken.Integer:
            case JsonToken.Float:
            case JsonToken.String:
            case JsonToken.Boolean:
            case JsonToken.Null:
                break;
            case JsonToken.PropertyName:
            case JsonToken.Comment:
            case JsonToken.Raw:
                goto IL_003A;
            default:
                if (jsonToken != JsonToken.Date)
                {
                    goto IL_003A;
                }
                break;
            }
            return null;
            IL_003A:
            Dictionary<string, string> dictionary = null;
            bool flag = false;
            while (!flag && reader.Read())
            {
                jsonToken = reader.TokenType;
                if (jsonToken != JsonToken.PropertyName)
                {
                    if (jsonToken != JsonToken.Comment && jsonToken != JsonToken.EndObject)
                    {
                        throw JsonSerializationException.Create(reader, "Unexpected JsonToken: " + reader.TokenType);
                    }
                    flag = true;
                }
                else
                {
                    string text = reader.Value.ToString();
                    if (!string.IsNullOrEmpty(text))
                    {
                        char c = text.get_Chars(0);
                        if (c != '$')
{
                            if (c == '@')
{
                                if (dictionary == null)
{
                                    dictionary = new Dictionary<string, string>();
                                }
                                text = text.Substring(1);
                                reader.Read();
                                string text2 = this.ConvertTokenToXmlValue(reader);
                                dictionary.Add(text, text2);
                                string text3;
                                if (this.IsNamespaceAttribute(text, out text3))
{
                                    manager.AddNamespace(text3, text2);
                                }
                            }
                            else
{
                                flag = true;
                            }
                        }
                        else if (text == "$values" || text == "$id" || text == "$ref" || text == "$type" || text == "$value")
{
                            string text4 = manager.LookupPrefix("http://james.newtonking.com/projects/json");
                            if (text4 == null)
{
                                if (dictionary == null)
{
                                    dictionary = new Dictionary<string, string>();
                                }
                                int? num = default(int?);
                                while (manager.LookupNamespace("json" + num) != null)
{
                                    num = new int?(num.GetValueOrDefault() + 1);
                                }
                                text4 = "json" + num;
                                dictionary.Add("xmlns:" + text4, "http://james.newtonking.com/projects/json");
                                manager.AddNamespace(text4, "http://james.newtonking.com/projects/json");
                            }
                            if (text == "$values")
{
                                flag = true;
                            }
                            else
{
                                text = text.Substring(1);
                                reader.Read();
                                if (!JsonTokenUtils.IsPrimitiveToken(reader.TokenType))
{
                                    throw JsonSerializationException.Create(reader, "Unexpected JsonToken: " + reader.TokenType);
                                }
                                if (dictionary == null)
{
                                    dictionary = new Dictionary<string, string>();
                                }
                                object value = reader.Value;
                                string text2 = ((value != null) ? value.ToString() : null);
                                dictionary.Add(text4 + ":" + text, text2);
                            }
                        }
                        else
{
                            flag = true;
                        }
                    }
                    else
                    {
                        flag = true;
                    }
                }
            }
            return dictionary;
        }
References Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), Newtonsoft.Json.JsonSerializationException.Create(), System.dictionary, Newtonsoft.Json.Converters.XmlNodeConverter.IsNamespaceAttribute(), Newtonsoft.Json.Utilities.JsonTokenUtils.IsPrimitiveToken(), Newtonsoft.Json.JsonReader.Read(), System.text, Newtonsoft.Json.JsonReader.TokenType, System.value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.ReadElement().