Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode
SerializeNode()
void Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode (JsonWriter writer, IXmlNode node, XmlNamespaceManager manager, bool writePropertyName) inline private
Definition at line 312 of file XmlNodeConverter.cs.
        {
            switch (node.NodeType)
            {
            case 1:
                if (this.IsArray(node) && XmlNodeConverter.AllSameName(node) && node.ChildNodes.Count > 0)
                {
                    this.SerializeGroupedNodes(writer, node, manager, false);
                    return;
                }
                manager.PushScope();
                foreach (IXmlNode xmlNode in node.Attributes)
                {
                    if (xmlNode.NamespaceUri == "http://www.w3.org/2000/xmlns/")
                    {
                        string text = ((xmlNode.LocalName != "xmlns") ? XmlConvert.DecodeName(xmlNode.LocalName) : string.Empty);
                        string value = xmlNode.Value;
                        manager.AddNamespace(text, value);
                    }
                }
                if (writePropertyName)
                {
                    writer.WritePropertyName(this.GetPropertyName(node, manager));
                }
                if (!this.ValueAttributes(node.Attributes) && node.ChildNodes.Count == 1 && node.ChildNodes[0].NodeType == 3)
                {
                    writer.WriteValue(node.ChildNodes[0].Value);
                }
                else if (node.ChildNodes.Count == 0 && node.Attributes.Count == 0)
                {
                    if (((IXmlElement)node).IsEmpty)
                    {
                        writer.WriteNull();
                    }
                    else
                    {
                        writer.WriteValue(string.Empty);
                    }
                }
                else
                {
                    writer.WriteStartObject();
                    for (int i = 0; i < node.Attributes.Count; i++)
                    {
                        this.SerializeNode(writer, node.Attributes[i], manager, true);
                    }
                    this.SerializeGroupedNodes(writer, node, manager, true);
                    writer.WriteEndObject();
                }
                manager.PopScope();
                return;
            case 2:
            case 3:
            case 4:
            case 7:
            case 13:
            case 14:
                if (node.NamespaceUri == "http://www.w3.org/2000/xmlns/" && node.Value == "http://james.newtonking.com/projects/json")
                {
                    return;
                }
                if (node.NamespaceUri == "http://james.newtonking.com/projects/json" && node.LocalName == "Array")
                {
                    return;
                }
                if (writePropertyName)
                {
                    writer.WritePropertyName(this.GetPropertyName(node, manager));
                }
                writer.WriteValue(node.Value);
                return;
            case 8:
                if (writePropertyName)
                {
                    writer.WriteComment(node.Value);
                    return;
                }
                return;
            case 9:
            case 11:
                this.SerializeGroupedNodes(writer, node, manager, writePropertyName);
                return;
            case 10:
            {
                IXmlDocumentType xmlDocumentType = (IXmlDocumentType)node;
                writer.WritePropertyName(this.GetPropertyName(node, manager));
                writer.WriteStartObject();
                if (!string.IsNullOrEmpty(xmlDocumentType.Name))
                {
                    writer.WritePropertyName("@name");
                    writer.WriteValue(xmlDocumentType.Name);
                }
                if (!string.IsNullOrEmpty(xmlDocumentType.Public))
                {
                    writer.WritePropertyName("@public");
                    writer.WriteValue(xmlDocumentType.Public);
                }
                if (!string.IsNullOrEmpty(xmlDocumentType.System))
                {
                    writer.WritePropertyName("@system");
                    writer.WriteValue(xmlDocumentType.System);
                }
                if (!string.IsNullOrEmpty(xmlDocumentType.InternalSubset))
                {
                    writer.WritePropertyName("@internalSubset");
                    writer.WriteValue(xmlDocumentType.InternalSubset);
                }
                writer.WriteEndObject();
                return;
            }
            case 17:
            {
                IXmlDeclaration xmlDeclaration = (IXmlDeclaration)node;
                writer.WritePropertyName(this.GetPropertyName(node, manager));
                writer.WriteStartObject();
                if (!string.IsNullOrEmpty(xmlDeclaration.Version))
                {
                    writer.WritePropertyName("@version");
                    writer.WriteValue(xmlDeclaration.Version);
                }
                if (!string.IsNullOrEmpty(xmlDeclaration.Encoding))
                {
                    writer.WritePropertyName("@encoding");
                    writer.WriteValue(xmlDeclaration.Encoding);
                }
                if (!string.IsNullOrEmpty(xmlDeclaration.Standalone))
                {
                    writer.WritePropertyName("@standalone");
                    writer.WriteValue(xmlDeclaration.Standalone);
                }
                writer.WriteEndObject();
                return;
            }
            }
            throw new JsonSerializationException("Unexpected XmlNodeType when serializing nodes: " + node.NodeType);
        }
References Newtonsoft.Json.Converters.XmlNodeConverter.AllSameName(), Newtonsoft.Json.Converters.IXmlNode.Attributes, Newtonsoft.Json.Converters.IXmlNode.ChildNodes, Newtonsoft.Json.Converters.IXmlDeclaration.Encoding, Newtonsoft.Json.Converters.XmlNodeConverter.GetPropertyName(), Newtonsoft.Json.Converters.IXmlDocumentType.InternalSubset, Newtonsoft.Json.Converters.XmlNodeConverter.IsArray(), Newtonsoft.Json.Converters.IXmlNode.LocalName, Newtonsoft.Json.Converters.IXmlDocumentType.Name, Newtonsoft.Json.Converters.IXmlNode.NamespaceUri, Newtonsoft.Json.Converters.IXmlNode.NodeType, Newtonsoft.Json.Converters.IXmlDocumentType.Public, Newtonsoft.Json.Converters.XmlNodeConverter.SerializeGroupedNodes(), Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode(), Newtonsoft.Json.Converters.IXmlDeclaration.Standalone, Newtonsoft.Json.Converters.IXmlDocumentType.System, System.text, System.value, Newtonsoft.Json.Converters.IXmlNode.Value, Newtonsoft.Json.Converters.XmlNodeConverter.ValueAttributes(), Newtonsoft.Json.Converters.IXmlDeclaration.Version, Newtonsoft.Json.JsonWriter.WriteComment(), Newtonsoft.Json.JsonWriter.WriteEndObject(), Newtonsoft.Json.JsonWriter.WriteNull(), Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.JsonWriter.WriteValue().
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode(), Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes(), Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes(), and Newtonsoft.Json.Converters.XmlNodeConverter.WriteJson().