Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes
WriteGroupedNodes() [2/2]
void Newtonsoft.Json.Converters.XmlNodeConverter.WriteGroupedNodes (JsonWriter writer, XmlNamespaceManager manager, bool writePropertyName, List< IXmlNode > groupedNodes, string elementNames) inline private
Definition at line 275 of file XmlNodeConverter.cs.
        {
            if (groupedNodes.Count == 1 && !this.IsArray(groupedNodes[0]))
            {
                this.SerializeNode(writer, groupedNodes[0], manager, writePropertyName);
                return;
            }
            if (writePropertyName)
            {
                writer.WritePropertyName(elementNames);
            }
            writer.WriteStartArray();
            for (int i = 0; i < groupedNodes.Count; i++)
            {
                this.SerializeNode(writer, groupedNodes[i], manager, false);
            }
            writer.WriteEndArray();
        }
References System.Collections.Generic.List< T >.Count, Newtonsoft.Json.Converters.XmlNodeConverter.SerializeNode(), Newtonsoft.Json.JsonWriter.WriteEndArray(), Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.JsonWriter.WriteStartArray().
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.SerializeGroupedNodes().