Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue
ConvertTokenToXmlValue()
string Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue (JsonReader reader) inline private
Definition at line 660 of file XmlNodeConverter.cs.
        {
            switch (reader.TokenType)
            {
            case JsonToken.Integer:
                if (reader.Value is BigInteger)
                {
                    return ((BigInteger)reader.Value).ToString(CultureInfo.InvariantCulture);
                }
                return XmlConvert.ToString(Convert.ToInt64(reader.Value, CultureInfo.InvariantCulture));
            case JsonToken.Float:
                if (reader.Value is decimal)
                {
                    return XmlConvert.ToString((decimal)reader.Value);
                }
                if (reader.Value is float)
                {
                    return XmlConvert.ToString((float)reader.Value);
                }
                return XmlConvert.ToString(Convert.ToDouble(reader.Value, CultureInfo.InvariantCulture));
            case JsonToken.String:
            {
                object value = reader.Value;
                if (value == null)
                {
                    return null;
                }
                return value.ToString();
            }
            case JsonToken.Boolean:
                return XmlConvert.ToString(Convert.ToBoolean(reader.Value, CultureInfo.InvariantCulture));
            case JsonToken.Null:
                return null;
            case JsonToken.Date:
            {
                if (reader.Value is DateTimeOffset)
                {
                    return XmlConvert.ToString((DateTimeOffset)reader.Value);
                }
                DateTime dateTime = Convert.ToDateTime(reader.Value, CultureInfo.InvariantCulture);
                return XmlConvert.ToString(dateTime, DateTimeUtils.ToSerializationMode(dateTime.Kind));
            }
            }
            throw JsonSerializationException.Create(reader, "Cannot get an XML string value from token type '{0}'.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonSerializationException.Create(), System.Globalization.CultureInfo.InvariantCulture, System.DateTime.Kind, System.Convert.ToBoolean(), System.Convert.ToDateTime(), System.Convert.ToDouble(), System.Convert.ToInt64(), Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Utilities.DateTimeUtils.ToSerializationMode(), System.DateTime.ToString(), System.value, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.CreateDocumentType(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateElement(), Newtonsoft.Json.Converters.XmlNodeConverter.CreateInstruction(), and Newtonsoft.Json.Converters.XmlNodeConverter.ReadAttributeElements().