Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.CreateInstruction
CreateInstruction()
void Newtonsoft.Json.Converters.XmlNodeConverter.CreateInstruction (JsonReader reader, IXmlDocument document, IXmlNode currentNode, string propertyName) inline private
Definition at line 868 of file XmlNodeConverter.cs.
        {
            if (propertyName == "?xml")
            {
                string text = null;
                string text2 = null;
                string text3 = null;
                while (reader.Read() && reader.TokenType != JsonToken.EndObject)
                {
                    string text4 = reader.Value.ToString();
                    if (!(text4 == "@version"))
                    {
                        if (!(text4 == "@encoding"))
{
                            if (!(text4 == "@standalone"))
{
                                throw JsonSerializationException.Create(reader, "Unexpected property name encountered while deserializing XmlDeclaration: " + reader.Value);
                            }
                            reader.Read();
                            text3 = this.ConvertTokenToXmlValue(reader);
                        }
                        else
{
                            reader.Read();
                            text2 = this.ConvertTokenToXmlValue(reader);
                        }
                    }
                    else
                    {
                        reader.Read();
                        text = this.ConvertTokenToXmlValue(reader);
                    }
                }
                IXmlNode xmlNode = document.CreateXmlDeclaration(text, text2, text3);
                currentNode.AppendChild(xmlNode);
                return;
            }
            IXmlNode xmlNode2 = document.CreateProcessingInstruction(propertyName.Substring(1), this.ConvertTokenToXmlValue(reader));
            currentNode.AppendChild(xmlNode2);
        }
References Newtonsoft.Json.Converters.IXmlNode.AppendChild(), Newtonsoft.Json.Converters.XmlNodeConverter.ConvertTokenToXmlValue(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Converters.IXmlDocument.CreateProcessingInstruction(), Newtonsoft.Json.Converters.IXmlDocument.CreateXmlDeclaration(), Newtonsoft.Json.JsonReader.Read(), System.text, Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeValue().