Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.XmlNodeConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 466 of file XmlNodeConverter.cs.
        {
            JsonToken tokenType = reader.TokenType;
            if (tokenType != JsonToken.StartObject)
            {
                if (tokenType == JsonToken.Null)
                {
                    return null;
                }
                throw JsonSerializationException.Create(reader, "XmlNodeConverter can only convert JSON that begins with an object.");
            }
            else
            {
                XmlNamespaceManager xmlNamespaceManager = new XmlNamespaceManager(new NameTable());
                IXmlDocument xmlDocument = null;
                IXmlNode xmlNode = null;
                if (typeof(XObject).IsAssignableFrom(objectType))
                {
                    if (objectType != typeof(XDocument) && objectType != typeof(XElement))
                    {
                        throw JsonSerializationException.Create(reader, "XmlNodeConverter only supports deserializing XDocument or XElement.");
                    }
                    xmlDocument = new XDocumentWrapper(new XDocument());
                    xmlNode = xmlDocument;
                }
                if (typeof(XmlNode).IsAssignableFrom(objectType))
                {
                    if (objectType != typeof(XmlDocument))
                    {
                        throw JsonSerializationException.Create(reader, "XmlNodeConverter only supports deserializing XmlDocuments");
                    }
                    xmlDocument = new XmlDocumentWrapper(new XmlDocument
                    {
                        XmlResolver = null
                    });
                    xmlNode = xmlDocument;
                }
                if (xmlDocument == null || xmlNode == null)
                {
                    throw JsonSerializationException.Create(reader, "Unexpected type when converting XML: " + objectType);
                }
                if (!string.IsNullOrEmpty(this.DeserializeRootElementName))
                {
                    this.ReadElement(reader, xmlDocument, xmlNode, this.DeserializeRootElementName, xmlNamespaceManager);
                }
                else
                {
                    reader.Read();
                    this.DeserializeNode(reader, xmlDocument, xmlNamespaceManager, xmlNode);
                }
                if (objectType == typeof(XElement))
                {
                    XElement xelement = (XElement)xmlDocument.DocumentElement.WrappedNode;
                    xelement.Remove();
                    return xelement;
                }
                return xmlDocument.WrappedNode;
            }
        }
References Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode(), Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeRootElementName, Newtonsoft.Json.Converters.IXmlDocument.DocumentElement, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Converters.XmlNodeConverter.ReadElement(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.Converters.IXmlNode.WrappedNode.