Terraria Decompiled: Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode
DeserializeNode()
void Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeNode (JsonReader reader, IXmlDocument document, XmlNamespaceManager manager, IXmlNode currentNode) inline private
Definition at line 967 of file XmlNodeConverter.cs.
        {
            JsonToken tokenType;
            for (;;)
            {
                tokenType = reader.TokenType;
                switch (tokenType)
                {
                case JsonToken.StartConstructor:
                {
                    string text = reader.Value.ToString();
                    while (reader.Read())
                    {
                        if (reader.TokenType == JsonToken.EndConstructor)
{
                            break;
                        }
                        this.DeserializeValue(reader, document, manager, text, currentNode);
                    }
                    goto IL_0175;
                }
                case JsonToken.PropertyName:
                {
                    if (currentNode.NodeType == 9 && document.DocumentElement != null)
                    {
                        goto Block_4;
                    }
                    string text2 = reader.Value.ToString();
                    reader.Read();
                    if (reader.TokenType == JsonToken.StartArray)
                    {
                        int num = 0;
                        while (reader.Read() && reader.TokenType != JsonToken.EndArray)
{
                            this.DeserializeValue(reader, document, manager, text2, currentNode);
                            num++;
                        }
                        if (num != 1 || !this.WriteArrayAttribute)
{
                            goto IL_0175;
                        }
                        using (List<IXmlNode>.Enumerator enumerator = currentNode.ChildNodes.GetEnumerator())
{
                            while (enumerator.MoveNext())
{
                                IXmlNode xmlNode = enumerator.Current;
                                IXmlElement xmlElement = xmlNode as IXmlElement;
                                if (xmlElement != null && xmlElement.LocalName == text2)
{
                                    this.AddJsonArrayAttribute(xmlElement, document);
                                    break;
                                }
                            }
                            goto IL_0175;
                        }
                    }
                    this.DeserializeValue(reader, document, manager, text2, currentNode);
                    goto IL_0175;
                }
                case JsonToken.Comment:
                    currentNode.AppendChild(document.CreateComment((string)reader.Value));
                    goto IL_0175;
                }
                break;
                IL_0175:
                if (!reader.Read())
                {
                    return;
                }
            }
            if (tokenType != JsonToken.EndObject && tokenType != JsonToken.EndArray)
            {
                throw JsonSerializationException.Create(reader, "Unexpected JsonToken when deserializing node: " + reader.TokenType);
            }
            return;
            Block_4:
            throw JsonSerializationException.Create(reader, "JSON root object has multiple properties. The root object must have a single property in order to create a valid XML document. Consider specifying a DeserializeRootElementName.");
        }
References Newtonsoft.Json.Converters.XmlNodeConverter.AddJsonArrayAttribute(), Newtonsoft.Json.Converters.IXmlNode.AppendChild(), Newtonsoft.Json.Converters.IXmlNode.ChildNodes, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Converters.IXmlDocument.CreateComment(), Newtonsoft.Json.Converters.XmlNodeConverter.DeserializeValue(), Newtonsoft.Json.Converters.IXmlDocument.DocumentElement, Newtonsoft.Json.Converters.IXmlNode.LocalName, Newtonsoft.Json.Converters.IXmlNode.NodeType, Newtonsoft.Json.JsonReader.Read(), System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.JsonReader.Value, and Newtonsoft.Json.Converters.XmlNodeConverter.WriteArrayAttribute.
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.CreateElement(), and Newtonsoft.Json.Converters.XmlNodeConverter.ReadJson().