Terraria Decompiled: System.Security.SecurityElement.SearchForTextOfLocalName
SearchForTextOfLocalName()
string System.Security.SecurityElement.SearchForTextOfLocalName (string strLocalName) inline package
Definition at line 578 of file SecurityElement.cs.
        {
            if (strLocalName == null)
            {
                throw new ArgumentNullException("strLocalName");
            }
            if (this.tag == null)
            {
                return null;
            }
            if (this.tag.Equals(strLocalName) || this.tag.EndsWith(":" + strLocalName, StringComparison.Ordinal))
            {
                return SecurityElement.Unescape(this.text);
            }
            if (this.children == null)
            {
                return null;
            }
            foreach (object obj in this.children)
            {
                string text = ((SecurityElement)obj).SearchForTextOfLocalName(strLocalName);
                if (text != null)
                {
                    return text;
                }
            }
            return null;
        }
References System.Security.SecurityElement.children, System.obj, System.Security.SecurityElement.SecurityElement(), System.Security.SecurityElement.tag, System.Security.SecurityElement.text, and System.Security.SecurityElement.Unescape().
Referenced by System.Security.Cryptography.DSA.FromXmlString(), and System.Security.Cryptography.RSA.FromXmlString().