Terraria Decompiled: System.Security.SecurityElement.Attribute
Attribute()
string System.Security.SecurityElement.Attribute (string name) inline
Definition at line 207 of file SecurityElement.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            SecurityElement.SecurityAttribute attribute = this.GetAttribute(name);
            if (attribute != null)
            {
                return attribute.Value;
            }
            return null;
        }
References System.Security.SecurityElement.GetAttribute(), System.name, and System.Security.SecurityElement.SecurityAttribute.Value.
Referenced by System.Security.CodeAccessPermission.CheckSecurityElement(), System.Security.Permissions.PrincipalPermission.CheckSecurityElement(), System.Security.Policy.MembershipConditionHelper.CheckSecurityElement(), System.Security.PermissionBuilder.Create(), System.Security.Policy.CodeGroup.CreateFromXml(), System.Security.Permissions.PermissionSetAttribute.CreateFromXml(), System.Security.Permissions.StrongNameIdentityPermission.FromSecurityElement(), System.Security.Permissions.HostProtectionPermission.FromXml(), System.Security.Policy.PolicyLevel.FromXml(), System.Security.Policy.CodeGroup.FromXml(), System.Security.Policy.HashMembershipCondition.FromXml(), System.Security.Policy.SiteMembershipCondition.FromXml(), System.Security.Policy.StrongNameMembershipCondition.FromXml(), System.Security.Policy.UrlMembershipCondition.FromXml(), System.Security.Policy.ZoneMembershipCondition.FromXml(), System.Security.Permissions.PrincipalPermission.FromXml(), System.Security.Policy.ApplicationTrust.FromXml(), System.Security.Permissions.EnvironmentPermission.FromXml(), System.Security.Permissions.FileDialogPermission.FromXml(), System.Security.Permissions.FileIOPermission.FromXml(), System.Security.Permissions.IsolatedStoragePermission.FromXml(), System.Security.Permissions.RegistryPermission.FromXml(), System.Security.Permissions.SecurityPermission.FromXml(), System.Security.Permissions.SiteIdentityPermission.FromXml(), System.Security.Permissions.UIPermission.FromXml(), System.Security.Permissions.UrlIdentityPermission.FromXml(), System.Security.Permissions.ZoneIdentityPermission.FromXml(), System.Security.NamedPermissionSet.FromXml(), System.Security.PermissionSet.FromXml(), System.Security.Policy.PolicyStatement.FromXml(), System.Security.Permissions.KeyContainerPermission.FromXml(), System.Security.CodeAccessPermission.IsUnrestricted(), Mono.Security.StrongNameManager.LoadMapping(), Mono.Security.StrongNameManager.LoadVerificationSettings(), and System.Security.Policy.FileCodeGroup.ParseXml().