Terraria Decompiled: System.Security.SecurityElement.ToString
ToString()
override string System.Security.SecurityElement.ToString () inline
Definition at line 471 of file SecurityElement.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            this.ToXml(ref stringBuilder, 0);
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.ToString(), and System.Security.SecurityElement.ToXml().
Referenced by System.Reflection.Emit.ConstructorBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.MethodBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.TypeBuilder.AddDeclarativeSecurity(), System.Reflection.Emit.AssemblyBuilder.AddPermissionRequests(), System.Security.Policy.PermissionRequestEvidence.GetRequiredSize(), Microsoft.Win32.KeyHandler.Save(), System.Security.Policy.PolicyLevel.Save(), System.Security.CodeAccessPermission.ToString(), System.Security.Permissions.PrincipalPermission.ToString(), System.Security.PermissionSet.ToString(), System.Security.Policy.ApplicationDirectory.ToString(), System.Security.Policy.GacInstalled.ToString(), System.Security.Policy.Hash.ToString(), System.Security.Policy.PermissionRequestEvidence.ToString(), System.Security.Policy.Site.ToString(), System.Security.Policy.StrongName.ToString(), System.Security.Policy.Url.ToString(), and System.Security.Policy.Zone.ToString().