Terraria Decompiled: System.Security.SecurityElement.ToXml
ToXml()
void System.Security.SecurityElement.ToXml (ref StringBuilder s, int level) inline private
Definition at line 479 of file SecurityElement.cs.
        {
            s.Append("<");
            s.Append(this.tag);
            if (this.attributes != null)
            {
                s.Append(" ");
                for (int i = 0; i < this.attributes.Count; i++)
                {
                    SecurityElement.SecurityAttribute securityAttribute = (SecurityElement.SecurityAttribute)this.attributes[i];
                    s.Append(securityAttribute.Name).Append("=\"").Append(SecurityElement.Escape(securityAttribute.Value))
                        .Append("\"");
                    if (i != this.attributes.Count - 1)
                    {
                        s.Append(Environment.NewLine);
                    }
                }
            }
            if ((this.text == null || this.text == string.Empty) && (this.children == null || this.children.Count == 0))
            {
                s.Append("/>").Append(Environment.NewLine);
                return;
            }
            s.Append(">").Append(SecurityElement.Escape(this.text));
            if (this.children != null)
            {
                s.Append(Environment.NewLine);
                foreach (object obj in this.children)
                {
                    ((SecurityElement)obj).ToXml(ref s, level + 1);
                }
            }
            s.Append("</").Append(this.tag).Append(">")
                .Append(Environment.NewLine);
        }
References System.Security.SecurityElement.attributes, System.Security.SecurityElement.children, System.Collections.ArrayList.Count, System.Security.SecurityElement.Escape(), System.Security.SecurityElement.SecurityAttribute.Name, System.obj, System.s, System.Security.SecurityElement.SecurityElement(), System.Security.SecurityElement.tag, System.Security.SecurityElement.text, and System.Security.SecurityElement.SecurityAttribute.Value.
Referenced by System.Security.SecurityElement.ToString(), System.Security.NamedPermissionSet.ToXml(), and System.Security.Permissions.IsolatedStorageFilePermission.ToXml().