Terraria Decompiled: System.Security.SecurityElement.Escape
Escape()
static string System.Security.SecurityElement.Escape (string str) inline static
Definition at line 297 of file SecurityElement.cs.
        {
            if (str == null)
            {
                return null;
            }
            if (str.IndexOfAny(SecurityElement.invalid_chars) == -1)
            {
                return str;
            }
            StringBuilder stringBuilder = new StringBuilder();
            int length = str.Length;
            int i = 0;
            while (i < length)
            {
                char c = str[i];
                if (c <= '&')
                {
                    if (c != '"')
                    {
                        if (c != '&')
{
                            goto IL_0096;
                        }
                        stringBuilder.Append("&amp;");
                    }
                    else
                    {
                        stringBuilder.Append("&quot;");
                    }
                }
                else if (c != '\'')
                {
                    if (c != '<')
                    {
                        if (c != '>')
{
                            goto IL_0096;
                        }
                        stringBuilder.Append("&gt;");
                    }
                    else
                    {
                        stringBuilder.Append("&lt;");
                    }
                }
                else
                {
                    stringBuilder.Append("&apos;");
                }
                IL_009E:
                i++;
                continue;
                IL_0096:
                stringBuilder.Append(c);
                goto IL_009E;
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Security.SecurityElement.invalid_chars, System.length, and System.Text.StringBuilder.ToString().
Referenced by Mono.Xml.SecurityParser.OnChars(), Mono.Xml.SecurityParser.OnStartElement(), Microsoft.Win32.KeyHandler.Save(), and System.Security.SecurityElement.ToXml().