Terraria Decompiled: System.Security.SecurityElement.AddAttribute
AddAttribute()
void System.Security.SecurityElement.AddAttribute (string name, string value) inline
Definition at line 171 of file SecurityElement.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            if (this.GetAttribute(name) != null)
            {
                throw new ArgumentException(Locale.GetText("Duplicate attribute : " + name));
            }
            if (this.attributes == null)
            {
                this.attributes = new ArrayList();
            }
            this.attributes.Add(new SecurityElement.SecurityAttribute(name, value));
        }
References System.Collections.ArrayList.Add(), System.Security.SecurityElement.attributes, System.Security.SecurityElement.GetAttribute(), Locale.GetText(), System.name, and System.value.
Referenced by System.Security.PermissionBuilder.Create(), System.Security.Policy.FileCodeGroup.CreateXml(), System.Security.CodeAccessPermission.Element(), System.Security.Policy.MembershipConditionHelper.Element(), System.Security.SecurityDocument.InternalGetElement(), Mono.Xml.SecurityParser.OnStartElement(), System.Security.Policy.DefaultPolicies.PrintingPermission(), Microsoft.Win32.KeyHandler.Save(), System.Security.SecurityElement.SecurityElement(), System.Security.Permissions.StrongNameIdentityPermission.ToSecurityElement(), System.Security.Policy.ApplicationDirectory.ToString(), System.Security.Policy.GacInstalled.ToString(), System.Security.Policy.Hash.ToString(), System.Security.Policy.PermissionRequestEvidence.ToString(), System.Security.Policy.Site.ToString(), System.Security.Policy.StrongName.ToString(), System.Security.Policy.Url.ToString(), System.Security.Policy.Zone.ToString(), System.Security.NamedPermissionSet.ToXml(), System.Security.Permissions.EnvironmentPermission.ToXml(), System.Security.Permissions.FileDialogPermission.ToXml(), System.Security.Permissions.FileIOPermission.ToXml(), System.Security.Permissions.HostProtectionPermission.ToXml(), System.Security.Permissions.IsolatedStoragePermission.ToXml(), System.Security.Permissions.KeyContainerPermission.ToXml(), System.Security.Permissions.PrincipalPermission.ToXml(), System.Security.Permissions.PublisherIdentityPermission.ToXml(), System.Security.Permissions.ReflectionPermission.ToXml(), System.Security.Permissions.RegistryPermission.ToXml(), System.Security.Permissions.SecurityPermission.ToXml(), System.Security.Permissions.SiteIdentityPermission.ToXml(), System.Security.Permissions.UIPermission.ToXml(), System.Security.Permissions.UrlIdentityPermission.ToXml(), System.Security.Permissions.ZoneIdentityPermission.ToXml(), System.Security.PermissionSet.ToXml(), System.Security.Policy.ApplicationTrust.ToXml(), System.Security.Policy.MonoTrustManager.ToXml(), System.Security.Policy.PolicyLevel.ToXml(), System.Security.Policy.CodeGroup.ToXml(), System.Security.Policy.HashMembershipCondition.ToXml(), System.Security.Policy.PolicyStatement.ToXml(), System.Security.Policy.SiteMembershipCondition.ToXml(), System.Security.Policy.StrongNameMembershipCondition.ToXml(), System.Security.Policy.UrlMembershipCondition.ToXml(), and System.Security.Policy.ZoneMembershipCondition.ToXml().