Terraria Decompiled: System.Security.SecurityElement.AddChild
AddChild()
void System.Security.SecurityElement.AddChild (SecurityElement child) inline
Definition at line 193 of file SecurityElement.cs.
        {
            if (child == null)
            {
                throw new ArgumentNullException("child");
            }
            if (this.children == null)
            {
                this.children = new ArrayList();
            }
            this.children.Add(child);
        }
References System.Collections.ArrayList.Add(), and System.Security.SecurityElement.children.
Referenced by System.Security.SecurityDocument.InternalGetElement(), Microsoft.Win32.KeyHandler.Save(), System.Security.SecurityElement.SecurityElement(), System.Security.Policy.ApplicationDirectory.ToString(), System.Security.Policy.Hash.ToString(), System.Security.Policy.PermissionRequestEvidence.ToString(), System.Security.Policy.Site.ToString(), System.Security.Policy.Url.ToString(), System.Security.Policy.Zone.ToString(), System.Security.Permissions.StrongNameIdentityPermission.ToXml(), System.Security.Policy.ApplicationTrust.ToXml(), System.Security.Policy.PolicyLevel.ToXml(), System.Security.Policy.CodeGroup.ToXml(), and System.Security.Policy.PolicyStatement.ToXml().