Terraria Decompiled: Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability
UpdateAvailability()
void Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability () inline
Definition at line 116 of file UIBestiaryFilteringOptionsGrid.cs.
        {
            int num;
            int num2;
            int num3;
            int num4;
            int num5;
            float num6;
            float num7;
            int num8;
            this.GetDisplaySettings(out num, out num2, out num3, out num4, out num5, out num6, out num7, out num8);
            this._container.RemoveAllChildren();
            this._filterButtons.Clear();
            this._areFiltersAvailable.Clear();
            int num9 = -1;
            int num10 = -1;
            for (int i = 0; i < this._filterer.AvailableFilters.Count; i++)
            {
                int num11 = i / num5;
                int num12 = i % num5;
                IBestiaryEntryFilter bestiaryEntryFilter = this._filterer.AvailableFilters[i];
                List<BestiaryEntry> list = this._filterAvailabilityTests[i];
                if (this.GetIsFilterAvailableForEntries(bestiaryEntryFilter, list))
                {
                    GroupOptionButton<int> groupOptionButton = new GroupOptionButton<int>(i, null, null, Color.White, null, 1f, 0.5f, 10f)
                    {
                        Width = new StyleDimension((float)num, 0f),
                        Height = new StyleDimension((float)num2, 0f),
                        HAlign = 0f,
                        VAlign = 0f,
                        Top = new StyleDimension(num7 + (float)(num11 * num4), 0f),
                        Left = new StyleDimension(num6 + (float)(num12 * num3), 0f)
                    };
                    groupOptionButton.OnLeftClick += this.ClickOption;
                    groupOptionButton.SetSnapPoint("Filters", i, null, null);
                    groupOptionButton.ShowHighlightWhenSelected = false;
                    this.AddOnHover(bestiaryEntryFilter, groupOptionButton);
                    this._container.Append(groupOptionButton);
                    UIElement image = bestiaryEntryFilter.GetImage();
                    if (image != null)
                    {
                        image.Left = new StyleDimension((float)num9, 0f);
                        image.Top = new StyleDimension((float)num10, 0f);
                        groupOptionButton.Append(image);
                    }
                    this._filterButtons.Add(groupOptionButton);
                }
                else
                {
                    this._filterer.ActiveFilters.Remove(bestiaryEntryFilter);
                    GroupOptionButton<int> groupOptionButton2 = new GroupOptionButton<int>(-2, null, null, Color.White, null, 1f, 0.5f, 10f)
                    {
                        Width = new StyleDimension((float)num, 0f),
                        Height = new StyleDimension((float)num2, 0f),
                        HAlign = 0f,
                        VAlign = 0f,
                        Top = new StyleDimension(num7 + (float)(num11 * num4), 0f),
                        Left = new StyleDimension(num6 + (float)(num12 * num3), 0f),
                        FadeFromBlack = 0.5f
                    };
                    groupOptionButton2.ShowHighlightWhenSelected = false;
                    groupOptionButton2.SetPadding(0f);
                    groupOptionButton2.SetSnapPoint("Filters", i, null, null);
                    Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Icon_Tags_Shadow", 1);
                    UIImageFramed uiimageFramed = new UIImageFramed(asset, asset.Frame(16, 5, 0, 4, 0, 0))
                    {
                        HAlign = 0.5f,
                        VAlign = 0.5f,
                        Color = Color.White * 0.2f
                    };
                    uiimageFramed.Left = new StyleDimension((float)num9, 0f);
                    uiimageFramed.Top = new StyleDimension((float)num10, 0f);
                    groupOptionButton2.Append(uiimageFramed);
                    this._filterButtons.Add(groupOptionButton2);
                    this._container.Append(groupOptionButton2);
                }
            }
            this.UpdateButtonSelections();
        }
References Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._areFiltersAvailable, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._container, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._filterAvailabilityTests, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._filterButtons, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid._filterer, Terraria.DataStructures.EntryFilterer< T, U >.ActiveFilters, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.AddOnHover(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.DataStructures.EntryFilterer< T, U >.AvailableFilters, System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.ClickOption(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetDisplaySettings(), Terraria.DataStructures.IEntryFilter< T >.GetImage(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.GetIsFilterAvailableForEntries(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, System.list, System.Collections.Generic.List< T >.Remove(), Terraria.UI.UIElement.RemoveAllChildren(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateButtonSelections(), Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents().