Terraria Decompiled: System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForNonArrayTypes
GetClrTypeFullNameForNonArrayTypes()
static string System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForNonArrayTypes (Type type) inline static private
Definition at line 470 of file FormatterServices.cs.
        {
            if (!type.IsGenericType)
            {
                return type.FullName;
            }
            Type[] genericArguments = type.GetGenericArguments();
            StringBuilder stringBuilder = new StringBuilder(type.GetGenericTypeDefinition().FullName).Append("[");
            foreach (Type type2 in genericArguments)
            {
                stringBuilder.Append("[").Append(FormatterServices.GetClrTypeFullName(type2)).Append(", ");
                bool flag;
                stringBuilder.Append(FormatterServices.GetClrAssemblyName(type2, out flag)).Append("],");
            }
            return stringBuilder.Remove(stringBuilder.Length - 1, 1).Append("]").ToString();
        }
References System.Text.StringBuilder.Append(), System.Type.FullName, System.Runtime.Serialization.FormatterServices.GetClrAssemblyName(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullName(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Type.IsGenericType, System.Text.StringBuilder.Remove(), and System.Text.StringBuilder.ToString().
Referenced by System.Runtime.Serialization.FormatterServices.GetClrTypeFullName().