Terraria Decompiled: System.Collections.Hashtable.GetObjectData
GetObjectData()
virtual void System.Collections.Hashtable.GetObjectData (SerializationInfo info, StreamingContext context) inline virtual
Implements System.Runtime.Serialization.ISerializable.
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 842 of file Hashtable.cs.
        {
            if (info == null)
            {
                throw new ArgumentNullException("info");
            }
            object syncRoot = this.SyncRoot;
            lock (syncRoot)
            {
                int version = this._version;
                info.AddValue("LoadFactor", this._loadFactor);
                info.AddValue("Version", this._version);
                IEqualityComparer keycomparer = this._keycomparer;
                if (keycomparer == null)
                {
                    info.AddValue("Comparer", null, typeof(IComparer));
                    info.AddValue("HashCodeProvider", null, typeof(IHashCodeProvider));
                }
                else if (keycomparer is CompatibleComparer)
                {
                    CompatibleComparer compatibleComparer = keycomparer as CompatibleComparer;
                    info.AddValue("Comparer", compatibleComparer.Comparer, typeof(IComparer));
                    info.AddValue("HashCodeProvider", compatibleComparer.HashCodeProvider, typeof(IHashCodeProvider));
                }
                else
                {
                    info.AddValue("KeyComparer", keycomparer, typeof(IEqualityComparer));
                }
                info.AddValue("HashSize", this._buckets.Length);
                object[] array = new object[this._count];
                object[] array2 = new object[this._count];
                this.CopyKeys(array, 0);
                this.CopyValues(array2, 0);
                info.AddValue("Keys", array, typeof(object[]));
                info.AddValue("Values", array2, typeof(object[]));
                if (this._version != version)
                {
                    throw new InvalidOperationException("Collection was modified; enumeration operation may not execute.");
                }
            }
        }
References System.Collections.Hashtable._buckets, System.Collections.Hashtable._count, System.Collections.Hashtable._keycomparer, System.Collections.Hashtable._loadFactor, System.Collections.Hashtable._version, System.Runtime.Serialization.SerializationInfo.AddValue(), System.array, System.Collections.CompatibleComparer.Comparer, System.Collections.Hashtable.CopyKeys(), System.Collections.Hashtable.CopyValues(), System.Collections.CompatibleComparer.HashCodeProvider, System.info, and System.Collections.Hashtable.SyncRoot.