Terraria Decompiled: System.Runtime.Serialization.FormatterServices.GetSerializableMembers
GetSerializableMembers() [1/3]
static MemberInfo[] System.Runtime.Serialization.FormatterServices.GetSerializableMembers (RuntimeType type) inline static private
Definition at line 31 of file FormatterServices.cs.
        {
            FieldInfo[] fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            int num = 0;
            for (int i = 0; i < fields.Length; i++)
            {
                if ((fields[i].Attributes & FieldAttributes.NotSerialized) != FieldAttributes.NotSerialized)
                {
                    num++;
                }
            }
            if (num != fields.Length)
            {
                FieldInfo[] array = new FieldInfo[num];
                num = 0;
                for (int j = 0; j < fields.Length; j++)
                {
                    if ((fields[j].Attributes & FieldAttributes.NotSerialized) != FieldAttributes.NotSerialized)
                    {
                        array[num] = fields[j];
                        num++;
                    }
                }
                return array;
            }
            return fields;
        }
References System.array, System.Reflection.Attributes, and System.RuntimeType.GetFields().
Referenced by System.Runtime.Serialization.FormatterServices.GetSerializableMembers(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo(), System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(), and System.Runtime.Serialization.ObjectCloneHelper.PrepareConstructorArgs().