Terraria Decompiled: System.Runtime.Serialization.FormatterServices.GetParentTypes
GetParentTypes()
static bool System.Runtime.Serialization.FormatterServices.GetParentTypes (RuntimeType parentType, out RuntimeType[] parentTypes, out int parentTypeCount) inline static private
Definition at line 124 of file FormatterServices.cs.
        {
            parentTypes = null;
            parentTypeCount = 0;
            bool flag = true;
            RuntimeType runtimeType = (RuntimeType)typeof(object);
            RuntimeType runtimeType2 = parentType;
            while (runtimeType2 != runtimeType)
            {
                if (runtimeType2 == null)
                {
                    throw new InvalidOperationException(string.Format("Type '{0}' of type '{1}' does not derive from System.Object", parentType, (parentType != null) ? parentType.GetType() : null));
                }
                if (!runtimeType2.IsInterface)
                {
                    string name = runtimeType2.Name;
                    int num = 0;
                    while (flag && num < parentTypeCount)
                    {
                        string name2 = parentTypes[num].Name;
                        if (name2.Length == name.Length && name2[0] == name[0] && name == name2)
{
                            flag = false;
                            break;
                        }
                        num++;
                    }
                    if (parentTypes == null || parentTypeCount == parentTypes.Length)
                    {
                        RuntimeType[] array = new RuntimeType[Math.Max(parentTypeCount * 2, 12)];
                        if (parentTypes != null)
{
                            Array.Copy(parentTypes, 0, array, 0, parentTypeCount);
                        }
                        parentTypes = array;
                    }
                    RuntimeType[] array2 = parentTypes;
                    int num2 = parentTypeCount;
                    parentTypeCount = num2 + 1;
                    array2[num2] = runtimeType2;
                }
                runtimeType2 = (RuntimeType)runtimeType2.BaseType;
            }
            return flag;
        }
References System.array, System.RuntimeType.BaseType, System.Array.Copy(), System.Format, System.RuntimeType.GetType(), System.Math.Max(), System.name, and System.RuntimeType.Name.
Referenced by System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers().