Terraria Decompiled: System.Collections.Hashtable.Insert
Insert()
void System.Collections.Hashtable.Insert (object key, object nvalue, bool add) inline private
Definition at line 655 of file Hashtable.cs.
        {
            if (key == null)
            {
                throw new ArgumentNullException("key", "Key cannot be null.");
            }
            if (this._count >= this._loadsize)
            {
                this.expand();
            }
            else if (this._occupancy > this._loadsize && this._count > 100)
            {
                this.rehash();
            }
            uint num2;
            uint num3;
            uint num = this.InitHash(key, this._buckets.Length, out num2, out num3);
            int num4 = 0;
            int num5 = -1;
            int num6 = (int)(num2 % (uint)this._buckets.Length);
            for (;;)
            {
                if (num5 == -1 && this._buckets[num6].key == this._buckets && this._buckets[num6].hash_coll < 0)
                {
                    num5 = num6;
                }
                if (this._buckets[num6].key == null || (this._buckets[num6].key == this._buckets && ((long)this._buckets[num6].hash_coll & (long)((ulong)(-2147483648))) == 0L))
                {
                    break;
                }
                if ((long)(this._buckets[num6].hash_coll & 2147483647) == (long)((ulong)num) && this.KeyEquals(this._buckets[num6].key, key))
                {
                    goto Block_12;
                }
                if (num5 == -1 && this._buckets[num6].hash_coll >= 0)
                {
                    Hashtable.bucket[] buckets = this._buckets;
                    int num7 = num6;
                    buckets[num7].hash_coll = buckets[num7].hash_coll | int.MinValue;
                    this._occupancy++;
                }
                num6 = (int)(((long)num6 + (long)((ulong)num3)) % (long)((ulong)this._buckets.Length));
                if (++num4 >= this._buckets.Length)
                {
                    goto Block_16;
                }
            }
            if (num5 != -1)
            {
                num6 = num5;
            }
            this._isWriterInProgress = true;
            this._buckets[num6].val = nvalue;
            this._buckets[num6].key = key;
            Hashtable.bucket[] buckets2 = this._buckets;
            int num8 = num6;
            buckets2[num8].hash_coll = buckets2[num8].hash_coll | (int)num;
            this._count++;
            this.UpdateVersion();
            this._isWriterInProgress = false;
            return;
            Block_12:
            if (add)
            {
                throw new ArgumentException(SR.Format("Item has already been added. Key in dictionary: '{0}'  Key being added: '{1}'", this._buckets[num6].key, key));
            }
            this._isWriterInProgress = true;
            this._buckets[num6].val = nvalue;
            this.UpdateVersion();
            this._isWriterInProgress = false;
            return;
            Block_16:
            if (num5 != -1)
            {
                this._isWriterInProgress = true;
                this._buckets[num5].val = nvalue;
                this._buckets[num5].key = key;
                Hashtable.bucket[] buckets3 = this._buckets;
                int num9 = num5;
                buckets3[num9].hash_coll = buckets3[num9].hash_coll | (int)num;
                this._count++;
                this.UpdateVersion();
                this._isWriterInProgress = false;
                return;
            }
            throw new InvalidOperationException("Hashtable insert failed. Load factor too high. The most common cause is multiple threads writing to the Hashtable simultaneously.");
        }
References System.Collections.Hashtable._buckets, System.Collections.Hashtable._count, System.Collections.Hashtable._loadsize, System.Collections.Hashtable._occupancy, System.Collections.Hashtable.expand(), SR.Format(), System.Collections.Hashtable.InitHash(), int, System.key, System.Collections.Hashtable.KeyEquals(), System.L, long, System.Collections.Hashtable.rehash(), and System.Collections.Hashtable.UpdateVersion().