Terraria Decompiled: System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForArray
GetClrTypeFullNameForArray()
static string System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForArray (Type type) inline static private
Definition at line 453 of file FormatterServices.cs.
        {
            int arrayRank = type.GetArrayRank();
            if (arrayRank == 1)
            {
                return string.Format(CultureInfo.InvariantCulture, "{0}{1}", FormatterServices.GetClrTypeFullName(type.GetElementType()), "[]");
            }
            StringBuilder stringBuilder = new StringBuilder(FormatterServices.GetClrTypeFullName(type.GetElementType())).Append("[");
            for (int i = 1; i < arrayRank; i++)
            {
                stringBuilder.Append(",");
            }
            stringBuilder.Append("]");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Type.GetArrayRank(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullName(), System.Type.GetElementType(), System.Globalization.CultureInfo.InvariantCulture, and System.Text.StringBuilder.ToString().
Referenced by System.Runtime.Serialization.FormatterServices.GetClrTypeFullName().