Terraria Decompiled: System.Collections.Hashtable.OnDeserialization
OnDeserialization()
virtual void System.Collections.Hashtable.OnDeserialization (object sender) inline virtual
Implements System.Runtime.Serialization.IDeserializationCallback.
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 885 of file Hashtable.cs.
        {
            if (this._buckets != null)
            {
                return;
            }
            SerializationInfo serializationInfo;
            Hashtable.SerializationInfoTable.TryGetValue(this, out serializationInfo);
            if (serializationInfo == null)
            {
                throw new SerializationException("OnDeserialization method was called while the object was not being deserialized.");
            }
            int num = 0;
            IComparer comparer = null;
            IHashCodeProvider hashCodeProvider = null;
            object[] array = null;
            object[] array2 = null;
            SerializationInfoEnumerator enumerator = serializationInfo.GetEnumerator();
            while (enumerator.MoveNext())
            {
                string name = enumerator.Name;
                uint num2 = <PrivateImplementationDetails>.ComputeStringHash(name);
                if (num2 <= 1613443821U)
                {
                    if (num2 != 891156946U)
                    {
                        if (num2 != 1228509323U)
{
                            if (num2 == 1613443821U)
{
                                if (name == "Keys")
{
                                    array = (object[])serializationInfo.GetValue("Keys", typeof(object[]));
                                }
                            }
                        }
                        else if (name == "KeyComparer")
{
                            this._keycomparer = (IEqualityComparer)serializationInfo.GetValue("KeyComparer", typeof(IEqualityComparer));
                        }
                    }
                    else if (name == "Comparer")
                    {
                        comparer = (IComparer)serializationInfo.GetValue("Comparer", typeof(IComparer));
                    }
                }
                else if (num2 <= 2484309429U)
                {
                    if (num2 != 2370642523U)
                    {
                        if (num2 == 2484309429U)
{
                            if (name == "HashCodeProvider")
{
                                hashCodeProvider = (IHashCodeProvider)serializationInfo.GetValue("HashCodeProvider", typeof(IHashCodeProvider));
                            }
                        }
                    }
                    else if (name == "Values")
                    {
                        array2 = (object[])serializationInfo.GetValue("Values", typeof(object[]));
                    }
                }
                else if (num2 != 3356145248U)
                {
                    if (num2 == 3483216242U)
                    {
                        if (name == "LoadFactor")
{
                            this._loadFactor = serializationInfo.GetSingle("LoadFactor");
                        }
                    }
                }
                else if (name == "HashSize")
                {
                    num = serializationInfo.GetInt32("HashSize");
                }
            }
            this._loadsize = (int)(this._loadFactor * (float)num);
            if (this._keycomparer == null && (comparer != null || hashCodeProvider != null))
            {
                this._keycomparer = new CompatibleComparer(hashCodeProvider, comparer);
            }
            this._buckets = new Hashtable.bucket[num];
            if (array == null)
            {
                throw new SerializationException("The keys for this dictionary are missing.");
            }
            if (array2 == null)
            {
                throw new SerializationException("The values for this dictionary are missing.");
            }
            if (array.Length != array2.Length)
            {
                throw new SerializationException("The keys and values arrays have different sizes.");
            }
            for (int i = 0; i < array.Length; i++)
            {
                if (array[i] == null)
                {
                    throw new SerializationException("One of the serialized keys is null.");
                }
                this.Insert(array[i], array2[i], true);
            }
            this._version = serializationInfo.GetInt32("Version");
            Hashtable.SerializationInfoTable.Remove(this);
        }
References System.Collections.Hashtable._buckets, System.Collections.Hashtable._keycomparer, System.Collections.Hashtable._loadFactor, System.array, System.Collections.Hashtable.comparer, System.Runtime.Serialization.SerializationInfo.GetEnumerator(), System.Runtime.Serialization.SerializationInfo.GetInt32(), System.Runtime.Serialization.SerializationInfo.GetSingle(), System.Runtime.Serialization.SerializationInfo.GetValue(), System.Insert, int, System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext(), System.name, System.Runtime.Serialization.SerializationInfoEnumerator.Name, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.Remove(), System.Collections.Hashtable.SerializationInfoTable, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >.TryGetValue(), and System.U.