Terraria Decompiled: System.Runtime.Serialization.FormatterServices.PopulateObjectMembers
PopulateObjectMembers()
static object System.Runtime.Serialization.FormatterServices.PopulateObjectMembers (object obj, MemberInfo[] members, object[] data) inline static
Definition at line 307 of file FormatterServices.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj");
            }
            if (members == null)
            {
                throw new ArgumentNullException("members");
            }
            if (data == null)
            {
                throw new ArgumentNullException("data");
            }
            if (members.Length != data.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("Parameters 'members' and 'data' must have the same length."));
            }
            for (int i = 0; i < members.Length; i++)
            {
                MemberInfo memberInfo = members[i];
                if (memberInfo == null)
                {
                    throw new ArgumentNullException("members", Environment.GetResourceString("Member at position {0} was null.", new object[] { i }));
                }
                if (data[i] != null)
                {
                    if (memberInfo.MemberType != MemberTypes.Field)
                    {
                        throw new SerializationException(Environment.GetResourceString("Only FieldInfo, PropertyInfo, and SerializationMemberInfo are recognized."));
                    }
                    FormatterServices.SerializationSetValue(memberInfo, obj, data[i]);
                }
            }
            return obj;
        }
References System.Environment.GetResourceString(), System.Reflection.MemberInfo.MemberType, System.obj, and System.Runtime.Serialization.FormatterServices.SerializationSetValue().
Referenced by System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.PopulateObjectMembers().