Terraria Decompiled: System.Collections.Hashtable.ContainsKey
ContainsKey()
virtual bool System.Collections.Hashtable.ContainsKey (object key) inline virtual
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 314 of file Hashtable.cs.
        {
            if (key == null)
            {
                throw new ArgumentNullException("key", "Key cannot be null.");
            }
            Hashtable.bucket[] buckets = this._buckets;
            uint num2;
            uint num3;
            uint num = this.InitHash(key, buckets.Length, out num2, out num3);
            int num4 = 0;
            int num5 = (int)(num2 % (uint)buckets.Length);
            for (;;)
            {
                Hashtable.bucket bucket = buckets[num5];
                if (bucket.key == null)
                {
                    break;
                }
                if ((long)(bucket.hash_coll & 2147483647) == (long)((ulong)num) && this.KeyEquals(bucket.key, key))
                {
                    return true;
                }
                num5 = (int)(((long)num5 + (long)((ulong)num3)) % (long)((ulong)buckets.Length));
                if (bucket.hash_coll >= 0 || ++num4 >= buckets.Length)
                {
                    return false;
                }
            }
            return false;
        }
References System.Collections.Hashtable._buckets, System.Collections.Hashtable.bucket.hash_coll, System.Collections.Hashtable.InitHash(), int, System.Collections.Hashtable.bucket.key, System.key, System.Collections.Hashtable.KeyEquals(), and long.
Referenced by System.Security.Policy.NetCodeGroup.AddConnectAccess(), System.Collections.Hashtable.Contains(), System.Collections.Hashtable.SyncHashtable.ContainsKey(), System.Runtime.Remoting.ChannelData.CopyFrom(), System.Runtime.Remoting.ProviderData.CopyFrom(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetAssemblyId(), System.Reflection.Emit.TypeBuilderInstantiation.GetConstructor(), System.Reflection.Emit.TypeBuilderInstantiation.GetField(), System.Reflection.Emit.TypeBuilderInstantiation.GetMethod(), System.Runtime.Remoting.Channels.CrossAppDomainSink.GetSink(), System.Runtime.Remoting.RemotingConfiguration.IsActivationAllowed(), System.Runtime.Remoting.Lifetime.ClientSponsor.Register(), System.Runtime.Remoting.RemotingConfiguration.RegisterActivatedClientType(), System.Runtime.Remoting.RemotingServices.RegisterServerIdentity(), System.Runtime.Remoting.RemotingConfiguration.RegisterWellKnownClientType(), and System.Runtime.Remoting.Lifetime.ClientSponsor.Unregister().