Terraria Decompiled: System.Runtime.Serialization.FormatterServices.SerializationSetValue
SerializationSetValue()
static void System.Runtime.Serialization.FormatterServices.SerializationSetValue (MemberInfo fi, object target, object value) inline static package
Definition at line 287 of file FormatterServices.cs.
        {
            RtFieldInfo rtFieldInfo = fi as RtFieldInfo;
            if (rtFieldInfo != null)
            {
                rtFieldInfo.CheckConsistency(target);
                rtFieldInfo.UnsafeSetValue(target, value, BindingFlags.Default, FormatterServices.s_binder, null);
                return;
            }
            SerializationFieldInfo serializationFieldInfo = fi as SerializationFieldInfo;
            if (serializationFieldInfo != null)
            {
                serializationFieldInfo.InternalSetValue(target, value, BindingFlags.Default, FormatterServices.s_binder, null);
                return;
            }
            throw new ArgumentException(Environment.GetResourceString("The FieldInfo object is not valid."));
        }
References System.Reflection.RtFieldInfo.CheckConsistency(), System.Environment.GetResourceString(), System.Runtime.Serialization.SerializationFieldInfo.InternalSetValue(), System.Runtime.Serialization.FormatterServices.s_binder, System.Reflection.RtFieldInfo.UnsafeSetValue(), and System.value.
Referenced by System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup(), System.Runtime.Serialization.FormatterServices.PopulateObjectMembers(), System.Runtime.Serialization.ObjectCloneHelper.PrepareConstructorArgs(), and System.Runtime.Serialization.Formatters.InternalST.SerializationSetValue().