Terraria Decompiled: System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject
GetSafeUninitializedObject()
static object System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject (Type type) inline static
Definition at line 229 of file FormatterServices.cs.
        {
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }
            if (!(type is RuntimeType))
            {
                throw new SerializationException(Environment.GetResourceString("Only system-provided types can be passed to the GetUninitializedObject method. '{0}' is not a valid instance of a type.", new object[] { type.ToString() }));
            }
            if (type == typeof(ConstructionCall) || type == typeof(LogicalCallContext) || type == typeof(SynchronizationAttribute))
            {
                return FormatterServices.nativeGetUninitializedObject((RuntimeType)type);
            }
            object obj;
            try
            {
                obj = FormatterServices.nativeGetSafeUninitializedObject((RuntimeType)type);
            }
            catch (SecurityException ex)
            {
                throw new SerializationException(Environment.GetResourceString("Because of security restrictions, the type {0} cannot be accessed.", new object[] { type.FullName }), ex);
            }
            return obj;
        }
References System.Environment.GetResourceString(), System.Runtime.Serialization.FormatterServices.nativeGetSafeUninitializedObject(), System.Runtime.Serialization.FormatterServices.nativeGetUninitializedObject(), and System.obj.
Referenced by FullSerializer.fsMetaType.CreateInstance(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject().