Terraria Decompiled: System.Collections.Hashtable.Add
Add()
virtual void System.Collections.Hashtable.Add (object key, object value) inline virtual
Implements System.Collections.IDictionary.
Reimplemented in System.Collections.Hashtable.SyncHashtable.
Definition at line 261 of file Hashtable.cs.
        {
            this.Insert(key, value, true);
        }
References System.Insert, and System.value.
Referenced by System.Collections.DictionaryBase.Add(), System.Collections.Hashtable.SyncHashtable.Add(), System.Security.Policy.NetCodeGroup.AddConnectAccess(), System.Runtime.Serialization.SurrogateSelector.AddSurrogate(), System.Security.SecurityManager.Decode(), Mono.Security.StrongNameManager.Element.Element(), System.Security.Policy.PolicyLevel.FromXml(), System.CurrentSystemTimeZone.GetCachedDaylightChanges(), System.Resources.ResourceSet.GetCaseInsensitiveObjectInternal(), Mono.Security.StrongNameManager.LoadMapping(), Mono.Security.StrongNameManager.LoadVerificationSettings(), System.Runtime.Remoting.ConfigHandler.ReadChannel(), System.Runtime.Remoting.ConfigHandler.ReadProvider(), System.Resources.ResourceSet.ReadResources(), System.Runtime.Remoting.Lifetime.ClientSponsor.Register(), System.Runtime.Remoting.RemotingConfiguration.RegisterActivatedServiceType(), System.Runtime.InteropServices.ExtensibleClassFactory.RegisterObjectCreationCallback(), System.Collections.DictionaryBase.Remove(), System.Security.Policy.PolicyLevel.ToXml(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteObject().