Terraria Decompiled: System.Text.Encoding.GetEncoding
GetEncoding() [3/4]
static Encoding System.Text.Encoding.GetEncoding (string name) inline static
Definition at line 326 of file Encoding.cs.
        {
            Encoding encodingFromProvider = EncodingProvider.GetEncodingFromProvider(name);
            if (encodingFromProvider != null)
            {
                return encodingFromProvider;
            }
            return Encoding.GetEncoding(EncodingTable.GetCodePageFromName(name));
        }
References System.Globalization.EncodingTable.GetCodePageFromName(), System.Text.Encoding.GetEncoding(), System.Text.EncodingProvider.GetEncodingFromProvider(), and System.name.