Terraria Decompiled: System.Text.Encoding.GetEncoding
GetEncoding() [1/4]
static Encoding System.Text.Encoding.GetEncoding (int codepage) inline static
Definition at line 184 of file Encoding.cs.
        {
            Encoding encoding = EncodingProvider.GetEncodingFromProvider(codepage);
            if (encoding != null)
            {
                return encoding;
            }
            if (codepage < 0 || codepage > 65535)
            {
                throw new ArgumentOutOfRangeException("codepage", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[] { 0, 65535 }));
            }
            if (Encoding.encodings != null)
            {
                Encoding.encodings.TryGetValue(codepage, out encoding);
            }
            if (encoding == null)
            {
                object internalSyncObject = Encoding.InternalSyncObject;
                lock (internalSyncObject)
                {
                    if (Encoding.encodings == null)
                    {
                        Encoding.encodings = new Dictionary<int, Encoding>();
                    }
                    if (Encoding.encodings.TryGetValue(codepage, out encoding))
                    {
                        return encoding;
                    }
                    if (codepage <= 1201)
                    {
                        if (codepage <= 3)
{
                            if (codepage == 0)
{
                                encoding = Encoding.Default;
                                goto IL_0233;
                            }
                            if (codepage - 1 > 2)
{
                                goto IL_01B0;
                            }
                        }
                        else if (codepage != 42)
{
                            if (codepage == 1200)
{
                                encoding = Encoding.Unicode;
                                goto IL_0233;
                            }
                            if (codepage != 1201)
{
                                goto IL_01B0;
                            }
                            encoding = Encoding.BigEndianUnicode;
                            goto IL_0233;
                        }
                        throw new ArgumentException(Environment.GetResourceString("{0} is not a supported code page.", new object[] { codepage }), "codepage");
                    }
                    if (codepage <= 20127)
                    {
                        if (codepage == 12000)
{
                            encoding = Encoding.UTF32;
                            goto IL_0233;
                        }
                        if (codepage == 12001)
{
                            encoding = new UTF32Encoding(true, true);
                            goto IL_0233;
                        }
                        if (codepage == 20127)
{
                            encoding = Encoding.ASCII;
                            goto IL_0233;
                        }
                    }
                    else
                    {
                        if (codepage == 28591)
{
                            encoding = Encoding.Latin1;
                            goto IL_0233;
                        }
                        if (codepage == 65000)
{
                            encoding = Encoding.UTF7;
                            goto IL_0233;
                        }
                        if (codepage == 65001)
{
                            encoding = Encoding.UTF8;
                            goto IL_0233;
                        }
                    }
                    IL_01B0:
                    if (EncodingTable.GetCodePageDataItem(codepage) == null)
                    {
                        throw new NotSupportedException(Environment.GetResourceString("No data is available for encoding {0}. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.", new object[] { codepage }));
                    }
                    if (codepage != 12000)
                    {
                        if (codepage != 12001)
{
                            encoding = (Encoding)EncodingHelper.InvokeI18N("GetEncoding", new object[] { codepage });
                            if (encoding == null)
{
                                throw new NotSupportedException(string.Format("Encoding {0} data could not be found. Make sure you have correct international codeset assembly installed and enabled.", codepage));
                            }
                        }
                        else
{
                            encoding = new UTF32Encoding(true, true);
                        }
                    }
                    else
                    {
                        encoding = Encoding.UTF32;
                    }
                    IL_0233:
                    Encoding.encodings.Add(codepage, encoding);
                }
                return encoding;
            }
            return encoding;
        }
References System.Text.Encoding.ASCII, System.Text.Encoding.BigEndianUnicode, System.Text.Encoding.Default, System.Text.Encoding.Encoding(), System.Text.Encoding.encodings, System.Format, System.Globalization.EncodingTable.GetCodePageDataItem(), System.Text.EncodingProvider.GetEncodingFromProvider(), System.Environment.GetResourceString(), System.Text.Encoding.InternalSyncObject, System.Text.EncodingHelper.InvokeI18N(), System.Text.Encoding.Latin1, System.Text.Encoding.Unicode, System.Text.Encoding.UTF32, System.Text.Encoding.UTF7, and System.Text.Encoding.UTF8.
Referenced by Ionic.Zip.ZipInputStream._Init(), System.Console.Console(), System.Security.Util.Parser.DetermineFormat(), System.Text.EncodingHelper.GetDefaultEncoding(), System.Text.EncodingInfo.GetEncoding(), System.Text.Encoding.GetEncoding(), System.Text.Encoding.GetEncoding(), System.Text.Encoding.GetEncoding(), System.Text.EncodingProvider.GetEncodingFromProvider(), System.Text.EncodingProvider.GetEncodingFromProvider(), System.Text.EncodingProvider.GetEncodingFromProvider(), System.Text.EncodingProvider.GetEncodingFromProvider(), Mono.DataConverter.PackOne(), Mono.DataConverter.Unpack(), Ionic.Zip.ZipEntry.ZipEntry(), Ionic.Zip.ZipOutputStream.ZipOutputStream(), and Ionic.Zip.ZipOutputStream.ZipOutputStream().