Terraria Decompiled: System.Text.Encoding.SetDefaultFallbacks
SetDefaultFallbacks()
virtual void System.Text.Encoding.SetDefaultFallbacks () inline package virtual
Reimplemented in System.Text.ASCIIEncoding, System.Text.UnicodeEncoding, System.Text.UTF32Encoding, System.Text.UTF7Encoding, and System.Text.UTF8Encoding.
Definition at line 51 of file Encoding.cs.
        {
            this.encoderFallback = new InternalEncoderBestFitFallback(this);
            this.decoderFallback = new InternalDecoderBestFitFallback(this);
        }
Referenced by System.Text.Encoding.DeserializeEncoding(), System.Text.Encoding.Encoding(), and System.Text.Encoding.OnDeserialized().