Terraria Decompiled: System.Text.Encoding.GetString
GetString() [1/4]
unsafe string System.Text.Encoding.GetString (byte * bytes, int byteCount) inline
Definition at line 858 of file Encoding.cs.
        {
            if (bytes == null)
            {
                throw new ArgumentNullException("bytes", Environment.GetResourceString("Array cannot be null."));
            }
            if (byteCount < 0)
            {
                throw new ArgumentOutOfRangeException("byteCount", Environment.GetResourceString("Non-negative number required."));
            }
            return string.CreateStringFromEncoding(bytes, byteCount, this);
        }
References System.Environment.GetResourceString().
Referenced by System.Resources.ResourceReader.AllocateStringForNameIndex(), Microsoft.Xna.Framework.Audio.AudioEngine.AudioEngine(), Terraria.Social.WeGame.IPCMessage.BuildFrom(), Steamworks.InteropHelp.ByteArrayToStringUTF8(), System.Security.PermissionSet.ConvertPermissionSet(), System.Security.Permissions.PermissionSetAttribute.CreatePermissionSet(), System.String.CreateStringForSByteConstructor(), System.String.Ctor(), System.Security.SecurityManager.Decode(), Microsoft.Win32.RegistryKey.DecodeString(), Ionic.Zip.ZipEntry.GetEncodedFileNameBytes(), Ionic.Zip.ZipOutput.GetEncoding(), Steamworks.gameserveritem_t.GetGameDescription(), Steamworks.gameserveritem_t.GetGameDir(), Steamworks.gameserveritem_t.GetGameTags(), Steamworks.gameserveritem_t.GetMap(), Steamworks.gameserveritem_t.GetServerName(), System.TermInfoReader.GetString(), System.Globalization.CultureData.idx2string(), Terraria.Main.InputTextSign(), Terraria.IO.FavoritesFile.Load(), UTF8Marshaler.MarshalNativeToManaged(), System.Security.PermissionSet.ProcessAttribute(), Steamworks.InteropHelp.PtrToStringUTF8(), Ionic.Zip.ZipEntry.ReadHeader(), Interop.Sys.ReadLink(), NVorbis.StreamDecoder.ReadString(), Ionic.Zlib.ZlibBaseStream.ReadZeroTerminatedString(), Ionic.Zip.ZipFile.ReadZipFileComment(), System.Reflection.Emit.CustomAttributeBuilder.string_from_bytes(), Ionic.Zip.SharedUtilities.StringFromBuffer(), Mono.Security.ASN1Convert.ToDateTime(), and System.TimeZoneInfo.TZif_ParseRaw().