Terraria Decompiled: System.Text.Encoding.GetDecoder
GetDecoder()
virtual Decoder System.Text.Encoding.GetDecoder () inline virtual
Reimplemented in System.Text.ASCIIEncoding, System.Text.EncodingNLS, System.Text.UnicodeEncoding, System.Text.UTF32Encoding, System.Text.UTF7Encoding, and System.Text.UTF8Encoding.
Definition at line 920 of file Encoding.cs.
        {
            return new Encoding.DefaultDecoder(this);
        }
Referenced by System.IO.BinaryReader.BinaryReader(), System.IO.StreamReader.DetectEncoding(), System.IO.StreamReader.DiscardBufferedData(), and System.IO.StreamReader.Init().