Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SandySurface
BiomeRoom_SandySurface()
void Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SandySurface (UnifiedRandom genRand, ref List< int > heightsToSkip, int tileX, int tileY, Tile tile) inline
Definition at line 256 of file BiomeDungeonRoom.cs.
        {
            if (!Main.tile[tileX, tileY - 1].active() && tile.active() && tile.type == 396)
            {
                if (WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(tileX, tileY))
                {
                    DungeonUtils.ChangeTileType(tile, 397, false, -1);
                }
                else
                {
                    DungeonUtils.ChangeTileType(tile, 53, false, -1);
                }
                for (int i = 0; i < 5 + genRand.Next(4); i++)
                {
                    int num = tileY + i;
                    Tile tile2 = Main.tile[tileX, num];
                    if (tile2.active() && tile2.type == 396)
                    {
                        heightsToSkip.Add(num);
                        tile2.liquid = 0;
                        if (WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(tileX, num))
{
                            DungeonUtils.ChangeTileType(tile2, 397, false, -1);
                        }
                        else
{
                            DungeonUtils.ChangeTileType(tile2, 53, false, -1);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_FinishRoom().