Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_FinishRoom
BiomeRoom_FinishRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_FinishRoom (UnifiedRandom genRand, int outerRoomLeft, int outerRoomRight, int outerRoomTop, int outerRoomBottom, bool treatAsSurface = false) inline
Definition at line 140 of file BiomeDungeonRoom.cs.
        {
            List<int> list = new List<int>();
            for (int i = outerRoomLeft; i < outerRoomRight; i++)
            {
                list.Clear();
                int num = i;
                for (int j = outerRoomTop; j < outerRoomBottom; j++)
                {
                    int num2 = j;
                    Tile tile = Main.tile[num, num2];
                    if (list.Contains(num2))
                    {
                        list.Remove(num2);
                    }
                    else if (this.InnerBounds.Contains(num, num2))
                    {
                        switch (this.settings.StyleData.Style)
{
                        default:
                            if (tile.liquid > 0)
{
                                tile.liquidType(0);
                            }
                            break;
                        case 2:
                            if (treatAsSurface)
{
                                this.BiomeRoom_SnowySurface(genRand, ref list, num, num2, tile);
                            }
                            if (tile.liquid > 0)
{
                                tile.liquidType(0);
                            }
                            break;
                        case 3:
                            if (treatAsSurface)
{
                                this.BiomeRoom_SandySurface(genRand, ref list, num, num2, tile);
                            }
                            if (tile.liquid > 0)
{
                                tile.liquidType(1);
                            }
                            break;
                        case 4:
                            if (treatAsSurface)
{
                                this.BiomeRoom_GrassySurface(genRand, ref list, num, num2, tile, 25, 23);
                            }
                            if (tile.liquid > 0)
{
                                tile.liquidType(0);
                            }
                            break;
                        case 5:
                            if (treatAsSurface)
{
                                this.BiomeRoom_GrassySurface(genRand, ref list, num, num2, tile, 203, 199);
                            }
                            if (tile.liquid > 0)
{
                                tile.liquidType(0);
                            }
                            break;
                        case 6:
                            if (treatAsSurface)
{
                                this.BiomeRoom_GrassySurface(genRand, ref list, num, num2, tile, 117, 109);
                            }
                            if (tile.liquid > 0)
{
                                tile.liquidType(0);
                            }
                            break;
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_GrassySurface(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SandySurface(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SnowySurface(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Contains(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.Tile.liquid, Terraria.Tile.liquidType(), System.list, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, and Terraria.Main.tile.