Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_AddHallwaySpace
BiomeRoom_AddHallwaySpace()
void Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_AddHallwaySpace (Vector2 position, int edgeLeft, int edgeRight, int edgeTop, int edgeBottom, int shapeOffset, ushort wallType, int wallPaint, bool generating) inline
Definition at line 111 of file BiomeDungeonRoom.cs.
        {
            int num = (edgeTop + edgeBottom) / 2 - 3;
            int num2 = (edgeTop + edgeBottom) / 2 + 3;
            for (int i = edgeLeft; i < edgeRight; i++)
            {
                int num3 = i;
                for (int j = num; j < num2; j++)
                {
                    int num4 = j;
                    Tile tile = Main.tile[num3, num4];
                    if (!generating && this._innerShapeData != null)
                    {
                        this._innerShapeData.Add(num3 - (int)position.X + shapeOffset, num4 - (int)position.Y + shapeOffset);
                        this._outerShapeData.Add(num3 - (int)position.X + shapeOffset, num4 - (int)position.Y + shapeOffset);
                    }
                    else
                    {
                        tile.active(false);
                        if (tile.wall != wallType)
{
                            DungeonUtils.ChangeWallType(tile, wallType, false, wallPaint);
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom._innerShapeData, Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom._outerShapeData, Terraria.Tile.active(), Terraria.WorldBuilding.ShapeData.Add(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeWallType(), int, Terraria.Main.tile, Terraria.Tile.wall, and Microsoft.Xna.Framework.Vector2.Y.