Terraria Decompiled: System.Security.Permissions.UIPermission.IsSubsetOf
IsSubsetOf()
override bool System.Security.Permissions.UIPermission.IsSubsetOf (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 130 of file UIPermission.cs.
        {
            UIPermission uipermission = this.Cast(target);
            if (uipermission == null)
            {
                return this.IsEmpty(this._window, this._clipboard);
            }
            return uipermission.IsUnrestricted() || (this._window <= uipermission._window && this._clipboard <= uipermission._clipboard);
        }
References System.Security.Permissions.UIPermission._clipboard, System.Security.Permissions.UIPermission._window, System.Security.Permissions.UIPermission.Cast(), System.Security.Permissions.UIPermission.IsEmpty(), and System.Security.Permissions.UIPermission.IsUnrestricted().