Terraria Decompiled: System.Security.Permissions.UIPermission.FromXml
FromXml()
override void System.Security.Permissions.UIPermission.FromXml (SecurityElement esd) inline
Implements System.Security.ISecurityEncodable.
Definition at line 85 of file UIPermission.cs.
        {
            CodeAccessPermission.CheckSecurityElement(esd, "esd", 1, 1);
            if (CodeAccessPermission.IsUnrestricted(esd))
            {
                this._window = UIPermissionWindow.AllWindows;
                this._clipboard = UIPermissionClipboard.AllClipboard;
                return;
            }
            string text = esd.Attribute("Window");
            if (text == null)
            {
                this._window = UIPermissionWindow.NoWindows;
            }
            else
            {
                this._window = (UIPermissionWindow)Enum.Parse(typeof(UIPermissionWindow), text);
            }
            string text2 = esd.Attribute("Clipboard");
            if (text2 == null)
            {
                this._clipboard = UIPermissionClipboard.NoClipboard;
                return;
            }
            this._clipboard = (UIPermissionClipboard)Enum.Parse(typeof(UIPermissionClipboard), text2);
        }
References System.Security.SecurityElement.Attribute(), System.Security.CodeAccessPermission.CheckSecurityElement(), System.Security.CodeAccessPermission.IsUnrestricted(), System.Enum.Parse(), and System.text.