Terraria Decompiled: MonoGame.Utilities.FileHelpers.NormalizeFilePathSeparators
NormalizeFilePathSeparators()
static string MonoGame.Utilities.FileHelpers.NormalizeFilePathSeparators (string name) inline static
Definition at line 10 of file FileHelpers.cs.
        {
            return name.Replace(FileHelpers.NotSeparator, FileHelpers.Separator);
        }
References System.name, MonoGame.Utilities.FileHelpers.NotSeparator, and MonoGame.Utilities.FileHelpers.Separator.
Referenced by Microsoft.Xna.Framework.Content.ContentManager.CheckRawExtensions(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), Microsoft.Xna.Framework.TitleContainer.ReadToPointer(), MonoGame.Utilities.FileHelpers.ResolveRelativePath(), and Microsoft.Xna.Framework.Audio.WaveBank.WaveBank().