Terraria Decompiled: MonoGame.Utilities.FileHelpers.ResolveRelativePath
ResolveRelativePath()
static string MonoGame.Utilities.FileHelpers.ResolveRelativePath (string filePath, string relativeFile) inline static
Definition at line 16 of file FileHelpers.cs.
        {
            filePath = filePath.Replace(FileHelpers.BackwardSlash, FileHelpers.ForwardSlash);
            while (filePath.Contains("//"))
            {
                filePath = filePath.Replace("//", "/");
            }
            bool flag = filePath.StartsWith(FileHelpers.ForwardSlashString);
            if (!flag)
            {
                filePath = FileHelpers.ForwardSlashString + filePath;
            }
            string text = new Uri(new Uri("file://" + filePath), relativeFile).LocalPath;
            if (!flag && text.StartsWith("/"))
            {
                text = text.Substring(1);
            }
            return FileHelpers.NormalizeFilePathSeparators(text);
        }
References MonoGame.Utilities.FileHelpers.BackwardSlash, MonoGame.Utilities.FileHelpers.ForwardSlash, MonoGame.Utilities.FileHelpers.ForwardSlashString, MonoGame.Utilities.FileHelpers.NormalizeFilePathSeparators(), and System.text.
Referenced by Microsoft.Xna.Framework.Content.SongReader.Read(), Microsoft.Xna.Framework.Content.VideoReader.Read(), and Microsoft.Xna.Framework.Content.ContentReader.ReadExternalReference< T >().