Terraria Decompiled: Mono.Globalization.Unicode.SortKeyBuffer.GetResult
GetResult()
SortKey Mono.Globalization.Unicode.SortKeyBuffer.GetResult () inline
Definition at line 182 of file SortKeyBuffer.cs.
        {
            if (this.source.Length == 0)
            {
                return new SortKey(this.lcid, this.source, new byte[0], this.options, 0, 0, 0, 0, 0, 0, 0, 0);
            }
            if (this.frenchSort && !this.frenchSorted && this.l2b != null)
            {
                int num = 0;
                while (num < this.l2b.Length && this.l2b[num] != 0)
                {
                    num++;
                }
                Array.Reverse<byte>(this.l2b, 0, num);
                this.frenchSorted = true;
            }
            this.l2 = this.GetOptimizedLength(this.l2b, this.l2, 2);
            this.l3 = this.GetOptimizedLength(this.l3b, this.l3, 2);
            bool flag = this.l4s > 0;
            this.l4s = this.GetOptimizedLength(this.l4sb, this.l4s, 228);
            this.l4t = this.GetOptimizedLength(this.l4tb, this.l4t, 3);
            this.l4k = this.GetOptimizedLength(this.l4kb, this.l4k, 228);
            this.l4w = this.GetOptimizedLength(this.l4wb, this.l4w, 228);
            this.l5 = this.GetOptimizedLength(this.l5b, this.l5, 2);
            int num2 = this.l1 + this.l2 + this.l3 + this.l5 + 5;
            int num3 = this.l4s + this.l4t + this.l4k + this.l4w;
            if (flag)
            {
                num2 += num3 + 4;
            }
            byte[] array = new byte[num2];
            Array.Copy(this.l1b, array, this.l1);
            array[this.l1] = 1;
            int num4 = this.l1 + 1;
            if (this.l2 > 0)
            {
                Array.Copy(this.l2b, 0, array, num4, this.l2);
            }
            num4 += this.l2;
            array[num4++] = 1;
            if (this.l3 > 0)
            {
                Array.Copy(this.l3b, 0, array, num4, this.l3);
            }
            num4 += this.l3;
            array[num4++] = 1;
            if (flag)
            {
                Array.Copy(this.l4sb, 0, array, num4, this.l4s);
                num4 += this.l4s;
                array[num4++] = byte.MaxValue;
                Array.Copy(this.l4tb, 0, array, num4, this.l4t);
                num4 += this.l4t;
                array[num4++] = 2;
                Array.Copy(this.l4kb, 0, array, num4, this.l4k);
                num4 += this.l4k;
                array[num4++] = byte.MaxValue;
                Array.Copy(this.l4wb, 0, array, num4, this.l4w);
                num4 += this.l4w;
                array[num4++] = byte.MaxValue;
            }
            array[num4++] = 1;
            if (this.l5 > 0)
            {
                Array.Copy(this.l5b, 0, array, num4, this.l5);
            }
            num4 += this.l5;
            array[num4++] = 0;
            return new SortKey(this.lcid, this.source, array, this.options, this.l1, this.l2, this.l3, this.l4s, this.l4t, this.l4k, this.l4w, this.l5);
        }
References System.array, System.Array.Copy(), Mono.Globalization.Unicode.SortKeyBuffer.frenchSort, Mono.Globalization.Unicode.SortKeyBuffer.frenchSorted, Mono.Globalization.Unicode.SortKeyBuffer.GetOptimizedLength(), Mono.Globalization.Unicode.SortKeyBuffer.l1, Mono.Globalization.Unicode.SortKeyBuffer.l1b, Mono.Globalization.Unicode.SortKeyBuffer.l2, Mono.Globalization.Unicode.SortKeyBuffer.l2b, Mono.Globalization.Unicode.SortKeyBuffer.l3, Mono.Globalization.Unicode.SortKeyBuffer.l3b, Mono.Globalization.Unicode.SortKeyBuffer.l4k, Mono.Globalization.Unicode.SortKeyBuffer.l4kb, Mono.Globalization.Unicode.SortKeyBuffer.l4s, Mono.Globalization.Unicode.SortKeyBuffer.l4sb, Mono.Globalization.Unicode.SortKeyBuffer.l4t, Mono.Globalization.Unicode.SortKeyBuffer.l4tb, Mono.Globalization.Unicode.SortKeyBuffer.l4w, Mono.Globalization.Unicode.SortKeyBuffer.l4wb, Mono.Globalization.Unicode.SortKeyBuffer.l5, Mono.Globalization.Unicode.SortKeyBuffer.l5b, Mono.Globalization.Unicode.SortKeyBuffer.lcid, Mono.Globalization.Unicode.SortKeyBuffer.options, System.Array.Reverse(), and Mono.Globalization.Unicode.SortKeyBuffer.source.
Referenced by Mono.Globalization.Unicode.SortKeyBuffer.GetResultAndReset().