Terraria Decompiled: Mono.Globalization.Unicode.SortKeyBuffer.AppendKana
AppendKana()
void Mono.Globalization.Unicode.SortKeyBuffer.AppendKana (byte category, byte lv1, byte lv2, byte lv3, bool isSmallKana, byte markType, bool isKatakana, bool isHalfWidth) inline package
Definition at line 85 of file SortKeyBuffer.cs.
        {
            this.AppendNormal(category, lv1, lv2, lv3);
            this.AppendBufferPrimitive(isSmallKana ? 196 : 228, ref this.l4sb, ref this.l4s);
            this.AppendBufferPrimitive(markType, ref this.l4tb, ref this.l4t);
            this.AppendBufferPrimitive(isKatakana ? 196 : 228, ref this.l4kb, ref this.l4k);
            this.AppendBufferPrimitive(isHalfWidth ? 196 : 228, ref this.l4wb, ref this.l4w);
        }
References Mono.Globalization.Unicode.SortKeyBuffer.AppendBufferPrimitive(), Mono.Globalization.Unicode.SortKeyBuffer.AppendNormal(), Mono.Globalization.Unicode.SortKeyBuffer.l4k, Mono.Globalization.Unicode.SortKeyBuffer.l4kb, Mono.Globalization.Unicode.SortKeyBuffer.l4s, Mono.Globalization.Unicode.SortKeyBuffer.l4sb, Mono.Globalization.Unicode.SortKeyBuffer.l4t, Mono.Globalization.Unicode.SortKeyBuffer.l4tb, Mono.Globalization.Unicode.SortKeyBuffer.l4w, and Mono.Globalization.Unicode.SortKeyBuffer.l4wb.
Referenced by Mono.Globalization.Unicode.SimpleCollator.FillSortKeyRaw().