Terraria Decompiled: System.Collections.Generic.Comparer.CreateComparer
CreateComparer()
static Comparer< T > System.Collections.Generic.Comparer< T >.CreateComparer () inline static private
Definition at line 40 of file Comparer.cs.
        {
            RuntimeType runtimeType = (RuntimeType)typeof(T);
            if (typeof(IComparable<T>).IsAssignableFrom(runtimeType))
            {
                return (Comparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(GenericComparer<>), runtimeType);
            }
            if (runtimeType.IsGenericType && runtimeType.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                RuntimeType runtimeType2 = (RuntimeType)runtimeType.GetGenericArguments()[0];
                if (typeof(IComparable<>).MakeGenericType(new Type[] { runtimeType2 }).IsAssignableFrom(runtimeType2))
                {
                    return (Comparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(NullableComparer<>), runtimeType2);
                }
            }
            return new ObjectComparer<T>();
        }
References System.RuntimeType.CreateInstanceForAnotherGenericParameter(), System.RuntimeType.GetGenericArguments(), System.RuntimeType.GetGenericTypeDefinition(), and System.RuntimeType.IsGenericType.