Terraria Decompiled: System.IO.StreamReader.d__63.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamReader.d__63.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1469 of file StreamReader.cs.
            {
                int num2;
                int num = num2;
                StreamReader streamReader = this;
                string text;
                try
                {
                    ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    if (num == 0)
                    {
                        ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                        num2 = -1;
                        goto IL_00B8;
                    }
                    sb = new StringBuilder(streamReader._charLen - streamReader._charPos);
                    IL_002C:
                    int charPos = streamReader._charPos;
                    sb.Append(streamReader._charBuffer, charPos, streamReader._charLen - charPos);
                    streamReader._charPos = streamReader._charLen;
                    configuredTaskAwaiter = streamReader.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter.IsCompleted)
                    {
                        num2 = 0;
                        ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter, StreamReader.<ReadToEndAsyncInternal>d__63>(ref configuredTaskAwaiter, ref this);
                        return;
                    }
                    IL_00B8:
                    configuredTaskAwaiter.GetResult();
                    if (streamReader._charLen > 0)
                    {
                        goto IL_002C;
                    }
                    text = sb.ToString();
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    sb = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                sb = null;
                this.<>t__builder.SetResult(text);
            }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.IO.StreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadToEndAsyncInternal(), and System.text.