Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest
TurnGoldChestIntoDeadMansChest()
void Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest (Point position) inline private
Definition at line 391 of file DeadMansChestBiome.cs.
        {
            for (int i = 0; i < 2; i++)
            {
                for (int j = 0; j < 2; j++)
                {
                    int num = position.X + i;
                    int num2 = position.Y + j;
                    Tile tile = Main.tile[num, num2];
                    tile.type = 467;
                    tile.frameX = (short)(144 + i * 18);
                    tile.frameY = (short)(j * 18);
                }
            }
            if (GenBase._random.Next(3) == 0)
            {
                int num3 = Chest.FindChest(position.X, position.Y);
                if (num3 > -1)
                {
                    Item[] item = Main.chest[num3].item;
                    for (int k = item.Length - 2; k > 0; k--)
                    {
                        Item item2 = item[k];
                        if (item2.stack != 0)
{
                            item[k + 1] = item2.DeepClone();
                        }
                    }
                    item[1] = new Item();
                    item[1].SetDefaults(5007, null);
                    Main.chest[num3].item = item;
                }
            }
        }
References Terraria.WorldBuilding.GenBase._random, Terraria.Main.chest, Terraria.Item.DeepClone(), Terraria.Chest.FindChest(), System.item, Terraria.Chest.item, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.stack, Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.Place().