Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle
FindDartTrapSpotSingle()
bool Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle (Point position, int directionX) inline private
Definition at line 233 of file DeadMansChestBiome.cs.
        {
            int x = position.X;
            int y = position.Y;
            int i = 0;
            while (i < 20)
            {
                Tile tile = Main.tile[x + i * directionX, y];
                if ((!tile.active() || tile.type < 0 || tile.type >= TileID.Count || !TileID.Sets.IsAContainer[(int)tile.type]) && tile.active() && Main.tileSolid[(int)tile.type])
                {
                    if (i >= 5 && !tile.actuator() && !Main.tileFrameImportant[(int)tile.type] && WorldGen.CanBeClearedDuringGeneration((int)tile.type, x + i * directionX, y, false))
                    {
                        this._dartTrapPlacementSpots.Add(new DeadMansChestBiome.DartTrapPlacementAttempt(position, directionX, x, y, i, tile));
                        return true;
                    }
                    return false;
                }
                else
                {
                    i++;
                }
            }
            return false;
        }
References Terraria.GameContent.Biomes.DeadMansChestBiome._dartTrapPlacementSpots, Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.WorldGen.CanBeClearedDuringGeneration(), Terraria.ID.TileID.Count, Terraria.ID.TileID.Sets.IsAContainer, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots().