Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.Place
Place()
override bool Terraria.GameContent.Biomes.DeadMansChestBiome.Place (Point origin, StructureMap structures, GenerationProgress progress) inline
Definition at line 15 of file DeadMansChestBiome.cs.
        {
            if (!DeadMansChestBiome.IsAGoodSpot(origin))
            {
                return false;
            }
            this.ClearCaches();
            Point point = new Point(origin.X, origin.Y + 1);
            this.FindBoulderTrapSpots(point);
            this.FindDartTrapSpots(point);
            this.FindExplosiveTrapSpots(point);
            if (!this.AreThereEnoughTraps())
            {
                return false;
            }
            this.TurnGoldChestIntoDeadMansChest(origin);
            foreach (DeadMansChestBiome.DartTrapPlacementAttempt dartTrapPlacementAttempt in this._dartTrapPlacementSpots)
            {
                this.ActuallyPlaceDartTrap(dartTrapPlacementAttempt.position, dartTrapPlacementAttempt.directionX, dartTrapPlacementAttempt.x, dartTrapPlacementAttempt.y, dartTrapPlacementAttempt.xPush, dartTrapPlacementAttempt.t);
            }
            foreach (DeadMansChestBiome.WirePlacementAttempt wirePlacementAttempt in this._wirePlacementSpots)
            {
                this.PlaceWireLine(wirePlacementAttempt.position, wirePlacementAttempt.dirX, wirePlacementAttempt.dirY, wirePlacementAttempt.steps);
            }
            foreach (DeadMansChestBiome.BoulderPlacementAttempt boulderPlacementAttempt in this._boulderPlacementSpots)
            {
                this.ActuallyPlaceBoulderTrap(boulderPlacementAttempt.position, boulderPlacementAttempt.yPush, boulderPlacementAttempt.requiredHeight, boulderPlacementAttempt.bestType);
            }
            foreach (DeadMansChestBiome.ExplosivePlacementAttempt explosivePlacementAttempt in this._explosivePlacementAttempt)
            {
                this.ActuallyPlaceExplosive(explosivePlacementAttempt.position);
            }
            this.PlaceWiresForExplosives(origin);
            return true;
        }
References Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceExplosive(), Terraria.GameContent.Biomes.DeadMansChestBiome.AreThereEnoughTraps(), Terraria.GameContent.Biomes.DeadMansChestBiome.ClearCaches(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindExplosiveTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWireLine(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWiresForExplosives(), Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.