Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap
ActuallyPlaceBoulderTrap()
void Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap (Point position, int yPush, int requiredHeight, int bestType) inline private
Definition at line 455 of file DeadMansChestBiome.cs.
        {
            for (int i = position.X; i < position.X + 2; i++)
            {
                for (int j = position.Y - requiredHeight; j <= position.Y + 2; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (j < position.Y - requiredHeight + 2)
                    {
                        tile.ClearTile();
                    }
                    else if (j <= position.Y)
                    {
                        bool flag = false;
                        do
{
                            if (!tile.active())
{
                                tile.active(true);
                                tile.type = (ushort)bestType;
                            }
                            tile.slope(0);
                            tile.halfBrick(false);
                            WorldGen.TileFrame(i, j, true, false);
                            if (flag)
{
                                break;
                            }
                            flag = true;
                        }
                        while (!tile.active());
                        tile.wire(true);
                        if (Main.tileSolid[(int)tile.type])
{
                            tile.actuator(true);
                        }
                    }
                    else
                    {
                        tile.ClearTile();
                    }
                }
            }
            int num = position.X + 1;
            int num2 = position.Y - requiredHeight + 1;
            int num3 = 3;
            int num4 = num - num3;
            int num5 = num2 - num3;
            int num6 = num + num3 - 1;
            int num7 = num2 + num3 - 1;
            for (int k = num4; k <= num6; k++)
            {
                for (int l = num5; l <= num7; l++)
                {
                    Tile tile2 = Main.tile[k, l];
                    if (tile2.type >= 0 && !TileID.Sets.Boulders[(int)tile2.type])
                    {
                        tile2.type = 1;
                        if (tile2.wire())
{
                            tile2.actuator(true);
                        }
                    }
                }
            }
            WorldGen.PlaceTile(num, num2, 138, false, false, -1, 0);
            this.PlaceWireLine(position, 0, 1, yPush);
        }
References Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.ID.TileID.Sets.Boulders, Terraria.Tile.ClearTile(), Terraria.Tile.halfBrick(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWireLine(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wire(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.Place().