Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot
PlaceBoulderTrapSpot()
void Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceBoulderTrapSpot (Point position, int yPush) inline private
Definition at line 149 of file DeadMansChestBiome.cs.
        {
            int[] array = new int[(int)TileID.Count];
            for (int i = position.X; i < position.X + 2; i++)
            {
                for (int j = position.Y - 4; j <= position.Y; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && !Main.tileFrameImportant[(int)tile.type] && Main.tileSolid[(int)tile.type])
                    {
                        array[(int)tile.type]++;
                    }
                    if (tile.active() && !WorldGen.CanBeClearedDuringGeneration((int)tile.type, i, j, false))
                    {
                        return;
                    }
                    if (tile.active() && TileID.Sets.IsAContainer[(int)tile.type])
                    {
                        return;
                    }
                }
            }
            for (int k = position.X - 1; k < position.X + 2 + 1; k++)
            {
                for (int l = position.Y - 4 - 1; l <= position.Y - 4 + 2; l++)
                {
                    Tile tile2 = Main.tile[k, l];
                    if (!tile2.active())
                    {
                        return;
                    }
                    if (TileID.Sets.IsAContainer[(int)tile2.type])
                    {
                        return;
                    }
                }
            }
            int num = 2;
            int num2 = position.X - num;
            int num3 = position.Y - 4 - num;
            int num4 = position.X + num + 1;
            int num5 = position.Y - 4 + num + 1;
            for (int m = num2; m <= num4; m++)
            {
                for (int n = num3; n <= num5; n++)
                {
                    Tile tile3 = Main.tile[m, n];
                    if (tile3.active() && (TileID.Sets.IsAContainer[(int)tile3.type] || tile3.type == 12 || tile3.type == 665 || tile3.type == 639))
                    {
                        return;
                    }
                }
            }
            int num6 = -1;
            for (int num7 = 0; num7 < array.Length; num7++)
            {
                if (num6 == -1 || array[num6] < array[num7])
                {
                    num6 = num7;
                }
            }
            this._boulderPlacementSpots.Add(new DeadMansChestBiome.BoulderPlacementAttempt(position, yPush - 1, 4, num6));
        }
References Terraria.GameContent.Biomes.DeadMansChestBiome._boulderPlacementSpots, Terraria.Tile.active(), System.array, Terraria.WorldGen.CanBeClearedDuringGeneration(), Terraria.ID.TileID.Count, int, Terraria.ID.TileID.Sets.IsAContainer, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.Main.tileSolid, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpot().