Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.FindExplosiveTrapSpots
FindExplosiveTrapSpots()
void Terraria.GameContent.Biomes.DeadMansChestBiome.FindExplosiveTrapSpots (Point position) inline private
Definition at line 259 of file DeadMansChestBiome.cs.
        {
            int num = position.X;
            int num2 = position.Y + 3;
            List<int> list = new List<int>();
            if (this.IsGoodSpotsForExplosive(num, num2))
            {
                list.Add(num);
            }
            num++;
            if (this.IsGoodSpotsForExplosive(num, num2))
            {
                list.Add(num);
            }
            int num3 = -1;
            if (list.Count > 0)
            {
                num3 = list[GenBase._random.Next(list.Count)];
            }
            list.Clear();
            num += GenBase._random.Next(2, 6);
            int num4 = 4;
            for (int i = num; i < num + num4; i++)
            {
                if (this.IsGoodSpotsForExplosive(i, num2))
                {
                    list.Add(i);
                }
            }
            int num5 = -1;
            if (list.Count > 0)
            {
                num5 = list[GenBase._random.Next(list.Count)];
            }
            num = position.X - num4 - GenBase._random.Next(2, 6);
            for (int j = num; j < num + num4; j++)
            {
                if (this.IsGoodSpotsForExplosive(j, num2))
                {
                    list.Add(j);
                }
            }
            int num6 = -1;
            if (list.Count > 0)
            {
                num6 = list[GenBase._random.Next(list.Count)];
            }
            if (num6 != -1)
            {
                this._explosivePlacementAttempt.Add(new DeadMansChestBiome.ExplosivePlacementAttempt(new Point(num6, num2)));
            }
            if (num3 != -1)
            {
                this._explosivePlacementAttempt.Add(new DeadMansChestBiome.ExplosivePlacementAttempt(new Point(num3, num2)));
            }
            if (num5 != -1)
            {
                this._explosivePlacementAttempt.Add(new DeadMansChestBiome.ExplosivePlacementAttempt(new Point(num5, num2)));
            }
        }
References Terraria.GameContent.Biomes.DeadMansChestBiome._explosivePlacementAttempt, Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.DeadMansChestBiome.IsGoodSpotsForExplosive(), System.list, Terraria.Utilities.UnifiedRandom.Next(), and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.Place().