Terraria Decompiled: Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots
FindBoulderTrapSpots()
void Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots (Point position) inline private
Definition at line 92 of file DeadMansChestBiome.cs.
        {
            int num = position.X;
            int num2 = GenBase._random.Next(this._numberOfBoulderTraps);
            int num3 = GenBase._random.Next(this._numberOfStepsBetweenBoulderTraps);
            num -= num2 / 2 * num3;
            int num4 = position.Y - 6;
            for (int i = 0; i <= num2; i++)
            {
                this.FindBoulderTrapSpot(new Point(num, num4));
                num += num3;
            }
            if (this._boulderPlacementSpots.Count > 0)
            {
                int num5 = this._boulderPlacementSpots[0].position.X;
                int num6 = this._boulderPlacementSpots[0].position.X;
                for (int j = 1; j < this._boulderPlacementSpots.Count; j++)
                {
                    int x = this._boulderPlacementSpots[j].position.X;
                    if (num5 > x)
                    {
                        num5 = x;
                    }
                    if (num6 < x)
                    {
                        num6 = x;
                    }
                }
                if (num5 > position.X)
                {
                    num5 = position.X;
                }
                if (num6 < position.X)
                {
                    num6 = position.X;
                }
                this._wirePlacementSpots.Add(new DeadMansChestBiome.WirePlacementAttempt(new Point(num5, num4 - 1), 1, 0, num6 - num5));
                this._wirePlacementSpots.Add(new DeadMansChestBiome.WirePlacementAttempt(position, 0, -1, 7));
            }
        }
References Terraria.GameContent.Biomes.DeadMansChestBiome._boulderPlacementSpots, Terraria.GameContent.Biomes.DeadMansChestBiome._numberOfBoulderTraps, Terraria.GameContent.Biomes.DeadMansChestBiome._numberOfStepsBetweenBoulderTraps, Terraria.WorldBuilding.GenBase._random, Terraria.GameContent.Biomes.DeadMansChestBiome._wirePlacementSpots, Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpot(), Terraria.Utilities.UnifiedRandom.Next(), and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.GetPossibleChestsToTrapify(), and Terraria.GameContent.Biomes.DeadMansChestBiome.Place().