Terraria Decompiled: Terraria.Social.Steam.AchievementsSocialModule.Initialize
Initialize()
override void Terraria.Social.Steam.AchievementsSocialModule.Initialize () inline
Definition at line 13 of file AchievementsSocialModule.cs.
        {
            this._userStatsReceived = Callback<UserStatsReceived_t>.Create(new Callback<UserStatsReceived_t>.DispatchDelegate(this.OnUserStatsReceived));
            SteamUserStats.RequestCurrentStats();
            while (!this._areStatsReceived)
            {
                CoreSocialModule.Pulse();
                Thread.Sleep(10);
            }
        }
References Terraria.Social.Steam.AchievementsSocialModule._areStatsReceived, Steamworks.Callback< T >.Create(), Terraria.Social.Steam.AchievementsSocialModule.OnUserStatsReceived(), Terraria.Social.Steam.CoreSocialModule.Pulse(), Steamworks.SteamUserStats.RequestCurrentStats(), and System.Threading.Thread.Sleep().