Terraria Decompiled: Terraria.Social.Steam.AchievementsSocialModule.GetFloatStat
GetFloatStat()
float Terraria.Social.Steam.AchievementsSocialModule.GetFloatStat (string name) inline private
Definition at line 70 of file AchievementsSocialModule.cs.
        {
            float num;
            if (this._floatStatCache.TryGetValue(name, out num))
            {
                return num;
            }
            if (SteamUserStats.GetStat(name, ref num))
            {
                this._floatStatCache.Add(name, num);
            }
            return num;
        }
References Terraria.Social.Steam.AchievementsSocialModule._floatStatCache, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Steamworks.SteamUserStats.GetStat(), System.name, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.Social.Steam.AchievementsSocialModule.UpdateFloatStat().