Terraria Decompiled: XPT.Core.Audio.MP3Sharp.IO.WaveFile.Close
Close() [1/2]
override int XPT.Core.Audio.MP3Sharp.IO.WaveFile.Close () inline package virtual
Reimplemented from XPT.Core.Audio.MP3Sharp.IO.RiffFile.
Definition at line 75 of file WaveFile.cs.
        {
            int num = 0;
            if (this.Fmode == 1)
            {
                num = this.Backpatch(this._PcmDataOffset, this._PcmData, 8);
            }
            if (!this._JustWriteLengthBytes && num == 0)
            {
                num = base.Close();
            }
            return num;
        }
References XPT.Core.Audio.MP3Sharp.IO.WaveFile._JustWriteLengthBytes, XPT.Core.Audio.MP3Sharp.IO.WaveFile._PcmData, XPT.Core.Audio.MP3Sharp.IO.WaveFile._PcmDataOffset, XPT.Core.Audio.MP3Sharp.IO.RiffFile.Backpatch(), and XPT.Core.Audio.MP3Sharp.IO.RiffFile.Fmode.
Referenced by XPT.Core.Audio.MP3Sharp.IO.WaveFileBuffer.Close(), XPT.Core.Audio.MP3Sharp.IO.WaveFile.Close(), and XPT.Core.Audio.MP3Sharp.IO.WaveFileBuffer.Close().