Terraria Decompiled: XPT.Core.Audio.MP3Sharp.IO.WaveFile.OpenForWrite
OpenForWrite() [1/2]
virtual int XPT.Core.Audio.MP3Sharp.IO.WaveFile.OpenForWrite (string filename, Stream stream, int samplingRate, short bitsPerSample, short numChannels) inline package virtual
Definition at line 21 of file WaveFile.cs.
        {
            if ((bitsPerSample != 8 && bitsPerSample != 16) || numChannels < 1 || numChannels > 2)
            {
                return 4;
            }
            this._WaveFormat.Data.Config(samplingRate, bitsPerSample, numChannels);
            int num = 0;
            if (stream != null)
            {
                this.Open(stream, 1);
            }
            else
            {
                this.Open(filename, 1);
            }
            if (num == 0)
            {
                sbyte[] array = new sbyte[]
                {
                    (sbyte)SupportClass.Identity(87L),
                    (sbyte)SupportClass.Identity(65L),
                    (sbyte)SupportClass.Identity(86L),
                    (sbyte)SupportClass.Identity(69L)
                };
                num = this.Write(array, 4);
                if (num == 0)
                {
                    num = this.Write(this._WaveFormat.Header, 8);
                    num = this.Write(this._WaveFormat.Data.FormatTag, 2);
                    num = this.Write(this._WaveFormat.Data.NumChannels, 2);
                    num = this.Write(this._WaveFormat.Data.NumSamplesPerSec, 4);
                    num = this.Write(this._WaveFormat.Data.NumAvgBytesPerSec, 4);
                    num = this.Write(this._WaveFormat.Data.NumBlockAlign, 2);
                    num = this.Write(this._WaveFormat.Data.NumBitsPerSample, 2);
                    if (num == 0)
                    {
                        this._PcmDataOffset = this.CurrentFilePosition();
                        num = this.Write(this._PcmData, 8);
                    }
                }
            }
            return num;
        }
References XPT.Core.Audio.MP3Sharp.IO.WaveFile._PcmData, XPT.Core.Audio.MP3Sharp.IO.WaveFile._WaveFormat, System.array, XPT.Core.Audio.MP3Sharp.IO.RiffFile.CurrentFilePosition(), XPT.Core.Audio.MP3Sharp.Support.SupportClass.Identity(), System.L, XPT.Core.Audio.MP3Sharp.IO.WaveFile.NumChannels(), System.IO.Open, and System.IO.Write.
Referenced by XPT.Core.Audio.MP3Sharp.IO.WaveFile.OpenForWrite(), XPT.Core.Audio.MP3Sharp.IO.WaveFileBuffer.WaveFileBuffer(), and XPT.Core.Audio.MP3Sharp.IO.WaveFileBuffer.WaveFileBuffer().