Terraria Decompiled: System.Threading.Monitor.ObjWait
ObjWait()
static bool System.Threading.Monitor.ObjWait (bool exitContext, int millisecondsTimeout, object obj) inline static private
Definition at line 206 of file Monitor.cs.
        {
            if (millisecondsTimeout < 0 && millisecondsTimeout != -1)
            {
                throw new ArgumentOutOfRangeException("millisecondsTimeout");
            }
            if (!Monitor.Monitor_test_synchronised(obj))
            {
                throw new SynchronizationLockException("Object is not synchronized");
            }
            bool flag;
            try
            {
                if (exitContext)
                {
                    SynchronizationAttribute.ExitContext();
                }
                flag = Monitor.Monitor_wait(obj, millisecondsTimeout);
            }
            finally
            {
                if (exitContext)
                {
                    SynchronizationAttribute.EnterContext();
                }
            }
            return flag;
        }
References System.Runtime.Remoting.Contexts.SynchronizationAttribute.EnterContext(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.ExitContext(), System.Threading.Monitor.Monitor_test_synchronised(), System.Threading.Monitor.Monitor_wait(), and System.obj.
Referenced by System.Threading.Monitor.Wait().