Terraria Decompiled: System.Security.Cryptography.RijndaelManaged.NewEncryptor
NewEncryptor()
ICryptoTransform System.Security.Cryptography.RijndaelManaged.NewEncryptor (byte[] rgbKey, CipherMode mode, byte[] rgbIV, int feedbackSize, RijndaelManagedTransformMode encryptMode) inline private
Definition at line 44 of file RijndaelManaged.cs.
        {
            if (rgbKey == null)
            {
                rgbKey = Utils.GenerateRandom(this.KeySizeValue / 8);
            }
            if (rgbIV == null)
            {
                rgbIV = Utils.GenerateRandom(this.BlockSizeValue / 8);
            }
            return new RijndaelManagedTransform(rgbKey, mode, rgbIV, this.BlockSizeValue, feedbackSize, this.PaddingValue, encryptMode);
        }
References System.Security.Cryptography.SymmetricAlgorithm.BlockSizeValue, System.Security.Cryptography.Utils.GenerateRandom(), System.Security.Cryptography.SymmetricAlgorithm.KeySizeValue, System.mode, and System.Security.Cryptography.SymmetricAlgorithm.PaddingValue.
Referenced by System.Security.Cryptography.RijndaelManaged.CreateDecryptor(), and System.Security.Cryptography.RijndaelManaged.CreateEncryptor().