Terraria Decompiled: System.Security.SecurityException.ToString
ToString()
override string System.Security.SecurityException.ToString () inline
Implements System.Runtime.InteropServices._Exception.
Definition at line 334 of file SecurityException.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(base.ToString());
            try
            {
                if (this.permissionType != null)
                {
                    stringBuilder.AppendFormat("{0}Type: {1}", Environment.NewLine, this.PermissionType);
                }
                if (this._method != null)
                {
                    string text = this._method.ToString();
                    int num = text.IndexOf(" ") + 1;
                    stringBuilder.AppendFormat("{0}Method: {1} {2}.{3}", new object[]
                    {
                        Environment.NewLine,
                        this._method.ReturnType.Name,
                        this._method.ReflectedType,
                        text.Substring(num)
                    });
                }
                if (this.permissionState != null)
                {
                    stringBuilder.AppendFormat("{0}State: {1}", Environment.NewLine, this.PermissionState);
                }
                if (this._granted != null && this._granted.Length > 0)
                {
                    stringBuilder.AppendFormat("{0}Granted: {1}", Environment.NewLine, this.GrantedSet);
                }
                if (this._refused != null && this._refused.Length > 0)
                {
                    stringBuilder.AppendFormat("{0}Refused: {1}", Environment.NewLine, this.RefusedSet);
                }
                if (this._demanded != null)
                {
                    stringBuilder.AppendFormat("{0}Demanded: {1}", Environment.NewLine, this.Demanded);
                }
                if (this._firstperm != null)
                {
                    stringBuilder.AppendFormat("{0}Failed Permission: {1}", Environment.NewLine, this.FirstPermissionThatFailed);
                }
                if (this._evidence != null)
                {
                    stringBuilder.AppendFormat("{0}Evidences:", Environment.NewLine);
                    foreach (object obj in this._evidence)
                    {
                        if (!(obj is Hash))
{
                            stringBuilder.AppendFormat("{0}\t{1}", Environment.NewLine, obj);
                        }
                    }
                }
            }
            catch (SecurityException)
            {
            }
            return stringBuilder.ToString();
        }
References System.Security.SecurityException._demanded, System.Security.SecurityException._evidence, System.Security.SecurityException._firstperm, System.Security.SecurityException._granted, System.Security.SecurityException._method, System.Security.SecurityException._refused, System.Text.StringBuilder.AppendFormat(), System.Reflection.MemberInfo.Name, System.obj, System.Security.SecurityException.permissionState, System.Security.SecurityException.permissionType, System.Runtime.InteropServices._MethodInfo.ReflectedType, System.Reflection.MethodInfo.ReturnType, System.text, System.Runtime.InteropServices._MethodInfo.ToString(), and System.Text.StringBuilder.ToString().