Terraria Decompiled: System.IO.PathInternal.RemoveRelativeSegments
RemoveRelativeSegments()
static unsafe string System.IO.PathInternal.RemoveRelativeSegments (string path, int rootLength) inline static package
Definition at line 193 of file PathInternal.cs.
        {
            bool flag = false;
            int num = rootLength;
            if (PathInternal.IsDirectorySeparator(path[num - 1]))
            {
                num--;
            }
            Span<char> span = new Span<char>(stackalloc byte[(UIntPtr)520], 260);
            ValueStringBuilder valueStringBuilder = new ValueStringBuilder(span);
            if (num > 0)
            {
                valueStringBuilder.Append(path.AsSpan(0, num));
            }
            int i = num;
            while (i < path.Length)
            {
                char c = path[i];
                if (!PathInternal.IsDirectorySeparator(c) || i + 1 >= path.Length)
                {
                    goto IL_0165;
                }
                if (!PathInternal.IsDirectorySeparator(path[i + 1]))
                {
                    if ((i + 2 == path.Length || PathInternal.IsDirectorySeparator(path[i + 2])) && path[i + 1] == '.')
                    {
                        i++;
                    }
                    else
                    {
                        if (i + 2 >= path.Length || (i + 3 != path.Length && !PathInternal.IsDirectorySeparator(path[i + 3])) || path[i + 1] != '.' || path[i + 2] != '.')
{
                            goto IL_0165;
                        }
                        int j;
                        for (j = valueStringBuilder.Length - 1; j >= num; j--)
{
                            if (PathInternal.IsDirectorySeparator(*valueStringBuilder[j]))
{
                                valueStringBuilder.Length = ((i + 3 >= path.Length && j == num) ? (j + 1) : j);
                                break;
                            }
                        }
                        if (j < num)
{
                            valueStringBuilder.Length = num;
                        }
                        i += 2;
                    }
                }
                IL_0180:
                i++;
                continue;
                IL_0165:
                if (c != '/' && c == '/')
                {
                    c = '/';
                    flag = true;
                }
                valueStringBuilder.Append(c);
                goto IL_0180;
            }
            if (!flag && valueStringBuilder.Length == path.Length)
            {
                valueStringBuilder.Dispose();
                return path;
            }
            if (valueStringBuilder.Length >= rootLength)
            {
                return valueStringBuilder.ToString();
            }
            return path.Substring(0, rootLength);
        }
References System.Text.ValueStringBuilder.Append(), System.Text.ValueStringBuilder.Dispose(), System.IO.PathInternal.IsDirectorySeparator(), System.Text.ValueStringBuilder.Length, and System.Text.ValueStringBuilder.ToString().