Terraria Decompiled: System.Runtime.Remoting.Messaging.CADMethodRef.Resolve
Resolve()
MethodBase System.Runtime.Remoting.Messaging.CADMethodRef.Resolve () inline
Definition at line 22 of file CADMethodRef.cs.
        {
            Type type = Type.GetType(this.typeName, true);
            Type[] types = this.GetTypes(this.param_names);
            MethodBase methodBase;
            if (this.ctor)
            {
                methodBase = type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, types, null);
            }
            else
            {
                methodBase = type.GetMethod(this.methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, types, null);
            }
            if (methodBase != null && this.generic_arg_names != null && !methodBase.IsGenericMethodDefinition)
            {
                methodBase = null;
            }
            if (methodBase != null && this.generic_arg_names != null)
            {
                methodBase = ((MethodInfo)methodBase).MakeGenericMethod(this.GetTypes(this.generic_arg_names));
            }
            if (methodBase == null && this.generic_arg_names != null)
            {
                foreach (MethodInfo methodInfo in type.GetMethods())
                {
                    if (!(methodInfo.Name != this.methodName) && methodInfo.IsGenericMethodDefinition && methodInfo.GetGenericArguments().Length == this.generic_arg_names.Length)
                    {
                        methodBase = methodInfo.MakeGenericMethod(this.GetTypes(this.generic_arg_names));
                        ParameterInfo[] parameters = methodBase.GetParameters();
                        if (this.param_names.Length == parameters.Length)
{
                            for (int j = 0; j < parameters.Length; j++)
{
                                if (parameters[j].ParameterType.AssemblyQualifiedName != this.param_names[j])
{
                                    methodBase = null;
                                    break;
                                }
                            }
                            if (methodBase != null)
{
                                break;
                            }
                        }
                    }
                }
            }
            if (methodBase == null)
            {
                throw new RemotingException(string.Concat(new string[] { "Method '", this.methodName, "' not found in type '", this.typeName, "'" }));
            }
            return methodBase;
        }
References System.Runtime.Remoting.Messaging.CADMethodRef.ctor, System.Runtime.Remoting.Messaging.CADMethodRef.generic_arg_names, System.Type.GetConstructor(), System.Reflection.MethodInfo.GetGenericArguments(), System.Type.GetMethod(), System.Type.GetMethods(), System.Reflection.MethodBase.GetParameters(), System.Type.GetType(), System.Runtime.Remoting.Messaging.CADMethodRef.GetTypes(), System.Reflection.MethodBase.IsGenericMethodDefinition, System.Reflection.MethodInfo.MakeGenericMethod(), System.Runtime.Remoting.Messaging.CADMethodRef.methodName, System.Runtime.InteropServices._MethodInfo.Name, System.Runtime.Remoting.Messaging.CADMethodRef.param_names, and System.Runtime.Remoting.Messaging.CADMethodRef.typeName.