Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.DecodeFrame
DecodeFrame()
virtual void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.DecodeFrame () inline virtual
Implements XPT.Core.Audio.MP3Sharp.Decoding.Decoders.IFrameDecoder.
Definition at line 16 of file LayerIDecoder.cs.
        {
            this.NuSubbands = this.Header.NumberSubbands();
            this.Subbands = new ASubband[32];
            this.Mode = this.Header.Mode();
            this.CreateSubbands();
            this.ReadAllocation();
            this.ReadScaleFactorSelection();
            if (this.CRC != null || this.Header.IsChecksumOK())
            {
                this.ReadScaleFactors();
                this.ReadSampleData();
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.CRC, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.CreateSubbands(), XPT.Core.Audio.MP3Sharp.Decoding.Header.IsChecksumOK(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Mode(), XPT.Core.Audio.MP3Sharp.Decoding.Header.NumberSubbands(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadAllocation(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadSampleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadScaleFactors(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadScaleFactorSelection().