Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadSampleData
ReadSampleData()
virtual void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.ReadSampleData () inline protected virtual
Definition at line 97 of file LayerIDecoder.cs.
        {
            bool flag = false;
            bool flag2 = false;
            int num = this.Header.Mode();
            do
            {
                for (int i = 0; i < this.NuSubbands; i++)
                {
                    flag = this.Subbands[i].ReadSampleData(this.Stream);
                }
                do
                {
                    for (int i = 0; i < this.NuSubbands; i++)
                    {
                        flag2 = this.Subbands[i].PutNextSample(this.WhichChannels, this.Filter1, this.Filter2);
                    }
                    this.Filter1.calculate_pc_samples(this.Buffer);
                    if (this.WhichChannels == 0 && num != 3)
                    {
                        this.Filter2.calculate_pc_samples(this.Buffer);
                    }
                }
                while (!flag2);
            }
            while (!flag);
        }
References XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.calculate_pc_samples(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.Filter1, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.Filter2, XPT.Core.Audio.MP3Sharp.Decoding.Header.Mode(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.NuSubbands, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.ASubband.PutNextSample(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.ASubband.ReadSampleData(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.Stream, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.Subbands, and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.WhichChannels.
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerIDecoder.DecodeFrame().