Terraria Decompiled: Terraria.Graphics.Capture.CaptureCamera.SaveImage
SaveImage() [1/3]
static bool Terraria.Graphics.Capture.CaptureCamera.SaveImage (byte[] data, int width, int height, ImageFormat imageFormat, string filename) inline static
Definition at line 243 of file CaptureCamera.cs.
        {
            if (!Utils.TryCreatingDirectory(Main.SavePath + Path.DirectorySeparatorChar.ToString() + "Captures" + Path.DirectorySeparatorChar.ToString()))
            {
                return false;
            }
            bool flag;
            try
            {
                if (Program.IsFna)
                {
                    PlatformUtilities.SavePng(filename, width, height, data);
                }
                else
                {
                    using (Bitmap bitmap = new Bitmap(width, height))
                    {
                        global::System.Drawing.Rectangle rectangle = new global::System.Drawing.Rectangle(0, 0, width, height);
                        BitmapData bitmapData = bitmap.LockBits(rectangle, ImageLockMode.WriteOnly, PixelFormat.Format32bppPArgb);
                        IntPtr scan = bitmapData.Scan0;
                        Marshal.Copy(data, 0, scan, width * height * 4);
                        bitmap.UnlockBits(bitmapData);
                        bitmap.Save(filename, imageFormat);
                        bitmap.Dispose();
                    }
                }
                flag = true;
            }
            catch (Exception ex)
            {
                Console.WriteLine(ex);
                flag = false;
            }
            return flag;
        }
References System.Runtime.InteropServices.Marshal.Copy(), System.IO.Path.DirectorySeparatorChar, Terraria.Program.IsFna, Terraria.Main.SavePath, Terraria.Utilities.PlatformUtilities.SavePng(), Terraria.Utils.TryCreatingDirectory(), and System.Console.WriteLine().