Terraria Decompiled: Terraria.Graphics.Capture.CaptureCamera.BeginDrawCapture
BeginDrawCapture()
void Terraria.Graphics.Capture.CaptureCamera.BeginDrawCapture () inline
Definition at line 172 of file CaptureCamera.cs.
        {
            if (Lighting.NotRetro)
            {
                Main.instance.GraphicsDevice.SetRenderTarget(Main.skyTarget);
                Main.instance.GraphicsDevice.Clear(Microsoft.Xna.Framework.Color.Transparent);
                Filters.Scene.BeginCapture(this._filterFrameBuffer1);
            }
            Main.waterTarget = this._waterTarget;
        }
References Terraria.Graphics.Capture.CaptureCamera._filterFrameBuffer1, Terraria.Graphics.Capture.CaptureCamera._waterTarget, Terraria.Graphics.Effects.FilterManager.BeginCapture(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Game.GraphicsDevice, Terraria.Main.instance, Terraria.Lighting.NotRetro, Terraria.Graphics.Effects.Filters.Scene, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.skyTarget, and Microsoft.Xna.Framework.Color.Transparent.