Terraria Decompiled: Terraria.Graphics.Capture.CaptureCamera.SaveImage
SaveImage() [3/3]
void Terraria.Graphics.Capture.CaptureCamera.SaveImage (Texture2D texture, int width, int height, ImageFormat imageFormat, string foldername, string filename) inline private
Definition at line 280 of file CaptureCamera.cs.
        {
            string text = string.Concat(new string[]
            {
                Main.SavePath,
                Path.DirectorySeparatorChar.ToString(),
                "Captures",
                Path.DirectorySeparatorChar.ToString(),
                foldername
            });
            string text2 = Path.Combine(text, filename);
            if (!Utils.TryCreatingDirectory(text))
            {
                return;
            }
            if (Program.IsFna)
            {
                int num = texture.Width * texture.Height * 4;
                texture.GetData<byte>(this._outputData, 0, num);
                int num2 = 0;
                int num3 = 0;
                for (int i = 0; i < height; i++)
                {
                    for (int j = 0; j < width; j++)
                    {
                        this._outputData[num3] = this._outputData[num2];
                        this._outputData[num3 + 1] = this._outputData[num2 + 1];
                        this._outputData[num3 + 2] = this._outputData[num2 + 2];
                        this._outputData[num3 + 3] = this._outputData[num2 + 3];
                        num2 += 4;
                        num3 += 4;
                    }
                    num2 += texture.Width - width << 2;
                }
                PlatformUtilities.SavePng(text2, width, height, this._outputData);
                return;
            }
            using (Bitmap bitmap = new Bitmap(width, height))
            {
                global::System.Drawing.Rectangle rectangle = new global::System.Drawing.Rectangle(0, 0, width, height);
                int num4 = texture.Width * texture.Height * 4;
                texture.GetData<byte>(this._outputData, 0, num4);
                int num5 = 0;
                int num6 = 0;
                for (int k = 0; k < height; k++)
                {
                    for (int l = 0; l < width; l++)
                    {
                        byte b = this._outputData[num5 + 2];
                        this._outputData[num6 + 2] = this._outputData[num5];
                        this._outputData[num6] = b;
                        this._outputData[num6 + 1] = this._outputData[num5 + 1];
                        this._outputData[num6 + 3] = this._outputData[num5 + 3];
                        num5 += 4;
                        num6 += 4;
                    }
                    num5 += texture.Width - width << 2;
                }
                BitmapData bitmapData = bitmap.LockBits(rectangle, ImageLockMode.WriteOnly, PixelFormat.Format32bppPArgb);
                IntPtr scan = bitmapData.Scan0;
                Marshal.Copy(this._outputData, 0, scan, width * height * 4);
                bitmap.UnlockBits(bitmapData);
                bitmap.Save(text2, imageFormat);
            }
        }
References Terraria.Graphics.Capture.CaptureCamera._outputData, System.IO.Path.Combine(), System.Runtime.InteropServices.Marshal.Copy(), System.IO.Path.DirectorySeparatorChar, Terraria.Program.IsFna, Terraria.Main.SavePath, Terraria.Utilities.PlatformUtilities.SavePng(), System.text, and Terraria.Utils.TryCreatingDirectory().