Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.BuildPage
BuildPage()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.BuildPage () inline private
Definition at line 47 of file UIWorldCreationAdvanced.cs.
        {
            base.RemoveAllChildren();
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixels(500f),
                Height = StyleDimension.FromPixelsAndPercent(-200f, 1f),
                Top = StyleDimension.FromPixels(202f),
                HAlign = 0.5f,
                VAlign = 0f
            };
            if (!this._allowScrolling)
            {
                uielement.MaxHeight = StyleDimension.FromPixels(400f);
            }
            uielement.SetPadding(0f);
            base.Append(uielement);
            UIPanel uipanel = new UIPanel
            {
                Width = StyleDimension.FromPercent(1f),
                Height = StyleDimension.FromPixelsAndPercent(-102f, 1f),
                BackgroundColor = new Color(33, 43, 79) * 0.8f
            };
            uipanel.SetPadding(0f);
            uielement.Append(uipanel);
            this.MakeBackAndCreatebuttons(uielement);
            UIElement uielement2 = new UIElement
            {
                Top = StyleDimension.FromPixelsAndPercent(0f, 0f),
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                HAlign = 1f
            };
            uielement2.SetPadding(0f);
            uielement2.PaddingTop = 8f;
            uielement2.PaddingBottom = 12f;
            uipanel.Append(uielement2);
            this.MakeInfoMenu(uielement2);
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._allowScrolling, Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeInfoMenu(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UIWorldCreationAdvanced().