Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSeedButtons
AddSeedButtons()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSeedButtons (UIElement infoContainer) inline private
Definition at line 395 of file UIWorldCreationAdvanced.cs.
        {
            float num = 0f;
            float num2 = 44f;
            float num3 = num + num2;
            float num4 = num2;
            float num5 = 0f;
            GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(true, null, Language.GetText("UI.WorldCreationRandomizeSeedDescription"), Color.White, null, 1f, 0.5f, 10f)
            {
                Width = StyleDimension.FromPixelsAndPercent(40f, 0f),
                Height = new StyleDimension(40f, 0f),
                HAlign = 0f,
                Top = StyleDimension.FromPixelsAndPercent(num5, 0f),
                ShowHighlightWhenSelected = false
            };
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/WorldCreation/IconEvilRandom", 1))
            {
                IgnoresMouseInteraction = true,
                HAlign = 0.5f,
                VAlign = 0.5f
            };
            groupOptionButton.Append(uiimage);
            groupOptionButton.OnLeftMouseDown += this.ClickRandomizeSeed;
            groupOptionButton.OnMouseOver += this.ShowOptionDescription;
            groupOptionButton.OnMouseOut += this.ClearOptionDescription;
            groupOptionButton.SetSnapPoint("RandomizeSeed", 0, null, null);
            infoContainer.Append(groupOptionButton);
            this._randomButton = groupOptionButton;
            UICharacterNameButton uicharacterNameButton = new UICharacterNameButton(Language.GetText("UI.WorldCreationSeed"), Language.GetText("UI.WorldCreationSeedEmpty"), Language.GetText("UI.WorldDescriptionSeed"))
            {
                Width = StyleDimension.FromPixelsAndPercent(-num3, 1f),
                HAlign = 0f,
                Left = new StyleDimension(num4, 0f),
                Top = StyleDimension.FromPixelsAndPercent(num5, 0f),
                DistanceFromTitleToOption = 29f
            };
            uicharacterNameButton.OnLeftMouseDown += this.Click_SetSeed;
            uicharacterNameButton.OnMouseOver += this.ShowOptionDescription;
            uicharacterNameButton.OnMouseOut += this.ClearOptionDescription;
            uicharacterNameButton.SetSnapPoint("Seed", 0, null, null);
            infoContainer.Append(uicharacterNameButton);
            this._seedPlate = uicharacterNameButton;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.Click_SetSeed(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClickRandomizeSeed(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowOptionDescription(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeInfoMenu().