Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions
AddSpecialSeedOptions()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions (UIList listArea) inline private
Definition at line 190 of file UIWorldCreationAdvanced.cs.
        {
            int num = 6;
            GroupOptionButton<AWorldGenerationOption>[] array = this.PrepareSeedButtons();
            this._seedButtons = array;
            this._seedButtonRegion = new UIElement
            {
                Width = StyleDimension.FromPercent(1f),
                Height = StyleDimension.FromPixels((float)Math.Ceiling((double)array.Length / (double)num) * 70f - 10f)
            };
            listArea.Add(this._seedButtonRegion);
            for (int i = 0; i < array.Length; i++)
            {
                GroupOptionButton<AWorldGenerationOption> groupOptionButton = array[i];
                int num2 = i % 6;
                int num3 = i / 6;
                groupOptionButton.HAlign = (float)num2 / 5f;
                groupOptionButton.Top.Set((float)(num3 * 67 + 3), 0f);
                groupOptionButton.OnLeftMouseDown += this.ClickSeedOption;
                groupOptionButton.SetSnapPoint("seeds", i, null, null);
                this._seedButtonRegion.Append(groupOptionButton);
                array[i] = groupOptionButton;
            }
            this.RefreshSecretSeedButton();
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._seedButtonRegion, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), System.array, System.Math.Ceiling(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClickSeedOption(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.Height, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.PrepareSeedButtons(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddListArea().