Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddListArea
AddListArea()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddListArea (UIElement infoContainer) inline private
Definition at line 107 of file UIWorldCreationAdvanced.cs.
        {
            int num = 0;
            UIList uilist = new UIList
            {
                Width = StyleDimension.FromPixelsAndPercent(-48f, 1f),
                Height = StyleDimension.FromPixelsAndPercent((float)(-138 - num * 2), 1f),
                HAlign = 0f,
                VAlign = 0f,
                Top = StyleDimension.FromPixels((float)(44 + num)),
                Left = StyleDimension.FromPixels(24f)
            };
            num = 4;
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                Height = StyleDimension.FromPixelsAndPercent((float)(-138 - num * 2), 1f),
                Top = StyleDimension.FromPixels((float)(44 + num)),
                HAlign = 1f
            };
            uilist.SetScrollbar(uiscrollbar);
            infoContainer.Append(uilist);
            if (this._allowScrolling)
            {
                infoContainer.Append(uiscrollbar);
            }
            this.AddSpecialSeedOptions(uilist);
            this._optionList = uilist;
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._allowScrolling, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions(), Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeInfoMenu().