Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UpdateContents
UpdateContents()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UpdateContents () inline private
Definition at line 37 of file UIWorldCreationAdvanced.cs.
        {
            this._creationState.FillSeedContent(this._seedPlate);
            foreach (GroupOptionButton<AWorldGenerationOption> groupOptionButton in this._seedButtons)
            {
                groupOptionButton.SetCurrentOption(groupOptionButton.OptionValue.Enabled ? groupOptionButton.OptionValue : null);
            }
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._creationState, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._seedButtons, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._seedPlate, Terraria.GameContent.UI.States.UIWorldCreation.FillSeedContent(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.OptionValue, and Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClickRandomizeSeed(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClickSeedOption(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.Prepare(), and Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UIWorldCreationAdvanced().