Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.CreateButton
CreateButton()
GroupOptionButton< AWorldGenerationOption > Terraria.GameContent.UI.States.UIWorldCreationAdvanced.CreateButton (UIWorldCreationAdvanced::WorldSpecialSeedOption option) inline private
Definition at line 243 of file UIWorldCreationAdvanced.cs.
        {
            GroupOptionButton<AWorldGenerationOption> groupOptionButton = new GroupOptionButton<AWorldGenerationOption>(option.Seed, null, option.Description, Color.White, null, 1f, 1f, 16f)
            {
                Width = StyleDimension.FromPixels(60f),
                Height = StyleDimension.FromPixels(60f),
                InnerHighlightRim = 4
            };
            groupOptionButton.OnMouseOver += delegate(UIMouseEvent evt, UIElement elem)
            {
                this.ShowOptionDescription(option.Description, option.Title);
            };
            groupOptionButton.OnMouseOut += this.ClearOptionDescription;
            UIElement element = option.Element;
            element.OnUpdate += this.UpdateIconOpacity;
            groupOptionButton.Append(element);
            if (false)
            {
                UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/IconCompletion", 1))
                {
                    HAlign = 0.5f,
                    VAlign = 0.5f,
                    Top = new StyleDimension(-9f, 0f),
                    Left = new StyleDimension(-3f, 0f),
                    IgnoresMouseInteraction = true
                };
                groupOptionButton.Append(uiimage);
            }
            return groupOptionButton;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClearOptionDescription(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowOptionDescription(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UpdateIconOpacity(), Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.PrepareSeedButtons().