Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 510 of file UIWorldCreationAdvanced.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            int num2 = num;
            this.GetSnapPoints();
            UILinkPoint linkPoint = this._helper.GetLinkPoint(num2++, this._backButton);
            UILinkPoint linkPoint2 = this._helper.GetLinkPoint(num2++, this._seedPlate);
            UILinkPoint linkPoint3 = this._helper.GetLinkPoint(num2++, this._randomButton);
            List<SnapPoint> snapPoints = this._optionList.GetSnapPoints();
            UILinkPoint[,] array = this._helper.CreateUILinkPointGrid(ref num2, snapPoints, 6, linkPoint2, null, null, linkPoint);
            this._helper.PairLeftRight(linkPoint3, linkPoint2);
            UILinkPoint uilinkPoint = array[0, 0];
            this._helper.PairUpDown(linkPoint3, uilinkPoint);
            this._helper.PairUpDown(linkPoint2, uilinkPoint);
            UILinkPoint uilinkPoint2 = array[0, array.GetLength(1) - 1];
            this._helper.PairUpDown(uilinkPoint2, linkPoint);
            this._helper.MoveToVisuallyClosestPoint(num, num2);
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._backButton, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._helper, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._optionList, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._randomButton, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._seedPlate, System.array, Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.GetLinkPoint(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight(), and Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.Draw().