Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton
RefreshSecretSeedButton()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton () inline
Definition at line 137 of file UIWorldCreationAdvanced.cs.
        {
            bool flag = SecretSeedsTracker.SeedsForInterface.Count > 0 || this._creationState.HasEnteredSpecialSeed || this._creationState.HasDisabledSecretSeed;
            if (this._secretSeedButton == null && flag)
            {
                int num = this._seedButtons.Length;
                int num2 = num % 6;
                int num3 = num / 6;
                this._secretSeedButton = new GroupOptionButton<bool>(true, null, null, Color.White, null, 1f, 0.5f, 10f)
                {
                    Width = StyleDimension.FromPixels(60f),
                    Height = StyleDimension.FromPixels(60f),
                    InnerHighlightRim = 4,
                    HAlign = (float)num2 / 5f,
                    Top = StyleDimension.FromPixelsAndPercent((float)(num3 * 67 + 3), 0f),
                    ShowHighlightWhenSelected = true
                };
                this._secretSeedButton.SetCurrentOption(this._creationState.HasEnteredSpecialSeed);
                UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/WorldCreation/Seed_Secret", 1).Value)
                {
                    Left = StyleDimension.FromPixels(-1f)
                };
                uiimage.OnUpdate += this.UpdateIconOpacity;
                this._secretSeedButton.Append(uiimage);
                this._secretSeedButton.SetSnapPoint("seeds", num, null, null);
                this._secretSeedButton.OnMouseOver += this.ShowSecretSeedDescription;
                this._secretSeedButton.OnMouseOut += this.ClearOptionDescription;
                this._secretSeedButton.OnDraw += this._creationState.DrawSpecialSeedRingCallback;
                this._secretSeedButton.OnLeftClick += this.SecretSeedButton_OnLeftClick;
                this._seedButtonRegion.Append(this._secretSeedButton);
                return;
            }
            if (this._secretSeedButton != null && !flag)
            {
                this._seedButtonRegion.RemoveChild(this._secretSeedButton);
                this._secretSeedButton = null;
                return;
            }
            if (this._secretSeedButton != null)
            {
                this._secretSeedButton.SetCurrentOption(this._creationState.HasEnteredSpecialSeed);
            }
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._creationState, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._secretSeedButton, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._seedButtonRegion, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._seedButtons, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.GameContent.UI.States.UIWorldCreation.HasDisabledSecretSeed, Terraria.GameContent.UI.States.UIWorldCreation.HasEnteredSpecialSeed, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.RemoveChild(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SecretSeedButton_OnLeftClick(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowSecretSeedDescription(), Terraria.UI.UIElement.Top, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UpdateIconOpacity(), Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.GoBack(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing().