Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowSecretSeedDescription
ShowSecretSeedDescription()
void Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowSecretSeedDescription (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 370 of file UIWorldCreationAdvanced.cs.
        {
            DynamicSpriteFont value = FontAssets.MouseText.Value;
            string joinedSecretSeedString = this._creationState.GetJoinedSecretSeedString(value, this._descriptionText.GetInnerDimensions().Width / 0.7f, this._descriptionText.GetInnerDimensions().Height / 0.7f);
            this._descriptionText.SetText(joinedSecretSeedString);
            this._titleText.SetText(Language.GetText("UI.WorldDescriptionSecretSeeds_Title"));
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced._creationState, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._descriptionText, Terraria.GameContent.UI.States.UIWorldCreationAdvanced._titleText, Terraria.UI.UIElement.GetInnerDimensions(), Terraria.GameContent.UI.States.UIWorldCreation.GetJoinedSecretSeedString(), Terraria.Localization.Language.GetText(), Terraria.GameContent.FontAssets.MouseText, Terraria.GameContent.UI.Elements.UIText.SetText(), System.value, ReLogic.Content.Asset< T >.Value, and Terraria.UI.CalculatedStyle.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton().