Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreationAdvanced.PrepareSeedButtons
PrepareSeedButtons()
GroupOptionButton< AWorldGenerationOption >[] Terraria.GameContent.UI.States.UIWorldCreationAdvanced.PrepareSeedButtons () inline private
Definition at line 217 of file UIWorldCreationAdvanced.cs.
        {
            List<GroupOptionButton<AWorldGenerationOption>> list = new List<GroupOptionButton<AWorldGenerationOption>>();
            foreach (AWorldGenerationOption aworldGenerationOption in WorldGenerationOptions.Options)
            {
                aworldGenerationOption.Load();
                list.Add(this.CreateButton(new UIWorldCreationAdvanced.WorldSpecialSeedOption
                {
                    Seed = aworldGenerationOption,
                    Description = aworldGenerationOption.Description,
                    Title = aworldGenerationOption.Title,
                    Element = aworldGenerationOption.ProvideUIElement()
                }));
            }
            return list.ToArray();
        }
References Terraria.GameContent.UI.States.UIWorldCreationAdvanced.CreateButton(), System.list, Terraria.WorldBuilding.AWorldGenerationOption.Load(), and Terraria.WorldBuilding.WorldGenerationOptions.Options.
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions().