Terraria Decompiled: Terraria.GameContent.Skies.StardustSky.Activate
Activate()
override void Terraria.GameContent.Skies.StardustSky.Activate (Vector2 position, params object[] args) inline
Definition at line 97 of file StardustSky.cs.
        {
            this._fadeOpacity = 0.002f;
            this._isActive = true;
            int num = 200;
            int num2 = 10;
            this._stars = new StardustSky.Star[num * num2];
            int num3 = 0;
            for (int i = 0; i < num; i++)
            {
                float num4 = (float)i / (float)num;
                for (int j = 0; j < num2; j++)
                {
                    float num5 = (float)j / (float)num2;
                    this._stars[num3].Position.X = num4 * (float)Main.maxTilesX * 16f;
                    this._stars[num3].Position.Y = num5 * ((float)Main.worldSurface * 16f + 2000f) - 1000f;
                    this._stars[num3].Depth = this._random.NextFloat() * 8f + 1.5f;
                    this._stars[num3].TextureIndex = this._random.Next(this._starTextures.Length);
                    this._stars[num3].SinOffset = this._random.NextFloat() * 6.28f;
                    this._stars[num3].AlphaAmplitude = this._random.NextFloat() * 5f;
                    this._stars[num3].AlphaFrequency = this._random.NextFloat() + 1f;
                    num3++;
                }
            }
            Array.Sort<StardustSky.Star>(this._stars, new Comparison<StardustSky.Star>(this.SortMethod));
        }
References Terraria.GameContent.Skies.StardustSky._random, Terraria.GameContent.Skies.StardustSky._stars, Terraria.GameContent.Skies.StardustSky._starTextures, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), System.Array.Sort(), Terraria.GameContent.Skies.StardustSky.SortMethod(), and Terraria.Main.worldSurface.