Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom
GenerateLateDungeonFeaturesInRoom()
override void Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom (DungeonData data) inline virtual
Reimplemented from Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.
Definition at line 108 of file LivingTreeDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            LivingTreeDungeonRoomSettings livingTreeDungeonRoomSettings = (LivingTreeDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickCrackedTileType = this.settings.StyleData.BrickCrackedTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            for (int i = 0; i < 50; i++)
            {
                int num = unifiedRandom.Next(this.InnerBounds.Left + 1, this.InnerBounds.Right);
                int num2 = unifiedRandom.Next(this.InnerBounds.Top + 1, this.InnerBounds.Bottom);
                Point point = DungeonUtils.FirstSolid(false, new Point(num, num2), this.InnerBounds);
                num = point.X;
                num2 = point.Y - 1;
                Tile tile = Main.tile[num, num2];
                if (!tile.active() && tile.wall == brickWallType)
                {
                    if (unifiedRandom.Next(2) == 0)
                    {
                        WorldGen.PlaceTile(num, num2, 187, true, false, -1, unifiedRandom.Next(47, 50));
                    }
                    else
                    {
                        int num3 = unifiedRandom.Next(2);
                        int num4 = 72;
                        if (num3 == 1)
{
                            num4 = unifiedRandom.Next(59, 62);
                        }
                        WorldGen.PlaceSmallPile(num, num2, num4, num3, 185);
                    }
                }
            }
            for (int j = 0; j < 10; j++)
            {
                int num5 = unifiedRandom.Next(this.InnerBounds.Left + 1, this.InnerBounds.Right);
                int num6 = unifiedRandom.Next(this.InnerBounds.Top + 1, this.InnerBounds.Bottom);
                Point point2 = DungeonUtils.FirstSolid(true, new Point(num5, num6), this.InnerBounds);
                num5 = point2.X;
                num6 = point2.Y + 1;
                Tile tile2 = Main.tile[num5, num6];
                Tile tile3 = Main.tile[num5, num6 - 1];
                if (!tile2.active() && tile2.wall == brickWallType && tile3.active() && tile3.type == brickCrackedTileType)
                {
                    ushort num7 = 52;
                    if (brickTileType == 383)
                    {
                        num7 = 62;
                    }
                    for (int k = unifiedRandom.Next(3, 12); k > 0; k--)
                    {
                        Tile tile4 = Main.tile[num5, num6];
                        if (tile4.active())
{
                            break;
                        }
                        tile4.ClearTile();
                        tile4.active(true);
                        tile4.type = num7;
                        if (livingTreeDungeonRoomSettings.OverridePaintTile > -1)
{
                            WorldGen.paintTile(num5, num6, (byte)livingTreeDungeonRoomSettings.OverridePaintTile, false, false);
                        }
                        num6++;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.Tile.ClearTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OverridePaintTile, Terraria.WorldGen.paintTile(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, and Microsoft.Xna.Framework.Point.X.