Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom
LivingTreeRoom()
void Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom (DungeonData data, int i, int j, bool generating) inline
Definition at line 178 of file LivingTreeDungeonRoom.cs.
        {
            UnifiedRandom unifiedRandom = new UnifiedRandom(this.settings.RandomSeed);
            LivingTreeDungeonRoomSettings livingTreeDungeonRoomSettings = (LivingTreeDungeonRoomSettings)this.settings;
            ushort brickTileType = this.settings.StyleData.BrickTileType;
            ushort brickCrackedTileType = this.settings.StyleData.BrickCrackedTileType;
            ushort brickWallType = this.settings.StyleData.BrickWallType;
            Point basePosition = new Point(i, j);
            if (this.calculated)
            {
                basePosition = this.BasePosition;
            }
            Point point = new Point(basePosition.X, basePosition.Y + livingTreeDungeonRoomSettings.InnerHeight / 2);
            int num = point.Y - livingTreeDungeonRoomSettings.InnerHeight;
            int innerWidth = livingTreeDungeonRoomSettings.InnerWidth;
            int depth = livingTreeDungeonRoomSettings.Depth;
            int num2 = innerWidth;
            int num3 = num2 + depth;
            this.OuterBounds.SetBounds(basePosition.X, basePosition.Y, basePosition.X, basePosition.Y);
            this.InnerBounds.SetBounds(basePosition.X, basePosition.Y, basePosition.X, basePosition.Y);
            while (point.Y > num)
            {
                this.OuterBounds.UpdateBounds(point.X - num3, point.Y - num3, point.X + num3, point.Y + num3);
                this.InnerBounds.UpdateBounds(point.X - num2, point.Y - num2, point.X + num2, point.Y + num2);
                this._outerShapeData.AddBounds(point.X - num3 - basePosition.X, point.Y - num3 - basePosition.Y, point.X + num3 - basePosition.X, point.Y + num3 - basePosition.Y);
                this._innerShapeData.AddBounds(point.X - num2 - basePosition.X, point.Y - num2 - basePosition.Y, point.X + num2 - basePosition.X, point.Y + num2 - basePosition.Y);
                if (generating)
                {
                    base.GenerateDungeonSquareRoom(data, point, brickTileType, brickCrackedTileType, brickWallType, livingTreeDungeonRoomSettings.InnerWidth, livingTreeDungeonRoomSettings.Depth, false);
                }
                if (point.Y % 4 == 0)
                {
                    point.X += ((unifiedRandom.Next(2) == 0) ? (-1) : 1);
                }
                point.Y--;
            }
            this.InnerBounds.CalculateHitbox();
            this.OuterBounds.CalculateHitbox();
            this.BasePosition = basePosition;
            this._floodedTileCount = DungeonUtils.CalculateFloodedTileCountFromShapeData(this.InnerBounds, this._innerShapeData);
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom._innerShapeData, Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom._outerShapeData, Terraria.WorldBuilding.ShapeData.AddBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.BasePosition, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickCrackedTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.BrickWallType, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.calculated, Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculateFloodedTileCountFromShapeData(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.CalculateHitbox(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoomSettings.Depth, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.InnerBounds, Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoomSettings.InnerHeight, Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoomSettings.InnerWidth, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.OuterBounds, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RandomSeed, Terraria.GameContent.Generation.Dungeon.DungeonBounds.SetBounds(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Terraria.GameContent.Generation.Dungeon.DungeonBounds.UpdateBounds(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.CalculateRoom(), and Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateRoom().