Terraria Decompiled: Terraria.GameContent.Dyes.ReflectiveArmorShaderData.Apply
Apply()
override void Terraria.GameContent.Dyes.ReflectiveArmorShaderData.Apply (Entity entity, DrawData? drawData) inline virtual
Reimplemented from Terraria.Graphics.Shaders.ArmorShaderData.
Definition at line 31 of file ReflectiveArmorShaderData.cs.
        {
            this.CheckCachedParameters();
            if (entity == null)
            {
                this.uLightSource.SetValue(Vector3.Zero);
            }
            else
            {
                float num = 0f;
                if (drawData != null)
                {
                    num = drawData.Value.rotation;
                }
                Vector2 position = entity.position;
                float num2 = (float)entity.width;
                float num3 = (float)entity.height;
                Vector2 vector = position + new Vector2(num2, num3) * 0.1f;
                num2 *= 0.8f;
                num3 *= 0.8f;
                Vector3 subLight = Lighting.GetSubLight(vector + new Vector2(num2 * 0.5f, 0f));
                Vector3 subLight2 = Lighting.GetSubLight(vector + new Vector2(0f, num3 * 0.5f));
                Vector3 subLight3 = Lighting.GetSubLight(vector + new Vector2(num2, num3 * 0.5f));
                Vector3 subLight4 = Lighting.GetSubLight(vector + new Vector2(num2 * 0.5f, num3));
                float num4 = subLight.X + subLight.Y + subLight.Z;
                float num5 = subLight2.X + subLight2.Y + subLight2.Z;
                float num6 = subLight3.X + subLight3.Y + subLight3.Z;
                float num7 = subLight4.X + subLight4.Y + subLight4.Z;
                Vector2 vector2 = new Vector2(num6 - num5, num7 - num4);
                float num8 = vector2.Length();
                if (num8 > 1f)
                {
                    num8 = 1f;
                    vector2 /= num8;
                }
                if (entity.direction == -1)
                {
                    vector2.X *= -1f;
                }
                vector2 = vector2.RotatedBy((double)(-(double)num), default(Vector2));
                Vector3 vector3 = new Vector3(vector2, 1f - (vector2.X * vector2.X + vector2.Y * vector2.Y));
                vector3.X *= 2f;
                vector3.Y -= 0.15f;
                vector3.Y *= 2f;
                vector3.Normalize();
                vector3.Z *= 0.6f;
                this.uLightSource.SetValue(vector3);
            }
            base.Apply(entity, drawData);
        }
References Terraria.Graphics.Shaders.ShaderData.Apply(), Terraria.GameContent.Dyes.ReflectiveArmorShaderData.CheckCachedParameters(), Terraria.Entity.direction, Terraria.Lighting.GetSubLight(), Terraria.Entity.height, Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector3.Normalize(), Terraria.Entity.position, Terraria.DataStructures.DrawData.rotation, Terraria.GameContent.Dyes.ReflectiveArmorShaderData.uLightSource, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Vector3, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector3.Zero.