Terraria Decompiled: Terraria.GameContent.UI.UIDust.NewDust
NewDust()
Dust Terraria.GameContent.UI.UIDust.NewDust (Vector2 Position, int Width, int Height, int Type, float SpeedX = 0f, float SpeedY = 0f, int Alpha = 0, Color newColor = default(Color), float Scale = 1f) inline
Definition at line 44 of file UIDust.cs.
        {
            if (Type != 6 && Type != 267)
            {
                throw new Exception();
            }
            int num = 200;
            int i = 0;
            while (i < 200)
            {
                Dust dust = this.dust[i];
                if (!dust.active)
                {
                    int num2 = Width;
                    int num3 = Height;
                    if (num2 < 5)
                    {
                        num2 = 5;
                    }
                    if (num3 < 5)
                    {
                        num3 = 5;
                    }
                    num = i;
                    dust.fadeIn = 0f;
                    dust.active = true;
                    dust.type = Type;
                    dust.noGravity = false;
                    dust.color = newColor;
                    dust.alpha = Alpha;
                    dust.position.X = Position.X + (float)Main.rand.Next(num2 - 4) + 4f;
                    dust.position.Y = Position.Y + (float)Main.rand.Next(num3 - 4) + 4f;
                    dust.velocity.X = (float)Main.rand.Next(-20, 21) * 0.1f + SpeedX;
                    dust.velocity.Y = (float)Main.rand.Next(-20, 21) * 0.1f + SpeedY;
                    dust.frame.X = 10 * Type;
                    dust.frame.Y = 10 * Main.rand.Next(3);
                    dust.shader = null;
                    dust.customData = null;
                    dust.noLightEmittance = false;
                    dust.fullBright = false;
                    int j = Type;
                    while (j >= 100)
                    {
                        j -= 100;
                        Dust dust2 = dust;
                        dust2.frame.X = dust2.frame.X - 1000;
                        Dust dust3 = dust;
                        dust3.frame.Y = dust3.frame.Y + 30;
                    }
                    dust.frame.Width = 8;
                    dust.frame.Height = 8;
                    dust.rotation = 0f;
                    dust.scale = 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                    dust.scale *= Scale;
                    dust.noLight = false;
                    dust.firstFrame = true;
                    if (dust.type == 6)
                    {
                        dust.velocity.Y = (float)Main.rand.Next(-10, 6) * 0.1f;
                        Dust dust4 = dust;
                        dust4.velocity.X = dust4.velocity.X * 0.3f;
                        dust.scale *= 0.7f;
                        break;
                    }
                    break;
                }
                else
                {
                    i++;
                }
            }
            return this.dust[num];
        }
References Terraria.Dust.active, Microsoft.Xna.Framework.Graphics.Alpha, Terraria.GameContent.UI.UIDust.dust, Terraria.Main.rand, and Terraria.Dust.type.
Referenced by Terraria.GameContent.UI.UIDust.CloneDust(), Terraria.GameContent.UI.UIDust.NewDustDirect(), Terraria.GameContent.UI.UIDust.NewDustPerfect(), Terraria.GameContent.UI.UIDust.QuickDust(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_BestReforge(), Terraria.GameContent.UI.States.UIWorldCreation.Spawn_RainbowRodHit(), and Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.Spawn_RainbowRodHit().