Terraria Decompiled: Terraria.GameContent.UI.UIDust.UpdateDust
UpdateDust()
void Terraria.GameContent.UI.UIDust.UpdateDust () inline
Definition at line 230 of file UIDust.cs.
        {
            Sandstorm.ShowSandstormVisuals();
            for (int i = 0; i < 200; i++)
            {
                Dust dust = this.dust[i];
                if (dust.active)
                {
                    if (dust.scale > 10f)
                    {
                        dust.active = false;
                    }
                    dust.position += dust.velocity;
                    if (dust.type == 6)
                    {
                        if (!dust.noGravity)
{
                            Dust dust2 = dust;
                            dust2.velocity.Y = dust2.velocity.Y + 0.05f;
                        }
                    }
                    else if (dust.type == 267)
                    {
                        if (dust.velocity.X < 0f)
{
                            dust.rotation -= 1f;
                        }
                        else
{
                            dust.rotation += 1f;
                        }
                        Dust dust3 = dust;
                        dust3.velocity.Y = dust3.velocity.Y * 0.98f;
                        Dust dust4 = dust;
                        dust4.velocity.X = dust4.velocity.X * 0.98f;
                        dust.scale += 0.02f;
                    }
                    Dust dust5 = dust;
                    dust5.velocity.X = dust5.velocity.X * 0.99f;
                    dust.rotation += dust.velocity.X * 0.5f;
                    if (dust.fadeIn > 0f && dust.fadeIn < 100f)
                    {
                        dust.scale += 0.03f;
                        if (dust.scale > dust.fadeIn)
{
                            dust.fadeIn = 0f;
                        }
                    }
                    else
                    {
                        dust.scale -= 0.01f;
                    }
                    if (dust.noGravity)
                    {
                        dust.velocity *= 0.92f;
                        if (dust.fadeIn == 0f)
{
                            dust.scale -= 0.04f;
                        }
                    }
                    float num = 0.1f;
                    if (dust.scale < num)
                    {
                        dust.active = false;
                    }
                }
            }
        }
References Terraria.Dust.active, Terraria.GameContent.UI.UIDust.dust, Terraria.Dust.fadeIn, Terraria.Dust.noGravity, Terraria.Dust.scale, Terraria.GameContent.Events.Sandstorm.ShowSandstormVisuals(), Terraria.Dust.type, Terraria.Dust.velocity, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.DrawSeedSystems(), and Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawSeedSystems().