Terraria Decompiled: Terraria.GameContent.UI.UIDust.DrawDust
DrawDust()
void Terraria.GameContent.UI.UIDust.DrawDust () inline package
Definition at line 300 of file UIDust.cs.
        {
            SpriteBatch spriteBatch = Main.spriteBatch;
            for (int i = 0; i < 200; i++)
            {
                Dust dust = this.dust[i];
                if (dust.active)
                {
                    float visualScale = dust.GetVisualScale();
                    Color color = Lighting.GetColor((int)((double)dust.position.X + 4.0) / 16, (int)((double)dust.position.Y + 4.0) / 16);
                    if (dust.type == 6)
                    {
                        color = Color.White;
                    }
                    color = dust.GetAlpha(color);
                    spriteBatch.Draw(TextureAssets.Dust.Value, dust.position, new Rectangle?(dust.frame), color, dust.GetVisualRotation(), new Vector2(4f, 4f), visualScale, SpriteEffects.None, 0f);
                    if (dust.color.PackedValue != 0U)
                    {
                        Color color2 = dust.GetColor(color);
                        if (color2.PackedValue != 0U)
{
                            spriteBatch.Draw(TextureAssets.Dust.Value, dust.position, new Rectangle?(dust.frame), color2, dust.GetVisualRotation(), new Vector2(4f, 4f), visualScale, SpriteEffects.None, 0f);
                        }
                    }
                    if (color == Color.Black)
                    {
                        dust.active = false;
                    }
                }
            }
        }
References Terraria.Dust.active, Microsoft.Xna.Framework.Color.Black, Terraria.Dust.color, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.TextureAssets.Dust, Terraria.GameContent.UI.UIDust.dust, Terraria.Dust.frame, Terraria.Dust.GetAlpha(), Terraria.Dust.GetColor(), Terraria.Lighting.GetColor(), Terraria.Dust.GetVisualRotation(), Terraria.Dust.GetVisualScale(), Microsoft.Xna.Framework.Color.PackedValue, Terraria.Dust.position, Terraria.Main.spriteBatch, Terraria.Dust.type, System.U, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.DrawSeedSystems(), and Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawSeedSystems().