Terraria Decompiled: System.IO.BinaryWriter.Write
Write() [5/20]
virtual unsafe void System.IO.BinaryWriter.Write (char ch) inline virtual
Definition at line 186 of file BinaryWriter.cs.
        {
            if (char.IsSurrogate(ch))
            {
                throw new ArgumentException(Environment.GetResourceString("Unicode surrogate characters must be written out as pairs together in the same call, not individually. Consider passing in a character array instead."));
            }
            byte[] array;
            byte* ptr;
            if ((array = this._buffer) == null || array.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &array[0];
            }
            int bytes = this._encoder.GetBytes(&ch, 1, ptr, this._buffer.Length, true);
            array = null;
            this.OutStream.Write(this._buffer, 0, bytes);
        }
References System.IO.BinaryWriter._buffer, System.IO.BinaryWriter._encoder, System.array, System.Text.Encoder.GetBytes(), System.Environment.GetResourceString(), System.IO.BinaryWriter.OutStream, and System.IO.Stream.Write().