Terraria Decompiled: System.Globalization.NumberFormatInfo.Clone
Clone()
object System.Globalization.NumberFormatInfo.Clone () inline
Implements System.ICloneable.
Definition at line 196 of file NumberFormatInfo.cs.
        {
            NumberFormatInfo numberFormatInfo = (NumberFormatInfo)base.MemberwiseClone();
            numberFormatInfo.isReadOnly = false;
            return numberFormatInfo;
        }
References System.Globalization.NumberFormatInfo.NumberFormatInfo().
Referenced by System.Globalization.CultureInfo.Clone(), and System.Globalization.CultureInfo.ConstructInvariant().