Terraria Decompiled: Terraria.GameInput.PlayerInput.ExitBuildingMode
ExitBuildingMode()
static void Terraria.GameInput.PlayerInput.ExitBuildingMode (bool quiet = false) inline static
Definition at line 330 of file PlayerInput.cs.
        {
            if (!quiet)
            {
                SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
            }
            PlayerInput._InBuildingMode = false;
            UILinkPointNavigator.ChangePoint(PlayerInput._UIPointForBuildingMode);
            if (Main.mouseItem.stack > 0 && Main.player[Main.myPlayer].itemAnimation == 0)
            {
                int uipointForBuildingMode = PlayerInput._UIPointForBuildingMode;
                if (uipointForBuildingMode < 50 && uipointForBuildingMode >= 0 && Main.player[Main.myPlayer].inventory[uipointForBuildingMode].stack <= 0)
                {
                    Utils.Swap<Item>(ref Main.mouseItem, ref Main.player[Main.myPlayer].inventory[uipointForBuildingMode]);
                }
            }
            PlayerInput._UIPointForBuildingMode = -1;
        }
References Terraria.GameInput.PlayerInput._UIPointForBuildingMode, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.Player.inventory, Terraria.Player.itemAnimation, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Item.stack.
Referenced by Terraria.UI.IngameUIWindows.CloseAll(), Terraria.Player.ToggleInv(), Terraria.GameInput.PlayerInput.UpdateInput(), and Terraria.GameInput.PlayerInput.VerifyBuildingMode().