Terraria Decompiled: System.IO.BinaryWriter.Write
Write() [13/20]
virtual void System.IO.BinaryWriter.Write (ReadOnlySpan< byte > buffer) inline virtual
Definition at line 110 of file BinaryWriter.cs.
        {
            this.Write(buffer.ToArray());
        }
References System.ReadOnlySpan< T >.ToArray(), and System.IO.Write.
Referenced by Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.AttemptPushingChange(), Terraria.GameContent.UnbreakableWallScan.NetModule.BroadcastChange(), Terraria.Social.Steam.NetServerSocialModule.BroadcastConnectedUsers(), Terraria.Netplay.BroadcastThread(), Terraria.NetMessage.CompressTileBlock(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.WorldBuilding.WorldGenSnapshot.Create(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.DebugCall(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DebugCall(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.DeserializeNetMessage(), System.Resources.Win32VersionResource.emit_padding(), Terraria.DataStructures.BinaryWriterHelper.FillOnlyIfThereIsLengthOrRevertToSavedPosition(), Terraria.DataStructures.BinaryWriterHelper.FillReservedPoint(), System.Resources.ResourceWriter.Generate(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.Player.InternalSavePlayerFile(), Terraria.Netplay.KickClient(), Terraria.Net.NetPacket.NetPacket(), Terraria.GameContent.LeashedEntities.LeashedCritter.NetSend(), Terraria.GameContent.LeashedEntities.LeashedKite.NetSend(), Terraria.GameContent.LeashedEntities.NormalButterflyLeashedCritter.NetSend(), Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter.NetSend(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.OnPlayerJoining(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.OnPlayerJoining(), System.Resources.Win32VersionResource.patch_length(), Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.PushChange(), Microsoft.Xna.Framework.Content.SoundEffectReader.Read(), Terraria.GameContent.LeashedEntity.NetModule.Remove(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.RequestUse(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.RequestUse(), Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion(), Terraria.DataStructures.BinaryWriterHelper.ReservePointToFillLengthLaterByFilling6Bytes(), Terraria.GameContent.BannerSystem.Save(), Terraria.GameContent.Bestiary.NPCKillsTracker.Save(), Terraria.GameContent.Bestiary.NPCWasChatWithTracker.Save(), Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.Save(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.Save(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.Save(), Terraria.GameContent.Creative.CreativePowers.FreezeTime.Save(), Terraria.GameContent.Creative.CreativePowers.FreezeWindDirectionAndStrength.Save(), Terraria.GameContent.Creative.CreativePowers.FreezeRainPower.Save(), Terraria.GameContent.Creative.CreativePowers.StopBiomeSpreadPower.Save(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.Save(), Terraria.GameContent.Events.DD2Event.Save(), Terraria.GameContent.TownRoomManager.Save(), Terraria.GameContent.TreeTopsInfo.Save(), Terraria.Utilities.TileSnapshot.Save(), Terraria.GameContent.Creative.CreativePowers.GodmodePower.Save(), Terraria.GameContent.Creative.CreativePowers.FarPlacementRangePower.Save(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.Save(), Terraria.IO.WorldFile.SaveChests(), Terraria.IO.WorldFile.SaveFileFormatHeader(), Terraria.IO.WorldFile.SaveFooter(), Terraria.IO.WorldFile.SaveHeaderPointers(), Terraria.IO.WorldFile.SaveNPCs(), Terraria.GameContent.CraftingRequests.SavePossibleRefunds(), Terraria.Main.SaveRecent(), Terraria.IO.WorldFile.SaveSigns(), Terraria.Player.SaveTemporaryItemSlotContents(), Terraria.IO.WorldFile.SaveTileEntities(), Terraria.IO.WorldFile.SaveWeightedPressurePlates(), Terraria.IO.WorldFile.SaveWorldHeader(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.Chat.ChatCommandId.Serialize(), Terraria.Chat.ChatMessage.Serialize(), Terraria.EquipmentLoadout.Serialize(), Terraria.GameContent.Drawing.ParticleOrchestraSettings.Serialize(), Terraria.Localization.NetworkText.Serialize(), Terraria.Testing.ChatCommands.DebugMessage.Serialize(), Terraria.Item.Serialize(), Terraria.GameContent.NetModules.NetLiquidModule.Serialize(), Terraria.GameContent.NetModules.NetParticlesModule.Serialize(), Terraria.Player.Serialize(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeChat(), Terraria.GameContent.NetModules.NetCreativePowerPermissionsModule.SerializeCurrentPowerPermissionLevel(), Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeKillCount(), System.Threading.Thread.SerializePrincipal(), Terraria.GameContent.NetModules.NetTeleportPylonModule.SerializePylonWasAddedOrRemoved(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeSight(), Terraria.GameContent.NetModules.NetAmbienceModule.SerializeSkyEntitySpawn(), Terraria.Localization.NetworkText.SerializeSubstitutionList(), Terraria.GameContent.NetModules.NetTeleportPylonModule.SerializeUseRequest(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.SetEnabledState(), Terraria.Net.NetPacket.ShrinkToFit(), Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt1Block(), Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt3Block(), Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt5Block(), Terraria.GameContent.LeashedEntity.NetModule.Sync(), Terraria.GameContent.TreeTopsInfo.SyncSend(), Terraria.DataStructures.TrackedProjectileReference.Write(), Terraria.IO.FileMetadata.Write(), Terraria.Utilities.TileSnapshot.TileStruct.Write(), Terraria.GameContent.ExtraSpawnPointManager.Write(), Terraria.DataStructures.TileEntity.Write(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Write(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Write(), System.Resources.ResourceWriter.Write7BitEncodedInt(), Terraria.Utils.Write7BitEncodedInt(), Terraria.NetMessage.WriteAccessoryVisibility(), Terraria.GameContent.QuickStacking.WriteBlockedChestList(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBoolean(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBytes(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteBytes(), Terraria.GameContent.Items.TagEffectState.NetModule.WriteChangeActiveEffect(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteChar(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteChars(), Terraria.GameContent.BannerSystem.NetBannersModule.WriteClaimCountUpdate(), Terraria.GameContent.BannerSystem.NetBannersModule.WriteClaimRequest(), Terraria.GameContent.BannerSystem.NetBannersModule.WriteClaimResponse(), Terraria.Testing.LockstepDebug.WriteControlMessage(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.WriteData(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteDouble(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.WriteDummySync(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.WriteExtraData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.WriteExtraData(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.WriteExtraData(), Terraria.GameContent.Tile_Entities.TEHatRack.WriteExtraData(), Terraria.GameContent.Tile_Entities.TEItemFrame.WriteExtraData(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchorWithItem.WriteExtraData(), Terraria.GameContent.Tile_Entities.TELogicSensor.WriteExtraData(), Terraria.GameContent.Tile_Entities.TETrainingDummy.WriteExtraData(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.WriteExtraData(), Terraria.GameContent.BannerSystem.NetBannersModule.WriteFullState(), Terraria.GameContent.Items.TagEffectState.NetModule.WriteFullState(), Terraria.DataStructures.TileEntity.WriteInner(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt16(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt64(), Terraria.GameContent.Tile_Entities.TEHatRack.WriteItem(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.WriteItem(), Terraria.GameContent.BannerSystem.NetBannersModule.WriteKillCountUpdate(), Terraria.GameContent.QuickStacking.WriteNetInventorySlots(), Terraria.GameContent.Items.TagEffectState.NetModule.WriteNPCChange(), Terraria.Utils.WritePackedVector2(), Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.WriteRequest(), Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.WriteResponse(), Terraria.Utils.WriteRGB(), Terraria.DataStructures.PlayerDeathReason.WriteSelfTo(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.WriteSelfTo(), Terraria.NetMessage.NetSoundInfo.WriteSelfTo(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSingle(), Terraria.GameContent.Items.TagEffectState.NetModule.WriteSparseNPCTimeArray(), Terraria.Testing.LockstepDebug.WriteStep(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteString(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteString(), Terraria.DataStructures.NPCFollowState.WriteTo(), System.Security.Claims.Claim.WriteTo(), System.Security.Claims.ClaimsIdentity.WriteTo(), System.Security.Claims.ClaimsPrincipal.WriteTo(), System.Resources.Win32VersionResource.WriteTo(), System.Resources.Win32GroupIconResource.WriteTo(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteTokenInternal(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteUInt16(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteUInt32(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteUInt64(), Newtonsoft.Json.Bson.BsonBinaryWriter.WriteUtf8Bytes(), System.Resources.ResourceWriter.WriteValue(), and Terraria.Utils.WriteVector2().