Terraria Decompiled: System.IO.BinaryWriter.Write7BitEncodedInt
Write7BitEncodedInt()
void System.IO.BinaryWriter.Write7BitEncodedInt (int value) inline protected
Definition at line 370 of file BinaryWriter.cs.
        {
            uint num;
            for (num = (uint)value; num >= 128U; num >>= 7)
            {
                this.Write((byte)(num | 128U));
            }
            this.Write((byte)num);
        }
References System.U, System.value, and System.IO.Write.
Referenced by Terraria.GameContent.LeashedEntities.LeashedCritter.NetSend(), Terraria.GameContent.LeashedEntities.LeashedKite.NetSend(), Terraria.GameContent.LeashedEntity.NetModule.Remove(), Terraria.GameContent.NetModules.NetBestiaryModule.SerializeKillCount(), Terraria.GameContent.LeashedEntity.NetModule.Sync(), System.IO.BinaryWriter.Write(), and Terraria.GameContent.CraftingRequests.NetCraftingRequestsModule.WriteRequest().