Terraria Decompiled: System.Globalization.NumberFormatInfo.ValidateParseStyleFloatingPoint
ValidateParseStyleFloatingPoint()
static void System.Globalization.NumberFormatInfo.ValidateParseStyleFloatingPoint (NumberStyles style) inline static package
Definition at line 821 of file NumberFormatInfo.cs.
        {
            if ((style & ~(NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign | NumberStyles.AllowTrailingSign | NumberStyles.AllowParentheses | NumberStyles.AllowDecimalPoint | NumberStyles.AllowThousands | NumberStyles.AllowExponent | NumberStyles.AllowCurrencySymbol | NumberStyles.AllowHexSpecifier)) != NumberStyles.None)
            {
                throw new ArgumentException(Environment.GetResourceString("An undefined NumberStyles value is being used."), "style");
            }
            if ((style & NumberStyles.AllowHexSpecifier) != NumberStyles.None)
            {
                throw new ArgumentException(Environment.GetResourceString("The number style AllowHexSpecifier is not supported on floating point data types."));
            }
        }
References System.Environment.GetResourceString().
Referenced by System.Double.Parse(), System.Single.Parse(), System.Decimal.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Single.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Single.Parse(), System.Decimal.TryParse(), System.Double.TryParse(), System.Single.TryParse(), System.Decimal.TryParse(), System.Double.TryParse(), and System.Single.TryParse().