Terraria Decompiled: System.Globalization.NumberFormatInfo.ValidateParseStyleInteger
ValidateParseStyleInteger()
static void System.Globalization.NumberFormatInfo.ValidateParseStyleInteger (NumberStyles style) inline static package
Definition at line 808 of file NumberFormatInfo.cs.
        {
            if ((style & ~(NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite | NumberStyles.AllowLeadingSign | NumberStyles.AllowTrailingSign | NumberStyles.AllowParentheses | NumberStyles.AllowDecimalPoint | NumberStyles.AllowThousands | NumberStyles.AllowExponent | NumberStyles.AllowCurrencySymbol | NumberStyles.AllowHexSpecifier)) != NumberStyles.None)
            {
                throw new ArgumentException(Environment.GetResourceString("An undefined NumberStyles value is being used."), "style");
            }
            if ((style & NumberStyles.AllowHexSpecifier) != NumberStyles.None && (style & ~(NumberStyles.AllowLeadingWhite | NumberStyles.AllowTrailingWhite | NumberStyles.AllowHexSpecifier)) != NumberStyles.None)
            {
                throw new ArgumentException(Environment.GetResourceString("With the AllowHexSpecifier bit set in the enum bit field, the only other valid bits that can be combined into the enum value must be a subset of those in HexNumber."));
            }
        }
References System.Environment.GetResourceString().
Referenced by System.Byte.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.TryParse(), System.Int32.TryParse(), System.Int64.TryParse(), System.SByte.TryParse(), System.Int16.TryParse(), System.UInt32.TryParse(), System.UInt64.TryParse(), System.UInt16.TryParse(), System.Byte.TryParse(), System.Int32.TryParse(), System.Int64.TryParse(), System.SByte.TryParse(), System.Int16.TryParse(), System.UInt32.TryParse(), System.UInt64.TryParse(), and System.UInt16.TryParse().