Terraria Decompiled: XPT.Core.Audio.MP3Sharp.IO.RiffFile.Open
Open() [2/2]
virtual int XPT.Core.Audio.MP3Sharp.IO.RiffFile.Open (string filename, int newMode) inline package virtual
Definition at line 27 of file RiffFile.cs.
        {
            int num = 0;
            if (this.Fmode != 0)
            {
                num = this.Close();
            }
            if (num == 0)
            {
                if (newMode != 1)
                {
                    if (newMode != 2)
                    {
                        goto IL_0241;
                    }
                }
                else
                {
                    try
                    {
                        this._File = RandomAccessFileStream.CreateRandomAccessFile(filename, "rw");
                        try
{
                            sbyte[] array = new sbyte[8];
                            array[0] = (sbyte)(SupportClass.URShift(this._RiffHeader.CkId, 24) & 255);
                            array[1] = (sbyte)(SupportClass.URShift(this._RiffHeader.CkId, 16) & 255);
                            array[2] = (sbyte)(SupportClass.URShift(this._RiffHeader.CkId, 8) & 255);
                            array[3] = (sbyte)(this._RiffHeader.CkId & 255);
                            sbyte b = (sbyte)(SupportClass.URShift(this._RiffHeader.CkSize, 24) & 255);
                            sbyte b2 = (sbyte)(SupportClass.URShift(this._RiffHeader.CkSize, 16) & 255);
                            sbyte b3 = (sbyte)(SupportClass.URShift(this._RiffHeader.CkSize, 8) & 255);
                            sbyte b4 = (sbyte)(this._RiffHeader.CkSize & 255);
                            array[4] = b4;
                            array[5] = b3;
                            array[6] = b2;
                            array[7] = b;
                            this._File.Write(SupportClass.ToByteArray(array), 0, 8);
                            this.Fmode = 1;
                        }
                        catch
{
                            this._File.Close();
                            this.Fmode = 0;
                        }
                        return num;
                    }
                    catch
                    {
                        this.Fmode = 0;
                        return 3;
                    }
                }
                try
                {
                    this._File = RandomAccessFileStream.CreateRandomAccessFile(filename, "r");
                    try
                    {
                        sbyte[] array2 = new sbyte[8];
                        SupportClass.ReadInput(this._File, ref array2, 0, 8);
                        this.Fmode = 2;
                        this._RiffHeader.CkId = (((int)array2[0] << 24) & (int)SupportClass.Identity((long)((ulong)(-16777216)))) | (((int)array2[1] << 16) & 16711680) | (((int)array2[2] << 8) & 65280) | ((int)array2[3] & 255);
                        this._RiffHeader.CkSize = (((int)array2[4] << 24) & (int)SupportClass.Identity((long)((ulong)(-16777216)))) | (((int)array2[5] << 16) & 16711680) | (((int)array2[6] << 8) & 65280) | ((int)array2[7] & 255);
                    }
                    catch
                    {
                        this._File.Close();
                        this.Fmode = 0;
                    }
                    return num;
                }
                catch
                {
                    this.Fmode = 0;
                    return 3;
                }
                IL_0241:
                num = 4;
            }
            return num;
        }
References XPT.Core.Audio.MP3Sharp.IO.RiffFile._File, XPT.Core.Audio.MP3Sharp.IO.RiffFile._RiffHeader, System.array, XPT.Core.Audio.MP3Sharp.IO.RiffFile.Close(), System.IO.Stream.Close(), XPT.Core.Audio.MP3Sharp.IO.RandomAccessFileStream.CreateRandomAccessFile(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Fmode, XPT.Core.Audio.MP3Sharp.Support.SupportClass.Identity(), int, XPT.Core.Audio.MP3Sharp.Support.SupportClass.ReadInput(), XPT.Core.Audio.MP3Sharp.Support.SupportClass.ToByteArray(), XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift(), and System.IO.Stream.Write().