Terraria Decompiled: XPT.Core.Audio.MP3Sharp.IO.RiffFile.Close
Close()
virtual int XPT.Core.Audio.MP3Sharp.IO.RiffFile.Close () inline package virtual
Reimplemented in XPT.Core.Audio.MP3Sharp.IO.WaveFile.
Definition at line 347 of file RiffFile.cs.
        {
            int num = 0;
            int fmode = this.Fmode;
            if (fmode != 1)
            {
                if (fmode != 2)
                {
                    goto IL_013F;
                }
            }
            else
            {
                try
                {
                    this._File.Seek(0L, 0);
                    try
                    {
                        sbyte[] array = new sbyte[]
{
                            (sbyte)(SupportClass.URShift(this._RiffHeader.CkId, 24) & 255),
                            (sbyte)(SupportClass.URShift(this._RiffHeader.CkId, 16) & 255),
                            (sbyte)(SupportClass.URShift(this._RiffHeader.CkId, 8) & 255),
                            (sbyte)(this._RiffHeader.CkId & 255),
                            default(sbyte),
                            default(sbyte),
                            default(sbyte),
                            (sbyte)(SupportClass.URShift(this._RiffHeader.CkSize, 24) & 255)
                        };
                        array[6] = (sbyte)(SupportClass.URShift(this._RiffHeader.CkSize, 16) & 255);
                        array[5] = (sbyte)(SupportClass.URShift(this._RiffHeader.CkSize, 8) & 255);
                        array[4] = (sbyte)(this._RiffHeader.CkSize & 255);
                        this._File.Write(SupportClass.ToByteArray(array), 0, 8);
                        this._File.Close();
                    }
                    catch
                    {
                        num = 3;
                    }
                    goto IL_013F;
                }
                catch
                {
                    num = 3;
                    goto IL_013F;
                }
            }
            try
            {
                this._File.Close();
            }
            catch
            {
                num = 3;
            }
            IL_013F:
            this._File = null;
            this.Fmode = 0;
            return num;
        }
References XPT.Core.Audio.MP3Sharp.IO.RiffFile._File, XPT.Core.Audio.MP3Sharp.IO.RiffFile._RiffHeader, System.array, System.IO.Stream.Close(), XPT.Core.Audio.MP3Sharp.IO.RiffFile.Fmode, System.L, System.IO.Stream.Seek(), XPT.Core.Audio.MP3Sharp.Support.SupportClass.ToByteArray(), XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift(), and System.IO.Stream.Write().
Referenced by XPT.Core.Audio.MP3Sharp.IO.RiffFile.Open(), and XPT.Core.Audio.MP3Sharp.IO.RiffFile.Open().