Terraria Decompiled: Terraria.GameInput.PlayerInput.CheckRebindingProcessGamepad
CheckRebindingProcessGamepad()
static bool Terraria.GameInput.PlayerInput.CheckRebindingProcessGamepad (string newKey) inline static private
Definition at line 1340 of file PlayerInput.cs.
        {
            PlayerInput._canReleaseRebindingLock = false;
            if (!PlayerInput.CurrentlyRebinding)
            {
                return PlayerInput.NavigatorRebindingLock > 0;
            }
            if (PlayerInput.CurrentlyRebinding && PlayerInput._listeningInputMode == InputMode.XBoxGamepad)
            {
                PlayerInput.NavigatorRebindingLock = 3;
                PlayerInput._memoOfLastPoint = UILinkPointNavigator.CurrentPoint;
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                if (PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus[PlayerInput.ListeningTrigger].Contains(newKey))
                {
                    PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus[PlayerInput.ListeningTrigger].Remove(newKey);
                }
                else
                {
                    PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepad].KeyStatus[PlayerInput.ListeningTrigger] = new List<string> { newKey };
                }
                PlayerInput.ListenFor(null, InputMode.XBoxGamepad);
            }
            if (PlayerInput.CurrentlyRebinding && PlayerInput._listeningInputMode == InputMode.XBoxGamepadUI)
            {
                PlayerInput.NavigatorRebindingLock = 3;
                PlayerInput._memoOfLastPoint = UILinkPointNavigator.CurrentPoint;
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                if (PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus[PlayerInput.ListeningTrigger].Contains(newKey))
                {
                    PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus[PlayerInput.ListeningTrigger].Remove(newKey);
                }
                else
                {
                    PlayerInput.CurrentProfile.InputModes[InputMode.XBoxGamepadUI].KeyStatus[PlayerInput.ListeningTrigger] = new List<string> { newKey };
                }
                PlayerInput.ListenFor(null, InputMode.XBoxGamepadUI);
            }
            PlayerInput.FixDerpedRebinds();
            if (PlayerInput.OnBindingChange != null)
            {
                PlayerInput.OnBindingChange();
            }
            return PlayerInput.NavigatorRebindingLock > 0;
        }
References Terraria.GameInput.PlayerInput._listeningInputMode, Terraria.GameInput.PlayerInput.CurrentlyRebinding, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.FixDerpedRebinds(), Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.GameInput.PlayerInput.ListenFor(), Terraria.GameInput.PlayerInput.ListeningTrigger, Terraria.GameInput.PlayerInput.OnBindingChange, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.GameInput.PlayerInput.GamePadInput().