Terraria Decompiled: Terraria.GameInput.PlayerInput.ComposeInstructionsForGamepad
ComposeInstructionsForGamepad()
static string Terraria.GameInput.PlayerInput.ComposeInstructionsForGamepad () inline static
Definition at line 1536 of file PlayerInput.cs.
        {
            string text = string.Empty;
            InputMode inputMode = InputMode.XBoxGamepad;
            if (Main.gameMenu || UILinkPointNavigator.Available)
            {
                inputMode = InputMode.XBoxGamepadUI;
            }
            if (PlayerInput.InBuildingMode && !Main.gameMenu)
            {
                inputMode = InputMode.XBoxGamepad;
            }
            KeyConfiguration keyConfiguration = PlayerInput.CurrentProfile.InputModes[inputMode];
            Player localPlayer = Main.LocalPlayer;
            if (Main.mapFullscreen && !Main.gameMenu)
            {
                text += "          ";
                text += PlayerInput.BuildCommand(Lang.misc[56].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Inventory"] });
                text += PlayerInput.BuildCommand(Lang.inter[118].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["HotbarPlus"] });
                text += PlayerInput.BuildCommand(Lang.inter[119].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["HotbarMinus"] });
                if (Main.netMode == 1 && Main.player[Main.myPlayer].HasItem(2997))
                {
                    text += PlayerInput.BuildCommand(Lang.inter[120].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                }
            }
            else if (inputMode == InputMode.XBoxGamepadUI && !PlayerInput.InBuildingMode)
            {
                text = UILinkPointNavigator.GetInstructions();
            }
            else if ((localPlayer.dead && localPlayer.CanDeathSpectate && localPlayer.AnyoneToSpectate()) || localPlayer.spectating >= 0)
            {
                string textValue = Language.GetTextValue((localPlayer.spectating >= 0) ? "Game.GamepadSpectateChangeTarget" : "Game.GamepadSpectate");
                text += PlayerInput.BuildCommand(textValue, new List<string>[]
                {
                    keyConfiguration.KeyStatus["Left"],
                    keyConfiguration.KeyStatus["Right"]
                });
                if (localPlayer.spectating >= 0)
                {
                    text += PlayerInput.BuildCommand(Language.GetTextValue("Game.GamepadSpectateCancel"), new List<string>[] { keyConfiguration.KeyStatus["Jump"] });
                }
                if (localPlayer.CanWormholeToSpectating())
                {
                    text += PlayerInput.BuildCommand(Language.GetTextValue("Game.GamepadSpectateWormhole"), new List<string>[] { keyConfiguration.KeyStatus["QuickBuff"] });
                }
            }
            else
            {
                if (localPlayer.dead)
                {
                    return text;
                }
                text += PlayerInput.BuildCommand(Lang.misc[58].Value, new List<string>[] { keyConfiguration.KeyStatus["Jump"] });
                text += PlayerInput.BuildCommand(Lang.misc[59].Value, new List<string>[]
                {
                    keyConfiguration.KeyStatus["HotbarMinus"],
                    keyConfiguration.KeyStatus["HotbarPlus"]
                });
                if (PlayerInput.InBuildingMode)
                {
                    text += PlayerInput.BuildCommand(Lang.menu[6].Value, new List<string>[]
                    {
                        keyConfiguration.KeyStatus["Inventory"],
                        keyConfiguration.KeyStatus["MouseRight"]
                    });
                }
                if (WiresUI.Open)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[53].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseLeft"] });
                    text += PlayerInput.BuildCommand(Lang.misc[56].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                }
                else
                {
                    Item item = Main.player[Main.myPlayer].inventory[Main.player[Main.myPlayer].selectedItem];
                    if (item.damage > 0 && item.ammo == 0)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[60].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseLeft"] });
                    }
                    else if (item.createTile >= 0 || item.createWall > 0)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[61].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseLeft"] });
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[63].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseLeft"] });
                    }
                    bool flag = true;
                    bool flag2 = Main.SmartInteractProj != -1 || Main.HasInteractableObjectThatIsNotATile;
                    bool flag3 = !Main.SmartInteractShowingGenuine && Main.SmartInteractShowingFake;
                    if (Main.SmartInteractShowingGenuine || Main.SmartInteractShowingFake || flag2)
                    {
                        if (Main.SmartInteractNPC != -1)
{
                            if (flag3)
{
                                flag = false;
                            }
                            text += PlayerInput.BuildCommand(Lang.misc[80].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                        }
                        else if (flag2)
{
                            if (flag3)
{
                                flag = false;
                            }
                            text += PlayerInput.BuildCommand(Lang.misc[79].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                        }
                        else if (Main.SmartInteractX != -1 && Main.SmartInteractY != -1)
{
                            if (flag3)
{
                                flag = false;
                            }
                            Tile tile = Main.tile[Main.SmartInteractX, Main.SmartInteractY];
                            if (TileID.Sets.TileInteractRead[(int)tile.type])
{
                                text += PlayerInput.BuildCommand(Lang.misc[81].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                            }
                            else
{
                                text += PlayerInput.BuildCommand(Lang.misc[79].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                            }
                        }
                    }
                    else if (WiresUI.Settings.DrawToolModeUI)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[89].Value, new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                    }
                    else if (ItemID.Sets.HasRightFire[item.type])
                    {
                        text += PlayerInput.BuildCommand(Language.GetTextValue("UI.ActionAltAction"), new List<string>[] { keyConfiguration.KeyStatus["MouseRight"] });
                    }
                    if ((!PlayerInput.GrappleAndInteractAreShared || (!WiresUI.Settings.DrawToolModeUI && (!Main.SmartInteractShowingGenuine || !Main.HasSmartInteractTarget) && (!Main.SmartInteractShowingFake || flag) && !ItemID.Sets.HasRightFire[item.type])) && Main.LocalPlayer.QuickGrapple_GetItemToUse() != null)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[57].Value, new List<string>[] { keyConfiguration.KeyStatus["Grapple"] });
                    }
                }
            }
            return text;
        }
References Terraria.Player.AnyoneToSpectate(), Terraria.UI.Gamepad.UILinkPointNavigator.Available, Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.Player.CanDeathSpectate, Terraria.Player.CanWormholeToSpectating(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Player.dead, Terraria.Main.gameMenu, Terraria.UI.Gamepad.UILinkPointNavigator.GetInstructions(), Terraria.Localization.Language.GetTextValue(), Terraria.Player.HasItem(), Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.Lang.inter, Terraria.GameInput.KeyConfiguration.KeyStatus, Terraria.Main.LocalPlayer, Terraria.Main.mapFullscreen, Terraria.Lang.misc, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Player.spectating, System.text, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.DrawGamepadInstructions(), and Terraria.Main.HackForGamepadInputHell().