Terraria Decompiled: Terraria.GameInput.PlayerInput.LockGamepadButtons
LockGamepadButtons()
static void Terraria.GameInput.PlayerInput.LockGamepadButtons (string TriggerName) inline static
Definition at line 565 of file PlayerInput.cs.
        {
            List<string> list = null;
            KeyConfiguration keyConfiguration = null;
            if (PlayerInput.CurrentProfile.InputModes.TryGetValue(PlayerInput.CurrentInputMode, out keyConfiguration) && keyConfiguration.KeyStatus.TryGetValue(TriggerName, out list))
            {
                PlayerInput._buttonsLocked.AddRange(list);
            }
        }
References Terraria.GameInput.PlayerInput._buttonsLocked, System.Collections.Generic.List< T >.AddRange(), Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInputProfile.InputModes, Terraria.GameInput.KeyConfiguration.KeyStatus, System.list, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.Map.TeleportPylonsMapLayer.Draw(), Terraria.Initializers.UILinksInitializer.FancyUISpecialInstructions(), Terraria.UI.ItemSlot.GetCraftSlotGamepadInstructions(), and Terraria.UI.ItemSlot.GetGamepadInstructions().