Terraria Decompiled: Terraria.GameInput.PlayerInput.FixDerpedRebinds
FixDerpedRebinds()
static void Terraria.GameInput.PlayerInput.FixDerpedRebinds () inline static private
Definition at line 1289 of file PlayerInput.cs.
        {
            List<string> list = new List<string> { "MouseLeft", "MouseRight", "Inventory" };
            foreach (object obj in Enum.GetValues(typeof(InputMode)))
            {
                InputMode inputMode = (InputMode)obj;
                if (inputMode != InputMode.Mouse)
                {
                    PlayerInput.FixKeysConflict(inputMode, list);
                    foreach (string text in list)
                    {
                        if (PlayerInput.CurrentProfile.InputModes[inputMode].KeyStatus[text].Count < 1)
{
                            PlayerInput.ResetKeyBinding(inputMode, text);
                        }
                    }
                }
            }
        }
References Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.FixKeysConflict(), System.Enum.GetValues(), Terraria.GameInput.PlayerInputProfile.InputModes, System.list, System.obj, Terraria.GameInput.PlayerInput.ResetKeyBinding(), and System.text.
Referenced by Terraria.GameInput.PlayerInput.CheckRebindingProcessGamepad(), and Terraria.GameInput.PlayerInput.CheckRebindingProcessKeyboard().