Terraria Decompiled: Terraria.GameInput.PlayerInput.ResetInputsOnActiveStateChange
ResetInputsOnActiveStateChange()
static void Terraria.GameInput.PlayerInput.ResetInputsOnActiveStateChange () inline static
Definition at line 233 of file PlayerInput.cs.
        {
            bool allowInputProcessing = FocusHelper.AllowInputProcessing;
            if (PlayerInput._lastActivityState != allowInputProcessing)
            {
                PlayerInput.MouseInfo = default(MouseState);
                PlayerInput.MouseInfoOld = default(MouseState);
                Main.keyState = Keyboard.GetState();
                Main.inputText = Keyboard.GetState();
                Main.oldInputText = Keyboard.GetState();
                Main.keyCount = 0;
                PlayerInput.Triggers.Reset();
                PlayerInput.Triggers.Reset();
                string text = "";
                List<Keys> pressedKeys = PlayerInput.GetPressedKeys();
                for (int i = 0; i < pressedKeys.Count; i++)
                {
                    text = text + pressedKeys[i] + ", ";
                }
                PlayerInput._invalidatorCheck = text;
            }
            PlayerInput._lastActivityState = allowInputProcessing;
        }
References Terraria.GameInput.PlayerInput._lastActivityState, Terraria.FocusHelper.AllowInputProcessing, System.Collections.Generic.List< T >.Count, Terraria.GameInput.PlayerInput.GetPressedKeys(), Microsoft.Xna.Framework.Input.Keyboard.GetState(), Terraria.GameInput.TriggersPack.Reset(), System.text, and Terraria.GameInput.PlayerInput.Triggers.
Referenced by Terraria.Main.DoUpdate().