Terraria Decompiled: System.Globalization.NumberFormatInfo.GetInstance
GetInstance()
static NumberFormatInfo System.Globalization.NumberFormatInfo.GetInstance (IFormatProvider formatProvider) inline static
Definition at line 164 of file NumberFormatInfo.cs.
        {
            CultureInfo cultureInfo = formatProvider as CultureInfo;
            if (cultureInfo != null && !cultureInfo.m_isInherited)
            {
                NumberFormatInfo numberFormatInfo = cultureInfo.numInfo;
                if (numberFormatInfo != null)
                {
                    return numberFormatInfo;
                }
                return cultureInfo.NumberFormat;
            }
            else
            {
                NumberFormatInfo numberFormatInfo = formatProvider as NumberFormatInfo;
                if (numberFormatInfo != null)
                {
                    return numberFormatInfo;
                }
                if (formatProvider != null)
                {
                    numberFormatInfo = formatProvider.GetFormat(typeof(NumberFormatInfo)) as NumberFormatInfo;
                    if (numberFormatInfo != null)
                    {
                        return numberFormatInfo;
                    }
                }
                return NumberFormatInfo.CurrentInfo;
            }
        }
References System.Globalization.NumberFormatInfo.CurrentInfo, System.IFormatProvider.GetFormat(), System.Globalization.CultureInfo.m_isInherited, System.Globalization.CultureInfo.NumberFormat, System.Globalization.NumberFormatInfo.NumberFormatInfo(), and System.Globalization.CultureInfo.numInfo.
Referenced by System.Number.FormatInt32(), System.Number.FormatInt64(), System.Number.FormatUInt32(), System.Number.FormatUInt64(), System.NumberFormatter.GetNumberFormatInstance(), System.Double.Parse(), System.Single.Parse(), System.Byte.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Decimal.Parse(), System.Byte.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Byte.Parse(), System.Decimal.Parse(), System.Double.Parse(), System.Int16.Parse(), System.Int32.Parse(), System.Int64.Parse(), System.SByte.Parse(), System.Single.Parse(), System.UInt16.Parse(), System.UInt32.Parse(), System.UInt64.Parse(), System.Decimal.ToString(), System.Double.ToString(), System.Single.ToString(), System.Numerics.Vector< T >.ToString(), System.Decimal.ToString(), System.Double.ToString(), System.Single.ToString(), System.Decimal.TryFormat(), System.Double.TryFormat(), System.Single.TryFormat(), System.Number.TryFormatInt32(), System.Number.TryFormatInt64(), System.Number.TryFormatUInt32(), System.Number.TryFormatUInt64(), System.Byte.TryParse(), System.Decimal.TryParse(), System.Double.TryParse(), System.Single.TryParse(), System.Int32.TryParse(), System.Int64.TryParse(), System.SByte.TryParse(), System.Int16.TryParse(), System.UInt32.TryParse(), System.UInt64.TryParse(), System.UInt16.TryParse(), System.Byte.TryParse(), System.Decimal.TryParse(), System.Double.TryParse(), System.Single.TryParse(), System.Int32.TryParse(), System.Int64.TryParse(), System.SByte.TryParse(), System.Int16.TryParse(), System.UInt32.TryParse(), System.UInt64.TryParse(), and System.UInt16.TryParse().