Terraria Decompiled: Terraria.GameInput.PlayerInput.Load
Load()
static void Terraria.GameInput.PlayerInput.Load () inline static
Definition at line 459 of file PlayerInput.cs.
        {
            Main.InputProfiles.Load();
            Dictionary<string, PlayerInputProfile> dictionary = new Dictionary<string, PlayerInputProfile>();
            string text = null;
            Main.InputProfiles.Get<string>("Selected Profile", ref text);
            List<string> allKeys = Main.InputProfiles.GetAllKeys();
            for (int i = 0; i < allKeys.Count; i++)
            {
                string text2 = allKeys[i];
                if (!(text2 == "Selected Profile") && !string.IsNullOrEmpty(text2))
                {
                    Dictionary<string, object> dictionary2 = new Dictionary<string, object>();
                    Main.InputProfiles.Get<Dictionary<string, object>>(text2, ref dictionary2);
                    if (dictionary2.Count > 0)
                    {
                        PlayerInputProfile playerInputProfile = new PlayerInputProfile(text2);
                        playerInputProfile.Initialize(PresetProfiles.None);
                        if (playerInputProfile.Load(dictionary2))
{
                            dictionary.Add(text2, playerInputProfile);
                        }
                    }
                }
            }
            if (dictionary.Count > 0)
            {
                PlayerInput.Profiles = dictionary;
                if (!string.IsNullOrEmpty(text) && PlayerInput.Profiles.ContainsKey(text))
                {
                    PlayerInput.SetSelectedProfile(text);
                    return;
                }
                PlayerInput.SetSelectedProfile(PlayerInput.Profiles.Keys.First<string>());
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.dictionary, Terraria.GameInput.PlayerInputProfile.Initialize(), Terraria.Main.InputProfiles, Terraria.GameInput.PlayerInputProfile.Load(), Terraria.GameInput.PlayerInput.Profiles, Terraria.GameInput.PlayerInput.SetSelectedProfile(), and System.text.
Referenced by Terraria.Main.LoadSettings().