Terraria Decompiled: Steamworks.InteropHelp.TestIfAvailableGameServer
TestIfAvailableGameServer()
static void Steamworks.InteropHelp.TestIfAvailableGameServer () inline static
Definition at line 28 of file InteropHelp.cs.
        {
            InteropHelp.TestIfPlatformSupported();
            if (CSteamGameServerAPIContext.GetSteamClient() == IntPtr.Zero && !CSteamGameServerAPIContext.Init())
            {
                throw new InvalidOperationException("Steamworks GameServer is not initialized.");
            }
        }
References Steamworks.CSteamGameServerAPIContext.GetSteamClient(), Steamworks.CSteamGameServerAPIContext.Init(), Steamworks.InteropHelp.TestIfPlatformSupported(), and System.IntPtr.Zero.
Referenced by Steamworks.SteamGameServerNetworkingSockets.AcceptConnection(), Steamworks.SteamGameServerNetworking.AcceptP2PSessionWithUser(), Steamworks.SteamGameServerNetworkingMessages.AcceptSessionWithUser(), Steamworks.SteamGameServerUGC.AddAppDependency(), Steamworks.SteamGameServerUGC.AddContentDescriptor(), Steamworks.SteamGameServerUGC.AddDependency(), Steamworks.SteamGameServerUGC.AddExcludedTag(), Steamworks.SteamGameServerUGC.AddItemKeyValueTag(), Steamworks.SteamGameServerUGC.AddItemPreviewFile(), Steamworks.SteamGameServerUGC.AddItemPreviewVideo(), Steamworks.SteamGameServerUGC.AddItemToFavorites(), Steamworks.SteamGameServerInventory.AddPromoItem(), Steamworks.SteamGameServerInventory.AddPromoItems(), Steamworks.SteamGameServerUGC.AddRequiredKeyValueTag(), Steamworks.SteamGameServerUGC.AddRequiredTag(), Steamworks.SteamGameServerUGC.AddRequiredTagGroup(), Steamworks.SteamGameServerNetworkingUtils.AllocateMessage(), Steamworks.SteamGameServerNetworking.AllowP2PPacketRelay(), Steamworks.SteamGameServer.AssociateWithClan(), Steamworks.SteamGameServerNetworkingSockets.BeginAsyncRequestFakeIP(), Steamworks.SteamGameServer.BeginAuthSession(), Steamworks.SteamGameServerUGC.BInitWorkshopForGameServer(), Steamworks.SteamGameServer.BLoggedOn(), Steamworks.SteamGameServerUtils.BOverlayNeedsPresent(), Steamworks.SteamGameServerClient.BReleaseSteamPipe(), Steamworks.SteamGameServer.BSecure(), Steamworks.SteamGameServerClient.BShutdownIfAllPipesClosed(), Steamworks.SteamGameServer.BUpdateUserData(), Steamworks.SteamGameServer.CancelAuthTicket(), Steamworks.SteamGameServerUtils.CheckFileSignature(), Steamworks.SteamGameServerNetworkingUtils.CheckPingDataUpToDate(), Steamworks.SteamGameServerInventory.CheckResultSteamID(), Steamworks.SteamGameServer.ClearAllKeyValues(), Steamworks.SteamGameServerStats.ClearUserAchievement(), Steamworks.SteamGameServerNetworkingMessages.CloseChannelWithUser(), Steamworks.SteamGameServerNetworkingSockets.CloseConnection(), Steamworks.SteamGameServerNetworkingSockets.CloseListenSocket(), Steamworks.SteamGameServerNetworking.CloseP2PChannelWithUser(), Steamworks.SteamGameServerNetworking.CloseP2PSessionWithUser(), Steamworks.SteamGameServerNetworkingMessages.CloseSessionWithUser(), Steamworks.SteamGameServer.ComputeNewPlayerCompatibility(), Steamworks.SteamGameServerNetworkingSockets.ConfigureConnectionLanes(), Steamworks.SteamGameServerNetworkingSockets.ConnectByIPAddress(), Steamworks.SteamGameServerNetworkingSockets.ConnectP2P(), Steamworks.SteamGameServerNetworkingSockets.ConnectP2PCustomSignaling(), Steamworks.SteamGameServerClient.ConnectToGlobalUser(), Steamworks.SteamGameServerNetworkingSockets.ConnectToHostedDedicatedServer(), Steamworks.SteamGameServerInventory.ConsumeItem(), Steamworks.SteamGameServerNetworkingUtils.ConvertPingLocationToString(), Steamworks.SteamGameServerNetworking.CreateConnectionSocket(), Steamworks.SteamGameServerHTTP.CreateCookieContainer(), Steamworks.SteamGameServerNetworkingSockets.CreateFakeUDPPort(), Steamworks.SteamGameServerNetworkingSockets.CreateHostedDedicatedServerListenSocket(), Steamworks.SteamGameServerHTTP.CreateHTTPRequest(), Steamworks.SteamGameServerUGC.CreateItem(), Steamworks.SteamGameServerNetworking.CreateListenSocket(), Steamworks.SteamGameServerNetworkingSockets.CreateListenSocketIP(), Steamworks.SteamGameServerNetworkingSockets.CreateListenSocketP2P(), Steamworks.SteamGameServerNetworkingSockets.CreateListenSocketP2PFakeIP(), Steamworks.SteamGameServerClient.CreateLocalUser(), Steamworks.SteamGameServerNetworking.CreateP2PConnectionSocket(), Steamworks.SteamGameServerNetworkingSockets.CreatePollGroup(), Steamworks.SteamGameServerUGC.CreateQueryAllUGCRequest(), Steamworks.SteamGameServerUGC.CreateQueryAllUGCRequest(), Steamworks.SteamGameServerUGC.CreateQueryUGCDetailsRequest(), Steamworks.SteamGameServerUGC.CreateQueryUserUGCRequest(), Steamworks.SteamGameServerNetworkingSockets.CreateSocketPair(), Steamworks.SteamGameServerClient.CreateSteamPipe(), Steamworks.SteamGameServer.CreateUnauthenticatedUserConnection(), Steamworks.SteamGameServerHTTP.DeferHTTPRequest(), Steamworks.SteamGameServerUGC.DeleteItem(), Steamworks.SteamGameServerInventory.DeserializeResult(), Steamworks.SteamGameServerNetworking.DestroyListenSocket(), Steamworks.SteamGameServerNetworkingSockets.DestroyPollGroup(), Steamworks.SteamGameServerInventory.DestroyResult(), Steamworks.SteamGameServerNetworking.DestroySocket(), Steamworks.SteamGameServerUtils.DismissFloatingGamepadTextInput(), Steamworks.SteamGameServerUtils.DismissGamepadTextInput(), Steamworks.SteamGameServerUGC.DownloadItem(), Steamworks.SteamGameServer.EndAuthSession(), Steamworks.SteamGameServerNetworkingUtils.EstimatePingTimeBetweenTwoLocations(), Steamworks.SteamGameServerNetworkingUtils.EstimatePingTimeFromLocalHost(), Steamworks.SteamGameServerInventory.ExchangeItems(), Steamworks.SteamGameServerUtils.FilterText(), Steamworks.SteamGameServerNetworkingSockets.FindRelayAuthTicketForServer(), Steamworks.SteamGameServerNetworkingSockets.FlushMessagesOnConnection(), Steamworks.SteamGameServerInventory.GenerateItems(), Steamworks.SteamGameServerInventory.GetAllItems(), Steamworks.SteamGameServerUtils.GetAPICallFailureReason(), Steamworks.SteamGameServerUtils.GetAPICallResult(), Steamworks.SteamGameServerUGC.GetAppDependencies(), Steamworks.SteamGameServerUtils.GetAppID(), Steamworks.SteamGameServerNetworkingSockets.GetAuthenticationStatus(), Steamworks.SteamGameServer.GetAuthSessionTicket(), Steamworks.SteamGameServerNetworkingSockets.GetCertificateRequest(), Steamworks.SteamGameServerNetworkingUtils.GetConfigValue(), Steamworks.SteamGameServerNetworkingUtils.GetConfigValueInfo(), Steamworks.SteamGameServerUtils.GetConnectedUniverse(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionInfo(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionName(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionRealTimeStatus(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionUserData(), Steamworks.SteamGameServerUtils.GetCurrentBatteryPower(), Steamworks.SteamGameServerNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamGameServerNetworkingUtils.GetDirectPingToPOP(), Steamworks.SteamGameServerInventory.GetEligiblePromoItemDefinitionIDs(), Steamworks.SteamGameServerUtils.GetEnteredGamepadTextInput(), Steamworks.SteamGameServerUtils.GetEnteredGamepadTextLength(), Steamworks.SteamGameServerNetworkingSockets.GetFakeIP(), Steamworks.SteamGameServerNetworkingSockets.GetGameCoordinatorServerLogin(), Steamworks.SteamGameServer.GetGameplayStats(), Steamworks.SteamGameServerNetworkingSockets.GetHostedDedicatedServerAddress(), Steamworks.SteamGameServerNetworkingSockets.GetHostedDedicatedServerPOPID(), Steamworks.SteamGameServerNetworkingSockets.GetHostedDedicatedServerPort(), Steamworks.SteamGameServerHTTP.GetHTTPDownloadProgressPct(), Steamworks.SteamGameServerHTTP.GetHTTPRequestWasTimedOut(), Steamworks.SteamGameServerHTTP.GetHTTPResponseBodyData(), Steamworks.SteamGameServerHTTP.GetHTTPResponseBodySize(), Steamworks.SteamGameServerHTTP.GetHTTPResponseHeaderSize(), Steamworks.SteamGameServerHTTP.GetHTTPResponseHeaderValue(), Steamworks.SteamGameServerHTTP.GetHTTPStreamingResponseBodyData(), Steamworks.SteamGameServerNetworkingSockets.GetIdentity(), Steamworks.SteamGameServerUtils.GetImageRGBA(), Steamworks.SteamGameServerUtils.GetImageSize(), Steamworks.SteamGameServerClient.GetIPCCallCount(), Steamworks.SteamGameServerUtils.GetIPCCallCount(), Steamworks.SteamGameServerUtils.GetIPCountry(), Steamworks.SteamGameServerNetworkingUtils.GetIPv4FakeIPType(), Steamworks.SteamGameServerUtils.GetIPv6ConnectivityState(), Steamworks.SteamGameServerClient.GetISteamApps(), Steamworks.SteamGameServerClient.GetISteamController(), Steamworks.SteamGameServerClient.GetISteamFriends(), Steamworks.SteamGameServerClient.GetISteamGameSearch(), Steamworks.SteamGameServerClient.GetISteamGameServer(), Steamworks.SteamGameServerClient.GetISteamGameServerStats(), Steamworks.SteamGameServerClient.GetISteamGenericInterface(), Steamworks.SteamGameServerClient.GetISteamHTMLSurface(), Steamworks.SteamGameServerClient.GetISteamHTTP(), Steamworks.SteamGameServerClient.GetISteamInput(), Steamworks.SteamGameServerClient.GetISteamInventory(), Steamworks.SteamGameServerClient.GetISteamMatchmaking(), Steamworks.SteamGameServerClient.GetISteamMatchmakingServers(), Steamworks.SteamGameServerClient.GetISteamMusic(), Steamworks.SteamGameServerClient.GetISteamMusicRemote(), Steamworks.SteamGameServerClient.GetISteamNetworking(), Steamworks.SteamGameServerClient.GetISteamParentalSettings(), Steamworks.SteamGameServerClient.GetISteamParties(), Steamworks.SteamGameServerClient.GetISteamRemotePlay(), Steamworks.SteamGameServerClient.GetISteamRemoteStorage(), Steamworks.SteamGameServerClient.GetISteamScreenshots(), Steamworks.SteamGameServerClient.GetISteamUGC(), Steamworks.SteamGameServerClient.GetISteamUser(), Steamworks.SteamGameServerClient.GetISteamUserStats(), Steamworks.SteamGameServerClient.GetISteamUtils(), Steamworks.SteamGameServerClient.GetISteamVideo(), Steamworks.SteamGameServerInventory.GetItemDefinitionIDs(), Steamworks.SteamGameServerInventory.GetItemDefinitionProperty(), Steamworks.SteamGameServerUGC.GetItemDownloadInfo(), Steamworks.SteamGameServerUGC.GetItemInstallInfo(), Steamworks.SteamGameServerInventory.GetItemPrice(), Steamworks.SteamGameServerInventory.GetItemsByID(), Steamworks.SteamGameServerUGC.GetItemState(), Steamworks.SteamGameServerInventory.GetItemsWithPrices(), Steamworks.SteamGameServerUGC.GetItemUpdateProgress(), Steamworks.SteamGameServerNetworkingSockets.GetListenSocketAddress(), Steamworks.SteamGameServerNetworking.GetListenSocketInfo(), Steamworks.SteamGameServerNetworkingUtils.GetLocalPingLocation(), Steamworks.SteamGameServerNetworkingUtils.GetLocalTimestamp(), Steamworks.SteamGameServerNetworking.GetMaxPacketSize(), Steamworks.SteamGameServer.GetNextOutgoingPacket(), Steamworks.SteamGameServerInventory.GetNumItemsWithPrices(), Steamworks.SteamGameServerUGC.GetNumSubscribedItems(), Steamworks.SteamGameServerUGC.GetNumSupportedGameVersions(), Steamworks.SteamGameServerNetworking.GetP2PSessionState(), Steamworks.SteamGameServerNetworkingUtils.GetPingToDataCenter(), Steamworks.SteamGameServerNetworkingUtils.GetPOPCount(), Steamworks.SteamGameServerNetworkingUtils.GetPOPList(), Steamworks.SteamGameServer.GetPublicIP(), Steamworks.SteamGameServerUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamGameServerUGC.GetQueryUGCChildren(), Steamworks.SteamGameServerUGC.GetQueryUGCContentDescriptors(), Steamworks.SteamGameServerUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamGameServerUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamGameServerUGC.GetQueryUGCMetadata(), Steamworks.SteamGameServerUGC.GetQueryUGCNumAdditionalPreviews(), Steamworks.SteamGameServerUGC.GetQueryUGCNumKeyValueTags(), Steamworks.SteamGameServerUGC.GetQueryUGCNumTags(), Steamworks.SteamGameServerUGC.GetQueryUGCPreviewURL(), Steamworks.SteamGameServerUGC.GetQueryUGCResult(), Steamworks.SteamGameServerUGC.GetQueryUGCStatistic(), Steamworks.SteamGameServerUGC.GetQueryUGCTag(), Steamworks.SteamGameServerUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamGameServerNetworkingUtils.GetRealIdentityForFakeIP(), Steamworks.SteamGameServerNetworkingUtils.GetRelayNetworkStatus(), Steamworks.SteamGameServerNetworkingSockets.GetRemoteFakeIPForConnection(), Steamworks.SteamGameServerInventory.GetResultItemProperty(), Steamworks.SteamGameServerInventory.GetResultItems(), Steamworks.SteamGameServerInventory.GetResultStatus(), Steamworks.SteamGameServerInventory.GetResultTimestamp(), Steamworks.SteamGameServerUtils.GetSecondsSinceAppActive(), Steamworks.SteamGameServerUtils.GetSecondsSinceComputerActive(), Steamworks.SteamGameServerUtils.GetServerRealTime(), Steamworks.SteamGameServer.GetServerReputation(), Steamworks.SteamGameServerNetworkingMessages.GetSessionConnectionInfo(), Steamworks.SteamGameServerNetworking.GetSocketConnectionType(), Steamworks.SteamGameServerNetworking.GetSocketInfo(), Steamworks.SteamGameServer.GetSteamID(), Steamworks.SteamGameServerUtils.GetSteamUILanguage(), Steamworks.SteamGameServerUGC.GetSubscribedItems(), Steamworks.SteamGameServerUGC.GetSupportedGameVersionData(), Steamworks.SteamGameServerStats.GetUserAchievement(), Steamworks.SteamGameServerUGC.GetUserContentDescriptorPreferences(), Steamworks.SteamGameServerUGC.GetUserItemVote(), Steamworks.SteamGameServerStats.GetUserStat(), Steamworks.SteamGameServerStats.GetUserStat(), Steamworks.SteamGameServerUGC.GetWorkshopEULAStatus(), Steamworks.SteamGameServerInventory.GrantPromoItems(), Steamworks.SteamGameServer.HandleIncomingPacket(), Steamworks.SteamGameServerNetworkingSockets.InitAuthentication(), Steamworks.SteamGameServerUtils.InitFilterText(), Steamworks.SteamGameServerNetworkingUtils.InitRelayNetworkAccess(), Steamworks.SteamGameServerInventory.InspectItem(), Steamworks.SteamGameServerUtils.IsAPICallCompleted(), Steamworks.SteamGameServerNetworking.IsDataAvailable(), Steamworks.SteamGameServerNetworking.IsDataAvailableOnSocket(), Steamworks.SteamGameServerNetworkingUtils.IsFakeIPv4(), Steamworks.SteamGameServerUtils.IsOverlayEnabled(), Steamworks.SteamGameServerNetworking.IsP2PPacketAvailable(), Steamworks.SteamGameServerUtils.IsSteamChinaLauncher(), Steamworks.SteamGameServerUtils.IsSteamInBigPictureMode(), Steamworks.SteamGameServerUtils.IsSteamRunningInVR(), Steamworks.SteamGameServerUtils.IsSteamRunningOnSteamDeck(), Steamworks.SteamGameServerUtils.IsVRHeadsetStreamingEnabled(), Steamworks.SteamGameServerNetworkingUtils.IterateGenericEditableConfigValues(), Steamworks.SteamGameServerInventory.LoadItemDefinitions(), Steamworks.SteamGameServer.LogOff(), Steamworks.SteamGameServer.LogOn(), Steamworks.SteamGameServer.LogOnAnonymous(), Steamworks.SteamGameServerNetworkingUtils.ParsePingLocationString(), Steamworks.SteamGameServerHTTP.PrioritizeHTTPRequest(), Steamworks.SteamGameServerNetworking.ReadP2PPacket(), Steamworks.SteamGameServerNetworkingSockets.ReceivedP2PCustomSignal(), Steamworks.SteamGameServerNetworkingSockets.ReceivedRelayAuthTicket(), Steamworks.SteamGameServerNetworkingMessages.ReceiveMessagesOnChannel(), Steamworks.SteamGameServerNetworkingSockets.ReceiveMessagesOnConnection(), Steamworks.SteamGameServerNetworkingSockets.ReceiveMessagesOnPollGroup(), Steamworks.SteamGameServerHTTP.ReleaseCookieContainer(), Steamworks.SteamGameServerHTTP.ReleaseHTTPRequest(), Steamworks.SteamGameServerUGC.ReleaseQueryUGCRequest(), Steamworks.SteamGameServerClient.ReleaseUser(), Steamworks.SteamGameServerUGC.RemoveAllItemKeyValueTags(), Steamworks.SteamGameServerUGC.RemoveAppDependency(), Steamworks.SteamGameServerUGC.RemoveContentDescriptor(), Steamworks.SteamGameServerUGC.RemoveDependency(), Steamworks.SteamGameServerUGC.RemoveItemFromFavorites(), Steamworks.SteamGameServerUGC.RemoveItemKeyValueTags(), Steamworks.SteamGameServerUGC.RemoveItemPreview(), Steamworks.SteamGameServerInventory.RemoveProperty(), Steamworks.SteamGameServerInventory.RequestEligiblePromoItemDefinitionsIDs(), Steamworks.SteamGameServerInventory.RequestPrices(), Steamworks.SteamGameServerUGC.RequestUGCDetails(), Steamworks.SteamGameServer.RequestUserGroupStatus(), Steamworks.SteamGameServerStats.RequestUserStats(), Steamworks.SteamGameServerNetworkingSockets.ResetIdentity(), Steamworks.SteamGameServerNetworking.RetrieveData(), Steamworks.SteamGameServerNetworking.RetrieveDataFromSocket(), Steamworks.SteamGameServerNetworkingSockets.RunCallbacks(), Steamworks.SteamGameServerNetworking.SendDataOnSocket(), Steamworks.SteamGameServerHTTP.SendHTTPRequest(), Steamworks.SteamGameServerHTTP.SendHTTPRequestAndStreamResponse(), Steamworks.SteamGameServerInventory.SendItemDropHeartbeat(), Steamworks.SteamGameServerNetworkingSockets.SendMessages(), Steamworks.SteamGameServerNetworkingSockets.SendMessageToConnection(), Steamworks.SteamGameServerNetworkingMessages.SendMessageToUser(), Steamworks.SteamGameServerNetworking.SendP2PPacket(), Steamworks.SteamGameServerUGC.SendQueryUGCRequest(), Steamworks.SteamGameServer.SendUserConnectAndAuthenticate_DEPRECATED(), Steamworks.SteamGameServer.SendUserDisconnect_DEPRECATED(), Steamworks.SteamGameServerInventory.SerializeResult(), Steamworks.SteamGameServerUGC.SetAdminQuery(), Steamworks.SteamGameServer.SetAdvertiseServerActive(), Steamworks.SteamGameServerUGC.SetAllowCachedResponse(), Steamworks.SteamGameServerUGC.SetAllowLegacyUpload(), Steamworks.SteamGameServer.SetBotPlayerCount(), Steamworks.SteamGameServerNetworkingSockets.SetCertificate(), Steamworks.SteamGameServerUGC.SetCloudFileNameFilter(), Steamworks.SteamGameServerNetworkingUtils.SetConfigValue(), Steamworks.SteamGameServerNetworkingSockets.SetConnectionName(), Steamworks.SteamGameServerNetworkingSockets.SetConnectionPollGroup(), Steamworks.SteamGameServerNetworkingSockets.SetConnectionUserData(), Steamworks.SteamGameServerHTTP.SetCookie(), Steamworks.SteamGameServerNetworkingUtils.SetDebugOutputFunction(), Steamworks.SteamGameServer.SetDedicatedServer(), Steamworks.SteamGameServer.SetGameData(), Steamworks.SteamGameServer.SetGameDescription(), Steamworks.SteamGameServerUtils.SetGameLauncherMode(), Steamworks.SteamGameServer.SetGameTags(), Steamworks.SteamGameServerHTTP.SetHTTPRequestAbsoluteTimeoutMS(), Steamworks.SteamGameServerHTTP.SetHTTPRequestContextValue(), Steamworks.SteamGameServerHTTP.SetHTTPRequestCookieContainer(), Steamworks.SteamGameServerHTTP.SetHTTPRequestGetOrPostParameter(), Steamworks.SteamGameServerHTTP.SetHTTPRequestHeaderValue(), Steamworks.SteamGameServerHTTP.SetHTTPRequestNetworkActivityTimeout(), Steamworks.SteamGameServerHTTP.SetHTTPRequestRawPostBody(), Steamworks.SteamGameServerHTTP.SetHTTPRequestRequiresVerifiedCertificate(), Steamworks.SteamGameServerHTTP.SetHTTPRequestUserAgentInfo(), Steamworks.SteamGameServerUGC.SetItemContent(), Steamworks.SteamGameServerUGC.SetItemDescription(), Steamworks.SteamGameServerUGC.SetItemMetadata(), Steamworks.SteamGameServerUGC.SetItemPreview(), Steamworks.SteamGameServerUGC.SetItemTags(), Steamworks.SteamGameServerUGC.SetItemTitle(), Steamworks.SteamGameServerUGC.SetItemUpdateLanguage(), Steamworks.SteamGameServerUGC.SetItemVisibility(), Steamworks.SteamGameServer.SetKeyValue(), Steamworks.SteamGameServerUGC.SetLanguage(), Steamworks.SteamGameServerClient.SetLocalIPBinding(), Steamworks.SteamGameServer.SetMapName(), Steamworks.SteamGameServerUGC.SetMatchAnyTag(), Steamworks.SteamGameServer.SetMaxPlayerCount(), Steamworks.SteamGameServer.SetModDir(), Steamworks.SteamGameServerUtils.SetOverlayNotificationInset(), Steamworks.SteamGameServerUtils.SetOverlayNotificationPosition(), Steamworks.SteamGameServer.SetPasswordProtected(), Steamworks.SteamGameServer.SetProduct(), Steamworks.SteamGameServerInventory.SetProperty(), Steamworks.SteamGameServerInventory.SetProperty(), Steamworks.SteamGameServerInventory.SetProperty(), Steamworks.SteamGameServerInventory.SetProperty(), Steamworks.SteamGameServerUGC.SetRankedByTrendDays(), Steamworks.SteamGameServer.SetRegion(), Steamworks.SteamGameServerUGC.SetRequiredGameVersions(), Steamworks.SteamGameServerUGC.SetReturnAdditionalPreviews(), Steamworks.SteamGameServerUGC.SetReturnChildren(), Steamworks.SteamGameServerUGC.SetReturnKeyValueTags(), Steamworks.SteamGameServerUGC.SetReturnLongDescription(), Steamworks.SteamGameServerUGC.SetReturnMetadata(), Steamworks.SteamGameServerUGC.SetReturnOnlyIDs(), Steamworks.SteamGameServerUGC.SetReturnPlaytimeStats(), Steamworks.SteamGameServerUGC.SetReturnTotalOnly(), Steamworks.SteamGameServerUGC.SetSearchText(), Steamworks.SteamGameServer.SetServerName(), Steamworks.SteamGameServer.SetSpectatorPort(), Steamworks.SteamGameServer.SetSpectatorServerName(), Steamworks.SteamGameServerUGC.SetTimeCreatedDateRange(), Steamworks.SteamGameServerUGC.SetTimeUpdatedDateRange(), Steamworks.SteamGameServerStats.SetUserAchievement(), Steamworks.SteamGameServerUGC.SetUserItemVote(), Steamworks.SteamGameServerStats.SetUserStat(), Steamworks.SteamGameServerStats.SetUserStat(), Steamworks.SteamGameServerUtils.SetVRHeadsetStreamingEnabled(), Steamworks.SteamGameServerClient.SetWarningMessageHook(), Steamworks.SteamGameServerUtils.SetWarningMessageHook(), Steamworks.SteamGameServerUtils.ShowFloatingGamepadTextInput(), Steamworks.SteamGameServerUtils.ShowGamepadTextInput(), Steamworks.SteamGameServerUGC.ShowWorkshopEULA(), Steamworks.SteamGameServerUGC.StartItemUpdate(), Steamworks.SteamGameServerUGC.StartPlaytimeTracking(), Steamworks.SteamGameServerInventory.StartPurchase(), Steamworks.SteamGameServerInventory.StartUpdateProperties(), Steamworks.SteamGameServerUtils.StartVRDashboard(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIdentity_ParseString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_GetFakeIPType(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ParseString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ToString(), Steamworks.SteamGameServerUGC.StopPlaytimeTracking(), Steamworks.SteamGameServerUGC.StopPlaytimeTrackingForAllItems(), Steamworks.SteamGameServerStats.StoreUserStats(), Steamworks.SteamGameServerUGC.SubmitItemUpdate(), Steamworks.SteamGameServerInventory.SubmitUpdateProperties(), Steamworks.SteamGameServerUGC.SubscribeItem(), Steamworks.SteamGameServerUGC.SuspendDownloads(), Steamworks.SteamGameServerInventory.TradeItems(), Steamworks.SteamGameServerInventory.TransferItemQuantity(), Steamworks.SteamGameServerInventory.TriggerItemDrop(), Steamworks.SteamGameServerUGC.UnsubscribeItem(), Steamworks.SteamGameServerUGC.UpdateItemPreviewFile(), Steamworks.SteamGameServerUGC.UpdateItemPreviewVideo(), Steamworks.SteamGameServerStats.UpdateUserAvgRateStat(), Steamworks.SteamGameServer.UserHasLicenseForApp(), and Steamworks.SteamGameServer.WasRestartRequested().