Terraria Decompiled: Steamworks.InteropHelp.PtrToStringUTF8
PtrToStringUTF8()
static string Steamworks.InteropHelp.PtrToStringUTF8 (IntPtr nativeUtf8) inline static
Definition at line 38 of file InteropHelp.cs.
        {
            if (nativeUtf8 == IntPtr.Zero)
            {
                return null;
            }
            int num = 0;
            while (Marshal.ReadByte(nativeUtf8, num) != 0)
            {
                num++;
            }
            if (num == 0)
            {
                return string.Empty;
            }
            byte[] array = new byte[num];
            Marshal.Copy(nativeUtf8, array, 0, array.Length);
            return Encoding.UTF8.GetString(array);
        }
References System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Text.Encoding.GetString(), System.Runtime.InteropServices.Marshal.ReadByte(), System.Text.Encoding.UTF8, and System.IntPtr.Zero.
Referenced by Steamworks.SteamApps.BGetDLCDataByIndex(), Steamworks.SteamGameServerNetworkingUtils.ConvertPingLocationToString(), Steamworks.SteamNetworkingUtils.ConvertPingLocationToString(), Steamworks.SteamGameServerUtils.FilterText(), Steamworks.SteamUtils.FilterText(), Steamworks.SteamUserStats.GetAchievementDisplayAttribute(), Steamworks.SteamUserStats.GetAchievementName(), Steamworks.SteamApps.GetAppInstallDir(), Steamworks.SteamApps.GetAvailableGameLanguages(), Steamworks.SteamParties.GetBeaconDetails(), Steamworks.SteamParties.GetBeaconLocationData(), Steamworks.SteamApps.GetBetaInfo(), Steamworks.SteamFriends.GetClanChatMessage(), Steamworks.SteamFriends.GetClanName(), Steamworks.SteamFriends.GetClanTag(), Steamworks.SteamGameServerNetworkingUtils.GetConfigValueInfo(), Steamworks.SteamNetworkingUtils.GetConfigValueInfo(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionName(), Steamworks.SteamNetworkingSockets.GetConnectionName(), Steamworks.SteamApps.GetCurrentBetaName(), Steamworks.SteamApps.GetCurrentGameLanguage(), Steamworks.SteamGameServerNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamGameServerUtils.GetEnteredGamepadTextInput(), Steamworks.SteamUtils.GetEnteredGamepadTextInput(), Steamworks.SteamRemoteStorage.GetFileNameAndSize(), Steamworks.SteamFriends.GetFriendMessage(), Steamworks.SteamFriends.GetFriendPersonaName(), Steamworks.SteamFriends.GetFriendPersonaNameHistory(), Steamworks.SteamFriends.GetFriendRichPresence(), Steamworks.SteamFriends.GetFriendRichPresenceKeyByIndex(), Steamworks.SteamFriends.GetFriendsGroupName(), Steamworks.SteamNetworkingIdentity.GetGenericString(), Steamworks.SteamInput.GetGlyphForActionOrigin_Legacy(), Steamworks.SteamInput.GetGlyphForXboxOrigin(), Steamworks.SteamInput.GetGlyphPNGForActionOrigin(), Steamworks.SteamInput.GetGlyphSVGForActionOrigin(), Steamworks.SteamGameServerUtils.GetIPCountry(), Steamworks.SteamUtils.GetIPCountry(), Steamworks.SteamGameServerInventory.GetItemDefinitionProperty(), Steamworks.SteamInventory.GetItemDefinitionProperty(), Steamworks.SteamGameServerUGC.GetItemInstallInfo(), Steamworks.SteamUGC.GetItemInstallInfo(), Steamworks.SteamApps.GetLaunchCommandLine(), Steamworks.SteamApps.GetLaunchQueryParam(), Steamworks.SteamUserStats.GetLeaderboardName(), Steamworks.SteamMatchmaking.GetLobbyData(), Steamworks.SteamMatchmaking.GetLobbyDataByIndex(), Steamworks.SteamMatchmaking.GetLobbyMemberData(), Steamworks.SteamRemoteStorage.GetLocalFileChange(), Steamworks.SteamUserStats.GetMostAchievedAchievementInfo(), Steamworks.SteamUserStats.GetNextMostAchievedAchievementInfo(), Steamworks.SteamVideo.GetOPFStringForApp(), Steamworks.SteamFriends.GetPersonaName(), Steamworks.SteamFriends.GetPlayerNickname(), Steamworks.SteamFriends.GetProfileItemPropertyString(), Steamworks.SteamGameServerUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamGameServerUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamGameServerUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamGameServerUGC.GetQueryUGCMetadata(), Steamworks.SteamUGC.GetQueryUGCMetadata(), Steamworks.SteamGameServerUGC.GetQueryUGCPreviewURL(), Steamworks.SteamUGC.GetQueryUGCPreviewURL(), Steamworks.SteamGameServerUGC.GetQueryUGCTag(), Steamworks.SteamUGC.GetQueryUGCTag(), Steamworks.SteamGameServerUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamGameServerInventory.GetResultItemProperty(), Steamworks.SteamInventory.GetResultItemProperty(), Steamworks.SteamRemotePlay.GetSessionClientName(), Steamworks.SteamGameServerUtils.GetSteamUILanguage(), Steamworks.SteamUtils.GetSteamUILanguage(), Steamworks.SteamInput.GetStringForActionOrigin(), Steamworks.SteamInput.GetStringForAnalogActionName(), Steamworks.SteamInput.GetStringForDigitalActionName(), Steamworks.SteamInput.GetStringForXboxOrigin(), Steamworks.SteamGameServerUGC.GetSupportedGameVersionData(), Steamworks.SteamUGC.GetSupportedGameVersionData(), Steamworks.SteamRemoteStorage.GetUGCDetails(), Steamworks.SteamUser.GetUserDataFolder(), Steamworks.SteamNetworkingIdentity.GetXboxPairwiseID(), Steamworks.SteamAPI.InitEx(), Steamworks.GameServer.InitEx(), Steamworks.ISteamMatchmakingPlayersResponse.InternalOnAddPlayerToList(), Steamworks.ISteamMatchmakingRulesResponse.InternalOnRulesResponded(), Steamworks.SteamGameSearch.RetrieveConnectionDetails(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ToString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIPAddr_ToString(), Steamworks.SteamNetworkingIdentity.ToString(), and Steamworks.SteamNetworkingIPAddr.ToString().