Terraria Decompiled: Steamworks.InteropHelp.TestIfAvailableClient
TestIfAvailableClient()
static void Steamworks.InteropHelp.TestIfAvailableClient () inline static
Definition at line 18 of file InteropHelp.cs.
        {
            InteropHelp.TestIfPlatformSupported();
            if (CSteamAPIContext.GetSteamClient() == IntPtr.Zero && !CSteamAPIContext.Init())
            {
                throw new InvalidOperationException("Steamworks is not initialized.");
            }
        }
References Steamworks.CSteamAPIContext.GetSteamClient(), Steamworks.CSteamAPIContext.Init(), Steamworks.InteropHelp.TestIfPlatformSupported(), and System.IntPtr.Zero.
Referenced by Steamworks.SteamNetworkingSockets.AcceptConnection(), Steamworks.SteamGameSearch.AcceptGame(), Steamworks.SteamNetworking.AcceptP2PSessionWithUser(), Steamworks.SteamNetworkingMessages.AcceptSessionWithUser(), Steamworks.SteamInput.ActivateActionSet(), Steamworks.SteamInput.ActivateActionSetLayer(), Steamworks.SteamFriends.ActivateGameOverlay(), Steamworks.SteamFriends.ActivateGameOverlayInviteDialog(), Steamworks.SteamFriends.ActivateGameOverlayInviteDialogConnectString(), Steamworks.SteamFriends.ActivateGameOverlayRemotePlayTogetherInviteDialog(), Steamworks.SteamFriends.ActivateGameOverlayToStore(), Steamworks.SteamFriends.ActivateGameOverlayToUser(), Steamworks.SteamFriends.ActivateGameOverlayToWebPage(), Steamworks.SteamUGC.AddAppDependency(), Steamworks.SteamUGC.AddContentDescriptor(), Steamworks.SteamUGC.AddDependency(), Steamworks.SteamUGC.AddExcludedTag(), Steamworks.SteamMatchmaking.AddFavoriteGame(), Steamworks.SteamGameSearch.AddGameSearchParams(), Steamworks.SteamHTMLSurface.AddHeader(), Steamworks.SteamUGC.AddItemKeyValueTag(), Steamworks.SteamUGC.AddItemPreviewFile(), Steamworks.SteamUGC.AddItemPreviewVideo(), Steamworks.SteamUGC.AddItemToFavorites(), Steamworks.SteamInventory.AddPromoItem(), Steamworks.SteamInventory.AddPromoItems(), Steamworks.SteamMatchmaking.AddRequestLobbyListCompatibleMembersFilter(), Steamworks.SteamMatchmaking.AddRequestLobbyListDistanceFilter(), Steamworks.SteamMatchmaking.AddRequestLobbyListFilterSlotsAvailable(), Steamworks.SteamMatchmaking.AddRequestLobbyListNearValueFilter(), Steamworks.SteamMatchmaking.AddRequestLobbyListNumericalFilter(), Steamworks.SteamMatchmaking.AddRequestLobbyListResultCountFilter(), Steamworks.SteamMatchmaking.AddRequestLobbyListStringFilter(), Steamworks.SteamUGC.AddRequiredKeyValueTag(), Steamworks.SteamUGC.AddRequiredTag(), Steamworks.SteamUGC.AddRequiredTagGroup(), Steamworks.SteamScreenshots.AddScreenshotToLibrary(), Steamworks.SteamTimeline.AddTimelineEvent(), Steamworks.SteamScreenshots.AddVRScreenshotToLibrary(), Steamworks.SteamUser.AdvertiseGame(), Steamworks.SteamNetworkingUtils.AllocateMessage(), Steamworks.SteamNetworking.AllowP2PPacketRelay(), Steamworks.SteamHTMLSurface.AllowStartRequest(), Steamworks.SteamUserStats.AttachLeaderboardUGC(), Steamworks.SteamMusicRemote.BActivationSuccess(), Steamworks.SteamNetworkingSockets.BeginAsyncRequestFakeIP(), Steamworks.SteamUser.BeginAuthSession(), Steamworks.SteamRemoteStorage.BeginFileWriteBatch(), Steamworks.SteamApps.BGetDLCDataByIndex(), Steamworks.SteamRemotePlay.BGetSessionClientResolution(), Steamworks.SteamFriends.BHasEquippedProfileItem(), Steamworks.SteamUGC.BInitWorkshopForGameServer(), Steamworks.SteamParentalSettings.BIsAppBlocked(), Steamworks.SteamParentalSettings.BIsAppInBlockList(), Steamworks.SteamApps.BIsAppInstalled(), Steamworks.SteamUser.BIsBehindNAT(), Steamworks.SteamMusicRemote.BIsCurrentMusicRemote(), Steamworks.SteamApps.BIsCybercafe(), Steamworks.SteamApps.BIsDlcInstalled(), Steamworks.SteamMusic.BIsEnabled(), Steamworks.SteamParentalSettings.BIsFeatureBlocked(), Steamworks.SteamParentalSettings.BIsFeatureInBlockList(), Steamworks.SteamApps.BIsLowViolence(), Steamworks.SteamParentalSettings.BIsParentalLockEnabled(), Steamworks.SteamParentalSettings.BIsParentalLockLocked(), Steamworks.SteamUser.BIsPhoneIdentifying(), Steamworks.SteamUser.BIsPhoneRequiringVerification(), Steamworks.SteamUser.BIsPhoneVerified(), Steamworks.SteamMusic.BIsPlaying(), Steamworks.SteamApps.BIsSubscribed(), Steamworks.SteamApps.BIsSubscribedApp(), Steamworks.SteamApps.BIsSubscribedFromFamilySharing(), Steamworks.SteamApps.BIsSubscribedFromFreeWeekend(), Steamworks.SteamApps.BIsTimedTrial(), Steamworks.SteamUser.BIsTwoFactorEnabled(), Steamworks.SteamApps.BIsVACBanned(), Steamworks.SteamUser.BLoggedOn(), Steamworks.SteamInput.BNewDataAvailable(), Steamworks.SteamUtils.BOverlayNeedsPresent(), Steamworks.SteamClient.BReleaseSteamPipe(), Steamworks.SteamRemotePlay.BSendRemotePlayTogetherInvite(), Steamworks.SteamUser.BSetDurationControlOnlineState(), Steamworks.SteamClient.BShutdownIfAllPipesClosed(), Steamworks.SteamRemotePlay.BStartRemotePlayTogether(), Steamworks.SteamInput.BWaitForData(), Steamworks.SteamUser.CancelAuthTicket(), Steamworks.SteamMatchmakingServers.CancelQuery(), Steamworks.SteamGameSearch.CancelRequestPlayersForGame(), Steamworks.SteamParties.CancelReservation(), Steamworks.SteamMatchmakingServers.CancelServerQuery(), Steamworks.SteamParties.ChangeNumOpenSlots(), Steamworks.SteamUtils.CheckFileSignature(), Steamworks.SteamNetworkingUtils.CheckPingDataUpToDate(), Steamworks.SteamInventory.CheckResultSteamID(), Steamworks.SteamUserStats.ClearAchievement(), Steamworks.SteamFriends.ClearRichPresence(), Steamworks.SteamTimeline.ClearTimelineStateDescription(), Steamworks.SteamNetworkingMessages.CloseChannelWithUser(), Steamworks.SteamFriends.CloseClanChatWindowInSteam(), Steamworks.SteamNetworkingSockets.CloseConnection(), Steamworks.SteamNetworkingSockets.CloseListenSocket(), Steamworks.SteamNetworking.CloseP2PChannelWithUser(), Steamworks.SteamNetworking.CloseP2PSessionWithUser(), Steamworks.SteamNetworkingMessages.CloseSessionWithUser(), Steamworks.SteamRemoteStorage.CommitPublishedFileUpdate(), Steamworks.SteamNetworkingSockets.ConfigureConnectionLanes(), Steamworks.SteamNetworkingSockets.ConnectByIPAddress(), Steamworks.SteamNetworkingSockets.ConnectP2P(), Steamworks.SteamNetworkingSockets.ConnectP2PCustomSignaling(), Steamworks.SteamClient.ConnectToGlobalUser(), Steamworks.SteamNetworkingSockets.ConnectToHostedDedicatedServer(), Steamworks.SteamInventory.ConsumeItem(), Steamworks.SteamNetworkingUtils.ConvertPingLocationToString(), Steamworks.SteamHTMLSurface.CopyToClipboard(), Steamworks.SteamParties.CreateBeacon(), Steamworks.SteamHTMLSurface.CreateBrowser(), Steamworks.SteamNetworking.CreateConnectionSocket(), Steamworks.SteamHTTP.CreateCookieContainer(), Steamworks.SteamNetworkingSockets.CreateFakeUDPPort(), Steamworks.SteamNetworkingSockets.CreateHostedDedicatedServerListenSocket(), Steamworks.SteamHTTP.CreateHTTPRequest(), Steamworks.SteamUGC.CreateItem(), Steamworks.SteamNetworking.CreateListenSocket(), Steamworks.SteamNetworkingSockets.CreateListenSocketIP(), Steamworks.SteamNetworkingSockets.CreateListenSocketP2P(), Steamworks.SteamNetworkingSockets.CreateListenSocketP2PFakeIP(), Steamworks.SteamMatchmaking.CreateLobby(), Steamworks.SteamClient.CreateLocalUser(), Steamworks.SteamNetworking.CreateP2PConnectionSocket(), Steamworks.SteamNetworkingSockets.CreatePollGroup(), Steamworks.SteamRemoteStorage.CreatePublishedFileUpdateRequest(), Steamworks.SteamUGC.CreateQueryAllUGCRequest(), Steamworks.SteamUGC.CreateQueryAllUGCRequest(), Steamworks.SteamUGC.CreateQueryUGCDetailsRequest(), Steamworks.SteamUGC.CreateQueryUserUGCRequest(), Steamworks.SteamNetworkingSockets.CreateSocketPair(), Steamworks.SteamClient.CreateSteamPipe(), Steamworks.SteamMusicRemote.CurrentEntryDidChange(), Steamworks.SteamMusicRemote.CurrentEntryIsAvailable(), Steamworks.SteamMusicRemote.CurrentEntryWillChange(), Steamworks.SteamInput.DeactivateActionSetLayer(), Steamworks.SteamInput.DeactivateAllActionSetLayers(), Steamworks.SteamGameSearch.DeclineGame(), Steamworks.SteamUser.DecompressVoice(), Steamworks.SteamHTTP.DeferHTTPRequest(), Steamworks.SteamUGC.DeleteItem(), Steamworks.SteamMatchmaking.DeleteLobbyData(), Steamworks.SteamRemoteStorage.DeletePublishedFile(), Steamworks.SteamMusicRemote.DeregisterSteamMusicRemote(), Steamworks.SteamInventory.DeserializeResult(), Steamworks.SteamParties.DestroyBeacon(), Steamworks.SteamNetworking.DestroyListenSocket(), Steamworks.SteamNetworkingSockets.DestroyPollGroup(), Steamworks.SteamInventory.DestroyResult(), Steamworks.SteamNetworking.DestroySocket(), Steamworks.SteamUtils.DismissFloatingGamepadTextInput(), Steamworks.SteamUtils.DismissGamepadTextInput(), Steamworks.SteamFriends.DownloadClanActivityCounts(), Steamworks.SteamUGC.DownloadItem(), Steamworks.SteamUserStats.DownloadLeaderboardEntries(), Steamworks.SteamUserStats.DownloadLeaderboardEntriesForUsers(), Steamworks.SteamInput.EnableActionEventCallbacks(), Steamworks.SteamInput.EnableDeviceCallbacks(), Steamworks.SteamMusicRemote.EnableLooped(), Steamworks.SteamMusicRemote.EnablePlaylists(), Steamworks.SteamMusicRemote.EnablePlayNext(), Steamworks.SteamMusicRemote.EnablePlayPrevious(), Steamworks.SteamMusicRemote.EnableQueue(), Steamworks.SteamMusicRemote.EnableShuffled(), Steamworks.SteamUser.EndAuthSession(), Steamworks.SteamRemoteStorage.EndFileWriteBatch(), Steamworks.SteamGameSearch.EndGame(), Steamworks.SteamGameSearch.EndGameSearch(), Steamworks.SteamFriends.EnumerateFollowingList(), Steamworks.SteamRemoteStorage.EnumeratePublishedFilesByUserAction(), Steamworks.SteamRemoteStorage.EnumeratePublishedWorkshopFiles(), Steamworks.SteamRemoteStorage.EnumerateUserPublishedFiles(), Steamworks.SteamRemoteStorage.EnumerateUserSharedWorkshopFiles(), Steamworks.SteamRemoteStorage.EnumerateUserSubscribedFiles(), Steamworks.SteamNetworkingUtils.EstimatePingTimeBetweenTwoLocations(), Steamworks.SteamNetworkingUtils.EstimatePingTimeFromLocalHost(), Steamworks.SteamInventory.ExchangeItems(), Steamworks.SteamHTMLSurface.ExecuteJavascript(), Steamworks.SteamRemoteStorage.FileDelete(), Steamworks.SteamRemoteStorage.FileExists(), Steamworks.SteamRemoteStorage.FileForget(), Steamworks.SteamHTMLSurface.FileLoadDialogResponse(), Steamworks.SteamRemoteStorage.FilePersisted(), Steamworks.SteamRemoteStorage.FileRead(), Steamworks.SteamRemoteStorage.FileReadAsync(), Steamworks.SteamRemoteStorage.FileReadAsyncComplete(), Steamworks.SteamRemoteStorage.FileShare(), Steamworks.SteamRemoteStorage.FileWrite(), Steamworks.SteamRemoteStorage.FileWriteAsync(), Steamworks.SteamRemoteStorage.FileWriteStreamCancel(), Steamworks.SteamRemoteStorage.FileWriteStreamClose(), Steamworks.SteamRemoteStorage.FileWriteStreamOpen(), Steamworks.SteamRemoteStorage.FileWriteStreamWriteChunk(), Steamworks.SteamUtils.FilterText(), Steamworks.SteamHTMLSurface.Find(), Steamworks.SteamUserStats.FindLeaderboard(), Steamworks.SteamUserStats.FindOrCreateLeaderboard(), Steamworks.SteamNetworkingSockets.FindRelayAuthTicketForServer(), Steamworks.SteamNetworkingSockets.FlushMessagesOnConnection(), Steamworks.SteamInventory.GenerateItems(), Steamworks.SteamUserStats.GetAchievement(), Steamworks.SteamUserStats.GetAchievementAchievedPercent(), Steamworks.SteamUserStats.GetAchievementAndUnlockTime(), Steamworks.SteamUserStats.GetAchievementDisplayAttribute(), Steamworks.SteamUserStats.GetAchievementIcon(), Steamworks.SteamUserStats.GetAchievementName(), Steamworks.SteamUserStats.GetAchievementProgressLimits(), Steamworks.SteamUserStats.GetAchievementProgressLimits(), Steamworks.SteamInput.GetActionOriginFromXboxOrigin(), Steamworks.SteamInput.GetActionSetHandle(), Steamworks.SteamInput.GetActiveActionSetLayers(), Steamworks.SteamInventory.GetAllItems(), Steamworks.SteamInput.GetAnalogActionData(), Steamworks.SteamInput.GetAnalogActionHandle(), Steamworks.SteamInput.GetAnalogActionOrigins(), Steamworks.SteamUtils.GetAPICallFailureReason(), Steamworks.SteamUtils.GetAPICallResult(), Steamworks.SteamApps.GetAppBuildId(), Steamworks.SteamUGC.GetAppDependencies(), Steamworks.SteamUtils.GetAppID(), Steamworks.SteamApps.GetAppInstallDir(), Steamworks.SteamApps.GetAppOwner(), Steamworks.SteamNetworkingSockets.GetAuthenticationStatus(), Steamworks.SteamUser.GetAuthSessionTicket(), Steamworks.SteamUser.GetAuthTicketForWebApi(), Steamworks.SteamParties.GetAvailableBeaconLocations(), Steamworks.SteamApps.GetAvailableGameLanguages(), Steamworks.SteamUser.GetAvailableVoice(), Steamworks.SteamParties.GetBeaconByIndex(), Steamworks.SteamParties.GetBeaconDetails(), Steamworks.SteamParties.GetBeaconLocationData(), Steamworks.SteamApps.GetBetaInfo(), Steamworks.SteamRemoteStorage.GetCachedUGCCount(), Steamworks.SteamRemoteStorage.GetCachedUGCHandle(), Steamworks.SteamNetworkingSockets.GetCertificateRequest(), Steamworks.SteamFriends.GetChatMemberByIndex(), Steamworks.SteamFriends.GetClanActivityCounts(), Steamworks.SteamFriends.GetClanByIndex(), Steamworks.SteamFriends.GetClanChatMemberCount(), Steamworks.SteamFriends.GetClanChatMessage(), Steamworks.SteamFriends.GetClanCount(), Steamworks.SteamFriends.GetClanName(), Steamworks.SteamFriends.GetClanOfficerByIndex(), Steamworks.SteamFriends.GetClanOfficerCount(), Steamworks.SteamFriends.GetClanOwner(), Steamworks.SteamFriends.GetClanTag(), Steamworks.SteamNetworkingUtils.GetConfigValue(), Steamworks.SteamNetworkingUtils.GetConfigValueInfo(), Steamworks.SteamInput.GetConnectedControllers(), Steamworks.SteamUtils.GetConnectedUniverse(), Steamworks.SteamNetworkingSockets.GetConnectionInfo(), Steamworks.SteamNetworkingSockets.GetConnectionName(), Steamworks.SteamNetworkingSockets.GetConnectionRealTimeStatus(), Steamworks.SteamNetworkingSockets.GetConnectionUserData(), Steamworks.SteamInput.GetControllerForGamepadIndex(), Steamworks.SteamFriends.GetCoplayFriend(), Steamworks.SteamFriends.GetCoplayFriendCount(), Steamworks.SteamInput.GetCurrentActionSet(), Steamworks.SteamUtils.GetCurrentBatteryPower(), Steamworks.SteamApps.GetCurrentBetaName(), Steamworks.SteamApps.GetCurrentGameLanguage(), Steamworks.SteamNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamInput.GetDeviceBindingRevision(), Steamworks.SteamInput.GetDigitalActionData(), Steamworks.SteamInput.GetDigitalActionHandle(), Steamworks.SteamInput.GetDigitalActionOrigins(), Steamworks.SteamNetworkingUtils.GetDirectPingToPOP(), Steamworks.SteamApps.GetDLCCount(), Steamworks.SteamApps.GetDlcDownloadProgress(), Steamworks.SteamUserStats.GetDownloadedLeaderboardEntry(), Steamworks.SteamUser.GetDurationControl(), Steamworks.SteamApps.GetEarliestPurchaseUnixTime(), Steamworks.SteamInventory.GetEligiblePromoItemDefinitionIDs(), Steamworks.SteamUser.GetEncryptedAppTicket(), Steamworks.SteamUtils.GetEnteredGamepadTextInput(), Steamworks.SteamUtils.GetEnteredGamepadTextLength(), Steamworks.SteamNetworkingSockets.GetFakeIP(), Steamworks.SteamMatchmaking.GetFavoriteGame(), Steamworks.SteamMatchmaking.GetFavoriteGameCount(), Steamworks.SteamRemoteStorage.GetFileCount(), Steamworks.SteamApps.GetFileDetails(), Steamworks.SteamRemoteStorage.GetFileNameAndSize(), Steamworks.SteamRemoteStorage.GetFileSize(), Steamworks.SteamRemoteStorage.GetFileTimestamp(), Steamworks.SteamFriends.GetFollowerCount(), Steamworks.SteamFriends.GetFriendByIndex(), Steamworks.SteamFriends.GetFriendCoplayGame(), Steamworks.SteamFriends.GetFriendCoplayTime(), Steamworks.SteamFriends.GetFriendCount(), Steamworks.SteamFriends.GetFriendCountFromSource(), Steamworks.SteamFriends.GetFriendFromSourceByIndex(), Steamworks.SteamFriends.GetFriendGamePlayed(), Steamworks.SteamFriends.GetFriendMessage(), Steamworks.SteamFriends.GetFriendPersonaName(), Steamworks.SteamFriends.GetFriendPersonaNameHistory(), Steamworks.SteamFriends.GetFriendPersonaState(), Steamworks.SteamFriends.GetFriendRelationship(), Steamworks.SteamFriends.GetFriendRichPresence(), Steamworks.SteamFriends.GetFriendRichPresenceKeyByIndex(), Steamworks.SteamFriends.GetFriendRichPresenceKeyCount(), Steamworks.SteamFriends.GetFriendsGroupCount(), Steamworks.SteamFriends.GetFriendsGroupIDByIndex(), Steamworks.SteamFriends.GetFriendsGroupMembersCount(), Steamworks.SteamFriends.GetFriendsGroupMembersList(), Steamworks.SteamFriends.GetFriendsGroupName(), Steamworks.SteamFriends.GetFriendSteamLevel(), Steamworks.SteamUser.GetGameBadgeLevel(), Steamworks.SteamNetworkingSockets.GetGameCoordinatorServerLogin(), Steamworks.SteamInput.GetGamepadIndexForController(), Steamworks.SteamUserStats.GetGlobalStat(), Steamworks.SteamUserStats.GetGlobalStat(), Steamworks.SteamUserStats.GetGlobalStatHistory(), Steamworks.SteamUserStats.GetGlobalStatHistory(), Steamworks.SteamInput.GetGlyphForActionOrigin_Legacy(), Steamworks.SteamInput.GetGlyphForXboxOrigin(), Steamworks.SteamInput.GetGlyphPNGForActionOrigin(), Steamworks.SteamInput.GetGlyphSVGForActionOrigin(), Steamworks.SteamNetworkingSockets.GetHostedDedicatedServerAddress(), Steamworks.SteamNetworkingSockets.GetHostedDedicatedServerPOPID(), Steamworks.SteamNetworkingSockets.GetHostedDedicatedServerPort(), Steamworks.SteamUser.GetHSteamUser(), Steamworks.SteamHTTP.GetHTTPDownloadProgressPct(), Steamworks.SteamHTTP.GetHTTPRequestWasTimedOut(), Steamworks.SteamHTTP.GetHTTPResponseBodyData(), Steamworks.SteamHTTP.GetHTTPResponseBodySize(), Steamworks.SteamHTTP.GetHTTPResponseHeaderSize(), Steamworks.SteamHTTP.GetHTTPResponseHeaderValue(), Steamworks.SteamHTTP.GetHTTPStreamingResponseBodyData(), Steamworks.SteamNetworkingSockets.GetIdentity(), Steamworks.SteamUtils.GetImageRGBA(), Steamworks.SteamUtils.GetImageSize(), Steamworks.SteamInput.GetInputTypeForHandle(), Steamworks.SteamApps.GetInstalledDepots(), Steamworks.SteamClient.GetIPCCallCount(), Steamworks.SteamUtils.GetIPCCallCount(), Steamworks.SteamUtils.GetIPCountry(), Steamworks.SteamNetworkingUtils.GetIPv4FakeIPType(), Steamworks.SteamUtils.GetIPv6ConnectivityState(), Steamworks.SteamClient.GetISteamApps(), Steamworks.SteamClient.GetISteamController(), Steamworks.SteamClient.GetISteamFriends(), Steamworks.SteamClient.GetISteamGameSearch(), Steamworks.SteamClient.GetISteamGameServer(), Steamworks.SteamClient.GetISteamGameServerStats(), Steamworks.SteamClient.GetISteamGenericInterface(), Steamworks.SteamClient.GetISteamHTMLSurface(), Steamworks.SteamClient.GetISteamHTTP(), Steamworks.SteamClient.GetISteamInput(), Steamworks.SteamClient.GetISteamInventory(), Steamworks.SteamClient.GetISteamMatchmaking(), Steamworks.SteamClient.GetISteamMatchmakingServers(), Steamworks.SteamClient.GetISteamMusic(), Steamworks.SteamClient.GetISteamMusicRemote(), Steamworks.SteamClient.GetISteamNetworking(), Steamworks.SteamClient.GetISteamParentalSettings(), Steamworks.SteamClient.GetISteamParties(), Steamworks.SteamClient.GetISteamRemotePlay(), Steamworks.SteamClient.GetISteamRemoteStorage(), Steamworks.SteamClient.GetISteamScreenshots(), Steamworks.SteamClient.GetISteamUGC(), Steamworks.SteamClient.GetISteamUser(), Steamworks.SteamClient.GetISteamUserStats(), Steamworks.SteamClient.GetISteamUtils(), Steamworks.SteamClient.GetISteamVideo(), Steamworks.SteamInventory.GetItemDefinitionIDs(), Steamworks.SteamInventory.GetItemDefinitionProperty(), Steamworks.SteamUGC.GetItemDownloadInfo(), Steamworks.SteamUGC.GetItemInstallInfo(), Steamworks.SteamInventory.GetItemPrice(), Steamworks.SteamInventory.GetItemsByID(), Steamworks.SteamUGC.GetItemState(), Steamworks.SteamInventory.GetItemsWithPrices(), Steamworks.SteamUGC.GetItemUpdateProgress(), Steamworks.SteamFriends.GetLargeFriendAvatar(), Steamworks.SteamApps.GetLaunchCommandLine(), Steamworks.SteamApps.GetLaunchQueryParam(), Steamworks.SteamUserStats.GetLeaderboardDisplayType(), Steamworks.SteamUserStats.GetLeaderboardEntryCount(), Steamworks.SteamUserStats.GetLeaderboardName(), Steamworks.SteamUserStats.GetLeaderboardSortMethod(), Steamworks.SteamHTMLSurface.GetLinkAtPosition(), Steamworks.SteamNetworkingSockets.GetListenSocketAddress(), Steamworks.SteamNetworking.GetListenSocketInfo(), Steamworks.SteamMatchmaking.GetLobbyByIndex(), Steamworks.SteamMatchmaking.GetLobbyChatEntry(), Steamworks.SteamMatchmaking.GetLobbyData(), Steamworks.SteamMatchmaking.GetLobbyDataByIndex(), Steamworks.SteamMatchmaking.GetLobbyDataCount(), Steamworks.SteamMatchmaking.GetLobbyGameServer(), Steamworks.SteamMatchmaking.GetLobbyMemberByIndex(), Steamworks.SteamMatchmaking.GetLobbyMemberData(), Steamworks.SteamMatchmaking.GetLobbyMemberLimit(), Steamworks.SteamMatchmaking.GetLobbyOwner(), Steamworks.SteamRemoteStorage.GetLocalFileChange(), Steamworks.SteamRemoteStorage.GetLocalFileChangeCount(), Steamworks.SteamNetworkingUtils.GetLocalPingLocation(), Steamworks.SteamNetworkingUtils.GetLocalTimestamp(), Steamworks.SteamUser.GetMarketEligibility(), Steamworks.SteamNetworking.GetMaxPacketSize(), Steamworks.SteamFriends.GetMediumFriendAvatar(), Steamworks.SteamUserStats.GetMostAchievedAchievementInfo(), Steamworks.SteamInput.GetMotionData(), Steamworks.SteamUserStats.GetNextMostAchievedAchievementInfo(), Steamworks.SteamUserStats.GetNumAchievements(), Steamworks.SteamParties.GetNumActiveBeacons(), Steamworks.SteamParties.GetNumAvailableBeaconLocations(), Steamworks.SteamUserStats.GetNumberOfCurrentPlayers(), Steamworks.SteamApps.GetNumBetas(), Steamworks.SteamFriends.GetNumChatsWithUnreadPriorityMessages(), Steamworks.SteamInventory.GetNumItemsWithPrices(), Steamworks.SteamMatchmaking.GetNumLobbyMembers(), Steamworks.SteamUGC.GetNumSubscribedItems(), Steamworks.SteamUGC.GetNumSupportedGameVersions(), Steamworks.SteamVideo.GetOPFSettings(), Steamworks.SteamVideo.GetOPFStringForApp(), Steamworks.SteamNetworking.GetP2PSessionState(), Steamworks.SteamFriends.GetPersonaName(), Steamworks.SteamFriends.GetPersonaState(), Steamworks.SteamNetworkingUtils.GetPingToDataCenter(), Steamworks.SteamMusic.GetPlaybackStatus(), Steamworks.SteamFriends.GetPlayerNickname(), Steamworks.SteamUser.GetPlayerSteamLevel(), Steamworks.SteamNetworkingUtils.GetPOPCount(), Steamworks.SteamNetworkingUtils.GetPOPList(), Steamworks.SteamFriends.GetProfileItemPropertyString(), Steamworks.SteamFriends.GetProfileItemPropertyUint(), Steamworks.SteamRemoteStorage.GetPublishedFileDetails(), Steamworks.SteamRemoteStorage.GetPublishedItemVoteDetails(), Steamworks.SteamUGC.GetQueryUGCAdditionalPreview(), Steamworks.SteamUGC.GetQueryUGCChildren(), Steamworks.SteamUGC.GetQueryUGCContentDescriptors(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCKeyValueTag(), Steamworks.SteamUGC.GetQueryUGCMetadata(), Steamworks.SteamUGC.GetQueryUGCNumAdditionalPreviews(), Steamworks.SteamUGC.GetQueryUGCNumKeyValueTags(), Steamworks.SteamUGC.GetQueryUGCNumTags(), Steamworks.SteamUGC.GetQueryUGCPreviewURL(), Steamworks.SteamUGC.GetQueryUGCResult(), Steamworks.SteamUGC.GetQueryUGCStatistic(), Steamworks.SteamUGC.GetQueryUGCTag(), Steamworks.SteamUGC.GetQueryUGCTagDisplayName(), Steamworks.SteamRemoteStorage.GetQuota(), Steamworks.SteamNetworkingUtils.GetRealIdentityForFakeIP(), Steamworks.SteamNetworkingUtils.GetRelayNetworkStatus(), Steamworks.SteamNetworkingSockets.GetRemoteFakeIPForConnection(), Steamworks.SteamInput.GetRemotePlaySessionID(), Steamworks.SteamInventory.GetResultItemProperty(), Steamworks.SteamInventory.GetResultItems(), Steamworks.SteamInventory.GetResultStatus(), Steamworks.SteamInventory.GetResultTimestamp(), Steamworks.SteamUtils.GetSecondsSinceAppActive(), Steamworks.SteamUtils.GetSecondsSinceComputerActive(), Steamworks.SteamMatchmakingServers.GetServerCount(), Steamworks.SteamMatchmakingServers.GetServerDetails(), Steamworks.SteamUtils.GetServerRealTime(), Steamworks.SteamRemotePlay.GetSessionClientFormFactor(), Steamworks.SteamRemotePlay.GetSessionClientName(), Steamworks.SteamNetworkingMessages.GetSessionConnectionInfo(), Steamworks.SteamRemotePlay.GetSessionCount(), Steamworks.SteamRemotePlay.GetSessionID(), Steamworks.SteamInput.GetSessionInputConfigurationSettings(), Steamworks.SteamRemotePlay.GetSessionSteamID(), Steamworks.SteamFriends.GetSmallFriendAvatar(), Steamworks.SteamNetworking.GetSocketConnectionType(), Steamworks.SteamNetworking.GetSocketInfo(), Steamworks.SteamUserStats.GetStat(), Steamworks.SteamUserStats.GetStat(), Steamworks.SteamUser.GetSteamID(), Steamworks.SteamUtils.GetSteamUILanguage(), Steamworks.SteamInput.GetStringForActionOrigin(), Steamworks.SteamInput.GetStringForAnalogActionName(), Steamworks.SteamInput.GetStringForDigitalActionName(), Steamworks.SteamInput.GetStringForXboxOrigin(), Steamworks.SteamUGC.GetSubscribedItems(), Steamworks.SteamUGC.GetSupportedGameVersionData(), Steamworks.SteamRemoteStorage.GetSyncPlatforms(), Steamworks.SteamRemoteStorage.GetUGCDetails(), Steamworks.SteamRemoteStorage.GetUGCDownloadProgress(), Steamworks.SteamUserStats.GetUserAchievement(), Steamworks.SteamUserStats.GetUserAchievementAndUnlockTime(), Steamworks.SteamUGC.GetUserContentDescriptorPreferences(), Steamworks.SteamUser.GetUserDataFolder(), Steamworks.SteamUGC.GetUserItemVote(), Steamworks.SteamRemoteStorage.GetUserPublishedItemVoteDetails(), Steamworks.SteamFriends.GetUserRestrictions(), Steamworks.SteamUserStats.GetUserStat(), Steamworks.SteamUserStats.GetUserStat(), Steamworks.SteamVideo.GetVideoURL(), Steamworks.SteamUser.GetVoice(), Steamworks.SteamUser.GetVoiceOptimalSampleRate(), Steamworks.SteamMusic.GetVolume(), Steamworks.SteamUGC.GetWorkshopEULAStatus(), Steamworks.SteamHTMLSurface.GoBack(), Steamworks.SteamHTMLSurface.GoForward(), Steamworks.SteamInventory.GrantPromoItems(), Steamworks.SteamFriends.HasFriend(), Steamworks.SteamScreenshots.HookScreenshots(), Steamworks.SteamGameSearch.HostConfirmGameStart(), Steamworks.SteamUserStats.IndicateAchievementProgress(), Steamworks.SteamHTMLSurface.Init(), Steamworks.SteamInput.Init(), Steamworks.SteamNetworkingSockets.InitAuthentication(), Steamworks.SteamUtils.InitFilterText(), Steamworks.SteamUser.InitiateGameConnection_DEPRECATED(), Steamworks.SteamNetworkingUtils.InitRelayNetworkAccess(), Steamworks.SteamInventory.InspectItem(), Steamworks.SteamApps.InstallDLC(), Steamworks.SteamFriends.InviteUserToGame(), Steamworks.SteamMatchmaking.InviteUserToLobby(), Steamworks.SteamUtils.IsAPICallCompleted(), Steamworks.SteamVideo.IsBroadcasting(), Steamworks.SteamFriends.IsClanChatAdmin(), Steamworks.SteamFriends.IsClanChatWindowOpenInSteam(), Steamworks.SteamFriends.IsClanOfficialGameGroup(), Steamworks.SteamFriends.IsClanPublic(), Steamworks.SteamRemoteStorage.IsCloudEnabledForAccount(), Steamworks.SteamRemoteStorage.IsCloudEnabledForApp(), Steamworks.SteamNetworking.IsDataAvailable(), Steamworks.SteamNetworking.IsDataAvailableOnSocket(), Steamworks.SteamNetworkingUtils.IsFakeIPv4(), Steamworks.SteamFriends.IsFollowing(), Steamworks.SteamUtils.IsOverlayEnabled(), Steamworks.SteamNetworking.IsP2PPacketAvailable(), Steamworks.SteamMatchmakingServers.IsRefreshing(), Steamworks.SteamScreenshots.IsScreenshotsHooked(), Steamworks.SteamUtils.IsSteamChinaLauncher(), Steamworks.SteamUtils.IsSteamInBigPictureMode(), Steamworks.SteamUtils.IsSteamRunningInVR(), Steamworks.SteamUtils.IsSteamRunningOnSteamDeck(), Steamworks.SteamFriends.IsUserInSource(), Steamworks.SteamUtils.IsVRHeadsetStreamingEnabled(), Steamworks.SteamNetworkingUtils.IterateGenericEditableConfigValues(), Steamworks.SteamFriends.JoinClanChatRoom(), Steamworks.SteamMatchmaking.JoinLobby(), Steamworks.SteamParties.JoinParty(), Steamworks.SteamHTMLSurface.JSDialogResponse(), Steamworks.SteamHTMLSurface.KeyChar(), Steamworks.SteamHTMLSurface.KeyDown(), Steamworks.SteamHTMLSurface.KeyUp(), Steamworks.SteamFriends.LeaveClanChatRoom(), Steamworks.SteamMatchmaking.LeaveLobby(), Steamworks.SteamInput.Legacy_TriggerHapticPulse(), Steamworks.SteamInput.Legacy_TriggerRepeatedHapticPulse(), Steamworks.SteamInventory.LoadItemDefinitions(), Steamworks.SteamHTMLSurface.LoadURL(), Steamworks.SteamApps.MarkContentCorrupt(), Steamworks.SteamHTMLSurface.MouseDoubleClick(), Steamworks.SteamHTMLSurface.MouseDown(), Steamworks.SteamHTMLSurface.MouseMove(), Steamworks.SteamHTMLSurface.MouseUp(), Steamworks.SteamHTMLSurface.MouseWheel(), Steamworks.SteamParties.OnReservationCompleted(), Steamworks.SteamFriends.OpenClanChatWindowInSteam(), Steamworks.SteamHTMLSurface.OpenDeveloperTools(), Steamworks.SteamNetworkingUtils.ParsePingLocationString(), Steamworks.SteamHTMLSurface.PasteFromClipboard(), Steamworks.SteamMusic.Pause(), Steamworks.SteamMatchmakingServers.PingServer(), Steamworks.SteamMusic.Play(), Steamworks.SteamMatchmakingServers.PlayerDetails(), Steamworks.SteamMusicRemote.PlaylistDidChange(), Steamworks.SteamMusicRemote.PlaylistWillChange(), Steamworks.SteamMusic.PlayNext(), Steamworks.SteamMusic.PlayPrevious(), Steamworks.SteamHTTP.PrioritizeHTTPRequest(), Steamworks.SteamRemoteStorage.PublishVideo(), Steamworks.SteamRemoteStorage.PublishWorkshopFile(), Steamworks.SteamMusicRemote.QueueDidChange(), Steamworks.SteamMusicRemote.QueueWillChange(), Steamworks.SteamNetworking.ReadP2PPacket(), Steamworks.SteamNetworkingSockets.ReceivedP2PCustomSignal(), Steamworks.SteamNetworkingSockets.ReceivedRelayAuthTicket(), Steamworks.SteamNetworkingMessages.ReceiveMessagesOnChannel(), Steamworks.SteamNetworkingSockets.ReceiveMessagesOnConnection(), Steamworks.SteamNetworkingSockets.ReceiveMessagesOnPollGroup(), Steamworks.SteamMatchmakingServers.RefreshQuery(), Steamworks.SteamMatchmakingServers.RefreshServer(), Steamworks.SteamFriends.RegisterProtocolInOverlayBrowser(), Steamworks.SteamMusicRemote.RegisterSteamMusicRemote(), Steamworks.SteamHTTP.ReleaseCookieContainer(), Steamworks.SteamHTTP.ReleaseHTTPRequest(), Steamworks.SteamUGC.ReleaseQueryUGCRequest(), Steamworks.SteamMatchmakingServers.ReleaseRequest(), Steamworks.SteamClient.ReleaseUser(), Steamworks.SteamHTMLSurface.Reload(), Steamworks.SteamUGC.RemoveAllItemKeyValueTags(), Steamworks.SteamUGC.RemoveAppDependency(), Steamworks.SteamHTMLSurface.RemoveBrowser(), Steamworks.SteamUGC.RemoveContentDescriptor(), Steamworks.SteamUGC.RemoveDependency(), Steamworks.SteamMatchmaking.RemoveFavoriteGame(), Steamworks.SteamUGC.RemoveItemFromFavorites(), Steamworks.SteamUGC.RemoveItemKeyValueTags(), Steamworks.SteamUGC.RemoveItemPreview(), Steamworks.SteamInventory.RemoveProperty(), Steamworks.SteamFriends.ReplyToFriendMessage(), Steamworks.SteamApps.RequestAllProofOfPurchaseKeys(), Steamworks.SteamApps.RequestAppProofOfPurchaseKey(), Steamworks.SteamFriends.RequestClanOfficerList(), Steamworks.SteamUserStats.RequestCurrentStats(), Steamworks.SteamInventory.RequestEligiblePromoItemDefinitionsIDs(), Steamworks.SteamUser.RequestEncryptedAppTicket(), Steamworks.SteamFriends.RequestEquippedProfileItems(), Steamworks.SteamMatchmakingServers.RequestFavoritesServerList(), Steamworks.SteamFriends.RequestFriendRichPresence(), Steamworks.SteamMatchmakingServers.RequestFriendsServerList(), Steamworks.SteamUserStats.RequestGlobalAchievementPercentages(), Steamworks.SteamUserStats.RequestGlobalStats(), Steamworks.SteamMatchmakingServers.RequestHistoryServerList(), Steamworks.SteamMatchmakingServers.RequestInternetServerList(), Steamworks.SteamMatchmakingServers.RequestLANServerList(), Steamworks.SteamMatchmaking.RequestLobbyData(), Steamworks.SteamMatchmaking.RequestLobbyList(), Steamworks.SteamGameSearch.RequestPlayersForGame(), Steamworks.SteamInventory.RequestPrices(), Steamworks.SteamMatchmakingServers.RequestSpectatorServerList(), Steamworks.SteamUser.RequestStoreAuthURL(), Steamworks.SteamUGC.RequestUGCDetails(), Steamworks.SteamFriends.RequestUserInformation(), Steamworks.SteamUserStats.RequestUserStats(), Steamworks.SteamUserStats.ResetAllStats(), Steamworks.SteamNetworkingSockets.ResetIdentity(), Steamworks.SteamMusicRemote.ResetPlaylistEntries(), Steamworks.SteamMusicRemote.ResetQueueEntries(), Steamworks.SteamGameSearch.RetrieveConnectionDetails(), Steamworks.SteamNetworking.RetrieveData(), Steamworks.SteamNetworking.RetrieveDataFromSocket(), Steamworks.SteamNetworkingSockets.RunCallbacks(), Steamworks.SteamInput.RunFrame(), Steamworks.SteamGameSearch.SearchForGameSolo(), Steamworks.SteamGameSearch.SearchForGameWithLobby(), Steamworks.SteamFriends.SendClanChatMessage(), Steamworks.SteamNetworking.SendDataOnSocket(), Steamworks.SteamHTTP.SendHTTPRequest(), Steamworks.SteamHTTP.SendHTTPRequestAndStreamResponse(), Steamworks.SteamInventory.SendItemDropHeartbeat(), Steamworks.SteamMatchmaking.SendLobbyChatMsg(), Steamworks.SteamNetworkingSockets.SendMessages(), Steamworks.SteamNetworkingSockets.SendMessageToConnection(), Steamworks.SteamNetworkingMessages.SendMessageToUser(), Steamworks.SteamNetworking.SendP2PPacket(), Steamworks.SteamUGC.SendQueryUGCRequest(), Steamworks.SteamInventory.SerializeResult(), Steamworks.SteamMatchmakingServers.ServerRules(), Steamworks.SteamUserStats.SetAchievement(), Steamworks.SteamApps.SetActiveBeta(), Steamworks.SteamUGC.SetAdminQuery(), Steamworks.SteamUGC.SetAllowCachedResponse(), Steamworks.SteamUGC.SetAllowLegacyUpload(), Steamworks.SteamHTMLSurface.SetBackgroundMode(), Steamworks.SteamNetworkingSockets.SetCertificate(), Steamworks.SteamRemoteStorage.SetCloudEnabledForApp(), Steamworks.SteamUGC.SetCloudFileNameFilter(), Steamworks.SteamNetworkingUtils.SetConfigValue(), Steamworks.SteamGameSearch.SetConnectionDetails(), Steamworks.SteamNetworkingSockets.SetConnectionName(), Steamworks.SteamNetworkingSockets.SetConnectionPollGroup(), Steamworks.SteamNetworkingSockets.SetConnectionUserData(), Steamworks.SteamHTTP.SetCookie(), Steamworks.SteamHTMLSurface.SetCookie(), Steamworks.SteamMusicRemote.SetCurrentPlaylistEntry(), Steamworks.SteamMusicRemote.SetCurrentQueueEntry(), Steamworks.SteamNetworkingUtils.SetDebugOutputFunction(), Steamworks.SteamMusicRemote.SetDisplayName(), Steamworks.SteamApps.SetDlcContext(), Steamworks.SteamHTMLSurface.SetDPIScalingFactor(), Steamworks.SteamInput.SetDualSenseTriggerEffect(), Steamworks.SteamGameSearch.SetGameHostParams(), Steamworks.SteamUtils.SetGameLauncherMode(), Steamworks.SteamHTMLSurface.SetHorizontalScroll(), Steamworks.SteamHTTP.SetHTTPRequestAbsoluteTimeoutMS(), Steamworks.SteamHTTP.SetHTTPRequestContextValue(), Steamworks.SteamHTTP.SetHTTPRequestCookieContainer(), Steamworks.SteamHTTP.SetHTTPRequestGetOrPostParameter(), Steamworks.SteamHTTP.SetHTTPRequestHeaderValue(), Steamworks.SteamHTTP.SetHTTPRequestNetworkActivityTimeout(), Steamworks.SteamHTTP.SetHTTPRequestRawPostBody(), Steamworks.SteamHTTP.SetHTTPRequestRequiresVerifiedCertificate(), Steamworks.SteamHTTP.SetHTTPRequestUserAgentInfo(), Steamworks.SteamFriends.SetInGameVoiceSpeaking(), Steamworks.SteamInput.SetInputActionManifestFilePath(), Steamworks.SteamUGC.SetItemContent(), Steamworks.SteamUGC.SetItemDescription(), Steamworks.SteamUGC.SetItemMetadata(), Steamworks.SteamUGC.SetItemPreview(), Steamworks.SteamUGC.SetItemTags(), Steamworks.SteamUGC.SetItemTitle(), Steamworks.SteamUGC.SetItemUpdateLanguage(), Steamworks.SteamUGC.SetItemVisibility(), Steamworks.SteamHTMLSurface.SetKeyFocus(), Steamworks.SteamUGC.SetLanguage(), Steamworks.SteamInput.SetLEDColor(), Steamworks.SteamMatchmaking.SetLinkedLobby(), Steamworks.SteamFriends.SetListenForFriendsMessages(), Steamworks.SteamMatchmaking.SetLobbyData(), Steamworks.SteamMatchmaking.SetLobbyGameServer(), Steamworks.SteamMatchmaking.SetLobbyJoinable(), Steamworks.SteamMatchmaking.SetLobbyMemberData(), Steamworks.SteamMatchmaking.SetLobbyMemberLimit(), Steamworks.SteamMatchmaking.SetLobbyOwner(), Steamworks.SteamMatchmaking.SetLobbyType(), Steamworks.SteamClient.SetLocalIPBinding(), Steamworks.SteamScreenshots.SetLocation(), Steamworks.SteamUGC.SetMatchAnyTag(), Steamworks.SteamUtils.SetOverlayNotificationInset(), Steamworks.SteamUtils.SetOverlayNotificationPosition(), Steamworks.SteamHTMLSurface.SetPageScaleFactor(), Steamworks.SteamFriends.SetPersonaName(), Steamworks.SteamFriends.SetPlayedWith(), Steamworks.SteamMusicRemote.SetPlaylistEntry(), Steamworks.SteamMusicRemote.SetPNGIcon_64x64(), Steamworks.SteamInventory.SetProperty(), Steamworks.SteamInventory.SetProperty(), Steamworks.SteamInventory.SetProperty(), Steamworks.SteamInventory.SetProperty(), Steamworks.SteamMusicRemote.SetQueueEntry(), Steamworks.SteamUGC.SetRankedByTrendDays(), Steamworks.SteamUGC.SetRequiredGameVersions(), Steamworks.SteamUGC.SetReturnAdditionalPreviews(), Steamworks.SteamUGC.SetReturnChildren(), Steamworks.SteamUGC.SetReturnKeyValueTags(), Steamworks.SteamUGC.SetReturnLongDescription(), Steamworks.SteamUGC.SetReturnMetadata(), Steamworks.SteamUGC.SetReturnOnlyIDs(), Steamworks.SteamUGC.SetReturnPlaytimeStats(), Steamworks.SteamUGC.SetReturnTotalOnly(), Steamworks.SteamFriends.SetRichPresence(), Steamworks.SteamUGC.SetSearchText(), Steamworks.SteamHTMLSurface.SetSize(), Steamworks.SteamUserStats.SetStat(), Steamworks.SteamUserStats.SetStat(), Steamworks.SteamRemoteStorage.SetSyncPlatforms(), Steamworks.SteamUGC.SetTimeCreatedDateRange(), Steamworks.SteamTimeline.SetTimelineGameMode(), Steamworks.SteamTimeline.SetTimelineStateDescription(), Steamworks.SteamUGC.SetTimeUpdatedDateRange(), Steamworks.SteamUGC.SetUserItemVote(), Steamworks.SteamRemoteStorage.SetUserPublishedFileAction(), Steamworks.SteamHTMLSurface.SetVerticalScroll(), Steamworks.SteamMusic.SetVolume(), Steamworks.SteamUtils.SetVRHeadsetStreamingEnabled(), Steamworks.SteamClient.SetWarningMessageHook(), Steamworks.SteamUtils.SetWarningMessageHook(), Steamworks.SteamInput.ShowBindingPanel(), Steamworks.SteamUtils.ShowFloatingGamepadTextInput(), Steamworks.SteamUtils.ShowGamepadTextInput(), Steamworks.SteamUGC.ShowWorkshopEULA(), Steamworks.SteamHTMLSurface.Shutdown(), Steamworks.SteamInput.Shutdown(), Steamworks.SteamUGC.StartItemUpdate(), Steamworks.SteamUGC.StartPlaytimeTracking(), Steamworks.SteamInventory.StartPurchase(), Steamworks.SteamInventory.StartUpdateProperties(), Steamworks.SteamUser.StartVoiceRecording(), Steamworks.SteamUtils.StartVRDashboard(), Steamworks.SteamNetworkingUtils.SteamNetworkingIdentity_ParseString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIPAddr_GetFakeIPType(), Steamworks.SteamNetworkingUtils.SteamNetworkingIPAddr_ParseString(), Steamworks.SteamNetworkingUtils.SteamNetworkingIPAddr_ToString(), Steamworks.SteamInput.StopAnalogActionMomentum(), Steamworks.SteamHTMLSurface.StopFind(), Steamworks.SteamHTMLSurface.StopLoad(), Steamworks.SteamUGC.StopPlaytimeTracking(), Steamworks.SteamUGC.StopPlaytimeTrackingForAllItems(), Steamworks.SteamUser.StopVoiceRecording(), Steamworks.SteamUserStats.StoreStats(), Steamworks.SteamUGC.SubmitItemUpdate(), Steamworks.SteamGameSearch.SubmitPlayerResult(), Steamworks.SteamInventory.SubmitUpdateProperties(), Steamworks.SteamUGC.SubscribeItem(), Steamworks.SteamRemoteStorage.SubscribePublishedFile(), Steamworks.SteamUGC.SuspendDownloads(), Steamworks.SteamScreenshots.TagPublishedFile(), Steamworks.SteamScreenshots.TagUser(), Steamworks.SteamUser.TerminateGameConnection_DEPRECATED(), Steamworks.SteamUser.TrackAppUsageEvent(), Steamworks.SteamInventory.TradeItems(), Steamworks.SteamInventory.TransferItemQuantity(), Steamworks.SteamInput.TranslateActionOrigin(), Steamworks.SteamInventory.TriggerItemDrop(), Steamworks.SteamScreenshots.TriggerScreenshot(), Steamworks.SteamInput.TriggerSimpleHapticEvent(), Steamworks.SteamInput.TriggerVibration(), Steamworks.SteamInput.TriggerVibrationExtended(), Steamworks.SteamRemoteStorage.UGCDownload(), Steamworks.SteamRemoteStorage.UGCDownloadToLocation(), Steamworks.SteamRemoteStorage.UGCRead(), Steamworks.SteamApps.UninstallDLC(), Steamworks.SteamUGC.UnsubscribeItem(), Steamworks.SteamRemoteStorage.UnsubscribePublishedFile(), Steamworks.SteamUserStats.UpdateAvgRateStat(), Steamworks.SteamMusicRemote.UpdateCurrentEntryCoverArt(), Steamworks.SteamMusicRemote.UpdateCurrentEntryElapsedSeconds(), Steamworks.SteamMusicRemote.UpdateCurrentEntryText(), Steamworks.SteamUGC.UpdateItemPreviewFile(), Steamworks.SteamUGC.UpdateItemPreviewVideo(), Steamworks.SteamMusicRemote.UpdateLooped(), Steamworks.SteamMusicRemote.UpdatePlaybackStatus(), Steamworks.SteamRemoteStorage.UpdatePublishedFileDescription(), Steamworks.SteamRemoteStorage.UpdatePublishedFileFile(), Steamworks.SteamRemoteStorage.UpdatePublishedFilePreviewFile(), Steamworks.SteamRemoteStorage.UpdatePublishedFileSetChangeDescription(), Steamworks.SteamRemoteStorage.UpdatePublishedFileTags(), Steamworks.SteamRemoteStorage.UpdatePublishedFileTitle(), Steamworks.SteamRemoteStorage.UpdatePublishedFileVisibility(), Steamworks.SteamMusicRemote.UpdateShuffled(), Steamworks.SteamRemoteStorage.UpdateUserPublishedItemVote(), Steamworks.SteamMusicRemote.UpdateVolume(), Steamworks.SteamUserStats.UploadLeaderboardScore(), Steamworks.SteamUser.UserHasLicenseForApp(), Steamworks.SteamHTMLSurface.ViewSource(), and Steamworks.SteamScreenshots.WriteScreenshot().