Terraria Decompiled: System.Runtime.Remoting.Contexts.CrossContextChannel.AsyncProcessMessage
AsyncProcessMessage()
IMessageCtrl System.Runtime.Remoting.Contexts.CrossContextChannel.AsyncProcessMessage (IMessage msg, IMessageSink replySink) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 43 of file CrossContextChannel.cs.
        {
            ServerIdentity serverIdentity = (ServerIdentity)RemotingServices.GetMessageTargetIdentity(msg);
            Context context = null;
            if (Thread.CurrentContext != serverIdentity.Context)
            {
                context = Context.SwitchToContext(serverIdentity.Context);
            }
            IMessageCtrl messageCtrl2;
            try
            {
                Context.NotifyGlobalDynamicSinks(true, msg, false, true);
                Thread.CurrentContext.NotifyDynamicSinks(true, msg, false, false);
                if (replySink != null)
                {
                    replySink = new CrossContextChannel.ContextRestoreSink(replySink, context, msg);
                }
                IMessageCtrl messageCtrl = serverIdentity.AsyncObjectProcessMessage(msg, replySink);
                if (replySink == null)
                {
                    Context.NotifyGlobalDynamicSinks(false, msg, false, false);
                    Thread.CurrentContext.NotifyDynamicSinks(false, msg, false, false);
                }
                messageCtrl2 = messageCtrl;
            }
            catch (Exception ex)
            {
                if (replySink != null)
                {
                    replySink.SyncProcessMessage(new ReturnMessage(ex, (IMethodCallMessage)msg));
                }
                messageCtrl2 = null;
            }
            finally
            {
                if (context != null)
                {
                    Context.SwitchToContext(context);
                }
            }
            return messageCtrl2;
        }
References System.Runtime.Remoting.ServerIdentity.AsyncObjectProcessMessage(), System.Runtime.Remoting.ServerIdentity.Context, System.Threading.Thread.CurrentContext, System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity(), System.Runtime.Remoting.Contexts.Context.NotifyGlobalDynamicSinks(), System.Runtime.Remoting.Contexts.Context.SwitchToContext(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().
Referenced by System.Runtime.Remoting.Channels.ChannelServices.AsyncDispatchMessage().