Terraria Decompiled: System.Runtime.Remoting.Contexts.CrossContextChannel.SyncProcessMessage
SyncProcessMessage()
IMessage System.Runtime.Remoting.Contexts.CrossContextChannel.SyncProcessMessage (IMessage msg) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 11 of file CrossContextChannel.cs.
        {
            ServerIdentity serverIdentity = (ServerIdentity)RemotingServices.GetMessageTargetIdentity(msg);
            Context context = null;
            if (Thread.CurrentContext != serverIdentity.Context)
            {
                context = Context.SwitchToContext(serverIdentity.Context);
            }
            IMessage message;
            try
            {
                Context.NotifyGlobalDynamicSinks(true, msg, false, false);
                Thread.CurrentContext.NotifyDynamicSinks(true, msg, false, false);
                message = serverIdentity.Context.GetServerContextSinkChain().SyncProcessMessage(msg);
                Context.NotifyGlobalDynamicSinks(false, msg, false, false);
                Thread.CurrentContext.NotifyDynamicSinks(false, msg, false, false);
            }
            catch (Exception ex)
            {
                message = new ReturnMessage(ex, (IMethodCallMessage)msg);
            }
            finally
            {
                if (context != null)
                {
                    Context.SwitchToContext(context);
                }
            }
            return message;
        }
References System.Runtime.Remoting.ServerIdentity.Context, System.Threading.Thread.CurrentContext, System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity(), System.Runtime.Remoting.Contexts.Context.NotifyGlobalDynamicSinks(), and System.Runtime.Remoting.Contexts.Context.SwitchToContext().
Referenced by System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage().