Terraria Decompiled: System.Globalization.CompareInfo.internal_index_switch
internal_index_switch()
int System.Globalization.CompareInfo.internal_index_switch (string s1, int sindex, int count, string s2, CompareOptions opt, bool first) inline private
Definition at line 1373 of file CompareInfo.cs.
        {
            if (opt == CompareOptions.Ordinal)
            {
                if (!first)
                {
                    return s1.LastIndexOfUnchecked(s2, sindex, count);
                }
                return s1.IndexOfUnchecked(s2, sindex, count);
            }
            else
            {
                if (!CompareInfo.UseManagedCollation)
                {
                    return CompareInfo.internal_index(s1, sindex, count, s2, first);
                }
                return this.internal_index_managed(s1, sindex, count, s2, opt, first);
            }
        }
References System.count, System.Globalization.CompareInfo.internal_index(), System.Globalization.CompareInfo.internal_index_managed(), and System.Globalization.CompareInfo.UseManagedCollation.
Referenced by System.Globalization.CompareInfo.IndexOfCore(), and System.Globalization.CompareInfo.LastIndexOfCore().