Terraria Decompiled: System.Globalization.CompareInfo.StartsWith
StartsWith() [2/2]
bool System.Globalization.CompareInfo.StartsWith (string source, string prefix, CompareOptions options) inline private
Definition at line 1596 of file CompareInfo.cs.
        {
            if (CompareInfo.UseManagedCollation)
            {
                return this.GetCollator().IsPrefix(source, prefix, options);
            }
            return source.Length >= prefix.Length && this.Compare(source, 0, prefix.Length, prefix, 0, prefix.Length, options) == 0;
        }
References System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.GetCollator(), System.Globalization.ISimpleCollator.IsPrefix(), System.options, and System.Globalization.CompareInfo.UseManagedCollation.
Referenced by System.Globalization.CompareInfo.IsPrefix(), System.Globalization.CompareInfo.IsPrefix(), and System.Globalization.CompareInfo.StartsWith().