Terraria Decompiled: System.Globalization.CompareInfo.GetCompareInfo
GetCompareInfo() [2/4]
static CompareInfo System.Globalization.CompareInfo.GetCompareInfo (int culture, Assembly assembly) inline static
Definition at line 270 of file CompareInfo.cs.
        {
            if (assembly == null)
            {
                throw new ArgumentNullException("assembly");
            }
            if (assembly != typeof(object).Module.Assembly)
            {
                throw new ArgumentException("Only mscorlib's assembly is valid.");
            }
            return CompareInfo.GetCompareInfo(culture);
        }
References System.Reflection.Module.Assembly, System.Globalization.CompareInfo.culture, and System.Globalization.CompareInfo.GetCompareInfo().
Referenced by System.Globalization.CompareInfo.GetCompareInfo(), and System.Globalization.CompareInfo.GetCompareInfo().