Terraria Decompiled: System.Globalization.CompareInfo.GetCollator
GetCollator()
ISimpleCollator System.Globalization.CompareInfo.GetCollator () inline private
Definition at line 1340 of file CompareInfo.cs.
        {
            if (this.collator != null)
            {
                return this.collator;
            }
            if (CompareInfo.collators == null)
            {
                Interlocked.CompareExchange<Dictionary<string, ISimpleCollator>>(ref CompareInfo.collators, new Dictionary<string, ISimpleCollator>(StringComparer.Ordinal), null);
            }
            Dictionary<string, ISimpleCollator> dictionary = CompareInfo.collators;
            lock (dictionary)
            {
                if (!CompareInfo.collators.TryGetValue(this._sortName, out this.collator))
                {
                    this.collator = new SimpleCollator(CultureInfo.GetCultureInfo(this.m_name));
                    CompareInfo.collators[this._sortName] = this.collator;
                }
            }
            return this.collator;
        }
References System.Globalization.CompareInfo._sortName, System.Globalization.CompareInfo.collator, System.Globalization.CompareInfo.collators, System.Threading.Interlocked.CompareExchange(), System.dictionary, System.Globalization.CultureInfo.GetCultureInfo(), and System.StringComparer.Ordinal.
Referenced by System.Globalization.CompareInfo.CreateSortKeyCore(), System.Globalization.CompareInfo.EndsWith(), System.Globalization.CompareInfo.internal_compare_managed(), System.Globalization.CompareInfo.internal_index_managed(), System.Globalization.CompareInfo.internal_index_managed(), and System.Globalization.CompareInfo.StartsWith().