Terraria Decompiled: System.Globalization.CompareInfo.CompareOptionNone
CompareOptionNone()
int System.Globalization.CompareInfo.CompareOptionNone (ReadOnlySpan< char > string1, ReadOnlySpan< char > string2) inline package
Definition at line 491 of file CompareInfo.cs.
        {
            if (string1.Length == 0 || string2.Length == 0)
            {
                return string1.Length - string2.Length;
            }
            if (!GlobalizationMode.Invariant)
            {
                return this.CompareString(string1, string2, CompareOptions.None);
            }
            return string.CompareOrdinal(string1, string2);
        }
References System.Globalization.CompareInfo.CompareString(), System.Globalization.GlobalizationMode.Invariant, and System.ReadOnlySpan< T >.Length.
Referenced by System.MemoryExtensions.CompareTo(), and System.MemoryExtensions.Equals().