Terraria Decompiled: System.Globalization.CompareInfo.GetIgnoreCaseHash
GetIgnoreCaseHash()
static unsafe int System.Globalization.CompareInfo.GetIgnoreCaseHash (string source) inline static package
Definition at line 1221 of file CompareInfo.cs.
        {
            if (source.Length == 0)
            {
                return source.GetHashCode();
            }
            char[] array = null;
            Span<char> span;
            if (source.Length <= 255)
            {
                span = new Span<char>(stackalloc byte[(UIntPtr)510], 255);
            }
            else
            {
                span = (array = ArrayPool<char>.Shared.Rent(source.Length));
            }
            Span<char> span2 = span;
            int num = source.AsSpan().ToUpperInvariant(span2);
            int num2 = Marvin.ComputeHash32(MemoryMarshal.AsBytes<char>(span2.Slice(0, num)), Marvin.DefaultSeed);
            if (array != null)
            {
                ArrayPool<char>.Shared.Return(array, false);
            }
            return num2;
        }
References System.array, System.Marvin.ComputeHash32(), System.Marvin.DefaultSeed, System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), and System.source.
Referenced by System.OrdinalComparer.GetHashCode(), System.OrdinalIgnoreCaseComparer.GetHashCode(), System.Globalization.CompareInfo.GetHashCode(), and System.Globalization.CompareInfo.GetHashCodeOfString().