Terraria Decompiled: System.Delegate.GetCandidateMethod
GetCandidateMethod()
static MethodInfo System.Delegate.GetCandidateMethod (Type type, Type target, string method, BindingFlags bflags, bool ignoreCase, bool throwOnBindFailure) inline static private
Definition at line 306 of file Delegate.cs.
        {
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }
            if (method == null)
            {
                throw new ArgumentNullException("method");
            }
            if (!type.IsSubclassOf(typeof(MulticastDelegate)))
            {
                throw new ArgumentException("type is not subclass of MulticastDelegate.");
            }
            MethodInfo methodInfo = type.GetMethod("Invoke");
            ParameterInfo[] parametersInternal = methodInfo.GetParametersInternal();
            Type[] array = new Type[parametersInternal.Length];
            for (int i = 0; i < parametersInternal.Length; i++)
            {
                array[i] = parametersInternal[i].ParameterType;
            }
            BindingFlags bindingFlags = BindingFlags.DeclaredOnly | BindingFlags.Public | BindingFlags.NonPublic | BindingFlags.ExactBinding | bflags;
            if (ignoreCase)
            {
                bindingFlags |= BindingFlags.IgnoreCase;
            }
            MethodInfo methodInfo2 = null;
            Type type2 = target;
            while (type2 != null)
            {
                MethodInfo methodInfo3 = type2.GetMethod(method, bindingFlags, null, array, Array.Empty<ParameterModifier>());
                if (methodInfo3 != null && Delegate.return_type_match(methodInfo.ReturnType, methodInfo3.ReturnType))
                {
                    methodInfo2 = methodInfo3;
                    break;
                }
                type2 = type2.BaseType;
            }
            if (!(methodInfo2 == null))
            {
                return methodInfo2;
            }
            if (throwOnBindFailure)
            {
                throw new ArgumentException("Couldn't bind to method '" + method + "'.");
            }
            return null;
        }
References System.array, System.Type.BaseType, System.Type.GetMethod(), System.Reflection.MethodBase.GetParametersInternal(), System.Type.IsSubclassOf(), System.Delegate.method, System.Reflection.ParameterInfo.ParameterType, System.Delegate.return_type_match(), and System.Reflection.MethodInfo.ReturnType.
Referenced by System.Delegate.CreateDelegate(), and System.Delegate.CreateDelegate().