Terraria Decompiled: System.Delegate.Combine
Combine() [1/2]
static Delegate System.Delegate.Combine (Delegate a, Delegate b) inline static
Definition at line 544 of file Delegate.cs.
        {
            if (a == null)
            {
                return b;
            }
            if (b == null)
            {
                return a;
            }
            if (a.GetType() != b.GetType())
            {
                throw new ArgumentException(string.Format("Incompatible Delegate Types. First is {0} second is {1}.", a.GetType().FullName, b.GetType().FullName));
            }
            return a.CombineImpl(b);
        }
References System.Delegate.CombineImpl(), and System.Format.
Referenced by System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.AddEventHandlerNoLock(), System.Runtime.Serialization.SerializationEvents.AddOnDelegate(), System.Runtime.Serialization.ObjectManager.AddOnDeserialization(), System.Delegate.Combine(), CsvHelper.CsvWriter.CombineDelegates(), Terraria.Initializers.AssetInitializer.CreateAssetServices(), System.DelegateSerializationHolder.DelegateSerializationHolder(), Terraria.Main.DrawMenu(), Terraria.Main.LoadContent(), Terraria.GameContent.UI.States.UITextWrappingTest.MakeElement(), Terraria.Social.WeGame.NetServerSocialModule.OnLobbyCreated(), rail.RailCallBackHelper.RegisterCallback(), and ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup.SteelSeriesDeviceGroup().