Terraria Decompiled: System.Delegate.Equals
Equals()
override bool System.Delegate.Equals (object obj) inline
Definition at line 477 of file Delegate.cs.
        {
            Delegate @delegate = obj as Delegate;
            if (@delegate == null)
            {
                return false;
            }
            if (@delegate.m_target != this.m_target || !(@delegate.Method == this.Method))
            {
                return false;
            }
            if (@delegate.data == null && this.data == null)
            {
                return true;
            }
            if (@delegate.data != null && this.data != null)
            {
                return @delegate.data.target_type == this.data.target_type && @delegate.data.method_name == this.data.method_name;
            }
            if (@delegate.data != null)
            {
                return @delegate.data.target_type == null;
            }
            return this.data != null && this.data.target_type == null;
        }
References System.Delegate.data, System.Delegate, System.Delegate.m_target, System.Delegate.Method, System.DelegateData.method_name, and System.obj.
Referenced by System.Delegate.operator==(), System.Delegate.RemoveImpl(), and System.MulticastDelegate.RemoveImpl().