Terraria Decompiled: System.Delegate.CreateDelegate
CreateDelegate() [5/11]
static Delegate System.Delegate.CreateDelegate (Type type, object firstArgument, MethodInfo method, bool throwOnBindFailure, bool allowClosed) inline static private
Definition at line 136 of file Delegate.cs.
        {
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }
            if (method == null)
            {
                throw new ArgumentNullException("method");
            }
            if (!type.IsSubclassOf(typeof(MulticastDelegate)))
            {
                throw new ArgumentException("type is not a subclass of Multicastdelegate");
            }
            MethodInfo methodInfo = type.GetMethod("Invoke");
            if (!Delegate.return_type_match(methodInfo.ReturnType, method.ReturnType))
            {
                if (throwOnBindFailure)
                {
                    throw new ArgumentException("method return type is incompatible");
                }
                return null;
            }
            else
            {
                ParameterInfo[] parametersInternal = methodInfo.GetParametersInternal();
                ParameterInfo[] parametersInternal2 = method.GetParametersInternal();
                bool flag;
                if (firstArgument != null)
                {
                    if (!method.IsStatic)
                    {
                        flag = parametersInternal2.Length == parametersInternal.Length;
                    }
                    else
                    {
                        flag = parametersInternal2.Length == parametersInternal.Length + 1;
                    }
                }
                else if (!method.IsStatic)
                {
                    flag = parametersInternal2.Length + 1 == parametersInternal.Length;
                    if (!flag)
                    {
                        flag = parametersInternal2.Length == parametersInternal.Length;
                    }
                }
                else
                {
                    flag = parametersInternal2.Length == parametersInternal.Length;
                    if (!flag)
                    {
                        flag = parametersInternal2.Length == parametersInternal.Length + 1;
                    }
                }
                if (!flag)
                {
                    if (throwOnBindFailure)
                    {
                        throw new TargetParameterCountException("Parameter count mismatch.");
                    }
                    return null;
                }
                else
                {
                    DelegateData delegateData = new DelegateData();
                    bool flag2;
                    if (firstArgument != null)
                    {
                        if (!method.IsStatic)
{
                            flag2 = Delegate.arg_type_match_this(firstArgument.GetType(), method.DeclaringType, true);
                            for (int i = 0; i < parametersInternal2.Length; i++)
{
                                flag2 &= Delegate.arg_type_match(parametersInternal[i].ParameterType, parametersInternal2[i].ParameterType);
                            }
                        }
                        else
{
                            flag2 = Delegate.arg_type_match(firstArgument.GetType(), parametersInternal2[0].ParameterType);
                            for (int j = 1; j < parametersInternal2.Length; j++)
{
                                flag2 &= Delegate.arg_type_match(parametersInternal[j - 1].ParameterType, parametersInternal2[j].ParameterType);
                            }
                            delegateData.curried_first_arg = true;
                        }
                    }
                    else if (!method.IsStatic)
                    {
                        if (parametersInternal2.Length + 1 == parametersInternal.Length)
{
                            flag2 = Delegate.arg_type_match_this(parametersInternal[0].ParameterType, method.DeclaringType, false);
                            for (int k = 0; k < parametersInternal2.Length; k++)
{
                                flag2 &= Delegate.arg_type_match(parametersInternal[k + 1].ParameterType, parametersInternal2[k].ParameterType);
                            }
                        }
                        else
{
                            flag2 = allowClosed;
                            for (int l = 0; l < parametersInternal2.Length; l++)
{
                                flag2 &= Delegate.arg_type_match(parametersInternal[l].ParameterType, parametersInternal2[l].ParameterType);
                            }
                        }
                    }
                    else if (parametersInternal.Length + 1 == parametersInternal2.Length)
                    {
                        flag2 = !parametersInternal2[0].ParameterType.IsValueType && !parametersInternal2[0].ParameterType.IsByRef && allowClosed;
                        for (int m = 0; m < parametersInternal.Length; m++)
{
                            flag2 &= Delegate.arg_type_match(parametersInternal[m].ParameterType, parametersInternal2[m + 1].ParameterType);
                        }
                        delegateData.curried_first_arg = true;
                    }
                    else
                    {
                        flag2 = true;
                        for (int n = 0; n < parametersInternal2.Length; n++)
{
                            flag2 &= Delegate.arg_type_match(parametersInternal[n].ParameterType, parametersInternal2[n].ParameterType);
                        }
                    }
                    if (flag2)
                    {
                        Delegate @delegate = Delegate.CreateDelegate_internal(type, firstArgument, method, throwOnBindFailure);
                        if (@delegate != null)
{
                            @delegate.original_method_info = method;
                        }
                        if (delegateData != null)
{
                            @delegate.data = delegateData;
                        }
                        return @delegate;
                    }
                    if (throwOnBindFailure)
                    {
                        throw new ArgumentException("method arguments are incompatible");
                    }
                    return null;
                }
            }
        }
References System.Delegate.arg_type_match(), System.Delegate.arg_type_match_this(), System.Delegate.CreateDelegate_internal(), System.Type.GetMethod(), System.Reflection.MethodBase.GetParametersInternal(), System.Type.IsByRef, System.Type.IsSubclassOf(), System.Type.IsValueType, System.Delegate.method, System.Reflection.ParameterInfo.ParameterType, System.Delegate.return_type_match(), and System.Reflection.MethodInfo.ReturnType.