Terraria Decompiled: System.Delegate.DynamicInvokeImpl
DynamicInvokeImpl()
virtual object System.Delegate.DynamicInvokeImpl (object[] args) inline protected virtual
Reimplemented in System.MulticastDelegate.
Definition at line 428 of file Delegate.cs.
        {
            if (this.Method == null)
            {
                Type[] array = new Type[args.Length];
                for (int i = 0; i < args.Length; i++)
                {
                    array[i] = args[i].GetType();
                }
                this.method_info = this.m_target.GetType().GetMethod(this.data.method_name, array);
            }
            object obj = this.m_target;
            if (this.data == null)
            {
                this.InitializeDelegateData();
            }
            if (this.Method.IsStatic)
            {
                if (this.data.curried_first_arg)
                {
                    if (args == null)
                    {
                        args = new object[] { obj };
                    }
                    else
                    {
                        Array.Resize<object>(ref args, args.Length + 1);
                        Array.Copy(args, 0, args, 1, args.Length - 1);
                        args[0] = obj;
                    }
                    obj = null;
                }
            }
            else if (this.m_target == null && args != null && args.Length != 0)
            {
                obj = args[0];
                Array.Copy(args, 1, args, 0, args.Length - 1);
                Array.Resize<object>(ref args, args.Length - 1);
            }
            return this.Method.Invoke(obj, args);
        }
References System.array, System.Array.Copy(), System.DelegateData.curried_first_arg, System.Delegate.data, System.Delegate.InitializeDelegateData(), System.Reflection.MethodInfo.Invoke(), System.Reflection.MethodBase.IsStatic, System.Delegate.m_target, System.Delegate.Method, System.DelegateData.method_name, and System.obj.
Referenced by System.Delegate.DynamicInvoke().