Terraria Decompiled: System.Delegate.GetHashCode
GetHashCode()
override int System.Delegate.GetHashCode () inline
Definition at line 504 of file Delegate.cs.
        {
            MethodInfo methodInfo = this.Method;
            return ((methodInfo != null) ? methodInfo.GetHashCode() : base.GetType().GetHashCode()) ^ RuntimeHelpers.GetHashCode(this.m_target);
        }
References System.Reflection.MethodInfo.GetHashCode(), System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(), and System.Delegate.Method.
Referenced by System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.GetPreferredToken().