Terraria Decompiled: Terraria.Map.WorldMap.UnlockMapSection
UnlockMapSection()
void Terraria.Map.WorldMap.UnlockMapSection (int sectionX, int sectionY) inline
Definition at line 121 of file WorldMap.cs.
        {
            int num = sectionX * 200;
            int num2 = num + 200;
            int num3 = sectionY * 150;
            int num4 = num3 + 150;
            int num5 = 40;
            num = Utils.Clamp<int>(num, num5, Main.maxTilesX - num5);
            num2 = Utils.Clamp<int>(num2, num5, Main.maxTilesX - num5);
            num3 = Utils.Clamp<int>(num3, num5, Main.maxTilesY - num5);
            num4 = Utils.Clamp<int>(num4, num5, Main.maxTilesY - num5);
            if (DebugOptions.unlockMap == 2)
            {
                for (int i = num; i < num2; i++)
                {
                    for (int j = num3; j < num4; j++)
                    {
                        this.UnlockMapTilePretty(i, j);
                    }
                }
                return;
            }
            for (int k = num; k < num2; k++)
            {
                for (int l = num3; l < num4; l++)
                {
                    this.UpdateLighting(k, l, byte.MaxValue);
                }
            }
        }
References Terraria.Utils.Clamp(), Terraria.Testing.DebugOptions.unlockMap, Terraria.Map.WorldMap.UnlockMapTilePretty(), and Terraria.Map.WorldMap.UpdateLighting().
Referenced by Terraria.Main.DoDraw().