Terraria Decompiled: Terraria.Map.WorldMap.Load
Load()
void Terraria.Map.WorldMap.Load () inline
Definition at line 194 of file WorldMap.cs.
        {
            Lighting.Clear();
            bool isCloudSave = Main.ActivePlayerFileData.IsCloudSave;
            if (isCloudSave && SocialAPI.Cloud == null)
            {
                return;
            }
            if (!Main.mapEnabled)
            {
                return;
            }
            string text;
            if (!WorldMap.TryGetMapPath(Main.ActivePlayerFileData, Main.ActiveWorldFileData, out text))
            {
                Main.MapFileMetadata = FileMetadata.FromCurrentSettings(FileType.Map);
                return;
            }
            using (MemoryStream memoryStream = new MemoryStream(FileUtilities.ReadAllBytes(text, isCloudSave)))
            {
                using (BinaryReader binaryReader = new BinaryReader(memoryStream))
                {
                    try
                    {
                        int num = binaryReader.ReadInt32();
                        bool flag = (num & 32768) == 32768;
                        num &= -32769;
                        if (num <= 319)
{
                            if (flag)
{
                                MapHelper.LoadMapVersionCompressed(binaryReader, num);
                            }
                            else if (num <= 91)
{
                                MapHelper.LoadMapVersion1(binaryReader, num);
                            }
                            else
{
                                MapHelper.LoadMapVersion2(binaryReader, num);
                            }
                            this.ClearEdges();
                            Main.clearMap = true;
                            Main.loadMap = true;
                            Main.loadMapLock = true;
                            Main.refreshMap = false;
                        }
                    }
                    catch (Exception ex)
                    {
                        using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", true))
{
                            streamWriter.WriteLine(DateTime.Now);
                            streamWriter.WriteLine(ex);
                            streamWriter.WriteLine("");
                        }
                        if (!isCloudSave)
{
                            File.Copy(text, text + ".bad", true);
                        }
                        this.Clear();
                    }
                }
            }
        }
References Terraria.Main.ActivePlayerFileData, Terraria.Main.ActiveWorldFileData, Terraria.Lighting.Clear(), Terraria.Map.WorldMap.Clear(), Terraria.Map.WorldMap.ClearEdges(), Terraria.Social.SocialAPI.Cloud, System.IO.File.Copy(), Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.IO.FileData.IsCloudSave, Terraria.Map.MapHelper.LoadMapVersion1(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.Main.mapEnabled, System.DateTime.Now, Terraria.Utilities.FileUtilities.ReadAllBytes(), System.IO.BinaryReader.ReadInt32(), System.text, Terraria.Map.WorldMap.TryGetMapPath(), and System.IO.StreamWriter.WriteLine().
Referenced by Terraria.Netplay.InnerClientLoop(), and Terraria.WorldGen.playWorldCallBack().