Terraria Decompiled: Terraria.Map.WorldMap.TryGetMapPath
TryGetMapPath()
static bool Terraria.Map.WorldMap.TryGetMapPath (PlayerFileData playerFileData, WorldFileData worldFileData, out string mapPath) inline static
Definition at line 261 of file WorldMap.cs.
        {
            string text = playerFileData.Path.Substring(0, playerFileData.Path.Length - 4);
            mapPath = text + Path.DirectorySeparatorChar.ToString() + worldFileData.MapFileName + ".map";
            if (worldFileData.UseGuidAsMapName && !FileUtilities.Exists(mapPath, playerFileData.IsCloudSave))
            {
                mapPath = string.Concat(new object[]
                {
                    text,
                    Path.DirectorySeparatorChar.ToString(),
                    worldFileData.WorldId,
                    ".map"
                });
            }
            return FileUtilities.Exists(mapPath, playerFileData.IsCloudSave);
        }
References System.IO.Path.DirectorySeparatorChar, Terraria.Utilities.FileUtilities.Exists(), Terraria.IO.FileData.IsCloudSave, Terraria.IO.FileData.Path, System.text, Terraria.IO.WorldFileData.UseGuidAsMapName, and Terraria.IO.WorldFileData.WorldId.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.HasWorldBeenPlayedByActivePlayer(), and Terraria.Map.WorldMap.Load().