Terraria Decompiled: System.IO.File.Open
Open() [1/3]
static FileStream System.IO.File.Open (string path, FileMode mode) inline static
Definition at line 136 of file File.cs.
        {
            return File.Open(path, mode, (mode == FileMode.Append) ? FileAccess.Write : FileAccess.ReadWrite, FileShare.None);
        }
References System.mode, and System.IO.File.Open().
Referenced by Ionic.Zip.ZipEntry.FigureCrc32(), Ionic.Zip.ZipSegmentedStream.ForUpdate(), Ionic.Zip.SharedUtilities.GetFileLength(), Ionic.Zip.ZipFile.IsZipFile(), System.IO.File.Open(), System.IO.File.Open(), Microsoft.Xna.Framework.Storage.StorageContainer.OpenFile(), Mono.Security.Cryptography.KeyPairPersistence.Save(), Ionic.Zip.ZipEntry.SetInputAndFigureFileLength(), Terraria.Utilities.FileUtilities.Write(), Ionic.Zip.ZipInputStream.ZipInputStream(), and Ionic.Zip.ZipOutputStream.ZipOutputStream().