Terraria Decompiled: System.IO.File.Delete
Delete()
static void System.IO.File.Delete (string path) inline static
Definition at line 94 of file File.cs.
        {
            if (path == null)
            {
                throw new ArgumentNullException("path");
            }
            FileSystem.DeleteFile(Path.GetFullPath(path));
        }
References System.IO.FileSystem.DeleteFile(), and System.IO.Path.GetFullPath().
Referenced by Ionic.Zip.ZipSegmentedStream._SetWriteStream(), Terraria.Testing.QuickLoad.Clear(), Terraria.Utilities.FileUtilities.Delete(), Terraria.WorldBuilding.WorldGenSnapshot.Delete(), Microsoft.Xna.Framework.Storage.StorageContainer.DeleteFile(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(), Ionic.Zip.ZipFile.DeleteFileWithRetry(), Ionic.Zip.ZipEntry.InternalExtract(), Terraria.Main.LoadSettings(), Terraria.Utilities.FileUtilities.Move(), Ionic.Zip.ZipEntry.ReallyDelete(), Mono.Security.Cryptography.KeyPairPersistence.Remove(), Ionic.Zip.ZipFile.RemoveTempFile(), System.Security.Policy.PolicyLevel.Reset(), Ionic.Zip.ZipFile.Save(), System.Reflection.Emit.ModuleBuilder.Save(), and Ionic.Zip.ZipSegmentedStream.TruncateBackward().