Terraria Decompiled: System.IO.File.ReadAllBytes
ReadAllBytes()
static byte[] System.IO.File.ReadAllBytes (string path) inline static
Definition at line 351 of file File.cs.
        {
            byte[] array;
            using (FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 1))
            {
                long length = fileStream.Length;
                if (length > 2147483647L)
                {
                    throw new IOException("The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size.");
                }
                if (length == 0L)
                {
                    array = File.ReadAllBytesUnknownLength(fileStream);
                }
                else
                {
                    int num = 0;
                    int i = (int)length;
                    byte[] array2 = new byte[i];
                    while (i > 0)
                    {
                        int num2 = fileStream.Read(array2, num, i);
                        if (num2 == 0)
{
                            throw Error.GetEndOfFile();
                        }
                        num += num2;
                        i -= num2;
                    }
                    array = array2;
                }
            }
            return array;
        }
References System.array, System.IO.Error.GetEndOfFile(), int, System.L, System.length, System.IO.FileStream.Length, System.IO.FileStream.Read(), and System.IO.File.ReadAllBytesUnknownLength().
Referenced by Terraria.Utilities.FileUtilities.ReadAllBytes(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), System.TimeZoneInfo.TryLoadTzFile(), System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate(), and System.Security.Cryptography.X509Certificates.X509Certificate.X509Certificate().