Terraria Decompiled: System.IO.File.ReadAllBytesAsync
ReadAllBytesAsync()
static Task< byte[]> System.IO.File.ReadAllBytesAsync (string path, CancellationToken cancellationToken = default(CancellationToken)) inline static
Definition at line 876 of file File.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled<byte[]>(cancellationToken);
            }
            FileStream fileStream = new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read, 1, FileOptions.Asynchronous | FileOptions.SequentialScan);
            bool flag = false;
            Task<byte[]> task;
            try
            {
                long length = fileStream.Length;
                if (length > 2147483647L)
                {
                    task = Task.FromException<byte[]>(new IOException("The file is too long. This operation is currently limited to supporting files less than 2 gigabytes in size."));
                }
                else
                {
                    flag = true;
                    task = ((length > 0L) ? File.InternalReadAllBytesAsync(fileStream, (int)length, cancellationToken) : File.InternalReadAllBytesUnknownLengthAsync(fileStream, cancellationToken));
                }
            }
            finally
            {
                if (!flag)
                {
                    fileStream.Dispose();
                }
            }
            return task;
        }
References System.IO.FileStream.Dispose(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.IO.File.InternalReadAllBytesAsync(), System.IO.File.InternalReadAllBytesUnknownLengthAsync(), System.L, System.length, System.IO.FileStream.Length, and System.task.