Terraria Decompiled: System.IO.File.InternalReadAllBytesAsync
InternalReadAllBytesAsync()
static async Task< byte[]> System.IO.File.InternalReadAllBytesAsync (FileStream fs, int count, CancellationToken cancellationToken) inline static private
Definition at line 909 of file File.cs.
        {
            byte[] array;
            try
            {
                int index = 0;
                byte[] bytes = new byte[count];
                for (;;)
                {
                    int num = await fs.ReadAsync(new Memory<byte>(bytes, index, count - index), cancellationToken).ConfigureAwait(false);
                    if (num == 0)
                    {
                        break;
                    }
                    index += num;
                    if (index >= count)
                    {
                        goto Block_3;
                    }
                }
                throw Error.GetEndOfFile();
                Block_3:
                array = bytes;
            }
            finally
            {
                if (fs != null)
                {
                    ((IDisposable)fs).Dispose();
                }
            }
            return array;
        }
References System.array, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.IO.Error.GetEndOfFile(), System.index, and System.IO.FileStream.ReadAsync().
Referenced by System.IO.File.d__71.MoveNext(), and System.IO.File.ReadAllBytesAsync().