Terraria Decompiled: System.IO.File.InternalReadAllBytesUnknownLengthAsync
InternalReadAllBytesUnknownLengthAsync()
static async Task< byte[]> System.IO.File.InternalReadAllBytesUnknownLengthAsync (FileStream fs, CancellationToken cancellationToken) inline static private
Definition at line 944 of file File.cs.
        {
            byte[] rentedArray = ArrayPool<byte>.Shared.Rent(512);
            byte[] array2;
            try
            {
                int bytesRead = 0;
                for (;;)
                {
                    if (bytesRead == rentedArray.Length)
                    {
                        uint num = (uint)(rentedArray.Length * 2);
                        if (num > 2147483591U)
{
                            num = (uint)Math.Max(2147483591, rentedArray.Length + 1);
                        }
                        byte[] array = ArrayPool<byte>.Shared.Rent((int)num);
                        Buffer.BlockCopy(rentedArray, 0, array, 0, bytesRead);
                        ArrayPool<byte>.Shared.Return(rentedArray, false);
                        rentedArray = array;
                    }
                    int num2 = await fs.ReadAsync(rentedArray.AsMemory(bytesRead), cancellationToken).ConfigureAwait(false);
                    if (num2 == 0)
                    {
                        break;
                    }
                    bytesRead += num2;
                }
                array2 = rentedArray.AsSpan(0, bytesRead).ToArray();
            }
            finally
            {
                fs.Dispose();
                ArrayPool<byte>.Shared.Return(rentedArray, false);
            }
            return array2;
        }
References System.array, System.Buffer.BlockCopy(), System.IO.FileStream.Dispose(), System.Math.Max(), System.IO.FileStream.ReadAsync(), System.Buffers.ArrayPool< T >.Shared, and System.U.
Referenced by System.IO.File.d__72.MoveNext(), and System.IO.File.ReadAllBytesAsync().