Terraria Decompiled: System.IO.File.Move
Move()
static void System.IO.File.Move (string sourceFileName, string destFileName) inline static
Definition at line 707 of file File.cs.
        {
            if (sourceFileName == null)
            {
                throw new ArgumentNullException("sourceFileName", "File name cannot be null.");
            }
            if (destFileName == null)
            {
                throw new ArgumentNullException("destFileName", "File name cannot be null.");
            }
            if (sourceFileName.Length == 0)
            {
                throw new ArgumentException("Empty file name is not legal.", "sourceFileName");
            }
            if (destFileName.Length == 0)
            {
                throw new ArgumentException("Empty file name is not legal.", "destFileName");
            }
            string fullPath = Path.GetFullPath(sourceFileName);
            string fullPath2 = Path.GetFullPath(destFileName);
            if (!FileSystem.FileExists(fullPath))
            {
                throw new FileNotFoundException(SR.Format("Could not find file '{0}'.", fullPath), fullPath);
            }
            FileSystem.MoveFile(fullPath, fullPath2);
        }
References System.IO.FileSystem.FileExists(), SR.Format(), System.IO.Path.GetFullPath(), and System.IO.FileSystem.MoveFile().
Referenced by Ionic.Zip.ZipSegmentedStream._SetWriteStream(), Ionic.Zip.ZipEntry.InternalExtract(), Terraria.Utilities.FileUtilities.Move(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile(), ReLogic.OS.Linux.PathService.MoveToRecycleBin(), Ionic.Zip.ZipFile.Save(), and Ionic.Zip.ZipSegmentedStream.TruncateBackward().