Terraria Decompiled: System.IO.File.OpenRead
OpenRead()
static FileStream System.IO.File.OpenRead (string path) inline static
Definition at line 258 of file File.cs.
        {
            return new FileStream(path, FileMode.Open, FileAccess.Read, FileShare.Read);
        }
Referenced by Ionic.Zip.ZipSegmentedStream._SetReadStream(), Terraria.Utilities.FileUtilities.Copy(), Mono.Security.StrongName.Hash(), Microsoft.Win32.KeyHandler.Load(), Terraria.IO.Preferences.Load(), Terraria.WorldBuilding.WorldGenSnapshot.Load(), Terraria.Utilities.TileSnapshot.Load(), ReLogic.Content.Sources.FileSystemContentSource.OpenStream(), ReLogic.Content.Sources.XnaDirectContentSource.OpenStream(), Terraria.IO.ResourcePack.OpenStream(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), Terraria.WorldGen.PrepForRegen(), Terraria.Utilities.FileUtilities.Read(), Terraria.WorldBuilding.WorldGenSnapshot.ReadSnapshot(), Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion(), Mono.Security.StrongName.Sign(), System.TermInfoReader.TermInfoReader(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview(), ReLogic.Content.AssetRepository.UpdateWatchedAsset(), and Mono.Security.StrongName.Verify().