Terraria Decompiled: System.IO.File.ReadAllBytesUnknownLength
ReadAllBytesUnknownLength()
static unsafe byte[] System.IO.File.ReadAllBytesUnknownLength (FileStream fs) inline static private
Definition at line 387 of file File.cs.
        {
            byte[] array = null;
            Span<byte> span = new Span<byte>(stackalloc byte[(UIntPtr)512], 512);
            byte[] array3;
            try
            {
                int num = 0;
                for (;;)
                {
                    if (num == span.Length)
                    {
                        uint num2 = (uint)(span.Length * 2);
                        if (num2 > 2147483591U)
{
                            num2 = (uint)Math.Max(2147483591, span.Length + 1);
                        }
                        byte[] array2 = ArrayPool<byte>.Shared.Rent((int)num2);
                        span.CopyTo(array2);
                        if (array != null)
{
                            ArrayPool<byte>.Shared.Return(array, false);
                        }
                        span = (array = array2);
                    }
                    int num3 = fs.Read(span.Slice(num));
                    if (num3 == 0)
                    {
                        break;
                    }
                    num += num3;
                }
                array3 = span.Slice(0, num).ToArray();
            }
            finally
            {
                if (array != null)
                {
                    ArrayPool<byte>.Shared.Return(array, false);
                }
            }
            return array3;
        }
References System.array, System.Span< T >.CopyTo(), System.Span< T >.Length, System.Math.Max(), System.IO.FileStream.Read(), System.Buffers.ArrayPool< T >.Shared, System.Span< T >.Slice(), and System.U.
Referenced by System.IO.File.ReadAllBytes().