Terraria Decompiled: System.IO.File.InternalWriteAllTextAsync
InternalWriteAllTextAsync()
static async Task System.IO.File.InternalWriteAllTextAsync (StreamWriter sw, string contents, CancellationToken cancellationToken) inline static private
Definition at line 1112 of file File.cs.
        {
            char[] buffer = null;
            try
            {
                buffer = ArrayPool<char>.Shared.Rent(4096);
                int count = contents.Length;
                int batchSize;
                for (int index = 0; index < count; index += batchSize)
                {
                    batchSize = Math.Min(4096, count - index);
                    contents.CopyTo(index, buffer, 0, batchSize);
                    await sw.WriteAsync(new ReadOnlyMemory<char>(buffer, 0, batchSize), cancellationToken).ConfigureAwait(false);
                }
                cancellationToken.ThrowIfCancellationRequested();
                await sw.FlushAsync().ConfigureAwait(false);
            }
            finally
            {
                sw.Dispose();
                if (buffer != null)
                {
                    ArrayPool<char>.Shared.Return(buffer, false);
                }
            }
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.count, System.IO.StreamWriter.Dispose(), System.IO.StreamWriter.FlushAsync(), System.index, System.Math.Min(), System.Buffers.ArrayPool< T >.Shared, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.IO.StreamWriter.WriteAsync().
Referenced by System.IO.File.AppendAllTextAsync(), System.IO.File.d__81.MoveNext(), and System.IO.File.WriteAllTextAsync().