Terraria Decompiled: System.IO.File.InternalWriteAllLinesAsync
InternalWriteAllLinesAsync()
static async Task System.IO.File.InternalWriteAllLinesAsync (TextWriter writer, IEnumerable< string > contents, CancellationToken cancellationToken) inline static private
Definition at line 1095 of file File.cs.
        {
            using (writer)
            {
                foreach (string text in contents)
                {
                    cancellationToken.ThrowIfCancellationRequested();
                    await writer.WriteLineAsync(text).ConfigureAwait(false);
                }
                IEnumerator<string> enumerator = null;
                cancellationToken.ThrowIfCancellationRequested();
                await writer.FlushAsync().ConfigureAwait(false);
            }
            TextWriter textWriter = null;
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.TextWriter.FlushAsync(), System.text, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.IO.TextWriter.WriteLineAsync().
Referenced by System.IO.File.AppendAllLinesAsync(), System.IO.File.d__80.MoveNext(), and System.IO.File.WriteAllLinesAsync().