Terraria Decompiled: System.IO.File.InternalReadAllLinesAsync
InternalReadAllLinesAsync()
static async Task< string[]> System.IO.File.InternalReadAllLinesAsync (string path, Encoding encoding, CancellationToken cancellationToken) inline static private
Definition at line 1044 of file File.cs.
        {
            string[] array;
            using (StreamReader sr = File.AsyncStreamReader(path, encoding))
            {
                cancellationToken.ThrowIfCancellationRequested();
                List<string> lines = new List<string>();
                string text;
                while ((text = await sr.ReadLineAsync().ConfigureAwait(false)) != null)
                {
                    lines.Add(text);
                    cancellationToken.ThrowIfCancellationRequested();
                }
                array = lines.ToArray();
            }
            return array;
        }
References System.Collections.Generic.List< T >.Add(), System.array, System.IO.File.AsyncStreamReader(), System.IO.StreamReader.ReadLineAsync(), System.text, System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Collections.Generic.List< T >.ToArray().
Referenced by System.IO.File.d__77.MoveNext(), and System.IO.File.ReadAllLinesAsync().