Terraria Decompiled: System.IO.File.GetUtcDateTimeOffset
GetUtcDateTimeOffset()
static DateTimeOffset System.IO.File.GetUtcDateTimeOffset (DateTime dateTime) inline static package
Definition at line 154 of file File.cs.
        {
            if (dateTime.Kind == DateTimeKind.Unspecified)
            {
                return DateTime.SpecifyKind(dateTime, DateTimeKind.Utc);
            }
            return dateTime.ToUniversalTime();
        }
References System.DateTime.Kind, System.DateTime.SpecifyKind(), and System.DateTime.ToUniversalTime().
Referenced by System.IO.Directory.SetCreationTimeUtc(), System.IO.File.SetCreationTimeUtc(), System.IO.Directory.SetLastAccessTimeUtc(), System.IO.File.SetLastAccessTimeUtc(), System.IO.Directory.SetLastWriteTimeUtc(), and System.IO.File.SetLastWriteTimeUtc().