Terraria Decompiled: System.IO.File.Exists
Exists()
static bool System.IO.File.Exists (string path) inline static
Definition at line 104 of file File.cs.
        {
            try
            {
                if (path == null)
                {
                    return false;
                }
                if (path.Length == 0)
                {
                    return false;
                }
                path = Path.GetFullPath(path);
                if (path.Length > 0 && PathInternal.IsDirectorySeparator(path[path.Length - 1]))
                {
                    return false;
                }
                return FileSystem.FileExists(path);
            }
            catch (ArgumentException)
            {
            }
            catch (IOException)
            {
            }
            catch (UnauthorizedAccessException)
            {
            }
            return false;
        }
References System.IO.FileSystem.FileExists(), System.IO.Path.GetFullPath(), and System.IO.PathInternal.IsDirectorySeparator().
Referenced by Ionic.Zip.ZipFile._InitInstance(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._readProps(), Ionic.Zip.ZipSegmentedStream._SetWriteStream(), Ionic.Zip.ZipFile.AddItem(), System.Reflection.Emit.AssemblyBuilder.check_name_and_filename(), Microsoft.Xna.Framework.Content.ContentManager.CheckRawExtensions(), Terraria.Testing.QuickLoad.Clear(), System.Runtime.Remoting.RemotingConfiguration.Configure(), System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile(), Ionic.Zip.ZipEntry.Create(), System.Security.Policy.Zone.CreateFromUrl(), Terraria.IO.ResourcePackList.CreatePacksFromSavedJson(), System.Reflection.Emit.AssemblyBuilder.DefineUnmanagedResource(), System.Reflection.Emit.ModuleBuilder.DefineUnmanagedResource(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(), Terraria.Utilities.FileUtilities.Exists(), Microsoft.Xna.Framework.Storage.StorageContainer.FileExists(), System.IO.IsolatedStorage.IsolatedStorageFile.FileExists(), System.Resources.FileBasedResourceGroveler.FindResourceFile(), System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime(), Ionic.Zip.SharedUtilities.GetFileLength(), System.IO.PathInternal.GetIsCaseSensitive(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastAccessTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime(), Microsoft.Win32.KeyHandler.GetRegisteredBootTime(), Microsoft.Win32.KeyHandler.GetSystemBootTime(), Terraria.IO.ResourcePack.HasFile(), System.Resources.FileBasedResourceGroveler.HasNeutralResources(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_GetIconName(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_GetIconName(), Ionic.Zip.ZipEntry.InternalExtract(), System.Reflection.Assembly.InternalGetSatelliteAssembly(), Terraria.Netplay.IsBanned(), Ionic.Zip.ZipFile.IsZipFile(), Microsoft.Win32.KeyHandler.Load(), Mono.Security.Cryptography.KeyPairPersistence.Load(), Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Load(), Terraria.IO.Preferences.Load(), Mono.Security.StrongNameManager.LoadConfig(), System.Security.Cryptography.CryptoConfig.LoadConfig(), Terraria.Main.LoadDedConfig(), System.Security.Policy.PolicyLevel.LoadFromFile(), Terraria.Main.LoadSettings(), Terraria.Utilities.FileUtilities.Move(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile(), ReLogic.OS.Linux.PathService.MoveToRecycleBin(), Microsoft.Xna.Framework.Content.SongReader.Normalize(), Microsoft.Xna.Framework.Content.VideoReader.Normalize(), Terraria.Main.OpenLegacySettings(), Terraria.Testing.ChatCommands.DebugCommandProcessor.OpenMemo(), Terraria.Main.OpenRecent(), ReLogic.Content.Sources.FileSystemContentSource.OpenStream(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.TitleContainer.ReadToPointer(), System.Security.Policy.PolicyLevel.Recover(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh(), Terraria.Utilities.FileUtilities.RemoveReadOnlyAttribute(), Ionic.Zip.ZipFile.RemoveTempFile(), System.Security.Policy.PolicyLevel.Reset(), Terraria.IO.ResourcePack.ResourcePack(), Ionic.Zip.ZipFile.Save(), Microsoft.Win32.KeyHandler.Save(), System.Security.Policy.PolicyLevel.Save(), Terraria.IO.Preferences.Save(), Ionic.Zip.ZipFile.Save(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotLoadCommand(), Microsoft.Xna.Framework.Media.Song.Song(), Ionic.Zip.ZipSegmentedStream.TruncateBackward(), System.TimeZoneInfo.TryLoadTzFile(), Terraria.Testing.ChatCommands.DebugCommandProcessor.TryProcessMemo(), Terraria.Testing.QuickLoad.TryRead(), Terraria.Social.Base.AWorkshopEntry.TryReadingManifest(), System.TermInfoDriver.TryTermInfoDir(), Ionic.Zip.ZipFile.UpdateItem(), and Microsoft.Xna.Framework.Media.Video.Video().