Terraria Decompiled: System.IO.File.InternalWriteAllBytesAsync
InternalWriteAllBytesAsync()
static async Task System.IO.File.InternalWriteAllBytesAsync (string path, byte[] bytes, CancellationToken cancellationToken) inline static private
Definition at line 1005 of file File.cs.
        {
            using (FileStream fs = new FileStream(path, FileMode.Create, FileAccess.Write, FileShare.Read, 4096, FileOptions.Asynchronous | FileOptions.SequentialScan))
            {
                await fs.WriteAsync(new ReadOnlyMemory<byte>(bytes), cancellationToken).ConfigureAwait(false);
                await fs.FlushAsync(cancellationToken).ConfigureAwait(false);
            }
            FileStream fs = null;
        }
References System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.FileStream.FlushAsync(), and System.IO.FileStream.WriteAsync().
Referenced by System.IO.File.d__74.MoveNext(), and System.IO.File.WriteAllBytesAsync().