Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer
ReadStringIntoBuffer()
void Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer (char quote) inline private
Definition at line 1188 of file JsonTextReader.cs.
        {
            int num = this._charPos;
            int charPos = this._charPos;
            int num2 = this._charPos;
            this._stringBuffer.Position = 0;
            char c2;
            for (;;)
            {
                char c = this._chars[num++];
                if (c <= '\r')
                {
                    if (c != '\0')
                    {
                        if (c != '\n')
{
                            if (c == '\r')
{
                                this._charPos = num - 1;
                                this.ProcessCarriageReturn(true);
                                num = this._charPos;
                            }
                        }
                        else
{
                            this._charPos = num - 1;
                            this.ProcessLineFeed();
                            num = this._charPos;
                        }
                    }
                    else if (this._charsUsed == num - 1)
                    {
                        num--;
                        if (this.ReadData(true) == 0)
{
                            break;
                        }
                    }
                }
                else if (c != '"' && c != '\'')
                {
                    if (c == '\\')
                    {
                        this._charPos = num;
                        if (!this.EnsureChars(0, true))
{
                            goto Block_10;
                        }
                        int num3 = num - 1;
                        c2 = this._chars[num];
                        num++;
                        char c3;
                        if (c2 <= '\\')
{
                            if (c2 <= '\'')
{
                                if (c2 != '"' && c2 != '\'')
{
                                    goto Block_14;
                                }
                            }
                            else if (c2 != '/')
{
                                if (c2 != '\\')
{
                                    goto Block_16;
                                }
                                c3 = '\\';
                                goto IL_0287;
                            }
                            c3 = c2;
                        }
                        else if (c2 <= 'f')
{
                            if (c2 != 'b')
{
                                if (c2 != 'f')
{
                                    goto Block_19;
                                }
                                c3 = '\f';
                            }
                            else
{
                                c3 = '\b';
                            }
                        }
                        else
{
                            if (c2 != 'n')
{
                                switch (c2)
{
                                case 'r':
                                    c3 = '\r';
                                    goto IL_0287;
                                case 't':
                                    c3 = '\t';
                                    goto IL_0287;
                                case 'u':
                                    this._charPos = num;
                                    c3 = this.ParseUnicode();
                                    if (StringUtils.IsLowSurrogate(c3))
{
                                        c3 = '\ufffd';
                                    }
                                    else if (StringUtils.IsHighSurrogate(c3))
{
                                        bool flag;
                                        do
{
                                            flag = false;
                                            if (this.EnsureChars(2, true) && this._chars[this._charPos] == '\\' && this._chars[this._charPos + 1] == 'u')
{
                                                char c4 = c3;
                                                this._charPos += 2;
                                                c3 = this.ParseUnicode();
                                                if (!StringUtils.IsLowSurrogate(c3))
{
                                                    if (StringUtils.IsHighSurrogate(c3))
{
                                                        c4 = '\ufffd';
                                                        flag = true;
                                                    }
                                                    else
{
                                                        c4 = '\ufffd';
                                                    }
                                                }
                                                this.EnsureBufferNotEmpty();
                                                this.WriteCharToBuffer(c4, num2, num3);
                                                num2 = this._charPos;
                                            }
                                            else
{
                                                c3 = '\ufffd';
                                            }
                                        }
                                        while (flag);
                                    }
                                    num = this._charPos;
                                    goto IL_0287;
                                }
                                goto Block_21;
                            }
                            c3 = '\n';
                        }
                        IL_0287:
                        this.EnsureBufferNotEmpty();
                        this.WriteCharToBuffer(c3, num2, num3);
                        num2 = num;
                    }
                }
                else if (this._chars[num - 1] == quote)
                {
                    goto Block_28;
                }
            }
            this._charPos = num;
            throw JsonReaderException.Create(this, "Unterminated string. Expected delimiter: {0}.".FormatWith(CultureInfo.InvariantCulture, quote));
            Block_10:
            throw JsonReaderException.Create(this, "Unterminated string. Expected delimiter: {0}.".FormatWith(CultureInfo.InvariantCulture, quote));
            Block_14:
            Block_16:
            Block_19:
            Block_21:
            this._charPos = num;
            throw JsonReaderException.Create(this, "Bad JSON escape sequence: {0}.".FormatWith(CultureInfo.InvariantCulture, "\\" + c2.ToString()));
            Block_28:
            this.FinishReadStringIntoBuffer(num - 1, charPos, num2);
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.EnsureBufferNotEmpty(), Newtonsoft.Json.JsonTextReader.EnsureChars(), Newtonsoft.Json.JsonTextReader.FinishReadStringIntoBuffer(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.StringUtils.IsHighSurrogate(), Newtonsoft.Json.Utilities.StringUtils.IsLowSurrogate(), Newtonsoft.Json.JsonTextReader.ParseUnicode(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), Newtonsoft.Json.JsonTextReader.ReadData(), and Newtonsoft.Json.JsonTextReader.WriteCharToBuffer().
Referenced by Newtonsoft.Json.JsonTextReader.ParseProperty(), and Newtonsoft.Json.JsonTextReader.ParseString().