Terraria Decompiled: Newtonsoft.Json.JsonTextReader.Read
Read()
override bool Newtonsoft.Json.JsonTextReader.Read () inline
Definition at line 263 of file JsonTextReader.cs.
        {
            this.EnsureBuffer();
            for (;;)
            {
                switch (this._currentState)
                {
                case JsonReader.State.Start:
                case JsonReader.State.Property:
                case JsonReader.State.ArrayStart:
                case JsonReader.State.Array:
                case JsonReader.State.ConstructorStart:
                case JsonReader.State.Constructor:
                    goto IL_004C;
                case JsonReader.State.ObjectStart:
                case JsonReader.State.Object:
                    goto IL_0053;
                case JsonReader.State.PostValue:
                    if (this.ParsePostValue(false))
                    {
                        return true;
                    }
                    continue;
                case JsonReader.State.Finished:
                    goto IL_0065;
                }
                break;
            }
            goto IL_00D1;
            IL_004C:
            return this.ParseValue();
            IL_0053:
            return this.ParseObject();
            IL_0065:
            if (!this.EnsureChars(0, false))
            {
                base.SetToken(JsonToken.None);
                return false;
            }
            this.EatWhitespace();
            if (this._isEndOfFile)
            {
                base.SetToken(JsonToken.None);
                return false;
            }
            if (this._chars[this._charPos] == '/')
            {
                this.ParseComment(true);
                return true;
            }
            throw JsonReaderException.Create(this, "Additional text encountered after finished reading JSON content: {0}.".FormatWith(CultureInfo.InvariantCulture, this._chars[this._charPos]));
            IL_00D1:
            throw JsonReaderException.Create(this, "Unexpected state: {0}.".FormatWith(CultureInfo.InvariantCulture, base.CurrentState));
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonReader._currentState, Newtonsoft.Json.JsonTextReader._isEndOfFile, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.EatWhitespace(), Newtonsoft.Json.JsonTextReader.EnsureBuffer(), Newtonsoft.Json.JsonTextReader.EnsureChars(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseObject(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), and Newtonsoft.Json.JsonTextReader.ParseValue().