Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer
ReadNumberIntoBuffer()
void Newtonsoft.Json.JsonTextReader.ReadNumberIntoBuffer () inline private
Definition at line 1413 of file JsonTextReader.cs.
        {
            int num = this._charPos;
            for (;;)
            {
                char c = this._chars[num];
                if (c == '\0')
                {
                    this._charPos = num;
                    if (this._charsUsed != num)
                    {
                        return;
                    }
                    if (this.ReadData(true) == 0)
                    {
                        break;
                    }
                }
                else
                {
                    if (this.ReadNumberCharIntoBuffer(c, num))
                    {
                        return;
                    }
                    num++;
                }
            }
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonTextReader.ReadData(), and Newtonsoft.Json.JsonTextReader.ReadNumberCharIntoBuffer().
Referenced by Newtonsoft.Json.JsonTextReader.ParseNumber().