Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ReadStringValue
ReadStringValue()
object Newtonsoft.Json.JsonTextReader.ReadStringValue (ReadType readType) inline private
Definition at line 495 of file JsonTextReader.cs.
        {
            this.EnsureBuffer();
            switch (this._currentState)
            {
            case JsonReader.State.Start:
            case JsonReader.State.Property:
            case JsonReader.State.ArrayStart:
            case JsonReader.State.Array:
            case JsonReader.State.ConstructorStart:
            case JsonReader.State.Constructor:
                break;
            case JsonReader.State.Complete:
            case JsonReader.State.ObjectStart:
            case JsonReader.State.Object:
            case JsonReader.State.Closed:
            case JsonReader.State.Error:
                goto IL_02E1;
            case JsonReader.State.PostValue:
                if (this.ParsePostValue(true))
                {
                    return null;
                }
                break;
            case JsonReader.State.Finished:
                this.ReadFinished();
                return null;
            default:
                goto IL_02E1;
            }
            char c;
            for (;;)
            {
                c = this._chars[this._charPos];
                if (c <= 'I')
                {
                    if (c <= '\r')
                    {
                        if (c != '\0')
{
                            switch (c)
{
                            case '\t':
                                break;
                            case '\n':
                                this.ProcessLineFeed();
                                continue;
                            case '\v':
                            case '\f':
                                goto IL_02B8;
                            case '\r':
                                this.ProcessCarriageReturn(false);
                                continue;
                            default:
                                goto IL_02B8;
                            }
                        }
                        else
{
                            if (this.ReadNullChar())
{
                                break;
                            }
                            continue;
                        }
                    }
                    else
                    {
                        switch (c)
{
                        case ' ':
                            break;
                        case '!':
                        case '#':
                        case '$':
                        case '%':
                        case '&':
                        case '(':
                        case ')':
                        case '*':
                        case '+':
                            goto IL_02B8;
                        case '"':
                        case '\'':
                            goto IL_0165;
                        case ',':
                            this.ProcessValueComma();
                            continue;
                        case '-':
                            goto IL_0175;
                        case '.':
                        case '0':
                        case '1':
                        case '2':
                        case '3':
                        case '4':
                        case '5':
                        case '6':
                        case '7':
                        case '8':
                        case '9':
                            goto IL_01A8;
                        case '/':
                            this.ParseComment(false);
                            continue;
                        default:
                            if (c != 'I')
{
                                goto IL_02B8;
                            }
                            goto IL_0224;
                        }
                    }
                    this._charPos++;
                    continue;
                }
                if (c <= ']')
                {
                    if (c == 'N')
                    {
                        goto IL_022C;
                    }
                    if (c == ']')
                    {
                        goto IL_0253;
                    }
                }
                else
                {
                    if (c == 'f')
                    {
                        goto IL_01D0;
                    }
                    if (c == 'n')
                    {
                        goto IL_0234;
                    }
                    if (c == 't')
                    {
                        goto IL_01D0;
                    }
                }
                IL_02B8:
                this._charPos++;
                if (!char.IsWhiteSpace(c))
                {
                    goto Block_24;
                }
            }
            base.SetToken(JsonToken.None, null, false);
            return null;
            IL_0165:
            this.ParseString(c, readType);
            return this.FinishReadQuotedStringValue(readType);
            IL_0175:
            if (this.EnsureChars(1, true) && this._chars[this._charPos + 1] == 'I')
            {
                return this.ParseNumberNegativeInfinity(readType);
            }
            this.ParseNumber(readType);
            return this.Value;
            IL_01A8:
            if (readType != ReadType.ReadAsString)
            {
                this._charPos++;
                throw this.CreateUnexpectedCharacterException(c);
            }
            this.ParseNumber(ReadType.ReadAsString);
            return this.Value;
            IL_01D0:
            if (readType != ReadType.ReadAsString)
            {
                this._charPos++;
                throw this.CreateUnexpectedCharacterException(c);
            }
            string text = ((c == 't') ? JsonConvert.True : JsonConvert.False);
            if (!this.MatchValueWithTrailingSeparator(text))
            {
                throw this.CreateUnexpectedCharacterException(this._chars[this._charPos]);
            }
            base.SetToken(JsonToken.String, text);
            return text;
            IL_0224:
            return this.ParseNumberPositiveInfinity(readType);
            IL_022C:
            return this.ParseNumberNaN(readType);
            IL_0234:
            this.HandleNull();
            return null;
            IL_0253:
            this._charPos++;
            if (this._currentState == JsonReader.State.Array || this._currentState == JsonReader.State.ArrayStart || this._currentState == JsonReader.State.PostValue)
            {
                base.SetToken(JsonToken.EndArray);
                return null;
            }
            throw this.CreateUnexpectedCharacterException(c);
            Block_24:
            throw this.CreateUnexpectedCharacterException(c);
            IL_02E1:
            throw JsonReaderException.Create(this, "Unexpected state: {0}.".FormatWith(CultureInfo.InvariantCulture, base.CurrentState));
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonReader._currentState, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonTextReader.EnsureBuffer(), Newtonsoft.Json.JsonTextReader.EnsureChars(), Newtonsoft.Json.JsonConvert.False, Newtonsoft.Json.JsonTextReader.FinishReadQuotedStringValue(), Newtonsoft.Json.JsonTextReader.HandleNull(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.MatchValueWithTrailingSeparator(), Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseNumber(), Newtonsoft.Json.JsonTextReader.ParseNumberNaN(), Newtonsoft.Json.JsonTextReader.ParseNumberNegativeInfinity(), Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseString(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), Newtonsoft.Json.JsonTextReader.ProcessValueComma(), Newtonsoft.Json.JsonTextReader.ReadFinished(), Newtonsoft.Json.JsonTextReader.ReadNullChar(), System.text, Newtonsoft.Json.JsonConvert.True, and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonTextReader.ReadAsDateTime(), Newtonsoft.Json.JsonTextReader.ReadAsDateTimeOffset(), and Newtonsoft.Json.JsonTextReader.ReadAsString().