Terraria Decompiled: Newtonsoft.Json.JsonTextReader.Close
Close()
override void Newtonsoft.Json.JsonTextReader.Close () inline virtual
Reimplemented from Newtonsoft.Json.JsonReader.
Definition at line 2711 of file JsonTextReader.cs.
        {
            base.Close();
            if (this._chars != null)
            {
                BufferUtils.ReturnBuffer(this._arrayPool, this._chars);
                this._chars = null;
            }
            if (base.CloseInput)
            {
                TextReader reader = this._reader;
                if (reader != null)
                {
                    reader.Close();
                }
            }
            this._stringBuffer.Clear(this._arrayPool);
        }
References Newtonsoft.Json.JsonTextReader._arrayPool, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._reader, Newtonsoft.Json.JsonTextReader._stringBuffer, Newtonsoft.Json.Utilities.StringBuffer.Clear(), System.IO.TextReader.Close(), and Newtonsoft.Json.Utilities.BufferUtils.ReturnBuffer().