Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseObject
ParseObject()
bool Newtonsoft.Json.JsonTextReader.ParseObject () inline private
Definition at line 1635 of file JsonTextReader.cs.
        {
            for (;;)
            {
                char c = this._chars[this._charPos];
                if (c <= '\r')
                {
                    if (c != '\0')
                    {
                        switch (c)
{
                        case '\t':
                            break;
                        case '\n':
                            this.ProcessLineFeed();
                            continue;
                        case '\v':
                        case '\f':
                            goto IL_00BD;
                        case '\r':
                            this.ProcessCarriageReturn(false);
                            continue;
                        default:
                            goto IL_00BD;
                        }
                    }
                    else
                    {
                        if (this._charsUsed != this._charPos)
{
                            this._charPos++;
                            continue;
                        }
                        if (this.ReadData(false) == 0)
{
                            break;
                        }
                        continue;
                    }
                }
                else if (c != ' ')
                {
                    if (c == '/')
                    {
                        goto IL_008A;
                    }
                    if (c != '}')
                    {
                        goto IL_00BD;
                    }
                    goto IL_0072;
                }
                this._charPos++;
                continue;
                IL_00BD:
                if (!char.IsWhiteSpace(c))
                {
                    goto IL_00D8;
                }
                this._charPos++;
            }
            return false;
            IL_0072:
            base.SetToken(JsonToken.EndObject);
            this._charPos++;
            return true;
            IL_008A:
            this.ParseComment(true);
            return true;
            IL_00D8:
            return this.ParseProperty();
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseProperty(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), and Newtonsoft.Json.JsonTextReader.ReadData().
Referenced by Newtonsoft.Json.JsonTextReader.Read().