Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ReadNumberValue
ReadNumberValue()
object Newtonsoft.Json.JsonTextReader.ReadNumberValue (ReadType readType) inline private
Definition at line 919 of file JsonTextReader.cs.
        {
            this.EnsureBuffer();
            switch (this._currentState)
            {
            case JsonReader.State.Start:
            case JsonReader.State.Property:
            case JsonReader.State.ArrayStart:
            case JsonReader.State.Array:
            case JsonReader.State.ConstructorStart:
            case JsonReader.State.Constructor:
                break;
            case JsonReader.State.Complete:
            case JsonReader.State.ObjectStart:
            case JsonReader.State.Object:
            case JsonReader.State.Closed:
            case JsonReader.State.Error:
                goto IL_0250;
            case JsonReader.State.PostValue:
                if (this.ParsePostValue(true))
                {
                    return null;
                }
                break;
            case JsonReader.State.Finished:
                this.ReadFinished();
                return null;
            default:
                goto IL_0250;
            }
            char c;
            for (;;)
            {
                c = this._chars[this._charPos];
                if (c <= '9')
                {
                    if (c != '\0')
                    {
                        switch (c)
{
                        case '\t':
                            break;
                        case '\n':
                            this.ProcessLineFeed();
                            continue;
                        case '\v':
                        case '\f':
                            goto IL_0227;
                        case '\r':
                            this.ProcessCarriageReturn(false);
                            continue;
                        default:
                            switch (c)
{
                            case ' ':
                                break;
                            case '!':
                            case '#':
                            case '$':
                            case '%':
                            case '&':
                            case '(':
                            case ')':
                            case '*':
                            case '+':
                                goto IL_0227;
                            case '"':
                            case '\'':
                                goto IL_0142;
                            case ',':
                                this.ProcessValueComma();
                                continue;
                            case '-':
                                goto IL_016A;
                            case '.':
                            case '0':
                            case '1':
                            case '2':
                            case '3':
                            case '4':
                            case '5':
                            case '6':
                            case '7':
                            case '8':
                            case '9':
                                goto IL_019D;
                            case '/':
                                this.ParseComment(false);
                                continue;
                            default:
                                goto IL_0227;
                            }
                            break;
                        }
                        this._charPos++;
                        continue;
                    }
                    if (this.ReadNullChar())
                    {
                        break;
                    }
                    continue;
                }
                else if (c <= 'N')
                {
                    if (c == 'I')
                    {
                        goto IL_0162;
                    }
                    if (c == 'N')
                    {
                        goto IL_015A;
                    }
                }
                else
                {
                    if (c == ']')
                    {
                        goto IL_01C2;
                    }
                    if (c == 'n')
                    {
                        goto IL_0152;
                    }
                }
                IL_0227:
                this._charPos++;
                if (!char.IsWhiteSpace(c))
                {
                    goto Block_17;
                }
            }
            base.SetToken(JsonToken.None, null, false);
            return null;
            IL_0142:
            this.ParseString(c, readType);
            return this.FinishReadQuotedNumber(readType);
            IL_0152:
            this.HandleNull();
            return null;
            IL_015A:
            return this.ParseNumberNaN(readType);
            IL_0162:
            return this.ParseNumberPositiveInfinity(readType);
            IL_016A:
            if (this.EnsureChars(1, true) && this._chars[this._charPos + 1] == 'I')
            {
                return this.ParseNumberNegativeInfinity(readType);
            }
            this.ParseNumber(readType);
            return this.Value;
            IL_019D:
            this.ParseNumber(readType);
            return this.Value;
            IL_01C2:
            this._charPos++;
            if (this._currentState == JsonReader.State.Array || this._currentState == JsonReader.State.ArrayStart || this._currentState == JsonReader.State.PostValue)
            {
                base.SetToken(JsonToken.EndArray);
                return null;
            }
            throw this.CreateUnexpectedCharacterException(c);
            Block_17:
            throw this.CreateUnexpectedCharacterException(c);
            IL_0250:
            throw JsonReaderException.Create(this, "Unexpected state: {0}.".FormatWith(CultureInfo.InvariantCulture, base.CurrentState));
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonReader._currentState, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonTextReader.EnsureBuffer(), Newtonsoft.Json.JsonTextReader.EnsureChars(), Newtonsoft.Json.JsonTextReader.FinishReadQuotedNumber(), Newtonsoft.Json.JsonTextReader.HandleNull(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseNumber(), Newtonsoft.Json.JsonTextReader.ParseNumberNaN(), Newtonsoft.Json.JsonTextReader.ParseNumberNegativeInfinity(), Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseString(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), Newtonsoft.Json.JsonTextReader.ProcessValueComma(), Newtonsoft.Json.JsonTextReader.ReadFinished(), Newtonsoft.Json.JsonTextReader.ReadNullChar(), and Newtonsoft.Json.JsonReader.Value.
Referenced by Newtonsoft.Json.JsonTextReader.ReadAsDecimal(), Newtonsoft.Json.JsonTextReader.ReadAsDouble(), and Newtonsoft.Json.JsonTextReader.ReadAsInt32().