Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseValue
ParseValue()
bool Newtonsoft.Json.JsonTextReader.ParseValue () inline private
Definition at line 1806 of file JsonTextReader.cs.
        {
            char c;
            for (;;)
            {
                c = this._chars[this._charPos];
                if (c <= 'N')
                {
                    if (c <= ' ')
                    {
                        if (c != '\0')
{
                            switch (c)
{
                            case '\t':
                                break;
                            case '\n':
                                this.ProcessLineFeed();
                                continue;
                            case '\v':
                            case '\f':
                                goto IL_0276;
                            case '\r':
                                this.ProcessCarriageReturn(false);
                                continue;
                            default:
                                if (c != ' ')
{
                                    goto IL_0276;
                                }
                                break;
                            }
                            this._charPos++;
                            continue;
                        }
                        if (this._charsUsed != this._charPos)
{
                            this._charPos++;
                            continue;
                        }
                        if (this.ReadData(false) == 0)
{
                            break;
                        }
                        continue;
                    }
                    else if (c <= '/')
                    {
                        if (c == '"')
{
                            goto IL_0116;
                        }
                        switch (c)
{
                        case '\'':
                            goto IL_0116;
                        case ')':
                            goto IL_0234;
                        case ',':
                            goto IL_022A;
                        case '-':
                            goto IL_01A3;
                        case '/':
                            goto IL_01D3;
                        }
                    }
                    else
                    {
                        if (c == 'I')
{
                            goto IL_0199;
                        }
                        if (c == 'N')
{
                            goto IL_018F;
                        }
                    }
                }
                else if (c <= 'f')
                {
                    if (c == '[')
                    {
                        goto IL_01FB;
                    }
                    if (c == ']')
                    {
                        goto IL_0212;
                    }
                    if (c == 'f')
                    {
                        goto IL_0128;
                    }
                }
                else if (c <= 't')
                {
                    if (c == 'n')
                    {
                        goto IL_0130;
                    }
                    if (c == 't')
                    {
                        goto IL_0120;
                    }
                }
                else
                {
                    if (c == 'u')
                    {
                        goto IL_01DC;
                    }
                    if (c == '{')
                    {
                        goto IL_01E4;
                    }
                }
                IL_0276:
                if (!char.IsWhiteSpace(c))
                {
                    goto IL_0291;
                }
                this._charPos++;
            }
            return false;
            IL_0116:
            this.ParseString(c, ReadType.Read);
            return true;
            IL_0120:
            this.ParseTrue();
            return true;
            IL_0128:
            this.ParseFalse();
            return true;
            IL_0130:
            if (this.EnsureChars(1, true))
            {
                char c2 = this._chars[this._charPos + 1];
                if (c2 == 'u')
                {
                    this.ParseNull();
                }
                else
                {
                    if (c2 != 'e')
                    {
                        throw this.CreateUnexpectedCharacterException(this._chars[this._charPos]);
                    }
                    this.ParseConstructor();
                }
                return true;
            }
            this._charPos++;
            throw base.CreateUnexpectedEndException();
            IL_018F:
            this.ParseNumberNaN(ReadType.Read);
            return true;
            IL_0199:
            this.ParseNumberPositiveInfinity(ReadType.Read);
            return true;
            IL_01A3:
            if (this.EnsureChars(1, true) && this._chars[this._charPos + 1] == 'I')
            {
                this.ParseNumberNegativeInfinity(ReadType.Read);
            }
            else
            {
                this.ParseNumber(ReadType.Read);
            }
            return true;
            IL_01D3:
            this.ParseComment(true);
            return true;
            IL_01DC:
            this.ParseUndefined();
            return true;
            IL_01E4:
            this._charPos++;
            base.SetToken(JsonToken.StartObject);
            return true;
            IL_01FB:
            this._charPos++;
            base.SetToken(JsonToken.StartArray);
            return true;
            IL_0212:
            this._charPos++;
            base.SetToken(JsonToken.EndArray);
            return true;
            IL_022A:
            base.SetToken(JsonToken.Undefined);
            return true;
            IL_0234:
            this._charPos++;
            base.SetToken(JsonToken.EndConstructor);
            return true;
            IL_0291:
            if (char.IsNumber(c) || c == '-' || c == '.')
            {
                this.ParseNumber(ReadType.Read);
                return true;
            }
            throw this.CreateUnexpectedCharacterException(c);
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonTextReader.EnsureChars(), Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseConstructor(), Newtonsoft.Json.JsonTextReader.ParseFalse(), Newtonsoft.Json.JsonTextReader.ParseNull(), Newtonsoft.Json.JsonTextReader.ParseNumber(), Newtonsoft.Json.JsonTextReader.ParseNumberNaN(), Newtonsoft.Json.JsonTextReader.ParseNumberNegativeInfinity(), Newtonsoft.Json.JsonTextReader.ParseNumberPositiveInfinity(), Newtonsoft.Json.JsonTextReader.ParseString(), Newtonsoft.Json.JsonTextReader.ParseTrue(), Newtonsoft.Json.JsonTextReader.ParseUndefined(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), and Newtonsoft.Json.JsonTextReader.ReadData().
Referenced by Newtonsoft.Json.JsonTextReader.Read().