Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ReadAsBoolean
ReadAsBoolean()
override? bool Newtonsoft.Json.JsonTextReader.ReadAsBoolean () inline virtual
Reimplemented from Newtonsoft.Json.JsonReader.
Definition at line 729 of file JsonTextReader.cs.
        {
            this.EnsureBuffer();
            switch (this._currentState)
            {
            case JsonReader.State.Start:
            case JsonReader.State.Property:
            case JsonReader.State.ArrayStart:
            case JsonReader.State.Array:
            case JsonReader.State.ConstructorStart:
            case JsonReader.State.Constructor:
                break;
            case JsonReader.State.Complete:
            case JsonReader.State.ObjectStart:
            case JsonReader.State.Object:
            case JsonReader.State.Closed:
            case JsonReader.State.Error:
                goto IL_02DB;
            case JsonReader.State.PostValue:
                if (this.ParsePostValue(true))
                {
                    return default(bool?);
                }
                break;
            case JsonReader.State.Finished:
                this.ReadFinished();
                return default(bool?);
            default:
                goto IL_02DB;
            }
            char c;
            for (;;)
            {
                c = this._chars[this._charPos];
                if (c <= '9')
                {
                    if (c != '\0')
                    {
                        switch (c)
{
                        case '\t':
                            break;
                        case '\n':
                            this.ProcessLineFeed();
                            continue;
                        case '\v':
                        case '\f':
                            goto IL_02AA;
                        case '\r':
                            this.ProcessCarriageReturn(false);
                            continue;
                        default:
                            switch (c)
{
                            case ' ':
                                break;
                            case '!':
                            case '#':
                            case '$':
                            case '%':
                            case '&':
                            case '(':
                            case ')':
                            case '*':
                            case '+':
                                goto IL_02AA;
                            case '"':
                            case '\'':
                                goto IL_0158;
                            case ',':
                                this.ProcessValueComma();
                                continue;
                            case '-':
                            case '.':
                            case '0':
                            case '1':
                            case '2':
                            case '3':
                            case '4':
                            case '5':
                            case '6':
                            case '7':
                            case '8':
                            case '9':
                                goto IL_0188;
                            case '/':
                                this.ParseComment(false);
                                continue;
                            default:
                                goto IL_02AA;
                            }
                            break;
                        }
                        this._charPos++;
                        continue;
                    }
                    if (this.ReadNullChar())
                    {
                        break;
                    }
                    continue;
                }
                else if (c <= 'f')
                {
                    if (c == ']')
                    {
                        goto IL_023D;
                    }
                    if (c == 'f')
                    {
                        goto IL_01D8;
                    }
                }
                else
                {
                    if (c == 'n')
                    {
                        goto IL_0178;
                    }
                    if (c == 't')
                    {
                        goto IL_01D8;
                    }
                }
                IL_02AA:
                this._charPos++;
                if (!char.IsWhiteSpace(c))
                {
                    goto Block_18;
                }
            }
            base.SetToken(JsonToken.None, null, false);
            return default(bool?);
            IL_0158:
            this.ParseString(c, ReadType.Read);
            return base.ReadBooleanString(this._stringReference.ToString());
            IL_0178:
            this.HandleNull();
            return default(bool?);
            IL_0188:
            this.ParseNumber(ReadType.Read);
            bool flag;
            if (this.Value is BigInteger)
            {
                flag = (BigInteger)this.Value != 0L;
            }
            else
            {
                flag = Convert.ToBoolean(this.Value, CultureInfo.InvariantCulture);
            }
            base.SetToken(JsonToken.Boolean, flag, false);
            return new bool?(flag);
            IL_01D8:
            bool flag2 = c == 't';
            string text = (flag2 ? JsonConvert.True : JsonConvert.False);
            if (!this.MatchValueWithTrailingSeparator(text))
            {
                throw this.CreateUnexpectedCharacterException(this._chars[this._charPos]);
            }
            base.SetToken(JsonToken.Boolean, flag2);
            return new bool?(flag2);
            IL_023D:
            this._charPos++;
            if (this._currentState == JsonReader.State.Array || this._currentState == JsonReader.State.ArrayStart || this._currentState == JsonReader.State.PostValue)
            {
                base.SetToken(JsonToken.EndArray);
                return default(bool?);
            }
            throw this.CreateUnexpectedCharacterException(c);
            Block_18:
            throw this.CreateUnexpectedCharacterException(c);
            IL_02DB:
            throw JsonReaderException.Create(this, "Unexpected state: {0}.".FormatWith(CultureInfo.InvariantCulture, base.CurrentState));
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonReader._currentState, Newtonsoft.Json.JsonTextReader._stringReference, Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonTextReader.EnsureBuffer(), Newtonsoft.Json.JsonConvert.False, Newtonsoft.Json.JsonTextReader.HandleNull(), System.Globalization.CultureInfo.InvariantCulture, System.L, Newtonsoft.Json.JsonTextReader.MatchValueWithTrailingSeparator(), Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseNumber(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseString(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), Newtonsoft.Json.JsonTextReader.ProcessValueComma(), Newtonsoft.Json.JsonTextReader.ReadFinished(), Newtonsoft.Json.JsonTextReader.ReadNullChar(), System.text, System.Convert.ToBoolean(), Newtonsoft.Json.Utilities.StringReference.ToString(), and Newtonsoft.Json.JsonReader.Value.