Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseProperty
ParseProperty()
bool Newtonsoft.Json.JsonTextReader.ParseProperty () inline private
Definition at line 1709 of file JsonTextReader.cs.
        {
            char c = this._chars[this._charPos];
            char c2;
            if (c == '"' || c == '\'')
            {
                this._charPos++;
                c2 = c;
                this.ShiftBufferIfNeeded();
                this.ReadStringIntoBuffer(c2);
            }
            else
            {
                if (!this.ValidIdentifierChar(c))
                {
                    throw JsonReaderException.Create(this, "Invalid property identifier character: {0}.".FormatWith(CultureInfo.InvariantCulture, this._chars[this._charPos]));
                }
                c2 = '\0';
                this.ShiftBufferIfNeeded();
                this.ParseUnquotedProperty();
            }
            string text;
            if (this.NameTable != null)
            {
                text = this.NameTable.Get(this._stringReference.Chars, this._stringReference.StartIndex, this._stringReference.Length);
                if (text == null)
                {
                    text = this._stringReference.ToString();
                }
            }
            else
            {
                text = this._stringReference.ToString();
            }
            this.EatWhitespace();
            if (this._chars[this._charPos] != ':')
            {
                throw JsonReaderException.Create(this, "Invalid character after parsing property name. Expected ':' but got: {0}.".FormatWith(CultureInfo.InvariantCulture, this._chars[this._charPos]));
            }
            this._charPos++;
            base.SetToken(JsonToken.PropertyName, text);
            this._quoteChar = c2;
            this.ClearRecentString();
            return true;
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._stringReference, Newtonsoft.Json.Utilities.StringReference.Chars, Newtonsoft.Json.JsonTextReader.ClearRecentString(), Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.EatWhitespace(), Newtonsoft.Json.Utilities.PropertyNameTable.Get(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.NameTable, Newtonsoft.Json.JsonTextReader.ParseUnquotedProperty(), Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(), Newtonsoft.Json.JsonTextReader.ShiftBufferIfNeeded(), System.text, Newtonsoft.Json.Utilities.StringReference.ToString(), and Newtonsoft.Json.JsonTextReader.ValidIdentifierChar().
Referenced by Newtonsoft.Json.JsonTextReader.ParseObject().