Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseComment
ParseComment()
void Newtonsoft.Json.JsonTextReader.ParseComment (bool setToken) inline private
Definition at line 2370 of file JsonTextReader.cs.
        {
            this._charPos++;
            if (!this.EnsureChars(1, false))
            {
                throw JsonReaderException.Create(this, "Unexpected end while parsing comment.");
            }
            bool flag;
            if (this._chars[this._charPos] == '*')
            {
                flag = false;
            }
            else
            {
                if (this._chars[this._charPos] != '/')
                {
                    throw JsonReaderException.Create(this, "Error parsing comment. Expected: *, got {0}.".FormatWith(CultureInfo.InvariantCulture, this._chars[this._charPos]));
                }
                flag = true;
            }
            this._charPos++;
            int charPos = this._charPos;
            for (;;)
            {
                char c = this._chars[this._charPos];
                if (c <= '\n')
                {
                    if (c != '\0')
                    {
                        if (c == '\n')
{
                            if (flag)
{
                                goto Block_16;
                            }
                            this.ProcessLineFeed();
                            continue;
                        }
                    }
                    else
                    {
                        if (this._charsUsed != this._charPos)
{
                            this._charPos++;
                            continue;
                        }
                        if (this.ReadData(true) == 0)
{
                            break;
                        }
                        continue;
                    }
                }
                else if (c != '\r')
                {
                    if (c == '*')
                    {
                        this._charPos++;
                        if (!flag && this.EnsureChars(0, true) && this._chars[this._charPos] == '/')
{
                            goto Block_14;
                        }
                        continue;
                    }
                }
                else
                {
                    if (flag)
                    {
                        goto Block_15;
                    }
                    this.ProcessCarriageReturn(true);
                    continue;
                }
                this._charPos++;
            }
            if (!flag)
            {
                throw JsonReaderException.Create(this, "Unexpected end while parsing comment.");
            }
            this.EndComment(setToken, charPos, this._charPos);
            return;
            Block_14:
            this.EndComment(setToken, charPos, this._charPos - 1);
            this._charPos++;
            return;
            Block_15:
            this.EndComment(setToken, charPos, this._charPos);
            return;
            Block_16:
            this.EndComment(setToken, charPos, this._charPos);
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.EndComment(), Newtonsoft.Json.JsonTextReader.EnsureChars(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), and Newtonsoft.Json.JsonTextReader.ReadData().
Referenced by Newtonsoft.Json.JsonTextReader.ParseObject(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseValue(), Newtonsoft.Json.JsonTextReader.Read(), Newtonsoft.Json.JsonTextReader.ReadAsBoolean(), Newtonsoft.Json.JsonTextReader.ReadAsBytes(), Newtonsoft.Json.JsonTextReader.ReadFinished(), Newtonsoft.Json.JsonTextReader.ReadNumberValue(), and Newtonsoft.Json.JsonTextReader.ReadStringValue().