Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseReadNumber
ParseReadNumber()
void Newtonsoft.Json.JsonTextReader.ParseReadNumber (ReadType readType, char firstChar, int initialPosition) inline private
Definition at line 2150 of file JsonTextReader.cs.
        {
            base.SetPostValueState(true);
            this._stringReference = new StringReference(this._chars, initialPosition, this._charPos - initialPosition);
            bool flag = char.IsDigit(firstChar) && this._stringReference.Length == 1;
            bool flag2 = firstChar == '0' && this._stringReference.Length > 1 && this._stringReference.Chars[this._stringReference.StartIndex + 1] != '.' && this._stringReference.Chars[this._stringReference.StartIndex + 1] != 'e' && this._stringReference.Chars[this._stringReference.StartIndex + 1] != 'E';
            JsonToken jsonToken;
            object obj;
            if (readType == ReadType.ReadAsString)
            {
                string text = this._stringReference.ToString();
                if (flag2)
                {
                    try
                    {
                        if (text.StartsWith("0x", 5))
{
                            Convert.ToInt64(text, 16);
                        }
                        else
{
                            Convert.ToInt64(text, 8);
                        }
                        goto IL_0148;
                    }
                    catch (Exception ex)
                    {
                        throw this.ThrowReaderError("Input string '{0}' is not a valid number.".FormatWith(CultureInfo.InvariantCulture, text), ex);
                    }
                }
                double num;
                if (!double.TryParse(text, 167, CultureInfo.InvariantCulture, ref num))
                {
                    throw this.ThrowReaderError("Input string '{0}' is not a valid number.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                }
                IL_0148:
                jsonToken = JsonToken.String;
                obj = text;
            }
            else if (readType == ReadType.ReadAsInt32)
            {
                if (flag)
                {
                    obj = (int)(firstChar - '0');
                }
                else
                {
                    if (flag2)
                    {
                        string text2 = this._stringReference.ToString();
                        try
{
                            obj = (text2.StartsWith("0x", 5) ? Convert.ToInt32(text2, 16) : Convert.ToInt32(text2, 8));
                            goto IL_0259;
                        }
                        catch (Exception ex2)
{
                            throw this.ThrowReaderError("Input string '{0}' is not a valid integer.".FormatWith(CultureInfo.InvariantCulture, text2), ex2);
                        }
                    }
                    int num2;
                    ParseResult parseResult = ConvertUtils.Int32TryParse(this._stringReference.Chars, this._stringReference.StartIndex, this._stringReference.Length, out num2);
                    if (parseResult == ParseResult.Success)
                    {
                        obj = num2;
                    }
                    else
                    {
                        if (parseResult == ParseResult.Overflow)
{
                            throw this.ThrowReaderError("JSON integer {0} is too large or small for an Int32.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                        }
                        throw this.ThrowReaderError("Input string '{0}' is not a valid integer.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                    }
                }
                IL_0259:
                jsonToken = JsonToken.Integer;
            }
            else if (readType == ReadType.ReadAsDecimal)
            {
                if (flag)
                {
                    obj = firstChar - 48m;
                }
                else
                {
                    if (flag2)
                    {
                        string text3 = this._stringReference.ToString();
                        try
{
                            obj = Convert.ToDecimal(text3.StartsWith("0x", 5) ? Convert.ToInt64(text3, 16) : Convert.ToInt64(text3, 8));
                            goto IL_0345;
                        }
                        catch (Exception ex3)
{
                            throw this.ThrowReaderError("Input string '{0}' is not a valid decimal.".FormatWith(CultureInfo.InvariantCulture, text3), ex3);
                        }
                    }
                    decimal num3;
                    if (ConvertUtils.DecimalTryParse(this._stringReference.Chars, this._stringReference.StartIndex, this._stringReference.Length, out num3) != ParseResult.Success)
                    {
                        throw this.ThrowReaderError("Input string '{0}' is not a valid decimal.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                    }
                    obj = num3;
                }
                IL_0345:
                jsonToken = JsonToken.Float;
            }
            else if (readType == ReadType.ReadAsDouble)
            {
                if (flag)
                {
                    obj = (double)firstChar - 48.0;
                }
                else
                {
                    if (flag2)
                    {
                        string text4 = this._stringReference.ToString();
                        try
{
                            obj = Convert.ToDouble(text4.StartsWith("0x", 5) ? Convert.ToInt64(text4, 16) : Convert.ToInt64(text4, 8));
                            goto IL_0424;
                        }
                        catch (Exception ex4)
{
                            throw this.ThrowReaderError("Input string '{0}' is not a valid double.".FormatWith(CultureInfo.InvariantCulture, text4), ex4);
                        }
                    }
                    double num4;
                    if (!double.TryParse(this._stringReference.ToString(), 167, CultureInfo.InvariantCulture, ref num4))
                    {
                        throw this.ThrowReaderError("Input string '{0}' is not a valid double.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                    }
                    obj = num4;
                }
                IL_0424:
                jsonToken = JsonToken.Float;
            }
            else if (flag)
            {
                obj = (long)((ulong)firstChar - 48UL);
                jsonToken = JsonToken.Integer;
            }
            else if (flag2)
            {
                string text5 = this._stringReference.ToString();
                try
                {
                    obj = (text5.StartsWith("0x", 5) ? Convert.ToInt64(text5, 16) : Convert.ToInt64(text5, 8));
                }
                catch (Exception ex5)
                {
                    throw this.ThrowReaderError("Input string '{0}' is not a valid number.".FormatWith(CultureInfo.InvariantCulture, text5), ex5);
                }
                jsonToken = JsonToken.Integer;
            }
            else
            {
                long num5;
                ParseResult parseResult2 = ConvertUtils.Int64TryParse(this._stringReference.Chars, this._stringReference.StartIndex, this._stringReference.Length, out num5);
                if (parseResult2 == ParseResult.Success)
                {
                    obj = num5;
                    jsonToken = JsonToken.Integer;
                }
                else if (parseResult2 == ParseResult.Overflow)
                {
                    string text6 = this._stringReference.ToString();
                    if (text6.Length > 380)
                    {
                        throw this.ThrowReaderError("JSON integer {0} is too large to parse.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                    }
                    obj = JsonTextReader.BigIntegerParse(text6, CultureInfo.InvariantCulture);
                    jsonToken = JsonToken.Integer;
                }
                else
                {
                    if (this._floatParseHandling == FloatParseHandling.Decimal)
                    {
                        decimal num6;
                        parseResult2 = ConvertUtils.DecimalTryParse(this._stringReference.Chars, this._stringReference.StartIndex, this._stringReference.Length, out num6);
                        if (parseResult2 != ParseResult.Success)
{
                            throw this.ThrowReaderError("Input string '{0}' is not a valid decimal.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                        }
                        obj = num6;
                    }
                    else
                    {
                        double num7;
                        if (!double.TryParse(this._stringReference.ToString(), 167, CultureInfo.InvariantCulture, ref num7))
{
                            throw this.ThrowReaderError("Input string '{0}' is not a valid number.".FormatWith(CultureInfo.InvariantCulture, this._stringReference.ToString()), null);
                        }
                        obj = num7;
                    }
                    jsonToken = JsonToken.Float;
                }
            }
            this.ClearRecentString();
            base.SetToken(jsonToken, obj, false);
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonReader._floatParseHandling, Newtonsoft.Json.JsonTextReader._stringReference, Newtonsoft.Json.JsonTextReader.BigIntegerParse(), Newtonsoft.Json.Utilities.StringReference.Chars, Newtonsoft.Json.JsonTextReader.ClearRecentString(), Newtonsoft.Json.Utilities.ConvertUtils.DecimalTryParse(), int, Newtonsoft.Json.Utilities.ConvertUtils.Int32TryParse(), Newtonsoft.Json.Utilities.ConvertUtils.Int64TryParse(), System.Globalization.CultureInfo.InvariantCulture, long, System.obj, System.text, Newtonsoft.Json.JsonTextReader.ThrowReaderError(), System.Convert.ToDecimal(), System.Convert.ToDouble(), System.Convert.ToInt32(), System.Convert.ToInt64(), System.Globalization.CultureInfo.ToString(), and Newtonsoft.Json.Utilities.StringReference.ToString().
Referenced by Newtonsoft.Json.JsonTextReader.ParseNumber().