Terraria Decompiled: Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData
PrepareBufferForReadData()
void Newtonsoft.Json.JsonTextReader.PrepareBufferForReadData (bool append, int charsRequired) inline private
Definition at line 181 of file JsonTextReader.cs.
        {
            if (this._charsUsed + charsRequired >= this._chars.Length - 1)
            {
                if (append)
                {
                    int num = Math.Max(this._chars.Length * 2, this._charsUsed + charsRequired + 1);
                    char[] array = BufferUtils.RentBuffer(this._arrayPool, num);
                    JsonTextReader.BlockCopyChars(this._chars, 0, array, 0, this._chars.Length);
                    BufferUtils.ReturnBuffer(this._arrayPool, this._chars);
                    this._chars = array;
                    return;
                }
                int num2 = this._charsUsed - this._charPos;
                if (num2 + charsRequired + 1 >= this._chars.Length)
                {
                    char[] array2 = BufferUtils.RentBuffer(this._arrayPool, num2 + charsRequired + 1);
                    if (num2 > 0)
                    {
                        JsonTextReader.BlockCopyChars(this._chars, this._charPos, array2, 0, num2);
                    }
                    BufferUtils.ReturnBuffer(this._arrayPool, this._chars);
                    this._chars = array2;
                }
                else if (num2 > 0)
                {
                    JsonTextReader.BlockCopyChars(this._chars, this._charPos, this._chars, 0, num2);
                }
                this._lineStartPos -= this._charPos;
                this._charPos = 0;
                this._charsUsed = num2;
            }
        }
References Newtonsoft.Json.JsonTextReader._arrayPool, Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, System.array, Newtonsoft.Json.JsonTextReader.BlockCopyChars(), System.Math.Max(), Newtonsoft.Json.Utilities.BufferUtils.RentBuffer(), and Newtonsoft.Json.Utilities.BufferUtils.ReturnBuffer().
Referenced by Newtonsoft.Json.JsonTextReader.ReadData().