Terraria Decompiled: Newtonsoft.Json.JsonTextReader.EatWhitespace
EatWhitespace()
void Newtonsoft.Json.JsonTextReader.EatWhitespace () inline private
Definition at line 2023 of file JsonTextReader.cs.
        {
            for (;;)
            {
                char c = this._chars[this._charPos];
                if (c != '\0')
                {
                    if (c != '\n')
                    {
                        if (c != '\r')
{
                            if (c != ' ' && !char.IsWhiteSpace(c))
{
                                return;
                            }
                            this._charPos++;
                        }
                        else
{
                            this.ProcessCarriageReturn(false);
                        }
                    }
                    else
                    {
                        this.ProcessLineFeed();
                    }
                }
                else if (this._charsUsed == this._charPos)
                {
                    if (this.ReadData(false) == 0)
                    {
                        break;
                    }
                }
                else
                {
                    this._charPos++;
                }
            }
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), and Newtonsoft.Json.JsonTextReader.ReadData().
Referenced by Newtonsoft.Json.JsonTextReader.ParseConstructor(), Newtonsoft.Json.JsonTextReader.ParseProperty(), Newtonsoft.Json.JsonTextReader.Read(), and Newtonsoft.Json.JsonTextReader.ReadFinished().