Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ReadAsBytes
ReadAsBytes()
override byte[] Newtonsoft.Json.JsonTextReader.ReadAsBytes () inline virtual
Reimplemented from Newtonsoft.Json.JsonReader.
Definition at line 337 of file JsonTextReader.cs.
        {
            this.EnsureBuffer();
            bool flag = false;
            switch (this._currentState)
            {
            case JsonReader.State.Start:
            case JsonReader.State.Property:
            case JsonReader.State.ArrayStart:
            case JsonReader.State.Array:
            case JsonReader.State.ConstructorStart:
            case JsonReader.State.Constructor:
                break;
            case JsonReader.State.Complete:
            case JsonReader.State.ObjectStart:
            case JsonReader.State.Object:
            case JsonReader.State.Closed:
            case JsonReader.State.Error:
                goto IL_023E;
            case JsonReader.State.PostValue:
                if (this.ParsePostValue(true))
                {
                    return null;
                }
                break;
            case JsonReader.State.Finished:
                this.ReadFinished();
                return null;
            default:
                goto IL_023E;
            }
            char c;
            for (;;)
            {
                c = this._chars[this._charPos];
                if (c <= '\'')
                {
                    if (c <= '\r')
                    {
                        if (c != '\0')
{
                            switch (c)
{
                            case '\t':
                                break;
                            case '\n':
                                this.ProcessLineFeed();
                                continue;
                            case '\v':
                            case '\f':
                                goto IL_0215;
                            case '\r':
                                this.ProcessCarriageReturn(false);
                                continue;
                            default:
                                goto IL_0215;
                            }
                        }
                        else
{
                            if (this.ReadNullChar())
{
                                break;
                            }
                            continue;
                        }
                    }
                    else if (c != ' ')
                    {
                        if (c != '"' && c != '\'')
{
                            goto IL_0215;
                        }
                        goto IL_00FF;
                    }
                    this._charPos++;
                    continue;
                }
                if (c <= '[')
                {
                    if (c == ',')
                    {
                        this.ProcessValueComma();
                        continue;
                    }
                    if (c == '/')
                    {
                        this.ParseComment(false);
                        continue;
                    }
                    if (c == '[')
                    {
                        goto IL_0175;
                    }
                }
                else
                {
                    if (c == ']')
                    {
                        goto IL_01B0;
                    }
                    if (c == 'n')
                    {
                        goto IL_0191;
                    }
                    if (c == '{')
                    {
                        this._charPos++;
                        base.SetToken(JsonToken.StartObject);
                        base.ReadIntoWrappedTypeObject();
                        flag = true;
                        continue;
                    }
                }
                IL_0215:
                this._charPos++;
                if (!char.IsWhiteSpace(c))
                {
                    goto Block_22;
                }
            }
            base.SetToken(JsonToken.None, null, false);
            return null;
            IL_00FF:
            this.ParseString(c, ReadType.ReadAsBytes);
            byte[] array = (byte[])this.Value;
            if (flag)
            {
                base.ReaderReadAndAssert();
                if (this.TokenType != JsonToken.EndObject)
                {
                    throw JsonReaderException.Create(this, "Error reading bytes. Unexpected token: {0}.".FormatWith(CultureInfo.InvariantCulture, this.TokenType));
                }
                base.SetToken(JsonToken.Bytes, array, false);
            }
            return array;
            IL_0175:
            this._charPos++;
            base.SetToken(JsonToken.StartArray);
            return base.ReadArrayIntoByteArray();
            IL_0191:
            this.HandleNull();
            return null;
            IL_01B0:
            this._charPos++;
            if (this._currentState == JsonReader.State.Array || this._currentState == JsonReader.State.ArrayStart || this._currentState == JsonReader.State.PostValue)
            {
                base.SetToken(JsonToken.EndArray);
                return null;
            }
            throw this.CreateUnexpectedCharacterException(c);
            Block_22:
            throw this.CreateUnexpectedCharacterException(c);
            IL_023E:
            throw JsonReaderException.Create(this, "Unexpected state: {0}.".FormatWith(CultureInfo.InvariantCulture, base.CurrentState));
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonReader._currentState, System.array, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonTextReader.EnsureBuffer(), Newtonsoft.Json.JsonTextReader.HandleNull(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseString(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), Newtonsoft.Json.JsonTextReader.ProcessValueComma(), Newtonsoft.Json.JsonTextReader.ReadFinished(), Newtonsoft.Json.JsonTextReader.ReadNullChar(), and Newtonsoft.Json.JsonReader.Value.