Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseConstructor
ParseConstructor()
void Newtonsoft.Json.JsonTextReader.ParseConstructor () inline private
Definition at line 2065 of file JsonTextReader.cs.
        {
            if (!this.MatchValueWithTrailingSeparator("new"))
            {
                throw JsonReaderException.Create(this, "Unexpected content while parsing JSON.");
            }
            this.EatWhitespace();
            int charPos = this._charPos;
            char c;
            for (;;)
            {
                c = this._chars[this._charPos];
                if (c == '\0')
                {
                    if (this._charsUsed != this._charPos)
                    {
                        goto IL_0051;
                    }
                    if (this.ReadData(true) == 0)
                    {
                        break;
                    }
                }
                else
                {
                    if (!char.IsLetterOrDigit(c))
                    {
                        goto IL_0083;
                    }
                    this._charPos++;
                }
            }
            throw JsonReaderException.Create(this, "Unexpected end while parsing constructor.");
            IL_0051:
            int num = this._charPos;
            this._charPos++;
            goto IL_00F5;
            IL_0083:
            if (c == '\r')
            {
                num = this._charPos;
                this.ProcessCarriageReturn(true);
            }
            else if (c == '\n')
            {
                num = this._charPos;
                this.ProcessLineFeed();
            }
            else if (char.IsWhiteSpace(c))
            {
                num = this._charPos;
                this._charPos++;
            }
            else
            {
                if (c != '(')
                {
                    throw JsonReaderException.Create(this, "Unexpected character while parsing constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, c));
                }
                num = this._charPos;
            }
            IL_00F5:
            this._stringReference = new StringReference(this._chars, charPos, num - charPos);
            string text = this._stringReference.ToString();
            this.EatWhitespace();
            if (this._chars[this._charPos] != '(')
            {
                throw JsonReaderException.Create(this, "Unexpected character while parsing constructor: {0}.".FormatWith(CultureInfo.InvariantCulture, this._chars[this._charPos]));
            }
            this._charPos++;
            this.ClearRecentString();
            base.SetToken(JsonToken.StartConstructor, text);
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonTextReader._stringReference, Newtonsoft.Json.JsonTextReader.ClearRecentString(), Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonTextReader.EatWhitespace(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.JsonTextReader.MatchValueWithTrailingSeparator(), Newtonsoft.Json.JsonTextReader.ProcessCarriageReturn(), Newtonsoft.Json.JsonTextReader.ProcessLineFeed(), Newtonsoft.Json.JsonTextReader.ReadData(), System.text, and Newtonsoft.Json.Utilities.StringReference.ToString().
Referenced by Newtonsoft.Json.JsonTextReader.ParseValue().