Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ParseReadString
ParseReadString()
void Newtonsoft.Json.JsonTextReader.ParseReadString (char quote, ReadType readType) inline private
Definition at line 79 of file JsonTextReader.cs.
        {
            base.SetPostValueState(true);
            switch (readType)
            {
            case ReadType.ReadAsInt32:
            case ReadType.ReadAsDecimal:
            case ReadType.ReadAsBoolean:
                return;
            case ReadType.ReadAsBytes:
            {
                byte[] array;
                Guid guid;
                if (this._stringReference.Length == 0)
                {
                    array = CollectionUtils.ArrayEmpty<byte>();
                }
                else if (this._stringReference.Length == 36 && ConvertUtils.TryConvertGuid(this._stringReference.ToString(), out guid))
                {
                    array = guid.ToByteArray();
                }
                else
                {
                    array = Convert.FromBase64CharArray(this._stringReference.Chars, this._stringReference.StartIndex, this._stringReference.Length);
                }
                base.SetToken(JsonToken.Bytes, array, false);
                return;
            }
            case ReadType.ReadAsString:
            {
                string text = this._stringReference.ToString();
                base.SetToken(JsonToken.String, text, false);
                this._quoteChar = quote;
                return;
            }
            }
            if (this._dateParseHandling != DateParseHandling.None)
            {
                DateParseHandling dateParseHandling;
                if (readType == ReadType.ReadAsDateTime)
                {
                    dateParseHandling = DateParseHandling.DateTime;
                }
                else if (readType == ReadType.ReadAsDateTimeOffset)
                {
                    dateParseHandling = DateParseHandling.DateTimeOffset;
                }
                else
                {
                    dateParseHandling = this._dateParseHandling;
                }
                DateTimeOffset dateTimeOffset;
                if (dateParseHandling == DateParseHandling.DateTime)
                {
                    DateTime dateTime;
                    if (DateTimeUtils.TryParseDateTime(this._stringReference, base.DateTimeZoneHandling, base.DateFormatString, base.Culture, out dateTime))
                    {
                        base.SetToken(JsonToken.Date, dateTime, false);
                        return;
                    }
                }
                else if (DateTimeUtils.TryParseDateTimeOffset(this._stringReference, base.DateFormatString, base.Culture, out dateTimeOffset))
                {
                    base.SetToken(JsonToken.Date, dateTimeOffset, false);
                    return;
                }
            }
            base.SetToken(JsonToken.String, this._stringReference.ToString(), false);
            this._quoteChar = quote;
        }
References Newtonsoft.Json.JsonReader._dateParseHandling, Newtonsoft.Json.JsonTextReader._stringReference, System.array, Newtonsoft.Json.Utilities.StringReference.Chars, System.Convert.FromBase64CharArray(), Newtonsoft.Json.Utilities.StringReference.Length, System.text, System.Guid.ToByteArray(), Newtonsoft.Json.Utilities.StringReference.ToString(), Newtonsoft.Json.Utilities.ConvertUtils.TryConvertGuid(), Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTime(), and Newtonsoft.Json.Utilities.DateTimeUtils.TryParseDateTimeOffset().
Referenced by Newtonsoft.Json.JsonTextReader.ParseString().