Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ProcessLineFeed
ProcessLineFeed()
void Newtonsoft.Json.JsonTextReader.ProcessLineFeed () inline private
Definition at line 2009 of file JsonTextReader.cs.
        {
            this._charPos++;
            this.OnNewLine(this._charPos);
        }
References Newtonsoft.Json.JsonTextReader._charPos, and Newtonsoft.Json.JsonTextReader.OnNewLine().
Referenced by Newtonsoft.Json.JsonTextReader.EatWhitespace(), Newtonsoft.Json.JsonTextReader.ParseComment(), Newtonsoft.Json.JsonTextReader.ParseConstructor(), Newtonsoft.Json.JsonTextReader.ParseObject(), Newtonsoft.Json.JsonTextReader.ParsePostValue(), Newtonsoft.Json.JsonTextReader.ParseValue(), Newtonsoft.Json.JsonTextReader.ReadAsBoolean(), Newtonsoft.Json.JsonTextReader.ReadAsBytes(), Newtonsoft.Json.JsonTextReader.ReadNumberValue(), Newtonsoft.Json.JsonTextReader.ReadStringIntoBuffer(), and Newtonsoft.Json.JsonTextReader.ReadStringValue().