Terraria Decompiled: Newtonsoft.Json.JsonTextReader.HandleNull
HandleNull()
void Newtonsoft.Json.JsonTextReader.HandleNull () inline private
Definition at line 1124 of file JsonTextReader.cs.
        {
            if (!this.EnsureChars(1, true))
            {
                this._charPos = this._charsUsed;
                throw base.CreateUnexpectedEndException();
            }
            if (this._chars[this._charPos + 1] == 'u')
            {
                this.ParseNull();
                return;
            }
            this._charPos += 2;
            throw this.CreateUnexpectedCharacterException(this._chars[this._charPos - 1]);
        }
References Newtonsoft.Json.JsonTextReader._charPos, Newtonsoft.Json.JsonTextReader._chars, Newtonsoft.Json.JsonTextReader._charsUsed, Newtonsoft.Json.JsonTextReader.CreateUnexpectedCharacterException(), Newtonsoft.Json.JsonTextReader.EnsureChars(), and Newtonsoft.Json.JsonTextReader.ParseNull().
Referenced by Newtonsoft.Json.JsonTextReader.ReadAsBoolean(), Newtonsoft.Json.JsonTextReader.ReadAsBytes(), Newtonsoft.Json.JsonTextReader.ReadNumberValue(), and Newtonsoft.Json.JsonTextReader.ReadStringValue().