Terraria Decompiled: Newtonsoft.Json.JsonTextReader.ConvertUnicode
ConvertUnicode()
char Newtonsoft.Json.JsonTextReader.ConvertUnicode (bool enoughChars) inline private
Definition at line 1390 of file JsonTextReader.cs.
        {
            if (!enoughChars)
            {
                throw JsonReaderException.Create(this, "Unexpected end while parsing Unicode escape sequence.");
            }
            int num;
            if (ConvertUtils.TryHexTextToInt(this._chars, this._charPos, this._charPos + 4, out num))
            {
                char c = Convert.ToChar(num);
                this._charPos += 4;
                return c;
            }
            throw JsonReaderException.Create(this, "Invalid Unicode escape sequence: \\u{0}.".FormatWith(CultureInfo.InvariantCulture, new string(this._chars, this._charPos, 4)));
        }
References Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToChar(), and Newtonsoft.Json.Utilities.ConvertUtils.TryHexTextToInt().
Referenced by Newtonsoft.Json.JsonTextReader.ParseUnicode().