Terraria Decompiled: Steamworks.MMKVPMarshaller.MMKVPMarshaller
MMKVPMarshaller()
Steamworks.MMKVPMarshaller.MMKVPMarshaller (MatchMakingKeyValuePair_t[] filters) inline
Definition at line 10 of file MMKVPMarshaller.cs.
        {
            if (filters == null)
            {
                return;
            }
            int num = Marshal.SizeOf(typeof(MatchMakingKeyValuePair_t));
            this.m_pNativeArray = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(IntPtr)) * filters.Length);
            this.m_pArrayEntries = Marshal.AllocHGlobal(num * filters.Length);
            for (int i = 0; i < filters.Length; i++)
            {
                Marshal.StructureToPtr(filters[i], new IntPtr(this.m_pArrayEntries.ToInt64() + (long)(i * num)), false);
            }
            Marshal.WriteIntPtr(this.m_pNativeArray, this.m_pArrayEntries);
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), Steamworks.MMKVPMarshaller.m_pArrayEntries, Steamworks.MMKVPMarshaller.m_pNativeArray, System.Runtime.InteropServices.Marshal.SizeOf(), System.Runtime.InteropServices.Marshal.StructureToPtr(), System.IntPtr.ToInt64(), and System.Runtime.InteropServices.Marshal.WriteIntPtr().