Terraria Decompiled: ReLogic.Peripherals.RGB.ChromaEngine.Update
Update()
void ReLogic.Peripherals.RGB.ChromaEngine.Update (float totalTime) inline
Definition at line 237 of file ChromaEngine.cs.
        {
            if (this._deviceGroups.Count == 0)
            {
                return;
            }
            if (totalTime < this._lastTime)
            {
                this._lastTime = totalTime;
            }
            float num = totalTime - this._lastTime;
            if (num >= this.FrameTimeInSeconds && Monitor.TryEnter(this._updateLock))
            {
                try
                {
                    if (this.OnUpdate != null)
                    {
                        this.OnUpdate.Invoke(this, new ChromaEngineUpdateEventArgs(num));
                    }
                    this._hotkeys.UpdateAll(num);
                    this._shaderSelector.Update(num);
                    this._lastTime = totalTime;
                    ThreadPool.QueueUserWorkItem(delegate(object context)
                    {
                        ((ChromaEngine)context).Draw();
                    }, this);
                }
                catch
                {
                    this.DisableAllDeviceGroups();
                }
                finally
                {
                    Monitor.Exit(this._updateLock);
                }
            }
        }
References ReLogic.Peripherals.RGB.ChromaEngine._deviceGroups, ReLogic.Peripherals.RGB.ChromaEngine._hotkeys, ReLogic.Peripherals.RGB.ChromaEngine._lastTime, ReLogic.Peripherals.RGB.ChromaEngine._shaderSelector, ReLogic.Peripherals.RGB.ChromaEngine._updateLock, ReLogic.Peripherals.RGB.ChromaEngine.ChromaEngine(), ReLogic.Peripherals.RGB.ChromaEngine.DisableAllDeviceGroups(), System.Threading.Monitor.Exit(), ReLogic.Peripherals.RGB.ChromaEngine.FrameTimeInSeconds, ReLogic.Peripherals.RGB.ChromaEngine.OnUpdate, System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.Monitor.TryEnter(), ReLogic.Peripherals.RGB.ShaderSelector.Update(), and ReLogic.Peripherals.RGB.HotkeyCollection.UpdateAll().
Referenced by Terraria.Main.DoUpdate().