Terraria Decompiled: ReLogic.Peripherals.RGB.ChromaEngine.Draw
Draw()
void ReLogic.Peripherals.RGB.ChromaEngine.Draw () inline private
Definition at line 276 of file ChromaEngine.cs.
        {
            object updateLock = this._updateLock;
            lock (updateLock)
            {
                try
                {
                    for (int i = 0; i <= 1; i++)
                    {
                        EffectDetailLevel detail = (EffectDetailLevel)i;
                        ICollection<ShaderOperation> collection = this._shaderSelector.AtDetailLevel(detail);
                        Func<RgbDevice, bool> <>9__0;
                        foreach (RgbDeviceGroup rgbDeviceGroup in this._deviceGroups.Values)
{
                            ChromaPipeline pipeline = this._pipeline;
                            IEnumerable<RgbDevice> enumerable = rgbDeviceGroup;
                            Func<RgbDevice, bool> func;
                            if ((func = <>9__0) == null)
{
                                func = (<>9__0 = (RgbDevice device) => device.PreferredLevelOfDetail == detail);
                            }
                            pipeline.Process(Enumerable.Where<RgbDevice>(enumerable, func), collection, this._lastTime);
                        }
                    }
                }
                catch
                {
                    this.DisableAllDeviceGroups();
                }
                foreach (RgbDeviceGroup rgbDeviceGroup2 in this._deviceGroups.Values)
                {
                    rgbDeviceGroup2.OnceProcessed();
                }
            }
        }
References ReLogic.Peripherals.RGB.ChromaEngine._deviceGroups, ReLogic.Peripherals.RGB.ChromaEngine._lastTime, ReLogic.Peripherals.RGB.ChromaEngine._pipeline, ReLogic.Peripherals.RGB.ChromaEngine._shaderSelector, ReLogic.Peripherals.RGB.ChromaEngine._updateLock, ReLogic.Peripherals.RGB.ShaderSelector.AtDetailLevel(), System.collection, ReLogic.Peripherals.RGB.ChromaEngine.DisableAllDeviceGroups(), ReLogic.Peripherals.RGB.RgbDeviceGroup.OnceProcessed(), and ReLogic.Peripherals.RGB.ChromaPipeline.Process().