Terraria Decompiled: System.Security.Policy.Zone.CreateFromUrl
CreateFromUrl()
static Zone System.Security.Policy.Zone.CreateFromUrl (string url) inline static
Definition at line 49 of file Zone.cs.
        {
            if (url == null)
            {
                throw new ArgumentNullException("url");
            }
            SecurityZone securityZone = SecurityZone.NoZone;
            if (url.Length == 0)
            {
                return new Zone(securityZone);
            }
            Uri uri = null;
            try
            {
                uri = new Uri(url);
            }
            catch
            {
                return new Zone(securityZone);
            }
            if (securityZone == SecurityZone.NoZone)
            {
                if (uri.IsFile)
                {
                    if (File.Exists(uri.LocalPath))
                    {
                        securityZone = SecurityZone.MyComputer;
                    }
                    else if (string.Compare("FILE://", 0, url, 0, 7, true, CultureInfo.InvariantCulture) == 0)
                    {
                        securityZone = SecurityZone.Intranet;
                    }
                    else
                    {
                        securityZone = SecurityZone.Internet;
                    }
                }
                else if (uri.IsLoopback)
                {
                    securityZone = SecurityZone.Intranet;
                }
                else
                {
                    securityZone = SecurityZone.Internet;
                }
            }
            return new Zone(securityZone);
        }
References System.IO.File.Exists(), System.Globalization.CultureInfo.InvariantCulture, Mono.Security.Uri.IsFile, Mono.Security.Uri.IsLoopback, Mono.Security.Uri.LocalPath, and System.Security.Policy.Zone.Zone().
Referenced by System.Security.Policy.Evidence.GetDefaultHostEvidence().