Terraria Decompiled: Newtonsoft.Json.Serialization.DefaultReferenceResolver.GetReference
GetReference()
string Newtonsoft.Json.Serialization.DefaultReferenceResolver.GetReference (object context, object value) inline
Implements Newtonsoft.Json.Serialization.IReferenceResolver.
Definition at line 35 of file DefaultReferenceResolver.cs.
        {
            BidirectionalDictionary<string, object> mappings = this.GetMappings(context);
            string text;
            if (!mappings.TryGetBySecond(value, out text))
            {
                this._referenceCount++;
                text = this._referenceCount.ToString(CultureInfo.InvariantCulture);
                mappings.Set(text, value);
            }
            return text;
        }
References Newtonsoft.Json.Serialization.DefaultReferenceResolver._referenceCount, Newtonsoft.Json.Serialization.DefaultReferenceResolver.GetMappings(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >.Set(), System.text, Newtonsoft.Json.Utilities.BidirectionalDictionary< TFirst, TSecond >.TryGetBySecond(), and System.value.