Terraria Decompiled: System.Runtime.Remoting.Proxies.RemotingProxy.Invoke
Invoke()
override IMessage System.Runtime.Remoting.Proxies.RemotingProxy.Invoke (IMessage request) inline
Definition at line 30 of file RemotingProxy.cs.
        {
            IMethodCallMessage methodCallMessage = request as IMethodCallMessage;
            if (methodCallMessage != null)
            {
                if (methodCallMessage.MethodBase == RemotingProxy._cache_GetHashCodeMethod)
                {
                    return new MethodResponse(base.ObjectIdentity.GetHashCode(), null, null, methodCallMessage);
                }
                if (methodCallMessage.MethodBase == RemotingProxy._cache_GetTypeMethod)
                {
                    return new MethodResponse(base.GetProxiedType(), null, null, methodCallMessage);
                }
            }
            IInternalMessage internalMessage = request as IInternalMessage;
            if (internalMessage != null)
            {
                if (internalMessage.Uri == null)
                {
                    internalMessage.Uri = this._targetUri;
                }
                internalMessage.TargetIdentity = this._objectIdentity;
            }
            this._objectIdentity.NotifyClientDynamicSinks(true, request, true, false);
            IMessageSink messageSink;
            if (Thread.CurrentContext.HasExitSinks && !this._hasEnvoySink)
            {
                messageSink = Thread.CurrentContext.GetClientContextSinkChain();
            }
            else
            {
                messageSink = this._sink;
            }
            MonoMethodMessage monoMethodMessage = request as MonoMethodMessage;
            IMessage message;
            if (monoMethodMessage == null || monoMethodMessage.CallType == CallType.Sync)
            {
                message = messageSink.SyncProcessMessage(request);
            }
            else
            {
                AsyncResult asyncResult = monoMethodMessage.AsyncResult;
                IMessageCtrl messageCtrl = messageSink.AsyncProcessMessage(request, asyncResult);
                if (asyncResult != null)
                {
                    asyncResult.SetMessageCtrl(messageCtrl);
                }
                message = new ReturnMessage(null, new object[0], 0, null, monoMethodMessage);
            }
            this._objectIdentity.NotifyClientDynamicSinks(false, request, true, false);
            return message;
        }
References System.Runtime.Remoting.Proxies.RemotingProxy._cache_GetHashCodeMethod, System.Runtime.Remoting.Proxies.RemotingProxy._cache_GetTypeMethod, System.Runtime.Remoting.Proxies.RealProxy._objectIdentity, System.Runtime.Remoting.Proxies.RemotingProxy._sink, System.Runtime.Remoting.Proxies.RealProxy._targetUri, System.Runtime.Remoting.Messaging.IMessageSink.AsyncProcessMessage(), System.Runtime.Remoting.Messaging.MonoMethodMessage.AsyncResult, System.Runtime.Remoting.Messaging.MonoMethodMessage.CallType, System.Threading.Thread.CurrentContext, System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase, System.Runtime.Remoting.Identity.NotifyClientDynamicSinks(), System.Runtime.Remoting.Messaging.AsyncResult.SetMessageCtrl(), System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage(), and System.Runtime.Remoting.Messaging.IInternalMessage.Uri.