Terraria Decompiled: System.Runtime.Remoting.Proxies.RemotingProxy.AttachIdentity
AttachIdentity()
void System.Runtime.Remoting.Proxies.RemotingProxy.AttachIdentity (Identity identity) inline package
Definition at line 84 of file RemotingProxy.cs.
        {
            this._objectIdentity = identity;
            if (identity is ClientActivatedIdentity)
            {
                ClientActivatedIdentity clientActivatedIdentity = (ClientActivatedIdentity)identity;
                this._targetContext = clientActivatedIdentity.Context;
                base.AttachServer(clientActivatedIdentity.GetServerObject());
                clientActivatedIdentity.SetClientProxy((MarshalByRefObject)this.GetTransparentProxy());
            }
            if (identity is ClientIdentity)
            {
                ((ClientIdentity)identity).ClientProxy = (MarshalByRefObject)this.GetTransparentProxy();
                this._targetUri = ((ClientIdentity)identity).TargetUri;
            }
            else
            {
                this._targetUri = identity.ObjectUri;
            }
            if (this._objectIdentity.EnvoySink != null)
            {
                this._sink = this._objectIdentity.EnvoySink;
                this._hasEnvoySink = true;
            }
            else
            {
                this._sink = this._objectIdentity.ChannelSink;
            }
            this._ctorCall = null;
        }
References System.Runtime.Remoting.Proxies.RealProxy._objectIdentity, System.Runtime.Remoting.Identity.ChannelSink, System.Runtime.Remoting.ServerIdentity.Context, System.Runtime.Remoting.Identity.EnvoySink, System.Runtime.Remoting.ClientActivatedIdentity.GetServerObject(), System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy(), System.Runtime.Remoting.Identity.ObjectUri, and System.Runtime.Remoting.ClientActivatedIdentity.SetClientProxy().
Referenced by System.Runtime.Remoting.Activation.ActivationServices.Activate(), and System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage().