Terraria Decompiled: System.Runtime.Remoting.Proxies.RemotingProxy.CanCastTo
CanCastTo()
bool System.Runtime.Remoting.Proxies.RemotingProxy.CanCastTo (Type fromType, object o) inline
Implements System.Runtime.Remoting.IRemotingTypeInfo.
Definition at line 150 of file RemotingProxy.cs.
        {
            if (this._objectIdentity is ClientIdentity)
            {
                ObjRef objRef = this._objectIdentity.CreateObjRef(null);
                if (objRef.IsReferenceToWellKnow && (fromType.IsInterface || base.GetProxiedType() == typeof(MarshalByRefObject)))
                {
                    return true;
                }
                if (objRef.TypeInfo != null)
                {
                    return objRef.TypeInfo.CanCastTo(fromType, o);
                }
            }
            return fromType.IsAssignableFrom(base.GetProxiedType());
        }
References System.Runtime.Remoting.Proxies.RealProxy._objectIdentity, System.Runtime.Remoting.IRemotingTypeInfo.CanCastTo(), System.Runtime.Remoting.Identity.CreateObjRef(), System.Type.IsAssignableFrom(), System.Type.IsInterface, System.Runtime.Remoting.ObjRef.IsReferenceToWellKnow, and System.Runtime.Remoting.ObjRef.TypeInfo.