Terraria Decompiled: Terraria.Utilities.Secrets.ToSecret
ToSecret()
static string Terraria.Utilities.Secrets.ToSecret (string plainInput) inline static
Definition at line 16 of file Secrets.cs.
        {
            byte[] array = Encoding.UTF8.GetBytes(plainInput);
            array = new BCrypt().CryptRaw(array, Secrets._salt, 4);
            for (int i = 0; i < 1000; i++)
            {
                int num = i % array.Length;
                int num2 = (int)array[num] % array.Length;
                Utils.Swap<byte>(ref array[num], ref array[num2]);
            }
            array = new BCrypt().CryptRaw(array, Secrets._salt, 4);
            return Convert.ToBase64String(array);
        }
References Terraria.Utilities.Secrets._salt, System.array, System.Text.Encoding.GetBytes(), int, System.Convert.ToBase64String(), and System.Text.Encoding.UTF8.
Referenced by Terraria.WorldGen.SecretSeed.Check(), and Terraria.WorldGen.SecretSeed.CheckInputForSecretSeed().