Terraria Decompiled: Terraria.GameContent.Creative.CreativePowersHelper.GetIconImage
GetIconImage()
static UIImageFramed Terraria.GameContent.Creative.CreativePowersHelper.GetIconImage (Point iconLocation) inline static
Definition at line 23 of file CreativePowersHelper.cs.
        {
            Asset<Texture2D> powerIconAsset = CreativePowersHelper.GetPowerIconAsset("Images/UI/Creative/Infinite_Powers");
            return new UIImageFramed(powerIconAsset, powerIconAsset.Frame(21, 1, iconLocation.X, iconLocation.Y, 0, 0))
            {
                MarginLeft = 4f,
                MarginTop = 4f,
                VAlign = 0.5f,
                HAlign = 1f,
                IgnoresMouseInteraction = true
            };
        }
References Terraria.GameContent.Creative.CreativePowersHelper.GetPowerIconAsset(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip(), Terraria.GameContent.Creative.CreativePowers.FreezeTime.CustomizeButton(), Terraria.GameContent.Creative.CreativePowers.FreezeWindDirectionAndStrength.CustomizeButton(), Terraria.GameContent.Creative.CreativePowers.FreezeRainPower.CustomizeButton(), Terraria.GameContent.Creative.CreativePowers.StopBiomeSpreadPower.CustomizeButton(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.GetOptionButton(), Terraria.GameContent.Creative.CreativePowers.ASharedSliderPower.GetOptionButton(), Terraria.GameContent.Creative.CreativePowers.APerPlayerTogglePower.ProvidePowerButtons(), and Terraria.GameContent.Creative.CreativePowers.ASharedButtonPower.ProvidePowerButtons().