Terraria Decompiled: Terraria.GameContent.UI.Elements.UIText.SetText
SetText() [3/4]
void Terraria.GameContent.UI.Elements.UIText.SetText (string text) inline
Definition at line 186 of file UIText.cs.
        {
            this.InternalSetText(text, this._textScale, this._isLarge);
        }
References Terraria.GameContent.UI.Elements.UIText._isLarge, Terraria.GameContent.UI.Elements.UIText._textScale, and Terraria.GameContent.UI.Elements.UIText.InternalSetText().
Referenced by Terraria.GameContent.UI.Elements.UICharacterListItem.ButtonMouseOut(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ButtonMouseOut(), Terraria.GameContent.UI.Elements.UIWorldListItem.ButtonMouseOut(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorkshopHub.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ClearOptionDescription(), Terraria.GameContent.UI.Elements.UICharacterListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.CloudMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.CloudMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UICharacterListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UICharacterListItem.FavoriteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.HasPlayedMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.NewlyGeneratedMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UICharacterListItem.RenameMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameMouseOver(), Terraria.GameContent.UI.States.UITextWrappingTest.ResetList(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedMouseOver(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowOptionDescription(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorkshopHub.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowSecretSeedDescription(), Terraria.GameContent.UI.Elements.UICharacterNameButton.TrimDisplayIfOverElementDimensions(), Terraria.GameContent.UI.States.UITextWrappingTest.Update(), Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryContents(), Terraria.GameContent.UI.States.UIBestiaryTest.UpdateBestiaryGridRange(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateDifficultyDescription(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHelpGlyphs(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateHexText(), Terraria.GameContent.UI.NewCraftingUI.UpdateText(), and Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UpdateTitles().