Terraria Decompiled: Terraria.NPC.Spawner.SpawnNPC
SpawnNPC() [1/2]
void Terraria.NPC.Spawner.SpawnNPC () inline
Definition at line 98048 of file NPC.cs.
            {
                for (int i = 0; i < 255; i++)
                {
                    Player player = Main.player[i];
                    if (NPC.Spawner.CanSpawnEnemiesNear(player))
                    {
                        if (Main.slimeRain)
{
                            NPC.Spawner.SlimeRainSpawns(player);
                        }
                        if (this.TrySpawnAnNPC(player))
{
                            break;
                        }
                    }
                }
            }
References Terraria.NPC.Spawner.CanSpawnEnemiesNear(), Terraria.Main.player, Terraria.Main.slimeRain, and Terraria.NPC.Spawner.SlimeRainSpawns().
Referenced by Terraria.NPC.SpawnNPC().