Terraria Decompiled: Terraria.NPC.Spawner.SpawnFaelings
SpawnFaelings()
static void Terraria.NPC.Spawner.SpawnFaelings (Player player) inline static
Definition at line 104098 of file NPC.cs.
            {
                if (NPC.AnyNPCs(677))
                {
                    return;
                }
                int num = Main.rand.Next(2, 6);
                Rectangle rectangle;
                Rectangle rectangle2;
                NPC.Spawner.GetSpawnArea(player, out rectangle, out rectangle2);
                for (int i = 0; i < num; i++)
                {
                    int num2 = 1000;
                    for (int j = 0; j < num2; j++)
                    {
                        int num3 = Main.rand.Next(rectangle.Left, rectangle.Right);
                        int num4 = Main.rand.Next(rectangle.Top, rectangle.Bottom);
                        if (Main.tile[num3, num4].liquid > 0)
{
                            if (Main.tile[num3, num4].shimmer())
{
                                while (Main.tile[num3, num4].liquid > 0)
{
                                    if (num4 < 50)
{
                                        return;
                                    }
                                    num4--;
                                }
                                if (!rectangle2.Contains(num3, num4) && NPC.Spawner.CheckNotSpawningOnScreen(num3, num4))
{
                                    int num5 = NPC.NewNPC(NPC.GetSpawnSourceForNaturalSpawn(), num3 * 16 + 8, num4 * 16, 677, 0, 0f, 0f, 0f, 0f, 255);
                                    if (Main.netMode == 2 && num5 < Main.maxNPCs)
{
                                        NetMessage.SendData(23, -1, -1, null, num5, 0f, 0f, 0f, 0, 0, 0);
                                        break;
                                    }
                                    break;
                                }
                            }
                        }
                    }
                }
            }
References Terraria.NPC.AnyNPCs(), Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.NPC.Spawner.CheckNotSpawningOnScreen(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.NPC.Spawner.GetSpawnArea(), Terraria.NPC.GetSpawnSourceForNaturalSpawn(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Tile.liquid, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Microsoft.Xna.Framework.Rectangle.Right, Terraria.NetMessage.SendData(), Terraria.Tile.shimmer(), Terraria.Main.tile, and Microsoft.Xna.Framework.Rectangle.Top.
Referenced by Terraria.Player.TrySpawningFaelings().