Terraria Decompiled: Terraria.NPC.Spawner.SpawnNPC
SpawnNPC() [2/2]
NPC Terraria.NPC.Spawner.SpawnNPC (int X, int Y, int Type, int Start = 0, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, float ai3 = 0f, int Target = 255) inline
Definition at line 103368 of file NPC.cs.
            {
                if (NPCID.FromNetId(Type) == 1)
                {
                    if (this.RollLuck(180) == 0)
                    {
                        Type = -4;
                    }
                    if (Main.tenthAnniversaryWorld && this.RollLuck(180) == 0)
                    {
                        Type = 667;
                    }
                }
                if (Target == 255)
                {
                    Target = this.defaultTarget;
                }
                int num = NPC.NewNPC(NPC.GetSpawnSourceForNaturalSpawn(), X, Y, Type, Start, ai0, ai1, ai2, ai3, Target);
                NPC npc = Main.npc[num];
                if (Main.dualDungeonsSeed && (double)Y > Main.worldSurface * 16.0 && Y < Main.UnderworldLayer * 16)
                {
                    ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.InScreenDungeonSpawn, new ParticleOrchestraSettings
                    {
                        PositionInWorld = new Vector2((float)X, (float)Y),
                        MovementVector = new Vector2((float)npc.width, (float)npc.height),
                        UniqueInfoPiece = Type
                    });
                }
                return npc;
            }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.Main.dualDungeonsSeed, Terraria.ID.NPCID.FromNetId(), Terraria.NPC.GetSpawnSourceForNaturalSpawn(), Terraria.NPC.NewNPC(), Terraria.Main.npc, Microsoft.Xna.Framework.Graphics.Target, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.UnderworldLayer, Terraria.Main.worldSurface, System.X, and System.Y.