Terraria Decompiled: Terraria.NPC.Spawner.SetSpawnFlagsForChosenTile
SetSpawnFlagsForChosenTile()
void Terraria.NPC.Spawner.SetSpawnFlagsForChosenTile (int spawnTileX, int spawnTileY, int spawnTileType, int spawnWallType) inline
Definition at line 98829 of file NPC.cs.
            {
                if (!this.skyMob && this.noGroundWorms)
                {
                    this.noWorms = true;
                }
                Tile tile = Main.tile[spawnTileX, spawnTileY];
                this.waterTile = Main.tile[spawnTileX, spawnTileY - 1].liquid > 0 && Main.tile[spawnTileX, spawnTileY - 2].liquid > 0 && Main.tile[spawnTileX, spawnTileY - 1].liquidType() == 0;
                if (tile.type == 367)
                {
                    this.nearMarble = true;
                }
                else if (tile.type == 368)
                {
                    this.nearGranite = true;
                }
                else if (Main.tile[this.pX, this.pY].type == 367)
                {
                    this.nearMarble = true;
                }
                else if (Main.tile[this.pX, this.pY].type == 368)
                {
                    this.nearGranite = true;
                }
                else
                {
                    int num = Main.rand.Next(20, 31);
                    int num2 = Main.rand.Next(1, 4);
                    if (spawnTileX - num < 0)
                    {
                        num = spawnTileX;
                    }
                    if (spawnTileY - num < 0)
                    {
                        num = spawnTileY;
                    }
                    if (spawnTileX + num >= Main.maxTilesX)
                    {
                        num = Main.maxTilesX - spawnTileX - 1;
                    }
                    if (spawnTileY + num >= Main.maxTilesY)
                    {
                        num = Main.maxTilesY - spawnTileY - 1;
                    }
                    for (int i = spawnTileX - num; i <= spawnTileX + num; i += num2)
                    {
                        int num3 = Main.rand.Next(1, 4);
                        for (int j = spawnTileY - num; j <= spawnTileY + num; j += num3)
{
                            if (Main.tile[i, j].type == 367)
{
                                this.nearMarble = true;
                            }
                            if (Main.tile[i, j].type == 368)
{
                                this.nearGranite = true;
                            }
                        }
                    }
                    num = Main.rand.Next(30, 61);
                    num2 = Main.rand.Next(3, 7);
                    if (this.pX - num < 0)
                    {
                        num = this.pX;
                    }
                    if (this.pY - num < 0)
                    {
                        num = this.pY;
                    }
                    if (this.pX + num >= Main.maxTilesX)
                    {
                        num = Main.maxTilesX - this.pX - 2;
                    }
                    if (this.pY + num >= Main.maxTilesY)
                    {
                        num = Main.maxTilesY - this.pY - 2;
                    }
                    for (int k = this.pX - num; k <= this.pX + num; k += num2)
                    {
                        int num4 = Main.rand.Next(3, 7);
                        for (int l = this.pY - num; l <= this.pY + num; l += num4)
{
                            if (Main.tile[k, l].type == 367)
{
                                this.nearMarble = true;
                            }
                            if (Main.tile[k, l].type == 368)
{
                                this.nearGranite = true;
                            }
                        }
                    }
                }
                this.underGround = (double)spawnTileY <= Main.rockLayer;
                if (Main.remixWorld)
                {
                    this.underGround = (double)spawnTileY > Main.rockLayer && spawnTileY <= Main.maxTilesY - 190;
                }
                bool flag = (double)spawnTileY > Main.rockLayer && spawnTileY < Main.UnderworldLayer;
                if (Main.dontStarveWorld)
                {
                    flag = spawnTileY < Main.UnderworldLayer;
                }
                if (flag && !this.ZoneDungeon && !this.invaders)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        int num5 = Main.rand.Next(5, 15);
                        if (spawnTileX - num5 >= 0 && spawnTileX + num5 < Main.maxTilesX)
{
                            for (int m = spawnTileX - num5; m < spawnTileX + num5; m++)
{
                                for (int n = spawnTileY - num5; n < spawnTileY + num5; n++)
{
                                    if (Main.tile[m, n].wall == 62)
{
                                        this.spawnSpider = true;
                                    }
                                }
                            }
                        }
                    }
                    else if (Main.tile[this.pX, this.pY].wall == 62)
                    {
                        this.spawnSpider = true;
                    }
                }
                if ((double)spawnTileY < Main.rockLayer && spawnTileY > 200 && !this.ZoneDungeon && !this.invaders)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        int num6 = Main.rand.Next(5, 15);
                        if (spawnTileX - num6 >= 0 && spawnTileX + num6 < Main.maxTilesX)
{
                            for (int num7 = spawnTileX - num6; num7 < spawnTileX + num6; num7++)
{
                                for (int num8 = spawnTileY - num6; num8 < spawnTileY + num6; num8++)
{
                                    if (WallID.Sets.AllowsUndergroundDesertEnemiesToSpawn[(int)Main.tile[num7, num8].wall])
{
                                        this.spawnUndergroundDesert = true;
                                    }
                                }
                            }
                        }
                    }
                    else if (WallID.Sets.AllowsUndergroundDesertEnemiesToSpawn[(int)Main.tile[this.pX, this.pY].wall])
                    {
                        this.spawnUndergroundDesert = true;
                    }
                }
                this.isSpawningInWindDirection = (float)(this.pX - spawnTileX) * Main.windSpeedTarget > 0f;
                this.surfaceSpawn = (double)spawnTileY <= Main.worldSurface;
                this.deeperThanRockLayer = (double)spawnTileY >= Main.rockLayer;
                this.isOcean = ((spawnTileX < WorldGen.oceanDistance || spawnTileX > Main.maxTilesX - WorldGen.oceanDistance) && Main.tileSand[spawnTileType] && (double)spawnTileY < Main.rockLayer) || (spawnTileType == 53 && WorldGen.oceanDepths(spawnTileX, spawnTileY));
                this.isBeach = (double)spawnTileY <= Main.worldSurface && (spawnTileX < WorldGen.beachDistance || spawnTileX > Main.maxTilesX - WorldGen.beachDistance);
                if (Main.remixWorld)
                {
                    if ((double)spawnTileY > Main.worldSurface && (double)spawnTileY < Main.rockLayer)
                    {
                        this.deeperThanRockLayer = true;
                    }
                    else
                    {
                        this.deeperThanRockLayer = false;
                    }
                    bool flag2 = (double)spawnTileY < Main.worldSurface + 5.0;
                    bool flag3 = spawnTileY > Main.UnderworldLayer;
                    if (flag2 || flag3)
                    {
                        this.raining = false;
                    }
                    if (flag2)
                    {
                        this.dayTime = false;
                    }
                    if (this.ZoneCorrupt || this.ZoneCrimson)
                    {
                        this.isOcean = false;
                        this.isBeach = false;
                    }
                    if ((double)spawnTileX < (double)Main.maxTilesX * 0.43 || (double)spawnTileX > (double)Main.maxTilesX * 0.57)
                    {
                        if ((double)spawnTileY > Main.rockLayer - 200.0 && spawnTileY < Main.maxTilesY - 200 && Main.rand.Next(2) == 0)
{
                            this.isOcean = true;
                        }
                        if ((double)spawnTileY > Main.rockLayer - 200.0 && spawnTileY < Main.maxTilesY - 200 && Main.rand.Next(2) == 0)
{
                            this.isBeach = true;
                        }
                    }
                    if ((double)spawnTileY > Main.rockLayer - 20.0)
                    {
                        if (spawnTileY <= Main.maxTilesY - 190 && Main.rand.Next(3) != 0)
{
                            this.surfaceSpawn = true;
                            this.dayTime = Main.rand.Next(2) == 0;
                        }
                        else if ((Main.bloodMoon || (Main.eclipse && Main.dayTime)) && (double)spawnTileX > (double)Main.maxTilesX * 0.38 + 50.0 && (double)spawnTileX < (double)Main.maxTilesX * 0.62)
{
                            this.surfaceSpawn = true;
                        }
                    }
                }
                if (this.dualDungeonsSpawnRules && (double)spawnTileY > Main.worldSurface && spawnTileY < Main.UnderworldLayer)
                {
                    switch (Main.rand.Next(7))
                    {
                    case 0:
                    case 1:
                        this.surfaceSpawn = true;
                        this.underGround = false;
                        this.deeperThanRockLayer = false;
                        break;
                    case 2:
                        this.surfaceSpawn = false;
                        this.underGround = true;
                        this.deeperThanRockLayer = false;
                        break;
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                        this.surfaceSpawn = false;
                        this.underGround = false;
                        this.deeperThanRockLayer = true;
                        break;
                    }
                    if (tile.active() && tile.type == 48)
                    {
                        return;
                    }
                    this.SetSpawnFlagsForChosenTile_ForDualDungeon(spawnTileX, spawnTileY, spawnTileType, spawnWallType);
                }
            }
References Terraria.Tile.active(), Terraria.ID.WallID.Sets.AllowsUndergroundDesertEnemiesToSpawn, Terraria.WorldGen.beachDistance, Terraria.Main.bloodMoon, Terraria.Main.dayTime, Terraria.Main.dontStarveWorld, Terraria.Main.eclipse, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.oceanDepths(), Terraria.WorldGen.oceanDistance, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.Main.tileSand, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, and Terraria.Main.worldSurface.