Terraria Decompiled: Terraria.NPC.Spawner.FindSpawnTile
FindSpawnTile()
bool Terraria.NPC.Spawner.FindSpawnTile (Player player, out int spawnTileX, out int spawnTileY, out bool xRange) inline
Definition at line 98757 of file NPC.cs.
            {
                Rectangle rectangle;
                Rectangle rectangle2;
                NPC.Spawner.GetSpawnArea(player, out rectangle, out rectangle2);
                for (int i = 0; i < 50; i++)
                {
                    int num = Main.rand.Next(rectangle.Left, rectangle.Right);
                    int num2 = Main.rand.Next(rectangle.Top, rectangle.Bottom);
                    if ((!Main.tile[num, num2].nactive() || !Main.tileSolid[(int)Main.tile[num, num2].type]) && (this.ignoreSafeWalls || !Main.wallHouse[(int)Main.tile[num, num2].wall]))
                    {
                        if (!this.invaders && (double)num2 < Main.worldSurface * 0.3499999940395355 && !this.spawnFriendly && ((double)num < (double)Main.maxTilesX * 0.45 || (double)num > (double)Main.maxTilesX * 0.55 || Main.hardMode))
{
                            this.skyMob = true;
                        }
                        else if (!this.invaders && (double)num2 < Main.worldSurface * 0.44999998807907104 && !this.spawnFriendly && Main.hardMode && Main.rand.Next(10) == 0)
{
                            this.skyMob = true;
                        }
                        else
{
                            while (num2 < Main.maxTilesY && num2 < rectangle.Bottom && (!Main.tile[num, num2].nactive() || !Main.tileSolid[(int)Main.tile[num, num2].type]))
{
                                num2++;
                            }
                            if (num2 >= rectangle.Bottom)
{
                                goto IL_01CB;
                            }
                        }
                        spawnTileX = num;
                        spawnTileY = num2;
                        if (!rectangle2.Contains(spawnTileX, spawnTileY) && NPC.Spawner.HasTileSpawnSpace(spawnTileX, spawnTileY))
{
                            xRange = spawnTileX >= rectangle2.Left && spawnTileX < rectangle2.Right;
                            return true;
                        }
                    }
                    IL_01CB:;
                }
                spawnTileX = 0;
                spawnTileY = 0;
                xRange = false;
                return false;
            }
References Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.NPC.Spawner.GetSpawnArea(), Terraria.Main.hardMode, Terraria.NPC.Spawner.HasTileSpawnSpace(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.tile, Terraria.Main.tileSolid, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallHouse, and Terraria.Main.worldSurface.