Terraria Decompiled: Terraria.NPC.Spawner.GetSpawnRate
GetSpawnRate()
void Terraria.NPC.Spawner.GetSpawnRate (Player player, out int spawnRate, out int maxSpawns) inline private
Definition at line 98258 of file NPC.cs.
            {
                spawnRate = NPC.defaultSpawnRate;
                maxSpawns = NPC.defaultMaxSpawns;
                if (Main.hardMode)
                {
                    spawnRate = (int)((double)NPC.defaultSpawnRate * 0.9);
                    maxSpawns = NPC.defaultMaxSpawns + 1;
                }
                if (player.position.Y > (float)(Main.UnderworldLayer * 16))
                {
                    maxSpawns = (int)((float)maxSpawns * 2f);
                }
                else if ((double)player.position.Y > Main.rockLayer * 16.0 + (double)NPC.sHeight)
                {
                    if (Main.remixWorld)
                    {
                        if (Main.hardMode)
{
                            spawnRate = (int)((double)spawnRate * 0.45);
                            maxSpawns = (int)((float)maxSpawns * 1.8f);
                        }
                        else
{
                            spawnRate = (int)((double)spawnRate * 0.5);
                            maxSpawns = (int)((float)maxSpawns * 1.7f);
                        }
                    }
                    else
                    {
                        spawnRate = (int)((double)spawnRate * 0.4);
                        maxSpawns = (int)((float)maxSpawns * 1.9f);
                    }
                }
                else if ((double)player.position.Y > Main.worldSurface * 16.0 + (double)NPC.sHeight)
                {
                    if (Main.remixWorld)
                    {
                        spawnRate = (int)((double)spawnRate * 0.4);
                        maxSpawns = (int)((float)maxSpawns * 1.9f);
                    }
                    else if (Main.hardMode)
                    {
                        spawnRate = (int)((double)spawnRate * 0.45);
                        maxSpawns = (int)((float)maxSpawns * 1.8f);
                    }
                    else
                    {
                        spawnRate = (int)((double)spawnRate * 0.5);
                        maxSpawns = (int)((float)maxSpawns * 1.7f);
                    }
                }
                else if (Main.remixWorld)
                {
                    if (!Main.dayTime)
                    {
                        spawnRate = (int)((double)spawnRate * 0.6);
                        maxSpawns = (int)((float)maxSpawns * 1.3f);
                    }
                }
                else if (!Main.dayTime)
                {
                    spawnRate = (int)((double)spawnRate * 0.6);
                    maxSpawns = (int)((float)maxSpawns * 1.3f);
                    if (Main.bloodMoon)
                    {
                        spawnRate = (int)((double)spawnRate * 0.3);
                        maxSpawns = (int)((float)maxSpawns * 1.8f);
                    }
                    if ((Main.pumpkinMoon || Main.snowMoon) && (double)player.position.Y < Main.worldSurface * 16.0)
                    {
                        spawnRate = (int)((double)spawnRate * 0.2);
                        maxSpawns *= 2;
                    }
                }
                else if (Main.dayTime && Main.eclipse)
                {
                    spawnRate = (int)((double)spawnRate * 0.2);
                    maxSpawns = (int)((float)maxSpawns * 1.9f);
                }
                if (Main.remixWorld)
                {
                    if (!Main.dayTime)
                    {
                        if (Main.bloodMoon)
{
                            spawnRate = (int)((double)spawnRate * 0.3);
                            maxSpawns = (int)((float)maxSpawns * 1.8f);
                            if ((double)player.position.Y > Main.rockLayer * 16.0 + (double)NPC.sHeight)
{
                                spawnRate = (int)((double)spawnRate * 0.6);
                            }
                        }
                        if (Main.pumpkinMoon || Main.snowMoon)
{
                            spawnRate = (int)((double)spawnRate * 0.2);
                            maxSpawns *= 2;
                            if ((double)player.position.Y > Main.rockLayer * 16.0 + (double)NPC.sHeight)
{
                                spawnRate = (int)((double)spawnRate * 0.6);
                            }
                        }
                    }
                    else if (Main.dayTime && Main.eclipse)
                    {
                        spawnRate = (int)((double)spawnRate * 0.2);
                        maxSpawns = (int)((float)maxSpawns * 1.9f);
                    }
                }
                if (this.ZoneSnow && (double)(player.position.Y / 16f) < Main.worldSurface)
                {
                    maxSpawns = (int)((float)maxSpawns + (float)maxSpawns * Main.cloudAlpha);
                    spawnRate = (int)((float)spawnRate * (1f - Main.cloudAlpha + 1f) / 2f);
                }
                if (Main.drunkWorld && Main.tile[this.pX, this.pY].wall == 86)
                {
                    spawnRate = (int)((double)spawnRate * 0.3);
                    maxSpawns = (int)((float)maxSpawns * 1.8f);
                }
                if (this.inDualDungeon || this.ZoneDungeon)
                {
                    spawnRate = (int)((double)spawnRate * 0.3);
                    maxSpawns = (int)((float)maxSpawns * 1.8f);
                }
                else if (this.ZoneSandstorm)
                {
                    spawnRate = (int)((float)spawnRate * (Main.hardMode ? 0.4f : 0.9f));
                    maxSpawns = (int)((float)maxSpawns * (Main.hardMode ? 1.5f : 1.2f));
                }
                else if (player.ZoneUndergroundDesert)
                {
                    spawnRate = (int)((float)spawnRate * 0.2f);
                    maxSpawns = (int)((float)maxSpawns * 3f);
                }
                else if (this.ZoneJungle)
                {
                    if (this.townNPCs == 0)
                    {
                        spawnRate = (int)((double)spawnRate * 0.4);
                        maxSpawns = (int)((float)maxSpawns * 1.5f);
                    }
                    else if (this.townNPCs == 1)
                    {
                        spawnRate = (int)((double)spawnRate * 0.55);
                        maxSpawns = (int)((double)maxSpawns * 1.4);
                    }
                    else if (this.townNPCs == 2)
                    {
                        spawnRate = (int)((double)spawnRate * 0.7);
                        maxSpawns = (int)((float)maxSpawns * 1.3f);
                    }
                    else
                    {
                        spawnRate = (int)((double)spawnRate * 0.85);
                        maxSpawns = (int)((float)maxSpawns * 1.2f);
                    }
                }
                else if (this.ZoneCorrupt || this.ZoneCrimson)
                {
                    spawnRate = (int)((double)spawnRate * 0.65);
                    maxSpawns = (int)((float)maxSpawns * 1.3f);
                }
                else if (this.ZoneMeteor)
                {
                    spawnRate = (int)((double)spawnRate * 0.4);
                    maxSpawns = (int)((float)maxSpawns * 1.1f);
                }
                if (this.ZoneLihzhardTemple)
                {
                    spawnRate = (int)((float)spawnRate * 0.8f);
                    maxSpawns = (int)((float)maxSpawns * 1.2f);
                    if (Main.remixWorld)
                    {
                        spawnRate = (int)((double)spawnRate * 0.4);
                        maxSpawns = (int)((float)maxSpawns * 1.5f);
                    }
                }
                if (Main.remixWorld && (this.ZoneCorrupt || this.ZoneCrimson) && (double)(player.position.Y / 16f) < Main.worldSurface)
                {
                    spawnRate = (int)((double)spawnRate * 0.5);
                    maxSpawns *= 2;
                }
                if (this.ZoneHallow && (double)player.position.Y > Main.rockLayer * 16.0 + (double)NPC.sHeight)
                {
                    spawnRate = (int)((double)spawnRate * 0.65);
                    maxSpawns = (int)((float)maxSpawns * 1.3f);
                }
                if (this.tresspassingDualDungeon)
                {
                    spawnRate = (int)((float)spawnRate * 0.6f);
                    maxSpawns = (int)((float)maxSpawns * 1.3f);
                }
                if (Main.wofNPCIndex >= 0 && player.position.Y > (float)(Main.UnderworldLayer * 16))
                {
                    maxSpawns = (int)((float)maxSpawns * 0.3f);
                    spawnRate *= 3;
                }
                if ((double)player.nearbyActiveNPCs < (double)maxSpawns * 0.2)
                {
                    spawnRate = (int)((float)spawnRate * 0.6f);
                }
                else if ((double)player.nearbyActiveNPCs < (double)maxSpawns * 0.4)
                {
                    spawnRate = (int)((float)spawnRate * 0.7f);
                }
                else if ((double)player.nearbyActiveNPCs < (double)maxSpawns * 0.6)
                {
                    spawnRate = (int)((float)spawnRate * 0.8f);
                }
                else if ((double)player.nearbyActiveNPCs < (double)maxSpawns * 0.8)
                {
                    spawnRate = (int)((float)spawnRate * 0.9f);
                }
                if ((double)(player.position.Y / 16f) > (Main.worldSurface + Main.rockLayer) / 2.0 || this.ZoneCorrupt || this.ZoneCrimson)
                {
                    if ((double)player.nearbyActiveNPCs < (double)maxSpawns * 0.2)
                    {
                        spawnRate = (int)((float)spawnRate * 0.7f);
                    }
                    else if ((double)player.nearbyActiveNPCs < (double)maxSpawns * 0.4)
                    {
                        spawnRate = (int)((float)spawnRate * 0.9f);
                    }
                }
                if (Main.remixWorld && (double)(player.position.Y / 16f) < Main.worldSurface && (this.ZoneCorrupt || this.ZoneCrimson))
                {
                    spawnRate = (int)((double)spawnRate * 0.8);
                    maxSpawns *= 2;
                }
                if (player.invis)
                {
                    spawnRate = (int)((float)spawnRate * 1.2f);
                    maxSpawns = (int)((float)maxSpawns * 0.8f);
                }
                if (player.calmed)
                {
                    spawnRate = (int)((float)spawnRate * 1.65f);
                    maxSpawns = (int)((float)maxSpawns * 0.6f);
                }
                if (player.sunflower)
                {
                    spawnRate = (int)((float)spawnRate * 1.2f);
                    maxSpawns = (int)((float)maxSpawns * 0.8f);
                }
                if (player.anglerSetSpawnReduction)
                {
                    spawnRate = (int)((float)spawnRate * 1.3f);
                    maxSpawns = (int)((float)maxSpawns * 0.7f);
                }
                if (player.enemySpawns)
                {
                    spawnRate = (int)((double)spawnRate * 0.5);
                    maxSpawns = (int)((float)maxSpawns * 2f);
                }
                if (this.ZoneWaterCandle)
                {
                    if (!this.ZonePeaceCandle)
                    {
                        spawnRate = (int)((double)spawnRate * 0.75);
                        maxSpawns = (int)((float)maxSpawns * 1.5f);
                    }
                }
                else if (this.ZonePeaceCandle)
                {
                    spawnRate = (int)((double)spawnRate * 1.3);
                    maxSpawns = (int)((float)maxSpawns * 0.7f);
                }
                if (this.ZoneWaterCandle && (double)(player.position.Y / 16f) < Main.worldSurface * 0.3499999940395355)
                {
                    spawnRate = (int)((double)spawnRate * 0.5);
                }
                if (player.isNearFairy())
                {
                    spawnRate = (int)((float)spawnRate * 1.2f);
                    maxSpawns = (int)((float)maxSpawns * 0.8f);
                }
                if ((double)spawnRate < (double)NPC.defaultSpawnRate * 0.1)
                {
                    spawnRate = (int)((double)NPC.defaultSpawnRate * 0.1);
                }
                if (maxSpawns > NPC.defaultMaxSpawns * 3)
                {
                    maxSpawns = NPC.defaultMaxSpawns * 3;
                }
                if (Main.getGoodWorld)
                {
                    spawnRate = (int)((float)spawnRate * 0.8f);
                    maxSpawns = (int)((float)maxSpawns * 1.2f);
                }
                if (Main.IsJourneyMode)
                {
                    CreativePowers.SpawnRateSliderPerPlayerPower power = CreativePowerManager.Instance.GetPower<CreativePowers.SpawnRateSliderPerPlayerPower>();
                    float num;
                    if (power != null && power.GetIsUnlocked() && power.GetRemappedSliderValueFor(player.whoAmI, out num))
                    {
                        spawnRate = (int)((float)spawnRate / num);
                        maxSpawns = (int)((float)maxSpawns * num);
                    }
                }
                if ((Main.pumpkinMoon || Main.snowMoon) && (Main.remixWorld || (double)player.position.Y < Main.worldSurface * 16.0))
                {
                    maxSpawns = (int)((double)NPC.defaultMaxSpawns * (2.0 + 0.3 * (double)this.numberOfActivePlayers));
                    spawnRate = 20;
                }
                if (DD2Event.Ongoing && this.ZoneOldOneArmy)
                {
                    maxSpawns = NPC.defaultMaxSpawns;
                    spawnRate = NPC.defaultSpawnRate;
                }
                if (this.invaders)
                {
                    maxSpawns = (int)((double)NPC.defaultMaxSpawns * (2.0 + 0.3 * (double)this.numberOfActivePlayers));
                    spawnRate = 20;
                }
                if (this.ZoneDungeon && !NPC.downedBoss3)
                {
                    spawnRate = 10;
                }
                if (WorldGen.Skyblock.lowTiles)
                {
                    spawnRate /= 2;
                }
                bool flag = this.ZoneCorrupt || this.ZoneCrimson;
                if (Main.infectedSeed)
                {
                    flag = false;
                }
                if (!this.invaders && ((!Main.bloodMoon && !Main.pumpkinMoon && !Main.snowMoon) || Main.dayTime) && (!Main.eclipse || !Main.dayTime) && !flag && !this.ZoneCrimson && !this.ZoneMeteor && !this.ZoneOldOneArmy)
                {
                    if (player.Center.Y / 16f > (float)Main.UnderworldLayer && !this.inRemixStartingArea)
                    {
                        if (this.townNPCs == 1)
{
                            if (!WorldGen.Skyblock.lowTiles)
{
                                if (Main.rand.Next(2) == 0)
{
                                    this.noWorms = true;
                                }
                                if (Main.rand.Next(10) == 0)
{
                                    this.spawnFriendly = true;
                                    maxSpawns = (int)((double)((float)maxSpawns) * 0.5);
                                }
                                else
{
                                    spawnRate = (int)((double)((float)spawnRate) * 1.25);
                                }
                            }
                        }
                        else if (this.townNPCs == 2)
{
                            if (Main.rand.Next(4) != 0)
{
                                this.noWorms = true;
                            }
                            if (Main.rand.Next(5) == 0)
{
                                this.spawnFriendly = true;
                                maxSpawns = (int)((double)((float)maxSpawns) * 0.5);
                            }
                            else
{
                                spawnRate = (int)((double)((float)spawnRate) * 1.5);
                            }
                        }
                        else if (this.townNPCs >= 3)
{
                            if (Main.rand.Next(10) != 0)
{
                                this.noWorms = true;
                            }
                            if (Main.rand.Next(3) == 0)
{
                                this.spawnFriendly = true;
                                maxSpawns = (int)((double)((float)maxSpawns) * 0.5);
                            }
                            else
{
                                spawnRate = (int)((float)spawnRate * 2f);
                            }
                        }
                    }
                    else if (this.townNPCs == 1)
                    {
                        this.noWorms = true;
                        if (!WorldGen.Skyblock.lowTiles)
{
                            if (this.ZoneGraveyard && (!this.ZonePeaceCandle || Main.rand.Next(3) == 0))
{
                                spawnRate = (int)((double)((float)spawnRate) * 1.66);
                                if (Main.rand.Next(9) == 1)
{
                                    this.spawnFriendly = true;
                                    maxSpawns = (int)((double)((float)maxSpawns) * 0.6);
                                }
                            }
                            else if (Main.rand.Next(3) == 1)
{
                                this.spawnFriendly = true;
                                maxSpawns = (int)((double)((float)maxSpawns) * 0.6);
                            }
                            else
{
                                spawnRate = (int)((float)spawnRate * 2f);
                            }
                        }
                    }
                    else if (this.townNPCs == 2)
                    {
                        this.noWorms = true;
                        if (this.ZoneGraveyard && (!this.ZonePeaceCandle || Main.rand.Next(3) == 0))
{
                            spawnRate = (int)((double)((float)spawnRate) * 2.33);
                            if (Main.rand.Next(6) == 1)
{
                                this.spawnFriendly = true;
                                maxSpawns = (int)((double)((float)maxSpawns) * 0.6);
                            }
                        }
                        else if (Main.rand.Next(3) != 0)
{
                            this.spawnFriendly = true;
                            maxSpawns = (int)((double)((float)maxSpawns) * 0.6);
                        }
                        else
{
                            spawnRate = (int)((float)spawnRate * 3f);
                        }
                    }
                    else if (this.townNPCs >= 3)
                    {
                        this.noWorms = true;
                        if (this.ZoneGraveyard && (!this.ZonePeaceCandle || Main.rand.Next(3) == 0))
{
                            spawnRate = (int)((float)spawnRate * 3f);
                            if (Main.rand.Next(3) == 1)
{
                                this.spawnFriendly = true;
                                maxSpawns = (int)((double)((float)maxSpawns) * 0.6);
                            }
                        }
                        else
{
                            if (!Main.expertMode || Main.rand.Next(30) != 0)
{
                                this.spawnFriendly = true;
                            }
                            maxSpawns = (int)((double)((float)maxSpawns) * 0.6);
                        }
                    }
                }
                if (!this.spawnFriendly && this.RollOnlyBadLuckExtreme(50) == 0)
                {
                    spawnRate = (int)((float)spawnRate * 0.85f);
                    maxSpawns = (int)((float)maxSpawns * 1.15f);
                }
            }
References Terraria.Player.anglerSetSpawnReduction, Terraria.Main.bloodMoon, Terraria.Player.calmed, Terraria.Entity.Center, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.NPC.defaultMaxSpawns, Terraria.NPC.defaultSpawnRate, Terraria.NPC.downedBoss3, Terraria.Main.drunkWorld, Terraria.Main.eclipse, Terraria.Player.enemySpawns, Terraria.Main.expertMode, Terraria.Main.getGoodWorld, Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.GetIsUnlocked(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.GetRemappedSliderValueFor(), Terraria.Main.hardMode, Terraria.Main.infectedSeed, Terraria.GameContent.Creative.CreativePowerManager.Instance, int, Terraria.Player.invis, Terraria.Main.IsJourneyMode, Terraria.Player.isNearFairy(), Terraria.WorldGen.Skyblock.lowTiles, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.NPC.sHeight, Terraria.Main.snowMoon, Terraria.Player.sunflower, Terraria.Main.tile, Terraria.Tile.wall, Terraria.Entity.whoAmI, Terraria.Main.wofNPCIndex, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.Y, and Terraria.Player.ZoneUndergroundDesert.