Terraria Decompiled: Terraria.NPC.Spawner.GetSpawnArea
GetSpawnArea()
static void Terraria.NPC.Spawner.GetSpawnArea (Player player, out Rectangle spawnArea, out Rectangle safeArea) inline static
Definition at line 98718 of file NPC.cs.
            {
                int num = (int)((double)(NPC.sWidth / 16) * 0.7);
                int num2 = (int)((double)(NPC.sHeight / 16) * 0.7);
                NPC.safeRangeX = (int)((double)(NPC.sWidth / 16) * 0.52);
                NPC.safeRangeY = (int)((double)(NPC.sHeight / 16) * 0.52);
                if (player.inventory[player.selectedItem].type == 1254 || player.inventory[player.selectedItem].type == 1299 || player.scope)
                {
                    float num3 = 1.5f;
                    if (player.inventory[player.selectedItem].type == 1254 && player.scope)
                    {
                        num3 = 1.25f;
                    }
                    else if (player.inventory[player.selectedItem].type == 1254)
                    {
                        num3 = 1.5f;
                    }
                    else if (player.inventory[player.selectedItem].type == 1299)
                    {
                        num3 = 1.5f;
                    }
                    else if (player.scope)
                    {
                        num3 = 2f;
                    }
                    num += (int)((double)(NPC.sWidth / 16) * 0.5 / (double)num3);
                    num2 += (int)((double)(NPC.sHeight / 16) * 0.5 / (double)num3);
                    NPC.safeRangeX += (int)((double)(NPC.sWidth / 16) * 0.5 / (double)num3);
                    NPC.safeRangeY += (int)((double)(NPC.sHeight / 16) * 0.5 / (double)num3);
                }
                spawnArea = WorldUtils.ClampToWorld(Utils.CenteredRectangle(player.position.ToTileCoordinates(), new Point(num * 2, num2 * 2)), 0);
                safeArea = Utils.CenteredRectangle(player.position.ToTileCoordinates(), new Point(NPC.safeRangeX * 2, NPC.safeRangeY * 2));
                if (Main.dualDungeonsSeed && !player.ZoneOverworldHeight && !player.ZoneSkyHeight)
                {
                    safeArea = Utils.CenteredRectangle(player.position.ToTileCoordinates(), new Point(NPC.safeRangeX, NPC.safeRangeY));
                }
            }
References Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.Main.dualDungeonsSeed, int, Terraria.Player.inventory, Microsoft.Xna.Framework.Graphics.Point, Terraria.Entity.position, Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.Player.scope, Terraria.Player.selectedItem, Terraria.Item.type, Terraria.Player.ZoneOverworldHeight, and Terraria.Player.ZoneSkyHeight.
Referenced by Terraria.NPC.Spawner.FindSpawnTile(), and Terraria.NPC.Spawner.SpawnFaelings().