Terraria Decompiled: Terraria.NPC.Spawner.CheckNotSpawningOnScreen
CheckNotSpawningOnScreen()
static bool Terraria.NPC.Spawner.CheckNotSpawningOnScreen (int spawnTileX, int spawnTileY) inline static
Definition at line 103566 of file NPC.cs.
            {
                Rectangle rectangle = new Rectangle(spawnTileX * 16, spawnTileY * 16, 16, 16);
                int num = NPC.sWidth / 2;
                int num2 = NPC.sHeight / 2;
                for (int i = 0; i < 255; i++)
                {
                    Player player = Main.player[i];
                    if (player.active && (!Main.dualDungeonsSeed || !player.insideUnbreakableWalls))
                    {
                        Rectangle rectangle2 = new Rectangle((int)(player.Center.X - (float)num - (float)NPC.safeRangeX), (int)(player.Center.Y - (float)num2 - (float)NPC.safeRangeY), NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                        if (rectangle.Intersects(rectangle2))
{
                            return false;
                        }
                    }
                }
                return true;
            }
References Terraria.Player.active, Terraria.Entity.Center, Terraria.Main.dualDungeonsSeed, Terraria.Player.insideUnbreakableWalls, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.player, Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.NPC.sHeight, Terraria.NPC.sWidth, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI_FindNearbyBook(), Terraria.NPC.Spawner.SpawnFaelings(), and Terraria.NPC.Spawner.TrySpawnAnNPC().