Terraria Decompiled: Terraria.NPC.Spawner.ShouldSpawnInvasionEnemies
ShouldSpawnInvasionEnemies()
static bool Terraria.NPC.Spawner.ShouldSpawnInvasionEnemies (Vector2 position) inline static
Definition at line 98221 of file NPC.cs.
            {
                if (Main.invasionType <= 0 || Main.invasionDelay != 0 || Main.invasionSize <= 0)
                {
                    return false;
                }
                if ((double)position.Y < Main.worldSurface * 16.0 + (double)NPC.sHeight || (double)Main.spawnTileY > Main.worldSurface)
                {
                    int num = 3000;
                    if ((double)position.X > Main.invasionX * 16.0 - (double)num && (double)position.X < Main.invasionX * 16.0 + (double)num)
                    {
                        return true;
                    }
                    if (Main.invasionX >= (double)(Main.maxTilesX / 2 - 5) && Main.invasionX <= (double)(Main.maxTilesX / 2 + 5))
                    {
                        int i = 0;
                        while (i < Main.maxNPCs)
{
                            if (Main.npc[i].townNPC && Math.Abs(position.X - Main.npc[i].Center.X) < (float)num)
{
                                if (Main.rand.Next(3) != 0)
{
                                    return true;
                                }
                                break;
                            }
                            else
{
                                i++;
                            }
                        }
                    }
                }
                return false;
            }
References System.Math.Abs(), Terraria.Entity.Center, Terraria.Main.invasionDelay, Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.Main.invasionX, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.rand, Terraria.NPC.sHeight, Terraria.Main.spawnTileY, Terraria.NPC.townNPC, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.Spawner.SetSpawnFlags().