Terraria Decompiled: Terraria.NPC.Spawner.HasTileSpawnSpace
HasTileSpawnSpace()
static bool Terraria.NPC.Spawner.HasTileSpawnSpace (int spawnTileX, int spawnTileY) inline static
Definition at line 103537 of file NPC.cs.
            {
                Rectangle rectangle = new Rectangle(spawnTileX - NPC.Spawner.spawnSpaceX / 2, spawnTileY - NPC.Spawner.spawnSpaceY, NPC.Spawner.spawnSpaceX, NPC.Spawner.spawnSpaceY);
                return WorldGen.InWorld(rectangle, 0) && NPC.Spawner.CanSpawnInTiles(rectangle);
            }
References Terraria.NPC.Spawner.CanSpawnInTiles(), Terraria.WorldGen.InWorld(), Terraria.NPC.Spawner.spawnSpaceX, and Terraria.NPC.Spawner.spawnSpaceY.
Referenced by Terraria.NPC.Spawner.FindSpawnTile().