Terraria Decompiled: Terraria.NPC.Spawner.TrySpawnAnNPC
TrySpawnAnNPC()
bool Terraria.NPC.Spawner.TrySpawnAnNPC (Player player) inline private
Definition at line 98068 of file NPC.cs.
            {
                this.SetSpawnFlags(player);
                int num;
                int num2;
                this.GetSpawnRate(player, out num, out num2);
                if (player.nearbyActiveNPCs >= (float)num2)
                {
                    return false;
                }
                if (Main.rand.Next(num) != 0)
                {
                    return false;
                }
                int num3;
                int num4;
                bool flag;
                if (!this.FindSpawnTile(player, out num3, out num4, out flag))
                {
                    return false;
                }
                if (!NPC.Spawner.CheckNotSpawningOnScreen(num3, num4))
                {
                    return false;
                }
                int num5 = 0;
                int num6 = 0;
                NPC.Spawner.GetProperGroundSpawnTileTypeAndWallType(num3, num4, out num5, out num6);
                if (!this.PostCheckChosenSpawnTile(num3, num4, num5, num6))
                {
                    return false;
                }
                this.SetSpawnFlagsForChosenTile(num3, num4, num5, num6);
                if (this.dualDungeonsSpawnRules && this.ZoneDungeon)
                {
                    if (!player.ZoneDungeon)
                    {
                        this.ZoneDungeon = false;
                    }
                    else
                    {
                        Tile tile = Main.tile[this.pX, this.pY];
                        if (tile == null || !Main.wallDungeon[(int)tile.wall])
{
                            this.ZoneDungeon = false;
                        }
                    }
                }
                this.SpawnAnNPC(num3, num4, num5, flag, player.whoAmI);
                if (Main.netMode == 2)
                {
                    NPC.Spawner.SyncNewlySpawnedNPCs();
                }
                return true;
            }
References Terraria.NPC.Spawner.CheckNotSpawningOnScreen(), Terraria.NPC.Spawner.GetProperGroundSpawnTileTypeAndWallType(), Terraria.Player.nearbyActiveNPCs, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NPC.Spawner.SyncNewlySpawnedNPCs(), Terraria.Main.tile, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.Entity.whoAmI, and Terraria.Player.ZoneDungeon.