Terraria Decompiled: Terraria.NPC.Spawner.SetSpawnFlags
SetSpawnFlags()
void Terraria.NPC.Spawner.SetSpawnFlags (Player player) inline private
Definition at line 98143 of file NPC.cs.
            {
                this.pX = (int)player.Center.X / 16;
                this.pY = (int)player.Center.Y / 16;
                this.luck = player.luck;
                this.dayTime = Main.dayTime;
                this.raining = Main.raining;
                this.skyMob = false;
                this.spawnFriendly = false;
                this.ignoreSafeWalls = false;
                this.waterTile = false;
                this.nearGranite = false;
                this.nearMarble = false;
                this.spawnSpider = false;
                this.spawnUndergroundDesert = false;
                this.hardDungeon = NPC.downedPlantBoss && Main.hardMode;
                this.ZoneCorrupt = player.ZoneCorrupt;
                this.ZoneCrimson = player.ZoneCrimson;
                this.ZoneHallow = player.ZoneHallow;
                this.ZoneJungle = player.ZoneJungle;
                this.ZoneSnow = player.ZoneSnow;
                this.ZoneGlowshroom = player.ZoneGlowshroom;
                this.ZoneMeteor = player.ZoneMeteor;
                this.ZoneGraveyard = player.ZoneGraveyard;
                this.ZoneDungeon = player.ZoneDungeon;
                this.ZoneLihzhardTemple = player.ZoneLihzhardTemple;
                this.ZoneSandstorm = player.ZoneSandstorm;
                this.ZoneTowerSolar = player.ZoneTowerSolar;
                this.ZoneTowerVortex = player.ZoneTowerVortex;
                this.ZoneTowerNebula = player.ZoneTowerNebula;
                this.ZoneTowerStardust = player.ZoneTowerStardust;
                this.ZoneOldOneArmy = player.ZoneOldOneArmy;
                this.ZoneWaterCandle = player.ZoneWaterCandle;
                this.ZonePeaceCandle = player.ZonePeaceCandle;
                this.ZoneShadowCandle = player.ZoneShadowCandle;
                this.dualDungeonsSpawnRules = Main.dualDungeonsSeed;
                this.inDualDungeon = this.dualDungeonsSpawnRules && player.insideUnbreakableWalls;
                this.tresspassingDualDungeon = this.inDualDungeon && DangerousDungeonCurse.GetProgressPlayerCanSafelyMatch() < DangerousDungeonCurse.GetProgressPlayerNeedsToMatch(player);
                this.invaders = NPC.Spawner.ShouldSpawnInvasionEnemies(player.position);
                if (this.ZoneTowerSolar || this.ZoneTowerNebula || this.ZoneTowerVortex || this.ZoneTowerStardust)
                {
                    this.invaders = true;
                    this.ignoreSafeWalls = true;
                }
                this.townNPCs = player.townNPCs;
                this.noWorms = WorldGen.InWorld(this.pX, this.pY, 0) && Main.wallHouse[(int)Main.tile[this.pX, this.pY].wall];
                this.noGroundWorms = player.afkCounter >= Player.AFKTimeNeededForNoWormSpawns;
                this.skyBehindPlayer = Main.wallLight[(int)Main.tile[this.pX, this.pY].wall] || Main.tile[this.pX, this.pY].wall == 73;
                this.livingTree = Main.tile[this.pX, this.pY].wall == 244;
                this.inRemixStartingArea = Main.remixWorld && (double)(player.Center.X / 16f) > (double)Main.maxTilesX * 0.39 + 50.0 && (double)(player.Center.X / 16f) < (double)Main.maxTilesX * 0.61;
                this.offensiveToTim = (player.armor[1].type == 4256 || (player.armor[1].type >= 1282 && player.armor[1].type <= 1287)) && player.armor[0].type != 238;
                this.playerHasStartingHealth = player.statLifeMax <= 100;
                if (this.ZoneShadowCandle)
                {
                    this.noWorms = false;
                    this.noGroundWorms = false;
                    this.townNPCs = 0;
                }
            }
References Terraria.Player.AFKTimeNeededForNoWormSpawns, Terraria.Player.armor, Terraria.Entity.Center, Terraria.Main.dayTime, Terraria.Main.dualDungeonsSeed, Terraria.GameContent.Events.DangerousDungeonCurse.GetProgressPlayerCanSafelyMatch(), Terraria.GameContent.Events.DangerousDungeonCurse.GetProgressPlayerNeedsToMatch(), Terraria.Main.hardMode, Terraria.Player.insideUnbreakableWalls, int, Terraria.WorldGen.InWorld(), Terraria.Player.luck, Terraria.Main.maxTilesX, Terraria.Entity.position, Terraria.Main.raining, Terraria.NPC.Spawner.ShouldSpawnInvasionEnemies(), Terraria.Main.tile, Terraria.Player.townNPCs, Terraria.Item.type, Terraria.Tile.wall, Terraria.Main.wallHouse, Terraria.Main.wallLight, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneDungeon, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneGraveyard, Terraria.Player.ZoneHallow, Terraria.Player.ZoneJungle, Terraria.Player.ZoneLihzhardTemple, Terraria.Player.ZoneMeteor, Terraria.Player.ZoneOldOneArmy, Terraria.Player.ZonePeaceCandle, Terraria.Player.ZoneSandstorm, Terraria.Player.ZoneShadowCandle, Terraria.Player.ZoneSnow, Terraria.Player.ZoneTowerNebula, Terraria.Player.ZoneTowerSolar, Terraria.Player.ZoneTowerStardust, Terraria.Player.ZoneTowerVortex, and Terraria.Player.ZoneWaterCandle.