Terraria Decompiled: Terraria.NPC.Spawner.SharkSpawnChance
SharkSpawnChance()
static int Terraria.NPC.Spawner.SharkSpawnChance (int x, int y) inline static private
Definition at line 103673 of file NPC.cs.
            {
                int num = 10;
                int num2 = 2;
                y--;
                while (!WorldGen.SolidTile3(x, y) && Main.tile[x, y].liquid > 0)
                {
                    y--;
                }
                y++;
                for (int i = 0; i < 1000; i++)
                {
                    if (Main.projectile[i].active && Main.projectile[i].type == 820 && Collision.CanHit(new Vector2((float)(x * 16 + 8), (float)(y * 16)), 1, 1, Main.projectile[i].position, Main.projectile[i].width, Main.projectile[i].height))
                    {
                        return num2;
                    }
                }
                return num;
            }
References Terraria.Projectile.active, Terraria.Collision.CanHit(), Terraria.Entity.height, Terraria.Tile.liquid, Terraria.Entity.position, Terraria.Main.projectile, Terraria.WorldGen.SolidTile3(), Terraria.Main.tile, Terraria.Projectile.type, and Terraria.Entity.width.
Referenced by Terraria.NPC.Spawner.SpawnAnNPC().