Terraria Decompiled: Terraria.NPC.Spawner.SlimeRainSpawns
SlimeRainSpawns()
static void Terraria.NPC.Spawner.SlimeRainSpawns (Player player) inline static
Definition at line 104014 of file NPC.cs.
            {
                int y = Main.MaxWorldViewSize.Y;
                int x = Main.MaxWorldViewSize.X;
                float num = 15f;
                if ((double)player.position.Y > Main.worldSurface * 16.0 + (double)(y / 2))
                {
                    return;
                }
                if (player.nearbyActiveNPCs > num)
                {
                    return;
                }
                float num2 = player.nearbyActiveNPCs / num;
                int num3 = 45 + (int)(450f * num2);
                if (Main.expertMode)
                {
                    num3 = (int)((double)num3 * 0.85);
                }
                if (Main.IsJourneyMode)
                {
                    CreativePowers.SpawnRateSliderPerPlayerPower power = CreativePowerManager.Instance.GetPower<CreativePowers.SpawnRateSliderPerPlayerPower>();
                    float num4;
                    if (power != null && power.GetIsUnlocked() && power.GetRemappedSliderValueFor(player.whoAmI, out num4))
                    {
                        num3 = (int)((float)num3 / num4);
                    }
                }
                if (Main.rand.Next(num3) != 0)
                {
                    return;
                }
                int num5 = (int)(player.Center.X - (float)x);
                int num6 = num5 + x * 2;
                int num7 = (int)((double)player.Center.Y - (double)y * 1.5);
                int num8 = (int)((double)player.Center.Y - (double)y * 0.75);
                int num9 = Main.rand.Next(num5, num6);
                int num10 = Main.rand.Next(num7, num8);
                num9 /= 16;
                num10 /= 16;
                if (num9 < 10 || num9 > Main.maxTilesX + 10)
                {
                    return;
                }
                if ((double)num10 < Main.worldSurface * 0.3 || (double)num10 > Main.worldSurface)
                {
                    return;
                }
                if (Collision.SolidTiles(num9 - 3, num9 + 3, num10 - 5, num10 + 2))
                {
                    return;
                }
                if (Main.wallHouse[(int)Main.tile[num9, num10].wall])
                {
                    return;
                }
                int num11 = 1;
                if (Main.rand.Next(200) == 0)
                {
                    num11 = -4;
                }
                else if (Main.expertMode)
                {
                    if (Main.rand.Next(7) == 0)
                    {
                        num11 = -7;
                    }
                    else if (Main.rand.Next(3) == 0)
                    {
                        num11 = -3;
                    }
                }
                else if (Main.rand.Next(10) == 0)
                {
                    num11 = -7;
                }
                else if (Main.rand.Next(5) < 2)
                {
                    num11 = -3;
                }
                NPC.NewNPC(NPC.GetSpawnSourceForNaturalSpawn(), num9 * 16 + 8, num10 * 16, num11, 0, 0f, 0f, 0f, 0f, 255);
            }
References Terraria.Entity.Center, Terraria.Main.expertMode, Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.GetIsUnlocked(), Terraria.GameContent.Creative.CreativePowers.APerPlayerSliderPower.GetRemappedSliderValueFor(), Terraria.NPC.GetSpawnSourceForNaturalSpawn(), Terraria.GameContent.Creative.CreativePowerManager.Instance, int, Terraria.Main.IsJourneyMode, Terraria.Main.maxTilesX, Terraria.Main.MaxWorldViewSize, Terraria.Player.nearbyActiveNPCs, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Collision.SolidTiles(), Terraria.Main.tile, Terraria.Tile.wall, Terraria.Main.wallHouse, Terraria.Entity.whoAmI, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.Spawner.SpawnNPC().