Terraria Decompiled: Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteButtonClick
DeleteButtonClick()
void Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 323 of file UIWorldListItem.cs.
        {
            for (int i = 0; i < Main.WorldList.Count; i++)
            {
                if (Main.WorldList[i] == this._data)
                {
                    SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
                    Main.selectedWorld = i;
                    Main.menuMode = 9;
                    return;
                }
            }
        }
References System.Collections.Generic.List< T >.Count, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Main.WorldList.
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteButtonClick(), and Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem().