Terraria Decompiled: Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem
UIWorldListItem()
Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem (WorldFileData data, int orderInList, bool canBePlayed, bool hasBeenPlayedByActivePlayer, bool isNewlyGenerated) inline
Definition at line 30 of file UIWorldListItem.cs.
        {
            this._orderInList = orderInList;
            this._data = data;
            this._canBePlayed = canBePlayed;
            this._hasBeenPlayedByActivePlayer = hasBeenPlayedByActivePlayer;
            this._isNewlyGenerated = isNewlyGenerated;
            this.LoadTextures();
            this.InitializeAppearance();
            this._worldIcon = base.GetIconElement();
            this._worldIcon.OnLeftDoubleClick += this.PlayGame;
            base.Append(this._worldIcon);
            if (this._data.DefeatedMoonlord)
            {
                UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/IconCompletion", 1))
                {
                    HAlign = 0.5f,
                    VAlign = 0.5f,
                    Top = new StyleDimension(-10f, 0f),
                    Left = new StyleDimension(-3f, 0f),
                    IgnoresMouseInteraction = true
                };
                this._worldIcon.Append(uiimage);
            }
            if (base.GetIcons().Count >= 2 && !this._data.ZenithWorld)
            {
                UIImage uiimage2 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/IconMixedSeed", 1))
                {
                    HAlign = 0f,
                    VAlign = 1f,
                    Top = StyleDimension.FromPixels(0f),
                    Left = StyleDimension.FromPixels(0f)
                };
                this._worldIcon.Append(uiimage2);
            }
            float num = 4f;
            UIImageButton uiimageButton = new UIImageButton(this._buttonPlayTexture, null);
            uiimageButton.VAlign = 1f;
            uiimageButton.Left.Set(num, 0f);
            uiimageButton.OnLeftClick += this.PlayGame;
            base.OnLeftDoubleClick += this.PlayGame;
            uiimageButton.OnMouseOver += this.PlayMouseOver;
            uiimageButton.OnMouseOut += this.ButtonMouseOut;
            base.Append(uiimageButton);
            num += 24f;
            UIImageButton uiimageButton2 = new UIImageButton(this._data.IsFavorite ? this._buttonFavoriteActiveTexture : this._buttonFavoriteInactiveTexture, null);
            uiimageButton2.VAlign = 1f;
            uiimageButton2.Left.Set(num, 0f);
            uiimageButton2.OnLeftClick += this.FavoriteButtonClick;
            uiimageButton2.OnMouseOver += this.FavoriteMouseOver;
            uiimageButton2.OnMouseOut += this.ButtonMouseOut;
            uiimageButton2.SetVisibility(1f, this._data.IsFavorite ? 0.8f : 0.4f);
            base.Append(uiimageButton2);
            num += 24f;
            if (SocialAPI.Cloud != null)
            {
                UIImageButton uiimageButton3 = new UIImageButton(this._data.IsCloudSave ? this._buttonCloudActiveTexture : this._buttonCloudInactiveTexture, null);
                uiimageButton3.VAlign = 1f;
                uiimageButton3.Left.Set(num, 0f);
                uiimageButton3.OnLeftClick += this.CloudButtonClick;
                uiimageButton3.OnMouseOver += this.CloudMouseOver;
                uiimageButton3.OnMouseOut += this.ButtonMouseOut;
                uiimageButton3.SetSnapPoint("Cloud", orderInList, null, null);
                base.Append(uiimageButton3);
                num += 24f;
            }
            if (this._data.WorldGeneratorVersion != 0UL)
            {
                UIImageButton uiimageButton4 = new UIImageButton(this._buttonSeedTexture, null);
                uiimageButton4.VAlign = 1f;
                uiimageButton4.Left.Set(num, 0f);
                uiimageButton4.OnLeftClick += this.SeedButtonClick;
                uiimageButton4.OnMouseOver += this.SeedMouseOver;
                uiimageButton4.OnMouseOut += this.ButtonMouseOut;
                uiimageButton4.SetSnapPoint("Seed", orderInList, null, null);
                base.Append(uiimageButton4);
                num += 24f;
            }
            UIImageButton uiimageButton5 = new UIImageButton(this._buttonRenameTexture, null);
            uiimageButton5.VAlign = 1f;
            uiimageButton5.Left.Set(num, 0f);
            uiimageButton5.OnLeftClick += this.RenameButtonClick;
            uiimageButton5.OnMouseOver += this.RenameMouseOver;
            uiimageButton5.OnMouseOut += this.ButtonMouseOut;
            uiimageButton5.SetSnapPoint("Rename", orderInList, null, null);
            base.Append(uiimageButton5);
            num += 24f;
            UIImageButton uiimageButton6 = new UIImageButton(this._buttonDeleteTexture, null);
            uiimageButton6.VAlign = 1f;
            uiimageButton6.HAlign = 1f;
            if (!this._data.IsFavorite)
            {
                uiimageButton6.OnLeftClick += this.DeleteButtonClick;
            }
            uiimageButton6.OnMouseOver += this.DeleteMouseOver;
            uiimageButton6.OnMouseOut += this.DeleteMouseOut;
            this._deleteButton = uiimageButton6;
            base.Append(uiimageButton6);
            num += 4f;
            this._buttonLabel = new UIText("", 1f, false);
            this._buttonLabel.VAlign = 1f;
            this._buttonLabel.Left.Set(num, 0f);
            this._buttonLabel.Top.Set(-3f, 0f);
            base.Append(this._buttonLabel);
            this._deleteButtonLabel = new UIText("", 1f, false);
            this._deleteButtonLabel.VAlign = 1f;
            this._deleteButtonLabel.HAlign = 1f;
            this._deleteButtonLabel.Left.Set(-30f, 0f);
            this._deleteButtonLabel.Top.Set(-3f, 0f);
            base.Append(this._deleteButtonLabel);
            int num2 = 0;
            if (this._hasBeenPlayedByActivePlayer)
            {
                UIImage uiimage3 = new UIImage(this._hasBeenPlayedByActivePlayerTexture)
                {
                    HAlign = 1f,
                    Left = new StyleDimension((float)num2, 0f),
                    Top = new StyleDimension(-6f, 0f),
                    ImageScale = 0.75f,
                    UseTextureSizeForOrigin = false
                };
                uiimage3.OnMouseOver += this.HasPlayedMouseOver;
                uiimage3.OnMouseOut += this.DeleteMouseOut;
                base.Append(uiimage3);
                num2 -= 24;
            }
            if (this._isNewlyGenerated)
            {
                UIImage uiimage4 = new UIImage(this._isNewlyGeneratedTexture)
                {
                    HAlign = 1f,
                    Left = new StyleDimension((float)(num2 - 2), 0f),
                    Top = new StyleDimension(-6f, 0f),
                    ImageScale = 0.75f,
                    UseTextureSizeForOrigin = false
                };
                uiimage4.OnMouseOver += this.NewlyGeneratedMouseOver;
                uiimage4.OnMouseOut += this.DeleteMouseOut;
                base.Append(uiimage4);
                num2 -= 24;
            }
            uiimageButton.SetSnapPoint("Play", orderInList, null, null);
            uiimageButton2.SetSnapPoint("Favorite", orderInList, null, null);
            uiimageButton5.SetSnapPoint("Rename", orderInList, null, null);
            uiimageButton6.SetSnapPoint("Delete", orderInList, null, null);
        }
References Terraria.GameContent.UI.Elements.UIWorldListItem._buttonCloudInactiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonDeleteTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonFavoriteInactiveTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonLabel, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonPlayTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonRenameTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._buttonSeedTexture, Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.GameContent.UI.Elements.UIWorldListItem._deleteButtonLabel, Terraria.GameContent.UI.Elements.UIWorldListItem._hasBeenPlayedByActivePlayer, Terraria.GameContent.UI.Elements.UIWorldListItem._hasBeenPlayedByActivePlayerTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._isNewlyGenerated, Terraria.GameContent.UI.Elements.UIWorldListItem._isNewlyGeneratedTexture, Terraria.GameContent.UI.Elements.UIWorldListItem._worldIcon, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIWorldListItem.ButtonMouseOut(), Terraria.Social.SocialAPI.Cloud, Terraria.GameContent.UI.Elements.UIWorldListItem.CloudButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.CloudMouseOver(), Terraria.IO.WorldFileData.DefeatedMoonlord, Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOut(), Terraria.GameContent.UI.Elements.UIWorldListItem.DeleteMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.FavoriteMouseOver(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.UIElement.HAlign, Terraria.GameContent.UI.Elements.UIWorldListItem.HasPlayedMouseOver(), Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.GameContent.UI.Elements.UIWorldListItem.InitializeAppearance(), Terraria.IO.FileData.IsCloudSave, Terraria.IO.FileData.IsFavorite, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIWorldListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorldListItem.NewlyGeneratedMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayGame(), Terraria.GameContent.UI.Elements.UIWorldListItem.PlayMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.RenameMouseOver(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedButtonClick(), Terraria.GameContent.UI.Elements.UIWorldListItem.SeedMouseOver(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.IO.WorldFileData.WorldGeneratorVersion.
Referenced by Terraria.GameContent.UI.Elements.UIWorldListItem.CompareTo().