Terraria Decompiled: System.Collections.ArrayList.Range.ToArray
ToArray() [2/2]
override Array System.Collections.ArrayList.Range.ToArray (Type type) inline virtual
Reimplemented from System.Collections.ArrayList.
Definition at line 3437 of file ArrayList.cs.
            {
                if (type == null)
                {
                    throw new ArgumentNullException("type");
                }
                this.InternalUpdateRange();
                Array array = Array.CreateInstance(type, this._baseSize);
                this._baseList.CopyTo(this._baseIndex, array, 0, this._baseSize);
                return array;
            }
References System.Collections.ArrayList.Range._baseIndex, System.Collections.ArrayList.Range._baseList, System.Collections.ArrayList.Range._baseSize, System.array, System.Collections.ArrayList.CopyTo(), System.Array.CreateInstance(), and System.Collections.ArrayList.Range.InternalUpdateRange().