Terraria Decompiled: System.Collections.ArrayList.Range.Clear
Clear()
override void System.Collections.ArrayList.Range.Clear () inline virtual
Reimplemented from System.Collections.ArrayList.
Definition at line 3008 of file ArrayList.cs.
            {
                this.InternalUpdateRange();
                if (this._baseSize != 0)
                {
                    this._baseList.RemoveRange(this._baseIndex, this._baseSize);
                    this.InternalUpdateVersion();
                    this._baseSize = 0;
                }
            }
References System.Collections.ArrayList.Range._baseIndex, System.Collections.ArrayList.Range._baseList, System.Collections.ArrayList.Range._baseSize, System.Collections.ArrayList.Range.InternalUpdateRange(), System.Collections.ArrayList.Range.InternalUpdateVersion(), and System.Collections.ArrayList.RemoveRange().