Terraria Decompiled: Terraria.DelegateMethods.CutTiles
CutTiles()
static bool Terraria.DelegateMethods.CutTiles (int x, int y) inline static
Definition at line 440 of file DelegateMethods.cs.
        {
            if (!WorldGen.InWorld(x, y, 1))
            {
                return false;
            }
            if (Main.tile[x, y] == null)
            {
                return false;
            }
            if (!Main.tileCut[(int)Main.tile[x, y].type])
            {
                return true;
            }
            if (DelegateMethods.tileCutIgnore[(int)Main.tile[x, y].type])
            {
                return true;
            }
            if (WorldGen.CanCutTile(x, y, DelegateMethods.tilecut_0))
            {
                WorldGen.KillTile(x, y, false, false, false);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                }
            }
            return true;
        }
References Terraria.WorldGen.CanCutTile(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.DelegateMethods.tilecut_0, Terraria.DelegateMethods.tileCutIgnore, and Terraria.Tile.type.
Referenced by Terraria.Projectile.CutTiles().