Terraria Decompiled: Terraria.DelegateMethods.SpreadTile
SpreadTile()
static bool Terraria.DelegateMethods.SpreadTile (int x, int y, int tileType, int dustType, bool pyramidShape = false, int overLiquidType = -1) inline static
Definition at line 63 of file DelegateMethods.cs.
        {
            float num = Math.Max(0.1f, DelegateMethods.f_1);
            if (pyramidShape)
            {
                float num2 = num;
                float num3 = DelegateMethods.v2_1.Y + num / 2f;
                float num4 = Math.Abs((float)y - num3) / num;
                num2 *= 1f - num4;
                if (Math.Abs((float)x - DelegateMethods.v2_1.X) > num2 || Math.Abs((float)y - DelegateMethods.v2_1.Y) > num)
                {
                    return false;
                }
            }
            else if (Vector2.Distance(DelegateMethods.v2_1, new Vector2((float)x, (float)y)) > num)
            {
                return false;
            }
            if (overLiquidType >= 0 && (Main.tile[x, y].liquid == 0 || (int)Main.tile[x, y].liquidType() != overLiquidType))
            {
                return !WorldGen.SolidTile(x, y, false) || (int)Main.tile[x, y].type == tileType;
            }
            WorldGen.TryKillingReplaceableTile(x, y, tileType);
            if (WorldGen.PlaceTile(x, y, tileType, false, false, -1, 0))
            {
                if (overLiquidType >= 0)
                {
                    Main.tile[x, y].Clear(TileDataType.Liquid);
                    WorldGen.SquareTileFrame(x, y, false);
                    if (Main.netMode != 0)
                    {
                        NetMessage.sendWater(x, y);
                    }
                    else
                    {
                        Liquid.AddWater(x, y);
                    }
                }
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 1, (float)x, (float)y, (float)tileType, 0, 0, 0);
                }
                Vector2 vector = new Vector2((float)(x * 16), (float)(y * 16));
                for (int i = 0; i < 3; i++)
                {
                    Dust dust = Dust.NewDustDirect(vector, 16, 16, dustType, 0f, 0f, 100, Color.Transparent, 2.2f);
                    dust.noGravity = true;
                    dust.velocity.Y = dust.velocity.Y - 1.2f;
                    dust.velocity *= 4f;
                    Dust dust2 = Dust.NewDustDirect(vector, 16, 16, dustType, 0f, 0f, 100, Color.Transparent, 1.3f);
                    dust2.velocity.Y = dust2.velocity.Y - 1.2f;
                    dust2.velocity *= 2f;
                }
                int num5 = y + 1;
                if (Main.tile[x, num5] != null && !TileID.Sets.Platforms[(int)Main.tile[x, num5].type] && (Main.tile[x, num5].topSlope() || Main.tile[x, num5].halfBrick()))
                {
                    WorldGen.SlopeTile(x, num5, 0, false, true);
                    if (Main.netMode != 0)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)num5, 0f, 0, 0, 0);
                    }
                }
                num5 = y - 1;
                if (Main.tile[x, num5] != null && !TileID.Sets.Platforms[(int)Main.tile[x, num5].type] && Main.tile[x, num5].bottomSlope())
                {
                    WorldGen.SlopeTile(x, num5, 0, false, true);
                    if (Main.netMode != 0)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)num5, 0f, 0, 0, 0);
                    }
                }
                for (int j = x - 1; j <= x + 1; j++)
                {
                    for (int k = y - 1; k <= y + 1; k++)
                    {
                        Tile tile = Main.tile[j, k];
                        if (tile.active() && tileType != (int)tile.type && (tile.type == 2 || tile.type == 23 || tile.type == 60 || tile.type == 70 || tile.type == 109 || tile.type == 199 || tile.type == 477 || tile.type == 492))
{
                            bool flag = true;
                            for (int l = j - 1; l <= j + 1; l++)
{
                                for (int m = k - 1; m <= k + 1; m++)
{
                                    if (!WorldGen.SolidTile(l, m, false))
{
                                        flag = false;
                                    }
                                }
                            }
                            if (flag)
{
                                WorldGen.KillTile(j, k, true, false, false);
                                if (Main.netMode != 0)
{
                                    NetMessage.SendData(17, -1, -1, null, 0, (float)j, (float)k, 1f, 0, 0, 0);
                                }
                            }
                        }
                    }
                }
                return true;
            }
            if (overLiquidType >= 0 && !Collision.EmptyTile(x, y, true))
            {
                return true;
            }
            Tile tile2 = Main.tile[x, y];
            return tile2 != null && tile2.type >= 0 && tile2.type < TileID.Count && (!Main.tileSolid[(int)tile2.type] || TileID.Sets.Platforms[(int)tile2.type] || tile2.type == 380);
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Liquid.AddWater(), Terraria.Tile.bottomSlope(), Terraria.Tile.Clear(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Collision.EmptyTile(), Terraria.DelegateMethods.f_1, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), System.Math.Max(), Terraria.Main.netMode, Terraria.Dust.NewDustDirect(), Terraria.WorldGen.PlaceTile(), Terraria.ID.TileID.Sets.Platforms, Terraria.NetMessage.SendData(), Terraria.NetMessage.sendWater(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.topSlope(), Microsoft.Xna.Framework.Color.Transparent, Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.Tile.type, Terraria.DelegateMethods.v2_1, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.DelegateMethods.SpreadDirt(), Terraria.DelegateMethods.SpreadIceBlocksOverWater(), and Terraria.DelegateMethods.SpreadPoopPyramid().