Terraria Decompiled: Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance
CastLightOpen_StopForSolids_ScaleWithDistance()
static bool Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance (int x, int y) inline static
Definition at line 346 of file DelegateMethods.cs.
        {
            if (x < 0 || x >= Main.maxTilesX || y < 0 || y >= Main.maxTilesY)
            {
                return false;
            }
            if (Main.tile[x, y] == null)
            {
                return false;
            }
            if (!Main.tile[x, y].active() || Main.tile[x, y].inActive() || Main.tileSolidTop[(int)Main.tile[x, y].type] || !Main.tileSolid[(int)Main.tile[x, y].type])
            {
                Vector3 vector = DelegateMethods.v3_1;
                Vector2 vector2 = new Vector2((float)x, (float)y);
                float num = Vector2.Distance(DelegateMethods.v2_1, vector2);
                vector *= MathHelper.Lerp(0.65f, 1f, num / DelegateMethods.f_1);
                Lighting.AddLight(x, y, vector.X, vector.Y, vector.Z);
                return true;
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Vector2.Distance(), Terraria.DelegateMethods.f_1, Terraria.Tile.inActive(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.DelegateMethods.v2_1, Terraria.DelegateMethods.v3_1, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Mount.EmitGolfCartlight().