Terraria Decompiled: Terraria.Localization.LocalizedText.GetPropertyLookupFunc
GetPropertyLookupFunc()
static Func< string, object > Terraria.Localization.LocalizedText.GetPropertyLookupFunc (object inst) inline static private
Definition at line 236 of file LocalizedText.cs.
        {
            Type type = inst.GetType();
            PropertyDescriptorCollection properties;
            if (!LocalizedText._propertyLookupCache.TryGetValue(type, out properties))
            {
                LocalizedText._propertyLookupCache[type] = (properties = TypeDescriptor.GetProperties(type));
            }
            return delegate(string name)
            {
                PropertyDescriptor propertyDescriptor = properties[name];
                if (propertyDescriptor != null)
                {
                    return propertyDescriptor.GetValue(inst);
                }
                return Lang.GetGlobalSubstitution(name);
            };
        }
References Terraria.Localization.LocalizedText._propertyLookupCache, Terraria.Lang.GetGlobalSubstitution(), System.name, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.Localization.LocalizedText.ConditionsMetWith(), and Terraria.Localization.LocalizedText.TryFormatWith().