Terraria Decompiled: Terraria.Localization.LocalizedText.ToNetworkText
ToNetworkText() [1/2]
NetworkText Terraria.Localization.LocalizedText.ToNetworkText () inline
Definition at line 175 of file LocalizedText.cs.
        {
            return NetworkText.FromKey(this.Key, new object[0]);
        }
References Terraria.Localization.NetworkText.FromKey(), and Terraria.Localization.LocalizedText.Key.
Referenced by Terraria.RemoteClient.CheckSection_ForClient(), Terraria.Chat.Commands.HelpCommand.ComposeMessage(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.NPCDamageTracker.GetReport(), Terraria.Chat.Commands.PartyChatCommand.SendNoTeamError(), Terraria.NPC.SpawnBoss(), Terraria.Main.UpdateTime_StartDay(), and Terraria.Main.UpdateTime_StartNight().