Terraria Decompiled: Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.AdvanceTargetPosition
AdvanceTargetPosition()
bool Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.AdvanceTargetPosition () inline protected
Definition at line 18 of file WalkerLeashedCritter.cs.
        {
            if (Math.Abs((int)(this.TargetPosition.X - base.AnchorPosition.X)) >= this.strayingRangeInBlocks)
            {
                this.direction = Math.Sign((int)(base.AnchorPosition.X - this.TargetPosition.X));
            }
            if (!WorldGen.InWorld((int)this.TargetPosition.X + this.direction, (int)this.TargetPosition.Y, 0))
            {
                this.direction *= -1;
            }
            this.spriteDirection = this.direction;
            int num = (int)this.TargetPosition.X + this.direction;
            short y = this.TargetPosition.Y;
            bool flag = !WorldGen.SolidTile2(num, (int)(y - 1));
            bool flag2 = !WorldGen.SolidTile2(num, (int)y);
            bool flag3 = !WorldGen.SolidTile2(num, (int)(y + 1));
            bool flag4 = WorldGen.AnyLiquidAt(num, (int)(y + 1), -1);
            bool flag5 = !WorldGen.SolidTile2(num, (int)(y + 2));
            bool flag6 = flag && !flag2;
            bool flag7 = flag2 && flag3 && !flag4 && !flag5;
            bool flag8 = flag2 && !flag3;
            if (flag6)
            {
                this.TargetPosition = new Point16(num, (int)(y - 1));
            }
            else if (flag7)
            {
                this.TargetPosition = new Point16(num, (int)(y + 1));
            }
            else
            {
                if (!flag8)
                {
                    return false;
                }
                this.TargetPosition = new Point16(num, (int)y);
            }
            return true;
        }
References System.Math.Abs(), Terraria.WorldGen.AnyLiquidAt(), Terraria.GameContent.LeashedEntity.direction, int, Terraria.WorldGen.InWorld(), System.Math.Sign(), Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleWalking().