Terraria Decompiled: Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleFalling
HandleFalling()
void Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleFalling (Point16 tilePosition) inline private
Definition at line 98 of file WalkerLeashedCritter.cs.
        {
            if (WorldGen.SolidTile2((int)tilePosition.X, (int)(tilePosition.Y + 1)))
            {
                this.velocity.Y = 0f;
                if (this.State == 3 || this.State == 4)
                {
                    base.Center = this.TargetPosition.ToWorldCoordinates(8f, 8f);
                }
                if (this.State != 3)
                {
                    return;
                }
                this.State = 0;
                this.WaitTime = 0;
                return;
            }
            else
            {
                this.velocity.Y = this.velocity.Y + LeashedCritter.gravity;
                if (this.velocity.Y > LeashedCritter.maxFallSpeed)
                {
                    this.velocity.Y = LeashedCritter.maxFallSpeed;
                }
                this.TargetPosition.X = tilePosition.X;
                this.TargetPosition.Y = (short)Math.Min((int)(tilePosition.Y + 1), Main.maxTilesY - 1);
                if (this.State == 4)
                {
                    return;
                }
                if ((int)(this.TargetPosition.Y - base.AnchorPosition.Y) > this.strayingRangeInBlocks)
                {
                    this.State = 4;
                    this.WaitTime = 20;
                    return;
                }
                this.State = 3;
                return;
            }
        }
References Terraria.GameContent.LeashedEntities.LeashedCritter.gravity, Terraria.GameContent.LeashedEntities.LeashedCritter.maxFallSpeed, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntities.LeashedCritter.State, Terraria.GameContent.LeashedEntities.LeashedCritter.strayingRangeInBlocks, Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.GameContent.LeashedEntity.velocity, Terraria.DataStructures.Point16.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.Update().