Terraria Decompiled: Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.Update
Update()
override void Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.Update () inline virtual
Reimplemented from Terraria.GameContent.LeashedEntities.LeashedCritter.
Definition at line 59 of file WalkerLeashedCritter.cs.
        {
            base.Update();
            Point16 point = base.Center.ToTileCoordinates16();
            this.HandleFalling(point);
            this.WaitTime -= 1;
            if (this.WaitTime <= 0)
            {
                if (this.State == 4)
                {
                    base.Recall();
                }
                this.WaitTime = (short)this.rand.Next(60, 61);
                this.State = (byte)this.rand.Next(2);
            }
            this.HandleWalking();
            int num = (int)(this.TargetPosition.X - point.X);
            int num2 = (int)(this.TargetPosition.Y - point.Y);
            if (Math.Abs(num) == 1 && Math.Abs(num2) == 1)
            {
                this.velocity.Y = (float)(num2 * 2);
            }
            float num3 = this.velocity.Length();
            Vector2 vector = this.TargetPosition.ToWorldCoordinates(8f, 8f);
            base.Center = base.Center.MoveTowards(vector, num3);
            if (base.Center == vector && this.State == 0)
            {
                this.velocity = Vector2.Zero;
            }
            if (Main.netMode != 2)
            {
                this.VisualEffects();
            }
            this.CopyToDummy();
            LeashedCritter._dummy.FindFrame();
            base.CopyFromDummy();
        }
References Terraria.GameContent.LeashedEntities.LeashedCritter._dummy, System.Math.Abs(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.CopyToDummy(), Terraria.NPC.FindFrame(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleFalling(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleWalking(), int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Main.netMode, Terraria.GameContent.LeashedEntities.LeashedCritter.rand, Terraria.GameContent.LeashedEntities.LeashedCritter.State, Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.GameContent.LeashedEntity.velocity, Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.LeashedCritter.WaitTime, Terraria.DataStructures.Point16.X, Terraria.DataStructures.Point16.Y, and Microsoft.Xna.Framework.Vector2.Zero.