Terraria Decompiled: System.Security.AccessControl.DiscretionaryAcl.GetAceQualifier
GetAceQualifier()
static AceQualifier System.Security.AccessControl.DiscretionaryAcl.GetAceQualifier (AccessControlType accessType) inline static private
Definition at line 121 of file DiscretionaryAcl.cs.
        {
            if (accessType == AccessControlType.Allow)
            {
                return AceQualifier.AccessAllowed;
            }
            if (AccessControlType.Deny == accessType)
            {
                return AceQualifier.AccessDenied;
            }
            throw new ArgumentOutOfRangeException("accessType");
        }
Referenced by System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.AddAccess(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.RemoveAccessSpecific(), System.Security.AccessControl.DiscretionaryAcl.SetAccess(), and System.Security.AccessControl.DiscretionaryAcl.SetAccess().