Terraria Decompiled: Terraria.MapRenderer.DrawToMap
DrawToMap()
static void Terraria.MapRenderer.DrawToMap (Rectangle area) inline static
Definition at line 112 of file MapRenderer.cs.
        {
            if (!Main.mapEnabled)
            {
                return;
            }
            area = WorldUtils.ClampToWorld(area, 0);
            int num = Main.maxTilesX / MapRenderer.textureMaxWidth;
            int num2 = Main.maxTilesY / MapRenderer.textureMaxHeight;
            for (int i = 0; i <= num; i++)
            {
                for (int j = 0; j <= num2; j++)
                {
                    if (!MapRenderer.checkMap(i, j))
                    {
                        return;
                    }
                }
            }
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            if (Main.clearMap || Main.refreshMap)
            {
                List<Point16>[,] array = MapRenderer.changeQueues;
                int upperBound = array.GetUpperBound(0);
                int upperBound2 = array.GetUpperBound(1);
                for (int k = array.GetLowerBound(0); k <= upperBound; k++)
                {
                    for (int l = array.GetLowerBound(1); l <= upperBound2; l++)
                    {
                        array[k, l].Clear();
                    }
                }
            }
            if (Main.clearMap)
            {
                for (int m = 0; m <= num; m++)
                {
                    for (int n = 0; n <= num2; n++)
                    {
                        MapRenderer.GraphicsDevice.SetRenderTarget(MapRenderer.mapTarget[m, n]);
                        MapRenderer.GraphicsDevice.Clear(Color.Transparent);
                        MapRenderer.GraphicsDevice.SetRenderTarget(null);
                    }
                }
                Main.clearMap = false;
            }
            RenderTarget2D renderTarget2D = null;
            int num3 = 0;
            int num4 = 0;
            while (num4 < MapRenderer.numTargetsX && num3 < Main.maxMapUpdates)
            {
                int num5 = 0;
                while (num5 < MapRenderer.numTargetsY && num3 < Main.maxMapUpdates)
                {
                    Rectangle rectangle = new Rectangle(num4 * MapRenderer.textureMaxWidth, num5 * MapRenderer.textureMaxHeight, MapRenderer.textureMaxWidth, MapRenderer.textureMaxHeight);
                    MapRenderer.DrawAreaToMap(Rectangle.Intersect(area, rectangle), num4, num5, ref renderTarget2D, ref num3);
                    num5++;
                }
                num4++;
            }
            if (renderTarget2D != null)
            {
                Main.spriteBatch.End();
                MapRenderer.GraphicsDevice.SetRenderTarget(null);
            }
            Main.mapReady = true;
            Main.loadMapLastX = 0;
            Main.loadMap = false;
            Main.loadMapLock = false;
            TimeLogger.MapUpdate.AddTime(startTimestamp);
        }
References System.array, Terraria.MapRenderer.changeQueues, Terraria.MapRenderer.checkMap(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Terraria.Main.clearMap, Terraria.MapRenderer.DrawAreaToMap(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.MapRenderer.GraphicsDevice, Microsoft.Xna.Framework.Rectangle.Intersect(), Terraria.Main.mapEnabled, Terraria.MapRenderer.mapTarget, Terraria.TimeLogger.MapUpdate, Terraria.Main.maxMapUpdates, Terraria.MapRenderer.numTargetsX, Terraria.MapRenderer.numTargetsY, Terraria.Main.refreshMap, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.spriteBatch, Terraria.TimeLogger.Start(), Terraria.MapRenderer.textureMaxHeight, Terraria.MapRenderer.textureMaxWidth, and Microsoft.Xna.Framework.Color.Transparent.
Referenced by Terraria.Main.DoDraw(), and Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap().