Terraria Decompiled: Terraria.MapRenderer.DrawChangesToMap
DrawChangesToMap()
static void Terraria.MapRenderer.DrawChangesToMap (int rX, int rY, ref RenderTarget2D activeTarget, RenderTarget2D target, int i, ref int j, MapTile mapTile) inline static private
Definition at line 235 of file MapRenderer.cs.
        {
            Main.Map.ConsumeUpdate(i, j);
            if (target != activeTarget)
            {
                if (activeTarget != null)
                {
                    Main.spriteBatch.End();
                }
                activeTarget = target;
                MapRenderer.GraphicsDevice.SetRenderTarget(target);
                Main.spriteBatch.Begin();
            }
            int num = i - rX * MapRenderer.textureMaxWidth;
            int num2 = j - rY * MapRenderer.textureMaxHeight;
            Color mapTileXnaColor = MapHelper.GetMapTileXnaColor(mapTile);
            int num3 = 1;
            int num4 = 1;
            int num5 = j + 1;
            for (;;)
            {
                MapTile mapTile3;
                MapTile mapTile2 = (mapTile3 = Main.Map[i, num5]);
                if (!mapTile3.IsChanged || !mapTile.Equals(mapTile2) || num5 / MapRenderer.textureMaxHeight != rY)
                {
                    break;
                }
                Main.Map.ConsumeUpdate(i, num5);
                num3++;
                num5++;
                j++;
            }
            if (num3 == 1)
            {
                num5 = i + 1;
                for (;;)
                {
                    MapTile mapTile3;
                    MapTile mapTile2 = (mapTile3 = Main.Map[num5, j]);
                    if (!mapTile3.IsChanged || !mapTile.Equals(mapTile2) || num5 / MapRenderer.textureMaxWidth != rX)
                    {
                        break;
                    }
                    Main.Map.ConsumeUpdate(num5, j);
                    num4++;
                    num5++;
                }
            }
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Vector2((float)num, (float)num2), new Rectangle?(new Rectangle(0, 0, num4, num3)), mapTileXnaColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Map.WorldMap.ConsumeUpdate(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Map.MapTile.Equals(), Terraria.Map.MapHelper.GetMapTileXnaColor(), Terraria.MapRenderer.GraphicsDevice, Terraria.Map.MapTile.IsChanged, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.Main.Map, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.spriteBatch, Terraria.MapRenderer.textureMaxHeight, Terraria.MapRenderer.textureMaxWidth, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.MapRenderer.DrawAreaToMap().