Terraria Decompiled: Terraria.MapRenderer.DrawToMap_Section
DrawToMap_Section()
static void Terraria.MapRenderer.DrawToMap_Section (int secX, int secY) inline static
Definition at line 305 of file MapRenderer.cs.
        {
            if (MapRenderer.mapSectionTexture == null)
            {
                MapRenderer.mapSectionTexture = new RenderTarget2D(MapRenderer.GraphicsDevice, 200, 150);
            }
            Stopwatch stopwatch = Stopwatch.StartNew();
            Color[] mapColorCacheArray = MapRenderer._mapColorCacheArray;
            int num = secX * 200;
            int num2 = num + 200;
            int num3 = secY * 150;
            int num4 = num3 + 150;
            int num5 = num / MapRenderer.textureMaxWidth;
            int num6 = num3 / MapRenderer.textureMaxHeight;
            int num7 = num % MapRenderer.textureMaxWidth;
            int num8 = num3 % MapRenderer.textureMaxHeight;
            if (!MapRenderer.checkMap(num5, num6))
            {
                return;
            }
            int num9 = 0;
            Color transparent = Color.Transparent;
            for (int i = num3; i < num4; i++)
            {
                for (int j = num; j < num2; j++)
                {
                    MapTile mapTile = Main.Map[j, i];
                    mapColorCacheArray[num9] = MapHelper.GetMapTileXnaColor(mapTile);
                    num9++;
                }
            }
            try
            {
                MapRenderer.GraphicsDevice.SetRenderTarget(MapRenderer.mapTarget[num5, num6]);
            }
            catch (ObjectDisposedException)
            {
                MapRenderer.initMap[num5, num6] = false;
                return;
            }
            Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
            double num10 = stopwatch.Elapsed.TotalMilliseconds;
            MapRenderer.mapSectionTexture.SetData<Color>(mapColorCacheArray, 0, mapColorCacheArray.Length);
            double totalMilliseconds = stopwatch.Elapsed.TotalMilliseconds;
            num10 = stopwatch.Elapsed.TotalMilliseconds;
            Main.spriteBatch.Draw(MapRenderer.mapSectionTexture, new Vector2((float)num7, (float)num8), Color.White);
            Main.spriteBatch.End();
            MapRenderer.GraphicsDevice.SetRenderTarget(null);
            double totalMilliseconds2 = stopwatch.Elapsed.TotalMilliseconds;
            stopwatch.Stop();
        }
References Terraria.MapRenderer._mapColorCacheArray, Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.MapRenderer.checkMap(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Map.MapHelper.GetMapTileXnaColor(), Terraria.MapRenderer.GraphicsDevice, Terraria.MapRenderer.initMap, Terraria.Main.Map, Terraria.MapRenderer.mapSectionTexture, Terraria.MapRenderer.mapTarget, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.spriteBatch, Terraria.MapRenderer.textureMaxHeight, Terraria.MapRenderer.textureMaxWidth, Microsoft.Xna.Framework.Color.Transparent, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DoDraw(), and Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap().