Terraria Decompiled: Terraria.DataStructures.PlayerDrawHelper.SetShaderForData
SetShaderForData()
static void Terraria.DataStructures.PlayerDrawHelper.SetShaderForData (Player player, int cHead, ref DrawData cdd) inline static
Definition at line 24 of file PlayerDrawHelper.cs.
        {
            int num;
            PlayerDrawHelper.ShaderConfiguration shaderConfiguration;
            PlayerDrawHelper.UnpackShader(cdd.shader, out num, out shaderConfiguration);
            switch (shaderConfiguration)
            {
            case PlayerDrawHelper.ShaderConfiguration.ArmorShader:
                GameShaders.Hair.Apply(0, player, new DrawData?(cdd));
                GameShaders.Armor.Apply(num, player, new DrawData?(cdd));
                return;
            case PlayerDrawHelper.ShaderConfiguration.HairShader:
                if (player.head == 0)
                {
                    GameShaders.Hair.Apply(0, player, new DrawData?(cdd));
                    GameShaders.Armor.Apply(cHead, player, new DrawData?(cdd));
                    return;
                }
                GameShaders.Armor.Apply(0, player, new DrawData?(cdd));
                GameShaders.Hair.Apply((short)num, player, new DrawData?(cdd));
                return;
            case PlayerDrawHelper.ShaderConfiguration.TileShader:
                Main.tileShader.CurrentTechnique.Passes[num].Apply();
                return;
            case PlayerDrawHelper.ShaderConfiguration.TilePaintID:
            {
                int num2 = Main.ConvertPaintIdToTileShaderIndex(num, false, false);
                Main.tileShader.CurrentTechnique.Passes[num2].Apply();
                return;
            }
            default:
                return;
            }
        }
References Terraria.Graphics.Shaders.ArmorShaderDataSet.Apply(), Terraria.Graphics.Shaders.HairShaderDataSet.Apply(), Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Main.ConvertPaintIdToTileShaderIndex(), Terraria.Graphics.Shaders.GameShaders.Hair, Terraria.Player.head, Terraria.Main.tileShader, and Terraria.DataStructures.PlayerDrawHelper.UnpackShader().
Referenced by Terraria.Graphics.Renderers.FadingPlayerShaderParticle.Draw(), Terraria.Graphics.Renderers.FlameParticle.Draw(), Terraria.DataStructures.PlayerDrawHeadLayers.DrawPlayer_RenderAllLayers(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayers(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_RenderAllLayersSlow(), and Terraria.Graphics.Renderers.MapHeadRenderer.RenderDrawData().