Terraria Decompiled: System.Security.Policy.UrlMembershipCondition.CheckUrl
CheckUrl()
void System.Security.Policy.UrlMembershipCondition.CheckUrl (string url) inline package
Definition at line 153 of file UrlMembershipCondition.cs.
        {
            if (new Uri((url.IndexOf(Uri.SchemeDelimiter) < 0) ? ("file://" + url) : url, false, false).Host.IndexOf('*') >= 1)
            {
                throw new ArgumentException(Locale.GetText("Invalid * character in url"), "name");
            }
        }
References Locale.GetText(), Mono.Security.Uri.SchemeDelimiter, and System.Security.Policy.UrlMembershipCondition.url.
Referenced by System.Security.Policy.UrlMembershipCondition.FromXml(), and System.Security.Policy.UrlMembershipCondition.UrlMembershipCondition().