Terraria Decompiled: System.Runtime.Remoting.Contexts.SynchronizationAttribute.ReleaseLock
ReleaseLock()
void System.Runtime.Remoting.Contexts.SynchronizationAttribute.ReleaseLock () inline package
Definition at line 103 of file SynchronizationAttribute.cs.
        {
            lock (this)
            {
                if (this._lockCount > 0 && this._ownerThread == Thread.CurrentThread)
                {
                    this._lockCount--;
                    this._mutex.ReleaseMutex();
                    if (this._lockCount == 0)
                    {
                        this._ownerThread = null;
                    }
                }
            }
        }
References System.Runtime.Remoting.Contexts.SynchronizationAttribute._lockCount, System.Runtime.Remoting.Contexts.SynchronizationAttribute._mutex, System.Runtime.Remoting.Contexts.SynchronizationAttribute._ownerThread, System.Threading.Thread.CurrentThread, and System.Threading.Mutex.ReleaseMutex().
Referenced by System.Runtime.Remoting.Contexts.SynchronizedClientContextSink.AsyncProcessMessage(), System.Runtime.Remoting.Contexts.SynchronizedClientContextSink.SyncProcessMessage(), System.Runtime.Remoting.Contexts.SynchronizedContextReplySink.SyncProcessMessage(), and System.Runtime.Remoting.Contexts.SynchronizedServerContextSink.SyncProcessMessage().