Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.Draw
Draw()
override void Terraria.GameContent.UI.NewCraftingUI.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 178 of file NewCraftingUI.cs.
        {
            if (base.IsMouseHovering)
            {
                Main.LocalPlayer.mouseInterface = true;
            }
            this.UpdateCraftAreaSize();
            this.UpdateText();
            this.UpdateContents();
            base.Draw(spriteBatch);
        }
References Terraria.GameContent.UI.NewCraftingUI.UpdateContents(), Terraria.GameContent.UI.NewCraftingUI.UpdateCraftAreaSize(), and Terraria.GameContent.UI.NewCraftingUI.UpdateText().