Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.GetGamepadInstructions
GetGamepadInstructions()
string Terraria.GameContent.UI.NewCraftingUI.GetGamepadInstructions () inline private
Definition at line 566 of file NewCraftingUI.cs.
        {
            if (!NewCraftingUI.Visible)
            {
                return "";
            }
            bool flag = true;
            int num = -1;
            if (UILinkPointNavigator.CurrentPoint == 20000)
            {
                num = 42;
            }
            else if (UILinkPointNavigator.CurrentPoint == 20020)
            {
                num = 7;
            }
            else if (NewCraftingUI.IsMaterialPoint(UILinkPointNavigator.CurrentPoint))
            {
                num = 43;
            }
            else if (this._hoveredEntry != null)
            {
                num = 41;
            }
            else
            {
                flag = false;
            }
            if (num != 42 && num != 43)
            {
                this._gamepadReturnToGridEntry = false;
            }
            string text = "";
            if (this._gamepadReturnToGridEntry)
            {
                text += PlayerInput.BuildCommand(Language.GetTextValue("UI.Back"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Inventory"] });
                Main.LocalPlayer.releaseInventory = false;
                if (PlayerInput.AllowExecutionOfGamepadInstructions && PlayerInput.Triggers.JustPressed.Inventory)
                {
                    this._gamepadMoveToGridEntryHack = true;
                }
            }
            else
            {
                text += PlayerInput.BuildCommand(Lang.misc[56].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Inventory"] });
            }
            text += PlayerInput.BuildCommand(Lang.misc[64].Value, new List<string>[]
            {
                PlayerInput.ProfileGamepadUI.KeyStatus["HotbarMinus"],
                PlayerInput.ProfileGamepadUI.KeyStatus["HotbarPlus"]
            });
            if (!flag || this._hoveredEntry != null)
            {
                text += PlayerInput.BuildCommand(Lang.misc[53].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                if (this._hoveredEntry != null && this._hoveredEntry.Available && !Main.InGuideCraftMenu)
                {
                    string quickCraftGamepadInstructions = ItemSlot.GetQuickCraftGamepadInstructions(this._hoveredEntry.Recipe);
                    if (quickCraftGamepadInstructions != null)
                    {
                        if (PlayerInput.AllowExecutionOfGamepadInstructions && PlayerInput.Triggers.Current.Grapple)
{
                            this._selectedRecipeIndex = new int?(this._hoveredEntry.index);
                        }
                        text += quickCraftGamepadInstructions;
                    }
                }
            }
            else if (num == 42)
            {
                NewCraftingUI.RecipeEntry selectedEntry = this.SelectedEntry;
                if (selectedEntry != null && selectedEntry.Available)
                {
                    text += ItemSlot.GetCraftSlotGamepadInstructions();
                }
            }
            if (num == 7)
            {
                text += ItemSlot.GetGamepadInstructions(ref Main.guideItem, num);
            }
            else if (!flag)
            {
                text += ItemSlot.GetGamepadInstructions(43);
            }
            else
            {
                text += ItemSlot.GetGamepadInstructions(num);
            }
            return text;
        }
References Terraria.GameContent.UI.NewCraftingUI._gamepadReturnToGridEntry, Terraria.GameContent.UI.NewCraftingUI._hoveredEntry, Terraria.GameInput.PlayerInput.AllowExecutionOfGamepadInstructions, Terraria.GameContent.UI.NewCraftingUI.RecipeEntry.Available, Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.GameInput.TriggersPack.Current, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.ItemSlot.GetCraftSlotGamepadInstructions(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.UI.ItemSlot.GetQuickCraftGamepadInstructions(), Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.TriggersSet.Grapple, Terraria.Main.guideItem, Terraria.Main.InGuideCraftMenu, Terraria.GameInput.TriggersSet.Inventory, Terraria.GameContent.UI.NewCraftingUI.IsMaterialPoint(), Terraria.GameInput.TriggersPack.JustPressed, Terraria.Lang.misc, Terraria.GameContent.UI.NewCraftingUI.SelectedEntry, System.text, Terraria.GameInput.PlayerInput.Triggers, Terraria.Localization.LocalizedText.Value, and Terraria.GameContent.UI.NewCraftingUI.Visible.
Referenced by Terraria.GameContent.UI.NewCraftingUI.NewCraftingUI().