Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.HandleCraftSlot
HandleCraftSlot()
void Terraria.GameContent.UI.NewCraftingUI.HandleCraftSlot (NewCraftingUI::RecipeEntry entry, int context) inline private
Definition at line 289 of file NewCraftingUI.cs.
        {
            Recipe recipe = entry.Recipe;
            int? selectedRecipeIndex = this._selectedRecipeIndex;
            int index = entry.index;
            bool flag = !((selectedRecipeIndex.GetValueOrDefault() == index) & (selectedRecipeIndex != null)) || (PlayerInput.UsingGamepad && context == 41);
            if (!entry.Available || flag)
            {
                if (!ItemSlot.HoverOverrideClick(recipe.createItem, context) && flag && ((Main.mouseLeft && Main.mouseLeftRelease) || (Main.mouseRight && Main.mouseRightRelease)))
                {
                    this._selectedRecipeIndex = new int?(entry.index);
                    if (entry.Available)
                    {
                        Main.focusRecipe = entry.availableIndex;
                    }
                    UILinkPointNavigator.ChangePoint(20000);
                    this._gamepadReturnToGridEntry = true;
                    Main.stackSplit = 15;
                    Main._preventCraftingBecauseClickWasUsedToChangeFocusedRecipe = true;
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                ItemSlot.MouseHover(recipe.createItem, context);
            }
            else
            {
                Main.HoverOverCraftingItemButton(Main.focusRecipe);
            }
            if (!entry.Available)
            {
                this._missingRequirementsTooltipText = this.GetReasonForRecipeNotAvailable(recipe);
            }
        }
References Terraria.GameContent.UI.NewCraftingUI._selectedRecipeIndex, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), Terraria.Recipe.createItem, Terraria.Main.focusRecipe, Terraria.GameContent.UI.NewCraftingUI.GetReasonForRecipeNotAvailable(), Terraria.Main.HoverOverCraftingItemButton(), Terraria.UI.ItemSlot.HoverOverrideClick(), System.index, Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseLeftRelease, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Recipe.Recipe(), and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.GameContent.UI.NewCraftingUI.DrawChildren(), and Terraria.GameContent.UI.NewCraftingUI.ItemGrid.DrawSlot().