Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.NewCraftingUI.SetupGamepadPoints (bool craftSlotVisible, int materialCount) inline private
Definition at line 461 of file NewCraftingUI.cs.
        {
            UILinkPage uilinkPage = UILinkPointNavigator.Pages[24];
            int num = 20050;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            UILinkPage uilinkPage2 = UILinkPointNavigator.Pages[0];
            UILinkPoint uilinkPoint = uilinkPage2.LinkMap[300];
            UILinkPoint uilinkPoint2 = ((!craftSlotVisible) ? null : uilinkPage.LinkMap[20000]);
            UILinkPoint uilinkPoint3 = ((!Main.InGuideCraftMenu) ? null : uilinkPage.LinkMap[20020]);
            UILinkPoint uilinkPoint4 = ((Main.LocalPlayer.difficulty != 3 || Main.CreativeMenu.Blocked) ? null : uilinkPage2.LinkMap[311]);
            UILinkPoint uilinkPoint5 = uilinkPage.LinkMap[20030];
            UILinkPoint uilinkPoint6 = (Main.InGuideCraftMenu ? null : uilinkPage.LinkMap[20031]);
            UILinkPoint uilinkPoint7 = this._helper.MakeLinkPointFromSnapPoint(num++, snapPoints.First((SnapPoint pt) => pt.Name == "NewCraftingUISearch"));
            if (this._gamepadMoveToSearchButtonHack)
            {
                this._gamepadMoveToSearchButtonHack = false;
                UILinkPointNavigator.ChangePoint(uilinkPoint7.ID);
            }
            List<SnapPoint> orderedPointsByCategoryName = this._helper.GetOrderedPointsByCategoryName(snapPoints, "NewCraftingUIFilters");
            UILinkPoint[] array = this._helper.CreateUILinkStripHorizontal(ref num, orderedPointsByCategoryName);
            uilinkPoint7.Up = array[0].ID;
            for (int i = 0; i < array.Length; i++)
            {
                UILinkPoint uilinkPoint8 = ((i == 10) ? uilinkPoint : uilinkPage2.LinkMap[40 + (int)Math.Round((double)((float)(i * 10) / 11f))]);
                this._helper.PairUpDown(uilinkPoint8, array[i]);
                array[i].Down = uilinkPoint7.ID;
            }
            int num2 = 0;
            if (uilinkPoint4 != null)
            {
                this._helper.PairUpDown(uilinkPoint4, array[num2]);
                this._helper.PairUpDown(uilinkPage2.LinkMap[40], uilinkPoint4);
                num2++;
            }
            this._helper.PairLeftRight(uilinkPoint4, uilinkPoint5);
            this._helper.PairUpDown(uilinkPoint5, array[num2]);
            this._helper.PairUpDown(uilinkPage2.LinkMap[40 + num2], uilinkPoint5);
            num2++;
            this._helper.PairLeftRight(uilinkPoint5, uilinkPoint6);
            if (uilinkPoint6 != null)
            {
                this._helper.PairUpDown(uilinkPoint6, array[num2]);
                this._helper.PairUpDown(uilinkPage2.LinkMap[40 + num2], uilinkPoint6);
            }
            this._helper.PairLeftRight(uilinkPoint6 ?? uilinkPoint5, uilinkPoint);
            this._helper.PairUpDown(uilinkPoint2, uilinkPoint3);
            this._helper.PairUpDown(uilinkPoint7, uilinkPoint2 ?? uilinkPoint3);
            UILinkPoint uilinkPoint9;
            if ((uilinkPoint9 = uilinkPoint3) == null)
            {
                uilinkPoint9 = uilinkPoint2 ?? uilinkPoint7;
            }
            UILinkPoint uilinkPoint10 = uilinkPoint9;
            UILinkPoint uilinkPoint11 = null;
            List<SnapPoint> orderedPointsByCategoryName2 = this._helper.GetOrderedPointsByCategoryName(snapPoints, "DynamicItemCollectionSlot");
            if (orderedPointsByCategoryName2.Count > 0)
            {
                int num3 = 20100;
                int itemsPerLine = this._itemGrid.GetItemsPerLine();
                UILinkPoint[,] array2 = this._helper.CreateUILinkPointGrid(ref num3, orderedPointsByCategoryName2, itemsPerLine, uilinkPoint10, null, null, null);
                uilinkPoint11 = array2[0, 0];
                if (this.SelectedEntry != null && this.SelectedEntry.gridIndex >= 0)
                {
                    int num4 = this.SelectedEntry.gridIndex - orderedPointsByCategoryName2[0].Id;
                    if (num4 >= 0 && num4 < orderedPointsByCategoryName2.Count)
                    {
                        uilinkPoint11 = array2[num4 % itemsPerLine, num4 / itemsPerLine];
                        if (this._gamepadMoveToGridEntryHack)
{
                            UILinkPointNavigator.ChangePoint(uilinkPoint11.ID);
                        }
                    }
                }
            }
            uilinkPoint10.Down = ((uilinkPoint11 == null) ? (-1) : uilinkPoint11.ID);
            this._gamepadMoveToGridEntryHack = false;
            UILinkPoint uilinkPoint12 = ((materialCount == 0) ? null : uilinkPage.LinkMap[20001]);
            UILinkPoint uilinkPoint13 = ((materialCount == 0) ? null : uilinkPage.LinkMap[20001 + materialCount - 1]);
            this._helper.PairLeftRight(uilinkPoint2, uilinkPoint12);
            for (int j = 0; j < Recipe.maxRequirements - 1; j++)
            {
                UILinkPoint uilinkPoint14 = uilinkPage.LinkMap[20001 + j];
                this._helper.PairLeftRight(uilinkPoint14, uilinkPage.LinkMap[20001 + j + 1]);
                uilinkPoint14.Down = ((uilinkPoint2 == null) ? (-1) : uilinkPoint2.Down);
                uilinkPoint14.Up = ((uilinkPoint2 == null) ? (-1) : uilinkPoint2.Up);
            }
            if (uilinkPoint13 != null)
            {
                uilinkPoint13.Right = -1;
            }
        }
References Terraria.GameContent.UI.NewCraftingUI._gamepadMoveToGridEntryHack, Terraria.GameContent.UI.NewCraftingUI._gamepadMoveToSearchButtonHack, Terraria.GameContent.UI.NewCraftingUI._helper, Terraria.GameContent.UI.NewCraftingUI._itemGrid, System.array, Terraria.GameContent.Creative.CreativeUI.Blocked, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripHorizontal(), Terraria.Main.CreativeMenu, Terraria.UI.Gamepad.UILinkPoint.Down, Terraria.GameContent.UI.States.UIGamepadHelper.GetOrderedPointsByCategoryName(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.Main.InGuideCraftMenu, int, Terraria.UI.Gamepad.UILinkPage.LinkMap, Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), Terraria.UI.Gamepad.UILinkPointNavigator.Pages, Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight(), Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown(), System.Math.Round(), Terraria.GameContent.UI.NewCraftingUI.SelectedEntry, and Terraria.UI.Gamepad.UILinkPoint.Up.
Referenced by Terraria.GameContent.UI.NewCraftingUI.DrawChildren().