Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.OpenCloseFilter
OpenCloseFilter()
static void Terraria.GameContent.UI.NewCraftingUI.OpenCloseFilter (NewCraftingUI::RecipeFilter filter) inline static
Definition at line 741 of file NewCraftingUI.cs.
        {
            if (!NewCraftingUI.Visible)
            {
                NewCraftingUI.Open(false, filter);
                return;
            }
            if (NewCraftingUI._instance._filter == null || !NewCraftingUI._instance._filter.Matches(filter))
            {
                if (Main.InGuideCraftMenu)
                {
                    Main.LocalPlayer.SetTalkNPC(-1);
                    Main.InGuideCraftMenu = false;
                    Main.LocalPlayer.dropItemCheck();
                }
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                NewCraftingUI._instance.SetFilter(filter);
                return;
            }
            if (NewCraftingUI._instance._openedWithoutFilter)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                NewCraftingUI._instance.SetFilter(null);
                return;
            }
            NewCraftingUI.Close(false, true);
        }
References Terraria.GameContent.UI.NewCraftingUI._filter, Terraria.GameContent.UI.NewCraftingUI._instance, Terraria.GameContent.UI.NewCraftingUI._openedWithoutFilter, Terraria.GameContent.UI.NewCraftingUI.Close(), Terraria.Player.dropItemCheck(), Terraria.Main.InGuideCraftMenu, Terraria.Main.LocalPlayer, Terraria.GameContent.UI.NewCraftingUI.Open(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.UI.NewCraftingUI.SetFilter(), Terraria.Player.SetTalkNPC(), and Terraria.GameContent.UI.NewCraftingUI.Visible.
Referenced by Terraria.Player.InteractWithCraftingStation().