Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.DrawChildren
DrawChildren()
override void Terraria.GameContent.UI.NewCraftingUI.DrawChildren (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 215 of file NewCraftingUI.cs.
        {
            this._hoveredEntry = null;
            this._missingRequirementsTooltipText = null;
            base.DrawChildren(spriteBatch);
            if (PlayerInput.UsingGamepad && this._hoveredEntry != null)
            {
                this._selectedRecipeIndex = new int?(this._hoveredEntry.index);
            }
            Vector2 vector = base.GetInnerDimensions().ToRectangle().TopLeft() + new Vector2(24f, 73f);
            if (Main.InGuideCraftMenu)
            {
                if (this.DrawRecipeSlot(spriteBatch, Main.guideItem, 7, vector + new Vector2(0f, 58f), true, 1f))
                {
                    ItemSlot.Handle(ref Main.guideItem, 7, true);
                }
                string text = (Main.guideItem.IsAir ? Lang.inter[24].Value : (Lang.inter[21].Value + " " + Main.guideItem.Name));
                ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, text, vector + new Vector2(52f, 73f), Color.White, 0f, Vector2.Zero, Vector2.One, -1f, 1f);
            }
            int num = 0;
            NewCraftingUI.RecipeEntry recipeEntry = this._hoveredEntry ?? this.SelectedEntry;
            if (recipeEntry != null)
            {
                Recipe recipe = recipeEntry.Recipe;
                if (Main.InGuideCraftMenu)
                {
                    string recipeRequirementsText = Main.GetRecipeRequirementsText(recipe, false);
                    ChatManager.DrawColorCodedStringWithShadow(spriteBatch, FontAssets.MouseText.Value, recipeRequirementsText, vector + new Vector2(52f, 36f), Color.White, 0f, Vector2.Zero, Vector2.One, -1f, 1f);
                }
                if (this.DrawRecipeSlot(spriteBatch, recipe.createItem, 42, vector, recipeEntry.Available, 1f))
                {
                    this.HandleCraftSlot(recipeEntry, 42);
                }
                spriteBatch.Draw(Main.Assets.Request<Texture2D>("Images/UI/Craft", 1).Value, vector + new Vector2(47f, 13f), null, Color.White, 0f, Vector2.Zero, 0.8f, SpriteEffects.None, 0f);
                while (num < Recipe.maxRequirements && !recipe.requiredItem[num].IsAir)
                {
                    num++;
                }
                vector += new Vector2(72f, 22f);
                float num2 = Math.Min(11f / (float)num, 1f);
                for (int i = 0; i < num; i++)
                {
                    Item item = recipe.requiredItem[i];
                    int availableItemCount = Recipe.GetAvailableItemCount(recipe.requiredItemQuickLookup[i]);
                    bool flag = Main.InGuideCraftMenu || availableItemCount >= item.stack;
                    Vector2 vector2 = vector + new Vector2((float)(i * 34), -16f) * num2;
                    UILinkPointNavigator.Shortcuts.NewCraftingUI_MaterialIndex = i;
                    if (this.DrawRecipeSlot(spriteBatch, item, 43, vector2, flag, 0.7f * num2))
                    {
                        ItemSlot.HoverOverrideClick(item, 43);
                        CraftingUI.SetRecipeMaterialDisplayName(recipe, item);
                    }
                    if (!Main.InGuideCraftMenu)
                    {
                        this.DrawOwnedItemCount(spriteBatch, availableItemCount, flag, vector2, num2);
                    }
                }
            }
            int num3 = 42;
            int num4 = 285;
            if (Main.LocalPlayer.difficulty == 3 && !Main.CreativeMenu.Blocked)
            {
                num3 += 40;
            }
            CraftingUI.DrawGridToggle(spriteBatch, num3, num4, 20030);
            num3 += 40;
            if (!Main.InGuideCraftMenu)
            {
                CraftingUI.DrawCraftFromNearbyChestsToggle(spriteBatch, num3, num4, 20031);
            }
            this.SetupGamepadPoints(recipeEntry != null, num);
        }
References Terraria.GameContent.UI.NewCraftingUI._hoveredEntry, Terraria.Main.Assets, Terraria.GameContent.UI.NewCraftingUI.RecipeEntry.Available, Terraria.GameContent.Creative.CreativeUI.Blocked, Terraria.Recipe.createItem, Terraria.Main.CreativeMenu, Terraria.Player.difficulty, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.UI.CraftingUI.DrawCraftFromNearbyChestsToggle(), Terraria.UI.CraftingUI.DrawGridToggle(), Terraria.GameContent.UI.NewCraftingUI.DrawOwnedItemCount(), Terraria.GameContent.UI.NewCraftingUI.DrawRecipeSlot(), Terraria.Recipe.GetAvailableItemCount(), Terraria.Main.GetRecipeRequirementsText(), Terraria.Main.guideItem, Terraria.UI.ItemSlot.Handle(), Terraria.GameContent.UI.NewCraftingUI.HandleCraftSlot(), Terraria.UI.ItemSlot.HoverOverrideClick(), Terraria.Main.InGuideCraftMenu, Terraria.Lang.inter, Terraria.Item.IsAir, System.item, Terraria.Main.LocalPlayer, Terraria.Recipe.maxRequirements, System.Math.Min(), Terraria.GameContent.FontAssets.MouseText, Terraria.Item.Name, Microsoft.Xna.Framework.Vector2.One, Terraria.GameContent.UI.NewCraftingUI.RecipeEntry.Recipe, Terraria.Recipe.requiredItem, Terraria.Recipe.requiredItemQuickLookup, Terraria.GameContent.UI.NewCraftingUI.SelectedEntry, Terraria.UI.CraftingUI.SetRecipeMaterialDisplayName(), Terraria.GameContent.UI.NewCraftingUI.SetupGamepadPoints(), System.text, Terraria.GameInput.PlayerInput.UsingGamepad, ReLogic.Content.Asset< T >.Value, Terraria.Localization.LocalizedText.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.