Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.UpdateContents
UpdateContents()
void Terraria.GameContent.UI.NewCraftingUI.UpdateContents () inline private
Definition at line 385 of file NewCraftingUI.cs.
        {
            Recipe.UpdateRecipeList();
            if (Main.InGuideCraftMenu && Main.guideItem != this._resetForGuideItem)
            {
                this.ResetRecipes();
            }
            foreach (NewCraftingUI.RecipeEntry recipeEntry in this._recipes)
            {
                recipeEntry.availableIndex = -1;
            }
            int num = Main.numAvailableRecipes;
            if (Main.InGuideCraftMenu && Main.guideItem.IsAir)
            {
                num = 0;
            }
            bool flag = this._filteredRecipes.Count == 0;
            for (int i = 0; i < num; i++)
            {
                int num2 = Main.availableRecipe[i];
                NewCraftingUI.RecipeEntry recipeEntry2 = this._recipeListLookup[num2];
                if (recipeEntry2 == null)
                {
                    recipeEntry2 = (this._recipeListLookup[num2] = new NewCraftingUI.RecipeEntry(num2));
                    this._recipes.Add(recipeEntry2);
                    if (this.FitsFilter(recipeEntry2.Recipe))
                    {
                        recipeEntry2.gridIndex = this._filteredRecipes.Count;
                        this._filteredRecipes.Add(recipeEntry2);
                    }
                }
                recipeEntry2.availableIndex = i;
            }
            if (this.SelectedEntry == null)
            {
                this._selectedRecipeIndex = null;
            }
            else if (this._filter != null && !this._filter.Accepts(this.SelectedEntry.Recipe))
            {
                this._selectedRecipeIndex = null;
            }
            else if (this.SelectedEntry.Available)
            {
                Main.focusRecipe = this.SelectedEntry.availableIndex;
            }
            if (this._itemGrid.Count != this._filteredRecipes.Count || (flag && this._filteredRecipes.Count > 0))
            {
                this._itemGrid.SetContentsToShow(this._filteredRecipes);
            }
        }
References Terraria.GameContent.UI.NewCraftingUI._filter, Terraria.GameContent.UI.NewCraftingUI._filteredRecipes, Terraria.GameContent.UI.NewCraftingUI._itemGrid, Terraria.GameContent.UI.NewCraftingUI._recipeListLookup, Terraria.GameContent.UI.NewCraftingUI._recipes, Terraria.Main.availableRecipe, Terraria.GameContent.UI.NewCraftingUI.FitsFilter(), Terraria.Main.guideItem, Terraria.Main.InGuideCraftMenu, Terraria.Item.IsAir, Terraria.Main.numAvailableRecipes, Terraria.GameContent.UI.NewCraftingUI.RecipeEntry.Recipe, Terraria.GameContent.UI.NewCraftingUI.ResetRecipes(), Terraria.GameContent.UI.NewCraftingUI.SelectedEntry, and Terraria.Recipe.UpdateRecipeList().
Referenced by Terraria.GameContent.UI.NewCraftingUI.Draw().