Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.BuildInfinitesMenuContents
BuildInfinitesMenuContents()
void Terraria.GameContent.UI.NewCraftingUI.BuildInfinitesMenuContents (UIElement totalContainer) inline private
Definition at line 99 of file NewCraftingUI.cs.
        {
            UIPanel uipanel = new UIPanel
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(-38f, 1f),
                Top = new StyleDimension(38f, 0f),
                PaddingRight = 8f
            };
            uipanel.BackgroundColor = Utils.ShiftBlueToCyanTheme(uipanel.BackgroundColor);
            uipanel.BorderColor = Utils.ShiftBlueToCyanTheme(uipanel.BorderColor);
            uipanel.BackgroundColor *= 0.8f;
            uipanel.BorderColor *= 0.8f;
            totalContainer.Append(uipanel);
            UIText uitext = new UIText("", 1f, false)
            {
                Left = new StyleDimension(-1f, 0f),
                Top = new StyleDimension(-2f, 0f)
            };
            uipanel.Append(uitext);
            this._text = uitext;
            UIWrappedSearchBar uiwrappedSearchBar = new UIWrappedSearchBar(new Action(this.GoBackFromVirtualKeyboard), null, UIWrappedSearchBar.ColorTheme.Red)
            {
                Top = new StyleDimension(-4f, 0f),
                HAlign = 1f
            };
            uiwrappedSearchBar.CustomOpenVirtualKeyboard = delegate(UIState state)
            {
                IngameFancyUI.OpenUIState(state, false);
            };
            uiwrappedSearchBar.OnSearchContentsChanged += this.OnSearchContentsChanged;
            uiwrappedSearchBar.SetSearchSnapPoint("NewCraftingUISearch", 0, null, null);
            uipanel.Append(uiwrappedSearchBar);
            this._searchBar = uiwrappedSearchBar;
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.Fill,
                Height = StyleDimension.Fill,
                VAlign = 1f
            };
            this._gridContainer = uielement;
            uipanel.Append(uielement);
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
            {
                Width = new StyleDimension(-8f, 1f),
                HAlign = 0.5f,
                Color = new Color(89, 116, 213, 255) * 0.9f
            };
            uihorizontalSeparator.Color = Utils.ShiftBlueToCyanTheme(uihorizontalSeparator.Color);
            uielement.Append(uihorizontalSeparator);
            UIList uilist = new UIList
            {
                Width = new StyleDimension(-20f, 1f),
                Height = new StyleDimension(-7f, 1f),
                VAlign = 1f,
                HAlign = 0f
            };
            uielement.Append(uilist);
            float num = 4f;
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Cyan)
            {
                AutoHide = true,
                Height = new StyleDimension(-num * 2f - 11f, 1f),
                Top = new StyleDimension(-num, 0f),
                VAlign = 1f,
                HAlign = 1f
            };
            uielement.Append(uiscrollbar);
            uilist.SetScrollbar(uiscrollbar);
            uilist.Add(this._itemGrid = new NewCraftingUI.ItemGrid(this));
            UICreativeItemsInfiniteFilteringOptions uicreativeItemsInfiniteFilteringOptions = new UICreativeItemsInfiniteFilteringOptions(this._filterer, "NewCraftingUIFilters", UICreativeItemsInfiniteFilteringOptions.ColorTheme.Cyan)
            {
                HAlign = 0.5f
            };
            uicreativeItemsInfiniteFilteringOptions.OnClickingOption += this.ResetRecipes;
            totalContainer.Append(uicreativeItemsInfiniteFilteringOptions);
        }
References Terraria.GameContent.UI.NewCraftingUI._filterer, Terraria.GameContent.UI.NewCraftingUI._itemGrid, System.Action(), Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.Elements.UIHorizontalSeparator.Color, Terraria.UI.StyleDimension.Fill, Terraria.GameContent.UI.NewCraftingUI.GoBackFromVirtualKeyboard(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.NewCraftingUI.OnSearchContentsChanged(), Terraria.UI.IngameFancyUI.OpenUIState(), Terraria.UI.UIElement.PaddingRight, Terraria.GameContent.UI.NewCraftingUI.ResetRecipes(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.SetSearchSnapPoint(), Terraria.Utils.ShiftBlueToCyanTheme(), System.state, Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.NewCraftingUI.NewCraftingUI().