Terraria Decompiled: Terraria.GameContent.UI.NewCraftingUI.DrawRecipeSlot
DrawRecipeSlot()
bool Terraria.GameContent.UI.NewCraftingUI.DrawRecipeSlot (SpriteBatch spriteBatch, Item item, int context, Vector2 pos, bool enabled, float scale) inline private
Definition at line 355 of file NewCraftingUI.cs.
        {
            Color inventoryBack = Main.inventoryBack;
            Main.inventoryBack = Color.White * 0.7490196f;
            float inventoryScale = Main.inventoryScale;
            Main.inventoryScale *= scale;
            ItemSlot.Draw(spriteBatch, ref item, context, pos, enabled ? Color.White : NewCraftingUI.DisabledSlotColor);
            Main.inventoryScale = inventoryScale;
            Main.inventoryBack = inventoryBack;
            Rectangle rectangle = new Rectangle((int)pos.X, (int)pos.Y, (int)((float)TextureAssets.InventoryBack.Width() * scale), (int)((float)TextureAssets.InventoryBack.Height() * scale));
            return rectangle.Contains(Main.MouseScreen.ToPoint());
        }
References Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.UI.NewCraftingUI.DisabledSlotColor, Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryBack, Terraria.Main.inventoryScale, System.item, Terraria.Main.MouseScreen, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.NewCraftingUI.DrawChildren().