Terraria Decompiled: System.__DTString.MatchSpecifiedWords
MatchSpecifiedWords()
unsafe bool System.__DTString.MatchSpecifiedWords (string target, bool checkWordBoundary, ref int matchLength) inline package
Definition at line 202 of file __DTString.cs.
        {
            int num = this.Value.Length - this.Index;
            matchLength = target.Length;
            if (matchLength > num || this.m_info.Compare(this.Value.Slice(this.Index, matchLength), target, CompareOptions.IgnoreCase) != 0)
            {
                int num2 = 0;
                int num3 = this.Index;
                int num4 = target.IndexOfAny(__DTString.WhiteSpaceChecks, num2);
                if (num4 == -1)
                {
                    return false;
                }
                for (;;)
                {
                    int num5 = num4 - num2;
                    if (num3 >= this.Value.Length - num5)
                    {
                        break;
                    }
                    if (num5 == 0)
                    {
                        matchLength--;
                    }
                    else
                    {
                        if (!char.IsWhiteSpace((char)(*this.Value[num3 + num5])))
{
                            return false;
                        }
                        if (this.m_info.CompareOptionIgnoreCase(this.Value.Slice(num3, num5), target.AsSpan(num2, num5)) != 0)
{
                            return false;
                        }
                        num3 = num3 + num5 + 1;
                    }
                    num2 = num4 + 1;
                    while (num3 < this.Value.Length && char.IsWhiteSpace((char)(*this.Value[num3])))
                    {
                        num3++;
                        matchLength++;
                    }
                    if ((num4 = target.IndexOfAny(__DTString.WhiteSpaceChecks, num2)) < 0)
                    {
                        goto Block_8;
                    }
                }
                return false;
                Block_8:
                if (num2 < target.Length)
                {
                    int num6 = target.Length - num2;
                    if (num3 > this.Value.Length - num6)
                    {
                        return false;
                    }
                    if (this.m_info.CompareOptionIgnoreCase(this.Value.Slice(num3, num6), target.AsSpan(num2, num6)) != 0)
                    {
                        return false;
                    }
                }
            }
            if (checkWordBoundary)
            {
                int num7 = this.Index + matchLength;
                if (num7 < this.Value.Length && char.IsLetter((char)(*this.Value[num7])))
                {
                    return false;
                }
            }
            return true;
        }
References System.Globalization.CompareInfo.Compare(), System.Globalization.CompareInfo.CompareOptionIgnoreCase(), System.__DTString.Index, System.ReadOnlySpan< T >.Length, System.__DTString.m_info, System.__DTString.Value, and System.__DTString.WhiteSpaceChecks.
Referenced by System.__DTString.MatchLongestWords().