Terraria Decompiled: System.__DTString.RemoveLeadingInQuoteSpaces
RemoveLeadingInQuoteSpaces()
unsafe void System.__DTString.RemoveLeadingInQuoteSpaces () inline package
Definition at line 439 of file __DTString.cs.
        {
            if (this.Length <= 2)
            {
                return;
            }
            int num = 0;
            char c = (char)(*this.Value[num]);
            if (c != '\'')
            {
                if (c != '"')
                {
                    return;
                }
            }
            while (num + 1 < this.Length && char.IsWhiteSpace((char)(*this.Value[num + 1])))
            {
                num++;
            }
            if (num != 0)
            {
                Span<char> span = new char[this.Value.Length - num];
                *span[0] = c;
                this.Value.Slice(num + 1).CopyTo(span.Slice(1));
                this.Value = span;
            }
        }
References System.__DTString.Length, System.ReadOnlySpan< T >.Slice(), System.Span< T >.Slice(), and System.__DTString.Value.
Referenced by System.DateTimeParse.DoStrictParse().