Terraria Decompiled: Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.Deserialize
Deserialize()
override bool Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 21 of file NetCreativeUnlocksPlayerReportModule.cs.
        {
            int num = (int)reader.ReadByte();
            int num2 = (int)reader.ReadUInt16();
            int num3 = (int)reader.ReadUInt16();
            if (Main.dedServ)
            {
                NetManager.Instance.Broadcast(NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(userId, num2, num3), userId);
                return true;
            }
            Player player = Main.player[num];
            if (Main.LocalPlayer.team > 0 && Main.LocalPlayer.team == player.team)
            {
                Main.LocalPlayerCreativeTracker.ItemSacrifices.RegisterItemSacrifice(num2, num3, player.name);
            }
            return true;
        }
References Terraria.Net.NetManager.Broadcast(), Terraria.Main.dedServ, Terraria.Net.NetManager.Instance, int, Terraria.Main.LocalPlayer, Terraria.Main.LocalPlayerCreativeTracker, Terraria.Player.name, Terraria.Main.player, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadUInt16(), Terraria.GameContent.NetModules.NetCreativeUnlocksPlayerReportModule.SerializeSacrificeRequest(), and Terraria.Player.team.