Terraria Decompiled: System.Runtime.Remoting.RemotingConfiguration.RegisterActivatedClientType
RegisterActivatedClientType() [1/2]
static void System.Runtime.Remoting.RemotingConfiguration.RegisterActivatedClientType (ActivatedClientTypeEntry entry) inline static
Definition at line 265 of file RemotingConfiguration.cs.
        {
            Hashtable hashtable = RemotingConfiguration.channelTemplates;
            lock (hashtable)
            {
                if (RemotingConfiguration.wellKnownClientEntries.ContainsKey(entry.ObjectType) || RemotingConfiguration.activatedClientEntries.ContainsKey(entry.ObjectType))
                {
                    throw new RemotingException("Attempt to redirect activation of type '" + entry.ObjectType.FullName + "' which is already redirected.");
                }
                RemotingConfiguration.activatedClientEntries[entry.ObjectType] = entry;
                ActivationServices.EnableProxyActivation(entry.ObjectType, true);
            }
        }
References System.Runtime.Remoting.RemotingConfiguration.activatedClientEntries, System.Runtime.Remoting.RemotingConfiguration.channelTemplates, System.Collections.Hashtable.ContainsKey(), System.Runtime.Remoting.Activation.ActivationServices.EnableProxyActivation(), System.Type.FullName, System.Runtime.Remoting.ActivatedClientTypeEntry.ObjectType, and System.Runtime.Remoting.RemotingConfiguration.wellKnownClientEntries.
Referenced by System.Runtime.Remoting.RemotingConfiguration.RegisterActivatedClientType(), and System.Runtime.Remoting.RemotingConfiguration.RegisterTypes().