Terraria Decompiled: System.Runtime.Remoting.RemotingConfiguration.RegisterChannels
RegisterChannels()
static void System.Runtime.Remoting.RemotingConfiguration.RegisterChannels (ArrayList channels, bool onlyDelayed) inline static package
Definition at line 374 of file RemotingConfiguration.cs.
        {
            foreach (object obj in channels)
            {
                ChannelData channelData = (ChannelData)obj;
                if ((!onlyDelayed || !(channelData.DelayLoadAsClientChannel != "true")) && (!RemotingConfiguration.defaultDelayedConfigRead || !(channelData.DelayLoadAsClientChannel == "true")))
                {
                    if (channelData.Ref != null)
                    {
                        ChannelData channelData2 = (ChannelData)RemotingConfiguration.channelTemplates[channelData.Ref];
                        if (channelData2 == null)
{
                            throw new RemotingException("Channel template '" + channelData.Ref + "' not found");
                        }
                        channelData.CopyFrom(channelData2);
                    }
                    foreach (object obj2 in channelData.ServerProviders)
                    {
                        ProviderData providerData = (ProviderData)obj2;
                        if (providerData.Ref != null)
{
                            ProviderData providerData2 = (ProviderData)RemotingConfiguration.serverProviderTemplates[providerData.Ref];
                            if (providerData2 == null)
{
                                throw new RemotingException("Provider template '" + providerData.Ref + "' not found");
                            }
                            providerData.CopyFrom(providerData2);
                        }
                    }
                    foreach (object obj3 in channelData.ClientProviders)
                    {
                        ProviderData providerData3 = (ProviderData)obj3;
                        if (providerData3.Ref != null)
{
                            ProviderData providerData4 = (ProviderData)RemotingConfiguration.clientProviderTemplates[providerData3.Ref];
                            if (providerData4 == null)
{
                                throw new RemotingException("Provider template '" + providerData3.Ref + "' not found");
                            }
                            providerData3.CopyFrom(providerData4);
                        }
                    }
                    ChannelServices.RegisterChannelConfig(channelData);
                }
            }
        }
References System.Runtime.Remoting.RemotingConfiguration.channelTemplates, System.Runtime.Remoting.ChannelData.ClientProviders, System.Runtime.Remoting.RemotingConfiguration.clientProviderTemplates, System.Runtime.Remoting.ChannelData.CopyFrom(), System.Runtime.Remoting.ProviderData.CopyFrom(), System.Runtime.Remoting.ChannelData.DelayLoadAsClientChannel, System.obj, System.Runtime.Remoting.ChannelData.Ref, System.Runtime.Remoting.ProviderData.Ref, System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig(), System.Runtime.Remoting.ChannelData.ServerProviders, and System.Runtime.Remoting.RemotingConfiguration.serverProviderTemplates.
Referenced by System.Runtime.Remoting.ConfigHandler.OnEndParsing().