Terraria Decompiled: System.Runtime.Remoting.RemotingConfiguration.Configure
Configure() [2/2]
static void System.Runtime.Remoting.RemotingConfiguration.Configure (string filename, bool ensureSecurity) inline static
Definition at line 73 of file RemotingConfiguration.cs.
        {
            Hashtable hashtable = RemotingConfiguration.channelTemplates;
            lock (hashtable)
            {
                if (!RemotingConfiguration.defaultConfigRead)
                {
                    string bundledMachineConfig = Environment.GetBundledMachineConfig();
                    if (bundledMachineConfig != null)
                    {
                        RemotingConfiguration.ReadConfigString(bundledMachineConfig);
                    }
                    if (File.Exists(Environment.GetMachineConfigPath()))
                    {
                        RemotingConfiguration.ReadConfigFile(Environment.GetMachineConfigPath());
                    }
                    RemotingConfiguration.defaultConfigRead = true;
                }
                if (filename != null)
                {
                    RemotingConfiguration.ReadConfigFile(filename);
                }
            }
        }
References System.Runtime.Remoting.RemotingConfiguration.channelTemplates, System.Runtime.Remoting.RemotingConfiguration.defaultConfigRead, System.IO.File.Exists(), System.Runtime.Remoting.RemotingConfiguration.ReadConfigFile(), and System.Runtime.Remoting.RemotingConfiguration.ReadConfigString().
Referenced by System.Runtime.Remoting.RemotingConfiguration.Configure().