Terraria Decompiled: SDL3.SDL.EncodeAsUTF8
EncodeAsUTF8()
static unsafe byte * SDL3.SDL.EncodeAsUTF8 (string str) inline static private
Definition at line 12 of file SDL.cs.
        {
            if (str == null)
            {
                return null;
            }
            int num = str.Length * 4 + 1;
            byte* ptr = (byte*)(void*)SDL.SDL_malloc((UIntPtr)((ulong)((long)num)));
            fixed (string text = str)
            {
                char* ptr2 = text;
                if (ptr2 != null)
                {
                    ptr2 += RuntimeHelpers.OffsetToStringData / 2;
                }
                Encoding.UTF8.GetBytes(ptr2, str.Length + 1, ptr, num);
            }
            return ptr;
        }
References System.Text.Encoding.GetBytes(), SDL3.SDL.SDL_malloc(), System.text, and System.Text.Encoding.UTF8.
Referenced by SDL3.SDL.SDL_AddGamepadMapping(), SDL3.SDL.SDL_AddGamepadMappingsFromFile(), SDL3.SDL.SDL_AddHintCallback(), SDL3.SDL.SDL_AsyncIOFromFile(), SDL3.SDL.SDL_ClearProperty(), SDL3.SDL.SDL_CopyFile(), SDL3.SDL.SDL_CopyStorageFile(), SDL3.SDL.SDL_CreateDirectory(), SDL3.SDL.SDL_CreateGPUDevice(), SDL3.SDL.SDL_CreateRenderer(), SDL3.SDL.SDL_CreateStorageDirectory(), SDL3.SDL.SDL_CreateThreadRuntime(), SDL3.SDL.SDL_CreateTray(), SDL3.SDL.SDL_CreateWindow(), SDL3.SDL.SDL_CreateWindowAndRenderer(), SDL3.SDL.SDL_EGL_GetProcAddress(), SDL3.SDL.SDL_EnumerateDirectory(), SDL3.SDL.SDL_EnumerateStorageDirectory(), SDL3.SDL.SDL_GetAppMetadataProperty(), SDL3.SDL.SDL_GetBooleanProperty(), SDL3.SDL.SDL_GetClipboardData(), SDL3.SDL.SDL_GetEventDescription(), SDL3.SDL.SDL_GetFloatProperty(), SDL3.SDL.SDL_GetGamepadAxisFromString(), SDL3.SDL.SDL_GetGamepadButtonFromString(), SDL3.SDL.SDL_GetGamepadTypeFromString(), SDL3.SDL.SDL_GetHint(), SDL3.SDL.SDL_GetHintBoolean(), SDL3.SDL.SDL_GetKeyFromName(), SDL3.SDL.SDL_GetNumberProperty(), SDL3.SDL.SDL_GetPathInfo(), SDL3.SDL.SDL_GetPointerProperty(), SDL3.SDL.SDL_GetPrefPath(), SDL3.SDL.SDL_GetPropertyType(), SDL3.SDL.SDL_GetScancodeFromName(), SDL3.SDL.SDL_GetStorageFileSize(), SDL3.SDL.SDL_GetStoragePathInfo(), SDL3.SDL.SDL_GetStringProperty(), SDL3.SDL.SDL_GL_ExtensionSupported(), SDL3.SDL.SDL_GL_GetProcAddress(), SDL3.SDL.SDL_GL_LoadLibrary(), SDL3.SDL.SDL_GlobDirectory(), SDL3.SDL.SDL_GlobStorageDirectory(), SDL3.SDL.SDL_GPUSupportsShaderFormats(), SDL3.SDL.SDL_GUIDToString(), SDL3.SDL.SDL_HasClipboardData(), SDL3.SDL.SDL_HasProperty(), SDL3.SDL.SDL_hid_get_indexed_string(), SDL3.SDL.SDL_hid_get_manufacturer_string(), SDL3.SDL.SDL_hid_get_product_string(), SDL3.SDL.SDL_hid_get_serial_number_string(), SDL3.SDL.SDL_hid_open(), SDL3.SDL.SDL_hid_open_path(), SDL3.SDL.SDL_InsertGPUDebugLabel(), SDL3.SDL.SDL_InsertTrayEntryAt(), SDL3.SDL.SDL_IOFromFile(), SDL3.SDL.SDL_IOprintf(), SDL3.SDL.SDL_LoadBMP(), SDL3.SDL.SDL_LoadFile(), SDL3.SDL.SDL_LoadFileAsync(), SDL3.SDL.SDL_LoadFunction(), SDL3.SDL.SDL_LoadObject(), SDL3.SDL.SDL_LoadPNG(), SDL3.SDL.SDL_LoadSurface(), SDL3.SDL.SDL_LoadWAV(), SDL3.SDL.SDL_Log(), SDL3.SDL.SDL_LogCritical(), SDL3.SDL.SDL_LogDebug(), SDL3.SDL.SDL_LogError(), SDL3.SDL.SDL_LogInfo(), SDL3.SDL.SDL_LogMessage(), SDL3.SDL.SDL_LogTrace(), SDL3.SDL.SDL_LogVerbose(), SDL3.SDL.SDL_LogWarn(), SDL3.SDL.SDL_OpenFileStorage(), SDL3.SDL.SDL_OpenTitleStorage(), SDL3.SDL.SDL_OpenURL(), SDL3.SDL.SDL_OpenUserStorage(), SDL3.SDL.SDL_PushGPUDebugGroup(), SDL3.SDL.SDL_ReadStorageFile(), SDL3.SDL.SDL_RemoveHintCallback(), SDL3.SDL.SDL_RemovePath(), SDL3.SDL.SDL_RemoveStoragePath(), SDL3.SDL.SDL_RenamePath(), SDL3.SDL.SDL_RenameStoragePath(), SDL3.SDL.SDL_RenderDebugText(), SDL3.SDL.SDL_RenderDebugTextFormat(), SDL3.SDL.SDL_ReportAssertion(), SDL3.SDL.SDL_ResetHint(), SDL3.SDL.SDL_SaveBMP(), SDL3.SDL.SDL_SaveFile(), SDL3.SDL.SDL_SavePNG(), SDL3.SDL.SDL_SetAppMetadata(), SDL3.SDL.SDL_SetAppMetadataProperty(), SDL3.SDL.SDL_SetBooleanProperty(), SDL3.SDL.SDL_SetClipboardText(), SDL3.SDL.SDL_SetError(), SDL3.SDL.SDL_SetFloatProperty(), SDL3.SDL.SDL_SetGamepadMapping(), SDL3.SDL.SDL_SetGPUBufferName(), SDL3.SDL.SDL_SetGPUTextureName(), SDL3.SDL.SDL_SetHint(), SDL3.SDL.SDL_SetHintWithPriority(), SDL3.SDL.SDL_SetLogPriorityPrefix(), SDL3.SDL.SDL_SetNumberProperty(), SDL3.SDL.SDL_SetPointerProperty(), SDL3.SDL.SDL_SetPointerPropertyWithCleanup(), SDL3.SDL.SDL_SetPrimarySelectionText(), SDL3.SDL.SDL_SetScancodeName(), SDL3.SDL.SDL_SetStringProperty(), SDL3.SDL.SDL_SetTrayEntryLabel(), SDL3.SDL.SDL_SetTrayTooltip(), SDL3.SDL.SDL_SetWindowTitle(), SDL3.SDL.SDL_ShowOpenFileDialog(), SDL3.SDL.SDL_ShowOpenFolderDialog(), SDL3.SDL.SDL_ShowSaveFileDialog(), SDL3.SDL.SDL_ShowSimpleMessageBox(), SDL3.SDL.SDL_StringToGUID(), and SDL3.SDL.SDL_WriteStorageFile().