Terraria Decompiled: SDL3.SDL.DecodeFromUTF8
DecodeFromUTF8()
static unsafe string SDL3.SDL.DecodeFromUTF8 (IntPtr ptr, bool shouldFree = false) inline static private
Definition at line 33 of file SDL.cs.
        {
            if (ptr == IntPtr.Zero)
            {
                return null;
            }
            byte* ptr2 = (byte*)(void*)ptr;
            while (*ptr2 != 0)
            {
                ptr2++;
            }
            string text = new string((sbyte*)(void*)ptr, 0, (int)((long)((byte*)ptr2 - (byte*)(void*)ptr)), Encoding.UTF8);
            if (shouldFree)
            {
                SDL.SDL_free(ptr);
            }
            return text;
        }
References SDL3.SDL.SDL_free(), System.text, System.Text.Encoding.UTF8, and System.IntPtr.Zero.
Referenced by SDL3.SDL.SDL_GetAppMetadataProperty(), SDL3.SDL.SDL_GetAudioDeviceName(), SDL3.SDL.SDL_GetAudioDriver(), SDL3.SDL.SDL_GetAudioFormatName(), SDL3.SDL.SDL_GetBasePath(), SDL3.SDL.SDL_GetCameraDriver(), SDL3.SDL.SDL_GetCameraName(), SDL3.SDL.SDL_GetClipboardText(), SDL3.SDL.SDL_GetCurrentAudioDriver(), SDL3.SDL.SDL_GetCurrentCameraDriver(), SDL3.SDL.SDL_GetCurrentDirectory(), SDL3.SDL.SDL_GetCurrentVideoDriver(), SDL3.SDL.SDL_GetDisplayName(), SDL3.SDL.SDL_GetError(), SDL3.SDL.SDL_GetGamepadAppleSFSymbolsNameForAxis(), SDL3.SDL.SDL_GetGamepadAppleSFSymbolsNameForButton(), SDL3.SDL.SDL_GetGamepadMapping(), SDL3.SDL.SDL_GetGamepadMappingForGUID(), SDL3.SDL.SDL_GetGamepadMappingForID(), SDL3.SDL.SDL_GetGamepadName(), SDL3.SDL.SDL_GetGamepadNameForID(), SDL3.SDL.SDL_GetGamepadPath(), SDL3.SDL.SDL_GetGamepadPathForID(), SDL3.SDL.SDL_GetGamepadSerial(), SDL3.SDL.SDL_GetGamepadStringForAxis(), SDL3.SDL.SDL_GetGamepadStringForButton(), SDL3.SDL.SDL_GetGamepadStringForType(), SDL3.SDL.SDL_GetGPUDeviceDriver(), SDL3.SDL.SDL_GetGPUDriver(), SDL3.SDL.SDL_GetHapticName(), SDL3.SDL.SDL_GetHapticNameForID(), SDL3.SDL.SDL_GetHint(), SDL3.SDL.SDL_GetJoystickName(), SDL3.SDL.SDL_GetJoystickNameForID(), SDL3.SDL.SDL_GetJoystickPath(), SDL3.SDL.SDL_GetJoystickPathForID(), SDL3.SDL.SDL_GetJoystickSerial(), SDL3.SDL.SDL_GetKeyboardNameForID(), SDL3.SDL.SDL_GetKeyName(), SDL3.SDL.SDL_GetMouseNameForID(), SDL3.SDL.SDL_GetPixelFormatName(), SDL3.SDL.SDL_GetPlatform(), SDL3.SDL.SDL_GetPrefPath(), SDL3.SDL.SDL_GetPrimarySelectionText(), SDL3.SDL.SDL_GetRenderDriver(), SDL3.SDL.SDL_GetRendererName(), SDL3.SDL.SDL_GetRevision(), SDL3.SDL.SDL_GetScancodeName(), SDL3.SDL.SDL_GetSensorName(), SDL3.SDL.SDL_GetSensorNameForID(), SDL3.SDL.SDL_GetStringProperty(), SDL3.SDL.SDL_GetThreadName(), SDL3.SDL.SDL_GetTouchDeviceName(), SDL3.SDL.SDL_GetTrayEntryLabel(), SDL3.SDL.SDL_GetUserFolder(), SDL3.SDL.SDL_GetVideoDriver(), and SDL3.SDL.SDL_GetWindowTitle().