Terraria Decompiled: SDL3.SDL.SDL_SetHintWithPriority
SDL_SetHintWithPriority()
static unsafe SDL.SDLBool SDL3.SDL.SDL_SetHintWithPriority (string name, string value, SDL::SDL_HintPriority priority) inline static
Definition at line 4369 of file SDL.cs.
        {
            byte* ptr = SDL.EncodeAsUTF8(name);
            byte* ptr2 = SDL.EncodeAsUTF8(value);
            SDL.SDLBool sdlbool = SDL.INTERNAL_SDL_SetHintWithPriority(ptr, ptr2, priority);
            SDL.SDL_free((IntPtr)((void*)ptr));
            SDL.SDL_free((IntPtr)((void*)ptr2));
            return sdlbool;
        }
References SDL3.SDL.EncodeAsUTF8(), SDL3.SDL.INTERNAL_SDL_SetHintWithPriority(), System.name, SDL3.SDL.SDL_free(), and System.value.
Referenced by Microsoft.Xna.Framework.SDL3_FNAPlatform.DisposeWindow(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.SetEnv().