Terraria Decompiled: Terraria.Chat.ChatHelper.DisplayMessageOnClient
DisplayMessageOnClient()
static void Terraria.Chat.ChatHelper.DisplayMessageOnClient (NetworkText text, Color color, int playerId) inline static
Definition at line 15 of file ChatHelper.cs.
        {
            if (Main.dedServ)
            {
                NetPacket netPacket = NetTextModule.SerializeServerMessage(text, color, byte.MaxValue);
                NetManager.Instance.SendToClient(netPacket, playerId);
                return;
            }
            ChatHelper.DisplayMessage(text, color, byte.MaxValue);
        }
References Terraria.Main.dedServ, Terraria.Chat.ChatHelper.DisplayMessage(), Terraria.Net.NetManager.Instance, Terraria.Net.NetManager.SendToClient(), Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage(), and System.text.
Referenced by Terraria.Testing.ChatCommands.DebugMessage.DisplayMessage().