Terraria Decompiled: Terraria.Chat.ChatHelper.BroadcastChatMessageAs
BroadcastChatMessageAs()
static void Terraria.Chat.ChatHelper.BroadcastChatMessageAs (byte messageAuthor, NetworkText text, Color color, int excludedPlayer = -1) inline static
Definition at line 53 of file ChatHelper.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            if (Main.dedServ)
            {
                NetPacket netPacket = NetTextModule.SerializeServerMessage(text, color, messageAuthor);
                NetManager.Instance.Broadcast(netPacket, new NetManager.BroadcastCondition(ChatHelper.OnlySendToPlayersWhoAreLoggedIn), excludedPlayer);
                return;
            }
            if (excludedPlayer != Main.myPlayer)
            {
                ChatHelper.DisplayMessage(text, color, messageAuthor);
            }
        }
References Terraria.Net.NetManager.Broadcast(), Terraria.Net.NetManager.BroadcastCondition(), Terraria.Main.dedServ, Terraria.Chat.ChatHelper.DisplayMessage(), Terraria.Net.NetManager.Instance, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Chat.ChatHelper.OnlySendToPlayersWhoAreLoggedIn(), Terraria.GameContent.NetModules.NetTextModule.SerializeServerMessage(), and System.text.
Referenced by Terraria.Chat.ChatHelper.BroadcastChatMessage(), and Terraria.Chat.Commands.SayChatCommand.ProcessIncomingMessage().