Terraria Decompiled: Terraria.Testing.ChatCommands.DebugCommandProcessor.Process
Process() [2/2]
bool Terraria.Testing.ChatCommands.DebugCommandProcessor.Process (DebugMessage message) inline
Definition at line 64 of file DebugCommandProcessor.cs.
        {
            if (!DebugOptions.enableDebugCommands && !message.CommandName.Equals("toggledebugcommands"))
            {
                return false;
            }
            IDebugCommand debugCommand;
            if (!this._commands.TryGetValue(message.CommandName, out debugCommand))
            {
                return (int)message.Author == Main.myPlayer && this.TryProcessMemo(message);
            }
            if ((debugCommand.Requirements & CommandRequirement.MultiplayerRPC) != (CommandRequirement)0 && Main.netMode == 1)
            {
                NetPacket netPacket = NetDebugModule.Serialize(message);
                NetManager.Instance.SendToServer(netPacket);
                return true;
            }
            if (!DebugCommandProcessor.CanRunCommandLocally((int)message.Author, debugCommand.Requirements))
            {
                return false;
            }
            bool flag = debugCommand.Process(message);
            if (!flag && debugCommand.HelpText != null)
            {
                message.Reply(debugCommand.HelpText);
            }
            if ((DebugOptions.Shared_ReportCommandUsage || debugCommand.Name == "showdebug") && flag && Main.netMode != 0)
            {
                string text = ((message.Author == byte.MaxValue) ? "server" : Main.player[(int)message.Author].name);
                string text2 = string.Format("{0} debugged: /{1} {2}", text, message.CommandName, message.Arguments);
                if (Main.netMode != 1)
                {
                    ChatHelper.BroadcastChatMessage(NetworkText.FromLiteral(text2), new Color(250, 250, 0), -1);
                }
                else
                {
                    ChatHelper.SendChatMessageFromClient(new ChatMessage(text2));
                }
            }
            return true;
        }
References Terraria.Testing.ChatCommands.DebugCommandProcessor._commands, Terraria.Testing.ChatCommands.DebugMessage.Arguments, Terraria.Testing.ChatCommands.DebugMessage.Author, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Testing.ChatCommands.DebugCommandProcessor.CanRunCommandLocally(), Terraria.Testing.ChatCommands.DebugMessage.CommandName, Terraria.Testing.DebugOptions.enableDebugCommands, Terraria.Localization.NetworkText.FromLiteral(), Terraria.Testing.ChatCommands.IDebugCommand.HelpText, Terraria.Net.NetManager.Instance, int, Terraria.Player.name, Terraria.Testing.ChatCommands.IDebugCommand.Name, Terraria.Main.netMode, Terraria.Main.player, Terraria.Testing.ChatCommands.IDebugCommand.Process(), Terraria.Testing.ChatCommands.DebugMessage.Reply(), Terraria.Testing.ChatCommands.IDebugCommand.Requirements, Terraria.Chat.ChatHelper.SendChatMessageFromClient(), Terraria.Net.NetManager.SendToServer(), Terraria.GameContent.NetModules.NetDebugModule.Serialize(), Terraria.Testing.DebugOptions.Shared_ReportCommandUsage, System.text, and Terraria.Testing.ChatCommands.DebugCommandProcessor.TryProcessMemo().