Terraria Decompiled: Steamworks.ISteamMatchmakingPingResponse.ISteamMatchmakingPingResponse
ISteamMatchmakingPingResponse()
Steamworks.ISteamMatchmakingPingResponse.ISteamMatchmakingPingResponse (ISteamMatchmakingPingResponse::ServerResponded onServerResponded, ISteamMatchmakingPingResponse::ServerFailedToRespond onServerFailedToRespond) inline
Definition at line 10 of file ISteamMatchmakingPingResponse.cs.
        {
            if (onServerResponded == null || onServerFailedToRespond == null)
            {
                throw new ArgumentNullException();
            }
            this.m_ServerResponded = onServerResponded;
            this.m_ServerFailedToRespond = onServerFailedToRespond;
            this.m_VTable = new ISteamMatchmakingPingResponse.VTable
            {
                m_VTServerResponded = new ISteamMatchmakingPingResponse.InternalServerResponded(this.InternalOnServerResponded),
                m_VTServerFailedToRespond = new ISteamMatchmakingPingResponse.InternalServerFailedToRespond(this.InternalOnServerFailedToRespond)
            };
            this.m_pVTable = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(ISteamMatchmakingPingResponse.VTable)));
            Marshal.StructureToPtr(this.m_VTable, this.m_pVTable, false);
            this.m_pGCHandle = GCHandle.Alloc(this.m_pVTable, 3);
        }
References System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), Steamworks.ISteamMatchmakingPingResponse.InternalOnServerFailedToRespond(), Steamworks.ISteamMatchmakingPingResponse.InternalOnServerResponded(), Steamworks.ISteamMatchmakingPingResponse.InternalServerFailedToRespond(), Steamworks.ISteamMatchmakingPingResponse.InternalServerResponded(), Steamworks.ISteamMatchmakingPingResponse.m_pVTable, Steamworks.ISteamMatchmakingPingResponse.m_VTable, System.Runtime.InteropServices.Marshal.SizeOf(), and System.Runtime.InteropServices.Marshal.StructureToPtr().