Terraria Decompiled: Microsoft.Win32.RegistryKey.CreateSubKey
CreateSubKey() [5/7]
RegistryKey Microsoft.Win32.RegistryKey.CreateSubKey (string subkey, RegistryKeyPermissionCheck permissionCheck, RegistryOptions options) inline
Definition at line 261 of file RegistryKey.cs.
        {
            this.AssertKeyStillValid();
            this.AssertKeyNameNotNull(subkey);
            this.AssertKeyNameLength(subkey);
            if (!this.IsWritable)
            {
                throw new UnauthorizedAccessException("Cannot write to the registry key.");
            }
            return RegistryKey.RegistryApi.CreateSubKey(this, subkey, options);
        }
References Microsoft.Win32.RegistryKey.AssertKeyNameLength(), Microsoft.Win32.RegistryKey.AssertKeyNameNotNull(), Microsoft.Win32.RegistryKey.AssertKeyStillValid(), Microsoft.Win32.IRegistryApi.CreateSubKey(), Microsoft.Win32.RegistryKey.IsWritable, System.options, and Microsoft.Win32.RegistryKey.RegistryApi.