Terraria Decompiled: Microsoft.Win32.RegistryKey.Close
Close()
void Microsoft.Win32.RegistryKey.Close () inline
Definition at line 80 of file RegistryKey.cs.
        {
            this.Flush();
            if (!this.isRemoteRoot && this.IsRoot)
            {
                return;
            }
            RegistryKey.RegistryApi.Close(this);
            this.handle = null;
            this.safe_handle = null;
        }
References Microsoft.Win32.IRegistryApi.Close(), Microsoft.Win32.RegistryKey.Flush(), Microsoft.Win32.RegistryKey.isRemoteRoot, Microsoft.Win32.RegistryKey.IsRoot, and Microsoft.Win32.RegistryKey.RegistryApi.
Referenced by Microsoft.Win32.RegistryKey.DeleteChildKeysAndValues(), Microsoft.Win32.RegistryKey.DeleteSubKey(), Microsoft.Win32.RegistryKey.DeleteSubKeyTree(), and Microsoft.Win32.RegistryKey.Dispose().