Terraria Decompiled: Microsoft.Win32.RegistryKey.SetValue
SetValue() [1/2]
void Microsoft.Win32.RegistryKey.SetValue (string name, object value) inline
Definition at line 145 of file RegistryKey.cs.
        {
            this.AssertKeyStillValid();
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            if (name != null)
            {
                this.AssertKeyNameLength(name);
            }
            if (!this.IsWritable)
            {
                throw new UnauthorizedAccessException("Cannot write to the registry key.");
            }
            RegistryKey.RegistryApi.SetValue(this, name, value);
        }
References Microsoft.Win32.RegistryKey.AssertKeyNameLength(), Microsoft.Win32.RegistryKey.AssertKeyStillValid(), Microsoft.Win32.RegistryKey.IsWritable, System.name, Microsoft.Win32.RegistryKey.RegistryApi, Microsoft.Win32.IRegistryApi.SetValue(), and System.value.
Referenced by Microsoft.Win32.Registry.SetValue(), and Microsoft.Win32.Registry.SetValue().