Terraria Decompiled: System.Collections.Generic.Dictionary.KeyCollection.CopyTo
CopyTo() [1/2]
void ICollection. System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo (Array array, int index) inline private
Definition at line 1418 of file Dictionary.cs.
            {
                if (array == null)
                {
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
                }
                if (array.Rank != 1)
                {
                    ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_RankMultiDimNotSupported);
                }
                if (array.GetLowerBound(0) != 0)
                {
                    ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_NonZeroLowerBound);
                }
                if (index > array.Length)
                {
                    ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
                }
                if (array.Length - index < this._dictionary.Count)
                {
                    ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall);
                }
                TKey[] array2 = array as TKey[];
                if (array2 != null)
                {
                    this.CopyTo(array2, index);
                    return;
                }
                object[] array3 = array as object[];
                if (array3 == null)
                {
                    ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
                }
                int count = this._dictionary._count;
                Dictionary<TKey, TValue>.Entry[] entries = this._dictionary._entries;
                try
                {
                    for (int i = 0; i < count; i++)
                    {
                        if (entries[i].hashCode >= 0)
{
                            array3[index++] = entries[i].key;
                        }
                    }
                }
                catch (ArrayTypeMismatchException)
                {
                    ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType();
                }
            }
References System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection._dictionary, System.array, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo(), System.count, System.index, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentException_Argument_InvalidArrayType(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException().