Terraria Decompiled: Microsoft.Win32.RegistryKey.DeleteChildKeysAndValues
DeleteChildKeysAndValues()
void Microsoft.Win32.RegistryKey.DeleteChildKeysAndValues () inline private
Definition at line 589 of file RegistryKey.cs.
        {
            if (this.IsRoot)
            {
                return;
            }
            foreach (string text in this.GetSubKeyNames())
            {
                RegistryKey registryKey = this.OpenSubKey(text, true);
                registryKey.DeleteChildKeysAndValues();
                registryKey.Close();
                this.DeleteSubKey(text, false);
            }
            foreach (string text2 in this.GetValueNames())
            {
                this.DeleteValue(text2, false);
            }
        }
References Microsoft.Win32.RegistryKey.Close(), Microsoft.Win32.RegistryKey.DeleteChildKeysAndValues(), Microsoft.Win32.RegistryKey.DeleteSubKey(), Microsoft.Win32.RegistryKey.DeleteValue(), Microsoft.Win32.RegistryKey.GetSubKeyNames(), Microsoft.Win32.RegistryKey.GetValueNames(), Microsoft.Win32.RegistryKey.IsRoot, Microsoft.Win32.RegistryKey.OpenSubKey(), and System.text.
Referenced by Microsoft.Win32.RegistryKey.DeleteChildKeysAndValues(), and Microsoft.Win32.RegistryKey.DeleteSubKeyTree().