Terraria Decompiled: System.Collections.Generic.Dictionary.KeyCollection.CopyTo
CopyTo() [2/2]
void System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo (TKey[] array, int index) inline
Definition at line 1335 of file Dictionary.cs.
            {
                if (array == null)
                {
                    ThrowHelper.ThrowArgumentNullException(ExceptionArgument.array);
                }
                if (index < 0 || index > array.Length)
                {
                    ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException();
                }
                if (array.Length - index < this._dictionary.Count)
                {
                    ThrowHelper.ThrowArgumentException(ExceptionResource.Arg_ArrayPlusOffTooSmall);
                }
                int count = this._dictionary._count;
                Dictionary<TKey, TValue>.Entry[] entries = this._dictionary._entries;
                for (int i = 0; i < count; i++)
                {
                    if (entries[i].hashCode >= 0)
                    {
                        array[index++] = entries[i].key;
                    }
                }
            }
References System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection._dictionary, System.array, System.count, System.index, System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentNullException(), and System.ThrowHelper.ThrowIndexArgumentOutOfRange_NeedNonNegNumException().
Referenced by System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection.CopyTo().