Terraria Decompiled: Terraria.Social.Steam.SteamP2PReader.ClearUser
ClearUser()
void Terraria.Social.Steam.SteamP2PReader.ClearUser (CSteamID id) inline
Definition at line 17 of file SteamP2PReader.cs.
        {
            Dictionary<CSteamID, Queue<SteamP2PReader.ReadResult>> pendingReadBuffers = this._pendingReadBuffers;
            lock (pendingReadBuffers)
            {
                this._deletionQueue.Enqueue(id);
            }
        }
References Terraria.Social.Steam.SteamP2PReader._deletionQueue, Terraria.Social.Steam.SteamP2PReader._pendingReadBuffers, and System.Collections.Generic.Queue< T >.Enqueue().
Referenced by Terraria.Social.Steam.NetClientSocialModule.Close(), and Terraria.Social.Steam.NetServerSocialModule.Close().