Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints () inline private
Definition at line 452 of file UICreativePowersMenu.cs.
        {
            int num = 10000;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            List<SnapPoint> orderedPointsByCategoryName = this._helper.GetOrderedPointsByCategoryName(snapPoints, "strip 0");
            List<SnapPoint> orderedPointsByCategoryName2 = this._helper.GetOrderedPointsByCategoryName(snapPoints, "strip 1");
            List<SnapPoint> orderedPointsByCategoryName3 = this._helper.GetOrderedPointsByCategoryName(snapPoints, "strip 2");
            UILinkPoint[] array = null;
            UILinkPoint[] array2 = null;
            UILinkPoint[] array3 = null;
            if (orderedPointsByCategoryName.Count > 0)
            {
                array = this._helper.CreateUILinkStripVertical(ref num, orderedPointsByCategoryName);
            }
            if (orderedPointsByCategoryName2.Count > 0)
            {
                array2 = this._helper.CreateUILinkStripVertical(ref num, orderedPointsByCategoryName2);
            }
            if (orderedPointsByCategoryName3.Count > 0)
            {
                array3 = this._helper.CreateUILinkStripVertical(ref num, orderedPointsByCategoryName3);
            }
            if (array != null && array2 != null)
            {
                this._helper.LinkVerticalStrips(array, array2, (array.Length - array2.Length) / 2);
            }
            if (array2 != null && array3 != null)
            {
                this._helper.LinkVerticalStrips(array2, array3, (array.Length - array2.Length) / 2);
            }
            UILinkPoint uilinkPoint = null;
            UILinkPoint uilinkPoint2 = null;
            for (int i = 0; i < snapPoints.Count; i++)
            {
                SnapPoint snapPoint = snapPoints[i];
                string name = snapPoint.Name;
                if (!(name == "CreativeSacrificeConfirm"))
                {
                    if (name == "CreativeInfinitesSearch")
                    {
                        uilinkPoint2 = this._helper.MakeLinkPointFromSnapPoint(num++, snapPoint);
                    }
                }
                else
                {
                    uilinkPoint = this._helper.MakeLinkPointFromSnapPoint(num++, snapPoint);
                }
            }
            UILinkPoint uilinkPoint3 = UILinkPointNavigator.Points[15000];
            List<SnapPoint> orderedPointsByCategoryName4 = this._helper.GetOrderedPointsByCategoryName(snapPoints, "CreativeInfinitesFilter");
            if (orderedPointsByCategoryName4.Count > 0)
            {
                UILinkPoint[] array4 = this._helper.CreateUILinkStripHorizontal(ref num, orderedPointsByCategoryName4);
                if (uilinkPoint2 != null)
                {
                    uilinkPoint2.Up = array4[0].ID;
                    for (int j = 0; j < array4.Length; j++)
                    {
                        array4[j].Down = uilinkPoint2.ID;
                    }
                }
            }
            List<SnapPoint> orderedPointsByCategoryName5 = this._helper.GetOrderedPointsByCategoryName(snapPoints, "DynamicItemCollectionSlot");
            UILinkPoint[,] array5 = null;
            if (orderedPointsByCategoryName5.Count > 0)
            {
                array5 = this._helper.CreateUILinkPointGrid(ref num, orderedPointsByCategoryName5, this._infiniteItemsWindow.GetItemsPerLine(), uilinkPoint2, array[0], null, null);
                this._helper.LinkVerticalStripRightSideToSingle(array, array5[0, 0]);
            }
            else if (uilinkPoint2 != null)
            {
                this._helper.LinkVerticalStripRightSideToSingle(array, uilinkPoint2);
            }
            if (uilinkPoint2 != null && array5 != null)
            {
                this._helper.PairUpDown(uilinkPoint2, array5[0, 0]);
            }
            if (uilinkPoint3 != null && this.IsShowingResearchMenu)
            {
                this._helper.LinkVerticalStripRightSideToSingle(array, uilinkPoint3);
            }
            if (uilinkPoint != null)
            {
                this._helper.PairUpDown(uilinkPoint3, uilinkPoint);
                uilinkPoint.Left = array[0].ID;
            }
            if (Main.CreativeMenu.GamepadMoveToSearchButtonHack)
            {
                Main.CreativeMenu.GamepadMoveToSearchButtonHack = false;
                if (uilinkPoint2 != null)
                {
                    UILinkPointNavigator.ChangePoint(uilinkPoint2.ID);
                }
            }
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._helper, Terraria.GameContent.UI.States.UICreativePowersMenu._infiniteItemsWindow, System.array, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePoint(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripHorizontal(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripVertical(), Terraria.Main.CreativeMenu, Terraria.UI.Gamepad.UILinkPoint.Down, Terraria.GameContent.Creative.CreativeUI.GamepadMoveToSearchButtonHack, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GetItemsPerLine(), Terraria.GameContent.UI.States.UIGamepadHelper.GetOrderedPointsByCategoryName(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.GameContent.UI.States.UICreativePowersMenu.IsShowingResearchMenu, Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStripRightSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkVerticalStrips(), Terraria.GameContent.UI.States.UIGamepadHelper.MakeLinkPointFromSnapPoint(), System.name, Terraria.UI.SnapPoint.Name, Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown(), and Terraria.UI.Gamepad.UILinkPointNavigator.Points.
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.Draw().