Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip
CreateMainPowerStrip()
List< UIElement > Terraria.GameContent.UI.States.UICreativePowersMenu.CreateMainPowerStrip () inline private
Definition at line 99 of file UICreativePowersMenu.cs.
        {
            UICreativePowersMenu.MenuTree<UICreativePowersMenu.OpenMainSubCategory> mainCategory = this._mainCategory;
            mainCategory.Buttons.Clear();
            List<UIElement> list = new List<UIElement>();
            CreativePowerUIElementRequestInfo creativePowerUIElementRequestInfo = new CreativePowerUIElementRequestInfo
            {
                PreferredButtonWidth = 40,
                PreferredButtonHeight = 40
            };
            GroupOptionButton<int> groupOptionButton = CreativePowersHelper.CreateCategoryButton<int>(creativePowerUIElementRequestInfo, 1, 0);
            groupOptionButton.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.ItemDuplication));
            groupOptionButton.OnLeftClick += this.MainCategoryButtonClick;
            groupOptionButton.OnUpdate += this.itemsWindowButton_OnUpdate;
            mainCategory.Buttons.Add(1, groupOptionButton);
            list.Add(groupOptionButton);
            this._infiniteItemsButton = groupOptionButton;
            GroupOptionButton<int> groupOptionButton2 = CreativePowersHelper.CreateCategoryButton<int>(creativePowerUIElementRequestInfo, 2, 0);
            groupOptionButton2.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.ItemResearch));
            groupOptionButton2.OnLeftClick += this.MainCategoryButtonClick;
            groupOptionButton2.OnUpdate += this.researchWindowButton_OnUpdate;
            mainCategory.Buttons.Add(2, groupOptionButton2);
            list.Add(groupOptionButton2);
            GroupOptionButton<int> groupOptionButton3 = CreativePowersHelper.CreateCategoryButton<int>(creativePowerUIElementRequestInfo, 3, 0);
            groupOptionButton3.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.TimeCategory));
            groupOptionButton3.OnLeftClick += this.MainCategoryButtonClick;
            groupOptionButton3.OnUpdate += this.timeCategoryButton_OnUpdate;
            mainCategory.Buttons.Add(3, groupOptionButton3);
            list.Add(groupOptionButton3);
            GroupOptionButton<int> groupOptionButton4 = CreativePowersHelper.CreateCategoryButton<int>(creativePowerUIElementRequestInfo, 4, 0);
            groupOptionButton4.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.WeatherCategory));
            groupOptionButton4.OnLeftClick += this.MainCategoryButtonClick;
            groupOptionButton4.OnUpdate += this.weatherCategoryButton_OnUpdate;
            mainCategory.Buttons.Add(4, groupOptionButton4);
            list.Add(groupOptionButton4);
            GroupOptionButton<int> groupOptionButton5 = CreativePowersHelper.CreateCategoryButton<int>(creativePowerUIElementRequestInfo, 6, 0);
            groupOptionButton5.Append(CreativePowersHelper.GetIconImage(CreativePowersHelper.CreativePowerIconLocations.PersonalCategory));
            groupOptionButton5.OnLeftClick += this.MainCategoryButtonClick;
            groupOptionButton5.OnUpdate += this.personalCategoryButton_OnUpdate;
            mainCategory.Buttons.Add(6, groupOptionButton5);
            list.Add(groupOptionButton5);
            CreativePowerManager.Instance.GetPower<CreativePowers.StopBiomeSpreadPower>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            GroupOptionButton<int> groupOptionButton6 = this.CreateSubcategoryButton<CreativePowers.DifficultySliderPower>(ref creativePowerUIElementRequestInfo, 1, "strip 1", 5, 0, mainCategory.Buttons, mainCategory.Sliders);
            groupOptionButton6.OnLeftClick += this.MainCategoryButtonClick;
            list.Add(groupOptionButton6);
            return list;
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._mainCategory, System.Collections.Generic.List< T >.Add(), Terraria.UI.UIElement.Append(), Terraria.GameContent.Creative.CreativePowersHelper.GetIconImage(), Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.GameContent.Creative.CreativePowersHelper.CreativePowerIconLocations.ItemDuplication, Terraria.GameContent.Creative.CreativePowersHelper.CreativePowerIconLocations.ItemResearch, Terraria.GameContent.UI.States.UICreativePowersMenu.itemsWindowButton_OnUpdate(), System.list, Terraria.GameContent.UI.States.UICreativePowersMenu.MainCategoryButtonClick(), Terraria.GameContent.Creative.CreativePowersHelper.CreativePowerIconLocations.PersonalCategory, Terraria.GameContent.UI.States.UICreativePowersMenu.personalCategoryButton_OnUpdate(), Terraria.GameContent.UI.States.UICreativePowersMenu.researchWindowButton_OnUpdate(), Terraria.GameContent.Creative.CreativePowersHelper.CreativePowerIconLocations.TimeCategory, Terraria.GameContent.UI.States.UICreativePowersMenu.timeCategoryButton_OnUpdate(), Terraria.GameContent.Creative.CreativePowersHelper.CreativePowerIconLocations.WeatherCategory, and Terraria.GameContent.UI.States.UICreativePowersMenu.weatherCategoryButton_OnUpdate().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage().