Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.CreateWeatherPowerStrip
CreateWeatherPowerStrip()
List< UIElement > Terraria.GameContent.UI.States.UICreativePowersMenu.CreateWeatherPowerStrip () inline private
Definition at line 308 of file UICreativePowersMenu.cs.
        {
            UICreativePowersMenu.MenuTree<UICreativePowersMenu.WeatherSubcategory> weatherCategory = this._weatherCategory;
            List<UIElement> list = new List<UIElement>();
            CreativePowerUIElementRequestInfo creativePowerUIElementRequestInfo = new CreativePowerUIElementRequestInfo
            {
                PreferredButtonWidth = 40,
                PreferredButtonHeight = 40
            };
            GroupOptionButton<int> groupOptionButton = this.CreateSubcategoryButton<CreativePowers.ModifyWindDirectionAndStrength>(ref creativePowerUIElementRequestInfo, 2, "strip 2", 1, 0, weatherCategory.Buttons, weatherCategory.Sliders);
            groupOptionButton.OnLeftClick += this.WeatherCategoryButtonClick;
            list.Add(groupOptionButton);
            CreativePowerManager.Instance.GetPower<CreativePowers.FreezeWindDirectionAndStrength>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            GroupOptionButton<int> groupOptionButton2 = this.CreateSubcategoryButton<CreativePowers.ModifyRainPower>(ref creativePowerUIElementRequestInfo, 2, "strip 2", 2, 0, weatherCategory.Buttons, weatherCategory.Sliders);
            groupOptionButton2.OnLeftClick += this.WeatherCategoryButtonClick;
            list.Add(groupOptionButton2);
            CreativePowerManager.Instance.GetPower<CreativePowers.FreezeRainPower>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            return list;
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._weatherCategory, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Creative.CreativePowerManager.Instance, System.list, and Terraria.GameContent.UI.States.UICreativePowersMenu.WeatherCategoryButtonClick().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage().