Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.CreatePersonalPowerStrip
CreatePersonalPowerStrip()
List< UIElement > Terraria.GameContent.UI.States.UICreativePowersMenu.CreatePersonalPowerStrip () inline private
Definition at line 290 of file UICreativePowersMenu.cs.
        {
            UICreativePowersMenu.MenuTree<UICreativePowersMenu.PersonalSubcategory> personalCategory = this._personalCategory;
            List<UIElement> list = new List<UIElement>();
            CreativePowerUIElementRequestInfo creativePowerUIElementRequestInfo = new CreativePowerUIElementRequestInfo
            {
                PreferredButtonWidth = 40,
                PreferredButtonHeight = 40
            };
            CreativePowerManager.Instance.GetPower<CreativePowers.GodmodePower>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            CreativePowerManager.Instance.GetPower<CreativePowers.FarPlacementRangePower>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            GroupOptionButton<int> groupOptionButton = this.CreateSubcategoryButton<CreativePowers.SpawnRateSliderPerPlayerPower>(ref creativePowerUIElementRequestInfo, 2, "strip 2", 1, 0, personalCategory.Buttons, personalCategory.Sliders);
            groupOptionButton.OnLeftClick += this.PersonalCategoryButtonClick;
            list.Add(groupOptionButton);
            return list;
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._personalCategory, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Creative.CreativePowerManager.Instance, System.list, and Terraria.GameContent.UI.States.UICreativePowersMenu.PersonalCategoryButtonClick().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage().