Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.RefreshElementsOrder
RefreshElementsOrder()
void Terraria.GameContent.UI.States.UICreativePowersMenu.RefreshElementsOrder () inline private
Definition at line 389 of file UICreativePowersMenu.cs.
        {
            this._container.RemoveAllChildren();
            this._container.Append(this._mainPowerStrip);
            UIElement uielement = null;
            UICreativePowersMenu.MenuTree<UICreativePowersMenu.OpenMainSubCategory> mainCategory = this._mainCategory;
            if (mainCategory.Sliders.TryGetValue(mainCategory.CurrentOption, out uielement))
            {
                this._container.Append(uielement);
            }
            if (mainCategory.CurrentOption == 1)
            {
                Main.LocalPlayerCreativeTracker.ItemSacrifices.DismissNewlyUnlockedFromTeamMatesIcon();
                this._infiniteItemsWindow.SetPageTypeToShow(UICreativeInfiniteItemsDisplay.InfiniteItemsDisplayPage.InfiniteItemsPickup);
                this._container.Append(this._infiniteItemsWindow);
            }
            if (mainCategory.CurrentOption == 2)
            {
                this._infiniteItemsWindow.SetPageTypeToShow(UICreativeInfiniteItemsDisplay.InfiniteItemsDisplayPage.InfiniteItemsResearch);
                this._container.Append(this._infiniteItemsWindow);
            }
            if (mainCategory.CurrentOption == 3)
            {
                this._container.Append(this._timePowersStrip);
                UICreativePowersMenu.MenuTree<UICreativePowersMenu.TimeSubcategory> timeCategory = this._timeCategory;
                if (timeCategory.Sliders.TryGetValue(timeCategory.CurrentOption, out uielement))
                {
                    this._container.Append(uielement);
                }
            }
            if (mainCategory.CurrentOption == 4)
            {
                this._container.Append(this._weatherPowersStrip);
                UICreativePowersMenu.MenuTree<UICreativePowersMenu.WeatherSubcategory> weatherCategory = this._weatherCategory;
                if (weatherCategory.Sliders.TryGetValue(weatherCategory.CurrentOption, out uielement))
                {
                    this._container.Append(uielement);
                }
            }
            if (mainCategory.CurrentOption == 6)
            {
                this._container.Append(this._personalPowersStrip);
                UICreativePowersMenu.MenuTree<UICreativePowersMenu.PersonalSubcategory> personalCategory = this._personalCategory;
                if (personalCategory.Sliders.TryGetValue(personalCategory.CurrentOption, out uielement))
                {
                    this._container.Append(uielement);
                }
            }
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._container, Terraria.GameContent.UI.States.UICreativePowersMenu._infiniteItemsWindow, Terraria.GameContent.UI.States.UICreativePowersMenu._mainCategory, Terraria.GameContent.UI.States.UICreativePowersMenu._mainPowerStrip, Terraria.GameContent.UI.States.UICreativePowersMenu._personalCategory, Terraria.GameContent.UI.States.UICreativePowersMenu._personalPowersStrip, Terraria.GameContent.UI.States.UICreativePowersMenu._timeCategory, Terraria.GameContent.UI.States.UICreativePowersMenu._timePowersStrip, Terraria.GameContent.UI.States.UICreativePowersMenu._weatherCategory, Terraria.GameContent.UI.States.UICreativePowersMenu._weatherPowersStrip, Terraria.UI.UIElement.Append(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.DismissNewlyUnlockedFromTeamMatesIcon(), Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, Terraria.Main.LocalPlayerCreativeTracker, Terraria.UI.UIElement.RemoveAllChildren(), and Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.SetPageTypeToShow().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage(), Terraria.GameContent.UI.States.UICreativePowersMenu.MainCategoryButtonClick(), Terraria.GameContent.UI.States.UICreativePowersMenu.PersonalCategoryButtonClick(), Terraria.GameContent.UI.States.UICreativePowersMenu.TimeCategoryButtonClick(), and Terraria.GameContent.UI.States.UICreativePowersMenu.WeatherCategoryButtonClick().