Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.Draw
Draw()
override void Terraria.GameContent.UI.States.UICreativePowersMenu.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 440 of file UICreativePowersMenu.cs.
        {
            base.Draw(spriteBatch);
            if (Main.LocalPlayerCreativeTracker.ItemSacrifices.AnyNewUnlocksFromTeammates)
            {
                Rectangle rectangle = this._infiniteItemsButton.GetDimensions().ToRectangle();
                Utils.DrawNotificationIcon(spriteBatch, rectangle, 1f, false);
            }
            this.SetupGamepadPoints();
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._infiniteItemsButton, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.AnyNewUnlocksFromTeammates, Terraria.Utils.DrawNotificationIcon(), Terraria.UI.UIElement.GetDimensions(), Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, Terraria.Main.LocalPlayerCreativeTracker, Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), and Terraria.UI.CalculatedStyle.ToRectangle().