Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.CreateTimePowerStrip
CreateTimePowerStrip()
List< UIElement > Terraria.GameContent.UI.States.UICreativePowersMenu.CreateTimePowerStrip () inline private
Definition at line 269 of file UICreativePowersMenu.cs.
        {
            UICreativePowersMenu.MenuTree<UICreativePowersMenu.TimeSubcategory> timeCategory = this._timeCategory;
            List<UIElement> list = new List<UIElement>();
            CreativePowerUIElementRequestInfo creativePowerUIElementRequestInfo = new CreativePowerUIElementRequestInfo
            {
                PreferredButtonWidth = 40,
                PreferredButtonHeight = 40
            };
            CreativePowerManager.Instance.GetPower<CreativePowers.FreezeTime>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            CreativePowerManager.Instance.GetPower<CreativePowers.StartDayImmediately>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            CreativePowerManager.Instance.GetPower<CreativePowers.StartNoonImmediately>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            CreativePowerManager.Instance.GetPower<CreativePowers.StartNightImmediately>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            CreativePowerManager.Instance.GetPower<CreativePowers.StartMidnightImmediately>().ProvidePowerButtons(creativePowerUIElementRequestInfo, list);
            GroupOptionButton<int> groupOptionButton = this.CreateSubcategoryButton<CreativePowers.ModifyTimeRate>(ref creativePowerUIElementRequestInfo, 2, "strip 2", 1, 0, timeCategory.Buttons, timeCategory.Sliders);
            groupOptionButton.OnLeftClick += this.TimeCategoryButtonClick;
            list.Add(groupOptionButton);
            return list;
        }
References Terraria.GameContent.UI.States.UICreativePowersMenu._timeCategory, System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Creative.CreativePowerManager.Instance, System.list, and Terraria.GameContent.UI.States.UICreativePowersMenu.TimeCategoryButtonClick().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.InitializePage().