Terraria Decompiled: Terraria.GameContent.UI.States.UICreativePowersMenu.TimeCategoryButtonClick
TimeCategoryButtonClick()
void Terraria.GameContent.UI.States.UICreativePowersMenu.TimeCategoryButtonClick (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 363 of file UICreativePowersMenu.cs.
        {
            GroupOptionButton<int> groupOptionButton = listeningElement as GroupOptionButton<int>;
            int optionValue = groupOptionButton.OptionValue;
            if (optionValue == 1 && !CreativePowerManager.Instance.GetPower<CreativePowers.ModifyTimeRate>().GetIsUnlocked())
            {
                return;
            }
            this.ToggleTimeCategory(groupOptionButton.OptionValue);
            this.RefreshElementsOrder();
        }
References Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.GetIsUnlocked(), Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.OptionValue, Terraria.GameContent.UI.States.UICreativePowersMenu.RefreshElementsOrder(), and Terraria.GameContent.UI.States.UICreativePowersMenu.ToggleTimeCategory().
Referenced by Terraria.GameContent.UI.States.UICreativePowersMenu.CreateTimePowerStrip().