Terraria Decompiled: System.Security.HostSecurityManager.DetermineApplicationTrust
DetermineApplicationTrust()
virtual ApplicationTrust System.Security.HostSecurityManager.DetermineApplicationTrust (Evidence applicationEvidence, Evidence activatorEvidence, TrustManagerContext context) inline virtual
Definition at line 40 of file HostSecurityManager.cs.
        {
            if (applicationEvidence == null)
            {
                throw new ArgumentNullException("applicationEvidence");
            }
            ActivationArguments activationArguments = null;
            foreach (object obj in applicationEvidence)
            {
                activationArguments = obj as ActivationArguments;
                if (activationArguments != null)
                {
                    break;
                }
            }
            if (activationArguments == null)
            {
                throw new ArgumentException(string.Format(Locale.GetText("No {0} found in {1}."), "ActivationArguments", "Evidence"), "applicationEvidence");
            }
            if (activationArguments.ActivationContext == null)
            {
                throw new ArgumentException(string.Format(Locale.GetText("No {0} found in {1}."), "ActivationContext", "ActivationArguments"), "applicationEvidence");
            }
            if (!ApplicationSecurityManager.DetermineApplicationTrust(activationArguments.ActivationContext, context))
            {
                return null;
            }
            if (activationArguments.ApplicationIdentity == null)
            {
                return new ApplicationTrust();
            }
            return new ApplicationTrust(activationArguments.ApplicationIdentity);
        }
References System.Security.Policy.ApplicationSecurityManager.DetermineApplicationTrust(), System.Security.Format, Locale.GetText(), and System.obj.
Referenced by System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper().