Terraria Decompiled: System.Security.Policy.ApplicationTrust.FromXml
FromXml()
void System.Security.Policy.ApplicationTrust.FromXml (SecurityElement element) inline
Implements System.Security.ISecurityEncodable.
Definition at line 140 of file ApplicationTrust.cs.
        {
            if (element == null)
            {
                throw new ArgumentNullException("element");
            }
            if (element.Tag != "ApplicationTrust")
            {
                throw new ArgumentException("element");
            }
            string text = element.Attribute("FullName");
            if (text != null)
            {
                this._appid = new ApplicationIdentity(text);
            }
            else
            {
                this._appid = null;
            }
            this._defaultPolicy = null;
            SecurityElement securityElement = element.SearchForChildByTag("DefaultGrant");
            if (securityElement != null)
            {
                for (int i = 0; i < securityElement.Children.Count; i++)
                {
                    SecurityElement securityElement2 = securityElement.Children[i] as SecurityElement;
                    if (securityElement2.Tag == "PolicyStatement")
                    {
                        this.DefaultGrantSet.FromXml(securityElement2, null);
                        break;
                    }
                }
            }
            if (!bool.TryParse(element.Attribute("TrustedToRun"), out this._trustrun))
            {
                this._trustrun = false;
            }
            if (!bool.TryParse(element.Attribute("Persist"), out this._persist))
            {
                this._persist = false;
            }
            this._xtranfo = null;
            SecurityElement securityElement3 = element.SearchForChildByTag("ExtraInfo");
            if (securityElement3 != null)
            {
                text = securityElement3.Attribute("Data");
                if (text != null)
                {
                    using (MemoryStream memoryStream = new MemoryStream(CryptoConvert.FromHex(text)))
                    {
                        BinaryFormatter binaryFormatter = new BinaryFormatter();
                        this._xtranfo = binaryFormatter.Deserialize(memoryStream);
                    }
                }
            }
        }
References System.Security.Policy.ApplicationTrust.ApplicationIdentity, System.Security.SecurityElement.Attribute(), System.Security.SecurityElement.Children, System.Security.Policy.ApplicationTrust.DefaultGrantSet, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), Mono.Security.Cryptography.CryptoConvert.FromHex(), System.Security.Policy.PolicyStatement.FromXml(), System.Security.SecurityElement.SearchForChildByTag(), System.Security.SecurityElement.Tag, and System.text.