Terraria Decompiled: System.Security.Policy.ApplicationTrust.ToXml
ToXml()
SecurityElement System.Security.Policy.ApplicationTrust.ToXml () inline
Implements System.Security.ISecurityEncodable.
Definition at line 198 of file ApplicationTrust.cs.
        {
            SecurityElement securityElement = new SecurityElement("ApplicationTrust");
            securityElement.AddAttribute("version", "1");
            if (this._appid != null)
            {
                securityElement.AddAttribute("FullName", this._appid.FullName);
            }
            if (this._trustrun)
            {
                securityElement.AddAttribute("TrustedToRun", "true");
            }
            if (this._persist)
            {
                securityElement.AddAttribute("Persist", "true");
            }
            SecurityElement securityElement2 = new SecurityElement("DefaultGrant");
            securityElement2.AddChild(this.DefaultGrantSet.ToXml());
            securityElement.AddChild(securityElement2);
            if (this._xtranfo != null)
            {
                byte[] array = null;
                using (MemoryStream memoryStream = new MemoryStream())
                {
                    new BinaryFormatter().Serialize(memoryStream, this._xtranfo);
                    array = memoryStream.ToArray();
                }
                SecurityElement securityElement3 = new SecurityElement("ExtraInfo");
                securityElement3.AddAttribute("Data", CryptoConvert.ToHex(array));
                securityElement.AddChild(securityElement3);
            }
            return securityElement;
        }
References System.Security.Policy.ApplicationTrust._appid, System.Security.Policy.ApplicationTrust._persist, System.Security.Policy.ApplicationTrust._trustrun, System.Security.Policy.ApplicationTrust._xtranfo, System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.array, System.Security.Policy.ApplicationTrust.DefaultGrantSet, System.ApplicationIdentity.FullName, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), System.IO.MemoryStream.ToArray(), Mono.Security.Cryptography.CryptoConvert.ToHex(), and System.Security.Policy.PolicyStatement.ToXml().