Terraria Decompiled: Terraria.GameContent.Drawing.BackgroundGradientDrawer.Draw
Draw()
void Terraria.GameContent.Drawing.BackgroundGradientDrawer.Draw () inline
Definition at line 22 of file BackgroundGradientDrawer.cs.
        {
            if (!Main.BackgroundEnabled)
            {
                return;
            }
            float num = this._weightGetter();
            if (num <= 0f)
            {
                return;
            }
            if (!this.ShouldDrawForTextures())
            {
                return;
            }
            if (!Main.ShouldDrawSurfaceBackground())
            {
                return;
            }
            if (BackgroundGradientDrawer._sunflareGradientDitherTexture == null)
            {
                BackgroundGradientDrawer._sunflareGradientDitherTexture = Main.Assets.Request<Texture2D>("Images/Misc/Sunflare/colorgradientdither", 1);
            }
            SpriteBatch spriteBatch = Main.spriteBatch;
            Color color = new Color(this._color.ToVector3() * Main.ColorOfSurfaceBackgroundsBase.ToVector3());
            spriteBatch.Draw(BackgroundGradientDrawer._sunflareGradientDitherTexture.Value, BackgroundGradientDrawer.GetGradientRect(), null, color * num, 0f, Vector2.Zero, SpriteEffects.None, 0f);
        }
References Terraria.GameContent.Drawing.BackgroundGradientDrawer._color, Terraria.GameContent.Drawing.BackgroundGradientDrawer._sunflareGradientDitherTexture, Terraria.GameContent.Drawing.BackgroundGradientDrawer._weightGetter, Terraria.Main.Assets, Terraria.Main.BackgroundEnabled, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.ColorOfSurfaceBackgroundsBase, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Drawing.BackgroundGradientDrawer.GetGradientRect(), Terraria.GameContent.Drawing.BackgroundGradientDrawer.ShouldDrawForTextures(), Terraria.Main.ShouldDrawSurfaceBackground(), Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Color.ToVector3(), ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Drawing.EmptyHorizonRenderer.DrawHorizon(), and Terraria.GameContent.Drawing.NextHorizonRenderer.DrawHorizon().