Terraria Decompiled: System.Int32.Parse
Parse() [3/5]
static int System.Int32.Parse (string s, IFormatProvider provider) inline static
Definition at line 119 of file Int32.cs.
        {
            if (s == null)
            {
                ThrowHelper.ThrowArgumentNullException(ExceptionArgument.s);
            }
            return Number.ParseInt32(s, NumberStyles.Integer, NumberFormatInfo.GetInstance(provider));
        }
References System.Globalization.NumberFormatInfo.GetInstance(), System.Number.ParseInt32(), System.s, and System.ThrowHelper.ThrowArgumentNullException().