Terraria Decompiled: Ionic.Crc.CrcCalculatorStream.Read
Read()
override int Ionic.Crc.CrcCalculatorStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 96 of file CrcCalculatorStream.cs.
        {
            int num = count;
            if (this._lengthLimit != CrcCalculatorStream.UnsetLengthLimit)
            {
                if (this._Crc32.TotalBytesRead >= this._lengthLimit)
                {
                    return 0;
                }
                long num2 = this._lengthLimit - this._Crc32.TotalBytesRead;
                if (num2 < (long)count)
                {
                    num = (int)num2;
                }
            }
            int num3 = this._innerStream.Read(buffer, offset, num);
            if (num3 > 0)
            {
                this._Crc32.SlurpBlock(buffer, offset, num3);
            }
            return num3;
        }
References Ionic.Crc.CrcCalculatorStream._Crc32, Ionic.Crc.CrcCalculatorStream._innerStream, Ionic.Crc.CrcCalculatorStream._lengthLimit, System.count, int, System.offset, System.IO.Stream.Read(), Ionic.Crc.CRC32.SlurpBlock(), Ionic.Crc.CRC32.TotalBytesRead, and Ionic.Crc.CrcCalculatorStream.UnsetLengthLimit.
Referenced by Ionic.Zip.ZipEntry.ExtractOne(), and Ionic.Zip.ZipInputStream.Read().