Terraria Decompiled: FullSerializer.Internal.fsReflectedConverter.TryDeserialize
TryDeserialize()
override fsResult FullSerializer.Internal.fsReflectedConverter.TryDeserialize (fsData data, ref object instance, Type storageType) inline
Definition at line 40 of file fsReflectedConverter.cs.
        {
            fsResult fsResult = fsResult.Success;
            fsResult fsResult2;
            fsResult = (fsResult2 = fsResult + base.CheckType(data, fsDataType.Object));
            if (fsResult2.Failed)
            {
                return fsResult;
            }
            fsMetaType fsMetaType = fsMetaType.Get(this.Serializer.Config, storageType);
            fsMetaType.EmitAotData();
            for (int i = 0; i < fsMetaType.Properties.Length; i++)
            {
                fsMetaProperty fsMetaProperty = fsMetaType.Properties[i];
                fsData fsData;
                if (fsMetaProperty.CanWrite && data.AsDictionary.TryGetValue(fsMetaProperty.JsonName, ref fsData))
                {
                    object obj = null;
                    if (fsMetaProperty.CanRead)
                    {
                        obj = fsMetaProperty.Read(instance);
                    }
                    fsResult fsResult3 = this.Serializer.TryDeserialize(fsData, fsMetaProperty.StorageType, fsMetaProperty.OverrideConverterType, ref obj);
                    fsResult.AddMessages(fsResult3);
                    if (!fsResult3.Failed)
                    {
                        fsMetaProperty.Write(instance, obj);
                    }
                }
            }
            return fsResult;
        }
References FullSerializer.fsResult.AddMessages(), FullSerializer.fsData.AsDictionary, FullSerializer.Internal.fsMetaProperty.CanRead, FullSerializer.Internal.fsMetaProperty.CanWrite, FullSerializer.fsSerializer.Config, FullSerializer.fsMetaType.EmitAotData(), FullSerializer.fsResult.Failed, FullSerializer.fsMetaType.Get(), FullSerializer.Internal.fsMetaProperty.JsonName, System.obj, FullSerializer.Internal.fsMetaProperty.OverrideConverterType, FullSerializer.fsMetaType.Properties, FullSerializer.Internal.fsMetaProperty.Read(), FullSerializer.fsBaseConverter.Serializer, FullSerializer.Internal.fsMetaProperty.StorageType, FullSerializer.fsResult.Success, FullSerializer.fsSerializer.TryDeserialize(), and FullSerializer.Internal.fsMetaProperty.Write().