Terraria Decompiled: FullSerializer.Internal.fsReflectedConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsReflectedConverter.TrySerialize (object instance, out fsData serialized, Type storageType) inline
Definition at line 16 of file fsReflectedConverter.cs.
        {
            serialized = fsData.CreateDictionary();
            fsResult success = fsResult.Success;
            fsMetaType fsMetaType = fsMetaType.Get(this.Serializer.Config, instance.GetType());
            fsMetaType.EmitAotData();
            for (int i = 0; i < fsMetaType.Properties.Length; i++)
            {
                fsMetaProperty fsMetaProperty = fsMetaType.Properties[i];
                if (fsMetaProperty.CanRead)
                {
                    fsData fsData;
                    fsResult fsResult = this.Serializer.TrySerialize(fsMetaProperty.StorageType, fsMetaProperty.OverrideConverterType, fsMetaProperty.Read(instance), out fsData);
                    success.AddMessages(fsResult);
                    if (!fsResult.Failed)
                    {
                        serialized.AsDictionary[fsMetaProperty.JsonName] = fsData;
                    }
                }
            }
            return success;
        }
References FullSerializer.fsResult.AddMessages(), FullSerializer.Internal.fsMetaProperty.CanRead, FullSerializer.fsSerializer.Config, FullSerializer.fsData.CreateDictionary(), FullSerializer.fsMetaType.EmitAotData(), FullSerializer.fsResult.Failed, FullSerializer.fsMetaType.Get(), FullSerializer.Internal.fsMetaProperty.JsonName, FullSerializer.Internal.fsMetaProperty.OverrideConverterType, FullSerializer.fsMetaType.Properties, FullSerializer.Internal.fsMetaProperty.Read(), FullSerializer.fsBaseConverter.Serializer, FullSerializer.Internal.fsMetaProperty.StorageType, FullSerializer.fsResult.Success, and FullSerializer.fsSerializer.TrySerialize().