Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Save
Save()
static void Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Save () inline static
Definition at line 1211 of file UIWorldGenDebug.cs.
            {
                File.WriteAllText(UIWorldGenDebug.Config.FilePath, JsonConvert.SerializeObject(UIWorldGenDebug.Config.Instance));
            }
References Terraria.GameContent.UI.States.UIWorldGenDebug.Config.FilePath, Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Instance, Newtonsoft.Json.JsonConvert.SerializeObject(), and System.IO.File.WriteAllText().
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.ToggleHighlight().