Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Load
Load()
static void Terraria.GameContent.UI.States.UIWorldGenDebug.Config.Load () inline static
Definition at line 1217 of file UIWorldGenDebug.cs.
            {
                try
                {
                    if (File.Exists(UIWorldGenDebug.Config.FilePath))
                    {
                        UIWorldGenDebug.Config.Instance = JsonConvert.DeserializeObject<UIWorldGenDebug.Config>(File.ReadAllText(UIWorldGenDebug.Config.FilePath));
                    }
                }
                catch (Exception)
                {
                }
            }
References Newtonsoft.Json.JsonConvert.DeserializeObject(), System.IO.File.Exists(), Terraria.GameContent.UI.States.UIWorldGenDebug.Config.FilePath, and System.IO.File.ReadAllText().
Referenced by Terraria.GameContent.UI.States.UIWorldGenDebug.OnActivate().