Terraria Decompiled: System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke
PrivateInvoke()
static object System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke (RealProxy rp, IMessage msg, out Exception exc, out object[] out_args) inline static package
Definition at line 132 of file RealProxy.cs.
        {
            MonoMethodMessage monoMethodMessage = (MonoMethodMessage)msg;
            monoMethodMessage.LogicalCallContext = Thread.CurrentThread.GetMutableExecutionContext().LogicalCallContext;
            CallType callType = monoMethodMessage.CallType;
            bool flag = rp is RemotingProxy;
            out_args = null;
            IMethodReturnMessage methodReturnMessage = null;
            if (callType == CallType.BeginInvoke)
            {
                monoMethodMessage.AsyncResult.CallMessage = monoMethodMessage;
            }
            if (callType == CallType.EndInvoke)
            {
                methodReturnMessage = (IMethodReturnMessage)monoMethodMessage.AsyncResult.EndInvoke();
            }
            if (monoMethodMessage.MethodBase.IsConstructor)
            {
                if (flag)
                {
                    methodReturnMessage = (IMethodReturnMessage)(rp as RemotingProxy).ActivateRemoteObject((IMethodMessage)msg);
                }
                else
                {
                    msg = new ConstructionCall(rp.GetProxiedType());
                }
            }
            if (methodReturnMessage == null)
            {
                bool flag2 = false;
                try
                {
                    methodReturnMessage = (IMethodReturnMessage)rp.Invoke(msg);
                }
                catch (Exception ex)
                {
                    flag2 = true;
                    if (callType != CallType.BeginInvoke)
                    {
                        throw;
                    }
                    monoMethodMessage.AsyncResult.SyncProcessMessage(new ReturnMessage(ex, msg as IMethodCallMessage));
                    methodReturnMessage = new ReturnMessage(null, null, 0, null, msg as IMethodCallMessage);
                }
                if (!flag && callType == CallType.BeginInvoke && !flag2)
                {
                    object obj = monoMethodMessage.AsyncResult.SyncProcessMessage(methodReturnMessage);
                    out_args = methodReturnMessage.OutArgs;
                    methodReturnMessage = new ReturnMessage(obj, null, 0, null, methodReturnMessage as IMethodCallMessage);
                }
            }
            if (methodReturnMessage.LogicalCallContext != null && methodReturnMessage.LogicalCallContext.HasInfo)
            {
                Thread.CurrentThread.GetMutableExecutionContext().LogicalCallContext.Merge(methodReturnMessage.LogicalCallContext);
            }
            exc = methodReturnMessage.Exception;
            if (exc != null)
            {
                out_args = null;
                throw exc.FixRemotingException();
            }
            if (methodReturnMessage is IConstructionReturnMessage)
            {
                if (out_args == null)
                {
                    out_args = methodReturnMessage.OutArgs;
                }
            }
            else if (monoMethodMessage.CallType != CallType.BeginInvoke)
            {
                if (monoMethodMessage.CallType == CallType.Sync)
                {
                    out_args = RealProxy.ProcessResponse(methodReturnMessage, monoMethodMessage);
                }
                else if (monoMethodMessage.CallType == CallType.EndInvoke)
                {
                    out_args = RealProxy.ProcessResponse(methodReturnMessage, monoMethodMessage.AsyncResult.CallMessage);
                }
                else if (out_args == null)
                {
                    out_args = methodReturnMessage.OutArgs;
                }
            }
            return methodReturnMessage.ReturnValue;
        }
References System.Runtime.Remoting.Messaging.MonoMethodMessage.AsyncResult, System.Runtime.Remoting.Messaging.AsyncResult.CallMessage, System.Runtime.Remoting.Messaging.MonoMethodMessage.CallType, System.Threading.Thread.CurrentThread, System.Runtime.Remoting.Messaging.AsyncResult.EndInvoke(), System.Runtime.Remoting.Messaging.IMethodReturnMessage.Exception, System.Exception.FixRemotingException(), System.Threading.Thread.GetMutableExecutionContext(), System.Runtime.Remoting.Proxies.RealProxy.GetProxiedType(), System.Runtime.Remoting.Messaging.LogicalCallContext.HasInfo, System.Runtime.Remoting.Proxies.RealProxy.Invoke(), System.Reflection.MethodBase.IsConstructor, System.Runtime.Remoting.Messaging.IMethodMessage.LogicalCallContext, System.Threading.ExecutionContext.LogicalCallContext, System.Runtime.Remoting.Messaging.LogicalCallContext.Merge(), System.Runtime.Remoting.Messaging.MonoMethodMessage.MethodBase, System.obj, System.Runtime.Remoting.Messaging.IMethodReturnMessage.OutArgs, System.Runtime.Remoting.Proxies.RealProxy.ProcessResponse(), System.Runtime.Remoting.Messaging.IMethodReturnMessage.ReturnValue, and System.Runtime.Remoting.Messaging.AsyncResult.SyncProcessMessage().
Referenced by System.Runtime.Remoting.Proxies.TransparentProxy.LoadRemoteFieldNew(), and System.Runtime.Remoting.Proxies.TransparentProxy.StoreRemoteField().