Terraria Decompiled: System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy
GetTransparentProxy()
virtual object System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy () inline virtual
Definition at line 223 of file RealProxy.cs.
        {
            if (this._objTP == null)
            {
                IRemotingTypeInfo remotingTypeInfo = this as IRemotingTypeInfo;
                string text;
                if (remotingTypeInfo != null)
                {
                    text = remotingTypeInfo.TypeName;
                    if (text == null || text == typeof(MarshalByRefObject).AssemblyQualifiedName)
                    {
                        text = this.class_to_proxy.AssemblyQualifiedName;
                    }
                }
                else
                {
                    text = this.class_to_proxy.AssemblyQualifiedName;
                }
                this._objTP = this.InternalGetTransparentProxy(text);
            }
            return this._objTP;
        }
References System.Runtime.Remoting.Proxies.RealProxy._objTP, System.Type.AssemblyQualifiedName, System.Runtime.Remoting.Proxies.RealProxy.class_to_proxy, System.Runtime.Remoting.Proxies.RealProxy.InternalGetTransparentProxy(), System.text, and System.Runtime.Remoting.IRemotingTypeInfo.TypeName.
Referenced by System.Runtime.Remoting.Proxies.RemotingProxy.AttachIdentity(), System.Runtime.Remoting.RemotingServices.CreateClientProxy(), System.Runtime.Remoting.RemotingServices.CreateClientProxyForComInterop(), System.Runtime.Remoting.RemotingServices.CreateClientProxyForContextBound(), System.Runtime.Remoting.Proxies.ProxyAttribute.CreateInstance(), System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage(), System.Runtime.Remoting.Proxies.RealProxy.CreateObjRef(), System.Runtime.InteropServices.Marshal.CreateWrapperOfType(), System.Runtime.Remoting.Proxies.RealProxy.GetObjectData(), System.Runtime.InteropServices.Marshal.GetObjectForIUnknown(), System.Runtime.Remoting.RemotingServices.GetOrCreateClientIdentity(), System.Runtime.InteropServices.Marshal.GetTypedObjectForIUnknown(), and System.Runtime.Remoting.RemotingServices.Unmarshal().