Terraria Decompiled: System.Runtime.Remoting.Proxies.RealProxy.ProcessResponse
ProcessResponse()
static object[] System.Runtime.Remoting.Proxies.RealProxy.ProcessResponse (IMethodReturnMessage mrm, MonoMethodMessage call) inline static private
Definition at line 296 of file RealProxy.cs.
        {
            MethodInfo methodInfo = (MethodInfo)call.MethodBase;
            if (mrm.ReturnValue != null && !methodInfo.ReturnType.IsInstanceOfType(mrm.ReturnValue))
            {
                throw new InvalidCastException("Return value has an invalid type");
            }
            int num;
            if (call.NeedsOutProcessing(out num))
            {
                ParameterInfo[] parameters = methodInfo.GetParameters();
                object[] array = new object[num];
                int num2 = 0;
                foreach (ParameterInfo parameterInfo in parameters)
                {
                    if (parameterInfo.IsOut && !parameterInfo.ParameterType.IsByRef)
                    {
                        object obj = ((parameterInfo.Position < mrm.ArgCount) ? mrm.GetArg(parameterInfo.Position) : null);
                        if (obj != null)
{
                            object arg = call.GetArg(parameterInfo.Position);
                            if (arg == null)
{
                                throw new RemotingException("Unexpected null value in local out parameter '" + parameterInfo.Name + "'");
                            }
                            RemotingServices.UpdateOutArgObject(parameterInfo, arg, obj);
                        }
                    }
                    else if (parameterInfo.ParameterType.IsByRef)
                    {
                        object obj2 = ((parameterInfo.Position < mrm.ArgCount) ? mrm.GetArg(parameterInfo.Position) : null);
                        if (obj2 != null && !parameterInfo.ParameterType.GetElementType().IsInstanceOfType(obj2))
{
                            throw new InvalidCastException("Return argument '" + parameterInfo.Name + "' has an invalid type");
                        }
                        array[num2++] = obj2;
                    }
                }
                return array;
            }
            return new object[0];
        }
References System.Runtime.Remoting.Messaging.IMethodMessage.ArgCount, System.array, System.Runtime.Remoting.Messaging.MonoMethodMessage.GetArg(), System.Runtime.Remoting.Messaging.IMethodMessage.GetArg(), System.Type.GetElementType(), System.Reflection.MethodBase.GetParameters(), System.Type.IsByRef, System.Type.IsInstanceOfType(), System.Reflection.ParameterInfo.IsOut, System.Runtime.Remoting.Messaging.MonoMethodMessage.MethodBase, System.Reflection.ParameterInfo.Name, System.Runtime.Remoting.Messaging.MonoMethodMessage.NeedsOutProcessing(), System.obj, System.Reflection.ParameterInfo.ParameterType, System.Reflection.ParameterInfo.Position, System.Reflection.MethodInfo.ReturnType, System.Runtime.Remoting.Messaging.IMethodReturnMessage.ReturnValue, and System.Runtime.Remoting.RemotingServices.UpdateOutArgObject().
Referenced by System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke().