Terraria Decompiled: Terraria.TimeLogger.DrawExtras
DrawExtras()
static void Terraria.TimeLogger.DrawExtras () inline static private
Definition at line 323 of file TimeLogger.cs.
        {
            if (Platform.IsWindows)
            {
                WindowsPerformanceDiagnostics.Data data = WindowsPerformanceDiagnostics.GetData();
                int num = Main.screenWidth - 180;
                int num2 = Main.screenHeight - 100;
                TimeLogger.DrawString((data.PinnedToProcessor ? TimeLogger._PinnedCPUFormat : TimeLogger._AssignedCPUFormat).Format((double)data.CurrentProcessor), new Vector2((float)num, (float)(num2 += 12)), Color.White);
                TimeLogger.DrawString(TimeLogger._procThrottleFormat.Format(data.ProcessorThrottlePercent), new Vector2((float)num, (float)(num2 += 12)), Color.White);
                TimeLogger.DrawString(TimeLogger._expectedCPUFormat.Format(data.ExpectedCPUPercent), new Vector2((float)num, (float)(num2 += 12)), Color.White);
                if (data.PinnedToProcessor)
                {
                    TimeLogger.DrawString(TimeLogger._terrariaCPUFormat.Format(data.MainThreadCPUPercent), new Vector2((float)num, (float)(num2 += 12)), Color.White);
                }
                TimeLogger.FormatPool pendingCPUFormat = TimeLogger._pendingCPUFormat;
                long? contentionQueueLength = data.ContentionQueueLength;
                TimeLogger.DrawString(pendingCPUFormat.Format((contentionQueueLength != null) ? new double?((double)contentionQueueLength.GetValueOrDefault()) : null), new Vector2((float)num, (float)(num2 += 12)), Color.White);
                num2 += 2;
                if (data.RecommendUnpinning)
                {
                    TimeLogger.DrawString("Core pinning may be", new Vector2((float)num, (float)(num2 += 11)), Color.Orange);
                    TimeLogger.DrawString("reducing performance", new Vector2((float)num, (float)(num2 + 12)), Color.Orange);
                }
            }
            if (PlayerInput.UsingGamepad)
            {
                for (int i = 0; i < 2; i++)
                {
                    string text = "";
                    int num3 = Main.screenWidth - 220;
                    int num4 = Main.screenHeight - 140 + i * 12;
                    if (i == 0)
                    {
                        text = string.Format("Thumbstick (L): {0,7:P2} ,{1,7:P2}", PlayerInput.GamepadThumbstickLeft.X, PlayerInput.GamepadThumbstickLeft.Y);
                    }
                    if (i == 1)
                    {
                        text = string.Format("Thumbstick (R): {0,7:P2} ,{1,7:P2}", PlayerInput.GamepadThumbstickRight.X, PlayerInput.GamepadThumbstickRight.Y);
                    }
                    TimeLogger.DrawString(text, new Vector2((float)num3, (float)num4), Color.White);
                }
            }
        }
References Terraria.TimeLogger._AssignedCPUFormat, Terraria.TimeLogger._expectedCPUFormat, Terraria.TimeLogger._pendingCPUFormat, Terraria.TimeLogger._PinnedCPUFormat, Terraria.TimeLogger._procThrottleFormat, Terraria.TimeLogger._terrariaCPUFormat, Terraria.Testing.WindowsPerformanceDiagnostics.Data.ContentionQueueLength, Terraria.Testing.WindowsPerformanceDiagnostics.Data.CurrentProcessor, Terraria.TimeLogger.DrawString(), Terraria.Testing.WindowsPerformanceDiagnostics.Data.ExpectedCPUPercent, System.Format, Terraria.TimeLogger.FormatPool.Format(), Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Terraria.Testing.WindowsPerformanceDiagnostics.GetData(), ReLogic.OS.Platform.IsWindows, Terraria.Testing.WindowsPerformanceDiagnostics.Data.MainThreadCPUPercent, Microsoft.Xna.Framework.Color.Orange, Terraria.Testing.WindowsPerformanceDiagnostics.Data.PinnedToProcessor, Terraria.Testing.WindowsPerformanceDiagnostics.Data.ProcessorThrottlePercent, Terraria.Testing.WindowsPerformanceDiagnostics.Data.RecommendUnpinning, System.text, Terraria.GameInput.PlayerInput.UsingGamepad, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.TimeLogger.Draw().