Terraria Decompiled: Terraria.TimeLogger.DrawEntry
DrawEntry()
static void Terraria.TimeLogger.DrawEntry (TimeLogger::TimeLogData e, ref int y, int indent = 0) inline static private
Definition at line 368 of file TimeLogger.cs.
        {
            e.pendingDisplay = false;
            if (TimeLogger.DrawnEntryNumber++ % 2 == 1)
            {
                Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(0, y, TimeLogger.TableWidth, 12), new Color(0, 0, 0, 80));
            }
            int num = 0;
            TimeLogger.DrawString(e.name, new Vector2((float)(num + 20 + indent * 12), (float)y), TimeLogger.PerformanceColor((long)e.data[0].median, (long)e.budget));
            TimeLogger.DrawEntryData(num, y, e.data[0], e.format, e.budget);
            num += TimeLogger.ColumnSpacing;
            TimeLogger.DrawEntryData(num, y, e.data[1], e.format, e.budget);
            num += TimeLogger.ColumnSpacing;
            TimeLogger.DrawDelta(num, y, e.data[0], e.data[1], e.format, e.budget);
            y += 12;
        }
References Terraria.TimeLogger.ColumnSpacing, Terraria.TimeLogger.DrawDelta(), Terraria.TimeLogger.DrawEntryData(), Terraria.TimeLogger.DrawnEntryNumber, Terraria.TimeLogger.DrawString(), Terraria.GameContent.TextureAssets.MagicPixel, Terraria.TimeLogger.PerformanceColor(), Terraria.Main.spriteBatch, Terraria.TimeLogger.TableWidth, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.TimeLogger.DrawTimes().