Terraria Decompiled: Terraria.TimeLogger.DrawDelta
DrawDelta() [1/2]
static void Terraria.TimeLogger.DrawDelta (int value0, int value1, Vector2 pos, Func< int, string > format, int budget) inline static private
Definition at line 432 of file TimeLogger.cs.
        {
            int num = value1 - value0;
            int num2 = (int)Math.Round((double)value1 * 100.0 / (double)value0 - 100.0);
            if (value0 == 0 || Math.Abs(num2) <= 1 || Math.Abs(num * 100) <= budget)
            {
                return;
            }
            Color color = ((num2 < 0) ? Color.Lerp(Color.White, new Color(0, 200, 0), (float)(-(float)num2) / 100f) : Color.Lerp(Color.White, new Color(200, 0, 0), (float)num2 / 100f));
            TimeLogger.DrawString(format(num), pos, color);
            pos.X += 40f;
            TimeLogger.DrawString(TimeLogger._percentFormat.Format((double)num2), pos, color);
        }
References Terraria.TimeLogger._percentFormat, System.Math.Abs(), Terraria.TimeLogger.DrawString(), System.format, int, Microsoft.Xna.Framework.Color.Lerp(), System.Math.Round(), and Microsoft.Xna.Framework.Color.White.