Terraria Decompiled: Terraria.TimeLogger.Start
Start()
static TimeLogger.StartTimestamp Terraria.TimeLogger.Start () inline static
Definition at line 172 of file TimeLogger.cs.
        {
            return new TimeLogger.StartTimestamp
            {
                ticks = Stopwatch.GetTimestamp()
            };
        }
Referenced by Terraria.Graphics.Light.LegacyLighting.DoColors(), Terraria.Main.DoDraw(), Terraria.Main.DoDraw_WallsTilesNPCs(), Terraria.Main.DoDraw_Waterfalls(), Terraria.Graphics.Renderers.ParticleRenderer.Draw(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects(), Terraria.Main.DrawBackground(), Terraria.Main.DrawBlack(), Terraria.Main.DrawCachedNPCs(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawDust(), Terraria.GameContent.LeashedEntity.DrawEntities(), Terraria.Main.DrawGore(), Terraria.Main.DrawItems(), Terraria.Main.DrawMap(), Terraria.Main.DrawNPCs(), Terraria.Main.DrawPlayerChat(), Terraria.Main.DrawPlayers_AfterProjectiles(), Terraria.Main.DrawPlayers_BehindNPCs(), Terraria.Main.DrawProjectiles(), Terraria.Main.DrawRain(), Terraria.Main.DrawTiles(), Terraria.MapRenderer.DrawToMap(), Terraria.Main.DrawWalls(), Terraria.Main.DrawWaters(), Terraria.Main.DrawWires(), Terraria.GameContent.Drawing.TileDrawingBase.End(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.GameContent.Drawing.TileDrawing.GetScreenDrawArea(), Terraria.Lighting.LightTiles(), Terraria.Main.OldDrawBackground(), Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles(), Terraria.GameContent.Drawing.TileDrawing.PrepareForAreaDrawing(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.Graphics.Light.LightingEngine.ProcessArea(), Terraria.Main.RenderBackground(), Terraria.Main.RenderBackgroundWater(), Terraria.Main.RenderTiles(), Terraria.Main.RenderTiles2(), Terraria.Main.RenderWallsAndBlacks(), Terraria.Main.RenderWater(), Terraria.GameContent.Drawing.TileDrawingBase.RestartLayeredBatch(), Terraria.GameContent.Drawing.TileDrawingBase.RestartSpriteBatch(), Terraria.Map.MapUpdateQueue.Update(), and Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().