Terraria Decompiled: Terraria.TimeLogger.DrawTimes
DrawTimes()
static void Terraria.TimeLogger.DrawTimes () inline static private
Definition at line 227 of file TimeLogger.cs.
        {
            TimeLogger.DrawnEntryNumber = 0;
            foreach (TimeLogger.TimeLogData timeLogData in TimeLogger.entries)
            {
                timeLogData.pendingDisplay = timeLogData.ShouldDrawByDefault;
            }
            int num = 100;
            TimeLogger.TableWidth = ((TimeLogger.DataSeriesHeaders[1] != null) ? 900 : 440);
            Main.spriteBatch.Draw(TextureAssets.MagicPixel.Value, new Rectangle(0, num, TimeLogger.TableWidth, 800), new Color(60, 60, 60, 80));
            TimeLogger.DrawString("Render Time (ms) F7 to hide", new Vector2(80f, (float)(num - 16)), Color.White);
            TimeLogger.DrawString("Median", new Vector2(273f, (float)num), Color.White);
            TimeLogger.DrawString("P90", new Vector2(325f, (float)num), Color.White);
            TimeLogger.DrawString("Max", new Vector2(365f, (float)num), Color.White);
            TimeLogger.DrawString("Freq", new Vector2(400f, (float)num), Color.White);
            if (TimeLogger.DataSeriesHeaders[1] != null)
            {
                TimeLogger.DrawString(TimeLogger.DataSeriesHeaders[0], new Vector2(280f, (float)(num - 16)), (TimeLogger.activeDataSeries == 0) ? Color.LightGreen : Color.White);
                TimeLogger.DrawString(TimeLogger.DataSeriesHeaders[1], new Vector2((float)(280 + TimeLogger.ColumnSpacing), (float)(num - 16)), (TimeLogger.activeDataSeries == 1) ? Color.LightGreen : Color.White);
                TimeLogger.DrawString("Delta", new Vector2((float)(320 + 2 * TimeLogger.ColumnSpacing), (float)(num - 16)), Color.White);
                TimeLogger.DrawString("Median", new Vector2((float)(273 + TimeLogger.ColumnSpacing), (float)num), Color.White);
                TimeLogger.DrawString("P90", new Vector2((float)(325 + TimeLogger.ColumnSpacing), (float)num), Color.White);
                TimeLogger.DrawString("Max", new Vector2((float)(365 + TimeLogger.ColumnSpacing), (float)num), Color.White);
                TimeLogger.DrawString("Freq", new Vector2((float)(400 + TimeLogger.ColumnSpacing), (float)num), Color.White);
                TimeLogger.DrawString("Median", new Vector2((float)(250 + 2 * TimeLogger.ColumnSpacing), (float)num), Color.White);
                TimeLogger.DrawString("P90", new Vector2((float)(360 + 2 * TimeLogger.ColumnSpacing), (float)num), Color.White);
            }
            num += 16;
            TimeLogger.DrawEntry(TimeLogger.TotalDrawAndUpdate, ref num, -1);
            TimeLogger.DrawEntry(TimeLogger.TotalDraw, ref num, -1);
            if (!Main.drawToScreen)
            {
                TimeLogger.DrawEntry(TimeLogger.TotalDrawByRenderCount[0], ref num, 0);
                TimeLogger.DrawEntry(TimeLogger.TotalDrawByRenderCount[1], ref num, 0);
                TimeLogger.DrawEntry(TimeLogger.RenderLiquid, ref num, 1);
                TimeLogger.DrawEntry(TimeLogger.LiquidDrawCalls, ref num, 2);
                TimeLogger.DrawEntry(TimeLogger.TotalDrawByRenderCount[2], ref num, 0);
                if (TimeLogger.RenderUndergroundBackground.pendingDisplay)
                {
                    TimeLogger.DrawEntry(TimeLogger.RenderUndergroundBackground, ref num, 1);
                    TimeLogger.DrawEntry(TimeLogger.DrawUndergroundBackground, ref num, 2);
                }
                TimeLogger.DrawEntry(TimeLogger.RenderBackgroundLiquid, ref num, 1);
                TimeLogger.DrawEntry(TimeLogger.LiquidBackgroundDrawCalls, ref num, 2);
                TimeLogger.DrawEntry(TimeLogger.TotalDrawByRenderCount[3], ref num, 0);
                TimeLogger.DrawEntry(TimeLogger.RenderBlacksAndWalls, ref num, 1);
                TimeLogger.DrawEntry(TimeLogger.DrawBlackTiles, ref num, 2);
                TimeLogger.DrawEntry(TimeLogger.DrawWallTiles, ref num, 2);
                TimeLogger.DrawEntry(TimeLogger.FlushWallTiles, ref num, 3);
                TimeLogger.DrawEntry(TimeLogger.WallDrawCalls, ref num, 4);
                TimeLogger.DrawEntry(TimeLogger.RenderSolidTiles, ref num, 1);
                TimeLogger.DrawEntry(TimeLogger.FlushSolidTiles, ref num, 2);
                TimeLogger.DrawEntry(TimeLogger.SolidDrawCalls, ref num, 3);
                TimeLogger.DrawEntry(TimeLogger.RenderNonSolidTiles, ref num, 1);
                TimeLogger.DrawEntry(TimeLogger.FlushNonSolidTiles, ref num, 2);
                TimeLogger.DrawEntry(TimeLogger.NonSolidDrawCalls, ref num, 3);
                TimeLogger.DrawWaterTiles.pendingDisplay = false;
                TimeLogger.DrawBackgroundWaterTiles.pendingDisplay = false;
                TimeLogger.DrawSolidTiles.pendingDisplay = false;
                TimeLogger.DrawNonSolidTiles.pendingDisplay = false;
            }
            foreach (TimeLogger.TimeLogData timeLogData2 in TimeLogger.TotalDrawByRenderCount)
            {
                if (timeLogData2.pendingDisplay)
                {
                    TimeLogger.DrawEntry(timeLogData2, ref num, 0);
                }
            }
            if (TimeLogger.TotalDrawRenderNow.pendingDisplay)
            {
                TimeLogger.DrawEntry(TimeLogger.TotalDrawRenderNow, ref num, 0);
            }
            num += 12;
            TimeLogger.DrawEntry(TimeLogger.Lighting, ref num, 0);
            if (TimeLogger.LightingInit.pendingDisplay)
            {
                TimeLogger.DrawEntry(TimeLogger.LightingInit, ref num, 1);
            }
            foreach (TimeLogger.TimeLogData timeLogData3 in TimeLogger.LightingByPass)
            {
                if (timeLogData3.pendingDisplay)
                {
                    TimeLogger.DrawEntry(timeLogData3, ref num, 1);
                }
            }
            num += 12;
            foreach (TimeLogger.TimeLogData timeLogData4 in TimeLogger.entries)
            {
                if (timeLogData4.pendingDisplay)
                {
                    TimeLogger.DrawEntry(timeLogData4, ref num, 0);
                }
            }
        }
References Terraria.TimeLogger.ColumnSpacing, Terraria.TimeLogger.DataSeriesHeaders, Terraria.TimeLogger.DrawBlackTiles, Terraria.TimeLogger.DrawEntry(), Terraria.TimeLogger.DrawString(), Terraria.Main.drawToScreen, Terraria.TimeLogger.DrawUndergroundBackground, Terraria.TimeLogger.DrawWallTiles, Terraria.TimeLogger.entries, Terraria.TimeLogger.FlushNonSolidTiles, Terraria.TimeLogger.FlushSolidTiles, Terraria.TimeLogger.FlushWallTiles, Microsoft.Xna.Framework.Color.LightGreen, Terraria.TimeLogger.Lighting, Terraria.TimeLogger.LightingByPass, Terraria.TimeLogger.LightingInit, Terraria.TimeLogger.LiquidBackgroundDrawCalls, Terraria.TimeLogger.LiquidDrawCalls, Terraria.GameContent.TextureAssets.MagicPixel, Terraria.TimeLogger.NonSolidDrawCalls, Terraria.TimeLogger.RenderBackgroundLiquid, Terraria.TimeLogger.RenderBlacksAndWalls, Terraria.TimeLogger.RenderLiquid, Terraria.TimeLogger.RenderNonSolidTiles, Terraria.TimeLogger.RenderSolidTiles, Terraria.TimeLogger.RenderUndergroundBackground, Terraria.TimeLogger.SolidDrawCalls, Terraria.Main.spriteBatch, Terraria.TimeLogger.TableWidth, Terraria.TimeLogger.TotalDraw, Terraria.TimeLogger.TotalDrawAndUpdate, Terraria.TimeLogger.TotalDrawByRenderCount, Terraria.TimeLogger.TotalDrawRenderNow, ReLogic.Content.Asset< T >.Value, Terraria.TimeLogger.WallDrawCalls, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.TimeLogger.Draw().