Terraria Decompiled: Terraria.TimeLogger.DrawEntryData
DrawEntryData()
static void Terraria.TimeLogger.DrawEntryData (int x, int y, TimeLogger::DataSeries data, Func< int, string > format, int budget) inline static private
Definition at line 386 of file TimeLogger.cs.
        {
            if (!data.HasData)
            {
                return;
            }
            TimeLogger.DrawValue(data.previous, new Vector2((float)(x + 240), (float)y), format, budget);
            TimeLogger.DrawValue(data.median, new Vector2((float)(x + 280), (float)y), format, budget);
            TimeLogger.DrawValue(data.p90, new Vector2((float)(x + 320), (float)y), format, budget);
            TimeLogger.DrawValue(data.max, new Vector2((float)(x + 360), (float)y), format, budget);
            if (data.frequency < 1f)
            {
                TimeLogger.DrawString(TimeLogger._percentFormat.Format((double)(data.frequency * 100f)), new Vector2((float)(x + 400), (float)y), Color.White);
            }
        }
References Terraria.TimeLogger._percentFormat, Terraria.TimeLogger.DrawString(), Terraria.TimeLogger.DrawValue(), System.format, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.TimeLogger.DrawEntry().