Terraria Decompiled: Terraria.TimeLogger.StartNextFrame
StartNextFrame()
static void Terraria.TimeLogger.StartNextFrame () inline static
Definition at line 92 of file TimeLogger.cs.
        {
            while (TimeLogger._onNextFrame.Count > 0)
            {
                TimeLogger._onNextFrame.Dequeue()();
            }
            TimeLogger.ABTest();
            foreach (TimeLogger.TimeLogData timeLogData in TimeLogger.entries)
            {
                timeLogData.StartNextFrame();
            }
            if (TimeLogger.startLoggingNextFrame)
            {
                TimeLogger.startLoggingNextFrame = false;
                DateTime now = DateTime.Now;
                string text = Main.SavePath + Path.DirectorySeparatorChar.ToString() + "TerrariaDrawLog.7z";
                try
                {
                    TimeLogger.logWriter = new StreamWriter(new GZipStream(new FileStream(text, FileMode.Create), CompressionMode.Compress));
                    TimeLogger.logBuilder = new StringBuilder(5000);
                    TimeLogger.framesToLog = 600;
                    TimeLogger.currentFrame = 1;
                    TimeLogger.currentlyLogging = true;
                }
                catch
                {
                    Main.NewText("Detailed logging could not be started.", 250, 250, 0);
                }
            }
            if (TimeLogger.currentlyLogging)
            {
                TimeLogger.logBuilder.AppendLine(string.Format("Start of Frame #{0}", TimeLogger.currentFrame));
            }
        }
References Terraria.TimeLogger._onNextFrame, Terraria.TimeLogger.ABTest(), System.Text.StringBuilder.AppendLine(), System.Collections.Generic.Queue< T >.Count, Terraria.TimeLogger.currentFrame, Terraria.TimeLogger.currentlyLogging, System.Collections.Generic.Queue< T >.Dequeue(), System.IO.Path.DirectorySeparatorChar, Terraria.TimeLogger.entries, System.Format, Terraria.TimeLogger.logBuilder, Terraria.Main.NewText(), System.DateTime.Now, Terraria.TimeLogger.startLoggingNextFrame, and System.text.
Referenced by Terraria.Testing.DetailedFPS.StartNextFrame(), and Terraria.TimeLogger.TimeLogData.StartNextFrame().