Terraria Decompiled: System.Security.Cryptography.CryptoStream.d__49.MoveNext
MoveNext()
void IAsyncStateMachine. System.Security.Cryptography.CryptoStream.d__49.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1223 of file CryptoStream.cs.
            {
                int num2;
                int num = num2;
                CryptoStream cryptoStream = this;
                try
                {
                    ValueTaskAwaiter valueTaskAwaiter;
                    switch (num)
                    {
                    case 0:
                    {
                        ValueTaskAwaiter valueTaskAwaiter2;
                        valueTaskAwaiter = valueTaskAwaiter2;
                        valueTaskAwaiter2 = default(ValueTaskAwaiter);
                        num = (num2 = -1);
                        break;
                    }
                    case 1:
                    {
                        ValueTaskAwaiter valueTaskAwaiter2;
                        valueTaskAwaiter = valueTaskAwaiter2;
                        valueTaskAwaiter2 = default(ValueTaskAwaiter);
                        num = (num2 = -1);
                        goto IL_0266;
                    }
                    case 2:
                        IL_02FA:
                        try
{
                            if (num != 2)
{
                                numOutputBytes = cryptoStream._transform.TransformBlock(buffer, currentInputIndex, numWholeBlocksInBytes, tempOutputBuffer, 0);
                                if (!useAsync)
{
                                    cryptoStream._stream.Write(tempOutputBuffer, 0, numOutputBytes);
                                    goto IL_03C9;
                                }
                                valueTaskAwaiter = cryptoStream._stream.WriteAsync(new ReadOnlyMemory<byte>(tempOutputBuffer, 0, numOutputBytes), cancellationToken).GetAwaiter();
                                if (!valueTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 2);
                                    ValueTaskAwaiter valueTaskAwaiter2 = valueTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ValueTaskAwaiter, CryptoStream.<WriteAsyncCore>d__49>(ref valueTaskAwaiter, ref this);
                                    return;
                                }
                            }
                            else
{
                                ValueTaskAwaiter valueTaskAwaiter2;
                                valueTaskAwaiter = valueTaskAwaiter2;
                                valueTaskAwaiter2 = default(ValueTaskAwaiter);
                                num = (num2 = -1);
                            }
                            valueTaskAwaiter.GetResult();
                            IL_03C9:
                            currentInputIndex += numWholeBlocksInBytes;
                            bytesToWrite -= numWholeBlocksInBytes;
                        }
                        finally
{
                            if (num < 0)
{
                                CryptographicOperations.ZeroMemory(new Span<byte>(tempOutputBuffer, 0, numOutputBytes));
                                ArrayPool<byte>.Shared.Return(tempOutputBuffer, false);
                                tempOutputBuffer = null;
                            }
                        }
                        tempOutputBuffer = null;
                        goto IL_0553;
                    case 3:
                    {
                        ValueTaskAwaiter valueTaskAwaiter2;
                        valueTaskAwaiter = valueTaskAwaiter2;
                        valueTaskAwaiter2 = default(ValueTaskAwaiter);
                        num = (num2 = -1);
                        goto IL_04D7;
                    }
                    default:
                        bytesToWrite = count;
                        currentInputIndex = offset;
                        if (cryptoStream._inputBufferIndex > 0)
{
                            if (count < cryptoStream._inputBlockSize - cryptoStream._inputBufferIndex)
{
                                Buffer.BlockCopy(buffer, offset, cryptoStream._inputBuffer, cryptoStream._inputBufferIndex, count);
                                cryptoStream._inputBufferIndex += count;
                                goto IL_057A;
                            }
                            Buffer.BlockCopy(buffer, offset, cryptoStream._inputBuffer, cryptoStream._inputBufferIndex, cryptoStream._inputBlockSize - cryptoStream._inputBufferIndex);
                            currentInputIndex += cryptoStream._inputBlockSize - cryptoStream._inputBufferIndex;
                            bytesToWrite -= cryptoStream._inputBlockSize - cryptoStream._inputBufferIndex;
                            cryptoStream._inputBufferIndex = cryptoStream._inputBlockSize;
                        }
                        if (cryptoStream._outputBufferIndex <= 0)
{
                            goto IL_01B4;
                        }
                        if (!useAsync)
{
                            cryptoStream._stream.Write(cryptoStream._outputBuffer, 0, cryptoStream._outputBufferIndex);
                            goto IL_01AD;
                        }
                        valueTaskAwaiter = cryptoStream._stream.WriteAsync(new ReadOnlyMemory<byte>(cryptoStream._outputBuffer, 0, cryptoStream._outputBufferIndex), cancellationToken).GetAwaiter();
                        if (!valueTaskAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            ValueTaskAwaiter valueTaskAwaiter2 = valueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ValueTaskAwaiter, CryptoStream.<WriteAsyncCore>d__49>(ref valueTaskAwaiter, ref this);
                            return;
                        }
                        break;
                    }
                    valueTaskAwaiter.GetResult();
                    IL_01AD:
                    cryptoStream._outputBufferIndex = 0;
                    IL_01B4:
                    if (cryptoStream._inputBufferIndex != cryptoStream._inputBlockSize)
                    {
                        goto IL_0553;
                    }
                    numOutputBytes = cryptoStream._transform.TransformBlock(cryptoStream._inputBuffer, 0, cryptoStream._inputBlockSize, cryptoStream._outputBuffer, 0);
                    if (!useAsync)
                    {
                        cryptoStream._stream.Write(cryptoStream._outputBuffer, 0, numOutputBytes);
                        goto IL_0287;
                    }
                    valueTaskAwaiter = cryptoStream._stream.WriteAsync(new ReadOnlyMemory<byte>(cryptoStream._outputBuffer, 0, numOutputBytes), cancellationToken).GetAwaiter();
                    if (!valueTaskAwaiter.IsCompleted)
                    {
                        num = (num2 = 1);
                        ValueTaskAwaiter valueTaskAwaiter2 = valueTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ValueTaskAwaiter, CryptoStream.<WriteAsyncCore>d__49>(ref valueTaskAwaiter, ref this);
                        return;
                    }
                    IL_0266:
                    valueTaskAwaiter.GetResult();
                    IL_0287:
                    cryptoStream._inputBufferIndex = 0;
                    goto IL_0553;
                    IL_04D7:
                    valueTaskAwaiter.GetResult();
                    IL_04F8:
                    currentInputIndex += cryptoStream._inputBlockSize;
                    bytesToWrite -= cryptoStream._inputBlockSize;
                    IL_0553:
                    if (bytesToWrite > 0)
                    {
                        if (bytesToWrite >= cryptoStream._inputBlockSize)
{
                            int num3 = bytesToWrite / cryptoStream._inputBlockSize;
                            if (cryptoStream._transform.CanTransformMultipleBlocks && num3 > 1)
{
                                numWholeBlocksInBytes = num3 * cryptoStream._inputBlockSize;
                                tempOutputBuffer = ArrayPool<byte>.Shared.Rent(num3 * cryptoStream._outputBlockSize);
                                numOutputBytes = 0;
                                goto IL_02FA;
                            }
                            numOutputBytes = cryptoStream._transform.TransformBlock(buffer, currentInputIndex, cryptoStream._inputBlockSize, cryptoStream._outputBuffer, 0);
                            if (!useAsync)
{
                                cryptoStream._stream.Write(cryptoStream._outputBuffer, 0, numOutputBytes);
                                goto IL_04F8;
                            }
                            valueTaskAwaiter = cryptoStream._stream.WriteAsync(new ReadOnlyMemory<byte>(cryptoStream._outputBuffer, 0, numOutputBytes), cancellationToken).GetAwaiter();
                            if (!valueTaskAwaiter.IsCompleted)
{
                                num = (num2 = 3);
                                ValueTaskAwaiter valueTaskAwaiter2 = valueTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ValueTaskAwaiter, CryptoStream.<WriteAsyncCore>d__49>(ref valueTaskAwaiter, ref this);
                                return;
                            }
                            goto IL_04D7;
                        }
                        else
{
                            Buffer.BlockCopy(buffer, currentInputIndex, cryptoStream._inputBuffer, 0, bytesToWrite);
                            cryptoStream._inputBufferIndex += bytesToWrite;
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_057A:
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.Security.Cryptography.CryptoStream._inputBlockSize, System.Security.Cryptography.CryptoStream._inputBuffer, System.Security.Cryptography.CryptoStream._inputBufferIndex, System.Security.Cryptography.CryptoStream._outputBlockSize, System.Security.Cryptography.CryptoStream._outputBuffer, System.Security.Cryptography.CryptoStream._outputBufferIndex, System.Security.Cryptography.CryptoStream._stream, System.Security.Cryptography.CryptoStream._transform, System.Buffer.BlockCopy(), System.Security.Cryptography.ICryptoTransform.CanTransformMultipleBlocks, System.count, System.Runtime.CompilerServices.ValueTaskAwaiter< TResult >.GetResult(), System.Runtime.CompilerServices.ValueTaskAwaiter< TResult >.IsCompleted, System.offset, System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.ICryptoTransform.TransformBlock(), System.IO.Stream.Write(), System.IO.Stream.WriteAsync(), System.Security.Cryptography.CryptoStream.WriteAsyncCore(), and System.Security.Cryptography.CryptographicOperations.ZeroMemory().