Terraria Decompiled: Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors
SetShimmerVertexColors()
static void Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors (ref VertexColors colors, float opacity, int x, int y) inline static
Definition at line 680 of file LiquidRenderer.cs.
        {
            colors.BottomLeftColor = Color.White;
            colors.BottomRightColor = Color.White;
            colors.TopLeftColor = Color.White;
            colors.TopRightColor = Color.White;
            colors.BottomLeftColor *= opacity;
            colors.BottomRightColor *= opacity;
            colors.TopLeftColor *= opacity;
            colors.TopRightColor *= opacity;
            colors.BottomLeftColor = new Color(colors.BottomLeftColor.ToVector4() * LiquidRenderer.GetShimmerBaseColor((float)x, (float)(y + 1)));
            colors.BottomRightColor = new Color(colors.BottomRightColor.ToVector4() * LiquidRenderer.GetShimmerBaseColor((float)(x + 1), (float)(y + 1)));
            colors.TopLeftColor = new Color(colors.TopLeftColor.ToVector4() * LiquidRenderer.GetShimmerBaseColor((float)x, (float)y));
            colors.TopRightColor = new Color(colors.TopRightColor.ToVector4() * LiquidRenderer.GetShimmerBaseColor((float)(x + 1), (float)y));
        }
References Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerBaseColor(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.Liquid.LiquidRenderer.DrawShimmer(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), and Terraria.WaterfallManager.DrawWaterfall().