Terraria Decompiled: System.Reflection.Emit.ModuleBuilder.ModuleBuilder
ModuleBuilder() [1/2]
System.Reflection.Emit.ModuleBuilder.ModuleBuilder (AssemblyBuilder assb, string name, string fullyqname, bool emitSymbolInfo, bool transient) inline package
Definition at line 53 of file ModuleBuilder.cs.
        {
            this.scopename = name;
            this.name = name;
            this.fqname = fullyqname;
            this.assemblyb = assb;
            this.assembly = assb;
            this.transient = transient;
            this.guid = Guid.FastNewGuidArray();
            this.table_idx = this.get_next_table_index(this, 0, 1);
            this.name_cache = new Dictionary<TypeName, TypeBuilder>();
            this.us_string_cache = new Dictionary<string, int>(512);
            ModuleBuilder.basic_init(this);
            this.CreateGlobalType();
            if (assb.IsRun)
            {
                Type type = new TypeBuilder(this, TypeAttributes.Abstract, 16777215).CreateType();
                ModuleBuilder.set_wrappers_type(this, type);
            }
            if (emitSymbolInfo)
            {
                Assembly assembly = Assembly.LoadWithPartialName("Mono.CompilerServices.SymbolWriter");
                Type type2 = null;
                if (assembly != null)
                {
                    type2 = assembly.GetType("Mono.CompilerServices.SymbolWriter.SymbolWriterImpl");
                }
                if (type2 == null)
                {
                    ModuleBuilder.WarnAboutSymbolWriter("Failed to load the default Mono.CompilerServices.SymbolWriter assembly");
                }
                else
                {
                    try
                    {
                        this.symbolWriter = (ISymbolWriter)Activator.CreateInstance(type2, new object[] { this });
                    }
                    catch (MissingMethodException)
                    {
                        ModuleBuilder.WarnAboutSymbolWriter("The default Mono.CompilerServices.SymbolWriter is not available on this platform");
                        return;
                    }
                }
                string text = this.fqname;
                if (this.assemblyb.AssemblyDir != null)
                {
                    text = Path.Combine(this.assemblyb.AssemblyDir, text);
                }
                this.symbolWriter.Initialize(IntPtr.Zero, text, true);
            }
        }
References System.Reflection.Emit.ModuleBuilder.assembly, System.Reflection.Emit.ModuleBuilder.assemblyb, System.Reflection.Emit.AssemblyBuilder.AssemblyDir, System.Reflection.Emit.ModuleBuilder.basic_init(), System.IO.Path.Combine(), System.Reflection.Emit.ModuleBuilder.CreateGlobalType(), System.Activator.CreateInstance(), System.Reflection.Emit.TypeBuilder.CreateType(), System.Guid.FastNewGuidArray(), System.Reflection.Emit.ModuleBuilder.fqname, System.Reflection.Emit.ModuleBuilder.get_next_table_index(), System.Reflection.Assembly.GetType(), System.Diagnostics.SymbolStore.ISymbolWriter.Initialize(), System.Reflection.Emit.AssemblyBuilder.IsRun, System.Reflection.Assembly.LoadWithPartialName(), System.Reflection.Emit.ModuleBuilder.name, System.Reflection.Emit.ModuleBuilder.set_wrappers_type(), System.Reflection.Emit.ModuleBuilder.symbolWriter, System.text, System.Reflection.Emit.ModuleBuilder.WarnAboutSymbolWriter(), and System.IntPtr.Zero.