Terraria Decompiled: System.Reflection.Emit.ModuleBuilder.GetType
GetType() [3/3]
override Type System.Reflection.Emit.ModuleBuilder.GetType (string className, bool throwOnError, bool ignoreCase) inline virtual
Reimplemented from System.Reflection.Module.
Definition at line 474 of file ModuleBuilder.cs.
        {
            if (className == null)
            {
                throw new ArgumentNullException("className");
            }
            if (className.Length == 0)
            {
                throw new ArgumentException("className");
            }
            TypeBuilder typeBuilder = null;
            if (this.types == null && throwOnError)
            {
                throw new TypeLoadException(className);
            }
            TypeSpec typeSpec = TypeSpec.Parse(className);
            if (!ignoreCase)
            {
                TypeName typeName = typeSpec.TypeNameWithoutModifiers();
                this.name_cache.TryGetValue(typeName, out typeBuilder);
            }
            else
            {
                if (this.types != null)
                {
                    typeBuilder = this.search_in_array(this.types, this.num_types, typeSpec.Name);
                }
                if (!typeSpec.IsNested && typeBuilder != null)
                {
                    typeBuilder = this.GetMaybeNested(typeBuilder, typeSpec.Nested);
                }
            }
            if (typeBuilder == null && throwOnError)
            {
                throw new TypeLoadException(className);
            }
            if (typeBuilder != null && (typeSpec.HasModifiers || typeSpec.IsByRef))
            {
                Type type = typeBuilder;
                if (typeBuilder != null)
                {
                    TypeBuilder typeBuilder2 = typeBuilder;
                    if (typeBuilder2.is_created)
                    {
                        type = typeBuilder2.CreateType();
                    }
                }
                foreach (ModifierSpec modifierSpec in typeSpec.Modifiers)
                {
                    if (modifierSpec is PointerSpec)
                    {
                        type = type.MakePointerType();
                    }
                    else if (modifierSpec is ArraySpec)
                    {
                        ArraySpec arraySpec = modifierSpec as ArraySpec;
                        if (arraySpec.IsBound)
{
                            return null;
                        }
                        if (arraySpec.Rank == 1)
{
                            type = type.MakeArrayType();
                        }
                        else
{
                            type = type.MakeArrayType(arraySpec.Rank);
                        }
                    }
                }
                if (typeSpec.IsByRef)
                {
                    type = type.MakeByRefType();
                }
                typeBuilder = type as TypeBuilder;
                if (typeBuilder == null)
                {
                    return type;
                }
            }
            IL_0186:
            if (typeBuilder != null && typeBuilder.is_created)
            {
                return typeBuilder.CreateType();
            }
            return typeBuilder;
        }
References System.Reflection.Emit.TypeBuilder.CreateType(), System.TypeSpec.HasModifiers, System.Reflection.Emit.TypeBuilder.is_created, System.ArraySpec.IsBound, System.TypeSpec.IsByRef, System.TypeSpec.IsNested, System.Type.MakePointerType(), System.TypeSpec.Modifiers, System.TypeSpec.Name, System.TypeSpec.Nested, System.TypeSpec.Parse(), System.ArraySpec.Rank, and System.TypeSpec.TypeNameWithoutModifiers().