Terraria Decompiled: Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids
DrawNormalLiquids()
unsafe void Terraria.GameContent.Liquid.LiquidRenderer.DrawNormalLiquids (SpriteBatch spriteBatch, Vector2 drawOffset, int waterStyle, float globalAlpha, bool isBackgroundDraw, bool waterOnly) inline
Definition at line 554 of file LiquidRenderer.cs.
        {
            Rectangle drawArea = this._drawArea;
            Main.tileBatch.Restart();
            fixed (LiquidRenderer.LiquidDrawCache* ptr = &this._drawCache[0])
            {
                LiquidRenderer.LiquidDrawCache* ptr2 = ptr;
                for (int i = drawArea.X; i < drawArea.X + drawArea.Width; i++)
                {
                    for (int j = drawArea.Y; j < drawArea.Y + drawArea.Height; j++)
                    {
                        if (ptr2->IsVisible && (!waterOnly || ptr2->Type == 0))
{
                            Main.tileBatch.SetLayer(0U, 0);
                            Rectangle sourceRectangle = ptr2->SourceRectangle;
                            if (ptr2->IsSurfaceLiquid)
{
                                sourceRectangle.Y = 1280;
                            }
                            else if (sourceRectangle.X == 16)
{
                                sourceRectangle.Y += this._waterfallAnimationFrame * 80;
                            }
                            else
{
                                sourceRectangle.Y += this._animationFrame * 80;
                            }
                            Vector2 liquidOffset = ptr2->LiquidOffset;
                            float num = ptr2->Opacity * (isBackgroundDraw ? 1f : LiquidRenderer.DEFAULT_OPACITY[(int)ptr2->Type]);
                            int num2 = (int)ptr2->Type;
                            if (num2 == 0)
{
                                num2 = waterStyle;
                                num *= globalAlpha;
                            }
                            else if (num2 == 1)
{
                                num *= Main.player[Main.myPlayer].lavaOpacity;
                            }
                            else if (num2 == 2)
{
                                num2 = 11;
                            }
                            num = Math.Min(1f, num);
                            VertexColors vertexColors;
                            Lighting.GetCornerColors(i, j, out vertexColors, 1f);
                            vertexColors.BottomLeftColor *= num;
                            vertexColors.BottomRightColor *= num;
                            vertexColors.TopLeftColor *= num;
                            vertexColors.TopRightColor *= num;
                            Main.DrawTileInWater(drawOffset, i, j);
                            Main.tileBatch.Draw(this._liquidTextures[num2].Value, new Vector2((float)(i << 4), (float)(j << 4)) + drawOffset + liquidOffset, new Rectangle?(sourceRectangle), vertexColors, Vector2.Zero, 1f, SpriteEffects.None);
                        }
                        ptr2++;
                    }
                }
            }
            int num3 = Main.tileBatch.End();
            (isBackgroundDraw ? TimeLogger.LiquidBackgroundDrawCalls : TimeLogger.LiquidDrawCalls).Add(num3);
        }
References Terraria.GameContent.Liquid.LiquidRenderer._drawArea, Terraria.GameContent.Liquid.LiquidRenderer._liquidTextures, Microsoft.Xna.Framework.Graphics.Add, Terraria.GameContent.Liquid.LiquidRenderer.DEFAULT_OPACITY, Terraria.Graphics.TileBatch.Draw(), Terraria.Main.DrawTileInWater(), Terraria.Graphics.TileBatch.End(), Terraria.Lighting.GetCornerColors(), Microsoft.Xna.Framework.Rectangle.Height, int, Terraria.Player.lavaOpacity, Terraria.TimeLogger.LiquidDrawCalls, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Graphics.TileBatch.Restart(), Terraria.Graphics.TileBatch.SetLayer(), Terraria.Main.tileBatch, System.U, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DrawLiquid().