Terraria Decompiled: System.Reflection.Emit.ModuleBuilder.Save
Save()
void System.Reflection.Emit.ModuleBuilder.Save () inline package
Definition at line 1205 of file ModuleBuilder.cs.
        {
            if (this.transient && !this.is_main)
            {
                return;
            }
            if (this.types != null)
            {
                for (int i = 0; i < this.num_types; i++)
                {
                    if (!this.types[i].is_created)
                    {
                        throw new NotSupportedException("Type '" + this.types[i].FullName + "' was not completed.");
                    }
                }
            }
            this.FixupTokens();
            if (this.global_type != null && this.global_type_created == null)
            {
                this.global_type_created = this.global_type.CreateType();
            }
            if (this.resources != null)
            {
                for (int j = 0; j < this.resources.Length; j++)
                {
                    IResourceWriter resourceWriter;
                    if (this.resource_writers != null && (resourceWriter = this.resource_writers[this.resources[j].name] as IResourceWriter) != null)
                    {
                        ResourceWriter resourceWriter2 = (ResourceWriter)resourceWriter;
                        resourceWriter2.Generate();
                        MemoryStream memoryStream = (MemoryStream)resourceWriter2._output;
                        this.resources[j].data = new byte[memoryStream.Length];
                        memoryStream.Seek(0L, SeekOrigin.Begin);
                        memoryStream.Read(this.resources[j].data, 0, (int)memoryStream.Length);
                    }
                    else
                    {
                        Stream stream = this.resources[j].stream;
                        if (stream != null)
{
                            try
{
                                long length = stream.Length;
                                this.resources[j].data = new byte[length];
                                stream.Seek(0L, SeekOrigin.Begin);
                                stream.Read(this.resources[j].data, 0, (int)length);
                            }
                            catch
{
                            }
                        }
                    }
                }
            }
            ModuleBuilder.build_metadata(this);
            string text = this.fqname;
            if (this.assemblyb.AssemblyDir != null)
            {
                text = Path.Combine(this.assemblyb.AssemblyDir, text);
            }
            try
            {
                File.Delete(text);
            }
            catch
            {
            }
            using (FileStream fileStream = new FileStream(text, FileMode.Create, FileAccess.Write))
            {
                this.WriteToFile(fileStream.Handle);
            }
            File.SetAttributes(text, (FileAttributes)(-2147483648));
            if (this.types != null && this.symbolWriter != null)
            {
                for (int k = 0; k < this.num_types; k++)
                {
                    this.types[k].GenerateDebugInfo(this.symbolWriter);
                }
                this.symbolWriter.Close();
            }
        }
References System.Resources.ResourceWriter._output, System.Reflection.Emit.ModuleBuilder.build_metadata(), System.IO.Path.Combine(), System.IO.File.Delete(), System.FullName, System.Resources.ResourceWriter.Generate(), System.IO.FileStream.Handle, System.L, System.length, System.IO.MemoryStream.Length, System.IO.Stream.Length, System.name, System.IO.MemoryStream.Read(), System.IO.Stream.Read(), System.IO.MemoryStream.Seek(), System.IO.Stream.Seek(), System.IO.File.SetAttributes(), and System.text.
Referenced by System.Reflection.Emit.AssemblyBuilder.Save().