Terraria Decompiled: Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor
GetShimmerGlitterColor()
static Color Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterColor (bool top, float worldPositionX, float worldPositionY) inline static
Definition at line 703 of file LiquidRenderer.cs.
        {
            Color color = Main.hslToRgb((float)(((double)(worldPositionX + worldPositionY / 6f) + Main.timeForVisualEffects / 30.0) / 6.0) % 1f, 1f, 0.5f, byte.MaxValue);
            color.A = 0;
            return new Color(color.ToVector4() * LiquidRenderer.GetShimmerGlitterOpacity(top, worldPositionX, worldPositionY));
        }
References Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterOpacity(), Terraria.Main.hslToRgb(), Terraria.Main.timeForVisualEffects, and Microsoft.Xna.Framework.Color.ToVector4().
Referenced by Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_10_BackAcc(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_32_FrontAcc_BackPart(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_32_FrontAcc_FrontPart(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.Main.oldDrawWater(), and Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors_Sparkle().