Terraria Decompiled: System.Reflection.Emit.ModuleBuilder.ResolveOrGetRegisteredToken
ResolveOrGetRegisteredToken()
MemberInfo System.Reflection.Emit.ModuleBuilder.ResolveOrGetRegisteredToken (int metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) inline package
Definition at line 1395 of file ModuleBuilder.cs.
        {
            ResolveTokenError resolveTokenError;
            MemberInfo memberInfo = RuntimeModule.ResolveMemberToken(this._impl, metadataToken, RuntimeModule.ptrs_from_types(genericTypeArguments), RuntimeModule.ptrs_from_types(genericMethodArguments), out resolveTokenError);
            if (memberInfo != null)
            {
                return memberInfo;
            }
            memberInfo = this.GetRegisteredToken(metadataToken) as MemberInfo;
            if (memberInfo == null)
            {
                throw RuntimeModule.resolve_token_exception(this.Name, metadataToken, resolveTokenError, "MemberInfo");
            }
            return memberInfo;
        }
References System.Reflection.Name, System.Reflection.RuntimeModule.ptrs_from_types(), System.Reflection.RuntimeModule.resolve_token_exception(), and System.Reflection.RuntimeModule.ResolveMemberToken().