Terraria Decompiled: System.Reflection.Emit.ModuleBuilder.GetToken
GetToken() [6/6]
int System.Reflection.Emit.ModuleBuilder.GetToken (string str) inline package
Definition at line 896 of file ModuleBuilder.cs.
        {
            int usindex;
            if (!this.us_string_cache.TryGetValue(str, out usindex))
            {
                usindex = ModuleBuilder.getUSIndex(this, str);
                this.us_string_cache[str] = usindex;
            }
            return usindex;
        }
References System.Reflection.Emit.ModuleBuilder.getUSIndex().
Referenced by System.Reflection.Emit.ModuleBuilderTokenGenerator.GetToken(), System.Reflection.Emit.ModuleBuilderTokenGenerator.GetToken(), System.Reflection.Emit.ModuleBuilderTokenGenerator.GetToken(), and System.Reflection.Emit.ModuleBuilderTokenGenerator.GetToken().