Terraria Decompiled: System.IO.BufferedStream.CopyToAsyncCore
CopyToAsyncCore()
async Task System.IO.BufferedStream.CopyToAsyncCore (Stream destination, int bufferSize, CancellationToken cancellationToken) inline private
Definition at line 1028 of file BufferedStream.cs.
        {
            await this.LazyEnsureAsyncActiveSemaphoreInitialized().WaitAsync().ConfigureAwait(false);
            try
            {
                int num = this._readLen - this._readPos;
                if (num > 0)
                {
                    await destination.WriteAsync(new ReadOnlyMemory<byte>(this._buffer, this._readPos, num), cancellationToken).ConfigureAwait(false);
                    int num2 = 0;
                    this._readLen = num2;
                    this._readPos = num2;
                }
                else if (this._writePos > 0)
                {
                    await this.FlushWriteAsync(cancellationToken).ConfigureAwait(false);
                }
                await this._stream.CopyToAsync(destination, bufferSize, cancellationToken).ConfigureAwait(false);
            }
            finally
            {
                this._asyncActiveSemaphore.Release();
            }
        }
References System.IO.BufferedStream._asyncActiveSemaphore, System.IO.BufferedStream._buffer, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.CopyToAsync(), System.destination, System.IO.BufferedStream.FlushWriteAsync(), System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.Threading.SemaphoreSlim.Release(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.BufferedStream.CopyToAsync(), and System.IO.BufferedStream.d__71.MoveNext().