Terraria Decompiled: System.IO.BufferedStream.Flush
Flush()
override void System.IO.BufferedStream.Flush () inline
Definition at line 258 of file BufferedStream.cs.
        {
            this.EnsureNotClosed();
            if (this._writePos > 0)
            {
                this.FlushWrite();
                return;
            }
            if (this._readPos < this._readLen)
            {
                if (this._stream.CanSeek)
                {
                    this.FlushRead();
                }
                if (this._stream.CanWrite)
                {
                    this._stream.Flush();
                }
                return;
            }
            if (this._stream.CanWrite)
            {
                this._stream.Flush();
            }
            this._writePos = (this._readPos = (this._readLen = 0));
        }
References System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.Stream.CanSeek, System.IO.Stream.CanWrite, System.IO.BufferedStream.EnsureNotClosed(), System.IO.Stream.Flush(), System.IO.BufferedStream.FlushRead(), and System.IO.BufferedStream.FlushWrite().
Referenced by System.IO.BufferedStream.Dispose(), and System.IO.BufferedStream.SetLength().