Terraria Decompiled: System.IO.BufferedStream.WriteToBuffer
WriteToBuffer() [3/3]
int System.IO.BufferedStream.WriteToBuffer (ReadOnlySpan< byte > buffer) inline private
Definition at line 701 of file BufferedStream.cs.
        {
            int num = Math.Min(this._bufferSize - this._writePos, buffer.Length);
            if (num > 0)
            {
                this.EnsureBufferAllocated();
                buffer.Slice(0, num).CopyTo(new Span<byte>(this._buffer, this._writePos, num));
                this._writePos += num;
            }
            return num;
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._writePos, System.IO.BufferedStream.EnsureBufferAllocated(), System.ReadOnlySpan< T >.Length, System.Math.Min(), and System.ReadOnlySpan< T >.Slice().