Terraria Decompiled: System.IO.BufferedStream.Read
Read() [1/2]
override int System.IO.BufferedStream.Read (byte[] array, int offset, int count) inline
Definition at line 418 of file BufferedStream.cs.
        {
            if (array == null)
            {
                throw new ArgumentNullException("array", "Buffer cannot be null.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (array.Length - offset < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            this.EnsureNotClosed();
            this.EnsureCanRead();
            int num = this.ReadFromBuffer(array, offset, count);
            if (num == count)
            {
                return num;
            }
            int num2 = num;
            if (num > 0)
            {
                count -= num;
                offset += num;
            }
            this._readPos = (this._readLen = 0);
            if (this._writePos > 0)
            {
                this.FlushWrite();
            }
            if (count >= this._bufferSize)
            {
                return this._stream.Read(array, offset, count) + num2;
            }
            this.EnsureBufferAllocated();
            this._readLen = this._stream.Read(this._buffer, 0, this._bufferSize);
            num = this.ReadFromBuffer(array, offset, count);
            return num + num2;
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.array, System.count, System.IO.BufferedStream.EnsureBufferAllocated(), System.IO.BufferedStream.EnsureCanRead(), System.IO.BufferedStream.EnsureNotClosed(), System.IO.BufferedStream.FlushWrite(), System.offset, System.IO.Stream.Read(), and System.IO.BufferedStream.ReadFromBuffer().