Terraria Decompiled: System.IO.BufferedStream.ReadAsync
ReadAsync() [2/2]
override ValueTask< int > System.IO.BufferedStream.ReadAsync (Memory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 558 of file BufferedStream.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return new ValueTask<int>(Task.FromCanceled<int>(cancellationToken));
            }
            this.EnsureNotClosed();
            this.EnsureCanRead();
            int num = 0;
            SemaphoreSlim semaphoreSlim = this.LazyEnsureAsyncActiveSemaphoreInitialized();
            Task task = semaphoreSlim.WaitAsync();
            if (task.IsCompletedSuccessfully)
            {
                bool flag = true;
                try
                {
                    num = this.ReadFromBuffer(buffer.Span);
                    flag = num == buffer.Length;
                    if (flag)
                    {
                        return new ValueTask<int>(num);
                    }
                }
                finally
                {
                    if (flag)
                    {
                        semaphoreSlim.Release();
                    }
                }
            }
            return this.ReadFromUnderlyingStreamAsync(buffer.Slice(num), cancellationToken, num, task);
        }
References System.IO.BufferedStream.EnsureCanRead(), System.IO.BufferedStream.EnsureNotClosed(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.Memory< T >.Length, System.IO.BufferedStream.ReadFromBuffer(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.Threading.SemaphoreSlim.Release(), System.Memory< T >.Slice(), System.Memory< T >.Span, System.task, and System.Threading.SemaphoreSlim.WaitAsync().