Terraria Decompiled: Newtonsoft.Json.Linq.JObject.MergeItem
MergeItem()
override void Newtonsoft.Json.Linq.JObject.MergeItem (object content, JsonMergeSettings settings) inline package
Definition at line 167 of file JObject.cs.
        {
            JObject jobject = content as JObject;
            if (jobject == null)
            {
                return;
            }
            foreach (KeyValuePair<string, JToken> keyValuePair in jobject)
            {
                JProperty jproperty = this.Property(keyValuePair.Key);
                if (jproperty == null)
                {
                    this.Add(keyValuePair.Key, keyValuePair.Value);
                }
                else if (keyValuePair.Value != null)
                {
                    JContainer jcontainer = jproperty.Value as JContainer;
                    if (jcontainer == null || jcontainer.Type != keyValuePair.Value.Type)
                    {
                        if (keyValuePair.Value.Type != JTokenType.Null || (settings != null && settings.MergeNullValueHandling == MergeNullValueHandling.Merge))
{
                            jproperty.Value = keyValuePair.Value;
                        }
                    }
                    else
                    {
                        jcontainer.Merge(keyValuePair.Value, settings);
                    }
                }
            }
        }
References System.Add, Newtonsoft.Json.Linq.JContainer.JContainer(), Newtonsoft.Json.Linq.JObject.JObject(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Newtonsoft.Json.Linq.JContainer.Merge(), Newtonsoft.Json.Linq.Property, Newtonsoft.Json.Linq.JToken.Type, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.