Terraria Decompiled: System.IO.BufferedStream.CopyToAsync
CopyToAsync()
override Task System.IO.BufferedStream.CopyToAsync (Stream destination, int bufferSize, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 1017 of file BufferedStream.cs.
        {
            StreamHelpers.ValidateCopyToArgs(this, destination, bufferSize);
            if (!cancellationToken.IsCancellationRequested)
            {
                return this.CopyToAsyncCore(destination, bufferSize, cancellationToken);
            }
            return Task.FromCanceled<int>(cancellationToken);
        }
References System.IO.BufferedStream.CopyToAsyncCore(), System.destination, System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.CancellationToken.IsCancellationRequested, and System.IO.StreamHelpers.ValidateCopyToArgs().