Terraria Decompiled: System.IO.BufferedStream.ReadFromBuffer
ReadFromBuffer() [1/3]
int System.IO.BufferedStream.ReadFromBuffer (byte[] array, int offset, int count) inline private
Definition at line 372 of file BufferedStream.cs.
        {
            int num = this._readLen - this._readPos;
            if (num == 0)
            {
                return 0;
            }
            if (num > count)
            {
                num = count;
            }
            Buffer.BlockCopy(this._buffer, this._readPos, array, offset, num);
            this._readPos += num;
            return num;
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._readPos, System.array, System.Buffer.BlockCopy(), System.count, and System.offset.
Referenced by System.IO.BufferedStream.d__51.MoveNext(), System.IO.BufferedStream.Read(), System.IO.BufferedStream.Read(), System.IO.BufferedStream.ReadAsync(), System.IO.BufferedStream.ReadAsync(), System.IO.BufferedStream.ReadFromBuffer(), and System.IO.BufferedStream.ReadFromUnderlyingStreamAsync().