Terraria Decompiled: System.IO.BufferedStream.FlushRead
FlushRead()
void System.IO.BufferedStream.FlushRead () inline private
Definition at line 330 of file BufferedStream.cs.
        {
            if (this._readPos - this._readLen != 0)
            {
                this._stream.Seek((long)(this._readPos - this._readLen), SeekOrigin.Current);
            }
            this._readPos = 0;
            this._readLen = 0;
        }
References System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, and System.IO.Stream.Seek().
Referenced by System.IO.BufferedStream.ClearReadBufferBeforeWrite(), System.IO.BufferedStream.Flush(), System.IO.BufferedStream.FlushAsyncInternal(), and System.IO.BufferedStream.d__38.MoveNext().