Terraria Decompiled: System.IO.BufferedStream.DisposeAsync
DisposeAsync()
override async ValueTask System.IO.BufferedStream.DisposeAsync () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 197 of file BufferedStream.cs.
        {
            try
            {
                if (this._stream != null)
                {
                    object obj = null;
                    try
                    {
                        await base.FlushAsync().ConfigureAwait(false);
                    }
                    catch (object obj)
                    {
                    }
                    await this._stream.DisposeAsync().ConfigureAwait(false);
                    object obj2 = obj;
                    if (obj2 != null)
                    {
                        Exception ex = obj2 as Exception;
                        if (ex == null)
{
                            throw obj2;
                        }
                        ExceptionDispatchInfo.Capture(ex).Throw();
                    }
                    obj = null;
                }
            }
            finally
            {
                this._stream = null;
                this._buffer = null;
            }
        }
References System.IO.BufferedStream._stream, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Threading.Tasks.ValueTask< TResult >.ConfigureAwait(), System.IO.Stream.DisposeAsync(), System.obj, and System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw().
Referenced by System.IO.BufferedStream.d__34.MoveNext().