Terraria Decompiled: System.IO.BufferedStream.WriteAsync
WriteAsync() [2/2]
override ValueTask System.IO.BufferedStream.WriteAsync (ReadOnlyMemory< byte > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 843 of file BufferedStream.cs.
        {
            if (cancellationToken.IsCancellationRequested)
            {
                return new ValueTask(Task.FromCanceled<int>(cancellationToken));
            }
            this.EnsureNotClosed();
            this.EnsureCanWrite();
            SemaphoreSlim semaphoreSlim = this.LazyEnsureAsyncActiveSemaphoreInitialized();
            Task task = semaphoreSlim.WaitAsync();
            if (task.IsCompletedSuccessfully)
            {
                bool flag = true;
                try
                {
                    if (this._writePos == 0)
                    {
                        this.ClearReadBufferBeforeWrite();
                    }
                    flag = buffer.Length < this._bufferSize - this._writePos;
                    if (flag)
                    {
                        this.WriteToBuffer(buffer.Span);
                        return default(ValueTask);
                    }
                }
                finally
                {
                    if (flag)
                    {
                        semaphoreSlim.Release();
                    }
                }
            }
            return new ValueTask(this.WriteToUnderlyingStreamAsync(buffer, cancellationToken, task));
        }
References System.IO.BufferedStream._writePos, System.IO.BufferedStream.ClearReadBufferBeforeWrite(), System.IO.BufferedStream.EnsureCanWrite(), System.IO.BufferedStream.EnsureNotClosed(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.Threading.SemaphoreSlim.Release(), System.ReadOnlyMemory< T >.Span, System.task, System.Threading.SemaphoreSlim.WaitAsync(), System.IO.BufferedStream.WriteToBuffer(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().