Terraria Decompiled: System.IO.BufferedStream.WriteByte
WriteByte()
override void System.IO.BufferedStream.WriteByte (byte value) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 938 of file BufferedStream.cs.
        {
            this.EnsureNotClosed();
            if (this._writePos == 0)
            {
                this.EnsureCanWrite();
                this.ClearReadBufferBeforeWrite();
                this.EnsureBufferAllocated();
            }
            if (this._writePos >= this._bufferSize - 1)
            {
                this.FlushWrite();
            }
            byte[] buffer = this._buffer;
            int writePos = this._writePos;
            this._writePos = writePos + 1;
            buffer[writePos] = value;
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._writePos, System.IO.BufferedStream.ClearReadBufferBeforeWrite(), System.IO.BufferedStream.EnsureBufferAllocated(), System.IO.BufferedStream.EnsureCanWrite(), System.IO.BufferedStream.EnsureNotClosed(), System.IO.BufferedStream.FlushWrite(), and System.value.