Terraria Decompiled: System.IO.BufferedStream.CopyTo
CopyTo()
override void System.IO.BufferedStream.CopyTo (Stream destination, int bufferSize) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 1000 of file BufferedStream.cs.
        {
            StreamHelpers.ValidateCopyToArgs(this, destination, bufferSize);
            int num = this._readLen - this._readPos;
            if (num > 0)
            {
                destination.Write(this._buffer, this._readPos, num);
                this._readPos = (this._readLen = 0);
            }
            else if (this._writePos > 0)
            {
                this.FlushWrite();
            }
            this._stream.CopyTo(destination, bufferSize);
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.Stream.CopyTo(), System.destination, System.IO.BufferedStream.FlushWrite(), and System.IO.StreamHelpers.ValidateCopyToArgs().