Terraria Decompiled: System.IO.BufferedStream.ClearReadBufferBeforeWrite
ClearReadBufferBeforeWrite()
void System.IO.BufferedStream.ClearReadBufferBeforeWrite () inline private
Definition at line 341 of file BufferedStream.cs.
        {
            if (this._readPos == this._readLen)
            {
                this._readPos = (this._readLen = 0);
                return;
            }
            if (!this._stream.CanSeek)
            {
                throw new NotSupportedException("Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.");
            }
            this.FlushRead();
        }
References System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.Stream.CanSeek, and System.IO.BufferedStream.FlushRead().
Referenced by System.IO.BufferedStream.d__63.MoveNext(), System.IO.BufferedStream.Write(), System.IO.BufferedStream.Write(), System.IO.BufferedStream.WriteAsync(), System.IO.BufferedStream.WriteByte(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().