Terraria Decompiled: Newtonsoft.Json.Linq.JObject.Load
Load() [2/2]
static new JObject Newtonsoft.Json.Linq.JObject.Load (JsonReader reader, JsonLoadSettings settings) inline static
Definition at line 318 of file JObject.cs.
        {
            ValidationUtils.ArgumentNotNull(reader, "reader");
            if (reader.TokenType == JsonToken.None && !reader.Read())
            {
                throw JsonReaderException.Create(reader, "Error reading JObject from JsonReader.");
            }
            reader.MoveToContent();
            if (reader.TokenType != JsonToken.StartObject)
            {
                throw JsonReaderException.Create(reader, "Error reading JObject from JsonReader. Current JsonReader item is not an object: {0}".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
            }
            JObject jobject = new JObject();
            jobject.SetLineInfo(reader as IJsonLineInfo, settings);
            jobject.ReadTokenFrom(reader, settings);
            return jobject;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JObject.JObject(), Newtonsoft.Json.JsonReader.MoveToContent(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(), Newtonsoft.Json.Linq.JToken.SetLineInfo(), and Newtonsoft.Json.JsonReader.TokenType.