Terraria Decompiled: System.IO.BufferedStream.Seek
Seek()
override long System.IO.BufferedStream.Seek (long offset, SeekOrigin origin) inline
Definition at line 958 of file BufferedStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureCanSeek();
            if (this._writePos > 0)
            {
                this.FlushWrite();
                return this._stream.Seek(offset, origin);
            }
            if (this._readLen - this._readPos > 0 && origin == SeekOrigin.Current)
            {
                offset -= (long)(this._readLen - this._readPos);
            }
            long position = this.Position;
            long num = this._stream.Seek(offset, origin);
            this._readPos = (int)(num - (position - (long)this._readPos));
            if (0 <= this._readPos && this._readPos < this._readLen)
            {
                this._stream.Seek((long)(this._readLen - this._readPos), SeekOrigin.Current);
            }
            else
            {
                this._readPos = (this._readLen = 0);
            }
            return num;
        }
References System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.BufferedStream.EnsureCanSeek(), System.IO.BufferedStream.EnsureNotClosed(), System.IO.BufferedStream.FlushWrite(), int, long, System.offset, System.IO.BufferedStream.Position, and System.IO.Stream.Seek().