Terraria Decompiled: Newtonsoft.Json.Linq.JObject.InternalPropertyChanged
InternalPropertyChanged()
void Newtonsoft.Json.Linq.JObject.InternalPropertyChanged (JProperty childProperty) inline package
Definition at line 200 of file JObject.cs.
        {
            this.OnPropertyChanged(childProperty.Name);
            if (this._listChanged != null)
            {
                this.OnListChanged(new ListChangedEventArgs(4, this.IndexOfItem(childProperty)));
            }
            if (this._collectionChanged != null)
            {
                this.OnCollectionChanged(new NotifyCollectionChangedEventArgs(2, childProperty, childProperty, this.IndexOfItem(childProperty)));
            }
        }
References Newtonsoft.Json.Linq.JContainer._collectionChanged, Newtonsoft.Json.Linq.JContainer._listChanged, Newtonsoft.Json.Linq.JObject.IndexOfItem(), Newtonsoft.Json.Linq.JProperty.Name, Newtonsoft.Json.Linq.JContainer.OnCollectionChanged(), Newtonsoft.Json.Linq.JContainer.OnListChanged(), and Newtonsoft.Json.Linq.JObject.OnPropertyChanged().
Referenced by Newtonsoft.Json.Linq.JProperty.SetItem().