Terraria Decompiled: System.IO.BufferedStream.ReadAsync
ReadAsync() [1/2]
override Task< int > System.IO.BufferedStream.ReadAsync (byte[] buffer, int offset, int count, CancellationToken cancellationToken) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 506 of file BufferedStream.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer", "Buffer cannot be null.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (buffer.Length - offset < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            if (cancellationToken.IsCancellationRequested)
            {
                return Task.FromCanceled<int>(cancellationToken);
            }
            this.EnsureNotClosed();
            this.EnsureCanRead();
            int num = 0;
            SemaphoreSlim semaphoreSlim = this.LazyEnsureAsyncActiveSemaphoreInitialized();
            Task task = semaphoreSlim.WaitAsync();
            if (task.IsCompletedSuccessfully)
            {
                bool flag = true;
                try
                {
                    Exception ex;
                    num = this.ReadFromBuffer(buffer, offset, count, out ex);
                    flag = num == count || ex != null;
                    if (flag)
                    {
                        return (ex == null) ? this.LastSyncCompletedReadTask(num) : Task.FromException<int>(ex);
                    }
                }
                finally
                {
                    if (flag)
                    {
                        semaphoreSlim.Release();
                    }
                }
            }
            return this.ReadFromUnderlyingStreamAsync(new Memory<byte>(buffer, offset + num, count - num), cancellationToken, num, task).AsTask();
        }
References System.count, System.IO.BufferedStream.EnsureCanRead(), System.IO.BufferedStream.EnsureNotClosed(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.Task< TResult >.FromException(), System.Threading.CancellationToken.IsCancellationRequested, System.IO.BufferedStream.LastSyncCompletedReadTask(), System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.offset, System.IO.BufferedStream.ReadFromBuffer(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.Threading.SemaphoreSlim.Release(), System.task, and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.BufferedStream.BeginRead().