Terraria Decompiled: System.IO.BufferedStream.WriteToBuffer
WriteToBuffer() [1/3]
void System.IO.BufferedStream.WriteToBuffer (byte[] array, ref int offset, ref int count) inline private
Definition at line 686 of file BufferedStream.cs.
        {
            int num = Math.Min(this._bufferSize - this._writePos, count);
            if (num <= 0)
            {
                return;
            }
            this.EnsureBufferAllocated();
            Buffer.BlockCopy(array, offset, this._buffer, this._writePos, num);
            this._writePos += num;
            count -= num;
            offset += num;
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._writePos, System.array, System.Buffer.BlockCopy(), System.count, System.IO.BufferedStream.EnsureBufferAllocated(), System.Math.Min(), and System.offset.
Referenced by System.IO.BufferedStream.d__63.MoveNext(), System.IO.BufferedStream.Write(), System.IO.BufferedStream.Write(), System.IO.BufferedStream.WriteAsync(), System.IO.BufferedStream.WriteToBuffer(), and System.IO.BufferedStream.WriteToUnderlyingStreamAsync().