Terraria Decompiled: System.IO.BufferedStream.Write
Write() [2/2]
override void System.IO.BufferedStream.Write (ReadOnlySpan< byte > buffer) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 782 of file BufferedStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureCanWrite();
            if (this._writePos == 0)
            {
                this.ClearReadBufferBeforeWrite();
            }
            int num = checked(this._writePos + buffer.Length);
            if (checked(num + buffer.Length >= this._bufferSize + this._bufferSize))
            {
                if (this._writePos > 0)
                {
                    if (num <= this._bufferSize + this._bufferSize && num <= 81920)
                    {
                        this.EnsureShadowBufferAllocated();
                        buffer.CopyTo(new Span<byte>(this._buffer, this._writePos, buffer.Length));
                        this._stream.Write(this._buffer, 0, num);
                        this._writePos = 0;
                        return;
                    }
                    this._stream.Write(this._buffer, 0, this._writePos);
                    this._writePos = 0;
                }
                this._stream.Write(buffer);
                return;
            }
            int num2 = this.WriteToBuffer(buffer);
            if (this._writePos < this._bufferSize)
            {
                return;
            }
            buffer = buffer.Slice(num2);
            this._stream.Write(this._buffer, 0, this._writePos);
            this._writePos = 0;
            num2 = this.WriteToBuffer(buffer);
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.BufferedStream.ClearReadBufferBeforeWrite(), System.ReadOnlySpan< T >.CopyTo(), System.IO.BufferedStream.EnsureCanWrite(), System.IO.BufferedStream.EnsureNotClosed(), System.IO.BufferedStream.EnsureShadowBufferAllocated(), System.ReadOnlySpan< T >.Length, System.ReadOnlySpan< T >.Slice(), System.IO.Stream.Write(), and System.IO.BufferedStream.WriteToBuffer().