Terraria Decompiled: System.IO.BufferedStream.FlushWriteAsync
FlushWriteAsync()
async Task System.IO.BufferedStream.FlushWriteAsync (CancellationToken cancellationToken) inline private
Definition at line 364 of file BufferedStream.cs.
        {
            await this._stream.WriteAsync(new ReadOnlyMemory<byte>(this._buffer, 0, this._writePos), cancellationToken).ConfigureAwait(false);
            this._writePos = 0;
            await this._stream.FlushAsync(cancellationToken).ConfigureAwait(false);
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.FlushAsync(), and System.IO.Stream.WriteAsync().
Referenced by System.IO.BufferedStream.CopyToAsyncCore(), System.IO.BufferedStream.FlushAsyncInternal(), System.IO.BufferedStream.d__38.MoveNext(), System.IO.BufferedStream.d__42.MoveNext(), System.IO.BufferedStream.d__51.MoveNext(), System.IO.BufferedStream.d__71.MoveNext(), and System.IO.BufferedStream.ReadFromUnderlyingStreamAsync().