Terraria Decompiled: System.IO.BufferedStream.FlushAsyncInternal
FlushAsyncInternal()
async Task System.IO.BufferedStream.FlushAsyncInternal (CancellationToken cancellationToken) inline private
Definition at line 297 of file BufferedStream.cs.
        {
            SemaphoreSlim sem = this.LazyEnsureAsyncActiveSemaphoreInitialized();
            await sem.WaitAsync().ConfigureAwait(false);
            try
            {
                if (this._writePos > 0)
                {
                    await this.FlushWriteAsync(cancellationToken).ConfigureAwait(false);
                }
                else if (this._readPos < this._readLen)
                {
                    if (this._stream.CanSeek)
                    {
                        this.FlushRead();
                    }
                    if (this._stream.CanWrite)
                    {
                        await this._stream.FlushAsync(cancellationToken).ConfigureAwait(false);
                    }
                }
                else if (this._stream.CanWrite)
                {
                    await this._stream.FlushAsync(cancellationToken).ConfigureAwait(false);
                }
            }
            finally
            {
                sem.Release();
            }
        }
References System.IO.BufferedStream._readLen, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.IO.Stream.CanSeek, System.IO.Stream.CanWrite, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.FlushAsync(), System.IO.BufferedStream.FlushRead(), System.IO.BufferedStream.FlushWriteAsync(), System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.Threading.SemaphoreSlim.Release(), and System.Threading.SemaphoreSlim.WaitAsync().
Referenced by System.IO.BufferedStream.FlushAsync(), and System.IO.BufferedStream.d__38.MoveNext().