Terraria Decompiled: System.IO.BufferedStream.ReadFromUnderlyingStreamAsync
ReadFromUnderlyingStreamAsync()
async ValueTask< int > System.IO.BufferedStream.ReadFromUnderlyingStreamAsync (Memory< byte > buffer, CancellationToken cancellationToken, int bytesAlreadySatisfied, Task semaphoreLockTask) inline private
Definition at line 593 of file BufferedStream.cs.
        {
            await semaphoreLockTask.ConfigureAwait(false);
            int num2;
            try
            {
                int num = this.ReadFromBuffer(buffer.Span);
                if (num == buffer.Length)
                {
                    num2 = bytesAlreadySatisfied + num;
                }
                else
                {
                    if (num > 0)
                    {
                        buffer = buffer.Slice(num);
                        bytesAlreadySatisfied += num;
                    }
                    int num3 = 0;
                    this._readLen = num3;
                    this._readPos = num3;
                    if (this._writePos > 0)
                    {
                        await this.FlushWriteAsync(cancellationToken).ConfigureAwait(false);
                    }
                    if (buffer.Length >= this._bufferSize)
                    {
                        int num4 = bytesAlreadySatisfied;
                        num2 = num4 + await this._stream.ReadAsync(buffer, cancellationToken).ConfigureAwait(false);
                    }
                    else
                    {
                        this.EnsureBufferAllocated();
                        this._readLen = await this._stream.ReadAsync(new Memory<byte>(this._buffer, 0, this._bufferSize), cancellationToken).ConfigureAwait(false);
                        num2 = bytesAlreadySatisfied + this.ReadFromBuffer(buffer.Span);
                    }
                }
            }
            finally
            {
                this.LazyEnsureAsyncActiveSemaphoreInitialized().Release();
            }
            return num2;
        }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.BufferedStream.EnsureBufferAllocated(), System.IO.BufferedStream.FlushWriteAsync(), System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.Memory< T >.Length, System.IO.Stream.ReadAsync(), System.IO.BufferedStream.ReadFromBuffer(), System.Threading.SemaphoreSlim.Release(), System.Memory< T >.Slice(), and System.Memory< T >.Span.
Referenced by System.IO.BufferedStream.d__51.MoveNext(), System.IO.BufferedStream.ReadAsync(), and System.IO.BufferedStream.ReadAsync().