Terraria Decompiled: System.MulticastDelegate.RemoveImpl
RemoveImpl()
override Delegate System.MulticastDelegate.RemoveImpl (Delegate value) inline sealed protected virtual
Reimplemented from System.Delegate.
Definition at line 190 of file MulticastDelegate.cs.
        {
            if (value == null)
            {
                return this;
            }
            MulticastDelegate multicastDelegate = (MulticastDelegate)value;
            if (this.delegates == null && multicastDelegate.delegates == null)
            {
                if (!this.Equals(multicastDelegate))
                {
                    return this;
                }
                return null;
            }
            else
            {
                if (this.delegates == null)
                {
                    foreach (Delegate @delegate in multicastDelegate.delegates)
                    {
                        if (this.Equals(@delegate))
{
                            return null;
                        }
                    }
                    return this;
                }
                if (multicastDelegate.delegates == null)
                {
                    int num = Array.LastIndexOf<Delegate>(this.delegates, multicastDelegate);
                    if (num == -1)
                    {
                        return this;
                    }
                    if (this.delegates.Length <= 1)
                    {
                        throw new InvalidOperationException();
                    }
                    if (this.delegates.Length == 2)
                    {
                        return this.delegates[(num == 0) ? 1 : 0];
                    }
                    MulticastDelegate multicastDelegate2 = Delegate.AllocDelegateLike_internal(this);
                    multicastDelegate2.delegates = new Delegate[this.delegates.Length - 1];
                    Array.Copy(this.delegates, multicastDelegate2.delegates, num);
                    Array.Copy(this.delegates, num + 1, multicastDelegate2.delegates, num, this.delegates.Length - num - 1);
                    return multicastDelegate2;
                }
                else
                {
                    if (this.delegates.Equals(multicastDelegate.delegates))
                    {
                        return null;
                    }
                    int num2 = this.LastIndexOf(this.delegates, multicastDelegate.delegates);
                    if (num2 == -1)
                    {
                        return this;
                    }
                    MulticastDelegate multicastDelegate3 = Delegate.AllocDelegateLike_internal(this);
                    multicastDelegate3.delegates = new Delegate[this.delegates.Length - multicastDelegate.delegates.Length];
                    Array.Copy(this.delegates, multicastDelegate3.delegates, num2);
                    Array.Copy(this.delegates, num2 + multicastDelegate.delegates.Length, multicastDelegate3.delegates, num2, this.delegates.Length - num2 - multicastDelegate.delegates.Length);
                    return multicastDelegate3;
                }
            }
        }
References System.Delegate.AllocDelegateLike_internal(), System.Array.Copy(), System.MulticastDelegate.delegates, System.Delegate.Equals(), System.MulticastDelegate.Equals(), System.Array.LastIndexOf(), System.MulticastDelegate.LastIndexOf(), System.MulticastDelegate.MulticastDelegate(), and System.value.