Terraria Decompiled: System.MulticastDelegate.CombineImpl
CombineImpl()
override Delegate System.MulticastDelegate.CombineImpl (Delegate follow) inline sealed protected virtual
Reimplemented from System.Delegate.
Definition at line 121 of file MulticastDelegate.cs.
        {
            if (follow == null)
            {
                return this;
            }
            MulticastDelegate multicastDelegate = (MulticastDelegate)follow;
            MulticastDelegate multicastDelegate2 = Delegate.AllocDelegateLike_internal(this);
            if (this.delegates == null && multicastDelegate.delegates == null)
            {
                multicastDelegate2.delegates = new Delegate[] { this, multicastDelegate };
            }
            else if (this.delegates == null)
            {
                multicastDelegate2.delegates = new Delegate[1 + multicastDelegate.delegates.Length];
                multicastDelegate2.delegates[0] = this;
                Array.Copy(multicastDelegate.delegates, 0, multicastDelegate2.delegates, 1, multicastDelegate.delegates.Length);
            }
            else if (multicastDelegate.delegates == null)
            {
                multicastDelegate2.delegates = new Delegate[this.delegates.Length + 1];
                Array.Copy(this.delegates, 0, multicastDelegate2.delegates, 0, this.delegates.Length);
                multicastDelegate2.delegates[multicastDelegate2.delegates.Length - 1] = multicastDelegate;
            }
            else
            {
                multicastDelegate2.delegates = new Delegate[this.delegates.Length + multicastDelegate.delegates.Length];
                Array.Copy(this.delegates, 0, multicastDelegate2.delegates, 0, this.delegates.Length);
                Array.Copy(multicastDelegate.delegates, 0, multicastDelegate2.delegates, this.delegates.Length, multicastDelegate.delegates.Length);
            }
            return multicastDelegate2;
        }
References System.Delegate.AllocDelegateLike_internal(), System.Array.Copy(), System.MulticastDelegate.delegates, and System.MulticastDelegate.MulticastDelegate().