Terraria Decompiled: Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateDefaultConstructor< T >
CreateDefaultConstructor< T >()
override Func< T > Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateDefaultConstructor< T > (Type type) inline
Definition at line 46 of file LateBoundReflectionDelegateFactory.cs.
        {
            ValidationUtils.ArgumentNotNull(type, "type");
            if (type.IsValueType())
            {
                return () => (T)((object)Activator.CreateInstance(type));
            }
            ConstructorInfo constructorInfo = ReflectionUtils.GetDefaultConstructor(type, true);
            return () => (T)((object)constructorInfo.Invoke(null));
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Activator.CreateInstance(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDefaultConstructor(), System.Reflection.ConstructorInfo.Invoke(), System.Type.IsValueType, and System.T.