Terraria Decompiled: Steamworks.SteamGameServerClient.GetISteamUserStats
GetISteamUserStats()
static IntPtr Steamworks.SteamGameServerClient.GetISteamUserStats (HSteamUser hSteamUser, HSteamPipe hSteamPipe, string pchVersion) inline static
Definition at line 135 of file SteamGameServerClient.cs.
        {
            InteropHelp.TestIfAvailableGameServer();
            IntPtr intPtr;
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle(pchVersion))
            {
                intPtr = NativeMethods.ISteamClient_GetISteamUserStats(CSteamGameServerAPIContext.GetSteamClient(), hSteamUser, hSteamPipe, utf8StringHandle);
            }
            return intPtr;
        }
References Steamworks.CSteamGameServerAPIContext.GetSteamClient(), Steamworks.NativeMethods.ISteamClient_GetISteamUserStats(), and Steamworks.InteropHelp.TestIfAvailableGameServer().