Terraria Decompiled: System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent
ParseComponent()
static unsafe Utf8Parser.ComponentParseResult System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent (ReadOnlySpan< byte > source, bool neverParseAsFraction, ref int srcIndex, out uint value) inline static private
Definition at line 4224 of file Utf8Parser.cs.
            {
                if (srcIndex == source.Length)
                {
                    value = 0U;
                    return Utf8Parser.ComponentParseResult.NoMoreData;
                }
                byte b = *source[srcIndex];
                if (b == 58 || (b == 46 && neverParseAsFraction))
                {
                    srcIndex++;
                    int num;
                    if (!Utf8Parser.TryParseUInt32D(source.Slice(srcIndex), out value, out num))
                    {
                        value = 0U;
                        return Utf8Parser.ComponentParseResult.ParseFailure;
                    }
                    srcIndex += num;
                    if (b != 58)
                    {
                        return Utf8Parser.ComponentParseResult.Period;
                    }
                    return Utf8Parser.ComponentParseResult.Colon;
                }
                else
                {
                    if (b != 46)
                    {
                        value = 0U;
                        return Utf8Parser.ComponentParseResult.NoMoreData;
                    }
                    srcIndex++;
                    int num2;
                    if (!Utf8Parser.TryParseTimeSpanFraction(source.Slice(srcIndex), out value, out num2))
                    {
                        value = 0U;
                        return Utf8Parser.ComponentParseResult.ParseFailure;
                    }
                    srcIndex += num2;
                    return Utf8Parser.ComponentParseResult.Period;
                }
            }
References System.source, System.Buffers.Text.Utf8Parser.TryParseTimeSpanFraction(), System.Buffers.Text.Utf8Parser.TryParseUInt32D(), System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan().