Terraria Decompiled: System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan
TrySplitTimeSpan()
unsafe bool System.Buffers.Text.Utf8Parser.TimeSpanSplitter.TrySplitTimeSpan (ReadOnlySpan< byte > source, bool periodUsedToSeparateDay, out int bytesConsumed) inline
Definition at line 4131 of file Utf8Parser.cs.
            {
                int num = 0;
                byte b = 0;
                while (num != source.Length)
                {
                    b = *source[num];
                    if (b != 32 && b != 9)
                    {
                        break;
                    }
                    num++;
                }
                if (num == source.Length)
                {
                    bytesConsumed = 0;
                    return false;
                }
                if (b == 45)
                {
                    this.IsNegative = true;
                    num++;
                    if (num == source.Length)
                    {
                        bytesConsumed = 0;
                        return false;
                    }
                }
                int num2;
                if (!Utf8Parser.TryParseUInt32D(source.Slice(num), out this.V1, out num2))
                {
                    bytesConsumed = 0;
                    return false;
                }
                num += num2;
                Utf8Parser.ComponentParseResult componentParseResult = Utf8Parser.TimeSpanSplitter.ParseComponent(source, periodUsedToSeparateDay, ref num, out this.V2);
                if (componentParseResult == Utf8Parser.ComponentParseResult.ParseFailure)
                {
                    bytesConsumed = 0;
                    return false;
                }
                if (componentParseResult == Utf8Parser.ComponentParseResult.NoMoreData)
                {
                    bytesConsumed = num;
                    return true;
                }
                this.Separators |= (uint)((uint)componentParseResult << 24);
                componentParseResult = Utf8Parser.TimeSpanSplitter.ParseComponent(source, false, ref num, out this.V3);
                if (componentParseResult == Utf8Parser.ComponentParseResult.ParseFailure)
                {
                    bytesConsumed = 0;
                    return false;
                }
                if (componentParseResult == Utf8Parser.ComponentParseResult.NoMoreData)
                {
                    bytesConsumed = num;
                    return true;
                }
                this.Separators |= (uint)((uint)componentParseResult << 16);
                componentParseResult = Utf8Parser.TimeSpanSplitter.ParseComponent(source, false, ref num, out this.V4);
                if (componentParseResult == Utf8Parser.ComponentParseResult.ParseFailure)
                {
                    bytesConsumed = 0;
                    return false;
                }
                if (componentParseResult == Utf8Parser.ComponentParseResult.NoMoreData)
                {
                    bytesConsumed = num;
                    return true;
                }
                this.Separators |= (uint)((uint)componentParseResult << 8);
                componentParseResult = Utf8Parser.TimeSpanSplitter.ParseComponent(source, false, ref num, out this.V5);
                if (componentParseResult == Utf8Parser.ComponentParseResult.ParseFailure)
                {
                    bytesConsumed = 0;
                    return false;
                }
                if (componentParseResult == Utf8Parser.ComponentParseResult.NoMoreData)
                {
                    bytesConsumed = num;
                    return true;
                }
                this.Separators |= (uint)componentParseResult;
                if (num != source.Length && (*source[num] == 46 || *source[num] == 58))
                {
                    bytesConsumed = 0;
                    return false;
                }
                bytesConsumed = num;
                return true;
            }
References System.Buffers.Text.Utf8Parser.TimeSpanSplitter.ParseComponent(), System.source, System.Buffers.Text.Utf8Parser.TryParseUInt32D(), System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V2, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V3, System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V4, and System.Buffers.Text.Utf8Parser.TimeSpanSplitter.V5.
Referenced by System.Buffers.Text.Utf8Parser.TryParseTimeSpanC(), and System.Buffers.Text.Utf8Parser.TryParseTimeSpanLittleG().