Terraria Decompiled: Terraria.GameContent.LightningGenerator.TileCollision
TileCollision()
bool Terraria.GameContent.LightningGenerator.TileCollision (Vector2 pos) inline private
Definition at line 123 of file LightningGenerator.cs.
        {
            Point point = pos.ToTileCoordinates();
            if (!WorldGen.InWorld(point, 0) || Main.tile[point.X, point.Y] == null)
            {
                return false;
            }
            if (WorldGen.SolidOrSlopedTile(point.X, point.Y))
            {
                return true;
            }
            int liquid = (int)Main.tile[point.X, point.Y].liquid;
            return liquid > 0 && (int)pos.Y % 16 > 16 * (255 - liquid) / 255;
        }
References int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.LightningGenerator.GenerateBolt().