Terraria Decompiled: Terraria.GameContent.LightningGenerator.GenerateBolt
GenerateBolt()
LightningGenerator.Bolt Terraria.GameContent.LightningGenerator.GenerateBolt (List< LightningGenerator::Bolt > bolts, uint seed, int depth, bool calcPositions, Vector2 startPos, Vector2 targetPos, float rotationStrength, float stepSize, FloatRange progressRange) inline private
Definition at line 28 of file LightningGenerator.cs.
        {
            LCG32Random lcg32Random = new LCG32Random(seed);
            float num = 0f;
            float[] array = new float[this.Layers];
            Point point = targetPos.ToTileCoordinates();
            Vector2 vector = startPos;
            Vector2 vector2 = targetPos - startPos;
            float num2 = vector2.Length();
            vector2 /= num2;
            Vector2 vector3 = new Vector2(vector2.Y, -vector2.X);
            int num3 = (int)(num2 * 2f / stepSize);
            int num4 = 0;
            Vector2[] array2 = (calcPositions ? new Vector2[num3] : null);
            LightningGenerator.Bolt bolt = new LightningGenerator.Bolt
            {
                positions = array2,
                forkDepth = depth,
                progressRange = progressRange
            };
            int i;
            for (i = 0; i < num3; i++)
            {
                if (calcPositions)
                {
                    array2[i] = vector;
                }
                Vector2 vector4 = targetPos - vector;
                float num5 = Vector2.Dot(vector4, vector2);
                if (num5 < stepSize)
                {
                    break;
                }
                float num6 = MathHelper.Clamp(1f - num5 / num2, 0f, 1f);
                if (this.SolidTileCollision && vector.ToTileCoordinates() != point && this.TileCollision(vector))
                {
                    bolt.progressRange = new FloatRange(progressRange.Minimum, progressRange.Lerp(num6));
                    bolt.collidedWithTile = true;
                    break;
                }
                vector4 /= vector4.Length();
                float num7 = -Vector2.Dot(vector4, vector3);
                float num8 = Math.Max(0.01f, Math.Min(num6, 1f - num6) * this.PerpendicularDeviationFactor * 2f);
                float num9 = MathHelper.Clamp(num7 / num8, -1f, 1f);
                int num10;
                if (this.PickLayerToReroll(lcg32Random.NextDouble(), 0.5f, out num10))
                {
                    float num11 = rotationStrength;
                    for (int j = this.Layers - 1; j > num10; j--)
                    {
                        num11 /= this.LayerStrengthFactor;
                    }
                    float num12 = (float)lcg32Random.NextDouble() * 2f - 1f;
                    num12 += (num9 - num12 * Math.Abs(num9)) / 2f;
                    float num13 = num12 * num11;
                    float num14 = array[num10];
                    float num15 = num13 - num14;
                    num += num15;
                    array[num10] = num13;
                    if (num10 == this.Layers - 1)
                    {
                        float num16 = lcg32Random.NextFloat();
                        float num17 = Utils.Remap((float)num4, 0f, (float)this.MaxForksPerBolt, 1f, 0f, true);
                        float num18 = num - num15 * (1f + this.ForkReflectAngleMultiplier);
                        if (bolts != null && Math.Abs(num15) >= rotationStrength * this.ForkGenerationThresholdAngleFraction && this.ForkProgressRange.Contains(num6) && depth < this.MaxForkDepth && num16 < num17 && Math.Abs(num18) < 1.3962635f)
{
                            num4++;
                            float num19 = (1f - num6) * this.ForkLengthMultiplier;
                            Vector2 vector5 = vector + vector4.RotatedBy((double)num18, default(Vector2)) * num2 * num19;
                            this.GenerateBolt(bolts, lcg32Random.state + 1U, depth + 1, calcPositions, vector, vector5, rotationStrength * this.ForkRotationStrengthMultiplier, stepSize * this.ForkStepSizeMultiplier, new FloatRange(progressRange.Lerp(num6), progressRange.Lerp(num6 + num19)));
                        }
                    }
                }
                float num20 = Utils.Remap(num6, this.ReduceRandomnessAfter, 1f, 0f, 1f, true);
                num20 += Utils.Remap(Math.Abs(num9), 0.5f, 1f, 0f, 1f, true);
                if (this.PickHighLayerToReroll(lcg32Random.NextDouble(), num20, out num10))
                {
                    num -= array[num10];
                    array[num10] = 0f;
                }
                vector += vector4.RotatedBy((double)num, default(Vector2)) * stepSize;
            }
            if (calcPositions && i < num3)
            {
                Array.Resize<Vector2>(ref array2, i + 1);
                bolt.positions = array2;
            }
            if (bolts != null && i > 2)
            {
                bolts.Add(bolt);
            }
            return bolt;
        }
References System.Math.Abs(), System.Collections.Generic.List< T >.Add(), System.array, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Utilities.Terraria.Utilities.FloatRange.Contains(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.GameContent.LightningGenerator.ForkLengthMultiplier, Terraria.GameContent.LightningGenerator.ForkProgressRange, Terraria.GameContent.LightningGenerator.ForkReflectAngleMultiplier, Terraria.GameContent.LightningGenerator.GenerateBolt(), int, Terraria.GameContent.LightningGenerator.Layers, Terraria.GameContent.LightningGenerator.LayerStrengthFactor, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Utilities.Terraria.Utilities.FloatRange.Lerp(), System.Math.Max(), Terraria.GameContent.LightningGenerator.MaxForksPerBolt, System.Math.Min(), Terraria.Utilities.Terraria.Utilities.FloatRange.Minimum, Terraria.Utilities.LCG32Random.NextDouble(), Terraria.Utilities.LCG32Random.NextFloat(), Terraria.GameContent.LightningGenerator.PickHighLayerToReroll(), Terraria.GameContent.LightningGenerator.PickLayerToReroll(), Terraria.GameContent.LightningGenerator.ReduceRandomnessAfter, Terraria.Utils.Remap(), Terraria.GameContent.LightningGenerator.SolidTileCollision, Terraria.Utilities.LCG32Random.state, Terraria.GameContent.LightningGenerator.TileCollision(), System.U, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.LightningGenerator.Generate(), and Terraria.GameContent.LightningGenerator.GenerateBolt().