Terraria Decompiled: Microsoft.Xna.Framework.Vector4.Lerp
Lerp() [2/2]
static Vector4 Microsoft.Xna.Framework.Vector4.Lerp (Vector4 value1, Vector4 value2, float amount) inline static
Definition at line 350 of file Vector4.cs.
        {
            return new Vector4(MathHelper.Lerp(value1.X, value2.X, amount), MathHelper.Lerp(value1.Y, value2.Y, amount), MathHelper.Lerp(value1.Z, value2.Z, amount), MathHelper.Lerp(value1.W, value2.W, amount));
        }
References Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector4.Vector4(), Microsoft.Xna.Framework.Vector4.W, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector4.Y, and Microsoft.Xna.Framework.Vector4.Z.
Referenced by Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.GameContent.RGB.CorruptSurfaceShader.CorruptSurfaceShader(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem_ApplyStealthToColor(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawSimpleSurfaceBackground(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerBaseColor(), Terraria.GameContent.Skies.MoonLordSky.OnTileColor(), Terraria.GameContent.Skies.NebulaSky.OnTileColor(), Terraria.GameContent.Skies.SolarSky.OnTileColor(), Terraria.GameContent.Skies.StardustSky.OnTileColor(), Terraria.GameContent.Skies.VortexSky.OnTileColor(), Terraria.GameContent.RGB.SkyShader.ProcessAnyDetail(), Terraria.GameContent.RGB.BlizzardShader.ProcessHighDetail(), Terraria.GameContent.RGB.BrainShader.ProcessHighDetail(), Terraria.GameContent.RGB.CavernShader.ProcessHighDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.CultistShader.ProcessHighDetail(), Terraria.GameContent.RGB.DD2Shader.ProcessHighDetail(), Terraria.GameContent.RGB.DesertShader.ProcessHighDetail(), Terraria.GameContent.RGB.DrippingShader.ProcessHighDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessHighDetail(), Terraria.GameContent.RGB.DungeonShader.ProcessHighDetail(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail(), Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessHighDetail(), Terraria.GameContent.RGB.FrostLegionShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessHighDetail(), Terraria.GameContent.RGB.GolemShader.ProcessHighDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessHighDetail(), Terraria.GameContent.RGB.IceShader.ProcessHighDetail(), Terraria.GameContent.RGB.JungleShader.ProcessHighDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessHighDetail(), Terraria.GameContent.RGB.MoonShader.ProcessHighDetail(), Terraria.GameContent.RGB.PillarShader.ProcessHighDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail(), Terraria.GameContent.RGB.PlanteraShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenBeeShader.ProcessHighDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessHighDetail(), Terraria.GameContent.RGB.RainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SandstormShader.ProcessHighDetail(), Terraria.GameContent.RGB.SkullShader.ProcessHighDetail(), Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessHighDetail(), Terraria.GameContent.RGB.TempleShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundHallowShader.ProcessHighDetail(), Terraria.GameContent.RGB.UndergroundMushroomShader.ProcessHighDetail(), Terraria.GameContent.RGB.UnderworldShader.ProcessHighDetail(), Terraria.GameContent.RGB.VineShader.ProcessHighDetail(), Terraria.GameContent.RGB.WallOfFleshShader.ProcessHighDetail(), Terraria.GameContent.RGB.WormShader.ProcessHighDetail(), Terraria.GameContent.RGB.BrainShader.ProcessLowDetail(), Terraria.GameContent.RGB.CavernShader.ProcessLowDetail(), Terraria.GameContent.RGB.CorruptSurfaceShader.ProcessLowDetail(), Terraria.GameContent.RGB.DeathShader.ProcessLowDetail(), Terraria.GameContent.RGB.DrippingShader.ProcessLowDetail(), Terraria.GameContent.RGB.DukeFishronShader.ProcessLowDetail(), Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessLowDetail(), Terraria.GameContent.RGB.GoblinArmyShader.ProcessLowDetail(), Terraria.GameContent.RGB.GolemShader.ProcessLowDetail(), Terraria.GameContent.RGB.HallowSurfaceShader.ProcessLowDetail(), Terraria.GameContent.RGB.JungleShader.ProcessLowDetail(), Terraria.GameContent.RGB.KingSlimeShader.ProcessLowDetail(), Terraria.GameContent.RGB.LavaIndicatorShader.ProcessLowDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessLowDetail(), Terraria.GameContent.RGB.MeteoriteShader.ProcessLowDetail(), Terraria.GameContent.RGB.MoonShader.ProcessLowDetail(), Terraria.GameContent.RGB.PillarShader.ProcessLowDetail(), Terraria.GameContent.RGB.PirateInvasionShader.ProcessLowDetail(), Terraria.GameContent.RGB.PlanteraShader.ProcessLowDetail(), Terraria.GameContent.RGB.QueenBeeShader.ProcessLowDetail(), Terraria.GameContent.RGB.QueenSlimeShader.ProcessLowDetail(), Terraria.GameContent.RGB.SkullShader.ProcessLowDetail(), Terraria.GameContent.RGB.SurfaceBiomeShader.ProcessLowDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail(), Terraria.GameContent.RGB.UndergroundCorruptionShader.ProcessLowDetail(), Terraria.GameContent.RGB.UndergroundHallowShader.ProcessLowDetail(), Terraria.GameContent.RGB.UndergroundMushroomShader.ProcessLowDetail(), Terraria.GameContent.RGB.UnderworldShader.ProcessLowDetail(), Terraria.GameContent.RGB.WormShader.ProcessLowDetail(), Terraria.GameContent.RGB.EmpressShader.RedsVersion(), and ReLogic.Peripherals.RGB.RgbDevice.Render().