Terraria Decompiled: Microsoft.Xna.Framework.Vector4.Length
Length()
float Microsoft.Xna.Framework.Vector4.Length () inline
Definition at line 148 of file Vector4.cs.
        {
            return (float)Math.Sqrt((double)(this.X * this.X + this.Y * this.Y + this.Z * this.Z + this.W * this.W));
        }
References System.Math.Sqrt(), Microsoft.Xna.Framework.Vector4.W, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector4.Y, and Microsoft.Xna.Framework.Vector4.Z.
Referenced by ReLogic.Peripherals.RGB.Fragment.Clear(), ReLogic.Peripherals.RGB.Fragment.GetAverage(), Terraria.GameContent.RGB.EmpressShader.ProcessHighDetail(), Terraria.GameContent.RGB.GemCaveShader.ProcessHighDetail(), Terraria.GameContent.RGB.SlimeRainShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessLowDetail(), Terraria.GameContent.RGB.EmpressShader.RedsVersion(), Microsoft.Xna.Framework.Vector4.Transform(), Microsoft.Xna.Framework.Vector4.Transform(), Microsoft.Xna.Framework.Vector4.Transform(), and Microsoft.Xna.Framework.Vector4.Transform().