Terraria Decompiled: Terraria.Liquid.Update
Update()
void Terraria.Liquid.Update () inline
Definition at line 454 of file Liquid.cs.
        {
            Main.tileSolid[379] = true;
            Tile tile = Main.tile[this.x - 1, this.y];
            Tile tile2 = Main.tile[this.x + 1, this.y];
            Tile tile3 = Main.tile[this.x, this.y - 1];
            Tile tile4 = Main.tile[this.x, this.y + 1];
            Tile tile5 = Main.tile[this.x, this.y];
            if (tile5.nactive() && Main.tileSolid[(int)tile5.type] && !Main.tileSolidTop[(int)tile5.type])
            {
                ushort type = tile5.type;
                this.kill = 999;
                return;
            }
            byte liquid = tile5.liquid;
            if (this.y > Main.UnderworldLayer && tile5.liquidType() == 0 && tile5.liquid > 0)
            {
                byte b = 2;
                if (tile5.liquid < b)
                {
                    b = tile5.liquid;
                }
                Tile tile6 = tile5;
                tile6.liquid -= b;
            }
            if (tile5.liquid == 0)
            {
                this.kill = 999;
                return;
            }
            if (tile5.lava())
            {
                Liquid.LavaCheck(this.x, this.y);
                if (!Liquid.quickFall)
                {
                    if (this.delay < 5)
                    {
                        this.delay++;
                        return;
                    }
                    this.delay = 0;
                }
            }
            else
            {
                if (tile.lava())
                {
                    Liquid.AddWater(this.x - 1, this.y);
                }
                if (tile2.lava())
                {
                    Liquid.AddWater(this.x + 1, this.y);
                }
                if (tile3.lava())
                {
                    Liquid.AddWater(this.x, this.y - 1);
                }
                if (tile4.lava())
                {
                    Liquid.AddWater(this.x, this.y + 1);
                }
                if (tile5.honey())
                {
                    Liquid.HoneyCheck(this.x, this.y);
                    if (!Liquid.quickFall)
                    {
                        if (this.delay < 10)
{
                            this.delay++;
                            return;
                        }
                        this.delay = 0;
                    }
                }
                else
                {
                    if (tile.honey())
                    {
                        Liquid.AddWater(this.x - 1, this.y);
                    }
                    if (tile2.honey())
                    {
                        Liquid.AddWater(this.x + 1, this.y);
                    }
                    if (tile3.honey())
                    {
                        Liquid.AddWater(this.x, this.y - 1);
                    }
                    if (tile4.honey())
                    {
                        Liquid.AddWater(this.x, this.y + 1);
                    }
                    if (tile5.shimmer())
                    {
                        Liquid.ShimmerCheck(this.x, this.y);
                    }
                    else
                    {
                        if (tile.shimmer())
{
                            Liquid.AddWater(this.x - 1, this.y);
                        }
                        if (tile2.shimmer())
{
                            Liquid.AddWater(this.x + 1, this.y);
                        }
                        if (tile3.shimmer())
{
                            Liquid.AddWater(this.x, this.y - 1);
                        }
                        if (tile4.shimmer())
{
                            Liquid.AddWater(this.x, this.y + 1);
                        }
                    }
                }
            }
            if ((!tile4.nactive() || !Main.tileSolid[(int)tile4.type] || Main.tileSolidTop[(int)tile4.type]) && (tile4.liquid <= 0 || tile4.liquidType() == tile5.liquidType()) && tile4.liquid < 255)
            {
                bool flag = false;
                float num = (float)(byte.MaxValue - tile4.liquid);
                if (num > (float)tile5.liquid)
                {
                    num = (float)tile5.liquid;
                }
                if (num == 1f && tile5.liquid == 255)
                {
                    flag = true;
                }
                if (!flag)
                {
                    Tile tile7 = tile5;
                    tile7.liquid -= (byte)num;
                }
                Tile tile8 = tile4;
                tile8.liquid += (byte)num;
                tile4.liquidType((int)tile5.liquidType());
                Liquid.AddWater(this.x, this.y + 1);
                tile4.skipLiquid(true);
                tile5.skipLiquid(true);
                if (Liquid.quickSettle && tile5.liquid > 250)
                {
                    tile5.liquid = byte.MaxValue;
                }
                else if (!flag)
                {
                    Liquid.AddWater(this.x - 1, this.y);
                    Liquid.AddWater(this.x + 1, this.y);
                }
            }
            if (tile5.liquid > 0)
            {
                bool flag2 = true;
                bool flag3 = true;
                bool flag4 = true;
                bool flag5 = true;
                if (tile.nactive() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
                {
                    flag2 = false;
                }
                else if (tile.liquid > 0 && tile.liquidType() != tile5.liquidType())
                {
                    flag2 = false;
                }
                else if (Main.tile[this.x - 2, this.y].nactive() && Main.tileSolid[(int)Main.tile[this.x - 2, this.y].type] && !Main.tileSolidTop[(int)Main.tile[this.x - 2, this.y].type])
                {
                    flag4 = false;
                }
                else if (Main.tile[this.x - 2, this.y].liquid == 0)
                {
                    flag4 = false;
                }
                else if (Main.tile[this.x - 2, this.y].liquid > 0 && Main.tile[this.x - 2, this.y].liquidType() != tile5.liquidType())
                {
                    flag4 = false;
                }
                if (tile2.nactive() && Main.tileSolid[(int)tile2.type] && !Main.tileSolidTop[(int)tile2.type])
                {
                    flag3 = false;
                }
                else if (tile2.liquid > 0 && tile2.liquidType() != tile5.liquidType())
                {
                    flag3 = false;
                }
                else if (Main.tile[this.x + 2, this.y].nactive() && Main.tileSolid[(int)Main.tile[this.x + 2, this.y].type] && !Main.tileSolidTop[(int)Main.tile[this.x + 2, this.y].type])
                {
                    flag5 = false;
                }
                else if (Main.tile[this.x + 2, this.y].liquid == 0)
                {
                    flag5 = false;
                }
                else if (Main.tile[this.x + 2, this.y].liquid > 0 && Main.tile[this.x + 2, this.y].liquidType() != tile5.liquidType())
                {
                    flag5 = false;
                }
                int num2 = 0;
                if (tile5.liquid < 3)
                {
                    num2 = -1;
                }
                if (tile5.liquid > 250)
                {
                    flag4 = false;
                    flag5 = false;
                }
                if (flag2 && flag3)
                {
                    if (flag4 && flag5)
                    {
                        bool flag6 = true;
                        bool flag7 = true;
                        if (Main.tile[this.x - 3, this.y].nactive() && Main.tileSolid[(int)Main.tile[this.x - 3, this.y].type] && !Main.tileSolidTop[(int)Main.tile[this.x - 3, this.y].type])
{
                            flag6 = false;
                        }
                        else if (Main.tile[this.x - 3, this.y].liquid == 0)
{
                            flag6 = false;
                        }
                        else if (Main.tile[this.x - 3, this.y].liquidType() != tile5.liquidType())
{
                            flag6 = false;
                        }
                        if (Main.tile[this.x + 3, this.y].nactive() && Main.tileSolid[(int)Main.tile[this.x + 3, this.y].type] && !Main.tileSolidTop[(int)Main.tile[this.x + 3, this.y].type])
{
                            flag7 = false;
                        }
                        else if (Main.tile[this.x + 3, this.y].liquid == 0)
{
                            flag7 = false;
                        }
                        else if (Main.tile[this.x + 3, this.y].liquidType() != tile5.liquidType())
{
                            flag7 = false;
                        }
                        if (flag6 && flag7)
{
                            float num = (float)((int)(tile.liquid + tile2.liquid + Main.tile[this.x - 2, this.y].liquid + Main.tile[this.x + 2, this.y].liquid + Main.tile[this.x - 3, this.y].liquid + Main.tile[this.x + 3, this.y].liquid + tile5.liquid) + num2);
                            num = (float)Math.Round((double)(num / 7f));
                            int num3 = 0;
                            tile.liquidType((int)tile5.liquidType());
                            if (tile.liquid != (byte)num)
{
                                tile.liquid = (byte)num;
                                Liquid.AddWater(this.x - 1, this.y);
                            }
                            else
{
                                num3++;
                            }
                            tile2.liquidType((int)tile5.liquidType());
                            if (tile2.liquid != (byte)num)
{
                                tile2.liquid = (byte)num;
                                Liquid.AddWater(this.x + 1, this.y);
                            }
                            else
{
                                num3++;
                            }
                            Main.tile[this.x - 2, this.y].liquidType((int)tile5.liquidType());
                            if (Main.tile[this.x - 2, this.y].liquid != (byte)num)
{
                                Main.tile[this.x - 2, this.y].liquid = (byte)num;
                                Liquid.AddWater(this.x - 2, this.y);
                            }
                            else
{
                                num3++;
                            }
                            Main.tile[this.x + 2, this.y].liquidType((int)tile5.liquidType());
                            if (Main.tile[this.x + 2, this.y].liquid != (byte)num)
{
                                Main.tile[this.x + 2, this.y].liquid = (byte)num;
                                Liquid.AddWater(this.x + 2, this.y);
                            }
                            else
{
                                num3++;
                            }
                            Main.tile[this.x - 3, this.y].liquidType((int)tile5.liquidType());
                            if (Main.tile[this.x - 3, this.y].liquid != (byte)num)
{
                                Main.tile[this.x - 3, this.y].liquid = (byte)num;
                                Liquid.AddWater(this.x - 3, this.y);
                            }
                            else
{
                                num3++;
                            }
                            Main.tile[this.x + 3, this.y].liquidType((int)tile5.liquidType());
                            if (Main.tile[this.x + 3, this.y].liquid != (byte)num)
{
                                Main.tile[this.x + 3, this.y].liquid = (byte)num;
                                Liquid.AddWater(this.x + 3, this.y);
                            }
                            else
{
                                num3++;
                            }
                            if (tile.liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x - 1, this.y);
                            }
                            if (tile2.liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x + 1, this.y);
                            }
                            if (Main.tile[this.x - 2, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x - 2, this.y);
                            }
                            if (Main.tile[this.x + 2, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x + 2, this.y);
                            }
                            if (Main.tile[this.x - 3, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x - 3, this.y);
                            }
                            if (Main.tile[this.x + 3, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x + 3, this.y);
                            }
                            if (num3 != 6 || tile3.liquid <= 0)
{
                                tile5.liquid = (byte)num;
                            }
                        }
                        else
{
                            int num4 = 0;
                            float num = (float)((int)(tile.liquid + tile2.liquid + Main.tile[this.x - 2, this.y].liquid + Main.tile[this.x + 2, this.y].liquid + tile5.liquid) + num2);
                            num = (float)Math.Round((double)(num / 5f));
                            tile.liquidType((int)tile5.liquidType());
                            if (tile.liquid != (byte)num)
{
                                tile.liquid = (byte)num;
                                Liquid.AddWater(this.x - 1, this.y);
                            }
                            else
{
                                num4++;
                            }
                            tile2.liquidType((int)tile5.liquidType());
                            if (tile2.liquid != (byte)num)
{
                                tile2.liquid = (byte)num;
                                Liquid.AddWater(this.x + 1, this.y);
                            }
                            else
{
                                num4++;
                            }
                            Main.tile[this.x - 2, this.y].liquidType((int)tile5.liquidType());
                            if (Main.tile[this.x - 2, this.y].liquid != (byte)num)
{
                                Main.tile[this.x - 2, this.y].liquid = (byte)num;
                                Liquid.AddWater(this.x - 2, this.y);
                            }
                            else
{
                                num4++;
                            }
                            Main.tile[this.x + 2, this.y].liquidType((int)tile5.liquidType());
                            if (Main.tile[this.x + 2, this.y].liquid != (byte)num)
{
                                Main.tile[this.x + 2, this.y].liquid = (byte)num;
                                Liquid.AddWater(this.x + 2, this.y);
                            }
                            else
{
                                num4++;
                            }
                            if (tile.liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x - 1, this.y);
                            }
                            if (tile2.liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x + 1, this.y);
                            }
                            if (Main.tile[this.x - 2, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x - 2, this.y);
                            }
                            if (Main.tile[this.x + 2, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                                Liquid.AddWater(this.x + 2, this.y);
                            }
                            if (num4 != 4 || tile3.liquid <= 0)
{
                                tile5.liquid = (byte)num;
                            }
                        }
                    }
                    else if (flag4)
                    {
                        float num = (float)((int)(tile.liquid + tile2.liquid + Main.tile[this.x - 2, this.y].liquid + tile5.liquid) + num2);
                        num = (float)Math.Round((double)(num / 4f));
                        tile.liquidType((int)tile5.liquidType());
                        if (tile.liquid != (byte)num || tile5.liquid != (byte)num)
{
                            tile.liquid = (byte)num;
                            Liquid.AddWater(this.x - 1, this.y);
                        }
                        tile2.liquidType((int)tile5.liquidType());
                        if (tile2.liquid != (byte)num || tile5.liquid != (byte)num)
{
                            tile2.liquid = (byte)num;
                            Liquid.AddWater(this.x + 1, this.y);
                        }
                        Main.tile[this.x - 2, this.y].liquidType((int)tile5.liquidType());
                        if (Main.tile[this.x - 2, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                            Main.tile[this.x - 2, this.y].liquid = (byte)num;
                            Liquid.AddWater(this.x - 2, this.y);
                        }
                        tile5.liquid = (byte)num;
                    }
                    else if (flag5)
                    {
                        float num = (float)((int)(tile.liquid + tile2.liquid + Main.tile[this.x + 2, this.y].liquid + tile5.liquid) + num2);
                        num = (float)Math.Round((double)(num / 4f));
                        tile.liquidType((int)tile5.liquidType());
                        if (tile.liquid != (byte)num || tile5.liquid != (byte)num)
{
                            tile.liquid = (byte)num;
                            Liquid.AddWater(this.x - 1, this.y);
                        }
                        tile2.liquidType((int)tile5.liquidType());
                        if (tile2.liquid != (byte)num || tile5.liquid != (byte)num)
{
                            tile2.liquid = (byte)num;
                            Liquid.AddWater(this.x + 1, this.y);
                        }
                        Main.tile[this.x + 2, this.y].liquidType((int)tile5.liquidType());
                        if (Main.tile[this.x + 2, this.y].liquid != (byte)num || tile5.liquid != (byte)num)
{
                            Main.tile[this.x + 2, this.y].liquid = (byte)num;
                            Liquid.AddWater(this.x + 2, this.y);
                        }
                        tile5.liquid = (byte)num;
                    }
                    else
                    {
                        float num = (float)((int)(tile.liquid + tile2.liquid + tile5.liquid) + num2);
                        num = (float)Math.Round((double)(num / 3f));
                        if (num == 254f && WorldGen.genRand.Next(30) == 0)
{
                            num = 255f;
                        }
                        tile.liquidType((int)tile5.liquidType());
                        if (tile.liquid != (byte)num)
{
                            tile.liquid = (byte)num;
                            Liquid.AddWater(this.x - 1, this.y);
                        }
                        tile2.liquidType((int)tile5.liquidType());
                        if (tile2.liquid != (byte)num)
{
                            tile2.liquid = (byte)num;
                            Liquid.AddWater(this.x + 1, this.y);
                        }
                        tile5.liquid = (byte)num;
                    }
                }
                else if (flag2)
                {
                    float num = (float)((int)(tile.liquid + tile5.liquid) + num2);
                    num = (float)Math.Round((double)(num / 2f));
                    if (tile.liquid != (byte)num)
                    {
                        tile.liquid = (byte)num;
                    }
                    tile.liquidType((int)tile5.liquidType());
                    if (tile5.liquid != (byte)num || tile.liquid != (byte)num)
                    {
                        Liquid.AddWater(this.x - 1, this.y);
                    }
                    tile5.liquid = (byte)num;
                }
                else if (flag3)
                {
                    float num = (float)((int)(tile2.liquid + tile5.liquid) + num2);
                    num = (float)Math.Round((double)(num / 2f));
                    if (tile2.liquid != (byte)num)
                    {
                        tile2.liquid = (byte)num;
                    }
                    tile2.liquidType((int)tile5.liquidType());
                    if (tile5.liquid != (byte)num || tile2.liquid != (byte)num)
                    {
                        Liquid.AddWater(this.x + 1, this.y);
                    }
                    tile5.liquid = (byte)num;
                }
            }
            if (tile5.liquid == liquid)
            {
                this.kill++;
                return;
            }
            if (tile5.liquid != 254 || liquid != 255)
            {
                Liquid.AddWater(this.x, this.y - 1);
                this.kill = 0;
                return;
            }
            if (Liquid.quickSettle)
            {
                tile5.liquid = byte.MaxValue;
                this.kill++;
                return;
            }
            this.kill++;
        }
References Terraria.Liquid.AddWater(), Terraria.Liquid.delay, Terraria.WorldGen.genRand, Terraria.Tile.honey(), Terraria.Liquid.HoneyCheck(), int, Terraria.Liquid.kill, Terraria.Tile.lava(), Terraria.Liquid.LavaCheck(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Tile.nactive(), Terraria.Liquid.quickFall, Terraria.Liquid.quickSettle, System.Math.Round(), Terraria.Tile.shimmer(), Terraria.Liquid.ShimmerCheck(), Terraria.Tile.skipLiquid(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Liquid.x, and Terraria.Liquid.y.
Referenced by Terraria.Liquid.UpdateLiquid().