Terraria Decompiled: Terraria.Liquid.AttemptToMoveShimmer
AttemptToMoveShimmer()
static void Terraria.Liquid.AttemptToMoveShimmer (int X, int Y, bool tileAtXYHasShimmer) inline static private
Definition at line 376 of file Liquid.cs.
        {
            if (Main.tile[X - 1, Y].liquid > 0 && Main.tile[X - 1, Y].shimmer() != tileAtXYHasShimmer)
            {
                if (tileAtXYHasShimmer)
                {
                    Liquid.ShimmerCheck(X, Y);
                    return;
                }
                Liquid.ShimmerCheck(X - 1, Y);
                return;
            }
            else if (Main.tile[X + 1, Y].liquid > 0 && Main.tile[X + 1, Y].shimmer() != tileAtXYHasShimmer)
            {
                if (tileAtXYHasShimmer)
                {
                    Liquid.ShimmerCheck(X, Y);
                    return;
                }
                Liquid.ShimmerCheck(X + 1, Y);
                return;
            }
            else
            {
                if (Main.tile[X, Y - 1].liquid <= 0 || Main.tile[X, Y - 1].shimmer() == tileAtXYHasShimmer)
                {
                    if (Main.tile[X, Y + 1].liquid > 0 && Main.tile[X, Y + 1].shimmer() != tileAtXYHasShimmer)
                    {
                        if (tileAtXYHasShimmer)
{
                            Liquid.ShimmerCheck(X, Y);
                            return;
                        }
                        Liquid.ShimmerCheck(X, Y + 1);
                    }
                    return;
                }
                if (tileAtXYHasShimmer)
                {
                    Liquid.ShimmerCheck(X, Y);
                    return;
                }
                Liquid.ShimmerCheck(X, Y - 1);
                return;
            }
        }
References Terraria.Tile.liquid, Terraria.Tile.shimmer(), Terraria.Liquid.ShimmerCheck(), Terraria.Main.tile, System.X, and System.Y.
Referenced by Terraria.Liquid.SettleWaterAt().