Terraria Decompiled: Terraria.Liquid.QuickWater
QuickWater()
static void Terraria.Liquid.QuickWater (int verbose = 0, int minY = -1, int maxY = -1) inline static
Definition at line 68 of file Liquid.cs.
        {
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                WorldGen.ShimmerRemoveWater();
                if (WorldGen.noTrapsWorldGen)
                {
                    WorldGen.SetBoulderSolidity(false);
                }
            }
            Main.tileSolid[379] = true;
            Liquid.tilesIgnoreWater(true);
            if (minY == -1)
            {
                minY = 3;
            }
            if (maxY == -1)
            {
                maxY = Main.maxTilesY - 3;
            }
            for (int i = maxY; i >= minY; i--)
            {
                Liquid.UpdateProgressDisplay(verbose, minY, maxY, i);
                for (int j = 4; j < Main.maxTilesX - 4; j++)
                {
                    if (Main.tile[j, i].liquid != 0)
                    {
                        Liquid.SettleWaterAt(j, i);
                    }
                }
            }
            Liquid.tilesIgnoreWater(false);
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                WorldGen.ShimmerRemoveWater();
                if (WorldGen.noTrapsWorldGen)
                {
                    WorldGen.SetBoulderSolidity(true);
                }
            }
            if (WorldGen.generatingWorld && !Main.skyblockWorld)
            {
                WorldGen.LiquidInteractionsCleanup();
            }
        }
References Terraria.WorldGen.generatingWorld, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.liquid, Terraria.WorldGen.LiquidInteractionsCleanup(), Terraria.WorldGen.noTrapsWorldGen, Terraria.WorldGen.SetBoulderSolidity(), Terraria.Liquid.SettleWaterAt(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.Main.skyblockWorld, Terraria.Main.tile, Terraria.Liquid.tilesIgnoreWater(), Terraria.Main.tileSolid, and Terraria.Liquid.UpdateProgressDisplay().
Referenced by Terraria.WorldGen.AddPasses(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.GenerateUnderworldStartingMound(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.Liquid.UpdateLiquid().