Terraria Decompiled: Ionic.Zip.ZipOutputStream._FinishCurrentEntry
_FinishCurrentEntry()
void Ionic.Zip.ZipOutputStream._FinishCurrentEntry () inline private
Definition at line 459 of file ZipOutputStream.cs.
        {
            if (this._currentEntry != null)
            {
                if (this._needToWriteEntryHeader)
                {
                    this._InitiateCurrentEntry(true);
                }
                this._currentEntry.FinishOutputStream(this._outputStream, this._outputCounter, this._encryptor, this._deflater, this._entryOutputStream);
                this._currentEntry.PostProcessOutput(this._outputStream);
                if (this._currentEntry.OutputUsedZip64 != null)
                {
                    this._anyEntriesUsedZip64 |= this._currentEntry.OutputUsedZip64.Value;
                }
                this._outputCounter = null;
                this._encryptor = (this._deflater = null);
                this._entryOutputStream = null;
            }
        }
References Ionic.Zip.ZipOutputStream._currentEntry, Ionic.Zip.ZipOutputStream._deflater, Ionic.Zip.ZipOutputStream._encryptor, Ionic.Zip.ZipOutputStream._entryOutputStream, Ionic.Zip.ZipOutputStream._InitiateCurrentEntry(), Ionic.Zip.ZipOutputStream._needToWriteEntryHeader, Ionic.Zip.ZipOutputStream._outputCounter, Ionic.Zip.ZipOutputStream._outputStream, Ionic.Zip.ZipEntry.FinishOutputStream(), Ionic.Zip.ZipEntry.OutputUsedZip64, and Ionic.Zip.ZipEntry.PostProcessOutput().
Referenced by Ionic.Zip.ZipOutputStream.Dispose(), and Ionic.Zip.ZipOutputStream.PutNextEntry().