Terraria Decompiled: Terraria.Liquid.UpdateLiquid
UpdateLiquid()
static void Terraria.Liquid.UpdateLiquid () inline static
Definition at line 992 of file Liquid.cs.
        {
            int num = 8;
            Liquid.tilesIgnoreWater(true);
            if (Main.netMode == 2 && !WorldGen.isGeneratingOrLoadingWorld)
            {
                int num2 = 0;
                for (int i = 0; i < 15; i++)
                {
                    if (Main.player[i].active)
                    {
                        num2++;
                    }
                }
                Liquid.cycles = 10 + num2 / 3;
                Liquid.curMaxLiquid = Liquid.maxLiquid - num2 * 250;
                num = 10 + num2 / 3;
                if (Main.Setting_UseReducedMaxLiquids)
                {
                    Liquid.curMaxLiquid = 5000;
                }
            }
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                if (!Liquid.panicMode)
                {
                    if ((double)LiquidBuffer.numLiquidBuffer >= 45000.0)
                    {
                        Liquid.panicCounter++;
                        if (Liquid.panicCounter > 3600)
{
                            Liquid.StartPanic();
                        }
                    }
                    else
                    {
                        Liquid.panicCounter = 0;
                    }
                }
                if (Liquid.panicMode)
                {
                    int num3 = 0;
                    while (Liquid.panicY >= 3 && num3 < 5)
                    {
                        num3++;
                        Liquid.QuickWater(0, Liquid.panicY, Liquid.panicY);
                        Liquid.panicY--;
                        if (Liquid.panicY < 3)
{
                            Console.WriteLine(Language.GetTextValue("Misc.WaterSettled"));
                            Liquid.panicCounter = 0;
                            Liquid.panicMode = false;
                            WorldGen.WaterCheck();
                            if (Main.netMode == 2)
{
                                for (int j = 0; j < 255; j++)
{
                                    for (int k = 0; k < Main.maxSectionsX; k++)
{
                                        for (int l = 0; l < Main.maxSectionsY; l++)
{
                                            Netplay.Clients[j].TileSections[k, l] = false;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    return;
                }
            }
            bool flag = Liquid.quickSettle;
            if (Main.Setting_UseReducedMaxLiquids)
            {
                flag |= Liquid.numLiquid > 2000;
            }
            if (flag)
            {
                Liquid.quickFall = true;
            }
            else
            {
                Liquid.quickFall = false;
            }
            Liquid.wetCounter++;
            int num4 = Liquid.curMaxLiquid / Liquid.cycles;
            int num5 = num4 * (Liquid.wetCounter - 1);
            int num6 = num4 * Liquid.wetCounter;
            if (Liquid.wetCounter == Liquid.cycles)
            {
                num6 = Liquid.numLiquid;
            }
            if (num6 > Liquid.numLiquid)
            {
                num6 = Liquid.numLiquid;
                int netMode = Main.netMode;
                Liquid.wetCounter = Liquid.cycles;
            }
            if (Liquid.quickFall)
            {
                for (int m = num5; m < num6; m++)
                {
                    Main.liquid[m].delay = 10;
                    Main.liquid[m].Update();
                    Main.tile[Main.liquid[m].x, Main.liquid[m].y].skipLiquid(false);
                }
            }
            else
            {
                for (int n = num5; n < num6; n++)
                {
                    if (!Main.tile[Main.liquid[n].x, Main.liquid[n].y].skipLiquid())
                    {
                        Main.liquid[n].Update();
                    }
                    else
                    {
                        Main.tile[Main.liquid[n].x, Main.liquid[n].y].skipLiquid(false);
                    }
                }
            }
            if (Liquid.wetCounter >= Liquid.cycles)
            {
                Liquid.wetCounter = 0;
                for (int num7 = Liquid.numLiquid - 1; num7 >= 0; num7--)
                {
                    if (Main.liquid[num7].kill >= num)
                    {
                        if (Main.tile[Main.liquid[num7].x, Main.liquid[num7].y].liquid == 254)
{
                            Main.tile[Main.liquid[num7].x, Main.liquid[num7].y].liquid = byte.MaxValue;
                        }
                        Liquid.DelWater(num7);
                    }
                }
                int num8 = Liquid.curMaxLiquid - (Liquid.curMaxLiquid - Liquid.numLiquid);
                if (num8 > LiquidBuffer.numLiquidBuffer)
                {
                    num8 = LiquidBuffer.numLiquidBuffer;
                }
                for (int num9 = 0; num9 < num8; num9++)
                {
                    Main.tile[Main.liquidBuffer[0].x, Main.liquidBuffer[0].y].checkingLiquid(false);
                    Liquid.AddWater(Main.liquidBuffer[0].x, Main.liquidBuffer[0].y);
                    LiquidBuffer.DelBuffer(0);
                }
                if (Liquid.numLiquid > 0 && Liquid.numLiquid > Liquid.stuckAmount - 50 && Liquid.numLiquid < Liquid.stuckAmount + 50)
                {
                    Liquid.stuckCount++;
                    if (Liquid.stuckCount >= 10000)
                    {
                        Liquid.stuck = true;
                        for (int num10 = Liquid.numLiquid - 1; num10 >= 0; num10--)
{
                            Liquid.DelWater(num10);
                        }
                        Liquid.stuck = false;
                        Liquid.stuckCount = 0;
                    }
                }
                else
                {
                    Liquid.stuckCount = 0;
                    Liquid.stuckAmount = Liquid.numLiquid;
                }
            }
            if (!WorldGen.isGeneratingOrLoadingWorld && Main.netMode == 2 && Liquid._netChangeSet.Count > 0)
            {
                Utils.Swap<HashSet<int>>(ref Liquid._netChangeSet, ref Liquid._swapNetChangeSet);
                NetLiquidModule.CreateAndBroadcastByChunk(Liquid._swapNetChangeSet);
                Liquid._swapNetChangeSet.Clear();
            }
            Liquid.tilesIgnoreWater(false);
        }
References Terraria.Liquid._netChangeSet, Terraria.Liquid._swapNetChangeSet, Terraria.Player.active, Terraria.Liquid.AddWater(), Terraria.Tile.checkingLiquid(), Terraria.Netplay.Clients, Terraria.GameContent.NetModules.NetLiquidModule.CreateAndBroadcastByChunk(), Terraria.Liquid.cycles, Terraria.Liquid.delay, Terraria.LiquidBuffer.DelBuffer(), Terraria.Liquid.DelWater(), Terraria.Localization.Language.GetTextValue(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Liquid.kill, Terraria.Main.liquid, Terraria.Tile.liquid, Terraria.Main.liquidBuffer, Terraria.Main.maxSectionsX, Terraria.Main.maxSectionsY, Terraria.Main.netMode, Terraria.Liquid.numLiquid, Terraria.LiquidBuffer.numLiquidBuffer, Terraria.Liquid.panicCounter, Terraria.Liquid.panicMode, Terraria.Liquid.panicY, Terraria.Main.player, Terraria.Liquid.quickFall, Terraria.Liquid.quickSettle, Terraria.Liquid.QuickWater(), Terraria.Main.Setting_UseReducedMaxLiquids, Terraria.Tile.skipLiquid(), Terraria.Liquid.StartPanic(), Terraria.Liquid.stuckAmount, Terraria.Liquid.stuckCount, Terraria.Main.tile, Terraria.RemoteClient.TileSections, Terraria.Liquid.tilesIgnoreWater(), Terraria.Liquid.Update(), Terraria.WorldGen.WaterCheck(), Terraria.Liquid.wetCounter, System.Console.WriteLine(), Terraria.Liquid.x, Terraria.LiquidBuffer.x, Terraria.Liquid.y, and Terraria.LiquidBuffer.y.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.WorldGen.UpdateWorld().