Terraria Decompiled: Ionic.Zip.ZipOutputStream._InitiateCurrentEntry
_InitiateCurrentEntry()
void Ionic.Zip.ZipOutputStream._InitiateCurrentEntry (bool finishing) inline private
Definition at line 439 of file ZipOutputStream.cs.
        {
            this._entriesWritten.Add(this._currentEntry.FileName, this._currentEntry);
            this._entryCount++;
            if (this._entryCount > 65534 && this._zip64 == Zip64Option.Default)
            {
                this._exceptionPending = true;
                throw new InvalidOperationException("Too many entries. Consider setting ZipOutputStream.EnableZip64.");
            }
            this._currentEntry.WriteHeader(this._outputStream, finishing ? 99 : 0);
            this._currentEntry.StoreRelativeOffset();
            if (!this._currentEntry.IsDirectory)
            {
                this._currentEntry.WriteSecurityMetadata(this._outputStream);
                this._currentEntry.PrepOutputStream(this._outputStream, finishing ? 0L : (-1L), out this._outputCounter, out this._encryptor, out this._deflater, out this._entryOutputStream);
            }
            this._needToWriteEntryHeader = false;
        }
References Ionic.Zip.ZipOutputStream._currentEntry, Ionic.Zip.ZipOutputStream._deflater, Ionic.Zip.ZipOutputStream._encryptor, Ionic.Zip.ZipOutputStream._entriesWritten, Ionic.Zip.ZipOutputStream._entryCount, Ionic.Zip.ZipOutputStream._entryOutputStream, Ionic.Zip.ZipOutputStream._outputCounter, Ionic.Zip.ZipOutputStream._outputStream, Ionic.Zip.ZipOutputStream._zip64, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipEntry.IsDirectory, System.L, Ionic.Zip.ZipEntry.PrepOutputStream(), Ionic.Zip.ZipEntry.StoreRelativeOffset(), Ionic.Zip.ZipEntry.WriteHeader(), and Ionic.Zip.ZipEntry.WriteSecurityMetadata().
Referenced by Ionic.Zip.ZipOutputStream._FinishCurrentEntry(), and Ionic.Zip.ZipOutputStream.Write().