Terraria Decompiled: Terraria.Liquid.LiquidCheck
LiquidCheck()
static void Terraria.Liquid.LiquidCheck (int x, int y, int thisLiquidType, bool createMergeTilesDuringGen = false) inline static
Definition at line 1254 of file Liquid.cs.
        {
            if (!WorldGen.InWorld(x, y, 1))
            {
                return;
            }
            if (WorldGen.SolidTile(x, y, false))
            {
                return;
            }
            Tile tile = Main.tile[x - 1, y];
            Tile tile2 = Main.tile[x + 1, y];
            Tile tile3 = Main.tile[x, y - 1];
            Tile tile4 = Main.tile[x, y + 1];
            Tile tile5 = Main.tile[x, y];
            if ((tile.liquid > 0 && (int)tile.liquidType() != thisLiquidType) || (tile2.liquid > 0 && (int)tile2.liquidType() != thisLiquidType) || (tile3.liquid > 0 && (int)tile3.liquidType() != thisLiquidType))
            {
                bool flag = tile.anyWater() || tile2.anyWater() || tile3.anyWater();
                bool flag2 = tile.anyLava() || tile2.anyLava() || tile3.anyLava();
                bool flag3 = tile.anyHoney() || tile2.anyHoney() || tile3.anyHoney();
                bool flag4 = tile.anyShimmer() || tile2.anyShimmer() || tile3.anyShimmer();
                int num = 0;
                if ((int)tile.liquidType() != thisLiquidType)
                {
                    num += (int)tile.liquid;
                    tile.liquid = 0;
                }
                if ((int)tile2.liquidType() != thisLiquidType)
                {
                    num += (int)tile2.liquid;
                    tile2.liquid = 0;
                }
                if ((int)tile3.liquidType() != thisLiquidType)
                {
                    num += (int)tile3.liquid;
                    tile3.liquid = 0;
                }
                int num2 = 56;
                int num3 = 0;
                Liquid.GetLiquidMergeTypes(thisLiquidType, out num2, out num3, flag, flag2, flag3, flag4);
                if (num >= 24 && num3 != thisLiquidType && (!tile5.active() || Main.tileObsidianKill[(int)tile5.type]))
                {
                    tile5.liquid = 0;
                    Liquid.CreateLiquidMergeTile(x, y, thisLiquidType, num3, num2, createMergeTilesDuringGen);
                    return;
                }
            }
            else if (tile4.liquid > 0 && (int)tile4.liquidType() != thisLiquidType)
            {
                bool flag5 = false;
                if (tile5.active() && TileID.Sets.IsAContainer[(int)tile5.type] && !TileID.Sets.IsAContainer[(int)tile4.type])
                {
                    flag5 = true;
                }
                if (thisLiquidType != 0 && Main.tileCut[(int)tile4.type])
                {
                    WorldGen.KillTile(x, y + 1, false, false, false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)(y + 1), 0f, 0, 0, 0);
                    }
                }
                if (!tile4.active() || Main.tileObsidianKill[(int)tile4.type] || flag5)
                {
                    if (tile5.liquid < 24)
                    {
                        tile5.liquid = 0;
                        tile5.liquidType(0);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, x - 1, y, 3, TileChangeType.None);
                            return;
                        }
                    }
                    else
                    {
                        int num4 = 56;
                        int num5 = 0;
                        bool flag6 = tile4.water();
                        bool flag7 = tile4.lava();
                        bool flag8 = tile4.honey();
                        bool flag9 = tile4.shimmer();
                        Liquid.GetLiquidMergeTypes(thisLiquidType, out num4, out num5, flag6, flag7, flag8, flag9);
                        tile5.liquid = 0;
                        tile4.liquid = 0;
                        Liquid.CreateLiquidMergeTile(x, y + 1, thisLiquidType, num5, num4, createMergeTilesDuringGen);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.anyHoney(), Terraria.Tile.anyLava(), Terraria.Tile.anyShimmer(), Terraria.Tile.anyWater(), Terraria.Liquid.CreateLiquidMergeTile(), Terraria.Liquid.GetLiquidMergeTypes(), Terraria.Tile.honey(), int, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsAContainer, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.shimmer(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileObsidianKill, Terraria.Tile.type, Terraria.Tile.water(), Terraria.Liquid.x, and Terraria.Liquid.y.
Referenced by Terraria.Liquid.HoneyCheck(), Terraria.Liquid.LavaCheck(), and Terraria.Liquid.ShimmerCheck().