Terraria Decompiled: Ionic.Zip.ZipOutputStream.Dispose
Dispose()
override void Ionic.Zip.ZipOutputStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Definition at line 480 of file ZipOutputStream.cs.
        {
            if (this._disposed)
            {
                return;
            }
            if (disposing && !this._exceptionPending)
            {
                this._FinishCurrentEntry();
                this._directoryNeededZip64 = ZipOutput.WriteCentralDirectoryStructure(this._outputStream, this._entriesWritten.Values, 1U, this._zip64, this.Comment, new ZipContainer(this));
                CountingStream countingStream = this._outputStream as CountingStream;
                Stream stream;
                if (countingStream != null)
                {
                    stream = countingStream.WrappedStream;
                    countingStream.Close();
                }
                else
                {
                    stream = this._outputStream;
                }
                if (!this._leaveUnderlyingStreamOpen)
                {
                    stream.Close();
                }
                this._outputStream = null;
            }
            this._disposed = true;
        }
References Ionic.Zip.ZipOutputStream._disposed, Ionic.Zip.ZipOutputStream._entriesWritten, Ionic.Zip.ZipOutputStream._exceptionPending, Ionic.Zip.ZipOutputStream._FinishCurrentEntry(), Ionic.Zip.ZipOutputStream._leaveUnderlyingStreamOpen, Ionic.Zip.ZipOutputStream._outputStream, System.IO.Stream.Close(), System.U, System.Collections.Generic.Dictionary< TKey, TValue >.Values, Ionic.Zip.CountingStream.WrappedStream, and Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure().