Terraria Decompiled: Terraria.Liquid.SettleWaterAt
SettleWaterAt()
static void Terraria.Liquid.SettleWaterAt (int originX, int originY) inline static private
Definition at line 115 of file Liquid.cs.
        {
            Tile tile = Main.tile[originX, originY];
            Liquid.tilesIgnoreWater(true);
            if (tile.liquid == 0)
            {
                return;
            }
            if (tile.active() && tile.type == 379)
            {
                return;
            }
            int num = originX;
            int num2 = originY;
            bool flag = tile.lava();
            bool flag2 = tile.honey();
            bool flag3 = tile.shimmer();
            int num3 = (int)tile.liquid;
            byte b = tile.liquidType();
            tile.liquid = 0;
            bool flag4 = true;
            for (;;)
            {
                Tile tile2 = Main.tile[num, num2 + 1];
                bool flag5 = false;
                while (num2 < Main.maxTilesY - 5 && tile2.liquid == 0 && (!tile2.nactive() || !Main.tileSolid[(int)tile2.type] || Main.tileSolidTop[(int)tile2.type]))
                {
                    num2++;
                    flag5 = true;
                    flag4 = false;
                    tile2 = Main.tile[num, num2 + 1];
                }
                if (WorldGen.isGeneratingOrLoadingWorld && flag5 && !flag2 && !flag3)
                {
                    if (WorldGen.remixWorldGen)
                    {
                        if (num2 > GenVars.lavaLine && ((double)num2 < Main.rockLayer - 80.0 || num2 > Main.maxTilesY - 350))
{
                            if (WorldGen.oceanDepths(num, num2))
{
                                b = 0;
                            }
                            else
{
                                b = 1;
                            }
                        }
                        else
{
                            b = 0;
                        }
                    }
                    else if (num2 > GenVars.waterLine)
                    {
                        b = 1;
                    }
                    if (WorldGen.generatingWorld && DungeonUtils.InAnyPotentialDungeonBounds(num, num2, 0, false) && DungeonUtils.IsConsideredDungeonWall((int)tile.wall, true))
                    {
                        b = 0;
                    }
                }
                int num4 = -1;
                int num5 = 0;
                int num6 = -1;
                int num7 = 0;
                bool flag6 = false;
                bool flag7 = false;
                bool flag8 = false;
                for (;;)
                {
                    if (Main.tile[num + num5 * num4, num2].liquid == 0)
                    {
                        num6 = num4;
                        num7 = num5;
                    }
                    if (num4 == -1 && num + num5 * num4 < 5)
                    {
                        flag7 = true;
                    }
                    else if (num4 == 1 && num + num5 * num4 > Main.maxTilesX - 5)
                    {
                        flag6 = true;
                    }
                    tile2 = Main.tile[num + num5 * num4, num2 + 1];
                    if (tile2.liquid != 0 && tile2.liquid != 255 && tile2.liquidType() == b)
                    {
                        int num8 = (int)(byte.MaxValue - tile2.liquid);
                        if (num8 > num3)
{
                            num8 = num3;
                        }
                        Tile tile3 = tile2;
                        tile3.liquid += (byte)num8;
                        num3 -= num8;
                        if (num3 == 0)
{
                            break;
                        }
                    }
                    if (num2 < Main.maxTilesY - 5 && tile2.liquid == 0 && (!tile2.nactive() || !Main.tileSolid[(int)tile2.type] || Main.tileSolidTop[(int)tile2.type]))
                    {
                        goto IL_0267;
                    }
                    Tile tile4 = Main.tile[num + (num5 + 1) * num4, num2];
                    if ((tile4.liquid != 0 && (!flag4 || num4 != 1)) || (tile4.nactive() && Main.tileSolid[(int)tile4.type] && !Main.tileSolidTop[(int)tile4.type]))
                    {
                        if (num4 == 1)
{
                            flag6 = true;
                        }
                        else
{
                            flag7 = true;
                        }
                    }
                    if (flag7 && flag6)
                    {
                        break;
                    }
                    if (flag6)
                    {
                        num4 = -1;
                        num5++;
                    }
                    else if (flag7)
                    {
                        if (num4 == 1)
{
                            num5++;
                        }
                        num4 = 1;
                    }
                    else
                    {
                        if (num4 == 1)
{
                            num5++;
                        }
                        num4 = -num4;
                    }
                }
                IL_0310:
                num += num7 * num6;
                if (num3 != 0 && flag8)
                {
                    num2++;
                    continue;
                }
                break;
                IL_0267:
                flag8 = true;
                goto IL_0310;
            }
            Main.tile[num, num2].liquid = (byte)num3;
            Main.tile[num, num2].liquidType((int)b);
            if (Main.tile[num, num2].liquid > 0)
            {
                Liquid.AttemptToMoveLava(num, num2, flag);
                Liquid.AttemptToMoveHoney(num, num2, flag2);
                Liquid.AttemptToMoveShimmer(num, num2, flag3);
            }
            Liquid.tilesIgnoreWater(false);
        }
References Terraria.Tile.active(), Terraria.Liquid.AttemptToMoveHoney(), Terraria.Liquid.AttemptToMoveLava(), Terraria.Liquid.AttemptToMoveShimmer(), Terraria.WorldGen.generatingWorld, Terraria.Tile.honey(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.InAnyPotentialDungeonBounds(), int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.lava(), Terraria.WorldBuilding.GenVars.lavaLine, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.WorldGen.oceanDepths(), Terraria.WorldGen.remixWorldGen, Terraria.Tile.shimmer(), Terraria.Main.tile, Terraria.Liquid.tilesIgnoreWater(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.WorldBuilding.GenVars.waterLine.
Referenced by Terraria.Liquid.QuickWater().