Terraria Decompiled: Terraria.Liquid.AttemptToMoveLava
AttemptToMoveLava()
static void Terraria.Liquid.AttemptToMoveLava (int X, int Y, bool tileAtXYHasLava) inline static private
Definition at line 328 of file Liquid.cs.
        {
            if (Main.tile[X - 1, Y].liquid > 0 && Main.tile[X - 1, Y].lava() != tileAtXYHasLava)
            {
                if (tileAtXYHasLava)
                {
                    Liquid.LavaCheck(X, Y);
                    return;
                }
                Liquid.LavaCheck(X - 1, Y);
                return;
            }
            else if (Main.tile[X + 1, Y].liquid > 0 && Main.tile[X + 1, Y].lava() != tileAtXYHasLava)
            {
                if (tileAtXYHasLava)
                {
                    Liquid.LavaCheck(X, Y);
                    return;
                }
                Liquid.LavaCheck(X + 1, Y);
                return;
            }
            else
            {
                if (Main.tile[X, Y - 1].liquid <= 0 || Main.tile[X, Y - 1].lava() == tileAtXYHasLava)
                {
                    if (Main.tile[X, Y + 1].liquid > 0 && Main.tile[X, Y + 1].lava() != tileAtXYHasLava)
                    {
                        if (tileAtXYHasLava)
{
                            Liquid.LavaCheck(X, Y);
                            return;
                        }
                        Liquid.LavaCheck(X, Y + 1);
                    }
                    return;
                }
                if (tileAtXYHasLava)
                {
                    Liquid.LavaCheck(X, Y);
                    return;
                }
                Liquid.LavaCheck(X, Y - 1);
                return;
            }
        }
References Terraria.Tile.lava(), Terraria.Liquid.LavaCheck(), Terraria.Tile.liquid, Terraria.Main.tile, System.X, and System.Y.
Referenced by Terraria.Liquid.SettleWaterAt().