Terraria Decompiled: Terraria.Liquid.AddWater
AddWater()
static void Terraria.Liquid.AddWater (int x, int y) inline static
Definition at line 1168 of file Liquid.cs.
        {
            Tile tile = Main.tile[x, y];
            if (Main.tile[x, y] == null)
            {
                return;
            }
            if (tile.checkingLiquid())
            {
                return;
            }
            if (x >= Main.maxTilesX - 5 || y >= Main.maxTilesY - 5)
            {
                return;
            }
            if (x < 5 || y < 5)
            {
                return;
            }
            if (tile.liquid == 0)
            {
                return;
            }
            if (tile.nactive() && Main.tileSolid[(int)tile.type] && tile.type != 546 && !Main.tileSolidTop[(int)tile.type])
            {
                return;
            }
            if (Liquid.numLiquid >= Liquid.curMaxLiquid - 1)
            {
                LiquidBuffer.AddBuffer(x, y);
                return;
            }
            tile.checkingLiquid(true);
            tile.skipLiquid(false);
            Main.liquid[Liquid.numLiquid].kill = 0;
            Main.liquid[Liquid.numLiquid].x = x;
            Main.liquid[Liquid.numLiquid].y = y;
            Main.liquid[Liquid.numLiquid].delay = 0;
            Liquid.numLiquid++;
            if (Main.netMode == 2)
            {
                Liquid.NetSendLiquid(x, y);
            }
            if (tile.active() && !WorldGen.isGeneratingOrLoadingWorld)
            {
                bool flag = false;
                if (tile.lava())
                {
                    if (TileObjectData.CheckLavaDeath(tile))
                    {
                        flag = true;
                    }
                }
                else if (TileObjectData.CheckWaterDeath(tile))
                {
                    flag = true;
                }
                if (flag)
                {
                    WorldGen.KillTile(x, y, false, false, false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.LiquidBuffer.AddBuffer(), Terraria.Tile.checkingLiquid(), Terraria.ObjectData.TileObjectData.CheckLavaDeath(), Terraria.ObjectData.TileObjectData.CheckWaterDeath(), Terraria.Liquid.curMaxLiquid, Terraria.Liquid.delay, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Liquid.kill, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Main.liquid, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Liquid.NetSendLiquid(), Terraria.Liquid.numLiquid, Terraria.NetMessage.SendData(), Terraria.Tile.skipLiquid(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Terraria.Liquid.x, and Terraria.Liquid.y.
Referenced by Terraria.Liquid.DelWater(), Terraria.WorldGen.EmptyLiquid(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.DelegateMethods.SpreadTile(), Terraria.WorldGen.TileFrame(), Terraria.Liquid.Update(), Terraria.Liquid.UpdateLiquid(), and Terraria.WorldGen.WaterCheck().