Terraria Decompiled: Terraria.Liquid.CreateLiquidMergeTile
CreateLiquidMergeTile()
static void Terraria.Liquid.CreateLiquidMergeTile (int x, int y, int thisLiquidType, int liquidMergeType, int liquidMergeTileType, bool createMergeTilesDuringGen) inline static private
Definition at line 1363 of file Liquid.cs.
        {
            Tile tile = Main.tile[x, y];
            TileChangeType liquidChangeType = WorldGen.GetLiquidChangeType(thisLiquidType, liquidMergeType);
            if (WorldGen.isGeneratingOrLoadingWorld && !createMergeTilesDuringGen)
            {
                int num = -1;
                if (liquidMergeTileType == 229)
                {
                    num = 0;
                }
                else if (liquidMergeTileType == 230)
                {
                    num = 1;
                }
                else if (liquidMergeTileType == 56)
                {
                    num = 1;
                }
                else if (liquidMergeTileType == 659)
                {
                    num = 3;
                }
                if (y >= Main.UnderworldLayer)
                {
                    num = 1;
                }
                Liquid.LiquidOverwriteStrip(x, y, num);
                return;
            }
            if (!Main.gameMenu && !WorldGen.isGeneratingOrLoadingWorld)
            {
                WorldGen.PlayLiquidChangeSound(liquidChangeType, x, y, 1);
            }
            bool flag = true;
            Utils.Swap<bool>(ref flag, ref Main.tileSolid[546]);
            if (!tile.active() || !WorldGen.ReplaceTile(x, y, liquidMergeTileType, 0))
            {
                WorldGen.KillTile(x, y, false, false, false);
                WorldGen.PlaceTile(x, y, liquidMergeTileType, true, true, -1, 0);
            }
            WorldGen.SquareTileFrame(x, y, true);
            Main.tileSolid[546] = flag;
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, x - 1, y - 1, 3, liquidChangeType);
            }
        }
References Terraria.Tile.active(), Terraria.Main.gameMenu, Terraria.WorldGen.GetLiquidChangeType(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.KillTile(), Terraria.Liquid.LiquidOverwriteStrip(), Terraria.Main.netMode, Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlayLiquidChangeSound(), Terraria.WorldGen.ReplaceTile(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.UnderworldLayer, Terraria.Liquid.x, and Terraria.Liquid.y.
Referenced by Terraria.Liquid.LiquidCheck().