Terraria Decompiled: Terraria.GameContent.UI.UIPopupText.Update
Update()
void Terraria.GameContent.UI.UIPopupText.Update (int whoAmI, UIPopupTextManager manager) inline
Definition at line 26 of file UIPopupText.cs.
        {
            if (this.active)
            {
                this.framesSinceSpawn++;
                float targetScale = this.TargetScale;
                this.alpha += (float)this.alphaDir * 0.01f;
                if ((double)this.alpha <= 0.7)
                {
                    this.alpha = 0.7f;
                    this.alphaDir = 1;
                }
                if (this.alpha >= 1f)
                {
                    this.alpha = 1f;
                    this.alphaDir = -1;
                }
                bool flag = false;
                Vector2 textHitbox = this.GetTextHitbox();
                Rectangle rectangle = new Rectangle((int)(this.position.X - textHitbox.X / 2f), (int)(this.position.Y - textHitbox.Y / 2f), (int)textHitbox.X, (int)textHitbox.Y);
                for (int i = 0; i < 20; i++)
                {
                    UIPopupText uipopupText = manager.popupText[i];
                    if (uipopupText.active && i != whoAmI)
                    {
                        Vector2 textHitbox2 = uipopupText.GetTextHitbox();
                        Rectangle rectangle2 = new Rectangle((int)(uipopupText.position.X - textHitbox2.X / 2f), (int)(uipopupText.position.Y - textHitbox2.Y / 2f), (int)textHitbox2.X, (int)textHitbox2.Y);
                        if (rectangle.Intersects(rectangle2) && (this.position.Y < uipopupText.position.Y || (this.position.Y == uipopupText.position.Y && whoAmI < i)))
{
                            flag = true;
                            int num = manager.numActive;
                            if (num > 3)
{
                                num = 3;
                            }
                            uipopupText.lifeTime = UIPopupText.activeTime + 15 * num;
                            this.lifeTime = UIPopupText.activeTime + 15 * num;
                        }
                    }
                }
                if (!flag)
                {
                    if (this.context != UIPopupTextContext.SpecialSeed || (this.scale != targetScale && this.lifeTime > 0))
                    {
                        this.velocity.Y = this.velocity.Y * 0.86f;
                        if (this.scale == targetScale)
{
                            this.velocity.Y = this.velocity.Y * 0.4f;
                        }
                    }
                }
                else if (this.velocity.Y > -6f)
                {
                    this.velocity.Y = this.velocity.Y - 0.2f;
                }
                else
                {
                    this.velocity.Y = this.velocity.Y * 0.86f;
                }
                this.velocity.X = this.velocity.X * 0.93f;
                this.position += this.velocity;
                this.lifeTime--;
                if (this.lifeTime <= 0)
                {
                    this.scale -= 0.03f * targetScale;
                    if ((double)this.scale < 0.1 * (double)targetScale)
                    {
                        this.active = false;
                    }
                    this.lifeTime = 0;
                    return;
                }
                if (this.scale < targetScale)
                {
                    this.scale += 0.1f * targetScale;
                }
                if (this.scale > targetScale)
                {
                    this.scale = targetScale;
                }
            }
        }
References Terraria.GameContent.UI.UIPopupText.active, Terraria.GameContent.UI.UIPopupText.alpha, Terraria.GameContent.UI.UIPopupText.alphaDir, Terraria.GameContent.UI.UIPopupText.context, Terraria.GameContent.UI.UIPopupText.framesSinceSpawn, Terraria.GameContent.UI.UIPopupText.GetTextHitbox(), Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.GameContent.UI.UIPopupText.lifeTime, Terraria.GameContent.UI.UIPopupTextManager.numActive, Terraria.GameContent.UI.UIPopupTextManager.popupText, Terraria.GameContent.UI.UIPopupText.position, Terraria.GameContent.UI.UIPopupText.scale, Terraria.GameContent.UI.UIPopupText.TargetScale, Terraria.GameContent.UI.UIPopupText.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.UIPopupTextManager.UpdateItemText().