Terraria Decompiled: Terraria.Social.Steam.SteamP2PWriter.QueueSend
QueueSend()
void Terraria.Social.Steam.SteamP2PWriter.QueueSend (CSteamID user, byte[] data, int length) inline
Definition at line 18 of file SteamP2PWriter.cs.
        {
            object @lock = this._lock;
            lock (@lock)
            {
                Queue<SteamP2PWriter.WriteInformation> queue;
                if (this._pendingSendData.ContainsKey(user))
                {
                    queue = this._pendingSendData[user];
                }
                else
                {
                    queue = (this._pendingSendData[user] = new Queue<SteamP2PWriter.WriteInformation>());
                }
                int i = length;
                int num = 0;
                while (i > 0)
                {
                    SteamP2PWriter.WriteInformation writeInformation;
                    if (queue.Count == 0 || 1024 - queue.Peek().Size == 0)
                    {
                        byte[] array;
                        if (!this._bufferPool.TryTake(out array))
{
                            array = new byte[1024];
                        }
                        writeInformation = new SteamP2PWriter.WriteInformation(array);
                        queue.Enqueue(writeInformation);
                    }
                    else
                    {
                        writeInformation = queue.Peek();
                    }
                    int num2 = Math.Min(i, 1024 - writeInformation.Size);
                    Array.Copy(data, num, writeInformation.Data, writeInformation.Size, num2);
                    writeInformation.Size += num2;
                    i -= num2;
                    num += num2;
                }
            }
        }
References Terraria.Social.Steam.SteamP2PWriter._bufferPool, Terraria.Social.Steam.SteamP2PWriter._lock, Terraria.Social.Steam.SteamP2PWriter._pendingSendData, System.array, System.Array.Copy(), Terraria.Social.Steam.SteamP2PWriter.WriteInformation.Data, System.length, System.Math.Min(), System.queue, and Terraria.Social.Steam.SteamP2PWriter.WriteInformation.Size.
Referenced by Terraria.Social.Steam.NetSocialModule.Send().