Terraria Decompiled: System.ParameterizedStrings.Evaluate
Evaluate()
static string System.ParameterizedStrings.Evaluate (string format, params ParameterizedStrings::FormatParam[] args) inline static
Definition at line 11 of file ParameterizedStrings.cs.
        {
            if (format == null)
            {
                throw new ArgumentNullException("format");
            }
            if (args == null)
            {
                throw new ArgumentNullException("args");
            }
            ParameterizedStrings.LowLevelStack lowLevelStack = ParameterizedStrings._cachedStack;
            if (lowLevelStack == null)
            {
                lowLevelStack = (ParameterizedStrings._cachedStack = new ParameterizedStrings.LowLevelStack());
            }
            else
            {
                lowLevelStack.Clear();
            }
            ParameterizedStrings.FormatParam[] array = null;
            ParameterizedStrings.FormatParam[] array2 = null;
            int num = 0;
            return ParameterizedStrings.EvaluateInternal(format, ref num, args, lowLevelStack, ref array, ref array2);
        }
References System.ParameterizedStrings._cachedStack, System.array, System.ParameterizedStrings.LowLevelStack.Clear(), System.ParameterizedStrings.EvaluateInternal(), and System.format.
Referenced by System.TermInfoDriver.ChangeColor(), and System.TermInfoDriver.SetCursorPosition().