Terraria Decompiled: Terraria.UI.UIElement.GetSnapPoints
GetSnapPoints()
virtual List< SnapPoint > Terraria.UI.UIElement.GetSnapPoints () inline virtual
Reimplemented in Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >, and Terraria.GameContent.UI.Elements.UIList.
Definition at line 674 of file UIElement.cs.
        {
            List<SnapPoint> list = new List<SnapPoint>();
            SnapPoint snapPoint;
            if (this.GetSnapPoint(out snapPoint))
            {
                list.Add(snapPoint);
            }
            foreach (UIElement uielement in this.Elements)
            {
                list.AddRange(uielement.GetSnapPoints());
            }
            return list;
        }
References Terraria.UI.UIElement.GetSnapPoint(), Terraria.UI.UIElement.GetSnapPoints(), and System.list.
Referenced by Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.GetSnapPoints(), Terraria.GameContent.UI.Elements.UIList.GetSnapPoints(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.GameContent.UI.States.UICreativePowersMenu.SetupGamepadPoints(), Terraria.GameContent.UI.NewCraftingUI.SetupGamepadPoints(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIBestiaryTest.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UICharacterSelect.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIReportsPage.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldCreation.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.SetupGamepadPoints(), Terraria.GameContent.UI.States.UIWorldSelect.SetupGamepadPoints(), and Terraria.GameContent.UI.States.UIEmotesMenu.SetupGamepadPoints2().