Terraria Decompiled: Terraria.UI.UIElement.SetPadding
SetPadding()
void Terraria.UI.UIElement.SetPadding (float pixels) inline
Definition at line 783 of file UIElement.cs.
        {
            this.PaddingBottom = pixels;
            this.PaddingLeft = pixels;
            this.PaddingRight = pixels;
            this.PaddingTop = pixels;
        }
Referenced by Terraria.GameContent.UI.States.UIBestiaryTest.AddBackAndForwardButtons(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.AddSearchBar(), Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.BuildContainer(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage(), Terraria.GameContent.UI.States.UIBestiaryTest.BuildPage(), Terraria.GameContent.UI.States.UICharacterCreation.BuildPage(), Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreation.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreateOffsetButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackInfoButton(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer(), Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UITextWrappingTest.MakeElement(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairstylesMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeInfoMenu(), Terraria.GameContent.UI.NewCraftingUI.NewCraftingUI(), Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnInitialize(), Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize(), Terraria.GameContent.UI.Elements.PowerStripUIElement.PowerStripUIElement(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.ProvideUIElement(), Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton(), Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.UIBestiaryEntryInfoPage(), Terraria.GameContent.UI.Elements.UIBestiaryNPCEntryPortrait.UIBestiaryNPCEntryPortrait(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), Terraria.GameContent.UI.States.UITextWrappingTest.UITextWrappingTest(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug(), and Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability().