Terraria Decompiled: Terraria.UI.UIElement.RightMouseDown
RightMouseDown()
virtual void Terraria.UI.UIElement.RightMouseDown (UIMouseEvent evt) inline virtual
Definition at line 891 of file UIElement.cs.
        {
            if (this.OnRightMouseDown != null)
            {
                this.OnRightMouseDown(evt, this);
            }
            if (this.Parent != null)
            {
                this.Parent.RightMouseDown(evt);
            }
        }
References Terraria.UI.UIElement.OnRightMouseDown, Terraria.UI.UIElement.Parent, and Terraria.UI.UIElement.RightMouseDown().
Referenced by Terraria.UI.UIElement.RightMouseDown(), and Terraria.UI.UserInterface.UserInterface().