Terraria Decompiled: Terraria.UI.UIElement.CopyStyle
CopyStyle()
void Terraria.UI.UIElement.CopyStyle (UIElement element) inline
Definition at line 819 of file UIElement.cs.
        {
            this.Top = element.Top;
            this.Left = element.Left;
            this.Width = element.Width;
            this.Height = element.Height;
            this.PaddingBottom = element.PaddingBottom;
            this.PaddingLeft = element.PaddingLeft;
            this.PaddingRight = element.PaddingRight;
            this.PaddingTop = element.PaddingTop;
            this.HAlign = element.HAlign;
            this.VAlign = element.VAlign;
            this.MinWidth = element.MinWidth;
            this.MaxWidth = element.MaxWidth;
            this.MinHeight = element.MinHeight;
            this.MaxHeight = element.MaxHeight;
            this.Recalculate();
        }
References Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.MaxHeight, Terraria.UI.UIElement.MaxWidth, Terraria.UI.UIElement.MinHeight, Terraria.UI.UIElement.MinWidth, Terraria.UI.UIElement.PaddingBottom, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingRight, Terraria.UI.UIElement.PaddingTop, Terraria.UI.UIElement.Recalculate(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize(), and Terraria.GameContent.UI.States.UIWorldLoad.UIWorldLoad().