Terraria Decompiled: Terraria.UI.UIElement.DrawDebugHitbox
DrawDebugHitbox()
void Terraria.UI.UIElement.DrawDebugHitbox (BasicDebugDrawer drawer, float colorIntensity = 0f) inline
Definition at line 1004 of file UIElement.cs.
        {
            if (this.IsMouseHovering)
            {
                colorIntensity += 0.1f;
            }
            Color color = Main.hslToRgb(colorIntensity, colorIntensity, 0.5f, byte.MaxValue);
            CalculatedStyle innerDimensions = this.GetInnerDimensions();
            drawer.DrawLine(innerDimensions.Position(), innerDimensions.Position() + new Vector2(innerDimensions.Width, 0f), 2f, color);
            drawer.DrawLine(innerDimensions.Position() + new Vector2(innerDimensions.Width, 0f), innerDimensions.Position() + new Vector2(innerDimensions.Width, innerDimensions.Height), 2f, color);
            drawer.DrawLine(innerDimensions.Position() + new Vector2(innerDimensions.Width, innerDimensions.Height), innerDimensions.Position() + new Vector2(0f, innerDimensions.Height), 2f, color);
            drawer.DrawLine(innerDimensions.Position() + new Vector2(0f, innerDimensions.Height), innerDimensions.Position(), 2f, color);
            foreach (UIElement uielement in this.Elements)
            {
            }
        }
References ReLogic.Graphics.BasicDebugDrawer.DrawLine(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.CalculatedStyle.Height, Terraria.Main.hslToRgb(), Terraria.UI.UIElement.IsMouseHovering, Terraria.UI.CalculatedStyle.Position(), and Terraria.UI.CalculatedStyle.Width.