Terraria Decompiled: Terraria.UI.UIElement.LeftMouseDown
LeftMouseDown()
virtual void Terraria.UI.UIElement.LeftMouseDown (UIMouseEvent evt) inline virtual
Reimplemented in Terraria.GameContent.UI.Elements.GroupOptionButton< T >, Terraria.GameContent.UI.Elements.UICharacterNameButton, Terraria.GameContent.UI.Elements.UIClothStyleButton, Terraria.GameContent.UI.Elements.UIDifficultyButton, Terraria.GameContent.UI.Elements.UIHairStyleButton, Terraria.GameContent.UI.Elements.UIIconTextButton, and Terraria.GameContent.UI.Elements.UIScrollbar.
Definition at line 839 of file UIElement.cs.
        {
            if (this.OnLeftMouseDown != null)
            {
                this.OnLeftMouseDown(evt, this);
            }
            if (this.Parent != null)
            {
                this.Parent.LeftMouseDown(evt);
            }
        }
References Terraria.UI.UIElement.LeftMouseDown(), Terraria.UI.UIElement.OnLeftMouseDown, and Terraria.UI.UIElement.Parent.
Referenced by Terraria.UI.UIElement.LeftMouseDown(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MouseOverSeed(), and Terraria.UI.UserInterface.UserInterface().