Terraria Decompiled: Terraria.UI.UIElement.SetSnapPoint
SetSnapPoint()
void Terraria.UI.UIElement.SetSnapPoint (string name, int id, Vector2? anchor = null, Vector2? offset = null) inline
Definition at line 513 of file UIElement.cs.
        {
            if (anchor == null)
            {
                anchor = new Vector2?(new Vector2(0.5f));
            }
            if (offset == null)
            {
                offset = new Vector2?(Vector2.Zero);
            }
            this._snapPoint = new SnapPoint(name, id, anchor.Value, offset.Value);
        }
References System.name, System.offset, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.AddBackAndFolderButtons(), Terraria.GameContent.UI.States.UIBestiaryTest.AddBackAndForwardButtons(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddBackButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSeedButtons(), Terraria.GameContent.UI.States.UIBestiaryTest.AddSortAndFilterButtons(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), Terraria.GameContent.UI.States.UICharacterCreation.CreateColorPicker(), Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup(), Terraria.GameContent.UI.States.UICharacterCreation.CreateHSLSlider(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.UI.Elements.EmotesGroupListItem.EmotesGroupListItem(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FillBestiarySpaceWithEntries(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.UI.States.UICharacterCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UICharacterCreation.MakeCategoriesBar(), Terraria.GameContent.UI.States.UICharacterCreation.MakeClothStylesMenu(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairstylesMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHSLMenu(), Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList(), Terraria.GameContent.UI.Elements.PowerStripUIElement.PowerStripUIElement(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.SetSearchSnapPoint(), Terraria.GameContent.UI.Elements.UICharacterListItem.UICharacterListItem(), Terraria.GameContent.UI.Elements.UICreativeItemsInfiniteFilteringOptions.UICreativeItemsInfiniteFilteringOptions(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), Terraria.GameContent.UI.Elements.UIWorldListItem.UIWorldListItem(), and Terraria.GameContent.UI.Elements.UIBestiaryFilteringOptionsGrid.UpdateAvailability().