Terraria Decompiled: Terraria.UI.UIElement.Draw
Draw()
virtual void Terraria.UI.UIElement.Draw (SpriteBatch spriteBatch) inline virtual
Reimplemented in Terraria.GameContent.UI.Elements.UIClothStyleButton, Terraria.GameContent.UI.NewCraftingUI, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >, Terraria.GameContent.UI.States.UIAchievementsMenu, Terraria.GameContent.UI.States.UIBestiaryTest, Terraria.GameContent.UI.States.UICharacterCreation, Terraria.GameContent.UI.States.UICharacterSelect, Terraria.GameContent.UI.States.UICreativePowersMenu, Terraria.GameContent.UI.States.UIEmotesMenu, Terraria.GameContent.UI.States.UIManageControls, Terraria.GameContent.UI.States.UIReportsPage, Terraria.GameContent.UI.States.UIResourcePackInfoMenu, Terraria.GameContent.UI.States.UIResourcePackSelectionMenu, Terraria.GameContent.UI.States.UITextWrappingTest, Terraria.GameContent.UI.States.UIWorkshopHub, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish, Terraria.GameContent.UI.States.UIWorkshopWorldImport, Terraria.GameContent.UI.States.UIWorldCreation, Terraria.GameContent.UI.States.UIWorldCreationAdvanced, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList, Terraria.GameContent.UI.States.UIWorldGenDebug, Terraria.GameContent.UI.States.UIWorldLoad, and Terraria.GameContent.UI.States.UIWorldSelect.
Definition at line 597 of file UIElement.cs.
        {
            if (this.OnDraw != null)
            {
                this.OnDraw(this, spriteBatch);
            }
            bool overflowHidden = this.OverflowHidden;
            bool useImmediateMode = this.UseImmediateMode;
            RasterizerState rasterizerState = spriteBatch.GraphicsDevice.RasterizerState;
            Rectangle scissorRectangle = spriteBatch.GraphicsDevice.ScissorRectangle;
            SamplerState anisotropicClamp = SamplerState.AnisotropicClamp;
            if (useImmediateMode || this.OverrideSamplerState != null)
            {
                spriteBatch.End();
                spriteBatch.Begin(useImmediateMode ? SpriteSortMode.Immediate : SpriteSortMode.Deferred, BlendState.AlphaBlend, (this.OverrideSamplerState != null) ? this.OverrideSamplerState : anisotropicClamp, DepthStencilState.None, UIElement.OverflowHiddenRasterizerState, null, Main.UIScaleMatrix);
                this.DrawSelf(spriteBatch);
                spriteBatch.End();
                spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, anisotropicClamp, DepthStencilState.None, UIElement.OverflowHiddenRasterizerState, null, Main.UIScaleMatrix);
            }
            else
            {
                this.DrawSelf(spriteBatch);
            }
            if (overflowHidden)
            {
                spriteBatch.End();
                Rectangle clippingRectangle = this.GetClippingRectangle(spriteBatch);
                spriteBatch.GraphicsDevice.ScissorRectangle = clippingRectangle;
                spriteBatch.GraphicsDevice.RasterizerState = UIElement.OverflowHiddenRasterizerState;
                spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, anisotropicClamp, DepthStencilState.None, UIElement.OverflowHiddenRasterizerState, null, Main.UIScaleMatrix);
            }
            this.DrawChildren(spriteBatch);
            if (overflowHidden)
            {
                spriteBatch.End();
                spriteBatch.GraphicsDevice.ScissorRectangle = scissorRectangle;
                spriteBatch.GraphicsDevice.RasterizerState = rasterizerState;
                spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, anisotropicClamp, DepthStencilState.None, rasterizerState, null, Main.UIScaleMatrix);
            }
        }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SamplerState.AnisotropicClamp, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.UI.UIElement.DrawChildren(), Terraria.UI.UIElement.DrawSelf(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.UI.UIElement.GetClippingRectangle(), Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.UI.UIElement.OnDraw, Terraria.UI.UIElement.OverflowHidden, Terraria.UI.UIElement.OverflowHiddenRasterizerState, Terraria.UI.UIElement.OverrideSamplerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.RasterizerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.ScissorRectangle, Terraria.Main.UIScaleMatrix, and Terraria.UI.UIElement.UseImmediateMode.
Referenced by Terraria.UI.UserInterface.Draw(), Terraria.GameContent.UI.Elements.UIList.UIInnerList.DrawChildren(), and Terraria.UI.UIElement.DrawChildren().