Terraria Decompiled: Terraria.UI.UIElement.Recalculate
Recalculate()
virtual void Terraria.UI.UIElement.Recalculate () inline virtual
Reimplemented in Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid, Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage, Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >, Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >, Terraria.GameContent.UI.Elements.UIGenProgressBar, Terraria.GameContent.UI.Elements.UIList, Terraria.GameContent.UI.Elements.UIParticleLayer, Terraria.GameContent.UI.Elements.UIText, Terraria.GameContent.UI.Elements.UITextPanel< T >, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >, Terraria.GameContent.UI.States.UIBestiaryTest, Terraria.GameContent.UI.States.UICharacterSelect, Terraria.GameContent.UI.States.UIEmotesMenu, Terraria.GameContent.UI.States.UIReportsPage, Terraria.GameContent.UI.States.UIResourcePackInfoMenu, Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish, Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish, Terraria.GameContent.UI.States.UIWorkshopWorldImport, Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList, Terraria.GameContent.UI.States.UIWorldGenDebug, and Terraria.GameContent.UI.States.UIWorldSelect.
Definition at line 690 of file UIElement.cs.
        {
            CalculatedStyle calculatedStyle;
            if (this.Parent != null)
            {
                calculatedStyle = this.Parent.GetInnerDimensions();
            }
            else
            {
                calculatedStyle = UserInterface.ActiveInstance.GetDimensions();
            }
            if (this.Parent != null && this.Parent is UIList)
            {
                calculatedStyle.Height = float.MaxValue;
            }
            CalculatedStyle dimensionsBasedOnParentDimensions = this.GetDimensionsBasedOnParentDimensions(calculatedStyle);
            this._outerDimensions = dimensionsBasedOnParentDimensions;
            dimensionsBasedOnParentDimensions.X += this.MarginLeft;
            dimensionsBasedOnParentDimensions.Y += this.MarginTop;
            dimensionsBasedOnParentDimensions.Width -= this.MarginLeft + this.MarginRight;
            dimensionsBasedOnParentDimensions.Height -= this.MarginTop + this.MarginBottom;
            this._dimensions = dimensionsBasedOnParentDimensions;
            dimensionsBasedOnParentDimensions.X += this.PaddingLeft;
            dimensionsBasedOnParentDimensions.Y += this.PaddingTop;
            dimensionsBasedOnParentDimensions.Width -= this.PaddingLeft + this.PaddingRight;
            dimensionsBasedOnParentDimensions.Height -= this.PaddingTop + this.PaddingBottom;
            this._innerDimensions = dimensionsBasedOnParentDimensions;
            this.RecalculateChildren();
        }
References Terraria.UI.UserInterface.ActiveInstance, Terraria.UI.UserInterface.GetDimensions(), Terraria.UI.UIElement.GetDimensionsBasedOnParentDimensions(), Terraria.UI.UIElement.GetInnerDimensions(), Terraria.UI.UIElement.MarginBottom, Terraria.UI.UIElement.MarginLeft, Terraria.UI.UIElement.MarginRight, Terraria.UI.UIElement.MarginTop, Terraria.UI.UIElement.PaddingBottom, Terraria.UI.UIElement.PaddingLeft, Terraria.UI.UIElement.PaddingRight, Terraria.UI.UIElement.PaddingTop, Terraria.UI.UIElement.Parent, and Terraria.UI.UIElement.RecalculateChildren().
Referenced by Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIResourcePack.BuildChildren(), Terraria.UI.UIElement.CopyStyle(), Terraria.GameContent.UI.States.UIManageControls.CreateBindingGroup(), Terraria.UI.UserInterface.Draw(), Terraria.GameContent.UI.Elements.UIProgressBar.DrawSelf(), Terraria.GameContent.UI.States.UIVirtualKeyboard.DrawSelf(), Terraria.GameContent.UI.States.UIWorldCreation.FillSeedContent(), Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.HideSearchButton(), Terraria.UI.UserInterface.Recalculate(), Terraria.UI.UIElement.RecalculateChildren(), Terraria.UI.UserInterface.RefreshState(), Terraria.GameContent.UI.Elements.UIProgressBar.UIProgressBar(), Terraria.UI.UIState.UIState(), Terraria.GameContent.UI.States.UIWorldLoad.UIWorldLoad(), Terraria.GameContent.UI.States.UIWorldLoad.Update(), Terraria.GameContent.UI.NewCraftingUI.UpdateCraftAreaSize(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UpdateOffsetDown(), and Terraria.GameContent.UI.NewCraftingUI.UpdateText().