Terraria Decompiled: SteelSeries.GameSense.LocklessQueue.PEnqueue
PEnqueue()
bool SteelSeries.GameSense.LocklessQueue< T >.PEnqueue (T obj) inline
Definition at line 26 of file LocklessQueue.cs.
        {
            int writeIdx;
            for (;;)
            {
                writeIdx = this._writeIdx;
                int readIdx = this._readIdx;
                if (this.index(writeIdx + 1) == this.index(readIdx))
                {
                    break;
                }
                if (Interlocked.CompareExchange(ref this._writeIdx, this.index(writeIdx + 1), writeIdx) == writeIdx)
                {
                    goto Block_1;
                }
            }
            return false;
            Block_1:
            this._bfr[this.index(writeIdx)] = obj;
            while (Interlocked.CompareExchange(ref this._maxReadIdx, this.index(writeIdx + 1), writeIdx) != writeIdx)
            {
            }
            return true;
        }
References SteelSeries.GameSense.LocklessQueue< T >._bfr, SteelSeries.GameSense.LocklessQueue< T >._readIdx, SteelSeries.GameSense.LocklessQueue< T >._writeIdx, System.Threading.Interlocked.CompareExchange(), System.index, and System.obj.
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterEvent(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterEvents(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RegisterGame(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.RemoveGame(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendEvent(), and ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendEvent().