Terraria Decompiled: Terraria.UI.UIElement.LeftMouseUp
LeftMouseUp()
virtual void Terraria.UI.UIElement.LeftMouseUp (UIMouseEvent evt) inline virtual
Reimplemented in Terraria.GameContent.UI.Elements.UIScrollbar.
Definition at line 852 of file UIElement.cs.
        {
            if (this.OnLeftMouseUp != null)
            {
                this.OnLeftMouseUp(evt, this);
            }
            if (this.Parent != null)
            {
                this.Parent.LeftMouseUp(evt);
            }
        }
References Terraria.UI.UIElement.LeftMouseUp(), Terraria.UI.UIElement.OnLeftMouseUp, and Terraria.UI.UIElement.Parent.
Referenced by Terraria.UI.UIElement.LeftMouseUp(), and Terraria.UI.UserInterface.UserInterface().