Terraria Decompiled: Terraria.UI.UIElement.MouseOut
MouseOut()
virtual void Terraria.UI.UIElement.MouseOut (UIMouseEvent evt) inline virtual
Reimplemented in Terraria.GameContent.UI.Elements.EmoteButton, Terraria.GameContent.UI.Elements.GroupOptionButton< T >, Terraria.GameContent.UI.Elements.UIAchievementListItem, Terraria.GameContent.UI.Elements.UICharacterListItem, Terraria.GameContent.UI.Elements.UICharacterNameButton, Terraria.GameContent.UI.Elements.UIClothStyleButton, Terraria.GameContent.UI.Elements.UIColoredImageButton, Terraria.GameContent.UI.Elements.UIDebugCommandItem, Terraria.GameContent.UI.Elements.UIDifficultyButton, Terraria.GameContent.UI.Elements.UIHairStyleButton, Terraria.GameContent.UI.Elements.UIIconTextButton, Terraria.GameContent.UI.Elements.UIImageButton, Terraria.GameContent.UI.Elements.UIResourcePack, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem, Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem, Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem, Terraria.GameContent.UI.Elements.UIWorldListItem, and Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.
Definition at line 957 of file UIElement.cs.
        {
            this.IsMouseHovering = false;
            if (this.OnMouseOut != null)
            {
                this.OnMouseOut(evt, this);
            }
            if (this.Parent != null)
            {
                this.Parent.MouseOut(evt);
            }
        }
References Terraria.UI.UIElement.MouseOut(), Terraria.UI.UIElement.OnMouseOut, and Terraria.UI.UIElement.Parent.
Referenced by Terraria.UI.UIElement.MouseOut(), Terraria.UI.UserInterface.ResetLasts(), Terraria.UI.UserInterface.ResetState(), Terraria.UI.UserInterface.SetState(), and Terraria.UI.UserInterface.Update().