Terraria Decompiled: System.Security.Policy.Evidence.GetDefaultHostEvidence
GetDefaultHostEvidence()
static Evidence System.Security.Policy.Evidence.GetDefaultHostEvidence (Assembly a) inline static package
Definition at line 289 of file Evidence.cs.
        {
            Evidence evidence = new Evidence();
            string escapedCodeBase = a.EscapedCodeBase;
            evidence.AddHost(Zone.CreateFromUrl(escapedCodeBase));
            evidence.AddHost(new Url(escapedCodeBase));
            evidence.AddHost(new Hash(a));
            if (string.Compare("FILE://", 0, escapedCodeBase, 0, 7, true, CultureInfo.InvariantCulture) != 0)
            {
                evidence.AddHost(Site.CreateFromUrl(escapedCodeBase));
            }
            AssemblyName name = a.GetName();
            byte[] publicKey = name.GetPublicKey();
            if (publicKey != null && publicKey.Length != 0)
            {
                StrongNamePublicKeyBlob strongNamePublicKeyBlob = new StrongNamePublicKeyBlob(publicKey);
                evidence.AddHost(new StrongName(strongNamePublicKeyBlob, name.Name, name.Version));
            }
            if (Evidence.IsAuthenticodePresent(a))
            {
                try
                {
                    X509Certificate x509Certificate = X509Certificate.CreateFromSignedFile(a.Location);
                    evidence.AddHost(new Publisher(x509Certificate));
                }
                catch (CryptographicException)
                {
                }
            }
            if (a.GlobalAssemblyCache)
            {
                evidence.AddHost(new GacInstalled());
            }
            AppDomainManager domainManager = AppDomain.CurrentDomain.DomainManager;
            if (domainManager != null && (domainManager.HostSecurityManager.Flags & HostSecurityManagerOptions.HostAssemblyEvidence) == HostSecurityManagerOptions.HostAssemblyEvidence)
            {
                evidence = domainManager.HostSecurityManager.ProvideAssemblyEvidence(a, evidence);
            }
            return evidence;
        }
References System.Security.Policy.Evidence.AddHost(), System.Security.Cryptography.X509Certificates.X509Certificate.CreateFromSignedFile(), System.Security.Policy.Site.CreateFromUrl(), System.Security.Policy.Zone.CreateFromUrl(), System.AppDomain.CurrentDomain, System.AppDomain.DomainManager, System.Reflection.Assembly.EscapedCodeBase, System.Security.Policy.Evidence.Evidence(), System.Reflection.Assembly.GetName(), System.Reflection.AssemblyName.GetPublicKey(), System.Reflection.Assembly.GlobalAssemblyCache, System.AppDomainManager.HostSecurityManager, System.Globalization.CultureInfo.InvariantCulture, System.Security.Policy.Evidence.IsAuthenticodePresent(), System.Reflection.Assembly.Location, and System.name.
Referenced by System.Reflection.Emit.AssemblyBuilder.UnprotectedGetEvidence(), and System.Reflection.RuntimeAssembly.UnprotectedGetEvidence().