Terraria Decompiled: System.Security.Policy.Evidence.AddHost
AddHost()
void System.Security.Policy.Evidence.AddHost (object id) inline
Definition at line 163 of file Evidence.cs.
        {
            if (this._locked && SecurityManager.SecurityEnabled)
            {
                new SecurityPermission(SecurityPermissionFlag.ControlEvidence).Demand();
            }
            this.HostEvidenceList.Add(id);
        }
References System.Security.Policy.Evidence._locked, System.Collections.ArrayList.Add(), System.Security.CodeAccessPermission.Demand(), System.Security.Policy.Evidence.HostEvidenceList, and System.Security.SecurityManager.SecurityEnabled.
Referenced by System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(), System.Security.Policy.Evidence.GetDefaultHostEvidence(), System.Security.Policy.Evidence.Merge(), and System.Reflection.RuntimeAssembly.Resolve().