Terraria Decompiled: System.Security.Policy.Evidence.Merge
Merge()
void System.Security.Policy.Evidence.Merge (Evidence evidence) inline
Definition at line 242 of file Evidence.cs.
        {
            if (evidence != null && evidence.Count > 0)
            {
                if (evidence.hostEvidenceList != null)
                {
                    foreach (object obj in evidence.hostEvidenceList)
                    {
                        this.AddHost(obj);
                    }
                }
                if (evidence.assemblyEvidenceList != null)
                {
                    foreach (object obj2 in evidence.assemblyEvidenceList)
                    {
                        this.AddAssembly(obj2);
                    }
                }
            }
        }
References System.Security.Policy.Evidence.AddAssembly(), System.Security.Policy.Evidence.AddHost(), System.Security.Policy.Evidence.assemblyEvidenceList, System.Security.Policy.Evidence.Count, System.Security.Policy.Evidence.hostEvidenceList, and System.obj.
Referenced by System.Security.Policy.Evidence.Evidence(), and System.Reflection.Assembly.LoadFrom().