Terraria Decompiled: System.NumberFormatter.FormatPercent
FormatPercent()
string System.NumberFormatter.FormatPercent (int precision, NumberFormatInfo nfi) inline private
Definition at line 1383 of file NumberFormatter.cs.
        {
            precision = ((precision >= 0) ? precision : nfi.PercentDecimalDigits);
            this.Multiply10(2);
            this.RoundDecimal(precision);
            this.ResetCharBuf(this.IntegerDigits * 2 + precision + 16);
            if (this._positive)
            {
                if (nfi.PercentPositivePattern == 2)
                {
                    this.Append(nfi.PercentSymbol);
                }
            }
            else
            {
                switch (nfi.PercentNegativePattern)
                {
                case 0:
                    this.Append(nfi.NegativeSign);
                    break;
                case 1:
                    this.Append(nfi.NegativeSign);
                    break;
                case 2:
                    this.Append(nfi.NegativeSign);
                    this.Append(nfi.PercentSymbol);
                    break;
                }
            }
            this.AppendIntegerStringWithGroupSeparator(nfi.PercentGroupSizes, nfi.PercentGroupSeparator);
            if (precision > 0)
            {
                this.Append(nfi.PercentDecimalSeparator);
                this.AppendDecimalString(precision);
            }
            if (this._positive)
            {
                int num = nfi.PercentPositivePattern;
                if (num != 0)
                {
                    if (num == 1)
                    {
                        this.Append(nfi.PercentSymbol);
                    }
                }
                else
                {
                    this.Append(' ');
                    this.Append(nfi.PercentSymbol);
                }
            }
            else
            {
                int num = nfi.PercentNegativePattern;
                if (num != 0)
                {
                    if (num == 1)
                    {
                        this.Append(nfi.PercentSymbol);
                    }
                }
                else
                {
                    this.Append(' ');
                    this.Append(nfi.PercentSymbol);
                }
            }
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._ind, System.NumberFormatter._positive, System.NumberFormatter.Append(), System.NumberFormatter.AppendDecimalString(), System.NumberFormatter.AppendIntegerStringWithGroupSeparator(), System.NumberFormatter.IntegerDigits, System.NumberFormatter.Multiply10(), System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.PercentDecimalDigits, System.Globalization.NumberFormatInfo.PercentDecimalSeparator, System.Globalization.NumberFormatInfo.PercentGroupSeparator, System.Globalization.NumberFormatInfo.PercentGroupSizes, System.Globalization.NumberFormatInfo.PercentNegativePattern, System.Globalization.NumberFormatInfo.PercentPositivePattern, System.Globalization.NumberFormatInfo.PercentSymbol, System.NumberFormatter.ResetCharBuf(), and System.NumberFormatter.RoundDecimal().
Referenced by System.NumberFormatter.IntegerToString(), and System.NumberFormatter.NumberToString().