Terraria Decompiled: System.NumberFormatter.FormatGeneral
FormatGeneral()
string System.NumberFormatter.FormatGeneral (int precision, NumberFormatInfo nfi) inline private
Definition at line 1282 of file NumberFormatter.cs.
        {
            bool flag;
            if (precision == -1)
            {
                flag = this.IsFloatingSource;
                precision = this._defPrecision;
            }
            else
            {
                flag = true;
                if (precision == 0)
                {
                    precision = this._defPrecision;
                }
                this.RoundPos(precision);
            }
            int num = this._decPointPos;
            int digitsLen = this._digitsLen;
            int num2 = digitsLen - num;
            if ((num > precision || num <= -4) && flag)
            {
                return this.FormatExponential(digitsLen - 1, nfi, 2);
            }
            if (num2 < 0)
            {
                num2 = 0;
            }
            if (num < 0)
            {
                num = 0;
            }
            this.ResetCharBuf(num2 + num + 3);
            if (!this._positive)
            {
                this.Append(nfi.NegativeSign);
            }
            if (num == 0)
            {
                this.Append('0');
            }
            else
            {
                this.AppendDigits(digitsLen - num, digitsLen);
            }
            if (num2 > 0)
            {
                this.Append(nfi.NumberDecimalSeparator);
                this.AppendDigits(0, num2);
            }
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._decPointPos, System.NumberFormatter._defPrecision, System.NumberFormatter._digitsLen, System.NumberFormatter._ind, System.NumberFormatter._positive, System.NumberFormatter.Append(), System.NumberFormatter.AppendDigits(), System.NumberFormatter.FormatExponential(), System.NumberFormatter.IsFloatingSource, System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.NumberDecimalSeparator, System.NumberFormatter.ResetCharBuf(), and System.NumberFormatter.RoundPos().
Referenced by System.NumberFormatter.FormatRoundtrip(), System.NumberFormatter.FormatRoundtrip(), System.NumberFormatter.IntegerToString(), and System.NumberFormatter.NumberToString().