Terraria Decompiled: System.NumberFormatter.AppendDigits
AppendDigits() [1/2]
void System.NumberFormatter.AppendDigits (int start, int end) inline private
Definition at line 1839 of file NumberFormatter.cs.
        {
            if (start >= end)
            {
                return;
            }
            int num = this._ind + (end - start);
            if (num > this._cbuf.Length)
            {
                this.Resize(num + 10);
            }
            this._ind = num;
            end += this._offset;
            start += this._offset;
            int num2 = start + 8 - (start & 7);
            for (;;)
            {
                uint num3;
                if (num2 == 8)
                {
                    num3 = this._val1;
                }
                else if (num2 == 16)
                {
                    num3 = this._val2;
                }
                else if (num2 == 24)
                {
                    num3 = this._val3;
                }
                else if (num2 == 32)
                {
                    num3 = this._val4;
                }
                else
                {
                    num3 = 0U;
                }
                num3 >>= (start & 7) << 2;
                if (num2 > end)
                {
                    num2 = end;
                }
                this._cbuf[--num] = (char)(48U | (num3 & 15U));
                switch (num2 - start)
                {
                case 1:
                    goto IL_017F;
                case 2:
                    goto IL_0167;
                case 3:
                    goto IL_014F;
                case 4:
                    goto IL_0137;
                case 5:
                    goto IL_011F;
                case 6:
                    goto IL_0107;
                case 7:
                    goto IL_00EF;
                case 8:
                    this._cbuf[--num] = (char)(48U | ((num3 >>= 4) & 15U));
                    goto IL_00EF;
                }
                IL_0184:
                start = num2;
                num2 += 8;
                continue;
                IL_017F:
                if (num2 == end)
                {
                    break;
                }
                goto IL_0184;
                IL_0167:
                this._cbuf[--num] = (char)(48U | ((num3 >> 4) & 15U));
                goto IL_017F;
                IL_014F:
                this._cbuf[--num] = (char)(48U | ((num3 >>= 4) & 15U));
                goto IL_0167;
                IL_0137:
                this._cbuf[--num] = (char)(48U | ((num3 >>= 4) & 15U));
                goto IL_014F;
                IL_011F:
                this._cbuf[--num] = (char)(48U | ((num3 >>= 4) & 15U));
                goto IL_0137;
                IL_0107:
                this._cbuf[--num] = (char)(48U | ((num3 >>= 4) & 15U));
                goto IL_011F;
                IL_00EF:
                this._cbuf[--num] = (char)(48U | ((num3 >>= 4) & 15U));
                goto IL_0107;
            }
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._offset, System.NumberFormatter._val1, System.NumberFormatter._val2, System.NumberFormatter._val3, System.NumberFormatter._val4, System.NumberFormatter.Resize(), System.start, and System.U.
Referenced by System.NumberFormatter.AppendDecimalString(), System.NumberFormatter.AppendDecimalString(), System.NumberFormatter.AppendIntegerString(), System.NumberFormatter.AppendIntegerString(), System.NumberFormatter.AppendIntegerStringWithGroupSeparator(), System.NumberFormatter.FormatDecimal(), System.NumberFormatter.FormatExponential(), and System.NumberFormatter.FormatGeneral().