Terraria Decompiled: System.NumberFormatter.FormatNumber
FormatNumber()
string System.NumberFormatter.FormatNumber (int precision, NumberFormatInfo nfi) inline private
Definition at line 1336 of file NumberFormatter.cs.
        {
            precision = ((precision >= 0) ? precision : nfi.NumberDecimalDigits);
            this.ResetCharBuf(this.IntegerDigits * 3 + precision);
            this.RoundDecimal(precision);
            if (!this._positive)
            {
                switch (nfi.NumberNegativePattern)
                {
                case 0:
                    this.Append('(');
                    break;
                case 1:
                    this.Append(nfi.NegativeSign);
                    break;
                case 2:
                    this.Append(nfi.NegativeSign);
                    this.Append(' ');
                    break;
                }
            }
            this.AppendIntegerStringWithGroupSeparator(nfi.NumberGroupSizes, nfi.NumberGroupSeparator);
            if (precision > 0)
            {
                this.Append(nfi.NumberDecimalSeparator);
                this.AppendDecimalString(precision);
            }
            if (!this._positive)
            {
                switch (nfi.NumberNegativePattern)
                {
                case 0:
                    this.Append(')');
                    break;
                case 3:
                    this.Append(nfi.NegativeSign);
                    break;
                case 4:
                    this.Append(' ');
                    this.Append(nfi.NegativeSign);
                    break;
                }
            }
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._ind, System.NumberFormatter._positive, System.NumberFormatter.Append(), System.NumberFormatter.AppendDecimalString(), System.NumberFormatter.AppendIntegerStringWithGroupSeparator(), System.NumberFormatter.IntegerDigits, System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.NumberDecimalDigits, System.Globalization.NumberFormatInfo.NumberDecimalSeparator, System.Globalization.NumberFormatInfo.NumberGroupSeparator, System.Globalization.NumberFormatInfo.NumberGroupSizes, System.Globalization.NumberFormatInfo.NumberNegativePattern, System.NumberFormatter.ResetCharBuf(), and System.NumberFormatter.RoundDecimal().
Referenced by System.NumberFormatter.IntegerToString(), and System.NumberFormatter.NumberToString().