Terraria Decompiled: System.NumberFormatter.AppendIntegerStringWithGroupSeparator
AppendIntegerStringWithGroupSeparator()
void System.NumberFormatter.AppendIntegerStringWithGroupSeparator (int[] groups, string groupSeparator) inline private
Definition at line 1675 of file NumberFormatter.cs.
        {
            if (this.IsZeroInteger)
            {
                this.Append('0');
                return;
            }
            int num = 0;
            int num2 = 0;
            for (int i = 0; i < groups.Length; i++)
            {
                num += groups[i];
                if (num > this._decPointPos)
                {
                    break;
                }
                num2 = i;
            }
            if (groups.Length != 0 && num > 0)
            {
                int num3 = groups[num2];
                int num4 = ((this._decPointPos > num) ? (this._decPointPos - num) : 0);
                if (num3 == 0)
                {
                    while (num2 >= 0 && groups[num2] == 0)
                    {
                        num2--;
                    }
                    num3 = ((num4 > 0) ? num4 : groups[num2]);
                }
                int num5;
                if (num4 == 0)
                {
                    num5 = num3;
                }
                else
                {
                    num2 += num4 / num3;
                    num5 = num4 % num3;
                    if (num5 == 0)
                    {
                        num5 = num3;
                    }
                    else
                    {
                        num2++;
                    }
                }
                if (num >= this._decPointPos)
                {
                    int num6 = groups[0];
                    if (num > num6)
                    {
                        int num7 = -(num6 - this._decPointPos);
                        int num8;
                        if (num7 < num6)
{
                            num5 = num7;
                        }
                        else if (num6 > 0 && (num8 = this._decPointPos % num6) > 0)
{
                            num5 = num8;
                        }
                    }
                }
                int num9 = 0;
                while (this._decPointPos - num9 > num5 && num5 != 0)
                {
                    this.AppendDigits(this._digitsLen - num9 - num5, this._digitsLen - num9);
                    num9 += num5;
                    this.Append(groupSeparator);
                    if (--num2 < groups.Length && num2 >= 0)
                    {
                        num3 = groups[num2];
                    }
                    num5 = num3;
                }
                this.AppendDigits(this._digitsLen - this._decPointPos, this._digitsLen - num9);
                return;
            }
            this.AppendDigits(this._digitsLen - this._decPointPos, this._digitsLen);
        }
References System.NumberFormatter._decPointPos, System.NumberFormatter._digitsLen, System.NumberFormatter.Append(), System.NumberFormatter.AppendDigits(), and System.NumberFormatter.IsZeroInteger.
Referenced by System.NumberFormatter.FormatCurrency(), System.NumberFormatter.FormatNumber(), and System.NumberFormatter.FormatPercent().