Terraria Decompiled: System.NumberFormatter.NumberToString
NumberToString() [6/8]
string System.NumberFormatter.NumberToString (string format, NumberFormatInfo nfi) inline private
Definition at line 1003 of file NumberFormatter.cs.
        {
            char specifier = this._specifier;
            if (specifier <= 'N')
            {
                switch (specifier)
                {
                case 'C':
                    return this.FormatCurrency(this._precision, nfi);
                case 'D':
                    break;
                case 'E':
                    return this.FormatExponential(this._precision, nfi);
                case 'F':
                    return this.FormatFixedPoint(this._precision, nfi);
                case 'G':
                    return this.FormatGeneral(this._precision, nfi);
                default:
                    if (specifier == 'N')
                    {
                        return this.FormatNumber(this._precision, nfi);
                    }
                    break;
                }
            }
            else
            {
                if (specifier == 'P')
                {
                    return this.FormatPercent(this._precision, nfi);
                }
                if (specifier != 'X')
                {
                }
            }
            if (this._isCustomFormat)
            {
                return this.FormatCustom(format, nfi);
            }
            throw new FormatException("The specified format '" + format + "' is invalid");
        }
References System.NumberFormatter._isCustomFormat, System.NumberFormatter._precision, System.NumberFormatter._specifier, System.format, System.NumberFormatter.FormatCurrency(), System.NumberFormatter.FormatCustom(), System.NumberFormatter.FormatExponential(), System.NumberFormatter.FormatFixedPoint(), System.NumberFormatter.FormatGeneral(), System.NumberFormatter.FormatNumber(), and System.NumberFormatter.FormatPercent().