Terraria Decompiled: System.NumberFormatter.CountTrailingZeros
CountTrailingZeros() [1/2]
int System.NumberFormatter.CountTrailingZeros () inline private
Definition at line 744 of file NumberFormatter.cs.
        {
            if (this._val1 != 0U)
            {
                return NumberFormatter.CountTrailingZeros(this._val1);
            }
            if (this._val2 != 0U)
            {
                return NumberFormatter.CountTrailingZeros(this._val2) + 8;
            }
            if (this._val3 != 0U)
            {
                return NumberFormatter.CountTrailingZeros(this._val3) + 16;
            }
            if (this._val4 != 0U)
            {
                return NumberFormatter.CountTrailingZeros(this._val4) + 24;
            }
            return this._digitsLen;
        }
References System.NumberFormatter._digitsLen, System.NumberFormatter._val1, System.NumberFormatter._val2, System.NumberFormatter._val3, System.NumberFormatter._val4, System.NumberFormatter.CountTrailingZeros(), and System.U.
Referenced by System.NumberFormatter.CountTrailingZeros(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), and System.NumberFormatter.RemoveTrailingZeros().