Terraria Decompiled: System.NumberFormatter.Init
Init() [3/7]
unsafe void System.NumberFormatter.Init (string format, double value, int defPrecision) inline private
Definition at line 366 of file NumberFormatter.cs.
        {
            this.Init(format);
            this._defPrecision = defPrecision;
            long num = BitConverter.DoubleToInt64Bits(value);
            this._positive = num >= 0L;
            num &= long.MaxValue;
            if (num == 0L)
            {
                this._decPointPos = 1;
                this._digitsLen = 0;
                this._positive = true;
                return;
            }
            int num2 = (int)(num >> 52);
            long num3 = num & 4503599627370495L;
            if (num2 == 2047)
            {
                this._NaN = num3 != 0L;
                this._infinity = num3 == 0L;
                return;
            }
            int num4 = 0;
            if (num2 == 0)
            {
                num2 = 1;
                int num5 = NumberFormatter.ScaleOrder(num3);
                if (num5 < 15)
                {
                    num4 = num5 - 15;
                    num3 *= NumberFormatter.GetTenPowerOf(-num4);
                }
            }
            else
            {
                num3 = (num3 + 4503599627370495L + 1L) * 10L;
                num4 = -1;
            }
            ulong num6 = (ulong)((uint)num3);
            ulong num7 = (ulong)num3 >> 32;
            ulong num8 = NumberFormatter.MantissaBitsTable[num2];
            ulong num9 = num8 >> 32;
            num8 = (ulong)((uint)num8);
            ulong num10 = num7 * num8 + num6 * num9 + (num6 * num8 >> 32);
            long num11 = (long)(num7 * num9 + (num10 >> 32));
            while (num11 < 10000000000000000L)
            {
                num10 = (num10 & (ulong)(-1)) * 10UL;
                num11 = num11 * 10L + (long)(num10 >> 32);
                num4--;
            }
            if ((num10 & (ulong)(-2147483648)) != 0UL)
            {
                num11 += 1L;
            }
            int num12 = 17;
            this._decPointPos = NumberFormatter.TensExponentTable[num2] + num4 + num12;
            int num13 = this.InitialFloatingPrecision();
            if (num12 > num13)
            {
                long tenPowerOf = NumberFormatter.GetTenPowerOf(num12 - num13);
                num11 = (num11 + (tenPowerOf >> 1)) / tenPowerOf;
                num12 = num13;
            }
            if (num11 >= NumberFormatter.GetTenPowerOf(num12))
            {
                num12++;
                this._decPointPos++;
            }
            this.InitDecHexDigits((ulong)num11);
            this._offset = this.CountTrailingZeros();
            this._digitsLen = num12 - this._offset;
        }
References System.NumberFormatter._decPointPos, System.NumberFormatter._offset, System.NumberFormatter.CountTrailingZeros(), System.BitConverter.DoubleToInt64Bits(), System.NumberFormatter.GetTenPowerOf(), System.NumberFormatter.Init(), System.NumberFormatter.InitDecHexDigits(), System.NumberFormatter.InitialFloatingPrecision(), int, System.L, long, System.NumberFormatter.MantissaBitsTable, System.NumberFormatter.ScaleOrder(), System.NumberFormatter.TensExponentTable, and System.value.