Terraria Decompiled: System.NumberFormatter.FormatFixedPoint
FormatFixedPoint()
string System.NumberFormatter.FormatFixedPoint (int precision, NumberFormatInfo nfi) inline private
Definition at line 1233 of file NumberFormatter.cs.
        {
            if (precision == -1)
            {
                precision = nfi.NumberDecimalDigits;
            }
            this.RoundDecimal(precision);
            this.ResetCharBuf(this.IntegerDigits + precision + 2);
            if (!this._positive)
            {
                this.Append(nfi.NegativeSign);
            }
            this.AppendIntegerString(this.IntegerDigits);
            if (precision > 0)
            {
                this.Append(nfi.NumberDecimalSeparator);
                this.AppendDecimalString(precision);
            }
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._ind, System.NumberFormatter._positive, System.NumberFormatter.Append(), System.NumberFormatter.AppendDecimalString(), System.NumberFormatter.AppendIntegerString(), System.NumberFormatter.IntegerDigits, System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.NumberDecimalDigits, System.Globalization.NumberFormatInfo.NumberDecimalSeparator, System.NumberFormatter.ResetCharBuf(), and System.NumberFormatter.RoundDecimal().
Referenced by System.NumberFormatter.IntegerToString(), and System.NumberFormatter.NumberToString().