Terraria Decompiled: System.NumberFormatter.NumberToString
NumberToString() [1/8]
static string System.NumberFormatter.NumberToString (string format, decimal value, IFormatProvider fp) inline static
Definition at line 944 of file NumberFormatter.cs.
        {
            NumberFormatter instance = NumberFormatter.GetInstance(fp);
            instance.Init(format, value);
            string text = instance.NumberToString(format, instance.GetNumberFormatInstance(fp));
            instance.Release();
            return text;
        }
References System.format, System.NumberFormatter.GetInstance(), System.NumberFormatter.GetNumberFormatInstance(), System.NumberFormatter.Init(), System.NumberFormatter.NumberToString(), System.NumberFormatter.Release(), System.text, and System.value.