Terraria Decompiled: System.NumberFormatter.FormatCustom
FormatCustom()
string System.NumberFormatter.FormatCustom (string format, NumberFormatInfo nfi) inline private
Definition at line 1487 of file NumberFormatter.cs.
        {
            bool positive = this._positive;
            int num = 0;
            int num2 = 0;
            NumberFormatter.CustomInfo.GetActiveSection(format, ref positive, this.IsZero, ref num, ref num2);
            if (num2 != 0)
            {
                this._positive = positive;
                NumberFormatter.CustomInfo customInfo = NumberFormatter.CustomInfo.Parse(format, num, num2, nfi);
                StringBuilder stringBuilder = new StringBuilder(customInfo.IntegerDigits * 2);
                StringBuilder stringBuilder2 = new StringBuilder(customInfo.DecimalDigits * 2);
                StringBuilder stringBuilder3 = (customInfo.UseExponent ? new StringBuilder(customInfo.ExponentDigits * 2) : null);
                int num3 = 0;
                if (customInfo.Percents > 0)
                {
                    this.Multiply10(2 * customInfo.Percents);
                }
                if (customInfo.Permilles > 0)
                {
                    this.Multiply10(3 * customInfo.Permilles);
                }
                if (customInfo.DividePlaces > 0)
                {
                    this.Divide10(customInfo.DividePlaces);
                }
                bool flag = true;
                if (customInfo.UseExponent && (customInfo.DecimalDigits > 0 || customInfo.IntegerDigits > 0))
                {
                    if (!this.IsZero)
                    {
                        this.RoundPos(customInfo.DecimalDigits + customInfo.IntegerDigits);
                        num3 -= this._decPointPos - customInfo.IntegerDigits;
                        this._decPointPos = customInfo.IntegerDigits;
                    }
                    flag = num3 <= 0;
                    NumberFormatter.AppendNonNegativeNumber(stringBuilder3, (num3 < 0) ? (-num3) : num3);
                }
                else
                {
                    this.RoundDecimal(customInfo.DecimalDigits);
                }
                if (customInfo.IntegerDigits != 0 || !this.IsZeroInteger)
                {
                    this.AppendIntegerString(this.IntegerDigits, stringBuilder);
                }
                this.AppendDecimalString(this.DecimalDigits, stringBuilder2);
                if (customInfo.UseExponent)
                {
                    if (customInfo.DecimalDigits <= 0 && customInfo.IntegerDigits <= 0)
                    {
                        this._positive = true;
                    }
                    if (stringBuilder.Length < customInfo.IntegerDigits)
                    {
                        stringBuilder.Insert(0, "0", customInfo.IntegerDigits - stringBuilder.Length);
                    }
                    while (stringBuilder3.Length < customInfo.ExponentDigits - customInfo.ExponentTailSharpDigits)
                    {
                        stringBuilder3.Insert(0, '0');
                    }
                    if (flag && !customInfo.ExponentNegativeSignOnly)
                    {
                        stringBuilder3.Insert(0, nfi.PositiveSign);
                    }
                    else if (!flag)
                    {
                        stringBuilder3.Insert(0, nfi.NegativeSign);
                    }
                }
                else
                {
                    if (stringBuilder.Length < customInfo.IntegerDigits - customInfo.IntegerHeadSharpDigits)
                    {
                        stringBuilder.Insert(0, "0", customInfo.IntegerDigits - customInfo.IntegerHeadSharpDigits - stringBuilder.Length);
                    }
                    if (customInfo.IntegerDigits == customInfo.IntegerHeadSharpDigits && NumberFormatter.IsZeroOnly(stringBuilder))
                    {
                        stringBuilder.Remove(0, stringBuilder.Length);
                    }
                }
                NumberFormatter.ZeroTrimEnd(stringBuilder2, true);
                while (stringBuilder2.Length < customInfo.DecimalDigits - customInfo.DecimalTailSharpDigits)
                {
                    stringBuilder2.Append('0');
                }
                if (stringBuilder2.Length > customInfo.DecimalDigits)
                {
                    stringBuilder2.Remove(customInfo.DecimalDigits, stringBuilder2.Length - customInfo.DecimalDigits);
                }
                return customInfo.Format(format, num, num2, nfi, this._positive, stringBuilder, stringBuilder2, stringBuilder3);
            }
            if (!this._positive)
            {
                return nfi.NegativeSign;
            }
            return string.Empty;
        }
References System.NumberFormatter._positive, System.Text.StringBuilder.Append(), System.NumberFormatter.AppendDecimalString(), System.NumberFormatter.AppendIntegerString(), System.NumberFormatter.AppendNonNegativeNumber(), System.NumberFormatter.DecimalDigits, System.NumberFormatter.CustomInfo.DecimalDigits, System.NumberFormatter.CustomInfo.DecimalTailSharpDigits, System.NumberFormatter.Divide10(), System.NumberFormatter.CustomInfo.DividePlaces, System.NumberFormatter.CustomInfo.ExponentDigits, System.NumberFormatter.CustomInfo.ExponentNegativeSignOnly, System.NumberFormatter.CustomInfo.ExponentTailSharpDigits, System.format, System.NumberFormatter.CustomInfo.Format(), System.NumberFormatter.CustomInfo.GetActiveSection(), System.Text.StringBuilder.Insert(), System.NumberFormatter.IntegerDigits, System.NumberFormatter.CustomInfo.IntegerDigits, System.NumberFormatter.CustomInfo.IntegerHeadSharpDigits, System.NumberFormatter.IsZero, System.NumberFormatter.IsZeroOnly(), System.Text.StringBuilder.Length, System.NumberFormatter.Multiply10(), System.Globalization.NumberFormatInfo.NegativeSign, System.NumberFormatter.CustomInfo.Parse(), System.NumberFormatter.CustomInfo.Percents, System.NumberFormatter.CustomInfo.Permilles, System.Globalization.NumberFormatInfo.PositiveSign, System.Text.StringBuilder.Remove(), System.NumberFormatter.RoundDecimal(), System.NumberFormatter.RoundPos(), System.NumberFormatter.CustomInfo.UseExponent, and System.NumberFormatter.ZeroTrimEnd().
Referenced by System.NumberFormatter.IntegerToString(), and System.NumberFormatter.NumberToString().