Terraria Decompiled: System.NumberFormatter.InitDecHexDigits
InitDecHexDigits() [2/3]
void System.NumberFormatter.InitDecHexDigits (uint value) inline private
Definition at line 29 of file NumberFormatter.cs.
        {
            if (value >= 100000000U)
            {
                int num = (int)(value / 100000000U);
                value -= (uint)(100000000 * num);
                this._val2 = NumberFormatter.FastToDecHex(num);
            }
            this._val1 = NumberFormatter.ToDecHex((int)value);
        }
References System.NumberFormatter.FastToDecHex(), int, System.NumberFormatter.ToDecHex(), System.U, and System.value.
Referenced by System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), and System.NumberFormatter.InitDecHexDigits().