Terraria Decompiled: System.NumberFormatter.DecHexLen
DecHexLen() [1/2]
int System.NumberFormatter.DecHexLen () inline private
Definition at line 159 of file NumberFormatter.cs.
        {
            if (this._val4 != 0U)
            {
                return NumberFormatter.DecHexLen(this._val4) + 24;
            }
            if (this._val3 != 0U)
            {
                return NumberFormatter.DecHexLen(this._val3) + 16;
            }
            if (this._val2 != 0U)
            {
                return NumberFormatter.DecHexLen(this._val2) + 8;
            }
            if (this._val1 != 0U)
            {
                return NumberFormatter.DecHexLen(this._val1);
            }
            return 0;
        }
References System.NumberFormatter._val1, System.NumberFormatter._val2, System.NumberFormatter._val3, System.NumberFormatter._val4, System.NumberFormatter.DecHexLen(), and System.U.
Referenced by System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.InitHex(), and System.NumberFormatter.RoundBits().