Terraria Decompiled: System.NumberFormatter.IntegerToString
IntegerToString()
string System.NumberFormatter.IntegerToString (string format, IFormatProvider fp) inline private
Definition at line 954 of file NumberFormatter.cs.
        {
            NumberFormatInfo numberFormatInstance = this.GetNumberFormatInstance(fp);
            char specifier = this._specifier;
            if (specifier <= 'N')
            {
                switch (specifier)
                {
                case 'C':
                    return this.FormatCurrency(this._precision, numberFormatInstance);
                case 'D':
                    return this.FormatDecimal(this._precision, numberFormatInstance);
                case 'E':
                    return this.FormatExponential(this._precision, numberFormatInstance);
                case 'F':
                    return this.FormatFixedPoint(this._precision, numberFormatInstance);
                case 'G':
                    if (this._precision <= 0)
                    {
                        return this.FormatDecimal(-1, numberFormatInstance);
                    }
                    return this.FormatGeneral(this._precision, numberFormatInstance);
                default:
                    if (specifier == 'N')
                    {
                        return this.FormatNumber(this._precision, numberFormatInstance);
                    }
                    break;
                }
            }
            else
            {
                if (specifier == 'P')
                {
                    return this.FormatPercent(this._precision, numberFormatInstance);
                }
                if (specifier == 'X')
                {
                    return this.FormatHexadecimal(this._precision);
                }
            }
            if (this._isCustomFormat)
            {
                return this.FormatCustom(format, numberFormatInstance);
            }
            throw new FormatException("The specified format '" + format + "' is invalid");
        }
References System.NumberFormatter._isCustomFormat, System.NumberFormatter._precision, System.NumberFormatter._specifier, System.format, System.NumberFormatter.FormatCurrency(), System.NumberFormatter.FormatCustom(), System.NumberFormatter.FormatDecimal(), System.NumberFormatter.FormatExponential(), System.NumberFormatter.FormatFixedPoint(), System.NumberFormatter.FormatGeneral(), System.NumberFormatter.FormatHexadecimal(), System.NumberFormatter.FormatNumber(), System.NumberFormatter.FormatPercent(), and System.NumberFormatter.GetNumberFormatInstance().
Referenced by System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), and System.NumberFormatter.NumberToString().