Terraria Decompiled: System.NumberFormatter.AddOneToDecHex
AddOneToDecHex() [1/2]
void System.NumberFormatter.AddOneToDecHex () inline private
Definition at line 680 of file NumberFormatter.cs.
        {
            if (this._val1 != 2576980377U)
            {
                this._val1 = NumberFormatter.AddOneToDecHex(this._val1);
                return;
            }
            this._val1 = 0U;
            if (this._val2 != 2576980377U)
            {
                this._val2 = NumberFormatter.AddOneToDecHex(this._val2);
                return;
            }
            this._val2 = 0U;
            if (this._val3 == 2576980377U)
            {
                this._val3 = 0U;
                this._val4 = NumberFormatter.AddOneToDecHex(this._val4);
                return;
            }
            this._val3 = NumberFormatter.AddOneToDecHex(this._val3);
        }
References System.NumberFormatter._val1, System.NumberFormatter._val2, System.NumberFormatter._val3, System.NumberFormatter._val4, System.NumberFormatter.AddOneToDecHex(), and System.U.
Referenced by System.NumberFormatter.AddOneToDecHex(), and System.NumberFormatter.RoundBits().