Terraria Decompiled: System.NumberFormatter.FormatExponential
FormatExponential() [2/2]
string System.NumberFormatter.FormatExponential (int precision, NumberFormatInfo nfi, int expDigits) inline private
Definition at line 1465 of file NumberFormatter.cs.
        {
            int decPointPos = this._decPointPos;
            int digitsLen = this._digitsLen;
            int num = decPointPos - 1;
            this._decPointPos = 1;
            this.ResetCharBuf(precision + 8);
            if (!this._positive)
            {
                this.Append(nfi.NegativeSign);
            }
            this.AppendOneDigit(digitsLen - 1);
            if (precision > 0)
            {
                this.Append(nfi.NumberDecimalSeparator);
                this.AppendDigits(digitsLen - precision - 1, digitsLen - this._decPointPos);
            }
            this.AppendExponent(nfi, num, expDigits);
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._decPointPos, System.NumberFormatter._digitsLen, System.NumberFormatter._ind, System.NumberFormatter._positive, System.NumberFormatter.Append(), System.NumberFormatter.AppendDigits(), System.NumberFormatter.AppendExponent(), System.NumberFormatter.AppendOneDigit(), System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.NumberDecimalSeparator, and System.NumberFormatter.ResetCharBuf().