Terraria Decompiled: System.NumberFormatter.RoundBits
RoundBits()
bool System.NumberFormatter.RoundBits (int shift) inline private
Definition at line 623 of file NumberFormatter.cs.
        {
            if (shift <= 0)
            {
                return false;
            }
            if (shift > this._digitsLen)
            {
                this._digitsLen = 0;
                this._decPointPos = 1;
                this._val1 = (this._val2 = (this._val3 = (this._val4 = 0U)));
                this._positive = true;
                return false;
            }
            shift += this._offset;
            this._digitsLen += this._offset;
            while (shift > 8)
            {
                this._val1 = this._val2;
                this._val2 = this._val3;
                this._val3 = this._val4;
                this._val4 = 0U;
                this._digitsLen -= 8;
                shift -= 8;
            }
            shift = shift - 1 << 2;
            uint num = this._val1 >> shift;
            uint num2 = num & 15U;
            this._val1 = (num ^ num2) << shift;
            bool flag = false;
            if (num2 >= 5U)
            {
                this._val1 |= 2576980377U >> 28 - shift;
                this.AddOneToDecHex();
                int num3 = this.DecHexLen();
                flag = num3 != this._digitsLen;
                this._decPointPos = this._decPointPos + num3 - this._digitsLen;
                this._digitsLen = num3;
            }
            this.RemoveTrailingZeros();
            return flag;
        }
References System.NumberFormatter._digitsLen, System.NumberFormatter._offset, System.NumberFormatter._val2, System.NumberFormatter._val3, System.NumberFormatter._val4, System.NumberFormatter.AddOneToDecHex(), System.NumberFormatter.DecHexLen(), System.NumberFormatter.RemoveTrailingZeros(), and System.U.
Referenced by System.NumberFormatter.RoundDecimal(), and System.NumberFormatter.RoundPos().