Terraria Decompiled: System.NumberFormatter.Init
Init() [2/7]
void System.NumberFormatter.Init (string format, decimal value) inline private
Definition at line 441 of file NumberFormatter.cs.
        {
            this.Init(format);
            this._defPrecision = 100;
            int[] bits = decimal.GetBits(value);
            int num = (bits[3] & 2031616) >> 16;
            this._positive = bits[3] >= 0;
            if (bits[0] == 0 && bits[1] == 0 && bits[2] == 0)
            {
                this._decPointPos = -num;
                this._positive = true;
                this._digitsLen = 0;
                return;
            }
            this.InitDecHexDigits((uint)bits[2], (ulong)(((long)bits[1] << 32) | (long)((ulong)bits[0])));
            this._digitsLen = this.DecHexLen();
            this._decPointPos = this._digitsLen - num;
            if (this._precision != -1 || this._specifier != 'G')
            {
                this._offset = this.CountTrailingZeros();
                this._digitsLen -= this._offset;
            }
        }
References System.NumberFormatter._offset, System.NumberFormatter._precision, System.NumberFormatter._specifier, System.NumberFormatter.CountTrailingZeros(), System.NumberFormatter.DecHexLen(), System.NumberFormatter.Init(), System.NumberFormatter.InitDecHexDigits(), and System.value.