Terraria Decompiled: System.NumberFormatter.FormatHexadecimal
FormatHexadecimal()
unsafe string System.NumberFormatter.FormatHexadecimal (int precision) inline private
Definition at line 1217 of file NumberFormatter.cs.
        {
            int i = Math.Max(precision, this._decPointPos);
            char* ptr = (this._specifierIsUpper ? NumberFormatter.DigitUpperTable : NumberFormatter.DigitLowerTable);
            this.ResetCharBuf(i);
            this._ind = i;
            ulong num = (ulong)this._val1 | ((ulong)this._val2 << 32);
            while (i > 0)
            {
                this._cbuf[--i] = ptr[(num & 15UL) * 2UL / 2UL];
                num >>= 4;
            }
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._decPointPos, System.NumberFormatter._ind, System.NumberFormatter._val1, System.NumberFormatter.DigitLowerTable, System.Math.Max(), and System.NumberFormatter.ResetCharBuf().
Referenced by System.NumberFormatter.IntegerToString().