Terraria Decompiled: System.NumberFormatter.Init
Init() [7/7]
void System.NumberFormatter.Init (string format, ulong value) inline private
Definition at line 351 of file NumberFormatter.cs.
        {
            this.Init(format);
            this._defPrecision = 20;
            this._positive = true;
            if (value == 0UL || this._specifier == 'X')
            {
                this.InitHex(value);
                return;
            }
            this.InitDecHexDigits(value);
            this._decPointPos = (this._digitsLen = this.DecHexLen());
        }
References System.NumberFormatter._specifier, System.NumberFormatter.DecHexLen(), System.NumberFormatter.Init(), System.NumberFormatter.InitDecHexDigits(), System.NumberFormatter.InitHex(), and System.value.