Terraria Decompiled: System.NumberFormatter.GetInstance
GetInstance()
static NumberFormatter System.NumberFormatter.GetInstance (IFormatProvider fp) inline static private
Definition at line 806 of file NumberFormatter.cs.
        {
            if (fp != null)
            {
                if (NumberFormatter.userFormatProvider == null)
                {
                    Interlocked.CompareExchange<NumberFormatter>(ref NumberFormatter.userFormatProvider, new NumberFormatter(null), null);
                }
                return NumberFormatter.userFormatProvider;
            }
            NumberFormatter numberFormatter = NumberFormatter.threadNumberFormatter;
            NumberFormatter.threadNumberFormatter = null;
            if (numberFormatter == null)
            {
                return new NumberFormatter(Thread.CurrentThread);
            }
            numberFormatter.CurrentCulture = Thread.CurrentThread.CurrentCulture;
            return numberFormatter;
        }
References System.Threading.Interlocked.CompareExchange(), System.Threading.Thread.CurrentCulture, System.Threading.Thread.CurrentThread, System.NumberFormatter.NumberFormatter(), System.NumberFormatter.threadNumberFormatter, and System.NumberFormatter.userFormatProvider.
Referenced by System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), and System.NumberFormatter.NumberToString().