Terraria Decompiled: System.NumberFormatter.Init
Init() [6/7]
void System.NumberFormatter.Init (string format, uint value, int defPrecision) inline private
Definition at line 317 of file NumberFormatter.cs.
        {
            this.Init(format);
            this._defPrecision = defPrecision;
            this._positive = true;
            if (value == 0U || this._specifier == 'X')
            {
                this.InitHex((ulong)value);
                return;
            }
            this.InitDecHexDigits(value);
            this._decPointPos = (this._digitsLen = this.DecHexLen());
        }
References System.NumberFormatter._specifier, System.NumberFormatter.DecHexLen(), System.NumberFormatter.Init(), System.NumberFormatter.InitDecHexDigits(), System.NumberFormatter.InitHex(), System.U, and System.value.