Terraria Decompiled: System.NumberFormatter.AppendExponent
AppendExponent()
void System.NumberFormatter.AppendExponent (NumberFormatInfo nfi, int exponent, int minDigits) inline private
Definition at line 1759 of file NumberFormatter.cs.
        {
            if (this._specifierIsUpper || this._specifier == 'R')
            {
                this.Append('E');
            }
            else
            {
                this.Append('e');
            }
            if (exponent >= 0)
            {
                this.Append(nfi.PositiveSign);
            }
            else
            {
                this.Append(nfi.NegativeSign);
                exponent = -exponent;
            }
            if (exponent == 0)
            {
                this.Append('0', minDigits);
                return;
            }
            if (exponent < 10)
            {
                this.Append('0', minDigits - 1);
                this.Append((char)(48 | exponent));
                return;
            }
            uint num = NumberFormatter.FastToDecHex(exponent);
            if (exponent >= 100 || minDigits == 3)
            {
                this.Append((char)(48U | (num >> 8)));
            }
            this.Append((char)(48U | ((num >> 4) & 15U)));
            this.Append((char)(48U | (num & 15U)));
        }
References System.NumberFormatter._specifier, System.NumberFormatter._specifierIsUpper, System.NumberFormatter.Append(), System.NumberFormatter.FastToDecHex(), System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.PositiveSign, and System.U.
Referenced by System.NumberFormatter.FormatExponential().