Terraria Decompiled: System.NumberFormatter.AppendNonNegativeNumber
AppendNonNegativeNumber()
static void System.NumberFormatter.AppendNonNegativeNumber (StringBuilder sb, int v) inline static private
Definition at line 1616 of file NumberFormatter.cs.
        {
            if (v < 0)
            {
                throw new ArgumentException();
            }
            int num = NumberFormatter.ScaleOrder((long)v) - 1;
            do
            {
                int num2 = v / (int)NumberFormatter.GetTenPowerOf(num);
                sb.Append((char)(48 | num2));
                v -= (int)NumberFormatter.GetTenPowerOf(num--) * num2;
            }
            while (num >= 0);
        }
References System.Text.StringBuilder.Append(), System.NumberFormatter.GetTenPowerOf(), int, and System.NumberFormatter.ScaleOrder().
Referenced by System.NumberFormatter.FormatCustom().