Terraria Decompiled: System.NumberFormatter.Init
Init() [1/7]
void System.NumberFormatter.Init (string format) inline private
Definition at line 243 of file NumberFormatter.cs.
        {
            this._val1 = (this._val2 = (this._val3 = (this._val4 = 0U)));
            this._offset = 0;
            this._NaN = (this._infinity = false);
            this._isCustomFormat = false;
            this._specifierIsUpper = true;
            this._precision = -1;
            if (format == null || format.Length == 0)
            {
                this._specifier = 'G';
                return;
            }
            char c = format[0];
            if (c >= 'a' && c <= 'z')
            {
                c = c - 'a' + 'A';
                this._specifierIsUpper = false;
            }
            else if (c < 'A' || c > 'Z')
            {
                this._isCustomFormat = true;
                this._specifier = '0';
                return;
            }
            this._specifier = c;
            if (format.Length > 1)
            {
                this._precision = NumberFormatter.ParsePrecision(format);
                if (this._precision == -2)
                {
                    this._isCustomFormat = true;
                    this._specifier = '0';
                    this._precision = -1;
                }
            }
        }
References System.NumberFormatter._precision, System.format, System.NumberFormatter.ParsePrecision(), and System.U.
Referenced by System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.Init(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), System.NumberFormatter.NumberToString(), and System.NumberFormatter.NumberToString().