Terraria Decompiled: System.NumberFormatter.FormatDecimal
FormatDecimal()
string System.NumberFormatter.FormatDecimal (int precision, NumberFormatInfo nfi) inline private
Definition at line 1197 of file NumberFormatter.cs.
        {
            if (precision < this._digitsLen)
            {
                precision = this._digitsLen;
            }
            if (precision == 0)
            {
                return "0";
            }
            this.ResetCharBuf(precision + 1);
            if (!this._positive)
            {
                this.Append(nfi.NegativeSign);
            }
            this.AppendDigits(0, precision);
            return new string(this._cbuf, 0, this._ind);
        }
References System.NumberFormatter._cbuf, System.NumberFormatter._digitsLen, System.NumberFormatter._ind, System.NumberFormatter._positive, System.NumberFormatter.Append(), System.NumberFormatter.AppendDigits(), System.Globalization.NumberFormatInfo.NegativeSign, and System.NumberFormatter.ResetCharBuf().
Referenced by System.NumberFormatter.IntegerToString().