Terraria Decompiled: System.NumberFormatter.NumberToString
NumberToString() [2/8]
static string System.NumberFormatter.NumberToString (string format, double value, IFormatProvider fp) inline static
Definition at line 910 of file NumberFormatter.cs.
        {
            NumberFormatter instance = NumberFormatter.GetInstance(fp);
            instance.Init(format, value, 15);
            NumberFormatInfo numberFormatInstance = instance.GetNumberFormatInstance(fp);
            string text;
            if (instance._NaN)
            {
                text = numberFormatInstance.NaNSymbol;
            }
            else if (instance._infinity)
            {
                if (instance._positive)
                {
                    text = numberFormatInstance.PositiveInfinitySymbol;
                }
                else
                {
                    text = numberFormatInstance.NegativeInfinitySymbol;
                }
            }
            else if (instance._specifier == 'R')
            {
                text = instance.FormatRoundtrip(value, numberFormatInstance);
            }
            else
            {
                text = instance.NumberToString(format, numberFormatInstance);
            }
            instance.Release();
            return text;
        }
References System.NumberFormatter._infinity, System.NumberFormatter._NaN, System.NumberFormatter._positive, System.NumberFormatter._specifier, System.format, System.NumberFormatter.FormatRoundtrip(), System.NumberFormatter.GetInstance(), System.NumberFormatter.GetNumberFormatInstance(), System.NumberFormatter.Init(), System.Globalization.NumberFormatInfo.NaNSymbol, System.Globalization.NumberFormatInfo.NegativeInfinitySymbol, System.NumberFormatter.NumberToString(), System.Globalization.NumberFormatInfo.PositiveInfinitySymbol, System.NumberFormatter.Release(), System.text, and System.value.