Terraria Decompiled: rail.IRailRoomImpl.AsyncSetMemberMetadata
AsyncSetMemberMetadata()
virtual RailResult rail.IRailRoomImpl.AsyncSetMemberMetadata (RailID member_id, List< RailKeyValue > key_values, string user_data) inline virtual
Implements rail.IRailRoom.
Definition at line 287 of file IRailRoomImpl.cs.
        {
            IntPtr intPtr = ((member_id == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailID__SWIG_0());
            if (member_id != null)
            {
                RailConverter.Csharp2Cpp(member_id, intPtr);
            }
            IntPtr intPtr2 = ((key_values == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailKeyValue__SWIG_0());
            if (key_values != null)
            {
                RailConverter.Csharp2Cpp(key_values, intPtr2);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailRoom_AsyncSetMemberMetadata(this.swigCPtr_, intPtr, intPtr2, user_data);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailID(intPtr);
                RAIL_API_PINVOKE.delete_RailArrayRailKeyValue(intPtr2);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailKeyValue(), rail.RAIL_API_PINVOKE.delete_RailID(), rail.RAIL_API_PINVOKE.IRailRoom_AsyncSetMemberMetadata(), rail.RAIL_API_PINVOKE.new_RailArrayRailKeyValue__SWIG_0(), rail.RAIL_API_PINVOKE.new_RailID__SWIG_0(), and System.IntPtr.Zero.