Terraria Decompiled: System.Collections.Generic.LargeArrayBuilder.AddRange
AddRange()
void System.Collections.Generic.LargeArrayBuilder< T >.AddRange (IEnumerable< T > items) inline
Definition at line 64 of file LargeArrayBuilder.cs.
        {
            using (IEnumerator<T> enumerator = items.GetEnumerator())
            {
                T[] current = this._current;
                int num = this._index;
                while (enumerator.MoveNext())
                {
                    T t = enumerator.Current;
                    if (num >= current.Length)
                    {
                        this.AddWithBufferAllocation(t, ref current, ref num);
                    }
                    else
                    {
                        current[num] = t;
                    }
                    num++;
                }
                this._count += num - this._index;
                this._index = num;
            }
        }
References System.Collections.Generic.LargeArrayBuilder< T >._current, System.Collections.Generic.LargeArrayBuilder< T >._index, System.Collections.Generic.LargeArrayBuilder< T >.AddWithBufferAllocation(), System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), and System.Collections.IEnumerator.MoveNext().
Referenced by System.Collections.Generic.EnumerableHelpers.ToArray< T >().