Terraria Decompiled: System.Collections.Generic.LargeArrayBuilder.AllocateBuffer
AllocateBuffer()
void System.Collections.Generic.LargeArrayBuilder< T >.AllocateBuffer () inline private
Definition at line 181 of file LargeArrayBuilder.cs.
        {
            if (this._count < 8)
            {
                int num = Math.Min((this._count == 0) ? 4 : (this._count * 2), this._maxCapacity);
                this._current = new T[num];
                Array.Copy(this._first, 0, this._current, 0, this._count);
                this._first = this._current;
                return;
            }
            int num2;
            if (this._count == 8)
            {
                num2 = 8;
            }
            else
            {
                this._buffers.Add(this._current);
                num2 = Math.Min(this._count, this._maxCapacity - this._count);
            }
            this._current = new T[num2];
            this._index = 0;
        }
References System.Collections.Generic.LargeArrayBuilder< T >._buffers, System.Collections.Generic.LargeArrayBuilder< T >._count, System.Collections.Generic.LargeArrayBuilder< T >._current, System.Collections.Generic.LargeArrayBuilder< T >._first, System.Collections.Generic.LargeArrayBuilder< T >._maxCapacity, System.Collections.Generic.ArrayBuilder< T >.Add(), System.Array.Copy(), and System.Math.Min().
Referenced by System.Collections.Generic.LargeArrayBuilder< T >.AddWithBufferAllocation(), and System.Collections.Generic.LargeArrayBuilder< T >.AddWithBufferAllocation().