Terraria Decompiled: System.Collections.Generic.LargeArrayBuilder.CopyTo
CopyTo() [1/2]
CopyPosition System.Collections.Generic.LargeArrayBuilder< T >.CopyTo (CopyPosition position, T[] array, int arrayIndex, int count) inline
Definition at line 116 of file LargeArrayBuilder.cs.
        {
            LargeArrayBuilder<T>.<>c__DisplayClass17_0 CS$<>8__locals1;
            CS$<>8__locals1.count = count;
            CS$<>8__locals1.array = array;
            CS$<>8__locals1.arrayIndex = arrayIndex;
            int num = position.Row;
            int column = position.Column;
            T[] array2 = this.GetBuffer(num);
            int num2 = LargeArrayBuilder<T>.<CopyTo>g__CopyToCore|17_0(array2, column, ref CS$<>8__locals1);
            if (CS$<>8__locals1.count == 0)
            {
                return new CopyPosition(num, column + num2).Normalize(array2.Length);
            }
            do
            {
                array2 = this.GetBuffer(++num);
                num2 = LargeArrayBuilder<T>.<CopyTo>g__CopyToCore|17_0(array2, 0, ref CS$<>8__locals1);
            }
            while (CS$<>8__locals1.count > 0);
            return new CopyPosition(num, num2).Normalize(array2.Length);
        }
References System.array, System.arrayIndex, System.Collections.Generic.CopyPosition.Column, System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), System.count, System.Collections.Generic.LargeArrayBuilder< T >.g__CopyToCore(), System.Collections.Generic.LargeArrayBuilder< T >.GetBuffer(), System.Collections.Generic.CopyPosition.Normalize(), and System.Collections.Generic.CopyPosition.Row.