Terraria Decompiled: System.Collections.Generic.LargeArrayBuilder.CopyTo
CopyTo() [2/2]
void System.Collections.Generic.LargeArrayBuilder< T >.CopyTo (T[] array, int arrayIndex, int count) inline
Definition at line 101 of file LargeArrayBuilder.cs.
        {
            int num = 0;
            while (count > 0)
            {
                T[] buffer = this.GetBuffer(num);
                int num2 = Math.Min(count, buffer.Length);
                Array.Copy(buffer, 0, array, arrayIndex, num2);
                count -= num2;
                arrayIndex += num2;
                num++;
            }
        }
References System.array, System.arrayIndex, System.Array.Copy(), System.count, System.Collections.Generic.LargeArrayBuilder< T >.GetBuffer(), and System.Math.Min().
Referenced by System.Collections.Generic.LargeArrayBuilder< T >.CopyTo(), and System.Collections.Generic.LargeArrayBuilder< T >.ToArray().