Terraria Decompiled: XPT.Core.Audio.MP3Sharp.MP3Stream.ReadFrame
ReadFrame()
bool XPT.Core.Audio.MP3Sharp.MP3Stream.ReadFrame () inline private
Definition at line 247 of file MP3Stream.cs.
        {
            Header header = this._BitStream.ReadFrame();
            if (header == null)
            {
                return false;
            }
            try
            {
                if (header.Mode() == 3)
                {
                    this._ChannelCountRep = 1;
                }
                else
                {
                    this._ChannelCountRep = 2;
                }
                this._FrequencyRep = header.Frequency();
                if (this._Decoder.DecodeFrame(header, this._BitStream) != this._Buffer)
                {
                    throw new ApplicationException("Output buffers are different.");
                }
            }
            finally
            {
                this._BitStream.CloseFrame();
            }
            return true;
        }
References XPT.Core.Audio.MP3Sharp.MP3Stream._BitStream, XPT.Core.Audio.MP3Sharp.MP3Stream._Decoder, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.CloseFrame(), XPT.Core.Audio.MP3Sharp.Decoding.Decoder.DecodeFrame(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Frequency(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Mode(), and XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadFrame().
Referenced by XPT.Core.Audio.MP3Sharp.MP3Stream.DecodeFrames(), and XPT.Core.Audio.MP3Sharp.MP3Stream.MP3Stream().