Terraria Decompiled: XPT.Core.Audio.MP3Sharp.MP3Stream.Read
Read()
override int XPT.Core.Audio.MP3Sharp.MP3Stream.Read (byte[] buffer, int offset, int count) inline
Definition at line 220 of file MP3Stream.cs.
        {
            if (this.IsEOF)
            {
                return 0;
            }
            int num = 0;
            while (this._Buffer.BytesLeft > 0 || this.ReadFrame())
            {
                num += this._Buffer.Read(buffer, offset + num, count - num);
                if (num >= count)
                {
                    return num;
                }
            }
            this.IsEOF = true;
            this._BitStream.CloseFrame();
            return num;
        }
References XPT.Core.Audio.MP3Sharp.MP3Stream._BitStream, XPT.Core.Audio.MP3Sharp.MP3Stream._Buffer, XPT.Core.Audio.MP3Sharp.Buffer16BitStereo.BytesLeft, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.CloseFrame(), System.count, XPT.Core.Audio.MP3Sharp.MP3Stream.IsEOF, System.offset, and XPT.Core.Audio.MP3Sharp.Buffer16BitStereo.Read().
Referenced by Terraria.Audio.MP3AudioTrack.ReadAheadPutAChunkIntoTheBuffer().