Terraria Decompiled: System.Runtime.InteropServices.ExtensibleClassFactory.RegisterObjectCreationCallback
RegisterObjectCreationCallback()
static void System.Runtime.InteropServices.ExtensibleClassFactory.RegisterObjectCreationCallback (ObjectCreationDelegate callback) inline static
Definition at line 24 of file ExtensibleClassFactory.cs.
        {
            int i = 1;
            StackTrace stackTrace = new StackTrace(false);
            while (i < stackTrace.FrameCount)
            {
                MethodBase method = stackTrace.GetFrame(i).GetMethod();
                if (method.MemberType == MemberTypes.Constructor && method.IsStatic)
                {
                    ExtensibleClassFactory.hashtable.Add(method.DeclaringType, callback);
                    return;
                }
                i++;
            }
            throw new InvalidOperationException("RegisterObjectCreationCallback must be called from .cctor of class derived from ComImport type.");
        }
References System.Collections.Hashtable.Add(), System.Reflection.MemberInfo.DeclaringType, System.Diagnostics.StackTrace.FrameCount, System.Diagnostics.StackTrace.GetFrame(), System.Diagnostics.StackFrame.GetMethod(), System.Runtime.InteropServices.ExtensibleClassFactory.hashtable, System.Reflection.MethodBase.IsStatic, and System.Reflection.MemberInfo.MemberType.