Terraria Decompiled: Terraria.Initializers.ChromaInitializer.Load
Load()
static void Terraria.Initializers.ChromaInitializer.Load () inline static
Definition at line 273 of file ChromaInitializer.cs.
        {
            ChromaInitializer._engine = Main.Chroma;
            ChromaInitializer.AddDevices();
            Color color = new Color(46, 23, 12);
            ChromaInitializer.RegisterShader("Base", new SurfaceBiomeShader(Color.Green, color), CommonConditions.InMenu, 9);
            ChromaInitializer.RegisterShader("Surface Mushroom", new SurfaceBiomeShader(Color.DarkBlue, new Color(33, 31, 27)), CommonConditions.DrunkMenu, 9);
            ChromaInitializer.RegisterShader("Sky", new SkyShader(new Color(34, 51, 128), new Color(5, 5, 5)), CommonConditions.Depth.Sky, 1);
            ChromaInitializer.RegisterShader("Surface", new SurfaceBiomeShader(Color.Green, color), CommonConditions.Depth.Surface, 1);
            ChromaInitializer.RegisterShader("Vines", new VineShader(), CommonConditions.Depth.Vines, 1);
            ChromaInitializer.RegisterShader("Underground", new CavernShader(new Color(122, 62, 32), new Color(25, 13, 7), 0.5f), CommonConditions.Depth.Underground, 1);
            ChromaInitializer.RegisterShader("Caverns", new CavernShader(color, new Color(25, 25, 25), 0.5f), CommonConditions.Depth.Caverns, 1);
            ChromaInitializer.RegisterShader("Magma", new CavernShader(new Color(181, 17, 0), new Color(25, 25, 25), 0.5f), CommonConditions.Depth.Magma, 1);
            ChromaInitializer.RegisterShader("Underworld", new UnderworldShader(Color.Red, new Color(1f, 0.5f, 0f), 1f), CommonConditions.Depth.Underworld, 1);
            ChromaInitializer.RegisterShader("Surface Desert", new SurfaceBiomeShader(new Color(84, 49, 0), new Color(245, 225, 33)), CommonConditions.SurfaceBiome.Desert, 2);
            ChromaInitializer.RegisterShader("Surface Jungle", new SurfaceBiomeShader(Color.Green, Color.Teal), CommonConditions.SurfaceBiome.Jungle, 2);
            ChromaInitializer.RegisterShader("Surface Ocean", new SurfaceBiomeShader(Color.SkyBlue, Color.Blue), CommonConditions.SurfaceBiome.Ocean, 2);
            ChromaInitializer.RegisterShader("Surface Snow", new SurfaceBiomeShader(new Color(0, 10, 50), new Color(0.5f, 0.75f, 1f)), CommonConditions.SurfaceBiome.Snow, 2);
            ChromaInitializer.RegisterShader("Surface Mushroom", new SurfaceBiomeShader(Color.DarkBlue, new Color(33, 31, 27)), CommonConditions.SurfaceBiome.Mushroom, 2);
            ChromaInitializer.RegisterShader("Surface Hallow", new HallowSurfaceShader(), CommonConditions.SurfaceBiome.Hallow, 3);
            ChromaInitializer.RegisterShader("Surface Crimson", new CorruptSurfaceShader(Color.Red, new Color(25, 25, 40)), CommonConditions.SurfaceBiome.Crimson, 3);
            ChromaInitializer.RegisterShader("Surface Corruption", new CorruptSurfaceShader(new Color(73, 0, 255), new Color(15, 15, 27)), CommonConditions.SurfaceBiome.Corruption, 3);
            ChromaInitializer.RegisterShader("Hive", new DrippingShader(new Color(0.05f, 0.01f, 0f), new Color(255, 150, 0), 0.5f), CommonConditions.UndergroundBiome.Hive, 3);
            ChromaInitializer.RegisterShader("Underground Mushroom", new UndergroundMushroomShader(), CommonConditions.UndergroundBiome.Mushroom, 2);
            ChromaInitializer.RegisterShader("Underground Corrutpion", new UndergroundCorruptionShader(), CommonConditions.UndergroundBiome.Corrupt, 2);
            ChromaInitializer.RegisterShader("Underground Crimson", new DrippingShader(new Color(0.05f, 0f, 0f), new Color(255, 0, 0), 1f), CommonConditions.UndergroundBiome.Crimson, 2);
            ChromaInitializer.RegisterShader("Underground Hallow", new UndergroundHallowShader(), CommonConditions.UndergroundBiome.Hallow, 2);
            ChromaInitializer.RegisterShader("Meteorite", new MeteoriteShader(), CommonConditions.MiscBiome.Meteorite, 3);
            ChromaInitializer.RegisterShader("Temple", new TempleShader(), CommonConditions.UndergroundBiome.Temple, 3);
            ChromaInitializer.RegisterShader("Dungeon", new DungeonShader(), CommonConditions.UndergroundBiome.Dungeon, 3);
            ChromaInitializer.RegisterShader("Granite", new CavernShader(new Color(14, 19, 46), new Color(5, 0, 30), 0.5f), CommonConditions.UndergroundBiome.Granite, 3);
            ChromaInitializer.RegisterShader("Marble", new CavernShader(new Color(100, 100, 100), new Color(20, 20, 20), 0.5f), CommonConditions.UndergroundBiome.Marble, 3);
            ChromaInitializer.RegisterShader("Gem Cave", new GemCaveShader(color, new Color(25, 25, 25), new Vector4[]
            {
                Color.White.ToVector4(),
                Color.Yellow.ToVector4(),
                Color.Orange.ToVector4(),
                Color.Red.ToVector4(),
                Color.Green.ToVector4(),
                Color.Blue.ToVector4(),
                Color.Purple.ToVector4()
            })
            {
                CycleTime = 100f,
                ColorRarity = 20f,
                TimeRate = 0.25f
            }, CommonConditions.UndergroundBiome.GemCave, 3);
            Vector4[] array = new Vector4[12];
            for (int i = 0; i < array.Length; i++)
            {
                array[i] = Main.hslToRgb((float)i / (float)array.Length, 1f, 0.5f, byte.MaxValue).ToVector4();
            }
            ChromaInitializer.RegisterShader("Shimmer", new GemCaveShader(Color.Silver * 0.5f, new Color(125, 55, 125), array)
            {
                CycleTime = 2f,
                ColorRarity = 4f,
                TimeRate = 0.5f
            }, CommonConditions.UndergroundBiome.Shimmer, 3);
            ChromaInitializer.RegisterShader("Underground Jungle", new JungleShader(), CommonConditions.UndergroundBiome.Jungle, 2);
            ChromaInitializer.RegisterShader("Underground Ice", new IceShader(new Color(0, 10, 50), new Color(0.5f, 0.75f, 1f)), CommonConditions.UndergroundBiome.Ice, 2);
            ChromaInitializer.RegisterShader("Corrupt Ice", new IceShader(new Color(5, 0, 25), new Color(152, 102, 255)), CommonConditions.UndergroundBiome.CorruptIce, 3);
            ChromaInitializer.RegisterShader("Crimson Ice", new IceShader(new Color(0.1f, 0f, 0f), new Color(1f, 0.45f, 0.4f)), CommonConditions.UndergroundBiome.CrimsonIce, 3);
            ChromaInitializer.RegisterShader("Hallow Ice", new IceShader(new Color(0.2f, 0f, 0.1f), new Color(1f, 0.7f, 0.7f)), CommonConditions.UndergroundBiome.HallowIce, 3);
            ChromaInitializer.RegisterShader("Underground Desert", new DesertShader(new Color(60, 10, 0), new Color(255, 165, 0)), CommonConditions.UndergroundBiome.Desert, 2);
            ChromaInitializer.RegisterShader("Corrupt Desert", new DesertShader(new Color(15, 0, 15), new Color(116, 103, 255)), CommonConditions.UndergroundBiome.CorruptDesert, 3);
            ChromaInitializer.RegisterShader("Crimson Desert", new DesertShader(new Color(20, 10, 0), new Color(195, 0, 0)), CommonConditions.UndergroundBiome.CrimsonDesert, 3);
            ChromaInitializer.RegisterShader("Hallow Desert", new DesertShader(new Color(29, 0, 56), new Color(255, 221, 255)), CommonConditions.UndergroundBiome.HallowDesert, 3);
            ChromaInitializer.RegisterShader("Pumpkin Moon", new MoonShader(new Color(13, 0, 26), Color.Orange), CommonConditions.Events.PumpkinMoon, 4);
            ChromaInitializer.RegisterShader("Blood Moon", new MoonShader(new Color(10, 0, 0), Color.Red, Color.Red, new Color(255, 150, 125)), CommonConditions.Events.BloodMoon, 4);
            ChromaInitializer.RegisterShader("Frost Moon", new MoonShader(new Color(0, 4, 13), new Color(255, 255, 255)), CommonConditions.Events.FrostMoon, 4);
            ChromaInitializer.RegisterShader("Solar Eclipse", new MoonShader(new Color(0.02f, 0.02f, 0.02f), Color.Orange, Color.Black), CommonConditions.Events.SolarEclipse, 4);
            ChromaInitializer.RegisterShader("Pirate Invasion", new PirateInvasionShader(new Color(173, 173, 173), new Color(101, 101, 255), Color.Blue, Color.Black), CommonConditions.Events.PirateInvasion, 4);
            ChromaInitializer.RegisterShader("DD2 Event", new DD2Shader(new Color(222, 94, 245), Color.White), CommonConditions.Events.DD2Event, 4);
            ChromaInitializer.RegisterShader("Goblin Army", new GoblinArmyShader(new Color(14, 0, 79), new Color(176, 0, 144)), CommonConditions.Events.GoblinArmy, 4);
            ChromaInitializer.RegisterShader("Frost Legion", new FrostLegionShader(Color.White, new Color(27, 80, 201)), CommonConditions.Events.FrostLegion, 4);
            ChromaInitializer.RegisterShader("Martian Madness", new MartianMadnessShader(new Color(64, 64, 64), new Color(64, 113, 122), new Color(255, 255, 0), new Color(3, 3, 18)), CommonConditions.Events.MartianMadness, 4);
            ChromaInitializer.RegisterShader("Solar Pillar", new PillarShader(Color.Red, Color.Orange), CommonConditions.Events.SolarPillar, 4);
            ChromaInitializer.RegisterShader("Nebula Pillar", new PillarShader(new Color(255, 144, 209), new Color(100, 0, 76)), CommonConditions.Events.NebulaPillar, 4);
            ChromaInitializer.RegisterShader("Vortex Pillar", new PillarShader(Color.Green, Color.Black), CommonConditions.Events.VortexPillar, 4);
            ChromaInitializer.RegisterShader("Stardust Pillar", new PillarShader(new Color(46, 63, 255), Color.White), CommonConditions.Events.StardustPillar, 4);
            ChromaInitializer.RegisterShader("Eater of Worlds", new WormShader(new Color(14, 0, 15), new Color(47, 51, 59), new Color(20, 25, 11)), CommonConditions.Boss.EaterOfWorlds, 5);
            ChromaInitializer.RegisterShader("Eye of Cthulhu", new EyeOfCthulhuShader(new Color(145, 145, 126), new Color(138, 0, 0), new Color(3, 3, 18)), CommonConditions.Boss.EyeOfCthulhu, 5);
            ChromaInitializer.RegisterShader("Skeletron", new SkullShader(new Color(110, 92, 47), new Color(36, 32, 51), new Color(0, 0, 0)), CommonConditions.Boss.Skeletron, 5);
            ChromaInitializer.RegisterShader("Brain Of Cthulhu", new BrainShader(new Color(54, 0, 0), new Color(186, 137, 139)), CommonConditions.Boss.BrainOfCthulhu, 5);
            ChromaInitializer.RegisterShader("Empress of Light", new EmpressShader(), CommonConditions.Boss.Empress, 5);
            ChromaInitializer.RegisterShader("Queen Slime", new QueenSlimeShader(new Color(72, 41, 130), new Color(126, 220, 255)), CommonConditions.Boss.QueenSlime, 5);
            ChromaInitializer.RegisterShader("King Slime", new KingSlimeShader(new Color(41, 70, 130), Color.White), CommonConditions.Boss.KingSlime, 5);
            ChromaInitializer.RegisterShader("Queen Bee", new QueenBeeShader(new Color(5, 5, 0), new Color(255, 235, 0)), CommonConditions.Boss.QueenBee, 5);
            ChromaInitializer.RegisterShader("Wall of Flesh", new WallOfFleshShader(new Color(112, 48, 60), new Color(5, 0, 0)), CommonConditions.Boss.WallOfFlesh, 5);
            ChromaInitializer.RegisterShader("Destroyer", new WormShader(new Color(25, 25, 25), new Color(192, 0, 0), new Color(10, 0, 0)), CommonConditions.Boss.Destroyer, 5);
            ChromaInitializer.RegisterShader("Skeletron Prime", new SkullShader(new Color(110, 92, 47), new Color(79, 0, 0), new Color(255, 29, 0)), CommonConditions.Boss.SkeletronPrime, 5);
            ChromaInitializer.RegisterShader("The Twins", new TwinsShader(new Color(145, 145, 126), new Color(138, 0, 0), new Color(138, 0, 0), new Color(20, 20, 20), new Color(65, 140, 0), new Color(3, 3, 18)), CommonConditions.Boss.TheTwins, 5);
            ChromaInitializer.RegisterShader("Duke Fishron", new DukeFishronShader(new Color(0, 0, 122), new Color(100, 254, 194)), CommonConditions.Boss.DukeFishron, 5);
            ChromaInitializer.RegisterShader("Deerclops", new BlizzardShader(new Vector4(1f, 1f, 1f, 1f), new Vector4(0.15f, 0.1f, 0.4f, 1f), -0.1f, 0.4f), CommonConditions.Boss.Deerclops, 5);
            ChromaInitializer.RegisterShader("Plantera", new PlanteraShader(new Color(255, 0, 220), new Color(0, 255, 0), new Color(12, 4, 0)), CommonConditions.Boss.Plantera, 5);
            ChromaInitializer.RegisterShader("Golem", new GolemShader(new Color(255, 144, 0), new Color(255, 198, 0), new Color(10, 10, 0)), CommonConditions.Boss.Golem, 5);
            ChromaInitializer.RegisterShader("Cultist", new CultistShader(), CommonConditions.Boss.Cultist, 5);
            ChromaInitializer.RegisterShader("Moon Lord", new EyeballShader(false), CommonConditions.Boss.MoonLord, 5);
            ChromaInitializer.RegisterShader("Rain", new RainShader(), CommonConditions.Weather.Rain, 6);
            ChromaInitializer.RegisterShader("Snowstorm", new BlizzardShader(new Vector4(1f, 1f, 1f, 1f), new Vector4(0.1f, 0.1f, 0.3f, 1f), 0.35f, -0.35f), CommonConditions.Weather.Blizzard, 6);
            ChromaInitializer.RegisterShader("Sandstorm", new SandstormShader(), CommonConditions.Weather.Sandstorm, 6);
            ChromaInitializer.RegisterShader("Slime Rain", new SlimeRainShader(), CommonConditions.Weather.SlimeRain, 6);
            ChromaInitializer.RegisterShader("Drowning", new DrowningShader(), CommonConditions.Alert.Drowning, 7);
            ChromaInitializer.RegisterShader("Keybinds", new KeybindsMenuShader(), CommonConditions.Alert.Keybinds, 7);
            ChromaInitializer.RegisterShader("Lava Indicator", new LavaIndicatorShader(Color.Black, Color.Red, new Color(255, 188, 0)), CommonConditions.Alert.LavaIndicator, 7);
            ChromaInitializer.RegisterShader("Moon Lord Spawn", new EyeballShader(true), CommonConditions.Alert.MoonlordComing, 7);
            ChromaInitializer.RegisterShader("Low Life", new LowLifeShader(), CommonConditions.CriticalAlert.LowLife, 8);
            ChromaInitializer.RegisterShader("Death", new DeathShader(new Color(36, 0, 10), new Color(158, 28, 53)), CommonConditions.CriticalAlert.Death, 8);
        }
References Terraria.Initializers.ChromaInitializer.AddDevices(), System.array, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.RGB.CommonConditions.Weather.Blizzard, Terraria.GameContent.RGB.CommonConditions.Events.BloodMoon, Microsoft.Xna.Framework.Color.Blue, Terraria.GameContent.RGB.CommonConditions.Boss.BrainOfCthulhu, Terraria.GameContent.RGB.CommonConditions.Depth.Caverns, Terraria.Main.Chroma, SteelSeries.GameSense.Color, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Corrupt, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.CorruptDesert, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.CorruptIce, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Corruption, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Crimson, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Crimson, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.CrimsonDesert, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.CrimsonIce, Terraria.GameContent.RGB.CommonConditions.Boss.Cultist, Microsoft.Xna.Framework.Color.DarkBlue, Terraria.GameContent.RGB.CommonConditions.Events.DD2Event, Terraria.GameContent.RGB.CommonConditions.CriticalAlert.Death, Terraria.GameContent.RGB.CommonConditions.Boss.Deerclops, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Desert, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Desert, Terraria.GameContent.RGB.CommonConditions.Boss.Destroyer, Terraria.GameContent.RGB.CommonConditions.Alert.Drowning, Terraria.GameContent.RGB.CommonConditions.DrunkMenu, Terraria.GameContent.RGB.CommonConditions.Boss.DukeFishron, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Dungeon, Terraria.GameContent.RGB.CommonConditions.Boss.EaterOfWorlds, Terraria.GameContent.RGB.CommonConditions.Boss.Empress, Terraria.GameContent.RGB.CommonConditions.Boss.EyeOfCthulhu, Terraria.GameContent.RGB.CommonConditions.Events.FrostLegion, Terraria.GameContent.RGB.CommonConditions.Events.FrostMoon, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.GemCave, Terraria.GameContent.RGB.CommonConditions.Events.GoblinArmy, Terraria.GameContent.RGB.CommonConditions.Boss.Golem, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Granite, Microsoft.Xna.Framework.Color.Green, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Hallow, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Hallow, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.HallowDesert, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.HallowIce, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Hive, Terraria.Main.hslToRgb(), Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Ice, Terraria.GameContent.RGB.CommonConditions.InMenu, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Jungle, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Jungle, Terraria.GameContent.RGB.CommonConditions.Alert.Keybinds, Terraria.GameContent.RGB.CommonConditions.Boss.KingSlime, Terraria.GameContent.RGB.CommonConditions.Alert.LavaIndicator, Terraria.GameContent.RGB.CommonConditions.CriticalAlert.LowLife, Terraria.GameContent.RGB.CommonConditions.Depth.Magma, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Marble, Terraria.GameContent.RGB.CommonConditions.Events.MartianMadness, Terraria.GameContent.RGB.CommonConditions.MiscBiome.Meteorite, Terraria.GameContent.RGB.CommonConditions.Boss.MoonLord, Terraria.GameContent.RGB.CommonConditions.Alert.MoonlordComing, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Mushroom, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Mushroom, Terraria.GameContent.RGB.CommonConditions.Events.NebulaPillar, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Ocean, Microsoft.Xna.Framework.Color.Orange, Terraria.GameContent.RGB.CommonConditions.Events.PirateInvasion, Terraria.GameContent.RGB.CommonConditions.Boss.Plantera, Terraria.GameContent.RGB.CommonConditions.Events.PumpkinMoon, Microsoft.Xna.Framework.Color.Purple, Terraria.GameContent.RGB.CommonConditions.Boss.QueenBee, Terraria.GameContent.RGB.CommonConditions.Boss.QueenSlime, Terraria.GameContent.RGB.CommonConditions.Weather.Rain, Microsoft.Xna.Framework.Color.Red, Terraria.Initializers.ChromaInitializer.RegisterShader(), Terraria.GameContent.RGB.CommonConditions.Weather.Sandstorm, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Shimmer, Microsoft.Xna.Framework.Color.Silver, Terraria.GameContent.RGB.CommonConditions.Boss.Skeletron, Terraria.GameContent.RGB.CommonConditions.Boss.SkeletronPrime, Terraria.GameContent.RGB.CommonConditions.Depth.Sky, Microsoft.Xna.Framework.Color.SkyBlue, Terraria.GameContent.RGB.CommonConditions.Weather.SlimeRain, Terraria.GameContent.RGB.CommonConditions.SurfaceBiome.Snow, Terraria.GameContent.RGB.CommonConditions.Events.SolarEclipse, Terraria.GameContent.RGB.CommonConditions.Events.SolarPillar, Terraria.GameContent.RGB.CommonConditions.Events.StardustPillar, Terraria.GameContent.RGB.CommonConditions.Depth.Surface, Microsoft.Xna.Framework.Color.Teal, Terraria.GameContent.RGB.CommonConditions.UndergroundBiome.Temple, Terraria.GameContent.RGB.CommonConditions.Boss.TheTwins, Microsoft.Xna.Framework.Color.ToVector4(), Terraria.GameContent.RGB.CommonConditions.Depth.Underground, Terraria.GameContent.RGB.CommonConditions.Depth.Underworld, Terraria.GameContent.RGB.CommonConditions.Depth.Vines, Terraria.GameContent.RGB.CommonConditions.Events.VortexPillar, Terraria.GameContent.RGB.CommonConditions.Boss.WallOfFlesh, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Color.Yellow.
Referenced by Terraria.Main.LoadContent().