Terraria Decompiled: Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense
LoadSpecialRulesFor_GameSense()
static void Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense () inline static private
Definition at line 151 of file ChromaInitializer.cs.
        {
            GameSenseSpecificInfo gameSenseSpecificInfo = new GameSenseSpecificInfo();
            List<Bind_Event> list = new List<Bind_Event>();
            gameSenseSpecificInfo.EventsToBind = list;
            ChromaInitializer.LoadSpecialRulesFor_GameSense_Keyboard(list);
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE1", "zone1", new RGBZonedDevice("one"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE2", "zone2", new RGBZonedDevice("two"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE3", "zone3", new RGBZonedDevice("three"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE4", "zone4", new RGBZonedDevice("four"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE5", "zone5", new RGBZonedDevice("five"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE6", "zone6", new RGBZonedDevice("six"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE7", "zone7", new RGBZonedDevice("seven"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE8", "zone8", new RGBZonedDevice("eight"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE9", "zone9", new RGBZonedDevice("nine"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE10", "zone10", new RGBZonedDevice("ten"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE11", "zone11", new RGBZonedDevice("eleven"));
            ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(list, "ZONE12", "zone12", new RGBZonedDevice("twelve"));
            ChromaInitializer.AddGameplayEvents(list);
            gameSenseSpecificInfo.MiscEvents = new List<ARgbGameValueTracker>
            {
                ChromaInitializer.Event_LifePercent,
                ChromaInitializer.Event_ManaPercent,
                ChromaInitializer.Event_BreathPercent
            };
            foreach (Bind_Event bind_Event in gameSenseSpecificInfo.EventsToBind)
            {
                ChromaInitializer.EventLocalization eventLocalization;
                if (ChromaInitializer._localizedEvents.TryGetValue(bind_Event.eventName, out eventLocalization))
                {
                    bind_Event.defaultDisplayName = eventLocalization.DefaultDisplayName;
                    bind_Event.localizedDisplayNames = eventLocalization.LocalizedNames;
                }
            }
            ChromaInitializer._engine.LoadSpecialRules(gameSenseSpecificInfo);
        }
References Terraria.Initializers.ChromaInitializer._engine, Terraria.Initializers.ChromaInitializer._localizedEvents, Terraria.Initializers.ChromaInitializer.AddGameplayEvents(), Terraria.Initializers.ChromaInitializer.EventLocalization.DefaultDisplayName, Terraria.Initializers.ChromaInitializer.Event_LifePercent, Terraria.Initializers.ChromaInitializer.Event_ManaPercent, SteelSeries.GameSense.Bind_Event.eventName, System.list, ReLogic.Peripherals.RGB.ChromaEngine.LoadSpecialRules(), Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_GameSense_Keyboard(), Terraria.Initializers.ChromaInitializer.LoadSpecialRulesFor_SecondaryDevice(), and Terraria.Initializers.ChromaInitializer.EventLocalization.LocalizedNames.
Referenced by Terraria.Initializers.ChromaInitializer.LoadSpecialRulesForDevices().