Terraria Decompiled: Terraria.Initializers.ChromaInitializer.UpdateEvents
UpdateEvents()
static void Terraria.Initializers.ChromaInitializer.UpdateEvents () inline static
Definition at line 132 of file ChromaInitializer.cs.
        {
            if (Main.gameMenu)
            {
                ChromaInitializer.Event_LifePercent.Update(0, false);
                ChromaInitializer.Event_ManaPercent.Update(0, false);
                ChromaInitializer.Event_BreathPercent.Update(0, false);
                return;
            }
            Player localPlayer = Main.LocalPlayer;
            int num = (int)Utils.Clamp<float>((float)localPlayer.statLife / (float)localPlayer.statLifeMax2 * 100f, 0f, 100f);
            ChromaInitializer.Event_LifePercent.Update(num, true);
            int num2 = (int)Utils.Clamp<float>((float)localPlayer.statMana / (float)localPlayer.statManaMax2 * 100f, 0f, 100f);
            ChromaInitializer.Event_ManaPercent.Update(num2, true);
            int num3 = (int)Utils.Clamp<float>((float)localPlayer.breath / (float)localPlayer.breathMax * 100f, 0f, 100f);
            ChromaInitializer.Event_BreathPercent.Update(num3, true);
        }
References Terraria.Player.breathMax, Terraria.Utils.Clamp(), Terraria.Initializers.ChromaInitializer.Event_BreathPercent, Terraria.Initializers.ChromaInitializer.Event_LifePercent, Terraria.Initializers.ChromaInitializer.Event_ManaPercent, Terraria.Main.gameMenu, int, Terraria.Main.LocalPlayer, Terraria.Player.statLifeMax2, Terraria.Player.statManaMax2, and ReLogic.Peripherals.RGB.ARgbGameValueTracker< TValueType >.Update().
Referenced by Terraria.Main.DoUpdate().