Terraria Decompiled: Microsoft.Xna.Framework.Vector3.ToString
ToString()
override string Microsoft.Xna.Framework.Vector3.ToString () inline
Definition at line 206 of file Vector3.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(32);
            stringBuilder.Append("{X:");
            stringBuilder.Append(this.X);
            stringBuilder.Append(" Y:");
            stringBuilder.Append(this.Y);
            stringBuilder.Append(" Z:");
            stringBuilder.Append(this.Z);
            stringBuilder.Append("}");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.ToString(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingBox.ToString(), Microsoft.Xna.Framework.BoundingSphere.ToString(), Microsoft.Xna.Framework.Graphics.VertexPositionColor.ToString(), Microsoft.Xna.Framework.Graphics.VertexPositionColorTexture.ToString(), Microsoft.Xna.Framework.Graphics.VertexPositionNormalTexture.ToString(), Microsoft.Xna.Framework.Graphics.VertexPositionTexture.ToString(), Microsoft.Xna.Framework.Plane.ToString(), and Microsoft.Xna.Framework.Ray.ToString().