Terraria Decompiled: Microsoft.Xna.Framework.Vector3.Length
Length()
float Microsoft.Xna.Framework.Vector3.Length () inline
Definition at line 185 of file Vector3.cs.
        {
            return (float)Math.Sqrt((double)(this.X * this.X + this.Y * this.Y + this.Z * this.Z));
        }
References System.Math.Sqrt(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Graphics.Light.LightMap.Clear(), Microsoft.Xna.Framework.BoundingBox.Contains(), Microsoft.Xna.Framework.BoundingSphere.CreateMerged(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawProjDirect(), Microsoft.Xna.Framework.BoundingBox.GetCorners(), Microsoft.Xna.Framework.BoundingFrustum.GetCorners(), Microsoft.Xna.Framework.Plane.Normalize(), Terraria.GameInput.LockOnHelper.RefreshTargets(), Terraria.Graphics.Light.LightMap.SetSize(), Microsoft.Xna.Framework.Vector3.Transform(), Microsoft.Xna.Framework.Vector3.Transform(), Microsoft.Xna.Framework.Vector3.TransformNormal(), and Microsoft.Xna.Framework.Vector3.TransformNormal().