Terraria Decompiled: Terraria.Achievements.AchievementManager.Load
Load() [2/2]
void Terraria.Achievements.AchievementManager.Load (string path, bool cloud) inline private
Definition at line 124 of file AchievementManager.cs.
        {
            bool flag = false;
            object ioLock = AchievementManager._ioLock;
            lock (ioLock)
            {
                if (!FileUtilities.Exists(path, cloud))
                {
                    return;
                }
                byte[] array = FileUtilities.ReadAllBytes(path, cloud);
                Dictionary<string, AchievementManager.StoredAchievement> dictionary = null;
                try
                {
                    using (MemoryStream memoryStream = new MemoryStream(array))
                    {
                        using (CryptoStream cryptoStream = new CryptoStream(memoryStream, new RijndaelManaged().CreateDecryptor(this._cryptoKey, this._cryptoKey), CryptoStreamMode.Read))
{
                            using (BsonReader bsonReader = new BsonReader(cryptoStream))
{
                                dictionary = JsonSerializer.Create(this._serializerSettings).Deserialize<Dictionary<string, AchievementManager.StoredAchievement>>(bsonReader);
                            }
                        }
                    }
                }
                catch (Exception)
                {
                    FileUtilities.Delete(path, cloud, false);
                    return;
                }
                if (dictionary == null)
                {
                    return;
                }
                foreach (KeyValuePair<string, AchievementManager.StoredAchievement> keyValuePair in dictionary)
                {
                    if (this._achievements.ContainsKey(keyValuePair.Key))
                    {
                        this._achievements[keyValuePair.Key].Load(keyValuePair.Value.Conditions);
                    }
                }
                if (SocialAPI.Achievements != null)
                {
                    foreach (KeyValuePair<string, Achievement> keyValuePair2 in this._achievements)
                    {
                        if (keyValuePair2.Value.IsCompleted && !SocialAPI.Achievements.IsAchievementCompleted(keyValuePair2.Key))
{
                            flag = true;
                            keyValuePair2.Value.ClearProgress();
                        }
                    }
                }
            }
            if (flag)
            {
                this.Save();
            }
        }
References Terraria.Achievements.AchievementManager._achievements, Terraria.Achievements.AchievementManager._cryptoKey, Terraria.Achievements.AchievementManager._ioLock, Terraria.Achievements.AchievementManager._serializerSettings, Terraria.Social.SocialAPI.Achievements, System.array, Newtonsoft.Json.JsonSerializer.Create(), Terraria.Utilities.FileUtilities.Delete(), Newtonsoft.Json.JsonSerializer.Deserialize(), System.dictionary, Terraria.Utilities.FileUtilities.Exists(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.Utilities.FileUtilities.ReadAllBytes(), Terraria.Achievements.AchievementManager.Save(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.