Terraria Decompiled: Terraria.Achievements.AchievementManager.Save
Save() [2/2]
void Terraria.Achievements.AchievementManager.Save (string path, bool cloud) inline private
Definition at line 79 of file AchievementManager.cs.
        {
            object ioLock = AchievementManager._ioLock;
            lock (ioLock)
            {
                if (SocialAPI.Achievements != null)
                {
                    SocialAPI.Achievements.StoreStats();
                }
                try
                {
                    using (MemoryStream memoryStream = new MemoryStream())
                    {
                        using (CryptoStream cryptoStream = new CryptoStream(memoryStream, new RijndaelManaged().CreateEncryptor(this._cryptoKey, this._cryptoKey), CryptoStreamMode.Write))
{
                            using (BsonWriter bsonWriter = new BsonWriter(cryptoStream))
{
                                JsonSerializer.Create(this._serializerSettings).Serialize(bsonWriter, this._achievements);
                                bsonWriter.Flush();
                                cryptoStream.FlushFinalBlock();
                                FileUtilities.WriteAllBytes(path, memoryStream.ToArray(), cloud);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    FancyErrorPrinter.ShowFileSavingFailError(ex, this._savePath);
                }
            }
        }
References Terraria.Achievements.AchievementManager._achievements, Terraria.Achievements.AchievementManager._cryptoKey, Terraria.Achievements.AchievementManager._ioLock, Terraria.Achievements.AchievementManager._savePath, Terraria.Achievements.AchievementManager._serializerSettings, Terraria.Social.SocialAPI.Achievements, Newtonsoft.Json.JsonSerializer.Create(), Newtonsoft.Json.Bson.BsonWriter.Flush(), System.Security.Cryptography.CryptoStream.FlushFinalBlock(), Newtonsoft.Json.JsonSerializer.Serialize(), Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError(), System.IO.MemoryStream.ToArray(), and Terraria.Utilities.FileUtilities.WriteAllBytes().