Terraria Decompiled: Mono.Xml.SecurityParser.OnStartElement
OnStartElement()
void Mono.Xml.SecurityParser.OnStartElement (string name, SmallXmlParser::IAttrList attrs) inline
Implements Mono.Xml.SmallXmlParser.IContentHandler.
Definition at line 47 of file SecurityParser.cs.
        {
            SecurityElement securityElement = new SecurityElement(name);
            if (this.root == null)
            {
                this.root = securityElement;
                this.current = securityElement;
            }
            else
            {
                ((SecurityElement)this.stack.Peek()).AddChild(securityElement);
            }
            this.stack.Push(securityElement);
            this.current = securityElement;
            int length = attrs.Length;
            for (int i = 0; i < length; i++)
            {
                this.current.AddAttribute(attrs.GetName(i), SecurityElement.Escape(attrs.GetValue(i)));
            }
        }
References System.Security.SecurityElement.AddAttribute(), Mono.Xml.SecurityParser.current, System.Security.SecurityElement.Escape(), System.length, System.name, System.Collections.Stack.Peek(), System.Collections.Stack.Push(), Mono.Xml.SecurityParser.root, and Mono.Xml.SecurityParser.stack.