Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.CreateSteamDisclaimer
CreateSteamDisclaimer()
UIElement Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer (string tagGroup) inline private
Definition at line 176 of file AWorkshopPublishInfoState.cs.
        {
            float num = 60f;
            float num2 = 0f + num;
            GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(true, null, null, Color.White, null, 1f, 0.5f, 16f);
            groupOptionButton.HAlign = 0.5f;
            groupOptionButton.VAlign = 0f;
            groupOptionButton.Width = StyleDimension.FromPixelsAndPercent(0f, 1f);
            groupOptionButton.Left = StyleDimension.FromPixels(0f);
            groupOptionButton.Height = StyleDimension.FromPixelsAndPercent(num2 + 4f, 0f);
            groupOptionButton.Top = StyleDimension.FromPixels(0f);
            groupOptionButton.ShowHighlightWhenSelected = false;
            groupOptionButton.SetCurrentOption(false);
            groupOptionButton.Width.Set(0f, 1f);
            UIElement uielement = new UIElement
            {
                HAlign = 0.5f,
                VAlign = 1f,
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(num, 0f)
            };
            groupOptionButton.Append(uielement);
            UIText uitext = new UIText(Language.GetText("Workshop.SteamDisclaimer"), 1f, false)
            {
                HAlign = 0f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(-40f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                TextColor = Color.Cyan,
                IgnoresMouseInteraction = true
            };
            uitext.PaddingLeft = 20f;
            uitext.PaddingRight = 20f;
            uitext.PaddingTop = 4f;
            uitext.IsWrapped = true;
            this._disclaimerText = uitext;
            groupOptionButton.OnLeftClick += this.steamDisclaimerText_OnClick;
            groupOptionButton.OnMouseOver += this.steamDisclaimerText_OnMouseOver;
            groupOptionButton.OnMouseOut += this.steamDisclaimerText_OnMouseOut;
            uielement.Append(uitext);
            uitext.SetSnapPoint(tagGroup, 0, null, null);
            this._steamDisclaimerButton = uitext;
            return groupOptionButton;
        }
References Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Color.Cyan, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.steamDisclaimerText_OnClick(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.steamDisclaimerText_OnMouseOut(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.steamDisclaimerText_OnMouseOver(), Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList().