Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.AddPublishButton
AddPublishButton()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton (int backButtonYLift, UIElement outerContainer) inline private
Definition at line 626 of file AWorkshopPublishInfoState.cs.
        {
            UITextPanel<LocalizedText> uitextPanel = new UITextPanel<LocalizedText>(Language.GetText("Workshop.Publish"), 0.7f, true);
            uitextPanel.Width.Set(-10f, 0.5f);
            uitextPanel.Height.Set(50f, 0f);
            uitextPanel.VAlign = 1f;
            uitextPanel.Top.Set((float)(-(float)backButtonYLift), 0f);
            uitextPanel.HAlign = 1f;
            uitextPanel.OnMouseOver += this.FadedMouseOver;
            uitextPanel.OnMouseOut += this.FadedMouseOut;
            uitextPanel.OnLeftClick += this.Click_Publish;
            uitextPanel.SetSnapPoint("publish", 0, null, null);
            outerContainer.Append(uitextPanel);
            this._publishButton = uitextPanel;
        }
References Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.Click_Publish(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FadedMouseOut(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.Height, Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize().