Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.AddHorizontalSeparator
AddHorizontalSeparator()
UIElement Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator (UIElement Container, float accumualtedHeight, int widthReduction = 0) inline private
Definition at line 660 of file AWorkshopPublishInfoState.cs.
        {
            UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
            {
                Width = StyleDimension.FromPixelsAndPercent((float)(-(float)widthReduction), 1f),
                HAlign = 0.5f,
                Top = StyleDimension.FromPixels(accumualtedHeight - 8f),
                Color = Color.Lerp(Color.White, new Color(63, 65, 151, 255), 0.85f) * 0.9f
            };
            Container.Append(uihorizontalSeparator);
            return uihorizontalSeparator;
        }
References Terraria.UI.UIElement.Append(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Microsoft.Xna.Framework.Color.Lerp(), Terraria.UI.UIElement.Top, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize().