Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.PickNewVelocity
PickNewVelocity()
void Terraria.Graphics.Renderers.FakeFishParticle.PickNewVelocity () inline private
Definition at line 400 of file FakeFishParticle.cs.
        {
            this._targetVelocity = Main.rand.NextVector2Circular(1.5f, 0.6f);
            if (this._state == FakeFishParticle.State.InterestedInBobber)
            {
                this._targetVelocity = (this._bobberLocation - this.Position).SafeNormalize(-Vector2.UnitY) * (0.7f + 0.5f * Main.rand.NextFloat());
            }
            if (this._state == FakeFishParticle.State.Latched)
            {
                this._targetVelocity = (this._latchedProjectile.Center - this.Position).SafeNormalize(-Vector2.UnitY) * 0.7f;
            }
        }
References Terraria.Graphics.Renderers.FakeFishParticle._state, Terraria.Graphics.Renderers.FakeFishParticle.Position, Terraria.Main.rand, and Microsoft.Xna.Framework.Vector2.UnitY.
Referenced by Terraria.Graphics.Renderers.FakeFishParticle.BeRepelled(), Terraria.Graphics.Renderers.FakeFishParticle.Prepare(), Terraria.Graphics.Renderers.FakeFishParticle.RemoveLatch(), and Terraria.Graphics.Renderers.FakeFishParticle.Update().