Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.TryToPushAway
TryToPushAway()
bool Terraria.Graphics.Renderers.FakeFishParticle.TryToPushAway (Projectile projectile, int requiredItemType = -1) inline
Definition at line 57 of file FakeFishParticle.cs.
        {
            if (this._state == FakeFishParticle.State.Jumping)
            {
                return false;
            }
            if (requiredItemType == this._itemInstance.type)
            {
                return false;
            }
            if (!this.CanHit(projectile, -1, 160f))
            {
                return false;
            }
            this.Velocity += projectile.DirectionTo(this.Position).SafeNormalize(Vector2.UnitY) * (1f + 1f * Main.rand.NextFloat()) * 1f;
            return true;
        }
References Terraria.Graphics.Renderers.FakeFishParticle._itemInstance, Terraria.Graphics.Renderers.FakeFishParticle._state, Terraria.Graphics.Renderers.FakeFishParticle.CanHit(), Terraria.Entity.DirectionTo(), Terraria.Graphics.Renderers.FakeFishParticle.Position, Terraria.Main.rand, Terraria.Item.type, and Microsoft.Xna.Framework.Vector2.UnitY.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.PushAwayFakeFish().