Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.OnInitialize
OnInitialize()
override void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize () inline virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 33 of file AWorkshopPublishInfoState.cs.
        {
            base.OnInitialize();
            int num = 40;
            int num2 = 200;
            int num3 = 50 + num + 10;
            int num4 = 70;
            UIElement uielement = new UIElement();
            uielement.Width.Set(600f, 0f);
            uielement.Top.Set((float)num2, 0f);
            uielement.Height.Set((float)(-(float)num2), 1f);
            uielement.HAlign = 0.5f;
            UIPanel uipanel = new UIPanel();
            uipanel.Width.Set(0f, 1f);
            uipanel.Height.Set((float)(-(float)num3), 1f);
            uipanel.BackgroundColor = new Color(33, 43, 79) * 0.8f;
            this.AddBackButton(num, uielement);
            this.AddPublishButton(num, uielement);
            int num5 = 6 + num4;
            UIList uilist = this.AddUIList(uipanel, (float)num5);
            this.FillUIList(uilist);
            this.AddHorizontalSeparator(uipanel, 0f, 0).Top = new StyleDimension((float)(-(float)num4 + 3), 1f);
            this.AddDescriptionPanel(uipanel, (float)(num4 - 6), "desc");
            uielement.Append(uipanel);
            base.Append(uielement);
            this.SetDefaultOptions();
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddBackButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddHorizontalSeparator(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), Terraria.UI.UIElement.Append(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList(), Terraria.UI.UIElement.Height, Terraria.UI.StyleDimension.Set(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetDefaultOptions(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), and Terraria.UI.UIElement.Width.