Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.DoStandardWaterSplash
DoStandardWaterSplash()
void Terraria.Graphics.Renderers.FakeFishParticle.DoStandardWaterSplash (Vector2 castPosition, bool shimmerWet, bool honeyWet, bool lavaWet) inline private
Definition at line 157 of file FakeFishParticle.cs.
        {
            Vector2 vector = castPosition - new Vector2(4f, 4f);
            int num = 8;
            int num2 = 8;
            if (shimmerWet)
            {
                for (int i = 0; i < 10; i++)
                {
                    int num3 = Dust.NewDust(new Vector2(vector.X - 6f, vector.Y + (float)(num2 / 2) - 8f), num + 12, 24, 308, 0f, 0f, 0, default(Color), 1f);
                    Dust dust = Main.dust[num3];
                    dust.velocity.Y = dust.velocity.Y - 4f;
                    Dust dust2 = Main.dust[num3];
                    dust2.velocity.X = dust2.velocity.X * 2.5f;
                    Main.dust[num3].scale = 1.3f;
                    Main.dust[num3].noGravity = true;
                    int num4 = Main.rand.Next(6);
                    if (num4 == 0)
                    {
                        Main.dust[num3].color = new Color(255, 255, 210);
                    }
                    else if (num4 == 1)
                    {
                        Main.dust[num3].color = new Color(190, 245, 255);
                    }
                    else if (num4 == 2)
                    {
                        Main.dust[num3].color = new Color(255, 150, 255);
                    }
                    else
                    {
                        Main.dust[num3].color = new Color(190, 175, 255);
                    }
                    SoundEngine.PlaySound(SoundID.FishSplash, (int)vector.X, (int)vector.Y, 5f, 1f);
                }
                return;
            }
            if (honeyWet)
            {
                for (int j = 0; j < 10; j++)
                {
                    int num5 = Dust.NewDust(new Vector2(vector.X - 6f, vector.Y + (float)(num2 / 2) - 8f), num + 12, 24, 152, 0f, 0f, 0, default(Color), 1f);
                    Dust dust3 = Main.dust[num5];
                    dust3.velocity.Y = dust3.velocity.Y - 1f;
                    Dust dust4 = Main.dust[num5];
                    dust4.velocity.X = dust4.velocity.X * 2.5f;
                    Main.dust[num5].scale = 1.3f;
                    Main.dust[num5].alpha = 100;
                    Main.dust[num5].noGravity = true;
                }
                SoundEngine.PlaySound(SoundID.FishSplash, (int)vector.X, (int)vector.Y, 1f, 1f);
                return;
            }
            if (lavaWet)
            {
                for (int k = 0; k < 10; k++)
                {
                    int num6 = Dust.NewDust(new Vector2(vector.X - 6f, vector.Y + (float)(num2 / 2) - 8f), num + 12, 24, 35, 0f, 0f, 0, default(Color), 1f);
                    Dust dust5 = Main.dust[num6];
                    dust5.velocity.Y = dust5.velocity.Y - 1.5f;
                    Dust dust6 = Main.dust[num6];
                    dust6.velocity.X = dust6.velocity.X * 2.5f;
                    Main.dust[num6].scale = 1.3f;
                    Main.dust[num6].alpha = 100;
                    Main.dust[num6].noGravity = true;
                }
                SoundEngine.PlaySound(SoundID.FishSplash, (int)vector.X, (int)vector.Y, 1f, 1f);
                return;
            }
            for (int l = 0; l < 10; l++)
            {
                int num7 = Dust.NewDust(new Vector2(vector.X - 6f, vector.Y + (float)(num2 / 2)), num + 12, 24, Dust.dustWater(), 0f, 0f, 0, default(Color), 1f);
                Dust dust7 = Main.dust[num7];
                dust7.velocity.Y = dust7.velocity.Y - 4f;
                Dust dust8 = Main.dust[num7];
                dust8.velocity.X = dust8.velocity.X * 2.5f;
                Main.dust[num7].scale = 1.3f;
                Main.dust[num7].alpha = 100;
                Main.dust[num7].noGravity = true;
            }
            SoundEngine.PlaySound(SoundID.FishSplash, (int)vector.X, (int)vector.Y, 1f, 1f);
        }
References Terraria.Dust.alpha, Microsoft.Xna.Framework.Graphics.Color, Terraria.Dust.color, Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.ID.SoundID.FishSplash, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Renderers.FakeFishParticle.EmitWaterPulse().