Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.UpdateScrollbar
UpdateScrollbar()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateScrollbar () inline private
Definition at line 256 of file AWorkshopPublishInfoState.cs.
        {
            if (this._scrollbar == null)
            {
                return;
            }
            if (this._isScrollbarAttached && !this._scrollbar.CanScroll)
            {
                this._uiListContainer.RemoveChild(this._scrollbar);
                this._isScrollbarAttached = false;
                this._uiListRect.Width.Set(0f, 1f);
                return;
            }
            if (!this._isScrollbarAttached && this._scrollbar.CanScroll)
            {
                this._uiListContainer.Append(this._scrollbar);
                this._isScrollbarAttached = true;
                this._uiListRect.Width.Set(-25f, 1f);
            }
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._isScrollbarAttached, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._scrollbar, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._uiListContainer, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._uiListRect, Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UIScrollbar.CanScroll, Terraria.UI.UIElement.RemoveChild(), Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.Recalculate().