Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.CreatePreviewImageSelectionPanel
CreatePreviewImageSelectionPanel()
UIElement Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel (string tagGroup) inline private
Definition at line 91 of file AWorkshopPublishInfoState.cs.
        {
            UIElement uielement = new UIElement();
            uielement.Width = new StyleDimension(0f, 1f);
            uielement.Height = new StyleDimension(80f, 0f);
            UIElement uielement2 = new UIElement
            {
                Width = new StyleDimension(72f, 0f),
                Height = new StyleDimension(72f, 0f),
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension(-6f, 0f),
                Top = new StyleDimension(0f, 0f)
            };
            uielement2.SetPadding(0f);
            uielement.Append(uielement2);
            float num = 86f;
            this._defaultPreviewImageTexture = Main.Assets.Request<Texture2D>("Images/UI/Workshop/DefaultPreviewImage", 1);
            UIImage uiimage = new UIImage(this._defaultPreviewImageTexture)
            {
                Width = new StyleDimension(-4f, 1f),
                Height = new StyleDimension(-4f, 1f),
                HAlign = 0.5f,
                VAlign = 0.5f,
                ScaleToFit = true,
                AllowResizingDimensions = false
            };
            UIImage uiimage2 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Achievement_Borders", 1))
            {
                HAlign = 0.5f,
                VAlign = 0.5f
            };
            uielement2.Append(uiimage);
            uielement2.Append(uiimage2);
            this._previewImageUIElement = uiimage;
            UICharacterNameButton uicharacterNameButton = new UICharacterNameButton(Language.GetText("Workshop.PreviewImagePathTitle"), Language.GetText("Workshop.PreviewImagePathEmpty"), Language.GetText("Workshop.PreviewImagePathDescription"))
            {
                Width = StyleDimension.FromPixelsAndPercent(-num, 1f),
                Height = new StyleDimension(0f, 1f)
            };
            uicharacterNameButton.OnLeftMouseDown += this.Click_SetPreviewImage;
            uicharacterNameButton.OnMouseOver += this.ShowOptionDescription;
            uicharacterNameButton.OnMouseOut += this.ClearOptionDescription;
            uicharacterNameButton.SetSnapPoint(tagGroup, 0, null, null);
            uielement.Append(uicharacterNameButton);
            this._previewImagePathPlate = uicharacterNameButton;
            return uielement;
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._defaultPreviewImageTexture, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ClearOptionDescription(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.Click_SetPreviewImage(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ShowOptionDescription(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.UIElement(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList().