Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.EmitWaterPulse
EmitWaterPulse()
void Terraria.Graphics.Renderers.FakeFishParticle.EmitWaterPulse () inline private
Definition at line 139 of file FakeFishParticle.cs.
        {
            if (Main.netMode == 2)
            {
                return;
            }
            Vector2 vector = this.Position - new Vector2(4f, 4f);
            int num = 8;
            int num2 = 8;
            bool flag = Collision.LavaCollision(vector, num, num2);
            Collision.WetCollision(vector, num, num2);
            this.DoStandardWaterSplash(this.Position, Collision.shimmer, Collision.honey, flag);
            WaterShaderData waterShaderData = (WaterShaderData)Filters.Scene["WaterDistortion"].GetShader();
            float num3 = 1.4f;
            waterShaderData.QueueRipple(this.Position, new Color(0.5f, 0.1f * (float)Math.Sign(num3) + 0.5f, 0f, 1f) * Math.Abs(num3), new Vector2(4f, 4f), RippleShape.Circle, 0f);
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Graphics.Renderers.FakeFishParticle.DoStandardWaterSplash(), Terraria.Collision.honey, Terraria.Collision.LavaCollision(), Terraria.Main.netMode, Terraria.Graphics.Renderers.FakeFishParticle.Position, Terraria.GameContent.Shaders.WaterShaderData.QueueRipple(), Terraria.Graphics.Effects.Filters.Scene, Terraria.Collision.shimmer, System.Math.Sign(), Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Collision.WetCollision().
Referenced by Terraria.Graphics.Renderers.FakeFishParticle.Update().