Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.TryToMagnetizeTo
TryToMagnetizeTo()
bool Terraria.Graphics.Renderers.FakeFishParticle.TryToMagnetizeTo (Projectile projectile, int requiredItemType = -1) inline
Definition at line 40 of file FakeFishParticle.cs.
        {
            if (!this.CanHit(projectile, requiredItemType, 80f))
            {
                return false;
            }
            this._latchedProjectile = projectile;
            this._latchedProjectileType = projectile.type;
            this._state = FakeFishParticle.State.Latched;
            Vector2 vector;
            Vector2 vector2;
            this.SetAndGetLatchDetails(out vector, out vector2);
            this.Rotate(true);
            return true;
        }
References Terraria.Graphics.Renderers.FakeFishParticle.CanHit(), Terraria.Graphics.Renderers.FakeFishParticle.Rotate(), Terraria.Graphics.Renderers.FakeFishParticle.SetAndGetLatchDetails(), and Terraria.Projectile.type.