Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.ShowOptionDescription
ShowOptionDescription()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ShowOptionDescription (UIMouseEvent evt, UIElement listeningElement) inline
Definition at line 478 of file AWorkshopPublishInfoState.cs.
        {
            LocalizedText localizedText = null;
            GroupOptionButton<WorkshopItemPublicSettingId> groupOptionButton = listeningElement as GroupOptionButton<WorkshopItemPublicSettingId>;
            if (groupOptionButton != null)
            {
                localizedText = groupOptionButton.Description;
            }
            UICharacterNameButton uicharacterNameButton = listeningElement as UICharacterNameButton;
            if (uicharacterNameButton != null)
            {
                localizedText = uicharacterNameButton.Description;
            }
            GroupOptionButton<bool> groupOptionButton2 = listeningElement as GroupOptionButton<bool>;
            if (groupOptionButton2 != null)
            {
                localizedText = groupOptionButton2.Description;
            }
            GroupOptionButton<WorkshopTagOption> groupOptionButton3 = listeningElement as GroupOptionButton<WorkshopTagOption>;
            if (groupOptionButton3 != null)
            {
                localizedText = groupOptionButton3.Description;
            }
            if (listeningElement == this._steamDisclaimerButton)
            {
                localizedText = Language.GetText("Workshop.SteamDisclaimerDescrpition");
            }
            if (localizedText != null)
            {
                this._descriptionText.SetText(localizedText);
            }
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._descriptionText, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._steamDisclaimerButton, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.Description, Terraria.GameContent.UI.Elements.UICharacterNameButton.Description, Terraria.Localization.Language.GetText(), and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.steamDisclaimerText_OnMouseOver().