Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.Update
Update()
void Terraria.Graphics.Renderers.FakeFishParticle.Update (ref ParticleRendererSettings settings) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 241 of file FakeFishParticle.cs.
        {
            int num = this._delayTime;
            this._delayTime = num - 1;
            if (num >= 0)
            {
                return;
            }
            num = this._lifeTimeCounted + 1;
            this._lifeTimeCounted = num;
            if (num >= this._lifeTimeTotal)
            {
                this.ShouldBeRemovedFromRenderer = true;
            }
            num = this._sonarTimeleft - 1;
            this._sonarTimeleft = num;
            if (num < 0)
            {
                this._sonarTimeleft = 0;
            }
            bool flag = Collision.WetCollision(this.Position, 2, 2);
            if (flag != this._wasWet)
            {
                this.EmitWaterPulse();
            }
            this._wasWet = flag;
            if (this._state == FakeFishParticle.State.Jumping)
            {
                this.Velocity.Y = this.Velocity.Y + 0.2f;
                this.Rotation = this.Velocity.ToRotation();
                this.Position += this.Velocity;
                num = this._jumpTimeLeft - 1;
                this._jumpTimeLeft = num;
                if (num > 0)
                {
                    return;
                }
                this._state = FakeFishParticle.State.FreeRoaming;
                this.PickNewVelocity();
                this.Velocity *= 0.15f;
            }
            if ((float)this._lifeTimeCounted / (float)this._lifeTimeTotal >= 0.15f && this.Velocity.Length() < 0.1f)
            {
                num = this._waitTime - 1;
                this._waitTime = num;
                if (num <= 0)
                {
                    this._waitTime = Main.rand.Next(30, 121);
                    this.PickNewVelocity();
                    this._steerTime = Main.rand.Next(30, 121);
                }
            }
            num = this._steerTime - 1;
            this._steerTime = num;
            if (num > 0)
            {
                this.Velocity = Vector2.Lerp(this.Velocity, this.Rotation.ToRotationVector2() * 1f, 0.033333335f);
                this.Velocity = Vector2.Lerp(this.Velocity, this._targetVelocity, 0.05f);
            }
            else if (this.Velocity.Length() > 0.3f)
            {
                this.Velocity *= 0.975f;
            }
            if (this._state == FakeFishParticle.State.InterestedInBobber && this.Position.Distance(this._bobberLocation) < 16f)
            {
                this.Velocity *= 0.9f;
                if (this.Velocity.Length() < 0.02f)
                {
                    float num2 = 0.3f + 1.4f * Main.rand.NextFloat();
                    this.Velocity = (this._bobberLocation - this.Position).SafeNormalize(Vector2.Zero) * -num2;
                }
            }
            this.CheckLatch();
            if (this._state == FakeFishParticle.State.Latched)
            {
                Vector2 vector;
                Vector2 vector2;
                this.SetAndGetLatchDetails(out vector, out vector2);
                this.Position = Vector2.Lerp(this.Position, vector - vector2, 0.05f);
            }
            this.Position += this.Velocity;
            this.Rotate(false);
            int num3 = 20;
            if (this._lifeTimeTotal - this._lifeTimeCounted > num3 && !flag)
            {
                this._lifeTimeCounted = this._lifeTimeTotal - num3;
            }
            if (this.Velocity.Y < 0f && !Collision.WetCollision(this.Position + new Vector2(0f, -20f), 0, 0))
            {
                this._steerTime = 0;
                this.Velocity.Y = this.Velocity.Y * 0.92f;
            }
            if (this.Velocity != Vector2.Zero && !Collision.WetCollision(this.Position + this.Velocity.SafeNormalize(Vector2.Zero) * 32f, 0, 0))
            {
                this._steerTime = 0;
                this.PickNewVelocity();
                this.Velocity *= 0.92f;
            }
            if (this.Velocity != Vector2.Zero)
            {
                for (float num4 = 0f; num4 < 1f; num4 += 0.25f)
                {
                    Vector2 vector3 = (6.2831855f * num4).ToRotationVector2() * 16f;
                    if (Vector2.Dot(vector3, this.Velocity.SafeNormalize(Vector2.UnitY)) >= 0f && !Collision.WetCollision(this.Position + vector3, 0, 0))
                    {
                        this._steerTime = 0;
                        this.PickNewVelocity();
                        this.Velocity *= 0.92f;
                        return;
                    }
                }
            }
        }
References Terraria.Graphics.Renderers.FakeFishParticle._delayTime, Terraria.Graphics.Renderers.FakeFishParticle._lifeTimeCounted, Terraria.Graphics.Renderers.FakeFishParticle._lifeTimeTotal, Terraria.Graphics.Renderers.FakeFishParticle._state, Terraria.Graphics.Renderers.FakeFishParticle._targetVelocity, Terraria.Graphics.Renderers.FakeFishParticle._wasWet, Terraria.Graphics.Renderers.FakeFishParticle.CheckLatch(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Graphics.Renderers.FakeFishParticle.EmitWaterPulse(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Graphics.Renderers.FakeFishParticle.PickNewVelocity(), Terraria.Graphics.Renderers.FakeFishParticle.Position, Terraria.Main.rand, Terraria.Graphics.Renderers.FakeFishParticle.Rotate(), Terraria.Graphics.Renderers.FakeFishParticle.Rotation, Terraria.Graphics.Renderers.FakeFishParticle.SetAndGetLatchDetails(), Microsoft.Xna.Framework.Vector2.UnitY, Terraria.Graphics.Renderers.FakeFishParticle.Velocity, Terraria.Collision.WetCollision(), Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.