Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 779 of file AWorkshopPublishInfoState.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            int num2 = num;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            this._helper.RemovePointsOutOfView(snapPoints, this._listContainer, spriteBatch);
            UILinkPoint linkPoint = this._helper.GetLinkPoint(num2++, this._backButton);
            UILinkPoint linkPoint2 = this._helper.GetLinkPoint(num2++, this._publishButton);
            SnapPoint snapPoint = null;
            SnapPoint snapPoint2 = null;
            for (int i = 0; i < snapPoints.Count; i++)
            {
                SnapPoint snapPoint3 = snapPoints[i];
                string name = snapPoint3.Name;
                if (!(name == "disclaimer"))
                {
                    if (name == "image")
                    {
                        snapPoint2 = snapPoint3;
                    }
                }
                else
                {
                    snapPoint = snapPoint3;
                }
            }
            UILinkPoint uilinkPoint = this._helper.TryMakeLinkPoint(ref num2, snapPoint);
            UILinkPoint uilinkPoint2 = this._helper.TryMakeLinkPoint(ref num2, snapPoint2);
            this._helper.PairLeftRight(linkPoint, linkPoint2);
            this._helper.PairUpDown(uilinkPoint, uilinkPoint2);
            UILinkPoint[] array = this._helper.CreateUILinkStripHorizontal(ref num2, snapPoints.Where((SnapPoint x) => x.Name == "public").ToList<SnapPoint>());
            if (array.Length != 0)
            {
                this._helper.LinkHorizontalStripUpSideToSingle(array, uilinkPoint2);
            }
            UILinkPoint uilinkPoint3 = ((array.Length != 0) ? array[0] : null);
            UILinkPoint uilinkPoint4 = linkPoint;
            List<SnapPoint> list = snapPoints.Where((SnapPoint x) => x.Name == "tags").ToList<SnapPoint>();
            UILinkPoint[,] array2 = this._helper.CreateUILinkPointGrid(ref num2, list, 3, uilinkPoint3, null, null, uilinkPoint4);
            int num3 = array2.GetLength(1) - 1;
            if (num3 >= 0)
            {
                this._helper.LinkHorizontalStripBottomSideToSingle(array, array2[0, 0]);
                for (int j = array2.GetLength(0) - 1; j >= 0; j--)
                {
                    if (array2[j, num3] != null)
                    {
                        this._helper.PairUpDown(array2[j, num3], linkPoint2);
                        break;
                    }
                }
            }
            UILinkPoint uilinkPoint5 = UILinkPointNavigator.Points[num2 - 1];
            this._helper.PairUpDown(uilinkPoint5, linkPoint);
            this._helper.MoveToVisuallyClosestPoint(num, num2);
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._backButton, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._helper, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._listContainer, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._publishButton, System.array, System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkPointGrid(), Terraria.GameContent.UI.States.UIGamepadHelper.CreateUILinkStripHorizontal(), Terraria.GameContent.UI.States.UIGamepadHelper.GetLinkPoint(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkHorizontalStripBottomSideToSingle(), Terraria.GameContent.UI.States.UIGamepadHelper.LinkHorizontalStripUpSideToSingle(), System.list, Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), System.name, Terraria.UI.SnapPoint.Name, Terraria.GameContent.UI.States.UIGamepadHelper.PairLeftRight(), Terraria.GameContent.UI.States.UIGamepadHelper.PairUpDown(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.GameContent.UI.States.UIGamepadHelper.RemovePointsOutOfView(), and Terraria.GameContent.UI.States.UIGamepadHelper.TryMakeLinkPoint().
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.Draw().