Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.Draw
Draw()
void Terraria.Graphics.Renderers.FakeFishParticle.Draw (ref ParticleRendererSettings settings, SpriteBatch spritebatch) inline
Implements Terraria.Graphics.Renderers.IParticle.
Definition at line 449 of file FakeFishParticle.cs.
        {
            Main.instance.LoadItem(this._itemInstance.type);
            float num = (float)this._lifeTimeCounted / (float)this._lifeTimeTotal;
            float num2 = Utils.Remap(num, 0.1f, 0.5f, 0f, 0.85f, true);
            num2 = Utils.Remap(num, 0.5f, 0.9f, num2, 1f, true);
            Vector2 vector = settings.AnchorPosition + this.Position;
            float num3 = Utils.Remap(num, 0f, 0.25f, 0f, 1f, true) * Utils.Remap(num, 0.85f, 1f, 1f, 0f, true);
            Vector2 vector2 = new Vector2(this._itemInstance.scale * this._totalScale);
            Vector2 vector3 = (6.2831855f * num * 6f).ToRotationVector2();
            vector2.X += vector3.Y * 0.014f;
            vector2.Y += vector3.X * 0.012f;
            float num4 = this.Rotation;
            if (this._itemLooksDiagonal)
            {
                num4 += 0.7853982f;
            }
            SpriteEffects spriteEffects = SpriteEffects.None;
            Vector2 vector4 = this.Velocity;
            if (this._itemLooksDiagonal)
            {
                if (this._state == FakeFishParticle.State.InterestedInBobber)
                {
                    vector4 = this._targetVelocity;
                }
                else if (this._state == FakeFishParticle.State.Latched)
                {
                    vector4 = this._targetVelocity;
                }
            }
            if (vector4.X < 0f)
            {
                spriteEffects = SpriteEffects.FlipVertically;
                if (this._itemLooksDiagonal)
                {
                    num4 -= 1.5707964f;
                }
            }
            Texture2D texture2D;
            Rectangle rectangle;
            Rectangle rectangle2;
            Main.instance.DrawItem_GetBasics(this._itemInstance, 0, out texture2D, out rectangle, out rectangle2);
            Color color = Color.Lerp(Color.White, Color.Black, 0.8f) * 0.7f;
            if (this._sonarStartTime > 0 && this._sonarTimeleft <= this._sonarStartTime && this._sonarTimeleft > 0)
            {
                float num5 = 1f - (float)this._sonarTimeleft / (float)this._sonarStartTime;
                float num6 = Utils.Remap(num5, 0f, 0.2f, 0f, 1f, true) * Utils.Remap(num5, 0.2f, 1f, 1f, 0f, true);
                color = Color.Lerp(color, Color.White, this._isSelectedSonarType ? num6 : (num6 * 0.4f));
                Color color2 = this._sonarColor * num6 * num3;
                for (float num7 = 0f; num7 < 6.2831855f; num7 += 1.5707964f)
                {
                    spritebatch.Draw(texture2D, vector + (num7 + num4).ToRotationVector2() * 2f * vector2, new Rectangle?(rectangle), color2, num4, rectangle.Size() / 2f, vector2, spriteEffects, 0f);
                }
            }
            spritebatch.Draw(texture2D, vector, new Rectangle?(rectangle), color * num3, num4, rectangle.Size() / 2f, vector2, spriteEffects, 0f);
            if (this._itemInstance.glowMask != -1)
            {
                spritebatch.Draw(TextureAssets.GlowMask[(int)this._itemInstance.glowMask].Value, vector, new Rectangle?(rectangle2), Color.Lerp(Color.White, Color.Black, 0.8f) * num3 * 0.7f, num4, rectangle2.Size() / 2f, vector2, spriteEffects, 0f);
            }
        }
References Terraria.Graphics.Renderers.FakeFishParticle._itemInstance, Terraria.Graphics.Renderers.FakeFishParticle._itemLooksDiagonal, Terraria.Graphics.Renderers.FakeFishParticle._lifeTimeCounted, Terraria.Graphics.Renderers.FakeFishParticle._lifeTimeTotal, Terraria.Graphics.Renderers.FakeFishParticle._sonarStartTime, Terraria.Graphics.Renderers.FakeFishParticle._sonarTimeleft, Terraria.Graphics.Renderers.FakeFishParticle._state, Terraria.Graphics.Renderers.FakeFishParticle._targetVelocity, Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.DrawItem_GetBasics(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Item.glowMask, Terraria.Main.instance, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.LoadItem(), Terraria.Graphics.Renderers.FakeFishParticle.Position, Terraria.Utils.Remap(), Terraria.Graphics.Renderers.FakeFishParticle.Rotation, Terraria.Item.scale, Terraria.Item.type, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Graphics.Renderers.FakeFishParticle.Velocity, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.X.