Terraria Decompiled: Terraria.Graphics.Renderers.FakeFishParticle.Prepare
Prepare()
void Terraria.Graphics.Renderers.FakeFishParticle.Prepare (int itemType, int lifeTimeTotal, Vector2 bobberLocation) inline
Definition at line 414 of file FakeFishParticle.cs.
        {
            this._itemInstance.SetDefaults(itemType, null);
            this._totalScale = 0.6f + 0.15f * Main.rand.NextFloat();
            this._bobberLocation = bobberLocation + new Vector2(0f, 8f);
            this._isInanimate = false;
            this._lifeTimeTotal = lifeTimeTotal;
            this._state = ((Main.rand.Next(3) != 0) ? FakeFishParticle.State.InterestedInBobber : FakeFishParticle.State.FreeRoaming);
            this._itemLooksDiagonal = ItemID.Sets.ReceivesDiagonalCorrectionAsFakeFish[itemType];
            if (ItemID.Sets.IsFishingCrate[itemType] || ItemID.Sets.FakeFishInanimate[itemType])
            {
                this._state = FakeFishParticle.State.FreeRoaming;
                this._isInanimate = true;
                this._itemLooksDiagonal = false;
            }
            this.PickNewVelocity();
            this._steerTime = Main.rand.Next(30, 121);
            this._wasWet = true;
            this._delayTime = 0;
        }
References Terraria.Graphics.Renderers.FakeFishParticle._itemInstance, Terraria.ID.ItemID.Sets.FakeFishInanimate, Terraria.ID.ItemID.Sets.IsFishingCrate, Terraria.Graphics.Renderers.FakeFishParticle.PickNewVelocity(), Terraria.Main.rand, Terraria.ID.ItemID.Sets.ReceivesDiagonalCorrectionAsFakeFish, Terraria.Item.SetDefaults(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_FakeFish().