Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.UpdateImagePreview
UpdateImagePreview()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview () inline private
Definition at line 725 of file AWorkshopPublishInfoState.cs.
        {
            Texture2D texture2D = null;
            string text = this.PrettifyPath(this._previewImagePath);
            this._previewImagePathPlate.SetContents(text);
            if (this._previewImagePath != null)
            {
                try
                {
                    using (FileStream fileStream = File.OpenRead(this._previewImagePath))
                    {
                        texture2D = Texture2D.FromStream(Main.graphics.GraphicsDevice, fileStream);
                    }
                }
                catch (Exception ex)
                {
                    FancyErrorPrinter.ShowFailedToLoadAssetError(ex, this._previewImagePath);
                }
            }
            if (texture2D != null && (texture2D.Width > 512 || texture2D.Height > 512))
            {
                object obj = new { texture2D.Width, texture2D.Height };
                string textValueWith = Language.GetTextValueWith("Workshop.ReportIssue_FailedToPublish_ImageSizeIsTooLarge", obj);
                if (SocialAPI.Workshop != null)
                {
                    SocialAPI.Workshop.IssueReporter.ReportInstantUploadProblemFromValue(textValueWith);
                }
                this._previewImagePath = null;
                this._previewImagePathPlate.SetContents(null);
                this._previewImageUIElement.SetImage(this._defaultPreviewImageTexture);
                return;
            }
            if (this._previewImageTransientTexture != null)
            {
                this._previewImageTransientTexture.Dispose();
                this._previewImageTransientTexture = null;
            }
            if (texture2D != null)
            {
                this._previewImageUIElement.SetImage(texture2D);
                this._previewImageTransientTexture = texture2D;
                return;
            }
            this._previewImageUIElement.SetImage(this._defaultPreviewImageTexture);
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._defaultPreviewImageTexture, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._previewImagePath, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._previewImagePathPlate, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._previewImageTransientTexture, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._previewImageUIElement, Microsoft.Xna.Framework.Graphics.Texture.Dispose(), Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Terraria.Localization.Language.GetTextValueWith(), Terraria.Main.graphics, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDevice, Microsoft.Xna.Framework.Graphics.Texture2D.Height, System.obj, System.IO.File.OpenRead(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.PrettifyPath(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), Terraria.GameContent.UI.Elements.UIImage.SetImage(), Terraria.UI.FancyErrorPrinter.ShowFailedToLoadAssetError(), System.text, Microsoft.Xna.Framework.Graphics.Texture2D.Width, and Terraria.Social.SocialAPI.Workshop.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OpenFileDialogueToSelectPreviewImage(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetDefaultOptions().