Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.SetTagsFromFoundEntry
SetTagsFromFoundEntry()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetTagsFromFoundEntry () inline private
Definition at line 141 of file AWorkshopPublishInfoState.cs.
        {
            FoundWorkshopEntryInfo foundWorkshopEntryInfo;
            if (!this.TryFindingTags(out foundWorkshopEntryInfo))
            {
                return;
            }
            if (foundWorkshopEntryInfo.tags != null)
            {
                foreach (GroupOptionButton<WorkshopTagOption> groupOptionButton in this._tagOptions)
                {
                    bool flag = foundWorkshopEntryInfo.tags.Contains(groupOptionButton.OptionValue.InternalNameForAPIs);
                    groupOptionButton.SetCurrentOption(flag ? groupOptionButton.OptionValue : null);
                    groupOptionButton.SetColor(groupOptionButton.IsSelected ? new Color(152, 175, 235) : Colors.InventoryDefaultColor, 1f);
                }
            }
            this._optionPublicity = foundWorkshopEntryInfo.publicity;
            GroupOptionButton<WorkshopItemPublicSettingId>[] publicityOptions = this._publicityOptions;
            for (int i = 0; i < publicityOptions.Length; i++)
            {
                publicityOptions[i].SetCurrentOption(foundWorkshopEntryInfo.publicity);
            }
        }
References Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._publicityOptions, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >._tagOptions, Terraria.ID.Colors.InventoryDefaultColor, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.IsSelected, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.OptionValue, Terraria.Social.Base.FoundWorkshopEntryInfo.publicity, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetColor(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.Social.Base.FoundWorkshopEntryInfo.tags, and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.TryFindingTags().
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.SetDefaultOptions().