Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.FillUIList
FillUIList()
void Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList (UIList uiList) inline private
Definition at line 75 of file AWorkshopPublishInfoState.cs.
        {
            UIElement uielement = new UIElement
            {
                Width = new StyleDimension(0f, 0f),
                Height = new StyleDimension(0f, 0f)
            };
            uielement.SetPadding(0f);
            uiList.Add(uielement);
            uiList.Add(this.CreateSteamDisclaimer("disclaimer"));
            uiList.Add(this.CreatePreviewImageSelectionPanel("image"));
            uiList.Add(this.CreatePublicSettingsRow(0f, 44f, "public"));
            uiList.Add(this.CreateTagOptionsPanel(0f, 44, "tags"));
        }
References Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.UI.UIElement.Height, Terraria.UI.UIElement.SetPadding(), and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize().