Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.AddUIList
AddUIList()
UIList Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList (UIElement container, float antiHeight) inline private
Definition at line 278 of file AWorkshopPublishInfoState.cs.
        {
            this._uiListContainer = container;
            float num = 0f;
            UIElement uielement = new UIElement
            {
                HAlign = 0f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(-num * 2f, 1f),
                Left = StyleDimension.FromPixels(-num),
                Height = StyleDimension.FromPixelsAndPercent(-2f - antiHeight, 1f),
                OverflowHidden = true
            };
            this._listContainer = uielement;
            UISlicedImage uislicedImage = new UISlicedImage(Main.Assets.Request<Texture2D>("Images/UI/Workshop/ListBackground", 1))
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(0f, 1f),
                Color = Color.White * 0.7f
            };
            uislicedImage.SetSliceDepths(4);
            container.Append(uielement);
            uielement.Append(uislicedImage);
            UIList uilist = new UIList
            {
                Width = StyleDimension.FromPixelsAndPercent(-10f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(-4f, 1f),
                HAlign = 0.5f,
                VAlign = 0.5f,
                OverflowHidden = true
            };
            uilist.ManualSortMethod = new Action<List<UIElement>>(this.ManualIfnoSortingMethod);
            uilist.ListPadding = 5f;
            uielement.Append(uilist);
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                HAlign = 1f,
                VAlign = 0f,
                Width = StyleDimension.FromPixelsAndPercent(-num * 2f, 1f),
                Left = StyleDimension.FromPixels(-num),
                Height = StyleDimension.FromPixelsAndPercent(-14f - antiHeight, 1f),
                Top = StyleDimension.FromPixels(6f)
            };
            uiscrollbar.SetView(100f, 1000f);
            uilist.SetScrollbar(uiscrollbar);
            this._uiListRect = uielement;
            this._scrollbar = uiscrollbar;
            return uilist;
        }
References Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ManualIfnoSortingMethod(), Terraria.UI.UIElement.OverflowHidden, Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UISlicedImage.SetSliceDepths(), Terraria.GameContent.UI.Elements.UIScrollbar.SetView(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.OnInitialize().