Terraria Decompiled: Terraria.GameContent.UI.States.AWorkshopPublishInfoState.CreatePublicSettingsRow
CreatePublicSettingsRow()
UIElement Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow (float accumulatedHeight, float height, string tagGroup) inline private
Definition at line 334 of file AWorkshopPublishInfoState.cs.
        {
            UIElement uielement;
            UIElement uielement2;
            this.CreateStylizedCategoryPanel(height, "Workshop.CategoryTitlePublicity", out uielement, out uielement2);
            WorkshopItemPublicSettingId[] array = new WorkshopItemPublicSettingId[3];
            array[0] = WorkshopItemPublicSettingId.Public;
            array[1] = WorkshopItemPublicSettingId.FriendsOnly;
            WorkshopItemPublicSettingId[] array2 = array;
            LocalizedText[] array3 = new LocalizedText[]
            {
                Language.GetText("Workshop.SettingsPublicityPublic"),
                Language.GetText("Workshop.SettingsPublicityFriendsOnly"),
                Language.GetText("Workshop.SettingsPublicityPrivate")
            };
            LocalizedText[] array4 = new LocalizedText[]
            {
                Language.GetText("Workshop.SettingsPublicityPublicDescription"),
                Language.GetText("Workshop.SettingsPublicityFriendsOnlyDescription"),
                Language.GetText("Workshop.SettingsPublicityPrivateDescription")
            };
            Color[] array5 = new Color[]
            {
                Color.White,
                Color.White,
                Color.White
            };
            string[] array6 = new string[] { "Images/UI/Workshop/PublicityPublic", "Images/UI/Workshop/PublicityFriendsOnly", "Images/UI/Workshop/PublicityPrivate" };
            float num = 0.98f;
            GroupOptionButton<WorkshopItemPublicSettingId>[] array7 = new GroupOptionButton<WorkshopItemPublicSettingId>[array2.Length];
            for (int i = 0; i < array7.Length; i++)
            {
                GroupOptionButton<WorkshopItemPublicSettingId> groupOptionButton = new GroupOptionButton<WorkshopItemPublicSettingId>(array2[i], array3[i], array4[i], array5[i], array6[i], 1f, 1f, 16f);
                groupOptionButton.Width = StyleDimension.FromPixelsAndPercent((float)(-4 * (array7.Length - 1)), 1f / (float)array7.Length * num);
                groupOptionButton.HAlign = (float)i / (float)(array7.Length - 1);
                groupOptionButton.Left = StyleDimension.FromPercent((1f - num) * (1f - groupOptionButton.HAlign * 2f));
                groupOptionButton.Top.Set(accumulatedHeight, 0f);
                groupOptionButton.OnLeftMouseDown += this.ClickPublicityOption;
                groupOptionButton.OnMouseOver += this.ShowOptionDescription;
                groupOptionButton.OnMouseOut += this.ClearOptionDescription;
                groupOptionButton.SetSnapPoint(tagGroup, i, null, null);
                uielement2.Append(groupOptionButton);
                array7[i] = groupOptionButton;
            }
            this._publicityOptions = array7;
            return uielement;
        }
References Terraria.UI.UIElement.Append(), System.array, Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ClearOptionDescription(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ClickPublicityOption(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), Terraria.UI.StyleDimension.FromPercent(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ShowOptionDescription(), Terraria.UI.UIElement.Top, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList().