Terraria Decompiled: System.Threading.ExecutionContext.Capture
Capture() [2/2]
static ExecutionContext System.Threading.ExecutionContext.Capture (ref StackCrawlMark stackMark, ExecutionContext::CaptureOptions options) inline static package
Definition at line 519 of file ExecutionContext.cs.
        {
            ExecutionContext.Reader executionContextReader = Thread.CurrentThread.GetExecutionContextReader();
            if (executionContextReader.IsFlowSuppressed)
            {
                return null;
            }
            SynchronizationContext synchronizationContext = null;
            LogicalCallContext logicalCallContext = null;
            if (!executionContextReader.IsNull)
            {
                if ((options & ExecutionContext.CaptureOptions.IgnoreSyncCtx) == ExecutionContext.CaptureOptions.None)
                {
                    synchronizationContext = ((executionContextReader.SynchronizationContext == null) ? null : executionContextReader.SynchronizationContext.CreateCopy());
                }
                if (executionContextReader.LogicalCallContext.HasInfo)
                {
                    logicalCallContext = executionContextReader.LogicalCallContext.Clone();
                }
            }
            Dictionary<IAsyncLocal, object> dictionary = null;
            List<IAsyncLocal> list = null;
            if (!executionContextReader.IsNull)
            {
                dictionary = executionContextReader.DangerousGetRawExecutionContext()._localValues;
                list = executionContextReader.DangerousGetRawExecutionContext()._localChangeNotifications;
            }
            if ((options & ExecutionContext.CaptureOptions.OptimizeDefaultCase) != ExecutionContext.CaptureOptions.None && synchronizationContext == null && (logicalCallContext == null || !logicalCallContext.HasInfo) && dictionary == null && list == null)
            {
                return ExecutionContext.s_dummyDefaultEC;
            }
            return new ExecutionContext
            {
                _syncContext = synchronizationContext,
                LogicalCallContext = logicalCallContext,
                _localValues = dictionary,
                _localChangeNotifications = list,
                isNewCapture = true
            };
        }
References System.Threading.ExecutionContext._localChangeNotifications, System.Threading.ExecutionContext._localValues, System.Threading.ExecutionContext._syncContext, System.Runtime.Remoting.Messaging.LogicalCallContext.Clone(), System.Threading.SynchronizationContext.CreateCopy(), System.Threading.Thread.CurrentThread, System.Threading.ExecutionContext.Reader.DangerousGetRawExecutionContext(), System.dictionary, System.Threading.Thread.GetExecutionContextReader(), System.Runtime.Remoting.Messaging.LogicalCallContext.HasInfo, System.Threading.ExecutionContext.Reader.IsFlowSuppressed, System.Threading.ExecutionContext.isNewCapture, System.Threading.ExecutionContext.Reader.IsNull, System.list, System.Threading.ExecutionContext.Reader.LogicalCallContext, System.options, System.Threading.ExecutionContext.s_dummyDefaultEC, and System.Threading.ExecutionContext.Reader.SynchronizationContext.