Terraria Decompiled: System.Threading.ExecutionContext.SetExecutionContext
SetExecutionContext()
static ExecutionContextSwitcher System.Threading.ExecutionContext.SetExecutionContext (ExecutionContext executionContext, bool preserveSyncCtx) inline static package
Definition at line 399 of file ExecutionContext.cs.
        {
            ExecutionContextSwitcher executionContextSwitcher = default(ExecutionContextSwitcher);
            Thread currentThread = Thread.CurrentThread;
            ExecutionContext.Reader executionContextReader = currentThread.GetExecutionContextReader();
            executionContextSwitcher.thread = currentThread;
            executionContextSwitcher.outerEC = executionContextReader;
            executionContextSwitcher.outerECBelongsToScope = currentThread.ExecutionContextBelongsToCurrentScope;
            if (preserveSyncCtx)
            {
                executionContext.SynchronizationContext = executionContextReader.SynchronizationContext;
            }
            executionContext.SynchronizationContextNoFlow = executionContextReader.SynchronizationContextNoFlow;
            currentThread.SetExecutionContext(executionContext, true);
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                ExecutionContext.OnAsyncLocalContextChanged(executionContextReader.DangerousGetRawExecutionContext(), executionContext);
            }
            catch
            {
                executionContextSwitcher.UndoNoThrow();
                throw;
            }
            return executionContextSwitcher;
        }
References System.Threading.Thread.CurrentThread, System.Threading.ExecutionContext.Reader.DangerousGetRawExecutionContext(), System.Threading.Thread.ExecutionContextBelongsToCurrentScope, System.Threading.Thread.GetExecutionContextReader(), System.Threading.ExecutionContext.OnAsyncLocalContextChanged(), System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Threading.Thread.SetExecutionContext(), System.Threading.ExecutionContext.Reader.SynchronizationContext, System.Threading.ExecutionContext.Reader.SynchronizationContextNoFlow, and System.Threading.ExecutionContextSwitcher.UndoNoThrow().
Referenced by System.Threading.ExecutionContext.RunInternal(), and System.Threading.ExecutionContext.RunInternal< TState >().