Terraria Decompiled: System.Threading.ExecutionContext.CreateCopy
CreateCopy()
ExecutionContext System.Threading.ExecutionContext.CreateCopy () inline
Definition at line 428 of file ExecutionContext.cs.
        {
            if (!this.isNewCapture)
            {
                throw new InvalidOperationException(Environment.GetResourceString("Only newly captured contexts can be copied"));
            }
            ExecutionContext executionContext = new ExecutionContext();
            executionContext.isNewCapture = true;
            executionContext._syncContext = ((this._syncContext == null) ? null : this._syncContext.CreateCopy());
            executionContext._localValues = this._localValues;
            executionContext._localChangeNotifications = this._localChangeNotifications;
            if (this._logicalCallContext != null)
            {
                executionContext.LogicalCallContext = (LogicalCallContext)this.LogicalCallContext.Clone();
            }
            return executionContext;
        }
References System.Threading.ExecutionContext._localChangeNotifications, System.Threading.ExecutionContext._localValues, System.Threading.ExecutionContext._logicalCallContext, System.Threading.ExecutionContext._syncContext, System.Runtime.Remoting.Messaging.LogicalCallContext.Clone(), System.Threading.SynchronizationContext.CreateCopy(), System.Threading.ExecutionContext.ExecutionContext(), System.Environment.GetResourceString(), System.Threading.ExecutionContext.isNewCapture, and System.Threading.ExecutionContext.LogicalCallContext.
Referenced by System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback().