Terraria Decompiled: System.Threading.ExecutionContext.Run
Run() [1/2]
static void System.Threading.ExecutionContext.Run (ExecutionContext executionContext, ContextCallback callback, object state) inline static
Definition at line 275 of file ExecutionContext.cs.
        {
            if (executionContext == null)
            {
                throw new InvalidOperationException(Environment.GetResourceString("Cannot call Set on a null context"));
            }
            if (!executionContext.isNewCapture)
            {
                throw new InvalidOperationException(Environment.GetResourceString("Cannot apply a context that has been marshaled across AppDomains, that was not acquired through a Capture operation or that has already been the argument to a Set call."));
            }
            ExecutionContext.Run(executionContext, callback, state, false);
        }
References System.Environment.GetResourceString(), System.Threading.ExecutionContext.isNewCapture, System.Threading.ExecutionContext.Run(), and System.state.
Referenced by System.Threading.CancellationCallbackInfo.ExecuteCallback(), System.Threading.Tasks.Task< TResult >.ExecuteWithThreadLocal(), System.Threading.QueueUserWorkItemCallback.ExecuteWorkItem(), System.Threading.Tasks.AwaitTaskContinuation.ExecuteWorkItem(), System.Threading._ThreadPoolWaitOrTimerCallback.PerformWaitOrTimerCallback(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.MoveNextRunner.Run(), System.Threading.ExecutionContext.Run(), System.Threading.ThreadHelper.ThreadStart(), and System.Threading.ThreadHelper.ThreadStart().