Terraria Decompiled: System.Threading.ExecutionContext.CreateMutableCopy
CreateMutableCopy()
ExecutionContext System.Threading.ExecutionContext.CreateMutableCopy () inline package
Definition at line 448 of file ExecutionContext.cs.
        {
            ExecutionContext executionContext = new ExecutionContext();
            executionContext._syncContext = this._syncContext;
            executionContext._syncContextNoFlow = this._syncContextNoFlow;
            if (this._logicalCallContext != null)
            {
                executionContext.LogicalCallContext = (LogicalCallContext)this.LogicalCallContext.Clone();
            }
            if (this._illogicalCallContext != null)
            {
                executionContext.IllogicalCallContext = this.IllogicalCallContext.CreateCopy();
            }
            executionContext._localValues = this._localValues;
            executionContext._localChangeNotifications = this._localChangeNotifications;
            executionContext.isFlowSuppressed = this.isFlowSuppressed;
            return executionContext;
        }
References System.Threading.ExecutionContext._illogicalCallContext, System.Threading.ExecutionContext._localChangeNotifications, System.Threading.ExecutionContext._localValues, System.Threading.ExecutionContext._logicalCallContext, System.Threading.ExecutionContext._syncContext, System.Threading.ExecutionContext._syncContextNoFlow, System.Runtime.Remoting.Messaging.LogicalCallContext.Clone(), System.Runtime.Remoting.Messaging.IllogicalCallContext.CreateCopy(), System.Threading.ExecutionContext.ExecutionContext(), System.Threading.ExecutionContext.isFlowSuppressed, and System.Threading.ExecutionContext.LogicalCallContext.
Referenced by System.Threading.Thread.GetMutableExecutionContext().