Terraria Decompiled: System.Threading.ExecutionContext.Capture
Capture() [1/2]
static ExecutionContext System.Threading.ExecutionContext.Capture () inline static
Definition at line 501 of file ExecutionContext.cs.
        {
            StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMyCaller;
            return ExecutionContext.Capture(ref stackCrawlMark, ExecutionContext.CaptureOptions.None);
        }
References System.Threading.ExecutionContext.Capture().
Referenced by System.Threading._ThreadPoolWaitOrTimerCallback._ThreadPoolWaitOrTimerCallback(), System.Threading.Tasks.AwaitTaskContinuation.AwaitTaskContinuation(), System.Threading.ExecutionContext.Capture(), System.Threading.ExecutionContext.FastCapture(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted(), System.Threading.QueueUserWorkItemCallback.QueueUserWorkItemCallback(), System.IO.Stream.ReadWriteTask.ReadWriteTask(), System.Threading.CancellationToken.Register(), System.Threading.Thread.Start(), and System.Threading.Tasks.Task< TResult >.TaskConstructorCore().