Terraria Decompiled: System.Threading.ExecutionContext.RunInternal< TState >
RunInternal< TState >() [2/2]
static void System.Threading.ExecutionContext.RunInternal< TState > (ExecutionContext executionContext, ContextCallback< TState > callback, ref TState state, bool preserveSyncCtx) inline static package
Definition at line 346 of file ExecutionContext.cs.
        {
            if (!executionContext.IsPreAllocatedDefault)
            {
                executionContext.isNewCapture = false;
            }
            Thread currentThread = Thread.CurrentThread;
            ExecutionContextSwitcher executionContextSwitcher = default(ExecutionContextSwitcher);
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                ExecutionContext.Reader executionContextReader = currentThread.GetExecutionContextReader();
                if ((executionContextReader.IsNull || executionContextReader.IsDefaultFTContext(preserveSyncCtx)) && executionContext.IsDefaultFTContext(preserveSyncCtx) && executionContextReader.HasSameLocalValues(executionContext))
                {
                    ExecutionContext.EstablishCopyOnWriteScope(currentThread, true, ref executionContextSwitcher);
                }
                else
                {
                    if (executionContext.IsPreAllocatedDefault)
                    {
                        executionContext = new ExecutionContext();
                    }
                    executionContextSwitcher = ExecutionContext.SetExecutionContext(executionContext, preserveSyncCtx);
                }
                callback(ref state);
            }
            finally
            {
                executionContextSwitcher.Undo();
            }
        }
References System.Threading.Thread.CurrentThread, System.Threading.ExecutionContext.EstablishCopyOnWriteScope(), System.Threading.ExecutionContext.ExecutionContext(), System.Threading.Thread.GetExecutionContextReader(), System.Threading.ExecutionContext.Reader.HasSameLocalValues(), System.Threading.ExecutionContext.IsDefaultFTContext(), System.Threading.ExecutionContext.Reader.IsDefaultFTContext(), System.Threading.ExecutionContext.Reader.IsNull, System.Threading.ExecutionContext.IsPreAllocatedDefault, System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Threading.ExecutionContext.SetExecutionContext(), System.state, and System.Threading.ExecutionContextSwitcher.Undo().