Terraria Decompiled: System.Threading.ExecutionContext.OnAsyncLocalContextChanged
OnAsyncLocalContextChanged()
static void System.Threading.ExecutionContext.OnAsyncLocalContextChanged (ExecutionContext previous, ExecutionContext current) inline static package
Definition at line 141 of file ExecutionContext.cs.
        {
            List<IAsyncLocal> list = ((previous == null) ? null : previous._localChangeNotifications);
            if (list != null)
            {
                foreach (IAsyncLocal asyncLocal in list)
                {
                    object obj = null;
                    if (previous != null && previous._localValues != null)
                    {
                        previous._localValues.TryGetValue(asyncLocal, out obj);
                    }
                    object obj2 = null;
                    if (current != null && current._localValues != null)
                    {
                        current._localValues.TryGetValue(asyncLocal, out obj2);
                    }
                    if (obj != obj2)
                    {
                        asyncLocal.OnValueChanged(obj, obj2, true);
                    }
                }
            }
            List<IAsyncLocal> list2 = ((current == null) ? null : current._localChangeNotifications);
            if (list2 != null && list2 != list)
            {
                try
                {
                    foreach (IAsyncLocal asyncLocal2 in list2)
                    {
                        object obj3 = null;
                        if (previous == null || previous._localValues == null || !previous._localValues.TryGetValue(asyncLocal2, out obj3))
{
                            object obj4 = null;
                            if (current != null && current._localValues != null)
{
                                current._localValues.TryGetValue(asyncLocal2, out obj4);
                            }
                            if (obj3 != obj4)
{
                                asyncLocal2.OnValueChanged(obj3, obj4, true);
                            }
                        }
                    }
                }
                catch (Exception ex)
                {
                    Environment.FailFast(Environment.GetResourceString("An exception was not handled in an AsyncLocal<T> notification callback."), ex);
                }
            }
        }
References System.Threading.ExecutionContext._localChangeNotifications, System.Threading.ExecutionContext._localValues, System.Environment.GetResourceString(), System.list, System.obj, System.Threading.IAsyncLocal.OnValueChanged(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Threading.ExecutionContext.SetExecutionContext(), and System.Threading.ExecutionContextSwitcher.Undo().