Terraria Decompiled: Microsoft.Xna.Framework.Media.MediaPlayer.Update
Update()
static void Microsoft.Xna.Framework.Media.MediaPlayer.Update () inline static package
Definition at line 314 of file MediaPlayer.cs.
        {
            if (MediaPlayer.Queue == null || MediaPlayer.Queue.ActiveSong == null || MediaPlayer.State != MediaState.Playing || FAudio.XNA_GetSongEnded() == 0U)
            {
                return;
            }
            MediaPlayer.numSongsInQueuePlayed++;
            if (MediaPlayer.numSongsInQueuePlayed >= MediaPlayer.Queue.Count)
            {
                MediaPlayer.numSongsInQueuePlayed = 0;
                if (!MediaPlayer.IsRepeating)
                {
                    MediaPlayer.Stop();
                    FrameworkDispatcher.ActiveSongChanged = true;
                    return;
                }
            }
            MediaPlayer.MoveNext();
        }
References Microsoft.Xna.Framework.Media.MediaQueue.ActiveSong, Microsoft.Xna.Framework.Media.MediaQueue.Count, Microsoft.Xna.Framework.Media.MediaPlayer.IsRepeating, Microsoft.Xna.Framework.Media.MediaPlayer.MoveNext(), Microsoft.Xna.Framework.Media.MediaPlayer.numSongsInQueuePlayed, Microsoft.Xna.Framework.Media.MediaPlayer.Queue, Microsoft.Xna.Framework.Media.MediaPlayer.State, Microsoft.Xna.Framework.Media.MediaPlayer.Stop(), System.U, and FAudio.XNA_GetSongEnded().
Referenced by Microsoft.Xna.Framework.FrameworkDispatcher.Update().