Terraria Decompiled: Microsoft.Xna.Framework.Media.MediaPlayer.PlaySong
PlaySong()
static void Microsoft.Xna.Framework.Media.MediaPlayer.PlaySong (Song song) inline static private
Definition at line 384 of file MediaPlayer.cs.
        {
            if (!MediaPlayer.initialized)
            {
                FAudio.XNA_SongInit();
                MediaPlayer.initialized = true;
            }
            song.Duration = TimeSpan.FromSeconds((double)FAudio.XNA_PlaySong(song.handle));
            MediaPlayer.timer.Start();
            MediaPlayer.State = MediaState.Playing;
        }
References System.TimeSpan.FromSeconds(), Microsoft.Xna.Framework.Media.Song.handle, Microsoft.Xna.Framework.Media.MediaPlayer.initialized, Microsoft.Xna.Framework.Media.MediaPlayer.timer, FAudio.XNA_PlaySong(), and FAudio.XNA_SongInit().
Referenced by Microsoft.Xna.Framework.Media.MediaPlayer.NextSong(), Microsoft.Xna.Framework.Media.MediaPlayer.Play(), and Microsoft.Xna.Framework.Media.MediaPlayer.Play().