Terraria Decompiled: Terraria.GameContent.NPCDamageTracker.NPCDamageTracker
NPCDamageTracker() [1/2]
static Terraria.GameContent.NPCDamageTracker.NPCDamageTracker () inline static private
Definition at line 38 of file NPCDamageTracker.cs.
        {
            NPCDamageTracker.RegisterMobsForBoss(50, new int[] { 1, 535 });
            NPCDamageTracker.RegisterMobsForBoss(4, new int[] { 5 });
            NPCDamageTracker.RegisterMobsForBoss(222, new int[] { 210, 211 });
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 13, 14, 15 });
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 266, 267 });
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 35, 36 });
            NPCDamageTracker.RegisterMobsForBoss(113, new int[] { 115, 116, 117, 118, 119 });
            NPCDamageTracker.RegisterMobsForBoss(657, new int[] { 658, 659, 660 });
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 126, 125 }).Name = Language.GetText("Enemies.TheTwins");
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 127, 128, 129, 130, 131 });
            NPCDamageTracker.RegisterMobsForBoss(134, new int[] { 139 });
            NPCDamageTracker.RegisterMobsForBoss(262, new int[] { 264 });
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 245, 246, 247, 248 });
            NPCDamageTracker.RegisterMobsForBoss(370, new int[] { 372, 373 });
            NPCDamageTracker.RegisterMobsForBoss(439, new int[] { 454, 455, 456, 457, 458, 459 });
            NPCDamageTracker.RegisterCompositeTypeBoss(new int[] { 398, 396, 397 }).Name = Language.GetText("Enemies.MoonLord");
        }
References Terraria.Localization.Language.GetText(), Terraria.GameContent.NPCDamageTracker.Name, Terraria.GameContent.NPCDamageTracker.RegisterCompositeTypeBoss(), and Terraria.GameContent.NPCDamageTracker.RegisterMobsForBoss().