Terraria Decompiled: Terraria.GameContent.NPCDamageTracker.AddDamageToLastAttack
AddDamageToLastAttack() [2/2]
static void Terraria.GameContent.NPCDamageTracker.AddDamageToLastAttack (NPC npc, int damage) inline static
Definition at line 120 of file NPCDamageTracker.cs.
        {
            if (!NPCDamageTracker.GetRealActiveNPC(ref npc) || npc.life <= 0)
            {
                return;
            }
            NPCDamageTracker npcdamageTracker;
            if (!NPCDamageTracker.TryGetTrackerFor(npc, out npcdamageTracker))
            {
                return;
            }
            npcdamageTracker.AddDamageToLastAttack(Math.Min(damage, npc.life));
        }
References Terraria.GameContent.NPCDamageTracker.AddDamageToLastAttack(), Terraria.GameContent.NPCDamageTracker.GetRealActiveNPC(), Terraria.NPC.life, System.Math.Min(), and Terraria.GameContent.NPCDamageTracker.TryGetTrackerFor().
Referenced by Terraria.GameContent.NPCDamageTracker.AddDamageToLastAttack(), and Terraria.NPC.AI_006_Worms().