Terraria Decompiled: Terraria.GameContent.NPCDamageTracker.GetReport
GetReport()
NetworkText Terraria.GameContent.NPCDamageTracker.GetReport (Player forPlayer = null) inline
Definition at line 303 of file NPCDamageTracker.cs.
        {
            this._list.Sort();
            int[] array = this._list.Select((NPCDamageTracker.CreditEntry x) => x.Damage).ToArray<int>();
            int[] array2 = NPCDamageTracker.CalculatePercentages(array);
            int length = array.Max().ToString().Length;
            List<NetworkText> list = new List<NetworkText>(this._list.Count + 2);
            StringBuilder stringBuilder = new StringBuilder("{0}");
            list.Add(NetworkText.FromKey("BossDamageCommand.Title", new object[] { this.Name.ToNetworkText() }));
            LocalizedText killTimeMessage = this.KillTimeMessage;
            if (killTimeMessage != null)
            {
                stringBuilder.Append("\n{1}");
                TimeSpan timeSpan = TimeSpan.FromSeconds((double)this.Duration / 60.0);
                string text = string.Format("{0}:{1:00}", (int)timeSpan.TotalMinutes, timeSpan.Seconds);
                list.Add(killTimeMessage.ToNetworkText(new object[] { text }));
            }
            for (int i = 0; i < this._list.Count; i++)
            {
                StringBuilder stringBuilder2 = new StringBuilder();
                stringBuilder2.Append(array2[i]).Append('%');
                while (stringBuilder2.Length < 6)
                {
                    stringBuilder2.Append(' ');
                }
                stringBuilder2.Append(array[i]);
                while (stringBuilder2.Length < 8 + length)
                {
                    stringBuilder2.Append(' ');
                }
                NPCDamageTracker.CreditEntry creditEntry = this._list[i];
                stringBuilder2.Append('{').Append(list.Count).Append('}');
                list.Add(creditEntry.Name);
                string text2 = stringBuilder2.ToString();
                if (forPlayer != null && creditEntry is NPCDamageTracker.PlayerCreditEntry && ((NPCDamageTracker.PlayerCreditEntry)creditEntry).PlayerName == forPlayer.name)
                {
                    text2 = "[c/FFAF00:" + text2 + "]";
                }
                stringBuilder.Append('\n').Append(text2);
            }
            string text3 = stringBuilder.ToString();
            object[] array3 = list.ToArray();
            return NetworkText.FromFormattable(text3, array3);
        }
References Terraria.GameContent.NPCDamageTracker._list, System.TimeSpan.Add(), System.Text.StringBuilder.Append(), System.array, Terraria.GameContent.NPCDamageTracker.CalculatePercentages(), Terraria.GameContent.NPCDamageTracker.Duration, Terraria.Localization.NetworkText.FromFormattable(), Terraria.Localization.NetworkText.FromKey(), System.TimeSpan.FromSeconds(), Terraria.GameContent.NPCDamageTracker.KillTimeMessage, System.length, System.Text.StringBuilder.Length, System.list, Terraria.GameContent.NPCDamageTracker.CreditEntry.Name, Terraria.GameContent.NPCDamageTracker.PlayerCreditEntry.PlayerName, System.TimeSpan.Seconds, System.text, Terraria.Localization.LocalizedText.ToNetworkText(), System.Text.StringBuilder.ToString(), and System.TimeSpan.TotalMinutes.
Referenced by Terraria.Chat.Commands.BossDamageCommand.ProcessIncomingMessage().