Terraria Decompiled: Terraria.GameContent.PlayerEyeHelper.SetStateByPlayerInfo
SetStateByPlayerInfo()
void Terraria.GameContent.PlayerEyeHelper.SetStateByPlayerInfo (Player player) inline private
Definition at line 112 of file PlayerEyeHelper.cs.
        {
            if (player.blackout || player.blind)
            {
                this.SwitchToState(PlayerEyeHelper.EyeState.IsBlind, false);
                return;
            }
            if (this._state == PlayerEyeHelper.EyeState.JustTookDamage && this._timeInState < 20)
            {
                return;
            }
            if (player.sleeping.isSleeping)
            {
                bool flag = player.itemAnimation > 0;
                this.SwitchToState(PlayerEyeHelper.EyeState.InBed, flag);
                return;
            }
            if (this.DoesPlayerCountAsModeratelyDamaged(player))
            {
                this.SwitchToState(PlayerEyeHelper.EyeState.IsModeratelyDamaged, false);
                return;
            }
            if (player.tipsy)
            {
                this.SwitchToState(PlayerEyeHelper.EyeState.IsTipsy, false);
                return;
            }
            if (player.poisoned || player.venom || player.starving)
            {
                this.SwitchToState(PlayerEyeHelper.EyeState.IsPoisoned, false);
                return;
            }
            bool flag2 = player.ZoneSandstorm || (player.ZoneSnow && Main.IsItRaining);
            if (player.behindBackWall)
            {
                flag2 = false;
            }
            if (flag2)
            {
                this.SwitchToState(PlayerEyeHelper.EyeState.InStorm, false);
                return;
            }
            this.SwitchToState(PlayerEyeHelper.EyeState.NormalBlinking, false);
        }
References Terraria.GameContent.PlayerEyeHelper._state, Terraria.Player.behindBackWall, Terraria.Player.blackout, Terraria.Player.blind, Terraria.GameContent.PlayerEyeHelper.DoesPlayerCountAsModeratelyDamaged(), Terraria.Main.IsItRaining, Terraria.Player.poisoned, Terraria.Player.sleeping, Terraria.Player.starving, Terraria.GameContent.PlayerEyeHelper.SwitchToState(), Terraria.Player.tipsy, and Terraria.Player.venom.
Referenced by Terraria.GameContent.PlayerEyeHelper.Update().