Terraria Decompiled: Microsoft.Xna.Framework.Content.ModelReader.Read
Read()
override Model Microsoft.Xna.Framework.Content.ModelReader.Read (ContentReader reader, Model existingInstance) inline package
Definition at line 36 of file ModelReader.cs.
        {
            uint num = reader.ReadUInt32();
            List<ModelBone> list = new List<ModelBone>((int)num);
            for (uint num2 = 0U; num2 < num; num2 += 1U)
            {
                string text = reader.ReadObject<string>();
                Matrix matrix = reader.ReadMatrix();
                ModelBone modelBone = new ModelBone
                {
                    Transform = matrix,
                    Index = (int)num2,
                    Name = text
                };
                list.Add(modelBone);
            }
            int num3 = 0;
            while ((long)num3 < (long)((ulong)num))
            {
                ModelBone modelBone2 = list[num3];
                int num4 = ModelReader.ReadBoneReference(reader, num);
                if (num4 != -1)
                {
                    modelBone2.Parent = list[num4];
                }
                uint num5 = reader.ReadUInt32();
                if (num5 != 0U)
                {
                    for (uint num6 = 0U; num6 < num5; num6 += 1U)
                    {
                        int num7 = ModelReader.ReadBoneReference(reader, num);
                        if (num7 != -1)
{
                            modelBone2.AddChild(list[num7]);
                        }
                    }
                }
                num3++;
            }
            List<ModelMesh> list2 = new List<ModelMesh>();
            int num8 = reader.ReadInt32();
            GraphicsDevice graphicsDevice = reader.ContentManager.GetGraphicsDevice();
            for (int i = 0; i < num8; i++)
            {
                string text2 = reader.ReadObject<string>();
                int num9 = ModelReader.ReadBoneReference(reader, num);
                BoundingSphere boundingSphere = reader.ReadBoundingSphere();
                object obj = reader.ReadObject<object>();
                int num10 = reader.ReadInt32();
                List<ModelMeshPart> parts = new List<ModelMeshPart>(num10);
                uint num11 = 0U;
                while ((ulong)num11 < (ulong)((long)num10))
                {
                    ModelMeshPart modelMeshPart;
                    if (existingInstance != null)
                    {
                        modelMeshPart = existingInstance.Meshes[i].MeshParts[(int)num11];
                    }
                    else
                    {
                        modelMeshPart = new ModelMeshPart();
                    }
                    modelMeshPart.VertexOffset = reader.ReadInt32();
                    modelMeshPart.NumVertices = reader.ReadInt32();
                    modelMeshPart.StartIndex = reader.ReadInt32();
                    modelMeshPart.PrimitiveCount = reader.ReadInt32();
                    modelMeshPart.Tag = reader.ReadObject<object>();
                    parts.Add(modelMeshPart);
                    int jj = (int)num11;
                    reader.ReadSharedResource<VertexBuffer>(delegate(VertexBuffer v)
                    {
                        parts[jj].VertexBuffer = v;
                    });
                    reader.ReadSharedResource<IndexBuffer>(delegate(IndexBuffer v)
                    {
                        parts[jj].IndexBuffer = v;
                    });
                    reader.ReadSharedResource<Effect>(delegate(Effect v)
                    {
                        parts[jj].Effect = v;
                    });
                    num11 += 1U;
                }
                if (existingInstance == null)
                {
                    ModelMesh modelMesh = new ModelMesh(graphicsDevice, parts);
                    modelMesh.Tag = obj;
                    modelMesh.Name = text2;
                    modelMesh.ParentBone = list[num9];
                    modelMesh.ParentBone.AddMesh(modelMesh);
                    modelMesh.BoundingSphere = boundingSphere;
                    list2.Add(modelMesh);
                }
            }
            if (existingInstance != null)
            {
                ModelReader.ReadBoneReference(reader, num);
                reader.ReadObject<object>();
                return existingInstance;
            }
            int num12 = ModelReader.ReadBoneReference(reader, num);
            return new Model(graphicsDevice, list, list2)
            {
                Root = list[num12],
                Tag = reader.ReadObject<object>()
            };
        }
References System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Graphics.ModelBone.AddChild(), Microsoft.Xna.Framework.Graphics.ModelBone.AddMesh(), Microsoft.Xna.Framework.Content.ContentReader.ContentManager, Microsoft.Xna.Framework.Content.ContentManager.GetGraphicsDevice(), int, System.list, long, Microsoft.Xna.Framework.Graphics.Model.Meshes, System.Name, System.obj, Microsoft.Xna.Framework.Graphics.ModelMesh.ParentBone, Microsoft.Xna.Framework.Content.ModelReader.ReadBoneReference(), Microsoft.Xna.Framework.Content.ContentReader.ReadBoundingSphere(), System.IO.BinaryReader.ReadInt32(), Microsoft.Xna.Framework.Content.ContentReader.ReadMatrix(), System.IO.BinaryReader.ReadUInt32(), System.text, and System.U.