Terraria Decompiled: Ionic.Zip.ZipFile.Zip64SeekToCentralDirectory
Zip64SeekToCentralDirectory()
static void Ionic.Zip.ZipFile.Zip64SeekToCentralDirectory (ZipFile zf) inline static private
Definition at line 2261 of file ZipFile.cs.
        {
            Stream readStream = zf.ReadStream;
            byte[] array = new byte[16];
            readStream.Seek(-40L, 1);
            readStream.Read(array, 0, 16);
            long num = BitConverter.ToInt64(array, 8);
            zf._OffsetOfCentralDirectory = uint.MaxValue;
            zf._OffsetOfCentralDirectory64 = num;
            readStream.Seek(num, 0);
            uint num2 = (uint)SharedUtilities.ReadInt(readStream);
            if (num2 != 101075792U)
            {
                throw new BadReadException(string.Format("  Bad signature (0x{0:X8}) looking for ZIP64 EoCD Record at position 0x{1:X8}", num2, readStream.Position));
            }
            readStream.Read(array, 0, 8);
            long num3 = BitConverter.ToInt64(array, 0);
            array = new byte[num3];
            readStream.Read(array, 0, array.Length);
            num = BitConverter.ToInt64(array, 36);
            readStream.Seek(num, 0);
        }
References System.array, System.Format, System.L, System.IO.Stream.Position, System.IO.Stream.Read(), Ionic.Zip.SharedUtilities.ReadInt(), Ionic.Zip.ZipFile.ReadStream, System.IO.Stream.Seek(), System.BitConverter.ToInt64(), and System.U.
Referenced by Ionic.Zip.ZipFile.ReadIntoInstance().