Terraria Decompiled: Ionic.Zip.ZipFile._InternalExtractAll
_InternalExtractAll()
void Ionic.Zip.ZipFile._InternalExtractAll (string path, bool overrideExtractExistingProperty) inline private
Definition at line 2031 of file ZipFile.cs.
        {
            bool flag = this.Verbose;
            this._inExtractAll = true;
            try
            {
                this.OnExtractAllStarted(path);
                int num = 0;
                foreach (ZipEntry zipEntry in this._entries.Values)
                {
                    if (flag)
                    {
                        this.StatusMessageTextWriter.WriteLine("\n{1,-22} {2,-8} {3,4}   {4,-8}  {0}", new object[] { "Name", "Modified", "Size", "Ratio", "Packed" });
                        this.StatusMessageTextWriter.WriteLine(new string('-', 72));
                        flag = false;
                    }
                    if (this.Verbose)
                    {
                        this.StatusMessageTextWriter.WriteLine("{1,-22} {2,-8} {3,4:F0}%   {4,-8} {0}", new object[]
{
                            zipEntry.FileName,
                            zipEntry.LastModified.ToString("yyyy-MM-dd HH:mm:ss"),
                            zipEntry.UncompressedSize,
                            zipEntry.CompressionRatio,
                            zipEntry.CompressedSize
                        });
                        if (!string.IsNullOrEmpty(zipEntry.Comment))
{
                            this.StatusMessageTextWriter.WriteLine("  Comment: {0}", zipEntry.Comment);
                        }
                    }
                    zipEntry.Password = this._Password;
                    this.OnExtractEntry(num, true, zipEntry, path);
                    if (overrideExtractExistingProperty)
                    {
                        zipEntry.ExtractExistingFile = this.ExtractExistingFile;
                    }
                    zipEntry.Extract(path);
                    num++;
                    this.OnExtractEntry(num, false, zipEntry, path);
                    if (this._extractOperationCanceled)
                    {
                        break;
                    }
                }
                if (!this._extractOperationCanceled)
                {
                    foreach (ZipEntry zipEntry2 in this._entries.Values)
                    {
                        if (zipEntry2.IsDirectory || zipEntry2.FileName.EndsWith("/"))
{
                            string text = (zipEntry2.FileName.StartsWith("/") ? Path.Combine(path, zipEntry2.FileName.Substring(1)) : Path.Combine(path, zipEntry2.FileName));
                            zipEntry2._SetTimes(text, false);
                        }
                    }
                    this.OnExtractAllCompleted(path);
                }
            }
            finally
            {
                this._inExtractAll = false;
            }
        }
References Ionic.Zip.ZipFile._entries, Ionic.Zip.ZipFile._extractOperationCanceled, Ionic.Zip.ZipFile._Password, Ionic.Zip.ZipEntry._SetTimes(), System.IO.Path.Combine(), Ionic.Zip.ZipEntry.Comment, Ionic.Zip.ZipEntry.CompressedSize, Ionic.Zip.ZipEntry.CompressionRatio, Ionic.Zip.ZipEntry.Extract(), Ionic.Zip.ZipFile.ExtractExistingFile, Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipEntry.IsDirectory, Ionic.Zip.ZipEntry.LastModified, Ionic.Zip.ZipFile.OnExtractAllCompleted(), Ionic.Zip.ZipFile.OnExtractAllStarted(), Ionic.Zip.ZipFile.OnExtractEntry(), Ionic.Zip.ZipFile.StatusMessageTextWriter, System.text, System.DateTime.ToString(), Ionic.Zip.ZipEntry.UncompressedSize, System.Collections.Generic.Dictionary< TKey, TValue >.Values, Ionic.Zip.ZipFile.Verbose, and System.IO.TextWriter.WriteLine().
Referenced by Ionic.Zip.ZipFile.ExtractAll(), and Ionic.Zip.ZipFile.ExtractAll().