Terraria Decompiled: Ionic.Zip.ZipFile.IsZipFile
IsZipFile() [3/3]
static bool Ionic.Zip.ZipFile.IsZipFile (string fileName, bool testExtract) inline static
Definition at line 2464 of file ZipFile.cs.
        {
            bool flag = false;
            try
            {
                if (!File.Exists(fileName))
                {
                    return false;
                }
                using (FileStream fileStream = File.Open(fileName, 3, 1, 3))
                {
                    flag = ZipFile.IsZipFile(fileStream, testExtract);
                }
            }
            catch (IOException)
            {
            }
            catch (ZipException)
            {
            }
            return flag;
        }
References System.IO.File.Exists(), Ionic.Zip.ZipFile.IsZipFile(), and System.IO.File.Open().