Terraria Decompiled: Ionic.Zip.ZipFile._InitInstance
_InitInstance()
void Ionic.Zip.ZipFile._InitInstance (string zipFileName, TextWriter statusMessageWriter) inline private
Definition at line 1361 of file ZipFile.cs.
        {
            this._name = zipFileName;
            this._StatusMessageTextWriter = statusMessageWriter;
            this._contentsChanged = true;
            this.AddDirectoryWillTraverseReparsePoints = true;
            this.CompressionLevel = CompressionLevel.Default;
            this._initEntriesDictionary();
            if (File.Exists(this._name))
            {
                if (this.FullScan)
                {
                    ZipFile.ReadIntoInstance_Orig(this);
                }
                else
                {
                    ZipFile.ReadIntoInstance(this);
                }
                this._fileAlreadyExists = true;
            }
        }
References Ionic.Zip.ZipFile._initEntriesDictionary(), System.IO.File.Exists(), Ionic.Zip.ZipFile.FullScan, Ionic.Zip.ZipFile.ReadIntoInstance(), and Ionic.Zip.ZipFile.ReadIntoInstance_Orig().
Referenced by Ionic.Zip.ZipFile.Initialize(), Ionic.Zip.ZipFile.ZipFile(), Ionic.Zip.ZipFile.ZipFile(), Ionic.Zip.ZipFile.ZipFile(), Ionic.Zip.ZipFile.ZipFile(), Ionic.Zip.ZipFile.ZipFile(), and Ionic.Zip.ZipFile.ZipFile().