Terraria Decompiled: Ionic.Zip.ZipFile.RemoveEntry
RemoveEntry() [2/2]
void Ionic.Zip.ZipFile.RemoveEntry (ZipEntry entry) inline
Definition at line 1474 of file ZipFile.cs.
        {
            if (entry == null)
            {
                throw new ArgumentNullException("entry");
            }
            this._entries.Remove(SharedUtilities.NormalizePathForUseInZipFile(entry.FileName));
            this._zipEntriesAsList = null;
            this._contentsChanged = true;
        }
References Ionic.Zip.ZipFile._entries, Ionic.Zip.ZipEntry.FileName, Ionic.Zip.SharedUtilities.NormalizePathForUseInZipFile(), and System.Collections.Generic.Dictionary< TKey, TValue >.Remove().
Referenced by Ionic.Zip.ZipFile.RemoveEntries(), Ionic.Zip.ZipFile.RemoveEntries(), Ionic.Zip.ZipFile.RemoveEntry(), Ionic.Zip.ZipFile.RemoveEntryForUpdate(), and Ionic.Zip.ZipFile.UpdateFile().