Terraria Decompiled: Ionic.Zip.ZipFile.ReadIntoInstance_Orig
ReadIntoInstance_Orig()
static void Ionic.Zip.ZipFile.ReadIntoInstance_Orig (ZipFile zf) inline static private
Definition at line 2332 of file ZipFile.cs.
        {
            zf.OnReadStarted();
            zf._entries = new Dictionary<string, ZipEntry>();
            if (zf.Verbose)
            {
                if (zf.Name == null)
                {
                    zf.StatusMessageTextWriter.WriteLine("Reading zip from stream...");
                }
                else
                {
                    zf.StatusMessageTextWriter.WriteLine("Reading zip {0}...", zf.Name);
                }
            }
            bool flag = true;
            ZipContainer zipContainer = new ZipContainer(zf);
            ZipEntry zipEntry;
            while ((zipEntry = ZipEntry.ReadEntry(zipContainer, flag)) != null)
            {
                if (zf.Verbose)
                {
                    zf.StatusMessageTextWriter.WriteLine("  {0}", zipEntry.FileName);
                }
                zf._entries.Add(zipEntry.FileName, zipEntry);
                flag = false;
            }
            try
            {
                Dictionary<string, object> dictionary = new Dictionary<string, object>();
                ZipEntry zipEntry2;
                while ((zipEntry2 = ZipEntry.ReadDirEntry(zf, dictionary)) != null)
                {
                    ZipEntry zipEntry3 = zf._entries[zipEntry2.FileName];
                    if (zipEntry3 != null)
                    {
                        zipEntry3._Comment = zipEntry2.Comment;
                        if (zipEntry2.IsDirectory)
{
                            zipEntry3.MarkAsDirectory();
                        }
                    }
                    dictionary.Add(zipEntry2.FileName, null);
                }
                if (zf._locEndOfCDS > 0L)
                {
                    zf.ReadStream.Seek(zf._locEndOfCDS, 0);
                }
                ZipFile.ReadCentralDirectoryFooter(zf);
                if (zf.Verbose && !string.IsNullOrEmpty(zf.Comment))
                {
                    zf.StatusMessageTextWriter.WriteLine("Zip file Comment: {0}", zf.Comment);
                }
            }
            catch (ZipException)
            {
            }
            catch (IOException)
            {
            }
            zf.OnReadCompleted();
        }
References Ionic.Zip.ZipFile._entries, Ionic.Zip.ZipFile._locEndOfCDS, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Ionic.Zip.ZipEntry.Comment, Ionic.Zip.ZipFile.Comment, System.dictionary, Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipEntry.IsDirectory, System.L, Ionic.Zip.ZipEntry.MarkAsDirectory(), Ionic.Zip.ZipFile.Name, Ionic.Zip.ZipFile.OnReadCompleted(), Ionic.Zip.ZipFile.OnReadStarted(), Ionic.Zip.ZipFile.ReadCentralDirectoryFooter(), Ionic.Zip.ZipEntry.ReadDirEntry(), Ionic.Zip.ZipEntry.ReadEntry(), Ionic.Zip.ZipFile.ReadStream, System.IO.Stream.Seek(), Ionic.Zip.ZipFile.StatusMessageTextWriter, Ionic.Zip.ZipFile.Verbose, and System.IO.TextWriter.WriteLine().
Referenced by Ionic.Zip.ZipFile._InitInstance(), and Ionic.Zip.ZipFile.ReadIntoInstance().