Terraria Decompiled: Ionic.Zip.ZipFile.RemoveTempFile
RemoveTempFile()
void Ionic.Zip.ZipFile.RemoveTempFile () inline private
Definition at line 2686 of file ZipFile.cs.
        {
            try
            {
                if (File.Exists(this._temporaryFileName))
                {
                    File.Delete(this._temporaryFileName);
                }
            }
            catch (IOException ex)
            {
                if (this.Verbose)
                {
                    this.StatusMessageTextWriter.WriteLine("ZipFile::Save: could not delete temp file: {0}.", ex.Message);
                }
            }
        }
References Ionic.Zip.ZipFile._temporaryFileName, System.IO.File.Delete(), System.IO.File.Exists(), System.Exception.Message, Ionic.Zip.ZipFile.StatusMessageTextWriter, Ionic.Zip.ZipFile.Verbose, and System.IO.TextWriter.WriteLine().
Referenced by Ionic.Zip.ZipFile.CleanupAfterSaveOperation().