Terraria Decompiled: Ionic.Zip.ZipFile.Save
Save() [3/3]
void Ionic.Zip.ZipFile.Save (string fileName) inline
Definition at line 2729 of file ZipFile.cs.
        {
            if (this._name == null)
            {
                this._writestream = null;
            }
            else
            {
                this._readName = this._name;
            }
            this._name = fileName;
            if (Directory.Exists(this._name))
            {
                throw new ZipException("Bad Directory", new ArgumentException("That name specifies an existing directory. Please specify a filename.", "fileName"));
            }
            this._contentsChanged = true;
            this._fileAlreadyExists = File.Exists(this._name);
            this.Save();
        }
References Ionic.Zip.ZipFile._name, System.IO.Directory.Exists(), System.IO.File.Exists(), and Ionic.Zip.ZipFile.Save().