Terraria Decompiled: Ionic.Zip.ZipFile.CleanupAfterSaveOperation
CleanupAfterSaveOperation()
void Ionic.Zip.ZipFile.CleanupAfterSaveOperation () inline private
Definition at line 2705 of file ZipFile.cs.
        {
            if (this._name != null)
            {
                if (this._writestream != null)
                {
                    try
                    {
                        this._writestream.Close();
                    }
                    catch (IOException)
                    {
                    }
                }
                this._writestream = null;
                if (this._temporaryFileName != null)
                {
                    this.RemoveTempFile();
                    this._temporaryFileName = null;
                }
            }
        }
References Ionic.Zip.ZipFile._name, Ionic.Zip.ZipFile._temporaryFileName, Ionic.Zip.ZipFile._writestream, System.IO.Stream.Close(), and Ionic.Zip.ZipFile.RemoveTempFile().
Referenced by Ionic.Zip.ZipFile.Save().