Terraria Decompiled: Ionic.Zip.ZipFile.OnReadCompleted
OnReadCompleted()
void Ionic.Zip.ZipFile.OnReadCompleted () inline private
Definition at line 1734 of file ZipFile.cs.
        {
            EventHandler<ReadProgressEventArgs> readProgress = this.ReadProgress;
            if (readProgress != null)
            {
                ReadProgressEventArgs readProgressEventArgs = ReadProgressEventArgs.Completed(this.ArchiveNameForEvent);
                readProgress.Invoke(this, readProgressEventArgs);
            }
        }
References Ionic.Zip.ZipFile.ArchiveNameForEvent, Ionic.Zip.ReadProgressEventArgs.Completed(), and Ionic.Zip.ZipFile.ReadProgress.
Referenced by Ionic.Zip.ZipFile.ReadCentralDirectory(), and Ionic.Zip.ZipFile.ReadIntoInstance_Orig().