Terraria Decompiled: Ionic.Zip.ZipFile.Reset
Reset()
void Ionic.Zip.ZipFile.Reset (bool whileSaving) inline package
Definition at line 1244 of file ZipFile.cs.
        {
            if (this._JustSaved)
            {
                using (ZipFile zipFile = new ZipFile())
                {
                    zipFile._readName = (zipFile._name = (whileSaving ? (this._readName ?? this._name) : this._name));
                    zipFile.AlternateEncoding = this.AlternateEncoding;
                    zipFile.AlternateEncodingUsage = this.AlternateEncodingUsage;
                    ZipFile.ReadIntoInstance(zipFile);
                    foreach (ZipEntry zipEntry in zipFile)
                    {
                        foreach (ZipEntry zipEntry2 in this)
{
                            if (zipEntry.FileName == zipEntry2.FileName)
{
                                zipEntry2.CopyMetaData(zipEntry);
                                break;
                            }
                        }
                    }
                }
                this._JustSaved = false;
            }
        }
References Ionic.Zip.ZipFile._JustSaved, Ionic.Zip.ZipFile._name, Ionic.Zip.ZipFile.AlternateEncoding, Ionic.Zip.ZipFile.AlternateEncodingUsage, Ionic.Zip.ZipEntry.CopyMetaData(), Ionic.Zip.ZipEntry.FileName, Ionic.Zip.ZipFile.ReadIntoInstance(), and Ionic.Zip.ZipFile.ZipFile().
Referenced by Ionic.Zip.ZipEntry.InternalExtract(), and Ionic.Zip.ZipFile.Save().