Terraria Decompiled: Ionic.Zip.ZipFile.CheckZip
CheckZip() [2/2]
static bool Ionic.Zip.ZipFile.CheckZip (string zipFileName, bool fixIfNecessary, TextWriter writer) inline static
Definition at line 498 of file ZipFile.cs.
        {
            ZipFile zipFile = null;
            ZipFile zipFile2 = null;
            bool flag = true;
            try
            {
                zipFile = new ZipFile();
                zipFile.FullScan = true;
                zipFile.Initialize(zipFileName);
                zipFile2 = ZipFile.Read(zipFileName);
                foreach (ZipEntry zipEntry in zipFile)
                {
                    foreach (ZipEntry zipEntry2 in zipFile2)
                    {
                        if (zipEntry.FileName == zipEntry2.FileName)
{
                            if (zipEntry._RelativeOffsetOfLocalHeader != zipEntry2._RelativeOffsetOfLocalHeader)
{
                                flag = false;
                                if (writer != null)
{
                                    writer.WriteLine("{0}: mismatch in RelativeOffsetOfLocalHeader  (0x{1:X16} != 0x{2:X16})", new object[] { zipEntry.FileName, zipEntry._RelativeOffsetOfLocalHeader, zipEntry2._RelativeOffsetOfLocalHeader });
                                }
                            }
                            if (zipEntry._CompressedSize != zipEntry2._CompressedSize)
{
                                flag = false;
                                if (writer != null)
{
                                    writer.WriteLine("{0}: mismatch in CompressedSize  (0x{1:X16} != 0x{2:X16})", new object[] { zipEntry.FileName, zipEntry._CompressedSize, zipEntry2._CompressedSize });
                                }
                            }
                            if (zipEntry._UncompressedSize != zipEntry2._UncompressedSize)
{
                                flag = false;
                                if (writer != null)
{
                                    writer.WriteLine("{0}: mismatch in UncompressedSize  (0x{1:X16} != 0x{2:X16})", new object[] { zipEntry.FileName, zipEntry._UncompressedSize, zipEntry2._UncompressedSize });
                                }
                            }
                            if (zipEntry.CompressionMethod != zipEntry2.CompressionMethod)
{
                                flag = false;
                                if (writer != null)
{
                                    writer.WriteLine("{0}: mismatch in CompressionMethod  (0x{1:X4} != 0x{2:X4})", new object[] { zipEntry.FileName, zipEntry.CompressionMethod, zipEntry2.CompressionMethod });
                                }
                            }
                            if (zipEntry.Crc == zipEntry2.Crc)
{
                                break;
                            }
                            flag = false;
                            if (writer != null)
{
                                writer.WriteLine("{0}: mismatch in Crc32  (0x{1:X4} != 0x{2:X4})", new object[] { zipEntry.FileName, zipEntry.Crc, zipEntry2.Crc });
                                break;
                            }
                            break;
                        }
                    }
                }
                zipFile2.Dispose();
                zipFile2 = null;
                if (!flag && fixIfNecessary)
                {
                    string text = Path.GetFileNameWithoutExtension(zipFileName);
                    text = string.Format("{0}_fixed.zip", text);
                    zipFile.Save(text);
                }
            }
            finally
            {
                if (zipFile != null)
                {
                    zipFile.Dispose();
                }
                if (zipFile2 != null)
                {
                    zipFile2.Dispose();
                }
            }
            return flag;
        }
References Ionic.Zip.ZipEntry._CompressedSize, Ionic.Zip.ZipEntry._RelativeOffsetOfLocalHeader, Ionic.Zip.ZipEntry._UncompressedSize, Ionic.Zip.ZipEntry.CompressionMethod, Ionic.Zip.ZipEntry.Crc, Ionic.Zip.ZipFile.Dispose(), Ionic.Zip.ZipEntry.FileName, System.IO.Path.GetFileNameWithoutExtension(), Ionic.Zip.ZipFile.Initialize(), Ionic.Zip.ZipFile.Read(), System.text, System.IO.TextWriter.WriteLine(), and Ionic.Zip.ZipFile.ZipFile().