Terraria Decompiled: Ionic.Zip.ZipFile.RemoveEntryForUpdate
RemoveEntryForUpdate()
void Ionic.Zip.ZipFile.RemoveEntryForUpdate (string entryName) inline private
Definition at line 322 of file ZipFile.cs.
        {
            if (string.IsNullOrEmpty(entryName))
            {
                throw new ArgumentNullException("entryName");
            }
            string text = null;
            if (entryName.IndexOf('\\') != -1)
            {
                text = Path.GetDirectoryName(entryName);
                entryName = Path.GetFileName(entryName);
            }
            string text2 = ZipEntry.NameInArchive(entryName, text);
            if (this[text2] != null)
            {
                this.RemoveEntry(text2);
            }
        }
References System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), Ionic.Zip.ZipEntry.NameInArchive(), Ionic.Zip.ZipFile.RemoveEntry(), and System.text.
Referenced by Ionic.Zip.ZipFile.UpdateEntry(), Ionic.Zip.ZipFile.UpdateEntry(), Ionic.Zip.ZipFile.UpdateEntry(), Ionic.Zip.ZipFile.UpdateEntry(), and Ionic.Zip.ZipFile.UpdateEntry().