Terraria Decompiled: Ionic.Zip.ZipFile.ReadCentralDirectory
ReadCentralDirectory()
static void Ionic.Zip.ZipFile.ReadCentralDirectory (ZipFile zf) inline static private
Definition at line 2291 of file ZipFile.cs.
        {
            bool flag = false;
            Dictionary<string, object> dictionary = new Dictionary<string, object>();
            ZipEntry zipEntry;
            while ((zipEntry = ZipEntry.ReadDirEntry(zf, dictionary)) != null)
            {
                zipEntry.ResetDirEntry();
                zf.OnReadEntry(true, null);
                if (zf.Verbose)
                {
                    zf.StatusMessageTextWriter.WriteLine("entry {0}", zipEntry.FileName);
                }
                zf._entries.Add(zipEntry.FileName, zipEntry);
                if (zipEntry._InputUsesZip64)
                {
                    flag = true;
                }
                dictionary.Add(zipEntry.FileName, null);
            }
            if (flag)
            {
                zf.UseZip64WhenSaving = Zip64Option.Always;
            }
            if (zf._locEndOfCDS > 0L)
            {
                zf.ReadStream.Seek(zf._locEndOfCDS, 0);
            }
            ZipFile.ReadCentralDirectoryFooter(zf);
            if (zf.Verbose && !string.IsNullOrEmpty(zf.Comment))
            {
                zf.StatusMessageTextWriter.WriteLine("Zip file Comment: {0}", zf.Comment);
            }
            if (zf.Verbose)
            {
                zf.StatusMessageTextWriter.WriteLine("read in {0} entries.", zf._entries.Count);
            }
            zf.OnReadCompleted();
        }
References Ionic.Zip.ZipFile._entries, Ionic.Zip.ZipEntry._InputUsesZip64, Ionic.Zip.ZipFile._locEndOfCDS, System.Collections.Generic.Dictionary< TKey, TValue >.Add(), Ionic.Zip.ZipFile.Comment, System.Collections.Generic.Dictionary< TKey, TValue >.Count, System.dictionary, Ionic.Zip.ZipEntry.FileName, System.L, Ionic.Zip.ZipFile.OnReadCompleted(), Ionic.Zip.ZipFile.OnReadEntry(), Ionic.Zip.ZipFile.ReadCentralDirectoryFooter(), Ionic.Zip.ZipEntry.ReadDirEntry(), Ionic.Zip.ZipFile.ReadStream, Ionic.Zip.ZipEntry.ResetDirEntry(), System.IO.Stream.Seek(), Ionic.Zip.ZipFile.StatusMessageTextWriter, Ionic.Zip.ZipFile.Verbose, and System.IO.TextWriter.WriteLine().
Referenced by Ionic.Zip.ZipFile.ReadIntoInstance().