Terraria Decompiled: Ionic.Zip.ZipFile.OnReadBytes
OnReadBytes()
void Ionic.Zip.ZipFile.OnReadBytes (ZipEntry entry) inline package
Definition at line 1745 of file ZipFile.cs.
        {
            EventHandler<ReadProgressEventArgs> readProgress = this.ReadProgress;
            if (readProgress != null)
            {
                ReadProgressEventArgs readProgressEventArgs = ReadProgressEventArgs.ByteUpdate(this.ArchiveNameForEvent, entry, this.ReadStream.Position, this.LengthOfReadStream);
                readProgress.Invoke(this, readProgressEventArgs);
            }
        }
References Ionic.Zip.ZipFile.ArchiveNameForEvent, Ionic.Zip.ReadProgressEventArgs.ByteUpdate(), System.IO.Stream.Position, Ionic.Zip.ZipFile.ReadProgress, and Ionic.Zip.ZipFile.ReadStream.
Referenced by Ionic.Zip.ZipEntry.ReadEntry(), and Ionic.Zip.ZipEntry.ReadHeader().