Terraria Decompiled: Ionic.Zip.ZipFile.OnReadEntry
OnReadEntry()
void Ionic.Zip.ZipFile.OnReadEntry (bool before, ZipEntry entry) inline package
Definition at line 1756 of file ZipFile.cs.
        {
            EventHandler<ReadProgressEventArgs> readProgress = this.ReadProgress;
            if (readProgress != null)
            {
                ReadProgressEventArgs readProgressEventArgs = (before ? ReadProgressEventArgs.Before(this.ArchiveNameForEvent, this._entries.Count) : ReadProgressEventArgs.After(this.ArchiveNameForEvent, entry, this._entries.Count));
                readProgress.Invoke(this, readProgressEventArgs);
            }
        }
References Ionic.Zip.ZipFile._entries, Ionic.Zip.ReadProgressEventArgs.After(), Ionic.Zip.ZipFile.ArchiveNameForEvent, Ionic.Zip.ReadProgressEventArgs.Before(), System.Collections.Generic.Dictionary< TKey, TValue >.Count, and Ionic.Zip.ZipFile.ReadProgress.
Referenced by Ionic.Zip.ZipFile.ReadCentralDirectory(), and Ionic.Zip.ZipEntry.ReadEntry().