Terraria Decompiled: Ionic.Zip.ZipFile.ReadZipFileComment
ReadZipFileComment()
static void Ionic.Zip.ZipFile.ReadZipFileComment (ZipFile zf) inline static private
Definition at line 2443 of file ZipFile.cs.
        {
            byte[] array = new byte[2];
            zf.ReadStream.Read(array, 0, array.Length);
            short num = (short)((int)array[0] + (int)array[1] * 256);
            if (num > 0)
            {
                array = new byte[(int)num];
                zf.ReadStream.Read(array, 0, array.Length);
                string @string = zf.AlternateEncoding.GetString(array, 0, array.Length);
                zf.Comment = @string;
            }
        }
References Ionic.Zip.ZipFile.AlternateEncoding, System.array, System.Text.Encoding.GetString(), int, System.IO.Stream.Read(), and Ionic.Zip.ZipFile.ReadStream.
Referenced by Ionic.Zip.ZipFile.ReadCentralDirectoryFooter().