Terraria Decompiled: Ionic.Zip.ZipFile.Read
Read() [3/6]
static ZipFile Ionic.Zip.ZipFile.Read (Stream zipStream, TextWriter statusMessageWriter, Encoding encoding, EventHandler< ReadProgressEventArgs > readProgress) inline static private
Definition at line 2149 of file ZipFile.cs.
        {
            if (zipStream == null)
            {
                throw new ArgumentNullException("zipStream");
            }
            ZipFile zipFile = new ZipFile();
            zipFile._StatusMessageTextWriter = statusMessageWriter;
            zipFile._alternateEncoding = encoding ?? ZipFile.DefaultEncoding;
            zipFile._alternateEncodingUsage = ZipOption.Always;
            if (readProgress != null)
            {
                zipFile.ReadProgress += readProgress;
            }
            zipFile._readstream = ((zipStream.Position == 0L) ? zipStream : new OffsetStream(zipStream));
            zipFile._ReadStreamIsOurs = false;
            if (zipFile.Verbose)
            {
                zipFile._StatusMessageTextWriter.WriteLine("reading from stream...");
            }
            ZipFile.ReadIntoInstance(zipFile);
            return zipFile;
        }
References Ionic.Zip.ZipFile._StatusMessageTextWriter, Ionic.Zip.ZipFile.DefaultEncoding, System.L, Ionic.Zip.ZipFile.ReadIntoInstance(), Ionic.Zip.ZipFile.Verbose, System.IO.TextWriter.WriteLine(), and Ionic.Zip.ZipFile.ZipFile().