Terraria Decompiled: Ionic.Zip.ZipFile.ReadCentralDirectoryFooter
ReadCentralDirectoryFooter()
static void Ionic.Zip.ZipFile.ReadCentralDirectoryFooter (ZipFile zf) inline static private
Definition at line 2396 of file ZipFile.cs.
        {
            Stream readStream = zf.ReadStream;
            int num = SharedUtilities.ReadSignature(readStream);
            int num2 = 0;
            byte[] array;
            if ((long)num == 101075792L)
            {
                array = new byte[52];
                readStream.Read(array, 0, array.Length);
                long num3 = BitConverter.ToInt64(array, 0);
                if (num3 < 44L)
                {
                    throw new ZipException("Bad size in the ZIP64 Central Directory.");
                }
                zf._versionMadeBy = BitConverter.ToUInt16(array, num2);
                num2 += 2;
                zf._versionNeededToExtract = BitConverter.ToUInt16(array, num2);
                num2 += 2;
                zf._diskNumberWithCd = BitConverter.ToUInt32(array, num2);
                num2 += 2;
                array = new byte[num3 - 44L];
                readStream.Read(array, 0, array.Length);
                num = SharedUtilities.ReadSignature(readStream);
                if ((long)num != 117853008L)
                {
                    throw new ZipException("Inconsistent metadata in the ZIP64 Central Directory.");
                }
                array = new byte[16];
                readStream.Read(array, 0, array.Length);
                num = SharedUtilities.ReadSignature(readStream);
            }
            if ((long)num != 101010256L)
            {
                readStream.Seek(-4L, 1);
                throw new BadReadException(string.Format("Bad signature ({0:X8}) at position 0x{1:X8}", num, readStream.Position));
            }
            array = new byte[16];
            zf.ReadStream.Read(array, 0, array.Length);
            if (zf._diskNumberWithCd == 0U)
            {
                zf._diskNumberWithCd = (uint)BitConverter.ToUInt16(array, 2);
            }
            ZipFile.ReadZipFileComment(zf);
        }
References Ionic.Zip.ZipFile._diskNumberWithCd, System.array, System.Format, System.L, System.IO.Stream.Position, System.IO.Stream.Read(), Ionic.Zip.SharedUtilities.ReadSignature(), Ionic.Zip.ZipFile.ReadStream, Ionic.Zip.ZipFile.ReadZipFileComment(), System.IO.Stream.Seek(), System.BitConverter.ToInt64(), System.BitConverter.ToUInt16(), System.BitConverter.ToUInt32(), and System.U.
Referenced by Ionic.Zip.ZipFile.ReadCentralDirectory(), and Ionic.Zip.ZipFile.ReadIntoInstance_Orig().