Terraria Decompiled: Ionic.Zip.ZipFile.Save
Save() [1/3]
void Ionic.Zip.ZipFile.Save () inline
Definition at line 2549 of file ZipFile.cs.
        {
            try
            {
                bool flag = false;
                this._saveOperationCanceled = false;
                this._numberOfSegmentsForMostRecentSave = 0U;
                this.OnSaveStarted();
                if (this.WriteStream == null)
                {
                    throw new BadStateException("You haven't specified where to save the zip.");
                }
                if (this._name != null && this._name.EndsWith(".exe") && !this._SavingSfx)
                {
                    throw new BadStateException("You specified an EXE for a plain zip file.");
                }
                if (!this._contentsChanged)
                {
                    this.OnSaveCompleted();
                    if (this.Verbose)
                    {
                        this.StatusMessageTextWriter.WriteLine("No save is necessary....");
                    }
                }
                else
                {
                    this.Reset(true);
                    if (this.Verbose)
                    {
                        this.StatusMessageTextWriter.WriteLine("saving....");
                    }
                    if (this._entries.Count >= 65535 && this._zip64 == Zip64Option.Default)
                    {
                        throw new ZipException("The number of entries is 65535 or greater. Consider setting the UseZip64WhenSaving property on the ZipFile instance.");
                    }
                    int num = 0;
                    ICollection<ZipEntry> collection = (this.SortEntriesBeforeSaving ? this.EntriesSorted : this.Entries);
                    foreach (ZipEntry zipEntry in collection)
                    {
                        this.OnSaveEntry(num, zipEntry, true);
                        zipEntry.Write(this.WriteStream);
                        if (this._saveOperationCanceled)
{
                            break;
                        }
                        num++;
                        this.OnSaveEntry(num, zipEntry, false);
                        if (this._saveOperationCanceled)
{
                            break;
                        }
                        if (zipEntry.IncludedInMostRecentSave)
{
                            flag |= zipEntry.OutputUsedZip64.Value;
                        }
                    }
                    if (!this._saveOperationCanceled)
                    {
                        ZipSegmentedStream zipSegmentedStream = this.WriteStream as ZipSegmentedStream;
                        this._numberOfSegmentsForMostRecentSave = ((zipSegmentedStream != null) ? zipSegmentedStream.CurrentSegment : 1U);
                        bool flag2 = ZipOutput.WriteCentralDirectoryStructure(this.WriteStream, collection, this._numberOfSegmentsForMostRecentSave, this._zip64, this.Comment, new ZipContainer(this));
                        this.OnSaveEvent(ZipProgressEventType.Saving_AfterSaveTempArchive);
                        this._hasBeenSaved = true;
                        this._contentsChanged = false;
                        flag = flag || flag2;
                        this._OutputUsesZip64 = new bool?(flag);
                        if (this._name != null && (this._temporaryFileName != null || zipSegmentedStream != null))
{
                            this.WriteStream.Close();
                            if (this._saveOperationCanceled)
{
                                return;
                            }
                            if (this._fileAlreadyExists && this._readstream != null)
{
                                this._readstream.Close();
                                this._readstream = null;
                                foreach (ZipEntry zipEntry2 in collection)
{
                                    ZipSegmentedStream zipSegmentedStream2 = zipEntry2._archiveStream as ZipSegmentedStream;
                                    if (zipSegmentedStream2 != null)
{
                                        zipSegmentedStream2.Close();
                                    }
                                    zipEntry2._archiveStream = null;
                                }
                            }
                            string text = null;
                            if (File.Exists(this._name))
{
                                text = this._name + "." + SharedUtilities.GenerateRandomStringImpl(8, 0) + ".tmp";
                                if (File.Exists(text))
{
                                    this.DeleteFileWithRetry(text);
                                }
                                File.Move(this._name, text);
                            }
                            this.OnSaveEvent(ZipProgressEventType.Saving_BeforeRenameTempArchive);
                            File.Move((zipSegmentedStream != null) ? zipSegmentedStream.CurrentTempName : this._temporaryFileName, this._name);
                            this.OnSaveEvent(ZipProgressEventType.Saving_AfterRenameTempArchive);
                            if (text != null)
{
                                try
{
                                    if (File.Exists(text))
{
                                        File.Delete(text);
                                    }
                                }
                                catch
{
                                }
                            }
                            this._fileAlreadyExists = true;
                        }
                        ZipFile.NotifyEntriesSaveComplete(collection);
                        this.OnSaveCompleted();
                        this._JustSaved = true;
                    }
                }
            }
            finally
            {
                this.CleanupAfterSaveOperation();
            }
        }
References Ionic.Zip.ZipFile._contentsChanged, Ionic.Zip.ZipFile._entries, Ionic.Zip.ZipFile._fileAlreadyExists, Ionic.Zip.ZipFile._name, Ionic.Zip.ZipFile._numberOfSegmentsForMostRecentSave, Ionic.Zip.ZipFile._readstream, Ionic.Zip.ZipFile._saveOperationCanceled, Ionic.Zip.ZipFile._temporaryFileName, Ionic.Zip.ZipFile._zip64, Ionic.Zip.ZipFile.CleanupAfterSaveOperation(), System.IO.Stream.Close(), System.collection, Ionic.Zip.ZipFile.Comment, System.Collections.Generic.Dictionary< TKey, TValue >.Count, Ionic.Zip.ZipSegmentedStream.CurrentSegment, Ionic.Zip.ZipSegmentedStream.CurrentTempName, System.IO.File.Delete(), Ionic.Zip.ZipFile.DeleteFileWithRetry(), Ionic.Zip.ZipFile.Entries, System.IO.File.Exists(), Ionic.Zip.SharedUtilities.GenerateRandomStringImpl(), Ionic.Zip.ZipEntry.IncludedInMostRecentSave, System.IO.File.Move(), Ionic.Zip.ZipFile.NotifyEntriesSaveComplete(), Ionic.Zip.ZipFile.OnSaveCompleted(), Ionic.Zip.ZipFile.OnSaveEntry(), Ionic.Zip.ZipFile.OnSaveEvent(), Ionic.Zip.ZipFile.OnSaveStarted(), Ionic.Zip.ZipEntry.OutputUsedZip64, Ionic.Zip.ZipFile.Reset(), Ionic.Zip.ZipFile.StatusMessageTextWriter, System.text, System.U, Ionic.Zip.ZipFile.Verbose, Ionic.Zip.ZipEntry.Write(), Ionic.Zip.ZipOutput.WriteCentralDirectoryStructure(), System.IO.TextWriter.WriteLine(), and Ionic.Zip.ZipFile.WriteStream.
Referenced by Ionic.Zip.ZipFile.FixZipDirectory(), Ionic.Zip.ZipFile.Save(), and Ionic.Zip.ZipFile.Save().