Terraria Decompiled: Ionic.Zip.ZipFile.AddEntry
AddEntry() [3/6]
ZipEntry Ionic.Zip.ZipFile.AddEntry (string entryName, Stream stream) inline
Definition at line 233 of file ZipFile.cs.
        {
            ZipEntry zipEntry = ZipEntry.CreateForStream(entryName, stream);
            zipEntry.SetEntryTimes(DateTime.Now, DateTime.Now, DateTime.Now);
            if (this.Verbose)
            {
                this.StatusMessageTextWriter.WriteLine("adding {0}...", entryName);
            }
            return this._InternalAddEntry(zipEntry);
        }
References Ionic.Zip.ZipFile._InternalAddEntry(), Ionic.Zip.ZipEntry.CreateForStream(), System.DateTime.Now, Ionic.Zip.ZipEntry.SetEntryTimes(), Ionic.Zip.ZipFile.StatusMessageTextWriter, Ionic.Zip.ZipFile.Verbose, and System.IO.TextWriter.WriteLine().