Terraria Decompiled: Ionic.Zip.ZipFile.AddOrUpdateDirectoryImpl
AddOrUpdateDirectoryImpl() [2/2]
ZipEntry Ionic.Zip.ZipFile.AddOrUpdateDirectoryImpl (string directoryName, string rootDirectoryPathInArchive, AddOrUpdateAction action, bool recurse, int level) inline private
Definition at line 407 of file ZipFile.cs.
        {
            if (this.Verbose)
            {
                this.StatusMessageTextWriter.WriteLine("{0} {1}...", (action == AddOrUpdateAction.AddOnly) ? "adding" : "Adding or updating", directoryName);
            }
            if (level == 0)
            {
                this._addOperationCanceled = false;
                this.OnAddStarted();
            }
            if (this._addOperationCanceled)
            {
                return null;
            }
            string text = rootDirectoryPathInArchive;
            ZipEntry zipEntry = null;
            if (level > 0)
            {
                int num = directoryName.Length;
                for (int i = level; i > 0; i--)
                {
                    num = directoryName.LastIndexOfAny("/\\".ToCharArray(), num - 1, num - 1);
                }
                text = directoryName.Substring(num + 1);
                text = Path.Combine(rootDirectoryPathInArchive, text);
            }
            if (level > 0 || rootDirectoryPathInArchive != "")
            {
                zipEntry = ZipEntry.CreateFromFile(directoryName, text);
                zipEntry._container = new ZipContainer(this);
                zipEntry.AlternateEncoding = this.AlternateEncoding;
                zipEntry.AlternateEncodingUsage = this.AlternateEncodingUsage;
                zipEntry.MarkAsDirectory();
                zipEntry.EmitTimesInWindowsFormatWhenSaving = this._emitNtfsTimes;
                zipEntry.EmitTimesInUnixFormatWhenSaving = this._emitUnixTimes;
                if (!this._entries.ContainsKey(zipEntry.FileName))
                {
                    this.InternalAddEntry(zipEntry.FileName, zipEntry);
                    this.AfterAddEntry(zipEntry);
                }
                text = zipEntry.FileName;
            }
            if (!this._addOperationCanceled)
            {
                string[] files = Directory.GetFiles(directoryName);
                if (recurse)
                {
                    foreach (string text2 in files)
                    {
                        if (this._addOperationCanceled)
{
                            break;
                        }
                        if (action == AddOrUpdateAction.AddOnly)
{
                            this.AddFile(text2, text);
                        }
                        else
{
                            this.UpdateFile(text2, text);
                        }
                    }
                    if (!this._addOperationCanceled)
                    {
                        string[] directories = Directory.GetDirectories(directoryName);
                        foreach (string text3 in directories)
{
                            FileAttributes attributes = NetCfFile.GetAttributes(text3);
                            if (this.AddDirectoryWillTraverseReparsePoints || (attributes & 1024) == null)
{
                                this.AddOrUpdateDirectoryImpl(text3, rootDirectoryPathInArchive, action, recurse, level + 1);
                            }
                        }
                    }
                }
            }
            if (level == 0)
            {
                this.OnAddCompleted();
            }
            return zipEntry;
        }
References Ionic.Zip.ZipFile._addOperationCanceled, Ionic.Zip.ZipFile._emitNtfsTimes, Ionic.Zip.ZipFile._emitUnixTimes, Ionic.Zip.ZipFile._entries, System.action, Ionic.Zip.ZipFile.AddDirectoryWillTraverseReparsePoints, Ionic.Zip.ZipFile.AddFile(), Ionic.Zip.ZipFile.AddOrUpdateDirectoryImpl(), Ionic.Zip.ZipFile.AfterAddEntry(), Ionic.Zip.ZipFile.AlternateEncoding, Ionic.Zip.ZipFile.AlternateEncodingUsage, System.IO.Path.Combine(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Ionic.Zip.ZipEntry.CreateFromFile(), Ionic.Zip.ZipEntry.FileName, Ionic.Zip.NetCfFile.GetAttributes(), System.IO.Directory.GetDirectories(), System.IO.Directory.GetFiles(), Ionic.Zip.ZipFile.InternalAddEntry(), Ionic.Zip.ZipEntry.MarkAsDirectory(), Ionic.Zip.ZipFile.OnAddCompleted(), Ionic.Zip.ZipFile.OnAddStarted(), Ionic.Zip.ZipFile.StatusMessageTextWriter, System.text, Ionic.Zip.ZipFile.UpdateFile(), Ionic.Zip.ZipFile.Verbose, and System.IO.TextWriter.WriteLine().