Terraria Decompiled: Ionic.Zip.ZipFile.DeleteFileWithRetry
DeleteFileWithRetry()
void Ionic.Zip.ZipFile.DeleteFileWithRetry (string filename) inline private
Definition at line 2527 of file ZipFile.cs.
        {
            bool flag = false;
            int num = 3;
            int num2 = 0;
            while (num2 < num && !flag)
            {
                try
                {
                    File.Delete(filename);
                    flag = true;
                }
                catch (UnauthorizedAccessException)
                {
                    Console.WriteLine("************************************************** Retry delete.");
                    Thread.Sleep(200 + num2 * 200);
                }
                num2++;
            }
        }
References System.IO.File.Delete(), System.Threading.Thread.Sleep(), and System.Console.WriteLine().
Referenced by Ionic.Zip.ZipFile.Save().