Terraria Decompiled: Ionic.Zip.ZipFile.ReadIntoInstance
ReadIntoInstance()
static void Ionic.Zip.ZipFile.ReadIntoInstance (ZipFile zf) inline static private
Definition at line 2174 of file ZipFile.cs.
        {
            Stream readStream = zf.ReadStream;
            try
            {
                zf._readName = zf._name;
                if (!readStream.CanSeek)
                {
                    ZipFile.ReadIntoInstance_Orig(zf);
                    return;
                }
                zf.OnReadStarted();
                uint num = ZipFile.ReadFirstFourBytes(readStream);
                if (num == 101010256U)
                {
                    return;
                }
                int num2 = 0;
                bool flag = false;
                long num3 = readStream.Length - 64L;
                long num4 = Math.Max(readStream.Length - 16384L, 10L);
                do
                {
                    if (num3 < 0L)
                    {
                        num3 = 0L;
                    }
                    readStream.Seek(num3, 0);
                    long num5 = SharedUtilities.FindSignature(readStream, 101010256);
                    if (num5 != -1L)
                    {
                        flag = true;
                    }
                    else
                    {
                        if (num3 == 0L)
{
                            break;
                        }
                        num2++;
                        num3 -= (long)(32 * (num2 + 1) * num2);
                    }
                }
                while (!flag && num3 > num4);
                if (flag)
                {
                    zf._locEndOfCDS = readStream.Position - 4L;
                    byte[] array = new byte[16];
                    readStream.Read(array, 0, array.Length);
                    zf._diskNumberWithCd = (uint)BitConverter.ToUInt16(array, 2);
                    if (zf._diskNumberWithCd == 65535U)
                    {
                        throw new ZipException("Spanned archives with more than 65534 segments are not supported at this time.");
                    }
                    zf._diskNumberWithCd += 1U;
                    int num6 = 12;
                    uint num7 = BitConverter.ToUInt32(array, num6);
                    if (num7 == 4294967295U)
                    {
                        ZipFile.Zip64SeekToCentralDirectory(zf);
                    }
                    else
                    {
                        zf._OffsetOfCentralDirectory = num7;
                        readStream.Seek((long)((ulong)num7), 0);
                    }
                    ZipFile.ReadCentralDirectory(zf);
                }
                else
                {
                    readStream.Seek(0L, 0);
                    ZipFile.ReadIntoInstance_Orig(zf);
                }
            }
            catch (Exception ex)
            {
                if (zf._ReadStreamIsOurs && zf._readstream != null)
                {
                    zf._readstream.Close();
                    zf._readstream = null;
                }
                throw new ZipException("Cannot read that as a ZipFile", ex);
            }
            zf._contentsChanged = false;
        }
References Ionic.Zip.ZipFile._diskNumberWithCd, Ionic.Zip.ZipFile._name, Ionic.Zip.ZipFile._readstream, Ionic.Zip.ZipFile._ReadStreamIsOurs, System.array, System.IO.Stream.CanSeek, System.IO.Stream.Close(), Ionic.Zip.SharedUtilities.FindSignature(), System.L, System.IO.Stream.Length, long, System.Math.Max(), Ionic.Zip.ZipFile.OnReadStarted(), System.IO.Stream.Read(), Ionic.Zip.ZipFile.ReadCentralDirectory(), Ionic.Zip.ZipFile.ReadFirstFourBytes(), Ionic.Zip.ZipFile.ReadIntoInstance_Orig(), Ionic.Zip.ZipFile.ReadStream, System.IO.Stream.Seek(), System.BitConverter.ToUInt16(), System.BitConverter.ToUInt32(), System.U, and Ionic.Zip.ZipFile.Zip64SeekToCentralDirectory().
Referenced by Ionic.Zip.ZipFile._InitInstance(), Ionic.Zip.ZipFile.Read(), Ionic.Zip.ZipFile.Read(), and Ionic.Zip.ZipFile.Reset().