Terraria Decompiled: Ionic.Zip.ZipFile.AddFiles
AddFiles() [2/3]
void Ionic.Zip.ZipFile.AddFiles (IEnumerable< string > fileNames, bool preserveDirHierarchy, string directoryPathInArchive) inline
Definition at line 102 of file ZipFile.cs.
        {
            if (fileNames == null)
            {
                throw new ArgumentNullException("fileNames");
            }
            this._addOperationCanceled = false;
            this.OnAddStarted();
            if (preserveDirHierarchy)
            {
                using (IEnumerator<string> enumerator = fileNames.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        string text = enumerator.Current;
                        if (this._addOperationCanceled)
{
                            break;
                        }
                        if (directoryPathInArchive != null)
{
                            string fullPath = Path.GetFullPath(Path.Combine(directoryPathInArchive, Path.GetDirectoryName(text)));
                            this.AddFile(text, fullPath);
                        }
                        else
{
                            this.AddFile(text, null);
                        }
                    }
                    goto IL_00AD;
                }
            }
            foreach (string text2 in fileNames)
            {
                if (this._addOperationCanceled)
                {
                    break;
                }
                this.AddFile(text2, directoryPathInArchive);
            }
            IL_00AD:
            if (!this._addOperationCanceled)
            {
                this.OnAddCompleted();
            }
        }
References Ionic.Zip.ZipFile._addOperationCanceled, Ionic.Zip.ZipFile.AddFile(), System.IO.Path.Combine(), System.Collections.Generic.IEnumerator< out T >.Current, System.IO.Path.GetDirectoryName(), System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), System.IO.Path.GetFullPath(), System.Collections.IEnumerator.MoveNext(), Ionic.Zip.ZipFile.OnAddCompleted(), Ionic.Zip.ZipFile.OnAddStarted(), and System.text.