Terraria Decompiled: Ionic.Zlib.DeflateManager.SetDictionary
SetDictionary()
int Ionic.Zlib.DeflateManager.SetDictionary (byte[] dictionary) inline package
Definition at line 1047 of file DeflateManager.cs.
        {
            int num = dictionary.Length;
            int num2 = 0;
            if (dictionary == null || this.status != DeflateManager.INIT_STATE)
            {
                throw new ZlibException("Stream error.");
            }
            this._codec._Adler32 = Adler.Adler32(this._codec._Adler32, dictionary, 0, dictionary.Length);
            if (num < DeflateManager.MIN_MATCH)
            {
                return 0;
            }
            if (num > this.w_size - DeflateManager.MIN_LOOKAHEAD)
            {
                num = this.w_size - DeflateManager.MIN_LOOKAHEAD;
                num2 = dictionary.Length - num;
            }
            Array.Copy(dictionary, num2, this.window, 0, num);
            this.strstart = num;
            this.block_start = num;
            this.ins_h = (int)(this.window[0] & byte.MaxValue);
            this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[1] & byte.MaxValue)) & this.hash_mask;
            for (int i = 0; i <= num - DeflateManager.MIN_MATCH; i++)
            {
                this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[i + (DeflateManager.MIN_MATCH - 1)] & byte.MaxValue)) & this.hash_mask;
                this.prev[i & this.w_mask] = this.head[this.ins_h];
                this.head[this.ins_h] = (short)i;
            }
            return 0;
        }
References Ionic.Zlib.ZlibCodec._Adler32, Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.Adler.Adler32(), System.Array.Copy(), System.dictionary, Ionic.Zlib.DeflateManager.hash_mask, Ionic.Zlib.DeflateManager.hash_shift, Ionic.Zlib.DeflateManager.head, Ionic.Zlib.DeflateManager.INIT_STATE, Ionic.Zlib.DeflateManager.ins_h, int, Ionic.Zlib.DeflateManager.MIN_LOOKAHEAD, Ionic.Zlib.DeflateManager.MIN_MATCH, Ionic.Zlib.DeflateManager.prev, Ionic.Zlib.DeflateManager.status, Ionic.Zlib.DeflateManager.w_mask, Ionic.Zlib.DeflateManager.w_size, and Ionic.Zlib.DeflateManager.window.
Referenced by Ionic.Zlib.ZlibCodec.SetDictionary().