Terraria Decompiled: Ionic.Zlib.DeflateManager.DeflateNone
DeflateNone()
BlockState Ionic.Zlib.DeflateManager.DeflateNone (FlushType flush) inline package
Definition at line 472 of file DeflateManager.cs.
        {
            int num = 65535;
            if (num > this.pending.Length - 5)
            {
                num = this.pending.Length - 5;
            }
            for (;;)
            {
                if (this.lookahead <= 1)
                {
                    this._fillWindow();
                    if (this.lookahead == 0 && flush == FlushType.None)
                    {
                        break;
                    }
                    if (this.lookahead == 0)
                    {
                        goto IL_00DB;
                    }
                }
                this.strstart += this.lookahead;
                this.lookahead = 0;
                int num2 = this.block_start + num;
                if (this.strstart == 0 || this.strstart >= num2)
                {
                    this.lookahead = this.strstart - num2;
                    this.strstart = num2;
                    this.flush_block_only(false);
                    if (this._codec.AvailableBytesOut == 0)
                    {
                        return BlockState.NeedMore;
                    }
                }
                if (this.strstart - this.block_start >= this.w_size - DeflateManager.MIN_LOOKAHEAD)
                {
                    this.flush_block_only(false);
                    if (this._codec.AvailableBytesOut == 0)
                    {
                        return BlockState.NeedMore;
                    }
                }
            }
            return BlockState.NeedMore;
            IL_00DB:
            this.flush_block_only(flush == FlushType.Finish);
            if (this._codec.AvailableBytesOut == 0)
            {
                if (flush != FlushType.Finish)
                {
                    return BlockState.NeedMore;
                }
                return BlockState.FinishStarted;
            }
            else
            {
                if (flush != FlushType.Finish)
                {
                    return BlockState.BlockDone;
                }
                return BlockState.FinishDone;
            }
        }
References Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.DeflateManager._fillWindow(), Ionic.Zlib.ZlibCodec.AvailableBytesOut, Ionic.Zlib.DeflateManager.block_start, Ionic.Zlib.DeflateManager.flush_block_only(), Ionic.Zlib.DeflateManager.lookahead, Ionic.Zlib.DeflateManager.MIN_LOOKAHEAD, Ionic.Zlib.DeflateManager.pending, Ionic.Zlib.DeflateManager.strstart, and Ionic.Zlib.DeflateManager.w_size.
Referenced by Ionic.Zlib.DeflateManager.SetDeflater().