Terraria Decompiled: Ionic.Zlib.DeflateManager._tr_tally
_tr_tally()
bool Ionic.Zlib.DeflateManager._tr_tally (int dist, int lc) inline package
Definition at line 306 of file DeflateManager.cs.
        {
            this.pending[this._distanceOffset + this.last_lit * 2] = (byte)((uint)dist >> 8);
            this.pending[this._distanceOffset + this.last_lit * 2 + 1] = (byte)dist;
            this.pending[this._lengthOffset + this.last_lit] = (byte)lc;
            this.last_lit++;
            if (dist == 0)
            {
                short[] array = this.dyn_ltree;
                int num = lc * 2;
                array[num] += 1;
            }
            else
            {
                this.matches++;
                dist--;
                short[] array2 = this.dyn_ltree;
                int num2 = ((int)Tree.LengthCode[lc] + InternalConstants.LITERALS + 1) * 2;
                array2[num2] += 1;
                short[] array3 = this.dyn_dtree;
                int num3 = Tree.DistanceCode(dist) * 2;
                array3[num3] += 1;
            }
            if ((this.last_lit & 8191) == 0 && this.compressionLevel > CompressionLevel.Level2)
            {
                int num4 = this.last_lit << 3;
                int num5 = this.strstart - this.block_start;
                for (int i = 0; i < InternalConstants.D_CODES; i++)
                {
                    num4 = (int)((long)num4 + (long)this.dyn_dtree[i * 2] * (5L + (long)Tree.ExtraDistanceBits[i]));
                }
                num4 >>= 3;
                if (this.matches < this.last_lit / 2 && num4 < num5 / 2)
                {
                    return true;
                }
            }
            return this.last_lit == this.lit_bufsize - 1 || this.last_lit == this.lit_bufsize;
        }
References System.array, Ionic.Zlib.DeflateManager.block_start, Ionic.Zlib.InternalConstants.D_CODES, Ionic.Zlib.Tree.DistanceCode(), Ionic.Zlib.DeflateManager.dyn_dtree, Ionic.Zlib.DeflateManager.dyn_ltree, Ionic.Zlib.Tree.ExtraDistanceBits, int, System.L, Ionic.Zlib.DeflateManager.last_lit, Ionic.Zlib.Tree.LengthCode, Ionic.Zlib.DeflateManager.lit_bufsize, Ionic.Zlib.InternalConstants.LITERALS, long, Ionic.Zlib.DeflateManager.matches, and Ionic.Zlib.DeflateManager.pending.
Referenced by Ionic.Zlib.DeflateManager.DeflateFast(), and Ionic.Zlib.DeflateManager.DeflateSlow().