Terraria Decompiled: Ionic.Zlib.DeflateManager.send_all_trees
send_all_trees()
void Ionic.Zlib.DeflateManager.send_all_trees (int lcodes, int dcodes, int blcodes) inline package
Definition at line 179 of file DeflateManager.cs.
        {
            this.send_bits(lcodes - 257, 5);
            this.send_bits(dcodes - 1, 5);
            this.send_bits(blcodes - 4, 4);
            for (int i = 0; i < blcodes; i++)
            {
                this.send_bits((int)this.bl_tree[(int)(Tree.bl_order[i] * 2 + 1)], 3);
            }
            this.send_tree(this.dyn_ltree, lcodes - 1);
            this.send_tree(this.dyn_dtree, dcodes - 1);
        }
References Ionic.Zlib.Tree.bl_order, Ionic.Zlib.DeflateManager.bl_tree, Ionic.Zlib.DeflateManager.dyn_dtree, Ionic.Zlib.DeflateManager.dyn_ltree, Ionic.Zlib.DeflateManager.send_bits(), and Ionic.Zlib.DeflateManager.send_tree().
Referenced by Ionic.Zlib.DeflateManager._tr_flush_block().