Terraria Decompiled: Ionic.Zlib.DeflateManager.flush_block_only
flush_block_only()
void Ionic.Zlib.DeflateManager.flush_block_only (bool eof) inline package
Definition at line 464 of file DeflateManager.cs.
        {
            this._tr_flush_block((this.block_start >= 0) ? this.block_start : (-1), this.strstart - this.block_start, eof);
            this.block_start = this.strstart;
            this._codec.flush_pending();
        }
References Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.DeflateManager._tr_flush_block(), Ionic.Zlib.DeflateManager.block_start, Ionic.Zlib.ZlibCodec.flush_pending(), and Ionic.Zlib.DeflateManager.strstart.
Referenced by Ionic.Zlib.DeflateManager.DeflateFast(), Ionic.Zlib.DeflateManager.DeflateNone(), and Ionic.Zlib.DeflateManager.DeflateSlow().