Terraria Decompiled: Ionic.Zlib.DeflateManager.DeflateSlow
DeflateSlow()
BlockState Ionic.Zlib.DeflateManager.DeflateSlow (FlushType flush) inline package
Definition at line 741 of file DeflateManager.cs.
        {
            int num = 0;
            for (;;)
            {
                if (this.lookahead < DeflateManager.MIN_LOOKAHEAD)
                {
                    this._fillWindow();
                    if (this.lookahead < DeflateManager.MIN_LOOKAHEAD && flush == FlushType.None)
                    {
                        break;
                    }
                    if (this.lookahead == 0)
                    {
                        goto IL_0365;
                    }
                }
                if (this.lookahead >= DeflateManager.MIN_MATCH)
                {
                    this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[this.strstart + (DeflateManager.MIN_MATCH - 1)] & byte.MaxValue)) & this.hash_mask;
                    num = (int)this.head[this.ins_h] & 65535;
                    this.prev[this.strstart & this.w_mask] = this.head[this.ins_h];
                    this.head[this.ins_h] = (short)this.strstart;
                }
                this.prev_length = this.match_length;
                this.prev_match = this.match_start;
                this.match_length = DeflateManager.MIN_MATCH - 1;
                if (num != 0 && this.prev_length < this.config.MaxLazy && ((this.strstart - num) & 65535) <= this.w_size - DeflateManager.MIN_LOOKAHEAD)
                {
                    if (this.compressionStrategy != CompressionStrategy.HuffmanOnly)
                    {
                        this.match_length = this.longest_match(num);
                    }
                    if (this.match_length <= 5 && (this.compressionStrategy == CompressionStrategy.Filtered || (this.match_length == DeflateManager.MIN_MATCH && this.strstart - this.match_start > 4096)))
                    {
                        this.match_length = DeflateManager.MIN_MATCH - 1;
                    }
                }
                if (this.prev_length >= DeflateManager.MIN_MATCH && this.match_length <= this.prev_length)
                {
                    int num2 = this.strstart + this.lookahead - DeflateManager.MIN_MATCH;
                    bool flag = this._tr_tally(this.strstart - 1 - this.prev_match, this.prev_length - DeflateManager.MIN_MATCH);
                    this.lookahead -= this.prev_length - 1;
                    this.prev_length -= 2;
                    do
                    {
                        if (++this.strstart <= num2)
{
                            this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[this.strstart + (DeflateManager.MIN_MATCH - 1)] & byte.MaxValue)) & this.hash_mask;
                            num = (int)this.head[this.ins_h] & 65535;
                            this.prev[this.strstart & this.w_mask] = this.head[this.ins_h];
                            this.head[this.ins_h] = (short)this.strstart;
                        }
                    }
                    while (--this.prev_length != 0);
                    this.match_available = 0;
                    this.match_length = DeflateManager.MIN_MATCH - 1;
                    this.strstart++;
                    if (flag)
                    {
                        this.flush_block_only(false);
                        if (this._codec.AvailableBytesOut == 0)
{
                            return BlockState.NeedMore;
                        }
                    }
                }
                else if (this.match_available != 0)
                {
                    bool flag = this._tr_tally(0, (int)(this.window[this.strstart - 1] & byte.MaxValue));
                    if (flag)
                    {
                        this.flush_block_only(false);
                    }
                    this.strstart++;
                    this.lookahead--;
                    if (this._codec.AvailableBytesOut == 0)
                    {
                        return BlockState.NeedMore;
                    }
                }
                else
                {
                    this.match_available = 1;
                    this.strstart++;
                    this.lookahead--;
                }
            }
            return BlockState.NeedMore;
            IL_0365:
            if (this.match_available != 0)
            {
                bool flag = this._tr_tally(0, (int)(this.window[this.strstart - 1] & byte.MaxValue));
                this.match_available = 0;
            }
            this.flush_block_only(flush == FlushType.Finish);
            if (this._codec.AvailableBytesOut == 0)
            {
                if (flush == FlushType.Finish)
                {
                    return BlockState.FinishStarted;
                }
                return BlockState.NeedMore;
            }
            else
            {
                if (flush != FlushType.Finish)
                {
                    return BlockState.BlockDone;
                }
                return BlockState.FinishDone;
            }
        }
References Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.DeflateManager._fillWindow(), Ionic.Zlib.DeflateManager._tr_tally(), Ionic.Zlib.ZlibCodec.AvailableBytesOut, Ionic.Zlib.DeflateManager.compressionStrategy, Ionic.Zlib.DeflateManager.config, Ionic.Zlib.DeflateManager.flush_block_only(), Ionic.Zlib.DeflateManager.hash_mask, Ionic.Zlib.DeflateManager.hash_shift, Ionic.Zlib.DeflateManager.head, Ionic.Zlib.DeflateManager.ins_h, int, Ionic.Zlib.DeflateManager.longest_match(), Ionic.Zlib.DeflateManager.lookahead, Ionic.Zlib.DeflateManager.match_available, Ionic.Zlib.DeflateManager.match_length, Ionic.Zlib.DeflateManager.match_start, Ionic.Zlib.DeflateManager.MIN_LOOKAHEAD, Ionic.Zlib.DeflateManager.MIN_MATCH, Ionic.Zlib.DeflateManager.prev, Ionic.Zlib.DeflateManager.prev_length, Ionic.Zlib.DeflateManager.prev_match, Ionic.Zlib.DeflateManager.strstart, Ionic.Zlib.DeflateManager.w_mask, Ionic.Zlib.DeflateManager.w_size, and Ionic.Zlib.DeflateManager.window.
Referenced by Ionic.Zlib.DeflateManager.SetDeflater().