Terraria Decompiled: Ionic.Zlib.DeflateManager.build_bl_tree
build_bl_tree()
int Ionic.Zlib.DeflateManager.build_bl_tree () inline package
Definition at line 164 of file DeflateManager.cs.
        {
            this.scan_tree(this.dyn_ltree, this.treeLiterals.max_code);
            this.scan_tree(this.dyn_dtree, this.treeDistances.max_code);
            this.treeBitLengths.build_tree(this);
            int num = InternalConstants.BL_CODES - 1;
            while (num >= 3 && this.bl_tree[(int)(Tree.bl_order[num] * 2 + 1)] == 0)
            {
                num--;
            }
            this.opt_len += 3 * (num + 1) + 5 + 5 + 4;
            return num;
        }
References Ionic.Zlib.Tree.bl_order, Ionic.Zlib.DeflateManager.bl_tree, Ionic.Zlib.Tree.build_tree(), Ionic.Zlib.DeflateManager.dyn_dtree, Ionic.Zlib.DeflateManager.dyn_ltree, Ionic.Zlib.Tree.max_code, Ionic.Zlib.DeflateManager.scan_tree(), Ionic.Zlib.DeflateManager.treeBitLengths, Ionic.Zlib.DeflateManager.treeDistances, and Ionic.Zlib.DeflateManager.treeLiterals.
Referenced by Ionic.Zlib.DeflateManager._tr_flush_block().