Terraria Decompiled: Ionic.Zlib.DeflateManager.send_bits
send_bits()
void Ionic.Zlib.DeflateManager.send_bits (int value, int length) inline package
Definition at line 275 of file DeflateManager.cs.
        {
            if (this.bi_valid > DeflateManager.Buf_size - length)
            {
                this.bi_buf |= (short)((value << this.bi_valid) & 65535);
                this.pending[this.pendingCount++] = (byte)this.bi_buf;
                this.pending[this.pendingCount++] = (byte)(this.bi_buf >> 8);
                this.bi_buf = (short)((uint)value >> DeflateManager.Buf_size - this.bi_valid);
                this.bi_valid += length - DeflateManager.Buf_size;
                return;
            }
            this.bi_buf |= (short)((value << this.bi_valid) & 65535);
            this.bi_valid += length;
        }
References Ionic.Zlib.DeflateManager.bi_buf, Ionic.Zlib.DeflateManager.bi_valid, Ionic.Zlib.DeflateManager.Buf_size, System.length, Ionic.Zlib.DeflateManager.pending, Ionic.Zlib.DeflateManager.pendingCount, and System.value.
Referenced by Ionic.Zlib.DeflateManager._tr_align(), Ionic.Zlib.DeflateManager._tr_flush_block(), Ionic.Zlib.DeflateManager._tr_stored_block(), Ionic.Zlib.DeflateManager.send_all_trees(), Ionic.Zlib.DeflateManager.send_code(), Ionic.Zlib.DeflateManager.send_compressed_block(), and Ionic.Zlib.DeflateManager.send_tree().