Terraria Decompiled: Ionic.Zlib.DeflateManager._tr_flush_block
_tr_flush_block()
void Ionic.Zlib.DeflateManager._tr_flush_block (int buf, int stored_len, bool eof) inline package
Definition at line 544 of file DeflateManager.cs.
        {
            int num = 0;
            int num2;
            int num3;
            if (this.compressionLevel > CompressionLevel.None)
            {
                if ((int)this.data_type == DeflateManager.Z_UNKNOWN)
                {
                    this.set_data_type();
                }
                this.treeLiterals.build_tree(this);
                this.treeDistances.build_tree(this);
                num = this.build_bl_tree();
                num2 = this.opt_len + 3 + 7 >> 3;
                num3 = this.static_len + 3 + 7 >> 3;
                if (num3 <= num2)
                {
                    num2 = num3;
                }
            }
            else
            {
                num3 = (num2 = stored_len + 5);
            }
            if (stored_len + 4 <= num2 && buf != -1)
            {
                this._tr_stored_block(buf, stored_len, eof);
            }
            else if (num3 == num2)
            {
                this.send_bits((DeflateManager.STATIC_TREES << 1) + (eof ? 1 : 0), 3);
                this.send_compressed_block(StaticTree.lengthAndLiteralsTreeCodes, StaticTree.distTreeCodes);
            }
            else
            {
                this.send_bits((DeflateManager.DYN_TREES << 1) + (eof ? 1 : 0), 3);
                this.send_all_trees(this.treeLiterals.max_code + 1, this.treeDistances.max_code + 1, num + 1);
                this.send_compressed_block(this.dyn_ltree, this.dyn_dtree);
            }
            this._InitializeBlocks();
            if (eof)
            {
                this.bi_windup();
            }
        }
References Ionic.Zlib.DeflateManager._InitializeBlocks(), Ionic.Zlib.DeflateManager._tr_stored_block(), Ionic.Zlib.DeflateManager.bi_windup(), Ionic.Zlib.DeflateManager.build_bl_tree(), Ionic.Zlib.Tree.build_tree(), Ionic.Zlib.DeflateManager.compressionLevel, Ionic.Zlib.DeflateManager.data_type, Ionic.Zlib.StaticTree.distTreeCodes, Ionic.Zlib.DeflateManager.dyn_dtree, Ionic.Zlib.DeflateManager.dyn_ltree, Ionic.Zlib.DeflateManager.DYN_TREES, Ionic.Zlib.StaticTree.lengthAndLiteralsTreeCodes, Ionic.Zlib.Tree.max_code, Ionic.Zlib.DeflateManager.send_all_trees(), Ionic.Zlib.DeflateManager.send_bits(), Ionic.Zlib.DeflateManager.send_compressed_block(), Ionic.Zlib.DeflateManager.set_data_type(), Ionic.Zlib.DeflateManager.STATIC_TREES, Ionic.Zlib.DeflateManager.treeDistances, Ionic.Zlib.DeflateManager.treeLiterals, and Ionic.Zlib.DeflateManager.Z_UNKNOWN.
Referenced by Ionic.Zlib.DeflateManager.flush_block_only().