Terraria Decompiled: Ionic.Zlib.DeflateManager.Reset
Reset()
void Ionic.Zlib.DeflateManager.Reset () inline package
Definition at line 976 of file DeflateManager.cs.
        {
            this._codec.TotalBytesIn = (this._codec.TotalBytesOut = 0L);
            this._codec.Message = null;
            this.pendingCount = 0;
            this.nextPending = 0;
            this.Rfc1950BytesEmitted = false;
            this.status = (this.WantRfc1950HeaderBytes ? DeflateManager.INIT_STATE : DeflateManager.BUSY_STATE);
            this._codec._Adler32 = Adler.Adler32(0U, null, 0, 0);
            this.last_flush = 0;
            this._InitializeTreeData();
            this._InitializeLazyMatch();
        }
References Ionic.Zlib.DeflateManager._InitializeLazyMatch(), Ionic.Zlib.DeflateManager._InitializeTreeData(), Ionic.Zlib.Adler.Adler32(), Ionic.Zlib.DeflateManager.BUSY_STATE, System.L, and System.U.
Referenced by Ionic.Zlib.DeflateManager.Initialize(), and Ionic.Zlib.ZlibCodec.ResetDeflate().