Terraria Decompiled: Ionic.Zlib.DeflateManager.send_tree
send_tree()
void Ionic.Zlib.DeflateManager.send_tree (short[] tree, int max_code) inline package
Definition at line 193 of file DeflateManager.cs.
        {
            int num = -1;
            int num2 = (int)tree[1];
            int num3 = 0;
            int num4 = 7;
            int num5 = 4;
            if (num2 == 0)
            {
                num4 = 138;
                num5 = 3;
            }
            for (int i = 0; i <= max_code; i++)
            {
                int num6 = num2;
                num2 = (int)tree[(i + 1) * 2 + 1];
                if (++num3 >= num4 || num6 != num2)
                {
                    if (num3 < num5)
                    {
                        do
{
                            this.send_code(num6, this.bl_tree);
                        }
                        while (--num3 != 0);
                    }
                    else if (num6 != 0)
                    {
                        if (num6 != num)
{
                            this.send_code(num6, this.bl_tree);
                            num3--;
                        }
                        this.send_code(InternalConstants.REP_3_6, this.bl_tree);
                        this.send_bits(num3 - 3, 2);
                    }
                    else if (num3 <= 10)
                    {
                        this.send_code(InternalConstants.REPZ_3_10, this.bl_tree);
                        this.send_bits(num3 - 3, 3);
                    }
                    else
                    {
                        this.send_code(InternalConstants.REPZ_11_138, this.bl_tree);
                        this.send_bits(num3 - 11, 7);
                    }
                    num3 = 0;
                    num = num6;
                    if (num2 == 0)
                    {
                        num4 = 138;
                        num5 = 3;
                    }
                    else if (num6 == num2)
                    {
                        num4 = 6;
                        num5 = 3;
                    }
                    else
                    {
                        num4 = 7;
                        num5 = 4;
                    }
                }
            }
        }
References Ionic.Zlib.DeflateManager.bl_tree, int, Ionic.Zlib.InternalConstants.REP_3_6, Ionic.Zlib.InternalConstants.REPZ_11_138, Ionic.Zlib.InternalConstants.REPZ_3_10, Ionic.Zlib.DeflateManager.send_bits(), and Ionic.Zlib.DeflateManager.send_code().
Referenced by Ionic.Zlib.DeflateManager.send_all_trees().