Terraria Decompiled: Ionic.Zlib.DeflateManager.DeflateFast
DeflateFast()
BlockState Ionic.Zlib.DeflateManager.DeflateFast (FlushType flush) inline package
Definition at line 649 of file DeflateManager.cs.
        {
            int num = 0;
            for (;;)
            {
                if (this.lookahead < DeflateManager.MIN_LOOKAHEAD)
                {
                    this._fillWindow();
                    if (this.lookahead < DeflateManager.MIN_LOOKAHEAD && flush == FlushType.None)
                    {
                        break;
                    }
                    if (this.lookahead == 0)
                    {
                        goto IL_02EA;
                    }
                }
                if (this.lookahead >= DeflateManager.MIN_MATCH)
                {
                    this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[this.strstart + (DeflateManager.MIN_MATCH - 1)] & byte.MaxValue)) & this.hash_mask;
                    num = (int)this.head[this.ins_h] & 65535;
                    this.prev[this.strstart & this.w_mask] = this.head[this.ins_h];
                    this.head[this.ins_h] = (short)this.strstart;
                }
                if ((long)num != 0L && ((this.strstart - num) & 65535) <= this.w_size - DeflateManager.MIN_LOOKAHEAD && this.compressionStrategy != CompressionStrategy.HuffmanOnly)
                {
                    this.match_length = this.longest_match(num);
                }
                bool flag;
                if (this.match_length >= DeflateManager.MIN_MATCH)
                {
                    flag = this._tr_tally(this.strstart - this.match_start, this.match_length - DeflateManager.MIN_MATCH);
                    this.lookahead -= this.match_length;
                    if (this.match_length <= this.config.MaxLazy && this.lookahead >= DeflateManager.MIN_MATCH)
                    {
                        this.match_length--;
                        do
{
                            this.strstart++;
                            this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[this.strstart + (DeflateManager.MIN_MATCH - 1)] & byte.MaxValue)) & this.hash_mask;
                            num = (int)this.head[this.ins_h] & 65535;
                            this.prev[this.strstart & this.w_mask] = this.head[this.ins_h];
                            this.head[this.ins_h] = (short)this.strstart;
                        }
                        while (--this.match_length != 0);
                        this.strstart++;
                    }
                    else
                    {
                        this.strstart += this.match_length;
                        this.match_length = 0;
                        this.ins_h = (int)(this.window[this.strstart] & byte.MaxValue);
                        this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[this.strstart + 1] & byte.MaxValue)) & this.hash_mask;
                    }
                }
                else
                {
                    flag = this._tr_tally(0, (int)(this.window[this.strstart] & byte.MaxValue));
                    this.lookahead--;
                    this.strstart++;
                }
                if (flag)
                {
                    this.flush_block_only(false);
                    if (this._codec.AvailableBytesOut == 0)
                    {
                        return BlockState.NeedMore;
                    }
                }
            }
            return BlockState.NeedMore;
            IL_02EA:
            this.flush_block_only(flush == FlushType.Finish);
            if (this._codec.AvailableBytesOut == 0)
            {
                if (flush == FlushType.Finish)
                {
                    return BlockState.FinishStarted;
                }
                return BlockState.NeedMore;
            }
            else
            {
                if (flush != FlushType.Finish)
                {
                    return BlockState.BlockDone;
                }
                return BlockState.FinishDone;
            }
        }
References Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.DeflateManager._fillWindow(), Ionic.Zlib.DeflateManager._tr_tally(), Ionic.Zlib.ZlibCodec.AvailableBytesOut, Ionic.Zlib.DeflateManager.flush_block_only(), Ionic.Zlib.DeflateManager.hash_mask, Ionic.Zlib.DeflateManager.hash_shift, Ionic.Zlib.DeflateManager.head, Ionic.Zlib.DeflateManager.ins_h, int, System.L, Ionic.Zlib.DeflateManager.longest_match(), Ionic.Zlib.DeflateManager.lookahead, Ionic.Zlib.DeflateManager.match_length, Ionic.Zlib.DeflateManager.match_start, Ionic.Zlib.DeflateManager.MIN_LOOKAHEAD, Ionic.Zlib.DeflateManager.MIN_MATCH, Ionic.Zlib.DeflateManager.prev, Ionic.Zlib.DeflateManager.strstart, Ionic.Zlib.DeflateManager.w_mask, and Ionic.Zlib.DeflateManager.window.
Referenced by Ionic.Zlib.DeflateManager.SetDeflater().