Terraria Decompiled: Ionic.Zlib.DeflateManager.Deflate
Deflate()
int Ionic.Zlib.DeflateManager.Deflate (FlushType flush) inline package
Definition at line 1080 of file DeflateManager.cs.
        {
            if (this._codec.OutputBuffer == null || (this._codec.InputBuffer == null && this._codec.AvailableBytesIn != 0) || (this.status == DeflateManager.FINISH_STATE && flush != FlushType.Finish))
            {
                this._codec.Message = DeflateManager._ErrorMessage[4];
                throw new ZlibException(string.Format("Something is fishy. [{0}]", this._codec.Message));
            }
            if (this._codec.AvailableBytesOut == 0)
            {
                this._codec.Message = DeflateManager._ErrorMessage[7];
                throw new ZlibException("OutputBuffer is full (AvailableBytesOut == 0)");
            }
            int num = this.last_flush;
            this.last_flush = (int)flush;
            if (this.status == DeflateManager.INIT_STATE)
            {
                int num2 = DeflateManager.Z_DEFLATED + (this.w_bits - 8 << 4) << 8;
                int num3 = ((this.compressionLevel - CompressionLevel.BestSpeed) & 255) >> 1;
                if (num3 > 3)
                {
                    num3 = 3;
                }
                num2 |= num3 << 6;
                if (this.strstart != 0)
                {
                    num2 |= DeflateManager.PRESET_DICT;
                }
                num2 += 31 - num2 % 31;
                this.status = DeflateManager.BUSY_STATE;
                this.pending[this.pendingCount++] = (byte)(num2 >> 8);
                this.pending[this.pendingCount++] = (byte)num2;
                if (this.strstart != 0)
                {
                    this.pending[this.pendingCount++] = (byte)((this._codec._Adler32 & 4278190080U) >> 24);
                    this.pending[this.pendingCount++] = (byte)((this._codec._Adler32 & 16711680U) >> 16);
                    this.pending[this.pendingCount++] = (byte)((this._codec._Adler32 & 65280U) >> 8);
                    this.pending[this.pendingCount++] = (byte)(this._codec._Adler32 & 255U);
                }
                this._codec._Adler32 = Adler.Adler32(0U, null, 0, 0);
            }
            if (this.pendingCount != 0)
            {
                this._codec.flush_pending();
                if (this._codec.AvailableBytesOut == 0)
                {
                    this.last_flush = -1;
                    return 0;
                }
            }
            else if (this._codec.AvailableBytesIn == 0 && flush <= (FlushType)num && flush != FlushType.Finish)
            {
                return 0;
            }
            if (this.status == DeflateManager.FINISH_STATE && this._codec.AvailableBytesIn != 0)
            {
                this._codec.Message = DeflateManager._ErrorMessage[7];
                throw new ZlibException("status == FINISH_STATE && _codec.AvailableBytesIn != 0");
            }
            if (this._codec.AvailableBytesIn != 0 || this.lookahead != 0 || (flush != FlushType.None && this.status != DeflateManager.FINISH_STATE))
            {
                BlockState blockState = this.DeflateFunction(flush);
                if (blockState == BlockState.FinishStarted || blockState == BlockState.FinishDone)
                {
                    this.status = DeflateManager.FINISH_STATE;
                }
                if (blockState == BlockState.NeedMore || blockState == BlockState.FinishStarted)
                {
                    if (this._codec.AvailableBytesOut == 0)
                    {
                        this.last_flush = -1;
                    }
                    return 0;
                }
                if (blockState == BlockState.BlockDone)
                {
                    if (flush == FlushType.Partial)
                    {
                        this._tr_align();
                    }
                    else
                    {
                        this._tr_stored_block(0, 0, false);
                        if (flush == FlushType.Full)
{
                            for (int i = 0; i < this.hash_size; i++)
{
                                this.head[i] = 0;
                            }
                        }
                    }
                    this._codec.flush_pending();
                    if (this._codec.AvailableBytesOut == 0)
                    {
                        this.last_flush = -1;
                        return 0;
                    }
                }
            }
            if (flush != FlushType.Finish)
            {
                return 0;
            }
            if (!this.WantRfc1950HeaderBytes || this.Rfc1950BytesEmitted)
            {
                return 1;
            }
            this.pending[this.pendingCount++] = (byte)((this._codec._Adler32 & 4278190080U) >> 24);
            this.pending[this.pendingCount++] = (byte)((this._codec._Adler32 & 16711680U) >> 16);
            this.pending[this.pendingCount++] = (byte)((this._codec._Adler32 & 65280U) >> 8);
            this.pending[this.pendingCount++] = (byte)(this._codec._Adler32 & 255U);
            this._codec.flush_pending();
            this.Rfc1950BytesEmitted = true;
            if (this.pendingCount == 0)
            {
                return 1;
            }
            return 0;
        }
References Ionic.Zlib.ZlibCodec._Adler32, Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.DeflateManager._ErrorMessage, Ionic.Zlib.DeflateManager._tr_align(), Ionic.Zlib.DeflateManager._tr_stored_block(), Ionic.Zlib.Adler.Adler32(), Ionic.Zlib.ZlibCodec.AvailableBytesIn, Ionic.Zlib.ZlibCodec.AvailableBytesOut, Ionic.Zlib.DeflateManager.BUSY_STATE, Ionic.Zlib.DeflateManager.DeflateFunction, Ionic.Zlib.DeflateManager.FINISH_STATE, Ionic.Zlib.ZlibCodec.flush_pending(), System.Format, Ionic.Zlib.DeflateManager.hash_size, Ionic.Zlib.DeflateManager.head, Ionic.Zlib.DeflateManager.INIT_STATE, int, Ionic.Zlib.DeflateManager.last_flush, Ionic.Zlib.ZlibCodec.Message, Ionic.Zlib.ZlibCodec.OutputBuffer, Ionic.Zlib.DeflateManager.pending, Ionic.Zlib.DeflateManager.pendingCount, Ionic.Zlib.DeflateManager.PRESET_DICT, Ionic.Zlib.DeflateManager.Rfc1950BytesEmitted, Ionic.Zlib.DeflateManager.status, Ionic.Zlib.DeflateManager.strstart, System.U, and Ionic.Zlib.DeflateManager.WantRfc1950HeaderBytes.
Referenced by Ionic.Zlib.ZlibCodec.Deflate().