Terraria Decompiled: Ionic.Zlib.DeflateManager._fillWindow
_fillWindow()
void Ionic.Zlib.DeflateManager._fillWindow () inline private
Definition at line 592 of file DeflateManager.cs.
        {
            for (;;)
            {
                int num = this.window_size - this.lookahead - this.strstart;
                int num2;
                if (num == 0 && this.strstart == 0 && this.lookahead == 0)
                {
                    num = this.w_size;
                }
                else if (num == -1)
                {
                    num--;
                }
                else if (this.strstart >= this.w_size + this.w_size - DeflateManager.MIN_LOOKAHEAD)
                {
                    Array.Copy(this.window, this.w_size, this.window, 0, this.w_size);
                    this.match_start -= this.w_size;
                    this.strstart -= this.w_size;
                    this.block_start -= this.w_size;
                    num2 = this.hash_size;
                    int num3 = num2;
                    do
                    {
                        int num4 = (int)this.head[--num3] & 65535;
                        this.head[num3] = (short)((num4 >= this.w_size) ? (num4 - this.w_size) : 0);
                    }
                    while (--num2 != 0);
                    num2 = this.w_size;
                    num3 = num2;
                    do
                    {
                        int num4 = (int)this.prev[--num3] & 65535;
                        this.prev[num3] = (short)((num4 >= this.w_size) ? (num4 - this.w_size) : 0);
                    }
                    while (--num2 != 0);
                    num += this.w_size;
                }
                if (this._codec.AvailableBytesIn == 0)
                {
                    break;
                }
                num2 = this._codec.read_buf(this.window, this.strstart + this.lookahead, num);
                this.lookahead += num2;
                if (this.lookahead >= DeflateManager.MIN_MATCH)
                {
                    this.ins_h = (int)(this.window[this.strstart] & byte.MaxValue);
                    this.ins_h = ((this.ins_h << this.hash_shift) ^ (int)(this.window[this.strstart + 1] & byte.MaxValue)) & this.hash_mask;
                }
                if (this.lookahead >= DeflateManager.MIN_LOOKAHEAD || this._codec.AvailableBytesIn == 0)
                {
                    return;
                }
            }
        }
References Ionic.Zlib.DeflateManager._codec, Ionic.Zlib.ZlibCodec.AvailableBytesIn, System.Array.Copy(), Ionic.Zlib.DeflateManager.hash_mask, Ionic.Zlib.DeflateManager.hash_shift, Ionic.Zlib.DeflateManager.hash_size, Ionic.Zlib.DeflateManager.head, int, Ionic.Zlib.DeflateManager.lookahead, Ionic.Zlib.DeflateManager.MIN_LOOKAHEAD, Ionic.Zlib.DeflateManager.MIN_MATCH, Ionic.Zlib.DeflateManager.prev, Ionic.Zlib.ZlibCodec.read_buf(), Ionic.Zlib.DeflateManager.strstart, Ionic.Zlib.DeflateManager.w_size, and Ionic.Zlib.DeflateManager.window.
Referenced by Ionic.Zlib.DeflateManager.DeflateFast(), Ionic.Zlib.DeflateManager.DeflateNone(), and Ionic.Zlib.DeflateManager.DeflateSlow().