Terraria Decompiled: Ionic.Zlib.DeflateManager._tr_align
_tr_align()
void Ionic.Zlib.DeflateManager._tr_align () inline package
Definition at line 291 of file DeflateManager.cs.
        {
            this.send_bits(DeflateManager.STATIC_TREES << 1, 3);
            this.send_code(DeflateManager.END_BLOCK, StaticTree.lengthAndLiteralsTreeCodes);
            this.bi_flush();
            if (1 + this.last_eob_len + 10 - this.bi_valid < 9)
            {
                this.send_bits(DeflateManager.STATIC_TREES << 1, 3);
                this.send_code(DeflateManager.END_BLOCK, StaticTree.lengthAndLiteralsTreeCodes);
                this.bi_flush();
            }
            this.last_eob_len = 7;
        }
References Ionic.Zlib.DeflateManager.bi_flush(), Ionic.Zlib.DeflateManager.bi_valid, Ionic.Zlib.DeflateManager.END_BLOCK, Ionic.Zlib.DeflateManager.last_eob_len, Ionic.Zlib.StaticTree.lengthAndLiteralsTreeCodes, Ionic.Zlib.DeflateManager.send_bits(), Ionic.Zlib.DeflateManager.send_code(), and Ionic.Zlib.DeflateManager.STATIC_TREES.
Referenced by Ionic.Zlib.DeflateManager.Deflate().