Terraria Decompiled: Ionic.Zlib.DeflateManager.send_compressed_block
send_compressed_block()
void Ionic.Zlib.DeflateManager.send_compressed_block (short[] ltree, short[] dtree) inline package
Definition at line 347 of file DeflateManager.cs.
        {
            int num = 0;
            if (this.last_lit != 0)
            {
                do
                {
                    int num2 = this._distanceOffset + num * 2;
                    int num3 = (((int)this.pending[num2] << 8) & 65280) | (int)(this.pending[num2 + 1] & byte.MaxValue);
                    int num4 = (int)(this.pending[this._lengthOffset + num] & byte.MaxValue);
                    num++;
                    if (num3 == 0)
                    {
                        this.send_code(num4, ltree);
                    }
                    else
                    {
                        int num5 = (int)Tree.LengthCode[num4];
                        this.send_code(num5 + InternalConstants.LITERALS + 1, ltree);
                        int num6 = Tree.ExtraLengthBits[num5];
                        if (num6 != 0)
{
                            num4 -= Tree.LengthBase[num5];
                            this.send_bits(num4, num6);
                        }
                        num3--;
                        num5 = Tree.DistanceCode(num3);
                        this.send_code(num5, dtree);
                        num6 = Tree.ExtraDistanceBits[num5];
                        if (num6 != 0)
{
                            num3 -= Tree.DistanceBase[num5];
                            this.send_bits(num3, num6);
                        }
                    }
                }
                while (num < this.last_lit);
            }
            this.send_code(DeflateManager.END_BLOCK, ltree);
            this.last_eob_len = (int)ltree[DeflateManager.END_BLOCK * 2 + 1];
        }
References Ionic.Zlib.DeflateManager._lengthOffset, Ionic.Zlib.Tree.DistanceBase, Ionic.Zlib.Tree.DistanceCode(), Ionic.Zlib.DeflateManager.END_BLOCK, Ionic.Zlib.Tree.ExtraDistanceBits, Ionic.Zlib.Tree.ExtraLengthBits, int, Ionic.Zlib.DeflateManager.last_lit, Ionic.Zlib.Tree.LengthBase, Ionic.Zlib.Tree.LengthCode, Ionic.Zlib.InternalConstants.LITERALS, Ionic.Zlib.DeflateManager.pending, Ionic.Zlib.DeflateManager.send_bits(), and Ionic.Zlib.DeflateManager.send_code().
Referenced by Ionic.Zlib.DeflateManager._tr_flush_block().