Terraria Decompiled: Terraria.Utilities.UnifiedRandom.SetSeed
SetSeed()
void Terraria.Utilities.UnifiedRandom.SetSeed (int Seed) inline
Definition at line 22 of file UnifiedRandom.cs.
        {
            for (int i = 0; i < this.SeedArray.Length; i++)
            {
                this.SeedArray[i] = 0;
            }
            int num = ((Seed == int.MinValue) ? int.MaxValue : Math.Abs(Seed));
            int num2 = 161803398 - num;
            this.SeedArray[55] = num2;
            int num3 = 1;
            for (int j = 1; j < 55; j++)
            {
                int num4 = 21 * j % 55;
                this.SeedArray[num4] = num3;
                num3 = num2 - num3;
                if (num3 < 0)
                {
                    num3 += int.MaxValue;
                }
                num2 = this.SeedArray[num4];
            }
            for (int k = 1; k < 5; k++)
            {
                for (int l = 1; l < 56; l++)
                {
                    this.SeedArray[l] -= this.SeedArray[1 + (l + 30) % 55];
                    if (this.SeedArray[l] < 0)
                    {
                        this.SeedArray[l] += int.MaxValue;
                    }
                }
            }
            this.inext = 0U;
        }
References System.Math.Abs(), Terraria.Utilities.UnifiedRandom.SeedArray, and System.U.
Referenced by Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProjDirect(), and Terraria.Utilities.UnifiedRandom.UnifiedRandom().