Terraria Decompiled: Terraria.Utilities.UnifiedRandom.Next
Next() [1/3]
int Terraria.Utilities.UnifiedRandom.Next () inline
Definition at line 105 of file UnifiedRandom.cs.
        {
            return this.InternalSample();
        }
References Terraria.Utilities.UnifiedRandom.InternalSample().
Referenced by Terraria.GameContent.Skies.SolarSky.Activate(), Terraria.GameContent.Skies.StardustSky.Activate(), Terraria.WorldGen.AddBuriedChest(), Terraria.Cloud.addCloud(), Terraria.GameContent.Events.MoonlordDeathDrama.AddExplosion(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.AddMonsterVoiceChangeItemToChest(), Terraria.WorldGen.AddPasses(), Terraria.WorldGen.AddSpikeCaves(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.WorldGen.AddTrees(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_001_Slimes_GenerateItemInsideBody(), Terraria.NPC.AI_002_FloatingEye(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_AttemptToPlayIdleAnimationsForPets(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TryForcingSitting(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Dust(), Terraria.NPC.AI_015_KingSlime(), Terraria.NPC.AI_015_KingSlime_FindTeleportSpot(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_019_Spears_Old(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_061_FishingBobber(), Terraria.Projectile.AI_061_FishingBobber_GiveItemToPlayer(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_100_Medusa(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_116_WaterStriders(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_118_Seahorses(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss_DoMagicEffect(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.NPC.AI_126_StatueMimic(), Terraria.NPC.AI_127_Pal(), Terraria.Projectile.AI_130_FlameBurstTower(), Terraria.Projectile.AI_131_FlameBurstShot(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_140_MonkStaffT1(), Terraria.Projectile.AI_142_MonkStaffT2And3(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Projectile.AI_153_ToiletPop(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_155_SpawnRopeIn(), Terraria.Projectile.AI_156_Think(), Terraria.Projectile.AI_157_SharpTears(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_163_Chum(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_166_Dove(), Terraria.Projectile.AI_168_FirstFractal(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_175_TitaniumStormShards(), Terraria.Projectile.AI_176_EdgyLightning(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_178_FireExplosion(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_181_FairyQueenRangedItemShot(), Terraria.Projectile.AI_184_BadTorchLuck(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Projectile.AI_189_Volcano(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.Projectile.AI_193_Flamethrower(), Terraria.Projectile.AI_194_HorsemanPumpkin(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_196_Petal(), Terraria.Projectile.AI_197_CeilingAndHoverTurret(), Terraria.Projectile.AI_197_HandleTileCollision(), Terraria.Projectile.AI_198_Flint(), Terraria.Projectile.AI_199_MeteorOre(), Terraria.Projectile.AI_200_BirdDroppings(), Terraria.Projectile.AI_202_TorchGodHelper(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Projectile.AI_204_Digtoise(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.NPC.AI_87_BigMimic_FireStuffCannonBurst(), Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks(), Terraria.NPC.AI_FindNearbyBook(), Terraria.Main.AnglerQuestSwap(), Terraria.Main.AnimateTiles(), Terraria.Main.AnimateTiles_CritterCages(), Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyLifeAndOrMana(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.Player.ApplyPotionDelay(), Terraria.Player.ApplyTouchDamage(), Terraria.Projectile.ApplyWhipDebuffs(), Terraria.Player.ApplyWilsonBeard(), Terraria.Player.ArmorSetDye(), Terraria.GameContent.Skies.MartianSky.Ufo.AssignNewBehavior(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.AttemptClaim(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners(), Terraria.Lang.BartenderChat(), Terraria.Player.beeDamage(), Terraria.Player.beeType(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.BiomeChests(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.BiomeChests_DualDungeons(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_GrassySurface(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SandySurface(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SnowySurface(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.Projectile.BoulderExplosion(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceRoom(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformAndDoorsOnHallway(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateStartingRoom(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Caverer(), Terraria.WorldGen.Cavinator(), Terraria.Main.ChangeRain(), Terraria.GameContent.Events.Sandstorm.ChangeSeverityIntentions(), Terraria.WorldGen.ChasmRunner(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.NPC.checkDead(), Terraria.NPC.CheckDrowning(), Terraria.Player.CheckDrowning(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPalmTree(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckSign(), Terraria.NPC.Spawner.CheckToSpawnRockGolem(), Terraria.NPC.Spawner.CheckToSpawnSpider(), Terraria.NPC.Spawner.CheckToSpawnUndergroundGnomes(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.Player.ChickenBonesWingDust(), Terraria.HitTile.HitTileObject.Clear(), Terraria.WorldGen.CloseDoor(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.NPC.Collision_WaterCollision(), Terraria.WorldGen.Convert(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.WorldGen.ConvertTreeAndGround(), Terraria.Lang.CreateDeathMessage(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.WorldGen.CrimEnt(), Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.CrimVein(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.Damage_PVP(), Terraria.Main.DamageVar(), Terraria.Player.DashMovement(), Terraria.Main.DedServ(), Terraria.Player.DemonConch(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.digTunnel(), Terraria.WorldGen.DirtyRockRunner(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoAddTeleporters(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho(), Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts(), Terraria.WorldGen.SecretSeed.DoDigExtraHoles(), Terraria.WorldGen.SecretSeed.DoErrorWorldFindChestItem(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoErrorWorldGetRandomBlock(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddLiquid(), Terraria.Player.DoEyebrellaRainEffect(), Terraria.Player.DoGlassSlipperSparkles(), Terraria.WorldGen.SecretSeed.DoHallowOnSurface(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance_TreeOnPillar(), Terraria.WorldGen.SecretSeed.DoNoSurfaceFillTheTop(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.WorldGen.SecretSeed.DoPaintEverythingGray(), Terraria.WorldGen.SecretSeed.DoPaintEverythingNegative(), Terraria.WorldGen.SecretSeed.DoPooEverywhere(), Terraria.WorldGen.SecretSeed.DoPortalGunInChests(), Terraria.Projectile.DoRainbowCrystalStaffExplosion(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert(), Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms(), Terraria.Player.DoubleJumpVisuals(), Terraria.Main.DoUpdate(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozen(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozenFinish(), Terraria.WorldGen.SecretSeed.DoWorldIsInfected(), Terraria.GameContent.Drawing.TileDrawing.DrawAnimatedTile_AdjustForVisionChangers(), Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.Main.DrawItem(), Terraria.Main.DrawMenu(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileGrassInWind(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Main.DrawSunAndMoon(), Terraria.Main.DrawSurfaceBG_Mushroom(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.Projectile.DropGeodeGems(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC(), Terraria.WorldGen.dropMeteor(), Terraria.Player.DropTombstone(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralHallType(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralRoomType(), Terraria.WorldGen.DungeonDesertCleanup(), Terraria.Lang.DyeTraderQuestChat(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.GameContent.Drawing.TileDrawing.EmitAlchemyHerbParticles(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf(), Terraria.Player.EmitMaxManaEffect(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.NPC.FairyEffects(), Terraria.Star.Fall(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindBoulderTrapSpots(), Terraria.NPC.FindCattailTop(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpots(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindExplosiveTrapSpots(), Terraria.NPC.FindFrame(), Terraria.Player.FindSharpTearsSpot(), Terraria.NPC.Spawner.FindSpawnTile(), Terraria.NPC.FindTreeBranch(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.FinishTenthAnniversaryWorld(), Terraria.Projectile.FishingCheck(), Terraria.Projectile.FishingCheck_RollDropLevels(), Terraria.Projectile.FishingCheck_RollEnemySpawns(), Terraria.Projectile.FishingCheck_RollItemDropOld(), Terraria.WorldGen.FixSunflower(), Terraria.WorldGen.FloatingIsland(), Terraria.WorldGen.Spread.Gem(), Terraria.WorldGen.gemCave(), Terraria.GameContent.Biomes.Desert.DesertHive.ClusterGroup.Generate(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate(), Terraria.GameContent.Skies.PartySky.GenerateBalloons(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonBook(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonPot(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonPotionBottle(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonRegularChest(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateFloatingRocksInArea(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateHangingLeafCluster(), Terraria.GameContent.Skies.LanternSky.GenerateLanterns(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom(), Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateRockPlatform(), Terraria.WorldGen.GenerateSkyBlockWorld(), Terraria.GameContent.Skies.SlimeSky.GenerateSlimes(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothem(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothemsInArea(), Terraria.WorldGen.GenerateUnderworldStartingMound(), Terraria.WorldGen.GERunner(), Terraria.Projectile.GetAlpha(), Terraria.Player.GetAnglerReward_Bait(), Terraria.Player.GetAnglerReward_Decoration(), Terraria.Player.GetAnglerReward_MainReward(), Terraria.Player.GetAnglerReward_Money(), Terraria.NPC.Spawner.GetBasicSlimeToSpawn(), Terraria.NPC.Spawner.GetBasicSlimeToSpawn_ChanceToBeHolidaySlime(), Terraria.NPC.GetChat(), Terraria.Player.GetDyeTraderReward(), Terraria.WorldGen.GetFruitForPot(), Terraria.NPC.Spawner.GetGemBunnyToSpawn(), Terraria.NPC.Spawner.GetGemSquirrelToSpawn(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetHallwayConnectionPoint(), Terraria.WorldGen.GetNextJungleChestItem(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.GetPlatformStyle(), Terraria.WorldBuilding.WorldGenRange.GetRandom(), Terraria.GameContent.FlexibleTileWand.OptionBucket.GetRandomOption(), Terraria.Audio.CustomSoundStyle.GetRandomSound(), Terraria.WorldGen.GetRandomStatueStyleForStatueMimics(), Terraria.Item.GetRandomVoiceItem(), Terraria.NPC.Spawner.GetSpawnRate(), Terraria.NPC.GetStackForSlimeItemDrop(), Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.GetWindowPlatformStyle(), Terraria.NPC.Spawner.GetZombieSettings(), Terraria.Projectile.ghostHurt(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_GetFurnitureItem(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowGlowTulips(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.GrowWeb(), Terraria.Dust.HackFrame(), Terraria.Main.HandleMeteorFall(), Terraria.Projectile.HandleMovement(), Terraria.WorldGen.hardUpdateWorld(), Terraria.NPC.HasLuckTextForWizard(), Terraria.NPC.HasSpecialEventText(), Terraria.WorldGen.HellFort(), Terraria.WorldGen.HellHouse(), Terraria.Player.HeroicisWingDust(), Terraria.NPC.HitEffect(), Terraria.Player.HorizontalMovement(), Terraria.Player.HorsemansBlade_SpawnPumpkin(), Terraria.Player.Hurt(), Terraria.NPC.IdleSounds(), Terraria.Main.Initialize(), Terraria.WorldGen.initializeHardMode(), Terraria.GameContent.Skies.MartianSky.ZipBehavior.InitializeUfo(), Terraria.GameContent.Skies.MartianSky.HoverBehavior.InitializeUfo(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.WorldGen.IslandHouse(), Terraria.Player.ItemCheck(), Terraria.Player.ItemCheck_ApplyHoldStyle(), Terraria.Player.ItemCheck_ApplyPetBuffs(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_CheckFishingBobber_ConsumeBait(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_EmitDrinkParticles(), Terraria.Player.ItemCheck_EmitFoodParticles(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Player.ItemCheck_EmitUseVisuals(), Terraria.Player.ItemCheck_GetMeleeHitboxParticles(), Terraria.Player.ItemCheck_ManageRightClickFeatures_ShieldRaise(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_OwnerOnlyCode(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseTeleportRod(), Terraria.Player.JumpMovement(), Terraria.Player.KazzymodusWingDust(), Terraria.Player.KillMe(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.WorldGen.KillTile_GetTreeDrops(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillTile_PlaySounds(), Terraria.WorldGen.KillTile_ShouldDropSeeds(), Terraria.WorldGen.KillWall_MakeWallDust(), Terraria.Projectile.KiteLogic(), Terraria.WorldGen.Lakinater(), Terraria.WorldGen.LaunchRocketSmall(), Terraria.WorldGen.LavaLayerCaverer(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.LegacyDungeonLayoutProvider.LegacyDungeonLayout(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.Projectile.LightningKillLambda_Step(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.LivingTreeRoom(), Terraria.IO.WorldFile.LoadHeader(), Terraria.Initializers.AssetInitializer.LoadSplashAssets(), Terraria.IO.WorldFile.LoadWorld(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Legacy(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GenerateNextEntranceHall_Precalculated(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetEntranceSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHallSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings(), Terraria.Player.MakeFloorDust(), Terraria.WorldGen.makeTemple(), Terraria.NPC.MakeTransitionEffectsForTextureChanges(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.MatureTheHerbPlants(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.Player.ModifyFlexibleWandPlacementInfo(), Terraria.WorldGen.Mountinater(), Terraria.WorldGen.MudWallRunner(), Terraria.WorldGen.nearbyChlorophyte(), Terraria.WorldGen.neonMossBiome(), Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Main.NewLightning(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utils.Next(), Terraria.Utils.NextFromCollection< T >(), Terraria.Utils.NextFromList< T >(), Terraria.Utils.NextFromRectangle(), Terraria.Star.NightSetup(), Terraria.Player.NinjaDodge(), Terraria.WorldGen.NotTheBees(), Terraria.Main.NPCChatText_DoNurseHeal(), Terraria.Main.NPCChatText_DoTaxCollector(), Terraria.Main.NPCChatText_PartyGirlSwapMusic(), Terraria.NPC.NPCLoot_DropCommonLifeAndMana(), Terraria.NPC.NPCLoot_DropDungeonStuff(), Terraria.NPC.NPCLoot_DropHeals(), Terraria.NPC.NPCLoot_DropLihzahrdStuff(), Terraria.NPC.NPCLoot_DropMoney(), Terraria.NPC.NPCLoot_DropTempleTraps(), Terraria.WorldGen.oceanCave(), Terraria.Main.oldDrawWater(), Terraria.Player.OnHit(), Terraria.Player.OpenBossBag(), Terraria.Player.OpenCanofWorms(), Terraria.Player.OpenChilletEgg(), Terraria.Player.OpenFishingCrate(), Terraria.Player.OpenGoodieBag(), Terraria.Player.OpenHerbBag(), Terraria.Player.OpenLegacyPresent(), Terraria.Player.OpenLockBox(), Terraria.Player.OpenOyster(), Terraria.Player.OpenPresent(), Terraria.WorldGen.OrePatch(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.OverGrownDungeon(), Terraria.WorldGen.OverGrownDungeonWithRainbowMoss(), Terraria.WorldGen.paintCoatEffect(), Terraria.WorldGen.paintEffect(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_RandomBonePainting(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_RandomDungeonPainting(), Terraria.WorldGen.PaintTheMushrooms(), Terraria.WorldGen.PaintTheTrees(), Terraria.Player.PickAmmo(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.Place(), Terraria.WorldGen.Place1x1(), Terraria.WorldGen.Place1x2(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.PlaceAt(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChilletEggs(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlacePumpkin(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceSunflower(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AdjustPlants(), Terraria.Player.PlaceThing_Tiles_PlaceIt_GetLegacyTileStyle(), Terraria.WorldGen.PlaceTight(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceTorchesAroundSpawn(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.PlantCactus(), Terraria.WorldGen.plantDye(), Terraria.WorldGen.PlantSeaOat(), Terraria.Player.PlayerFrame(), Terraria.Player.PlayGuitarChord(), Terraria.Player.PlayHurtSound(), Terraria.Utils.PoofOfSmoke(), Terraria.NPC.Spawner.PostCheckChosenSpawnTile(), Terraria.Main.PostContentLoadInitialize(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PotentiallyConvertToRainbowBrick(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PotentiallyConvertToRainbowMossBlock(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PotentiallyConvertToSeedHouse(), Terraria.Item.Prefix(), Terraria.WorldGen.PrefixItemFromOptions(), Terraria.Projectile.PrepareFishingContext(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.Projectile.ProjLight(), Terraria.WorldGen.PutMonsterVanityInChests(), Terraria.WorldGen.Pyramid(), Terraria.Player.QuickBuff_ShouldUseItem(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.RainbowifyOnTenthAnniversaryWorlds(), Terraria.Main.randColor(), Terraria.WorldGen.randGem(), Terraria.WorldGen.randGemTile(), Terraria.WorldGen.RandHellPicture(), Terraria.WorldGen.RandHousePicture(), Terraria.WorldGen.RandHousePictureDesert(), Terraria.WorldGen.randMoss(), Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer(), Terraria.WorldGen.RandomizeBackgrounds(), Terraria.WorldGen.RandomizeBackgrounds_Corruption(), Terraria.WorldGen.RandomizeBackgrounds_Desert(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.Projectile.RandomizeInsanityShadowFor(), Terraria.WorldGen.RandomizeMoonState(), Terraria.WorldGen.RandomizeTreeStyle(), Terraria.GameContent.TreeTopsInfo.RandomizeTreeStyle(), Terraria.WorldGen.RandomizeWeather(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.RandomPointInBounds(), Terraria.WorldGen.RandomRectanglePoint(), Terraria.WorldGen.RandomRectanglePoint(), Terraria.WorldGen.RandomWorldPoint(), Terraria.NPC.ReflectProjectile(), Terraria.GameContent.Generation.Dungeon.Rooms.RegularDungeonRoom.RegularRoom(), Terraria.NPC.ReleaseNPC(), Terraria.WorldGen.Reset(), Terraria.GameContent.Skies.PartySky.ResetBalloon(), Terraria.GameContent.Skies.LanternSky.ResetLantern(), Terraria.Player.RocketBootVisuals(), Terraria.Item.RollAPrefix(), Terraria.WorldGen.RollRandomForestBGStyle(), Terraria.WorldGen.RollRandomSeaShellStyle(), Terraria.Cloud.RollRareCloud(), Terraria.WorldBuilding.WorldGenerator.RunPass(), Terraria.Utils.SelectRandom< T >(), Terraria.Projectile.SetDefaults(), Terraria.NPC.setFireFlyChance(), Terraria.Projectile.SetFishingCheckResults(), Terraria.WorldGen.SetGemTreeDrops(), Terraria.NPC.Spawner.SetSpawnFlagsForChosenTile(), Terraria.Main.SetTitle(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonDataVariables(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonGenVarVariables(), Terraria.WorldGen.SetVanityTreeDrops(), Terraria.NPC.SetWorldSpecificMonstersByWorldID(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.NPC.Spawner.ShouldSpawnInvasionEnemies(), Terraria.WorldGen.ShroomPatch(), Terraria.WorldGen.SkyblockIsland(), Terraria.NPC.Spawner.SlimeRainSpawns(), Terraria.WorldGen.SmashAltar(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Main.snowing(), Terraria.WorldGen.SonOfLakinater(), Terraria.GameContent.LeashedEntities.LeashedCritter.Spawn(), Terraria.GameContent.AmbientWindSystem.SpawnAirborneCloud(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.NPC.Spawner.SpawnFaelings(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.Player.SpawnFastRunParticles(), Terraria.GameContent.AmbientWindSystem.SpawnFloorCloud(), Terraria.WorldGen.SpawnGraveyardBiome(), Terraria.WorldGen.SpawnGraveyardBiomesEverywhere(), Terraria.Player.SpawnHallucination(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.NPC.Spawner.SpawnHornet(), Terraria.NPC.Spawner.SpawnLavaBaitCritters(), Terraria.Projectile.SpawnMoonLordWhipProc(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.NPC.SpawnStardustMark_StardustTower(), Terraria.NPC.SpawnStardustMark_StardustWorm(), Terraria.WorldGen.SpawnStormLightning(), Terraria.WorldGen.SpawnStormLightningNearPlayer(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.Projectile.SpawnWebs(), Terraria.WorldGen.Spread.Spider(), Terraria.WorldGen.SpiderWallRemover(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.Spikes(), Terraria.Player.SporeSac(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.WorldGen.SpreadGrassWalls(), Terraria.Main.StartInvasion(), Terraria.WorldGen.StartMeteorShower(), Terraria.Main.StartRain(), Terraria.GameContent.Events.Sandstorm.StartSandstorm(), Terraria.Main.StartSlimeRain(), Terraria.WorldGen.Statue(), Terraria.Player.StatusFromNPC(), Terraria.Projectile.StatusNPC(), Terraria.Projectile.StatusPlayer(), Terraria.Projectile.StatusPvP(), Terraria.Player.StatusToNPC(), Terraria.Player.StatusToPlayerPvP(), Terraria.Player.StickyMovement(), Terraria.NPC.StingerExplosion(), Terraria.WorldGen.StonePatch(), Terraria.Main.StopSlimeRain(), Terraria.NPC.StrikeNPC(), Terraria.Projectile.SummonMonkGhast(), Terraria.Main.TeleportEffect(), Terraria.WorldGen.templePart2(), Terraria.WorldGen.templePather(), Terraria.GameContent.AmbientWindSystem.TestAirCloud(), Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.Player.TileInteractionsUse(), Terraria.WorldGen.TileRunner(), Terraria.Player.TorchAttack(), Terraria.Player.TorchGodsFlavor(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_TreeOnPillar(), Terraria.NPC.TransformVisuals(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalTraps.Traps(), Terraria.WorldGen.TreeGrowFX_AshShake(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.Main.TryApplyingPlayerStringColor(), Terraria.Projectile.TryBuildFishingContext(), Terraria.Player.TryDroppingSingleItem(), Terraria.Player.TryGettingDevArmor(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.WorldGen.TryPlacingChilletEgg(), Terraria.NPC.Spawner.TrySpawnAnNPC(), Terraria.WorldGen.TrySpawningTownNPC(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.WorldGen.TrySpawnLightningBolt(), Terraria.Player.TryToPoop(), Terraria.WorldGen.TuneOceanDepth(), Terraria.GameContent.Biomes.DeadMansChestBiome.TurnGoldChestIntoDeadMansChest(), Terraria.Cloud.Update(), Terraria.Gore.Update(), Terraria.Player.RabbitOrderFrameHelper.Update(), Terraria.GameContent.Skies.LanternSky.Update(), Terraria.GameContent.Skies.PartySky.Update(), Terraria.GameContent.Skies.SlimeSky.Update(), Terraria.GameContent.Skies.VortexSky.Update(), Terraria.Player.Update(), Terraria.Projectile.Update(), Terraria.Gore.UpdateAmbientAirborneCloud(), Terraria.Player.UpdateArmorSets_Always_Beetle(), Terraria.Main.UpdateAudio_DecideOnNewMusic(), Terraria.Player.UpdateBuffs(), Terraria.Main.updateCloudLayer(), Terraria.Cloud.UpdateClouds(), Terraria.Main.UpdateDragonflyJarFrame(), Terraria.Dust.UpdateDust(), Terraria.Gore.UpdateFogMachineCloud(), Terraria.Player.UpdateHairDyeDust(), Terraria.Player.UpdateLifeRegen(), Terraria.Gore.UpdateLightningBunnySparks(), Terraria.Player.UpdateManaRegen(), Terraria.Main.UpdateMenu(), Terraria.NPC.UpdateNPC(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.NPC.UpdateNPC_CastLights(), Terraria.NPC.UpdateNPC_CritterSounds(), Terraria.NPC.UpdateNPC_SoulDrainDebuff(), Terraria.NPC.UpdateNPC_TeleportVisuals(), Terraria.Main.UpdateOwlCageFrame(), Terraria.WorldGen.UpdateStalagtiteStyle(), Terraria.Player.UpdateTeleportVisuals(), Terraria.GameContent.Events.Sandstorm.UpdateTime(), Terraria.Main.UpdateTime(), Terraria.Main.UpdateTime_SpawnTownNPCs(), Terraria.Main.UpdateTime_StartDay(), Terraria.Main.UpdateTime_StartNight(), Terraria.Main.UpdateWeather(), Terraria.WorldGen.UpdateWorld(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants(), Terraria.WorldGen.WavyCaverer(), Terraria.Player.WingAirVisuals(), Terraria.Player.WingFrame(), and Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom().