Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.InitializeFromCollection
InitializeFromCollection()
void System.Collections.Concurrent.ConcurrentQueue< T >.InitializeFromCollection (IEnumerable< T > collection) inline private
Definition at line 24 of file ConcurrentQueue.cs.
        {
            this._crossSegmentLock = new object();
            int num = 32;
            ICollection<T> collection2 = collection as ICollection<T>;
            if (collection2 != null)
            {
                int count = collection2.Count;
                if (count > num)
                {
                    num = Math.Min(ConcurrentQueue<T>.Segment.RoundUpToPowerOf2(count), 1048576);
                }
            }
            this._tail = (this._head = new ConcurrentQueue<T>.Segment(num));
            foreach (T t in collection)
            {
                this.Enqueue(t);
            }
        }
References System.collection, System.Collections.ICollection.Count, System.count, System.Collections.Concurrent.ConcurrentQueue< T >.Enqueue(), System.Math.Min(), and System.Collections.Concurrent.ConcurrentQueue< T >.Segment.RoundUpToPowerOf2().
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.ConcurrentQueue().