Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.CopyTo
CopyTo() [2/2]
void System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo (T[] array, int index) inline
Implements System.Collections.Concurrent.IProducerConsumerCollection< T >.
Definition at line 230 of file ConcurrentQueue.cs.
        {
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index", "The index argument must be greater than or equal zero.");
            }
            ConcurrentQueue<T>.Segment segment;
            int num;
            ConcurrentQueue<T>.Segment segment2;
            int num2;
            this.SnapForObservation(out segment, out num, out segment2, out num2);
            long count = ConcurrentQueue<T>.GetCount(segment, num, segment2, num2);
            if ((long)index > (long)array.Length - count)
            {
                throw new ArgumentException("The number of elements in the collection is greater than the available space from index to the end of the destination array.");
            }
            int num3 = index;
            using (IEnumerator<T> enumerator = this.Enumerate(segment, num, segment2, num2))
            {
                while (enumerator.MoveNext())
                {
                    T t = enumerator.Current;
                    array[num3++] = t;
                }
            }
        }
References System.array, System.count, System.Collections.IEnumerator.Current, System.Collections.Concurrent.ConcurrentQueue< T >.Enumerate(), System.Collections.Concurrent.ConcurrentQueue< T >.GetCount(), System.index, System.Collections.IEnumerator.MoveNext(), and System.Collections.Concurrent.ConcurrentQueue< T >.SnapForObservation().