Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.Enumerate
Enumerate()
IEnumerator< T > System.Collections.Concurrent.ConcurrentQueue< T >.Enumerate (ConcurrentQueue< T >::Segment head, int headHead, ConcurrentQueue< T >::Segment tail, int tailTail) inline private
Definition at line 312 of file ConcurrentQueue.cs.
        {
            int headTail = ((head == tail) ? tailTail : Volatile.Read(ref head._headAndTail.Tail)) - head.FreezeOffset;
            if (headHead < headTail)
            {
                headHead &= head._slotsMask;
                headTail &= head._slotsMask;
                if (headHead < headTail)
                {
                    int num;
                    for (int i = headHead; i < headTail; i = num + 1)
                    {
                        yield return this.GetItemWhenAvailable(head, i);
                        num = i;
                    }
                }
                else
                {
                    int num;
                    for (int i = headHead; i < head._slots.Length; i = num + 1)
                    {
                        yield return this.GetItemWhenAvailable(head, i);
                        num = i;
                    }
                    for (int i = 0; i < headTail; i = num + 1)
                    {
                        yield return this.GetItemWhenAvailable(head, i);
                        num = i;
                    }
                }
            }
            if (head != tail)
            {
                int num;
                ConcurrentQueue<T>.Segment s;
                for (s = head._nextSegment; s != tail; s = s._nextSegment)
                {
                    int i = s._headAndTail.Tail - s.FreezeOffset;
                    for (int j = 0; j < i; j = num + 1)
                    {
                        yield return this.GetItemWhenAvailable(s, j);
                        num = j;
                    }
                }
                s = null;
                tailTail -= tail.FreezeOffset;
                for (int i = 0; i < tailTail; i = num + 1)
                {
                    yield return this.GetItemWhenAvailable(tail, i);
                    num = i;
                }
            }
            yield break;
        }
References System.Collections.Concurrent.ConcurrentQueue< T >.Segment.FreezeOffset, System.Collections.Concurrent.ConcurrentQueue< T >.GetItemWhenAvailable(), System.Threading.Volatile.Read(), and System.s.
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo(), System.Collections.Concurrent.ConcurrentQueue< T >.GetEnumerator(), and System.Collections.Concurrent.ConcurrentQueue< T >.ToArray().