Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.ToArray
ToArray()
T[] System.Collections.Concurrent.ConcurrentQueue< T >.ToArray () inline
Implements System.Collections.Concurrent.IProducerConsumerCollection< T >.
Definition at line 121 of file ConcurrentQueue.cs.
        {
            ConcurrentQueue<T>.Segment segment;
            int num;
            ConcurrentQueue<T>.Segment segment2;
            int num2;
            this.SnapForObservation(out segment, out num, out segment2, out num2);
            T[] array = new T[ConcurrentQueue<T>.GetCount(segment, num, segment2, num2)];
            using (IEnumerator<T> enumerator = this.Enumerate(segment, num, segment2, num2))
            {
                int num3 = 0;
                while (enumerator.MoveNext())
                {
                    T t = enumerator.Current;
                    array[num3++] = t;
                }
            }
            return array;
        }
References System.array, System.Collections.IEnumerator.Current, System.Collections.Concurrent.ConcurrentQueue< T >.Enumerate(), System.Collections.Concurrent.ConcurrentQueue< T >.GetCount(), System.Collections.IEnumerator.MoveNext(), and System.Collections.Concurrent.ConcurrentQueue< T >.SnapForObservation().
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.CopyTo().