Terraria Decompiled: Terraria.GameContent.UI.CustomCurrencySystem.TryPurchasing
TryPurchasing()
virtual bool Terraria.GameContent.UI.CustomCurrencySystem.TryPurchasing (long price, List< Item[]> inv, List< Point > slotCoins, List< Point > slotsEmpty, List< Point > slotEmptyBank, List< Point > slotEmptyBank2, List< Point > slotEmptyBank3, List< Point > slotEmptyBank4) inline virtual
Reimplemented in Terraria.GameContent.UI.CustomCurrencySingleCoin.
Definition at line 76 of file CustomCurrencySystem.cs.
        {
            long num = price;
            Dictionary<Point, Item> dictionary = new Dictionary<Point, Item>();
            bool flag = true;
            while (num > 0L)
            {
                long num2 = 1000000L;
                for (int i = 0; i < 4; i++)
                {
                    if (num >= num2)
                    {
                        foreach (Point point in slotCoins)
{
                            if (inv[point.X][point.Y].type == 74 - i)
{
                                long num3 = num / num2;
                                dictionary[point] = inv[point.X][point.Y].Clone();
                                if (num3 < (long)inv[point.X][point.Y].stack)
{
                                    inv[point.X][point.Y].stack -= (int)num3;
                                }
                                else
{
                                    inv[point.X][point.Y].SetDefaults(0, null);
                                    slotsEmpty.Add(point);
                                }
                                num -= num2 * (long)(dictionary[point].stack - inv[point.X][point.Y].stack);
                            }
                        }
                    }
                    num2 /= 100L;
                }
                if (num > 0L)
                {
                    if (slotsEmpty.Count <= 0)
                    {
                        foreach (KeyValuePair<Point, Item> keyValuePair in dictionary)
{
                            inv[keyValuePair.Key.X][keyValuePair.Key.Y] = keyValuePair.Value.Clone();
                        }
                        flag = false;
                        break;
                    }
                    slotsEmpty.Sort(new Comparison<Point>(DelegateMethods.CompareYReverse));
                    Point point2 = new Point(-1, -1);
                    for (int j = 0; j < inv.Count; j++)
                    {
                        num2 = 10000L;
                        for (int k = 0; k < 3; k++)
{
                            if (num >= num2)
{
                                foreach (Point point3 in slotCoins)
{
                                    if (point3.X == j && inv[point3.X][point3.Y].type == 74 - k && inv[point3.X][point3.Y].stack >= 1)
{
                                        List<Point> list = slotsEmpty;
                                        if (j == 1 && slotEmptyBank.Count > 0)
{
                                            list = slotEmptyBank;
                                        }
                                        if (j == 2 && slotEmptyBank2.Count > 0)
{
                                            list = slotEmptyBank2;
                                        }
                                        if (j == 3 && slotEmptyBank3.Count > 0)
{
                                            list = slotEmptyBank3;
                                        }
                                        if (j == 4 && slotEmptyBank4.Count > 0)
{
                                            list = slotEmptyBank4;
                                        }
                                        Item item = inv[point3.X][point3.Y];
                                        int num4 = item.stack - 1;
                                        item.stack = num4;
                                        if (num4 <= 0)
{
                                            inv[point3.X][point3.Y].SetDefaults(0, null);
                                            list.Add(point3);
                                        }
                                        dictionary[list[0]] = inv[list[0].X][list[0].Y].Clone();
                                        inv[list[0].X][list[0].Y].SetDefaults(73 - k, null);
                                        inv[list[0].X][list[0].Y].stack = 100;
                                        point2 = list[0];
                                        list.RemoveAt(0);
                                        break;
                                    }
                                }
                            }
                            if (point2.X != -1 || point2.Y != -1)
{
                                break;
                            }
                            num2 /= 100L;
                        }
                        for (int l = 0; l < 2; l++)
{
                            if (point2.X == -1 && point2.Y == -1)
{
                                foreach (Point point4 in slotCoins)
{
                                    if (point4.X == j && inv[point4.X][point4.Y].type == 73 + l && inv[point4.X][point4.Y].stack >= 1)
{
                                        List<Point> list2 = slotsEmpty;
                                        if (j == 1 && slotEmptyBank.Count > 0)
{
                                            list2 = slotEmptyBank;
                                        }
                                        if (j == 2 && slotEmptyBank2.Count > 0)
{
                                            list2 = slotEmptyBank2;
                                        }
                                        if (j == 3 && slotEmptyBank3.Count > 0)
{
                                            list2 = slotEmptyBank3;
                                        }
                                        if (j == 4 && slotEmptyBank4.Count > 0)
{
                                            list2 = slotEmptyBank4;
                                        }
                                        Item item2 = inv[point4.X][point4.Y];
                                        int num4 = item2.stack - 1;
                                        item2.stack = num4;
                                        if (num4 <= 0)
{
                                            inv[point4.X][point4.Y].SetDefaults(0, null);
                                            list2.Add(point4);
                                        }
                                        dictionary[list2[0]] = inv[list2[0].X][list2[0].Y].Clone();
                                        inv[list2[0].X][list2[0].Y].SetDefaults(72 + l, null);
                                        inv[list2[0].X][list2[0].Y].stack = 100;
                                        point2 = list2[0];
                                        list2.RemoveAt(0);
                                        break;
                                    }
                                }
                            }
                        }
                        if (point2.X != -1 && point2.Y != -1)
{
                            slotCoins.Add(point2);
                            break;
                        }
                    }
                    slotsEmpty.Sort(new Comparison<Point>(DelegateMethods.CompareYReverse));
                    slotEmptyBank.Sort(new Comparison<Point>(DelegateMethods.CompareYReverse));
                    slotEmptyBank2.Sort(new Comparison<Point>(DelegateMethods.CompareYReverse));
                    slotEmptyBank3.Sort(new Comparison<Point>(DelegateMethods.CompareYReverse));
                    slotEmptyBank4.Sort(new Comparison<Point>(DelegateMethods.CompareYReverse));
                }
            }
            return flag;
        }
References System.Collections.Generic.List< T >.Add(), Terraria.DelegateMethods.CompareYReverse(), System.Collections.Generic.List< T >.Count, System.dictionary, int, System.item, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.L, System.list, long, Microsoft.Xna.Framework.Graphics.Point, System.Collections.Generic.List< T >.RemoveAt(), System.Collections.Generic.List< T >.Sort(), System.stack, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.UI.CustomCurrencyManager.BuyItem().