Terraria Decompiled: Terraria.DelegateMethods.Minecart.SparksTerraFart
SparksTerraFart()
static void Terraria.DelegateMethods.Minecart.SparksTerraFart (Vector2 dustPosition) inline static
Definition at line 972 of file DelegateMethods.cs.
            {
                if (Main.rand.Next(2) == 0)
                {
                    DelegateMethods.Minecart.SparksFart(dustPosition);
                    return;
                }
                dustPosition += new Vector2((float)((Main.rand.Next(2) == 0) ? 13 : (-13)), 0f).RotatedBy((double)DelegateMethods.Minecart.rotation, default(Vector2));
                int num = Dust.NewDust(dustPosition, 1, 1, 107, (float)Main.rand.Next(-2, 3), (float)Main.rand.Next(-2, 3), 100, Color.Lerp(new Color(64, 220, 96), Color.White, Main.rand.NextFloat() * 0.3f), 0.8f);
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num].alpha += 25;
                }
                if (Main.rand.Next(2) == 0)
                {
                    Main.dust[num].alpha += 25;
                }
                Main.dust[num].noLightEmittance = true;
                Main.dust[num].noGravity = Main.rand.Next(3) == 0;
                Main.dust[num].velocity *= (float)Main.rand.Next(15, 51) * 0.01f;
                Dust dust = Main.dust[num];
                dust.velocity.X = dust.velocity.X * ((float)Main.rand.Next(25, 101) * 0.01f);
                Dust dust2 = Main.dust[num];
                dust2.velocity.Y = dust2.velocity.Y - (float)Main.rand.Next(15, 31) * 0.1f;
                Dust dust3 = Main.dust[num];
                dust3.position.Y = dust3.position.Y - 4f;
            }
References Terraria.Dust.alpha, Terraria.Main.dust, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Dust.noLightEmittance, Terraria.Main.rand, Terraria.DelegateMethods.Minecart.rotation, Terraria.DelegateMethods.Minecart.SparksFart(), Terraria.Dust.velocity, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Mount.Initialize().