Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream.Read
Read()
int XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream.Read (sbyte[] toRead, int offset, int length) inline package
Definition at line 19 of file PushbackStream.cs.
        {
            int num = 0;
            bool flag = true;
            while (num < length && flag)
            {
                if (this._NumForwardBytesInBuffer > 0)
                {
                    this._NumForwardBytesInBuffer--;
                    toRead[offset + num] = (sbyte)this._CircularByteBuffer[this._NumForwardBytesInBuffer];
                    num++;
                }
                else
                {
                    int num2 = length - num;
                    int num3 = this._Stream.Read(this._TemporaryBuffer, 0, num2);
                    flag = num3 >= num2;
                    for (int i = 0; i < num3; i++)
                    {
                        this._CircularByteBuffer.Push(this._TemporaryBuffer[i]);
                        toRead[offset + num + i] = (sbyte)this._TemporaryBuffer[i];
                    }
                    num += num3;
                }
            }
            return num;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream._CircularByteBuffer, XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream._NumForwardBytesInBuffer, XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream._Stream, XPT.Core.Audio.MP3Sharp.Decoding.PushbackStream._TemporaryBuffer, System.length, System.offset, XPT.Core.Audio.MP3Sharp.Decoding.CircularByteBuffer.Push(), and System.IO.Stream.Read().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadBytes(), and XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadFully().