Terraria Decompiled: System.IO.FileStatus.SetAccessWriteTimes
SetAccessWriteTimes()
void System.IO.FileStatus.SetAccessWriteTimes (string path, long? accessSec, long? accessUSec, long? writeSec, long? writeUSec) inline private
Definition at line 213 of file FileStatus.cs.
        {
            this._fileStatusInitialized = -1;
            this.EnsureStatInitialized(path, false);
            Interop.Sys.TimeValPair timeValPair;
            timeValPair.ASec = accessSec ?? this._fileStatus.ATime;
            timeValPair.AUSec = accessUSec ?? (this._fileStatus.ATimeNsec / 1000L);
            timeValPair.MSec = writeSec ?? this._fileStatus.MTime;
            timeValPair.MUSec = writeUSec ?? (this._fileStatus.MTimeNsec / 1000L);
            Interop.CheckIo(Interop.Sys.UTimes(path, ref timeValPair), path, this.InitiallyDirectory, null);
            this._fileStatusInitialized = -1;
        }
References System.IO.FileStatus._fileStatus, System.IO.FileStatus.EnsureStatInitialized(), System.IO.FileStatus.InitiallyDirectory, and System.L.
Referenced by System.IO.FileStatus.SetLastAccessTime(), and System.IO.FileStatus.SetLastWriteTime().