Terraria Decompiled: System.IO.FileStatus.EnsureStatInitialized
EnsureStatInitialized()
void System.IO.FileStatus.EnsureStatInitialized (ReadOnlySpan< char > path, bool continueOnError = false) inline package
Definition at line 261 of file FileStatus.cs.
        {
            if (this._fileStatusInitialized == -1)
            {
                this.Refresh(path);
            }
            if (this._fileStatusInitialized != 0 && !continueOnError)
            {
                int fileStatusInitialized = this._fileStatusInitialized;
                this._fileStatusInitialized = -1;
                throw Interop.GetExceptionForIoErrno(new Interop.ErrorInfo(fileStatusInitialized), new string(path), false);
            }
        }
References System.IO.FileStatus._fileStatusInitialized, and System.IO.FileStatus.Refresh().
Referenced by System.IO.FileStatus.GetAttributes(), System.IO.FileStatus.GetCreationTime(), System.IO.FileStatus.GetLastAccessTime(), System.IO.FileStatus.GetLastWriteTime(), System.IO.FileStatus.GetLength(), System.IO.FileSystemInfo.Init(), System.IO.FileStatus.IsReadOnly(), System.IO.FileStatus.SetAccessWriteTimes(), and System.IO.FileStatus.SetAttributes().