Terraria Decompiled: System.IO.FileStatus.Refresh
Refresh()
void System.IO.FileStatus.Refresh (ReadOnlySpan< char > path) inline
Definition at line 234 of file FileStatus.cs.
        {
            this._isDirectory = false;
            path = PathInternal.TrimEndingDirectorySeparator(path);
            if (Interop.Sys.LStat(path, out this._fileStatus) >= 0)
            {
                this._exists = true;
                this._isDirectory = (this._fileStatus.Mode & 61440) == 16384;
                Interop.Sys.FileStatus fileStatus;
                if ((this._fileStatus.Mode & 61440) == 40960 && Interop.Sys.Stat(path, out fileStatus) >= 0)
                {
                    this._isDirectory = (fileStatus.Mode & 61440) == 16384;
                }
                this._fileStatusInitialized = 0;
                return;
            }
            Interop.ErrorInfo lastErrorInfo = Interop.Sys.GetLastErrorInfo();
            if (lastErrorInfo.Error == Interop.Error.ENOENT || lastErrorInfo.Error == Interop.Error.ENOTDIR)
            {
                this._fileStatusInitialized = 0;
                this._exists = false;
                return;
            }
            this._fileStatusInitialized = lastErrorInfo.RawErrno;
        }
References System.IO.FileStatus._fileStatus, Interop.ErrorInfo.Error, Interop.ErrorInfo.RawErrno, and System.IO.PathInternal.TrimEndingDirectorySeparator().
Referenced by System.IO.FileStatus.EnsureStatInitialized(), System.IO.FileStatus.GetExists(), and System.IO.FileSystemInfo.Refresh().