Terraria Decompiled: System.Runtime.Serialization.SurrogateSelector.ChainSelector
ChainSelector()
virtual void System.Runtime.Serialization.SurrogateSelector.ChainSelector (ISurrogateSelector selector) inline virtual
Implements System.Runtime.Serialization.ISurrogateSelector.
Definition at line 61 of file SurrogateSelector.cs.
        {
            if (selector == null)
            {
                throw new ArgumentNullException("selector");
            }
            if (selector == this)
            {
                throw new SerializationException(Environment.GetResourceString("Selector is already on the list of checked selectors."));
            }
            if (!SurrogateSelector.HasCycle(selector))
            {
                throw new ArgumentException(Environment.GetResourceString("Selector contained a cycle."), "selector");
            }
            ISurrogateSelector surrogateSelector = selector.GetNextSelector();
            ISurrogateSelector surrogateSelector2 = selector;
            while (surrogateSelector != null && surrogateSelector != this)
            {
                surrogateSelector2 = surrogateSelector;
                surrogateSelector = surrogateSelector.GetNextSelector();
            }
            if (surrogateSelector == this)
            {
                throw new ArgumentException(Environment.GetResourceString("Adding selector will introduce a cycle."), "selector");
            }
            surrogateSelector = selector;
            ISurrogateSelector surrogateSelector3 = selector;
            while (surrogateSelector != null)
            {
                if (surrogateSelector == surrogateSelector2)
                {
                    surrogateSelector = this.GetNextSelector();
                }
                else
                {
                    surrogateSelector = surrogateSelector.GetNextSelector();
                }
                if (surrogateSelector == null)
                {
                    break;
                }
                if (surrogateSelector == surrogateSelector3)
                {
                    throw new ArgumentException(Environment.GetResourceString("Adding selector will introduce a cycle."), "selector");
                }
                if (surrogateSelector == surrogateSelector2)
                {
                    surrogateSelector = this.GetNextSelector();
                }
                else
                {
                    surrogateSelector = surrogateSelector.GetNextSelector();
                }
                if (surrogateSelector3 == surrogateSelector2)
                {
                    surrogateSelector3 = this.GetNextSelector();
                }
                else
                {
                    surrogateSelector3 = surrogateSelector3.GetNextSelector();
                }
                if (surrogateSelector == surrogateSelector3)
                {
                    throw new ArgumentException(Environment.GetResourceString("Adding selector will introduce a cycle."), "selector");
                }
            }
            ISurrogateSelector nextSelector = this.m_nextSelector;
            this.m_nextSelector = selector;
            if (nextSelector != null)
            {
                surrogateSelector2.ChainSelector(nextSelector);
            }
        }
References System.Runtime.Serialization.ISurrogateSelector.ChainSelector(), System.Runtime.Serialization.ISurrogateSelector.GetNextSelector(), System.Runtime.Serialization.SurrogateSelector.GetNextSelector(), System.Environment.GetResourceString(), System.Runtime.Serialization.SurrogateSelector.HasCycle(), and System.Runtime.Serialization.SurrogateSelector.m_nextSelector.