Terraria Decompiled: System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper
CreateInstanceHelper()
static ObjectHandle System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper (AppDomainSetup adSetup) inline static protected
Definition at line 36 of file ApplicationActivator.cs.
        {
            if (adSetup == null)
            {
                throw new ArgumentNullException("adSetup");
            }
            if (adSetup.ActivationArguments == null)
            {
                throw new ArgumentException(string.Format(Locale.GetText("{0} is missing it's {1} property"), "AppDomainSetup", "ActivationArguments"), "adSetup");
            }
            HostSecurityManager hostSecurityManager;
            if (AppDomain.CurrentDomain.DomainManager != null)
            {
                hostSecurityManager = AppDomain.CurrentDomain.DomainManager.HostSecurityManager;
            }
            else
            {
                hostSecurityManager = new HostSecurityManager();
            }
            Evidence evidence = new Evidence();
            evidence.AddHost(adSetup.ActivationArguments);
            TrustManagerContext trustManagerContext = new TrustManagerContext();
            if (!hostSecurityManager.DetermineApplicationTrust(evidence, null, trustManagerContext).IsApplicationTrustedToRun)
            {
                throw new PolicyException(Locale.GetText("Current policy doesn't allow execution of addin."));
            }
            return AppDomain.CreateDomain("friendlyName", null, adSetup).CreateInstance("assemblyName", "typeName", null);
        }
References System.AppDomainSetup.ActivationArguments, System.Security.Policy.Evidence.AddHost(), System.AppDomain.CreateDomain(), System.AppDomain.CreateInstance(), System.AppDomain.CurrentDomain, System.Security.HostSecurityManager.DetermineApplicationTrust(), System.AppDomain.DomainManager, System.Format, Locale.GetText(), System.AppDomainManager.HostSecurityManager, and System.Security.Policy.ApplicationTrust.IsApplicationTrustedToRun.
Referenced by System.Runtime.Hosting.ApplicationActivator.CreateInstance().