Terraria Decompiled: Steamworks.SteamRemoteStorage.EndFileWriteBatch
EndFileWriteBatch()
static bool Steamworks.SteamRemoteStorage.EndFileWriteBatch () inline static
Definition at line 550 of file SteamRemoteStorage.cs.
        {
            InteropHelp.TestIfAvailableClient();
            return NativeMethods.ISteamRemoteStorage_EndFileWriteBatch(CSteamAPIContext.GetSteamRemoteStorage());
        }
References Steamworks.CSteamAPIContext.GetSteamRemoteStorage(), Steamworks.NativeMethods.ISteamRemoteStorage_EndFileWriteBatch(), and Steamworks.InteropHelp.TestIfAvailableClient().