Terraria Decompiled: Microsoft.Xna.Framework.Graphics.Texture.ParseDDS
ParseDDS()
static void Microsoft.Xna.Framework.Graphics.Texture.ParseDDS (BinaryReader reader, out SurfaceFormat format, out int width, out int height, out int levels, out bool isCube) inline static package
Definition at line 227 of file Texture.cs.
        {
            if (reader.ReadUInt32() != 542327876U)
            {
                throw new NotSupportedException("Not a DDS!");
            }
            if (reader.ReadUInt32() != 124U)
            {
                throw new NotSupportedException("Invalid DDS header!");
            }
            uint num = reader.ReadUInt32();
            if ((num & 6U) != 6U)
            {
                throw new NotSupportedException("Invalid DDS flags!");
            }
            if ((num & 524296U) == 524296U)
            {
                throw new NotSupportedException("Invalid DDS flags!");
            }
            height = reader.ReadInt32();
            width = reader.ReadInt32();
            reader.ReadUInt32();
            reader.ReadUInt32();
            levels = reader.ReadInt32();
            reader.ReadBytes(44);
            if (reader.ReadUInt32() != 32U)
            {
                throw new NotSupportedException("Bogus PIXFMTSIZE!");
            }
            uint num2 = reader.ReadUInt32();
            uint num3 = reader.ReadUInt32();
            uint num4 = reader.ReadUInt32();
            uint num5 = reader.ReadUInt32();
            uint num6 = reader.ReadUInt32();
            uint num7 = reader.ReadUInt32();
            uint num8 = reader.ReadUInt32();
            uint num9 = reader.ReadUInt32();
            if ((num9 & 4096U) == 0U)
            {
                throw new NotSupportedException("Not a texture!");
            }
            isCube = false;
            uint num10 = reader.ReadUInt32();
            if (num10 != 0U)
            {
                if ((num10 & 512U) != 512U)
                {
                    throw new NotSupportedException("Invalid caps2!");
                }
                isCube = true;
            }
            reader.ReadUInt32();
            reader.ReadUInt32();
            reader.ReadUInt32();
            if ((num9 & 4194304U) != 4194304U)
            {
                levels = 1;
            }
            if ((num2 & 4U) == 4U)
            {
                if (num3 <= 808540228U)
                {
                    if (num3 == 113U)
                    {
                        format = SurfaceFormat.HalfVector4;
                        return;
                    }
                    if (num3 == 116U)
                    {
                        format = SurfaceFormat.Vector4;
                        return;
                    }
                    if (num3 == 808540228U)
                    {
                        uint num11 = reader.ReadUInt32();
                        if (num11 <= 71U)
{
                            if (num11 == 2U)
{
                                format = SurfaceFormat.Vector4;
                                goto IL_0215;
                            }
                            if (num11 == 10U)
{
                                format = SurfaceFormat.HalfVector4;
                                goto IL_0215;
                            }
                            if (num11 == 71U)
{
                                format = SurfaceFormat.Dxt1;
                                goto IL_0215;
                            }
                        }
                        else if (num11 <= 77U)
{
                            if (num11 == 74U)
{
                                format = SurfaceFormat.Dxt3;
                                goto IL_0215;
                            }
                            if (num11 == 77U)
{
                                format = SurfaceFormat.Dxt5;
                                goto IL_0215;
                            }
                        }
                        else
{
                            if (num11 == 98U)
{
                                format = SurfaceFormat.Bc7EXT;
                                goto IL_0215;
                            }
                            if (num11 == 99U)
{
                                format = SurfaceFormat.Bc7SrgbEXT;
                                goto IL_0215;
                            }
                        }
                        throw new NotSupportedException("Unsupported DDS texture format");
                        IL_0215:
                        uint num12 = reader.ReadUInt32();
                        if (num12 <= 1U)
{
                            throw new NotSupportedException("Unsupported DDS texture format");
                        }
                        reader.ReadUInt32();
                        if (reader.ReadUInt32() > 1U)
{
                            throw new NotSupportedException("Unsupported DDS texture format");
                        }
                        reader.ReadUInt32();
                        return;
                    }
                }
                else
                {
                    if (num3 == 827611204U)
                    {
                        format = SurfaceFormat.Dxt1;
                        return;
                    }
                    if (num3 == 861165636U)
                    {
                        format = SurfaceFormat.Dxt3;
                        return;
                    }
                    if (num3 == 894720068U)
                    {
                        format = SurfaceFormat.Dxt5;
                        return;
                    }
                }
                throw new NotSupportedException("Unsupported DDS texture format");
            }
            if ((num2 & 64U) != 64U)
            {
                throw new NotSupportedException("Unsupported DDS texture format");
            }
            if (num4 != 32U)
            {
                throw new NotSupportedException("Unsupported DDS texture format: Alpha channel required");
            }
            bool flag = num5 == 16711680U && num6 == 65280U && num7 == 255U && num8 == 4278190080U;
            bool flag2 = num5 == 255U && num6 == 65280U && num7 == 16711680U && num8 == 4278190080U;
            if (flag)
            {
                format = SurfaceFormat.ColorBgraEXT;
                return;
            }
            if (flag2)
            {
                format = SurfaceFormat.Color;
                return;
            }
            throw new NotSupportedException("Unsupported DDS texture format: Only RGBA and BGRA are supported");
        }
References System.format, System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadUInt32(), and System.U.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.DDSFromStreamEXT(), and Microsoft.Xna.Framework.Graphics.TextureCube.DDSFromStreamEXT().