Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.GetSteamHTTP
GetSteamHTTP()
static IntPtr Steamworks.CSteamGameServerAPIContext.GetSteamHTTP () inline static package
Definition at line 130 of file CSteamGameServerAPIContext.cs.
        {
            return CSteamGameServerAPIContext.m_pSteamHTTP;
        }
References Steamworks.CSteamGameServerAPIContext.m_pSteamHTTP.
Referenced by Steamworks.SteamGameServerHTTP.CreateCookieContainer(), Steamworks.SteamGameServerHTTP.CreateHTTPRequest(), Steamworks.SteamGameServerHTTP.DeferHTTPRequest(), Steamworks.SteamGameServerHTTP.GetHTTPDownloadProgressPct(), Steamworks.SteamGameServerHTTP.GetHTTPRequestWasTimedOut(), Steamworks.SteamGameServerHTTP.GetHTTPResponseBodyData(), Steamworks.SteamGameServerHTTP.GetHTTPResponseBodySize(), Steamworks.SteamGameServerHTTP.GetHTTPResponseHeaderSize(), Steamworks.SteamGameServerHTTP.GetHTTPResponseHeaderValue(), Steamworks.SteamGameServerHTTP.GetHTTPStreamingResponseBodyData(), Steamworks.SteamGameServerHTTP.PrioritizeHTTPRequest(), Steamworks.SteamGameServerHTTP.ReleaseCookieContainer(), Steamworks.SteamGameServerHTTP.ReleaseHTTPRequest(), Steamworks.SteamGameServerHTTP.SendHTTPRequest(), Steamworks.SteamGameServerHTTP.SendHTTPRequestAndStreamResponse(), Steamworks.SteamGameServerHTTP.SetCookie(), Steamworks.SteamGameServerHTTP.SetHTTPRequestAbsoluteTimeoutMS(), Steamworks.SteamGameServerHTTP.SetHTTPRequestContextValue(), Steamworks.SteamGameServerHTTP.SetHTTPRequestCookieContainer(), Steamworks.SteamGameServerHTTP.SetHTTPRequestGetOrPostParameter(), Steamworks.SteamGameServerHTTP.SetHTTPRequestHeaderValue(), Steamworks.SteamGameServerHTTP.SetHTTPRequestNetworkActivityTimeout(), Steamworks.SteamGameServerHTTP.SetHTTPRequestRawPostBody(), Steamworks.SteamGameServerHTTP.SetHTTPRequestRequiresVerifiedCertificate(), and Steamworks.SteamGameServerHTTP.SetHTTPRequestUserAgentInfo().