Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.GetSteamNetworkingSockets
GetSteamNetworkingSockets()
static IntPtr Steamworks.CSteamGameServerAPIContext.GetSteamNetworkingSockets () inline static package
Definition at line 154 of file CSteamGameServerAPIContext.cs.
        {
            return CSteamGameServerAPIContext.m_pSteamNetworkingSockets;
        }
References Steamworks.CSteamGameServerAPIContext.m_pSteamNetworkingSockets.
Referenced by Steamworks.SteamGameServerNetworkingSockets.AcceptConnection(), Steamworks.SteamGameServerNetworkingSockets.BeginAsyncRequestFakeIP(), Steamworks.SteamGameServerNetworkingSockets.CloseConnection(), Steamworks.SteamGameServerNetworkingSockets.CloseListenSocket(), Steamworks.SteamGameServerNetworkingSockets.ConfigureConnectionLanes(), Steamworks.SteamGameServerNetworkingSockets.ConnectByIPAddress(), Steamworks.SteamGameServerNetworkingSockets.ConnectP2P(), Steamworks.SteamGameServerNetworkingSockets.ConnectP2PCustomSignaling(), Steamworks.SteamGameServerNetworkingSockets.ConnectToHostedDedicatedServer(), Steamworks.SteamGameServerNetworkingSockets.CreateFakeUDPPort(), Steamworks.SteamGameServerNetworkingSockets.CreateHostedDedicatedServerListenSocket(), Steamworks.SteamGameServerNetworkingSockets.CreateListenSocketIP(), Steamworks.SteamGameServerNetworkingSockets.CreateListenSocketP2P(), Steamworks.SteamGameServerNetworkingSockets.CreateListenSocketP2PFakeIP(), Steamworks.SteamGameServerNetworkingSockets.CreatePollGroup(), Steamworks.SteamGameServerNetworkingSockets.CreateSocketPair(), Steamworks.SteamGameServerNetworkingSockets.DestroyPollGroup(), Steamworks.SteamGameServerNetworkingSockets.FindRelayAuthTicketForServer(), Steamworks.SteamGameServerNetworkingSockets.FlushMessagesOnConnection(), Steamworks.SteamGameServerNetworkingSockets.GetAuthenticationStatus(), Steamworks.SteamGameServerNetworkingSockets.GetCertificateRequest(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionInfo(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionName(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionRealTimeStatus(), Steamworks.SteamGameServerNetworkingSockets.GetConnectionUserData(), Steamworks.SteamGameServerNetworkingSockets.GetDetailedConnectionStatus(), Steamworks.SteamGameServerNetworkingSockets.GetFakeIP(), Steamworks.SteamGameServerNetworkingSockets.GetGameCoordinatorServerLogin(), Steamworks.SteamGameServerNetworkingSockets.GetHostedDedicatedServerAddress(), Steamworks.SteamGameServerNetworkingSockets.GetHostedDedicatedServerPOPID(), Steamworks.SteamGameServerNetworkingSockets.GetHostedDedicatedServerPort(), Steamworks.SteamGameServerNetworkingSockets.GetIdentity(), Steamworks.SteamGameServerNetworkingSockets.GetListenSocketAddress(), Steamworks.SteamGameServerNetworkingSockets.GetRemoteFakeIPForConnection(), Steamworks.SteamGameServerNetworkingSockets.InitAuthentication(), Steamworks.SteamGameServerNetworkingSockets.ReceivedP2PCustomSignal(), Steamworks.SteamGameServerNetworkingSockets.ReceivedRelayAuthTicket(), Steamworks.SteamGameServerNetworkingSockets.ReceiveMessagesOnConnection(), Steamworks.SteamGameServerNetworkingSockets.ReceiveMessagesOnPollGroup(), Steamworks.SteamGameServerNetworkingSockets.ResetIdentity(), Steamworks.SteamGameServerNetworkingSockets.RunCallbacks(), Steamworks.SteamGameServerNetworkingSockets.SendMessages(), Steamworks.SteamGameServerNetworkingSockets.SendMessageToConnection(), Steamworks.SteamGameServerNetworkingSockets.SetCertificate(), Steamworks.SteamGameServerNetworkingSockets.SetConnectionName(), Steamworks.SteamGameServerNetworkingSockets.SetConnectionPollGroup(), and Steamworks.SteamGameServerNetworkingSockets.SetConnectionUserData().