Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.GetSteamNetworkingUtils
GetSteamNetworkingUtils()
static IntPtr Steamworks.CSteamGameServerAPIContext.GetSteamNetworkingUtils () inline static package
Definition at line 148 of file CSteamGameServerAPIContext.cs.
        {
            return CSteamGameServerAPIContext.m_pSteamNetworkingUtils;
        }
References Steamworks.CSteamGameServerAPIContext.m_pSteamNetworkingUtils.
Referenced by Steamworks.SteamGameServerNetworkingUtils.AllocateMessage(), Steamworks.SteamGameServerNetworkingUtils.CheckPingDataUpToDate(), Steamworks.SteamGameServerNetworkingUtils.ConvertPingLocationToString(), Steamworks.SteamGameServerNetworkingUtils.EstimatePingTimeBetweenTwoLocations(), Steamworks.SteamGameServerNetworkingUtils.EstimatePingTimeFromLocalHost(), Steamworks.SteamGameServerNetworkingUtils.GetConfigValue(), Steamworks.SteamGameServerNetworkingUtils.GetConfigValueInfo(), Steamworks.SteamGameServerNetworkingUtils.GetDirectPingToPOP(), Steamworks.SteamGameServerNetworkingUtils.GetIPv4FakeIPType(), Steamworks.SteamGameServerNetworkingUtils.GetLocalPingLocation(), Steamworks.SteamGameServerNetworkingUtils.GetLocalTimestamp(), Steamworks.SteamGameServerNetworkingUtils.GetPingToDataCenter(), Steamworks.SteamGameServerNetworkingUtils.GetPOPCount(), Steamworks.SteamGameServerNetworkingUtils.GetPOPList(), Steamworks.SteamGameServerNetworkingUtils.GetRealIdentityForFakeIP(), Steamworks.SteamGameServerNetworkingUtils.GetRelayNetworkStatus(), Steamworks.SteamGameServerNetworkingUtils.InitRelayNetworkAccess(), Steamworks.SteamGameServerNetworkingUtils.IsFakeIPv4(), Steamworks.SteamGameServerNetworkingUtils.IterateGenericEditableConfigValues(), Steamworks.SteamGameServerNetworkingUtils.ParsePingLocationString(), Steamworks.SteamGameServerNetworkingUtils.SetConfigValue(), Steamworks.SteamGameServerNetworkingUtils.SetDebugOutputFunction(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIdentity_ParseString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIdentity_ToString(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_GetFakeIPType(), Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ParseString(), and Steamworks.SteamGameServerNetworkingUtils.SteamNetworkingIPAddr_ToString().