Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.Init
Init()
static bool Steamworks.CSteamGameServerAPIContext.Init () inline static package
Definition at line 25 of file CSteamGameServerAPIContext.cs.
        {
            HSteamUser hsteamUser = GameServer.GetHSteamUser();
            HSteamPipe hsteamPipe = GameServer.GetHSteamPipe();
            if (hsteamPipe == (HSteamPipe)0)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle("SteamClient021"))
            {
                CSteamGameServerAPIContext.m_pSteamClient = NativeMethods.SteamInternal_CreateInterface(utf8StringHandle);
            }
            if (CSteamGameServerAPIContext.m_pSteamClient == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamGameServer = SteamGameServerClient.GetISteamGameServer(hsteamUser, hsteamPipe, "SteamGameServer015");
            if (CSteamGameServerAPIContext.m_pSteamGameServer == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamUtils = SteamGameServerClient.GetISteamUtils(hsteamPipe, "SteamUtils010");
            if (CSteamGameServerAPIContext.m_pSteamUtils == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamNetworking = SteamGameServerClient.GetISteamNetworking(hsteamUser, hsteamPipe, "SteamNetworking006");
            if (CSteamGameServerAPIContext.m_pSteamNetworking == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamGameServerStats = SteamGameServerClient.GetISteamGameServerStats(hsteamUser, hsteamPipe, "SteamGameServerStats001");
            if (CSteamGameServerAPIContext.m_pSteamGameServerStats == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamHTTP = SteamGameServerClient.GetISteamHTTP(hsteamUser, hsteamPipe, "STEAMHTTP_INTERFACE_VERSION003");
            if (CSteamGameServerAPIContext.m_pSteamHTTP == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamInventory = SteamGameServerClient.GetISteamInventory(hsteamUser, hsteamPipe, "STEAMINVENTORY_INTERFACE_V003");
            if (CSteamGameServerAPIContext.m_pSteamInventory == IntPtr.Zero)
            {
                return false;
            }
            CSteamGameServerAPIContext.m_pSteamUGC = SteamGameServerClient.GetISteamUGC(hsteamUser, hsteamPipe, "STEAMUGC_INTERFACE_VERSION020");
            if (CSteamGameServerAPIContext.m_pSteamUGC == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle2 = new InteropHelp.UTF8StringHandle("SteamNetworkingUtils004"))
            {
                CSteamGameServerAPIContext.m_pSteamNetworkingUtils = ((NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle2) != IntPtr.Zero) ? NativeMethods.SteamInternal_FindOrCreateUserInterface(hsteamUser, utf8StringHandle2) : NativeMethods.SteamInternal_FindOrCreateGameServerInterface(hsteamUser, utf8StringHandle2));
            }
            if (CSteamGameServerAPIContext.m_pSteamNetworkingUtils == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle3 = new InteropHelp.UTF8StringHandle("SteamNetworkingSockets012"))
            {
                CSteamGameServerAPIContext.m_pSteamNetworkingSockets = NativeMethods.SteamInternal_FindOrCreateGameServerInterface(hsteamUser, utf8StringHandle3);
            }
            if (CSteamGameServerAPIContext.m_pSteamNetworkingSockets == IntPtr.Zero)
            {
                return false;
            }
            using (InteropHelp.UTF8StringHandle utf8StringHandle4 = new InteropHelp.UTF8StringHandle("SteamNetworkingMessages002"))
            {
                CSteamGameServerAPIContext.m_pSteamNetworkingMessages = NativeMethods.SteamInternal_FindOrCreateGameServerInterface(hsteamUser, utf8StringHandle4);
            }
            return !(CSteamGameServerAPIContext.m_pSteamNetworkingMessages == IntPtr.Zero);
        }
References Steamworks.GameServer.GetHSteamPipe(), Steamworks.GameServer.GetHSteamUser(), Steamworks.SteamGameServerClient.GetISteamGameServer(), Steamworks.SteamGameServerClient.GetISteamGameServerStats(), Steamworks.SteamGameServerClient.GetISteamHTTP(), Steamworks.SteamGameServerClient.GetISteamInventory(), Steamworks.SteamGameServerClient.GetISteamNetworking(), Steamworks.SteamGameServerClient.GetISteamUGC(), Steamworks.SteamGameServerClient.GetISteamUtils(), Steamworks.CSteamGameServerAPIContext.m_pSteamClient, Steamworks.CSteamGameServerAPIContext.m_pSteamGameServer, Steamworks.CSteamGameServerAPIContext.m_pSteamGameServerStats, Steamworks.CSteamGameServerAPIContext.m_pSteamHTTP, Steamworks.CSteamGameServerAPIContext.m_pSteamInventory, Steamworks.CSteamGameServerAPIContext.m_pSteamNetworking, Steamworks.CSteamGameServerAPIContext.m_pSteamNetworkingSockets, Steamworks.CSteamGameServerAPIContext.m_pSteamNetworkingUtils, Steamworks.CSteamGameServerAPIContext.m_pSteamUGC, Steamworks.CSteamGameServerAPIContext.m_pSteamUtils, Steamworks.NativeMethods.SteamInternal_CreateInterface(), Steamworks.NativeMethods.SteamInternal_FindOrCreateGameServerInterface(), Steamworks.NativeMethods.SteamInternal_FindOrCreateUserInterface(), and System.IntPtr.Zero.
Referenced by Steamworks.GameServer.InitEx(), and Steamworks.InteropHelp.TestIfAvailableGameServer().