Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.GetSteamClient
GetSteamClient()
static IntPtr Steamworks.CSteamGameServerAPIContext.GetSteamClient () inline static package
Definition at line 100 of file CSteamGameServerAPIContext.cs.
        {
            return CSteamGameServerAPIContext.m_pSteamClient;
        }
References Steamworks.CSteamGameServerAPIContext.m_pSteamClient.
Referenced by Steamworks.SteamGameServerClient.BReleaseSteamPipe(), Steamworks.SteamGameServerClient.BShutdownIfAllPipesClosed(), Steamworks.SteamGameServerClient.ConnectToGlobalUser(), Steamworks.SteamGameServerClient.CreateLocalUser(), Steamworks.SteamGameServerClient.CreateSteamPipe(), Steamworks.SteamGameServerClient.GetIPCCallCount(), Steamworks.SteamGameServerClient.GetISteamApps(), Steamworks.SteamGameServerClient.GetISteamController(), Steamworks.SteamGameServerClient.GetISteamFriends(), Steamworks.SteamGameServerClient.GetISteamGameSearch(), Steamworks.SteamGameServerClient.GetISteamGameServer(), Steamworks.SteamGameServerClient.GetISteamGameServerStats(), Steamworks.SteamGameServerClient.GetISteamGenericInterface(), Steamworks.SteamGameServerClient.GetISteamHTMLSurface(), Steamworks.SteamGameServerClient.GetISteamHTTP(), Steamworks.SteamGameServerClient.GetISteamInput(), Steamworks.SteamGameServerClient.GetISteamInventory(), Steamworks.SteamGameServerClient.GetISteamMatchmaking(), Steamworks.SteamGameServerClient.GetISteamMatchmakingServers(), Steamworks.SteamGameServerClient.GetISteamMusic(), Steamworks.SteamGameServerClient.GetISteamMusicRemote(), Steamworks.SteamGameServerClient.GetISteamNetworking(), Steamworks.SteamGameServerClient.GetISteamParentalSettings(), Steamworks.SteamGameServerClient.GetISteamParties(), Steamworks.SteamGameServerClient.GetISteamRemotePlay(), Steamworks.SteamGameServerClient.GetISteamRemoteStorage(), Steamworks.SteamGameServerClient.GetISteamScreenshots(), Steamworks.SteamGameServerClient.GetISteamUGC(), Steamworks.SteamGameServerClient.GetISteamUser(), Steamworks.SteamGameServerClient.GetISteamUserStats(), Steamworks.SteamGameServerClient.GetISteamUtils(), Steamworks.SteamGameServerClient.GetISteamVideo(), Steamworks.SteamGameServerClient.ReleaseUser(), Steamworks.SteamGameServerClient.SetLocalIPBinding(), Steamworks.SteamGameServerClient.SetWarningMessageHook(), and Steamworks.InteropHelp.TestIfAvailableGameServer().