Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.GetSteamGameServer
GetSteamGameServer()
static IntPtr Steamworks.CSteamGameServerAPIContext.GetSteamGameServer () inline static package
Definition at line 106 of file CSteamGameServerAPIContext.cs.
        {
            return CSteamGameServerAPIContext.m_pSteamGameServer;
        }
References Steamworks.CSteamGameServerAPIContext.m_pSteamGameServer.
Referenced by Steamworks.SteamGameServer.AssociateWithClan(), Steamworks.SteamGameServer.BeginAuthSession(), Steamworks.SteamGameServer.BLoggedOn(), Steamworks.SteamGameServer.BSecure(), Steamworks.SteamGameServer.BUpdateUserData(), Steamworks.SteamGameServer.CancelAuthTicket(), Steamworks.SteamGameServer.ClearAllKeyValues(), Steamworks.SteamGameServer.ComputeNewPlayerCompatibility(), Steamworks.SteamGameServer.CreateUnauthenticatedUserConnection(), Steamworks.SteamGameServer.EndAuthSession(), Steamworks.SteamGameServer.GetAuthSessionTicket(), Steamworks.SteamGameServer.GetGameplayStats(), Steamworks.SteamGameServer.GetNextOutgoingPacket(), Steamworks.SteamGameServer.GetPublicIP(), Steamworks.SteamGameServer.GetServerReputation(), Steamworks.SteamGameServer.GetSteamID(), Steamworks.SteamGameServer.HandleIncomingPacket(), Steamworks.SteamGameServer.LogOff(), Steamworks.SteamGameServer.LogOn(), Steamworks.SteamGameServer.LogOnAnonymous(), Steamworks.SteamGameServer.RequestUserGroupStatus(), Steamworks.SteamGameServer.SendUserConnectAndAuthenticate_DEPRECATED(), Steamworks.SteamGameServer.SendUserDisconnect_DEPRECATED(), Steamworks.SteamGameServer.SetAdvertiseServerActive(), Steamworks.SteamGameServer.SetBotPlayerCount(), Steamworks.SteamGameServer.SetDedicatedServer(), Steamworks.SteamGameServer.SetGameData(), Steamworks.SteamGameServer.SetGameDescription(), Steamworks.SteamGameServer.SetGameTags(), Steamworks.SteamGameServer.SetKeyValue(), Steamworks.SteamGameServer.SetMapName(), Steamworks.SteamGameServer.SetMaxPlayerCount(), Steamworks.SteamGameServer.SetModDir(), Steamworks.SteamGameServer.SetPasswordProtected(), Steamworks.SteamGameServer.SetProduct(), Steamworks.SteamGameServer.SetRegion(), Steamworks.SteamGameServer.SetServerName(), Steamworks.SteamGameServer.SetSpectatorPort(), Steamworks.SteamGameServer.SetSpectatorServerName(), Steamworks.SteamGameServer.UserHasLicenseForApp(), and Steamworks.SteamGameServer.WasRestartRequested().