Terraria Decompiled: Steamworks.CSteamGameServerAPIContext.GetSteamNetworking
GetSteamNetworking()
static IntPtr Steamworks.CSteamGameServerAPIContext.GetSteamNetworking () inline static package
Definition at line 118 of file CSteamGameServerAPIContext.cs.
        {
            return CSteamGameServerAPIContext.m_pSteamNetworking;
        }
References Steamworks.CSteamGameServerAPIContext.m_pSteamNetworking.
Referenced by Steamworks.SteamGameServerNetworking.AcceptP2PSessionWithUser(), Steamworks.SteamGameServerNetworking.AllowP2PPacketRelay(), Steamworks.SteamGameServerNetworking.CloseP2PChannelWithUser(), Steamworks.SteamGameServerNetworking.CloseP2PSessionWithUser(), Steamworks.SteamGameServerNetworking.CreateConnectionSocket(), Steamworks.SteamGameServerNetworking.CreateListenSocket(), Steamworks.SteamGameServerNetworking.CreateP2PConnectionSocket(), Steamworks.SteamGameServerNetworking.DestroyListenSocket(), Steamworks.SteamGameServerNetworking.DestroySocket(), Steamworks.SteamGameServerNetworking.GetListenSocketInfo(), Steamworks.SteamGameServerNetworking.GetMaxPacketSize(), Steamworks.SteamGameServerNetworking.GetP2PSessionState(), Steamworks.SteamGameServerNetworking.GetSocketConnectionType(), Steamworks.SteamGameServerNetworking.GetSocketInfo(), Steamworks.SteamGameServerNetworking.IsDataAvailable(), Steamworks.SteamGameServerNetworking.IsDataAvailableOnSocket(), Steamworks.SteamGameServerNetworking.IsP2PPacketAvailable(), Steamworks.SteamGameServerNetworking.ReadP2PPacket(), Steamworks.SteamGameServerNetworking.RetrieveData(), Steamworks.SteamGameServerNetworking.RetrieveDataFromSocket(), Steamworks.SteamGameServerNetworking.SendDataOnSocket(), and Steamworks.SteamGameServerNetworking.SendP2PPacket().