Terraria Decompiled: Terraria.GameContent.Skies.NebulaSky.Draw
Draw()
override void Terraria.GameContent.Skies.NebulaSky.Draw (SpriteBatch spriteBatch, float minDepth, float maxDepth) inline
Definition at line 44 of file NebulaSky.cs.
        {
            if (maxDepth >= 3.4028235E+38f && minDepth < 3.4028235E+38f)
            {
                spriteBatch.Draw(TextureAssets.BlackTile.Value, new Rectangle(0, 0, Main.screenWidth, Main.screenHeight), Color.Black * this._fadeOpacity);
                spriteBatch.Draw(this._bgTexture.Value, new Rectangle(0, Math.Max(0, (int)((Main.worldSurface * 16.0 - (double)Main.screenPosition.Y - 2400.0) * 0.10000000149011612)), Main.screenWidth, Main.screenHeight), Color.White * Math.Min(1f, (Main.screenPosition.Y - 800f) / 1000f * this._fadeOpacity));
                Vector2 vector = new Vector2((float)(Main.screenWidth >> 1), (float)(Main.screenHeight >> 1));
                Vector2 vector2 = 0.01f * (new Vector2((float)Main.maxTilesX * 8f, (float)Main.worldSurface / 2f) - Main.screenPosition);
                spriteBatch.Draw(this._planetTexture.Value, vector + new Vector2(-200f, -200f) + vector2, null, Color.White * 0.9f * this._fadeOpacity, 0f, new Vector2((float)(this._planetTexture.Width() >> 1), (float)(this._planetTexture.Height() >> 1)), 1f, SpriteEffects.None, 0f);
            }
            int num = -1;
            int num2 = 0;
            for (int i = 0; i < this._pillars.Length; i++)
            {
                float depth = this._pillars[i].Depth;
                if (num == -1 && depth < maxDepth)
                {
                    num = i;
                }
                if (depth <= minDepth)
                {
                    break;
                }
                num2 = i;
            }
            if (num == -1)
            {
                return;
            }
            Vector2 vector3 = Main.screenPosition + new Vector2((float)(Main.screenWidth >> 1), (float)(Main.screenHeight >> 1));
            Rectangle rectangle = new Rectangle(-1000, -1000, Main.screenWidth + 1000, Main.screenHeight + 1000);
            float num3 = Math.Min(1f, (Main.screenPosition.Y - 1000f) / 1000f);
            for (int j = num; j < num2; j++)
            {
                Vector2 vector4 = new Vector2(1f / this._pillars[j].Depth, 0.9f / this._pillars[j].Depth);
                Vector2 vector5 = this._pillars[j].Position;
                vector5 = (vector5 - vector3) * vector4 + vector3 - Main.screenPosition;
                if (rectangle.Contains((int)vector5.X, (int)vector5.Y))
                {
                    float num4 = vector4.X * 450f;
                    spriteBatch.Draw(this._beamTexture.Value, vector5, null, Color.White * 0.2f * num3 * this._fadeOpacity, 0f, Vector2.Zero, new Vector2(num4 / 70f, num4 / 45f), SpriteEffects.None, 0f);
                    int num5 = 0;
                    for (float num6 = 0f; num6 <= 1f; num6 += 0.03f)
                    {
                        float num7 = 1f - (num6 + Main.GlobalTimeWrappedHourly * 0.02f + (float)Math.Sin((double)j)) % 1f;
                        spriteBatch.Draw(this._rockTextures[num5].Value, vector5 + new Vector2((float)Math.Sin((double)(num6 * 1582f)) * (num4 * 0.5f) + num4 * 0.5f, num7 * 2000f), null, Color.White * num7 * num3 * this._fadeOpacity, num7 * 20f, new Vector2((float)(this._rockTextures[num5].Width() >> 1), (float)(this._rockTextures[num5].Height() >> 1)), 0.9f, SpriteEffects.None, 0f);
                        num5 = (num5 + 1) % this._rockTextures.Length;
                    }
                }
            }
        }
References Terraria.GameContent.Skies.NebulaSky._beamTexture, Terraria.GameContent.Skies.NebulaSky._bgTexture, Terraria.GameContent.Skies.NebulaSky._fadeOpacity, Terraria.GameContent.Skies.NebulaSky._pillars, Terraria.GameContent.Skies.NebulaSky._planetTexture, Terraria.GameContent.Skies.NebulaSky._rockTextures, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BlackTile, Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.Depth, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), System.E, System.Math.Max(), Terraria.Main.maxTilesX, System.Math.Min(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, System.Math.Sin(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.