Terraria Decompiled: System.Security.Policy.PolicyLevel.CreateDefaultNamedPermissionSets
CreateDefaultNamedPermissionSets()
void System.Security.Policy.PolicyLevel.CreateDefaultNamedPermissionSets () inline package
Definition at line 615 of file PolicyLevel.cs.
        {
            this.named_permission_sets.Clear();
            try
            {
                SecurityManager.ResolvingPolicyLevel = this;
                this.named_permission_sets.Add(DefaultPolicies.LocalIntranet);
                this.named_permission_sets.Add(DefaultPolicies.Internet);
                this.named_permission_sets.Add(DefaultPolicies.SkipVerification);
                this.named_permission_sets.Add(DefaultPolicies.Execution);
                this.named_permission_sets.Add(DefaultPolicies.Nothing);
                this.named_permission_sets.Add(DefaultPolicies.Everything);
                this.named_permission_sets.Add(DefaultPolicies.FullTrust);
            }
            finally
            {
                SecurityManager.ResolvingPolicyLevel = null;
            }
        }
References System.Collections.ArrayList.Add(), System.Collections.ArrayList.Clear(), System.Security.Policy.DefaultPolicies.Everything, System.Security.Policy.DefaultPolicies.Execution, System.Security.Policy.DefaultPolicies.FullTrust, System.Security.Policy.DefaultPolicies.Internet, System.Security.Policy.DefaultPolicies.LocalIntranet, System.Security.Policy.PolicyLevel.named_permission_sets, System.Security.Policy.DefaultPolicies.Nothing, and System.Security.Policy.DefaultPolicies.SkipVerification.
Referenced by System.Security.Policy.PolicyLevel.LoadFromFile(), and System.Security.Policy.PolicyLevel.Reset().