Terraria Decompiled: System.Security.Policy.PolicyLevel.AddFullTrustAssembly
AddFullTrustAssembly() [2/2]
void System.Security.Policy.PolicyLevel.AddFullTrustAssembly (StrongNameMembershipCondition snMC) inline
Definition at line 189 of file PolicyLevel.cs.
        {
            if (snMC == null)
            {
                throw new ArgumentNullException("snMC");
            }
            using (IEnumerator enumerator = this.full_trust_assemblies.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (((StrongNameMembershipCondition)enumerator.Current).Equals(snMC))
                    {
                        throw new ArgumentException(Locale.GetText("sn already has full trust."));
                    }
                }
            }
            this.full_trust_assemblies.Add(snMC);
        }
References System.Collections.ArrayList.Add(), System.Collections.IEnumerator.Current, System.Security.Policy.PolicyLevel.full_trust_assemblies, System.Collections.ArrayList.GetEnumerator(), Locale.GetText(), and System.Collections.IEnumerator.MoveNext().