Terraria Decompiled: Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor
TryCloseDoor()
DoorOpeningHelper.DoorCloseAttemptResult Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor (DoorOpeningHelper::DoorOpenCloseTogglingInfo info, DoorOpeningHelper::PlayerInfoForClosingDoors playerInfo) inline
Implements Terraria.GameContent.DoorOpeningHelper.DoorAutoHandler.
Definition at line 334 of file DoorOpeningHelper.cs.
            {
                Point tileCoordsForToggling = info.tileCoordsForToggling;
                Tile tile = Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y];
                if (!tile.active() || tile.type != 11)
                {
                    return DoorOpeningHelper.DoorCloseAttemptResult.DoorIsInvalidated;
                }
                int num = (int)(tile.frameX % 72 / 18);
                Rectangle rectangle = new Rectangle(tileCoordsForToggling.X * 16, tileCoordsForToggling.Y * 16, 16, 48);
                if (num != 1)
                {
                    if (num == 2)
                    {
                        rectangle.X += 16;
                    }
                }
                else
                {
                    rectangle.X -= 16;
                }
                rectangle.Inflate(1, 0);
                Rectangle rectangle2 = Rectangle.Intersect(rectangle, playerInfo.hitboxToNotCloseDoor);
                if (rectangle2.Width > 0 || rectangle2.Height > 0)
                {
                    return DoorOpeningHelper.DoorCloseAttemptResult.StillInDoorArea;
                }
                if (WorldGen.CloseDoor(tileCoordsForToggling.X, tileCoordsForToggling.Y, false))
                {
                    NetMessage.SendData(13, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                    NetMessage.SendData(19, -1, -1, null, 1, (float)tileCoordsForToggling.X, (float)tileCoordsForToggling.Y, 1f, 0, 0, 0);
                    return DoorOpeningHelper.DoorCloseAttemptResult.ClosedDoor;
                }
                return DoorOpeningHelper.DoorCloseAttemptResult.FailedToCloseDoor;
            }
References Terraria.Tile.active(), Terraria.WorldGen.CloseDoor(), Terraria.Tile.frameX, Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Inflate(), System.info, int, Microsoft.Xna.Framework.Rectangle.Intersect(), Terraria.Main.myPlayer, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.