Terraria Decompiled: System.Security.Policy.PolicyLevel.FromString
FromString()
SecurityElement System.Security.Policy.PolicyLevel.FromString (string xml) inline private
Definition at line 77 of file PolicyLevel.cs.
        {
            SecurityParser securityParser = new SecurityParser();
            securityParser.LoadXml(xml);
            SecurityElement securityElement = securityParser.ToXml();
            if (securityElement.Tag != "configuration")
            {
                throw new ArgumentException(Locale.GetText("missing <configuration> root element"));
            }
            SecurityElement securityElement2 = (SecurityElement)securityElement.Children[0];
            if (securityElement2.Tag != "mscorlib")
            {
                throw new ArgumentException(Locale.GetText("missing <mscorlib> tag"));
            }
            SecurityElement securityElement3 = (SecurityElement)securityElement2.Children[0];
            if (securityElement3.Tag != "security")
            {
                throw new ArgumentException(Locale.GetText("missing <security> tag"));
            }
            SecurityElement securityElement4 = (SecurityElement)securityElement3.Children[0];
            if (securityElement4.Tag != "policy")
            {
                throw new ArgumentException(Locale.GetText("missing <policy> tag"));
            }
            return (SecurityElement)securityElement4.Children[0];
        }
References System.Security.SecurityElement.Children, Locale.GetText(), Mono.Xml.SecurityParser.LoadXml(), System.Security.SecurityElement.Tag, Mono.Xml.SecurityParser.ToXml(), and System.Security.Policy.PolicyLevel.xml.
Referenced by System.Security.Policy.PolicyLevel.LoadFromFile(), and System.Security.Policy.PolicyLevel.LoadFromString().