Terraria Decompiled: Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor
TryOpenDoor()
bool Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor (DoorOpeningHelper::DoorOpenCloseTogglingInfo doorInfo, DoorOpeningHelper::PlayerInfoForOpeningDoors playerInfo) inline
Implements Terraria.GameContent.DoorOpeningHelper.DoorAutoHandler.
Definition at line 292 of file DoorOpeningHelper.cs.
            {
                Point tileCoordsForToggling = doorInfo.tileCoordsForToggling;
                int intendedOpeningDirection = playerInfo.intendedOpeningDirection;
                Rectangle rectangle = new Rectangle(doorInfo.tileCoordsForToggling.X * 16, doorInfo.tileCoordsForToggling.Y * 16, 16, 48);
                int playerGravityDirection = playerInfo.playerGravityDirection;
                if (playerGravityDirection != -1)
                {
                    if (playerGravityDirection == 1)
                    {
                        rectangle.Height += 16;
                    }
                }
                else
                {
                    rectangle.Y -= 16;
                    rectangle.Height += 16;
                }
                if (!rectangle.Intersects(playerInfo.hitboxToOpenDoor))
                {
                    return false;
                }
                if (playerInfo.hitboxToOpenDoor.Top < rectangle.Top || playerInfo.hitboxToOpenDoor.Bottom > rectangle.Bottom)
                {
                    return false;
                }
                WorldGen.OpenDoor(tileCoordsForToggling.X, tileCoordsForToggling.Y, intendedOpeningDirection);
                if (Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y].type != 10)
                {
                    NetMessage.SendData(19, -1, -1, null, 0, (float)tileCoordsForToggling.X, (float)tileCoordsForToggling.Y, (float)intendedOpeningDirection, 0, 0, 0);
                    return true;
                }
                WorldGen.OpenDoor(tileCoordsForToggling.X, tileCoordsForToggling.Y, -intendedOpeningDirection);
                if (Main.tile[tileCoordsForToggling.X, tileCoordsForToggling.Y].type != 10)
                {
                    NetMessage.SendData(19, -1, -1, null, 0, (float)tileCoordsForToggling.X, (float)tileCoordsForToggling.Y, (float)(-(float)intendedOpeningDirection), 0, 0, 0);
                    return true;
                }
                return false;
            }
References Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.OpenDoor(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Tile.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.