Terraria Decompiled: System.Security.Policy.PolicyLevel.ChangeNamedPermissionSet
ChangeNamedPermissionSet()
NamedPermissionSet System.Security.Policy.PolicyLevel.ChangeNamedPermissionSet (string name, PermissionSet pSet) inline
Definition at line 227 of file PolicyLevel.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (pSet == null)
            {
                throw new ArgumentNullException("pSet");
            }
            if (DefaultPolicies.ReservedNames.IsReserved(name))
            {
                throw new ArgumentException(Locale.GetText("Reserved name"));
            }
            foreach (object obj in this.named_permission_sets)
            {
                NamedPermissionSet namedPermissionSet = (NamedPermissionSet)obj;
                if (name == namedPermissionSet.Name)
                {
                    this.named_permission_sets.Remove(namedPermissionSet);
                    this.AddNamedPermissionSet(new NamedPermissionSet(name, pSet));
                    return namedPermissionSet;
                }
            }
            throw new ArgumentException(Locale.GetText("PermissionSet not found"));
        }
References System.Security.Policy.PolicyLevel.AddNamedPermissionSet(), Locale.GetText(), System.Security.Policy.DefaultPolicies.ReservedNames.IsReserved(), System.name, System.Security.NamedPermissionSet.Name, System.Security.Policy.PolicyLevel.named_permission_sets, and System.obj.