Terraria Decompiled: System.Security.Policy.PolicyLevel.Resolve
Resolve()
PolicyStatement System.Security.Policy.PolicyLevel.Resolve (Evidence evidence) inline
Definition at line 452 of file PolicyLevel.cs.
        {
            if (evidence == null)
            {
                throw new ArgumentNullException("evidence");
            }
            PolicyStatement policyStatement = this.root_code_group.Resolve(evidence);
            if (policyStatement == null)
            {
                return PolicyStatement.Empty();
            }
            return policyStatement;
        }
References System.Security.Policy.PolicyStatement.Empty(), System.Security.Policy.CodeGroup.Resolve(), and System.Security.Policy.PolicyLevel.root_code_group.
Referenced by System.Security.SecurityManager.ResolvePolicyLevel(), and System.AppDomain.SetAppDomainPolicy().