Terraria Decompiled: System.Security.Policy.PolicyLevel.Save
Save()
void System.Security.Policy.PolicyLevel.Save () inline package
Definition at line 532 of file PolicyLevel.cs.
        {
            if (this._type == PolicyLevelType.AppDomain)
            {
                throw new PolicyException(Locale.GetText("Can't save AppDomain PolicyLevel"));
            }
            if (this._location != null)
            {
                try
                {
                    if (File.Exists(this._location))
                    {
                        File.Copy(this._location, this._location + ".backup", true);
                    }
                }
                catch (Exception)
                {
                }
                finally
                {
                    using (StreamWriter streamWriter = new StreamWriter(this._location))
                    {
                        streamWriter.Write(this.ToXml().ToString());
                        streamWriter.Close();
                    }
                }
            }
        }
References System.Security.Policy.PolicyLevel._location, System.Security.Policy.PolicyLevel._type, System.IO.StreamWriter.Close(), System.IO.File.Copy(), System.IO.File.Exists(), Locale.GetText(), System.Security.SecurityElement.ToString(), System.Security.Policy.PolicyLevel.ToXml(), and System.IO.StreamWriter.Write().
Referenced by System.Security.Policy.PolicyLevel.LoadFromFile(), and System.Security.SecurityManager.SavePolicyLevel().