Terraria Decompiled: System.Security.Policy.PolicyLevel.CreateDefaultFullTrustAssemblies
CreateDefaultFullTrustAssemblies()
void System.Security.Policy.PolicyLevel.CreateDefaultFullTrustAssemblies () inline package
Definition at line 602 of file PolicyLevel.cs.
        {
            this.full_trust_assemblies.Clear();
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("mscorlib", DefaultPolicies.Key.Ecma));
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("System", DefaultPolicies.Key.Ecma));
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("System.Data", DefaultPolicies.Key.Ecma));
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("System.DirectoryServices", DefaultPolicies.Key.MsFinal));
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("System.Drawing", DefaultPolicies.Key.MsFinal));
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("System.Messaging", DefaultPolicies.Key.MsFinal));
            this.full_trust_assemblies.Add(DefaultPolicies.FullTrustMembership("System.ServiceProcess", DefaultPolicies.Key.MsFinal));
        }
References System.Collections.ArrayList.Add(), System.Collections.ArrayList.Clear(), System.Security.Policy.PolicyLevel.full_trust_assemblies, and System.Security.Policy.DefaultPolicies.FullTrustMembership().
Referenced by System.Security.Policy.PolicyLevel.LoadFromFile(), and System.Security.Policy.PolicyLevel.Reset().