Terraria Decompiled: System.Security.Policy.PolicyLevel.FromXml
FromXml()
void System.Security.Policy.PolicyLevel.FromXml (SecurityElement e) inline
Definition at line 266 of file PolicyLevel.cs.
        {
            if (e == null)
            {
                throw new ArgumentNullException("e");
            }
            SecurityElement securityElement = e.SearchForChildByTag("SecurityClasses");
            if (securityElement != null && securityElement.Children != null && securityElement.Children.Count > 0)
            {
                this.fullNames = new Hashtable(securityElement.Children.Count);
                foreach (object obj in securityElement.Children)
                {
                    SecurityElement securityElement2 = (SecurityElement)obj;
                    this.fullNames.Add(securityElement2.Attributes["Name"], securityElement2.Attributes["Description"]);
                }
            }
            SecurityElement securityElement3 = e.SearchForChildByTag("FullTrustAssemblies");
            if (securityElement3 != null && securityElement3.Children != null && securityElement3.Children.Count > 0)
            {
                this.full_trust_assemblies.Clear();
                foreach (object obj2 in securityElement3.Children)
                {
                    SecurityElement securityElement4 = (SecurityElement)obj2;
                    if (securityElement4.Tag != "IMembershipCondition")
                    {
                        throw new ArgumentException(Locale.GetText("Invalid XML"));
                    }
                    if (securityElement4.Attribute("class").IndexOf("StrongNameMembershipCondition") < 0)
                    {
                        throw new ArgumentException(Locale.GetText("Invalid XML - must be StrongNameMembershipCondition"));
                    }
                    this.full_trust_assemblies.Add(new StrongNameMembershipCondition(securityElement4));
                }
            }
            SecurityElement securityElement5 = e.SearchForChildByTag("CodeGroup");
            if (securityElement5 != null && securityElement5.Children != null && securityElement5.Children.Count > 0)
            {
                this.root_code_group = CodeGroup.CreateFromXml(securityElement5, this);
                SecurityElement securityElement6 = e.SearchForChildByTag("NamedPermissionSets");
                if (securityElement6 != null && securityElement6.Children != null && securityElement6.Children.Count > 0)
                {
                    this.named_permission_sets.Clear();
                    foreach (object obj3 in securityElement6.Children)
                    {
                        SecurityElement securityElement7 = (SecurityElement)obj3;
                        NamedPermissionSet namedPermissionSet = new NamedPermissionSet();
                        namedPermissionSet.Resolver = this;
                        namedPermissionSet.FromXml(securityElement7);
                        this.named_permission_sets.Add(namedPermissionSet);
                    }
                }
                return;
            }
            throw new ArgumentException(Locale.GetText("Missing Root CodeGroup"));
        }
References System.Collections.Hashtable.Add(), System.Collections.ArrayList.Add(), System.Security.SecurityElement.Attribute(), System.Security.SecurityElement.Attributes, System.Security.SecurityElement.Children, System.Collections.ArrayList.Clear(), System.Collections.ArrayList.Count, System.Security.Policy.CodeGroup.CreateFromXml(), System.Security.NamedPermissionSet.FromXml(), System.Security.Policy.PolicyLevel.full_trust_assemblies, System.Security.Policy.PolicyLevel.fullNames, Locale.GetText(), System.Security.Policy.PolicyLevel.named_permission_sets, System.obj, System.Security.SecurityElement.SearchForChildByTag(), and System.Security.SecurityElement.Tag.
Referenced by System.Security.Policy.PolicyLevel.LoadFromFile(), and System.Security.Policy.PolicyLevel.LoadFromString().