Terraria Decompiled: System.Security.Policy.PolicyLevel.Reset
Reset()
void System.Security.Policy.PolicyLevel.Reset () inline
Definition at line 424 of file PolicyLevel.cs.
        {
            if (this.fullNames != null)
            {
                this.fullNames.Clear();
            }
            if (this._type != PolicyLevelType.AppDomain)
            {
                this.full_trust_assemblies.Clear();
                this.named_permission_sets.Clear();
                if (this._location != null && File.Exists(this._location))
                {
                    try
                    {
                        File.Delete(this._location);
                    }
                    catch
                    {
                    }
                }
                this.LoadFromFile(this._location);
                return;
            }
            this.CreateDefaultFullTrustAssemblies();
            this.CreateDefaultNamedPermissionSets();
        }
References System.Security.Policy.PolicyLevel._location, System.Security.Policy.PolicyLevel._type, System.Collections.ArrayList.Clear(), System.Collections.Hashtable.Clear(), System.Security.Policy.PolicyLevel.CreateDefaultFullTrustAssemblies(), System.Security.Policy.PolicyLevel.CreateDefaultNamedPermissionSets(), System.IO.File.Delete(), System.IO.File.Exists(), System.Security.Policy.PolicyLevel.full_trust_assemblies, System.Security.Policy.PolicyLevel.fullNames, System.Security.Policy.PolicyLevel.LoadFromFile(), and System.Security.Policy.PolicyLevel.named_permission_sets.
Referenced by System.Security.Policy.PolicyLevel.CreateAppDomainLevel().