Terraria Decompiled: System.Security.Policy.PolicyLevel.ToXml
ToXml()
SecurityElement System.Security.Policy.PolicyLevel.ToXml () inline
Definition at line 482 of file PolicyLevel.cs.
        {
            Hashtable hashtable = new Hashtable();
            if (this.full_trust_assemblies.Count > 0 && !hashtable.Contains("StrongNameMembershipCondition"))
            {
                hashtable.Add("StrongNameMembershipCondition", typeof(StrongNameMembershipCondition).FullName);
            }
            SecurityElement securityElement = new SecurityElement("NamedPermissionSets");
            foreach (object obj in this.named_permission_sets)
            {
                NamedPermissionSet namedPermissionSet = (NamedPermissionSet)obj;
                SecurityElement securityElement2 = namedPermissionSet.ToXml();
                object obj2 = securityElement2.Attributes["class"];
                if (!hashtable.Contains(obj2))
                {
                    hashtable.Add(obj2, namedPermissionSet.GetType().FullName);
                }
                securityElement.AddChild(securityElement2);
            }
            SecurityElement securityElement3 = new SecurityElement("FullTrustAssemblies");
            foreach (object obj3 in this.full_trust_assemblies)
            {
                StrongNameMembershipCondition strongNameMembershipCondition = (StrongNameMembershipCondition)obj3;
                securityElement3.AddChild(strongNameMembershipCondition.ToXml(this));
            }
            SecurityElement securityElement4 = new SecurityElement("SecurityClasses");
            if (hashtable.Count > 0)
            {
                foreach (object obj4 in hashtable)
                {
                    DictionaryEntry dictionaryEntry = (DictionaryEntry)obj4;
                    SecurityElement securityElement5 = new SecurityElement("SecurityClass");
                    securityElement5.AddAttribute("Name", (string)dictionaryEntry.Key);
                    securityElement5.AddAttribute("Description", (string)dictionaryEntry.Value);
                    securityElement4.AddChild(securityElement5);
                }
            }
            SecurityElement securityElement6 = new SecurityElement(typeof(PolicyLevel).Name);
            securityElement6.AddAttribute("version", "1");
            securityElement6.AddChild(securityElement4);
            securityElement6.AddChild(securityElement);
            if (this.root_code_group != null)
            {
                securityElement6.AddChild(this.root_code_group.ToXml(this));
            }
            securityElement6.AddChild(securityElement3);
            return securityElement6;
        }
References System.Collections.Hashtable.Add(), System.Security.SecurityElement.AddAttribute(), System.Security.SecurityElement.AddChild(), System.Security.SecurityElement.Attributes, System.Collections.Hashtable.Contains(), System.Collections.ArrayList.Count, System.Security.Policy.PolicyLevel.full_trust_assemblies, System.FullName, System.Collections.DictionaryEntry.Key, System.Name, System.Security.Policy.PolicyLevel.named_permission_sets, System.obj, System.Security.Policy.PolicyLevel.root_code_group, System.Security.NamedPermissionSet.ToXml(), System.Security.Policy.CodeGroup.ToXml(), System.Security.Policy.StrongNameMembershipCondition.ToXml(), and System.Collections.DictionaryEntry.Value.
Referenced by System.Security.Policy.PolicyLevel.Save().