Terraria Decompiled: System.Security.Policy.PolicyLevel.IsFullTrustAssembly
IsFullTrustAssembly()
bool System.Security.Policy.PolicyLevel.IsFullTrustAssembly (Assembly a) inline package
Definition at line 650 of file PolicyLevel.cs.
        {
            AssemblyName name = a.GetName();
            StrongNameMembershipCondition strongNameMembershipCondition = new StrongNameMembershipCondition(new StrongNamePublicKeyBlob(name.GetPublicKey()), name.Name, name.Version);
            using (IEnumerator enumerator = this.full_trust_assemblies.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (((StrongNameMembershipCondition)enumerator.Current).Equals(strongNameMembershipCondition))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References System.Collections.IEnumerator.Current, System.Security.Policy.PolicyLevel.full_trust_assemblies, System.Collections.ArrayList.GetEnumerator(), System.Reflection.Assembly.GetName(), System.Collections.IEnumerator.MoveNext(), and System.name.