Terraria Decompiled: System.Security.Policy.PolicyLevel.LoadFromFile
LoadFromFile()
void System.Security.Policy.PolicyLevel.LoadFromFile (string filename) inline package
Definition at line 26 of file PolicyLevel.cs.
        {
            try
            {
                if (!File.Exists(filename))
                {
                    string text = filename + ".default";
                    if (File.Exists(text))
                    {
                        File.Copy(text, filename);
                    }
                }
                if (File.Exists(filename))
                {
                    using (StreamReader streamReader = File.OpenText(filename))
                    {
                        this.xml = this.FromString(streamReader.ReadToEnd());
                    }
                    try
                    {
                        SecurityManager.ResolvingPolicyLevel = this;
                        this.FromXml(this.xml);
                        goto IL_008A;
                    }
                    finally
                    {
                        SecurityManager.ResolvingPolicyLevel = this;
                    }
                }
                this.CreateDefaultFullTrustAssemblies();
                this.CreateDefaultNamedPermissionSets();
                this.CreateDefaultLevel(this._type);
                this.Save();
                IL_008A:;
            }
            catch
            {
            }
            finally
            {
                this._location = filename;
            }
        }
References System.Security.Policy.PolicyLevel._type, System.IO.File.Copy(), System.Security.Policy.PolicyLevel.CreateDefaultFullTrustAssemblies(), System.Security.Policy.PolicyLevel.CreateDefaultLevel(), System.Security.Policy.PolicyLevel.CreateDefaultNamedPermissionSets(), System.IO.File.Exists(), System.Security.Policy.PolicyLevel.FromString(), System.Security.Policy.PolicyLevel.FromXml(), System.IO.File.OpenText(), System.IO.StreamReader.ReadToEnd(), System.Security.Policy.PolicyLevel.Save(), System.text, and System.Security.Policy.PolicyLevel.xml.
Referenced by System.Security.SecurityManager.InitializePolicyHierarchy(), System.Security.SecurityManager.LoadPolicyLevelFromFile(), and System.Security.Policy.PolicyLevel.Reset().