Terraria Decompiled: Terraria.GameInput.TriggersSet.CopyInto
CopyInto()
void Terraria.GameInput.TriggersSet.CopyInto (Player p) inline
Definition at line 967 of file TriggersSet.cs.
        {
            if (PlayerInput.CurrentInputMode != InputMode.XBoxGamepadUI && !PlayerInput.CursorIsBusy)
            {
                p.controlUp = this.Up;
                p.controlDown = this.Down;
                p.controlLeft = this.Left;
                p.controlRight = this.Right;
                p.controlJump = this.Jump;
                p.controlHook = this.Grapple;
                if (!p.mouseInterface)
                {
                    p.controlTorch = this.SmartSelect;
                }
                p.controlSmart = this.SmartCursor;
                p.controlMount = this.QuickMount;
                p.controlQuickHeal = this.QuickHeal;
                p.controlQuickMana = this.QuickMana;
                p.controlCreativeMenu = this.OpenCreativePowersMenu;
                if (this.QuickBuff)
                {
                    p.QuickBuff();
                }
                if (Utils.JustBecameTrue(this.Loadout1, ref p.releaseLoadout1))
                {
                    p.TrySwitchingLoadout(0);
                }
                if (Utils.JustBecameTrue(this.Loadout2, ref p.releaseLoadout2))
                {
                    p.TrySwitchingLoadout(1);
                }
                if (Utils.JustBecameTrue(this.Loadout3, ref p.releaseLoadout3))
                {
                    p.TrySwitchingLoadout(2);
                }
                if (Utils.JustBecameTrue(this.NextLoadout, ref p.releaseNextLoadout))
                {
                    p.TrySwitchingToNextLoadout();
                }
                if (Utils.JustBecameTrue(this.PreviousLoadout, ref p.releasePreviousLoadout))
                {
                    p.TrySwitchingToPreviousLoadout();
                }
                p.controlDash = this.Dash;
                if (!p.controlDash)
                {
                    p.releaseDash = true;
                }
                p.controlArmorSetAbility = this.ArmorSetAbility;
            }
            p.controlInv = this.Inventory;
            p.controlThrow = this.Throw;
            p.mapZoomIn = this.MapZoomIn;
            p.mapZoomOut = this.MapZoomOut;
            p.mapAlphaUp = this.MapAlphaUp;
            p.mapAlphaDown = this.MapAlphaDown;
            p.mapFullScreen = this.MapFull;
            p.mapStyle = this.MapStyle;
            if (this.MouseLeft)
            {
                if (!Main.blockMouse && !p.mouseInterface)
                {
                    p.controlUseItem = true;
                }
            }
            else
            {
                Main.blockMouse = false;
            }
            if (!Main.playerInventory && Main.player[Main.myPlayer].stressBall && Main.player[Main.myPlayer].CanUseStressBall() && !this.MouseLeft && !Main.blockMouse && !p.mouseInterface)
            {
                p.controlUseItem = true;
            }
            if (!this.MouseRight && !Main.playerInventory)
            {
                PlayerInput.LockGamepadTileUseButton = false;
            }
            if (this.MouseRight && !p.mouseInterface && !Main.blockMouse && !this.ShouldLockTileUsage() && !PlayerInput.InBuildingMode)
            {
                p.controlUseTile = true;
            }
            if (PlayerInput.InBuildingMode && this.MouseRight)
            {
                p.controlInv = true;
            }
            InputMode inputMode;
            if (this.SmartSelect && this.LatestInputMode.TryGetValue("SmartSelect", out inputMode) && this.IsInputFromGamepad(inputMode))
            {
                PlayerInput.SettingsForUI.SetCursorMode(CursorMode.Gamepad);
            }
            bool flag = PlayerInput.Triggers.Current.HotbarPlus || PlayerInput.Triggers.Current.HotbarMinus;
            if (flag)
            {
                this.HotbarHoldTime++;
            }
            else
            {
                this.HotbarHoldTime = 0;
            }
            if (this.HotbarScrollCD > 0 && (this.HotbarScrollCD != 1 || !flag || PlayerInput.CurrentProfile.HotbarRadialHoldTimeRequired <= 0))
            {
                this.HotbarScrollCD--;
            }
        }
References Terraria.GameInput.TriggersSet.ArmorSetAbility, Terraria.Main.blockMouse, Terraria.Player.CanUseStressBall(), Terraria.Player.controlDash, Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInput.CursorIsBusy, Terraria.GameInput.TriggersSet.Dash, Terraria.GameInput.TriggersSet.Down, Terraria.GameInput.TriggersSet.Grapple, Terraria.GameInput.TriggersSet.HotbarHoldTime, Terraria.GameInput.TriggersSet.HotbarMinus, Terraria.GameInput.PlayerInputProfile.HotbarRadialHoldTimeRequired, Terraria.GameInput.TriggersSet.HotbarScrollCD, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.GameInput.TriggersSet.Inventory, Terraria.GameInput.TriggersSet.Jump, Terraria.Utils.JustBecameTrue(), Terraria.GameInput.TriggersSet.LatestInputMode, Terraria.GameInput.TriggersSet.Left, Terraria.GameInput.TriggersSet.MapAlphaDown, Terraria.GameInput.TriggersSet.MapAlphaUp, Terraria.GameInput.TriggersSet.MapFull, Terraria.GameInput.TriggersSet.MapStyle, Terraria.GameInput.TriggersSet.MapZoomIn, Terraria.GameInput.TriggersSet.MapZoomOut, Terraria.Player.mouseInterface, Terraria.GameInput.TriggersSet.MouseLeft, Terraria.GameInput.TriggersSet.MouseRight, Terraria.Main.myPlayer, Terraria.GameInput.TriggersSet.OpenCreativePowersMenu, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.GameInput.TriggersSet.QuickBuff, Terraria.Player.QuickBuff(), Terraria.GameInput.TriggersSet.QuickHeal, Terraria.GameInput.TriggersSet.QuickMana, Terraria.GameInput.TriggersSet.QuickMount, Terraria.Player.releaseLoadout1, Terraria.Player.releaseLoadout2, Terraria.Player.releaseLoadout3, Terraria.Player.releaseNextLoadout, Terraria.Player.releasePreviousLoadout, Terraria.GameInput.TriggersSet.Right, Terraria.GameInput.PlayerInput.SettingsForUI.SetCursorMode(), Terraria.GameInput.TriggersSet.SmartCursor, Terraria.GameInput.TriggersSet.SmartSelect, Terraria.Player.stressBall, Terraria.GameInput.TriggersSet.Throw, Terraria.GameInput.PlayerInput.Triggers, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.Player.TrySwitchingLoadout(), Terraria.Player.TrySwitchingToNextLoadout(), Terraria.Player.TrySwitchingToPreviousLoadout(), and Terraria.GameInput.TriggersSet.Up.
Referenced by Terraria.Player.Ghost(), Terraria.Player.Update(), and Terraria.Player.UpdateDead().