Terraria Decompiled: Terraria.GameInput.TriggersSet.CloneFrom
CloneFrom()
void Terraria.GameInput.TriggersSet.CloneFrom (TriggersSet other) inline
Definition at line 922 of file TriggersSet.cs.
        {
            this.KeyStatus.Clear();
            this.LatestInputMode.Clear();
            foreach (KeyValuePair<string, bool> keyValuePair in other.KeyStatus)
            {
                this.KeyStatus.Add(keyValuePair.Key, keyValuePair.Value);
            }
            this.UsedMovementKey = other.UsedMovementKey;
            this.HotbarScrollCD = other.HotbarScrollCD;
            this.HotbarHoldTime = other.HotbarHoldTime;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.GameInput.TriggersSet.KeyStatus, Terraria.GameInput.TriggersSet.LatestInputMode, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.GameInput.TriggersPack.Reset().