Terraria Decompiled: System.IO.TextWriter.WriteAsync
WriteAsync() [4/5]
virtual Task System.IO.TextWriter.WriteAsync (ReadOnlyMemory< char > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented in System.IO.StreamWriter.
Definition at line 454 of file TextWriter.cs.
        {
            ArraySegment<char> arraySegment;
            if (!MemoryMarshal.TryGetArray<char>(buffer, out arraySegment))
            {
                return Task.Factory.StartNew(delegate(object state)
                {
                    Tuple<TextWriter, ReadOnlyMemory<char>> tuple = (Tuple<TextWriter, ReadOnlyMemory<char>>)state;
                    tuple.Item1.Write(tuple.Item2.Span);
                }, Tuple.Create<TextWriter, ReadOnlyMemory<char>>(this, buffer), cancellationToken, TaskCreationOptions.DenyChildAttach, TaskScheduler.Default);
            }
            return this.WriteAsync(arraySegment.Array, arraySegment.Offset, arraySegment.Count);
        }
References System.ArraySegment< T >.Array, System.ArraySegment< T >.Count, System.Threading.Tasks.TaskScheduler.Default, System.Threading.Tasks.Task< TResult >.Factory, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, System.ArraySegment< T >.Offset, System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.state, System.IO.TextWriter.TextWriter(), and System.IO.TextWriter.WriteAsync().