Terraria Decompiled: System.Globalization.PersianCalendar.GetDatePart
GetDatePart()
int System.Globalization.PersianCalendar.GetDatePart (long ticks, int part) inline package
Definition at line 137 of file PersianCalendar.cs.
        {
            PersianCalendar.CheckTicksRange(ticks);
            long num = ticks / 864000000000L + 1L;
            int num2 = (int)Math.Floor((double)(CalendricalCalculationsHelper.PersianNewYearOnOrBefore(num) - PersianCalendar.PersianEpoch) / 365.242189 + 0.5) + 1;
            if (part == 0)
            {
                return num2;
            }
            int num3 = (int)(num - CalendricalCalculationsHelper.GetNumberOfDays(this.ToDateTime(num2, 1, 1, 0, 0, 0, 0, 1)));
            if (part == 1)
            {
                return num3;
            }
            int num4 = PersianCalendar.MonthFromOrdinalDay(num3);
            if (part == 2)
            {
                return num4;
            }
            int num5 = num3 - PersianCalendar.DaysInPreviousMonths(num4);
            if (part == 3)
            {
                return num5;
            }
            throw new InvalidOperationException(Environment.GetResourceString("Internal Error in DateTime and Calendar operations."));
        }
References System.Globalization.PersianCalendar.CheckTicksRange(), System.Globalization.PersianCalendar.DaysInPreviousMonths(), System.Math.Floor(), System.Globalization.CalendricalCalculationsHelper.GetNumberOfDays(), System.Environment.GetResourceString(), int, System.L, System.Globalization.PersianCalendar.MonthFromOrdinalDay(), System.Globalization.PersianCalendar.PersianEpoch, and System.Globalization.CalendricalCalculationsHelper.PersianNewYearOnOrBefore().
Referenced by System.Globalization.PersianCalendar.AddMonths(), System.Globalization.PersianCalendar.GetDayOfMonth(), System.Globalization.PersianCalendar.GetDayOfYear(), System.Globalization.PersianCalendar.GetMonth(), and System.Globalization.PersianCalendar.GetYear().