Terraria Decompiled: System.IO.DirectoryInfo.MoveTo
MoveTo()
void System.IO.DirectoryInfo.MoveTo (string destDirName) inline
Definition at line 263 of file DirectoryInfo.cs.
        {
            if (destDirName == null)
            {
                throw new ArgumentNullException("destDirName");
            }
            if (destDirName.Length == 0)
            {
                throw new ArgumentException("Empty file name is not legal.", "destDirName");
            }
            string fullPath = Path.GetFullPath(destDirName);
            string text = PathInternal.EnsureTrailingSeparator(fullPath);
            string text2 = PathInternal.EnsureTrailingSeparator(this.FullPath);
            if (string.Equals(text2, text, PathInternal.StringComparison))
            {
                throw new IOException("Source and destination path must be different.");
            }
            string pathRoot = Path.GetPathRoot(text2);
            string pathRoot2 = Path.GetPathRoot(text);
            if (!string.Equals(pathRoot, pathRoot2, PathInternal.StringComparison))
            {
                throw new IOException("Source and destination path must have identical roots. Move will not work across volumes.");
            }
            if (!this.Exists && !FileSystem.FileExists(this.FullPath))
            {
                throw new DirectoryNotFoundException(SR.Format("Could not find a part of the path '{0}'.", this.FullPath));
            }
            if (FileSystem.DirectoryExists(fullPath))
            {
                throw new IOException(SR.Format("Cannot create '{0}' because a file or directory with the same name already exists.", text));
            }
            FileSystem.MoveDirectory(this.FullPath, fullPath);
            this.Init(destDirName, text, null, true);
            base.Invalidate();
        }
References System.IO.FileSystem.DirectoryExists(), System.IO.PathInternal.EnsureTrailingSeparator(), System.IO.FileSystemInfo.Exists, System.IO.FileSystem.FileExists(), SR.Format(), System.IO.FileSystemInfo.FullPath, System.IO.Path.GetFullPath(), System.IO.Path.GetPathRoot(), System.IO.DirectoryInfo.Init(), System.IO.FileSystem.MoveDirectory(), System.IO.PathInternal.StringComparison, and System.text.