Terraria Decompiled: System.IO.DirectoryInfo.InternalEnumerateInfos
InternalEnumerateInfos()
static IEnumerable< FileSystemInfo > System.IO.DirectoryInfo.InternalEnumerateInfos (string path, string searchPattern, SearchTarget searchTarget, EnumerationOptions options) inline static package
Definition at line 232 of file DirectoryInfo.cs.
        {
            if (searchPattern == null)
            {
                throw new ArgumentNullException("searchPattern");
            }
            FileSystemEnumerableFactory.NormalizeInputs(ref path, ref searchPattern, options);
            switch (searchTarget)
            {
            case SearchTarget.Files:
                return FileSystemEnumerableFactory.FileInfos(path, searchPattern, options);
            case SearchTarget.Directories:
                return FileSystemEnumerableFactory.DirectoryInfos(path, searchPattern, options);
            case SearchTarget.Both:
                return FileSystemEnumerableFactory.FileSystemInfos(path, searchPattern, options);
            default:
                throw new ArgumentException("Enum value was out of legal range.", "searchTarget");
            }
        }
References System.IO.Enumeration.FileSystemEnumerableFactory.DirectoryInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.FileInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.FileSystemInfos(), System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(), and System.options.
Referenced by System.IO.DirectoryInfo.EnumerateDirectories(), System.IO.DirectoryInfo.EnumerateFiles(), System.IO.DirectoryInfo.EnumerateFileSystemInfos(), System.IO.DirectoryInfo.GetDirectories(), System.IO.DirectoryInfo.GetFiles(), and System.IO.DirectoryInfo.GetFileSystemInfos().