Terraria Decompiled: Theorafile.Utf8Encode
Utf8Encode()
static unsafe byte * Theorafile.Utf8Encode (string str) inline static private
Definition at line 10 of file Theorafile.cs.
    {
        int num = str.Length * 4 + 1;
        byte* ptr = (byte*)(void*)Marshal.AllocHGlobal(num);
        fixed (string text = str)
        {
            char* ptr2 = text;
            if (ptr2 != null)
            {
                ptr2 += RuntimeHelpers.OffsetToStringData / 2;
            }
            Encoding.UTF8.GetBytes(ptr2, str.Length + 1, ptr, num);
        }
        return ptr;
    }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Text.Encoding.GetBytes(), System.text, and System.Text.Encoding.UTF8.
Referenced by tf_fopen().