Terraria Decompiled: Theorafile.tf_close
tf_close()
static int Theorafile.tf_close (ref IntPtr file) inline static
Definition at line 68 of file Theorafile.cs.
    {
        int num = Theorafile.INTERNAL_tf_close(file);
        Marshal.FreeHGlobal(file);
        file = IntPtr.Zero;
        return num;
    }
References System.Runtime.InteropServices.Marshal.FreeHGlobal(), INTERNAL_tf_close(), and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerTheora.Dispose(), Microsoft.Xna.Framework.Media.VideoPlayerTheora.Play(), and Microsoft.Xna.Framework.Media.VideoPlayerTheora.ReadInfo().