Terraria Decompiled: Newtonsoft.Json.JsonPosition.FormatMessage
FormatMessage()
static string Newtonsoft.Json.JsonPosition.FormatMessage (IJsonLineInfo lineInfo, string path, string message) inline static package
Definition at line 106 of file JsonPosition.cs.
        {
            if (!message.EndsWith(Environment.NewLine, 4))
            {
                message = message.Trim();
                if (!message.EndsWith('.'))
                {
                    message += ".";
                }
                message += " ";
            }
            message += "Path '{0}'".FormatWith(CultureInfo.InvariantCulture, path);
            if (lineInfo != null && lineInfo.HasLineInfo())
            {
                message += ", line {0}, position {1}".FormatWith(CultureInfo.InvariantCulture, lineInfo.LineNumber, lineInfo.LinePosition);
            }
            message += ".";
            return message;
        }
References Newtonsoft.Json.IJsonLineInfo.HasLineInfo(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.IJsonLineInfo.LineNumber, and Newtonsoft.Json.IJsonLineInfo.LinePosition.
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.AddReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.CheckForCircularReference(), Newtonsoft.Json.JsonException.Create(), Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.JsonWriterException.Create(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateISerializable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.IsErrorHandled(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.IsSpecified(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.OnDeserializing(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerialized(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.OnSerializing(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataProperties(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ReadMetadataPropertiesToken(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolvePropertyAndCreatorValues(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ResolveTypeName(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeConvertable(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.SetPropertyValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ShouldDeserialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldSerialize(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReference(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteReferenceIdProperty(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.WriteTypeProperty().