Terraria Decompiled: Newtonsoft.Json.JsonPosition.BuildPath
BuildPath()
static string Newtonsoft.Json.JsonPosition.BuildPath (List< JsonPosition > positions, JsonPosition? currentPosition) inline static package
Definition at line 76 of file JsonPosition.cs.
        {
            int num = 0;
            if (positions != null)
            {
                for (int i = 0; i < positions.Count; i++)
                {
                    num += positions[i].CalculateLength();
                }
            }
            if (currentPosition != null)
            {
                num += currentPosition.GetValueOrDefault().CalculateLength();
            }
            StringBuilder stringBuilder = new StringBuilder(num);
            if (positions != null)
            {
                foreach (JsonPosition jsonPosition in positions)
                {
                    jsonPosition.WriteTo(stringBuilder);
                }
            }
            if (currentPosition != null)
            {
                currentPosition.GetValueOrDefault().WriteTo(stringBuilder);
            }
            return stringBuilder.ToString();
        }
References Newtonsoft.Json.JsonPosition.CalculateLength(), System.Collections.Generic.List< T >.Count, System.Text.StringBuilder.ToString(), and Newtonsoft.Json.JsonPosition.WriteTo().