Terraria Decompiled: Terraria.Social.Steam.CloudSocialModule.Write
Write()
override bool Terraria.Social.Steam.CloudSocialModule.Write (string path, byte[] data, int length) inline
Definition at line 41 of file CloudSocialModule.cs.
        {
            object obj = this.ioLock;
            bool flag3;
            lock (obj)
            {
                UGCFileWriteStreamHandle_t ugcfileWriteStreamHandle_t = SteamRemoteStorage.FileWriteStreamOpen(path);
                bool flag2 = false;
                uint num = 0U;
                while ((ulong)num < (ulong)((long)length))
                {
                    int num2 = (int)Math.Min(1024L, (long)length - (long)((ulong)num));
                    Array.Copy(data, (long)((ulong)num), this.writeBuffer, 0L, (long)num2);
                    if (!SteamRemoteStorage.FileWriteStreamWriteChunk(ugcfileWriteStreamHandle_t, this.writeBuffer, num2))
                    {
                        flag2 = true;
                        break;
                    }
                    num += 1024U;
                }
                if (flag2)
                {
                    SteamRemoteStorage.FileWriteStreamCancel(ugcfileWriteStreamHandle_t);
                    flag3 = false;
                }
                else
                {
                    flag3 = SteamRemoteStorage.FileWriteStreamClose(ugcfileWriteStreamHandle_t);
                }
            }
            return flag3;
        }
References System.Array.Copy(), Steamworks.SteamRemoteStorage.FileWriteStreamCancel(), Steamworks.SteamRemoteStorage.FileWriteStreamClose(), Steamworks.SteamRemoteStorage.FileWriteStreamOpen(), Steamworks.SteamRemoteStorage.FileWriteStreamWriteChunk(), int, Terraria.Social.Steam.CloudSocialModule.ioLock, System.L, System.length, long, System.Math.Min(), System.obj, System.U, and Terraria.Social.Steam.CloudSocialModule.writeBuffer.