Terraria Decompiled: Mono.Security.StrongName.IsAssemblyStrongnamed
IsAssemblyStrongnamed()
static bool Mono.Security.StrongName.IsAssemblyStrongnamed (string assemblyName) inline static
Definition at line 515 of file StrongName.cs.
        {
            if (!StrongName.initialized)
            {
                object obj = StrongName.lockObject;
                lock (obj)
                {
                    if (!StrongName.initialized)
                    {
                        StrongNameManager.LoadConfig(Environment.GetMachineConfigPath());
                        StrongName.initialized = true;
                    }
                }
            }
            bool flag;
            try
            {
                AssemblyName assemblyName2 = AssemblyName.GetAssemblyName(assemblyName);
                if (assemblyName2 == null)
                {
                    flag = false;
                }
                else
                {
                    byte[] mappedPublicKey = StrongNameManager.GetMappedPublicKey(assemblyName2.GetPublicKeyToken());
                    if (mappedPublicKey == null || mappedPublicKey.Length < 12)
                    {
                        mappedPublicKey = assemblyName2.GetPublicKey();
                        if (mappedPublicKey == null || mappedPublicKey.Length < 12)
{
                            return false;
                        }
                    }
                    if (!StrongNameManager.MustVerify(assemblyName2))
                    {
                        flag = true;
                    }
                    else
                    {
                        flag = new StrongName(CryptoConvert.FromCapiPublicKeyBlob(mappedPublicKey, 12)).Verify(assemblyName);
                    }
                }
            }
            catch
            {
                flag = false;
            }
            return flag;
        }
References Mono.Security.Cryptography.CryptoConvert.FromCapiPublicKeyBlob(), System.Reflection.AssemblyName.GetAssemblyName(), Mono.Security.StrongNameManager.GetMappedPublicKey(), System.Reflection.AssemblyName.GetPublicKey(), System.Reflection.AssemblyName.GetPublicKeyToken(), Mono.Security.StrongName.initialized, Mono.Security.StrongNameManager.LoadConfig(), Mono.Security.StrongName.lockObject, Mono.Security.StrongNameManager.MustVerify(), System.obj, and Mono.Security.StrongName.StrongName().