Terraria Decompiled: Mono.Security.StrongName.Sign
Sign()
bool Mono.Security.StrongName.Sign (string fileName) inline
Definition at line 447 of file StrongName.cs.
        {
            StrongName.StrongNameSignature strongNameSignature;
            using (FileStream fileStream = File.OpenRead(fileName))
            {
                strongNameSignature = this.StrongHash(fileStream, StrongName.StrongNameOptions.Signature);
            }
            if (strongNameSignature.Hash == null)
            {
                return false;
            }
            byte[] array = null;
            try
            {
                RSAPKCS1SignatureFormatter rsapkcs1SignatureFormatter = new RSAPKCS1SignatureFormatter(this.rsa);
                rsapkcs1SignatureFormatter.SetHashAlgorithm(this.TokenAlgorithm);
                array = rsapkcs1SignatureFormatter.CreateSignature(strongNameSignature.Hash);
                Array.Reverse<byte>(array);
            }
            catch (CryptographicException)
            {
                return false;
            }
            using (FileStream fileStream2 = File.OpenWrite(fileName))
            {
                fileStream2.Position = (long)((ulong)strongNameSignature.SignaturePosition);
                fileStream2.Write(array, 0, array.Length);
            }
            return true;
        }
References System.array, System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(), Mono.Security.StrongName.StrongNameSignature.Hash, long, System.IO.File.OpenRead(), System.IO.File.OpenWrite(), System.Array.Reverse(), Mono.Security.StrongName.rsa, System.Security.Cryptography.RSAPKCS1SignatureFormatter.SetHashAlgorithm(), Mono.Security.StrongName.StrongNameSignature.SignaturePosition, Mono.Security.StrongName.StrongHash(), Mono.Security.StrongName.TokenAlgorithm, and System.IO.FileStream.Write().