Terraria Decompiled: Mono.Security.StrongName.StrongHash
StrongHash()
StrongName.StrongNameSignature Mono.Security.StrongName.StrongHash (Stream stream, StrongName::StrongNameOptions options) inline package
Definition at line 256 of file StrongName.cs.
        {
            byte[] array = new byte[64];
            int num = stream.Read(array, 0, 64);
            if (num == 64 && array[0] == 77 && array[1] == 90)
            {
                int num2 = BitConverterLE.ToInt32(array, 60);
                if (num2 < 64)
                {
                    return StrongName.Error("peHeader_lt_64");
                }
                array = StrongName.ReadMore(stream, array, num2);
                if (array == null)
                {
                    return StrongName.Error("read_mz2_failed");
                }
            }
            else
            {
                if (num < 4 || array[0] != 80 || array[1] != 69 || array[2] != 0 || array[3] != 0)
                {
                    return StrongName.Error("read_mz_or_mzsig_failed");
                }
                stream.Position = 0L;
                array = new byte[0];
            }
            int num3 = 2;
            int num4 = 24 + num3;
            byte[] array2 = new byte[num4];
            if (stream.Read(array2, 0, num4) != num4 || array2[0] != 80 || array2[1] != 69 || array2[2] != 0 || array2[3] != 0)
            {
                return StrongName.Error("read_minimumHeadersSize_or_pesig_failed");
            }
            num3 = (int)BitConverterLE.ToUInt16(array2, 20);
            if (num3 < 2)
            {
                return StrongName.Error(string.Format("sizeOfOptionalHeader_lt_2 ${0}", num3));
            }
            int num5 = 24 + num3;
            if (num5 < 24)
            {
                return StrongName.Error("headers_overflow");
            }
            array2 = StrongName.ReadMore(stream, array2, num5);
            if (array2 == null)
            {
                return StrongName.Error("read_pe2_failed");
            }
            uint num6 = (uint)BitConverterLE.ToUInt16(array2, 24);
            int num7 = 0;
            bool flag = false;
            if (num6 != 267U)
            {
                if (num6 == 523U)
                {
                    num7 = 16;
                }
                else
                {
                    if (num6 != 263U)
                    {
                        return StrongName.Error("bad_magic_value");
                    }
                    flag = true;
                }
            }
            uint num8 = 0U;
            if (!flag)
            {
                if (num3 >= 116 + num7 + 4)
                {
                    num8 = BitConverterLE.ToUInt32(array2, 116 + num7);
                }
                int num9 = 64;
                while (num9 < num3 && num9 < 68)
                {
                    array2[24 + num9] = 0;
                    num9++;
                }
                int num10 = 128 + num7;
                while (num10 < num3 && num10 < 136 + num7)
                {
                    array2[24 + num10] = 0;
                    num10++;
                }
            }
            int num11 = (int)BitConverterLE.ToUInt16(array2, 6);
            byte[] array3 = new byte[num11 * 40];
            if (stream.Read(array3, 0, array3.Length) != array3.Length)
            {
                return StrongName.Error("read_section_headers_failed");
            }
            uint num12 = 0U;
            uint num13 = 0U;
            uint num14 = 0U;
            uint num15 = 0U;
            if (15U < num8 && num3 >= 216 + num7)
            {
                uint num16 = BitConverterLE.ToUInt32(array2, 232 + num7);
                uint num17 = this.RVAtoPosition(num16, num11, array3);
                int num18 = BitConverterLE.ToInt32(array2, 236 + num7);
                byte[] array4 = new byte[num18];
                stream.Position = (long)((ulong)num17);
                if (stream.Read(array4, 0, num18) != num18)
                {
                    return StrongName.Error("read_cli_header_failed");
                }
                uint num19 = BitConverterLE.ToUInt32(array4, 32);
                num12 = this.RVAtoPosition(num19, num11, array3);
                num13 = BitConverterLE.ToUInt32(array4, 36);
                uint num20 = BitConverterLE.ToUInt32(array4, 8);
                num14 = this.RVAtoPosition(num20, num11, array3);
                num15 = BitConverterLE.ToUInt32(array4, 12);
            }
            StrongName.StrongNameSignature strongNameSignature = new StrongName.StrongNameSignature();
            strongNameSignature.SignaturePosition = num12;
            strongNameSignature.SignatureLength = num13;
            strongNameSignature.MetadataPosition = num14;
            strongNameSignature.MetadataLength = num15;
            using (HashAlgorithm hashAlgorithm = HashAlgorithm.Create(this.TokenAlgorithm))
            {
                if (options == StrongName.StrongNameOptions.Metadata)
                {
                    hashAlgorithm.Initialize();
                    byte[] array5 = new byte[num15];
                    stream.Position = (long)((ulong)num14);
                    if (stream.Read(array5, 0, (int)num15) != (int)num15)
                    {
                        return StrongName.Error("read_cli_metadata_failed");
                    }
                    strongNameSignature.Hash = hashAlgorithm.ComputeHash(array5);
                    return strongNameSignature;
                }
                else
                {
                    using (CryptoStream cryptoStream = new CryptoStream(Stream.Null, hashAlgorithm, CryptoStreamMode.Write))
                    {
                        cryptoStream.Write(array, 0, array.Length);
                        cryptoStream.Write(array2, 0, array2.Length);
                        cryptoStream.Write(array3, 0, array3.Length);
                        for (int i = 0; i < num11; i++)
{
                            uint num21 = BitConverterLE.ToUInt32(array3, i * 40 + 20);
                            int num22 = BitConverterLE.ToInt32(array3, i * 40 + 16);
                            byte[] array6 = new byte[num22];
                            stream.Position = (long)((ulong)num21);
                            if (stream.Read(array6, 0, num22) != num22)
{
                                return StrongName.Error("read_section_failed");
                            }
                            if (num21 <= num12 && num12 < num21 + (uint)num22)
{
                                int num23 = (int)(num12 - num21);
                                if (num23 > 0)
{
                                    cryptoStream.Write(array6, 0, num23);
                                }
                                strongNameSignature.Signature = new byte[num13];
                                Buffer.BlockCopy(array6, num23, strongNameSignature.Signature, 0, (int)num13);
                                Array.Reverse<byte>(strongNameSignature.Signature);
                                int num24 = (int)((long)num23 + (long)((ulong)num13));
                                int num25 = num22 - num24;
                                if (num25 > 0)
{
                                    cryptoStream.Write(array6, num24, num25);
                                }
                            }
                            else
{
                                cryptoStream.Write(array6, 0, num22);
                            }
                        }
                    }
                    strongNameSignature.Hash = hashAlgorithm.Hash;
                }
            }
            return strongNameSignature;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Security.Cryptography.HashAlgorithm.Create(), Mono.Security.StrongName.Error(), System.Globalization.Format, System.Security.Cryptography.HashAlgorithm.Hash, System.Security.Cryptography.HashAlgorithm.Initialize(), int, System.L, long, System.IO.Stream.Null, System.options, System.IO.Stream.Read(), Mono.Security.StrongName.ReadMore(), System.Array.Reverse(), Mono.Security.StrongName.RVAtoPosition(), Mono.Security.StrongName.StrongNameSignature.Signature, Mono.Security.BitConverterLE.ToInt32(), Mono.Security.StrongName.TokenAlgorithm, Mono.Security.BitConverterLE.ToUInt16(), Mono.Security.BitConverterLE.ToUInt32(), System.U, and System.Security.Cryptography.CryptoStream.Write().
Referenced by Mono.Security.StrongName.Hash(), Mono.Security.StrongName.Sign(), and Mono.Security.StrongName.Verify().