Terraria Decompiled: Terraria.Cinematics.DD2Film.DD2Film
DD2Film()
Terraria.Cinematics.DD2Film.DD2Film () inline
Definition at line 15 of file DD2Film.cs.
        {
            base.AppendKeyFrames(new FrameEvent[]
            {
                new FrameEvent(this.CreateDryad),
                new FrameEvent(this.CreateCritters)
            });
            base.AppendSequences(120, new FrameEvent[]
            {
                new FrameEvent(this.DryadStand),
                new FrameEvent(this.DryadLookRight)
            });
            base.AppendSequences(100, new FrameEvent[]
            {
                new FrameEvent(this.DryadLookRight),
                new FrameEvent(this.DryadInteract)
            });
            base.AddKeyFrame(base.AppendPoint - 20, new FrameEvent(this.CreatePortal));
            base.AppendSequences(30, new FrameEvent[]
            {
                new FrameEvent(this.DryadLookLeft),
                new FrameEvent(this.DryadStand)
            });
            base.AppendSequences(40, new FrameEvent[]
            {
                new FrameEvent(this.DryadConfusedEmote),
                new FrameEvent(this.DryadStand),
                new FrameEvent(this.DryadLookLeft)
            });
            base.AppendKeyFrame(new FrameEvent(this.CreateOgre));
            base.AddKeyFrame(base.AppendPoint + 60, new FrameEvent(this.SpawnJavalinThrower));
            base.AddKeyFrame(base.AppendPoint + 120, new FrameEvent(this.SpawnGoblin));
            base.AddKeyFrame(base.AppendPoint + 180, new FrameEvent(this.SpawnGoblin));
            base.AddKeyFrame(base.AppendPoint + 240, new FrameEvent(this.SpawnWitherBeast));
            base.AppendSequences(30, new FrameEvent[]
            {
                new FrameEvent(this.DryadStand),
                new FrameEvent(this.DryadLookLeft)
            });
            base.AppendSequences(30, new FrameEvent[]
            {
                new FrameEvent(this.DryadLookRight),
                new FrameEvent(this.DryadWalk)
            });
            base.AppendSequences(300, new FrameEvent[]
            {
                new FrameEvent(this.DryadAttack),
                new FrameEvent(this.DryadLookLeft)
            });
            base.AppendKeyFrame(new FrameEvent(this.RemoveEnemyDamage));
            base.AppendSequences(60, new FrameEvent[]
            {
                new FrameEvent(this.DryadLookRight),
                new FrameEvent(this.DryadStand),
                new FrameEvent(this.DryadAlertEmote)
            });
            base.AddSequences(base.AppendPoint - 90, 60, new FrameEvent[]
            {
                new FrameEvent(this.OgreLookLeft),
                new FrameEvent(this.OgreStand)
            });
            base.AddKeyFrame(base.AppendPoint - 12, new FrameEvent(this.OgreSwingSound));
            base.AddSequences(base.AppendPoint - 30, 50, new FrameEvent[]
            {
                new FrameEvent(this.DryadPortalKnock),
                new FrameEvent(this.DryadStand)
            });
            base.AppendKeyFrame(new FrameEvent(this.RestoreEnemyDamage));
            base.AppendSequences(40, new FrameEvent[]
            {
                new FrameEvent(this.DryadPortalFade),
                new FrameEvent(this.DryadStand)
            });
            base.AppendSequence(180, new FrameEvent(this.DryadStand));
            base.AddSequence(0, base.AppendPoint, new FrameEvent(this.PerFrameSettings));
        }
References Terraria.Cinematics.DD2Film.CreateCritters(), Terraria.Cinematics.DD2Film.CreateDryad(), Terraria.Cinematics.DD2Film.CreateOgre(), Terraria.Cinematics.DD2Film.CreatePortal(), Terraria.Cinematics.DD2Film.DryadAlertEmote(), Terraria.Cinematics.DD2Film.DryadAttack(), Terraria.Cinematics.DD2Film.DryadConfusedEmote(), Terraria.Cinematics.DD2Film.DryadInteract(), Terraria.Cinematics.DD2Film.DryadLookLeft(), Terraria.Cinematics.DD2Film.DryadLookRight(), Terraria.Cinematics.DD2Film.DryadStand(), Terraria.Cinematics.DD2Film.DryadWalk(), Terraria.Cinematics.FrameEvent(), Terraria.Cinematics.DD2Film.OgreLookLeft(), Terraria.Cinematics.DD2Film.OgreStand(), Terraria.Cinematics.DD2Film.RemoveEnemyDamage(), Terraria.Cinematics.DD2Film.SpawnGoblin(), Terraria.Cinematics.DD2Film.SpawnJavalinThrower(), and Terraria.Cinematics.DD2Film.SpawnWitherBeast().