Terraria Decompiled: Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OpenVirtualKeyboardWhenNeeded
OpenVirtualKeyboardWhenNeeded()
void Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OpenVirtualKeyboardWhenNeeded () inline private
Definition at line 205 of file UIWrappedSearchBar.cs.
        {
            UIVirtualKeyboard uivirtualKeyboard = new UIVirtualKeyboard(this._emptyText.Value, this._searchString, new UIVirtualKeyboard.KeyboardSubmitEvent(this.SubmitVirtualText), new Action(this.GoBackFromVirtualKeyboard), 0, true, this.MaxInputLength);
            if (this.CustomOpenVirtualKeyboard != null)
            {
                this.CustomOpenVirtualKeyboard(uivirtualKeyboard);
                return;
            }
            UserInterface.ActiveInstance.SetState(uivirtualKeyboard);
        }
References Terraria.GameContent.UI.Elements.UIWrappedSearchBar._emptyText, Terraria.UI.UserInterface.ActiveInstance, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.CustomOpenVirtualKeyboard, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.GoBackFromVirtualKeyboard(), Terraria.GameContent.UI.States.UIVirtualKeyboard.KeyboardSubmitEvent(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.MaxInputLength, Terraria.UI.UserInterface.SetState(), and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.UI.Elements.UIWrappedSearchBar.AddSearchBar().