Terraria Decompiled: Terraria.GameContent.UI.Elements.UIWrappedSearchBar.AddSearchBar
AddSearchBar()
void Terraria.GameContent.UI.Elements.UIWrappedSearchBar.AddSearchBar () inline private
Definition at line 125 of file UIWrappedSearchBar.cs.
        {
            string text = "Images/UI/Bestiary/Button_Search";
            if (this._theme == UIWrappedSearchBar.ColorTheme.Red)
            {
                text = "Images/UI/Bestiary/Button_Search_2";
            }
            UIImageButton uiimageButton = new UIImageButton(Main.Assets.Request<Texture2D>(text, 1), null)
            {
                VAlign = 0.5f
            };
            this._searchButton = uiimageButton;
            uiimageButton.OnLeftClick += this.Click_SearchArea;
            uiimageButton.SetHoverImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Button_Search_Border", 1), null);
            uiimageButton.SetVisibility(1f, 1f);
            base.Append(uiimageButton);
            UIPanel uipanel = new UIPanel
            {
                Width = new StyleDimension(-uiimageButton.Width.Pixels - 3f, 1f),
                Height = new StyleDimension(0f, 1f),
                VAlign = 0.5f,
                HAlign = 1f
            };
            this._searchBoxPanel = uipanel;
            uipanel.BackgroundColor = new Color(35, 40, 83);
            uipanel.BorderColor = new Color(35, 40, 83);
            if (this._theme == UIWrappedSearchBar.ColorTheme.Red)
            {
                uipanel.BackgroundColor = Utils.ShiftBlueToCyanTheme(uipanel.BackgroundColor);
                uipanel.BorderColor = Utils.ShiftBlueToCyanTheme(uipanel.BorderColor);
            }
            uipanel.SetPadding(0f);
            base.Append(uipanel);
            UISearchBar uisearchBar = new UISearchBar(this._emptyText, 0.8f)
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(0f, 1f),
                HAlign = 0f,
                VAlign = 0.5f,
                Left = new StyleDimension(0f, 0f),
                IgnoresMouseInteraction = true
            };
            this._searchBar = uisearchBar;
            uipanel.OnLeftClick += this.Click_SearchArea;
            uipanel.OnRightClick += this.SearchBox_OnRightClick;
            uisearchBar.OnContentsChanged += this.UpdateSearchContents;
            uipanel.Append(uisearchBar);
            uisearchBar.OnStartTakingInput += this.OnStartTakingInput;
            uisearchBar.OnEndTakingInput += this.OnEndTakingInput;
            uisearchBar.OnNeedingVirtualKeyboard += this.OpenVirtualKeyboardWhenNeeded;
            UIImageButton uiimageButton2 = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/SearchCancel", 1), null)
            {
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension(-2f, 0f)
            };
            uiimageButton2.OnMouseOver += this.searchCancelButton_OnMouseOver;
            uiimageButton2.OnLeftClick += this.searchCancelButton_OnClick;
            uipanel.Append(uiimageButton2);
        }
References Terraria.GameContent.UI.Elements.UIWrappedSearchBar._emptyText, Terraria.GameContent.UI.Elements.UIWrappedSearchBar._theme, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIPanel.BackgroundColor, Terraria.GameContent.UI.Elements.UIPanel.BorderColor, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.Click_SearchArea(), Microsoft.Xna.Framework.Graphics.Color, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OnEndTakingInput(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OnStartTakingInput(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.OpenVirtualKeyboardWhenNeeded(), Terraria.UI.StyleDimension.Pixels, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.SearchBox_OnRightClick(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.searchCancelButton_OnClick(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.searchCancelButton_OnMouseOver(), Terraria.GameContent.UI.Elements.UIImageButton.SetHoverImage(), Terraria.UI.UIElement.SetPadding(), Terraria.GameContent.UI.Elements.UIImageButton.SetVisibility(), Terraria.Utils.ShiftBlueToCyanTheme(), System.text, Terraria.GameContent.UI.Elements.UIWrappedSearchBar.UpdateSearchContents(), Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UIWrappedSearchBar.UIWrappedSearchBar().