Terraria Decompiled: Terraria.DataStructures.PlayerDrawHeadSet.BoringSetup
BoringSetup()
void Terraria.DataStructures.PlayerDrawHeadSet.BoringSetup (Player drawPlayer2, List< DrawData > drawData, List< int > dust, List< int > gore, float X, float Y, float Alpha, float Scale) inline
Definition at line 25 of file PlayerDrawHeadSet.cs.
        {
            this.DrawData = drawData;
            this.Dust = dust;
            this.Gore = gore;
            this.drawPlayer = drawPlayer2;
            this.Position = this.drawPlayer.position;
            this.cHead = 0;
            this.cFace = 0;
            this.cUnicornHorn = 0;
            this.cAngelHalo = 0;
            this.cBeard = 0;
            this.drawUnicornHorn = false;
            this.drawAngelHalo = false;
            this.skinVar = this.drawPlayer.skinVariant;
            this.hairShaderPacked = PlayerDrawHelper.PackShader((int)this.drawPlayer.hairDye, PlayerDrawHelper.ShaderConfiguration.HairShader);
            if (this.drawPlayer.head == 0 && this.drawPlayer.hairDye == 0)
            {
                this.hairShaderPacked = PlayerDrawHelper.PackShader(1, PlayerDrawHelper.ShaderConfiguration.HairShader);
            }
            this.skinDyePacked = this.drawPlayer.skinDyePacked;
            if (this.drawPlayer.face > 0 && this.drawPlayer.face < ArmorIDs.Face.Count)
            {
                Main.instance.LoadAccFace((int)this.drawPlayer.face);
            }
            this.cHead = this.drawPlayer.cHead;
            this.cFace = this.drawPlayer.cFace;
            this.cFaceHead = this.drawPlayer.cFaceHead;
            this.cFaceFlower = this.drawPlayer.cFaceFlower;
            this.cFaceMask = this.drawPlayer.cFaceMask;
            this.cUnicornHorn = this.drawPlayer.cUnicornHorn;
            this.cAngelHalo = this.drawPlayer.cAngelHalo;
            this.cBeard = this.drawPlayer.cBeard;
            this.drawUnicornHorn = this.drawPlayer.hasUnicornHorn;
            this.drawAngelHalo = this.drawPlayer.hasAngelHalo;
            Main.instance.LoadHair(this.drawPlayer.hair);
            this.scale = Scale;
            this.colorEyeWhites = Main.quickAlpha(Color.White, Alpha);
            this.colorEyes = Main.quickAlpha(this.drawPlayer.eyeColor, Alpha);
            this.colorHair = Main.quickAlpha(this.drawPlayer.GetHairColor(false), Alpha);
            this.colorHead = Main.quickAlpha(this.drawPlayer.skinColor, Alpha);
            this.colorArmorHead = Main.quickAlpha(Color.White, Alpha);
            if (this.drawPlayer.isDisplayDollOrInanimate)
            {
                this.colorDisplayDollSkin = Main.quickAlpha(PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, Alpha);
            }
            else
            {
                this.colorDisplayDollSkin = this.colorHead;
            }
            this.playerEffect = SpriteEffects.None;
            if (this.drawPlayer.direction < 0)
            {
                this.playerEffect = SpriteEffects.FlipHorizontally;
            }
            this.headVect = new Vector2((float)this.drawPlayer.legFrame.Width * 0.5f, (float)this.drawPlayer.legFrame.Height * 0.4f);
            this.bodyFrameMemory = this.drawPlayer.bodyFrame;
            this.bodyFrameMemory.Y = 0;
            this.Position = Main.screenPosition;
            this.Position.X = this.Position.X + X;
            this.Position.Y = this.Position.Y + Y;
            this.Position.X = this.Position.X - 6f;
            this.Position.Y = this.Position.Y - 4f;
            this.Position.Y = this.Position.Y - (float)this.drawPlayer.HeightMapOffset;
            if (this.drawPlayer.head > 0 && this.drawPlayer.head < ArmorIDs.Head.Count)
            {
                Main.instance.LoadArmorHead(this.drawPlayer.head);
                int num = ArmorIDs.Head.Sets.FrontToBackID[this.drawPlayer.head];
                if (num >= 0)
                {
                    Main.instance.LoadArmorHead(num);
                }
            }
            if (this.drawPlayer.face > 0 && this.drawPlayer.face < ArmorIDs.Face.Count)
            {
                Main.instance.LoadAccFace((int)this.drawPlayer.face);
            }
            if (this.drawPlayer.faceHead > 0 && this.drawPlayer.faceHead < ArmorIDs.Face.Count)
            {
                Main.instance.LoadAccFace((int)this.drawPlayer.faceHead);
            }
            if (this.drawPlayer.faceFlower > 0 && this.drawPlayer.faceFlower < ArmorIDs.Face.Count)
            {
                Main.instance.LoadAccFace((int)this.drawPlayer.faceFlower);
            }
            if (this.drawPlayer.faceMask > 0 && this.drawPlayer.faceMask < ArmorIDs.Face.Count)
            {
                Main.instance.LoadAccFace((int)this.drawPlayer.faceMask);
            }
            if (this.drawPlayer.beard > 0 && this.drawPlayer.beard < ArmorIDs.Beard.Count)
            {
                Main.instance.LoadAccBeard((int)this.drawPlayer.beard);
            }
            bool flag;
            this.drawPlayer.GetHairSettings(out this.fullHair, out this.hatHair, out this.hideHair, out flag, out this.helmetIsOverFullHair);
            this.hairOffset = this.drawPlayer.GetHairDrawOffset(this.drawPlayer.hair, this.hatHair);
            this.hairOffset.Y = this.hairOffset.Y * this.drawPlayer.Directions.Y;
            this.helmetOffset = this.drawPlayer.GetHelmetDrawOffset(true);
            this.helmetOffset.Y = this.helmetOffset.Y * this.drawPlayer.Directions.Y;
            this.helmetIsTall = this.drawPlayer.head == 14 || this.drawPlayer.head == 56 || this.drawPlayer.head == 158;
            this.helmetIsNormal = !this.helmetIsTall && !this.helmetIsOverFullHair && this.drawPlayer.head > 0 && this.drawPlayer.head < ArmorIDs.Head.Count && this.drawPlayer.head != 28;
        }
References Microsoft.Xna.Framework.Graphics.Alpha, Terraria.Player.beard, Terraria.Player.bodyFrame, Terraria.Player.cAngelHalo, Terraria.Player.cBeard, Terraria.Player.cFace, Terraria.Player.cFaceFlower, Terraria.Player.cFaceHead, Terraria.Player.cFaceMask, Terraria.Player.cHead, Terraria.DataStructures.PlayerDrawHeadSet.colorHead, Terraria.ID.ArmorIDs.Head.Count, Terraria.ID.ArmorIDs.Face.Count, Terraria.ID.ArmorIDs.Beard.Count, Terraria.Player.cUnicornHorn, Terraria.Entity.direction, Terraria.Player.Directions, Terraria.DataStructures.PlayerDrawHelper.DISPLAY_DOLL_DEFAULT_SKIN_COLOR, Terraria.DataStructures.PlayerDrawHeadSet.drawPlayer, Terraria.Player.eyeColor, Terraria.Player.face, Terraria.Player.faceFlower, Terraria.Player.faceHead, Terraria.Player.faceMask, Terraria.ID.ArmorIDs.Head.Sets.FrontToBackID, Terraria.DataStructures.PlayerDrawHeadSet.fullHair, Terraria.Player.GetHairColor(), Terraria.Player.GetHairDrawOffset(), Terraria.Player.GetHairSettings(), Terraria.Player.GetHelmetDrawOffset(), Terraria.Player.hair, Terraria.Player.hairDye, Terraria.Player.hasAngelHalo, Terraria.Player.hasUnicornHorn, Terraria.DataStructures.PlayerDrawHeadSet.hatHair, Terraria.Player.head, Terraria.Player.HeightMapOffset, Terraria.DataStructures.PlayerDrawHeadSet.helmetIsOverFullHair, Terraria.DataStructures.PlayerDrawHeadSet.hideHair, Terraria.Main.instance, Terraria.Player.isDisplayDollOrInanimate, Terraria.Player.legFrame, Terraria.Main.LoadAccBeard(), Terraria.Main.LoadAccFace(), Terraria.Main.LoadArmorHead(), Terraria.Main.LoadHair(), Terraria.DataStructures.PlayerDrawHelper.PackShader(), Terraria.Entity.position, Terraria.Main.quickAlpha(), Terraria.Main.screenPosition, Terraria.Player.skinColor, Terraria.Player.skinDyePacked, Terraria.Player.skinVariant, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Rectangle.Width, System.X, Microsoft.Xna.Framework.Vector2.Y, and System.Y.
Referenced by Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerHead(), and Terraria.GameContent.PlayerHeadDrawRenderTargetContent.DrawTheContent().