Terraria Decompiled: NVorbis.TagData.TagData
TagData() [1/2]
NVorbis.TagData.TagData (string vendor, string[] comments) inline
Definition at line 14 of file TagData.cs.
        {
            this.EncoderVendor = vendor;
            Dictionary<string, IList<string>> dictionary = new Dictionary<string, IList<string>>();
            for (int i = 0; i < comments.Length; i++)
            {
                string[] array = comments[i].Split(new char[] { '=' });
                if (array.Length == 1)
                {
                    array = new string[]
                    {
                        array[0],
                        string.Empty
                    };
                }
                int num = array[0].IndexOf('[');
                if (num > -1)
                {
                    array[1] = array[0].Substring(num + 1, array[0].Length - num - 2).ToUpper(CultureInfo.CurrentCulture) + ": " + array[1];
                    array[0] = array[0].Substring(0, num);
                }
                IList<string> list;
                if (dictionary.TryGetValue(array[0].ToUpperInvariant(), ref list))
                {
                    list.Add(array[1]);
                }
                else
                {
                    Dictionary<string, IList<string>> dictionary2 = dictionary;
                    string text = array[0].ToUpperInvariant();
                    List<string> list2 = new List<string>();
                    list2.Add(array[1]);
                    dictionary2.Add(text, list2);
                }
            }
            this._tags = dictionary;
        }
References System.Collections.Generic.ICollection< T >.Add(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.array, System.Globalization.CultureInfo.CurrentCulture, System.dictionary, System.list, and System.text.