Terraria Decompiled: System.Security.Cryptography.RIPEMD160Managed._HashData
_HashData()
unsafe void System.Security.Cryptography.RIPEMD160Managed._HashData (byte[] partIn, int ibStart, int cbSize) inline private
Definition at line 58 of file RIPEMD160Managed.cs.
        {
            int i = cbSize;
            int num = ibStart;
            int num2 = (int)(this._count & 63L);
            this._count += (long)i;
            uint[] array;
            uint* ptr;
            if ((array = this._stateMD160) == null || array.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &array[0];
            }
            byte[] array2;
            byte* ptr2;
            if ((array2 = this._buffer) == null || array2.Length == 0)
            {
                ptr2 = null;
            }
            else
            {
                ptr2 = &array2[0];
            }
            uint[] array3;
            uint* ptr3;
            if ((array3 = this._blockDWords) == null || array3.Length == 0)
            {
                ptr3 = null;
            }
            else
            {
                ptr3 = &array3[0];
            }
            if (num2 > 0 && num2 + i >= 64)
            {
                Buffer.InternalBlockCopy(partIn, num, this._buffer, num2, 64 - num2);
                num += 64 - num2;
                i -= 64 - num2;
                RIPEMD160Managed.MDTransform(ptr3, ptr, ptr2);
                num2 = 0;
            }
            while (i >= 64)
            {
                Buffer.InternalBlockCopy(partIn, num, this._buffer, 0, 64);
                num += 64;
                i -= 64;
                RIPEMD160Managed.MDTransform(ptr3, ptr, ptr2);
            }
            if (i > 0)
            {
                Buffer.InternalBlockCopy(partIn, num, this._buffer, num2, i);
            }
            array3 = null;
            array2 = null;
            array = null;
        }
References System.Security.Cryptography.RIPEMD160Managed._blockDWords, System.Security.Cryptography.RIPEMD160Managed._buffer, System.Security.Cryptography.RIPEMD160Managed._count, System.Security.Cryptography.RIPEMD160Managed._stateMD160, System.array, int, System.Buffer.InternalBlockCopy(), System.L, long, and System.Security.Cryptography.RIPEMD160Managed.MDTransform().
Referenced by System.Security.Cryptography.RIPEMD160Managed._EndHash(), and System.Security.Cryptography.RIPEMD160Managed.HashCore().