Terraria Decompiled: System.Security.Cryptography.RIPEMD160Managed._EndHash
_EndHash()
byte[] System.Security.Cryptography.RIPEMD160Managed._EndHash () inline private
Definition at line 120 of file RIPEMD160Managed.cs.
        {
            byte[] array = new byte[20];
            int num = 64 - (int)(this._count & 63L);
            if (num <= 8)
            {
                num += 64;
            }
            byte[] array2 = new byte[num];
            array2[0] = 128;
            long num2 = this._count * 8L;
            array2[num - 1] = (byte)((num2 >> 56) & 255L);
            array2[num - 2] = (byte)((num2 >> 48) & 255L);
            array2[num - 3] = (byte)((num2 >> 40) & 255L);
            array2[num - 4] = (byte)((num2 >> 32) & 255L);
            array2[num - 5] = (byte)((num2 >> 24) & 255L);
            array2[num - 6] = (byte)((num2 >> 16) & 255L);
            array2[num - 7] = (byte)((num2 >> 8) & 255L);
            array2[num - 8] = (byte)(num2 & 255L);
            this._HashData(array2, 0, array2.Length);
            Utils.DWORDToLittleEndian(array, this._stateMD160, 5);
            this.HashValue = array;
            return array;
        }
References System.Security.Cryptography.RIPEMD160Managed._count, System.Security.Cryptography.RIPEMD160Managed._HashData(), System.Security.Cryptography.RIPEMD160Managed._stateMD160, System.array, System.Security.Cryptography.Utils.DWORDToLittleEndian(), int, and System.L.
Referenced by System.Security.Cryptography.RIPEMD160Managed.HashFinal().