Terraria Decompiled: System.TypedReference.MakeTypedReference
MakeTypedReference()
static unsafe TypedReference System.TypedReference.MakeTypedReference (object target, FieldInfo[] flds) inline static
Definition at line 19 of file TypedReference.cs.
        {
            if (target == null)
            {
                throw new ArgumentNullException("target");
            }
            if (flds == null)
            {
                throw new ArgumentNullException("flds");
            }
            if (flds.Length == 0)
            {
                throw new ArgumentException(Environment.GetResourceString("Array must not be of length zero."), "flds");
            }
            IntPtr[] array = new IntPtr[flds.Length];
            RuntimeType runtimeType = (RuntimeType)target.GetType();
            for (int i = 0; i < flds.Length; i++)
            {
                RuntimeFieldInfo runtimeFieldInfo = flds[i] as RuntimeFieldInfo;
                if (runtimeFieldInfo == null)
                {
                    throw new ArgumentException(Environment.GetResourceString("FieldInfo must be a runtime FieldInfo object."));
                }
                if (runtimeFieldInfo.IsStatic)
                {
                    throw new ArgumentException(Environment.GetResourceString("Field in TypedReferences cannot be static or init only."));
                }
                if (runtimeType != runtimeFieldInfo.GetDeclaringTypeInternal() && !runtimeType.IsSubclassOf(runtimeFieldInfo.GetDeclaringTypeInternal()))
                {
                    throw new MissingMemberException(Environment.GetResourceString("FieldInfo does not match the target Type."));
                }
                RuntimeType runtimeType2 = (RuntimeType)runtimeFieldInfo.FieldType;
                if (runtimeType2.IsPrimitive)
                {
                    throw new ArgumentException(Environment.GetResourceString("TypedReferences cannot be redefined as primitives."));
                }
                if (i < flds.Length - 1 && !runtimeType2.IsValueType)
                {
                    throw new MissingMemberException(Environment.GetResourceString("TypedReference can only be made on nested value Types."));
                }
                array[i] = runtimeFieldInfo.FieldHandle.Value;
                runtimeType = runtimeType2;
            }
            TypedReference typedReference = default(TypedReference);
            TypedReference.InternalMakeTypedReference((void*)(&typedReference), target, array, runtimeType);
            return typedReference;
        }
References System.array, System.Reflection.RuntimeFieldInfo.FieldHandle, System.Reflection.RuntimeFieldInfo.FieldType, System.Reflection.RuntimeFieldInfo.GetDeclaringTypeInternal(), System.Environment.GetResourceString(), System.TypedReference.InternalMakeTypedReference(), System.Reflection.FieldInfo.IsStatic, System.RuntimeType.IsSubclassOf(), and System.RuntimeFieldHandle.Value.
Referenced by System.Runtime.Serialization.ObjectManager.DoValueTypeFixup().