Terraria Decompiled: Newtonsoft.Json.Linq.JToken.ToBigIntegerNullable
ToBigIntegerNullable()
static ? BigInteger Newtonsoft.Json.Linq.JToken.ToBigIntegerNullable (JToken value) inline static private
Definition at line 1142 of file JToken.cs.
        {
            JValue jvalue = JToken.EnsureValue(value);
            if (jvalue == null || !JToken.ValidateToken(jvalue, JToken.BigIntegerTypes, true))
            {
                throw new ArgumentException("Can not convert {0} to BigInteger.".FormatWith(CultureInfo.InvariantCulture, JToken.GetType(value)));
            }
            if (jvalue.Value == null)
            {
                return default(BigInteger?);
            }
            return new BigInteger?(ConvertUtils.ToBigInteger(jvalue.Value));
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.Linq.JToken.BigIntegerTypes, Newtonsoft.Json.Linq.JToken.EnsureValue(), Newtonsoft.Json.Linq.JToken.GetType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ConvertUtils.ToBigInteger(), Newtonsoft.Json.Linq.JToken.ValidateToken(), System.value, and Newtonsoft.Json.Linq.JValue.Value.
Referenced by Newtonsoft.Json.Linq.JToken.ToObject().