Terraria Decompiled: Newtonsoft.Json.Linq.JToken.operator char
operator char()
static Newtonsoft.Json.Linq.JToken.operator char (JToken value) inline explicit static
Definition at line 625 of file JToken.cs.
        {
            JValue jvalue = JToken.EnsureValue(value);
            if (jvalue == null || !JToken.ValidateToken(jvalue, JToken.CharTypes, false))
            {
                throw new ArgumentException("Can not convert {0} to Char.".FormatWith(CultureInfo.InvariantCulture, JToken.GetType(value)));
            }
            if (jvalue.Value is BigInteger)
            {
                return (char)(ushort)((BigInteger)jvalue.Value);
            }
            return Convert.ToChar(jvalue.Value, CultureInfo.InvariantCulture);
        }
References Newtonsoft.Json.Utilities.BigInteger, Newtonsoft.Json.Linq.JToken.CharTypes, Newtonsoft.Json.Linq.JToken.EnsureValue(), Newtonsoft.Json.Linq.JToken.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToChar(), Newtonsoft.Json.Linq.JToken.ValidateToken(), System.value, and Newtonsoft.Json.Linq.JValue.Value.