Terraria Decompiled: Newtonsoft.Json.Linq.JToken.operator Guid?
operator Guid?()
static Newtonsoft.Json.Linq.JToken.operator Guid? (JToken value) inline explicit static
Definition at line 1050 of file JToken.cs.
        {
            if (value == null)
            {
                return default(Guid?);
            }
            JValue jvalue = JToken.EnsureValue(value);
            if (jvalue == null || !JToken.ValidateToken(jvalue, JToken.GuidTypes, true))
            {
                throw new ArgumentException("Can not convert {0} to Guid.".FormatWith(CultureInfo.InvariantCulture, JToken.GetType(value)));
            }
            if (jvalue.Value == null)
            {
                return default(Guid?);
            }
            byte[] array = jvalue.Value as byte[];
            if (array != null)
            {
                return new Guid?(new Guid(array));
            }
            return new Guid?((jvalue.Value is Guid) ? ((Guid)jvalue.Value) : new Guid(Convert.ToString(jvalue.Value, CultureInfo.InvariantCulture)));
        }
References System.array, Newtonsoft.Json.Linq.JToken.EnsureValue(), Newtonsoft.Json.Linq.JToken.GetType(), Newtonsoft.Json.Linq.Guid, Newtonsoft.Json.Linq.JToken.GuidTypes, System.Globalization.CultureInfo.InvariantCulture, System.Convert.ToString(), Newtonsoft.Json.Linq.JToken.ValidateToken(), System.value, and Newtonsoft.Json.Linq.JValue.Value.