Terraria Decompiled: Newtonsoft.Json.Linq.JToken.FromObjectInternal
FromObjectInternal()
static JToken Newtonsoft.Json.Linq.JToken.FromObjectInternal (object o, JsonSerializer jsonSerializer) inline static package
Definition at line 1407 of file JToken.cs.
        {
            ValidationUtils.ArgumentNotNull(o, "o");
            ValidationUtils.ArgumentNotNull(jsonSerializer, "jsonSerializer");
            JToken token;
            using (JTokenWriter jtokenWriter = new JTokenWriter())
            {
                jsonSerializer.Serialize(jtokenWriter, o);
                token = jtokenWriter.Token;
            }
            return token;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.JsonSerializer.Serialize(), and Newtonsoft.Json.Linq.JTokenWriter.Token.
Referenced by Newtonsoft.Json.Linq.JToken.FromObject(), Newtonsoft.Json.Linq.JArray.FromObject(), Newtonsoft.Json.Linq.JObject.FromObject(), and Newtonsoft.Json.Linq.JToken.FromObject().