Terraria Decompiled: Newtonsoft.Json.Linq.JToken.ToObject
ToObject() [1/2]
object Newtonsoft.Json.Linq.JToken.ToObject (Type objectType) inline
Definition at line 1439 of file JToken.cs.
        {
            if (JsonConvert.DefaultSettings == null)
            {
                bool flag;
                PrimitiveTypeCode typeCode = ConvertUtils.GetTypeCode(objectType, out flag);
                if (flag)
                {
                    if (this.Type == JTokenType.String)
                    {
                        try
{
                            return this.ToObject(objectType, JsonSerializer.CreateDefault());
                        }
                        catch (Exception ex)
{
                            Type type = (objectType.IsEnum() ? objectType : Nullable.GetUnderlyingType(objectType));
                            throw new ArgumentException("Could not convert '{0}' to {1}.".FormatWith(CultureInfo.InvariantCulture, (string)this, type.Name), ex);
                        }
                    }
                    if (this.Type == JTokenType.Integer)
                    {
                        return Enum.ToObject(objectType.IsEnum() ? objectType : Nullable.GetUnderlyingType(objectType), ((JValue)this).Value);
                    }
                }
                switch (typeCode)
                {
                case PrimitiveTypeCode.Char:
                    return (char)this;
                case PrimitiveTypeCode.CharNullable:
                    return (char?)this;
                case PrimitiveTypeCode.Boolean:
                    return (bool)this;
                case PrimitiveTypeCode.BooleanNullable:
                    return (bool?)this;
                case PrimitiveTypeCode.SByte:
                    return (sbyte)this;
                case PrimitiveTypeCode.SByteNullable:
                    return (sbyte?)this;
                case PrimitiveTypeCode.Int16:
                    return (short)this;
                case PrimitiveTypeCode.Int16Nullable:
                    return (short?)this;
                case PrimitiveTypeCode.UInt16:
                    return (ushort)this;
                case PrimitiveTypeCode.UInt16Nullable:
                    return (ushort?)this;
                case PrimitiveTypeCode.Int32:
                    return (int)this;
                case PrimitiveTypeCode.Int32Nullable:
                    return (int?)this;
                case PrimitiveTypeCode.Byte:
                    return (byte)this;
                case PrimitiveTypeCode.ByteNullable:
                    return (byte?)this;
                case PrimitiveTypeCode.UInt32:
                    return (uint)this;
                case PrimitiveTypeCode.UInt32Nullable:
                    return (uint?)this;
                case PrimitiveTypeCode.Int64:
                    return (long)this;
                case PrimitiveTypeCode.Int64Nullable:
                    return (long?)this;
                case PrimitiveTypeCode.UInt64:
                    return (ulong)this;
                case PrimitiveTypeCode.UInt64Nullable:
                    return (ulong?)this;
                case PrimitiveTypeCode.Single:
                    return (float)this;
                case PrimitiveTypeCode.SingleNullable:
                    return (float?)this;
                case PrimitiveTypeCode.Double:
                    return (double)this;
                case PrimitiveTypeCode.DoubleNullable:
                    return (double?)this;
                case PrimitiveTypeCode.DateTime:
                    return (DateTime)this;
                case PrimitiveTypeCode.DateTimeNullable:
                    return (DateTime?)this;
                case PrimitiveTypeCode.DateTimeOffset:
                    return (DateTimeOffset)this;
                case PrimitiveTypeCode.DateTimeOffsetNullable:
                    return (DateTimeOffset?)this;
                case PrimitiveTypeCode.Decimal:
                    return (decimal)this;
                case PrimitiveTypeCode.DecimalNullable:
                    return (decimal?)this;
                case PrimitiveTypeCode.Guid:
                    return (Guid)this;
                case PrimitiveTypeCode.GuidNullable:
                    return (Guid?)this;
                case PrimitiveTypeCode.TimeSpan:
                    return (TimeSpan)this;
                case PrimitiveTypeCode.TimeSpanNullable:
                    return (TimeSpan?)this;
                case PrimitiveTypeCode.BigInteger:
                    return JToken.ToBigInteger(this);
                case PrimitiveTypeCode.BigIntegerNullable:
                    return JToken.ToBigIntegerNullable(this);
                case PrimitiveTypeCode.Uri:
                    return (Uri)this;
                case PrimitiveTypeCode.String:
                    return (string)this;
                }
            }
            return this.ToObject(objectType, JsonSerializer.CreateDefault());
        }
References Newtonsoft.Json.JsonSerializer.CreateDefault(), Newtonsoft.Json.JsonConvert.DefaultSettings, Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, System.Type.IsEnum, System.Reflection.MemberInfo.Name, Newtonsoft.Json.Linq.JToken.ToBigInteger(), Newtonsoft.Json.Linq.JToken.ToBigIntegerNullable(), System.Enum.ToObject(), and Newtonsoft.Json.Linq.JToken.ToObject().
Referenced by Terraria.WorldBuilding.WorldGenConfiguration.CreateBiome< T >(), Terraria.IO.ResourcePackList.CreatePackEntryListFromJson(), Terraria.IO.GameConfiguration.Get< T >(), Terraria.IO.ResourcePack.LoadManifest(), Terraria.Social.Base.AWorkshopEntry.ReadHeader(), Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson(), Newtonsoft.Json.Linq.JToken.ToObject(), Newtonsoft.Json.Linq.JToken.ToObject< T >(), Newtonsoft.Json.Linq.JToken.ToObject< T >(), and Terraria.Social.Base.AWorkshopEntry.TryReadingManifest().