Terraria Decompiled: Newtonsoft.Json.Linq.JToken.operator DateTimeOffset
operator DateTimeOffset()
static Newtonsoft.Json.Linq.JToken.operator DateTimeOffset (JToken value) inline explicit static
Definition at line 400 of file JToken.cs.
        {
            JValue jvalue = JToken.EnsureValue(value);
            if (jvalue == null || !JToken.ValidateToken(jvalue, JToken.DateTimeTypes, false))
            {
                throw new ArgumentException("Can not convert {0} to DateTimeOffset.".FormatWith(CultureInfo.InvariantCulture, JToken.GetType(value)));
            }
            if (jvalue.Value is DateTimeOffset)
            {
                return (DateTimeOffset)jvalue.Value;
            }
            string text = jvalue.Value as string;
            if (text != null)
            {
                return DateTimeOffset.Parse(text, CultureInfo.InvariantCulture);
            }
            return new DateTimeOffset(Convert.ToDateTime(jvalue.Value, CultureInfo.InvariantCulture));
        }
References Newtonsoft.Json.DateTimeOffset, Newtonsoft.Json.Linq.JToken.DateTimeTypes, Newtonsoft.Json.Linq.JToken.EnsureValue(), Newtonsoft.Json.Linq.JToken.GetType(), System.Globalization.CultureInfo.InvariantCulture, System.DateTimeOffset.Parse(), System.text, System.Convert.ToDateTime(), Newtonsoft.Json.Linq.JToken.ValidateToken(), System.value, and Newtonsoft.Json.Linq.JValue.Value.