Terraria Decompiled: Newtonsoft.Json.Linq.JToken.EnsureValue
EnsureValue()
static JValue Newtonsoft.Json.Linq.JToken.EnsureValue (JToken value) inline static private
Definition at line 354 of file JToken.cs.
        {
            if (value == null)
            {
                throw new ArgumentNullException("value");
            }
            if (value is JProperty)
            {
                value = ((JProperty)value).Value;
            }
            return value as JValue;
        }
References System.value.
Referenced by Newtonsoft.Json.Linq.JToken.operator bool(), Newtonsoft.Json.Linq.JToken.operator bool?(), Newtonsoft.Json.Linq.JToken.operator byte(), Newtonsoft.Json.Linq.JToken.operator byte?(), Newtonsoft.Json.Linq.JToken.operator byte[](), Newtonsoft.Json.Linq.JToken.operator char(), Newtonsoft.Json.Linq.JToken.operator char?(), Newtonsoft.Json.Linq.JToken.operator DateTime(), Newtonsoft.Json.Linq.JToken.operator DateTime?(), Newtonsoft.Json.Linq.JToken.operator DateTimeOffset(), Newtonsoft.Json.Linq.JToken.operator DateTimeOffset?(), Newtonsoft.Json.Linq.JToken.operator decimal(), Newtonsoft.Json.Linq.JToken.operator decimal?(), Newtonsoft.Json.Linq.JToken.operator double(), Newtonsoft.Json.Linq.JToken.operator double?(), Newtonsoft.Json.Linq.JToken.operator float(), Newtonsoft.Json.Linq.JToken.operator float?(), Newtonsoft.Json.Linq.JToken.operator Guid(), Newtonsoft.Json.Linq.JToken.operator Guid?(), Newtonsoft.Json.Linq.JToken.operator int(), Newtonsoft.Json.Linq.JToken.operator int?(), Newtonsoft.Json.Linq.JToken.operator long(), Newtonsoft.Json.Linq.JToken.operator long?(), Newtonsoft.Json.Linq.JToken.operator sbyte(), Newtonsoft.Json.Linq.JToken.operator sbyte?(), Newtonsoft.Json.Linq.JToken.operator short(), Newtonsoft.Json.Linq.JToken.operator short?(), Newtonsoft.Json.Linq.JToken.operator string(), Newtonsoft.Json.Linq.JToken.operator TimeSpan(), Newtonsoft.Json.Linq.JToken.operator TimeSpan?(), Newtonsoft.Json.Linq.JToken.operator uint(), Newtonsoft.Json.Linq.JToken.operator uint?(), Newtonsoft.Json.Linq.JToken.operator ulong(), Newtonsoft.Json.Linq.JToken.operator ulong?(), Newtonsoft.Json.Linq.JToken.operator Uri(), Newtonsoft.Json.Linq.JToken.operator ushort(), Newtonsoft.Json.Linq.JToken.operator ushort?(), Newtonsoft.Json.Linq.JToken.ToBigInteger(), and Newtonsoft.Json.Linq.JToken.ToBigIntegerNullable().