Terraria Decompiled: Newtonsoft.Json.Linq.JToken.operator TimeSpan?
operator TimeSpan?()
static Newtonsoft.Json.Linq.JToken.operator TimeSpan? (JToken value) inline explicit static
Definition at line 1089 of file JToken.cs.
        {
            if (value == null)
            {
                return default(TimeSpan?);
            }
            JValue jvalue = JToken.EnsureValue(value);
            if (jvalue == null || !JToken.ValidateToken(jvalue, JToken.TimeSpanTypes, true))
            {
                throw new ArgumentException("Can not convert {0} to TimeSpan.".FormatWith(CultureInfo.InvariantCulture, JToken.GetType(value)));
            }
            if (jvalue.Value == null)
            {
                return default(TimeSpan?);
            }
            return new TimeSpan?((jvalue.Value is TimeSpan) ? ((TimeSpan)jvalue.Value) : ConvertUtils.ParseTimeSpan(Convert.ToString(jvalue.Value, CultureInfo.InvariantCulture)));
        }
References Newtonsoft.Json.Linq.JToken.EnsureValue(), Newtonsoft.Json.Linq.JToken.GetType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ConvertUtils.ParseTimeSpan(), Newtonsoft.Json.Linq.TimeSpan, Newtonsoft.Json.Linq.JToken.TimeSpanTypes, System.Convert.ToString(), Newtonsoft.Json.Linq.JToken.ValidateToken(), System.value, and Newtonsoft.Json.Linq.JValue.Value.