Terraria Decompiled: Newtonsoft.Json.Linq.JToken.ReadFrom
ReadFrom() [2/2]
static JToken Newtonsoft.Json.Linq.JToken.ReadFrom (JsonReader reader, JsonLoadSettings settings) inline static
Definition at line 1572 of file JToken.cs.
        {
            ValidationUtils.ArgumentNotNull(reader, "reader");
            if (reader.TokenType == JsonToken.None && !((settings != null && settings.CommentHandling == CommentHandling.Ignore) ? reader.ReadAndMoveToContent() : reader.Read()))
            {
                throw JsonReaderException.Create(reader, "Error reading JToken from JsonReader.");
            }
            IJsonLineInfo jsonLineInfo = reader as IJsonLineInfo;
            switch (reader.TokenType)
            {
            case JsonToken.StartObject:
                return JObject.Load(reader, settings);
            case JsonToken.StartArray:
                return JArray.Load(reader, settings);
            case JsonToken.StartConstructor:
                return JConstructor.Load(reader, settings);
            case JsonToken.PropertyName:
                return JProperty.Load(reader, settings);
            case JsonToken.Comment:
            {
                JValue jvalue = JValue.CreateComment(reader.Value.ToString());
                jvalue.SetLineInfo(jsonLineInfo, settings);
                return jvalue;
            }
            case JsonToken.Integer:
            case JsonToken.Float:
            case JsonToken.String:
            case JsonToken.Boolean:
            case JsonToken.Date:
            case JsonToken.Bytes:
            {
                JValue jvalue2 = new JValue(reader.Value);
                jvalue2.SetLineInfo(jsonLineInfo, settings);
                return jvalue2;
            }
            case JsonToken.Null:
            {
                JValue jvalue3 = JValue.CreateNull();
                jvalue3.SetLineInfo(jsonLineInfo, settings);
                return jvalue3;
            }
            case JsonToken.Undefined:
            {
                JValue jvalue4 = JValue.CreateUndefined();
                jvalue4.SetLineInfo(jsonLineInfo, settings);
                return jvalue4;
            }
            }
            throw JsonReaderException.Create(reader, "Error reading JToken from JsonReader. Unexpected token: {0}".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Linq.JsonLoadSettings.CommentHandling, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.Linq.JValue.CreateComment(), Newtonsoft.Json.Linq.JValue.CreateNull(), Newtonsoft.Json.Linq.JValue.CreateUndefined(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JArray.Load(), Newtonsoft.Json.Linq.JConstructor.Load(), Newtonsoft.Json.Linq.JObject.Load(), Newtonsoft.Json.Linq.JProperty.Load(), Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.JsonReader.ReadAndMoveToContent(), Newtonsoft.Json.Linq.JToken.SetLineInfo(), Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.