Terraria Decompiled: Terraria.GameContent.Biomes.DitherSnakePass.ApplyPass
ApplyPass()
override void Terraria.GameContent.Biomes.DitherSnakePass.ApplyPass (GenerationProgress progress, GameConfiguration configuration) inline protected
Definition at line 23 of file DitherSnakePass.cs.
        {
            progress.Message = Language.GetTextValue("WorldGeneration.DualDungeonsDitherSnake");
            GenVars.CurrentDungeon = 0;
            GenVars.CurrentDungeonGenVars.dungeonDitherSnake = this.CalculateDungeonDitherSnake(progress, 0.0, 0.02500000037252903);
            this.GenerateDungeonDitherSnake(progress, 0.02500000037252903, 0.5);
            GenVars.CurrentDungeon = 1;
            GenVars.CurrentDungeonGenVars.dungeonDitherSnake = this.CalculateDungeonDitherSnake(progress, 0.5, 0.5249999761581421);
            this.GenerateDungeonDitherSnake(progress, 0.5249999761581421, 1.0);
        }
References Terraria.GameContent.Biomes.DitherSnakePass.CalculateDungeonDitherSnake(), Terraria.GameContent.Biomes.DitherSnakePass.GenerateDungeonDitherSnake(), and Terraria.Localization.Language.GetTextValue().