Terraria Decompiled: System.Runtime.Serialization.SerializationFieldInfo.InternalSetValue
InternalSetValue()
void System.Runtime.Serialization.SerializationFieldInfo.InternalSetValue (object obj, object value, BindingFlags invokeAttr, Binder binder, CultureInfo culture) inline package
Definition at line 125 of file SerializationFieldInfo.cs.
        {
            RtFieldInfo field = this.m_field;
            if (field != null)
            {
                field.CheckConsistency(obj);
                field.UnsafeSetValue(obj, value, invokeAttr, binder, culture);
                return;
            }
            this.m_field.SetValue(obj, value, invokeAttr, binder, culture);
        }
References System.Reflection.RtFieldInfo.CheckConsistency(), System.culture, System.Runtime.Serialization.SerializationFieldInfo.m_field, System.obj, System.Reflection.RuntimeFieldInfo.SetValue(), System.Reflection.RtFieldInfo.UnsafeSetValue(), and System.value.
Referenced by System.Runtime.Serialization.FormatterServices.SerializationSetValue().