Terraria Decompiled: Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy
SpawnEnemy()
void Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy () inline
Definition at line 437 of file CoinLossRevengeSystem.cs.
            {
                int num = NPC.NewNPC(new EntitySource_RevengeSystem(), (int)this._location.X, (int)this._location.Y, this._npcNetID, 0, 0f, 0f, 0f, 0f, 255);
                NPC npc = Main.npc[num];
                npc.Center = this._location;
                if (this._npcNetID < 0)
                {
                    npc.SetDefaults(this._npcNetID, default(NPCSpawnParams));
                }
                int num2;
                if (NPCID.Sets.SpecialSpawningRules.TryGetValue(this._npcNetID, out num2) && num2 == 0)
                {
                    Point point = npc.position.ToTileCoordinates();
                    npc.ai[0] = (float)point.X;
                    npc.ai[1] = (float)point.Y;
                    npc.netUpdate = true;
                }
                npc.timeLeft += 3600;
                npc.extraValue = this._coinsValue;
                npc.value = this._baseValue;
                npc.SpawnedFromStatue = this._spawnedFromStatue;
                float num3 = Math.Max(0.5f, this._npcHPPercent);
                npc.life = (int)((float)npc.lifeMax * num3);
                if (num < Main.maxNPCs)
                {
                    if (Main.netMode == 0)
                    {
                        npc.moneyPing(this._location);
                    }
                    else
                    {
                        NetMessage.SendData(23, -1, -1, null, num, 0f, 0f, 0f, 0, 0, 0);
                        NetMessage.SendData(92, -1, -1, null, num, (float)this._coinsValue, this._location.X, this._location.Y, 0, 0, 0);
                    }
                }
                if (CoinLossRevengeSystem.DisplayCaching)
                {
                    Main.NewText("Spawned " + npc.GivenOrTypeName, byte.MaxValue, byte.MaxValue, byte.MaxValue);
                }
            }
References Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker._baseValue, Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker._coinsValue, Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker._location, Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker._npcHPPercent, Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker._npcNetID, Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker._spawnedFromStatue, Terraria.NPC.ai, Terraria.GameContent.CoinLossRevengeSystem.DisplayCaching, Terraria.NPC.GivenOrTypeName, int, System.Math.Max(), Terraria.Main.maxNPCs, Terraria.NPC.moneyPing(), Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.NewText(), Terraria.Main.npc, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.NPC.SetDefaults(), Terraria.ID.NPCID.Sets.SpecialSpawningRules, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.