Terraria Decompiled: Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.UseMouseOver
UseMouseOver()
void Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.UseMouseOver (SpriteBatch spriteBatch, ref string mouseTextString, float drawScale = 1f) inline
Definition at line 554 of file CoinLossRevengeSystem.cs.
            {
                mouseTextString = "";
                Vector2 vector = Main.MouseScreen / drawScale + new Vector2(-28f) + new Vector2(4f, 0f);
                ItemSlot.DrawMoney(spriteBatch, "", vector.X, vector.Y, Utils.CoinsSplit((long)this._coinsValue), true, false);
            }
References Terraria.Utils.CoinsSplit(), Terraria.UI.ItemSlot.DrawMoney(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawMap().