Terraria Decompiled: System.Reflection.MethodBase.GetParametersCount
GetParametersCount()
virtual int System.Reflection.MethodBase.GetParametersCount () inline package virtual
Reimplemented in System.Reflection.Emit.ConstructorBuilder, System.Reflection.Emit.ConstructorOnTypeBuilderInst, System.Reflection.Emit.DynamicMethod, System.Reflection.Emit.MethodBuilder, System.Reflection.Emit.MethodOnTypeBuilderInst, System.Reflection.MonoArrayMethod, System.Reflection.RuntimeConstructorInfo, and System.Reflection.RuntimeMethodInfo.
Definition at line 324 of file MethodBase.cs.
        {
            return this.GetParametersInternal().Length;
        }
References System.Reflection.MethodBase.GetParametersInternal().
Referenced by System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ILGenerator.Emit(), System.Reflection.Emit.ConstructorOnTypeBuilderInst.GetParametersCount(), System.Reflection.Emit.MethodOnTypeBuilderInst.GetParametersCount(), System.Reflection.Emit.CustomAttributeBuilder.Initialize(), and System.Reflection.Emit.AssemblyBuilder.Save().