Terraria Decompiled: System.Reflection.MethodBase.GetParametersInternal
GetParametersInternal()
virtual ParameterInfo[] System.Reflection.MethodBase.GetParametersInternal () inline package virtual
Reimplemented in System.Reflection.Emit.ConstructorBuilder, System.Reflection.Emit.ConstructorOnTypeBuilderInst, System.Reflection.Emit.DynamicMethod, System.Reflection.Emit.MethodBuilder, System.Reflection.Emit.MethodOnTypeBuilderInst, System.Reflection.MonoArrayMethod, System.Reflection.RuntimeConstructorInfo, and System.Reflection.RuntimeMethodInfo.
Definition at line 318 of file MethodBase.cs.
        {
            return this.GetParameters();
        }
References System.Reflection.MethodBase.GetParameters().
Referenced by System.Reflection.EventInfo.CreateAddEventDelegate(), System.Delegate.CreateDelegate(), System.Delegate.GetCandidateMethod(), System.Reflection.RuntimePropertyInfo.GetIndexParameters(), System.Reflection.Emit.CustomAttributeBuilder.GetParameters(), System.Reflection.MethodBase.GetParametersCount(), System.Attribute.InternalParamGetCustomAttributes(), System.Attribute.InternalParamIsDefined(), and System.Reflection.Emit.TypeBuilder.SetCustomAttribute().