Terraria Decompiled: System.Reflection.MethodBase.GetMethodFromHandle
GetMethodFromHandle() [1/2]
static MethodBase System.Reflection.MethodBase.GetMethodFromHandle (RuntimeMethodHandle handle) inline static
Definition at line 378 of file MethodBase.cs.
        {
            if (handle.IsNullHandle())
            {
                throw new ArgumentException(Environment.GetResourceString("The handle is invalid."));
            }
            MethodBase methodFromHandleInternalType = RuntimeMethodInfo.GetMethodFromHandleInternalType(handle.Value, IntPtr.Zero);
            if (methodFromHandleInternalType == null)
            {
                throw new ArgumentException("The handle is invalid.");
            }
            Type declaringType = methodFromHandleInternalType.DeclaringType;
            if (declaringType != null && declaringType.IsGenericType)
            {
                throw new ArgumentException(string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Cannot resolve method {0} because the declaring type of the method handle {1} is generic. Explicitly provide the declaring type to GetMethodFromHandle."), methodFromHandleInternalType, declaringType.GetGenericTypeDefinition()));
            }
            return methodFromHandleInternalType;
        }
References System.Globalization.CultureInfo.CurrentCulture, System.Reflection.MemberInfo.DeclaringType, System.Format, System.Type.GetGenericTypeDefinition(), System.Reflection.RuntimeMethodInfo.GetMethodFromHandleInternalType(), System.Environment.GetResourceString(), System.Type.IsGenericType, System.RuntimeMethodHandle.IsNullHandle(), System.RuntimeMethodHandle.Value, and System.IntPtr.Zero.
Referenced by System.RuntimeMethodHandle.GetObjectData(), System.Reflection.Emit.DynamicILInfo.GetTokenFor(), System.Reflection.Emit.GenericTypeParameterBuilder.InternalResolve(), and System.Reflection.Emit.GenericTypeParameterBuilder.RuntimeResolve().