Terraria Decompiled: ReLogic.Text.WrappedTextBuilder.Append
Append()
void ReLogic.Text.WrappedTextBuilder.Append (WrappedTextBuilder::NonBreakingText textToken) inline private
Definition at line 44 of file WrappedTextBuilder.cs.
        {
            float num;
            if (this._workingLineWidth == 0f)
            {
                num = textToken.WidthOnNewLine;
            }
            else
            {
                num = this._workingLineWidth + this._font.CharacterSpacing + textToken.Width;
            }
            if (num <= this._maxWidth)
            {
                this._workingLine.Append(textToken.Text);
                this._workingLineWidth = num;
                return;
            }
            this.FinishPartialLine();
            if (textToken.IsWhitespace)
            {
                return;
            }
            if (textToken.WidthOnNewLine <= this._maxWidth)
            {
                this._workingLine.Append(textToken.Text);
                this._workingLineWidth = textToken.WidthOnNewLine;
                return;
            }
            this.AppendWithHardBreaks(textToken.Text);
        }
References ReLogic.Text.WrappedTextBuilder._maxWidth, ReLogic.Text.WrappedTextBuilder._workingLine, ReLogic.Text.WrappedTextBuilder._workingLineWidth, System.Text.StringBuilder.Append(), ReLogic.Text.WrappedTextBuilder.AppendWithHardBreaks(), and ReLogic.Text.WrappedTextBuilder.FinishPartialLine().