Terraria Decompiled: ReLogic.Text.WrappedTextBuilder.AppendWithHardBreaks
AppendWithHardBreaks()
void ReLogic.Text.WrappedTextBuilder.AppendWithHardBreaks (string text) inline private
Definition at line 76 of file WrappedTextBuilder.cs.
        {
            for (int i = 0; i < text.Length; i++)
            {
                char c = text.get_Chars(i);
                GlyphMetrics characterMetrics = this._font.GetCharacterMetrics(c);
                float num;
                if (this._workingLine.IsEmpty())
                {
                    num = characterMetrics.KernedWidthOnNewLine;
                }
                else
                {
                    num = this._workingLineWidth + this._font.CharacterSpacing + characterMetrics.KernedWidth;
                }
                if (num <= this._maxWidth)
                {
                    this._workingLine.Append(c);
                    this._workingLineWidth = num;
                }
                else if (this._workingLine.Length > 1 && !StringReaderWrapExtension.BreaksBetweenMostGlyphs(this._culture))
                {
                    this._workingLineWidth += this._font.CharacterSpacing + this._font.GetCharacterMetrics('-').KernedWidth;
                    while (this._workingLine.Length > 1 && this._workingLineWidth > this._maxWidth)
                    {
                        this._workingLineWidth -= this._font.CharacterSpacing + this._font.GetCharacterMetrics(this._workingLine.get_Chars(this._workingLine.Length - 1)).KernedWidth;
                        this._workingLine.Remove(this._workingLine.Length - 1, 1);
                        i--;
                    }
                    this._workingLine.Append('-');
                    this.FinishPartialLine();
                    i--;
                }
                else
                {
                    this.FinishPartialLine();
                    this._workingLine.Append(c);
                    this._workingLineWidth = characterMetrics.KernedWidthOnNewLine;
                }
            }
        }
References ReLogic.Text.WrappedTextBuilder._font, ReLogic.Text.WrappedTextBuilder._maxWidth, ReLogic.Text.WrappedTextBuilder._workingLine, System.Text.StringBuilder.Append(), ReLogic.Text.StringReaderWrapExtension.BreaksBetweenMostGlyphs(), ReLogic.Text.WrappedTextBuilder.FinishPartialLine(), ReLogic.Text.IFontMetrics.GetCharacterMetrics(), ReLogic.Text.GlyphMetrics.KernedWidth, ReLogic.Text.GlyphMetrics.KernedWidthOnNewLine, System.Text.StringBuilder.Length, System.Text.StringBuilder.Remove(), and System.text.
Referenced by ReLogic.Text.WrappedTextBuilder.Append().