Terraria Decompiled: ReLogic.Text.WrappedTextBuilder.Build
Build()
string ReLogic.Text.WrappedTextBuilder.Build (string text) inline
Definition at line 119 of file WrappedTextBuilder.cs.
        {
            StringReader stringReader = new StringReader(text);
            this._completedText.EnsureCapacity(this._completedText.Capacity + text.Length);
            while (stringReader.Peek() > 0)
            {
                if ((ushort)stringReader.Peek() == 10)
                {
                    stringReader.Read();
                    this.CommitWorkingLine();
                }
                else
                {
                    string text2 = stringReader.ReadUntilBreakable(this._culture);
                    this.Append(new WrappedTextBuilder.NonBreakingText(this._font, text2));
                }
            }
            this.CommitWorkingLine();
            return this._completedText.ToString();
        }
References ReLogic.Text.WrappedTextBuilder._completedText, ReLogic.Text.WrappedTextBuilder._culture, System.IO.Append, System.Text.StringBuilder.Capacity, ReLogic.Text.WrappedTextBuilder.CommitWorkingLine(), System.Text.StringBuilder.EnsureCapacity(), System.IO.StringReader.Peek(), System.IO.StringReader.Read(), System.text, and System.Text.StringBuilder.ToString().
Referenced by ReLogic.Graphics.DynamicSpriteFont.CreateWrappedText().