Terraria Decompiled: System.Collections.Queue.Clone
Clone()
virtual object System.Collections.Queue.Clone () inline virtual
Implements System.ICloneable.
Reimplemented in System.Collections.Queue.SynchronizedQueue.
Definition at line 68 of file Queue.cs.
        {
            Queue queue = new Queue(this._size);
            queue._size = this._size;
            int num = this._size;
            int num2 = ((this._array.Length - this._head < num) ? (this._array.Length - this._head) : num);
            Array.Copy(this._array, this._head, queue._array, 0, num2);
            num -= num2;
            if (num > 0)
            {
                Array.Copy(this._array, 0, queue._array, this._array.Length - this._head, num);
            }
            queue._version = this._version;
            return queue;
        }
References System.Collections.Queue._array, System.Collections.Queue._head, System.Collections.Queue._size, System.Collections.Queue._version, System.Array.Copy(), System.Collections.Queue.Queue(), and System.queue.
Referenced by System.Collections.Queue.SynchronizedQueue.Clone().