Terraria Decompiled: System.Collections.Generic.EqualityComparer.Equals
Equals() [2/2]
bool System.Collections.Generic.EqualityComparer< T >.Equals (T x, T y) abstract
Implements System.Collections.Generic.IEqualityComparer< in T >.
Referenced by FullSerializer.Internal.fsEnumConverter.ArrayContains< T >(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsValue(), Terraria.Utils.Count< T >(), System.Collections.Generic.EqualityComparer< T >.Equals(), System.Collections.Generic.EqualityComparer< T >.IndexOf(), System.Collections.Generic.EqualityComparer< T >.LastIndexOf(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Terraria.Graphics.Shaders.ShaderData.EffectParameter< T >.SetValue(), System.Collections.Generic.Dictionary< TKey, TValue >.TryInsert(), and System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.TryRemoveInternal().