Terraria Decompiled: System.Collections.Generic.EqualityComparer.CreateComparer
CreateComparer()
static EqualityComparer< T > System.Collections.Generic.EqualityComparer< T >.CreateComparer () inline static private
Definition at line 31 of file EqualityComparer.cs.
        {
            RuntimeType runtimeType = (RuntimeType)typeof(T);
            if (runtimeType == typeof(byte))
            {
                return (EqualityComparer<T>)new ByteEqualityComparer();
            }
            if (typeof(IEquatable<T>).IsAssignableFrom(runtimeType))
            {
                return (EqualityComparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(GenericEqualityComparer<>), runtimeType);
            }
            if (runtimeType.IsGenericType && runtimeType.GetGenericTypeDefinition() == typeof(Nullable<>))
            {
                RuntimeType runtimeType2 = (RuntimeType)runtimeType.GetGenericArguments()[0];
                if (typeof(IEquatable<>).MakeGenericType(new Type[] { runtimeType2 }).IsAssignableFrom(runtimeType2))
                {
                    return (EqualityComparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(NullableEqualityComparer<>), runtimeType2);
                }
            }
            if (runtimeType.IsEnum)
            {
                switch (Type.GetTypeCode(Enum.GetUnderlyingType(runtimeType)))
                {
                case TypeCode.SByte:
                    return (EqualityComparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(SByteEnumEqualityComparer<>), runtimeType);
                case TypeCode.Byte:
                case TypeCode.UInt16:
                case TypeCode.Int32:
                case TypeCode.UInt32:
                    return (EqualityComparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(EnumEqualityComparer<>), runtimeType);
                case TypeCode.Int16:
                    return (EqualityComparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(ShortEnumEqualityComparer<>), runtimeType);
                case TypeCode.Int64:
                case TypeCode.UInt64:
                    return (EqualityComparer<T>)RuntimeType.CreateInstanceForAnotherGenericParameter(typeof(LongEnumEqualityComparer<>), runtimeType);
                }
            }
            return new ObjectEqualityComparer<T>();
        }
References System.RuntimeType.CreateInstanceForAnotherGenericParameter(), System.RuntimeType.GetGenericArguments(), System.RuntimeType.GetGenericTypeDefinition(), System.Type.GetTypeCode(), System.Enum.GetUnderlyingType(), System.RuntimeType.IsEnum, and System.RuntimeType.IsGenericType.