Terraria Decompiled: System.Reflection.Emit.MethodOnTypeBuilderInst.ToString
ToString()
override string System.Reflection.Emit.MethodOnTypeBuilderInst.ToString () inline
Implements System.Runtime.InteropServices._MethodInfo.
Definition at line 160 of file MethodOnTypeBuilderInst.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(this.ReturnType.ToString());
            stringBuilder.Append(" ");
            stringBuilder.Append(this.base_method.Name);
            stringBuilder.Append("(");
            stringBuilder.Append(")");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Reflection.Emit.MethodOnTypeBuilderInst.base_method, System.Runtime.InteropServices._MethodInfo.Name, System.Reflection.Emit.MethodOnTypeBuilderInst.ReturnType, System.Text.StringBuilder.ToString(), and System.Type.ToString().