Terraria Decompiled: System.Reflection.Emit.MethodOnTypeBuilderInst.RuntimeResolve
RuntimeResolve()
MethodInfo System.Reflection.Emit.MethodOnTypeBuilderInst.RuntimeResolve () inline package
Definition at line 76 of file MethodOnTypeBuilderInst.cs.
        {
            MethodInfo methodInfo = this.instantiation.InternalResolve().GetMethod(this.base_method);
            if (this.method_arguments != null)
            {
                Type[] array = new Type[this.method_arguments.Length];
                for (int i = 0; i < this.method_arguments.Length; i++)
                {
                    array[i] = this.method_arguments[i].InternalResolve();
                }
                methodInfo = methodInfo.MakeGenericMethod(array);
            }
            return methodInfo;
        }
References System.array, System.Reflection.Emit.MethodOnTypeBuilderInst.base_method, System.Type.GetMethod(), System.Reflection.Emit.MethodOnTypeBuilderInst.instantiation, System.Type.InternalResolve(), System.Reflection.MethodInfo.MakeGenericMethod(), and System.Reflection.Emit.MethodOnTypeBuilderInst.method_arguments.