Terraria Decompiled: Terraria.Social.Steam.WorkshopSocialModule.PublishWorld
PublishWorld()
override void Terraria.Social.Steam.WorkshopSocialModule.PublishWorld (WorldFileData world, WorkshopItemPublishSettings settings) inline
Definition at line 101 of file WorkshopSocialModule.cs.
        {
            string name = world.Name;
            string textForWorld = this.GetTextForWorld(world);
            string[] usedTagsInternalNames = settings.GetUsedTagsInternalNames();
            string text = this.GetTemporaryFolderPath() + world.GetFileName(false);
            if (!this.MakeTemporaryFolder(text))
            {
                return;
            }
            WorkshopHelper.UGCBased.WorldPublisherInstance worldPublisherInstance = new WorkshopHelper.UGCBased.WorldPublisherInstance(world);
            this._publisherInstances.Add(worldPublisherInstance);
            worldPublisherInstance.PublishContent(this._publishedItems, base.IssueReporter, new WorkshopHelper.UGCBased.APublisherInstance.FinishedPublishingAction(this.Forget), name, textForWorld, text, settings.PreviewImagePath, settings.Publicity, usedTagsInternalNames);
        }
References Terraria.Social.Steam.WorkshopSocialModule._publishedItems, Terraria.Social.Steam.WorkshopSocialModule._publisherInstances, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.FinishedPublishingAction(), Terraria.IO.FileData.GetFileName(), Terraria.Social.Steam.WorkshopSocialModule.GetTemporaryFolderPath(), Terraria.Social.Steam.WorkshopSocialModule.GetTextForWorld(), Terraria.Social.Base.WorkshopItemPublishSettings.GetUsedTagsInternalNames(), Terraria.Social.Steam.WorkshopSocialModule.MakeTemporaryFolder(), System.name, Terraria.IO.FileData.Name, Terraria.Social.Base.WorkshopItemPublishSettings.PreviewImagePath, Terraria.Social.Base.WorkshopItemPublishSettings.Publicity, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent(), and System.text.