Terraria Decompiled: Terraria.Social.Steam.WorkshopSocialModule.GetTemporaryFolderPath
GetTemporaryFolderPath()
string Terraria.Social.Steam.WorkshopSocialModule.GetTemporaryFolderPath () inline private
Definition at line 203 of file WorkshopSocialModule.cs.
        {
            ulong steamID = SteamUser.GetSteamID().m_SteamID;
            return this._contentBaseFolder + Path.DirectorySeparatorChar.ToString() + steamID.ToString() + Path.DirectorySeparatorChar.ToString();
        }
References System.IO.Path.DirectorySeparatorChar, Steamworks.SteamUser.GetSteamID(), and Steamworks.CSteamID.m_SteamID.
Referenced by Terraria.Social.Steam.WorkshopSocialModule.PublishWorld(), and Terraria.Social.Steam.WorkshopSocialModule.TryGetInfoForWorld().