Terraria Decompiled: Terraria.Social.Steam.WorkshopSocialModule.Initialize
Initialize()
override void Terraria.Social.Steam.WorkshopSocialModule.Initialize () inline
Definition at line 18 of file WorkshopSocialModule.cs.
        {
            base.Branding = new WorkshopBranding
            {
                ResourcePackBrand = ResourcePack.BrandingType.SteamWorkshop
            };
            this._publisherInstances = new List<WorkshopHelper.UGCBased.APublisherInstance>();
            base.ProgressReporter = new WorkshopProgressReporter(this._publisherInstances);
            base.SupportedTags = new SupportedWorkshopTags();
            this._contentBaseFolder = Main.SavePath + Path.DirectorySeparatorChar.ToString() + "Workshop";
            this._downloader = WorkshopHelper.UGCBased.Downloader.Create();
            this._publishedItems = WorkshopHelper.UGCBased.PublishedItemsFinder.Create();
            WorkshopIssueReporter workshopIssueReporter = new WorkshopIssueReporter();
            workshopIssueReporter.OnNeedToOpenUI += this._issueReporter_OnNeedToOpenUI;
            workshopIssueReporter.OnNeedToNotifyUI += this._issueReporter_OnNeedToNotifyUI;
            base.IssueReporter = workshopIssueReporter;
            UIWorkshopHub.OnWorkshopHubMenuOpened += this.RefreshSubscriptionsAndPublishings;
        }
References Terraria.Social.Steam.WorkshopSocialModule._issueReporter_OnNeedToNotifyUI(), Terraria.Social.Steam.WorkshopSocialModule._issueReporter_OnNeedToOpenUI(), Terraria.Social.Steam.WorkshopSocialModule._publisherInstances, Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Create(), Terraria.Social.Steam.WorkshopHelper.UGCBased.PublishedItemsFinder.Create(), System.IO.Path.DirectorySeparatorChar, and Terraria.Social.Steam.WorkshopSocialModule.RefreshSubscriptionsAndPublishings().