Terraria Decompiled: Terraria.Social.Steam.WorkshopSocialModule.PublishResourcePack
PublishResourcePack()
override void Terraria.Social.Steam.WorkshopSocialModule.PublishResourcePack (ResourcePack resourcePack, WorkshopItemPublishSettings settings) inline
Definition at line 182 of file WorkshopSocialModule.cs.
        {
            if (resourcePack.IsCompressed)
            {
                base.IssueReporter.ReportInstantUploadProblem("Workshop.ReportIssue_CannotPublishZips");
                return;
            }
            string name = resourcePack.Name;
            string text = resourcePack.Description;
            if (string.IsNullOrWhiteSpace(text))
            {
                text = "";
            }
            string[] usedTagsInternalNames = settings.GetUsedTagsInternalNames();
            string fullPath = resourcePack.FullPath;
            WorkshopHelper.UGCBased.ResourcePackPublisherInstance resourcePackPublisherInstance = new WorkshopHelper.UGCBased.ResourcePackPublisherInstance(resourcePack);
            this._publisherInstances.Add(resourcePackPublisherInstance);
            resourcePackPublisherInstance.PublishContent(this._publishedItems, base.IssueReporter, new WorkshopHelper.UGCBased.APublisherInstance.FinishedPublishingAction(this.Forget), name, text, fullPath, settings.PreviewImagePath, settings.Publicity, usedTagsInternalNames);
        }
References Terraria.Social.Steam.WorkshopSocialModule._publishedItems, Terraria.Social.Steam.WorkshopSocialModule._publisherInstances, Terraria.IO.ResourcePack.Description, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.FinishedPublishingAction(), Terraria.IO.ResourcePack.FullPath, Terraria.Social.Base.WorkshopItemPublishSettings.GetUsedTagsInternalNames(), Terraria.IO.ResourcePack.IsCompressed, System.name, Terraria.IO.ResourcePack.Name, Terraria.Social.Base.WorkshopItemPublishSettings.PreviewImagePath, Terraria.Social.Base.WorkshopItemPublishSettings.Publicity, Terraria.Social.Steam.WorkshopHelper.UGCBased.APublisherInstance.PublishContent(), and System.text.