Terraria Decompiled: Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals
ValueEquals()
static bool Newtonsoft.Json.Utilities.MiscellaneousUtils.ValueEquals (object objA, object objB) inline static
Definition at line 10 of file MiscellaneousUtils.cs.
        {
            if (objA == objB)
            {
                return true;
            }
            if (objA == null || objB == null)
            {
                return false;
            }
            if (!(objA.GetType() != objB.GetType()))
            {
                return objA.Equals(objB);
            }
            if (ConvertUtils.IsInteger(objA) && ConvertUtils.IsInteger(objB))
            {
                return Convert.ToDecimal(objA, CultureInfo.CurrentCulture).Equals(Convert.ToDecimal(objB, CultureInfo.CurrentCulture));
            }
            return (objA is double || objA is float || objA is decimal) && (objB is double || objB is float || objB is decimal) && MathUtils.ApproxEquals(Convert.ToDouble(objA, CultureInfo.CurrentCulture), Convert.ToDouble(objB, CultureInfo.CurrentCulture));
        }
References Newtonsoft.Json.Utilities.MathUtils.ApproxEquals(), System.Globalization.CultureInfo.CurrentCulture, Newtonsoft.Json.Utilities.ConvertUtils.IsInteger(), System.Convert.ToDecimal(), and System.Convert.ToDouble().
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CalculatePropertyDetails(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.ShouldSetPropertyValue(), Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteDynamicProperty(), and Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.ShouldWriteProperty().