Terraria Decompiled: System.IO.BufferedStream.d__51.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.BufferedStream.d__51.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1504 of file BufferedStream.cs.
            {
                int num6;
                int num5 = num6;
                BufferedStream bufferedStream = this;
                int num8;
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                    if (num5 != 0)
                    {
                        if (num5 - 1 <= 2)
{
                            goto IL_007C;
                        }
                        configuredTaskAwaiter = semaphoreLockTask.ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num5 = (num6 = 0);
                            configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<ReadFromUnderlyingStreamAsync>d__51>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num5 = (num6 = -1);
                    }
                    configuredTaskAwaiter.GetResult();
                    IL_007C:
                    try
                    {
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        int num7;
                        switch (num5)
{
                        case 1:
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num5 = (num6 = -1);
                            break;
                        case 2:
{
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                            num5 = (num6 = -1);
                            goto IL_0207;
                        }
                        case 3:
{
                            ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                            num5 = (num6 = -1);
                            goto IL_02A7;
                        }
                        default:
                            num7 = bufferedStream.ReadFromBuffer(buffer.Span);
                            if (num7 == buffer.Length)
{
                                num8 = bytesAlreadySatisfied + num7;
                                goto IL_0301;
                            }
                            if (num7 > 0)
{
                                buffer = buffer.Slice(num7);
                                bytesAlreadySatisfied += num7;
                            }
                            bufferedStream._readPos = (bufferedStream._readLen = 0);
                            if (bufferedStream._writePos <= 0)
{
                                goto IL_016F;
                            }
                            configuredTaskAwaiter = bufferedStream.FlushWriteAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                            if (!configuredTaskAwaiter.IsCompleted)
{
                                num5 = (num6 = 1);
                                configuredTaskAwaiter2 = configuredTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<ReadFromUnderlyingStreamAsync>d__51>(ref configuredTaskAwaiter, ref this);
                                return;
                            }
                            break;
                        }
                        configuredTaskAwaiter.GetResult();
                        IL_016F:
                        if (buffer.Length >= bufferedStream._bufferSize)
{
                            num4 = bytesAlreadySatisfied;
                            configuredValueTaskAwaiter = bufferedStream._stream.ReadAsync(buffer, cancellationToken).ConfigureAwait(false).GetAwaiter();
                            if (!configuredValueTaskAwaiter.IsCompleted)
{
                                num5 = (num6 = 2);
                                ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, BufferedStream.<ReadFromUnderlyingStreamAsync>d__51>(ref configuredValueTaskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            bufferedStream.EnsureBufferAllocated();
                            configuredValueTaskAwaiter = bufferedStream._stream.ReadAsync(new Memory<byte>(bufferedStream._buffer, 0, bufferedStream._bufferSize), cancellationToken).ConfigureAwait(false).GetAwaiter();
                            if (!configuredValueTaskAwaiter.IsCompleted)
{
                                num5 = (num6 = 3);
                                ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, BufferedStream.<ReadFromUnderlyingStreamAsync>d__51>(ref configuredValueTaskAwaiter, ref this);
                                return;
                            }
                            goto IL_02A7;
                        }
                        IL_0207:
                        int num9 = configuredValueTaskAwaiter.GetResult();
                        num8 = num4 + num9;
                        goto IL_0301;
                        IL_02A7:
                        num9 = configuredValueTaskAwaiter.GetResult();
                        bufferedStream._readLen = num9;
                        num7 = bufferedStream.ReadFromBuffer(buffer.Span);
                        num8 = bytesAlreadySatisfied + num7;
                    }
                    finally
                    {
                        if (num5 < 0)
{
                            bufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized().Release();
                        }
                    }
                }
                catch (Exception ex)
                {
                    num6 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_0301:
                num6 = -2;
                this.<>t__builder.SetResult(num8);
            }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._bufferSize, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.BufferedStream.EnsureBufferAllocated(), System.IO.BufferedStream.FlushWriteAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.ReadOnlyMemory< T >.Length, System.IO.Stream.ReadAsync(), System.IO.BufferedStream.ReadFromBuffer(), System.IO.BufferedStream.ReadFromUnderlyingStreamAsync(), System.Threading.SemaphoreSlim.Release(), System.ReadOnlyMemory< T >.Slice(), and System.ReadOnlyMemory< T >.Span.