Terraria Decompiled: System.Globalization.HijriCalendar.GetDatePart
GetDatePart()
virtual int System.Globalization.HijriCalendar.GetDatePart (long ticks, int part) inline package virtual
Definition at line 165 of file HijriCalendar.cs.
        {
            HijriCalendar.CheckTicksRange(ticks);
            long num = ticks / 864000000000L + 1L;
            num += (long)this.HijriAdjustment;
            int num2 = (int)((num - 227013L) * 30L / 10631L) + 1;
            long num3 = this.DaysUpToHijriYear(num2);
            long num4 = (long)this.GetDaysInYear(num2, 0);
            if (num < num3)
            {
                num3 -= num4;
                num2--;
            }
            else if (num == num3)
            {
                num2--;
                num3 -= (long)this.GetDaysInYear(num2, 0);
            }
            else if (num > num3 + num4)
            {
                num3 += num4;
                num2++;
            }
            if (part == 0)
            {
                return num2;
            }
            int num5 = 1;
            num -= num3;
            if (part == 1)
            {
                return (int)num;
            }
            while (num5 <= 12 && num > (long)HijriCalendar.HijriMonthDays[num5 - 1])
            {
                num5++;
            }
            num5--;
            if (part == 2)
            {
                return num5;
            }
            int num6 = (int)(num - (long)HijriCalendar.HijriMonthDays[num5 - 1]);
            if (part == 3)
            {
                return num6;
            }
            throw new InvalidOperationException(Environment.GetResourceString("Internal Error in DateTime and Calendar operations."));
        }
References System.Globalization.HijriCalendar.CheckTicksRange(), System.Globalization.HijriCalendar.DaysUpToHijriYear(), System.Globalization.HijriCalendar.GetDaysInYear(), System.Environment.GetResourceString(), System.Globalization.HijriCalendar.HijriAdjustment, System.Globalization.HijriCalendar.HijriMonthDays, int, System.L, and long.
Referenced by System.Globalization.HijriCalendar.AddMonths(), System.Globalization.HijriCalendar.GetDayOfMonth(), System.Globalization.HijriCalendar.GetDayOfYear(), System.Globalization.HijriCalendar.GetMonth(), and System.Globalization.HijriCalendar.GetYear().