Terraria Decompiled: Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate
LineUpdate()
void Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate () inline private
Definition at line 137 of file WiresUI.cs.
            {
                bool flag = true;
                float num = 0.75f;
                Player player = Main.player[Main.myPlayer];
                if (!WiresUI.Settings.DrawToolModeUI || Main.drawingPlayerChat)
                {
                    flag = false;
                    num = 0f;
                }
                if (player.dead || Main.mouseItem.type > 0)
                {
                    this._lineOpacity = 0f;
                    return;
                }
                if (player.cursorItemIconEnabled && player.cursorItemIconID != 0 && player.cursorItemIconID != 3625)
                {
                    this._lineOpacity = 0f;
                    return;
                }
                if ((!player.cursorItemIconEnabled && ((!PlayerInput.UsingGamepad && !WiresUI.Settings.DrawToolAllowActuators) || player.mouseInterface || player.lastMouseInterface)) || Main.ingameOptionsWindow || Main.InGameUI.IsVisible)
                {
                    this._lineOpacity = 0f;
                    return;
                }
                float num2 = Utils.Clamp<float>(this._lineOpacity + 0.05f * (float)flag.ToDirectionInt(), num, 1f);
                this._lineOpacity += 0.05f * (float)Math.Sign(num2 - this._lineOpacity);
                if (Math.Abs(this._lineOpacity - num2) < 0.05f)
                {
                    this._lineOpacity = num2;
                }
            }
References System.Math.Abs(), Terraria.Utils.Clamp(), Terraria.Player.cursorItemIconEnabled, Terraria.Player.cursorItemIconID, Terraria.Player.dead, Terraria.Main.drawingPlayerChat, Terraria.GameContent.UI.WiresUI.Settings.DrawToolAllowActuators, Terraria.GameContent.UI.WiresUI.Settings.DrawToolModeUI, Terraria.Main.ingameOptionsWindow, Terraria.Main.InGameUI, Terraria.Player.lastMouseInterface, Terraria.Player.mouseInterface, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.player, System.Math.Sign(), Terraria.Item.type, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.GameContent.UI.WiresUI.WiresRadial.Update().