Terraria Decompiled: Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower
DrawFlower()
void Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower (SpriteBatch spriteBatch) inline private
Definition at line 361 of file WiresUI.cs.
            {
                if (!this.active)
                {
                    return;
                }
                Vector2 vector = Main.MouseScreen;
                Vector2 vector2 = this.position;
                if (PlayerInput.UsingGamepad && Main.SmartCursorWanted)
                {
                    if (PlayerInput.GamepadThumbstickRight != Vector2.Zero)
                    {
                        vector = this.position + PlayerInput.GamepadThumbstickRight * 40f;
                    }
                    else if (PlayerInput.GamepadThumbstickLeft != Vector2.Zero)
                    {
                        vector = this.position + PlayerInput.GamepadThumbstickLeft * 40f;
                    }
                    else
                    {
                        vector = this.position;
                    }
                }
                Vector2 vector3 = vector - vector2;
                Vector2.Dot(Vector2.Normalize(vector3), Vector2.UnitX);
                Vector2.Dot(Vector2.Normalize(vector3), Vector2.UnitY);
                float num = vector3.ToRotation();
                float num2 = vector3.Length();
                bool flag = false;
                bool drawToolAllowActuators = WiresUI.Settings.DrawToolAllowActuators;
                float num3 = (float)(4 + drawToolAllowActuators.ToInt());
                float num4 = (drawToolAllowActuators ? 11f : (-0.5f));
                for (int i = 0; i < 6; i++)
                {
                    if (drawToolAllowActuators || i != 5)
                    {
                        bool flag2 = (WiresUI.Settings.ToolMode & (WiresUI.Settings.MultiToolMode)(1 << i)) > (WiresUI.Settings.MultiToolMode)0;
                        if (i == 5)
{
                            flag2 = (WiresUI.Settings.ToolMode & WiresUI.Settings.MultiToolMode.Actuator) > (WiresUI.Settings.MultiToolMode)0;
                        }
                        Vector2 vector4 = vector2 + Vector2.UnitX * (45f * ((float)i - 1.5f));
                        switch (i)
{
                        case 0:
                        case 1:
                        case 2:
                        case 3:
{
                            float num5 = (float)i;
                            if (i == 0)
{
                                num5 = 3f;
                            }
                            if (i == 3)
{
                                num5 = 0f;
                            }
                            vector4 = vector2 + Vector2.UnitX.RotatedBy((double)(num5 * 6.2831855f / num3 - 3.1415927f / num4), default(Vector2)) * 45f;
                            break;
                        }
                        case 4:
                            flag2 = false;
                            vector4 = vector2;
                            break;
                        case 5:
                            vector4 = vector2 + Vector2.UnitX.RotatedBy((double)((float)(i - 1) * 6.2831855f / num3 - 3.1415927f / num4), default(Vector2)) * 45f;
                            break;
                        }
                        bool flag3 = false;
                        if (i == 4)
{
                            flag3 = num2 < 20f;
                        }
                        switch (i)
{
                        case 0:
                        case 1:
                        case 2:
                        case 3:
                        case 5:
{
                            float num6 = (vector4 - vector2).ToRotation().AngleTowards(num, 6.2831855f / (num3 * 2f)) - num;
                            if (num2 >= 20f && Math.Abs(num6) < 0.01f)
{
                                flag3 = true;
                            }
                            break;
                        }
                        case 4:
                            flag3 = num2 < 20f;
                            break;
                        }
                        if (!PlayerInput.UsingGamepad)
{
                            flag3 = Vector2.Distance(vector4, vector) < 19f;
                        }
                        if (flag)
{
                            flag3 = false;
                        }
                        if (flag3)
{
                            flag = true;
                        }
                        Texture2D value = TextureAssets.WireUi[(((WiresUI.Settings.ToolMode & WiresUI.Settings.MultiToolMode.Cutter) != (WiresUI.Settings.MultiToolMode)0) ? 8 : 0) + (flag3 ? 1 : 0)].Value;
                        Texture2D texture2D = null;
                        switch (i)
{
                        case 0:
                        case 1:
                        case 2:
                        case 3:
                            texture2D = TextureAssets.WireUi[2 + i].Value;
                            break;
                        case 4:
                            texture2D = TextureAssets.WireUi[((WiresUI.Settings.ToolMode & WiresUI.Settings.MultiToolMode.Cutter) != (WiresUI.Settings.MultiToolMode)0) ? 7 : 6].Value;
                            break;
                        case 5:
                            texture2D = TextureAssets.WireUi[10].Value;
                            break;
                        }
                        Color white = Color.White;
                        Color white2 = Color.White;
                        if (!flag2 && i != 4)
{
                            if (flag3)
{
                                white2 = new Color(100, 100, 100);
                                white2 = new Color(120, 120, 120);
                                white = new Color(200, 200, 200);
                            }
                            else
{
                                white2 = new Color(150, 150, 150);
                                white2 = new Color(80, 80, 80);
                                white = new Color(100, 100, 100);
                            }
                        }
                        Utils.CenteredRectangle(vector4, new Vector2(40f));
                        if (flag3)
{
                            if (Main.mouseLeft && Main.mouseLeftRelease)
{
                                switch (i)
{
                                case 0:
                                    WiresUI.Settings.ToolMode ^= WiresUI.Settings.MultiToolMode.Red;
                                    break;
                                case 1:
                                    WiresUI.Settings.ToolMode ^= WiresUI.Settings.MultiToolMode.Green;
                                    break;
                                case 2:
                                    WiresUI.Settings.ToolMode ^= WiresUI.Settings.MultiToolMode.Blue;
                                    break;
                                case 3:
                                    WiresUI.Settings.ToolMode ^= WiresUI.Settings.MultiToolMode.Yellow;
                                    break;
                                case 4:
                                    WiresUI.Settings.ToolMode ^= WiresUI.Settings.MultiToolMode.Cutter;
                                    break;
                                case 5:
                                    WiresUI.Settings.ToolMode ^= WiresUI.Settings.MultiToolMode.Actuator;
                                    break;
                                }
                            }
                            Main.player[Main.myPlayer].mouseInterface = true;
                            this.OnWiresMenu = true;
                        }
                        spriteBatch.Draw(value, vector4, null, white, 0f, value.Size() / 2f, 1f, SpriteEffects.None, 0f);
                        spriteBatch.Draw(texture2D, vector4, null, white2, 0f, texture2D.Size() / 2f, 1f, SpriteEffects.None, 0f);
                    }
                }
                if (Main.mouseLeft && Main.mouseLeftRelease && !flag)
                {
                    this.active = false;
                }
            }
References System.Math.Abs(), Terraria.GameContent.UI.WiresUI.WiresRadial.active, Terraria.Utils.CenteredRectangle(), Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Vector2.Dot(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.WiresUI.Settings.DrawToolAllowActuators, Terraria.GameInput.PlayerInput.GamepadThumbstickLeft, Terraria.GameInput.PlayerInput.GamepadThumbstickRight, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseScreen, Terraria.Main.myPlayer, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.player, Terraria.GameContent.UI.WiresUI.WiresRadial.position, Terraria.Main.SmartCursorWanted, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Vector2.UnitY, Terraria.GameInput.PlayerInput.UsingGamepad, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.TextureAssets.WireUi, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.WiresUI.WiresRadial.Draw().