Terraria Decompiled: ReLogic.Content.AssetPathHelper.CleanPath
CleanPath()
static string ReLogic.Content.AssetPathHelper.CleanPath (string path) inline static
Definition at line 10 of file AssetPathHelper.cs.
        {
            path = path.Replace('/', '\\');
            path = path.Replace("\\.\\", "\\");
            while (path.StartsWith(".\\"))
            {
                path = path.Substring(".\\".Length);
            }
            while (path.EndsWith("\\."))
            {
                if (path.Length > "\\.".Length)
                {
                    path = path.Substring(0, path.Length - "\\.".Length);
                }
                else
                {
                    path = "\\";
                }
            }
            for (int i = 1; i < path.Length; i = AssetPathHelper.CollapseParentDirectory(ref path, i, "\\..\\".Length))
            {
                i = path.IndexOf("\\..\\", i);
                if (i < 0)
                {
                    break;
                }
            }
            if (path.EndsWith("\\.."))
            {
                int num = path.Length - "\\..".Length;
                if (num > 0)
                {
                    AssetPathHelper.CollapseParentDirectory(ref path, num, "\\..".Length);
                }
            }
            if (path == ".")
            {
                path = string.Empty;
            }
            if (Path.DirectorySeparatorChar != '\\')
            {
                path = path.Replace('\\', Path.DirectorySeparatorChar);
            }
            return path;
        }
References ReLogic.Content.AssetPathHelper.CollapseParentDirectory(), and System.IO.Path.DirectorySeparatorChar.
Referenced by ReLogic.Content.Sources.FileSystemContentSource.Refresh(), ReLogic.Content.Sources.ZipContentSource.Refresh(), ReLogic.Content.AssetRepository.Request< T >(), ReLogic.Content.Sources.XnaContentSource.XnaContentSource(), and ReLogic.Content.Sources.XnaDirectContentSource.XnaDirectContentSource().