Terraria Decompiled: Terraria.Chest.CloneWithSeparateItems
CloneWithSeparateItems()
Chest Terraria.Chest.CloneWithSeparateItems () inline
Definition at line 143 of file Chest.cs.
        {
            Chest chest = new Chest(this.index, this.x, this.y, this.bankChest, this.maxItems)
            {
                name = this.name
            };
            for (int i = 0; i < this.maxItems; i++)
            {
                chest.item[i] = this.item[i].Clone();
                chest._itemsGotSet = true;
            }
            return chest;
        }
References Terraria.Chest.bankChest, Terraria.Chest.Chest(), Terraria.Item.Clone(), Terraria.Chest.index, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Chest.name, Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.Utilities.TileSnapshot.RestoreChests(), and Terraria.Utilities.TileSnapshot.SaveChests().