Terraria Decompiled: Terraria.Chest.IndicateBlockedChest
IndicateBlockedChest()
static void Terraria.Chest.IndicateBlockedChest (int chestIndex) inline static
Definition at line 3584 of file Chest.cs.
        {
            Chest chest = Main.chest[chestIndex];
            if (chest == null)
            {
                return;
            }
            RoomCheckParticle roomCheckParticle = Chest._particlePool.RequestParticle();
            roomCheckParticle.SetBasicInfo(TextureAssets.Cd, null, Vector2.Zero, new Vector2((float)(chest.x * 16 + 16), (float)(chest.y * 16 + 16)));
            float num = 60f;
            roomCheckParticle.Delay = 0;
            float num2 = num - (float)roomCheckParticle.Delay;
            roomCheckParticle.SetTypeInfo(num2, false);
            roomCheckParticle.FadeInNormalizedTime = Utils.Remap(num - 55f, (float)roomCheckParticle.Delay, num, 0f, 1f, true);
            roomCheckParticle.FadeOutNormalizedTime = Utils.Remap(num - 20f, (float)roomCheckParticle.Delay, num, 0f, 1f, true);
            roomCheckParticle.ColorTint = new Color(255, 40, 40, 255);
            roomCheckParticle.Scale = Vector2.One * 1f;
            roomCheckParticle.Velocity = Vector2.UnitY * 0.1f;
            roomCheckParticle.AccelerationPerFrame = Vector2.UnitY * -0.4f / num2;
            Main.ParticleSystem_World_OverPlayers.Add(roomCheckParticle);
        }
References Terraria.Chest._particlePool, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Terraria.GameContent.TextureAssets.Cd, Terraria.Main.chest, Terraria.Graphics.Renderers.FadingParticle.Delay, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Utils.Remap(), Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Terraria.Chest.x, Terraria.Chest.y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.QuickStacking.IndicateBlockedChests().