Terraria Decompiled: Terraria.Chest.SetupTravelShop
SetupTravelShop()
static void Terraria.Chest.SetupTravelShop () inline static
Definition at line 1259 of file Chest.cs.
        {
            for (int i = 0; i < Main.travelShop.Length; i++)
            {
                Main.travelShop[i] = 0;
            }
            Player playerWithHighestLuck = Player.GetPlayerWithHighestLuck();
            int num = Main.rand.Next(4, 7);
            if (playerWithHighestLuck.RollLuck(4) == 0)
            {
                num++;
            }
            if (playerWithHighestLuck.RollLuck(8) == 0)
            {
                num++;
            }
            if (playerWithHighestLuck.RollLuck(16) == 0)
            {
                num++;
            }
            if (playerWithHighestLuck.RollLuck(32) == 0)
            {
                num++;
            }
            if (Main.expertMode && playerWithHighestLuck.RollLuck(2) == 0)
            {
                num++;
            }
            if (NPC.peddlersSatchelWasUsed)
            {
                num++;
            }
            if (Main.tenthAnniversaryWorld)
            {
                if (!Main.getGoodWorld)
                {
                    num++;
                }
                num++;
            }
            int num2 = 0;
            int j = 0;
            int[] array = new int[] { 100, 200, 300, 400, 500, 600 };
            int[] array2 = array;
            int k = 0;
            if (Main.hardMode)
            {
                int num3 = 0;
                while (k < 5000)
                {
                    k++;
                    Chest.SetupTravelShop_AdjustSlotRarities(k, ref array2);
                    Chest.SetupTravelShop_GetItem(playerWithHighestLuck, array2, ref num3, 2);
                    if (Chest.SetupTravelShop_CanAddItemToShop(num3))
                    {
                        Chest.SetupTravelShop_AddToShop(num3, ref j, ref num2);
                        break;
                    }
                }
            }
            while (j < num)
            {
                int num4 = 0;
                Chest.SetupTravelShop_GetItem(playerWithHighestLuck, array, ref num4, 0);
                if (Chest.SetupTravelShop_CanAddItemToShop(num4))
                {
                    Chest.SetupTravelShop_AddToShop(num4, ref j, ref num2);
                }
            }
            array2 = array;
            k = 0;
            int num5 = 0;
            while (k < 5000)
            {
                k++;
                Chest.SetupTravelShop_AdjustSlotRarities(k, ref array2);
                Chest.SetupTravelShop_GetPainting(playerWithHighestLuck, array2, ref num5, 0);
                if (Chest.SetupTravelShop_CanAddItemToShop(num5))
                {
                    Chest.SetupTravelShop_AddToShop(num5, ref j, ref num2);
                    return;
                }
            }
        }
References System.array, Terraria.Main.expertMode, Terraria.Main.getGoodWorld, Terraria.Player.GetPlayerWithHighestLuck(), Terraria.Main.hardMode, Terraria.NPC.peddlersSatchelWasUsed, Terraria.Main.rand, Terraria.Player.RollLuck(), Terraria.Chest.SetupTravelShop_AddToShop(), Terraria.Chest.SetupTravelShop_AdjustSlotRarities(), Terraria.Chest.SetupTravelShop_CanAddItemToShop(), Terraria.Chest.SetupTravelShop_GetItem(), Terraria.Chest.SetupTravelShop_GetPainting(), Terraria.Main.tenthAnniversaryWorld, and Terraria.Main.travelShop.
Referenced by Terraria.Main.Initialize_AlmostEverything(), and Terraria.WorldGen.SpawnTravelNPC().