Terraria Decompiled: Terraria.Chest.VisualizeChestTransfer
VisualizeChestTransfer()
static void Terraria.Chest.VisualizeChestTransfer (Vector2 position, Vector2 chestPosition, int itemType, Chest::ItemTransferVisualizationSettings settings) inline static
Definition at line 228 of file Chest.cs.
        {
            BitsByte bitsByte = new BitsByte(settings.RandomizeStartPosition, settings.RandomizeEndPosition, settings.TransitionIn, settings.Fullbright, false, false, false, false);
            ParticleOrchestrator.BroadcastOrRequestParticleSpawn(ParticleOrchestraType.ItemTransfer, new ParticleOrchestraSettings
            {
                PositionInWorld = position,
                MovementVector = chestPosition - position,
                UniqueInfoPiece = (itemType | ((int)bitsByte << 24))
            });
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn().
Referenced by Terraria.GameContent.QuickStacking.FillStack(), Terraria.Wiring.Hopper(), Terraria.GameContent.QuickStacking.InsertIntoFreeSlot(), and Terraria.Chest.VisualizeChestTransfer_CoinsBatch().