Terraria Decompiled: Terraria.Chest.CreateWorldChest
CreateWorldChest()
static Chest Terraria.Chest.CreateWorldChest (int index, int x, int y) inline static
Definition at line 28 of file Chest.cs.
        {
            Chest chest = new Chest(index, x, y, false, 40);
            chest.FillWithEmptyInstances();
            Chest.Assign(chest);
            return chest;
        }
References Terraria.Chest.Assign(), Terraria.Chest.Chest(), Terraria.Chest.FillWithEmptyInstances(), Terraria.Chest.index, Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.Chest.AfterPlacement_Hook(), Terraria.Chest.CreateChest(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.IO.WorldFile.LoadChests(), and Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88().