Terraria Decompiled: Terraria.Chest.DestroyChest
DestroyChest()
static bool Terraria.Chest.DestroyChest (int X, int Y) inline static
Definition at line 562 of file Chest.cs.
        {
            Chest chest;
            if (!Chest._chestsByCoords.TryGetValue(new Point(X, Y), out chest))
            {
                return true;
            }
            for (int i = 0; i < chest.maxItems; i++)
            {
                if (chest.item[i] != null && chest.item[i].type > 0 && chest.item[i].stack > 0)
                {
                    return false;
                }
            }
            int num = chest.index;
            Chest.RemoveChest(num);
            if (Main.player[Main.myPlayer].chest == num)
            {
                Main.player[Main.myPlayer].chest = -1;
            }
            return true;
        }
References Terraria.Chest._chestsByCoords, Terraria.Player.chest, Terraria.Chest.index, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Chest.RemoveChest(), Terraria.Item.stack, Terraria.Item.type, System.X, and System.Y.
Referenced by Terraria.NPC.BigMimicSummonCheck(), Terraria.WorldGen.CheckChest(), and Terraria.WorldGen.CheckTileBreakability2_ShouldTileSurvive().