Terraria Decompiled: Terraria.Chest.NearOtherChests
NearOtherChests()
static bool Terraria.Chest.NearOtherChests (int x, int y) inline static
Definition at line 478 of file Chest.cs.
        {
            for (int i = x - 25; i < x + 25; i++)
            {
                for (int j = y - 8; j < y + 8; j++)
                {
                    Tile tileSafely = Framing.GetTileSafely(i, j);
                    if (tileSafely.active() && TileID.Sets.BasicChest[(int)tileSafely.type])
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.Framing.GetTileSafely(), Terraria.Tile.type, Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.WorldGen.PlaceChest().