Terraria Decompiled: Terraria.Chest.AddItemToShop
AddItemToShop()
void Terraria.Chest.AddItemToShop (Item newItem) inline
Definition at line 613 of file Chest.cs.
        {
            int num = Main.shopSellbackHelper.Remove(newItem);
            if (num >= newItem.stack)
            {
                return;
            }
            for (int i = 0; i < 39; i++)
            {
                if (this.item[i] == null || this.item[i].type == 0)
                {
                    this.item[i] = newItem.Clone();
                    this.item[i].favorited = false;
                    this.item[i].buyOnce = true;
                    this.item[i].stack -= num;
                    int value = this.item[i].value;
                    return;
                }
            }
        }
References Terraria.Item.buyOnce, Terraria.Item.Clone(), Terraria.Item.favorited, Terraria.Chest.item, Terraria.GameContent.ItemShopSellbackHelper.Remove(), Terraria.Main.shopSellbackHelper, Terraria.Item.stack, System.value, and Terraria.Item.value.
Referenced by Terraria.UI.ItemSlot.LeftClick(), and Terraria.UI.ItemSlot.OverrideLeftClick().