Terraria Decompiled: System.Environment.GetResourceString
GetResourceString() [1/3]
static string System.Environment.GetResourceString (string key) inline static package
Definition at line 23 of file Environment.cs.
        {
            return key;
        }
References System.key.
Referenced by System.Resources.ResourceReader._LoadObjectV2(), System.Resources.ResourceReader._ReadResources(), System.Globalization.Calendar.Add(), System.Collections.EmptyReadOnlyDictionaryInternal.Add(), System.GC.AddMemoryPressure(), System.Globalization.EastAsianLunisolarCalendar.AddMonths(), System.Globalization.GregorianCalendar.AddMonths(), System.Globalization.GregorianCalendarHelper.AddMonths(), System.Globalization.HebrewCalendar.AddMonths(), System.Globalization.HijriCalendar.AddMonths(), System.Globalization.JulianCalendar.AddMonths(), System.Globalization.PersianCalendar.AddMonths(), System.Globalization.UmAlQuraCalendar.AddMonths(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResource(), System.Resources.ResourceWriter.AddResourceData(), System.Resources.ResourceWriter.AddResourceInternal(), System.Runtime.Serialization.SafeSerializationEventArgs.AddSerializedState(), System.Runtime.Serialization.SerializationInfo.AddValueInternal(), System.Resources.ResourceReader.AllocateStringForNameIndex(), System.Diagnostics.Contracts.Contract.AssertMustUseRewriter(), System.IO.BinaryReader.BinaryReader(), System.IO.BinaryWriter.BinaryWriter(), System.DefaultBinder.BindToField(), System.DefaultBinder.BindToMethod(), System.GC.CancelFullGCNotification(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture(), System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup(), System.Runtime.Serialization.SurrogateSelector.ChainSelector(), System.Threading.Timer.Change(), System.DefaultBinder.ChangeType(), System.Globalization.Calendar.CheckAddResult(), System.Reflection.RuntimeFieldInfo.CheckConsistency(), System.Globalization.JulianCalendar.CheckDayRange(), System.Globalization.CultureInfo.CheckDomainSafetyObject(), System.Globalization.EastAsianLunisolarCalendar.CheckEraRange(), System.Globalization.HebrewCalendar.CheckEraRange(), System.Globalization.HijriCalendar.CheckEraRange(), System.Globalization.JulianCalendar.CheckEraRange(), System.Globalization.PersianCalendar.CheckEraRange(), System.Globalization.UmAlQuraCalendar.CheckEraRange(), System.Globalization.NumberFormatInfo.CheckGroupSize(), System.Globalization.HebrewCalendar.CheckHebrewDayValue(), System.Globalization.HebrewCalendar.CheckHebrewMonthValue(), System.Globalization.HebrewCalendar.CheckHebrewYearValue(), System.IO.Path.CheckInvalidPathChars(), System.Globalization.JulianCalendar.CheckMonthRange(), System.IO.Path.CheckSearchPattern(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSecurity(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.CheckSerializable(), System.Globalization.EastAsianLunisolarCalendar.CheckTicksRange(), System.Globalization.GregorianCalendarHelper.CheckTicksRange(), System.Globalization.HebrewCalendar.CheckTicksRange(), System.Globalization.HijriCalendar.CheckTicksRange(), System.Globalization.PersianCalendar.CheckTicksRange(), System.Globalization.UmAlQuraCalendar.CheckTicksRange(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom(), System.Runtime.Serialization.FormatterServices.CheckTypeSecurity(), System.RuntimeType.CheckValue(), System.Globalization.JulianCalendar.CheckYearEraRange(), System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange(), System.Globalization.HijriCalendar.CheckYearMonthRange(), System.Globalization.PersianCalendar.CheckYearMonthRange(), System.Globalization.UmAlQuraCalendar.CheckYearMonthRange(), System.Globalization.EastAsianLunisolarCalendar.CheckYearRange(), System.Globalization.HijriCalendar.CheckYearRange(), System.Globalization.PersianCalendar.CheckYearRange(), System.Globalization.UmAlQuraCalendar.CheckYearRange(), System.Security.Claims.ClaimsIdentity.ClaimsIdentity(), System.Collections.EmptyReadOnlyDictionaryInternal.Clear(), System.Security.Claims.ClaimsIdentity.Clone(), System.GC.Collect(), System.GC.CollectionCount(), System.Resources.ResourceReader.CompareStringEqualsName(), System.Enum.CompareTo(), System.Runtime.Serialization.ObjectManager.CompleteISerializableObject(), System.Runtime.Serialization.ObjectManager.CompleteObject(), System.Threading.SpinLock.ContinueTryEnter(), System.Threading.SpinLock.ContinueTryEnterWithThreadTracking(), System.Text.Encoding.Convert(), System.Security.Util.Hex.ConvertHexDigit(), System.Reflection.RuntimeMethodInfo.ConvertValues(), System.Collections.EmptyReadOnlyDictionaryInternal.CopyTo(), System.Reflection.RuntimeAssembly.CreateAssemblyName(), System.Activator.CreateComInstanceFrom(), System.Threading.ExecutionContext.CreateCopy(), System.Security.Cryptography.DESCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateDecryptor(), System.Security.Cryptography.DESCryptoServiceProvider.CreateEncryptor(), System.Security.Cryptography.TripleDESCryptoServiceProvider.CreateEncryptor(), System.Activator.CreateInstance(), System.Activator.CreateInstance(), System.Activator.CreateInstance< T >(), System.RuntimeType.CreateInstanceCheckThis(), System.RuntimeType.CreateInstanceDefaultCtor(), System.RuntimeType.CreateInstanceImpl(), System.RuntimeType.CreateInstanceMono(), System.Security.Cryptography.RSAOAEPKeyExchangeFormatter.CreateKeyExchange(), System.Security.Cryptography.RSAPKCS1KeyExchangeFormatter.CreateKeyExchange(), System.Threading.ThreadLocal< T >.CreateLinkedSlot(), System.Security.Cryptography.RSAEncryptionPadding.CreateOaep(), System.Resources.ManifestBasedResourceGroveler.CreateResourceSet(), System.Resources.FileBasedResourceGroveler.CreateResourceSet(), System.Security.Cryptography.DSASignatureFormatter.CreateSignature(), System.Security.Cryptography.PasswordDeriveBytes.CryptDeriveKey(), System.Security.Util.Hex.DecodeHexString(), System.Security.Cryptography.RSACryptoServiceProvider.Decrypt(), System.Security.Cryptography.RijndaelManagedTransform.DecryptData(), System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter.DecryptKeyExchange(), System.Security.Cryptography.RSAPKCS1KeyExchangeDeformatter.DecryptKeyExchange(), System.Security.Cryptography.RSA.DecryptValue(), System.Security.Cryptography.DSA.DerivedClassMustOverride(), System.Security.Cryptography.RSA.DerivedClassMustOverride(), System.Security.Cryptography.DESCryptoServiceProvider.DESCryptoServiceProvider(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Security.Claims.ClaimsPrincipal.DeserializeIdentities(), System.Resources.ResourceReader.DeserializeObject(), System.Security.Util.Parser.DetermineFormat(), System.Runtime.Serialization.ObjectManager.DoFixups(), System.Text.Encoding.EncodingByteBuffer.EncodingByteBuffer(), System.Security.Cryptography.RijndaelManagedTransform.EncryptData(), System.Security.Cryptography.RSA.EncryptValue(), System.IO.__Error.EndOfFile(), System.IO.__Error.EndReadCalledTwice(), System.IO.__Error.EndWriteCalledTwice(), System.Runtime.Serialization.FixupHolderList.EnlargeArray(), System.Runtime.Serialization.LongList.EnlargeArray(), System.Runtime.Serialization.ObjectHolderList.EnlargeArray(), System.Security.Cryptography.TripleDES.EqualBytes(), System.TypedReference.Equals(), System.Runtime.InteropServices.WindowsRuntime.EventRegistrationTokenTable< T >.EventRegistrationTokenTable(), System.Threading.EventWaitHandle.EventWaitHandle(), System.Threading.EventWaitHandle.EventWaitHandle(), System.DefaultBinder.ExactPropertyBinding(), System.Exception.Exception(), System.Reflection.Emit.ExceptionHandler.ExceptionHandler(), System.Threading.SpinLock.ExitSlowPath(), System.Diagnostics.Assert.Fail(), System.IO.__Error.FileNotOpen(), System.IO.BinaryReader.FillBuffer(), System.__Filters.FilterAttribute(), System.__Filters.FilterIgnoreCase(), System.__Filters.FilterName(), System.DefaultBinder.FindMostDerivedNewSlotMeth(), System.Resources.ResourceReader.FindPosForResource(), System.Resources.ResourceReader.FindType(), System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup(), System.Runtime.Serialization.ObjectManager.FixupSpecialObject(), System.Enum.Format(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.FreeHString(), System.Security.Cryptography.DSA.FromXmlString(), System.Security.Cryptography.RSA.FromXmlString(), System.Resources.ResourceWriter.Generate(), System.Security.Cryptography.RijndaelManagedTransform.GenerateKeyExpansion(), System.Globalization.GregorianCalendar.GetAbsoluteDate(), System.Globalization.GregorianCalendarHelper.GetAbsoluteDate(), System.Globalization.PersianCalendar.GetAbsoluteDatePersian(), System.Security.Cryptography.RSACryptoServiceProvider.GetAlgorithmId(), System.RuntimeType.GetArrayRank(), System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly(), System.Runtime.Serialization.Formatters.Binary.BinaryConverter.GetBinaryTypeInfo(), System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetByteCount(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Text.Encoding.GetBytes(), System.Resources.ResourceSet.GetCaseInsensitiveObjectInternal(), System.Globalization.EastAsianLunisolarCalendar.GetCelestialStem(), System.Text.Encoding.GetCharCount(), System.Text.Encoding.GetCharCount(), System.Text.Encoding.GetChars(), System.Text.Encoding.GetChars(), System.Runtime.Serialization.ObjectManager.GetCompletionInfo(), System.Threading.Thread.GetCompressedStack(), System.Runtime.Serialization.ObjectManager.GetConstructor(), System.Reflection.Emit.SymbolType.GetConstructorImpl(), System.Reflection.Emit.SymbolType.GetConstructors(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttribute(), System.Attribute.GetCustomAttributes(), System.Reflection.Emit.SymbolType.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Attribute.GetCustomAttributes(), System.Reflection.Emit.SymbolType.GetCustomAttributes(), System.RuntimeType.GetCustomAttributes(), System.LocalDataStore.GetData(), System.Text.Encoding.GetDataItem(), System.Globalization.UmAlQuraCalendar.GetDatePart(), System.Globalization.HijriCalendar.GetDatePart(), System.Globalization.PersianCalendar.GetDatePart(), System.Globalization.GregorianCalendar.GetDaysInMonth(), System.Globalization.GregorianCalendarHelper.GetDaysInMonth(), System.Globalization.HebrewCalendar.GetDaysInMonth(), System.Globalization.GregorianCalendar.GetDaysInYear(), System.IO.__Error.GetDisplayablePath(), System.Runtime.CompilerServices.ContractHelper.GetDisplayMessage(), System.Runtime.Serialization.SerializationInfo.GetElement(), System.Text.Encoding.GetEncoding(), System.Globalization.EncodingTable.GetEncodings(), System.Resources.ResourceReader.GetEnumerator(), System.Resources.ResourceSet.GetEnumeratorHelper(), System.RuntimeType.GetEnumName(), System.RuntimeType.GetEnumNames(), System.Enum.EnumResult.GetEnumParseException(), System.RuntimeType.GetEnumUnderlyingType(), System.RuntimeType.GetEnumValues(), System.Globalization.GregorianCalendarHelper.GetEra(), System.Reflection.Emit.SymbolType.GetEvent(), System.RuntimeType.GetEvent(), System.Reflection.Emit.SymbolType.GetEvents(), System.Reflection.Emit.SymbolType.GetEvents(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.GetExceptionForHR(), System.Reflection.Emit.SymbolType.GetField(), System.RuntimeType.GetField(), System.Reflection.Emit.SymbolType.GetFields(), System.RuntimeType.GetGenericParameterConstraints(), System.RuntimeType.GetGenericTypeDefinition(), System.Globalization.ChineseLunisolarCalendar.GetGregorianYear(), System.Globalization.KoreanLunisolarCalendar.GetGregorianYear(), System.Runtime.Serialization.ObjectIDGenerator.GetId(), System.RuntimeType.GetInterface(), System.Reflection.Emit.SymbolType.GetInterface(), System.RuntimeType.GetInterfaceMap(), System.Reflection.Emit.SymbolType.GetInterfaceMap(), System.Reflection.Emit.SymbolType.GetInterfaces(), System.Globalization.GregorianCalendar.GetLeapMonth(), System.Reflection.Emit.SymbolType.GetMember(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetMemberInfo(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberInfo(), System.Reflection.Emit.SymbolType.GetMembers(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberType(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetMemberType(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberTypes(), System.Reflection.MethodBase.GetMethodFromHandle(), System.Reflection.MethodBase.GetMethodFromHandle(), System.Reflection.Emit.SymbolType.GetMethodImpl(), System.Reflection.Emit.SymbolType.GetMethods(), System.Globalization.GregorianCalendar.GetMonthsInYear(), System.Resources.ResourceReader.GetNamePosition(), System.RuntimeType.GetNestedType(), System.Reflection.Emit.SymbolType.GetNestedType(), System.Reflection.Emit.SymbolType.GetNestedTypes(), System.Resources.ManifestBasedResourceGroveler.GetNeutralResourcesLanguage(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetNext(), System.Globalization.StringInfo.GetNextTextElement(), System.Runtime.Serialization.ObjectManager.GetObject(), System.Runtime.Serialization.FormatterServices.GetObjectData(), System.Runtime.Serialization.ObjectCloneHelper.GetObjectData(), System.Reflection.MemberInfoSerializationHolder.GetObjectData(), System.UnitySerializationHolder.GetObjectData(), System.Resources.ResourceSet.GetObjectInternal(), System.Reflection.Emit.SymbolType.GetProperties(), System.Reflection.Emit.SymbolType.GetPropertyImpl(), System.RuntimeType.GetPropertyImpl(), System.Reflection.MemberInfoSerializationHolder.GetRealObject(), System.UnitySerializationHolder.GetRealObject(), System.Security.Util.Parser.GetRequiredSizes(), System.Runtime.Versioning.VersioningHelper.GetRequirements(), System.Resources.ResourceReader.GetResourceData(), System.Threading.SemaphoreSlim.GetResourceString(), System.Environment.GetResourceStringEncodingName(), System.Globalization.HebrewCalendar.GetResult(), System.Runtime.Serialization.FormatterServices.GetSafeUninitializedObject(), System.Resources.ResourceManager.GetSatelliteContractVersion(), System.Runtime.Serialization.FormatterServices.GetSerializableMembers(), System.Resources.ResourceManager.GetStream(), System.Text.Encoding.GetString(), System.Text.Encoding.GetString(), System.Resources.ResourceSet.GetString(), System.Resources.ResourceSet.GetString(), System.Globalization.EastAsianLunisolarCalendar.GetTerrestrialBranch(), System.Globalization.TextElementEnumerator.GetTextElement(), System.Globalization.StringInfo.GetTextElementEnumerator(), System.Security.Util.Tokenizer.GetTokens(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetType(), System.Enum.GetTypeCode(), System.Runtime.Serialization.FormatterServices.GetUninitializedObject(), System.Runtime.Serialization.SerializationInfo.GetValue(), System.Reflection.RuntimeFieldInfo.GetValueDirect(), System.Resources.ResourceReader.GetValueForNameIndex(), System.Threading.ThreadLocal< T >.GetValueSlow(), System.Globalization.Calendar.GetWeekOfYear(), System.Globalization.GregorianCalendarHelper.GetYear(), System.Globalization.GregorianCalendarHelper.GetYear(), System.Globalization.ChineseLunisolarCalendar.GetYearInfo(), System.Globalization.JapaneseLunisolarCalendar.GetYearInfo(), System.Globalization.KoreanLunisolarCalendar.GetYearInfo(), System.Globalization.TaiwanLunisolarCalendar.GetYearInfo(), System.Globalization.GregorianCalendar.GregorianCalendar(), System.Resources.FileBasedResourceGroveler.GrovelForResourceSet(), System.Resources.ManifestBasedResourceGroveler.HandleResourceStreamMissing(), System.Resources.ManifestBasedResourceGroveler.HandleSatelliteMissing(), System.Enum.HasFlag(), System.Security.Cryptography.DSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.RSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.DSACryptoServiceProvider.HashData(), System.Security.Cryptography.DSACryptoServiceProvider.HashData(), System.Security.Cryptography.PasswordDeriveBytes.HashPrefix(), System.Runtime.Serialization.ObjectIDGenerator.HasId(), System.Runtime.Serialization.Formatters.Binary.IntSizedArray.IncreaseCapacity(), System.Runtime.Serialization.Formatters.Binary.SizedArray.IncreaseCapacity(), System.Collections.Generic.ByteEqualityComparer.IndexOf(), System.IO.FileStream.Init(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(), System.IO.Path.InternalCombine(), System.Enum.InternalFormattedHexString(), System.Globalization.EncodingTable.internalGetCodePageFromName(), System.Runtime.Serialization.FormatterServices.InternalGetSerializableMembers(), System.Threading.WaitHandle.InternalWaitOne(), System.RuntimeType.InvokeMember(), System.Reflection.Emit.SymbolType.InvokeMember(), System.Attribute.IsDefined(), System.Attribute.IsDefined(), System.Attribute.IsDefined(), System.Attribute.IsDefined(), System.Reflection.Emit.SymbolType.IsDefined(), System.RuntimeType.IsDefined(), System.RuntimeType.IsEnumDefined(), System.Globalization.EastAsianLunisolarCalendar.IsLeapDay(), System.Globalization.GregorianCalendar.IsLeapDay(), System.Globalization.GregorianCalendarHelper.IsLeapDay(), System.Globalization.HijriCalendar.IsLeapDay(), System.Globalization.PersianCalendar.IsLeapDay(), System.Globalization.UmAlQuraCalendar.IsLeapDay(), System.Globalization.GregorianCalendar.IsLeapMonth(), System.Globalization.GregorianCalendarHelper.IsLeapMonth(), System.Globalization.GregorianCalendar.IsLeapYear(), System.Security.Cryptography.DES.IsSemiWeakKey(), System.Security.Cryptography.DES.IsWeakKey(), System.Security.Cryptography.TripleDES.IsWeakKey(), System.Threading.Thread.Join(), System.Threading.Thread.Join(), System.Resources.ResourceReader.LoadObjectV1(), System.Resources.ResourceReader.LoadObjectV2(), System.Resources.ResourceReader.LoadString(), System.RuntimeType.MakeGenericType(), System.Reflection.Emit.GenericTypeParameterBuilder.MakeGenericType(), System.TypedReference.MakeTypedReference(), System.Runtime.Versioning.VersioningHelper.MakeVersionSafeName(), System.Globalization.EastAsianLunisolarCalendar.MaxEraCalendarYear(), System.Reflection.MemberInfoSerializationHolder.MemberInfoSerializationHolder(), System.IO.__Error.MemoryStreamNotExpandable(), System.Threading.Monitor.MillisecondsTimeoutFromTimeSpan(), System.Globalization.EastAsianLunisolarCalendar.MinEraCalendarYear(), System.Runtime.Serialization.ObjectHolder.ObjectHolder(), System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ObjectReader(), System.Threading.ExecutionContext.OnAsyncLocalContextChanged(), System.Globalization.GregorianCalendar.OnDeserialized(), System.Threading.EventWaitHandle.OpenExisting(), System.Threading.EventWaitHandle.OpenExistingWorker(), System.Security.Cryptography.RSACryptoServiceProvider.PaddingModeNotSupported(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArray(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseArrayMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseError(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseObject(), System.LocalDataStore.PopulateElement(), System.Runtime.Serialization.FormatterServices.PopulateObjectMembers(), System.Runtime.Serialization.ObjectCloneHelper.PrepareConstructorArgs(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.PtrToStringHString(), System.Runtime.CompilerServices.ContractHelper.RaiseContractFailedEventImplementation(), System.Security.Cryptography.RC2CryptoServiceProvider.RC2CryptoServiceProvider(), System.IO.StringReader.Read(), System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read(), System.IO.BinaryReader.Read(), System.Security.Cryptography.TailStream.Read(), System.IO.BinaryReader.Read(), System.IO.BinaryReader.Read7BitEncodedInt(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.ReadArray(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadAssembly(), System.IO.StringReader.ReadAsync(), System.IO.StringReader.ReadBlockAsync(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadChars(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadCrossAppDomainMap(), System.IO.BinaryReader.ReadDecimal(), System.IO.__Error.ReaderClosed(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMessageEnd(), System.IO.__Error.ReadNotSupported(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(), System.Resources.ResourceReader.ReadResources(), System.IO.BinaryReader.ReadString(), System.Runtime.Serialization.Formatters.Binary.BinaryConverter.ReadTypeInfo(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadValue(), System.Runtime.Serialization.ObjectManager.RecordArrayElementFixup(), System.Runtime.Serialization.ObjectManager.RecordDelayedFixup(), System.Runtime.Serialization.ObjectManager.RecordFixup(), System.Runtime.Serialization.ObjectManager.RegisterFixup(), System.GC.RegisterForFullGCNotification(), System.Runtime.Serialization.ObjectManager.RegisterObject(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), System.Runtime.Serialization.ObjectIDGenerator.Rehash(), System.Collections.EmptyReadOnlyDictionaryInternal.Remove(), System.Security.Claims.ClaimsIdentity.RemoveClaim(), System.GC.RemoveMemoryPressure(), System.Diagnostics.Contracts.Contract.ReportFailure(), System.Resources.ResourceReader.ResourceEnumerator.Reset(), System.Threading.Thread.ResetAbort(), System.Runtime.Serialization.ObjectManager.ResolveObjectReference(), System.Resources.ResourceManager.ResourceManager(), System.Resources.ResourceManager.ResourceManager(), System.Resources.ResourceManager.ResourceManager(), System.Resources.ResourceReader.ResourceReader(), System.Resources.ResourceWriter.ResourceWriter(), System.Threading.ExecutionContext.RestoreFlow(), System.Security.Cryptography.RijndaelManaged.RijndaelManaged(), System.Security.Cryptography.RijndaelManagedTransform.RijndaelManagedTransform(), System.Security.Cryptography.RIPEMD160Managed.RIPEMD160Managed(), System.Security.Cryptography.Utils.RsaOaepDecrypt(), System.Security.Cryptography.Utils.RsaPkcs1Padding(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run(), System.Threading.ExecutionContext.Run(), System.RuntimeType.SanityCheckGenericArguments(), System.Security.Cryptography.TailStream.Seek(), System.IO.__Error.SeekNotSupported(), System.DefaultBinder.SelectProperty(), System.Runtime.Serialization.FormatterServices.SerializationSetValue(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Serialize(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), System.Threading.Thread.SetCompressedStack(), System.LocalDataStore.SetData(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetException(), System.Security.Cryptography.DSASignatureDeformatter.SetHashAlgorithm(), System.Security.Cryptography.DSASignatureFormatter.SetHashAlgorithm(), System.Security.Cryptography.TailStream.SetLength(), System.TypeLoadException.SetMessageField(), System.Runtime.CompilerServices.AsyncTaskMethodBuilder< TResult >.SetResult(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.SetStateMachine(), System.AppContext.SetSwitch(), System.Reflection.RuntimeFieldInfo.SetValueDirect(), System.Threading.ThreadLocal< T >.SetValueSlow(), System.Security.Cryptography.SHA1Managed.SHA1Managed(), System.Security.Cryptography.SHA256Managed.SHA256Managed(), System.Security.Cryptography.SHA384Managed.SHA384Managed(), System.Security.Cryptography.SHA512Managed.SHA512Managed(), System.Threading.WaitHandle.SignalAndWait(), System.Threading.WaitHandle.SignalAndWait(), System.Resources.ResourceReader.SkipString(), System.Threading.Thread.Sleep(), System.Threading.Thread.Sleep(), System.Threading.Thread.Start(), System.IO.__Error.StreamIsClosed(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.StringToHString(), System.IO.StringWriter.StringWriter(), System.Globalization.StringInfo.SubstringByTextElements(), System.Globalization.StringInfo.SubstringByTextElements(), System.Threading.ExecutionContext.SuppressFlow(), System.Threading.Thread.Thread(), System.Threading.Thread.Thread(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentException(), System.ThrowHelper.ThrowArgumentOutOfRangeException(), System.Text.Encoding.ThrowBytesOverflow(), System.Text.Encoding.ThrowCharsOverflow(), System.RuntimeType.ThrowIfTypeNeverValidGenericArgument(), System.UnitySerializationHolder.ThrowInsufficientInformation(), System.ThrowHelper.ThrowInvalidOperationException(), System.Threading.Monitor.ThrowLockTakenException(), System.ThrowHelper.ThrowNotSupportedException(), System.ThrowHelper.ThrowObjectDisposedException(), System.ThrowHelper.ThrowSecurityException(), System.ThrowHelper.ThrowSerializationException(), System.ThrowHelper.ThrowUnauthorizedAccessException(), System.ThrowHelper.ThrowWrongKeyTypeArgumentException(), System.ThrowHelper.ThrowWrongValueTypeArgumentException(), System.Globalization.Calendar.TimeToTicks(), System.Globalization.GregorianCalendarHelper.TimeToTicks(), System.Enum.ToDateTime(), System.Globalization.EastAsianLunisolarCalendar.ToDateTime(), System.Globalization.GregorianCalendar.ToDateTime(), System.Globalization.HijriCalendar.ToDateTime(), System.Globalization.JulianCalendar.ToDateTime(), System.Globalization.PersianCalendar.ToDateTime(), System.Globalization.UmAlQuraCalendar.ToDateTime(), System.Globalization.Calendar.ToFourDigitYear(), System.Globalization.EastAsianLunisolarCalendar.ToFourDigitYear(), System.Globalization.GregorianCalendar.ToFourDigitYear(), System.Globalization.HebrewCalendar.ToFourDigitYear(), System.Globalization.HijriCalendar.ToFourDigitYear(), System.Globalization.JapaneseCalendar.ToFourDigitYear(), System.Globalization.JulianCalendar.ToFourDigitYear(), System.Globalization.KoreanCalendar.ToFourDigitYear(), System.Globalization.PersianCalendar.ToFourDigitYear(), System.Globalization.TaiwanCalendar.ToFourDigitYear(), System.Globalization.ThaiBuddhistCalendar.ToFourDigitYear(), System.Globalization.UmAlQuraCalendar.ToFourDigitYear(), System.Globalization.GregorianCalendarHelper.ToFourDigitYear(), System.Security.Util.Tokenizer.Tokenizer(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Enum.ToObject(), System.Exception.ToString(), System.Enum.ToString(), System.Enum.ToUInt64(), System.Security.Cryptography.FromBase64Transform.TransformBlock(), System.Security.Cryptography.RijndaelManagedTransform.TransformBlock(), System.Security.Cryptography.ToBase64Transform.TransformBlock(), System.Security.Cryptography.FromBase64Transform.TransformFinalBlock(), System.Security.Cryptography.RijndaelManagedTransform.TransformFinalBlock(), System.Security.Cryptography.ToBase64Transform.TransformFinalBlock(), System.Runtime.CompilerServices.ContractHelper.TriggerFailureImplementation(), System.Security.Cryptography.TripleDESCryptoServiceProvider.TripleDESCryptoServiceProvider(), System.Threading.SpinLock.TryEnter(), System.AppContext.TryGetSwitch(), System.Enum.TryParseEnum(), System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo(), System.Threading.AsyncFlowControl.Undo(), System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject(), System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject(), System.Threading.ThreadPool.UnsafeRegisterWaitForSingleObject(), System.Runtime.Serialization.ObjectHolder.UpdateData(), System.Globalization.NumberFormatInfo.ValidateParseStyleFloatingPoint(), System.Globalization.NumberFormatInfo.ValidateParseStyleInteger(), System.LocalDataStoreMgr.ValidateSlot(), System.Globalization.TimeSpanParse.ValidateStyles(), System.Globalization.CultureInfo.VerifyCultureName(), System.Globalization.NumberFormatInfo.VerifyDecimalSeparator(), System.Globalization.NumberFormatInfo.VerifyDigitSubstitution(), System.Globalization.NumberFormatInfo.VerifyGroupSeparator(), System.Globalization.NumberFormatInfo.VerifyNativeDigits(), System.Security.Cryptography.DSASignatureDeformatter.VerifySignature(), System.Globalization.Calendar.VerifyWritable(), System.Globalization.NumberFormatInfo.VerifyWritable(), System.Globalization.TextInfo.VerifyWritable(), System.Threading.WaitHandle.WaitAll(), System.Threading.WaitHandle.WaitAll(), System.Threading.WaitHandle.WaitAny(), System.Threading.WaitHandle.WaitAny(), System.GC.WaitForFullGCApproach(), System.GC.WaitForFullGCComplete(), System.Threading.WaitHandle.WaitOne(), System.Threading.WaitHandle.WaitOne(), System.Threading.WaitHandle.WaitOneWithoutFAS(), System.IO.__Error.WinIOError(), System.IO.BinaryWriter.Write(), System.IO.StringWriter.Write(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.Write(), System.IO.__Error.WriteNotSupported(), System.IO.__Error.WriterClosed(), System.Runtime.Serialization.Formatters.Binary.BinaryConverter.WriteTypeInfo(), System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteValue(), System.Resources.ResourceWriter.WriteValue(), and System.IO.__Error.WrongAsyncResult().