Terraria Decompiled: Terraria.Utils.DrawBorderString
DrawBorderString()
static Vector2 Terraria.Utils.DrawBorderString (SpriteBatch sb, string text, Vector2 pos, Color color, float scale = 1f, float anchorx = 0f, float anchory = 0f, int maxCharactersDisplayed = -1) inline static
Definition at line 2576 of file Utils.cs.
        {
            if (maxCharactersDisplayed != -1)
            {
                text = Utils.TrimUserString(text, maxCharactersDisplayed);
            }
            DynamicSpriteFont value = FontAssets.MouseText.Value;
            Vector2 vector = value.MeasureString(text);
            ChatManager.DrawColorCodedStringWithShadow(sb, value, text, pos, color, 0f, new Vector2(anchorx, anchory) * vector, new Vector2(scale), -1f, 1.5f);
            return vector * scale;
        }
References Terraria.UI.Chat.ChatManager.DrawColorCodedStringWithShadow(), Terraria.GameContent.FontAssets.MouseText, System.text, Terraria.Utils.TrimUserString(), System.value, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.IngameOptions.Draw(), Terraria.UI.NetDiagnosticsUI.Draw(), Terraria.Main.DrawIMEPanel(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInvasionProgress(), Terraria.IngameOptions.DrawRightSide(), Terraria.GameContent.UI.Elements.UIBestiaryInfoLine< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.TimeLogger.DrawString(), Terraria.GameContent.UI.Elements.UITextPanel< T >.DrawText(), Terraria.IngameOptions.DrawValue(), and Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget().