Terraria Decompiled: Terraria.Utils.TryOperateInLock
TryOperateInLock()
static bool Terraria.Utils.TryOperateInLock (object _lock, Action action) inline static
Definition at line 2891 of file Utils.cs.
        {
            if (!Monitor.TryEnter(_lock))
            {
                return false;
            }
            bool flag;
            try
            {
                action();
                flag = true;
            }
            finally
            {
                Monitor.Exit(_lock);
            }
            return flag;
        }
References System.action, System.Threading.Monitor.Exit(), and System.Threading.Monitor.TryEnter().
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.DeleteSnapshot(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.Disable(), Terraria.GameContent.UI.States.UIWorldGenDebug.GenPassElement.Enable(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryOperateInControlLock().