Terraria Decompiled: Terraria.Utils.PlotLine
PlotLine() [3/3]
static bool Terraria.Utils.PlotLine (Point16 p0, Point16 p1, Utils::TileActionAttempt plot, bool jump = true) inline static
Definition at line 2286 of file Utils.cs.
        {
            return Utils.PlotLine((int)p0.X, (int)p0.Y, (int)p1.X, (int)p1.Y, plot, jump);
        }
References Terraria.Utils.PlotLine(), Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.Projectile.DoLightningKillLambda(), Terraria.GameContent.PortalHelper.FindCollision(), Terraria.GameContent.Biomes.DitherSnake.IsLineInsideBorder(), Terraria.GameContent.Generation.ShapeBranch.PerformSegment(), Terraria.Utils.PlotLine(), Terraria.Utils.PlotLine(), Terraria.Utils.PlotTileLine(), Terraria.Utils.PlotTileTale(), and Terraria.Projectile.StormLightningLiquidCollisionCheck().