Terraria Decompiled: Terraria.Utils.CoinsCount
CoinsCount()
static long Terraria.Utils.CoinsCount (out bool overFlowing, Item[] inv, params int[] ignoreSlots) inline static
Definition at line 975 of file Utils.cs.
        {
            List<int> list = new List<int>(ignoreSlots);
            long num = 0L;
            for (int i = 0; i < inv.Length; i++)
            {
                if (!list.Contains(i))
                {
                    switch (inv[i].type)
                    {
                    case 71:
                        num += (long)inv[i].stack;
                        break;
                    case 72:
                        num += (long)inv[i].stack * 100L;
                        break;
                    case 73:
                        num += (long)inv[i].stack * 10000L;
                        break;
                    case 74:
                        num += (long)inv[i].stack * 1000000L;
                        break;
                    }
                }
            }
            overFlowing = false;
            return num;
        }
References Microsoft.Xna.Framework.Input.L, System.list, long, and System.stack.
Referenced by Terraria.Player.BuyItem(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.Player.KillMe(), Terraria.UI.ChestUI.MoveCoins(), Terraria.UI.ItemSorting.SortCoins(), and Terraria.Wiring.TryMoveCoinsInChest().