Terraria Decompiled: Terraria.Utils.ReadEmbeddedResource
ReadEmbeddedResource()
static string Terraria.Utils.ReadEmbeddedResource (string path) inline static
Definition at line 2647 of file Utils.cs.
        {
            string text;
            using (Stream manifestResourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(path))
            {
                using (StreamReader streamReader = new StreamReader(manifestResourceStream))
                {
                    text = streamReader.ReadToEnd();
                }
            }
            return text;
        }
References System.Reflection.Assembly.GetExecutingAssembly(), System.Reflection.Assembly.GetManifestResourceStream(), System.IO.StreamReader.ReadToEnd(), and System.text.
Referenced by Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Initialize(), Terraria.Localization.LanguageManager.LoadFilesForCulture(), and Terraria.GameContent.VanillaContentValidator.VanillaContentValidator().