Terraria Decompiled: Terraria.Utils.GetChaseResults
GetChaseResults()
static Utils.ChaseResults Terraria.Utils.GetChaseResults (Vector2 chaserPosition, float chaserSpeed, Vector2 runnerPosition, Vector2 runnerVelocity) inline static
Definition at line 573 of file Utils.cs.
        {
            Utils.ChaseResults chaseResults = default(Utils.ChaseResults);
            if (chaserPosition == runnerPosition)
            {
                return new Utils.ChaseResults
                {
                    InterceptionHappens = true,
                    InterceptionPosition = chaserPosition,
                    InterceptionTime = 0f,
                    ChaserVelocity = Vector2.Zero
                };
            }
            if (chaserSpeed <= 0f)
            {
                return default(Utils.ChaseResults);
            }
            Vector2 vector = chaserPosition - runnerPosition;
            float num = vector.Length();
            float num2 = runnerVelocity.Length();
            if (num2 == 0f)
            {
                chaseResults.InterceptionTime = num / chaserSpeed;
                chaseResults.InterceptionPosition = runnerPosition;
            }
            else
            {
                float num3 = chaserSpeed * chaserSpeed - num2 * num2;
                float num4 = 2f * Vector2.Dot(vector, runnerVelocity);
                float num5 = -num * num;
                float num6;
                float num7;
                if (!Utils.SolveQuadratic(num3, num4, num5, out num6, out num7))
                {
                    return default(Utils.ChaseResults);
                }
                if (num6 < 0f && num7 < 0f)
                {
                    return default(Utils.ChaseResults);
                }
                if (num6 > 0f && num7 > 0f)
                {
                    chaseResults.InterceptionTime = Math.Min(num6, num7);
                }
                else
                {
                    chaseResults.InterceptionTime = Math.Max(num6, num7);
                }
                chaseResults.InterceptionPosition = runnerPosition + runnerVelocity * chaseResults.InterceptionTime;
            }
            chaseResults.ChaserVelocity = (chaseResults.InterceptionPosition - chaserPosition) / chaseResults.InterceptionTime;
            chaseResults.InterceptionHappens = true;
            return chaseResults;
        }
References Microsoft.Xna.Framework.Vector2.Dot(), Terraria.Utils.ChaseResults.InterceptionTime, Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), System.Math.Min(), and Terraria.Utils.SolveQuadratic().
Referenced by Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_066_TryInterceptingTarget(), Terraria.Projectile.AI_067_FreakingPirates_TryJumpingToTarget(), Terraria.Player.OnHit(), and Terraria.Projectile.RainbowBoulder_JumpToPosition().