Terraria Decompiled: Terraria.Utils.CenteredRectangle
CenteredRectangle() [2/2]
static Rectangle Terraria.Utils.CenteredRectangle (Vector2 center, Vector2 size) inline static
Definition at line 905 of file Utils.cs.
        {
            return new Rectangle((int)(center.X - size.X / 2f), (int)(center.Y - size.Y / 2f), (int)size.X, (int)size.Y);
        }
References Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_019_Spears_GetExtensionHitbox(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_150_GolfClubHelper(), Terraria.Projectile.AI_151_SuperStar(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.NPC.AnyoneNearCultists(), Terraria.Map.MapHelper.CaptureSceneState(), Terraria.WorldGen.CheckForHousesNearAPlayer(), Terraria.GameContent.CoinLossRevengeSystem.CheckRespawns(), Terraria.Projectile.Colliding(), Terraria.GameContent.TeleportPylonsSystem.DoesPositionHaveEnoughNPCs(), Terraria.Player.DoGlassSlipperSparkles(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawBareBonesBar(), Terraria.Main.DrawBuilderAccToggles(), Terraria.Main.DrawDefenseCounter(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawExplosions(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInvasionProgress(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.DrawMapIcon(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), Terraria.Main.DrawNPCPortrait(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawPieces(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_07_LeinforsHairShampoo(), Terraria.Main.DrawProjDirect(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Projectile.HallowBossPelletStormInfo.GetBulletHitbox(), Terraria.IngameOptions.GetExpectedRectangleForNotification(), Terraria.NPC.GetMeleeCollisionData(), Terraria.GameContent.EmergencyStacking.GetPlayerViewRects(), Terraria.Player.GetSparkleGuitarTarget(), Terraria.NPC.Spawner.GetSpawnArea(), Terraria.Projectile.GetStormLightningExplosionRect(), Terraria.Wiring.Hopper(), Terraria.Main.HoverOverNPCs(), Terraria.Player.LimitPointToPlayerReachableArea(), Terraria.Player.MowTheLawn(), Terraria.DataStructures.MultiPointHitbox.MultiPointHitbox(), Terraria.Projectile.RainbowBoulder_GetAreas(), Terraria.Projectile.RainbowBoulder_HighlightNearbyTreasure(), Terraria.Projectile.RainbowBoulder_PreventSpam(), Terraria.GameInput.LockOnHelper.RefreshTargets(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.RevengeMarker(), Terraria.SceneMetrics.ScanNPCPositions(), Terraria.GameContent.Drawing.WindGrid.ScanPlayer(), Terraria.SceneMetrics.ScanTiles(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_RainbowBoulder4(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPC(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_ShimmerTownNPCSend(), Terraria.WorldGen.SpawnStormLightning(), Terraria.WorldGen.SpawnStormLightningNearPlayer(), Terraria.Projectile.StatusNPC(), Terraria.GameContent.ObjectInteractions.PotionOfReturnHelper.TryGetGateHitbox(), Terraria.Mount.TryPettingMount(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Update(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap(), Terraria.Projectile.UpdateEnchantmentVisuals(), Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility(), and Terraria.Player.WingFrame().