Terraria Decompiled: Terraria.Utils.Clamp
Clamp()
static Rectangle Terraria.Utils.Clamp (Rectangle r, Rectangle bounds) inline static
Definition at line 141 of file Utils.cs.
        {
            return new Rectangle(Utils.Clamp<int>(r.X, bounds.Left, bounds.Right - r.Width), Utils.Clamp<int>(r.Y, bounds.Top, bounds.Bottom - r.Height), r.Width, r.Height);
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Left, Microsoft.Xna.Framework.Rectangle.Right, Microsoft.Xna.Framework.Rectangle.Top, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Player.AdjustRespawnTimerForWorldJoining(), Terraria.Collision.AdvancedTileCollision(), Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_066_TryInterceptingTarget(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_122_PirateGhost(), Terraria.NPC.AI_126_StatueMimic(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_194_HorsemanPumpkin(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.GameContent.Biomes.JunglePass.ApplyPass(), Terraria.GameContent.Biomes.TerrainPass.ApplyPass(), Terraria.GameContent.Biomes.JunglePass.ApplyRandomMovement(), Terraria.GameContent.Animations.Actions.NPCs.Fade.ApplyTo(), Terraria.SceneState.ApplyVisuals(), Terraria.Collision.BuildTileContacts(), Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot(), Terraria.Utils.Clamp(), Terraria.Utils.ClampedInWorld(), Terraria.DataStructures.ActiveSections.ClampSectionCoords(), Terraria.WorldBuilding.WorldUtils.ClampToWorldBorders(), Terraria.Utils.ClampWithinWorld(), Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd(), Terraria.WorldGen.CountNearBlocksTypes(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Player.Deserialize(), Terraria.WorldGen.digTunnel(), Terraria.GameContent.Generation.ShapeRoot.DoRoot(), Terraria.Main.DoUpdate(), Terraria.Mount.Draw(), Terraria.UI.BannerClaimingUI.DrawBannersGrid(), Terraria.UI.BannerClaimingUI.DrawBannersList_Move(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawNPCPortrait(), Terraria.UI.ChestUI.DrawSlots(), Terraria.Main.DrawSunAndMoon(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.Collision.DrownCollision(), Terraria.WorldGen.FillWallHolesInColumn(), Terraria.GameContent.TeleportHelpers.FindClosestTeleportSpotNoSpace(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.FindRoom(), Terraria.GameContent.UI.Elements.UIBestiaryEntryGrid.FixBestiaryRange(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.Map.MapHelper.GetBackgroundType(), Terraria.UI.UIElement.GetClippingRectangle(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetColor(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Drawing.HorizonHelper.GetMoonColor(), Terraria.Main.GetPlayerControlledCameraPan(), Terraria.Collision.GetTilesIn(), Terraria.Mount.GetWitchBroomTrinketRotation(), Terraria.WorldGen.HasAnyWireNearby(), Terraria.NPC.HaveDryadDoStardewAnimation(), Terraria.Collision.HitLine(), Terraria.Player.IsTileTypeInInteractionRange(), Terraria.Player.ItemCheck(), Terraria.Projectile.KiteLogic(), Terraria.Collision.LavaCollision(), Terraria.GameContent.UI.WiresUI.WiresRadial.LineUpdate(), Terraria.Player.LoadPlayer_LastMinuteFixes(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.UI.BannerClaimingUI.NavigatePipsGrid(), Terraria.UI.BannerClaimingUI.NavigatePipsList(), Terraria.WorldGen.neonMossBiome(), Terraria.Rain.NewRain(), Terraria.WorldGen.NoNearbyAbigailsFlower(), Terraria.WorldGen.NoNearbyChilletEggs(), Terraria.WorldGen.NoNearbyGlowTulips(), Terraria.Collision.noSlopeCollision(), Terraria.WorldGen.oceanCave(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.OffsetResourcePackPriority(), Terraria.WorldGen.OrePatch(), Terraria.GameContent.UI.Chat.ItemTagHandler.Parse(), Terraria.TimeLogger.PerformanceColor(), Terraria.Net.Ping.PingRecieved(), Terraria.GameContent.Biomes.Desert.SandMound.Place(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), Terraria.WorldGen.PlaceUncheckedStalactite(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.plantDye(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.PrepareFields(), Terraria.DataStructures.PlayerIntentionGuesser.PrepareUsageProxy(), Terraria.Graphics.Light.LegacyLighting.PreRenderPhase(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ProvideUIElement(), Terraria.Player.QuickMinecart(), Terraria.Player.RollerSkateMovement(), Terraria.GameContent.Creative.CreativeUI.SacrificeItem(), Terraria.UI.ChestUI.Scroll(), Terraria.GameContent.Bestiary.NPCKillsTracker.SetKillCountDirectly(), Terraria.GameContent.Events.CreditsRollEvent.SetRemainingTimeDirect(), Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.SetSacrificeCountDirectly(), Terraria.WorldGen.ShellPile(), Terraria.Utils.ShiftHue(), Terraria.Projectile.Shimmer(), Terraria.GameContent.Biomes.GraniteBiome.SimulatePressure(), Terraria.WorldGen.SkyblockIsland(), Terraria.Collision.SlopeCollision(), Terraria.GameContent.SmartCursorHelper.SmartCursorLookup(), Terraria.Player.SmartInteractLookup_PrepareCommonlyUsedInfo(), Terraria.GameContent.Biomes.Desert.PitEntrance.SmootherStep(), Terraria.Utils.SmoothStep(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LakeSparkle(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.Player.SpawnHallucination(), Terraria.WorldGen.SpawnStormLightning(), Terraria.WorldGen.StonePatch(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TooManyJunglePlantsNearby(), Terraria.WorldGen.TooManyJungleVinesNearby(), Terraria.Player.TorchAttack(), Terraria.Item.TryAddStack(), Terraria.Main.TryApplyingPlayerStringColor(), Terraria.WorldBuilding.WorldGenerationOptions.TryEnablingFlagFrom(), Terraria.GameContent.Creative.CreativePowerManager.TryListingPermissionsFrom(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Player.TryRecalculatingTorchLuck(), Terraria.Player.TryToPoop(), Terraria.Player.TryToShimmerUnstuck(), Terraria.Graphics.Light.LegacyLighting.TryUpdatingMapWithLight(), Terraria.Map.WorldMap.UnlockMapSection(), Terraria.GameContent.Skies.LanternSky.Update(), Terraria.GameContent.UI.States.UITextWrappingTest.Update(), Terraria.GameContent.Events.ScreenObstruction.Update(), Terraria.Main.UpdateAudio(), Terraria.Player.UpdateBuffs(), Terraria.Main.UpdateCameraPan(), Terraria.Player.UpdateDead(), Terraria.Initializers.ChromaInitializer.UpdateEvents(), Terraria.Player.RabbitOrderFrameHelper.UpdateFrame(), Terraria.Mount.UpdateFrame(), Terraria.Graphics.Light.LegacyLighting.UpdateLightToSkyColor(), Terraria.Player.UpdatePlacementPreview(), Terraria.Player.UpdateSunScorchValues(), Terraria.GameContent.Events.CreditsRollEvent.UpdateTime(), Terraria.Main.UpdateViewZoomKeys(), Terraria.WorldGen.UpdateWorld(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo(), Terraria.Collision.WalkDownSlope(), Terraria.Collision.WaterCollision(), and Terraria.Collision.WetCollision().