Terraria Decompiled: Terraria.Utils.DrawInvBG
DrawInvBG() [3/3]
static void Terraria.Utils.DrawInvBG (SpriteBatch sb, Rectangle R, Color c = default(Color)) inline static
Definition at line 2608 of file Utils.cs.
        {
            Utils.DrawInvBG(sb, R.X, R.Y, R.Width, R.Height, c);
        }
References Terraria.Utils.DrawInvBG(), and Microsoft.Xna.Framework.Input.R.
Referenced by Terraria.GameContent.UI.NPCChatPanel.Draw(), Terraria.IngameOptions.Draw(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.Draw(), Terraria.UI.NetDiagnosticsUI.Draw(), Terraria.Main.DrawClothesWindow(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInNotificationsArea(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInvasionProgress(), Terraria.Utils.DrawInvBG(), Terraria.Utils.DrawInvBG(), Terraria.Main.DrawMouseOver(), and Terraria.Main.MouseText_DrawItemTooltip().