Terraria Decompiled: Terraria.Utils.ConstrainedToPointInRectangle
ConstrainedToPointInRectangle()
static Vector2 Terraria.Utils.ConstrainedToPointInRectangle (Rectangle bounds, Vector2 centerTestPosition) inline static
Definition at line 395 of file Utils.cs.
        {
            if (bounds.Contains(centerTestPosition.ToPoint()))
            {
                return centerTestPosition;
            }
            Vector2 vector = new Vector2((float)bounds.Center.X, (float)bounds.Center.Y);
            Vector2 vector2 = vector - centerTestPosition;
            float num = ((vector2.X == 0f) ? float.MaxValue : Math.Abs((vector.X - (float)(bounds.Width / 2) - centerTestPosition.X) / vector2.X));
            float num2 = ((vector2.Y == 0f) ? float.MaxValue : Math.Abs((vector.Y - (float)(bounds.Height / 2) - centerTestPosition.Y) / vector2.Y));
            float num3 = Math.Min(num, num2);
            Vector2 vector3 = centerTestPosition + vector2 * num3;
            vector3.X = MathHelper.Clamp(vector3.X, (float)bounds.Left, (float)bounds.Right);
            vector3.Y = MathHelper.Clamp(vector3.Y, (float)bounds.Top, (float)bounds.Bottom);
            return vector3;
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Rectangle.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Left, System.Reflection.MaxValue, System.Math.Min(), Microsoft.Xna.Framework.Rectangle.Right, Microsoft.Xna.Framework.Rectangle.Top, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.