Terraria Decompiled: Terraria.Utils.GetLerpValue
GetLerpValue() [2/2]
static float Terraria.Utils.GetLerpValue (float from, float to, float t, bool clamped = false) inline static
Definition at line 228 of file Utils.cs.
        {
            if (clamped)
            {
                if (from < to)
                {
                    if (t < from)
                    {
                        return 0f;
                    }
                    if (t > to)
                    {
                        return 1f;
                    }
                }
                else
                {
                    if (t < to)
                    {
                        return 1f;
                    }
                    if (t > from)
                    {
                        return 0f;
                    }
                }
            }
            return (t - from) / (to - from);
        }
Referenced by Terraria.GameContent.Drawing.NextHorizonRenderer.AdjustIntensity(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_120_HallowBoss_DashTo(), Terraria.NPC.AI_120_HallowBoss_DoMagicEffect(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_161_RapierStabs(), Terraria.Projectile.AI_163_Chum(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_168_FirstFractal(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_171_HallowBossRainbowStreak(), Terraria.Projectile.AI_172_GetPelletStormInfo(), Terraria.Projectile.AI_172_HallowBossRainbowPelletStorm(), Terraria.Projectile.AI_173_GetColor(), Terraria.Projectile.AI_173_HallowBossRainbowTrail(), Terraria.Projectile.AI_179_FairyQueenLance(), Terraria.Projectile.AI_180_FairyQueenSunDance(), Terraria.Projectile.AI_181_FairyQueenRangedItemShot(), Terraria.Projectile.AI_182_FinalFractal(), Terraria.GameContent.Animations.Actions.Players.Fade.ApplyTo(), Terraria.GameContent.Animations.Actions.Sprites.Fade.ApplyTo(), Terraria.SceneState.ApplyVisuals(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.CalculateExpirationTime(), Terraria.GameContent.UI.States.UIManageControls.CreatePanel(), Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.GameContent.Animations.Segments.LocalizedTextSegment.Draw(), Terraria.Graphics.Renderers.CreativeSacrificeParticle.Draw(), Terraria.Graphics.Renderers.FadingParticle.Draw(), Terraria.Graphics.Renderers.FadingPlayerShaderParticle.Draw(), Terraria.Graphics.Renderers.FlameParticle.Draw(), Terraria.Graphics.Renderers.PrettySparkleParticle.Draw(), Terraria.Graphics.Renderers.RandomizedFrameParticle.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawKite(), Terraria.Main.DrawMurderAurora(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Main.DrawPrettyStarSparkle(), Terraria.Main.DrawProj_EmpressBlade(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FairyQueenRangedItemShot(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Flamethrower_Foxsparks(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_StardustGuardianPunching(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.GameContent.UI.ResourceSets.HorizontalBarsPlayerResourcesDisplaySet.FillBarByValues(), Terraria.NPC.GetAttackDamage_ForProjectiles_MultiLerp(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetGradientRect(), Terraria.Projectile.GetLastPrismHue(), Terraria.GameContent.Animations.Actions.Sprites.LinearScale.GetProgress(), Terraria.GameContent.Animations.Actions.Sprites.OutCircleScale.GetProgress(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GetSacrificeAnimationProgress(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetScale(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.GetSliderValueInner(), Terraria.GameContent.Drawing.TileDrawing.GetWindCycle(), Terraria.Projectile.HandleMovement(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.HeartFillingDrawer(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Helper_GetOpacityWithAccountingForOceanWaterLine(), Terraria.Player.ItemCheck_ApplyUseStyle(), Terraria.Player.ItemCheck_Shoot(), Terraria.NPC.KeyBrandStrike(), Terraria.Projectile.KiteLogic(), Terraria.GameContent.Drawing.TileDrawing.LavaLightA(), Terraria.Utils.Remap(), Terraria.Utils.Remap(), Terraria.GameContent.UI.ResourceSets.FancyClassicPlayerResourcesDisplaySet.StarFillingDrawer(), Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal(), Terraria.Graphics.EmpressBladeDrawer.StripColors(), Terraria.Graphics.FinalFractalHelper.StripColors(), Terraria.Graphics.FinalFractalHelper.FinalFractalProfile.StripColors(), Terraria.Graphics.FlameLashDrawer.StripColors(), Terraria.Graphics.MagicMissileDrawer.StripColors(), Terraria.Graphics.RainbowRodDrawer.StripColors(), Terraria.GameContent.UI.States.UIWorldCreation.StripWidth(), Terraria.Graphics.FlameLashDrawer.StripWidth(), Terraria.Graphics.MagicMissileDrawer.StripWidth(), Terraria.Graphics.RainbowRodDrawer.StripWidth(), Terraria.GameContent.ChromaHotkeyPainter.ReactiveRGBKey.Update(), Terraria.GameContent.Drawing.TileDrawing.Update(), Terraria.GameContent.UI.GameTipsDisplay.GameTip.Update(), Terraria.GameContent.UI.States.UIWorldLoad.Update(), Terraria.Graphics.Renderers.PrettySparkleParticle.Update(), Terraria.Mount.UpdateFrame(), Terraria.SceneState.UpdateGraveyard(), Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.UpdateOpacity(), Terraria.Player.UpdateSunScorchValues(), and Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateVisualFrame().