Terraria Decompiled: Terraria.Utils.BounceEaseOut
BounceEaseOut()
static double Terraria.Utils.BounceEaseOut (double t, int bounces, double elasticity) inline static private
Definition at line 277 of file Utils.cs.
        {
            double num = (double)bounces * 3.141592653589793;
            double num2 = Math.Pow(1.0 - t, elasticity);
            double num3 = Math.Abs(Math.Sin(t * num));
            return 1.0 - num2 * num3;
        }
References System.Math.Abs(), System.Math.Pow(), and System.Math.Sin().
Referenced by Terraria.Utils.EaseOutBounce().