Terraria Decompiled: Terraria.Utils.WrappedLerp
WrappedLerp()
static float Terraria.Utils.WrappedLerp (float value1, float value2, float percent) inline static
Definition at line 217 of file Utils.cs.
        {
            float num = percent * 2f;
            if (num > 1f)
            {
                num = 2f - num;
            }
            return MathHelper.Lerp(value1, value2, num);
        }
References Microsoft.Xna.Framework.MathHelper.Lerp().
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom_GetXPercent(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeStructuredDungeonRoom.BiomeRoom_GetYPercent(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.Main.DrawProjDirect(), Terraria.NPC.FindFrame(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateHangingLeafCluster(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateSpeleothem(), Terraria.NPC.GetAlpha(), Terraria.Projectile.GetAlpha(), Terraria.DataStructures.PlayerDrawLayers.GetChickenBonesGlowColor(), Terraria.GameContent.Drawing.TileDrawing.GetFallenStarFurnitureFlameColor(), Terraria.GameContent.Drawing.TileDrawing.GetHallowedFurnitureFlameColor(), Terraria.DataStructures.PlayerDrawLayers.GetLunaGlowColor(), Terraria.GameContent.Drawing.TileDrawing.GetWrappedFurnitureFlameColor(), and Terraria.GameContent.Generation.Dungeon.DungeonShapes.HourglassRoom.Perform().