Terraria Decompiled: Terraria.Utils.FloodFillTile
FloodFillTile()
static void Terraria.Utils.FloodFillTile (Point point, float maxDist, Utils::TileActionAttempt plot) inline static
Definition at line 2451 of file Utils.cs.
        {
            if (!WorldGen.InWorld(point, 0))
            {
                return;
            }
            List<Point> floodFillQueue = Utils._floodFillQueue1;
            List<Point> floodFillQueue2 = Utils._floodFillQueue2;
            BitSet2D floodFillBitset = Utils._floodFillBitset;
            floodFillBitset.Reset(point, (int)Math.Ceiling((double)maxDist) + 1);
            floodFillQueue2.Add(point);
            floodFillBitset.Add(point);
            while (floodFillQueue2.Count > 0)
            {
                Utils.Swap<List<Point>>(ref floodFillQueue, ref floodFillQueue2);
                floodFillQueue2.Clear();
                foreach (Point point2 in floodFillQueue)
                {
                    if (plot(point2.X, point2.Y))
                    {
                        Point point3 = new Point(point2.X - 1, point2.Y);
                        if (WorldGen.InWorld(point3, 0) && floodFillBitset.Add(point3))
{
                            floodFillQueue2.Add(point3);
                        }
                        point3 = new Point(point2.X + 1, point2.Y);
                        if (WorldGen.InWorld(point3, 0) && floodFillBitset.Add(point3))
{
                            floodFillQueue2.Add(point3);
                        }
                        point3 = new Point(point2.X, point2.Y - 1);
                        if (WorldGen.InWorld(point3, 0) && floodFillBitset.Add(point3))
{
                            floodFillQueue2.Add(point3);
                        }
                        point3 = new Point(point2.X, point2.Y + 1);
                        if (WorldGen.InWorld(point3, 0) && floodFillBitset.Add(point3))
{
                            floodFillQueue2.Add(point3);
                        }
                    }
                }
            }
        }
References Terraria.Utils._floodFillBitset, Terraria.Utils._floodFillQueue1, Terraria.Utils._floodFillQueue2, Terraria.Utilities.BitSet2D.Add(), System.Collections.Generic.List< T >.Add(), System.Math.Ceiling(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.WorldGen.InWorld(), Microsoft.Xna.Framework.Graphics.Point, Terraria.Utilities.BitSet2D.Reset(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(), and Terraria.Projectile.ProjLight().