Terraria Decompiled: Terraria.Utils.RandomVector2
RandomVector2()
static Vector2 Terraria.Utils.RandomVector2 (UnifiedRandom random, float min, float max) inline static
Definition at line 2503 of file Utils.cs.
        {
            return new Vector2((max - min) * (float)random.NextDouble() + min, (max - min) * (float)random.NextDouble() + min);
        }
References Terraria.Utilities.UnifiedRandom.NextDouble(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Mount.CastSuperCartLaser(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.GameContent.Drawing.ParticleOrchestrator.ElderSlimeEffect(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_EmitHeldItemLight(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning(), Terraria.WorldGen.TreeGrowFX(), and Terraria.WorldGen.TreeGrowFX_AshShake().