Terraria Decompiled: Terraria.Utils.ShiftHue
ShiftHue()
static Color Terraria.Utils.ShiftHue (Color color, float hueShift, float luminanceShift, float saturationBoost) inline static
Definition at line 338 of file Utils.cs.
        {
            Vector3 vector = Main.rgbToHsl(color);
            float num = (vector.X + hueShift) % 1f;
            if (num < 0f)
            {
                num += 1f;
            }
            return Main.hslToRgb(num, vector.Y + saturationBoost, Utils.Clamp<float>(vector.Z + luminanceShift, 0f, 1f), color.A);
        }
References Microsoft.Xna.Framework.Color.A, Terraria.Utils.Clamp(), Terraria.Main.hslToRgb(), Terraria.Main.rgbToHsl(), Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Utils.ShiftBlueToCyanTheme().