Terraria Decompiled: Terraria.Utils.Remap
Remap() [2/2]
static float Terraria.Utils.Remap (float fromValue, float fromMin, float fromMax, float toMin, float toMax, bool clamped = true) inline static
Definition at line 259 of file Utils.cs.
        {
            return MathHelper.Lerp(toMin, toMax, Utils.GetLerpValue(fromMin, fromMax, fromValue, clamped));
        }
References Terraria.Utils.GetLerpValue(), and Microsoft.Xna.Framework.MathHelper.Lerp().
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_019_Spears_GetExtensionHitbox(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_123_Deerclops(), Terraria.Projectile.AI_152_SuperStarSlash(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_186_PrincessWeapon(), Terraria.Projectile.AI_187_ShadowHand(), Terraria.Projectile.AI_189_Volcano(), Terraria.Projectile.AI_190_NightsEdge(), Terraria.Projectile.AI_191_TrueNightsEdge(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.Projectile.AI_193_Flamethrower(), Terraria.Projectile.AI_195_JimsDrone(), Terraria.Projectile.AI_198_Flint(), Terraria.Projectile.AI_203_StormLightning(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.SceneState.ApplyVisuals(), Terraria.Graphics.Renderers.FakeFishParticle.BeRepelled(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.BeRepelled(), Terraria.GameContent.Biomes.DitherSnakePass.CalculateDungeonDitherSnake(), Terraria.Projectile.Colliding(), Terraria.Projectile.Damage_GetHitbox(), Terraria.Projectile.Damage_GetProjectileSpecificDamageMultiplier(), Terraria.Player.DoDeadCellsBeheadedParticles(), Terraria.Graphics.Renderers.FakeFishParticle.Draw(), Terraria.Graphics.Renderers.ItemTransferParticle.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Graphics.StormLightningDrawer.Draw(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_ButterFly(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawAfterAllObjects(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.Main.DrawClothesWindow(), Terraria.UI.NetDiagnosticsUI.DrawCounter(), Terraria.Main.DrawDebugSectionsOnMap(), Terraria.Main.DrawDefenseCounter(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawKite(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.Main.DrawProj_DeadCellsFlintSlash(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_Flamethrower(), Terraria.Main.DrawProj_Flamethrower_Foxsparks(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawTrail(), Terraria.Main.DrawWhip_Constellation(), Terraria.Main.DrawWhip_EelWhip(), Terraria.Main.DrawWhip_FlowerWhip(), Terraria.Main.DrawWhip_GenericWhip(), Terraria.DataStructures.RichRoomCheckFeedback.EndScoring(), Terraria.DataStructures.RichRoomCheckFeedback.EndSpread(), Terraria.Projectile.FillWhipControlPoints(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_WorldPercentileAvoidWorldSpawnIfNeeded(), Terraria.WorldGen.GenerateSkyBlockWorld(), Terraria.NPC.GetAlpha(), Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetAttackDamage_LerpBetweenFinalValues(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetCelestialEffectPower(), Terraria.DataStructures.PlayerDrawLayers.GetChickenBonesGlowColor(), Terraria.UI.ItemSlot.GetColorByLoadout(), Terraria.GameContent.Shaders.SepiaScreenShaderData.GetDaylightPowers(), Terraria.DataStructures.PlayerDrawLayers.GetLunaGlowColor(), Terraria.GameContent.Drawing.HorizonHelper.GetMoonStrength(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetMoonStrength(), Terraria.GameContent.UI.States.UICharacterCreation.GetPitchSlider(), Terraria.Player.GetPlacementPreviewOpacity(), Terraria.GameContent.Liquid.LiquidRenderer.GetShimmerGlitterOpacity(), Terraria.GameContent.Biomes.DungeonControlLine.GetStyleWithDitheredTransition(), Terraria.GameContent.Drawing.NextHorizonRenderer.GetVisibilities(), Terraria.GameContent.UI.States.UICharacterCreation.GetVoicePitchColorAt(), Terraria.Player.HeroicisWingDust(), Terraria.Chest.IndicateBlockedChest(), Terraria.GameContent.Drawing.TileDrawing.LavaLightA(), Terraria.GameContent.DontStarveSeed.ModifyNightColor(), Terraria.Player.PlayHurtSound(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout(), Terraria.Projectile.RainbowBoulder_JumpToPosition(), Terraria.GameContent.Creative.CreativePowers.SpawnRateSliderPerPlayerPower.RemapSliderValueToPowerValue(), Terraria.NPC.ScaleStats_ByDifficulty_Tweaks(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreStairwell(), Terraria.GameContent.UI.States.UICharacterCreation.SetPitchSlider_GamePad(), Terraria.GameContent.UI.States.UICharacterCreation.SetPitchSlider_Keyboard(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_NatureFly(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PooFly(), Terraria.NPC.SpawnPassiveShadowHands(), Terraria.Graphics.StormLightningDrawer.StripColors(), Terraria.Graphics.StormLightningDrawer.StripWidth(), Terraria.GameContent.LeashedEntities.LeashedKite.Update(), Terraria.Graphics.CameraModifiers.PunchCameraModifier.Update(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Update(), Terraria.Graphics.Renderers.GasParticle.Update(), Terraria.Graphics.Renderers.ShockIconParticle.Update(), Terraria.Graphics.Renderers.StormLightningParticle.Update(), Terraria.GameContent.Events.ScreenDarkness.Update(), Terraria.Dust.UpdateDust(), Terraria.GameContent.Creative.CreativePowers.ModifyTimeRate.UpdateInfoFromSliderValueCache(), Terraria.GameContent.Creative.CreativePowers.DifficultySliderPower.UpdateInfoFromSliderValueCache(), and Terraria.Graphics.StormLightningDrawer.WaveTransition().