Terraria Decompiled: Terraria.Utils.DrawLine
DrawLine() [2/3]
static void Terraria.Utils.DrawLine (SpriteBatch spriteBatch, Vector2 start, Vector2 end, Color color) inline static
Definition at line 2756 of file Utils.cs.
        {
            float num = Vector2.Distance(start, end);
            Vector2 vector = (end - start) / num;
            Vector2 vector2 = start;
            Vector2 screenPosition = Main.screenPosition;
            float num2 = vector.ToRotation();
            for (float num3 = 0f; num3 <= num; num3 += 4f)
            {
                float num4 = num3 / num;
                spriteBatch.Draw(TextureAssets.BlackTile.Value, vector2 - screenPosition, null, new Color(new Vector4(num4, num4, num4, 1f) * color.ToVector4()), num2, Vector2.Zero, 0.25f, SpriteEffects.None, 0f);
                vector2 = start + num3 * vector;
            }
        }
References Terraria.GameContent.TextureAssets.BlackTile, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.screenPosition, System.start, Microsoft.Xna.Framework.Color.ToVector4(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector4, and Microsoft.Xna.Framework.Vector2.Zero.