Terraria Decompiled: Terraria.Utils.WordwrapStringLegacy
WordwrapStringLegacy()
static string[] Terraria.Utils.WordwrapStringLegacy (string text, DynamicSpriteFont font, int maxWidth, int maxLines, out int lineAmount) inline static
Definition at line 820 of file Utils.cs.
        {
            string[] array = new string[maxLines];
            int num = 0;
            List<string> list = new List<string>(text.Split(new char[] { '\n' }));
            List<string> list2 = new List<string>(list[0].Split(new char[] { ' ' }));
            int num2 = 1;
            while (num2 < list.Count && num2 < maxLines)
            {
                list2.Add("\n");
                list2.AddRange(list[num2].Split(new char[] { ' ' }));
                num2++;
            }
            bool flag = true;
            while (list2.Count > 0)
            {
                string text2 = list2[0];
                string text3 = " ";
                if (list2.Count == 1)
                {
                    text3 = "";
                }
                if (text2 == "\n")
                {
                    string[] array2 = array;
                    int num3 = num++;
                    array2[num3] += text2;
                    flag = true;
                    if (num >= maxLines)
                    {
                        break;
                    }
                    list2.RemoveAt(0);
                }
                else if (flag)
                {
                    if (font.MeasureString(text2).X > (float)maxWidth)
                    {
                        string text4 = text2[0].ToString() ?? "";
                        int num4 = 1;
                        while (font.MeasureString(text4 + text2[num4].ToString() + "-").X <= (float)maxWidth)
{
                            text4 += text2[num4++].ToString();
                        }
                        text4 += "-";
                        array[num++] = text4 + " ";
                        if (num >= maxLines)
{
                            break;
                        }
                        list2.RemoveAt(0);
                        list2.Insert(0, text2.Substring(num4));
                    }
                    else
                    {
                        string[] array3 = array;
                        int num5 = num;
                        array3[num5] = array3[num5] + text2 + text3;
                        flag = false;
                        list2.RemoveAt(0);
                    }
                }
                else if (font.MeasureString(array[num] + text2).X > (float)maxWidth)
                {
                    num++;
                    if (num >= maxLines)
                    {
                        break;
                    }
                    flag = true;
                }
                else
                {
                    string[] array4 = array;
                    int num6 = num;
                    array4[num6] = array4[num6] + text2 + text3;
                    flag = false;
                    list2.RemoveAt(0);
                }
            }
            lineAmount = Math.Min(num + 1, maxLines);
            return array;
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), System.array, System.Collections.Generic.List< T >.Count, System.Collections.Generic.List< T >.Insert(), System.list, ReLogic.Graphics.DynamicSpriteFont.MeasureString(), System.Math.Min(), System.Collections.Generic.List< T >.RemoveAt(), System.text, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf().