Terraria Decompiled: Terraria.Utils.WordwrapStringSmart
WordwrapStringSmart()
static List< List< TextSnippet > > Terraria.Utils.WordwrapStringSmart (string text, Color c, DynamicSpriteFont font, float maxWidth = -1f, int maxLines = -1) inline static
Definition at line 789 of file Utils.cs.
        {
            List<List<TextSnippet>> list = new List<List<TextSnippet>>();
            List<TextSnippet> list2 = new List<TextSnippet>();
            list.Add(list2);
            foreach (PositionedSnippet positionedSnippet in ChatManager.LayoutSnippets(font, ChatManager.ParseMessage(text, c), Vector2.One, maxWidth))
            {
                while (positionedSnippet.Line >= list.Count)
                {
                    if (list.Count == maxLines)
                    {
                        return list;
                    }
                    list.Add(list2 = new List<TextSnippet>());
                }
                list2.Add(positionedSnippet.Snippet);
            }
            return list;
        }
References Terraria.UI.Chat.ChatManager.LayoutSnippets(), Terraria.UI.Chat.PositionedSnippet.Line, System.list, Microsoft.Xna.Framework.Vector2.One, Terraria.UI.Chat.ChatManager.ParseMessage(), Terraria.UI.Chat.PositionedSnippet.Snippet, and System.text.
Referenced by Terraria.GameContent.UI.States.UITextWrappingTest.TestElement.DrawSelf(), Terraria.GameContent.UI.Chat.LegacyChatMonitor.NewTextMultiline(), and Terraria.UI.Chat.ChatMessageContainer.Refresh().