Terraria Decompiled: Terraria.Utils.CheckForGoodTeleportationSpot
CheckForGoodTeleportationSpot()
static Vector2 Terraria.Utils.CheckForGoodTeleportationSpot (ref bool canSpawn, int teleportStartX, int teleportRangeX, int teleportStartY, int teleportRangeY, Utils::RandomTeleportationAttemptSettings settings) inline static
Definition at line 446 of file Utils.cs.
        {
            int num = (int)settings.teleporteeSize.X;
            int num2 = (int)settings.teleporteeSize.Y;
            Vector2 teleporteeVelocity = settings.teleporteeVelocity;
            float teleporteeGravityDirection = settings.teleporteeGravityDirection;
            Rectangle rectangle = new Rectangle(teleportStartX, teleportStartY, teleportRangeX, teleportRangeY);
            int num3 = 0;
            int num4 = 0;
            int num5 = 0;
            int num6 = num;
            Vector2 vector = new Vector2((float)num4, (float)num5) * 16f + new Vector2((float)(-(float)num6 / 2 + 8), (float)(-(float)num2));
            while (!canSpawn && num3 < settings.attemptsBeforeGivingUp)
            {
                num3++;
                num4 = teleportStartX + Main.rand.Next(teleportRangeX);
                num5 = teleportStartY + Main.rand.Next(teleportRangeY);
                int num7 = 45;
                num4 = (int)MathHelper.Clamp((float)num4, (float)num7, (float)(Main.maxTilesX - num7));
                num5 = (int)MathHelper.Clamp((float)num5, (float)num7, (float)(Main.maxTilesY - num7));
                if (!settings.strictRange || rectangle.Contains(new Point(num4, num5)))
                {
                    vector = new Vector2((float)num4, (float)num5) * 16f + new Vector2((float)(-(float)num6 / 2 + 8), (float)(-(float)num2));
                    if (!Collision.SolidCollision(vector, num6, num2))
                    {
                        if (Main.tile[num4, num5] == null)
{
                            Main.tile[num4, num5] = new Tile();
                        }
                        Tile tile = Main.tile[num4, num5];
                        if ((!settings.avoidWalls || tile.wall <= 0) && (tile.wall != 87 || (double)num5 <= Main.worldSurface || NPC.downedPlantBoss) && (!Main.wallDungeon[(int)tile.wall] || (double)num5 <= Main.worldSurface || NPC.downedBoss3) && Utils.CheckForGoodTeleportationSpot_CheckNoInvalidTiles(num4, num5, settings))
{
                            bool flag = false;
                            int i = 0;
                            while (i < settings.maximumFallDistanceFromOrignalPoint)
{
                                if (settings.strictRange && !rectangle.Contains(new Point(num4, num5 + i)))
{
                                    flag = true;
                                    break;
                                }
                                if (Main.tile[num4, num5 + i] == null)
{
                                    Main.tile[num4, num5 + i] = new Tile();
                                }
                                Tile tile2 = Main.tile[num4, num5 + i];
                                vector = new Vector2((float)num4, (float)(num5 + i)) * 16f + new Vector2((float)(-(float)num6 / 2 + 8), (float)(-(float)num2));
                                Collision.SlopeCollision(vector, teleporteeVelocity, num6, num2, teleporteeGravityDirection, false, false);
                                if (!Collision.SolidCollision(vector, num6, num2 + 1, settings.allowSolidTopFloor))
{
                                    i++;
                                }
                                else
{
                                    if (tile2.active() && !tile2.inActive() && Main.tileSolid[(int)tile2.type])
{
                                        break;
                                    }
                                    i++;
                                }
                            }
                            if (!flag)
{
                                int num8 = (int)vector.X / 16;
                                int num9 = (int)vector.Y / 16;
                                if (Utils.CheckForGoodTeleportationSpot_CheckNoInvalidTiles(num8, num9, settings))
{
                                    int num10 = (int)(vector.X + (float)num6 * 0.5f) / 16;
                                    int num11 = (int)(vector.Y + (float)num2) / 16;
                                    Tile tileSafely = Framing.GetTileSafely(num8, num9);
                                    Tile tileSafely2 = Framing.GetTileSafely(num10, num11);
                                    if ((settings.specializedConditions == null || settings.specializedConditions(tileSafely2, num10, num11)) && (!settings.avoidAnyLiquid || tileSafely2.liquid <= 0))
{
                                        if (settings.mostlySolidFloor)
{
                                            Tile tileSafely3 = Framing.GetTileSafely(num10 - 1, num11);
                                            Tile tileSafely4 = Framing.GetTileSafely(num10 + 1, num11);
                                            bool flag2;
                                            bool flag3;
                                            if (settings.allowSolidTopFloor)
{
                                                flag2 = !tileSafely3.inActive() && WorldGen.SolidTileAllowBottomSlope(num10 - 1, num11);
                                                flag3 = !tileSafely4.inActive() && WorldGen.SolidTileAllowBottomSlope(num10 + 1, num11);
                                            }
                                            else
{
                                                flag2 = tileSafely3.active() && !tileSafely3.inActive() && Main.tileSolid[(int)tileSafely3.type] && !Main.tileSolidTop[(int)tileSafely3.type];
                                                flag3 = tileSafely4.active() && !tileSafely4.inActive() && Main.tileSolid[(int)tileSafely4.type] && !Main.tileSolidTop[(int)tileSafely4.type];
                                            }
                                            if (!flag2 && !flag3)
{
                                                continue;
                                            }
                                        }
                                        if ((!settings.avoidWalls || tileSafely.wall <= 0) && (!settings.avoidAnyLiquid || !Collision.WetCollision(vector, num6, num2)) && (!settings.avoidLava || !Collision.LavaCollision(vector, num6, num2)) && (!settings.avoidHurtTiles || !Collision.AnyHurtingTiles(vector, num6, num2)) && !Collision.SolidCollision(vector, num6, num2, settings.allowSolidTopFloor) && i < settings.maximumFallDistanceFromOrignalPoint - 1)
{
                                            Vector2 vector2 = Vector2.UnitX * 16f;
                                            if (!(Collision.TileCollision(vector - vector2, vector2, num, num2, false, false, (int)teleporteeGravityDirection, false, false, true) != vector2))
{
                                                vector2 = -Vector2.UnitX * 16f;
                                                if (!(Collision.TileCollision(vector - vector2, vector2, num, num2, false, false, (int)teleporteeGravityDirection, false, false, true) != vector2))
{
                                                    vector2 = Vector2.UnitY * 16f;
                                                    if (!(Collision.TileCollision(vector - vector2, vector2, num, num2, false, false, (int)teleporteeGravityDirection, false, false, true) != vector2))
{
                                                        vector2 = -Vector2.UnitY * 16f;
                                                        if (!(Collision.TileCollision(vector - vector2, vector2, num, num2, false, false, (int)teleporteeGravityDirection, false, false, true) != vector2) && (!Main.dualDungeonsSeed || !UnbreakableWallScan.InsideUnbreakableWalls(new Point(num8, num9))))
{
                                                            canSpawn = true;
                                                            num5 += i;
                                                            break;
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            return vector;
        }
References Terraria.Tile.active(), Terraria.Collision.AnyHurtingTiles(), Terraria.Utils.CheckForGoodTeleportationSpot_CheckNoInvalidTiles(), Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.NPC.downedBoss3, Terraria.NPC.downedPlantBoss, Terraria.Framing.GetTileSafely(), Terraria.Tile.inActive(), Terraria.GameContent.UnbreakableWallScan.InsideUnbreakableWalls(), int, Terraria.Collision.LavaCollision(), Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Graphics.Point, Terraria.Main.rand, Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Collision.TileCollision(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.Collision.WetCollision(), Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.DemonConch(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_TryFindSpawnAt(), Terraria.WorldGen.RandomizeWorldSpawn(), and Terraria.Player.TeleportationPotion().