Terraria Decompiled: Terraria.Utils.DrawLaser
DrawLaser()
static void Terraria.Utils.DrawLaser (SpriteBatch sb, Texture2D tex, Vector2 start, Vector2 end, Vector2 scale, Utils::LaserLineFraming framing) inline static
Definition at line 2712 of file Utils.cs.
        {
            Vector2 vector = Vector2.Normalize(end - start);
            float num = (end - start).Length();
            float num2 = vector.ToRotation() - 1.5707964f;
            if (vector.HasNaNs())
            {
                return;
            }
            float num3;
            Rectangle rectangle;
            Vector2 vector2;
            Color color;
            framing(0, start, num, default(Rectangle), out num3, out rectangle, out vector2, out color);
            sb.Draw(tex, start, new Rectangle?(rectangle), color, num2, rectangle.Size() / 2f, scale, SpriteEffects.None, 0f);
            num -= num3 * scale.Y;
            Vector2 vector3 = start + vector * ((float)rectangle.Height - vector2.Y) * scale.Y;
            if (num > 0f)
            {
                float num4 = 0f;
                while (num4 + 1f < num)
                {
                    framing(1, vector3, num - num4, rectangle, out num3, out rectangle, out vector2, out color);
                    if (num - num4 < (float)rectangle.Height)
                    {
                        num3 *= (num - num4) / (float)rectangle.Height;
                        rectangle.Height = (int)(num - num4);
                    }
                    sb.Draw(tex, vector3, new Rectangle?(rectangle), color, num2, vector2, scale, SpriteEffects.None, 0f);
                    num4 += num3 * scale.Y;
                    vector3 += vector * num3 * scale.Y;
                }
            }
            framing(2, vector3, num, default(Rectangle), out num3, out rectangle, out vector2, out color);
            sb.Draw(tex, vector3, new Rectangle?(rectangle), color, num2, vector2, scale, SpriteEffects.None, 0f);
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.Vector2.Normalize(), System.start, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Main.DrawProjDirect().