Terraria Decompiled: Terraria.Utils.TryCreatingDirectory
TryCreatingDirectory()
static bool Terraria.Utils.TryCreatingDirectory (string folderPath) inline static
Definition at line 1111 of file Utils.cs.
        {
            if (Directory.Exists(folderPath))
            {
                return true;
            }
            bool flag;
            try
            {
                Directory.CreateDirectory(folderPath);
                flag = true;
            }
            catch (Exception ex)
            {
                FancyErrorPrinter.ShowDirectoryCreationFailError(ex, folderPath);
                flag = false;
            }
            return flag;
        }
References System.IO.Directory.CreateDirectory(), System.IO.Directory.Exists(), and Terraria.UI.FancyErrorPrinter.ShowDirectoryCreationFailError().
Referenced by Terraria.Initializers.AssetInitializer.GetResourcePacksFolderPathAndConfirmItExists(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.Player.InternalSaveMap(), Terraria.IO.WorldFile.InternalSaveWorld(), Terraria.Main.LoadPlayers(), Terraria.IO.WorldFile.LoadWorld(), Terraria.Main.LoadWorlds(), Terraria.Social.Steam.WorkshopSocialModule.MakeTemporaryFolder(), Terraria.Utils.OpenFolder(), Terraria.Testing.ChatCommands.DebugCommandProcessor.OpenMemo(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Main.SaveRecent(), Terraria.Utilities.CrashDump.Write(), and Terraria.Utilities.FileUtilities.Write().