Terraria Decompiled: Terraria.Utils.LineRectangleDistance
LineRectangleDistance()
static float Terraria.Utils.LineRectangleDistance (Rectangle rect, Vector2 lineStart, Vector2 lineEnd) inline static
Definition at line 771 of file Utils.cs.
        {
            Vector2 vector = rect.TopLeft();
            Vector2 vector2 = rect.TopRight();
            Vector2 vector3 = rect.BottomLeft();
            Vector2 vector4 = rect.BottomRight();
            if (lineStart.Between(vector, vector4) || lineEnd.Between(vector, vector4))
            {
                return 0f;
            }
            float num = vector.Distance(vector.ClosestPointOnLine(lineStart, lineEnd));
            float num2 = vector2.Distance(vector2.ClosestPointOnLine(lineStart, lineEnd));
            float num3 = vector3.Distance(vector3.ClosestPointOnLine(lineStart, lineEnd));
            float num4 = vector4.Distance(vector4.ClosestPointOnLine(lineStart, lineEnd));
            return MathHelper.Min(num, MathHelper.Min(num2, MathHelper.Min(num3, num4)));
        }
References Microsoft.Xna.Framework.Vector2.Distance(), and Microsoft.Xna.Framework.MathHelper.Min().
Referenced by Terraria.Player.ProcessHitAgainstNPC().