Terraria Decompiled: Terraria.Utils.PlotTileLine
PlotTileLine() [2/2]
static bool Terraria.Utils.PlotTileLine (Vector2D start, Vector2D end, double width, Utils::TileActionAttempt plot) inline static
Definition at line 2403 of file Utils.cs.
        {
            double num = width / 2.0;
            Vector2D vector2D = end - start;
            Vector2D vector2D2 = vector2D / vector2D.Length();
            Vector2D vector2D3 = new Vector2D(-vector2D2.Y, vector2D2.X) * num;
            Point point = (start - vector2D3).ToTileCoordinates();
            Point point2 = (start + vector2D3).ToTileCoordinates();
            Point point3 = start.ToTileCoordinates();
            Point point4 = end.ToTileCoordinates();
            Point lineMinOffset = new Point(point.X - point3.X, point.Y - point3.Y);
            Point lineMaxOffset = new Point(point2.X - point3.X, point2.Y - point3.Y);
            return Utils.PlotLine(point3.X, point3.Y, point4.X, point4.Y, (int x, int y) => Utils.PlotLine(x + lineMinOffset.X, y + lineMinOffset.Y, x + lineMaxOffset.X, y + lineMaxOffset.Y, plot, false), true);
        }
References ReLogic.Utilities.Vector2D.Length(), Terraria.Utils.PlotLine(), Microsoft.Xna.Framework.Graphics.Point, System.start, Terraria.Utils.ToTileCoordinates(), Microsoft.Xna.Framework.Point.X, ReLogic.Utilities.Vector2D.X, Microsoft.Xna.Framework.Point.Y, and ReLogic.Utilities.Vector2D.Y.