Terraria Decompiled: System.Runtime.Remoting.Channels.ChannelServices.CreateProvider
CreateProvider()
static object System.Runtime.Remoting.Channels.ChannelServices.CreateProvider (ProviderData prov) inline static private
Definition at line 364 of file ChannelServices.cs.
        {
            Type type = Type.GetType(prov.Type);
            if (type == null)
            {
                throw new RemotingException("Type '" + prov.Type + "' not found");
            }
            object[] array = new object[] { prov.CustomProperties, prov.CustomData };
            object obj;
            try
            {
                obj = Activator.CreateInstance(type, array);
            }
            catch (Exception innerException)
            {
                if (innerException is TargetInvocationException)
                {
                    innerException = ((TargetInvocationException)innerException).InnerException;
                }
                string text = "An instance of provider '";
                Type type2 = type;
                throw new RemotingException(text + ((type2 != null) ? type2.ToString() : null) + "' could not be created: " + innerException.Message);
            }
            return obj;
        }
References System.array, System.Activator.CreateInstance(), System.Runtime.Remoting.ProviderData.CustomProperties, System.Type.GetType(), System.Exception.InnerException, System.Exception.Message, System.obj, System.text, System.Type.ToString(), and System.Runtime.Remoting.ProviderData.Type.
Referenced by System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig().