Terraria Decompiled: System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig
RegisterChannelConfig()
static void System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig (ChannelData channel) inline static package
Definition at line 276 of file ChannelServices.cs.
        {
            IServerChannelSinkProvider serverChannelSinkProvider = null;
            IClientChannelSinkProvider clientChannelSinkProvider = null;
            for (int i = channel.ServerProviders.Count - 1; i >= 0; i--)
            {
                IServerChannelSinkProvider serverChannelSinkProvider2 = (IServerChannelSinkProvider)ChannelServices.CreateProvider(channel.ServerProviders[i] as ProviderData);
                serverChannelSinkProvider2.Next = serverChannelSinkProvider;
                serverChannelSinkProvider = serverChannelSinkProvider2;
            }
            for (int j = channel.ClientProviders.Count - 1; j >= 0; j--)
            {
                IClientChannelSinkProvider clientChannelSinkProvider2 = (IClientChannelSinkProvider)ChannelServices.CreateProvider(channel.ClientProviders[j] as ProviderData);
                clientChannelSinkProvider2.Next = clientChannelSinkProvider;
                clientChannelSinkProvider = clientChannelSinkProvider2;
            }
            Type type = Type.GetType(channel.Type);
            if (type == null)
            {
                throw new RemotingException("Type '" + channel.Type + "' not found");
            }
            bool flag = typeof(IChannelSender).IsAssignableFrom(type);
            bool flag2 = typeof(IChannelReceiver).IsAssignableFrom(type);
            Type[] array;
            object[] array2;
            if (flag && flag2)
            {
                array = new Type[]
                {
                    typeof(IDictionary),
                    typeof(IClientChannelSinkProvider),
                    typeof(IServerChannelSinkProvider)
                };
                array2 = new object[] { channel.CustomProperties, clientChannelSinkProvider, serverChannelSinkProvider };
            }
            else if (flag)
            {
                array = new Type[]
                {
                    typeof(IDictionary),
                    typeof(IClientChannelSinkProvider)
                };
                array2 = new object[] { channel.CustomProperties, clientChannelSinkProvider };
            }
            else
            {
                if (!flag2)
                {
                    Type type2 = type;
                    throw new RemotingException(((type2 != null) ? type2.ToString() : null) + " is not a valid channel type");
                }
                array = new Type[]
                {
                    typeof(IDictionary),
                    typeof(IServerChannelSinkProvider)
                };
                array2 = new object[] { channel.CustomProperties, serverChannelSinkProvider };
            }
            ConstructorInfo constructor = type.GetConstructor(array);
            if (constructor == null)
            {
                Type type3 = type;
                throw new RemotingException(((type3 != null) ? type3.ToString() : null) + " does not have a valid constructor");
            }
            IChannel channel2;
            try
            {
                channel2 = (IChannel)constructor.Invoke(array2);
            }
            catch (TargetInvocationException ex)
            {
                throw ex.InnerException;
            }
            object syncRoot = ChannelServices.registeredChannels.SyncRoot;
            lock (syncRoot)
            {
                if (channel.DelayLoadAsClientChannel == "true" && !(channel2 is IChannelReceiver))
                {
                    ChannelServices.delayedClientChannels.Add(channel2);
                }
                else
                {
                    ChannelServices.RegisterChannel(channel2);
                }
            }
        }
References System.Collections.ArrayList.Add(), System.array, System.Runtime.Remoting.ChannelData.ClientProviders, System.Collections.ArrayList.Count, System.Runtime.Remoting.Channels.ChannelServices.CreateProvider(), System.Runtime.Remoting.ChannelData.CustomProperties, System.Runtime.Remoting.Channels.ChannelServices.delayedClientChannels, System.Runtime.Remoting.ChannelData.DelayLoadAsClientChannel, System.Type.GetConstructor(), System.Type.GetType(), System.Exception.InnerException, System.Reflection.ConstructorInfo.Invoke(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel(), System.Runtime.Remoting.Channels.ChannelServices.registeredChannels, System.Runtime.Remoting.ChannelData.ServerProviders, System.Collections.ArrayList.SyncRoot, System.Type.ToString(), and System.Runtime.Remoting.ChannelData.Type.
Referenced by System.Runtime.Remoting.RemotingConfiguration.RegisterChannels().