Terraria Decompiled: System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage
DispatchMessage()
static ServerProcessing System.Runtime.Remoting.Channels.ChannelServices.DispatchMessage (IServerChannelSinkStack sinkStack, IMessage msg, out IMessage replyMsg) inline static
Definition at line 131 of file ChannelServices.cs.
        {
            if (msg == null)
            {
                throw new ArgumentNullException("msg");
            }
            replyMsg = ChannelServices.SyncDispatchMessage(msg);
            if (RemotingServices.IsOneWay(((IMethodMessage)msg).MethodBase))
            {
                return ServerProcessing.OneWay;
            }
            return ServerProcessing.Complete;
        }
References System.Runtime.Remoting.RemotingServices.IsOneWay(), and System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage().
Referenced by System.Runtime.Remoting.Channels.ServerDispatchSink.ProcessMessage().