Terraria Decompiled: System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel
RegisterChannel() [2/2]
static void System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel (IChannel chnl, bool ensureSecurity) inline static
Definition at line 228 of file ChannelServices.cs.
        {
            if (chnl == null)
            {
                throw new ArgumentNullException("chnl");
            }
            if (ensureSecurity)
            {
                ISecurableChannel securableChannel = chnl as ISecurableChannel;
                if (securableChannel == null)
                {
                    throw new RemotingException(string.Format("Channel {0} is not securable while ensureSecurity is specified as true", chnl.ChannelName));
                }
                securableChannel.IsSecured = true;
            }
            object syncRoot = ChannelServices.registeredChannels.SyncRoot;
            lock (syncRoot)
            {
                int num = -1;
                for (int i = 0; i < ChannelServices.registeredChannels.Count; i++)
                {
                    IChannel channel = (IChannel)ChannelServices.registeredChannels[i];
                    if (channel.ChannelName == chnl.ChannelName && chnl.ChannelName != "")
                    {
                        throw new RemotingException("Channel " + channel.ChannelName + " already registered");
                    }
                    if (channel.ChannelPriority < chnl.ChannelPriority && num == -1)
                    {
                        num = i;
                    }
                }
                if (num != -1)
                {
                    ChannelServices.registeredChannels.Insert(num, chnl);
                }
                else
                {
                    ChannelServices.registeredChannels.Add(chnl);
                }
                IChannelReceiver channelReceiver = chnl as IChannelReceiver;
                if (channelReceiver != null && ChannelServices.oldStartModeTypes.Contains(chnl.GetType().ToString()))
                {
                    channelReceiver.StartListening(null);
                }
            }
        }
References System.Collections.ArrayList.Add(), System.Runtime.Remoting.Channels.IChannel.ChannelName, System.Runtime.Remoting.Channels.IChannel.ChannelPriority, System.Collections.Generic.ICollection< T >.Contains(), System.Collections.ArrayList.Count, System.Format, System.Collections.ArrayList.Insert(), System.Runtime.Remoting.Channels.ChannelServices.oldStartModeTypes, System.Runtime.Remoting.Channels.ChannelServices.registeredChannels, System.Runtime.Remoting.Channels.IChannelReceiver.StartListening(), and System.Collections.ArrayList.SyncRoot.