Terraria Decompiled: System.Runtime.Remoting.Channels.ChannelServices.CreateClientChannelSinkChain
CreateClientChannelSinkChain() [2/2]
static IMessageSink System.Runtime.Remoting.Channels.ChannelServices.CreateClientChannelSinkChain (string url, object remoteChannelData, out string objectUri) inline static package
Definition at line 31 of file ChannelServices.cs.
        {
            object[] array = (object[])remoteChannelData;
            object syncRoot = ChannelServices.registeredChannels.SyncRoot;
            lock (syncRoot)
            {
                foreach (object obj in ChannelServices.registeredChannels)
                {
                    IChannelSender channelSender = ((IChannel)obj) as IChannelSender;
                    if (channelSender != null)
                    {
                        IMessageSink messageSink = ChannelServices.CreateClientChannelSinkChain(channelSender, url, array, out objectUri);
                        if (messageSink != null)
{
                            return messageSink;
                        }
                    }
                }
                RemotingConfiguration.LoadDefaultDelayedChannels();
                foreach (object obj2 in ChannelServices.delayedClientChannels)
                {
                    IChannelSender channelSender2 = (IChannelSender)obj2;
                    IMessageSink messageSink2 = ChannelServices.CreateClientChannelSinkChain(channelSender2, url, array, out objectUri);
                    if (messageSink2 != null)
                    {
                        ChannelServices.delayedClientChannels.Remove(channelSender2);
                        ChannelServices.RegisterChannel(channelSender2);
                        return messageSink2;
                    }
                }
            }
            objectUri = null;
            return null;
        }
References System.array, System.Runtime.Remoting.Channels.ChannelServices.CreateClientChannelSinkChain(), System.Runtime.Remoting.Channels.ChannelServices.delayedClientChannels, System.Runtime.Remoting.RemotingConfiguration.LoadDefaultDelayedChannels(), System.obj, System.Runtime.Remoting.Channels.ChannelServices.RegisterChannel(), System.Runtime.Remoting.Channels.ChannelServices.registeredChannels, System.Collections.ArrayList.Remove(), and System.Collections.ArrayList.SyncRoot.
Referenced by System.Runtime.Remoting.Channels.ChannelServices.CreateClientChannelSinkChain(), and System.Runtime.Remoting.RemotingServices.GetClientChannelSinkChain().