Terraria Decompiled: System.Runtime.Remoting.Channels.ChannelServices.CheckReturnMessage
CheckReturnMessage()
static IMessage System.Runtime.Remoting.Channels.ChannelServices.CheckReturnMessage (IMessage callMsg, IMessage retMsg) inline static package
Definition at line 432 of file ChannelServices.cs.
        {
            IMethodReturnMessage methodReturnMessage = retMsg as IMethodReturnMessage;
            if (methodReturnMessage != null && methodReturnMessage.Exception != null && RemotingConfiguration.CustomErrorsEnabled(ChannelServices.IsLocalCall(callMsg)))
            {
                retMsg = new MethodResponse(new Exception("Server encountered an internal error. For more information, turn off customErrors in the server's .config file."), (IMethodCallMessage)callMsg);
            }
            return retMsg;
        }
References System.Runtime.Remoting.RemotingConfiguration.CustomErrorsEnabled(), System.Runtime.Remoting.Messaging.IMethodReturnMessage.Exception, and System.Runtime.Remoting.Channels.ChannelServices.IsLocalCall().
Referenced by System.Runtime.Remoting.Channels.ChannelServices.AsyncDispatchMessage(), System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage(), and System.Runtime.Remoting.Channels.ExceptionFilterSink.SyncProcessMessage().