Terraria Decompiled: ReLogic.OS.Windows.WindowService.SetUnicodeTitle
SetUnicodeTitle()
void ReLogic.OS.Windows.WindowService.SetUnicodeTitle (GameWindow window, string title) inline
Implements ReLogic.OS.IWindowService.
Definition at line 50 of file WindowService.cs.
        {
            NativeMethods.WndProcCallback wndProcCallback = new NativeMethods.WndProcCallback(NativeMethods.DefWindowProc);
            int num = NativeMethods.SetWindowLong(window.Handle, -4, (int)Marshal.GetFunctionPointerForDelegate(wndProcCallback));
            window.Title = title;
            NativeMethods.SetWindowLong(window.Handle, -4, num);
            GC.KeepAlive(wndProcCallback);
        }
References ReLogic.OS.Windows.NativeMethods.DefWindowProc(), System.Runtime.InteropServices.Marshal.GetFunctionPointerForDelegate(), Microsoft.Xna.Framework.GameWindow.Handle, System.GC.KeepAlive(), ReLogic.OS.Windows.NativeMethods.SetWindowLong(), and ReLogic.OS.Windows.NativeMethods.WndProcCallback().