Terraria Decompiled: Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem
UIWorkshopImportWorldListItem()
Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem (UIState ownerState, WorldFileData data, int orderInList) inline
Definition at line 19 of file UIWorkshopImportWorldListItem.cs.
        {
            this._ownerState = ownerState;
            this._orderInList = orderInList;
            this._data = data;
            this.LoadTextures();
            this.InitializeAppearance();
            this._worldIcon = base.GetIconElement();
            this._worldIcon.Left.Set(4f, 0f);
            this._worldIcon.OnLeftDoubleClick += this.ImportButtonClick_ImportWorldToLocalFiles;
            base.Append(this._worldIcon);
            float num = 4f;
            UIImageButton uiimageButton = new UIImageButton(Main.Assets.Request<Texture2D>("Images/UI/ButtonPlay", 1), null);
            uiimageButton.VAlign = 1f;
            uiimageButton.Left.Set(num, 0f);
            uiimageButton.OnLeftClick += this.ImportButtonClick_ImportWorldToLocalFiles;
            base.OnLeftDoubleClick += this.ImportButtonClick_ImportWorldToLocalFiles;
            uiimageButton.OnMouseOver += this.PlayMouseOver;
            uiimageButton.OnMouseOut += this.ButtonMouseOut;
            base.Append(uiimageButton);
            num += 24f;
            this._buttonLabel = new UIText("", 1f, false);
            this._buttonLabel.VAlign = 1f;
            this._buttonLabel.Left.Set(num, 0f);
            this._buttonLabel.Top.Set(-3f, 0f);
            base.Append(this._buttonLabel);
            uiimageButton.SetSnapPoint("Import", orderInList, null, null);
        }
References Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem._buttonLabel, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem._worldIcon, Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ButtonMouseOut(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.InitializeAppearance(), Terraria.UI.UIElement.Left, Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.LoadTextures(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.PlayMouseOver(), Terraria.UI.StyleDimension.Set(), Terraria.UI.UIElement.SetSnapPoint(), and Terraria.UI.UIElement.Top.
Referenced by Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.CompareTo().