Terraria Decompiled: Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles
ImportButtonClick_ImportWorldToLocalFiles()
void Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.ImportButtonClick_ImportWorldToLocalFiles (UIMouseEvent evt, UIElement listeningElement) inline private
Definition at line 92 of file UIWorkshopImportWorldListItem.cs.
        {
            if (listeningElement != evt.Target)
            {
                return;
            }
            if (!this._data.IsValid)
            {
                return;
            }
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            Main.clrInput();
            UIVirtualKeyboard uivirtualKeyboard = new UIVirtualKeyboard(Language.GetTextValue("Workshop.EnterNewNameForImportedWorld"), this._data.Name, new UIVirtualKeyboard.KeyboardSubmitEvent(this.OnFinishedSettingName), new Action(this.GoBackHere), 0, true, 27);
            Main.MenuUI.SetState(uivirtualKeyboard);
        }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, Terraria.Main.clrInput(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.GoBackHere(), Terraria.IO.WorldFileData.IsValid, Terraria.GameContent.UI.States.UIVirtualKeyboard.KeyboardSubmitEvent(), Terraria.Main.MenuUI, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.UserInterface.SetState(), and Terraria.UI.UIEvent.Target.
Referenced by Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.UIWorkshopImportWorldListItem().