Terraria Decompiled: Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt1Block
SwapDxt1Block()
static void Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt1Block (BinaryReader imageReader, BinaryWriter imageWriter) inline static private
Definition at line 153 of file X360TexUtil.cs.
        {
            imageWriter.Write(X360TexUtil.SwapEndian(imageReader.ReadUInt16()));
            imageWriter.Write(X360TexUtil.SwapEndian(imageReader.ReadUInt16()));
            imageWriter.Write(X360TexUtil.SwapEndian(imageReader.ReadUInt16()));
            imageWriter.Write(X360TexUtil.SwapEndian(imageReader.ReadUInt16()));
        }
References System.IO.BinaryReader.ReadUInt16(), Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapEndian(), and System.IO.BinaryWriter.Write().
Referenced by Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt1(), Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt3Block(), and Microsoft.Xna.Framework.Graphics.X360TexUtil.SwapDxt5Block().