Terraria Decompiled: Microsoft.Xna.Framework.Storage.StorageContainer.StorageContainer
StorageContainer()
Microsoft.Xna.Framework.Storage.StorageContainer.StorageContainer (StorageDevice device, string name, string rootPath, PlayerIndex? playerIndex) inline package
Definition at line 96 of file StorageContainer.cs.
        {
            if (string.IsNullOrEmpty(name))
            {
                throw new ArgumentNullException("A title name has to be provided in parameter name.");
            }
            this.StorageDevice = device;
            this.DisplayName = name;
            this.storagePath = Path.Combine(rootPath, name, (playerIndex != null) ? ("Player" + ((int)(playerIndex.Value + 1)).ToString()) : "AllPlayers");
            if (!Directory.Exists(this.storagePath))
            {
                Directory.CreateDirectory(this.storagePath);
            }
        }
References System.IO.Path.Combine(), System.IO.Directory.CreateDirectory(), System.IO.Directory.Exists(), System.name, and Microsoft.Xna.Framework.Storage.StorageContainer.storagePath.