Terraria Decompiled: Microsoft.Xna.Framework.Storage.StorageContainer.CreateDirectory
CreateDirectory()
void Microsoft.Xna.Framework.Storage.StorageContainer.CreateDirectory (string directory) inline
Definition at line 122 of file StorageContainer.cs.
        {
            if (string.IsNullOrEmpty(directory))
            {
                throw new ArgumentNullException("Parameter directory must contain a value.");
            }
            string text = Path.Combine(this.storagePath, directory);
            if (!Directory.Exists(text))
            {
                Directory.CreateDirectory(text);
            }
        }
References System.IO.Path.Combine(), System.IO.Directory.CreateDirectory(), System.IO.Directory.Exists(), Microsoft.Xna.Framework.Storage.StorageContainer.storagePath, and System.text.