Terraria Decompiled: Terraria.GameContent.QuickStacking.DestinationHelper.Reset
Reset()
void Terraria.GameContent.QuickStacking.DestinationHelper.Reset (PositionedChest inventory) inline
Definition at line 451 of file QuickStacking.cs.
            {
                this._chest = inventory;
                this.items = inventory.chest.item;
                this.itemCount = inventory.chest.maxItems;
                this.locked = inventory.chest.IsLockedOrInUse();
                this.transferBlocked = false;
                if (this.freeSlots.Length < this.itemCount)
                {
                    Array.Resize<int>(ref this.freeSlots, this.itemCount);
                }
                Array.Clear(this.freeSlots, 0, this.freeSlots.Length);
                this.freeSlotStart = 0;
                this.freeSlotCount = 0;
                Array.Clear(this.categoryScores, 0, this.categoryScores.Length);
            }
References Terraria.GameContent.QuickStacking.DestinationHelper.categoryScores, Terraria.GameContent.PositionedChest.chest, System.Array.Clear(), Terraria.GameContent.QuickStacking.DestinationHelper.freeSlots, Terraria.Chest.IsLockedOrInUse(), Terraria.Chest.item, Terraria.GameContent.QuickStacking.DestinationHelper.itemCount, and Terraria.Chest.maxItems.
Referenced by Terraria.GameContent.QuickStacking.Transfer().