Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup
Fixup()
void System.Runtime.Serialization.Formatters.Binary.ValueFixup.Fixup (ParseRecord record, ParseRecord parent) inline package
Definition at line 30 of file ValueFixup.cs.
        {
            object prnewObj = record.PRnewObj;
            switch (this.valueFixupEnum)
            {
            case ValueFixupEnum.Array:
                this.arrayObj.SetValue(prnewObj, this.indexMap);
                return;
            case ValueFixupEnum.Header:
            {
                Type typeFromHandle = typeof(Header);
                if (ValueFixup.valueInfo == null)
                {
                    MemberInfo[] member = typeFromHandle.GetMember("Value");
                    if (member.Length != 1)
                    {
                        throw new SerializationException(Environment.GetResourceString("Header reflection error: number of value members: {0}.", new object[] { member.Length }));
                    }
                    ValueFixup.valueInfo = member[0];
                }
                FormatterServices.SerializationSetValue(ValueFixup.valueInfo, this.header, prnewObj);
                return;
            }
            case ValueFixupEnum.Member:
            {
                if (this.objectInfo.isSi)
                {
                    this.objectInfo.objectManager.RecordDelayedFixup(parent.PRobjectId, this.memberName, record.PRobjectId);
                    return;
                }
                MemberInfo memberInfo = this.objectInfo.GetMemberInfo(this.memberName);
                if (memberInfo != null)
                {
                    this.objectInfo.objectManager.RecordFixup(parent.PRobjectId, memberInfo, record.PRobjectId);
                }
                return;
            }
            default:
                return;
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ValueFixup.arrayObj, System.Type.GetMember(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberInfo(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ValueFixup.indexMap, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.ValueFixup.memberName, System.Runtime.Serialization.Formatters.Binary.ValueFixup.objectInfo, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectManager, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.ObjectManager.RecordDelayedFixup(), System.Runtime.Serialization.ObjectManager.RecordFixup(), System.Runtime.Serialization.FormatterServices.SerializationSetValue(), System.Array.SetValue(), System.Runtime.Serialization.Formatters.Binary.ValueFixup.valueFixupEnum, and System.Runtime.Serialization.Formatters.Binary.ValueFixup.valueInfo.