Terraria Decompiled: Newtonsoft.Json.Linq.JTokenReader.ReadOver
ReadOver()
bool Newtonsoft.Json.Linq.JTokenReader.ReadOver (JToken t) inline private
Definition at line 55 of file JTokenReader.cs.
        {
            if (t == this._root)
            {
                return this.ReadToEnd();
            }
            JToken next = t.Next;
            if (next != null && next != t && t != t.Parent.Last)
            {
                this._current = next;
                this.SetToken(this._current);
                return true;
            }
            if (t.Parent == null)
            {
                return this.ReadToEnd();
            }
            return this.SetEnd(t.Parent);
        }
References Newtonsoft.Json.Linq.JTokenReader._current, Newtonsoft.Json.Linq.JTokenReader._root, Newtonsoft.Json.Linq.JContainer.Last, Newtonsoft.Json.Linq.JToken.Next, Newtonsoft.Json.Linq.JToken.Parent, Newtonsoft.Json.Linq.JTokenReader.ReadToEnd(), Newtonsoft.Json.Linq.JTokenReader.SetEnd(), and Newtonsoft.Json.Linq.JTokenReader.SetToken().
Referenced by Newtonsoft.Json.Linq.JTokenReader.Read(), and Newtonsoft.Json.Linq.JTokenReader.SetEnd().