Terraria Decompiled: Newtonsoft.Json.Linq.JTokenReader.SetToken
SetToken()
void Newtonsoft.Json.Linq.JTokenReader.SetToken (JToken token) inline private
Definition at line 130 of file JTokenReader.cs.
        {
            switch (token.Type)
            {
            case JTokenType.Object:
                base.SetToken(JsonToken.StartObject);
                return;
            case JTokenType.Array:
                base.SetToken(JsonToken.StartArray);
                return;
            case JTokenType.Constructor:
                base.SetToken(JsonToken.StartConstructor, ((JConstructor)token).Name);
                return;
            case JTokenType.Property:
                base.SetToken(JsonToken.PropertyName, ((JProperty)token).Name);
                return;
            case JTokenType.Comment:
                base.SetToken(JsonToken.Comment, ((JValue)token).Value);
                return;
            case JTokenType.Integer:
                base.SetToken(JsonToken.Integer, ((JValue)token).Value);
                return;
            case JTokenType.Float:
                base.SetToken(JsonToken.Float, ((JValue)token).Value);
                return;
            case JTokenType.String:
                base.SetToken(JsonToken.String, ((JValue)token).Value);
                return;
            case JTokenType.Boolean:
                base.SetToken(JsonToken.Boolean, ((JValue)token).Value);
                return;
            case JTokenType.Null:
                base.SetToken(JsonToken.Null, ((JValue)token).Value);
                return;
            case JTokenType.Undefined:
                base.SetToken(JsonToken.Undefined, ((JValue)token).Value);
                return;
            case JTokenType.Date:
                base.SetToken(JsonToken.Date, ((JValue)token).Value);
                return;
            case JTokenType.Raw:
                base.SetToken(JsonToken.Raw, ((JValue)token).Value);
                return;
            case JTokenType.Bytes:
                base.SetToken(JsonToken.Bytes, ((JValue)token).Value);
                return;
            case JTokenType.Guid:
                base.SetToken(JsonToken.String, this.SafeToString(((JValue)token).Value));
                return;
            case JTokenType.Uri:
            {
                object value = ((JValue)token).Value;
                Uri uri = value as Uri;
                base.SetToken(JsonToken.String, (uri != null) ? uri.OriginalString : this.SafeToString(value));
                return;
            }
            case JTokenType.TimeSpan:
                base.SetToken(JsonToken.String, this.SafeToString(((JValue)token).Value));
                return;
            default:
                throw MiscellaneousUtils.CreateArgumentOutOfRangeException("Type", token.Type, "Unexpected JTokenType.");
            }
        }
References Newtonsoft.Json.Utilities.MiscellaneousUtils.CreateArgumentOutOfRangeException(), Newtonsoft.Json.Linq.JTokenReader.SafeToString(), Newtonsoft.Json.Linq.JConstructor.Type, Newtonsoft.Json.Linq.JToken.Type, Newtonsoft.Json.Linq.Uri, and System.value.
Referenced by Newtonsoft.Json.Linq.JTokenReader.Read(), Newtonsoft.Json.Linq.JTokenReader.ReadInto(), and Newtonsoft.Json.Linq.JTokenReader.ReadOver().