Terraria Decompiled: Newtonsoft.Json.Linq.JTokenReader.Read
Read()
override bool Newtonsoft.Json.Linq.JTokenReader.Read () inline
Definition at line 34 of file JTokenReader.cs.
        {
            if (base.CurrentState == JsonReader.State.Start)
            {
                this._current = this._root;
                this.SetToken(this._current);
                return true;
            }
            if (this._current == null)
            {
                return false;
            }
            JContainer jcontainer = this._current as JContainer;
            if (jcontainer != null && this._parent != jcontainer)
            {
                return this.ReadInto(jcontainer);
            }
            return this.ReadOver(this._current);
        }
References Newtonsoft.Json.Linq.JTokenReader._current, Newtonsoft.Json.Linq.JTokenReader._parent, Newtonsoft.Json.Linq.JTokenReader._root, Newtonsoft.Json.Linq.JTokenReader.ReadInto(), Newtonsoft.Json.Linq.JTokenReader.ReadOver(), and Newtonsoft.Json.Linq.JTokenReader.SetToken().
Referenced by Newtonsoft.Json.Linq.JTokenWriter.WriteToken().