Terraria Decompiled: Microsoft.Xna.Framework.Content.TextureCubeReader.Read
Read()
override TextureCube Microsoft.Xna.Framework.Content.TextureCubeReader.Read (ContentReader reader, TextureCube existingInstance) inline package
Definition at line 10 of file TextureCubeReader.cs.
        {
            SurfaceFormat surfaceFormat = (SurfaceFormat)reader.ReadInt32();
            int num = reader.ReadInt32();
            int num2 = reader.ReadInt32();
            TextureCube textureCube;
            if (existingInstance == null)
            {
                textureCube = new TextureCube(reader.ContentManager.GetGraphicsDevice(), num, num2 > 1, surfaceFormat);
            }
            else
            {
                textureCube = existingInstance;
            }
            for (int i = 0; i < 6; i++)
            {
                for (int j = 0; j < num2; j++)
                {
                    int num3 = reader.ReadInt32();
                    byte[] array = reader.ReadBytes(num3);
                    textureCube.SetData<byte>((CubeMapFace)i, j, null, array, 0, num3);
                }
            }
            return textureCube;
        }
References System.array, Microsoft.Xna.Framework.Content.ContentReader.ContentManager, Microsoft.Xna.Framework.Content.ContentManager.GetGraphicsDevice(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), and Microsoft.Xna.Framework.Graphics.TextureCube.