Terraria Decompiled: System.Runtime.InteropServices.GCHandle.Alloc
Alloc() [1/2]
static GCHandle System.Runtime.InteropServices.GCHandle.Alloc (object value) inline static
Definition at line 78 of file GCHandle.cs.
        {
            return new GCHandle(value);
        }
References System.Runtime.InteropServices.GCHandle.GCHandle(), and System.value.
Referenced by System.WeakReference< T >.AllocateHandle(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.TextureCube.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.GetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.GetData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.GetData< T >(), Steamworks.ISteamMatchmakingPingResponse.ISteamMatchmakingPingResponse(), Steamworks.ISteamMatchmakingPlayersResponse.ISteamMatchmakingPlayersResponse(), Steamworks.ISteamMatchmakingRulesResponse.ISteamMatchmakingRulesResponse(), Steamworks.ISteamMatchmakingServerListResponse.ISteamMatchmakingServerListResponse(), System.Memory< T >.Pin(), System.ReadOnlyMemory< T >.Pin(), System.IO.PinnedBufferMemoryStream.PinnedBufferMemoryStream(), Microsoft.Xna.Framework.Graphics.TextureCube.SetData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.SetData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicVertexBuffer.SetData< T >(), System.Gen2GcCallback.Setup(), Internal.Cryptography.PinAndClear.Track(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.VertexDeclaration(), System.WeakReference< T >.WeakReference(), and System.WeakReference< T >.WeakReference().