Terraria Decompiled: System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject
AddrOfPinnedObject()
IntPtr System.Runtime.InteropServices.GCHandle.AddrOfPinnedObject () inline
Definition at line 63 of file GCHandle.cs.
        {
            IntPtr addrOfPinnedObject = GCHandle.GetAddrOfPinnedObject(this.handle);
            if (addrOfPinnedObject == (IntPtr)(-1))
            {
                throw new ArgumentException("Object contains non-primitive or non-blittable data.");
            }
            if (addrOfPinnedObject == (IntPtr)(-2))
            {
                throw new InvalidOperationException("Handle is not pinned.");
            }
            return addrOfPinnedObject;
        }
References System.Runtime.InteropServices.GCHandle.GetAddrOfPinnedObject(), and System.Runtime.InteropServices.GCHandle.handle.
Referenced by Microsoft.Xna.Framework.Audio.AudioEmitter.AudioEmitter(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.TextureCube.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.GetData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.GetData< T >(), Steamworks.ISteamMatchmakingPingResponse.operator IntPtr(), Steamworks.ISteamMatchmakingPlayersResponse.operator IntPtr(), Steamworks.ISteamMatchmakingRulesResponse.operator IntPtr(), Steamworks.ISteamMatchmakingServerListResponse.operator IntPtr(), Microsoft.Xna.Framework.Graphics.Texture2D.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetData< T >(), and Microsoft.Xna.Framework.Graphics.VertexDeclaration.VertexDeclaration().