Terraria Decompiled: System.Runtime.InteropServices.GCHandle.Free
Free()
void System.Runtime.InteropServices.GCHandle.Free () inline
Definition at line 90 of file GCHandle.cs.
        {
            IntPtr intPtr = this.handle;
            if (intPtr != IntPtr.Zero && Interlocked.CompareExchange(ref this.handle, IntPtr.Zero, intPtr) == intPtr)
            {
                GCHandle.FreeHandle(intPtr);
                return;
            }
            throw new InvalidOperationException("Handle is not initialized.");
        }
References System.Threading.Interlocked.CompareExchange(), System.Runtime.InteropServices.GCHandle.FreeHandle(), System.Runtime.InteropServices.GCHandle.handle, and System.IntPtr.Zero.
Referenced by Internal.Cryptography.PinAndClear.Dispose(), System.Buffers.MemoryHandle.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsResource.Dispose(), System.IO.PinnedBufferMemoryStream.Dispose(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserIndexedPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawUserPrimitives< T >(), System.Gen2GcCallback.Finalize(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.GetBackBufferData< T >(), Microsoft.Xna.Framework.Graphics.TextureCube.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture3D.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.GetData< T >(), Microsoft.Xna.Framework.Graphics.VertexBuffer.GetData< T >(), Microsoft.Xna.Framework.Graphics.Texture2D.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.IndexBuffer.SetData< T >(), Microsoft.Xna.Framework.Graphics.DynamicIndexBuffer.SetData< T >(), Steamworks.ISteamMatchmakingPingResponse.~ISteamMatchmakingPingResponse(), Steamworks.ISteamMatchmakingPlayersResponse.~ISteamMatchmakingPlayersResponse(), Steamworks.ISteamMatchmakingRulesResponse.~ISteamMatchmakingRulesResponse(), Steamworks.ISteamMatchmakingServerListResponse.~ISteamMatchmakingServerListResponse(), Microsoft.Xna.Framework.Graphics.VertexDeclaration.~VertexDeclaration(), and System.WeakReference< T >.~WeakReference().