Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.PushSprite
PushSprite()
unsafe void Microsoft.Xna.Framework.Graphics.SpriteBatch.PushSprite (Texture2D texture, float sourceX, float sourceY, float sourceW, float sourceH, float destinationX, float destinationY, float destinationW, float destinationH, Color color, float originX, float originY, float rotationSin, float rotationCos, float depth, byte effects) inline private
Definition at line 459 of file SpriteBatch.cs.
        {
            if (this.numSprites >= this.vertexInfo.Length)
            {
                if (this.vertexInfo.Length >= 699050)
                {
                    this.FlushBatch();
                }
                else
                {
                    int num = Math.Min(this.vertexInfo.Length * 2, 699050);
                    Array.Resize<SpriteBatch.VertexPositionColorTexture4>(ref this.vertexInfo, num);
                    Array.Resize<Texture2D>(ref this.textureInfo, num);
                    Array.Resize<SpriteBatch.SpriteInfo>(ref this.spriteInfos, num);
                    Array.Resize<IntPtr>(ref this.sortedSpriteInfos, num);
                }
            }
            if (this.sortMode == SpriteSortMode.Immediate)
            {
                int num2;
                fixed (SpriteBatch.VertexPositionColorTexture4* ptr = &this.vertexInfo[0])
                {
                    SpriteBatch.VertexPositionColorTexture4* ptr2 = ptr;
                    SpriteBatch.GenerateVertexInfo(ptr2, sourceX, sourceY, sourceW, sourceH, destinationX, destinationY, destinationW, destinationH, color, originX, originY, rotationSin, rotationCos, depth, effects);
                    if (this.supportsNoOverwrite)
                    {
                        num2 = this.UpdateVertexBuffer(0, 1);
                    }
                    else
                    {
                        num2 = 0;
                        this.vertexBuffer.SetDataPointerEXT(0, (IntPtr)((void*)ptr2), 96, SetDataOptions.None);
                    }
                }
                this.DrawPrimitives(texture, num2, 1);
                return;
            }
            if (this.sortMode == SpriteSortMode.Deferred)
            {
                fixed (SpriteBatch.VertexPositionColorTexture4* ptr = &this.vertexInfo[this.numSprites])
                {
                    SpriteBatch.GenerateVertexInfo(ptr, sourceX, sourceY, sourceW, sourceH, destinationX, destinationY, destinationW, destinationH, color, originX, originY, rotationSin, rotationCos, depth, effects);
                }
                this.textureInfo[this.numSprites] = texture;
                this.numSprites++;
                return;
            }
            fixed (SpriteBatch.SpriteInfo* ptr3 = &this.spriteInfos[this.numSprites])
            {
                SpriteBatch.SpriteInfo* ptr4 = ptr3;
                ptr4->textureHash = texture.GetHashCode();
                ptr4->sourceX = sourceX;
                ptr4->sourceY = sourceY;
                ptr4->sourceW = sourceW;
                ptr4->sourceH = sourceH;
                ptr4->destinationX = destinationX;
                ptr4->destinationY = destinationY;
                ptr4->destinationW = destinationW;
                ptr4->destinationH = destinationH;
                ptr4->color = color;
                ptr4->originX = originX;
                ptr4->originY = originY;
                ptr4->rotationSin = rotationSin;
                ptr4->rotationCos = rotationCos;
                ptr4->depth = depth;
                ptr4->effects = effects;
            }
            this.textureInfo[this.numSprites] = texture;
            this.numSprites++;
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushBatch(), Microsoft.Xna.Framework.Graphics.SpriteBatch.GenerateVertexInfo(), System.Math.Min(), Microsoft.Xna.Framework.Graphics.SpriteBatch.numSprites, Microsoft.Xna.Framework.Graphics.VertexBuffer.SetDataPointerEXT(), Microsoft.Xna.Framework.Graphics.SpriteBatch.sortedSpriteInfos, Microsoft.Xna.Framework.Graphics.SpriteBatch.sortMode, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteInfos, Microsoft.Xna.Framework.Graphics.SpriteBatch.supportsNoOverwrite, Microsoft.Xna.Framework.Graphics.SpriteBatch.SpriteInfo.textureHash, Microsoft.Xna.Framework.Graphics.SpriteBatch.textureInfo, Microsoft.Xna.Framework.Graphics.SpriteBatch.UpdateVertexBuffer(), Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBuffer, and Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexInfo.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString().