Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin
Begin() [1/5]
void Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin () inline
Definition at line 47 of file SpriteBatch.cs.
        {
            this.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.LinearClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Matrix.Identity);
        }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Microsoft.Xna.Framework.Matrix.Identity, Microsoft.Xna.Framework.Graphics.SamplerState.LinearClamp, and Microsoft.Xna.Framework.Graphics.DepthStencilState.None.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.ApplyDefaultSpriteEffect(), Terraria.DataStructures.SpriteDrawBuffer.ApplyDefaultSpriteEffect(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), ReLogic.Graphics.BasicDebugDrawer.Begin(), ReLogic.Graphics.BasicDebugDrawer.Begin(), Terraria.Graphics.TileBatch.Begin(), Terraria.DataStructures.SpriteBatchBeginner.Begin(), Terraria.DataStructures.SpriteBatchBeginner.Begin(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Main.DoDraw_WallsTilesNPCs(), Terraria.GameContent.UI.LegacyMultiplayerClosePlayersOverlay.Draw(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.Draw(), Terraria.UI.GameInterfaceLayer.Draw(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.GameContent.UI.States.UIWorldGenDebug.Draw(), Terraria.Testing.DebugLineDraw.Draw(), Terraria.UI.UIElement.Draw(), Terraria.UI.IngameFancyUI.Draw(), Terraria.Graphics.Effects.OverlayManager.Draw(), Terraria.Main.DrawBlack(), Terraria.Main.DrawCachedProjs(), Terraria.MapRenderer.DrawChangesToMap(), Terraria.Main.DrawClothesWindow(), Terraria.Main.DrawDust(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks(), Terraria.Main.DrawIMEPanel(), Terraria.Main.DrawInterface(), Terraria.Main.DrawInterface_11_IngameOptionsMenu(), Terraria.Main.DrawInterface_12_IngameFancyUI(), Terraria.Main.DrawInterface_1_1_DrawEmoteBubblesInWorld(), Terraria.Main.DrawInterface_1_2_DrawEntityMarkersInWorld(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.UI.AchievementAdvisor.DrawMouseHover(), Terraria.Main.DrawMouseOver(), Terraria.Main.DrawNPCChatBubble(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawNPCPortrait(), Terraria.Main.DrawPendingMouseText(), Terraria.GameContent.UI.Elements.UICharacter.DrawPets(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProjectiles(), Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld(), Terraria.GameContent.UI.States.UIWorldGenDebug.DrawSelf(), Terraria.Main.DrawSmartCursor(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallbackWithoutCondition(), Terraria.Main.DrawSplash(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.MapRenderer.DrawToMap_Section(), Terraria.Main.DrawWallOfBoulders(), Terraria.Main.DrawWallOfCopperShortswords(), Terraria.Main.DrawWallOfStars(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.EndDrawingSelection(), Terraria.Main.GUIBarsDrawInner(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseRequest(), Terraria.Main.PrepareDrawnEntityDrawing(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.Main.RenderBackground(), Terraria.Main.RenderBackgroundWater(), Terraria.Main.RenderWater(), Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.StartDrawingSelection(), Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateAndDrawMap(), and Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().