Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushBatch
FlushBatch()
unsafe void Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushBatch () inline private
Definition at line 531 of file SpriteBatch.cs.
        {
            this.PrepRenderState();
            if (this.numSprites == 0)
            {
                return;
            }
            if (this.sortMode != SpriteSortMode.Deferred)
            {
                IComparer<IntPtr> comparer;
                if (this.sortMode == SpriteSortMode.Texture)
                {
                    comparer = SpriteBatch.TextureCompare;
                }
                else if (this.sortMode == SpriteSortMode.BackToFront)
                {
                    comparer = SpriteBatch.BackToFrontCompare;
                }
                else
                {
                    comparer = SpriteBatch.FrontToBackCompare;
                }
                fixed (SpriteBatch.SpriteInfo* ptr = &this.spriteInfos[0])
                {
                    SpriteBatch.SpriteInfo* ptr2 = ptr;
                    fixed (IntPtr* ptr3 = &this.sortedSpriteInfos[0])
                    {
                        IntPtr* ptr4 = ptr3;
                        fixed (SpriteBatch.VertexPositionColorTexture4* ptr5 = &this.vertexInfo[0])
{
                            SpriteBatch.VertexPositionColorTexture4* ptr6 = ptr5;
                            for (int i = 0; i < this.numSprites; i++)
{
                                ptr4[(IntPtr)i * (IntPtr)sizeof(IntPtr) / (IntPtr)sizeof(IntPtr)] = (IntPtr)((void*)(ptr2 + i));
                            }
                            Array.Sort<IntPtr, Texture2D>(this.sortedSpriteInfos, this.textureInfo, 0, this.numSprites, comparer);
                            for (int j = 0; j < this.numSprites; j++)
{
                                SpriteBatch.SpriteInfo* ptr7 = (SpriteBatch.SpriteInfo*)(void*)ptr4[(IntPtr)j * (IntPtr)sizeof(IntPtr) / (IntPtr)sizeof(IntPtr)];
                                SpriteBatch.GenerateVertexInfo(ptr6 + j, ptr7->sourceX, ptr7->sourceY, ptr7->sourceW, ptr7->sourceH, ptr7->destinationX, ptr7->destinationY, ptr7->destinationW, ptr7->destinationH, ptr7->color, ptr7->originX, ptr7->originY, ptr7->rotationSin, ptr7->rotationCos, ptr7->depth, ptr7->effects);
                            }
                        }
                    }
                }
            }
            int num = 0;
            for (;;)
            {
                int num2 = Math.Min(this.numSprites, 2048);
                int num3 = this.UpdateVertexBuffer(num, num2);
                int num4 = 0;
                Texture2D texture2D = this.textureInfo[num];
                for (int k = 1; k < num2; k++)
                {
                    Texture2D texture2D2 = this.textureInfo[num + k];
                    if (texture2D2 != texture2D)
                    {
                        this.DrawPrimitives(texture2D, num3 + num4, k - num4);
                        texture2D = texture2D2;
                        num4 = k;
                    }
                }
                this.DrawPrimitives(texture2D, num3 + num4, num2 - num4);
                if (this.numSprites <= 2048)
                {
                    break;
                }
                this.numSprites -= 2048;
                num += 2048;
            }
            this.numSprites = 0;
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.BackToFrontCompare, System.comparer, Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawPrimitives(), Microsoft.Xna.Framework.Graphics.SpriteBatch.FrontToBackCompare, Microsoft.Xna.Framework.Graphics.SpriteBatch.GenerateVertexInfo(), System.Math.Min(), Microsoft.Xna.Framework.Graphics.SpriteBatch.numSprites, Microsoft.Xna.Framework.Graphics.SpriteBatch.PrepRenderState(), System.Array.Sort(), Microsoft.Xna.Framework.Graphics.SpriteBatch.sortedSpriteInfos, Microsoft.Xna.Framework.Graphics.SpriteBatch.sortMode, Microsoft.Xna.Framework.Graphics.SpriteBatch.TextureCompare, Microsoft.Xna.Framework.Graphics.SpriteBatch.textureInfo, and Microsoft.Xna.Framework.Graphics.SpriteBatch.UpdateVertexBuffer().
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.PushSprite().