Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawPrimitives
DrawPrimitives()
void Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawPrimitives (Texture texture, int baseSprite, int batchSize) inline private
Definition at line 706 of file SpriteBatch.cs.
        {
            if (this.customEffect != null)
            {
                using (List<EffectPass>.Enumerator enumerator = this.customEffect.CurrentTechnique.Passes.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        EffectPass effectPass = enumerator.Current;
                        effectPass.Apply();
                        base.GraphicsDevice.Textures[0] = texture;
                        base.GraphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, baseSprite * 4, 0, batchSize * 4, 0, batchSize * 2);
                    }
                    return;
                }
            }
            base.GraphicsDevice.Textures[0] = texture;
            base.GraphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, baseSprite * 4, 0, batchSize * 4, 0, batchSize * 2);
        }
References Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.SpriteBatch.customEffect, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.EffectPassCollection.GetEnumerator(), Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, and Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushBatch(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.PushSprite().