Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw
Draw() [4/7]
void Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw (Texture2D texture, Vector2 position, Color color) inline
Definition at line 107 of file SpriteBatch.cs.
        {
            this.CheckBegin("Draw");
            this.PushSprite(texture, 0f, 0f, 1f, 1f, position.X, position.Y, (float)texture.Width, (float)texture.Height, color, 0f, 0f, 0f, 1f, 0f, 0);
        }
References Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckBegin(), Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Graphics.SpriteBatch.PushSprite(), Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldBuilding.Actions.DebugDraw.Apply(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.CommonDraw(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.GameContent.Drawing.BackgroundGradientDrawer.Draw(), Terraria.GameContent.Bestiary.CustomEntryIcon.Draw(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Draw(), Terraria.GameContent.Golf.FancyGolfPredictionLine.Draw(), Terraria.Graphics.Renderers.BloodyExplosionParticle.Draw(), Terraria.Graphics.Renderers.CreativeSacrificeParticle.Draw(), Terraria.Graphics.Renderers.FadingParticle.Draw(), Terraria.Graphics.Renderers.FadingPlayerShaderParticle.Draw(), Terraria.Graphics.Renderers.FakeFishParticle.Draw(), Terraria.Graphics.Renderers.GasParticle.Draw(), Terraria.Graphics.Renderers.PrettySparkleParticle.Draw(), Terraria.Graphics.Renderers.RandomizedFrameParticle.Draw(), Terraria.Graphics.Renderers.ShockIconParticle.Draw(), Terraria.DataStructures.DrawData.Draw(), Terraria.GameContent.UI.EmoteBubble.Draw(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.Draw(), Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordExplosion.Draw(), Terraria.GameContent.Events.ScreenObstruction.Draw(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.GameContent.UI.States.UITextWrappingTest.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.GameInput.LockOnHelper.Draw(), Terraria.Graphics.Effects.SimpleOverlay.Draw(), Terraria.GameContent.Skies.BlizzardSky.Draw(), Terraria.GameContent.Skies.MartianSky.Draw(), Terraria.GameContent.Skies.MoonLordSky.Draw(), Terraria.GameContent.Skies.NebulaSky.Draw(), Terraria.GameContent.Skies.PartySky.Draw(), Terraria.GameContent.Skies.SandstormSky.Draw(), Terraria.GameContent.Skies.SlimeSky.Draw(), Terraria.GameContent.Skies.SolarSky.Draw(), Terraria.GameContent.Skies.StardustSky.Draw(), Terraria.GameContent.Skies.VortexSky.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.GameContent.UI.ResourceSets.ResourceDrawSettings.Draw(), Terraria.DataStructures.TitleLinkButton.Draw(), Terraria.GameContent.UI.Minimap.MinimapFrame.Button.Draw(), Terraria.GameContent.Drawing.LensFlareElement.Draw(), Terraria.Map.MapOverlayDrawContext.Draw(), Terraria.Map.MapOverlayDrawContext.Draw(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_ButterFly(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Draw_Fly(), Terraria.GameContent.Events.ScreenDarkness.DrawBack(), Terraria.GameContent.UI.Minimap.MinimapFrame.DrawBackground(), Terraria.Main.DrawBackground_DirtBackground(), Terraria.Main.DrawBackground_DrawMagmaLayer(), Terraria.Main.DrawBackground_DrawMagmaTransition(), Terraria.Main.DrawBackground_DrawRockLayer(), Terraria.Main.DrawBackground_DrawUnderworldBlackBox(), Terraria.Main.DrawBackground_SurfaceTransitionBackground(), Terraria.Main.DrawBackgroundBlackFill(), Terraria.UI.BannerClaimingUI.DrawBannersGrid(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawBar(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawBareBonesBar(), Terraria.Main.DrawBestiaryIcon(), Terraria.Main.DrawBlack(), Terraria.Main.DrawBlockReplacementIcon(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawBound(), Terraria.GameContent.LeashedEntities.LeashedCritter.DrawBubble(), Terraria.Main.DrawBuffIcon(), Terraria.Main.DrawBuilderAccToggles(), Terraria.Graphics.Capture.CaptureInterface.DrawButtons(), Terraria.Graphics.Capture.CaptureInterface.DrawCameraLock(), Terraria.UI.AchievementAdvisor.DrawCard(), Terraria.MapRenderer.DrawChangesToMap(), Terraria.GameContent.UI.NewCraftingUI.DrawChildren(), Terraria.Map.MapOverlayDrawContext.DrawClamped(), Terraria.Main.DrawClothesWindow(), Terraria.GameContent.Drawing.EmptyHorizonRenderer.DrawCloud(), Terraria.UI.CraftingUI.DrawCraftFromNearbyChestsToggle(), Terraria.Main.DrawCursor(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawCursorArea(), Terraria.Utils.DrawCursorSingle(), Terraria.Main.DrawDebugSectionsOnMap(), Terraria.Main.DrawDefenseCounter(), Terraria.GameContent.UI.UIDust.DrawDust(), Terraria.Main.DrawDust(), Terraria.Main.DrawElderEye(), Terraria.Main.DrawEmoteBubblesButton(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.BigProgressBar.BigProgressBarHelper.DrawFancyBar(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawFilling(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawFilling2(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.GameContent.UI.Minimap.MinimapFrame.DrawForeground(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Events.ScreenDarkness.DrawFront(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawGhost(), Terraria.GameContent.Drawing.OriginalNatureRenderer.DrawGlowmask(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.DrawGlowRing(), Terraria.Main.DrawGore(), Terraria.Main.DrawGoreBehind(), Terraria.UI.BannerClaimingUI.DrawGridToggle(), Terraria.UI.CraftingUI.DrawGridToggle(), Terraria.Main.DrawHairWindow(), Terraria.Main.DrawHealthBar(), Terraria.Main.DrawHotbarLockIcon(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawIcon(), Terraria.Main.DrawInfernoRings(), Terraria.Main.DrawInfoAccs(), Terraria.UI.InGamePopups.AchievementUnlockedPopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInGame(), Terraria.UI.InGamePopups.PlayerWantsToJoinGamePopup.DrawInNotificationsArea(), Terraria.Main.DrawInterface_19_SignTileBubble(), Terraria.Main.DrawInterface_1_2_DrawEntityMarkersInWorld(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawInterface_6_TileGridOption(), Terraria.Main.DrawInterface_GolfBallIndicator(), Terraria.Main.DrawInterface_Resources_Breath(), Terraria.Main.DrawInterface_Resources_GolfPower(), Terraria.Main.DrawInvasionProgress(), Terraria.Utils.DrawInvBG(), Terraria.Main.DrawInventory(), Terraria.Main.DrawItem(), Terraria.UI.CoinSlot.DrawItemCoin(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups(), Terraria.PopupText.DrawItemTextPopups(), Terraria.GameContent.Skies.LanternSky.DrawLantern(), Terraria.Utils.DrawLaser(), Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawLife(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), Terraria.Map.TeleportPylonsMapLayer.DrawLine(), Terraria.Utils.DrawLine(), Terraria.Utils.DrawLine(), ReLogic.Graphics.BasicDebugDrawer.DrawLine(), Terraria.Main.DrawLoadoutButtons(), Terraria.GameContent.UI.ResourceSets.ClassicPlayerResourcesDisplaySet.DrawMana(), Terraria.MapRenderer.DrawMap(), Terraria.Main.DrawMap(), Terraria.Main.DrawMapFullscreenBackground(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.DrawMapIcon(), Terraria.Main.DrawMapIcons_LastGolfballHit(), Terraria.Main.DrawMapIcons_PotionOfReturnAppearAfterUsePosition(), Terraria.Main.DrawMapIcons_PotionOfReturnHomePosition(), Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.DrawMarkedArea(), Terraria.Graphics.Capture.CaptureInterface.ModeDragBounds.DrawMarkedArea(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.Main.DrawMenu(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.GameContent.Drawing.OriginalNatureRenderer.DrawNature(), Terraria.Utils.DrawNotificationIcon(), Terraria.Main.DrawNPC_SlimeItem(), Terraria.Main.DrawNPCChatBottomRightItem(), Terraria.Main.DrawNPCChatBubble(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Deerclops(), Terraria.Main.DrawNPCDirect_DeerclopsLeg(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawNPCDirect_QueenSlimeWings(), Terraria.Main.DrawNPCExtras(), Terraria.Main.DrawNPCHousesInUI(), Terraria.Main.DrawNPCHousesInWorld(), Terraria.Main.DrawNPCPortrait(), Terraria.Main.DrawNPCs(), Terraria.GameContent.Drawing.WallDrawing.DrawOutline(), Terraria.Main.DrawPageIcons(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.GameContent.UI.Elements.UIPanel.DrawPanel(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIDebugCommandItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawPanel(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawPanel(), Terraria.Utils.DrawPanel(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawPanelBottom(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawPanelTop(), Terraria.Main.DrawPlayerChat(), Terraria.Main.DrawPlayerDeathMarker(), Terraria.GameContent.UI.NewMultiplayerClosePlayersOverlay.PlayerOffScreenCache.DrawPlayerHead(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerStoned(), Terraria.TileObject.DrawPreview(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawProgressBar(), Terraria.Main.DrawProj_CoolWhipMinion(), Terraria.Main.DrawProj_DeadCellsFlintSlash(), Terraria.Main.DrawProj_Excalibur(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FairyQueenRangedItemShot(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProj_NightsEdge(), Terraria.Main.DrawProj_PiercingStarlight(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProj_StardustGuardianPunching(), Terraria.Main.DrawProj_TerraBlade2(), Terraria.Main.DrawProj_TerraBlade2Shot(), Terraria.Main.DrawProj_TheHorsemansBlade(), Terraria.Main.DrawProj_TrueExcalibur(), Terraria.Main.DrawProj_TrueNightsEdge(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawPVPIcons(), Terraria.UI.ItemSlot.DrawRadialCircular(), Terraria.UI.ItemSlot.DrawRadialDpad(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.Main.DrawRain(), Terraria.UI.CraftingUI.DrawRecipesGrid(), Terraria.Testing.DetailedFPS.DrawRect(), Terraria.UI.ItemSlot.DrawSavings(), Terraria.GameContent.UI.CustomCurrencyManager.DrawSavings(), Terraria.GameContent.UI.CustomCurrencySingleCoin.DrawSavingsMoney(), Terraria.Utils.DrawSelectedCraftingBarIndicator(), Terraria.GameContent.UI.Elements.EmoteButton.DrawSelf(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.DrawSelf(), Terraria.GameContent.UI.Elements.UIAchievementListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIBestiaryEntryIcon.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacter.DrawSelf(), Terraria.GameContent.UI.Elements.UICharacterListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIColoredImageButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIHairStyleButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIIconTextButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageButton.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageFramed.DrawSelf(), Terraria.GameContent.UI.Elements.UIImageWithBorder.DrawSelf(), Terraria.GameContent.UI.Elements.UIKeybindingToggleListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIProgressBar.UIInnerProgressBar.DrawSelf(), Terraria.GameContent.UI.Elements.UIResourcePack.DrawSelf(), Terraria.GameContent.UI.Elements.UIToggleImage.DrawSelf(), Terraria.GameContent.UI.Elements.UIVerticalSeparator.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorkshopImportWorldListItem.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldCreationPreview.DrawSelf(), Terraria.GameContent.UI.Elements.UIWorldListItem.DrawSelf(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIImageButtonWithExtraIcon.DrawSelf(), Terraria.Main.DrawSmartCursor(), Terraria.Main.DrawSmartInteract(), Terraria.Main.DrawSplash(), Terraria.Main.DrawSplash_LoadingFlower(), Terraria.Main.DrawSplash_LoadingStar(), Terraria.Utils.DrawSplicedPanel(), ReLogic.Graphics.BasicDebugDrawer.DrawSquare(), ReLogic.Graphics.BasicDebugDrawer.DrawSquare(), ReLogic.Graphics.BasicDebugDrawer.DrawSquareFromCenter(), Terraria.Main.DrawStar(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSun(), Terraria.Main.DrawSunAndMoon(), Terraria.Main.DrawSurfaceBG(), Terraria.Main.DrawSurfaceBG_Corrupt(), Terraria.Main.DrawSurfaceBG_Crimson(), Terraria.Main.DrawSurfaceBG_Desert(), Terraria.Main.DrawSurfaceBG_DrawBackMountainsLayer(), Terraria.Main.DrawSurfaceBG_DrawChangeOverlay(), Terraria.Main.DrawSurfaceBG_Forest(), Terraria.Main.DrawSurfaceBG_GoodEvilDesert(), Terraria.Main.DrawSurfaceBG_Hallow(), Terraria.Main.DrawSurfaceBG_Jungle(), Terraria.Main.DrawSurfaceBG_Mushroom(), Terraria.Main.DrawSurfaceBG_Snow(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawSurfaceLayer(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.OutlinedDrawRenderTargetContent.DrawTheContent(), Terraria.Main.DrawThickCursor(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.Main.DrawTileCracks(), Terraria.Main.DrawTileInWater(), Terraria.GameContent.Creative.CreativeUI.DrawToggleButton(), Terraria.MapRenderer.DrawToMap_Section(), Terraria.Main.DrawTorchBiomeSwapIcon(), Terraria.Main.DrawUnderworldBackgroundLayer(), Terraria.IngameOptions.DrawValueBar(), Terraria.GameContent.UI.Elements.UIColoredSlider.DrawValueBar(), Terraria.GameContent.UI.Elements.UIColoredSliderSimple.DrawValueBarDynamicWidth(), Terraria.GameContent.UI.Elements.UIVerticalSlider.DrawValueBarDynamicWidth(), Terraria.Main.DrawWallOfBoulders(), Terraria.Main.DrawWallOfCopperShortswords(), Terraria.Main.DrawWallOfFish(), Terraria.Graphics.Capture.CaptureInterface.ModeChangeSettings.DrawWaterChoices(), Terraria.Main.DrawWhip(), Terraria.Main.DrawWhip_BoneWhip(), Terraria.Main.DrawWhip_Constellation(), Terraria.Main.DrawWhip_CoolWhip(), Terraria.Main.DrawWhip_EelWhip(), Terraria.Main.DrawWhip_FireWhip(), Terraria.Main.DrawWhip_FlowerWhip(), Terraria.Main.DrawWhip_GenericWhip(), Terraria.Main.DrawWhip_MeteorWhip(), Terraria.Main.DrawWhip_MoonLordWhip(), Terraria.Main.DrawWhip_RainbowWhip(), Terraria.Main.DrawWhip_SlimeWhip(), Terraria.Main.DrawWhip_ThornWhip(), Terraria.Main.DrawWhip_WhipBland(), Terraria.Main.DrawWhip_WhipMace(), Terraria.Main.DrawWhip_WhipScythe(), Terraria.Main.DrawWhip_WhipSword(), Terraria.GameContent.Events.MoonlordDeathDrama.DrawWhite(), Terraria.Main.DrawWires(), Terraria.Main.DrawWithOutlines(), Terraria.Graphics.Renderers.OutlinedTextureRenderer.DrawWithOutlines(), Terraria.Main.DrawWOFBody(), Terraria.Main.DrawWOFRopeToTheHungry(), Terraria.Main.DrawWOFTongueToPlayer(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.Main.EntitySpriteDraw(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), Terraria.Main.MouseText_DrawItemTooltip(), Terraria.Main.OldDrawBackground(), Terraria.Main.oldDrawWater(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.GameContent.Drawing.HorizonHelper.Test_DrawSmallTarget(), Terraria.GameContent.UI.Chat.GlyphTagHandler.GlyphSnippet.UniqueDraw(), and Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().