Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.PrepRenderState
PrepRenderState()
unsafe void Microsoft.Xna.Framework.Graphics.SpriteBatch.PrepRenderState () inline private
Definition at line 674 of file SpriteBatch.cs.
        {
            base.GraphicsDevice.BlendState = this.blendState;
            base.GraphicsDevice.SamplerStates[0] = this.samplerState;
            base.GraphicsDevice.DepthStencilState = this.depthStencilState;
            base.GraphicsDevice.RasterizerState = this.rasterizerState;
            base.GraphicsDevice.SetVertexBuffer(this.vertexBuffer);
            base.GraphicsDevice.Indices = this.indexBuffer;
            Viewport viewport = base.GraphicsDevice.Viewport;
            float num = (float)(2.0 / (double)viewport.Width);
            float num2 = (float)(-2.0 / (double)viewport.Height);
            float* ptr = (float*)(void*)this.spriteMatrixTransform;
            *ptr = num * this.transformMatrix.M11 - this.transformMatrix.M14;
            ptr[1] = num * this.transformMatrix.M21 - this.transformMatrix.M24;
            ptr[2] = num * this.transformMatrix.M31 - this.transformMatrix.M34;
            ptr[3] = num * this.transformMatrix.M41 - this.transformMatrix.M44;
            ptr[4] = num2 * this.transformMatrix.M12 + this.transformMatrix.M14;
            ptr[5] = num2 * this.transformMatrix.M22 + this.transformMatrix.M24;
            ptr[6] = num2 * this.transformMatrix.M32 + this.transformMatrix.M34;
            ptr[7] = num2 * this.transformMatrix.M42 + this.transformMatrix.M44;
            ptr[8] = this.transformMatrix.M13;
            ptr[9] = this.transformMatrix.M23;
            ptr[10] = this.transformMatrix.M33;
            ptr[11] = this.transformMatrix.M43;
            ptr[12] = this.transformMatrix.M14;
            ptr[13] = this.transformMatrix.M24;
            ptr[14] = this.transformMatrix.M34;
            ptr[15] = this.transformMatrix.M44;
            this.spriteEffectPass.Apply();
        }
References Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.SpriteBatch.blendState, Microsoft.Xna.Framework.Graphics.SpriteBatch.depthStencilState, Microsoft.Xna.Framework.Graphics.GraphicsResource.GraphicsDevice, Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Graphics.SpriteBatch.indexBuffer, Microsoft.Xna.Framework.Matrix.M13, Microsoft.Xna.Framework.Matrix.M14, Microsoft.Xna.Framework.Matrix.M23, Microsoft.Xna.Framework.Matrix.M24, Microsoft.Xna.Framework.Matrix.M33, Microsoft.Xna.Framework.Matrix.M34, Microsoft.Xna.Framework.Matrix.M43, Microsoft.Xna.Framework.Matrix.M44, Microsoft.Xna.Framework.Graphics.SpriteBatch.rasterizerState, Microsoft.Xna.Framework.Graphics.SpriteBatch.samplerState, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(), Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteEffectPass, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteMatrixTransform, Microsoft.Xna.Framework.Graphics.SpriteBatch.transformMatrix, Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBuffer, Microsoft.Xna.Framework.Graphics.Viewport.Viewport(), and Microsoft.Xna.Framework.Graphics.Viewport.Width.
Referenced by Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.FlushBatch().