Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.Dispose
Dispose()
override void Microsoft.Xna.Framework.Graphics.SpriteBatch.Dispose (bool disposing) inline protected virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.GraphicsResource.
Definition at line 35 of file SpriteBatch.cs.
        {
            if (!base.IsDisposed)
            {
                this.spriteEffect.Dispose();
                this.indexBuffer.Dispose();
                this.vertexBuffer.Dispose();
            }
            base.Dispose(disposing);
        }
References Microsoft.Xna.Framework.Graphics.Effect.Dispose(), Microsoft.Xna.Framework.Graphics.IndexBuffer.Dispose(), Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose(), Microsoft.Xna.Framework.Graphics.SpriteBatch.indexBuffer, Microsoft.Xna.Framework.Graphics.SpriteBatch.spriteEffect, and Microsoft.Xna.Framework.Graphics.SpriteBatch.vertexBuffer.
Referenced by ReLogic.Graphics.BasicDebugDrawer.Dispose().