Terraria Decompiled: Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString
DrawString() [6/6]
void Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawString (SpriteFont spriteFont, StringBuilder text, Vector2 position, Color color, float rotation, Vector2 origin, Vector2 scale, SpriteEffects effects, float layerDepth) inline
Definition at line 282 of file SpriteBatch.cs.
        {
            this.CheckBegin("DrawString");
            if (text == null)
            {
                throw new ArgumentNullException("text");
            }
            if (text.Length == 0)
            {
                return;
            }
            effects &= SpriteEffects.FlipHorizontally | SpriteEffects.FlipVertically;
            Texture2D textureValue = spriteFont.textureValue;
            List<Rectangle> glyphData = spriteFont.glyphData;
            List<Rectangle> croppingData = spriteFont.croppingData;
            List<Vector3> kerning = spriteFont.kerning;
            Dictionary<char, int> characterIndexMap = spriteFont.characterIndexMap;
            Vector2 vector = origin;
            float num = SpriteBatch.axisDirectionX[(int)effects];
            float num2 = SpriteBatch.axisDirectionY[(int)effects];
            float num3 = 0f;
            float num4 = 0f;
            if (effects != SpriteEffects.None)
            {
                Vector2 vector2 = spriteFont.MeasureString(text);
                vector.X -= vector2.X * SpriteBatch.axisIsMirroredX[(int)effects];
                vector.Y -= vector2.Y * SpriteBatch.axisIsMirroredY[(int)effects];
                num3 = SpriteBatch.axisIsMirroredX[(int)effects];
                num4 = SpriteBatch.axisIsMirroredY[(int)effects];
            }
            Vector2 zero = Vector2.Zero;
            bool flag = true;
            for (int i = 0; i < text.Length; i++)
            {
                char c = text[i];
                if (c != '\r')
                {
                    if (c == '\n')
                    {
                        zero.X = 0f;
                        zero.Y += (float)spriteFont.LineSpacing;
                        flag = true;
                    }
                    else
                    {
                        int num5;
                        if (!characterIndexMap.TryGetValue(c, out num5))
{
                            if (spriteFont.DefaultCharacter == null)
{
                                throw new ArgumentException("Text contains characters that cannot be resolved by this SpriteFont.", "text");
                            }
                            num5 = characterIndexMap[spriteFont.DefaultCharacter.Value];
                        }
                        Vector3 vector3 = kerning[num5];
                        if (flag)
{
                            zero.X += Math.Abs(vector3.X);
                            flag = false;
                        }
                        else
{
                            zero.X += spriteFont.Spacing + vector3.X;
                        }
                        Rectangle rectangle = croppingData[num5];
                        Rectangle rectangle2 = glyphData[num5];
                        float num6 = vector.X + (zero.X + (float)rectangle.X) * num;
                        float num7 = vector.Y + (zero.Y + (float)rectangle.Y) * num2;
                        if (effects != SpriteEffects.None)
{
                            num6 += (float)rectangle2.Width * num3;
                            num7 += (float)rectangle2.Height * num4;
                        }
                        float num8 = (float)Math.Sign(rectangle2.Width) * Math.Max((float)Math.Abs(rectangle2.Width), MathHelper.MachineEpsilonFloat) / (float)textureValue.Width;
                        float num9 = (float)Math.Sign(rectangle2.Height) * Math.Max((float)Math.Abs(rectangle2.Height), MathHelper.MachineEpsilonFloat) / (float)textureValue.Height;
                        this.PushSprite(textureValue, (float)rectangle2.X / (float)textureValue.Width, (float)rectangle2.Y / (float)textureValue.Height, num8, num9, position.X, position.Y, (float)rectangle2.Width * scale.X, (float)rectangle2.Height * scale.Y, color, num6 / num8 / (float)textureValue.Width, num7 / num9 / (float)textureValue.Height, (float)Math.Sin((double)rotation), (float)Math.Cos((double)rotation), layerDepth, (byte)effects);
                        zero.X += vector3.Y + vector3.Z;
                    }
                }
            }
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Graphics.SpriteBatch.axisDirectionX, Microsoft.Xna.Framework.Graphics.SpriteBatch.axisDirectionY, Microsoft.Xna.Framework.Graphics.SpriteBatch.axisIsMirroredX, Microsoft.Xna.Framework.Graphics.SpriteBatch.axisIsMirroredY, Microsoft.Xna.Framework.Graphics.SpriteFont.characterIndexMap, Microsoft.Xna.Framework.Graphics.SpriteBatch.CheckBegin(), System.Math.Cos(), Microsoft.Xna.Framework.Graphics.SpriteFont.croppingData, Microsoft.Xna.Framework.Graphics.SpriteFont.DefaultCharacter, Microsoft.Xna.Framework.Graphics.SpriteFont.glyphData, Microsoft.Xna.Framework.Graphics.Texture2D.Height, Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.Graphics.SpriteFont.kerning, Microsoft.Xna.Framework.Graphics.SpriteFont.LineSpacing, Microsoft.Xna.Framework.MathHelper.MachineEpsilonFloat, System.Math.Max(), Microsoft.Xna.Framework.Graphics.SpriteFont.MeasureString(), Microsoft.Xna.Framework.Graphics.SpriteBatch.PushSprite(), System.Math.Sign(), System.Math.Sin(), System.text, Microsoft.Xna.Framework.Graphics.SpriteFont.textureValue, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Graphics.Texture2D.Width, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector3.Z, and Microsoft.Xna.Framework.Vector2.Zero.