Terraria Decompiled: NVorbis.Ogg.PageReaderBase.ReadNextPage
ReadNextPage()
bool NVorbis.Ogg.PageReaderBase.ReadNextPage () inline
Implements NVorbis.Contracts.Ogg.IPageReader.
Definition at line 292 of file PageReaderBase.cs.
        {
            if (!this.CheckLock())
            {
                throw new InvalidOperationException("Must be locked prior to reading!");
            }
            bool flag = false;
            int num = 0;
            this.PrepareStreamForNextPage();
            int num2;
            while ((num2 = this.FillHeader(this._headerBuf, num, 27 - num, 10)) > 0)
            {
                num2 += num;
                for (int i = 0; i < num2 - 4; i++)
                {
                    if (this.VerifyHeader(this._headerBuf, i, ref num2, true))
                    {
                        byte[] array;
                        int num3;
                        if (this.VerifyPage(this._headerBuf, i, num2, out array, out num3))
{
                            this.ClearEnqueuedData(num3);
                            this.SaveNextPageSearch();
                            if (this.AddPage(array, flag))
{
                                return true;
                            }
                            this.WasteBits += (long)(array.Length * 8);
                            num = 0;
                            num2 = 0;
                            break;
                        }
                        else if (array != null)
{
                            this.EnqueueData(array, num3);
                        }
                    }
                    this.WasteBits += 8L;
                    flag = true;
                }
                if (num2 >= 3)
                {
                    this._headerBuf[0] = this._headerBuf[num2 - 3];
                    this._headerBuf[1] = this._headerBuf[num2 - 2];
                    this._headerBuf[2] = this._headerBuf[num2 - 1];
                    num = 3;
                }
            }
            if (num2 == 0)
            {
                this.SetEndOfStreams();
            }
            return false;
        }
References NVorbis.Ogg.PageReaderBase._headerBuf, NVorbis.Ogg.PageReaderBase.AddPage(), System.array, NVorbis.Ogg.PageReaderBase.CheckLock(), NVorbis.Ogg.PageReaderBase.ClearEnqueuedData(), NVorbis.Ogg.PageReaderBase.EnqueueData(), NVorbis.Ogg.PageReaderBase.FillHeader(), System.L, long, NVorbis.Ogg.PageReaderBase.PrepareStreamForNextPage(), NVorbis.Ogg.PageReaderBase.SaveNextPageSearch(), NVorbis.Ogg.PageReaderBase.SetEndOfStreams(), NVorbis.Ogg.PageReaderBase.VerifyHeader(), and NVorbis.Ogg.PageReaderBase.VerifyPage().