Terraria Decompiled: NVorbis.Ogg.PageReaderBase.VerifyHeader
VerifyHeader() [2/2]
bool NVorbis.Ogg.PageReaderBase.VerifyHeader (byte[] buffer, int index, ref int cnt, bool isFromReadNextPage) inline private
Definition at line 189 of file PageReaderBase.cs.
        {
            if (buffer[index] == 79 && buffer[index + 1] == 103 && buffer[index + 2] == 103 && buffer[index + 3] == 83)
            {
                if (cnt < 27)
                {
                    if (isFromReadNextPage)
                    {
                        cnt += this.FillHeader(buffer, 27 - cnt + index, 27 - cnt, 10);
                    }
                    else
                    {
                        cnt += this.EnsureRead(buffer, 27 - cnt + index, 27 - cnt, 10);
                    }
                }
                if (cnt >= 27)
                {
                    byte b = buffer[index + 26];
                    if (isFromReadNextPage)
                    {
                        cnt += this.FillHeader(buffer, index + 27, (int)b, 10);
                    }
                    else
                    {
                        cnt += this.EnsureRead(buffer, index + 27, (int)b, 10);
                    }
                    if (cnt == index + 27 + (int)b)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References NVorbis.Ogg.PageReaderBase.EnsureRead(), NVorbis.Ogg.PageReaderBase.FillHeader(), and System.index.
Referenced by NVorbis.Ogg.PageReaderBase.ReadNextPage(), and NVorbis.Ogg.PageReaderBase.VerifyHeader().