Terraria Decompiled: NVorbis.Ogg.PageReaderBase.VerifyPage
VerifyPage()
bool NVorbis.Ogg.PageReaderBase.VerifyPage (byte[] headerBuf, int index, int cnt, out byte[] pageBuf, out int bytesRead) inline private
Definition at line 86 of file PageReaderBase.cs.
        {
            byte b = headerBuf[index + 26];
            if (cnt - index < index + 27 + (int)b)
            {
                pageBuf = null;
                bytesRead = 0;
                return false;
            }
            int num = 0;
            int i;
            for (i = 0; i < (int)b; i++)
            {
                num += (int)headerBuf[index + i + 27];
            }
            pageBuf = new byte[num + (int)b + 27];
            Buffer.BlockCopy(headerBuf, index, pageBuf, 0, (int)(b + 27));
            bytesRead = this.EnsureRead(pageBuf, (int)(b + 27), num, 10);
            if (bytesRead != num)
            {
                return false;
            }
            num = pageBuf.Length;
            this._crc.Reset();
            for (i = 0; i < 22; i++)
            {
                this._crc.Update((int)pageBuf[i]);
            }
            this._crc.Update(0);
            this._crc.Update(0);
            this._crc.Update(0);
            this._crc.Update(0);
            for (i += 4; i < num; i++)
            {
                this._crc.Update((int)pageBuf[i]);
            }
            return this._crc.Test(BitConverter.ToUInt32(pageBuf, 22));
        }
References NVorbis.Ogg.PageReaderBase._crc, System.Buffer.BlockCopy(), NVorbis.Ogg.PageReaderBase.EnsureRead(), System.index, int, NVorbis.Contracts.Ogg.ICrc.Reset(), NVorbis.Contracts.Ogg.ICrc.Test(), System.BitConverter.ToUInt32(), and NVorbis.Contracts.Ogg.ICrc.Update().
Referenced by NVorbis.Ogg.PageReaderBase.ReadNextPage().