Terraria Decompiled: NVorbis.Ogg.PageReaderBase.FillHeader
FillHeader()
int NVorbis.Ogg.PageReaderBase.FillHeader (byte[] buf, int index, int count, int maxTries = 10) inline private
Definition at line 167 of file PageReaderBase.cs.
        {
            int num = 0;
            if (this._overflowBuf != null)
            {
                num = Math.Min(this._overflowBuf.Length - this._overflowBufIndex, count);
                Buffer.BlockCopy(this._overflowBuf, this._overflowBufIndex, buf, index, num);
                index += num;
                count -= num;
                if ((this._overflowBufIndex += num) == this._overflowBuf.Length)
                {
                    this._overflowBuf = null;
                }
            }
            if (count > 0)
            {
                num += this.EnsureRead(buf, index, count, maxTries);
            }
            return num;
        }
References NVorbis.Ogg.PageReaderBase._overflowBuf, NVorbis.Ogg.PageReaderBase._overflowBufIndex, System.Buffer.BlockCopy(), System.count, NVorbis.Ogg.PageReaderBase.EnsureRead(), System.index, and System.Math.Min().
Referenced by NVorbis.Ogg.PageReaderBase.ReadNextPage(), and NVorbis.Ogg.PageReaderBase.VerifyHeader().