Terraria Decompiled: Terraria.GameContent.PlayerSittingHelper.UpdateSitting
UpdateSitting()
void Terraria.GameContent.PlayerSittingHelper.UpdateSitting (Player player) inline
Definition at line 47 of file PlayerSittingHelper.cs.
        {
            if (!this.isSitting)
            {
                return;
            }
            Point point = (player.Bottom + new Vector2(0f, -2f)).ToTileCoordinates();
            int num;
            Vector2 vector;
            Vector2 vector2;
            ExtraSeatInfo extraSeatInfo;
            if (!PlayerSittingHelper.GetSittingTargetInfo(player, point.X, point.Y, out num, out vector, out vector2, out extraSeatInfo))
            {
                this.SitUp(player, true);
                return;
            }
            if (player.controlLeft || player.controlRight || player.controlUp || player.controlDown || player.controlJump || player.pulley || player.mount.Active || num != player.direction)
            {
                this.SitUp(player, true);
            }
            if (Main.sittingManager.GetNextPlayerStackIndexInCoords(point) >= 2)
            {
                this.SitUp(player, true);
            }
            if (!this.isSitting)
            {
                return;
            }
            if (Main.netMode != 1 && !Main.IsItDay())
            {
                int num2 = 2322;
                int num3 = 2358;
                Tile tile = Main.tile[point.X, point.Y];
                if (tile.type == 89 && (int)tile.frameX >= num2 && (int)tile.frameX <= num3)
                {
                    NPC.RedHatSkeletron(player.whoAmI);
                }
            }
            this.offsetForSeat = vector2;
            this.details = extraSeatInfo;
            Main.sittingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, point, out this.sittingIndex);
        }
References Terraria.Mount.Active, Terraria.Player.controlDown, Terraria.Player.controlJump, Terraria.Player.controlLeft, Terraria.Player.controlRight, Terraria.Player.controlUp, Terraria.Entity.direction, Terraria.Tile.frameX, Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo(), Terraria.Main.IsItDay(), Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.Player.mount, Terraria.Main.netMode, Terraria.Player.pulley, Terraria.NPC.RedHatSkeletron(), Terraria.Main.sittingManager, Terraria.GameContent.PlayerSittingHelper.SitUp(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.