Terraria Decompiled: Terraria.GameContent.PlayerSittingHelper.SitDown
SitDown()
void Terraria.GameContent.PlayerSittingHelper.SitDown (Player player, int x, int y) inline
Definition at line 108 of file PlayerSittingHelper.cs.
        {
            int num;
            Vector2 vector;
            Vector2 vector2;
            ExtraSeatInfo extraSeatInfo;
            if (!PlayerSittingHelper.GetSittingTargetInfo(player, x, y, out num, out vector, out vector2, out extraSeatInfo))
            {
                return;
            }
            Vector2 vector3 = vector - player.Bottom;
            bool flag = player.CanSnapToPosition(vector3);
            if (flag)
            {
                flag &= Main.sittingManager.GetNextPlayerStackIndexInCoords((vector + new Vector2(0f, -2f)).ToTileCoordinates()) < 2;
            }
            if (flag)
            {
                if (this.isSitting && player.Bottom == vector)
                {
                    this.SitUp(player, true);
                    return;
                }
                player.StopVanityActions(true);
                player.RemoveAllGrapplingHooks();
                if (player.mount.Active)
                {
                    player.mount.TryDismount(player);
                }
                player.Bottom = vector;
                player.ChangeDir(num);
                this.isSitting = true;
                this.details = extraSeatInfo;
                this.offsetForSeat = vector2;
                Main.sittingManager.AddPlayerAndGetItsStackedIndexInCoords(player.whoAmI, new Point(x, y), out this.sittingIndex);
                player.velocity = Vector2.Zero;
                player.gravDir = 1f;
                if (Main.myPlayer == player.whoAmI)
                {
                    NetMessage.SendData(13, -1, -1, null, player.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.Mount.Active, Terraria.Entity.Bottom, Terraria.Player.CanSnapToPosition(), Terraria.Player.ChangeDir(), Terraria.GameContent.PlayerSittingHelper.GetSittingTargetInfo(), Terraria.GameContent.PlayerSittingHelper.isSitting, Terraria.Player.mount, Terraria.Main.myPlayer, Terraria.Player.RemoveAllGrapplingHooks(), Terraria.NetMessage.SendData(), Terraria.GameContent.PlayerSittingHelper.sittingIndex, Terraria.Main.sittingManager, Terraria.GameContent.PlayerSittingHelper.SitUp(), Terraria.Player.StopVanityActions(), Terraria.Mount.TryDismount(), Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.