Terraria Decompiled: Microsoft.Xna.Framework.Game.CategorizeComponent
CategorizeComponent()
void Microsoft.Xna.Framework.Game.CategorizeComponent (IGameComponent component) inline private
Definition at line 762 of file Game.cs.
        {
            IUpdateable updateable = component as IUpdateable;
            if (updateable != null)
            {
                List<IUpdateable> list = this.updateableComponents;
                lock (list)
                {
                    this.SortUpdateable(updateable);
                }
                updateable.UpdateOrderChanged += this.OnUpdateOrderChanged;
            }
            IDrawable drawable = component as IDrawable;
            if (drawable != null)
            {
                List<IDrawable> list2 = this.drawableComponents;
                lock (list2)
                {
                    this.SortDrawable(drawable);
                }
                drawable.DrawOrderChanged += this.OnDrawOrderChanged;
            }
        }
References Microsoft.Xna.Framework.Game.drawableComponents, System.list, Microsoft.Xna.Framework.Game.OnDrawOrderChanged(), Microsoft.Xna.Framework.Game.OnUpdateOrderChanged(), Microsoft.Xna.Framework.Game.SortDrawable(), Microsoft.Xna.Framework.Game.SortUpdateable(), and Microsoft.Xna.Framework.Game.updateableComponents.
Referenced by Microsoft.Xna.Framework.Game.DoInitialize(), and Microsoft.Xna.Framework.Game.OnComponentAdded().