Terraria Decompiled: Microsoft.Xna.Framework.Game.RedrawWindow
RedrawWindow()
void Microsoft.Xna.Framework.Game.RedrawWindow () inline package
Definition at line 583 of file Game.cs.
        {
            if (this.gameTime.TotalGameTime != TimeSpan.Zero && this.BeginDraw())
            {
                this.Draw(new GameTime(this.gameTime.TotalGameTime, TimeSpan.Zero));
                this.EndDraw();
            }
        }
References Microsoft.Xna.Framework.Game.Draw(), Microsoft.Xna.Framework.Game.EndDraw(), Microsoft.Xna.Framework.Game.gameTime, Microsoft.Xna.Framework.GameTime.TotalGameTime, and System.TimeSpan.Zero.
Referenced by Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL2_FNAPlatform.Win32OnPaint(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.Win32OnPaint().