Terraria Decompiled: Microsoft.Xna.Framework.Game.OnUpdateOrderChanged
OnUpdateOrderChanged()
void Microsoft.Xna.Framework.Game.OnUpdateOrderChanged (object sender, EventArgs e) inline private
Definition at line 913 of file Game.cs.
        {
            IUpdateable updateable = sender as IUpdateable;
            List<IUpdateable> list = this.updateableComponents;
            lock (list)
            {
                this.updateableComponents.Remove(updateable);
                this.SortUpdateable(updateable);
            }
        }
References System.list, System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.Game.SortUpdateable(), and Microsoft.Xna.Framework.Game.updateableComponents.
Referenced by Microsoft.Xna.Framework.Game.CategorizeComponent(), and Microsoft.Xna.Framework.Game.OnComponentRemoved().