Terraria Decompiled: Microsoft.Xna.Framework.Game.Initialize
Initialize()
virtual void Microsoft.Xna.Framework.Game.Initialize () inline protected virtual
Reimplemented in Terraria.Main.
Definition at line 628 of file Game.cs.
        {
            for (int i = 0; i < this.Components.Count; i++)
            {
                this.Components[i].Initialize();
            }
            this.graphicsDeviceService = (IGraphicsDeviceService)this.Services.GetService(typeof(IGraphicsDeviceService));
            if (this.graphicsDeviceService != null)
            {
                this.graphicsDeviceService.DeviceDisposing += delegate(object o, EventArgs e)
                {
                    this.UnloadContent();
                };
                if (this.graphicsDeviceService.GraphicsDevice != null)
                {
                    this.LoadContent();
                    return;
                }
                this.graphicsDeviceService.DeviceCreated += delegate(object o, EventArgs e)
                {
                    this.LoadContent();
                };
            }
        }
References Microsoft.Xna.Framework.Game.Components, System.Collections.ObjectModel.Collection< T >.Count, Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService.GraphicsDevice, Microsoft.Xna.Framework.Game.graphicsDeviceService, Microsoft.Xna.Framework.Game.LoadContent(), and Microsoft.Xna.Framework.Game.UnloadContent().
Referenced by Microsoft.Xna.Framework.Game.DoInitialize().