Terraria Decompiled: Microsoft.Xna.Framework.Game.Run
Run()
void Microsoft.Xna.Framework.Game.Run () inline
Definition at line 485 of file Game.cs.
        {
            this.AssertNotDisposed();
            if (!this.hasInitialized)
            {
                this.DoInitialize();
                this.hasInitialized = true;
            }
            this.BeginRun();
            this.BeforeLoop();
            this.gameTimer = Stopwatch.StartNew();
            this.RunLoop();
            this.EndRun();
            this.AfterLoop();
        }
References Microsoft.Xna.Framework.Game.AfterLoop(), Microsoft.Xna.Framework.Game.AssertNotDisposed(), Microsoft.Xna.Framework.Game.BeforeLoop(), Microsoft.Xna.Framework.Game.BeginRun(), Microsoft.Xna.Framework.Game.DoInitialize(), Microsoft.Xna.Framework.Game.EndRun(), Microsoft.Xna.Framework.Game.hasInitialized, and Microsoft.Xna.Framework.Game.RunLoop().
Referenced by Terraria.Program.RunGame().