Terraria Decompiled: Microsoft.Xna.Framework.Game.Game
Game() [1/2]
Microsoft.Xna.Framework.Game.Game () inline
Definition at line 356 of file Game.cs.
        {
            AppDomain.CurrentDomain.UnhandledException += this.OnUnhandledException;
            this.LaunchParameters = new LaunchParameters();
            this.Components = new GameComponentCollection();
            this.Services = new GameServiceContainer();
            this.Content = new ContentManager(this.Services);
            this.updateableComponents = new List<IUpdateable>();
            this.currentlyUpdatingComponents = new List<IUpdateable>();
            this.drawableComponents = new List<IDrawable>();
            this.currentlyDrawingComponents = new List<IDrawable>();
            this.IsMouseVisible = false;
            this.IsFixedTimeStep = true;
            this.TargetElapsedTime = TimeSpan.FromTicks(166667L);
            this.InactiveSleepTime = TimeSpan.FromSeconds(0.02);
            for (int i = 0; i < this.previousSleepTimes.Length; i++)
            {
                this.previousSleepTimes[i] = TimeSpan.FromMilliseconds(1.0);
            }
            this.textInputControlDown = new bool[FNAPlatform.TextInputCharacters.Length];
            this.hasInitialized = false;
            this.suppressDraw = false;
            this.isDisposed = false;
            this.gameTime = new GameTime();
            this.Window = FNAPlatform.CreateWindow();
            Mouse.WindowHandle = this.Window.Handle;
            TouchPanel.WindowHandle = this.Window.Handle;
            TextInputEXT.WindowHandle = this.Window.Handle;
            FrameworkDispatcher.Update();
            this.RunApplication = true;
        }
References Microsoft.Xna.Framework.FNAPlatform.CreateWindow, System.TimeSpan.FromMilliseconds(), System.TimeSpan.FromSeconds(), System.TimeSpan.FromTicks(), Microsoft.Xna.Framework.GameWindow.Handle, Microsoft.Xna.Framework.Input.L, Microsoft.Xna.Framework.Game.LaunchParameters, Microsoft.Xna.Framework.Game.OnUnhandledException(), Microsoft.Xna.Framework.Game.previousSleepTimes, Microsoft.Xna.Framework.FNAPlatform.TextInputCharacters, Microsoft.Xna.Framework.FrameworkDispatcher.Update(), and Microsoft.Xna.Framework.Game.Window.