Terraria Decompiled: Microsoft.Xna.Framework.Game.Update
Update()
virtual void Microsoft.Xna.Framework.Game.Update (GameTime gameTime) inline protected virtual
Reimplemented in Terraria.Main.
Definition at line 675 of file Game.cs.
        {
            List<IUpdateable> list = this.updateableComponents;
            lock (list)
            {
                for (int i = 0; i < this.updateableComponents.Count; i++)
                {
                    this.currentlyUpdatingComponents.Add(this.updateableComponents[i]);
                }
            }
            foreach (IUpdateable updateable in this.currentlyUpdatingComponents)
            {
                if (updateable.Enabled)
                {
                    updateable.Update(gameTime);
                }
            }
            this.currentlyUpdatingComponents.Clear();
            FrameworkDispatcher.Update();
        }
References System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Game.currentlyUpdatingComponents, Microsoft.Xna.Framework.IUpdateable.Enabled, Microsoft.Xna.Framework.Game.gameTime, System.list, Microsoft.Xna.Framework.FrameworkDispatcher.Update(), Microsoft.Xna.Framework.IUpdateable.Update(), and Microsoft.Xna.Framework.Game.updateableComponents.
Referenced by Microsoft.Xna.Framework.Game.Tick().