Terraria Decompiled: Microsoft.Xna.Framework.Game.OnDrawOrderChanged
OnDrawOrderChanged()
void Microsoft.Xna.Framework.Game.OnDrawOrderChanged (object sender, EventArgs e) inline private
Definition at line 925 of file Game.cs.
        {
            IDrawable drawable = sender as IDrawable;
            List<IDrawable> list = this.drawableComponents;
            lock (list)
            {
                this.drawableComponents.Remove(drawable);
                this.SortDrawable(drawable);
            }
        }
References Microsoft.Xna.Framework.Game.drawableComponents, System.list, System.Collections.Generic.List< T >.Remove(), and Microsoft.Xna.Framework.Game.SortDrawable().
Referenced by Microsoft.Xna.Framework.Game.CategorizeComponent(), and Microsoft.Xna.Framework.Game.OnComponentRemoved().