Terraria Decompiled: Microsoft.Xna.Framework.Game.RunLoop
RunLoop()
void Microsoft.Xna.Framework.Game.RunLoop () inline private
Definition at line 829 of file Game.cs.
        {
            if (FNAPlatform.NeedsPlatformMainLoop())
            {
                FNAPlatform.RunPlatformMainLoop(this);
            }
            while (this.RunApplication)
            {
                this.Tick();
            }
            this.OnExiting(this, EventArgs.Empty);
        }
References System.EventArgs.Empty, Microsoft.Xna.Framework.FNAPlatform.NeedsPlatformMainLoop, Microsoft.Xna.Framework.Game.OnExiting(), Microsoft.Xna.Framework.Game.RunApplication, Microsoft.Xna.Framework.FNAPlatform.RunPlatformMainLoop, and Microsoft.Xna.Framework.Game.Tick().
Referenced by Microsoft.Xna.Framework.Game.Run().