Terraria Decompiled: Microsoft.Xna.Framework.Game.Tick
Tick()
void Microsoft.Xna.Framework.Game.Tick () inline
Definition at line 502 of file Game.cs.
        {
            this.AdvanceElapsedTime();
            if (this.IsFixedTimeStep)
            {
                while (this.accumulatedElapsedTime + this.worstCaseSleepPrecision < this.TargetElapsedTime)
                {
                    Thread.Sleep(1);
                    TimeSpan timeSpan = this.AdvanceElapsedTime();
                    this.UpdateEstimatedSleepPrecision(timeSpan);
                }
                while (this.accumulatedElapsedTime < this.TargetElapsedTime)
                {
                    Thread.SpinWait(1);
                    this.AdvanceElapsedTime();
                }
            }
            FNAPlatform.PollEvents(this, ref this.currentAdapter, this.textInputControlDown, ref this.textInputSuppress);
            if (this.accumulatedElapsedTime > Game.MaxElapsedTime)
            {
                this.accumulatedElapsedTime = Game.MaxElapsedTime;
            }
            if (this.IsFixedTimeStep)
            {
                this.gameTime.ElapsedGameTime = this.TargetElapsedTime;
                int num = 0;
                while (this.accumulatedElapsedTime >= this.TargetElapsedTime)
                {
                    this.gameTime.TotalGameTime += this.TargetElapsedTime;
                    this.accumulatedElapsedTime -= this.TargetElapsedTime;
                    num++;
                    this.AssertNotDisposed();
                    this.Update(this.gameTime);
                }
                this.updateFrameLag += Math.Max(0, num - 1);
                if (this.gameTime.IsRunningSlowly)
                {
                    if (this.updateFrameLag == 0)
                    {
                        this.gameTime.IsRunningSlowly = false;
                    }
                }
                else if (this.updateFrameLag >= 5)
                {
                    this.gameTime.IsRunningSlowly = true;
                }
                if (num == 1 && this.updateFrameLag > 0)
                {
                    this.updateFrameLag--;
                }
                this.gameTime.ElapsedGameTime = TimeSpan.FromTicks(this.TargetElapsedTime.Ticks * (long)num);
            }
            else
            {
                if (this.forceElapsedTimeToZero)
                {
                    this.gameTime.ElapsedGameTime = TimeSpan.Zero;
                    this.forceElapsedTimeToZero = false;
                }
                else
                {
                    this.gameTime.ElapsedGameTime = this.accumulatedElapsedTime;
                    this.gameTime.TotalGameTime += this.gameTime.ElapsedGameTime;
                }
                this.accumulatedElapsedTime = TimeSpan.Zero;
                this.AssertNotDisposed();
                this.Update(this.gameTime);
            }
            if (this.suppressDraw)
            {
                this.suppressDraw = false;
                return;
            }
            if (this.BeginDraw())
            {
                this.Draw(this.gameTime);
                this.EndDraw();
            }
        }
References Microsoft.Xna.Framework.Game.accumulatedElapsedTime, Microsoft.Xna.Framework.Game.AdvanceElapsedTime(), Microsoft.Xna.Framework.Game.AssertNotDisposed(), Microsoft.Xna.Framework.Game.BeginDraw(), Microsoft.Xna.Framework.Game.currentAdapter, Microsoft.Xna.Framework.Game.Draw(), Microsoft.Xna.Framework.GameTime.ElapsedGameTime, Microsoft.Xna.Framework.Game.EndDraw(), Microsoft.Xna.Framework.Game.forceElapsedTimeToZero, System.TimeSpan.FromTicks(), Microsoft.Xna.Framework.Game.gameTime, Microsoft.Xna.Framework.Game.IsFixedTimeStep, Microsoft.Xna.Framework.GameTime.IsRunningSlowly, System.Math.Max(), Microsoft.Xna.Framework.Game.MaxElapsedTime, Microsoft.Xna.Framework.FNAPlatform.PollEvents, System.Threading.Thread.Sleep(), System.Threading.Thread.SpinWait(), Microsoft.Xna.Framework.Game.suppressDraw, Microsoft.Xna.Framework.Game.TargetElapsedTime, Microsoft.Xna.Framework.Game.textInputControlDown, Microsoft.Xna.Framework.Game.textInputSuppress, System.TimeSpan.Ticks, Microsoft.Xna.Framework.Game.Update(), Microsoft.Xna.Framework.Game.UpdateEstimatedSleepPrecision(), Microsoft.Xna.Framework.Game.updateFrameLag, Microsoft.Xna.Framework.Game.worstCaseSleepPrecision, and System.TimeSpan.Zero.
Referenced by Microsoft.Xna.Framework.Game.RunLoop(), and Microsoft.Xna.Framework.Game.RunOneFrame().