Terraria Decompiled: Microsoft.Xna.Framework.Game.Dispose
Dispose() [2/2]
virtual void Microsoft.Xna.Framework.Game.Dispose (bool disposing) inline protected virtual
Definition at line 406 of file Game.cs.
        {
            if (!this.isDisposed)
            {
                if (disposing)
                {
                    for (int i = 0; i < this.Components.Count; i++)
                    {
                        IDisposable disposable = this.Components[i] as IDisposable;
                        if (disposable != null)
{
                            disposable.Dispose();
                        }
                    }
                    if (this.Content != null)
                    {
                        this.Content.Dispose();
                    }
                    if (this.graphicsDeviceService != null)
                    {
                        (this.graphicsDeviceService as IDisposable).Dispose();
                    }
                    if (this.Window != null)
                    {
                        FNAPlatform.DisposeWindow(this.Window);
                    }
                    ContentTypeReaderManager.ClearTypeCreators();
                }
                AppDomain.CurrentDomain.UnhandledException -= this.OnUnhandledException;
                this.isDisposed = true;
            }
        }
References Microsoft.Xna.Framework.Content.ContentTypeReaderManager.ClearTypeCreators(), Microsoft.Xna.Framework.Game.Components, System.Collections.ObjectModel.Collection< T >.Count, Microsoft.Xna.Framework.Game.Dispose(), System.IDisposable.Dispose(), Microsoft.Xna.Framework.FNAPlatform.DisposeWindow, Microsoft.Xna.Framework.Game.graphicsDeviceService, Microsoft.Xna.Framework.Game.isDisposed, Microsoft.Xna.Framework.Game.OnUnhandledException(), and Microsoft.Xna.Framework.Game.Window.