Terraria Decompiled: Microsoft.Xna.Framework.Game.DoInitialize
DoInitialize()
void Microsoft.Xna.Framework.Game.DoInitialize () inline private
Definition at line 742 of file Game.cs.
        {
            this.AssertNotDisposed();
            this.graphicsDeviceManager = (IGraphicsDeviceManager)this.Services.GetService(typeof(IGraphicsDeviceManager));
            if (this.graphicsDeviceManager != null)
            {
                this.graphicsDeviceManager.CreateDevice();
            }
            this.Initialize();
            this.updateableComponents.Clear();
            this.drawableComponents.Clear();
            for (int i = 0; i < this.Components.Count; i++)
            {
                this.CategorizeComponent(this.Components[i]);
            }
            this.Components.ComponentAdded += this.OnComponentAdded;
            this.Components.ComponentRemoved += this.OnComponentRemoved;
        }
References Microsoft.Xna.Framework.Game.AssertNotDisposed(), Microsoft.Xna.Framework.Game.CategorizeComponent(), Microsoft.Xna.Framework.Game.Components, System.Collections.ObjectModel.Collection< T >.Count, Microsoft.Xna.Framework.IGraphicsDeviceManager.CreateDevice(), Microsoft.Xna.Framework.Game.drawableComponents, Microsoft.Xna.Framework.Game.graphicsDeviceManager, Microsoft.Xna.Framework.Game.Initialize(), Microsoft.Xna.Framework.Game.OnComponentAdded(), Microsoft.Xna.Framework.Game.OnComponentRemoved(), and Microsoft.Xna.Framework.Game.updateableComponents.
Referenced by Microsoft.Xna.Framework.Game.Run(), and Microsoft.Xna.Framework.Game.RunOneFrame().