Terraria Decompiled: Newtonsoft.Json.Converters.DiscriminatedUnionConverter.WriteJson
WriteJson()
override void Newtonsoft.Json.Converters.DiscriminatedUnionConverter.WriteJson (JsonWriter writer, object value, JsonSerializer serializer) inline
Definition at line 67 of file DiscriminatedUnionConverter.cs.
        {
            DefaultContractResolver defaultContractResolver = serializer.ContractResolver as DefaultContractResolver;
            Type type = DiscriminatedUnionConverter.UnionTypeLookupCache.Get(value.GetType());
            DiscriminatedUnionConverter.Union union = DiscriminatedUnionConverter.UnionCache.Get(type);
            int tag = (int)union.TagReader.Invoke(new object[] { value });
            DiscriminatedUnionConverter.UnionCase unionCase = Enumerable.Single<DiscriminatedUnionConverter.UnionCase>(union.Cases, (DiscriminatedUnionConverter.UnionCase c) => c.Tag == tag);
            writer.WriteStartObject();
            writer.WritePropertyName((defaultContractResolver != null) ? defaultContractResolver.GetResolvedPropertyName("Case") : "Case");
            writer.WriteValue(unionCase.Name);
            if (unionCase.Fields != null && unionCase.Fields.Length != 0)
            {
                object[] array = (object[])unionCase.FieldReader.Invoke(new object[] { value });
                writer.WritePropertyName((defaultContractResolver != null) ? defaultContractResolver.GetResolvedPropertyName("Fields") : "Fields");
                writer.WriteStartArray();
                foreach (object obj in array)
                {
                    serializer.Serialize(writer, obj);
                }
                writer.WriteEndArray();
            }
            writer.WriteEndObject();
        }
References System.array, Newtonsoft.Json.Converters.DiscriminatedUnionConverter.UnionCase.FieldReader, Newtonsoft.Json.Converters.DiscriminatedUnionConverter.UnionCase.Fields, Newtonsoft.Json.Utilities.ThreadSafeStore< TKey, TValue >.Get(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetResolvedPropertyName(), int, Newtonsoft.Json.Utilities.FSharpFunction.Invoke(), Newtonsoft.Json.Converters.DiscriminatedUnionConverter.UnionCase.Name, System.obj, Newtonsoft.Json.Converters.DiscriminatedUnionConverter.UnionTypeLookupCache, System.value, Newtonsoft.Json.JsonWriter.WritePropertyName(), Newtonsoft.Json.JsonWriter.WriteStartArray(), Newtonsoft.Json.JsonWriter.WriteStartObject(), and Newtonsoft.Json.JsonWriter.WriteValue().