Terraria Decompiled: Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CanConvert
CanConvert()
override bool Newtonsoft.Json.Converters.DiscriminatedUnionConverter.CanConvert (Type objectType) inline
Definition at line 165 of file DiscriminatedUnionConverter.cs.
        {
            if (typeof(IEnumerable).IsAssignableFrom(objectType))
            {
                return false;
            }
            object[] customAttributes = objectType.GetCustomAttributes(true);
            bool flag = false;
            object[] array = customAttributes;
            for (int i = 0; i < array.Length; i++)
            {
                Type type = array[i].GetType();
                if (type.FullName == "Microsoft.FSharp.Core.CompilationMappingAttribute")
                {
                    FSharpUtils.EnsureInitialized(type.Assembly());
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                return false;
            }
            MethodCall<object, object> isUnion = FSharpUtils.IsUnion;
            object obj = null;
            object[] array2 = new object[2];
            array2[0] = objectType;
            return (bool)isUnion(obj, array2);
        }
References System.array, System.Type.Assembly, Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized(), System.Type.FullName, System.Reflection.MemberInfo.GetCustomAttributes(), System.Type.GetType(), Newtonsoft.Json.Utilities.FSharpUtils.IsUnion, and System.obj.