Terraria Decompiled: Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.DiscriminatedUnionConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 92 of file DiscriminatedUnionConverter.cs.
        {
            if (reader.TokenType == JsonToken.Null)
            {
                return null;
            }
            DiscriminatedUnionConverter.UnionCase unionCase = null;
            string caseName = null;
            JArray jarray = null;
            reader.ReadAndAssert();
            Func<DiscriminatedUnionConverter.UnionCase, bool> <>9__0;
            while (reader.TokenType == JsonToken.PropertyName)
            {
                string text = reader.Value.ToString();
                if (string.Equals(text, "Case", 5))
                {
                    reader.ReadAndAssert();
                    DiscriminatedUnionConverter.Union union = DiscriminatedUnionConverter.UnionCache.Get(objectType);
                    caseName = reader.Value.ToString();
                    IEnumerable<DiscriminatedUnionConverter.UnionCase> cases = union.Cases;
                    Func<DiscriminatedUnionConverter.UnionCase, bool> func;
                    if ((func = <>9__0) == null)
                    {
                        func = (<>9__0 = (DiscriminatedUnionConverter.UnionCase c) => c.Name == caseName);
                    }
                    unionCase = Enumerable.SingleOrDefault<DiscriminatedUnionConverter.UnionCase>(cases, func);
                    if (unionCase == null)
                    {
                        throw JsonSerializationException.Create(reader, "No union type found with the name '{0}'.".FormatWith(CultureInfo.InvariantCulture, caseName));
                    }
                }
                else
                {
                    if (!string.Equals(text, "Fields", 5))
                    {
                        throw JsonSerializationException.Create(reader, "Unexpected property '{0}' found when reading union.".FormatWith(CultureInfo.InvariantCulture, text));
                    }
                    reader.ReadAndAssert();
                    if (reader.TokenType != JsonToken.StartArray)
                    {
                        throw JsonSerializationException.Create(reader, "Union fields must been an array.");
                    }
                    jarray = (JArray)JToken.ReadFrom(reader);
                }
                reader.ReadAndAssert();
            }
            if (unionCase == null)
            {
                throw JsonSerializationException.Create(reader, "No '{0}' property with union name found.".FormatWith(CultureInfo.InvariantCulture, "Case"));
            }
            object[] array = new object[unionCase.Fields.Length];
            if (unionCase.Fields.Length != 0 && jarray == null)
            {
                throw JsonSerializationException.Create(reader, "No '{0}' property with union fields found.".FormatWith(CultureInfo.InvariantCulture, "Fields"));
            }
            if (jarray != null)
            {
                if (unionCase.Fields.Length != jarray.Count)
                {
                    throw JsonSerializationException.Create(reader, "The number of field values does not match the number of properties defined by union '{0}'.".FormatWith(CultureInfo.InvariantCulture, caseName));
                }
                for (int i = 0; i < jarray.Count; i++)
                {
                    JToken jtoken = jarray[i];
                    PropertyInfo propertyInfo = unionCase.Fields[i];
                    array[i] = jtoken.ToObject(propertyInfo.PropertyType, serializer);
                }
            }
            object[] array2 = new object[] { array };
            return unionCase.Constructor.Invoke(array2);
        }
References System.array, Newtonsoft.Json.Converters.DiscriminatedUnionConverter.UnionCase.Constructor, Newtonsoft.Json.Linq.JContainer.Count, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Converters.DiscriminatedUnionConverter.UnionCase.Fields, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.FSharpFunction.Invoke(), System.Reflection.PropertyInfo.PropertyType, Newtonsoft.Json.JsonReader.ReadAndAssert(), Newtonsoft.Json.Linq.JToken.ReadFrom(), System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.Linq.JToken.ToObject(), and Newtonsoft.Json.JsonReader.Value.