Terraria Decompiled: Terraria.Audio.LegacyAudioSystem.UpdateAmbientCueState
UpdateAmbientCueState()
void Terraria.Audio.LegacyAudioSystem.UpdateAmbientCueState (int i, bool gameIsActive, ref float trackVolume, float systemVolume) inline
Implements Terraria.Audio.IAudioSystem.
Definition at line 208 of file LegacyAudioSystem.cs.
        {
            if (!this.WaveBank.IsPrepared || this.AudioTracks[i] == null)
            {
                return;
            }
            if (systemVolume == 0f)
            {
                if (this.AudioTracks[i].IsPlaying)
                {
                    this.AudioTracks[i].Stop(AudioStopOptions.Immediate);
                    return;
                }
            }
            else
            {
                if (!this.AudioTracks[i].IsPlaying)
                {
                    this.AudioTracks[i].Reuse();
                    this.AudioTracks[i].Play();
                    this.AudioTracks[i].SetVariable("Volume", trackVolume * systemVolume);
                    return;
                }
                if (this.AudioTracks[i].IsPaused && gameIsActive)
                {
                    this.AudioTracks[i].Resume();
                    return;
                }
                trackVolume += 0.005f;
                if (trackVolume > 1f)
                {
                    trackVolume = 1f;
                }
                this.AudioTracks[i].SetVariable("Volume", trackVolume * systemVolume);
            }
        }
References Terraria.Audio.LegacyAudioSystem.AudioTracks, Microsoft.Xna.Framework.Audio.WaveBank.IsPrepared, Terraria.Audio.IAudioTrack.Play(), Terraria.Audio.IAudioTrack.Resume(), Terraria.Audio.IAudioTrack.Reuse(), Terraria.Audio.IAudioTrack.SetVariable(), and Terraria.Audio.IAudioTrack.Stop().