Terraria Decompiled: Terraria.Audio.LegacyAudioSystem.LegacyAudioSystem
LegacyAudioSystem()
Terraria.Audio.LegacyAudioSystem.LegacyAudioSystem () inline
Definition at line 121 of file LegacyAudioSystem.cs.
        {
            this.Engine = new AudioEngine("Content\\TerrariaMusic.xgs");
            Console.WriteLine("SDL Audio Driver: " + SDL.SDL_GetCurrentAudioDriver());
            this.SoundBank = new SoundBank(this.Engine, "Content\\Sound Bank.xsb");
            this.Engine.Update();
            this.WaveBank = new WaveBank(this.Engine, "Content\\Wave Bank.xwb", 0, 512);
            this.Engine.Update();
            this.AudioTracks = new IAudioTrack[Main.maxMusic];
            this.TrackNamesByIndex = new Dictionary<int, string>();
            this.DefaultTrackByIndex = new Dictionary<int, IAudioTrack>();
            this.TrackLoopCounts = new int[Main.maxMusic];
            this.PlayCallbacks = new AudioTrackPlayCallback[Main.maxMusic];
        }
References Terraria.Audio.AudioTrackPlayCallback(), Terraria.Audio.LegacyAudioSystem.Engine, Terraria.Main.maxMusic, SDL3.SDL.SDL_GetCurrentAudioDriver(), Terraria.Audio.LegacyAudioSystem.SoundBank, Microsoft.Xna.Framework.Audio.AudioEngine.Update(), Terraria.Audio.LegacyAudioSystem.WaveBank, and System.Console.WriteLine().