Terraria Decompiled: Terraria.Audio.LegacyAudioSystem.LoadFromSources
LoadFromSources()
void Terraria.Audio.LegacyAudioSystem.LoadFromSources () inline
Implements Terraria.Audio.IAudioSystem.
Definition at line 17 of file LegacyAudioSystem.cs.
        {
            List<IContentSource> fileSources = this.FileSources;
            for (int i = 0; i < this.AudioTracks.Length; i++)
            {
                string text;
                if (this.TrackNamesByIndex.TryGetValue(i, out text))
                {
                    string text2 = "Music" + Path.DirectorySeparatorChar.ToString() + text;
                    IAudioTrack audioTrack = this.DefaultTrackByIndex[i];
                    IAudioTrack audioTrack2 = audioTrack;
                    IAudioTrack audioTrack3 = this.FindReplacementTrack(fileSources, text2);
                    if (audioTrack3 != null)
                    {
                        audioTrack2 = audioTrack3;
                    }
                    if (this.AudioTracks[i] != audioTrack2)
                    {
                        this.AudioTracks[i].Stop(AudioStopOptions.Immediate);
                    }
                    if (this.AudioTracks[i] != audioTrack)
                    {
                        this.AudioTracks[i].Dispose();
                    }
                    this.AudioTracks[i] = audioTrack2;
                }
            }
        }
References Terraria.Audio.LegacyAudioSystem.AudioTracks, Terraria.Audio.LegacyAudioSystem.DefaultTrackByIndex, System.IO.Path.DirectorySeparatorChar, System.IDisposable.Dispose(), Terraria.Audio.LegacyAudioSystem.FileSources, Terraria.Audio.LegacyAudioSystem.FindReplacementTrack(), Terraria.Audio.IAudioTrack.Stop(), System.text, Terraria.Audio.LegacyAudioSystem.TrackNamesByIndex, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by Terraria.Audio.LegacyAudioSystem.UseSources().