Terraria Decompiled: Terraria.Audio.LegacyAudioSystem.UpdateCommonTrack
UpdateCommonTrack()
void Terraria.Audio.LegacyAudioSystem.UpdateCommonTrack (bool active, int i, float totalVolume, ref float tempFade) inline
Implements Terraria.Audio.IAudioSystem.
Definition at line 280 of file LegacyAudioSystem.cs.
        {
            if (!this.WaveBank.IsPrepared || this.AudioTracks[i] == null)
            {
                return;
            }
            tempFade += 0.005f;
            if (tempFade > 1f)
            {
                tempFade = 1f;
            }
            if (!this.AudioTracks[i].IsPlaying && active)
            {
                this.AudioTracks[i].Reuse();
                this.AudioTracks[i].SetVariable("Volume", totalVolume);
                this.AudioTracks[i].Play();
                if (this.PlayCallbacks[i] != null)
                {
                    this.PlayCallbacks[i](i, this.TrackLoopCounts[i]);
                }
                this.TrackLoopCounts[i]++;
                return;
            }
            this.AudioTracks[i].SetVariable("Volume", totalVolume);
        }
References Terraria.Audio.LegacyAudioSystem.AudioTracks, Microsoft.Xna.Framework.Audio.WaveBank.IsPrepared, Terraria.Audio.IAudioTrack.Play(), Terraria.Audio.LegacyAudioSystem.PlayCallbacks, Terraria.Audio.IAudioTrack.Reuse(), Terraria.Audio.IAudioTrack.SetVariable(), and Terraria.Audio.LegacyAudioSystem.TrackLoopCounts.