Terraria Decompiled: Terraria.Audio.LegacyAudioSystem.Dispose
Dispose()
void Terraria.Audio.LegacyAudioSystem.Dispose () inline
Implements System.IDisposable.
Definition at line 350 of file LegacyAudioSystem.cs.
        {
            this.SoundBank.Dispose();
            this.WaveBank.Dispose();
            this.Engine.Dispose();
        }
References Microsoft.Xna.Framework.Audio.AudioEngine.Dispose(), Microsoft.Xna.Framework.Audio.SoundBank.Dispose(), Microsoft.Xna.Framework.Audio.WaveBank.Dispose(), and Terraria.Audio.LegacyAudioSystem.Engine.