Terraria Decompiled: Microsoft.Xna.Framework.Content.VideoReader.Read
Read()
override Video Microsoft.Xna.Framework.Content.VideoReader.Read (ContentReader input, Video existingInstance) inline package
Definition at line 12 of file VideoReader.cs.
        {
            string text = FileHelpers.ResolveRelativePath(Path.Combine(input.ContentManager.RootDirectoryFullPath, input.AssetName), input.ReadObject<string>());
            string text2 = VideoReader.Normalize(text.Substring(0, text.Length - 4));
            if (!string.IsNullOrEmpty(text2))
            {
                text = text2;
            }
            int num = input.ReadObject<int>();
            int num2 = input.ReadObject<int>();
            int num3 = input.ReadObject<int>();
            float num4 = input.ReadObject<float>();
            VideoSoundtrackType videoSoundtrackType = (VideoSoundtrackType)input.ReadObject<int>();
            return new Video(text, input.ContentManager.GetGraphicsDevice(), num, num2, num3, num4, videoSoundtrackType);
        }
References System.IO.Path.Combine(), System.input, Microsoft.Xna.Framework.Content.VideoReader.Normalize(), MonoGame.Utilities.FileHelpers.ResolveRelativePath(), and System.text.