Terraria Decompiled: System.Reflection.Emit.TypeBuilderInstantiation.InflateType
InflateType() [3/3]
static Type System.Reflection.Emit.TypeBuilderInstantiation.InflateType (Type type, Type[] type_args, Type[] method_args) inline static package
Definition at line 87 of file TypeBuilderInstantiation.cs.
        {
            if (type == null)
            {
                return null;
            }
            if (!type.IsGenericParameter && !type.ContainsGenericParameters)
            {
                return type;
            }
            if (type.IsGenericParameter)
            {
                if (type.DeclaringMethod == null)
                {
                    if (type_args != null)
                    {
                        return type_args[type.GenericParameterPosition];
                    }
                    return type;
                }
                else
                {
                    if (method_args != null)
                    {
                        return method_args[type.GenericParameterPosition];
                    }
                    return type;
                }
            }
            else
            {
                if (type.IsPointer)
                {
                    return TypeBuilderInstantiation.InflateType(type.GetElementType(), type_args, method_args).MakePointerType();
                }
                if (type.IsByRef)
                {
                    return TypeBuilderInstantiation.InflateType(type.GetElementType(), type_args, method_args).MakeByRefType();
                }
                if (!type.IsArray)
                {
                    Type[] genericArguments = type.GetGenericArguments();
                    for (int i = 0; i < genericArguments.Length; i++)
                    {
                        genericArguments[i] = TypeBuilderInstantiation.InflateType(genericArguments[i], type_args, method_args);
                    }
                    return (type.IsGenericTypeDefinition ? type : type.GetGenericTypeDefinition()).MakeGenericType(genericArguments);
                }
                if (type.GetArrayRank() > 1)
                {
                    return TypeBuilderInstantiation.InflateType(type.GetElementType(), type_args, method_args).MakeArrayType(type.GetArrayRank());
                }
                if (type.ToString().EndsWith("[*]", StringComparison.Ordinal))
                {
                    return TypeBuilderInstantiation.InflateType(type.GetElementType(), type_args, method_args).MakeArrayType(1);
                }
                return TypeBuilderInstantiation.InflateType(type.GetElementType(), type_args, method_args).MakeArrayType();
            }
        }
References System.Type.ContainsGenericParameters, System.Type.DeclaringMethod, System.Type.GenericParameterPosition, System.Type.GetArrayRank(), System.Type.GetElementType(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), System.Type.IsArray, System.Type.IsByRef, System.Type.IsGenericParameter, System.Type.IsGenericTypeDefinition, System.Type.IsPointer, System.Reflection.Emit.TypeBuilderInstantiation.MakeArrayType(), System.Type.MakeByRefType(), System.Reflection.Emit.TypeBuilderInstantiation.MakeGenericType(), System.Type.MakePointerType(), System.Type.ToString(), and System.Reflection.TypeInfo.type.