Terraria Decompiled: System.DateTimeFormat.GetAllDateTimes
GetAllDateTimes() [1/2]
static string[] System.DateTimeFormat.GetAllDateTimes (DateTime dateTime, char format, DateTimeFormatInfo dtfi) inline static package
Definition at line 1034 of file DateTimeFormat.cs.
        {
            string[] array;
            string[] array2;
            if (format <= 'U')
            {
                switch (format)
                {
                case 'D':
                case 'F':
                case 'G':
                    break;
                case 'E':
                    goto IL_0138;
                default:
                    switch (format)
                    {
                    case 'M':
                    case 'T':
                        break;
                    case 'N':
                    case 'P':
                    case 'Q':
                    case 'S':
                        goto IL_0138;
                    case 'O':
                    case 'R':
                        goto IL_011E;
                    case 'U':
                    {
                        DateTime dateTime2 = dateTime.ToUniversalTime();
                        array = dtfi.GetAllDateTimePatterns(format);
                        array2 = new string[array.Length];
                        for (int i = 0; i < array.Length; i++)
{
                            array2[i] = DateTimeFormat.Format(dateTime2, array[i], dtfi);
                        }
                        return array2;
                    }
                    default:
                        goto IL_0138;
                    }
                    break;
                }
            }
            else if (format != 'Y')
            {
                switch (format)
                {
                case 'd':
                case 'f':
                case 'g':
                    break;
                case 'e':
                    goto IL_0138;
                default:
                    switch (format)
                    {
                    case 'm':
                    case 't':
                    case 'y':
                        break;
                    case 'n':
                    case 'p':
                    case 'q':
                    case 'v':
                    case 'w':
                    case 'x':
                        goto IL_0138;
                    case 'o':
                    case 'r':
                    case 's':
                    case 'u':
                        goto IL_011E;
                    default:
                        goto IL_0138;
                    }
                    break;
                }
            }
            array = dtfi.GetAllDateTimePatterns(format);
            array2 = new string[array.Length];
            for (int j = 0; j < array.Length; j++)
            {
                array2[j] = DateTimeFormat.Format(dateTime, array[j], dtfi);
            }
            return array2;
            IL_011E:
            return new string[] { DateTimeFormat.Format(dateTime, new string(format, 1), dtfi) };
            IL_0138:
            throw new FormatException("Input string was not in a correct format.");
        }
References System.array, System.DateTimeFormat.Format(), System.format, and System.DateTime.ToUniversalTime().
Referenced by System.DateTimeFormat.GetAllDateTimes(), System.DateTime.GetDateTimeFormats(), and System.DateTime.GetDateTimeFormats().