Terraria Decompiled: System.DateTimeFormat.TryFormatO
TryFormatO()
static unsafe bool System.DateTimeFormat.TryFormatO (DateTime dateTime, TimeSpan offset, Span< char > destination, out int charsWritten) inline static private
Definition at line 885 of file DateTimeFormat.cs.
        {
            int num = 27;
            DateTimeKind dateTimeKind = DateTimeKind.Local;
            if (offset == DateTimeFormat.NullOffset)
            {
                dateTimeKind = dateTime.Kind;
                if (dateTimeKind == DateTimeKind.Local)
                {
                    offset = TimeZoneInfo.Local.GetUtcOffset(dateTime);
                    num += 6;
                }
                else if (dateTimeKind == DateTimeKind.Utc)
                {
                    num++;
                }
            }
            else
            {
                num += 6;
            }
            if (destination.Length < num)
            {
                charsWritten = 0;
                return false;
            }
            charsWritten = num;
            ref char ptr = ref destination[26];
            DateTimeFormat.WriteFourDecimalDigits((uint)dateTime.Year, destination, 0);
            *destination[4] = '-';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Month, destination, 5);
            *destination[7] = '-';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Day, destination, 8);
            *destination[10] = 'T';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Hour, destination, 11);
            *destination[13] = ':';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Minute, destination, 14);
            *destination[16] = ':';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Second, destination, 17);
            *destination[19] = '.';
            DateTimeFormat.WriteDigits((ulong)((uint)(dateTime.Ticks % 10000000L)), destination.Slice(20, 7));
            if (dateTimeKind == DateTimeKind.Local)
            {
                char c;
                if (offset < default(TimeSpan))
                {
                    c = '-';
                    offset = TimeSpan.FromTicks(-offset.Ticks);
                }
                else
                {
                    c = '+';
                }
                DateTimeFormat.WriteTwoDecimalDigits((uint)offset.Minutes, destination, 31);
                *destination[30] = ':';
                DateTimeFormat.WriteTwoDecimalDigits((uint)offset.Hours, destination, 28);
                *destination[27] = c;
            }
            else if (dateTimeKind == DateTimeKind.Utc)
            {
                *destination[27] = 'Z';
            }
            return true;
        }
References System.DateTime.Day, System.destination, System.TimeSpan.FromTicks(), System.TimeZoneInfo.GetUtcOffset(), System.DateTime.Hour, System.DateTime.Kind, System.L, System.TimeZoneInfo.Local, System.DateTime.Minute, System.DateTime.Month, System.DateTimeFormat.NullOffset, System.offset, System.DateTime.Second, System.DateTime.Ticks, System.DateTimeFormat.WriteDigits(), System.DateTimeFormat.WriteFourDecimalDigits(), System.DateTimeFormat.WriteTwoDecimalDigits(), and System.DateTime.Year.
Referenced by System.DateTimeFormat.Format(), and System.DateTimeFormat.TryFormat().