Terraria Decompiled: System.DateTimeFormat.TryFormat
TryFormat() [2/2]
static unsafe bool System.DateTimeFormat.TryFormat (DateTime dateTime, Span< char > destination, out int charsWritten, ReadOnlySpan< char > format, IFormatProvider provider, TimeSpan offset) inline static package
Definition at line 793 of file DateTimeFormat.cs.
        {
            if (format.Length == 1)
            {
                char c = (char)(*format[0]);
                if (c <= 'R')
                {
                    if (c != 'O')
                    {
                        if (c != 'R')
{
                            goto IL_0047;
                        }
                        goto IL_003C;
                    }
                }
                else if (c != 'o')
                {
                    if (c != 'r')
                    {
                        goto IL_0047;
                    }
                    goto IL_003C;
                }
                return DateTimeFormat.TryFormatO(dateTime, offset, destination, out charsWritten);
                IL_003C:
                return DateTimeFormat.TryFormatR(dateTime, offset, destination, out charsWritten);
            }
            IL_0047:
            DateTimeFormatInfo instance = DateTimeFormatInfo.GetInstance(provider);
            StringBuilder stringBuilder = DateTimeFormat.FormatStringBuilder(dateTime, format, instance, offset);
            bool flag = stringBuilder.Length <= destination.Length;
            if (flag)
            {
                stringBuilder.CopyTo(0, destination, stringBuilder.Length);
                charsWritten = stringBuilder.Length;
            }
            else
            {
                charsWritten = 0;
            }
            StringBuilderCache.Release(stringBuilder);
            return flag;
        }
References System.Text.StringBuilder.CopyTo(), System.destination, System.format, System.DateTimeFormat.FormatStringBuilder(), System.Globalization.DateTimeFormatInfo.GetInstance(), System.Text.StringBuilder.Length, System.offset, System.Text.StringBuilderCache.Release(), System.DateTimeFormat.TryFormatO(), and System.DateTimeFormat.TryFormatR().