Terraria Decompiled: System.DateTimeFormat.Format
Format() [2/2]
static unsafe string System.DateTimeFormat.Format (DateTime dateTime, string format, IFormatProvider provider, TimeSpan offset) inline static package
Definition at line 747 of file DateTimeFormat.cs.
        {
            if (format != null && format.Length == 1)
            {
                char c = format[0];
                if (c <= 'R')
                {
                    if (c != 'O')
                    {
                        if (c != 'R')
{
                            goto IL_0093;
                        }
                        goto IL_006E;
                    }
                }
                else if (c != 'o')
                {
                    if (c != 'r')
                    {
                        goto IL_0093;
                    }
                    goto IL_006E;
                }
                Span<char> span = new Span<char>(stackalloc byte[(UIntPtr)66], 33);
                int num;
                DateTimeFormat.TryFormatO(dateTime, offset, span, out num);
                return span.Slice(0, num).ToString();
                IL_006E:
                string text = string.FastAllocateString(29);
                int num2;
                DateTimeFormat.TryFormatR(dateTime, offset, new Span<char>(text.GetRawStringData(), text.Length), out num2);
                return text;
            }
            IL_0093:
            DateTimeFormatInfo instance = DateTimeFormatInfo.GetInstance(provider);
            return StringBuilderCache.GetStringAndRelease(DateTimeFormat.FormatStringBuilder(dateTime, format, instance, offset));
        }
References System.format, System.DateTimeFormat.FormatStringBuilder(), System.Globalization.DateTimeFormatInfo.GetInstance(), System.Text.StringBuilderCache.GetStringAndRelease(), System.offset, System.Span< T >.Slice(), System.text, System.DateTimeFormat.TryFormatO(), and System.DateTimeFormat.TryFormatR().