Terraria Decompiled: System.DateTimeFormat.FormatCustomized
FormatCustomized()
static unsafe StringBuilder System.DateTimeFormat.FormatCustomized (DateTime dateTime, ReadOnlySpan< char > format, DateTimeFormatInfo dtfi, TimeSpan offset, StringBuilder result) inline static private
Definition at line 186 of file DateTimeFormat.cs.
        {
            Calendar calendar = dtfi.Calendar;
            bool flag = false;
            if (result == null)
            {
                flag = true;
                result = StringBuilderCache.Acquire(16);
            }
            bool flag2 = !GlobalizationMode.Invariant && (ushort)calendar.ID == 8;
            bool flag3 = !GlobalizationMode.Invariant && (ushort)calendar.ID == 3;
            bool flag4 = true;
            int i = 0;
            while (i < format.Length)
            {
                char c = (char)(*format[i]);
                int num2;
                if (c <= 'K')
                {
                    if (c <= '/')
                    {
                        if (c <= '%')
{
                            if (c != '"')
{
                                if (c != '%')
{
                                    goto IL_0686;
                                }
                                int num = DateTimeFormat.ParseNextChar(format, i);
                                if (num >= 0 && num != 37)
{
                                    char c2 = (char)num;
                                    DateTimeFormat.FormatCustomized(dateTime, MemoryMarshal.CreateReadOnlySpan<char>(ref c2, 1), dtfi, offset, result);
                                    num2 = 2;
                                    goto IL_0693;
                                }
                                if (flag)
{
                                    StringBuilderCache.Release(result);
                                }
                                throw new FormatException("Input string was not in a correct format.");
                            }
                        }
                        else if (c != '\'')
{
                            if (c != '/')
{
                                goto IL_0686;
                            }
                            result.Append(dtfi.DateSeparator);
                            num2 = 1;
                            goto IL_0693;
                        }
                        num2 = DateTimeFormat.ParseQuoteString(format, i, result);
                    }
                    else if (c <= 'F')
                    {
                        if (c != ':')
{
                            if (c != 'F')
{
                                goto IL_0686;
                            }
                            goto IL_0209;
                        }
                        else
{
                            result.Append(dtfi.TimeSeparator);
                            num2 = 1;
                        }
                    }
                    else if (c != 'H')
                    {
                        if (c != 'K')
{
                            goto IL_0686;
                        }
                        num2 = 1;
                        DateTimeFormat.FormatCustomizedRoundripTimeZone(dateTime, offset, result);
                    }
                    else
                    {
                        num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                        DateTimeFormat.FormatDigits(result, dateTime.Hour, num2);
                    }
                }
                else if (c <= 'm')
                {
                    if (c <= '\\')
                    {
                        if (c != 'M')
{
                            if (c != '\\')
{
                                goto IL_0686;
                            }
                            int num = DateTimeFormat.ParseNextChar(format, i);
                            if (num < 0)
{
                                if (flag)
{
                                    StringBuilderCache.Release(result);
                                }
                                throw new FormatException("Input string was not in a correct format.");
                            }
                            result.Append((char)num);
                            num2 = 2;
                        }
                        else
{
                            num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            int month = calendar.GetMonth(dateTime);
                            if (num2 <= 2)
{
                                if (flag2 && !GlobalizationMode.Invariant)
{
                                    DateTimeFormat.HebrewFormatDigits(result, month);
                                }
                                else
{
                                    DateTimeFormat.FormatDigits(result, month, num2);
                                }
                            }
                            else if (flag2 && !GlobalizationMode.Invariant)
{
                                result.Append(DateTimeFormat.FormatHebrewMonthName(dateTime, month, num2, dtfi));
                            }
                            else if ((dtfi.FormatFlags & DateTimeFormatFlags.UseGenitiveMonth) != DateTimeFormatFlags.None && num2 >= 4)
{
                                result.Append(dtfi.internalGetMonthName(month, DateTimeFormat.IsUseGenitiveForm(format, i, num2, 'd') ? MonthNameStyles.Genitive : MonthNameStyles.Regular, false));
                            }
                            else
{
                                result.Append(DateTimeFormat.FormatMonth(month, num2, dtfi));
                            }
                            flag4 = false;
                        }
                    }
                    else
                    {
                        switch (c)
{
                        case 'd':
                            num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            if (num2 <= 2)
{
                                int dayOfMonth = calendar.GetDayOfMonth(dateTime);
                                if (flag2 && !GlobalizationMode.Invariant)
{
                                    DateTimeFormat.HebrewFormatDigits(result, dayOfMonth);
                                }
                                else
{
                                    DateTimeFormat.FormatDigits(result, dayOfMonth, num2);
                                }
                            }
                            else
{
                                int dayOfWeek = (int)calendar.GetDayOfWeek(dateTime);
                                result.Append(DateTimeFormat.FormatDayOfWeek(dayOfWeek, num2, dtfi));
                            }
                            flag4 = false;
                            break;
                        case 'e':
                            goto IL_0686;
                        case 'f':
                            goto IL_0209;
                        case 'g':
                            num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            result.Append(dtfi.GetEraName(calendar.GetEra(dateTime)));
                            break;
                        case 'h':
{
                            num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            int num3 = dateTime.Hour % 12;
                            if (num3 == 0)
{
                                num3 = 12;
                            }
                            DateTimeFormat.FormatDigits(result, num3, num2);
                            break;
                        }
                        default:
                            if (c != 'm')
{
                                goto IL_0686;
                            }
                            num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                            DateTimeFormat.FormatDigits(result, dateTime.Minute, num2);
                            break;
                        }
                    }
                }
                else if (c <= 't')
                {
                    if (c != 's')
                    {
                        if (c != 't')
{
                            goto IL_0686;
                        }
                        num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                        if (num2 == 1)
{
                            if (dateTime.Hour < 12)
{
                                if (dtfi.AMDesignator.Length >= 1)
{
                                    result.Append(dtfi.AMDesignator[0]);
                                }
                            }
                            else if (dtfi.PMDesignator.Length >= 1)
{
                                result.Append(dtfi.PMDesignator[0]);
                            }
                        }
                        else
{
                            result.Append((dateTime.Hour < 12) ? dtfi.AMDesignator : dtfi.PMDesignator);
                        }
                    }
                    else
                    {
                        num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                        DateTimeFormat.FormatDigits(result, dateTime.Second, num2);
                    }
                }
                else if (c != 'y')
                {
                    if (c != 'z')
                    {
                        goto IL_0686;
                    }
                    num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                    DateTimeFormat.FormatCustomizedTimeZone(dateTime, offset, format, num2, flag4, result);
                }
                else
                {
                    int year = calendar.GetYear(dateTime);
                    num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                    if (flag3 && !AppContextSwitches.FormatJapaneseFirstYearAsANumber && year == 1 && i + num2 < format.Length - 1 && *format[i + num2] == 39 && *format[i + num2 + 1] == (ushort)"年"[0])
                    {
                        result.Append("元"[0]);
                    }
                    else if (dtfi.HasForceTwoDigitYears)
                    {
                        DateTimeFormat.FormatDigits(result, year, (num2 <= 2) ? num2 : 2);
                    }
                    else if (flag2 && !GlobalizationMode.Invariant)
                    {
                        DateTimeFormat.HebrewFormatDigits(result, year);
                    }
                    else if (num2 <= 2)
                    {
                        DateTimeFormat.FormatDigits(result, year % 100, num2);
                    }
                    else
                    {
                        string text = "D" + num2.ToString();
                        result.Append(year.ToString(text, CultureInfo.InvariantCulture));
                    }
                    flag4 = false;
                }
                IL_0693:
                i += num2;
                continue;
                IL_0209:
                num2 = DateTimeFormat.ParseRepeatPattern(format, i, c);
                if (num2 > 7)
                {
                    if (flag)
                    {
                        StringBuilderCache.Release(result);
                    }
                    throw new FormatException("Input string was not in a correct format.");
                }
                long num4 = dateTime.Ticks % 10000000L;
                num4 /= (long)Math.Pow(10.0, (double)(7 - num2));
                if (c == 'f')
                {
                    result.Append(((int)num4).ToString(DateTimeFormat.fixedNumberFormats[num2 - 1], CultureInfo.InvariantCulture));
                    goto IL_0693;
                }
                int num5 = num2;
                while (num5 > 0 && num4 % 10L == 0L)
                {
                    num4 /= 10L;
                    num5--;
                }
                if (num5 > 0)
                {
                    result.Append(((int)num4).ToString(DateTimeFormat.fixedNumberFormats[num5 - 1], CultureInfo.InvariantCulture));
                    goto IL_0693;
                }
                if (result.Length > 0 && result[result.Length - 1] == '.')
                {
                    result.Remove(result.Length - 1, 1);
                    goto IL_0693;
                }
                goto IL_0693;
                IL_0686:
                result.Append(c);
                num2 = 1;
                goto IL_0693;
            }
            return result;
        }
References System.Text.StringBuilderCache.Acquire(), System.Globalization.DateTimeFormatInfo.AMDesignator, System.Text.StringBuilder.Append(), System.Globalization.DateTimeFormatInfo.Calendar, System.Globalization.DateTimeFormatInfo.DateSeparator, System.DateTimeFormat.fixedNumberFormats, System.format, System.DateTimeFormat.FormatCustomized(), System.DateTimeFormat.FormatCustomizedRoundripTimeZone(), System.DateTimeFormat.FormatCustomizedTimeZone(), System.DateTimeFormat.FormatDayOfWeek(), System.DateTimeFormat.FormatDigits(), System.DateTimeFormat.FormatHebrewMonthName(), System.AppContextSwitches.FormatJapaneseFirstYearAsANumber, System.DateTimeFormat.FormatMonth(), System.Globalization.Calendar.GetDayOfMonth(), System.Globalization.Calendar.GetDayOfWeek(), System.Globalization.Calendar.GetEra(), System.Globalization.DateTimeFormatInfo.GetEraName(), System.Globalization.Calendar.GetMonth(), System.Globalization.Calendar.GetYear(), System.DateTimeFormat.HebrewFormatDigits(), System.DateTime.Hour, System.Globalization.Calendar.ID, int, System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureInfo.InvariantCulture, System.DateTimeFormat.IsUseGenitiveForm(), System.L, System.Text.StringBuilder.Length, long, System.DateTime.Minute, System.offset, System.DateTimeFormat.ParseNextChar(), System.DateTimeFormat.ParseQuoteString(), System.DateTimeFormat.ParseRepeatPattern(), System.Globalization.DateTimeFormatInfo.PMDesignator, System.Math.Pow(), System.Text.StringBuilderCache.Release(), System.Text.StringBuilder.Remove(), System.DateTime.Second, System.text, and System.ToString.
Referenced by System.DateTimeFormat.FormatCustomized(), and System.DateTimeFormat.FormatStringBuilder().