Terraria Decompiled: System.DateTimeFormat.TryFormatR
TryFormatR()
static unsafe bool System.DateTimeFormat.TryFormatR (DateTime dateTime, TimeSpan offset, Span< char > destination, out int charsWritten) inline static private
Definition at line 951 of file DateTimeFormat.cs.
        {
            if (28 >= destination.Length)
            {
                charsWritten = 0;
                return false;
            }
            if (offset != DateTimeFormat.NullOffset)
            {
                dateTime -= offset;
            }
            int num;
            int num2;
            int num3;
            dateTime.GetDatePart(out num, out num2, out num3);
            string text = DateTimeFormat.InvariantAbbreviatedDayNames[(int)dateTime.DayOfWeek];
            string text2 = DateTimeFormat.InvariantAbbreviatedMonthNames[num2 - 1];
            *destination[0] = text[0];
            *destination[1] = text[1];
            *destination[2] = text[2];
            *destination[3] = ',';
            *destination[4] = ' ';
            DateTimeFormat.WriteTwoDecimalDigits((uint)num3, destination, 5);
            *destination[7] = ' ';
            *destination[8] = text2[0];
            *destination[9] = text2[1];
            *destination[10] = text2[2];
            *destination[11] = ' ';
            DateTimeFormat.WriteFourDecimalDigits((uint)num, destination, 12);
            *destination[16] = ' ';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Hour, destination, 17);
            *destination[19] = ':';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Minute, destination, 20);
            *destination[22] = ':';
            DateTimeFormat.WriteTwoDecimalDigits((uint)dateTime.Second, destination, 23);
            *destination[25] = ' ';
            *destination[26] = 'G';
            *destination[27] = 'M';
            *destination[28] = 'T';
            charsWritten = 29;
            return true;
        }
References System.DateTime.DayOfWeek, System.destination, System.DateTime.GetDatePart(), System.DateTime.Hour, int, System.DateTimeFormat.InvariantAbbreviatedDayNames, System.DateTimeFormat.InvariantAbbreviatedMonthNames, System.DateTime.Minute, System.DateTimeFormat.NullOffset, System.offset, System.DateTime.Second, System.text, System.DateTimeFormat.WriteFourDecimalDigits(), and System.DateTimeFormat.WriteTwoDecimalDigits().
Referenced by System.DateTimeFormat.Format(), and System.DateTimeFormat.TryFormat().