Terraria Decompiled: System.DateTimeFormat.FormatStringBuilder
FormatStringBuilder()
static StringBuilder System.DateTimeFormat.FormatStringBuilder (DateTime dateTime, ReadOnlySpan< char > format, DateTimeFormatInfo dtfi, TimeSpan offset) inline static private
Definition at line 839 of file DateTimeFormat.cs.
        {
            if (format.Length == 0)
            {
                bool flag = false;
                if (dateTime.Ticks < 864000000000L)
                {
                    CalendarId calendarId = (CalendarId)dtfi.Calendar.ID;
                    switch (calendarId)
                    {
                    case CalendarId.JAPAN:
                    case CalendarId.TAIWAN:
                    case CalendarId.HIJRI:
                    case CalendarId.HEBREW:
                        break;
                    case CalendarId.KOREA:
                    case CalendarId.THAI:
                        goto IL_0062;
                    default:
                        if (calendarId != CalendarId.JULIAN && calendarId - CalendarId.PERSIAN > 1)
{
                            goto IL_0062;
                        }
                        break;
                    }
                    flag = true;
                    dtfi = DateTimeFormatInfo.InvariantInfo;
                }
                IL_0062:
                if (offset == DateTimeFormat.NullOffset)
                {
                    format = (flag ? "s" : "G");
                }
                else
                {
                    format = (flag ? "yyyy'-'MM'-'ddTHH':'mm':'ss zzz" : dtfi.DateTimeOffsetPattern);
                }
            }
            if (format.Length == 1)
            {
                format = DateTimeFormat.ExpandPredefinedFormat(format, ref dateTime, ref dtfi, ref offset);
            }
            return DateTimeFormat.FormatCustomized(dateTime, format, dtfi, offset, null);
        }
References System.Globalization.DateTimeFormatInfo.Calendar, System.DateTimeFormat.ExpandPredefinedFormat(), System.format, System.DateTimeFormat.FormatCustomized(), System.Globalization.Calendar.ID, System.Globalization.DateTimeFormatInfo.InvariantInfo, System.L, System.DateTimeFormat.NullOffset, System.offset, and System.DateTime.Ticks.
Referenced by System.DateTimeFormat.Format(), and System.DateTimeFormat.TryFormat().