Terraria Decompiled: System.DateTimeFormat.ExpandPredefinedFormat
ExpandPredefinedFormat()
static unsafe string System.DateTimeFormat.ExpandPredefinedFormat (ReadOnlySpan< char > format, ref DateTime dateTime, ref DateTimeFormatInfo dtfi, ref TimeSpan offset) inline static private
Definition at line 666 of file DateTimeFormat.cs.
        {
            char c = (char)(*format[0]);
            if (c <= 'R')
            {
                if (c != 'O')
                {
                    if (c != 'R')
                    {
                        goto IL_015D;
                    }
                    goto IL_005C;
                }
            }
            else if (c != 'U')
            {
                switch (c)
                {
                case 'o':
                    break;
                case 'p':
                case 'q':
                case 't':
                    goto IL_015D;
                case 'r':
                    goto IL_005C;
                case 's':
                    dtfi = DateTimeFormatInfo.InvariantInfo;
                    goto IL_015D;
                case 'u':
                    if (offset != DateTimeFormat.NullOffset)
                    {
                        dateTime -= offset;
                    }
                    else if (dateTime.Kind == DateTimeKind.Local)
                    {
                        DateTimeFormat.InvalidFormatForLocal(format, dateTime);
                    }
                    dtfi = DateTimeFormatInfo.InvariantInfo;
                    goto IL_015D;
                default:
                    goto IL_015D;
                }
            }
            else
            {
                if (offset != DateTimeFormat.NullOffset)
                {
                    throw new FormatException("Input string was not in a correct format.");
                }
                dtfi = (DateTimeFormatInfo)dtfi.Clone();
                if (dtfi.Calendar.GetType() != typeof(GregorianCalendar))
                {
                    dtfi.Calendar = GregorianCalendar.GetDefaultInstance();
                }
                dateTime = dateTime.ToUniversalTime();
                goto IL_015D;
            }
            dtfi = DateTimeFormatInfo.InvariantInfo;
            goto IL_015D;
            IL_005C:
            if (offset != DateTimeFormat.NullOffset)
            {
                dateTime -= offset;
            }
            else if (dateTime.Kind == DateTimeKind.Local)
            {
                DateTimeFormat.InvalidFormatForLocal(format, dateTime);
            }
            dtfi = DateTimeFormatInfo.InvariantInfo;
            IL_015D:
            return DateTimeFormat.GetRealFormat(format, dtfi);
        }
References System.format, System.Globalization.GregorianCalendar.GetDefaultInstance(), System.DateTimeFormat.GetRealFormat(), System.DateTimeFormat.InvalidFormatForLocal(), System.Globalization.DateTimeFormatInfo.InvariantInfo, System.DateTimeFormat.NullOffset, and System.offset.
Referenced by System.DateTimeFormat.FormatStringBuilder().