Terraria Decompiled: System.DateTimeFormat.ParseQuoteString
ParseQuoteString()
static unsafe int System.DateTimeFormat.ParseQuoteString (ReadOnlySpan< char > format, int pos, StringBuilder result) inline static package
Definition at line 101 of file DateTimeFormat.cs.
        {
            int length = format.Length;
            int num = pos;
            char c = (char)(*format[pos++]);
            bool flag = false;
            while (pos < length)
            {
                char c2 = (char)(*format[pos++]);
                if (c2 == c)
                {
                    flag = true;
                    break;
                }
                if (c2 == '\\')
                {
                    if (pos >= length)
                    {
                        throw new FormatException("Input string was not in a correct format.");
                    }
                    result.Append((char)(*format[pos++]));
                }
                else
                {
                    result.Append(c2);
                }
            }
            if (!flag)
            {
                throw new FormatException(string.Format(CultureInfo.CurrentCulture, "Cannot find a matching quote character for the character '{0}'.", c));
            }
            return pos - num;
        }
References System.Text.StringBuilder.Append(), System.Globalization.CultureInfo.CurrentCulture, System.format, System.Format, and System.length.
Referenced by System.DateTimeFormat.FormatCustomized(), and System.Globalization.TimeSpanFormat.FormatCustomized().