Terraria Decompiled: Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError
ShowFileSavingFailError()
static void Terraria.UI.FancyErrorPrinter.ShowFileSavingFailError (Exception exception, string filePath) inline static
Definition at line 52 of file FancyErrorPrinter.cs.
        {
            bool flag = false;
            if (exception is UnauthorizedAccessException)
            {
                flag = true;
            }
            if (exception is FileNotFoundException)
            {
                flag = true;
            }
            if (exception is DirectoryNotFoundException)
            {
                flag = true;
            }
            if (!flag)
            {
                return;
            }
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("Failed to create the file: \"" + filePath.Replace("/", "\\") + "\"!");
            List<string> list = new List<string>();
            list.Add("If you are using an Anti-virus, please make sure it does not block Terraria in any way.");
            list.Add("Try making sure your `Documents/My Games/Terraria` folder is not set to 'read-only'.");
            list.Add("Try to verify/repair the game installation.");
            if (filePath.ToLower().Contains("onedrive"))
            {
                list.Add("Try updating OneDrive.");
            }
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Suggestions:");
            FancyErrorPrinter.AppendSuggestions(stringBuilder, list);
            stringBuilder.AppendLine();
            FancyErrorPrinter.IncludeOriginalMessage(stringBuilder, exception);
            FancyErrorPrinter.ShowTheBox(stringBuilder.ToString());
            Console.WriteLine(stringBuilder.ToString());
        }
References System.Text.StringBuilder.AppendLine(), Terraria.UI.FancyErrorPrinter.AppendSuggestions(), System.exception, Terraria.UI.FancyErrorPrinter.IncludeOriginalMessage(), System.list, Terraria.UI.FancyErrorPrinter.ShowTheBox(), System.Text.StringBuilder.ToString(), and System.Console.WriteLine().
Referenced by Terraria.IO.FavoritesFile.Save(), Terraria.Achievements.AchievementManager.Save(), Terraria.Player.SavePlayer(), and Terraria.IO.WorldFile.SaveWorld().