Terraria Decompiled: Terraria.UI.FancyErrorPrinter.ShowFailedToLoadAssetError
ShowFailedToLoadAssetError()
static void Terraria.UI.FancyErrorPrinter.ShowFailedToLoadAssetError (Exception exception, string filePath) inline static
Definition at line 14 of file FancyErrorPrinter.cs.
        {
            bool flag = false;
            if (exception is UnauthorizedAccessException)
            {
                flag = true;
            }
            if (exception is FileNotFoundException)
            {
                flag = true;
            }
            if (exception is DirectoryNotFoundException)
            {
                flag = true;
            }
            if (exception is AssetLoadException)
            {
                flag = true;
            }
            if (!flag)
            {
                return;
            }
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine("Failed to load asset: \"" + filePath.Replace("/", "\\") + "\"!");
            List<string> list = new List<string>();
            list.Add("Try to verify/repair the game installation, the asset may be missing.");
            list.Add("If you are using an Anti-virus, please make sure it does not block Terraria in any way.");
            stringBuilder.AppendLine();
            stringBuilder.AppendLine("Suggestions:");
            FancyErrorPrinter.AppendSuggestions(stringBuilder, list);
            stringBuilder.AppendLine();
            FancyErrorPrinter.IncludeOriginalMessage(stringBuilder, exception);
            FancyErrorPrinter.ShowTheBox(stringBuilder.ToString());
            Console.WriteLine(stringBuilder.ToString());
        }
References System.Text.StringBuilder.AppendLine(), Terraria.UI.FancyErrorPrinter.AppendSuggestions(), System.exception, Terraria.UI.FancyErrorPrinter.IncludeOriginalMessage(), System.list, Terraria.UI.FancyErrorPrinter.ShowTheBox(), System.Text.StringBuilder.ToString(), and System.Console.WriteLine().
Referenced by Terraria.Main.OnceFailedLoadingAnAsset(), and Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.UpdateImagePreview().