Terraria Decompiled: Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Initialize
Initialize()
void Terraria.GameContent.Creative.CreativeItemSacrificesCatalog.Initialize () inline
Definition at line 22 of file CreativeItemSacrificesCatalog.cs.
        {
            this._sacrificeCountNeededByItemId.Clear();
            foreach (string text in Regex.Split(Utils.ReadEmbeddedResource("Terraria.GameContent.Creative.Content.Sacrifices.tsv"), "\r\n|\r|\n"))
            {
                if (!text.StartsWith("//"))
                {
                    string[] array2 = text.Split(new char[] { '\t' });
                    int num;
                    if (array2.Length >= 3 && ItemID.Search.TryGetId(array2[0], ref num))
                    {
                        int num2 = 0;
                        bool flag = false;
                        string text2 = array2[1].ToLower();
                        uint num3 = <PrivateImplementationDetails>.ComputeStringHash(text2);
                        if (num3 <= 3876335077U)
{
                            if (num3 <= 3792446982U)
{
                                if (num3 <= 3758891744U)
{
                                    if (num3 != 2166136261U)
{
                                        if (num3 != 3758891744U)
{
                                            goto IL_0352;
                                        }
                                        if (!(text2 == "e"))
{
                                            goto IL_0352;
                                        }
                                        flag = true;
                                        goto IL_036C;
                                    }
                                    else
{
                                        if (text2 == null)
{
                                            goto IL_0352;
                                        }
                                        if (text2.Length != 0)
{
                                            goto IL_0352;
                                        }
                                    }
                                }
                                else if (num3 != 3775669363U)
{
                                    if (num3 != 3792446982U)
{
                                        goto IL_0352;
                                    }
                                    if (!(text2 == "g"))
{
                                        goto IL_0352;
                                    }
                                    num2 = 3;
                                    goto IL_036C;
                                }
                                else
{
                                    if (!(text2 == "d"))
{
                                        goto IL_0352;
                                    }
                                    num2 = 1;
                                    goto IL_036C;
                                }
                            }
                            else if (num3 <= 3826002220U)
{
                                if (num3 != 3809224601U)
{
                                    if (num3 != 3826002220U)
{
                                        goto IL_0352;
                                    }
                                    if (!(text2 == "a"))
{
                                        goto IL_0352;
                                    }
                                }
                                else
{
                                    if (!(text2 == "f"))
{
                                        goto IL_0352;
                                    }
                                    num2 = 2;
                                    goto IL_036C;
                                }
                            }
                            else if (num3 != 3859557458U)
{
                                if (num3 != 3876335077U)
{
                                    goto IL_0352;
                                }
                                if (!(text2 == "b"))
{
                                    goto IL_0352;
                                }
                                num2 = 25;
                                goto IL_036C;
                            }
                            else
{
                                if (!(text2 == "c"))
{
                                    goto IL_0352;
                                }
                                num2 = 5;
                                goto IL_036C;
                            }
                            num2 = 50;
                        }
                        else if (num3 <= 3943445553U)
{
                            if (num3 <= 3909890315U)
{
                                if (num3 != 3893112696U)
{
                                    if (num3 != 3909890315U)
{
                                        goto IL_0352;
                                    }
                                    if (!(text2 == "l"))
{
                                        goto IL_0352;
                                    }
                                    num2 = 100;
                                }
                                else
{
                                    if (!(text2 == "m"))
{
                                        goto IL_0352;
                                    }
                                    num2 = 200;
                                }
                            }
                            else if (num3 != 3926667934U)
{
                                if (num3 != 3943445553U)
{
                                    goto IL_0352;
                                }
                                if (!(text2 == "n"))
{
                                    goto IL_0352;
                                }
                                num2 = 20;
                            }
                            else
{
                                if (!(text2 == "o"))
{
                                    goto IL_0352;
                                }
                                num2 = 400;
                            }
                        }
                        else if (num3 <= 3977000791U)
{
                            if (num3 != 3960223172U)
{
                                if (num3 != 3977000791U)
{
                                    goto IL_0352;
                                }
                                if (!(text2 == "h"))
{
                                    goto IL_0352;
                                }
                                num2 = 10;
                            }
                            else
{
                                if (!(text2 == "i"))
{
                                    goto IL_0352;
                                }
                                num2 = 15;
                            }
                        }
                        else if (num3 != 3993778410U)
{
                            if (num3 != 4010556029U)
{
                                goto IL_0352;
                            }
                            if (!(text2 == "j"))
{
                                goto IL_0352;
                            }
                            num2 = 30;
                        }
                        else
{
                            if (!(text2 == "k"))
{
                                goto IL_0352;
                            }
                            num2 = 99;
                        }
                        IL_036C:
                        if (!flag)
{
                            this._sacrificeCountNeededByItemId[num] = num2;
                            goto IL_037F;
                        }
                        goto IL_037F;
                        IL_0352:
                        throw new Exception("There is no category for this item: " + array2[0] + ", category: " + text2);
                    }
                }
                IL_037F:;
            }
        }
References Terraria.GameContent.Creative.CreativeItemSacrificesCatalog._sacrificeCountNeededByItemId, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.Utils.ReadEmbeddedResource(), Terraria.ID.ItemID.Search, System.text, and System.U.
Referenced by Terraria.Main.Initialize_AlmostEverything().