Terraria Decompiled: System.Threading.ThreadPool.QueueUserWorkItemHelper
QueueUserWorkItemHelper()
static bool System.Threading.ThreadPool.QueueUserWorkItemHelper (WaitCallback callBack, object state, ref StackCrawlMark stackMark, bool compressStack, bool forceGlobal = true) inline static private
Definition at line 243 of file ThreadPool.cs.
        {
            bool flag = true;
            if (callBack != null)
            {
                ThreadPool.EnsureVMInitialized();
                try
                {
                    return flag;
                }
                finally
                {
                    QueueUserWorkItemCallback queueUserWorkItemCallback = new QueueUserWorkItemCallback(callBack, state, compressStack, ref stackMark);
                    ThreadPoolGlobals.workQueue.Enqueue(queueUserWorkItemCallback, forceGlobal);
                    flag = true;
                }
            }
            throw new ArgumentNullException("WaitCallback");
        }
References System.Threading.ThreadPoolWorkQueue.Enqueue(), System.Threading.ThreadPool.EnsureVMInitialized(), System.state, and System.Threading.ThreadPoolGlobals.workQueue.
Referenced by System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.ThreadPool.QueueUserWorkItem(), System.Threading.ThreadPool.QueueUserWorkItem< TState >(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), and System.Threading.ThreadPool.UnsafeQueueUserWorkItem< TState >().