Terraria Decompiled: System.Threading.ThreadPool.QueueUserWorkItem
QueueUserWorkItem() [2/2]
static bool System.Threading.ThreadPool.QueueUserWorkItem (WaitCallback callBack, object state) inline static
Definition at line 189 of file ThreadPool.cs.
        {
            StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMyCaller;
            return ThreadPool.QueueUserWorkItemHelper(callBack, state, ref stackCrawlMark, true, true);
        }
References System.Threading.ThreadPool.QueueUserWorkItemHelper(), and System.state.
Referenced by System.Runtime.Remoting.Messaging.StackBuilderSink.AsyncProcessMessage(), System.Runtime.Remoting.Channels.CrossAppDomainSink.AsyncProcessMessage(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CompleteTaskAsync(), ReLogic.Threading.FastParallel.For(), Terraria.Social.WeGame.CoreSocialModule.Initialize(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.InvokeContinuation(), System.Threading.Tasks.Sources.ManualResetValueTaskSourceCore< TResult >.OnCompleted(), Terraria.WorldGen.playWorld(), System.Threading.SynchronizationContext.Post(), System.Runtime.CompilerServices.YieldAwaitable.YieldAwaiter.QueueContinuation(), System.Threading.ThreadPool.RegisterWaitForSingleObject(), Terraria.WorldGen.RenameWorld(), Terraria.WorldGen.saveAndPlay(), Terraria.WorldGen.SaveAndQuit(), Terraria.WorldGen.saveToonWhilePlaying(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync(), ReLogic.Peripherals.RGB.ChromaEngine.Update(), and System.Threading.RegisteredWaitHandle.Wait().