Terraria Decompiled: System.Threading.ThreadPool.EnumerateQueuedWorkItems
EnumerateQueuedWorkItems()
static IEnumerable< IThreadPoolWorkItem > System.Threading.ThreadPool.EnumerateQueuedWorkItems (ThreadPoolWorkQueue::WorkStealingQueue[] wsQueues, ThreadPoolWorkQueue::QueueSegment globalQueueTail) inline static package
Definition at line 292 of file ThreadPool.cs.
        {
            if (wsQueues != null)
            {
                foreach (ThreadPoolWorkQueue.WorkStealingQueue workStealingQueue in wsQueues)
                {
                    if (workStealingQueue != null && workStealingQueue.m_array != null)
                    {
                        IThreadPoolWorkItem[] items = workStealingQueue.m_array;
                        int num;
                        for (int i = 0; i < items.Length; i = num + 1)
{
                            IThreadPoolWorkItem threadPoolWorkItem = items[i];
                            if (threadPoolWorkItem != null)
{
                                yield return threadPoolWorkItem;
                            }
                            num = i;
                        }
                        items = null;
                    }
                }
                ThreadPoolWorkQueue.WorkStealingQueue[] array = null;
            }
            if (globalQueueTail != null)
            {
                ThreadPoolWorkQueue.QueueSegment segment;
                for (segment = globalQueueTail; segment != null; segment = segment.Next)
                {
                    IThreadPoolWorkItem[] items = segment.nodes;
                    int num;
                    for (int j = 0; j < items.Length; j = num + 1)
                    {
                        IThreadPoolWorkItem threadPoolWorkItem2 = items[j];
                        if (threadPoolWorkItem2 != null)
{
                            yield return threadPoolWorkItem2;
                        }
                        num = j;
                    }
                    items = null;
                }
                segment = null;
            }
            yield break;
        }
References System.array, System.Threading.ThreadPoolWorkQueue.QueueSegment.Next, and System.Threading.ThreadPoolWorkQueue.QueueSegment.nodes.
Referenced by System.Threading.ThreadPool.GetGloballyQueuedWorkItems(), System.Threading.ThreadPool.GetLocallyQueuedWorkItems(), and System.Threading.ThreadPool.GetQueuedWorkItems().