Terraria Decompiled: System.Threading.ThreadPool.RegisterWaitForSingleObject
RegisterWaitForSingleObject() [5/5]
static RegisteredWaitHandle System.Threading.ThreadPool.RegisterWaitForSingleObject (WaitHandle waitObject, WaitOrTimerCallback callBack, object state, uint millisecondsTimeOutInterval, bool executeOnlyOnce, ref StackCrawlMark stackMark, bool compressStack) inline static private
Definition at line 72 of file ThreadPool.cs.
        {
            if (waitObject == null)
            {
                throw new ArgumentNullException("waitObject");
            }
            if (callBack == null)
            {
                throw new ArgumentNullException("callBack");
            }
            if (millisecondsTimeOutInterval != 4294967295U && millisecondsTimeOutInterval > 2147483647U)
            {
                throw new NotSupportedException("Timeout is too big. Maximum is Int32.MaxValue");
            }
            RegisteredWaitHandle registeredWaitHandle = new RegisteredWaitHandle(waitObject, callBack, state, new TimeSpan(0, 0, 0, 0, (int)millisecondsTimeOutInterval), executeOnlyOnce);
            if (compressStack)
            {
                ThreadPool.QueueUserWorkItem(new WaitCallback(registeredWaitHandle.Wait), null);
            }
            else
            {
                ThreadPool.UnsafeQueueUserWorkItem(new WaitCallback(registeredWaitHandle.Wait), null);
            }
            return registeredWaitHandle;
        }
References System.Threading.ThreadPool.QueueUserWorkItem(), System.state, System.U, System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), System.Threading.RegisteredWaitHandle.Wait(), and System.Threading.WaitCallback().