Terraria Decompiled: Terraria.DataStructures.PlayerIntentionGuesser.PrepareUsageProxy
PrepareUsageProxy()
void Terraria.DataStructures.PlayerIntentionGuesser.PrepareUsageProxy (Player player, int itemType, int areaInflateWidth, int areaInflateHeight) inline
Definition at line 85 of file PlayerIntentionGuesser.cs.
        {
            this.UsageProxy.player = player;
            if (this.UsageProxy.item == null)
            {
                this.UsageProxy.item = new Item();
            }
            this.UsageProxy.item.SetDefaults(itemType, null);
            this.UsageProxy.position = this.LastPosition;
            this.UsageProxy.Center = this.LastCenter;
            this.UsageProxy.mouse = this.LastMouse;
            this.UsageProxy.screenTargetX = this.LastX;
            this.UsageProxy.screenTargetY = this.LastY;
            this.UsageProxy.screenTargetX = Utils.Clamp<int>(this.UsageProxy.screenTargetX, 10, Main.maxTilesX - 10);
            this.UsageProxy.screenTargetY = Utils.Clamp<int>(this.UsageProxy.screenTargetY, 10, Main.maxTilesY - 10);
            Rectangle rectangle = new Rectangle(this.LastX, this.LastY, 1, 1);
            rectangle.Inflate(areaInflateWidth, areaInflateHeight);
            Rectangle rectangle2 = new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY);
            rectangle2.Inflate(-10, -10);
            Rectangle rectangle3 = default(Rectangle);
            rectangle3 = Rectangle.Intersect(rectangle, rectangle2);
            this.UsageProxy.reachableStartX = rectangle3.Left;
            this.UsageProxy.reachableStartY = rectangle3.Top;
            this.UsageProxy.reachableEndX = rectangle3.Right;
            this.UsageProxy.reachableEndY = rectangle3.Bottom;
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Rectangle.Intersect(), Terraria.DataStructures.PlayerIntentionGuesser.LastCenter, Terraria.DataStructures.PlayerIntentionGuesser.LastMouse, Terraria.DataStructures.PlayerIntentionGuesser.LastPosition, Terraria.DataStructures.PlayerIntentionGuesser.LastX, Terraria.DataStructures.PlayerIntentionGuesser.LastY, Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Microsoft.Xna.Framework.Rectangle.Right, Microsoft.Xna.Framework.Rectangle.Top, and Terraria.DataStructures.PlayerIntentionGuesser.UsageProxy.
Referenced by Terraria.Projectile.AI_067_FreakingPirates_TryAssigningHelp().