Terraria Decompiled: Terraria.GameContent.NetModules.NetAmbienceModule.Deserialize
Deserialize()
override bool Terraria.GameContent.NetModules.NetAmbienceModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 26 of file NetAmbienceModule.cs.
        {
            if (Main.dedServ)
            {
                return false;
            }
            byte playerId = reader.ReadByte();
            int seed = reader.ReadInt32();
            SkyEntityType type = (SkyEntityType)reader.ReadByte();
            if (Main.remixWorld)
            {
                return true;
            }
            Main.QueueMainThreadAction(delegate
            {
                ((AmbientSky)SkyManager.Instance["Ambience"]).Spawn(Main.player[(int)playerId], type, seed);
            });
            return true;
        }
References Terraria.Main.dedServ, Terraria.Graphics.Effects.SkyManager.Instance, Terraria.Main.player, Terraria.Main.QueueMainThreadAction(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), and Terraria.Main.remixWorld.