Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveUnTyped
ReadMemberPrimitiveUnTyped()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveUnTyped () inline private
Definition at line 948 of file __BinaryParser.cs.
        {
            ObjectProgress objectProgress = (ObjectProgress)this.stack.Peek();
            if (this.memberPrimitiveUnTyped == null)
            {
                this.memberPrimitiveUnTyped = new MemberPrimitiveUnTyped();
            }
            this.memberPrimitiveUnTyped.Set((InternalPrimitiveTypeE)this.expectedTypeInformation);
            this.memberPrimitiveUnTyped.Read(this);
            this.memberPrimitiveUnTyped.Dump();
            this.prs.Init();
            this.prs.PRvarValue = this.memberPrimitiveUnTyped.value;
            this.prs.PRdtTypeCode = (InternalPrimitiveTypeE)this.expectedTypeInformation;
            this.prs.PRdtType = Converter.ToType(this.prs.PRdtTypeCode);
            this.prs.PRparseTypeEnum = InternalParseTypeE.Member;
            this.prs.PRmemberValueEnum = InternalMemberValueE.InlineValue;
            if (objectProgress.objectTypeEnum == InternalObjectTypeE.Object)
            {
                this.prs.PRmemberTypeEnum = InternalMemberTypeE.Field;
                this.prs.PRname = objectProgress.name;
            }
            else
            {
                this.prs.PRmemberTypeEnum = InternalMemberTypeE.Item;
            }
            this.objectReader.Parse(this.prs);
        }
References System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Dump(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.expectedTypeInformation, System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.memberPrimitiveUnTyped, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRdtTypeCode, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.prs, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Read(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.Set(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack, System.Runtime.Serialization.Formatters.Binary.Converter.ToType(), and System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveUnTyped.value.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().