Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadCrossAppDomainMap
ReadCrossAppDomainMap()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadCrossAppDomainMap () inline package
Definition at line 458 of file __BinaryParser.cs.
        {
            BinaryCrossAppDomainMap binaryCrossAppDomainMap = new BinaryCrossAppDomainMap();
            binaryCrossAppDomainMap.Read(this);
            binaryCrossAppDomainMap.Dump();
            object obj = this.objectReader.CrossAppDomainArray(binaryCrossAppDomainMap.crossAppDomainArrayIndex);
            BinaryObjectWithMap binaryObjectWithMap = obj as BinaryObjectWithMap;
            if (binaryObjectWithMap != null)
            {
                binaryObjectWithMap.Dump();
                this.ReadObjectWithMap(binaryObjectWithMap);
                return;
            }
            BinaryObjectWithMapTyped binaryObjectWithMapTyped = obj as BinaryObjectWithMapTyped;
            if (binaryObjectWithMapTyped != null)
            {
                this.ReadObjectWithMapTyped(binaryObjectWithMapTyped);
                return;
            }
            throw new SerializationException(Environment.GetResourceString("Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.", new object[] { "BinaryObjectMap", obj }));
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader.CrossAppDomainArray(), System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainMap.crossAppDomainArrayIndex, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainMap.Dump(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Dump(), System.Environment.GetResourceString(), System.obj, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainMap.Read(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().