Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArrayAsBytes
ReadArrayAsBytes()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArrayAsBytes (ParseRecord pr) inline private
Definition at line 904 of file __BinaryParser.cs.
        {
            if (pr.PRarrayElementTypeCode == InternalPrimitiveTypeE.Byte)
            {
                pr.PRnewObj = this.ReadBytes(pr.PRlengthA[0]);
                return;
            }
            if (pr.PRarrayElementTypeCode == InternalPrimitiveTypeE.Char)
            {
                pr.PRnewObj = this.ReadChars(pr.PRlengthA[0]);
                return;
            }
            int num = Converter.TypeLength(pr.PRarrayElementTypeCode);
            pr.PRnewObj = Converter.CreatePrimitiveArray(pr.PRarrayElementTypeCode, pr.PRlengthA[0]);
            Array array = (Array)pr.PRnewObj;
            int i = 0;
            if (this.byteBuffer == null)
            {
                this.byteBuffer = new byte[4096];
            }
            while (i < array.Length)
            {
                int num2 = Math.Min(4096 / num, array.Length - i);
                int num3 = num2 * num;
                this.ReadBytes(this.byteBuffer, 0, num3);
                if (!BitConverter.IsLittleEndian)
                {
                    for (int j = 0; j < num3; j += num)
                    {
                        for (int k = 0; k < num / 2; k++)
{
                            byte b = this.byteBuffer[j + k];
                            this.byteBuffer[j + k] = this.byteBuffer[j + num - 1 - k];
                            this.byteBuffer[j + num - 1 - k] = b;
                        }
                    }
                }
                Buffer.InternalBlockCopy(this.byteBuffer, 0, array, i * num, num3);
                i += num2;
            }
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.Array, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.byteBuffer, System.Runtime.Serialization.Formatters.Binary.Converter.CreatePrimitiveArray(), System.Buffer.InternalBlockCopy(), System.BitConverter.IsLittleEndian, System.Math.Min(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRlengthA, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRnewObj, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadBytes(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadChars(), and System.Runtime.Serialization.Formatters.Binary.Converter.TypeLength().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray().