Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.GetOp
GetOp()
ObjectProgress System.Runtime.Serialization.Formatters.Binary.__BinaryParser.GetOp () inline private
Definition at line 1089 of file __BinaryParser.cs.
        {
            ObjectProgress objectProgress;
            if (this.opPool != null && !this.opPool.IsEmpty())
            {
                objectProgress = (ObjectProgress)this.opPool.Pop();
                objectProgress.Init();
            }
            else
            {
                objectProgress = new ObjectProgress();
            }
            return objectProgress;
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectProgress.Init(), System.Runtime.Serialization.Formatters.Binary.SerStack.IsEmpty(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.opPool, and System.Runtime.Serialization.Formatters.Binary.SerStack.Pop().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped().