Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray
ReadArray()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray (BinaryHeaderEnum binaryHeaderEnum) inline private
Definition at line 781 of file __BinaryParser.cs.
        {
            BinaryArray binaryArray = new BinaryArray(binaryHeaderEnum);
            binaryArray.Read(this);
            BinaryAssemblyInfo binaryAssemblyInfo;
            if (binaryArray.binaryTypeEnum == BinaryTypeEnum.ObjectUser)
            {
                if (binaryArray.assemId < 1)
                {
                    throw new SerializationException(Environment.GetResourceString("No assembly ID for object type '{0}'.", new object[] { binaryArray.typeInformation }));
                }
                binaryAssemblyInfo = (BinaryAssemblyInfo)this.AssemIdToAssemblyTable[binaryArray.assemId];
            }
            else
            {
                binaryAssemblyInfo = this.SystemAssemblyInfo;
            }
            ObjectProgress op = this.GetOp();
            ParseRecord pr = op.pr;
            op.objectTypeEnum = InternalObjectTypeE.Array;
            op.binaryTypeEnum = binaryArray.binaryTypeEnum;
            op.typeInformation = binaryArray.typeInformation;
            ObjectProgress objectProgress = (ObjectProgress)this.stack.PeekPeek();
            if (objectProgress == null || binaryArray.objectId > 0)
            {
                op.name = "System.Array";
                pr.PRparseTypeEnum = InternalParseTypeE.Object;
                op.memberValueEnum = InternalMemberValueE.Empty;
            }
            else
            {
                pr.PRparseTypeEnum = InternalParseTypeE.Member;
                pr.PRmemberValueEnum = InternalMemberValueE.Nested;
                op.memberValueEnum = InternalMemberValueE.Nested;
                InternalObjectTypeE objectTypeEnum = objectProgress.objectTypeEnum;
                if (objectTypeEnum != InternalObjectTypeE.Object)
                {
                    if (objectTypeEnum != InternalObjectTypeE.Array)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid ObjectTypeEnum {0}.", new object[] { objectProgress.objectTypeEnum.ToString() }));
                    }
                    pr.PRmemberTypeEnum = InternalMemberTypeE.Item;
                    op.memberTypeEnum = InternalMemberTypeE.Item;
                }
                else
                {
                    pr.PRname = objectProgress.name;
                    pr.PRmemberTypeEnum = InternalMemberTypeE.Field;
                    op.memberTypeEnum = InternalMemberTypeE.Field;
                    pr.PRkeyDt = objectProgress.name;
                    pr.PRdtType = objectProgress.dtType;
                }
            }
            pr.PRobjectId = this.objectReader.GetId((long)binaryArray.objectId);
            if (pr.PRobjectId == this.topId)
            {
                pr.PRobjectPositionEnum = InternalObjectPositionE.Top;
            }
            else if (this.headerId > 0L && pr.PRobjectId == this.headerId)
            {
                pr.PRobjectPositionEnum = InternalObjectPositionE.Headers;
            }
            else
            {
                pr.PRobjectPositionEnum = InternalObjectPositionE.Child;
            }
            pr.PRobjectTypeEnum = InternalObjectTypeE.Array;
            BinaryConverter.TypeFromInfo(binaryArray.binaryTypeEnum, binaryArray.typeInformation, this.objectReader, binaryAssemblyInfo, out pr.PRarrayElementTypeCode, out pr.PRarrayElementTypeString, out pr.PRarrayElementType, out pr.PRisArrayVariant);
            pr.PRdtTypeCode = InternalPrimitiveTypeE.Invalid;
            pr.PRrank = binaryArray.rank;
            pr.PRlengthA = binaryArray.lengthA;
            pr.PRlowerBoundA = binaryArray.lowerBoundA;
            bool flag = false;
            switch (binaryArray.binaryArrayTypeEnum)
            {
            case BinaryArrayTypeEnum.Single:
            case BinaryArrayTypeEnum.SingleOffset:
                op.numItems = binaryArray.lengthA[0];
                pr.PRarrayTypeEnum = InternalArrayTypeE.Single;
                if (Converter.IsWriteAsByteArray(pr.PRarrayElementTypeCode) && binaryArray.lowerBoundA[0] == 0)
                {
                    flag = true;
                    this.ReadArrayAsBytes(pr);
                }
                break;
            case BinaryArrayTypeEnum.Jagged:
            case BinaryArrayTypeEnum.JaggedOffset:
                op.numItems = binaryArray.lengthA[0];
                pr.PRarrayTypeEnum = InternalArrayTypeE.Jagged;
                break;
            case BinaryArrayTypeEnum.Rectangular:
            case BinaryArrayTypeEnum.RectangularOffset:
            {
                int num = 1;
                for (int i = 0; i < binaryArray.rank; i++)
                {
                    num *= binaryArray.lengthA[i];
                }
                op.numItems = num;
                pr.PRarrayTypeEnum = InternalArrayTypeE.Rectangular;
                break;
            }
            default:
                throw new SerializationException(Environment.GetResourceString("Invalid array type '{0}'.", new object[] { binaryArray.binaryArrayTypeEnum.ToString() }));
            }
            if (!flag)
            {
                this.stack.Push(op);
            }
            else
            {
                this.PutOp(op);
            }
            this.objectReader.Parse(pr);
            if (flag)
            {
                pr.PRparseTypeEnum = InternalParseTypeE.ObjectEnd;
                this.objectReader.Parse(pr);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryArray.assemId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.AssemIdToAssemblyTable, System.Runtime.Serialization.Formatters.Binary.BinaryArray.binaryArrayTypeEnum, System.Runtime.Serialization.Formatters.Binary.BinaryArray.binaryTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.dtType, System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.GetOp(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.headerId, System.Runtime.Serialization.Formatters.Binary.Converter.IsWriteAsByteArray(), System.L, System.Runtime.Serialization.Formatters.Binary.BinaryArray.lengthA, System.Runtime.Serialization.Formatters.Binary.BinaryArray.lowerBoundA, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.BinaryArray.objectId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.pr, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementType, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementTypeCode, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRarrayElementTypeString, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRisArrayVariant, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.PutOp(), System.Runtime.Serialization.Formatters.Binary.BinaryArray.rank, System.Runtime.Serialization.Formatters.Binary.BinaryArray.Read(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArrayAsBytes(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.SystemAssemblyInfo, System.Runtime.Serialization.Formatters.Binary.BinaryConverter.TypeFromInfo(), and System.Runtime.Serialization.Formatters.Binary.BinaryArray.typeInformation.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().