Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap
ReadObjectWithMap() [1/2]
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap (BinaryHeaderEnum binaryHeaderEnum) inline package
Definition at line 482 of file __BinaryParser.cs.
        {
            if (this.bowm == null)
            {
                this.bowm = new BinaryObjectWithMap(binaryHeaderEnum);
            }
            else
            {
                this.bowm.binaryHeaderEnum = binaryHeaderEnum;
            }
            this.bowm.Read(this);
            this.bowm.Dump();
            this.ReadObjectWithMap(this.bowm);
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryParser.bowm, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Dump(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMap.Read(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadCrossAppDomainMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().