Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadValue
ReadValue()
object System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadValue (InternalPrimitiveTypeE code) inline package
Definition at line 1050 of file __BinaryParser.cs.
        {
            switch (code)
            {
            case InternalPrimitiveTypeE.Boolean:
                return this.ReadBoolean();
            case InternalPrimitiveTypeE.Byte:
                return this.ReadByte();
            case InternalPrimitiveTypeE.Char:
                return this.ReadChar();
            case InternalPrimitiveTypeE.Decimal:
                return this.ReadDecimal();
            case InternalPrimitiveTypeE.Double:
                return this.ReadDouble();
            case InternalPrimitiveTypeE.Int16:
                return this.ReadInt16();
            case InternalPrimitiveTypeE.Int32:
                return this.ReadInt32();
            case InternalPrimitiveTypeE.Int64:
                return this.ReadInt64();
            case InternalPrimitiveTypeE.SByte:
                return this.ReadSByte();
            case InternalPrimitiveTypeE.Single:
                return this.ReadSingle();
            case InternalPrimitiveTypeE.TimeSpan:
                return this.ReadTimeSpan();
            case InternalPrimitiveTypeE.DateTime:
                return this.ReadDateTime();
            case InternalPrimitiveTypeE.UInt16:
                return this.ReadUInt16();
            case InternalPrimitiveTypeE.UInt32:
                return this.ReadUInt32();
            case InternalPrimitiveTypeE.UInt64:
                return this.ReadUInt64();
            }
            throw new SerializationException(Environment.GetResourceString("Invalid type code in stream '{0}'.", new object[] { code.ToString() }));
        }
References System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadBoolean(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadChar(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadDateTime(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadDecimal(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadDouble(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadInt16(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadInt32(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadInt64(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSingle(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadTimeSpan(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadUInt16(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadUInt32(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadUInt64().