Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run
Run()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run () inline package
Definition at line 78 of file __BinaryParser.cs.
        {
            try
            {
                bool flag = true;
                this.ReadBegin();
                this.ReadSerializationHeaderRecord();
                while (flag)
                {
                    BinaryHeaderEnum binaryHeaderEnum = BinaryHeaderEnum.Object;
                    BinaryTypeEnum binaryTypeEnum = this.expectedType;
                    if (binaryTypeEnum != BinaryTypeEnum.Primitive)
                    {
                        if (binaryTypeEnum - BinaryTypeEnum.String > 6)
{
                            throw new SerializationException(Environment.GetResourceString("Invalid expected type."));
                        }
                        byte b = this.dataReader.ReadByte();
                        binaryHeaderEnum = (BinaryHeaderEnum)b;
                        switch (binaryHeaderEnum)
{
                        case BinaryHeaderEnum.Object:
                            this.ReadObject();
                            break;
                        case BinaryHeaderEnum.ObjectWithMap:
                        case BinaryHeaderEnum.ObjectWithMapAssemId:
                            this.ReadObjectWithMap(binaryHeaderEnum);
                            break;
                        case BinaryHeaderEnum.ObjectWithMapTyped:
                        case BinaryHeaderEnum.ObjectWithMapTypedAssemId:
                            this.ReadObjectWithMapTyped(binaryHeaderEnum);
                            break;
                        case BinaryHeaderEnum.ObjectString:
                        case BinaryHeaderEnum.CrossAppDomainString:
                            this.ReadObjectString(binaryHeaderEnum);
                            break;
                        case BinaryHeaderEnum.Array:
                        case BinaryHeaderEnum.ArraySinglePrimitive:
                        case BinaryHeaderEnum.ArraySingleObject:
                        case BinaryHeaderEnum.ArraySingleString:
                            this.ReadArray(binaryHeaderEnum);
                            break;
                        case BinaryHeaderEnum.MemberPrimitiveTyped:
                            this.ReadMemberPrimitiveTyped();
                            break;
                        case BinaryHeaderEnum.MemberReference:
                            this.ReadMemberReference();
                            break;
                        case BinaryHeaderEnum.ObjectNull:
                        case BinaryHeaderEnum.ObjectNullMultiple256:
                        case BinaryHeaderEnum.ObjectNullMultiple:
                            this.ReadObjectNull(binaryHeaderEnum);
                            break;
                        case BinaryHeaderEnum.MessageEnd:
                            flag = false;
                            this.ReadMessageEnd();
                            this.ReadEnd();
                            break;
                        case BinaryHeaderEnum.Assembly:
                        case BinaryHeaderEnum.CrossAppDomainAssembly:
                            this.ReadAssembly(binaryHeaderEnum);
                            break;
                        case BinaryHeaderEnum.CrossAppDomainMap:
                            this.ReadCrossAppDomainMap();
                            break;
                        case BinaryHeaderEnum.MethodCall:
                        case BinaryHeaderEnum.MethodReturn:
                            this.ReadMethodObject(binaryHeaderEnum);
                            break;
                        default:
                            throw new SerializationException(Environment.GetResourceString("Binary stream '{0}' does not contain a valid BinaryHeader. Possible causes are invalid stream or object version change between serialization and deserialization.", new object[] { b }));
                        }
                    }
                    else
                    {
                        this.ReadMemberPrimitiveUnTyped();
                    }
                    if (binaryHeaderEnum != BinaryHeaderEnum.Assembly)
                    {
                        bool flag2 = false;
                        while (!flag2)
{
                            ObjectProgress objectProgress = (ObjectProgress)this.stack.Peek();
                            if (objectProgress == null)
{
                                this.expectedType = BinaryTypeEnum.ObjectUrt;
                                this.expectedTypeInformation = null;
                                flag2 = true;
                            }
                            else
{
                                flag2 = objectProgress.GetNext(out objectProgress.expectedType, out objectProgress.expectedTypeInformation);
                                this.expectedType = objectProgress.expectedType;
                                this.expectedTypeInformation = objectProgress.expectedTypeInformation;
                                if (!flag2)
{
                                    this.prs.Init();
                                    if (objectProgress.memberValueEnum == InternalMemberValueE.Nested)
{
                                        this.prs.PRparseTypeEnum = InternalParseTypeE.MemberEnd;
                                        this.prs.PRmemberTypeEnum = objectProgress.memberTypeEnum;
                                        this.prs.PRmemberValueEnum = objectProgress.memberValueEnum;
                                        this.objectReader.Parse(this.prs);
                                    }
                                    else
{
                                        this.prs.PRparseTypeEnum = InternalParseTypeE.ObjectEnd;
                                        this.prs.PRmemberTypeEnum = objectProgress.memberTypeEnum;
                                        this.prs.PRmemberValueEnum = objectProgress.memberValueEnum;
                                        this.objectReader.Parse(this.prs);
                                    }
                                    this.stack.Pop();
                                    this.PutOp(objectProgress);
                                }
                            }
                        }
                    }
                }
            }
            catch (EndOfStreamException)
            {
                throw new SerializationException(Environment.GetResourceString("End of Stream encountered before parsing was completed."));
            }
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryParser.dataReader, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.expectedType, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.expectedType, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.expectedTypeInformation, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.GetNext(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.memberTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.memberValueEnum, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.SerStack.Pop(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.prs, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.PutOp(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadAssembly(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadBegin(), System.IO.BinaryReader.ReadByte(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadCrossAppDomainMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadEnd(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveTyped(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveUnTyped(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberReference(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMessageEnd(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMethodObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectNull(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectString(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMap(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSerializationHeaderRecord(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.Deserialize().