Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject
ReadObject()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObject () inline private
Definition at line 392 of file __BinaryParser.cs.
        {
            if (this.binaryObject == null)
            {
                this.binaryObject = new BinaryObject();
            }
            this.binaryObject.Read(this);
            this.binaryObject.Dump();
            ObjectMap objectMap = (ObjectMap)this.ObjectMapIdTable[this.binaryObject.mapId];
            if (objectMap == null)
            {
                throw new SerializationException(Environment.GetResourceString("No map for object '{0}'.", new object[] { this.binaryObject.mapId }));
            }
            ObjectProgress op = this.GetOp();
            ParseRecord pr = op.pr;
            this.stack.Push(op);
            op.objectTypeEnum = InternalObjectTypeE.Object;
            op.binaryTypeEnumA = objectMap.binaryTypeEnumA;
            op.memberNames = objectMap.memberNames;
            op.memberTypes = objectMap.memberTypes;
            op.typeInformationA = objectMap.typeInformationA;
            op.memberLength = op.binaryTypeEnumA.Length;
            ObjectProgress objectProgress = (ObjectProgress)this.stack.PeekPeek();
            if (objectProgress == null || objectProgress.isInitial)
            {
                op.name = objectMap.objectName;
                pr.PRparseTypeEnum = InternalParseTypeE.Object;
                op.memberValueEnum = InternalMemberValueE.Empty;
            }
            else
            {
                pr.PRparseTypeEnum = InternalParseTypeE.Member;
                pr.PRmemberValueEnum = InternalMemberValueE.Nested;
                op.memberValueEnum = InternalMemberValueE.Nested;
                InternalObjectTypeE objectTypeEnum = objectProgress.objectTypeEnum;
                if (objectTypeEnum != InternalObjectTypeE.Object)
                {
                    if (objectTypeEnum != InternalObjectTypeE.Array)
                    {
                        throw new SerializationException(Environment.GetResourceString("No map for object '{0}'.", new object[] { objectProgress.objectTypeEnum.ToString() }));
                    }
                    pr.PRmemberTypeEnum = InternalMemberTypeE.Item;
                    op.memberTypeEnum = InternalMemberTypeE.Item;
                }
                else
                {
                    pr.PRname = objectProgress.name;
                    pr.PRmemberTypeEnum = InternalMemberTypeE.Field;
                    op.memberTypeEnum = InternalMemberTypeE.Field;
                }
            }
            pr.PRobjectId = this.objectReader.GetId((long)this.binaryObject.objectId);
            pr.PRobjectInfo = objectMap.CreateObjectInfo(ref pr.PRsi, ref pr.PRmemberData);
            if (pr.PRobjectId == this.topId)
            {
                pr.PRobjectPositionEnum = InternalObjectPositionE.Top;
            }
            pr.PRobjectTypeEnum = InternalObjectTypeE.Object;
            pr.PRkeyDt = objectMap.objectName;
            pr.PRdtType = objectMap.objectType;
            pr.PRdtTypeCode = InternalPrimitiveTypeE.Invalid;
            this.objectReader.Parse(pr);
        }
References System.Runtime.Serialization.Formatters.Binary.__BinaryParser.binaryObject, System.Runtime.Serialization.Formatters.Binary.ObjectMap.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectMap.CreateObjectInfo(), System.Runtime.Serialization.Formatters.Binary.BinaryObject.Dump(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.GetOp(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.isInitial, System.Runtime.Serialization.Formatters.Binary.BinaryObject.mapId, System.Runtime.Serialization.Formatters.Binary.ObjectMap.memberNames, System.Runtime.Serialization.Formatters.Binary.ObjectMap.memberTypes, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.BinaryObject.objectId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ObjectMapIdTable, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectName, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectType, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.pr, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberData, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRsi, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.Formatters.Binary.BinaryObject.Read(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack, and System.Runtime.Serialization.Formatters.Binary.ObjectMap.typeInformationA.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().