Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveTyped
ReadMemberPrimitiveTyped()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMemberPrimitiveTyped () inline private
Definition at line 737 of file __BinaryParser.cs.
        {
            if (this.memberPrimitiveTyped == null)
            {
                this.memberPrimitiveTyped = new MemberPrimitiveTyped();
            }
            this.memberPrimitiveTyped.Read(this);
            this.memberPrimitiveTyped.Dump();
            this.prs.PRobjectTypeEnum = InternalObjectTypeE.Object;
            ObjectProgress objectProgress = (ObjectProgress)this.stack.Peek();
            this.prs.Init();
            this.prs.PRvarValue = this.memberPrimitiveTyped.value;
            this.prs.PRkeyDt = Converter.ToComType(this.memberPrimitiveTyped.primitiveTypeEnum);
            this.prs.PRdtType = Converter.ToType(this.memberPrimitiveTyped.primitiveTypeEnum);
            this.prs.PRdtTypeCode = this.memberPrimitiveTyped.primitiveTypeEnum;
            if (objectProgress == null)
            {
                this.prs.PRparseTypeEnum = InternalParseTypeE.Object;
                this.prs.PRname = "System.Variant";
            }
            else
            {
                this.prs.PRparseTypeEnum = InternalParseTypeE.Member;
                this.prs.PRmemberValueEnum = InternalMemberValueE.InlineValue;
                InternalObjectTypeE objectTypeEnum = objectProgress.objectTypeEnum;
                if (objectTypeEnum != InternalObjectTypeE.Object)
                {
                    if (objectTypeEnum != InternalObjectTypeE.Array)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid ObjectTypeEnum {0}.", new object[] { objectProgress.objectTypeEnum.ToString() }));
                    }
                    this.prs.PRmemberTypeEnum = InternalMemberTypeE.Item;
                }
                else
                {
                    this.prs.PRname = objectProgress.name;
                    this.prs.PRmemberTypeEnum = InternalMemberTypeE.Field;
                }
            }
            this.objectReader.Parse(this.prs);
        }
References System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Dump(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.memberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.primitiveTypeEnum, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.prs, System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.Read(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack, System.Runtime.Serialization.Formatters.Binary.Converter.ToComType(), System.Runtime.Serialization.Formatters.Binary.Converter.ToType(), and System.Runtime.Serialization.Formatters.Binary.MemberPrimitiveTyped.value.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().