Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped
ReadObjectWithMapTyped() [2/2]
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectWithMapTyped (BinaryObjectWithMapTyped record) inline private
Definition at line 590 of file __BinaryParser.cs.
        {
            BinaryAssemblyInfo binaryAssemblyInfo = null;
            ObjectProgress op = this.GetOp();
            ParseRecord pr = op.pr;
            this.stack.Push(op);
            if (record.binaryHeaderEnum == BinaryHeaderEnum.ObjectWithMapTypedAssemId)
            {
                if (record.assemId < 1)
                {
                    throw new SerializationException(Environment.GetResourceString("No assembly ID for object type '{0}'.", new object[] { record.name }));
                }
                binaryAssemblyInfo = (BinaryAssemblyInfo)this.AssemIdToAssemblyTable[record.assemId];
                if (binaryAssemblyInfo == null)
                {
                    throw new SerializationException(Environment.GetResourceString("No assembly ID for object type '{0}'.", new object[] { record.assemId.ToString() + " " + record.name }));
                }
            }
            else if (record.binaryHeaderEnum == BinaryHeaderEnum.ObjectWithMapTyped)
            {
                binaryAssemblyInfo = this.SystemAssemblyInfo;
            }
            ObjectMap objectMap = ObjectMap.Create(record.name, record.memberNames, record.binaryTypeEnumA, record.typeInformationA, record.memberAssemIds, this.objectReader, record.objectId, binaryAssemblyInfo, this.AssemIdToAssemblyTable);
            this.ObjectMapIdTable[record.objectId] = objectMap;
            op.objectTypeEnum = InternalObjectTypeE.Object;
            op.binaryTypeEnumA = objectMap.binaryTypeEnumA;
            op.typeInformationA = objectMap.typeInformationA;
            op.memberLength = op.binaryTypeEnumA.Length;
            op.memberNames = objectMap.memberNames;
            op.memberTypes = objectMap.memberTypes;
            ObjectProgress objectProgress = (ObjectProgress)this.stack.PeekPeek();
            if (objectProgress == null || objectProgress.isInitial)
            {
                op.name = record.name;
                pr.PRparseTypeEnum = InternalParseTypeE.Object;
                op.memberValueEnum = InternalMemberValueE.Empty;
            }
            else
            {
                pr.PRparseTypeEnum = InternalParseTypeE.Member;
                pr.PRmemberValueEnum = InternalMemberValueE.Nested;
                op.memberValueEnum = InternalMemberValueE.Nested;
                InternalObjectTypeE objectTypeEnum = objectProgress.objectTypeEnum;
                if (objectTypeEnum != InternalObjectTypeE.Object)
                {
                    if (objectTypeEnum != InternalObjectTypeE.Array)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid ObjectTypeEnum {0}.", new object[] { objectProgress.objectTypeEnum.ToString() }));
                    }
                    pr.PRmemberTypeEnum = InternalMemberTypeE.Item;
                    op.memberTypeEnum = InternalMemberTypeE.Item;
                }
                else
                {
                    pr.PRname = objectProgress.name;
                    pr.PRmemberTypeEnum = InternalMemberTypeE.Field;
                    op.memberTypeEnum = InternalMemberTypeE.Field;
                }
            }
            pr.PRobjectTypeEnum = InternalObjectTypeE.Object;
            pr.PRobjectInfo = objectMap.CreateObjectInfo(ref pr.PRsi, ref pr.PRmemberData);
            pr.PRobjectId = this.objectReader.GetId((long)record.objectId);
            if (pr.PRobjectId == this.topId)
            {
                pr.PRobjectPositionEnum = InternalObjectPositionE.Top;
            }
            pr.PRkeyDt = record.name;
            pr.PRdtType = objectMap.objectType;
            pr.PRdtTypeCode = InternalPrimitiveTypeE.Invalid;
            this.objectReader.Parse(pr);
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.assemId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.AssemIdToAssemblyTable, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectMap.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.binaryTypeEnumA, System.Runtime.Serialization.Formatters.Binary.ObjectMap.Create(), System.Runtime.Serialization.Formatters.Binary.ObjectMap.CreateObjectInfo(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.GetOp(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.isInitial, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.memberAssemIds, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.memberNames, System.Runtime.Serialization.Formatters.Binary.ObjectMap.memberNames, System.Runtime.Serialization.Formatters.Binary.ObjectMap.memberTypes, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.name, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.objectId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ObjectMapIdTable, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectMap.objectType, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.PeekPeek(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.pr, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRmemberData, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRsi, System.Runtime.Serialization.Formatters.Binary.SerStack.Push(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.SystemAssemblyInfo, System.Runtime.Serialization.Formatters.Binary.BinaryObjectWithMapTyped.typeInformationA, and System.Runtime.Serialization.Formatters.Binary.ObjectMap.typeInformationA.