Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectString
ReadObjectString()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectString (BinaryHeaderEnum binaryHeaderEnum) inline private
Definition at line 664 of file __BinaryParser.cs.
        {
            if (this.objectString == null)
            {
                this.objectString = new BinaryObjectString();
            }
            if (binaryHeaderEnum == BinaryHeaderEnum.ObjectString)
            {
                this.objectString.Read(this);
                this.objectString.Dump();
            }
            else
            {
                if (this.crossAppDomainString == null)
                {
                    this.crossAppDomainString = new BinaryCrossAppDomainString();
                }
                this.crossAppDomainString.Read(this);
                this.crossAppDomainString.Dump();
                this.objectString.value = this.objectReader.CrossAppDomainArray(this.crossAppDomainString.value) as string;
                if (this.objectString.value == null)
                {
                    throw new SerializationException(Environment.GetResourceString("Cross-AppDomain BinaryFormatter error; expected '{0}' but received '{1}'.", new object[]
                    {
                        "String",
                        this.crossAppDomainString.value
                    }));
                }
                this.objectString.objectId = this.crossAppDomainString.objectId;
            }
            this.prs.Init();
            this.prs.PRparseTypeEnum = InternalParseTypeE.Object;
            this.prs.PRobjectId = this.objectReader.GetId((long)this.objectString.objectId);
            if (this.prs.PRobjectId == this.topId)
            {
                this.prs.PRobjectPositionEnum = InternalObjectPositionE.Top;
            }
            this.prs.PRobjectTypeEnum = InternalObjectTypeE.Object;
            ObjectProgress objectProgress = (ObjectProgress)this.stack.Peek();
            this.prs.PRvalue = this.objectString.value;
            this.prs.PRkeyDt = "System.String";
            this.prs.PRdtType = Converter.typeofString;
            this.prs.PRdtTypeCode = InternalPrimitiveTypeE.Invalid;
            this.prs.PRvarValue = this.objectString.value;
            if (objectProgress == null)
            {
                this.prs.PRparseTypeEnum = InternalParseTypeE.Object;
                this.prs.PRname = "System.String";
            }
            else
            {
                this.prs.PRparseTypeEnum = InternalParseTypeE.Member;
                this.prs.PRmemberValueEnum = InternalMemberValueE.InlineValue;
                InternalObjectTypeE objectTypeEnum = objectProgress.objectTypeEnum;
                if (objectTypeEnum != InternalObjectTypeE.Object)
                {
                    if (objectTypeEnum != InternalObjectTypeE.Array)
                    {
                        throw new SerializationException(Environment.GetResourceString("Invalid ObjectTypeEnum {0}.", new object[] { objectProgress.objectTypeEnum.ToString() }));
                    }
                    this.prs.PRmemberTypeEnum = InternalMemberTypeE.Item;
                }
                else
                {
                    this.prs.PRname = objectProgress.name;
                    this.prs.PRmemberTypeEnum = InternalMemberTypeE.Field;
                }
            }
            this.objectReader.Parse(this.prs);
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectReader.CrossAppDomainArray(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.crossAppDomainString, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString.Dump(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Dump(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetId(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString.objectId, System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.objectId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectString, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.PRobjectId, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.prs, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString.Read(), System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.Read(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack, System.Runtime.Serialization.Formatters.Binary.Converter.typeofString, System.Runtime.Serialization.Formatters.Binary.BinaryCrossAppDomainString.value, and System.Runtime.Serialization.Formatters.Binary.BinaryObjectString.value.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().