Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMethodObject
ReadMethodObject()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadMethodObject (BinaryHeaderEnum binaryHeaderEnum) inline package
Definition at line 374 of file __BinaryParser.cs.
        {
            if (binaryHeaderEnum == BinaryHeaderEnum.MethodCall)
            {
                BinaryMethodCall binaryMethodCall = new BinaryMethodCall();
                binaryMethodCall.Read(this);
                binaryMethodCall.Dump();
                this.objectReader.SetMethodCall(binaryMethodCall);
                return;
            }
            BinaryMethodReturn binaryMethodReturn = new BinaryMethodReturn();
            binaryMethodReturn.Read(this);
            binaryMethodReturn.Dump();
            this.objectReader.SetMethodReturn(binaryMethodReturn);
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.Dump(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.Dump(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.BinaryMethodCall.Read(), System.Runtime.Serialization.Formatters.Binary.BinaryMethodReturn.Read(), System.Runtime.Serialization.Formatters.Binary.ObjectReader.SetMethodCall(), and System.Runtime.Serialization.Formatters.Binary.ObjectReader.SetMethodReturn().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().