Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectNull
ReadObjectNull()
void System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadObjectNull (BinaryHeaderEnum binaryHeaderEnum) inline private
Definition at line 1006 of file __BinaryParser.cs.
        {
            if (this.objectNull == null)
            {
                this.objectNull = new ObjectNull();
            }
            this.objectNull.Read(this, binaryHeaderEnum);
            this.objectNull.Dump();
            ObjectProgress objectProgress = (ObjectProgress)this.stack.Peek();
            this.prs.Init();
            this.prs.PRparseTypeEnum = InternalParseTypeE.Member;
            this.prs.PRmemberValueEnum = InternalMemberValueE.Null;
            if (objectProgress.objectTypeEnum == InternalObjectTypeE.Object)
            {
                this.prs.PRmemberTypeEnum = InternalMemberTypeE.Field;
                this.prs.PRname = objectProgress.name;
                this.prs.PRdtType = objectProgress.dtType;
            }
            else
            {
                this.prs.PRmemberTypeEnum = InternalMemberTypeE.Item;
                this.prs.PRnullCount = this.objectNull.nullCount;
                objectProgress.ArrayCountIncrement(this.objectNull.nullCount - 1);
            }
            this.objectReader.Parse(this.prs);
        }
References System.Runtime.Serialization.Formatters.Binary.ObjectProgress.ArrayCountIncrement(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.dtType, System.Runtime.Serialization.Formatters.Binary.ObjectNull.Dump(), System.Runtime.Serialization.Formatters.Binary.ParseRecord.Init(), System.Runtime.Serialization.Formatters.Binary.ObjectProgress.name, System.Runtime.Serialization.Formatters.Binary.ObjectNull.nullCount, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectNull, System.Runtime.Serialization.Formatters.Binary.ObjectNull, System.Runtime.Serialization.Formatters.Binary.__BinaryParser.objectReader, System.Runtime.Serialization.Formatters.Binary.ObjectProgress.objectTypeEnum, System.Runtime.Serialization.Formatters.Binary.ObjectReader.Parse(), System.Runtime.Serialization.Formatters.Binary.SerStack.Peek(), System.Runtime.Serialization.Formatters.Binary.__BinaryParser.prs, System.Runtime.Serialization.Formatters.Binary.ObjectNull.Read(), and System.Runtime.Serialization.Formatters.Binary.__BinaryParser.stack.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.Run().