Terraria Decompiled: System.ArgIterator.GetNextArg
GetNextArg() [1/2]
unsafe TypedReference System.ArgIterator.GetNextArg () inline
Definition at line 62 of file ArgIterator.cs.
        {
            if (this.num_args == this.next_arg)
            {
                throw new InvalidOperationException("Invalid iterator position.");
            }
            TypedReference typedReference = default(TypedReference);
            this.IntGetNextArg((void*)(&typedReference));
            return typedReference;
        }
References System.ArgIterator.IntGetNextArg(), System.ArgIterator.next_arg, and System.ArgIterator.num_args.
Referenced by System.Console.Write(), and System.Console.WriteLine().