Terraria Decompiled: Mono.Math.BigInteger.Kernel.AddSameSign
AddSameSign()
static BigInteger Mono.Math.BigInteger.Kernel.AddSameSign (BigInteger bi1, BigInteger bi2) inline static
Definition at line 1067 of file BigInteger.cs.
            {
                uint num = 0U;
                uint[] array;
                uint num2;
                uint[] array2;
                uint num3;
                if (bi1.length < bi2.length)
                {
                    array = bi2.data;
                    num2 = bi2.length;
                    array2 = bi1.data;
                    num3 = bi1.length;
                }
                else
                {
                    array = bi1.data;
                    num2 = bi1.length;
                    array2 = bi2.data;
                    num3 = bi2.length;
                }
                BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, num2 + 1U);
                uint[] data = bigInteger.data;
                ulong num4 = 0UL;
                do
                {
                    num4 = (ulong)array[(int)num] + (ulong)array2[(int)num] + num4;
                    data[(int)num] = (uint)num4;
                    num4 >>= 32;
                }
                while ((num += 1U) < num3);
                bool flag = num4 > 0UL;
                if (flag)
                {
                    if (num < num2)
                    {
                        do
{
                            flag = (data[(int)num] = array[(int)num] + 1U) == 0U;
                        }
                        while ((num += 1U) < num2 && flag);
                    }
                    if (flag)
                    {
                        data[(int)num] = 1U;
                        bigInteger.length = num + 1U;
                        return bigInteger;
                    }
                }
                if (num < num2)
                {
                    do
                    {
                        data[(int)num] = array[(int)num];
                    }
                    while ((num += 1U) < num2);
                }
                bigInteger.Normalize();
                return bigInteger;
            }
References System.array, Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Normalize(), and System.U.
Referenced by Mono.Math.BigInteger.operator+().