Terraria Decompiled: Mono.Math.BigInteger.Kernel.multiByteDivide
multiByteDivide()
static BigInteger[] Mono.Math.BigInteger.Kernel.multiByteDivide (BigInteger bi1, BigInteger bi2) inline static
Definition at line 1391 of file BigInteger.cs.
            {
                if (BigInteger.Kernel.Compare(bi1, bi2) == BigInteger.Sign.Negative)
                {
                    return new BigInteger[]
                    {
                        0,
                        new BigInteger(bi1)
                    };
                }
                bi1.Normalize();
                bi2.Normalize();
                if (bi2.length == 1U)
                {
                    return BigInteger.Kernel.DwordDivMod(bi1, bi2.data[0]);
                }
                uint num = bi1.length + 1U;
                int num2 = (int)(bi2.length + 1U);
                uint num3 = 2147483648U;
                uint num4 = bi2.data[(int)(bi2.length - 1U)];
                int num5 = 0;
                int num6 = (int)(bi1.length - bi2.length);
                while (num3 != 0U && (num4 & num3) == 0U)
                {
                    num5++;
                    num3 >>= 1;
                }
                BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, bi1.length - bi2.length + 1U);
                BigInteger bigInteger2 = bi1 << num5;
                uint[] data = bigInteger2.data;
                bi2 <<= num5;
                int i = (int)(num - bi2.length);
                int num7 = (int)(num - 1U);
                uint num8 = bi2.data[(int)(bi2.length - 1U)];
                ulong num9 = (ulong)bi2.data[(int)(bi2.length - 2U)];
                while (i > 0)
                {
                    ulong num10 = ((ulong)data[num7] << 32) + (ulong)data[num7 - 1];
                    ulong num11 = num10 / (ulong)num8;
                    ulong num12 = num10 % (ulong)num8;
                    while (num11 == 4294967296UL || num11 * num9 > (num12 << 32) + (ulong)data[num7 - 2])
                    {
                        num11 -= 1UL;
                        num12 += (ulong)num8;
                        if (num12 >= 4294967296UL)
{
                            break;
                        }
                    }
                    uint num13 = 0U;
                    int num14 = num7 - num2 + 1;
                    ulong num15 = 0UL;
                    uint num16 = (uint)num11;
                    do
                    {
                        num15 += (ulong)bi2.data[(int)num13] * (ulong)num16;
                        uint num17 = data[num14];
                        data[num14] -= (uint)num15;
                        num15 >>= 32;
                        if (data[num14] > num17)
{
                            num15 += 1UL;
                        }
                        num13 += 1U;
                        num14++;
                    }
                    while ((ulong)num13 < (ulong)((long)num2));
                    num14 = num7 - num2 + 1;
                    num13 = 0U;
                    if (num15 != 0UL)
                    {
                        num16 -= 1U;
                        ulong num18 = 0UL;
                        do
{
                            num18 = (ulong)data[num14] + (ulong)bi2.data[(int)num13] + num18;
                            data[num14] = (uint)num18;
                            num18 >>= 32;
                            num13 += 1U;
                            num14++;
                        }
                        while ((ulong)num13 < (ulong)((long)num2));
                    }
                    bigInteger.data[num6--] = num16;
                    num7--;
                    i--;
                }
                bigInteger.Normalize();
                bigInteger2.Normalize();
                BigInteger[] array = new BigInteger[] { bigInteger, bigInteger2 };
                if (num5 != 0)
                {
                    BigInteger[] array2 = array;
                    array2[1] = array2[1] >> num5;
                }
                return array;
            }
References System.array, Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.Kernel.Compare(), Mono.Math.BigInteger.data, Mono.Math.BigInteger.Kernel.DwordDivMod(), int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Normalize(), and System.U.
Referenced by Mono.Math.BigInteger.Kernel.modInverse(), Mono.Math.BigInteger.operator%(), and Mono.Math.BigInteger.operator/().