Terraria Decompiled: Mono.Math.BigInteger.Kernel.Subtract
Subtract()
static BigInteger Mono.Math.BigInteger.Kernel.Subtract (BigInteger big, BigInteger small) inline static
Definition at line 1129 of file BigInteger.cs.
            {
                BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, big.length);
                uint[] data = bigInteger.data;
                uint[] data2 = big.data;
                uint[] data3 = small.data;
                uint num = 0U;
                uint num2 = 0U;
                do
                {
                    uint num3 = data3[(int)num];
                    if (((num3 += num2) < num2) | ((data[(int)num] = data2[(int)num] - num3) > ~num3))
                    {
                        num2 = 1U;
                    }
                    else
                    {
                        num2 = 0U;
                    }
                }
                while ((num += 1U) < small.length);
                if (num != big.length)
                {
                    if (num2 == 1U)
                    {
                        do
{
                            data[(int)num] = data2[(int)num] - 1U;
                        }
                        while (data2[(int)num++] == 0U && num < big.length);
                        if (num == big.length)
{
                            goto IL_00B8;
                        }
                    }
                    do
                    {
                        data[(int)num] = data2[(int)num];
                    }
                    while ((num += 1U) < big.length);
                }
                IL_00B8:
                bigInteger.Normalize();
                return bigInteger;
            }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Normalize(), and System.U.
Referenced by Mono.Math.BigInteger.operator-().