Terraria Decompiled: Mono.Math.BigInteger.Kernel.modInverse
modInverse() [1/2]
static BigInteger Mono.Math.BigInteger.Kernel.modInverse (BigInteger bi, BigInteger modulus) inline static
Definition at line 1917 of file BigInteger.cs.
            {
                if (modulus.length == 1U)
                {
                    return BigInteger.Kernel.modInverse(bi, modulus.data[0]);
                }
                BigInteger[] array = new BigInteger[] { 0, 1 };
                BigInteger[] array2 = new BigInteger[2];
                BigInteger[] array3 = new BigInteger[] { 0, 0 };
                int num = 0;
                BigInteger bigInteger = modulus;
                BigInteger bigInteger2 = bi;
                BigInteger.ModulusRing modulusRing = new BigInteger.ModulusRing(modulus);
                while (bigInteger2 != 0U)
                {
                    if (num > 1)
                    {
                        BigInteger bigInteger3 = modulusRing.Difference(array[0], array[1] * array2[0]);
                        array[0] = array[1];
                        array[1] = bigInteger3;
                    }
                    BigInteger[] array4 = BigInteger.Kernel.multiByteDivide(bigInteger, bigInteger2);
                    array2[0] = array2[1];
                    array2[1] = array4[0];
                    array3[0] = array3[1];
                    array3[1] = array4[1];
                    bigInteger = bigInteger2;
                    bigInteger2 = array4[1];
                    num++;
                }
                if (array3[0] != 1U)
                {
                    throw new ArithmeticException("No inverse!");
                }
                return modulusRing.Difference(array[0], array[1] * array2[0]);
            }
References System.array, Mono.Math.BigInteger.data, Mono.Math.BigInteger.ModulusRing.Difference(), Mono.Math.BigInteger.length, Mono.Math.BigInteger.Kernel.modInverse(), Mono.Math.BigInteger.Kernel.multiByteDivide(), and System.U.