Terraria Decompiled: Mono.Math.BigInteger.Kernel.Compare
Compare()
static BigInteger.Sign Mono.Math.BigInteger.Kernel.Compare (BigInteger bi1, BigInteger bi2) inline static
Definition at line 1281 of file BigInteger.cs.
            {
                uint num = bi1.length;
                uint num2 = bi2.length;
                while (num > 0U)
                {
                    if (bi1.data[(int)(num - 1U)] != 0U)
                    {
                        break;
                    }
                    num -= 1U;
                }
                while (num2 > 0U && bi2.data[(int)(num2 - 1U)] == 0U)
                {
                    num2 -= 1U;
                }
                if (num == 0U && num2 == 0U)
                {
                    return BigInteger.Sign.Zero;
                }
                if (num < num2)
                {
                    return BigInteger.Sign.Negative;
                }
                if (num > num2)
                {
                    return BigInteger.Sign.Positive;
                }
                uint num3 = num - 1U;
                while (num3 != 0U && bi1.data[(int)num3] == bi2.data[(int)num3])
                {
                    num3 -= 1U;
                }
                if (bi1.data[(int)num3] < bi2.data[(int)num3])
                {
                    return BigInteger.Sign.Negative;
                }
                if (bi1.data[(int)num3] > bi2.data[(int)num3])
                {
                    return BigInteger.Sign.Positive;
                }
                return BigInteger.Sign.Zero;
            }
References Mono.Math.BigInteger.data, Mono.Math.BigInteger.length, and System.U.
Referenced by Mono.Math.BigInteger.Compare(), Mono.Math.BigInteger.ModulusRing.Difference(), Mono.Math.BigInteger.Equals(), Mono.Math.BigInteger.Kernel.multiByteDivide(), Mono.Math.BigInteger.operator!=(), Mono.Math.BigInteger.operator-(), Mono.Math.BigInteger.operator<(), Mono.Math.BigInteger.operator<=(), Mono.Math.BigInteger.operator==(), Mono.Math.BigInteger.operator>(), and Mono.Math.BigInteger.operator>=().