Terraria Decompiled: Mono.Math.BigInteger.Kernel.DwordDivMod
DwordDivMod()
static BigInteger[] Mono.Math.BigInteger.Kernel.DwordDivMod (BigInteger n, uint d) inline static
Definition at line 1373 of file BigInteger.cs.
            {
                BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, n.length);
                ulong num = 0UL;
                uint length = n.length;
                while (length-- > 0U)
                {
                    num <<= 32;
                    num |= (ulong)n.data[(int)length];
                    bigInteger.data[(int)length] = (uint)(num / (ulong)d);
                    num %= (ulong)d;
                }
                bigInteger.Normalize();
                BigInteger bigInteger2 = (uint)num;
                return new BigInteger[] { bigInteger, bigInteger2 };
            }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Normalize(), and System.U.
Referenced by Mono.Math.BigInteger.Kernel.multiByteDivide().