Terraria Decompiled: Mono.Math.BigInteger.Kernel.MultiplyByDword
MultiplyByDword()
static BigInteger Mono.Math.BigInteger.Kernel.MultiplyByDword (BigInteger n, uint f) inline static
Definition at line 1574 of file BigInteger.cs.
            {
                BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, n.length + 1U);
                uint num = 0U;
                ulong num2 = 0UL;
                do
                {
                    num2 += (ulong)n.data[(int)num] * (ulong)f;
                    bigInteger.data[(int)num] = (uint)num2;
                    num2 >>= 32;
                }
                while ((num += 1U) < n.length);
                bigInteger.data[(int)num] = (uint)num2;
                bigInteger.Normalize();
                return bigInteger;
            }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Normalize(), and System.U.
Referenced by Mono.Math.BigInteger.operator*().