Terraria Decompiled: Mono.Math.BigInteger.Kernel.RightShift
RightShift()
static BigInteger Mono.Math.BigInteger.Kernel.RightShift (BigInteger bi, int n) inline static
Definition at line 1535 of file BigInteger.cs.
            {
                if (n == 0)
                {
                    return new BigInteger(bi);
                }
                int num = n >> 5;
                bool flag = (n & 31) != 0;
                BigInteger bigInteger = new BigInteger(BigInteger.Sign.Positive, bi.length - (uint)num + 1U);
                uint num2 = (uint)(bigInteger.data.Length - 1);
                if (flag)
                {
                    uint num3 = 0U;
                    while (num2-- > 0U)
                    {
                        uint num4;
                        checked
{
                            num4 = bi.data[(int)((IntPtr)(unchecked((ulong)num2 + (ulong)((long)num))))];
                            bigInteger.data[(int)num2] = (num4 >> n) | num3;
                        }
                        num3 = num4 << 32 - n;
                    }
                }
                else
                {
                    while (num2-- > 0U)
                    {
                        checked
{
                            bigInteger.data[(int)num2] = bi.data[(int)((IntPtr)(unchecked((ulong)num2 + (ulong)((long)num))))];
                        }
                    }
                }
                bigInteger.Normalize();
                return bigInteger;
            }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Normalize(), and System.U.
Referenced by Mono.Math.BigInteger.operator>>().