Terraria Decompiled: System.Globalization.HebrewCalendar.AddMonths
AddMonths()
override DateTime System.Globalization.HebrewCalendar.AddMonths (DateTime time, int months) inline
Definition at line 216 of file HebrewCalendar.cs.
        {
            DateTime dateTime;
            try
            {
                int num = this.GetDatePart(time.Ticks, 0);
                int datePart = this.GetDatePart(time.Ticks, 2);
                int num2 = this.GetDatePart(time.Ticks, 3);
                int i;
                if (months >= 0)
                {
                    int num3;
                    for (i = datePart + months; i > (num3 = this.GetMonthsInYear(num, 0)); i -= num3)
                    {
                        num++;
                    }
                }
                else if ((i = datePart + months) <= 0)
                {
                    months = -months;
                    months -= datePart;
                    num--;
                    int num3;
                    while (months > (num3 = this.GetMonthsInYear(num, 0)))
                    {
                        num--;
                        months -= num3;
                    }
                    num3 = this.GetMonthsInYear(num, 0);
                    i = num3 - months;
                }
                int daysInMonth = this.GetDaysInMonth(num, i);
                if (num2 > daysInMonth)
                {
                    num2 = daysInMonth;
                }
                dateTime = this.ToDateTime(num, i, num2, 0, 0, 0, 0);
                dateTime = new DateTime(dateTime.Ticks + time.Ticks % 864000000000L);
            }
            catch (ArgumentException)
            {
                throw new ArgumentOutOfRangeException("months", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Value to add was out of range."), Array.Empty<object>()));
            }
            return dateTime;
        }
References System.Globalization.CultureInfo.CurrentCulture, System.DateTime, System.Globalization.Format, System.Globalization.HebrewCalendar.GetDatePart(), System.Globalization.HebrewCalendar.GetDaysInMonth(), System.Globalization.HebrewCalendar.GetMonthsInYear(), System.Environment.GetResourceString(), System.L, System.DateTime.Ticks, and System.Globalization.HebrewCalendar.ToDateTime().