Terraria Decompiled: System.Globalization.HebrewCalendar.AddYears
AddYears()
override DateTime System.Globalization.HebrewCalendar.AddYears (DateTime time, int years) inline
Definition at line 263 of file HebrewCalendar.cs.
        {
            int num = this.GetDatePart(time.Ticks, 0);
            int num2 = this.GetDatePart(time.Ticks, 2);
            int num3 = this.GetDatePart(time.Ticks, 3);
            num += years;
            HebrewCalendar.CheckHebrewYearValue(num, 0, "years");
            int monthsInYear = this.GetMonthsInYear(num, 0);
            if (num2 > monthsInYear)
            {
                num2 = monthsInYear;
            }
            int daysInMonth = this.GetDaysInMonth(num, num2);
            if (num3 > daysInMonth)
            {
                num3 = daysInMonth;
            }
            long num4 = this.ToDateTime(num, num2, num3, 0, 0, 0, 0).Ticks + time.Ticks % 864000000000L;
            Calendar.CheckAddResult(num4, this.MinSupportedDateTime, this.MaxSupportedDateTime);
            return new DateTime(num4);
        }
References System.Globalization.Calendar.CheckAddResult(), System.Globalization.HebrewCalendar.CheckHebrewYearValue(), System.DateTime, System.Globalization.HebrewCalendar.GetDatePart(), System.Globalization.HebrewCalendar.GetDaysInMonth(), System.Globalization.HebrewCalendar.GetMonthsInYear(), System.L, System.Globalization.HebrewCalendar.MaxSupportedDateTime, System.Globalization.HebrewCalendar.MinSupportedDateTime, System.DateTime.Ticks, and System.Globalization.HebrewCalendar.ToDateTime().