Terraria Decompiled: System.Globalization.HebrewCalendar.GetDatePart
GetDatePart()
virtual int System.Globalization.HebrewCalendar.GetDatePart (long ticks, int part) inline package virtual
Definition at line 164 of file HebrewCalendar.cs.
        {
            HebrewCalendar.CheckTicksRange(ticks);
            DateTime dateTime = new DateTime(ticks);
            int year = dateTime.Year;
            int month = dateTime.Month;
            int day = dateTime.Day;
            HebrewCalendar.__DateBuffer _DateBuffer = new HebrewCalendar.__DateBuffer();
            _DateBuffer.year = year + 3760;
            int num = HebrewCalendar.GetLunarMonthDay(year, _DateBuffer);
            HebrewCalendar.__DateBuffer _DateBuffer2 = new HebrewCalendar.__DateBuffer();
            _DateBuffer2.year = _DateBuffer.year;
            _DateBuffer2.month = _DateBuffer.month;
            _DateBuffer2.day = _DateBuffer.day;
            long absoluteDate = GregorianCalendar.GetAbsoluteDate(year, month, day);
            if (month == 1 && day == 1)
            {
                return HebrewCalendar.GetResult(_DateBuffer2, part);
            }
            long num2 = absoluteDate - GregorianCalendar.GetAbsoluteDate(year, 1, 1);
            if (num2 + (long)_DateBuffer.day <= (long)HebrewCalendar.LunarMonthLen[num, _DateBuffer.month])
            {
                _DateBuffer2.day += (int)num2;
                return HebrewCalendar.GetResult(_DateBuffer2, part);
            }
            _DateBuffer2.month++;
            _DateBuffer2.day = 1;
            num2 -= (long)(HebrewCalendar.LunarMonthLen[num, _DateBuffer.month] - _DateBuffer.day);
            if (num2 > 1L)
            {
                while (num2 > (long)HebrewCalendar.LunarMonthLen[num, _DateBuffer2.month])
                {
                    long num3 = num2;
                    int[,] lunarMonthLen = HebrewCalendar.LunarMonthLen;
                    int num4 = num;
                    HebrewCalendar.__DateBuffer _DateBuffer3 = _DateBuffer2;
                    int month2 = _DateBuffer3.month;
                    _DateBuffer3.month = month2 + 1;
                    num2 = num3 - (long)lunarMonthLen[num4, month2];
                    if (_DateBuffer2.month > 13 || HebrewCalendar.LunarMonthLen[num, _DateBuffer2.month] == 0)
                    {
                        _DateBuffer2.year++;
                        num = HebrewCalendar.HebrewTable[(year + 1 - 1583) * 2 + 1];
                        _DateBuffer2.month = 1;
                    }
                }
                _DateBuffer2.day += (int)(num2 - 1L);
            }
            return HebrewCalendar.GetResult(_DateBuffer2, part);
        }
References System.Globalization.HebrewCalendar.CheckTicksRange(), System.DateTime, System.DateTime.Day, System.Globalization.HebrewCalendar.__DateBuffer.day, System.Globalization.GregorianCalendar.GetAbsoluteDate(), System.Globalization.HebrewCalendar.GetLunarMonthDay(), System.Globalization.HebrewCalendar.GetResult(), System.Globalization.HebrewCalendar.HebrewTable, int, System.L, long, System.Globalization.HebrewCalendar.LunarMonthLen, System.DateTime.Month, System.Globalization.HebrewCalendar.__DateBuffer.month, System.DateTime.Year, and System.Globalization.HebrewCalendar.__DateBuffer.year.
Referenced by System.Globalization.HebrewCalendar.AddMonths(), System.Globalization.HebrewCalendar.AddYears(), System.Globalization.HebrewCalendar.GetDayOfMonth(), System.Globalization.HebrewCalendar.GetMonth(), and System.Globalization.HebrewCalendar.GetYear().