Terraria Decompiled: System.Globalization.HebrewCalendar.HebrewToGregorian
HebrewToGregorian()
static DateTime System.Globalization.HebrewCalendar.HebrewToGregorian (int hebrewYear, int hebrewMonth, int hebrewDay, int hour, int minute, int second, int millisecond) inline static private
Definition at line 457 of file HebrewCalendar.cs.
        {
            int num = hebrewYear - 3760;
            HebrewCalendar.__DateBuffer _DateBuffer = new HebrewCalendar.__DateBuffer();
            int lunarMonthDay = HebrewCalendar.GetLunarMonthDay(num, _DateBuffer);
            if (hebrewMonth == _DateBuffer.month && hebrewDay == _DateBuffer.day)
            {
                return new DateTime(num, 1, 1, hour, minute, second, millisecond);
            }
            int dayDifference = HebrewCalendar.GetDayDifference(lunarMonthDay, hebrewMonth, hebrewDay, _DateBuffer.month, _DateBuffer.day);
            DateTime dateTime = new DateTime(num, 1, 1);
            return new DateTime(dateTime.Ticks + (long)dayDifference * 864000000000L + Calendar.TimeToTicks(hour, minute, second, millisecond));
        }
References System.DateTime, System.Globalization.HebrewCalendar.__DateBuffer.day, System.Globalization.HebrewCalendar.GetDayDifference(), System.Globalization.HebrewCalendar.GetLunarMonthDay(), System.L, System.Globalization.HebrewCalendar.__DateBuffer.month, System.DateTime.Ticks, and System.Globalization.Calendar.TimeToTicks().
Referenced by System.Globalization.HebrewCalendar.ToDateTime().