Terraria Decompiled: System.Globalization.HebrewCalendar.ToDateTime
ToDateTime()
override DateTime System.Globalization.HebrewCalendar.ToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era) inline
Definition at line 472 of file HebrewCalendar.cs.
        {
            HebrewCalendar.CheckHebrewYearValue(year, era, "year");
            this.CheckHebrewMonthValue(year, month, era);
            this.CheckHebrewDayValue(year, month, day, era);
            DateTime dateTime = HebrewCalendar.HebrewToGregorian(year, month, day, hour, minute, second, millisecond);
            HebrewCalendar.CheckTicksRange(dateTime.Ticks);
            return dateTime;
        }
References System.Globalization.HebrewCalendar.CheckHebrewDayValue(), System.Globalization.HebrewCalendar.CheckHebrewMonthValue(), System.Globalization.HebrewCalendar.CheckHebrewYearValue(), System.Globalization.HebrewCalendar.CheckTicksRange(), System.Globalization.HebrewCalendar.HebrewToGregorian(), and System.DateTime.Ticks.
Referenced by System.Globalization.HebrewCalendar.AddMonths(), System.Globalization.HebrewCalendar.AddYears(), and System.Globalization.HebrewCalendar.GetDayOfYear().