Terraria Decompiled: Ionic.Zip.ZipCrypto.ForRead
ForRead()
static ZipCrypto Ionic.Zip.ZipCrypto.ForRead (string password, ZipEntry e) inline static
Definition at line 28 of file ZipCrypto.cs.
        {
            Stream archiveStream = e._archiveStream;
            e._WeakEncryptionHeader = new byte[12];
            byte[] weakEncryptionHeader = e._WeakEncryptionHeader;
            ZipCrypto zipCrypto = new ZipCrypto();
            if (password == null)
            {
                throw new BadPasswordException("This entry requires a password.");
            }
            zipCrypto.InitCipher(password);
            ZipEntry.ReadWeakEncryptionHeader(archiveStream, weakEncryptionHeader);
            byte[] array = zipCrypto.DecryptMessage(weakEncryptionHeader, weakEncryptionHeader.Length);
            if (array[11] != (byte)((e._Crc32 >> 24) & 255))
            {
                if ((e._BitField & 8) != 8)
                {
                    throw new BadPasswordException("The password did not match.");
                }
                if (array[11] != (byte)((e._TimeBlob >> 8) & 255))
                {
                    throw new BadPasswordException("The password did not match.");
                }
            }
            return zipCrypto;
        }
References Ionic.Zip.ZipEntry._archiveStream, Ionic.Zip.ZipEntry._BitField, Ionic.Zip.ZipEntry._Crc32, Ionic.Zip.ZipEntry._TimeBlob, Ionic.Zip.ZipEntry._WeakEncryptionHeader, System.array, Ionic.Zip.ZipCrypto.DecryptMessage(), Ionic.Zip.ZipCrypto.InitCipher(), Ionic.Zip.ZipEntry.ReadWeakEncryptionHeader(), and Ionic.Zip.ZipCrypto.ZipCrypto().
Referenced by Ionic.Zip.ZipEntry.SetupCryptoForExtract().