Terraria Decompiled: Ionic.Zip.ZipCrypto.UpdateKeys
UpdateKeys()
void Ionic.Zip.ZipCrypto.UpdateKeys (byte byteValue) inline private
Definition at line 119 of file ZipCrypto.cs.
        {
            this._Keys[0] = (uint)this.crc32.ComputeCrc32((int)this._Keys[0], byteValue);
            this._Keys[1] = this._Keys[1] + (uint)((byte)this._Keys[0]);
            this._Keys[1] = this._Keys[1] * 134775813U + 1U;
            this._Keys[2] = (uint)this.crc32.ComputeCrc32((int)this._Keys[2], (byte)(this._Keys[1] >> 24));
        }
References Ionic.Zip.ZipCrypto._Keys, Ionic.Crc.CRC32.ComputeCrc32(), Ionic.Zip.ZipCrypto.crc32, and System.U.
Referenced by Ionic.Zip.ZipCrypto.DecryptMessage(), Ionic.Zip.ZipCrypto.EncryptMessage(), and Ionic.Zip.ZipCrypto.InitCipher().