Terraria Decompiled: System.Globalization.UmAlQuraCalendar.AddMonths
AddMonths()
override DateTime System.Globalization.UmAlQuraCalendar.AddMonths (DateTime time, int months) inline
Definition at line 287 of file UmAlQuraCalendar.cs.
        {
            if (months < -120000 || months > 120000)
            {
                throw new ArgumentOutOfRangeException("months", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Valid values are between {0} and {1}, inclusive."), -120000, 120000));
            }
            int num = this.GetDatePart(time, 0);
            int num2 = this.GetDatePart(time, 2);
            int num3 = this.GetDatePart(time, 3);
            int num4 = num2 - 1 + months;
            if (num4 >= 0)
            {
                num2 = num4 % 12 + 1;
                num += num4 / 12;
            }
            else
            {
                num2 = 12 + (num4 + 1) % 12;
                num += (num4 - 11) / 12;
            }
            if (num3 > 29)
            {
                int daysInMonth = this.GetDaysInMonth(num, num2);
                if (num3 > daysInMonth)
                {
                    num3 = daysInMonth;
                }
            }
            UmAlQuraCalendar.CheckYearRange(num, 1);
            DateTime dateTime = new DateTime(UmAlQuraCalendar.GetAbsoluteDateUmAlQura(num, num2, num3) * 864000000000L + time.Ticks % 864000000000L);
            Calendar.CheckAddResult(dateTime.Ticks, this.MinSupportedDateTime, this.MaxSupportedDateTime);
            return dateTime;
        }
References System.Globalization.Calendar.CheckAddResult(), System.Globalization.UmAlQuraCalendar.CheckYearRange(), System.Globalization.CultureInfo.CurrentCulture, System.DateTime, System.Globalization.Format, System.Globalization.UmAlQuraCalendar.GetAbsoluteDateUmAlQura(), System.Globalization.UmAlQuraCalendar.GetDatePart(), System.Globalization.UmAlQuraCalendar.GetDaysInMonth(), System.Environment.GetResourceString(), System.L, and System.DateTime.Ticks.
Referenced by System.Globalization.UmAlQuraCalendar.AddYears().