Terraria Decompiled: System.Globalization.UmAlQuraCalendar.ConvertGregorianToHijri
ConvertGregorianToHijri()
static void System.Globalization.UmAlQuraCalendar.ConvertGregorianToHijri (DateTime time, ref int HijriYear, ref int HijriMonth, ref int HijriDay) inline static private
Definition at line 229 of file UmAlQuraCalendar.cs.
        {
            int num = (int)((time.Ticks - UmAlQuraCalendar.minDate.Ticks) / 864000000000L) / 355;
            while (time.CompareTo(UmAlQuraCalendar.HijriYearInfo[++num].GregorianDate) > 0)
            {
            }
            if (time.CompareTo(UmAlQuraCalendar.HijriYearInfo[num].GregorianDate) != 0)
            {
                num--;
            }
            TimeSpan timeSpan = time.Subtract(UmAlQuraCalendar.HijriYearInfo[num].GregorianDate);
            int num2 = num + 1318;
            int num3 = 1;
            int num4 = 1;
            double num5 = timeSpan.TotalDays;
            int num6 = UmAlQuraCalendar.HijriYearInfo[num].HijriMonthsLengthFlags;
            int num7 = 29 + (num6 & 1);
            while (num5 >= (double)num7)
            {
                num5 -= (double)num7;
                num6 >>= 1;
                num7 = 29 + (num6 & 1);
                num3++;
            }
            num4 += (int)num5;
            HijriDay = num4;
            HijriMonth = num3;
            HijriYear = num2;
        }
References System.DateTime.CompareTo(), System.Globalization.UmAlQuraCalendar.HijriYearInfo, int, System.L, System.Globalization.UmAlQuraCalendar.minDate, System.DateTime.Subtract(), System.DateTime.Ticks, and System.TimeSpan.TotalDays.
Referenced by System.Globalization.UmAlQuraCalendar.GetDatePart().