Terraria Decompiled: System.Globalization.UmAlQuraCalendar.ToDateTime
ToDateTime()
override DateTime System.Globalization.UmAlQuraCalendar.ToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era) inline
Definition at line 450 of file UmAlQuraCalendar.cs.
        {
            if (day >= 1 && day <= 29)
            {
                UmAlQuraCalendar.CheckYearMonthRange(year, month, era);
            }
            else
            {
                int daysInMonth = this.GetDaysInMonth(year, month, era);
                if (day < 1 || day > daysInMonth)
                {
                    throw new ArgumentOutOfRangeException("day", string.Format(CultureInfo.CurrentCulture, Environment.GetResourceString("Day must be between 1 and {0} for month {1}."), daysInMonth, month));
                }
            }
            long absoluteDateUmAlQura = UmAlQuraCalendar.GetAbsoluteDateUmAlQura(year, month, day);
            if (absoluteDateUmAlQura >= 0L)
            {
                return new DateTime(absoluteDateUmAlQura * 864000000000L + Calendar.TimeToTicks(hour, minute, second, millisecond));
            }
            throw new ArgumentOutOfRangeException(null, Environment.GetResourceString("Year, Month, and Day parameters describe an un-representable DateTime."));
        }
References System.Globalization.UmAlQuraCalendar.CheckYearMonthRange(), System.Globalization.CultureInfo.CurrentCulture, System.DateTime, System.Globalization.Format, System.Globalization.UmAlQuraCalendar.GetAbsoluteDateUmAlQura(), System.Globalization.UmAlQuraCalendar.GetDaysInMonth(), System.Environment.GetResourceString(), System.L, and System.Globalization.Calendar.TimeToTicks().