Terraria Decompiled: System.Collections.Generic.IEnumerable.GetEnumerator
GetEnumerator()
IEnumerator< T > System.Collections.Generic.IEnumerable< out T >.GetEnumerator ()
Implements System.Collections.IEnumerable.
Implemented in CsvHelper.Configuration.CsvPropertyMapCollection, CsvHelper.Configuration.CsvPropertyMapCollection, CsvHelper.Configuration.CsvPropertyNameCollection, CsvHelper.Configuration.CsvPropertyNameCollection, Microsoft.Xna.Framework.CurveKeyCollection, Microsoft.Xna.Framework.CurveKeyCollection, Microsoft.Xna.Framework.Graphics.DisplayModeCollection, Microsoft.Xna.Framework.Graphics.DisplayModeCollection, Microsoft.Xna.Framework.Graphics.EffectAnnotationCollection, Microsoft.Xna.Framework.Graphics.EffectAnnotationCollection, Microsoft.Xna.Framework.Graphics.EffectAnnotationCollection, Microsoft.Xna.Framework.Graphics.EffectParameterCollection, Microsoft.Xna.Framework.Graphics.EffectParameterCollection, Microsoft.Xna.Framework.Graphics.EffectParameterCollection, Microsoft.Xna.Framework.Graphics.EffectPassCollection, Microsoft.Xna.Framework.Graphics.EffectPassCollection, Microsoft.Xna.Framework.Graphics.EffectPassCollection, Microsoft.Xna.Framework.Graphics.EffectTechniqueCollection, Microsoft.Xna.Framework.Graphics.EffectTechniqueCollection, Microsoft.Xna.Framework.Graphics.EffectTechniqueCollection, Microsoft.Xna.Framework.Input.Touch.TouchCollection, Microsoft.Xna.Framework.Input.Touch.TouchCollection, Microsoft.Xna.Framework.Input.Touch.TouchCollection, Microsoft.Xna.Framework.Media.AlbumCollection, Microsoft.Xna.Framework.Media.AlbumCollection, Microsoft.Xna.Framework.Media.ArtistCollection, Microsoft.Xna.Framework.Media.ArtistCollection, Microsoft.Xna.Framework.Media.GenreCollection, Microsoft.Xna.Framework.Media.GenreCollection, Microsoft.Xna.Framework.Media.PictureAlbumCollection, Microsoft.Xna.Framework.Media.PictureAlbumCollection, Microsoft.Xna.Framework.Media.PictureCollection, Microsoft.Xna.Framework.Media.PictureCollection, Microsoft.Xna.Framework.Media.PlaylistCollection, Microsoft.Xna.Framework.Media.PlaylistCollection, Microsoft.Xna.Framework.Media.SongCollection, Microsoft.Xna.Framework.Media.SongCollection, Ionic.Zip.ZipFile, Ionic.Zip.ZipFile, System.Array, System.ArraySegment< T >, System.ArraySegment< T >, System.ArraySegment< T >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.Dictionary< TKey, TValue >.KeyCollection, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.Dictionary< TKey, TValue >.ValueCollection, System.Collections.Generic.List< T >, System.Collections.Generic.List< T >, System.Collections.Generic.List< T >, System.Collections.Generic.LowLevelListWithIList< T >, System.Collections.Generic.LowLevelListWithIList< T >, System.Collections.Generic.Queue< T >, System.Collections.Generic.Queue< T >, System.Collections.Generic.Queue< T >, System.Collections.Generic.Stack< T >, System.Collections.Generic.Stack< T >, System.Collections.Generic.Stack< T >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.Collections.ObjectModel.ReadOnlyDictionary< TKey, TValue >, System.IO.Enumeration.FileSystemEnumerable< TResult >, System.IO.Enumeration.FileSystemEnumerable< TResult >, System.IO.Iterator< TSource >, System.IO.Iterator< TSource >, System.Resources.ResourceFallbackManager, System.Resources.ResourceFallbackManager, System.Resources.ResourceReader, System.Resources.ResourceReader, System.Resources.RuntimeResourceSet, System.Resources.RuntimeResourceSet, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >, System.Runtime.CompilerServices.ConditionalWeakTable< TKey, TValue >, System.Security.Principal.IdentityReferenceCollection, System.Security.Principal.IdentityReferenceCollection, System.String, System.String, System.String, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >, System.Threading.Tasks.SingleProducerSingleConsumerQueue< T >, Newtonsoft.Json.Bson.BsonArray, Newtonsoft.Json.Bson.BsonArray, Newtonsoft.Json.Bson.BsonObject, Newtonsoft.Json.Bson.BsonObject, Newtonsoft.Json.Linq.JArray, Newtonsoft.Json.Linq.JEnumerable< T >, Newtonsoft.Json.Linq.JEnumerable< T >, Newtonsoft.Json.Linq.JObject, Newtonsoft.Json.Linq.JProperty.JPropertyList, Newtonsoft.Json.Linq.JProperty.JPropertyList, Newtonsoft.Json.Linq.JToken, Newtonsoft.Json.Linq.JToken, Newtonsoft.Json.Linq.JToken, Newtonsoft.Json.Linq.JToken, Newtonsoft.Json.Serialization.DefaultContractResolver.EnumerableDictionaryWrapper< TEnumeratorKey, TEnumeratorValue >, Newtonsoft.Json.Serialization.DefaultContractResolver.EnumerableDictionaryWrapper< TEnumeratorKey, TEnumeratorValue >, Newtonsoft.Json.Utilities.CollectionWrapper< T >, Newtonsoft.Json.Utilities.CollectionWrapper< T >, Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >, Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >, Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >, NVorbis.Codebook.FastRange, NVorbis.Codebook.FastRange, ReLogic.Peripherals.RGB.Corsair.CorsairDeviceGroup, ReLogic.Peripherals.RGB.HotkeyCollection, ReLogic.Peripherals.RGB.HotkeyCollection, ReLogic.Peripherals.RGB.Logitech.LogitechDeviceGroup, ReLogic.Peripherals.RGB.Razer.RazerDeviceGroup, ReLogic.Peripherals.RGB.RgbDeviceGroup, ReLogic.Peripherals.RGB.RgbDeviceGroup, ReLogic.Peripherals.RGB.SteelSeries.SteelSeriesDeviceGroup, ReLogic.Peripherals.RGB.VirtualRgbDeviceGroup, ReLogic.Utilities.SlotVector< T >, ReLogic.Utilities.SlotVector< T >, Terraria.GameContent.Personalities.BiomePreferenceListTrait, Terraria.GameContent.Personalities.BiomePreferenceListTrait, Terraria.GameContent.UI.Elements.UIList, Terraria.GameContent.UI.Elements.UIList, Terraria.Testing.ChatCommands.ArgumentListResult, and Terraria.Testing.ChatCommands.ArgumentListResult.
Referenced by System.Threading.Tasks.TaskExceptionHolder.AddFaultException(), Ionic.Zip.ZipFile.AddFiles(), Newtonsoft.Json.Linq.JContainer.AddInternal(), System.Collections.Generic.LargeArrayBuilder< T >.AddRange(), System.Diagnostics.StackTrace.ConvertAsyncStateMachineMethod(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.CopyTo(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.FindNext(), Newtonsoft.Json.Linq.Extensions.GetEnumerator(), Newtonsoft.Json.Linq.JToken.GetEnumerator(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.GetEnumerator(), Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.IsMatch(), Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots(), Newtonsoft.Json.Linq.JContainer.MergeEnumerableContent(), System.IO.File.d__80.MoveNext(), Newtonsoft.Json.Linq.Extensions.MoveNext(), Mono.DataConverter.PackEnumerable(), System.Threading.Tasks.Parallel.PartitionerForEachWorker< TSource, TLocal >(), and Terraria.GameContent.UI.States.UIWorldGenDebug.RunTest().