Terraria Decompiled: Terraria.ID.TileID.Sets.Platforms
Platforms
bool [] Terraria.ID.TileID.Sets.Platforms = TileID.Sets.Factory.CreateBoolSet(new int[] { 19, 427, 435, 436, 437, 438, 439 }) static
Definition at line 2549 of file TileID.cs.
Referenced by Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.WorldGen.AnchorValid(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.CheckBanner(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Events.CultistRitual.CheckFloor2(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckTorch(), Terraria.Recipe.CreateReversePlatformRecipes(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.dropMeteor(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.ID.ContentSamples.CreativeHelper.GetItemGroup(), Terraria.Player.GetSmartPlatformSlope(), Terraria.WorldGen.HandleRopeEndFraming_Inner(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.WorldGen.IsBelowANonHammeredPlatform(), Terraria.GameContent.SmartCursorHelper.IsPlatform(), Terraria.WorldGen.IsRope(), Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch(), Terraria.Collision.IsWorldPointSolid(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.DelegateMethods.NotSolidOrPlatforms(), Terraria.NPC.NPCCanStickToWalls(), Terraria.Player.PlaceThing_CheckPlatformSolidityForBlockSwap(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_CheckRopeUsability(), Terraria.Player.PlaceThing_Tiles_PlaceIt_AutoPaintAndActuate(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.Player.PlaceThing_ValidTileForReplacement(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PoundPlatform(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.WorldGen.ReplaceTile_IsValidPlatform(), Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.NPC.SolidOrSlopedTileOrPlatform(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.WorldGen.SolidTileAllowTopSlope(), Terraria.WorldGen.SolidTileNoPlatforms(), Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.DelegateMethods.SpreadTile(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepUp(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.TileIsExposedToAir(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.Player.UpdateBlacklistedTilesForGrappling(), and Terraria.WorldGen.WouldTileReplacementWork().