Terraria Decompiled: System.TypeSpec.Resolve
Resolve()
Type System.TypeSpec.Resolve (Func< AssemblyName, Assembly > assemblyResolver, Func< Assembly, string, bool, Type > typeResolver, bool throwOnError, bool ignoreCase, ref StackCrawlMark stackMark) inline package
Definition at line 269 of file TypeSpec.cs.
        {
            Assembly assembly = null;
            if (assemblyResolver == null && typeResolver == null)
            {
                return RuntimeType.GetType(this.DisplayFullName, throwOnError, ignoreCase, false, ref stackMark);
            }
            if (this.assembly_name != null)
            {
                if (assemblyResolver != null)
                {
                    assembly = assemblyResolver(new AssemblyName(this.assembly_name));
                }
                else
                {
                    assembly = Assembly.Load(this.assembly_name);
                }
                if (assembly == null)
                {
                    if (throwOnError)
                    {
                        throw new FileNotFoundException("Could not resolve assembly '" + this.assembly_name + "'");
                    }
                    return null;
                }
            }
            Type type = null;
            if (typeResolver != null)
            {
                type = typeResolver(assembly, this.name.DisplayName, ignoreCase);
            }
            else
            {
                type = assembly.GetType(this.name.DisplayName, false, ignoreCase);
            }
            if (!(type == null))
            {
                if (this.nested != null)
                {
                    foreach (TypeIdentifier typeIdentifier in this.nested)
                    {
                        Type nestedType = type.GetNestedType(typeIdentifier.DisplayName, BindingFlags.Public | BindingFlags.NonPublic);
                        if (nestedType == null)
{
                            if (throwOnError)
{
                                string text = "Could not resolve type '";
                                TypeIdentifier typeIdentifier2 = typeIdentifier;
                                throw new TypeLoadException(text + ((typeIdentifier2 != null) ? typeIdentifier2.ToString() : null) + "'");
                            }
                            return null;
                        }
                        else
{
                            type = nestedType;
                        }
                    }
                }
                if (this.generic_params != null)
                {
                    Type[] array = new Type[this.generic_params.Count];
                    int i = 0;
                    while (i < array.Length)
                    {
                        Type type2 = this.generic_params[i].Resolve(assemblyResolver, typeResolver, throwOnError, ignoreCase, ref stackMark);
                        if (type2 == null)
{
                            if (throwOnError)
{
                                string text2 = "Could not resolve type '";
                                TypeIdentifier typeIdentifier3 = this.generic_params[i].name;
                                throw new TypeLoadException(text2 + ((typeIdentifier3 != null) ? typeIdentifier3.ToString() : null) + "'");
                            }
                            return null;
                        }
                        else
{
                            array[i] = type2;
                            i++;
                        }
                    }
                    type = type.MakeGenericType(array);
                }
                if (this.modifier_spec != null)
                {
                    foreach (ModifierSpec modifierSpec in this.modifier_spec)
                    {
                        type = modifierSpec.Resolve(type);
                    }
                }
                if (this.is_byref)
                {
                    type = type.MakeByRefType();
                }
                return type;
            }
            if (throwOnError)
            {
                string text3 = "Could not resolve type '";
                TypeIdentifier typeIdentifier4 = this.name;
                throw new TypeLoadException(text3 + ((typeIdentifier4 != null) ? typeIdentifier4.ToString() : null) + "'");
            }
            return null;
        }
References System.array, System.TypeSpec.assembly_name, System.TypeSpec.DisplayFullName, System.TypeName.DisplayName, System.TypeSpec.generic_params, System.Type.GetNestedType(), System.Reflection.Assembly.GetType(), System.RuntimeType.GetType(), System.TypeSpec.is_byref, System.Reflection.Assembly.Load(), System.Type.MakeByRefType(), System.Type.MakeGenericType(), System.TypeSpec.modifier_spec, System.TypeSpec.name, System.TypeSpec.nested, System.ModifierSpec.Resolve(), and System.text.
Referenced by System.TypeNameParser.GetType().