Terraria Decompiled: System.TypeSpec.Parse
Parse() [1/2]
static TypeSpec System.TypeSpec.Parse (string name, ref int p, bool is_recurse, bool allow_aqn) inline static private
Definition at line 426 of file TypeSpec.cs.
        {
            int i = p;
            bool flag = false;
            TypeSpec typeSpec = new TypeSpec();
            TypeSpec.SkipSpace(name, ref i);
            int num = i;
            while (i < name.Length)
            {
                char c = name[i];
                switch (c)
                {
                case '&':
                case '*':
                    goto IL_0098;
                case '\'':
                case '(':
                case ')':
                    break;
                case '+':
                    typeSpec.AddName(name.Substring(num, i - num));
                    num = i + 1;
                    break;
                case ',':
                    goto IL_0077;
                default:
                    switch (c)
                    {
                    case '[':
                        goto IL_0098;
                    case '\\':
                        i++;
                        break;
                    case ']':
                        goto IL_0077;
                    }
                    break;
                }
                IL_00D6:
                if (!flag)
                {
                    i++;
                    continue;
                }
                break;
                IL_0077:
                typeSpec.AddName(name.Substring(num, i - num));
                num = i + 1;
                flag = true;
                if (is_recurse && !allow_aqn)
                {
                    p = i;
                    return typeSpec;
                }
                goto IL_00D6;
                IL_0098:
                if (name[i] != '[' && is_recurse)
                {
                    throw new ArgumentException("Generic argument can't be byref or pointer type", "typeName");
                }
                typeSpec.AddName(name.Substring(num, i - num));
                num = i + 1;
                flag = true;
                goto IL_00D6;
            }
            if (num < i)
            {
                typeSpec.AddName(name.Substring(num, i - num));
            }
            else if (num == i)
            {
                typeSpec.AddName(string.Empty);
            }
            if (flag)
            {
                while (i < name.Length)
                {
                    char c = name[i];
                    if (c <= '*')
                    {
                        if (c != '&')
{
                            if (c != '*')
{
                                goto IL_04BE;
                            }
                            if (typeSpec.is_byref)
{
                                throw new ArgumentException("Can't have a pointer to a byref type", "typeName");
                            }
                            int num2 = 1;
                            while (i + 1 < name.Length && name[i + 1] == '*')
{
                                i++;
                                num2++;
                            }
                            typeSpec.AddModifier(new PointerSpec(num2));
                        }
                        else
{
                            if (typeSpec.is_byref)
{
                                throw new ArgumentException("Can't have a byref of a byref", "typeName");
                            }
                            typeSpec.is_byref = true;
                        }
                    }
                    else if (c != ',')
                    {
                        if (c != '[')
{
                            if (c != ']')
{
                                goto IL_04BE;
                            }
                            if (is_recurse)
{
                                p = i;
                                return typeSpec;
                            }
                            throw new ArgumentException("Unmatched ']'", "typeName");
                        }
                        else
{
                            if (typeSpec.is_byref)
{
                                throw new ArgumentException("Byref qualifier must be the last one of a type", "typeName");
                            }
                            i++;
                            if (i >= name.Length)
{
                                throw new ArgumentException("Invalid array/generic spec", "typeName");
                            }
                            TypeSpec.SkipSpace(name, ref i);
                            if (name[i] != ',' && name[i] != '*' && name[i] != ']')
{
                                List<TypeSpec> list = new List<TypeSpec>();
                                if (typeSpec.HasModifiers)
{
                                    throw new ArgumentException("generic args after array spec or pointer type", "typeName");
                                }
                                while (i < name.Length)
{
                                    TypeSpec.SkipSpace(name, ref i);
                                    bool flag2 = name[i] == '[';
                                    if (flag2)
{
                                        i++;
                                    }
                                    list.Add(TypeSpec.Parse(name, ref i, true, flag2));
                                    TypeSpec.BoundCheck(i, name);
                                    if (flag2)
{
                                        if (name[i] != ']')
{
                                            throw new ArgumentException("Unclosed assembly-qualified type name at " + name[i].ToString(), "typeName");
                                        }
                                        i++;
                                        TypeSpec.BoundCheck(i, name);
                                    }
                                    if (name[i] == ']')
{
                                        break;
                                    }
                                    if (name[i] != ',')
{
                                        throw new ArgumentException("Invalid generic arguments separator " + name[i].ToString(), "typeName");
                                    }
                                    i++;
                                }
                                if (i >= name.Length || name[i] != ']')
{
                                    throw new ArgumentException("Error parsing generic params spec", "typeName");
                                }
                                typeSpec.generic_params = list;
                            }
                            else
{
                                int num3 = 1;
                                bool flag3 = false;
                                while (i < name.Length && name[i] != ']')
{
                                    if (name[i] == '*')
{
                                        if (flag3)
{
                                            throw new ArgumentException("Array spec cannot have 2 bound dimensions", "typeName");
                                        }
                                        flag3 = true;
                                    }
                                    else
{
                                        if (name[i] != ',')
{
                                            throw new ArgumentException("Invalid character in array spec " + name[i].ToString(), "typeName");
                                        }
                                        num3++;
                                    }
                                    i++;
                                    TypeSpec.SkipSpace(name, ref i);
                                }
                                if (i >= name.Length || name[i] != ']')
{
                                    throw new ArgumentException("Error parsing array spec", "typeName");
                                }
                                if (num3 > 1 && flag3)
{
                                    throw new ArgumentException("Invalid array spec, multi-dimensional array cannot be bound", "typeName");
                                }
                                typeSpec.AddModifier(new ArraySpec(num3, flag3));
                            }
                        }
                    }
                    else if (is_recurse && allow_aqn)
                    {
                        int num4 = i;
                        while (num4 < name.Length && name[num4] != ']')
{
                            num4++;
                        }
                        if (num4 >= name.Length)
{
                            throw new ArgumentException("Unmatched ']' while parsing generic argument assembly name");
                        }
                        typeSpec.assembly_name = name.Substring(i + 1, num4 - i - 1).Trim();
                        p = num4;
                        return typeSpec;
                    }
                    else
                    {
                        if (is_recurse)
{
                            p = i;
                            return typeSpec;
                        }
                        if (allow_aqn)
{
                            typeSpec.assembly_name = name.Substring(i + 1).Trim();
                            i = name.Length;
                        }
                    }
                    i++;
                    continue;
                    IL_04BE:
                    throw new ArgumentException("Bad type def, can't handle '" + name[i].ToString() + "' at " + i.ToString(), "typeName");
                }
            }
            p = i;
            return typeSpec;
        }
References System.TypeSpec.AddModifier(), System.TypeSpec.AddName(), System.TypeSpec.BoundCheck(), System.TypeSpec.HasModifiers, System.TypeSpec.is_byref, System.list, System.TypeSpec.name, System.TypeSpec.Parse(), System.TypeSpec.SkipSpace(), System.ToString, and System.TypeSpec.TypeSpec().