Terraria Decompiled: System.TypeSpec.GetDisplayFullName
GetDisplayFullName()
string System.TypeSpec.GetDisplayFullName (TypeSpec::DisplayNameFormat flags) inline private
Definition at line 82 of file TypeSpec.cs.
        {
            bool flag = (flags & TypeSpec.DisplayNameFormat.WANT_ASSEMBLY) > TypeSpec.DisplayNameFormat.Default;
            bool flag2 = (flags & TypeSpec.DisplayNameFormat.NO_MODIFIERS) == TypeSpec.DisplayNameFormat.Default;
            StringBuilder stringBuilder = new StringBuilder(this.name.DisplayName);
            if (this.nested != null)
            {
                foreach (TypeIdentifier typeIdentifier in this.nested)
                {
                    stringBuilder.Append('+').Append(typeIdentifier.DisplayName);
                }
            }
            if (this.generic_params != null)
            {
                stringBuilder.Append('[');
                for (int i = 0; i < this.generic_params.Count; i++)
                {
                    if (i > 0)
                    {
                        stringBuilder.Append(", ");
                    }
                    if (this.generic_params[i].assembly_name != null)
                    {
                        stringBuilder.Append('[').Append(this.generic_params[i].DisplayFullName).Append(']');
                    }
                    else
                    {
                        stringBuilder.Append(this.generic_params[i].DisplayFullName);
                    }
                }
                stringBuilder.Append(']');
            }
            if (flag2)
            {
                this.GetModifierString(stringBuilder);
            }
            if (this.assembly_name != null && flag)
            {
                stringBuilder.Append(", ").Append(this.assembly_name);
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.TypeSpec.assembly_name, System.TypeSpec.DisplayFullName, System.TypeName.DisplayName, System.TypeSpec.generic_params, System.TypeSpec.GetModifierString(), System.TypeSpec.name, System.TypeSpec.nested, and System.Text.StringBuilder.ToString().