Terraria Decompiled: CsvHelper.CsvWriter.WriteExcelSeparator
WriteExcelSeparator()
virtual void CsvHelper.CsvWriter.WriteExcelSeparator () inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 180 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            if (this.hasHeaderBeenWritten)
            {
                throw new CsvWriterException("The Excel seperator record must be the first record written in the file.");
            }
            if (this.hasRecordBeenWritten)
            {
                throw new CsvWriterException("The Excel seperator record must be the first record written in the file.");
            }
            this.WriteField("sep=" + this.configuration.Delimiter, false);
            this.NextRecord();
        }
References CsvHelper.CsvWriter.CheckDisposed(), CsvHelper.CsvWriter.configuration, CsvHelper.Configuration.CsvConfiguration.Delimiter, CsvHelper.CsvWriter.hasHeaderBeenWritten, CsvHelper.CsvWriter.hasRecordBeenWritten, CsvHelper.CsvWriter.NextRecord(), and CsvHelper.CsvWriter.WriteField().
Referenced by CsvHelper.CsvWriter.WriteRecords().