Terraria Decompiled: CsvHelper.CsvWriter.AddProperties
AddProperties()
virtual void CsvHelper.CsvWriter.AddProperties (CsvPropertyMapCollection properties, CsvClassMap mapping) inline protected virtual
Definition at line 355 of file CsvWriter.cs.
        {
            properties.AddRange(mapping.PropertyMaps);
            foreach (CsvPropertyReferenceMap csvPropertyReferenceMap in mapping.ReferenceMaps)
            {
                this.AddProperties(properties, csvPropertyReferenceMap.Data.Mapping);
            }
        }
References CsvHelper.CsvWriter.AddProperties(), CsvHelper.Configuration.CsvPropertyMapCollection.AddRange(), CsvHelper.Configuration.CsvPropertyReferenceMap.Data, CsvHelper.Configuration.CsvPropertyReferenceMapData.Mapping, and CsvHelper.Configuration.CsvClassMap< T >.PropertyMaps.
Referenced by CsvHelper.CsvWriter.AddProperties(), CsvHelper.CsvWriter.CreateActionForObject(), and CsvHelper.CsvWriter.WriteHeader().