Terraria Decompiled: CsvHelper.CsvWriter.WriteField
WriteField() [4/4]
virtual void CsvHelper.CsvWriter.WriteField (Type type, object field, ITypeConverter converter) inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 159 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            TypeConverterOptions options = TypeConverterOptionsFactory.GetOptions(type);
            if (options.CultureInfo == null)
            {
                options.CultureInfo = this.configuration.CultureInfo;
            }
            string text = converter.ConvertToString(options, field);
            this.WriteField(text);
        }
References CsvHelper.CsvWriter.CheckDisposed(), CsvHelper.CsvWriter.configuration, CsvHelper.TypeConversion.ITypeConverter.ConvertToString(), CsvHelper.Configuration.CsvConfiguration.CultureInfo, CsvHelper.TypeConversion.TypeConverterOptionsFactory.GetOptions(), System.options, System.text, and CsvHelper.CsvWriter.WriteField().