Terraria Decompiled: CsvHelper.CsvWriter.WriteRecord
WriteRecord()
virtual void CsvHelper.CsvWriter.WriteRecord (Type type, object record) inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 262 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            try
            {
                try
                {
                    this.GetWriteRecordAction(type).DynamicInvoke(new object[] { record });
                }
                catch (TargetInvocationException ex)
                {
                    throw ex.InnerException;
                }
                this.hasRecordBeenWritten = true;
                this.NextRecord();
            }
            catch (Exception ex2)
            {
                ExceptionHelper.AddExceptionDataMessage(ex2, null, type, null, default(int?), null);
                throw;
            }
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvWriter.CheckDisposed(), System.Delegate.DynamicInvoke(), CsvHelper.CsvWriter.GetWriteRecordAction(), System.Exception.InnerException, and CsvHelper.CsvWriter.NextRecord().