Terraria Decompiled: CsvHelper.CsvWriter.CreatePropertyExpression
CreatePropertyExpression()
virtual Expression CsvHelper.CsvWriter.CreatePropertyExpression (Expression recordExpression, CsvClassMap mapping, CsvPropertyMap propertyMap) inline protected virtual
Definition at line 365 of file CsvWriter.cs.
        {
            if (Enumerable.Any<CsvPropertyMap>(mapping.PropertyMaps, (CsvPropertyMap pm) => pm == propertyMap))
            {
                return Expression.Property(recordExpression, propertyMap.Data.Property);
            }
            foreach (CsvPropertyReferenceMap csvPropertyReferenceMap in mapping.ReferenceMaps)
            {
                MemberExpression memberExpression = Expression.Property(recordExpression, csvPropertyReferenceMap.Data.Property);
                Expression expression = this.CreatePropertyExpression(memberExpression, csvPropertyReferenceMap.Data.Mapping, propertyMap);
                if (expression != null)
                {
                    if (csvPropertyReferenceMap.Data.Property.PropertyType.GetTypeInfo().IsValueType)
                    {
                        return expression;
                    }
                    BinaryExpression binaryExpression = Expression.Equal(memberExpression, Expression.Constant(null));
                    bool isValueType = propertyMap.Data.Property.PropertyType.GetTypeInfo().IsValueType;
                    bool flag = isValueType && propertyMap.Data.Property.PropertyType.GetTypeInfo().IsGenericType;
                    Type type;
                    if (isValueType && !flag && !this.configuration.UseNewObjectForNullReferenceProperties)
                    {
                        type = typeof(Nullable).MakeGenericType(new Type[] { propertyMap.Data.Property.PropertyType });
                        expression = Expression.Convert(expression, type);
                    }
                    else
                    {
                        type = propertyMap.Data.Property.PropertyType;
                    }
                    Expression expression2 = ((isValueType && !flag) ? Expression.New(type) : Expression.Constant(null, type));
                    return Expression.Condition(binaryExpression, expression2, expression);
                }
            }
            return null;
        }
References CsvHelper.CsvWriter.configuration, CsvHelper.CsvWriter.CreatePropertyExpression(), CsvHelper.Configuration.CsvPropertyMap.Data, CsvHelper.Configuration.CsvPropertyReferenceMap.Data, System.Type.GetTypeInfo(), System.Type.MakeGenericType(), CsvHelper.Configuration.CsvPropertyReferenceMapData.Mapping, CsvHelper.Configuration.CsvPropertyMapData.Property, CsvHelper.Configuration.CsvPropertyReferenceMapData.Property, CsvHelper.Configuration.CsvClassMap< T >.PropertyMaps, System.Reflection.PropertyInfo.PropertyType, and CsvHelper.Configuration.CsvConfiguration.UseNewObjectForNullReferenceProperties.
Referenced by CsvHelper.CsvWriter.CreateActionForObject(), and CsvHelper.CsvWriter.CreatePropertyExpression().