Terraria Decompiled: CsvHelper.CsvWriter.WriteHeader
WriteHeader()
virtual void CsvHelper.CsvWriter.WriteHeader (Type type) inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 203 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }
            if (!this.configuration.HasHeaderRecord)
            {
                throw new CsvWriterException("Configuration.HasHeaderRecord is false. This will need to be enabled to write the header.");
            }
            if (this.hasHeaderBeenWritten)
            {
                throw new CsvWriterException("The header record has already been written. You can't write it more than once.");
            }
            if (this.hasRecordBeenWritten)
            {
                throw new CsvWriterException("Records have already been written. You can't write the header after writing records has started.");
            }
            if (type == typeof(object))
            {
                return;
            }
            if (this.configuration.Maps[type] == null)
            {
                this.configuration.Maps.Add(this.configuration.AutoMap(type));
            }
            CsvPropertyMapCollection csvPropertyMapCollection = new CsvPropertyMapCollection();
            this.AddProperties(csvPropertyMapCollection, this.configuration.Maps[type]);
            foreach (CsvPropertyMap csvPropertyMap in csvPropertyMapCollection)
            {
                if (this.CanWrite(csvPropertyMap))
                {
                    this.WriteField(Enumerable.FirstOrDefault<string>(csvPropertyMap.Data.Names));
                }
            }
            this.NextRecord();
            this.hasHeaderBeenWritten = true;
        }
References CsvHelper.Configuration.CsvClassMapCollection.Add(), CsvHelper.CsvWriter.AddProperties(), CsvHelper.Configuration.CsvConfiguration.AutoMap(), CsvHelper.CsvWriter.CanWrite(), CsvHelper.CsvWriter.CheckDisposed(), CsvHelper.CsvWriter.configuration, CsvHelper.Configuration.CsvPropertyMap.Data, CsvHelper.CsvWriter.hasHeaderBeenWritten, CsvHelper.Configuration.CsvConfiguration.HasHeaderRecord, CsvHelper.CsvWriter.hasRecordBeenWritten, CsvHelper.Configuration.CsvConfiguration.Maps, CsvHelper.Configuration.CsvPropertyMapData.Names, CsvHelper.CsvWriter.NextRecord(), and CsvHelper.CsvWriter.WriteField().
Referenced by CsvHelper.CsvWriter.WriteHeader< T >(), and CsvHelper.CsvWriter.WriteRecords().