Terraria Decompiled: CsvHelper.CsvWriter.WriteField
WriteField() [1/4]
virtual void CsvHelper.CsvWriter.WriteField (string field) inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 70 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            bool flag = this.configuration.QuoteAllFields;
            if (this.configuration.TrimFields)
            {
                field = field.Trim();
            }
            if (!this.configuration.QuoteNoFields && !string.IsNullOrEmpty(field))
            {
                bool flag2 = field.Contains(this.configuration.QuoteString);
                if (flag || flag2 || field.get_Chars(0) == ' ' || field.get_Chars(field.Length - 1) == ' ' || field.IndexOfAny(this.configuration.QuoteRequiredChars) > -1 || (this.configuration.Delimiter.Length > 1 && field.Contains(this.configuration.Delimiter)))
                {
                    flag = true;
                }
            }
            this.WriteField(field, flag);
        }
References CsvHelper.CsvWriter.CheckDisposed(), CsvHelper.CsvWriter.configuration, CsvHelper.Configuration.CsvConfiguration.QuoteAllFields, CsvHelper.Configuration.CsvConfiguration.QuoteNoFields, CsvHelper.Configuration.CsvConfiguration.QuoteString, CsvHelper.Configuration.CsvConfiguration.TrimFields, and CsvHelper.CsvWriter.WriteField().
Referenced by CsvHelper.CsvWriter.WriteExcelSeparator(), CsvHelper.CsvWriter.WriteField(), CsvHelper.CsvWriter.WriteField(), CsvHelper.CsvWriter.WriteField(), CsvHelper.CsvWriter.WriteField< T >(), CsvHelper.CsvWriter.WriteField< T >(), and CsvHelper.CsvWriter.WriteHeader().