Terraria Decompiled: CsvHelper.CsvWriter.WriteRecords
WriteRecords()
virtual void CsvHelper.CsvWriter.WriteRecords (IEnumerable records) inline virtual
Definition at line 286 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            Type type = null;
            try
            {
                if (this.configuration.HasExcelSeparator && !this.hasExcelSeperatorBeenRead)
                {
                    this.WriteExcelSeparator();
                    this.hasExcelSeperatorBeenRead = true;
                }
                Type type2 = Enumerable.FirstOrDefault<Type>(records.GetType().GetInterfaces(), (Type t) => t.GetTypeInfo().IsGenericType && t.GetGenericTypeDefinition() == typeof(IEnumerable));
                if (type2 != null)
                {
                    type = Enumerable.Single<Type>(type2.GetGenericArguments());
                    bool isPrimitive = type.GetTypeInfo().IsPrimitive;
                    if (this.configuration.HasHeaderRecord && !this.hasHeaderBeenWritten && !isPrimitive)
                    {
                        this.WriteHeader(type);
                    }
                }
                foreach (object obj in records)
                {
                    type = obj.GetType();
                    bool isPrimitive2 = type.GetTypeInfo().IsPrimitive;
                    if (this.configuration.HasHeaderRecord && !this.hasHeaderBeenWritten && !isPrimitive2)
                    {
                        this.WriteHeader(type);
                    }
                    try
                    {
                        this.GetWriteRecordAction(obj.GetType()).DynamicInvoke(new object[] { obj });
                    }
                    catch (TargetInvocationException ex)
                    {
                        throw ex.InnerException;
                    }
                    this.NextRecord();
                }
            }
            catch (Exception ex2)
            {
                ExceptionHelper.AddExceptionDataMessage(ex2, null, type, null, default(int?), null);
                throw;
            }
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvWriter.CheckDisposed(), CsvHelper.CsvWriter.configuration, System.Delegate.DynamicInvoke(), System.Type.GetGenericArguments(), System.Type.GetType(), System.Type.GetTypeInfo(), CsvHelper.CsvWriter.GetWriteRecordAction(), CsvHelper.Configuration.CsvConfiguration.HasExcelSeparator, CsvHelper.Configuration.CsvConfiguration.HasHeaderRecord, System.Exception.InnerException, CsvHelper.CsvWriter.NextRecord(), System.obj, CsvHelper.CsvWriter.WriteExcelSeparator(), and CsvHelper.CsvWriter.WriteHeader().