Terraria Decompiled: CsvHelper.CsvWriter.WriteRecord< T >
WriteRecord< T >()
virtual void CsvHelper.CsvWriter.WriteRecord< T > (T record) inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 244 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            try
            {
                this.GetWriteRecordAction<T>().Invoke(record);
                this.hasRecordBeenWritten = true;
                this.NextRecord();
            }
            catch (Exception ex)
            {
                ExceptionHelper.AddExceptionDataMessage(ex, null, record.GetType(), null, default(int?), null);
                throw;
            }
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), CsvHelper.CsvWriter.CheckDisposed(), CsvHelper.CsvWriter.GetWriteRecordAction< T >(), and CsvHelper.CsvWriter.NextRecord().