Terraria Decompiled: CsvHelper.CsvWriter.WriteField
WriteField() [3/4]
virtual void CsvHelper.CsvWriter.WriteField (Type type, object field) inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 145 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            if (type == typeof(string))
            {
                this.WriteField(field as string);
                return;
            }
            ITypeConverter converter = TypeConverterFactory.GetConverter(type);
            this.WriteField(type, field, converter);
        }
References CsvHelper.CsvWriter.CheckDisposed(), System.converter, CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), and CsvHelper.CsvWriter.WriteField().