Terraria Decompiled: CsvHelper.CsvWriter.CreateWriteRecordAction
CreateWriteRecordAction()
virtual void CsvHelper.CsvWriter.CreateWriteRecordAction (Type type) inline protected virtual
Definition at line 448 of file CsvWriter.cs.
        {
            if (this.typeActions.ContainsKey(type))
            {
                return;
            }
            if (this.configuration.Maps[type] == null)
            {
                this.configuration.Maps.Add(this.configuration.AutoMap(type));
            }
            if (type.GetTypeInfo().IsPrimitive)
            {
                this.CreateActionForPrimitive(type);
                return;
            }
            this.CreateActionForObject(type);
        }
References CsvHelper.Configuration.CsvClassMapCollection.Add(), CsvHelper.Configuration.CsvConfiguration.AutoMap(), CsvHelper.CsvWriter.configuration, System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), CsvHelper.CsvWriter.CreateActionForObject(), CsvHelper.CsvWriter.CreateActionForPrimitive(), System.Type.GetTypeInfo(), CsvHelper.Configuration.CsvConfiguration.Maps, and CsvHelper.CsvWriter.typeActions.
Referenced by CsvHelper.CsvWriter.GetWriteRecordAction(), and CsvHelper.CsvWriter.GetWriteRecordAction< T >().