Terraria Decompiled: CsvHelper.CsvWriter.NextRecord
NextRecord()
virtual void CsvHelper.CsvWriter.NextRecord () inline virtual
Implements CsvHelper.ICsvWriter.
Definition at line 172 of file CsvWriter.cs.
        {
            this.CheckDisposed();
            this.serializer.Write(this.currentRecord.ToArray());
            this.currentRecord.Clear();
        }
References CsvHelper.CsvWriter.CheckDisposed(), System.Collections.Generic.List< T >.Clear(), CsvHelper.CsvWriter.currentRecord, CsvHelper.CsvWriter.serializer, System.Collections.Generic.List< T >.ToArray(), and CsvHelper.ICsvSerializer.Write().
Referenced by CsvHelper.CsvWriter.WriteExcelSeparator(), CsvHelper.CsvWriter.WriteHeader(), CsvHelper.CsvWriter.WriteRecord(), CsvHelper.CsvWriter.WriteRecord< T >(), and CsvHelper.CsvWriter.WriteRecords().