Terraria Decompiled: CsvHelper.CsvWriter.CreateActionForObject
CreateActionForObject()
virtual void CsvHelper.CsvWriter.CreateActionForObject (Type type) inline protected virtual
Definition at line 467 of file CsvWriter.cs.
        {
            ParameterExpression parameterExpression = Expression.Parameter(type, "record");
            CsvPropertyMapCollection csvPropertyMapCollection = new CsvPropertyMapCollection();
            this.AddProperties(csvPropertyMapCollection, this.configuration.Maps[type]);
            if (csvPropertyMapCollection.Count == 0)
            {
                throw new CsvWriterException(string.Format("No properties are mapped for type '{0}'.", type.FullName));
            }
            List<Delegate> list = new List<Delegate>();
            foreach (CsvPropertyMap csvPropertyMap in csvPropertyMapCollection)
            {
                if (this.CanWrite(csvPropertyMap) && csvPropertyMap.Data.TypeConverter != null && csvPropertyMap.Data.TypeConverter.CanConvertTo(typeof(string)))
                {
                    Expression expression = this.CreatePropertyExpression(parameterExpression, this.configuration.Maps[type], csvPropertyMap);
                    ConstantExpression constantExpression = Expression.Constant(csvPropertyMap.Data.TypeConverter);
                    if (csvPropertyMap.Data.TypeConverterOptions.CultureInfo == null)
                    {
                        csvPropertyMap.Data.TypeConverterOptions.CultureInfo = this.configuration.CultureInfo;
                    }
                    ConstantExpression constantExpression2 = Expression.Constant(TypeConverterOptions.Merge(new TypeConverterOptions[]
                    {
                        TypeConverterOptionsFactory.GetOptions(csvPropertyMap.Data.Property.PropertyType),
                        csvPropertyMap.Data.TypeConverterOptions
                    }));
                    MethodInfo method = csvPropertyMap.Data.TypeConverter.GetType().GetMethod("ConvertToString");
                    expression = Expression.Convert(expression, typeof(object));
                    expression = Expression.Call(constantExpression, method, constantExpression2, expression);
                    if (type.GetTypeInfo().IsClass)
                    {
                        expression = Expression.Condition(Expression.Equal(parameterExpression, Expression.Constant(null)), Expression.Constant(string.Empty), expression);
                    }
                    MethodCallExpression methodCallExpression = Expression.Call(Expression.Constant(this), "WriteField", new Type[] { typeof(string) }, new Expression[] { expression });
                    Type type2 = typeof(Action).MakeGenericType(new Type[] { type });
                    list.Add(Expression.Lambda(type2, methodCallExpression, new ParameterExpression[] { parameterExpression }).Compile());
                }
            }
            this.typeActions[type] = this.CombineDelegates(list);
        }
References CsvHelper.CsvWriter.AddProperties(), CsvHelper.TypeConversion.ITypeConverter.CanConvertTo(), CsvHelper.CsvWriter.CanWrite(), CsvHelper.CsvWriter.CombineDelegates(), CsvHelper.CsvWriter.configuration, CsvHelper.Configuration.CsvPropertyMapCollection.Count, CsvHelper.CsvWriter.CreatePropertyExpression(), CsvHelper.Configuration.CsvConfiguration.CultureInfo, CsvHelper.TypeConversion.TypeConverterOptions.CultureInfo, CsvHelper.Configuration.CsvPropertyMap.Data, System.Format, System.Type.FullName, System.list, System.Type.MakeGenericType(), CsvHelper.Configuration.CsvConfiguration.Maps, CsvHelper.TypeConversion.TypeConverterOptions.Merge(), CsvHelper.CsvWriter.typeActions, CsvHelper.Configuration.CsvPropertyMapData.TypeConverter, and CsvHelper.Configuration.CsvPropertyMapData.TypeConverterOptions.
Referenced by CsvHelper.CsvWriter.CreateWriteRecordAction().