Terraria Decompiled: CsvHelper.CsvWriter.CreateActionForPrimitive
CreateActionForPrimitive()
virtual void CsvHelper.CsvWriter.CreateActionForPrimitive (Type type) inline protected virtual
Definition at line 508 of file CsvWriter.cs.
        {
            ParameterExpression parameterExpression = Expression.Parameter(type, "record");
            Expression expression = Expression.Convert(parameterExpression, typeof(object));
            ITypeConverter converter = TypeConverterFactory.GetConverter(type);
            ConstantExpression constantExpression = Expression.Constant(converter);
            MethodInfo method = converter.GetType().GetMethod("ConvertToString");
            TypeConverterOptions options = TypeConverterOptionsFactory.GetOptions(type);
            if (options.CultureInfo == null)
            {
                options.CultureInfo = this.configuration.CultureInfo;
            }
            expression = Expression.Call(constantExpression, method, Expression.Constant(options), expression);
            expression = Expression.Call(Expression.Constant(this), "WriteField", new Type[] { typeof(string) }, new Expression[] { expression });
            Type type2 = typeof(Action).MakeGenericType(new Type[] { type });
            this.typeActions[type] = Expression.Lambda(type2, expression, new ParameterExpression[] { parameterExpression }).Compile();
        }
References CsvHelper.CsvWriter.configuration, System.converter, CsvHelper.Configuration.CsvConfiguration.CultureInfo, CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), System.Type.GetMethod(), CsvHelper.TypeConversion.TypeConverterOptionsFactory.GetOptions(), System.Reflection.MethodInfo.GetType(), System.Type.MakeGenericType(), System.options, and CsvHelper.CsvWriter.typeActions.
Referenced by CsvHelper.CsvWriter.CreateWriteRecordAction().