Terraria Decompiled: Terraria.DataStructures.RichRoomCheckFeedback.EndSpread
EndSpread()
void Terraria.DataStructures.RichRoomCheckFeedback.EndSpread () inline
Implements Terraria.DataStructures.IRoomCheckFeedback_Spread.
Definition at line 134 of file RichRoomCheckFeedback.cs.
        {
            Vector2 vector = new Vector2((float)this._originX, (float)this._originY);
            for (int i = 0; i < this._spaceCount; i++)
            {
                RichRoomCheckFeedback.ParticlePreparation particlePreparation = this._space[i];
                for (int j = 0; j < this._spaceCount; j++)
                {
                    RichRoomCheckFeedback.ParticlePreparation particlePreparation2 = this._space[j];
                    if (particlePreparation.x == particlePreparation2.x && particlePreparation.y == particlePreparation2.y && particlePreparation.type == RichRoomCheckFeedback.Reason.Good && particlePreparation2.type != RichRoomCheckFeedback.Reason.Good)
                    {
                        particlePreparation.consumed = true;
                    }
                }
                this._space[i] = particlePreparation;
            }
            float highestDistanceFromOrigin = this.GetHighestDistanceFromOrigin(ref vector);
            float num = 3f * highestDistanceFromOrigin + 60f;
            for (int k = 0; k < this._spaceCount; k++)
            {
                RichRoomCheckFeedback.ParticlePreparation particlePreparation3 = this._space[k];
                if (!particlePreparation3.consumed)
                {
                    ushort type = Main.tile[particlePreparation3.x, particlePreparation3.y].type;
                    bool flag = TileID.Sets.RoomNeeds.CountsAsTable[(int)type] || TileID.Sets.RoomNeeds.CountsAsChair[(int)type] || TileID.Sets.RoomNeeds.CountsAsTorch[(int)type] || TileID.Sets.RoomNeeds.CountsAsDoor[(int)type];
                    Asset<Texture2D> asset = TextureAssets.Extra[293];
                    Color color = Color.Cyan * 0.7f;
                    color.A /= 2;
                    Vector2 vector2 = new Vector2((float)particlePreparation3.x, (float)particlePreparation3.y);
                    float num2 = 1f;
                    switch (particlePreparation3.type)
                    {
                    case RichRoomCheckFeedback.Reason.BlockedWall:
                        asset = TextureAssets.Extra[292];
                        color = new Color(80, 255, 255) * 0.7f;
                        color.A /= 2;
                        goto IL_031D;
                    case RichRoomCheckFeedback.Reason.UnsafeWall:
                        asset = TextureAssets.Extra[298];
                        color = new Color(255, 40, 40, 255);
                        goto IL_023C;
                    case RichRoomCheckFeedback.Reason.OpenAir:
                    case RichRoomCheckFeedback.Reason.Hazard:
                        asset = TextureAssets.Extra[292];
                        color = new Color(255, 40, 40, 255);
                        goto IL_023C;
                    }
                    num2 = 1.5f;
                    if (flag)
                    {
                        goto IL_031D;
                    }
                    IL_023C:
                    RoomCheckParticle roomCheckParticle = RichRoomCheckFeedback._particlePool.RequestParticle();
                    roomCheckParticle.SetBasicInfo(asset, null, Vector2.Zero, new Vector2((float)(particlePreparation3.x * 16 + 8), (float)(particlePreparation3.y * 16 + 8)));
                    roomCheckParticle.Delay = (int)(3f * Vector2.Distance(vector, vector2));
                    float num3 = num - (float)roomCheckParticle.Delay;
                    roomCheckParticle.SetTypeInfo(num3 * num2, true);
                    roomCheckParticle.FadeInNormalizedTime = Utils.Remap(num - 24f, (float)roomCheckParticle.Delay, num, 0f, 1f, true);
                    roomCheckParticle.FadeOutNormalizedTime = Utils.Remap(num - 6f, (float)roomCheckParticle.Delay, num, 0f, 1f, true);
                    roomCheckParticle.ColorTint = color;
                    roomCheckParticle.Scale = Vector2.One;
                    Main.ParticleSystem_World_OverPlayers.Add(roomCheckParticle);
                }
                IL_031D:;
            }
            for (int l = 0; l < this._spaceCount; l++)
            {
                RichRoomCheckFeedback.ParticlePreparation particlePreparation4 = this._space[l];
                if (!particlePreparation4.consumed)
                {
                    ushort type2 = Main.tile[particlePreparation4.x, particlePreparation4.y].type;
                    if (TileID.Sets.RoomNeeds.CountsAsTable[(int)type2] || TileID.Sets.RoomNeeds.CountsAsChair[(int)type2] || TileID.Sets.RoomNeeds.CountsAsTorch[(int)type2] || TileID.Sets.RoomNeeds.CountsAsDoor[(int)type2])
                    {
                        Rectangle rectangle;
                        TileObjectData.TryGetTileBounds(particlePreparation4.x, particlePreparation4.y, out rectangle);
                        for (int m = 0; m < this._spaceCount; m++)
{
                            if (m != l)
{
                                RichRoomCheckFeedback.ParticlePreparation particlePreparation5 = this._space[m];
                                if (particlePreparation5.x >= rectangle.Left && particlePreparation5.x < rectangle.Right && particlePreparation5.y >= rectangle.Top && particlePreparation5.y < rectangle.Bottom)
{
                                    this._space[m].consumed = true;
                                }
                            }
                        }
                    }
                }
            }
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            for (int n = 0; n < this._spaceCount; n++)
            {
                RichRoomCheckFeedback.ParticlePreparation particlePreparation6 = this._space[n];
                if (!particlePreparation6.consumed)
                {
                    ushort type3 = Main.tile[particlePreparation6.x, particlePreparation6.y].type;
                    bool flag6 = TileID.Sets.RoomNeeds.CountsAsTable[(int)type3];
                    bool flag7 = TileID.Sets.RoomNeeds.CountsAsChair[(int)type3];
                    bool flag8 = TileID.Sets.RoomNeeds.CountsAsTorch[(int)type3];
                    bool flag9 = TileID.Sets.RoomNeeds.CountsAsDoor[(int)type3];
                    if (flag6 || flag7 || flag9 || flag8)
                    {
                        Asset<Texture2D> asset2 = TextureAssets.Extra[293];
                        if (flag6)
{
                            if (flag3)
{
                                goto IL_0711;
                            }
                            flag3 = true;
                            asset2 = TextureAssets.Extra[297];
                        }
                        if (flag7)
{
                            if (flag2)
{
                                goto IL_0711;
                            }
                            flag2 = true;
                            asset2 = TextureAssets.Extra[295];
                        }
                        if (flag9)
{
                            if (flag5)
{
                                goto IL_0711;
                            }
                            flag5 = true;
                            asset2 = TextureAssets.Extra[296];
                        }
                        if (flag8)
{
                            if (flag4)
{
                                goto IL_0711;
                            }
                            flag4 = true;
                            asset2 = TextureAssets.Extra[294];
                        }
                        Rectangle rectangle2;
                        TileObjectData.TryGetTileBounds(particlePreparation6.x, particlePreparation6.y, out rectangle2);
                        Color color2;
                        (Color.LimeGreen * 0.8f).A = color2.A / 2;
                        Vector2 vector3 = new Vector2((float)particlePreparation6.x, (float)particlePreparation6.y);
                        RoomCheckParticle roomCheckParticle2 = RichRoomCheckFeedback._particlePool.RequestParticle();
                        Vector2 vector4 = new Vector2((float)(rectangle2.Left + rectangle2.Right) / 2f, MathHelper.Min((float)rectangle2.Top / 2f + (float)rectangle2.Bottom / 2f, (float)(rectangle2.Top + 1)));
                        roomCheckParticle2.SetBasicInfo(asset2, null, Vector2.Zero, vector4 * 16f + new Vector2(0f, (float)(-(float)asset2.Height() / 2)));
                        roomCheckParticle2.Delay = (int)(3f * Vector2.Distance(vector, vector3));
                        float num4 = num - (float)roomCheckParticle2.Delay;
                        roomCheckParticle2.SetTypeInfo(num4, true);
                        roomCheckParticle2.FadeInNormalizedTime = Utils.Remap(num - 24f, (float)roomCheckParticle2.Delay, num, 0f, 1f, true);
                        roomCheckParticle2.FadeOutNormalizedTime = Utils.Remap(num - 6f, (float)roomCheckParticle2.Delay, num, 0f, 1f, true);
                        roomCheckParticle2.Scale = Vector2.One;
                        int num5 = 32;
                        RoomCheckParticle roomCheckParticle3 = roomCheckParticle2;
                        roomCheckParticle3.LocalPosition.Y = roomCheckParticle3.LocalPosition.Y - (float)num5;
                        roomCheckParticle2.Velocity = new Vector2(0f, (float)num5 * 2.5f) / num4;
                        roomCheckParticle2.AccelerationPerFrame = -roomCheckParticle2.Velocity * 1.25f / num4;
                        Main.ParticleSystem_World_OverPlayers.Add(roomCheckParticle2);
                    }
                }
                IL_0711:;
            }
        }
References Terraria.DataStructures.RichRoomCheckFeedback._originX, Terraria.DataStructures.RichRoomCheckFeedback._originY, Terraria.DataStructures.RichRoomCheckFeedback._particlePool, Terraria.DataStructures.RichRoomCheckFeedback._space, Terraria.DataStructures.RichRoomCheckFeedback._spaceCount, Microsoft.Xna.Framework.Color.A, System.A, Terraria.Graphics.Renderers.ParticleRenderer.Add(), Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Graphics.Color, Terraria.DataStructures.RichRoomCheckFeedback.ParticlePreparation.consumed, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsChair, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsDoor, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsTable, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsTorch, Terraria.Graphics.Renderers.FadingParticle.Delay, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.GameContent.TextureAssets.Extra, Terraria.DataStructures.RichRoomCheckFeedback.GetHighestDistanceFromOrigin(), int, Microsoft.Xna.Framework.Rectangle.Left, Microsoft.Xna.Framework.MathHelper.Min(), Microsoft.Xna.Framework.Vector2.One, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Utils.Remap(), Terraria.Graphics.Renderers.ParticlePool< T >.RequestParticle(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Graphics.Renderers.ABasicParticle.SetBasicInfo(), Terraria.Graphics.Renderers.FadingParticle.SetTypeInfo(), Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Terraria.ObjectData.TileObjectData.TryGetTileBounds(), Terraria.DataStructures.RichRoomCheckFeedback.ParticlePreparation.type, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.DataStructures.RichRoomCheckFeedback.ParticlePreparation.x, Terraria.DataStructures.RichRoomCheckFeedback.ParticlePreparation.y, and Microsoft.Xna.Framework.Vector2.Zero.