Terraria Decompiled: System.Threading.Tasks.Parallel.Invoke
Invoke() [1/2]
static void System.Threading.Tasks.Parallel.Invoke (ParallelOptions parallelOptions, params Action[] actions) inline static
Definition at line 20 of file Parallel.cs.
        {
            if (actions == null)
            {
                throw new ArgumentNullException("actions");
            }
            if (parallelOptions == null)
            {
                throw new ArgumentNullException("parallelOptions");
            }
            parallelOptions.CancellationToken.ThrowIfCancellationRequested();
            Action[] actionsCopy = new Action[actions.Length];
            for (int i = 0; i < actionsCopy.Length; i++)
            {
                actionsCopy[i] = actions[i];
                if (actionsCopy[i] == null)
                {
                    throw new ArgumentException("One of the actions was null.");
                }
            }
            int num = 0;
            if (ParallelEtwProvider.Log.IsEnabled())
            {
                num = Interlocked.Increment(ref Parallel.s_forkJoinContextID);
                ParallelEtwProvider.Log.ParallelInvokeBegin(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), num, ParallelEtwProvider.ForkJoinOperationType.ParallelInvoke, actionsCopy.Length);
            }
            if (actionsCopy.Length < 1)
            {
                return;
            }
            try
            {
                if (actionsCopy.Length > 10 || (parallelOptions.MaxDegreeOfParallelism != -1 && parallelOptions.MaxDegreeOfParallelism < actionsCopy.Length))
                {
                    ConcurrentQueue<Exception> exceptionQ = null;
                    int actionIndex = 0;
                    try
                    {
                        TaskReplicator.Run<object>(delegate(ref object state, int timeout, out bool replicationDelegateYieldedBeforeCompletion)
{
                            replicationDelegateYieldedBeforeCompletion = false;
                            for (int k = Interlocked.Increment(ref actionIndex); k <= actionsCopy.Length; k = Interlocked.Increment(ref actionIndex))
{
                                try
{
                                    actionsCopy[k - 1]();
                                }
                                catch (Exception ex5)
{
                                    LazyInitializer.EnsureInitialized<ConcurrentQueue<Exception>>(ref exceptionQ, () => new ConcurrentQueue<Exception>());
                                    exceptionQ.Enqueue(ex5);
                                }
                                parallelOptions.CancellationToken.ThrowIfCancellationRequested();
                            }
                        }, parallelOptions, false);
                    }
                    catch (Exception ex)
                    {
                        LazyInitializer.EnsureInitialized<ConcurrentQueue<Exception>>(ref exceptionQ, () => new ConcurrentQueue<Exception>());
                        if (ex is ObjectDisposedException)
{
                            throw;
                        }
                        AggregateException ex2 = ex as AggregateException;
                        if (ex2 != null)
{
                            using (IEnumerator<Exception> enumerator = ex2.InnerExceptions.GetEnumerator())
{
                                while (enumerator.MoveNext())
{
                                    Exception ex3 = enumerator.Current;
                                    exceptionQ.Enqueue(ex3);
                                }
                                goto IL_01C3;
                            }
                        }
                        exceptionQ.Enqueue(ex);
                        IL_01C3:;
                    }
                    if (exceptionQ != null && exceptionQ.Count > 0)
                    {
                        Parallel.ThrowSingleCancellationExceptionOrOtherException(exceptionQ, parallelOptions.CancellationToken, new AggregateException(exceptionQ));
                    }
                }
                else
                {
                    Task[] array = new Task[actionsCopy.Length];
                    parallelOptions.CancellationToken.ThrowIfCancellationRequested();
                    for (int j = 1; j < array.Length; j++)
                    {
                        array[j] = Task.Factory.StartNew(actionsCopy[j], parallelOptions.CancellationToken, TaskCreationOptions.None, parallelOptions.EffectiveTaskScheduler);
                    }
                    array[0] = new Task(actionsCopy[0], parallelOptions.CancellationToken, TaskCreationOptions.None);
                    array[0].RunSynchronously(parallelOptions.EffectiveTaskScheduler);
                    try
                    {
                        Task.WaitAll(array);
                    }
                    catch (AggregateException ex4)
                    {
                        Parallel.ThrowSingleCancellationExceptionOrOtherException(ex4.InnerExceptions, parallelOptions.CancellationToken, ex4);
                    }
                }
            }
            finally
            {
                if (ParallelEtwProvider.Log.IsEnabled())
                {
                    ParallelEtwProvider.Log.ParallelInvokeEnd(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), num);
                }
            }
        }
References System.array, System.Threading.Tasks.ParallelOptions.CancellationToken, System.Collections.Concurrent.ConcurrentQueue< T >.Count, System.Collections.Generic.IEnumerator< out T >.Current, System.Threading.Tasks.TaskScheduler.Current, System.Threading.Tasks.Task< TResult >.CurrentId, System.Threading.Tasks.ParallelOptions.EffectiveTaskScheduler, System.Collections.Concurrent.ConcurrentQueue< T >.Enqueue(), System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Tasks.TaskScheduler.Id, System.Threading.Interlocked.Increment(), System.AggregateException.InnerExceptions, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Threading.Tasks.ParallelEtwProvider.Log, System.Threading.Tasks.ParallelOptions.MaxDegreeOfParallelism, System.Collections.IEnumerator.MoveNext(), System.Threading.CancellationToken.None, System.Threading.Tasks.ParallelEtwProvider.ParallelInvokeBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelInvokeEnd(), System.Threading.Tasks.Parallel.s_forkJoinContextID, System.Threading.Tasks.TaskFactory< TResult >.StartNew(), System.state, System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(), and System.Threading.Tasks.Task< TResult >.WaitAll().