Terraria Decompiled: System.Threading.Tasks.Parallel.ForWorker64< TLocal >
ForWorker64< TLocal >()
static ParallelLoopResult System.Threading.Tasks.Parallel.ForWorker64< TLocal > (long fromInclusive, long toExclusive, ParallelOptions parallelOptions, Action< long > body, Action< long, ParallelLoopState > bodyWithState, Func< long, ParallelLoopState, TLocal, TLocal > bodyWithLocal, Func< TLocal > localInit, Action< TLocal > localFinally) inline static private
Definition at line 498 of file Parallel.cs.
        {
            ParallelLoopResult parallelLoopResult = default(ParallelLoopResult);
            if (toExclusive <= fromInclusive)
            {
                parallelLoopResult._completed = true;
                return parallelLoopResult;
            }
            ParallelLoopStateFlags64 sharedPStateFlags = new ParallelLoopStateFlags64();
            parallelOptions.CancellationToken.ThrowIfCancellationRequested();
            int num = ((parallelOptions.EffectiveMaxConcurrencyLevel == -1) ? PlatformHelper.ProcessorCount : parallelOptions.EffectiveMaxConcurrencyLevel);
            RangeManager rangeManager = new RangeManager(fromInclusive, toExclusive, 1L, num);
            OperationCanceledException oce = null;
            CancellationTokenRegistration cancellationTokenRegistration = ((!parallelOptions.CancellationToken.CanBeCanceled) ? default(CancellationTokenRegistration) : parallelOptions.CancellationToken.Register(delegate(object o)
            {
                oce = new OperationCanceledException(parallelOptions.CancellationToken);
                sharedPStateFlags.Cancel();
            }, null, false));
            int forkJoinContextID = 0;
            if (ParallelEtwProvider.Log.IsEnabled())
            {
                forkJoinContextID = Interlocked.Increment(ref Parallel.s_forkJoinContextID);
                ParallelEtwProvider.Log.ParallelLoopBegin(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID, ParallelEtwProvider.ForkJoinOperationType.ParallelFor, fromInclusive, toExclusive);
            }
            try
            {
                try
                {
                    TaskReplicator.Run<RangeWorker>(delegate(ref RangeWorker currentWorker, int timeout, out bool replicationDelegateYieldedBeforeCompletion)
                    {
                        if (!currentWorker.IsInitialized)
{
                            currentWorker = rangeManager.RegisterNewWorker();
                        }
                        replicationDelegateYieldedBeforeCompletion = false;
                        long num3;
                        long num4;
                        if (!currentWorker.FindNewWork(out num3, out num4) || sharedPStateFlags.ShouldExitLoop(num3))
{
                            return;
                        }
                        if (ParallelEtwProvider.Log.IsEnabled())
{
                            ParallelEtwProvider.Log.ParallelFork(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID);
                        }
                        TLocal tlocal = default(TLocal);
                        bool flag = false;
                        try
{
                            ParallelLoopState64 parallelLoopState = null;
                            if (bodyWithState != null)
{
                                parallelLoopState = new ParallelLoopState64(sharedPStateFlags);
                            }
                            else if (bodyWithLocal != null)
{
                                parallelLoopState = new ParallelLoopState64(sharedPStateFlags);
                                if (localInit != null)
{
                                    tlocal = localInit();
                                    flag = true;
                                }
                            }
                            int num5 = Parallel.ComputeTimeoutPoint(timeout);
                            for (;;)
{
                                if (body != null)
{
                                    for (long num6 = num3; num6 < num4; num6 += 1L)
{
                                        if (sharedPStateFlags.LoopStateFlags != 0 && sharedPStateFlags.ShouldExitLoop())
{
                                            break;
                                        }
                                        body(num6);
                                    }
                                }
                                else if (bodyWithState != null)
{
                                    for (long num7 = num3; num7 < num4; num7 += 1L)
{
                                        if (sharedPStateFlags.LoopStateFlags != 0 && sharedPStateFlags.ShouldExitLoop(num7))
{
                                            break;
                                        }
                                        parallelLoopState.CurrentIteration = num7;
                                        bodyWithState(num7, parallelLoopState);
                                    }
                                }
                                else
{
                                    long num8 = num3;
                                    while (num8 < num4 && (sharedPStateFlags.LoopStateFlags == 0 || !sharedPStateFlags.ShouldExitLoop(num8)))
{
                                        parallelLoopState.CurrentIteration = num8;
                                        tlocal = bodyWithLocal(num8, parallelLoopState, tlocal);
                                        num8 += 1L;
                                    }
                                }
                                if (Parallel.CheckTimeoutReached(num5))
{
                                    break;
                                }
                                if (!currentWorker.FindNewWork(out num3, out num4) || (sharedPStateFlags.LoopStateFlags != 0 && sharedPStateFlags.ShouldExitLoop(num3)))
{
                                    goto IL_01DB;
                                }
                            }
                            replicationDelegateYieldedBeforeCompletion = true;
                            IL_01DB:;
                        }
                        catch (Exception ex2)
{
                            sharedPStateFlags.SetExceptional();
                            ExceptionDispatchInfo.Throw(ex2);
                        }
                        finally
{
                            if (localFinally != null && flag)
{
                                localFinally(tlocal);
                            }
                            if (ParallelEtwProvider.Log.IsEnabled())
{
                                ParallelEtwProvider.Log.ParallelJoin(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID);
                            }
                        }
                    }, parallelOptions, true);
                }
                finally
                {
                    if (parallelOptions.CancellationToken.CanBeCanceled)
                    {
                        cancellationTokenRegistration.Dispose();
                    }
                }
                if (oce != null)
                {
                    throw oce;
                }
            }
            catch (AggregateException ex)
            {
                Parallel.ThrowSingleCancellationExceptionOrOtherException(ex.InnerExceptions, parallelOptions.CancellationToken, ex);
            }
            finally
            {
                int loopStateFlags = sharedPStateFlags.LoopStateFlags;
                parallelLoopResult._completed = loopStateFlags == 0;
                if ((loopStateFlags & 2) != 0)
                {
                    parallelLoopResult._lowestBreakIteration = new long?(sharedPStateFlags.LowestBreakIteration);
                }
                if (ParallelEtwProvider.Log.IsEnabled())
                {
                    long num2;
                    if (loopStateFlags == 0)
                    {
                        num2 = toExclusive - fromInclusive;
                    }
                    else if ((loopStateFlags & 2) != 0)
                    {
                        num2 = sharedPStateFlags.LowestBreakIteration - fromInclusive;
                    }
                    else
                    {
                        num2 = -1L;
                    }
                    ParallelEtwProvider.Log.ParallelLoopEnd(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID, num2);
                }
            }
            return parallelLoopResult;
        }
References System.Threading.CancellationToken.CanBeCanceled, System.Threading.Tasks.ParallelLoopStateFlags.Cancel(), System.Threading.Tasks.ParallelOptions.CancellationToken, System.Threading.Tasks.Parallel.CheckTimeoutReached(), System.Threading.Tasks.Parallel.ComputeTimeoutPoint(), System.Threading.Tasks.TaskScheduler.Current, System.Threading.Tasks.Task< TResult >.CurrentId, System.Threading.CancellationTokenRegistration.Dispose(), System.Threading.Tasks.ParallelOptions.EffectiveMaxConcurrencyLevel, System.Threading.Tasks.TaskScheduler.Id, System.Threading.Interlocked.Increment(), System.AggregateException.InnerExceptions, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.L, System.Threading.Tasks.ParallelEtwProvider.Log, System.Threading.Tasks.ParallelLoopStateFlags.LoopStateFlags, System.Threading.Tasks.ParallelLoopStateFlags64.LowestBreakIteration, System.Threading.Tasks.ParallelEtwProvider.ParallelFork(), System.Threading.Tasks.ParallelEtwProvider.ParallelJoin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopEnd(), System.Threading.PlatformHelper.ProcessorCount, System.Threading.CancellationToken.Register(), System.Threading.Tasks.RangeManager.RegisterNewWorker(), System.Threading.Tasks.Parallel.s_forkJoinContextID, System.Threading.Tasks.ParallelLoopStateFlags.SetExceptional(), System.Threading.Tasks.ParallelLoopStateFlags64.ShouldExitLoop(), System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), and System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException().