Terraria Decompiled: System.Threading.Tasks.Parallel.PartitionerForEachWorker< TSource, TLocal >
PartitionerForEachWorker< TSource, TLocal >()
static ParallelLoopResult System.Threading.Tasks.Parallel.PartitionerForEachWorker< TSource, TLocal > (Partitioner< TSource > source, ParallelOptions parallelOptions, Action< TSource > simpleBody, Action< TSource, ParallelLoopState > bodyWithState, Action< TSource, ParallelLoopState, long > bodyWithStateAndIndex, Func< TSource, ParallelLoopState, TLocal, TLocal > bodyWithStateAndLocal, Func< TSource, ParallelLoopState, long, TLocal, TLocal > bodyWithEverything, Func< TLocal > localInit, Action< TLocal > localFinally) inline static private
Definition at line 1154 of file Parallel.cs.
        {
            OrderablePartitioner<TSource> orderedSource = source as OrderablePartitioner<TSource>;
            if (!source.SupportsDynamicPartitions)
            {
                throw new InvalidOperationException("The Partitioner used here must support dynamic partitioning.");
            }
            parallelOptions.CancellationToken.ThrowIfCancellationRequested();
            int forkJoinContextID = 0;
            if (ParallelEtwProvider.Log.IsEnabled())
            {
                forkJoinContextID = Interlocked.Increment(ref Parallel.s_forkJoinContextID);
                ParallelEtwProvider.Log.ParallelLoopBegin(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID, ParallelEtwProvider.ForkJoinOperationType.ParallelForEach, 0L, 0L);
            }
            ParallelLoopStateFlags64 sharedPStateFlags = new ParallelLoopStateFlags64();
            ParallelLoopResult parallelLoopResult = default(ParallelLoopResult);
            OperationCanceledException oce = null;
            CancellationTokenRegistration cancellationTokenRegistration = ((!parallelOptions.CancellationToken.CanBeCanceled) ? default(CancellationTokenRegistration) : parallelOptions.CancellationToken.Register(delegate(object o)
            {
                oce = new OperationCanceledException(parallelOptions.CancellationToken);
                sharedPStateFlags.Cancel();
            }, null, false));
            IEnumerable<TSource> partitionerSource = null;
            IEnumerable<KeyValuePair<long, TSource>> orderablePartitionerSource = null;
            if (orderedSource != null)
            {
                orderablePartitionerSource = orderedSource.GetOrderableDynamicPartitions();
                if (orderablePartitionerSource == null)
                {
                    throw new InvalidOperationException("The Partitioner used here returned a null partitioner source.");
                }
            }
            else
            {
                partitionerSource = source.GetDynamicPartitions();
                if (partitionerSource == null)
                {
                    throw new InvalidOperationException("The Partitioner used here returned a null partitioner source.");
                }
            }
            try
            {
                try
                {
                    TaskReplicator.Run<IEnumerator>(delegate(ref IEnumerator partitionState, int timeout, out bool replicationDelegateYieldedBeforeCompletion)
                    {
                        replicationDelegateYieldedBeforeCompletion = false;
                        if (ParallelEtwProvider.Log.IsEnabled())
{
                            ParallelEtwProvider.Log.ParallelFork(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID);
                        }
                        TLocal tlocal = default(TLocal);
                        bool flag = false;
                        try
{
                            ParallelLoopState64 parallelLoopState = null;
                            if (bodyWithState != null || bodyWithStateAndIndex != null)
{
                                parallelLoopState = new ParallelLoopState64(sharedPStateFlags);
                            }
                            else if (bodyWithStateAndLocal != null || bodyWithEverything != null)
{
                                parallelLoopState = new ParallelLoopState64(sharedPStateFlags);
                                if (localInit != null)
{
                                    tlocal = localInit();
                                    flag = true;
                                }
                            }
                            int num = Parallel.ComputeTimeoutPoint(timeout);
                            if (orderedSource != null)
{
                                IEnumerator<KeyValuePair<long, TSource>> enumerator = partitionState as IEnumerator<KeyValuePair<long, TSource>>;
                                if (enumerator == null)
{
                                    enumerator = orderablePartitionerSource.GetEnumerator();
                                    partitionState = enumerator;
                                }
                                if (enumerator == null)
{
                                    throw new InvalidOperationException("The Partitioner source returned a null enumerator.");
                                }
                                while (enumerator.MoveNext())
{
                                    KeyValuePair<long, TSource> keyValuePair = enumerator.Current;
                                    long key = keyValuePair.Key;
                                    TSource value = keyValuePair.Value;
                                    if (parallelLoopState != null)
{
                                        parallelLoopState.CurrentIteration = key;
                                    }
                                    if (simpleBody != null)
{
                                        simpleBody(value);
                                    }
                                    else if (bodyWithState != null)
{
                                        bodyWithState(value, parallelLoopState);
                                    }
                                    else if (bodyWithStateAndIndex != null)
{
                                        bodyWithStateAndIndex(value, parallelLoopState, key);
                                    }
                                    else if (bodyWithStateAndLocal != null)
{
                                        tlocal = bodyWithStateAndLocal(value, parallelLoopState, tlocal);
                                    }
                                    else
{
                                        tlocal = bodyWithEverything(value, parallelLoopState, key, tlocal);
                                    }
                                    if (sharedPStateFlags.ShouldExitLoop(key))
{
                                        break;
                                    }
                                    if (Parallel.CheckTimeoutReached(num))
{
                                        replicationDelegateYieldedBeforeCompletion = true;
                                        break;
                                    }
                                }
                            }
                            else
{
                                IEnumerator<TSource> enumerator2 = partitionState as IEnumerator<TSource>;
                                if (enumerator2 == null)
{
                                    enumerator2 = partitionerSource.GetEnumerator();
                                    partitionState = enumerator2;
                                }
                                if (enumerator2 == null)
{
                                    throw new InvalidOperationException("The Partitioner source returned a null enumerator.");
                                }
                                if (parallelLoopState != null)
{
                                    parallelLoopState.CurrentIteration = 0L;
                                }
                                while (enumerator2.MoveNext())
{
                                    TSource tsource = enumerator2.Current;
                                    if (simpleBody != null)
{
                                        simpleBody(tsource);
                                    }
                                    else if (bodyWithState != null)
{
                                        bodyWithState(tsource, parallelLoopState);
                                    }
                                    else if (bodyWithStateAndLocal != null)
{
                                        tlocal = bodyWithStateAndLocal(tsource, parallelLoopState, tlocal);
                                    }
                                    if (sharedPStateFlags.LoopStateFlags != 0)
{
                                        break;
                                    }
                                    if (Parallel.CheckTimeoutReached(num))
{
                                        replicationDelegateYieldedBeforeCompletion = true;
                                        break;
                                    }
                                }
                            }
                        }
                        catch (Exception ex2)
{
                            sharedPStateFlags.SetExceptional();
                            ExceptionDispatchInfo.Throw(ex2);
                        }
                        finally
{
                            if (localFinally != null && flag)
{
                                localFinally(tlocal);
                            }
                            if (!replicationDelegateYieldedBeforeCompletion)
{
                                IDisposable disposable2 = partitionState as IDisposable;
                                if (disposable2 != null)
{
                                    disposable2.Dispose();
                                }
                            }
                            if (ParallelEtwProvider.Log.IsEnabled())
{
                                ParallelEtwProvider.Log.ParallelJoin(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID);
                            }
                        }
                    }, parallelOptions, true);
                }
                finally
                {
                    if (parallelOptions.CancellationToken.CanBeCanceled)
                    {
                        cancellationTokenRegistration.Dispose();
                    }
                }
                if (oce != null)
                {
                    throw oce;
                }
            }
            catch (AggregateException ex)
            {
                Parallel.ThrowSingleCancellationExceptionOrOtherException(ex.InnerExceptions, parallelOptions.CancellationToken, ex);
            }
            finally
            {
                int loopStateFlags = sharedPStateFlags.LoopStateFlags;
                parallelLoopResult._completed = loopStateFlags == 0;
                if ((loopStateFlags & 2) != 0)
                {
                    parallelLoopResult._lowestBreakIteration = new long?(sharedPStateFlags.LowestBreakIteration);
                }
                IDisposable disposable;
                if (orderablePartitionerSource != null)
                {
                    disposable = orderablePartitionerSource as IDisposable;
                }
                else
                {
                    disposable = partitionerSource as IDisposable;
                }
                if (disposable != null)
                {
                    disposable.Dispose();
                }
                if (ParallelEtwProvider.Log.IsEnabled())
                {
                    ParallelEtwProvider.Log.ParallelLoopEnd(TaskScheduler.Current.Id, Task.CurrentId.GetValueOrDefault(), forkJoinContextID, 0L);
                }
            }
            return parallelLoopResult;
        }
References System.Threading.CancellationToken.CanBeCanceled, System.Threading.Tasks.ParallelLoopStateFlags.Cancel(), System.Threading.Tasks.ParallelOptions.CancellationToken, System.Threading.Tasks.Parallel.CheckTimeoutReached(), System.Threading.Tasks.Parallel.ComputeTimeoutPoint(), System.Collections.Generic.IEnumerator< out T >.Current, System.Threading.Tasks.TaskScheduler.Current, System.Threading.Tasks.Task< TResult >.CurrentId, System.IDisposable.Dispose(), System.Threading.CancellationTokenRegistration.Dispose(), System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), System.Collections.Concurrent.OrderablePartitioner< TSource >.GetOrderableDynamicPartitions(), System.Threading.Tasks.TaskScheduler.Id, System.Threading.Interlocked.Increment(), System.AggregateException.InnerExceptions, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.key, System.L, System.Threading.Tasks.ParallelEtwProvider.Log, System.Threading.Tasks.ParallelLoopStateFlags.LoopStateFlags, System.Threading.Tasks.ParallelLoopStateFlags64.LowestBreakIteration, System.Collections.IEnumerator.MoveNext(), System.Threading.Tasks.ParallelEtwProvider.ParallelFork(), System.Threading.Tasks.ParallelEtwProvider.ParallelJoin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopBegin(), System.Threading.Tasks.ParallelEtwProvider.ParallelLoopEnd(), System.Threading.CancellationToken.Register(), System.Threading.Tasks.Parallel.s_forkJoinContextID, System.Threading.Tasks.ParallelLoopStateFlags.SetExceptional(), System.Threading.Tasks.ParallelLoopStateFlags64.ShouldExitLoop(), System.source, System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw(), System.Threading.CancellationToken.ThrowIfCancellationRequested(), System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, and System.value.