Terraria Decompiled: rail.IRailUsersHelperImpl.AsyncGetUserLimits
AsyncGetUserLimits()
virtual RailResult rail.IRailUsersHelperImpl.AsyncGetUserLimits (RailID user_id, string user_data) inline virtual
Implements rail.IRailUsersHelper.
Definition at line 99 of file IRailUsersHelperImpl.cs.
        {
            IntPtr intPtr = ((user_id == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailID__SWIG_0());
            if (user_id != null)
            {
                RailConverter.Csharp2Cpp(user_id, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailUsersHelper_AsyncGetUserLimits(this.swigCPtr_, intPtr, user_data);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailID(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailID(), rail.RAIL_API_PINVOKE.IRailUsersHelper_AsyncGetUserLimits(), rail.RAIL_API_PINVOKE.new_RailID__SWIG_0(), and System.IntPtr.Zero.