Terraria Decompiled: Terraria.NPC.AI_124_DeerclopsLeg
AI_124_DeerclopsLeg()
void Terraria.NPC.AI_124_DeerclopsLeg () inline private
Definition at line 41490 of file NPC.cs.
        {
            int num = (int)this.ai[0];
            if (num < 0 || num > Main.maxNPCs)
            {
                this.active = false;
                if (Main.netMode != 1)
                {
                    NetMessage.SendData(23, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                }
                return;
            }
            NPC npc = Main.npc[num];
            if (!npc.active || npc.type != 668)
            {
                this.active = false;
                if (Main.netMode != 1)
                {
                    NetMessage.SendData(23, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                }
                return;
            }
            NPCAimedTarget targetData = npc.GetTargetData(true);
            Vector2 vector = targetData.Center - base.Center;
            float num2 = targetData.Center.X - (float)(this.width / 2);
            int num3 = Math.Sign(num2 - this.position.X);
            float num4 = Math.Abs(num2 - this.position.X);
            float num5 = Math.Min(50f, num4);
            float num6 = num2 + (float)(-(float)num3) * num5;
            Math.Abs(vector.X);
            if (Math.Abs(num6 - base.Center.X) >= 30f && this.localAI[0] == 0f)
            {
                this.localAI[0] = 1f;
            }
            float num7 = 4f;
            float num8 = 30f;
            if (this.localAI[0] < 0f)
            {
                this.localAI[0] += 1f;
            }
            if (this.localAI[0] > 0f)
            {
                this.localAI[0] += 1f;
                if (this.localAI[0] >= num8)
                {
                    this.localAI[0] = -num7;
                }
            }
            int num9 = ((this.ai[1] == 0f) ? (-1) : 1);
            if (this.localAI[0] > 0f)
            {
                Vector2 vector2 = new Vector2((float)(num9 * 14), -20f);
                Vector2 vector3 = npc.Bottom + vector2 + new Vector2(0f, 30f);
                int num10 = 16;
                int num11 = 0;
                float? num12 = NPC.TryFindingFloor(vector3, num10, out num11);
                float num13 = 0.33333334f;
                Vector2 vector4 = new Vector2(vector3.X, vector3.Y + 100f);
                float num14 = this.localAI[0] / num8;
                if (num12 != null && num11 > 2)
                {
                    new Vector2(vector3.X, num12.Value * 16f);
                    vector4 = new Vector2(vector3.X, num12.Value * 16f);
                    num13 = num14;
                }
                vector4.Y -= (1f - num14) * 30f;
                Vector2 vector5 = Vector2.Lerp(base.Bottom, vector4, num13);
                base.Bottom = vector5;
            }
            int num15 = num9;
            if (Math.Abs(vector.X) > 30f)
            {
                num15 = Math.Sign(vector.X);
            }
            this.spriteDirection = -num15;
        }
References System.Math.Abs(), Terraria.NPC.active, Terraria.NPC.ai, Terraria.NPC.GetTargetData(), int, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.NPC.localAI, Terraria.Main.maxNPCs, System.Math.Min(), Terraria.Main.netMode, Terraria.Main.npc, Terraria.Entity.position, Terraria.NetMessage.SendData(), System.Math.Sign(), Terraria.NPC.TryFindingFloor(), Terraria.NPC.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.whoAmI, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.