Terraria Decompiled: Terraria.NPC.FindCattailTop
FindCattailTop()
static bool Terraria.NPC.FindCattailTop (int landX, int landY, out int cattailX, out int cattailY) inline static
Definition at line 79189 of file NPC.cs.
        {
            cattailX = landX;
            cattailY = landY;
            if (!WorldGen.InWorld(landX, landY, 31))
            {
                return false;
            }
            int num = 1;
            for (int i = landX - 30; i <= landX + 30; i++)
            {
                for (int j = landY - 20; j <= landY + 20; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active() && tile.type == 519 && tile.frameX >= 180 && Main.rand.Next(num) == 0)
                    {
                        cattailX = i;
                        cattailY = j;
                        num++;
                    }
                }
            }
            return cattailX != landX || cattailY != landY;
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_114_Dragonflies(), and Terraria.NPC.Spawner.SpawnAnNPC().