Terraria Decompiled: Terraria.NPC.GetAvailableNPCSlot
GetAvailableNPCSlot()
static int Terraria.NPC.GetAvailableNPCSlot (int Type, int startIndex) inline static private
Definition at line 79809 of file NPC.cs.
        {
            Type = NPCID.FromNetId(Type);
            bool flag = NPCID.Sets.SearchSpawnSlotsInReverse[Type];
            if (startIndex == 0 && NPCID.Sets.CannotSpawnInSlot0[Type])
            {
                startIndex = 1;
            }
            int num = Main.maxNPCs;
            int num2 = 1;
            if (flag)
            {
                num--;
                Utils.Swap<int>(ref startIndex, ref num);
                num2 = -1;
            }
            for (int num3 = startIndex; num3 != num; num3 += num2)
            {
                if (!NPC.IsSpawnSlotInUse(num3))
                {
                    return num3;
                }
            }
            for (int num4 = startIndex; num4 != num; num4 += num2)
            {
                if (Main.npc[num4].CanBeReplacedByOtherNPCs)
                {
                    return num4;
                }
            }
            return -1;
        }
References Terraria.NPC.CanBeReplacedByOtherNPCs, Terraria.ID.NPCID.Sets.CannotSpawnInSlot0, Terraria.ID.NPCID.FromNetId(), Terraria.NPC.IsSpawnSlotInUse(), Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.ID.NPCID.Sets.SearchSpawnSlotsInReverse, and System.startIndex.
Referenced by Terraria.NPC.NewNPC().