Terraria Decompiled: Terraria.NPC.UpdateNPC_CritterSounds
UpdateNPC_CritterSounds()
void Terraria.NPC.UpdateNPC_CritterSounds () inline private
Definition at line 93270 of file NPC.cs.
        {
            if (Main.netMode != 2)
            {
                if ((this.type == 611 || this.type == 689) && !Main.dayTime && Main.rand.Next(700) == 0)
                {
                    SoundEngine.PlaySound(46, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                }
                if (this.type >= 602 && this.type <= 603 && Main.dayTime && Main.rand.Next(1200) == 0)
                {
                    SoundEngine.PlaySound(44, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                }
                if (this.type >= 362 && this.type <= 365)
                {
                    if (Main.dayTime && Main.rand.Next(200) == 0)
                    {
                        SoundEngine.PlaySound(30, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        return;
                    }
                }
                else if (this.type == 361 || this.type == 445 || this.type == 687)
                {
                    if ((double)Math.Abs(this.velocity.X) < 0.5 && (!Main.dayTime || (double)this.position.Y > Main.worldSurface * 16.0) && Main.rand.Next(200) == 0)
                    {
                        SoundEngine.PlaySound(31, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        return;
                    }
                }
                else if (this.type == 74 || this.type == 297 || this.type == 298 || this.type == 442 || this.type == 671 || this.type == 672 || this.type == 673 || this.type == 674 || this.type == 675)
                {
                    if (Main.dayTime && Main.time < 18000.0)
                    {
                        int num = 400;
                        if (Main.rand.Next(num) == 0)
{
                            if (this.type == 74)
{
                                if (Main.rand.Next(3) != 0)
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 14, 1f, 0f);
                                }
                                else
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 18, 1f, 0f);
                                }
                            }
                            if (this.type == 297)
{
                                SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 16, 1f, 0f);
                            }
                            if (this.type == 298)
{
                                if (Main.rand.Next(3) != 0)
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 17, 1f, 0f);
                                }
                                else
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 19, 1f, 0f);
                                }
                            }
                            if (this.type == 674 || this.type == 675)
{
                                SoundEngine.PlaySound(67, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                            if (this.type == 671 || this.type == 672)
{
                                SoundEngine.PlaySound(68, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                            if (this.type == 673)
{
                                SoundEngine.PlaySound(69, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                            if (this.type == 442)
{
                                int num2 = Main.rand.Next(5);
                                if (num2 == 0)
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 16, 1f, 0f);
                                    return;
                                }
                                if (num2 == 1)
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 17, 1f, 0f);
                                    return;
                                }
                                if (num2 == 2)
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 19, 1f, 0f);
                                    return;
                                }
                                if (num2 == 3)
{
                                    SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 14, 1f, 0f);
                                    return;
                                }
                                SoundEngine.PlaySound(32, (int)this.position.X, (int)this.position.Y, 18, 1f, 0f);
                                return;
                            }
                        }
                    }
                }
                else if ((this.type == 300 || this.type == 447 || this.type == 610) && Main.rand.Next(1800) == 0)
                {
                    SoundEngine.PlaySound(33, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                }
            }
        }
References System.Math.Abs(), Terraria.Main.dayTime, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Main.time, and Terraria.Main.worldSurface.