Terraria Decompiled: Terraria.NPC.ViolentlySpawnNerdySlime
ViolentlySpawnNerdySlime()
void Terraria.NPC.ViolentlySpawnNerdySlime () inline private
Definition at line 78490 of file NPC.cs.
        {
            int num = NPC.NewNPC(this.GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X - 10, (int)base.Center.Y, 670, 0, 0f, 0f, 0f, 0f, 255);
            NPC npc = Main.npc[num];
            Vector2 vector = new Vector2(Main.rand.NextFloatDirection() * 3f, -10f);
            npc.velocity = vector;
            npc.netUpdate = true;
            WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            ParticleOrchestrator.BroadcastParticleSpawn(ParticleOrchestraType.TownSlimeTransform, new ParticleOrchestraSettings
            {
                PositionInWorld = base.Center,
                MovementVector = vector,
                UniqueInfoPiece = 0
            });
        }
References Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.Main.rand, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.NPC.DoDeathEvents().