Terraria Decompiled: Terraria.NPC.GetBossHeadRotation
GetBossHeadRotation()
float Terraria.NPC.GetBossHeadRotation () inline
Definition at line 1339 of file NPC.cs.
        {
            float num = 0f;
            int num2 = this.type;
            if (num2 <= 68)
            {
                if (num2 == 35)
                {
                    goto IL_003E;
                }
                if (num2 != 68)
                {
                    return num;
                }
            }
            else
            {
                if (num2 == 127)
                {
                    goto IL_003E;
                }
                if (num2 != 262)
                {
                    if (num2 != 345)
                    {
                        return num;
                    }
                    if (this.ai[0] == 2f)
                    {
                        return this.rotation;
                    }
                    return num;
                }
            }
            return this.rotation;
            IL_003E:
            if (this.ai[1] == 1f || this.ai[1] == 2f)
            {
                num = this.rotation;
            }
            return num;
        }
References Terraria.NPC.ai, Terraria.NPC.rotation, and Terraria.NPC.type.
Referenced by Terraria.Main.DrawNPCMapIcons(), Terraria.Main.DrawNPCMapIcons2(), and Terraria.Main.DrawNPCMapIcons3().