Terraria Decompiled: Terraria.NPC.ScaleStats_ByDifficulty
ScaleStats_ByDifficulty()
void Terraria.NPC.ScaleStats_ByDifficulty () inline
Definition at line 11997 of file NPC.cs.
        {
            if (this.type < 0 || !NPCID.Sets.ProjectileNPC[this.type])
            {
                this.lifeMax = (int)((float)this.lifeMax * GameDifficultyData.EnemyMaxLifeMultiplier.Sample(this.difficulty));
                this.value = (float)((int)(this.value * GameDifficultyData.EnemyMoneyDropMultiplier.Sample(this.difficulty)));
            }
            this.damage = this.GetAttackDamage_ScaledByDifficulty((float)this.damage);
            this.knockBackResist = this.GetKnockbackMultiplier_ScaledByDifficulty(this.knockBackResist);
            this.ScaleStats_ByDifficulty_Tweaks();
        }
References Terraria.NPC.damage, Terraria.NPC.difficulty, Terraria.DataStructures.GameDifficultyData.EnemyMaxLifeMultiplier, Terraria.DataStructures.GameDifficultyData.EnemyMoneyDropMultiplier, Terraria.NPC.GetAttackDamage_ScaledByDifficulty(), Terraria.NPC.GetKnockbackMultiplier_ScaledByDifficulty(), int, Terraria.NPC.knockBackResist, Terraria.ID.NPCID.Sets.ProjectileNPC, Terraria.NPC.ScaleStats_ByDifficulty_Tweaks(), and Terraria.NPC.type.
Referenced by Terraria.NPC.ScaleStats().