Terraria Decompiled: Terraria.NPC.TryTrackingTarget
TryTrackingTarget()
void Terraria.NPC.TryTrackingTarget (ref float distance, ref float realDist, ref bool t, ref int tankTarget, int j) inline private
Definition at line 76174 of file NPC.cs.
        {
            float num = Math.Abs(Main.player[j].position.X + (float)(Main.player[j].width / 2) - this.position.X + (float)(this.width / 2)) + Math.Abs(Main.player[j].position.Y + (float)(Main.player[j].height / 2) - this.position.Y + (float)(this.height / 2));
            num -= (float)Main.player[j].aggro;
            if (Main.player[j].npcTypeNoAggro[this.type] && this.direction != 0)
            {
                num += 1000f;
            }
            if (!t || num < distance)
            {
                t = true;
                tankTarget = -1;
                realDist = Math.Abs(Main.player[j].position.X + (float)(Main.player[j].width / 2) - this.position.X + (float)(this.width / 2)) + Math.Abs(Main.player[j].position.Y + (float)(Main.player[j].height / 2) - this.position.Y + (float)(this.height / 2));
                distance = num;
                this.target = j;
            }
            if (Main.player[j].tankPet >= 0 && !Main.player[j].npcTypeNoAggro[this.type])
            {
                int tankPet = Main.player[j].tankPet;
                float num2 = Math.Abs(Main.projectile[tankPet].position.X + (float)(Main.projectile[tankPet].width / 2) - this.position.X + (float)(this.width / 2)) + Math.Abs(Main.projectile[tankPet].position.Y + (float)(Main.projectile[tankPet].height / 2) - this.position.Y + (float)(this.height / 2));
                num2 -= 200f;
                if (num2 < distance && num2 < 200f && Collision.CanHit(base.Center, 1, 1, Main.projectile[tankPet].Center, 1, 1))
                {
                    tankTarget = tankPet;
                }
            }
        }
References System.Math.Abs(), Terraria.Player.aggro, Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Entity.height, Terraria.Player.npcTypeNoAggro, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.projectile, Terraria.Player.tankPet, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.TargetClosest(), and Terraria.NPC.TargetClosest_WOF().