Terraria Decompiled: Terraria.NPC.MakeTransitionEffectsForTextureChanges
MakeTransitionEffectsForTextureChanges()
void Terraria.NPC.MakeTransitionEffectsForTextureChanges (int oldAltTexture, int currentAltTexture) inline private
Definition at line 91072 of file NPC.cs.
        {
            if (oldAltTexture == 0 && currentAltTexture == 1)
            {
                for (int i = 0; i < 20; i++)
                {
                    Dust.NewDust(this.position, this.width, this.height / 4, 139 + Main.rand.Next(4), 0f, -2f, 0, default(Color), 1f);
                }
            }
            if (oldAltTexture == 1 && currentAltTexture == 0)
            {
                Utils.PoofOfSmoke(this.position);
            }
            if (this.type == 633)
            {
                int num = 2;
                if ((oldAltTexture == 0 && currentAltTexture == num) || (oldAltTexture == num && currentAltTexture == 0))
                {
                    for (int j = 0; j < 20; j++)
                    {
                        Dust dust = Dust.NewDustDirect(this.position, this.width, this.height, 262, 0f, -2f, 0, default(Color), 1f);
                        dust.noGravity = true;
                        dust.scale = 2f;
                    }
                }
            }
        }
References Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utils.PoofOfSmoke(), and Terraria.Main.rand.