Terraria Decompiled: Terraria.NPC.ScaleStats_ByDifficulty_Tweaks
ScaleStats_ByDifficulty_Tweaks()
void Terraria.NPC.ScaleStats_ByDifficulty_Tweaks () inline private
Definition at line 12010 of file NPC.cs.
        {
            double num = 1.0;
            double num2 = 1.0;
            double num3 = 1.0;
            if (Main.getGoodWorld)
            {
                if (this.type == 6 && NPC.AnyNPCs(13))
                {
                    num3 *= NPC.CommonMasterBossLifeReduction;
                    num2 *= 1.5;
                    if (this.difficulty >= GameDifficultyLevel.Expert)
                    {
                        this.defense += 2;
                    }
                }
                if (this.type == 32 && NPC.AnyNPCs(35))
                {
                    num3 *= NPC.CommonMasterBossLifeReduction;
                    num2 *= 1.5;
                    if (this.difficulty >= GameDifficultyLevel.Expert)
                    {
                        this.defense += 6;
                    }
                }
                if (this.type == 24 && NPC.AnyNPCs(113))
                {
                    num3 *= NPC.CommonMasterBossLifeReduction;
                    num2 *= 1.5;
                    if (this.difficulty >= GameDifficultyLevel.Expert)
                    {
                        this.defense += 10;
                    }
                }
            }
            if (this.type == 210 || this.type == 211)
            {
                num2 = 0.6000000000000001;
                num = 0.6;
                this.defense = (int)((float)this.defense * Utils.Remap(this.difficulty, GameDifficultyLevel.Classic, GameDifficultyLevel.Expert, 1f, 0.8f, true));
            }
            else if (this.type == 5)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            else if (this.type == 4)
            {
                num2 = 0.65;
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            else if (this.type >= 13 && this.type <= 15)
            {
                num2 = 0.7;
                num3 *= NPC.CommonMasterBossLifeReduction;
                if (this.type == 13)
                {
                    num *= 1.1;
                }
                if (this.type == 14)
                {
                    num *= 0.8;
                }
                if (this.type == 15)
                {
                    num *= 0.8;
                }
                if (this.difficulty >= GameDifficultyLevel.Expert)
                {
                    this.scale *= 1.2f;
                    this.defense += 2;
                }
            }
            else if (this.type == 266 || this.type == 267)
            {
                num2 = 0.85;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num *= 0.9;
                if (this.difficulty >= GameDifficultyLevel.Expert)
                {
                    this.scale *= 1.05f;
                }
            }
            else if (this.type == 50)
            {
                num2 = 0.7;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num *= 0.8;
            }
            else if (this.type == 471)
            {
                num2 = 0.85;
            }
            else if (this.type == 472)
            {
                num2 = 0.85;
                num = 0.8;
            }
            else if (this.type == 492)
            {
                num2 = 0.85;
            }
            else if (this.type == 393 || this.type == 394 || this.type == 395)
            {
                num2 = 0.85;
            }
            else if (this.type == 222)
            {
                num2 = 0.7;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.9;
            }
            else if (this.type == 35)
            {
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 1.1;
            }
            else if (this.type == 36)
            {
                num2 = 1.3;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 1.1;
            }
            else if (this.type == 668)
            {
                num2 = 0.85;
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            else if (this.type == 113 || this.type == 114)
            {
                num2 = 0.7;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 1.5;
                if (this.difficulty >= GameDifficultyLevel.Expert)
                {
                    this.defense += 6;
                }
            }
            else if (this.type == 115)
            {
                num2 = 0.7;
                if (this.difficulty >= GameDifficultyLevel.Expert)
                {
                    this.defense += 6;
                }
            }
            else if (this.type == 116)
            {
                num2 = 0.7;
            }
            else if (this.type == 117 || this.type == 118 || this.type == 119)
            {
                num2 = 0.8;
            }
            else if (this.type == 657)
            {
                num2 = 0.8;
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            else if (this.type >= 658 && this.type <= 660)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            else if (this.type >= 134 && this.type <= 136)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
                if (this.type == 134)
                {
                    num *= 2.0;
                }
                if (this.type == 135)
                {
                    num *= 0.85;
                }
                if (this.type == 136)
                {
                    num *= 0.85;
                }
                if (this.difficulty >= GameDifficultyLevel.Expert)
                {
                    this.scale *= 1.05f;
                }
            }
            else if (this.type == 139)
            {
                num2 = 0.75;
                num = 0.8;
                if (this.difficulty >= GameDifficultyLevel.Expert)
                {
                    this.scale *= 1.05f;
                }
            }
            else if (this.type >= 127 && this.type <= 131)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.85;
            }
            else if (this.type >= 125 && this.type <= 126)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.85;
            }
            else if (this.type == 262)
            {
                num2 = 0.7;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 1.15;
            }
            else if (this.type == 264)
            {
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 1.15;
            }
            else if (this.type == 636)
            {
                num2 = 0.7;
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            else if (this.type >= 245 && this.type <= 249)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.8;
            }
            else if (this.type == 370)
            {
                num2 = 0.65;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.7;
            }
            else if (this.type == 371 || this.type == 372 || this.type == 373)
            {
                if (this.type != 371)
                {
                    num2 = 0.75;
                }
                num = 0.75;
            }
            else if (this.type == 439 || this.type == 440 || (this.type >= 454 && this.type <= 459) || this.type == 522 || this.type == 523)
            {
                if (this.type != 522)
                {
                    num2 = 0.75;
                    num3 *= NPC.CommonMasterBossLifeReduction;
                }
                num = 0.75;
            }
            else if (this.type == 397 || this.type == 396 || this.type == 398)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.75;
            }
            else if (this.type == 551)
            {
                num2 = 0.75;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.65;
            }
            else if (NPCID.Sets.BelongsToInvasionOldOnesArmy[this.type])
            {
                num3 *= NPC.CommonMasterBossLifeReduction;
            }
            int npcinvasionGroup = NPC.GetNPCInvasionGroup(this.type);
            if (npcinvasionGroup == -2 || npcinvasionGroup == -1)
            {
                int num4 = this.type;
                if (num4 <= 325)
                {
                    if (num4 != 315 && num4 != 325)
                    {
                        goto IL_0909;
                    }
                }
                else if (num4 != 327 && num4 - 344 > 2)
                {
                    goto IL_0909;
                }
                num2 = 0.65;
                num3 *= NPC.CommonMasterBossLifeReduction;
                num = 0.75;
                goto IL_091D;
                IL_0909:
                num2 = 0.75;
                num = 0.75;
            }
            IL_091D:
            float num5 = 1f;
            num5 *= Utils.Remap(this.difficulty, GameDifficultyLevel.Classic, GameDifficultyLevel.Expert, 1f, (float)num2, true);
            num5 *= Utils.Remap(this.difficulty, GameDifficultyLevel.Expert, GameDifficultyLevel.Master, 1f, (float)num3, true);
            this.lifeMax = (int)Math.Round((double)((float)this.lifeMax * num5));
            float num6 = 1f;
            num6 *= Utils.Remap(this.difficulty, GameDifficultyLevel.Classic, GameDifficultyLevel.Expert, 1f, (float)num, true);
            this.damage = (int)Math.Round((double)((float)this.damage * num6));
        }
References Terraria.NPC.AnyNPCs(), Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.DataStructures.GameDifficultyLevel.Classic, Terraria.NPC.CommonMasterBossLifeReduction, Terraria.NPC.damage, Terraria.NPC.difficulty, Terraria.DataStructures.GameDifficultyLevel.Expert, Terraria.Main.getGoodWorld, Terraria.NPC.GetNPCInvasionGroup(), int, Terraria.NPC.lifeMax, Terraria.DataStructures.GameDifficultyLevel.Master, Terraria.Utils.Remap(), System.Math.Round(), and Terraria.NPC.type.
Referenced by Terraria.NPC.ScaleStats_ByDifficulty().