Terraria Decompiled: Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall
AI_AttemptToFindTeleportSpotNearBooks_SearchWall()
bool Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall (int x, int y, bool downwards, out Vector2 destination, out bool outOfBounds) inline private
Definition at line 12996 of file NPC.cs.
        {
            destination = Vector2.Zero;
            outOfBounds = false;
            int num = (downwards ? 1 : (-1));
            bool flag;
            for (;;)
            {
                y += num;
                if (y < 0 || y >= Main.maxTilesY)
                {
                    break;
                }
                Tile tile = Main.tile[x, y];
                flag = false;
                if (tile.active() && tile.type == 50)
                {
                    goto Block_4;
                }
                bool flag2 = tile.active() && Main.tileSolid[(int)tile.type];
                if (flag2)
                {
                    return false;
                }
            }
            outOfBounds = true;
            return false;
            Block_4:
            Rectangle rectangle = new Rectangle(x * 16, y * 16, 16, 16);
            rectangle.Inflate(80, 80);
            for (int i = 0; i < Main.player.Length; i++)
            {
                Player player = Main.player[i];
                if (player != null && player.active && !player.dead)
                {
                    Rectangle hitbox = player.Hitbox;
                    Rectangle rectangle2 = hitbox.Modified((int)(player.velocity.X * 20f), (int)(player.velocity.Y * 20f), 0, 0);
                    Rectangle.Union(ref rectangle2, ref hitbox, out rectangle2);
                    if (rectangle2.Intersects(rectangle))
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (!flag)
            {
                destination = new Vector2((float)x, (float)y);
                return true;
            }
            return false;
        }
References Terraria.Player.active, Terraria.Tile.active(), Terraria.Player.dead, System.destination, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.maxTilesY, Terraria.Main.player, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Microsoft.Xna.Framework.Rectangle.Union(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks().