Terraria Decompiled: Terraria.NPC.CatchNPC
CatchNPC()
static void Terraria.NPC.CatchNPC (int i, int who = -1) inline static
Definition at line 78885 of file NPC.cs.
        {
            if (!Main.npc[i].active)
            {
                return;
            }
            if (who == -1)
            {
                who = Main.myPlayer;
            }
            if (Main.netMode == 1)
            {
                Main.npc[i].active = false;
                NetMessage.SendData(70, -1, -1, null, i, (float)who, 0f, 0f, 0, 0, 0);
                return;
            }
            if (Main.npc[i].catchItem > 0)
            {
                if (Main.npc[i].type == 687)
                {
                    Main.npc[i].TryTeleportingCaughtMysticFrog();
                    return;
                }
                if (Main.npc[i].SpawnedFromStatue)
                {
                    Vector2 vector = Main.npc[i].Center - new Vector2(20f);
                    Utils.PoofOfSmoke(vector);
                    Main.npc[i].active = false;
                    NetMessage.SendData(23, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                    NetMessage.SendData(106, -1, -1, null, (int)vector.X, vector.Y, 0f, 0f, 0, 0, 0);
                    return;
                }
                new Item().SetDefaults((int)Main.npc[i].catchItem, null);
                Item.NewItem(NPC.GetSpawnSource_NPCCatch(who), (int)Main.player[who].Center.X, (int)Main.player[who].Center.Y, 0, 0, (int)Main.npc[i].catchItem, 1, false, 0, true);
                Main.npc[i].active = false;
                NetMessage.SendData(23, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.NPC.active, Terraria.NPC.catchItem, Terraria.Entity.Center, Terraria.NPC.GetSpawnSource_NPCCatch(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.npc, Terraria.Main.player, Terraria.Utils.PoofOfSmoke(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.NPC.SpawnedFromStatue, Terraria.NPC.TryTeleportingCaughtMysticFrog(), Terraria.NPC.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.ItemCheck_CatchCritters().