Terraria Decompiled: Terraria.NPC.IsDeerclopsHostile
IsDeerclopsHostile()
static bool Terraria.NPC.IsDeerclopsHostile () inline static
Definition at line 40740 of file NPC.cs.
        {
            if (NPC.deerclopsBoss == -1)
            {
                return false;
            }
            NPC npc = Main.npc[NPC.deerclopsBoss];
            if (!npc.active || npc.type != 668)
            {
                return false;
            }
            int num = (int)npc.ai[0];
            if (num == 6 || num == 7 || num == 8)
            {
                Rectangle rectangle = new Rectangle((int)Main.screenPosition.X, (int)Main.screenPosition.Y, Main.screenWidth, Main.screenHeight);
                rectangle.Inflate(960, 960);
                if (!npc.Hitbox.Intersects(rectangle))
                {
                    return false;
                }
            }
            return true;
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.NPC.deerclopsBoss, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.npc, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.NPC.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.SceneState.UpdateRGBPeriheralProbe(), and Terraria.GameContent.UI.BigProgressBar.DeerclopsBigProgressBar.ValidateAndCollectNecessaryInfo().