Terraria Decompiled: Terraria.NPC.AI_118_Seahorses
AI_118_Seahorses()
void Terraria.NPC.AI_118_Seahorses () inline private
Definition at line 43903 of file NPC.cs.
        {
            this.noGravity = this.wet;
            float num;
            Collision.GetWaterLineIterate(base.Center.ToTileCoordinates(), out num);
            bool flag = num > 0f && base.Top.Y - num < 20f;
            if (!this.wet)
            {
                if (this.velocity.Y == 0f)
                {
                    this.velocity.X = this.velocity.X * 0.95f;
                }
                this.rotation += (this.velocity.X + this.velocity.Y) / 2f * 0.05f;
            }
            else
            {
                this.ai[1] -= 1f;
                if (this.ai[1] <= 0f)
                {
                    this.velocity += this.ai[0].ToRotationVector2() * 0.06f;
                    float num2 = this.velocity.Length();
                    if (num2 > 3f || num2 < -3f)
                    {
                        this.velocity.X = Math.Min(3f, Math.Max(-3f, this.velocity.X));
                        this.ai[1] = (float)Main.rand.Next(450, 600);
                        this.ai[0] = Main.rand.NextFloat() * 6.2831855f;
                        if (flag && this.ai[0] > 3.1415927f)
{
                            this.ai[0] -= 3.1415927f;
                        }
                        this.netUpdate = true;
                    }
                }
                else
                {
                    this.velocity *= 0.95f;
                }
                this.rotation = this.velocity.X * 0.1f;
            }
            bool flag2 = this.collideY && this.wet && (!flag || this.velocity.Y < 0f);
            if (this.collideX || flag2)
            {
                Vector2 vector = this.ai[0].ToRotationVector2();
                if (this.collideX)
                {
                    vector.X *= -1f;
                }
                if (flag2)
                {
                    vector.Y *= -1f;
                }
                this.ai[0] = vector.ToRotation();
                this.velocity = this.ai[0].ToRotationVector2() * this.velocity.Length();
                this.netUpdate = true;
            }
        }
References Terraria.NPC.ai, Terraria.NPC.collideX, Terraria.Collision.GetWaterLineIterate(), Microsoft.Xna.Framework.Vector2.Length(), System.Math.Max(), System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Entity.velocity, Terraria.Entity.wet, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().