Terraria Decompiled: Terraria.NPC.CreateBrickBoxForWallOfFlesh
CreateBrickBoxForWallOfFlesh()
void Terraria.NPC.CreateBrickBoxForWallOfFlesh () inline private
Definition at line 77778 of file NPC.cs.
        {
            int num = (int)(this.position.X + (float)(this.width / 2)) / 16;
            int num2 = (int)(this.position.Y + (float)(this.height / 2)) / 16;
            int num3 = this.width / 2 / 16 + 1;
            for (int i = num - num3; i <= num + num3; i++)
            {
                for (int j = num2 - num3; j <= num2 + num3; j++)
                {
                    if ((i == num - num3 || i == num + num3 || j == num2 - num3 || j == num2 + num3) && !Main.tile[i, j].active())
                    {
                        Main.tile[i, j].type = (WorldGen.crimson ? 347 : 140);
                        Main.tile[i, j].active(true);
                    }
                    Main.tile[i, j].lava(false);
                    Main.tile[i, j].liquid = 0;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                    }
                    else
                    {
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                }
            }
        }
References Terraria.Tile.active(), int, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.Entity.position, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.DoDeathEvents().