Terraria Decompiled: Terraria.NPC.FindFirstNPC
FindFirstNPC()
static int Terraria.NPC.FindFirstNPC (int Type) inline static
Definition at line 90663 of file NPC.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == Type)
                {
                    return i;
                }
            }
            return -1;
        }
References Terraria.NPC.active, Terraria.Main.maxNPCs, Terraria.Main.npc, and Terraria.NPC.type.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AnyoneNearCultists(), Terraria.GameContent.Events.DD2Event.Difficulty_3_GetRequiredWaveKills(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.SpawnMechQueen(), Terraria.GameContent.Events.DD2Event.StartVictoryScene(), and Terraria.GameContent.Events.DD2Event.SummonBetsy().