Terraria Decompiled: Terraria.NPC.AI_127_Pal_GiveRewerd
AI_127_Pal_GiveRewerd()
void Terraria.NPC.AI_127_Pal_GiveRewerd () inline private
Definition at line 39751 of file NPC.cs.
        {
            short num = 5663;
            if (this.type == 696)
            {
                num = 5664;
            }
            Item.NewItem(this.GetItemSource_Loot(), this.position, base.Size, (int)num, 1, false, -1, false);
        }
References Terraria.NPC.GetItemSource_Loot(), Terraria.Item.NewItem(), Terraria.Entity.position, and Terraria.NPC.type.
Referenced by Terraria.NPC.AI_127_Pal().