Terraria Decompiled: Terraria.NPC.GetTargetData
GetTargetData()
NPCAimedTarget Terraria.NPC.GetTargetData (bool ignorePlayerTankPets = true) inline
Definition at line 118 of file NPC.cs.
        {
            if (!this.HasValidTarget)
            {
                return default(NPCAimedTarget);
            }
            if (this.SupportsNPCTargets && this.HasNPCTarget)
            {
                return new NPCAimedTarget(Main.npc[this.TranslatedTargetIndex]);
            }
            return new NPCAimedTarget(Main.player[this.target], ignorePlayerTankPets);
        }
References Terraria.NPC.HasNPCTarget, Terraria.NPC.HasValidTarget, Terraria.Main.npc, Terraria.Main.player, and Terraria.NPC.SupportsNPCTargets.
Referenced by Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_119_Dandelion(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_122_PirateGhost(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_123_Deerclops_Movement(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.NPC.AI_124_DeerclopsLeg(), and Terraria.NPC.AI_125_ClumsySlimeBalloon().