Terraria Decompiled: Terraria.NPC.SpawnMechQueen
SpawnMechQueen()
static bool Terraria.NPC.SpawnMechQueen (int onWhichPlayer) inline static
Definition at line 13753 of file NPC.cs.
        {
            if (NPC.AnyNPCs(127) || NPC.AnyNPCs(134) || NPC.AnyNPCs(125) || NPC.AnyNPCs(126))
            {
                return false;
            }
            if (!SpecialSeedFeatures.Mechdusa)
            {
                return false;
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(61, -1, -1, null, onWhichPlayer, -16f, 0f, 0f, 0, 0, 0);
            }
            else
            {
                NPC.mechQueen = -2;
                NPC.SpawnOnPlayer(onWhichPlayer, 127, 0f, 0f, 0f, 0f);
                NPC.mechQueen = NPC.FindFirstNPC(127);
                NPC.NewNPC(NPC.GetBossSpawnSource(onWhichPlayer), (int)Main.npc[NPC.mechQueen].Center.X, (int)Main.npc[NPC.mechQueen].Center.Y, 125, 1, 0f, 0f, 0f, 0f, 255);
                NPC.NewNPC(NPC.GetBossSpawnSource(onWhichPlayer), (int)Main.npc[NPC.mechQueen].Center.X, (int)Main.npc[NPC.mechQueen].Center.Y, 126, 1, 0f, 0f, 0f, 0f, 255);
                int num = NPC.NewNPC(NPC.GetBossSpawnSource(onWhichPlayer), (int)Main.npc[NPC.mechQueen].Center.X, (int)Main.npc[NPC.mechQueen].Center.Y, 134, 1, 0f, 0f, 0f, 0f, 255);
                NPC.NewNPC(NPC.GetBossSpawnSource(onWhichPlayer), (int)Main.npc[NPC.mechQueen].Center.X, (int)Main.npc[NPC.mechQueen].Center.Y, 139, 1, 0f, 0f, (float)num, -1f, 255);
                NPC.NewNPC(NPC.GetBossSpawnSource(onWhichPlayer), (int)Main.npc[NPC.mechQueen].Center.X, (int)Main.npc[NPC.mechQueen].Center.Y, 139, 1, 0f, 0f, (float)num, 1f, 255);
            }
            return true;
        }
References Terraria.NPC.AnyNPCs(), Terraria.Entity.Center, Terraria.NPC.FindFirstNPC(), Terraria.NPC.GetBossSpawnSource(), Terraria.GameContent.SpecialSeedFeatures.Mechdusa, Terraria.NPC.mechQueen, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnOnPlayer(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.ItemCheck_UseBossSpawners(), and Terraria.Main.UpdateTime().