Terraria Decompiled: Terraria.NPC.ResetForNewNPC
ResetForNewNPC()
void Terraria.NPC.ResetForNewNPC () inline
Definition at line 2162 of file NPC.cs.
        {
            this.netOffset = Vector2.Zero;
            this.netStream = 0;
            this.netSpam = 0;
            Array.Clear(this.playerNetSyncState, 0, this.playerNetSyncState.Length);
            this.velocity = Vector2.Zero;
            this.direction = 0;
            this.oldDirection = 0;
            this.spriteDirection = -1;
            this.wet = false;
            this.lavaWet = false;
            this.honeyWet = false;
            this.shimmerWet = false;
            this.SpawnedFromStatue = false;
            this.extraValue = 0;
            this.shimmerTransparency = 0f;
            this.lookForHomeTimeout = 0;
            Array.Clear(this.buffTime, 0, this.buffTime.Length);
            Array.Clear(this.buffType, 0, this.buffType.Length);
            Array.Clear(this.playerInteraction, 0, this.playerInteraction.Length);
            if (this.whoAmI >= Main.maxNPCs)
            {
                return;
            }
            PortalHelper.ResetNPCSlotData(this.whoAmI);
            Projectile.ResetNPCSlotData(this.whoAmI);
            Player.ResetNPCSlotData(this.whoAmI);
        }
References Terraria.NPC.buffTime, Terraria.NPC.buffType, System.Array.Clear(), Terraria.Main.maxNPCs, Terraria.NPC.playerInteraction, Terraria.NPC.playerNetSyncState, Terraria.GameContent.PortalHelper.ResetNPCSlotData(), Terraria.Player.ResetNPCSlotData(), Terraria.Projectile.ResetNPCSlotData(), Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.NPC.NewNPC().