Terraria Decompiled: Terraria.NPC.AI_007_TownEntities_TeleportToHome
AI_007_TownEntities_TeleportToHome()
void Terraria.NPC.AI_007_TownEntities_TeleportToHome (int homeFloorX, int homeFloorY) inline private
Definition at line 52820 of file NPC.cs.
        {
            bool flag = false;
            for (int i = 0; i < 3; i++)
            {
                int num = homeFloorX + ((i == 0) ? 0 : ((i == 1) ? (-1) : 1));
                if (this.type == 37 || !Collision.SolidTiles(num - 1, num + 1, homeFloorY - 3, homeFloorY - 1))
                {
                    this.velocity.X = 0f;
                    this.velocity.Y = 0f;
                    this.position.X = (float)(num * 16 + 8 - this.width / 2);
                    this.position.Y = (float)(homeFloorY * 16 - this.height) - 0.1f;
                    this.netUpdate = true;
                    this.AI_007_TryForcingSitting(homeFloorX, homeFloorY);
                    flag = true;
                    break;
                }
            }
            if (!flag)
            {
                this.homeless = true;
                WorldGen.QuickFindHome(this.whoAmI);
            }
        }
References Terraria.NPC.AI_007_TryForcingSitting(), Terraria.Entity.height, Terraria.WorldGen.QuickFindHome(), Terraria.Collision.SolidTiles(), Terraria.NPC.type, Terraria.Entity.whoAmI, and Terraria.Entity.width.
Referenced by Terraria.NPC.AI_007_TownEntities().