Terraria Decompiled: System.Security.Cryptography.RNGCryptoServiceProvider.RNGCryptoServiceProvider
RNGCryptoServiceProvider() [5/5]
unsafe System.Security.Cryptography.RNGCryptoServiceProvider.RNGCryptoServiceProvider (string str) inline
Definition at line 55 of file RNGCryptoServiceProvider.cs.
        {
            if (str == null)
            {
                this._handle = RNGCryptoServiceProvider.RngInitialize(null, IntPtr.Zero);
            }
            else
            {
                byte[] bytes = Encoding.UTF8.GetBytes(str);
                byte[] array;
                byte* ptr;
                if ((array = bytes) == null || array.Length == 0)
                {
                    ptr = null;
                }
                else
                {
                    ptr = &array[0];
                }
                this._handle = RNGCryptoServiceProvider.RngInitialize(ptr, (IntPtr)bytes.Length);
                array = null;
            }
            this.Check();
        }
References System.array, System.Security.Cryptography.RNGCryptoServiceProvider.Check(), System.Text.Encoding.GetBytes(), System.Security.Cryptography.RNGCryptoServiceProvider.RngInitialize(), System.Text.Encoding.UTF8, and System.IntPtr.Zero.