Terraria Decompiled: Terraria.NPC.AI_FindNearbyBook
AI_FindNearbyBook()
static bool Terraria.NPC.AI_FindNearbyBook (Point searchPosition, int searchWidth, int searchHeight, out Point bookPosition, bool closestBook = false, bool checkPlayerScreenRanges = false) inline static private
Definition at line 59684 of file NPC.cs.
        {
            bookPosition = Point.Zero;
            Point[] nearbyBooks = NPC._nearbyBooks;
            int num = nearbyBooks.Length;
            int num2 = 0;
            int num3 = Math.Max(0, searchPosition.X);
            int num4 = Math.Min(searchPosition.X + searchWidth, Main.maxTilesX);
            int num5 = Math.Max(0, searchPosition.Y);
            int num6 = Math.Min(searchPosition.Y + searchHeight, Main.maxTilesY);
            float num7 = 9999999f;
            Vector2 vector = searchPosition.ToVector2();
            Vector2 vector2 = vector;
            for (int i = num5; i < num6; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Tile tile = Main.tile[j, i];
                    if (tile.active() && tile.type == 50)
                    {
                        Vector2 vector3 = new Vector2((float)j, (float)i);
                        if (!checkPlayerScreenRanges || NPC.Spawner.CheckNotSpawningOnScreen((int)vector3.X, (int)vector3.Y))
{
                            float num8 = vector3.Distance(vector2);
                            if (closestBook && num8 < num7)
{
                                num7 = num8;
                                vector = vector3;
                            }
                            else
{
                                nearbyBooks[num2++] = new Point(j, i);
                                if (num2 >= num)
{
                                    break;
                                }
                            }
                        }
                    }
                }
            }
            if (closestBook)
            {
                bookPosition = vector.ToPoint();
                return vector.X != vector2.X || vector.Y != vector2.Y;
            }
            if (num2 == 0)
            {
                return false;
            }
            bookPosition = nearbyBooks[Main.rand.Next(num2)];
            return true;
        }
References Terraria.NPC._nearbyBooks, Terraria.Tile.active(), Terraria.NPC.Spawner.CheckNotSpawningOnScreen(), Microsoft.Xna.Framework.Vector2.Distance(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Graphics.Point, Terraria.Main.rand, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.NPC.AI(), and Terraria.NPC.Spawner.SpawnAnNPC().