Terraria Decompiled: Terraria.NPC.DoDeathEvents_CelebrateBossDeath
DoDeathEvents_CelebrateBossDeath()
void Terraria.NPC.DoDeathEvents_CelebrateBossDeath () inline private
Definition at line 77760 of file NPC.cs.
        {
            NPCDamageTracker.BossKilled(this);
            Color bossOrEvent = ChatColors.BossOrEvent;
            if (this.type == 125 || this.type == 126)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Plural", new object[] { NetworkText.FromKey("Enemies.TheTwins", new object[0]) }), bossOrEvent, -1);
                return;
            }
            if (this.type == 398)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Single", new object[] { NetworkText.FromKey("Enemies.MoonLord", new object[0]) }), bossOrEvent, -1);
                return;
            }
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasBeenDefeated_Single", new object[] { this.GetTypeNetName() }), bossOrEvent, -1);
        }
References Terraria.GameContent.NPCDamageTracker.BossKilled(), Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), and Terraria.NPC.type.
Referenced by Terraria.NPC.DoDeathEvents().