Terraria Decompiled: Terraria.NPC.GetNPCLocation
GetNPCLocation()
static bool Terraria.NPC.GetNPCLocation (int i, bool seekHead, bool averageDirection, out int index, out Vector2 pos) inline static
Definition at line 12588 of file NPC.cs.
        {
            int num = Main.npc[i].type;
            int num2 = -1;
            int num3 = -1;
            if (num <= 119)
            {
                if (num <= 41)
                {
                    switch (num)
                    {
                    case 7:
                        num3 = 9;
                        num2 = 0;
                        break;
                    case 8:
                    case 9:
                        num3 = 7;
                        num2 = 1;
                        break;
                    case 10:
                        num3 = 12;
                        num2 = 0;
                        break;
                    case 11:
                    case 12:
                        num3 = 10;
                        num2 = 1;
                        break;
                    case 13:
                        num3 = 15;
                        num2 = 0;
                        break;
                    case 14:
                    case 15:
                        num3 = 13;
                        num2 = 1;
                        break;
                    default:
                        if (num != 39)
{
                            if (num - 40 <= 1)
{
                                num3 = 39;
                                num2 = 1;
                            }
                        }
                        else
{
                            num3 = 41;
                            num2 = 0;
                        }
                        break;
                    }
                }
                else
                {
                    switch (num)
                    {
                    case 87:
                        num3 = 92;
                        num2 = 0;
                        break;
                    case 88:
                    case 89:
                    case 90:
                    case 91:
                    case 92:
                        num3 = 87;
                        num2 = 1;
                        break;
                    case 93:
                    case 94:
                        break;
                    case 95:
                        num3 = 97;
                        num2 = 0;
                        break;
                    case 96:
                    case 97:
                        num3 = 95;
                        num2 = 1;
                        break;
                    case 98:
                        num3 = 100;
                        num2 = 0;
                        break;
                    case 99:
                    case 100:
                        num3 = 98;
                        num2 = 1;
                        break;
                    default:
                        if (num != 117)
{
                            if (num - 118 <= 1)
{
                                num3 = 117;
                                num2 = 1;
                            }
                        }
                        else
{
                            num3 = 119;
                            num2 = 0;
                        }
                        break;
                    }
                }
            }
            else if (num <= 454)
            {
                if (num != 134)
                {
                    if (num - 135 > 1)
                    {
                        if (num == 454)
{
                            num3 = 459;
                            num2 = 0;
                        }
                    }
                    else
                    {
                        num3 = 134;
                        num2 = 1;
                    }
                }
                else
                {
                    num3 = 136;
                    num2 = 0;
                }
            }
            else if (num <= 515)
            {
                if (num - 455 > 4)
                {
                    switch (num)
                    {
                    case 510:
                        num3 = 512;
                        num2 = 0;
                        break;
                    case 511:
                    case 512:
                        num3 = 510;
                        num2 = 1;
                        break;
                    case 513:
                        num3 = 515;
                        num2 = 0;
                        break;
                    case 514:
                    case 515:
                        num3 = 513;
                        num2 = 1;
                        break;
                    }
                }
                else
                {
                    num3 = 454;
                    num2 = 1;
                }
            }
            else if (num != 621)
            {
                if (num - 622 <= 1)
                {
                    num3 = 621;
                    num2 = 1;
                }
            }
            else
            {
                num3 = 623;
                num2 = 0;
            }
            if (num2 == -1)
            {
                pos = Main.npc[i].Center;
                index = i;
                return true;
            }
            if (seekHead && num2 == 1)
            {
                index = -1;
                pos = Vector2.Zero;
                return false;
            }
            Vector2 vector = Main.npc[i].Center;
            int num4 = -1;
            float num5 = -1f;
            int num6 = -1;
            Vector2 center = Main.player[Main.myPlayer].Center;
            int num7 = (int)Main.npc[i].ai[num2];
            int num8 = 0;
            while (num7 >= 0 && num7 < Main.maxNPCs && ++num8 < Main.maxNPCs / 2 && Main.npc[num7].active)
            {
                if (!averageDirection && (num6 == -1 || Main.npc[num7].Distance(center) < num5))
                {
                    num5 = Main.npc[num7].Distance(center);
                    num6 = num7;
                }
                if (Main.npc[num7].type == num3)
                {
                    num4 = num7;
                    break;
                }
                num7 = (int)Main.npc[num7].ai[num2];
            }
            if (num4 >= 0)
            {
                if (!averageDirection)
                {
                    pos = Main.npc[num6].Center;
                    index = num6;
                }
                else
                {
                    vector += Main.npc[num4].Center;
                    pos = vector / 2f;
                    index = num4;
                }
                return true;
            }
            pos = Vector2.Zero;
            index = -1;
            return false;
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.Entity.Center, Terraria.Entity.Distance(), System.index, int, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.npc, Terraria.Main.player, Terraria.NPC.type, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameInput.LockOnHelper.Draw(), and Terraria.Main.DrawInterface_14_EntityHealthBars().