Terraria Decompiled: Terraria.NPC.AI_001_Slimes
AI_001_Slimes()
void Terraria.NPC.AI_001_Slimes () inline private
Definition at line 57554 of file NPC.cs.
        {
            if (this.type == 1 && this.ai[1] == 75f)
            {
                float num = 0.3f;
                Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.8f * num, 0.7f * num, 0.1f * num);
                if (Main.rand.Next(12) == 0)
                {
                    Dust dust = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)this.height * 0.2f) + Main.rand.NextVector2CircularEdge((float)this.width, (float)this.height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 228, new Vector2?(new Vector2(0f, -Main.rand.NextFloat() * 0.3f - 1.5f)), 127, default(Color), 1f);
                    dust.scale = 0.5f;
                    dust.fadeIn = 1.1f;
                    dust.noGravity = true;
                    dust.noLight = true;
                }
            }
            if (NPCID.Sets.SlimeCanContainItems[this.type] && this.ai[1] == 0f && Main.netMode != 1 && this.value > 0f)
            {
                this.ai[1] = -1f;
                int num2 = 20;
                int num3 = 40;
                int num4 = 1;
                if (WorldGen.Skyblock.lowTiles)
                {
                    num3 = 20;
                    num4 += 4;
                    num2 = 15;
                    if (this.netID == -6)
                    {
                        num4 += 5;
                    }
                }
                else if (this.netID == -6)
                {
                    num4 += 4;
                }
                if (Main.slimeRain)
                {
                    num4 += 2;
                }
                int num5 = 0;
                while (num5 < num4 && this.ai[1] == -1f)
                {
                    if (this.type == 59)
                    {
                        if (Main.remixWorld && Main.rand.Next(num2) == 0)
{
                            int num6 = this.AI_001_Slimes_GenerateItemInsideBody(this.ai[0] == -999f);
                            this.ai[1] = (float)num6;
                        }
                        else if (WorldGen.Skyblock.noHellstone && NPC.downedBoss3 && Main.rand.Next(15) == 0)
{
                            this.ai[1] = 174f;
                        }
                    }
                    else if ((double)(this.position.Y / 16f) > Main.worldSurface && (this.type == 147 || this.type == 184))
                    {
                        if (WorldGen.Skyblock.lowTiles)
{
                            if (Main.rand.Next(num3) == 0)
{
                                if (Main.rand.Next(2) == 0)
{
                                    this.ai[1] = 1103f;
                                }
                                else
{
                                    this.ai[1] = 593f;
                                }
                            }
                        }
                        else if (Main.rand.Next(num3) == 0)
{
                            if (Main.rand.Next(2) == 0)
{
                                this.ai[1] = 1103f;
                            }
                            else
{
                                this.ai[1] = 593f;
                            }
                        }
                    }
                    else if (this.type == 537)
                    {
                        if (WorldGen.Skyblock.noFossils && Main.rand.Next(5) == 0)
{
                            this.ai[1] = 3347f;
                        }
                    }
                    else if (this.type == 1 && this.netID != -5 && this.netID != -4)
                    {
                        int num7 = 500;
                        if (Main.noTrapsWorld)
{
                            num7 = 20;
                        }
                        else if (Main.getGoodWorld)
{
                            num7 = 100;
                        }
                        else if ((double)base.Center.Y < Main.worldSurface * 16.0)
{
                            num7 = -1;
                        }
                        if (WorldGen.isThisInTheRockLayer((int)(this.position.Y / 16f)) && (WorldGen.Skyblock.noLifeCrystals || WorldGen.Skyblock.lowTiles) && !NPC.AnyLifeCrystalSlimes() && Main.rand.Next(200) == 0)
{
                            this.ai[1] = 29f;
                        }
                        else if (WorldGen.Skyblock.lowTiles && (double)(this.position.Y / 16f) > Main.worldSurface && Main.rand.Next(1000) == 0)
{
                            this.ai[1] = (float)Item.GetRandomVoiceItem();
                        }
                        else if (BirthdayParty.GenuineParty && (double)base.Center.Y < Main.worldSurface * 16.0)
{
                            if (Main.rand.Next(2) == 0)
{
                                this.ai[1] = (float)Main.rand.Next(3736, 3739);
                            }
                            else
{
                                this.ai[1] = 1345f;
                            }
                        }
                        else if (this.netID == -10 && Main.rand.Next(20) == 0)
{
                            int num8;
                            if (Main.notTheBeesWorld)
{
                                num8 = Main.rand.Next(4);
                            }
                            else
{
                                num8 = Main.rand.Next(3);
                            }
                            switch (num8)
{
                            default:
                                num8 = 1124;
                                break;
                            case 1:
                                num8 = 1125;
                                break;
                            case 2:
                                num8 = 314;
                                break;
                            case 3:
                                num8 = 5395;
                                break;
                            }
                            this.ai[1] = (float)num8;
                        }
                        else if (Main.rand.Next(num2) == 0)
{
                            int num9 = this.AI_001_Slimes_GenerateItemInsideBody(this.ai[0] == -999f);
                            this.ai[1] = (float)num9;
                        }
                        else if (Main.rand.Next(num3) == 0)
{
                            if ((double)(this.position.Y / 16f) <= Main.worldSurface)
{
                                if (WorldGen.Skyblock.lowTiles && (Main.moonPhase == 0 || Main.rand.Next(2) == 0))
{
                                    if (Main.rand.Next(2) == 0)
{
                                        if (Main.rand.Next(50) == 0)
{
                                            this.ai[1] = 194f;
                                        }
                                        else if (Main.rand.Next(10) == 0)
{
                                            this.ai[1] = 195f;
                                        }
                                        else
{
                                            this.ai[1] = 62f;
                                        }
                                    }
                                    else
{
                                        this.ai[1] = 27f;
                                    }
                                }
                                else
{
                                    this.ai[1] = 751f;
                                }
                            }
                            else if (!WorldGen.isThisInTheRockLayer((int)(this.position.Y / 16f)))
{
                                int num10;
                                switch (Main.rand.Next(3))
{
                                default:
                                    num10 = 2;
                                    break;
                                case 1:
                                    num10 = 3;
                                    break;
                                case 2:
                                    num10 = 9;
                                    break;
                                }
                                this.ai[1] = (float)num10;
                            }
                            else if (Main.rand.Next(10) == 0)
{
                                this.ai[1] = 3609f;
                            }
                            else if (WorldGen.Skyblock.lowTiles && Main.hardMode && Main.rand.Next(2) == 0)
{
                                int num11;
                                switch (Main.rand.Next(6))
{
                                default:
                                    num11 = 364;
                                    break;
                                case 1:
                                    num11 = 1104;
                                    break;
                                case 2:
                                    num11 = 365;
                                    break;
                                case 3:
                                    num11 = 1105;
                                    break;
                                case 4:
                                    num11 = 366;
                                    break;
                                case 5:
                                    num11 = 1106;
                                    break;
                                }
                                this.ai[1] = (float)num11;
                            }
                            else
{
                                int num12;
                                switch (Main.rand.Next(4))
{
                                default:
                                    num12 = 3;
                                    break;
                                case 1:
                                    num12 = 150;
                                    break;
                                case 2:
                                    num12 = 3086;
                                    break;
                                case 3:
                                    num12 = 3081;
                                    break;
                                }
                                this.ai[1] = (float)num12;
                            }
                        }
                        else if (num7 > 0 && Main.rand.Next(num7) == 0)
{
                            this.ai[1] = 539f;
                        }
                        else if (Main.getGoodWorld && (double)(this.position.Y / 16f) > Main.worldSurface && Main.rand.Next(num7) == 0)
{
                            this.ai[1] = 147f;
                        }
                        else if (num5 == 0 && Main.remixWorld && this.ai[0] != -999f && Main.rand.Next(3) == 0)
{
                            this.ai[1] = 75f;
                        }
                        else if (Main.vampireSeed && !Main.remixWorld && Main.rand.Next(13) == 0 && (double)(this.position.Y / 16f) > Main.worldSurface)
{
                            this.ai[1] = 9f;
                        }
                    }
                    num5++;
                }
                this.netUpdate = true;
            }
            if (this.type == 1)
            {
                bool flag = false;
                int num13 = (int)(base.Left.X / 16f);
                while ((float)num13 <= base.Right.X / 16f)
                {
                    int num14 = (int)((base.Bottom.Y + 1f) / 16f);
                    if (WorldGen.SolidTile3(num13, num14) && Main.tile[num13, num14].color() > 0 && Main.tile[num13, num14].color() != 30)
                    {
                        Color color = WorldGen.paintColor((int)Main.tile[num13, num14].color());
                        this.color = new Color((int)((this.color.R * 19 + color.R) / 20), (int)((this.color.G * 19 + color.G) / 20), (int)((this.color.B * 19 + color.B) / 20), (int)((this.color.A * 19 + 100) / 20));
                        flag = true;
                    }
                    num13++;
                }
                if (this.ai[1] > 0f && !flag)
                {
                    if (this.ai[1] == 751f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 185) / 20), (int)((this.color.G * 19 + 235) / 20), (int)((this.color.B * 19 + byte.MaxValue) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 2f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 169) / 20), (int)((this.color.G * 19 + 125) / 20), (int)((this.color.B * 19 + 93) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 3f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 128) / 20), (int)((this.color.G * 19 + 128) / 20), (int)((this.color.B * 19 + 128) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 9f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 229) / 20), (int)((this.color.G * 19 + 149) / 20), (int)((this.color.B * 19 + 93) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 150f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 193) / 20), (int)((this.color.G * 19 + 202) / 20), (int)((this.color.B * 19 + 203) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 3086f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 59) / 20), (int)((this.color.G * 19 + 28) / 20), (int)((this.color.B * 19 + 136) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 3081f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 138) / 20), (int)((this.color.G * 19 + 145) / 20), (int)((this.color.B * 19 + 170) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 147f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 189) / 20), (int)((this.color.G * 19 + 159) / 20), (int)((this.color.B * 19 + 139) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 29f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 220) / 20), (int)((this.color.G * 19 + 36) / 20), (int)((this.color.B * 19 + 117) / 20), (int)((this.color.A * 19 + 125) / 20));
                    }
                    else if (this.ai[1] == 3609f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 232) / 20), (int)((this.color.G * 19 + 172) / 20), (int)((this.color.B * 19 + 162) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 3736f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + byte.MaxValue) / 20), (int)((this.color.G * 19 + 66) / 20), (int)((this.color.B * 19 + 152) / 20), (int)((this.color.A * 19 + 125) / 20));
                    }
                    else if (this.ai[1] == 3737f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 179) / 20), (int)((this.color.G * 19 + 132) / 20), (int)((this.color.B * 19 + byte.MaxValue) / 20), (int)((this.color.A * 19 + 125) / 20));
                    }
                    else if (this.ai[1] == 3738f)
                    {
                        this.color = new Color((int)(this.color.R * 19 / 20), (int)((this.color.G * 19 + 206) / 20), (int)((this.color.B * 19 + 180) / 20), (int)((this.color.A * 19 + 125) / 20));
                    }
                    else if (this.ai[1] == 1345f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 200) / 20), (int)((this.color.G * 19 + 200) / 20), (int)((this.color.B * 19 + 200) / 20), (int)((this.color.A * 19 + 50) / 20));
                    }
                    else if (this.ai[1] == 5395f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 198) / 20), (int)((this.color.G * 19 + 72) / 20), (int)((this.color.B * 19 + 12) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 1124f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + byte.MaxValue) / 20), (int)((this.color.G * 19 + 158) / 20), (int)((this.color.B * 19 + 49) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 1125f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + byte.MaxValue) / 20), (int)((this.color.G * 19 + 156) / 20), (int)((this.color.B * 19 + 12) / 20), (int)((this.color.A * 19 + 150) / 20));
                    }
                    else if (this.ai[1] == 314f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 79) / 20), (int)((this.color.G * 19 + 163) / 20), (int)((this.color.B * 19 + 241) / 20), (int)((this.color.A * 19 + 75) / 20));
                    }
                    else if (this.ai[1] == 364f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 37) / 20), (int)((this.color.G * 19 + 118) / 20), (int)((this.color.B * 19 + 172) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 1104f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 227) / 20), (int)((this.color.G * 19 + 52) / 20), (int)((this.color.B * 19 + 14) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 365f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 22) / 20), (int)((this.color.G * 19 + 119) / 20), (int)((this.color.B * 19 + 125) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 1105f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 205) / 20), (int)((this.color.G * 19 + 30) / 20), (int)((this.color.B * 19 + 199) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 366f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 173) / 20), (int)((this.color.G * 19 + 15) / 20), (int)((this.color.B * 19 + 13) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 1106f)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 91) / 20), (int)((this.color.G * 19 + 90) / 20), (int)((this.color.B * 19 + 119) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                    else if (this.ai[1] == 8f && Main.getGoodWorld)
                    {
                        this.color = new Color((int)((this.color.R * 19 + 253) / 20), (int)((this.color.G * 19 + 62) / 20), (int)((this.color.B * 19 + 3) / 20), (int)((this.color.A * 19 + 100) / 20));
                    }
                }
            }
            bool flag2 = false;
            if (NPCID.Sets.SlimeCanContainItems[this.type] && this.ai[1] > 0f)
            {
                if (this.ai[1] == 539f && Main.netMode != 1)
                {
                    int num15 = 300;
                    if (Main.noTrapsWorld)
                    {
                        num15 -= 120;
                    }
                    if (Main.getGoodWorld)
                    {
                        num15 -= 120;
                    }
                    if (Main.rand.Next(num15) == 0 && this.target >= 0 && Main.player[this.target].active && !Main.player[this.target].dead && !Main.player[this.target].npcTypeNoAggro[this.type] && Collision.CanHit(this, Main.player[this.target]))
                    {
                        Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), (float)((int)base.Center.X), base.Center.Y, (float)(this.direction * 12), 0f, 1073, 20, 2f, Main.myPlayer, 0f, 0f, 0f, null);
                    }
                }
                else if (this.ai[1] == 364f || this.ai[1] == 1104f || this.ai[1] == 365f || this.ai[1] == 1105f || this.ai[1] == 366f || this.ai[1] == 1106f)
                {
                    this.lavaImmune = true;
                    this.defense = this.defDefense + 30;
                    this.damage = this.defDamage * 3;
                    this.buffImmune[70] = false;
                    this.buffImmune[20] = false;
                    this.knockBackResist = 0f;
                    if (this.lifeMax == this.defLifeMax)
                    {
                        this.position.X = this.position.X + (float)(this.width / 2);
                        this.position.Y = this.position.Y + (float)this.height;
                        this.scale *= 1.2f;
                        this.width = (int)((float)this.width * this.scale);
                        this.height = (int)((float)this.height * this.scale);
                        this.position.X = this.position.X - (float)(this.width / 2);
                        this.position.Y = this.position.Y - (float)this.height;
                        if (this.life == this.lifeMax)
{
                            this.life = this.defLifeMax * 3;
                        }
                        this.lifeMax = this.defLifeMax * 3;
                    }
                    if (base.Bottom.Y < Main.player[this.target].Top.Y && base.Right.X >= Main.player[this.target].Left.X && base.Left.X <= Main.player[this.target].Right.X && Collision.CanHitWithCheck(this, Main.player[this.target], new Utils.TileActionAttempt(DelegateMethods.NotSolidOrPlatforms)))
                    {
                        flag2 = true;
                        this.direction = 0;
                        this.velocity.X = this.velocity.X * 0.5f;
                        if (this.velocity.Y < 0f)
{
                            this.velocity.Y = 0f;
                        }
                        this.velocity.Y = this.velocity.Y + NPC.gravity;
                    }
                    else
                    {
                        if (this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y + NPC.gravity;
                        }
                        if (this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y - NPC.gravity * 0.75f;
                        }
                    }
                    Lighting.AddLight(this.position, (float)this.color.R / 500f, (float)this.color.G / 500f, (float)this.color.B / 500f);
                    this.extraValue = 0;
                    if (this.ai[1] == 364f)
                    {
                        this._givenName = Language.GetTextValue("SpecialNPCName.CobaltSlime");
                    }
                    else if (this.ai[1] == 1104f)
                    {
                        this._givenName = Language.GetTextValue("SpecialNPCName.PalladiumSlime");
                    }
                    else if (this.ai[1] == 365f)
                    {
                        this._givenName = Language.GetTextValue("SpecialNPCName.MythrilSlime");
                    }
                    else if (this.ai[1] == 1105f)
                    {
                        this._givenName = Language.GetTextValue("SpecialNPCName.OrichalcumSlime");
                    }
                    else if (this.ai[1] == 366f)
                    {
                        this._givenName = Language.GetTextValue("SpecialNPCName.AdamantiteSlime");
                    }
                    else if (this.ai[1] == 1106f)
                    {
                        this._givenName = Language.GetTextValue("SpecialNPCName.TitaniumSlime");
                    }
                }
                else if (this.ai[1] == 2f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.DirtSlime");
                    if (this.velocity.Y == 0f)
                    {
                        this.ai[0] += 9f;
                    }
                }
                else if (this.ai[1] == 9f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.WoodSlime");
                    this.defense = this.defDefense + 16;
                }
                else if (this.ai[1] == 3f && this.velocity.Y != 0f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.StoneSlime");
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y + NPC.gravity * 2f;
                    }
                }
                else if (this.ai[1] == 751f && this.velocity.Y != 0f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.CloudSlime");
                    this.velocity.Y = this.velocity.Y - NPC.gravity * 0.6f;
                }
                else if (this.ai[1] == 150f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.WebSlime");
                    if (Main.netMode != 1 && Main.rand.Next(120) == 0)
                    {
                        int num16 = Main.rand.Next((int)(base.Left.X / 16f), (int)(base.Right.X / 16f) + 1);
                        int num17 = Main.rand.Next((int)(base.Top.Y / 16f), (int)(base.Bottom.Y / 16f) + 1);
                        if (!Main.tile[num16, num17].active())
{
                            WorldGen.PlaceTile(num16, num17, 51, true, false, -1, 0);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, num16, num17, TileChangeType.None);
                            }
                        }
                    }
                }
                else if (this.ai[1] == 3086f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.GraniteSlime");
                    this.defense = this.defDefense + 16;
                    this.knockBackResist = 0f;
                }
                else if (this.ai[1] == 3081f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.MarbleSlime");
                    this.defense = this.defDefense + 16;
                    this.knockBackResist = 0f;
                }
                else if (this.ai[1] == 147f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.SpikeSlime");
                    this.damage = this.defDamage * 2;
                }
                else if (this.ai[1] == 8f && Main.getGoodWorld)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.TorchSlime");
                    this.AddBuff(24, 216000, false);
                    this.buffImmune[323] = true;
                    this.buffImmune[44] = true;
                    this.buffImmune[324] = true;
                    this.buffImmune[39] = true;
                }
                else if (this.ai[1] == 5395f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.PooSlime");
                    if (Main.rand.Next(30) == 0)
                    {
                        Vector2 vector = Main.rand.NextVector2FromRectangle(base.Hitbox);
                        ParticleOrchestrator.RequestParticleSpawn(true, ParticleOrchestraType.PooFly, new ParticleOrchestraSettings
{
                            PositionInWorld = vector + this.velocity * -1f
                        }, null);
                    }
                }
                else if (this.ai[1] == 1124f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.HiveSlime");
                    if (Main.netMode != 1 && Main.rand.Next(60) == 7 && this.target >= 0 && Collision.CanHit(this, Main.player[this.target]))
                    {
                        int num18 = Main.rand.Next(210, 212);
                        int num19 = NPC.NewNPC(this.GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, num18, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num19].CanBeReplacedByOtherNPCs = true;
                        Main.npc[num19].velocity *= 0f;
                        Main.npc[num19].velocity.Y = -1f;
                        Main.npc[num19].velocity.X = (float)Main.rand.Next(-20, 21) * 0.1f;
                        Main.npc[num19].velocity.Normalize();
                        Main.npc[num19].velocity *= 3f;
                        Main.npc[num19].localAI[0] = 60f;
                        Main.npc[num19].ai[1] = 60f;
                        Main.npc[num19].netUpdate = true;
                    }
                }
                else if (this.ai[1] == 1125f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.HoneySlime");
                }
                else if (this.ai[1] == 314f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.HerbSlime");
                    if (Main.rand.Next(60) == 0)
                    {
                        Dust.NewDust(this.position, this.width, this.height, 41, 0f, 0f, 250, default(Color), 0.8f);
                    }
                    Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), 0.4f, 0.9f, 1f);
                    if (Main.netMode != 1 && this.velocity.Y == 0f && this.localAI[3] < 5f && Main.rand.Next(180) == 0)
                    {
                        int num20 = (int)(base.Center.X / 16f);
                        int num21 = (int)((base.Bottom.Y - 8f) / 16f);
                        if (WorldGen.InWorld(num20, num21, 0) && !Main.tile[num20, num21].active())
{
                            WorldGen.PlaceSuitableHerbHere(num20, num21 + 1);
                            if (Main.tile[num20, num21].active())
{
                                this.localAI[3] += 1f;
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, num20, num21, TileChangeType.None);
                                }
                            }
                        }
                    }
                }
                else if (this.ai[1] == 3736f || this.ai[1] == 3737f || this.ai[1] == 3738f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.BalloonSlime");
                    if (this.collideY && this.oldVelocity.Y > 4f)
                    {
                        this.velocity.Y = -this.oldVelocity.Y * 0.7f;
                    }
                }
                else if (this.ai[1] == 1345f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.ConfettiSlime");
                    if (Main.rand.Next(30) == 0)
                    {
                        int num22 = Main.rand.Next(139, 143);
                        int num23 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, num22, 0f, -10f, 0, default(Color), 1.2f);
                        Main.dust[num23].scale *= 1f + (float)Main.rand.Next(-30, 31) * 0.01f;
                        Dust dust2 = Main.dust[num23];
                        dust2.velocity.X = dust2.velocity.X + (float)Main.rand.Next(-50, 51) * 0.05f;
                    }
                    if (Main.rand.Next(60) == 0)
                    {
                        int num24 = Main.rand.Next(276, 283);
                        int num25 = Gore.NewGore(this.position, new Vector2(0f, -10f), num24, 1f);
                        Main.gore[num25].scale *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                        Gore gore = Main.gore[num25];
                        gore.velocity.X = gore.velocity.X + (float)Main.rand.Next(-50, 51) * 0.05f;
                    }
                }
                else if (this.ai[1] == 1103f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.SlushSlime");
                    if (Main.rand.Next(3) == 0)
                    {
                        this.position += this.netOffset;
                        Dust dust3 = Dust.NewDustDirect(new Vector2(this.position.X - 2f, this.position.Y - 2f), this.width + 4, this.height + 4, 135, this.velocity.X * 0.4f, this.velocity.Y * 0.4f, 100, default(Color), 2.5f);
                        dust3.noGravity = true;
                        dust3.velocity *= 1.8f;
                        Dust dust4 = dust3;
                        dust4.velocity.Y = dust4.velocity.Y - 0.75f;
                        if (Main.rand.Next(4) == 0)
{
                            dust3.noGravity = false;
                            dust3.scale *= 0.5f;
                        }
                        this.position -= this.netOffset;
                    }
                }
                else if (this.ai[1] == 593f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.SnowSlime");
                    if (Main.rand.Next(3) == 0)
                    {
                        this.position += this.netOffset;
                        Dust dust5 = Dust.NewDustDirect(new Vector2(this.position.X - 2f, this.position.Y - 2f), this.width + 4, this.height + 4, 135, this.velocity.X * 0.4f, this.velocity.Y * 0.4f, 100, default(Color), 2.5f);
                        dust5.noGravity = true;
                        dust5.velocity *= 1.8f;
                        Dust dust6 = dust5;
                        dust6.velocity.Y = dust6.velocity.Y - 0.75f;
                        if (Main.rand.Next(4) == 0)
{
                            dust5.noGravity = false;
                            dust5.scale *= 0.5f;
                        }
                        this.position -= this.netOffset;
                    }
                }
                else if (this.ai[1] == 3347f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.FossilSlime");
                    this.alpha = 125;
                    this.ai[0] += 1f;
                    this.damage = this.defDamage + 10;
                }
                else if (this.ai[1] == 29f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.HeartSlime");
                    this.defense = this.defDefense + 4;
                    if (this.lifeMax == this.defLifeMax)
                    {
                        if (this.life == this.lifeMax)
{
                            this.life = this.defLifeMax * 2;
                        }
                        this.lifeMax = this.defLifeMax * 2;
                    }
                }
                else if (this.ai[1] == 3609f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.ConveyorSlime");
                    this.defense = this.defDefense + 8;
                    this.damage = this.defDamage + 6;
                }
                else if (this.ai[1] == 174f)
                {
                    this._givenName = Language.GetTextValue("SpecialNPCName.HellSlime");
                    this.defense = this.defDefense + 14;
                    this.damage = this.defDamage + 20;
                    if (this.lifeMax == this.defLifeMax)
                    {
                        this.knockBackResist /= 3f;
                        this.life *= 2;
                        this.lifeMax *= 2;
                        float num26 = 1.2f;
                        this.scale *= num26;
                        this.position.X = this.position.X + (float)(this.width / 2);
                        this.position.Y = this.position.Y + (float)this.height;
                        this.width = (int)((float)this.width * num26);
                        this.height = (int)((float)this.height * num26);
                        this.position.X = this.position.X - (float)(this.width / 2);
                        this.position.Y = this.position.Y - (float)this.height;
                    }
                    this.position += this.netOffset;
                    int num27 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 6, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 1.7f);
                    Main.dust[num27].scale *= 0.6f;
                    Main.dust[num27].velocity *= 2f;
                    Dust dust7 = Main.dust[num27];
                    dust7.velocity.Y = dust7.velocity.Y - 2f;
                    this.position -= this.netOffset;
                    num27 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 31, 0f, 0f, 50, default(Color), 1f);
                    Main.dust[num27].scale = 0.1f + (float)Main.rand.Next(5) * 0.1f;
                    Main.dust[num27].fadeIn = 1.5f + (float)Main.rand.Next(5) * 0.1f;
                    Dust dust8 = Main.dust[num27];
                    dust8.velocity.Y = dust8.velocity.Y - 5f;
                    Main.dust[num27].noGravity = true;
                }
                else if (this.ai[1] > 0f && this.ai[1] < (float)ItemID.Count && ItemID.Sets.IsAVoiceChangeItem[(int)this.ai[1]] && this.lifeMax == this.defLifeMax)
                {
                    if (this.life == this.lifeMax)
                    {
                        this.life = this.defLifeMax * 3;
                    }
                    this.lifeMax = this.defLifeMax * 3;
                }
            }
            if (this.type == 1 && this.direction == 0 && !flag2)
            {
                this.direction = 1;
                this.netUpdate = true;
            }
            if (this.ai[0] == -999f)
            {
                this.frame.Y = 0;
                this.frameCounter = 0.0;
                this.rotation = 0f;
                return;
            }
            if (this.type == 244)
            {
                float num28 = (float)Main.DiscoR / 255f;
                float num29 = (float)Main.DiscoG / 255f;
                float num30 = (float)Main.DiscoB / 255f;
                num28 *= 1f;
                num29 *= 1f;
                num30 *= 1f;
                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), num28, num29, num30);
                this.AI_001_SetRainbowSlimeColor();
            }
            bool flag3 = false;
            if (!Main.dayTime || this.life != this.lifeMax || (double)this.position.Y > Main.worldSurface * 16.0 || Main.slimeRain)
            {
                flag3 = true;
            }
            if (Main.remixWorld && this.type == 59 && this.life == this.lifeMax)
            {
                flag3 = false;
            }
            if (this.type == 81)
            {
                flag3 = true;
                if (Main.rand.Next(30) == 0)
                {
                    this.position += this.netOffset;
                    int num31 = Dust.NewDust(this.position, this.width, this.height, 14, 0f, 0f, this.alpha, this.color, 1f);
                    Main.dust[num31].velocity *= 0.3f;
                    this.position -= this.netOffset;
                }
            }
            if ((this.type == 377 || this.type == 446) && this.target != 255 && !Main.player[this.target].dead && Vector2.Distance(base.Center, Main.player[this.target].Center) <= 200f && !this.wet)
            {
                flag3 = true;
            }
            if (this.type == 183)
            {
                flag3 = true;
            }
            if (this.type == 304)
            {
                flag3 = true;
            }
            if (this.type == 667)
            {
                flag3 = true;
            }
            if (this.type == 244)
            {
                flag3 = true;
                this.ai[0] += 2f;
            }
            if (this.type == 147 && Main.rand.Next(10) == 0)
            {
                this.position += this.netOffset;
                int num32 = Dust.NewDust(this.position, this.width, this.height, 76, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num32].noGravity = true;
                Main.dust[num32].velocity *= 0.1f;
                this.position -= this.netOffset;
            }
            if (this.type == 667)
            {
                Color color2 = new Color(204, 181, 72, 255);
                Lighting.AddLight((int)(base.Center.X / 16f), (int)(base.Center.Y / 16f), (float)color2.R / 255f * 1.1f, (float)color2.G / 255f * 1.1f, (float)color2.B / 255f * 1.1f);
                if (this.velocity.Length() > 1f || Main.rand.Next(4) != 0)
                {
                    int num33 = 8;
                    Vector2 vector2 = this.position + new Vector2((float)(-(float)num33), (float)(-(float)num33));
                    int num34 = this.width + num33 * 2;
                    int num35 = this.height + num33 * 2;
                    this.position += this.netOffset;
                    int num36 = Dust.NewDust(vector2, num34, num35, 246, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num36].noGravity = true;
                    Main.dust[num36].noLightEmittance = true;
                    Main.dust[num36].velocity *= 0.2f;
                    Main.dust[num36].scale = 1.5f;
                    this.position -= this.netOffset;
                }
            }
            if (this.type == 676)
            {
                Lighting.AddLight(base.Center, 23);
                if ((this.velocity.Length() > 1f && Main.rand.Next(3) == 0) || Main.rand.Next(5) == 0)
                {
                    Dust dust9 = Dust.NewDustPerfect(Main.rand.NextVector2FromRectangle(base.Hitbox), 306, null, 0, default(Color), 1f);
                    dust9.noGravity = true;
                    dust9.noLightEmittance = true;
                    dust9.alpha = 127;
                    dust9.color = Main.hslToRgb(((float)Main.timeForVisualEffects / 300f + Main.rand.NextFloat() * 0.1f) % 1f, 1f, 0.65f, byte.MaxValue);
                    dust9.color.A = 0;
                    dust9.velocity = dust9.position - base.Center;
                    dust9.velocity *= 0.1f;
                    Dust dust10 = dust9;
                    dust10.velocity.X = dust10.velocity.X * 0.25f;
                    if (dust9.velocity.Y > 0f)
                    {
                        Dust dust11 = dust9;
                        dust11.velocity.Y = dust11.velocity.Y * -1f;
                    }
                    dust9.scale = Main.rand.NextFloat() * 0.3f + 0.5f;
                    dust9.fadeIn = 0.9f;
                    dust9.position += this.netOffset;
                }
            }
            if (this.type == 184)
            {
                if (Main.rand.Next(8) == 0)
                {
                    this.position += this.netOffset;
                    int num37 = Dust.NewDust(this.position - this.velocity, this.width, this.height, 76, 0f, 0f, 0, default(Color), 1f);
                    Main.dust[num37].noGravity = true;
                    Main.dust[num37].velocity *= 0.15f;
                    this.position -= this.netOffset;
                }
                flag3 = true;
                if (this.localAI[0] > 0f)
                {
                    this.localAI[0] -= 1f;
                }
                if (!this.wet && Main.player[this.target].active && !Main.player[this.target].dead && !Main.player[this.target].npcTypeNoAggro[this.type])
                {
                    Vector2 vector3 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num38 = Main.player[this.target].position.X + (float)Main.player[this.target].width * 0.5f - vector3.X;
                    float num39 = Main.player[this.target].position.Y - vector3.Y;
                    float num40 = (float)Math.Sqrt((double)(num38 * num38 + num39 * num39));
                    if (Main.expertMode && num40 < 120f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            for (int i = 0; i < 5; i++)
{
                                Vector2 vector4 = new Vector2((float)(i - 2), -4f);
                                vector4.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                                vector4.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                                vector4.Normalize();
                                vector4 *= 4f + (float)Main.rand.Next(-50, 51) * 0.01f;
                                int attackDamage_ForProjectiles = this.GetAttackDamage_ForProjectiles(9f, 9f);
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector3.X, vector3.Y, vector4.X, vector4.Y, 174, attackDamage_ForProjectiles, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                                this.localAI[0] = 30f;
                            }
                        }
                    }
                    else if (num40 < 200f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            num39 = Main.player[this.target].position.Y - vector3.Y - (float)Main.rand.Next(0, 200);
                            num40 = (float)Math.Sqrt((double)(num38 * num38 + num39 * num39));
                            num40 = 4.5f / num40;
                            num38 *= num40;
                            num39 *= num40;
                            this.localAI[0] = 50f;
                            Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector3.X, vector3.Y, num38, num39, 174, 9, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        }
                    }
                }
            }
            if (this.type == 535)
            {
                flag3 = true;
                if (this.localAI[0] > 0f)
                {
                    this.localAI[0] -= 1f;
                }
                if (!this.wet && Main.player[this.target].active && !Main.player[this.target].dead && !Main.player[this.target].npcTypeNoAggro[this.type])
                {
                    Vector2 vector5 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num41 = Main.player[this.target].position.X + (float)Main.player[this.target].width * 0.5f - vector5.X;
                    float num42 = Main.player[this.target].position.Y - vector5.Y;
                    float num43 = (float)Math.Sqrt((double)(num41 * num41 + num42 * num42));
                    if (Main.expertMode && num43 < 120f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            for (int j = 0; j < 5; j++)
{
                                Vector2 vector6 = new Vector2((float)(j - 2), -4f);
                                vector6.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                                vector6.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                                vector6.Normalize();
                                vector6 *= 4f + (float)Main.rand.Next(-50, 51) * 0.01f;
                                int attackDamage_ForProjectiles2 = this.GetAttackDamage_ForProjectiles(9f, 9f);
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector5.X, vector5.Y, vector6.X, vector6.Y, 605, attackDamage_ForProjectiles2, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                                this.localAI[0] = 30f;
                            }
                        }
                    }
                    else if (num43 < 200f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            num42 = Main.player[this.target].position.Y - vector5.Y - (float)Main.rand.Next(0, 200);
                            num43 = (float)Math.Sqrt((double)(num41 * num41 + num42 * num42));
                            num43 = 4.5f / num43;
                            num41 *= num43;
                            num42 *= num43;
                            this.localAI[0] = 50f;
                            Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector5.X, vector5.Y, num41, num42, 605, 9, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        }
                    }
                }
            }
            if (this.type == 658)
            {
                flag3 = true;
                if (this.localAI[0] > 0f)
                {
                    this.localAI[0] -= 1f;
                }
                if (!this.wet && Main.player[this.target].active && !Main.player[this.target].dead && !Main.player[this.target].npcTypeNoAggro[this.type])
                {
                    Player player = Main.player[this.target];
                    Vector2 center = base.Center;
                    float num44 = player.Center.X - center.X;
                    float num45 = player.Center.Y - center.Y;
                    float num46 = (float)Math.Sqrt((double)(num44 * num44 + num45 * num45));
                    int num47 = NPC.CountNPCS(658);
                    if (Main.expertMode && num47 < 5 && Math.Abs(num44) < 500f && Math.Abs(num45) < 550f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            for (int k = 0; k < 3; k++)
{
                                Vector2 vector7 = new Vector2((float)(k - 1), -4f);
                                vector7.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                                vector7.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.005f;
                                vector7.Normalize();
                                vector7 *= 6f + (float)Main.rand.Next(-50, 51) * 0.01f;
                                if (num46 > 350f)
{
                                    vector7 *= 2f;
                                }
                                else if (num46 > 250f)
{
                                    vector7 *= 1.5f;
                                }
                                int attackDamage_ForProjectiles_MultiLerp = this.GetAttackDamage_ForProjectiles_MultiLerp(15f, 17f, 20f);
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), center.X, center.Y, vector7.X, vector7.Y, 920, attackDamage_ForProjectiles_MultiLerp, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                                this.localAI[0] = 25f;
                                if (num47 > 4)
{
                                    break;
                                }
                            }
                        }
                    }
                    else if (Math.Abs(num44) < 500f && Math.Abs(num45) < 550f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        float num48 = num46;
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            num45 = Main.player[this.target].position.Y - center.Y - (float)Main.rand.Next(0, 200);
                            num46 = (float)Math.Sqrt((double)(num44 * num44 + num45 * num45));
                            num46 = 4.5f / num46;
                            num46 *= 2f;
                            if (num48 > 350f)
{
                                num46 *= 2f;
                            }
                            else if (num48 > 250f)
{
                                num46 *= 1.5f;
                            }
                            num44 *= num46;
                            num45 *= num46;
                            this.localAI[0] = 50f;
                            int attackDamage_ForProjectiles_MultiLerp2 = this.GetAttackDamage_ForProjectiles_MultiLerp(15f, 17f, 20f);
                            Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), center.X, center.Y, num44, num45, 920, attackDamage_ForProjectiles_MultiLerp2, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        }
                    }
                }
            }
            if (this.type == 659)
            {
                flag3 = true;
                if (this.localAI[0] > 0f)
                {
                    this.localAI[0] -= 1f;
                }
                if (!this.wet && Main.player[this.target].active && !Main.player[this.target].dead && !Main.player[this.target].npcTypeNoAggro[this.type])
                {
                    Player player2 = Main.player[this.target];
                    Vector2 center2 = base.Center;
                    float num49 = player2.Center.X - center2.X;
                    float num50 = player2.Center.Y - center2.Y;
                    float num51 = (float)Math.Sqrt((double)(num49 * num49 + num50 * num50));
                    float num52 = num51;
                    if (Math.Abs(num49) < 500f && Math.Abs(num50) < 550f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            num50 = Main.player[this.target].position.Y - center2.Y - (float)Main.rand.Next(0, 200);
                            num51 = (float)Math.Sqrt((double)(num49 * num49 + num50 * num50));
                            num51 = 4.5f / num51;
                            num51 *= 2f;
                            if (num52 > 350f)
{
                                num51 *= 1.75f;
                            }
                            else if (num52 > 250f)
{
                                num51 *= 1.25f;
                            }
                            num49 *= num51;
                            num50 *= num51;
                            this.localAI[0] = 40f;
                            if (Main.expertMode)
{
                                this.localAI[0] = 30f;
                            }
                            int attackDamage_ForProjectiles_MultiLerp3 = this.GetAttackDamage_ForProjectiles_MultiLerp(15f, 17f, 20f);
                            Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), center2.X, center2.Y, num49, num50, 921, attackDamage_ForProjectiles_MultiLerp3, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        }
                    }
                }
            }
            if (this.type == 204)
            {
                flag3 = true;
                if (this.localAI[0] > 0f)
                {
                    this.localAI[0] -= 1f;
                }
                if (!this.wet && Main.player[this.target].active && !Main.player[this.target].dead && !Main.player[this.target].npcTypeNoAggro[this.type])
                {
                    Vector2 vector8 = new Vector2(this.position.X + (float)this.width * 0.5f, this.position.Y + (float)this.height * 0.5f);
                    float num53 = Main.player[this.target].position.X + (float)Main.player[this.target].width * 0.5f - vector8.X;
                    float num54 = Main.player[this.target].position.Y - vector8.Y;
                    float num55 = (float)Math.Sqrt((double)(num53 * num53 + num54 * num54));
                    if (Main.expertMode && num55 < 200f && Collision.CanHit(new Vector2(this.position.X, this.position.Y - 20f), this.width, this.height + 20, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -40f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            for (int l = 0; l < 5; l++)
{
                                Vector2 vector9 = new Vector2((float)(l - 2), -2f);
                                vector9.X *= 1f + (float)Main.rand.Next(-50, 51) * 0.02f;
                                vector9.Y *= 1f + (float)Main.rand.Next(-50, 51) * 0.02f;
                                vector9.Normalize();
                                vector9 *= 3f + (float)Main.rand.Next(-50, 51) * 0.01f;
                                int attackDamage_ForProjectiles3 = this.GetAttackDamage_ForProjectiles(13f, 13f);
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector8.X, vector8.Y, vector9.X, vector9.Y, 176, attackDamage_ForProjectiles3, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                                this.localAI[0] = 80f;
                            }
                        }
                    }
                    if (num55 < 400f && Collision.CanHit(new Vector2(this.position.X, this.position.Y - 20f), this.width, this.height + 20, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height) && this.velocity.Y == 0f)
                    {
                        this.ai[0] = -80f;
                        if (this.velocity.Y == 0f)
{
                            this.velocity.X = this.velocity.X * 0.9f;
                        }
                        if (Main.netMode != 1 && this.localAI[0] == 0f)
{
                            num54 = Main.player[this.target].position.Y - vector8.Y - (float)Main.rand.Next(-30, 20);
                            num54 -= num55 * 0.05f;
                            num53 = Main.player[this.target].position.X - vector8.X - (float)Main.rand.Next(-20, 20);
                            num55 = (float)Math.Sqrt((double)(num53 * num53 + num54 * num54));
                            num55 = 7f / num55;
                            num53 *= num55;
                            num54 *= num55;
                            this.localAI[0] = 65f;
                            Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector8.X, vector8.Y, num53, num54, 176, 13, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        }
                    }
                }
            }
            if (this.type == 377 || this.type == 446)
            {
                if (this.localAI[2] < 90f)
                {
                    this.localAI[2] += 1f;
                }
                else
                {
                    this.friendly = false;
                }
            }
            if (this.type == 59)
            {
                this.position += this.netOffset;
                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f, 0.3f, 0.1f);
                int num56 = Dust.NewDust(new Vector2(this.position.X, this.position.Y), this.width, this.height, 6, this.velocity.X * 0.2f, this.velocity.Y * 0.2f, 100, default(Color), 1.7f);
                Main.dust[num56].noGravity = true;
                this.position -= this.netOffset;
            }
            if (this.ai[2] > 1f)
            {
                this.ai[2] -= 1f;
            }
            if (this.wet)
            {
                if (this.collideY)
                {
                    this.velocity.Y = -2f;
                }
                if (this.velocity.Y < 0f && this.ai[3] == this.position.X)
                {
                    this.direction *= -1;
                    this.ai[2] = 200f;
                }
                if (this.velocity.Y > 0f)
                {
                    this.ai[3] = this.position.X;
                }
                if (this.type == 59 && !Main.remixWorld)
                {
                    if (this.velocity.Y > 2f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.9f;
                    }
                    else if (this.directionY < 0)
                    {
                        this.velocity.Y = this.velocity.Y - 0.8f;
                    }
                    this.velocity.Y = this.velocity.Y - 0.5f;
                    if (this.velocity.Y < -10f)
                    {
                        this.velocity.Y = -10f;
                    }
                }
                else
                {
                    if (this.velocity.Y > 2f)
                    {
                        this.velocity.Y = this.velocity.Y * 0.9f;
                    }
                    this.velocity.Y = this.velocity.Y - 0.5f;
                    if (this.velocity.Y < -4f)
                    {
                        this.velocity.Y = -4f;
                    }
                }
                if (this.ai[2] == 1f && flag3)
                {
                    this.TargetClosest(true);
                }
            }
            this.aiAction = 0;
            if (this.ai[2] == 0f)
            {
                this.ai[0] = -100f;
                this.ai[2] = 1f;
                this.TargetClosest(true);
            }
            if (this.velocity.Y == 0f)
            {
                if (this.collideY && this.oldVelocity.Y != 0f && Collision.SolidCollision(this.position, this.width, this.height))
                {
                    this.position.X = this.position.X - (this.velocity.X + (float)this.direction);
                }
                if (this.ai[3] == this.position.X)
                {
                    this.direction *= -1;
                    this.ai[2] = 200f;
                }
                this.ai[3] = 0f;
                if (this.ai[1] == 3609f)
                {
                    if (this.direction < 0)
                    {
                        this.velocity.X = this.velocity.X - 0.1f;
                    }
                    else
                    {
                        this.velocity.X = this.velocity.X + 0.1f;
                    }
                    this.velocity.X = Utils.Clamp<float>(this.velocity.X, -2.5f, 2.5f);
                }
                else
                {
                    this.velocity.X = this.velocity.X * 0.8f;
                    if ((double)this.velocity.X > -0.1 && (double)this.velocity.X < 0.1)
                    {
                        this.velocity.X = 0f;
                    }
                }
                if (flag3)
                {
                    this.ai[0] += 1f;
                }
                this.ai[0] += 1f;
                if (this.type == 59 && !Main.remixWorld)
                {
                    this.ai[0] += 2f;
                }
                if (this.type == 71)
                {
                    this.ai[0] += 3f;
                }
                if (this.type == 667)
                {
                    this.ai[0] += 3f;
                }
                if (this.type == 138)
                {
                    this.ai[0] += 2f;
                }
                if (this.type == 183)
                {
                    this.ai[0] += 1f;
                }
                if (this.type == 658)
                {
                    this.ai[0] += 5f;
                }
                if (this.type == 659)
                {
                    this.ai[0] += 3f;
                }
                if (this.type == 304)
                {
                    float num57 = (float)((1 - this.life / this.lifeMax) * 10);
                    this.ai[0] += num57;
                }
                if (this.type == 377 || this.type == 446)
                {
                    this.ai[0] += 3f;
                }
                if (this.type == 81)
                {
                    if (this.scale >= 0f)
                    {
                        this.ai[0] += 4f;
                    }
                    else
                    {
                        this.ai[0] += 1f;
                    }
                }
                float num58 = -1000f;
                if (this.type == 659)
                {
                    num58 = -500f;
                }
                if (this.type == 667)
                {
                    num58 = -400f;
                }
                int num59 = 0;
                if (this.ai[0] >= 0f)
                {
                    num59 = 1;
                }
                if (this.ai[0] >= num58 && this.ai[0] <= num58 * 0.5f)
                {
                    num59 = 2;
                }
                if (this.ai[0] >= num58 * 2f && this.ai[0] <= num58 * 1.5f)
                {
                    num59 = 3;
                }
                if (num59 > 0)
                {
                    this.netUpdate = true;
                    if (flag3 && this.ai[2] == 1f)
                    {
                        this.TargetClosest(true);
                    }
                    if (num59 == 3)
                    {
                        this.velocity.Y = -8f;
                        if (this.type == 59 && !Main.remixWorld)
{
                            this.velocity.Y = this.velocity.Y - 2f;
                        }
                        this.velocity.X = this.velocity.X + (float)(3 * this.direction);
                        if (this.type == 59 && !Main.remixWorld)
{
                            this.velocity.X = this.velocity.X + 0.5f * (float)this.direction;
                        }
                        this.ai[0] = -200f;
                        this.ai[3] = this.position.X;
                    }
                    else
                    {
                        this.velocity.Y = -6f;
                        this.velocity.X = this.velocity.X + (float)(2 * this.direction);
                        if (this.type == 59 && !Main.remixWorld)
{
                            this.velocity.X = this.velocity.X + (float)(2 * this.direction);
                        }
                        this.ai[0] = -120f;
                        if (num59 == 1)
{
                            this.ai[0] += num58;
                        }
                        else
{
                            this.ai[0] += num58 * 2f;
                        }
                    }
                    if (this.type == 659)
                    {
                        this.velocity.Y = this.velocity.Y * 1.6f;
                        this.velocity.X = this.velocity.X * 1.2f;
                    }
                    if (this.type == 685)
                    {
                        this.velocity.Y = this.velocity.Y * 0.5f;
                        this.velocity.X = this.velocity.X * 0.2f;
                        if (Main.rand.Next(2) == 0)
{
                            this.direction *= -1;
                        }
                    }
                    if (this.type == 141)
                    {
                        this.velocity.Y = this.velocity.Y * 1.3f;
                        this.velocity.X = this.velocity.X * 1.2f;
                    }
                    if (this.type == 377 || this.type == 446)
                    {
                        this.velocity.Y = this.velocity.Y * 0.9f;
                        this.velocity.X = this.velocity.X * 0.6f;
                        if (flag3)
{
                            this.direction = -this.direction;
                            this.velocity.X = this.velocity.X * -1f;
                        }
                        int num60 = (int)(base.Center.X / 16f);
                        int num61 = (int)(base.Center.Y / 16f) - 1;
                        if (WorldGen.SolidTile(num60, num61, false) && -this.velocity.Y + (float)this.height > 16f)
{
                            this.velocity.Y = (float)(-(float)(16 - this.height));
                            return;
                        }
                    }
                }
                else if (this.ai[0] >= -30f)
                {
                    this.aiAction = 1;
                    return;
                }
            }
            else if (this.target < 255 && ((this.direction == 1 && this.velocity.X < 3f) || (this.direction == -1 && this.velocity.X > -3f)))
            {
                if (this.collideX && Math.Abs(this.velocity.X) == 0.2f)
                {
                    this.position.X = this.position.X - 1.4f * (float)this.direction;
                }
                if (this.collideY && this.oldVelocity.Y != 0f && Collision.SolidCollision(this.position, this.width, this.height))
                {
                    this.position.X = this.position.X - (this.velocity.X + (float)this.direction);
                }
                if ((this.direction == -1 && (double)this.velocity.X < 0.01) || (this.direction == 1 && (double)this.velocity.X > -0.01))
                {
                    this.velocity.X = this.velocity.X + 0.2f * (float)this.direction;
                    return;
                }
                this.velocity.X = this.velocity.X * 0.93f;
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Tile.active(), Terraria.NPC.AddBuff(), Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.AI_001_SetRainbowSlimeColor(), Terraria.NPC.AI_001_Slimes_GenerateItemInsideBody(), Terraria.NPC.alpha, Terraria.NPC.AnyLifeCrystalSlimes(), Microsoft.Xna.Framework.Color.B, Terraria.NPC.buffImmune, Terraria.NPC.CanBeReplacedByOtherNPCs, Terraria.Collision.CanHit(), Terraria.Collision.CanHitWithCheck(), Terraria.Entity.Center, Terraria.Utils.Clamp(), Terraria.NPC.collideX, Terraria.NPC.collideY, Microsoft.Xna.Framework.Graphics.Color, Terraria.NPC.color, Terraria.Tile.color(), Terraria.NPC.CountNPCS(), Terraria.Main.dayTime, Terraria.Player.dead, Terraria.NPC.defLifeMax, Terraria.Entity.direction, Terraria.NPC.directionY, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.NPC.downedBoss3, Terraria.Main.dust, Terraria.Main.expertMode, Terraria.Dust.fadeIn, Microsoft.Xna.Framework.Color.G, Terraria.GameContent.Events.BirthdayParty.GenuineParty, Terraria.NPC.GetAttackDamage_ForProjectiles(), Terraria.NPC.GetAttackDamage_ForProjectiles_MultiLerp(), Terraria.Main.getGoodWorld, Terraria.Item.GetRandomVoiceItem(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.gore, Terraria.NPC.gravity, Terraria.Main.hardMode, Terraria.Entity.height, Terraria.Main.hslToRgb(), int, Terraria.WorldGen.InWorld(), Terraria.ID.ItemID.Sets.IsAVoiceChangeItem, Terraria.WorldGen.isThisInTheRockLayer(), Terraria.Entity.Left, Microsoft.Xna.Framework.Vector2.Length(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.WorldGen.Skyblock.lowTiles, Terraria.Main.moonPhase, Terraria.Main.myPlayer, Terraria.NPC.netID, Terraria.Main.netMode, Terraria.NPC.netOffset, Terraria.NPC.netUpdate, Terraria.Dust.NewDust(), Terraria.Dust.NewDustDirect(), Terraria.Dust.NewDustPerfect(), Terraria.Gore.NewGore(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.Skyblock.noFossils, Terraria.Dust.noGravity, Terraria.WorldGen.Skyblock.noHellstone, Terraria.Dust.noLightEmittance, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.noTrapsWorld, Terraria.DelegateMethods.NotSolidOrPlatforms(), Terraria.Main.notTheBeesWorld, Terraria.Main.npc, Terraria.Player.npcTypeNoAggro, Terraria.Entity.oldVelocity, Terraria.WorldGen.paintColor(), Terraria.WorldGen.PlaceSuitableHerbHere(), Terraria.WorldGen.PlaceTile(), Terraria.Main.player, Terraria.Entity.position, Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn(), Terraria.Entity.Right, Terraria.Dust.scale, Terraria.Gore.scale, Terraria.NPC.scale, Terraria.NetMessage.SendTileSquare(), Terraria.ID.NPCID.Sets.SlimeCanContainItems, Terraria.Main.slimeRain, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile3(), System.Math.Sqrt(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.Utils.TileActionAttempt(), Terraria.Main.timeForVisualEffects, Terraria.Entity.Top, Terraria.NPC.type, Terraria.Main.vampireSeed, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().