Terraria Decompiled: Terraria.NPC.NPCLoot_DropHeals
NPCLoot_DropHeals()
void Terraria.NPC.NPCLoot_DropHeals (Player closestPlayer) inline private
Definition at line 77843 of file NPC.cs.
        {
            this.NPCLoot_DropCommonLifeAndMana(closestPlayer);
            int num = this.type;
            if (num <= 119)
            {
                if (num - 13 > 2)
                {
                    if (num - 116 > 3)
                    {
                        return;
                    }
                    if (!Main.expertMode || Main.rand.Next(5) == 0)
                    {
                        Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                        return;
                    }
                }
                else if (Main.rand.Next(4) == 0 && closestPlayer.statLife < closestPlayer.statLifeMax2)
                {
                    Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                    return;
                }
            }
            else if (num != 139)
            {
                if (num != 267)
                {
                    switch (num)
                    {
                    case 305:
                    case 306:
                    case 307:
                    case 308:
                    case 309:
                    case 310:
                    case 311:
                    case 312:
                    case 313:
                    case 314:
                    case 329:
                    case 330:
                        if (closestPlayer.RollLuck(4) == 0)
{
                            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                            return;
                        }
                        break;
                    case 315:
                        Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                        return;
                    case 316:
                    case 317:
                    case 318:
                    case 319:
                    case 320:
                    case 321:
                    case 322:
                    case 323:
                    case 324:
                    case 328:
                    case 331:
                    case 332:
                    case 333:
                    case 334:
                    case 335:
                    case 336:
                    case 337:
                    case 343:
                        break;
                    case 325:
                    case 327:
                    case 344:
                    case 345:
                    case 346:
                    {
                        int num2 = Main.rand.Next(6) + 6;
                        for (int i = 0; i < num2; i++)
{
                            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                        }
                        return;
                    }
                    case 326:
                        if (closestPlayer.RollLuck(6) == 0)
{
                            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                            return;
                        }
                        break;
                    case 338:
                    case 339:
                    case 340:
                        if (closestPlayer.RollLuck(5) == 0)
{
                            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                            return;
                        }
                        break;
                    case 341:
                    {
                        int num3 = Main.rand.Next(5, 11);
                        for (int j = 0; j < num3; j++)
{
                            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                        }
                        return;
                    }
                    case 342:
                        if (Main.rand.Next(3) != 0)
{
                            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                            return;
                        }
                        break;
                    default:
                        return;
                    }
                }
                else if (Main.rand.Next(2) == 0 && closestPlayer.statLife < closestPlayer.statLifeMax2)
                {
                    Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
                    return;
                }
            }
            else if (Main.rand.Next(2) == 0)
            {
                Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
            }
        }
References Terraria.Main.expertMode, Terraria.NPC.GetItemSource_Loot(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.NPCLoot_DropCommonLifeAndMana(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Player.RollLuck(), Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.NPC.type, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.NPC.NPCLoot().