Terraria Decompiled: Terraria.NPC.CheckProgressFrostMoon
CheckProgressFrostMoon()
void Terraria.NPC.CheckProgressFrostMoon () inline private
Definition at line 77151 of file NPC.cs.
        {
            if (Main.snowMoon)
            {
                NetworkText networkText = NetworkText.Empty;
                int num = NPC.MoonEventRequiredPointsPerWaveLookup[NPC.waveNumber];
                switch (NPC.waveNumber)
                {
                case 1:
                    networkText = Lang.GetInvasionWaveText(2, new short[] { 338, 350 });
                    break;
                case 2:
                    networkText = Lang.GetInvasionWaveText(3, new short[] { 338, 350, 342, 348 });
                    break;
                case 3:
                    networkText = Lang.GetInvasionWaveText(4, new short[] { 344, 338, 350, 342 });
                    break;
                case 4:
                    networkText = Lang.GetInvasionWaveText(5, new short[] { 344, 338, 350, 348 });
                    break;
                case 5:
                    networkText = Lang.GetInvasionWaveText(6, new short[] { 344, 350, 348, 347 });
                    break;
                case 6:
                    networkText = Lang.GetInvasionWaveText(7, new short[] { 346, 342, 350, 338 });
                    break;
                case 7:
                    networkText = Lang.GetInvasionWaveText(8, new short[] { 346, 347, 350, 348, 351 });
                    break;
                case 8:
                    networkText = Lang.GetInvasionWaveText(9, new short[] { 346, 344, 348, 347, 342 });
                    break;
                case 9:
                    networkText = Lang.GetInvasionWaveText(10, new short[] { 346, 344, 351, 338, 347 });
                    break;
                case 10:
                    networkText = Lang.GetInvasionWaveText(11, new short[] { 345, 352, 338, 342 });
                    break;
                case 11:
                    networkText = Lang.GetInvasionWaveText(12, new short[] { 345, 344, 342, 343, 338 });
                    break;
                case 12:
                    networkText = Lang.GetInvasionWaveText(13, new short[] { 345, 346, 342, 352, 343, 347 });
                    break;
                case 13:
                    networkText = Lang.GetInvasionWaveText(14, new short[] { 345, 346, 344, 343, 351 });
                    break;
                case 14:
                    networkText = Lang.GetInvasionWaveText(15, new short[] { 345, 346, 344, 343, 347 });
                    break;
                case 15:
                    networkText = Lang.GetInvasionWaveText(16, new short[] { 345, 346, 344, 343, 352 });
                    break;
                case 16:
                    networkText = Lang.GetInvasionWaveText(17, new short[] { 345, 346, 344, 343, 351, 347 });
                    break;
                case 17:
                    networkText = Lang.GetInvasionWaveText(18, new short[] { 345, 346, 344, 343, 348, 351 });
                    break;
                case 18:
                    networkText = Lang.GetInvasionWaveText(19, new short[] { 345, 346, 344, 343 });
                    break;
                case 19:
                    networkText = Lang.GetInvasionWaveText(-1, new short[] { 345, 346, 344 });
                    break;
                }
                float num2 = 0f;
                switch (this.type)
                {
                case 338:
                case 339:
                case 340:
                    num2 = 1f;
                    break;
                case 341:
                    num2 = 20f;
                    break;
                case 342:
                    num2 = 2f;
                    break;
                case 343:
                    num2 = 18f;
                    break;
                case 344:
                    num2 = 50f;
                    break;
                case 345:
                    num2 = 150f;
                    break;
                case 346:
                    num2 = 100f;
                    break;
                case 347:
                    num2 = 8f;
                    break;
                case 348:
                case 349:
                    num2 = 4f;
                    break;
                case 350:
                    num2 = 3f;
                    break;
                case 351:
                    num2 = 10f;
                    break;
                case 352:
                    num2 = 5f;
                    break;
                }
                num2 *= this.GetMoonEventPointScalar();
                float num3 = NPC.waveKills;
                NPC.waveKills += num2;
                NPC.totalInvasionPoints += num2;
                if (NPC.waveKills >= (float)num && num != 0)
                {
                    NPC.waveKills = 0f;
                    NPC.waveNumber++;
                    num = NPC.MoonEventRequiredPointsPerWaveLookup[NPC.waveNumber];
                    if (networkText != NetworkText.Empty)
                    {
                        ChatHelper.BroadcastChatMessage(networkText, ChatColors.BossOrEvent, -1);
                        if (NPC.waveNumber == 15)
{
                            AchievementsHelper.NotifyProgressionEvent(14);
                        }
                    }
                }
                if (NPC.waveKills != num3 && num2 != 0f)
                {
                    if (Main.netMode != 1)
                    {
                        Main.ReportInvasionProgress((int)NPC.waveKills, num, 1, NPC.waveNumber);
                    }
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, (float)Main.invasionProgressMax, 1f, (float)NPC.waveNumber, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.Empty, Terraria.Lang.GetInvasionWaveText(), Terraria.NPC.GetMoonEventPointScalar(), Terraria.Main.invasionProgress, Terraria.Main.invasionProgressMax, Terraria.NPC.MoonEventRequiredPointsPerWaveLookup, Terraria.Main.netMode, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.ReportInvasionProgress(), Terraria.NetMessage.SendData(), Terraria.Main.snowMoon, Terraria.NPC.type, Terraria.NPC.waveKills, and Terraria.NPC.waveNumber.
Referenced by Terraria.NPC.checkDead().