Terraria Decompiled: Terraria.NPC.ScaleStats
ScaleStats()
void Terraria.NPC.ScaleStats (int? activePlayersCount, float? strengthOverride) inline
Definition at line 11970 of file NPC.cs.
        {
            if (!NPCID.Sets.NeedsExpertScaling[this.type] && (this.lifeMax <= 5 || this.damage == 0 || this.friendly || this.townNPC))
            {
                return;
            }
            this.difficulty = ((strengthOverride != null) ? strengthOverride.Value : Main.Difficulty);
            if (this.difficulty >= GameDifficultyLevel.Expert && Main.hardMode)
            {
                this.ScaleStats_ForExpertHardmode();
            }
            this.ScaleStats_ByDifficulty();
            if (this.difficulty >= GameDifficultyLevel.Expert)
            {
                this.ScaleStats_ByPlayerCount((activePlayersCount != null) ? activePlayersCount.Value : NPC.GetActivePlayerCount());
            }
            if ((this.type < 0 || !NPCID.Sets.ProjectileNPC[this.type]) && this.lifeMax < 6)
            {
                this.lifeMax = 6;
            }
            this.life = this.lifeMax;
            this.defDamage = this.damage;
            this.defDefense = this.defense;
            this.defLifeMax = this.lifeMax;
        }
References Terraria.NPC.damage, Terraria.NPC.defense, Terraria.Main.Difficulty, Terraria.NPC.difficulty, Terraria.DataStructures.GameDifficultyLevel.Expert, Terraria.NPC.GetActivePlayerCount(), Terraria.Main.hardMode, Terraria.NPC.lifeMax, Terraria.ID.NPCID.Sets.NeedsExpertScaling, Terraria.ID.NPCID.Sets.ProjectileNPC, Terraria.NPC.ScaleStats_ByDifficulty(), Terraria.NPC.ScaleStats_ByPlayerCount(), Terraria.NPC.ScaleStats_ForExpertHardmode(), and Terraria.NPC.type.
Referenced by Terraria.NPC.SetDefaults(), and Terraria.NPC.SetDefaultsFromNetId().