Terraria Decompiled: Terraria.NPC.BigMimicSummonCheck
BigMimicSummonCheck()
static bool Terraria.NPC.BigMimicSummonCheck (int x, int y, Player user) inline static
Definition at line 75904 of file NPC.cs.
        {
            if (Main.netMode == 1 || !Main.hardMode)
            {
                return false;
            }
            int num = Chest.FindChest(x, y);
            if (num < 0)
            {
                return false;
            }
            int num2 = 0;
            int num3 = 0;
            int num4 = 0;
            Chest chest = Main.chest[num];
            ushort num5 = Main.tile[chest.x, chest.y].type;
            int num6 = (int)(Main.tile[chest.x, chest.y].frameX / 36);
            for (int i = 0; i < chest.maxItems; i++)
            {
                if (TileID.Sets.BasicChest[(int)num5] && (num5 != 21 || num6 < 5 || num6 > 6) && chest.item[i] != null && chest.item[i].type > 0)
                {
                    if (chest.item[i].type == 3092)
                    {
                        num2 += chest.item[i].stack;
                    }
                    else if (chest.item[i].type == 3091)
                    {
                        num3 += chest.item[i].stack;
                    }
                    else
                    {
                        num4++;
                    }
                }
            }
            if (num4 == 0 && num2 + num3 == 1)
            {
                if (num2 != 1)
                {
                }
                if (TileID.Sets.BasicChest[(int)Main.tile[x, y].type])
                {
                    if (Main.tile[x, y].frameX % 36 != 0)
                    {
                        x--;
                    }
                    if (Main.tile[x, y].frameY % 36 != 0)
                    {
                        y--;
                    }
                    int num7 = Chest.FindChest(x, y);
                    Chest chest2 = Main.chest[num];
                    int maxItems = chest2.maxItems;
                    for (int j = 0; j < maxItems; j++)
                    {
                        chest2.item[j] = new Item();
                    }
                    Chest.DestroyChest(x, y);
                    for (int k = x; k <= x + 1; k++)
                    {
                        for (int l = y; l <= y + 1; l++)
{
                            if (TileID.Sets.BasicChest[(int)Main.tile[k, l].type])
{
                                Main.tile[k, l].ClearTile();
                            }
                        }
                    }
                    int num8 = 1;
                    if (Main.tile[x, y].type == 467)
                    {
                        num8 = 5;
                    }
                    NetMessage.SendData(34, -1, -1, null, num8, (float)x, (float)y, 0f, num7, 0, 0);
                    NetMessage.SendTileSquare(-1, x, y, 3, TileChangeType.None);
                }
                int num9 = 475;
                if (num3 == 1)
                {
                    if (WorldGen.crimson)
                    {
                        num9 = 474;
                    }
                    else
                    {
                        num9 = 473;
                    }
                }
                int num10 = NPC.NewNPC(user.GetNPCSource_TileInteraction(x, y), x * 16 + 16, y * 16 + 32, num9, 0, 0f, 0f, 0f, 0f, 255);
                Main.npc[num10].whoAmI = num10;
                NetMessage.SendData(23, -1, -1, null, num10, 0f, 0f, 0f, 0, 0, 0);
                Main.npc[num10].BigMimicSpawnSmoke();
            }
            return false;
        }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.NPC.BigMimicSpawnSmoke(), Terraria.Main.chest, Terraria.Tile.ClearTile(), Terraria.WorldGen.crimson, Terraria.Chest.DestroyChest(), Terraria.Chest.FindChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Player.GetNPCSource_TileInteraction(), Terraria.Main.hardMode, int, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Item.type, Terraria.Tile.type, Terraria.Entity.whoAmI, Terraria.Chest.x, and Terraria.Chest.y.
Referenced by Terraria.Player.ChestChangeEvents().