Terraria Decompiled: Terraria.NPC.Collision_MoveSlopesAndStairFall
Collision_MoveSlopesAndStairFall()
void Terraria.NPC.Collision_MoveSlopesAndStairFall (bool fall) inline private
Definition at line 93711 of file NPC.cs.
        {
            if (fall)
            {
                this.stairFall = true;
            }
            if (this.aiStyle == 7)
            {
                int num = (int)base.Center.X / 16;
                int num2 = (int)this.position.Y / 16;
                if (WorldGen.InWorld(num, num2, 0))
                {
                    int num3 = 16;
                    bool flag = false;
                    if (Main.tile[num, num2] != null && Main.tile[num, num2].active() && Main.tileSolid[(int)Main.tile[num, num2].type])
                    {
                        flag = true;
                    }
                    if (!this.townNPC)
                    {
                        flag = false;
                    }
                    if (!Main.dayTime || Main.eclipse)
                    {
                        flag = true;
                    }
                    else
                    {
                        int num4 = (int)(this.position.Y + (float)this.height) / 16;
                        if (this.homeTileY - num4 > num3)
{
                            flag = true;
                        }
                    }
                    if (flag)
                    {
                        if ((this.position.Y + (float)this.height - 8f) / 16f < (float)this.homeTileY)
{
                            this.stairFall = true;
                        }
                        else
{
                            this.stairFall = false;
                        }
                    }
                }
            }
            Vector2 vector;
            int num5;
            int num6;
            this.GetTileCollisionParameters(out vector, out num5, out num6);
            Vector2 vector2 = this.position - vector;
            Vector4 vector3 = Collision.SlopeCollision(vector, this.velocity, num5, num6, NPC.gravity, this.stairFall, false);
            if (Collision.stairFall)
            {
                this.stairFall = true;
            }
            else if (!fall)
            {
                this.stairFall = false;
            }
            if (Collision.stair && Math.Abs(vector3.Y - this.position.Y) > 8f)
            {
                this.gfxOffY -= vector3.Y - this.position.Y;
                this.stepSpeed = 2f;
            }
            this.position.X = vector3.X;
            this.position.Y = vector3.Y;
            this.velocity.X = vector3.Z;
            this.velocity.Y = vector3.W;
            this.position += vector2;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Main.dayTime, Terraria.Main.eclipse, Terraria.NPC.gravity, int, Terraria.WorldGen.InWorld(), Terraria.Collision.SlopeCollision(), Terraria.Collision.stair, Terraria.Collision.stairFall, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Microsoft.Xna.Framework.Vector4.W, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector4.Y, and Microsoft.Xna.Framework.Vector4.Z.