Terraria Decompiled: Terraria.NPC.AI_125_ClumsySlimeBalloon
AI_125_ClumsySlimeBalloon()
void Terraria.NPC.AI_125_ClumsySlimeBalloon () inline private
Definition at line 40433 of file NPC.cs.
        {
            if (this.localAI[0] == 0f && Main.netMode != 1)
            {
                this.TargetClosest(true);
                this.localAI[0] = 1f;
                this.netUpdate = true;
            }
            this.spriteDirection = this.direction;
            this.rotation = this.velocity.X * 0.05f;
            NPCAimedTarget targetData = this.GetTargetData(true);
            float num = float.PositiveInfinity;
            int num2 = 0;
            Vector2 vector = Vector2.Zero;
            if (!targetData.Invalid)
            {
                vector = targetData.Center - base.Bottom;
                if (vector.Y < 0f)
                {
                    num2 = (int)vector.Y / -16;
                }
                num = vector.Length();
                if (this.direction != Math.Sign(vector.X))
                {
                    num2 = 0;
                }
            }
            if (this.wet || this.collideX || (this.collideY && this.oldVelocity.Y < 0f))
            {
                float num3 = this.oldVelocity.X + (float)(this.direction * 8);
                this.position.X = this.position.X - num3;
                this.TargetClosest(false);
                this.direction *= -1;
                this.velocity.X = (float)(this.direction * 2);
                this.life = -1;
                this.HitEffect(0, 10.0);
                this.active = false;
                this.netUpdate = true;
                SoundEngine.PlaySound(this.DeathSound, this.position, 0f, 1f);
                return;
            }
            if (this.collideY)
            {
                this.velocity.Y = (float)((this.oldVelocity.Y > 0f) ? 1 : (-1));
                this.TargetClosest(false);
            }
            float num4 = 3f + Math.Abs(Main.windSpeedTarget) * 2f;
            if (Math.Sign(this.velocity.X) != this.direction || Math.Abs(this.velocity.X) < num4)
            {
                this.velocity.X = this.velocity.X + (float)this.direction * 0.04f;
                if (this.velocity.X * (float)this.direction < 0f)
                {
                    if (Math.Abs(this.velocity.X) > num4)
                    {
                        this.velocity.X = this.velocity.X + (float)this.direction * 0.15f;
                    }
                    else
                    {
                        this.velocity.X = this.velocity.X + (float)this.direction * 0.1f;
                    }
                }
                else if (Math.Abs(this.velocity.X) > num4)
                {
                    this.velocity.X = (float)this.direction * num4;
                }
            }
            int num5 = (int)((this.position.X + (float)(this.width / 2)) / 16f) + this.direction;
            int num6 = (int)((this.position.Y + (float)this.height) / 16f);
            bool flag = true;
            int num7 = 8 + num2;
            bool flag2 = false;
            for (int i = num6; i < num6 + num7; i++)
            {
                if (Main.tile[num5, i] == null)
                {
                    Main.tile[num5, i] = new Tile();
                }
                if ((Main.tile[num5, i].nactive() && Main.tileSolid[(int)Main.tile[num5, i].type]) || Main.tile[num5, i].liquid > 0)
                {
                    if (i < num6 + 5 + num2)
                    {
                        flag2 = true;
                    }
                    flag = false;
                    break;
                }
            }
            if (num < 400f && Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height))
            {
                float num8 = 2f;
                float num9 = 0.035f;
                if (base.Center.Y + (float)(this.height / 4) > Main.player[this.target].position.Y + (float)(Main.player[this.target].height / 4) && this.velocity.Y > -num8)
                {
                    this.velocity.Y = this.velocity.Y - num9;
                    if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - num9;
                        return;
                    }
                }
                else if (base.Center.Y + (float)(this.height / 4) < Main.player[this.target].position.Y + (float)(Main.player[this.target].height / 4) && this.velocity.Y < num8)
                {
                    this.velocity.Y = this.velocity.Y + num9;
                    if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + num9;
                        return;
                    }
                }
            }
            else
            {
                if (flag)
                {
                    this.velocity.Y = this.velocity.Y + 0.05f;
                }
                else
                {
                    this.velocity.Y = this.velocity.Y - 0.1f;
                }
                if (flag2)
                {
                    this.velocity.Y = this.velocity.Y - 0.2f;
                }
                if (this.velocity.Y > 2f)
                {
                    this.velocity.Y = 2f;
                }
                if (this.velocity.Y < -4f)
                {
                    this.velocity.Y = -4f;
                }
            }
        }
References System.Math.Abs(), Terraria.Collision.CanHit(), Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.NPC.DeathSound, Terraria.Entity.direction, Terraria.NPC.GetTargetData(), Terraria.Entity.height, Terraria.NPC.HitEffect(), int, Terraria.DataStructures.NPCAimedTarget.Invalid, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Tile.liquid, Terraria.NPC.localAI, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Entity.oldVelocity, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, System.Math.Sign(), Terraria.NPC.TargetClosest(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.width, Terraria.Main.windSpeedTarget, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.AI().