Terraria Decompiled: Terraria.NPC.GetChat
GetChat()
string Terraria.NPC.GetChat () inline
Definition at line 94894 of file NPC.cs.
        {
            if (this.nextDialogue != null)
            {
                return this.nextDialogue.GetChatAndClearCondition(this);
            }
            NPC.PreventJojaColaDialog = false;
            NPC.RerollDryadText = 0;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            bool flag6 = false;
            bool flag7 = false;
            bool flag8 = false;
            bool flag9 = false;
            bool flag10 = false;
            bool flag11 = false;
            bool flag12 = false;
            bool flag13 = false;
            bool flag14 = false;
            bool flag15 = false;
            bool flag16 = false;
            bool flag17 = false;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active)
                {
                    if (Main.npc[i].type == 17)
                    {
                        flag = true;
                    }
                    else if (Main.npc[i].type == 18)
                    {
                        flag2 = true;
                    }
                    else if (Main.npc[i].type == 19)
                    {
                        flag3 = true;
                    }
                    else if (Main.npc[i].type == 20)
                    {
                        flag4 = true;
                    }
                    else if (Main.npc[i].type == 37)
                    {
                        flag5 = true;
                    }
                    else if (Main.npc[i].type == 38)
                    {
                        flag6 = true;
                    }
                    else if (Main.npc[i].type == 124)
                    {
                        flag7 = true;
                    }
                    else if (Main.npc[i].type == 107)
                    {
                        flag8 = true;
                    }
                    else if (Main.npc[i].type == 54)
                    {
                        flag9 = true;
                    }
                    else if (Main.npc[i].type == 160)
                    {
                        flag10 = true;
                    }
                    else if (Main.npc[i].type == 178)
                    {
                        flag11 = true;
                    }
                    else if (Main.npc[i].type == 229)
                    {
                        flag12 = true;
                    }
                    else if (Main.npc[i].type == 209)
                    {
                        flag13 = true;
                    }
                    else if (Main.npc[i].type == 208)
                    {
                        flag14 = true;
                    }
                    else if (Main.npc[i].type == 353)
                    {
                        flag15 = true;
                    }
                    else if (Main.npc[i].type == 22)
                    {
                        flag16 = true;
                    }
                    else if (Main.npc[i].type == 441)
                    {
                        flag17 = true;
                    }
                }
            }
            string text = "";
            string text2 = "";
            if (this.type == 17)
            {
                if (this.HasSpecialEventText("Merchant", out text2))
                {
                    text = text2;
                }
                else if (!NPC.downedBoss1 && Main.rand.Next(3) == 0)
                {
                    if (Main.player[Main.myPlayer].statLifeMax < 200)
                    {
                        text = Lang.dialog(1, false);
                    }
                    else if (Main.player[Main.myPlayer].statDefense <= 10)
                    {
                        text = Lang.dialog(2, false);
                    }
                    else
                    {
                        text = Lang.dialog(3, false);
                    }
                }
                else if (Main.dayTime)
                {
                    if (Main.time < 16200.0)
                    {
                        int num = Main.rand.Next(3);
                        if (num == 0)
{
                            text = Lang.dialog(4, false);
                        }
                        else if (num == 1)
{
                            text = Lang.dialog(5, false);
                        }
                        else
{
                            text = Lang.dialog(6, false);
                        }
                    }
                    else if (Main.time > 37800.0)
                    {
                        int num2 = Main.rand.Next(3);
                        if (num2 == 0)
{
                            text = Lang.dialog(7, false);
                        }
                        else if (num2 == 1)
{
                            text = Lang.dialog(8, false);
                        }
                        else
{
                            text = Lang.dialog(9, false);
                        }
                    }
                    else
                    {
                        int num3 = Main.rand.Next(3);
                        if (num3 == 0)
{
                            text = Lang.dialog(10, false);
                        }
                        else if (num3 == 1)
{
                            text = Lang.dialog(11, false);
                        }
                        else
{
                            text = Lang.dialog(12, false);
                        }
                    }
                }
                else if (Main.bloodMoon)
                {
                    if (flag2 && flag7 && Main.rand.Next(3) == 0)
                    {
                        text = Lang.dialog(13, false);
                    }
                    else
                    {
                        int num4 = Main.rand.Next(4);
                        if (num4 == 0)
{
                            text = Lang.dialog(14, false);
                        }
                        else if (num4 == 1)
{
                            text = Lang.dialog(15, false);
                        }
                        else if (num4 == 2)
{
                            text = Lang.dialog(16, false);
                        }
                        else
{
                            text = Lang.dialog(17, false);
                        }
                    }
                }
                else if (Main.time < 9720.0)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        text = Lang.dialog(18, false);
                    }
                    else
                    {
                        text = Lang.dialog(19, false);
                    }
                }
                else if (Main.time > 22680.0)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        text = Lang.dialog(20, false);
                    }
                    else
                    {
                        text = Lang.dialog(21, false);
                    }
                }
                else
                {
                    int num5 = Main.rand.Next(3);
                    if (num5 == 0)
                    {
                        text = Lang.dialog(22, false);
                    }
                    else if (num5 == 1)
                    {
                        text = Lang.dialog(23, false);
                    }
                    else
                    {
                        text = Lang.dialog(24, false);
                    }
                }
            }
            else if (this.type == 18)
            {
                if (this.HasSpecialEventText("Nurse", out text2))
                {
                    text = text2;
                }
                else if (Main.bloodMoon)
                {
                    if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.66)
                    {
                        int num6 = Main.rand.Next(3);
                        if (num6 == 0)
{
                            text = Lang.dialog(25, false);
                        }
                        else if (num6 == 1)
{
                            text = Lang.dialog(26, false);
                        }
                        else
{
                            text = Lang.dialog(27, false);
                        }
                    }
                    else
                    {
                        int num7 = Main.rand.Next(4);
                        if (num7 == 0)
{
                            text = Lang.dialog(28, false);
                        }
                        else if (num7 == 1)
{
                            text = Lang.dialog(29, false);
                        }
                        else if (num7 == 2)
{
                            text = Lang.dialog(30, false);
                        }
                        else
{
                            text = Lang.dialog(31, false);
                        }
                    }
                }
                else if (Main.rand.Next(5) == 0 && Main.LocalPlayer.numberOfDeathsPVE > 1)
                {
                    int numberOfDeathsPVE = Main.LocalPlayer.numberOfDeathsPVE;
                    int num8 = 25;
                    int num9 = 100;
                    string text3 = "Low";
                    if (numberOfDeathsPVE >= num9)
                    {
                        text3 = "High";
                    }
                    else if (numberOfDeathsPVE >= num8)
                    {
                        text3 = "Medium";
                    }
                    text = Language.GetTextValue("NurseSpecialText.DeathCount" + text3);
                }
                else if (Main.rand.Next(3) == 0 && !NPC.downedBoss3)
                {
                    text = Lang.dialog(32, false);
                }
                else if (flag6 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(33, false);
                }
                else if (flag3 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(34, false);
                }
                else if (flag16 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(35, false);
                }
                else if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.33)
                {
                    int num10 = Main.rand.Next(5);
                    if (num10 == 0)
                    {
                        text = Lang.dialog(36, false);
                    }
                    else if (num10 == 1)
                    {
                        text = Lang.dialog(37, false);
                    }
                    else if (num10 == 2)
                    {
                        text = Lang.dialog(38, false);
                    }
                    else if (num10 == 3)
                    {
                        text = Lang.dialog(39, false);
                    }
                    else
                    {
                        text = Lang.dialog(40, false);
                    }
                }
                else if ((double)Main.player[Main.myPlayer].statLife < (double)Main.player[Main.myPlayer].statLifeMax2 * 0.66)
                {
                    int num11 = Main.rand.Next(7);
                    if (num11 == 0)
                    {
                        text = Lang.dialog(41, false);
                    }
                    else if (num11 == 1)
                    {
                        text = Lang.dialog(42, false);
                    }
                    else if (num11 == 2)
                    {
                        text = Lang.dialog(43, false);
                    }
                    else if (num11 == 3)
                    {
                        text = Lang.dialog(44, false);
                    }
                    else if (num11 == 4)
                    {
                        text = Lang.dialog(45, false);
                    }
                    else if (num11 == 5)
                    {
                        text = Lang.dialog(46, false);
                    }
                    else
                    {
                        text = Lang.dialog(47, false);
                    }
                }
                else
                {
                    LocalizedText[] array = Language.FindAll(Lang.CreateDialogFilter("NurseChatter.", true));
                    int num12 = Main.rand.Next(4 + array.Length);
                    if (num12 >= 4)
                    {
                        text = array[num12 - 4].Value;
                    }
                    else if (num12 == 0)
                    {
                        text = Lang.dialog(48, false);
                    }
                    else if (num12 == 1)
                    {
                        text = Lang.dialog(49, false);
                    }
                    else if (num12 == 2)
                    {
                        text = Lang.dialog(50, false);
                    }
                    else
                    {
                        text = Lang.dialog(51, false);
                    }
                }
            }
            else if (this.type == 19)
            {
                if (this.HasSpecialEventText("ArmsDealer", out text2))
                {
                    text = text2;
                }
                else if (flag16 && NPC.downedBoss3 && !Main.hardMode)
                {
                    text = Lang.dialog(58, false);
                }
                else if (flag2 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(59, false);
                }
                else if (flag2 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(60, false);
                }
                else if (flag4 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(61, false);
                }
                else if (flag6 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(62, false);
                }
                else if (flag6 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(63, false);
                }
                else if (Main.bloodMoon)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        text = Lang.dialog(64, false);
                    }
                    else
                    {
                        text = Lang.dialog(65, false);
                    }
                }
                else
                {
                    int num13 = Main.rand.Next(3);
                    if (num13 == 0)
                    {
                        text = Lang.dialog(66, false);
                    }
                    else if (num13 == 1)
                    {
                        text = Lang.dialog(67, false);
                    }
                    else
                    {
                        text = Lang.dialog(68, false);
                    }
                }
            }
            else if (this.type == 20)
            {
                if (this.HasSpecialEventText("Dryad", out text2))
                {
                    text = text2;
                }
                else if (DD2Event.DownedInvasionT1 && Main.rand.Next(6) == 0)
                {
                    if (DD2Event.DownedInvasionT2)
                    {
                        text = Language.GetTextValue("DryadSpecialText.AfterDD2Tier2");
                    }
                    else
                    {
                        text = Language.GetTextValue("DryadSpecialText.AfterDD2Tier1");
                    }
                }
                else if (!NPC.downedBoss2 && Main.rand.Next(3) == 0)
                {
                    if (WorldGen.crimson)
                    {
                        text = Lang.dialog(332, false);
                    }
                    else
                    {
                        text = Lang.dialog(69, false);
                    }
                }
                else if (flag3 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(70, false);
                }
                else if (flag && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(71, false);
                }
                else if (flag5 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(72, false);
                }
                else if (flag10 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(238, false);
                }
                else if (Main.bloodMoon)
                {
                    int num14 = Main.rand.Next(4);
                    if (num14 == 0)
                    {
                        text = Lang.dialog(73, false);
                    }
                    else if (num14 == 1)
                    {
                        text = Lang.dialog(74, false);
                    }
                    else if (num14 == 2)
                    {
                        text = Lang.dialog(75, false);
                    }
                    else
                    {
                        text = Lang.dialog(76, false);
                    }
                }
                else
                {
                    int num15 = Main.rand.Next(5);
                    if (num15 == 0)
                    {
                        if (WorldGen.crimson)
{
                            text = Lang.dialog(333, false);
                        }
                        else
{
                            text = Lang.dialog(77, false);
                        }
                    }
                    else if (num15 == 1)
                    {
                        text = Lang.dialog(78, false);
                    }
                    else if (num15 == 2)
                    {
                        text = Lang.dialog(79, false);
                    }
                    else if (num15 == 3)
                    {
                        text = Lang.dialog(80, false);
                    }
                    else
                    {
                        text = Lang.dialog(81, false);
                    }
                }
                if (Main.LocalPlayer.HasItem(5275))
                {
                    text = Language.GetTextValue("StardewTalk.PlayerHasColaButIsNotHoldingIt");
                }
            }
            else if (this.type == 37)
            {
                if (Main.dayTime && !Main.remixWorld)
                {
                    int num16 = Main.rand.Next(3);
                    if (num16 == 0)
                    {
                        text = Lang.dialog(82, false);
                    }
                    else if (num16 == 1)
                    {
                        text = Lang.dialog(83, false);
                    }
                    else
                    {
                        text = Lang.dialog(84, false);
                    }
                }
                else if (Main.player[Main.myPlayer].statLifeMax < 300 || Main.player[Main.myPlayer].statDefense < 10)
                {
                    int num17 = Main.rand.Next(4);
                    if (num17 == 0)
                    {
                        text = Lang.dialog(85, false);
                    }
                    else if (num17 == 1)
                    {
                        text = Lang.dialog(86, false);
                    }
                    else if (num17 == 2)
                    {
                        text = Lang.dialog(87, false);
                    }
                    else
                    {
                        text = Lang.dialog(88, false);
                    }
                }
                else
                {
                    int num18 = Main.rand.Next(4);
                    if (num18 == 0)
                    {
                        text = Lang.dialog(89, false);
                    }
                    else if (num18 == 1)
                    {
                        text = Lang.dialog(90, false);
                    }
                    else if (num18 == 2)
                    {
                        text = Lang.dialog(91, false);
                    }
                    else
                    {
                        text = Lang.dialog(92, false);
                    }
                }
            }
            else if (this.type == 38)
            {
                if (this.HasSpecialEventText("Demolitionist", out text2))
                {
                    text = text2;
                }
                else if (!NPC.downedBoss2 && Main.rand.Next(3) == 0)
                {
                    text = Lang.dialog(93, false);
                }
                else if (Main.bloodMoon)
                {
                    int num19 = Main.rand.Next(3);
                    if (num19 == 0)
                    {
                        text = Lang.dialog(94, false);
                    }
                    else if (num19 == 1)
                    {
                        text = Lang.dialog(95, false);
                    }
                    else
                    {
                        text = Lang.dialog(96, false);
                    }
                }
                else if ((DD2Event.DownedInvasionT1 || DD2Event.Ongoing) && Main.rand.Next(5) == 0)
                {
                    text = Language.GetTextValue("DemolitionistSpecialText.AfterDD2Start");
                }
                else if (flag3 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(97, false);
                }
                else if (flag3 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(98, false);
                }
                else if (flag2 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(99, false);
                }
                else if (flag4 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(100, false);
                }
                else if (!Main.dayTime)
                {
                    int num20 = Main.rand.Next(4);
                    if (num20 == 0)
                    {
                        text = Lang.dialog(101, false);
                    }
                    else if (num20 == 1)
                    {
                        text = Lang.dialog(102, false);
                    }
                    else if (num20 == 2)
                    {
                        text = Lang.dialog(103, false);
                    }
                    else
                    {
                        text = Lang.dialog(104, false);
                    }
                }
                else
                {
                    int num21 = Main.rand.Next(5);
                    if (num21 == 0)
                    {
                        text = Lang.dialog(105, false);
                    }
                    else if (num21 == 1)
                    {
                        text = Lang.dialog(106, false);
                    }
                    else if (num21 == 2)
                    {
                        text = Lang.dialog(107, false);
                    }
                    else if (num21 == 3)
                    {
                        text = Lang.dialog(108, false);
                    }
                    else
                    {
                        text = Lang.dialog(109, false);
                    }
                }
            }
            else if (this.type == 54)
            {
                if (this.HasSpecialEventText("Clothier", out text2))
                {
                    text = text2;
                }
                else if (!flag7 && Main.rand.Next(2) == 0)
                {
                    text = Lang.dialog(110, false);
                }
                else if (flag10 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(237, false);
                }
                else if (Main.bloodMoon)
                {
                    text = Lang.dialog(111, false);
                }
                else if (flag2 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(112, false);
                }
                else if (Main.player[Main.myPlayer].head == 24)
                {
                    text = Lang.dialog(113, false);
                }
                else
                {
                    int num22 = Main.rand.Next(6);
                    if (num22 == 0)
                    {
                        text = Lang.dialog(114, false);
                    }
                    else if (num22 == 1)
                    {
                        text = Lang.dialog(115, false);
                    }
                    else if (num22 == 2)
                    {
                        text = Lang.dialog(116, false);
                    }
                    else if (num22 == 3)
                    {
                        text = Lang.dialog(117, false);
                    }
                    else if (num22 == 4)
                    {
                        text = Lang.dialog(118, false);
                    }
                    else
                    {
                        text = Lang.dialog(119, false);
                    }
                }
            }
            else if (this.type == 105)
            {
                text = Lang.dialog(120, false);
            }
            else if (this.type == 107)
            {
                if (this.homeless)
                {
                    int num23 = Main.rand.Next(5);
                    if (num23 == 0)
                    {
                        text = Lang.dialog(121, false);
                    }
                    else if (num23 == 1)
                    {
                        text = Lang.dialog(122, false);
                    }
                    else if (num23 == 2)
                    {
                        text = Lang.dialog(123, false);
                    }
                    else if (num23 == 3)
                    {
                        text = Lang.dialog(124, false);
                    }
                    else
                    {
                        text = Lang.dialog(125, false);
                    }
                }
                else if (this.HasSpecialEventText("GoblinTinkerer", out text2))
                {
                    text = text2;
                }
                else if (flag7 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(126, false);
                }
                else if (flag15 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(309, false);
                }
                else
                {
                    LocalizedText[] array2 = Language.FindAll(Lang.CreateDialogFilter("GoblinTinkererChatter.", true));
                    int num24 = Main.rand.Next(array2.Length + 5);
                    if (num24 >= 5)
                    {
                        text = array2[num24 - 5].Value;
                    }
                    else if (!Main.dayTime)
                    {
                        if (num24 == 0)
{
                            text = Lang.dialog(127, false);
                        }
                        else if (num24 == 1)
{
                            text = Lang.dialog(128, false);
                        }
                        else if (num24 == 2)
{
                            text = Lang.dialog(129, false);
                        }
                        else if (num24 == 3)
{
                            text = Lang.dialog(130, false);
                        }
                        else
{
                            text = Lang.dialog(131, false);
                        }
                    }
                    else if (num24 == 0)
                    {
                        text = Lang.dialog(132, false);
                    }
                    else if (num24 == 1)
                    {
                        text = Lang.dialog(133, false);
                    }
                    else if (num24 == 2)
                    {
                        text = Lang.dialog(134, false);
                    }
                    else if (num24 == 3)
                    {
                        text = Lang.dialog(135, false);
                    }
                    else
                    {
                        text = Lang.dialog(136, false);
                    }
                }
            }
            else if (this.type == 106)
            {
                text = Lang.dialog(137, false);
            }
            else if (this.type == 108)
            {
                if (this.homeless)
                {
                    int num25 = Main.rand.Next(3);
                    if (num25 == 0)
                    {
                        text = Lang.dialog(138, false);
                    }
                    else if (num25 == 1 && !Main.player[Main.myPlayer].Male)
                    {
                        text = Lang.dialog(139, false);
                    }
                    else if (num25 == 1)
                    {
                        text = Lang.dialog(140, false);
                    }
                    else if (num25 == 2)
                    {
                        text = Lang.dialog(141, false);
                    }
                }
                else if (this.HasLuckTextForWizard(out text2))
                {
                    text = text2;
                }
                else if (this.HasSpecialEventText("Wizard", out text2))
                {
                    text = text2;
                }
                else if (DD2Event.DownedInvasionT1 && Main.rand.Next(6) == 0)
                {
                    text = Language.GetTextValue("WizardSpecialText.AfterDD2Tier1");
                }
                else if (Main.player[Main.myPlayer].Male && flag16 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(142, false);
                }
                else if (Main.player[Main.myPlayer].Male && flag6 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(143, false);
                }
                else if (Main.player[Main.myPlayer].Male && flag8 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(144, false);
                }
                else if (!Main.player[Main.myPlayer].Male && flag2 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(145, false);
                }
                else if (!Main.player[Main.myPlayer].Male && flag7 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(146, false);
                }
                else if (!Main.player[Main.myPlayer].Male && flag4 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(147, false);
                }
                else if (!Main.dayTime)
                {
                    int num26 = Main.rand.Next(3);
                    if (num26 == 0)
                    {
                        text = Lang.dialog(148, false);
                    }
                    else if (num26 == 1)
                    {
                        text = Lang.dialog(149, false);
                    }
                    else if (num26 == 2)
                    {
                        text = Lang.dialog(150, false);
                    }
                }
                else
                {
                    int num27 = Main.rand.Next(5);
                    if (num27 == 0)
                    {
                        text = Lang.dialog(151, false);
                    }
                    else if (num27 == 1)
                    {
                        text = Lang.dialog(152, false);
                    }
                    else if (num27 == 2)
                    {
                        text = Lang.dialog(153, false);
                    }
                    else if (num27 == 3)
                    {
                        text = Lang.dialog(154, false);
                    }
                    else
                    {
                        text = Lang.dialog(155, false);
                    }
                }
            }
            else if (this.type == 123)
            {
                text = Lang.dialog(156, false);
            }
            else if (this.type == 124)
            {
                if (this.homeless)
                {
                    int num28 = Main.rand.Next(4);
                    if (num28 == 0)
                    {
                        text = Lang.dialog(157, false);
                    }
                    else if (num28 == 1)
                    {
                        text = Lang.dialog(158, false);
                    }
                    else if (num28 == 2)
                    {
                        text = Lang.dialog(159, false);
                    }
                    else
                    {
                        text = Lang.dialog(160, false);
                    }
                }
                else if (this.HasSpecialEventText("Mechanic", out text2))
                {
                    text = text2;
                }
                else if (Main.bloodMoon)
                {
                    int num29 = Main.rand.Next(4);
                    if (num29 == 0)
                    {
                        text = Lang.dialog(161, false);
                    }
                    else if (num29 == 1)
                    {
                        text = Lang.dialog(162, false);
                    }
                    else if (num29 == 2)
                    {
                        text = Lang.dialog(163, false);
                    }
                    else
                    {
                        text = Lang.dialog(164, false);
                    }
                }
                else if (flag8 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(165, false);
                }
                else if (flag3 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(166, false);
                }
                else
                {
                    LocalizedText[] array3 = Language.FindAll(Lang.CreateDialogFilter("MechanicChatter.", true));
                    int num30 = Main.rand.Next(3 + array3.Length);
                    if (num30 >= 3)
                    {
                        text = array3[num30 - 3].Value;
                    }
                    else if (num30 == 0)
                    {
                        text = Lang.dialog(167, false);
                    }
                    else if (num30 == 1)
                    {
                        text = Lang.dialog(168, false);
                    }
                    else
                    {
                        text = Lang.dialog(169, false);
                    }
                }
            }
            else if (this.type == 22)
            {
                if (this.HasSpecialEventText("Guide", out text2))
                {
                    text = text2;
                }
                else if (Main.bloodMoon)
                {
                    int num31 = Main.rand.Next(3);
                    if (num31 == 0)
                    {
                        text = Lang.dialog(170, false);
                    }
                    else if (num31 == 1)
                    {
                        text = Lang.dialog(171, false);
                    }
                    else
                    {
                        text = Lang.dialog(172, false);
                    }
                }
                else if (LanternNight.LanternsUp && !NPC.downedMoonlord)
                {
                    text = Language.GetTextValue("GuideSpecialText.Lantern1");
                }
                else if (LanternNight.LanternsUp && NPC.downedMoonlord)
                {
                    text = Language.GetTextValue("GuideSpecialText.Lantern2");
                }
                else if (Main.eclipse)
                {
                    text = Language.GetTextValue("GuideSpecialText.Eclipse");
                }
                else if (Main.slimeRain)
                {
                    text = Language.GetTextValue("GuideSpecialText.SlimeRain");
                }
                else if (!Main.dayTime)
                {
                    text = Lang.dialog(173, false);
                }
                else if (Main.hardMode && flag17 && Main.rand.Next(8) == 0)
                {
                    text = Language.GetTextValue("GuideChatter.Chatter_1");
                }
                else if (Main.hardMode && Main.rand.Next(8) == 0)
                {
                    text = Language.GetTextValue("GuideChatter.Chatter_2");
                }
                else
                {
                    int num32 = Main.rand.Next(3);
                    if (num32 == 0)
                    {
                        text = Lang.dialog(174, false);
                    }
                    else if (num32 == 1)
                    {
                        text = Lang.dialog(175, false);
                    }
                    else
                    {
                        text = Lang.dialog(176, false);
                    }
                }
            }
            else if (this.type == 142)
            {
                int num33 = Main.rand.Next(3);
                if (this.HasSpecialEventText("Santa", out text2))
                {
                    text = text2;
                }
                else if (num33 == 0)
                {
                    text = Lang.dialog(224, false);
                }
                else if (num33 == 1)
                {
                    text = Lang.dialog(225, false);
                }
                else if (num33 == 2)
                {
                    text = Lang.dialog(226, false);
                }
            }
            else if (this.type == 160)
            {
                int num34 = Main.rand.Next(6);
                if (this.HasSpecialEventText("Truffle", out text2))
                {
                    text = text2;
                }
                else if (flag4 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(232, false);
                }
                else if (flag9 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(236, false);
                }
                else if (num34 == 0)
                {
                    text = Lang.dialog(231, false);
                }
                else if (num34 == 1)
                {
                    text = Lang.dialog(233, false);
                }
                else if (num34 == 2)
                {
                    text = Lang.dialog(234, false);
                }
                else if (num34 == 3)
                {
                    text = Lang.dialog(235, false);
                }
                else if (num34 == 4)
                {
                    text = Lang.dialog(240, false);
                }
                else if (num34 == 5)
                {
                    text = Lang.dialog(241, false);
                }
            }
            else if (this.type == 178)
            {
                int num35 = Main.rand.Next(5);
                if (this.HasSpecialEventText("Steampunker", out text2))
                {
                    text = text2;
                }
                else if (Main.bloodMoon && Main.rand.Next(3) == 0)
                {
                    text = Lang.dialog(245, false);
                }
                else if (flag13 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(246, false);
                }
                else if (flag12 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(247, false);
                }
                else if (num35 == 0)
                {
                    text = Lang.dialog(242, false);
                }
                else if (num35 == 1)
                {
                    text = Lang.dialog(243, false);
                }
                else if (num35 == 2)
                {
                    text = Lang.dialog(244, false);
                }
                else if (num35 == 3)
                {
                    text = Lang.dialog(248, false);
                }
                else if (num35 == 4)
                {
                    text = Lang.dialog(249, false);
                }
            }
            else if (this.type == 207)
            {
                int num36 = Main.rand.Next(3);
                if (this.HasSpecialEventText("DyeTrader", out text2))
                {
                    text = text2;
                }
                else if (flag12 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(260, false);
                }
                else if (num36 == 0)
                {
                    text = Lang.dialog(257, false);
                }
                else if (num36 == 1)
                {
                    text = Lang.dialog(258, false);
                }
                else if (num36 == 2)
                {
                    text = Lang.dialog(259, false);
                }
            }
            else if (this.type == 208)
            {
                int num37 = Main.rand.Next(7);
                if (this.HasSpecialEventText("PartyGirl", out text2))
                {
                    text = text2;
                }
                else if (DD2Event.DownedInvasionT1 && Main.rand.Next(5) == 0)
                {
                    text = Language.GetTextValue("PartyGirlSpecialText.AfterDD2Tier1");
                }
                else if (Main.player[Main.myPlayer].Male && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(268, false);
                }
                else if (flag15 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(310, false);
                }
                else if (num37 == 0)
                {
                    text = Lang.dialog(265, false);
                }
                else if (num37 == 1)
                {
                    text = Lang.dialog(266, false);
                }
                else if (num37 == 2)
                {
                    text = Lang.dialog(267, false);
                }
                else if (num37 == 3)
                {
                    text = Lang.dialog(269, false);
                }
                else if (num37 == 4)
                {
                    text = Lang.dialog(270, false);
                }
                else if (num37 == 5)
                {
                    text = Lang.dialog(271, false);
                }
                else if (num37 == 6)
                {
                    text = Lang.dialog(272, false);
                }
            }
            else if (this.type == 209)
            {
                if (this.HasSpecialEventText("Cyborg", out text2))
                {
                    text = text2;
                }
                else if (flag12 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(284, false);
                }
                else if (flag11 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(283, false);
                }
                else
                {
                    LocalizedText[] array4 = Language.FindAll(Lang.CreateDialogFilter("CyborgChatter.", true));
                    int num38 = Main.rand.Next(5 + array4.Length);
                    if (num38 >= 5)
                    {
                        text = array4[num38 - 5].Value;
                    }
                    else if (num38 == 0)
                    {
                        text = Lang.dialog(280, false);
                    }
                    else if (num38 == 1)
                    {
                        text = Lang.dialog(281, false);
                    }
                    else if (num38 == 2)
                    {
                        text = Lang.dialog(282, false);
                    }
                    else if (num38 == 3)
                    {
                        text = Lang.dialog(285, false);
                    }
                    else if (num38 == 4)
                    {
                        text = Lang.dialog(286, false);
                    }
                }
            }
            else if (this.type == 227)
            {
                int num39 = Main.rand.Next(5);
                if (this.HasSpecialEventText("Painter", out text2))
                {
                    text = text2;
                }
                else if (Main.hardMode && Main.rand.Next(7) == 0)
                {
                    text = Lang.dialog(250, false);
                }
                else if (flag14 && Main.rand.Next(6) == 0)
                {
                    text = Lang.dialog(251, false);
                }
                else if (num39 == 0)
                {
                    text = Lang.dialog(252, false);
                }
                else if (num39 == 1)
                {
                    text = Lang.dialog(253, false);
                }
                else if (num39 == 2)
                {
                    text = Lang.dialog(254, false);
                }
                else if (num39 == 3)
                {
                    text = Lang.dialog(255, false);
                }
                else if (num39 == 4)
                {
                    text = Lang.dialog(256, false);
                }
            }
            else if (this.type == 228)
            {
                int num40 = Main.rand.Next(4);
                if (this.HasSpecialEventText("WitchDoctor", out text2))
                {
                    text = text2;
                }
                else if (flag2 && Main.rand.Next(4) == 0)
                {
                    text = Lang.dialog(263, false);
                }
                else if (num40 == 0)
                {
                    text = Lang.dialog(261, false);
                }
                else if (num40 == 1)
                {
                    text = Lang.dialog(262, false);
                }
                else if (num40 == 2)
                {
                    text = Lang.dialog(264, false);
                }
                else if (num40 == 3)
                {
                    text = Language.GetTextValue("WitchDoctorSpecialText.AfterDD2Tier1");
                }
            }
            else if (this.type == 229)
            {
                LocalizedText[] array5 = Language.FindAll(Lang.CreateDialogFilter("PirateChatter.", true));
                int num41 = Main.rand.Next(6 + array5.Length);
                if (num41 >= 6)
                {
                    text = array5[num41 - 6].Value;
                }
                else if (this.HasSpecialEventText("Pirate", out text2))
                {
                    text = text2;
                }
                else if (!Main.player[Main.myPlayer].Male && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(276, false);
                }
                else if (num41 == 0)
                {
                    text = Lang.dialog(273, false);
                }
                else if (num41 == 1)
                {
                    text = Lang.dialog(274, false);
                }
                else if (num41 == 2)
                {
                    text = Lang.dialog(275, false);
                }
                else if (num41 == 3)
                {
                    text = Lang.dialog(277, false);
                }
                else if (num41 == 4)
                {
                    text = Lang.dialog(278, false);
                }
                else if (num41 == 5)
                {
                    text = Lang.dialog(279, false);
                }
            }
            else if (this.type == 354)
            {
                text = Lang.dialog(Main.rand.Next(315, 319), false);
            }
            else if (this.type == 353)
            {
                if (this.HasSpecialEventText("Stylist", out text2))
                {
                    text = text2;
                }
                else if (Main.bloodMoon)
                {
                    int num42 = Main.rand.Next(3);
                    if (num42 == 0)
                    {
                        text = Lang.dialog(304, false);
                    }
                    else if (num42 == 1)
                    {
                        text = Lang.dialog(305, false);
                    }
                    else if (num42 == 2)
                    {
                        text = Lang.dialog(306, false);
                    }
                }
                else if (Main.dayTime && Main.time < 16200.0 && Main.rand.Next(3) == 0)
                {
                    text = Lang.dialog(311, false);
                }
                else if (Main.player[Main.myPlayer].Male && Main.rand.Next(3) == 0)
                {
                    int num43 = Main.rand.Next(2);
                    if (num43 == 0)
                    {
                        text = Lang.dialog(293, false);
                    }
                    else if (num43 == 1)
                    {
                        text = Lang.dialog(300, false);
                    }
                }
                else if (!Main.player[Main.myPlayer].Male && Main.rand.Next(3) == 0)
                {
                    int num44 = Main.rand.Next(3);
                    if (num44 == 0)
                    {
                        text = Lang.dialog(291, false);
                    }
                    else if (num44 == 1)
                    {
                        text = Lang.dialog(292, false);
                    }
                    else if (num44 == 2)
                    {
                        text = Lang.dialog(312, false);
                    }
                }
                else if (flag14 && flag7 && flag2 && flag3 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(307, false);
                }
                else if (flag14 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(302, false);
                }
                else if (flag6 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(303, false);
                }
                else if (flag13 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(308, false);
                }
                else
                {
                    LocalizedText[] array6 = Language.FindAll(Lang.CreateDialogFilter("StylistChatter.", true));
                    int num45 = ((Main.moonPhase < 3) ? 5 : 4);
                    int num46 = Main.rand.Next(num45 + array6.Length);
                    if (num46 >= num45)
                    {
                        text = array6[num46 - num45].Value;
                    }
                    else if (Main.moonPhase < 3)
                    {
                        if (num46 == 0)
{
                            text = Lang.dialog(287, false);
                        }
                        else if (num46 == 1)
{
                            text = Lang.dialog(288, false);
                        }
                        else if (num46 == 2)
{
                            text = Lang.dialog(289, false);
                        }
                        else if (num46 == 3)
{
                            text = Lang.dialog(290, false);
                        }
                        else if (num46 == 4)
{
                            text = Lang.dialog(294, false);
                        }
                    }
                    else if (Main.moonPhase < 6)
                    {
                        if (num46 == 0)
{
                            text = Lang.dialog(295, false);
                        }
                        else if (num46 == 1)
{
                            text = Lang.dialog(296, false);
                        }
                        else if (num46 == 2)
{
                            text = Lang.dialog(297, false);
                        }
                        else if (num46 == 3)
{
                            text = Lang.dialog(298, false);
                        }
                    }
                    else if (num46 == 0)
                    {
                        text = Lang.dialog(299, false);
                    }
                    else if (num46 == 1)
                    {
                        text = Lang.dialog(301, false);
                    }
                    else if (num46 == 2)
                    {
                        text = Lang.dialog(313, false);
                    }
                    else if (num46 == 3)
                    {
                        text = Lang.dialog(314, false);
                    }
                }
            }
            else if (this.type == 368)
            {
                if (this.HasSpecialEventText("TravellingMerchant", out text2))
                {
                    text = text2;
                }
                else if (flag16 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(319, false);
                }
                else if (flag && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(320, false);
                }
                else if (flag9 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(321, false);
                }
                else
                {
                    text = Lang.dialog(Main.rand.Next(322, 331), false);
                }
            }
            else if (this.type == 376)
            {
                text = Lang.dialog(Main.rand.Next(353, 356), false);
            }
            else if (this.type == 369)
            {
                if (Main.rand.Next(5) == 0 && Main.LocalPlayer.anglerQuestsFinished > 1)
                {
                    text = Lang.AnglerQuestCountChat();
                }
                else if (this.HasSpecialEventText("Angler", out text2))
                {
                    text = text2;
                }
                else if (Main.bloodMoon)
                {
                    if (Main.rand.Next(3) == 0)
                    {
                        text = Language.SelectRandom(Lang.CreateDialogFilter("AnglerSpecialText.BloodMoonFishing", true), null).Value;
                    }
                    else if (!Main.anglerQuestFinished)
                    {
                        text = Lang.dialog(Main.rand.Next(348, 350), false);
                    }
                    else
                    {
                        text = Lang.dialog(Main.rand.Next(350, 353), false);
                    }
                }
                else if (!Main.anglerQuestFinished)
                {
                    text = Lang.dialog(Main.rand.Next(334, 338), false);
                }
                else if (flag4 && Main.rand.Next(5) == 0)
                {
                    text = Lang.dialog(347, false);
                }
                else
                {
                    text = Language.SelectRandom(Lang.CreateDialogFilter("AnglerChatter.", true), null).Value;
                }
            }
            else if (this.type == 453)
            {
                if (this.HasSpecialEventText("SkeletonMerchant", out text2))
                {
                    text = text2;
                }
                else
                {
                    int num47 = 8;
                    int categorySize = Language.GetCategorySize("SkeletonMerchantChatter");
                    int num48 = Main.rand.Next(num47 + categorySize);
                    if (num48 < num47)
                    {
                        text = Lang.dialog(356 + num48, false);
                    }
                    else
                    {
                        text = Language.RandomFromCategory("SkeletonMerchantChatter", null).Value;
                    }
                }
            }
            else if (this.type == 441)
            {
                if (this.HasSpecialEventText("TaxCollector", out text2))
                {
                    text = text2;
                }
                else if (Main.rand.Next(6) == 0 && flag4)
                {
                    text = Lang.dialog(371, false);
                }
                else if (Main.rand.Next(6) == 0 && flag3)
                {
                    text = Lang.dialog(372, false);
                }
                else if (Main.rand.Next(6) == 0 && flag6)
                {
                    text = Lang.dialog(373, false);
                }
                else if (Main.rand.Next(6) == 0 && flag)
                {
                    text = Lang.dialog(374, false);
                }
                else
                {
                    text = Lang.dialog(Main.rand.Next(364, 371), false);
                }
            }
            else if (this.type == 579)
            {
                text = Language.GetTextValue("BartenderSpecialText.FirstMeeting");
            }
            else if (this.type == 550)
            {
                if (this.HasSpecialEventText("Bartender", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.BartenderChat();
                }
            }
            else if (this.type == 589)
            {
                if (Main.rand.Next(2) == 0)
                {
                    text = Language.GetTextValue("GolferSpecialText.FirstMeeting1");
                }
                else
                {
                    text = Language.GetTextValue("GolferSpecialText.FirstMeeting2");
                }
            }
            else if (this.type == 588)
            {
                if (Main.rand.Next(3) != 0 && this.HasSpecialEventText("Golfer", out text2))
                {
                    text = text2;
                }
                else if (Main.rand.Next(3) == 0)
                {
                    string text4;
                    if (Main.LocalPlayer.golferScoreAccumulated >= 2000)
                    {
                        text4 = "GolferQuestsChatterMaster";
                    }
                    else if (Main.LocalPlayer.golferScoreAccumulated >= 1000)
                    {
                        text4 = "GolferQuestsChatterJourneyman";
                    }
                    else if (Main.LocalPlayer.golferScoreAccumulated >= 500)
                    {
                        text4 = "GolferQuestsChatterApprentice";
                    }
                    else
                    {
                        text4 = "GolferQuestsChatterBeginner";
                    }
                    text = Language.SelectRandom(Lang.CreateDialogFilter(text4 + ".", true), null).Value;
                }
                else
                {
                    text = Lang.GolferChat();
                }
            }
            else if (this.type == 633)
            {
                if (!NPC.ShouldBestiaryGirlBeLycantrope() && this.HasSpecialEventText("BestiaryGirl", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.BestiaryGirlChat();
                }
            }
            else if (this.type == 663)
            {
                if (this.HasSpecialEventText("Princess", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.PrincessChat();
                }
            }
            else if (this.type == 637)
            {
                if (this.HasSpecialEventText("Cat", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.CatChat();
                }
            }
            else if (this.type == 638)
            {
                if (this.HasSpecialEventText("Dog", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.DogChat();
                }
            }
            else if (this.type == 656)
            {
                if (this.HasSpecialEventText("Bunny", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.BunnyChat();
                }
            }
            else if (NPCID.Sets.IsTownSlime[this.type])
            {
                if (this.HasSpecialEventText("Slime", out text2))
                {
                    text = text2;
                }
                else
                {
                    text = Lang.SlimeChat(this);
                }
            }
            return text;
        }
References Terraria.NPC.active, Terraria.Lang.AnglerQuestCountChat(), Terraria.Main.anglerQuestFinished, System.array, Terraria.Lang.BartenderChat(), Terraria.Lang.BestiaryGirlChat(), Terraria.Main.bloodMoon, Terraria.Lang.BunnyChat(), Terraria.Lang.CatChat(), Terraria.Lang.CreateDialogFilter(), Terraria.WorldGen.crimson, Terraria.Main.dayTime, Terraria.Lang.dialog(), Terraria.Lang.DogChat(), Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.GameContent.Events.DD2Event.DownedInvasionT1, Terraria.GameContent.Events.DD2Event.DownedInvasionT2, Terraria.NPC.downedMoonlord, Terraria.Main.eclipse, Terraria.Localization.Language.FindAll(), Terraria.Localization.Language.GetCategorySize(), Terraria.Localization.Language.GetTextValue(), Terraria.Lang.GolferChat(), Terraria.Player.golferScoreAccumulated, Terraria.Main.hardMode, Terraria.Player.HasItem(), Terraria.Player.head, Terraria.ID.NPCID.Sets.IsTownSlime, Terraria.GameContent.Events.LanternNight.LanternsUp, Terraria.Main.LocalPlayer, Terraria.Player.Male, Terraria.Main.maxNPCs, Terraria.Main.moonPhase, Terraria.Main.myPlayer, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Player.numberOfDeathsPVE, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Main.player, Terraria.Lang.PrincessChat(), Terraria.Main.rand, Terraria.Localization.Language.RandomFromCategory(), Terraria.Main.remixWorld, Terraria.Localization.Language.SelectRandom(), Terraria.NPC.ShouldBestiaryGirlBeLycantrope(), Terraria.Lang.SlimeChat(), Terraria.Main.slimeRain, Terraria.Player.statDefense, Terraria.Player.statLife, Terraria.Player.statLifeMax, Terraria.Player.statLifeMax2, System.text, Terraria.Main.time, Terraria.NPC.type, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.Main.HoverOverNPCs(), and Terraria.GameContent.UI.NPCChatPanel.OverrideChatTextWithShenanigans().