Terraria Decompiled: Terraria.NPC.TargetClosest
TargetClosest()
void Terraria.NPC.TargetClosest (bool faceTarget = true) inline
Definition at line 76140 of file NPC.cs.
        {
            float num = 0f;
            float num2 = 0f;
            bool flag = false;
            int num3 = -1;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active && !Main.player[i].dead && !Main.player[i].ghost)
                {
                    this.TryTrackingTarget(ref num, ref num2, ref flag, ref num3, i);
                }
            }
            this.SetTargetTrackingValues(faceTarget, num2, num3);
        }
References Terraria.Player.active, Terraria.Player.dead, Terraria.Player.ghost, Terraria.Main.player, Terraria.NPC.SetTargetTrackingValues(), and Terraria.NPC.TryTrackingTarget().
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_002_FloatingEye(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_015_KingSlime(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_047_GolemFist(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.NPC.AI_122_PirateGhost(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.NPC.AI_126_StatueMimic(), Terraria.NPC.AI_127_Pal(), Terraria.WorldGen.CheckSuper(), Terraria.Cinematics.DSTFilm.DeerclopsAttack(), Terraria.WorldGen.KillTile_DropBait(), Terraria.NPC.ReleaseNPC(), Terraria.Utilities.NPCUtils.TargetClosestCommon(), and Terraria.Cinematics.DSTFilm.TurnPlayerToTheLeft().