Terraria Decompiled: Terraria.NPC.AI_015_KingSlime
AI_015_KingSlime()
void Terraria.NPC.AI_015_KingSlime () inline private
Definition at line 39852 of file NPC.cs.
        {
            float num = 1f;
            float num2 = 1f;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            float num3 = 2f;
            if (Main.getGoodWorld)
            {
                num3 -= 1f - (float)this.life / (float)this.lifeMax;
                num2 *= num3;
            }
            this.aiAction = 0;
            if (this.ai[3] == 0f && this.life > 0)
            {
                this.ai[3] = (float)this.lifeMax;
            }
            if (this.localAI[3] == 0f)
            {
                this.localAI[3] = 1f;
                flag = true;
                if (Main.netMode != 1)
                {
                    this.ai[0] = -100f;
                    this.TargetClosest(true);
                    this.netUpdate = true;
                }
            }
            int num4 = 3000;
            if (Main.player[this.target].dead || Vector2.Distance(base.Center, Main.player[this.target].Center) > (float)num4)
            {
                this.TargetClosest(true);
                if (Main.player[this.target].dead || Vector2.Distance(base.Center, Main.player[this.target].Center) > (float)num4)
                {
                    this.EncourageDespawn(10);
                    if (Main.player[this.target].Center.X < base.Center.X)
                    {
                        this.direction = 1;
                    }
                    else
                    {
                        this.direction = -1;
                    }
                    if (Main.netMode != 1 && this.ai[1] != 5f)
                    {
                        this.netUpdate = true;
                        this.ai[2] = 0f;
                        this.ai[0] = 0f;
                        this.ai[1] = 5f;
                        this.localAI[1] = (float)(Main.maxTilesX * 16);
                        this.localAI[2] = (float)(Main.maxTilesY * 16);
                    }
                }
            }
            if (!Main.player[this.target].dead && this.timeLeft > 10 && this.ai[2] >= 300f && this.ai[1] < 5f && this.velocity.Y == 0f)
            {
                this.ai[2] = 0f;
                this.ai[0] = 0f;
                this.ai[1] = 5f;
                if (Main.netMode != 1)
                {
                    this.TargetClosest(false);
                    base.Center.ToTileCoordinates();
                    Main.player[this.target].Center.ToTileCoordinates();
                    Vector2 vector = Main.player[this.target].Center - base.Center;
                    bool flag4 = false;
                    if (this.localAI[0] >= 360f || vector.Length() > 2000f)
                    {
                        if (this.localAI[0] >= 360f)
{
                            this.localAI[0] = 360f;
                        }
                        flag4 = true;
                    }
                    this.AI_015_KingSlime_FindTeleportSpot(flag4, ref this.localAI[1], ref this.localAI[2]);
                }
            }
            if (!Collision.CanHitLine(base.Center, 0, 0, Main.player[this.target].Center, 0, 0) || Math.Abs(base.Top.Y - Main.player[this.target].Bottom.Y) > 160f)
            {
                this.ai[2] += 1f;
                if (Main.netMode != 1)
                {
                    this.localAI[0] += 1f;
                }
            }
            else if (Main.netMode != 1)
            {
                this.localAI[0] -= 1f;
                if (this.localAI[0] < 0f)
                {
                    this.localAI[0] = 0f;
                }
            }
            if (this.timeLeft < 10 && (this.ai[0] != 0f || this.ai[1] != 0f))
            {
                this.ai[0] = 0f;
                this.ai[1] = 0f;
                this.netUpdate = true;
                flag2 = false;
            }
            if (this.ai[1] == 5f)
            {
                flag2 = true;
                this.aiAction = 1;
                this.ai[0] += 1f;
                num = MathHelper.Clamp((60f - this.ai[0]) / 60f, 0f, 1f);
                num = 0.5f + num * 0.5f;
                if (this.ai[0] >= 60f)
                {
                    flag3 = true;
                }
                if (this.ai[0] == 60f)
                {
                    Gore.NewGore(base.Center + new Vector2(-40f, (float)(-(float)this.height / 2)), this.velocity, 734, 1f);
                }
                if (this.ai[0] >= 60f && Main.netMode != 1)
                {
                    base.Bottom = new Vector2(this.localAI[1], this.localAI[2]);
                    this.ai[1] = 6f;
                    this.ai[0] = 0f;
                    this.netUpdate = true;
                }
                if (Main.netMode == 1 && this.ai[0] >= 120f)
                {
                    this.ai[1] = 6f;
                    this.ai[0] = 0f;
                }
                if (!flag3)
                {
                    for (int i = 0; i < 10; i++)
                    {
                        int num5 = Dust.NewDust(this.position + Vector2.UnitX * -20f, this.width + 40, this.height, 4, this.velocity.X, this.velocity.Y, 150, new Color(78, 136, 255, 80), 2f);
                        Main.dust[num5].noGravity = true;
                        Main.dust[num5].velocity *= 0.5f;
                    }
                }
            }
            else if (this.ai[1] == 6f)
            {
                flag2 = true;
                this.aiAction = 0;
                this.ai[0] += 1f;
                num = MathHelper.Clamp(this.ai[0] / 30f, 0f, 1f);
                num = 0.5f + num * 0.5f;
                if (this.ai[0] >= 30f && Main.netMode != 1)
                {
                    this.ai[1] = 0f;
                    this.ai[0] = 0f;
                    this.netUpdate = true;
                    this.TargetClosest(true);
                }
                if (Main.netMode == 1 && this.ai[0] >= 60f)
                {
                    this.ai[1] = 0f;
                    this.ai[0] = 0f;
                    this.TargetClosest(true);
                }
                for (int j = 0; j < 10; j++)
                {
                    int num6 = Dust.NewDust(this.position + Vector2.UnitX * -20f, this.width + 40, this.height, 4, this.velocity.X, this.velocity.Y, 150, new Color(78, 136, 255, 80), 2f);
                    Main.dust[num6].noGravity = true;
                    Main.dust[num6].velocity *= 2f;
                }
            }
            this.dontTakeDamage = (this.hide = flag3);
            if (this.velocity.Y == 0f)
            {
                this.velocity.X = this.velocity.X * 0.8f;
                if (this.velocity.X > -0.1f && this.velocity.X < 0.1f)
                {
                    this.velocity.X = 0f;
                }
                if (!flag2)
                {
                    this.ai[0] += 2f;
                    if ((float)this.life < (float)this.lifeMax * 0.8f)
                    {
                        this.ai[0] += 1f;
                    }
                    if ((float)this.life < (float)this.lifeMax * 0.6f)
                    {
                        this.ai[0] += 1f;
                    }
                    if ((float)this.life < (float)this.lifeMax * 0.4f)
                    {
                        this.ai[0] += 2f;
                    }
                    if ((float)this.life < (float)this.lifeMax * 0.2f)
                    {
                        this.ai[0] += 3f;
                    }
                    if ((float)this.life < (float)this.lifeMax * 0.1f)
                    {
                        this.ai[0] += 4f;
                    }
                    if (this.ai[0] >= 0f)
                    {
                        this.netUpdate = true;
                        this.TargetClosest(true);
                        if (this.ai[1] == 3f)
{
                            this.velocity.Y = -13f;
                            this.velocity.X = this.velocity.X + 3.5f * (float)this.direction;
                            this.ai[0] = -200f;
                            this.ai[1] = 0f;
                        }
                        else if (this.ai[1] == 2f)
{
                            this.velocity.Y = -6f;
                            this.velocity.X = this.velocity.X + 4.5f * (float)this.direction;
                            this.ai[0] = -120f;
                            this.ai[1] += 1f;
                        }
                        else
{
                            this.velocity.Y = -8f;
                            this.velocity.X = this.velocity.X + 4f * (float)this.direction;
                            this.ai[0] = -120f;
                            this.ai[1] += 1f;
                        }
                    }
                    else if (this.ai[0] >= -30f)
                    {
                        this.aiAction = 1;
                    }
                }
            }
            else if (this.target < 255)
            {
                float num7 = 3f;
                if (Main.getGoodWorld)
                {
                    num7 = 6f;
                }
                if ((this.direction == 1 && this.velocity.X < num7) || (this.direction == -1 && this.velocity.X > -num7))
                {
                    if ((this.direction == -1 && this.velocity.X < 0.1f) || (this.direction == 1 && this.velocity.X > -0.1f))
                    {
                        this.velocity.X = this.velocity.X + 0.2f * (float)this.direction;
                    }
                    else
                    {
                        this.velocity.X = this.velocity.X * 0.93f;
                    }
                }
            }
            int num8 = Dust.NewDust(this.position, this.width, this.height, 4, this.velocity.X, this.velocity.Y, 255, new Color(0, 80, 255, 80), this.scale * 1.2f);
            Main.dust[num8].noGravity = true;
            Main.dust[num8].velocity *= 0.5f;
            if (this.life > 0)
            {
                float num9 = (float)this.life / (float)this.lifeMax;
                num9 = num9 * 0.5f + 0.75f;
                num9 *= num;
                num9 *= num2;
                if (num9 != this.scale || flag)
                {
                    this.position.X = this.position.X + (float)(this.width / 2);
                    this.position.Y = this.position.Y + (float)this.height;
                    this.scale = num9;
                    this.width = (int)(98f * this.scale);
                    this.height = (int)(92f * this.scale);
                    this.position.X = this.position.X - (float)(this.width / 2);
                    this.position.Y = this.position.Y - (float)this.height;
                }
                if (Main.netMode != 1)
                {
                    int num10 = (int)((float)this.lifeMax * 0.05f);
                    if ((float)(this.life + num10) < this.ai[3])
                    {
                        this.ai[3] = (float)this.life;
                        int num11 = Main.rand.Next(1, 4);
                        for (int k = 0; k < num11; k++)
{
                            int num12 = (int)(this.position.X + (float)Main.rand.Next(this.width - 32));
                            int num13 = (int)(this.position.Y + (float)Main.rand.Next(this.height - 32));
                            int num14 = 1;
                            if (Main.expertMode && Main.rand.Next(4) == 0)
{
                                num14 = 535;
                            }
                            int num15 = NPC.NewNPC(this.GetSpawnSourceForProjectileNPC(), num12, num13, num14, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num15].SetDefaults(num14, default(NPCSpawnParams));
                            Main.npc[num15].velocity.X = (float)Main.rand.Next(-15, 16) * 0.1f;
                            Main.npc[num15].velocity.Y = (float)Main.rand.Next(-30, 1) * 0.1f;
                            Main.npc[num15].ai[0] = (float)(-1000 * Main.rand.Next(3));
                            Main.npc[num15].ai[1] = 0f;
                            if (Main.netMode == 2 && num15 < Main.maxNPCs)
{
                                NetMessage.SendData(23, -1, -1, null, num15, 0f, 0f, 0f, 0, 0, 0);
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.NPC.ai, Terraria.NPC.AI_015_KingSlime_FindTeleportSpot(), Terraria.Entity.Bottom, Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Player.dead, Terraria.Entity.direction, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.Main.expertMode, Terraria.Main.getGoodWorld, Terraria.NPC.GetSpawnSourceForProjectileNPC(), Terraria.Entity.height, int, Microsoft.Xna.Framework.Vector2.Length(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Main.npc, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.scale, Terraria.NetMessage.SendData(), Terraria.NPC.SetDefaults(), Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.NPC.timeLeft, Microsoft.Xna.Framework.Vector2.UnitX, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().