Terraria Decompiled: Terraria.NPC.CheckActive
CheckActive()
void Terraria.NPC.CheckActive () inline
Definition at line 76455 of file NPC.cs.
        {
            if (this.active)
            {
                if (this.type == 690 && this.ai[0] == 0f)
                {
                    return;
                }
                if (this.DoesntDespawnToInactivity())
                {
                    return;
                }
                if (this.townNPC)
                {
                    return;
                }
                bool flag = this.DoesntDespawnToInactivityAndCountsNPCSlots();
                bool flag2 = false;
                Rectangle rectangle = new Rectangle((int)(this.position.X + (float)(this.width / 2) - (float)NPC.activeRangeX), (int)(this.position.Y + (float)(this.height / 2) - (float)NPC.activeRangeY), NPC.activeRangeX * 2, NPC.activeRangeY * 2);
                Rectangle rectangle2 = new Rectangle((int)((double)(this.position.X + (float)(this.width / 2)) - (double)NPC.sWidth * 0.5 - (double)this.width), (int)((double)(this.position.Y + (float)(this.height / 2)) - (double)NPC.sHeight * 0.5 - (double)this.height), NPC.sWidth + this.width * 2, NPC.sHeight + this.height * 2);
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active)
                    {
                        Rectangle hitbox = Main.player[i].Hitbox;
                        if (rectangle.Intersects(hitbox))
{
                            flag2 = true;
                            if (this.type != 25 && this.type != 30 && this.type != 33 && this.releaseOwner == 255 && this.lifeMax > 0)
{
                                if (Main.slimeRain && Main.slimeRainNPC[this.type])
{
                                    Main.player[i].nearbyActiveNPCs += this.npcSlots * Main.slimeRainNPCSlots;
                                }
                                else
{
                                    Main.player[i].nearbyActiveNPCs += this.npcSlots;
                                }
                            }
                        }
                        if (!flag)
{
                            if (rectangle2.Intersects(hitbox))
{
                                this.timeLeft = NPC.activeTime;
                                this.despawnEncouraged = false;
                                if (i == Main.myPlayer && (this.type == 604 || this.type == 605))
{
                                    this.LadyBugLuck(i, this.type == 605);
                                }
                            }
                            if (this.boss)
{
                                flag2 = true;
                            }
                            int num = this.type;
                            if (num <= 39)
{
                                if (num <= 10)
{
                                    if (num != 7 && num != 10)
{
                                        goto IL_030E;
                                    }
                                }
                                else if (num != 13 && num - 35 > 1 && num != 39)
{
                                    goto IL_030E;
                                }
                            }
                            else if (num <= 394)
{
                                if (num != 87 && num - 127 > 4 && num - 392 > 2)
{
                                    goto IL_030E;
                                }
                            }
                            else
{
                                if (num == 399)
{
                                    if (this.ai[0] == 2f || this.ai[0] == 1f)
{
                                        this.timeLeft = NPC.activeTime;
                                    }
                                    flag2 = true;
                                    goto IL_030E;
                                }
                                if (num - 491 > 1)
{
                                    if (num - 583 > 2)
{
                                        goto IL_030E;
                                    }
                                    if (!Main.dayTime && this.ai[2] == 0f)
{
                                        flag2 = true;
                                        this.timeLeft = NPC.activeTime;
                                        goto IL_030E;
                                    }
                                    goto IL_030E;
                                }
                            }
                            flag2 = true;
                        }
                    }
                    IL_030E:;
                }
                if (flag)
                {
                    return;
                }
                this.timeLeft--;
                if (this.timeLeft <= 0)
                {
                    flag2 = false;
                }
                if (!flag2 && Main.netMode != 1)
                {
                    NPC.noSpawnCycle = true;
                    this.active = false;
                    if (Main.netMode == 2)
                    {
                        this.life = 0;
                        NetMessage.SendData(23, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    }
                    if (this.extraValue > 0)
                    {
                        NPC.RevengeManager.CacheEnemy(this);
                    }
                    this.CheckActive_WormSegments();
                }
            }
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.NPC.activeRangeX, Terraria.NPC.activeRangeY, Terraria.NPC.activeTime, Terraria.NPC.ai, Terraria.NPC.boss, Terraria.GameContent.CoinLossRevengeSystem.CacheEnemy(), Terraria.NPC.CheckActive_WormSegments(), Terraria.Main.dayTime, Terraria.NPC.DoesntDespawnToInactivity(), Terraria.NPC.DoesntDespawnToInactivityAndCountsNPCSlots(), Terraria.NPC.extraValue, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.NPC.LadyBugLuck(), Terraria.NPC.lifeMax, Terraria.Main.myPlayer, Terraria.Player.nearbyActiveNPCs, Terraria.Main.netMode, Terraria.NPC.npcSlots, Terraria.Main.player, Terraria.Entity.position, Terraria.NPC.releaseOwner, Terraria.NPC.RevengeManager, Terraria.NetMessage.SendData(), Terraria.NPC.sHeight, Terraria.Main.slimeRain, Terraria.Main.slimeRainNPC, Terraria.Main.slimeRainNPCSlots, Terraria.NPC.sWidth, Terraria.NPC.timeLeft, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Entity.whoAmI, and Microsoft.Xna.Framework.Vector2.X.