Terraria Decompiled: Terraria.NPC.UpdateNPC
UpdateNPC()
void Terraria.NPC.UpdateNPC (int i) inline
Definition at line 91111 of file NPC.cs.
        {
            this.whoAmI = i;
            if (this.active)
            {
                if (Main.netMode == 2 || NPC.offSetDelayTime > 0 || Main.multiplayerNPCSmoothingRange <= 0 || NPCID.Sets.NoMultiplayerSmoothingByType[this.type] || NPCID.Sets.NoMultiplayerSmoothingByAI[this.aiStyle] || (this.townNPC && this.ai[0] == 25f))
                {
                    this.netOffset *= 0f;
                }
                else if (DebugOptions.FakeNetOffset != Vector2.Zero)
                {
                    this.netOffset = DebugOptions.FakeNetOffset;
                }
                else if (this.netOffset != new Vector2(0f, 0f))
                {
                    float num = 2f;
                    float num2 = (float)Main.multiplayerNPCSmoothingRange;
                    float num3 = this.netOffset.Length();
                    if (num3 > num2)
                    {
                        this.netOffset.Normalize();
                        this.netOffset *= num2;
                        num3 = this.netOffset.Length();
                    }
                    num += num3 / num2 * num;
                    Vector2 vector = this.netOffset;
                    vector.Normalize();
                    vector *= num;
                    this.netOffset -= vector;
                    if (this.netOffset.Length() < num)
                    {
                        this.netOffset *= 0f;
                    }
                    if (this.townNPC && Vector2.Distance(this.position, new Vector2((float)(this.homeTileX * 16 + 8 - this.width / 2), (float)(this.homeTileY * 16 - this.height) - 0.1f)) < 1f)
                    {
                        this.netOffset *= 0f;
                    }
                    if (this.netOffset != Vector2.Zero && DebugOptions.ShowNetOffsetDust)
                    {
                        Dust.QuickDust(this.position + this.netOffset, Color.Green).scale = 0.5f;
                    }
                }
                this.UpdateAltTexture();
                if (this.type == 368)
                {
                    NPC.travelNPC = true;
                }
                if (Main.netMode != 2)
                {
                    this.UpdateNPC_CastLights();
                }
                this.UpdateNPC_TeleportVisuals();
                this.UpdateNPC_CritterSounds();
                if (this.lookForHomeTimeout > 0)
                {
                    this.lookForHomeTimeout--;
                }
                this.TrySyncingUniqueTownNPCData(i);
                if (this.aiStyle == 7 && this.position.Y > Main.bottomWorld - 640f + (float)this.height && Main.netMode != 1)
                {
                    this.StrikeNPCNoInteraction(9999, 0f, 0, false, false, false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(28, -1, -1, null, this.whoAmI, 9999f, 0f, 0f, 0, 0, 0);
                    }
                }
                if (Main.netMode == 1 && NPCID.Sets.SkipUpdateInUnsyncedTiles[this.type])
                {
                    bool flag = false;
                    int num4 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                    int num5 = (int)(this.position.Y + (float)(this.height / 2)) / 16;
                    try
                    {
                        if (num4 >= 4 && num4 <= Main.maxTilesX - 4 && num5 >= 4 && num5 <= Main.maxTilesY - 4)
{
                            if (Main.tile[num4, num5] == null)
{
                                flag = true;
                            }
                            else if (Main.tile[num4 - 3, num5] == null)
{
                                flag = true;
                            }
                            else if (Main.tile[num4 + 3, num5] == null)
{
                                flag = true;
                            }
                            else if (Main.tile[num4, num5 - 3] == null)
{
                                flag = true;
                            }
                            else if (Main.tile[num4, num5 + 3] == null)
{
                                flag = true;
                            }
                        }
                    }
                    catch
                    {
                        flag = true;
                    }
                    if (flag)
                    {
                        return;
                    }
                }
                this.UpdateNPC_BuffFlagsReset();
                this.UpdateNPC_BuffSetFlags(true);
                this.UpdateNPC_SoulDrainDebuff();
                this.UpdateNPC_BuffClearExpiredBuffs();
                this.UpdateNPC_BuffApplyDOTs();
                this.UpdateNPC_BuffApplyVFX();
                this.UpdateNPC_BloodMoonTransformations();
                float num6;
                this.UpdateNPC_UpdateGravity(out num6);
                if (this.soundDelay > 0)
                {
                    this.soundDelay--;
                }
                if (this.life <= 0)
                {
                    this.active = false;
                    this.UpdateNetworkCode(i);
                    this.netUpdate = false;
                    this.justHit = false;
                    return;
                }
                this.oldTarget = this.target;
                this.oldDirection = this.direction;
                this.oldDirectionY = this.directionY;
                float num7 = 1f + Math.Abs(this.velocity.X) / 3f;
                if (this.gfxOffY > 0f)
                {
                    this.gfxOffY -= num7 * this.stepSpeed;
                    if (this.gfxOffY < 0f)
                    {
                        this.gfxOffY = 0f;
                    }
                }
                else if (this.gfxOffY < 0f)
                {
                    this.gfxOffY += num7 * this.stepSpeed;
                    if (this.gfxOffY > 0f)
                    {
                        this.gfxOffY = 0f;
                    }
                }
                if (this.gfxOffY > 16f)
                {
                    this.gfxOffY = 16f;
                }
                if (this.gfxOffY < -16f)
                {
                    this.gfxOffY = -16f;
                }
                this.TryPortalJumping();
                this.IdleSounds();
                this.AI();
                this.SubAI_HandleTemporaryCatchableNPCPlayerInvulnerability();
                if (Main.netMode != 2 && this.extraValue > 0)
                {
                    int num8 = 244;
                    float num9 = 30f;
                    if (this.extraValue >= 1000000)
                    {
                        num8 = 247;
                        num9 *= 0.25f;
                    }
                    else if (this.extraValue >= 10000)
                    {
                        num8 = 246;
                        num9 *= 0.5f;
                    }
                    else if (this.extraValue >= 100)
                    {
                        num8 = 245;
                        num9 *= 0.75f;
                    }
                    if (Main.rand.Next((int)num9) == 0)
                    {
                        this.position += this.netOffset;
                        int num10 = Dust.NewDust(this.position, this.width, this.height, num8, 0f, 0f, 254, default(Color), 0.25f);
                        Main.dust[num10].velocity *= 0.1f;
                        this.position -= this.netOffset;
                    }
                }
                for (int j = 0; j < 256; j++)
                {
                    if (this.immune[j] > 0)
                    {
                        this.immune[j]--;
                    }
                }
                if (!this.noGravity && !this.noTileCollide)
                {
                    int num11 = (int)(this.position.X + (float)(this.width / 2)) / 16;
                    int num12 = (int)(this.position.Y + (float)(this.height / 2)) / 16;
                    if (WorldGen.InWorld(num11, num12, 0) && Main.tile[num11, num12] == null)
                    {
                        NPC.gravity = 0f;
                        this.velocity.X = 0f;
                        this.velocity.Y = 0f;
                    }
                }
                if (!this.noGravity)
                {
                    this.velocity.Y = this.velocity.Y + NPC.gravity;
                    if (this.velocity.Y > num6)
                    {
                        this.velocity.Y = num6;
                    }
                }
                if ((double)this.velocity.X < 0.005 && (double)this.velocity.X > -0.005)
                {
                    this.velocity.X = 0f;
                }
                if (Main.netMode != 1 && this.type != 37 && (this.friendly || NPCID.Sets.TakesDamageFromHostilesWithoutBeingFriendly[this.type]))
                {
                    if (this.townNPC)
                    {
                        this.CheckDrowning();
                    }
                    this.CheckLifeRegen();
                    this.GetHurtByOtherNPCs(NPCID.Sets.AllNPCs);
                }
                if (Main.netMode != 1 && (NPC.npcsFoundForCheckActive[210] || NPC.npcsFoundForCheckActive[211]) && NPCID.Sets.CanBeHurtByBees[this.type] && (this.type != 1 || (this.ai[1] != 1124f && this.ai[1] != 1125f)))
                {
                    this.GetHurtByOtherNPCs(NPCID.Sets.HurtingBees);
                }
                if (!this.noTileCollide)
                {
                    this.UpdateCollision();
                }
                else
                {
                    this.oldPosition = this.position;
                    this.oldDirection = this.direction;
                    this.position += this.velocity;
                    if (Collision.WetCollision(this.position, this.width, this.height))
                    {
                        this.TryRemovingWaterPerishableEffects(false);
                    }
                }
                if (Main.netMode != 1 && !this.noTileCollide && this.lifeMax > 1 && Collision.SwitchTiles(this, this.position, this.width, this.height, this.oldPosition, 2) && (this.type == 46 || this.type == 148 || this.type == 149 || this.type == 303 || this.type == 361 || this.type == 362 || this.type == 364 || this.type == 366 || this.type == 367 || (this.type >= 442 && this.type <= 448) || this.type == 602 || this.type == 608 || this.type == 614 || this.type == 687))
                {
                    this.ai[0] = 1f;
                    this.ai[1] = 400f;
                    this.ai[2] = 0f;
                }
                this.CheckDialogue();
                this.FindFrame();
                this.UpdateNPC_UpdateTrails();
                this.UpdateNetworkCode(i);
                this.CheckActive();
                this.netUpdate = false;
                this.justHit = false;
            }
        }
References System.Math.Abs(), Terraria.ID.NPCID.Sets.AllNPCs, Terraria.Main.bottomWorld, Terraria.ID.NPCID.Sets.CanBeHurtByBees, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Testing.DebugOptions.FakeNetOffset, Terraria.NPC.gravity, Microsoft.Xna.Framework.Color.Green, Terraria.ID.NPCID.Sets.HurtingBees, int, Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesY, Terraria.Main.multiplayerNPCSmoothingRange, Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.NPCID.Sets.NoMultiplayerSmoothingByAI, Terraria.ID.NPCID.Sets.NoMultiplayerSmoothingByType, Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.NPC.npcsFoundForCheckActive, Terraria.NPC.offSetDelayTime, Terraria.Dust.QuickDust(), Terraria.Main.rand, Terraria.Dust.scale, Terraria.NetMessage.SendData(), Terraria.Testing.DebugOptions.ShowNetOffsetDust, Terraria.ID.NPCID.Sets.SkipUpdateInUnsyncedTiles, Terraria.Collision.SwitchTiles(), Terraria.ID.NPCID.Sets.TakesDamageFromHostilesWithoutBeingFriendly, Terraria.Main.tile, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Dust.velocity, Terraria.Collision.WetCollision(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Main.DoUpdateInWorld().