Terraria Decompiled: Terraria.NPC.AI_120_HallowBoss_DashTo
AI_120_HallowBoss_DashTo()
void Terraria.NPC.AI_120_HallowBoss_DashTo (Vector2 targetPosition) inline private
Definition at line 43786 of file NPC.cs.
        {
            base.DirectionTo(targetPosition);
            targetPosition += new Vector2(0f, -300f);
            if (base.Distance(targetPosition) > 200f)
            {
                targetPosition -= base.DirectionTo(targetPosition) * 100f;
            }
            Vector2 vector = targetPosition - base.Center;
            float lerpValue = Utils.GetLerpValue(100f, 600f, vector.Length(), true);
            float num = vector.Length();
            if (num > 18f)
            {
                num = 18f;
            }
            this.velocity = Vector2.Lerp(vector.SafeNormalize(Vector2.Zero) * num, vector / 6f, lerpValue);
        }
References Terraria.Utils.GetLerpValue(), Microsoft.Xna.Framework.Vector2.Length(), Microsoft.Xna.Framework.Vector2.Lerp(), Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.AI_120_HallowBoss().