Terraria Decompiled: Terraria.NPC.GetNPCInvasionGroup
GetNPCInvasionGroup()
static int Terraria.NPC.GetNPCInvasionGroup (int npcID) inline static
Definition at line 76921 of file NPC.cs.
        {
            int num = 0;
            if (npcID > 252)
            {
                if (npcID <= 472)
                {
                    switch (npcID)
                    {
                    case 305:
                    case 306:
                    case 307:
                    case 308:
                    case 309:
                    case 310:
                    case 311:
                    case 312:
                    case 313:
                    case 314:
                    case 315:
                    case 325:
                    case 326:
                    case 327:
                    case 329:
                    case 330:
                        return -2;
                    case 316:
                    case 317:
                    case 318:
                    case 319:
                    case 320:
                    case 321:
                    case 322:
                    case 323:
                    case 324:
                    case 328:
                    case 331:
                    case 332:
                    case 333:
                    case 334:
                    case 335:
                    case 336:
                    case 337:
                        return num;
                    case 338:
                    case 339:
                    case 340:
                    case 341:
                    case 342:
                    case 343:
                    case 344:
                    case 345:
                    case 346:
                    case 347:
                    case 348:
                    case 349:
                    case 350:
                    case 351:
                    case 352:
                        return -1;
                    default:
                        switch (npcID)
{
                        case 381:
                        case 382:
                        case 383:
                        case 385:
                        case 386:
                        case 387:
                        case 388:
                        case 389:
                        case 390:
                        case 391:
                        case 394:
                        case 395:
                            break;
                        case 384:
                        case 392:
                        case 393:
                            return num;
                        default:
                            if (npcID - 471 > 1)
{
                                return num;
                            }
                            goto IL_0290;
                        }
                        break;
                    }
                }
                else
                {
                    if (npcID - 491 <= 1)
                    {
                        goto IL_0298;
                    }
                    switch (npcID)
                    {
                    case 520:
                        break;
                    case 521:
                    case 522:
                    case 523:
                    case 524:
                    case 525:
                    case 526:
                    case 527:
                    case 528:
                    case 529:
                    case 530:
                    case 531:
                    case 532:
                    case 533:
                    case 534:
                    case 535:
                    case 536:
                    case 537:
                    case 538:
                    case 539:
                    case 540:
                    case 541:
                    case 542:
                    case 543:
                    case 544:
                    case 545:
                    case 546:
                    case 550:
                        return num;
                    case 547:
                    case 548:
                    case 549:
                    case 551:
                    case 552:
                    case 553:
                    case 554:
                    case 555:
                    case 556:
                    case 557:
                    case 558:
                    case 559:
                    case 560:
                    case 561:
                    case 562:
                    case 563:
                    case 564:
                    case 565:
                    case 566:
                    case 567:
                    case 568:
                    case 569:
                    case 570:
                    case 571:
                    case 572:
                    case 573:
                    case 574:
                    case 575:
                    case 576:
                    case 577:
                    case 578:
                        return -3;
                    default:
                        if (npcID != 662)
{
                            return num;
                        }
                        goto IL_0298;
                    }
                }
                return 4;
            }
            if (npcID <= 111)
            {
                if (npcID - 26 > 3 && npcID != 111)
                {
                    return num;
                }
            }
            else
            {
                if (npcID - 143 <= 2)
                {
                    return 2;
                }
                if (npcID - 212 > 4 && npcID != 252)
                {
                    return num;
                }
                goto IL_0298;
            }
            IL_0290:
            return 1;
            IL_0298:
            num = 3;
            return num;
        }
Referenced by Terraria.Player.AllowShimmerDodge(), Terraria.NPC.checkDead(), Terraria.Main.CheckInvasionProgressDisplay(), Terraria.GameContent.InvasionDamageTracker.IncludeDamageFor(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.IsInvalid(), Terraria.NPC.ScaleStats_ByDifficulty_Tweaks(), and Terraria.NPC.ScaleStats_ByPlayerCount().