Terraria Decompiled: Terraria.NPC.NPCLoot_DropMoney
NPCLoot_DropMoney()
void Terraria.NPC.NPCLoot_DropMoney (Player closestPlayer) inline private
Definition at line 78606 of file NPC.cs.
        {
            float num = 0f;
            float luck = closestPlayer.luck;
            int num2 = 1;
            if (Main.rand.NextFloat() < Math.Abs(luck))
            {
                num2 = 2;
            }
            for (int i = 0; i < num2; i++)
            {
                float num3 = this.value;
                if (this.midas)
                {
                    num3 *= 1f + (float)Main.rand.Next(10, 51) * 0.01f;
                }
                num3 *= 1f + (float)Main.rand.Next(-20, 76) * 0.01f;
                if (Main.rand.Next(2) == 0)
                {
                    num3 *= 1f + (float)Main.rand.Next(5, 11) * 0.01f;
                }
                if (Main.rand.Next(4) == 0)
                {
                    num3 *= 1f + (float)Main.rand.Next(10, 21) * 0.01f;
                }
                if (Main.rand.Next(8) == 0)
                {
                    num3 *= 1f + (float)Main.rand.Next(15, 31) * 0.01f;
                }
                if (Main.rand.Next(16) == 0)
                {
                    num3 *= 1f + (float)Main.rand.Next(20, 41) * 0.01f;
                }
                if (Main.rand.Next(32) == 0)
                {
                    num3 *= 1f + (float)Main.rand.Next(25, 51) * 0.01f;
                }
                if (Main.rand.Next(64) == 0)
                {
                    num3 *= 1f + (float)Main.rand.Next(50, 101) * 0.01f;
                }
                if (Main.bloodMoon)
                {
                    num3 *= 1f + (float)Main.rand.Next(101) * 0.01f;
                }
                if (i == 0)
                {
                    num = num3;
                }
                else if (luck < 0f)
                {
                    if (num3 < num)
                    {
                        num = num3;
                    }
                }
                else if (num3 > num)
                {
                    num = num3;
                }
            }
            num += (float)this.extraValue;
            while ((int)num > 0)
            {
                if (num > 1000000f)
                {
                    int num4 = (int)(num / 1000000f);
                    if (num4 > 50 && Main.rand.Next(5) == 0)
                    {
                        num4 /= Main.rand.Next(3) + 1;
                    }
                    if (Main.rand.Next(5) == 0)
                    {
                        num4 /= Main.rand.Next(3) + 1;
                    }
                    int j = num4;
                    while (j > 999)
                    {
                        j -= 999;
                        Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 74, 999, false, 0, false);
                    }
                    num -= (float)(1000000 * num4);
                    Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 74, j, false, 0, false);
                }
                else if (num > 10000f)
                {
                    int num5 = (int)(num / 10000f);
                    if (num5 > 50 && Main.rand.Next(5) == 0)
                    {
                        num5 /= Main.rand.Next(3) + 1;
                    }
                    if (Main.rand.Next(5) == 0)
                    {
                        num5 /= Main.rand.Next(3) + 1;
                    }
                    num -= (float)(10000 * num5);
                    Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 73, num5, false, 0, false);
                }
                else if (num > 100f)
                {
                    int num6 = (int)(num / 100f);
                    if (num6 > 50 && Main.rand.Next(5) == 0)
                    {
                        num6 /= Main.rand.Next(3) + 1;
                    }
                    if (Main.rand.Next(5) == 0)
                    {
                        num6 /= Main.rand.Next(3) + 1;
                    }
                    num -= (float)(100 * num6);
                    Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 72, num6, false, 0, false);
                }
                else
                {
                    int num7 = (int)num;
                    if (num7 > 50 && Main.rand.Next(5) == 0)
                    {
                        num7 /= Main.rand.Next(3) + 1;
                    }
                    if (Main.rand.Next(5) == 0)
                    {
                        num7 /= Main.rand.Next(4) + 1;
                    }
                    if (num7 < 1)
                    {
                        num7 = 1;
                    }
                    num -= (float)num7;
                    Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 71, num7, false, 0, false);
                }
            }
        }
References System.Math.Abs(), Terraria.Main.bloodMoon, Terraria.NPC.extraValue, Terraria.NPC.GetItemSource_Loot(), Terraria.Entity.height, int, Terraria.Player.luck, Terraria.NPC.midas, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.value, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.NPCLoot().