Terraria Decompiled: Terraria.NPC.CheckDrowning
CheckDrowning()
void Terraria.NPC.CheckDrowning () inline
Definition at line 96792 of file NPC.cs.
        {
            bool flag = Collision.DrownCollision(this.position, this.width, this.height, 1f, false);
            if (Main.netMode != 1)
            {
                if (flag)
                {
                    int num = this.breathCounter + 1;
                    this.breathCounter = num;
                    if (num >= 7)
                    {
                        this.breathCounter = 0;
                        this.breath--;
                        if (this.breath <= 0)
{
                            this.friendlyRegen = 0;
                            this.breath = 0;
                            this.life -= 2;
                            this.NetUpdateLowPriority();
                            if (this.life <= 0)
{
                                this.life = 1;
                                this.StrikeNPCNoInteraction(2, 0f, 0, false, false, false);
                                if (Main.netMode != 0)
{
                                    NetMessage.SendData(28, -1, -1, null, this.whoAmI, 2f, 0f, 0f, 0, 0, 0);
                                }
                            }
                        }
                    }
                }
                else
                {
                    this.breath += 3;
                    if (this.breath > 200)
                    {
                        this.breath = 200;
                    }
                    this.breathCounter = 0;
                }
            }
            if (flag && Main.rand.Next(20) == 0 && !this.lavaWet && !this.honeyWet && !this.shimmerWet)
            {
                int num2 = 0;
                int num3 = 0;
                if (this.type == 369)
                {
                    num3 = 8;
                }
                Dust.NewDust(new Vector2(this.position.X + (float)((10 + num2) * this.direction), this.position.Y + (float)num3 + 4f), this.width - 8, 8, 34, 0f, 0f, 0, default(Color), 1.2f);
            }
        }
References Terraria.Collision.DrownCollision(), Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.NetMessage.SendData(), and Microsoft.Xna.Framework.Graphics.Vector2.