Terraria Decompiled: Terraria.NPC.AnyNPCs
AnyNPCs()
static bool Terraria.NPC.AnyNPCs (int Type) inline static
Definition at line 90650 of file NPC.cs.
        {
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == Type)
                {
                    return true;
                }
            }
            return false;
        }
References Terraria.NPC.active, Terraria.Main.maxNPCs, Terraria.Main.npc, and Terraria.NPC.type.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.GameContent.ItemDropRules.Conditions.MissingTwin.CanDrop(), Terraria.GameContent.ItemDropRules.Conditions.MechdusaKill.CanDrop(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckOrb(), Terraria.GameContent.Events.CultistRitual.CheckRitual(), Terraria.NPC.CountKillForAchievements(), Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_AdvanceSlimeRain(), Terraria.NPC.DoDeathEvents_BeforeLoot(), Terraria.Main.DoUpdateInWorld(), Terraria.Projectile.FishingCheck_ProbeForQuestFish(), Terraria.NPC.Spawner.GetGnomeChance(), Terraria.Main.HelpText(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC_Old(), Terraria.Player.LicenseOrExchangePet(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.GameContent.Achievements.AchievementsHelper.MechaMayhem_Kill(), Terraria.GameContent.Events.BirthdayParty.NaturalAttempt(), Terraria.NPC.NPCLoot(), Terraria.NPC.ScaleStats_ByDifficulty_Tweaks(), Terraria.NPC.ScaleStats_ForExpertHardmode(), Terraria.Chest.SetupShop(), Terraria.Main.ShouldNormalEventsBeAbleToStart(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.NPC.Spawner.SpawnFaelings(), Terraria.NPC.Spawner.SpawnFrog(), Terraria.NPC.SpawnMechQueen(), Terraria.NPC.SpawnOnPlayer(), Terraria.WorldGen.SpawnTownNPC(), Terraria.NPC.SpawnWOF(), Terraria.GameContent.Events.DD2Event.SummonBetsy(), Terraria.GameContent.Events.DD2Event.SummonCrystalDirect(), Terraria.Player.TileInteractionsUse(), Terraria.Projectile.TryBuildFishingContext(), Terraria.NPC.UnlockOrExchangePet(), Terraria.GameContent.Events.DD2Event.UpdateTime(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().