Terraria Decompiled: Terraria.NPC.UpdateNPC_CastLights
UpdateNPC_CastLights()
void Terraria.NPC.UpdateNPC_CastLights () inline private
Definition at line 93380 of file NPC.cs.
        {
            if (this.type >= 0 && NPCID.Sets.IsGoldCritter[this.type])
            {
                this.position += this.netOffset;
                Color color = Lighting.GetColor((int)base.Center.X / 16, (int)base.Center.Y / 16);
                if (color.R > 20 || color.B > 20 || color.G > 20)
                {
                    int num = (int)color.R;
                    if ((int)color.G > num)
                    {
                        num = (int)color.G;
                    }
                    if ((int)color.B > num)
                    {
                        num = (int)color.B;
                    }
                    num /= 30;
                    if (Main.rand.Next(300) < num)
                    {
                        int num2 = Dust.NewDust(this.position, this.width, this.height, 43, 0f, 0f, 254, new Color(255, 255, 0), 0.5f);
                        Main.dust[num2].velocity *= 0f;
                    }
                }
                this.position -= this.netOffset;
            }
            if (this.type == 160)
            {
                float num3 = (float)Main.rand.Next(28, 42) * 0.005f;
                num3 += (float)(270 - (int)Main.mouseTextColor) / 500f;
                float num4 = 0.1f;
                float num5 = 0.3f + num3 / 2f;
                float num6 = 0.6f + num3;
                if (this.townNpcVariationIndex == 1)
                {
                    float num7 = num4;
                    num4 = num6;
                    num6 = num7;
                }
                float num8 = 0.35f;
                num4 *= num8;
                num5 *= num8;
                num6 *= num8;
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num4, num5, num6);
            }
            if ((this.type >= 254 && this.type <= 261) || this.type == 634 || this.type == 635)
            {
                float num9 = (float)Main.rand.Next(28, 42) * 0.005f;
                num9 += (float)(270 - (int)Main.mouseTextColor) / 500f;
                float num10 = 0.1f;
                float num11 = 0.3f + num9 / 2f;
                float num12 = 0.6f + num9;
                float num13 = 0.35f;
                if (this.type == 634)
                {
                    num13 = 0.65f;
                }
                num10 *= num13;
                num11 *= num13;
                num12 *= num13;
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num10, num11, num12);
            }
            if (this.type == 209)
            {
                float num14 = (float)Main.rand.Next(28, 42) * 0.005f;
                num14 += (float)(270 - (int)Main.mouseTextColor) / 500f;
                float num15 = 0.1f;
                float num16 = 0.3f + num14 / 2f;
                float num17 = 0.4f + num14 / 2f;
                float num18 = 0.35f;
                num15 *= num18;
                num16 *= num18;
                num17 *= num18;
                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, num15, num16, num17);
                if (this.ai[0] == 12f)
                {
                    Lighting.AddLight(base.Top, 0.3f, 0.1f, 0.1f);
                }
            }
            if (this.type == 44)
            {
                Lighting.AddLight((int)(this.position.X + (float)(this.width / 2)) / 16, (int)(this.position.Y + 4f) / 16, 0.9f, 0.75f, 0.5f);
            }
        }
References Terraria.Lighting.AddLight(), Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.dust, Microsoft.Xna.Framework.Color.G, Terraria.Lighting.GetColor(), int, Terraria.ID.NPCID.Sets.IsGoldCritter, Terraria.Main.mouseTextColor, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Color.R, Terraria.Main.rand, and Terraria.Dust.velocity.