Terraria Decompiled: Terraria.NPC.AddBuff
AddBuff()
void Terraria.NPC.AddBuff (int type, int time, bool quiet = false) inline
Definition at line 90711 of file NPC.cs.
        {
            if (this.buffImmune[type])
            {
                return;
            }
            if (!quiet && Main.netMode == 1)
            {
                NetMessage.SendData(53, -1, -1, null, this.whoAmI, (float)type, (float)time, 0f, 0, 0, 0);
            }
            int num = -1;
            int i = 0;
            while (i < NPC.maxBuffs)
            {
                if (this.buffType[i] == type)
                {
                    if (this.buffTime[i] >= time)
                    {
                        return;
                    }
                    num = i;
                    IL_00BC:
                    while (num == -1)
                    {
                        int num2 = -1;
                        for (int j = 0; j < NPC.maxBuffs; j++)
{
                            if (!Main.debuff[this.buffType[j]])
{
                                num2 = j;
                                break;
                            }
                        }
                        if (num2 == -1)
{
                            return;
                        }
                        for (int k = num2; k < NPC.maxBuffs; k++)
{
                            if (this.buffType[k] == 0)
{
                                num = k;
                                break;
                            }
                        }
                        if (num == -1)
{
                            this.DelBuff(num2, true);
                        }
                    }
                    this.buffType[num] = type;
                    this.buffTime[num] = time;
                    if (!quiet && Main.netMode == 2)
                    {
                        NetMessage.SendData(54, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    }
                    return;
                }
                else
                {
                    i++;
                }
            }
            goto IL_00BC;
        }
References Terraria.Main.debuff, Terraria.NPC.maxBuffs, Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.Projectile.ApplyWhipDebuffs(), Terraria.NPC.HitEffect(), Terraria.Projectile.StatusNPC(), Terraria.Player.StatusToNPC(), and Terraria.Player.UpdateBuffs().