Terraria Decompiled: Terraria.NPC.AnyDanger
AnyDanger()
static bool Terraria.NPC.AnyDanger (bool quickBossNPCCheck = false, bool ignorePillarsAndMoonlordCountdown = false) inline static
Definition at line 79246 of file NPC.cs.
        {
            bool flag = false;
            if (!ignorePillarsAndMoonlordCountdown && NPC.MoonLordCountdown > 0)
            {
                flag = true;
            }
            if (Main.invasionType > 0)
            {
                flag = true;
            }
            if (Main.snowMoon || Main.pumpkinMoon || DD2Event.Ongoing)
            {
                flag = true;
            }
            if (!flag)
            {
                if (quickBossNPCCheck)
                {
                    flag |= Main.CurrentFrameFlags.AnyActiveBossNPC;
                }
                else
                {
                    for (int i = 0; i < Main.maxNPCs; i++)
                    {
                        if (Main.npc[i].active && (Main.npc[i].boss || NPCID.Sets.DangerThatPreventsOtherDangers[Main.npc[i].type]))
{
                            if (ignorePillarsAndMoonlordCountdown)
{
                                int num = Main.npc[i].type;
                                if (num <= 493)
{
                                    if (num == 422 || num == 493)
{
                                        goto IL_00B3;
                                    }
                                }
                                else if (num == 507 || num == 517)
{
                                    goto IL_00B3;
                                }
                            }
                            flag = true;
                        }
                        IL_00B3:;
                    }
                }
            }
            return flag;
        }
References Terraria.NPC.active, Terraria.Main.CurrentFrameFlags.AnyActiveBossNPC, Terraria.NPC.boss, Terraria.ID.NPCID.Sets.DangerThatPreventsOtherDangers, Terraria.Main.invasionType, Terraria.Main.maxNPCs, Terraria.NPC.MoonLordCountdown, Terraria.Main.npc, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Main.pumpkinMoon, Terraria.Main.snowMoon, and Terraria.NPC.type.
Referenced by Terraria.GameContent.PlayerSleepingHelper.DoesPlayerHaveReasonToActUpInBed(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_Head_GetTVScreen(), Terraria.Player.ItemCheck_CheckCanUse_Inner(), Terraria.Player.ItemCheck_UseEventItems(), Terraria.Rain.MakeRain(), Terraria.Testing.DebugUtils.PracticeModeReset(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.WorldGen.SpawnStormLightning(), Terraria.GameContent.Events.CultistRitual.UpdateTime(), and Terraria.Main.UpdateTime().