Terraria Decompiled: Terraria.NPC.AI_AttemptToFindTeleportSpot
AI_AttemptToFindTeleportSpot()
bool Terraria.NPC.AI_AttemptToFindTeleportSpot (ref Vector2 chosenTile, int targetTileX, int targetTileY, int rangeFromTargetTile = 20, int telefragPreventionDistanceInTiles = 5, int solidTileCheckFluff = 1, bool solidTileCheckCentered = false, bool teleportInAir = false) inline
Definition at line 12835 of file NPC.cs.
        {
            int num = (int)base.Center.X / 16;
            int num2 = (int)base.Center.Y / 16;
            int num3 = 0;
            bool flag = false;
            float num4 = 20f;
            if (Math.Abs(num * 16 - targetTileX * 16) + Math.Abs(num2 * 16 - targetTileY * 16) > 2000)
            {
                num3 = 100;
                flag = false;
            }
            while (!flag && num3 < 100)
            {
                num3++;
                int num5 = Main.rand.Next(targetTileX - rangeFromTargetTile, targetTileX + rangeFromTargetTile + 1);
                for (int i = Main.rand.Next(targetTileY - rangeFromTargetTile, targetTileY + rangeFromTargetTile + 1); i < targetTileY + rangeFromTargetTile; i++)
                {
                    if ((i < num2 - 1 || i > num2 + 1 || num5 < num - 1 || num5 > num + 1) && (teleportInAir || Main.tile[num5, i].nactive()))
                    {
                        bool flag2 = true;
                        if ((this.type == 32 || (this.type >= 281 && this.type <= 286)) && !Main.wallDungeon[(int)Main.tile[num5, i - 1].wall])
{
                            if (!NPC.AnyNPCs(35))
{
                                flag2 = false;
                            }
                        }
                        else if (Main.tile[num5, i - 1].lava())
{
                            flag2 = false;
                        }
                        if (flag2 && (teleportInAir || Main.tileSolid[(int)Main.tile[num5, i].type]))
{
                            bool flag3;
                            if (solidTileCheckCentered)
{
                                flag3 = !Collision.SolidTiles(num5 - solidTileCheckFluff, num5 + solidTileCheckFluff, i - solidTileCheckFluff, i + solidTileCheckFluff);
                            }
                            else
{
                                flag3 = !Collision.SolidTiles(num5 - solidTileCheckFluff, num5 + solidTileCheckFluff, i - 3 - solidTileCheckFluff, i - 1);
                            }
                            if (flag3)
{
                                Rectangle rectangle = new Rectangle(num5 * 16, i * 16, 16, 16);
                                rectangle.Inflate(telefragPreventionDistanceInTiles * 16, telefragPreventionDistanceInTiles * 16);
                                for (int j = 0; j < Main.player.Length; j++)
{
                                    Player player = Main.player[j];
                                    if (player != null && player.active && !player.dead)
{
                                        Rectangle hitbox = player.Hitbox;
                                        Rectangle rectangle2 = hitbox.Modified((int)(player.velocity.X * num4), (int)(player.velocity.Y * num4), 0, 0);
                                        Rectangle.Union(ref rectangle2, ref hitbox, out rectangle2);
                                        if (rectangle2.Intersects(rectangle))
{
                                            flag2 = false;
                                            flag = false;
                                            break;
                                        }
                                    }
                                }
                                if (flag2)
{
                                    chosenTile = new Vector2((float)num5, (float)i);
                                    flag = true;
                                    break;
                                }
                                break;
                            }
                        }
                    }
                }
            }
            return flag;
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.NPC.AnyNPCs(), Terraria.Player.dead, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Inflate(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Tile.lava(), Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, Terraria.Collision.SolidTiles(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.NPC.type, Terraria.Tile.type, Microsoft.Xna.Framework.Rectangle.Union(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Tile.wall, Terraria.Main.wallDungeon, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_003_Fighters(), and Terraria.NPC.TryTeleportingCaughtMysticFrog().