Terraria Decompiled: Terraria.NPC.SpawnBoss
SpawnBoss()
static void Terraria.NPC.SpawnBoss (int spawnPositionX, int spawnPositionY, int Type, int targetPlayerIndex, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, float ai3 = 0f) inline static
Definition at line 79702 of file NPC.cs.
        {
            int num = Main.maxNPCs;
            bool flag = Type == 134 || Type == 127 || Type == 126 || Type == 125;
            if (flag)
            {
                AchievementsHelper.MechaMayhem_Clear();
            }
            if (Type == 127 && NPC.mechQueen != -1)
            {
                num = NPC.NewNPC(NPC.GetBossSpawnSource(targetPlayerIndex), spawnPositionX, spawnPositionY, Type, 100, ai0, ai1, ai2, ai3, targetPlayerIndex);
                NPC.mechQueen = num;
                Main.npc[NPC.mechQueen].ai[3] = (float)NPC.mechQueen;
            }
            else
            {
                num = NPC.NewNPC(NPC.GetBossSpawnSource(targetPlayerIndex), spawnPositionX, spawnPositionY, Type, 1, ai0, ai1, ai2, ai3, targetPlayerIndex);
            }
            if (num == Main.maxNPCs)
            {
                return;
            }
            if (flag)
            {
                AchievementsHelper.MechaMayhem_Start();
            }
            Main.npc[num].timeLeft *= 20;
            string typeName = Main.npc[num].TypeName;
            if (Main.netMode == 2 && num < Main.maxNPCs)
            {
                NetMessage.SendData(23, -1, -1, null, num, 0f, 0f, 0f, 0, 0, 0);
            }
            if (Type == 127 && NPC.mechQueen == num)
            {
                ChatHelper.BroadcastChatMessage(Lang.misc[107].ToNetworkText(), ChatColors.BossOrEvent, -1);
                return;
            }
            if (Type == 125)
            {
                ChatHelper.BroadcastChatMessage(Lang.misc[48].ToNetworkText(), ChatColors.BossOrEvent, -1);
                return;
            }
            if (Type != 316 && Type != 662 && Type != 82 && Type != 126 && Type != 50 && Type != 398 && Type != 551)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { Main.npc[num].GetTypeNetName() }), ChatColors.BossOrEvent, -1);
            }
        }
References Terraria.NPC.ai, Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetBossSpawnSource(), Terraria.Main.maxNPCs, Terraria.GameContent.Achievements.AchievementsHelper.MechaMayhem_Clear(), Terraria.GameContent.Achievements.AchievementsHelper.MechaMayhem_Start(), Terraria.NPC.mechQueen, Terraria.Lang.misc, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.NPC.timeLeft, Terraria.Localization.LocalizedText.ToNetworkText(), and Terraria.NPC.TypeName.
Referenced by Terraria.NPC.DoDeathEvents().