Terraria Decompiled: Terraria.NPC.ShouldEmpressBeEnraged
ShouldEmpressBeEnraged()
static bool Terraria.NPC.ShouldEmpressBeEnraged () inline static
Definition at line 42755 of file NPC.cs.
        {
            if (!Main.remixWorld)
            {
                return Main.dayTime;
            }
            if (NPC.empressRageMode)
            {
                return true;
            }
            int num = -1;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].type == 636)
                {
                    num = i;
                    break;
                }
            }
            if (num >= 0 && (double)Main.npc[num].Center.Y < Main.worldSurface * 16.0)
            {
                NPC.empressRageMode = true;
                return true;
            }
            NPC.empressRageMode = false;
            return false;
        }
References Terraria.Entity.Center, Terraria.Main.dayTime, Terraria.NPC.empressRageMode, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.Main.remixWorld, Terraria.NPC.type, Terraria.Main.worldSurface, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI_120_HallowBoss(), Terraria.Projectile.AI_171_GetColor(), Terraria.Projectile.AI_173_GetColor(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawProjDirect(), and Terraria.NPC.IsDamageDodgeable().