Terraria Decompiled: Terraria.NPC.AI_116_WaterStriders
AI_116_WaterStriders()
void Terraria.NPC.AI_116_WaterStriders () inline private
Definition at line 44381 of file NPC.cs.
        {
            bool flag = false;
            float num;
            if (Collision.GetWaterLine(base.Center.ToTileCoordinates(), out num))
            {
                float num2 = base.Bottom.Y - 1f;
                if (base.Center.Y > num)
                {
                    this.velocity.Y = this.velocity.Y - 0.8f;
                    if (this.velocity.Y < -4f)
                    {
                        this.velocity.Y = -4f;
                    }
                    if (num2 + this.velocity.Y < num)
                    {
                        this.velocity.Y = num - num2;
                    }
                }
                else
                {
                    this.velocity.Y = MathHelper.Min(this.velocity.Y, num - num2);
                    flag = true;
                }
            }
            else if (this.wet)
            {
                this.velocity.Y = this.velocity.Y - 0.2f;
            }
            if ((int)this.ai[0] == 0)
            {
                this.ai[1] += 1f;
                this.velocity.X = this.velocity.X * 0.9f;
                if (this.velocity.Y == 0f)
                {
                    this.velocity.X = this.velocity.X * 0.6f;
                }
                bool flag2 = this.wet || flag;
                bool flag3 = flag2 || this.velocity.Y == 0f;
                int num3 = Main.rand.Next(120, 241);
                if (!flag2)
                {
                    num3 = Main.rand.Next(60, 241);
                }
                if (flag3 && this.ai[1] >= (float)num3)
                {
                    this.ai[1] = 0f;
                    this.velocity.X = Main.rand.NextFloatDirection() * 5f;
                    this.netUpdate = true;
                    if (!flag2)
                    {
                        if (this.velocity.Y == 0f)
{
                            this.velocity.Y = -2f;
                        }
                        this.ai[1] = 60f;
                    }
                }
            }
        }
References Terraria.NPC.ai, Terraria.Collision.GetWaterLine(), Microsoft.Xna.Framework.MathHelper.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Entity.velocity, Terraria.Entity.wet, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().