Terraria Decompiled: Terraria.NPC.NewNPC
NewNPC()
static int Terraria.NPC.NewNPC (IEntitySource source, int X, int Y, int Type, int Start = 0, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, float ai3 = 0f, int Target = 255) inline static
Definition at line 79760 of file NPC.cs.
        {
            if (Main.getGoodWorld && Main.rand.Next(3) != 0)
            {
                if (Type == 46)
                {
                    Type = 614;
                }
                if (Type == 62)
                {
                    Type = 66;
                }
            }
            int availableNPCSlot = NPC.GetAvailableNPCSlot(Type, Start);
            if (availableNPCSlot >= 0)
            {
                NPC.spawnSlotProtected[availableNPCSlot] = 2;
                NPC npc = new NPC();
                Main.npc[availableNPCSlot] = npc;
                npc.whoAmI = availableNPCSlot;
                npc.ResetForNewNPC();
                npc.SetDefaults(Type, default(NPCSpawnParams));
                NPC.GiveTownUniqueDataToNPCsThatNeedIt(Type, availableNPCSlot);
                npc.Bottom = new Vector2((float)X, (float)Y);
                npc.active = true;
                npc.timeLeft = (int)((double)NPC.activeTime * 1.25);
                if (!npc.noTileCollide)
                {
                    npc.wet = Collision.WetCollision(npc.position, npc.width, npc.height);
                }
                npc.ai[0] = ai0;
                npc.ai[1] = ai1;
                npc.ai[2] = ai2;
                npc.ai[3] = ai3;
                npc.target = Target;
                if (Main.netMode == 2)
                {
                    npc.spawnNeedsSyncing = true;
                }
                if (Type == 50)
                {
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { npc.GetTypeNetName() }), ChatColors.BossOrEvent, -1);
                }
                return availableNPCSlot;
            }
            return Main.maxNPCs;
        }
References Terraria.NPC.ai, Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetAvailableNPCSlot(), Terraria.Main.getGoodWorld, Terraria.NPC.GiveTownUniqueDataToNPCsThatNeedIt(), Terraria.Entity.height, int, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.noTileCollide, Terraria.Enums.NPC, Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.ResetForNewNPC(), Terraria.NPC.SetDefaults(), Terraria.NPC.spawnSlotProtected, Microsoft.Xna.Framework.Graphics.Target, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Collision.WetCollision(), Terraria.Entity.width, System.X, and System.Y.
Referenced by Terraria.GameContent.Tile_Entities.TETrainingDummy.Activate(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_015_KingSlime(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_127_Pal(), Terraria.NPC.BigMimicSummonCheck(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckSuper(), Terraria.Cinematics.DD2Film.CreateCritters(), Terraria.Cinematics.DD2Film.CreateOgre(), Terraria.GameContent.Events.DD2Event.Difficulty_1_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_2_SpawnMonsterFromGate(), Terraria.GameContent.Events.DD2Event.Difficulty_3_SpawnMonsterFromGate(), Terraria.NPC.DoDeathEvents_SummonDungeonSpirit(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozenFinish(), Terraria.WorldItem.GetShimmered(), Terraria.NPC.HitEffect(), Terraria.Wiring.HitWireSingle(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Projectile.Kill_SpiderBoulder_SpawnSpider(), Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.Cinematics.DD2Film.PlaceNPCOnGround(), Terraria.Cinematics.DSTFilm.PlaceNPCOnGround(), Terraria.GameContent.Events.DD2Event.RaiseGoblins(), Terraria.NPC.ReleaseNPC(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.SetOldManSpawnAndSpawnOldManIfDefaultDungeon(), Terraria.WorldGen.ShakeTree(), Terraria.Projectile.Shimmer(), Terraria.NPC.Spawner.SlimeRainSpawns(), Terraria.NPC.SpawnBoss(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.NPC.Spawner.SpawnFaelings(), Terraria.Cinematics.DD2Film.SpawnGoblin(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.Cinematics.DD2Film.SpawnJavalinThrower(), Terraria.NPC.SpawnMechQueen(), Terraria.NPC.Spawner.SpawnNPC(), Terraria.NPC.SpawnOnPlayer(), Terraria.NPC.SpawnSkeletron(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.Cinematics.DD2Film.SpawnWitherBeast(), Terraria.NPC.SpawnWOF(), Terraria.GameContent.Events.DD2Event.SummonCrystalDirect(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.GameContent.Events.CultistRitual.TrySpawning(), Terraria.Main.UpdateTime_SpawnTownNPCs(), and Terraria.NPC.ViolentlySpawnNerdySlime().