Terraria Decompiled: Terraria.NPC.NPCLoot
NPCLoot()
void Terraria.NPC.NPCLoot () inline
Definition at line 77555 of file NPC.cs.
        {
            if (Main.netMode == 1 || this.type >= (int)NPCID.Count)
            {
                return;
            }
            if ((Main.getGoodWorld || !Main.isThereAWorldSurface) && !NPC.downedBoss3 && !Main.onlyShimmerOceanWorlds && (this.type == 31 || this.type == 294 || this.type == 296 || this.type == 295 || this.type == 32 || this.type == 34 || this.type == 71 || this.type == 693 || this.type == 694))
            {
                return;
            }
            if (this.type == 32 && this.localAI[3] == 1f)
            {
                return;
            }
            bool flag = false;
            Player player = Main.player[(int)Player.FindClosest(this.position, this.width, this.height)];
            if (!flag)
            {
                this.CountKillForAchievements();
                if (this.GetWereThereAnyInteractions())
                {
                    if (this.IsNPCValidForBestiaryKillCredit())
                    {
                        Main.BestiaryTracker.Kills.RegisterKill(this);
                    }
                    this.CountKillForBannersAndDropThem();
                }
            }
            if (this.SpawnedFromStatue && NPCID.Sets.NoEarlymodeLootWhenSpawnedFromStatue[this.type] && !Main.hardMode)
            {
                return;
            }
            if (this.SpawnedFromStatue && NPCID.Sets.StatueSpawnedDropRarity[this.type] != -1f && (Main.rand.NextFloat() >= NPCID.Sets.StatueSpawnedDropRarity[this.type] || !this.AnyInteractions()))
            {
                return;
            }
            bool flag2 = NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3;
            this.DoDeathEvents_BeforeLoot(player);
            this.NPCLoot_DropItems(player);
            this.DoDeathEvents(player);
            if (SpecialSeedFeatures.Mechdusa)
            {
                int num = this.type;
                if (num - 125 <= 2 || num == 134)
                {
                    bool flag3 = this.type == 127 || !NPC.AnyNPCs(127);
                    bool flag4 = this.type == 134 || !NPC.AnyNPCs(134);
                    bool flag5 = this.type == 126 || !NPC.AnyNPCs(126);
                    bool flag6 = this.type == 125 || !NPC.AnyNPCs(125);
                    if (flag5 && flag6 && flag4 && flag3)
                    {
                        AchievementsHelper.NotifyProgressionEvent(31);
                    }
                }
            }
            if (!flag2 && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3 && Main.hardMode)
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[32].Key, new object[0]), ChatColors.World, -1);
            }
            if (this.IsNPCValidForBestiaryKillCredit())
            {
                if (this.type == 4 && WorldGen.Skyblock.noAltars)
                {
                    this.NPCLoot_DropAltar();
                }
                if ((this.type == 14 || this.type == 13 || this.type == 15 || this.type == 266) && WorldGen.Skyblock.noDungeon)
                {
                    this.NPCLoot_DropDungeonStuff();
                }
                if (this.type == 35 && WorldGen.Skyblock.noHellforge)
                {
                    this.NPCLoot_DropHellforge();
                }
                if (this.type == 262 && WorldGen.Skyblock.noTemple)
                {
                    this.NPCLoot_DropLihzahrdStuff();
                }
                if (this.type == 245 && WorldGen.Skyblock.lowTiles)
                {
                    this.NPCLoot_DropTempleTraps();
                }
            }
            this.NPCLoot_DropMoney(player);
            this.NPCLoot_DropHeals(player);
        }
References Terraria.NPC.AnyNPCs(), Terraria.Main.BestiaryTracker, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.ID.NPCID.Count, Terraria.NPC.CountKillForAchievements(), Terraria.NPC.CountKillForBannersAndDropThem(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_BeforeLoot(), Terraria.NPC.downedBoss3, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.Player.FindClosest(), Terraria.Localization.NetworkText.FromKey(), Terraria.Main.getGoodWorld, Terraria.NPC.GetWereThereAnyInteractions(), Terraria.Main.hardMode, int, Terraria.NPC.IsNPCValidForBestiaryKillCredit(), Terraria.Main.isThereAWorldSurface, Terraria.Localization.LocalizedText.Key, Terraria.NPC.localAI, Terraria.WorldGen.Skyblock.lowTiles, Terraria.GameContent.SpecialSeedFeatures.Mechdusa, Terraria.Lang.misc, Terraria.Main.netMode, Terraria.WorldGen.Skyblock.noAltars, Terraria.WorldGen.Skyblock.noDungeon, Terraria.ID.NPCID.Sets.NoEarlymodeLootWhenSpawnedFromStatue, Terraria.WorldGen.Skyblock.noHellforge, Terraria.WorldGen.Skyblock.noTemple, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.NPC.NPCLoot_DropAltar(), Terraria.NPC.NPCLoot_DropDungeonStuff(), Terraria.NPC.NPCLoot_DropHeals(), Terraria.NPC.NPCLoot_DropHellforge(), Terraria.NPC.NPCLoot_DropItems(), Terraria.NPC.NPCLoot_DropLihzahrdStuff(), Terraria.NPC.NPCLoot_DropMoney(), Terraria.NPC.NPCLoot_DropTempleTraps(), Terraria.Main.onlyShimmerOceanWorlds, Terraria.Main.player, Terraria.Main.rand, Terraria.NPC.SpawnedFromStatue, Terraria.ID.NPCID.Sets.StatueSpawnedDropRarity, Terraria.NPC.type, and Terraria.Chat.ChatColors.World.
Referenced by Terraria.NPC.checkDead(), and Terraria.NPC.DropEoWLoot().