Terraria Decompiled: Terraria.NPC.CanBeChasedBy
CanBeChasedBy()
bool Terraria.NPC.CanBeChasedBy (object attacker = null, bool ignoreDontTakeDamage = false) inline
Definition at line 90831 of file NPC.cs.
        {
            return this.active && this.chaseable && this.lifeMax > 5 && (!this.dontTakeDamage || ignoreDontTakeDamage) && !this.friendly && (DebugOptions.LetProjectilesAimAtTargetDummies || !this.immortal);
        }
References Terraria.Testing.DebugOptions.LetProjectilesAimAtTargetDummies.
Referenced by Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_015_Flails_Old(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_047_MagnetSphere_TryAttacking(), Terraria.Projectile.AI_053_HandleSentryNPCTargeting(), Terraria.Projectile.AI_062(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.Projectile.AI_099_1_Counterweights(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_100_Medusa(), Terraria.Projectile.AI_105_SporeSac(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.Projectile.AI_120_StardustGuardian_FindTarget(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_130_FlameBurstTower_FindTarget(), Terraria.Projectile.AI_134_Ballista_FindTarget(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_138_ExplosiveTrap(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_156_TryAttackingNPCs(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_171_HallowBossRainbowStreak(), Terraria.Projectile.AI_176_EdgyLightning(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_196_Petal(), Terraria.Player.BloodButcherer_TryButchering(), Terraria.Mount.CastSuperCartLaser(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Projectile.FindTargetWithinRange(), Terraria.Projectile.FindTargetWithLineOfSight(), Terraria.Player.GetSparkleGuitarTarget(), Terraria.Player.GetZenithTarget(), Terraria.Projectile.ghostHurt(), Terraria.Projectile.HandleMovement(), Terraria.Projectile.Minion_FindTargetInRange(), Terraria.Player.MinionNPCTargetAim(), Terraria.Utilities.NPCUtils.SearchFilters.NonBeeNPCs(), Terraria.Projectile.RainbowBoulder_PerformSmartBounce(), Terraria.Player.SpawnHallucination(), Terraria.Projectile.SummonMonkGhast(), Terraria.Player.TentacleSpike_TrySpiking(), Terraria.Mount.UpdateEffects(), Terraria.Player.UpdateMinionTarget(), and Terraria.Player.VolatileGelatin().