Terraria Decompiled: Terraria.NPC.ScaleStats_ByPlayerCount
ScaleStats_ByPlayerCount()
void Terraria.NPC.ScaleStats_ByPlayerCount (int numPlayers) inline private
Definition at line 12402 of file NPC.cs.
        {
            this.statsAreScaledForThisManyPlayers = numPlayers;
            float num;
            float num2;
            NPC.GetStatScalingFactors(numPlayers, out num, out num2);
            double num3 = 1.0;
            if (this.type == 4)
            {
                num3 *= (double)num;
            }
            if (this.type >= 13 && this.type <= 15)
            {
                num3 *= (double)num;
            }
            if (this.type == 266 || this.type == 267)
            {
                num3 *= (double)num;
                for (float num4 = 1f; num4 < num; num4 += 0.34f)
                {
                    if ((double)this.knockBackResist < 0.1)
                    {
                        this.knockBackResist = 0f;
                        break;
                    }
                    this.knockBackResist *= 0.8f;
                }
            }
            if (this.type == 50)
            {
                num3 *= (double)num;
            }
            if (this.type == 471)
            {
                num3 *= Utils.Lerp(1.0, (double)num, 0.6666666666666666);
            }
            if (this.type == 472)
            {
                num3 *= Utils.Lerp(1.0, (double)num, 0.5);
            }
            if (this.type == 222)
            {
                num3 *= (double)num;
            }
            if (this.type == 35)
            {
                num3 *= (double)num;
            }
            else if (this.type == 36)
            {
                num3 *= (double)num;
            }
            if (this.type == 668)
            {
                num3 *= (double)num;
            }
            if (this.type == 113 || this.type == 114)
            {
                num3 *= (double)num;
            }
            else if (this.type == 115)
            {
                num3 *= (double)num;
                if (numPlayers > 4)
                {
                    this.knockBackResist = 0f;
                }
                else if (numPlayers > 1)
                {
                    this.knockBackResist *= 1f - num2;
                }
            }
            else if (this.type == 116)
            {
                num3 *= (double)num;
                if (numPlayers > 4)
                {
                    this.knockBackResist = 0f;
                }
                else if (numPlayers > 1)
                {
                    this.knockBackResist *= 1f - num2;
                }
            }
            if (this.type == 657)
            {
                num3 *= (double)num;
            }
            if (this.type >= 658 && this.type <= 660)
            {
                num3 *= (double)num;
            }
            if (this.type >= 134 && this.type <= 136)
            {
                num3 *= (double)num;
            }
            else if (this.type == 139)
            {
                num3 *= Utils.Lerp(1.0, (double)num, 0.6666666666666666);
            }
            if (this.type >= 127 && this.type <= 131)
            {
                num3 *= (double)num;
            }
            if (this.type >= 125 && this.type <= 126)
            {
                num3 *= (double)num;
            }
            if (this.type == 262)
            {
                num3 *= (double)num;
            }
            else if (this.type == 264)
            {
                num3 *= (double)num;
            }
            if (this.type == 636)
            {
                num3 *= (double)num;
            }
            if (this.type >= 245 && this.type <= 249)
            {
                num3 *= (double)num;
            }
            if (this.type == 370)
            {
                num3 *= (double)num;
            }
            if (this.type == 439 || this.type == 440 || (this.type >= 454 && this.type <= 459) || this.type == 523)
            {
                num3 *= (double)num;
            }
            if (this.type == 397 || this.type == 396 || this.type == 398)
            {
                num3 *= (double)num;
            }
            if (this.type == 551)
            {
                num3 *= (double)num;
            }
            else if (NPCID.Sets.BelongsToInvasionOldOnesArmy[this.type])
            {
                num3 *= Utils.Lerp(1.0, (double)num, 0.8571428656578064);
            }
            int npcinvasionGroup = NPC.GetNPCInvasionGroup(this.type);
            if (npcinvasionGroup == -2 || npcinvasionGroup == -1)
            {
                int num5 = this.type;
                if (num5 <= 325)
                {
                    if (num5 == 315 || num5 == 325)
                    {
                        goto IL_040E;
                    }
                }
                else if (num5 == 327 || num5 - 344 <= 2)
                {
                    goto IL_040E;
                }
                num3 *= 1.0 + (double)(numPlayers - 1) * 0.2;
            }
            IL_040E:
            this.lifeMax = (int)Math.Round((double)this.lifeMax * num3);
        }
References Terraria.ID.NPCID.Sets.BelongsToInvasionOldOnesArmy, Terraria.NPC.GetNPCInvasionGroup(), Terraria.NPC.GetStatScalingFactors(), int, Terraria.Utils.Lerp(), System.Math.Round(), and Terraria.NPC.type.
Referenced by Terraria.NPC.ScaleStats().