Terraria Decompiled: Terraria.NPC.IsNPCValidForBestiaryKillCredit
IsNPCValidForBestiaryKillCredit()
bool Terraria.NPC.IsNPCValidForBestiaryKillCredit () inline
Definition at line 77642 of file NPC.cs.
        {
            int num = this.type;
            if (num - 13 > 2)
            {
                return num != 121;
            }
            return this.boss;
        }
References Terraria.NPC.boss, and Terraria.NPC.type.
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.WorldItem.CheckLavaDeath(), and Terraria.NPC.NPCLoot().