Terraria Decompiled: Terraria.NPC.AI_001_Slimes_GenerateItemInsideBody
AI_001_Slimes_GenerateItemInsideBody()
int Terraria.NPC.AI_001_Slimes_GenerateItemInsideBody (bool isBallooned) inline private
Definition at line 59021 of file NPC.cs.
        {
            int num = Main.rand.Next(4);
            bool flag = isBallooned;
            if (WorldGen.Skyblock.lowTiles)
            {
                if (Main.rand.Next(3) != 0)
                {
                    num = Main.rand.Next(1, 3);
                }
                if (Main.rand.Next(3) != 0)
                {
                    flag = false;
                }
            }
            if (flag)
            {
                switch (Main.rand.Next(13))
                {
                default:
                    num = 4367;
                    break;
                case 1:
                    num = 4368;
                    break;
                case 2:
                    num = 4369;
                    break;
                case 3:
                    num = 4370;
                    break;
                case 4:
                    num = 4371;
                    break;
                case 5:
                    num = 4612;
                    break;
                case 6:
                    num = 4674;
                    break;
                case 7:
                case 8:
                case 9:
                    num = 4343;
                    break;
                case 10:
                case 11:
                case 12:
                    num = 4344;
                    break;
                }
            }
            else if (num == 0)
            {
                num = Main.rand.Next(7);
                if (num == 0)
                {
                    num = 290;
                }
                else if (num == 1)
                {
                    num = 292;
                }
                else if (num == 2)
                {
                    num = 296;
                }
                else if (num == 3)
                {
                    num = 2322;
                }
                else if (Main.netMode != 0 && Main.rand.Next(2) == 0)
                {
                    num = 2997;
                }
                else
                {
                    num = 2350;
                }
            }
            else if (num == 1)
            {
                num = Main.rand.Next(4);
                if (WorldGen.Skyblock.lowTiles)
                {
                    if (Main.moonPhase == 0)
                    {
                        num = Main.rand.Next(2);
                    }
                    if (num == 2)
                    {
                        num = Main.rand.Next(4);
                    }
                }
                if (num == 0)
                {
                    num = 8;
                }
                else if (num == 1)
                {
                    num = 965;
                }
                else if (num == 2)
                {
                    num = 166;
                }
                else
                {
                    num = 58;
                }
            }
            else if (num == 2)
            {
                if (WorldGen.isThisInTheRockLayer((int)(base.Center.Y / 16f)) && WorldGen.Skyblock.lowTiles && Main.hardMode && Main.rand.Next(2) == 0)
                {
                    switch (Main.rand.Next(6))
                    {
                    default:
                        num = 364;
                        break;
                    case 1:
                        num = 1104;
                        break;
                    case 2:
                        num = 365;
                        break;
                    case 3:
                        num = 1105;
                        break;
                    case 4:
                        num = 366;
                        break;
                    case 5:
                        num = 1106;
                        break;
                    }
                }
                else if (Main.rand.Next(2) == 0)
                {
                    num = Main.rand.Next(11, 15);
                }
                else
                {
                    num = Main.rand.Next(699, 703);
                }
            }
            else
            {
                num = Main.rand.Next(3);
                if (WorldGen.Skyblock.lowTiles && Main.rand.Next(5) != 0)
                {
                    num = 0;
                }
                if (num == 0)
                {
                    num = 71;
                }
                else if (num == 1)
                {
                    num = 72;
                }
                else
                {
                    num = 73;
                }
            }
            return num;
        }
References Terraria.Main.hardMode, Terraria.WorldGen.isThisInTheRockLayer(), Terraria.WorldGen.Skyblock.lowTiles, Terraria.Main.moonPhase, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.rand.
Referenced by Terraria.NPC.AI_001_Slimes().