Terraria Decompiled: Terraria.NPC.TargetClosest_WOF
TargetClosest_WOF()
void Terraria.NPC.TargetClosest_WOF (bool faceTarget = true) inline
Definition at line 76157 of file NPC.cs.
        {
            float num = 0f;
            float num2 = 0f;
            bool flag = false;
            int num3 = -1;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active && !Main.player[i].dead && !Main.player[i].ghost && Main.player[i].gross)
                {
                    this.TryTrackingTarget(ref num, ref num2, ref flag, ref num3, i);
                }
            }
            this.SetTargetTrackingValues(faceTarget, num2, num3);
        }
References Terraria.Player.active, Terraria.Player.dead, Terraria.Player.ghost, Terraria.Player.gross, Terraria.Main.player, Terraria.NPC.SetTargetTrackingValues(), and Terraria.NPC.TryTrackingTarget().
Referenced by Terraria.NPC.AI().