Terraria Decompiled: Terraria.NPC.checkArmorPenetration
checkArmorPenetration()
int Terraria.NPC.checkArmorPenetration (int armorPenetration, float armorPenetrationPercent) inline
Definition at line 80182 of file NPC.cs.
        {
            if (this.ichor)
            {
                armorPenetration += 15;
            }
            if (this.brokenArmor)
            {
                armorPenetration += 20;
            }
            if (this.betsysCurse)
            {
                armorPenetration += 40;
            }
            armorPenetration += (int)((float)this.defense * armorPenetrationPercent);
            if (armorPenetration <= 0 || this.defense <= 0)
            {
                return 0;
            }
            if (armorPenetration > this.defense)
            {
                return this.defense / 2;
            }
            return armorPenetration / 2;
        }
References int.
Referenced by Terraria.Player.ApplyDamageToNPC(), Terraria.Projectile.Damage_PVE_Inner(), and Terraria.Player.ProcessHitAgainstNPC().