Terraria Decompiled: Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts
DoDeathEvents_DropBossPotionsAndHearts()
void Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts () inline private
Definition at line 77686 of file NPC.cs.
        {
            int num = Main.rand.Next(5, 16);
            int num2 = 28;
            if (this.type == 113)
            {
                num2 = 188;
            }
            else if (this.type == 35)
            {
                num2 = 188;
            }
            else if (this.type == 668)
            {
                num2 = 188;
            }
            else if (this.type == 222)
            {
                num2 = 1134;
            }
            else if (this.type == 657)
            {
                num2 = 499;
            }
            else if (this.type > 113 && this.type < 222)
            {
                num2 = 499;
            }
            else if (this.type == 636)
            {
                num2 = 499;
            }
            else if (this.type == 245 || this.type == 262)
            {
                num2 = 499;
            }
            else if (this.type == 370)
            {
                num2 = 499;
            }
            else if (this.type == 395)
            {
                num2 = 499;
            }
            else if (this.type == 439)
            {
                num2 = 499;
            }
            else if (this.type == 398)
            {
                num2 = 3544;
            }
            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, num2, num, false, 0, false);
            int num3 = Main.rand.Next(5) + 5;
            for (int i = 0; i < num3; i++)
            {
                Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 58, 1, false, 0, false);
            }
            if (this.type == 4)
            {
                NPC.EoCKilledToday = true;
            }
            else if (this.type == 113)
            {
                NPC.WoFKilledToday = true;
            }
            if (NPC.EoCKilledToday && NPC.WoFKilledToday)
            {
                NPC.ResetBadgerHatTime();
                Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 5004, 1, false, 0, false);
            }
        }
References Terraria.NPC.EoCKilledToday, Terraria.NPC.GetItemSource_Loot(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.ResetBadgerHatTime(), Terraria.NPC.type, Terraria.NPC.WoFKilledToday, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.NPC.DoDeathEvents().