Terraria Decompiled: Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike
AI_123_Deerclops_FindSpotToSpawnSpike()
void Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike (int howMany, int whichOne, ref int x, ref int y) inline private
Definition at line 41302 of file NPC.cs.
        {
            if (WorldGen.ActiveAndWalkableTile(x, y))
            {
                return;
            }
            Rectangle rectangle = this.targetRect;
            int num = rectangle.Center.X / 16;
            int num2 = (rectangle.Bottom - 16) / 16;
            int num3 = ((num2 - y > 0) ? 1 : (-1));
            int num4 = y;
            for (int i = 1; i <= 10; i++)
            {
                int num5 = y + num3 * i;
                if (num5 >= 20 && num5 <= Main.maxTilesY - 20 && WorldGen.ActiveAndWalkableTile(x, num5))
                {
                    num4 = num5;
                }
            }
            if (num4 != y)
            {
                y = num4;
                return;
            }
            y = (int)MathHelper.Lerp((float)num2, (float)y, (float)Math.Abs(num - x) * 0.1f);
            for (int j = 0; j < 4; j++)
            {
                int num6 = y + j;
                if (num6 >= 20 && num6 <= Main.maxTilesY - 20 && WorldGen.ActiveAndWalkableTile(x, num6))
                {
                    y = num6;
                    return;
                }
            }
        }
References System.Math.Abs(), Terraria.WorldGen.ActiveAndWalkableTile(), int, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Main.maxTilesY, and Terraria.NPC.targetRect.