Terraria Decompiled: Terraria.NPC.AddKingSlimeTeleportCacheTiles
AddKingSlimeTeleportCacheTiles()
void Terraria.NPC.AddKingSlimeTeleportCacheTiles (int x0, int x1, int y0, int y1) inline private
Definition at line 39784 of file NPC.cs.
        {
            for (int i = x0; i <= x1; i++)
            {
                for (int j = y0; j <= y1; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.nactive() && NPC.kingSlimePointCacheSize < NPC.kingSlimePointCacheSizeMax && ((Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type]) || TileID.Sets.Platforms[(int)tile.type]) && !WorldGen.SolidTile(Main.tile[i, j - 1]))
                    {
                        Vector2 vector = new Vector2((float)(i * 16 + 8), (float)(j * 16 - this.height / 2));
                        if (!tile.lava() && Collision.CanHitLine(vector, 0, 0, Main.player[this.target].Center, 0, 0))
{
                            NPC.kingSlimePointCache[NPC.kingSlimePointCacheSize].X = i;
                            NPC.kingSlimePointCache[NPC.kingSlimePointCacheSize].Y = j;
                            NPC.kingSlimePointCacheSize++;
                        }
                    }
                }
            }
        }
References Terraria.Collision.CanHitLine(), Terraria.Entity.Center, Terraria.Entity.height, Terraria.NPC.kingSlimePointCache, Terraria.NPC.kingSlimePointCacheSize, Terraria.NPC.kingSlimePointCacheSizeMax, Terraria.Tile.lava(), Terraria.Tile.nactive(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.NPC.BuildKingSlimeTeleportCache().