Terraria Decompiled: Terraria.NPC.moneyPing
moneyPing()
void Terraria.NPC.moneyPing (Vector2 pos) inline
Definition at line 90853 of file NPC.cs.
        {
            SoundEngine.PlaySound(38, pos, 1, 0f);
            int num = 244;
            if (this.extraValue >= 1000000)
            {
                num = 247;
            }
            else if (this.extraValue >= 10000)
            {
                num = 246;
            }
            else if (this.extraValue >= 100)
            {
                num = 245;
            }
            for (int i = 0; i < 20; i++)
            {
                int num2 = Dust.NewDust(pos - new Vector2(1f, 2f), 10, 14, num, 0f, 0f, 254, default(Color), 0.25f);
                Main.dust[num2].velocity *= 0.2f;
            }
        }
References Terraria.Main.dust, Terraria.Dust.NewDust(), Terraria.Audio.SoundEngine.PlaySound(), Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.Dust.velocity.
Referenced by Terraria.WorldItem.GetPickedUpByMonsters_Money(), and Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy().