Terraria Decompiled: Terraria.NPC.StrikeNPC
StrikeNPC()
double Terraria.NPC.StrikeNPC (int Damage, float knockBack, int hitDirection, bool crit = false, bool noEffect = false, bool fromNet = false, int owner = -1) inline
Definition at line 80234 of file NPC.cs.
        {
            if (owner < 0)
            {
                owner = Main.myPlayer;
            }
            if (Main.onlyShimmerOceanWorlds && this.type == 680 && this.GivenName == "Slimefors")
            {
                return 0.0;
            }
            bool flag = Main.netMode == 0;
            if (flag && NPC.ignorePlayerInteractions > 0)
            {
                NPC.ignorePlayerInteractions--;
                flag = false;
            }
            if (!this.active || this.life <= 0)
            {
                return 0.0;
            }
            this.NetUpdateLowPriority();
            double num = (double)Damage;
            num = Main.CalculateDamageNPCsTake((int)num, this.defense);
            if (crit)
            {
                num *= 2.0;
            }
            if (this.RedHatSkeletronAdjustmentsEnabled())
            {
                num = (double)((int)(num * 0.699999988079071));
                if (num < 1.0)
                {
                    num = 1.0;
                }
            }
            if (this.takenDamageMultiplier > 1f)
            {
                num *= (double)this.takenDamageMultiplier;
            }
            if ((this.takenDamageMultiplier > 1f || Damage != 9999) && this.lifeMax > 1)
            {
                if (this.friendly)
                {
                    Color color = (crit ? CombatText.DamagedFriendlyCrit : CombatText.DamagedFriendly);
                    CombatText.NewText(new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height), color, (int)num, crit, false);
                }
                else
                {
                    Color color2 = (crit ? CombatText.DamagedHostileCrit : CombatText.DamagedHostile);
                    if (fromNet)
                    {
                        color2 = (crit ? CombatText.OthersDamagedHostileCrit : CombatText.OthersDamagedHostile);
                    }
                    CombatText.NewText(new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height), color2, (int)num, crit, false);
                }
            }
            if (num >= 1.0)
            {
                if (flag)
                {
                    this.PlayerInteraction(Main.myPlayer);
                }
                this.justHit = true;
                if ((this.type == 438 || this.type == 379) && Main.netMode != 1)
                {
                    int num2 = (int)(-this.ai[3] - 1f);
                    if (num2 > -1 && Main.npc[num2].localAI[0] == 0f)
                    {
                        Main.npc[num2].localAI[0] = 1f;
                    }
                }
                if (this.townNPC)
                {
                    if (this.aiStyle == 7 && (this.ai[0] == 3f || this.ai[0] == 4f || this.ai[0] == 16f || this.ai[0] == 17f))
                    {
                        NPC npc = Main.npc[(int)this.ai[2]];
                        if (npc.active)
{
                            npc.ai[0] = 1f;
                            npc.ai[1] = (float)(300 + Main.rand.Next(300));
                            npc.ai[2] = 0f;
                            npc.localAI[3] = 0f;
                            npc.direction = hitDirection;
                            npc.netUpdate = true;
                        }
                    }
                    this.ai[0] = 1f;
                    this.ai[1] = (float)(300 + Main.rand.Next(300));
                    this.ai[2] = 0f;
                    this.localAI[3] = 0f;
                    this.direction = hitDirection;
                    this.netUpdate = true;
                }
                if (Main.netMode != 1 && this.aiStyle == 87 && this.ai[0] == 0f)
                {
                    this.ai[0] = 1f;
                    this.ai[1] = 0f;
                    this.netUpdate = true;
                }
                if (this.aiStyle == 8)
                {
                    if (Main.netMode != 1)
                    {
                        if (this.type == 172)
{
                            this.ai[0] = 450f;
                        }
                        else if (this.type == 283 || this.type == 284)
{
                            if (Main.rand.Next(2) == 0)
{
                                this.ai[0] = 390f;
                                this.netUpdate = true;
                            }
                        }
                        else if (this.type == 533)
{
                            if (Main.rand.Next(3) != 0)
{
                                this.ai[0] = 181f;
                                this.netUpdate = true;
                            }
                        }
                        else
{
                            this.ai[0] = 400f;
                        }
                        this.TargetClosest(true);
                    }
                    if (this.type == 693)
                    {
                        this.localAI[1] = this.localAI[0] + 250f;
                        this.localAI[2] = 10f;
                    }
                }
                if (this.aiStyle == 97 && Main.netMode != 1)
                {
                    this.localAI[1] = 1f;
                    this.TargetClosest(true);
                }
                if (this.type == 371)
                {
                    num = 0.0;
                    this.ai[0] = 1f;
                    this.ai[1] = 4f;
                    this.dontTakeDamage = true;
                }
                if (this.type == 346 && (double)this.life >= (double)this.lifeMax * 0.5 && (double)this.life - num < (double)this.lifeMax * 0.5)
                {
                    Gore.NewGore(this.position, this.velocity, 517, 1f);
                }
                if (this.type == 184)
                {
                    this.localAI[0] = 60f;
                }
                if (this.type == 535)
                {
                    this.localAI[0] = 60f;
                }
                if (this.type == 185)
                {
                    this.localAI[0] = 1f;
                }
                if (!this.immortal)
                {
                    bool flag2 = Damage >= 9999 && owner == 255;
                    if (Main.netMode != 1 && !flag2)
                    {
                        NPCDamageTracker.AddDamage(this, owner, (int)num);
                    }
                    if (this.realLife >= 0)
                    {
                        Main.npc[this.realLife].life -= (int)num;
                        this.life = Main.npc[this.realLife].life;
                        this.lifeMax = Main.npc[this.realLife].lifeMax;
                    }
                    else
                    {
                        this.life -= (int)num;
                    }
                }
                if (knockBack > 0f && this.knockBackResist > 0f)
                {
                    float num3 = knockBack * this.knockBackResist;
                    if (this.onFire2)
                    {
                        num3 *= 1.1f;
                    }
                    if (num3 > 8f)
                    {
                        float num4 = num3 - 8f;
                        num4 *= 0.9f;
                        num3 = 8f + num4;
                    }
                    if (num3 > 10f)
                    {
                        float num5 = num3 - 10f;
                        num5 *= 0.8f;
                        num3 = 10f + num5;
                    }
                    if (num3 > 12f)
                    {
                        float num6 = num3 - 12f;
                        num6 *= 0.7f;
                        num3 = 12f + num6;
                    }
                    if (num3 > 14f)
                    {
                        float num7 = num3 - 14f;
                        num7 *= 0.6f;
                        num3 = 14f + num7;
                    }
                    if (num3 > 16f)
                    {
                        num3 = 16f;
                    }
                    if (crit)
                    {
                        num3 *= 1.4f;
                    }
                    int num8 = (int)num * 10;
                    if (Main.expertMode)
                    {
                        num8 = (int)num * 15;
                    }
                    if (num8 > this.lifeMax)
                    {
                        if (hitDirection < 0 && this.velocity.X > -num3)
{
                            if (this.velocity.X > 0f)
{
                                this.velocity.X = this.velocity.X - num3;
                            }
                            this.velocity.X = this.velocity.X - num3;
                            if (this.velocity.X < -num3)
{
                                this.velocity.X = -num3;
                            }
                        }
                        else if (hitDirection > 0 && this.velocity.X < num3)
{
                            if (this.velocity.X < 0f)
{
                                this.velocity.X = this.velocity.X + num3;
                            }
                            this.velocity.X = this.velocity.X + num3;
                            if (this.velocity.X > num3)
{
                                this.velocity.X = num3;
                            }
                        }
                        if (this.type == 185)
{
                            num3 *= 1.5f;
                        }
                        if (!this.noGravity)
{
                            num3 *= -0.75f;
                        }
                        else
{
                            num3 *= -0.5f;
                        }
                        if (this.velocity.Y > num3)
{
                            this.velocity.Y = this.velocity.Y + num3;
                            if (this.velocity.Y < num3)
{
                                this.velocity.Y = num3;
                            }
                        }
                    }
                    else
                    {
                        if (!this.noGravity)
{
                            this.velocity.Y = -num3 * 0.75f * this.knockBackResist;
                        }
                        else
{
                            this.velocity.Y = -num3 * 0.5f * this.knockBackResist;
                        }
                        this.velocity.X = num3 * (float)hitDirection * this.knockBackResist;
                    }
                }
                if ((this.type == 113 || this.type == 114) && this.life <= 0)
                {
                    for (int i = 0; i < Main.maxNPCs; i++)
                    {
                        if (Main.npc[i].active && (Main.npc[i].type == 113 || Main.npc[i].type == 114))
{
                            Main.npc[i].HitEffect(hitDirection, num);
                        }
                    }
                }
                else
                {
                    this.HitEffect(hitDirection, num);
                }
                if (this.type == 1)
                {
                    int num9 = (int)this.ai[1];
                    if (num9 <= 5485)
                    {
                        if (num9 == 5484)
{
                            SoundEngine.PlaySound(SoundID.BellHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        }
                        if (num9 == 5485)
{
                            if (Main.rand.Next(5) == 0)
{
                                SoundEngine.PlaySound(SoundID.ChickenHurtRare, this.position, 0f, 1f);
                                goto IL_0BFF;
                            }
                            SoundEngine.PlaySound(SoundID.ChickenHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        }
                    }
                    else
                    {
                        switch (num9)
{
                        case 5499:
                            SoundEngine.PlaySound(SoundID.FrogHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5500:
                            SoundEngine.PlaySound(SoundID.GoatHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5501:
                            SoundEngine.PlaySound(SoundID.RetroHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5502:
                            SoundEngine.PlaySound(SoundID.CatHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5503:
                            SoundEngine.PlaySound(SoundID.DogHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5504:
                            SoundEngine.PlaySound(SoundID.TurkeyHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5505:
                            SoundEngine.PlaySound(SoundID.GoblinHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5506:
                            SoundEngine.PlaySound(SoundID.CrowHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5507:
                            SoundEngine.PlaySound(SoundID.BalloonHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5508:
                            SoundEngine.PlaySound(SoundID.UndeadHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        case 5509:
                            SoundEngine.PlaySound(SoundID.VampireHurt, this.position, 0f, 1f);
                            goto IL_0BFF;
                        default:
                            if (num9 == 5534)
{
                                SoundEngine.PlaySound(SoundID.FairyHurt, this.position, 0f, 1f);
                                goto IL_0BFF;
                            }
                            break;
                        }
                    }
                    if (this.HitSound != null)
                    {
                        SoundEngine.PlaySound(this.HitSound, this.position, 0f, 1f);
                    }
                }
                else if (this.HitSound != null)
                {
                    SoundEngine.PlaySound(this.HitSound, this.position, 0f, 1f);
                }
                IL_0BFF:
                if (this.realLife >= 0)
                {
                    Main.npc[this.realLife].checkDead();
                }
                else
                {
                    this.checkDead();
                }
                return num;
            }
            return 0.0;
        }
References Terraria.NPC.active, Terraria.GameContent.NPCDamageTracker.AddDamage(), Terraria.NPC.ai, Terraria.ID.SoundID.BalloonHurt, Terraria.ID.SoundID.BellHurt, Terraria.Main.CalculateDamageNPCsTake(), Terraria.ID.SoundID.CatHurt, Terraria.NPC.checkDead(), Terraria.ID.SoundID.ChickenHurt, Terraria.ID.SoundID.ChickenHurtRare, Terraria.ID.SoundID.CrowHurt, Terraria.GameContent.Damage, Terraria.CombatText.DamagedFriendly, Terraria.CombatText.DamagedHostile, Terraria.ID.SoundID.DogHurt, Terraria.Main.expertMode, Terraria.ID.SoundID.FairyHurt, Terraria.ID.SoundID.FrogHurt, Terraria.ID.SoundID.GoatHurt, Terraria.ID.SoundID.GoblinHurt, Terraria.NPC.HitEffect(), Terraria.NPC.ignorePlayerInteractions, int, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Gore.NewGore(), Terraria.CombatText.NewText(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.onlyShimmerOceanWorlds, Terraria.CombatText.OthersDamagedHostile, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.ID.SoundID.RetroHurt, Terraria.ID.SoundID.TurkeyHurt, Terraria.NPC.type, Terraria.ID.SoundID.UndeadHurt, and Terraria.ID.SoundID.VampireHurt.
Referenced by Terraria.Player.ApplyDamageToNPC(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.MessageBuffer.GetData(), and Terraria.Player.ProcessHitAgainstNPC().