Terraria Decompiled: Terraria.NPC.AI_000_TransformBoundNPC
AI_000_TransformBoundNPC()
void Terraria.NPC.AI_000_TransformBoundNPC (int playerID, int npcType) inline
Definition at line 41669 of file NPC.cs.
        {
            this.Transform(npcType, 0f, 0f, 0f, 0f, true);
            this.AI_007_TownEntities_UpdateSavedStates();
            Main.BestiaryTracker.Chats.RegisterChatStartWith(this);
            Main.player[playerID].SetTalkNPC(this.whoAmI);
            if (Main.netMode == 2)
            {
                NetMessage.SendData(40, -1, -1, null, playerID, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.NPC.AI_007_TownEntities_UpdateSavedStates(), Terraria.Main.BestiaryTracker, Terraria.Main.netMode, Terraria.Main.player, Terraria.NetMessage.SendData(), Terraria.Player.SetTalkNPC(), Terraria.NPC.Transform(), and Terraria.Entity.whoAmI.
Referenced by Terraria.NPC.AI().