Terraria Decompiled: Terraria.NPC.ReleaseNPC
ReleaseNPC()
static int Terraria.NPC.ReleaseNPC (int x, int y, int Type, int Style, int who) inline static
Definition at line 79107 of file NPC.cs.
        {
            int num = -1;
            if (Main.netMode == 1)
            {
                NetMessage.SendData(71, -1, -1, null, x, (float)y, (float)Type, (float)Style, 0, 0, 0);
            }
            else if (Type >= 0 && Type < (int)NPCID.Count && (Main.npcCatchable[Type] || who == Main.myPlayer) && NPC.CanReleaseNPCs(who))
            {
                if (Type <= 356)
                {
                    if (Type == 148)
                    {
                        int num2 = Type + Main.rand.Next(2);
                        num = NPC.NewNPC(NPC.GetSpawnSource_NPCRelease(who), x, y, num2, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num].releaseOwner = (short)who;
                        return num;
                    }
                    if (Type == 356)
                    {
                        num = NPC.NewNPC(NPC.GetSpawnSource_NPCRelease(who), x, y, Type, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num].ai[2] = (float)Style;
                        Main.npc[num].releaseOwner = (short)who;
                        return num;
                    }
                }
                else
                {
                    if (Type - 583 <= 2)
                    {
                        num = NPC.NewNPC(NPC.GetSpawnSource_NPCRelease(who), x, y, Type, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num].releaseOwner = (short)who;
                        Main.npc[num].ai[2] = 2f;
                        Main.npc[num].TargetClosest(true);
                        Main.npc[num].ai[3] = 0f;
                        Main.npc[num].netUpdate = true;
                        return num;
                    }
                    if (Type == 614)
                    {
                        num = NPC.NewNPC(NPC.GetSpawnSource_NPCRelease(who), x, y, Type, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num].releaseOwner = (short)who;
                        int num3 = Main.player[who].direction;
                        if (Style > 2)
{
                            Style -= 2;
                            Main.npc[num].SpawnedFromStatue = true;
                            Main.npc[num].CanBeReplacedByOtherNPCs = true;
                        }
                        if (Style == 1)
{
                            num3 = 1;
                        }
                        if (Style == 2)
{
                            num3 = -1;
                        }
                        Main.npc[num].direction = num3;
                        Main.npc[num].spriteDirection = num3;
                        Main.npc[num].netUpdate = true;
                        return num;
                    }
                }
                num = NPC.NewNPC(NPC.GetSpawnSource_NPCRelease(who), x, y, Type, 0, 0f, 0f, 0f, 0f, 255);
                Main.npc[num].releaseOwner = (short)who;
            }
            return num;
        }
References Terraria.NPC.ai, Terraria.NPC.CanBeReplacedByOtherNPCs, Terraria.NPC.CanReleaseNPCs(), Terraria.ID.NPCID.Count, Terraria.Entity.direction, Terraria.NPC.GetSpawnSource_NPCRelease(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.npcCatchable, Terraria.Main.player, Terraria.Main.rand, Terraria.NPC.releaseOwner, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnedFromStatue, Terraria.NPC.spriteDirection, and Terraria.NPC.TargetClosest().
Referenced by Terraria.WorldItem.GetShimmered(), Terraria.Projectile.HandleMovement(), and Terraria.Player.ItemCheck_ReleaseCritter().