Terraria Decompiled: Terraria.NPC.CheckProgressPumpkinMoon
CheckProgressPumpkinMoon()
void Terraria.NPC.CheckProgressPumpkinMoon () inline private
Definition at line 77293 of file NPC.cs.
        {
            if (Main.pumpkinMoon)
            {
                NetworkText networkText = NetworkText.Empty;
                int num = NPC.MoonEventRequiredPointsPerWaveLookup[NPC.waveNumber];
                switch (NPC.waveNumber)
                {
                case 1:
                    networkText = Lang.GetInvasionWaveText(2, new short[] { 326, 305 });
                    break;
                case 2:
                    networkText = Lang.GetInvasionWaveText(3, new short[] { 329, 326 });
                    break;
                case 3:
                    networkText = Lang.GetInvasionWaveText(4, new short[] { 330, 326, 305 });
                    break;
                case 4:
                    networkText = Lang.GetInvasionWaveText(5, new short[] { 315, 329 });
                    break;
                case 5:
                    networkText = Lang.GetInvasionWaveText(6, new short[] { 325, 326, 305 });
                    break;
                case 6:
                    networkText = Lang.GetInvasionWaveText(7, new short[] { 325, 330, 329 });
                    break;
                case 7:
                    networkText = Lang.GetInvasionWaveText(8, new short[] { 315, 330, 329 });
                    break;
                case 8:
                    networkText = Lang.GetInvasionWaveText(9, new short[] { 325, 330, 329, 326, 305 });
                    break;
                case 9:
                    networkText = Lang.GetInvasionWaveText(10, new short[] { 327, 329, 326 });
                    break;
                case 10:
                    networkText = Lang.GetInvasionWaveText(11, new short[] { 325, 330, 326 });
                    break;
                case 11:
                    networkText = Lang.GetInvasionWaveText(12, new short[] { 327, 330 });
                    break;
                case 12:
                    networkText = Lang.GetInvasionWaveText(13, new short[] { 325, 315, 330, 329, 326 });
                    break;
                case 13:
                    networkText = Lang.GetInvasionWaveText(14, new short[] { 327, 325, 315, 330, 329, 326, 305 });
                    break;
                case 14:
                    networkText = Lang.GetInvasionWaveText(15, new short[] { 327, 325, 330, 326, 305 });
                    break;
                case 15:
                    networkText = Lang.GetInvasionWaveText(16, new short[] { 327, 315, 330, 329, 326 });
                    break;
                case 16:
                    networkText = Lang.GetInvasionWaveText(17, new short[] { 327, 325, 315, 330, 329 });
                    break;
                case 17:
                    networkText = Lang.GetInvasionWaveText(18, new short[] { 327, 325, 315, 330 });
                    break;
                case 18:
                    networkText = Lang.GetInvasionWaveText(19, new short[] { 327, 325, 315 });
                    break;
                case 19:
                    networkText = Lang.GetInvasionWaveText(-1, new short[] { 327, 325, 315 });
                    break;
                }
                float num2 = 0f;
                switch (this.type)
                {
                case 305:
                case 306:
                case 307:
                case 308:
                case 309:
                case 310:
                case 311:
                case 312:
                case 313:
                case 314:
                    num2 = 1f;
                    break;
                case 315:
                    num2 = 50f;
                    break;
                case 325:
                    num2 = 75f;
                    break;
                case 326:
                    num2 = 2f;
                    break;
                case 327:
                    num2 = 150f;
                    break;
                case 329:
                    num2 = 5f;
                    break;
                case 330:
                    num2 = 10f;
                    break;
                }
                num2 *= this.GetMoonEventPointScalar();
                float num3 = NPC.waveKills;
                NPC.waveKills += num2;
                NPC.totalInvasionPoints += num2;
                if (NPC.waveKills >= (float)num && num != 0)
                {
                    NPC.waveKills = 0f;
                    NPC.waveNumber++;
                    num = NPC.MoonEventRequiredPointsPerWaveLookup[NPC.waveNumber];
                    if (networkText != NetworkText.Empty)
                    {
                        ChatHelper.BroadcastChatMessage(networkText, ChatColors.BossOrEvent, -1);
                        if (NPC.waveNumber == 15)
{
                            AchievementsHelper.NotifyProgressionEvent(15);
                        }
                    }
                }
                if (NPC.waveKills != num3 && num2 != 0f)
                {
                    if (Main.netMode != 1)
                    {
                        Main.ReportInvasionProgress((int)NPC.waveKills, num, 2, NPC.waveNumber);
                    }
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, (float)Main.invasionProgressMax, 2f, (float)NPC.waveNumber, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.Empty, Terraria.Lang.GetInvasionWaveText(), Terraria.NPC.GetMoonEventPointScalar(), Terraria.Main.invasionProgress, Terraria.Main.invasionProgressMax, Terraria.NPC.MoonEventRequiredPointsPerWaveLookup, Terraria.Main.netMode, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.pumpkinMoon, Terraria.Main.ReportInvasionProgress(), Terraria.NetMessage.SendData(), Terraria.NPC.type, Terraria.NPC.waveKills, and Terraria.NPC.waveNumber.
Referenced by Terraria.NPC.checkDead().