Terraria Decompiled: Terraria.NPC.GiveTownUniqueDataToNPCsThatNeedIt
GiveTownUniqueDataToNPCsThatNeedIt()
static void Terraria.NPC.GiveTownUniqueDataToNPCsThatNeedIt (int Type, int nextNPC) inline static private
Definition at line 79849 of file NPC.cs.
        {
            NPC npc = Main.npc[nextNPC];
            if (npc.isLikeATownNPC)
            {
                npc.GivenName = NPC.getNewNPCName(Type);
                ITownNPCProfile townNPCProfile;
                if (TownNPCProfiles.Instance.GetProfile(Type, out townNPCProfile))
                {
                    npc.townNpcVariationIndex = townNPCProfile.RollVariation();
                    npc.GivenName = townNPCProfile.GetNameForVariant(npc);
                }
                if (NPC.ShimmeredTownNPCs[Type])
                {
                    npc.townNpcVariationIndex = 1;
                }
                npc.needsUniqueInfoUpdate = true;
            }
        }
References Terraria.GameContent.ITownNPCProfile.GetNameForVariant(), Terraria.NPC.getNewNPCName(), Terraria.GameContent.TownNPCProfiles.GetProfile(), Terraria.GameContent.TownNPCProfiles.Instance, Terraria.NPC.isLikeATownNPC, Terraria.Main.npc, Terraria.GameContent.ITownNPCProfile.RollVariation(), and Terraria.NPC.ShimmeredTownNPCs.
Referenced by Terraria.NPC.NewNPC(), and Terraria.NPC.Transform().