Terraria Decompiled: Terraria.NPC.AI_123_Deerclops_ShootRubbleUp
AI_123_Deerclops_ShootRubbleUp()
void Terraria.NPC.AI_123_Deerclops_ShootRubbleUp (ref NPCAimedTarget targetData, ref Point sourceTileCoords, int howMany, int distancedByThisManyTiles, float upBiasPerSpike, int whichOne) inline private
Definition at line 41195 of file NPC.cs.
        {
            int num = 18;
            int num2 = whichOne * distancedByThisManyTiles;
            for (int i = 0; i < 35; i++)
            {
                int num3 = sourceTileCoords.X + num2 * this.direction;
                int num4 = sourceTileCoords.Y + i;
                if (WorldGen.SolidTile(num3, num4, false))
                {
                    Vector2 vector = targetData.Center + new Vector2((float)(num2 * this.direction * 20), -upBiasPerSpike * (float)howMany + (float)num2 * upBiasPerSpike / (float)distancedByThisManyTiles);
                    Vector2 vector2 = new Vector2((float)(num3 * 16 + 8), (float)(num4 * 16 + 8));
                    Vector2 vector3 = (vector - vector2).SafeNormalize(-Vector2.UnitY);
                    vector3 = new Vector2(0f, -1f).RotatedBy((double)((float)(whichOne * this.direction) * 0.7f * (0.7853982f / (float)howMany)), default(Vector2));
                    int num5 = Main.rand.Next(Main.projFrames[962] * 4);
                    num5 = 6 + Main.rand.Next(6);
                    Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), new Vector2((float)(num3 * 16 + 8), (float)(num4 * 16 - 8)), vector3 * (8f + Main.rand.NextFloat() * 8f), 962, num, 0f, Main.myPlayer, 0f, (float)num5, 0f, null);
                    return;
                }
            }
        }
References Terraria.Entity.direction, Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.projFrames, Terraria.Main.rand, Terraria.WorldGen.SolidTile(), Microsoft.Xna.Framework.Vector2.UnitY, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.NPC.AI_123_Deerclops().