Terraria Decompiled: Terraria.NPC.GetHurtByDebuff
GetHurtByDebuff()
void Terraria.NPC.GetHurtByDebuff (int amount) inline
Definition at line 92906 of file NPC.cs.
        {
            if (Main.netMode != 1)
            {
                NPCDamageTracker.AddDamage(this, 255, amount);
            }
            int whoAmI = this.whoAmI;
            if (this.realLife >= 0)
            {
                whoAmI = this.realLife;
            }
            if (!Main.npc[whoAmI].immortal)
            {
                Main.npc[whoAmI].life -= amount;
            }
            CombatText.NewText(new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height), CombatText.LifeRegenNegative, amount, false, true);
            if (Main.npc[whoAmI].life <= 0 && !Main.npc[whoAmI].immortal)
            {
                Main.npc[whoAmI].life = 1;
                if (Main.netMode != 1)
                {
                    Main.npc[whoAmI].StrikeNPCNoInteraction(9999, 0f, 0, false, false, false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(28, -1, -1, null, whoAmI, 9999f, 0f, 0f, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.GameContent.NPCDamageTracker.AddDamage(), Terraria.NPC.immortal, Terraria.NPC.life, Terraria.CombatText.LifeRegenNegative, Terraria.Main.netMode, Terraria.CombatText.NewText(), Terraria.Main.npc, Terraria.NetMessage.SendData(), and Terraria.NPC.StrikeNPCNoInteraction().