Terraria Decompiled: Terraria.NPC.RedHatSkeletron
RedHatSkeletron()
static void Terraria.NPC.RedHatSkeletron (int onWho) inline static
Definition at line 79420 of file NPC.cs.
        {
            if (Main.netMode == 1 || Main.IsItDay())
            {
                return;
            }
            Player player = Main.player[onWho];
            if (!player.killClothier)
            {
                return;
            }
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc != null && npc.active && npc.type == 54 && Collision.CanHit(player, npc))
                {
                    NPC.SpawnSkeletron(onWho, true);
                    Main.npc[i].ai[3] = 1f;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(23, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                    }
                    return;
                }
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.Collision.CanHit(), Terraria.Main.IsItDay(), Terraria.Player.killClothier, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.Main.npc, Terraria.Main.player, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnSkeletron(), and Terraria.NPC.type.
Referenced by Terraria.GameContent.PlayerSittingHelper.UpdateSitting().