Terraria Decompiled: Terraria.NPC.NPCLoot_DropLihzahrdStuff
NPCLoot_DropLihzahrdStuff()
void Terraria.NPC.NPCLoot_DropLihzahrdStuff () inline private
Definition at line 78577 of file NPC.cs.
        {
            WorldGen.Skyblock.noTemple = false;
            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 1294, 1, false, 0, false);
            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 1292, 1, false, 0, false);
            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 1101, Main.rand.Next(500, 601), false, 0, false);
            Item.NewItem(this.GetItemSource_Loot(), (int)this.position.X, (int)this.position.Y, this.width, this.height, 5376, Main.rand.Next(1200, 1501), false, 0, false);
        }
References Terraria.NPC.GetItemSource_Loot(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Entity.position, Terraria.Main.rand, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.NPC.NPCLoot().