Terraria Decompiled: Terraria.NPC.OnGameEventClearedForTheFirstTime
OnGameEventClearedForTheFirstTime()
static void Terraria.NPC.OnGameEventClearedForTheFirstTime (int gameEventId) inline static
Definition at line 77482 of file NPC.cs.
        {
            if (gameEventId <= 10)
            {
                if (gameEventId == 4)
                {
                    goto IL_0063;
                }
                if (gameEventId == 10)
                {
                    LanternNight.NextNightIsLanternNight = true;
                    CreditsRollEvent.TryStartingCreditsRoll();
                    goto IL_0063;
                }
            }
            else if (gameEventId - 16 > 2)
            {
                if (gameEventId - 21 <= 1)
                {
                    goto IL_0063;
                }
            }
            else
            {
                LanternNight.NextNightIsLanternNight = true;
                if (Main.netMode != 1 && Main.hardMode && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3)
                {
                    WorldGen.GeneratePlanteraBulbOnAllMechsDefeated();
                    goto IL_0063;
                }
                goto IL_0063;
            }
            LanternNight.NextNightIsLanternNight = true;
            IL_0063:
            if (Main.dualDungeonsSeed)
            {
                switch (gameEventId)
                {
                case 8:
                    WorldGen.ClearUnbreakableWallsWithPaintUpTo(DualDungeonUnbreakableWallTiers.JungleBoss);
                    return;
                case 9:
                case 10:
                case 12:
                case 20:
                case 21:
                case 22:
                case 23:
                    break;
                case 11:
                case 13:
                    WorldGen.ClearUnbreakableWallsWithPaintUpTo(DualDungeonUnbreakableWallTiers.EarlyGame);
                    return;
                case 14:
                    WorldGen.ClearUnbreakableWallsWithPaintUpTo(DualDungeonUnbreakableWallTiers.EvilBoss);
                    return;
                case 15:
                case 19:
                    WorldGen.ClearUnbreakableWallsWithPaintUpTo(DualDungeonUnbreakableWallTiers.Dungeon);
                    return;
                case 16:
                case 17:
                case 18:
                case 24:
                    WorldGen.ClearUnbreakableWallsWithPaintUpTo(DualDungeonUnbreakableWallTiers.Hallow);
                    break;
                default:
                    return;
                }
            }
        }
References Terraria.WorldGen.ClearUnbreakableWallsWithPaintUpTo(), Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.Main.dualDungeonsSeed, Terraria.GameContent.Generation.Dungeon.DualDungeonUnbreakableWallTiers.Dungeon, Terraria.GameContent.Generation.Dungeon.DualDungeonUnbreakableWallTiers.EarlyGame, Terraria.GameContent.Generation.Dungeon.DualDungeonUnbreakableWallTiers.EvilBoss, Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated(), Terraria.GameContent.Generation.Dungeon.DualDungeonUnbreakableWallTiers.Hallow, Terraria.Main.hardMode, Terraria.GameContent.Generation.Dungeon.DualDungeonUnbreakableWallTiers.JungleBoss, Terraria.Main.netMode, and Terraria.GameContent.Events.CreditsRollEvent.TryStartingCreditsRoll().
Referenced by Terraria.NPC.SetEventFlagCleared().