Terraria Decompiled: Terraria.NPC.GetSpawnSourceForNPCFromNPCAI
GetSpawnSourceForNPCFromNPCAI()
IEntitySource Terraria.NPC.GetSpawnSourceForNPCFromNPCAI () inline
Definition at line 91603 of file NPC.cs.
        {
            return new EntitySource_Parent(this);
        }
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_045_Golem(), Terraria.NPC.AI_069_DukeFishron(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_127_Pal(), Terraria.NPC.checkDead(), and Terraria.NPC.ViolentlySpawnNerdySlime().