Terraria Decompiled: Terraria.NPC.AI_126_StatueMimic
AI_126_StatueMimic()
void Terraria.NPC.AI_126_StatueMimic () inline private
Definition at line 40172 of file NPC.cs.
        {
            if (this.noTileCollide)
            {
                this.wet = false;
            }
            if (this.ai[0] == 0f)
            {
                this.timeLeft = 60;
                this.TargetClosest(true);
                this.direction = this.oldDirection;
                if (Main.netMode != 1)
                {
                    if (this.localAI[1] == 0f)
                    {
                        this.localAI[1] = 1f;
                        this.ai[1] = (float)WorldGen.GetRandomStatueStyleForStatueMimics();
                        this.netUpdate = true;
                    }
                    this.localAI[0] += 1f;
                    Vector2 vector = base.Center - Main.player[this.target].Center;
                    if (!Main.player[this.target].dead && vector.Length() < 96f)
                    {
                        if (Collision.CanHit(this, Main.player[this.target]))
{
                            this.ai[0] = 1f;
                            this.netUpdate = true;
                            return;
                        }
                    }
                    else if (this.localAI[0] >= 10f)
                    {
                        this.localAI[0] = 0f;
                        if (!NPC.CanAnyPlayerSeeThisTile((int)base.Center.X / 16, (int)base.Bottom.Y / 16))
{
                            int num = 0;
                            int num2;
                            int num3;
                            if (Math.Abs(Main.player[this.target].Center.X - base.Center.X) < (float)(NPC.sWidth / 2))
{
                                num2 = (int)((Main.player[this.target].Center.X - (float)(NPC.sWidth / 2) - (float)num) / 16f);
                                num3 = (int)((Main.player[this.target].Center.X + (float)(NPC.sWidth / 2) + (float)num) / 16f);
                            }
                            else if (Main.player[this.target].Center.X < base.Center.X)
{
                                num2 = (int)((Main.player[this.target].Center.X + (float)(NPC.sWidth / 2) + (float)num) / 16f);
                                num3 = (int)(base.Center.X / 16f);
                            }
                            else
{
                                num2 = (int)(base.Center.X / 16f);
                                num3 = (int)((Main.player[this.target].Center.X - (float)(NPC.sWidth / 2) - (float)num) / 16f);
                            }
                            int num4;
                            int num5;
                            if (Math.Abs(Main.player[this.target].Center.Y - base.Center.Y) < (float)(NPC.sHeight / 2))
{
                                num4 = (int)((Main.player[this.target].Center.Y - (float)(NPC.sHeight / 2) - (float)num) / 16f);
                                num5 = (int)((Main.player[this.target].Center.Y + (float)(NPC.sHeight / 2) + (float)num) / 16f);
                            }
                            else if (Main.player[this.target].Center.Y < base.Center.Y)
{
                                num4 = (int)((Main.player[this.target].Center.Y + (float)(NPC.sHeight / 2) + (float)num) / 16f);
                                num5 = (int)(base.Center.Y / 16f);
                            }
                            else
{
                                num4 = (int)(base.Center.Y / 16f);
                                num5 = (int)((Main.player[this.target].Center.Y - (float)(NPC.sHeight / 2) - (float)num) / 16f);
                            }
                            for (int i = 10; i > 0; i--)
{
                                int num6 = Main.rand.Next(num2, num3);
                                int num7 = Main.rand.Next(num4, num5);
                                bool flag = false;
                                int j = 0;
                                while (j < 10)
{
                                    if (WorldGen.SolidTile2(num6, num7) && WorldGen.SolidTile2(num6 + 1, num7))
{
                                        if (!NPC.CanAnyPlayerSeeThisTile(num6 + 1, num7))
{
                                            flag = true;
                                            break;
                                        }
                                        break;
                                    }
                                    else
{
                                        num7++;
                                        j++;
                                    }
                                }
                                if (flag && NPC.IsThisAGoodPlaceForAStatueMimic(num6, num7))
{
                                    Vector2 vector2 = new Vector2((float)(num6 * 16 + 16 - this.width / 2), (float)(num7 * 16 - this.height));
                                    Vector2 vector3 = this.position - Main.player[this.target].position;
                                    if ((vector2 - Main.player[this.target].position).Length() < vector3.Length())
{
                                        if (vector2.X < this.position.X)
{
                                            this.direction = -1;
                                        }
                                        else if (vector2.X > this.position.X)
{
                                            this.direction = 1;
                                        }
                                        this.position = vector2;
                                        this.netUpdate = true;
                                        return;
                                    }
                                }
                            }
                            return;
                        }
                    }
                }
            }
            else
            {
                this.immortal = false;
                this.dontTakeDamage = false;
                bool flag2 = false;
                if (this.localAI[2] == 0f)
                {
                    this.localAI[2] = 1f;
                    SoundEngine.PlaySound(SoundID.StatueMimicScare, base.Center, 0f, 1f);
                }
                if (this.velocity.Y > 0f && base.Top.Y > Main.player[this.target].Bottom.Y)
                {
                    if (Collision.SolidCollision(this.position, this.width, this.height))
                    {
                        flag2 = true;
                        SoundEngine.PlaySound(SoundID.StatueMimicJump, base.Center, 0f, 1f);
                        if ((base.Center - Main.player[this.target].Center).Length() > 480f)
{
                        }
                    }
                }
                else if (this.velocity.Y == 0f)
                {
                    int num8 = 20;
                    if (this.ai[2] == (float)num8)
                    {
                        SoundEngine.PlaySound(SoundID.StatueMimicJump, base.Center, 0f, 1f);
                    }
                    this.velocity.X = 0f;
                    this.ai[2] -= 1f;
                    if (this.ai[2] <= 0f)
                    {
                        this.ai[2] = (float)num8;
                        flag2 = true;
                        this.netUpdate = true;
                    }
                }
                bool flag3 = false;
                if (base.Right.X >= Main.player[this.target].Left.X && base.Left.X <= Main.player[this.target].Right.X)
                {
                    if (base.Bottom.Y < Main.player[this.target].Top.Y)
                    {
                        this.velocity.X = this.velocity.X * 0.75f;
                        if (this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y * 0.75f;
                        }
                    }
                    flag3 = true;
                }
                if (Main.player[this.target].dead)
                {
                    if (this.ai[3] == 0f)
                    {
                        SoundEngine.PlaySound(SoundID.StatueMimicLaugh, base.Center, 0f, 1f);
                        this.ai[3] = 300f;
                    }
                    if (this.ai[3] > 200f)
                    {
                        flag3 = true;
                        this.ai[3] -= 1f;
                    }
                }
                else if (this.ai[3] > 0f)
                {
                    this.ai[3] -= 1f;
                }
                if (flag2)
                {
                    this.noTileCollide = true;
                    this.TargetClosest(true);
                    float num9 = (base.Bottom.Y - Main.player[this.target].Bottom.Y) / 40f;
                    if (Main.player[this.target].dead)
                    {
                        num9 = 0f;
                    }
                    else
                    {
                        num9 = Utils.Clamp<float>(num9, 0f, 10f);
                    }
                    this.velocity.Y = -9.01f - num9;
                    float num10 = Math.Abs(base.Center.X - Main.player[this.target].Center.X) / 50f;
                    if (num10 > 12f)
                    {
                        num10 = 12f;
                    }
                    this.velocity.X = (4f + num10) * (float)this.direction;
                    this.netUpdate = true;
                    return;
                }
                if (this.velocity.Y != 0f)
                {
                    if (Main.player[this.target].dead && flag3 && base.Bottom.Y < Main.player[this.target].Bottom.Y)
                    {
                        this.velocity.Y = 16f;
                    }
                    else if (flag3 && base.Bottom.Y < Main.player[this.target].Top.Y)
                    {
                        this.velocity.Y = 16f;
                    }
                    else
                    {
                        if (this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y + NPC.gravity;
                        }
                        if (!Main.player[this.target].dead)
{
                            if (this.direction > 0 && base.Center.X > Main.player[this.target].Center.X)
{
                                this.velocity *= 0.96f;
                            }
                            if (this.direction < 0 && base.Center.X < Main.player[this.target].Center.X)
{
                                this.velocity *= 0.96f;
                            }
                        }
                    }
                    if (this.velocity.Y < 0f)
                    {
                        this.noTileCollide = true;
                        return;
                    }
                    if (flag3 && base.Bottom.Y < Main.player[this.target].Top.Y)
                    {
                        this.noTileCollide = true;
                        return;
                    }
                    if (!Collision.SolidCollision(this.position, this.width, this.height))
                    {
                        this.noTileCollide = false;
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.NPC.ai, Terraria.Entity.Bottom, Terraria.NPC.CanAnyPlayerSeeThisTile(), Terraria.Collision.CanHit(), Terraria.Entity.Center, Terraria.Utils.Clamp(), Terraria.Player.dead, Terraria.Entity.direction, Terraria.WorldGen.GetRandomStatueStyleForStatueMimics(), Terraria.NPC.gravity, Terraria.Entity.height, int, Terraria.NPC.IsThisAGoodPlaceForAStatueMimic(), Terraria.Entity.Left, Microsoft.Xna.Framework.Vector2.Length(), Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.noTileCollide, Terraria.Entity.oldDirection, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Entity.Right, Terraria.NPC.sHeight, Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile2(), Terraria.ID.SoundID.StatueMimicJump, Terraria.ID.SoundID.StatueMimicLaugh, Terraria.ID.SoundID.StatueMimicScare, Terraria.NPC.sWidth, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.Entity.Top, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().