Terraria Decompiled: Terraria.NPC.Transform
Transform()
void Terraria.NPC.Transform (int newType, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, float ai3 = 0f, bool withReposition = true) inline
Definition at line 80106 of file NPC.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            bool flag = this.value == 0f;
            int num = this.type;
            int num2 = this.life;
            int num3 = this.lifeMax;
            if (withReposition)
            {
                this.position.Y = this.position.Y + (float)this.height;
            }
            this.SetDefaults(newType, default(NPCSpawnParams));
            if (withReposition)
            {
                this.position.Y = this.position.Y - (float)this.height;
            }
            this.TargetClosest(true);
            if (flag)
            {
                this.value = 0f;
            }
            this.life = num2 * this.lifeMax / num3;
            if (this.life <= 0)
            {
                this.life = 1;
            }
            this.ai[0] = ai0;
            this.ai[1] = ai1;
            this.ai[2] = ai2;
            this.ai[3] = ai3;
            if (newType <= 369)
            {
                if (newType <= 124)
                {
                    if (newType - 107 > 1 && newType != 124)
                    {
                        goto IL_015B;
                    }
                }
                else if (newType != 353 && newType != 369)
                {
                    goto IL_015B;
                }
            }
            else if (newType <= 588)
            {
                if (newType != 550 && newType != 588)
                {
                    goto IL_015B;
                }
            }
            else if (newType - 679 > 1 && newType - 683 > 1)
            {
                goto IL_015B;
            }
            this.UpdateHomeTileState(true, (int)(this.position.X + (float)(this.width / 2)) / 16, (int)(this.position.Y + (float)this.height) / 16);
            IL_015B:
            if (Main.netMode == 2)
            {
                NetMessage.SendData(23, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                NetMessage.SendData(54, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
            }
            this.TransformVisuals(num, newType);
            NPC.GiveTownUniqueDataToNPCsThatNeedIt(this.type, this.whoAmI);
            if (this.townNPC)
            {
                this.homeless = true;
                WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            }
            this.altTexture = 0;
        }
References Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.NPC.GiveTownUniqueDataToNPCsThatNeedIt(), Terraria.Main.netMode, and Terraria.NetMessage.SendData().
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_000_TransformBoundNPC(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.Damage_TryUsingPowders(), Terraria.NPC.TransformCopperSlime(), and Terraria.NPC.TransformElderSlime().