Terraria Decompiled: Terraria.NPC.SpawnWOF
SpawnWOF()
static void Terraria.NPC.SpawnWOF (Vector2 pos) inline static
Definition at line 79324 of file NPC.cs.
        {
            if (pos.Y / 16f < (float)(Main.maxTilesY - 205))
            {
                return;
            }
            if (Main.wofNPCIndex >= 0)
            {
                return;
            }
            if (Main.netMode == 1)
            {
                return;
            }
            if (NPC.AnyNPCs(113))
            {
                return;
            }
            Player.FindClosest(pos, 16, 16);
            int num = 1;
            if (pos.X / 16f > (float)(Main.maxTilesX / 2))
            {
                num = -1;
            }
            bool flag = false;
            int num2 = (int)pos.X;
            int num3 = 0;
            while (!flag)
            {
                flag = true;
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active && Main.player[i].position.X > (float)(num2 - 1200) && Main.player[i].position.X < (float)(num2 + 1200))
                    {
                        num2 -= num * 16;
                        flag = false;
                        num3 = i;
                    }
                }
                if (num2 / 16 < 20 || num2 / 16 > Main.maxTilesX - 20)
                {
                    flag = true;
                }
            }
            int num4 = (int)pos.Y;
            int num5 = num2 / 16;
            int num6 = num4 / 16;
            int num7 = 0;
            int num8 = 1000;
            if (!WorldGen.InWorld(num5, num6, 2) || WorldGen.SolidTile(num5, num6, false) || Main.tile[num5, num6 - num7].liquid >= 100)
            {
                for (;;)
                {
                    num8--;
                    if (num8 > 0)
                    {
                        try
{
                            if (WorldGen.InWorld(num5, num6 - num7, 2) && !WorldGen.SolidTile(num5, num6 - num7, false) && Main.tile[num5, num6 - num7].liquid < 100)
{
                                num6 -= num7;
                            }
                            else
{
                                if (!WorldGen.InWorld(num5, num6 + num7, 2) || WorldGen.SolidTile(num5, num6 + num7, false) || Main.tile[num5, num6 + num7].liquid >= 100)
{
                                    num7++;
                                    continue;
                                }
                                num6 += num7;
                            }
                        }
                        catch
{
                        }
                        break;
                    }
                    break;
                }
            }
            int num9 = Main.UnderworldLayer + 10;
            int num10 = num9 + 70;
            if (num6 < num9)
            {
                num6 = num9;
            }
            if (num6 > num10)
            {
                num6 = num10;
            }
            num4 = num6 * 16;
            int num11 = NPC.NewNPC(NPC.GetBossSpawnSource(num3), num2, num4, 113, 0, 0f, 0f, 0f, 0f, 255);
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { Main.npc[num11].GetTypeNetName() }), ChatColors.BossOrEvent, -1);
        }
References Terraria.Player.active, Terraria.NPC.AnyNPCs(), Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Player.FindClosest(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetBossSpawnSource(), int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.player, Terraria.Entity.position, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.wofNPCIndex, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.CheckLavaDeath(), and Terraria.NPC.DoDeathEvents().