Terraria Decompiled: Terraria.NPC.CountKillForAchievements
CountKillForAchievements()
void Terraria.NPC.CountKillForAchievements () inline private
Definition at line 78819 of file NPC.cs.
        {
            int num = this.type;
            if (num <= 126)
            {
                if (num - 13 > 2)
                {
                    if (num - 125 <= 1)
                    {
                        if (!NPC.AnyNPCs((this.type == 126) ? 125 : 126))
{
                            AchievementsHelper.NotifyNPCKilled(this);
                            AchievementsHelper.MechaMayhem_Kill(this.type);
                            return;
                        }
                        return;
                    }
                }
                else
                {
                    if (this.boss)
                    {
                        AchievementsHelper.NotifyNPCKilled(this);
                        return;
                    }
                    return;
                }
            }
            else if (num == 127 || num == 134)
            {
                AchievementsHelper.MechaMayhem_Kill(this.type);
                AchievementsHelper.NotifyNPCKilled(this);
                return;
            }
            AchievementsHelper.NotifyNPCKilled(this);
        }
References Terraria.NPC.AnyNPCs(), Terraria.NPC.boss, Terraria.GameContent.Achievements.AchievementsHelper.MechaMayhem_Kill(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyNPCKilled(), and Terraria.NPC.type.
Referenced by Terraria.NPC.NPCLoot().