Terraria Decompiled: Terraria.NPC.TypeToDefaultHeadIndex
TypeToDefaultHeadIndex()
static int Terraria.NPC.TypeToDefaultHeadIndex (int type) inline static
Definition at line 1114 of file NPC.cs.
        {
            if (type == 0)
            {
                return 0;
            }
            if (type == 17)
            {
                return 2;
            }
            if (type == 18)
            {
                return 3;
            }
            if (type == 19)
            {
                return 6;
            }
            if (type == 20)
            {
                return 5;
            }
            if (type == 22)
            {
                return 1;
            }
            if (type == 38)
            {
                return 4;
            }
            if (type == 54)
            {
                return 7;
            }
            if (type == 107)
            {
                return 9;
            }
            if (type == 108)
            {
                return 10;
            }
            if (type == 124)
            {
                return 8;
            }
            if (type == 142)
            {
                return 11;
            }
            if (type == 160)
            {
                return 12;
            }
            if (type == 178)
            {
                return 13;
            }
            if (type == 207)
            {
                return 14;
            }
            if (type == 208)
            {
                return 15;
            }
            if (type == 209)
            {
                return 16;
            }
            if (type == 227)
            {
                return 17;
            }
            if (type == 228)
            {
                return 18;
            }
            if (type == 229)
            {
                return 19;
            }
            if (type == 353)
            {
                return 20;
            }
            if (type == 368)
            {
                return 21;
            }
            if (type == 369)
            {
                return 22;
            }
            if (type == 441)
            {
                return 23;
            }
            if (type == 550)
            {
                return 24;
            }
            if (type == 588)
            {
                return 25;
            }
            if (type == 633)
            {
                return 26;
            }
            if (type == 663)
            {
                return 45;
            }
            if (type == 637)
            {
                return 27;
            }
            if (type == 638)
            {
                return 33;
            }
            if (type == 656)
            {
                return 39;
            }
            if (type == 670)
            {
                return 46;
            }
            if (type == 678)
            {
                return 47;
            }
            if (type == 679)
            {
                return 48;
            }
            if (type == 680)
            {
                return 49;
            }
            if (type == 681)
            {
                return 50;
            }
            if (type == 682)
            {
                return 51;
            }
            if (type == 683)
            {
                return 52;
            }
            if (type == 684)
            {
                return 53;
            }
            return -1;
        }
References Terraria.NPC.type.
Referenced by Terraria.Player.CollectTaxes(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.GameContent.TownNPCProfiles.GetHeadIndexSafe(), Terraria.NetMessage.SendNPCHousesAndTravelShop(), and Terraria.NPC.UpdateNetworkCode().