Terraria Decompiled: Terraria.NPC.AnyoneNearCultists
AnyoneNearCultists()
static bool Terraria.NPC.AnyoneNearCultists () inline static
Definition at line 79298 of file NPC.cs.
        {
            int num = NPC.FindFirstNPC(437);
            if (num == -1)
            {
                return false;
            }
            Rectangle rectangle = Utils.CenteredRectangle(Main.npc[num].Center, new Vector2(2500f, 1500f));
            Rectangle rectangle2 = new Rectangle(0, 0, 2500, 1500);
            Vector2 vector = rectangle2.Size() / 2f;
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active)
                {
                    rectangle2.X = (int)Main.player[i].Center.X - (int)vector.X;
                    rectangle2.Y = (int)Main.player[i].Center.Y - (int)vector.Y;
                    if (rectangle.Intersects(rectangle2))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Player.active, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.NPC.FindFirstNPC(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.npc, Terraria.Main.player, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.ItemCheck_CheckCanUse_Inner(), and Terraria.Player.ItemCheck_UseEventItems().