Terraria Decompiled: Terraria.NPC.Teleport
Teleport()
void Terraria.NPC.Teleport (Vector2 newPos, int Style = 0, int extraInfo = 0) inline
Definition at line 80063 of file NPC.cs.
        {
            int num = 0;
            if (Style == 4)
            {
                num = this.lastPortalColorIndex;
            }
            float num2 = ((this.teleportTime > 0f) ? 0.3f : 1f);
            Vector2 position = this.position;
            Main.TeleportEffect(this.getRect(), Style, num, num2, TeleportationSide.Entry, newPos);
            this.position = newPos;
            if (Style == 4)
            {
                this.lastPortalColorIndex = extraInfo;
                num = this.lastPortalColorIndex;
            }
            Main.TeleportEffect(this.getRect(), Style, num, num2, TeleportationSide.Exit, position);
            this.teleportTime = 1f;
            this.teleportStyle = Style;
            if (Main.netMode == 2 && Style != 4)
            {
                NetMessage.SendData(65, -1, -1, null, 1, (float)this.whoAmI, newPos.X, newPos.Y, Style, 0, 0);
            }
        }
References Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Main.TeleportEffect(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.Wiring.HitWireSingle(), Terraria.Wiring.Teleport(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), and Terraria.NPC.TryTeleportingCaughtMysticFrog().