Terraria Decompiled: Terraria.NPC.GetKnockbackMultiplier_ScaledByDifficulty
GetKnockbackMultiplier_ScaledByDifficulty()
float Terraria.NPC.GetKnockbackMultiplier_ScaledByDifficulty (float normalKnockbackMult) inline
Definition at line 475 of file NPC.cs.
        {
            return normalKnockbackMult * GameDifficultyData.KnockbackToEnemiesMultiplier.Sample(this.difficulty);
        }
References Terraria.NPC.difficulty, and Terraria.DataStructures.GameDifficultyData.KnockbackToEnemiesMultiplier.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_108_DivingFlyer(), and Terraria.NPC.ScaleStats_ByDifficulty().