Terraria Decompiled: Terraria.NPC.AI_015_KingSlime_FindTeleportSpot
AI_015_KingSlime_FindTeleportSpot()
bool Terraria.NPC.AI_015_KingSlime_FindTeleportSpot (bool antiCheese, ref float teleportSpotX, ref float teleportSpotY) inline private
Definition at line 39817 of file NPC.cs.
        {
            if (antiCheese)
            {
                int num = (int)Player.FindClosest(this.position, this.width, this.height);
                teleportSpotX = Main.player[num].Bottom.X;
                teleportSpotY = Main.player[num].Bottom.Y;
                return false;
            }
            Point point = Main.player[this.target].Center.ToTileCoordinates();
            if (this.BuildKingSlimeTeleportCache(point.X, point.Y, 10, 7))
            {
                int num2 = Main.rand.Next(0, NPC.kingSlimePointCacheSize);
                int x = NPC.kingSlimePointCache[num2].X;
                int y = NPC.kingSlimePointCache[num2].Y;
                teleportSpotX = (float)(x * 16 + 8);
                teleportSpotY = (float)(y * 16);
                return true;
            }
            if (this.BuildKingSlimeTeleportCache(point.X, point.Y, 6, 2))
            {
                int num3 = Main.rand.Next(0, NPC.kingSlimePointCacheSize);
                int x2 = NPC.kingSlimePointCache[num3].X;
                int y2 = NPC.kingSlimePointCache[num3].Y;
                teleportSpotX = (float)(x2 * 16 + 8);
                teleportSpotY = (float)(y2 * 16);
                return true;
            }
            int num4 = (int)Player.FindClosest(this.position, this.width, this.height);
            teleportSpotX = Main.player[num4].Bottom.X;
            teleportSpotY = Main.player[num4].Bottom.Y;
            return false;
        }
References Terraria.Entity.Bottom, Terraria.NPC.BuildKingSlimeTeleportCache(), Terraria.Entity.Center, Terraria.Player.FindClosest(), int, Terraria.NPC.kingSlimePointCache, Terraria.NPC.kingSlimePointCacheSize, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, Terraria.NPC.target, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI_015_KingSlime(), and Terraria.NPC.AI_121_QueenSlime().