Terraria Decompiled: Terraria.NPC.SpawnSkeletron
SpawnSkeletron()
static void Terraria.NPC.SpawnSkeletron (int onWho, bool redHatMode = false) inline static
Definition at line 79448 of file NPC.cs.
        {
            bool flag = true;
            bool flag2 = false;
            Vector2 vector = Vector2.Zero;
            int num = 0;
            int num2 = 0;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == 35)
                {
                    flag = false;
                    break;
                }
            }
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                if (Main.npc[j].active)
                {
                    if (Main.npc[j].type == 37)
                    {
                        flag2 = true;
                        Main.npc[j].ai[3] = 1f;
                        vector = Main.npc[j].position;
                        num = Main.npc[j].width;
                        num2 = Main.npc[j].height;
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(23, -1, -1, null, j, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    else if (Main.npc[j].type == 54)
                    {
                        flag2 = true;
                        vector = Main.npc[j].position;
                        num = Main.npc[j].width;
                        num2 = Main.npc[j].height;
                    }
                }
            }
            if (flag && flag2)
            {
                int num3 = NPC.NewNPC(NPC.GetBossSpawnSource(onWho), (int)vector.X + num / 2, (int)vector.Y + num2 / 2, 35, 0, 0f, 0f, 0f, 0f, 255);
                if (redHatMode)
                {
                    Main.npc[num3].ai[3] = 1f;
                }
                Main.npc[num3].netUpdate = true;
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { Lang.GetNPCName(35).ToNetworkText() }), ChatColors.BossOrEvent, -1);
            }
        }
References Terraria.NPC.active, Terraria.NPC.ai, Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetBossSpawnSource(), Terraria.Entity.height, Terraria.Main.maxNPCs, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.NPC.type, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.checkDead(), Terraria.GameContent.NPCInteractions.Actions.OldManCurse.Interact(), and Terraria.NPC.RedHatSkeletron().