Terraria Decompiled: Terraria.NPC.GetBossHeadTextureIndex
GetBossHeadTextureIndex()
int Terraria.NPC.GetBossHeadTextureIndex () inline
Definition at line 1276 of file NPC.cs.
        {
            int num = NPCID.Sets.BossHeadTextures[this.type];
            int num2 = this.type;
            if (num2 <= 126)
            {
                if (num2 != 4)
                {
                    if (num2 != 125)
                    {
                        if (num2 == 126)
{
                            if (this.ai[0] >= 3f)
{
                                num = 21;
                            }
                        }
                    }
                    else if (this.ai[0] >= 3f)
                    {
                        num = 16;
                    }
                }
                else if (this.ai[0] >= 2f)
                {
                    num = 1;
                }
            }
            else if (num2 <= 266)
            {
                if (num2 != 262)
                {
                    if (num2 == 266)
                    {
                        if (this.ai[0] < 0f || this.localAI[2] > 0f)
{
                            num = -1;
                        }
                    }
                }
                else if (this.life <= this.lifeMax / 2)
                {
                    num = 12;
                }
            }
            else if (num2 != 439)
            {
                if (num2 == 440)
                {
                    if (this.ai[0] != 5f || this.alpha == 255)
                    {
                        num = -1;
                    }
                }
            }
            else if (this.ai[0] == 5f && this.alpha == 255)
            {
                num = -1;
            }
            return num;
        }
References Terraria.NPC.ai, Terraria.NPC.alpha, Terraria.ID.NPCID.Sets.BossHeadTextures, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.localAI, and Terraria.NPC.type.
Referenced by Terraria.Main.DrawNPCMapIcons(), Terraria.Main.DrawNPCMapIcons2(), Terraria.Main.DrawNPCMapIcons3(), Terraria.GameContent.UI.BigProgressBar.CommonBossBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.DeerclopsBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.LunarPillarBigProgessBar.ValidateAndCollectNecessaryInfo(), and Terraria.GameContent.UI.BigProgressBar.TwinsBigProgressBar.ValidateAndCollectNecessaryInfo().