Terraria Decompiled: Terraria.NPC.SpawnPassiveShadowHands
SpawnPassiveShadowHands()
void Terraria.NPC.SpawnPassiveShadowHands (float lifePercent, int shadowHandDamage) inline private
Definition at line 41167 of file NPC.cs.
        {
            int num = (int)Utils.Remap(lifePercent, 1f, 0f, 80f, 40f, true);
            this.localAI[2] += 1f;
            int num2 = (int)this.localAI[2];
            if (num2 % num == 0)
            {
                int num3 = num2 / num;
                if (num2 / num >= 3)
                {
                    this.localAI[2] = 0f;
                }
                for (int i = 0; i < 255; i++)
                {
                    if (this.Boss_CanShootExtraAt(i, num3 % 3, 3, 1200f, false))
                    {
                        Vector2 vector;
                        Vector2 vector2;
                        float num4;
                        float num5;
                        Projectile.RandomizeInsanityShadowFor(Main.player[i], true, out vector, out vector2, out num4, out num5);
                        Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), vector, vector2, 965, shadowHandDamage, 0f, Main.myPlayer, num4, num5, 0f, null);
                    }
                }
            }
        }
References Terraria.NPC.Boss_CanShootExtraAt(), Terraria.NPC.GetSpawnSource_ForProjectile(), int, Terraria.NPC.localAI, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Main.player, Terraria.Projectile.RandomizeInsanityShadowFor(), and Terraria.Utils.Remap().
Referenced by Terraria.NPC.AI_123_Deerclops().