Terraria Decompiled: Terraria.NPC.LadyBugLuck
LadyBugLuck()
void Terraria.NPC.LadyBugLuck (int plr, bool GoldLadyBug = false) inline private
Definition at line 80658 of file NPC.cs.
        {
            if (this.releaseOwner == 255 && Main.player[plr].ladyBugLuckTimeLeft >= 0)
            {
                Vector2 vector = base.Center - Main.player[plr].Center;
                int num = 800;
                if (vector.Length() < (float)num)
                {
                    if (vector.Length() < 30f)
                    {
                        vector = default(Vector2);
                    }
                    double num2 = 1.0 - (double)vector.Length() / (double)num;
                    num2 = Math.Pow(num2, 6.0);
                    int num3 = (int)((double)NPC.ladyBugGoodLuckTime * num2);
                    if (GoldLadyBug)
                    {
                        num3 *= 2;
                    }
                    if (num3 > Main.player[plr].ladyBugLuckTimeLeft)
                    {
                        Main.player[plr].ladyBugLuckTimeLeft = num3;
                        Main.player[plr].luckNeedsSync = true;
                    }
                }
            }
        }
References Terraria.Entity.Center, int, Terraria.Player.ladyBugLuckTimeLeft, Microsoft.Xna.Framework.Vector2.Length(), Terraria.Player.luckNeedsSync, Terraria.Main.player, and System.Math.Pow().
Referenced by Terraria.NPC.CheckActive().