Terraria Decompiled: Terraria.NPC.AI_002_FloatingEye
AI_002_FloatingEye()
void Terraria.NPC.AI_002_FloatingEye () inline private
Definition at line 49267 of file NPC.cs.
        {
            if ((this.type == 170 || this.type == 171 || this.type == 180) && Main.rand.Next(1000) == 0)
            {
                SoundEngine.PlaySound(29, (int)this.position.X, (int)this.position.Y, 9, 1f, 0f);
            }
            this.noGravity = true;
            if (!this.noTileCollide)
            {
                if (this.collideX)
                {
                    this.velocity.X = this.oldVelocity.X * -0.5f;
                    if (this.direction == -1 && this.velocity.X > 0f && this.velocity.X < 2f)
                    {
                        this.velocity.X = 2f;
                    }
                    if (this.direction == 1 && this.velocity.X < 0f && this.velocity.X > -2f)
                    {
                        this.velocity.X = -2f;
                    }
                }
                if (this.collideY)
                {
                    this.velocity.Y = this.oldVelocity.Y * -0.5f;
                    if (this.velocity.Y > 0f && this.velocity.Y < 1f)
                    {
                        this.velocity.Y = 1f;
                    }
                    if (this.velocity.Y < 0f && this.velocity.Y > -1f)
                    {
                        this.velocity.Y = -1f;
                    }
                }
            }
            if (NPC.DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged(this.type, this.position, this.target))
            {
                this.EncourageDespawn(10);
                this.directionY = -1;
                if (this.velocity.Y > 0f)
                {
                    this.direction = 1;
                }
                this.direction = -1;
                if (this.velocity.X > 0f)
                {
                    this.direction = 1;
                }
            }
            else
            {
                this.TargetClosest(true);
            }
            if (this.type == 170 || this.type == 171 || this.type == 180)
            {
                if (Collision.CanHit(this.position, this.width, this.height, Main.player[this.target].position, Main.player[this.target].width, Main.player[this.target].height))
                {
                    if (this.ai[1] > 0f && !Collision.SolidCollision(this.position, this.width, this.height))
                    {
                        this.ai[1] = 0f;
                        this.ai[0] = 0f;
                        this.netUpdate = true;
                    }
                }
                else if (this.ai[1] == 0f)
                {
                    this.ai[0] += 1f;
                }
                if (this.ai[0] >= 300f)
                {
                    this.ai[1] = 1f;
                    this.ai[0] = 0f;
                    this.netUpdate = true;
                }
                if (this.ai[1] == 0f)
                {
                    this.alpha = 0;
                    this.noTileCollide = false;
                }
                else
                {
                    this.wet = false;
                    this.alpha = 200;
                    this.noTileCollide = true;
                }
                this.rotation = this.velocity.Y * 0.1f * (float)this.direction;
                this.TargetClosest(true);
                if (this.direction == -1 && this.velocity.X > -4f && this.position.X > Main.player[this.target].position.X + (float)Main.player[this.target].width)
                {
                    this.velocity.X = this.velocity.X - 0.08f;
                    if (this.velocity.X > 4f)
                    {
                        this.velocity.X = this.velocity.X - 0.04f;
                    }
                    else if (this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X - 0.2f;
                    }
                    if (this.velocity.X < -4f)
                    {
                        this.velocity.X = -4f;
                    }
                }
                else if (this.direction == 1 && this.velocity.X < 4f && this.position.X + (float)this.width < Main.player[this.target].position.X)
                {
                    this.velocity.X = this.velocity.X + 0.08f;
                    if (this.velocity.X < -4f)
                    {
                        this.velocity.X = this.velocity.X + 0.04f;
                    }
                    else if (this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X + 0.2f;
                    }
                    if (this.velocity.X > 4f)
                    {
                        this.velocity.X = 4f;
                    }
                }
                if (this.directionY == -1 && (double)this.velocity.Y > -2.5 && this.position.Y > Main.player[this.target].position.Y + (float)Main.player[this.target].height)
                {
                    this.velocity.Y = this.velocity.Y - 0.1f;
                    if ((double)this.velocity.Y > 2.5)
                    {
                        this.velocity.Y = this.velocity.Y - 0.05f;
                    }
                    else if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - 0.15f;
                    }
                    if ((double)this.velocity.Y < -2.5)
                    {
                        this.velocity.Y = -2.5f;
                    }
                }
                else if (this.directionY == 1 && (double)this.velocity.Y < 2.5 && this.position.Y + (float)this.height < Main.player[this.target].position.Y)
                {
                    this.velocity.Y = this.velocity.Y + 0.1f;
                    if ((double)this.velocity.Y < -2.5)
                    {
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                    else if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + 0.15f;
                    }
                    if ((double)this.velocity.Y > 2.5)
                    {
                        this.velocity.Y = 2.5f;
                    }
                }
            }
            else if (this.type == 116)
            {
                this.TargetClosest(true);
                Lighting.AddLight((int)(this.position.X + (float)(this.width / 2)) / 16, (int)(this.position.Y + (float)(this.height / 2)) / 16, 0.3f, 0.2f, 0.1f);
                if (this.direction == -1 && this.velocity.X > -6f)
                {
                    this.velocity.X = this.velocity.X - 0.1f;
                    if (this.velocity.X > 6f)
                    {
                        this.velocity.X = this.velocity.X - 0.1f;
                    }
                    else if (this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X - 0.2f;
                    }
                    if (this.velocity.X < -6f)
                    {
                        this.velocity.X = -6f;
                    }
                }
                else if (this.direction == 1 && this.velocity.X < 6f)
                {
                    this.velocity.X = this.velocity.X + 0.1f;
                    if (this.velocity.X < -6f)
                    {
                        this.velocity.X = this.velocity.X + 0.1f;
                    }
                    else if (this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X + 0.2f;
                    }
                    if (this.velocity.X > 6f)
                    {
                        this.velocity.X = 6f;
                    }
                }
                if (this.directionY == -1 && (double)this.velocity.Y > -2.5)
                {
                    this.velocity.Y = this.velocity.Y - 0.04f;
                    if ((double)this.velocity.Y > 2.5)
                    {
                        this.velocity.Y = this.velocity.Y - 0.05f;
                    }
                    else if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y - 0.15f;
                    }
                    if ((double)this.velocity.Y < -2.5)
                    {
                        this.velocity.Y = -2.5f;
                    }
                }
                else if (this.directionY == 1 && (double)this.velocity.Y < 1.5)
                {
                    this.velocity.Y = this.velocity.Y + 0.04f;
                    if ((double)this.velocity.Y < -2.5)
                    {
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                    else if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y + 0.15f;
                    }
                    if ((double)this.velocity.Y > 2.5)
                    {
                        this.velocity.Y = 2.5f;
                    }
                }
                if (Main.rand.Next(40) == 0)
                {
                    this.position += this.netOffset;
                    int num = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)this.height * 0.25f), this.width, (int)((float)this.height * 0.5f), 5, this.velocity.X, 2f, 0, default(Color), 1f);
                    Dust dust = Main.dust[num];
                    dust.velocity.X = dust.velocity.X * 0.5f;
                    Dust dust2 = Main.dust[num];
                    dust2.velocity.Y = dust2.velocity.Y * 0.1f;
                    this.position -= this.netOffset;
                }
            }
            else if (this.type == 133)
            {
                if ((double)this.life < (double)this.lifeMax * 0.5)
                {
                    if (this.direction == -1 && this.velocity.X > -6f)
                    {
                        this.velocity.X = this.velocity.X - 0.1f;
                        if (this.velocity.X > 6f)
{
                            this.velocity.X = this.velocity.X - 0.1f;
                        }
                        else if (this.velocity.X > 0f)
{
                            this.velocity.X = this.velocity.X + 0.05f;
                        }
                        if (this.velocity.X < -6f)
{
                            this.velocity.X = -6f;
                        }
                    }
                    else if (this.direction == 1 && this.velocity.X < 6f)
                    {
                        this.velocity.X = this.velocity.X + 0.1f;
                        if (this.velocity.X < -6f)
{
                            this.velocity.X = this.velocity.X + 0.1f;
                        }
                        else if (this.velocity.X < 0f)
{
                            this.velocity.X = this.velocity.X - 0.05f;
                        }
                        if (this.velocity.X > 6f)
{
                            this.velocity.X = 6f;
                        }
                    }
                    if (this.directionY == -1 && this.velocity.Y > -4f)
                    {
                        this.velocity.Y = this.velocity.Y - 0.1f;
                        if (this.velocity.Y > 4f)
{
                            this.velocity.Y = this.velocity.Y - 0.1f;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y + 0.05f;
                        }
                        if (this.velocity.Y < -4f)
{
                            this.velocity.Y = -4f;
                        }
                    }
                    else if (this.directionY == 1 && this.velocity.Y < 4f)
                    {
                        this.velocity.Y = this.velocity.Y + 0.1f;
                        if (this.velocity.Y < -4f)
{
                            this.velocity.Y = this.velocity.Y + 0.1f;
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y - 0.05f;
                        }
                        if (this.velocity.Y > 4f)
{
                            this.velocity.Y = 4f;
                        }
                    }
                }
                else
                {
                    if (this.direction == -1 && this.velocity.X > -4f)
                    {
                        this.velocity.X = this.velocity.X - 0.1f;
                        if (this.velocity.X > 4f)
{
                            this.velocity.X = this.velocity.X - 0.1f;
                        }
                        else if (this.velocity.X > 0f)
{
                            this.velocity.X = this.velocity.X + 0.05f;
                        }
                        if (this.velocity.X < -4f)
{
                            this.velocity.X = -4f;
                        }
                    }
                    else if (this.direction == 1 && this.velocity.X < 4f)
                    {
                        this.velocity.X = this.velocity.X + 0.1f;
                        if (this.velocity.X < -4f)
{
                            this.velocity.X = this.velocity.X + 0.1f;
                        }
                        else if (this.velocity.X < 0f)
{
                            this.velocity.X = this.velocity.X - 0.05f;
                        }
                        if (this.velocity.X > 4f)
{
                            this.velocity.X = 4f;
                        }
                    }
                    if (this.directionY == -1 && (double)this.velocity.Y > -1.5)
                    {
                        this.velocity.Y = this.velocity.Y - 0.04f;
                        if ((double)this.velocity.Y > 1.5)
{
                            this.velocity.Y = this.velocity.Y - 0.05f;
                        }
                        else if (this.velocity.Y > 0f)
{
                            this.velocity.Y = this.velocity.Y + 0.03f;
                        }
                        if ((double)this.velocity.Y < -1.5)
{
                            this.velocity.Y = -1.5f;
                        }
                    }
                    else if (this.directionY == 1 && (double)this.velocity.Y < 1.5)
                    {
                        this.velocity.Y = this.velocity.Y + 0.04f;
                        if ((double)this.velocity.Y < -1.5)
{
                            this.velocity.Y = this.velocity.Y + 0.05f;
                        }
                        else if (this.velocity.Y < 0f)
{
                            this.velocity.Y = this.velocity.Y - 0.03f;
                        }
                        if ((double)this.velocity.Y > 1.5)
{
                            this.velocity.Y = 1.5f;
                        }
                    }
                }
            }
            else
            {
                float num2 = 4f;
                float num3 = 1.5f;
                num2 *= 1f + (1f - this.scale);
                num3 *= 1f + (1f - this.scale);
                if (this.direction == -1 && this.velocity.X > -num2)
                {
                    this.velocity.X = this.velocity.X - 0.1f;
                    if (this.velocity.X > num2)
                    {
                        this.velocity.X = this.velocity.X - 0.1f;
                    }
                    else if (this.velocity.X > 0f)
                    {
                        this.velocity.X = this.velocity.X + 0.05f;
                    }
                    if (this.velocity.X < -num2)
                    {
                        this.velocity.X = -num2;
                    }
                }
                else if (this.direction == 1 && this.velocity.X < num2)
                {
                    this.velocity.X = this.velocity.X + 0.1f;
                    if (this.velocity.X < -num2)
                    {
                        this.velocity.X = this.velocity.X + 0.1f;
                    }
                    else if (this.velocity.X < 0f)
                    {
                        this.velocity.X = this.velocity.X - 0.05f;
                    }
                    if (this.velocity.X > num2)
                    {
                        this.velocity.X = num2;
                    }
                }
                if (this.directionY == -1 && this.velocity.Y > -num3)
                {
                    this.velocity.Y = this.velocity.Y - 0.04f;
                    if (this.velocity.Y > num3)
                    {
                        this.velocity.Y = this.velocity.Y - 0.05f;
                    }
                    else if (this.velocity.Y > 0f)
                    {
                        this.velocity.Y = this.velocity.Y + 0.03f;
                    }
                    if (this.velocity.Y < -num3)
                    {
                        this.velocity.Y = -num3;
                    }
                }
                else if (this.directionY == 1 && this.velocity.Y < num3)
                {
                    this.velocity.Y = this.velocity.Y + 0.04f;
                    if (this.velocity.Y < -num3)
                    {
                        this.velocity.Y = this.velocity.Y + 0.05f;
                    }
                    else if (this.velocity.Y < 0f)
                    {
                        this.velocity.Y = this.velocity.Y - 0.03f;
                    }
                    if (this.velocity.Y > num3)
                    {
                        this.velocity.Y = num3;
                    }
                }
            }
            if ((this.type == 2 || this.type == 133 || this.type == 190 || this.type == 191 || this.type == 192 || this.type == 193 || this.type == 194) && Main.rand.Next(40) == 0)
            {
                this.position += this.netOffset;
                int num4 = Dust.NewDust(new Vector2(this.position.X, this.position.Y + (float)this.height * 0.25f), this.width, (int)((float)this.height * 0.5f), 5, this.velocity.X, 2f, 0, default(Color), 1f);
                Dust dust3 = Main.dust[num4];
                dust3.velocity.X = dust3.velocity.X * 0.5f;
                Dust dust4 = Main.dust[num4];
                dust4.velocity.Y = dust4.velocity.Y * 0.1f;
                this.position -= this.netOffset;
            }
            if (this.wet && this.type != 170 && this.type != 171 && this.type != 180)
            {
                if (this.velocity.Y > 0f)
                {
                    this.velocity.Y = this.velocity.Y * 0.95f;
                }
                this.velocity.Y = this.velocity.Y - 0.5f;
                if (this.velocity.Y < -4f)
                {
                    this.velocity.Y = -4f;
                }
                this.TargetClosest(true);
            }
        }
References Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.Collision.CanHit(), Terraria.NPC.collideX, Terraria.NPC.collideY, Terraria.NPC.DespawnEncouragement_AIStyle2_FloatingEye_IsDiscouraged(), Terraria.Entity.direction, Terraria.NPC.directionY, Terraria.Main.dust, Terraria.NPC.EncourageDespawn(), Terraria.Entity.height, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.NPC.netOffset, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.NPC.noTileCollide, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.scale, Terraria.Collision.SolidCollision(), Terraria.NPC.TargetClosest(), Terraria.NPC.type, Microsoft.Xna.Framework.Graphics.Vector2, Terraria.Entity.velocity, Terraria.Entity.wet, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().