Terraria Decompiled: Terraria.NPC.SetDefaultsFromNetId
SetDefaultsFromNetId()
void Terraria.NPC.SetDefaultsFromNetId (int id, NPCSpawnParams spawnparams = default(NPCSpawnParams)) inline private
Definition at line 1405 of file NPC.cs.
        {
            bool flag = false;
            int num = NPCID.FromNetId(id);
            this.SetDefaults(0, default(NPCSpawnParams));
            if (id == -1)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.6f);
                flag = true;
                this.damage = 45;
                this.defense = 10;
                this.life = 90;
                this.knockBackResist *= 1.2f;
                this.value = 100f;
            }
            else if (id == -2)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = true;
                this.damage = 45;
                this.defense = 20;
                this.life = 90;
                this.knockBackResist *= 1.2f;
                this.value = 100f;
            }
            else if (id == -3)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = true;
                this.damage = 6;
                this.defense = 0;
                this.life = 14;
                this.knockBackResist *= 1.2f;
                this.color = new Color(0, 220, 40, 100);
                this.value = 3f;
            }
            else if (id == -4)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.6f);
                flag = true;
                this.damage = 5;
                this.defense = 5;
                this.life = 150;
                this.knockBackResist *= 1.4f;
                this.color = new Color(250, 30, 90, 90);
                this.value = 10000f;
                this.rarity = 2;
            }
            else if (id == -5)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = true;
                this.damage = 13;
                this.defense = 4;
                this.life = 30;
                this.knockBackResist *= 0.95f;
                this.alpha = 120;
                this.color = new Color(0, 0, 0, 50);
                this.value = 10f;
            }
            else if (id == -6)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.05f);
                flag = true;
                this.damage = 15;
                this.defense = 4;
                this.life = 45;
                this.color = new Color(0, 0, 0, 50);
                this.value = 20f;
            }
            else if (id == -7)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.2f);
                flag = true;
                this.damage = 12;
                this.defense = 6;
                this.life = 40;
                this.knockBackResist *= 0.9f;
                this.color = new Color(200, 0, 255, 150);
                this.value = 10f;
            }
            else if (id == -8)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.025f);
                flag = true;
                this.damage = 12;
                this.defense = 4;
                this.life = 35;
                this.color = new Color(255, 30, 0, 100);
                this.value = 8f;
            }
            else if (id == -9)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.2f);
                flag = true;
                this.damage = 15;
                this.defense = 7;
                this.life = 45;
                this.color = new Color(255, 255, 0, 100);
                this.value = 10f;
            }
            else if (id == -10)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = true;
                this.damage = 18;
                this.defense = 6;
                this.life = 60;
                this.color = new Color(143, 215, 93, 100);
                this.value = 500f;
            }
            else if (id == -11)
            {
                float num2 = 0.85f;
                if (Main.remixWorld && !this.IsABestiaryIconDummy)
                {
                    num2 *= 1.3f;
                }
                this.SetDefaults_ForNetId(num, spawnparams, num2);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -12)
            {
                float num3 = 1.15f;
                if ((Main.remixWorld || Main.getGoodWorld) && !this.IsABestiaryIconDummy)
                {
                    num3 *= 1.3f;
                }
                this.SetDefaults_ForNetId(num, spawnparams, num3);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -13)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
            }
            else if (id == -14)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((double)((float)this.damage * this.scale) * 1.1);
                this.life = (int)((double)((float)this.life * this.scale) * 1.1);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots = 2f;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -15)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((double)((float)this.damage * this.scale) * 1.1);
                this.life = 400;
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots = 2f;
                this.knockBackResist *= 2f - this.scale;
                this.height = 44;
            }
            else if (id == -16)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.85f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -17)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.2f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -18)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.8f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -19)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -20)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -21)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.2f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -22)
            {
                float num4 = 0.85f;
                if (Main.remixWorld && !this.IsABestiaryIconDummy)
                {
                    num4 *= 1.3f;
                }
                this.SetDefaults_ForNetId(num, spawnparams, num4);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -23)
            {
                float num5 = 1.15f;
                if (Main.remixWorld && !this.IsABestiaryIconDummy)
                {
                    num5 *= 1.3f;
                }
                this.SetDefaults_ForNetId(num, spawnparams, num5);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -24)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.85f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -25)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -26)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -27)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -28)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.85f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -29)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -30)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.93f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -31)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.13f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -32)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.89f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -33)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.11f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -34)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.87f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -35)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.13f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -36)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.92f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -37)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.08f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -38)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -39)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -40)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -41)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.85f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -42)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -43)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -44)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.87f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -45)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.05f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -46)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -47)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -48)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.93f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -49)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.07f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -50)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.87f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -51)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.13f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -52)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.85f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -53)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -54)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.9f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -55)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -56)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.85f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -57)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.25f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -58)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.8f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -59)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.15f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -60)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.92f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -61)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.1f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -62)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.78f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -63)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 1.16f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else if (id == -64)
            {
                this.SetDefaults_ForNetId(num, spawnparams, 0.87f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            else
            {
                if (id != -65)
                {
                    return;
                }
                this.SetDefaults_ForNetId(num, spawnparams, 1.21f);
                flag = false;
                this.defense = (int)((float)this.defense * this.scale);
                this.damage = (int)((float)this.damage * this.scale);
                this.life = (int)((float)this.life * this.scale);
                this.value = (float)((int)(this.value * this.scale));
                this.npcSlots *= this.scale;
                this.knockBackResist *= 2f - this.scale;
            }
            this.netID = id;
            this.lifeMax = this.life;
            this.defDamage = this.damage;
            this.defDefense = this.defense;
            this.defLifeMax = this.lifeMax;
            if (flag)
            {
                this.ScaleStats(spawnparams.playerCountForMultiplayerDifficultyOverride, spawnparams.difficultyOverride);
                this.life = this.lifeMax;
            }
        }
References Microsoft.Xna.Framework.Graphics.Color, Terraria.NPC.damage, Terraria.NPC.defense, Terraria.ID.NPCID.FromNetId(), Terraria.Main.getGoodWorld, int, Terraria.NPC.IsABestiaryIconDummy, Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.remixWorld, Terraria.NPC.scale, Terraria.NPC.ScaleStats(), Terraria.NPC.SetDefaults(), and Terraria.NPC.SetDefaults_ForNetId().
Referenced by Terraria.NPC.SetDefaults().