Terraria Decompiled: Terraria.NPC.AI_127_Pal
AI_127_Pal()
void Terraria.NPC.AI_127_Pal () inline private
Definition at line 39645 of file NPC.cs.
        {
            this.TargetClosest(true);
            this.spriteDirection = -this.direction;
            if (Main.netMode != 1)
            {
                if (this.localAI[0] == 0f)
                {
                    this.localAI[0] = 1f;
                    Point[] array = null;
                    if (!CultistRitual.CheckFloor2(base.Center, out array))
                    {
                        this.life = 0;
                        this.HitEffect(0, 10.0);
                        this.active = false;
                        return;
                    }
                    for (int i = 0; i < 2; i++)
                    {
                        int num = 111;
                        int num2 = NPC.NewNPC(this.GetSpawnSourceForNPCFromNPCAI(), array[i].X * 16 + 8, array[i].Y * 16 - 48, num, 0, 0f, 0f, 0f, 0f, 255);
                        this.ai[1 + i] = (float)(num2 + 1);
                        Main.npc[num2].ai[3] = (float)(-(float)(this.whoAmI + 1));
                        Main.npc[num2].netUpdate = true;
                    }
                    this.netUpdate = true;
                }
                if (this.ai[0] == 0f)
                {
                    bool flag = this.AI_127_Pal_TryUnpackNPC(this.ai[1]) != null;
                    NPC npc = this.AI_127_Pal_TryUnpackNPC(this.ai[2]);
                    if (!flag && npc == null)
                    {
                        this.ai[0] = 1f;
                        this.netUpdate = true;
                    }
                    else
                    {
                        this.timeLeft = NPC.activeTime;
                    }
                }
                if (this.ai[0] == 1f)
                {
                    Player player = Main.player[this.target];
                    if (base.Distance(player.Center) < 100f)
                    {
                        this.ai[0] = 2f;
                        this.ai[1] = 0f;
                        this.ai[2] = 0f;
                        this.netUpdate = true;
                    }
                }
            }
            if (this.ai[0] == 0f && this.soundDelay == 0)
            {
                this.soundDelay = Main.rand.Next(600, 1800);
                if (this.type == 695)
                {
                    SoundEngine.PlaySound(SoundID.PalCattivaPain, base.Center, 0f, 1f);
                }
                if (this.type == 696)
                {
                    SoundEngine.PlaySound(SoundID.PalFoxparksPain, base.Center, 0f, 1f);
                }
            }
            if (this.ai[0] == 2f)
            {
                if (this.soundDelay != -2)
                {
                    this.soundDelay = -2;
                    if (this.type == 695)
                    {
                        SoundEngine.PlaySound(SoundID.PalCattivaJoy, base.Center, 0f, 1f);
                    }
                    if (this.type == 696)
                    {
                        SoundEngine.PlaySound(SoundID.PalFoxparksJoy, base.Center, 0f, 1f);
                    }
                }
                float[] array2 = this.ai;
                int num3 = 1;
                float num4 = array2[num3] + 1f;
                array2[num3] = num4;
                if (num4 >= 120f)
                {
                    if (Main.netMode != 1)
                    {
                        this.AI_127_Pal_GiveRewerd();
                    }
                    this.life = 0;
                    this.active = false;
                    return;
                }
            }
            if (this.type == 696)
            {
                Lighting.AddLight(base.Center, 0.5f, 0.3f, 0.1f);
            }
            this.velocity.X = this.velocity.X * 0.93f;
            if ((double)this.velocity.X > -0.1 && (double)this.velocity.X < 0.1)
            {
                this.velocity.X = 0f;
            }
        }
References Terraria.NPC.activeTime, Terraria.Lighting.AddLight(), Terraria.NPC.ai, Terraria.NPC.AI_127_Pal_GiveRewerd(), Terraria.NPC.AI_127_Pal_TryUnpackNPC(), System.array, Terraria.Entity.Center, Terraria.GameContent.Events.CultistRitual.CheckFloor2(), Terraria.Entity.direction, Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), Terraria.NPC.HitEffect(), Terraria.NPC.localAI, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.ID.SoundID.PalCattivaJoy, Terraria.ID.SoundID.PalCattivaPain, Terraria.ID.SoundID.PalFoxparksJoy, Terraria.ID.SoundID.PalFoxparksPain, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.NPC.soundDelay, Terraria.NPC.target, Terraria.NPC.TargetClosest(), Terraria.NPC.type, Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, System.X, and System.Y.
Referenced by Terraria.NPC.AI().