Terraria Decompiled: Terraria.NPC.setFireFlyChance
setFireFlyChance()
static void Terraria.NPC.setFireFlyChance () inline static
Definition at line 94476 of file NPC.cs.
        {
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
            }
            if (WorldGen.genRand.Next(9) == 0)
            {
                NPC.fireFlyChance = Main.rand.Next(5, 10);
                NPC.fireFlyFriendly = Main.rand.Next(1, 4);
                NPC.fireFlyMultiple = Main.rand.Next(3, 8);
            }
            else if (WorldGen.genRand.Next(3) == 0)
            {
                NPC.fireFlyChance = 999999;
                NPC.fireFlyFriendly = 999999;
                NPC.fireFlyMultiple = 999999;
            }
            else
            {
                NPC.fireFlyChance = Main.rand.Next(10, 60);
                NPC.fireFlyFriendly = Main.rand.Next(2, 15);
                NPC.fireFlyMultiple = Main.rand.Next(6, 30);
            }
            if (Main.rand.Next(3) == 0)
            {
                NPC.butterflyChance = 999999;
                NPC.stinkBugChance = Main.rand.Next(1, 14);
                if (WorldGen.genRand.Next(5) == 0)
                {
                    NPC.stinkBugChance = 999999;
                }
            }
            else
            {
                NPC.stinkBugChance = 999999;
                NPC.butterflyChance = Main.rand.Next(1, 21);
                if (WorldGen.genRand.Next(5) == 0)
                {
                    NPC.butterflyChance = 999999;
                }
            }
            if (Main.tenthAnniversaryWorld)
            {
                NPC.fireFlyChance = Math.Max(1, (int)((float)NPC.fireFlyChance * 0.5f));
                NPC.butterflyChance = Math.Max(1, (int)((float)NPC.butterflyChance * 0.5f));
            }
        }
References Terraria.NPC.butterflyChance, Terraria.NPC.fireFlyChance, Terraria.WorldGen.genRand, System.Math.Max(), Terraria.Utilities.UnifiedRandom.Next(), System.DateTime.Now, Terraria.Main.rand, Terraria.Main.tenthAnniversaryWorld, and System.DateTime.Ticks.
Referenced by Terraria.IO.WorldFile.LoadWorld(), and Terraria.Main.UpdateTime_StartNight().