Terraria Decompiled: Terraria.NPC.SetDefaults
SetDefaults()
void Terraria.NPC.SetDefaults (int Type, NPCSpawnParams spawnparams = default(NPCSpawnParams)) inline
Definition at line 2193 of file NPC.cs.
        {
            if (Main.getGoodWorld && !this.IsABestiaryIconDummy && spawnparams.sizeScaleOverride != null)
            {
                spawnparams.sizeScaleOverride = (spawnparams.sizeScaleOverride + spawnparams.sizeScaleOverride * spawnparams.sizeScaleOverride) / (float)2;
            }
            if (Type < 0)
            {
                this.SetDefaultsFromNetId(Type, spawnparams);
                return;
            }
            this.waterMovementSpeed = (this.lavaMovementSpeed = 0.5f);
            this.honeyMovementSpeed = 0.25f;
            this.altTexture = 0;
            this.townNpcVariationIndex = 0;
            this.nameOver = 0f;
            this.takenDamageMultiplier = 1f;
            this.rarity = 0;
            this.dontCountMe = false;
            this.releaseOwner = 255;
            this.catchItem = 0;
            this.needsUniqueInfoUpdate = true;
            this.netID = 0;
            this.netAlways = false;
            this.CanBeReplacedByOtherNPCs = false;
            this.statsAreScaledForThisManyPlayers = 0;
            this.difficulty = 1f;
            int num = 10;
            if (Type >= 0)
            {
                num = NPCID.Sets.TrailCacheLength[Type];
            }
            if (num != this.oldPos.Length)
            {
                Array.Resize<Vector2>(ref this.oldPos, num);
                Array.Resize<float>(ref this.oldRot, num);
            }
            for (int i = 0; i < this.oldPos.Length; i++)
            {
                this.oldRot[i] = 0f;
                this.oldPos[i].X = 0f;
                this.oldPos[i].Y = 0f;
            }
            for (int j = 0; j < BuffID.Count; j++)
            {
                this.buffImmune[j] = false;
            }
            this.setFrameSize = false;
            this.spawnNeedsSyncing = false;
            this.realLife = -1;
            this.lifeRegen = 0;
            this.lifeRegenExpectedLossPerSecond = -1;
            this.lifeRegenCount = 0;
            this.markedByScytheWhip = false;
            this.markedByEelWhip = false;
            this.poisoned = false;
            this.bleeding = false;
            this.tipsy = false;
            this.hemorrhage = false;
            this.soulDrain = false;
            this.venom = false;
            this.shadowFlame = false;
            this.canDisplayBuffs = true;
            this.onFire = false;
            this.midas = false;
            this.ichor = false;
            this.brokenArmor = false;
            this.onFrostBurn = false;
            this.onFrostBurn2 = false;
            this.shimmering = false;
            this.confused = false;
            this.loveStruck = false;
            this.dontTakeDamageFromHostiles = false;
            this.stinky = false;
            this.dryadWard = false;
            this.onFire2 = false;
            this.onFire3 = false;
            this.justHit = false;
            this.dontTakeDamage = false;
            this.catchableNPCTempImmunityCounter = 0;
            this.electricEelCounter = 0;
            this.npcSlots = 1f;
            this.lavaImmune = false;
            this.wetCount = 0;
            this.townNPC = false;
            this.homeless = false;
            this.homelessDespawn = false;
            this.homeTileX = -1;
            this.homeTileY = -1;
            this.housingCategory = 0;
            this.friendly = false;
            this.behindTiles = false;
            this.boss = false;
            this.noTileCollide = false;
            this.rotation = 0f;
            this.active = Type != 0;
            this.alpha = 0;
            this.color = default(Color);
            this.collideX = false;
            this.collideY = false;
            this.frameCounter = 0.0;
            this.netUpdate = true;
            this.netUpdatePendingSpamCooldown = false;
            this.netUpdatePendingFullSpamCooldown = false;
            this.knockBackResist = 1f;
            this.GivenName = "";
            this.noGravity = false;
            this.scale = 1f;
            this.HitSound = null;
            this.DeathSound = null;
            this.target = 255;
            this.oldTarget = this.target;
            this.targetRect = default(Rectangle);
            this.timeLeft = NPC.activeTime;
            this.type = Type;
            this.value = 0f;
            this.coldDamage = false;
            this.trapImmune = false;
            this.hide = false;
            this.immortal = false;
            this.chaseable = true;
            this.breath = 200;
            this.breathCounter = 0;
            this.reflectsProjectiles = false;
            this.canGhostHeal = true;
            this.javelined = false;
            this.tentacleSpiked = false;
            this.bloodButchered = false;
            this.daybreak = false;
            this.celled = false;
            this.dryadBane = false;
            this.betsysCurse = false;
            this.oiled = false;
            this.despawnEncouraged = false;
            this.damage = 0;
            for (int k = 0; k < NPC.maxAI; k++)
            {
                this.ai[k] = 0f;
            }
            for (int l = 0; l < NPC.maxAI; l++)
            {
                this.localAI[l] = 0f;
            }
            if (this.type == 1)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 7;
                this.defense = 2;
                this.lifeMax = 25;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 175;
                this.color = new Color(0, 80, 255, 100);
                this.value = 25f;
            }
            else if (this.type == 2)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 18;
                this.defense = 2;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 75f;
            }
            else if (this.type == 3)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 60f;
            }
            else if (this.type == 430)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 60f;
            }
            else if (this.type == 431)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 8;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 80f;
            }
            else if (this.type == 432)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 8;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 65f;
            }
            else if (this.type == 433)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 13;
                this.defense = 6;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.55f;
                this.value = 55f;
            }
            else if (this.type == 434)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 13;
                this.defense = 8;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 80f;
            }
            else if (this.type == 435)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 4;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.55f;
                this.value = 70f;
            }
            else if (this.type == 436)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 12;
                this.defense = 4;
                this.lifeMax = 38;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 65f;
            }
            else if (this.type == 4)
            {
                this.width = 100;
                this.height = 110;
                this.aiStyle = 4;
                this.damage = 15;
                this.defense = 12;
                this.lifeMax = 2800;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.value = 30000f;
                this.npcSlots = 5f;
            }
            else if (this.type == 5)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 5;
                this.damage = 12;
                this.defense = 0;
                this.lifeMax = 8;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
            }
            else if (this.type == 6)
            {
                this.npcSlots = 1f;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 5;
                this.damage = 22;
                this.defense = 8;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.knockBackResist = 0.5f;
                this.value = 90f;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.3f;
                    }
                    this.damage = (int)((float)this.damage * this.scale);
                    this.defense = (int)((float)this.defense * this.scale);
                    this.lifeMax = (int)((float)this.lifeMax * this.scale);
                    this.value = (float)((int)(this.value * this.scale));
                }
                else if (Main.getGoodWorld && !this.IsABestiaryIconDummy)
                {
                    this.scale *= 1.3f;
                }
            }
            else if (this.type == 7)
            {
                this.npcSlots = 3.5f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.damage = 31;
                this.defense = 2;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 140f;
                this.netAlways = true;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.3f;
                    }
                    this.damage = (int)((float)this.damage * this.scale);
                    this.defense = (int)((float)this.defense * this.scale);
                    this.lifeMax = (int)((float)this.lifeMax * this.scale);
                    this.value = (float)((int)(this.value * this.scale));
                }
            }
            else if (this.type == 8)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 16;
                this.defense = 6;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 140f;
                this.dontCountMe = true;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.3f;
                    }
                    this.damage = (int)((float)this.damage * this.scale);
                    this.defense = (int)((float)this.defense * this.scale);
                    this.lifeMax = (int)((float)this.lifeMax * this.scale);
                    this.value = (float)((int)(this.value * this.scale));
                }
            }
            else if (this.type == 9)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 13;
                this.defense = 10;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 140f;
                this.dontCountMe = true;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.3f;
                    }
                    this.damage = (int)((float)this.damage * this.scale);
                    this.defense = (int)((float)this.defense * this.scale);
                    this.lifeMax = (int)((float)this.lifeMax * this.scale);
                    this.value = (float)((int)(this.value * this.scale));
                }
            }
            else if (this.type == 10)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 8;
                this.defense = 0;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 40f;
            }
            else if (this.type == 11)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 4;
                this.defense = 4;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 40f;
                this.dontCountMe = true;
            }
            else if (this.type == 12)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 4;
                this.defense = 6;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 40f;
                this.dontCountMe = true;
            }
            else if (this.type == 13)
            {
                this.npcSlots = 5f;
                this.width = 38;
                this.height = 38;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 22;
                this.defense = 2;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 800f;
                this.scale = 1f;
                this.alpha = 255;
            }
            else if (this.type == 14)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 13;
                this.defense = 4;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 800f;
                this.scale = 1f;
                this.dontCountMe = true;
                this.alpha = 255;
            }
            else if (this.type == 15)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 11;
                this.defense = 8;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 800f;
                this.scale = 1f;
                this.dontCountMe = true;
                this.alpha = 255;
            }
            else if (this.type == 16)
            {
                this.npcSlots = 2f;
                this.width = 36;
                this.height = 24;
                this.aiStyle = 1;
                this.damage = 20;
                this.defense = 7;
                this.lifeMax = 90;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 120;
                this.color = new Color(0, 0, 0, 50);
                this.value = 75f;
                this.scale = 1.25f;
                this.knockBackResist = 0.6f;
            }
            else if (this.type == 17)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 18)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 19)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 20)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 21)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 100f;
            }
            else if (this.type == 22)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 30;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 23)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 5;
                this.damage = 40;
                this.defense = 6;
                this.lifeMax = 26;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 80f;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 24)
            {
                this.npcSlots = 3f;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 30;
                this.defense = 16;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.lavaImmune = true;
                this.value = 350f;
            }
            else if (this.type == 25)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 9;
                this.damage = 30;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.alpha = 100;
            }
            else if (this.type == 31)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 26;
                this.defense = 8;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.8f;
                this.value = 130f;
            }
            else if (this.type == 32)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 20;
                this.defense = 2;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 140f;
                this.npcSlots = 2f;
            }
            else if (this.type == 33)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 9;
                this.damage = 20;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.alpha = 255;
                this.knockBackResist = 0f;
            }
            else if (this.type == 34)
            {
                this.width = 26;
                this.height = 28;
                this.aiStyle = 10;
                this.damage = 35;
                this.defense = 6;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 150f;
                this.knockBackResist = 0.2f;
                this.npcSlots = 0.75f;
            }
            else if (this.type == 35)
            {
                this.width = 80;
                this.height = 102;
                this.aiStyle = 11;
                this.damage = 32;
                this.defense = 10;
                this.lifeMax = 4400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 50000f;
                this.knockBackResist = 0f;
                this.boss = true;
                this.npcSlots = 6f;
            }
            else if (this.type == 36)
            {
                this.width = 52;
                this.height = 52;
                this.aiStyle = 12;
                this.damage = 20;
                this.defense = 14;
                this.lifeMax = 600;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
            }
            else if (this.type == 37)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 38)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 39)
            {
                this.npcSlots = 6f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 36;
                this.defense = 12;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath5;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 1200f;
            }
            else if (this.type == 40)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 20;
                this.defense = 18;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath5;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 1200f;
                this.dontCountMe = true;
            }
            else if (this.type == 41)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 16;
                this.defense = 18;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath5;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 1200f;
                this.dontCountMe = true;
            }
            else if (this.type == 42)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 26;
                this.defense = 12;
                this.lifeMax = 48;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.5f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 200f;
                this.noGravity = true;
            }
            else if (this.type == 43)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 13;
                this.damage = 34;
                this.defense = 10;
                this.lifeMax = 110;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 350f;
            }
            else if (this.type == 44)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 22;
                this.defense = 9;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 250f;
                this.rarity = 1;
            }
            else if (this.type == 45)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 20;
                this.defense = 4;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 5000f;
                this.rarity = 4;
            }
            else if (this.type == 46 || this.type == 303 || this.type == 337 || this.type == 540)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2019;
            }
            else if (this.type == 47)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 4;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 48)
            {
                this.width = 24;
                this.height = 34;
                this.aiStyle = 14;
                this.damage = 25;
                this.defense = 8;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 300f;
            }
            else if (this.type == 49)
            {
                this.npcSlots = 0.5f;
                this.width = 22;
                this.height = 18;
                this.aiStyle = 14;
                this.damage = 13;
                this.defense = 2;
                this.lifeMax = 16;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 90f;
            }
            else if (this.type == 50)
            {
                this.boss = true;
                this.width = 98;
                this.height = 92;
                this.aiStyle = 15;
                this.damage = 40;
                this.defense = 10;
                this.lifeMax = 2000;
                this.knockBackResist = 0f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 30;
                this.value = 10000f;
                this.scale = 1.25f;
                this.npcSlots = 5f;
            }
            else if (this.type == 51)
            {
                this.npcSlots = 0.5f;
                this.width = 22;
                this.height = 18;
                this.aiStyle = 14;
                this.damage = 20;
                this.defense = 4;
                this.lifeMax = 34;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 80f;
            }
            else if (this.type == 52)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 1000f;
                this.rarity = 2;
            }
            else if (this.type == 53)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 8;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 1000f;
                this.rarity = 2;
            }
            else if (this.type == 54)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 55)
            {
                this.noGravity = true;
                this.width = 20;
                this.height = 18;
                this.aiStyle = 16;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.catchItem = 261;
            }
            else if (this.type == 56)
            {
                this.noTileCollide = true;
                this.noGravity = true;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 13;
                this.damage = 25;
                this.defense = 10;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 90f;
            }
            else if (this.type == 57)
            {
                this.noGravity = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 16;
                this.damage = 30;
                this.defense = 6;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 58)
            {
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 16;
                this.damage = 25;
                this.defense = 2;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 50f;
            }
            else if (this.type == 59)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 15;
                this.defense = 10;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.scale = 1.1f;
                this.alpha = 50;
                this.lavaImmune = true;
                this.value = 120f;
                if (Main.remixWorld)
                {
                    this.damage = 7;
                    this.defense = 2;
                    this.lifeMax = 25;
                    this.value = 25f;
                }
            }
            else if (this.type == 60)
            {
                this.npcSlots = 0.5f;
                this.width = 22;
                this.height = 18;
                this.aiStyle = 14;
                this.damage = 35;
                this.defense = 8;
                this.lifeMax = 46;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 120f;
                this.scale = 1.1f;
                this.lavaImmune = true;
            }
            else if (this.type == 61)
            {
                this.width = 36;
                this.height = 36;
                this.aiStyle = 17;
                this.damage = 15;
                this.defense = 4;
                this.lifeMax = 40;
                this.knockBackResist = 0.8f;
                this.HitSound = SoundID.NPCHit28;
                this.DeathSound = SoundID.NPCDeath31;
                this.value = 60f;
            }
            else if (this.type == 62)
            {
                this.npcSlots = 2f;
                this.width = 28;
                this.height = 48;
                this.aiStyle = 14;
                this.damage = 32;
                this.defense = 8;
                this.lifeMax = 120;
                this.HitSound = SoundID.NPCHit21;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath24;
                this.value = 300f;
                this.lavaImmune = true;
            }
            else if (this.type == 63)
            {
                this.noGravity = true;
                this.width = 26;
                this.height = 26;
                this.aiStyle = 18;
                this.damage = 25;
                this.defense = 4;
                this.lifeMax = 34;
                this.HitSound = SoundID.NPCHit25;
                this.DeathSound = SoundID.NPCDeath28;
                this.value = 100f;
                this.alpha = 20;
            }
            else if (this.type == 64)
            {
                this.noGravity = true;
                this.width = 26;
                this.height = 26;
                this.aiStyle = 18;
                this.damage = 30;
                this.defense = 6;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit25;
                this.DeathSound = SoundID.NPCDeath28;
                this.value = 100f;
                this.alpha = 20;
            }
            else if (this.type == 65)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 24;
                this.aiStyle = 16;
                this.damage = 40;
                this.defense = 2;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 400f;
                this.knockBackResist = 0.7f;
            }
            else if (this.type == 66)
            {
                this.npcSlots = 2f;
                this.width = 28;
                this.height = 48;
                this.aiStyle = 14;
                this.damage = 32;
                this.defense = 8;
                this.lifeMax = 140;
                this.HitSound = SoundID.NPCHit21;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath24;
                this.value = 1000f;
                this.lavaImmune = true;
                this.rarity = 1;
            }
            else if (this.type == 67)
            {
                this.width = 28;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 60f;
            }
            else if (this.type == 68)
            {
                this.width = 80;
                this.height = 102;
                this.aiStyle = 11;
                this.damage = 9999;
                this.defense = 9999;
                this.lifeMax = 9999;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
            }
            else if (this.type == 69)
            {
                this.width = 24;
                this.height = 24;
                this.aiStyle = 19;
                this.damage = 10;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit31;
                this.DeathSound = SoundID.NPCDeath34;
                this.knockBackResist = 0f;
                this.value = 60f;
                this.behindTiles = true;
            }
            else if (this.type == 70)
            {
                this.npcSlots = 0.3f;
                this.width = 34;
                this.height = 34;
                this.aiStyle = 20;
                this.damage = 32;
                this.defense = 100;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.dontTakeDamage = true;
                this.scale = 1.5f;
            }
            else if (this.type == 71)
            {
                this.npcSlots = 2f;
                this.width = 36;
                this.height = 24;
                this.aiStyle = 1;
                this.damage = 30;
                this.defense = 7;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 60;
                this.value = 150f;
                this.scale = 1.25f;
                this.knockBackResist = 0.6f;
                this.rarity = 1;
            }
            else if (this.type == 72)
            {
                this.npcSlots = 0.3f;
                this.width = 34;
                this.height = 34;
                this.aiStyle = 21;
                this.damage = 24;
                this.defense = 100;
                this.lifeMax = 100;
                this.alpha = 100;
                this.behindTiles = true;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.dontTakeDamage = true;
                this.scale = 1.2f;
            }
            else if (this.type == 73)
            {
                this.scale = 0.95f;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 6;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.7f;
                this.value = 200f;
                this.rarity = 1;
            }
            else if (this.type == 74 || this.type == 297 || this.type == 298)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                if (this.type == 74)
                {
                    this.catchItem = 2015;
                }
                if (this.type == 297)
                {
                    this.catchItem = 2016;
                }
                if (this.type == 298)
                {
                    this.catchItem = 2017;
                }
                this.npcSlots = 0.4f;
            }
            else if (this.type == 75)
            {
                this.noGravity = true;
                this.width = 20;
                this.height = 20;
                this.aiStyle = 22;
                this.damage = 55;
                this.defense = 20;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit5;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath7;
                this.value = 350f;
            }
            else if (this.type == 77)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 40;
                this.defense = 28;
                this.lifeMax = 260;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 400f;
            }
            else if (this.type == 78)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 16;
                this.lifeMax = 130;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.6f;
                this.value = 600f;
            }
            else if (this.type == 79)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 18;
                this.lifeMax = 180;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.value = 700f;
            }
            else if (this.type == 80)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 55;
                this.defense = 18;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.55f;
                this.value = 700f;
            }
            else if (this.type == 81)
            {
                this.width = 40;
                this.height = 30;
                this.aiStyle = 1;
                this.damage = 55;
                this.defense = 20;
                this.lifeMax = 170;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 55;
                this.value = 400f;
                this.scale = 1.1f;
            }
            else if (this.type == 82)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 24;
                this.height = 44;
                this.aiStyle = 22;
                this.damage = 65;
                this.defense = 16;
                this.lifeMax = 160;
                this.HitSound = SoundID.NPCHit54;
                this.DeathSound = SoundID.NPCDeath52;
                this.alpha = 100;
                this.value = 500f;
                this.knockBackResist = 0.7f;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.2f;
                    }
                    this.damage = (int)((float)this.damage * this.scale);
                    this.defense = (int)((float)this.defense * this.scale);
                    this.lifeMax = (int)((float)this.lifeMax * this.scale);
                    this.value = (float)((int)(this.value * this.scale));
                }
            }
            else if (this.type == 83)
            {
                this.width = 40;
                this.height = 40;
                this.aiStyle = 23;
                this.damage = 80;
                this.defense = 18;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 1000f;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 84)
            {
                this.width = 40;
                this.height = 40;
                this.aiStyle = 23;
                this.damage = 80;
                this.defense = 18;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 1000f;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 85)
            {
                this.width = 24;
                this.height = 24;
                this.aiStyle = 25;
                this.damage = 80;
                this.defense = 30;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 100000f;
                this.knockBackResist = 0.3f;
                this.rarity = 4;
                if (!Main.hardMode)
                {
                    this.damage = 30;
                    this.defense = 12;
                    this.lifeMax = 300;
                    this.value = (float)Item.buyPrice(0, 2, 0, 0);
                }
            }
            else if (this.type == 86)
            {
                this.width = 46;
                this.height = 42;
                this.aiStyle = 26;
                this.damage = 65;
                this.defense = 30;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit12;
                this.DeathSound = SoundID.NPCDeath18;
                this.knockBackResist = 0.3f;
                this.value = 1000f;
            }
            else if (this.type == 87)
            {
                this.noTileCollide = true;
                this.npcSlots = 5f;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 80;
                this.defense = 10;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath8;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.scale = 1f;
            }
            else if (this.type == 88)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath8;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.scale = 1f;
                this.dontCountMe = true;
            }
            else if (this.type == 89)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath8;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 2000f;
                this.scale = 1f;
                this.dontCountMe = true;
            }
            else if (this.type == 90)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath8;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.scale = 1f;
                this.dontCountMe = true;
            }
            else if (this.type == 91)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath8;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.scale = 1f;
                this.dontCountMe = true;
            }
            else if (this.type == 92)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath8;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.scale = 1f;
                this.dontCountMe = true;
            }
            else if (this.type == 93)
            {
                this.npcSlots = 0.5f;
                this.width = 26;
                this.height = 20;
                this.aiStyle = 14;
                this.damage = 45;
                this.defense = 16;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.75f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 400f;
            }
            else if (this.type == 94)
            {
                this.npcSlots = 1f;
                this.width = 44;
                this.height = 44;
                this.aiStyle = 5;
                this.damage = 60;
                this.defense = 32;
                this.lifeMax = 230;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.knockBackResist = 0.55f;
                this.value = 500f;
            }
            else if (this.type == 95)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 45;
                this.defense = 10;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.scale = 0.9f;
                this.value = 300f;
            }
            else if (this.type == 96)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 28;
                this.defense = 20;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.scale = 0.9f;
                this.value = 300f;
                this.dontCountMe = true;
            }
            else if (this.type == 97)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 26;
                this.defense = 30;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.scale = 0.9f;
                this.value = 300f;
                this.dontCountMe = true;
            }
            else if (this.type == 98)
            {
                this.npcSlots = 3.5f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 70;
                this.defense = 36;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 700f;
            }
            else if (this.type == 99)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 55;
                this.defense = 40;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 700f;
                this.dontCountMe = true;
            }
            else if (this.type == 100)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 40;
                this.defense = 44;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 700f;
                this.dontCountMe = true;
            }
            else if (this.type == 101)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.behindTiles = true;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 13;
                this.damage = 70;
                this.defense = 30;
                this.lifeMax = 320;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.2f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 600f;
            }
            else if (this.type == 102)
            {
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 16;
                this.damage = 80;
                this.defense = 22;
                this.lifeMax = 90;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 103)
            {
                this.noGravity = true;
                this.width = 26;
                this.height = 26;
                this.aiStyle = 18;
                this.damage = 80;
                this.defense = 30;
                this.lifeMax = 120;
                this.HitSound = SoundID.NPCHit25;
                this.DeathSound = SoundID.NPCDeath28;
                this.value = 800f;
                this.alpha = 20;
            }
            else if (this.type == 104)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 38;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit6;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
            }
            else if (this.type == 105)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 34;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.rarity = 1;
            }
            else if (this.type == 106)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.rarity = 1;
            }
            else if (this.type == 107)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 108)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 109)
            {
                this.width = 34;
                this.height = 78;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 25;
                this.lifeMax = 800;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.2f;
                this.value = 10000f;
                this.rarity = 1;
            }
            else if (this.type == 110)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 45;
                this.defense = 14;
                this.lifeMax = 210;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.55f;
                this.value = 400f;
            }
            else if (this.type == 112)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 9;
                this.damage = 65;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = null;
                this.DeathSound = SoundID.NPCDeath9;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.scale = 0.9f;
                this.alpha = 80;
            }
            else if (this.type == 113)
            {
                this.npcSlots = 10f;
                this.width = 100;
                this.height = 100;
                this.aiStyle = 27;
                this.damage = 50;
                this.defense = 12;
                this.lifeMax = 8000;
                this.HitSound = SoundID.NPCHit8;
                this.DeathSound = SoundID.NPCDeath10;
                this.noGravity = true;
                this.noTileCollide = true;
                this.behindTiles = true;
                this.knockBackResist = 0f;
                this.scale = 1.2f;
                this.boss = true;
                this.value = 80000f;
            }
            else if (this.type == 114)
            {
                this.width = 100;
                this.height = 100;
                this.aiStyle = 28;
                this.damage = 50;
                this.defense = 0;
                this.lifeMax = 8000;
                this.HitSound = SoundID.NPCHit8;
                this.DeathSound = SoundID.NPCDeath10;
                this.noGravity = true;
                this.noTileCollide = true;
                this.behindTiles = true;
                this.knockBackResist = 0f;
                this.scale = 1.2f;
                this.value = 80000f;
            }
            else if (this.type == 115)
            {
                this.width = 30;
                this.height = 30;
                this.aiStyle = 29;
                this.damage = 30;
                this.defense = 10;
                this.lifeMax = 240;
                this.HitSound = SoundID.NPCHit9;
                this.DeathSound = SoundID.NPCDeath11;
                this.noGravity = true;
                this.behindTiles = true;
                this.noTileCollide = true;
                this.knockBackResist = 1.1f;
            }
            else if (this.type == 116)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 30;
                this.defense = 6;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit9;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath12;
            }
            else if (this.type == 117)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 26;
                this.defense = 2;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit9;
                this.DeathSound = SoundID.NPCDeath12;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
            }
            else if (this.type == 118)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 22;
                this.defense = 6;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit9;
                this.DeathSound = SoundID.NPCDeath12;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
            }
            else if (this.type == 119)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 18;
                this.defense = 10;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit9;
                this.DeathSound = SoundID.NPCDeath12;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
            }
            else if (this.type == 120)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 40;
                this.defense = 30;
                this.lifeMax = 370;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.4f;
                this.value = 600f;
            }
            else if (this.type == 121)
            {
                this.width = 40;
                this.height = 30;
                this.aiStyle = 14;
                this.damage = 45;
                this.defense = 20;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.alpha = 55;
                this.knockBackResist = 0.8f;
                this.scale = 1.1f;
            }
            else if (this.type == 122)
            {
                this.noGravity = true;
                this.width = 20;
                this.height = 20;
                this.aiStyle = 22;
                this.damage = 60;
                this.defense = 22;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 600f;
            }
            else if (this.type == 123)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 34;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.scale = 0.9f;
                this.rarity = 1;
            }
            else if (this.type == 124)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 125)
            {
                this.width = 100;
                this.height = 110;
                this.aiStyle = 30;
                this.defense = 10;
                this.damage = 45;
                this.lifeMax = 20000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath14;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.value = 120000f;
                this.npcSlots = 5f;
            }
            else if (this.type == 126)
            {
                this.width = 100;
                this.height = 110;
                this.aiStyle = 31;
                this.defense = 10;
                this.damage = 50;
                this.lifeMax = 23000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath14;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.value = 120000f;
                this.npcSlots = 5f;
            }
            else if (this.type == 127)
            {
                this.width = 80;
                this.height = 102;
                this.aiStyle = 32;
                this.damage = 47;
                this.defense = 24;
                this.lifeMax = 28000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 120000f;
                this.knockBackResist = 0f;
                this.boss = true;
                this.npcSlots = 6f;
            }
            else if (this.type == 128)
            {
                this.width = 52;
                this.height = 52;
                this.aiStyle = 35;
                this.damage = 30;
                this.defense = 23;
                this.lifeMax = 7000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.netAlways = true;
            }
            else if (this.type == 129)
            {
                this.width = 52;
                this.height = 52;
                this.aiStyle = 33;
                this.damage = 56;
                this.defense = 38;
                this.lifeMax = 9000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.netAlways = true;
            }
            else if (this.type == 130)
            {
                this.width = 52;
                this.height = 52;
                this.aiStyle = 34;
                this.damage = 52;
                this.defense = 34;
                this.lifeMax = 9000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.netAlways = true;
            }
            else if (this.type == 131)
            {
                this.width = 52;
                this.height = 52;
                this.aiStyle = 36;
                this.damage = 29;
                this.defense = 20;
                this.lifeMax = 6000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.netAlways = true;
            }
            else if (this.type == 132)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 15;
                this.defense = 5;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 65f;
            }
            else if (this.type == 133)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 134)
            {
                this.npcSlots = 5f;
                this.width = 38;
                this.height = 38;
                this.aiStyle = 37;
                this.defense = 0;
                this.damage = 70;
                this.lifeMax = 80000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 120000f;
                this.scale = 1.25f;
                this.boss = true;
                this.netAlways = true;
                this.alpha = 255;
            }
            else if (this.type == 135)
            {
                this.npcSlots = 5f;
                this.width = 38;
                this.height = 38;
                this.aiStyle = 37;
                this.damage = 55;
                this.defense = 30;
                this.lifeMax = 80000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.netAlways = true;
                this.scale = 1.25f;
                this.dontCountMe = true;
                this.alpha = 255;
            }
            else if (this.type == 136)
            {
                this.npcSlots = 5f;
                this.width = 38;
                this.height = 38;
                this.aiStyle = 37;
                this.damage = 40;
                this.defense = 35;
                this.lifeMax = 80000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.scale = 1.25f;
                this.netAlways = true;
                this.dontCountMe = true;
                this.alpha = 255;
            }
            else if (this.type == 139)
            {
                this.npcSlots = 1f;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 5;
                this.damage = 50;
                this.defense = 20;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.noGravity = true;
                this.knockBackResist = 0.8f;
                this.noTileCollide = true;
            }
            else if (this.type == 137)
            {
                this.width = 26;
                this.height = 20;
                this.aiStyle = 14;
                this.damage = 75;
                this.defense = 30;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.75f;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 500f;
            }
            else if (this.type == 138)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 70;
                this.defense = 30;
                this.lifeMax = 180;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.alpha = 100;
                this.value = 400f;
                this.knockBackResist = 0.85f;
                this.scale = 1.05f;
            }
            else if (this.type == 140)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 55;
                this.defense = 28;
                this.lifeMax = 260;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.4f;
                this.value = 400f;
            }
            else if (this.type == 141)
            {
                this.width = 34;
                this.height = 28;
                this.aiStyle = 1;
                this.damage = 50;
                this.defense = 18;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 55;
                this.value = 400f;
                this.scale = 1.1f;
                this.knockBackResist = 0.8f;
            }
            else if (this.type == 142)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 143)
            {
                this.width = 26;
                this.height = 40;
                this.aiStyle = 38;
                this.damage = 50;
                this.defense = 20;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath15;
                this.knockBackResist = 0.6f;
                this.value = 400f;
                this.coldDamage = true;
            }
            else if (this.type == 144)
            {
                this.width = 26;
                this.height = 40;
                this.aiStyle = 38;
                this.damage = 65;
                this.defense = 26;
                this.lifeMax = 240;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath15;
                this.knockBackResist = 0.6f;
                this.value = 400f;
                this.coldDamage = true;
            }
            else if (this.type == 145)
            {
                this.width = 26;
                this.height = 40;
                this.aiStyle = 38;
                this.damage = 55;
                this.defense = 22;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath15;
                this.knockBackResist = 0.6f;
                this.value = 400f;
                this.coldDamage = true;
            }
            else if (this.type == 147)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 8;
                this.defense = 4;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 50;
                this.value = 50f;
                this.coldDamage = true;
            }
            else if (this.type == 148)
            {
                this.width = 16;
                this.height = 34;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2205;
            }
            else if (this.type == 149)
            {
                this.width = 16;
                this.height = 34;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2205;
            }
            else if (this.type == 150)
            {
                this.npcSlots = 0.5f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 14;
                this.damage = 18;
                this.defense = 6;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 250f;
                this.coldDamage = true;
            }
            else if (this.type == 151)
            {
                this.npcSlots = 0.5f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 14;
                this.damage = 50;
                this.defense = 16;
                this.lifeMax = 160;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 400f;
                this.scale = 1.15f;
                this.lavaImmune = true;
            }
            else if (this.type == 152)
            {
                this.npcSlots = 0.5f;
                this.width = 38;
                this.height = 34;
                this.aiStyle = 14;
                this.damage = 80;
                this.defense = 24;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.65f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 400f;
            }
            else if (this.type == 153)
            {
                this.npcSlots = 2f;
                this.width = 46;
                this.height = 32;
                this.aiStyle = 39;
                this.damage = 80;
                this.defense = 30;
                this.lifeMax = 470;
                this.HitSound = SoundID.NPCHit24;
                this.knockBackResist = 0.3f;
                this.DeathSound = SoundID.NPCDeath27;
                this.value = 500f;
                this.noGravity = false;
            }
            else if (this.type == 154)
            {
                this.npcSlots = 1.5f;
                this.width = 46;
                this.height = 32;
                this.aiStyle = 39;
                this.damage = 55;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit24;
                this.knockBackResist = 0.3f;
                this.DeathSound = SoundID.NPCDeath27;
                this.value = 450f;
                this.noGravity = false;
                this.coldDamage = true;
            }
            else if (this.type == 155)
            {
                this.width = 46;
                this.height = 30;
                this.aiStyle = 26;
                this.damage = 65;
                this.defense = 30;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 1000f;
            }
            else if (this.type == 156)
            {
                this.npcSlots = 2f;
                this.width = 28;
                this.height = 48;
                this.aiStyle = 14;
                this.damage = 50;
                this.defense = 40;
                this.lifeMax = 600;
                this.HitSound = SoundID.NPCHit21;
                this.knockBackResist = 0.5f;
                this.DeathSound = SoundID.NPCDeath24;
                this.value = 1200f;
                this.lavaImmune = true;
            }
            else if (this.type == 157)
            {
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.width = 74;
                this.height = 20;
                this.aiStyle = 16;
                this.damage = 75;
                this.defense = 30;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 160)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 161)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 8;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 80f;
            }
            else if (this.type == 163)
            {
                this.width = 50;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 90;
                this.defense = 40;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit29;
                this.DeathSound = SoundID.NPCDeath32;
                this.knockBackResist = 0.25f;
                this.value = 500f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 238)
            {
                this.noGravity = true;
                this.width = 36;
                this.height = 36;
                this.aiStyle = 40;
                this.damage = 100;
                this.defense = 40;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit29;
                this.DeathSound = SoundID.NPCDeath32;
                this.knockBackResist = 0.25f;
                this.value = 500f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 164)
            {
                this.width = 50;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 30;
                this.defense = 10;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit29;
                this.DeathSound = SoundID.NPCDeath32;
                this.knockBackResist = 0.25f;
                this.value = 100f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 165)
            {
                this.noGravity = true;
                this.width = 36;
                this.height = 36;
                this.aiStyle = 40;
                this.damage = 30;
                this.defense = 10;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit29;
                this.DeathSound = SoundID.NPCDeath32;
                this.knockBackResist = 0.25f;
                this.value = 100f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 167)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 24;
                this.defense = 10;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 200f;
            }
            else if (this.type == 168)
            {
                this.width = 16;
                this.height = 34;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 4;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 169)
            {
                this.noGravity = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 22;
                this.damage = 55;
                this.defense = 20;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit5;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath7;
                this.value = 1500f;
                this.coldDamage = true;
            }
            else if (this.type == 170)
            {
                this.width = 44;
                this.height = 36;
                this.aiStyle = 2;
                this.damage = 70;
                this.defense = 16;
                this.lifeMax = 210;
                this.HitSound = SoundID.NPCHit27;
                this.DeathSound = SoundID.NPCDeath30;
                this.knockBackResist = 0.5f;
                this.value = 2000f;
            }
            else if (this.type == 171)
            {
                this.width = 44;
                this.height = 36;
                this.aiStyle = 2;
                this.damage = 70;
                this.defense = 16;
                this.lifeMax = 210;
                this.HitSound = SoundID.NPCHit27;
                this.DeathSound = SoundID.NPCDeath30;
                this.knockBackResist = 0.5f;
                this.value = 2000f;
            }
            else if (this.type == 172)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 200;
                this.defense = 30;
                this.lifeMax = 600;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = 5000f;
                this.rarity = 4;
            }
            else if (this.type == 173)
            {
                this.npcSlots = 1f;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 5;
                this.damage = 22;
                this.defense = 8;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.knockBackResist = 0.5f;
                this.value = 90f;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.3f;
                    }
                    this.damage = (int)((float)this.damage * this.scale);
                    this.defense = (int)((float)this.defense * this.scale);
                    this.lifeMax = (int)((float)this.lifeMax * this.scale);
                    this.value = (float)((int)(this.value * this.scale));
                }
            }
            else if (this.type == 174)
            {
                this.npcSlots = 1f;
                this.width = 52;
                this.height = 26;
                this.aiStyle = 41;
                this.damage = 65;
                this.defense = 26;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 450f;
            }
            else if (this.type == 175)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 13;
                this.damage = 100;
                this.defense = 30;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.25f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 650f;
            }
            else if (this.type == 176)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 70;
                this.defense = 22;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.5f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 600f;
                this.noGravity = true;
                this.npcSlots = 1.5f;
            }
            else if (this.type == 177)
            {
                this.npcSlots = 1f;
                this.width = 58;
                this.height = 44;
                this.aiStyle = 41;
                this.damage = 80;
                this.defense = 26;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit22;
                this.DeathSound = SoundID.NPCDeath25;
                this.knockBackResist = 0.5f;
                this.value = 500f;
            }
            else if (this.type == 178)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 179)
            {
                this.width = 40;
                this.height = 40;
                this.aiStyle = 23;
                this.damage = 80;
                this.defense = 18;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 1000f;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 180)
            {
                this.width = 44;
                this.height = 36;
                this.aiStyle = 2;
                this.damage = 70;
                this.defense = 16;
                this.lifeMax = 210;
                this.HitSound = SoundID.NPCHit27;
                this.DeathSound = SoundID.NPCDeath30;
                this.knockBackResist = 0.5f;
                this.value = 2000f;
            }
            else if (this.type == 181)
            {
                this.width = 18;
                this.height = 44;
                this.aiStyle = 3;
                this.damage = 25;
                this.defense = 10;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 200f;
                if (Main.remixWorld)
                {
                    if (!this.IsABestiaryIconDummy)
                    {
                        this.scale *= 1.1f;
                    }
                    this.damage = (int)((double)((float)this.damage * this.scale) * 1.2);
                    this.defense = (int)((double)((float)this.defense * this.scale) * 1.2);
                    this.lifeMax = (int)((double)((float)this.lifeMax * this.scale) * 1.2);
                    this.value = (float)((int)((double)(this.value * this.scale) * 1.2));
                }
            }
            else if (this.type == 182)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 24;
                this.height = 62;
                this.aiStyle = 22;
                this.damage = 65;
                this.defense = 18;
                this.lifeMax = 240;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.alpha = 100;
                this.value = 500f;
                this.knockBackResist = 0.7f;
            }
            else if (this.type == 183)
            {
                this.width = 40;
                this.height = 30;
                this.aiStyle = 1;
                this.damage = 60;
                this.defense = 26;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 55;
                this.value = 400f;
                this.scale = 1.1f;
            }
            else if (this.type == 184)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 12;
                this.defense = 8;
                this.lifeMax = 60;
                this.scale = 1.1f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 50;
                this.value = 200f;
                this.coldDamage = true;
            }
            else if (this.type == 185)
            {
                this.width = 28;
                this.height = 28;
                this.aiStyle = 3;
                this.damage = 26;
                this.defense = 12;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 1.1f;
                this.value = 200f;
                this.coldDamage = true;
            }
            else if (this.type == 186)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 8;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 65f;
            }
            else if (this.type == 187)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 13;
                this.defense = 6;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.55f;
                this.value = 55f;
            }
            else if (this.type == 188)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 13;
                this.defense = 8;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 80f;
            }
            else if (this.type == 189)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 4;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.55f;
                this.value = 70f;
            }
            else if (this.type == 190)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 18;
                this.defense = 4;
                this.lifeMax = 65;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.7f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 75f;
            }
            else if (this.type == 191)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 16;
                this.defense = 2;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.85f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 75f;
            }
            else if (this.type == 192)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 18;
                this.defense = 2;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 75f;
            }
            else if (this.type == 193)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 20;
                this.defense = 0;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 75f;
            }
            else if (this.type == 194)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 14;
                this.defense = 4;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 75f;
            }
            else if (this.type == 195)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 42;
                this.damage = 10;
                this.defense = 30;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.rarity = 2;
                this.value = (float)Item.buyPrice(0, 2, 0, 0);
            }
            else if (this.type == 196)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 35;
                this.defense = 16;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = (float)Item.buyPrice(0, 2, 0, 0);
                this.rarity = 2;
            }
            else if (this.type == 197)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 28;
                this.lifeMax = 280;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 500f;
            }
            else if (this.type == 198)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 38;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit26;
                this.DeathSound = SoundID.NPCDeath29;
                this.knockBackResist = 0.4f;
                this.value = 650f;
            }
            else if (this.type == 199)
            {
                this.width = 42;
                this.height = 30;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 30;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit26;
                this.DeathSound = SoundID.NPCDeath29;
                this.knockBackResist = 0f;
                this.value = 650f;
            }
            else if (this.type == 200)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 12;
                this.defense = 4;
                this.lifeMax = 38;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 65f;
            }
            else if (this.type == 201)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 12;
                this.lifeMax = 55;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 130f;
            }
            else if (this.type == 202)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 18;
                this.defense = 8;
                this.lifeMax = 65;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 120f;
            }
            else if (this.type == 203)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 22;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 110f;
            }
            else if (this.type == 204)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 28;
                this.defense = 8;
                this.lifeMax = 65;
                this.scale = 1.15f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 50;
                this.value = 300f;
            }
            else if (this.type == 205)
            {
                this.width = 40;
                this.height = 40;
                this.aiStyle = 5;
                this.damage = 70;
                this.defense = 28;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.4f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 600f;
                this.noGravity = true;
                this.rarity = 2;
            }
            else if (this.type == 206)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 30;
                this.lifeMax = 280;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.value = 500f;
                this.coldDamage = true;
            }
            else if (this.type == 207)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 208)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 209)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.HitSound = SoundID.NPCHit4;
                this.lifeMax = 500;
                this.defense = 30;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.25f;
            }
            else if (this.type == 210)
            {
                this.width = 12;
                this.height = 12;
                this.aiStyle = 5;
                this.damage = 20;
                this.defense = 5;
                this.lifeMax = 20;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.5f;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
            }
            else if (this.type == 211)
            {
                this.width = 8;
                this.height = 8;
                this.aiStyle = 5;
                this.damage = 15;
                this.defense = 2;
                this.lifeMax = 10;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.5f;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
            }
            else if (this.type == 212)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 35;
                this.defense = 17;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
                this.value = 700f;
            }
            else if (this.type == 213)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 22;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.2f;
                this.value = 1000f;
            }
            else if (this.type == 214)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 30;
                this.defense = 14;
                this.lifeMax = 225;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 1000f;
            }
            else if (this.type == 215)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 35;
                this.defense = 20;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.35f;
                this.value = 1500f;
            }
            else if (this.type == 216)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 30;
                this.lifeMax = 3000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.value = 50000f;
                this.rarity = 1;
            }
            else if (this.type == 217)
            {
                this.width = 28;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath16;
                this.value = 60f;
                this.rarity = 1;
            }
            else if (this.type == 218)
            {
                this.width = 28;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath16;
                this.value = 60f;
                this.rarity = 1;
            }
            else if (this.type == 219)
            {
                this.width = 28;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath16;
                this.value = 60f;
                this.rarity = 1;
            }
            else if (this.type == 220)
            {
                this.width = 28;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 60f;
                this.rarity = 2;
            }
            else if (this.type == 221)
            {
                this.noGravity = true;
                this.width = 26;
                this.height = 26;
                this.aiStyle = 18;
                this.damage = 20;
                this.defense = 2;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 100f;
                this.alpha = 20;
                this.rarity = 1;
            }
            else if (this.type == 222)
            {
                this.width = 66;
                this.height = 66;
                this.aiStyle = 43;
                this.damage = 30;
                this.defense = 8;
                this.lifeMax = 3400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath66;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.value = 50000f;
                this.npcSlots = 7f;
            }
            else if (this.type == 223)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 16;
                this.defense = 8;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 70f;
            }
            else if (this.type == 224)
            {
                this.width = 32;
                this.height = 18;
                this.aiStyle = 44;
                this.damage = 9;
                this.defense = 4;
                this.lifeMax = 20;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 300f;
            }
            if (this.type == 225)
            {
                this.width = 38;
                this.height = 26;
                this.aiStyle = 1;
                this.damage = 10;
                this.defense = 5;
                this.lifeMax = 35;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.75f;
                this.value = 200f;
            }
            else if (this.type == 226)
            {
                this.npcSlots = 0.5f;
                this.width = 34;
                this.height = 50;
                this.aiStyle = 14;
                this.damage = 85;
                this.defense = 28;
                this.lifeMax = 260;
                this.HitSound = SoundID.NPCHit23;
                this.knockBackResist = 0.65f;
                this.DeathSound = SoundID.NPCDeath26;
                this.value = 400f;
            }
            else if (this.type == 227)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 228)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 229)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 230)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 261;
            }
            else if (this.type == 231)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 22;
                this.defense = 16;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.3f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 200f;
                this.noGravity = true;
            }
            else if (this.type == 232)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 28;
                this.defense = 12;
                this.lifeMax = 42;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 200f;
                this.noGravity = true;
            }
            else if (this.type == 233)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 30;
                this.defense = 14;
                this.lifeMax = 38;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.45f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 200f;
                this.noGravity = true;
            }
            else if (this.type == 234)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 32;
                this.defense = 6;
                this.lifeMax = 42;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.55f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 200f;
                this.noGravity = true;
            }
            else if (this.type == 235)
            {
                this.width = 34;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 34;
                this.defense = 4;
                this.lifeMax = 38;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 200f;
                this.noGravity = true;
            }
            else if (this.type == 236)
            {
                this.width = 50;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.25f;
                this.value = 1000f;
                this.npcSlots = 0.75f;
            }
            else if (this.type == 237)
            {
                this.noGravity = true;
                this.width = 36;
                this.height = 36;
                this.aiStyle = 40;
                this.damage = 100;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.25f;
                this.value = 1000f;
                this.npcSlots = 0.75f;
            }
            else if (this.type == 239)
            {
                this.width = 50;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 30;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit20;
                this.DeathSound = SoundID.NPCDeath23;
                this.knockBackResist = 0.5f;
                this.value = 130f;
            }
            else if (this.type == 240)
            {
                this.noGravity = true;
                this.width = 36;
                this.height = 36;
                this.aiStyle = 40;
                this.damage = 30;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit20;
                this.DeathSound = SoundID.NPCDeath23;
                this.knockBackResist = 0.5f;
                this.value = 130f;
            }
            else if (this.type == 241)
            {
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 16;
                this.damage = 50;
                this.defense = 20;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit13;
                this.DeathSound = SoundID.NPCDeath19;
                this.value = 500f;
            }
            else if (this.type == 242)
            {
                this.noGravity = true;
                this.width = 26;
                this.height = 26;
                this.aiStyle = 18;
                this.damage = 75;
                this.defense = 20;
                this.lifeMax = 150;
                this.HitSound = SoundID.NPCHit13;
                this.DeathSound = SoundID.NPCDeath19;
                this.value = 800f;
                this.alpha = 20;
            }
            else if (this.type == 243)
            {
                this.width = 30;
                this.height = 114;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 32;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit5;
                this.DeathSound = SoundID.NPCDeath7;
                this.knockBackResist = 0.05f;
                this.value = (float)Item.buyPrice(0, 1, 50, 0);
                this.coldDamage = true;
                this.rarity = 2;
            }
            else if (this.type == 244)
            {
                this.width = 60;
                this.height = 42;
                this.aiStyle = 1;
                this.damage = 85;
                this.defense = 26;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 175;
                this.value = (float)Item.buyPrice(0, 0, 20, 0);
                this.knockBackResist = 0.3f;
                this.rarity = 1;
            }
            else if (this.type == 245)
            {
                this.width = 140;
                this.height = 140;
                this.aiStyle = 45;
                this.damage = 72;
                this.defense = 26;
                this.lifeMax = 15000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.knockBackResist = 0f;
                this.value = (float)Item.buyPrice(0, 15, 0, 0);
                this.alpha = 255;
                this.boss = true;
                this.npcSlots = 5f;
            }
            else if (this.type == 246)
            {
                this.noGravity = true;
                this.width = 70;
                this.height = 70;
                this.aiStyle = 46;
                this.damage = 64;
                this.defense = 20;
                this.lifeMax = 25000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = null;
                this.knockBackResist = 0f;
                this.alpha = 255;
            }
            else if (this.type == 247 || this.type == 248)
            {
                this.noGravity = true;
                this.width = 40;
                this.height = 30;
                this.aiStyle = 47;
                this.damage = 59;
                this.defense = 28;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.alpha = 255;
                this.knockBackResist = 0f;
            }
            else if (this.type == 249)
            {
                this.noGravity = true;
                this.width = 70;
                this.height = 70;
                this.aiStyle = 48;
                this.damage = 80;
                this.defense = 32;
                this.lifeMax = 16000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.knockBackResist = 0f;
                this.dontTakeDamage = true;
            }
            else if (this.type == 250)
            {
                this.width = 34;
                this.height = 26;
                this.aiStyle = 49;
                this.damage = 50;
                this.defense = 24;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit30;
                this.DeathSound = SoundID.NPCDeath33;
                this.knockBackResist = 0.3f;
                this.value = 300f;
            }
            else if (this.type == 251)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 30;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = (float)Item.buyPrice(0, 0, 50, 0);
                this.rarity = 2;
            }
            else if (this.type == 252)
            {
                this.noGravity = true;
                this.npcSlots = 0.5f;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 5;
                this.damage = 80;
                this.defense = 12;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit46;
                this.knockBackResist = 0.7f;
                this.DeathSound = SoundID.NPCDeath48;
                this.value = 500f;
            }
            else if (this.type == 254)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 40;
                this.defense = 10;
                this.lifeMax = 180;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
            }
            else if (this.type == 255)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 38;
                this.defense = 16;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.3f;
                this.value = 1200f;
            }
            else if (this.type == 256)
            {
                this.noGravity = true;
                this.width = 26;
                this.height = 26;
                this.aiStyle = 18;
                this.damage = 90;
                this.defense = 20;
                this.lifeMax = 140;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 1200f;
                this.alpha = 20;
                this.npcSlots = 0.3f;
            }
            else if (this.type == 257)
            {
                this.width = 44;
                this.height = 34;
                this.aiStyle = 3;
                this.damage = 38;
                this.defense = 24;
                this.lifeMax = 230;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.3f;
                this.value = 1300f;
                this.npcSlots = 0.3f;
            }
            else if (this.type == 258)
            {
                this.width = 30;
                this.height = 24;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 16;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit45;
                this.DeathSound = SoundID.NPCDeath47;
                this.knockBackResist = 0.3f;
                this.value = 1500f;
                this.npcSlots = 0.3f;
            }
            else if (this.type == 259)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 20;
                this.height = 20;
                this.aiStyle = 13;
                this.damage = 24;
                this.defense = 4;
                this.lifeMax = 90;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 350f;
                this.npcSlots = 0.3f;
            }
            else if (this.type == 260)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 36;
                this.height = 36;
                this.aiStyle = 13;
                this.damage = 70;
                this.defense = 20;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 1250f;
                this.npcSlots = 0.3f;
            }
            else if (this.type == 261)
            {
                this.width = 12;
                this.height = 12;
                this.aiStyle = 50;
                this.damage = 80;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.npcSlots = 0f;
            }
            else if (this.type == 262)
            {
                this.noTileCollide = true;
                this.width = 86;
                this.height = 86;
                this.aiStyle = 51;
                this.damage = 50;
                this.defense = 14;
                this.lifeMax = 30000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.value = (float)Item.buyPrice(0, 15, 0, 0);
                this.noGravity = true;
                this.boss = true;
                this.npcSlots = 16f;
            }
            else if (this.type == 263)
            {
                this.noTileCollide = true;
                this.noGravity = true;
                this.width = 40;
                this.height = 40;
                this.aiStyle = 52;
                this.damage = 60;
                this.defense = 24;
                this.lifeMax = 4000;
                this.dontTakeDamage = true;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
            }
            else if (this.type == 264)
            {
                this.width = 24;
                this.height = 24;
                this.aiStyle = 53;
                this.damage = 60;
                this.defense = 20;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
            }
            else if (this.type == 265)
            {
                this.width = 18;
                this.height = 18;
                this.aiStyle = 50;
                this.damage = 70;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.npcSlots = 0f;
            }
            else if (this.type == 266)
            {
                this.dontTakeDamage = true;
                this.width = 160;
                this.height = 110;
                this.aiStyle = 54;
                this.damage = 30;
                this.defense = 14;
                this.lifeMax = 1250;
                this.HitSound = SoundID.NPCHit9;
                this.DeathSound = SoundID.NPCDeath11;
                this.knockBackResist = 0.45f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.value = 50000f;
                this.npcSlots = 6f;
            }
            else if (this.type == 267)
            {
                this.width = 30;
                this.height = 30;
                this.aiStyle = 55;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit9;
                this.DeathSound = SoundID.NPCDeath11;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.8f;
            }
            else if (this.type == 268)
            {
                this.noGravity = true;
                this.width = 28;
                this.height = 56;
                this.aiStyle = 22;
                this.damage = 55;
                this.defense = 20;
                this.lifeMax = 340;
                this.HitSound = SoundID.NPCHit13;
                this.DeathSound = SoundID.NPCDeath19;
                this.knockBackResist = 0.6f;
                this.value = 450f;
            }
            else if (this.type == 269)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 34;
                this.lifeMax = 550;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = 1000f;
            }
            else if (this.type == 270)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 55;
                this.defense = 50;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.2f;
                this.value = 1000f;
            }
            else if (this.type == 271)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 40;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.25f;
                this.value = 1000f;
            }
            else if (this.type == 272)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 75;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.35f;
                this.value = 1000f;
            }
            else if (this.type == 273)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 45;
                this.defense = 50;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.15f;
                this.value = 1000f;
            }
            else if (this.type == 274)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 65;
                this.defense = 34;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
            }
            else if (this.type == 275)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 45;
                this.defense = 50;
                this.lifeMax = 550;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.15f;
                this.value = 1000f;
            }
            else if (this.type == 276)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 85;
                this.defense = 54;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.2f;
                this.value = 1000f;
            }
            else if (this.type == 277)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 32;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
            }
            else if (this.type == 278)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 65;
                this.defense = 48;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = 1000f;
            }
            else if (this.type == 279)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 40;
                this.defense = 54;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.2f;
                this.value = 1000f;
            }
            else if (this.type == 280)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 75;
                this.defense = 34;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
            }
            else if (this.type == 281)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 1500f;
                this.npcSlots = 2f;
            }
            else if (this.type == 282)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 35;
                this.defense = 28;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 1500f;
                this.npcSlots = 2f;
            }
            else if (this.type == 283)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 50;
                this.defense = 18;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.55f;
                this.value = 1500f;
                this.npcSlots = 2f;
            }
            else if (this.type == 284)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 35;
                this.defense = 24;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 1500f;
                this.npcSlots = 2f;
            }
            else if (this.type == 285)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 50;
                this.defense = 12;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.7f;
                this.value = 1500f;
                this.npcSlots = 2f;
            }
            else if (this.type == 286)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 60;
                this.defense = 10;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.65f;
                this.value = 1500f;
                this.npcSlots = 2f;
            }
            else if (this.type == 287)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 90;
                this.defense = 42;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = 2000f;
                this.rarity = 1;
            }
            else if (this.type == 288)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 56;
                this.damage = 70;
                this.defense = 30;
                this.lifeMax = 200;
                this.knockBackResist = 0.2f;
                this.HitSound = SoundID.NPCHit36;
                this.DeathSound = SoundID.NPCDeath39;
                this.value = 500f;
                this.noTileCollide = true;
                this.noGravity = true;
            }
            else if (this.type == 289)
            {
                this.width = 44;
                this.height = 44;
                this.aiStyle = 10;
                this.damage = 60;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 150f;
                this.knockBackResist = 0.2f;
                this.npcSlots = 0.75f;
            }
            else if (this.type == 290)
            {
                this.width = 34;
                this.height = 62;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 50;
                this.lifeMax = 5000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0f;
                this.value = 50000f;
                this.rarity = 2;
            }
            else if (this.type == 291)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
                this.rarity = 1;
            }
            else if (this.type == 292)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
                this.rarity = 1;
            }
            else if (this.type == 293)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 28;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 1000f;
                this.rarity = 1;
            }
            else if (this.type == 294)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 34;
                this.defense = 6;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.9f;
                this.value = 130f;
            }
            else if (this.type == 295)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 28;
                this.defense = 12;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.7f;
                this.value = 130f;
            }
            else if (this.type == 296)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 24;
                this.defense = 14;
                this.lifeMax = 120;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 130f;
            }
            else if (this.type == 299)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2018;
            }
            else if (this.type == 300)
            {
                this.width = 14;
                this.height = 12;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath4;
                this.npcSlots = 0.25f;
                this.catchItem = 2003;
            }
            else if (this.type == 301)
            {
                this.width = 36;
                this.height = 26;
                this.aiStyle = 17;
                this.damage = 12;
                this.defense = 2;
                this.lifeMax = 35;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.85f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 50f;
            }
            if (this.type == 302)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 7;
                this.defense = 2;
                this.lifeMax = 25;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 25f;
            }
            else if (this.type == 304)
            {
                this.width = 34;
                this.height = 28;
                this.aiStyle = 1;
                this.damage = 80;
                this.defense = 20;
                this.lifeMax = 175;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
                this.scale = 1.1f;
                this.knockBackResist = 0.5f;
                this.npcSlots = 0.3f;
            }
            else if (this.type >= 305 && this.type <= 314)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 1200f;
                this.npcSlots = 0.5f;
                if (this.type == 305 || this.type == 310)
                {
                    this.damage = 60;
                    this.defense = 18;
                    this.lifeMax = 500;
                    this.knockBackResist = 0.4f;
                }
                else if (this.type == 306 || this.type == 311)
                {
                    this.damage = 52;
                    this.defense = 14;
                    this.lifeMax = 400;
                    this.knockBackResist = 0.2f;
                    this.scale = 1.05f;
                }
                else if (this.type == 307 || this.type == 312)
                {
                    this.damage = 78;
                    this.defense = 16;
                    this.lifeMax = 600;
                    this.knockBackResist = 0.25f;
                    this.scale = 0.9f;
                }
                else if (this.type == 308 || this.type == 313)
                {
                    this.damage = 66;
                    this.defense = 14;
                    this.lifeMax = 650;
                    this.knockBackResist = 0.35f;
                    this.scale = 0.95f;
                }
                else if (this.type == 309 || this.type == 314)
                {
                    this.damage = 52;
                    this.defense = 26;
                    this.lifeMax = 450;
                    this.knockBackResist = 0.5f;
                    this.scale = 1.1f;
                }
            }
            else if (this.type == 315)
            {
                this.width = 74;
                this.height = 70;
                this.aiStyle = 26;
                this.damage = 130;
                this.defense = 40;
                this.lifeMax = 5000;
                this.HitSound = SoundID.NPCHit12;
                this.DeathSound = SoundID.NPCDeath18;
                this.knockBackResist = 0f;
                this.value = 10000f;
            }
            else if (this.type == 316)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 24;
                this.height = 44;
                this.aiStyle = 22;
                this.damage = 15;
                this.defense = 4;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.alpha = 100;
                this.value = 90f;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 317)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 16;
                this.defense = 6;
                this.lifeMax = 75;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.7f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 100f;
            }
            else if (this.type == 318)
            {
                this.width = 30;
                this.height = 32;
                this.aiStyle = 2;
                this.damage = 20;
                this.defense = 4;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.65f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 100f;
            }
            else if (this.type == 319)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 6;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 85f;
                this.scale = 0.9f;
            }
            else if (this.type == 320)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 15;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 105f;
                this.scale = 1.05f;
            }
            else if (this.type == 321)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 14;
                this.lifeMax = 34;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = 120f;
                this.scale = 1.1f;
            }
            else if (this.type == 322)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 23;
                this.defense = 0;
                this.lifeMax = 115;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.65f;
                this.value = 130f;
            }
            else if (this.type == 323)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 18;
                this.defense = 10;
                this.lifeMax = 65;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 120f;
            }
            else if (this.type == 324)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 22;
                this.defense = 10;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 130f;
                this.scale = 1.05f;
            }
            else if (this.type == 325)
            {
                this.width = 164;
                this.height = 154;
                this.aiStyle = 57;
                this.damage = 120;
                this.defense = 34;
                this.lifeMax = 14000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.npcSlots = 3f;
            }
            else if (this.type == 326)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 32;
                this.lifeMax = 1200;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.2f;
                this.value = 2000f;
            }
            else if (this.type == 327)
            {
                this.width = 100;
                this.height = 100;
                this.aiStyle = 58;
                this.damage = 50;
                this.defense = 40;
                this.lifeMax = 26000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 50000f;
                this.knockBackResist = 0f;
                this.npcSlots = 5f;
            }
            else if (this.type == 328)
            {
                this.width = 80;
                this.height = 80;
                this.aiStyle = 59;
                this.damage = 65;
                this.defense = 14;
                this.lifeMax = 5000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.dontTakeDamage = true;
                this.npcSlots = 0f;
                this.dontCountMe = true;
            }
            else if (this.type == 329)
            {
                this.width = 46;
                this.height = 30;
                this.aiStyle = 26;
                this.damage = 80;
                this.defense = 38;
                this.lifeMax = 1800;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0.3f;
                this.value = 3000f;
            }
            else if (this.type == 330)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 24;
                this.height = 44;
                this.aiStyle = 22;
                this.damage = 90;
                this.defense = 44;
                this.lifeMax = 1250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.alpha = 100;
                this.value = 4500f;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 331)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 60f;
            }
            else if (this.type == 332)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 60f;
            }
            if (this.type == 333)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 7;
                this.defense = 2;
                this.lifeMax = 25;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 25f;
            }
            if (this.type == 334)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 6;
                this.defense = 2;
                this.lifeMax = 23;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.scale = 0.9f;
                this.value = 25f;
            }
            if (this.type == 335)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 8;
                this.defense = 3;
                this.lifeMax = 29;
                this.scale = 1.05f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 25f;
            }
            if (this.type == 336)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 5;
                this.defense = 1;
                this.lifeMax = 22;
                this.scale = 0.85f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 25f;
            }
            else if (this.type >= 338 && this.type <= 340)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 1200f;
                this.npcSlots = 0.5f;
                if (this.type == 338)
                {
                    this.damage = 65;
                    this.defense = 18;
                    this.lifeMax = 600;
                    this.knockBackResist = 0.4f;
                }
                else if (this.type == 339)
                {
                    this.damage = 52;
                    this.defense = 24;
                    this.lifeMax = 700;
                    this.knockBackResist = 0.2f;
                    this.scale = 1.05f;
                }
                else if (this.type == 340)
                {
                    this.damage = 78;
                    this.defense = 14;
                    this.lifeMax = 500;
                    this.knockBackResist = 0.25f;
                    this.scale = 0.9f;
                }
            }
            else if (this.type == 341)
            {
                this.width = 24;
                this.height = 24;
                this.aiStyle = 25;
                this.damage = 100;
                this.defense = 32;
                this.lifeMax = 900;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = (float)Item.buyPrice(0, 0, 20, 0);
                this.knockBackResist = 0.25f;
            }
            else if (this.type == 342)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 90;
                this.defense = 26;
                this.lifeMax = 750;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.2f;
                this.value = 1800f;
            }
            else if (this.type == 343)
            {
                this.width = 38;
                this.height = 78;
                this.aiStyle = 3;
                this.damage = 140;
                this.defense = 50;
                this.lifeMax = 3500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.value = 3000f;
                this.npcSlots = 2f;
                this.coldDamage = true;
            }
            else if (this.type == 344)
            {
                this.width = 172;
                this.height = 130;
                this.aiStyle = 57;
                this.damage = 110;
                this.defense = 38;
                this.lifeMax = 13000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.npcSlots = 3f;
            }
            else if (this.type == 345)
            {
                this.width = 130;
                this.height = 140;
                this.aiStyle = 60;
                this.damage = 120;
                this.defense = 38;
                this.lifeMax = 34000;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0f;
                this.value = 50000f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 5f;
                this.coldDamage = true;
            }
            else if (this.type == 346)
            {
                this.width = 112;
                this.height = 140;
                this.aiStyle = 61;
                this.damage = 120;
                this.defense = 56;
                this.lifeMax = 18000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.knockBackResist = 0f;
                this.value = 10000f;
                this.npcSlots = 4f;
            }
            else if (this.type == 347)
            {
                this.width = 50;
                this.height = 50;
                this.aiStyle = 62;
                this.damage = 60;
                this.defense = 28;
                this.lifeMax = 1200;
                this.HitSound = SoundID.NPCHit4;
                this.knockBackResist = 0.4f;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 1000f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 1.5f;
            }
            else if (this.type == 348)
            {
                this.width = 28;
                this.height = 76;
                this.aiStyle = 3;
                this.damage = 80;
                this.defense = 26;
                this.lifeMax = 1800;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
                this.value = 1500f;
                this.npcSlots = 1.5f;
            }
            else if (this.type == 349)
            {
                this.width = 28;
                this.height = 76;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 42;
                this.lifeMax = 1800;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.1f;
                this.value = 1500f;
                this.npcSlots = 1.5f;
            }
            else if (this.type == 350)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 30;
                this.lifeMax = 900;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.45f;
                this.value = 900f;
            }
            else if (this.type == 351)
            {
                this.width = 18;
                this.height = 90;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 40;
                this.lifeMax = 2500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.1f;
                this.value = 3000f;
                this.npcSlots = 1.75f;
            }
            else if (this.type == 352)
            {
                this.width = 54;
                this.height = 54;
                this.aiStyle = 63;
                this.damage = 75;
                this.defense = 8;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 500f;
                this.knockBackResist = 0.4f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 2f;
                this.coldDamage = true;
            }
            else if (this.type == 353)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 354)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 34;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.scale = 0.9f;
                this.rarity = 1;
            }
            else if (this.type == 355)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 64;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.2f;
                this.noGravity = true;
                this.catchItem = 1992;
            }
            else if (this.type == 356)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 65;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                this.catchItem = 1994;
            }
            else if (this.type == 357)
            {
                this.width = 10;
                this.height = 4;
                this.aiStyle = 66;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.1f;
                this.catchItem = 2002;
                this.friendly = true;
            }
            else if (this.type == 358)
            {
                this.width = 12;
                this.height = 12;
                this.aiStyle = 64;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.2f;
                this.noGravity = true;
                this.catchItem = 2004;
            }
            else if (this.type == 359)
            {
                this.width = 12;
                this.height = 12;
                this.aiStyle = 67;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.catchItem = 2006;
            }
            else if (this.type == 360)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 67;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.catchItem = 2007;
            }
            else if (this.type == 361)
            {
                this.width = 12;
                this.height = 10;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2121;
            }
            else if (this.type == 362)
            {
                this.width = 22;
                this.height = 26;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2122;
            }
            else if (this.type == 363)
            {
                this.width = 28;
                this.height = 22;
                this.aiStyle = 68;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2122;
            }
            else if (this.type == 364)
            {
                this.width = 22;
                this.height = 26;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2123;
            }
            else if (this.type == 365)
            {
                this.width = 28;
                this.height = 22;
                this.aiStyle = 68;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2123;
            }
            else if (this.type == 366 || this.type == 367)
            {
                this.width = 26;
                this.height = 18;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = (short)(2156 + this.type - 366);
            }
            else if (this.type == 368)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 369)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 370)
            {
                this.width = 150;
                this.height = 100;
                this.aiStyle = 69;
                this.damage = 100;
                this.defense = 50;
                this.lifeMax = 60000;
                this.knockBackResist = 0f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 10f;
                this.HitSound = SoundID.NPCHit14;
                this.DeathSound = SoundID.NPCDeath20;
                this.value = 250000f;
                this.boss = true;
                this.netAlways = true;
            }
            else if (this.type == 371)
            {
                this.width = 36;
                this.height = 36;
                this.aiStyle = 70;
                this.damage = 100;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.alpha = 255;
            }
            else if (this.type == 372)
            {
                this.noGravity = true;
                this.width = 120;
                this.height = 24;
                this.aiStyle = 71;
                this.damage = 100;
                this.defense = 100;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.alpha = 255;
            }
            else if (this.type == 373)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 24;
                this.aiStyle = 71;
                this.damage = 120;
                this.defense = 100;
                this.lifeMax = 100;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.alpha = 255;
            }
            else if (this.type == 374)
            {
                this.width = 20;
                this.height = 10;
                this.aiStyle = 66;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.15f;
                this.catchItem = 2673;
                this.rarity = 4;
                this.dontTakeDamageFromHostiles = true;
            }
            else if (this.type == 375)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 6;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.npcSlots = 0.15f;
                this.catchItem = 2673;
                this.rarity = 4;
                this.dontTakeDamageFromHostiles = true;
            }
            else if (this.type == 376)
            {
                this.friendly = true;
                this.width = 34;
                this.height = 8;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.scale = 0.9f;
                this.rarity = 1;
            }
            else if (this.type == 377)
            {
                this.width = 14;
                this.height = 10;
                this.aiStyle = 1;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.friendly = true;
                this.catchItem = 2740;
                this.npcSlots = 0.1f;
            }
            else if (this.type == 378)
            {
                this.npcSlots = 1f;
                this.width = 20;
                this.height = 26;
                this.aiStyle = 41;
                this.damage = 120;
                this.defense = 30;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.value = 450f;
            }
            else if (this.type >= 379 && this.type <= 380)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 45;
                this.defense = 14;
                this.lifeMax = 210;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.55f;
                this.value = 1000f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.netAlways = true;
                this.chaseable = false;
            }
            else if (this.type >= 381 && this.type <= 382)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 25;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit39;
                this.DeathSound = SoundID.NPCDeath57;
                this.knockBackResist = 0.35f;
                this.value = 1000f;
            }
            else if (this.type == 383)
            {
                this.lifeMax = 300;
                this.defense = 50;
                this.damage = 75;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit39;
                this.DeathSound = SoundID.NPCDeath57;
                this.value = 1200f;
                this.knockBackResist = 0.25f;
            }
            else if (this.type == 384)
            {
                this.lifeMax = 1000;
                this.width = 18;
                this.defense = 20;
                this.height = 40;
                this.aiStyle = 72;
                this.HitSound = SoundID.NPCHit43;
                this.DeathSound = SoundID.NPCDeath45;
                this.npcSlots = 0f;
                this.noTileCollide = true;
                this.canGhostHeal = false;
            }
            else if (this.type == 385)
            {
                this.lifeMax = 750;
                this.defense = 30;
                this.damage = 80;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit39;
                this.DeathSound = SoundID.NPCDeath57;
                this.value = 600f;
                this.knockBackResist = 0f;
                this.npcSlots = 0.75f;
            }
            else if (this.type == 386)
            {
                this.lifeMax = 400;
                this.defense = 34;
                this.damage = 40;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit39;
                this.DeathSound = SoundID.NPCDeath57;
                this.value = 1200f;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 387)
            {
                this.width = 20;
                this.height = 50;
                this.aiStyle = 73;
                this.damage = 10;
                this.defense = 40;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit53;
                this.DeathSound = SoundID.NPCDeath56;
                this.knockBackResist = 0f;
                this.canGhostHeal = false;
            }
            else if (this.type == 388)
            {
                this.width = 40;
                this.height = 30;
                this.aiStyle = 74;
                this.damage = 60;
                this.defense = 16;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit42;
                this.knockBackResist = 0.4f;
                this.DeathSound = SoundID.NPCDeath44;
                this.value = 1000f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 1.5f;
                this.canGhostHeal = false;
            }
            else if (this.type == 389)
            {
                this.lifeMax = 600;
                this.defense = 38;
                this.damage = 75;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit39;
                this.DeathSound = SoundID.NPCDeath57;
                this.value = 1200f;
                this.npcSlots = 0.5f;
                this.knockBackResist = 0.3f;
            }
            else if (this.type == 390)
            {
                this.damage = 65;
                this.defense = 30;
                this.lifeMax = 350;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 75;
                this.HitSound = SoundID.NPCHit39;
                this.DeathSound = SoundID.NPCDeath57;
                this.value = 1200f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 391)
            {
                this.lifeMax = 600;
                this.defense = 30;
                this.damage = 85;
                this.width = 60;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit51;
                this.DeathSound = SoundID.NPCDeath54;
                this.value = 1200f;
                this.npcSlots = 0.5f;
                this.knockBackResist = 0.1f;
            }
            else if (this.type == 392)
            {
                this.lifeMax = 100;
                this.defense = 100;
                this.damage = 50;
                this.width = 150;
                this.height = 80;
                this.aiStyle = 75;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 0f;
                this.npcSlots = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.dontTakeDamage = true;
                this.netAlways = true;
            }
            else if (this.type == 393)
            {
                this.lifeMax = 5000;
                this.defense = 20;
                this.damage = 60;
                this.width = 40;
                this.height = 16;
                this.aiStyle = 75;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 0f;
                this.npcSlots = 1f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.netAlways = true;
            }
            else if (this.type == 394)
            {
                this.lifeMax = 3500;
                this.defense = 20;
                this.damage = 60;
                this.width = 46;
                this.height = 36;
                this.aiStyle = 75;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 0f;
                this.npcSlots = 1f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.netAlways = true;
            }
            else if (this.type == 395)
            {
                this.lifeMax = 10000;
                this.defense = 0;
                this.damage = 80;
                this.width = 120;
                this.height = 90;
                this.aiStyle = 76;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 0f;
                this.npcSlots = 6f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.dontTakeDamage = true;
                this.boss = true;
                this.netAlways = true;
            }
            else if (this.type == 399)
            {
                this.defense = 5;
                this.damage = 5;
                this.lifeMax = 500;
                this.aiStyle = 80;
                this.width = 42;
                this.height = 72;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.npcSlots = 0f;
                this.noGravity = true;
                this.chaseable = false;
                this.netAlways = true;
                this.rarity = 1;
            }
            else if (this.type == 396)
            {
                this.lifeMax = 45000;
                this.defense = 50;
                this.damage = 0;
                this.width = 38;
                this.height = 56;
                this.aiStyle = 79;
                this.HitSound = SoundID.NPCHit57;
                this.DeathSound = SoundID.NPCDeath62;
                this.value = 0f;
                this.npcSlots = 6f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.hide = true;
                this.netAlways = true;
            }
            else if (this.type == 397)
            {
                this.lifeMax = 25000;
                this.defense = 40;
                this.damage = 0;
                this.width = 46;
                this.height = 66;
                this.aiStyle = 78;
                this.HitSound = SoundID.NPCHit57;
                this.DeathSound = SoundID.NPCDeath62;
                this.value = 0f;
                this.npcSlots = 6f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.boss = true;
                this.hide = true;
                this.netAlways = true;
            }
            else if (this.type == 398)
            {
                this.lifeMax = 50000;
                this.defense = 70;
                this.damage = 0;
                this.width = 46;
                this.height = 66;
                this.aiStyle = 77;
                this.HitSound = SoundID.NPCHit57;
                this.DeathSound = null;
                this.value = 1000000f;
                this.npcSlots = 6f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.dontTakeDamage = true;
                this.boss = true;
                this.behindTiles = true;
                this.hide = true;
                this.netAlways = true;
            }
            else if (this.type == 400)
            {
                this.defense = 0;
                this.damage = 60;
                this.lifeMax = 100;
                this.aiStyle = 81;
                this.width = 60;
                this.height = 60;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0f;
                this.noGravity = true;
                this.dontTakeDamage = true;
                this.noTileCollide = true;
                this.netAlways = true;
            }
            else if (this.type == 401)
            {
                this.lifeMax = 400;
                this.defense = 0;
                this.damage = 0;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 82;
                this.HitSound = SoundID.NPCHit57;
                this.DeathSound = SoundID.NPCDeath62;
                this.value = 0f;
                this.npcSlots = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.hide = true;
            }
            else if (this.type == 437)
            {
                this.lifeMax = 400;
                this.defense = 0;
                this.damage = 0;
                this.width = 54;
                this.height = 54;
                this.aiStyle = 83;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 0f;
                this.npcSlots = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.dontTakeDamage = true;
                this.netAlways = true;
                this.chaseable = false;
            }
            else if (this.type == 438)
            {
                this.lifeMax = 400;
                this.defense = 0;
                this.damage = 0;
                this.width = 22;
                this.height = 40;
                this.aiStyle = 83;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.npcSlots = 0f;
                this.knockBackResist = 0f;
                this.lavaImmune = true;
                this.netAlways = true;
                this.chaseable = false;
            }
            else if (this.type == 439)
            {
                this.width = 24;
                this.height = 50;
                this.aiStyle = 84;
                this.damage = 50;
                this.defense = 42;
                this.lifeMax = 32000;
                this.knockBackResist = 0f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 10f;
                this.HitSound = SoundID.NPCHit55;
                this.DeathSound = SoundID.NPCDeath59;
                this.value = 100000f;
                this.boss = true;
                this.netAlways = true;
            }
            else if (this.type == 440)
            {
                this.width = 24;
                this.height = 50;
                this.aiStyle = 84;
                this.damage = 0;
                this.defense = 35;
                this.lifeMax = 10000;
                this.knockBackResist = 0f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 0f;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.netAlways = true;
                this.chaseable = false;
            }
            else if (this.type == 442)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2889;
                this.npcSlots = 0.4f;
                this.rarity = 3;
            }
            else if (this.type == 443)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2890;
                this.rarity = 3;
            }
            else if (this.type == 444)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 65;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                this.catchItem = 2891;
                this.rarity = 3;
            }
            else if (this.type == 445)
            {
                this.width = 12;
                this.height = 10;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 2892;
                this.rarity = 3;
            }
            else if (this.type == 446)
            {
                this.width = 14;
                this.height = 10;
                this.aiStyle = 1;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.friendly = true;
                this.catchItem = 2893;
                this.npcSlots = 0.1f;
                this.rarity = 3;
            }
            else if (this.type == 447)
            {
                this.width = 14;
                this.height = 12;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath4;
                this.npcSlots = 0.25f;
                this.catchItem = 2894;
                this.rarity = 3;
            }
            else if (this.type == 448)
            {
                this.width = 10;
                this.height = 4;
                this.aiStyle = 66;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.1f;
                this.catchItem = 2895;
                this.friendly = true;
                this.rarity = 3;
            }
            else if (this.type == 449)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 100f;
            }
            else if (this.type == 450)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 12;
                this.lifeMax = 55;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 130f;
            }
            else if (this.type == 451)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 18;
                this.defense = 8;
                this.lifeMax = 65;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 120f;
            }
            else if (this.type == 452)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 22;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 110f;
            }
            else if (this.type == 453)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 30;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.npcSlots = 7f;
                this.rarity = 1;
            }
            else if (this.type == 454)
            {
                this.noTileCollide = true;
                this.npcSlots = 5f;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 100;
                this.defense = 15;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit56;
                this.DeathSound = SoundID.NPCDeath60;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.scale = 1f;
                this.alpha = 255;
            }
            else if (this.type == 459)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 50;
                this.defense = 30;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit56;
                this.DeathSound = SoundID.NPCDeath60;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.scale = 1f;
                this.alpha = 255;
                this.dontCountMe = true;
            }
            else if (this.type == 455 || this.type == 456 || this.type == 457 || this.type == 458)
            {
                this.noTileCollide = true;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 50;
                this.defense = 30;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit56;
                this.DeathSound = SoundID.NPCDeath60;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.scale = 1f;
                this.alpha = 255;
                this.dontCountMe = true;
            }
            else if (this.type == 464)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 21;
                this.defense = 5;
                this.lifeMax = 75;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 465)
            {
                this.noGravity = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 16;
                this.damage = 31;
                this.defense = 7;
                this.lifeMax = 110;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 470)
            {
                this.width = 16;
                this.height = 34;
                this.aiStyle = 3;
                this.damage = 21;
                this.defense = 5;
                this.lifeMax = 75;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 500f;
            }
            else if (this.type == 473 || this.type == 474 || this.type == 475 || this.type == 476)
            {
                this.width = 28;
                this.height = 44;
                this.aiStyle = 87;
                this.damage = 90;
                this.defense = 34;
                this.lifeMax = 3500;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 30000f;
                this.knockBackResist = 0.1f;
                this.rarity = 5;
            }
            else if (this.type == 480)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 30;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.15f;
                this.value = 1000f;
                this.rarity = 1;
            }
            else if (this.type == 481)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 22;
                this.defense = 10;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.4f;
                this.value = 300f;
            }
            else if (this.type == 482)
            {
                this.width = 28;
                this.height = 48;
                this.aiStyle = 3;
                this.damage = 30;
                this.defense = 18;
                this.lifeMax = 110;
                this.HitSound = SoundID.NPCHit41;
                this.DeathSound = SoundID.NPCDeath43;
                this.knockBackResist = 0.35f;
                this.value = 500f;
            }
            else if (this.type == 483)
            {
                this.npcSlots = 0.5f;
                this.width = 20;
                this.height = 30;
                this.aiStyle = 91;
                this.damage = 24;
                this.defense = 8;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit7;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 1000f;
            }
            else if (this.type >= 484 && this.type <= 487)
            {
                this.width = 10;
                this.height = 4;
                this.aiStyle = 66;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.1f;
                this.catchItem = (short)(3191 + this.type - 484);
                this.friendly = true;
            }
            else if (this.type == 488)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 92;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit15;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.immortal = true;
                this.netAlways = true;
            }
            else if (this.type == 489)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 8;
                this.lifeMax = 75;
                this.HitSound = SoundID.NPCHit18;
                this.DeathSound = SoundID.NPCDeath21;
                this.knockBackResist = 0.4f;
                this.value = 150f;
            }
            else if (this.type == 490)
            {
                this.noGravity = true;
                this.width = 28;
                this.height = 30;
                this.aiStyle = 22;
                this.damage = 28;
                this.defense = 14;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit19;
                this.knockBackResist = 0.6f;
                this.DeathSound = SoundID.NPCDeath22;
                this.value = 150f;
            }
            else if (this.type == 491)
            {
                this.noGravity = true;
                this.width = 350;
                this.height = 120;
                this.aiStyle = 93;
                this.damage = 0;
                this.defense = 100;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit19;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath22;
                this.value = 0f;
                this.dontTakeDamage = true;
                this.netAlways = true;
            }
            else if (this.type == 492)
            {
                this.lifeMax = 2000;
                this.defense = 20;
                this.damage = 30;
                this.width = 30;
                this.height = 30;
                this.aiStyle = 75;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.value = 0f;
                this.npcSlots = 1f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.hide = true;
                this.netAlways = true;
            }
            else if (this.type >= 494 && this.type <= 495)
            {
                this.width = 28;
                this.height = 22;
                this.aiStyle = 3;
                this.damage = 28;
                this.defense = 6;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit33;
                this.DeathSound = SoundID.NPCDeath36;
                this.value = 120f;
            }
            else if (this.type >= 496 && this.type <= 497)
            {
                this.width = 28;
                this.height = 22;
                this.aiStyle = 39;
                this.damage = 16;
                this.defense = 12;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit38;
                this.DeathSound = SoundID.NPCDeath41;
                this.knockBackResist = 0.75f;
                this.value = 120f;
            }
            else if (this.type >= 498 && this.type <= 506)
            {
                this.width = 24;
                this.height = 44;
                this.aiStyle = 3;
                this.damage = 18;
                this.defense = 10;
                this.lifeMax = 65;
                this.HitSound = SoundID.NPCHit50;
                this.DeathSound = SoundID.NPCDeath53;
                this.knockBackResist = 0.45f;
                this.value = 120f;
            }
            else if (this.type == 441)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 513)
            {
                this.npcSlots = 4f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.damage = 18;
                this.defense = 0;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 130f;
            }
            else if (this.type == 514)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 7;
                this.defense = 12;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 130f;
                this.dontCountMe = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 515)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 7;
                this.defense = 14;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 130f;
                this.dontCountMe = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 510)
            {
                this.npcSlots = 5f;
                this.width = 34;
                this.height = 34;
                this.aiStyle = 6;
                this.damage = 58;
                this.defense = 18;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 700f;
            }
            else if (this.type == 511)
            {
                this.width = 34;
                this.height = 34;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 54;
                this.defense = 28;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 700f;
                this.dontCountMe = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 512)
            {
                this.width = 34;
                this.height = 34;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 50;
                this.defense = 34;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = 700f;
                this.dontCountMe = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 508)
            {
                this.width = 50;
                this.height = 31;
                this.aiStyle = 3;
                this.damage = 38;
                this.defense = 16;
                this.lifeMax = 110;
                this.HitSound = SoundID.NPCHit31;
                this.DeathSound = SoundID.NPCDeath34;
                this.knockBackResist = 0.4f;
                this.value = 175f;
            }
            else if (this.type == 509)
            {
                this.width = 40;
                this.height = 31;
                this.aiStyle = 44;
                this.damage = 34;
                this.defense = 12;
                this.lifeMax = 90;
                this.knockBackResist = 0.3f;
                this.HitSound = SoundID.NPCHit32;
                this.DeathSound = SoundID.NPCDeath35;
                this.value = 195f;
            }
            else if (this.type == 580)
            {
                this.width = 26;
                this.height = 26;
                this.aiStyle = 3;
                this.damage = 25;
                this.defense = 10;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit31;
                this.DeathSound = SoundID.NPCDeath34;
                this.knockBackResist = 0.5f;
                this.value = 80f;
                this.npcSlots = 0.8f;
            }
            else if (this.type == 581)
            {
                this.width = 30;
                this.height = 22;
                this.aiStyle = 44;
                this.damage = 29;
                this.defense = 8;
                this.lifeMax = 60;
                this.knockBackResist = 0.5f;
                this.HitSound = SoundID.NPCHit32;
                this.DeathSound = SoundID.NPCDeath35;
                this.value = 90f;
                this.npcSlots = 0.8f;
            }
            else if (this.type >= 524 && this.type <= 527)
            {
                this.width = 24;
                this.height = 44;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 26;
                this.lifeMax = 180;
                this.HitSound = SoundID.NPCHit37;
                this.DeathSound = SoundID.NPCDeath40;
                this.knockBackResist = 0.6f;
                this.value = 500f;
                this.npcSlots = 0.5f;
                switch (this.type - 524)
                {
                case 1:
                    this.lifeMax += 70;
                    this.defense += 4;
                    this.damage += 10;
                    this.knockBackResist -= 0.1f;
                    this.value += 150f;
                    break;
                case 2:
                    this.lifeMax += 40;
                    this.defense += 6;
                    this.damage += 14;
                    this.knockBackResist -= 0.1f;
                    this.value += 150f;
                    break;
                case 3:
                    this.lifeMax += 120;
                    this.defense += 6;
                    this.damage += 4;
                    this.knockBackResist -= 0.2f;
                    this.value += 250f;
                    break;
                }
            }
            else if (this.type >= 528 && this.type <= 529)
            {
                this.width = 24;
                this.height = 44;
                this.aiStyle = 3;
                this.damage = 52;
                this.defense = 28;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.35f;
                this.value = 600f;
            }
            else if (this.type == 530)
            {
                this.width = 50;
                this.height = 20;
                this.aiStyle = 3;
                this.damage = 66;
                this.defense = 24;
                this.lifeMax = 320;
                this.HitSound = SoundID.NPCHit13;
                this.DeathSound = SoundID.NPCDeath19;
                this.knockBackResist = 0.5f;
                this.value = 600f;
            }
            else if (this.type == 531)
            {
                this.noGravity = true;
                this.width = 36;
                this.height = 36;
                this.aiStyle = 40;
                this.damage = 66;
                this.defense = 24;
                this.lifeMax = 320;
                this.HitSound = SoundID.NPCHit13;
                this.DeathSound = SoundID.NPCDeath19;
                this.knockBackResist = 0.5f;
                this.value = 600f;
            }
            else if (this.type == 532)
            {
                this.width = 32;
                this.height = 31;
                this.aiStyle = 3;
                this.damage = 65;
                this.defense = 34;
                this.lifeMax = 270;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 800f;
                this.npcSlots = 0.75f;
            }
            else if (this.type == 533)
            {
                this.width = 28;
                this.height = 62;
                this.aiStyle = 8;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 220;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0f;
                this.value = 1200f;
                this.npcSlots = 2f;
            }
            else if (this.type == 493)
            {
                this.lifeMax = 20000;
                this.defense = 20;
                this.damage = 0;
                this.width = 130;
                this.height = 270;
                this.aiStyle = 94;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 402)
            {
                this.noTileCollide = true;
                this.npcSlots = 1f;
                this.width = 32;
                this.height = 32;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 80;
                this.defense = 10;
                this.lifeMax = 1200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.scale = 1f;
            }
            else if (this.type == 405)
            {
                this.width = 44;
                this.height = 44;
                this.aiStyle = 85;
                this.damage = 120;
                this.defense = 50;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.noGravity = true;
                this.npcSlots = 2f;
            }
            else if (this.type == 406)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 95;
                this.damage = 70;
                this.defense = 0;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
                this.noGravity = true;
            }
            else if (this.type == 411)
            {
                this.width = 22;
                this.height = 56;
                this.aiStyle = 3;
                this.damage = 80;
                this.defense = 34;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit6;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 409)
            {
                this.width = 34;
                this.height = 42;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 40;
                this.lifeMax = 800;
                this.HitSound = SoundID.NPCHit6;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
                this.npcSlots = 3f;
            }
            else if (this.type == 410)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 26;
                this.damage = 80;
                this.defense = 10;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0.3f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 407)
            {
                this.width = 40;
                this.height = 60;
                this.aiStyle = 96;
                this.damage = 70;
                this.defense = 38;
                this.lifeMax = 1500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.knockBackResist = 0.03f;
                this.npcSlots = 3f;
            }
            else if (this.type == 507)
            {
                this.lifeMax = 20000;
                this.defense = 20;
                this.damage = 0;
                this.width = 130;
                this.height = 270;
                this.aiStyle = 94;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 423)
            {
                this.width = 50;
                this.height = 44;
                this.aiStyle = 26;
                this.damage = 90;
                this.defense = 46;
                this.lifeMax = 850;
                this.HitSound = SoundID.NPCHit6;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.2f;
                this.npcSlots = 1f;
            }
            else if (this.type == 421)
            {
                this.width = 44;
                this.height = 44;
                this.aiStyle = 85;
                this.damage = 70;
                this.defense = 34;
                this.lifeMax = 330;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.noGravity = true;
                this.npcSlots = 1f;
            }
            else if (this.type == 424)
            {
                this.width = 22;
                this.height = 56;
                this.aiStyle = 3;
                this.damage = 80;
                this.defense = 30;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0.6f;
                this.npcSlots = 2f;
            }
            else if (this.type == 420)
            {
                this.width = 40;
                this.height = 40;
                this.aiStyle = 97;
                this.damage = 75;
                this.defense = 20;
                this.lifeMax = 1300;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.noTileCollide = true;
                this.noGravity = true;
                this.npcSlots = 3f;
            }
            else if (this.type == 422)
            {
                this.lifeMax = 20000;
                this.defense = 20;
                this.damage = 0;
                this.width = 130;
                this.height = 270;
                this.aiStyle = 94;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 425)
            {
                this.width = 30;
                this.height = 56;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 40;
                this.lifeMax = 800;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 429)
            {
                this.width = 22;
                this.height = 56;
                this.aiStyle = 3;
                this.damage = 90;
                this.defense = 34;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath5;
                this.knockBackResist = 0.6f;
                this.npcSlots = 2f;
            }
            else if (this.type == 428)
            {
                this.width = 24;
                this.height = 26;
                this.aiStyle = 3;
                this.damage = 50;
                this.defense = 6;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
            }
            else if (this.type == 427)
            {
                this.width = 40;
                this.height = 28;
                this.aiStyle = 3;
                this.damage = 75;
                this.defense = 20;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 426)
            {
                this.width = 50;
                this.height = 62;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 44;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.3f;
            }
            else if (this.type == 517)
            {
                this.lifeMax = 20000;
                this.defense = 20;
                this.damage = 0;
                this.width = 130;
                this.height = 270;
                this.aiStyle = 94;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 412)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 120;
                this.defense = 1000;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath22;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.dontTakeDamage = true;
                this.npcSlots = 2f;
            }
            else if (this.type == 413)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 80;
                this.defense = 1000;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath22;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.dontCountMe = true;
                this.dontTakeDamage = true;
                this.npcSlots = 0f;
            }
            else if (this.type == 414)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 50;
                this.defense = 0;
                this.lifeMax = 10000;
                this.HitSound = SoundID.NPCHit8;
                this.DeathSound = SoundID.NPCDeath22;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.dontCountMe = true;
                this.takenDamageMultiplier = 10f;
                this.npcSlots = 0f;
            }
            else if (this.type == 415)
            {
                this.lifeMax = 800;
                this.defense = 32;
                this.damage = 55;
                this.width = 60;
                this.height = 40;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.2f;
            }
            else if (this.type == 416)
            {
                this.damage = 80;
                this.defense = 28;
                this.lifeMax = 800;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 75;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.2f;
            }
            else if (this.type == 518)
            {
                this.lifeMax = 1000;
                this.defense = 28;
                this.damage = 80;
                this.width = 22;
                this.height = 56;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 417)
            {
                this.npcSlots = 2f;
                this.width = 46;
                this.height = 52;
                this.aiStyle = 39;
                this.damage = 80;
                this.defense = 34;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit7;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath5;
            }
            else if (this.type == 418)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 74;
                this.damage = 70;
                this.defense = 26;
                this.lifeMax = 600;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.2f;
            }
            else if (this.type == 419)
            {
                this.lifeMax = 800;
                this.defense = 30;
                this.damage = 90;
                this.width = 22;
                this.height = 56;
                this.aiStyle = 3;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.4f;
            }
            else if (this.type == 516)
            {
                this.width = 26;
                this.height = 26;
                this.aiStyle = 9;
                this.damage = 100;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = null;
                this.DeathSound = null;
                this.noGravity = true;
                this.noTileCollide = false;
                this.alpha = 0;
                this.knockBackResist = 0f;
            }
            else if (this.type == 519)
            {
                this.width = 26;
                this.height = 26;
                this.aiStyle = 99;
                this.damage = 120;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = null;
                this.DeathSound = null;
                this.noGravity = true;
                this.noTileCollide = false;
                this.alpha = 0;
                this.knockBackResist = 0f;
            }
            else if (this.type == 162)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 65;
                this.defense = 18;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.3f;
                this.value = 600f;
            }
            else if (this.type == 166)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 26;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.2f;
                this.value = 1000f;
            }
            else if (this.type == 253)
            {
                this.noGravity = true;
                this.noTileCollide = true;
                this.width = 24;
                this.height = 44;
                this.aiStyle = 22;
                this.damage = 80;
                this.defense = 22;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit49;
                this.DeathSound = SoundID.NPCDeath51;
                this.alpha = 100;
                this.value = 1500f;
                this.knockBackResist = 0.6f;
            }
            else if (this.type == 158)
            {
                this.npcSlots = 2f;
                this.width = 22;
                this.height = 22;
                this.aiStyle = 14;
                this.damage = 60;
                this.defense = 32;
                this.lifeMax = 750;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.75f;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 5000f;
            }
            else if (this.type == 159)
            {
                this.npcSlots = 2f;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 80;
                this.defense = 24;
                this.lifeMax = 750;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.4f;
                this.value = 5000f;
            }
            else if (this.type == 460)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 30;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit7;
                this.DeathSound = SoundID.NPCDeath17;
                this.knockBackResist = 0.25f;
                this.value = 1000f;
            }
            else if (this.type == 461)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 22;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 1000f;
            }
            else if (this.type == 462)
            {
                this.width = 20;
                this.height = 24;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 14;
                this.lifeMax = 270;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.7f;
                this.value = 600f;
                this.npcSlots = 0.5f;
            }
            else if (this.type == 463)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 100;
                this.defense = 34;
                this.lifeMax = 4000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.1f;
                this.value = 3000f;
            }
            else if (this.type == 466)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 70;
                this.defense = 40;
                this.lifeMax = 550;
                this.HitSound = SoundID.NPCHit48;
                this.DeathSound = SoundID.NPCDeath50;
                this.knockBackResist = 0.5f;
                this.value = 1500f;
            }
            else if (this.type == 467)
            {
                this.width = 22;
                this.height = 22;
                this.aiStyle = 85;
                this.damage = 100;
                this.defense = 80;
                this.lifeMax = 350;
                this.HitSound = SoundID.NPCHit34;
                this.DeathSound = SoundID.NPCDeath37;
                this.value = 900f;
                this.knockBackResist = 0.7f;
                this.noGravity = true;
            }
            else if (this.type == 469)
            {
                this.width = 38;
                this.height = 26;
                this.aiStyle = 3;
                this.damage = 68;
                this.defense = 28;
                this.lifeMax = 600;
                this.HitSound = SoundID.NPCHit47;
                this.DeathSound = SoundID.NPCDeath49;
                this.knockBackResist = 0.35f;
                this.value = 1300f;
            }
            else if (this.type == 468)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 65;
                this.defense = 24;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit35;
                this.DeathSound = SoundID.NPCDeath38;
                this.knockBackResist = 0.6f;
                this.value = 1300f;
            }
            else if (this.type == 477)
            {
                this.noGravity = true;
                this.netAlways = true;
                this.width = 80;
                this.height = 50;
                this.aiStyle = 88;
                this.damage = 80;
                this.defense = 30;
                this.lifeMax = 6000;
                this.HitSound = SoundID.NPCHit44;
                this.DeathSound = SoundID.NPCDeath46;
                this.value = 50000f;
                this.knockBackResist = 0.2f;
                this.rarity = 1;
            }
            else if (this.type == 478)
            {
                this.width = 34;
                this.height = 34;
                this.aiStyle = 89;
                this.damage = 0;
                this.defense = 30;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.knockBackResist = 0.7f;
                this.npcSlots = 0f;
            }
            else if (this.type == 479)
            {
                this.width = 46;
                this.height = 30;
                this.aiStyle = 90;
                this.damage = 50;
                this.defense = 14;
                this.lifeMax = 700;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 0f;
                this.npcSlots = 0.1f;
            }
            else if (this.type == 26)
            {
                this.scale = 0.9f;
                this.width = 18;
                this.height = 38;
                this.aiStyle = 3;
                this.damage = 12;
                this.defense = 4;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.8f;
                this.value = 100f;
            }
            else if (this.type == 27)
            {
                this.scale = 0.95f;
                this.width = 18;
                this.height = 38;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 6;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.7f;
                this.value = 200f;
            }
            else if (this.type == 28)
            {
                this.scale = 1.1f;
                this.width = 18;
                this.height = 38;
                this.aiStyle = 3;
                this.damage = 25;
                this.defense = 8;
                this.lifeMax = 110;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.value = 150f;
            }
            else if (this.type == 29)
            {
                this.width = 18;
                this.height = 38;
                this.aiStyle = 8;
                this.damage = 20;
                this.defense = 2;
                this.lifeMax = 40;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.6f;
                this.value = 200f;
            }
            else if (this.type == 30)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 9;
                this.damage = 20;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.alpha = 100;
                this.knockBackResist = 0f;
            }
            else if (this.type == 111)
            {
                this.scale = 0.95f;
                this.width = 18;
                this.height = 38;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 6;
                this.lifeMax = 80;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.7f;
                this.value = 200f;
            }
            else if (this.type == 471)
            {
                this.width = 18;
                this.height = 38;
                this.aiStyle = 3;
                this.damage = 80;
                this.defense = 26;
                this.lifeMax = 2000;
                this.HitSound = SoundID.NPCHit40;
                this.DeathSound = SoundID.NPCDeath42;
                this.knockBackResist = 0.15f;
                this.value = 5000f;
                this.rarity = 1;
            }
            else if (this.type == 472)
            {
                this.width = 40;
                this.height = 24;
                this.aiStyle = 86;
                this.damage = 50;
                this.defense = 18;
                this.lifeMax = 180;
                this.HitSound = SoundID.NPCHit52;
                this.DeathSound = SoundID.NPCDeath55;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0.1f;
            }
            else if (this.type == 520)
            {
                this.width = 34;
                this.height = 110;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 40;
                this.lifeMax = 2000;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath14;
                this.knockBackResist = 0f;
            }
            else if (this.type == 521)
            {
                this.width = 60;
                this.height = 60;
                this.aiStyle = 86;
                this.damage = 90;
                this.defense = 30;
                this.lifeMax = 2000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0f;
            }
            else if (this.type == 522)
            {
                this.width = 26;
                this.height = 26;
                this.aiStyle = 100;
                this.damage = 120;
                this.defense = 0;
                this.lifeMax = 400;
                this.HitSound = null;
                this.DeathSound = null;
                this.noGravity = true;
                this.noTileCollide = true;
                this.alpha = 0;
                this.knockBackResist = 0f;
            }
            else if (this.type == 523)
            {
                this.width = 42;
                this.height = 42;
                this.aiStyle = 101;
                this.damage = 30;
                this.defense = 0;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.noGravity = true;
                this.noTileCollide = true;
                this.alpha = 0;
                this.knockBackResist = 0f;
                this.chaseable = false;
                this.alpha = 255;
                this.canGhostHeal = false;
            }
            else if (this.type == 534)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.3f;
                this.value = 0f;
                this.lavaImmune = true;
                this.netAlways = true;
                this.rarity = 2;
            }
            else if (this.type == 535)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 14;
                this.defense = 5;
                this.lifeMax = 50;
                this.scale = 1.1f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 0;
                this.value = 40f;
            }
            else if (this.type == 536)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 8;
                this.lifeMax = 200;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 1000f;
                this.rarity = 2;
            }
            else if (this.type == 537)
            {
                this.npcSlots = 2f;
                this.width = 30;
                this.height = 24;
                this.aiStyle = 1;
                this.damage = 15;
                this.defense = 5;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.alpha = 50;
                this.color = new Color(255, 250, 0, 0) * 0.2f;
                this.value = 75f;
                this.knockBackResist = 0.7f;
            }
            else if (this.type == 538)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 3563;
            }
            else if (this.type == 539)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 3564;
                this.rarity = 3;
            }
            else if (this.type == 541)
            {
                this.width = 30;
                this.height = 76;
                this.aiStyle = 102;
                this.damage = 40;
                this.defense = 30;
                this.lifeMax = 5000;
                this.HitSound = SoundID.NPCHit23;
                this.DeathSound = SoundID.NPCDeath39;
                this.knockBackResist = 0.05f;
                this.value = (float)Item.buyPrice(0, 1, 50, 0);
                this.rarity = 2;
            }
            else if (this.type == 542)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 24;
                this.aiStyle = 103;
                this.damage = 50;
                this.defense = 20;
                this.lifeMax = 360;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 400f;
                this.knockBackResist = 0.9f;
                this.behindTiles = true;
            }
            else if (this.type == 543)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 24;
                this.aiStyle = 103;
                this.damage = 60;
                this.defense = 24;
                this.lifeMax = 380;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 400f;
                this.knockBackResist = 0.8f;
                this.behindTiles = true;
            }
            else if (this.type == 544)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 24;
                this.aiStyle = 103;
                this.damage = 64;
                this.defense = 22;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 400f;
                this.knockBackResist = 0.8f;
                this.behindTiles = true;
            }
            else if (this.type == 545)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 24;
                this.aiStyle = 103;
                this.damage = 54;
                this.defense = 26;
                this.lifeMax = 450;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 400f;
                this.knockBackResist = 0.7f;
                this.behindTiles = true;
            }
            else if (this.type == 546)
            {
                this.width = 30;
                this.height = 30;
                this.aiStyle = 26;
                this.damage = 30;
                this.defense = 6;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath15;
                this.knockBackResist = 0.8f;
                this.value = 100f;
            }
            else if (this.type == 547)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 104;
                this.defense = 10;
                this.lifeMax = 10;
                this.HitSound = SoundID.NPCHit11;
                this.DeathSound = SoundID.NPCDeath15;
                this.knockBackResist = 1f;
                this.noGravity = true;
                this.noTileCollide = true;
            }
            else if (this.type == 548)
            {
                this.width = 40;
                this.height = 40;
                this.aiStyle = 105;
                this.defense = 14;
                this.lifeMax = 1000;
                this.HitSound = SoundID.DD2_CrystalCartImpact;
                this.DeathSound = SoundID.NPCDeath15;
                this.knockBackResist = 0f;
                this.friendly = true;
                this.npcSlots = 0f;
                this.hide = true;
                if (Main.hardMode && NPC.downedMechBossAny)
                {
                    this.defense = 18;
                    this.lifeMax = 3000;
                }
                if (NPC.downedGolemBoss && Main.hardMode)
                {
                    this.defense = 20;
                    this.lifeMax = 5000;
                }
                if (Main.masterMode)
                {
                    this.lifeMax *= 3;
                }
                else if (Main.expertMode)
                {
                    this.lifeMax *= 2;
                }
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 549)
            {
                this.lifeMax = 5;
                this.defense = 20;
                this.damage = 0;
                this.width = 78;
                this.height = 130;
                this.aiStyle = 106;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 0f;
                this.knockBackResist = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 0f;
                this.behindTiles = true;
                this.dontTakeDamage = true;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 552)
            {
                this.lifeMax = 30;
                this.defense = 14;
                this.damage = 18;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_GoblinHurt;
                this.DeathSound = SoundID.DD2_GoblinDeath;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 553)
            {
                this.lifeMax = 170;
                this.defense = 20;
                this.damage = 46;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_GoblinHurt;
                this.DeathSound = SoundID.DD2_GoblinDeath;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 554)
            {
                this.lifeMax = 560;
                this.defense = 28;
                this.damage = 70;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_GoblinHurt;
                this.DeathSound = SoundID.DD2_GoblinDeath;
                this.knockBackResist = 0.15f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 561)
            {
                this.lifeMax = 60;
                this.defense = 18;
                this.damage = 30;
                this.width = 26;
                this.height = 52;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_JavelinThrowersHurt;
                this.DeathSound = SoundID.DD2_JavelinThrowersDeath;
                this.knockBackResist = 0.1f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 562)
            {
                this.lifeMax = 300;
                this.defense = 28;
                this.damage = 60;
                this.width = 26;
                this.height = 52;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_JavelinThrowersHurt;
                this.DeathSound = SoundID.DD2_JavelinThrowersDeath;
                this.knockBackResist = 0.1f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 563)
            {
                this.lifeMax = 1000;
                this.defense = 38;
                this.damage = 80;
                this.width = 26;
                this.height = 52;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_JavelinThrowersHurt;
                this.DeathSound = SoundID.DD2_JavelinThrowersDeath;
                this.knockBackResist = 0.05f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 555)
            {
                this.lifeMax = 50;
                this.defense = 16;
                this.damage = 26;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_GoblinBomberHurt;
                this.DeathSound = SoundID.DD2_GoblinBomberDeath;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 556)
            {
                this.lifeMax = 200;
                this.defense = 26;
                this.damage = 55;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_GoblinBomberHurt;
                this.DeathSound = SoundID.DD2_GoblinBomberDeath;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 557)
            {
                this.lifeMax = 700;
                this.defense = 34;
                this.damage = 75;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_GoblinBomberHurt;
                this.DeathSound = SoundID.DD2_GoblinBomberDeath;
                this.knockBackResist = 0.15f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 558)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 108;
                this.damage = 30;
                this.defense = 4;
                this.lifeMax = 60;
                this.HitSound = SoundID.DD2_WyvernHurt;
                this.DeathSound = SoundID.DD2_WyvernDeath;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.2f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 559)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 108;
                this.damage = 75;
                this.defense = 16;
                this.lifeMax = 180;
                this.HitSound = SoundID.DD2_WyvernHurt;
                this.DeathSound = SoundID.DD2_WyvernDeath;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.2f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 560)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 108;
                this.damage = 100;
                this.defense = 30;
                this.lifeMax = 600;
                this.HitSound = SoundID.DD2_WyvernHurt;
                this.DeathSound = SoundID.DD2_WyvernDeath;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.05f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 550)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 576)
            {
                this.lifeMax = 5000;
                this.defense = 34;
                this.damage = 70;
                this.width = 96;
                this.height = 124;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_OgreHurt;
                this.DeathSound = SoundID.DD2_OgreDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 577)
            {
                this.lifeMax = 13000;
                this.defense = 40;
                this.damage = 90;
                this.width = 96;
                this.height = 124;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_OgreHurt;
                this.DeathSound = SoundID.DD2_OgreDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 568)
            {
                this.lifeMax = 500;
                this.defense = 30;
                this.damage = 50;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_WitherBeastHurt;
                this.DeathSound = SoundID.DD2_WitherBeastDeath;
                this.knockBackResist = 0.15f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 569)
            {
                this.lifeMax = 1400;
                this.defense = 40;
                this.damage = 80;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_WitherBeastHurt;
                this.DeathSound = SoundID.DD2_WitherBeastDeath;
                this.knockBackResist = 0.05f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 566)
            {
                this.lifeMax = 25;
                this.defense = 12;
                this.damage = 18;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_SkeletonHurt;
                this.DeathSound = SoundID.DD2_SkeletonDeath;
                this.knockBackResist = 0.3f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 567)
            {
                this.lifeMax = 480;
                this.defense = 22;
                this.damage = 70;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_SkeletonHurt;
                this.DeathSound = SoundID.DD2_SkeletonDeath;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 572)
            {
                this.lifeMax = 260;
                this.defense = 26;
                this.damage = 60;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_KoboldHurt;
                this.DeathSound = SoundID.DD2_KoboldDeath;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 573)
            {
                this.lifeMax = 800;
                this.defense = 32;
                this.damage = 80;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_KoboldHurt;
                this.DeathSound = SoundID.DD2_KoboldDeath;
                this.knockBackResist = 0.1f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 570)
            {
                this.lifeMax = 900;
                this.defense = 30;
                this.damage = 60;
                this.width = 42;
                this.height = 58;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_DrakinHurt;
                this.DeathSound = SoundID.DD2_DrakinDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 571)
            {
                this.lifeMax = 3000;
                this.defense = 40;
                this.damage = 90;
                this.width = 42;
                this.height = 58;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_DrakinHurt;
                this.DeathSound = SoundID.DD2_DrakinDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 564)
            {
                this.lifeMax = 800;
                this.defense = 18;
                this.damage = 40;
                this.width = 34;
                this.height = 62;
                this.aiStyle = 109;
                this.HitSound = SoundID.DD2_DarkMageHurt;
                this.DeathSound = SoundID.DD2_DarkMageDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.noGravity = true;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 565)
            {
                this.lifeMax = 4000;
                this.defense = 38;
                this.damage = 90;
                this.width = 34;
                this.height = 62;
                this.aiStyle = 109;
                this.HitSound = SoundID.DD2_DarkMageHurt;
                this.DeathSound = SoundID.DD2_DarkMageDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.npcSlots = 0f;
                this.noGravity = true;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 574)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 108;
                this.damage = 50;
                this.defense = 16;
                this.lifeMax = 170;
                this.HitSound = SoundID.DD2_KoboldFlyerHurt;
                this.DeathSound = SoundID.DD2_KoboldFlyerDeath;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.4f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 575)
            {
                this.width = 38;
                this.height = 38;
                this.aiStyle = 108;
                this.damage = 80;
                this.defense = 32;
                this.lifeMax = 580;
                this.HitSound = SoundID.DD2_KoboldFlyerHurt;
                this.DeathSound = SoundID.DD2_KoboldFlyerDeath;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.25f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 551)
            {
                this.damage = 80;
                this.defense = 38;
                this.lifeMax = 50000;
                this.width = 190;
                this.height = 90;
                this.aiStyle = 110;
                this.HitSound = SoundID.DD2_BetsyHurt;
                this.DeathSound = SoundID.DD2_BetsyDeath;
                this.knockBackResist = 0f;
                this.value = 0f;
                this.noGravity = true;
                this.noTileCollide = true;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 578)
            {
                this.width = 30;
                this.height = 24;
                this.aiStyle = 111;
                this.damage = 80;
                this.defense = 36;
                this.lifeMax = 500;
                this.HitSound = SoundID.DD2_LightningBugHurt;
                this.DeathSound = SoundID.DD2_LightningBugDeath;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0.8f;
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
            }
            else if (this.type == 579)
            {
                this.friendly = true;
                this.width = 34;
                this.height = 8;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.scale = 1f;
                this.rarity = 1;
            }
            else if (this.type == 582)
            {
                this.width = 18;
                this.height = 18;
                this.aiStyle = 3;
                this.damage = 10;
                this.defense = 2;
                this.lifeMax = 30;
                this.HitSound = SoundID.NPCHit31;
                this.DeathSound = SoundID.NPCDeath34;
                this.knockBackResist = 0.75f;
                this.value = 40f;
                this.npcSlots = 0.4f;
            }
            else if (this.type == 583 || this.type == 584 || this.type == 585)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 112;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                switch (this.type)
                {
                case 583:
                    this.catchItem = 4068;
                    break;
                case 584:
                    this.catchItem = 4069;
                    break;
                case 585:
                    this.catchItem = 4070;
                    break;
                }
                this.noGravity = true;
                this.rarity = 2;
            }
            else if (this.type == 586)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 40;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit18;
                this.DeathSound = SoundID.NPCDeath21;
                this.knockBackResist = 0f;
                this.value = 1000f;
                this.alpha = 255;
                this.rarity = 1;
            }
            else if (this.type == 587)
            {
                this.width = 32;
                this.height = 18;
                this.aiStyle = 44;
                this.damage = 35;
                this.defense = 18;
                this.lifeMax = 300;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0f;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 1000f;
                this.alpha = 255;
                this.rarity = 1;
            }
            else if (this.type == 588)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 589)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 34;
                this.aiStyle = 0;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.rarity = 1;
            }
            else if (this.type == 590 || this.type == 591)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 60f;
            }
            else if (this.type == 592)
            {
                this.noGravity = true;
                this.width = 20;
                this.height = 18;
                this.aiStyle = 16;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.catchItem = 4274;
                this.rarity = 3;
            }
            else if (this.type == 593)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 4274;
                this.rarity = 3;
            }
            else if (this.type == 594)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 113;
                this.damage = 0;
                this.defense = 0;
                this.knockBackResist = 0.3f;
                this.lifeMax = 1;
                this.DeathSound = SoundID.NPCDeath63;
                this.value = 0f;
                this.noGravity = true;
            }
            else if (this.type >= 595 && this.type <= 601)
            {
                this.timeLeft *= 3;
                this.width = 10;
                this.height = 10;
                this.aiStyle = 114;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                int num2 = this.type;
                if (num2 == 601)
                {
                    this.rarity = 3;
                }
                this.catchItem = (short)(this.type - 595 + 4334);
            }
            else if (this.type == 602)
            {
                this.width = 22;
                this.height = 26;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 4359;
            }
            else if (this.type == 603)
            {
                this.width = 28;
                this.height = 22;
                this.aiStyle = 68;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 4359;
            }
            else if (this.type == 604 || this.type == 605)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 115;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                int num2 = this.type;
                if (num2 == 605)
                {
                    this.rarity = 3;
                }
                this.catchItem = (short)(this.type - 604 + 4361);
            }
            else if (this.type == 606)
            {
                this.width = 10;
                this.height = 4;
                this.aiStyle = 66;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.1f;
                this.catchItem = 4363;
                this.friendly = true;
            }
            else if (this.type == 607)
            {
                this.noGravity = true;
                this.width = 20;
                this.height = 18;
                this.aiStyle = 16;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.catchItem = 4373;
            }
            else if (this.type == 608)
            {
                this.width = 22;
                this.height = 26;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 4374;
            }
            else if (this.type == 609)
            {
                this.width = 28;
                this.height = 22;
                this.aiStyle = 68;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 4374;
            }
            else if (this.type == 610)
            {
                this.width = 14;
                this.height = 12;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath4;
                this.npcSlots = 0.25f;
                this.catchItem = 4375;
            }
            else if (this.type == 611)
            {
                this.width = 18;
                this.height = 34;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 4395;
                this.npcSlots = 0.4f;
            }
            else if (this.type == 612 || this.type == 613)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 116;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                int num2 = this.type;
                if (num2 == 613)
                {
                    this.rarity = 3;
                }
                this.catchItem = (short)(this.type - 612 + 4418);
                this.waterMovementSpeed = 1f;
                this.lavaMovementSpeed = 1f;
                this.honeyMovementSpeed = 1f;
            }
            else if (this.type == 614)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = null;
                this.catchItem = 1338;
            }
            else if (this.type == 615)
            {
                this.noGravity = true;
                this.width = 20;
                this.height = 18;
                this.aiStyle = 16;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 616 || this.type == 617)
            {
                this.width = 22;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.catchItem = (short)(this.type - 616 + 4464);
            }
            else if (this.type == 618)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 100;
                this.aiStyle = 117;
                this.damage = 55;
                this.defense = 24;
                this.lifeMax = 7000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.value = (float)Item.buyPrice(0, 2, 0, 0);
                this.noTileCollide = true;
                this.rarity = 1;
            }
            else if (this.type == 619)
            {
                this.npcSlots = 1f;
                this.width = 44;
                this.height = 44;
                this.aiStyle = 5;
                this.damage = 60;
                this.defense = 16;
                this.lifeMax = 750;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.knockBackResist = 0f;
                this.value = 500f;
                this.alpha = 255;
            }
            else if (this.type == 620)
            {
                this.lifeMax = 5000;
                this.defense = 30;
                this.damage = 70;
                this.width = 34;
                this.height = 58;
                this.aiStyle = 107;
                this.HitSound = SoundID.DD2_DrakinHurt;
                this.DeathSound = SoundID.DD2_DrakinDeath;
                this.knockBackResist = 0f;
                this.value = (float)Item.buyPrice(0, 0, 75, 0);
                this.npcSlots = 0f;
                this.lavaImmune = true;
                this.LazySetLiquidMovementDD2();
                this.netAlways = true;
                this.alpha = 255;
                this.rarity = 1;
            }
            else if (this.type == 621)
            {
                this.npcSlots = 5f;
                this.width = 28;
                this.height = 28;
                this.aiStyle = 6;
                this.damage = 90;
                this.defense = 0;
                this.lifeMax = 6000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.value = (float)Item.buyPrice(0, 0, 75, 0);
                this.alpha = 255;
                this.rarity = 1;
            }
            else if (this.type == 622)
            {
                this.width = 28;
                this.height = 28;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 60;
                this.defense = 30;
                this.lifeMax = 6000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.dontCountMe = true;
                this.npcSlots = 0f;
                this.alpha = 255;
            }
            else if (this.type == 623)
            {
                this.width = 28;
                this.height = 28;
                this.aiStyle = 6;
                this.netAlways = true;
                this.damage = 50;
                this.defense = 40;
                this.lifeMax = 6000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.behindTiles = true;
                this.dontCountMe = true;
                this.npcSlots = 0f;
                this.alpha = 255;
            }
            else if (this.type == 624)
            {
                this.width = 14;
                this.height = 30;
                this.aiStyle = 3;
                this.damage = 10;
                this.defense = 0;
                this.lifeMax = 25;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 1f;
                this.rarity = 1;
            }
            else if (this.type == 625)
            {
                this.width = 22;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 626 || this.type == 627)
            {
                this.width = 16;
                this.height = 20;
                this.aiStyle = 118;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 1f;
                int num2 = this.type;
                if (num2 == 627)
                {
                    this.rarity = 3;
                }
                this.catchItem = 4480;
                if (this.type == 627)
                {
                    this.catchItem = 4482;
                }
            }
            else if (this.type == 628)
            {
                this.width = 22;
                this.height = 40;
                this.aiStyle = 119;
                this.damage = 15;
                this.defense = 0;
                this.lifeMax = 50;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0f;
                this.value = 50f;
            }
            else if (this.type == 629)
            {
                this.width = 24;
                this.height = 24;
                this.aiStyle = 25;
                this.damage = 80;
                this.defense = 30;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit4;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 100000f;
                this.knockBackResist = 0.3f;
                this.rarity = 4;
                this.coldDamage = true;
                if (!Main.hardMode)
                {
                    this.damage = 30;
                    this.defense = 12;
                    this.lifeMax = 300;
                    this.value = (float)Item.buyPrice(0, 2, 0, 0);
                }
            }
            else if (this.type == 630)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 60;
                this.defense = 18;
                this.lifeMax = 180;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.value = 700f;
            }
            else if (this.type == 631)
            {
                this.width = 36;
                this.height = 48;
                this.scale = 1.1f;
                this.aiStyle = 3;
                this.damage = 85;
                this.defense = 35;
                this.lifeMax = 1000;
                this.HitSound = SoundID.NPCHit41;
                this.DeathSound = SoundID.NPCDeath43;
                this.knockBackResist = 0.1f;
                this.value = 25000f;
            }
            else if (this.type == 632)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 14;
                this.defense = 6;
                this.lifeMax = 45;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 60f;
            }
            else if (this.type == 633)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 634)
            {
                this.npcSlots = 0.5f;
                this.width = 22;
                this.height = 18;
                this.aiStyle = 14;
                this.damage = 13;
                this.defense = 2;
                this.lifeMax = 16;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath4;
                this.value = 90f;
            }
            else if (this.type == 635)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 20;
                this.defense = 8;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.5f;
                this.value = 100f;
            }
            else if (this.type == 636)
            {
                this.noGravity = true;
                this.width = 100;
                this.height = 100;
                this.aiStyle = 120;
                this.damage = 80;
                this.defense = 50;
                this.lifeMax = 70000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath65;
                this.knockBackResist = 0f;
                this.value = 250000f;
                this.noTileCollide = true;
                this.boss = true;
                this.Opacity = 0f;
                this.dontTakeDamage = true;
                this.npcSlots = 16f;
            }
            else if (this.type == 637 || this.type == 638)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 28;
                if (this.type == 637)
                {
                    this.height = 20;
                }
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.housingCategory = 1;
            }
            else if (this.type >= 639 && this.type <= 645)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = (short)(4831 + (this.type - 639));
            }
            else if (this.type >= 646 && this.type <= 652)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = (short)(4838 + (this.type - 646));
            }
            else if (this.type == 653)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 65;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                this.lavaImmune = true;
                this.catchItem = 4845;
            }
            else if (this.type == 654)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 64;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.2f;
                this.noGravity = true;
                this.lavaImmune = true;
                this.catchItem = 4847;
            }
            else if (this.type == 655)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 67;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.5f;
                this.noGravity = true;
                this.lavaImmune = true;
                this.catchItem = 4849;
            }
            else if (this.type == 656)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.housingCategory = 1;
            }
            else if (this.type == 657)
            {
                this.width = 114;
                this.height = 100;
                this.aiStyle = 121;
                this.damage = 60;
                this.defense = 26;
                this.lifeMax = 18000;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath64;
                this.lavaImmune = true;
                this.knockBackResist = 0f;
                this.value = 60000f;
                this.boss = true;
                this.npcSlots = 5f;
            }
            else if (this.type == 658 || this.type == 659)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 40;
                this.defense = 35;
                this.lifeMax = 150;
                this.scale = 1f;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
            }
            else if (this.type == 660)
            {
                this.width = 40;
                this.height = 30;
                this.aiStyle = 14;
                this.damage = 50;
                this.defense = 30;
                this.lifeMax = 120;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.8f;
                this.scale = 1f;
            }
            else if (this.type == 661)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 65;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                this.lavaImmune = true;
                this.catchItem = 4961;
                this.rarity = 4;
            }
            else if (this.type == 662)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 122;
                this.damage = 75;
                this.defense = 22;
                this.lifeMax = 500;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.2f;
                this.value = 0f;
                this.noTileCollide = true;
                this.lavaImmune = true;
                this.trapImmune = true;
                this.noGravity = true;
            }
            else if (this.type == 663)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 40;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
            }
            else if (this.type == 664)
            {
                this.lifeMax = 20;
                this.boss = true;
            }
            else if (this.type == 665)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 9;
                this.damage = 20;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = SoundID.NPCHit3;
                this.DeathSound = SoundID.NPCDeath3;
                this.noGravity = true;
                this.noTileCollide = true;
                this.alpha = 100;
                this.knockBackResist = 0f;
            }
            else if (this.type == 666)
            {
                this.width = 16;
                this.height = 16;
                this.aiStyle = 9;
                this.damage = 65;
                this.defense = 0;
                this.lifeMax = 1;
                this.HitSound = null;
                this.DeathSound = SoundID.NPCDeath9;
                this.noGravity = true;
                this.noTileCollide = true;
                this.knockBackResist = 0f;
                this.scale = 0.9f;
                this.alpha = 80;
            }
            else if (this.type == 667)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 5;
                this.defense = 5;
                this.lifeMax = 300;
                this.knockBackResist *= 1.4f;
                this.rarity = 2;
                this.scale = 1f;
                this.value = (float)Item.buyPrice(0, 15, 0, 0);
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
            }
            else if (this.type == 668)
            {
                this.width = 60;
                this.height = 154;
                this.aiStyle = 123;
                this.damage = 20;
                this.defense = 10;
                this.lifeMax = 7000;
                this.HitSound = SoundID.DeerclopsHit;
                this.DeathSound = SoundID.DeerclopsDeath;
                this.knockBackResist = 0f;
                this.boss = true;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = (float)Item.buyPrice(0, 5, 0, 0);
                this.npcSlots = 10f;
                this.coldDamage = true;
            }
            else if (this.type == 669)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 115;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.25f;
                this.noGravity = true;
                this.catchItem = 5132;
            }
            else if (this.type == 670)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.housingCategory = 1;
            }
            else if (this.type == 671)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 5212;
                this.npcSlots = 1f;
            }
            else if (this.type == 672)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 5300;
                this.npcSlots = 1f;
            }
            else if (this.type == 673)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 5311;
                this.npcSlots = 1f;
            }
            else if (this.type == 674)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 5312;
                this.npcSlots = 1f;
            }
            else if (this.type == 675)
            {
                this.width = 14;
                this.height = 14;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.catchItem = 5313;
                this.npcSlots = 1f;
            }
            else if (this.type == 676)
            {
                this.width = 24;
                this.height = 18;
                this.aiStyle = 1;
                this.damage = 20;
                this.defense = 5;
                this.lifeMax = 80;
                this.scale = 1f;
                this.value = (float)Item.buyPrice(0, 0, 1, 50);
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
            }
            else if (this.type == 677)
            {
                this.width = 10;
                this.height = 10;
                this.aiStyle = 64;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.2f;
                this.noGravity = true;
                this.catchItem = 5350;
                this.noTileCollide = true;
            }
            else if (this.type == 678 || this.type == 679 || this.type == 680 || this.type == 681 || this.type == 682 || this.type == 683 || this.type == 684)
            {
                this.townNPC = true;
                this.friendly = true;
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 10;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.knockBackResist = 0.5f;
                this.housingCategory = 1;
            }
            else if (this.type == 685)
            {
                this.width = 30;
                this.height = 28;
                this.aiStyle = 1;
                this.damage = 0;
                this.defense = 10;
                this.knockBackResist = 0.3f;
                this.lifeMax = 250;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.value = 0f;
                this.rarity = 2;
                this.friendly = true;
            }
            else if (this.type == 686)
            {
                this.width = 20;
                this.height = 20;
                this.aiStyle = 125;
                this.damage = 0;
                this.defense = 0;
                this.knockBackResist = 0.3f;
                this.lifeMax = 1;
                this.DeathSound = SoundID.NPCDeath63;
                this.value = 0f;
                this.rarity = 2;
                this.noGravity = true;
                this.noTileCollide = true;
                this.dontTakeDamageFromHostiles = true;
            }
            else if (this.type == 687)
            {
                this.width = 18;
                this.height = 20;
                this.aiStyle = 7;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.rarity = 2;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath6;
                this.catchItem = 2121;
            }
            else if (this.type == 688)
            {
                this.noGravity = true;
                this.width = 32;
                this.height = 16;
                this.aiStyle = 16;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.knockBackResist = 0.5f;
                this.catchItem = 5511;
            }
            else if (this.type == 689)
            {
                this.width = 18;
                this.height = 34;
                this.aiStyle = 24;
                this.damage = 0;
                this.defense = 0;
                this.lifeMax = 5;
                this.HitSound = SoundID.NPCHit1;
                this.knockBackResist = 0.8f;
                this.DeathSound = SoundID.NPCDeath1;
                this.npcSlots = 0.4f;
            }
            else if (this.type == 690)
            {
                this.lavaImmune = true;
                this.immortal = true;
                this.dontTakeDamage = true;
                this.width = 28;
                this.height = 38;
                this.aiStyle = 126;
                this.damage = 40;
                this.defense = 10;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit58;
                this.DeathSound = SoundID.NPCDeath67;
                this.knockBackResist = 0f;
                this.npcSlots = 0f;
            }
            else if (this.type == 691)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 3;
                this.damage = 18;
                this.defense = 10;
                this.lifeMax = 60;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.45f;
                this.value = 80f;
            }
            else if (this.type == 692)
            {
                this.noGravity = true;
                this.width = 120;
                this.height = 34;
                this.aiStyle = 16;
                this.damage = 50;
                this.defense = 20;
                this.lifeMax = 400;
                this.HitSound = SoundID.NPCHit1;
                this.DeathSound = SoundID.NPCDeath1;
                this.value = 10000f;
                this.knockBackResist = 0.7f;
            }
            else if (this.type == 693)
            {
                this.width = 18;
                this.height = 40;
                this.aiStyle = 8;
                this.damage = 18;
                this.defense = 2;
                this.lifeMax = 70;
                this.HitSound = SoundID.NPCHit2;
                this.DeathSound = SoundID.NPCDeath2;
                this.knockBackResist = 0.6f;
                this.value = 160f;
                this.npcSlots = 2f;
            }
            else if (this.type == 694)
            {
                this.width = 44;
                this.height = 44;
                this.aiStyle = 10;
                this.damage = 20;
                this.defense = 4;
                this.lifeMax = 60;
                this.HitSound = SoundID.DD2_BookStaffCast;
                this.DeathSound = SoundID.NPCDeath52;
                this.noGravity = true;
                this.noTileCollide = true;
                this.value = 150f;
                this.knockBackResist = 0.2f;
            }
            else if (this.type == 695)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 18;
                this.aiStyle = 127;
                this.damage = 0;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.PalCattivaPain;
                this.DeathSound = SoundID.PalCattivaPain;
                this.knockBackResist = 0.5f;
                this.rarity = 1;
            }
            else if (this.type == 696)
            {
                this.friendly = true;
                this.width = 18;
                this.height = 18;
                this.aiStyle = 127;
                this.damage = 0;
                this.defense = 15;
                this.lifeMax = 250;
                this.HitSound = SoundID.PalFoxparksPain;
                this.DeathSound = SoundID.PalFoxparksPain;
                this.knockBackResist = 0.5f;
                this.rarity = 1;
            }
            if (Main.dedServ)
            {
                this.frame = default(Rectangle);
            }
            else if (TextureAssets.Npc[this.type] != null && TextureAssets.Npc[this.type].IsLoaded)
            {
                this.frame = new Rectangle(0, 0, TextureAssets.Npc[this.type].Width(), TextureAssets.Npc[this.type].Height() / Main.npcFrameCount[this.type]);
            }
            else
            {
                this.setFrameSize = true;
            }
            if (spawnparams.sizeScaleOverride != null)
            {
                int num3 = (int)((float)this.width * this.scale);
                int num4 = (int)((float)this.height * this.scale);
                this.position.X = this.position.X + (float)(num3 / 2);
                this.position.Y = this.position.Y + (float)num4;
                this.scale = spawnparams.sizeScaleOverride.Value;
                this.width = (int)((float)this.width * this.scale);
                this.height = (int)((float)this.height * this.scale);
                if (this.height == 16 || this.height == 32)
                {
                    this.height++;
                }
                this.position.X = this.position.X - (float)(this.width / 2);
                this.position.Y = this.position.Y - (float)this.height;
            }
            else
            {
                this.width = (int)((float)this.width * this.scale);
                this.height = (int)((float)this.height * this.scale);
            }
            this.life = this.lifeMax;
            this.defDamage = this.damage;
            this.defDefense = this.defense;
            this.defLifeMax = this.lifeMax;
            this.netID = this.type;
            NPCDebuffImmunityData npcdebuffImmunityData;
            if (NPCID.Sets.DebuffImmunitySets.TryGetValue(this.type, out npcdebuffImmunityData) && npcdebuffImmunityData != null)
            {
                npcdebuffImmunityData.ApplyToNPC(this);
            }
            else
            {
                for (int m = 0; m < this.buffImmune.Length; m++)
                {
                    this.buffImmune[m] = false;
                }
            }
            if (this.buffImmune[20])
            {
                this.buffImmune[30] = true;
                this.buffImmune[375] = this.buffImmune[30];
            }
            if (this.buffImmune[69])
            {
                this.buffImmune[36] = true;
            }
            this.buffImmune[353] = NPCID.Sets.ShimmerImmunity[this.type];
            if (Main.zenithWorld)
            {
                this.getZenithSeedAdjustmentsBeforeEverything();
            }
            if (Main.getGoodWorld)
            {
                this.getGoodAdjustments();
            }
            else if (Main.tenthAnniversaryWorld)
            {
                this.getTenthAnniversaryAdjustments();
            }
            if (this.type >= 0 && this.type < (int)NPCID.Count && Main.npcCatchable[this.type])
            {
                this.catchableNPCTempImmunityCounter = 90;
                this.friendly = true;
            }
            this.ScaleStats(spawnparams.playerCountForMultiplayerDifficultyOverride, spawnparams.difficultyOverride);
            this.life = this.lifeMax;
        }
References Terraria.NPC.activeTime, Terraria.NPC.ai, Terraria.DataStructures.NPCDebuffImmunityData.ApplyToNPC(), Terraria.NPC.buffImmune, Terraria.Item.buyPrice(), Microsoft.Xna.Framework.Graphics.Color, Terraria.ID.BuffID.Count, Terraria.ID.NPCID.Count, Terraria.NPC.damage, Terraria.ID.SoundID.DD2_BetsyDeath, Terraria.ID.SoundID.DD2_BetsyHurt, Terraria.ID.SoundID.DD2_BookStaffCast, Terraria.ID.SoundID.DD2_CrystalCartImpact, Terraria.ID.SoundID.DD2_DarkMageDeath, Terraria.ID.SoundID.DD2_DarkMageHurt, Terraria.ID.SoundID.DD2_DrakinDeath, Terraria.ID.SoundID.DD2_DrakinHurt, Terraria.ID.SoundID.DD2_GoblinBomberDeath, Terraria.ID.SoundID.DD2_GoblinBomberHurt, Terraria.ID.SoundID.DD2_GoblinDeath, Terraria.ID.SoundID.DD2_GoblinHurt, Terraria.ID.SoundID.DD2_JavelinThrowersDeath, Terraria.ID.SoundID.DD2_JavelinThrowersHurt, Terraria.ID.SoundID.DD2_KoboldDeath, Terraria.ID.SoundID.DD2_KoboldFlyerDeath, Terraria.ID.SoundID.DD2_KoboldFlyerHurt, Terraria.ID.SoundID.DD2_KoboldHurt, Terraria.ID.SoundID.DD2_LightningBugDeath, Terraria.ID.SoundID.DD2_LightningBugHurt, Terraria.ID.SoundID.DD2_OgreDeath, Terraria.ID.SoundID.DD2_OgreHurt, Terraria.ID.SoundID.DD2_SkeletonDeath, Terraria.ID.SoundID.DD2_SkeletonHurt, Terraria.ID.SoundID.DD2_WitherBeastDeath, Terraria.ID.SoundID.DD2_WitherBeastHurt, Terraria.ID.SoundID.DD2_WyvernDeath, Terraria.ID.SoundID.DD2_WyvernHurt, Terraria.ID.NPCID.Sets.DebuffImmunitySets, Terraria.Main.dedServ, Terraria.ID.SoundID.DeerclopsDeath, Terraria.ID.SoundID.DeerclopsHit, Terraria.NPC.defense, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedMechBossAny, Terraria.Main.expertMode, Terraria.NPC.getGoodAdjustments(), Terraria.Main.getGoodWorld, Terraria.NPC.getTenthAnniversaryAdjustments(), Terraria.NPC.getZenithSeedAdjustmentsBeforeEverything(), Terraria.Main.hardMode, Terraria.Entity.height, int, Terraria.NPC.IsABestiaryIconDummy, ReLogic.Content.Asset< T >.IsLoaded, Terraria.NPC.LazySetLiquidMovementDD2(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.NPC.lifeMax, Terraria.NPC.localAI, Terraria.Main.masterMode, Terraria.NPC.maxAI, Terraria.GameContent.TextureAssets.Npc, Terraria.Main.npcCatchable, Terraria.ID.SoundID.NPCDeath1, Terraria.ID.SoundID.NPCDeath10, Terraria.ID.SoundID.NPCDeath11, Terraria.ID.SoundID.NPCDeath12, Terraria.ID.SoundID.NPCDeath14, Terraria.ID.SoundID.NPCDeath15, Terraria.ID.SoundID.NPCDeath16, Terraria.ID.SoundID.NPCDeath17, Terraria.ID.SoundID.NPCDeath18, Terraria.ID.SoundID.NPCDeath19, Terraria.ID.SoundID.NPCDeath2, Terraria.ID.SoundID.NPCDeath20, Terraria.ID.SoundID.NPCDeath21, Terraria.ID.SoundID.NPCDeath22, Terraria.ID.SoundID.NPCDeath23, Terraria.ID.SoundID.NPCDeath24, Terraria.ID.SoundID.NPCDeath25, Terraria.ID.SoundID.NPCDeath26, Terraria.ID.SoundID.NPCDeath27, Terraria.ID.SoundID.NPCDeath28, Terraria.ID.SoundID.NPCDeath29, Terraria.ID.SoundID.NPCDeath3, Terraria.ID.SoundID.NPCDeath30, Terraria.ID.SoundID.NPCDeath31, Terraria.ID.SoundID.NPCDeath32, Terraria.ID.SoundID.NPCDeath33, Terraria.ID.SoundID.NPCDeath34, Terraria.ID.SoundID.NPCDeath35, Terraria.ID.SoundID.NPCDeath36, Terraria.ID.SoundID.NPCDeath37, Terraria.ID.SoundID.NPCDeath38, Terraria.ID.SoundID.NPCDeath39, Terraria.ID.SoundID.NPCDeath4, Terraria.ID.SoundID.NPCDeath40, Terraria.ID.SoundID.NPCDeath41, Terraria.ID.SoundID.NPCDeath42, Terraria.ID.SoundID.NPCDeath43, Terraria.ID.SoundID.NPCDeath44, Terraria.ID.SoundID.NPCDeath45, Terraria.ID.SoundID.NPCDeath46, Terraria.ID.SoundID.NPCDeath47, Terraria.ID.SoundID.NPCDeath48, Terraria.ID.SoundID.NPCDeath49, Terraria.ID.SoundID.NPCDeath5, Terraria.ID.SoundID.NPCDeath50, Terraria.ID.SoundID.NPCDeath51, Terraria.ID.SoundID.NPCDeath52, Terraria.ID.SoundID.NPCDeath53, Terraria.ID.SoundID.NPCDeath54, Terraria.ID.SoundID.NPCDeath55, Terraria.ID.SoundID.NPCDeath56, Terraria.ID.SoundID.NPCDeath57, Terraria.ID.SoundID.NPCDeath59, Terraria.ID.SoundID.NPCDeath6, Terraria.ID.SoundID.NPCDeath60, Terraria.ID.SoundID.NPCDeath62, Terraria.ID.SoundID.NPCDeath63, Terraria.ID.SoundID.NPCDeath64, Terraria.ID.SoundID.NPCDeath65, Terraria.ID.SoundID.NPCDeath66, Terraria.ID.SoundID.NPCDeath67, Terraria.ID.SoundID.NPCDeath7, Terraria.ID.SoundID.NPCDeath8, Terraria.ID.SoundID.NPCDeath9, Terraria.Main.npcFrameCount, Terraria.ID.SoundID.NPCHit1, Terraria.ID.SoundID.NPCHit11, Terraria.ID.SoundID.NPCHit12, Terraria.ID.SoundID.NPCHit13, Terraria.ID.SoundID.NPCHit14, Terraria.ID.SoundID.NPCHit15, Terraria.ID.SoundID.NPCHit18, Terraria.ID.SoundID.NPCHit19, Terraria.ID.SoundID.NPCHit2, Terraria.ID.SoundID.NPCHit20, Terraria.ID.SoundID.NPCHit21, Terraria.ID.SoundID.NPCHit22, Terraria.ID.SoundID.NPCHit23, Terraria.ID.SoundID.NPCHit24, Terraria.ID.SoundID.NPCHit25, Terraria.ID.SoundID.NPCHit26, Terraria.ID.SoundID.NPCHit27, Terraria.ID.SoundID.NPCHit28, Terraria.ID.SoundID.NPCHit29, Terraria.ID.SoundID.NPCHit3, Terraria.ID.SoundID.NPCHit30, Terraria.ID.SoundID.NPCHit31, Terraria.ID.SoundID.NPCHit32, Terraria.ID.SoundID.NPCHit33, Terraria.ID.SoundID.NPCHit34, Terraria.ID.SoundID.NPCHit35, Terraria.ID.SoundID.NPCHit36, Terraria.ID.SoundID.NPCHit37, Terraria.ID.SoundID.NPCHit38, Terraria.ID.SoundID.NPCHit39, Terraria.ID.SoundID.NPCHit4, Terraria.ID.SoundID.NPCHit40, Terraria.ID.SoundID.NPCHit41, Terraria.ID.SoundID.NPCHit42, Terraria.ID.SoundID.NPCHit43, Terraria.ID.SoundID.NPCHit44, Terraria.ID.SoundID.NPCHit45, Terraria.ID.SoundID.NPCHit46, Terraria.ID.SoundID.NPCHit47, Terraria.ID.SoundID.NPCHit48, Terraria.ID.SoundID.NPCHit49, Terraria.ID.SoundID.NPCHit5, Terraria.ID.SoundID.NPCHit50, Terraria.ID.SoundID.NPCHit51, Terraria.ID.SoundID.NPCHit52, Terraria.ID.SoundID.NPCHit53, Terraria.ID.SoundID.NPCHit54, Terraria.ID.SoundID.NPCHit55, Terraria.ID.SoundID.NPCHit56, Terraria.ID.SoundID.NPCHit57, Terraria.ID.SoundID.NPCHit58, Terraria.ID.SoundID.NPCHit6, Terraria.ID.SoundID.NPCHit7, Terraria.ID.SoundID.NPCHit8, Terraria.ID.SoundID.NPCHit9, Terraria.NPC.oldPos, Terraria.NPC.oldRot, Terraria.ID.SoundID.PalCattivaPain, Terraria.ID.SoundID.PalFoxparksPain, Terraria.Main.remixWorld, Terraria.NPC.scale, Terraria.NPC.ScaleStats(), Terraria.NPC.SetDefaultsFromNetId(), Terraria.ID.NPCID.Sets.ShimmerImmunity, Terraria.NPC.target, Terraria.Main.tenthAnniversaryWorld, Terraria.ID.NPCID.Sets.TrailCacheLength, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Terraria.NPC.type, Terraria.NPC.value, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.Main.zenithWorld.
Referenced by Terraria.GameContent.Bestiary.BestiaryDatabaseNPCsPopulator.AdjustPirateShipStats(), Terraria.NPC.AI_015_KingSlime(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_121_QueenSlime(), Terraria.Main.DrawNPCPortrait(), Terraria.ID.ContentSamples.FillNpcRarities(), Terraria.MessageBuffer.GetData(), Terraria.NPC.HitEffect(), Terraria.ID.ContentSamples.Initialize(), Terraria.Player.ItemCheck_UseTorchGodsFavor(), Terraria.IO.WorldFile.LoadNPCs(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.NPC.NewNPC(), Terraria.PopupText.NewText(), Terraria.GameContent.Bestiary.NPCKillCounterInfoElement.NPCKillCounterInfoElement(), Terraria.GameContent.Animations.Segments.NPCSegment.NPCSegment(), Terraria.Player.OpenBossBag(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.RefreshStats(), Terraria.GameContent.LeashedEntities.LeashedCritter.SetDefaults(), Terraria.NPC.SetDefaults_ForNetId(), Terraria.NPC.SetDefaultsFromNetId(), Terraria.Player.Spawn(), Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.SpawnEnemy(), Terraria.GameContent.LootSimulation.LootSimulator.TryGettingLootFor(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.UnlockableNPCEntryIcon(), Terraria.GameContent.UI.BigProgressBar.BrainOfCthuluBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.EaterOfWorldsProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.GolemHeadProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.MartianSaucerBigProgressBar.ValidateAndCollectNecessaryInfo(), Terraria.GameContent.UI.BigProgressBar.MoonLordProgressBar.ValidateAndCollectNecessaryInfo(), and Terraria.GameContent.UI.BigProgressBar.PirateShipBigProgressBar.ValidateAndCollectNecessaryInfo().