Terraria Decompiled: Terraria.NPC.UpdateNetworkCode
UpdateNetworkCode()
void Terraria.NPC.UpdateNetworkCode (int i) inline private
Definition at line 91447 of file NPC.cs.
        {
            this.whoAmI = i;
            if (!this.active)
            {
                this.netUpdate = true;
            }
            if (Main.netMode == 2)
            {
                if (this.townNPC)
                {
                    this.netSpam = Math.Min(this.netSpam, this.netSpamTicksPerPacket);
                }
                if (!this.active)
                {
                    this.netSpam = 0;
                }
                if (this.netUpdate || this.netUpdatePendingSpamCooldown || (this.netUpdatePendingFullSpamCooldown && this.netSpam == 0))
                {
                    int num = (this.boss ? this.netSpamTicksPerPacketForBosses : this.netSpamTicksPerPacket);
                    if (this.netSpam <= this.netSpamPacketLimit * num)
                    {
                        this.netSpam += num;
                        NetMessage.SendData(23, -1, -1, null, this.whoAmI, 0f, 0f, 0f, 0, 0, 0);
                    }
                    else
                    {
                        this.netUpdatePendingSpamCooldown = true;
                    }
                }
                if (this.netSpam > 0)
                {
                    this.netSpam--;
                }
                this.RecheckSectionsForSkippedUpdates();
                this.StreamUpdatesToNearbyPlayers();
                if (this.active && this.townNPC && NPC.TypeToDefaultHeadIndex(this.type) > 0)
                {
                    if (this.homeless != this.oldHomeless || this.homeTileX != this.oldHomeTileX || this.homeTileY != this.oldHomeTileY)
                    {
                        byte householdStatus = WorldGen.TownManager.GetHouseholdStatus(this);
                        NetMessage.SendData(60, -1, -1, null, this.whoAmI, (float)this.homeTileX, (float)this.homeTileY, (float)householdStatus, 0, 0, 0);
                    }
                    this.oldHomeless = this.homeless;
                    this.oldHomeTileX = this.homeTileX;
                    this.oldHomeTileY = this.homeTileY;
                }
            }
        }
References Terraria.GameContent.TownRoomManager.GetHouseholdStatus(), System.Math.Min(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.WorldGen.TownManager, and Terraria.NPC.TypeToDefaultHeadIndex().