Terraria Decompiled: Terraria.NPC.StingerExplosion
StingerExplosion()
void Terraria.NPC.StingerExplosion () inline private
Definition at line 49731 of file NPC.cs.
        {
            int num = Main.rand.Next(4, 9);
            for (int i = 0; i < num; i++)
            {
                float num2 = 8f;
                Vector2 vector = new Vector2(Main.rand.NextFloat() - 0.5f, Main.rand.NextFloat() - 0.5f);
                vector.Normalize();
                vector *= num2;
                int num3 = (int)(10f * this.scale);
                if (this.type == 176)
                {
                    num3 = (int)(30f * this.scale);
                }
                int num4 = 55;
                int num5 = Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, vector.X, vector.Y, num4, num3, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                Main.projectile[num5].timeLeft = 300;
            }
        }
References Terraria.NPC.GetSpawnSource_ForProjectile(), int, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Vector2.Normalize(), Terraria.Main.projectile, Terraria.Main.rand, Terraria.NPC.scale, Terraria.Projectile.timeLeft, Terraria.NPC.type, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.checkDead().