Terraria Decompiled: Terraria.NPC.SpawnOnPlayer
SpawnOnPlayer()
static void Terraria.NPC.SpawnOnPlayer (int plr, int npcType, float ai0 = 0f, float ai1 = 0f, float ai2 = 0f, float ai3 = 0f) inline static
Definition at line 79501 of file NPC.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            if (npcType == 262 && NPC.AnyNPCs(262))
            {
                return;
            }
            if (npcType == 245)
            {
                if (NPC.AnyNPCs(245))
                {
                    return;
                }
                try
                {
                    int num = (int)Main.player[plr].Center.X / 16;
                    int num2 = (int)Main.player[plr].Center.Y / 16;
                    int num3 = 0;
                    int num4 = 0;
                    for (int i = num - 20; i < num + 20; i++)
                    {
                        for (int j = num2 - 20; j < num2 + 20; j++)
{
                            if (Main.tile[i, j].active() && Main.tile[i, j].type == 237 && Main.tile[i, j].frameX == 18 && Main.tile[i, j].frameY == 0)
{
                                num3 = i;
                                num4 = j;
                            }
                        }
                    }
                    if (num3 > 0 && num4 > 0)
                    {
                        int num5 = num4 - 15;
                        int num6 = num4 - 15;
                        for (int k = num4; k > num4 - 50; k--)
{
                            if (WorldGen.SolidTile(num3, k, false))
{
                                num5 = k;
                                break;
                            }
                        }
                        for (int l = num4; l < num4 + 50; l++)
{
                            if (WorldGen.SolidTile(num3, l, false))
{
                                num6 = l;
                                break;
                            }
                        }
                        num4 = (num5 + num5 + num6) / 3;
                        int num7 = NPC.NewNPC(NPC.GetBossSpawnSource(plr), num3 * 16 + 8, num4 * 16, npcType, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num7].target = plr;
                        ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { Main.npc[num7].GetTypeNetName() }), ChatColors.BossOrEvent, -1);
                    }
                }
                catch
                {
                }
                return;
            }
            else if (npcType == 370)
            {
                Player player = Main.player[plr];
                if (!player.active || player.dead)
                {
                    return;
                }
                for (int m = 0; m < 1000; m++)
                {
                    Projectile projectile = Main.projectile[m];
                    if (projectile.active && projectile.bobber && projectile.owner == plr)
                    {
                        int num8 = NPC.NewNPC(NPC.GetBossSpawnSource(plr), (int)projectile.Center.X, (int)projectile.Center.Y + 100, 370, 0, 0f, 0f, 0f, 0f, 255);
                        ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { Main.npc[num8].GetTypeNetName() }), ChatColors.BossOrEvent, -1);
                        return;
                    }
                }
                return;
            }
            else
            {
                if (npcType != 398)
                {
                    bool flag = false;
                    int num9 = 0;
                    int num10 = 0;
                    int num11 = 500;
                    int num12 = 50;
                    if (npcType == 316 || npcType == 82)
                    {
                        num11 = 200;
                        num12 = 30;
                    }
                    int num13 = num11 / 2;
                    Rectangle rectangle;
                    Rectangle rectangle2;
                    NPC.Spawner.GetSpawnArea(Main.player[plr], out rectangle, out rectangle2);
                    for (int n = 0; n < num11; n++)
                    {
                        bool flag2 = n == num11 - 1;
                        bool flag3 = false;
                        if (n >= num13 && WorldGen.Skyblock.lowTiles && npcType >= 0 && NPCID.Sets.SpawnOnPlayerCanSpawnInMidairOnSkyblock[npcType])
{
                            flag3 = true;
                        }
                        for (int num14 = 0; num14 < num12; num14++)
{
                            int num15 = Main.rand.Next(rectangle.Left, rectangle.Right);
                            int num16 = Main.rand.Next(rectangle.Top, rectangle.Bottom);
                            if ((!Main.tile[num15, num16].nactive() || !Main.tileSolid[(int)Main.tile[num15, num16].type]) && (!Main.wallHouse[(int)Main.tile[num15, num16].wall] || n >= num11 - 1) && (npcType != 50 || n >= num13 || Main.tile[num16, num16].wall <= 0))
{
                                for (int num17 = num16; num17 < rectangle.Bottom; num17++)
{
                                    if ((flag3 || (Main.tile[num15, num17].nactive() && Main.tileSolid[(int)Main.tile[num15, num17].type])) && (flag2 || !rectangle2.Contains(num15, num16)))
{
                                        ushort num18 = Main.tile[num15, num17].type;
                                        num9 = num15;
                                        num10 = num17;
                                        flag = true;
                                        break;
                                    }
                                }
                                if (flag && npcType == 50 && n < num11 - 100)
{
                                    int num19 = 20;
                                    if (!Collision.CanHit(new Vector2((float)num9, (float)(num10 - 1)) * 16f, 16, 16, new Vector2((float)num9, (float)(num10 - 1 - num19)) * 16f, 16, 16) || !Collision.CanHit(new Vector2((float)num9, (float)(num10 - 1 - num19)) * 16f, 16, 16, Main.player[plr].Center, 0, 0))
{
                                        num9 = 0;
                                        num10 = 0;
                                        flag = false;
                                        goto IL_05A5;
                                    }
                                }
                                if (flag && !flag2 && !NPC.Spawner.HasTileSpawnSpace(num9, num10))
{
                                    flag = false;
                                }
                                if (flag)
{
                                    break;
                                }
                            }
                            IL_05A5:;
                        }
                        if ((!flag || flag2 || NPC.Spawner.CheckNotSpawningOnScreen(num9, num10)) && flag)
{
                            break;
                        }
                    }
                    if (flag)
                    {
                        int num20 = num9 * 16 + 8;
                        int num21 = num10 * 16;
                        NPC.SpawnBoss(num20, num21, npcType, plr, ai0, ai1, ai2, ai3);
                    }
                    return;
                }
                if (NPC.AnyNPCs(npcType))
                {
                    return;
                }
                Player player2 = Main.player[plr];
                NPC.NewNPC(NPC.GetBossSpawnSource(plr), (int)player2.Center.X, (int)player2.Center.Y - 150, npcType, 0, 0f, 0f, 0f, 0f, 255);
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasAwoken", new object[] { NetworkText.FromKey("Enemies.MoonLord", new object[0]) }), ChatColors.BossOrEvent, -1);
                return;
            }
        }
References Terraria.Player.active, Terraria.Projectile.active, Terraria.Tile.active(), Terraria.NPC.AnyNPCs(), Terraria.Projectile.bobber, Terraria.Chat.ChatColors.BossOrEvent, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Entity.Center, Terraria.Player.dead, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetBossSpawnSource(), Terraria.NPC.GetTypeNetName(), int, Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Main.npc, Terraria.Projectile.owner, Terraria.Main.player, Terraria.Main.projectile, Terraria.WorldGen.SolidTile(), Terraria.NPC.target, Terraria.Main.tile, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.Check3x3(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckSign(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_AdvanceSlimeRain(), Terraria.Player.ItemCheck_CheckFishingBobber_PullBobber(), Terraria.Player.ItemCheck_UseBossSpawners(), Terraria.WorldGen.SmashAltar(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.NPC.SpawnMechQueen(), Terraria.GameContent.Events.DD2Event.SummonBetsy(), Terraria.Player.TileInteractionsUse(), and Terraria.Main.UpdateTime().