Terraria Decompiled: Terraria.NPC.AI_87_BigMimic_FireStuffCannonBurst
AI_87_BigMimic_FireStuffCannonBurst()
void Terraria.NPC.AI_87_BigMimic_FireStuffCannonBurst () inline private
Definition at line 41589 of file NPC.cs.
        {
            int num = 10;
            for (int i = 0; i < num; i++)
            {
                int num2 = ItemID.Sets.ItemsForStuffCannon[Main.rand.Next(ItemID.Sets.ItemsForStuffCannon.Length)];
                this.AI_87_BigMimic_ShootItem(num2);
            }
        }
References Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.ID.ItemID.Sets.ItemsForStuffCannon, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.Main.rand.
Referenced by Terraria.NPC.AI().