Terraria Decompiled: Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks
AI_AttemptToFindTeleportSpotNearBooks()
bool Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks (Point targetPosition, int maxRangeInTiles, out Vector2 destination) inline private
Definition at line 12914 of file NPC.cs.
        {
            destination = Vector2.Zero;
            int num = (int)base.Center.X / 16;
            int num2 = (int)base.Center.Y / 16;
            int num3 = num - targetPosition.X;
            int num4 = num2 - targetPosition.Y;
            if (Math.Sqrt((double)(num3 * num3 + num4 * num4)) > 125.0)
            {
                return false;
            }
            int num5 = Main.rand.Next(2) * 2 - 1;
            for (int i = 0; i < 100; i++)
            {
                int num6 = Main.rand.Next(targetPosition.X - maxRangeInTiles, targetPosition.X + maxRangeInTiles + 1);
                int num7 = Main.rand.Next(targetPosition.Y - maxRangeInTiles, targetPosition.Y + maxRangeInTiles + 1);
                if (!WorldGen.InWorld(new Point(num6, num7), 0))
                {
                    return false;
                }
                Tile tile = Main.tile[num6, num7];
                if (Main.wallDungeon[(int)tile.wall] && !tile.active())
                {
                    num5 *= -1;
                    bool flag = false;
                    int num8 = Math.Max(0, targetPosition.X - maxRangeInTiles);
                    int num9 = Math.Min(Main.maxTilesX - 1, targetPosition.X + maxRangeInTiles);
                    bool flag2;
                    do
                    {
                        num6 += num5;
                        if (num6 < num8 || num6 > num9)
{
                            goto IL_012C;
                        }
                        tile = Main.tile[num6, num7];
                        flag2 = tile.active() && Main.tileSolid[(int)tile.type];
                    }
                    while (!flag2);
                    IL_0160:
                    if (flag)
                    {
                        goto IL_0244;
                    }
                    num6 -= num5;
                    int num10 = num7;
                    while (this.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(num6, num10, true, out destination, out flag))
                    {
                        if (Math.Abs(destination.X - (float)num) > 1f || Math.Abs(destination.Y - (float)num2) > 1f)
{
                            destination.X -= (float)num5;
                            destination.Y += 1f;
                            return true;
                        }
                        num10 = (int)destination.Y;
                    }
                    if (!flag)
                    {
                        num10 = num7;
                        while (this.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(num6, num10, false, out destination, out flag))
{
                            if (Math.Abs(destination.X - (float)num) > 1f || Math.Abs(destination.Y - (float)num2) > 1f)
{
                                destination.X -= (float)num5;
                                destination.Y += 1f;
                                return true;
                            }
                            num10 = (int)destination.Y;
                        }
                        goto IL_0244;
                    }
                    goto IL_0244;
                    IL_012C:
                    flag = true;
                    goto IL_0160;
                }
                IL_0244:;
            }
            return false;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks_SearchWall(), System.destination, int, Terraria.WorldGen.InWorld(), System.Math.Max(), Terraria.Main.maxTilesX, System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, System.Math.Sqrt(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.AI().