Terraria Decompiled: Terraria.NPC.checkDead
checkDead()
void Terraria.NPC.checkDead () inline
Definition at line 76615 of file NPC.cs.
        {
            if (!this.active)
            {
                return;
            }
            if (this.realLife >= 0 && this.realLife != this.whoAmI)
            {
                return;
            }
            if (this.life <= 0)
            {
                if (this.type == 35 && this.ai[3] == 1f)
                {
                    ChatHelper.BroadcastChatMessage(NetworkText.FromKey("SkeletronText.Taunt1", new object[0]), new Color(255, 0, 0), -1);
                }
                if (this.type == 604 || this.type == 605)
                {
                    NPC.LadyBugKilled(base.Center, this.type == 605);
                }
                if (this.type == 397 || this.type == 396)
                {
                    if (this.ai[0] != -2f)
                    {
                        this.ai[0] = -2f;
                        this.life = this.lifeMax;
                        this.netUpdate = true;
                        this.dontTakeDamage = true;
                        if (Main.netMode != 1)
{
                            int num = NPC.NewNPC(this.GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)base.Center.Y, 400, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num].ai[3] = this.ai[3];
                            Main.npc[num].netUpdate = true;
                        }
                    }
                    return;
                }
                if (this.type == 398 && this.ai[0] != 2f)
                {
                    this.ai[0] = 2f;
                    this.life = this.lifeMax;
                    this.netUpdate = true;
                    this.dontTakeDamage = true;
                    return;
                }
                if ((this.type == 517 || this.type == 422 || this.type == 507 || this.type == 493) && this.ai[2] != 1f)
                {
                    this.ai[2] = 1f;
                    this.ai[1] = 0f;
                    this.life = this.lifeMax;
                    this.dontTakeDamage = true;
                    this.netUpdate = true;
                    return;
                }
                if (this.type == 548 && this.ai[1] != 1f)
                {
                    this.ai[1] = 1f;
                    this.ai[0] = 0f;
                    this.life = this.lifeMax;
                    this.dontTakeDamageFromHostiles = true;
                    this.netUpdate = true;
                    return;
                }
                if (Main.netMode != 1 && Main.getGoodWorld && (this.type == 42 || this.type == 176 || (this.type >= 231 && this.type <= 235)))
                {
                    this.StingerExplosion();
                }
                if (Main.netMode != 1 && Main.getGoodWorld)
                {
                    if (this.type == 13)
                    {
                        int num2 = NPC.NewNPC(this.GetSpawnSourceForNPCFromNPCAI(), (int)base.Center.X, (int)(this.position.Y + (float)this.height), -12, 0, 0f, 0f, 0f, 0f, 255);
                        if (Main.netMode == 2 && num2 < Main.maxNPCs)
{
                            NetMessage.SendData(23, -1, -1, null, num2, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    if (this.type == 36)
                    {
                        int num3 = 3;
                        for (int i = 0; i < num3; i++)
{
                            int num4 = 1000;
                            int j = 0;
                            while (j < num4)
{
                                int num5 = (int)(base.Center.X / 16f) + Main.rand.Next(-50, 51);
                                int num6 = (int)(base.Center.Y / 16f) + Main.rand.Next(-50, 51);
                                while (num6 < Main.maxTilesY - 200 && !WorldGen.SolidTile(num5, num6, false))
{
                                    num6++;
                                }
                                num6--;
                                if (!WorldGen.SolidTile(num5, num6, false))
{
                                    int num7 = NPC.NewNPC(this.GetSpawnSourceForNPCFromNPCAI(), num5 * 16 + 8, num6 * 16, 32, 0, 0f, 0f, 0f, 0f, 255);
                                    if (Main.netMode == 2 && num7 < Main.maxNPCs)
{
                                        NetMessage.SendData(23, -1, -1, null, num7, 0f, 0f, 0f, 0, 0, 0);
                                        break;
                                    }
                                    break;
                                }
                                else
{
                                    j++;
                                }
                            }
                        }
                    }
                }
                NPC.noSpawnCycle = true;
                if (this.townNPC && this.type != 37 && this.type != 453)
                {
                    if (Main.netMode != 2)
                    {
                        this.NPCLuck();
                    }
                    bool flag = true;
                    NetworkText fullNetName = this.GetFullNetName();
                    int num8 = 19;
                    if (this.type == 369 || this.type == 663 || NPCID.Sets.IsTownPet[this.type])
                    {
                        num8 = 36;
                        flag = false;
                    }
                    NetworkText networkText = NetworkText.FromKey(Lang.misc[num8].Key, new object[] { fullNetName });
                    if (flag)
                    {
                        for (int k = 0; k < 255; k++)
{
                            Player player = Main.player[k];
                            if (player != null && player.active && player.difficulty != 2)
{
                                flag = false;
                                break;
                            }
                        }
                    }
                    if (flag)
                    {
                        this.DropTombstoneTownNPC(networkText);
                    }
                    ChatHelper.BroadcastChatMessage(networkText, ChatColors.Death, -1);
                }
                if (Main.netMode != 1 && !Main.IsItDay() && this.type == 54 && !NPC.AnyNPCs(35))
                {
                    for (int l = 0; l < 255; l++)
                    {
                        if (Main.player[l].active && !Main.player[l].dead && Main.player[l].killClothier)
{
                            NPC.SpawnSkeletron(l, false);
                            break;
                        }
                    }
                }
                if (this.townNPC && Main.netMode != 1 && this.homeless && WorldGen.prioritizedTownNPCType == this.type)
                {
                    WorldGen.prioritizedTownNPCType = 0;
                }
                LegacySoundStyle legacySoundStyle = this.DeathSound;
                if (this.type == 229 && this.IsShimmerVariant)
                {
                    legacySoundStyle = SoundID.NPCDeath6;
                }
                if (legacySoundStyle != null)
                {
                    SoundEngine.PlaySound(legacySoundStyle, this.position, 0f, 1f);
                }
                if (this.type == 13 || this.type == 14 || this.type == 15)
                {
                    this.DropEoWLoot(true);
                }
                else if (this.type == 134)
                {
                    Vector2 position = this.position;
                    Vector2 center = Main.player[this.target].Center;
                    float num9 = 100000000f;
                    Vector2 vector = this.position;
                    for (int m = 0; m < Main.maxNPCs; m++)
                    {
                        if (Main.npc[m].active && (Main.npc[m].type == 134 || Main.npc[m].type == 135 || Main.npc[m].type == 136))
{
                            float num10 = Math.Abs(Main.npc[m].Center.X - center.X) + Math.Abs(Main.npc[m].Center.Y - center.Y);
                            if (num10 < num9)
{
                                num9 = num10;
                                vector = Main.npc[m].position;
                            }
                        }
                    }
                    this.position = vector;
                    this.NPCLoot();
                    this.position = position;
                }
                else
                {
                    this.NPCLoot();
                }
                this.active = false;
                if (Main.getGoodWorld && Main.netMode != 1 && this.type == 631)
                {
                    Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center, Vector2.Zero, 99, 70, 10f, Main.myPlayer, 0f, 0f, 0f, null);
                }
                DD2Event.CheckProgress(this.type);
                this.CheckProgressFrostMoon();
                this.CheckProgressPumpkinMoon();
                int npcinvasionGroup = NPC.GetNPCInvasionGroup(this.type);
                if (npcinvasionGroup > 0 && npcinvasionGroup == Main.invasionType)
                {
                    int num11 = 1;
                    int num12 = this.type;
                    if (num12 <= 395)
                    {
                        if (num12 != 216)
{
                            if (num12 != 387)
{
                                if (num12 == 395)
{
                                    num11 = 10;
                                }
                            }
                            else
{
                                num11 = 0;
                            }
                        }
                        else
{
                            num11 = 5;
                        }
                    }
                    else if (num12 != 471)
                    {
                        if (num12 != 472)
{
                            if (num12 == 491)
{
                                num11 = 10;
                            }
                        }
                        else
{
                            num11 = 0;
                        }
                    }
                    else
                    {
                        num11 = 10;
                    }
                    if (num11 > 0)
                    {
                        Main.invasionSize -= num11;
                        if (Main.invasionSize < 0)
{
                            Main.invasionSize = 0;
                        }
                        if (Main.netMode != 1)
{
                            Main.ReportInvasionProgress(Main.invasionSizeStart - Main.invasionSize, Main.invasionSizeStart, npcinvasionGroup + 3, 0);
                        }
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(78, -1, -1, null, Main.invasionProgress, (float)Main.invasionProgressMax, (float)Main.invasionProgressIcon, 0f, 0, 0, 0);
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.NPC.active, Terraria.Player.active, Terraria.NPC.ai, Terraria.NPC.AnyNPCs(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Entity.Center, Terraria.GameContent.Events.DD2Event.CheckProgress(), Terraria.NPC.CheckProgressFrostMoon(), Terraria.NPC.CheckProgressPumpkinMoon(), Terraria.Player.dead, Terraria.Chat.ChatColors.Death, Terraria.NPC.DeathSound, Terraria.Player.difficulty, Terraria.NPC.DropEoWLoot(), Terraria.NPC.DropTombstoneTownNPC(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetFullNetName(), Terraria.Main.getGoodWorld, Terraria.NPC.GetNPCInvasionGroup(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.NPC.GetSpawnSourceForNPCFromNPCAI(), int, Terraria.Main.invasionProgress, Terraria.Main.invasionProgressIcon, Terraria.Main.invasionProgressMax, Terraria.Main.invasionSize, Terraria.Main.invasionSizeStart, Terraria.Main.invasionType, Terraria.Main.IsItDay(), Terraria.NPC.IsShimmerVariant, Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Localization.LocalizedText.Key, Terraria.Player.killClothier, Terraria.NPC.LadyBugKilled(), Terraria.NPC.life, Terraria.NPC.lifeMax, Terraria.Main.maxNPCs, Terraria.Main.maxTilesY, Terraria.Lang.misc, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.ID.SoundID.NPCDeath6, Terraria.NPC.NPCLoot(), Terraria.NPC.NPCLuck(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.WorldGen.prioritizedTownNPCType, Terraria.Main.rand, Terraria.NPC.realLife, Terraria.Main.ReportInvasionProgress(), Terraria.NetMessage.SendData(), Terraria.WorldGen.SolidTile(), Terraria.NPC.SpawnSkeletron(), Terraria.NPC.StingerExplosion(), Terraria.NPC.target, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Entity.whoAmI, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.NPC.AI(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_037_Destroyer(), and Terraria.NPC.StrikeNPC().