Terraria Decompiled: Terraria.NPC.DoDeathEvents
DoDeathEvents()
void Terraria.NPC.DoDeathEvents (Player closestPlayer) inline private
Definition at line 77975 of file NPC.cs.
        {
            this.DoDeathEvents_AdvanceSlimeRain(closestPlayer);
            this.DoDeathEvents_SummonDungeonSpirit(closestPlayer);
            if (Main.remixWorld && !NPC.downedSlimeKing && this.AnyInteractions() && Main.AnyPlayerReadyToFightKingSlime() && this.type == 1 && !NPC.AnyNPCs(50) && Main.rand.Next(200) == 0)
            {
                NPC.SpawnOnPlayer(closestPlayer.whoAmI, 50, 0f, 0f, 0f, 0f);
            }
            int num = this.type;
            if (num <= 266)
            {
                if (num <= 113)
                {
                    if (num <= 22)
                    {
                        if (num == 4)
{
                            NPC.SetEventFlagCleared(ref NPC.downedBoss1, 13);
                            goto IL_0A9C;
                        }
                        if (num - 13 > 2)
{
                            if (num != 22)
{
                                goto IL_0A9C;
                            }
                            if (Collision.LavaCollision(this.position, this.width, this.height))
{
                                NPC.SpawnWOF(this.position);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        }
                    }
                    else if (num <= 50)
                    {
                        if (num != 35)
{
                            if (num != 50)
{
                                goto IL_0A9C;
                            }
                            if (Main.slimeRain)
{
                                Main.StopSlimeRain(true);
                                AchievementsHelper.NotifyProgressionEvent(16);
                            }
                            if (Main.netMode != 1 && !NPC.unlockedSlimeBlueSpawn)
{
                                NPC.unlockedSlimeBlueSpawn = true;
                                this.ViolentlySpawnNerdySlime();
                            }
                            NPC.SetEventFlagCleared(ref NPC.downedSlimeKing, 11);
                            if (Main.netMode == 2)
{
                                NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        }
                        else
{
                            if (this.boss)
{
                                NPC.SetEventFlagCleared(ref NPC.downedBoss3, 15);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        }
                    }
                    else if (num != 109)
                    {
                        if (num != 113)
{
                            goto IL_0A9C;
                        }
                        if (Main.netMode != 1)
{
                            this.CreateBrickBoxForWallOfFlesh();
                            bool hardMode = Main.hardMode;
                            WorldGen.StartHardmode(false);
                            if (NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3 && !hardMode)
{
                                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[32].Key, new object[0]), ChatColors.World, -1);
                            }
                            NPC.SetEventFlagCleared(ref hardMode, 19);
                            goto IL_0A9C;
                        }
                        goto IL_0A9C;
                    }
                    else
                    {
                        if (NPC.downedClown)
{
                            goto IL_0A9C;
                        }
                        NPC.downedClown = true;
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                            goto IL_0A9C;
                        }
                        goto IL_0A9C;
                    }
                }
                else if (num <= 216)
                {
                    if (num <= 127)
                    {
                        if (num - 125 > 1)
{
                            if (num != 127)
{
                                goto IL_0A9C;
                            }
                            if (this.boss)
{
                                NPC.SetEventFlagCleared(ref NPC.downedMechBoss3, 18);
                                NPC.downedMechBossAny = true;
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        }
                        else
{
                            if (this.boss)
{
                                NPC.SetEventFlagCleared(ref NPC.downedMechBoss2, 17);
                                NPC.downedMechBossAny = true;
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        }
                    }
                    else if (num != 134)
                    {
                        if (num != 216)
{
                            goto IL_0A9C;
                        }
                        NPC.SpawnBoss((int)this.position.X, (int)this.position.Y, 662, this.target, 0f, 0f, 0f, 0f);
                        goto IL_0A9C;
                    }
                    else
                    {
                        if (this.boss)
{
                            NPC.SetEventFlagCleared(ref NPC.downedMechBoss1, 16);
                            NPC.downedMechBossAny = true;
                            goto IL_0A9C;
                        }
                        goto IL_0A9C;
                    }
                }
                else if (num <= 245)
                {
                    if (num != 222)
                    {
                        if (num != 245)
{
                            goto IL_0A9C;
                        }
                        NPC.SetEventFlagCleared(ref NPC.downedGolemBoss, 6);
                        goto IL_0A9C;
                    }
                    else
                    {
                        NPC.SetEventFlagCleared(ref NPC.downedQueenBee, 8);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                            goto IL_0A9C;
                        }
                        goto IL_0A9C;
                    }
                }
                else if (num != 262)
                {
                    if (num != 266)
                    {
                        goto IL_0A9C;
                    }
                }
                else
                {
                    bool flag = NPC.downedPlantBoss;
                    NPC.SetEventFlagCleared(ref NPC.downedPlantBoss, 12);
                    if (!flag)
                    {
                        ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[33].Key, new object[0]), ChatColors.World, -1);
                        goto IL_0A9C;
                    }
                    goto IL_0A9C;
                }
                if (this.boss)
                {
                    if (WorldGen.Skyblock.lowTiles)
                    {
                        WorldGen.shadowOrbSmashed = true;
                    }
                    if (!NPC.downedBoss2 || Main.rand.Next(2) == 0)
                    {
                        WorldGen.spawnMeteor = true;
                    }
                    NPC.SetEventFlagCleared(ref NPC.downedBoss2, 14);
                }
            }
            else
            {
                if (num <= 507)
                {
                    if (num <= 346)
                    {
                        if (num != 325)
{
                            if (num != 327)
{
                                switch (num)
{
                                case 344:
                                    if (Main.snowMoon)
{
                                        NPC.SetEventFlagCleared(ref NPC.downedChristmasTree, 21);
                                        goto IL_0A9C;
                                    }
                                    goto IL_0A9C;
                                case 345:
                                    if (Main.snowMoon)
{
                                        NPC.SetEventFlagCleared(ref NPC.downedChristmasIceQueen, 20);
                                        goto IL_0A9C;
                                    }
                                    goto IL_0A9C;
                                case 346:
                                    if (Main.snowMoon)
{
                                        NPC.SetEventFlagCleared(ref NPC.downedChristmasSantank, 22);
                                        goto IL_0A9C;
                                    }
                                    goto IL_0A9C;
                                default:
                                    goto IL_0A9C;
                                }
                            }
                            else
{
                                if (Main.pumpkinMoon)
{
                                    NPC.SetEventFlagCleared(ref NPC.downedHalloweenKing, 5);
                                    goto IL_0A9C;
                                }
                                goto IL_0A9C;
                            }
                        }
                        else
{
                            if (Main.pumpkinMoon)
{
                                NPC.SetEventFlagCleared(ref NPC.downedHalloweenTree, 4);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        }
                    }
                    else if (num <= 439)
                    {
                        if (num == 370)
{
                            NPC.SetEventFlagCleared(ref NPC.downedFishron, 7);
                            goto IL_0A9C;
                        }
                        switch (num)
{
                        case 398:
                            NPC.SetEventFlagCleared(ref NPC.downedMoonlord, 10);
                            NPC.LunarApocalypseIsUp = false;
                            if (Main.getGoodWorld)
{
                                AchievementsHelper.NotifyProgressionEvent(30);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        case 399:
                        case 400:
                        case 401:
                        case 403:
                        case 404:
                        case 406:
                        case 408:
                        case 410:
                        case 428:
                        case 430:
                        case 431:
                        case 432:
                        case 433:
                        case 434:
                        case 435:
                        case 436:
                        case 437:
                        case 438:
                            goto IL_0A9C;
                        case 402:
                        case 405:
                        case 407:
                        case 409:
                        case 411:
                            if (NPC.ShieldStrengthTowerStardust > 0)
{
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, (float)NPC.FindFirstNPC(493), 0f, 0f, null);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        case 412:
                        case 413:
                        case 414:
                        case 415:
                        case 416:
                        case 417:
                        case 418:
                        case 419:
                            break;
                        case 420:
                        case 421:
                        case 423:
                        case 424:
                            if (NPC.ShieldStrengthTowerNebula > 0)
{
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, (float)NPC.FindFirstNPC(507), 0f, 0f, null);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        case 422:
                            NPC.downedTowerVortex = true;
                            NPC.TowerActiveVortex = false;
                            WorldGen.UpdateLunarApocalypse();
                            WorldGen.MessageLunarApocalypse();
                            goto IL_0A9C;
                        case 425:
                        case 426:
                        case 427:
                        case 429:
                            if (NPC.ShieldStrengthTowerVortex > 0)
{
                                Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, (float)NPC.FindFirstNPC(422), 0f, 0f, null);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        case 439:
                            NPC.SetEventFlagCleared(ref NPC.downedAncientCultist, 9);
                            WorldGen.TriggerLunarApocalypse();
                            goto IL_0A9C;
                        default:
                            goto IL_0A9C;
                        }
                    }
                    else
                    {
                        if (num == 493)
{
                            NPC.downedTowerStardust = true;
                            NPC.TowerActiveStardust = false;
                            WorldGen.UpdateLunarApocalypse();
                            WorldGen.MessageLunarApocalypse();
                            goto IL_0A9C;
                        }
                        if (num != 507)
{
                            goto IL_0A9C;
                        }
                        NPC.downedTowerNebula = true;
                        NPC.TowerActiveNebula = false;
                        WorldGen.UpdateLunarApocalypse();
                        WorldGen.MessageLunarApocalypse();
                        goto IL_0A9C;
                    }
                }
                else if (num <= 614)
                {
                    if (num <= 518)
                    {
                        if (num == 517)
{
                            NPC.downedTowerSolar = true;
                            NPC.TowerActiveSolar = false;
                            WorldGen.UpdateLunarApocalypse();
                            WorldGen.MessageLunarApocalypse();
                            goto IL_0A9C;
                        }
                        if (num != 518)
{
                            goto IL_0A9C;
                        }
                    }
                    else
                    {
                        switch (num)
{
                        case 552:
                        case 553:
                        case 554:
                            if (!DD2Event.Ongoing)
{
                                goto IL_0A9C;
                            }
                            DD2Event.AnnounceGoblinDeath(this);
                            if (DD2Event.ShouldDropCrystals())
{
                                Item.NewItem(this.GetItemSource_Loot(), this.position, base.Size, 3822, 1, false, 0, false);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        case 555:
                        case 556:
                        case 557:
                        case 558:
                        case 559:
                        case 560:
                        case 561:
                        case 562:
                        case 563:
                        case 564:
                        case 565:
                        case 568:
                        case 569:
                        case 570:
                        case 571:
                        case 572:
                        case 573:
                        case 574:
                        case 575:
                        case 576:
                        case 577:
                        case 578:
                            if (DD2Event.ShouldDropCrystals())
{
                                Item.NewItem(this.GetItemSource_Loot(), this.position, base.Size, 3822, 1, false, 0, false);
                                goto IL_0A9C;
                            }
                            goto IL_0A9C;
                        case 566:
                        case 567:
                            goto IL_0A9C;
                        default:
{
                            if (num != 614)
{
                                goto IL_0A9C;
                            }
                            int num2 = 175;
                            if (this.SpawnedFromStatue)
{
                                num2 = 0;
                            }
                            Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 281, num2, 0f, Main.myPlayer, -2f, (float)(this.releaseOwner + 1), 0f, null);
                            goto IL_0A9C;
                        }
                        }
                    }
                }
                else if (num <= 657)
                {
                    if (num == 636)
                    {
                        NPC.SetEventFlagCleared(ref NPC.downedEmpressOfLight, 23);
                        goto IL_0A9C;
                    }
                    if (num != 657)
                    {
                        goto IL_0A9C;
                    }
                    NPC.SetEventFlagCleared(ref NPC.downedQueenSlime, 24);
                    goto IL_0A9C;
                }
                else if (num != 661)
                {
                    if (num != 668)
                    {
                        goto IL_0A9C;
                    }
                    NPC.SetEventFlagCleared(ref NPC.downedDeerclops, 25);
                    goto IL_0A9C;
                }
                else
                {
                    if (Main.netMode == 1 || !this.GetWereThereAnyInteractions())
                    {
                        goto IL_0A9C;
                    }
                    int num3 = 636;
                    if (!NPC.AnyNPCs(num3))
                    {
                        Vector2 vector = base.Center + new Vector2(0f, -200f) + Main.rand.NextVector2Circular(50f, 50f);
                        NPC.SpawnBoss((int)vector.X, (int)vector.Y, num3, closestPlayer.whoAmI, 0f, 0f, 0f, 0f);
                        goto IL_0A9C;
                    }
                    goto IL_0A9C;
                }
                if (NPC.ShieldStrengthTowerSolar > 0)
                {
                    Projectile.NewProjectile(this.GetSpawnSource_ForProjectile(), base.Center.X, base.Center.Y, 0f, 0f, 629, 0, 0f, Main.myPlayer, (float)NPC.FindFirstNPC(517), 0f, 0f, null);
                }
            }
            IL_0A9C:
            if (this.boss)
            {
                this.DoDeathEvents_DropBossPotionsAndHearts();
                this.DoDeathEvents_CelebrateBossDeath();
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.GameContent.Events.DD2Event.AnnounceGoblinDeath(), Terraria.NPC.AnyNPCs(), Terraria.Main.AnyPlayerReadyToFightKingSlime(), Terraria.NPC.boss, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.NPC.CreateBrickBoxForWallOfFlesh(), Terraria.NPC.DoDeathEvents_AdvanceSlimeRain(), Terraria.NPC.DoDeathEvents_CelebrateBossDeath(), Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts(), Terraria.NPC.DoDeathEvents_SummonDungeonSpirit(), Terraria.NPC.downedAncientCultist, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedChristmasIceQueen, Terraria.NPC.downedChristmasSantank, Terraria.NPC.downedChristmasTree, Terraria.NPC.downedClown, Terraria.NPC.downedDeerclops, Terraria.NPC.downedEmpressOfLight, Terraria.NPC.downedFishron, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedHalloweenKing, Terraria.NPC.downedHalloweenTree, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedMoonlord, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.NPC.downedQueenSlime, Terraria.NPC.downedSlimeKing, Terraria.NPC.FindFirstNPC(), Terraria.Localization.NetworkText.FromKey(), Terraria.Main.getGoodWorld, Terraria.NPC.GetItemSource_Loot(), Terraria.NPC.GetSpawnSource_ForProjectile(), Terraria.Main.hardMode, Terraria.Localization.LocalizedText.Key, Terraria.Collision.LavaCollision(), Terraria.WorldGen.Skyblock.lowTiles, Terraria.WorldGen.MessageLunarApocalypse(), Terraria.Lang.misc, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Entity.position, Terraria.Main.pumpkinMoon, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.NPC.SetEventFlagCleared(), Terraria.NPC.ShieldStrengthTowerNebula, Terraria.NPC.ShieldStrengthTowerSolar, Terraria.NPC.ShieldStrengthTowerStardust, Terraria.NPC.ShieldStrengthTowerVortex, Terraria.GameContent.Events.DD2Event.ShouldDropCrystals(), Terraria.Main.slimeRain, Terraria.Main.snowMoon, Terraria.NPC.SpawnBoss(), Terraria.NPC.SpawnedFromStatue, Terraria.NPC.SpawnOnPlayer(), Terraria.NPC.SpawnWOF(), Terraria.WorldGen.StartHardmode(), Terraria.Main.StopSlimeRain(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.NPC.type, Terraria.NPC.unlockedSlimeBlueSpawn, Terraria.WorldGen.UpdateLunarApocalypse(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.NPC.ViolentlySpawnNerdySlime(), Terraria.Entity.whoAmI, Terraria.Chat.ChatColors.World, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.NPCLoot().