Terraria Decompiled: Terraria.NPC.TryMoveToTransformableSpaceInto
TryMoveToTransformableSpaceInto()
bool Terraria.NPC.TryMoveToTransformableSpaceInto (int targetType) inline
Definition at line 80089 of file NPC.cs.
        {
            NPC npc;
            if (!ContentSamples.NpcsByNetId.TryGetValue(targetType, out npc))
            {
                return false;
            }
            Rectangle rectangle;
            if (!Collision.TryChangingSizeFromBottomCenter(base.Hitbox, npc.width, npc.height, out rectangle))
            {
                return false;
            }
            this.position = rectangle.TopLeft();
            return true;
        }
References Terraria.Entity.height, Terraria.ID.ContentSamples.NpcsByNetId, Terraria.Collision.TryChangingSizeFromBottomCenter(), and Terraria.Entity.width.
Referenced by Terraria.NPC.AI(), and Terraria.NPC.AI_003_Fighters().