Terraria Decompiled: Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestion
ConsumeSuggestion()
static void Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestion () inline static
Definition at line 48 of file UILinkPointNavigator.cs.
        {
            if (UILinkPointNavigator._suggestedPointID == null)
            {
                return;
            }
            int value = UILinkPointNavigator._suggestedPointID.Value;
            UILinkPointNavigator.ClearSuggestion();
            UILinkPointNavigator.CurrentPage = UILinkPointNavigator.Points[value].Page;
            UILinkPointNavigator.OverridePoint = value;
            UILinkPointNavigator.ProcessChanges();
            PlayerInput.Triggers.Current.UsedMovementKey = true;
        }
References Terraria.UI.Gamepad.UILinkPointNavigator._suggestedPointID, Terraria.UI.Gamepad.UILinkPointNavigator.ClearSuggestion(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges(), and System.value.
Referenced by Terraria.UI.Gamepad.UILinkPointNavigator.Update().