Terraria Decompiled: Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage
ChangePage()
static void Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage (int PageID) inline static
Definition at line 465 of file UILinkPointNavigator.cs.
        {
            if (UILinkPointNavigator.Pages.ContainsKey(PageID) && UILinkPointNavigator.Pages[PageID].CanEnter())
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                UILinkPointNavigator.CurrentPage = PageID;
                UILinkPointNavigator.ProcessChanges();
            }
        }
References Terraria.UI.Gamepad.UILinkPointNavigator.Pages, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges().
Referenced by Terraria.UI.BannerClaimingUI.DrawBannersGrid(), Terraria.UI.CraftingUI.DrawRecipesGrid(), Terraria.GameContent.UI.NewCraftingUI.OnActivate(), Terraria.UI.Gamepad.UILinkPage.SwapPageLeft(), Terraria.UI.Gamepad.UILinkPage.SwapPageRight(), and Terraria.Player.ToggleInv().