Terraria Decompiled: Terraria.UI.Gamepad.UILinkPointNavigator.Update
Update()
static void Terraria.UI.Gamepad.UILinkPointNavigator.Update () inline static
Definition at line 151 of file UILinkPointNavigator.cs.
        {
            bool inUse = UILinkPointNavigator.InUse;
            UILinkPointNavigator.InUse = false;
            bool flag = true;
            if (flag)
            {
                InputMode currentInputMode = PlayerInput.CurrentInputMode;
                if (currentInputMode <= InputMode.Mouse && !Main.gameMenu)
                {
                    flag = false;
                }
            }
            if (flag && PlayerInput.NavigatorRebindingLock > 0)
            {
                flag = false;
            }
            if (flag && !Main.gameMenu && !PlayerInput.UsingGamepadUI)
            {
                flag = false;
            }
            if (flag && !Main.gameMenu && PlayerInput.InBuildingMode)
            {
                flag = false;
            }
            if (flag && !Main.gameMenu && !UILinkPointNavigator.Available)
            {
                flag = false;
            }
            if (flag && Main.gameMenu && Main.MenuUI.IsVisible && Main.MenuUI.CurrentState != null && Main.MenuUI.CurrentState.NoGamepadSupport)
            {
                flag = false;
            }
            bool flag2 = false;
            UILinkPage uilinkPage;
            if (!UILinkPointNavigator.Pages.TryGetValue(UILinkPointNavigator.CurrentPage, out uilinkPage))
            {
                flag2 = true;
            }
            else if (!uilinkPage.IsValid())
            {
                flag2 = true;
            }
            if (flag2)
            {
                UILinkPointNavigator.GoToDefaultPage(0);
                UILinkPointNavigator.ProcessChanges();
                flag = false;
            }
            if (inUse != flag)
            {
                if (!flag)
                {
                    uilinkPage.Leave();
                    UILinkPointNavigator.GoToDefaultPage(0);
                    UILinkPointNavigator.ProcessChanges();
                }
                else
                {
                    UILinkPointNavigator.GoToDefaultPage(0);
                    UILinkPointNavigator.ProcessChanges();
                    UILinkPointNavigator.ConsumeSuggestion();
                    uilinkPage.Enter();
                }
                if (flag)
                {
                    if (!PlayerInput.SteamDeckIsUsed || PlayerInput.PreventCursorModeSwappingToGamepad)
                    {
                        Main.player[Main.myPlayer].releaseInventory = false;
                    }
                    Main.player[Main.myPlayer].releaseUseTile = false;
                    PlayerInput.LockGamepadTileUseButton = true;
                }
                if (!Main.gameMenu)
                {
                    if (flag)
                    {
                        PlayerInput.NavigatorCachePosition();
                    }
                    else
                    {
                        PlayerInput.NavigatorUnCachePosition();
                    }
                }
            }
            UILinkPointNavigator.ClearSuggestion();
            if (!flag)
            {
                return;
            }
            UILinkPointNavigator.InUse = true;
            UILinkPointNavigator.OverridePoint = -1;
            if (UILinkPointNavigator.PageLeftCD > 0)
            {
                UILinkPointNavigator.PageLeftCD--;
            }
            if (UILinkPointNavigator.PageRightCD > 0)
            {
                UILinkPointNavigator.PageRightCD--;
            }
            Vector2 navigatorDirections = PlayerInput.Triggers.Current.GetNavigatorDirections();
            object obj = PlayerInput.Triggers.Current.HotbarMinus && !PlayerInput.Triggers.Current.HotbarPlus;
            bool flag3 = PlayerInput.Triggers.Current.HotbarPlus && !PlayerInput.Triggers.Current.HotbarMinus;
            object obj2 = obj;
            if (obj2 == null)
            {
                UILinkPointNavigator.PageLeftCD = 0;
            }
            if (!flag3)
            {
                UILinkPointNavigator.PageRightCD = 0;
            }
            object obj3 = obj2 != null && UILinkPointNavigator.PageLeftCD == 0;
            flag3 = flag3 && UILinkPointNavigator.PageRightCD == 0;
            if (UILinkPointNavigator.LastInput.X != navigatorDirections.X)
            {
                UILinkPointNavigator.XCooldown = 0;
            }
            if (UILinkPointNavigator.LastInput.Y != navigatorDirections.Y)
            {
                UILinkPointNavigator.YCooldown = 0;
            }
            if (UILinkPointNavigator.XCooldown > 0)
            {
                UILinkPointNavigator.XCooldown--;
            }
            if (UILinkPointNavigator.YCooldown > 0)
            {
                UILinkPointNavigator.YCooldown--;
            }
            UILinkPointNavigator.LastInput = navigatorDirections;
            object obj4 = obj3;
            if (obj4 != null)
            {
                UILinkPointNavigator.PageLeftCD = 16;
            }
            if (flag3)
            {
                UILinkPointNavigator.PageRightCD = 16;
            }
            UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].Update();
            int num = 10;
            if (!Main.gameMenu && Main.playerInventory && !Main.ingameOptionsWindow && !Main.inFancyUI && (UILinkPointNavigator.CurrentPage == 0 || UILinkPointNavigator.CurrentPage == 4 || UILinkPointNavigator.CurrentPage == 2 || UILinkPointNavigator.CurrentPage == 1 || UILinkPointNavigator.CurrentPage == 20 || UILinkPointNavigator.CurrentPage == 21))
            {
                num = PlayerInput.CurrentProfile.InventoryMoveCD;
            }
            if (navigatorDirections.X == -1f && UILinkPointNavigator.XCooldown == 0)
            {
                UILinkPointNavigator.XCooldown = num;
                UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].TravelLeft();
            }
            if (navigatorDirections.X == 1f && UILinkPointNavigator.XCooldown == 0)
            {
                UILinkPointNavigator.XCooldown = num;
                UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].TravelRight();
            }
            if (navigatorDirections.Y == -1f && UILinkPointNavigator.YCooldown == 0)
            {
                UILinkPointNavigator.YCooldown = num;
                UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].TravelUp();
            }
            if (navigatorDirections.Y == 1f && UILinkPointNavigator.YCooldown == 0)
            {
                UILinkPointNavigator.YCooldown = num;
                UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].TravelDown();
            }
            UILinkPointNavigator.XCooldown = (UILinkPointNavigator.YCooldown = Math.Max(UILinkPointNavigator.XCooldown, UILinkPointNavigator.YCooldown));
            if (obj4 != null)
            {
                UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].SwapPageLeft();
            }
            if (flag3)
            {
                UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage].SwapPageRight();
            }
            if (PlayerInput.Triggers.Current.UsedMovementKey)
            {
                Vector2 position = UILinkPointNavigator.Points[UILinkPointNavigator.CurrentPoint].Position;
                Vector2 vector = new Vector2((float)PlayerInput.MouseX, (float)PlayerInput.MouseY);
                float num2 = 0.3f;
                if (PlayerInput.InvisibleGamepadInMenus)
                {
                    num2 = 1f;
                }
                Vector2 vector2 = Vector2.Lerp(vector, position, num2);
                if (Main.gameMenu)
                {
                    if (Math.Abs(vector2.X - position.X) <= 5f)
                    {
                        vector2.X = position.X;
                    }
                    if (Math.Abs(vector2.Y - position.Y) <= 5f)
                    {
                        vector2.Y = position.Y;
                    }
                }
                PlayerInput.MouseX = (int)vector2.X;
                PlayerInput.MouseY = (int)vector2.Y;
            }
            UILinkPointNavigator.ResetFlagsEnd();
            if (DebugOptions.DrawLinkPoints)
            {
                UILinkPointNavigator.DrawLinks();
            }
        }
References System.Math.Abs(), Terraria.UI.Gamepad.UILinkPointNavigator.Available, Terraria.UI.Gamepad.UILinkPointNavigator.ClearSuggestion(), Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestion(), Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.PlayerInput.CurrentInputMode, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPage, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.Testing.DebugOptions.DrawLinkPoints, Terraria.UI.Gamepad.UILinkPointNavigator.DrawLinks(), Terraria.UI.Gamepad.UILinkPage.Enter(), Terraria.Main.gameMenu, Terraria.GameInput.TriggersSet.GetNavigatorDirections(), Terraria.UI.Gamepad.UILinkPointNavigator.GoToDefaultPage(), Terraria.GameInput.TriggersSet.HotbarMinus, Terraria.GameInput.TriggersSet.HotbarPlus, Terraria.GameInput.PlayerInput.InBuildingMode, Terraria.Main.inFancyUI, Terraria.Main.ingameOptionsWindow, int, Terraria.UI.Gamepad.UILinkPointNavigator.InUse, Terraria.GameInput.PlayerInputProfile.InventoryMoveCD, Terraria.GameInput.PlayerInput.InvisibleGamepadInMenus, Terraria.UI.Gamepad.UILinkPage.IsValid(), Terraria.UI.Gamepad.UILinkPointNavigator.LastInput, Terraria.UI.Gamepad.UILinkPage.Leave(), Microsoft.Xna.Framework.Vector2.Lerp(), System.Math.Max(), Terraria.Main.MenuUI, Terraria.GameInput.PlayerInput.MouseX, Terraria.GameInput.PlayerInput.MouseY, Terraria.Main.myPlayer, Terraria.GameInput.PlayerInput.NavigatorCachePosition(), Terraria.GameInput.PlayerInput.NavigatorRebindingLock, Terraria.GameInput.PlayerInput.NavigatorUnCachePosition(), System.obj, Terraria.UI.Gamepad.UILinkPointNavigator.PageLeftCD, Terraria.UI.Gamepad.UILinkPointNavigator.PageRightCD, Terraria.UI.Gamepad.UILinkPointNavigator.Pages, Terraria.Main.player, Terraria.Main.playerInventory, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.GameInput.PlayerInput.PreventCursorModeSwappingToGamepad, Terraria.UI.Gamepad.UILinkPointNavigator.ProcessChanges(), Terraria.Player.releaseInventory, Terraria.Player.releaseUseTile, Terraria.UI.Gamepad.UILinkPointNavigator.ResetFlagsEnd(), Terraria.GameInput.PlayerInput.SteamDeckIsUsed, Terraria.GameInput.PlayerInput.Triggers, Terraria.GameInput.TriggersSet.UsedMovementKey, Terraria.GameInput.PlayerInput.UsingGamepadUI, Microsoft.Xna.Framework.Vector2.X, Terraria.UI.Gamepad.UILinkPointNavigator.XCooldown, Microsoft.Xna.Framework.Vector2.Y, and Terraria.UI.Gamepad.UILinkPointNavigator.YCooldown.
Referenced by Terraria.Main.DoUpdate_HandleInput().