Terraria Decompiled: Terraria.UI.Gamepad.UILinkPointNavigator.GetPosition
GetPosition()
static Vector2 Terraria.UI.Gamepad.UILinkPointNavigator.GetPosition (int ID) inline static
Definition at line 421 of file UILinkPointNavigator.cs.
        {
            UILinkPoint uilinkPoint;
            Vector2 vector;
            if (!UILinkPointNavigator.Points.TryGetValue(ID, out uilinkPoint))
            {
                vector = Vector2.Zero;
            }
            else
            {
                vector = uilinkPoint.Position;
            }
            if (vector == Vector2.Zero)
            {
                if (ID >= 180 && ID <= 184)
                {
                    vector = UILinkPointNavigator.GetPosition(ID - 180 + 100);
                }
                else if (ID >= 185 && ID <= 189)
                {
                    vector = UILinkPointNavigator.GetPosition(ID - 185 + 110);
                }
            }
            return vector / Main.UIScale;
        }
References Terraria.UI.Gamepad.UILinkPointNavigator.GetPosition(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPoint.Position, Terraria.Main.UIScale, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.UI.ItemSlot.DisplayTransfer_GetItem(), Terraria.UI.ItemSlot.DisplayTransfer_OneWay(), Terraria.UI.ItemSlot.DisplayTransfer_TwoWay(), Terraria.UI.ItemSlot.DisplayTransfer_TwoWay(), Terraria.GameContent.UI.Elements.UIDynamicItemCollection< TEntry >.DrawSelf(), and Terraria.UI.Gamepad.UILinkPointNavigator.GetPosition().