Terraria Decompiled: Terraria.UI.Gamepad.UILinkPointNavigator.GetInstructions
GetInstructions()
static string Terraria.UI.Gamepad.UILinkPointNavigator.GetInstructions () inline static
Definition at line 366 of file UILinkPointNavigator.cs.
        {
            UILinkPage uilinkPage = UILinkPointNavigator.Pages[UILinkPointNavigator.CurrentPage];
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[UILinkPointNavigator.CurrentPoint];
            if (UILinkPointNavigator._suggestedPointID != null)
            {
                UILinkPointNavigator.SwapToSuggestion();
                uilinkPoint = UILinkPointNavigator.Points[UILinkPointNavigator._suggestedPointID.Value];
                uilinkPage = UILinkPointNavigator.Pages[uilinkPoint.Page];
                UILinkPointNavigator.CurrentPage = uilinkPage.ID;
                uilinkPage.CurrentPoint = UILinkPointNavigator._suggestedPointID.Value;
            }
            string text = uilinkPage.SpecialInteractions();
            if ((PlayerInput.SettingsForUI.CurrentCursorMode == CursorMode.Gamepad && PlayerInput.Triggers.Current.UsedMovementKey && UILinkPointNavigator.InUse) || UILinkPointNavigator._suggestedPointID != null)
            {
                text += uilinkPoint.SpecialInteractions();
            }
            text += uilinkPage.SpecialInteractionsLate();
            UILinkPointNavigator.ConsumeSuggestionSwap();
            return text;
        }
References Terraria.UI.Gamepad.UILinkPointNavigator._suggestedPointID, Terraria.UI.Gamepad.UILinkPointNavigator.ConsumeSuggestionSwap(), Terraria.GameInput.TriggersPack.Current, Terraria.GameInput.PlayerInput.SettingsForUI.CurrentCursorMode, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPage, Terraria.UI.Gamepad.UILinkPointNavigator.CurrentPoint, Terraria.UI.Gamepad.UILinkPage.ID, Terraria.UI.Gamepad.UILinkPointNavigator.InUse, Terraria.UI.Gamepad.UILinkPoint.Page, Terraria.UI.Gamepad.UILinkPointNavigator.Pages, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPage.SpecialInteractions(), Terraria.UI.Gamepad.UILinkPoint.SpecialInteractions(), Terraria.UI.Gamepad.UILinkPage.SpecialInteractionsLate(), Terraria.UI.Gamepad.UILinkPointNavigator.SwapToSuggestion(), System.text, Terraria.GameInput.PlayerInput.Triggers, and Terraria.GameInput.TriggersSet.UsedMovementKey.
Referenced by Terraria.GameInput.PlayerInput.ComposeInstructionsForGamepad().