Terraria Decompiled: Terraria.UI.Gamepad.UILinkPointNavigator.DrawLink
DrawLink()
static void Terraria.UI.Gamepad.UILinkPointNavigator.DrawLink (UILinkPoint src, int targetId, Vector2 dir, Color colorStart, Color colorEnd) inline static private
Definition at line 533 of file UILinkPointNavigator.cs.
        {
            UILinkPoint uilinkPoint;
            if (!UILinkPointNavigator.Points.TryGetValue(targetId, out uilinkPoint) || uilinkPoint.Position == Vector2.Zero)
            {
                return;
            }
            if (UILinkPointNavigator._visited.Add(uilinkPoint))
            {
                UILinkPointNavigator._queue.Enqueue(uilinkPoint);
            }
            Vector2 vector = dir.RotatedBy(1.5707963267948966, default(Vector2));
            Vector2 vector2 = src.Position / Main.UIScale + vector * 2f;
            Vector2 vector3 = uilinkPoint.Position / Main.UIScale + vector * 2f;
            if (Vector2.Dot(vector3 - vector2, dir) < 0f)
            {
                DebugLineDraw.UI.AddLine(vector2, vector2 += (vector + dir * 2f) * 2f * 2f, colorStart, default(Color), 1, 1f);
                DebugLineDraw.UI.AddLine(vector3, vector3 += (vector - dir * 2f) * 2f * 2f, colorEnd, default(Color), 1, 1f);
            }
            DebugLineDraw.UI.AddLine(vector2, vector3, colorStart, colorEnd, 1, 1f);
        }
References Terraria.UI.Gamepad.UILinkPointNavigator._queue, Terraria.UI.Gamepad.UILinkPointNavigator._visited, Terraria.Testing.DebugLineDraw.AddLine(), Microsoft.Xna.Framework.Vector2.Dot(), Terraria.UI.Gamepad.UILinkPointNavigator.Points, Terraria.UI.Gamepad.UILinkPoint.Position, Terraria.Testing.DebugLineDraw.UI, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.UI.Gamepad.UILinkPointNavigator.DrawLinks().