Terraria Decompiled: System.Security.Cryptography.CryptoConfig.Initialize
Initialize()
static void System.Security.Cryptography.CryptoConfig.Initialize () inline static private
Definition at line 144 of file CryptoConfig.cs.
        {
            Dictionary<string, Type> dictionary = new Dictionary<string, Type>(StringComparer.OrdinalIgnoreCase);
            dictionary.Add("SHA", CryptoConfig.defaultSHA1);
            dictionary.Add("SHA1", CryptoConfig.defaultSHA1);
            dictionary.Add("System.Security.Cryptography.SHA1", CryptoConfig.defaultSHA1);
            dictionary.Add("System.Security.Cryptography.HashAlgorithm", CryptoConfig.defaultSHA1);
            dictionary.Add("MD5", CryptoConfig.defaultMD5);
            dictionary.Add("System.Security.Cryptography.MD5", CryptoConfig.defaultMD5);
            dictionary.Add("SHA256", CryptoConfig.defaultSHA256);
            dictionary.Add("SHA-256", CryptoConfig.defaultSHA256);
            dictionary.Add("System.Security.Cryptography.SHA256", CryptoConfig.defaultSHA256);
            dictionary.Add("SHA384", CryptoConfig.defaultSHA384);
            dictionary.Add("SHA-384", CryptoConfig.defaultSHA384);
            dictionary.Add("System.Security.Cryptography.SHA384", CryptoConfig.defaultSHA384);
            dictionary.Add("SHA512", CryptoConfig.defaultSHA512);
            dictionary.Add("SHA-512", CryptoConfig.defaultSHA512);
            dictionary.Add("System.Security.Cryptography.SHA512", CryptoConfig.defaultSHA512);
            dictionary.Add("RSA", CryptoConfig.defaultRSA);
            dictionary.Add("System.Security.Cryptography.RSA", CryptoConfig.defaultRSA);
            dictionary.Add("System.Security.Cryptography.AsymmetricAlgorithm", CryptoConfig.defaultRSA);
            dictionary.Add("DSA", CryptoConfig.defaultDSA);
            dictionary.Add("System.Security.Cryptography.DSA", CryptoConfig.defaultDSA);
            dictionary.Add("DES", CryptoConfig.defaultDES);
            dictionary.Add("System.Security.Cryptography.DES", CryptoConfig.defaultDES);
            dictionary.Add("3DES", CryptoConfig.default3DES);
            dictionary.Add("TripleDES", CryptoConfig.default3DES);
            dictionary.Add("Triple DES", CryptoConfig.default3DES);
            dictionary.Add("System.Security.Cryptography.TripleDES", CryptoConfig.default3DES);
            dictionary.Add("RC2", CryptoConfig.defaultRC2);
            dictionary.Add("System.Security.Cryptography.RC2", CryptoConfig.defaultRC2);
            dictionary.Add("Rijndael", CryptoConfig.defaultAES);
            dictionary.Add("System.Security.Cryptography.Rijndael", CryptoConfig.defaultAES);
            dictionary.Add("System.Security.Cryptography.SymmetricAlgorithm", CryptoConfig.defaultAES);
            dictionary.Add("RandomNumberGenerator", CryptoConfig.defaultRNG);
            dictionary.Add("System.Security.Cryptography.RandomNumberGenerator", CryptoConfig.defaultRNG);
            dictionary.Add("System.Security.Cryptography.KeyedHashAlgorithm", CryptoConfig.defaultHMAC);
            dictionary.Add("HMACSHA1", CryptoConfig.defaultHMAC);
            dictionary.Add("System.Security.Cryptography.HMACSHA1", CryptoConfig.defaultHMAC);
            dictionary.Add("MACTripleDES", CryptoConfig.defaultMAC3DES);
            dictionary.Add("System.Security.Cryptography.MACTripleDES", CryptoConfig.defaultMAC3DES);
            dictionary.Add("RIPEMD160", CryptoConfig.defaultRIPEMD160);
            dictionary.Add("RIPEMD-160", CryptoConfig.defaultRIPEMD160);
            dictionary.Add("System.Security.Cryptography.RIPEMD160", CryptoConfig.defaultRIPEMD160);
            dictionary.Add("System.Security.Cryptography.HMAC", CryptoConfig.defaultHMAC);
            dictionary.Add("HMACMD5", CryptoConfig.defaultHMACMD5);
            dictionary.Add("System.Security.Cryptography.HMACMD5", CryptoConfig.defaultHMACMD5);
            dictionary.Add("HMACRIPEMD160", CryptoConfig.defaultHMACRIPEMD160);
            dictionary.Add("System.Security.Cryptography.HMACRIPEMD160", CryptoConfig.defaultHMACRIPEMD160);
            dictionary.Add("HMACSHA256", CryptoConfig.defaultHMACSHA256);
            dictionary.Add("System.Security.Cryptography.HMACSHA256", CryptoConfig.defaultHMACSHA256);
            dictionary.Add("HMACSHA384", CryptoConfig.defaultHMACSHA384);
            dictionary.Add("System.Security.Cryptography.HMACSHA384", CryptoConfig.defaultHMACSHA384);
            dictionary.Add("HMACSHA512", CryptoConfig.defaultHMACSHA512);
            dictionary.Add("System.Security.Cryptography.HMACSHA512", CryptoConfig.defaultHMACSHA512);
            Dictionary<string, string> dictionary2 = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            dictionary.Add("http://www.w3.org/2000/09/xmldsig#dsa-sha1", CryptoConfig.defaultDSASigDesc);
            dictionary.Add("http://www.w3.org/2000/09/xmldsig#rsa-sha1", CryptoConfig.defaultRSAPKCS1SHA1SigDesc);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#rsa-sha256", CryptoConfig.defaultRSAPKCS1SHA256SigDesc);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#rsa-sha384", CryptoConfig.defaultRSAPKCS1SHA384SigDesc);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#rsa-sha512", CryptoConfig.defaultRSAPKCS1SHA512SigDesc);
            dictionary.Add("http://www.w3.org/2000/09/xmldsig#sha1", CryptoConfig.defaultSHA1);
            dictionary2.Add("http://www.w3.org/TR/2001/REC-xml-c14n-20010315", "System.Security.Cryptography.Xml.XmlDsigC14NTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/TR/2001/REC-xml-c14n-20010315#WithComments", "System.Security.Cryptography.Xml.XmlDsigC14NWithCommentsTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig#base64", "System.Security.Cryptography.Xml.XmlDsigBase64Transform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/TR/1999/REC-xpath-19991116", "System.Security.Cryptography.Xml.XmlDsigXPathTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/TR/1999/REC-xslt-19991116", "System.Security.Cryptography.Xml.XmlDsigXsltTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig#enveloped-signature", "System.Security.Cryptography.Xml.XmlDsigEnvelopedSignatureTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2001/10/xml-exc-c14n#", "System.Security.Cryptography.Xml.XmlDsigExcC14NTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2001/10/xml-exc-c14n#WithComments", "System.Security.Cryptography.Xml.XmlDsigExcC14NWithCommentsTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2002/07/decrypt#XML", "System.Security.Cryptography.Xml.XmlDecryptionTransform, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary.Add("http://www.w3.org/2001/04/xmlenc#sha256", CryptoConfig.defaultSHA256);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#sha384", CryptoConfig.defaultSHA384);
            dictionary.Add("http://www.w3.org/2001/04/xmlenc#sha512", CryptoConfig.defaultSHA512);
            dictionary.Add("http://www.w3.org/2000/09/xmldsig#hmac-sha1", CryptoConfig.defaultHMAC);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#hmac-sha256", CryptoConfig.defaultHMACSHA256);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#hmac-sha384", CryptoConfig.defaultHMACSHA384);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#hmac-sha512", CryptoConfig.defaultHMACSHA512);
            dictionary.Add("http://www.w3.org/2001/04/xmldsig-more#hmac-ripemd160", CryptoConfig.defaultHMACRIPEMD160);
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig# X509Data", "System.Security.Cryptography.Xml.KeyInfoX509Data, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig# KeyName", "System.Security.Cryptography.Xml.KeyInfoName, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig# KeyValue/DSAKeyValue", "System.Security.Cryptography.Xml.DSAKeyValue, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig# KeyValue/RSAKeyValue", "System.Security.Cryptography.Xml.RSAKeyValue, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("http://www.w3.org/2000/09/xmldsig# RetrievalMethod", "System.Security.Cryptography.Xml.KeyInfoRetrievalMethod, System.Security, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a");
            dictionary2.Add("2.5.29.14", "System.Security.Cryptography.X509Certificates.X509SubjectKeyIdentifierExtension, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("2.5.29.15", "System.Security.Cryptography.X509Certificates.X509KeyUsageExtension, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("2.5.29.19", "System.Security.Cryptography.X509Certificates.X509BasicConstraintsExtension, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("2.5.29.37", "System.Security.Cryptography.X509Certificates.X509EnhancedKeyUsageExtension, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("X509Chain", "System.Security.Cryptography.X509Certificates.X509Chain, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("AES", "System.Security.Cryptography.AesCryptoServiceProvider, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.AesCryptoServiceProvider", "System.Security.Cryptography.AesCryptoServiceProvider, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("AesManaged", "System.Security.Cryptography.AesManaged, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.AesManaged", "System.Security.Cryptography.AesManaged, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("ECDH", "System.Security.Cryptography.ECDiffieHellmanCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("ECDiffieHellman", "System.Security.Cryptography.ECDiffieHellmanCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("ECDiffieHellmanCng", "System.Security.Cryptography.ECDiffieHellmanCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.ECDiffieHellmanCng", "System.Security.Cryptography.ECDiffieHellmanCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("ECDsa", "System.Security.Cryptography.ECDsaCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("ECDsaCng", "System.Security.Cryptography.ECDsaCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.ECDsaCng", "System.Security.Cryptography.ECDsaCng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA1Cng", "System.Security.Cryptography.SHA1Cng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA256Cng", "System.Security.Cryptography.SHA256Cng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA256CryptoServiceProvider", "System.Security.Cryptography.SHA256CryptoServiceProvider, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA384Cng", "System.Security.Cryptography.SHA384Cng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA384CryptoServiceProvider", "System.Security.Cryptography.SHA384CryptoServiceProvider, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA512Cng", "System.Security.Cryptography.SHA512Cng, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            dictionary2.Add("System.Security.Cryptography.SHA512CryptoServiceProvider", "System.Security.Cryptography.SHA512CryptoServiceProvider, System.Core, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089");
            Dictionary<string, string> dictionary3 = new Dictionary<string, string>(StringComparer.OrdinalIgnoreCase);
            dictionary3.Add("System.Security.Cryptography.SHA1CryptoServiceProvider", "1.3.14.3.2.26");
            dictionary3.Add("System.Security.Cryptography.SHA1Managed", "1.3.14.3.2.26");
            dictionary3.Add("SHA1", "1.3.14.3.2.26");
            dictionary3.Add("System.Security.Cryptography.SHA1", "1.3.14.3.2.26");
            dictionary3.Add("System.Security.Cryptography.SHA1Cng", "1.3.14.3.2.26");
            dictionary3.Add("System.Security.Cryptography.MD5CryptoServiceProvider", "1.2.840.113549.2.5");
            dictionary3.Add("MD5", "1.2.840.113549.2.5");
            dictionary3.Add("System.Security.Cryptography.MD5", "1.2.840.113549.2.5");
            dictionary3.Add("System.Security.Cryptography.SHA256Managed", "2.16.840.1.101.3.4.2.1");
            dictionary3.Add("SHA256", "2.16.840.1.101.3.4.2.1");
            dictionary3.Add("System.Security.Cryptography.SHA256", "2.16.840.1.101.3.4.2.1");
            dictionary3.Add("System.Security.Cryptography.SHA256Cng", "2.16.840.1.101.3.4.2.1");
            dictionary3.Add("System.Security.Cryptography.SHA256CryptoServiceProvider", "2.16.840.1.101.3.4.2.1");
            dictionary3.Add("System.Security.Cryptography.SHA384Managed", "2.16.840.1.101.3.4.2.2");
            dictionary3.Add("SHA384", "2.16.840.1.101.3.4.2.2");
            dictionary3.Add("System.Security.Cryptography.SHA384", "2.16.840.1.101.3.4.2.2");
            dictionary3.Add("System.Security.Cryptography.SHA384Cng", "2.16.840.1.101.3.4.2.2");
            dictionary3.Add("System.Security.Cryptography.SHA384CryptoServiceProvider", "2.16.840.1.101.3.4.2.2");
            dictionary3.Add("System.Security.Cryptography.SHA512Managed", "2.16.840.1.101.3.4.2.3");
            dictionary3.Add("SHA512", "2.16.840.1.101.3.4.2.3");
            dictionary3.Add("System.Security.Cryptography.SHA512", "2.16.840.1.101.3.4.2.3");
            dictionary3.Add("System.Security.Cryptography.SHA512Cng", "2.16.840.1.101.3.4.2.3");
            dictionary3.Add("System.Security.Cryptography.SHA512CryptoServiceProvider", "2.16.840.1.101.3.4.2.3");
            dictionary3.Add("System.Security.Cryptography.RIPEMD160Managed", "1.3.36.3.2.1");
            dictionary3.Add("RIPEMD160", "1.3.36.3.2.1");
            dictionary3.Add("System.Security.Cryptography.RIPEMD160", "1.3.36.3.2.1");
            dictionary3.Add("TripleDESKeyWrap", "1.2.840.113549.1.9.16.3.6");
            dictionary3.Add("DES", "1.3.14.3.2.7");
            dictionary3.Add("TripleDES", "1.2.840.113549.3.7");
            dictionary3.Add("RC2", "1.2.840.113549.3.2");
            CryptoConfig.LoadConfig(Environment.GetMachineConfigPath(), dictionary, dictionary3);
            CryptoConfig.algorithms = dictionary;
            CryptoConfig.unresolved_algorithms = dictionary2;
            CryptoConfig.oids = dictionary3;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Security.Cryptography.CryptoConfig.default3DES, System.Security.Cryptography.CryptoConfig.defaultAES, System.Security.Cryptography.CryptoConfig.defaultDES, System.Security.Cryptography.CryptoConfig.defaultDSA, System.Security.Cryptography.CryptoConfig.defaultDSASigDesc, System.Security.Cryptography.CryptoConfig.defaultHMAC, System.Security.Cryptography.CryptoConfig.defaultHMACMD5, System.Security.Cryptography.CryptoConfig.defaultHMACRIPEMD160, System.Security.Cryptography.CryptoConfig.defaultHMACSHA256, System.Security.Cryptography.CryptoConfig.defaultHMACSHA384, System.Security.Cryptography.CryptoConfig.defaultHMACSHA512, System.Security.Cryptography.CryptoConfig.defaultMAC3DES, System.Security.Cryptography.CryptoConfig.defaultMD5, System.Security.Cryptography.CryptoConfig.defaultRC2, System.Security.Cryptography.CryptoConfig.defaultRIPEMD160, System.Security.Cryptography.CryptoConfig.defaultRNG, System.Security.Cryptography.CryptoConfig.defaultRSA, System.Security.Cryptography.CryptoConfig.defaultRSAPKCS1SHA1SigDesc, System.Security.Cryptography.CryptoConfig.defaultRSAPKCS1SHA256SigDesc, System.Security.Cryptography.CryptoConfig.defaultRSAPKCS1SHA384SigDesc, System.Security.Cryptography.CryptoConfig.defaultRSAPKCS1SHA512SigDesc, System.Security.Cryptography.CryptoConfig.defaultSHA1, System.Security.Cryptography.CryptoConfig.defaultSHA256, System.Security.Cryptography.CryptoConfig.defaultSHA384, System.Security.Cryptography.CryptoConfig.defaultSHA512, System.dictionary, System.Security.Cryptography.CryptoConfig.LoadConfig(), and System.StringComparer.OrdinalIgnoreCase.
Referenced by System.Security.Cryptography.CryptoConfig.AddAlgorithm(), System.Security.Cryptography.CryptoConfig.CreateFromName(), and System.Security.Cryptography.CryptoConfig.MapNameToOID().