Terraria Decompiled: System.Security.Cryptography.CryptoConfig.EncodeOID
EncodeOID()
static byte[] System.Security.Cryptography.CryptoConfig.EncodeOID (string str) inline static
Definition at line 54 of file CryptoConfig.cs.
        {
            if (str == null)
            {
                throw new ArgumentNullException("str");
            }
            char[] array = new char[] { '.' };
            string[] array2 = str.Split(array);
            if (array2.Length < 2)
            {
                throw new CryptographicUnexpectedOperationException(Locale.GetText("OID must have at least two parts"));
            }
            byte[] array3 = new byte[str.Length];
            try
            {
                byte b = Convert.ToByte(array2[0]);
                byte b2 = Convert.ToByte(array2[1]);
                array3[2] = Convert.ToByte((int)(b * 40 + b2));
            }
            catch
            {
                throw new CryptographicUnexpectedOperationException(Locale.GetText("Invalid OID"));
            }
            int num = 3;
            for (int i = 2; i < array2.Length; i++)
            {
                long num2 = Convert.ToInt64(array2[i]);
                if (num2 > 127L)
                {
                    byte[] array4 = CryptoConfig.EncodeLongNumber(num2);
                    Buffer.BlockCopy(array4, 0, array3, num, array4.Length);
                    num += array4.Length;
                }
                else
                {
                    array3[num++] = Convert.ToByte(num2);
                }
            }
            int num3 = 2;
            byte[] array5 = new byte[num];
            array5[0] = 6;
            if (num > 127)
            {
                throw new CryptographicUnexpectedOperationException(Locale.GetText("OID > 127 bytes"));
            }
            array5[1] = Convert.ToByte(num - 2);
            Buffer.BlockCopy(array3, num3, array5, num3, num - num3);
            return array5;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.CryptoConfig.EncodeLongNumber(), Locale.GetText(), System.L, System.Convert.ToByte(), and System.Convert.ToInt64().
Referenced by Mono.Security.Cryptography.PKCS1.Encode_v15(), and Mono.Security.ASN1Convert.FromOid().