Terraria Decompiled: System.Security.Cryptography.CryptoConfig.EncodeLongNumber
EncodeLongNumber()
static byte[] System.Security.Cryptography.CryptoConfig.EncodeLongNumber (long x) inline static private
Definition at line 105 of file CryptoConfig.cs.
        {
            if (x > 2147483647L || x < -2147483648L)
            {
                throw new OverflowException(Locale.GetText("Part of OID doesn't fit in Int32"));
            }
            long num = x;
            int num2 = 1;
            while (num > 127L)
            {
                num >>= 7;
                num2++;
            }
            byte[] array = new byte[num2];
            for (int i = 0; i < num2; i++)
            {
                num = x >> 7 * i;
                num &= 127L;
                if (i != 0)
                {
                    num += 128L;
                }
                array[num2 - i - 1] = Convert.ToByte(num);
            }
            return array;
        }
References System.array, Locale.GetText(), System.L, and System.Convert.ToByte().
Referenced by System.Security.Cryptography.CryptoConfig.EncodeOID().