Terraria Decompiled: Terraria.GameContent.ChromaHotkeyPainter.Step_Movement
Step_Movement()
void Terraria.GameContent.ChromaHotkeyPainter.Step_Movement () inline private
Definition at line 204 of file ChromaHotkeyPainter.cs.
        {
            List<ChromaHotkeyPainter.PaintKey> wasdKeys = this._wasdKeys;
            bool flag = this._player.frozen || this._player.tongued || this._player.webbed || this._player.stoned;
            if (this._player.dead)
            {
                this.SetGroupClear(wasdKeys);
                return;
            }
            if (flag)
            {
                this.SetGroupColorBase(wasdKeys, ChromaHotkeyPainter.PainterColors.DangerKeyBlocked);
                return;
            }
            this.SetGroupColorBase(wasdKeys, ChromaHotkeyPainter.PainterColors.MovementKeys);
        }
References Terraria.GameContent.ChromaHotkeyPainter._player, Terraria.GameContent.ChromaHotkeyPainter._wasdKeys, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.DangerKeyBlocked, Terraria.Player.dead, Terraria.GameContent.ChromaHotkeyPainter.PainterColors.MovementKeys, Terraria.GameContent.ChromaHotkeyPainter.SetGroupClear(), Terraria.GameContent.ChromaHotkeyPainter.SetGroupColorBase(), and Terraria.Player.stoned.
Referenced by Terraria.GameContent.ChromaHotkeyPainter.Update().