Terraria Decompiled: Terraria.GameContent.ChromaHotkeyPainter.Update
Update()
void Terraria.GameContent.ChromaHotkeyPainter.Update () inline
Definition at line 80 of file ChromaHotkeyPainter.cs.
        {
            this._player = Main.LocalPlayer;
            if (!FocusHelper.AllowChroma)
            {
                this.Step_ClearAll();
                return;
            }
            if (this.PotionAlert)
            {
                foreach (KeyValuePair<string, ChromaHotkeyPainter.PaintKey> keyValuePair in this._keys)
                {
                    if (keyValuePair.Key != "QuickHeal")
                    {
                        keyValuePair.Value.SetClear();
                    }
                }
                this.Step_QuickHeal();
            }
            else
            {
                this.Step_Movement();
                this.Step_QuickHeal();
            }
            if (Main.InGameUI.CurrentState == Main.ManageControlsMenu)
            {
                this.Step_ClearAll();
                this.Step_KeybindsMenu();
            }
            this.Step_UpdateReactiveKeys();
        }
References Terraria.GameContent.ChromaHotkeyPainter._keys, Terraria.FocusHelper.AllowChroma, Terraria.Main.InGameUI, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.Main.LocalPlayer, Terraria.Main.ManageControlsMenu, Terraria.GameContent.ChromaHotkeyPainter.PotionAlert, Terraria.GameContent.ChromaHotkeyPainter.Step_ClearAll(), Terraria.GameContent.ChromaHotkeyPainter.Step_KeybindsMenu(), Terraria.GameContent.ChromaHotkeyPainter.Step_Movement(), Terraria.GameContent.ChromaHotkeyPainter.Step_QuickHeal(), Terraria.GameContent.ChromaHotkeyPainter.Step_UpdateReactiveKeys(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.Main.DoUpdate().