Terraria Decompiled: Terraria.GameContent.ChromaHotkeyPainter.CollectBoundKeys
CollectBoundKeys()
void Terraria.GameContent.ChromaHotkeyPainter.CollectBoundKeys () inline
Definition at line 27 of file ChromaHotkeyPainter.cs.
        {
            foreach (KeyValuePair<string, ChromaHotkeyPainter.PaintKey> keyValuePair in this._keys)
            {
                keyValuePair.Value.Unbind();
            }
            this._keys.Clear();
            foreach (KeyValuePair<string, List<string>> keyValuePair2 in PlayerInput.CurrentProfile.InputModes[InputMode.Keyboard].KeyStatus)
            {
                this._keys.Add(keyValuePair2.Key, new ChromaHotkeyPainter.PaintKey(keyValuePair2.Key, keyValuePair2.Value));
            }
            foreach (KeyValuePair<string, ChromaHotkeyPainter.PaintKey> keyValuePair3 in this._keys)
            {
                keyValuePair3.Value.Bind();
            }
            this._wasdKeys = new List<ChromaHotkeyPainter.PaintKey>
            {
                this._keys["Up"],
                this._keys["Down"],
                this._keys["Left"],
                this._keys["Right"]
            };
            this._healKey = this._keys["QuickHeal"];
            this._mountKey = this._keys["QuickMount"];
            this._jumpKey = this._keys["Jump"];
            this._grappleKey = this._keys["Grapple"];
            this._throwKey = this._keys["Throw"];
            this._manaKey = this._keys["QuickMana"];
            this._buffKey = this._keys["QuickBuff"];
            this._smartCursorKey = this._keys["SmartCursor"];
            this._smartSelectKey = this._keys["SmartSelect"];
            this._reactiveKeys.Clear();
            this._xnaKeysInUse.Clear();
            foreach (KeyValuePair<string, ChromaHotkeyPainter.PaintKey> keyValuePair4 in this._keys)
            {
                this._xnaKeysInUse.AddRange(keyValuePair4.Value.GetXNAKeysInUse());
            }
            this._xnaKeysInUse = this._xnaKeysInUse.Distinct<Keys>().ToList<Keys>();
        }
References Terraria.GameContent.ChromaHotkeyPainter._keys, Terraria.GameContent.ChromaHotkeyPainter._reactiveKeys, Terraria.GameContent.ChromaHotkeyPainter._xnaKeysInUse, System.Collections.Generic.List< T >.AddRange(), System.Collections.Generic.List< T >.Clear(), Terraria.GameInput.PlayerInput.CurrentProfile, Terraria.GameInput.PlayerInputProfile.InputModes, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.Main.ClientInitialize().