Terraria Decompiled: System.IO.UnmanagedMemoryStream.WriteByte
WriteByte()
unsafe override void System.IO.UnmanagedMemoryStream.WriteByte (byte value) inline virtual
Reimplemented from System.IO.Stream.
Definition at line 714 of file UnmanagedMemoryStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureWriteable();
            long num = Interlocked.Read(ref this._position);
            long num2 = Interlocked.Read(ref this._length);
            long num3 = num + 1L;
            if (num >= num2)
            {
                if (num3 < 0L)
                {
                    throw new IOException("Stream was too long.");
                }
                if (num3 > this._capacity)
                {
                    throw new NotSupportedException("Unable to expand length of this stream beyond its capacity.");
                }
                if (this._buffer == null)
                {
                    if (num > num2)
                    {
                        Buffer.ZeroMemory(this._mem + num2, num - num2);
                    }
                    Interlocked.Exchange(ref this._length, num3);
                }
            }
            if (this._buffer != null)
            {
                byte* ptr = null;
                RuntimeHelpers.PrepareConstrainedRegions();
                try
                {
                    this._buffer.AcquirePointer(ref ptr);
                    (ptr + num)[this._offset] = value;
                    goto IL_00C4;
                }
                finally
                {
                    if (ptr != null)
                    {
                        this._buffer.ReleasePointer();
                    }
                }
            }
            this._mem[num] = value;
            IL_00C4:
            Interlocked.Exchange(ref this._position, num3);
        }
References System.IO.UnmanagedMemoryStream._buffer, System.IO.UnmanagedMemoryStream._capacity, System.IO.UnmanagedMemoryStream._length, System.IO.UnmanagedMemoryStream._mem, System.IO.UnmanagedMemoryStream._offset, System.IO.UnmanagedMemoryStream._position, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureWriteable(), System.Threading.Interlocked.Exchange(), System.L, System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Threading.Interlocked.Read(), System.Runtime.InteropServices.SafeBuffer.ReleasePointer(), System.value, and System.Buffer.ZeroMemory().
Referenced by System.IO.UnmanagedMemoryStreamWrapper.WriteByte().