Terraria Decompiled: System.IO.UnmanagedMemoryStream.WriteCore
WriteCore()
unsafe void System.IO.UnmanagedMemoryStream.WriteCore (ReadOnlySpan< byte > buffer) inline package
Definition at line 591 of file UnmanagedMemoryStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureWriteable();
            long num = Interlocked.Read(ref this._position);
            long num2 = Interlocked.Read(ref this._length);
            long num3 = num + (long)buffer.Length;
            if (num3 < 0L)
            {
                throw new IOException("Stream was too long.");
            }
            if (num3 > this._capacity)
            {
                throw new NotSupportedException("Unable to expand length of this stream beyond its capacity.");
            }
            if (this._buffer == null)
            {
                if (num > num2)
                {
                    Buffer.ZeroMemory(this._mem + num2, num - num2);
                }
                if (num3 > num2)
                {
                    Interlocked.Exchange(ref this._length, num3);
                }
            }
            fixed (byte* reference = MemoryMarshal.GetReference<byte>(buffer))
            {
                byte* ptr = reference;
                if (this._buffer != null)
                {
                    if (this._capacity - num < (long)buffer.Length)
                    {
                        throw new ArgumentException("Not enough space available in the buffer.");
                    }
                    byte* ptr2 = null;
                    RuntimeHelpers.PrepareConstrainedRegions();
                    try
                    {
                        this._buffer.AcquirePointer(ref ptr2);
                        Buffer.Memcpy(ptr2 + num + this._offset, ptr, buffer.Length);
                        goto IL_010C;
                    }
                    finally
                    {
                        if (ptr2 != null)
{
                            this._buffer.ReleasePointer();
                        }
                    }
                }
                Buffer.Memcpy(this._mem + num, ptr, buffer.Length);
                IL_010C:;
            }
            Interlocked.Exchange(ref this._position, num3);
        }
References System.IO.UnmanagedMemoryStream._buffer, System.IO.UnmanagedMemoryStream._capacity, System.IO.UnmanagedMemoryStream._length, System.IO.UnmanagedMemoryStream._mem, System.IO.UnmanagedMemoryStream._offset, System.IO.UnmanagedMemoryStream._position, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureWriteable(), System.Threading.Interlocked.Exchange(), System.L, System.ReadOnlySpan< T >.Length, long, System.Buffer.Memcpy(), System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Threading.Interlocked.Read(), System.Runtime.InteropServices.SafeBuffer.ReleasePointer(), and System.Buffer.ZeroMemory().
Referenced by System.IO.UnmanagedMemoryStream.Write(), and System.IO.UnmanagedMemoryStream.Write().