Terraria Decompiled: System.IO.UnmanagedMemoryStream.ReadByte
ReadByte()
unsafe override int System.IO.UnmanagedMemoryStream.ReadByte () inline virtual
Reimplemented from System.IO.Stream.
Definition at line 457 of file UnmanagedMemoryStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureReadable();
            long num = Interlocked.Read(ref this._position);
            long num2 = Interlocked.Read(ref this._length);
            if (num >= num2)
            {
                return -1;
            }
            Interlocked.Exchange(ref this._position, num + 1L);
            if (this._buffer != null)
            {
                byte* ptr = null;
                RuntimeHelpers.PrepareConstrainedRegions();
                try
                {
                    this._buffer.AcquirePointer(ref ptr);
                    return (int)(ptr + num)[this._offset];
                }
                finally
                {
                    if (ptr != null)
                    {
                        this._buffer.ReleasePointer();
                    }
                }
            }
            return (int)this._mem[num];
        }
References System.IO.UnmanagedMemoryStream._buffer, System.IO.UnmanagedMemoryStream._length, System.IO.UnmanagedMemoryStream._mem, System.IO.UnmanagedMemoryStream._offset, System.IO.UnmanagedMemoryStream._position, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureReadable(), System.Threading.Interlocked.Exchange(), System.L, System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Threading.Interlocked.Read(), and System.Runtime.InteropServices.SafeBuffer.ReleasePointer().
Referenced by System.IO.UnmanagedMemoryStreamWrapper.ReadByte().