Terraria Decompiled: System.IO.UnmanagedMemoryStream.Read
Read() [1/2]
override int System.IO.UnmanagedMemoryStream.Read (byte[] buffer, int offset, int count) inline
Definition at line 314 of file UnmanagedMemoryStream.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer", "Buffer cannot be null.");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Non-negative number required.");
            }
            if (buffer.Length - offset < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            return this.ReadCore(new Span<byte>(buffer, offset, count));
        }
References System.count, System.offset, and System.IO.UnmanagedMemoryStream.ReadCore().
Referenced by System.Resources.ResourceReader._LoadObjectV2(), System.IO.UnmanagedMemoryStreamWrapper.Read(), System.IO.UnmanagedMemoryStreamWrapper.Read(), and System.IO.UnmanagedMemoryStreamWrapper.ToArray().