Terraria Decompiled: System.IO.UnmanagedMemoryStream.Seek
Seek()
override long System.IO.UnmanagedMemoryStream.Seek (long offset, SeekOrigin loc) inline
Definition at line 489 of file UnmanagedMemoryStream.cs.
        {
            this.EnsureNotClosed();
            switch (loc)
            {
            case SeekOrigin.Begin:
                if (offset < 0L)
                {
                    throw new IOException("An attempt was made to move the position before the beginning of the stream.");
                }
                Interlocked.Exchange(ref this._position, offset);
                break;
            case SeekOrigin.Current:
            {
                long num = Interlocked.Read(ref this._position);
                if (offset + num < 0L)
                {
                    throw new IOException("An attempt was made to move the position before the beginning of the stream.");
                }
                Interlocked.Exchange(ref this._position, offset + num);
                break;
            }
            case SeekOrigin.End:
            {
                long num2 = Interlocked.Read(ref this._length);
                if (num2 + offset < 0L)
                {
                    throw new IOException("An attempt was made to move the position before the beginning of the stream.");
                }
                Interlocked.Exchange(ref this._position, num2 + offset);
                break;
            }
            default:
                throw new ArgumentException("Invalid seek origin.");
            }
            return Interlocked.Read(ref this._position);
        }
References System.IO.UnmanagedMemoryStream._length, System.IO.UnmanagedMemoryStream._position, System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.Threading.Interlocked.Exchange(), System.L, System.offset, and System.Threading.Interlocked.Read().
Referenced by System.Resources.ResourceReader._ReadResources(), System.Resources.ResourceReader.CompareStringEqualsName(), and System.IO.UnmanagedMemoryStreamWrapper.Seek().