Terraria Decompiled: System.IO.UnmanagedMemoryStream.ReadCore
ReadCore()
unsafe int System.IO.UnmanagedMemoryStream.ReadCore (Span< byte > buffer) inline package
Definition at line 346 of file UnmanagedMemoryStream.cs.
        {
            this.EnsureNotClosed();
            this.EnsureReadable();
            long num = Interlocked.Read(ref this._position);
            long num2 = Math.Min(Interlocked.Read(ref this._length) - num, (long)buffer.Length);
            if (num2 <= 0L)
            {
                return 0;
            }
            int num3 = (int)num2;
            if (num3 < 0)
            {
                return 0;
            }
            fixed (byte* reference = MemoryMarshal.GetReference<byte>(buffer))
            {
                byte* ptr = reference;
                if (this._buffer != null)
                {
                    byte* ptr2 = null;
                    RuntimeHelpers.PrepareConstrainedRegions();
                    try
                    {
                        this._buffer.AcquirePointer(ref ptr2);
                        Buffer.Memcpy(ptr, ptr2 + num + this._offset, num3);
                        goto IL_00A5;
                    }
                    finally
                    {
                        if (ptr2 != null)
{
                            this._buffer.ReleasePointer();
                        }
                    }
                }
                Buffer.Memcpy(ptr, this._mem + num, num3);
                IL_00A5:;
            }
            Interlocked.Exchange(ref this._position, num + num2);
            return num3;
        }
References System.IO.UnmanagedMemoryStream._buffer, System.IO.UnmanagedMemoryStream._mem, System.IO.UnmanagedMemoryStream._offset, System.IO.UnmanagedMemoryStream._position, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryStream.EnsureNotClosed(), System.IO.UnmanagedMemoryStream.EnsureReadable(), System.Threading.Interlocked.Exchange(), int, System.L, System.Span< T >.Length, System.Buffer.Memcpy(), System.Math.Min(), System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), System.Threading.Interlocked.Read(), and System.Runtime.InteropServices.SafeBuffer.ReleasePointer().
Referenced by System.IO.UnmanagedMemoryStream.Read(), and System.IO.UnmanagedMemoryStream.Read().