Terraria Decompiled: System.IO.UnmanagedMemoryStream.Initialize
Initialize() [2/2]
unsafe void System.IO.UnmanagedMemoryStream.Initialize (SafeBuffer buffer, long offset, long length, FileAccess access) inline protected
Definition at line 32 of file UnmanagedMemoryStream.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            if (offset < 0L)
            {
                throw new ArgumentOutOfRangeException("offset", "Non-negative number required.");
            }
            if (length < 0L)
            {
                throw new ArgumentOutOfRangeException("length", "Non-negative number required.");
            }
            if (buffer.ByteLength < (ulong)(offset + length))
            {
                throw new ArgumentException("Offset and length were greater than the size of the SafeBuffer.");
            }
            if (access < FileAccess.Read || access > FileAccess.ReadWrite)
            {
                throw new ArgumentOutOfRangeException("access");
            }
            if (this._isOpen)
            {
                throw new InvalidOperationException("The method cannot be called twice on the same instance.");
            }
            byte* ptr = null;
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                buffer.AcquirePointer(ref ptr);
                if (ptr + offset + length < ptr)
                {
                    throw new ArgumentException("The UnmanagedMemoryStream capacity would wrap around the high end of the address space.");
                }
            }
            finally
            {
                if (ptr != null)
                {
                    buffer.ReleasePointer();
                }
            }
            this._offset = offset;
            this._buffer = buffer;
            this._length = length;
            this._capacity = length;
            this._access = access;
            this._isOpen = true;
        }
References System.IO.UnmanagedMemoryStream._isOpen, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.Runtime.InteropServices.SafeBuffer.ByteLength, System.L, System.length, System.offset, System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions(), and System.Runtime.InteropServices.SafeBuffer.ReleasePointer().
Referenced by System.IO.UnmanagedMemoryStream.UnmanagedMemoryStream(), System.IO.UnmanagedMemoryStream.UnmanagedMemoryStream(), System.IO.UnmanagedMemoryStream.UnmanagedMemoryStream(), and System.IO.UnmanagedMemoryStream.UnmanagedMemoryStream().