Terraria Decompiled: System.LocalDataStoreMgr.GetNamedDataSlot
GetNamedDataSlot()
LocalDataStoreSlot System.LocalDataStoreMgr.GetNamedDataSlot (string name) inline
Definition at line 130 of file LocalDataStoreMgr.cs.
        {
            bool flag = false;
            RuntimeHelpers.PrepareConstrainedRegions();
            LocalDataStoreSlot localDataStoreSlot;
            try
            {
                Monitor.Enter(this, ref flag);
                LocalDataStoreSlot valueOrDefault = this.m_KeyToSlotMap.GetValueOrDefault(name);
                if (valueOrDefault == null)
                {
                    localDataStoreSlot = this.AllocateNamedDataSlot(name);
                }
                else
                {
                    localDataStoreSlot = valueOrDefault;
                }
            }
            finally
            {
                if (flag)
                {
                    Monitor.Exit(this);
                }
            }
            return localDataStoreSlot;
        }
References System.LocalDataStoreMgr.AllocateNamedDataSlot(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.LocalDataStoreMgr.m_KeyToSlotMap, and System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions().
Referenced by System.Runtime.Remoting.Contexts.Context.GetNamedDataSlot(), and System.Threading.Thread.GetNamedDataSlot().