Terraria Decompiled: System.LocalDataStoreMgr.DeleteLocalDataStore
DeleteLocalDataStore()
void System.LocalDataStoreMgr.DeleteLocalDataStore (LocalDataStore store) inline
Definition at line 37 of file LocalDataStoreMgr.cs.
        {
            bool flag = false;
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                Monitor.Enter(this, ref flag);
                this.m_ManagedLocalDataStores.Remove(store);
            }
            finally
            {
                if (flag)
                {
                    Monitor.Exit(this);
                }
            }
        }
References System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.LocalDataStoreMgr.m_ManagedLocalDataStores, and System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions().
Referenced by System.LocalDataStore.Dispose().