Terraria Decompiled: System.LocalDataStoreMgr.CreateLocalDataStore
CreateLocalDataStore()
LocalDataStoreHolder System.LocalDataStoreMgr.CreateLocalDataStore () inline
Definition at line 14 of file LocalDataStoreMgr.cs.
        {
            LocalDataStore localDataStore = new LocalDataStore(this, this.m_SlotInfoTable.Length);
            LocalDataStoreHolder localDataStoreHolder = new LocalDataStoreHolder(localDataStore);
            bool flag = false;
            RuntimeHelpers.PrepareConstrainedRegions();
            try
            {
                Monitor.Enter(this, ref flag);
                this.m_ManagedLocalDataStores.Add(localDataStore);
            }
            finally
            {
                if (flag)
                {
                    Monitor.Exit(this);
                }
            }
            return localDataStoreHolder;
        }
References System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.LocalDataStoreMgr.m_ManagedLocalDataStores, System.LocalDataStoreMgr.m_SlotInfoTable, and System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions().
Referenced by System.Threading.Thread.SetData().