Terraria Decompiled: System.LocalDataStoreMgr.AllocateDataSlot
AllocateDataSlot()
LocalDataStoreSlot System.LocalDataStoreMgr.AllocateDataSlot () inline
Definition at line 57 of file LocalDataStoreMgr.cs.
        {
            bool flag = false;
            RuntimeHelpers.PrepareConstrainedRegions();
            LocalDataStoreSlot localDataStoreSlot2;
            try
            {
                Monitor.Enter(this, ref flag);
                int num = this.m_SlotInfoTable.Length;
                int num2 = this.m_FirstAvailableSlot;
                while (num2 < num && this.m_SlotInfoTable[num2])
                {
                    num2++;
                }
                if (num2 >= num)
                {
                    int num3;
                    if (num < 512)
                    {
                        num3 = num * 2;
                    }
                    else
                    {
                        num3 = num + 128;
                    }
                    bool[] array = new bool[num3];
                    Array.Copy(this.m_SlotInfoTable, array, num);
                    this.m_SlotInfoTable = array;
                }
                this.m_SlotInfoTable[num2] = true;
                int num4 = num2;
                long cookieGenerator = this.m_CookieGenerator;
                this.m_CookieGenerator = checked(cookieGenerator + 1L);
                LocalDataStoreSlot localDataStoreSlot = new LocalDataStoreSlot(this, num4, cookieGenerator);
                this.m_FirstAvailableSlot = num2 + 1;
                localDataStoreSlot2 = localDataStoreSlot;
            }
            finally
            {
                if (flag)
                {
                    Monitor.Exit(this);
                }
            }
            return localDataStoreSlot2;
        }
References System.array, System.Array.Copy(), System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), System.L, System.LocalDataStoreMgr.m_CookieGenerator, System.LocalDataStoreMgr.m_FirstAvailableSlot, System.LocalDataStoreMgr.m_SlotInfoTable, and System.Runtime.CompilerServices.RuntimeHelpers.PrepareConstrainedRegions().
Referenced by System.Runtime.Remoting.Contexts.Context.AllocateDataSlot(), System.Threading.Thread.AllocateDataSlot(), and System.LocalDataStoreMgr.AllocateNamedDataSlot().