Terraria Decompiled: Newtonsoft.Json.Converters.XContainerWrapper.WrapNode
WrapNode()
static IXmlNode Newtonsoft.Json.Converters.XContainerWrapper.WrapNode (XObject node) inline static package
Definition at line 76 of file XContainerWrapper.cs.
        {
            XDocument xdocument = node as XDocument;
            if (xdocument != null)
            {
                return new XDocumentWrapper(xdocument);
            }
            XElement xelement = node as XElement;
            if (xelement != null)
            {
                return new XElementWrapper(xelement);
            }
            XContainer xcontainer = node as XContainer;
            if (xcontainer != null)
            {
                return new XContainerWrapper(xcontainer);
            }
            XProcessingInstruction xprocessingInstruction = node as XProcessingInstruction;
            if (xprocessingInstruction != null)
            {
                return new XProcessingInstructionWrapper(xprocessingInstruction);
            }
            XText xtext = node as XText;
            if (xtext != null)
            {
                return new XTextWrapper(xtext);
            }
            XComment xcomment = node as XComment;
            if (xcomment != null)
            {
                return new XCommentWrapper(xcomment);
            }
            XAttribute xattribute = node as XAttribute;
            if (xattribute != null)
            {
                return new XAttributeWrapper(xattribute);
            }
            XDocumentType xdocumentType = node as XDocumentType;
            if (xdocumentType != null)
            {
                return new XDocumentTypeWrapper(xdocumentType);
            }
            return new XObjectWrapper(node);
        }
References Newtonsoft.Json.Converters.XContainerWrapper.XContainerWrapper(), and Newtonsoft.Json.Converters.XObjectWrapper.XObjectWrapper().
Referenced by Newtonsoft.Json.Converters.XmlNodeConverter.WrapXml().