Terraria Decompiled: System.SpanHelpers.IndexOfCultureHelper
IndexOfCultureHelper()
static int System.SpanHelpers.IndexOfCultureHelper (ReadOnlySpan< char > span, ReadOnlySpan< char > value, CompareInfo compareInfo) inline static
Definition at line 1700 of file SpanHelpers.cs.
        {
            if (GlobalizationMode.Invariant)
            {
                return CompareInfo.InvariantIndexOf(span, value, false);
            }
            return compareInfo.IndexOf(span, value, CompareOptions.None);
        }
References System.Globalization.CompareInfo.IndexOf(), System.Globalization.GlobalizationMode.Invariant, System.Globalization.CompareInfo.InvariantIndexOf(), and System.value.
Referenced by System.MemoryExtensions.IndexOf().