Terraria Decompiled: ReLogic.Content.FileChangeWatcher.AddFileOrDirectoryUpdateRecursive
AddFileOrDirectoryUpdateRecursive()
void ReLogic.Content.FileChangeWatcher< T >.AddFileOrDirectoryUpdateRecursive (T source, FileSystemEventArgs e) inline private
Definition at line 47 of file FileChangeWatcher.cs.
        {
            if (!Directory.Exists(e.FullPath))
            {
                this.AddUpdate(source, e);
                return;
            }
            string text = e.FullPath.Substring(0, e.FullPath.Length - e.Name.Length);
            foreach (string text2 in Directory.EnumerateFiles(e.FullPath, "*", 1))
            {
                this.AddUpdate(source, new FileSystemEventArgs(e.ChangeType, text, text2.Substring(text.Length)));
            }
        }
References ReLogic.Content.FileChangeWatcher< T >.AddUpdate(), System.IO.Directory.EnumerateFiles(), System.IO.Directory.Exists(), System.source, and System.text.
Referenced by ReLogic.Content.FileChangeWatcher< T >.NewWatcher().