Terraria Decompiled: System.SpanHelpers.IndexOfAny
IndexOfAny() [3/3]
static unsafe int System.SpanHelpers.IndexOfAny (ref byte searchSpace, int searchSpaceLength, ref byte value, int valueLength) inline static
Definition at line 85 of file SpanHelpers.cs.
        {
            if (valueLength == 0)
            {
                return 0;
            }
            int num = -1;
            for (int i = 0; i < valueLength; i++)
            {
                int num2 = SpanHelpers.IndexOf(ref searchSpace, *Unsafe.Add<byte>(ref value, i), searchSpaceLength);
                if (num2 < num)
                {
                    num = num2;
                    searchSpaceLength = num2;
                    if (num == 0)
                    {
                        break;
                    }
                }
            }
            return num;
        }
References System.SpanHelpers.IndexOf(), and System.value.
Referenced by System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), System.MemoryExtensions.IndexOfAny< T >(), and System.MemoryExtensions.IndexOfAny< T >().