Terraria Decompiled: System.SpanHelpers.LastIndexOf
LastIndexOf() [2/3]
static int System.SpanHelpers.LastIndexOf (ref byte searchSpace, int searchSpaceLength, ref byte value, int valueLength) inline static
Definition at line 207 of file SpanHelpers.cs.
        {
            if (valueLength == 0)
            {
                return 0;
            }
            byte b = value;
            ref byte ptr = ref Unsafe.Add<byte>(ref value, 1);
            int num = valueLength - 1;
            int num2 = 0;
            int num4;
            for (;;)
            {
                int num3 = searchSpaceLength - num2 - num;
                if (num3 <= 0)
                {
                    return -1;
                }
                num4 = SpanHelpers.LastIndexOf(ref searchSpace, b, num3);
                if (num4 == -1)
                {
                    return -1;
                }
                if (SpanHelpers.SequenceEqual<byte>(Unsafe.Add<byte>(ref searchSpace, num4 + 1), ref ptr, num))
                {
                    break;
                }
                num2 += num3 - num4;
            }
            return num4;
        }
References System.SpanHelpers.LastIndexOf(), System.SpanHelpers.SequenceEqual(), and System.value.
Referenced by System.String.LastIndexOf(), System.String.LastIndexOf(), System.SpanHelpers.LastIndexOf(), System.SpanHelpers.LastIndexOf< T >(), System.MemoryExtensions.LastIndexOf< T >(), System.MemoryExtensions.LastIndexOf< T >(), System.MemoryExtensions.LastIndexOf< T >(), System.MemoryExtensions.LastIndexOf< T >(), System.SpanHelpers.LastIndexOfAny(), and System.SpanHelpers.LastIndexOfAny< T >().