Terraria Decompiled: System.SpanHelpers.LastIndexOfAny
LastIndexOfAny() [3/3]
static unsafe int System.SpanHelpers.LastIndexOfAny (ref byte searchSpace, int searchSpaceLength, ref byte value, int valueLength) inline static
Definition at line 109 of file SpanHelpers.cs.
        {
            if (valueLength == 0)
            {
                return 0;
            }
            int num = -1;
            for (int i = 0; i < valueLength; i++)
            {
                int num2 = SpanHelpers.LastIndexOf(ref searchSpace, *Unsafe.Add<byte>(ref value, i), searchSpaceLength);
                if (num2 > num)
                {
                    num = num2;
                }
            }
            return num;
        }
References System.SpanHelpers.LastIndexOf(), and System.value.
Referenced by System.MemoryExtensions.LastIndexOfAny< T >(), System.MemoryExtensions.LastIndexOfAny< T >(), System.MemoryExtensions.LastIndexOfAny< T >(), System.MemoryExtensions.LastIndexOfAny< T >(), System.MemoryExtensions.LastIndexOfAny< T >(), and System.MemoryExtensions.LastIndexOfAny< T >().