Terraria Decompiled: System.SpanHelpers.IsReferenceOrContainsReferencesCore
IsReferenceOrContainsReferencesCore()
static bool System.SpanHelpers.IsReferenceOrContainsReferencesCore (Type type) inline static private
Definition at line 2063 of file SpanHelpers.cs.
        {
            if (type.GetTypeInfo().IsPrimitive)
            {
                return false;
            }
            if (!type.GetTypeInfo().IsValueType)
            {
                return true;
            }
            Type underlyingType = Nullable.GetUnderlyingType(type);
            if (underlyingType != null)
            {
                type = underlyingType;
            }
            if (type.GetTypeInfo().IsEnum)
            {
                return false;
            }
            foreach (FieldInfo fieldInfo in type.GetTypeInfo().DeclaredFields)
            {
                if (!fieldInfo.IsStatic && SpanHelpers.IsReferenceOrContainsReferencesCore(fieldInfo.FieldType))
                {
                    return true;
                }
            }
            return false;
        }
References System.Reflection.FieldInfo.FieldType, System.Type.GetTypeInfo(), System.Nullable< T >.GetUnderlyingType(), System.Runtime.InteropServices._Type.IsEnum, System.Runtime.InteropServices._Type.IsPrimitive, System.SpanHelpers.IsReferenceOrContainsReferencesCore(), System.Reflection.FieldInfo.IsStatic, and System.Runtime.InteropServices._Type.IsValueType.
Referenced by System.SpanHelpers.IsReferenceOrContainsReferencesCore().