Terraria Decompiled: System.SpanHelpers.SequenceEqual
SequenceEqual()
static unsafe bool System.SpanHelpers.SequenceEqual (ref byte first, ref byte second, ulong length) inline static
Definition at line 695 of file SpanHelpers.cs.
        {
            if (!Unsafe.AreSame<byte>(ref first, ref second))
            {
                IntPtr intPtr = (IntPtr)0;
                IntPtr intPtr2 = (IntPtr)length;
                if ((void*)intPtr2 >= sizeof(UIntPtr))
                {
                    intPtr2 -= sizeof(UIntPtr);
                    while ((void*)intPtr2 != (void*)intPtr)
                    {
                        if (Unsafe.ReadUnaligned<UIntPtr>(Unsafe.AddByteOffset<byte>(ref first, intPtr)) != Unsafe.ReadUnaligned<UIntPtr>(Unsafe.AddByteOffset<byte>(ref second, intPtr)))
{
                            return false;
                        }
                        intPtr += sizeof(UIntPtr);
                    }
                    return Unsafe.ReadUnaligned<UIntPtr>(Unsafe.AddByteOffset<byte>(ref first, intPtr2)) == Unsafe.ReadUnaligned<UIntPtr>(Unsafe.AddByteOffset<byte>(ref second, intPtr2));
                }
                while ((void*)intPtr2 != (void*)intPtr)
                {
                    if (*Unsafe.AddByteOffset<byte>(ref first, intPtr) != *Unsafe.AddByteOffset<byte>(ref second, intPtr))
                    {
                        return false;
                    }
                    intPtr += 1;
                }
                return true;
            }
            return true;
        }
References System.length.
Referenced by System.MemoryExtensions.EndsWith< T >(), System.MemoryExtensions.EndsWith< T >(), System.String.EqualsHelper(), System.SpanHelpers.IndexOf(), System.SpanHelpers.IndexOf< T >(), System.SpanHelpers.LastIndexOf(), System.SpanHelpers.LastIndexOf< T >(), System.MemoryExtensions.SequenceEqual< T >(), System.MemoryExtensions.SequenceEqual< T >(), System.String.StartsWith(), System.MemoryExtensions.StartsWith< T >(), System.MemoryExtensions.StartsWith< T >(), and System.String.StartsWithOrdinalUnchecked().