Terraria Decompiled: Microsoft.Xna.Framework.Vector2.Distance
Distance() [2/2]
static float Microsoft.Xna.Framework.Vector2.Distance (Vector2 value1, Vector2 value2) inline static
Definition at line 194 of file Vector2.cs.
        {
            float num = value1.X - value2.X;
            float num2 = value1.Y - value2.Y;
            return (float)Math.Sqrt((double)(num * num + num2 * num2));
        }
References System.Math.Sqrt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Player.AddCoinLuck(), Terraria.Graphics.VertexStrip.AddVertexPair(), Terraria.Graphics.VertexStrip.AddVertexPair(), Terraria.Graphics.VertexStrip.AddVertexPair(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_015_Flails(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.Projectile.AI_120_StardustGuardian_FindTarget(), Terraria.Projectile.AI_130_FlameBurstTower_FindTarget(), Terraria.Projectile.AI_134_Ballista_FindTarget(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_156_Think(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_202_TorchGodHelper(), Terraria.NPC.AI_FindNearbyBook(), Terraria.Graphics.Renderers.FakeFishParticle.BeRepelled(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.BeRepelled(), Terraria.Graphics.Renderers.FakeFishParticle.CanHit(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.Projectile.Colliding(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.Utils.Distance(), Terraria.Utils.Distance(), Terraria.Entity.Distance(), Terraria.GameContent.Drawing.TileDrawing.DistToWanderingCircle(), Terraria.Main.DoDraw_UpdateCameraPosition(), Terraria.GameContent.TeleportPylonsSystem.DoesPositionHaveEnoughNPCs(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.Player.DoUnbreakableWallScan(), Terraria.Main.DrawCursor(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawKite(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), Terraria.Map.TeleportPylonsMapLayer.DrawLine(), Terraria.Utils.DrawLine(), Terraria.Utils.DrawLine(), Terraria.Main.DrawMap(), Terraria.DataStructures.PlayerDrawLayers.DrawMeowcartTrail(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.Main.DrawPaladinsShieldBoundary(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_ChippysHeadband(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.Main.DrawStar(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.DataStructures.RichRoomCheckFeedback.EndScoring(), Terraria.DataStructures.RichRoomCheckFeedback.EndSpread(), Terraria.Player.FindSharpTearsSpot(), Terraria.GameContent.ExtraSpawnPointManager.GenerateExtraSpawns_Setup(), Terraria.GameContent.NearbyChests.GetChestsInRangeOf(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetClosestRoomTo(), Terraria.MessageBuffer.GetData(), Terraria.DataStructures.RichRoomCheckFeedback.GetHighestDistanceFromOrigin(), Terraria.GameContent.ShopHelper.GetNearbyResidentNPCs(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetSectionLength(), Terraria.UI.ItemSlot.GetTimeToAnimate(), Terraria.GameContent.Golf.GolfBallTrackRecord.GetTrackInfo(), Terraria.GameContent.ShopHelper.GetTravelingMerchantPrices(), Terraria.Player.GetZenithTarget(), Terraria.GameContent.ShopHelper.IsFarFromHome(), Terraria.GameContent.Golf.GolfHelper.IsGolfBallResting(), Terraria.Projectile.IsInRangeOfMeOrMyOwner(), Terraria.Player.isNearFairy(), Terraria.Player.isNearNPC(), Terraria.GameContent.Events.DD2Event.IsStandActive(), Terraria.Player.ItemCheck_Shoot(), Terraria.Main.ItemIconCacheVerification(), Terraria.Projectile.KiteLogic(), Terraria.Projectile.LavaBoulderExplosion(), Terraria.Utils.LineRectangleDistance(), Terraria.GameContent.Drawing.ParticleOrchestrator.MagnetFakeFish(), Terraria.WorldItem.MoveInWorld(), Terraria.GameContent.UI.States.UICharacterCreation.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIBestiaryTest.MoveToVisuallyClosestPoint(), Terraria.GameContent.UI.States.UIGamepadHelper.MoveToVisuallyClosestPoint(), Terraria.GameContent.Drawing.ParticleOrchestrator.PingFakeFish(), Terraria.Graphics.Renderers.ItemTransferParticle.Prepare(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), Terraria.GameContent.ObjectInteractions.PotionOfReturnSmartInteractCandidateProvider.ProvideCandidate(), Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.ProvideCandidate(), Terraria.GameContent.Drawing.ParticleOrchestrator.PushAwayFakeFish(), Terraria.GameContent.Golf.GolfState.ResetGolfBall(), Terraria.Utilities.NPCUtils.SearchForTarget(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), Terraria.DelegateMethods.SpreadDry(), Terraria.DelegateMethods.SpreadHoney(), Terraria.DelegateMethods.SpreadLava(), Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.DelegateMethods.SpreadTile(), Terraria.DelegateMethods.SpreadWater(), Terraria.Main.StartCameraTransitionForPlayerTeleport(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_Axe(), Terraria.GameContent.SmartCursorHelper.Step_BlocksLines(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches(), Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Hammers(), Terraria.GameContent.SmartCursorHelper.Step_LawnMower(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_Moss(), Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintRoller(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineShinies(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Pigronata(), Terraria.GameContent.SmartCursorHelper.Step_PlanterBox(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.GameContent.SmartCursorHelper.Step_StaffOfRegrowth(), Terraria.GameContent.SmartCursorHelper.Step_Torch(), Terraria.GameContent.SmartCursorHelper.Step_Walls(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), Terraria.Projectile.StormLightningLiquidCollisionCheck(), Terraria.NPC.TargetClosestUpgraded(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.Graphics.Renderers.FakeFishParticle.TryToBePinged(), Terraria.Player.Update(), Terraria.DataStructures.PlayerIntentionGuesser.Update(), Terraria.Graphics.CameraModifiers.PunchCameraModifier.Update(), Terraria.GameContent.Events.MoonlordDeathDrama.Update(), Terraria.Player.Update_AdjustTileTargetForDisplayJars(), Terraria.Player.UpdateBiomesIfMovedEnoughForBlackFade(), Terraria.DataStructures.NPCFollowState.UpdateBreadcrumbs(), Terraria.Player.UpdateBuffs(), Terraria.Main.UpdateCameraPan(), Terraria.Mount.UpdateEffects(), Terraria.NPC.UpdateNPC(), Terraria.Player.UpdatePettingAnimal(), Terraria.GameContent.LeashedEntities.EmpressButterflyLeashedCritter.VisualEffects(), Terraria.Player.VolatileGelatin(), and Terraria.Player.Yoraiz0rEye().