Terraria Decompiled: Microsoft.Xna.Framework.Vector2.Normalize
Normalize() [1/3]
void Microsoft.Xna.Framework.Vector2.Normalize () inline
Definition at line 109 of file Vector2.cs.
        {
            float num = 1f / (float)Math.Sqrt((double)(this.X * this.X + this.Y * this.Y));
            this.X *= num;
            this.Y *= num;
        }
References System.Math.Sqrt(), and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_1_Counterweights(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.Projectile.AI_105_SporeSac(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.Projectile.AI_111_DryadsWard(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_122_PirateGhost(), Terraria.Projectile.AI_150_GolfClubHelper(), Microsoft.Xna.Framework.Input.GamePadThumbSticks.ApplyCircularClamp(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Projectile.BoulderExplosion(), Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.Player.Counterweight(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Utils.DirectionFrom(), Terraria.Entity.DirectionFrom(), Terraria.Utils.DirectionTo(), Terraria.Entity.DirectionTo(), Terraria.Player.DoubleJumpVisuals(), Terraria.Map.MapOverlayDrawContext.DrawClamped(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.Utils.DrawLaser(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawStar(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.Mount.DrillSmartCursor_Walls(), Terraria.Player.DryCollision(), Terraria.GameContent.Golf.GolfHelper.FindVectorOnOval(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.Player.GetGrapplingForces(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_MeleeHitPVP(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.JumpMovement(), Terraria.Player.MoonLeechRope(), Terraria.Player.OnHit(), Terraria.GameContent.PortalHelper.PortalHelper(), Terraria.NPC.ReflectProjectile(), Terraria.Utils.SafeNormalize(), Terraria.Main.SortStardustDragonProjectiles(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_PaladinsHammerShockwave(), Terraria.Player.SpawnFastRunParticles(), Terraria.Physics.BallCollision.Step(), Terraria.Collision.StepConveyorBelt(), Terraria.NPC.StingerExplosion(), Terraria.Player.TorchAttack(), Terraria.Player.TorchGodsFlavor(), Terraria.Minecart.TrackCollision(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.GameContent.Shaders.BlizzardShaderData.Update(), Terraria.GameContent.Shaders.SandstormShaderData.Update(), Terraria.Dust.UpdateDust(), Terraria.GameInput.PlayerInput.UpdateHousingCursor(), Terraria.Player.UpdateLifeRegen(), Terraria.NPC.UpdateNPC(), Terraria.NPC.UpdateNPC_BuffApplyVFX(), Terraria.Mount.UseAbility(), Terraria.Utils.Vector2FromElipse(), and Terraria.Player.WingFrame().