Terraria Decompiled: Microsoft.Xna.Framework.Vector2.Dot
Dot() [2/2]
static float Microsoft.Xna.Framework.Vector2.Dot (Vector2 value1, Vector2 value2) inline static
Definition at line 256 of file Vector2.cs.
        {
            return value1.X * value2.X + value1.Y * value2.Y;
        }
References Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_015_Flails(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_120_HallowBoss(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_161_RapierStabs(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_DisplayDoll(), Terraria.Utils.ClosestPointOnLine(), Terraria.Physics.BallCollision.ClosestPointOnLineSegment(), Terraria.GameContent.Drawing.LensFlareElement.Draw(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), Terraria.UI.Gamepad.UILinkPointNavigator.DrawLink(), Terraria.Main.DrawProjDirect(), Terraria.GameInput.PlayerInput.GamePadInput(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.Utils.GetChaseResults(), Terraria.Physics.BallCollision.GetClosestEdgeToCircle(), Terraria.GameInput.LockOnHelper.GetClosestTarget(), Terraria.GameContent.Shaders.SepiaScreenShaderData.GetDaylightPowers(), Terraria.Player.GetGrapplingForces(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.KiteLogic(), Terraria.GameContent.Golf.GolfHelper.ContactListener.OnCollision(), Terraria.GameContent.SmartCursorHelper.Step_MinecartTracks(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.PortalHelper.TryPlacingPortal(), Terraria.Graphics.Renderers.FakeFishParticle.Update(), and Terraria.Player.UpdateNetOffset().