Terraria Decompiled: Microsoft.Xna.Framework.Vector2.Length
Length()
float Microsoft.Xna.Framework.Vector2.Length () inline
Definition at line 97 of file Vector2.cs.
        {
            return (float)Math.Sqrt((double)(this.X * this.X + this.Y * this.Y));
        }
References System.Math.Sqrt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities_Shimmer_TeleportToLandingSpot(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_009_MagicMissiles_Old(), Terraria.NPC.AI_015_KingSlime(), Terraria.Projectile.AI_019_Spears(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_047_GolemFist(), Terraria.Projectile.AI_062(), Terraria.NPC.AI_065_Butterflies(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Projectile.AI_067_TigerSpecialAttack(), Terraria.NPC.AI_069_DukeFishron(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.Projectile.AI_099_1_Counterweights(), Terraria.Projectile.AI_099_2_Yoyos(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_108_DivingFlyer(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_118_Seahorses(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_120_HallowBoss_DashTo(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_121_QueenSlime(), Terraria.NPC.AI_121_QueenSlime_FlyMovement(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_122_PirateGhost(), Terraria.NPC.AI_123_Deerclops(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.NPC.AI_126_StatueMimic(), Terraria.Projectile.AI_137_CanHit(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_147_Celeb2Rocket(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_159_PaperAirplanes(), Terraria.Projectile.AI_165_Whip(), Terraria.Projectile.AI_169_Smolstars(), Terraria.Projectile.AI_170_FairyGlowstick(), Terraria.Projectile.AI_174_MultisegmentPet(), Terraria.Projectile.AI_189_Volcano(), Terraria.GameContent.Dyes.ReflectiveArmorShaderData.Apply(), Terraria.Player.ApplyRangeCompensation(), Terraria.GameContent.LightningGenerator.CalcRotations(), Terraria.GameContent.Golf.GolfHelper.CalculateShotStrength(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ChasePlayerTop(), Terraria.Collision.CheckAABBvLineCollision(), Terraria.GameContent.SpelunkerProjectileHelper.CheckSpot(), Terraria.Projectile.Colliding(), Terraria.Player.CommandForbiddenStorm(), Terraria.Projectile.Damage_CanDealDamage(), Terraria.Projectile.Damage_GetProjectileSpecificDamageMultiplier(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.Audio.ActiveSound.DetermineIntendedVolume(), Terraria.Mount.Dismount(), Terraria.Mount.DoConfettiMinecartEffect(), Terraria.Player.DoDeadCellsGroundPoundEffect(), Terraria.Main.DoDraw_UpdateCameraPosition(), Terraria.Utils.DoesFitInCone(), Terraria.Mount.DoExhaustMinecartEffect(), Terraria.Mount.Draw(), Terraria.Graphics.EmpressBladeDrawer.Draw(), Terraria.Graphics.FinalFractalHelper.Draw(), Terraria.GameContent.Drawing.LensFlareElement.Draw(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.UI.Chat.ChatManager.DrawColorCodedStringShadow(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawFlower(), Terraria.Main.DrawInfoAccs(), Terraria.Main.DrawInterface_14_EntityHealthBars(), Terraria.Main.DrawInterface_33_MouseText(), Terraria.Main.DrawInterface_3_LaserRuler(), Terraria.Main.DrawInterface_4_Ruler(), Terraria.Main.DrawInterface_6_TileGridOption(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Main.DrawKite(), Terraria.GameContent.UI.WiresUI.WiresRadial.DrawLine(), ReLogic.Graphics.BasicDebugDrawer.DrawLine(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_Faeling(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_21_Head(), Terraria.Main.DrawProj_FairyQueenLance(), Terraria.Main.DrawProj_FairyQueenRangedItemShot(), Terraria.Main.DrawProj_FlailChains(), Terraria.Main.DrawProj_Flamethrower_Foxsparks(), Terraria.Main.DrawProjDirect(), Terraria.Main.DrawProjWithStarryTrail(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing(), Terraria.Main.DrawTrail(), Terraria.GameContent.Shaders.WaterShaderData.DrawWaves(), Terraria.Main.DrawWhip(), Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.Mount.DrillSmartCursor_Walls(), Terraria.Cinematics.DD2Film.DryadPortalFade(), Terraria.Projectile.EmitEnchantmentVisualsAt(), Microsoft.Xna.Framework.Input.GamePadThumbSticks.ExcludeCircularDeadZone(), Terraria.Projectile.FillWhipControlPoints(), Terraria.NPC.FindFrame(), Terraria.GameContent.LightningGenerator.GenerateBolt(), Terraria.Utils.GetChaseResults(), Terraria.MessageBuffer.GetData(), Terraria.Player.GetFarthestSpawnPositionOnLine(), Terraria.Player.GetGrapplingForces(), Terraria.Main.GetPlayerControlledCameraPan(), Terraria.Player.GrabItems(), Terraria.Projectile.HandleMovement(), Terraria.NPC.HitEffect(), Terraria.Minecart.Initialize(), Terraria.Mount.Initialize(), Terraria.Utils.IntersectsConeFastInaccurate(), Terraria.GameContent.Golf.GolfHelper.IsGolfBallResting(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheckWrapped(), Terraria.NPC.LadyBugKilled(), Terraria.NPC.LadyBugLuck(), Terraria.Collision.LaserScan(), Terraria.Player.MoonLeechRope(), Terraria.GameContent.LeashedEntities.LeashedKite.MoveKite(), Terraria.Utils.MoveTowards(), Terraria.Player.OnHit(), Microsoft.Xna.Framework.Input.Touch.GestureDetector.OnReleased(), Terraria.Audio.LegacySoundPlayer.PlaySound(), Terraria.GameContent.PortalHelper.PortalHelper(), Terraria.Graphics.Renderers.StormLightningParticle.Prepare(), Terraria.Graphics.VertexStrip.PrepareStrip(), Terraria.Graphics.VertexStrip.PrepareStripWithProceduralPadding(), Terraria.GameContent.RGB.EyeOfCthulhuShader.ProcessHighDetail(), Terraria.GameContent.RGB.MartianMadnessShader.ProcessHighDetail(), Terraria.GameContent.RGB.PillarShader.ProcessHighDetail(), Terraria.GameContent.RGB.TwinsShader.ProcessHighDetail(), Terraria.Projectile.RainbowBoulder_JumpToPosition(), Terraria.NPC.ReflectProjectile(), Terraria.GameContent.PortalHelper.RemoveIntersectingPortals(), Terraria.GameContent.PressurePlateHelper.Reset(), Terraria.SceneMetrics.Reset(), Terraria.GameContent.UI.States.UIWorldCreation.ResetSpecialSeedRing(), Terraria.Utils.rotateTowards(), Terraria.Projectile.SetDefaults(), Terraria.NPC.SetDefaults(), Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter.SetDefaults(), Terraria.Mount.SetMount(), ReLogic.Peripherals.RGB.Fragment.SetupCanvasBounds(), Terraria.Main.SortStardustDragonProjectiles(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_BlueLightningSmallLong(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsHeadEffect(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_LakeSparkle(), Terraria.DelegateMethods.Minecart.SpawnFartCloud(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnHelper_SpawnInLine(), Terraria.Physics.BallCollision.Step(), Terraria.GameContent.SmartCursorHelper.Step_BlocksFilling(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.Collision.TileCollisionInStepsOf16(), Terraria.Player.TorchAttack(), Terraria.Minecart.TrackCollision(), Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Vector2.TransformNormal(), Terraria.GameContent.PortalHelper.TryGoingThroughPortals(), Terraria.GameContent.PortalHelper.TryPlacingPortal(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.Update(), Terraria.Gore.Update(), Terraria.Player.SelectionRadial.Update(), Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Update(), Terraria.GameContent.LeashedEntities.LeashedKite.Update(), Terraria.Graphics.Renderers.FakeFishParticle.Update(), Terraria.Graphics.Renderers.LittleFlyingCritterParticle.Update(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Mount.UpdateFrame(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing(), Terraria.GameContent.Golf.GolfHelper.ValidateShot(), Terraria.GameContent.LeashedEntities.ShimmerFlyLeashedCritter.VisualEffects(), Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.WormlikeRoom(), Terraria.DelegateMethods.CharacterPreview.WormPet(), and Terraria.Player.Yoraiz0rEye().