Terraria Decompiled: Microsoft.Xna.Framework.Vector2.Lerp
Lerp() [2/2]
static Vector2 Microsoft.Xna.Framework.Vector2.Lerp (Vector2 value1, Vector2 value2, float amount) inline static
Definition at line 283 of file Vector2.cs.
        {
            return new Vector2(MathHelper.Lerp(value1.X, value2.X, amount), MathHelper.Lerp(value1.Y, value2.Y, amount));
        }
References Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Vector2.Vector2(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.Projectile.AI_009_MagicMissiles(), Terraria.Projectile.AI_015_Flails_Dust(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_075(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_110_Betsy(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_117_BloodNautilus(), Terraria.NPC.AI_120_HallowBoss(), Terraria.NPC.AI_120_HallowBoss_DashTo(), Terraria.Projectile.AI_120_StardustGuardian(), Terraria.NPC.AI_124_DeerclopsLeg(), Terraria.Projectile.AI_136_BetsyBreath(), Terraria.Projectile.AI_137_CanHit(), Terraria.Projectile.AI_145_BookStaffStorm(), Terraria.Projectile.AI_147_Explosion(), Terraria.Projectile.AI_158_BabyBird(), Terraria.Projectile.AI_162_TigerPounce(), Terraria.Projectile.AI_175_TitaniumStormShards(), Terraria.Projectile.AI_177_IceWhipSlicer(), Terraria.Projectile.AI_188_LightsBane(), Terraria.GameContent.Animations.Actions.Sprites.AScale.ApplyTo(), Terraria.DataStructures.PlayerDrawSet.BoringSetup(), Terraria.Projectile.Colliding(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.Main.DoDraw_UpdateCameraPosition(), Terraria.Projectile.DoPalAppearEffect(), Terraria.Mount.DoSpawnDust(), Terraria.Graphics.Renderers.ItemTransferParticle.Draw(), Terraria.GameContent.UI.IssueReportsIndicator.Draw(), Terraria.GameContent.UI.WorkshopPublishingIndicator.Draw(), Terraria.GameContent.Drawing.LensFlareElement.Draw(), Terraria.PopupText.DrawItemTextPopups(), Terraria.Map.TeleportPylonsMapLayer.DrawLine(), Terraria.Utils.DrawLine(), Terraria.Main.DrawMap(), Terraria.Main.DrawNPCDirect(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Main.DrawProj_Spear(), Terraria.Main.DrawProjDirect(), Terraria.DataStructures.PlayerDrawLayers.DrawStarboardRainbowTrail(), Terraria.Projectile.FillWhipControlPoints(), Terraria.NPC.FindFrame(), Terraria.GameContent.Golf.FancyGolfPredictionLine.GetPosition(), Terraria.NPC.HitEffect(), Terraria.GameContent.Golf.GolfHelper.HitGolfBall(), Terraria.Player.ItemCheck_GetMeleeHitboxParticles(), Terraria.Player.ItemCheck_Shoot(), Terraria.Projectile.KiteLogic(), Terraria.Player.MowTheLawn(), Terraria.Dust.QuickDustLine(), Terraria.GameContent.UI.UIDust.QuickDustLine(), Terraria.GameContent.Drawing.ParticleOrchestrator.SpawnHelper_SpawnInLine(), Terraria.Player.TouchBlockSurfaceCenter(), Terraria.WorldItem.TryCombiningIntoNearbyItems(), Terraria.UI.Gamepad.UILinkPointNavigator.Update(), Terraria.Projectile.Update(), Terraria.Graphics.Renderers.FakeFishParticle.Update(), Terraria.Mount.UpdateEffects(), and Terraria.Player.Yoraiz0rEye().