Terraria Decompiled: Microsoft.Xna.Framework.Vector2.Transform
Transform() [3/8]
static Vector2 Microsoft.Xna.Framework.Vector2.Transform (Vector2 position, Matrix matrix) inline static
Definition at line 430 of file Vector2.cs.
        {
            return new Vector2(position.X * matrix.M11 + position.Y * matrix.M21 + matrix.M41, position.X * matrix.M12 + position.Y * matrix.M22 + matrix.M42);
        }
References Microsoft.Xna.Framework.Matrix.M11, Microsoft.Xna.Framework.Matrix.M12, Microsoft.Xna.Framework.Matrix.M21, Microsoft.Xna.Framework.Matrix.M22, Microsoft.Xna.Framework.Matrix.M41, Microsoft.Xna.Framework.Matrix.M42, Microsoft.Xna.Framework.Vector2.Vector2(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Mount.DoSpawnDust(), Terraria.Main.DrawInterface_Resources_Breath(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_TransformDrawData(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), Terraria.UI.UIElement.GetClippingRectangle(), Terraria.GameInput.PlayerInput.HandleDpadSnap(), Terraria.NPC.HitEffect(), ReLogic.Graphics.DynamicSpriteFont.InternalDraw(), Terraria.Utils.ScreenToWorldPosition(), Terraria.Utils.ToScreenPosition(), Terraria.Minecart.TrackCollision(), Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Vector2.Transform(), Microsoft.Xna.Framework.Vector2.Transform(), and Microsoft.Xna.Framework.Vector2.Transform().