Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.Read
Read()
JsonSchema Newtonsoft.Json.Schema.JsonSchemaBuilder.Read (JsonReader reader) inline package
Definition at line 52 of file JsonSchemaBuilder.cs.
        {
            JToken jtoken = JToken.ReadFrom(reader);
            this._rootSchema = jtoken as JObject;
            JsonSchema jsonSchema = this.BuildSchema(jtoken);
            this.ResolveReferences(jsonSchema);
            return jsonSchema;
        }
References Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema(), Newtonsoft.Json.Linq.JToken.ReadFrom(), and Newtonsoft.Json.Schema.JsonSchemaBuilder.ResolveReferences().
Referenced by Newtonsoft.Json.Schema.JsonSchema.Read().