Terraria Decompiled: FullSerializer.Internal.fsMetaProperty.CommonInitialize
CommonInitialize()
void FullSerializer.Internal.fsMetaProperty.CommonInitialize (fsConfig config) inline private
Definition at line 35 of file fsMetaProperty.cs.
        {
            fsPropertyAttribute attribute = fsPortableReflection.GetAttribute<fsPropertyAttribute>(this._memberInfo);
            if (attribute != null)
            {
                this.JsonName = attribute.Name;
                this.OverrideConverterType = attribute.Converter;
            }
            if (string.IsNullOrEmpty(this.JsonName))
            {
                this.JsonName = config.GetJsonNameFromMemberName.Invoke(this.MemberName, this._memberInfo);
            }
        }
References FullSerializer.Internal.fsMetaProperty._memberInfo, FullSerializer.fsPropertyAttribute.Converter, FullSerializer.Internal.fsPortableReflection.GetAttribute(), FullSerializer.fsConfig.GetJsonNameFromMemberName, FullSerializer.Internal.fsMetaProperty.JsonName, FullSerializer.Internal.fsMetaProperty.MemberName, and FullSerializer.fsPropertyAttribute.Name.
Referenced by FullSerializer.Internal.fsMetaProperty.fsMetaProperty(), and FullSerializer.Internal.fsMetaProperty.fsMetaProperty().