Terraria Decompiled: FullSerializer.Internal.fsMetaProperty.Write
Write()
void FullSerializer.Internal.fsMetaProperty.Write (object context, object value) inline
Definition at line 169 of file fsMetaProperty.cs.
        {
            FieldInfo fieldInfo = this._memberInfo as FieldInfo;
            PropertyInfo propertyInfo = this._memberInfo as PropertyInfo;
            if (fieldInfo != null)
            {
                fieldInfo.SetValue(context, value);
                return;
            }
            if (propertyInfo != null)
            {
                MethodInfo setMethod = propertyInfo.GetSetMethod(true);
                if (setMethod != null)
                {
                    setMethod.Invoke(context, new object[] { value });
                }
            }
        }
References System.Reflection.PropertyInfo.GetSetMethod(), System.Reflection.MethodInfo.Invoke(), System.Reflection.FieldInfo.SetValue(), and System.value.
Referenced by FullSerializer.Internal.fsForwardConverter.TryDeserialize(), and FullSerializer.Internal.fsReflectedConverter.TryDeserialize().