Terraria Decompiled: FullSerializer.Internal.fsMetaProperty.Read
Read()
object FullSerializer.Internal.fsMetaProperty.Read (object context) inline
Definition at line 189 of file fsMetaProperty.cs.
        {
            if (this._memberInfo is PropertyInfo)
            {
                return ((PropertyInfo)this._memberInfo).GetValue(context, new object[0]);
            }
            return ((FieldInfo)this._memberInfo).GetValue(context);
        }
References FullSerializer.Internal.fsMetaProperty._memberInfo.
Referenced by FullSerializer.Internal.fsReflectedConverter.TryDeserialize(), FullSerializer.Internal.fsForwardConverter.TrySerialize(), and FullSerializer.Internal.fsReflectedConverter.TrySerialize().