Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.ResolveReferences
ResolveReferences()
JsonSchema Newtonsoft.Json.Schema.JsonSchemaBuilder.ResolveReferences (JsonSchema schema) inline private
Definition at line 68 of file JsonSchemaBuilder.cs.
        {
            if (schema.DeferredReference != null)
            {
                string text = schema.DeferredReference;
                bool flag = text.StartsWith("#", 4);
                if (flag)
                {
                    text = this.UnescapeReference(text);
                }
                JsonSchema jsonSchema = this._resolver.GetSchema(text);
                if (jsonSchema == null)
                {
                    if (flag)
                    {
                        string[] array = schema.DeferredReference.TrimStart(new char[] { '#' }).Split(new char[] { '/' }, 1);
                        JToken jtoken = this._rootSchema;
                        foreach (string text2 in array)
{
                            string text3 = this.UnescapeReference(text2);
                            if (jtoken.Type == JTokenType.Object)
{
                                jtoken = jtoken[text3];
                            }
                            else if (jtoken.Type == JTokenType.Array || jtoken.Type == JTokenType.Constructor)
{
                                int num;
                                if (int.TryParse(text3, ref num) && num >= 0 && num < Enumerable.Count<JToken>(jtoken))
{
                                    jtoken = jtoken[num];
                                }
                                else
{
                                    jtoken = null;
                                }
                            }
                            if (jtoken == null)
{
                                break;
                            }
                        }
                        if (jtoken != null)
{
                            jsonSchema = this.BuildSchema(jtoken);
                        }
                    }
                    if (jsonSchema == null)
                    {
                        throw new JsonException("Could not resolve schema reference '{0}'.".FormatWith(CultureInfo.InvariantCulture, schema.DeferredReference));
                    }
                }
                schema = jsonSchema;
            }
            if (schema.ReferencesResolved)
            {
                return schema;
            }
            schema.ReferencesResolved = true;
            if (schema.Extends != null)
            {
                for (int j = 0; j < schema.Extends.Count; j++)
                {
                    schema.Extends[j] = this.ResolveReferences(schema.Extends[j]);
                }
            }
            if (schema.Items != null)
            {
                for (int k = 0; k < schema.Items.Count; k++)
                {
                    schema.Items[k] = this.ResolveReferences(schema.Items[k]);
                }
            }
            if (schema.AdditionalItems != null)
            {
                schema.AdditionalItems = this.ResolveReferences(schema.AdditionalItems);
            }
            if (schema.PatternProperties != null)
            {
                foreach (KeyValuePair<string, JsonSchema> keyValuePair in Enumerable.ToList<KeyValuePair<string, JsonSchema>>(schema.PatternProperties))
                {
                    schema.PatternProperties[keyValuePair.Key] = this.ResolveReferences(keyValuePair.Value);
                }
            }
            if (schema.Properties != null)
            {
                foreach (KeyValuePair<string, JsonSchema> keyValuePair2 in Enumerable.ToList<KeyValuePair<string, JsonSchema>>(schema.Properties))
                {
                    schema.Properties[keyValuePair2.Key] = this.ResolveReferences(keyValuePair2.Value);
                }
            }
            if (schema.AdditionalProperties != null)
            {
                schema.AdditionalProperties = this.ResolveReferences(schema.AdditionalProperties);
            }
            return schema;
        }
References Newtonsoft.Json.Schema.JsonSchemaBuilder._resolver, Newtonsoft.Json.Schema.JsonSchemaBuilder._rootSchema, Newtonsoft.Json.Schema.JsonSchema.AdditionalItems, Newtonsoft.Json.Schema.JsonSchema.AdditionalProperties, System.array, Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema(), Newtonsoft.Json.Schema.JsonSchema.DeferredReference, Newtonsoft.Json.Schema.JsonSchema.Extends, Newtonsoft.Json.Schema.JsonSchemaResolver.GetSchema(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Schema.JsonSchema.Items, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Newtonsoft.Json.Schema.JsonSchema.PatternProperties, Newtonsoft.Json.Schema.JsonSchema.Properties, Newtonsoft.Json.Schema.JsonSchema.ReferencesResolved, Newtonsoft.Json.Schema.JsonSchemaBuilder.ResolveReferences(), System.text, Newtonsoft.Json.Schema.JsonSchemaBuilder.UnescapeReference(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.Read(), and Newtonsoft.Json.Schema.JsonSchemaBuilder.ResolveReferences().