Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema
BuildSchema()
JsonSchema Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema (JToken token) inline private
Definition at line 166 of file JsonSchemaBuilder.cs.
        {
            JObject jobject = token as JObject;
            if (jobject == null)
            {
                throw JsonException.Create(token, token.Path, "Expected object while parsing schema object, got {0}.".FormatWith(CultureInfo.InvariantCulture, token.Type));
            }
            JToken jtoken;
            if (jobject.TryGetValue("$ref", out jtoken))
            {
                return new JsonSchema
                {
                    DeferredReference = (string)jtoken
                };
            }
            string text = token.Path.Replace(".", "/").Replace("[", "/").Replace("]", string.Empty);
            if (!string.IsNullOrEmpty(text))
            {
                text = "/" + text;
            }
            text = "#" + text;
            JsonSchema jsonSchema;
            if (this._documentSchemas.TryGetValue(text, ref jsonSchema))
            {
                return jsonSchema;
            }
            this.Push(new JsonSchema
            {
                Location = text
            });
            this.ProcessSchemaProperties(jobject);
            return this.Pop();
        }
References Newtonsoft.Json.Schema.JsonSchemaBuilder._documentSchemas, Newtonsoft.Json.JsonException.Create(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JToken.Path, Newtonsoft.Json.Schema.JsonSchemaBuilder.Pop(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties(), Newtonsoft.Json.Schema.JsonSchemaBuilder.Push(), System.text, Newtonsoft.Json.Linq.JObject.TryGetValue(), and Newtonsoft.Json.Linq.JToken.Type.
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessAdditionalItems(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessAdditionalProperties(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessExtends(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessItems(), Newtonsoft.Json.Schema.JsonSchemaBuilder.Read(), and Newtonsoft.Json.Schema.JsonSchemaBuilder.ResolveReferences().