Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessExtends
ProcessExtends()
void Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessExtends (JToken token) inline private
Definition at line 450 of file JsonSchemaBuilder.cs.
        {
            IList<JsonSchema> list = new List<JsonSchema>();
            if (token.Type == JTokenType.Array)
            {
                using (IEnumerator<JToken> enumerator = token.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        JToken jtoken = enumerator.Current;
                        list.Add(this.BuildSchema(jtoken));
                    }
                    goto IL_0052;
                }
            }
            JsonSchema jsonSchema = this.BuildSchema(token);
            if (jsonSchema != null)
            {
                list.Add(jsonSchema);
            }
            IL_0052:
            if (list.Count > 0)
            {
                this.CurrentSchema.Extends = list;
            }
        }
References Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema(), System.Collections.Generic.IEnumerator< out T >.Current, Newtonsoft.Json.Linq.JToken.GetEnumerator(), System.list, System.Collections.IEnumerator.MoveNext(), and Newtonsoft.Json.Linq.JToken.Type.
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties().