Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties
ProcessSchemaProperties()
void Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties (JObject schemaObject) inline private
Definition at line 201 of file JsonSchemaBuilder.cs.
        {
            foreach (KeyValuePair<string, JToken> keyValuePair in schemaObject)
            {
                string key = keyValuePair.Key;
                uint num = <PrivateImplementationDetails>.ComputeStringHash(key);
                if (num <= 2223801888U)
                {
                    if (num <= 981021583U)
                    {
                        if (num <= 353304077U)
{
                            if (num != 299789532U)
{
                                if (num != 334560121U)
{
                                    if (num == 353304077U)
{
                                        if (key == "divisibleBy")
{
                                            this.CurrentSchema.DivisibleBy = new double?((double)keyValuePair.Value);
                                        }
                                    }
                                }
                                else if (key == "minItems")
{
                                    this.CurrentSchema.MinimumItems = new int?((int)keyValuePair.Value);
                                }
                            }
                            else if (key == "properties")
{
                                this.CurrentSchema.Properties = this.ProcessProperties(keyValuePair.Value);
                            }
                        }
                        else if (num <= 879704937U)
{
                            if (num != 479998177U)
{
                                if (num == 879704937U)
{
                                    if (key == "description")
{
                                        this.CurrentSchema.Description = (string)keyValuePair.Value;
                                    }
                                }
                            }
                            else if (key == "additionalProperties")
{
                                this.ProcessAdditionalProperties(keyValuePair.Value);
                            }
                        }
                        else if (num != 926444256U)
{
                            if (num == 981021583U)
{
                                if (key == "items")
{
                                    this.ProcessItems(keyValuePair.Value);
                                }
                            }
                        }
                        else if (key == "id")
{
                            this.CurrentSchema.Id = (string)keyValuePair.Value;
                        }
                    }
                    else if (num <= 1693958795U)
                    {
                        if (num != 1361572173U)
{
                            if (num != 1542649473U)
{
                                if (num == 1693958795U)
{
                                    if (key == "exclusiveMaximum")
{
                                        this.CurrentSchema.ExclusiveMaximum = new bool?((bool)keyValuePair.Value);
                                    }
                                }
                            }
                            else if (key == "maximum")
{
                                this.CurrentSchema.Maximum = new double?((double)keyValuePair.Value);
                            }
                        }
                        else if (key == "type")
{
                            this.CurrentSchema.Type = this.ProcessType(keyValuePair.Value);
                        }
                    }
                    else if (num <= 2051482624U)
                    {
                        if (num != 1913005517U)
{
                            if (num == 2051482624U)
{
                                if (key == "additionalItems")
{
                                    this.ProcessAdditionalItems(keyValuePair.Value);
                                }
                            }
                        }
                        else if (key == "exclusiveMinimum")
{
                            this.CurrentSchema.ExclusiveMinimum = new bool?((bool)keyValuePair.Value);
                        }
                    }
                    else if (num != 2171383808U)
                    {
                        if (num == 2223801888U)
{
                            if (key == "required")
{
                                this.CurrentSchema.Required = new bool?((bool)keyValuePair.Value);
                            }
                        }
                    }
                    else if (key == "enum")
                    {
                        this.ProcessEnum(keyValuePair.Value);
                    }
                }
                else if (num <= 2692244416U)
                {
                    if (num <= 2474713847U)
                    {
                        if (num != 2268922153U)
{
                            if (num != 2470140894U)
{
                                if (num == 2474713847U)
{
                                    if (key == "minimum")
{
                                        this.CurrentSchema.Minimum = new double?((double)keyValuePair.Value);
                                    }
                                }
                            }
                            else if (key == "default")
{
                                this.CurrentSchema.Default = keyValuePair.Value.DeepClone();
                            }
                        }
                        else if (key == "pattern")
{
                            this.CurrentSchema.Pattern = (string)keyValuePair.Value;
                        }
                    }
                    else if (num <= 2609687125U)
                    {
                        if (num != 2556802313U)
{
                            if (num == 2609687125U)
{
                                if (key == "requires")
{
                                    this.CurrentSchema.Requires = (string)keyValuePair.Value;
                                }
                            }
                        }
                        else if (key == "title")
{
                            this.CurrentSchema.Title = (string)keyValuePair.Value;
                        }
                    }
                    else if (num != 2642794062U)
                    {
                        if (num == 2692244416U)
{
                            if (key == "disallow")
{
                                this.CurrentSchema.Disallow = this.ProcessType(keyValuePair.Value);
                            }
                        }
                    }
                    else if (key == "extends")
                    {
                        this.ProcessExtends(keyValuePair.Value);
                    }
                }
                else if (num <= 3522602594U)
                {
                    if (num <= 3114108242U)
                    {
                        if (num != 2957261815U)
{
                            if (num == 3114108242U)
{
                                if (key == "format")
{
                                    this.CurrentSchema.Format = (string)keyValuePair.Value;
                                }
                            }
                        }
                        else if (key == "minLength")
{
                            this.CurrentSchema.MinimumLength = new int?((int)keyValuePair.Value);
                        }
                    }
                    else if (num != 3456888823U)
                    {
                        if (num == 3522602594U)
{
                            if (key == "uniqueItems")
{
                                this.CurrentSchema.UniqueItems = (bool)keyValuePair.Value;
                            }
                        }
                    }
                    else if (key == "readonly")
                    {
                        this.CurrentSchema.ReadOnly = new bool?((bool)keyValuePair.Value);
                    }
                }
                else if (num <= 3947606640U)
                {
                    if (num != 3526559937U)
                    {
                        if (num == 3947606640U)
{
                            if (key == "patternProperties")
{
                                this.CurrentSchema.PatternProperties = this.ProcessProperties(keyValuePair.Value);
                            }
                        }
                    }
                    else if (key == "maxLength")
                    {
                        this.CurrentSchema.MaximumLength = new int?((int)keyValuePair.Value);
                    }
                }
                else if (num != 4128829753U)
                {
                    if (num == 4244322099U)
                    {
                        if (key == "maxItems")
{
                            this.CurrentSchema.MaximumItems = new int?((int)keyValuePair.Value);
                        }
                    }
                }
                else if (key == "hidden")
                {
                    this.CurrentSchema.Hidden = new bool?((bool)keyValuePair.Value);
                }
            }
        }
References int, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.key, Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessAdditionalItems(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessAdditionalProperties(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessEnum(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessExtends(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessItems(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessProperties(), Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessType(), System.U, and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema().