Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.MapType
MapType() [2/2]
static JsonSchemaType Newtonsoft.Json.Schema.JsonSchemaBuilder.MapType (string type) inline static package
Definition at line 584 of file JsonSchemaBuilder.cs.
        {
            JsonSchemaType jsonSchemaType;
            if (!JsonSchemaConstants.JsonSchemaTypeMapping.TryGetValue(type, ref jsonSchemaType))
            {
                throw new JsonException("Invalid JSON schema type: {0}".FormatWith(CultureInfo.InvariantCulture, type));
            }
            return jsonSchemaType;
        }
References System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Schema.JsonSchemaConstants.JsonSchemaTypeMapping, and System.Collections.Generic.IDictionary< TKey, TValue >.TryGetValue().
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessType(), and Newtonsoft.Json.Schema.JsonSchemaWriter.WriteType().