Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessEnum
ProcessEnum()
void Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessEnum (JToken token) inline private
Definition at line 478 of file JsonSchemaBuilder.cs.
        {
            if (token.Type != JTokenType.Array)
            {
                throw JsonException.Create(token, token.Path, "Expected Array token while parsing enum values, got {0}.".FormatWith(CultureInfo.InvariantCulture, token.Type));
            }
            this.CurrentSchema.Enum = new List<JToken>();
            foreach (JToken jtoken in token)
            {
                this.CurrentSchema.Enum.Add(jtoken.DeepClone());
            }
        }
References Newtonsoft.Json.JsonException.Create(), Newtonsoft.Json.Schema.JsonSchemaBuilder.CurrentSchema, Newtonsoft.Json.Linq.JToken.DeepClone(), Newtonsoft.Json.Schema.JsonSchema.Enum, System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JToken.Path, and Newtonsoft.Json.Linq.JToken.Type.
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties().