Terraria Decompiled: Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessItems
ProcessItems()
void Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessItems (JToken token) inline private
Definition at line 534 of file JsonSchemaBuilder.cs.
        {
            this.CurrentSchema.Items = new List<JsonSchema>();
            JTokenType type = token.Type;
            if (type != JTokenType.Object)
            {
                if (type == JTokenType.Array)
                {
                    this.CurrentSchema.PositionalItemsValidation = true;
                    using (IEnumerator<JToken> enumerator = token.GetEnumerator())
                    {
                        while (enumerator.MoveNext())
{
                            JToken jtoken = enumerator.Current;
                            this.CurrentSchema.Items.Add(this.BuildSchema(jtoken));
                        }
                        return;
                    }
                }
                throw JsonException.Create(token, token.Path, "Expected array or JSON schema object, got {0}.".FormatWith(CultureInfo.InvariantCulture, token.Type));
            }
            this.CurrentSchema.Items.Add(this.BuildSchema(token));
            this.CurrentSchema.PositionalItemsValidation = false;
        }
References Newtonsoft.Json.Schema.JsonSchemaBuilder.BuildSchema(), Newtonsoft.Json.JsonException.Create(), System.Collections.Generic.IEnumerator< out T >.Current, Newtonsoft.Json.Schema.JsonSchemaBuilder.CurrentSchema, Newtonsoft.Json.Linq.JToken.GetEnumerator(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Schema.JsonSchema.Items, System.Collections.IEnumerator.MoveNext(), Newtonsoft.Json.Linq.JToken.Path, and Newtonsoft.Json.Linq.JToken.Type.
Referenced by Newtonsoft.Json.Schema.JsonSchemaBuilder.ProcessSchemaProperties().