Terraria Decompiled: Microsoft.Xna.Framework.FNAPlatform.FNAPlatform
FNAPlatform()
static Microsoft.Xna.Framework.FNAPlatform.FNAPlatform () inline static private
Definition at line 17 of file FNAPlatform.cs.
        {
            bool flag = Environment.GetEnvironmentVariable("FNA_PLATFORM_BACKEND") == "SDL2";
            if (!flag)
            {
                FNAPlatform.SetEnv = new FNAPlatform.SetEnvFunc(SDL3_FNAPlatform.SetEnv);
            }
            else
            {
                FNAPlatform.SetEnv = new FNAPlatform.SetEnvFunc(SDL2_FNAPlatform.SetEnv);
            }
            LaunchParameters launchParameters = new LaunchParameters();
            string text;
            if (launchParameters.TryGetValue("enablehighdpi", out text) && text == "1")
            {
                Environment.SetEnvironmentVariable("FNA_GRAPHICS_ENABLE_HIGHDPI", "1");
            }
            if (launchParameters.TryGetValue("gldevice", out text))
            {
                FNAPlatform.SetEnv("FNA3D_FORCE_DRIVER", text);
            }
            if (launchParameters.TryGetValue("enablelateswaptear", out text) && text == "1")
            {
                FNAPlatform.SetEnv("FNA3D_ENABLE_LATESWAPTEAR", "1");
            }
            if (launchParameters.TryGetValue("mojoshaderprofile", out text))
            {
                FNAPlatform.SetEnv("FNA3D_MOJOSHADER_PROFILE", text);
            }
            if (launchParameters.TryGetValue("backbufferscalenearest", out text) && text == "1")
            {
                FNAPlatform.SetEnv("FNA3D_BACKBUFFER_SCALE_NEAREST", "1");
            }
            if (launchParameters.TryGetValue("usescancodes", out text) && text == "1")
            {
                Environment.SetEnvironmentVariable("FNA_KEYBOARD_USE_SCANCODES", "1");
            }
            if (launchParameters.TryGetValue("disableglobalmouse", out text) && text == "1")
            {
                Environment.SetEnvironmentVariable("FNA_MOUSE_DISABLE_GLOBAL_ACCESS", "1");
            }
            if (launchParameters.TryGetValue("nukesteaminput", out text) && text == "1")
            {
                Environment.SetEnvironmentVariable("FNA_NUKE_STEAM_INPUT", "1");
            }
            Environment.SetEnvironmentVariable("FNA_SDL_FORCE_BASE_PATH", Environment.GetEnvironmentVariable("FNA_SDL2_FORCE_BASE_PATH"));
            if (!flag)
            {
                FNAPlatform.Malloc = new FNAPlatform.MallocFunc(SDL3_FNAPlatform.Malloc);
                FNAPlatform.Free = new FNAPlatform.FreeFunc(global::SDL3.SDL.SDL_free);
                FNAPlatform.CreateWindow = new FNAPlatform.CreateWindowFunc(SDL3_FNAPlatform.CreateWindow);
                FNAPlatform.DisposeWindow = new FNAPlatform.DisposeWindowFunc(SDL3_FNAPlatform.DisposeWindow);
                FNAPlatform.ApplyWindowChanges = new FNAPlatform.ApplyWindowChangesFunc(SDL3_FNAPlatform.ApplyWindowChanges);
                FNAPlatform.ScaleForWindow = new FNAPlatform.ScaleForWindowFunc(SDL3_FNAPlatform.ScaleForWindow);
                FNAPlatform.GetWindowBounds = new FNAPlatform.GetWindowBoundsFunc(SDL3_FNAPlatform.GetWindowBounds);
                FNAPlatform.GetWindowResizable = new FNAPlatform.GetWindowResizableFunc(SDL3_FNAPlatform.GetWindowResizable);
                FNAPlatform.SetWindowResizable = new FNAPlatform.SetWindowResizableFunc(SDL3_FNAPlatform.SetWindowResizable);
                FNAPlatform.GetWindowBorderless = new FNAPlatform.GetWindowBorderlessFunc(SDL3_FNAPlatform.GetWindowBorderless);
                FNAPlatform.SetWindowBorderless = new FNAPlatform.SetWindowBorderlessFunc(SDL3_FNAPlatform.SetWindowBorderless);
                FNAPlatform.SetWindowTitle = new FNAPlatform.SetWindowTitleFunc(SDL3_FNAPlatform.SetWindowTitle);
                FNAPlatform.IsScreenKeyboardShown = new FNAPlatform.IsScreenKeyboardShownFunc(SDL3_FNAPlatform.IsScreenKeyboardShown);
                FNAPlatform.RegisterGame = new FNAPlatform.RegisterGameFunc(SDL3_FNAPlatform.RegisterGame);
                FNAPlatform.UnregisterGame = new FNAPlatform.UnregisterGameFunc(SDL3_FNAPlatform.UnregisterGame);
                FNAPlatform.PollEvents = new FNAPlatform.PollEventsFunc(SDL3_FNAPlatform.PollEvents);
                FNAPlatform.GetGraphicsAdapters = new FNAPlatform.GetGraphicsAdaptersFunc(SDL3_FNAPlatform.GetGraphicsAdapters);
                FNAPlatform.GetCurrentDisplayMode = new FNAPlatform.GetCurrentDisplayModeFunc(SDL3_FNAPlatform.GetCurrentDisplayMode);
                FNAPlatform.GetMonitorHandle = new FNAPlatform.GetMonitorHandleFunc(SDL3_FNAPlatform.GetMonitorHandle);
                FNAPlatform.GetKeyFromScancode = new FNAPlatform.GetKeyFromScancodeFunc(SDL3_FNAPlatform.GetKeyFromScancode);
                FNAPlatform.IsTextInputActive = new FNAPlatform.IsTextInputActiveFunc(SDL3_FNAPlatform.IsTextInputActive);
                FNAPlatform.StartTextInput = new FNAPlatform.StartTextInputFunc(SDL3_FNAPlatform.StartTextInput);
                FNAPlatform.StopTextInput = new FNAPlatform.StopTextInputFunc(SDL3_FNAPlatform.StopTextInput);
                FNAPlatform.SetTextInputRectangle = new FNAPlatform.SetTextInputRectangleFunc(SDL3_FNAPlatform.SetTextInputRectangle);
                FNAPlatform.GetMouseState = new FNAPlatform.GetMouseStateFunc(SDL3_FNAPlatform.GetMouseState);
                FNAPlatform.SetMousePosition = new FNAPlatform.SetMousePositionFunc(SDL3_FNAPlatform.WarpMouseInWindow);
                FNAPlatform.OnIsMouseVisibleChanged = new FNAPlatform.OnIsMouseVisibleChangedFunc(SDL3_FNAPlatform.OnIsMouseVisibleChanged);
                FNAPlatform.GetRelativeMouseMode = new FNAPlatform.GetRelativeMouseModeFunc(SDL3_FNAPlatform.GetRelativeMouseMode);
                FNAPlatform.SetRelativeMouseMode = new FNAPlatform.SetRelativeMouseModeFunc(SDL3_FNAPlatform.SetRelativeMouseMode);
                FNAPlatform.GetGamePadCapabilities = new FNAPlatform.GetGamePadCapabilitiesFunc(SDL3_FNAPlatform.GetGamePadCapabilities);
                FNAPlatform.GetGamePadState = new FNAPlatform.GetGamePadStateFunc(SDL3_FNAPlatform.GetGamePadState);
                FNAPlatform.SetGamePadVibration = new FNAPlatform.SetGamePadVibrationFunc(SDL3_FNAPlatform.SetGamePadVibration);
                FNAPlatform.SetGamePadTriggerVibration = new FNAPlatform.SetGamePadTriggerVibrationFunc(SDL3_FNAPlatform.SetGamePadTriggerVibration);
                FNAPlatform.GetGamePadGUID = new FNAPlatform.GetGamePadGUIDFunc(SDL3_FNAPlatform.GetGamePadGUID);
                FNAPlatform.SetGamePadLightBar = new FNAPlatform.SetGamePadLightBarFunc(SDL3_FNAPlatform.SetGamePadLightBar);
                FNAPlatform.GetGamePadGyro = new FNAPlatform.GetGamePadGyroFunc(SDL3_FNAPlatform.GetGamePadGyro);
                FNAPlatform.GetGamePadAccelerometer = new FNAPlatform.GetGamePadAccelerometerFunc(SDL3_FNAPlatform.GetGamePadAccelerometer);
                FNAPlatform.GetStorageRoot = new FNAPlatform.GetStorageRootFunc(SDL3_FNAPlatform.GetStorageRoot);
                FNAPlatform.GetDriveInfo = new FNAPlatform.GetDriveInfoFunc(SDL3_FNAPlatform.GetDriveInfo);
                FNAPlatform.ReadFileToPointer = new FNAPlatform.ReadFileToPointerFunc(SDL3_FNAPlatform.ReadToPointer);
                FNAPlatform.FreeFilePointer = new FNAPlatform.FreeFilePointerFunc(SDL3_FNAPlatform.FreeFilePointer);
                FNAPlatform.ShowRuntimeError = new FNAPlatform.ShowRuntimeErrorFunc(SDL3_FNAPlatform.ShowRuntimeError);
                FNAPlatform.GetMicrophones = new FNAPlatform.GetMicrophonesFunc(SDL3_FNAPlatform.GetMicrophones);
                FNAPlatform.GetMicrophoneSamples = new FNAPlatform.GetMicrophoneSamplesFunc(SDL3_FNAPlatform.GetMicrophoneSamples);
                FNAPlatform.GetMicrophoneQueuedBytes = new FNAPlatform.GetMicrophoneQueuedBytesFunc(SDL3_FNAPlatform.GetMicrophoneQueuedBytes);
                FNAPlatform.StartMicrophone = new FNAPlatform.StartMicrophoneFunc(SDL3_FNAPlatform.StartMicrophone);
                FNAPlatform.StopMicrophone = new FNAPlatform.StopMicrophoneFunc(SDL3_FNAPlatform.StopMicrophone);
                FNAPlatform.GetTouchCapabilities = new FNAPlatform.GetTouchCapabilitiesFunc(SDL3_FNAPlatform.GetTouchCapabilities);
                FNAPlatform.UpdateTouchPanelState = new FNAPlatform.UpdateTouchPanelStateFunc(SDL3_FNAPlatform.UpdateTouchPanelState);
                FNAPlatform.GetNumTouchFingers = new FNAPlatform.GetNumTouchFingersFunc(SDL3_FNAPlatform.GetNumTouchFingers);
                FNAPlatform.SupportsOrientationChanges = new FNAPlatform.SupportsOrientationChangesFunc(SDL3_FNAPlatform.SupportsOrientationChanges);
                FNAPlatform.NeedsPlatformMainLoop = new FNAPlatform.NeedsPlatformMainLoopFunc(SDL3_FNAPlatform.NeedsPlatformMainLoop);
                FNAPlatform.RunPlatformMainLoop = new FNAPlatform.RunPlatformMainLoopFunc(SDL3_FNAPlatform.RunPlatformMainLoop);
            }
            else
            {
                FNAPlatform.Malloc = new FNAPlatform.MallocFunc(SDL2_FNAPlatform.Malloc);
                FNAPlatform.Free = new FNAPlatform.FreeFunc(global::SDL2.SDL.SDL_free);
                FNAPlatform.CreateWindow = new FNAPlatform.CreateWindowFunc(SDL2_FNAPlatform.CreateWindow);
                FNAPlatform.DisposeWindow = new FNAPlatform.DisposeWindowFunc(SDL2_FNAPlatform.DisposeWindow);
                FNAPlatform.ApplyWindowChanges = new FNAPlatform.ApplyWindowChangesFunc(SDL2_FNAPlatform.ApplyWindowChanges);
                FNAPlatform.ScaleForWindow = new FNAPlatform.ScaleForWindowFunc(SDL2_FNAPlatform.ScaleForWindow);
                FNAPlatform.GetWindowBounds = new FNAPlatform.GetWindowBoundsFunc(SDL2_FNAPlatform.GetWindowBounds);
                FNAPlatform.GetWindowResizable = new FNAPlatform.GetWindowResizableFunc(SDL2_FNAPlatform.GetWindowResizable);
                FNAPlatform.SetWindowResizable = new FNAPlatform.SetWindowResizableFunc(SDL2_FNAPlatform.SetWindowResizable);
                FNAPlatform.GetWindowBorderless = new FNAPlatform.GetWindowBorderlessFunc(SDL2_FNAPlatform.GetWindowBorderless);
                FNAPlatform.SetWindowBorderless = new FNAPlatform.SetWindowBorderlessFunc(SDL2_FNAPlatform.SetWindowBorderless);
                FNAPlatform.SetWindowTitle = new FNAPlatform.SetWindowTitleFunc(SDL2_FNAPlatform.SetWindowTitle);
                FNAPlatform.IsScreenKeyboardShown = new FNAPlatform.IsScreenKeyboardShownFunc(SDL2_FNAPlatform.IsScreenKeyboardShown);
                FNAPlatform.RegisterGame = new FNAPlatform.RegisterGameFunc(SDL2_FNAPlatform.RegisterGame);
                FNAPlatform.UnregisterGame = new FNAPlatform.UnregisterGameFunc(SDL2_FNAPlatform.UnregisterGame);
                FNAPlatform.PollEvents = new FNAPlatform.PollEventsFunc(SDL2_FNAPlatform.PollEvents);
                FNAPlatform.GetGraphicsAdapters = new FNAPlatform.GetGraphicsAdaptersFunc(SDL2_FNAPlatform.GetGraphicsAdapters);
                FNAPlatform.GetCurrentDisplayMode = new FNAPlatform.GetCurrentDisplayModeFunc(SDL2_FNAPlatform.GetCurrentDisplayMode);
                FNAPlatform.GetMonitorHandle = new FNAPlatform.GetMonitorHandleFunc(SDL2_FNAPlatform.GetMonitorHandle);
                FNAPlatform.GetKeyFromScancode = new FNAPlatform.GetKeyFromScancodeFunc(SDL2_FNAPlatform.GetKeyFromScancode);
                FNAPlatform.IsTextInputActive = new FNAPlatform.IsTextInputActiveFunc(SDL2_FNAPlatform.IsTextInputActive);
                FNAPlatform.StartTextInput = new FNAPlatform.StartTextInputFunc(SDL2_FNAPlatform.StartTextInput);
                FNAPlatform.StopTextInput = new FNAPlatform.StopTextInputFunc(SDL2_FNAPlatform.StopTextInput);
                FNAPlatform.SetTextInputRectangle = new FNAPlatform.SetTextInputRectangleFunc(SDL2_FNAPlatform.SetTextInputRectangle);
                FNAPlatform.GetMouseState = new FNAPlatform.GetMouseStateFunc(SDL2_FNAPlatform.GetMouseState);
                FNAPlatform.SetMousePosition = new FNAPlatform.SetMousePositionFunc(global::SDL2.SDL.SDL_WarpMouseInWindow);
                FNAPlatform.OnIsMouseVisibleChanged = new FNAPlatform.OnIsMouseVisibleChangedFunc(SDL2_FNAPlatform.OnIsMouseVisibleChanged);
                FNAPlatform.GetRelativeMouseMode = new FNAPlatform.GetRelativeMouseModeFunc(SDL2_FNAPlatform.GetRelativeMouseMode);
                FNAPlatform.SetRelativeMouseMode = new FNAPlatform.SetRelativeMouseModeFunc(SDL2_FNAPlatform.SetRelativeMouseMode);
                FNAPlatform.GetGamePadCapabilities = new FNAPlatform.GetGamePadCapabilitiesFunc(SDL2_FNAPlatform.GetGamePadCapabilities);
                FNAPlatform.GetGamePadState = new FNAPlatform.GetGamePadStateFunc(SDL2_FNAPlatform.GetGamePadState);
                FNAPlatform.SetGamePadVibration = new FNAPlatform.SetGamePadVibrationFunc(SDL2_FNAPlatform.SetGamePadVibration);
                FNAPlatform.SetGamePadTriggerVibration = new FNAPlatform.SetGamePadTriggerVibrationFunc(SDL2_FNAPlatform.SetGamePadTriggerVibration);
                FNAPlatform.GetGamePadGUID = new FNAPlatform.GetGamePadGUIDFunc(SDL2_FNAPlatform.GetGamePadGUID);
                FNAPlatform.SetGamePadLightBar = new FNAPlatform.SetGamePadLightBarFunc(SDL2_FNAPlatform.SetGamePadLightBar);
                FNAPlatform.GetGamePadGyro = new FNAPlatform.GetGamePadGyroFunc(SDL2_FNAPlatform.GetGamePadGyro);
                FNAPlatform.GetGamePadAccelerometer = new FNAPlatform.GetGamePadAccelerometerFunc(SDL2_FNAPlatform.GetGamePadAccelerometer);
                FNAPlatform.GetStorageRoot = new FNAPlatform.GetStorageRootFunc(SDL2_FNAPlatform.GetStorageRoot);
                FNAPlatform.GetDriveInfo = new FNAPlatform.GetDriveInfoFunc(SDL2_FNAPlatform.GetDriveInfo);
                FNAPlatform.ReadFileToPointer = new FNAPlatform.ReadFileToPointerFunc(SDL2_FNAPlatform.ReadToPointer);
                FNAPlatform.FreeFilePointer = new FNAPlatform.FreeFilePointerFunc(SDL2_FNAPlatform.FreeFilePointer);
                FNAPlatform.ShowRuntimeError = new FNAPlatform.ShowRuntimeErrorFunc(SDL2_FNAPlatform.ShowRuntimeError);
                FNAPlatform.GetMicrophones = new FNAPlatform.GetMicrophonesFunc(SDL2_FNAPlatform.GetMicrophones);
                FNAPlatform.GetMicrophoneSamples = new FNAPlatform.GetMicrophoneSamplesFunc(SDL2_FNAPlatform.GetMicrophoneSamples);
                FNAPlatform.GetMicrophoneQueuedBytes = new FNAPlatform.GetMicrophoneQueuedBytesFunc(SDL2_FNAPlatform.GetMicrophoneQueuedBytes);
                FNAPlatform.StartMicrophone = new FNAPlatform.StartMicrophoneFunc(SDL2_FNAPlatform.StartMicrophone);
                FNAPlatform.StopMicrophone = new FNAPlatform.StopMicrophoneFunc(SDL2_FNAPlatform.StopMicrophone);
                FNAPlatform.GetTouchCapabilities = new FNAPlatform.GetTouchCapabilitiesFunc(SDL2_FNAPlatform.GetTouchCapabilities);
                FNAPlatform.UpdateTouchPanelState = new FNAPlatform.UpdateTouchPanelStateFunc(SDL2_FNAPlatform.UpdateTouchPanelState);
                FNAPlatform.GetNumTouchFingers = new FNAPlatform.GetNumTouchFingersFunc(SDL2_FNAPlatform.GetNumTouchFingers);
                FNAPlatform.SupportsOrientationChanges = new FNAPlatform.SupportsOrientationChangesFunc(SDL2_FNAPlatform.SupportsOrientationChanges);
                FNAPlatform.NeedsPlatformMainLoop = new FNAPlatform.NeedsPlatformMainLoopFunc(SDL2_FNAPlatform.NeedsPlatformMainLoop);
                FNAPlatform.RunPlatformMainLoop = new FNAPlatform.RunPlatformMainLoopFunc(SDL2_FNAPlatform.RunPlatformMainLoop);
            }
            FNALoggerEXT.Initialize();
            if (!flag)
            {
                AppDomain.CurrentDomain.ProcessExit += SDL3_FNAPlatform.ProgramExit;
                FNAPlatform.TitleLocation = SDL3_FNAPlatform.ProgramInit(launchParameters);
            }
            else
            {
                AppDomain.CurrentDomain.ProcessExit += SDL2_FNAPlatform.ProgramExit;
                FNAPlatform.TitleLocation = SDL2_FNAPlatform.ProgramInit(launchParameters);
            }
            FNALoggerEXT.HookFNA3D();
        }
References Microsoft.Xna.Framework.SDL2_FNAPlatform.ApplyWindowChanges(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ApplyWindowChanges(), Microsoft.Xna.Framework.FNAPlatform.ApplyWindowChangesFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow(), Microsoft.Xna.Framework.SDL3_FNAPlatform.CreateWindow(), Microsoft.Xna.Framework.FNAPlatform.CreateWindowFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.DisposeWindow(), Microsoft.Xna.Framework.SDL3_FNAPlatform.DisposeWindow(), Microsoft.Xna.Framework.FNAPlatform.DisposeWindowFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.FreeFilePointer(), Microsoft.Xna.Framework.SDL3_FNAPlatform.FreeFilePointer(), Microsoft.Xna.Framework.FNAPlatform.FreeFilePointerFunc(), Microsoft.Xna.Framework.FNAPlatform.FreeFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetCurrentDisplayMode(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetCurrentDisplayMode(), Microsoft.Xna.Framework.FNAPlatform.GetCurrentDisplayModeFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetDriveInfo(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetDriveInfo(), Microsoft.Xna.Framework.FNAPlatform.GetDriveInfoFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadAccelerometer(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadAccelerometer(), Microsoft.Xna.Framework.FNAPlatform.GetGamePadAccelerometerFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadCapabilities(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadCapabilities(), Microsoft.Xna.Framework.FNAPlatform.GetGamePadCapabilitiesFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadGUID(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadGUID(), Microsoft.Xna.Framework.FNAPlatform.GetGamePadGUIDFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadGyro(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadGyro(), Microsoft.Xna.Framework.FNAPlatform.GetGamePadGyroFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGamePadState(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGamePadState(), Microsoft.Xna.Framework.FNAPlatform.GetGamePadStateFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetGraphicsAdapters(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetGraphicsAdapters(), Microsoft.Xna.Framework.FNAPlatform.GetGraphicsAdaptersFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetKeyFromScancode(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetKeyFromScancode(), Microsoft.Xna.Framework.FNAPlatform.GetKeyFromScancodeFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMicrophoneQueuedBytes(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMicrophoneQueuedBytes(), Microsoft.Xna.Framework.FNAPlatform.GetMicrophoneQueuedBytesFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMicrophones(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMicrophones(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMicrophoneSamples(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMicrophoneSamples(), Microsoft.Xna.Framework.FNAPlatform.GetMicrophoneSamplesFunc(), Microsoft.Xna.Framework.FNAPlatform.GetMicrophonesFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMonitorHandle(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMonitorHandle(), Microsoft.Xna.Framework.FNAPlatform.GetMonitorHandleFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetMouseState(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetMouseState(), Microsoft.Xna.Framework.FNAPlatform.GetMouseStateFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetNumTouchFingers(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetNumTouchFingers(), Microsoft.Xna.Framework.FNAPlatform.GetNumTouchFingersFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetRelativeMouseMode(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetRelativeMouseMode(), Microsoft.Xna.Framework.FNAPlatform.GetRelativeMouseModeFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetStorageRoot(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetStorageRoot(), Microsoft.Xna.Framework.FNAPlatform.GetStorageRootFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetTouchCapabilities(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetTouchCapabilities(), Microsoft.Xna.Framework.FNAPlatform.GetTouchCapabilitiesFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetWindowBorderless(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowBorderless(), Microsoft.Xna.Framework.FNAPlatform.GetWindowBorderlessFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetWindowBounds(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowBounds(), Microsoft.Xna.Framework.FNAPlatform.GetWindowBoundsFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetWindowResizable(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetWindowResizable(), Microsoft.Xna.Framework.FNAPlatform.GetWindowResizableFunc(), Microsoft.Xna.Framework.FNALoggerEXT.HookFNA3D(), Microsoft.Xna.Framework.FNALoggerEXT.Initialize(), Microsoft.Xna.Framework.SDL2_FNAPlatform.IsScreenKeyboardShown(), Microsoft.Xna.Framework.SDL3_FNAPlatform.IsScreenKeyboardShown(), Microsoft.Xna.Framework.FNAPlatform.IsScreenKeyboardShownFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.IsTextInputActive(), Microsoft.Xna.Framework.SDL3_FNAPlatform.IsTextInputActive(), Microsoft.Xna.Framework.FNAPlatform.IsTextInputActiveFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.Malloc(), Microsoft.Xna.Framework.SDL3_FNAPlatform.Malloc(), Microsoft.Xna.Framework.FNAPlatform.MallocFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.NeedsPlatformMainLoop(), Microsoft.Xna.Framework.SDL3_FNAPlatform.NeedsPlatformMainLoop(), Microsoft.Xna.Framework.FNAPlatform.NeedsPlatformMainLoopFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.OnIsMouseVisibleChanged(), Microsoft.Xna.Framework.SDL3_FNAPlatform.OnIsMouseVisibleChanged(), Microsoft.Xna.Framework.FNAPlatform.OnIsMouseVisibleChangedFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents(), Microsoft.Xna.Framework.FNAPlatform.PollEventsFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramExit(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramExit(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.FNAPlatform.ReadFileToPointerFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ReadToPointer(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ReadToPointer(), Microsoft.Xna.Framework.SDL2_FNAPlatform.RegisterGame(), Microsoft.Xna.Framework.SDL3_FNAPlatform.RegisterGame(), Microsoft.Xna.Framework.FNAPlatform.RegisterGameFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.RunPlatformMainLoop(), Microsoft.Xna.Framework.SDL3_FNAPlatform.RunPlatformMainLoop(), Microsoft.Xna.Framework.FNAPlatform.RunPlatformMainLoopFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ScaleForWindow(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ScaleForWindow(), Microsoft.Xna.Framework.FNAPlatform.ScaleForWindowFunc(), SDL2.SDL.SDL_free(), SDL2.SDL.SDL_WarpMouseInWindow(), Microsoft.Xna.Framework.FNAPlatform.SetEnv, Microsoft.Xna.Framework.SDL2_FNAPlatform.SetEnv(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetEnv(), Microsoft.Xna.Framework.FNAPlatform.SetEnvFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadLightBar(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetGamePadLightBar(), Microsoft.Xna.Framework.FNAPlatform.SetGamePadLightBarFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadTriggerVibration(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetGamePadTriggerVibration(), Microsoft.Xna.Framework.FNAPlatform.SetGamePadTriggerVibrationFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetGamePadVibration(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetGamePadVibration(), Microsoft.Xna.Framework.FNAPlatform.SetGamePadVibrationFunc(), Microsoft.Xna.Framework.FNAPlatform.SetMousePositionFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetRelativeMouseMode(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetRelativeMouseMode(), Microsoft.Xna.Framework.FNAPlatform.SetRelativeMouseModeFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetTextInputRectangle(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetTextInputRectangle(), Microsoft.Xna.Framework.FNAPlatform.SetTextInputRectangleFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetWindowBorderless(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetWindowBorderless(), Microsoft.Xna.Framework.FNAPlatform.SetWindowBorderlessFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetWindowResizable(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetWindowResizable(), Microsoft.Xna.Framework.FNAPlatform.SetWindowResizableFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SetWindowTitle(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SetWindowTitle(), Microsoft.Xna.Framework.FNAPlatform.SetWindowTitleFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ShowRuntimeError(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ShowRuntimeError(), Microsoft.Xna.Framework.FNAPlatform.ShowRuntimeErrorFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.StartMicrophone(), Microsoft.Xna.Framework.SDL3_FNAPlatform.StartMicrophone(), Microsoft.Xna.Framework.FNAPlatform.StartMicrophoneFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.StartTextInput(), Microsoft.Xna.Framework.SDL3_FNAPlatform.StartTextInput(), Microsoft.Xna.Framework.FNAPlatform.StartTextInputFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.StopMicrophone(), Microsoft.Xna.Framework.SDL3_FNAPlatform.StopMicrophone(), Microsoft.Xna.Framework.FNAPlatform.StopMicrophoneFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.StopTextInput(), Microsoft.Xna.Framework.SDL3_FNAPlatform.StopTextInput(), Microsoft.Xna.Framework.FNAPlatform.StopTextInputFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.SupportsOrientationChanges(), Microsoft.Xna.Framework.SDL3_FNAPlatform.SupportsOrientationChanges(), Microsoft.Xna.Framework.FNAPlatform.SupportsOrientationChangesFunc(), System.text, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.SDL2_FNAPlatform.UnregisterGame(), Microsoft.Xna.Framework.SDL3_FNAPlatform.UnregisterGame(), Microsoft.Xna.Framework.FNAPlatform.UnregisterGameFunc(), Microsoft.Xna.Framework.SDL2_FNAPlatform.UpdateTouchPanelState(), Microsoft.Xna.Framework.SDL3_FNAPlatform.UpdateTouchPanelState(), Microsoft.Xna.Framework.FNAPlatform.UpdateTouchPanelStateFunc(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.WarpMouseInWindow().