Terraria Decompiled: System.IO.FileStreamAsyncResult.SetComplete
SetComplete() [1/3]
void System.IO.FileStreamAsyncResult.SetComplete (Exception e) inline
Definition at line 28 of file FileStreamAsyncResult.cs.
        {
            this.exc = e;
            this.completed = true;
            this.wh.Set();
            if (this.cb != null)
            {
                this.cb(this);
            }
        }
References System.IO.FileStreamAsyncResult.cb, System.Threading.EventWaitHandle.Set(), and System.IO.FileStreamAsyncResult.wh.
Referenced by System.IO.FileStreamAsyncResult.SetComplete(), and System.IO.FileStreamAsyncResult.SetComplete().