Terraria Decompiled: Newtonsoft.Json.Serialization.JsonTypeReflector.GetAssociateMetadataTypeFromAttribute
GetAssociateMetadataTypeFromAttribute()
static Type Newtonsoft.Json.Serialization.JsonTypeReflector.GetAssociateMetadataTypeFromAttribute (Type type) inline static private
Definition at line 182 of file JsonTypeReflector.cs.
        {
            foreach (Attribute attribute in ReflectionUtils.GetAttributes(type, null, true))
            {
                Type type2 = attribute.GetType();
                if (string.Equals(type2.FullName, "System.ComponentModel.DataAnnotations.MetadataTypeAttribute", 4))
                {
                    if (JsonTypeReflector._metadataTypeAttributeReflectionObject == null)
                    {
                        JsonTypeReflector._metadataTypeAttributeReflectionObject = ReflectionObject.Create(type2, new string[] { "MetadataClassType" });
                    }
                    return (Type)JsonTypeReflector._metadataTypeAttributeReflectionObject.GetValue(attribute, "MetadataClassType");
                }
            }
            return null;
        }
References Newtonsoft.Json.Serialization.JsonTypeReflector._metadataTypeAttributeReflectionObject, Newtonsoft.Json.Utilities.ReflectionObject.Create(), System.Type.FullName, Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes(), and Newtonsoft.Json.Utilities.ReflectionObject.GetValue().