Terraria Decompiled: Newtonsoft.Json.Serialization.JsonTypeReflector.GetCreator
GetCreator()
static Func< object[], object > Newtonsoft.Json.Serialization.JsonTypeReflector.GetCreator (Type type) inline static private
Definition at line 140 of file JsonTypeReflector.cs.
        {
            Func<object> defaultConstructor = (ReflectionUtils.HasDefaultConstructor(type, false) ? JsonTypeReflector.ReflectionDelegateFactory.CreateDefaultConstructor<object>(type) : null);
            return delegate(object[] parameters)
            {
                object obj;
                try
                {
                    if (parameters != null)
                    {
                        Type[] array = Enumerable.ToArray<Type>(Enumerable.Select<object, Type>(parameters, (object param) => param.GetType()));
                        ConstructorInfo constructor = type.GetConstructor(array);
                        if (!(null != constructor))
{
                            throw new JsonException("No matching parameterized constructor found for '{0}'.".FormatWith(CultureInfo.InvariantCulture, type));
                        }
                        obj = JsonTypeReflector.ReflectionDelegateFactory.CreateParameterizedConstructor(constructor)(parameters);
                    }
                    else
                    {
                        if (defaultConstructor == null)
{
                            throw new JsonException("No parameterless constructor defined for '{0}'.".FormatWith(CultureInfo.InvariantCulture, type));
                        }
                        obj = defaultConstructor.Invoke();
                    }
                }
                catch (Exception ex)
                {
                    throw new JsonException("Error creating '{0}'.".FormatWith(CultureInfo.InvariantCulture, type), ex);
                }
                return obj;
            };
        }
References System.array, Newtonsoft.Json.Utilities.ReflectionDelegateFactory.CreateParameterizedConstructor(), System.Type.GetConstructor(), Newtonsoft.Json.Utilities.ReflectionUtils.HasDefaultConstructor(), System.Globalization.CultureInfo.InvariantCulture, System.obj, and Newtonsoft.Json.Serialization.JsonTypeReflector.ReflectionDelegateFactory.