Terraria Decompiled: Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataMemberAttribute
GetDataMemberAttribute()
static DataMemberAttribute Newtonsoft.Json.Serialization.JsonTypeReflector.GetDataMemberAttribute (MemberInfo memberInfo) inline static
Definition at line 55 of file JsonTypeReflector.cs.
        {
            if (memberInfo.MemberType() == 4)
            {
                return CachedAttributeGetter<DataMemberAttribute>.GetAttribute(memberInfo);
            }
            PropertyInfo propertyInfo = (PropertyInfo)memberInfo;
            DataMemberAttribute dataMemberAttribute = CachedAttributeGetter<DataMemberAttribute>.GetAttribute(propertyInfo);
            if (dataMemberAttribute == null && propertyInfo.IsVirtual())
            {
                Type type = propertyInfo.DeclaringType;
                while (dataMemberAttribute == null && type != null)
                {
                    PropertyInfo propertyInfo2 = (PropertyInfo)ReflectionUtils.GetMemberInfoFromType(type, propertyInfo);
                    if (propertyInfo2 != null && propertyInfo2.IsVirtual())
                    {
                        dataMemberAttribute = CachedAttributeGetter<DataMemberAttribute>.GetAttribute(propertyInfo2);
                    }
                    type = type.BaseType();
                }
            }
            return dataMemberAttribute;
        }
References System.Type.BaseType, System.Reflection.MemberInfo.DeclaringType, Newtonsoft.Json.Serialization.CachedAttributeGetter< T >.GetAttribute(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberInfoFromType(), and System.Reflection.MemberInfo.MemberType.
Referenced by Newtonsoft.Json.Serialization.DefaultContractResolver.SetPropertySettingsFromAttributes().