Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.FromSecurityElement
FromSecurityElement()
StrongNameIdentityPermission.SNIP System.Security.Permissions.StrongNameIdentityPermission.FromSecurityElement (SecurityElement se) inline private
Definition at line 171 of file StrongNameIdentityPermission.cs.
        {
            string text = se.Attribute("Name");
            StrongNamePublicKeyBlob strongNamePublicKeyBlob = StrongNamePublicKeyBlob.FromString(se.Attribute("PublicKeyBlob"));
            string text2 = se.Attribute("AssemblyVersion");
            Version version = ((text2 == null) ? null : new Version(text2));
            return new StrongNameIdentityPermission.SNIP(strongNamePublicKeyBlob, text, version);
        }
References System.Security.SecurityElement.Attribute(), System.Security.Permissions.StrongNamePublicKeyBlob.FromString(), System.text, System.Security.Permissions.StrongNameIdentityPermission.Version, and System.Security.Permissions.StrongNameIdentityPermission.version.
Referenced by System.Security.Permissions.StrongNameIdentityPermission.FromXml().