Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.FromXml
FromXml()
override void System.Security.Permissions.StrongNameIdentityPermission.FromXml (SecurityElement e) inline
Implements System.Security.ISecurityEncodable.
Definition at line 150 of file StrongNameIdentityPermission.cs.
        {
            CodeAccessPermission.CheckSecurityElement(e, "e", 1, 1);
            this._list.Clear();
            if (e.Children != null && e.Children.Count > 0)
            {
                using (IEnumerator enumerator = e.Children.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        object obj = enumerator.Current;
                        SecurityElement securityElement = (SecurityElement)obj;
                        this._list.Add(this.FromSecurityElement(securityElement));
                    }
                    return;
                }
            }
            this._list.Add(this.FromSecurityElement(e));
        }
References System.Security.Permissions.StrongNameIdentityPermission._list, System.Collections.ArrayList.Add(), System.Security.CodeAccessPermission.CheckSecurityElement(), System.Security.SecurityElement.Children, System.Collections.ArrayList.Clear(), System.Collections.ArrayList.Count, System.Collections.IEnumerator.Current, System.Security.Permissions.StrongNameIdentityPermission.FromSecurityElement(), System.Collections.ArrayList.GetEnumerator(), System.Collections.IEnumerator.MoveNext(), and System.obj.