Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.ToXml
ToXml()
override SecurityElement System.Security.Permissions.StrongNameIdentityPermission.ToXml () inline
Implements System.Security.ISecurityEncodable.
Definition at line 248 of file StrongNameIdentityPermission.cs.
        {
            SecurityElement securityElement = base.Element(1);
            if (this._list.Count > 1)
            {
                using (IEnumerator enumerator = this._list.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        object obj = enumerator.Current;
                        StrongNameIdentityPermission.SNIP snip = (StrongNameIdentityPermission.SNIP)obj;
                        SecurityElement securityElement2 = new SecurityElement("StrongName");
                        this.ToSecurityElement(securityElement2, snip);
                        securityElement.AddChild(securityElement2);
                    }
                    return securityElement;
                }
            }
            if (this._list.Count == 1)
            {
                StrongNameIdentityPermission.SNIP snip2 = (StrongNameIdentityPermission.SNIP)this._list[0];
                if (!this.IsEmpty(snip2))
                {
                    this.ToSecurityElement(securityElement, snip2);
                }
            }
            return securityElement;
        }
References System.Security.Permissions.StrongNameIdentityPermission._list, System.Security.SecurityElement.AddChild(), System.Collections.ArrayList.Count, System.Collections.IEnumerator.Current, System.Collections.ArrayList.GetEnumerator(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Collections.IEnumerator.MoveNext(), System.obj, and System.Security.Permissions.StrongNameIdentityPermission.ToSecurityElement().