Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.Intersect
Intersect()
override IPermission System.Security.Permissions.StrongNameIdentityPermission.Intersect (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 181 of file StrongNameIdentityPermission.cs.
        {
            if (target == null)
            {
                return null;
            }
            StrongNameIdentityPermission strongNameIdentityPermission = target as StrongNameIdentityPermission;
            if (strongNameIdentityPermission == null)
            {
                throw new ArgumentException(Locale.GetText("Wrong permission type."));
            }
            if (this.IsEmpty() || strongNameIdentityPermission.IsEmpty())
            {
                return null;
            }
            if (!this.Match(strongNameIdentityPermission.Name))
            {
                return null;
            }
            string text = ((this.Name.Length < strongNameIdentityPermission.Name.Length) ? this.Name : strongNameIdentityPermission.Name);
            if (!this.Version.Equals(strongNameIdentityPermission.Version))
            {
                return null;
            }
            if (!this.PublicKey.Equals(strongNameIdentityPermission.PublicKey))
            {
                return null;
            }
            return new StrongNameIdentityPermission(this.PublicKey, text, this.Version);
        }
References System.Security.Permissions.StrongNamePublicKeyBlob.Equals(), System.Version.Equals(), Locale.GetText(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Security.Permissions.StrongNameIdentityPermission.Match(), System.Security.Permissions.StrongNameIdentityPermission.Name, System.Security.Permissions.StrongNameIdentityPermission.PublicKey, System.Security.Permissions.StrongNameIdentityPermission.StrongNameIdentityPermission(), System.text, and System.Security.Permissions.StrongNameIdentityPermission.Version.