Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.Union
Union()
override IPermission System.Security.Permissions.StrongNameIdentityPermission.Union (IPermission target) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 295 of file StrongNameIdentityPermission.cs.
        {
            StrongNameIdentityPermission strongNameIdentityPermission = this.Cast(target);
            if (strongNameIdentityPermission == null || strongNameIdentityPermission.IsEmpty())
            {
                return this.Copy();
            }
            if (this.IsEmpty())
            {
                return strongNameIdentityPermission.Copy();
            }
            StrongNameIdentityPermission strongNameIdentityPermission2 = (StrongNameIdentityPermission)this.Copy();
            foreach (object obj in strongNameIdentityPermission._list)
            {
                StrongNameIdentityPermission.SNIP snip = (StrongNameIdentityPermission.SNIP)obj;
                if (!this.IsEmpty(snip) && !this.Contains(snip))
                {
                    strongNameIdentityPermission2._list.Add(snip);
                }
            }
            return strongNameIdentityPermission2;
        }
References System.Security.Permissions.StrongNameIdentityPermission.Cast(), System.Security.Permissions.StrongNameIdentityPermission.Contains(), System.Security.Permissions.StrongNameIdentityPermission.Copy(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.obj, and System.Security.Permissions.StrongNameIdentityPermission.StrongNameIdentityPermission().