Terraria Decompiled: System.Security.Permissions.StrongNameIdentityPermission.IsSubsetOf
IsSubsetOf()
override bool System.Security.Permissions.StrongNameIdentityPermission.IsSubsetOf (IPermission target) inline
Implements System.Security.IPermission.
Definition at line 213 of file StrongNameIdentityPermission.cs.
        {
            StrongNameIdentityPermission strongNameIdentityPermission = this.Cast(target);
            if (strongNameIdentityPermission == null)
            {
                return this.IsEmpty();
            }
            if (this.IsEmpty())
            {
                return true;
            }
            if (this.IsUnrestricted())
            {
                return strongNameIdentityPermission.IsUnrestricted();
            }
            if (strongNameIdentityPermission.IsUnrestricted())
            {
                return true;
            }
            foreach (object obj in this._list)
            {
                StrongNameIdentityPermission.SNIP snip = (StrongNameIdentityPermission.SNIP)obj;
                foreach (object obj2 in strongNameIdentityPermission._list)
                {
                    StrongNameIdentityPermission.SNIP snip2 = (StrongNameIdentityPermission.SNIP)obj2;
                    if (!snip.IsSubsetOf(snip2))
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References System.Security.Permissions.StrongNameIdentityPermission._list, System.Security.Permissions.StrongNameIdentityPermission.Cast(), System.Security.Permissions.StrongNameIdentityPermission.IsEmpty(), System.Security.Permissions.StrongNameIdentityPermission.IsUnrestricted(), and System.obj.