Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings
Paintings()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings (DungeonData data) inline
Definition at line 28 of file DungeonGlobalPaintings.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            float num = (float)Main.maxTilesX / 4200f;
            DungeonGlobalPaintings.lihzahrdPaintingsPlaced = 0;
            switch (WorldGen.GetWorldSize())
            {
            default:
                DungeonGlobalPaintings.lihzahrdPaintingsMax = 1;
                break;
            case 1:
                DungeonGlobalPaintings.lihzahrdPaintingsMax = 2;
                break;
            case 2:
                DungeonGlobalPaintings.lihzahrdPaintingsMax = 2 + genRand.Next(2);
                break;
            }
            int num2 = data.wallVariants[0];
            double num3 = Math.Max(1.0, data.globalFeatureScalar * 0.75);
            int num4 = (int)((double)(100f * num) * num3);
            int num5 = num4 * 3;
            int i = 0;
            while (i < num4)
            {
                num5--;
                if (num5 <= 0)
                {
                    break;
                }
                int num6 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                int num7 = genRand.Next((int)Main.worldSurface, data.dungeonBounds.Bottom);
                int num8 = 1000;
                while (!DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num6, num7].wall, false) || Main.tile[num6, num7].active())
                {
                    num8--;
                    if (num8 <= 0)
                    {
                        break;
                    }
                    num6 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                    num7 = genRand.Next((int)Main.worldSurface, data.dungeonBounds.Bottom);
                }
                if (!WorldGen.InWorld(num6, num7, 5) || Main.tile[num6, num7] == null)
                {
                    goto IL_01BB;
                }
                DungeonGenerationStyleData styleForWall = DungeonGenerationStyles.GetStyleForWall(data.genVars.dungeonGenerationStyles, (int)Main.tile[num6, num7].wall);
                if (styleForWall == null || styleForWall.Style != 10 || DungeonGlobalPaintings.lihzahrdPaintingsPlaced < DungeonGlobalPaintings.lihzahrdPaintingsMax)
                {
                    goto IL_01BB;
                }
                i--;
                IL_0B4D:
                i++;
                continue;
                IL_01BB:
                int num9;
                int num10;
                int num11;
                int num12;
                for (int j = 0; j < 2; j++)
                {
                    num9 = num6;
                    num10 = num6;
                    while (num9 > 20 && !Main.tile[num9, num7].active() && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num9, num7].wall, false))
                    {
                        num9--;
                    }
                    num9++;
                    while (num10 < Main.maxTilesX - 20 && !Main.tile[num10, num7].active() && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num10, num7].wall, false))
                    {
                        num10++;
                    }
                    num10--;
                    num6 = (num9 + num10) / 2;
                    num11 = num7;
                    num12 = num7;
                    while (num11 > 20 && !Main.tile[num6, num11].active() && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num6, num11].wall, false))
                    {
                        num11--;
                    }
                    num11++;
                    while (num12 < Main.maxTilesY - 20 && !Main.tile[num6, num12].active() && DungeonUtils.IsConsideredDungeonWall((int)Main.tile[num6, num12].wall, false))
                    {
                        num12++;
                    }
                    num12--;
                    num7 = (num11 + num12) / 2;
                }
                num9 = num6;
                num10 = num6;
                while (num9 > 20 && !Main.tile[num9, num7].active() && !Main.tile[num9, num7 - 1].active() && !Main.tile[num9, num7 + 1].active())
                {
                    num9--;
                }
                num9++;
                while (num10 < Main.maxTilesX - 20 && !Main.tile[num10, num7].active() && !Main.tile[num10, num7 - 1].active() && !Main.tile[num10, num7 + 1].active())
                {
                    num10++;
                }
                num10--;
                num11 = num7;
                num12 = num7;
                while (num11 > 20 && !Main.tile[num6, num11].active() && !Main.tile[num6 - 1, num11].active() && !Main.tile[num6 + 1, num11].active())
                {
                    num11--;
                }
                num11++;
                while (num12 < Main.maxTilesY - 20 && !Main.tile[num6, num12].active() && !Main.tile[num6 - 1, num12].active() && !Main.tile[num6 + 1, num12].active())
                {
                    num12++;
                }
                num12--;
                num6 = (num9 + num10) / 2;
                num7 = (num11 + num12) / 2;
                int num13 = num10 - num9;
                int num14 = num12 - num11;
                if (num13 <= 7 || num14 <= 5)
                {
                    goto IL_0B4D;
                }
                bool[] array = new bool[3];
                array[0] = true;
                if (num13 > num14 * 3 && num13 > 21)
                {
                    array[1] = true;
                }
                if (num14 > num13 * 3 && num14 > 21)
                {
                    array[2] = true;
                }
                int num15 = genRand.Next(3);
                if ((int)Main.tile[num6, num7].wall == num2)
                {
                    num15 = 0;
                }
                while (!array[num15])
                {
                    num15 = genRand.Next(3);
                }
                if (WorldGen.nearPicture2(num6, num7))
                {
                    num15 = -1;
                }
                if (num15 == 0)
                {
                    PaintingEntry paintingEntry = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num6, num7].wall);
                    new DungeonBounds();
                    if (data.CanGenerateFeatureInArea(this, num6, num7, 3) && !WorldGen.nearPicture(num6, num7))
                    {
                        DungeonGlobalPaintings.Paintings_PlacePainting(num6, num7, paintingEntry);
                        goto IL_0B4D;
                    }
                    goto IL_0B4D;
                }
                else if (num15 == 1)
                {
                    PaintingEntry paintingEntry2 = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num6, num7].wall);
                    if (!data.CanGenerateFeatureInArea(this, num6, num7, 3))
                    {
                        goto IL_0B4D;
                    }
                    if (!Main.tile[num6, num7].active())
                    {
                        DungeonGlobalPaintings.Paintings_PlacePainting(num6, num7, paintingEntry2);
                    }
                    if (!Main.tile[num6, num7].active())
                    {
                        int num16 = num6;
                        int num17 = num7;
                        int num18 = num7;
                        for (int k = 0; k < 2; k++)
{
                            num6 += 7;
                            num11 = num18;
                            num12 = num18;
                            while (num11 > 0 && !Main.tile[num6, num11].active() && !Main.tile[num6 - 1, num11].active() && !Main.tile[num6 + 1, num11].active())
{
                                num11--;
                            }
                            num11++;
                            while (num12 < Main.maxTilesY - 1 && !Main.tile[num6, num12].active() && !Main.tile[num6 - 1, num12].active() && !Main.tile[num6 + 1, num12].active())
{
                                num12++;
                            }
                            num12--;
                            num18 = (num11 + num12) / 2;
                            if (data.CanGenerateFeatureInArea(this, num6, num18, 3))
{
                                paintingEntry2 = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num6, num18].wall);
                                if (Math.Abs(num17 - num18) >= 4 || WorldGen.nearPicture(num6, num18))
{
                                    break;
                                }
                                DungeonGlobalPaintings.Paintings_PlacePainting(num6, num18, paintingEntry2);
                            }
                        }
                        num18 = num7;
                        num6 = num16;
                        for (int l = 0; l < 2; l++)
{
                            num6 -= 7;
                            num11 = num18;
                            num12 = num18;
                            while (num11 > 0 && !Main.tile[num6, num11].active() && !Main.tile[num6 - 1, num11].active() && !Main.tile[num6 + 1, num11].active())
{
                                num11--;
                            }
                            num11++;
                            while (num12 < Main.maxTilesY - 1 && !Main.tile[num6, num12].active() && !Main.tile[num6 - 1, num12].active() && !Main.tile[num6 + 1, num12].active())
{
                                num12++;
                            }
                            num12--;
                            num18 = (num11 + num12) / 2;
                            if (data.CanGenerateFeatureInArea(this, num6, num18, 3))
{
                                paintingEntry2 = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num6, num18].wall);
                                if (Math.Abs(num17 - num18) >= 4 || WorldGen.nearPicture(num6, num18))
{
                                    break;
                                }
                                DungeonGlobalPaintings.Paintings_PlacePainting(num6, num18, paintingEntry2);
                            }
                        }
                        goto IL_0B4D;
                    }
                    goto IL_0B4D;
                }
                else
                {
                    if (num15 != 2)
                    {
                        goto IL_0B4D;
                    }
                    PaintingEntry paintingEntry3 = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num6, num7].wall);
                    if (!data.CanGenerateFeatureInArea(this, num6, num7, 3))
                    {
                        goto IL_0B4D;
                    }
                    if (!Main.tile[num6, num7].active())
                    {
                        DungeonGlobalPaintings.Paintings_PlacePainting(num6, num7, paintingEntry3);
                    }
                    if (!Main.tile[num6, num7].active())
                    {
                        int num19 = num7;
                        int num20 = num6;
                        int num21 = num6;
                        for (int m = 0; m < 3; m++)
{
                            num7 += 7;
                            num9 = num21;
                            num10 = num21;
                            while (num9 > 0 && !Main.tile[num9, num7].active() && !Main.tile[num9, num7 - 1].active() && !Main.tile[num9, num7 + 1].active())
{
                                num9--;
                            }
                            num9++;
                            while (num10 < Main.maxTilesX - 1 && !Main.tile[num10, num7].active() && !Main.tile[num10, num7 - 1].active() && !Main.tile[num10, num7 + 1].active())
{
                                num10++;
                            }
                            num10--;
                            num21 = (num9 + num10) / 2;
                            if (data.CanGenerateFeatureInArea(this, num21, num7, 3))
{
                                paintingEntry3 = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num21, num7].wall);
                                if (Math.Abs(num20 - num21) >= 4 || WorldGen.nearPicture(num21, num7))
{
                                    break;
                                }
                                DungeonGlobalPaintings.Paintings_PlacePainting(num21, num7, paintingEntry3);
                            }
                        }
                        num21 = num6;
                        num7 = num19;
                        for (int n = 0; n < 3; n++)
{
                            num7 -= 7;
                            num9 = num21;
                            num10 = num21;
                            while (num9 > 0 && !Main.tile[num9, num7].active() && !Main.tile[num9, num7 - 1].active() && !Main.tile[num9, num7 + 1].active())
{
                                num9--;
                            }
                            num9++;
                            while (num10 < Main.maxTilesX - 1 && !Main.tile[num10, num7].active() && !Main.tile[num10, num7 - 1].active() && !Main.tile[num10, num7 + 1].active())
{
                                num10++;
                            }
                            num10--;
                            num21 = (num9 + num10) / 2;
                            if (data.CanGenerateFeatureInArea(this, num21, num7, 3))
{
                                paintingEntry3 = DungeonGlobalPaintings.Paintings_GetPaintingEntry(data, (int)Main.tile[num21, num7].wall);
                                if (Math.Abs(num20 - num21) >= 4 || WorldGen.nearPicture(num21, num7))
{
                                    break;
                                }
                                DungeonGlobalPaintings.Paintings_PlacePainting(num21, num7, paintingEntry3);
                            }
                        }
                        goto IL_0B4D;
                    }
                    goto IL_0B4D;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), System.array, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureInArea(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonGenerationStyles, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.GetStyleForWall(), Terraria.WorldGen.GetWorldSize(), Terraria.GameContent.Generation.Dungeon.DungeonData.globalFeatureScalar, int, Terraria.WorldGen.InWorld(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.lihzahrdPaintingsMax, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.lihzahrdPaintingsPlaced, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.nearPicture(), Terraria.WorldGen.nearPicture2(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_GetPaintingEntry(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_PlacePainting(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.Main.tile, Terraria.Tile.wall, Terraria.GameContent.Generation.Dungeon.DungeonData.wallVariants, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.GenerateFeature().