Terraria Decompiled: Steamworks.SteamNetworking.GetSocketInfo
GetSocketInfo()
static bool Steamworks.SteamNetworking.GetSocketInfo (SNetSocket_t hSocket, out CSteamID pSteamIDRemote, out int peSocketStatus, out SteamIPAddress_t punIPRemote, out ushort punPortRemote) inline static
Definition at line 135 of file SteamNetworking.cs.
        {
            InteropHelp.TestIfAvailableClient();
            return NativeMethods.ISteamNetworking_GetSocketInfo(CSteamAPIContext.GetSteamNetworking(), hSocket, out pSteamIDRemote, out peSocketStatus, out punIPRemote, out punPortRemote);
        }
References Steamworks.CSteamAPIContext.GetSteamNetworking(), Steamworks.NativeMethods.ISteamNetworking_GetSocketInfo(), and Steamworks.InteropHelp.TestIfAvailableClient().