Terraria Decompiled: Terraria.GameContent.Bestiary.NPCPortraitInfoElement.ProvideUIElement
ProvideUIElement()
UIElement Terraria.GameContent.Bestiary.NPCPortraitInfoElement.ProvideUIElement (BestiaryUICollectionInfo info) inline
Implements Terraria.GameContent.Bestiary.IBestiaryInfoElement.
Definition at line 23 of file NPCPortraitInfoElement.cs.
        {
            UIElement uielement = new UIElement
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(112f, 0f)
            };
            uielement.SetPadding(0f);
            BestiaryEntry bestiaryEntry = new BestiaryEntry();
            Asset<Texture2D> asset = null;
            Color color = Color.White;
            bestiaryEntry.Icon = info.OwnerEntry.Icon.CreateClone();
            bestiaryEntry.UIInfoProvider = info.OwnerEntry.UIInfoProvider;
            List<IBestiaryBackgroundOverlayAndColorProvider> list = new List<IBestiaryBackgroundOverlayAndColorProvider>();
            bool flag = info.UnlockState > BestiaryEntryUnlockState.NotKnownAtAll_0;
            if (flag)
            {
                List<IBestiaryInfoElement> list2 = new List<IBestiaryInfoElement>();
                IEnumerable<IBestiaryBackgroundImagePathAndColorProvider> enumerable = info.OwnerEntry.Info.OfType<IBestiaryBackgroundImagePathAndColorProvider>();
                IEnumerable<IPreferenceProviderElement> preferences = info.OwnerEntry.Info.OfType<IPreferenceProviderElement>();
                IEnumerable<IBestiaryBackgroundImagePathAndColorProvider> enumerable2 = enumerable.Where((IBestiaryBackgroundImagePathAndColorProvider provider) => preferences.Any((IPreferenceProviderElement preference) => preference.Matches(provider)));
                bool flag2 = false;
                foreach (IBestiaryBackgroundImagePathAndColorProvider bestiaryBackgroundImagePathAndColorProvider in enumerable2)
                {
                    Asset<Texture2D> backgroundImage = bestiaryBackgroundImagePathAndColorProvider.GetBackgroundImage();
                    if (backgroundImage != null)
                    {
                        asset = backgroundImage;
                        flag2 = true;
                        Color? backgroundColor = bestiaryBackgroundImagePathAndColorProvider.GetBackgroundColor();
                        if (backgroundColor != null)
{
                            color = backgroundColor.Value;
                            break;
                        }
                        break;
                    }
                }
                foreach (IBestiaryInfoElement bestiaryInfoElement in info.OwnerEntry.Info)
                {
                    IBestiaryBackgroundImagePathAndColorProvider bestiaryBackgroundImagePathAndColorProvider2 = bestiaryInfoElement as IBestiaryBackgroundImagePathAndColorProvider;
                    if (bestiaryBackgroundImagePathAndColorProvider2 != null)
                    {
                        Asset<Texture2D> backgroundImage2 = bestiaryBackgroundImagePathAndColorProvider2.GetBackgroundImage();
                        if (backgroundImage2 == null)
{
                            continue;
                        }
                        if (!flag2)
{
                            asset = backgroundImage2;
                        }
                        Color? backgroundColor2 = bestiaryBackgroundImagePathAndColorProvider2.GetBackgroundColor();
                        if (backgroundColor2 != null)
{
                            color = backgroundColor2.Value;
                        }
                    }
                    if (!flag2)
                    {
                        IBestiaryBackgroundOverlayAndColorProvider bestiaryBackgroundOverlayAndColorProvider = bestiaryInfoElement as IBestiaryBackgroundOverlayAndColorProvider;
                        if (bestiaryBackgroundOverlayAndColorProvider != null && bestiaryBackgroundOverlayAndColorProvider.GetBackgroundOverlayImage() != null)
{
                            list2.Add(bestiaryInfoElement);
                        }
                    }
                }
                list.AddRange(from x in list2.OrderBy(new Func<IBestiaryInfoElement, float>(this.GetSortingValueForElement))
                    select x as IBestiaryBackgroundOverlayAndColorProvider);
            }
            UIBestiaryNPCEntryPortrait uibestiaryNPCEntryPortrait = new UIBestiaryNPCEntryPortrait(bestiaryEntry, asset, color, list)
            {
                Left = new StyleDimension(4f, 0f),
                HAlign = 0f
            };
            uielement.Append(uibestiaryNPCEntryPortrait);
            if (flag && this._filledStarsCount != null)
            {
                UIElement uielement2 = this.CreateStarsContainer();
                uielement.Append(uielement2);
            }
            return uielement;
        }
References Terraria.GameContent.Bestiary.NPCPortraitInfoElement._filledStarsCount, Terraria.UI.UIElement.Append(), Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer(), Terraria.GameContent.Bestiary.IBestiaryBackgroundImagePathAndColorProvider.GetBackgroundColor(), Terraria.GameContent.Bestiary.IBestiaryBackgroundImagePathAndColorProvider.GetBackgroundImage(), Terraria.GameContent.Bestiary.IBestiaryBackgroundOverlayAndColorProvider.GetBackgroundOverlayImage(), System.info, System.list, Terraria.GameContent.Bestiary.IPreferenceProviderElement.Matches(), Terraria.UI.UIElement.SetPadding(), and Microsoft.Xna.Framework.Color.White.