Terraria Decompiled: Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer
CreateStarsContainer()
UIElement Terraria.GameContent.Bestiary.NPCPortraitInfoElement.CreateStarsContainer () inline private
Definition at line 119 of file NPCPortraitInfoElement.cs.
        {
            int num = 14;
            int num2 = 14;
            int num3 = -4;
            int num4 = num + num3;
            int num5 = 5;
            int num6 = 5;
            int value = this._filledStarsCount.Value;
            float num7 = 1f;
            int num8 = num4 * Math.Min(num6, num5) - num3;
            double num9 = (double)num4 * Math.Ceiling((double)num5 / (double)num6) - (double)num3;
            UIElement uielement = new UIPanel(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Panel", 1), null, 5, 21)
            {
                Width = new StyleDimension((float)num8 + num7 * 2f, 0f),
                Height = new StyleDimension((float)num9 + num7 * 2f, 0f),
                BackgroundColor = Color.Gray * 0f,
                BorderColor = Color.Transparent,
                Left = new StyleDimension(10f, 0f),
                Top = new StyleDimension(6f, 0f),
                VAlign = 0f
            };
            uielement.SetPadding(0f);
            for (int i = num5 - 1; i >= 0; i--)
            {
                string text = "Images/UI/Bestiary/Icon_Rank_Light";
                if (i >= value)
                {
                    text = "Images/UI/Bestiary/Icon_Rank_Dim";
                }
                UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>(text, 1))
                {
                    Left = new StyleDimension((float)(num4 * (i % num6)) - (float)num8 * 0.5f + (float)num * 0.5f, 0f),
                    Top = new StyleDimension((float)(num4 * (i / num6)) - (float)num9 * 0.5f + (float)num2 * 0.5f, 0f),
                    HAlign = 0.5f,
                    VAlign = 0.5f
                };
                uielement.Append(uiimage);
            }
            return uielement;
        }
References Terraria.GameContent.Bestiary.NPCPortraitInfoElement._filledStarsCount, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, System.Math.Ceiling(), System.Math.Min(), Terraria.UI.UIElement.SetPadding(), System.text, Microsoft.Xna.Framework.Color.Transparent, and System.value.
Referenced by Terraria.GameContent.Bestiary.NPCPortraitInfoElement.ProvideUIElement().