Terraria Decompiled: System.Reflection.SignatureConstructedGenericType.ToString
ToString()
override string System.Reflection.SignatureConstructedGenericType.ToString () inline sealed
Implements System.Runtime.InteropServices._Type.
Definition at line 232 of file SignatureConstructedGenericType.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append(this._genericTypeDefinition.ToString());
            stringBuilder.Append('[');
            for (int i = 0; i < this._genericTypeArguments.Length; i++)
            {
                if (i != 0)
                {
                    stringBuilder.Append(',');
                }
                stringBuilder.Append(this._genericTypeArguments[i].ToString());
            }
            stringBuilder.Append(']');
            return stringBuilder.ToString();
        }
References System.Reflection.SignatureConstructedGenericType._genericTypeArguments, System.Reflection.SignatureConstructedGenericType._genericTypeDefinition, System.Text.StringBuilder.Append(), System.Reflection.SignatureConstructedGenericType.ToString(), System.Text.StringBuilder.ToString(), and System.Type.ToString().
Referenced by System.Reflection.SignatureConstructedGenericType.ToString().