Terraria Decompiled: Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame
PlaceItemInFrame()
static void Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame (Player player, int x, int y) inline static
Definition at line 134 of file TEFoodPlatter.cs.
        {
            if (!player.ItemTimeIsZero)
            {
                return;
            }
            TEFoodPlatter tefoodPlatter;
            if (!TileEntity.TryGetAt<TEFoodPlatter>(x, y, out tefoodPlatter))
            {
                return;
            }
            if (tefoodPlatter.item.stack > 0)
            {
                WorldGen.KillTile(x, y, true, false, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)Player.tileTargetX, (float)y, 1f, 0, 0, 0);
                }
            }
            if (Main.netMode == 1)
            {
                NetMessage.SendData(133, -1, -1, null, x, (float)y, (float)player.selectedItem, (float)player.whoAmI, 1, 0, 0);
            }
            else
            {
                TEFoodPlatter.TryPlacing(x, y, player.inventory[player.selectedItem].type, (int)player.inventory[player.selectedItem].prefix, 1);
            }
            player.inventory[player.selectedItem].stack--;
            if (player.inventory[player.selectedItem].stack <= 0)
            {
                player.inventory[player.selectedItem].SetDefaults(0, null);
                Main.mouseItem.SetDefaults(0, null);
            }
            if (player.selectedItem == 58)
            {
                Main.mouseItem = player.inventory[player.selectedItem].Clone();
            }
            player.releaseUseItem = false;
            player.mouseInterface = true;
            WorldGen.RangeFrame(x, y, x + 1, y + 1);
        }
References Terraria.Item.Clone(), Terraria.Player.inventory, Terraria.GameContent.Tile_Entities.TEFoodPlatter.item, Terraria.Player.ItemTimeIsZero, Terraria.WorldGen.KillTile(), Terraria.Main.mouseItem, Terraria.Main.netMode, Terraria.Item.prefix, Terraria.WorldGen.RangeFrame(), Terraria.Player.selectedItem, Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Player.tileTargetX, Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.Item.type, and Terraria.Entity.whoAmI.
Referenced by Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction().