Terraria Decompiled: System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter.DecryptKeyExchange
DecryptKeyExchange()
override byte[] System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter.DecryptKeyExchange (byte[] rgbData) inline
Definition at line 41 of file RSAOAEPKeyExchangeDeformatter.cs.
        {
            if (this._rsaKey == null)
            {
                throw new CryptographicUnexpectedOperationException(Environment.GetResourceString("No asymmetric key object has been associated with this formatter object."));
            }
            if (this.OverridesDecrypt)
            {
                return this._rsaKey.Decrypt(rgbData, RSAEncryptionPadding.OaepSHA1);
            }
            return Utils.RsaOaepDecrypt(this._rsaKey, SHA1.Create(), new PKCS1MaskGenerationMethod(), rgbData);
        }
References System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter._rsaKey, System.Security.Cryptography.SHA1.Create(), System.Security.Cryptography.RSA.Decrypt(), System.Environment.GetResourceString(), System.Security.Cryptography.RSAEncryptionPadding.OaepSHA1, System.Security.Cryptography.RSAOAEPKeyExchangeDeformatter.OverridesDecrypt, and System.Security.Cryptography.Utils.RsaOaepDecrypt().