Terraria Decompiled: System.Runtime.Remoting.Contexts.Context.CreateServerObjectSinkChain
CreateServerObjectSinkChain()
IMessageSink System.Runtime.Remoting.Contexts.Context.CreateServerObjectSinkChain (MarshalByRefObject obj, bool forceInternalExecute) inline package
Definition at line 287 of file Context.cs.
        {
            IMessageSink messageSink = new StackBuilderSink(obj, forceInternalExecute);
            messageSink = new ServerObjectTerminatorSink(messageSink);
            messageSink = new LeaseSink(messageSink);
            if (this.context_properties != null)
            {
                for (int i = this.context_properties.Count - 1; i >= 0; i--)
                {
                    IContributeObjectSink contributeObjectSink = this.context_properties[i] as IContributeObjectSink;
                    if (contributeObjectSink != null)
                    {
                        messageSink = contributeObjectSink.GetObjectSink(obj, messageSink);
                    }
                }
            }
            return messageSink;
        }
References System.Runtime.Remoting.Contexts.Context.context_properties, System.Runtime.Remoting.Contexts.IContributeObjectSink.GetObjectSink(), and System.obj.
Referenced by System.Runtime.Remoting.SingleCallIdentity.AsyncObjectProcessMessage(), System.Runtime.Remoting.SingletonIdentity.AsyncObjectProcessMessage(), System.Runtime.Remoting.SingleCallIdentity.SyncObjectProcessMessage(), and System.Runtime.Remoting.SingletonIdentity.SyncObjectProcessMessage().