Terraria Decompiled: System.Runtime.Remoting.Contexts.Context.SwitchToContext
SwitchToContext()
static Context System.Runtime.Remoting.Contexts.Context.SwitchToContext (Context newContext) inline static package
Definition at line 325 of file Context.cs.
        {
            return AppDomain.InternalSetContext(newContext);
        }
References System.AppDomain.InternalSetContext().
Referenced by System.Runtime.Remoting.Activation.ContextLevelActivator.Activate(), System.Runtime.Remoting.Contexts.CrossContextChannel.AsyncProcessMessage(), System.Runtime.Remoting.Contexts.Context.DoCallBack(), System.Runtime.Remoting.Contexts.CrossContextChannel.SyncProcessMessage(), and System.Runtime.Remoting.Contexts.CrossContextChannel.ContextRestoreSink.SyncProcessMessage().