Terraria Decompiled: System.Runtime.Remoting.Contexts.Context.NotifyDynamicSinks
NotifyDynamicSinks()
void System.Runtime.Remoting.Contexts.Context.NotifyDynamicSinks (bool start, IMessage req_msg, bool client_site, bool async) inline package
Definition at line 159 of file Context.cs.
        {
            if (this.context_dynamic_properties != null && this.context_dynamic_properties.HasProperties)
            {
                this.context_dynamic_properties.NotifyMessage(start, req_msg, client_site, async);
            }
        }
References System.Runtime.Remoting.Contexts.Context.context_dynamic_properties, System.Runtime.Remoting.Contexts.DynamicPropertyCollection.HasProperties, and System.Runtime.Remoting.Contexts.DynamicPropertyCollection.NotifyMessage().
Referenced by System.Runtime.Remoting.Messaging.ClientContextTerminatorSink.AsyncProcessMessage(), System.Runtime.Remoting.Messaging.ClientContextReplySink.SyncProcessMessage(), and System.Runtime.Remoting.Messaging.ClientContextTerminatorSink.SyncProcessMessage().