Terraria Decompiled: System.Runtime.Remoting.Contexts.Context.CreateNewContext
CreateNewContext()
static Context System.Runtime.Remoting.Contexts.Context.CreateNewContext (IConstructionCallMessage msg) inline static package
Definition at line 331 of file Context.cs.
        {
            Context context = new Context();
            foreach (object obj in msg.ContextProperties)
            {
                IContextProperty contextProperty = (IContextProperty)obj;
                if (context.GetProperty(contextProperty.Name) == null)
                {
                    context.SetProperty(contextProperty);
                }
            }
            context.Freeze();
            using (IEnumerator enumerator = msg.ContextProperties.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    if (!((IContextProperty)enumerator.Current).IsNewContextOK(context))
                    {
                        throw new RemotingException("A context property did not approve the candidate context for activating the object");
                    }
                }
            }
            return context;
        }
References System.Runtime.Remoting.Contexts.Context.Context(), System.Collections.Generic.IEnumerator< out T >.Current, System.Runtime.Remoting.Contexts.IContextProperty.Freeze(), System.Collections.IEnumerator.MoveNext(), System.Runtime.Remoting.Contexts.IContextProperty.Name, and System.obj.
Referenced by System.Runtime.Remoting.Activation.ContextLevelActivator.Activate().