Terraria Decompiled: System.Type.GetEnumNames
GetEnumNames()
virtual string[] System.Type.GetEnumNames () inline virtual
Reimplemented in System.Reflection.SignatureType.
Definition at line 82 of file Type.cs.
        {
            if (!this.IsEnum)
            {
                throw new ArgumentException("Type provided must be an Enum.", "enumType");
            }
            string[] array;
            Array array2;
            this.GetEnumData(out array, out array2);
            return array;
        }
References System.array, System.Type.GetEnumData(), and System.Type.IsEnum.
Referenced by System.Type.GetEnumName(), System.Enum.GetNames(), and System.Type.IsEnumDefined().