Terraria Decompiled: System.Type.IsAssignableFrom
IsAssignableFrom()
virtual bool System.Type.IsAssignableFrom (Type c) inline virtual
Implements System.Runtime.InteropServices._Type.
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, System.Reflection.Emit.TypeBuilder, System.Reflection.Emit.TypeBuilderInstantiation, and System.Reflection.SignatureType.
Definition at line 533 of file Type.cs.
        {
            if (c == null)
            {
                return false;
            }
            if (this == c)
            {
                return true;
            }
            Type underlyingSystemType = this.UnderlyingSystemType;
            if (underlyingSystemType.IsRuntimeImplemented())
            {
                return underlyingSystemType.IsAssignableFrom(c);
            }
            if (c.IsSubclassOf(this))
            {
                return true;
            }
            if (this.IsInterface)
            {
                return c.ImplementInterface(this);
            }
            if (this.IsGenericParameter)
            {
                Type[] genericParameterConstraints = this.GetGenericParameterConstraints();
                for (int i = 0; i < genericParameterConstraints.Length; i++)
                {
                    if (!genericParameterConstraints[i].IsAssignableFrom(c))
                    {
                        return false;
                    }
                }
                return true;
            }
            return false;
        }
References System.Type.GetGenericParameterConstraints(), System.Type.ImplementInterface(), System.Type.IsAssignableFrom(), System.Type.IsGenericParameter, System.Type.IsInterface, System.Type.IsRuntimeImplemented(), System.Type.IsSubclassOf(), and System.Type.UnderlyingSystemType.
Referenced by Microsoft.Xna.Framework.GameServiceContainer.AddService(), System.Delegate.arg_type_match(), System.Delegate.arg_type_match_this(), System.DefaultBinder.BindToField(), System.DefaultBinder.BindToMethod(), System.Array.CanAssignArrayElement(), System.Runtime.Remoting.Proxies.RemotingProxy.CanCastTo(), System.Runtime.Serialization.FormatterServices.CheckTypeSecurity(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateArrayContract(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.EnsureCastExpression(), Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(), System.DefaultBinder.FindMostSpecificType(), System.MonoCustomAttrs.GetCustomAttributes(), System.Reflection.Emit.DynamicMethod.GetCustomAttributes(), System.Reflection.Emit.ModuleBuilder.GetCustomAttributes(), System.MonoCustomAttrs.GetCustomAttributesData(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetExtensionDataMemberForType(), System.MonoCustomAttrs.GetPseudoCustomAttributes(), System.MonoCustomAttrs.GetPseudoCustomAttributesData(), System.Runtime.Remoting.Messaging.RemotingSurrogateSelector.GetSurrogate(), System.Reflection.RuntimeFieldInfo.GetValue(), System.Runtime.Serialization.SerializationInfo.GetValue(), System.Runtime.Serialization.SerializationInfo.GetValueNoThrow(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(), FullSerializer.fsSerializer.InternalDeserialize_3_Inheritance(), System.Type.IsAssignableFrom(), System.Reflection.TypeExtensions.IsAssignableFrom(), System.Reflection.TypeInfo.IsAssignableFrom(), System.Reflection.Emit.TypeBuilder.IsAssignableTo(), System.MonoCustomAttrs.IsDefined(), System.Reflection.Emit.DynamicMethod.IsDefined(), System.Type.IsInstanceOfType(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAccessRule(), System.Security.AccessControl.ObjectSecurity< T >.ModifyAuditRule(), Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor(), System.Delegate.return_type_match(), System.DefaultBinder.SelectMethod(), System.DefaultBinder.SelectProperty(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), and System.Reflection.RuntimeFieldInfo.SetValue().