Terraria Decompiled: System.Type.GetTypeCode
GetTypeCode()
static TypeCode System.Type.GetTypeCode (Type type) inline static
Definition at line 1704 of file Type.cs.
        {
            if (type == null)
            {
                return TypeCode.Empty;
            }
            return type.GetTypeCodeImpl();
        }
References System.Type.GetTypeCodeImpl().
Referenced by System.DefaultBinder.CanConvertPrimitive(), System.DefaultBinder.CanPrimitiveWiden(), System.Collections.Generic.EqualityComparer< T >.CreateComparer(), System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value(), System.Collections.Generic.EnumEqualityComparer< T >.GetObjectData(), System.Type.GetTypeCodeImpl(), System.RuntimeType.IsConvertibleToPrimitiveType(), System.Collections.Concurrent.ConcurrentDictionary< TKey, TValue >.IsValueWriteAtomic(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), System.Runtime.Serialization.Formatters.Binary.Converter.ToCode(), and System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArgument().