Terraria Decompiled: System.Type.GetTypeCodeImpl
GetTypeCodeImpl()
virtual TypeCode System.Type.GetTypeCodeImpl () inline protected virtual
Reimplemented in System.Reflection.SignatureType.
Definition at line 1714 of file Type.cs.
        {
            if (this != this.UnderlyingSystemType && this.UnderlyingSystemType != null)
            {
                return Type.GetTypeCode(this.UnderlyingSystemType);
            }
            return TypeCode.Object;
        }
References System.Type.GetTypeCode(), and System.Type.UnderlyingSystemType.
Referenced by System.Type.GetTypeCode(), and System.Type.IsEnumDefined().