Terraria Decompiled: System.Type.IsInstanceOfType
IsInstanceOfType()
virtual bool System.Type.IsInstanceOfType (object o) inline virtual
Implements System.Runtime.InteropServices._Type.
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, and System.Reflection.SignatureType.
Definition at line 1805 of file Type.cs.
        {
            return o != null && this.IsAssignableFrom(o.GetType());
        }
References System.Type.IsAssignableFrom().
Referenced by Newtonsoft.Json.Linq.JToken.Annotation(), Newtonsoft.Json.Linq.JToken.Annotations(), System.DefaultBinder.BindToMethod(), System.Runtime.Remoting.Messaging.StackBuilderSink.CheckParameters(), System.DelegateSerializationHolder.DelegateEntry.DeserializeDelegate(), System.Reflection.Emit.CustomAttributeBuilder.Initialize(), System.Reflection.RuntimeConstructorInfo.Invoke(), System.Reflection.TypeExtensions.IsInstanceOfType(), System.Runtime.Remoting.ObjRef.ObjRef(), System.Runtime.Remoting.Proxies.RealProxy.ProcessResponse(), Newtonsoft.Json.Linq.JToken.RemoveAnnotations(), and System.RuntimeType.TryConvertToType().