Terraria Decompiled: System.Type.ToString
ToString()
override string System.Type.ToString () inline
Implements System.Runtime.InteropServices._Type.
Definition at line 1888 of file Type.cs.
        {
            return "Type: " + this.Name;
        }
References System.Reflection.MemberInfo.Name.
Referenced by System.Runtime.Remoting.Channels.ChannelServices.CreateProvider(), FullSerializer.fsTypeExtensions.CSharpName(), System.Reflection.Emit.CustomAttributeBuilder.decode_cattr(), System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value(), System.Reflection.Emit.UnmanagedMarshal.DefineCustom(), System.Reflection.RuntimeConstructorInfo.DoInvoke(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.EnsureType(), Newtonsoft.Json.Utilities.ConvertUtils.EnsureTypeAssignable(), System.Reflection.Emit.TypeBuilderInstantiation.format_name(), Steamworks.CallbackIdentities.GetCallbackIdentity(), System.Exception.GetClassName(), System.__ComObject.GetCLSID(), System.Diagnostics.StackTrace.GetFullNameForStackTrace(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberInfo(), System.Reflection.Emit.TypeBuilder.GetMethod(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetType(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), System.Reflection.Emit.CustomAttributeBuilder.Initialize(), System.Reflection.Emit.GenericInstanceKey.IsBoundedVector(), System.Type.IsEnumDefined(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig(), System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), System.Reflection.Emit.MethodRental.SwapMethodBody(), System.Object.ToString(), System.Reflection.Emit.FieldOnTypeBuilderInst.ToString(), System.Reflection.Emit.MethodOnTypeBuilderInst.ToString(), System.Reflection.Emit.SymbolType.ToString(), System.Reflection.RuntimeEventInfo.ToString(), System.Reflection.SignatureConstructedGenericType.ToString(), System.Runtime.InteropServices.TypeLibImportClassAttribute.TypeLibImportClassAttribute(), and System.Runtime.Remoting.Messaging.CADMessageBase.UnmarshalArgument().