Terraria Decompiled: System.Type.GetHashCode
GetHashCode()
override int System.Type.GetHashCode () inline
Implements System.Runtime.InteropServices._Type.
Definition at line 1900 of file Type.cs.
        {
            Type underlyingSystemType = this.UnderlyingSystemType;
            if (underlyingSystemType != this)
            {
                return underlyingSystemType.GetHashCode();
            }
            return base.GetHashCode();
        }
References System.Type.GetHashCode(), and System.Type.UnderlyingSystemType.
Referenced by System.Reflection.Emit.GenericInstanceKey.GenericInstanceKey(), System.Attribute.GetHashCode(), System.Runtime.Serialization.MemberHolder.GetHashCode(), System.Runtime.Serialization.SurrogateKey.GetHashCode(), System.RuntimeType.GetHashCode(), System.Type.GetHashCode(), Newtonsoft.Json.Serialization.ResolverContractKey.GetHashCode(), Newtonsoft.Json.Utilities.ConvertUtils.TypeConvertKey.GetHashCode(), and FullSerializer.Internal.fsVersionedType.GetHashCode().