Terraria Decompiled: System.Type.GetMethod
GetMethod() [2/11]
MethodInfo System.Type.GetMethod (string name) inline
Implements System.Runtime.InteropServices._Type.
Definition at line 1451 of file Type.cs.
        {
            return this.GetMethod(name, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public);
        }
References System.Reflection.GetMethod.
Referenced by CsvHelper.CsvWriter.CreateActionForPrimitive(), System.Delegate.CreateDelegate(), Newtonsoft.Json.Utilities.FSharpUtils.CreateFSharpFuncCall(), Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateMemberCalls(), Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateSharpArgumentInfoArray(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateShouldSerializeTest(), System.Security.Cryptography.Utils.DoesRsaKeyOverrideSlowPath(), Newtonsoft.Json.Utilities.FSharpUtils.EnsureInitialized(), System.Runtime.Remoting.RemotingServices.FindInterfaceMethod(), System.Delegate.GetCandidateMethod(), System.Runtime.InteropServices.Marshal.GetCustomMarshalerInstance(), System.Reflection.Emit.TypeBuilder.GetMethod(), System.Reflection.TypeExtensions.GetMethod(), System.Reflection.TypeExtensions.GetMethod(), System.Reflection.TypeExtensions.GetMethod(), System.Runtime.Remoting.RemotingServices.GetMethodBaseFromName(), System.Reflection.Emit.TypeBuilder.GetMethodImpl(), System.Reflection.RuntimeModule.GetMethodImpl(), System.Reflection.TypeDelegator.GetMethodImpl(), System.Runtime.Remoting.Messaging.MonoMethodMessage.GetMethodInfo(), Newtonsoft.Json.Utilities.FSharpUtils.GetMethodWithNonPublicFallback(), System.Reflection.RuntimeReflectionExtensions.GetRuntimeMethod(), System.Runtime.Remoting.Messaging.CADMethodRef.Resolve(), System.Reflection.Emit.MethodBuilder.RuntimeResolve(), System.Reflection.Emit.MethodOnTypeBuilderInst.RuntimeResolve(), and Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates().