Terraria Decompiled: System.Type.GetField
GetField() [2/3]
FieldInfo System.Type.GetField (string name) inline
Implements System.Runtime.InteropServices._Type.
Definition at line 1406 of file Type.cs.
        {
            return this.GetField(name, BindingFlags.Instance | BindingFlags.Static | BindingFlags.Public);
        }
References System.Reflection.GetField.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.decode_cattr(), System.Runtime.Serialization.ObjectManager.DoValueTypeFixup(), ReLogic.Utilities.AttributeUtilities.GetAttribute< T >(), System.Reflection.RuntimeMethodInfo.GetDllImportAttributeData(), System.Reflection.Emit.TypeBuilder.GetField(), System.Reflection.RuntimeModule.GetField(), System.Reflection.TypeDelegator.GetField(), System.Reflection.Emit.TypeBuilder.GetField(), System.Reflection.TypeExtensions.GetField(), System.Reflection.TypeExtensions.GetField(), System.Reflection.RuntimeReflectionExtensions.GetRuntimeField(), System.Security.PermissionSet.ProcessAttribute(), System.Reflection.Emit.FieldOnTypeBuilderInst.RuntimeResolve(), Newtonsoft.Json.Serialization.DefaultContractResolver.SetIsSpecifiedActions(), and Terraria.Main.TrySupporting8K().