Terraria Decompiled: System.Type.GetArrayRank
GetArrayRank()
virtual int System.Type.GetArrayRank () inline virtual
Implements System.Runtime.InteropServices._Type.
Reimplemented in System.Reflection.Emit.ArrayType, System.Reflection.SignatureArrayType, System.Reflection.SignatureByRefType, System.Reflection.SignatureConstructedGenericType, System.Reflection.SignatureGenericParameterType, System.Reflection.SignatureHasElementType, System.Reflection.SignaturePointerType, and System.Reflection.SignatureType.
Definition at line 928 of file Type.cs.
        {
            throw new NotSupportedException("Derived classes must provide an implementation.");
        }
Referenced by Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForArray(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), System.Reflection.Emit.CustomAttributeBuilder.IsValidParam(), System.Reflection.Emit.CustomAttributeBuilder.IsValidType(), System.Reflection.SignatureTypeExtensions.MatchesExactly(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.PopulateMultidimensionalArray(), and System.Reflection.Emit.GenericInstanceKey.TypeEquals().