Terraria Decompiled: System.Type.GetGenericArguments
GetGenericArguments()
virtual Type[] System.Type.GetGenericArguments () inline virtual
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, System.Reflection.Emit.TypeBuilder, System.Reflection.Emit.TypeBuilderInstantiation, System.Reflection.SignatureConstructedGenericType, System.Reflection.SignatureGenericParameterType, System.Reflection.SignatureHasElementType, and System.Reflection.SignatureType.
Definition at line 954 of file Type.cs.
        {
            throw new NotSupportedException("Derived classes must provide an implementation.");
        }
Referenced by CsvHelper.Configuration.CsvClassMapCollection.Add(), FullSerializer.fsTypeExtensions.CSharpName(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForNonArrayTypes(), Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(), FullSerializer.Internal.fsIEnumerableConverter.GetElementType(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetExtensionDataMemberForType(), System.Reflection.TypeExtensions.GetGenericArguments(), FullSerializer.Internal.fsDictionaryConverter.GetKeyValueTypes(), System.Reflection.Emit.TypeBuilder.GetMethod(), System.UnitySerializationHolder.GetRealObject(), System.Reflection.Emit.MethodOnTypeBuilderInst.GetTypeArgs(), System.Nullable< T >.GetUnderlyingType(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), Newtonsoft.Json.Converters.KeyValuePairConverter.InitializeReflectionObject(), System.Reflection.Emit.GenericTypeParameterBuilder.InternalResolve(), System.Reflection.Emit.TypeBuilder.IsValidGetMethodType(), Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract(), Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract(), CsvHelper.Configuration.CsvClassMapCollection.Remove(), System.Reflection.Emit.GenericTypeParameterBuilder.RuntimeResolve(), Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates(), FullSerializer.Internal.fsKeyValuePairConverter.TryDeserialize(), FullSerializer.Internal.fsKeyValuePairConverter.TrySerialize(), System.Reflection.Emit.GenericInstanceKey.TypeEquals(), and CsvHelper.CsvWriter.WriteRecords().