Terraria Decompiled: System.Type.GetConstructor
GetConstructor() [4/4]
ConstructorInfo System.Type.GetConstructor (Type[] types) inline
Implements System.Runtime.InteropServices._Type.
Definition at line 1347 of file Type.cs.
        {
            return this.GetConstructor(BindingFlags.Instance | BindingFlags.Public, null, types, null);
        }
References System.Type.GetConstructor().
Referenced by CsvHelper.Configuration.CsvClassMap< T >.AutoMapInternal(), CsvHelper.ReflectionHelper.CreateInstance(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateISerializableContract(), Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateWrapper(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(), System.Reflection.Emit.TypeBuilder.DefineDefaultConstructor(), Newtonsoft.Json.Converters.BinaryConverter.EnsureReflectionObject(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateDefaultConstructorIL(), Newtonsoft.Json.Serialization.DefaultContractResolver.GetAttributeConstructor(), System.Type.GetConstructor(), System.Reflection.Emit.TypeBuilder.GetConstructor(), System.Reflection.TypeExtensions.GetConstructor(), System.Type.GetConstructor(), System.Reflection.Emit.TypeBuilder.GetConstructorImpl(), System.Reflection.TypeDelegator.GetConstructorImpl(), Newtonsoft.Json.Serialization.JsonTypeReflector.GetCreator(), Microsoft.Xna.Framework.Content.ContentExtensions.GetDefaultConstructor(), System.Reflection.RuntimeMethodInfo.GetDllImportAttributeData(), System.Runtime.Remoting.RemotingServices.GetMethodBaseFromName(), System.RuntimeType.GetSerializationCtor(), Newtonsoft.Json.Converters.KeyValuePairConverter.InitializeReflectionObject(), System.Runtime.Remoting.Channels.ChannelServices.RegisterChannelConfig(), System.Runtime.Remoting.Messaging.CADMethodRef.Resolve(), System.Reflection.Emit.ConstructorBuilder.RuntimeResolve(), System.Reflection.Emit.ConstructorOnTypeBuilderInst.RuntimeResolve(), and System.Reflection.Emit.ILGenerator.ThrowException().