Terraria Decompiled: System.Type.FindMembers
FindMembers()
virtual MemberInfo[] System.Type.FindMembers (MemberTypes memberType, BindingFlags bindingAttr, MemberFilter filter, object filterCriteria) inline virtual
Implements System.Runtime.InteropServices._Type.
Reimplemented in System.Reflection.SignatureType.
Definition at line 307 of file Type.cs.
        {
            MethodInfo[] array = null;
            ConstructorInfo[] array2 = null;
            FieldInfo[] array3 = null;
            PropertyInfo[] array4 = null;
            EventInfo[] array5 = null;
            Type[] array6 = null;
            int num = 0;
            if ((memberType & MemberTypes.Method) != (MemberTypes)0)
            {
                array = this.GetMethods(bindingAttr);
                if (filter != null)
                {
                    for (int i = 0; i < array.Length; i++)
                    {
                        if (!filter(array[i], filterCriteria))
{
                            array[i] = null;
                        }
                        else
{
                            num++;
                        }
                    }
                }
                else
                {
                    num += array.Length;
                }
            }
            if ((memberType & MemberTypes.Constructor) != (MemberTypes)0)
            {
                array2 = this.GetConstructors(bindingAttr);
                if (filter != null)
                {
                    for (int i = 0; i < array2.Length; i++)
                    {
                        if (!filter(array2[i], filterCriteria))
{
                            array2[i] = null;
                        }
                        else
{
                            num++;
                        }
                    }
                }
                else
                {
                    num += array2.Length;
                }
            }
            if ((memberType & MemberTypes.Field) != (MemberTypes)0)
            {
                array3 = this.GetFields(bindingAttr);
                if (filter != null)
                {
                    for (int i = 0; i < array3.Length; i++)
                    {
                        if (!filter(array3[i], filterCriteria))
{
                            array3[i] = null;
                        }
                        else
{
                            num++;
                        }
                    }
                }
                else
                {
                    num += array3.Length;
                }
            }
            if ((memberType & MemberTypes.Property) != (MemberTypes)0)
            {
                array4 = this.GetProperties(bindingAttr);
                if (filter != null)
                {
                    for (int i = 0; i < array4.Length; i++)
                    {
                        if (!filter(array4[i], filterCriteria))
{
                            array4[i] = null;
                        }
                        else
{
                            num++;
                        }
                    }
                }
                else
                {
                    num += array4.Length;
                }
            }
            if ((memberType & MemberTypes.Event) != (MemberTypes)0)
            {
                array5 = this.GetEvents(bindingAttr);
                if (filter != null)
                {
                    for (int i = 0; i < array5.Length; i++)
                    {
                        if (!filter(array5[i], filterCriteria))
{
                            array5[i] = null;
                        }
                        else
{
                            num++;
                        }
                    }
                }
                else
                {
                    num += array5.Length;
                }
            }
            if ((memberType & MemberTypes.NestedType) != (MemberTypes)0)
            {
                array6 = this.GetNestedTypes(bindingAttr);
                if (filter != null)
                {
                    for (int i = 0; i < array6.Length; i++)
                    {
                        if (!filter(array6[i], filterCriteria))
{
                            array6[i] = null;
                        }
                        else
{
                            num++;
                        }
                    }
                }
                else
                {
                    num += array6.Length;
                }
            }
            MemberInfo[] array7 = new MemberInfo[num];
            num = 0;
            if (array != null)
            {
                for (int i = 0; i < array.Length; i++)
                {
                    if (array[i] != null)
                    {
                        array7[num++] = array[i];
                    }
                }
            }
            if (array2 != null)
            {
                for (int i = 0; i < array2.Length; i++)
                {
                    if (array2[i] != null)
                    {
                        array7[num++] = array2[i];
                    }
                }
            }
            if (array3 != null)
            {
                for (int i = 0; i < array3.Length; i++)
                {
                    if (array3[i] != null)
                    {
                        array7[num++] = array3[i];
                    }
                }
            }
            if (array4 != null)
            {
                for (int i = 0; i < array4.Length; i++)
                {
                    if (array4[i] != null)
                    {
                        array7[num++] = array4[i];
                    }
                }
            }
            if (array5 != null)
            {
                for (int i = 0; i < array5.Length; i++)
                {
                    if (array5[i] != null)
                    {
                        array7[num++] = array5[i];
                    }
                }
            }
            if (array6 != null)
            {
                for (int i = 0; i < array6.Length; i++)
                {
                    if (array6[i] != null)
                    {
                        array7[num++] = array6[i];
                    }
                }
            }
            return array7;
        }
References System.array, System.Type.GetConstructors(), System.Type.GetEvents(), System.Type.GetFields(), System.Type.GetMethods(), System.Type.GetNestedTypes(), and System.Type.GetProperties().