Terraria Decompiled: System.Type.GetGenericTypeDefinition
GetGenericTypeDefinition()
virtual Type System.Type.GetGenericTypeDefinition () inline virtual
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, System.Reflection.Emit.TypeBuilder, System.Reflection.Emit.TypeBuilderInstantiation, System.Reflection.SignatureConstructedGenericType, System.Reflection.SignatureGenericParameterType, System.Reflection.SignatureHasElementType, and System.Reflection.SignatureType.
Definition at line 934 of file Type.cs.
        {
            throw new NotSupportedException("Derived classes must provide an implementation.");
        }
Referenced by Newtonsoft.Json.Converters.KeyValuePairConverter.CanConvert(), FullSerializer.Internal.fsKeyValuePairConverter.CanProcess(), FullSerializer.Internal.fsNullableConverter.CanProcess(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForNonArrayTypes(), System.Reflection.Emit.TypeBuilder.GetConstructor(), CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), System.Reflection.Emit.TypeBuilder.GetField(), System.Diagnostics.StackTrace.GetFullNameForStackTrace(), CsvHelper.Configuration.CsvClassMapCollection.GetGenericCsvClassMapType(), FullSerializer.Internal.fsReflectionUtility.GetInterface(), System.Reflection.Emit.TypeBuilder.GetMethod(), System.Reflection.MethodBase.GetMethodFromHandle(), System.Nullable< T >.GetUnderlyingType(), Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), Newtonsoft.Json.Utilities.ReflectionUtils.InheritsGenericDefinitionInternal(), Newtonsoft.Json.Utilities.ReflectionUtils.IsGenericDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), Newtonsoft.Json.Utilities.ReflectionUtils.IsOverridenGenericMember(), FullSerializer.Internal.fsIEnumerableConverter.IsStack(), Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract(), System.Reflection.SignatureTypeExtensions.MatchesExactly(), Newtonsoft.Json.Serialization.DefaultContractResolver.ShouldSerializeEntityMember(), Newtonsoft.Json.Serialization.DefaultContractResolver.ShouldSkipDeserialized(), and System.Reflection.Emit.GenericInstanceKey.TypeEquals().