Terraria Decompiled: System.Type.MakeGenericType
MakeGenericType()
virtual Type System.Type.MakeGenericType (params Type[] typeArguments) inline virtual
Reimplemented in System.Reflection.Emit.GenericTypeParameterBuilder, System.Reflection.Emit.TypeBuilder, and System.Reflection.SignatureType.
Definition at line 1860 of file Type.cs.
        {
            throw new NotSupportedException("Derived classes must provide an implementation.");
        }
Referenced by Newtonsoft.Json.Utilities.FSharpUtils.BuildMapCreator< TKey, TValue >(), CsvHelper.CsvWriter.CreateActionForObject(), CsvHelper.CsvWriter.CreateActionForPrimitive(), System.Reflection.EventInfo.CreateAddEventDelegate(), Newtonsoft.Json.Serialization.DefaultContractResolver.CreateDictionaryContract(), CsvHelper.CsvReader.CreateFuncForObject(), CsvHelper.CsvReader.CreateFuncForPrimitive(), System.Reflection.RuntimePropertyInfo.CreateGetterDelegate(), Newtonsoft.Json.Utilities.DynamicUtils.BinderWrapper.CreateMemberCalls(), CsvHelper.CsvWriter.CreatePropertyExpression(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateTemporaryCollection(), Newtonsoft.Json.Serialization.JsonDictionaryContract.CreateTemporaryDictionary(), Newtonsoft.Json.Serialization.JsonArrayContract.CreateWrapper(), Newtonsoft.Json.Serialization.DefaultSerializationBinder.GetGenericTypeFromTypeName(), System.Reflection.Emit.TypeBuilder.GetMethod(), System.UnitySerializationHolder.GetRealObject(), Newtonsoft.Json.Utilities.ConvertUtils.GetTypeCode(), System.Reflection.Emit.TypeBuilderInstantiation.InternalResolve(), Newtonsoft.Json.Serialization.JsonArrayContract.JsonArrayContract(), Newtonsoft.Json.Serialization.JsonDictionaryContract.JsonDictionaryContract(), System.TypeSpec.Resolve(), Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor(), Newtonsoft.Json.Utilities.CollectionUtils.ResolveEnumerableCollectionConstructor(), Newtonsoft.Json.Serialization.DefaultContractResolver.SetExtensionDataDelegates(), and System.Reflection.SignatureTypeExtensions.TryMakeGenericType().