Terraria Decompiled: System.Type.GetEnumData
GetEnumData()
void System.Type.GetEnumData (out string[] enumNames, out Array enumValues) inline private
Definition at line 104 of file Type.cs.
        {
            FieldInfo[] fields = this.GetFields(BindingFlags.Static | BindingFlags.Public | BindingFlags.NonPublic);
            object[] array = new object[fields.Length];
            string[] array2 = new string[fields.Length];
            for (int i = 0; i < fields.Length; i++)
            {
                array2[i] = fields[i].Name;
                array[i] = fields[i].GetRawConstantValue();
            }
            IComparer @default = Comparer<object>.Default;
            for (int j = 1; j < array.Length; j++)
            {
                int num = j;
                string text = array2[j];
                object obj = array[j];
                bool flag = false;
                while (@default.Compare(array[num - 1], obj) > 0)
                {
                    array2[num] = array2[num - 1];
                    array[num] = array[num - 1];
                    num--;
                    flag = true;
                    if (num == 0)
                    {
                        break;
                    }
                }
                if (flag)
                {
                    array2[num] = text;
                    array[num] = obj;
                }
            }
            enumNames = array2;
            enumValues = array;
        }
References System.array, System.Collections.Comparer.Default, System.Type.GetFields(), System.Reflection.FieldInfo.GetRawConstantValue(), System.Reflection.MemberInfo.Name, System.obj, and System.text.
Referenced by System.Type.GetEnumNames(), and System.Type.GetEnumRawConstantValues().