Terraria Decompiled: System.Type.GetElementType
GetElementType()
Type System.Type.GetElementType () abstract
Implements System.Runtime.InteropServices._Type.
Referenced by System.Delegate.arg_type_match_this(), System.DefaultBinder.BindToMethod(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.BuildMethodCall(), System.Runtime.Remoting.Messaging.StackBuilderSink.CheckParameters(), System.Collections.ObjectModel.Collection< T >.CopyTo(), System.Collections.ObjectModel.ReadOnlyCollection< T >.CopyTo(), FullSerializer.fsMetaType.CreateInstance(), System.Reflection.CustomAttributeTypedArgument.CustomAttributeTypedArgument(), System.DefaultBinder.FindMostSpecificType(), Newtonsoft.Json.Utilities.DynamicReflectionDelegateFactory.GenerateCreateMethodCallIL(), System.Runtime.Serialization.FormatterServices.GetClrTypeFullNameForArray(), Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType(), System.Reflection.TypeDelegator.GetElementType(), FullSerializer.Internal.fsIEnumerableConverter.GetElementType(), System.Type.GetRootElementType(), System.Runtime.CompilerServices.RuntimeHelpers.GetSubArray< T >(), System.Reflection.Emit.TypeBuilderInstantiation.InflateType(), System.Runtime.Remoting.Messaging.CADMessageBase.IsPossibleToIgnoreMarshal(), System.Reflection.Emit.CustomAttributeBuilder.IsValidParam(), System.Reflection.Emit.CustomAttributeBuilder.IsValidValue(), System.Reflection.SignatureTypeExtensions.MatchesExactly(), System.Runtime.Remoting.Proxies.RealProxy.ProcessResponse(), System.Reflection.Emit.TypeBuilder.SetConstantValue(), System.Reflection.CustomAttributeTypedArgument.ToString(), FullSerializer.Internal.fsArrayConverter.TryDeserialize(), FullSerializer.Internal.fsArrayConverter.TrySerialize(), System.Reflection.Emit.GenericInstanceKey.TypeEquals(), and System.Runtime.Serialization.Formatters.Binary.ObjectWriter.WriteArray().