Terraria Decompiled: rail.IRailBrowserImpl.GetCurrentUrl
GetCurrentUrl()
virtual bool rail.IRailBrowserImpl.GetCurrentUrl (out string url) inline virtual
Implements rail.IRailBrowser.
Definition at line 20 of file IRailBrowserImpl.cs.
        {
            IntPtr intPtr = RAIL_API_PINVOKE.new_RailString__SWIG_0();
            bool flag;
            try
            {
                flag = RAIL_API_PINVOKE.IRailBrowser_GetCurrentUrl(this.swigCPtr_, intPtr);
            }
            finally
            {
                url = RAIL_API_PINVOKE.RailString_c_str(intPtr);
                RAIL_API_PINVOKE.delete_RailString(intPtr);
            }
            return flag;
        }
References rail.RAIL_API_PINVOKE.delete_RailString(), rail.RAIL_API_PINVOKE.IRailBrowser_GetCurrentUrl(), rail.RAIL_API_PINVOKE.new_RailString__SWIG_0(), rail.RAIL_API_PINVOKE.RailString_c_str(), and rail.RailObject.swigCPtr_.