Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly
GetAssembly()
Assembly System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.GetAssembly () inline package
Definition at line 23 of file BinaryAssemblyInfo.cs.
        {
            if (this.assembly == null)
            {
                this.assembly = FormatterServices.LoadAssemblyFromStringNoThrow(this.assemblyString);
                if (this.assembly == null)
                {
                    throw new SerializationException(Environment.GetResourceString("Unable to find assembly '{0}'.", new object[] { this.assemblyString }));
                }
            }
            return this.assembly;
        }
References System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.assembly, System.Runtime.Serialization.Formatters.Binary.BinaryAssemblyInfo.assemblyString, System.Environment.GetResourceString(), and System.Runtime.Serialization.FormatterServices.LoadAssemblyFromStringNoThrow().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.GetType().