Terraria Decompiled: Terraria.IO.ResourcePackList.CreatePacksFromZips
CreatePacksFromZips()
static void Terraria.IO.ResourcePackList.CreatePacksFromZips (IServiceProvider services, string searchPath, List< ResourcePack > resourcePacks) inline static private
Definition at line 159 of file ResourcePackList.cs.
        {
            foreach (string text in Directory.GetFiles(searchPath, "*.zip"))
            {
                try
                {
                    string fileName = Path.GetFileName(text);
                    if (resourcePacks.All((ResourcePack pack) => pack.FileName != fileName))
                    {
                        resourcePacks.Add(new ResourcePack(services, text, ResourcePack.BrandingType.None));
                    }
                }
                catch (Exception ex)
                {
                    Console.WriteLine("Failed to read resource pack {0}: {1}", text, ex);
                }
            }
        }
References Terraria.IO.ResourcePack.FileName, System.IO.Path.GetFileName(), System.IO.Directory.GetFiles(), System.text, and System.Console.WriteLine().
Referenced by Terraria.IO.ResourcePackList.FromJson(), and Terraria.IO.ResourcePackList.Publishable().