Terraria Decompiled: Terraria.IO.ResourcePackList.CreatePackEntryListFromJson
CreatePackEntryListFromJson()
static IEnumerable< ResourcePackList.ResourcePackEntry > Terraria.IO.ResourcePackList.CreatePackEntryListFromJson (JArray serializedState) inline static private
Definition at line 206 of file ResourcePackList.cs.
        {
            try
            {
                if (serializedState != null && serializedState.Count != 0)
                {
                    return serializedState.ToObject<List<ResourcePackList.ResourcePackEntry>>();
                }
            }
            catch (JsonReaderException ex)
            {
                Console.WriteLine("Failed to parse configuration entry for resource pack list. {0}", ex);
            }
            return new List<ResourcePackList.ResourcePackEntry>();
        }
References Newtonsoft.Json.Linq.JContainer.Count, Newtonsoft.Json.Linq.JToken.ToObject(), and System.Console.WriteLine().
Referenced by Terraria.IO.ResourcePackList.CreatePacksFromSavedJson().