Terraria Decompiled: Terraria.IO.ResourcePackList.CreatePacksFromSavedJson
CreatePacksFromSavedJson()
static void Terraria.IO.ResourcePackList.CreatePacksFromSavedJson (JArray serializedState, IServiceProvider services, string searchPath, List< ResourcePack > resourcePacks) inline static private
Definition at line 102 of file ResourcePackList.cs.
        {
            foreach (ResourcePackList.ResourcePackEntry resourcePackEntry in ResourcePackList.CreatePackEntryListFromJson(serializedState))
            {
                if (resourcePackEntry.FileName != null)
                {
                    string text = Path.Combine(searchPath, resourcePackEntry.FileName);
                    try
                    {
                        bool flag = File.Exists(text) || Directory.Exists(text);
                        ResourcePack.BrandingType brandingType = ResourcePack.BrandingType.None;
                        string text2;
                        if (!flag && SocialAPI.Workshop != null && SocialAPI.Workshop.TryGetPath(resourcePackEntry.FileName, out text2))
{
                            text = text2;
                            flag = true;
                            brandingType = SocialAPI.Workshop.Branding.ResourcePackBrand;
                        }
                        if (flag)
{
                            ResourcePack resourcePack = new ResourcePack(services, text, brandingType)
{
                                IsEnabled = resourcePackEntry.Enabled,
                                SortingOrder = resourcePackEntry.SortingOrder
                            };
                            resourcePacks.Add(resourcePack);
                        }
                    }
                    catch (Exception ex)
                    {
                        Console.WriteLine("Failed to read resource pack {0}: {1}", text, ex);
                    }
                }
            }
        }
References System.Collections.Generic.List< T >.Add(), System.IO.Path.Combine(), Terraria.IO.ResourcePackList.CreatePackEntryListFromJson(), System.IO.Directory.Exists(), System.IO.File.Exists(), System.text, Terraria.Social.SocialAPI.Workshop, and System.Console.WriteLine().
Referenced by Terraria.IO.ResourcePackList.FromJson().