Terraria Decompiled: Terraria.Social.Steam.NetSocialModule.Initialize
Initialize()
override void Terraria.Social.Steam.NetSocialModule.Initialize () inline
Definition at line 21 of file NetSocialModule.cs.
        {
            CoreSocialModule.OnTick += this._reader.ReadTick;
            CoreSocialModule.OnTick += this._writer.SendAll;
            this._lobbyChatMessage = Callback<LobbyChatMsg_t>.Create(new Callback<LobbyChatMsg_t>.DispatchDelegate(this.OnLobbyChatMessage));
        }
References Terraria.Social.Steam.NetSocialModule._reader, Terraria.Social.Steam.NetSocialModule._writer, Steamworks.Callback< T >.Create(), Terraria.Social.Steam.NetSocialModule.OnLobbyChatMessage(), Terraria.Social.Steam.SteamP2PReader.ReadTick(), and Terraria.Social.Steam.SteamP2PWriter.SendAll().