Terraria Decompiled: System.Threading.ReaderWriterLock.AcquireReaderLock
AcquireReaderLock() [2/3]
void System.Threading.ReaderWriterLock.AcquireReaderLock (int millisecondsTimeout, int initialLockCount) inline private
Definition at line 79 of file ReaderWriterLock.cs.
        {
            lock (this)
            {
                if (this.HasWriterLock())
                {
                    this.AcquireWriterLock(millisecondsTimeout, initialLockCount);
                }
                else
                {
                    object obj = this.reader_locks[Thread.CurrentThreadId];
                    if (obj == null)
                    {
                        this.readers++;
                        try
{
                            if (this.state < 0 || !this.writer_queue.IsEmpty)
{
                                while (Monitor.Wait(this, millisecondsTimeout))
{
                                    if (this.state >= 0)
{
                                        goto IL_007B;
                                    }
                                }
                                throw new ApplicationException("Timeout expired");
                            }
                            IL_007B:;
                        }
                        finally
{
                            this.readers--;
                        }
                        this.reader_locks[Thread.CurrentThreadId] = initialLockCount;
                        this.state += initialLockCount;
                    }
                    else
                    {
                        this.reader_locks[Thread.CurrentThreadId] = (int)obj + 1;
                        this.state++;
                    }
                }
            }
        }
References System.Threading.ReaderWriterLock.AcquireWriterLock(), System.Threading.Thread.CurrentThreadId, System.Threading.ReaderWriterLock.HasWriterLock(), int, System.Threading.LockQueue.IsEmpty, System.obj, System.Threading.ReaderWriterLock.reader_locks, System.Threading.ReaderWriterLock.readers, System.Threading.ReaderWriterLock.state, System.Threading.Monitor.Wait(), and System.Threading.ReaderWriterLock.writer_queue.