Terraria Decompiled: Terraria.UI.ChestUI.DrawSlots
DrawSlots()
static void Terraria.UI.ChestUI.DrawSlots (SpriteBatch spriteBatch) inline static private
Definition at line 303 of file ChestUI.cs.
        {
            int num = 10;
            int num2 = 4;
            Player player = Main.player[Main.myPlayer];
            int num3 = 0;
            Chest chest = null;
            if (player.chest > -1)
            {
                num3 = 3;
                chest = Main.chest[player.chest];
            }
            if (player.chest == -2)
            {
                num3 = 4;
                chest = player.bank;
            }
            if (player.chest == -3)
            {
                num3 = 4;
                chest = player.bank2;
            }
            if (player.chest == -4)
            {
                num3 = 4;
                chest = player.bank3;
            }
            if (player.chest == -5)
            {
                num3 = 32;
                chest = player.bank4;
            }
            Item[] item = chest.item;
            int maxItems = chest.maxItems;
            Main.inventoryScale = 0.755f;
            Rectangle rectangle = new Rectangle(73, Main.instance.invBottom, (int)((float)(num * 56) * Main.inventoryScale), (int)((float)(num2 * 56) * Main.inventoryScale));
            ChestUI.LastChestDisplayRectangle = rectangle;
            if (rectangle.Contains(Main.mouseX, Main.mouseY) && !PlayerInput.IgnoreMouseInterface)
            {
                player.mouseInterface = true;
            }
            int num4 = (int)Math.Max(0.0, Math.Ceiling((double)((float)maxItems / (float)num)) - 4.0);
            ChestUI.StartingRowForDrawing = Utils.Clamp<int>(ChestUI.StartingRowForDrawing, 0, num4);
            ChestUI.LastHighestChestRow = num4;
            ItemSlot.PrepareForChest(chest);
            for (int i = 0; i < num; i++)
            {
                for (int j = 0; j < num2; j++)
                {
                    int num5 = i + j * num + ChestUI.StartingRowForDrawing * num;
                    if (num5 < item.Length)
                    {
                        int num6 = (int)(73f + (float)(i * 56) * Main.inventoryScale);
                        int num7 = (int)((float)Main.instance.invBottom + (float)(j * 56) * Main.inventoryScale);
                        new Color(100, 100, 100, 100);
                        if (Utils.FloatIntersect((float)Main.mouseX, (float)Main.mouseY, 0f, 0f, (float)num6, (float)num7, (float)TextureAssets.InventoryBack.Width() * Main.inventoryScale, (float)TextureAssets.InventoryBack.Height() * Main.inventoryScale) && !PlayerInput.IgnoreMouseInterface)
{
                            player.mouseInterface = true;
                            ItemSlot.Handle(item, num3, num5, true);
                        }
                        ItemSlot.Draw(spriteBatch, item, num3, num5, new Vector2((float)num6, (float)num7), default(Color));
                    }
                }
            }
        }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, System.Math.Ceiling(), Terraria.Main.chest, Terraria.Player.chest, Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.UI.ItemSlot.Draw(), Terraria.Utils.FloatIntersect(), Terraria.UI.ItemSlot.Handle(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.instance, int, Terraria.Main.invBottom, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.Main.inventoryScale, System.item, Terraria.Chest.item, System.Math.Max(), Terraria.Chest.maxItems, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.UI.ItemSlot.PrepareForChest(), Terraria.UI.ChestUI.StartingRowForDrawing, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.UI.ChestUI.Draw().