Terraria Decompiled: Terraria.UI.ChestUI.DepositAll
DepositAll()
static void Terraria.UI.ChestUI.DepositAll () inline static
Definition at line 518 of file ChestUI.cs.
        {
            Player player = Main.player[Main.myPlayer];
            if (player.chest > -1)
            {
                ChestUI.MoveCoins(player.inventory, Main.chest[player.chest]);
            }
            else if (player.chest == -3)
            {
                ChestUI.MoveCoins(player.inventory, player.bank2);
            }
            else if (player.chest == -4)
            {
                ChestUI.MoveCoins(player.inventory, player.bank3);
            }
            else if (player.chest == -5)
            {
                ChestUI.MoveCoins(player.inventory, player.bank4);
            }
            else
            {
                ChestUI.MoveCoins(player.inventory, player.bank);
            }
            for (int i = 49; i >= 10; i--)
            {
                if (player.inventory[i].stack > 0 && player.inventory[i].type > 0 && !player.inventory[i].favorited)
                {
                    if (player.inventory[i].maxStack > 1)
                    {
                        Chest currentContainer = player.GetCurrentContainer();
                        if (player.chest > -1)
{
                            ChestUI.DepositAll_IntoWorldChest(player, currentContainer, i);
                        }
                        else
{
                            ChestUI.DepositAll_IntoLocalChest(player, currentContainer, i);
                        }
                    }
                    if (player.inventory[i].stack > 0)
                    {
                        if (player.chest > -1)
{
                            int j = 0;
                            while (j < Main.chest[player.chest].maxItems)
{
                                if (Main.chest[player.chest].item[j].stack == 0)
{
                                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                                    Main.chest[player.chest].item[j] = player.inventory[i].Clone();
                                    player.inventory[i].SetDefaults(0, null);
                                    ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, i, Main.chest[player.chest].item, 3, j, Main.chest[player.chest].item[j].stack);
                                    if (Main.netMode == 1)
{
                                        NetMessage.SendData(32, -1, -1, null, player.chest, (float)j, 0f, 0f, 0, 0, 0);
                                        break;
                                    }
                                    break;
                                }
                                else
{
                                    j++;
                                }
                            }
                        }
                        else if (player.chest == -3)
{
                            for (int k = 0; k < player.bank2.maxItems; k++)
{
                                if (player.bank2.item[k].stack == 0)
{
                                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                                    player.bank2.item[k] = player.inventory[i].Clone();
                                    player.inventory[i].SetDefaults(0, null);
                                    ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, i, player.bank2.item, 4, k, player.bank2.item[k].stack);
                                    break;
                                }
                            }
                        }
                        else if (player.chest == -4)
{
                            for (int l = 0; l < player.bank3.maxItems; l++)
{
                                if (player.bank3.item[l].stack == 0)
{
                                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                                    player.bank3.item[l] = player.inventory[i].Clone();
                                    player.inventory[i].SetDefaults(0, null);
                                    ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, i, player.bank3.item, 4, l, player.bank3.item[l].stack);
                                    break;
                                }
                            }
                        }
                        else if (player.chest == -5)
{
                            for (int m = 0; m < player.bank4.maxItems; m++)
{
                                if (player.bank4.item[m].stack == 0)
{
                                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                                    player.bank4.item[m] = player.inventory[i].Clone();
                                    player.inventory[i].SetDefaults(0, null);
                                    ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, i, player.bank4.item, 32, m, player.bank4.item[m].stack);
                                    break;
                                }
                            }
                        }
                        else
{
                            for (int n = 0; n < player.bank.maxItems; n++)
{
                                if (player.bank.item[n].stack == 0)
{
                                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                                    player.bank.item[n] = player.inventory[i].Clone();
                                    player.inventory[i].SetDefaults(0, null);
                                    ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, i, player.bank.item, 4, n, player.bank.item[n].stack);
                                    break;
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Main.chest, Terraria.Player.chest, Terraria.Item.Clone(), Terraria.UI.ChestUI.DepositAll_IntoLocalChest(), Terraria.UI.ChestUI.DepositAll_IntoWorldChest(), Terraria.UI.ItemSlot.DisplayTransfer_OneWay(), Terraria.Item.favorited, Terraria.Player.GetCurrentContainer(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Item.maxStack, Terraria.UI.ChestUI.MoveCoins(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ChestUI.DrawButton().