Terraria Decompiled: Terraria.UI.ChestUI.QuickStack
QuickStack()
static void Terraria.UI.ChestUI.QuickStack (bool voidStack = false) inline static
Definition at line 645 of file ChestUI.cs.
        {
            Player player = Main.player[Main.myPlayer];
            Item[] array = player.inventory;
            if (voidStack)
            {
                array = player.bank4.item;
            }
            Vector2 center = player.Center;
            if (!voidStack && player.chest == -5)
            {
                ChestUI.MoveCoins(array, player.bank4);
            }
            else if (player.chest == -4)
            {
                ChestUI.MoveCoins(array, player.bank3);
            }
            else if (player.chest == -3)
            {
                ChestUI.MoveCoins(array, player.bank2);
            }
            else if (player.chest == -2)
            {
                ChestUI.MoveCoins(array, player.bank);
            }
            Chest currentContainer = player.GetCurrentContainer();
            Item[] item = currentContainer.item;
            int num = 3;
            if (voidStack || player.chest == -5)
            {
                num = 32;
            }
            else if (player.chest < -1)
            {
                num = 4;
            }
            List<int> list = new List<int>();
            List<int> list2 = new List<int>();
            List<int> list3 = new List<int>();
            Dictionary<int, int> dictionary = new Dictionary<int, int>();
            List<int> list4 = new List<int>();
            bool[] array2 = new bool[item.Length];
            for (int i = 0; i < currentContainer.maxItems; i++)
            {
                if (item[i].type > 0 && item[i].stack > 0 && (item[i].type < 71 || item[i].type > 74))
                {
                    list2.Add(i);
                    list.Add(item[i].type);
                }
                if (item[i].type == 0 || item[i].stack <= 0)
                {
                    list3.Add(i);
                }
            }
            int num2 = 50;
            int num3 = 10;
            if (player.chest <= -2)
            {
                num2 += 4;
            }
            if (voidStack)
            {
                num3 = 0;
                num2 = player.bank4.maxItems;
            }
            for (int j = num3; j < num2; j++)
            {
                if (list.Contains(array[j].type) && !array[j].favorited)
                {
                    dictionary.Add(j, array[j].type);
                }
            }
            for (int k = 0; k < list2.Count; k++)
            {
                int num4 = list2[k];
                foreach (KeyValuePair<int, int> keyValuePair in dictionary)
                {
                    if (Item.CanStack(array[keyValuePair.Key], item[num4]))
                    {
                        int num5 = array[keyValuePair.Key].stack;
                        int num6 = item[num4].maxStack - item[num4].stack;
                        if (num6 == 0)
{
                            break;
                        }
                        if (num5 > num6)
{
                            num5 = num6;
                        }
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        item[num4].stack += num5;
                        array[keyValuePair.Key].stack -= num5;
                        if (array[keyValuePair.Key].stack == 0)
{
                            array[keyValuePair.Key].SetDefaults(0, null);
                        }
                        array2[num4] = true;
                    }
                }
            }
            foreach (KeyValuePair<int, int> keyValuePair2 in dictionary)
            {
                if (array[keyValuePair2.Key].stack == 0)
                {
                    list4.Add(keyValuePair2.Key);
                }
            }
            foreach (int num7 in list4)
            {
                dictionary.Remove(num7);
            }
            for (int l = 0; l < list3.Count; l++)
            {
                int num8 = list3[l];
                bool flag = true;
                foreach (KeyValuePair<int, int> keyValuePair3 in dictionary)
                {
                    if (array[keyValuePair3.Key].stack != 0 && (flag || Item.CanStack(array[keyValuePair3.Key], item[num8])))
                    {
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        if (flag)
{
                            item[num8] = array[keyValuePair3.Key];
                            array[keyValuePair3.Key] = new Item();
                            ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, keyValuePair3.Key, item, num, num8, 1);
                        }
                        else
{
                            int num9 = array[keyValuePair3.Key].stack;
                            int num10 = item[num8].maxStack - item[num8].stack;
                            if (num10 == 0)
{
                                break;
                            }
                            if (num9 > num10)
{
                                num9 = num10;
                            }
                            item[num8].stack += num9;
                            array[keyValuePair3.Key].stack -= num9;
                            if (array[keyValuePair3.Key].stack == 0)
{
                                array[keyValuePair3.Key] = new Item();
                            }
                            ItemSlot.DisplayTransfer_OneWay(player.inventory, 0, keyValuePair3.Key, item, num, num8, 1);
                        }
                        array2[num8] = true;
                        flag = false;
                    }
                }
            }
            if (Main.netMode == 1 && player.chest >= 0)
            {
                for (int m = 0; m < array2.Length; m++)
                {
                    NetMessage.SendData(32, -1, -1, null, player.chest, (float)m, 0f, 0f, 0, 0, 0);
                }
            }
            list.Clear();
            list2.Clear();
            list3.Clear();
            dictionary.Clear();
            list4.Clear();
        }
References System.Collections.Generic.List< T >.Add(), System.array, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Item.CanStack(), Terraria.Entity.Center, Terraria.Player.chest, System.Collections.Generic.List< T >.Count, System.dictionary, Terraria.UI.ItemSlot.DisplayTransfer_OneWay(), Terraria.Player.GetCurrentContainer(), Terraria.Player.inventory, System.item, Terraria.Chest.item, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.list, Terraria.Chest.maxItems, Terraria.UI.ChestUI.MoveCoins(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), and System.stack.
Referenced by Terraria.UI.ChestUI.DrawButton().