Terraria Decompiled: Terraria.UI.ChestUI.Draw
Draw()
static void Terraria.UI.ChestUI.Draw (SpriteBatch spritebatch) inline static
Definition at line 50 of file ChestUI.cs.
        {
            if (Main.player[Main.myPlayer].chest != -1 && !Main.PipsUseGrid && !NewCraftingUI.Visible)
            {
                Main.inventoryScale = 0.755f;
                if (Utils.FloatIntersect((float)Main.mouseX, (float)Main.mouseY, 0f, 0f, 73f, (float)Main.instance.invBottom, 560f * Main.inventoryScale, 224f * Main.inventoryScale))
                {
                    Main.player[Main.myPlayer].mouseInterface = true;
                }
                ChestUI.DrawName(spritebatch);
                ChestUI.DrawButtons(spritebatch);
                ChestUI.DrawSlots(spritebatch);
                return;
            }
            for (int i = 0; i < ChestUI.ButtonID.Count; i++)
            {
                ChestUI.ButtonScale[i] = 0.75f;
                ChestUI.ButtonHovered[i] = false;
            }
        }
References Terraria.UI.ChestUI.ButtonHovered, Terraria.UI.ChestUI.ButtonScale, Terraria.Player.chest, Terraria.UI.ChestUI.ButtonID.Count, Terraria.UI.ChestUI.DrawButtons(), Terraria.UI.ChestUI.DrawName(), Terraria.UI.ChestUI.DrawSlots(), Terraria.Utils.FloatIntersect(), Terraria.Main.instance, Terraria.Main.invBottom, Terraria.Main.inventoryScale, Terraria.Player.mouseInterface, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.myPlayer, Terraria.Main.PipsUseGrid, Terraria.Main.player, and Terraria.GameContent.UI.NewCraftingUI.Visible.
Referenced by Terraria.Main.DrawInventory().