Terraria Decompiled: Terraria.UI.ChestUI.DepositAll_IntoLocalChest
DepositAll_IntoLocalChest()
static void Terraria.UI.ChestUI.DepositAll_IntoLocalChest (Player player, Chest chest, int p) inline static private
Definition at line 489 of file ChestUI.cs.
        {
            for (int i = 0; i < chest.maxItems; i++)
            {
                if (chest.item[i].stack < chest.item[i].maxStack && Item.CanStack(player.inventory[p], chest.item[i]))
                {
                    int num = player.inventory[p].stack;
                    if (player.inventory[p].stack + chest.item[i].stack > chest.item[i].maxStack)
                    {
                        num = chest.item[i].maxStack - chest.item[i].stack;
                    }
                    player.inventory[p].stack -= num;
                    chest.item[i].stack += num;
                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    if (player.inventory[p].stack <= 0)
                    {
                        player.inventory[p].SetDefaults(0, null);
                        return;
                    }
                    if (chest.item[i].type == 0)
                    {
                        chest.item[i] = player.inventory[p].Clone();
                        player.inventory[p].SetDefaults(0, null);
                    }
                }
            }
        }
References Terraria.Item.CanStack(), Terraria.Item.Clone(), Terraria.Player.inventory, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Item.maxStack, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.UI.ChestUI.DepositAll().