Terraria Decompiled: Terraria.UI.ChestUI.Restock
Restock()
static void Terraria.UI.ChestUI.Restock () inline static
Definition at line 856 of file ChestUI.cs.
        {
            Player player = Main.player[Main.myPlayer];
            Item[] inventory = player.inventory;
            Item[] array = player.bank.item;
            if (player.chest > -1)
            {
                array = Main.chest[player.chest].item;
            }
            else if (player.chest == -2)
            {
                array = player.bank.item;
            }
            else if (player.chest == -3)
            {
                array = player.bank2.item;
            }
            else if (player.chest == -4)
            {
                array = player.bank3.item;
            }
            else if (player.chest == -5)
            {
                array = player.bank4.item;
            }
            HashSet<int> hashSet = new HashSet<int>();
            List<int> list = new List<int>();
            List<int> list2 = new List<int>();
            for (int i = 57; i >= 0; i--)
            {
                Item item = inventory[i];
                if ((i < 50 || i >= 54) && (item.type < 71 || item.type > 74))
                {
                    if (item.stack == 0 || item.type == 0 || item.type == 0)
                    {
                        list2.Add(i);
                    }
                    else if (item.maxStack > 1 && (!item.favorited || !item.OnlyNeedOneInInventory()))
                    {
                        hashSet.Add(item.type);
                        if (item.stack < item.maxStack)
{
                            list.Add(i);
                        }
                    }
                }
            }
            bool flag = false;
            for (int j = 0; j < array.Length; j++)
            {
                if (array[j].stack >= 1 && array[j].prefix == 0 && hashSet.Contains(array[j].type))
                {
                    bool flag2 = false;
                    for (int k = 0; k < list.Count; k++)
                    {
                        int num = list[k];
                        int num2 = 0;
                        if (num >= 50)
{
                            num2 = 2;
                        }
                        if (Item.CanStack(inventory[num], array[j]) && ItemSlot.PickItemMovementAction(inventory, num2, num, array[j]) != -1)
{
                            int num3 = array[j].stack;
                            if (inventory[num].maxStack - inventory[num].stack < num3)
{
                                num3 = inventory[num].maxStack - inventory[num].stack;
                            }
                            inventory[num].stack += num3;
                            array[j].stack -= num3;
                            flag = true;
                            if (inventory[num].stack == inventory[num].maxStack)
{
                                if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
{
                                    NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)j, 0f, 0f, 0, 0, 0);
                                }
                                list.RemoveAt(k);
                                k--;
                            }
                            if (array[j].stack == 0)
{
                                array[j] = new Item();
                                flag2 = true;
                                if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
{
                                    NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)j, 0f, 0f, 0, 0, 0);
                                    break;
                                }
                                break;
                            }
                        }
                    }
                    if (!flag2 && list2.Count > 0 && array[j].ammo != 0)
                    {
                        for (int l = 0; l < list2.Count; l++)
{
                            int num4 = 0;
                            if (list2[l] >= 50)
{
                                num4 = 2;
                            }
                            if (ItemSlot.PickItemMovementAction(inventory, num4, list2[l], array[j]) != -1)
{
                                Utils.Swap<Item>(ref inventory[list2[l]], ref array[j]);
                                if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
{
                                    NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)j, 0f, 0f, 0, 0, 0);
                                }
                                list.Add(list2[l]);
                                list2.RemoveAt(l);
                                flag = true;
                                break;
                            }
                        }
                    }
                }
            }
            if (flag)
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
            }
        }
References System.Collections.Generic.List< T >.Add(), System.array, Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.Item.CanStack(), Terraria.Main.chest, Terraria.Player.chest, System.Collections.Generic.List< T >.Count, Terraria.Player.inventory, System.item, Terraria.Chest.item, System.list, Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.UI.ItemSlot.PickItemMovementAction(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.NetMessage.SendData(), System.stack, and Terraria.Item.stack.
Referenced by Terraria.UI.ChestUI.DrawButton().