Terraria Decompiled: Terraria.UI.ChestUI.MoveCoins
MoveCoins() [1/2]
static long Terraria.UI.ChestUI.MoveCoins (Item[] pInv, Chest chest) inline static
Definition at line 981 of file ChestUI.cs.
        {
            return ChestUI.MoveCoins(pInv, chest.item, chest.maxItems);
        }
References Terraria.Chest.item, Terraria.Chest.maxItems, and Terraria.UI.ChestUI.MoveCoins().
Referenced by Terraria.UI.ChestUI.DepositAll(), Terraria.UI.ChestUI.MoveCoins(), Terraria.UI.ChestUI.QuickStack(), and Terraria.GameContent.QuickStacking.QuickStackToNearbyBanks().