Terraria Decompiled: Terraria.UI.ChestUI.MoveCoins
MoveCoins() [2/2]
static long Terraria.UI.ChestUI.MoveCoins (Item[] pInv, Item[] cInv, int chestMaxItems) inline static
Definition at line 987 of file ChestUI.cs.
        {
            bool flag = false;
            int[] array = new int[4];
            List<int> list = new List<int>();
            List<int> list2 = new List<int>();
            bool flag2 = false;
            int[] array2 = new int[chestMaxItems];
            bool flag3;
            long num = Utils.CoinsCount(out flag3, pInv, new int[0]);
            for (int i = 0; i < cInv.Length; i++)
            {
                array2[i] = -1;
                if (cInv[i].stack < 1 || cInv[i].type < 1)
                {
                    list2.Add(i);
                    cInv[i] = new Item();
                }
                if (cInv[i] != null && cInv[i].stack > 0)
                {
                    int num2 = 0;
                    if (cInv[i].type == 71)
                    {
                        num2 = 1;
                    }
                    if (cInv[i].type == 72)
                    {
                        num2 = 2;
                    }
                    if (cInv[i].type == 73)
                    {
                        num2 = 3;
                    }
                    if (cInv[i].type == 74)
                    {
                        num2 = 4;
                    }
                    array2[i] = num2 - 1;
                    if (num2 > 0)
                    {
                        array[num2 - 1] += cInv[i].stack;
                        list2.Add(i);
                        cInv[i] = new Item();
                        flag2 = true;
                    }
                }
            }
            if (!flag2)
            {
                return 0L;
            }
            for (int j = 0; j < pInv.Length; j++)
            {
                if (j != 58 && pInv[j] != null && pInv[j].stack > 0 && !pInv[j].favorited)
                {
                    int num3 = 0;
                    if (pInv[j].type == 71)
                    {
                        num3 = 1;
                    }
                    if (pInv[j].type == 72)
                    {
                        num3 = 2;
                    }
                    if (pInv[j].type == 73)
                    {
                        num3 = 3;
                    }
                    if (pInv[j].type == 74)
                    {
                        num3 = 4;
                    }
                    if (num3 > 0)
                    {
                        flag = true;
                        array[num3 - 1] += pInv[j].stack;
                        list.Add(j);
                        pInv[j] = new Item();
                    }
                }
            }
            for (int k = 0; k < 3; k++)
            {
                while (array[k] >= 100)
                {
                    array[k] -= 100;
                    array[k + 1]++;
                }
            }
            for (int l = 0; l < chestMaxItems; l++)
            {
                if (array2[l] >= 0 && cInv[l].type == 0)
                {
                    int num4 = l;
                    int num5 = array2[l];
                    if (array[num5] > 0)
                    {
                        cInv[num4].SetDefaults(71 + num5, null);
                        cInv[num4].stack = array[num5];
                        if (cInv[num4].stack > cInv[num4].maxStack)
{
                            cInv[num4].stack = cInv[num4].maxStack;
                        }
                        array[num5] -= cInv[num4].stack;
                        array2[l] = -1;
                    }
                    if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
                    {
                        NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)num4, 0f, 0f, 0, 0, 0);
                    }
                    list2.Remove(num4);
                }
            }
            for (int m = 0; m < chestMaxItems; m++)
            {
                if (array2[m] >= 0 && cInv[m].type == 0)
                {
                    int num6 = m;
                    int n = 3;
                    while (n >= 0)
                    {
                        if (array[n] > 0)
{
                            cInv[num6].SetDefaults(71 + n, null);
                            cInv[num6].stack = array[n];
                            if (cInv[num6].stack > cInv[num6].maxStack)
{
                                cInv[num6].stack = cInv[num6].maxStack;
                            }
                            array[n] -= cInv[num6].stack;
                            array2[m] = -1;
                            break;
                        }
                        if (array[n] == 0)
{
                            n--;
                        }
                    }
                    if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
                    {
                        NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)num6, 0f, 0f, 0, 0, 0);
                    }
                    list2.Remove(num6);
                }
            }
            while (list2.Count > 0)
            {
                int num7 = list2[0];
                int num8 = 3;
                while (num8 >= 0)
                {
                    if (array[num8] > 0)
                    {
                        cInv[num7].SetDefaults(71 + num8, null);
                        cInv[num7].stack = array[num8];
                        if (cInv[num7].stack > cInv[num7].maxStack)
{
                            cInv[num7].stack = cInv[num7].maxStack;
                        }
                        array[num8] -= cInv[num7].stack;
                        break;
                    }
                    if (array[num8] == 0)
                    {
                        num8--;
                    }
                }
                if (Main.netMode == 1 && Main.player[Main.myPlayer].chest > -1)
                {
                    NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)list2[0], 0f, 0f, 0, 0, 0);
                }
                list2.RemoveAt(0);
            }
            int num9 = 3;
            while (num9 >= 0 && list.Count > 0)
            {
                int num10 = list[0];
                if (array[num9] > 0)
                {
                    pInv[num10].SetDefaults(71 + num9, null);
                    pInv[num10].stack = array[num9];
                    if (pInv[num10].stack > pInv[num10].maxStack)
                    {
                        pInv[num10].stack = pInv[num10].maxStack;
                    }
                    array[num9] -= pInv[num10].stack;
                    flag = false;
                    list.RemoveAt(0);
                }
                if (array[num9] == 0)
                {
                    num9--;
                }
            }
            if (flag)
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
            }
            bool flag4;
            long num11 = Utils.CoinsCount(out flag4, pInv, new int[0]);
            if (flag3 || flag4)
            {
                return 0L;
            }
            return num - num11;
        }
References System.Collections.Generic.List< T >.Add(), System.array, Terraria.Player.chest, Terraria.Utils.CoinsCount(), System.Collections.Generic.List< T >.Count, Microsoft.Xna.Framework.Input.L, System.list, Terraria.Item.maxStack, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), System.Collections.Generic.List< T >.Remove(), System.Collections.Generic.List< T >.RemoveAt(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), System.stack, and Terraria.Item.stack.