Terraria Decompiled: Terraria.UI.ChestUI.RenameChest
RenameChest()
static void Terraria.UI.ChestUI.RenameChest () inline static
Definition at line 811 of file ChestUI.cs.
        {
            Player player = Main.player[Main.myPlayer];
            if (!Main.editChest)
            {
                IngameFancyUI.OpenVirtualKeyboard(2);
                return;
            }
            ChestUI.RenameChestSubmit(player);
        }
References Terraria.Main.editChest, Terraria.Main.myPlayer, Terraria.UI.IngameFancyUI.OpenVirtualKeyboard(), Terraria.Main.player, and Terraria.UI.ChestUI.RenameChestSubmit().
Referenced by Terraria.UI.ChestUI.DrawButton().