Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants
WallVariants()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants (DungeonData data) inline
Definition at line 28 of file DungeonGlobalWallVariants.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int[] wallVariants = data.wallVariants;
            int num = wallVariants.Length;
            for (int i = 0; i < 5; i++)
            {
                for (int j = 0; j < num; j++)
                {
                    int num2 = genRand.Next(40, 240);
                    int num3 = genRand.Next(data.dungeonBounds.Left, data.dungeonBounds.Right);
                    int num4 = genRand.Next(data.dungeonBounds.Top, data.dungeonBounds.Bottom);
                    for (int k = num3 - num2; k < num3 + num2; k++)
                    {
                        for (int l = num4 - num2; l < num4 + num2; l++)
{
                            if ((double)l > Main.worldSurface && WorldGen.InWorld(k, l, 2))
{
                                int num5 = Math.Abs(num3 - k);
                                int num6 = Math.Abs(num4 - l);
                                if (Math.Sqrt((double)(num5 * num5 + num6 * num6)) < (double)((float)num2 * 0.4f) && Main.wallDungeon[(int)Main.tile[k, l].wall])
{
                                    this.SpreadWallDungeon(data, k, l, (ushort)wallVariants[j], true);
                                }
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonBounds, Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.GameContent.Generation.Dungeon.DungeonData.wallVariants, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.GenerateFeature().