Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon
SpreadWallDungeon()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon (DungeonData data, int x, int y, ushort wallType, bool dungeonWallOnly = true) inline
Definition at line 60 of file DungeonGlobalWallVariants.cs.
        {
            if (!WorldGen.InWorld(x, y, 0))
            {
                return;
            }
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            HashSet<Point> hashSet = new HashSet<Point>();
            list2.Add(new Point(x, y));
            while (list2.Count > 0)
            {
                list.Clear();
                list.AddRange(list2);
                list2.Clear();
                while (list.Count > 0)
                {
                    Point point = list[0];
                    if (!WorldGen.InWorld(point.X, point.Y, 1))
                    {
                        list.Remove(point);
                    }
                    else
                    {
                        hashSet.Add(point);
                        list.Remove(point);
                        Tile tile = Main.tile[point.X, point.Y];
                        if (tile.wall != 0 && tile.wall != wallType && tile.wall != 244 && tile.wall != 62 && data.CanGenerateFeatureAt(this, point.X, point.Y))
{
                            if (data.dungeonEntrance.Bounds.Contains(point.X, point.Y))
{
                                if (tile.wall != data.dungeonEntrance.settings.StyleData.BrickWallType)
{
                                    continue;
                                }
                            }
                            else if (dungeonWallOnly && tile.wall != data.genVars.brickWallType)
{
                                continue;
                            }
                            if (!WorldGen.SolidTile(point.X, point.Y, false))
{
                                tile.wall = wallType;
                                Point point2 = new Point(point.X - 1, point.Y);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X + 1, point.Y);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X, point.Y - 1);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X, point.Y + 1);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                            }
                            else if (tile.active())
{
                                tile.wall = wallType;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.brickWallType, Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonEntrance, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.WorldGen.InWorld(), System.list, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants().