Terraria Decompiled: Mono.Math.BigInteger.ModulusRing.Difference
Difference()
BigInteger Mono.Math.BigInteger.ModulusRing.Difference (BigInteger a, BigInteger b) inline
Definition at line 991 of file BigInteger.cs.
            {
                BigInteger.Sign sign = BigInteger.Kernel.Compare(a, b);
                BigInteger bigInteger;
                switch (sign)
                {
                case BigInteger.Sign.Negative:
                    bigInteger = b - a;
                    break;
                case BigInteger.Sign.Zero:
                    return 0;
                case BigInteger.Sign.Positive:
                    bigInteger = a - b;
                    break;
                default:
                    throw new Exception();
                }
                if (bigInteger >= this.mod)
                {
                    if (bigInteger.length >= this.mod.length << 1)
                    {
                        bigInteger %= this.mod;
                    }
                    else
                    {
                        this.BarrettReduction(bigInteger);
                    }
                }
                if (sign == BigInteger.Sign.Negative)
                {
                    bigInteger = this.mod - bigInteger;
                }
                return bigInteger;
            }
References Mono.Math.BigInteger.ModulusRing.BarrettReduction(), Mono.Math.BigInteger.Kernel.Compare(), Mono.Math.BigInteger.length, and Mono.Math.BigInteger.ModulusRing.mod.
Referenced by Mono.Math.BigInteger.Kernel.modInverse().