Terraria Decompiled: Mono.Math.BigInteger.ModulusRing.BarrettReduction
BarrettReduction()
void Mono.Math.BigInteger.ModulusRing.BarrettReduction (BigInteger x) inline
Definition at line 931 of file BigInteger.cs.
            {
                BigInteger bigInteger = this.mod;
                uint length = bigInteger.length;
                uint num = length + 1U;
                uint num2 = length - 1U;
                if (x.length < length)
                {
                    return;
                }
                if ((long)x.data.Length < (long)((ulong)x.length))
                {
                    throw new IndexOutOfRangeException("x out of range");
                }
                BigInteger bigInteger2 = new BigInteger(BigInteger.Sign.Positive, x.length - num2 + this.constant.length);
                BigInteger.Kernel.Multiply(x.data, num2, x.length - num2, this.constant.data, 0U, this.constant.length, bigInteger2.data, 0U);
                uint num3 = ((x.length > num) ? num : x.length);
                x.length = num3;
                x.Normalize();
                BigInteger bigInteger3 = new BigInteger(BigInteger.Sign.Positive, num);
                BigInteger.Kernel.MultiplyMod2p32pmod(bigInteger2.data, (int)num, (int)(bigInteger2.length - num), bigInteger.data, 0, (int)bigInteger.length, bigInteger3.data, 0, (int)num);
                bigInteger3.Normalize();
                if (bigInteger3 <= x)
                {
                    BigInteger.Kernel.MinusEq(x, bigInteger3);
                }
                else
                {
                    BigInteger bigInteger4 = new BigInteger(BigInteger.Sign.Positive, num + 1U);
                    bigInteger4.data[(int)num] = 1U;
                    BigInteger.Kernel.MinusEq(bigInteger4, bigInteger3);
                    BigInteger.Kernel.PlusEq(x, bigInteger4);
                }
                while (x >= bigInteger)
                {
                    BigInteger.Kernel.MinusEq(x, bigInteger);
                }
            }
References Mono.Math.BigInteger.BigInteger(), Mono.Math.BigInteger.data, int, Mono.Math.BigInteger.length, Mono.Math.BigInteger.Kernel.MinusEq(), Mono.Math.BigInteger.ModulusRing.mod, Mono.Math.BigInteger.Kernel.Multiply(), Mono.Math.BigInteger.Kernel.MultiplyMod2p32pmod(), Mono.Math.BigInteger.Normalize(), Mono.Math.BigInteger.Kernel.PlusEq(), and System.U.
Referenced by Mono.Math.BigInteger.ModulusRing.Difference(), and Mono.Math.BigInteger.ModulusRing.Multiply().