Terraria Decompiled: System.Attribute.IsDefined
IsDefined() [4/8]
static bool System.Attribute.IsDefined (MemberInfo element, Type attributeType, bool inherit) inline static
Definition at line 186 of file Attribute.cs.
        {
            if (element == null)
            {
                throw new ArgumentNullException("element");
            }
            if (attributeType == null)
            {
                throw new ArgumentNullException("attributeType");
            }
            if (!attributeType.IsSubclassOf(typeof(Attribute)) && attributeType != typeof(Attribute))
            {
                throw new ArgumentException(Environment.GetResourceString("Type passed in must be derived from System.Attribute or System.Attribute itself."));
            }
            MemberTypes memberType = element.MemberType;
            if (memberType == MemberTypes.Event)
            {
                return Attribute.InternalIsDefined((EventInfo)element, attributeType, inherit);
            }
            if (memberType == MemberTypes.Property)
            {
                return Attribute.InternalIsDefined((PropertyInfo)element, attributeType, inherit);
            }
            return element.IsDefined(attributeType, inherit);
        }
References System.Environment.GetResourceString(), System.Attribute.InternalIsDefined(), System.Reflection.MemberInfo.IsDefined(), System.Type.IsSubclassOf(), and System.Reflection.MemberInfo.MemberType.