Terraria Decompiled: System.Attribute.IsDefined
IsDefined() [8/8]
static bool System.Attribute.IsDefined (ParameterInfo element, Type attributeType, bool inherit) inline static
Definition at line 296 of file Attribute.cs.
        {
            if (element == null)
            {
                throw new ArgumentNullException("element");
            }
            if (attributeType == null)
            {
                throw new ArgumentNullException("attributeType");
            }
            if (!attributeType.IsSubclassOf(typeof(Attribute)) && attributeType != typeof(Attribute))
            {
                throw new ArgumentException(Environment.GetResourceString("Type passed in must be derived from System.Attribute or System.Attribute itself."));
            }
            MemberTypes memberType = element.Member.MemberType;
            if (memberType == MemberTypes.Constructor)
            {
                return element.IsDefined(attributeType, false);
            }
            if (memberType == MemberTypes.Method)
            {
                return Attribute.InternalParamIsDefined(element, attributeType, inherit);
            }
            if (memberType != MemberTypes.Property)
            {
                throw new ArgumentException(Environment.GetResourceString("Invalid type for ParameterInfo member in Attribute class."));
            }
            return element.IsDefined(attributeType, false);
        }
References System.Environment.GetResourceString(), System.Attribute.InternalParamIsDefined(), System.Reflection.ParameterInfo.IsDefined(), System.Type.IsSubclassOf(), System.Reflection.ParameterInfo.Member, and System.Reflection.MemberInfo.MemberType.