Terraria Decompiled: System.Attribute.GetHashCode
GetHashCode()
override int System.Attribute.GetHashCode () inline
Definition at line 592 of file Attribute.cs.
        {
            Type type = base.GetType();
            FieldInfo[] fields = type.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            object obj = null;
            for (int i = 0; i < fields.Length; i++)
            {
                object obj2 = ((RtFieldInfo)fields[i]).UnsafeGetValue(this);
                if (obj2 != null && !obj2.GetType().IsArray)
                {
                    obj = obj2;
                }
                if (obj != null)
                {
                    break;
                }
            }
            if (obj != null)
            {
                return obj.GetHashCode();
            }
            return type.GetHashCode();
        }
References System.Type.GetFields(), System.Type.GetHashCode(), System.Type.GetType(), and System.obj.