Terraria Decompiled: System.Attribute.Equals
Equals()
override bool System.Attribute.Equals (object obj) inline
Definition at line 528 of file Attribute.cs.
        {
            if (obj == null)
            {
                return false;
            }
            RuntimeType runtimeType = (RuntimeType)base.GetType();
            if ((RuntimeType)obj.GetType() != runtimeType)
            {
                return false;
            }
            FieldInfo[] fields = runtimeType.GetFields(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            for (int i = 0; i < fields.Length; i++)
            {
                object obj2 = ((RtFieldInfo)fields[i]).UnsafeGetValue(this);
                object obj3 = ((RtFieldInfo)fields[i]).UnsafeGetValue(obj);
                if (!Attribute.AreFieldValuesEqual(obj2, obj3))
                {
                    return false;
                }
            }
            return true;
        }
References System.Attribute.AreFieldValuesEqual(), System.RuntimeType.GetFields(), System.RuntimeType.GetType(), and System.obj.
Referenced by System.Attribute.Match().