Terraria Decompiled: System.Attribute.GetCustomAttributes
GetCustomAttributes() [14/16]
static Attribute[] System.Attribute.GetCustomAttributes (ParameterInfo element, bool inherit) inline static
Definition at line 272 of file Attribute.cs.
        {
            if (element == null)
            {
                throw new ArgumentNullException("element");
            }
            if (element.Member == null)
            {
                throw new ArgumentException(Environment.GetResourceString("The ParameterInfo object is not valid."), "element");
            }
            if (element.Member.MemberType == MemberTypes.Method && inherit)
            {
                return Attribute.InternalParamGetCustomAttributes(element, null, inherit);
            }
            return element.GetCustomAttributes(typeof(Attribute), inherit) as Attribute[];
        }
References System.Reflection.ParameterInfo.GetCustomAttributes(), System.Environment.GetResourceString(), System.Attribute.InternalParamGetCustomAttributes(), System.Reflection.ParameterInfo.Member, and System.Reflection.MemberInfo.MemberType.