Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetObjectInfo
GetObjectInfo()
static WriteObjectInfo System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetObjectInfo (SerObjectInfoInit serObjectInfoInit) inline static private
Definition at line 306 of file WriteObjectInfo.cs.
        {
            WriteObjectInfo writeObjectInfo;
            if (!serObjectInfoInit.oiPool.IsEmpty())
            {
                writeObjectInfo = (WriteObjectInfo)serObjectInfoInit.oiPool.Pop();
                writeObjectInfo.InternalInit();
            }
            else
            {
                writeObjectInfo = new WriteObjectInfo();
                WriteObjectInfo writeObjectInfo2 = writeObjectInfo;
                int objectInfoIdCount = serObjectInfoInit.objectInfoIdCount;
                serObjectInfoInit.objectInfoIdCount = objectInfoIdCount + 1;
                writeObjectInfo2.objectInfoId = objectInfoIdCount;
            }
            return writeObjectInfo;
        }
References System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InternalInit(), System.Runtime.Serialization.Formatters.Binary.SerStack.IsEmpty(), System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit.objectInfoIdCount, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit.oiPool, System.Runtime.Serialization.Formatters.Binary.SerStack.Pop(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.serObjectInfoInit, and System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.WriteObjectInfo().
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), and System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize().