Terraria Decompiled: System.Security.Cryptography.TripleDESTransform.TripleDESTransform
TripleDESTransform()
System.Security.Cryptography.TripleDESTransform.TripleDESTransform (TripleDES algo, bool encryption, byte[] key, byte[] iv) inline
Definition at line 10 of file TripleDESTransform.cs.
            : base(algo, encryption, iv)
        {
            if (key == null)
            {
                key = TripleDESTransform.GetStrongKey();
            }
            if (TripleDES.IsWeakKey(key))
            {
                throw new CryptographicException(Locale.GetText("This is a known weak key."));
            }
            byte[] array = new byte[8];
            byte[] array2 = new byte[8];
            byte[] array3 = new byte[8];
            DES des = DES.Create();
            Buffer.BlockCopy(key, 0, array, 0, 8);
            Buffer.BlockCopy(key, 8, array2, 0, 8);
            if (key.Length == 16)
            {
                Buffer.BlockCopy(key, 0, array3, 0, 8);
            }
            else
            {
                Buffer.BlockCopy(key, 16, array3, 0, 8);
            }
            if (encryption || algo.Mode == CipherMode.CFB)
            {
                this.E1 = new DESTransform(des, true, array, iv);
                this.D2 = new DESTransform(des, false, array2, iv);
                this.E3 = new DESTransform(des, true, array3, iv);
                return;
            }
            this.D1 = new DESTransform(des, false, array3, iv);
            this.E2 = new DESTransform(des, true, array2, iv);
            this.D3 = new DESTransform(des, false, array, iv);
        }
References Mono.Security.Cryptography.SymmetricTransform.algo, System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.DES.Create(), System.Security.Cryptography.TripleDESTransform.GetStrongKey(), Locale.GetText(), System.Security.Cryptography.TripleDES.IsWeakKey(), and System.key.