Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom
CheckTypeForwardedFrom()
static void System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom (SerObjectInfoCache cache, Type objectType, string binderAssemblyString) inline static private
Definition at line 203 of file WriteObjectInfo.cs.
        {
            if (cache.hasTypeForwardedFrom && binderAssemblyString == null && !FormatterServices.UnsafeTypeForwardersIsEnabled())
            {
                Assembly assembly = objectType.Assembly;
                if (!SerializationInfo.IsAssemblyNameAssignmentSafe(assembly.FullName, cache.assemblyString) && !assembly.IsFullyTrusted)
                {
                    throw new SecurityException(Environment.GetResourceString("A type '{0}' that is defined in a partially trusted assembly cannot be type forwarded from an assembly with a different Public Key Token or without a public key token. To fix this, please either turn on unsafeTypeForwarding flag in the configuration file or remove the TypeForwardedFrom attribute.", new object[] { objectType }));
                }
            }
        }
References System.Type.Assembly, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.assemblyString, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.binderAssemblyString, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.cache, System.Reflection.Assembly.FullName, System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.hasTypeForwardedFrom, System.Runtime.Serialization.SerializationInfo.IsAssemblyNameAssignmentSafe(), System.Reflection.Assembly.IsFullyTrusted, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, and System.Runtime.Serialization.FormatterServices.UnsafeTypeForwardersIsEnabled().
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(), and System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize().