Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo
InitMemberInfo()
void System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo () inline private
Definition at line 228 of file WriteObjectInfo.cs.
        {
            this.cache = (SerObjectInfoCache)this.serObjectInfoInit.seenBeforeTable[this.objectType];
            if (this.cache == null)
            {
                this.cache = new SerObjectInfoCache(this.objectType);
                this.cache.memberInfos = FormatterServices.GetSerializableMembers(this.objectType, this.context);
                int num = this.cache.memberInfos.Length;
                this.cache.memberNames = new string[num];
                this.cache.memberTypes = new Type[num];
                for (int i = 0; i < num; i++)
                {
                    this.cache.memberNames[i] = this.cache.memberInfos[i].Name;
                    this.cache.memberTypes[i] = this.GetMemberType(this.cache.memberInfos[i]);
                }
                this.serObjectInfoInit.seenBeforeTable.Add(this.objectType, this.cache);
            }
            if (this.obj != null)
            {
                this.memberData = FormatterServices.GetObjectData(this.obj, this.cache.memberInfos);
            }
            this.isTyped = true;
            this.isNamed = true;
        }
References System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.context, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.GetMemberType(), System.Runtime.Serialization.FormatterServices.GetObjectData(), System.Runtime.Serialization.FormatterServices.GetSerializableMembers(), System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberInfos, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberNames, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberTypes, System.Reflection.MemberInfo.Name, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.obj, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoInit.seenBeforeTable, and System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.serObjectInfoInit.
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(), and System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize().