Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize
InitSerialize() [1/2]
void System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize (object obj, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, ObjectWriter objectWriter, SerializationBinder binder) inline package
Definition at line 52 of file WriteObjectInfo.cs.
        {
            this.context = context;
            this.obj = obj;
            this.serObjectInfoInit = serObjectInfoInit;
            if (RemotingServices.IsTransparentProxy(obj))
            {
                this.objectType = Converter.typeofMarshalByRefObject;
            }
            else
            {
                this.objectType = obj.GetType();
            }
            if (this.objectType.IsArray)
            {
                this.isArray = true;
                this.InitNoMembers();
                return;
            }
            this.InvokeSerializationBinder(binder);
            objectWriter.ObjectManager.RegisterObject(obj);
            ISurrogateSelector surrogateSelector2;
            if (surrogateSelector != null && (this.serializationSurrogate = surrogateSelector.GetSurrogate(this.objectType, context, out surrogateSelector2)) != null)
            {
                this.si = new SerializationInfo(this.objectType, converter);
                if (!this.objectType.IsPrimitive)
                {
                    this.serializationSurrogate.GetObjectData(obj, this.si, context);
                }
                this.InitSiWrite();
                return;
            }
            if (!(obj is ISerializable))
            {
                this.InitMemberInfo();
                WriteObjectInfo.CheckTypeForwardedFrom(this.cache, this.objectType, this.binderAssemblyString);
                return;
            }
            if (!this.objectType.IsSerializable)
            {
                throw new SerializationException(Environment.GetResourceString("Type '{0}' in Assembly '{1}' is not marked as serializable.", new object[]
                {
                    this.objectType.FullName,
                    this.objectType.Assembly.FullName
                }));
            }
            this.si = new SerializationInfo(this.objectType, converter, !FormatterServices.UnsafeTypeForwardersIsEnabled());
            ((ISerializable)obj).GetObjectData(this.si, context);
            this.InitSiWrite();
            WriteObjectInfo.CheckTypeForwardedFrom(this.cache, this.objectType, this.binderAssemblyString);
        }
References System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.binderAssemblyString, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.context, System.Runtime.Serialization.ISerializationSurrogate.GetObjectData(), System.Environment.GetResourceString(), System.Runtime.Serialization.ISurrogateSelector.GetSurrogate(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitNoMembers(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSiWrite(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InvokeSerializationBinder(), System.Type.IsArray, System.Type.IsPrimitive, System.Type.IsSerializable, System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.obj, System.Runtime.Serialization.Formatters.Binary.ObjectWriter.ObjectManager, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.SerializationObjectManager.RegisterObject(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.serializationSurrogate, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.si, System.Runtime.Serialization.Formatters.Binary.Converter.typeofMarshalByRefObject, and System.Runtime.Serialization.FormatterServices.UnsafeTypeForwardersIsEnabled().
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize(), and System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.Serialize().