Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize
InitSerialize() [2/2]
void System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize (Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, SerializationBinder binder) inline package
Definition at line 124 of file WriteObjectInfo.cs.
        {
            this.objectType = objectType;
            this.context = context;
            this.serObjectInfoInit = serObjectInfoInit;
            if (objectType.IsArray)
            {
                this.InitNoMembers();
                return;
            }
            this.InvokeSerializationBinder(binder);
            ISurrogateSelector surrogateSelector2 = null;
            if (surrogateSelector != null)
            {
                this.serializationSurrogate = surrogateSelector.GetSurrogate(objectType, context, out surrogateSelector2);
            }
            if (this.serializationSurrogate != null)
            {
                this.si = new SerializationInfo(objectType, converter);
                this.cache = new SerObjectInfoCache(objectType);
                this.isSi = true;
            }
            else if (objectType != Converter.typeofObject && Converter.typeofISerializable.IsAssignableFrom(objectType))
            {
                this.si = new SerializationInfo(objectType, converter, !FormatterServices.UnsafeTypeForwardersIsEnabled());
                this.cache = new SerObjectInfoCache(objectType);
                WriteObjectInfo.CheckTypeForwardedFrom(this.cache, objectType, this.binderAssemblyString);
                this.isSi = true;
            }
            if (!this.isSi)
            {
                this.InitMemberInfo();
                WriteObjectInfo.CheckTypeForwardedFrom(this.cache, objectType, this.binderAssemblyString);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.binderAssemblyString, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.context, System.converter, System.Runtime.Serialization.ISurrogateSelector.GetSurrogate(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitMemberInfo(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitNoMembers(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InvokeSerializationBinder(), System.Type.IsArray, System.Type.IsAssignableFrom(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.serializationSurrogate, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.serObjectInfoInit, System.Runtime.Serialization.Formatters.Binary.Converter.typeofISerializable, System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject, and System.Runtime.Serialization.FormatterServices.UnsafeTypeForwardersIsEnabled().