Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSiWrite
InitSiWrite()
void System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSiWrite () inline private
Definition at line 161 of file WriteObjectInfo.cs.
        {
            this.isSi = true;
            SerializationInfoEnumerator serializationInfoEnumerator = this.si.GetEnumerator();
            int memberCount = this.si.MemberCount;
            TypeInformation typeInformation = null;
            string text = this.si.FullTypeName;
            string text2 = this.si.AssemblyName;
            bool flag = false;
            if (!this.si.IsFullTypeNameSetExplicit)
            {
                typeInformation = BinaryFormatter.GetTypeInformation(this.si.ObjectType);
                text = typeInformation.FullTypeName;
                flag = typeInformation.HasTypeForwardedFrom;
            }
            if (!this.si.IsAssemblyNameSetExplicit)
            {
                if (typeInformation == null)
                {
                    typeInformation = BinaryFormatter.GetTypeInformation(this.si.ObjectType);
                }
                text2 = typeInformation.AssemblyString;
                flag = typeInformation.HasTypeForwardedFrom;
            }
            this.cache = new SerObjectInfoCache(text, text2, flag);
            this.cache.memberNames = new string[memberCount];
            this.cache.memberTypes = new Type[memberCount];
            this.memberData = new object[memberCount];
            serializationInfoEnumerator = this.si.GetEnumerator();
            int num = 0;
            while (serializationInfoEnumerator.MoveNext())
            {
                this.cache.memberNames[num] = serializationInfoEnumerator.Name;
                this.cache.memberTypes[num] = serializationInfoEnumerator.ObjectType;
                this.memberData[num] = serializationInfoEnumerator.Value;
                num++;
            }
            this.isNamed = true;
            this.isTyped = false;
        }
References System.Runtime.Serialization.SerializationInfo.AssemblyName, System.Runtime.Serialization.Formatters.Binary.TypeInformation.AssemblyString, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.TypeInformation.FullTypeName, System.Runtime.Serialization.SerializationInfo.FullTypeName, System.Runtime.Serialization.SerializationInfo.GetEnumerator(), System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.GetTypeInformation(), System.Runtime.Serialization.Formatters.Binary.TypeInformation.HasTypeForwardedFrom, System.Runtime.Serialization.SerializationInfo.IsAssemblyNameSetExplicit, System.Runtime.Serialization.SerializationInfo.IsFullTypeNameSetExplicit, System.Runtime.Serialization.SerializationInfo.MemberCount, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.memberData, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberNames, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberTypes, System.Runtime.Serialization.SerializationInfoEnumerator.MoveNext(), System.Runtime.Serialization.SerializationInfoEnumerator.Name, System.Runtime.Serialization.SerializationInfo.ObjectType, System.Runtime.Serialization.SerializationInfoEnumerator.ObjectType, System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.si, System.text, and System.Runtime.Serialization.SerializationInfoEnumerator.Value.
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize().