Terraria Decompiled: System.NumberFormatter.CustomInfo.Format
Format()
string System.NumberFormatter.CustomInfo.Format (string format, int offset, int length, NumberFormatInfo nfi, bool positive, StringBuilder sb_int, StringBuilder sb_dec, StringBuilder sb_exp) inline
Definition at line 2492 of file NumberFormatter.cs.
            {
                StringBuilder stringBuilder = new StringBuilder();
                char c = '\0';
                bool flag = true;
                bool flag2 = false;
                int num = 0;
                int i = 0;
                int num2 = 0;
                int[] numberGroupSizes = nfi.NumberGroupSizes;
                string numberGroupSeparator = nfi.NumberGroupSeparator;
                int num3 = 0;
                int num4 = 0;
                int num5 = 0;
                int num6 = 0;
                int num7 = 0;
                if (this.UseGroup && numberGroupSizes.Length != 0)
                {
                    num3 = sb_int.Length;
                    for (int j = 0; j < numberGroupSizes.Length; j++)
                    {
                        num4 += numberGroupSizes[j];
                        if (num4 <= num3)
{
                            num5 = j;
                        }
                    }
                    num7 = numberGroupSizes[num5];
                    int num8 = ((num3 > num4) ? (num3 - num4) : 0);
                    if (num7 == 0)
                    {
                        while (num5 >= 0 && numberGroupSizes[num5] == 0)
{
                            num5--;
                        }
                        num7 = ((num8 > 0) ? num8 : numberGroupSizes[num5]);
                    }
                    if (num8 == 0)
                    {
                        num6 = num7;
                    }
                    else
                    {
                        num5 += num8 / num7;
                        num6 = num8 % num7;
                        if (num6 == 0)
{
                            num6 = num7;
                        }
                        else
{
                            num5++;
                        }
                    }
                }
                else
                {
                    this.UseGroup = false;
                }
                int num9 = offset;
                while (num9 - offset < length)
                {
                    char c2 = format[num9];
                    if (c2 == c && c2 != '\0')
                    {
                        c = '\0';
                    }
                    else if (c != '\0')
                    {
                        stringBuilder.Append(c2);
                    }
                    else
                    {
                        if (c2 <= 'E')
{
                            switch (c2)
{
                            case '"':
                            case '\'':
                                if (c2 == '"' || c2 == '\'')
{
                                    c = c2;
                                    goto IL_03CC;
                                }
                                goto IL_03CC;
                            case '#':
                                break;
                            case '$':
                            case '&':
                                goto IL_03C3;
                            case '%':
                                stringBuilder.Append(nfi.PercentSymbol);
                                goto IL_03CC;
                            default:
                                switch (c2)
{
                                case ',':
                                    goto IL_03CC;
                                case '-':
                                case '/':
                                    goto IL_03C3;
                                case '.':
                                    if (this.DecimalPointPos == num9)
{
                                        if (this.DecimalDigits > 0)
{
                                            while (i < sb_int.Length)
{
                                                stringBuilder.Append(sb_int[i++]);
                                            }
                                        }
                                        if (sb_dec.Length > 0)
{
                                            stringBuilder.Append(nfi.NumberDecimalSeparator);
                                        }
                                    }
                                    flag = false;
                                    flag2 = true;
                                    goto IL_03CC;
                                case '0':
                                    break;
                                default:
                                    if (c2 != 'E')
{
                                        goto IL_03C3;
                                    }
                                    goto IL_02A3;
                                }
                                break;
                            }
                            if (flag)
{
                                num++;
                                if (this.IntegerDigits - num >= sb_int.Length + i)
{
                                    if (c2 != '0')
{
                                        goto IL_03CC;
                                    }
                                }
                                while (this.IntegerDigits - num + i < sb_int.Length)
{
                                    stringBuilder.Append(sb_int[i++]);
                                    if (this.UseGroup && --num3 > 0 && --num6 == 0)
{
                                        stringBuilder.Append(numberGroupSeparator);
                                        if (--num5 < numberGroupSizes.Length && num5 >= 0)
{
                                            num7 = numberGroupSizes[num5];
                                        }
                                        num6 = num7;
                                    }
                                }
                                goto IL_03CC;
                            }
                            if (!flag2)
{
                                stringBuilder.Append(c2);
                                goto IL_03CC;
                            }
                            if (num2 < sb_dec.Length)
{
                                stringBuilder.Append(sb_dec[num2++]);
                                goto IL_03CC;
                            }
                            goto IL_03CC;
                        }
                        else if (c2 != '\\')
{
                            if (c2 != 'e')
{
                                if (c2 != '‰')
{
                                    goto IL_03C3;
                                }
                                stringBuilder.Append(nfi.PerMilleSymbol);
                                goto IL_03CC;
                            }
                        }
                        else
{
                            num9++;
                            if (num9 - offset < length)
{
                                stringBuilder.Append(format[num9]);
                                goto IL_03CC;
                            }
                            goto IL_03CC;
                        }
                        IL_02A3:
                        if (sb_exp == null || !this.UseExponent)
{
                            stringBuilder.Append(c2);
                            goto IL_03CC;
                        }
                        bool flag3 = true;
                        bool flag4 = false;
                        int num10 = num9 + 1;
                        while (num10 - offset < length)
{
                            if (format[num10] == '0')
{
                                flag4 = true;
                            }
                            else if (num10 != num9 + 1 || (format[num10] != '+' && format[num10] != '-'))
{
                                if (!flag4)
{
                                    flag3 = false;
                                    break;
                                }
                                break;
                            }
                            num10++;
                        }
                        if (flag3)
{
                            num9 = num10 - 1;
                            flag = this.DecimalPointPos < 0;
                            flag2 = !flag;
                            stringBuilder.Append(c2);
                            stringBuilder.Append(sb_exp);
                            sb_exp = null;
                            goto IL_03CC;
                        }
                        stringBuilder.Append(c2);
                        goto IL_03CC;
                        IL_03C3:
                        stringBuilder.Append(c2);
                    }
                    IL_03CC:
                    num9++;
                }
                if (!positive)
                {
                    stringBuilder.Insert(0, nfi.NegativeSign);
                }
                return stringBuilder.ToString();
            }
References System.Text.StringBuilder.Append(), System.NumberFormatter.CustomInfo.DecimalDigits, System.NumberFormatter.CustomInfo.DecimalPointPos, System.format, System.Text.StringBuilder.Insert(), System.NumberFormatter.CustomInfo.IntegerDigits, System.length, System.Text.StringBuilder.Length, System.Globalization.NumberFormatInfo.NegativeSign, System.Globalization.NumberFormatInfo.NumberDecimalSeparator, System.Globalization.NumberFormatInfo.NumberGroupSeparator, System.Globalization.NumberFormatInfo.NumberGroupSizes, System.offset, System.Globalization.NumberFormatInfo.PercentSymbol, System.Globalization.NumberFormatInfo.PerMilleSymbol, System.Text.StringBuilder.ToString(), System.NumberFormatter.CustomInfo.UseExponent, and System.NumberFormatter.CustomInfo.UseGroup.
Referenced by System.NumberFormatter.FormatCustom().