Terraria Decompiled: Terraria.Graphics.Renderers.OutlinedTextureRenderer.RequestAndTryGet
RequestAndTryGet()
bool Terraria.Graphics.Renderers.OutlinedTextureRenderer.RequestAndTryGet (int textureIndex, out RenderTarget2D renderTarget) inline
Definition at line 54 of file OutlinedTextureRenderer.cs.
        {
            renderTarget = null;
            if (this._contents[textureIndex] == null)
            {
                this._contents[textureIndex] = new OutlinedDrawRenderTargetContent();
                this._contents[textureIndex].SetTexture(this._matchingArray[textureIndex].Value);
            }
            OutlinedDrawRenderTargetContent outlinedDrawRenderTargetContent = this._contents[textureIndex];
            if (!outlinedDrawRenderTargetContent.IsReady)
            {
                outlinedDrawRenderTargetContent.Request();
                return false;
            }
            renderTarget = outlinedDrawRenderTargetContent.GetTarget();
            return true;
        }
References Terraria.Graphics.Renderers.OutlinedTextureRenderer._contents, Terraria.Graphics.Renderers.OutlinedTextureRenderer._matchingArray, Terraria.GameContent.ARenderTargetContentByRequest.GetTarget(), Terraria.GameContent.ARenderTargetContentByRequest.IsReady, Terraria.GameContent.ARenderTargetContentByRequest.Request(), and Terraria.GameContent.OutlinedDrawRenderTargetContent.SetTexture().