Terraria Decompiled: Mono.Math.Prime.Generator.SequentialSearchPrimeGeneratorBase.GenerateNewPrime
GenerateNewPrime() [2/2]
virtual BigInteger Mono.Math.Prime.Generator.SequentialSearchPrimeGeneratorBase.GenerateNewPrime (int bits, object context) inline virtual
Definition at line 23 of file SequentialSearchPrimeGeneratorBase.cs.
        {
            BigInteger bigInteger = this.GenerateSearchBase(bits, context);
            uint num = bigInteger % 3234846615U;
            int trialDivisionBounds = this.TrialDivisionBounds;
            uint[] smallPrimes = BigInteger.smallPrimes;
            for (;;)
            {
                if (num % 3U != 0U && num % 5U != 0U && num % 7U != 0U && num % 11U != 0U && num % 13U != 0U && num % 17U != 0U && num % 19U != 0U && num % 23U != 0U && num % 29U != 0U)
                {
                    int num2 = 10;
                    while (num2 < smallPrimes.Length && (ulong)smallPrimes[num2] <= (ulong)((long)trialDivisionBounds))
                    {
                        if (bigInteger % smallPrimes[num2] == 0U)
{
                            goto IL_009D;
                        }
                        num2++;
                    }
                    if (this.IsPrimeAcceptable(bigInteger, context) && this.PrimalityTest(bigInteger, this.Confidence))
                    {
                        break;
                    }
                }
                IL_009D:
                num += 2U;
                if (num >= 3234846615U)
                {
                    num -= 3234846615U;
                }
                bigInteger.Incr2();
            }
            return bigInteger;
        }
References Mono.Math.Prime.Generator.PrimeGeneratorBase.Confidence, Mono.Math.Prime.Generator.SequentialSearchPrimeGeneratorBase.GenerateSearchBase(), Mono.Math.BigInteger.Incr2(), Mono.Math.Prime.Generator.SequentialSearchPrimeGeneratorBase.IsPrimeAcceptable(), Mono.Math.Prime.Generator.PrimeGeneratorBase.PrimalityTest, Mono.Math.BigInteger.smallPrimes, Mono.Math.Prime.Generator.PrimeGeneratorBase.TrialDivisionBounds, and System.U.