Terraria Decompiled: Terraria.Item.FixAgainstExploit
FixAgainstExploit()
void Terraria.Item.FixAgainstExploit () inline
Definition at line 53941 of file Item.cs.
        {
            if (ItemID.Sets.ItemsThatShouldNotBeInInventory[this.type])
            {
                this.TurnToAir(false);
                return;
            }
            if (this.stack > this.maxStack)
            {
                this.stack = this.maxStack;
            }
            if (this.prefix != 0 && !this.CanRollPrefix((int)this.prefix))
            {
                this.ResetPrefix();
            }
        }
References Terraria.Item.CanRollPrefix(), Terraria.ID.ItemID.Sets.ItemsThatShouldNotBeInInventory, Terraria.Item.maxStack, Terraria.Item.prefix, Terraria.Item.ResetPrefix(), Terraria.Item.stack, and Terraria.Item.TurnToAir().
Referenced by Terraria.Chest.FixLoadedData(), Terraria.EquipmentLoadout.FixLoadedData(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.FixLoadedData(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.FixLoadedData(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.FixLoadedData(), Terraria.GameContent.Tile_Entities.TEHatRack.FixLoadedData(), Terraria.GameContent.Tile_Entities.TEItemFrame.FixLoadedData(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.FixLoadedData(), and Terraria.Player.FixLoadedData_Items().