Terraria Decompiled: Terraria.Item.AffixName
AffixName()
string Terraria.Item.AffixName () inline
Definition at line 935 of file Item.cs.
        {
            if (this.prefix <= 0 || (int)this.prefix >= Lang.prefix.Length)
            {
                return this.Name;
            }
            return Lang.GetPrefixedItemName(this.type, (int)this.prefix);
        }
References Terraria.Lang.GetPrefixedItemName(), Terraria.Item.Name, Terraria.Item.prefix, Terraria.Lang.prefix, and Terraria.Item.type.
Referenced by Terraria.WorldItem.AffixName(), Terraria.Main.GUIHotbarDrawInner(), and Terraria.PopupText.NewText().