Terraria Decompiled: Terraria.Item.SetFoodDefaults
SetFoodDefaults()
void Terraria.Item.SetFoodDefaults (int type) inline private
Definition at line 52152 of file Item.cs.
        {
            if (type <= 3532)
            {
                if (type <= 1911)
                {
                    if (type <= 967)
                    {
                        if (type != 353)
{
                            if (type != 357)
{
                                if (type == 967)
{
                                    this.DefaultToFood(12, 12, 26, 3600, false, 17);
                                    this.SetShopValues(ItemRarityColor.White0, Item.buyPrice(0, 0, 1, 0));
                                    this.useStyle = 9;
                                }
                            }
                            else
{
                                this.DefaultToFood(22, 22, 206, 28800, true, 17);
                                this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            }
                        }
                        else
{
                            this.DefaultToFood(22, 22, 25, 7200, true, 17);
                            this.SetShopValues(ItemRarityColor.White0, 100);
                            this.holdStyle = 1;
                            this.ammo = 353;
                            this.notAmmo = true;
                        }
                    }
                    else if (type != 969)
                    {
                        if (type != 1787)
{
                            if (type == 1911)
{
                                this.DefaultToFood(22, 22, 207, 14400, true, 17);
                                this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 10, 0));
                            }
                        }
                        else
{
                            this.DefaultToFood(22, 22, 26, 28800, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 10, 0));
                        }
                    }
                    else
                    {
                        this.DefaultToFood(12, 12, 26, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 2, 0));
                        this.useStyle = 9;
                    }
                }
                else if (type <= 1920)
                {
                    if (type != 1912)
                    {
                        if (type != 1919)
{
                            if (type == 1920)
{
                                this.DefaultToFood(22, 22, 207, 14400, false, 17);
                                this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 25, 0));
                            }
                        }
                        else
{
                            this.DefaultToFood(22, 22, 207, 14400, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 25, 0));
                        }
                    }
                    else
                    {
                        this.DefaultToHealingPotion(22, 22, 80, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, 40);
                    }
                }
                else if (type <= 2427)
                {
                    switch (type)
                    {
                    case 2266:
                        this.DefaultToFood(22, 22, 25, 14400, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 5, 0));
                        break;
                    case 2267:
                        this.DefaultToFood(22, 22, 206, 28800, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 55, 0));
                        break;
                    case 2268:
                        this.DefaultToFood(22, 22, 206, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 75, 0));
                        break;
                    default:
                        switch (type)
{
                        case 2425:
                            this.DefaultToFood(22, 22, 26, 28800, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 25, 0));
                            break;
                        case 2426:
                            this.DefaultToFood(22, 22, 206, 36000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 75, 0));
                            break;
                        case 2427:
                            this.DefaultToFood(22, 22, 206, 28800, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 25, 0));
                            break;
                        }
                        break;
                    }
                }
                else if (type != 3195)
                {
                    if (type == 3532)
                    {
                        this.DefaultToFood(22, 22, 207, 86400, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 5, 0, 0));
                    }
                }
                else
                {
                    this.DefaultToFood(22, 22, 206, 50400, true, 17);
                    this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                }
            }
            else if (type <= 5009)
            {
                if (type <= 4403)
                {
                    switch (type)
                    {
                    case 4009:
                        this.DefaultToFood(22, 22, 26, 18000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4010:
                        break;
                    case 4011:
                        this.DefaultToFood(22, 22, 207, 57600, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 3, 0, 0));
                        break;
                    case 4012:
                        this.DefaultToFood(22, 22, 206, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4013:
                        this.DefaultToFood(22, 22, 207, 86400, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 5, 0, 0));
                        break;
                    case 4014:
                        this.DefaultToFood(22, 22, 26, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4015:
                        this.DefaultToFood(22, 22, 207, 28800, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4016:
                        this.DefaultToFood(22, 22, 206, 50400, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4017:
                        this.DefaultToFood(22, 22, 206, 72000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 3, 0, 0));
                        break;
                    case 4018:
                        this.DefaultToFood(22, 22, 206, 57600, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4019:
                        this.DefaultToFood(22, 22, 206, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4020:
                        this.DefaultToFood(22, 22, 206, 50400, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4021:
                        this.DefaultToFood(22, 22, 206, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4022:
                        this.DefaultToFood(22, 22, 207, 172800, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 50, 0, 0));
                        break;
                    case 4023:
                        this.DefaultToFood(22, 22, 206, 57600, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4024:
                        this.DefaultToFood(22, 22, 26, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4025:
                        this.DefaultToFood(22, 22, 207, 43200, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 3, 0, 0));
                        break;
                    case 4026:
                        this.DefaultToFood(22, 22, 206, 50400, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4027:
                        this.DefaultToFood(22, 22, 207, 57600, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 3, 0, 0));
                        break;
                    case 4028:
                        this.DefaultToFood(22, 22, 206, 57600, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4029:
                        this.DefaultToFood(22, 22, 207, 28800, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4030:
                        this.DefaultToFood(22, 22, 26, 90000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 50, 0));
                        break;
                    case 4031:
                        this.DefaultToFood(22, 22, 26, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4032:
                        this.DefaultToFood(22, 22, 206, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4033:
                        this.DefaultToFood(22, 22, 26, 36000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 50, 0));
                        break;
                    case 4034:
                        this.DefaultToFood(22, 22, 206, 50400, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 50, 0));
                        break;
                    case 4035:
                        this.DefaultToFood(22, 22, 206, 64800, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 50, 0));
                        break;
                    case 4036:
                        this.DefaultToFood(22, 22, 207, 28800, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4037:
                        this.DefaultToFood(22, 22, 207, 57600, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 3, 0, 0));
                        break;
                    default:
                        switch (type)
{
                        case 4282:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4283:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4284:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4285:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4286:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4287:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4288:
                            this.DefaultToFood(22, 22, 206, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4289:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4290:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4291:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4292:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4293:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4294:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4295:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4296:
                            this.DefaultToFood(22, 22, 26, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        case 4297:
                            this.DefaultToFood(22, 22, 206, 18000, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            break;
                        default:
                            if (type == 4403)
{
                                this.DefaultToFood(22, 22, 206, 36000, false, 17);
                                this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                            }
                            break;
                        }
                        break;
                    }
                }
                else if (type != 4411)
                {
                    switch (type)
                    {
                    case 4614:
                        this.DefaultToFood(22, 22, 26, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4615:
                        this.DefaultToFood(22, 22, 207, 57600, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 4, 0, 0));
                        break;
                    case 4616:
                        this.DefaultToFood(22, 22, 26, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4617:
                        this.DefaultToFood(22, 22, 26, 54000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4618:
                        this.DefaultToFood(22, 22, 26, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 4619:
                        this.DefaultToFood(22, 22, 26, 72000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4620:
                        this.DefaultToFood(22, 22, 26, 72000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4621:
                        this.DefaultToFood(22, 22, 26, 72000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4622:
                        this.DefaultToFood(22, 22, 26, 72000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4623:
                        this.DefaultToFood(22, 22, 206, 72000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4624:
                        this.DefaultToFood(22, 22, 26, 54000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 2, 0, 0));
                        break;
                    case 4625:
                        this.DefaultToFood(22, 22, 26, 90000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 3, 0, 0));
                        break;
                    default:
                        if (type == 5009)
{
                            this.DefaultToFood(22, 22, 26, 18000, true, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 0, 20));
                        }
                        break;
                    }
                }
                else
                {
                    this.DefaultToFood(22, 22, 26, 36000, false, 17);
                    this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                }
            }
            else if (type <= 5092)
            {
                if (type != 5041)
                {
                    if (type != 5042)
                    {
                        if (type == 5092)
{
                            this.DefaultToFood(22, 22, 206, 28800, false, 17);
                            this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 50, 0));
                        }
                    }
                    else
                    {
                        this.DefaultToFood(22, 22, 206, 36000, true, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                    }
                }
                else
                {
                    this.DefaultToFood(22, 22, 26, 72000, true, 17);
                    this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                }
            }
            else if (type <= 5278)
            {
                if (type != 5093)
                {
                    switch (type)
                    {
                    case 5275:
                        this.DefaultToFood(22, 22, 26, 7200, true, 17);
                        this.SetShopValues(ItemRarityColor.White0, Item.buyPrice(0, 0, 1, 25));
                        break;
                    case 5277:
                        this.DefaultToFood(22, 22, 26, 18000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    case 5278:
                        this.DefaultToFood(22, 22, 26, 18000, false, 17);
                        this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                        break;
                    }
                }
                else
                {
                    this.DefaultToFood(22, 22, 206, 21600, false, 17);
                    this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                }
            }
            else if (type != 5537)
            {
                if (type == 5645)
                {
                    this.DefaultToFood(22, 22, 26, 36000, true, 17);
                    this.UseSound = SoundID.Item2;
                    this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 1, 0, 0));
                }
            }
            else
            {
                this.DefaultToFood(22, 22, 26, 18000, false, 17);
                this.SetShopValues(ItemRarityColor.Blue1, Item.buyPrice(0, 0, 15, 0));
            }
            float num = 0f;
            if (this.buffType == 207)
            {
                num += 12f;
            }
            else if (this.buffType == 206)
            {
                num += 8f;
            }
            else
            {
                num += 3f;
            }
            num += (float)(this.buffTime / 14400);
            this.rare = (int)(num / 4f);
        }
References Terraria.Item.buffTime, Terraria.Item.buffType, Terraria.Item.buyPrice(), Terraria.Item.DefaultToFood(), Terraria.Item.DefaultToHealingPotion(), int, Terraria.ID.SoundID.Item2, Terraria.Item.SetShopValues(), and Terraria.Item.type.
Referenced by Terraria.Item.SetDefaults().