Terraria Decompiled: Terraria.Item.DefaultToSeaShell
DefaultToSeaShell()
void Terraria.Item.DefaultToSeaShell () inline private
Definition at line 52070 of file Item.cs.
        {
            this.useStyle = 1;
            this.autoReuse = true;
            this.useAnimation = 15;
            this.useTime = 10;
            this.consumable = true;
            this.createTile = 324;
            this.width = 22;
            this.height = 22;
            int num = this.type;
            if (num == 2626)
            {
                this.placeStyle = 3;
                this.value = Item.sellPrice(0, 0, 10, 0);
                return;
            }
            switch (num)
            {
            case 4071:
                this.placeStyle = 12;
                this.value = Item.sellPrice(0, 1, 0, 0);
                return;
            case 4072:
                this.placeStyle = 6;
                this.value = Item.sellPrice(0, 0, 20, 0);
                return;
            case 4073:
                this.placeStyle = 9;
                this.value = Item.sellPrice(0, 0, 20, 0);
                return;
            default:
                this.value = Item.sellPrice(0, 0, 5, 0);
                return;
            }
        }
References Terraria.Item.sellPrice(), and Terraria.Item.type.
Referenced by Terraria.Item.SetDefaults3(), and Terraria.Item.SetDefaults5().