Terraria Decompiled: Terraria.Item.NewItem
NewItem() [3/3]
static int Terraria.Item.NewItem (IEntitySource source, Vector2 pos, Vector2 randomBox, int Type, int Stack = 1, bool noBroadcast = false, int prefixGiven = 0, bool noGrabDelay = false) inline static
Definition at line 54197 of file Item.cs.
        {
            return Item.NewItem(source, (int)pos.X, (int)pos.Y, (int)randomBox.X, (int)randomBox.Y, Type, Stack, noBroadcast, prefixGiven, noGrabDelay);
        }
References Terraria.Item.NewItem(), System.source, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Projectile.AI(), Terraria.NPC.AI_127_Pal_GiveRewerd(), Terraria.Projectile.AI_192_JuminoAnimation(), Terraria.NPC.AI_87_BigMimic_ShootItem(), Terraria.Player.ApplyNPCOnHitEffects(), Terraria.NPC.CatchNPC(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check4x4(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckStalactiteEcho(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTrapDoor(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.Projectile.Damage_PVE_Inner(), Terraria.NPC.DoDeathEvents(), Terraria.NPC.DoDeathEvents_DropBossPotionsAndHearts(), Terraria.Item.DropCache(), Terraria.WorldGen.DropDoorItem(), Terraria.Projectile.DropGeodeGems(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.DropItem(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.DropItem(), Terraria.GameContent.Tile_Entities.TEItemFrame.DropItem(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemForEachInteractingPlayerOnThePlayer(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchorWithItem.DropItemForTileBreak(), Terraria.Player.DropItemFromExtractinator(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemFromNPC(), Terraria.NPC.DropItemInstanced(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Terraria.Player.DropSelectedItem(), Terraria.GameContent.Events.DD2Event.DropStarterCrystals(), Terraria.WorldGen.dropXmasTree(), Terraria.Wiring.Extractinator(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.MessageBuffer.GetData(), Terraria.Player.GetOrDropItem(), Terraria.NPC.GetShimmered(), Terraria.WorldItem.GetShimmered(), Terraria.Wiring.HitWireSingle(), Terraria.Player.ItemCheck_CutTiles(), Terraria.WorldGen.KillActuator(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.KillWall_DropItems(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.Item.NewItem(), Terraria.Item.NewItem(), Terraria.Main.NPCChatText_DoTaxCollector(), Terraria.NPC.NPCLoot_DropAltar(), Terraria.NPC.NPCLoot_DropCommonLifeAndMana(), Terraria.NPC.NPCLoot_DropDungeonStuff(), Terraria.NPC.NPCLoot_DropHeals(), Terraria.NPC.NPCLoot_DropHellforge(), Terraria.NPC.NPCLoot_DropLihzahrdStuff(), Terraria.NPC.NPCLoot_DropMoney(), Terraria.NPC.NPCLoot_DropTempleTraps(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.ProcessHitAgainstNPC(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.WorldItem.SpawnShimmeredItem(), Terraria.WorldGen.SpawnThingsFromPot(), Terraria.WorldGen.ToggleGemLock(), Terraria.Player.TorchAttack(), Terraria.Player.TryDroppingSingleItem(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.TryPlacing(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), and Terraria.Projectile.UseGasTrapInChest().