Terraria Decompiled: Terraria.Item.GetRollablePrefixes
GetRollablePrefixes()
int[] Terraria.Item.GetRollablePrefixes () inline
Definition at line 861 of file Item.cs.
        {
            int num = this.type;
            if (PrefixLegacy.ItemSets.SwordsHammersAxesPicks[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForSwords;
            }
            if (PrefixLegacy.ItemSets.SpearsMacesChainsawsDrillsPunchCannon[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForSpears;
            }
            if (PrefixLegacy.ItemSets.GunsBows[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForGunsBows;
            }
            if (PrefixLegacy.ItemSets.Magic[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForMagic;
            }
            if (PrefixLegacy.ItemSets.Summon[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForSummons;
            }
            if (PrefixLegacy.ItemSets.BoomerangsChakrams[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums;
            }
            if (PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2[this.type])
            {
                return PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums_TerrarianYoyo;
            }
            if (this.IsAPrefixableAccessory())
            {
                return PrefixLegacy.Prefixes.PrefixesForAccessories;
            }
            return null;
        }
References Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.BoomerangsChakrams, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.GunsBows, Terraria.Item.IsAPrefixableAccessory(), Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.ItemsThatCanHaveLegendary2, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.Magic, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForAccessories, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForBoomeransAndChakrums_TerrarianYoyo, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForGunsBows, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForMagic, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForSpears, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForSummons, Terraria.GameContent.Prefixes.PrefixLegacy.Prefixes.PrefixesForSwords, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.SpearsMacesChainsawsDrillsPunchCannon, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.Summon, Terraria.GameContent.Prefixes.PrefixLegacy.ItemSets.SwordsHammersAxesPicks, and Terraria.Item.type.
Referenced by Terraria.Item.BestPrefixValue(), Terraria.Item.CanHavePrefixes(), Terraria.Item.CanRollPrefix(), Terraria.GameContent.CraftingEffects.GetEffectDetails(), and Terraria.Item.RollAPrefix().