Terraria Decompiled: Terraria.Item.Prefix
Prefix() [2/2]
bool Terraria.Item.Prefix (int prefixWeWant, out bool rolledPrefixIsTopTier) inline
Definition at line 189 of file Item.cs.
        {
            if (!WorldGen.isGeneratingOrLoadingWorld && Main.rand == null)
            {
                Main.rand = new UnifiedRandom();
            }
            rolledPrefixIsTopTier = false;
            if (prefixWeWant == 0)
            {
                return false;
            }
            if (!this.CanHavePrefixes())
            {
                return false;
            }
            if (prefixWeWant == -3)
            {
                return true;
            }
            float num = 0f;
            if (prefixWeWant == -2 || prefixWeWant == -1)
            {
                num = this.BestPrefixValue();
            }
            UnifiedRandom unifiedRandom = (WorldGen.isGeneratingOrLoadingWorld ? WorldGen.genRand : Main.rand);
            int num2 = prefixWeWant;
            float num3 = 1f;
            float num4 = 1f;
            float num5 = 1f;
            float num6 = 1f;
            float num7 = 1f;
            float num8 = 1f;
            int num9 = 0;
            int num10 = 0;
            int num11 = 0;
            float num12 = 0f;
            bool flag = true;
            while (flag)
            {
                flag = false;
                if (num2 == -1 && unifiedRandom.Next(4) == 0)
                {
                    num2 = 0;
                }
                if (prefixWeWant < -1)
                {
                    num2 = -1;
                }
                if ((num2 == -1 || num2 == -2 || num2 == -3) && !this.RollAPrefix(unifiedRandom, ref num2))
                {
                    return false;
                }
                if (prefixWeWant == -1 && PrefixID.Sets.ReducedNaturalChance[num2] && unifiedRandom.Next(3) != 0)
                {
                    num2 = 0;
                }
                if (prefixWeWant == -4)
                {
                    num2 = 0;
                }
                if (!this.TryGetPrefixStatMultipliersForItem(num2, out num3, out num4, out num5, out num6, out num7, out num8, out num9, out num10, out num11, out num12))
                {
                    flag = true;
                    num2 = -1;
                }
                if (prefixWeWant == -2 && num2 == 0)
                {
                    num2 = -1;
                    flag = true;
                }
            }
            rolledPrefixIsTopTier = num12 == num;
            this.damage = (int)Math.Round((double)((float)this.damage * num3));
            this.useAnimation = (int)Math.Round((double)((float)this.useAnimation * num5));
            this.useTime = (int)Math.Round((double)((float)this.useTime * num5));
            this.reuseDelay = (int)Math.Round((double)((float)this.reuseDelay * num5));
            this.mana = (int)Math.Round((double)((float)this.mana * num8));
            this.knockBack *= num4;
            this.scale *= num6;
            this.shootSpeed *= num7;
            this.crit += num9;
            this.bonusTagDamage += num10;
            this.armorPenetration += num11;
            if ((double)num12 >= 1.2)
            {
                this.rare += 2;
            }
            else if ((double)num12 >= 1.05)
            {
                this.rare++;
            }
            else if ((double)num12 <= 0.8)
            {
                this.rare -= 2;
            }
            else if ((double)num12 <= 0.95)
            {
                this.rare--;
            }
            if (this.rare > -11)
            {
                if (this.rare < -1)
                {
                    this.rare = -1;
                }
                if (this.rare > 11)
                {
                    this.rare = 11;
                }
            }
            num12 *= num12;
            this.value = (int)((float)this.value * num12);
            this.prefix = (byte)num2;
            return true;
        }
References Terraria.Item.BestPrefixValue(), Terraria.Item.CanHavePrefixes(), Terraria.Item.damage, int, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Item.mana, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Terraria.Item.rare, Terraria.ID.PrefixID.Sets.ReducedNaturalChance, Terraria.Item.reuseDelay, Terraria.Item.RollAPrefix(), System.Math.Round(), Terraria.Item.TryGetPrefixStatMultipliersForItem(), Terraria.Item.useAnimation, and Terraria.Item.useTime.