Terraria Decompiled: Terraria.Item.TryGetPrefixStatMultipliersForItem
TryGetPrefixStatMultipliersForItem()
bool Terraria.Item.TryGetPrefixStatMultipliersForItem (int rolledPrefix, out float dmg, out float kb, out float spd, out float size, out float shtspd, out float mcst, out int crt, out int tagdmg, out int arpen, out float value) inline
Definition at line 399 of file Item.cs.
        {
            dmg = 1f;
            kb = 1f;
            spd = 1f;
            size = 1f;
            shtspd = 1f;
            mcst = 1f;
            crt = 0;
            tagdmg = 0;
            arpen = 0;
            if (rolledPrefix == 1)
            {
                size = 1.12f;
            }
            else if (rolledPrefix == 2)
            {
                size = 1.18f;
            }
            else if (rolledPrefix == 3)
            {
                dmg = 1.05f;
                crt = 2;
                size = 1.05f;
            }
            else if (rolledPrefix == 4)
            {
                dmg = 1.1f;
                size = 1.1f;
                kb = 1.1f;
            }
            else if (rolledPrefix == 5)
            {
                dmg = 1.15f;
            }
            else if (rolledPrefix == 6)
            {
                dmg = 1.1f;
            }
            else if (rolledPrefix == 81)
            {
                kb = 1.15f;
                dmg = 1.15f;
                crt = 5;
                spd = 0.9f;
                size = 1.1f;
            }
            else if (rolledPrefix == 7)
            {
                size = 0.82f;
            }
            else if (rolledPrefix == 8)
            {
                kb = 0.85f;
                dmg = 0.85f;
                size = 0.87f;
            }
            else if (rolledPrefix == 9)
            {
                size = 0.9f;
            }
            else if (rolledPrefix == 10)
            {
                dmg = 0.85f;
            }
            else if (rolledPrefix == 11)
            {
                spd = 1.1f;
                kb = 0.9f;
                size = 0.9f;
            }
            else if (rolledPrefix == 12)
            {
                kb = 1.1f;
                dmg = 1.05f;
                size = 1.1f;
                spd = 1.15f;
            }
            else if (rolledPrefix == 13)
            {
                kb = 0.8f;
                dmg = 0.9f;
                size = 1.1f;
            }
            else if (rolledPrefix == 14)
            {
                kb = 1.15f;
                spd = 1.1f;
            }
            else if (rolledPrefix == 15)
            {
                kb = 0.9f;
                spd = 0.85f;
            }
            else if (rolledPrefix == 16)
            {
                dmg = 1.1f;
                crt = 3;
            }
            else if (rolledPrefix == 17)
            {
                spd = 0.85f;
                shtspd = 1.1f;
            }
            else if (rolledPrefix == 18)
            {
                spd = 0.9f;
                shtspd = 1.15f;
            }
            else if (rolledPrefix == 19)
            {
                kb = 1.15f;
                shtspd = 1.05f;
            }
            else if (rolledPrefix == 20)
            {
                kb = 1.05f;
                shtspd = 1.05f;
                dmg = 1.1f;
                spd = 0.95f;
                crt = 2;
            }
            else if (rolledPrefix == 21)
            {
                kb = 1.15f;
                dmg = 1.1f;
            }
            else if (rolledPrefix == 82)
            {
                kb = 1.15f;
                dmg = 1.15f;
                crt = 5;
                spd = 0.9f;
                shtspd = 1.1f;
            }
            else if (rolledPrefix == 22)
            {
                kb = 0.9f;
                shtspd = 0.9f;
                dmg = 0.85f;
            }
            else if (rolledPrefix == 23)
            {
                spd = 1.15f;
                shtspd = 0.9f;
            }
            else if (rolledPrefix == 24)
            {
                spd = 1.1f;
                kb = 0.8f;
            }
            else if (rolledPrefix == 25)
            {
                spd = 1.1f;
                dmg = 1.15f;
                crt = 1;
            }
            else if (rolledPrefix == 58)
            {
                spd = 0.85f;
                dmg = 0.85f;
            }
            else if (rolledPrefix == 26)
            {
                mcst = 0.85f;
                dmg = 1.1f;
            }
            else if (rolledPrefix == 27)
            {
                mcst = 0.85f;
            }
            else if (rolledPrefix == 28)
            {
                mcst = 0.85f;
                dmg = 1.15f;
                kb = 1.05f;
            }
            else if (rolledPrefix == 83)
            {
                kb = 1.15f;
                dmg = 1.15f;
                crt = 5;
                spd = 0.9f;
                mcst = 0.9f;
            }
            else if (rolledPrefix == 29)
            {
                mcst = 1.1f;
            }
            else if (rolledPrefix == 30)
            {
                mcst = 1.2f;
                dmg = 0.9f;
            }
            else if (rolledPrefix == 31)
            {
                kb = 0.9f;
                dmg = 0.9f;
            }
            else if (rolledPrefix == 32)
            {
                mcst = 1.15f;
                dmg = 1.1f;
            }
            else if (rolledPrefix == 33)
            {
                mcst = 1.1f;
                kb = 1.1f;
                spd = 0.9f;
            }
            else if (rolledPrefix == 34)
            {
                mcst = 0.9f;
                kb = 1.1f;
                spd = 1.1f;
                dmg = 1.1f;
            }
            else if (rolledPrefix == 35)
            {
                mcst = 1.2f;
                dmg = 1.15f;
                kb = 1.15f;
            }
            else if (rolledPrefix == 52)
            {
                mcst = 0.9f;
                dmg = 0.9f;
                spd = 0.9f;
            }
            else if (rolledPrefix == 85)
            {
                dmg = 1.15f;
                kb = 1.15f;
                arpen = 10;
                tagdmg = 3;
            }
            else if (rolledPrefix == 86)
            {
                dmg = 1.1f;
                kb = 1.05f;
                arpen = 5;
                tagdmg = 3;
            }
            else if (rolledPrefix == 87)
            {
                dmg = 1.15f;
                arpen = 8;
            }
            else if (rolledPrefix == 88)
            {
                dmg = 1.1f;
                tagdmg = 3;
            }
            else if (rolledPrefix == 89)
            {
                dmg = 0.95f;
                tagdmg = 3;
            }
            else if (rolledPrefix == 90)
            {
                dmg = 1.1f;
                kb = 0.9f;
            }
            else if (rolledPrefix == 91)
            {
                dmg = 0.95f;
                arpen = 10;
            }
            else if (rolledPrefix == 92)
            {
                dmg = 0.7f;
            }
            else if (rolledPrefix == 93)
            {
                kb = 0.75f;
            }
            else if (rolledPrefix == 94)
            {
                dmg = 0.85f;
                kb = 0.9f;
            }
            else if (rolledPrefix == 95)
            {
                arpen = 25;
            }
            else if (rolledPrefix == 96)
            {
                tagdmg = 5;
            }
            else if (rolledPrefix == 97)
            {
                kb = 1.25f;
            }
            else if (rolledPrefix == 84)
            {
                kb = 1.17f;
                dmg = 1.17f;
                crt = 8;
            }
            else if (rolledPrefix == 36)
            {
                crt = 3;
            }
            else if (rolledPrefix == 37)
            {
                dmg = 1.1f;
                crt = 3;
                kb = 1.1f;
            }
            else if (rolledPrefix == 38)
            {
                kb = 1.15f;
            }
            else if (rolledPrefix == 53)
            {
                dmg = 1.1f;
            }
            else if (rolledPrefix == 54)
            {
                kb = 1.15f;
            }
            else if (rolledPrefix == 55)
            {
                kb = 1.15f;
                dmg = 1.05f;
            }
            else if (rolledPrefix == 59)
            {
                kb = 1.15f;
                dmg = 1.15f;
                crt = 5;
            }
            else if (rolledPrefix == 60)
            {
                dmg = 1.15f;
                crt = 5;
            }
            else if (rolledPrefix == 61)
            {
                crt = 5;
            }
            else if (rolledPrefix == 39)
            {
                dmg = 0.7f;
                kb = 0.8f;
            }
            else if (rolledPrefix == 40)
            {
                dmg = 0.85f;
            }
            else if (rolledPrefix == 56)
            {
                kb = 0.8f;
            }
            else if (rolledPrefix == 41)
            {
                kb = 0.85f;
                dmg = 0.9f;
            }
            else if (rolledPrefix == 57)
            {
                kb = 0.9f;
                dmg = 1.18f;
            }
            else if (rolledPrefix == 42)
            {
                spd = 0.9f;
            }
            else if (rolledPrefix == 43)
            {
                dmg = 1.1f;
                spd = 0.9f;
            }
            else if (rolledPrefix == 44)
            {
                spd = 0.9f;
                crt = 3;
            }
            else if (rolledPrefix == 45)
            {
                spd = 0.95f;
            }
            else if (rolledPrefix == 46)
            {
                crt = 3;
                spd = 0.94f;
                dmg = 1.07f;
            }
            else if (rolledPrefix == 47)
            {
                spd = 1.15f;
            }
            else if (rolledPrefix == 48)
            {
                spd = 1.2f;
            }
            else if (rolledPrefix == 49)
            {
                spd = 1.08f;
            }
            else if (rolledPrefix == 50)
            {
                dmg = 0.8f;
                spd = 1.15f;
            }
            else if (rolledPrefix == 51)
            {
                kb = 0.9f;
                spd = 0.9f;
                dmg = 1.05f;
                crt = 2;
            }
            value = 1f * dmg * (2f - spd) * (2f - mcst) * size * kb * shtspd * (1f + (float)crt * 0.02f) * (1f + (float)arpen * 0.015f) * (1f + (float)tagdmg * 0.03f);
            if (rolledPrefix == 62 || rolledPrefix == 69 || rolledPrefix == 73 || rolledPrefix == 77)
            {
                value *= 1.05f;
            }
            if (rolledPrefix == 63 || rolledPrefix == 70 || rolledPrefix == 74 || rolledPrefix == 78 || rolledPrefix == 67)
            {
                value *= 1.1f;
            }
            if (rolledPrefix == 64 || rolledPrefix == 71 || rolledPrefix == 75 || rolledPrefix == 79 || rolledPrefix == 66)
            {
                value *= 1.15f;
            }
            if (rolledPrefix == 65 || rolledPrefix == 72 || rolledPrefix == 76 || rolledPrefix == 80 || rolledPrefix == 68)
            {
                value *= 1.2f;
            }
            return (dmg == 1f || Math.Round((double)((float)this.damage * dmg)) != (double)this.damage) && (spd == 1f || Math.Round((double)((float)this.useAnimation * spd)) != (double)this.useAnimation) && (mcst == 1f || Math.Round((double)((float)this.mana * mcst)) != (double)this.mana) && (kb == 1f || this.knockBack != 0f);
        }
References Terraria.Item.damage, Terraria.Item.knockBack, Terraria.Item.mana, System.Math.Round(), Terraria.Item.useAnimation, and Terraria.Item.value.
Referenced by Terraria.Item.BestPrefixValue(), and Terraria.Item.Prefix().