Terraria Decompiled: Terraria.Item.GetPhaseColor
GetPhaseColor()
static Color Terraria.Item.GetPhaseColor (int projectileType, bool drawColor = false) inline static
Definition at line 53298 of file Item.cs.
        {
            if (Item._phaseColors == null)
            {
                Item._phaseColors = new Color[]
                {
                    Item.GetPhaseColorDirect(1059),
                    Item.GetPhaseColorDirect(1060),
                    Item.GetPhaseColorDirect(1061),
                    Item.GetPhaseColorDirect(1062),
                    Item.GetPhaseColorDirect(1063),
                    Item.GetPhaseColorDirect(1064),
                    Item.GetPhaseColorDirect(1071),
                    Item.GetPhaseColorDirect(1075),
                    Item.GetPhaseColorDirect(1059)
                };
            }
            switch (projectileType)
            {
            case 1059:
            case 1065:
                return Item._phaseColors[0];
            case 1060:
            case 1066:
                return Item._phaseColors[1];
            case 1061:
            case 1067:
                return Item._phaseColors[2];
            case 1062:
            case 1068:
                return Item._phaseColors[3];
            case 1063:
            case 1069:
                return Item._phaseColors[4];
            case 1064:
            case 1070:
                return Item._phaseColors[5];
            case 1071:
            case 1072:
                return Item._phaseColors[6];
            case 1073:
            case 1074:
                break;
            case 1075:
            case 1076:
                return Item._phaseColors[7];
            default:
                if (projectileType - 1101 <= 1)
                {
                    Color color = Utils.MultiLerp(Main.LocalPlayer.miscCounterNormalized, Item._phaseColors);
                    if (drawColor)
                    {
                        float num = 0.5f;
                        color.A = (byte)(255f * num);
                    }
                    return color;
                }
                break;
            }
            return Color.White;
        }
References Terraria.Item._phaseColors, Terraria.Item.color, Terraria.Item.GetPhaseColorDirect(), Terraria.Main.LocalPlayer, Terraria.Player.miscCounterNormalized, Terraria.Utils.MultiLerp(), and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Projectile.AI_003_Boomerang(), Terraria.Main.DrawItem(), Terraria.UI.ItemSlot.DrawItemIcon(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.Main.DrawProjDirect(), Terraria.Projectile.HandleMovement(), and Terraria.Player.ItemCheck_EmitUseVisuals().