Terraria Decompiled: Terraria.Item.GetAlpha
GetAlpha()
Color Terraria.Item.GetAlpha (Color newColor) inline
Definition at line 53429 of file Item.cs.
        {
            if (ItemID.Sets.BossBag[this.type])
            {
                return Color.Lerp(newColor, Color.White, 0.4f);
            }
            int num = this.type;
            if (num > 1735)
            {
                if (num <= 3858)
                {
                    if (num <= 3191)
                    {
                        if (num <= 2765)
{
                            if (num == 1826)
{
                                return new Color(255, 255, 255, 200);
                            }
                            if (num - 1867 <= 1)
{
                                goto IL_0476;
                            }
                            if (num - 2763 > 2)
{
                                goto IL_0751;
                            }
                        }
                        else if (num - 2782 > 4)
{
                            if (num == 3065)
{
                                goto IL_03D7;
                            }
                            if (num != 3191)
{
                                goto IL_0751;
                            }
                            return new Color(250, 250, 250, 200);
                        }
                    }
                    else if (num <= 3522)
                    {
                        if (num - 3453 <= 2)
{
                            goto IL_045F;
                        }
                        if (num - 3456 <= 3)
{
                            goto IL_0445;
                        }
                        if (num != 3522)
{
                            goto IL_0751;
                        }
                    }
                    else if (num <= 3769)
                    {
                        if (num == 3580)
{
                            goto IL_045F;
                        }
                        if (num - 3764 > 5)
{
                            goto IL_0751;
                        }
                        goto IL_055B;
                    }
                    else
                    {
                        if (num == 3822)
{
                            return Color.Lerp(Color.White, newColor, 0.5f) * ((255f - (float)this.alpha) / 255f);
                        }
                        if (num != 3858)
{
                            goto IL_0751;
                        }
                        goto IL_03FA;
                    }
                    return new Color(250, 250, 250, 255 - this.alpha);
                }
                if (num <= 4956)
                {
                    if (num <= 4354)
                    {
                        if (num == 4143)
{
                            return Color.Lerp(Color.White, newColor, 0f) * ((255f - (float)this.alpha) / 255f);
                        }
                        if (num - 4258 <= 1)
{
                            goto IL_055B;
                        }
                        if (num != 4354)
{
                            goto IL_0751;
                        }
                    }
                    else if (num - 4377 > 1 && num != 4389)
                    {
                        if (num != 4956)
{
                            goto IL_0751;
                        }
                        goto IL_03D7;
                    }
                }
                else if (num <= 5128)
                {
                    if (num == 4988)
                    {
                        goto IL_04F1;
                    }
                    if (num == 5043)
                    {
                        return new Color(255, 255, 255, (int)newColor.A - this.alpha);
                    }
                    if (num - 5127 > 1)
                    {
                        goto IL_0751;
                    }
                }
                else if (num <= 5536)
                {
                    if (num == 5335)
                    {
                        goto IL_03A3;
                    }
                    if (num - 5535 > 1)
                    {
                        goto IL_0751;
                    }
                    goto IL_055B;
                }
                else
                {
                    if (num == 5669)
                    {
                        goto IL_03D7;
                    }
                    if (num - 5670 > 1)
                    {
                        goto IL_0751;
                    }
                    return Color.White;
                }
                Color color = default(Color);
                num = this.type;
                if (num <= 4378)
                {
                    if (num == 4377)
                    {
                        color = new Color(50, 255, 50, 200);
                        goto IL_06D6;
                    }
                    if (num == 4378)
                    {
                        color = new Color(50, 200, 255, 255);
                        goto IL_06D6;
                    }
                }
                else
                {
                    if (num == 4389)
                    {
                        color = new Color(255, 50, 125, 200);
                        goto IL_06D6;
                    }
                    if (num == 5127)
                    {
                        color = new Color(150, 50, 250, 200);
                        goto IL_06D6;
                    }
                    if (num == 5128)
                    {
                        color = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB, 200);
                        goto IL_06D6;
                    }
                }
                color = new Color(255, 150, 150, 200);
                IL_06D6:
                if (newColor.R > color.R)
                {
                    color.R = newColor.R;
                }
                if (newColor.G > color.G)
                {
                    color.G = newColor.G;
                }
                if (newColor.B > color.B)
                {
                    color.B = newColor.B;
                }
                if (newColor.A > color.A)
                {
                    color.A = newColor.A;
                }
                return color;
                IL_03D7:
                return new Color(255, 255, 255, (int)newColor.A - this.alpha);
            }
            if (num <= 575)
            {
                if (num <= 203)
                {
                    if (num <= 75)
                    {
                        if (num == 51)
{
                            return new Color(255, 255, 255, 0);
                        }
                        if (num == 58)
{
                            goto IL_0476;
                        }
                        if (num != 75)
{
                            goto IL_0751;
                        }
                        goto IL_03FA;
                    }
                    else if (num - 119 > 3)
                    {
                        if (num == 184)
{
                            goto IL_0476;
                        }
                        if (num - 198 > 5)
{
                            goto IL_0751;
                        }
                        goto IL_055B;
                    }
                }
                else if (num <= 502)
                {
                    if (num - 217 > 3)
                    {
                        if (num == 501)
{
                            return new Color(200, 200, 200, 50);
                        }
                        if (num != 502)
{
                            goto IL_0751;
                        }
                        goto IL_04F1;
                    }
                }
                else
                {
                    if (num - 520 > 2 && num - 547 > 2 && num != 575)
                    {
                        goto IL_0751;
                    }
                    goto IL_045F;
                }
                return new Color(255, 255, 255, 255);
            }
            if (num > 1326)
            {
                if (num <= 1507)
                {
                    if (num == 1332)
                    {
                        goto IL_045F;
                    }
                    if (num != 1446 && num - 1506 > 1)
                    {
                        goto IL_0751;
                    }
                }
                else if (num <= 1545)
                {
                    if (num == 1508)
                    {
                        return new Color(200, 200, 200, 0);
                    }
                    if (num - 1543 > 2)
                    {
                        goto IL_0751;
                    }
                }
                else
                {
                    if (num == 1572)
                    {
                        return new Color(200, 200, 255, 125);
                    }
                    if (num - 1734 > 1)
                    {
                        goto IL_0751;
                    }
                    goto IL_0476;
                }
                return new Color((int)newColor.R, (int)newColor.G, (int)newColor.B, (int)Main.gFade);
            }
            if (num <= 787)
            {
                if (num == 671)
                {
                    goto IL_03FA;
                }
                if (num == 757)
                {
                    goto IL_0445;
                }
                if (num != 787)
                {
                    goto IL_0751;
                }
                return new Color(255, 255, 255, 175);
            }
            else
            {
                if (num == 1260)
                {
                    return new Color(255, 255, 255, 175);
                }
                if (num == 1306)
                {
                    goto IL_0445;
                }
                if (num != 1326)
                {
                    goto IL_0751;
                }
            }
            IL_03A3:
            return Color.Lerp(newColor, Color.White, 0.75f);
            IL_03FA:
            return new Color(255, 255, 255, 255);
            IL_0445:
            return new Color(255, 255, 255, 200);
            IL_045F:
            return new Color(255, 255, 255, 50);
            IL_0476:
            return new Color(200, 200, 200, 200);
            IL_04F1:
            return new Color(255, 255, 255, 150);
            IL_055B:
            return Color.White;
            IL_0751:
            float num2 = (float)(255 - this.alpha) / 255f;
            int num3 = (int)((float)newColor.R * num2);
            int num4 = (int)((float)newColor.G * num2);
            int num5 = (int)((float)newColor.B * num2);
            int num6 = (int)newColor.A - this.alpha;
            if (num6 < 0)
            {
                num6 = 0;
            }
            if (num6 > 255)
            {
                num6 = 255;
            }
            return new Color(num3, num4, num5, num6);
        }
References Microsoft.Xna.Framework.Color.A, Terraria.Item.alpha, Microsoft.Xna.Framework.Color.B, Terraria.ID.ItemID.Sets.BossBag, Terraria.Item.color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Color.G, Terraria.Main.gFade, int, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Color.R, Terraria.Item.type, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_30_BladedGlove(), and Terraria.WorldItem.GetAlpha().