Terraria Decompiled: Terraria.Item.CanBeEquipped
CanBeEquipped()
bool Terraria.Item.CanBeEquipped () inline
Definition at line 918 of file Item.cs.
        {
            return this.headSlot >= 0 || this.bodySlot >= 0 || this.legSlot >= 0 || this.accessory || (this.shoot > 0 && Main.projHook[this.shoot]) || this.mountType >= 0 || (this.buffType > 0 && (Main.vanityPet[this.buffType] || Main.lightPet[this.buffType]));
        }
References Terraria.Item.buffType, Terraria.Main.lightPet, Terraria.Item.mountType, Terraria.Main.projHook, Terraria.Item.shoot, and Terraria.Main.vanityPet.
Referenced by Terraria.UI.ItemSlot.GetCraftSlotGamepadInstructions(), Terraria.UI.ItemSlot.GetGamepadInstructions(), Terraria.Item.OnlyNeedOneInInventory(), and Terraria.UI.ItemSlot.RightClick().