Terraria Decompiled: Terraria.Item.GetColor
GetColor()
Color Terraria.Item.GetColor (Color newColor) inline
Definition at line 53790 of file Item.cs.
        {
            int num = (int)(this.color.R - (byte.MaxValue - newColor.R));
            int num2 = (int)(this.color.G - (byte.MaxValue - newColor.G));
            int num3 = (int)(this.color.B - (byte.MaxValue - newColor.B));
            int num4 = (int)(this.color.A - (byte.MaxValue - newColor.A));
            if (num < 0)
            {
                num = 0;
            }
            if (num > 255)
            {
                num = 255;
            }
            if (num2 < 0)
            {
                num2 = 0;
            }
            if (num2 > 255)
            {
                num2 = 255;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num3 > 255)
            {
                num3 = 255;
            }
            if (num4 < 0)
            {
                num4 = 0;
            }
            if (num4 > 255)
            {
                num4 = 255;
            }
            return new Color(num, num2, num3, num4);
        }
References Microsoft.Xna.Framework.Color.A, Microsoft.Xna.Framework.Color.B, Terraria.Item.color, Microsoft.Xna.Framework.Color.G, int, and Microsoft.Xna.Framework.Color.R.
Referenced by Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.DataStructures.PlayerDrawLayers.DrawPlayer_27_HeldItem(), Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy(), and Terraria.WorldItem.GetColor().