Terraria Decompiled: Terraria.Item.BestPrefixValue
BestPrefixValue()
float Terraria.Item.BestPrefixValue () inline
Definition at line 832 of file Item.cs.
        {
            int[] rollablePrefixes = this.GetRollablePrefixes();
            if (rollablePrefixes == null)
            {
                return 0f;
            }
            float num = 0f;
            foreach (int num2 in rollablePrefixes)
            {
                float num3;
                float num4;
                float num5;
                float num6;
                float num7;
                float num8;
                int num9;
                int num10;
                int num11;
                float num12;
                if (this.TryGetPrefixStatMultipliersForItem(num2, out num3, out num4, out num5, out num6, out num7, out num8, out num9, out num10, out num11, out num12))
                {
                    num = Math.Max(num, num12);
                }
            }
            return num;
        }
References Terraria.Item.GetRollablePrefixes(), System.Math.Max(), and Terraria.Item.TryGetPrefixStatMultipliersForItem().
Referenced by Terraria.Item.Prefix().