Terraria Decompiled: Terraria.Item.GetRandomVoiceItem
GetRandomVoiceItem()
static int Terraria.Item.GetRandomVoiceItem () inline static
Definition at line 53873 of file Item.cs.
        {
            switch (WorldGen.genRand.Next(14))
            {
            default:
                return 5499;
            case 1:
                return 5500;
            case 2:
                return 5501;
            case 3:
                return 5502;
            case 4:
                return 5503;
            case 5:
                return 5504;
            case 6:
                return 5505;
            case 7:
                return 5506;
            case 8:
                return 5507;
            case 9:
                return 5508;
            case 10:
                return 5509;
            case 11:
                return 5484;
            case 12:
                return 5485;
            case 13:
                return 5534;
            }
        }
References Terraria.WorldGen.genRand, and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.WorldGen.AddVoiceChangeItemToChest(), and Terraria.NPC.AI_001_Slimes().