Terraria Decompiled: Terraria.Item.GetDrawHitbox
GetDrawHitbox()
static Rectangle Terraria.Item.GetDrawHitbox (int type, Player user) inline static
Definition at line 54148 of file Item.cs.
        {
            if (Main.dedServ)
            {
                return Rectangle.Empty;
            }
            Main.instance.LoadItem(type);
            if (ItemID.Sets.IsFood[type])
            {
                return TextureAssets.Item[type].Frame(1, 3, 0, 1, 0, 0);
            }
            if (type <= 549)
            {
                if (type == 75)
                {
                    return TextureAssets.Item[type].Frame(1, 8, 0, 0, 0, 0);
                }
                if (type - 520 > 1 && type - 547 > 2)
                {
                    goto IL_00AF;
                }
            }
            else if (type <= 3455)
            {
                if (type != 575 && type - 3453 > 2)
                {
                    goto IL_00AF;
                }
            }
            else if (type - 3580 > 1 && type - 4068 > 2)
            {
                goto IL_00AF;
            }
            return TextureAssets.Item[type].Frame(1, 4, 0, 0, 0, 0);
            IL_00AF:
            if (Main.itemAnimations[type] != null)
            {
                return Main.itemAnimations[type].GetFrame(TextureAssets.Item[type].Value, -1);
            }
            return TextureAssets.Item[type].Frame(1, 1, 0, 0, 0, 0);
        }
References Terraria.Main.dedServ, Microsoft.Xna.Framework.Rectangle.Empty, Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.Main.instance, Terraria.ID.ItemID.Sets.IsFood, Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Terraria.Main.LoadItem(), Terraria.Item.type, and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.Player.AnimatePlayerAndGetItemFrame(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.Main.DrawMouseOver(), and Terraria.Player.PlayerFrame().