Terraria Decompiled: Terraria.Item.buyPrice
buyPrice()
static int Terraria.Item.buyPrice (int platinum = 0, int gold = 0, int silver = 0, int copper = 0) inline static
Definition at line 53861 of file Item.cs.
        {
            return copper + silver * 100 + gold * 100 * 100 + platinum * 100 * 100 * 100;
        }
References Terraria.Item.copper, Terraria.Item.gold, Terraria.Item.platinum, and Terraria.Item.silver.
Referenced by Terraria.Player.CollectTaxes(), Terraria.Item.DefaultToFood(), Terraria.Item.DefaultToGolfBall(), Terraria.Item.DefaultToHealingPotion(), Terraria.Item.DefaultToKite(), Terraria.Item.DefaultToSolution(), Terraria.Initializers.DyeInitializer.LoadLegacyHairdyes(), Terraria.NPC.SetDefaults(), Terraria.Item.SetDefaults1(), Terraria.Item.SetDefaults2(), Terraria.Item.SetDefaults3(), Terraria.Item.SetDefaults4(), Terraria.Item.SetDefaults5(), Terraria.Item.SetFoodDefaults(), and Terraria.Chest.SetupShop().