Terraria Decompiled: Terraria.Item.TryAddStack
TryAddStack()
bool Terraria.Item.TryAddStack (int itemType, ref int amountLeftToAdd) inline
Definition at line 54099 of file Item.cs.
        {
            if (amountLeftToAdd < 0)
            {
                amountLeftToAdd = 0;
            }
            if (this.IsAir)
            {
                this.SetDefaults(itemType, null);
                int num = Math.Min(amountLeftToAdd, this.maxStack);
                this.stack = num;
                amountLeftToAdd -= num;
                return true;
            }
            if (this.type != itemType)
            {
                return false;
            }
            if (this.stack >= this.maxStack)
            {
                return false;
            }
            int num2 = this.maxStack - this.stack;
            int num3 = Utils.Clamp<int>(amountLeftToAdd, 0, num2);
            if (num3 <= 0)
            {
                return false;
            }
            this.stack += num3;
            amountLeftToAdd -= num3;
            return true;
        }
References Terraria.Utils.Clamp(), Terraria.Item.IsAir, Terraria.Item.maxStack, System.Math.Min(), Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.GameContent.BannerSystem.HandleBannerClaimResponse().