Terraria Decompiled: Terraria.Item.SetDefaults
SetDefaults()
void Terraria.Item.SetDefaults (int Type, ItemVariant variant = null) inline
Definition at line 52913 of file Item.cs.
        {
            if (Type < 0)
            {
                this.netDefaults(Type);
                return;
            }
            this.ResetStats(Type);
            if (this.type >= (int)ItemID.Count)
            {
                this.type = 0;
            }
            if (variant == null)
            {
                variant = ItemVariants.SelectVariant(Type);
            }
            else if (!ItemVariants.HasVariant(Type, variant))
            {
                variant = null;
            }
            this.Variant = variant;
            this.material = ItemID.Sets.IsAMaterial[this.type];
            if (this.type == 0)
            {
                this.stack = 0;
            }
            else if (ItemID.Sets.IsFood[this.type])
            {
                this.SetFoodDefaults(this.type);
            }
            else if (this.type <= 1000)
            {
                this.SetDefaults1(this.type);
            }
            else if (this.type <= 2001)
            {
                this.SetDefaults2(this.type);
            }
            else if (this.type <= 3000)
            {
                this.SetDefaults3(this.type);
            }
            else if (this.type <= 3989)
            {
                this.SetDefaults4(this.type);
            }
            else
            {
                this.SetDefaults5(this.type);
            }
            this.dye = (byte)GameShaders.Armor.GetShaderIdFromItemId(this.type);
            if (this.hairDye != 0)
            {
                this.hairDye = GameShaders.Hair.GetShaderIdFromItemId(this.type);
            }
            if (this.type == 2015)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 2016)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 2017)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 5212)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 5300)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 5311)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 5312)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 5313)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 2019)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 2018)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 3563)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 261)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 2205)
            {
                this.value = Item.sellPrice(0, 0, 12, 50);
            }
            if (this.type == 2123)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 2122)
            {
                this.value = Item.sellPrice(0, 0, 7, 50);
            }
            if (this.type == 2003)
            {
                this.value = Item.sellPrice(0, 0, 10, 0);
            }
            if (this.type == 2156)
            {
                this.value = Item.sellPrice(0, 0, 15, 0);
            }
            if (this.type == 2157)
            {
                this.value = Item.sellPrice(0, 0, 15, 0);
            }
            if (this.type == 2121)
            {
                this.value = Item.sellPrice(0, 0, 10, 0);
            }
            if (this.type == 1992)
            {
                this.value = Item.sellPrice(0, 0, 3, 0);
            }
            if (this.type == 2004)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 2002)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 2740)
            {
                this.value = Item.sellPrice(0, 0, 2, 50);
            }
            if (this.type == 2006)
            {
                this.value = Item.sellPrice(0, 0, 10, 0);
            }
            if (this.type == 3191)
            {
                this.value = Item.sellPrice(0, 0, 20, 0);
            }
            if (this.type == 3192)
            {
                this.value = Item.sellPrice(0, 0, 2, 50);
            }
            if (this.type == 3193)
            {
                this.value = Item.sellPrice(0, 0, 5, 0);
            }
            if (this.type == 3194)
            {
                this.value = Item.sellPrice(0, 0, 10, 0);
            }
            if (this.type == 2007)
            {
                this.value = Item.sellPrice(0, 0, 50, 0);
            }
            if (this.type == 2673)
            {
                this.value = Item.sellPrice(0, 10, 0, 0);
            }
            if (this.bait > 0)
            {
                if (this.bait >= 50)
                {
                    this.rare = 3;
                }
                else if (this.bait >= 30)
                {
                    this.rare = 2;
                }
                else if (this.bait >= 15)
                {
                    this.rare = 1;
                }
            }
            if (this.type >= 1994 && this.type <= 2001)
            {
                int num = this.type - 1994;
                if (num == 0)
                {
                    this.value = Item.sellPrice(0, 0, 5, 0);
                }
                if (num == 4)
                {
                    this.value = Item.sellPrice(0, 0, 10, 0);
                }
                if (num == 6)
                {
                    this.value = Item.sellPrice(0, 0, 15, 0);
                }
                if (num == 3)
                {
                    this.value = Item.sellPrice(0, 0, 20, 0);
                }
                if (num == 7)
                {
                    this.value = Item.sellPrice(0, 0, 30, 0);
                }
                if (num == 2)
                {
                    this.value = Item.sellPrice(0, 0, 40, 0);
                }
                if (num == 1)
                {
                    this.value = Item.sellPrice(0, 0, 75, 0);
                }
                if (num == 5)
                {
                    this.value = Item.sellPrice(0, 1, 0, 0);
                }
            }
            if (this.type == 2663 || this.type == 1720 || this.type == 2137 || this.type == 2155 || this.type == 2151 || this.type == 1704 || this.type == 2143 || this.type == 1710 || this.type == 2238 || this.type == 2133 || this.type == 2147 || this.type == 2405 || this.type == 1716 || this.type == 1705)
            {
                this.value = Item.sellPrice(0, 2, 0, 0);
            }
            if (Main.projHook[this.shoot])
            {
                this.useStyle = 0;
                this.useTime = 0;
                this.useAnimation = 0;
            }
            if (ItemID.Sets.IsDrill[this.type] || ItemID.Sets.IsChainsaw[this.type] || this.type == 1262)
            {
                this.useTime = (int)((double)this.useTime * 0.6);
                if (this.useTime < 1)
                {
                    this.useTime = 1;
                }
                this.useAnimation = (int)((double)this.useAnimation * 0.6);
                if (this.useAnimation < 1)
                {
                    this.useAnimation = 1;
                }
                this.tileBoost--;
            }
            if (ItemID.Sets.IsFood[this.type])
            {
                this.holdStyle = 1;
            }
            if (this.type >= 1803 && this.type <= 1807)
            {
                this.SetDefaults(1533 + this.type - 1803, null);
            }
            this.RebuildTooltip();
            if (this.type > 0 && this.type < (int)ItemID.Count && ItemID.Sets.Deprecated[this.type])
            {
                this.TurnToAir(false);
            }
        }
References Terraria.Graphics.Shaders.GameShaders.Armor, Terraria.Item.bait, Terraria.ID.ItemID.Count, Terraria.ID.ItemID.Sets.Deprecated, Terraria.Graphics.Shaders.ArmorShaderDataSet.GetShaderIdFromItemId(), Terraria.Graphics.Shaders.HairShaderDataSet.GetShaderIdFromItemId(), Terraria.Graphics.Shaders.GameShaders.Hair, Terraria.Item.hairDye, Terraria.GameContent.Items.ItemVariants.HasVariant(), int, Terraria.ID.ItemID.Sets.IsAMaterial, Terraria.ID.ItemID.Sets.IsChainsaw, Terraria.ID.ItemID.Sets.IsDrill, Terraria.ID.ItemID.Sets.IsFood, Terraria.Item.netDefaults(), Terraria.Main.projHook, Terraria.Item.RebuildTooltip(), Terraria.Item.ResetStats(), Terraria.GameContent.Items.ItemVariants.SelectVariant(), Terraria.Item.sellPrice(), Terraria.Item.SetDefaults(), Terraria.Item.SetDefaults1(), Terraria.Item.SetDefaults2(), Terraria.Item.SetDefaults3(), Terraria.Item.SetDefaults4(), Terraria.Item.SetDefaults5(), Terraria.Item.SetFoodDefaults(), Terraria.Item.tileBoost, Terraria.Item.TurnToAir(), Terraria.Item.type, Terraria.Item.useAnimation, and Terraria.Item.useTime.
Referenced by Terraria.Recipe.AddAetheriumFurniture(), Terraria.Recipe.AddAshWoodFurnitureArmorAndItems(), Terraria.Recipe.AddBalloonFurniture(), Terraria.Recipe.AddBambooFurniture(), Terraria.WorldGen.AddBuriedChest(), Terraria.Recipe.AddCoralFurniture(), Terraria.Recipe.AddCritterStatueRecipe(), Terraria.Recipe.AddFallenStarFurniture(), Terraria.Recipe.AddLesionFurniture(), Terraria.WorldGen.AddMonsterVoiceChangeItemToChest(), Terraria.Recipe.AddNebulaFurniture(), Terraria.Recipe.AddSandstoneFurniture(), Terraria.Recipe.AddSolarFurniture(), Terraria.Recipe.AddSpiderFurniture(), Terraria.Recipe.AddStandardFurnitureSetRecipes(), Terraria.Recipe.AddStardustFurniture(), Terraria.WorldGen.AddVoiceChangeItemToChest(), Terraria.Recipe.AddVortexFurniture(), Terraria.Player.ApplyCoating(), Terraria.Player.ApplyEquipFunctional(), Terraria.Player.ApplyPaint(), Terraria.Player.ApplyWilsonBeard(), Terraria.NPC.CatchNPC(), Terraria.Item.ChangeItemType(), Terraria.Player.ConsumeItem(), Terraria.Recipe.CreateReversePlatformRecipes(), Terraria.Recipe.CreateReverseWallRecipes(), Terraria.UI.ChestUI.DepositAll(), Terraria.UI.ChestUI.DepositAll_IntoLocalChest(), Terraria.UI.ChestUI.DepositAll_IntoWorldChest(), Terraria.Player.Deserialize(), Terraria.Main.DisplayAndGetFakeItem(), Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho(), Terraria.WorldGen.SecretSeed.DoPortalGunInChests(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozenFinish(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.GameContent.UI.Elements.UICreativeItemGrid.DrawSlot(), Terraria.DataStructures.TitleLinkButton.DrawTooltip(), Terraria.WorldGen.FinishDrunkGen(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNoTraps(), Terraria.Player.GetAnglerReward_MainReward(), Terraria.MessageBuffer.GetData(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.ID.ContentSamples.Initialize(), Terraria.Player.ItemCheck_CheckFishingBobber_ConsumeBait(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.UI.ItemSlot.LeftClick(), Terraria.Utilities.TileSnapshot.Load(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.Main.MouseText_DrawItemTooltip_GetLinesInfo(), Terraria.UI.ChestUI.MoveCoins(), Terraria.Item.netDefaults(), Terraria.Item.OnCreated(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.UI.ItemSlot.PickupItemIntoMouse(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.PlaceItemInJar(), Terraria.Player.PlaceWeapon(), Terraria.Graphics.Renderers.FakeFishParticle.Prepare(), Terraria.Graphics.Renderers.ItemTransferParticle.Prepare(), Terraria.Player.PutItemInInventoryFromItemUsage(), Terraria.WorldGen.PutMonsterVanityInChests(), Terraria.Player.QuickSpawnItem(), Terraria.GameContent.Tile_Entities.TEHatRack.ReadItem(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.ReadItem(), Terraria.NetMessage.SendData(), Terraria.WorldItem.SetDefaults(), Terraria.Item.SetDefaults(), Terraria.Recipe.SetIngredients(), Terraria.GameContent.UI.States.UICharacterCreation.SetupPlayerStatsAndInventoryBasedOnDifficulty(), Terraria.Recipe.SetupRecipes(), Terraria.UI.ItemSorting.SortCoins(), Terraria.Item.TryAddStack(), Terraria.Wiring.TryMoveCoinsInChest(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.TryPlacing(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.GameContent.UI.Elements.UIBestiaryInfoItemLine.UIBestiaryInfoItemLine(), Terraria.GameContent.UI.States.UICharacterCreation.UpdatePreviewItems(), and Terraria.Projectile.UseGasTrapInChest().