Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.AppendSamples
AppendSamples()
virtual void XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.AppendSamples (int channel, float[] samples) inline package virtual
Reimplemented in XPT.Core.Audio.MP3Sharp.Buffer16BitStereo, and XPT.Core.Audio.MP3Sharp.Decoding.SampleBuffer.
Definition at line 12 of file ABuffer.cs.
        {
            for (int i = 0; i < 32; i++)
            {
                this.Append(channel, ABuffer.Clip(samples[i]));
            }
        }
References XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.Append(), and XPT.Core.Audio.MP3Sharp.Decoding.ABuffer.Clip().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.SynthesisFilter.compute_pc_samples().