Terraria Decompiled: System.Reflection.RuntimeAssembly.GetManifestResourceStream
GetManifestResourceStream() [1/2]
unsafe override Stream System.Reflection.RuntimeAssembly.GetManifestResourceStream (string name) inline virtual
Reimplemented from System.Reflection.Assembly.
Definition at line 393 of file RuntimeAssembly.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            if (name.Length == 0)
            {
                throw new ArgumentException("String cannot have zero length.", "name");
            }
            ManifestResourceInfo manifestResourceInfo = this.GetManifestResourceInfo(name);
            if (manifestResourceInfo == null)
            {
                Assembly assembly = AppDomain.CurrentDomain.DoResourceResolve(name, this);
                if (assembly != null && assembly != this)
                {
                    return assembly.GetManifestResourceStream(name);
                }
                return null;
            }
            else
            {
                if (manifestResourceInfo.ReferencedAssembly != null)
                {
                    return manifestResourceInfo.ReferencedAssembly.GetManifestResourceStream(name);
                }
                if (manifestResourceInfo.FileName != null && manifestResourceInfo.ResourceLocation == (ResourceLocation)0)
                {
                    if (this.fromByteArray)
                    {
                        throw new FileNotFoundException(manifestResourceInfo.FileName);
                    }
                    return new FileStream(Path.Combine(Path.GetDirectoryName(this.Location), manifestResourceInfo.FileName), FileMode.Open, FileAccess.Read);
                }
                else
                {
                    int num;
                    Module module;
                    IntPtr manifestResourceInternal = this.GetManifestResourceInternal(name, out num, out module);
                    if (manifestResourceInternal == (IntPtr)0)
                    {
                        return null;
                    }
                    return new RuntimeAssembly.UnmanagedMemoryStreamForModule((byte*)(void*)manifestResourceInternal, (long)num, module);
                }
            }
        }
References System.IO.Path.Combine(), System.AppDomain.CurrentDomain, System.AppDomain.DoResourceResolve(), System.Reflection.ManifestResourceInfo.FileName, System.Reflection.RuntimeAssembly.fromByteArray, System.IO.Path.GetDirectoryName(), System.Reflection.RuntimeAssembly.GetManifestResourceInfo(), System.Reflection.RuntimeAssembly.GetManifestResourceInternal(), System.Reflection.Assembly.GetManifestResourceStream(), System.name, System.Reflection.ManifestResourceInfo.ReferencedAssembly, and System.Reflection.ManifestResourceInfo.ResourceLocation.
Referenced by System.Resources.ManifestBasedResourceGroveler.CaseInsensitiveManifestResourceStreamLookup(), and System.Resources.ManifestBasedResourceGroveler.GetManifestResourceStream().