Terraria Decompiled: System.Reflection.RuntimeAssembly.CreateAssemblyName
CreateAssemblyName()
static AssemblyName System.Reflection.RuntimeAssembly.CreateAssemblyName (string assemblyString, bool forIntrospection, out RuntimeAssembly assemblyFromResolveEvent) inline static package
Definition at line 47 of file RuntimeAssembly.cs.
        {
            if (assemblyString == null)
            {
                throw new ArgumentNullException("assemblyString");
            }
            if (assemblyString.Length == 0 || assemblyString[0] == '\0')
            {
                throw new ArgumentException(Environment.GetResourceString("String cannot have zero length."));
            }
            if (forIntrospection)
            {
                AppDomain.CheckReflectionOnlyLoadSupported();
            }
            AssemblyName assemblyName = new AssemblyName();
            assemblyName.Name = assemblyString;
            assemblyFromResolveEvent = null;
            return assemblyName;
        }
References System.Reflection.RuntimeAssembly.assemblyName, System.AppDomain.CheckReflectionOnlyLoadSupported(), and System.Environment.GetResourceString().
Referenced by System.Activator.CreateInstance().