Terraria Decompiled: System.Reflection.RuntimeAssembly.Resolve
Resolve()
void System.Reflection.RuntimeAssembly.Resolve () inline package
Definition at line 605 of file RuntimeAssembly.cs.
        {
            lock (this)
            {
                this.LoadAssemblyPermissions();
                Evidence evidence = new Evidence(this.UnprotectedGetEvidence());
                evidence.AddHost(new PermissionRequestEvidence(this._minimum, this._optional, this._refuse));
                this._granted = SecurityManager.ResolvePolicy(evidence, this._minimum, this._optional, this._refuse, out this._denied);
            }
        }
References System.Reflection.RuntimeAssembly._denied, System.Reflection.RuntimeAssembly._minimum, System.Reflection.RuntimeAssembly._optional, System.Reflection.RuntimeAssembly._refuse, System.Security.Policy.Evidence.AddHost(), System.Reflection.RuntimeAssembly.Evidence, System.Reflection.RuntimeAssembly.LoadAssemblyPermissions(), System.Security.SecurityManager.ResolvePolicy(), and System.Reflection.RuntimeAssembly.UnprotectedGetEvidence().