Terraria Decompiled: Ionic.Zlib.Adler.Adler32
Adler32()
static uint Ionic.Zlib.Adler.Adler32 (uint adler, byte[] buf, int index, int len) inline static
Definition at line 9 of file Adler.cs.
        {
            if (buf == null)
            {
                return 1U;
            }
            uint num = adler & 65535U;
            uint num2 = (adler >> 16) & 65535U;
            while (len > 0)
            {
                int i = ((len < Adler.NMAX) ? len : Adler.NMAX);
                len -= i;
                while (i >= 16)
                {
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    num += (uint)buf[index++];
                    num2 += num;
                    i -= 16;
                }
                if (i != 0)
                {
                    do
                    {
                        num += (uint)buf[index++];
                        num2 += num;
                    }
                    while (--i != 0);
                }
                num %= Adler.BASE;
                num2 %= Adler.BASE;
            }
            return (num2 << 16) | num;
        }
References Ionic.Zlib.Adler.BASE, System.index, Ionic.Zlib.Adler.NMAX, and System.U.
Referenced by Ionic.Zlib.DeflateManager.Deflate(), Ionic.Zlib.InflateBlocks.Flush(), Ionic.Zlib.ZlibCodec.read_buf(), Ionic.Zlib.DeflateManager.Reset(), Ionic.Zlib.InflateBlocks.Reset(), Ionic.Zlib.DeflateManager.SetDictionary(), and Ionic.Zlib.InflateManager.SetDictionary().