Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion
ResaveForCurrentVersion()
void Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion () inline
Definition at line 176 of file WorldGenSnapshot.cs.
        {
            this.Manifest = WorldGen.Manifest.Clone();
            this.GenVarsJson = WorldGenSnapshot.SnapshotGenVars.Serialize();
            using (MemoryStream memoryStream = new MemoryStream())
            {
                using (FileStream fileStream = File.OpenRead(this.Path))
                {
                    fileStream.Seek((long)this._dataOffset, SeekOrigin.Current);
                    fileStream.CopyTo(memoryStream);
                }
                memoryStream.Position = 0L;
                using (BinaryWriter binaryWriter = new BinaryWriter(File.Create(this.Path)))
                {
                    binaryWriter.Write(this.Manifest.Serialize());
                    binaryWriter.Write(this.GenVarsJson);
                    this._dataOffset = (int)binaryWriter.BaseStream.Position;
                    memoryStream.CopyTo(binaryWriter.BaseStream);
                    WorldGenSnapshot._snapshotSizeCache[this.Path] = binaryWriter.BaseStream.Length;
                }
            }
        }
References Terraria.WorldBuilding.WorldGenSnapshot._dataOffset, Terraria.WorldBuilding.WorldGenSnapshot._snapshotSizeCache, System.IO.BinaryWriter.BaseStream, System.IO.Stream.CopyTo(), System.IO.MemoryStream.CopyTo(), System.IO.File.Create(), Terraria.WorldBuilding.WorldGenSnapshot.GenVarsJson, int, System.L, System.IO.Stream.Length, Terraria.WorldBuilding.WorldGenSnapshot.Manifest, Terraria.WorldGen.Manifest, System.IO.File.OpenRead(), Terraria.WorldBuilding.WorldGenSnapshot.Path, System.IO.Stream.Position, System.IO.FileStream.Seek(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.Serialize(), Terraria.WorldBuilding.WorldManifest.Serialize(), and System.IO.BinaryWriter.Write().