Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.DeleteAllForCurrentWorld
DeleteAllForCurrentWorld()
static void Terraria.WorldBuilding.WorldGenSnapshot.DeleteAllForCurrentWorld () inline static
Definition at line 121 of file WorldGenSnapshot.cs.
        {
            if (Directory.Exists(WorldGenSnapshot.PathForActiveWorld))
            {
                try
                {
                    Directory.Delete(WorldGenSnapshot.PathForActiveWorld, true);
                }
                catch (Exception)
                {
                }
            }
            WorldGenSnapshot._snapshotSizeCache.Clear();
        }
References Terraria.WorldBuilding.WorldGenSnapshot._snapshotSizeCache, System.IO.Directory.Delete(), System.IO.Directory.Exists(), and Terraria.WorldBuilding.WorldGenSnapshot.PathForActiveWorld.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__41_0(), Terraria.WorldBuilding.WorldGenerator.Controller.DeleteAllSnapshots(), and Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots().