Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.Create
Create()
static WorldGenSnapshot Terraria.WorldBuilding.WorldGenSnapshot.Create () inline static
Definition at line 137 of file WorldGenSnapshot.cs.
        {
            WorldGenSnapshot worldGenSnapshot = new WorldGenSnapshot
            {
                Manifest = WorldGen.Manifest.Clone(),
                GenVarsJson = WorldGenSnapshot.SnapshotGenVars.Serialize()
            };
            worldGenSnapshot._matchingPasses = WorldGenerator.CurrentController.Passes.GetRange(0, worldGenSnapshot.GenPassResults.Count);
            worldGenSnapshot.Path = global::System.IO.Path.Combine(WorldGenSnapshot.PathForActiveWorld, worldGenSnapshot + WorldGenSnapshot.Extension);
            if (!Directory.Exists(WorldGenSnapshot.PathForActiveWorld))
            {
                Directory.CreateDirectory(WorldGenSnapshot.PathForActiveWorld);
            }
            TileSnapshot.Create(worldGenSnapshot);
            using (BinaryWriter binaryWriter = new BinaryWriter(File.Create(worldGenSnapshot.Path)))
            {
                binaryWriter.Write(worldGenSnapshot.Manifest.Serialize());
                binaryWriter.Write(worldGenSnapshot.GenVarsJson);
                worldGenSnapshot._dataOffset = (int)binaryWriter.BaseStream.Position;
                TileSnapshot.Save(binaryWriter);
                WorldGenSnapshot._snapshotSizeCache[worldGenSnapshot.Path] = binaryWriter.BaseStream.Length;
            }
            return worldGenSnapshot;
        }
References Terraria.WorldBuilding.WorldGenSnapshot._snapshotSizeCache, System.IO.BinaryWriter.BaseStream, Terraria.Utilities.TileSnapshot.Create(), System.IO.File.Create(), System.IO.Directory.CreateDirectory(), Terraria.WorldBuilding.WorldGenerator.CurrentController, System.IO.Directory.Exists(), Terraria.WorldBuilding.WorldGenSnapshot.Extension, Terraria.WorldBuilding.WorldGenSnapshot.GenPassResults, Terraria.WorldBuilding.WorldGenSnapshot.GenVarsJson, int, System.IO.Stream.Length, Terraria.WorldBuilding.WorldGenSnapshot.Manifest, Terraria.WorldGen.Manifest, Terraria.WorldBuilding.WorldGenSnapshot.Path, Terraria.WorldBuilding.WorldGenSnapshot.PathForActiveWorld, System.IO.Stream.Position, Terraria.Utilities.TileSnapshot.Save(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.Serialize(), Terraria.WorldBuilding.WorldManifest.Serialize(), and System.IO.BinaryWriter.Write().
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__45_0(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryCreateSnapshot().