Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots
LoadSnapshots()
static Dictionary< GenPass, WorldGenSnapshot > Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots (WorldManifest worldManifest, List< GenPass > passes) inline static
Definition at line 200 of file WorldGenSnapshot.cs.
        {
            WorldGenSnapshot._snapshotSizeCache.Clear();
            Dictionary<GenPass, WorldGenSnapshot> dictionary = new Dictionary<GenPass, WorldGenSnapshot>();
            Task.Factory.StartNew(delegate
            {
                WorldGenSnapshot.DeleteSnapshotsForOtherWorlds(WorldGenSnapshot.PathForActiveWorld);
            });
            if (!Directory.Exists(WorldGenSnapshot.PathForActiveWorld))
            {
                return dictionary;
            }
            if (worldManifest == null)
            {
                Trace.WriteLine("Deleting old snapshots because a new world is being created (/regen was not used)");
                WorldGenSnapshot.DeleteAllForCurrentWorld();
                return dictionary;
            }
            using (IEnumerator<string> enumerator = Directory.EnumerateFiles(WorldGenSnapshot.PathForActiveWorld, "*" + WorldGenSnapshot.Extension).GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    WorldGenSnapshot worldGenSnapshot;
                    GenPass genPass;
                    if (WorldGenSnapshot.ReadSnapshot(enumerator.Current, out worldGenSnapshot) && worldGenSnapshot.IsValidHistoryOf(worldManifest) && WorldGenSnapshot.FindMatchingGenPass(worldGenSnapshot.Manifest, passes, out genPass))
                    {
                        worldGenSnapshot._matchingPasses = passes.GetRange(0, worldGenSnapshot.GenPassResults.Count);
                        dictionary[genPass] = worldGenSnapshot;
                    }
                    else
                    {
                        Trace.WriteLine(string.Format("Deleting snapshot ({0}) due to manifest mismatch. A change to the codebase has probably invalidated it.", worldGenSnapshot));
                        WorldGenSnapshot.Delete(worldGenSnapshot);
                    }
                }
            }
            return dictionary;
        }
References Terraria.WorldBuilding.WorldGenSnapshot._snapshotSizeCache, System.Collections.Generic.IEnumerator< out T >.Current, Terraria.WorldBuilding.WorldGenSnapshot.Delete(), Terraria.WorldBuilding.WorldGenSnapshot.DeleteAllForCurrentWorld(), Terraria.WorldBuilding.WorldGenSnapshot.DeleteSnapshotsForOtherWorlds(), System.dictionary, System.IO.Directory.EnumerateFiles(), System.IO.Directory.Exists(), Terraria.WorldBuilding.WorldGenSnapshot.Extension, System.Threading.Tasks.Task< TResult >.Factory, Terraria.WorldBuilding.WorldGenSnapshot.FindMatchingGenPass(), System.Format, Terraria.WorldBuilding.WorldGenSnapshot.GenPassResults, System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), System.Collections.Generic.List< T >.GetRange(), Terraria.WorldBuilding.WorldGenSnapshot.IsValidHistoryOf(), Terraria.WorldBuilding.WorldGenSnapshot.Manifest, System.Collections.IEnumerator.MoveNext(), Terraria.WorldBuilding.WorldGenSnapshot.PathForActiveWorld, Terraria.WorldBuilding.WorldGenSnapshot.ReadSnapshot(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), and System.Trace.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.SetGenerator().