Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.ReadSnapshot
ReadSnapshot()
static bool Terraria.WorldBuilding.WorldGenSnapshot.ReadSnapshot (string path, out WorldGenSnapshot snap) inline static private
Definition at line 293 of file WorldGenSnapshot.cs.
        {
            bool flag;
            try
            {
                using (BinaryReader binaryReader = new BinaryReader(File.OpenRead(path)))
                {
                    snap = new WorldGenSnapshot
                    {
                        Path = path,
                        Manifest = WorldManifest.Deserialize(binaryReader.ReadString()),
                        GenVarsJson = binaryReader.ReadString(),
                        _dataOffset = (int)binaryReader.BaseStream.Position
                    };
                    WorldGenSnapshot._snapshotSizeCache[path] = binaryReader.BaseStream.Length;
                    flag = true;
                }
            }
            catch (Exception ex)
            {
                Trace.WriteLine(string.Concat(new object[] { "Failed to read snapshot: ", path, ", ", ex }));
                snap = null;
                flag = false;
            }
            return flag;
        }
References Terraria.WorldBuilding.WorldGenSnapshot._dataOffset, Terraria.WorldBuilding.WorldGenSnapshot._snapshotSizeCache, System.IO.BinaryReader.BaseStream, Terraria.WorldBuilding.WorldManifest.Deserialize(), Terraria.WorldBuilding.WorldGenSnapshot.GenVarsJson, int, System.IO.Stream.Length, Terraria.WorldBuilding.WorldGenSnapshot.Manifest, System.IO.File.OpenRead(), System.IO.Stream.Position, System.IO.BinaryReader.ReadString(), and System.Trace.
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.LoadSnapshots().