Terraria Decompiled: Terraria.WorldBuilding.WorldGenSnapshot.Restore
Restore()
void Terraria.WorldBuilding.WorldGenSnapshot.Restore () inline
Definition at line 335 of file WorldGenSnapshot.cs.
        {
            this.Load();
            WorldGen.RestoreTemporaryStateChanges();
            WorldGen.Reset();
            WorldGen.Manifest = this.Manifest.Clone();
            WorldGenSnapshot.SnapshotGenVars.DeserializeAndApply(this.GenVarsJson);
            TileSnapshot.Restore();
            NPC[] npc = Main.npc;
            for (int i = 0; i < npc.Length; i++)
            {
                npc[i].active = false;
            }
            Main.NewText("Restored " + this, byte.MaxValue, byte.MaxValue, 0);
        }
References Terraria.NPC.active, Terraria.WorldBuilding.WorldManifest.Clone(), Terraria.WorldBuilding.WorldGenSnapshot.SnapshotGenVars.DeserializeAndApply(), Terraria.WorldBuilding.WorldGenSnapshot.GenVarsJson, Terraria.WorldBuilding.WorldGenSnapshot.Load(), Terraria.WorldBuilding.WorldGenSnapshot.Manifest, System.Reflection.MaxValue, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.WorldGen.Reset(), Terraria.Utilities.TileSnapshot.Restore(), and Terraria.WorldGen.RestoreTemporaryStateChanges().
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.TryResetToSnapshot().