Terraria Decompiled: Terraria.GameContent.UI.Minimap.MinimapFrame.Update
Update()
void Terraria.GameContent.UI.Minimap.MinimapFrame.Update () inline
Definition at line 135 of file MinimapFrame.cs.
        {
            MinimapFrame.Button button = null;
            if (this._zoomInButton.IsHighlighted)
            {
                button = this._zoomInButton;
            }
            if (this._zoomOutButton.IsHighlighted)
            {
                button = this._zoomOutButton;
            }
            if (this._resetButton.IsHighlighted)
            {
                button = this._resetButton;
            }
            this._zoomInButton.IsHighlighted = false;
            this._zoomOutButton.IsHighlighted = false;
            this._resetButton.IsHighlighted = false;
            MinimapFrame.Button buttonUnderMouse = this.GetButtonUnderMouse();
            if (buttonUnderMouse != null && !PlayerInput.IgnoreMouseInterface && !Main.LocalPlayer.controlTorch)
            {
                buttonUnderMouse.IsHighlighted = true;
                Main.LocalPlayer.mouseInterface = true;
                if (button != buttonUnderMouse)
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                if (Main.mouseLeft)
                {
                    buttonUnderMouse.Click();
                    if (Main.mouseLeftRelease)
                    {
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    }
                }
            }
        }
References Terraria.GameContent.UI.Minimap.MinimapFrame._resetButton, Terraria.GameContent.UI.Minimap.MinimapFrame._zoomInButton, Terraria.GameContent.UI.Minimap.MinimapFrame._zoomOutButton, Terraria.GameContent.UI.Minimap.MinimapFrame.Button.Click(), Terraria.Player.controlTorch, Terraria.GameContent.UI.Minimap.MinimapFrame.GetButtonUnderMouse(), Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.LocalPlayer, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, and Terraria.Audio.SoundEngine.PlaySound().