Terraria Decompiled: Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ScanWorldForFinds
ScanWorldForFinds()
void Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.ScanWorldForFinds () inline
Definition at line 110 of file NPCWasNearPlayerTracker.cs.
        {
            this._playerHitboxesForBestiary.Clear();
            for (int i = 0; i < 255; i++)
            {
                Player player = Main.player[i];
                if (player.active)
                {
                    this._playerHitboxesForBestiary.Add(player.HitboxForBestiaryNearbyCheck);
                }
            }
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.active && npc.CountsAsACritter && !this._wasSeenNearPlayerByNetId.Contains(npc.netID))
                {
                    Rectangle hitbox = npc.Hitbox;
                    for (int k = 0; k < this._playerHitboxesForBestiary.Count; k++)
                    {
                        Rectangle rectangle = this._playerHitboxesForBestiary[k];
                        if (hitbox.Intersects(rectangle))
{
                            this._wasSeenNearPlayerByNetId.Add(npc.netID);
                            this.RegisterWasNearby(npc);
                        }
                    }
                }
            }
        }
References Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker._playerHitboxesForBestiary, Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker._wasSeenNearPlayerByNetId, Terraria.NPC.active, Terraria.Player.active, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.NPC.CountsAsACritter, Terraria.Entity.Hitbox, Terraria.Player.HitboxForBestiaryNearbyCheck, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.maxNPCs, Terraria.NPC.netID, Terraria.Main.npc, Terraria.Main.player, and Terraria.GameContent.Bestiary.NPCWasNearPlayerTracker.RegisterWasNearby().
Referenced by Terraria.Main.DoUpdateInWorld().