Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Header.ToString
ToString()
override string XPT.Core.Audio.MP3Sharp.Decoding.Header.ToString () inline
Definition at line 33 of file Header.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(200);
            stringBuilder.Append("Layer ");
            stringBuilder.Append(this.LayerAsString());
            stringBuilder.Append(" frame ");
            stringBuilder.Append(this.ModeAsString());
            stringBuilder.Append(' ');
            stringBuilder.Append(this.VersionAsString());
            if (!this.IsProtection())
            {
                stringBuilder.Append(" no");
            }
            stringBuilder.Append(" checksums");
            stringBuilder.Append(' ');
            stringBuilder.Append(this.SampleFrequencyAsString());
            stringBuilder.Append(',');
            stringBuilder.Append(' ');
            stringBuilder.Append(this.BitrateAsString());
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), XPT.Core.Audio.MP3Sharp.Decoding.Header.BitrateAsString(), XPT.Core.Audio.MP3Sharp.Decoding.Header.IsProtection(), XPT.Core.Audio.MP3Sharp.Decoding.Header.LayerAsString(), XPT.Core.Audio.MP3Sharp.Decoding.Header.ModeAsString(), XPT.Core.Audio.MP3Sharp.Decoding.Header.SampleFrequencyAsString(), System.Text.StringBuilder.ToString(), and XPT.Core.Audio.MP3Sharp.Decoding.Header.VersionAsString().