Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Header.read_header
read_header()
void XPT.Core.Audio.MP3Sharp.Decoding.Header.read_header (Bitstream stream, Crc16[] crcp) inline package
Definition at line 56 of file Header.cs.
        {
            bool flag = false;
            for (;;)
            {
                int num = stream.SyncHeader(this._Syncmode);
                this._Headerstring = num;
                if (this._Syncmode == 0)
                {
                    this._Version = SupportClass.URShift(num, 19) & 1;
                    if ((SupportClass.URShift(num, 20) & 1) == 0)
                    {
                        if (this._Version != 0)
{
                            break;
                        }
                        this._Version = 2;
                    }
                    if ((this._SampleFrequency = SupportClass.URShift(num, 10) & 3) == 3)
                    {
                        goto Block_4;
                    }
                }
                this._Layer = (4 - SupportClass.URShift(num, 17)) & 3;
                this._ProtectionBit = SupportClass.URShift(num, 16) & 1;
                this._BitrateIndex = SupportClass.URShift(num, 12) & 15;
                this._PaddingBit = SupportClass.URShift(num, 9) & 1;
                this._Mode = SupportClass.URShift(num, 6) & 3;
                this._ModeExtension = SupportClass.URShift(num, 4) & 3;
                if (this._Mode == 1)
                {
                    this._IntensityStereoBound = (this._ModeExtension << 2) + 4;
                }
                else
                {
                    this._IntensityStereoBound = 0;
                }
                this._Copyright |= (SupportClass.URShift(num, 3) & 1) == 1;
                this._Original |= (SupportClass.URShift(num, 2) & 1) == 1;
                if (this._Layer == 1)
                {
                    this._NumberOfSubbands = 32;
                }
                else
                {
                    int num2 = this._BitrateIndex;
                    if (this._Mode != 3)
                    {
                        if (num2 == 4)
{
                            num2 = 1;
                        }
                        else
{
                            num2 -= 4;
                        }
                    }
                    if (num2 == 1 || num2 == 2)
                    {
                        if (this._SampleFrequency == 2)
{
                            this._NumberOfSubbands = 12;
                        }
                        else
{
                            this._NumberOfSubbands = 8;
                        }
                    }
                    else if (this._SampleFrequency == 1 || (num2 >= 3 && num2 <= 5))
                    {
                        this._NumberOfSubbands = 27;
                    }
                    else
                    {
                        this._NumberOfSubbands = 30;
                    }
                }
                if (this._IntensityStereoBound > this._NumberOfSubbands)
                {
                    this._IntensityStereoBound = this._NumberOfSubbands;
                }
                this.CalculateFrameSize();
                stream.Read_frame_data(this.Framesize);
                if (stream.IsSyncCurrentPosition((int)this._Syncmode))
                {
                    if (this._Syncmode == 0)
                    {
                        this._Syncmode = 1;
                        stream.SetSyncWord(num & -521024);
                    }
                    flag = true;
                }
                else
                {
                    stream.UnreadFrame();
                }
                if (flag)
                {
                    goto Block_16;
                }
            }
            throw stream.NewBitstreamException(256);
            Block_4:
            throw stream.NewBitstreamException(256);
            Block_16:
            stream.ParseFrame();
            if (this._ProtectionBit == 0)
            {
                this.Checksum = (short)stream.GetBitsFromBuffer(16);
                if (this._CRC == null)
                {
                    this._CRC = new Crc16();
                }
                int num;
                this._CRC.AddBits(num, 16);
                crcp[0] = this._CRC;
            }
            else
            {
                crcp[0] = null;
            }
            int sampleFrequency = this._SampleFrequency;
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Header._BitrateIndex, XPT.Core.Audio.MP3Sharp.Decoding.Header._CRC, XPT.Core.Audio.MP3Sharp.Decoding.Header._IntensityStereoBound, XPT.Core.Audio.MP3Sharp.Decoding.Header._Layer, XPT.Core.Audio.MP3Sharp.Decoding.Header._Mode, XPT.Core.Audio.MP3Sharp.Decoding.Header._NumberOfSubbands, XPT.Core.Audio.MP3Sharp.Decoding.Header._ProtectionBit, XPT.Core.Audio.MP3Sharp.Decoding.Header._SampleFrequency, XPT.Core.Audio.MP3Sharp.Decoding.Header._Syncmode, XPT.Core.Audio.MP3Sharp.Decoding.Header._Version, XPT.Core.Audio.MP3Sharp.Decoding.Crc16.AddBits(), XPT.Core.Audio.MP3Sharp.Decoding.Header.CalculateFrameSize(), XPT.Core.Audio.MP3Sharp.Decoding.Header.Framesize, XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.GetBitsFromBuffer(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.IsSyncCurrentPosition(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.NewBitstreamException(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ParseFrame(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.Read_frame_data(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.SetSyncWord(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.SyncHeader(), XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.UnreadFrame(), and XPT.Core.Audio.MP3Sharp.Support.SupportClass.URShift().
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Bitstream.ReadNextFrame().