Terraria Decompiled: Terraria.TimeLogger.DataSeries.Quantile
Quantile()
static int Terraria.TimeLogger.DataSeries.Quantile (int[] sorted, int len, float quantile) inline static private
Definition at line 836 of file TimeLogger.cs.
            {
                quantile *= (float)(len - 1);
                return (int)MathHelper.Lerp((float)sorted[(int)Math.Floor((double)quantile)], (float)sorted[(int)Math.Ceiling((double)quantile)], quantile % 1f);
            }
References System.Math.Ceiling(), System.Math.Floor(), int, and Microsoft.Xna.Framework.MathHelper.Lerp().
Referenced by Terraria.TimeLogger.DataSeries.StartNextFrame().