Terraria Decompiled: System.IO.UnmanagedMemoryAccessor.ReadDecimal
ReadDecimal()
unsafe decimal System.IO.UnmanagedMemoryAccessor.ReadDecimal (long position) inline
Definition at line 230 of file UnmanagedMemoryAccessor.cs.
        {
            this.EnsureSafeToRead(position, 16);
            byte* ptr = null;
            int num;
            int num2;
            int num3;
            int num4;
            try
            {
                this._buffer.AcquirePointer(ref ptr);
                ptr += this._offset + position;
                num = Unsafe.ReadUnaligned<int>((void*)ptr);
                num2 = Unsafe.ReadUnaligned<int>((void*)(ptr + 4));
                num3 = Unsafe.ReadUnaligned<int>((void*)(ptr + 8));
                num4 = Unsafe.ReadUnaligned<int>((void*)(ptr + 12));
            }
            finally
            {
                if (ptr != null)
                {
                    this._buffer.ReleasePointer();
                }
            }
            if ((num4 & 2130771967) != 0 || (num4 & 16711680) > 1835008)
            {
                throw new ArgumentException("Read an invalid decimal value from the buffer.");
            }
            bool flag = (num4 & int.MinValue) != 0;
            byte b = (byte)(num4 >> 16);
            return new decimal(num, num2, num3, flag, b);
        }
References System.IO.UnmanagedMemoryAccessor._buffer, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryAccessor.EnsureSafeToRead(), and System.Runtime.InteropServices.SafeBuffer.ReleasePointer().