Terraria Decompiled: System.IO.UnmanagedMemoryAccessor.ReadInt32
ReadInt32()
unsafe int System.IO.UnmanagedMemoryAccessor.ReadInt32 (long position) inline
Definition at line 188 of file UnmanagedMemoryAccessor.cs.
        {
            this.EnsureSafeToRead(position, 4);
            byte* ptr = null;
            int num;
            try
            {
                this._buffer.AcquirePointer(ref ptr);
                num = Unsafe.ReadUnaligned<int>((void*)(ptr + this._offset + position));
            }
            finally
            {
                if (ptr != null)
                {
                    this._buffer.ReleasePointer();
                }
            }
            return num;
        }
References System.IO.UnmanagedMemoryAccessor._buffer, System.IO.UnmanagedMemoryAccessor._offset, System.Runtime.InteropServices.SafeBuffer.AcquirePointer(), System.IO.UnmanagedMemoryAccessor.EnsureSafeToRead(), and System.Runtime.InteropServices.SafeBuffer.ReleasePointer().
Referenced by System.IO.UnmanagedMemoryAccessor.ReadSingle(), and System.IO.UnmanagedMemoryAccessor.ReadUInt32().