Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicProxyMetaObject.CallMethodNoResult
CallMethodNoResult()
DynamicMetaObject Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.CallMethodNoResult (string methodName, DynamicMetaObjectBinder binder, Expression[] args, DynamicProxyMetaObject< T >::Fallback fallback) inline private
Definition at line 241 of file DynamicProxyMetaObject.cs.
        {
            DynamicMetaObject dynamicMetaObject = fallback(null);
            IList<Expression> list = new List<Expression>();
            list.Add(Expression.Convert(base.Expression, typeof(T)));
            list.Add(DynamicProxyMetaObject<T>.Constant(binder));
            list.AddRange(args);
            return new DynamicMetaObject(Expression.Condition(Expression.Call(Expression.Constant(this._proxy), typeof(DynamicProxy<T>).GetMethod(methodName), list), Expression.Empty(), dynamicMetaObject.Expression, typeof(void)), this.GetRestrictions().Merge(dynamicMetaObject.Restrictions));
        }
References Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.Constant(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.GetRestrictions(), and System.list.
Referenced by Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindDeleteIndex(), and Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindDeleteMember().