Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicProxyMetaObject.BindInvokeMember
BindInvokeMember()
override DynamicMetaObject Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindInvokeMember (InvokeMemberBinder binder, DynamicMetaObject[] args) inline
Definition at line 67 of file DynamicProxyMetaObject.cs.
        {
            if (!this.IsOverridden("TryInvokeMember"))
            {
                return base.BindInvokeMember(binder, args);
            }
            DynamicProxyMetaObject<T>.Fallback fallback = (DynamicMetaObject e) => binder.FallbackInvokeMember(this, args, e);
            return this.BuildCallMethodWithResult("TryInvokeMember", binder, DynamicProxyMetaObject<T>.GetArgArray(args), this.BuildCallMethodWithResult("TryGetMember", new DynamicProxyMetaObject<T>.GetBinderAdapter(binder), DynamicProxyMetaObject<T>.NoArgs, fallback(null), (DynamicMetaObject e) => binder.FallbackInvoke(e, args, null)), null);
        }
References Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BuildCallMethodWithResult(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.Fallback(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.GetArgArray(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.IsOverridden(), and Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.NoArgs.