Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicProxyMetaObject.GetArgs
GetArgs()
static IEnumerable< Expression > Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.GetArgs (params DynamicMetaObject[] args) inline static private
Definition at line 158 of file DynamicProxyMetaObject.cs.
        {
            return Enumerable.Select<DynamicMetaObject, Expression>(args, delegate(DynamicMetaObject arg)
            {
                Expression expression = arg.Expression;
                if (!expression.Type.IsValueType())
                {
                    return expression;
                }
                return Expression.Convert(expression, typeof(object));
            });
        }
Referenced by Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindBinaryOperation(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindSetMember(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.GetArgArray(), and Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.GetArgArray().