Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicProxyMetaObject.IsOverridden
IsOverridden()
bool Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.IsOverridden (string method) inline private
Definition at line 21 of file DynamicProxyMetaObject.cs.
        {
            return ReflectionUtils.IsMethodOverridden(this._proxy.GetType(), typeof(DynamicProxy<T>), method);
        }
References Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >._proxy, and Newtonsoft.Json.Utilities.ReflectionUtils.IsMethodOverridden().
Referenced by Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindBinaryOperation(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindConvert(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindCreateInstance(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindDeleteIndex(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindDeleteMember(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindGetIndex(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindGetMember(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindInvoke(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindInvokeMember(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindSetIndex(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindSetMember(), and Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindUnaryOperation().