Terraria Decompiled: Newtonsoft.Json.Utilities.DynamicProxyMetaObject.BindSetMember
BindSetMember()
override DynamicMetaObject Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.BindSetMember (SetMemberBinder binder, DynamicMetaObject value) inline
Definition at line 37 of file DynamicProxyMetaObject.cs.
        {
            if (!this.IsOverridden("TrySetMember"))
            {
                return base.BindSetMember(binder, value);
            }
            return this.CallMethodReturnLast("TrySetMember", binder, DynamicProxyMetaObject<T>.GetArgs(new DynamicMetaObject[] { value }), (DynamicMetaObject e) => binder.FallbackSetMember(this, value, e));
        }
References Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.CallMethodReturnLast(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.GetArgs(), Newtonsoft.Json.Utilities.DynamicProxyMetaObject< T >.IsOverridden(), and System.value.