Terraria Decompiled: System.Collections.CollectionBase.Add
Add()
int IList. System.Collections.CollectionBase.Add (object value) inline private
Implements System.Collections.IList.
Definition at line 182 of file CollectionBase.cs.
        {
            this.OnValidate(value);
            this.OnInsert(this.InnerList.Count, value);
            int num = this.InnerList.Add(value);
            try
            {
                this.OnInsertComplete(num, value);
            }
            catch
            {
                this.InnerList.RemoveAt(num);
                throw;
            }
            return num;
        }
References System.Collections.ArrayList.Add(), System.Collections.ArrayList.Count, System.Collections.CollectionBase.InnerList, System.Collections.CollectionBase.OnInsert(), System.Collections.CollectionBase.OnInsertComplete(), System.Collections.CollectionBase.OnValidate(), System.Collections.ArrayList.RemoveAt(), and System.value.