Terraria Decompiled: System.Collections.CollectionBase.Remove
Remove()
void IList. System.Collections.CollectionBase.Remove (object value) inline private
Implements System.Collections.IList.
Definition at line 200 of file CollectionBase.cs.
        {
            this.OnValidate(value);
            int num = this.InnerList.IndexOf(value);
            if (num < 0)
            {
                throw new ArgumentException("Cannot remove the specified item because it was not found in the specified Collection.");
            }
            this.OnRemove(num, value);
            this.InnerList.RemoveAt(num);
            try
            {
                this.OnRemoveComplete(num, value);
            }
            catch
            {
                this.InnerList.Insert(num, value);
                throw;
            }
        }
References System.Collections.ArrayList.IndexOf(), System.Collections.CollectionBase.InnerList, System.Collections.ArrayList.Insert(), System.Collections.CollectionBase.OnRemove(), System.Collections.CollectionBase.OnRemoveComplete(), System.Collections.CollectionBase.OnValidate(), System.Collections.ArrayList.RemoveAt(), and System.value.