Terraria Decompiled: Terraria.GameContent.Skies.SolarSky.Draw
Draw()
override void Terraria.GameContent.Skies.SolarSky.Draw (SpriteBatch spriteBatch, float minDepth, float maxDepth) inline
Definition at line 56 of file SolarSky.cs.
        {
            if (maxDepth >= 3.4028235E+38f && minDepth < 3.4028235E+38f)
            {
                spriteBatch.Draw(TextureAssets.BlackTile.Value, new Rectangle(0, 0, Main.screenWidth, Main.screenHeight), Color.Black * this._fadeOpacity);
                spriteBatch.Draw(this._bgTexture.Value, new Rectangle(0, Math.Max(0, (int)((Main.worldSurface * 16.0 - (double)Main.screenPosition.Y - 2400.0) * 0.10000000149011612)), Main.screenWidth, Main.screenHeight), Color.White * Math.Min(1f, (Main.screenPosition.Y - 800f) / 1000f * this._fadeOpacity));
                Vector2 vector = new Vector2((float)(Main.screenWidth >> 1), (float)(Main.screenHeight >> 1));
                Vector2 vector2 = 0.01f * (new Vector2((float)Main.maxTilesX * 8f, (float)Main.worldSurface / 2f) - Main.screenPosition);
                spriteBatch.Draw(this._planetTexture.Value, vector + new Vector2(-200f, -200f) + vector2, null, Color.White * 0.9f * this._fadeOpacity, 0f, new Vector2((float)(this._planetTexture.Width() >> 1), (float)(this._planetTexture.Height() >> 1)), 1f, SpriteEffects.None, 0f);
            }
            int num = -1;
            int num2 = 0;
            for (int i = 0; i < this._meteors.Length; i++)
            {
                float depth = this._meteors[i].Depth;
                if (num == -1 && depth < maxDepth)
                {
                    num = i;
                }
                if (depth <= minDepth)
                {
                    break;
                }
                num2 = i;
            }
            if (num == -1)
            {
                return;
            }
            float num3 = Math.Min(1f, (Main.screenPosition.Y - 1000f) / 1000f);
            Vector2 vector3 = Main.screenPosition + new Vector2((float)(Main.screenWidth >> 1), (float)(Main.screenHeight >> 1));
            Rectangle rectangle = new Rectangle(-1000, -1000, Main.screenWidth + 1000, Main.screenHeight + 1000);
            for (int j = num; j < num2; j++)
            {
                Vector2 vector4 = new Vector2(1f / this._meteors[j].Depth, 0.9f / this._meteors[j].Depth);
                Vector2 vector5 = (this._meteors[j].Position - vector3) * vector4 + vector3 - Main.screenPosition;
                int num4 = this._meteors[j].FrameCounter / 3;
                this._meteors[j].FrameCounter = (this._meteors[j].FrameCounter + 1) % 12;
                if (rectangle.Contains((int)vector5.X, (int)vector5.Y))
                {
                    spriteBatch.Draw(this._meteorTexture.Value, vector5, new Rectangle?(new Rectangle(0, num4 * (this._meteorTexture.Height() / 4), this._meteorTexture.Width(), this._meteorTexture.Height() / 4)), Color.White * num3 * this._fadeOpacity, 0f, Vector2.Zero, vector4.X * 5f * this._meteors[j].Scale, SpriteEffects.None, 0f);
                }
            }
        }
References Terraria.GameContent.Skies.SolarSky._bgTexture, Terraria.GameContent.Skies.SolarSky._fadeOpacity, Terraria.GameContent.Skies.SolarSky._meteors, Terraria.GameContent.Skies.SolarSky._meteorTexture, Terraria.GameContent.Skies.SolarSky._planetTexture, Microsoft.Xna.Framework.Color.Black, Terraria.GameContent.TextureAssets.BlackTile, Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.Depth, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), System.E, System.Math.Max(), Terraria.Main.maxTilesX, System.Math.Min(), Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.