Terraria Decompiled: Ionic.Zip.SharedUtilities.CreateAndOpenUniqueTempFile
CreateAndOpenUniqueTempFile()
static void Ionic.Zip.SharedUtilities.CreateAndOpenUniqueTempFile (string dir, out Stream fs, out string filename) inline static
Definition at line 364 of file SharedUtilities.cs.
        {
            for (int i = 0; i < 3; i++)
            {
                try
                {
                    filename = Path.Combine(dir, SharedUtilities.InternalGetTempFileName());
                    fs = new FileStream(filename, 1);
                    return;
                }
                catch (IOException)
                {
                    if (i == 2)
                    {
                        throw;
                    }
                }
            }
            throw new IOException();
        }
References System.IO.Path.Combine(), and Ionic.Zip.SharedUtilities.InternalGetTempFileName().
Referenced by Ionic.Zip.ZipSegmentedStream._SetWriteStream().