Terraria Decompiled: Ionic.Zip.SharedUtilities.FindSignature
FindSignature()
static long Ionic.Zip.SharedUtilities.FindSignature (Stream stream, int SignatureToFind) inline static package
Definition at line 160 of file SharedUtilities.cs.
        {
            long position = stream.Position;
            int num = 65536;
            byte[] array = new byte[]
            {
                (byte)(SignatureToFind >> 24),
                (byte)((SignatureToFind & 16711680) >> 16),
                (byte)((SignatureToFind & 65280) >> 8),
                (byte)(SignatureToFind & 255)
            };
            byte[] array2 = new byte[num];
            bool flag = false;
            do
            {
                int num2 = stream.Read(array2, 0, array2.Length);
                if (num2 == 0)
                {
                    break;
                }
                for (int i = 0; i < num2; i++)
                {
                    if (array2[i] == array[3])
                    {
                        long position2 = stream.Position;
                        stream.Seek((long)(i - num2), 1);
                        SharedUtilities.Workaround_Ladybug318918(stream);
                        int num3 = SharedUtilities.ReadSignature(stream);
                        flag = num3 == SignatureToFind;
                        if (flag)
{
                            break;
                        }
                        stream.Seek(position2, 0);
                        SharedUtilities.Workaround_Ladybug318918(stream);
                    }
                }
            }
            while (!flag);
            if (!flag)
            {
                stream.Seek(position, 0);
                SharedUtilities.Workaround_Ladybug318918(stream);
                return -1L;
            }
            return stream.Position - position - 4L;
        }
References System.array, System.L, System.IO.Stream.Position, System.IO.Stream.Read(), Ionic.Zip.SharedUtilities.ReadSignature(), System.IO.Stream.Seek(), and Ionic.Zip.SharedUtilities.Workaround_Ladybug318918().
Referenced by Ionic.Zip.ZipInputStream.GetNextEntry(), Ionic.Zip.ZipEntry.ReadHeader(), and Ionic.Zip.ZipFile.ReadIntoInstance().