Terraria Decompiled: Ionic.Zip.SharedUtilities.PackedToDateTime
PackedToDateTime()
static DateTime Ionic.Zip.SharedUtilities.PackedToDateTime (int packedDateTime) inline static package
Definition at line 228 of file SharedUtilities.cs.
        {
            if (packedDateTime == 65535 || packedDateTime == 0)
            {
                return new DateTime(1995, 1, 1, 0, 0, 0, 0);
            }
            short num = (short)(packedDateTime & 65535);
            short num2 = (short)(((long)packedDateTime & (long)((ulong)(-65536))) >> 16);
            int i = 1980 + (((int)num2 & 65024) >> 9);
            int j = (num2 & 480) >> 5;
            int k = (int)(num2 & 31);
            int num3 = ((int)num & 63488) >> 11;
            int l = (num & 2016) >> 5;
            int m = (int)((num & 31) * 2);
            if (m >= 60)
            {
                l++;
                m = 0;
            }
            if (l >= 60)
            {
                num3++;
                l = 0;
            }
            if (num3 >= 24)
            {
                k++;
                num3 = 0;
            }
            DateTime dateTime = DateTime.Now;
            bool flag = false;
            try
            {
                dateTime = new DateTime(i, j, k, num3, l, m, 0);
                flag = true;
            }
            catch (ArgumentOutOfRangeException)
            {
                if (i == 1980)
                {
                    if (j != 0)
                    {
                        if (k != 0)
{
                            goto IL_0111;
                        }
                    }
                    try
                    {
                        dateTime = new DateTime(1980, 1, 1, num3, l, m, 0);
                        flag = true;
                        goto IL_01AD;
                    }
                    catch (ArgumentOutOfRangeException)
                    {
                        try
{
                            dateTime = new DateTime(1980, 1, 1, 0, 0, 0, 0);
                            flag = true;
                        }
                        catch (ArgumentOutOfRangeException)
{
                        }
                        goto IL_01AD;
                    }
                }
                try
                {
                    IL_0111:
                    while (i < 1980)
                    {
                        i++;
                    }
                    while (i > 2030)
                    {
                        i--;
                    }
                    while (j < 1)
                    {
                        j++;
                    }
                    while (j > 12)
                    {
                        j--;
                    }
                    while (k < 1)
                    {
                        k++;
                    }
                    while (k > 28)
                    {
                        k--;
                    }
                    while (l < 0)
                    {
                        l++;
                    }
                    while (l > 59)
                    {
                        l--;
                    }
                    while (m < 0)
                    {
                        m++;
                    }
                    while (m > 59)
                    {
                        m--;
                    }
                    dateTime = new DateTime(i, j, k, num3, l, m, 0);
                    flag = true;
                }
                catch (ArgumentOutOfRangeException)
                {
                }
                IL_01AD:;
            }
            if (!flag)
            {
                string text = string.Format("y({0}) m({1}) d({2}) h({3}) m({4}) s({5})", new object[] { i, j, k, num3, l, m });
                throw new ZipException(string.Format("Bad date/time format in the zip file. ({0})", text));
            }
            dateTime = DateTime.SpecifyKind(dateTime, 2);
            return dateTime;
        }
References System.DateTime, System.Format, int, long, System.DateTime.Now, System.DateTime.SpecifyKind(), and System.text.
Referenced by Ionic.Zip.ZipEntry.ReadDirEntry(), and Ionic.Zip.ZipEntry.ReadHeader().