Terraria Decompiled: Ionic.Zip.SharedUtilities.Workaround_Ladybug318918
Workaround_Ladybug318918()
static void Ionic.Zip.SharedUtilities.Workaround_Ladybug318918 (Stream s) inline static
Definition at line 31 of file SharedUtilities.cs.
        {
            s.Flush();
        }
References System.s.
Referenced by Ionic.Zip.ZipEntry.ExtractOne(), Ionic.Zip.SharedUtilities.FindSignature(), Ionic.Zip.ZipInputStream.GetNextEntry(), Ionic.Zip.ZipEntry.HandlePK00Prefix(), Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor(), Ionic.Zip.ZipEntry.InternalOpenReader(), Ionic.Zip.ZipEntry.PostProcessOutput(), Ionic.Zip.ZipInputStream.Read(), Ionic.Zip.ZipEntry.ReadDirEntry(), Ionic.Zip.ZipEntry.ReadEntry(), Ionic.Zip.SharedUtilities.ReadEntrySignature(), Ionic.Zip.ZipEntry.ReadExtraField(), Ionic.Zip.ZipEntry.ReadHeader(), Ionic.Zip.ZipInputStream.Seek(), Ionic.Zip.ZipSegmentedStream.Seek(), Ionic.Zip.ZipEntry.SetFdpLoh(), Ionic.Zip.ZipEntry.SetupCryptoForExtract(), and Ionic.Zip.ZipSegmentedStream.TruncateBackward().