Terraria Decompiled: Ionic.Zip.SharedUtilities.NormalizePathForUseInZipFile
NormalizePathForUseInZipFile()
static string Ionic.Zip.SharedUtilities.NormalizePathForUseInZipFile (string pathName) inline static
Definition at line 49 of file SharedUtilities.cs.
        {
            if (string.IsNullOrEmpty(pathName))
            {
                return pathName;
            }
            if (pathName.Length >= 2 && pathName.get_Chars(1) == ':' && pathName.get_Chars(2) == '\\')
            {
                pathName = pathName.Substring(3);
            }
            pathName = pathName.Replace('\\', '/');
            while (pathName.StartsWith("/"))
            {
                pathName = pathName.Substring(1);
            }
            return SharedUtilities.SimplifyFwdSlashPath(pathName);
        }
References Ionic.Zip.SharedUtilities.SimplifyFwdSlashPath().
Referenced by Ionic.Zip.ZipFile.ContainsEntry(), Ionic.Zip.ZipOutputStream.ContainsEntry(), Ionic.Zip.ZipEntry.Create(), Ionic.Zip.ZipEntry.NameInArchive(), and Ionic.Zip.ZipFile.RemoveEntry().