Terraria Decompiled: Ionic.Zip.SharedUtilities.ReadInt
ReadInt()
static int Ionic.Zip.SharedUtilities.ReadInt (Stream s) inline static package
Definition at line 138 of file SharedUtilities.cs.
        {
            return SharedUtilities._ReadFourBytes(s, "Could not read block - no data!  (position 0x{0:X8})");
        }
References Ionic.Zip.SharedUtilities._ReadFourBytes(), and System.s.
Referenced by Ionic.Zip.ZipEntry.HandlePK00Prefix(), Ionic.Zip.ZipEntry.HandleUnexpectedDataDescriptor(), Ionic.Zip.ZipFile.ReadFirstFourBytes(), and Ionic.Zip.ZipFile.Zip64SeekToCentralDirectory().