Terraria Decompiled: Ionic.Zip.SharedUtilities.DateTimeToPacked
DateTimeToPacked()
static int Ionic.Zip.SharedUtilities.DateTimeToPacked (DateTime time) inline static package
Definition at line 355 of file SharedUtilities.cs.
        {
            time = time.ToLocalTime();
            ushort num = (ushort)((time.Day & 31) | ((time.Month << 5) & 480) | ((time.Year - 1980 << 9) & 65024));
            ushort num2 = (ushort)(((time.Second / 2) & 31) | ((time.Minute << 5) & 2016) | ((time.Hour << 11) & 63488));
            return ((int)num << 16) | (int)num2;
        }
References System.DateTime.Day, System.DateTime.Hour, System.DateTime.Minute, System.DateTime.Second, and System.DateTime.ToLocalTime().
Referenced by Ionic.Zip.ZipEntry.WriteHeader(), and Ionic.Zip.ZipEntry.WriteSecurityMetadata().