Terraria Decompiled: Terraria.GameContent.LucyAxeMessage.GetTextForVariation
GetTextForVariation()
static string Terraria.GameContent.LucyAxeMessage.GetTextForVariation (LucyAxeMessage::MessageSource source, int variationUnwrapped) inline static private
Definition at line 183 of file LucyAxeMessage.cs.
        {
            string categoryName = LucyAxeMessage.GetCategoryName(source);
            return LanguageManager.Instance.IndexedFromCategory(categoryName, variationUnwrapped).Value;
        }
References Terraria.GameContent.LucyAxeMessage.GetCategoryName(), Terraria.Localization.LanguageManager.IndexedFromCategory(), Terraria.Localization.LanguageManager.Instance, System.source, and Terraria.Localization.LocalizedText.Value.
Referenced by Terraria.GameContent.LucyAxeMessage.SpawnPopupText().