Terraria Decompiled: Terraria.IO.FileMetadata.Read
Read() [1/2]
void Terraria.IO.FileMetadata.Read (BinaryReader reader) inline private
Definition at line 60 of file FileMetadata.cs.
        {
            ulong num = reader.ReadUInt64();
            if ((num & 72057594037927935UL) != 27981915666277746UL)
            {
                throw new FormatException("Expected Re-Logic file format.");
            }
            byte b = (byte)((num >> 56) & 255UL);
            FileType fileType = FileType.None;
            FileType[] array = (FileType[])Enum.GetValues(typeof(FileType));
            for (int i = 0; i < array.Length; i++)
            {
                if (array[i] == (FileType)b)
                {
                    fileType = array[i];
                    break;
                }
            }
            if (fileType == FileType.None)
            {
                throw new FormatException("Found invalid file type.");
            }
            this.Type = fileType;
            this.Revision = reader.ReadUInt32();
            ulong num2 = reader.ReadUInt64();
            this.IsFavorite = (num2 & 1UL) == 1UL;
        }
References System.array, System.Enum.GetValues(), System.IO.BinaryReader.ReadUInt32(), and System.IO.BinaryReader.ReadUInt64().