Terraria Decompiled: Terraria.IO.FileMetadata.FromCurrentSettings
FromCurrentSettings()
static FileMetadata Terraria.IO.FileMetadata.FromCurrentSettings (FileType type) inline static
Definition at line 30 of file FileMetadata.cs.
        {
            return new FileMetadata
            {
                Type = type,
                Revision = 0U,
                IsFavorite = false
            };
        }
References Terraria.IO.FileMetadata.IsFavorite, Terraria.IO.FileMetadata.Revision, and System.U.
Referenced by Terraria.IO.PlayerFileData.CreateAndSave(), Terraria.IO.WorldFile.CreateMetadata(), Terraria.WorldGen.Finish(), Terraria.IO.WorldFileData.FromInvalidWorld(), Terraria.IO.WorldFile.GetAllMetadata(), Terraria.IO.WorldFile.GetFileMetadata(), Terraria.Map.WorldMap.Load(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.Player.LoadPlayer(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), and Terraria.Testing.QuickLoad.JoinWorld.WithCurrentState().