Terraria Decompiled: Terraria.IO.FileMetadata.Read
Read() [2/2]
static FileMetadata Terraria.IO.FileMetadata.Read (BinaryReader reader, FileType expectedType) inline static
Definition at line 41 of file FileMetadata.cs.
        {
            FileMetadata fileMetadata = new FileMetadata();
            fileMetadata.Read(reader);
            if (fileMetadata.Type != expectedType)
            {
                throw new FormatException(string.Concat(new string[]
                {
                    "Expected type \"",
                    Enum.GetName(typeof(FileType), expectedType),
                    "\" but found \"",
                    Enum.GetName(typeof(FileType), fileMetadata.Type),
                    "\"."
                }));
            }
            return fileMetadata;
        }
References Terraria.IO.FileMetadata.FileMetadata(), System.Enum.GetName(), Terraria.IO.FileMetadata.Read(), and Terraria.IO.FileMetadata.Type.
Referenced by Terraria.IO.WorldFile.GetAllMetadata(), Terraria.IO.WorldFile.GetFileMetadata(), Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.Map.MapHelper.LoadMapVersion2(), Terraria.Map.MapHelper.LoadMapVersionCompressed(), Terraria.Player.LoadPlayer(), and Terraria.IO.FileMetadata.Read().