Terraria Decompiled: System.Threading.Tasks.TaskFactory.CompleteOnCountdownPromise.Invoke
Invoke() [2/2]
void System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >.Invoke (Task completingTask) inline
Implements System.Threading.Tasks.ITaskCompletionAction.
Definition at line 936 of file TaskFactory.2.cs.
            {
                if (DebuggerSupport.LoggingOn)
                {
                    DebuggerSupport.TraceOperationRelation(CausalityTraceLevel.Important, this, CausalityRelation.Join);
                }
                if (completingTask.IsWaitNotificationEnabled)
                {
                    base.SetNotificationForWaitCompletion(true);
                }
                if (Interlocked.Decrement(ref this._count) == 0)
                {
                    if (DebuggerSupport.LoggingOn)
                    {
                        DebuggerSupport.TraceOperationCompletion(CausalityTraceLevel.Required, this, AsyncStatus.Completed);
                    }
                    DebuggerSupport.RemoveFromActiveTasks(this);
                    base.TrySetResult(this._tasks);
                }
            }
References System.Threading.Tasks.TaskFactory< TResult >.CompleteOnCountdownPromise< T >._tasks, System.Threading.Interlocked.Decrement(), System.Threading.Tasks.Task< TResult >.IsWaitNotificationEnabled, System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.DebuggerSupport.RemoveFromActiveTasks(), System.Threading.Tasks.DebuggerSupport.TraceOperationCompletion(), and System.Threading.Tasks.DebuggerSupport.TraceOperationRelation().