Terraria Decompiled: System.Runtime.Remoting.Proxies.TransparentProxy.StoreRemoteField
StoreRemoteField()
void System.Runtime.Remoting.Proxies.TransparentProxy.StoreRemoteField (IntPtr classPtr, IntPtr fieldPtr, object arg) inline package
Definition at line 80 of file TransparentProxy.cs.
        {
            RuntimeClassHandle runtimeClassHandle = new RuntimeClassHandle(classPtr);
            RuntimeFieldHandle runtimeFieldHandle = new RuntimeFieldHandle(fieldPtr);
            RuntimeTypeHandle typeHandle = runtimeClassHandle.GetTypeHandle();
            FieldInfo fieldFromHandle = FieldInfo.GetFieldFromHandle(runtimeFieldHandle);
            if (this.InCurrentContext())
            {
                object server = this._rp._server;
                fieldFromHandle.SetValue(server, arg);
                return;
            }
            string fullName = Type.GetTypeFromHandle(typeHandle).FullName;
            string name = fieldFromHandle.Name;
            object[] array = new object[] { fullName, name, arg };
            MethodInfo method = typeof(object).GetMethod("FieldSetter", BindingFlags.Instance | BindingFlags.NonPublic);
            if (method == null)
            {
                throw new MissingMethodException("System.Object", "FieldSetter");
            }
            MonoMethodMessage monoMethodMessage = new MonoMethodMessage(method, array, null);
            Exception ex;
            object[] array2;
            RealProxy.PrivateInvoke(this._rp, monoMethodMessage, out ex, out array2);
            if (ex != null)
            {
                throw ex;
            }
        }
References System.Runtime.Remoting.Proxies.TransparentProxy._rp, System.Runtime.Remoting.Proxies.RealProxy._server, System.array, System.Type.FullName, System.Reflection.FieldInfo.GetFieldFromHandle(), System.Type.GetTypeFromHandle(), Mono.RuntimeClassHandle.GetTypeHandle(), System.Runtime.Remoting.Proxies.TransparentProxy.InCurrentContext(), System.name, System.Reflection.MemberInfo.Name, System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(), and System.Reflection.FieldInfo.SetValue().