Terraria Decompiled: Terraria.Localization.Language.GetText
GetText()
static LocalizedText Terraria.Localization.Language.GetText (string key) inline static
Definition at line 21 of file Language.cs.
        {
            return LanguageManager.Instance.GetText(key);
        }
References Terraria.Localization.LanguageManager.GetText(), Terraria.Localization.LanguageManager.Instance, and System.key.
Referenced by Terraria.Achievements.Achievement.Achievement(), Terraria.DataStructures.ArmorSetBonus.Builder.Add(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.AddBackAndFolderButtons(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddBackButton(), Terraria.Chat.ChatCommandProcessor.AddCommand< T >(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorkshopHub.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreation.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddDescriptionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddPublishButton(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSeedButtons(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), Terraria.GameContent.UI.Elements.UIBestiarySortingOptionsGrid.BuildGrid(), Terraria.Lang.BuildMapAtlas(), Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents(), Terraria.GameContent.UI.States.UIVirtualKeyboard.BuildSpaceBarArea(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorkshopHub.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.ClearOptionDescription(), Terraria.Chat.Commands.HelpCommand.ComposeMessage(), Terraria.GameContent.UI.States.UIManageControls.controllerGlyphStyle(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateInsturctionsPanel(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.CreatePackToggleButton(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePreviewImageSelectionPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreatePublicSettingsRow(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateSteamDisclaimer(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateStylizedCategoryPanel(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.CreateTagOptionsPanel(), Terraria.GameContent.Bestiary.CustomEntryIcon.CustomEntryIcon(), Terraria.Main.DedServ(), Terraria.Main.DrawMenu(), Terraria.GameContent.Events.DD2Event.FailureMessage(), Terraria.Lang.FillNameCacheArray< IdClass, IdType >(), Terraria.GameContent.UI.GameTipsDisplay.GameTip.GameTip(), Terraria.GameContent.Bestiary.BossBestiaryInfoElement.GetSearchString(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.GetSearchString(), Terraria.GameContent.Bestiary.NamePlateInfoElement.GetSearchString(), Terraria.GameContent.Bestiary.RareSpawnBestiaryInfoElement.GetSearchString(), Terraria.Main.HelpText(), Terraria.Lang.if(), Terraria.Lang.InitializeLegacyLocalization(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.InvasionDamageTracker.InvasionDamageTracker(), Terraria.UI.ItemTooltip.ItemTooltip(), Terraria.WorldBuilding.AWorldGenerationOption.Load(), Terraria.GameContent.Animations.Segments.LocalizedTextSegment.LocalizedTextSegment(), Terraria.GameContent.UI.States.UICharacterCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreation.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.MakeBackAndCreatebuttons(), Terraria.GameContent.UI.States.UIBestiaryTest.MakeExitButton(), Terraria.GameContent.UI.States.UIWorkshopHub.MakeFancyButton(), Terraria.GameContent.UI.States.UICharacterCreation.MakeInfoMenu(), Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), Terraria.GameContent.NPCDamageTracker.NPCDamageTracker(), Terraria.GameContent.OneTimeDialogue.OneTimeDialogue(), Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopHub.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnInitialize(), Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize(), Terraria.Chat.Commands.EmojiCommand.PrepareAliases(), Terraria.GameContent.Creative.CreativePowers.ModifyWindDirectionAndStrength.ProvideSlider(), Terraria.GameContent.Creative.CreativePowers.ModifyRainPower.ProvideSlider(), Terraria.GameContent.Bestiary.FilterProviderInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.FlavorTextBestiaryInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.NamePlateInfoElement.ProvideUIElement(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ProvideUIElement(), Terraria.IO.WorldFileData.SetWorldSize(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorkshopHub.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ShowSecretSeedDescription(), Terraria.Main.startDedInputCallBack(), Terraria.GameContent.UI.Elements.UICharacterNameButton.UICharacterNameButton(), Terraria.GameContent.UI.States.UIVirtualKeyboard.UIVirtualKeyboard(), Terraria.GameContent.UI.Elements.UIWorkshopPublishResourcePackListItem.UIWorkshopPublishResourcePackListItem(), Terraria.GameContent.UI.Elements.UIWorkshopPublishWorldListItem.UIWorkshopPublishWorldListItem(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.UIWrappedSearchBar(), Terraria.GameContent.UI.States.UICharacterCreation.UpdateDifficultyDescription(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.UpdateTitles(), and Terraria.RecipeGroup.WithDefaultCombineFormat().