Terraria Decompiled: System.IO.TextReader.d__20.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.TextReader.d__20.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 643 of file TextReader.cs.
            {
                int num2;
                int num = num2;
                TextReader textReader = this;
                int num3;
                try
                {
                    ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                    if (num == 0)
                    {
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        goto IL_0094;
                    }
                    i = 0;
                    IL_0018:
                    configuredValueTaskAwaiter = textReader.ReadAsyncInternal(buffer.Slice(i), cancellationToken).ConfigureAwait(false).GetAwaiter();
                    if (!configuredValueTaskAwaiter.IsCompleted)
                    {
                        num2 = 0;
                        ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, TextReader.<ReadBlockAsyncInternal>d__20>(ref configuredValueTaskAwaiter, ref this);
                        return;
                    }
                    IL_0094:
                    int result = configuredValueTaskAwaiter.GetResult();
                    i += result;
                    if (result > 0 && i < buffer.Length)
                    {
                        goto IL_0018;
                    }
                    num3 = i;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult(num3);
            }
References System.Memory< T >.Length, System.IO.TextReader.ReadAsyncInternal(), System.IO.TextReader.ReadBlockAsyncInternal(), and System.Memory< T >.Slice().