Terraria Decompiled: System.IO.BufferedStream.d__71.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.BufferedStream.d__71.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1900 of file BufferedStream.cs.
            {
                int num2;
                int num = num2;
                BufferedStream bufferedStream = this;
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                    if (num != 0)
                    {
                        if (num - 1 <= 2)
{
                            goto IL_0080;
                        }
                        configuredTaskAwaiter = bufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized().WaitAsync().ConfigureAwait(false)
                            .GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<CopyToAsyncCore>d__71>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                        num = (num2 = -1);
                    }
                    configuredTaskAwaiter.GetResult();
                    IL_0080:
                    try
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                        switch (num)
{
                        case 1:
{
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                            configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                            num = (num2 = -1);
                            break;
                        }
                        case 2:
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_01B6;
                        case 3:
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                            goto IL_022E;
                        default:
{
                            int num3 = bufferedStream._readLen - bufferedStream._readPos;
                            if (num3 > 0)
{
                                configuredValueTaskAwaiter = destination.WriteAsync(new ReadOnlyMemory<byte>(bufferedStream._buffer, bufferedStream._readPos, num3), cancellationToken).ConfigureAwait(false).GetAwaiter();
                                if (!configuredValueTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 1);
                                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<CopyToAsyncCore>d__71>(ref configuredValueTaskAwaiter, ref this);
                                    return;
                                }
                            }
                            else
{
                                if (bufferedStream._writePos <= 0)
{
                                    goto IL_01BD;
                                }
                                configuredTaskAwaiter = bufferedStream.FlushWriteAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                                if (!configuredTaskAwaiter.IsCompleted)
{
                                    num = (num2 = 2);
                                    configuredTaskAwaiter2 = configuredTaskAwaiter;
                                    this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<CopyToAsyncCore>d__71>(ref configuredTaskAwaiter, ref this);
                                    return;
                                }
                                goto IL_01B6;
                            }
                            break;
                        }
                        }
                        configuredValueTaskAwaiter.GetResult();
                        bufferedStream._readPos = (bufferedStream._readLen = 0);
                        goto IL_01BD;
                        IL_01B6:
                        configuredTaskAwaiter.GetResult();
                        IL_01BD:
                        configuredTaskAwaiter = bufferedStream._stream.CopyToAsync(destination, bufferSize, cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            num = (num2 = 3);
                            configuredTaskAwaiter2 = configuredTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<CopyToAsyncCore>d__71>(ref configuredTaskAwaiter, ref this);
                            return;
                        }
                        IL_022E:
                        configuredTaskAwaiter.GetResult();
                    }
                    finally
                    {
                        if (num < 0)
{
                            bufferedStream._asyncActiveSemaphore.Release();
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.IO.BufferedStream._asyncActiveSemaphore, System.IO.BufferedStream._buffer, System.IO.BufferedStream._readPos, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.CopyToAsync(), System.IO.BufferedStream.CopyToAsyncCore(), System.destination, System.IO.BufferedStream.FlushWriteAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, System.IO.BufferedStream.LazyEnsureAsyncActiveSemaphoreInitialized(), System.Threading.SemaphoreSlim.Release(), and System.Threading.SemaphoreSlim.WaitAsync().