Terraria Decompiled: Terraria.WorldGen.Spread.Wall2
Wall2()
static void Terraria.WorldGen.Spread.Wall2 (int x, int y, int wallType) inline static
Definition at line 91947 of file WorldGen.cs.
            {
                if (!WorldGen.InWorld(x, y, 0))
                {
                    return;
                }
                ushort num = (ushort)wallType;
                int num2 = 0;
                int maxWallOut = WorldGen.maxWallOut2;
                List<Point> list = new List<Point>();
                List<Point> list2 = new List<Point>();
                HashSet<Point> hashSet = new HashSet<Point>();
                list2.Add(new Point(x, y));
                while (list2.Count > 0)
                {
                    list.Clear();
                    list.AddRange(list2);
                    list2.Clear();
                    while (list.Count > 0)
                    {
                        Point point = list[0];
                        if (!WorldGen.InWorld(point.X, point.Y, 1))
{
                            list.Remove(point);
                        }
                        else
{
                            hashSet.Add(point);
                            list.Remove(point);
                            Tile tile = Main.tile[point.X, point.Y];
                            if (tile.wall != num && !WallID.Sets.CannotBeReplacedByWallSpread[(int)tile.wall])
{
                                if (!WorldGen.SolidTile(point.X, point.Y, false))
{
                                    bool flag = WallID.Sets.WallSpreadStopsAtAir[(int)num];
                                    if (flag && tile.wall == 0)
{
                                        list.Remove(point);
                                    }
                                    else
{
                                        num2++;
                                        if (num2 >= maxWallOut)
{
                                            list.Remove(point);
                                        }
                                        else
{
                                            tile.wall = num;
                                            Point point2 = new Point(point.X - 1, point.Y);
                                            if (!hashSet.Contains(point2))
{
                                                list2.Add(point2);
                                            }
                                            point2 = new Point(point.X + 1, point.Y);
                                            if (!hashSet.Contains(point2))
{
                                                list2.Add(point2);
                                            }
                                            point2 = new Point(point.X, point.Y - 1);
                                            if (!hashSet.Contains(point2))
{
                                                list2.Add(point2);
                                            }
                                            point2 = new Point(point.X, point.Y + 1);
                                            if (!hashSet.Contains(point2))
{
                                                list2.Add(point2);
                                            }
                                            if (flag)
{
                                                point2 = new Point(point.X - 1, point.Y - 1);
                                                if (!hashSet.Contains(point2))
{
                                                    list2.Add(point2);
                                                }
                                                point2 = new Point(point.X + 1, point.Y - 1);
                                                if (!hashSet.Contains(point2))
{
                                                    list2.Add(point2);
                                                }
                                                point2 = new Point(point.X - 1, point.Y + 1);
                                                if (!hashSet.Contains(point2))
{
                                                    list2.Add(point2);
                                                }
                                                point2 = new Point(point.X + 1, point.Y + 1);
                                                if (!hashSet.Contains(point2))
{
                                                    list2.Add(point2);
                                                }
                                                point2 = new Point(point.X - 2, point.Y);
                                                if (!hashSet.Contains(point2))
{
                                                    list2.Add(point2);
                                                }
                                                point2 = new Point(point.X + 2, point.Y);
                                                if (!hashSet.Contains(point2))
{
                                                    list2.Add(point2);
                                                }
                                            }
                                        }
                                    }
                                }
                                else if (tile.active())
{
                                    tile.wall = num;
                                }
                            }
                        }
                    }
                }
            }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.WallID.Sets.CannotBeReplacedByWallSpread, System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, int, Terraria.WorldGen.InWorld(), System.list, Terraria.WorldGen.maxWallOut2, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.wall, Terraria.ID.WallID.Sets.WallSpreadStopsAtAir, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.FinishNotTheBees().