Terraria Decompiled: Terraria.WorldGen.Spread.Wall
Wall()
static void Terraria.WorldGen.Spread.Wall (int x, int y, int wallType) inline static
Definition at line 91882 of file WorldGen.cs.
            {
                if (!WorldGen.InWorld(x, y, 0))
                {
                    return;
                }
                ushort num = (ushort)wallType;
                List<Point> list = new List<Point>();
                List<Point> list2 = new List<Point>();
                HashSet<Point> hashSet = new HashSet<Point>();
                list2.Add(new Point(x, y));
                while (list2.Count > 0)
                {
                    list.Clear();
                    list.AddRange(list2);
                    list2.Clear();
                    while (list.Count > 0)
                    {
                        Point point = list[0];
                        if (!WorldGen.InWorld(point.X, point.Y, 1))
{
                            list.Remove(point);
                        }
                        else
{
                            hashSet.Add(point);
                            list.Remove(point);
                            Tile tile = Main.tile[point.X, point.Y];
                            if (WorldGen.SolidTile(point.X, point.Y, false) || tile.wall != 0)
{
                                if (tile.active() && tile.wall == 0)
{
                                    tile.wall = num;
                                }
                            }
                            else
{
                                tile.wall = num;
                                Point point2 = new Point(point.X - 1, point.Y);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X + 1, point.Y);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X, point.Y - 1);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X, point.Y + 1);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                            }
                        }
                    }
                }
            }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.WorldGen.InWorld(), System.list, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.