Terraria Decompiled: Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend
AlphaBlend
readonly BlendState Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend = new BlendState("BlendState.AlphaBlend", Blend.One, Blend.One, Blend.InverseSourceAlpha, Blend.InverseSourceAlpha) static
Definition at line 236 of file BlendState.cs.
Referenced by Terraria.GameContent.Animations.Segments.PlayerSegment.ImmediateSpritebatchForPlayerDyesEffect.AfterDrawing(), Terraria.GameContent.Animations.Segments.SpriteSegment.MaskedFadeEffect.AfterDrawing(), Terraria.GameContent.Animations.Segments.PlayerSegment.ImmediateSpritebatchForPlayerDyesEffect.BeforeDrawing(), Terraria.GameContent.Animations.Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.GameContent.Drawing.TileDrawingBase.Begin(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Main.DoDraw_DrawNPCsBehindTiles(), Terraria.Main.DoDraw_DrawNPCsOverTiles(), Terraria.Main.DoDraw_Tiles_NonSolid(), Terraria.Main.DoDraw_Tiles_Solid(), Terraria.Main.DoDraw_WallsAndBlacks(), Terraria.Main.DoDraw_WallsTilesNPCs(), Terraria.Graphics.Capture.CaptureInterface.Draw(), Terraria.Testing.DebugLineDraw.Draw(), Terraria.UI.UIElement.Draw(), Terraria.UI.IngameFancyUI.Draw(), Terraria.Graphics.Effects.OverlayManager.Draw(), Terraria.Main.DrawBlack(), Terraria.Main.DrawCachedProjs(), Terraria.Main.DrawDust(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_DisplayDolls(), Terraria.GameContent.Drawing.TileDrawing.DrawEntities_HatRacks(), Terraria.Main.DrawInterface_12_IngameFancyUI(), Terraria.Main.DrawInterface_36_Cursor(), Terraria.Main.DrawMap(), Terraria.Main.DrawMenu(), Terraria.Main.DrawNPCDirect(), Terraria.Main.DrawNPCDirect_HallowBoss(), Terraria.Main.DrawPendingMouseText(), Terraria.Graphics.Renderers.LegacyPlayerRenderer.DrawPlayerFull(), Terraria.Main.DrawProj_LightsBane(), Terraria.Main.DrawProjectiles(), Terraria.Graphics.Renderers.ReturnGatePlayerRenderer.DrawReturnGateInWorld(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallbackWithoutCondition(), Terraria.Main.DrawSuperSpecialProjectiles(), Terraria.Graphics.Capture.CaptureCamera.DrawTick(), Terraria.MapRenderer.DrawToMap_Section(), Terraria.Main.DrawWallOfStars(), Terraria.Graphics.Effects.FilterManager.EndCapture(), Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.EndDrawingSelection(), Terraria.Main.GUIBarsDrawInner(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), Terraria.GameContent.PlayerQueenSlimeMountTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerRainbowWingsTextureContent.HandleUseRequest(), Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseRequest(), Terraria.GameContent.Drawing.TileDrawing.PostDrawTiles(), Terraria.Main.PrepareDrawnEntityDrawing(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary(), Terraria.Graphics.Capture.CaptureInterface.CaptureInterfaceMode.StartDrawingSelection(), and Terraria.GameContent.Drawing.HorizonHelper.UpdateSunVisibility().