Terraria Decompiled: System.AppDomainSetup.GetAppBase
GetAppBase()
static string System.AppDomainSetup.GetAppBase (string appBase) inline static private
Definition at line 67 of file AppDomainSetup.cs.
        {
            if (appBase == null)
            {
                return null;
            }
            if (appBase.StartsWith("file://", StringComparison.OrdinalIgnoreCase))
            {
                appBase = new Uri(appBase).LocalPath;
                if (Path.DirectorySeparatorChar != '/')
                {
                    appBase = appBase.Replace('/', Path.DirectorySeparatorChar);
                }
            }
            appBase = Path.GetFullPath(appBase);
            if (Path.DirectorySeparatorChar != '/')
            {
                bool flag = appBase.StartsWith("\\\\?\\", StringComparison.Ordinal);
                if (appBase.IndexOf(':', flag ? 6 : 2) != -1)
                {
                    throw new NotSupportedException("The given path's format is not supported.");
                }
            }
            string directoryName = Path.GetDirectoryName(appBase);
            if (directoryName != null && directoryName.LastIndexOfAny(Path.GetInvalidPathChars()) >= 0)
            {
                throw new ArgumentException(string.Format(Locale.GetText("Invalid path characters in path: '{0}'"), appBase), "appBase");
            }
            string fileName = Path.GetFileName(appBase);
            if (fileName != null && fileName.LastIndexOfAny(Path.GetInvalidFileNameChars()) >= 0)
            {
                throw new ArgumentException(string.Format(Locale.GetText("Invalid filename characters in path: '{0}'"), appBase), "appBase");
            }
            return appBase;
        }
References System.IO.Path.DirectorySeparatorChar, System.Format, System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), System.IO.Path.GetFullPath(), System.IO.Path.GetInvalidFileNameChars(), Locale.GetText(), and Mono.Security.Uri.LocalPath.