Terraria Decompiled: Terraria.Social.WeGame.CoreSocialModule.Initialize
Initialize()
void Terraria.Social.WeGame.CoreSocialModule.Initialize () inline
Implements Terraria.Social.ISocialModule.
Definition at line 53 of file CoreSocialModule.cs.
        {
            RailGameID railGameID = new RailGameID();
            railGameID.id_ = 2000328UL;
            string[] array;
            if (Main.dedServ)
            {
                array = Environment.GetCommandLineArgs();
            }
            else
            {
                array = new string[] { " " };
            }
            if (rail_api.RailNeedRestartAppForCheckingEnvironment(railGameID, array.Length, array))
            {
                Environment.Exit(1);
            }
            if (!rail_api.RailInitialize())
            {
                Environment.Exit(1);
            }
            this._callbackHelper.RegisterCallback(2, new RailEventCallBackHandler(CoreSocialModule.RailEventCallBack));
            this.isRailValid = true;
            ThreadPool.QueueUserWorkItem(new WaitCallback(this.TickThread), null);
            Main.OnTickForThirdPartySoftwareOnly += CoreSocialModule.RailEventTick;
        }
References Terraria.Social.WeGame.CoreSocialModule._callbackHelper, System.array, Terraria.Main.dedServ, System.Threading.ThreadPool.QueueUserWorkItem(), Terraria.Social.WeGame.CoreSocialModule.RailEventCallBack(), RailEventCallBackHandler(), Terraria.Social.WeGame.CoreSocialModule.RailEventTick(), rail.rail_api.RailInitialize(), rail.rail_api.RailNeedRestartAppForCheckingEnvironment(), rail.RailCallBackHelper.RegisterCallback(), Terraria.Social.WeGame.CoreSocialModule.TickThread(), and System.Threading.WaitCallback().