Terraria Decompiled: Terraria.Social.WeGame.CoreSocialModule.TickThread
TickThread()
void Terraria.Social.WeGame.CoreSocialModule.TickThread (object context) inline private
Definition at line 92 of file CoreSocialModule.cs.
        {
            Monitor.Enter(CoreSocialModule._railTickLock);
            while (this.isRailValid)
            {
                if (CoreSocialModule.OnTick != null)
                {
                    CoreSocialModule.OnTick();
                }
                Monitor.Wait(CoreSocialModule._railTickLock);
            }
            Monitor.Exit(CoreSocialModule._railTickLock);
        }
References Terraria.Social.WeGame.CoreSocialModule._railTickLock, System.Threading.Monitor.Enter(), System.Threading.Monitor.Exit(), Terraria.Social.WeGame.CoreSocialModule.isRailValid, Terraria.Social.WeGame.CoreSocialModule.OnTick, and System.Threading.Monitor.Wait().
Referenced by Terraria.Social.WeGame.CoreSocialModule.Initialize().