Terraria Decompiled: Terraria.Social.WeGame.CoreSocialModule.RailEventTick
RailEventTick()
static void Terraria.Social.WeGame.CoreSocialModule.RailEventTick () inline static
Definition at line 81 of file CoreSocialModule.cs.
        {
            rail_api.RailFireEvents();
            if (Monitor.TryEnter(CoreSocialModule._railTickLock))
            {
                Monitor.Pulse(CoreSocialModule._railTickLock);
                Monitor.Exit(CoreSocialModule._railTickLock);
            }
        }
References Terraria.Social.WeGame.CoreSocialModule._railTickLock, System.Threading.Monitor.Exit(), System.Threading.Monitor.Pulse(), rail.rail_api.RailFireEvents(), and System.Threading.Monitor.TryEnter().
Referenced by Terraria.Social.WeGame.AchievementsSocialModule.Initialize(), and Terraria.Social.WeGame.CoreSocialModule.Initialize().