Terraria Decompiled: System.Security.Permissions.KeyContainerPermission.Union
Union()
override IPermission System.Security.Permissions.KeyContainerPermission.Union (IPermission target) inline virtual
Reimplemented from System.Security.CodeAccessPermission.
Definition at line 118 of file KeyContainerPermission.cs.
        {
            KeyContainerPermission keyContainerPermission = this.Cast(target);
            if (keyContainerPermission == null)
            {
                return this.Copy();
            }
            KeyContainerPermissionAccessEntryCollection keyContainerPermissionAccessEntryCollection = new KeyContainerPermissionAccessEntryCollection();
            foreach (KeyContainerPermissionAccessEntry keyContainerPermissionAccessEntry in this._accessEntries)
            {
                keyContainerPermissionAccessEntryCollection.Add(keyContainerPermissionAccessEntry);
            }
            foreach (KeyContainerPermissionAccessEntry keyContainerPermissionAccessEntry2 in keyContainerPermission._accessEntries)
            {
                if (this._accessEntries.IndexOf(keyContainerPermissionAccessEntry2) == -1)
                {
                    keyContainerPermissionAccessEntryCollection.Add(keyContainerPermissionAccessEntry2);
                }
            }
            if (keyContainerPermissionAccessEntryCollection.Count == 0)
            {
                return new KeyContainerPermission(this._flags | keyContainerPermission._flags);
            }
            KeyContainerPermissionAccessEntry[] array = new KeyContainerPermissionAccessEntry[keyContainerPermissionAccessEntryCollection.Count];
            keyContainerPermissionAccessEntryCollection.CopyTo(array, 0);
            return new KeyContainerPermission(this._flags | keyContainerPermission._flags, array);
        }
References System.Security.Permissions.KeyContainerPermission._accessEntries, System.Security.Permissions.KeyContainerPermission._flags, System.array, System.Security.Permissions.KeyContainerPermission.Cast(), System.Security.Permissions.KeyContainerPermission.Copy(), System.Security.Permissions.KeyContainerPermissionAccessEntryCollection.IndexOf(), and System.Security.Permissions.KeyContainerPermission.KeyContainerPermission().