Terraria Decompiled: System.Security.Permissions.KeyContainerPermission.FromXml
FromXml()
override void System.Security.Permissions.KeyContainerPermission.FromXml (SecurityElement securityElement) inline
Implements System.Security.ISecurityEncodable.
Definition at line 74 of file KeyContainerPermission.cs.
        {
            CodeAccessPermission.CheckSecurityElement(securityElement, "securityElement", 1, 1);
            if (CodeAccessPermission.IsUnrestricted(securityElement))
            {
                this._flags = KeyContainerPermissionFlags.AllFlags;
                return;
            }
            this._flags = (KeyContainerPermissionFlags)Enum.Parse(typeof(KeyContainerPermissionFlags), securityElement.Attribute("Flags"));
        }
References System.Security.SecurityElement.Attribute(), System.Security.CodeAccessPermission.CheckSecurityElement(), System.Security.CodeAccessPermission.IsUnrestricted(), and System.Enum.Parse().