Terraria Decompiled: System.Security.Permissions.KeyContainerPermission.Cast
Cast()
KeyContainerPermission System.Security.Permissions.KeyContainerPermission.Cast (IPermission target) inline private
Definition at line 163 of file KeyContainerPermission.cs.
        {
            if (target == null)
            {
                return null;
            }
            KeyContainerPermission keyContainerPermission = target as KeyContainerPermission;
            if (keyContainerPermission == null)
            {
                CodeAccessPermission.ThrowInvalidPermission(target, typeof(KeyContainerPermission));
            }
            return keyContainerPermission;
        }
References System.Security.Permissions.KeyContainerPermission.KeyContainerPermission(), and System.Security.CodeAccessPermission.ThrowInvalidPermission().
Referenced by System.Security.Permissions.KeyContainerPermission.Union().