Terraria Decompiled: Terraria.WorldGen.GrowShroom
GrowShroom()
static bool Terraria.WorldGen.GrowShroom (int i, int y) inline static
Definition at line 28606 of file WorldGen.cs.
        {
            if (Main.tile[i - 1, y - 1].anyLava() || Main.tile[i - 1, y - 1].anyLava() || Main.tile[i + 1, y - 1].anyLava())
            {
                return false;
            }
            if (Main.tile[i, y].nactive() && Main.tile[i, y].type == 70 && Main.tile[i, y - 1].wall == 0 && Main.tile[i - 1, y].active() && Main.tile[i - 1, y].type == 70 && Main.tile[i + 1, y].active() && Main.tile[i + 1, y].type == 70 && WorldGen.EmptyTileCheck(i - 2, i + 2, y - 13, y - 3, 71) && WorldGen.EmptyTileCheck(i - 1, i + 1, y - 3, y - 1, 71))
            {
                if (WorldGen.isGeneratingOrLoadingWorld && WorldGen.genRand.Next(3) != 0)
                {
                    Main.tile[i, y].halfBrick(false);
                    Main.tile[i, y].slope(0);
                }
                if (!Main.tile[i, y].halfBrick() && Main.tile[i, y].slope() == 0)
                {
                    int num = WorldGen.genRand.Next(4, 11);
                    for (int j = y - num; j < y; j++)
                    {
                        Main.tile[i, j].active(true);
                        Main.tile[i, j].type = 72;
                        int num2 = WorldGen.genRand.Next(3);
                        if (num2 == 0)
{
                            Main.tile[i, j].frameX = 0;
                            Main.tile[i, j].frameY = 0;
                        }
                        if (num2 == 1)
{
                            Main.tile[i, j].frameX = 0;
                            Main.tile[i, j].frameY = 18;
                        }
                        if (num2 == 2)
{
                            Main.tile[i, j].frameX = 0;
                            Main.tile[i, j].frameY = 36;
                        }
                    }
                    int num3 = WorldGen.genRand.Next(3);
                    if (num3 == 0)
                    {
                        Main.tile[i, y - num].frameX = 36;
                        Main.tile[i, y - num].frameY = 0;
                    }
                    if (num3 == 1)
                    {
                        Main.tile[i, y - num].frameX = 36;
                        Main.tile[i, y - num].frameY = 18;
                    }
                    if (num3 == 2)
                    {
                        Main.tile[i, y - num].frameX = 36;
                        Main.tile[i, y - num].frameY = 36;
                    }
                    WorldGen.RangeFrame(i - 2, y - num - 1, i + 2, y + 1);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i - 1, y - num, 3, num, TileChangeType.None);
                    }
                    return true;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.anyLava(), Terraria.WorldGen.EmptyTileCheck(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.