Terraria Decompiled: Terraria.WorldGen.Place6x3
Place6x3()
static void Terraria.WorldGen.Place6x3 (int x, int y, ushort type, int direction = -1, int style = 0) inline static
Definition at line 48942 of file WorldGen.cs.
        {
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            bool flag = true;
            for (int i = x - 3; i < x + 3; i++)
            {
                for (int j = y - 2; j <= y; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active())
                    {
                        flag = false;
                    }
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (!WorldGen.SolidTile2(i, y + 1) && (!Main.tile[i, y + 1].nactive() || !Main.tileSolidTop[(int)Main.tile[i, y + 1].type] || Main.tile[i, y + 1].frameY != 0))
                {
                    flag = false;
                }
            }
            if (flag)
            {
                int num = 0;
                for (int k = x - 3; k < x + 3; k++)
                {
                    int num2 = 0;
                    for (int l = y - 2; l <= y; l++)
                    {
                        Main.tile[k, l].active(true);
                        Main.tile[k, l].frameY = (short)num2;
                        Main.tile[k, l].frameX = (short)num;
                        Main.tile[k, l].type = type;
                        num2 += 18;
                    }
                    num += 18;
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().