Terraria Decompiled: Terraria.WorldGen.PaintTheLivingTrees
PaintTheLivingTrees()
static void Terraria.WorldGen.PaintTheLivingTrees (byte livingTreePaintColor, byte livingTreeWallPaintColor) inline static private
Definition at line 21776 of file WorldGen.cs.
        {
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active())
                    {
                        if (tile.wall == 244)
{
                            tile.color(livingTreePaintColor);
                        }
                        else if (tile.type == 192 || tile.type == 191)
{
                            tile.color(livingTreePaintColor);
                        }
                        else if (tile.type == 52 || tile.type == 382)
{
                            int num = i;
                            int num2 = j;
                            WorldGen.GetVineTop(i, j, out num, out num2);
                            if (Main.tile[num, num2].type == 192)
{
                                tile.color(livingTreePaintColor);
                            }
                        }
                        else if (tile.type == 187)
{
                            Tile tile2 = tile;
                            int num3 = 0;
                            while (tile2.type == 187)
{
                                num3++;
                                tile2 = Main.tile[i, j + num3];
                            }
                            if (tile2.type == 192)
{
                                tile.color(livingTreePaintColor);
                            }
                        }
                    }
                    if (tile.wall == 244)
                    {
                        tile.wallColor(livingTreeWallPaintColor);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.WorldGen.GetVineTop(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.WorldGen.FinishTenthAnniversaryWorld().