Terraria Decompiled: Terraria.WorldGen.FinishTenthAnniversaryWorld
FinishTenthAnniversaryWorld()
static void Terraria.WorldGen.FinishTenthAnniversaryWorld () inline static private
Definition at line 21376 of file WorldGen.cs.
        {
            if ((WorldGen.remixWorldGen || (!WorldGen.notTheBees && !WorldGen.dontStarveWorldGen)) && !WorldGen.remixWorldGen)
            {
                if (!WorldGen.getGoodWorldGen && !WorldGen.drunkWorldGen)
                {
                    WorldGen.ConvertSkyIslands(2, true);
                }
                WorldGen.PaintTheDungeon(24, 24);
                if (!Main.onlyShimmerOceanWorldsGeneration && !WorldGen.SecretSeed.noSurface.Enabled)
                {
                    WorldGen.PaintTheLivingTrees(12, 12);
                }
                WorldGen.PaintTheTemple(10, 5);
                if (!Main.onlyShimmerOceanWorldsGeneration)
                {
                    WorldGen.PaintTheClouds(12, 12);
                }
                WorldGen.PaintTheSand(7, 7);
                if (!Main.onlyShimmerOceanWorldsGeneration)
                {
                    WorldGen.PaintThePyramids(12, 12);
                }
            }
            if (!WorldGen.getGoodWorldGen)
            {
                for (int i = 50; i < Main.maxTilesX - 50; i++)
                {
                    for (int j = 50; j < Main.maxTilesY - 50; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (WorldGen.genRand.Next(4) == 0 && tile.active() && tile.type == 138 && tile.frameX == 0 && tile.frameY == 0)
{
                            Main.tile[i, j].type = 665;
                            Main.tile[i, j + 1].type = 665;
                            Main.tile[i + 1, j].type = 665;
                            Main.tile[i + 1, j + 1].type = 665;
                        }
                    }
                }
            }
            if (!WorldGen.getGoodWorldGen)
            {
                WorldGen.ImproveAllChestContents();
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGen, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.WorldGen.ImproveAllChestContents(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.notTheBees, Terraria.Main.onlyShimmerOceanWorldsGeneration, Terraria.WorldGen.PaintTheClouds(), Terraria.WorldGen.PaintTheDungeon(), Terraria.WorldGen.PaintTheLivingTrees(), Terraria.WorldGen.PaintThePyramids(), Terraria.WorldGen.PaintTheSand(), Terraria.WorldGen.PaintTheTemple(), Terraria.WorldGen.remixWorldGen, Terraria.Main.tile, and Terraria.Tile.type.