Terraria Decompiled: Terraria.WorldGen.MudWallRunner
MudWallRunner()
static void Terraria.WorldGen.MudWallRunner (int i, int j) inline static
Definition at line 77807 of file WorldGen.cs.
        {
            double num = (double)WorldGen.genRand.Next(8, 21);
            double num2 = (double)WorldGen.genRand.Next(8, 33);
            double num3 = num2;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            vector2D2.Y = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            while (num > 0.0 && num3 > 0.0)
            {
                double num4 = num * (num3 / num2);
                num3 -= 1.0;
                int num5 = (int)(vector2D.X - num4 * 0.5);
                int num6 = (int)(vector2D.X + num4 * 0.5);
                int num7 = (int)(vector2D.Y - num4 * 0.5);
                int num8 = (int)(vector2D.Y + num4 * 0.5);
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesX)
                {
                    num6 = Main.maxTilesX;
                }
                if (num7 < 0)
                {
                    num7 = 0;
                }
                if (num8 > Main.maxTilesY)
                {
                    num8 = Main.maxTilesY;
                }
                for (int k = num5; k < num6; k++)
                {
                    for (int l = num7; l < num8; l++)
                    {
                        if (Math.Abs((double)k - vector2D.X) + Math.Abs((double)l - vector2D.Y) < num * 0.5 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015) && (double)l > Main.worldSurface)
{
                            Main.tile[k, l].wall = 0;
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                vector2D2.Y += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.Y > 1.0)
                {
                    vector2D2.Y = 1.0;
                }
                if (vector2D2.Y < -1.0)
                {
                    vector2D2.Y = -1.0;
                }
            }
        }
References System.Math.Abs(), Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.JunglePass.GenerateHolesInMudWalls().