Terraria Decompiled: Terraria.WorldGen.Place3x2
Place3x2()
static void Terraria.WorldGen.Place3x2 (int x, int y, ushort type, int style = 0) inline static
Definition at line 50594 of file WorldGen.cs.
        {
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            bool flag = false;
            bool flag2 = true;
            if (type == 14 && style == 25)
            {
                flag = true;
            }
            int num = y - 1;
            if (flag)
            {
                num = y;
            }
            for (int i = x - 1; i < x + 2; i++)
            {
                for (int j = num; j < y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    Tile tile = Main.tile[i, j];
                    if (tile.active())
                    {
                        flag2 = false;
                    }
                    if (TileID.Sets.Campfires[(int)type] && tile.liquid > 0)
                    {
                        flag2 = false;
                    }
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (type == 285 || type == 286 || type == 298 || type == 299 || type == 310 || (type >= 361 && type <= 364) || type == 582 || type == 619)
                {
                    if (!WorldGen.SolidTile2(i, y + 1) && (!Main.tile[i, y + 1].nactive() || !Main.tileSolidTop[(int)Main.tile[i, y + 1].type] || Main.tile[i, y + 1].frameY != 0))
                    {
                        flag2 = false;
                    }
                }
                else
                {
                    if ((type == 186 || type == 187) && WorldGen.InvalidTileForPilesOrSpeleothems(i, y + 1))
                    {
                        flag2 = false;
                    }
                    if (type == 26 && TileID.Sets.Boulders[(int)Main.tile[i, y + 1].type])
                    {
                        flag2 = false;
                    }
                    if (!WorldGen.SolidTile2(i, y + 1))
                    {
                        flag2 = false;
                    }
                }
            }
            if (type == 88)
            {
                if (Chest.CreateChest(x - 1, y - 1, -1) == -1)
                {
                    flag2 = false;
                }
                else if (Main.netMode == 1)
                {
                    NetMessage.SendData(34, -1, -1, null, 2, (float)x, (float)y, (float)style, 0, 0, 0);
                }
            }
            if (flag2)
            {
                short num2 = (short)(54 * style);
                if (flag)
                {
                    Main.tile[x - 1, y].active(true);
                    Main.tile[x - 1, y].frameY = 0;
                    Main.tile[x - 1, y].frameX = num2;
                    Main.tile[x - 1, y].type = type;
                    Main.tile[x, y].active(true);
                    Main.tile[x, y].frameY = 0;
                    Main.tile[x, y].frameX = num2 + 18;
                    Main.tile[x, y].type = type;
                    Main.tile[x + 1, y].active(true);
                    Main.tile[x + 1, y].frameY = 0;
                    Main.tile[x + 1, y].frameX = num2 + 36;
                    Main.tile[x + 1, y].type = type;
                    return;
                }
                Main.tile[x - 1, y - 1].active(true);
                Main.tile[x - 1, y - 1].frameY = 0;
                Main.tile[x - 1, y - 1].frameX = num2;
                Main.tile[x - 1, y - 1].type = type;
                Main.tile[x, y - 1].active(true);
                Main.tile[x, y - 1].frameY = 0;
                Main.tile[x, y - 1].frameX = num2 + 18;
                Main.tile[x, y - 1].type = type;
                Main.tile[x + 1, y - 1].active(true);
                Main.tile[x + 1, y - 1].frameY = 0;
                Main.tile[x + 1, y - 1].frameX = num2 + 36;
                Main.tile[x + 1, y - 1].type = type;
                Main.tile[x - 1, y].active(true);
                Main.tile[x - 1, y].frameY = 18;
                Main.tile[x - 1, y].frameX = num2;
                Main.tile[x - 1, y].type = type;
                Main.tile[x, y].active(true);
                Main.tile[x, y].frameY = 18;
                Main.tile[x, y].frameX = num2 + 18;
                Main.tile[x, y].type = type;
                Main.tile[x + 1, y].active(true);
                Main.tile[x + 1, y].frameY = 18;
                Main.tile[x + 1, y].frameX = num2 + 36;
                Main.tile[x + 1, y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.ID.TileID.Sets.Campfires, Terraria.Chest.CreateChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.InvalidTileForPilesOrSpeleothems(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.WorldGen.ChasmRunner(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), and Terraria.WorldGen.PlaceTile().