Terraria Decompiled: Terraria.WorldGen.TileIsExposedToAir
TileIsExposedToAir()
static bool Terraria.WorldGen.TileIsExposedToAir (int x, int y) inline static
Definition at line 53310 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 2))
            {
                return false;
            }
            for (int i = x - 1; i <= x + 1; i++)
            {
                for (int j = y - 1; j <= y + 1; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && (!tile.active() || !Main.tileSolid[(int)tile.type] || TileID.Sets.Platforms[(int)tile.type]))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_GrassySurface(), Terraria.WorldGen.Convert(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance_TreeOnPillar(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_GrowGrass(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_TreeOnPillar().