Terraria Decompiled: Terraria.WorldGen.IsAlchemyPlantHarvestable
IsAlchemyPlantHarvestable()
static bool Terraria.WorldGen.IsAlchemyPlantHarvestable (int style, int y) inline static
Definition at line 65555 of file WorldGen.cs.
        {
            if (style == 0 && Main.dayTime)
            {
                return true;
            }
            if (style == 1 && !Main.dayTime)
            {
                return true;
            }
            if (style == 3 && !Main.dayTime && (Main.bloodMoon || Main.moonPhase == 0))
            {
                return true;
            }
            if (style == 4 && (Main.raining || Main.cloudAlpha > 0f))
            {
                return true;
            }
            if (style == 5)
            {
                bool flag = (double)y > Main.worldSurface;
                if (Main.remixWorld)
                {
                    int num = Main.maxTilesY - 350;
                    flag = y < num;
                }
                if ((!Main.raining || flag) && Main.time > 40500.0)
                {
                    return true;
                }
            }
            return false;
        }
References Terraria.Main.bloodMoon, Terraria.Main.cloudAlpha, Terraria.Main.dayTime, Terraria.Main.moonPhase, Terraria.Main.raining, Terraria.Main.remixWorld, Terraria.Main.time, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawAnyDirectionalGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawGrass(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawTexture(), Terraria.WorldGen.IsHarvestableHerbWithSeed(), and Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings().