Terraria Decompiled: Terraria.WorldGen.ChasmRunner
ChasmRunner()
static void Terraria.WorldGen.ChasmRunner (int i, int j, int steps, bool makeOrb = false) inline static
Definition at line 76414 of file WorldGen.cs.
        {
            double num = Main.worldSurface;
            if (WorldGen.SecretSeed.noSurface.Enabled)
            {
                num = Main.rockLayer;
            }
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            if (!makeOrb)
            {
                flag2 = true;
            }
            double num2 = (double)steps;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            vector2D2.Y = (double)WorldGen.genRand.Next(11) * 0.2 + 0.5;
            int num3 = 5;
            double num4 = (double)(WorldGen.genRand.Next(5) + 7);
            while (num4 > 0.0)
            {
                if (num2 > 0.0)
                {
                    num4 += (double)WorldGen.genRand.Next(3);
                    num4 -= (double)WorldGen.genRand.Next(3);
                    if (num4 < 7.0)
                    {
                        num4 = 7.0;
                    }
                    if (num4 > 20.0)
                    {
                        num4 = 20.0;
                    }
                    if (num2 == 1.0 && num4 < 10.0)
                    {
                        num4 = 10.0;
                    }
                }
                else if (vector2D.Y > num + 45.0)
                {
                    num4 -= (double)WorldGen.genRand.Next(4);
                }
                if (vector2D.Y > Main.rockLayer && num2 > 0.0)
                {
                    num2 = 0.0;
                }
                num2 -= 1.0;
                if (!flag && vector2D.Y > num + 20.0)
                {
                    flag = true;
                    WorldGen.ChasmRunnerSideways((int)vector2D.X, (int)vector2D.Y, -1, WorldGen.genRand.Next(20, 40));
                    WorldGen.ChasmRunnerSideways((int)vector2D.X, (int)vector2D.Y, 1, WorldGen.genRand.Next(20, 40));
                }
                int num5;
                int num6;
                int num7;
                int num8;
                if (num2 > (double)num3)
                {
                    num5 = (int)(vector2D.X - num4 * 0.5);
                    num6 = (int)(vector2D.X + num4 * 0.5);
                    num7 = (int)(vector2D.Y - num4 * 0.5);
                    num8 = (int)(vector2D.Y + num4 * 0.5);
                    if (num5 < 0)
                    {
                        num5 = 0;
                    }
                    if (num6 > Main.maxTilesX - 1)
                    {
                        num6 = Main.maxTilesX - 1;
                    }
                    if (num7 < 0)
                    {
                        num7 = 0;
                    }
                    if (num8 > Main.maxTilesY)
                    {
                        num8 = Main.maxTilesY;
                    }
                    for (int k = num5; k < num6; k++)
                    {
                        for (int l = num7; l < num8; l++)
{
                            if (Math.Abs((double)k - vector2D.X) + Math.Abs((double)l - vector2D.Y) < num4 * 0.5 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015) && WorldGen.CanEvilReplace(k, l) && Main.tile[k, l].type != 31 && Main.tile[k, l].type != 22 && Main.tile[k, l].type != 204)
{
                                Main.tile[k, l].active(false);
                            }
                        }
                    }
                }
                if (num2 <= 2.0 && vector2D.Y < num + 45.0)
                {
                    num2 = 2.0;
                }
                if (num2 <= 0.0)
                {
                    if (!flag2)
                    {
                        flag2 = true;
                        WorldGen.AddShadowOrb((int)vector2D.X, (int)vector2D.Y, false);
                    }
                    else if (!flag3)
                    {
                        flag3 = false;
                        bool flag4 = false;
                        int num9 = 0;
                        while (!flag4)
{
                            int num10 = WorldGen.genRand.Next((int)vector2D.X - 25, (int)vector2D.X + 25);
                            int num11 = WorldGen.genRand.Next((int)vector2D.Y - 50, (int)vector2D.Y);
                            if (num10 < 5)
{
                                num10 = 5;
                            }
                            if (num10 > Main.maxTilesX - 5)
{
                                num10 = Main.maxTilesX - 5;
                            }
                            if (num11 < 5)
{
                                num11 = 5;
                            }
                            if (num11 > Main.maxTilesY - 5)
{
                                num11 = Main.maxTilesY - 5;
                            }
                            if ((double)num11 > num)
{
                                if (!WorldGen.IsTileNearby(num10, num11, 26, 3))
{
                                    WorldGen.Place3x2(num10, num11, 26, 0);
                                }
                                if (Main.tile[num10, num11].type == 26)
{
                                    flag4 = true;
                                }
                                else
{
                                    num9++;
                                    if (num9 >= 10000)
{
                                        flag4 = true;
                                    }
                                }
                            }
                            else
{
                                flag4 = true;
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.01;
                if (vector2D2.X > 0.3)
                {
                    vector2D2.X = 0.3;
                }
                if (vector2D2.X < -0.3)
                {
                    vector2D2.X = -0.3;
                }
                num5 = (int)(vector2D.X - num4 * 1.1);
                num6 = (int)(vector2D.X + num4 * 1.1);
                num7 = (int)(vector2D.Y - num4 * 1.1);
                num8 = (int)(vector2D.Y + num4 * 1.1);
                if (num5 < 1)
                {
                    num5 = 1;
                }
                if (num6 > Main.maxTilesX - 1)
                {
                    num6 = Main.maxTilesX - 1;
                }
                if (num7 < 0)
                {
                    num7 = 0;
                }
                if (num8 > Main.maxTilesY)
                {
                    num8 = Main.maxTilesY;
                }
                for (int m = num5; m < num6; m++)
                {
                    for (int n = num7; n < num8; n++)
                    {
                        if (WorldGen.CanEvilReplace(m, n) && Math.Abs((double)m - vector2D.X) + Math.Abs((double)n - vector2D.Y) < num4 * 1.1 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015))
{
                            if (Main.tile[m, n].type != GenVars.ebonStone && n > j + WorldGen.genRand.Next(3, 20))
{
                                Main.tile[m, n].active(true);
                            }
                            if (steps <= num3)
{
                                Main.tile[m, n].active(true);
                            }
                            if (Main.tile[m, n].type != 31)
{
                                Main.tile[m, n].type = GenVars.ebonStone;
                            }
                        }
                    }
                }
                for (int num12 = num5; num12 < num6; num12++)
                {
                    for (int num13 = num7; num13 < num8; num13++)
                    {
                        if (WorldGen.CanEvilReplace(num12, num13) && Math.Abs((double)num12 - vector2D.X) + Math.Abs((double)num13 - vector2D.Y) < num4 * 1.1 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015))
{
                            if (Main.tile[num12, num13].type != 31)
{
                                Main.tile[num12, num13].type = GenVars.ebonStone;
                            }
                            if (steps <= num3)
{
                                Main.tile[num12, num13].active(true);
                            }
                            if (num13 > j + WorldGen.genRand.Next(3, 20))
{
                                Main.tile[num12, num13].wall = GenVars.ebonStoneWall;
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.AddShadowOrb(), Terraria.WorldGen.CanEvilReplace(), Terraria.WorldGen.ChasmRunnerSideways(), Terraria.WorldBuilding.GenVars.ebonStone, Terraria.WorldBuilding.GenVars.ebonStoneWall, Terraria.WorldGen.genRand, int, Terraria.WorldGen.IsTileNearby(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.Place3x2(), Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().