Terraria Decompiled: Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions
CheckSpecialTownNPCSpawningConditions()
static bool Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions (int type) inline static
Definition at line 612 of file WorldGen.cs.
        {
            if (type != 160)
            {
                return true;
            }
            if (!NPC.unlockedTruffleSpawn && (double)WorldGen.roomY2 > Main.worldSurface && !Main.NoFunctionalSurface)
            {
                return false;
            }
            int num;
            int num2;
            int num3;
            int num4;
            WorldGen.Housing_GetTestedRoomBounds(out num, out num2, out num3, out num4);
            int num5 = 0;
            for (int i = num + 1; i < num2; i++)
            {
                for (int j = num3 + 2; j < num4 + 2; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && (tile.type == 70 || tile.type == 71 || tile.type == 72 || tile.type == 528))
                    {
                        num5++;
                    }
                }
            }
            return num5 >= SceneMetrics.MushroomTileThreshold;
        }
References Terraria.Tile.active(), Terraria.WorldGen.Housing_GetTestedRoomBounds(), Terraria.SceneMetrics.MushroomTileThreshold, Terraria.Main.NoFunctionalSurface, Terraria.WorldGen.roomY2, Terraria.Main.tile, Terraria.Tile.type, Terraria.NPC.unlockedTruffleSpawn, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.FindNPCLookingForHomeThatCanMoveIn(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC_Old(), Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().