Terraria Decompiled: Terraria.WorldGen.GrowAlch
GrowAlch()
static void Terraria.WorldGen.GrowAlch (int x, int y) inline static
Definition at line 44106 of file WorldGen.cs.
        {
            if (Main.tile[x, y].active())
            {
                if (Main.tile[x, y].liquid > 0)
                {
                    int num = (int)(Main.tile[x, y].frameX / 18);
                    if ((!Main.tile[x, y].lava() || num != 5) && (Main.tile[x, y].liquidType() != 0 || (num != 1 && num != 4)))
                    {
                        WorldGen.KillTile(x, y, false, false, false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                        }
                        WorldGen.SquareTileFrame(x, y, true);
                    }
                }
                if (Main.tile[x, y].type == 82)
                {
                    if (WorldGen.genRand.Next(50) == 0)
                    {
                        bool flag = false;
                        if (Main.tile[x, y].frameX == 108)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                flag = true;
                            }
                        }
                        else
{
                            flag = true;
                        }
                        if (flag)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                            WorldGen.SquareTileFrame(x, y, true);
                            return;
                        }
                    }
                    else
                    {
                        if (Main.dayTime && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 0 && WorldGen.genRand.Next(50) == 0)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                            WorldGen.SquareTileFrame(x, y, true);
                            return;
                        }
                        if (!Main.dayTime && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 18 && WorldGen.genRand.Next(50) == 0)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                            WorldGen.SquareTileFrame(x, y, true);
                            return;
                        }
                        if (Main.raining && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 72 && WorldGen.genRand.Next(50) == 0)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                            WorldGen.SquareTileFrame(x, y, true);
                            return;
                        }
                        if ((double)y > Main.worldSurface && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 36 && WorldGen.genRand.Next(50) == 0)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                            WorldGen.SquareTileFrame(x, y, true);
                            return;
                        }
                        if (y > Main.maxTilesY - 200 && Main.tile[x, y].type == 82 && Main.tile[x, y].frameX == 90 && WorldGen.genRand.Next(50) == 0)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                            WorldGen.SquareTileFrame(x, y, true);
                            return;
                        }
                    }
                }
                else if (Main.tile[x, y].frameX == 36 && WorldGen.genRand.Next(3) != 0)
                {
                    if (Main.tile[x, y].type == 83)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            Main.tile[x, y].type = 84;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                                return;
                            }
                        }
                    }
                    else if (Main.tile[x, y].type == 84 || WorldGen.genRand.Next(5) == 0)
                    {
                        Main.tile[x, y].type = 83;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            return;
                        }
                    }
                }
                else if (Main.tile[x, y].frameX == 108 && Main.tile[x, y].type == 83 && WorldGen.genRand.Next(30) == 0)
                {
                    Main.tile[x, y].type = 84;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                    }
                    WorldGen.SquareTileFrame(x, y, true);
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.dayTime, Terraria.Tile.frameX, Terraria.WorldGen.genRand, int, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.raining, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().