Terraria Decompiled: Terraria.WorldGen.ActiveAndWalkableTile
ActiveAndWalkableTile()
static bool Terraria.WorldGen.ActiveAndWalkableTile (int i, int j) inline static
Definition at line 70573 of file WorldGen.cs.
        {
            try
            {
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    return true;
                }
                if (tile.active() && Main.tileSolid[(int)tile.type] && !tile.inActive())
                {
                    return true;
                }
            }
            catch
            {
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.inActive(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_123_Deerclops_FindSpotToSpawnSpike(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.Projectile.AI_198_Flint_EmitSpikes(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.Projectile.FindBlockCeiling(), and Terraria.Projectile.FindBlockSurface().