Terraria Decompiled: Terraria.WorldGen.CheckCannon
CheckCannon()
static void Terraria.WorldGen.CheckCannon (int i, int j, int type) inline static
Definition at line 49268 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k = (int)(Main.tile[i, j].frameX / 18);
            int num = 0;
            while (k >= 4)
            {
                num++;
                k -= 4;
            }
            k = i - k;
            int l = (int)(Main.tile[i, j].frameY / 18);
            int num2 = 0;
            while (l >= 3)
            {
                num2 += 54;
                l -= 3;
            }
            l = j - l;
            int num3 = 72 * num;
            for (int m = k; m < k + 4; m++)
            {
                int num4 = num2;
                for (int n = l; n < l + 3; n++)
                {
                    if (Main.tile[m, n] == null)
                    {
                        Main.tile[m, n] = new Tile();
                    }
                    if (!Main.tile[m, n].active() || (int)Main.tile[m, n].type != type || (int)Main.tile[m, n].frameX != num3 || (int)Main.tile[m, n].frameY != num4)
                    {
                        flag = true;
                    }
                    num4 += 18;
                }
                if (Main.tile[m, l + 3] == null)
                {
                    Main.tile[m, l + 3] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(m, l + 3) && m != k && m != k + 3)
                {
                    flag = true;
                }
                num3 += 18;
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int num5 = k; num5 < k + 4; num5++)
                {
                    for (int num6 = l; num6 < l + 3; num6++)
                    {
                        if ((int)Main.tile[num5, num6].type == type && Main.tile[num5, num6].active())
{
                            WorldGen.KillTile(num5, num6, false, false, false);
                        }
                    }
                }
                int num7 = 928;
                switch (num)
                {
                case 1:
                    num7 = 1337;
                    break;
                case 2:
                    num7 = 3369;
                    break;
                case 3:
                case 4:
                    num7 = 3664;
                    break;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num7, 1, false, 0, false);
                WorldGen.destroyObject = false;
                for (int num8 = k; num8 < k + 4; num8++)
                {
                    for (int num9 = l; num9 < l + 3; num9++)
                    {
                        WorldGen.TileFrame(num8, num9, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().