Terraria Decompiled: Terraria.WorldGen.Place2x2
Place2x2()
static void Terraria.WorldGen.Place2x2 (int x, int y, ushort type, int style) inline static
Definition at line 49834 of file WorldGen.cs.
        {
            if (type == 95 || type == 126)
            {
                y++;
            }
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            if (type == 172)
            {
                if (!WorldGen.CanPlaceSink(x, y, type, style))
                {
                    return;
                }
            }
            else
            {
                for (int i = x - 1; i < x + 1; i++)
                {
                    for (int j = y - 1; j < y + 1; j++)
                    {
                        Tile tile = Framing.GetTileSafely(i, j);
                        if (tile.active())
{
                            return;
                        }
                        if (type == 98 && tile.liquid > 0)
{
                            return;
                        }
                    }
                    if (type == 95 || type == 126)
                    {
                        Tile tile = Framing.GetTileSafely(i, y - 2);
                        if (!tile.nactive() || !Main.tileSolid[(int)tile.type] || Main.tileSolidTop[(int)tile.type])
{
                            return;
                        }
                    }
                    else if (type != 132)
                    {
                        Tile tile = Framing.GetTileSafely(i, y + 1);
                        if (!tile.nactive() || (!WorldGen.SolidTile2(tile) && !Main.tileTable[(int)tile.type]))
{
                            return;
                        }
                    }
                }
            }
            if (type == 132)
            {
                bool flag = true;
                if (Main.tile[x - 1, y + 1] == null)
                {
                    Main.tile[x - 1, y + 1] = new Tile();
                }
                if (Main.tile[x, y + 1] == null)
                {
                    Main.tile[x, y + 1] = new Tile();
                }
                if (!Main.tile[x - 1, y + 1].nactive() || (!WorldGen.SolidTile2(x - 1, y + 1) && !Main.tileTable[(int)Main.tile[x - 1, y + 1].type]))
                {
                    flag = false;
                }
                if (!Main.tile[x, y + 1].nactive() || (!WorldGen.SolidTile2(x, y + 1) && !Main.tileTable[(int)Main.tile[x, y + 1].type]))
                {
                    flag = false;
                }
                if (!flag && (Main.tile[x - 1, y - 1].wall < 1 || Main.tile[x, y - 1].wall < 1 || Main.tile[x - 1, y].wall < 1 || Main.tile[x - 1, y].wall < 1))
                {
                    return;
                }
            }
            x--;
            y--;
            int num = ((type == 172) ? 38 : 36);
            for (int k = 0; k < 2; k++)
            {
                for (int l = 0; l < 2; l++)
                {
                    Tile tile = Main.tile[x + k, y + l];
                    tile.active(true);
                    tile.frameX = (short)(k * 18);
                    tile.frameY = (short)(style * num + l * 18);
                    tile.type = type;
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanPlaceSink(), Terraria.Framing.GetTileSafely(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileTable, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.PlaceTile().