Terraria Decompiled: Terraria.WorldGen.PlaceWall
PlaceWall()
static void Terraria.WorldGen.PlaceWall (int i, int j, int type, bool mute = false) inline static
Definition at line 75623 of file WorldGen.cs.
        {
            if (i <= 1 || j <= 1 || i >= Main.maxTilesX - 2 || j >= Main.maxTilesY - 2)
            {
                return;
            }
            if (Main.tile[i, j] == null)
            {
                Main.tile[i, j] = new Tile();
            }
            if (Main.tile[i, j].wall == 0)
            {
                Main.tile[i, j].wall = (ushort)type;
                WorldGen.SquareWallFrame(i, j, true);
                if (!mute)
                {
                    SoundEngine.PlaySound(0, i * 16, j * 16, 1, 1f, 0f);
                }
            }
        }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Audio.SoundEngine.PlaySound(), Terraria.WorldGen.SquareWallFrame(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.ChasmRunnerSideways(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.Player.PlaceThing_Walls(), Terraria.Player.PlaceThing_Walls_FillEmptySpace(), Terraria.WorldGen.TileRunner(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_LineOfFence(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_OuterPillar().