Terraria Decompiled: Terraria.WorldGen.SpawnTownNPC
SpawnTownNPC()
static TownNPCSpawnResult Terraria.WorldGen.SpawnTownNPC (int x, int y, bool canSpawnNewTownNPC = true) inline static
Definition at line 1109 of file WorldGen.cs.
        {
            if (Main.wallHouse[(int)Main.tile[x, y].wall])
            {
                WorldGen.canSpawn = true;
            }
            if (!WorldGen.canSpawn)
            {
                return TownNPCSpawnResult.Blocked;
            }
            if (!WorldGen.StartRoomCheck(x, y, null))
            {
                return TownNPCSpawnResult.Blocked;
            }
            if (!WorldGen.RoomNeeds())
            {
                return TownNPCSpawnResult.Blocked;
            }
            int num = WorldGen.prioritizedTownNPCType;
            int num2 = WorldGen.FindNPCLookingForHomeThatCanMoveIn(num);
            Point zero = Point.Zero;
            bool flag = NPCID.Sets.IsTownPet[num] && WorldGen.TownManager.HasRoom(num, out zero);
            if ((WorldGen.roomHasStinkbug || WorldGen.roomHasEchoStinkbug) && !flag)
            {
                return TownNPCSpawnResult.Blocked;
            }
            WorldGen.ScoreRoom(-1, num, null);
            if (WorldGen.hiScore <= 0)
            {
                return TownNPCSpawnResult.Blocked;
            }
            if (WorldGen.CheckSpecialTownNPCSpawningConditions(WorldGen.prioritizedTownNPCType) && NPC.AnyNPCs(WorldGen.prioritizedTownNPCType))
            {
                canSpawnNewTownNPC = false;
            }
            else
            {
                num2 = -1;
                if (canSpawnNewTownNPC)
                {
                    num = WorldGen.IsThereASpawnablePrioritizedTownNPC(WorldGen.bestX, WorldGen.bestY);
                    canSpawnNewTownNPC = num > 0;
                }
            }
            if (num2 != -1)
            {
                Main.townNPCCanSpawn[WorldGen.prioritizedTownNPCType] = false;
                Main.npc[num2].homeTileX = WorldGen.bestX;
                Main.npc[num2].homeTileY = WorldGen.bestY;
                Main.npc[num2].homeless = false;
                Main.npc[num2].homelessDespawn = false;
                AchievementsHelper.NotifyProgressionEvent(8);
                WorldGen.prioritizedTownNPCType = 0;
                return TownNPCSpawnResult.RelocatedHomeless;
            }
            if (NPC.AnyNPCs(WorldGen.prioritizedTownNPCType))
            {
                canSpawnNewTownNPC = false;
            }
            if (!canSpawnNewTownNPC)
            {
                WorldGen.LastFoundHouse = new Point(x, y);
                return TownNPCSpawnResult.FoundHouseNoSpawn;
            }
            Point point;
            if (WorldGen.TownManager.HasRoom(num, out point) && !WorldGen.currentlyTryingToUseAlternateHousingSpot)
            {
                int num3 = WorldGen.bestX;
                int num4 = WorldGen.bestY;
                WorldGen.currentlyTryingToUseAlternateHousingSpot = true;
                TownNPCSpawnResult townNPCSpawnResult = WorldGen.SpawnTownNPC(point.X, point.Y - 2, true);
                WorldGen.currentlyTryingToUseAlternateHousingSpot = false;
                WorldGen.bestX = num3;
                WorldGen.bestY = num4;
                if (townNPCSpawnResult == TownNPCSpawnResult.Successful)
                {
                    return townNPCSpawnResult;
                }
            }
            int num5 = WorldGen.bestX;
            int num6 = WorldGen.bestY;
            int num7 = WorldGen.prioritizedTownNPCType;
            if (WorldGen.IsRoomConsideredAlreadyOccupied(num5, num6, num7))
            {
                return TownNPCSpawnResult.BlockedInfiHousing;
            }
            bool flag2 = false;
            if (!flag2)
            {
                flag2 = true;
                Rectangle rectangle = new Rectangle(num5 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num6 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active)
                    {
                        Rectangle rectangle2 = new Rectangle((int)Main.player[i].position.X, (int)Main.player[i].position.Y, Main.player[i].width, Main.player[i].height);
                        if (rectangle2.Intersects(rectangle))
{
                            flag2 = false;
                            break;
                        }
                    }
                }
            }
            if (!flag2 && (double)num6 <= Main.worldSurface)
            {
                for (int j = 1; j < 500; j++)
                {
                    for (int k = 0; k < 2; k++)
                    {
                        if (k == 0)
{
                            num5 = WorldGen.bestX + j;
                        }
                        else
{
                            num5 = WorldGen.bestX - j;
                        }
                        if (num5 > 10 && num5 < Main.maxTilesX - 10)
{
                            int num8 = WorldGen.bestY - j;
                            double num9 = (double)(WorldGen.bestY + j);
                            if (num8 < 10)
{
                                num8 = 10;
                            }
                            if (num9 > Main.worldSurface)
{
                                num9 = Main.worldSurface;
                            }
                            int num10 = num8;
                            while ((double)num10 < num9)
{
                                num6 = num10;
                                if (Main.tile[num5, num6].nactive() && Main.tileSolid[(int)Main.tile[num5, num6].type])
{
                                    if (!Collision.SolidTiles(num5 - 1, num5 + 1, num6 - 3, num6 - 1))
{
                                        flag2 = true;
                                        Rectangle rectangle3 = new Rectangle(num5 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num6 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                                        for (int l = 0; l < 255; l++)
{
                                            if (Main.player[l].active)
{
                                                Rectangle rectangle4 = new Rectangle((int)Main.player[l].position.X, (int)Main.player[l].position.Y, Main.player[l].width, Main.player[l].height);
                                                if (rectangle4.Intersects(rectangle3))
{
                                                    flag2 = false;
                                                    break;
                                                }
                                            }
                                        }
                                        break;
                                    }
                                    break;
                                }
                                else
{
                                    num10++;
                                }
                            }
                        }
                        if (flag2)
{
                            break;
                        }
                    }
                    if (flag2)
                    {
                        break;
                    }
                }
            }
            int num11 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), num5 * 16, num6 * 16, num, 1, 0f, 0f, 0f, 0f, 255);
            if (num11 == Main.maxNPCs && Main.npc[num11].type != num)
            {
                return TownNPCSpawnResult.BlockedTooManyNPCs;
            }
            Main.townNPCCanSpawn[num] = false;
            Main.npc[num11].homeTileX = WorldGen.bestX;
            Main.npc[num11].homeTileY = WorldGen.bestY;
            if (num5 < WorldGen.bestX)
            {
                Main.npc[num11].direction = 1;
            }
            else if (num5 > WorldGen.bestX)
            {
                Main.npc[num11].direction = -1;
            }
            Main.npc[num11].netUpdate = true;
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasArrived", new object[] { Main.npc[num11].GetFullNetName() }), ChatColors.NPCTravel, -1);
            AchievementsHelper.NotifyProgressionEvent(8);
            int type = Main.npc[num11].type;
            if (type <= 160)
            {
                switch (type)
                {
                case 17:
                    NPC.unlockedMerchantSpawn = true;
                    break;
                case 18:
                    NPC.unlockedNurseSpawn = true;
                    break;
                case 19:
                    NPC.unlockedArmsDealerSpawn = true;
                    break;
                default:
                    if (type != 38)
                    {
                        if (type == 160)
{
                            AchievementsHelper.NotifyProgressionEvent(18);
                            NPC.unlockedTruffleSpawn = true;
                            NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                    else
                    {
                        NPC.unlockedDemolitionistSpawn = true;
                    }
                    break;
                }
            }
            else if (type <= 208)
            {
                if (type != 207)
                {
                    if (type == 208)
                    {
                        NPC.unlockedPartyGirlSpawn = true;
                    }
                }
                else
                {
                    NPC.unlockedDyeTraderSpawn = true;
                }
            }
            else if (type != 663)
            {
                if (type == 678)
                {
                    NPC.unlockedSlimeGreenSpawn = true;
                }
            }
            else
            {
                NPC.unlockedPrincessSpawn = true;
            }
            WorldGen.CheckAchievement_RealEstateAndTownSlimes();
            WorldGen.prioritizedTownNPCType = 0;
            return TownNPCSpawnResult.Successful;
        }
References Terraria.Player.active, Terraria.NPC.AnyNPCs(), Terraria.WorldGen.bestX, Terraria.WorldGen.bestY, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.WorldGen.canSpawn, Terraria.WorldGen.CheckAchievement_RealEstateAndTownSlimes(), Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.WorldGen.currentlyTryingToUseAlternateHousingSpot, Terraria.Entity.direction, Terraria.WorldGen.FindNPCLookingForHomeThatCanMoveIn(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetSpawnSourceForTownSpawn(), Terraria.GameContent.TownRoomManager.HasRoom(), Terraria.Entity.height, Terraria.WorldGen.hiScore, Terraria.NPC.homeless, Terraria.NPC.homelessDespawn, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.IsRoomConsideredAlreadyOccupied(), Terraria.WorldGen.IsThereASpawnablePrioritizedTownNPC(), Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Tile.nactive(), Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.npc, Terraria.Chat.ChatColors.NPCTravel, Terraria.Main.player, Terraria.Entity.position, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.roomHasEchoStinkbug, Terraria.WorldGen.roomHasStinkbug, Terraria.WorldGen.RoomNeeds(), Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.WorldGen.ScoreRoom(), Terraria.NetMessage.SendData(), Terraria.NPC.sHeight, Terraria.Collision.SolidTiles(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.StartRoomCheck(), Terraria.NPC.sWidth, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.WorldGen.TownManager, Terraria.Main.townNPCCanSpawn, Terraria.NPC.type, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallHouse, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.WorldGen.CheckForHousesNearAPlayer(), Terraria.WorldGen.moveRoom(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.WorldGen.SpawnTownNPC(), and Terraria.WorldGen.TrySpawningTownNPC().