Terraria Decompiled: Terraria.WorldGen.paintCoatTile
paintCoatTile()
static bool Terraria.WorldGen.paintCoatTile (int x, int y, byte paintCoatId, bool broadcast = false, bool coatingEffects = true) inline static
Definition at line 42428 of file WorldGen.cs.
        {
            Tile tile = Main.tile[x, y];
            if (tile == null || !tile.active())
            {
                return false;
            }
            List<Color> list = WorldGen.coatingColors(tile, true);
            switch (paintCoatId)
            {
            case 0:
                if (!tile.fullbrightBlock() && !tile.invisibleBlock())
                {
                    return false;
                }
                tile.fullbrightBlock(false);
                tile.invisibleBlock(false);
                WorldGen.SquareTileFrame(x, y, false);
                break;
            case 1:
                if (tile.fullbrightBlock())
                {
                    return false;
                }
                tile.fullbrightBlock(true);
                break;
            case 2:
                if (tile.invisibleBlock())
                {
                    return false;
                }
                tile.invisibleBlock(true);
                WorldGen.SquareTileFrame(x, y, false);
                break;
            default:
                return false;
            }
            if (broadcast)
            {
                NetMessage.SendData(63, -1, -1, null, x, (float)y, (float)paintCoatId, 1f, 0, 0, 0);
            }
            if (coatingEffects)
            {
                WorldGen.paintCoatEffect(x, y, paintCoatId, list);
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.coatingColors(), Terraria.Tile.fullbrightBlock(), Terraria.Tile.invisibleBlock(), System.list, Terraria.WorldGen.paintCoatEffect(), Terraria.NetMessage.SendData(), Terraria.WorldGen.SquareTileFrame(), and Terraria.Main.tile.
Referenced by Terraria.Player.ApplyCoating(), Terraria.WorldGen.Convert_ActuallyConvertTile(), Terraria.WorldGen.Convert_ActuallyConvertTorch(), Terraria.WorldGen.meteor(), and Terraria.Player.PlaceThing_PaintScrapper_TryScrapping().