Terraria Decompiled: Terraria.WorldGen.PlaceChand
PlaceChand()
static void Terraria.WorldGen.PlaceChand (int x, int y, ushort type, int style = 0) inline static
Definition at line 51237 of file WorldGen.cs.
        {
            bool flag = true;
            int num = 0;
            for (int i = x - 1; i < x + 2; i++)
            {
                for (int j = y; j < y + 3; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active())
                    {
                        flag = false;
                    }
                }
            }
            if (Main.tile[x, y - 1] == null)
            {
                Main.tile[x, y - 1] = new Tile();
            }
            if (!Main.tile[x, y - 1].nactive() || !Main.tileSolid[(int)Main.tile[x, y - 1].type] || Main.tileSolidTop[(int)Main.tile[x, y - 1].type])
            {
                flag = false;
            }
            if (flag)
            {
                int num2 = style / 36 * 18 * 6;
                int num3 = style * 18 * 3;
                if (num2 >= 108)
                {
                    num3 -= 54 * (num2 / 108) * 37;
                }
                Main.tile[x - 1, y + num].active(true);
                Main.tile[x - 1, y + num].frameY = (short)num3;
                Main.tile[x - 1, y + num].frameX = (short)num2;
                Main.tile[x - 1, y + num].type = type;
                Main.tile[x, y + num].active(true);
                Main.tile[x, y + num].frameY = (short)num3;
                Main.tile[x, y + num].frameX = (short)(num2 + 18);
                Main.tile[x, y + num].type = type;
                Main.tile[x + 1, y + num].active(true);
                Main.tile[x + 1, y + num].frameY = (short)num3;
                Main.tile[x + 1, y + num].frameX = (short)(num2 + 36);
                Main.tile[x + 1, y + num].type = type;
                Main.tile[x - 1, y + 1 + num].active(true);
                Main.tile[x - 1, y + 1 + num].frameY = (short)(num3 + 18);
                Main.tile[x - 1, y + 1 + num].frameX = (short)num2;
                Main.tile[x - 1, y + 1 + num].type = type;
                Main.tile[x, y + 1 + num].active(true);
                Main.tile[x, y + 1 + num].frameY = (short)(num3 + 18);
                Main.tile[x, y + 1 + num].frameX = (short)(num2 + 18);
                Main.tile[x, y + 1 + num].type = type;
                Main.tile[x + 1, y + 1 + num].active(true);
                Main.tile[x + 1, y + 1 + num].frameY = (short)(num3 + 18);
                Main.tile[x + 1, y + 1 + num].frameX = (short)(num2 + 36);
                Main.tile[x + 1, y + 1 + num].type = type;
                Main.tile[x - 1, y + 2 + num].active(true);
                Main.tile[x - 1, y + 2 + num].frameY = (short)(num3 + 36);
                Main.tile[x - 1, y + 2 + num].frameX = (short)num2;
                Main.tile[x - 1, y + 2 + num].type = type;
                Main.tile[x, y + 2 + num].active(true);
                Main.tile[x, y + 2 + num].frameY = (short)(num3 + 36);
                Main.tile[x, y + 2 + num].frameX = (short)(num2 + 18);
                Main.tile[x, y + 2 + num].type = type;
                Main.tile[x + 1, y + 2 + num].active(true);
                Main.tile[x + 1, y + 2 + num].frameY = (short)(num3 + 36);
                Main.tile[x + 1, y + 2 + num].frameX = (short)(num2 + 36);
                Main.tile[x + 1, y + 2 + num].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.nactive(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), and Terraria.WorldGen.PlaceTile().