Terraria Decompiled: Terraria.WorldGen.AddPasses
AddPasses()
static void Terraria.WorldGen.AddPasses () inline static
Definition at line 7531 of file WorldGen.cs.
        {
            WorldGen.AddGenerationPass(new TerrainPass());
            if (WorldGen.skyblockWorldGen)
            {
                if (!WorldGen.Skyblock.denyAllGeneration)
                {
                    WorldGen.AddGenerationPass(new JunglePass());
                }
                WorldGen.AddGenerationPass(GenPassNameID.Skyblock, delegate(GenerationProgress progress, GameConfiguration passConfig)
                {
                    progress.Message = Lang.gen[12].Value;
                    WorldGen.GenerateSkyBlockWorld(progress);
                });
            }
            WorldGen.AddGenerationPass(GenPassNameID.DunesAndPyramidLocations, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                DungeonCrawler.SetupDungeonGenVarVariables(GenVars.CurrentDungeonGenVars, WorldGen.genRand);
                if (WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    GenVars.CurrentDungeon = 1;
                    DungeonCrawler.SetupDungeonGenVarVariables(GenVars.CurrentDungeonGenVars, WorldGen.genRand);
                    GenVars.CurrentDungeon = 0;
                }
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[1].Value;
                int random = passConfig.Get<WorldGenRange>("Count").GetRandom(WorldGen.genRand);
                double num = passConfig.Get<double>("ChanceOfPyramid");
                if (WorldGen.drunkWorldGen || WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    num = 1.0;
                }
                double num2 = (double)Main.maxTilesX / 4200.0;
                GenVars.PyrX = new int[random + 3];
                GenVars.PyrY = new int[random + 3];
                DunesBiome dunesBiome = GenVars.configuration.CreateBiome<DunesBiome>();
                for (int i = 0; i < random; i++)
                {
                    progress.Set((double)i / (double)random);
                    Point point = Point.Zero;
                    bool flag = false;
                    int num3 = 0;
                    while (!flag)
                    {
                        point = WorldGen.RandomWorldPoint(0, 500, 0, 500);
                        bool flag2 = Math.Abs(point.X - GenVars.jungleOriginX) < (int)(600.0 * num2);
                        bool flag3 = Math.Abs(point.X - Main.maxTilesX / 2) < 300;
                        bool flag4 = point.X > GenVars.snowOriginLeft - 300 && point.X < GenVars.snowOriginRight + 300;
                        num3++;
                        if (num3 >= Main.maxTilesX)
{
                            flag2 = false;
                        }
                        if (num3 >= Main.maxTilesX * 2)
{
                            flag4 = false;
                        }
                        flag = !flag2 && !flag3 && !flag4;
                    }
                    dunesBiome.Place(point, GenVars.structures);
                    if (WorldGen.genRand.NextDouble() <= num)
                    {
                        int num4 = WorldGen.genRand.Next(point.X - 200, point.X + 200);
                        for (int j = 0; j < Main.maxTilesY; j++)
{
                            if (Main.tile[num4, j].active())
{
                                GenVars.PyrX[GenVars.numPyr] = num4;
                                GenVars.PyrY[GenVars.numPyr] = j + 20;
                                GenVars.numPyr++;
                                break;
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.OceanSand, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.OceanSand");
                int k = 0;
                while (k < 3)
                {
                    progress.Set((double)((float)k / 3f));
                    int num5 = WorldGen.genRand.Next(Main.maxTilesX);
                    while ((double)num5 > (double)Main.maxTilesX * 0.4 && (double)num5 < (double)Main.maxTilesX * 0.6)
                    {
                        num5 = WorldGen.genRand.Next(Main.maxTilesX);
                    }
                    int num6 = WorldGen.genRand.Next(35, 90);
                    if (k == 1)
                    {
                        double num7 = (double)Main.maxTilesX / 4200.0;
                        num6 += (int)((double)WorldGen.genRand.Next(20, 40) * num7);
                    }
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        num6 *= 2;
                    }
                    if (k == 1)
                    {
                        num6 *= 2;
                    }
                    int num8 = num5 - num6;
                    num6 = WorldGen.genRand.Next(35, 90);
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        num6 *= 2;
                    }
                    if (k == 1)
                    {
                        num6 *= 2;
                    }
                    int num9 = num5 + num6;
                    if (num8 < 0)
                    {
                        num8 = 0;
                    }
                    if (num9 > Main.maxTilesX)
                    {
                        num9 = Main.maxTilesX;
                    }
                    if (k == 0)
                    {
                        num8 = 0;
                        num9 = GenVars.leftBeachEnd;
                        goto IL_0148;
                    }
                    if (k == 2)
                    {
                        num8 = GenVars.rightBeachStart;
                        num9 = Main.maxTilesX;
                        goto IL_0148;
                    }
                    if (k != 1)
                    {
                        goto IL_0148;
                    }
                    IL_02A8:
                    k++;
                    continue;
                    IL_0148:
                    int num10 = WorldGen.genRand.Next(50, 100);
                    for (int l = num8; l < num9; l++)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num10 += WorldGen.genRand.Next(-1, 2);
                            if (num10 < 50)
{
                                num10 = 50;
                            }
                            if (num10 > 200)
{
                                num10 = 200;
                            }
                        }
                        int num11 = 0;
                        while ((double)num11 < (Main.worldSurface + Main.rockLayer) / 2.0)
{
                            if (Main.tile[l, num11].active())
{
                                if (l == (num8 + num9) / 2 && WorldGen.genRand.Next(6) == 0)
{
                                    GenVars.PyrX[GenVars.numPyr] = l;
                                    GenVars.PyrY[GenVars.numPyr] = num11;
                                    GenVars.numPyr++;
                                }
                                int num12 = num10;
                                if (l - num8 < num12)
{
                                    num12 = l - num8;
                                }
                                if (num9 - l < num12)
{
                                    num12 = num9 - l;
                                }
                                num12 += WorldGen.genRand.Next(5);
                                for (int m = num11; m < num11 + num12; m++)
{
                                    if (l > num8 + WorldGen.genRand.Next(5) && l < num9 - WorldGen.genRand.Next(5))
{
                                        Main.tile[l, m].type = 53;
                                    }
                                }
                                break;
                            }
                            num11++;
                        }
                    }
                    goto IL_02A8;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SandPatches, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.SandPatches");
                progress.Set(0.0);
                int num13 = (int)((double)Main.maxTilesX * 0.013);
                if (WorldGen.remixWorldGen)
                {
                    num13 /= 4;
                }
                for (int n = 0; n < num13; n++)
                {
                    progress.Set((double)((float)n / (float)num13));
                    int num14 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    int num15 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    if (WorldGen.remixWorldGen)
                    {
                        num15 = WorldGen.genRand.Next((int)Main.rockLayer - 100, Main.maxTilesY - 350);
                    }
                    while ((double)num14 > (double)Main.maxTilesX * 0.46 && (double)num14 < (double)Main.maxTilesX * 0.54 && (double)num15 < Main.worldSurface + 150.0)
                    {
                        num14 = WorldGen.genRand.Next(0, Main.maxTilesX);
                        num15 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    int num16 = WorldGen.genRand.Next(15, 70);
                    int num17 = WorldGen.genRand.Next(20, 130);
                    WorldGen.TileRunner(num14, num15, (double)num16, num17, 53, false, 0.0, 0.0, false, true, -1);
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Tunnels, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.SurfaceTunnels");
                progress.Set(0.0);
                int num18 = (int)((double)Main.maxTilesX * 0.0015);
                if (WorldGen.remixWorldGen)
                {
                    num18 = (int)((double)num18 * 1.5);
                }
                for (int num19 = 0; num19 < num18; num19++)
                {
                    progress.Set((double)((float)num19 / (float)num18));
                    if (GenVars.numTunnels >= GenVars.maxTunnels - 1)
                    {
                        break;
                    }
                    int[] array = new int[10];
                    int[] array2 = new int[10];
                    int num20 = WorldGen.genRand.Next(450, Main.maxTilesX - 450);
                    if (!WorldGen.remixWorldGen)
                    {
                        if (WorldGen.tenthAnniversaryWorldGen)
{
                            num20 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                        }
                        else
{
                            while ((double)num20 > (double)Main.maxTilesX * 0.4 && (double)num20 < (double)Main.maxTilesX * 0.6)
{
                                num20 = WorldGen.genRand.Next(450, Main.maxTilesX - 450);
                            }
                        }
                    }
                    int num21 = 0;
                    bool flag5;
                    do
                    {
                        flag5 = false;
                        for (int num22 = 0; num22 < 10; num22++)
{
                            num20 %= Main.maxTilesX;
                            while (!Main.tile[num20, num21].active())
{
                                num21++;
                            }
                            if (Main.tile[num20, num21].type == 53)
{
                                flag5 = true;
                            }
                            array[num22] = num20;
                            array2[num22] = num21 - WorldGen.genRand.Next(11, 16);
                            num20 += WorldGen.genRand.Next(5, 11);
                        }
                    }
                    while (flag5);
                    GenVars.tunnelX[GenVars.numTunnels] = array[5];
                    GenVars.numTunnels++;
                    for (int num23 = 0; num23 < 10; num23++)
                    {
                        WorldGen.TileRunner(array[num23], array2[num23], (double)WorldGen.genRand.Next(5, 8), WorldGen.genRand.Next(6, 9), 0, true, -2.0, -0.3, false, true, -1);
                        WorldGen.TileRunner(array[num23], array2[num23], (double)WorldGen.genRand.Next(5, 8), WorldGen.genRand.Next(6, 9), 0, true, 2.0, -0.3, false, true, -1);
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.MountainCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    return;
                }
                GenVars.numMCaves = 0;
                progress.Message = Lang.gen[2].Value;
                progress.Set(0.0);
                int num24 = (int)((double)Main.maxTilesX * 0.001);
                if (WorldGen.remixWorldGen)
                {
                    num24 = (int)((double)num24 * 1.5);
                }
                for (int num25 = 0; num25 < num24; num25++)
                {
                    progress.Set((double)((float)num25 / (float)num24));
                    int num26 = 0;
                    bool flag6 = false;
                    bool flag7 = false;
                    int num27 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.75));
                    while (!flag7)
                    {
                        flag7 = true;
                        if (!WorldGen.remixWorldGen)
{
                            while (num27 > Main.maxTilesX / 2 - 90 && num27 < Main.maxTilesX / 2 + 90)
{
                                num27 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.75));
                            }
                        }
                        for (int num28 = 0; num28 < GenVars.numMCaves; num28++)
{
                            if (Math.Abs(num27 - GenVars.mCaveX[num28]) < 100)
{
                                num26++;
                                flag7 = false;
                                break;
                            }
                        }
                        if (num26 >= Main.maxTilesX / 5)
{
                            flag6 = true;
                            break;
                        }
                    }
                    if (!flag6)
                    {
                        int num29 = 0;
                        while ((double)num29 < Main.worldSurface)
{
                            if (Main.tile[num27, num29].active())
{
                                for (int num30 = num27 - 50; num30 < num27 + 50; num30++)
{
                                    for (int num31 = num29 - 25; num31 < num29 + 25; num31++)
{
                                        if (WorldGen.InWorld(num30, num31, 0) && Main.tile[num30, num31].active() && (Main.tile[num30, num31].type == 53 || Main.tile[num30, num31].type == 151 || Main.tile[num30, num31].type == 274))
{
                                            flag6 = true;
                                        }
                                    }
                                }
                                if (!flag6)
{
                                    WorldGen.Mountinater(num27, num29);
                                    GenVars.mCaveX[GenVars.numMCaves] = num27;
                                    GenVars.mCaveY[GenVars.numMCaves] = num29;
                                    GenVars.numMCaves++;
                                    break;
                                }
                            }
                            num29++;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtWallBackgrounds, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[3].Value;
                int num32 = 0;
                for (int num33 = 1; num33 < Main.maxTilesX - 1; num33++)
                {
                    ushort num34 = 2;
                    double num35 = (double)num33 / (double)Main.maxTilesX;
                    progress.Set(num35);
                    bool flag8 = false;
                    num32 += WorldGen.genRand.Next(-1, 2);
                    if (num32 < 0)
                    {
                        num32 = 0;
                    }
                    if (num32 > 10)
                    {
                        num32 = 10;
                    }
                    int num36 = 0;
                    while ((double)num36 < Main.worldSurface + 10.0 && (double)num36 <= Main.worldSurface + (double)num32)
                    {
                        if (Main.tile[num33, num36].active())
{
                            if (Main.tile[num33, num36].type == 147)
{
                                num34 = 40;
                            }
                            else
{
                                num34 = 2;
                            }
                        }
                        if (flag8 && Main.tile[num33, num36].wall != 64)
{
                            Main.tile[num33, num36].wall = num34;
                        }
                        if (Main.tile[num33, num36].active() && Main.tile[num33 - 1, num36].active() && Main.tile[num33 + 1, num36].active() && Main.tile[num33, num36 + 1].active() && Main.tile[num33 - 1, num36 + 1].active() && Main.tile[num33 + 1, num36 + 1].active())
{
                            flag8 = true;
                        }
                        num36++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.RocksInDirt, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[4].Value;
                double num37 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.00015;
                int num38 = 0;
                while ((double)num38 < num37)
                {
                    WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(0, (int)GenVars.worldSurfaceLow + 1), (double)WorldGen.genRand.Next(4, 15), WorldGen.genRand.Next(5, 40), 1, false, 0.0, 0.0, false, true, -1);
                    num38++;
                }
                progress.Set(0.34);
                num37 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0002;
                int num39 = 0;
                while ((double)num39 < num37)
                {
                    int num40 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    int num41 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1);
                    if (!Main.tile[num40, num41 - 10].active())
                    {
                        num41 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1);
                    }
                    WorldGen.TileRunner(num40, num41, (double)WorldGen.genRand.Next(4, 10), WorldGen.genRand.Next(5, 30), 1, false, 0.0, 0.0, false, true, -1);
                    num39++;
                }
                progress.Set(0.67);
                num37 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0045;
                int num42 = 0;
                while ((double)num42 < num37)
                {
                    WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh + 1), (double)WorldGen.genRand.Next(2, 7), WorldGen.genRand.Next(2, 23), 1, false, 0.0, 0.0, false, true, -1);
                    num42++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtInRocks, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[5].Value;
                double num43 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.005;
                int num44 = 0;
                while ((double)num44 < num43)
                {
                    progress.Set((double)num44 / num43);
                    WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(2, 6), WorldGen.genRand.Next(2, 40), 0, false, 0.0, 0.0, false, true, -1);
                    num44++;
                }
                if (WorldGen.remixWorldGen)
                {
                    for (int num45 = 0; num45 < Main.maxTilesX; num45++)
                    {
                        for (int num46 = (int)Main.worldSurface + WorldGen.genRand.Next(-1, 3); num46 < Main.maxTilesY; num46++)
{
                            if (Main.tile[num45, num46].active())
{
                                if (Main.tile[num45, num46].type == 0)
{
                                    Main.tile[num45, num46].type = 1;
                                }
                                else if (Main.tile[num45, num46].type == 1)
{
                                    Main.tile[num45, num46].type = 0;
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Clay, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[6].Value;
                for (int num47 = 0; num47 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05); num47++)
                {
                    WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(0, (int)GenVars.worldSurfaceLow), (double)WorldGen.genRand.Next(4, 14), WorldGen.genRand.Next(10, 50), 40, false, 0.0, 0.0, false, true, -1);
                }
                progress.Set(0.25);
                if (WorldGen.remixWorldGen)
                {
                    for (int num48 = 0; num48 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 7E-05); num48++)
                    {
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayer - 25, Main.maxTilesY - 350), (double)WorldGen.genRand.Next(8, 15), WorldGen.genRand.Next(5, 50), 40, false, 0.0, 0.0, false, true, -1);
                    }
                }
                else
                {
                    for (int num49 = 0; num49 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 5E-05); num49++)
                    {
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh + 1), (double)WorldGen.genRand.Next(8, 14), WorldGen.genRand.Next(15, 45), 40, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set(0.5);
                    for (int num50 = 0; num50 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05); num50++)
                    {
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh + 1), (double)WorldGen.genRand.Next(8, 15), WorldGen.genRand.Next(5, 50), 40, false, 0.0, 0.0, false, true, -1);
                    }
                }
                progress.Set(0.75);
                for (int num51 = 5; num51 < Main.maxTilesX - 5; num51++)
                {
                    int num52 = 1;
                    while ((double)num52 < Main.worldSurface - 1.0)
                    {
                        if (Main.tile[num51, num52].active())
{
                            for (int num53 = num52; num53 < num52 + 5; num53++)
{
                                if (Main.tile[num51, num53].type == 40)
{
                                    Main.tile[num51, num53].type = 0;
                                }
                            }
                            break;
                        }
                        num52++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SmallHoles, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[7].Value;
                double worldSurfaceHigh = GenVars.worldSurfaceHigh;
                int num54 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0015);
                for (int num55 = 0; num55 < num54; num55++)
                {
                    double num56 = (double)num55 / ((double)(Main.maxTilesX * Main.maxTilesY) * 0.0015);
                    progress.Set(num56);
                    int num57 = -1;
                    if (WorldGen.genRand.Next(5) == 0)
                    {
                        num57 = -2;
                    }
                    int num58 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    int num59 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    if (!WorldGen.remixWorldGen && WorldGen.tenthAnniversaryWorldGen)
                    {
                        while ((double)num58 < (double)Main.maxTilesX * 0.2 && (double)num58 > (double)Main.maxTilesX * 0.8)
{
                            if ((double)num59 >= GenVars.worldSurface)
{
                                break;
                            }
                            num58 = WorldGen.genRand.Next(0, Main.maxTilesX);
                            num59 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                        }
                    }
                    else
                    {
                        while (((num58 < GenVars.smallHolesBeachAvoidance || num58 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num59 < worldSurfaceHigh) || ((double)num58 > (double)Main.maxTilesX * 0.45 && (double)num58 < (double)Main.maxTilesX * 0.55 && (double)num59 < GenVars.worldSurface))
{
                            num58 = WorldGen.genRand.Next(0, Main.maxTilesX);
                            num59 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                        }
                    }
                    int num60 = WorldGen.genRand.Next(2, 5);
                    int num61 = WorldGen.genRand.Next(2, 20);
                    if (WorldGen.remixWorldGen && (double)num59 > Main.rockLayer)
                    {
                        num60 = (int)((double)num60 * 0.8);
                        num61 = (int)((double)num61 * 0.9);
                    }
                    WorldGen.TileRunner(num58, num59, (double)num60, num61, num57, false, 0.0, 0.0, false, true, -1);
                    num58 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    num59 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    while (((num58 < GenVars.smallHolesBeachAvoidance || num58 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num59 < worldSurfaceHigh) || ((double)num58 > (double)Main.maxTilesX * 0.45 && (double)num58 < (double)Main.maxTilesX * 0.55 && (double)num59 < GenVars.worldSurface))
                    {
                        num58 = WorldGen.genRand.Next(0, Main.maxTilesX);
                        num59 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY);
                    }
                    num60 = WorldGen.genRand.Next(8, 15);
                    num61 = WorldGen.genRand.Next(7, 30);
                    if (WorldGen.remixWorldGen && (double)num59 > Main.rockLayer)
                    {
                        num60 = (int)((double)num60 * 0.7);
                        num61 = (int)((double)num61 * 0.9);
                    }
                    WorldGen.TileRunner(num58, num59, (double)num60, num61, num57, false, 0.0, 0.0, false, true, -1);
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtLayerCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[8].Value;
                double worldSurfaceHigh2 = GenVars.worldSurfaceHigh;
                int num62 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05);
                if (WorldGen.remixWorldGen)
                {
                    num62 *= 2;
                }
                for (int num63 = 0; num63 < num62; num63++)
                {
                    double num64 = (double)num63 / (double)num62;
                    progress.Set(num64);
                    if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                    {
                        int num65 = -1;
                        if (WorldGen.genRand.Next(6) == 0)
{
                            num65 = -2;
                        }
                        int num66 = WorldGen.genRand.Next(0, Main.maxTilesX);
                        int num67 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.rockLayerHigh + 1);
                        while (((num66 < GenVars.smallHolesBeachAvoidance || num66 > Main.maxTilesX - GenVars.smallHolesBeachAvoidance) && (double)num67 < worldSurfaceHigh2) || ((double)num66 >= (double)Main.maxTilesX * 0.45 && (double)num66 <= (double)Main.maxTilesX * 0.55 && (double)num67 < Main.worldSurface))
{
                            num66 = WorldGen.genRand.Next(0, Main.maxTilesX);
                            num67 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.rockLayerHigh + 1);
                        }
                        int num68 = WorldGen.genRand.Next(5, 15);
                        int num69 = WorldGen.genRand.Next(30, 200);
                        if (WorldGen.remixWorldGen)
{
                            num68 = (int)((double)num68 * 1.1);
                            num69 = (int)((double)num69 * 1.9);
                        }
                        WorldGen.TileRunner(num66, num67, (double)num68, num69, num65, false, 0.0, 0.0, false, true, -1);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.RockLayerCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[9].Value;
                int num70 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00013);
                if (WorldGen.remixWorldGen)
                {
                    num70 = (int)((double)num70 * 1.1);
                }
                for (int num71 = 0; num71 < num70; num71++)
                {
                    double num72 = (double)num71 / (double)num70;
                    progress.Set(num72);
                    if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
                    {
                        int num73 = -1;
                        if (WorldGen.genRand.Next(10) == 0)
{
                            num73 = -2;
                        }
                        int num74 = WorldGen.genRand.Next(6, 20);
                        int num75 = WorldGen.genRand.Next(50, 300);
                        if (WorldGen.remixWorldGen)
{
                            num74 = (int)((double)num74 * 0.7);
                            num75 = (int)((double)num75 * 0.7);
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY), (double)num74, num75, num73, false, 0.0, 0.0, false, true, -1);
                    }
                }
                if (WorldGen.remixWorldGen)
                {
                    num70 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00013 * 0.4);
                    for (int num76 = 0; num76 < num70; num76++)
                    {
                        if (GenVars.rockLayerHigh <= (double)Main.maxTilesY)
{
                            int num77 = -1;
                            if (WorldGen.genRand.Next(10) == 0)
{
                                num77 = -2;
                            }
                            int num78 = WorldGen.genRand.Next(7, 26);
                            int num79 = WorldGen.genRand.Next(50, 200);
                            double num80 = (double)WorldGen.genRand.Next(100, 221) * 0.1;
                            double num81 = (double)WorldGen.genRand.Next(-10, 11) * 0.02;
                            int num82 = WorldGen.genRand.Next(0, Main.maxTilesX);
                            int num83 = WorldGen.genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                            WorldGen.TileRunner(num82, num83, (double)num78, num79, num77, false, num80, num81, true, true, -1);
                            WorldGen.TileRunner(num82, num83, (double)num78, num79, num77, false, -num80, -num81, true, true, -1);
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SurfaceCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[10].Value;
                int num84 = (int)((double)Main.maxTilesX * 0.002);
                int num85 = (int)((double)Main.maxTilesX * 0.0007);
                int num86 = (int)((double)Main.maxTilesX * 0.0003);
                if (WorldGen.remixWorldGen)
                {
                    num84 *= 3;
                    num85 *= 3;
                    num86 *= 3;
                }
                for (int num87 = 0; num87 < num84; num87++)
                {
                    progress.Set((double)((float)num87 / (float)num84 * 0.2f));
                    int num88 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    while (((double)num88 > (double)Main.maxTilesX * 0.45 && (double)num88 < (double)Main.maxTilesX * 0.55) || num88 < GenVars.leftBeachEnd + 20 || num88 > GenVars.rightBeachStart - 20)
                    {
                        num88 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    }
                    int num89 = 0;
                    while ((double)num89 < GenVars.worldSurfaceHigh)
                    {
                        if (Main.tile[num88, num89].active())
{
                            WorldGen.TileRunner(num88, num89, (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(5, 50), -1, false, (double)WorldGen.genRand.Next(-10, 11) * 0.1, 1.0, false, true, -1);
                            break;
                        }
                        num89++;
                    }
                }
                progress.Set(0.20000000298023224);
                for (int num90 = 0; num90 < num85; num90++)
                {
                    progress.Set((double)(0.2f + (float)num90 / (float)num85 * 0.2f));
                    int num91 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    while (((double)num91 > (double)Main.maxTilesX * 0.43 && (double)num91 < (double)Main.maxTilesX * 0.5700000000000001) || num91 < GenVars.leftBeachEnd + 20 || num91 > GenVars.rightBeachStart - 20)
                    {
                        num91 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    }
                    int num92 = 0;
                    while ((double)num92 < GenVars.worldSurfaceHigh)
                    {
                        if (Main.tile[num91, num92].active())
{
                            WorldGen.TileRunner(num91, num92, (double)WorldGen.genRand.Next(10, 15), WorldGen.genRand.Next(50, 130), -1, false, (double)WorldGen.genRand.Next(-10, 11) * 0.1, 2.0, false, true, -1);
                            break;
                        }
                        num92++;
                    }
                }
                progress.Set(0.4000000059604645);
                for (int num93 = 0; num93 < num86; num93++)
                {
                    progress.Set((double)(0.4f + (float)num93 / (float)num86 * 0.2f));
                    int num94 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    while (((double)num94 > (double)Main.maxTilesX * 0.4 && (double)num94 < (double)Main.maxTilesX * 0.6) || num94 < GenVars.leftBeachEnd + 20 || num94 > GenVars.rightBeachStart - 20)
                    {
                        num94 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    }
                    int num95 = 0;
                    while ((double)num95 < GenVars.worldSurfaceHigh)
                    {
                        if (Main.tile[num94, num95].active())
{
                            WorldGen.TileRunner(num94, num95, (double)WorldGen.genRand.Next(12, 25), WorldGen.genRand.Next(150, 500), -1, false, (double)WorldGen.genRand.Next(-10, 11) * 0.1, 4.0, false, true, -1);
                            WorldGen.TileRunner(num94, num95, (double)WorldGen.genRand.Next(8, 17), WorldGen.genRand.Next(60, 200), -1, false, (double)WorldGen.genRand.Next(-10, 11) * 0.1, 2.0, false, true, -1);
                            WorldGen.TileRunner(num94, num95, (double)WorldGen.genRand.Next(5, 13), WorldGen.genRand.Next(40, 170), -1, false, (double)WorldGen.genRand.Next(-10, 11) * 0.1, 2.0, false, true, -1);
                            break;
                        }
                        num95++;
                    }
                }
                progress.Set(0.6000000238418579);
                int num96 = (int)((double)Main.maxTilesX * 0.0004);
                for (int num97 = 0; num97 < num96; num97++)
                {
                    progress.Set((double)(0.6f + (float)num97 / (float)num96 * 0.2f));
                    int num98 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    while (((double)num98 > (double)Main.maxTilesX * 0.4 && (double)num98 < (double)Main.maxTilesX * 0.6) || num98 < GenVars.leftBeachEnd + 20 || num98 > GenVars.rightBeachStart - 20)
                    {
                        num98 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    }
                    int num99 = 0;
                    while ((double)num99 < GenVars.worldSurfaceHigh)
                    {
                        if (Main.tile[num98, num99].active())
{
                            WorldGen.TileRunner(num98, num99, (double)WorldGen.genRand.Next(7, 12), WorldGen.genRand.Next(150, 250), -1, false, 0.0, 1.0, true, true, -1);
                            break;
                        }
                        num99++;
                    }
                }
                progress.Set(0.800000011920929);
                double num100 = (double)Main.maxTilesX / 4200.0;
                int num101 = (int)(5.0 * num100);
                for (int num102 = 0; num102 < num101; num102++)
                {
                    progress.Set((double)(0.8f + (float)num102 / (float)num101 * 0.2f));
                    try
                    {
                        int num103 = (int)Main.rockLayer;
                        int num104 = Main.maxTilesY - 400;
                        if (num103 >= num104)
{
                            num103 = num104 - 1;
                        }
                        WorldGen.Caverer(WorldGen.genRand.Next(GenVars.surfaceCavesBeachAvoidance2, Main.maxTilesX - GenVars.surfaceCavesBeachAvoidance2), WorldGen.genRand.Next(num103, num104));
                    }
                    catch
                    {
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.WavyCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.dontStarveWorldGen)
                {
                    progress.Message = Language.GetTextValue("WorldGeneration.WavyCaves");
                    double num105 = (double)Main.maxTilesX / 4200.0;
                    num105 *= num105;
                    int num106 = (int)(35.0 * num105);
                    if (Main.remixWorld)
                    {
                        num106 /= 3;
                    }
                    int num107 = 0;
                    int num108 = 80;
                    for (int num109 = 0; num109 < num106; num109++)
                    {
                        double num110 = (double)num109 / (double)(num106 - 1);
                        progress.Set(num110);
                        int num111 = WorldGen.genRand.Next((int)Main.worldSurface + 100, Main.UnderworldLayer - 100);
                        int num112 = 0;
                        while (Math.Abs(num111 - num107) < num108)
{
                            num112++;
                            if (num112 > 100)
{
                                break;
                            }
                            num111 = WorldGen.genRand.Next((int)Main.worldSurface + 100, Main.UnderworldLayer - 100);
                        }
                        num107 = num111;
                        int num113 = 80;
                        int num114 = num113 + (int)((double)(Main.maxTilesX - num113 * 2) * num110);
                        try
{
                            WorldGen.WavyCaverer(num114, num111, (double)(12 + WorldGen.genRand.Next(3, 6)), 0.25 + WorldGen.genRand.NextDouble(), WorldGen.genRand.Next(300, 500), -1);
                        }
                        catch
{
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.IceBiome, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[56].Value;
                GenVars.snowTop = (int)Main.worldSurface;
                int num115 = GenVars.lavaLine - WorldGen.genRand.Next(160, 200);
                int num116 = GenVars.lavaLine;
                if (WorldGen.remixWorldGen)
                {
                    num116 = Main.maxTilesY - 250;
                    num115 = num116 - WorldGen.genRand.Next(160, 200);
                }
                int num117 = GenVars.snowOriginLeft;
                int num118 = GenVars.snowOriginRight;
                int num119 = 10;
                for (int num120 = 0; num120 <= num116 - 140; num120++)
                {
                    progress.Set((double)num120 / (double)(num116 - 140));
                    num117 += WorldGen.genRand.Next(-4, 4);
                    num118 += WorldGen.genRand.Next(-3, 5);
                    if (num120 > 0)
                    {
                        num117 = (num117 + GenVars.snowMinX[num120 - 1]) / 2;
                        num118 = (num118 + GenVars.snowMaxX[num120 - 1]) / 2;
                    }
                    if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
                    {
                        if (WorldGen.genRand.Next(4) == 0)
{
                            num117++;
                            num118++;
                        }
                    }
                    else if (WorldGen.genRand.Next(4) == 0)
                    {
                        num117--;
                        num118--;
                    }
                    GenVars.snowMinX[num120] = num117;
                    GenVars.snowMaxX[num120] = num118;
                    for (int num121 = num117; num121 < num118; num121++)
                    {
                        if (num120 < num115)
{
                            if (Main.tile[num121, num120].wall == 2)
{
                                Main.tile[num121, num120].wall = 40;
                            }
                            int type = (int)Main.tile[num121, num120].type;
                            if (type == 0 || type == 2 || type == 23 || type == 40 || type == 53)
{
                                Main.tile[num121, num120].type = 147;
                            }
                            else if (type == 1)
{
                                Main.tile[num121, num120].type = 161;
                            }
                        }
                        else
{
                            num119 += WorldGen.genRand.Next(-3, 4);
                            if (WorldGen.genRand.Next(3) == 0)
{
                                num119 += WorldGen.genRand.Next(-4, 5);
                                if (WorldGen.genRand.Next(3) == 0)
{
                                    num119 += WorldGen.genRand.Next(-6, 7);
                                }
                            }
                            if (num119 < 0)
{
                                num119 = WorldGen.genRand.Next(3);
                            }
                            else if (num119 > 50)
{
                                num119 = 50 - WorldGen.genRand.Next(3);
                            }
                            for (int num122 = num120; num122 < num120 + num119; num122++)
{
                                if (Main.tile[num121, num122].wall == 2)
{
                                    Main.tile[num121, num122].wall = 40;
                                }
                                int type2 = (int)Main.tile[num121, num122].type;
                                if (type2 == 0 || type2 == 2 || type2 == 23 || type2 == 40 || type2 == 53)
{
                                    Main.tile[num121, num122].type = 147;
                                }
                                else if (type2 == 1)
{
                                    Main.tile[num121, num122].type = 161;
                                }
                            }
                        }
                    }
                    if (GenVars.snowBottom < num120)
                    {
                        GenVars.snowBottom = num120;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Grass, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.digExtraHoles.Enabled)
                {
                    WorldGen.SecretSeed.DoDigExtraHoles();
                }
                if (WorldGen.SecretSeed.roundLandmasses.Enabled)
                {
                    WorldGen.SecretSeed.DoRoundLandMasses();
                }
                double num123 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.002;
                int num124 = 0;
                while ((double)num124 < num123)
                {
                    progress.Set((double)num124 / num123);
                    int num125 = WorldGen.genRand.Next(1, Main.maxTilesX - 1);
                    int num126 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh);
                    if (num126 >= Main.maxTilesY)
                    {
                        num126 = Main.maxTilesY - 2;
                    }
                    if (Main.tile[num125 - 1, num126].active() && Main.tile[num125 - 1, num126].type == 0 && Main.tile[num125 + 1, num126].active() && Main.tile[num125 + 1, num126].type == 0 && Main.tile[num125, num126 - 1].active() && Main.tile[num125, num126 - 1].type == 0 && Main.tile[num125, num126 + 1].active() && Main.tile[num125, num126 + 1].type == 0)
                    {
                        Main.tile[num125, num126].active(true);
                        Main.tile[num125, num126].type = 2;
                    }
                    num125 = WorldGen.genRand.Next(1, Main.maxTilesX - 1);
                    num126 = WorldGen.genRand.Next(5, (int)GenVars.worldSurfaceLow);
                    if (num126 >= Main.maxTilesY)
                    {
                        num126 = Main.maxTilesY - 2;
                    }
                    if (Main.tile[num125 - 1, num126].active() && Main.tile[num125 - 1, num126].type == 0 && Main.tile[num125 + 1, num126].active() && Main.tile[num125 + 1, num126].type == 0 && Main.tile[num125, num126 - 1].active() && Main.tile[num125, num126 - 1].type == 0 && Main.tile[num125, num126 + 1].active() && Main.tile[num125, num126 + 1].type == 0)
                    {
                        Main.tile[num125, num126].active(true);
                        Main.tile[num125, num126].type = 2;
                    }
                    num124++;
                }
            });
            if (!WorldGen.Skyblock.denyAllGeneration)
            {
                WorldGen.AddGenerationPass(new JunglePass());
            }
            WorldGen.AddGenerationPass(GenPassNameID.MudCavesToJungleGrass, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[77].Value;
                WorldGen.NotTheBees();
                if (WorldGen.SecretSeed.surfaceIsMushrooms.Enabled && !WorldGen.SecretSeed.noSurface.Enabled)
                {
                    WorldGen.SecretSeed.DoSurfaceIsMushrooms();
                }
                for (int num127 = 0; num127 < Main.maxTilesX; num127++)
                {
                    for (int num128 = 0; num128 < Main.maxTilesY; num128++)
                    {
                        if (Main.tile[num127, num128].active())
{
                            WorldGen.grassSpread = 0;
                            WorldGen.SpreadGrass(num127, num128, 59, 60, true, default(TileColorCache));
                        }
                        progress.Set(0.2 * ((double)(num127 * Main.maxTilesY + num128) / (double)(Main.maxTilesX * Main.maxTilesY)));
                    }
                }
                WorldGen.SmallConsecutivesFound = 0;
                WorldGen.SmallConsecutivesEliminated = 0;
                double num129 = (double)(Main.maxTilesX - 20);
                for (int num130 = 10; num130 < Main.maxTilesX - 10; num130++)
                {
                    WorldGen.ScanTileColumnAndRemoveClumps(num130);
                    double num131 = (double)(num130 - 10) / num129;
                    progress.Set(0.2 + num131 * 0.8);
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DesertBiome, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[78].Value;
                Main.tileSolid[484] = false;
                int num132 = 0;
                int num133 = GenVars.CurrentDungeonGenVars.dungeonSide;
                int num134 = Main.maxTilesX / 2;
                int num135 = WorldGen.genRand.Next(num134) / 8;
                num135 += num134 / 8;
                int num136 = num134 + num135 * -num133;
                int num137 = 0;
                DesertBiome desertBiome = GenVars.configuration.CreateBiome<DesertBiome>();
                while (!desertBiome.Place(new Point(num136, (int)GenVars.worldSurfaceHigh + 25), GenVars.structures, progress))
                {
                    num135 = WorldGen.genRand.Next(num134) / 2;
                    num135 += num134 / 8;
                    num135 += WorldGen.genRand.Next(num137 / 12);
                    num136 = num134 + num135 * -num133;
                    if (++num137 > Main.maxTilesX / 4)
                    {
                        num133 *= -1;
                        num137 = 0;
                        num132++;
                        if (num132 >= 2)
{
                            GenVars.skipDesertTileCheck = true;
                        }
                    }
                }
                if (WorldGen.remixWorldGen && !WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
                {
                    for (int num138 = 50; num138 < Main.maxTilesX - 50; num138++)
                    {
                        for (int num139 = (int)Main.rockLayer + WorldGen.genRand.Next(-1, 2); num139 < Main.maxTilesY - 50; num139++)
{
                            if (Main.tile[num138, num139].active() && (Main.tile[num138, num139].type == 396 || Main.tile[num138, num139].type == 397 || Main.tile[num138, num139].type == 53) && !WorldGen.SolidTile(num138, num139 - 1, false))
{
                                int num140 = num139;
                                while (num140 < num139 + WorldGen.genRand.Next(4, 7) && Main.tile[num138, num140 + 1].active() && (Main.tile[num138, num140].type == 396 || Main.tile[num138, num140].type == 397))
{
                                    Main.tile[num138, num140].type = 53;
                                    num140++;
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.GlowingMushroomPatches, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[13].Value;
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    WorldGen.SecretSeed.DoSurfaceIsDesert();
                }
                if (WorldGen.remixWorldGen)
                {
                    for (int num141 = 10; num141 < Main.maxTilesX - 10; num141++)
                    {
                        for (int num142 = GenVars.remixMushroomLayerLow + WorldGen.genRand.Next(3); num142 < Main.maxTilesY - 10; num142++)
{
                            if (Main.tile[num141, num142].type == 0)
{
                                Main.tile[num141, num142].type = 59;
                            }
                        }
                    }
                }
                double num143 = (double)Main.maxTilesX / 700.0;
                if (num143 > (double)GenVars.maxMushroomBiomes)
                {
                    num143 = (double)GenVars.maxMushroomBiomes;
                }
                int num144 = 0;
                while ((double)num144 < num143)
                {
                    progress.Set((double)((float)num144 / (float)num143), 0.0, 0.33000001311302185);
                    int num145 = 0;
                    bool flag9 = true;
                    while (flag9)
                    {
                        int num146 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                        if (num145 > Main.maxTilesX / 4)
{
                            num146 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.025), (int)((double)Main.maxTilesX * 0.975));
                        }
                        int num147;
                        if (WorldGen.SecretSeed.errorWorld.Enabled && !WorldGen.notTheBees)
{
                            num147 = WorldGen.genRand.Next(200, Main.maxTilesY - 300);
                            while ((double)num147 < Main.worldSurface + 300.0 && num146 > Main.maxTilesX / 2 - 300)
{
                                if (num146 >= Main.maxTilesX / 2 + 300)
{
                                    break;
                                }
                                num146 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                                num147 = WorldGen.genRand.Next(200, Main.maxTilesY - 300);
                            }
                        }
                        else if (WorldGen.remixWorldGen)
{
                            num147 = WorldGen.genRand.Next((int)Main.worldSurface + 50, (int)Main.rockLayer - 50);
                        }
                        else
{
                            num147 = WorldGen.genRand.Next((int)Main.rockLayer + 50, Main.maxTilesY - 300);
                        }
                        flag9 = false;
                        int num148 = 100;
                        int num149 = 500;
                        if (WorldGen.SecretSeed.dualDungeons.Enabled)
{
                            int num150 = num146 - num148;
                            int num151 = num147 - num148;
                            int num152 = num146 + num148;
                            int num153 = num147 + num148;
                            if (DungeonUtils.IntersectsAnyPotentialDungeonBounds(new Rectangle(num150, num151, num152 - num150, num153 - num151), false))
{
                                flag9 = true;
                            }
                        }
                        if (!flag9)
{
                            for (int num154 = num146 - num148; num154 < num146 + num148; num154 += 3)
{
                                for (int num155 = num147 - num148; num155 < num147 + num148; num155 += 3)
{
                                    if (WorldGen.InWorld(num154, num155, 0))
{
                                        Tile tile = Main.tile[num154, num155];
                                        if (tile.active() && (tile.type == 147 || tile.type == 161 || tile.type == 162 || tile.type == 60 || tile.type == 368 || tile.type == 367))
{
                                            flag9 = true;
                                            break;
                                        }
                                        if (GenVars.UndergroundDesertLocation.Contains(new Point(num154, num155)))
{
                                            flag9 = true;
                                            break;
                                        }
                                    }
                                    else
{
                                        flag9 = true;
                                    }
                                }
                            }
                        }
                        if (!flag9)
{
                            for (int num156 = 0; num156 < GenVars.numMushroomBiomes; num156++)
{
                                if (Vector2D.Distance(GenVars.mushroomBiomesPosition[num156].ToVector2D(), new Vector2D((double)num146, (double)num147)) < (double)num149)
{
                                    flag9 = true;
                                }
                            }
                        }
                        if (!flag9 && GenVars.numMushroomBiomes < GenVars.maxMushroomBiomes)
{
                            WorldGen.ShroomPatch(num146, num147);
                            for (int num157 = 0; num157 < 5; num157++)
{
                                int num158 = num146 + WorldGen.genRand.Next(-40, 41);
                                int num159 = num147 + WorldGen.genRand.Next(-40, 41);
                                WorldGen.ShroomPatch(num158, num159);
                            }
                            GenVars.mushroomBiomesPosition[GenVars.numMushroomBiomes].X = num146;
                            GenVars.mushroomBiomesPosition[GenVars.numMushroomBiomes].Y = num147;
                            GenVars.numMushroomBiomes++;
                        }
                        num145++;
                        if (num145 > Main.maxTilesX / 2)
{
                            break;
                        }
                    }
                    num144++;
                }
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    for (int num160 = 0; num160 < Main.maxTilesX; num160++)
                    {
                        progress.Set((double)((float)num160 / (float)Main.maxTilesX), 0.33000001311302185, 0.6600000262260437);
                        for (int num161 = 0; num161 < Main.maxTilesY; num161++)
{
                            if (WorldGen.InWorld(num160, num161, 50) && Main.tile[num160, num161].active())
{
                                WorldGen.grassSpread = 0;
                                WorldGen.SpreadGrass(num160, num161, 59, 70, false, default(TileColorCache));
                            }
                        }
                    }
                }
                else
                {
                    for (int num162 = 0; num162 < Main.maxTilesX; num162++)
                    {
                        progress.Set((double)((float)num162 / (float)Main.maxTilesX), 0.33000001311302185, 0.6600000262260437);
                        for (int num163 = (int)Main.worldSurface; num163 < Main.maxTilesY; num163++)
{
                            if (WorldGen.InWorld(num162, num163, 50) && Main.tile[num162, num163].active())
{
                                WorldGen.grassSpread = 0;
                                WorldGen.SpreadGrass(num162, num163, 59, 70, false, default(TileColorCache));
                            }
                        }
                    }
                }
                for (int num164 = 0; num164 < Main.maxTilesX; num164++)
                {
                    progress.Set((double)((float)num164 / (float)Main.maxTilesX), 0.6600000262260437, 1.0);
                    for (int num165 = (int)Main.worldSurface; num165 < Main.maxTilesY; num165++)
                    {
                        if (Main.tile[num164, num165].active() && Main.tile[num164, num165].type == 70)
{
                            int num166 = 59;
                            for (int num167 = num164 - 1; num167 <= num164 + 1; num167++)
{
                                for (int num168 = num165 - 1; num168 <= num165 + 1; num168++)
{
                                    if (Main.tile[num167, num168].active())
{
                                        if (!Main.tile[num167 - 1, num168].active() && !Main.tile[num167 + 1, num168].active())
{
                                            WorldGen.KillTile(num167, num168, false, false, false);
                                        }
                                        else if (!Main.tile[num167, num168 - 1].active() && !Main.tile[num167, num168 + 1].active())
{
                                            WorldGen.KillTile(num167, num168, false, false, false);
                                        }
                                    }
                                    else if (Main.tile[num167 - 1, num168].active() && Main.tile[num167 + 1, num168].active())
{
                                        WorldGen.PlaceTile(num167, num168, num166, false, false, -1, 0);
                                        if (Main.tile[num167 - 1, num165].type == 70)
{
                                            Main.tile[num167 - 1, num165].type = 59;
                                        }
                                        if (Main.tile[num167 + 1, num165].type == 70)
{
                                            Main.tile[num167 + 1, num165].type = 59;
                                        }
                                    }
                                    else if (Main.tile[num167, num168 - 1].active() && Main.tile[num167, num168 + 1].active())
{
                                        WorldGen.PlaceTile(num167, num168, num166, false, false, -1, 0);
                                        if (Main.tile[num167, num165 - 1].type == 70)
{
                                            Main.tile[num167, num165 - 1].type = 59;
                                        }
                                        if (Main.tile[num167, num165 + 1].type == 70)
{
                                            Main.tile[num167, num165 + 1].type = 59;
                                        }
                                    }
                                }
                            }
                            if (WorldGen.genRand.Next(4) == 0)
{
                                int num169 = num164 + WorldGen.genRand.Next(-20, 21);
                                int num170 = num165 + WorldGen.genRand.Next(-20, 21);
                                if (WorldGen.InWorld(num169, num170, 0) && Main.tile[num169, num170].type == 59)
{
                                    Main.tile[num169, num170].type = 70;
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Marble, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[80].Value;
                int num171 = passConfig.Get<WorldGenRange>("Count").GetRandom(WorldGen.genRand);
                if (WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    num171 /= 2;
                }
                double num172 = (double)(Main.maxTilesX - 160) / (double)num171;
                MarbleBiome marbleBiome = GenVars.configuration.CreateBiome<MarbleBiome>();
                int num173 = 0;
                int num174 = 0;
                while (num174 < num171)
                {
                    double num175 = (double)num174 / (double)num171;
                    progress.Set(num175);
                    Point point2 = Point.Zero;
                    bool flag10 = false;
                    int num176 = 100;
                    while (!flag10)
                    {
                        num176--;
                        if (num176 <= 0)
{
                            break;
                        }
                        if (WorldGen.SecretSeed.dualDungeons.Enabled)
{
                            int num177 = 120;
                            int num178 = num177 + 1;
                            int num179;
                            if (num174 != 0)
{
                                if (num174 != 1)
{
                                    num179 = num177;
                                    num178 = Main.maxTilesX - num177;
                                }
                                else
{
                                    num179 = Main.maxTilesX - num177 - 100;
                                    num178 = Main.maxTilesX - num177;
                                }
                            }
                            else
{
                                num179 = num177;
                                num178 = num177 + 100;
                            }
                            if (WorldGen.remixWorldGen)
{
                                point2 = WorldGen.RandomRectanglePoint(num179, (int)GenVars.worldSurface + 100, num178 - num179, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                            }
                            else
{
                                point2 = WorldGen.RandomRectanglePoint(num179, (int)GenVars.rockLayer + 20, num178 - num179, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                            }
                            int num180 = 40;
                            int num181 = point2.X - num180;
                            int num182 = point2.Y - num180;
                            int num183 = point2.X + num180;
                            int num184 = point2.Y + num180;
                            flag10 = !DungeonUtils.IntersectsAnyPotentialDungeonBounds(new Rectangle(num181, num182, num183 - num181, num184 - num182), false);
                        }
                        else if (WorldGen.remixWorldGen)
{
                            point2 = WorldGen.RandomRectanglePoint((int)(num175 * (double)(Main.maxTilesX - 200)) + 100, (int)GenVars.worldSurface + 100, (int)num172, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                        }
                        else
{
                            point2 = WorldGen.RandomRectanglePoint((int)(num175 * (double)(Main.maxTilesX - 200)) + 100, (int)GenVars.rockLayer + 20, (int)num172, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                        }
                        if (!WorldGen.SecretSeed.dualDungeons.Enabled)
{
                            while ((double)point2.X > (double)Main.maxTilesX * 0.45 && (double)point2.X < (double)Main.maxTilesX * 0.55)
{
                                point2.X = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                            }
                            flag10 = true;
                        }
                    }
                    num173++;
                    if (flag10 && marbleBiome.Place(point2, GenVars.structures))
                    {
                        num174++;
                        num173 = 0;
                    }
                    else if (num173 > Main.maxTilesX * 10)
                    {
                        num171 = num174;
                        num174++;
                        num173 = 0;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Granite, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[81].Value;
                int num185 = passConfig.Get<WorldGenRange>("Count").GetRandom(WorldGen.genRand);
                if (WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    num185 /= 2;
                }
                double num186 = (double)(Main.maxTilesX - 200) / (double)num185;
                List<Point> list = new List<Point>(num185);
                int num187 = 0;
                int num188 = 0;
                while (num188 < num185)
                {
                    float num189 = (float)num188 / (float)num185;
                    float num190 = num189 * 0.2f;
                    progress.Set((double)num190);
                    Point point3 = Point.Zero;
                    bool flag11 = false;
                    int num191 = 100;
                    while (!flag11)
                    {
                        num191--;
                        if (num191 <= 0)
{
                            break;
                        }
                        if (WorldGen.SecretSeed.dualDungeons.Enabled)
{
                            int num192 = 120;
                            int num193 = num192 + 1;
                            int num194;
                            if (num188 != 0)
{
                                if (num188 != 1)
{
                                    num194 = num192;
                                    num193 = Main.maxTilesX - num192;
                                }
                                else
{
                                    num194 = Main.maxTilesX - num192 - 100;
                                    num193 = Main.maxTilesX - num192;
                                }
                            }
                            else
{
                                num194 = num192;
                                num193 = num192 + 100;
                            }
                            if (WorldGen.remixWorldGen)
{
                                point3 = WorldGen.RandomRectanglePoint(num194, (int)GenVars.worldSurface + 100, num193 - num194, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                            }
                            else
{
                                point3 = WorldGen.RandomRectanglePoint(num194, (int)GenVars.rockLayer + 20, num193 - num194, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                            }
                            int num195 = 40;
                            int num196 = point3.X - num195;
                            int num197 = point3.Y - num195;
                            int num198 = point3.X + num195;
                            int num199 = point3.Y + num195;
                            flag11 = !DungeonUtils.IntersectsAnyPotentialDungeonBounds(new Rectangle(num196, num197, num198 - num196, num199 - num197), false);
                        }
                        else if (WorldGen.remixWorldGen)
{
                            point3 = WorldGen.RandomRectanglePoint((int)(num189 * (float)(Main.maxTilesX - 200)) + 100, (int)GenVars.worldSurface + 100, (int)num186, (int)GenVars.rockLayer - (int)GenVars.worldSurface - 100);
                        }
                        else
{
                            point3 = WorldGen.RandomRectanglePoint((int)(num189 * (float)(Main.maxTilesX - 200)) + 100, (int)GenVars.rockLayer + 20, (int)num186, Main.maxTilesY - ((int)GenVars.rockLayer + 40) - 200);
                        }
                        if (!WorldGen.SecretSeed.dualDungeons.Enabled)
{
                            while ((double)point3.X > (double)Main.maxTilesX * 0.45 && (double)point3.X < (double)Main.maxTilesX * 0.55)
{
                                point3.X = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                            }
                            flag11 = true;
                        }
                    }
                    num187++;
                    if (flag11 && GraniteBiome.CanPlace(point3, GenVars.structures))
                    {
                        list.Add(point3);
                        num188++;
                    }
                    else if (num187 > Main.maxTilesX * 10)
                    {
                        num185 = num188;
                        num188++;
                        num187 = 0;
                    }
                }
                GraniteBiome graniteBiome = GenVars.configuration.CreateBiome<GraniteBiome>();
                for (int num200 = 0; num200 < num185; num200++)
                {
                    double num201 = (double)(0.2f + (float)num200 / (float)num185 * 0.8f);
                    progress.Set(num201);
                    graniteBiome.Place(list[num200], GenVars.structures);
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.FloatingIslands, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyFloatingIslands)
                {
                    return;
                }
                if (WorldGen.SecretSeed.Variations.noSurfaceNoFloatingIslands)
                {
                    return;
                }
                GenVars.numIslandHouses = 0;
                GenVars.skyIslandHouseCount = 0;
                progress.Message = Lang.gen[12].Value;
                int num202 = (int)((double)Main.maxTilesX * 0.0008);
                int num203 = 0;
                if (WorldGen.SecretSeed.errorWorld.Enabled && WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0) < 3)
                {
                    num202 *= 3;
                }
                int num204 = num202;
                bool flag12 = false;
                if (WorldGen.SecretSeed.extraFloatingIslands.Enabled && !WorldGen.SecretSeed.Variations.extraFloatingIslandsNormalAmount)
                {
                    if (WorldGen.SecretSeed.Variations.extraFloatingIslandsReducedAmount)
                    {
                        num202 *= 2;
                        GenVars.skyLakes *= 2;
                    }
                    else
                    {
                        num202 *= 10;
                        GenVars.skyLakes *= 10;
                    }
                }
                double num205 = (double)(num202 + GenVars.skyLakes);
                int num206 = 0;
                while ((double)num206 < num205)
                {
                    progress.Set((double)num206 / num205);
                    int num207 = Main.maxTilesX;
                    if (WorldGen.skyblockWorldGen)
                    {
                        num207 /= 42;
                    }
                    while (--num207 > 0)
                    {
                        bool flag13 = true;
                        int num208 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.1), (int)((double)Main.maxTilesX * 0.9));
                        int num209 = 150;
                        if (WorldGen.SecretSeed.extraFloatingIslands.Enabled)
{
                            num209 = 100;
                        }
                        if (!WorldGen.SecretSeed.errorWorld.Enabled)
{
                            while (num208 > Main.maxTilesX / 2 - num209 && num208 < Main.maxTilesX / 2 + num209)
{
                                num208 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.1), (int)((double)Main.maxTilesX * 0.9));
                            }
                        }
                        int num210 = 180;
                        if (WorldGen.SecretSeed.extraFloatingIslands.Enabled && !WorldGen.SecretSeed.Variations.extraFloatingIslandsNormalAmount)
{
                            num210 = 100;
                        }
                        for (int num211 = 0; num211 < GenVars.numIslandHouses; num211++)
{
                            if (num208 > GenVars.floatingIslandHouseX[num211] - num210 && num208 < GenVars.floatingIslandHouseX[num211] + num210)
{
                                flag13 = false;
                                break;
                            }
                        }
                        if (flag13)
{
                            flag13 = false;
                            int num212 = 0;
                            if (WorldGen.SecretSeed.noSurface.Enabled)
{
                                num212 = WorldGen.genRand.Next(200, Main.UnderworldLayer - 200);
                                flag13 = true;
                            }
                            else if (WorldGen.skyblockWorldGen)
{
                                num212 = (int)(Main.worldSurface / 2.0 + 100.0);
                                flag13 = true;
                            }
                            else
{
                                int num213 = 200;
                                while ((double)num213 < Main.worldSurface)
{
                                    if (Main.tile[num208, num213].active())
{
                                        num212 = num213;
                                        flag13 = true;
                                        break;
                                    }
                                    num213++;
                                }
                            }
                            if (flag13)
{
                                int num214 = 0;
                                int num215 = WorldGen.genRand.Next(90, num212 - 100);
                                if (WorldGen.skyblockWorldGen && flag13)
{
                                    for (int num216 = num208 - 150; num216 <= num208 + 150; num216++)
{
                                        for (int num217 = num215 - 75; num217 <= num215 + 75; num217++)
{
                                            if (WorldGen.InWorld(num216, num217, 0) && Main.tile[num216, num217].active())
{
                                                flag13 = false;
                                            }
                                        }
                                    }
                                    if (!flag13)
{
                                        continue;
                                    }
                                }
                                num207 = -1;
                                if (!WorldGen.SecretSeed.noSurface.Enabled)
{
                                    num215 = Math.Min(num215, (int)GenVars.worldSurfaceLow - 50);
                                    if (WorldGen.SecretSeed.errorWorld.Enabled && WorldGen.genRand.Next(4) != 0)
{
                                        num215 = WorldGen.genRand.Next((int)Main.worldSurface + 50, Main.UnderworldLayer - 50);
                                    }
                                }
                                bool flag14 = false;
                                if (num203 >= num202)
{
                                    flag14 = true;
                                }
                                if (WorldGen.SecretSeed.extraFloatingIslands.Enabled && num206 > 4)
{
                                    if (!flag12)
{
                                        flag14 = true;
                                    }
                                    else if (WorldGen.genRand.Next(4) == 0)
{
                                        flag14 = true;
                                    }
                                }
                                if (flag14)
{
                                    flag12 = true;
                                    GenVars.skyLake[GenVars.numIslandHouses] = true;
                                    WorldGen.CloudLake(num208, num215);
                                }
                                else
{
                                    GenVars.skyLake[GenVars.numIslandHouses] = false;
                                    if (WorldGen.drunkWorldGen && !WorldGen.remixWorldGen)
{
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            num214 = 3;
                                            WorldGen.SnowCloudIsland(num208, num215);
                                        }
                                        else
{
                                            num214 = 1;
                                            WorldGen.DesertCloudIsland(num208, num215);
                                        }
                                    }
                                    else
{
                                        if (WorldGen.remixWorldGen && WorldGen.drunkWorldGen && (!WorldGen.tenthAnniversaryWorldGen || WorldGen.getGoodWorldGen))
{
                                            if (GenVars.crimsonLeft && num208 < Main.maxTilesX / 2)
{
                                                num214 = 5;
                                            }
                                            else if (!GenVars.crimsonLeft && num208 > Main.maxTilesX / 2)
{
                                                num214 = 5;
                                            }
                                            else
{
                                                num214 = 4;
                                            }
                                        }
                                        else if (!WorldGen.notTheBees || WorldGen.remixWorldGen)
{
                                            if (WorldGen.getGoodWorldGen || (WorldGen.remixWorldGen && !WorldGen.tenthAnniversaryWorldGen))
{
                                                if (WorldGen.crimson)
{
                                                    num214 = 5;
                                                }
                                                else
{
                                                    num214 = 4;
                                                }
                                            }
                                            else if (Main.tenthAnniversaryWorld)
{
                                                num214 = 6;
                                            }
                                        }
                                        WorldGen.CloudIsland(num208, num215);
                                    }
                                }
                                GenVars.floatingIslandHouseX[GenVars.numIslandHouses] = num208;
                                GenVars.floatingIslandHouseY[GenVars.numIslandHouses] = num215;
                                GenVars.floatingIslandStyle[GenVars.numIslandHouses] = num214;
                                GenVars.numIslandHouses++;
                                num203++;
                            }
                        }
                    }
                    num206++;
                }
                if (WorldGen.SecretSeed.extraFloatingIslands.Enabled && GenVars.numIslandHouses > num204 * 2)
                {
                    GenVars.numIslandHouses = num204 * 2;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtToMud, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[14].Value;
                double num218 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.001;
                int num219 = 0;
                while ((double)num219 < num218)
                {
                    progress.Set((double)num219 / num218);
                    if (WorldGen.remixWorldGen)
                    {
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.worldSurface, (int)GenVars.rockLayerLow), (double)WorldGen.genRand.Next(2, 6), WorldGen.genRand.Next(2, 40), 59, false, 0.0, 0.0, false, true, 53);
                    }
                    else
                    {
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(2, 6), WorldGen.genRand.Next(2, 40), 59, false, 0.0, 0.0, false, true, 53);
                    }
                    num219++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Silt, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[15].Value;
                progress.Set(0.0);
                int num220 = (int)((float)(Main.maxTilesX * Main.maxTilesY) * 0.0001f);
                for (int num221 = 0; num221 < num220; num221++)
                {
                    float num222 = (float)num221 / (float)num220;
                    progress.Set((double)(num222 * 0.5f));
                    int num223 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    int num224 = WorldGen.genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                    if (WorldGen.remixWorldGen)
                    {
                        num224 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    if (Main.tile[num223, num224].wall != 187 && Main.tile[num223, num224].wall != 216)
                    {
                        WorldGen.TileRunner(num223, num224, (double)WorldGen.genRand.Next(5, 12), WorldGen.genRand.Next(15, 50), 123, false, 0.0, 0.0, false, true, -1);
                    }
                }
                num220 = (int)((float)(Main.maxTilesX * Main.maxTilesY) * 0.0005f);
                for (int num225 = 0; num225 < num220; num225++)
                {
                    float num226 = (float)num225 / (float)num220;
                    progress.Set((double)(0.5f + num226 * 0.5f));
                    int num227 = WorldGen.genRand.Next(0, Main.maxTilesX);
                    int num228 = WorldGen.genRand.Next((int)GenVars.rockLayerHigh, Main.maxTilesY);
                    if (WorldGen.remixWorldGen)
                    {
                        num228 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    if (Main.tile[num227, num228].wall != 187 && Main.tile[num227, num228].wall != 216)
                    {
                        WorldGen.TileRunner(num227, num228, (double)WorldGen.genRand.Next(2, 5), WorldGen.genRand.Next(2, 5), 123, false, 0.0, 0.0, false, true, -1);
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.OresAndShinies, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[16].Value;
                progress.Set(0.0);
                float num229 = 12f;
                float num230 = 1f / num229;
                if (WorldGen.remixWorldGen)
                {
                    int num231 = (int)((float)(Main.maxTilesX * Main.maxTilesY) * 6E-05f);
                    for (int num232 = 0; num232 < num231; num232++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.copper = 7;
                            }
                            else
{
                                GenVars.copper = 166;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(2, 6), GenVars.copper, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)num230);
                    for (int num233 = 0; num233 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num233++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.copper = 7;
                            }
                            else
{
                                GenVars.copper = 166;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), (double)WorldGen.genRand.Next(3, 7), WorldGen.genRand.Next(3, 7), GenVars.copper, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 2f));
                    for (int num234 = 0; num234 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num234++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.copper = 7;
                            }
                            else
{
                                GenVars.copper = 166;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.copper, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 3f));
                    for (int num235 = 0; num235 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05); num235++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.iron = 6;
                            }
                            else
{
                                GenVars.iron = 167;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), (double)WorldGen.genRand.Next(3, 7), WorldGen.genRand.Next(2, 5), GenVars.iron, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 4f));
                    for (int num236 = 0; num236 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num236++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.iron = 6;
                            }
                            else
{
                                GenVars.iron = 167;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(3, 6), GenVars.iron, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 5f));
                    for (int num237 = 0; num237 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num237++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.iron = 6;
                            }
                            else
{
                                GenVars.iron = 167;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.iron, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 6f));
                    for (int num238 = 0; num238 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.6E-05); num238++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.silver = 9;
                            }
                            else
{
                                GenVars.silver = 168;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer - 100, Main.maxTilesY - 250), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(3, 6), GenVars.silver, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 7f));
                    for (int num239 = 0; num239 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00015); num239++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.silver = 9;
                            }
                            else
{
                                GenVars.silver = 168;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.silver, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 8f));
                    for (int num240 = 0; num240 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num240++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.gold = 8;
                            }
                            else
{
                                GenVars.gold = 169;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), (double)WorldGen.genRand.Next(4, 8), WorldGen.genRand.Next(4, 8), GenVars.gold, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 9f));
                    if (!WorldGen.SecretSeed.noSurface.Enabled && !WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
                    {
                        for (int num241 = 0; num241 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00017); num241++)
{
                            if (WorldGen.drunkWorldGen)
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    GenVars.silver = 9;
                                }
                                else
{
                                    GenVars.silver = 168;
                                }
                            }
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(0, (int)GenVars.worldSurfaceLow), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.silver, false, 0.0, 0.0, false, true, -1);
                        }
                        for (int num242 = 0; num242 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num242++)
{
                            if (WorldGen.drunkWorldGen)
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    GenVars.gold = 8;
                                }
                                else
{
                                    GenVars.gold = 169;
                                }
                            }
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(0, (int)GenVars.worldSurfaceLow - 20), (double)WorldGen.genRand.Next(4, 8), WorldGen.genRand.Next(4, 8), GenVars.gold, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                    progress.Set((double)(num230 * 10f));
                    if (WorldGen.drunkWorldGen)
                    {
                        for (int num243 = 0; num243 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num243++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 204, false, 0.0, 0.0, false, true, -1);
                        }
                        for (int num244 = 0; num244 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num244++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 22, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                    progress.Set((double)(num230 * 11f));
                    if (WorldGen.crimson)
                    {
                        for (int num245 = 0; num245 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 4.25E-05); num245++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 204, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                    else
                    {
                        for (int num246 = 0; num246 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 4.25E-05); num246++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 22, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                }
                else
                {
                    for (int num247 = 0; num247 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 6E-05); num247++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.copper = 7;
                            }
                            else
{
                                GenVars.copper = 166;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(2, 6), GenVars.copper, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)num230);
                    for (int num248 = 0; num248 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num248++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.copper = 7;
                            }
                            else
{
                                GenVars.copper = 166;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), (double)WorldGen.genRand.Next(3, 7), WorldGen.genRand.Next(3, 7), GenVars.copper, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 2f));
                    for (int num249 = 0; num249 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num249++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.copper = 7;
                            }
                            else
{
                                GenVars.copper = 166;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.copper, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 3f));
                    for (int num250 = 0; num250 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3E-05); num250++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.iron = 6;
                            }
                            else
{
                                GenVars.iron = 167;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurfaceHigh), (double)WorldGen.genRand.Next(3, 7), WorldGen.genRand.Next(2, 5), GenVars.iron, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 4f));
                    for (int num251 = 0; num251 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 8E-05); num251++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.iron = 6;
                            }
                            else
{
                                GenVars.iron = 167;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(3, 6), GenVars.iron, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 5f));
                    for (int num252 = 0; num252 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0002); num252++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.iron = 6;
                            }
                            else
{
                                GenVars.iron = 167;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.iron, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 6f));
                    for (int num253 = 0; num253 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.6E-05); num253++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.silver = 9;
                            }
                            else
{
                                GenVars.silver = 168;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, (int)GenVars.rockLayerHigh), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(3, 6), GenVars.silver, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 7f));
                    for (int num254 = 0; num254 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00015); num254++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.silver = 9;
                            }
                            else
{
                                GenVars.silver = 168;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.silver, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 8f));
                    for (int num255 = 0; num255 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num255++)
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                GenVars.gold = 8;
                            }
                            else
{
                                GenVars.gold = 169;
                            }
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)GenVars.rockLayerLow, Main.maxTilesY), (double)WorldGen.genRand.Next(4, 8), WorldGen.genRand.Next(4, 8), GenVars.gold, false, 0.0, 0.0, false, true, -1);
                    }
                    progress.Set((double)(num230 * 9f));
                    if (!WorldGen.SecretSeed.noSurface.Enabled && !WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
                    {
                        for (int num256 = 0; num256 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00017); num256++)
{
                            if (WorldGen.drunkWorldGen)
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    GenVars.silver = 9;
                                }
                                else
{
                                    GenVars.silver = 168;
                                }
                            }
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(0, (int)GenVars.worldSurfaceLow), (double)WorldGen.genRand.Next(4, 9), WorldGen.genRand.Next(4, 8), GenVars.silver, false, 0.0, 0.0, false, true, -1);
                        }
                        for (int num257 = 0; num257 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.00012); num257++)
{
                            if (WorldGen.drunkWorldGen)
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    GenVars.gold = 8;
                                }
                                else
{
                                    GenVars.gold = 169;
                                }
                            }
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(0, (int)GenVars.worldSurfaceLow - 20), (double)WorldGen.genRand.Next(4, 8), WorldGen.genRand.Next(4, 8), GenVars.gold, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                    progress.Set((double)(num230 * 10f));
                    if (WorldGen.drunkWorldGen)
                    {
                        for (int num258 = 0; num258 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num258++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 204, false, 0.0, 0.0, false, true, -1);
                        }
                        for (int num259 = 0; num259 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05 / 2.0); num259++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 22, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                    progress.Set((double)(num230 * 11f));
                    if (WorldGen.crimson)
                    {
                        for (int num260 = 0; num260 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05); num260++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 204, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                    else
                    {
                        for (int num261 = 0; num261 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 2.25E-05); num261++)
{
                            WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY), (double)WorldGen.genRand.Next(3, 6), WorldGen.genRand.Next(4, 8), 22, false, 0.0, 0.0, false, true, -1);
                        }
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.Webs, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[17].Value;
                for (int num262 = 0; num262 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0006); num262++)
                {
                    int num263 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num264 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY - 20);
                    if (num262 < GenVars.numMCaves)
                    {
                        num263 = GenVars.mCaveX[num262];
                        num264 = GenVars.mCaveY[num262];
                    }
                    if (!Main.tile[num263, num264].active())
                    {
                        if ((double)num264 <= Main.worldSurface)
{
                            if (Main.tile[num263, num264].wall <= 0)
{
                                goto IL_0151;
                            }
                        }
                        while (!Main.tile[num263, num264].active() && num264 > (int)GenVars.worldSurfaceLow)
{
                            num264--;
                        }
                        num264++;
                        int num265 = 1;
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num265 = -1;
                        }
                        while (!Main.tile[num263, num264].active() && num263 > 10 && num263 < Main.maxTilesX - 10)
{
                            num263 += num265;
                        }
                        num263 -= num265;
                        if ((double)num264 > Main.worldSurface || Main.tile[num263, num264].wall > 0)
{
                            WorldGen.TileRunner(num263, num264, (double)WorldGen.genRand.Next(4, 11), WorldGen.genRand.Next(2, 4), 51, true, (double)num265, -1.0, false, false, -1);
                        }
                    }
                    IL_0151:;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Underworld, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[18].Value;
                progress.Set(0.0);
                int num266 = Main.maxTilesY - WorldGen.genRand.Next(150, 190);
                int num267 = Main.maxTilesY - WorldGen.genRand.Next(40, 70);
                for (int num268 = 0; num268 < Main.maxTilesX; num268++)
                {
                    progress.Set((double)((float)num268 / (float)Main.maxTilesX), 0.0, 0.20000000298023224);
                    num266 += WorldGen.genRand.Next(-3, 4);
                    if (num266 < Main.maxTilesY - 190)
                    {
                        num266 = Main.maxTilesY - 190;
                    }
                    if (num266 > Main.maxTilesY - 160)
                    {
                        num266 = Main.maxTilesY - 160;
                    }
                    int num269 = num266;
                    if (GenVars.notTheBeesAndForTheWorthyNoCelebration)
                    {
                        num269 -= 30;
                    }
                    for (int num270 = num269 - 20 - WorldGen.genRand.Next(3); num270 < Main.maxTilesY; num270++)
                    {
                        if (GenVars.notTheBeesAndForTheWorthyNoCelebration && num270 <= num269 && !WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
{
                            Main.tile[num268, num270].wall = 62;
                        }
                        else if (num270 >= num266)
{
                            Main.tile[num268, num270].active(false);
                            Main.tile[num268, num270].lava(false);
                            Main.tile[num268, num270].liquid = 0;
                            if (GenVars.notTheBeesAndForTheWorthyNoCelebration && !WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
{
                                Main.tile[num268, num270].wall = 62;
                                if (num270 < num267 && WorldGen.genRand.Next(10) == 0)
{
                                    Main.tile[num268, num270].active(true);
                                    Main.tile[num268, num270].type = 51;
                                    Main.tile[num268, num270].ClearSlope();
                                }
                            }
                        }
                        else
{
                            Main.tile[num268, num270].type = 57;
                            if (GenVars.notTheBeesAndForTheWorthyNoCelebration && !WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
{
                                Main.tile[num268, num270].wall = 62;
                            }
                        }
                    }
                }
                for (int num271 = 10; num271 < Main.maxTilesX - 10; num271++)
                {
                    progress.Set((double)((float)(num271 - 10) / (float)(Main.maxTilesX - 20)), 0.20000000298023224, 0.4000000059604645);
                    num267 += WorldGen.genRand.Next(-10, 11);
                    if (num267 > Main.maxTilesY - 60)
                    {
                        num267 = Main.maxTilesY - 60;
                    }
                    if (num267 < Main.maxTilesY - 100)
                    {
                        num267 = Main.maxTilesY - 120;
                    }
                    for (int num272 = num267; num272 < Main.maxTilesY - 10; num272++)
                    {
                        if (!Main.tile[num271, num272].active())
{
                            Main.tile[num271, num272].lava(true);
                            Main.tile[num271, num272].liquid = byte.MaxValue;
                        }
                    }
                }
                for (int num273 = 0; num273 < Main.maxTilesX; num273++)
                {
                    progress.Set((double)((float)num273 / (float)Main.maxTilesX), 0.4000000059604645, 0.6600000262260437);
                    if (WorldGen.genRand.Next(50) == 0)
                    {
                        int num274 = Main.maxTilesY - 65;
                        while (!Main.tile[num273, num274].active() && num274 > Main.maxTilesY - 135)
{
                            num274--;
                        }
                        WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), num274 + WorldGen.genRand.Next(20, 50), (double)WorldGen.genRand.Next(15, 20), 1000, 57, true, 0.0, (double)WorldGen.genRand.Next(1, 3), true, true, -1);
                    }
                }
                Liquid.QuickWater(-2, -1, -1);
                for (int num275 = 0; num275 < Main.maxTilesX; num275++)
                {
                    double num276 = (double)num275 / (double)(Main.maxTilesX - 1);
                    progress.Set(num276, 0.6600000262260437, 1.0);
                    if (WorldGen.genRand.Next(13) == 0)
                    {
                        int num277 = Main.maxTilesY - 65;
                        while ((Main.tile[num275, num277].liquid > 0 || Main.tile[num275, num277].active()) && num277 > Main.maxTilesY - 140)
{
                            num277--;
                        }
                        if ((!WorldGen.drunkWorldGen && !WorldGen.remixWorldGen) || WorldGen.genRand.Next(3) == 0 || (double)num275 <= (double)Main.maxTilesX * 0.4 || (double)num275 >= (double)Main.maxTilesX * 0.6)
{
                            WorldGen.TileRunner(num275, num277 - WorldGen.genRand.Next(2, 5), (double)WorldGen.genRand.Next(5, 30), 1000, 57, true, 0.0, (double)WorldGen.genRand.Next(1, 3), true, true, -1);
                        }
                        double num278 = (double)WorldGen.genRand.Next(1, 3);
                        if (WorldGen.genRand.Next(3) == 0)
{
                            num278 *= 0.5;
                        }
                        if ((!WorldGen.drunkWorldGen && !WorldGen.remixWorldGen) || WorldGen.genRand.Next(3) == 0 || (double)num275 <= (double)Main.maxTilesX * 0.4 || (double)num275 >= (double)Main.maxTilesX * 0.6)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.TileRunner(num275, num277 - WorldGen.genRand.Next(2, 5), (double)((int)((double)WorldGen.genRand.Next(5, 15) * num278)), (int)((double)WorldGen.genRand.Next(10, 15) * num278), 57, true, 1.0, 0.3, false, true, -1);
                            }
                            if (WorldGen.genRand.Next(2) == 0)
{
                                num278 = (double)WorldGen.genRand.Next(1, 3);
                                WorldGen.TileRunner(num275, num277 - WorldGen.genRand.Next(2, 5), (double)((int)((double)WorldGen.genRand.Next(5, 15) * num278)), (int)((double)WorldGen.genRand.Next(10, 15) * num278), 57, true, -1.0, 0.3, false, true, -1);
                            }
                        }
                        WorldGen.TileRunner(num275 + WorldGen.genRand.Next(-10, 10), num277 + WorldGen.genRand.Next(-10, 10), (double)WorldGen.genRand.Next(5, 15), WorldGen.genRand.Next(5, 10), -2, false, (double)WorldGen.genRand.Next(-1, 3), (double)WorldGen.genRand.Next(-1, 3), false, true, -1);
                        if (WorldGen.genRand.Next(3) == 0)
{
                            WorldGen.TileRunner(num275 + WorldGen.genRand.Next(-10, 10), num277 + WorldGen.genRand.Next(-10, 10), (double)WorldGen.genRand.Next(10, 30), WorldGen.genRand.Next(10, 20), -2, false, (double)WorldGen.genRand.Next(-1, 3), (double)WorldGen.genRand.Next(-1, 3), false, true, -1);
                        }
                        if (WorldGen.genRand.Next(5) == 0)
{
                            WorldGen.TileRunner(num275 + WorldGen.genRand.Next(-15, 15), num277 + WorldGen.genRand.Next(-15, 10), (double)WorldGen.genRand.Next(15, 30), WorldGen.genRand.Next(5, 20), -2, false, (double)WorldGen.genRand.Next(-1, 3), (double)WorldGen.genRand.Next(-1, 3), false, true, -1);
                        }
                    }
                }
                for (int num279 = 0; num279 < Main.maxTilesX; num279++)
                {
                    WorldGen.TileRunner(WorldGen.genRand.Next(20, Main.maxTilesX - 20), WorldGen.genRand.Next(Main.maxTilesY - 180, Main.maxTilesY - 10), (double)WorldGen.genRand.Next(2, 7), WorldGen.genRand.Next(2, 7), -2, false, 0.0, 0.0, false, true, -1);
                }
                if (WorldGen.drunkWorldGen || WorldGen.remixWorldGen)
                {
                    for (int num280 = 0; num280 < Main.maxTilesX * 2; num280++)
                    {
                        WorldGen.TileRunner(WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.35), (int)((double)Main.maxTilesX * 0.65)), WorldGen.genRand.Next(Main.maxTilesY - 180, Main.maxTilesY - 10), (double)WorldGen.genRand.Next(5, 20), WorldGen.genRand.Next(5, 10), -2, false, 0.0, 0.0, false, true, -1);
                    }
                }
                for (int num281 = 0; num281 < Main.maxTilesX; num281++)
                {
                    if (!Main.tile[num281, Main.maxTilesY - 145].active())
                    {
                        Main.tile[num281, Main.maxTilesY - 145].liquid = byte.MaxValue;
                        Main.tile[num281, Main.maxTilesY - 145].lava(true);
                    }
                    if (!Main.tile[num281, Main.maxTilesY - 144].active())
                    {
                        Main.tile[num281, Main.maxTilesY - 144].liquid = byte.MaxValue;
                        Main.tile[num281, Main.maxTilesY - 144].lava(true);
                    }
                }
                for (int num282 = 0; num282 < (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0008); num282++)
                {
                    WorldGen.TileRunner(WorldGen.genRand.Next(0, Main.maxTilesX), WorldGen.genRand.Next(Main.maxTilesY - 140, Main.maxTilesY), (double)WorldGen.genRand.Next(2, 7), WorldGen.genRand.Next(3, 7), 58, false, 0.0, 0.0, false, true, -1);
                }
                if (WorldGen.remixWorldGen)
                {
                    WorldGen.GenerateUnderworldStartingMound();
                }
                else if (!WorldGen.drunkWorldGen)
                {
                    for (int num283 = 25; num283 < Main.maxTilesX - 25; num283++)
                    {
                        if ((double)num283 < (double)Main.maxTilesX * 0.17 || (double)num283 > (double)Main.maxTilesX * 0.83)
{
                            for (int num284 = Main.maxTilesY - 300; num284 < Main.maxTilesY - 100 + WorldGen.genRand.Next(-1, 2); num284++)
{
                                if (Main.tile[num283, num284].type == 57 && Main.tile[num283, num284].active() && (!Main.tile[num283 - 1, num284 - 1].active() || !Main.tile[num283, num284 - 1].active() || !Main.tile[num283 + 1, num284 - 1].active() || !Main.tile[num283 - 1, num284].active() || !Main.tile[num283 + 1, num284].active() || !Main.tile[num283 - 1, num284 + 1].active() || !Main.tile[num283, num284 + 1].active() || !Main.tile[num283 + 1, num284 + 1].active()))
{
                                    Main.tile[num283, num284].type = 633;
                                }
                            }
                        }
                    }
                    for (int num285 = 25; num285 < Main.maxTilesX - 25; num285++)
                    {
                        if ((double)num285 < (double)Main.maxTilesX * 0.17 || (double)num285 > (double)Main.maxTilesX * 0.83)
{
                            for (int num286 = Main.maxTilesY - 200; num286 < Main.maxTilesY - 50; num286++)
{
                                if (Main.tile[num285, num286].type == 633 && Main.tile[num285, num286].active() && !Main.tile[num285, num286 - 1].active() && WorldGen.genRand.Next(3) == 0)
{
                                    WorldGen.TryGrowingTreeByType(634, num285, num286, 0, false);
                                }
                            }
                        }
                    }
                }
                WorldGen.AddHellHouses();
                if (WorldGen.drunkWorldGen)
                {
                    for (int num287 = 25; num287 < Main.maxTilesX - 25; num287++)
                    {
                        for (int num288 = Main.maxTilesY - 300; num288 < Main.maxTilesY - 100 + WorldGen.genRand.Next(-1, 2); num288++)
{
                            if (Main.tile[num287, num288].type == 57 && Main.tile[num287, num288].active() && (!Main.tile[num287 - 1, num288 - 1].active() || !Main.tile[num287, num288 - 1].active() || !Main.tile[num287 + 1, num288 - 1].active() || !Main.tile[num287 - 1, num288].active() || !Main.tile[num287 + 1, num288].active() || !Main.tile[num287 - 1, num288 + 1].active() || !Main.tile[num287, num288 + 1].active() || !Main.tile[num287 + 1, num288 + 1].active()))
{
                                Main.tile[num287, num288].type = 633;
                            }
                        }
                    }
                    for (int num289 = 25; num289 < Main.maxTilesX - 25; num289++)
                    {
                        for (int num290 = Main.maxTilesY - 200; num290 < Main.maxTilesY - 50; num290++)
{
                            if (Main.tile[num289, num290].type == 633 && Main.tile[num289, num290].active() && !Main.tile[num289, num290 - 1].active() && WorldGen.genRand.Next(3) == 0)
{
                                WorldGen.TryGrowingTreeByType(634, num289, num290, 0, false);
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.CorruptionAndCrimson, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                double num291 = GenVars.worldSurfaceLow;
                double num292 = Main.worldSurface;
                if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
                {
                    num291 = (double)(WorldGen.FindLowestCloud() + 10);
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                    {
                        WorldGen.SecretSeed.DoSurfaceIsDesertNoSurfaceCleanup();
                    }
                    num292 = Main.rockLayer;
                    num291 = Main.rockLayer / 2.0;
                }
                int num293 = Main.maxTilesX;
                int num294 = 0;
                int num295 = Main.maxTilesX;
                int num296 = 0;
                for (int num297 = 0; num297 < Main.maxTilesX; num297++)
                {
                    int num298 = 0;
                    while ((double)num298 < num292)
                    {
                        if (Main.tile[num297, num298].active())
{
                            if (Main.tile[num297, num298].type == 60)
{
                                if (num297 < num293)
{
                                    num293 = num297;
                                }
                                if (num297 > num294)
{
                                    num294 = num297;
                                }
                            }
                            else if (Main.tile[num297, num298].type == 147 || Main.tile[num297, num298].type == 161)
{
                                if (num297 < num295)
{
                                    num295 = num297;
                                }
                                if (num297 > num296)
{
                                    num296 = num297;
                                }
                            }
                        }
                        num298++;
                    }
                }
                int num299 = 10;
                num293 -= num299;
                num294 += num299;
                num295 -= num299;
                num296 += num299;
                int num300 = 500;
                int num301 = 100;
                double num302 = (double)Main.maxTilesX * 0.00045;
                if (WorldGen.remixWorldGen)
                {
                    num302 *= 2.0;
                }
                else if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.dontStarveWorldGen)
                {
                    num300 *= 2;
                    num301 *= 2;
                }
                bool flag15 = WorldGen.crimson;
                if (WorldGen.drunkWorldGen)
                {
                    flag15 = true;
                    num302 /= 2.0;
                }
                if (flag15)
                {
                    progress.Message = Lang.gen[72].Value;
                    int num303 = 0;
                    while ((double)num303 < num302)
                    {
                        int num304 = num295;
                        int num305 = num296;
                        int num306 = num293;
                        int num307 = num294;
                        double num308 = (double)num303 / num302;
                        progress.Set(num308);
                        bool flag16 = false;
                        int num309 = 0;
                        int num310 = 0;
                        int num311 = 0;
                        while (!flag16)
{
                            flag16 = true;
                            int num312 = Main.maxTilesX / 2;
                            int num313 = 200;
                            if (WorldGen.drunkWorldGen)
{
                                num313 = 100;
                                if (GenVars.crimsonLeft)
{
                                    num309 = WorldGen.genRand.Next(num300, (int)((double)Main.maxTilesX * 0.5));
                                }
                                else
{
                                    num309 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.5), Main.maxTilesX - num300);
                                }
                            }
                            else
{
                                num309 = WorldGen.genRand.Next(num300, Main.maxTilesX - num300);
                            }
                            num310 = num309 - WorldGen.genRand.Next(200) - 100;
                            num311 = num309 + WorldGen.genRand.Next(200) + 100;
                            if (num310 < GenVars.evilBiomeBeachAvoidance)
{
                                num310 = GenVars.evilBiomeBeachAvoidance;
                            }
                            if (num311 > Main.maxTilesX - GenVars.evilBiomeBeachAvoidance)
{
                                num311 = Main.maxTilesX - GenVars.evilBiomeBeachAvoidance;
                            }
                            if (num309 < num310 + GenVars.evilBiomeAvoidanceMidFixer)
{
                                num309 = num310 + GenVars.evilBiomeAvoidanceMidFixer;
                            }
                            if (num309 > num311 - GenVars.evilBiomeAvoidanceMidFixer)
{
                                num309 = num311 - GenVars.evilBiomeAvoidanceMidFixer;
                            }
                            if (GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left && num310 < 400)
{
                                num310 = 400;
                            }
                            else if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right && num310 > Main.maxTilesX - 400)
{
                                num310 = Main.maxTilesX - 400;
                            }
                            if (num310 < GenVars.CurrentDungeonGenVars.dungeonLocation + num301 && num311 > GenVars.CurrentDungeonGenVars.dungeonLocation - num301)
{
                                flag16 = false;
                            }
                            if (!WorldGen.remixWorldGen)
{
                                if (!WorldGen.tenthAnniversaryWorldGen || WorldGen.dontStarveWorldGen)
{
                                    if (num309 > num312 - num313 && num309 < num312 + num313)
{
                                        flag16 = false;
                                    }
                                    if (num310 > num312 - num313 && num310 < num312 + num313)
{
                                        flag16 = false;
                                    }
                                    if (num311 > num312 - num313 && num311 < num312 + num313)
{
                                        flag16 = false;
                                    }
                                }
                                if (num309 > GenVars.UndergroundDesertLocation.X && num309 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                    flag16 = false;
                                }
                                if (num310 > GenVars.UndergroundDesertLocation.X && num310 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                    flag16 = false;
                                }
                                if (num311 > GenVars.UndergroundDesertLocation.X && num311 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                    flag16 = false;
                                }
                                if (num310 < num305 && num311 > num304)
{
                                    num304++;
                                    num305--;
                                    flag16 = false;
                                }
                                if ((!WorldGen.notTheBees || WorldGen.remixWorldGen) && num310 < num307 && num311 > num306)
{
                                    num306++;
                                    num307--;
                                    flag16 = false;
                                }
                            }
                        }
                        if (!GenVars.flipInfections)
{
                            WorldGen.CrimStart(num309, (int)num291 - 10);
                        }
                        int num314 = 0;
                        for (int num315 = num310; num315 < num311; num315++)
{
                            if (GenVars.flipInfections)
{
                                if (num314 > 0)
{
                                    num314--;
                                }
                                if (num315 == num309 || num314 == 0)
{
                                    int num316 = (int)num291;
                                    while ((double)num316 < num292 - 1.0)
{
                                        if (Main.tile[num315, num316].active() || Main.tile[num315, num316].wall > 0)
{
                                            if (num315 == num309)
{
                                                num314 = 20;
                                                WorldGen.ChasmRunner(num315, num316, WorldGen.genRand.Next(150) + 150, true);
                                                break;
                                            }
                                            if (WorldGen.genRand.Next(35) == 0 && num314 == 0)
{
                                                num314 = 30;
                                                bool flag17 = true;
                                                WorldGen.ChasmRunner(num315, num316, WorldGen.genRand.Next(50) + 50, flag17);
                                                break;
                                            }
                                            break;
                                        }
                                        else
{
                                            num316++;
                                        }
                                    }
                                }
                            }
                            int num317 = (int)num291;
                            while ((double)num317 < num292 - 1.0)
{
                                if (Main.tile[num315, num317].active())
{
                                    int num318 = num317 + WorldGen.genRand.Next(10, 14);
                                    for (int num319 = num317; num319 < num318; num319++)
{
                                        if (Main.tile[num315, num319].active() && Main.tile[num315, num319].type == 60 && num315 >= num310 + WorldGen.genRand.Next(5) && num315 < num311 - WorldGen.genRand.Next(5))
{
                                            Main.tile[num315, num319].type = 662;
                                        }
                                    }
                                    break;
                                }
                                num317++;
                            }
                        }
                        double num320 = num292 + 40.0;
                        for (int num321 = num310; num321 < num311; num321++)
{
                            num320 += (double)WorldGen.genRand.Next(-2, 3);
                            if (num320 < num292 + 30.0)
{
                                num320 = num292 + 30.0;
                            }
                            if (num320 > num292 + 50.0)
{
                                num320 = num292 + 50.0;
                            }
                            bool flag18 = false;
                            double num322 = num291;
                            if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
{
                                num322 = 0.0;
                            }
                            int num323 = (int)num322;
                            while ((double)num323 < num320)
{
                                if (((num321 > num310 + 1 && num321 < num311 - 2) || WorldGen.genRand.Next(2) != 0) && (((double)num323 > num322 + 1.0 && (double)num323 < num320 - 2.0) || WorldGen.genRand.Next(2) != 0))
{
                                    if (WorldGen.SecretSeed.noSurface.Enabled)
{
                                        if (Main.tile[num321, num323].wall == 216)
{
                                            Main.tile[num321, num323].wall = 218;
                                        }
                                        else if (Main.tile[num321, num323].wall == 187)
{
                                            Main.tile[num321, num323].wall = 221;
                                        }
                                    }
                                    if (Main.tile[num321, num323].active())
{
                                        if (Main.tile[num321, num323].type == 53 && num321 >= num310 + WorldGen.genRand.Next(5) && num321 <= num311 - WorldGen.genRand.Next(5))
{
                                            Main.tile[num321, num323].type = 234;
                                        }
                                        if ((double)num323 < num292 - 1.0 && !flag18)
{
                                            if (Main.tile[num321, num323].type == 0)
{
                                                WorldGen.grassSpread = 0;
                                                WorldGen.SpreadGrass(num321, num323, 0, 199, true, default(TileColorCache));
                                            }
                                            else if (Main.tile[num321, num323].type == 59)
{
                                                WorldGen.grassSpread = 0;
                                                WorldGen.SpreadGrass(num321, num323, 59, 662, true, default(TileColorCache));
                                            }
                                        }
                                        flag18 = true;
                                        if (Main.tile[num321, num323].wall == 216)
{
                                            Main.tile[num321, num323].wall = 218;
                                        }
                                        else if (Main.tile[num321, num323].wall == 187)
{
                                            Main.tile[num321, num323].wall = 221;
                                        }
                                        if (Main.tile[num321, num323].type == 1)
{
                                            if (num321 >= num310 + WorldGen.genRand.Next(5) && num321 <= num311 - WorldGen.genRand.Next(5))
{
                                                Main.tile[num321, num323].type = 203;
                                            }
                                        }
                                        else if (Main.tile[num321, num323].type == 2)
{
                                            Main.tile[num321, num323].type = 199;
                                        }
                                        else if (Main.tile[num321, num323].type == 60)
{
                                            Main.tile[num321, num323].type = 662;
                                        }
                                        else if (Main.tile[num321, num323].type == 161)
{
                                            Main.tile[num321, num323].type = 200;
                                        }
                                        else if (Main.tile[num321, num323].type == 396)
{
                                            Main.tile[num321, num323].type = 401;
                                        }
                                        else if (Main.tile[num321, num323].type == 397)
{
                                            Main.tile[num321, num323].type = 399;
                                        }
                                    }
                                }
                                num323++;
                            }
                        }
                        int num324 = WorldGen.genRand.Next(10, 15);
                        for (int num325 = 0; num325 < num324; num325++)
{
                            int num326 = 0;
                            bool flag19 = false;
                            int num327 = 0;
                            while (!flag19)
{
                                num326++;
                                int num328 = WorldGen.genRand.Next(num310 - num327, num311 + num327);
                                int num329 = WorldGen.genRand.Next((int)(num292 - (double)(num327 / 2)), (int)(num292 + 100.0 + (double)num327));
                                while (WorldGen.oceanDepths(num328, num329))
{
                                    num328 = WorldGen.genRand.Next(num310 - num327, num311 + num327);
                                    num329 = WorldGen.genRand.Next((int)(num292 - (double)(num327 / 2)), (int)(num292 + 100.0 + (double)num327));
                                }
                                if (num326 > 100)
{
                                    num327++;
                                    num326 = 0;
                                }
                                if (!Main.tile[num328, num329].active())
{
                                    while (!Main.tile[num328, num329].active())
{
                                        num329++;
                                    }
                                    num329--;
                                }
                                else
{
                                    while (Main.tile[num328, num329].active() && (double)num329 > num292)
{
                                        num329--;
                                    }
                                }
                                if ((num327 > 10 || (Main.tile[num328, num329 + 1].active() && Main.tile[num328, num329 + 1].type == 203)) && !WorldGen.IsTileNearby(num328, num329, 26, 3))
{
                                    WorldGen.Place3x2(num328, num329, 26, 1);
                                    if (Main.tile[num328, num329].type == 26)
{
                                        flag19 = true;
                                    }
                                }
                                if (num327 > 100)
{
                                    flag19 = true;
                                }
                            }
                        }
                        if (GenVars.flipInfections)
{
                            for (int num330 = num310; num330 < num311; num330++)
{
                                for (int num331 = 0; num331 < Main.maxTilesY - 50; num331++)
{
                                    if (Main.tile[num330, num331].active() && Main.tile[num330, num331].type == 31)
{
                                        int num332 = num330 - 13;
                                        int num333 = num330 + 13;
                                        int num334 = num331 - 13;
                                        int num335 = num331 + 13;
                                        for (int num336 = num332; num336 < num333; num336++)
{
                                            if (num336 > 10 && num336 < Main.maxTilesX - 10)
{
                                                for (int num337 = num334; num337 < num335; num337++)
{
                                                    if (Math.Abs(num336 - num330) + Math.Abs(num337 - num331) < 9 + WorldGen.genRand.Next(11) && WorldGen.genRand.Next(3) != 0 && Main.tile[num336, num337].type != 31)
{
                                                        Main.tile[num336, num337].active(true);
                                                        Main.tile[num336, num337].type = 203;
                                                        if (Math.Abs(num336 - num330) <= 1 && Math.Abs(num337 - num331) <= 1)
{
                                                            Main.tile[num336, num337].active(false);
                                                        }
                                                    }
                                                    if (Main.tile[num336, num337].type != 31 && Math.Abs(num336 - num330) <= 2 + WorldGen.genRand.Next(3) && Math.Abs(num337 - num331) <= 2 + WorldGen.genRand.Next(3))
{
                                                        Main.tile[num336, num337].active(false);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        num303++;
                    }
                    if (!GenVars.flipInfections)
                    {
                        WorldGen.CrimPlaceHearts();
                    }
                }
                if (WorldGen.drunkWorldGen)
                {
                    flag15 = false;
                }
                if (!flag15)
                {
                    progress.Message = Lang.gen[20].Value;
                    int num338 = 0;
                    while ((double)num338 < num302)
                    {
                        int num339 = num295;
                        int num340 = num296;
                        int num341 = num293;
                        int num342 = num294;
                        double num343 = (double)num338 / num302;
                        progress.Set(num343);
                        bool flag20 = false;
                        int num344 = 0;
                        int num345 = 0;
                        int num346 = 0;
                        while (!flag20)
{
                            flag20 = true;
                            int num347 = Main.maxTilesX / 2;
                            int num348 = 200;
                            if (WorldGen.drunkWorldGen)
{
                                if (!GenVars.crimsonLeft)
{
                                    num344 = WorldGen.genRand.Next(num300, (int)((double)Main.maxTilesX * 0.5));
                                }
                                else
{
                                    num344 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.5), Main.maxTilesX - num300);
                                }
                            }
                            else
{
                                num344 = WorldGen.genRand.Next(num300, Main.maxTilesX - num300);
                            }
                            num345 = num344 - WorldGen.genRand.Next(200) - 100;
                            num346 = num344 + WorldGen.genRand.Next(200) + 100;
                            if (num345 < GenVars.evilBiomeBeachAvoidance)
{
                                num345 = GenVars.evilBiomeBeachAvoidance;
                            }
                            if (num346 > Main.maxTilesX - GenVars.evilBiomeBeachAvoidance)
{
                                num346 = Main.maxTilesX - GenVars.evilBiomeBeachAvoidance;
                            }
                            if (num344 < num345 + GenVars.evilBiomeAvoidanceMidFixer)
{
                                num344 = num345 + GenVars.evilBiomeAvoidanceMidFixer;
                            }
                            if (num344 > num346 - GenVars.evilBiomeAvoidanceMidFixer)
{
                                num344 = num346 - GenVars.evilBiomeAvoidanceMidFixer;
                            }
                            if (num345 < GenVars.CurrentDungeonGenVars.dungeonLocation + num301 && num346 > GenVars.CurrentDungeonGenVars.dungeonLocation - num301)
{
                                flag20 = false;
                            }
                            if (!WorldGen.remixWorldGen)
{
                                if (!WorldGen.tenthAnniversaryWorldGen || WorldGen.dontStarveWorldGen)
{
                                    if (num344 > num347 - num348 && num344 < num347 + num348)
{
                                        flag20 = false;
                                    }
                                    if (num345 > num347 - num348 && num345 < num347 + num348)
{
                                        flag20 = false;
                                    }
                                    if (num346 > num347 - num348 && num346 < num347 + num348)
{
                                        flag20 = false;
                                    }
                                }
                                if (num344 > GenVars.UndergroundDesertLocation.X && num344 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                    flag20 = false;
                                }
                                if (num345 > GenVars.UndergroundDesertLocation.X && num345 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                    flag20 = false;
                                }
                                if (num346 > GenVars.UndergroundDesertLocation.X && num346 < GenVars.UndergroundDesertLocation.X + GenVars.UndergroundDesertLocation.Width)
{
                                    flag20 = false;
                                }
                                if (num345 < num340 && num346 > num339)
{
                                    num339++;
                                    num340--;
                                    flag20 = false;
                                }
                                if ((!WorldGen.notTheBees || WorldGen.remixWorldGen) && num345 < num342 && num346 > num341)
{
                                    num341++;
                                    num342--;
                                    flag20 = false;
                                }
                            }
                        }
                        int num349 = 0;
                        if (GenVars.flipInfections)
{
                            WorldGen.CrimStart(num344, (int)num291 - 10);
                        }
                        for (int num350 = num345; num350 < num346; num350++)
{
                            if (!GenVars.flipInfections)
{
                                if (num349 > 0)
{
                                    num349--;
                                }
                                if (num350 == num344 || num349 == 0)
{
                                    int num351 = (int)num291;
                                    while ((double)num351 < num292 - 1.0)
{
                                        if (Main.tile[num350, num351].active() || Main.tile[num350, num351].wall > 0)
{
                                            if (num350 == num344)
{
                                                num349 = 20;
                                                WorldGen.ChasmRunner(num350, num351, WorldGen.genRand.Next(150) + 150, true);
                                                break;
                                            }
                                            if (WorldGen.genRand.Next(35) == 0 && num349 == 0)
{
                                                num349 = 30;
                                                bool flag21 = true;
                                                WorldGen.ChasmRunner(num350, num351, WorldGen.genRand.Next(50) + 50, flag21);
                                                break;
                                            }
                                            break;
                                        }
                                        else
{
                                            num351++;
                                        }
                                    }
                                }
                            }
                            int num352 = (int)num291;
                            while ((double)num352 < num292 - 1.0)
{
                                if (Main.tile[num350, num352].active())
{
                                    int num353 = num352 + WorldGen.genRand.Next(10, 14);
                                    for (int num354 = num352; num354 < num353; num354++)
{
                                        if (Main.tile[num350, num354].active() && Main.tile[num350, num354].type == 60 && num350 >= num345 + WorldGen.genRand.Next(5) && num350 < num346 - WorldGen.genRand.Next(5))
{
                                            Main.tile[num350, num354].type = 661;
                                        }
                                    }
                                    break;
                                }
                                num352++;
                            }
                        }
                        double num355 = num292 + 40.0;
                        for (int num356 = num345; num356 < num346; num356++)
{
                            num355 += (double)WorldGen.genRand.Next(-2, 3);
                            if (num355 < num292 + 30.0)
{
                                num355 = num292 + 30.0;
                            }
                            if (num355 > num292 + 50.0)
{
                                num355 = num292 + 50.0;
                            }
                            bool flag22 = false;
                            double num357 = num291;
                            if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
{
                                num357 = 0.0;
                            }
                            int num358 = (int)num357;
                            while ((double)num358 < num355)
{
                                if (((num356 > num345 + 1 && num356 < num346 - 2) || WorldGen.genRand.Next(2) != 0) && (((double)num358 > num357 + 1.0 && (double)num358 < num355 - 2.0) || WorldGen.genRand.Next(2) != 0))
{
                                    if (WorldGen.SecretSeed.noSurface.Enabled)
{
                                        if (Main.tile[num356, num358].wall == 216)
{
                                            Main.tile[num356, num358].wall = 217;
                                        }
                                        else if (Main.tile[num356, num358].wall == 187)
{
                                            Main.tile[num356, num358].wall = 220;
                                        }
                                    }
                                    if (Main.tile[num356, num358].active())
{
                                        if (Main.tile[num356, num358].type == 53 && num356 >= num345 + WorldGen.genRand.Next(5) && num356 <= num346 - WorldGen.genRand.Next(5))
{
                                            Main.tile[num356, num358].type = 112;
                                        }
                                        if ((double)num358 < num292 - 1.0 && !flag22)
{
                                            if (Main.tile[num356, num358].type == 0)
{
                                                WorldGen.grassSpread = 0;
                                                WorldGen.SpreadGrass(num356, num358, 0, 23, true, default(TileColorCache));
                                            }
                                            else if (Main.tile[num356, num358].type == 59)
{
                                                WorldGen.grassSpread = 0;
                                                WorldGen.SpreadGrass(num356, num358, 59, 661, true, default(TileColorCache));
                                            }
                                        }
                                        flag22 = true;
                                        if (Main.tile[num356, num358].wall == 216)
{
                                            Main.tile[num356, num358].wall = 217;
                                        }
                                        else if (Main.tile[num356, num358].wall == 187)
{
                                            Main.tile[num356, num358].wall = 220;
                                        }
                                        if (Main.tile[num356, num358].type == 1)
{
                                            if (num356 >= num345 + WorldGen.genRand.Next(5) && num356 <= num346 - WorldGen.genRand.Next(5))
{
                                                Main.tile[num356, num358].type = 25;
                                            }
                                        }
                                        else if (Main.tile[num356, num358].type == 2)
{
                                            Main.tile[num356, num358].type = 23;
                                        }
                                        else if (Main.tile[num356, num358].type == 60)
{
                                            Main.tile[num356, num358].type = 661;
                                        }
                                        else if (Main.tile[num356, num358].type == 161)
{
                                            Main.tile[num356, num358].type = 163;
                                        }
                                        else if (Main.tile[num356, num358].type == 396)
{
                                            Main.tile[num356, num358].type = 400;
                                        }
                                        else if (Main.tile[num356, num358].type == 397)
{
                                            Main.tile[num356, num358].type = 398;
                                        }
                                    }
                                }
                                num358++;
                            }
                        }
                        if (GenVars.flipInfections)
{
                            WorldGen.CrimPlaceHearts();
                        }
                        else
{
                            for (int num359 = num345; num359 < num346; num359++)
{
                                for (int num360 = 0; num360 < Main.maxTilesY - 50; num360++)
{
                                    if (Main.tile[num359, num360].active() && Main.tile[num359, num360].type == 31)
{
                                        int num361 = num359 - 13;
                                        int num362 = num359 + 13;
                                        int num363 = num360 - 13;
                                        int num364 = num360 + 13;
                                        for (int num365 = num361; num365 < num362; num365++)
{
                                            if (num365 > 10 && num365 < Main.maxTilesX - 10)
{
                                                for (int num366 = num363; num366 < num364; num366++)
{
                                                    if (Math.Abs(num365 - num359) + Math.Abs(num366 - num360) < 9 + WorldGen.genRand.Next(11) && WorldGen.genRand.Next(3) != 0 && Main.tile[num365, num366].type != 31)
{
                                                        Main.tile[num365, num366].active(true);
                                                        Main.tile[num365, num366].type = 25;
                                                        if (Math.Abs(num365 - num359) <= 1 && Math.Abs(num366 - num360) <= 1)
{
                                                            Main.tile[num365, num366].active(false);
                                                        }
                                                    }
                                                    if (Main.tile[num365, num366].type != 31 && Math.Abs(num365 - num359) <= 2 + WorldGen.genRand.Next(3) && Math.Abs(num366 - num360) <= 2 + WorldGen.genRand.Next(3))
{
                                                        Main.tile[num365, num366].active(false);
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        num338++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Lakes, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[19].Value;
                double num367 = (double)Main.maxTilesX / 4200.0;
                int num368 = WorldGen.genRand.Next((int)(num367 * 3.0), (int)(num367 * 6.0));
                for (int num369 = 0; num369 < num368; num369++)
                {
                    int num370 = Main.maxTilesX / 4;
                    if (GenVars.numLakes >= GenVars.maxLakes - 1)
                    {
                        break;
                    }
                    double num371 = (double)num369 / (double)num368;
                    progress.Set(num371);
                    while (num370 > 0)
                    {
                        bool flag23 = false;
                        num370--;
                        int num372 = WorldGen.genRand.Next(GenVars.lakesBeachAvoidance, Main.maxTilesX - GenVars.lakesBeachAvoidance);
                        if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
{
                            num372 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                            while (WorldGen.dontStarveWorldGen && (double)num372 > (double)Main.maxTilesX * 0.45)
{
                                if ((double)num372 >= (double)Main.maxTilesX * 0.55)
{
                                    break;
                                }
                                num372 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                            }
                        }
                        else
{
                            while ((double)num372 > (double)Main.maxTilesX * 0.45 && (double)num372 < (double)Main.maxTilesX * 0.55)
{
                                num372 = WorldGen.genRand.Next(GenVars.lakesBeachAvoidance, Main.maxTilesX - GenVars.lakesBeachAvoidance);
                            }
                        }
                        for (int num373 = 0; num373 < GenVars.numLakes; num373++)
{
                            if (Math.Abs(num372 - GenVars.LakeX[num373]) < 150)
{
                                flag23 = true;
                                break;
                            }
                        }
                        for (int num374 = 0; num374 < GenVars.numMCaves; num374++)
{
                            if (Math.Abs(num372 - GenVars.mCaveX[num374]) < 100)
{
                                flag23 = true;
                                break;
                            }
                        }
                        for (int num375 = 0; num375 < GenVars.numTunnels; num375++)
{
                            if (Math.Abs(num372 - GenVars.tunnelX[num375]) < 100)
{
                                flag23 = true;
                                break;
                            }
                        }
                        if (!flag23)
{
                            int num376 = (int)GenVars.worldSurfaceLow - 20;
                            while (!Main.tile[num372, num376].active())
{
                                num376++;
                                if ((double)num376 >= Main.worldSurface || Main.tile[num372, num376].wall > 0)
{
                                    flag23 = true;
                                    break;
                                }
                            }
                            if (Main.tile[num372, num376].type == 53)
{
                                flag23 = true;
                            }
                            if (!flag23)
{
                                int num377 = 50;
                                for (int num378 = num372 - num377; num378 <= num372 + num377; num378++)
{
                                    for (int num379 = num376 - num377; num379 <= num376 + num377; num379++)
{
                                        if (Main.tile[num378, num379].type == 203 || Main.tile[num378, num379].type == 25)
{
                                            flag23 = true;
                                            break;
                                        }
                                    }
                                }
                                if (!flag23)
{
                                    int num380 = num376;
                                    num377 = 20;
                                    while (!WorldGen.SolidTile(num372 - num377, num376, false) || !WorldGen.SolidTile(num372 + num377, num376, false))
{
                                        num376++;
                                        if ((double)num376 > Main.worldSurface - 50.0)
{
                                            flag23 = true;
                                        }
                                    }
                                    if (num376 - num380 <= 10)
{
                                        num377 = 60;
                                        for (int num381 = num372 - num377; num381 <= num372 + num377; num381++)
{
                                            int num382 = num376 - 20;
                                            if (Main.tile[num381, num382].active() || Main.tile[num381, num382].wall > 0)
{
                                                flag23 = true;
                                            }
                                        }
                                        if (!flag23)
{
                                            int num383 = 0;
                                            for (int num384 = num372 - num377; num384 <= num372 + num377; num384++)
{
                                                for (int num385 = num376; num385 <= num376 + num377 * 2; num385++)
{
                                                    if (WorldGen.SolidTile(num384, num385, false))
{
                                                        num383++;
                                                    }
                                                }
                                            }
                                            int num386 = (num377 * 2 + 1) * (num377 * 2 + 1);
                                            if ((double)num383 >= (double)num386 * 0.8 && !GenVars.UndergroundDesertLocation.Intersects(new Rectangle(num372 - 8, num376 - 8, 16, 16)))
{
                                                WorldGen.SonOfLakinater(num372, num376, 1.0);
                                                GenVars.LakeX[GenVars.numLakes] = num372;
                                                GenVars.numLakes++;
                                                break;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.StoneToIceAndSiltPlusMudIntoSlush, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                for (int num387 = GenVars.snowTop; num387 < GenVars.snowBottom; num387++)
                {
                    for (int num388 = GenVars.snowMinX[num387]; num388 < GenVars.snowMaxX[num387]; num388++)
                    {
                        ushort type3 = Main.tile[num388, num387].type;
                        if (type3 == 123)
{
                            if (WorldGen.SecretSeed.surfaceIsDesert.Enabled && WorldGen.SecretSeed.noSurface.Enabled)
{
                                Main.tile[num388, num387].type = 53;
                            }
                            else
{
                                Main.tile[num388, num387].type = 224;
                            }
                        }
                        else if (type3 == 59)
{
                            bool flag24 = true;
                            int num389 = 3;
                            for (int num390 = num388 - num389; num390 <= num388 + num389; num390++)
{
                                for (int num391 = num387 - num389; num391 <= num387 + num389; num391++)
{
                                    if (Main.tile[num390, num391].active() && (Main.tile[num390, num391].type == 60 || Main.tile[num390, num391].type == 70 || Main.tile[num390, num391].type == 71 || Main.tile[num390, num391].type == 72))
{
                                        flag24 = false;
                                        break;
                                    }
                                }
                            }
                            if (flag24)
{
                                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled && WorldGen.SecretSeed.noSurface.Enabled)
{
                                    Main.tile[num388, num387].type = 53;
                                }
                                else
{
                                    Main.tile[num388, num387].type = 224;
                                }
                            }
                        }
                        else if (type3 == 1)
{
                            Main.tile[num388, num387].type = 161;
                        }
                    }
                }
            });
            if (!WorldGen.Skyblock.denyAllGeneration && WorldGen.SecretSeed.dualDungeons.Enabled)
            {
                WorldGen.AddGenerationPass(new DitherSnakePass(GenPassNameID.DualDungeonsDitherSnake));
            }
            WorldGen.AddGenerationPass(GenPassNameID.Dungeon, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(0.0);
                for (int num392 = 0; num392 < GenVars.dungeonGenVars.Count; num392++)
                {
                    DungeonCrawler.SetupDungeonData(num392, num392 == 0);
                    DungeonCrawler.SetupDungeonDataVariables(num392, WorldGen.genRand);
                }
                GenVars.CurrentDungeon = 0;
                int num393 = GenVars.CurrentDungeonGenVars.dungeonLocation;
                int num394 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + WorldGen.genRand.Next(-200, 200);
                int num395 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + 200;
                int num396 = num394;
                bool flag25 = false;
                for (int num397 = 0; num397 < 10; num397++)
                {
                    if (WorldGen.SolidTile(num393, num396 + num397, false))
                    {
                        flag25 = true;
                        break;
                    }
                }
                if (!flag25)
                {
                    while (num396 < num395 && !WorldGen.SolidTile(num393, num396 + 10, false))
                    {
                        num396++;
                    }
                }
                if (flag25)
                {
                    int num398 = 60;
                    int num399 = 0;
                    while (WorldGen.SolidTile(num393, num396 - num399, false))
                    {
                        num399++;
                        if (num399 == num398)
{
                            break;
                        }
                    }
                    if (num399 < num398)
                    {
                        num396 += num398 - num399;
                    }
                }
                if (WorldGen.drunkWorldGen && !WorldGen.SecretSeed.noSurface.Enabled)
                {
                    num396 = (int)Main.worldSurface + 70;
                }
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    WorldGen.DungeonDesertCleanup(num393);
                }
                DungeonCrawler.MakeDungeon(num393, num396, progress);
                if (DungeonCrawler.dungeonData.Count > 1)
                {
                    for (int num400 = 1; num400 < DungeonCrawler.dungeonData.Count; num400++)
                    {
                        GenVars.CurrentDungeon = num400;
                        num393 = GenVars.CurrentDungeonGenVars.dungeonLocation;
                        int num401 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + WorldGen.genRand.Next(-200, 200);
                        num395 = (int)((Main.worldSurface + Main.rockLayer) / 2.0) + 200;
                        num396 = num401;
                        flag25 = false;
                        for (int num402 = 0; num402 < 10; num402++)
{
                            if (WorldGen.SolidTile(num393, num396 + num402, false))
{
                                flag25 = true;
                                break;
                            }
                        }
                        if (!flag25)
{
                            while (num396 < num395 && !WorldGen.SolidTile(num393, num396 + 10, false))
{
                                num396++;
                            }
                        }
                        if (flag25)
{
                            int num403 = 60;
                            int num404 = 0;
                            while (WorldGen.SolidTile(num393, num396 - num404, false))
{
                                num404++;
                                if (num404 == num403)
{
                                    break;
                                }
                            }
                            if (num404 < num403)
{
                                num396 += num403 - num404;
                            }
                        }
                        if (WorldGen.drunkWorldGen && !WorldGen.SecretSeed.noSurface.Enabled)
{
                            num396 = (int)Main.worldSurface + 70;
                        }
                        if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
{
                            WorldGen.DungeonDesertCleanup(num393);
                        }
                        DungeonCrawler.MakeDungeon(num393, num396, progress);
                    }
                    GenVars.CurrentDungeon = 0;
                }
                DungeonCrawler.dungeonData.Clear();
                if (WorldGen.dontStarveWorldGen && !WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
                {
                    WorldGen.LavaLayerCaverer();
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.MountainCaveOpenings, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[21].Value;
                for (int num405 = 0; num405 < GenVars.numMCaves; num405++)
                {
                    progress.Set((double)((float)num405 / (float)GenVars.numMCaves));
                    int num406 = GenVars.mCaveX[num405];
                    int num407 = GenVars.mCaveY[num405];
                    WorldGen.CaveOpenater(num406, num407);
                    WorldGen.Cavinator(num406, num407, WorldGen.genRand.Next(40, 50));
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.BeachesAndOceanCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.pooEverywhere.Enabled)
                {
                    WorldGen.SecretSeed.DoPooEverywhere();
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                int num408 = 50;
                progress.Message = Lang.gen[22].Value;
                bool flag26 = false;
                bool flag27 = false;
                if (WorldGen.genRand.Next(4) == 0)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        flag26 = true;
                    }
                    else
                    {
                        flag27 = true;
                    }
                }
                for (int num409 = 0; num409 < 2; num409++)
                {
                    if (num409 == 0)
                    {
                        progress.Set(0.0);
                        int num410 = 0;
                        int num411 = WorldGen.genRand.Next(GenVars.oceanWaterStartRandomMin, GenVars.oceanWaterStartRandomMax);
                        if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
{
                            num411 = GenVars.oceanWaterForcedJungleLength;
                        }
                        int num412 = GenVars.leftBeachEnd - num408;
                        if (num411 > num412)
{
                            num411 = num412;
                        }
                        int num413 = 0;
                        double num414 = 1.0;
                        int num415 = 0;
                        while (!Main.tile[num411 - 1, num415].active())
{
                            num415++;
                        }
                        GenVars.shellStartYLeft = num415;
                        num415 += WorldGen.genRand.Next(1, 5);
                        int num416 = num411 - 1;
                        for (int num417 = num416; num417 >= num410; num417--)
{
                            progress.Set((double)((float)(num417 - num416) / (float)(num410 - num416)), 0.0, 0.5);
                            if (num417 > 30)
{
                                num413++;
                                num414 = WorldGen.TuneOceanDepth(num413, num414, flag26);
                            }
                            else
{
                                num414 += 1.0;
                            }
                            int num418 = WorldGen.genRand.Next(15, 20);
                            int num419 = 0;
                            while ((double)num419 < (double)num415 + num414 + (double)num418)
{
                                if ((double)num419 < (double)num415 + num414 * 0.75 - 3.0)
{
                                    Main.tile[num417, num419].active(false);
                                    if (num419 > num415)
{
                                        Main.tile[num417, num419].liquid = byte.MaxValue;
                                        Main.tile[num417, num419].liquidType(0);
                                    }
                                    else if (num419 == num415)
{
                                        Main.tile[num417, num419].liquid = 127;
                                        if (GenVars.shellStartXLeft == 0)
{
                                            GenVars.shellStartXLeft = num417;
                                        }
                                    }
                                }
                                else if (num419 > num415)
{
                                    Main.tile[num417, num419].type = 53;
                                    Main.tile[num417, num419].active(true);
                                }
                                Main.tile[num417, num419].wall = 0;
                                num419++;
                            }
                        }
                    }
                    else
                    {
                        progress.Set(0.5);
                        int num410 = Main.maxTilesX - WorldGen.genRand.Next(GenVars.oceanWaterStartRandomMin, GenVars.oceanWaterStartRandomMax);
                        int num411 = Main.maxTilesX;
                        if (GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left)
{
                            num410 = Main.maxTilesX - GenVars.oceanWaterForcedJungleLength;
                        }
                        int num420 = GenVars.rightBeachStart + num408;
                        if (num410 < num420)
{
                            num410 = num420;
                        }
                        double num421 = 1.0;
                        int num422 = 0;
                        int num423 = 0;
                        while (!Main.tile[num410, num423].active())
{
                            num423++;
                        }
                        GenVars.shellStartXRight = 0;
                        GenVars.shellStartYRight = num423;
                        num423 += WorldGen.genRand.Next(1, 5);
                        int num424 = num410;
                        for (int num425 = num410; num425 < num411; num425++)
{
                            progress.Set((double)((float)(num425 - num424) / (float)(num411 - num424)), 0.5, 1.0);
                            if (num425 < num411 - 30)
{
                                num422++;
                                num421 = WorldGen.TuneOceanDepth(num422, num421, flag27);
                            }
                            else
{
                                num421 += 1.0;
                            }
                            int num426 = WorldGen.genRand.Next(15, 20);
                            int num427 = 0;
                            while ((double)num427 < (double)num423 + num421 + (double)num426)
{
                                if ((double)num427 < (double)num423 + num421 * 0.75 - 3.0)
{
                                    Main.tile[num425, num427].active(false);
                                    if (num427 > num423)
{
                                        Main.tile[num425, num427].liquid = byte.MaxValue;
                                        Main.tile[num425, num427].liquidType(0);
                                    }
                                    else if (num427 == num423)
{
                                        Main.tile[num425, num427].liquid = 127;
                                        if (GenVars.shellStartXRight == 0)
{
                                            GenVars.shellStartXRight = num425;
                                        }
                                    }
                                }
                                else if (num427 > num423)
{
                                    Main.tile[num425, num427].type = 53;
                                    Main.tile[num425, num427].active(true);
                                }
                                Main.tile[num425, num427].wall = 0;
                                num427++;
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Gems, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[23].Value;
                Main.tileSolid[484] = false;
                for (int num428 = 63; num428 <= 68; num428++)
                {
                    double num429 = (double)(num428 - 63) / 6.0;
                    progress.Set(num429);
                    double num430 = 0.0;
                    if (num428 == 67)
                    {
                        num430 = (double)Main.maxTilesX * 0.5;
                    }
                    else if (num428 == 66)
                    {
                        num430 = (double)Main.maxTilesX * 0.45;
                    }
                    else if (num428 == 63)
                    {
                        num430 = (double)Main.maxTilesX * 0.3;
                    }
                    else if (num428 == 65)
                    {
                        num430 = (double)Main.maxTilesX * 0.25;
                    }
                    else if (num428 == 64)
                    {
                        num430 = (double)Main.maxTilesX * 0.1;
                    }
                    else if (num428 == 68)
                    {
                        num430 = (double)Main.maxTilesX * 0.05;
                    }
                    num430 *= 0.2;
                    int num431 = 0;
                    while ((double)num431 < num430)
                    {
                        int num432 = 3;
                        int num433;
                        int num434;
                        do
{
                            num433 = WorldGen.genRand.Next(0, Main.maxTilesX);
                            num434 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY);
                        }
                        while ((!Main.tile[num433, num434].active() || Main.tile[num433, num434].type != 1) && --num432 > 0);
                        if (num432 != 0)
{
                            WorldGen.TileRunner(num433, num434, (double)WorldGen.genRand.Next(2, 6), WorldGen.genRand.Next(3, 7), num428, false, 0.0, 0.0, false, true, -1);
                        }
                        num431++;
                    }
                }
                for (int num435 = 0; num435 < 2; num435++)
                {
                    int num436 = 1;
                    int num437 = 5;
                    int num438 = Main.maxTilesX - 5;
                    if (num435 == 1)
                    {
                        num436 = -1;
                        num437 = Main.maxTilesX - 5;
                        num438 = 5;
                    }
                    for (int num439 = num437; num439 != num438; num439 += num436)
                    {
                        if (num439 <= GenVars.UndergroundDesertLocation.Left || num439 >= GenVars.UndergroundDesertLocation.Right)
{
                            for (int num440 = 10; num440 < Main.maxTilesY - 10; num440++)
{
                                if (Main.tile[num439, num440].active() && Main.tile[num439, num440 + 1].active() && Main.tileSand[(int)Main.tile[num439, num440].type] && Main.tileSand[(int)Main.tile[num439, num440 + 1].type])
{
                                    ushort type4 = Main.tile[num439, num440].type;
                                    int num441 = num439 + num436;
                                    int num442 = num440 + 1;
                                    if (!Main.tile[num441, num440].active())
{
                                        if (!Main.tile[num441, num442].active())
{
                                            while (!Main.tile[num441, num442].active() && WorldGen.InWorld(num441, num442, 10))
{
                                                num442++;
                                            }
                                            num442--;
                                            Main.tile[num439, num440].active(false);
                                            Main.tile[num441, num442].active(true);
                                            Main.tile[num441, num442].type = type4;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.GravitatingSandCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.roundLandmasses.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[24].Value;
                for (int num443 = 0; num443 < Main.maxTilesX; num443++)
                {
                    double num444 = (double)num443 / (double)(Main.maxTilesX - 1);
                    progress.Set(num444);
                    bool flag28 = false;
                    int num445 = 0;
                    for (int num446 = Main.maxTilesY - 1; num446 > 0; num446--)
                    {
                        if (WorldGen.SolidOrSlopedTile(num443, num446))
{
                            ushort type5 = Main.tile[num443, num446].type;
                            if (flag28 && num446 < (int)Main.worldSurface && num446 != num445 - 1 && TileID.Sets.Falling[(int)type5])
{
                                for (int num447 = num446; num447 < num445; num447++)
{
                                    Main.tile[num443, num447].ResetToType(type5);
                                }
                            }
                            flag28 = true;
                            num445 = num446;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.OceanCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.roundLandmasses.Enabled)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                int num448 = 3;
                if (WorldGen.remixWorldGen)
                {
                    num448 = 2;
                }
                for (int num449 = 0; num449 < 2; num449++)
                {
                    if ((num449 != 0 || GenVars.CurrentDungeonGenVars.dungeonSide < (int)DungeonSide.Right) && (num449 != 1 || GenVars.CurrentDungeonGenVars.dungeonSide > (int)DungeonSide.Left) && (WorldGen.genRand.Next(num448) == 0 || WorldGen.drunkWorldGen || WorldGen.tenthAnniversaryWorldGen))
                    {
                        progress.Message = Lang.gen[90].Value;
                        int num450 = WorldGen.genRand.Next(55, 95);
                        if (num449 == 1)
{
                            num450 = WorldGen.genRand.Next(Main.maxTilesX - 95, Main.maxTilesX - 55);
                        }
                        int num451 = 0;
                        while (!Main.tile[num450, num451].active())
{
                            num451++;
                        }
                        WorldGen.oceanCave(num450, num451);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Shimmer, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                int num452 = 50;
                int num453 = (int)(Main.worldSurface + Main.rockLayer) / 2 + num452;
                int num454 = (int)((double)((Main.maxTilesY - 250) * 2) + Main.rockLayer) / 3;
                if (num454 > Main.maxTilesY - 330 - 100 - 30)
                {
                    num454 = Main.maxTilesY - 330 - 100 - 30;
                }
                if (num454 <= num453)
                {
                    num454 = num453 + 50;
                }
                int num455 = WorldGen.genRand.Next(num453, num454);
                int num456;
                if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
                {
                    num456 = WorldGen.genRand.Next(200, (int)((double)Main.maxTilesX * 0.11));
                }
                else
                {
                    num456 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200);
                }
                int num457 = (int)Main.worldSurface + 150;
                int num458 = (int)(Main.rockLayer + Main.worldSurface + 200.0) / 2;
                if (num458 <= num457)
                {
                    num458 = num457 + 50;
                }
                if (WorldGen.tenthAnniversaryWorldGen)
                {
                    num455 = WorldGen.genRand.Next(num457, num458);
                }
                int num459 = 0;
                while (!WorldGen.ShimmerMakeBiome(num456, num455))
                {
                    num459++;
                    if (WorldGen.tenthAnniversaryWorldGen && num459 < 10000)
                    {
                        num455 = WorldGen.genRand.Next(num457, num458);
                        if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
{
                            num456 = WorldGen.genRand.Next(200, (int)((double)Main.maxTilesX * 0.11));
                        }
                        else
{
                            num456 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200);
                        }
                    }
                    else if (num459 > 20000)
                    {
                        num455 = WorldGen.genRand.Next((int)Main.worldSurface + 100 + 20, num454);
                        if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
{
                            num456 = WorldGen.genRand.Next(200, (int)((double)Main.maxTilesX * 0.2));
                        }
                        else
{
                            num456 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.8), Main.maxTilesX - 200);
                        }
                    }
                    else
                    {
                        num455 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2 + 20, num454);
                        if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
{
                            num456 = WorldGen.genRand.Next(200, (int)((double)Main.maxTilesX * 0.11));
                        }
                        else
{
                            num456 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.89), Main.maxTilesX - 200);
                        }
                    }
                }
                GenVars.shimmerPosition = new Vector2D((double)num456, (double)num455);
                int num460 = 200;
                GenVars.structures.AddProtectedStructure(new Rectangle(num456 - num460 / 2, num455 - num460 / 2, num460, num460), 0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtWallCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    WorldGen.SecretSeed.DoNoSurfaceFillTheTop();
                    return;
                }
                progress.Message = Lang.gen[25].Value;
                for (int num461 = 3; num461 < Main.maxTilesX - 3; num461++)
                {
                    double num462 = (double)num461 / (double)Main.maxTilesX;
                    progress.Set(0.5 * num462);
                    bool flag29 = true;
                    int num463 = 0;
                    while ((double)num463 < Main.worldSurface)
                    {
                        if (flag29)
{
                            if (Main.tile[num461, num463].wall == 2 || Main.tile[num461, num463].wall == 40 || Main.tile[num461, num463].wall == 64 || Main.tile[num461, num463].wall == 86)
{
                                Main.tile[num461, num463].wall = 0;
                            }
                            if (!Main.tile[num461, num463].active() || (Main.tile[num461, num463].type != 53 && Main.tile[num461, num463].type != 112 && Main.tile[num461, num463].type != 234))
{
                                if (Main.tile[num461 - 1, num463].wall == 2 || Main.tile[num461 - 1, num463].wall == 40 || Main.tile[num461 - 1, num463].wall == 40)
{
                                    Main.tile[num461 - 1, num463].wall = 0;
                                }
                                if ((Main.tile[num461 - 2, num463].wall == 2 || Main.tile[num461 - 2, num463].wall == 40 || Main.tile[num461 - 2, num463].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num461 - 2, num463].wall = 0;
                                }
                                if ((Main.tile[num461 - 3, num463].wall == 2 || Main.tile[num461 - 3, num463].wall == 40 || Main.tile[num461 - 3, num463].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num461 - 3, num463].wall = 0;
                                }
                                if (Main.tile[num461 + 1, num463].wall == 2 || Main.tile[num461 + 1, num463].wall == 40 || Main.tile[num461 + 1, num463].wall == 40)
{
                                    Main.tile[num461 + 1, num463].wall = 0;
                                }
                                if ((Main.tile[num461 + 2, num463].wall == 2 || Main.tile[num461 + 2, num463].wall == 40 || Main.tile[num461 + 2, num463].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num461 + 2, num463].wall = 0;
                                }
                                if ((Main.tile[num461 + 3, num463].wall == 2 || Main.tile[num461 + 3, num463].wall == 40 || Main.tile[num461 + 3, num463].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num461 + 3, num463].wall = 0;
                                }
                                if (Main.tile[num461, num463].active())
{
                                    flag29 = false;
                                }
                            }
                        }
                        else if (Main.tile[num461, num463].wall == 0 && Main.tile[num461, num463 + 1].wall == 0 && Main.tile[num461, num463 + 2].wall == 0 && Main.tile[num461, num463 + 3].wall == 0 && Main.tile[num461, num463 + 4].wall == 0 && Main.tile[num461 - 1, num463].wall == 0 && Main.tile[num461 + 1, num463].wall == 0 && Main.tile[num461 - 2, num463].wall == 0 && Main.tile[num461 + 2, num463].wall == 0 && !Main.tile[num461, num463].active() && !Main.tile[num461, num463 + 1].active() && !Main.tile[num461, num463 + 2].active() && !Main.tile[num461, num463 + 3].active())
{
                            flag29 = true;
                        }
                        num463++;
                    }
                }
                for (int num464 = Main.maxTilesX - 5; num464 >= 5; num464--)
                {
                    double num465 = (double)num464 / (double)Main.maxTilesX;
                    progress.Set(1.0 - 0.5 * num465);
                    bool flag30 = true;
                    int num466 = 0;
                    while ((double)num466 < Main.worldSurface)
                    {
                        if (flag30)
{
                            if (Main.tile[num464, num466].wall == 2 || Main.tile[num464, num466].wall == 40 || Main.tile[num464, num466].wall == 64)
{
                                Main.tile[num464, num466].wall = 0;
                            }
                            if (!Main.tile[num464, num466].active() || Main.tile[num464, num466].type != 53)
{
                                if (Main.tile[num464 - 1, num466].wall == 2 || Main.tile[num464 - 1, num466].wall == 40 || Main.tile[num464 - 1, num466].wall == 40)
{
                                    Main.tile[num464 - 1, num466].wall = 0;
                                }
                                if ((Main.tile[num464 - 2, num466].wall == 2 || Main.tile[num464 - 2, num466].wall == 40 || Main.tile[num464 - 2, num466].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num464 - 2, num466].wall = 0;
                                }
                                if ((Main.tile[num464 - 3, num466].wall == 2 || Main.tile[num464 - 3, num466].wall == 40 || Main.tile[num464 - 3, num466].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num464 - 3, num466].wall = 0;
                                }
                                if (Main.tile[num464 + 1, num466].wall == 2 || Main.tile[num464 + 1, num466].wall == 40 || Main.tile[num464 + 1, num466].wall == 40)
{
                                    Main.tile[num464 + 1, num466].wall = 0;
                                }
                                if ((Main.tile[num464 + 2, num466].wall == 2 || Main.tile[num464 + 2, num466].wall == 40 || Main.tile[num464 + 2, num466].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num464 + 2, num466].wall = 0;
                                }
                                if ((Main.tile[num464 + 3, num466].wall == 2 || Main.tile[num464 + 3, num466].wall == 40 || Main.tile[num464 + 3, num466].wall == 40) && WorldGen.genRand.Next(2) == 0)
{
                                    Main.tile[num464 + 3, num466].wall = 0;
                                }
                                if (Main.tile[num464, num466].active())
{
                                    flag30 = false;
                                }
                            }
                        }
                        else if (Main.tile[num464, num466].wall == 0 && Main.tile[num464, num466 + 1].wall == 0 && Main.tile[num464, num466 + 2].wall == 0 && Main.tile[num464, num466 + 3].wall == 0 && Main.tile[num464, num466 + 4].wall == 0 && Main.tile[num464 - 1, num466].wall == 0 && Main.tile[num464 + 1, num466].wall == 0 && Main.tile[num464 - 2, num466].wall == 0 && Main.tile[num464 + 2, num466].wall == 0 && !Main.tile[num464, num466].active() && !Main.tile[num464, num466 + 1].active() && !Main.tile[num464, num466 + 2].active() && !Main.tile[num464, num466 + 3].active())
{
                            flag30 = true;
                        }
                        num466++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Pyramids, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.Variations.noSurfaceNoPyramids)
                {
                    return;
                }
                Rectangle undergroundDesertLocation = GenVars.UndergroundDesertLocation;
                if (Main.tenthAnniversaryWorld && !WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    int x = undergroundDesertLocation.Center.X;
                    int num467 = undergroundDesertLocation.Top - 10;
                    WorldGen.Pyramid(x, num467, 75, 125, false);
                }
                for (int num468 = 0; num468 < GenVars.numPyr; num468++)
                {
                    int num469 = GenVars.PyrX[num468];
                    int num470 = GenVars.PyrY[num468];
                    int num471 = 75;
                    int num472 = 125;
                    bool flag31 = false;
                    if (WorldGen.SecretSeed.dualDungeons.Enabled)
                    {
                        flag31 = true;
                    }
                    if (num469 > 300 && num469 < Main.maxTilesX - 300 && (GenVars.CurrentDungeonGenVars.dungeonSide > (int)DungeonSide.Left || (double)num469 >= (double)GenVars.CurrentDungeonGenVars.generatingDungeonPositionX + (double)Main.maxTilesX * 0.15) && (GenVars.CurrentDungeonGenVars.dungeonSide < (int)DungeonSide.Right || (double)num469 <= (double)GenVars.CurrentDungeonGenVars.generatingDungeonPositionX - (double)Main.maxTilesX * 0.15))
                    {
                        if (!Main.tenthAnniversaryWorld || WorldGen.SecretSeed.dualDungeons.Enabled || !undergroundDesertLocation.Contains(num469, num470))
{
                            while (!Main.tile[num469, num470].active() && (double)num470 < Main.worldSurface)
{
                                num470++;
                            }
                            if ((double)num470 < Main.worldSurface && Main.tile[num469, num470].type == 53)
{
                                int num473 = Main.maxTilesX;
                                for (int num474 = 0; num474 < num468; num474++)
{
                                    int num475 = Math.Abs(num469 - GenVars.PyrX[num474]);
                                    if (num475 < num473)
{
                                        num473 = num475;
                                    }
                                }
                                int num476 = 220;
                                if (WorldGen.drunkWorldGen)
{
                                    num476 /= 2;
                                }
                                if (num473 >= num476)
{
                                    num470--;
                                    if (WorldGen.SecretSeed.dualDungeons.Enabled)
{
                                        if (DungeonUtils.InAnyPotentialDungeonBounds(num469, num470 + num472, 5, false))
{
                                            num470 -= 50;
                                            num472 = 100;
                                        }
                                        if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num469, num470 + num472, 5, false))
{
                                            goto IL_0212;
                                        }
                                    }
                                    WorldGen.Pyramid(num469, num470, num471, num472, flag31);
                                }
                            }
                        }
                    }
                    IL_0212:;
                }
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                {
                    int num477 = WorldGen.genRand.Next(5, 8);
                    num477 *= Main.maxTilesX / 4200;
                    for (int num478 = 0; num478 < num477; num478++)
                    {
                        int num479 = WorldGen.genRand.Next(300, Main.maxTilesX - 300);
                        while ((double)num479 > (double)Main.maxTilesX * 0.47 && (double)num479 < (double)Main.maxTilesX * 0.53)
{
                            num479 = WorldGen.genRand.Next(300, Main.maxTilesX - 300);
                        }
                        int num480 = WorldGen.FindLowestCloud();
                        while (!Main.tile[num479, num480].active() && (double)num480 < Main.worldSurface)
{
                            num480++;
                        }
                        if ((double)num480 < Main.worldSurface && Main.tile[num479, num480].type == 53)
{
                            num480--;
                            WorldGen.Pyramid(num479, num480, 75, 125, false);
                        }
                    }
                }
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    int num481 = WorldGen.genRand.Next(5, 8);
                    num481 *= Main.maxTilesX / 4200;
                    num481 /= WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                    for (int num482 = 0; num482 < num481; num482++)
                    {
                        int num483 = WorldGen.genRand.Next(300, Main.maxTilesX - 300);
                        int num484 = WorldGen.genRand.Next(WorldGen.FindLowestCloud(), (int)Main.rockLayer);
                        while (((double)num483 > (double)Main.maxTilesX * 0.47 && (double)num483 < (double)Main.maxTilesX * 0.53) || Vector2D.Distance(new Vector2D((double)num483, (double)num484), GenVars.shimmerPosition) < 300.0)
{
                            num483 = WorldGen.genRand.Next(300, Main.maxTilesX - 300);
                            num484 = WorldGen.genRand.Next(WorldGen.FindLowestCloud(), (int)Main.rockLayer);
                        }
                        while (!Main.tile[num483, num484].active())
{
                            num484++;
                        }
                        num484--;
                        WorldGen.Pyramid(num483, num484, 75, 125, false);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtRockWallRunner, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                for (int num485 = 0; num485 < Main.maxTilesX; num485++)
                {
                    int num486 = WorldGen.genRand.Next(10, Main.maxTilesX - 10);
                    int num487 = WorldGen.genRand.Next(10, (int)Main.worldSurface);
                    if (Main.tile[num486, num487].wall == 2)
                    {
                        WorldGen.DirtyRockRunner(num486, num487);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.LivingTrees, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.Variations.noSurfaceNoLivingTrees)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.LivingTrees");
                progress.Set(0.0);
                int num488 = 200;
                int num489 = 0;
                double num490 = (double)Main.maxTilesX / 4200.0;
                int num491 = WorldGen.genRand.Next(0, (int)(2.0 * num490) + 1);
                if (num491 == 0 && WorldGen.genRand.Next(2) == 0)
                {
                    num491++;
                }
                if (WorldGen.SecretSeed.extraFloatingIslands.Enabled)
                {
                    num489 = WorldGen.FindLowestCloud() + 1;
                }
                if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
                {
                    if (WorldGen.SecretSeed.Variations.extraLivingTreesReducedAmount)
                    {
                        num491 += (int)(3.0 * num490);
                    }
                    else
                    {
                        num491 += (int)(30.0 * num490);
                    }
                    num488 = 150;
                    num489 = WorldGen.FindLowestCloud() + 1;
                }
                else if (WorldGen.notTheBees && WorldGen.tenthAnniversaryWorldGen && !WorldGen.drunkWorldGen)
                {
                    num491 += (int)(10.0 * num490);
                }
                else if (WorldGen.drunkWorldGen)
                {
                    num491 += (int)(2.0 * num490);
                }
                else if (Main.tenthAnniversaryWorld)
                {
                    num491 += (int)(3.0 * num490);
                }
                else if (WorldGen.remixWorldGen)
                {
                    num491 += (int)(2.0 * num490);
                }
                if (WorldGen.skyblockWorldGen)
                {
                    num489 = 50;
                }
                for (int num492 = 0; num492 < num491; num492++)
                {
                    progress.Set((double)((float)num492 / (float)num491), 0.0, 0.5);
                    bool flag32 = false;
                    int num493 = 0;
                    while (!flag32)
                    {
                        num493++;
                        if (num493 > Main.maxTilesX / 2)
{
                            flag32 = true;
                        }
                        int num494 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                        if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
{
                            num494 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((float)Main.maxTilesX * 0.85f));
                        }
                        if (num494 <= Main.maxTilesX / 2 - num488 || num494 >= Main.maxTilesX / 2 + num488)
{
                            int num495 = num489;
                            if (WorldGen.SecretSeed.noSurface.Enabled)
{
                                num495 = WorldGen.genRand.Next(200, Main.UnderworldLayer - 200);
                            }
                            else
{
                                while (!Main.tile[num494, num495].active() && (double)num495 < Main.worldSurface)
{
                                    num495++;
                                }
                                if ((double)num495 >= Main.worldSurface)
{
                                    continue;
                                }
                            }
                            if (Main.tile[num494, num495].type == 0 || (WorldGen.notTheBees && Main.tile[num494, num495].type == 60) || (WorldGen.notTheBees && WorldGen.tenthAnniversaryWorldGen && !WorldGen.drunkWorldGen))
{
                                num495--;
                                if (num495 > 150)
{
                                    bool flag33 = true;
                                    if (WorldGen.IsTileNearby(num494, num495, 191, 10) || WorldGen.IsTileNearby(num494, num495, 192, 10))
{
                                        flag33 = false;
                                    }
                                    if (flag33 && !WorldGen.SecretSeed.errorWorld.Enabled)
{
                                        for (int num496 = num494 - 50; num496 < num494 + 50; num496++)
{
                                            for (int num497 = num495 - 50; num497 < num495 + 50; num497++)
{
                                                if (Main.tile[num496, num497].active())
{
                                                    ushort num498 = Main.tile[num496, num497].type;
                                                    if (num498 <= 189)
{
                                                        if (num498 != 41 && num498 - 43 > 1)
{
                                                            if (num498 != 189)
{
                                                                goto IL_03AC;
                                                            }
                                                            goto IL_039D;
                                                        }
                                                    }
                                                    else if (num498 <= 460)
{
                                                        if (num498 != 196 && num498 != 460)
{
                                                            goto IL_03AC;
                                                        }
                                                        goto IL_039D;
                                                    }
                                                    else if (num498 - 481 > 2)
{
                                                        if (num498 - 717 > 2)
{
                                                            goto IL_03AC;
                                                        }
                                                        goto IL_039D;
                                                    }
                                                    flag33 = false;
                                                    goto IL_03AC;
                                                    IL_039D:
                                                    if (!WorldGen.SecretSeed.extraLivingTrees.Enabled)
{
                                                        flag33 = false;
                                                    }
                                                }
                                                IL_03AC:;
                                            }
                                        }
                                    }
                                    if (!WorldGen.SecretSeed.extraLivingTrees.Enabled)
{
                                        for (int num499 = 0; num499 < GenVars.numMCaves; num499++)
{
                                            if (num494 > GenVars.mCaveX[num499] - 50 && num494 < GenVars.mCaveX[num499] + 50)
{
                                                flag33 = false;
                                                break;
                                            }
                                        }
                                    }
                                    if (flag33)
{
                                        flag32 = WorldGen.GrowLivingTree(num494, num495, false);
                                        if (flag32)
{
                                            for (int num500 = -1; num500 <= 1; num500++)
{
                                                if (num500 != 0)
{
                                                    int num501 = num494;
                                                    int num502 = WorldGen.genRand.Next(4);
                                                    if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
{
                                                        num502 += WorldGen.genRand.Next(5, 11);
                                                    }
                                                    else if (WorldGen.notTheBees && WorldGen.tenthAnniversaryWorldGen && !WorldGen.drunkWorldGen)
{
                                                        num502 += WorldGen.genRand.Next(3, 7);
                                                    }
                                                    else if (WorldGen.drunkWorldGen || Main.tenthAnniversaryWorld)
{
                                                        num502 += WorldGen.genRand.Next(2, 5);
                                                    }
                                                    else if (WorldGen.remixWorldGen)
{
                                                        num502 += WorldGen.genRand.Next(1, 6);
                                                    }
                                                    else if (WorldGen.SecretSeed.errorWorld.Enabled)
{
                                                        num502 += WorldGen.genRand.Next(1, 4);
                                                    }
                                                    for (int num503 = 0; num503 < num502; num503++)
{
                                                        num501 += WorldGen.genRand.Next(13, 31) * num500;
                                                        if (num501 <= Main.maxTilesX / 2 - num488 || num501 >= Main.maxTilesX / 2 + num488)
{
                                                            int num504 = num495;
                                                            if (WorldGen.SecretSeed.noSurface.Enabled)
{
                                                                num504 += WorldGen.genRand.Next(-10, 11);
                                                            }
                                                            else if (Main.tile[num501, num504].active())
{
                                                                while (num504 > 0)
{
                                                                    if (!Main.tile[num501, num504].active())
{
                                                                        break;
                                                                    }
                                                                    num504--;
                                                                }
                                                            }
                                                            else
{
                                                                while (num504 < Main.maxTilesY - 1 && !Main.tile[num501, num504].active())
{
                                                                    num504++;
                                                                }
                                                                num504--;
                                                            }
                                                            flag33 = true;
                                                            if (!WorldGen.SecretSeed.errorWorld.Enabled)
{
                                                                for (int num505 = num494 - 50; num505 < num494 + 50; num505++)
{
                                                                    for (int num506 = num495 - 50; num506 < num495 + 50; num506++)
{
                                                                        if (Main.tile[num505, num506].active())
{
                                                                            ushort num498 = Main.tile[num505, num506].type;
                                                                            if (num498 <= 189)
{
                                                                                if (num498 != 41 && num498 - 43 > 1)
{
                                                                                    if (num498 != 189)
{
                                                                                        goto IL_0677;
                                                                                    }
                                                                                    goto IL_0668;
                                                                                }
                                                                            }
                                                                            else if (num498 <= 460)
{
                                                                                if (num498 != 196 && num498 != 460)
{
                                                                                    goto IL_0677;
                                                                                }
                                                                                goto IL_0668;
                                                                            }
                                                                            else if (num498 - 481 > 2)
{
                                                                                if (num498 - 717 > 2)
{
                                                                                    goto IL_0677;
                                                                                }
                                                                                goto IL_0668;
                                                                            }
                                                                            flag33 = false;
                                                                            goto IL_0677;
                                                                            IL_0668:
                                                                            if (!WorldGen.SecretSeed.extraLivingTrees.Enabled)
{
                                                                                flag33 = false;
                                                                            }
                                                                        }
                                                                        IL_0677:;
                                                                    }
                                                                }
                                                            }
                                                            if (flag33)
{
                                                                WorldGen.GrowLivingTree(num501, num504, true);
                                                            }
                                                        }
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                Main.tileSolid[192] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.LivingTreeWalls, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.LivingTrees");
                progress.Set(0.5);
                for (int num507 = 25; num507 < Main.maxTilesX - 25; num507++)
                {
                    progress.Set((double)((float)(num507 - 25) / (float)(Main.maxTilesX - 50)), 0.5, 1.0);
                    int num508 = 25;
                    while ((double)num508 < Main.worldSurface)
                    {
                        if (Main.tile[num507, num508].type == 191 || Main.tile[num507, num508 - 1].type == 191 || Main.tile[num507 - 1, num508].type == 191 || Main.tile[num507 + 1, num508].type == 191 || Main.tile[num507, num508 + 1].type == 191)
{
                            bool flag34 = true;
                            for (int num509 = num507 - 1; num509 <= num507 + 1; num509++)
{
                                for (int num510 = num508 - 1; num510 <= num508 + 1; num510++)
{
                                    if (num509 != num507 && num510 != num508 && (!Main.tile[num509, num510].active() || Main.tile[num509, num510].type != 191) && Main.tile[num509, num510].wall != 244)
{
                                        flag34 = false;
                                    }
                                }
                            }
                            if (flag34)
{
                                Main.tile[num507, num508].wall = 244;
                            }
                        }
                        num508++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DemonAndCrimsonAltars, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                Main.tileSolid[484] = false;
                progress.Message = Lang.gen[26].Value;
                int num511 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 3.3E-06);
                if (WorldGen.remixWorldGen)
                {
                    num511 *= 3;
                }
                if (WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    num511 /= 2;
                }
                for (int num512 = 0; num512 < num511; num512++)
                {
                    progress.Set((double)((float)num512 / (float)num511));
                    for (int num513 = 0; num513 < 10000; num513++)
                    {
                        int num514 = WorldGen.genRand.Next(281, Main.maxTilesX - 3 - 280);
                        while ((double)num514 > (double)Main.maxTilesX * 0.45 && (double)num514 < (double)Main.maxTilesX * 0.55)
{
                            num514 = WorldGen.genRand.Next(281, Main.maxTilesX - 3 - 280);
                        }
                        int num515 = WorldGen.genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, (int)(Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3);
                        if (WorldGen.remixWorldGen)
{
                            num515 = WorldGen.genRand.Next(100, (int)((double)Main.maxTilesY * 0.9));
                        }
                        while (WorldGen.oceanDepths(num514, num515) || Vector2D.Distance(new Vector2D((double)num514, (double)num515), GenVars.shimmerPosition) < (double)WorldGen.shimmerSafetyDistance || (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num514, num515, 0, true)))
{
                            num514 = WorldGen.genRand.Next(281, Main.maxTilesX - 3 - 280);
                            while ((double)num514 > (double)Main.maxTilesX * 0.45 && (double)num514 < (double)Main.maxTilesX * 0.55)
{
                                num514 = WorldGen.genRand.Next(281, Main.maxTilesX - 3 - 280);
                            }
                            num515 = WorldGen.genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, (int)(Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3);
                            if (WorldGen.remixWorldGen)
{
                                num515 = WorldGen.genRand.Next(100, (int)((double)Main.maxTilesY * 0.9));
                            }
                        }
                        int num516 = (WorldGen.crimson ? 1 : 0);
                        if (WorldGen.drunkWorldGen)
{
                            if (GenVars.crimsonLeft)
{
                                if (num514 < Main.maxTilesX / 2)
{
                                    num516 = 1;
                                }
                                else
{
                                    num516 = 0;
                                }
                            }
                            else if (num514 < Main.maxTilesX / 2)
{
                                num516 = 0;
                            }
                            else
{
                                num516 = 1;
                            }
                        }
                        if (!WorldGen.IsTileNearby(num514, num515, 26, 3))
{
                            WorldGen.Place3x2(num514, num515, 26, num516);
                        }
                        if (Main.tile[num514, num515].type == 26)
{
                            break;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SurfaceWaterInJungle, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num517 = 0; num517 < Main.maxTilesX; num517++)
                {
                    int num518 = (int)GenVars.worldSurfaceLow;
                    while ((double)num518 < Main.worldSurface - 1.0)
                    {
                        if (Main.tile[num517, num518].active())
{
                            if (Main.tile[num517, num518].type == 60)
{
                                Main.tile[num517, num518 - 1].liquidType(0);
                                Main.tile[num517, num518 - 1].liquid = byte.MaxValue;
                                Main.tile[num517, num518 - 2].liquidType(0);
                                Main.tile[num517, num518 - 2].liquid = byte.MaxValue;
                                break;
                            }
                            break;
                        }
                        else
{
                            num518++;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.LihzahrdTemple, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                int num519 = 0;
                progress.Message = Lang.gen[70].Value;
                long num520 = 0L;
                double num521 = 0.25;
                bool flag35 = false;
                int num524;
                int num525;
                for (;;)
                {
                    int num522 = (int)Main.rockLayer;
                    int num523 = Main.maxTilesY - 600;
                    if (num522 > num523 - 1)
                    {
                        num522 = num523 - 1;
                    }
                    num524 = WorldGen.genRand.Next(num522, num523);
                    num525 = (int)(((WorldGen.genRand.NextDouble() * num521 + 0.1) * (double)(-(double)GenVars.CurrentDungeonGenVars.dungeonSide) + 0.5) * (double)Main.maxTilesX);
                    if (WorldGen.remixWorldGen && !WorldGen.SecretSeed.noSurface.Enabled)
                    {
                        if (WorldGen.notTheBees)
{
                            if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
{
                                num525 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.4));
                            }
                            else
{
                                num525 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.6), (int)((double)Main.maxTilesX * 0.8));
                            }
                        }
                        else
{
                            num525 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                            while ((double)num525 > (double)Main.maxTilesX * 0.4)
{
                                if ((double)num525 >= (double)Main.maxTilesX * 0.6)
{
                                    break;
                                }
                                num525 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                            }
                        }
                        while (Main.tile[num525, num524].active() || Main.tile[num525, num524].wall > 0 || (double)num524 > Main.worldSurface - 5.0)
{
                            num524--;
                        }
                        num524++;
                        if (Main.tile[num525, num524].active() && (Main.tile[num525, num524].type == 60 || Main.tile[num525, num524].type == 59))
{
                            int num526 = 10;
                            bool flag36 = false;
                            for (int num527 = num525 - num526; num527 <= num527 + num526; num527++)
{
                                for (int num528 = num524 - num526; num528 < num526; num528++)
{
                                    if (Main.tile[num527, num528].type == 191 || Main.tileDungeon[(int)Main.tile[num527, num528].type])
{
                                        flag36 = true;
                                    }
                                }
                            }
                            if (!flag36)
{
                                break;
                            }
                        }
                    }
                    else if (Main.tile[num525, num524].active() && Main.tile[num525, num524].type == 60)
                    {
                        goto Block_19;
                    }
                    long num529 = num520;
                    num520 = num529 + 1L;
                    if (num529 > 1000000L)
                    {
                        if (num521 == 0.35)
{
                            num519++;
                            if (num519 > 10)
{
                                goto IL_0362;
                            }
                        }
                        num521 = Math.Min(0.35, num521 + 0.05);
                        num520 = 0L;
                    }
                }
                flag35 = true;
                num524 -= 10 + WorldGen.genRand.Next(10);
                WorldGen.makeTemple(num525, num524, progress);
                goto IL_0362;
                Block_19:
                flag35 = true;
                WorldGen.makeTemple(num525, num524, progress);
                IL_0362:
                if (!flag35)
                {
                    int num530 = Main.maxTilesX - GenVars.CurrentDungeonGenVars.generatingDungeonPositionX;
                    int num531 = (int)Main.rockLayer + 100;
                    if (WorldGen.remixWorldGen)
                    {
                        if (WorldGen.notTheBees)
{
                            num530 = ((GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right) ? ((int)((double)Main.maxTilesX * 0.3)) : ((int)((double)Main.maxTilesX * 0.7)));
                        }
                        else
{
                            num530 = ((GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right) ? ((int)((double)Main.maxTilesX * 0.3)) : ((int)((double)Main.maxTilesX * 0.7)));
                        }
                        if (Main.worldSurface < 150.0)
{
                            num531 = WorldGen.genRand.Next(200, (int)Main.rockLayer);
                        }
                        else
{
                            num531 = (int)Main.worldSurface - 100;
                        }
                    }
                    WorldGen.makeTemple(num530, num531, progress);
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Beehives, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[71].Value;
                double num532 = (double)Main.maxTilesX / 4200.0;
                double num533 = (double)(1 + WorldGen.genRand.Next((int)(5.0 * num532), (int)(8.0 * num532)));
                if (WorldGen.drunkWorldGen)
                {
                    num533 *= 0.667;
                }
                int num534 = 10000;
                HiveBiome hiveBiome = GenVars.configuration.CreateBiome<HiveBiome>();
                HoneyPatchBiome honeyPatchBiome = GenVars.configuration.CreateBiome<HoneyPatchBiome>();
                double num535 = num533;
                while (num533 > 0.0 && num534 > 0)
                {
                    if (progress != null)
                    {
                        float num536 = 1f - (float)num533 / (float)num535;
                        progress.Set((double)num536);
                    }
                    num534--;
                    Point point4 = WorldGen.RandomWorldPoint((int)(Main.worldSurface + Main.rockLayer) >> 1, 20, 300, 20);
                    if (WorldGen.drunkWorldGen)
                    {
                        WorldGen.RandomWorldPoint((int)Main.worldSurface, 20, 300, 20);
                    }
                    if (hiveBiome.Place(point4, GenVars.structures))
                    {
                        num533 -= 1.0;
                        int num537 = WorldGen.genRand.Next(5);
                        if (WorldGen.SecretSeed.extraLiquid.Enabled)
{
                            num537 = 0;
                        }
                        int num538 = 0;
                        int num539 = 10000;
                        while (num538 < num537 && num539 > 0)
{
                            double num540 = WorldGen.genRand.NextDouble() * 60.0 + 30.0;
                            double num541 = WorldGen.genRand.NextDouble() * 6.2831854820251465;
                            int num542 = (int)(Math.Cos(num541) * num540) + point4.X;
                            int num543 = (int)(Math.Sin(num541) * num540) + point4.Y;
                            num539--;
                            if (num542 > 50 && num542 < Main.maxTilesX - 50 && honeyPatchBiome.Place(new Point(num542, num543), GenVars.structures))
{
                                num538++;
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.JungleShrines, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                int num544 = WorldGen.genRand.Next(40, Main.maxTilesX - 40);
                int num545 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 400);
                double num546 = (double)WorldGen.genRand.Next(7, 12);
                num546 *= (double)Main.maxTilesX / 4200.0;
                int num547 = 0;
                int num548 = 0;
                while ((double)num548 < num546)
                {
                    bool flag37 = true;
                    while (flag37)
                    {
                        num547++;
                        num544 = WorldGen.genRand.Next(40, Main.maxTilesX / 2 - 40);
                        if (GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left)
{
                            num544 += Main.maxTilesX / 2;
                        }
                        num545 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 400);
                        int num549 = WorldGen.genRand.Next(2, 4);
                        int num550 = WorldGen.genRand.Next(2, 4);
                        Rectangle rectangle = new Rectangle(num544 - num549 - 1, num545 - num550 - 1, num549 + 1, num550 + 1);
                        if (Main.tile[num544, num545].active() && Main.tile[num544, num545].type == 60)
{
                            int num551 = 30;
                            flag37 = false;
                            for (int num552 = num544 - num551; num552 < num544 + num551; num552 += 3)
{
                                for (int num553 = num545 - num551; num553 < num545 + num551; num553 += 3)
{
                                    if (Main.tile[num552, num553].active() && (Main.tile[num552, num553].type == 225 || Main.tile[num552, num553].type == 229 || Main.tile[num552, num553].type == 226 || Main.tile[num552, num553].type == 119 || Main.tile[num552, num553].type == 120))
{
                                        flag37 = true;
                                    }
                                    if (Main.tile[num552, num553].wall == 86 || Main.tile[num552, num553].wall == 87)
{
                                        flag37 = true;
                                    }
                                }
                            }
                            if (!GenVars.structures.CanPlace(rectangle, 1))
{
                                flag37 = true;
                            }
                        }
                        if (!flag37)
{
                            ushort num554 = 0;
                            if (GenVars.jungleHut == 119)
{
                                num554 = 23;
                            }
                            else if (GenVars.jungleHut == 120)
{
                                num554 = 24;
                            }
                            else if (GenVars.jungleHut == 158)
{
                                num554 = 42;
                            }
                            else if (GenVars.jungleHut == 175)
{
                                num554 = 45;
                            }
                            else if (GenVars.jungleHut == 45)
{
                                num554 = 10;
                            }
                            for (int num555 = num544 - num549 - 1; num555 <= num544 + num549 + 1; num555++)
{
                                for (int num556 = num545 - num550 - 1; num556 <= num545 + num550 + 1; num556++)
{
                                    Main.tile[num555, num556].active(true);
                                    Main.tile[num555, num556].type = GenVars.jungleHut;
                                    Main.tile[num555, num556].liquid = 0;
                                    Main.tile[num555, num556].lava(false);
                                }
                            }
                            for (int num557 = num544 - num549; num557 <= num544 + num549; num557++)
{
                                for (int num558 = num545 - num550; num558 <= num545 + num550; num558++)
{
                                    Main.tile[num557, num558].active(false);
                                    Main.tile[num557, num558].wall = num554;
                                }
                            }
                            bool flag38 = false;
                            int num559 = 0;
                            while (!flag38 && num559 < 100)
{
                                num559++;
                                int num560 = WorldGen.genRand.Next(num544 - num549, num544 + num549 + 1);
                                int num561 = WorldGen.genRand.Next(num545 - num550, num545 + num550 - 2);
                                WorldGen.PlaceTile(num560, num561, 4, true, false, -1, 3);
                                if (Main.tile[num560, num561].active() && Main.tile[num560, num561].type == 4)
{
                                    flag38 = true;
                                }
                            }
                            for (int num562 = num544 - num549 - 1; num562 <= num544 + num549 + 1; num562++)
{
                                for (int num563 = num545 + num550 - 2; num563 <= num545 + num550; num563++)
{
                                    Main.tile[num562, num563].active(false);
                                }
                            }
                            for (int num564 = num544 - num549 - 1; num564 <= num544 + num549 + 1; num564++)
{
                                for (int num565 = num545 + num550 - 2; num565 <= num545 + num550 - 1; num565++)
{
                                    Main.tile[num564, num565].active(false);
                                }
                            }
                            for (int num566 = num544 - num549 - 1; num566 <= num544 + num549 + 1; num566++)
{
                                int num567 = 4;
                                int num568 = num545 + num550 + 2;
                                while (!Main.tile[num566, num568].active() && num568 < Main.maxTilesY && num567 > 0)
{
                                    Main.tile[num566, num568].active(true);
                                    Main.tile[num566, num568].type = 59;
                                    num568++;
                                    num567--;
                                }
                            }
                            num549 -= WorldGen.genRand.Next(1, 3);
                            int num569 = num545 - num550 - 2;
                            while (num549 > -1)
{
                                for (int num570 = num544 - num549 - 1; num570 <= num544 + num549 + 1; num570++)
{
                                    Main.tile[num570, num569].active(true);
                                    Main.tile[num570, num569].type = GenVars.jungleHut;
                                }
                                num549 -= WorldGen.genRand.Next(1, 3);
                                num569--;
                            }
                            GenVars.JChestX[GenVars.numJChests] = num544;
                            GenVars.JChestY[GenVars.numJChests] = num545;
                            GenVars.structures.AddProtectedStructure(rectangle, 0);
                            GenVars.numJChests++;
                            num547 = 0;
                        }
                        else if (num547 > Main.maxTilesX * 10)
{
                            num548++;
                            num547 = 0;
                            break;
                        }
                    }
                    num548++;
                }
                Main.tileSolid[137] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.SettleLiquids, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[27].Value;
                for (int num571 = 0; num571 < Main.maxTilesX; num571++)
                {
                    for (int num572 = 0; num572 < Main.maxTilesY; num572++)
                    {
                        if (WorldGen.oceanDepths(num571, num572) && Main.tile[num571, num572].liquid > 0 && Main.tile[num571, num572].liquidType() != 0)
{
                            Main.tile[num571, num572].liquidType(0);
                        }
                    }
                }
                if (WorldGen.SecretSeed.extraLiquid.Enabled)
                {
                    progress.Message = Language.GetTextValue("WorldGeneration.WaterFeatures");
                    WorldGen.SecretSeed.DoExtraLiquidAddLiquid();
                }
                if (WorldGen.notTheBees)
                {
                    WorldGen.NotTheBees();
                }
                Liquid.worldGenTilesIgnoreWater(true);
                Liquid.QuickWater(3, -1, -1);
                WorldGen.WaterCheck();
                int num573 = 0;
                Liquid.quickSettle = true;
                int num574 = 10;
                while (num573 < num574)
                {
                    int num575 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    num573++;
                    double num576 = 0.0;
                    int num577 = num575 * 5;
                    while (Liquid.numLiquid > 0)
                    {
                        num577--;
                        if (num577 < 0)
{
                            if (WorldGen.SecretSeed.extraLiquid.Enabled)
{
                                num573 += num574 / 5;
                                break;
                            }
                            break;
                        }
                        else
{
                            double num578 = (double)(num575 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (double)num575;
                            if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num575)
{
                                num575 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                            }
                            if (num578 > num576)
{
                                num576 = num578;
                            }
                            else
{
                                num578 = num576;
                            }
                            if (num573 == 1)
{
                                progress.Set(num578 / 3.0 + 0.33);
                            }
                            int num579 = 10;
                            if (num573 > num579)
{
                            }
                            Liquid.UpdateLiquid();
                        }
                    }
                    WorldGen.WaterCheck();
                    progress.Set((double)num573 * 0.1 / 3.0 + 0.66);
                }
                WorldGen.ClearPendingLiquid();
                Liquid.quickSettle = false;
                Liquid.worldGenTilesIgnoreWater(false);
                Main.tileSolid[484] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.RemoveSurfaceWaterAboveSand, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.extraLiquid.Enabled)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num580 = 400; num580 < Main.maxTilesX - 400; num580++)
                {
                    int num581 = 100;
                    while ((double)num581 < Main.worldSurface - 1.0)
                    {
                        if (Main.tile[num580, num581].active())
{
                            ushort type6 = Main.tile[num580, num581].type;
                            if (type6 == 53 || type6 == 396 || type6 == 397 || type6 == 404 || type6 == 407 || type6 == 151)
{
                                int num582 = num581;
                                while (num582 > 100)
{
                                    num582--;
                                    if (Main.tile[num580, num582].active())
{
                                        break;
                                    }
                                    Main.tile[num580, num582].liquid = 0;
                                }
                                break;
                            }
                            break;
                        }
                        else
{
                            num581++;
                        }
                    }
                }
                Main.tileSolid[192] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.Oasis, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.roundLandmasses.Enabled)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                if (WorldGen.notTheBees && !WorldGen.dontStarveWorldGen)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.Oasis");
                progress.Set(0.0);
                int num583 = Main.maxTilesX / 2100;
                num583 += WorldGen.genRand.Next(2);
                for (int num584 = 0; num584 < num583; num584++)
                {
                    progress.Set((double)((float)num584 / (float)num583));
                    int num585 = WorldGen.beachDistance + 300;
                    int num586 = Main.maxTilesX * 2;
                    while (num586 > 0)
                    {
                        num586--;
                        int num587 = WorldGen.genRand.Next(num585, Main.maxTilesX - num585);
                        int num588 = WorldGen.genRand.Next(100, (int)Main.worldSurface);
                        if (WorldGen.PlaceOasis(num587, num588))
{
                            num586 = -1;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.ShellPilesMarblePilesAndSpikePits, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Set(0.0);
                if (WorldGen.dontStarveWorldGen)
                {
                    progress.Message = Language.GetTextValue("WorldGeneration.MarblePiles");
                    progress.Set(0.0);
                    int num589 = (int)(5.0 * ((double)Main.maxTilesX / 4200.0));
                    int num590 = 0;
                    int num591 = 100;
                    int num592 = Main.maxTilesX / 2;
                    int num593 = num592 - num591;
                    int num594 = num592 + num591;
                    int num595 = 0;
                    while (num595 < 80)
                    {
                        int num596 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                        if (num596 < num593 || num596 > num594)
{
                            goto IL_00C4;
                        }
                        num596 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                        if (num596 < num593 || num596 > num594)
{
                            goto IL_00C4;
                        }
                        IL_00ED:
                        num595++;
                        continue;
                        IL_00C4:
                        int num597 = (int)Main.worldSurface / 2;
                        if (!WorldGen.MarblePileWithStatues(num596, num597))
{
                            goto IL_00ED;
                        }
                        num590++;
                        progress.Set((double)((float)num590 / (float)num589));
                        if (num590 < num589)
{
                            goto IL_00ED;
                        }
                        break;
                    }
                }
                if (GenVars.noTrapsAndForTheWorthyNoCelebration)
                {
                    WorldGen.AddSpikeCaves(progress);
                }
                if (WorldGen.notTheBees)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.ShellPiles");
                progress.Set(0.0);
                if (WorldGen.genRand.Next(2) == 0)
                {
                    progress.Set(0.33000001311302185);
                    int shellStartXLeft = GenVars.shellStartXLeft;
                    int shellStartYLeft = GenVars.shellStartYLeft;
                    for (int num598 = shellStartXLeft - 20; num598 <= shellStartXLeft + 20; num598++)
                    {
                        for (int num599 = shellStartYLeft - 10; num599 <= shellStartYLeft + 10; num599++)
{
                            if (Main.tile[num598, num599].active() && Main.tile[num598, num599].type == 53 && !Main.tile[num598, num599 - 1].active() && Main.tile[num598, num599 - 1].liquid == 0 && !Main.tile[num598 - 1, num599].active() && Main.tile[num598 - 1, num599].liquid > 0)
{
                                GenVars.shellStartXLeft = num598;
                                GenVars.shellStartYLeft = num599;
                            }
                        }
                    }
                    GenVars.shellStartYLeft -= 50;
                    GenVars.shellStartXLeft -= WorldGen.genRand.Next(5);
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        GenVars.shellStartXLeft -= WorldGen.genRand.Next(10);
                    }
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        GenVars.shellStartXLeft -= WorldGen.genRand.Next(15);
                    }
                    if (WorldGen.genRand.Next(4) != 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXLeft, GenVars.shellStartYLeft);
                    }
                    int num600 = WorldGen.genRand.Next(2, 4);
                    if (WorldGen.genRand.Next(num600) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXLeft - WorldGen.genRand.Next(10, 35), GenVars.shellStartYLeft);
                    }
                    if (WorldGen.genRand.Next(num600) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXLeft - WorldGen.genRand.Next(40, 65), GenVars.shellStartYLeft);
                    }
                    if (WorldGen.genRand.Next(num600) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXLeft - WorldGen.genRand.Next(70, 95), GenVars.shellStartYLeft);
                    }
                    if (WorldGen.genRand.Next(num600) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXLeft - WorldGen.genRand.Next(100, 125), GenVars.shellStartYLeft);
                    }
                    if (WorldGen.genRand.Next(num600) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXLeft + WorldGen.genRand.Next(10, 25), GenVars.shellStartYLeft);
                    }
                }
                if (WorldGen.genRand.Next(2) == 0)
                {
                    progress.Set(0.6600000262260437);
                    int shellStartXRight = GenVars.shellStartXRight;
                    int shellStartYRight = GenVars.shellStartYRight;
                    for (int num601 = shellStartXRight - 20; num601 <= shellStartXRight + 20; num601++)
                    {
                        for (int num602 = shellStartYRight - 10; num602 <= shellStartYRight + 10; num602++)
{
                            if (Main.tile[num601, num602].active() && Main.tile[num601, num602].type == 53 && !Main.tile[num601, num602 - 1].active() && Main.tile[num601, num602 - 1].liquid == 0 && !Main.tile[num601 + 1, num602].active() && Main.tile[num601 + 1, num602].liquid > 0)
{
                                GenVars.shellStartXRight = num601;
                                GenVars.shellStartYRight = num602;
                            }
                        }
                    }
                    GenVars.shellStartYRight -= 50;
                    GenVars.shellStartXRight += WorldGen.genRand.Next(5);
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        GenVars.shellStartXLeft += WorldGen.genRand.Next(10);
                    }
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        GenVars.shellStartXLeft += WorldGen.genRand.Next(15);
                    }
                    if (WorldGen.genRand.Next(4) != 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXRight, GenVars.shellStartYRight);
                    }
                    int num603 = WorldGen.genRand.Next(2, 4);
                    if (WorldGen.genRand.Next(num603) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXRight + WorldGen.genRand.Next(10, 35), GenVars.shellStartYRight);
                    }
                    if (WorldGen.genRand.Next(num603) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXRight + WorldGen.genRand.Next(40, 65), GenVars.shellStartYRight);
                    }
                    if (WorldGen.genRand.Next(num603) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXRight + WorldGen.genRand.Next(70, 95), GenVars.shellStartYRight);
                    }
                    if (WorldGen.genRand.Next(num603) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXRight + WorldGen.genRand.Next(100, 125), GenVars.shellStartYRight);
                    }
                    if (WorldGen.genRand.Next(num603) == 0)
                    {
                        WorldGen.ShellPile(GenVars.shellStartXRight - WorldGen.genRand.Next(10, 25), GenVars.shellStartYRight);
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.SmoothWorld, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                progress.Message = Lang.gen[60].Value;
                WorldGen.SetCrackedBrickSolidity(true);
                for (int num604 = 20; num604 < Main.maxTilesX - 20; num604++)
                {
                    progress.Set((double)num604 / (double)Main.maxTilesX, 0.0, 0.5);
                    for (int num605 = 20; num605 < Main.maxTilesY - 20; num605++)
                    {
                        if ((!Main.tile[num604, num605].active() || !TileID.Sets.PreventsSlopesDuringGeneration[(int)Main.tile[num604, num605].type]) && (!Main.tile[num604, num605 - 1].active() || !TileID.Sets.PreventsSlopesDuringGeneration[(int)Main.tile[num604, num605 - 1].type]))
{
                            if (!Main.tile[num604, num605 - 1].active() && (!Main.tile[num604 - 1, num605].active() || Main.tile[num604 - 1, num605].type != 136) && (!Main.tile[num604 + 1, num605].active() || Main.tile[num604 + 1, num605].type != 136))
{
                                if (WorldGen.SolidTile(num604, num605, false) && TileID.Sets.CanBeClearedDuringGeneration[(int)Main.tile[num604, num605].type])
{
                                    if ((!Main.tile[num604 - 1, num605].active() || Main.tile[num604 - 1, num605].blockType() == 0) && (!Main.tile[num604 + 1, num605].active() || Main.tile[num604 + 1, num605].blockType() == 0))
{
                                        if (WorldGen.SolidTile(num604, num605 + 1, false))
{
                                            if (!WorldGen.SolidTile(num604 - 1, num605, false) && !Main.tile[num604 - 1, num605 + 1].halfBrick() && WorldGen.SolidTile(num604 - 1, num605 + 1, false) && WorldGen.SolidTile(num604 + 1, num605, false) && !Main.tile[num604 + 1, num605 - 1].active())
{
                                                if (WorldGen.genRand.Next(2) == 0)
{
                                                    WorldGen.SlopeTile(num604, num605, 2, false, true);
                                                }
                                                else
{
                                                    WorldGen.PoundTile(num604, num605);
                                                }
                                            }
                                            else if (!WorldGen.SolidTile(num604 + 1, num605, false) && !Main.tile[num604 + 1, num605 + 1].halfBrick() && WorldGen.SolidTile(num604 + 1, num605 + 1, false) && WorldGen.SolidTile(num604 - 1, num605, false) && !Main.tile[num604 - 1, num605 - 1].active())
{
                                                if (WorldGen.genRand.Next(2) == 0)
{
                                                    WorldGen.SlopeTile(num604, num605, 1, false, true);
                                                }
                                                else
{
                                                    WorldGen.PoundTile(num604, num605);
                                                }
                                            }
                                            else if (WorldGen.SolidTile(num604 + 1, num605 + 1, false) && WorldGen.SolidTile(num604 - 1, num605 + 1, false) && !Main.tile[num604 + 1, num605].active() && !Main.tile[num604 - 1, num605].active())
{
                                                WorldGen.PoundTile(num604, num605);
                                            }
                                            if (WorldGen.SolidTile(num604, num605, false))
{
                                                if (WorldGen.SolidTile(num604 - 1, num605, false) && WorldGen.SolidTile(num604 + 1, num605 + 2, false) && !Main.tile[num604 + 1, num605].active() && !Main.tile[num604 + 1, num605 + 1].active() && !Main.tile[num604 - 1, num605 - 1].active())
{
                                                    WorldGen.KillTile(num604, num605, false, false, false);
                                                }
                                                else if (WorldGen.SolidTile(num604 + 1, num605, false) && WorldGen.SolidTile(num604 - 1, num605 + 2, false) && !Main.tile[num604 - 1, num605].active() && !Main.tile[num604 - 1, num605 + 1].active() && !Main.tile[num604 + 1, num605 - 1].active())
{
                                                    WorldGen.KillTile(num604, num605, false, false, false);
                                                }
                                                else if (!Main.tile[num604 - 1, num605 + 1].active() && !Main.tile[num604 - 1, num605].active() && WorldGen.SolidTile(num604 + 1, num605, false) && WorldGen.SolidTile(num604, num605 + 2, false))
{
                                                    if (WorldGen.genRand.Next(5) == 0)
{
                                                        WorldGen.KillTile(num604, num605, false, false, false);
                                                    }
                                                    else if (WorldGen.genRand.Next(5) == 0)
{
                                                        WorldGen.PoundTile(num604, num605);
                                                    }
                                                    else
{
                                                        WorldGen.SlopeTile(num604, num605, 2, false, true);
                                                    }
                                                }
                                                else if (!Main.tile[num604 + 1, num605 + 1].active() && !Main.tile[num604 + 1, num605].active() && WorldGen.SolidTile(num604 - 1, num605, false) && WorldGen.SolidTile(num604, num605 + 2, false))
{
                                                    if (WorldGen.genRand.Next(5) == 0)
{
                                                        WorldGen.KillTile(num604, num605, false, false, false);
                                                    }
                                                    else if (WorldGen.genRand.Next(5) == 0)
{
                                                        WorldGen.PoundTile(num604, num605);
                                                    }
                                                    else
{
                                                        WorldGen.SlopeTile(num604, num605, 1, false, true);
                                                    }
                                                }
                                            }
                                        }
                                        if (WorldGen.SolidTile(num604, num605, false) && !Main.tile[num604 - 1, num605].active() && !Main.tile[num604 + 1, num605].active())
{
                                            WorldGen.KillTile(num604, num605, false, false, false);
                                        }
                                    }
                                }
                                else if (!Main.tile[num604, num605].active() && WorldGen.SolidTile(num604, num605 + 1, false) && Main.tile[num604, num605 + 1].type != 151 && Main.tile[num604, num605 + 1].type != 274)
{
                                    if (Main.tile[num604 + 1, num605].type != 190 && Main.tile[num604 + 1, num605].type != 48 && Main.tile[num604 + 1, num605].type != 232 && WorldGen.SolidTile(num604 - 1, num605 + 1, false) && WorldGen.SolidTile(num604 + 1, num605, false) && !Main.tile[num604 - 1, num605].active() && !Main.tile[num604 + 1, num605 - 1].active())
{
                                        if (Main.tile[num604 + 1, num605].type == 495)
{
                                            WorldGen.PlaceTile(num604, num605, (int)Main.tile[num604 + 1, num605].type, false, false, -1, 0);
                                        }
                                        else
{
                                            WorldGen.PlaceTile(num604, num605, (int)Main.tile[num604, num605 + 1].type, false, false, -1, 0);
                                        }
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            WorldGen.SlopeTile(num604, num605, 2, false, true);
                                        }
                                        else
{
                                            WorldGen.PoundTile(num604, num605);
                                        }
                                    }
                                    if (Main.tile[num604 - 1, num605].type != 190 && Main.tile[num604 - 1, num605].type != 48 && Main.tile[num604 - 1, num605].type != 232 && WorldGen.SolidTile(num604 + 1, num605 + 1, false) && WorldGen.SolidTile(num604 - 1, num605, false) && !Main.tile[num604 + 1, num605].active() && !Main.tile[num604 - 1, num605 - 1].active())
{
                                        if (Main.tile[num604 - 1, num605].type == 495)
{
                                            WorldGen.PlaceTile(num604, num605, (int)Main.tile[num604 - 1, num605].type, false, false, -1, 0);
                                        }
                                        else
{
                                            WorldGen.PlaceTile(num604, num605, (int)Main.tile[num604, num605 + 1].type, false, false, -1, 0);
                                        }
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            WorldGen.SlopeTile(num604, num605, 1, false, true);
                                        }
                                        else
{
                                            WorldGen.PoundTile(num604, num605);
                                        }
                                    }
                                }
                            }
                            else if (!Main.tile[num604, num605 + 1].active() && WorldGen.genRand.Next(2) == 0 && WorldGen.SolidTile(num604, num605, false) && WorldGen.SolidTile(num604, num605 - 1, false) && (!Main.tile[num604 + 1, num605].active() || Main.tile[num604 + 1, num605].blockType() == 0) && (!Main.tile[num604 - 1, num605].active() || Main.tile[num604 - 1, num605].blockType() == 0))
{
                                if (WorldGen.SolidTile(num604 - 1, num605, false) && !WorldGen.SolidTile(num604 + 1, num605, false) && WorldGen.SolidTile(num604 - 1, num605 - 1, false))
{
                                    WorldGen.SlopeTile(num604, num605, 3, false, true);
                                }
                                else if (WorldGen.SolidTile(num604 + 1, num605, false) && !WorldGen.SolidTile(num604 - 1, num605, false) && WorldGen.SolidTile(num604 + 1, num605 - 1, false))
{
                                    WorldGen.SlopeTile(num604, num605, 4, false, true);
                                }
                            }
                        }
                    }
                }
                for (int num606 = 20; num606 < Main.maxTilesX - 20; num606++)
                {
                    progress.Set((double)num606 / (double)Main.maxTilesX, 0.5, 1.0);
                    for (int num607 = 20; num607 < Main.maxTilesY - 20; num607++)
                    {
                        if (WorldGen.genRand.Next(2) == 0 && !Main.tile[num606, num607 - 1].active() && Main.tile[num606, num607].type != 137 && Main.tile[num606, num607].type != 48 && Main.tile[num606, num607].type != 232 && Main.tile[num606, num607].type != 191 && Main.tile[num606, num607].type != 151 && Main.tile[num606, num607].type != 274 && Main.tile[num606, num607].type != 75 && Main.tile[num606, num607].type != 76 && WorldGen.SolidTile(num606, num607, false) && (!Main.tile[num606 - 1, num607].active() || Main.tile[num606 - 1, num607].type != 137) && (Main.tile[num606 + 1, num607].active() || Main.tile[num606 + 1, num607].type != 137))
{
                            if (WorldGen.SolidTile(num606, num607 + 1, false) && WorldGen.SolidTile(num606 + 1, num607, false) && !Main.tile[num606 - 1, num607].active())
{
                                WorldGen.SlopeTile(num606, num607, 2, false, true);
                            }
                            if (WorldGen.SolidTile(num606, num607 + 1, false) && WorldGen.SolidTile(num606 - 1, num607, false) && !Main.tile[num606 + 1, num607].active())
{
                                WorldGen.SlopeTile(num606, num607, 1, false, true);
                            }
                        }
                        if (Main.tile[num606, num607].active() && TileID.Sets.Conversion.Sand[(int)Main.tile[num606, num607].type])
{
                            Tile.SmoothSlope(num606, num607, false, false);
                        }
                        if (Main.tile[num606, num607].slope() == 1 && !WorldGen.SolidTile(num606 - 1, num607, false))
{
                            WorldGen.SlopeTile(num606, num607, 0, false, true);
                            WorldGen.PoundTile(num606, num607);
                        }
                        if (Main.tile[num606, num607].slope() == 2 && !WorldGen.SolidTile(num606 + 1, num607, false))
{
                            WorldGen.SlopeTile(num606, num607, 0, false, true);
                            WorldGen.PoundTile(num606, num607);
                        }
                    }
                }
                if (WorldGen.SecretSeed.addTeleporters.Enabled && WorldGen.Skyblock.denySomeGeneration)
                {
                    WorldGen.SecretSeed.DoAddTeleporters();
                }
                Main.tileSolid[137] = true;
                Main.tileSolid[190] = false;
                Main.tileSolid[192] = false;
                WorldGen.SetCrackedBrickSolidity(false);
            });
            WorldGen.AddGenerationPass(GenPassNameID.Waterfalls, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[69].Value;
                Main.tileSolid[191] = false;
                for (int num608 = 20; num608 < Main.maxTilesX - 20; num608++)
                {
                    double num609 = (double)num608 / (double)Main.maxTilesX;
                    progress.Set(num609 * 0.5);
                    for (int num610 = 20; num610 < Main.maxTilesY - 20; num610++)
                    {
                        if (WorldGen.SolidTile(num608, num610, false) && !Main.tile[num608 - 1, num610].active() && WorldGen.SolidTile(num608, num610 + 1, false) && !Main.tile[num608 + 1, num610].active() && (Main.tile[num608 - 1, num610].liquid > 0 || Main.tile[num608 + 1, num610].liquid > 0))
{
                            bool flag39 = true;
                            int num611 = WorldGen.genRand.Next(8, 20);
                            int num612 = WorldGen.genRand.Next(8, 20);
                            num611 = num610 - num611;
                            num612 += num610;
                            for (int num613 = num611; num613 <= num612; num613++)
{
                                if (Main.tile[num608, num613].active() && Main.tile[num608, num613].halfBrick())
{
                                    flag39 = false;
                                }
                            }
                            if ((Main.tile[num608, num610].type == 75 || Main.tile[num608, num610].type == 76) && WorldGen.genRand.Next(10) != 0)
{
                                flag39 = false;
                            }
                            if (flag39)
{
                                WorldGen.PoundTile(num608, num610);
                            }
                        }
                    }
                }
                for (int num614 = 20; num614 < Main.maxTilesX - 20; num614++)
                {
                    double num615 = (double)num614 / (double)Main.maxTilesX;
                    progress.Set(num615 * 0.5 + 0.5);
                    for (int num616 = 20; num616 < Main.maxTilesY - 20; num616++)
                    {
                        if (Main.tile[num614, num616].type != 48 && Main.tile[num614, num616].type != 232 && WorldGen.SolidTile(num614, num616, false) && WorldGen.SolidTile(num614, num616 + 1, false))
{
                            if (!WorldGen.SolidTile(num614 + 1, num616, false) && Main.tile[num614 - 1, num616].active() && Main.tile[num614 - 1, num616].halfBrick() && Main.tile[num614 - 2, num616].liquid > 0)
{
                                WorldGen.PoundTile(num614, num616);
                            }
                            if (!WorldGen.SolidTile(num614 - 1, num616, false) && Main.tile[num614 + 1, num616].active() && Main.tile[num614 + 1, num616].halfBrick() && Main.tile[num614 + 2, num616].liquid > 0)
{
                                WorldGen.PoundTile(num614, num616);
                            }
                        }
                    }
                }
                Main.tileSolid[191] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.FragileIceOverIceBiomeWater, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                if (WorldGen.notTheBees)
                {
                    WorldGen.NotTheBees();
                }
                int num617 = (int)Main.worldSurface;
                int num618 = Main.maxTilesY - 100;
                if (WorldGen.SecretSeed.worldIsFrozen.Enabled)
                {
                    WorldGen.SecretSeed.DoWorldIsFrozen();
                    num617 = 0;
                }
                progress.Set(1.0);
                for (int num619 = 10; num619 < Main.maxTilesX - 10; num619++)
                {
                    for (int num620 = num617; num620 < num618; num620++)
                    {
                        if (Main.tile[num619, num620].liquid > 0 && (!Main.tile[num619, num620].lava() || WorldGen.remixWorldGen))
{
                            WorldGen.MakeWateryIceThing(num619, num620);
                        }
                    }
                }
                Main.tileSolid[226] = false;
                Main.tileSolid[162] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.CaveWallVariety, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[79].Value;
                double num621 = (double)(Main.maxTilesX * Main.maxTilesY) / 5040000.0;
                int num622 = (int)(300.0 * num621);
                int num623 = num622;
                ShapeData shapeData = new ShapeData();
                int num624 = 100000;
                while (num622 > 0 && num624 > 0)
                {
                    progress.Set(1.0 - (double)num622 / (double)num623);
                    Point point5 = WorldGen.RandomWorldPoint((int)GenVars.worldSurface, 2, 190, 2);
                    while (Vector2D.Distance(new Vector2D((double)point5.X, (double)point5.Y), GenVars.shimmerPosition) < (double)WorldGen.shimmerSafetyDistance)
                    {
                        point5 = WorldGen.RandomWorldPoint((int)GenVars.worldSurface, 2, 190, 2);
                    }
                    Tile tile2 = Main.tile[point5.X, point5.Y];
                    Tile tile3 = Main.tile[point5.X, point5.Y - 1];
                    if (tile2.active())
                    {
                        bool flag40 = tile2.type == 60;
                        ushort num625 = 0;
                        if (flag40)
{
                            num625 = (ushort)(204 + WorldGen.genRand.Next(4));
                        }
                        else if (tile2.type == 1 && tile3.wall == 0)
{
                            if (WorldGen.remixWorldGen)
{
                                if ((double)point5.Y > GenVars.rockLayer)
{
                                    num625 = (ushort)(196 + WorldGen.genRand.Next(4));
                                }
                                else if (point5.Y > GenVars.lavaLine && WorldGen.genRand.Next(2) == 0)
{
                                    num625 = (ushort)(208 + WorldGen.genRand.Next(4));
                                }
                                else
{
                                    num625 = (ushort)(212 + WorldGen.genRand.Next(4));
                                }
                            }
                            else if ((double)point5.Y < GenVars.rockLayer)
{
                                num625 = (ushort)(196 + WorldGen.genRand.Next(4));
                            }
                            else if (point5.Y < GenVars.lavaLine)
{
                                num625 = (ushort)(212 + WorldGen.genRand.Next(4));
                            }
                            else
{
                                num625 = (ushort)(208 + WorldGen.genRand.Next(4));
                            }
                        }
                        if (num625 != 0 && !tile3.active())
{
                            bool foundInvalidTile = false;
                            bool flag41;
                            if (flag40)
{
                                flag41 = WorldUtils.Gen(new Point(point5.X, point5.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new GenAction[]
{
                                    new Modifiers.IsNotSolid(),
                                    new Actions.Blank().Output(shapeData),
                                    new Actions.ContinueWrapper(Actions.Chain(new GenAction[]
{
                                        new Modifiers.IsTouching(true, new ushort[] { 147, 161, 396, 397, 70, 191 }),
                                        new Actions.Custom(delegate(int x, int y, object[] args)
{
                                            foundInvalidTile = true;
                                            return true;
                                        })
                                    }))
                                }));
                            }
                            else
{
                                flag41 = WorldUtils.Gen(new Point(point5.X, point5.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new GenAction[]
{
                                    new Modifiers.IsNotSolid(),
                                    new Actions.Blank().Output(shapeData),
                                    new Actions.ContinueWrapper(Actions.Chain(new GenAction[]
{
                                        new Modifiers.IsTouching(true, new ushort[] { 60, 147, 161, 396, 397, 70, 191 }),
                                        new Modifiers.IsTouching(true, new ushort[] { 147, 161, 396, 397, 70, 191 }),
                                        new Actions.Custom(delegate(int x, int y, object[] args)
{
                                            foundInvalidTile = true;
                                            return true;
                                        })
                                    }))
                                }));
                            }
                            if (shapeData.Count > 50 && flag41 && !foundInvalidTile)
{
                                WorldUtils.Gen(new Point(point5.X, point5.Y), new ModShapes.OuterOutline(shapeData, true, true), Actions.Chain(new GenAction[]
{
                                    new Modifiers.SkipWalls(new ushort[] { 87, 86, 244 }),
                                    new Actions.PlaceWall(num625, true)
                                }));
                                num622--;
                            }
                            else
{
                                num624--;
                            }
                            shapeData.Clear();
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.LifeCrystals, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    WorldGen.SecretSeed.DoErrorWorldShuffleBlocks();
                }
                if (WorldGen.getGoodWorldGen)
                {
                    Main.tileSolid[56] = false;
                }
                if (WorldGen.notTheBees)
                {
                    WorldGen.NotTheBees();
                }
                progress.Message = Lang.gen[28].Value;
                double num626 = (double)(Main.maxTilesX * Main.maxTilesY) * 2E-05;
                if (WorldGen.tenthAnniversaryWorldGen)
                {
                    num626 *= 1.2;
                }
                if (Main.starGame)
                {
                    num626 *= Main.starGameMath(0.2);
                }
                int num627 = 10000;
                if (WorldGen.skyblockWorldGen)
                {
                    num627 = 10;
                }
                for (int num628 = 0; num628 < (int)num626; num628++)
                {
                    double num629 = (double)num628 / ((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05);
                    progress.Set(num629);
                    bool flag42 = false;
                    int num630 = 0;
                    while (!flag42)
                    {
                        int num631 = WorldGen.genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                        if (WorldGen.remixWorldGen)
{
                            num631 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                        }
                        if (WorldGen.AddLifeCrystal(WorldGen.genRand.Next(Main.offLimitBorderTiles, Main.maxTilesX - Main.offLimitBorderTiles), num631))
{
                            flag42 = true;
                        }
                        else
{
                            num630++;
                            if (num630 >= num627)
{
                                flag42 = true;
                            }
                        }
                    }
                }
                if (WorldGen.SecretSeed.errorWorld.Enabled || WorldGen.SecretSeed.noSurface.Enabled)
                {
                    num626 = (double)(Main.maxTilesX * Main.maxTilesY) * 1E-05;
                    if (WorldGen.tenthAnniversaryWorldGen)
                    {
                        num626 *= 1.2;
                    }
                    if (Main.starGame)
                    {
                        num626 *= Main.starGameMath(0.2);
                    }
                    for (int num632 = 0; num632 < (int)num626; num632++)
                    {
                        double num633 = (double)num632 / ((double)(Main.maxTilesX * Main.maxTilesY) * 2E-05);
                        progress.Set(num633);
                        bool flag43 = false;
                        int num634 = 0;
                        while (!flag43)
{
                            int num635 = WorldGen.genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                            if (WorldGen.remixWorldGen)
{
                                num635 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                            }
                            if (WorldGen.AddManaCrystal(WorldGen.genRand.Next(Main.offLimitBorderTiles, Main.maxTilesX - Main.offLimitBorderTiles), num635))
{
                                flag43 = true;
                            }
                            else
{
                                num634++;
                                if (num634 >= num627)
{
                                    flag43 = true;
                                }
                            }
                        }
                    }
                }
                Main.tileSolid[225] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.Statues, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[29].Value;
                int num636 = 0;
                double num637 = (double)Main.maxTilesX / 4200.0;
                int num638 = (int)((double)(GenVars.statueList.Length * 2) * num637);
                if (WorldGen.noTrapsWorldGen && !WorldGen.skyblockWorldGen)
                {
                    num638 *= 15;
                    if (WorldGen.tenthAnniversaryWorldGen || WorldGen.notTheBees)
                    {
                        num638 /= 5;
                    }
                }
                if (Main.starGame)
                {
                    num638 = (int)((double)num638 * Main.starGameMath(0.2));
                }
                int num639 = 10000;
                if (WorldGen.skyblockWorldGen)
                {
                    num639 = 10;
                    num638 /= 2;
                }
                for (int num640 = 0; num640 < num638; num640++)
                {
                    if (num636 >= GenVars.statueList.Length)
                    {
                        num636 = 0;
                    }
                    int x3 = (int)GenVars.statueList[num636].X;
                    int y = (int)GenVars.statueList[num636].Y;
                    double num641 = (double)(num640 / num638);
                    progress.Set(num641);
                    bool flag44 = false;
                    int num642 = 0;
                    while (!flag44)
                    {
                        int num643 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                        int num644 = WorldGen.genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                        if (WorldGen.remixWorldGen)
{
                            WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                        }
                        int num645 = 100;
                        while (WorldGen.oceanDepths(num643, num644) || (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num643, num644, 0, false)))
{
                            num645--;
                            if (num645 <= 0)
{
                                break;
                            }
                            num643 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                            num644 = WorldGen.genRand.Next((int)(Main.worldSurface * 2.0 + Main.rockLayer) / 3, Main.maxTilesY - 300);
                            if (WorldGen.remixWorldGen)
{
                                WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                            }
                        }
                        if (num645 <= 0)
{
                            flag44 = true;
                        }
                        else
{
                            while (!Main.tile[num643, num644].active())
{
                                num644++;
                                if (num644 >= Main.maxTilesY)
{
                                    break;
                                }
                            }
                            if (num644 >= Main.maxTilesY)
{
                                flag44 = true;
                            }
                            else
{
                                num644--;
                                Tile tile4 = Main.tile[num643, num644];
                                bool flag45 = true;
                                if (flag45 && tile4.active() && Main.tileFrameImportant[(int)tile4.type] && !Main.tileCut[(int)tile4.type])
{
                                    flag45 = false;
                                }
                                if (flag45 && tile4.anyShimmer())
{
                                    flag45 = false;
                                }
                                if (flag45)
{
                                    WorldGen.PlaceTile(num643, num644, x3, true, true, -1, y);
                                }
                                if (tile4.active() && (int)tile4.type == x3)
{
                                    flag44 = true;
                                    if (GenVars.StatuesWithTraps.Contains(num636))
{
                                        WorldGen.PlaceStatueTrap(num643, num644);
                                    }
                                    num636++;
                                }
                                else
{
                                    num642++;
                                    if (num642 >= num639)
{
                                        flag44 = true;
                                    }
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.UndergroundHousesAndBuriedChests, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                int num646 = 10000;
                if (WorldGen.skyblockWorldGen)
                {
                    num646 = 100;
                }
                progress.Message = Lang.gen[30].Value;
                Main.tileSolid[226] = true;
                Main.tileSolid[162] = true;
                Main.tileSolid[225] = true;
                Main.tileSolid[190] = true;
                CaveHouseBiome caveHouseBiome = GenVars.configuration.CreateBiome<CaveHouseBiome>();
                int random2 = passConfig.Get<WorldGenRange>("CaveHouseCount").GetRandom(WorldGen.genRand);
                int random3 = passConfig.Get<WorldGenRange>("UnderworldChestCount").GetRandom(WorldGen.genRand);
                int num647 = passConfig.Get<WorldGenRange>("CaveChestCount").GetRandom(WorldGen.genRand);
                int num648 = passConfig.Get<WorldGenRange>("AdditionalDesertHouseCount").GetRandom(WorldGen.genRand);
                if (WorldGen.skyblockWorldGen)
                {
                    num648 = 0;
                }
                if (Main.starGame)
                {
                    num647 = (int)((double)num647 * Main.starGameMath(0.2));
                }
                int num649 = random2 + random3 + num647 + num648;
                int num650 = num646;
                int num651 = 0;
                while (num651 < num647 && num650 > 0)
                {
                    progress.Set((double)num651 / (double)num649);
                    int num652 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num653 = WorldGen.genRand.Next((int)((GenVars.worldSurfaceHigh + 20.0 + Main.rockLayer) / 2.0), Main.maxTilesY - 230);
                    if (WorldGen.remixWorldGen)
                    {
                        num653 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                    }
                    ushort wall = Main.tile[num652, num653].wall;
                    if (Main.wallDungeon[(int)wall] || wall == 87 || WorldGen.oceanDepths(num652, num653))
                    {
                        num650--;
                        num651--;
                    }
                    else if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num652, num653, 0, false))
                    {
                        num650--;
                        num651--;
                    }
                    else if (!WorldGen.AddBuriedChest(num652, num653, 0, false, -1, false, 0))
                    {
                        num650--;
                        num651--;
                    }
                    num651++;
                }
                num650 = num646;
                int num654 = 0;
                while (num654 < random3 && num650 > 0)
                {
                    progress.Set((double)(num654 + num647) / (double)num649);
                    int num655 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num656 = WorldGen.genRand.Next(Main.UnderworldLayer, Main.maxTilesY - 50);
                    if (Main.wallDungeon[(int)Main.tile[num655, num656].wall])
                    {
                        num650--;
                        num654--;
                    }
                    else if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num655, num656, 0, false))
                    {
                        num650--;
                        num654--;
                    }
                    else if (!WorldGen.AddBuriedChest(num655, num656, 0, false, -1, false, 0))
                    {
                        num650--;
                        num654--;
                    }
                    num654++;
                }
                num650 = num646;
                int num657 = 0;
                while (num657 < random2 && num650 > 0)
                {
                    progress.Set((double)(num657 + num647 + random3) / (double)num649);
                    int num658 = WorldGen.genRand.Next(80, Main.maxTilesX - 80);
                    int num659 = WorldGen.genRand.Next((int)(GenVars.worldSurfaceHigh + 20.0), Main.maxTilesY - 230);
                    if (WorldGen.remixWorldGen)
                    {
                        num659 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 400);
                    }
                    if (WorldGen.SecretSeed.GenerateBiggerAbandonedHouses)
                    {
                        int num660 = (int)(GenVars.worldSurfaceHigh + 20.0);
                        int num661 = Main.maxTilesY - 230;
                        if (WorldGen.remixWorldGen)
{
                            num660 = (int)Main.worldSurface;
                            num661 = Main.maxTilesY - 400;
                        }
                        num660 += HouseUtils.GetMaxPossibleRoomsInABigAbandonedHouse() * 10;
                        num659 = (int)MathHelper.Clamp((float)num659, (float)num660, (float)num661);
                    }
                    if (WorldGen.oceanDepths(num658, num659))
                    {
                        num650--;
                        num657--;
                    }
                    else if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num658, num659, 0, false))
                    {
                        num650--;
                        num657--;
                    }
                    else if (!caveHouseBiome.Place(new Point(num658, num659), GenVars.structures))
                    {
                        num650--;
                        num657--;
                    }
                    num657++;
                }
                if (!WorldGen.skyblockWorldGen)
                {
                    num650 = num646;
                    Rectangle undergroundDesertHiveLocation = GenVars.UndergroundDesertHiveLocation;
                    if (undergroundDesertHiveLocation.Width > 0 && undergroundDesertHiveLocation.Height > 0)
                    {
                        if ((double)undergroundDesertHiveLocation.Y < Main.worldSurface + 26.0)
{
                            int num662 = (int)Main.worldSurface + 26 - undergroundDesertHiveLocation.Y;
                            undergroundDesertHiveLocation.Y += num662;
                            undergroundDesertHiveLocation.Height -= num662;
                        }
                        int num663 = 0;
                        while (num663 < num648 && num650 > 0)
{
                            progress.Set((double)(num663 + num647 + random3 + random2) / (double)num649);
                            if (!caveHouseBiome.Place(WorldGen.RandomRectanglePoint(undergroundDesertHiveLocation), GenVars.structures))
{
                                num650--;
                                num663--;
                            }
                            num663++;
                        }
                    }
                }
                Main.tileSolid[226] = false;
                Main.tileSolid[162] = false;
                Main.tileSolid[225] = false;
                Main.tileSolid[190] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.SurfaceChests, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[31].Value;
                int num664 = 2000;
                if (WorldGen.skyblockWorldGen)
                {
                    num664 = 100;
                }
                for (int num665 = 0; num665 < (int)((double)Main.maxTilesX * 0.005); num665++)
                {
                    double num666 = (double)num665 / ((double)Main.maxTilesX * 0.005);
                    progress.Set(num666);
                    bool flag46 = false;
                    int num667 = 0;
                    while (!flag46)
                    {
                        int num668 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                        int num669 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)Main.worldSurface);
                        if (WorldGen.remixWorldGen)
{
                            num669 = WorldGen.genRand.Next(Main.maxTilesY - 400, Main.maxTilesY - 150);
                        }
                        else
{
                            while (WorldGen.oceanDepths(num668, num669))
{
                                num668 = WorldGen.genRand.Next(300, Main.maxTilesX - 300);
                                num669 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)Main.worldSurface);
                            }
                        }
                        bool flag47 = false;
                        bool flag48 = false;
                        if (!Main.tile[num668, num669].active())
{
                            if (Main.tile[num668, num669].wall == 2 || Main.tile[num668, num669].wall == 59 || Main.tile[num668, num669].wall == 244 || WorldGen.remixWorldGen)
{
                                if (Main.tile[num668, num669].wall == 244)
{
                                    flag47 = true;
                                }
                                flag48 = true;
                            }
                        }
                        else
{
                            int num670 = 50;
                            int num671 = num668;
                            int num672 = num669;
                            int num673 = 1;
                            for (int num674 = num671 - num670; num674 <= num671 + num670; num674 += 2)
{
                                for (int num675 = num672 - num670; num675 <= num672 + num670; num675 += 2)
{
                                    if ((double)num675 < Main.worldSurface && !Main.tile[num674, num675].active() && Main.tile[num674, num675].wall == 244 && WorldGen.genRand.Next(num673) == 0)
{
                                        flag47 = true;
                                        num673++;
                                        flag48 = true;
                                        num668 = num674;
                                        num669 = num675;
                                    }
                                }
                            }
                        }
                        if (flag48 && WorldGen.AddBuriedChest(num668, num669, 0, true, flag47 ? 12 : (-1), false, 0))
{
                            flag46 = true;
                        }
                        else
{
                            num667++;
                            if (num667 >= num664)
{
                                flag46 = true;
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.ChestsInJungleShrines, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[32].Value;
                for (int num676 = 0; num676 < GenVars.numJChests; num676++)
                {
                    double num677 = (double)num676 / (double)GenVars.numJChests;
                    progress.Set(num677);
                    int nextJungleChestItem = WorldGen.GetNextJungleChestItem();
                    if (!WorldGen.AddBuriedChest(GenVars.JChestX[num676] + WorldGen.genRand.Next(2), GenVars.JChestY[num676], nextJungleChestItem, false, 10, false, 0))
                    {
                        for (int num678 = GenVars.JChestX[num676] - 1; num678 <= GenVars.JChestX[num676] + 1; num678++)
{
                            for (int num679 = GenVars.JChestY[num676]; num679 <= GenVars.JChestY[num676] + 2; num679++)
{
                                WorldGen.KillTile(num678, num679, false, false, false);
                            }
                        }
                        for (int num680 = GenVars.JChestX[num676] - 1; num680 <= GenVars.JChestX[num676] + 1; num680++)
{
                            for (int num681 = GenVars.JChestY[num676]; num681 <= GenVars.JChestY[num676] + 3; num681++)
{
                                if (num681 < Main.maxTilesY)
{
                                    Main.tile[num680, num681].slope(0);
                                    Main.tile[num680, num681].halfBrick(false);
                                }
                            }
                        }
                        WorldGen.AddBuriedChest(GenVars.JChestX[num676], GenVars.JChestY[num676], nextJungleChestItem, false, 10, false, 0);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.UnderwaterChests, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[33].Value;
                for (int num682 = 0; num682 < GenVars.numOceanCaveTreasure; num682++)
                {
                    int num683 = (int)WorldGen.genRand.NextFromList(new short[] { 863, 186, 277, 187, 4404 });
                    if (WorldGen.SecretSeed.extraLiquid.Enabled)
                    {
                        num683 = (int)WorldGen.genRand.NextFromList(new short[] { 863, 186, 277, 187, 4404, 268 });
                    }
                    bool flag49 = false;
                    double num684 = 2.0;
                    while (!flag49 && num684 < 50.0)
                    {
                        num684 += 0.1;
                        int num685 = WorldGen.genRand.Next(GenVars.oceanCaveTreasure[num682].X - (int)num684, GenVars.oceanCaveTreasure[num682].X + (int)num684 + 1);
                        int num686 = WorldGen.genRand.Next(GenVars.oceanCaveTreasure[num682].Y - (int)num684 / 2, GenVars.oceanCaveTreasure[num682].Y + (int)num684 / 2 + 1);
                        if (num685 < Main.maxTilesX)
{
                            num685 = (int)((double)num685 - num684 / 2.0);
                        }
                        else
{
                            num685 = (int)((double)num685 + num684 / 2.0);
                        }
                        if (WorldGen.InWorld(num685, num686, 0) && Main.tile[num685, num686].liquid > 250 && (Main.tile[num685, num686].liquidType() == 0 || WorldGen.notTheBees || WorldGen.remixWorldGen))
{
                            flag49 = WorldGen.AddBuriedChest(num685, num686, num683, false, 17, true, 0);
                        }
                    }
                }
                int num687 = 0;
                double num688 = (double)Main.maxTilesX / 4200.0;
                if (WorldGen.SecretSeed.extraLiquid.Enabled)
                {
                    num688 *= 3.0;
                }
                int num689 = 0;
                while ((double)num689 < 9.0 * num688)
                {
                    double num690 = (double)num689 / (9.0 * num688);
                    progress.Set(num690);
                    num687++;
                    int num691 = 10;
                    if (WorldGen.tenthAnniversaryWorldGen)
                    {
                        num691 = 7;
                    }
                    int num692;
                    if (WorldGen.genRand.Next(num691) == 0)
                    {
                        num692 = 863;
                    }
                    else if (num687 == 1)
                    {
                        num692 = 186;
                    }
                    else if (num687 == 2)
                    {
                        num692 = 4404;
                    }
                    else if (num687 == 3)
                    {
                        num692 = 277;
                    }
                    else if (WorldGen.SecretSeed.extraLiquid.Enabled && num687 == 4)
                    {
                        num692 = 268;
                    }
                    else
                    {
                        num692 = 187;
                        num687 = 0;
                    }
                    bool flag50 = false;
                    int num693 = 0;
                    while (!flag50)
                    {
                        int num694 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                        int num695 = WorldGen.genRand.Next(1, Main.UnderworldLayer);
                        while (Main.tile[num694, num695].liquid < 250 || (Main.tile[num694, num695].liquidType() != 0 && !WorldGen.notTheBees && !WorldGen.remixWorldGen))
{
                            num694 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                            num695 = WorldGen.genRand.Next(50, Main.UnderworldLayer);
                        }
                        flag50 = WorldGen.AddBuriedChest(num694, num695, num692, false, 17, num694 < WorldGen.beachDistance || num694 > Main.maxTilesX - WorldGen.beachDistance, 0);
                        num693++;
                        if (num693 > 10000)
{
                            break;
                        }
                    }
                    flag50 = false;
                    num693 = 0;
                    while (!flag50)
                    {
                        int num696 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                        int num697 = WorldGen.genRand.Next((int)Main.worldSurface, Main.UnderworldLayer);
                        while (Main.tile[num696, num697].liquid < 250 || (Main.tile[num696, num697].liquidType() != 0 && !WorldGen.notTheBees))
{
                            num696 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                            num697 = WorldGen.genRand.Next((int)Main.worldSurface, Main.UnderworldLayer);
                        }
                        flag50 = WorldGen.AddBuriedChest(num696, num697, num692, false, 17, num696 < WorldGen.beachDistance || num696 > Main.maxTilesX - WorldGen.beachDistance, 0);
                        num693++;
                        if (num693 > 10000)
{
                            break;
                        }
                    }
                    num689++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SpiderCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
                {
                    return;
                }
                Main.tileSolid[379] = false;
                progress.Message = Lang.gen[64].Value;
                WorldGen.maxTileCount = 3500;
                int num698 = Main.maxTilesX / 2;
                int num699 = (int)((double)Main.maxTilesX * 0.005);
                int num700 = 500;
                int num701 = 3500;
                if (GenVars.notTheBeesAndForTheWorthyNoCelebration)
                {
                    num698 = (int)((float)num698 * 1.25f);
                    num700 = 1000;
                    num699 *= 2;
                    num701 = 5000;
                }
                else if (WorldGen.SecretSeed.roundLandmasses.Enabled)
                {
                    num698 /= 2;
                }
                else if (WorldGen.getGoodWorldGen)
                {
                    num699 *= 3;
                }
                if (WorldGen.notTheBees)
                {
                    Main.tileSolid[225] = true;
                }
                for (int num702 = 0; num702 < num699; num702++)
                {
                    double num703 = (double)num702 / ((double)Main.maxTilesX * 0.005);
                    progress.Set(num703);
                    int num704 = 0;
                    int num705 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                    int num706 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 230);
                    if (WorldGen.remixWorldGen)
                    {
                        num706 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    int num707 = WorldGen.countTiles(num705, num706, false, true);
                    while ((num707 >= num701 || num707 < num700) && num704 < num698)
                    {
                        num704++;
                        num705 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                        num706 = WorldGen.genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                        if (WorldGen.remixWorldGen)
{
                            num706 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                        }
                        num707 = WorldGen.countTiles(num705, num706, false, true);
                        if (WorldGen.shroomCount > 1)
{
                            num707 = 0;
                        }
                    }
                    if (num704 < num698)
                    {
                        WorldGen.Spread.Spider(num705, num706);
                    }
                }
                if (WorldGen.notTheBees)
                {
                    Main.tileSolid[225] = false;
                }
                Main.tileSolid[162] = true;
                if (WorldGen.SecretSeed.Variations.noSpiderCavesILiedMoreSpiderCaves)
                {
                    WorldGen.SecretSeed.DoNoSpiderCavesILiedMoreSpiderCaves();
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.GemCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.notTheBees)
                {
                    return;
                }
                progress.Message = Lang.gen[64].Value;
                WorldGen.maxTileCount = 300;
                double num708 = (double)Main.maxTilesX * 0.003;
                if (WorldGen.tenthAnniversaryWorldGen)
                {
                    num708 *= 1.5;
                }
                if (Main.starGame)
                {
                    num708 *= Main.starGameMath(0.2);
                }
                int num709 = 0;
                while ((double)num709 < num708)
                {
                    double num710 = (double)num709 / num708;
                    progress.Set(num710);
                    int num711 = 0;
                    int num712 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                    int num713 = WorldGen.genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                    if (WorldGen.remixWorldGen)
                    {
                        num713 = WorldGen.genRand.Next((int)Main.worldSurface + 30, (int)Main.rockLayer - 30);
                    }
                    int num714 = WorldGen.countTiles(num712, num713, false, false);
                    while ((num714 >= 300 || num714 < 50 || WorldGen.lavaCount > 0 || WorldGen.iceCount > 0 || WorldGen.rockCount == 0) && num711 < 1000)
                    {
                        num711++;
                        num712 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                        num713 = WorldGen.genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                        if (WorldGen.remixWorldGen)
{
                            num713 = WorldGen.genRand.Next((int)Main.worldSurface + 30, (int)Main.rockLayer - 30);
                        }
                        num714 = WorldGen.countTiles(num712, num713, false, false);
                    }
                    if (num711 < 1000)
                    {
                        WorldGen.gemCave(num712, num713);
                    }
                    num709++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.MossAndMossCaves, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.worldIsFrozen.Enabled)
                {
                    return;
                }
                if (WorldGen.notTheBees && !WorldGen.remixWorldGen && !WorldGen.dontStarveWorldGen)
                {
                    return;
                }
                progress.Message = Lang.gen[61].Value;
                WorldGen.randMoss(false);
                int num715 = Main.maxTilesX / 2100;
                if (WorldGen.remixWorldGen)
                {
                    num715 = (int)((double)num715 * 1.5);
                }
                else if (WorldGen.tenthAnniversaryWorldGen)
                {
                    num715 *= 2;
                }
                int num716 = 0;
                int num717 = 0;
                while (num717 < num715)
                {
                    int num718 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                    if (WorldGen.remixWorldGen)
                    {
                        num718 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.3), (int)((double)Main.maxTilesX * 0.7));
                    }
                    else if (WorldGen.tenthAnniversaryWorldGen)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            WorldGen.randMoss(true);
                        }
                    }
                    else if (WorldGen.getGoodWorldGen)
                    {
                        while ((double)num718 > (double)Main.maxTilesX * 0.42)
{
                            if ((double)num718 >= (double)Main.maxTilesX * 0.48)
{
                                break;
                            }
                            num718 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                        }
                    }
                    else if (!WorldGen.drunkWorldGen)
                    {
                        while ((double)num718 > (double)Main.maxTilesX * 0.38 && (double)num718 < (double)Main.maxTilesX * 0.62)
{
                            num718 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                        }
                    }
                    int num719;
                    if (WorldGen.remixWorldGen)
                    {
                        num719 = WorldGen.genRand.Next((int)Main.worldSurface + 50, (int)Main.rockLayer - 50);
                    }
                    else
                    {
                        num719 = WorldGen.genRand.Next((int)Main.rockLayer + 40, GenVars.lavaLine - 40);
                    }
                    bool flag51 = false;
                    int num720 = 50;
                    for (int num721 = num718 - num720; num721 <= num718 + num720; num721++)
                    {
                        for (int num722 = num719 - num720; num722 <= num719 + num720; num722++)
{
                            if (Main.tile[num721, num722].active())
{
                                int type7 = (int)Main.tile[num721, num722].type;
                                if (WorldGen.remixWorldGen)
{
                                    if (type7 == 60 || type7 == 161 || type7 == 147 || Main.tileDungeon[type7] || type7 == 25 || type7 == 203)
{
                                        flag51 = true;
                                        num721 = num718 + num720 + 1;
                                        break;
                                    }
                                }
                                else if (WorldGen.notTheBees && WorldGen.dontStarveWorldGen)
{
                                    if (type7 == 70 || type7 == 367 || type7 == 368 || type7 == 161 || type7 == 147 || type7 == 396 || type7 == 397 || Main.tileDungeon[type7])
{
                                        flag51 = true;
                                        num721 = num718 + num720 + 1;
                                        break;
                                    }
                                }
                                else if (type7 == 70 || type7 == 60 || type7 == 367 || type7 == 368 || type7 == 161 || type7 == 147 || type7 == 396 || type7 == 397 || Main.tileDungeon[type7])
{
                                    flag51 = true;
                                    num721 = num718 + num720 + 1;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag51)
                    {
                        num716++;
                        if (num716 > Main.maxTilesX)
{
                            num717++;
                        }
                    }
                    else
                    {
                        num716 = 0;
                        num717++;
                        int num723 = GenVars.lavaLine;
                        if (WorldGen.remixWorldGen)
{
                            num723 = (int)Main.rockLayer + 50;
                        }
                        WorldGen.neonMossBiome(num718, num719, num723);
                    }
                }
                WorldGen.maxTileCount = 2500;
                for (int num724 = 0; num724 < (int)((double)Main.maxTilesX * 0.01); num724++)
                {
                    double num725 = (double)num724 / ((double)Main.maxTilesX * 0.01);
                    progress.Set(num725);
                    int num726 = 0;
                    int num727 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                    int num728 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.waterLine);
                    if (WorldGen.remixWorldGen)
                    {
                        num728 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    if (Vector2D.Distance(new Vector2D((double)num727, (double)num728), GenVars.shimmerPosition) >= (double)WorldGen.shimmerSafetyDistance)
                    {
                        int num729 = WorldGen.countTiles(num727, num728, false, false);
                        while ((num729 >= 2500 || num729 < 10 || WorldGen.lavaCount > 0 || WorldGen.iceCount > 0 || WorldGen.rockCount == 0 || WorldGen.shroomCount > 0) && num726 < 1000)
{
                            num726++;
                            num727 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                            num728 = WorldGen.genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                            num729 = WorldGen.countTiles(num727, num728, false, false);
                        }
                        if (num726 < 1000)
{
                            WorldGen.setMoss(num727, num728);
                            WorldGen.Spread.Moss(num727, num728);
                        }
                    }
                }
                for (int num730 = 0; num730 < Main.maxTilesX; num730++)
                {
                    int num731 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                    int num732;
                    if (WorldGen.remixWorldGen)
                    {
                        num732 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    }
                    else
                    {
                        num732 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine);
                    }
                    if (Vector2D.Distance(new Vector2D((double)num731, (double)num732), GenVars.shimmerPosition) >= (double)WorldGen.shimmerSafetyDistance && Main.tile[num731, num732].active() && Main.tile[num731, num732].type == 1)
                    {
                        WorldGen.setMoss(num731, num732);
                        Main.tile[num731, num732].type = GenVars.mossTile;
                    }
                }
                double num733 = (double)Main.maxTilesX * 0.05;
                while (num733 > 0.0)
                {
                    int num734 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                    int num735;
                    if (WorldGen.remixWorldGen)
                    {
                        num735 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    }
                    else
                    {
                        num735 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine);
                    }
                    if (Vector2D.Distance(new Vector2D((double)num734, (double)num735), GenVars.shimmerPosition) >= (double)WorldGen.shimmerSafetyDistance && Main.tile[num734, num735].active() && Main.tile[num734, num735].type == 1 && (!Main.tile[num734 - 1, num735].active() || !Main.tile[num734 + 1, num735].active() || !Main.tile[num734, num735 - 1].active() || !Main.tile[num734, num735 + 1].active()))
                    {
                        WorldGen.setMoss(num734, num735);
                        Main.tile[num734, num735].type = GenVars.mossTile;
                        num733 -= 1.0;
                    }
                }
                num733 = (double)Main.maxTilesX * 0.065;
                if (WorldGen.remixWorldGen)
                {
                    num733 *= 2.0;
                }
                while (num733 > 0.0)
                {
                    int num736 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                    int num737;
                    if (WorldGen.remixWorldGen)
                    {
                        num737 = WorldGen.genRand.Next(GenVars.lavaLine, (int)Main.rockLayer + 50);
                    }
                    else
                    {
                        num737 = WorldGen.genRand.Next(GenVars.waterLine, Main.UnderworldLayer);
                    }
                    if (Main.tile[num736, num737].active() && Main.tile[num736, num737].type == 1 && (!Main.tile[num736 - 1, num737].active() || !Main.tile[num736 + 1, num737].active() || !Main.tile[num736, num737 - 1].active() || !Main.tile[num736, num737 + 1].active()))
                    {
                        int num738 = 25;
                        int num739 = 0;
                        for (int num740 = num736 - num738; num740 < num736 + num738; num740++)
{
                            for (int num741 = num737 - num738; num741 < num737 + num738; num741++)
{
                                if (Main.tile[num740, num741].liquid > 0 && Main.tile[num740, num741].lava())
{
                                    num739++;
                                }
                            }
                        }
                        if (num739 > 20)
{
                            Main.tile[num736, num737].type = 381;
                            num733 -= 1.0;
                        }
                        else
{
                            num733 -= 0.002;
                        }
                    }
                    num733 -= 0.001;
                }
                for (int num742 = 0; num742 < Main.maxTilesX; num742++)
                {
                    for (int num743 = 0; num743 < Main.maxTilesY; num743++)
                    {
                        if (Main.tile[num742, num743].active() && Main.tileMoss[(int)Main.tile[num742, num743].type])
{
                            for (int num744 = 0; num744 < 4; num744++)
{
                                int num745 = num742;
                                int num746 = num743;
                                if (num744 == 0)
{
                                    num745--;
                                }
                                if (num744 == 1)
{
                                    num745++;
                                }
                                if (num744 == 2)
{
                                    num746--;
                                }
                                if (num744 == 3)
{
                                    num746++;
                                }
                                try
{
                                    WorldGen.grassSpread = 0;
                                    WorldGen.SpreadGrass(num745, num746, 1, (int)Main.tile[num742, num743].type, true, default(TileColorCache));
                                }
                                catch
{
                                    WorldGen.grassSpread = 0;
                                    WorldGen.SpreadGrass(num745, num746, 1, (int)Main.tile[num742, num743].type, false, default(TileColorCache));
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.LihzahrdTemplePart2, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                Main.tileSolid[162] = false;
                Main.tileSolid[226] = true;
                WorldGen.templePart2();
                Main.tileSolid[232] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.CaveWallsInEnclosedSpaces, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                Main.tileSolid[162] = false;
                Main.tileSolid[226] = true;
                Main.tileSolid[232] = false;
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[63].Value;
                WorldGen.maxTileCount = 1500;
                for (int num747 = 0; num747 < (int)((double)Main.maxTilesX * 0.04); num747++)
                {
                    double num748 = (double)num747 / ((double)Main.maxTilesX * 0.04);
                    progress.Set(num748 * 0.66);
                    int num749 = 0;
                    int num750 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                    int num751 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 220);
                    if (WorldGen.remixWorldGen)
                    {
                        num751 = WorldGen.genRand.Next((int)Main.worldSurface + 25, (int)Main.rockLayer);
                    }
                    int num752 = WorldGen.countTiles(num750, num751, false, true);
                    while ((num752 >= WorldGen.maxTileCount || num752 < 10) && num749 < 500)
                    {
                        num749++;
                        num750 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                        num751 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 220);
                        if (WorldGen.remixWorldGen)
{
                            num751 = WorldGen.genRand.Next((int)Main.worldSurface + 25, (int)Main.rockLayer);
                        }
                        num752 = WorldGen.countTiles(num750, num751, false, true);
                    }
                    if (num749 < 500)
                    {
                        int num753 = WorldGen.genRand.Next(2);
                        if ((double)WorldGen.shroomCount > (double)WorldGen.rockCount * 0.75)
{
                            num753 = 80;
                        }
                        else if (WorldGen.iceCount > 0)
{
                            if (num753 == 0)
{
                                num753 = 40;
                            }
                            else if (num753 == 1)
{
                                num753 = 71;
                            }
                        }
                        else if (WorldGen.lavaCount > 0)
{
                            num753 = 79;
                        }
                        else
{
                            num753 = WorldGen.genRand.Next(4);
                            if (num753 == 0)
{
                                num753 = 59;
                            }
                            else if (num753 == 1)
{
                                num753 = 61;
                            }
                            else if (num753 == 2)
{
                                num753 = 170;
                            }
                            else if (num753 == 3)
{
                                num753 = 171;
                            }
                        }
                        WorldGen.Spread.Wall(num750, num751, num753);
                    }
                }
                if (WorldGen.remixWorldGen)
                {
                    WorldGen.maxTileCount = 1500;
                    for (int num754 = 0; num754 < (int)((double)Main.maxTilesX * 0.04); num754++)
                    {
                        double num755 = (double)num754 / ((double)Main.maxTilesX * 0.04);
                        progress.Set(num755 * 0.66);
                        int num756 = 0;
                        int num757 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                        int num758 = WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                        int num759 = WorldGen.countTiles(num757, num758, false, true);
                        while ((num759 >= WorldGen.maxTileCount || num759 < 10) && num756 < 500)
{
                            num756++;
                            num757 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                            num758 = WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                            num759 = WorldGen.countTiles(num757, num758, false, true);
                        }
                        if (num756 < 500 && WorldGen.iceCount == 0 && WorldGen.lavaCount == 0 && WorldGen.sandCount == 0)
{
                            int num760;
                            if (WorldGen.genRand.Next(2) == 0)
{
                                num760 = 2;
                            }
                            else
{
                                num760 = 63;
                            }
                            WorldGen.Spread.Wall(num757, num758, num760);
                        }
                    }
                }
                WorldGen.maxTileCount = 1500;
                double num761 = (double)Main.maxTilesX * 0.02;
                int num762 = 0;
                while ((double)num762 < num761)
                {
                    double num763 = (double)num762 / ((double)Main.maxTilesX * 0.02);
                    progress.Set(num763 * 0.33 + 0.66);
                    int num764 = 0;
                    int num765 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                    int num766 = WorldGen.genRand.Next((int)Main.worldSurface, GenVars.lavaLine);
                    int num767 = 0;
                    if (Main.tile[num765, num766].wall == 64)
                    {
                        num767 = WorldGen.countTiles(num765, num766, true, false);
                    }
                    while ((num767 >= WorldGen.maxTileCount || num767 < 10) && num764 < 1000)
                    {
                        num764++;
                        num765 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                        num766 = WorldGen.genRand.Next((int)Main.worldSurface, GenVars.lavaLine);
                        if (!Main.wallHouse[(int)Main.tile[num765, num766].wall] && Main.tile[num765, num766].wall != 244)
{
                            if (Main.tile[num765, num766].wall == 64)
{
                                num767 = WorldGen.countTiles(num765, num766, true, false);
                            }
                            else
{
                                num767 = 0;
                            }
                        }
                    }
                    if (num764 < 1000)
                    {
                        WorldGen.Spread.Wall2(num765, num766, 15);
                    }
                    num762++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.UndergroundJungleTrees, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                Main.tileSolid[379] = true;
                progress.Message = Lang.gen[83].Value;
                for (int num768 = 0; num768 < Main.maxTilesX; num768++)
                {
                    progress.Set((double)num768 / (double)Main.maxTilesX);
                    for (int num769 = (int)Main.worldSurface - 1; num769 < Main.maxTilesY - 350; num769++)
                    {
                        if (WorldGen.genRand.Next(10) == 0 || WorldGen.drunkWorldGen)
{
                            WorldGen.GrowUndergroundTree(num768, num769, 0);
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.FloatingIslandHouses, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyFloatingIslands)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.FloatingIslandHouses");
                progress.Set(0.0);
                for (int num770 = 0; num770 < GenVars.numIslandHouses; num770++)
                {
                    progress.Set((double)((float)num770 / (float)GenVars.numIslandHouses));
                    if (!GenVars.skyLake[num770])
                    {
                        WorldGen.IslandHouse(GenVars.floatingIslandHouseX[num770], GenVars.floatingIslandHouseY[num770], GenVars.floatingIslandStyle[num770]);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.QuickCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.QuickCleanup");
                progress.Set(0.0);
                if (WorldGen.notTheBees)
                {
                    WorldGen.NotTheBees();
                }
                Main.tileSolid[137] = false;
                Main.tileSolid[130] = false;
                for (int num771 = 20; num771 < Main.maxTilesX - 20; num771++)
                {
                    progress.Set((double)((float)(num771 - 20) / (float)(Main.maxTilesX - 40)));
                    for (int num772 = 20; num772 < Main.maxTilesY - 20; num772++)
                    {
                        Tile tile5 = Main.tile[num771, num772];
                        if (WorldGen.oceanDepths(num771, num772) && tile5.liquid > 0 && tile5.liquidType() != 0)
{
                            tile5.liquidType(0);
                        }
                        if ((double)num772 < Main.worldSurface && WorldGen.oceanDepths(num771, num772) && !WorldGen.SecretSeed.roundLandmasses.Enabled && tile5.type == 53 && tile5.active())
{
                            if (tile5.bottomSlope())
{
                                tile5.slope(0);
                            }
                            int num773 = num772 + 1;
                            while (num773 < num772 + WorldGen.genRand.Next(4, 7) && (!Main.tile[num771, num773].active() || (Main.tile[num771, num773].type != 397 && Main.tile[num771, num773].type != 53)) && (!Main.tile[num771, num773 + 1].active() || (Main.tile[num771, num773 + 1].type != 397 && Main.tile[num771, num773 + 1].type != 53 && Main.tile[num771, num773 + 1].type != 495)) && (!Main.tile[num771, num773 + 2].active() || (Main.tile[num771, num773 + 2].type != 397 && Main.tile[num771, num773 + 2].type != 53 && Main.tile[num771, num773 + 2].type != 495)))
{
                                Main.tile[num771, num773].type = 0;
                                Main.tile[num771, num773].active(true);
                                Main.tile[num771, num773].halfBrick(false);
                                Main.tile[num771, num773].slope(0);
                                num773++;
                            }
                        }
                        if (tile5.wall == 187 || tile5.wall == 216)
{
                            if (tile5.type == 59 || tile5.type == 123 || tile5.type == 224)
{
                                tile5.type = 397;
                            }
                            if (tile5.type == 368 || tile5.type == 367)
{
                                tile5.type = 397;
                            }
                            if (!Main.dualDungeonsSeed)
{
                                if ((double)num772 <= Main.rockLayer)
{
                                    tile5.liquid = 0;
                                }
                                else if (tile5.liquid > 0)
{
                                    tile5.liquid = byte.MaxValue;
                                    tile5.lava(true);
                                }
                            }
                        }
                        if ((double)num772 < Main.worldSurface && tile5.active() && tile5.type == 53 && Main.tile[num771, num772 + 1].wall == 0 && !WorldGen.SolidTile(num771, num772 + 1, false))
{
                            ushort num774 = 0;
                            int num775 = 3;
                            for (int num776 = num771 - num775; num776 <= num771 + num775; num776++)
{
                                for (int num777 = num772 - num775; num777 <= num772 + num775; num777++)
{
                                    if (Main.tile[num776, num777].wall > 0)
{
                                        num774 = Main.tile[num776, num777].wall;
                                        break;
                                    }
                                }
                            }
                            if (num774 > 0)
{
                                Main.tile[num771, num772 + 1].wall = num774;
                                if (tile5.wall == 0)
{
                                    tile5.wall = num774;
                                }
                            }
                        }
                        if (!tile5.active() || !TileID.Sets.SaveSlopes[(int)tile5.type])
{
                            tile5.ClearSlope();
                        }
                        else if (!TileID.Sets.Platforms[(int)tile5.type] && TileID.Sets.CanBeClearedDuringGeneration[(int)tile5.type])
{
                            if (tile5.topSlope() || tile5.halfBrick())
{
                                if (tile5.type != 225 || !tile5.halfBrick())
{
                                    if (!WorldGen.SolidTile(num771, num772 + 1, false))
{
                                        tile5.active(false);
                                    }
                                    if (Main.tile[num771 + 1, num772].type == 137 || Main.tile[num771 - 1, num772].type == 137)
{
                                        tile5.active(false);
                                    }
                                }
                            }
                            else if (tile5.bottomSlope())
{
                                if (!WorldGen.SolidTile(num771, num772 - 1, false))
{
                                    tile5.active(false);
                                }
                                if (Main.tile[num771 + 1, num772].type == 137 || Main.tile[num771 - 1, num772].type == 137)
{
                                    tile5.active(false);
                                }
                            }
                        }
                    }
                }
                Main.tileSolid[137] = true;
                Main.tileSolid[130] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.PotsGraveyardsAndBoulderPiles, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[35].Value;
                if (WorldGen.SecretSeed.addTeleporters.Enabled)
                {
                    WorldGen.SecretSeed.DoAddTeleporters();
                }
                if ((WorldGen.dontStarveWorldGen && (WorldGen.drunkWorldGen || WorldGen.getGoodWorldGen) && !WorldGen.tenthAnniversaryWorldGen) || WorldGen.SecretSeed.graveyardBloodmoonStart.Enabled)
                {
                    WorldGen.SpawnGraveyardBiomesEverywhere();
                }
                if ((WorldGen.noTrapsWorldGen || WorldGen.SecretSeed.errorWorld.Enabled) && !WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
                {
                    WorldGen.SetBoulderSolidity(true);
                    int num778 = (int)((double)(Main.maxTilesX * Main.maxTilesY) * 0.0004);
                    if (WorldGen.remixWorldGen)
                    {
                        num778 /= 2;
                    }
                    for (int num779 = 0; num779 < num778; num779++)
                    {
                        int num780 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                        int num781 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 250);
                        if (WorldGen.dontStarveWorldGen && !WorldGen.remixWorldGen && num779 < num778 / 10)
{
                            num781 = WorldGen.genRand.Next(100, Main.maxTilesY - 250);
                            while ((double)num780 > (double)Main.maxTilesX * 0.4)
{
                                if ((double)num780 >= (double)Main.maxTilesX * 0.6)
{
                                    break;
                                }
                                num780 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                            }
                        }
                        while (!Main.tile[num780, num781].active() && num781 < Main.maxTilesY - 250)
{
                            num781++;
                        }
                        num781--;
                        if (!Main.tile[num780, num781].anyShimmer())
{
                            int num782 = 138;
                            if (WorldGen.tenthAnniversaryWorldGen && WorldGen.genRand.Next(5) == 0)
{
                                num782 = 711;
                            }
                            if (WorldGen.PlaceTile(num780, num781, num782, true, false, -1, 0) && WorldGen.SecretSeed.errorWorld.Enabled && (int)Main.tile[num780, num781].type == num782)
{
                                for (int num783 = num780 - 1; num783 <= num780; num783++)
{
                                    for (int num784 = num781 - 1; num784 <= num781; num784++)
{
                                        Main.tile[num783, num784].invisibleBlock(true);
                                    }
                                }
                            }
                            if (WorldGen.PlaceTile(num780 + 2, num781, num782, true, false, -1, 0) && WorldGen.SecretSeed.errorWorld.Enabled && (int)Main.tile[num780 + 2, num781].type == num782)
{
                                for (int num785 = num780 + 1; num785 <= num780 + 2; num785++)
{
                                    for (int num786 = num781 - 1; num786 <= num781; num786++)
{
                                        Main.tile[num785, num786].invisibleBlock(true);
                                    }
                                }
                            }
                            if (WorldGen.PlaceTile(num780 + 1, num781 - 2, num782, true, false, -1, 0) && WorldGen.SecretSeed.errorWorld.Enabled && (int)Main.tile[num780 + 1, num781 - 2].type == num782)
{
                                for (int num787 = num780; num787 <= num780 + 1; num787++)
{
                                    for (int num788 = num781 - 3; num788 <= num781 - 2; num788++)
{
                                        Main.tile[num787, num788].invisibleBlock(true);
                                    }
                                }
                            }
                        }
                    }
                    WorldGen.SetBoulderSolidity(false);
                }
                double num789 = (double)(Main.maxTilesX * Main.maxTilesY) * 0.0008;
                if (Main.starGame)
                {
                    num789 *= Main.starGameMath(0.2);
                }
                int num790 = 10000;
                if (WorldGen.skyblockWorldGen)
                {
                    num790 = 5;
                    num789 /= 5.0;
                }
                int num791 = 0;
                while ((double)num791 < num789)
                {
                    double num792 = (double)num791 / num789;
                    progress.Set(num792);
                    bool flag52 = false;
                    int num793 = 0;
                    while (!flag52)
                    {
                        int num794 = WorldGen.genRand.Next((int)GenVars.worldSurfaceHigh, Main.maxTilesY - 10);
                        if (num792 > 0.93)
{
                            num794 = Main.maxTilesY - 150;
                        }
                        else if (num792 > 0.75)
{
                            num794 = (int)GenVars.worldSurfaceLow;
                        }
                        int num795 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                        bool flag53 = false;
                        for (int num796 = num794; num796 < Main.maxTilesY - 20; num796++)
{
                            if (!flag53)
{
                                if (Main.tile[num795, num796].active() && Main.tileSolid[(int)Main.tile[num795, num796].type])
{
                                    if (!Main.tile[num795, num796 - 1].anyLava() && !Main.tile[num795, num796 - 1].anyShimmer())
{
                                        flag53 = true;
                                    }
                                }
                                else if (WorldGen.skyblockWorldGen && (double)num796 > Main.worldSurface + 50.0)
{
                                    flag53 = true;
                                }
                            }
                            else if ((double)num796 >= Main.worldSurface || Main.tile[num795, num796].wall != 0)
{
                                int num797 = WorldGen.genRand.Next(0, 4);
                                Tile tile6 = Main.tile[num795, num796 + 1];
                                if (tile6.active() && !WorldGen.oceanDepths(num795, num796) && !Main.tile[num795, num796].anyShimmer() && !Main.tile[num795, num796].anyLava())
{
                                    ushort type8 = tile6.type;
                                    if (type8 == 19)
{
                                        short num798 = tile6.frameY % 18;
                                    }
                                    ushort wall2 = Main.tile[num795, num796].wall;
                                    if (type8 == 147 || type8 == 161 || type8 == 162)
{
                                        num797 = WorldGen.genRand.Next(4, 7);
                                    }
                                    if (type8 == 60)
{
                                        num797 = WorldGen.genRand.Next(7, 10);
                                    }
                                    if (Main.wallDungeon[(int)wall2] || type8 == 41 || type8 == 43 || type8 == 44 || type8 == 481 || type8 == 482 || type8 == 483 || WorldGen.IsDungeonPlatformOrShelf(tile6))
{
                                        num797 = WorldGen.genRand.Next(10, 13);
                                    }
                                    if (type8 == 23 || type8 == 25 || type8 == 22 || type8 == 163)
{
                                        num797 = WorldGen.genRand.Next(16, 19);
                                    }
                                    if (type8 == 199 || type8 == 203 || type8 == 204 || type8 == 200)
{
                                        num797 = WorldGen.genRand.Next(22, 25);
                                    }
                                    if (type8 == 367)
{
                                        num797 = WorldGen.genRand.Next(31, 34);
                                    }
                                    if (type8 == 226)
{
                                        num797 = WorldGen.genRand.Next(28, 31);
                                    }
                                    if (wall2 == 187 || wall2 == 216 || wall2 == 223)
{
                                        num797 = WorldGen.genRand.Next(34, 37);
                                    }
                                    if (num796 > Main.UnderworldLayer)
{
                                        num797 = WorldGen.genRand.Next(13, 16);
                                    }
                                    if (WorldGen.PlacePot(num795, num796, 28, num797))
{
                                        flag52 = true;
                                        break;
                                    }
                                }
                            }
                        }
                        num793++;
                        if (num793 >= num790)
{
                            break;
                        }
                    }
                    num791++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Hellforges, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[36].Value;
                int num799 = Main.maxTilesX / 200;
                for (int num800 = 0; num800 < num799; num800++)
                {
                    float num801 = (float)num800 / (float)num799;
                    progress.Set((double)num801);
                    bool flag54 = false;
                    int num802 = 0;
                    while (!flag54)
                    {
                        int num803 = WorldGen.genRand.Next(1, Main.maxTilesX);
                        int num804 = WorldGen.genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 30);
                        try
{
                            if (Main.tile[num803, num804].wall != 13)
{
                                if (Main.tile[num803, num804].wall != 14)
{
                                    continue;
                                }
                            }
                            while (!Main.tile[num803, num804].active() && num804 < Main.maxTilesY - 20)
{
                                num804++;
                            }
                            num804--;
                            WorldGen.PlaceTile(num803, num804, 77, false, false, -1, 0);
                            if (Main.tile[num803, num804].type == 77)
{
                                flag54 = true;
                            }
                            else
{
                                num802++;
                                if (num802 >= 10000)
{
                                    flag54 = true;
                                }
                            }
                        }
                        catch
{
                            num802++;
                            if (num802 >= 10000)
{
                                flag54 = true;
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SpreadingGrassOnSurfaceSunflowersEvilsOnSurfaceAndLavaCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.notTheBees && !WorldGen.remixWorldGen && !WorldGen.tenthAnniversaryWorldGen)
                {
                    return;
                }
                progress.Message = Lang.gen[37].Value;
                for (int num805 = 50; num805 < Main.maxTilesX - 50; num805++)
                {
                    progress.Set((double)((float)(num805 - 50) / (float)(Main.maxTilesX - 100)), 0.0, 0.30000001192092896);
                    int num806 = 50;
                    while ((double)num806 <= Main.worldSurface)
                    {
                        if (Main.tile[num805, num806].active())
{
                            int type9 = (int)Main.tile[num805, num806].type;
                            if (Main.tile[num805, num806].active() && type9 == 60)
{
                                for (int num807 = num805 - 1; num807 <= num805 + 1; num807++)
{
                                    for (int num808 = num806 - 1; num808 <= num806 + 1; num808++)
{
                                        if (Main.tile[num807, num808].active() && Main.tile[num807, num808].type == 0)
{
                                            if (!Main.tile[num807, num808 - 1].active())
{
                                                Main.tile[num807, num808].type = 60;
                                            }
                                            else
{
                                                Main.tile[num807, num808].type = 59;
                                            }
                                        }
                                    }
                                }
                            }
                            else if (type9 == 1 || type9 == 40 || TileID.Sets.Ore[type9])
{
                                int num809 = 3;
                                bool flag55 = false;
                                ushort num810 = 0;
                                for (int num811 = num805 - num809; num811 <= num805 + num809; num811++)
{
                                    for (int num812 = num806 - num809; num812 <= num806 + num809; num812++)
{
                                        if (Main.tile[num811, num812].active())
{
                                            if (Main.tile[num811, num812].type == 53 || num810 == 53)
{
                                                num810 = 53;
                                            }
                                            else if (Main.tile[num811, num812].type == 59 || Main.tile[num811, num812].type == 60 || Main.tile[num811, num812].type == 147 || Main.tile[num811, num812].type == 161 || Main.tile[num811, num812].type == 199 || Main.tile[num811, num812].type == 23)
{
                                                num810 = Main.tile[num811, num812].type;
                                            }
                                        }
                                        else if (num812 < num806 && Main.tile[num811, num812].wall == 0)
{
                                            flag55 = true;
                                        }
                                    }
                                }
                                if (flag55)
{
                                    if (num810 == 199 || num810 == 23)
{
                                        if (Main.tile[num805, num806 - 1].active())
{
                                            num810 = 0;
                                        }
                                    }
                                    else if ((num810 == 60 || num810 == 59) && num805 >= GenVars.jungleMinX && num805 <= GenVars.jungleMaxX)
{
                                        if (!Main.tile[num805, num806 - 1].active())
{
                                            num810 = 60;
                                        }
                                        else
{
                                            num810 = 59;
                                        }
                                    }
                                    Main.tile[num805, num806].type = num810;
                                }
                            }
                        }
                        num806++;
                    }
                }
                for (int num813 = 10; num813 < Main.maxTilesX - 10; num813++)
                {
                    progress.Set((double)((float)(num813 - 10) / (float)(Main.maxTilesX - 20)), 0.30000001192092896, 0.550000011920929);
                    bool flag56 = true;
                    int num814 = 0;
                    while ((double)num814 < Main.worldSurface - 1.0)
                    {
                        if (Main.tile[num813, num814].active())
{
                            if (flag56 && Main.tile[num813, num814].type == 0)
{
                                try
{
                                    WorldGen.grassSpread = 0;
                                    WorldGen.SpreadGrass(num813, num814, 0, 2, true, default(TileColorCache));
                                }
                                catch
{
                                    WorldGen.grassSpread = 0;
                                    WorldGen.SpreadGrass(num813, num814, 0, 2, false, default(TileColorCache));
                                }
                            }
                            if ((double)num814 > GenVars.worldSurfaceHigh)
{
                                break;
                            }
                            flag56 = false;
                        }
                        else if (Main.tile[num813, num814].wall == 0)
{
                            flag56 = true;
                        }
                        num814++;
                    }
                }
                if (WorldGen.remixWorldGen)
                {
                    progress.Set(0.550000011920929);
                    for (int num815 = 5; num815 < Main.maxTilesX - 5; num815++)
                    {
                        for (int num816 = GenVars.remixSurfaceLayerLow + WorldGen.genRand.Next(-1, 2); num816 < GenVars.remixSurfaceLayerHigh; num816++)
{
                            if (Main.tile[num815, num816].type == 0 && Main.tile[num815, num816].active() && (!Main.tile[num815 - 1, num816 - 1].active() || !Main.tile[num815, num816 - 1].active() || !Main.tile[num815 + 1, num816 - 1].active() || !Main.tile[num815 - 1, num816].active() || !Main.tile[num815 + 1, num816].active() || !Main.tile[num815 - 1, num816 + 1].active() || !Main.tile[num815, num816 + 1].active() || !Main.tile[num815 + 1, num816 + 1].active()))
{
                                Main.tile[num815, num816].type = 2;
                            }
                        }
                    }
                    progress.Set(0.6499999761581421);
                    for (int num817 = 5; num817 < Main.maxTilesX - 5; num817++)
                    {
                        for (int num818 = GenVars.remixSurfaceLayerLow + WorldGen.genRand.Next(-1, 2); num818 < GenVars.remixSurfaceLayerHigh; num818++)
{
                            if (Main.tile[num817, num818].type == 2 && !Main.tile[num817, num818 - 1].active() && WorldGen.genRand.Next(20) == 0)
{
                                WorldGen.PlaceTile(num817, num818 - 1, 27, true, false, -1, 0);
                            }
                        }
                    }
                    progress.Set(0.75);
                    int num819 = 1;
                    if (WorldGen.crimson)
                    {
                        num819 = 4;
                    }
                    int num820 = Main.maxTilesX / 7;
                    for (int num821 = 10; num821 < Main.maxTilesX - 10; num821++)
                    {
                        progress.Set((double)((float)(num821 - 10) / (float)(Main.maxTilesX - 20)), 0.75, 0.8999999761581421);
                        for (int num822 = 10; num822 < Main.maxTilesY - 10; num822++)
{
                            if ((double)num822 < Main.worldSurface + (double)WorldGen.genRand.Next(3) || num821 < num820 + WorldGen.genRand.Next(3) || num821 >= Main.maxTilesX - num820 - WorldGen.genRand.Next(3))
{
                                if (WorldGen.drunkWorldGen)
{
                                    if (GenVars.crimsonLeft)
{
                                        if (num821 < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                            WorldGen.Convert(num821, num822, 4, true, true);
                                        }
                                        else
{
                                            WorldGen.Convert(num821, num822, 1, true, true);
                                        }
                                    }
                                    else if (num821 < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                        WorldGen.Convert(num821, num822, 1, true, true);
                                    }
                                    else
{
                                        WorldGen.Convert(num821, num822, 4, true, true);
                                    }
                                }
                                else
{
                                    WorldGen.Convert(num821, num822, num819, true, true);
                                }
                                Main.tile[num821, num822].color(0);
                                Main.tile[num821, num822].wallColor(0);
                            }
                        }
                    }
                    progress.Set(0.8999999761581421);
                    if (WorldGen.remixWorldGen)
                    {
                        Main.tileSolid[225] = true;
                        int num823 = (int)((double)Main.maxTilesX * 0.31);
                        int num824 = (int)((double)Main.maxTilesX * 0.69);
                        int maxTilesY = Main.maxTilesY;
                        int num825 = Main.maxTilesY - 135;
                        int maxTilesY2 = Main.maxTilesY;
                        Liquid.QuickWater(-2, -1, -1);
                        for (int num826 = num823; num826 < num824 + 15; num826++)
{
                            for (int num827 = Main.maxTilesY - 200; num827 < num825; num827++)
{
                                Main.tile[num826, num827].liquid = 0;
                            }
                        }
                        Main.tileSolid[225] = false;
                        Main.tileSolid[484] = false;
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.SurfaceOreAndStone, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                int num828 = WorldGen.genRand.Next(Main.maxTilesX * 5 / 4200, Main.maxTilesX * 10 / 4200);
                for (int num829 = 0; num829 < num828; num829++)
                {
                    int num830 = Main.maxTilesX / 420;
                    while (num830 > 0)
                    {
                        num830--;
                        int num831 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                        while ((double)num831 >= (double)Main.maxTilesX * 0.48 && (double)num831 <= (double)Main.maxTilesX * 0.52)
{
                            num831 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                        }
                        int num832 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurface);
                        bool flag57 = false;
                        for (int num833 = 0; num833 < GenVars.numOrePatch; num833++)
{
                            if (Math.Abs(num831 - GenVars.orePatchX[num833]) < 200)
{
                                flag57 = true;
                            }
                        }
                        if (!flag57 && WorldGen.OrePatch(num831, num832))
{
                            if (GenVars.numOrePatch < GenVars.maxOrePatch - 1)
{
                                GenVars.orePatchX[GenVars.numOrePatch] = num831;
                                GenVars.numOrePatch++;
                                break;
                            }
                            break;
                        }
                    }
                }
                num828 = WorldGen.genRand.Next(1, Main.maxTilesX * 7 / 4200);
                for (int num834 = 0; num834 < num828; num834++)
                {
                    int num835 = Main.maxTilesX / 420;
                    while (num835 > 0)
                    {
                        num835--;
                        int num836 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                        while ((double)num836 >= (double)Main.maxTilesX * 0.47 && (double)num836 <= (double)Main.maxTilesX * 0.53)
{
                            num836 = WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance);
                        }
                        int num837 = WorldGen.genRand.Next((int)GenVars.worldSurfaceLow, (int)GenVars.worldSurface);
                        bool flag58 = false;
                        for (int num838 = 0; num838 < GenVars.numOrePatch; num838++)
{
                            if (Math.Abs(num836 - GenVars.orePatchX[num838]) < 100)
{
                                flag58 = true;
                            }
                        }
                        if (!flag58 && WorldGen.StonePatch(num836, num837))
{
                            break;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.FallenLogsAndWaterFeatures, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.extraLiquid.Enabled && !WorldGen.SecretSeed.roundLandmasses.Enabled)
                {
                    progress.Message = Language.GetTextValue("WorldGeneration.WaterFeatures");
                    WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks();
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[85].Value;
                int num839 = Main.maxTilesX / 2100;
                if (WorldGen.remixWorldGen)
                {
                    num839 += WorldGen.genRand.Next(0, 2);
                }
                else
                {
                    num839 += WorldGen.genRand.Next(-1, 2);
                }
                for (int num840 = 0; num840 < num839; num840++)
                {
                    progress.Set((double)num840 / (double)num839);
                    int num841 = WorldGen.beachDistance + 20;
                    int num842 = 30000;
                    int num843 = 5000;
                    if (WorldGen.skyblockWorldGen)
                    {
                        num842 /= 10;
                        num843 /= 10;
                    }
                    while (num842 > 0)
                    {
                        num842--;
                        int num844 = WorldGen.genRand.Next(num841, Main.maxTilesX - num841);
                        int num845 = WorldGen.genRand.Next(10, (int)Main.worldSurface);
                        if (WorldGen.remixWorldGen)
{
                            num845 = WorldGen.genRand.Next(GenVars.remixSurfaceLayerLow, GenVars.remixSurfaceLayerHigh);
                        }
                        bool flag59 = false;
                        if (num842 < num843)
{
                            flag59 = true;
                        }
                        if (num842 > num843 / 2)
{
                            while ((double)num844 > (double)Main.maxTilesX * 0.4 && (double)num844 < (double)Main.maxTilesX * 0.6)
{
                                num844 = WorldGen.genRand.Next(num841, Main.maxTilesX - num841);
                            }
                        }
                        if (!Main.tile[num844, num845].active() && Main.tile[num844, num845].wall == 0)
{
                            bool flag60 = true;
                            if (WorldGen.remixWorldGen)
{
                                while (!Main.tile[num844, num845].active() && Main.tile[num844, num845].wall == 0)
{
                                    if (num845 > GenVars.remixSurfaceLayerHigh)
{
                                        break;
                                    }
                                    num845++;
                                }
                            }
                            else
{
                                while (!Main.tile[num844, num845].active() && Main.tile[num844, num845].wall == 0 && (double)num845 <= Main.worldSurface)
{
                                    num845++;
                                }
                            }
                            if ((double)num845 > Main.worldSurface - 10.0 && !WorldGen.remixWorldGen)
{
                                flag60 = false;
                            }
                            else if (!flag59)
{
                                int num846 = 50;
                                for (int num847 = num844 - num846; num847 < num844 + num846; num847++)
{
                                    if (num847 > 10 && num847 < Main.maxTilesX - 10)
{
                                        for (int num848 = num845 - num846; num848 < num845 + num846; num848++)
{
                                            if (num848 > 10 && num848 < Main.maxTilesY - 10)
{
                                                int type10 = (int)Main.tile[num847, num848].type;
                                                if (type10 == 189)
{
                                                    flag60 = false;
                                                }
                                                else if (type10 == 53)
{
                                                    flag60 = false;
                                                }
                                                else if (Main.tileDungeon[type10])
{
                                                    flag60 = false;
                                                }
                                                else if (TileID.Sets.Crimson[type10])
{
                                                    flag60 = false;
                                                }
                                                else if (TileID.Sets.Corrupt[type10])
{
                                                    flag60 = false;
                                                }
                                            }
                                        }
                                    }
                                }
                                if (flag60)
{
                                    int num849 = 10;
                                    int num850 = 10;
                                    for (int num851 = num844 - num849; num851 < num844 + num849; num851++)
{
                                        for (int num852 = num845 - num850; num852 < num845 - 1; num852++)
{
                                            if (Main.tile[num851, num852].active() && Main.tileSolid[(int)Main.tile[num851, num852].type])
{
                                                flag60 = false;
                                            }
                                            if (Main.tile[num851, num852].wall != 0)
{
                                                flag60 = false;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag60 && (Main.tile[num844, num845 - 1].liquid == 0 || num842 < num843 / 5) && (Main.tile[num844, num845].type == 2 || (WorldGen.notTheBees && Main.tile[num844, num845].type == 60) || (WorldGen.SecretSeed.worldIsFrozen.Enabled && Main.tile[num844, num845].type == 147) || (WorldGen.SecretSeed.surfaceIsDesert.Enabled && Main.tile[num844, num845].type == 53)) && (Main.tile[num844 - 1, num845].type == 2 || (WorldGen.notTheBees && Main.tile[num844 - 1, num845].type == 60) || (WorldGen.SecretSeed.worldIsFrozen.Enabled && Main.tile[num844 - 1, num845].type == 147) || (WorldGen.SecretSeed.surfaceIsDesert.Enabled && Main.tile[num844 - 1, num845].type == 53)) && (Main.tile[num844 + 1, num845].type == 2 || (WorldGen.notTheBees && Main.tile[num844 + 1, num845].type == 60) || (WorldGen.SecretSeed.worldIsFrozen.Enabled && Main.tile[num844 + 1, num845].type == 147) || (WorldGen.SecretSeed.surfaceIsDesert.Enabled && Main.tile[num844 + 1, num845].type == 53)))
{
                                num845--;
                                WorldGen.PlaceTile(num844, num845, 488, false, false, -1, 0);
                                if (Main.tile[num844, num845].active() && Main.tile[num844, num845].type == 488)
{
                                    if (WorldGen.genRand.Next(2) == 0)
{
                                        GenVars.logX = num844;
                                        GenVars.logY = num845;
                                    }
                                    num842 = -1;
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Traps, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
                {
                    return;
                }
                if (WorldGen.notTheBees && !WorldGen.noTrapsWorldGen && !WorldGen.remixWorldGen)
                {
                    return;
                }
                Main.tileSolid[379] = false;
                WorldGen.placingTraps = true;
                progress.Message = Lang.gen[34].Value;
                if (WorldGen.noTrapsWorldGen)
                {
                    progress.Message = Lang.gen[91].Value;
                }
                double num853 = (double)Main.maxTilesX * 0.05;
                if (WorldGen.noTrapsWorldGen)
                {
                    if ((WorldGen.tenthAnniversaryWorldGen || WorldGen.notTheBees) && WorldGen.remixWorldGen)
                    {
                        num853 *= 5.0;
                    }
                    else if (WorldGen.tenthAnniversaryWorldGen || WorldGen.notTheBees)
                    {
                        num853 *= 2.0;
                    }
                    else
                    {
                        num853 *= 100.0;
                    }
                }
                else if (WorldGen.getGoodWorldGen)
                {
                    num853 *= 1.5;
                }
                if (Main.starGame)
                {
                    num853 *= Main.starGameMath(0.2);
                }
                int num854 = 1150;
                if (WorldGen.skyblockWorldGen)
                {
                    num853 /= 5.0;
                    num854 = 100;
                }
                int num855 = -1;
                int num856 = 0;
                while ((double)num856 < num853)
                {
                    progress.Set((double)num856 / num853 / 2.0);
                    for (int num857 = 0; num857 < num854; num857++)
                    {
                        if (WorldGen.noTrapsWorldGen)
{
                            int num858 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                            int num859 = WorldGen.genRand.Next(50, Main.maxTilesY - 50);
                            if (WorldGen.remixWorldGen)
{
                                num859 = WorldGen.genRand.Next(50, Main.maxTilesY - 210);
                            }
                            if (((double)num859 > Main.worldSurface || Main.tile[num858, num859].wall > 0) && WorldGen.placeTrap(num858, num859, num855))
{
                                break;
                            }
                        }
                        else
{
                            int num860 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                            int num861 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 210);
                            while (WorldGen.oceanDepths(num860, num861))
{
                                num860 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                                num861 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 210);
                            }
                            if (Main.tile[num860, num861].wall == 0 && WorldGen.placeTrap(num860, num861, num855))
{
                                break;
                            }
                        }
                    }
                    num856++;
                }
                if (WorldGen.noTrapsWorldGen)
                {
                    num853 = (double)(Main.maxTilesX * 3);
                    if (WorldGen.tenthAnniversaryWorldGen)
                    {
                        num853 = (double)(Main.maxTilesX / 3);
                    }
                    if (Main.starGame)
                    {
                        num853 *= Main.starGameMath(0.2);
                    }
                    int num862 = 0;
                    while ((double)num862 < num853)
                    {
                        if (Main.remixWorld)
{
                            WorldGen.placeTNTBarrel(WorldGen.genRand.Next(50, Main.maxTilesX - 50), WorldGen.genRand.Next((int)Main.worldSurface, (int)((double)(Main.maxTilesY - 350) + Main.rockLayer) / 2));
                        }
                        else
{
                            WorldGen.placeTNTBarrel(WorldGen.genRand.Next(50, Main.maxTilesX - 50), WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 200));
                        }
                        num862++;
                    }
                }
                num853 = (double)Main.maxTilesX * 0.003;
                if (WorldGen.noTrapsWorldGen)
                {
                    num853 *= 5.0;
                }
                else if (WorldGen.getGoodWorldGen)
                {
                    num853 *= 1.5;
                }
                int num863 = 0;
                while ((double)num863 < num853)
                {
                    progress.Set((double)num863 / num853 / 2.0 + 0.5);
                    for (int num864 = 0; num864 < 20000; num864++)
                    {
                        int num865 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.85));
                        int num866 = WorldGen.genRand.Next((int)Main.worldSurface + 20, Main.maxTilesY - 210);
                        if (Main.tile[num865, num866].wall == 187 && WorldGen.PlaceSandTrap(num865, num866))
{
                            break;
                        }
                    }
                    num863++;
                }
                if (WorldGen.drunkWorldGen && !WorldGen.noTrapsWorldGen && !WorldGen.notTheBees && !WorldGen.getGoodWorldGen)
                {
                    for (int num867 = 0; num867 < 8; num867++)
                    {
                        progress.Message = Lang.gen[34].Value;
                        num853 = 100.0;
                        int num868 = 0;
                        while ((double)num868 < num853)
{
                            progress.Set((double)num868 / num853);
                            Thread.Sleep(10);
                            num868++;
                        }
                    }
                }
                if (WorldGen.noTrapsWorldGen)
                {
                    WorldGen.SetBoulderSolidity(true);
                }
                WorldGen.placingTraps = false;
                Main.tileSolid[379] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.Piles, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[89].Value;
                progress.Set(0.0);
                Main.tileSolid[379] = false;
                Main.tileSolid[229] = false;
                Main.tileSolid[190] = false;
                Main.tileSolid[196] = false;
                Main.tileSolid[189] = false;
                Main.tileSolid[717] = false;
                Main.tileSolid[718] = false;
                Main.tileSolid[719] = false;
                Main.tileSolid[202] = false;
                Main.tileSolid[460] = false;
                Main.tileSolid[484] = false;
                if (WorldGen.noTrapsWorldGen)
                {
                    WorldGen.SetBoulderSolidity(false);
                }
                float num869 = 7f;
                float num870 = 1f / num869;
                float num871 = (float)Main.maxTilesX * 0.06f;
                int num872 = 0;
                while ((float)num872 < num871)
                {
                    if (progress != null)
                    {
                        float num873 = (float)num872 / num871;
                        progress.Set((double)(num873 * num870));
                    }
                    int num874 = WorldGen.GetPileGenerationAttempts();
                    bool flag61 = false;
                    while (!flag61 && num874 > 0)
                    {
                        num874--;
                        int num875 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num876 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                        while (WorldGen.oceanDepths(num875, num876))
{
                            num875 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                            num876 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                        }
                        if (!Main.tile[num875, num876].active())
{
                            int num877 = 186;
                            while (!Main.tile[num875, num876 + 1].active() && num876 < Main.maxTilesY - 5)
{
                                num876++;
                            }
                            Tile tile7 = Main.tile[num875, num876];
                            Tile tile8 = Main.tile[num875, num876 + 1];
                            if (tile8.active())
{
                                int num878 = WorldGen.genRand.Next(22);
                                if (num878 >= 16 && num878 <= 22)
{
                                    num878 = WorldGen.genRand.Next(22);
                                }
                                if ((tile8.type == 0 || tile8.type == 1 || Main.tileMoss[(int)tile8.type]) && WorldGen.genRand.Next(5) == 0)
{
                                    num878 = WorldGen.genRand.Next(23, 29);
                                    num877 = 187;
                                }
                                if (num876 > Main.maxTilesY - 300 || Main.wallDungeon[(int)tile7.wall] || tile8.type == 30 || tile8.type == 19 || tile8.type == 25 || tile8.type == 203)
{
                                    num878 = WorldGen.genRand.Next(7);
                                    num877 = 186;
                                }
                                if (tile8.type == 147 || tile8.type == 161 || tile8.type == 162)
{
                                    num878 = WorldGen.genRand.Next(26, 32);
                                    num877 = 186;
                                }
                                if (tile8.type == 60)
{
                                    num877 = 187;
                                    num878 = WorldGen.genRand.Next(6);
                                }
                                if ((tile8.type == 57 || tile8.type == 58) && WorldGen.genRand.Next(3) < 2)
{
                                    num877 = 187;
                                    num878 = WorldGen.genRand.Next(6, 9);
                                }
                                if (tile8.type == 226)
{
                                    num877 = 187;
                                    num878 = WorldGen.genRand.Next(18, 23);
                                }
                                if (tile8.type == 70)
{
                                    num878 = WorldGen.genRand.Next(32, 35);
                                    num877 = 186;
                                }
                                if (tile8.type == 396 || tile8.type == 397 || tile8.type == 404)
{
                                    num878 = WorldGen.genRand.Next(29, 35);
                                    num877 = 187;
                                }
                                if (tile8.type == 368)
{
                                    num878 = WorldGen.genRand.Next(35, 41);
                                    num877 = 187;
                                }
                                if (tile8.type == 367)
{
                                    num878 = WorldGen.genRand.Next(41, 47);
                                    num877 = 187;
                                }
                                if (num877 == 186 && num878 >= 7 && num878 <= 15 && WorldGen.genRand.Next(75) == 0)
{
                                    num877 = 187;
                                    num878 = 17;
                                }
                                if (Main.wallDungeon[(int)tile7.wall] && WorldGen.genRand.Next(3) != 0)
{
                                    flag61 = true;
                                }
                                else
{
                                    if (!tile7.anyShimmer())
{
                                        WorldGen.PlaceTile(num875, num876, num877, true, false, -1, num878);
                                    }
                                    if (Main.tile[num875, num876].type == 186 || Main.tile[num875, num876].type == 187)
{
                                        flag61 = true;
                                    }
                                    if (flag61 && num877 == 186 && num878 <= 7)
{
                                        int num879 = WorldGen.genRand.Next(1, 5);
                                        for (int num880 = 0; num880 < num879; num880++)
{
                                            int num881 = num875 + WorldGen.genRand.Next(-10, 11);
                                            int num882 = num876 - WorldGen.genRand.Next(5);
                                            if (!Main.tile[num881, num882].active())
{
                                                while (!Main.tile[num881, num882 + 1].active() && num882 < Main.maxTilesY - 5)
{
                                                    num882++;
                                                }
                                                int num883 = WorldGen.genRand.Next(12, 36);
                                                WorldGen.PlaceSmallPile(num881, num882, num883, 0, 185);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                    num872++;
                }
                num871 = (float)Main.maxTilesX * 0.01f;
                int num884 = 0;
                while ((float)num884 < num871)
                {
                    if (progress != null)
                    {
                        float num885 = (float)num884 / num871;
                        progress.Set((double)(num870 + num885 * num870));
                    }
                    int num886 = WorldGen.GetPileGenerationAttempts();
                    bool flag62 = false;
                    while (!flag62 && num886 > 0)
                    {
                        num886--;
                        int num887 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num888 = WorldGen.genRand.Next(Main.maxTilesY - 300, Main.maxTilesY - 10);
                        if (!Main.tile[num887, num888].active())
{
                            int num889 = 186;
                            while (!Main.tile[num887, num888 + 1].active() && num888 < Main.maxTilesY - 5)
{
                                num888++;
                            }
                            Tile tile9 = Main.tile[num887, num888];
                            Tile tile10 = Main.tile[num887, num888 + 1];
                            if (tile10.active())
{
                                int num890 = WorldGen.genRand.Next(22);
                                if (num890 >= 16 && num890 <= 22)
{
                                    num890 = WorldGen.genRand.Next(22);
                                }
                                if (num888 > Main.maxTilesY - 300 || Main.wallDungeon[(int)tile9.wall] || tile10.type == 30 || tile10.type == 19)
{
                                    num890 = WorldGen.genRand.Next(7);
                                }
                                if ((tile10.type == 57 || tile10.type == 58) && WorldGen.genRand.Next(3) < 2)
{
                                    num889 = 187;
                                    num890 = WorldGen.genRand.Next(6, 9);
                                }
                                if (tile10.type == 147 || tile10.type == 161 || tile10.type == 162)
{
                                    num890 = WorldGen.genRand.Next(26, 32);
                                }
                                WorldGen.PlaceTile(num887, num888, num889, true, false, -1, num890);
                                if (Main.tile[num887, num888].type == 186 || Main.tile[num887, num888].type == 187)
{
                                    flag62 = true;
                                }
                                if (flag62 && num889 == 186 && num890 <= 7)
{
                                    int num891 = WorldGen.genRand.Next(1, 5);
                                    for (int num892 = 0; num892 < num891; num892++)
{
                                        int num893 = num887 + WorldGen.genRand.Next(-10, 11);
                                        int num894 = num888 - WorldGen.genRand.Next(5);
                                        if (!Main.tile[num893, num894].active())
{
                                            while (!Main.tile[num893, num894 + 1].active() && num894 < Main.maxTilesY - 5)
{
                                                num894++;
                                            }
                                            int num895 = WorldGen.genRand.Next(12, 36);
                                            WorldGen.PlaceSmallPile(num893, num894, num895, 0, 185);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    num884++;
                }
                num871 = (float)Main.maxTilesX * 0.03f;
                int num896 = 0;
                while ((float)num896 < num871)
                {
                    if (progress != null)
                    {
                        float num897 = (float)num896 / num871;
                        progress.Set((double)(num870 * 2f + num897 * num870));
                    }
                    int num898 = WorldGen.GetPileGenerationAttempts();
                    bool flag63 = false;
                    while (!flag63 && num898 > 0)
                    {
                        num898--;
                        int num899 = 186;
                        int num900 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num901 = WorldGen.genRand.Next(10, (int)Main.worldSurface);
                        while (WorldGen.oceanDepths(num900, num901))
{
                            num900 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                            num901 = WorldGen.genRand.Next(10, (int)Main.worldSurface);
                        }
                        if (!Main.tile[num900, num901].active())
{
                            while (!Main.tile[num900, num901 + 1].active() && num901 < Main.maxTilesY - 5)
{
                                num901++;
                            }
                            Tile tile11 = Main.tile[num900, num901];
                            Tile tile12 = Main.tile[num900, num901 + 1];
                            if (tile12.active())
{
                                int num902 = WorldGen.genRand.Next(7, 13);
                                if (num901 > Main.maxTilesY - 300 || Main.wallDungeon[(int)tile11.wall] || tile12.type == 30 || tile12.type == 19 || tile12.type == 25 || tile12.type == 204 || tile12.type == 234 || tile12.type == 112 || (tile12.type >= 0 && Main.tileDungeon[(int)tile12.type]))
{
                                    num902 = -1;
                                }
                                if (tile12.type == 147 || tile12.type == 161 || tile12.type == 162)
{
                                    num902 = WorldGen.genRand.Next(26, 32);
                                }
                                if (tile12.type == 53)
{
                                    num899 = 187;
                                    num902 = WorldGen.genRand.Next(52, 55);
                                }
                                if (tile12.type == 2 || (Main.tile[num900 - 1, num901 + 1].active() && Main.tile[num900 - 1, num901 + 1].type == 2) || (Main.tile[num900 + 1, num901 + 1].active() && Main.tile[num900 + 1, num901 + 1].type == 2))
{
                                    num899 = 187;
                                    num902 = WorldGen.genRand.Next(14, 17);
                                }
                                if (tile12.type == 151 || tile12.type == 274)
{
                                    num899 = 186;
                                    num902 = WorldGen.genRand.Next(7);
                                }
                                if (num902 >= 0)
{
                                    WorldGen.PlaceTile(num900, num901, num899, true, false, -1, num902);
                                }
                                if ((int)Main.tile[num900, num901].type == num899)
{
                                    flag63 = true;
                                }
                            }
                        }
                    }
                    num896++;
                }
                num871 = (float)Main.maxTilesX * 0.0035f;
                int num903 = 0;
                while ((float)num903 < num871)
                {
                    if (progress != null)
                    {
                        float num904 = (float)num903 / num871;
                        progress.Set((double)(num870 * 3f + num904 * num870));
                    }
                    int num905 = WorldGen.GetPileGenerationAttempts();
                    bool flag64 = false;
                    while (!flag64 && num905 > 0)
                    {
                        num905--;
                        int num906 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num907 = WorldGen.genRand.Next(10, (int)Main.worldSurface);
                        if (!Main.tile[num906, num907].active() && Main.tile[num906, num907].wall > 0)
{
                            int num908 = 186;
                            while (!Main.tile[num906, num907 + 1].active() && num907 < Main.maxTilesY - 5)
{
                                num907++;
                            }
                            Tile tile13 = Main.tile[num906, num907];
                            Tile tile14 = Main.tile[num906, num907 + 1];
                            if (tile14.active())
{
                                int num909 = WorldGen.genRand.Next(7, 13);
                                if (num907 > Main.maxTilesY - 300 || Main.wallDungeon[(int)tile13.wall] || tile14.type == 30 || tile14.type == 19 || (tile14.type >= 0 && Main.tileDungeon[(int)tile14.type]))
{
                                    num909 = -1;
                                }
                                if (tile14.type == 25)
{
                                    num909 = WorldGen.genRand.Next(7);
                                }
                                if (tile14.type == 147 || tile14.type == 161 || tile14.type == 162)
{
                                    num909 = WorldGen.genRand.Next(26, 32);
                                }
                                if (tile14.type == 2 || (Main.tile[num906 - 1, num907 + 1].active() && Main.tile[num906 - 1, num907 + 1].type == 2) || (Main.tile[num906 + 1, num907 + 1].active() && Main.tile[num906 + 1, num907 + 1].type == 2))
{
                                    num908 = 187;
                                    num909 = WorldGen.genRand.Next(14, 17);
                                }
                                if (tile14.type == 151 || tile14.type == 274)
{
                                    num908 = 186;
                                    num909 = WorldGen.genRand.Next(7);
                                }
                                if (num909 >= 0)
{
                                    WorldGen.PlaceTile(num906, num907, num908, true, false, -1, num909);
                                }
                                if ((int)Main.tile[num906, num907].type == num908)
{
                                    flag64 = true;
                                }
                                if (flag64 && num909 <= 7)
{
                                    int num910 = WorldGen.genRand.Next(1, 5);
                                    for (int num911 = 0; num911 < num910; num911++)
{
                                        int num912 = num906 + WorldGen.genRand.Next(-10, 11);
                                        int num913 = num907 - WorldGen.genRand.Next(5);
                                        if (!Main.tile[num912, num913].active())
{
                                            while (!Main.tile[num912, num913 + 1].active() && num913 < Main.maxTilesY - 5)
{
                                                num913++;
                                            }
                                            int num914 = WorldGen.genRand.Next(12, 36);
                                            WorldGen.PlaceSmallPile(num912, num913, num914, 0, 185);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    num903++;
                }
                num871 = (float)Main.maxTilesX * 0.6f;
                int num915 = 0;
                while ((float)num915 < num871)
                {
                    if (progress != null)
                    {
                        float num916 = (float)num915 / num871;
                        progress.Set((double)(num870 * 4f + num916 * num870));
                    }
                    int num917 = WorldGen.GetPileGenerationAttempts();
                    bool flag65 = false;
                    while (!flag65 && num917 > 0)
                    {
                        num917--;
                        int num918 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num919 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                        if (Main.tile[num918, num919].wall == 87 && WorldGen.genRand.Next(2) == 0)
{
                            num918 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                            num919 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                        }
                        while (WorldGen.oceanDepths(num918, num919))
{
                            num918 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                            num919 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 20);
                        }
                        if (!Main.tile[num918, num919].active())
{
                            while (!Main.tile[num918, num919 + 1].active() && num919 < Main.maxTilesY - 5)
{
                                num919++;
                            }
                            Tile tile15 = Main.tile[num918, num919];
                            Tile tile16 = Main.tile[num918, num919 + 1];
                            if (tile16.active())
{
                                int num920 = WorldGen.genRand.Next(2);
                                int num921 = WorldGen.genRand.Next(36);
                                if (num921 >= 28 && num921 <= 35)
{
                                    num921 = WorldGen.genRand.Next(36);
                                }
                                if (num920 == 1)
{
                                    num921 = WorldGen.genRand.Next(25);
                                    if (num921 >= 16 && num921 <= 24)
{
                                        num921 = WorldGen.genRand.Next(25);
                                    }
                                }
                                if (num919 > Main.maxTilesY - 300)
{
                                    if (num920 == 0)
{
                                        num921 = WorldGen.genRand.Next(12, 28);
                                    }
                                    if (num920 == 1)
{
                                        num921 = WorldGen.genRand.Next(6, 16);
                                    }
                                }
                                if (Main.wallDungeon[(int)tile15.wall] || tile15.wall == 87 || tile16.type == 30 || tile16.type == 19 || tile16.type == 25 || tile16.type == 203)
{
                                    if (num920 == 0 && num921 < 12)
{
                                        num921 += 12;
                                    }
                                    if (num920 == 1 && num921 < 6)
{
                                        num921 += 6;
                                    }
                                    if (num920 == 1 && num921 >= 17)
{
                                        num921 -= 10;
                                    }
                                }
                                if (tile16.type == 147 || tile16.type == 161 || tile16.type == 162)
{
                                    if (num920 == 0 && num921 < 12)
{
                                        num921 += 36;
                                    }
                                    if (num920 == 1 && num921 >= 20)
{
                                        num921 += 6;
                                    }
                                    if (num920 == 1 && num921 < 6)
{
                                        num921 += 25;
                                    }
                                }
                                if (tile15.liquid <= 0 && (tile16.type == 53 || tile16.type == 397 || tile16.type == 396))
{
                                    if (num920 == 0)
{
                                        num921 = WorldGen.genRand.Next(73, 78);
                                    }
                                    if (num920 == 1)
{
                                        num921 = WorldGen.genRand.Next(62, 65);
                                    }
                                }
                                if (tile16.type == 151 || tile16.type == 274)
{
                                    if (num920 == 0)
{
                                        num921 = WorldGen.genRand.Next(12, 28);
                                    }
                                    if (num920 == 1)
{
                                        num921 = WorldGen.genRand.Next(12, 19);
                                    }
                                }
                                if (tile16.type == 368)
{
                                    if (num920 == 0)
{
                                        num921 = WorldGen.genRand.Next(60, 66);
                                    }
                                    if (num920 == 1)
{
                                        num921 = WorldGen.genRand.Next(47, 53);
                                    }
                                }
                                if (tile16.type == 367)
{
                                    if (num920 == 0)
{
                                        num921 = WorldGen.genRand.Next(66, 72);
                                    }
                                    if (num920 == 1)
{
                                        num921 = WorldGen.genRand.Next(53, 59);
                                    }
                                }
                                if (tile16.type >= 0 && Main.tileDungeon[(int)tile16.type])
{
                                    flag65 = false;
                                }
                                else if (Main.wallDungeon[(int)tile15.wall] && WorldGen.genRand.Next(3) != 0)
{
                                    flag65 = true;
                                }
                                else if (!tile15.anyShimmer())
{
                                    flag65 = WorldGen.PlaceSmallPile(num918, num919, num921, num920, 185);
                                }
                                if (flag65 && num920 == 1 && num921 >= 6 && num921 <= 15)
{
                                    int num922 = WorldGen.genRand.Next(1, 5);
                                    for (int num923 = 0; num923 < num922; num923++)
{
                                        int num924 = num918 + WorldGen.genRand.Next(-10, 11);
                                        int num925 = num919 - WorldGen.genRand.Next(5);
                                        if (!Main.tile[num924, num925].active())
{
                                            while (!Main.tile[num924, num925 + 1].active() && num925 < Main.maxTilesY - 5)
{
                                                num925++;
                                            }
                                            int num926 = WorldGen.genRand.Next(12, 36);
                                            WorldGen.PlaceSmallPile(num924, num925, num926, 0, 185);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    num915++;
                }
                num871 = (float)Main.maxTilesX * 0.02f;
                int num927 = 0;
                while ((float)num927 < num871)
                {
                    if (progress != null)
                    {
                        float num928 = (float)num927 / num871;
                        progress.Set((double)(num870 * 5f + num928 * num870));
                    }
                    int num929 = WorldGen.GetPileGenerationAttempts();
                    bool flag66 = false;
                    while (!flag66 && num929 > 0)
                    {
                        num929--;
                        int num930 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num931 = WorldGen.genRand.Next(15, (int)Main.worldSurface);
                        while (WorldGen.oceanDepths(num930, num931))
{
                            num930 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                            num931 = WorldGen.genRand.Next(15, (int)Main.worldSurface);
                        }
                        if (!Main.tile[num930, num931].active())
{
                            while (!Main.tile[num930, num931 + 1].active() && num931 < Main.maxTilesY - 5)
{
                                num931++;
                            }
                            Tile tile17 = Main.tile[num930, num931];
                            Tile tile18 = Main.tile[num930, num931 + 1];
                            if (tile18.active())
{
                                int num932 = WorldGen.genRand.Next(2);
                                int num933 = WorldGen.genRand.Next(11);
                                if (num932 == 1)
{
                                    num933 = WorldGen.genRand.Next(5);
                                }
                                if (tile18.type == 147 || tile18.type == 161 || tile18.type == 162)
{
                                    if (num932 == 0 && num933 < 12)
{
                                        num933 += 36;
                                    }
                                    if (num932 == 1 && num933 >= 20)
{
                                        num933 += 6;
                                    }
                                    if (num932 == 1 && num933 < 6)
{
                                        num933 += 25;
                                    }
                                }
                                if (tile17.liquid <= 0 && (tile18.type == 53 || tile18.type == 397 || tile18.type == 396))
{
                                    if (num932 == 0)
{
                                        num933 = WorldGen.genRand.Next(73, 77);
                                    }
                                    if (num932 == 1)
{
                                        num933 = WorldGen.genRand.Next(62, 65);
                                    }
                                }
                                if (tile18.type == 2 && num932 == 1)
{
                                    num933 = WorldGen.genRand.Next(38, 41);
                                }
                                if (tile18.type == 151 || tile18.type == 274)
{
                                    if (num932 == 0)
{
                                        num933 = WorldGen.genRand.Next(12, 28);
                                    }
                                    if (num932 == 1)
{
                                        num933 = WorldGen.genRand.Next(12, 19);
                                    }
                                }
                                if (!Main.wallDungeon[(int)tile17.wall] && tile18.type != 30 && tile18.type != 19 && tile18.type != 41 && tile18.type != 43 && tile18.type != 44 && tile18.type != 481 && tile18.type != 482 && tile18.type != 483 && tile18.type != 45 && tile18.type != 46 && tile18.type != 47 && tile18.type != 175 && tile18.type != 176 && tile18.type != 177 && tile18.type != 25 && tile18.type != 203 && (tile18.type < 0 || !Main.tileDungeon[(int)tile18.type]))
{
                                    flag66 = WorldGen.PlaceSmallPile(num930, num931, num933, num932, 185);
                                }
                            }
                        }
                    }
                    num927++;
                }
                num871 = (float)Main.maxTilesX * 0.15f;
                int num934 = 0;
                while ((float)num934 < num871)
                {
                    if (progress != null)
                    {
                        float num935 = (float)num934 / num871;
                        progress.Set((double)(num870 * 6f + num935 * num870));
                    }
                    int num936 = WorldGen.GetPileGenerationAttempts();
                    bool flag67 = false;
                    while (!flag67 && num936 > 0)
                    {
                        num936--;
                        int num937 = WorldGen.genRand.Next(25, Main.maxTilesX - 25);
                        int num938 = WorldGen.genRand.Next(15, (int)Main.worldSurface);
                        if (!Main.tile[num937, num938].active())
{
                            if (Main.tile[num937, num938].wall != 2)
{
                                if (Main.tile[num937, num938].wall != 40)
{
                                    continue;
                                }
                            }
                            while (!Main.tile[num937, num938 + 1].active() && num938 < Main.maxTilesY - 5)
{
                                num938++;
                            }
                            Tile tile19 = Main.tile[num937, num938];
                            Tile tile20 = Main.tile[num937, num938 + 1];
                            if (tile20.active())
{
                                int num939 = WorldGen.genRand.Next(2);
                                int num940 = WorldGen.genRand.Next(11);
                                if (num939 == 1)
{
                                    num940 = WorldGen.genRand.Next(5);
                                }
                                if (tile20.type == 147 || tile20.type == 161 || tile20.type == 162)
{
                                    if (num939 == 0 && num940 < 12)
{
                                        num940 += 36;
                                    }
                                    if (num939 == 1 && num940 >= 20)
{
                                        num940 += 6;
                                    }
                                    if (num939 == 1 && num940 < 6)
{
                                        num940 += 25;
                                    }
                                }
                                if (tile19.liquid <= 0 && (tile20.type == 53 || tile20.type == 397 || tile20.type == 396))
{
                                    if (num939 == 0)
{
                                        num940 = WorldGen.genRand.Next(73, 77);
                                    }
                                    if (num939 == 1)
{
                                        num940 = WorldGen.genRand.Next(62, 65);
                                    }
                                }
                                if (tile20.type == 2 && num939 == 1)
{
                                    num940 = WorldGen.genRand.Next(38, 41);
                                }
                                if (tile20.type == 151 || tile20.type == 274)
{
                                    if (num939 == 0)
{
                                        num940 = WorldGen.genRand.Next(12, 28);
                                    }
                                    if (num939 == 1)
{
                                        num940 = WorldGen.genRand.Next(12, 19);
                                    }
                                }
                                if ((tile19.liquid != 255 || tile20.type != 53 || tile19.wall != 0) && !Main.wallDungeon[(int)tile19.wall] && tile20.type != 30 && tile20.type != 19 && tile20.type != 41 && tile20.type != 43 && tile20.type != 44 && tile20.type != 481 && tile20.type != 482 && tile20.type != 483 && tile20.type != 45 && tile20.type != 46 && tile20.type != 47 && tile20.type != 175 && tile20.type != 176 && tile20.type != 177 && tile20.type != 25 && tile20.type != 203 && (tile20.type < 0 || !Main.tileDungeon[(int)tile20.type]))
{
                                    flag67 = WorldGen.PlaceSmallPile(num937, num938, num940, num939, 185);
                                }
                            }
                        }
                    }
                    num934++;
                }
                progress.Set(1.0);
                Main.tileSolid[190] = true;
                Main.tileSolid[192] = true;
                Main.tileSolid[196] = true;
                Main.tileSolid[189] = true;
                Main.tileSolid[717] = true;
                Main.tileSolid[718] = true;
                Main.tileSolid[719] = true;
                Main.tileSolid[202] = true;
                Main.tileSolid[225] = true;
                Main.tileSolid[460] = true;
                Main.tileSolid[379] = true;
                WorldGen.SetBoulderSolidity(true);
            });
            WorldGen.AddGenerationPass(GenPassNameID.SpawnPoint, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.skyblockWorldGen)
                {
                    int spawnTileX = Main.spawnTileX;
                    int num941 = Main.spawnTileY;
                    int num942 = 20;
                    while (!WorldGen.SolidTile3(spawnTileX, num941))
                    {
                        if (num941 >= Main.maxTilesY - 1 - num942)
{
                            break;
                        }
                        num941++;
                    }
                    while (WorldGen.SolidTile3(spawnTileX, num941) && num941 > num942)
                    {
                        num941--;
                    }
                    num941++;
                    if (Math.Abs(num941 - Main.spawnTileY) <= num942)
                    {
                        Main.spawnTileX = spawnTileX;
                        Main.spawnTileY = num941;
                    }
                    return;
                }
                Main.tileSolid[379] = false;
                progress.Set(1.0);
                int num943 = 5;
                bool flag68 = true;
                int num944 = Main.maxTilesX / 2;
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    int num945 = Main.maxTilesY / 2;
                    Main.spawnTileX = num944;
                    Main.spawnTileY = num945;
                    int num946 = 300;
                    int num947 = 200;
                    bool flag69 = false;
                    int num948 = 1000;
                    int num949;
                    int num950;
                    for (;;)
                    {
                        num948--;
                        if (num948 <= 0)
{
                            goto IL_015C;
                        }
                        num949 = num944 - num946 + WorldGen.genRand.Next(num946 * 2);
                        num950 = num945 - num947 + WorldGen.genRand.Next(num947 * 2);
                        if (WorldGen.InWorld(num949, num950, 10))
{
                            Tile tile21 = Main.tile[num949, num950];
                            if (!tile21.active() && tile21.liquid <= 0 && Player.Spawn_IsAreaValidSpawn(num949, num950, true))
{
                                break;
                            }
                        }
                    }
                    Main.spawnTileX = num949;
                    Main.spawnTileY = num950;
                    flag69 = true;
                    IL_015C:
                    if (!flag69)
                    {
                        Main.spawnTileX = num944;
                        Main.spawnTileY = num945;
                        Player.Spawn_ForceClearArea(num944, num945);
                    }
                }
                else
                {
                    if (SpecialSeedFeatures.SpawnOnBeach)
                    {
                        int num951 = GenVars.beachBordersWidth + 15;
                        bool flag70 = GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left;
                        if (SpecialSeedFeatures.SpawnOnBeachOnDungeonSide)
{
                            if (flag70)
{
                                num944 = num951;
                            }
                            else
{
                                num944 = Main.maxTilesX - num951;
                            }
                        }
                        else if (WorldGen.genRand.Next(2) == 0)
{
                            num944 = num951;
                        }
                        else
{
                            num944 = Main.maxTilesX - num951;
                        }
                    }
                    while (flag68)
                    {
                        int num952 = num944 + WorldGen.genRand.Next(-num943, num943 + 1);
                        for (int num953 = 0; num953 < Main.maxTilesY; num953++)
{
                            if (Main.tile[num952, num953].active() && Main.tile[num952, num953].type != 379)
{
                                Main.spawnTileX = num952;
                                Main.spawnTileY = num953;
                                break;
                            }
                        }
                        flag68 = false;
                        num943++;
                        if ((double)Main.spawnTileY > Main.worldSurface)
{
                            flag68 = true;
                        }
                        if (Main.tile[Main.spawnTileX, Main.spawnTileY - 1].liquid > 0 || Main.tile[Main.spawnTileX, Main.spawnTileY - 2].liquid > 0 || Main.tile[Main.spawnTileX, Main.spawnTileY - 3].liquid > 0)
{
                            flag68 = true;
                        }
                        if (WorldGen.IsTileNearby(Main.spawnTileX, Main.spawnTileY, 379, 10))
{
                            flag68 = true;
                        }
                    }
                    int num954 = 10;
                    while ((double)Main.spawnTileY > Main.worldSurface)
                    {
                        int num955 = WorldGen.genRand.Next(num944 - num954, num944 + num954);
                        for (int num956 = 0; num956 < Main.maxTilesY; num956++)
{
                            if (Main.tile[num955, num956].active() && Main.tile[num955, num956].type != 379)
{
                                Main.spawnTileX = num955;
                                Main.spawnTileY = num956;
                                break;
                            }
                        }
                        num954++;
                    }
                }
                if (WorldGen.remixWorldGen)
                {
                    Main.spawnTileX = Main.maxTilesX / 2;
                    int num957 = Main.maxTilesY - 10;
                    while (WorldGen.SolidTile(Main.spawnTileX, num957, false))
                    {
                        num957--;
                    }
                    Main.spawnTileY = num957 + 1;
                }
                Main.tileSolid[379] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.SurfaceDirtWallsToGrassWalls, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                WorldGen.maxTileCount = 3500;
                progress.Set(1.0);
                for (int num958 = 50; num958 < Main.maxTilesX - 50; num958++)
                {
                    int num959 = 0;
                    while ((double)num959 < Main.worldSurface - 10.0)
                    {
                        if (WorldGen.genRand.Next(4) == 0)
{
                            bool flag71 = false;
                            int num960 = -1;
                            int num961 = -1;
                            if (Main.tile[num958, num959].active() && Main.tile[num958, num959].type == 2 && (Main.tile[num958, num959].wall == 2 || Main.tile[num958, num959].wall == 63))
{
                                for (int num962 = num958 - 1; num962 <= num958 + 1; num962++)
{
                                    for (int num963 = num959 - 1; num963 <= num959 + 1; num963++)
{
                                        if (Main.tile[num962, num963].wall == 0 && !WorldGen.SolidTile(num962, num963, false))
{
                                            flag71 = true;
                                        }
                                    }
                                }
                                if (flag71)
{
                                    for (int num964 = num958 - 1; num964 <= num958 + 1; num964++)
{
                                        for (int num965 = num959 - 1; num965 <= num959 + 1; num965++)
{
                                            if ((Main.tile[num964, num965].wall == 2 || Main.tile[num964, num965].wall == 15) && !WorldGen.SolidTile(num964, num965, false))
{
                                                num960 = num964;
                                                num961 = num965;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag71 && num960 > -1 && num961 > -1 && WorldGen.countDirtTiles(num960, num961) < WorldGen.maxTileCount)
{
                                try
{
                                    int num966 = 3;
                                    if (WorldGen.getGoodWorldGen)
{
                                        num966 = 10;
                                    }
                                    ushort num967 = 63;
                                    if (WorldGen.dontStarveWorldGen && WorldGen.genRand.Next(num966) != 0 && !WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
{
                                        num967 = 62;
                                    }
                                    WorldGen.Spread.Wall2(num960, num961, (int)num967);
                                }
                                catch
{
                                }
                            }
                        }
                        num959++;
                    }
                }
                for (int num968 = 5; num968 < Main.maxTilesX - 5; num968++)
                {
                    int num969 = 10;
                    while ((double)num969 < Main.worldSurface - 1.0)
                    {
                        if (Main.tile[num968, num969].wall == 63 && WorldGen.genRand.Next(10) == 0)
{
                            Main.tile[num968, num969].wall = 65;
                        }
                        if (Main.tile[num968, num969].active() && Main.tile[num968, num969].type == 0)
{
                            bool flag72 = false;
                            for (int num970 = num968 - 1; num970 <= num968 + 1; num970++)
{
                                for (int num971 = num969 - 1; num971 <= num969 + 1; num971++)
{
                                    if (Main.tile[num970, num971].wall == 63 || Main.tile[num970, num971].wall == 65)
{
                                        flag72 = true;
                                        break;
                                    }
                                }
                            }
                            if (flag72)
{
                                WorldGen.SpreadGrass(num968, num969, 0, 2, true, default(TileColorCache));
                            }
                        }
                        num969++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SpawnStarterNPCs, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                progress.Set(1.0);
                if (Main.tenthAnniversaryWorld)
                {
                    Point point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX, Main.spawnTileY);
                    int num972;
                    if (WorldGen.SecretSeed.worldIsInfected.Enabled)
                    {
                        num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 20, 0, 0f, 0f, 0f, 0f, 255);
                        if (WorldGen.remixWorldGen)
{
                            NPC.savedTaxCollector = true;
                        }
                    }
                    else if (WorldGen.remixWorldGen)
                    {
                        num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 441, 0, 0f, 0f, 0f, 0f, 255);
                        NPC.savedTaxCollector = true;
                    }
                    else if (WorldGen.notTheBees)
                    {
                        num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 228, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    else
                    {
                        num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 22, 0, 0f, 0f, 0f, 0f, 255);
                    }
                    Main.npc[num972].homeTileX = Main.spawnTileX;
                    Main.npc[num972].homeTileY = Main.spawnTileY;
                    Main.npc[num972].direction = 1;
                    Main.npc[num972].homeless = true;
                    if (WorldGen.SecretSeed.worldIsInfected.Enabled)
                    {
                        Main.npc[num972].GivenName = Language.GetTextValue("Lilith");
                        Main.npc[num972].townNpcVariationIndex = 1;
                    }
                    else if (WorldGen.notTheBees && !WorldGen.remixWorldGen)
                    {
                        Main.npc[num972].GivenName = Language.GetTextValue("SkeletonMerchantNames.Victor");
                    }
                    else
                    {
                        Main.npc[num972].GivenName = Language.GetTextValue("GuideNames.Andrew");
                    }
                    if (!WorldGen.skyblockWorldGen)
                    {
                        BirthdayParty.CelebratingNPCs.Add(num972);
                        if (WorldGen.dontStarveWorldGen && !WorldGen.remixWorldGen)
{
                            point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX + 2, Main.spawnTileY);
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 124, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].homeTileX = point6.X;
                            Main.npc[num972].homeTileY = point6.Y;
                            Main.npc[num972].direction = -1;
                            Main.npc[num972].homeless = true;
                            Main.npc[num972].GivenName = Language.GetTextValue("MechanicNames.Korrie");
                            BirthdayParty.CelebratingNPCs.Add(num972);
                        }
                        else
{
                            point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX + 2, Main.spawnTileY);
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 178, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].homeTileX = point6.X;
                            Main.npc[num972].homeTileY = point6.Y;
                            Main.npc[num972].direction = -1;
                            Main.npc[num972].homeless = true;
                            Main.npc[num972].GivenName = Language.GetTextValue("SteampunkerNames.Whitney");
                            BirthdayParty.CelebratingNPCs.Add(num972);
                        }
                        if (WorldGen.notTheBees && !WorldGen.remixWorldGen)
{
                            point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX - 2, Main.spawnTileY);
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 17, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].homeTileX = point6.X;
                            Main.npc[num972].homeTileY = point6.Y;
                            Main.npc[num972].direction = 1;
                            Main.npc[num972].homeless = true;
                            Main.npc[num972].GivenName = Language.GetTextValue("AnglerNames.Charles");
                            BirthdayParty.CelebratingNPCs.Add(num972);
                            NPC.unlockedMerchantSpawn = true;
                        }
                        else
{
                            point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX - 2, Main.spawnTileY);
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 663, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].homeTileX = point6.X;
                            Main.npc[num972].homeTileY = point6.Y;
                            Main.npc[num972].direction = 1;
                            Main.npc[num972].homeless = true;
                            Main.npc[num972].GivenName = Language.GetTextValue("PrincessNames.Yorai");
                            BirthdayParty.CelebratingNPCs.Add(num972);
                            NPC.unlockedPrincessSpawn = true;
                        }
                        if (WorldGen.drunkWorldGen)
{
                            point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX + 4, Main.spawnTileY);
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 227, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].homeTileX = point6.X;
                            Main.npc[num972].homeTileY = point6.Y;
                            Main.npc[num972].direction = -1;
                            Main.npc[num972].homeless = true;
                            Main.npc[num972].GivenName = Language.GetTextValue("PainterNames.Jim");
                            BirthdayParty.CelebratingNPCs.Add(num972);
                        }
                        else
{
                            point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX + 4, Main.spawnTileY);
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 208, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].homeTileX = point6.X;
                            Main.npc[num972].homeTileY = point6.Y;
                            Main.npc[num972].direction = -1;
                            Main.npc[num972].homeless = true;
                            Main.npc[num972].GivenName = Language.GetTextValue("PartyGirlNames.Amanda");
                            BirthdayParty.CelebratingNPCs.Add(num972);
                            NPC.unlockedPartyGirlSpawn = true;
                        }
                        point6 = WorldGen.GetAdjustedFloorPosition(Main.spawnTileX - 4, Main.spawnTileY);
                        if (Main.remixWorld)
{
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 681, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].GivenName = Language.GetTextValue("SlimeNames_Rainbow.Slimestar");
                            NPC.unlockedSlimeRainbowSpawn = true;
                        }
                        else if (Main.drunkWorld)
{
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 680, 0, 0f, 0f, 0f, 0f, 255);
                            Main.npc[num972].GivenName = Language.GetTextValue("SlimeNames_Purple.Slimefors");
                            NPC.unlockedSlimePurpleSpawn = true;
                        }
                        else
{
                            num972 = NPC.NewNPC(new EntitySource_WorldGen(), point6.X * 16, point6.Y * 16, 656, 0, 0f, 0f, 0f, 0f, 255);
                            NPC.boughtBunny = true;
                            Main.npc[num972].townNpcVariationIndex = 1;
                        }
                        Main.npc[num972].homeTileX = point6.X;
                        Main.npc[num972].homeTileY = point6.Y;
                        Main.npc[num972].direction = 1;
                        Main.npc[num972].homeless = true;
                        return;
                    }
                }
                else if (WorldGen.SecretSeed.worldIsInfected.Enabled)
                {
                    int num973 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 20, 0, 0f, 0f, 0f, 0f, 255);
                    Main.npc[num973].homeTileX = Main.spawnTileX;
                    Main.npc[num973].homeTileY = Main.spawnTileY;
                    Main.npc[num973].direction = 1;
                    Main.npc[num973].homeless = true;
                    Main.npc[num973].townNpcVariationIndex = 1;
                    if (WorldGen.remixWorldGen)
                    {
                        NPC.savedTaxCollector = true;
                        return;
                    }
                }
                else
                {
                    if (Main.vampireSeed)
                    {
                        int num974 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 633, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num974].homeTileX = Main.spawnTileX;
                        Main.npc[num974].homeTileY = Main.spawnTileY;
                        Main.npc[num974].direction = 1;
                        Main.npc[num974].homeless = true;
                        return;
                    }
                    if (WorldGen.remixWorldGen)
                    {
                        int num975 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 441, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num975].homeTileX = Main.spawnTileX;
                        Main.npc[num975].homeTileY = Main.spawnTileY;
                        Main.npc[num975].direction = 1;
                        Main.npc[num975].homeless = true;
                        NPC.savedTaxCollector = true;
                        return;
                    }
                    if (WorldGen.drunkWorldGen && WorldGen.dontStarveWorldGen)
                    {
                        int num976 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 124, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num976].homeTileX = Main.spawnTileX;
                        Main.npc[num976].homeTileY = Main.spawnTileY;
                        Main.npc[num976].direction = 1;
                        Main.npc[num976].homeless = true;
                        NPC.savedMech = true;
                        return;
                    }
                    if (WorldGen.notTheBees && !WorldGen.dontStarveWorldGen)
                    {
                        int num977 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 17, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num977].homeTileX = Main.spawnTileX;
                        Main.npc[num977].homeTileY = Main.spawnTileY;
                        Main.npc[num977].direction = 1;
                        Main.npc[num977].homeless = true;
                        NPC.unlockedMerchantSpawn = true;
                        return;
                    }
                    if (WorldGen.getGoodWorldGen)
                    {
                        int num978 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 38, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num978].homeTileX = Main.spawnTileX;
                        Main.npc[num978].homeTileY = Main.spawnTileY;
                        Main.npc[num978].direction = 1;
                        Main.npc[num978].homeless = true;
                        NPC.unlockedDemolitionistSpawn = true;
                        return;
                    }
                    if (WorldGen.drunkWorldGen)
                    {
                        int num979 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 208, 0, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num979].homeTileX = Main.spawnTileX;
                        Main.npc[num979].homeTileY = Main.spawnTileY;
                        Main.npc[num979].direction = 1;
                        Main.npc[num979].homeless = true;
                        NPC.unlockedPartyGirlSpawn = true;
                        return;
                    }
                    int num980 = NPC.NewNPC(new EntitySource_WorldGen(), Main.spawnTileX * 16, Main.spawnTileY * 16, 22, 0, 0f, 0f, 0f, 0f, 255);
                    Main.npc[num980].homeTileX = Main.spawnTileX;
                    Main.npc[num980].homeTileY = Main.spawnTileY;
                    Main.npc[num980].direction = 1;
                    Main.npc[num980].homeless = true;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SunflowersPart2, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[39].Value;
                double num981 = (double)Main.maxTilesX * 0.002;
                int num982 = 0;
                while ((double)num982 < num981)
                {
                    progress.Set((double)num982 / num981);
                    int num983 = Main.maxTilesX / 2;
                    int num984 = WorldGen.genRand.Next(Main.maxTilesX);
                    int num985 = num984 - WorldGen.genRand.Next(10) - 7;
                    int num986 = num984 + WorldGen.genRand.Next(10) + 7;
                    if (num985 < 0)
                    {
                        num985 = 0;
                    }
                    if (num986 > Main.maxTilesX - 1)
                    {
                        num986 = Main.maxTilesX - 1;
                    }
                    int num987 = 1;
                    int num988 = (int)Main.worldSurface - 1;
                    for (int num989 = num985; num989 < num986; num989++)
                    {
                        for (int num990 = num987; num990 < num988; num990++)
{
                            if (Main.tile[num989, num990].type == 2 && Main.tile[num989, num990].active() && !Main.tile[num989, num990 - 1].active())
{
                                WorldGen.PlaceTile(num989, num990 - 1, 27, true, false, -1, 0);
                            }
                            if (Main.tile[num989, num990].active())
{
                                break;
                            }
                        }
                    }
                    num982++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Trees, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[40].Value;
                if (!WorldGen.drunkWorldGen && !Main.tenthAnniversaryWorld)
                {
                    int num991 = 0;
                    while ((double)num991 < (double)Main.maxTilesX * 0.003)
                    {
                        progress.Set((double)num991 / ((double)Main.maxTilesX * 0.003));
                        int num992 = WorldGen.genRand.Next(50, Main.maxTilesX - 50);
                        int num993 = WorldGen.genRand.Next(25, 50);
                        for (int num994 = num992 - num993; num994 < num992 + num993; num994++)
{
                            int num995 = 20;
                            while ((double)num995 < Main.worldSurface)
{
                                WorldGen.GrowEpicTree(num994, num995);
                                num995++;
                            }
                        }
                        num991++;
                    }
                }
                WorldGen.AddTrees(false);
            });
            WorldGen.AddGenerationPass(GenPassNameID.AlchemyHerbs, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                double num996 = (double)Main.maxTilesX * 1.7;
                if (WorldGen.remixWorldGen)
                {
                    num996 *= 5.0;
                }
                progress.Message = Lang.gen[41].Value;
                int num997 = 0;
                while ((double)num997 < num996)
                {
                    progress.Set((double)num997 / num996);
                    WorldGen.PlantAlch();
                    num997++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.DyePlants, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num998 = 0; num998 < Main.maxTilesX; num998++)
                {
                    WorldGen.plantDye(WorldGen.genRand.Next(100, Main.maxTilesX - 100), WorldGen.genRand.Next(100, Main.UnderworldLayer), false);
                }
                WorldGen.MatureTheHerbPlants();
                WorldGen.GrowGlowTulips();
                WorldGen.PlaceChilletEggs();
            });
            WorldGen.AddGenerationPass(GenPassNameID.WebsInSpiderCavesAndHoneyPlusSpeleothemsInBeehives, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num999 = 100; num999 < Main.maxTilesX - 100; num999++)
                {
                    int num1000 = (int)Main.worldSurface;
                    if (WorldGen.dontStarveWorldGen)
                    {
                        num1000 = 50;
                    }
                    for (int num1001 = num1000; num1001 < Main.maxTilesY - 100; num1001++)
                    {
                        if (Main.tile[num999, num1001].wall == 86)
{
                            if (Main.tile[num999, num1001].liquid > 0)
{
                                Main.tile[num999, num1001].honey(true);
                            }
                            if (WorldGen.genRand.Next(3) == 0)
{
                                WorldGen.PlaceTight(num999, num1001, false);
                            }
                        }
                        if (Main.tile[num999, num1001].wall == 62)
{
                            if (WorldGen.SecretSeed.Variations.noSpiderCavesILiedMoreSpiderCaves)
{
                                if (Main.tile[num999, num1001].liquid > 0)
{
                                    Main.tile[num999, num1001].honey(true);
                                }
                            }
                            else
{
                                Main.tile[num999, num1001].liquid = 0;
                                Main.tile[num999, num1001].lava(false);
                            }
                        }
                        if (Main.tile[num999, num1001].wall == 62 && !Main.tile[num999, num1001].active() && WorldGen.genRand.Next(10) != 0)
{
                            int num1002 = WorldGen.genRand.Next(2, 5);
                            int num1003 = num999 - num1002;
                            int num1004 = num999 + num1002;
                            int num1005 = num1001 - num1002;
                            int num1006 = num1001 + num1002;
                            bool flag73 = false;
                            for (int num1007 = num1003; num1007 <= num1004; num1007++)
{
                                for (int num1008 = num1005; num1008 <= num1006; num1008++)
{
                                    if (WorldGen.SolidTile(num1007, num1008, false))
{
                                        flag73 = true;
                                        break;
                                    }
                                }
                            }
                            if (flag73)
{
                                WorldGen.PlaceTile(num999, num1001, 51, true, false, -1, 0);
                                WorldGen.TileFrame(num999, num1001, false, false);
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.GrassPlantsEvilPlantsAndPumpkinsOnSurface, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[42].Value;
                if (WorldGen.SecretSeed.halloweenGen.Enabled || WorldGen.SecretSeed.endlessHalloween.Enabled)
                {
                    for (int num1009 = 40; num1009 < Main.maxTilesX - 40; num1009++)
                    {
                        int num1010 = 50;
                        while ((double)num1010 < Main.worldSurface)
{
                            if (Main.tile[num1009, num1010].active() && Main.tile[num1009, num1010].type == 2 && WorldGen.genRand.Next(15) == 0)
{
                                WorldGen.PlacePumpkin(num1009, num1010 - 1);
                                int num1011 = WorldGen.genRand.Next(5);
                                for (int num1012 = 0; num1012 < num1011; num1012++)
{
                                    WorldGen.GrowPumpkin(num1009, num1010 - 1, 254);
                                }
                            }
                            num1010++;
                        }
                    }
                }
                for (int num1013 = 0; num1013 < Main.maxTilesX; num1013++)
                {
                    progress.Set((double)num1013 / (double)Main.maxTilesX);
                    for (int num1014 = 1; num1014 < Main.maxTilesY; num1014++)
                    {
                        if (Main.tile[num1013, num1014].type == 2 && Main.tile[num1013, num1014].nactive())
{
                            if (!Main.tile[num1013, num1014 - 1].active())
{
                                WorldGen.PlaceTile(num1013, num1014 - 1, 3, true, false, -1, 0);
                                Main.tile[num1013, num1014 - 1].CopyPaintAndCoating(Main.tile[num1013, num1014]);
                            }
                        }
                        else if (Main.tile[num1013, num1014].type == 23 && Main.tile[num1013, num1014].nactive())
{
                            if (!Main.tile[num1013, num1014 - 1].active())
{
                                WorldGen.PlaceTile(num1013, num1014 - 1, 24, true, false, -1, 0);
                            }
                        }
                        else if (Main.tile[num1013, num1014].type == 199 && Main.tile[num1013, num1014].nactive())
{
                            if (!Main.tile[num1013, num1014 - 1].active())
{
                                WorldGen.PlaceTile(num1013, num1014 - 1, 201, true, false, -1, 0);
                            }
                        }
                        else if (Main.tile[num1013, num1014].type == 633 && Main.tile[num1013, num1014].nactive() && !Main.tile[num1013, num1014 - 1].active())
{
                            WorldGen.PlaceTile(num1013, num1014 - 1, 637, true, false, -1, 0);
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.GlowingMushroomPlantsUndergroundAndJunglePlants, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num1015 = 5; num1015 < Main.maxTilesX - 5; num1015++)
                {
                    for (int num1016 = 5; num1016 < Main.maxTilesY - 5; num1016++)
                    {
                        if (Main.tile[num1015, num1016].active())
{
                            if (num1016 >= (int)Main.worldSurface && Main.tile[num1015, num1016].type == 70 && !Main.tile[num1015, num1016 - 1].active())
{
                                WorldGen.TryGrowingTreeByType(5, num1015, num1016, 0, false);
                                if (!Main.tile[num1015, num1016 - 1].active())
{
                                    WorldGen.TryGrowingTreeByType(5, num1015, num1016, 0, false);
                                    if (!Main.tile[num1015, num1016 - 1].active())
{
                                        WorldGen.TryGrowingTreeByType(5, num1015, num1016, 0, false);
                                        if (!Main.tile[num1015, num1016 - 1].active())
{
                                            WorldGen.PlaceTile(num1015, num1016 - 1, 71, true, false, -1, 0);
                                        }
                                    }
                                }
                            }
                            if (!Main.tile[num1015, num1016 - 1].active())
{
                                if (Main.tile[num1015, num1016].type == 60)
{
                                    WorldGen.PlaceTile(num1015, num1016 - 1, 61, true, false, -1, 0);
                                }
                                else if (Main.tile[num1015, num1016].type == 226 && WorldGen.genRand.Next(5) == 0 && !WorldGen.TooManyJunglePlantsNearby(num1015, num1016 - 1, 2))
{
                                    WorldGen.PlaceTile(num1015, num1016 - 1, 61, true, false, -1, 0);
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.JunglePlantsPart2, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num1017 = 0; num1017 < Main.maxTilesX * 100; num1017++)
                {
                    int num1018 = WorldGen.genRand.Next(40, Main.maxTilesX / 2 - 40);
                    if (GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left)
                    {
                        num1018 += Main.maxTilesX / 2;
                    }
                    int num1019 = WorldGen.genRand.Next(Main.maxTilesY - 300);
                    while (!Main.tile[num1018, num1019].active() && num1019 < Main.maxTilesY - 300)
                    {
                        num1019++;
                    }
                    if (Main.tile[num1018, num1019].active() && Main.tile[num1018, num1019].type == 60)
                    {
                        num1019--;
                        WorldGen.PlaceJunglePlant(num1018, num1019, 233, WorldGen.genRand.Next(8), 0, true);
                        if (Main.tile[num1018, num1019].type != 233)
{
                            WorldGen.PlaceJunglePlant(num1018, num1019, 233, WorldGen.genRand.Next(12), 1, true);
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Vines, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[43].Value;
                for (int num1020 = 5; num1020 < Main.maxTilesX - 5; num1020++)
                {
                    progress.Set((double)num1020 / (double)Main.maxTilesX);
                    int num1021 = 0;
                    ushort num1022 = 52;
                    int num1023 = (int)Main.worldSurface;
                    if (WorldGen.remixWorldGen)
                    {
                        num1023 = Main.maxTilesY - 200;
                    }
                    for (int num1024 = 0; num1024 < num1023; num1024++)
                    {
                        if (num1021 > 0 && !Main.tile[num1020, num1024].active())
{
                            Main.tile[num1020, num1024].active(true);
                            Main.tile[num1020, num1024].type = num1022;
                            Main.tile[num1020, num1024].ClearSlope();
                            Main.tile[num1020, num1024].CopyPaintAndCoating(Main.tile[num1020, num1024 - 1]);
                            num1021--;
                        }
                        else
{
                            num1021 = 0;
                        }
                        if (Main.tile[num1020, num1024].active() && !Main.tile[num1020, num1024].bottomSlope() && (Main.tile[num1020, num1024].type == 2 || (Main.tile[num1020, num1024].type == 192 && WorldGen.genRand.Next(4) == 0)) && WorldGen.GrowMoreVines(num1020, num1024))
{
                            num1022 = 52;
                            if (Main.tile[num1020, num1024].wall == 68 || Main.tile[num1020, num1024].wall == 65 || Main.tile[num1020, num1024].wall == 66 || Main.tile[num1020, num1024].wall == 63)
{
                                num1022 = 382;
                            }
                            else if (Main.tile[num1020, num1024 + 1].wall == 68 || Main.tile[num1020, num1024 + 1].wall == 65 || Main.tile[num1020, num1024 + 1].wall == 66 || Main.tile[num1020, num1024 + 1].wall == 63)
{
                                num1022 = 382;
                            }
                            if (WorldGen.remixWorldGen && WorldGen.genRand.Next(5) == 0)
{
                                num1022 = 382;
                            }
                            if (WorldGen.genRand.Next(5) < 3)
{
                                num1021 = WorldGen.genRand.Next(1, 10);
                            }
                        }
                    }
                    num1021 = 0;
                    for (int num1025 = 5; num1025 < Main.maxTilesY - 5; num1025++)
                    {
                        if (num1021 > 0 && !Main.tile[num1020, num1025].active())
{
                            Main.tile[num1020, num1025].active(true);
                            Main.tile[num1020, num1025].type = 62;
                            Main.tile[num1020, num1025].ClearSlope();
                            num1021--;
                        }
                        else
{
                            num1021 = 0;
                        }
                        if (Main.tile[num1020, num1025].active() && (Main.tile[num1020, num1025].type == 60 || Main.tile[num1020, num1025].type == 226) && !Main.tile[num1020, num1025].bottomSlope() && WorldGen.GrowMoreVines(num1020, num1025))
{
                            if (WorldGen.notTheBees && num1025 < Main.maxTilesY - 10 && Main.tile[num1020, num1025 - 1].active() && !Main.tile[num1020, num1025 - 1].bottomSlope() && Main.tile[num1020 + 1, num1025 - 1].active() && !Main.tile[num1020 + 1, num1025 - 1].bottomSlope() && (Main.tile[num1020, num1025 - 1].type == 60 || Main.tile[num1020, num1025 - 1].type == 444 || Main.tile[num1020, num1025 - 1].type == 230))
{
                                bool flag74 = true;
                                for (int num1026 = num1020; num1026 < num1020 + 2; num1026++)
{
                                    for (int num1027 = num1025 + 1; num1027 < num1025 + 3; num1027++)
{
                                        if (Main.tile[num1026, num1027].active() && (!Main.tileCut[(int)Main.tile[num1026, num1027].type] || Main.tile[num1026, num1027].type == 444))
{
                                            flag74 = false;
                                            break;
                                        }
                                        if (Main.tile[num1026, num1027].liquid > 0 || Main.wallHouse[(int)Main.tile[num1026, num1027].wall])
{
                                            flag74 = false;
                                            break;
                                        }
                                    }
                                    if (!flag74)
{
                                        break;
                                    }
                                }
                                if (flag74 && WorldGen.CountNearBlocksTypes(num1020, num1025, WorldGen.genRand.Next(3, 10), 1, new int[] { 444 }) > 0)
{
                                    flag74 = false;
                                }
                                if (flag74)
{
                                    for (int num1028 = num1020; num1028 < num1020 + 2; num1028++)
{
                                        for (int num1029 = num1025 + 1; num1029 < num1025 + 3; num1029++)
{
                                            WorldGen.KillTile(num1028, num1029, false, false, false);
                                        }
                                    }
                                    for (int num1030 = num1020; num1030 < num1020 + 2; num1030++)
{
                                        for (int num1031 = num1025 + 1; num1031 < num1025 + 3; num1031++)
{
                                            Main.tile[num1030, num1031].active(true);
                                            Main.tile[num1030, num1031].type = 444;
                                            Main.tile[num1030, num1031].frameX = (short)((num1030 - num1020) * 18);
                                            Main.tile[num1030, num1031].frameY = (short)((num1031 - num1025 - 1) * 18);
                                        }
                                    }
                                    goto IL_0833;
                                }
                            }
                            else if (num1020 < Main.maxTilesX - 1 && num1025 < Main.maxTilesY - 2 && Main.tile[num1020 + 1, num1025].active() && Main.tile[num1020 + 1, num1025].type == 60 && !Main.tile[num1020 + 1, num1025].bottomSlope() && WorldGen.genRand.Next(40) == 0)
{
                                bool flag75 = true;
                                for (int num1032 = num1020; num1032 < num1020 + 2; num1032++)
{
                                    for (int num1033 = num1025 + 1; num1033 < num1025 + 3; num1033++)
{
                                        if (Main.tile[num1032, num1033].active() && (!Main.tileCut[(int)Main.tile[num1032, num1033].type] || Main.tile[num1032, num1033].type == 444))
{
                                            flag75 = false;
                                            break;
                                        }
                                        if (Main.tile[num1032, num1033].liquid > 0 || Main.wallHouse[(int)Main.tile[num1032, num1033].wall])
{
                                            flag75 = false;
                                            break;
                                        }
                                    }
                                    if (!flag75)
{
                                        break;
                                    }
                                }
                                if (flag75 && WorldGen.CountNearBlocksTypes(num1020, num1025, 20, 1, new int[] { 444 }) > 0)
{
                                    flag75 = false;
                                }
                                if (flag75)
{
                                    for (int num1034 = num1020; num1034 < num1020 + 2; num1034++)
{
                                        for (int num1035 = num1025 + 1; num1035 < num1025 + 3; num1035++)
{
                                            WorldGen.KillTile(num1034, num1035, false, false, false);
                                        }
                                    }
                                    for (int num1036 = num1020; num1036 < num1020 + 2; num1036++)
{
                                        for (int num1037 = num1025 + 1; num1037 < num1025 + 3; num1037++)
{
                                            Main.tile[num1036, num1037].active(true);
                                            Main.tile[num1036, num1037].type = 444;
                                            Main.tile[num1036, num1037].frameX = (short)((num1036 - num1020) * 18);
                                            Main.tile[num1036, num1037].frameY = (short)((num1037 - num1025 - 1) * 18);
                                        }
                                    }
                                    goto IL_0833;
                                }
                            }
                            bool flag76 = true;
                            if (Main.tile[num1020, num1025].type == 226 && WorldGen.TooManyJungleVinesNearby(num1020, num1025, 6))
{
                                flag76 = false;
                            }
                            if (flag76 && WorldGen.genRand.Next(5) < 3)
{
                                num1021 = WorldGen.genRand.Next(1, 10);
                            }
                        }
                        IL_0833:;
                    }
                    num1021 = 0;
                    for (int num1038 = 0; num1038 < Main.maxTilesY; num1038++)
                    {
                        if (num1021 > 0 && !Main.tile[num1020, num1038].active())
{
                            Main.tile[num1020, num1038].active(true);
                            Main.tile[num1020, num1038].type = 528;
                            Main.tile[num1020, num1038].ClearSlope();
                            num1021--;
                        }
                        else
{
                            num1021 = 0;
                        }
                        if (Main.tile[num1020, num1038].active() && Main.tile[num1020, num1038].type == 70 && WorldGen.genRand.Next(5) == 0 && !Main.tile[num1020, num1038].bottomSlope() && WorldGen.GrowMoreVines(num1020, num1038) && WorldGen.genRand.Next(5) < 3)
{
                            num1021 = WorldGen.genRand.Next(1, 10);
                        }
                    }
                    num1021 = 0;
                    for (int num1039 = 0; num1039 < Main.maxTilesY; num1039++)
                    {
                        if (num1021 > 0 && !Main.tile[num1020, num1039].active())
{
                            Main.tile[num1020, num1039].active(true);
                            Main.tile[num1020, num1039].type = 636;
                            Main.tile[num1020, num1039].ClearSlope();
                            num1021--;
                        }
                        else
{
                            num1021 = 0;
                        }
                        if (Main.tile[num1020, num1039].active() && !Main.tile[num1020, num1039].bottomSlope() && Main.tile[num1020, num1039].type == 23 && WorldGen.GrowMoreVines(num1020, num1039) && WorldGen.genRand.Next(5) < 3)
{
                            num1021 = WorldGen.genRand.Next(1, 10);
                        }
                    }
                    num1021 = 0;
                    for (int num1040 = 0; num1040 < Main.maxTilesY; num1040++)
                    {
                        if (num1021 > 0 && !Main.tile[num1020, num1040].active())
{
                            Main.tile[num1020, num1040].active(true);
                            Main.tile[num1020, num1040].type = 205;
                            Main.tile[num1020, num1040].ClearSlope();
                            num1021--;
                        }
                        else
{
                            num1021 = 0;
                        }
                        if (Main.tile[num1020, num1040].active() && !Main.tile[num1020, num1040].bottomSlope() && Main.tile[num1020, num1040].type == 199 && WorldGen.GrowMoreVines(num1020, num1040) && WorldGen.genRand.Next(5) < 3)
{
                            num1021 = WorldGen.genRand.Next(1, 10);
                        }
                    }
                    num1021 = 0;
                    for (int num1041 = 0; num1041 < Main.maxTilesY; num1041++)
                    {
                        if (num1021 > 0 && !Main.tile[num1020, num1041].active())
{
                            Main.tile[num1020, num1041].active(true);
                            Main.tile[num1020, num1041].type = 638;
                            Main.tile[num1020, num1041].ClearSlope();
                            num1021--;
                        }
                        else
{
                            num1021 = 0;
                        }
                        if (Main.tile[num1020, num1041].active() && !Main.tile[num1020, num1041].bottomSlope() && Main.tile[num1020, num1041].type == 633 && WorldGen.GrowMoreVines(num1020, num1041) && WorldGen.genRand.Next(5) < 3)
{
                            num1021 = WorldGen.genRand.Next(1, 10);
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Flowers, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[44].Value;
                int num1042 = (int)((double)Main.maxTilesX * 0.004);
                if (WorldGen.remixWorldGen)
                {
                    num1042 *= 6;
                }
                for (int num1043 = 0; num1043 < num1042; num1043++)
                {
                    progress.Set((double)num1043 / (double)num1042);
                    int num1044 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                    int num1045 = WorldGen.genRand.Next(15, 30);
                    int num1046 = WorldGen.genRand.Next(15, 30);
                    if (WorldGen.remixWorldGen)
                    {
                        num1045 = WorldGen.genRand.Next(15, 45);
                        num1046 = WorldGen.genRand.Next(15, 45);
                        int num1047 = WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                        if (GenVars.logX >= 0)
{
                            num1044 = GenVars.logX;
                            num1047 = GenVars.logY;
                            GenVars.logX = -1;
                        }
                        int num1048 = WorldGen.genRand.NextFromList(new int[] { 21, 24, 27, 30, 33, 36, 39, 42 });
                        for (int num1049 = num1044 - num1045; num1049 < num1044 + num1045; num1049++)
{
                            for (int num1050 = num1047 - num1046; num1050 < num1047 + num1046; num1050++)
{
                                Tile tile22 = Main.tile[num1049, num1050];
                                Tile tile23 = Main.tile[num1049, num1050 + 1];
                                Tile tile24 = Main.tile[num1049, num1050 + 2];
                                if ((!tile22.active() || tile22.type != 488) && (!tile22.active() || !Main.tileSolid[(int)tile22.type]))
{
                                    if (tile22.active() && tile22.type == 3)
{
                                        tile22.frameX = (short)((num1048 + WorldGen.genRand.Next(3)) * 18);
                                        if (WorldGen.genRand.Next(3) != 0)
{
                                            tile22.type = 73;
                                        }
                                    }
                                    else if (tile23.wall == 0 && tile23.active() && (tile23.type == 2 || ((tile23.type == 40 || tile23.type == 1 || TileID.Sets.Ore[(int)tile23.type]) && !tile22.active())) && (!tile22.active() || tile22.type == 185 || tile22.type == 186 || tile22.type == 187 || (tile22.type == 5 && (double)num1049 < (double)Main.maxTilesX * 0.48) || (double)num1049 > (double)Main.maxTilesX * 0.52))
{
                                        if (tile23.type == 40 || tile23.type == 1 || TileID.Sets.Ore[(int)tile23.type])
{
                                            tile23.type = 2;
                                            if (tile24.type == 40 || tile24.type == 1 || TileID.Sets.Ore[(int)tile24.type])
{
                                                tile24.type = 2;
                                            }
                                        }
                                        WorldGen.KillTile(num1049, num1050, false, false, false);
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            tile23.slope(0);
                                            tile23.halfBrick(false);
                                        }
                                        WorldGen.PlaceTile(num1049, num1050, 3, false, false, -1, 0);
                                        if (tile22.active() && tile22.type == 3)
{
                                            tile22.frameX = (short)((num1048 + WorldGen.genRand.Next(3)) * 18);
                                            if (WorldGen.genRand.Next(3) != 0)
{
                                                tile22.type = 73;
                                            }
                                        }
                                        if (tile24.type == 40 || tile24.type == 1 || TileID.Sets.Ore[(int)tile24.type])
{
                                            tile24.type = 0;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        int num1051 = num1046;
                        while ((double)num1051 < Main.worldSurface - (double)num1046 - 1.0)
{
                            if (Main.tile[num1044, num1051].active())
{
                                if (GenVars.logX >= 0)
{
                                    num1044 = GenVars.logX;
                                    num1051 = GenVars.logY;
                                    GenVars.logX = -1;
                                }
                                int num1052 = WorldGen.genRand.NextFromList(new int[] { 21, 24, 27, 30, 33, 36, 39, 42 });
                                for (int num1053 = num1044 - num1045; num1053 < num1044 + num1045; num1053++)
{
                                    for (int num1054 = num1051 - num1046; num1054 < num1051 + num1046; num1054++)
{
                                        if (WorldGen.InWorld(num1053, num1054, 5))
{
                                            Tile tile25 = Main.tile[num1053, num1054];
                                            Tile tile26 = Main.tile[num1053, num1054 + 1];
                                            Tile tile27 = Main.tile[num1053, num1054 + 2];
                                            if ((!tile25.active() || tile25.type != 488) && (!tile25.active() || !Main.tileSolid[(int)tile25.type]))
{
                                                if (tile25.active() && tile25.type == 3)
{
                                                    tile25.frameX = (short)((num1052 + WorldGen.genRand.Next(3)) * 18);
                                                    if (WorldGen.genRand.Next(3) != 0)
{
                                                        tile25.type = 73;
                                                    }
                                                }
                                                else if (tile26.wall == 0 && tile26.active() && (tile26.type == 2 || ((tile26.type == 40 || tile26.type == 1 || TileID.Sets.Ore[(int)tile26.type]) && !tile25.active())) && (!tile25.active() || tile25.type == 185 || tile25.type == 186 || tile25.type == 187 || (tile25.type == 5 && (double)num1053 < (double)Main.maxTilesX * 0.48) || (double)num1053 > (double)Main.maxTilesX * 0.52))
{
                                                    if (tile26.type == 40 || tile26.type == 1 || TileID.Sets.Ore[(int)tile26.type])
{
                                                        tile26.type = 2;
                                                        if (tile27.type == 40 || tile27.type == 1 || TileID.Sets.Ore[(int)tile27.type])
{
                                                            tile27.type = 2;
                                                        }
                                                    }
                                                    WorldGen.KillTile(num1053, num1054, false, false, false);
                                                    if (WorldGen.genRand.Next(2) == 0)
{
                                                        tile26.slope(0);
                                                        tile26.halfBrick(false);
                                                    }
                                                    WorldGen.PlaceTile(num1053, num1054, 3, false, false, -1, 0);
                                                    if (tile25.active() && tile25.type == 3)
{
                                                        tile25.frameX = (short)((num1052 + WorldGen.genRand.Next(3)) * 18);
                                                        if (WorldGen.genRand.Next(3) != 0)
{
                                                            tile25.type = 73;
                                                        }
                                                    }
                                                    if (tile27.type == 40 || tile27.type == 1 || TileID.Sets.Ore[(int)tile27.type])
{
                                                        tile27.type = 0;
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                                break;
                            }
                            num1051++;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.Mushrooms, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[45].Value;
                int num1055 = (int)((double)Main.maxTilesX * 0.002);
                if (WorldGen.remixWorldGen)
                {
                    num1055 *= 9;
                }
                for (int num1056 = 0; num1056 < num1055; num1056++)
                {
                    progress.Set((double)num1056 / (double)num1055);
                    int num1057 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num1058 = WorldGen.genRand.Next(4, 10);
                    int num1059 = WorldGen.genRand.Next(15, 30);
                    if (WorldGen.remixWorldGen)
                    {
                        num1058 = WorldGen.genRand.Next(8, 17);
                        num1059 = WorldGen.genRand.Next(8, 17);
                        int num1060 = WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                        if (Main.tile[num1057, num1060].active())
{
                            for (int num1061 = num1057 - num1058; num1061 < num1057 + num1058; num1061++)
{
                                int num1062 = num1060 - num1059;
                                while (num1062 < num1060 + num1059 && num1061 >= 10 && num1062 >= 0 && num1061 <= Main.maxTilesX - 10 && num1062 <= Main.maxTilesY - 10)
{
                                    if (Main.tile[num1061, num1062].type == 3 || Main.tile[num1061, num1062].type == 24)
{
                                        Main.tile[num1061, num1062].frameX = 144;
                                    }
                                    else if (Main.tile[num1061, num1062].type == 201)
{
                                        Main.tile[num1061, num1062].frameX = 270;
                                    }
                                    num1062++;
                                }
                            }
                        }
                    }
                    else
                    {
                        int num1063 = 1;
                        while ((double)num1063 < Main.worldSurface - 1.0)
{
                            if (Main.tile[num1057, num1063].active())
{
                                for (int num1064 = num1057 - num1058; num1064 < num1057 + num1058; num1064++)
{
                                    int num1065 = num1063 - num1059;
                                    while (num1065 < num1063 + num1059 && num1064 >= 10 && num1065 >= 0 && num1064 <= Main.maxTilesX - 10 && num1065 <= Main.maxTilesY - 10)
{
                                        if (Main.tile[num1064, num1065].type == 3 || Main.tile[num1064, num1065].type == 24)
{
                                            Main.tile[num1064, num1065].frameX = 144;
                                        }
                                        else if (Main.tile[num1064, num1065].type == 201)
{
                                            Main.tile[num1064, num1065].frameX = 270;
                                        }
                                        num1065++;
                                    }
                                }
                                break;
                            }
                            num1063++;
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.ExposedGemsInIceBiome, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                int num1066 = 0;
                while ((double)num1066 < (double)Main.maxTilesX * 0.25)
                {
                    int num1067;
                    if (WorldGen.remixWorldGen)
                    {
                        num1067 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    }
                    else
                    {
                        num1067 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, GenVars.lavaLine);
                    }
                    int num1068 = WorldGen.genRand.Next(GenVars.snowMinX[num1067], GenVars.snowMaxX[num1067]);
                    if (Main.tile[num1068, num1067].active() && (Main.tile[num1068, num1067].type == 147 || Main.tile[num1068, num1067].type == 161 || Main.tile[num1068, num1067].type == 162 || Main.tile[num1068, num1067].type == 224))
                    {
                        int num1069 = WorldGen.genRand.Next(1, 4);
                        int num1070 = WorldGen.genRand.Next(1, 4);
                        int num1071 = WorldGen.genRand.Next(1, 4);
                        int num1072 = WorldGen.genRand.Next(1, 4);
                        int num1073 = WorldGen.genRand.Next(12);
                        int num1074;
                        if (num1073 < 3)
{
                            num1074 = 0;
                        }
                        else if (num1073 < 6)
{
                            num1074 = 1;
                        }
                        else if (num1073 < 8)
{
                            num1074 = 2;
                        }
                        else if (num1073 < 10)
{
                            num1074 = 3;
                        }
                        else if (num1073 < 11)
{
                            num1074 = 4;
                        }
                        else
{
                            num1074 = 5;
                        }
                        for (int num1075 = num1068 - num1069; num1075 < num1068 + num1070; num1075++)
{
                            for (int num1076 = num1067 - num1071; num1076 < num1067 + num1072; num1076++)
{
                                if (WorldGen.InWorld(num1075, num1076, 40) && !Main.tile[num1075, num1076].active())
{
                                    WorldGen.PlaceTile(num1075, num1076, 178, true, false, -1, num1074);
                                }
                            }
                        }
                    }
                    num1066++;
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.ExposedGemsUnderground, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num1077 = 0; num1077 < Main.maxTilesX; num1077++)
                {
                    int num1078 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num1079 = WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 300);
                    if (!Main.tile[num1078, num1079].active() && !Main.tile[num1078, num1079].anyLava() && !Main.wallDungeon[(int)Main.tile[num1078, num1079].wall] && Main.tile[num1078, num1079].wall != 27)
                    {
                        int num1080 = WorldGen.genRand.Next(12);
                        int num1081;
                        if (num1080 < 3)
{
                            num1081 = 0;
                        }
                        else if (num1080 < 6)
{
                            num1081 = 1;
                        }
                        else if (num1080 < 8)
{
                            num1081 = 2;
                        }
                        else if (num1080 < 10)
{
                            num1081 = 3;
                        }
                        else if (num1080 < 11)
{
                            num1081 = 4;
                        }
                        else
{
                            num1081 = 5;
                        }
                        WorldGen.PlaceTile(num1078, num1079, 178, true, false, -1, num1081);
                    }
                }
                for (int num1082 = 0; num1082 < Main.maxTilesX; num1082++)
                {
                    int num1083 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num1084 = WorldGen.genRand.Next((int)Main.worldSurface, Main.maxTilesY - 300);
                    if (!Main.tile[num1083, num1084].active() && !Main.tile[num1083, num1084].anyLava() && (Main.tile[num1083, num1084].wall == 216 || Main.tile[num1083, num1084].wall == 187))
                    {
                        int num1085 = WorldGen.genRand.Next(1, 4);
                        int num1086 = WorldGen.genRand.Next(1, 4);
                        int num1087 = WorldGen.genRand.Next(1, 4);
                        int num1088 = WorldGen.genRand.Next(1, 4);
                        for (int num1089 = num1083 - num1085; num1089 < num1083 + num1086; num1089++)
{
                            for (int num1090 = num1084 - num1087; num1090 < num1084 + num1088; num1090++)
{
                                if (!Main.tile[num1089, num1090].active())
{
                                    WorldGen.PlaceTile(num1089, num1090, 178, true, false, -1, 6);
                                }
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.LongMoss, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                progress.Message = Language.GetTextValue("WorldGeneration.LongMoss");
                progress.Set(0.0);
                int num1091 = Main.maxTilesX - 5;
                for (int num1092 = 5; num1092 < num1091; num1092++)
                {
                    if (progress != null)
                    {
                        float num1093 = (float)num1092 / (float)num1091;
                        progress.Set((double)num1093);
                    }
                    for (int num1094 = 5; num1094 < Main.maxTilesY - 5; num1094++)
                    {
                        if (Main.tile[num1092, num1094].active() && Main.tileMoss[(int)Main.tile[num1092, num1094].type])
{
                            for (int num1095 = 0; num1095 < 4; num1095++)
{
                                int num1096 = num1092;
                                int num1097 = num1094;
                                if (num1095 == 0)
{
                                    num1096--;
                                }
                                else if (num1095 == 1)
{
                                    num1096++;
                                }
                                else if (num1095 == 2)
{
                                    num1097--;
                                }
                                else if (num1095 == 3)
{
                                    num1097++;
                                }
                                if (!Main.tile[num1096, num1097].active())
{
                                    WorldGen.PlaceTile(num1096, num1097, 184, true, false, -1, 0);
                                }
                            }
                        }
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.DirtWallsIntoMudWallsInJungleAndJungleMinMax, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                int num1098 = 0;
                int num1099 = 0;
                bool flag77 = false;
                for (int num1100 = 5; num1100 < Main.maxTilesX - 5; num1100++)
                {
                    int num1101 = 0;
                    while ((double)num1101 < Main.worldSurface + 20.0)
                    {
                        if (Main.tile[num1100, num1101].active() && Main.tile[num1100, num1101].type == 60)
{
                            num1098 = num1100;
                            flag77 = true;
                            break;
                        }
                        num1101++;
                    }
                    if (flag77)
                    {
                        break;
                    }
                }
                flag77 = false;
                for (int num1102 = Main.maxTilesX - 5; num1102 > 5; num1102--)
                {
                    int num1103 = 0;
                    while ((double)num1103 < Main.worldSurface + 20.0)
                    {
                        if (Main.tile[num1102, num1103].active() && Main.tile[num1102, num1103].type == 60)
{
                            num1099 = num1102;
                            flag77 = true;
                            break;
                        }
                        num1103++;
                    }
                    if (flag77)
                    {
                        break;
                    }
                }
                GenVars.jungleMinX = num1098;
                GenVars.jungleMaxX = num1099;
                for (int num1104 = num1098; num1104 <= num1099; num1104++)
                {
                    int num1105 = 0;
                    while ((double)num1105 < Main.worldSurface + 20.0)
                    {
                        if (((num1104 >= num1098 + 2 && num1104 <= num1099 - 2) || WorldGen.genRand.Next(2) != 0) && ((num1104 >= num1098 + 3 && num1104 <= num1099 - 3) || WorldGen.genRand.Next(3) != 0) && (Main.tile[num1104, num1105].wall == 2 || Main.tile[num1104, num1105].wall == 59))
{
                            Main.tile[num1104, num1105].wall = 15;
                        }
                        num1105++;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.BeeLarvaInBeehives, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                Main.tileSolid[229] = true;
                progress.Set(1.0);
                for (int num1106 = 0; num1106 < GenVars.numLarva; num1106++)
                {
                    int num1107 = GenVars.larvaX[num1106];
                    int num1108 = GenVars.larvaY[num1106];
                    for (int num1109 = num1107 - 1; num1109 <= num1107 + 1; num1109++)
                    {
                        for (int num1110 = num1108 - 2; num1110 <= num1108 + 1; num1110++)
{
                            if (num1110 != num1108 + 1)
{
                                Main.tile[num1109, num1110].active(false);
                            }
                            else
{
                                Main.tile[num1109, num1110].active(true);
                                Main.tile[num1109, num1110].type = 225;
                                Main.tile[num1109, num1110].slope(0);
                                Main.tile[num1109, num1110].halfBrick(false);
                            }
                        }
                    }
                    WorldGen.PlaceTile(num1107, num1108, 231, true, false, -1, 0);
                }
                Main.tileSolid[232] = true;
                Main.tileSolid[162] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.SettleLiquidsPart2AndNotTheBees, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.getGoodWorldGen)
                {
                    Main.tileSolid[56] = true;
                }
                progress.Message = Lang.gen[27].Value;
                if (WorldGen.SecretSeed.extraLiquid.Enabled)
                {
                    progress.Message = Language.GetTextValue("WorldGeneration.WaterFeatures");
                }
                if (WorldGen.notTheBees)
                {
                    WorldGen.NotTheBees();
                }
                Liquid.worldGenTilesIgnoreWater(true);
                Liquid.QuickWater(3, -1, -1);
                WorldGen.WaterCheck();
                int num1111 = 0;
                Liquid.quickSettle = true;
                int num1112 = 10;
                while (num1111 < num1112)
                {
                    int num1113 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                    num1111++;
                    double num1114 = 0.0;
                    int num1115 = num1113 * 5;
                    while (Liquid.numLiquid > 0)
                    {
                        num1115--;
                        if (num1115 < 0)
{
                            break;
                        }
                        double num1116 = (double)(num1113 - (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer)) / (double)num1113;
                        if (Liquid.numLiquid + LiquidBuffer.numLiquidBuffer > num1113)
{
                            num1113 = Liquid.numLiquid + LiquidBuffer.numLiquidBuffer;
                        }
                        if (num1116 > num1114)
{
                            num1114 = num1116;
                        }
                        else
{
                            num1116 = num1114;
                        }
                        if (num1111 == 1)
{
                            progress.Set(num1116 / 3.0 + 0.33);
                        }
                        Liquid.UpdateLiquid();
                    }
                    WorldGen.WaterCheck();
                    progress.Set((double)num1111 / (double)num1112 / 3.0 + 0.66);
                }
                WorldGen.ClearPendingLiquid();
                Liquid.quickSettle = false;
                Liquid.worldGenTilesIgnoreWater(false);
                Main.tileSolid[484] = false;
            });
            WorldGen.AddGenerationPass(GenPassNameID.CactusPalmTreesAndCoral, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                if (WorldGen.SecretSeed.noSurface.Enabled)
                {
                    return;
                }
                progress.Message = Lang.gen[38].Value;
                int num1117 = 8;
                if (WorldGen.remixWorldGen)
                {
                    num1117 = 2;
                }
                int num1118 = 400;
                int num1119 = WorldGen.genRand.Next(3, 13);
                int num1120 = WorldGen.genRand.Next(3, 13);
                int num1121 = WorldGen.genRand.Next(2, 6);
                int num1122 = WorldGen.genRand.Next(2, 6);
                int num1123 = 380;
                for (int num1124 = 0; num1124 < GenVars.numOasis; num1124++)
                {
                    int num1125 = (int)((double)GenVars.oasisWidth[num1124] * 1.5);
                    for (int num1126 = GenVars.oasisPosition[num1124].X - num1125; num1126 <= GenVars.oasisPosition[num1124].X + num1125; num1126++)
                    {
                        for (int num1127 = GenVars.oasisPosition[num1124].Y - GenVars.oasisHeight; num1127 <= GenVars.oasisPosition[num1124].Y + GenVars.oasisHeight; num1127++)
{
                            double num1128 = 1.0;
                            int num1129 = 8;
                            for (int num1130 = num1126 - num1129; num1130 <= num1126 + num1129; num1130++)
{
                                for (int num1131 = num1127 - num1129; num1131 <= num1127 + num1129; num1131++)
{
                                    if (WorldGen.InWorld(num1130, num1131, 0) && Main.tile[num1130, num1131] != null && Main.tile[num1130, num1131].active() && Main.tile[num1130, num1131].type == 323)
{
                                        num1128 = 0.13;
                                    }
                                }
                            }
                            if (WorldGen.genRand.NextDouble() < num1128)
{
                                WorldGen.TryGrowingTreeByType(323, num1126, num1127, 0, false);
                            }
                            if (WorldGen.PlantSeaOat(num1126, num1127))
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    WorldGen.GrowSeaOat(num1126, num1127);
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    WorldGen.GrowSeaOat(num1126, num1127);
                                }
                            }
                            WorldGen.PlaceOasisPlant(num1126, num1127, 530);
                        }
                    }
                }
                for (int num1132 = 0; num1132 < 3; num1132++)
                {
                    progress.Set((double)num1132 / 3.0);
                    int num1133;
                    int num1134;
                    bool flag78;
                    int num1135;
                    switch (num1132)
                    {
                    default:
                        num1133 = 5;
                        num1134 = num1123;
                        flag78 = false;
                        num1135 = num1119;
                        break;
                    case 1:
                        num1133 = num1118;
                        num1134 = Main.maxTilesX - num1118;
                        flag78 = true;
                        num1135 = num1117;
                        break;
                    case 2:
                        num1133 = Main.maxTilesX - num1123;
                        num1134 = Main.maxTilesX - 5;
                        flag78 = false;
                        num1135 = num1120;
                        break;
                    }
                    double num1136 = Main.worldSurface - 1.0;
                    if (WorldGen.remixWorldGen)
                    {
                        num1136 = (double)(Main.maxTilesY - 50);
                    }
                    for (int num1137 = num1133; num1137 < num1134; num1137++)
                    {
                        if (WorldGen.genRand.Next(num1135) == 0)
{
                            int num1138 = 0;
                            while ((double)num1138 < num1136)
{
                                Tile tile28 = Main.tile[num1137, num1138];
                                if (tile28.active() && (tile28.type == 53 || tile28.type == 112 || tile28.type == 234))
{
                                    Tile tile29 = Main.tile[num1137, num1138 - 1];
                                    if (!tile29.active() && tile29.wall == 0)
{
                                        if (flag78)
{
                                            if (WorldGen.remixWorldGen)
{
                                                if ((double)num1138 > Main.worldSurface)
{
                                                    if (WorldGen.SolidTile(num1137, num1138, false) && Main.tile[num1137, num1138 + 1].active() && Main.tile[num1137, num1138 + 1].type == 53 && Main.tile[num1137, num1138 + 2].active() && Main.tile[num1137, num1138 + 2].type == 53)
{
                                                        int num1139 = 3;
                                                        WorldGen.TryGrowingTreeByType(323, num1137, num1138, 0, false);
                                                        if (!Main.tile[num1137, num1138 - 1].active() && WorldGen.genRand.Next(num1139) == 0)
{
                                                            WorldGen.PlantCactus(num1137, num1138);
                                                        }
                                                    }
                                                }
                                                else
{
                                                    int num1140 = 0;
                                                    for (int num1141 = num1137 - WorldGen.cactusWaterWidth; num1141 < num1137 + WorldGen.cactusWaterWidth; num1141++)
{
                                                        for (int num1142 = num1138 - WorldGen.cactusWaterHeight; num1142 < num1138 + WorldGen.cactusWaterHeight; num1142++)
{
                                                            num1140 += (int)Main.tile[num1141, num1142].liquid;
                                                        }
                                                    }
                                                    if (num1140 / 255 > WorldGen.cactusWaterLimit)
{
                                                        int num1143 = 4;
                                                        if (WorldGen.genRand.Next(num1143) == 0)
{
                                                            WorldGen.TryGrowingTreeByType(323, num1137, num1138, 0, false);
                                                        }
                                                    }
                                                    else
{
                                                        WorldGen.PlantCactus(num1137, num1138);
                                                    }
                                                }
                                            }
                                            else
{
                                                int num1144 = 0;
                                                for (int num1145 = num1137 - WorldGen.cactusWaterWidth; num1145 < num1137 + WorldGen.cactusWaterWidth; num1145++)
{
                                                    for (int num1146 = num1138 - WorldGen.cactusWaterHeight; num1146 < num1138 + WorldGen.cactusWaterHeight; num1146++)
{
                                                        if (WorldGen.InWorld(num1145, num1146, 0))
{
                                                            num1144 += (int)Main.tile[num1145, num1146].liquid;
                                                        }
                                                    }
                                                }
                                                if (num1144 / 255 > WorldGen.cactusWaterLimit)
{
                                                    int num1147 = 4;
                                                    if (WorldGen.genRand.Next(num1147) == 0)
{
                                                        WorldGen.TryGrowingTreeByType(323, num1137, num1138, 0, false);
                                                    }
                                                }
                                                else
{
                                                    WorldGen.PlantCactus(num1137, num1138);
                                                }
                                            }
                                        }
                                        else if (Main.tile[num1137, num1138 - 2].liquid == 255 && Main.tile[num1137, num1138 - 3].liquid == 255 && Main.tile[num1137, num1138 - 4].liquid == 255)
{
                                            if (WorldGen.genRand.Next(2) == 0)
{
                                                WorldGen.PlaceTile(num1137, num1138 - 1, 81, true, false, -1, 0);
                                                break;
                                            }
                                            WorldGen.PlaceTile(num1137, num1138 - 1, 324, true, false, -1, WorldGen.RollRandomSeaShellStyle());
                                            break;
                                        }
                                        else if (Main.tile[num1137, num1138 - 2].liquid == 0 && (double)num1138 < Main.worldSurface)
{
                                            WorldGen.PlaceTile(num1137, num1138 - 1, 324, true, false, -1, WorldGen.RollRandomSeaShellStyle());
                                            break;
                                        }
                                    }
                                }
                                num1138++;
                            }
                        }
                        else
{
                            int num1148 = 0;
                            while ((double)num1148 < num1136)
{
                                if (WorldGen.PlantSeaOat(num1137, num1148))
{
                                    if (WorldGen.genRand.Next(2) == 0)
{
                                        WorldGen.GrowSeaOat(num1137, num1148);
                                    }
                                    if (WorldGen.genRand.Next(2) == 0)
{
                                        WorldGen.GrowSeaOat(num1137, num1148);
                                    }
                                }
                                WorldGen.PlaceOasisPlant(num1137, num1148, 530);
                                num1148++;
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.TileCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denySomeGeneration)
                {
                    return;
                }
                Main.tileSolid[379] = false;
                progress.Message = Lang.gen[84].Value;
                for (int num1149 = 0; num1149 < Main.maxTilesX; num1149++)
                {
                    for (int num1150 = 0; num1150 < Main.maxTilesY; num1150++)
                    {
                        Tile tile30 = Main.tile[num1149, num1150];
                        if (!tile30.active() || !TileID.Sets.SaveSlopes[(int)tile30.type])
{
                            tile30.ClearSlope();
                        }
                    }
                }
                for (int num1151 = 40; num1151 < Main.maxTilesX - 40; num1151++)
                {
                    progress.Set((double)(num1151 - 40) / (double)(Main.maxTilesX - 80));
                    for (int num1152 = 40; num1152 < Main.maxTilesY - 40; num1152++)
                    {
                        if (Main.tile[num1151, num1152].active() && Main.tile[num1151, num1152].topSlope() && ((Main.tile[num1151, num1152].leftSlope() && Main.tile[num1151 + 1, num1152].active() && Main.tile[num1151 + 1, num1152].halfBrick()) || (Main.tile[num1151, num1152].rightSlope() && Main.tile[num1151 - 1, num1152].active() && Main.tile[num1151 - 1, num1152].halfBrick())))
{
                            Main.tile[num1151, num1152].slope(0);
                            Main.tile[num1151, num1152].halfBrick(true);
                        }
                        if (Main.tile[num1151, num1152].active() && Main.tile[num1151, num1152].liquid > 0 && TileID.Sets.SlowlyDiesInWater[(int)Main.tile[num1151, num1152].type])
{
                            WorldGen.KillTile(num1151, num1152, false, false, false);
                        }
                        if (!Main.tile[num1151, num1152].active() && Main.tile[num1151, num1152].liquid == 0 && WorldGen.genRand.Next(3) != 0 && WorldGen.SolidTile(num1151, num1152 - 1, false))
{
                            int num1153 = WorldGen.genRand.Next(15, 21);
                            for (int num1154 = num1152 - 2; num1154 >= num1152 - num1153; num1154--)
{
                                if (Main.tile[num1151, num1154].liquid >= 128 && !Main.tile[num1151, num1154].shimmer())
{
                                    int num1155 = 373;
                                    if (Main.tile[num1151, num1154].lava())
{
                                        num1155 = 374;
                                    }
                                    else if (Main.tile[num1151, num1154].honey())
{
                                        num1155 = 375;
                                    }
                                    else if (Main.tile[num1151, num1154].shimmer())
{
                                        num1155 = 709;
                                    }
                                    int num1156 = num1152 - num1154;
                                    if (WorldGen.genRand.Next(num1156) <= 1)
{
                                        if (Main.tile[num1151, num1152].wall == 86)
{
                                            num1155 = 375;
                                        }
                                        Main.tile[num1151, num1152].type = (ushort)num1155;
                                        Main.tile[num1151, num1152].frameX = 0;
                                        Main.tile[num1151, num1152].frameY = 0;
                                        Main.tile[num1151, num1152].active(true);
                                        break;
                                    }
                                }
                            }
                            if (!Main.tile[num1151, num1152].active())
{
                                num1153 = WorldGen.genRand.Next(3, 11);
                                for (int num1157 = num1152 + 1; num1157 <= num1152 + num1153; num1157++)
{
                                    if (Main.tile[num1151, num1157].liquid >= 200 && !Main.tile[num1151, num1157].shimmer())
{
                                        int num1158 = 373;
                                        if (Main.tile[num1151, num1157].lava())
{
                                            num1158 = 374;
                                        }
                                        else if (Main.tile[num1151, num1157].honey())
{
                                            num1158 = 375;
                                        }
                                        else if (Main.tile[num1151, num1157].shimmer())
{
                                            num1158 = 709;
                                        }
                                        int num1159 = num1157 - num1152;
                                        if (WorldGen.genRand.Next(num1159 * 3) <= 1)
{
                                            Main.tile[num1151, num1152].type = (ushort)num1158;
                                            Main.tile[num1151, num1152].frameX = 0;
                                            Main.tile[num1151, num1152].frameY = 0;
                                            Main.tile[num1151, num1152].active(true);
                                            break;
                                        }
                                    }
                                }
                            }
                            if (!Main.tile[num1151, num1152].active() && WorldGen.genRand.Next(4) == 0)
{
                                Tile tile31 = Main.tile[num1151, num1152 - 1];
                                if (TileID.Sets.Conversion.Sandstone[(int)tile31.type] || TileID.Sets.Conversion.HardenedSand[(int)tile31.type])
{
                                    Main.tile[num1151, num1152].type = 461;
                                    Main.tile[num1151, num1152].frameX = 0;
                                    Main.tile[num1151, num1152].frameY = 0;
                                    Main.tile[num1151, num1152].active(true);
                                }
                            }
                        }
                        if (Main.tile[num1151, num1152].wall == 13 || Main.tile[num1151, num1152].wall == 14)
{
                            Main.tile[num1151, num1152].liquid = 0;
                        }
                        if (Main.tile[num1151, num1152].wall == 87)
{
                            if (WorldGen.SecretSeed.extraLiquid.Enabled)
{
                                if (Main.tile[num1151, num1152].liquid > 0)
{
                                    Main.tile[num1151, num1152].liquidType(0);
                                }
                                if (Main.tile[num1151, num1152].type == 374 || Main.tile[num1151, num1152].type == 709 || Main.tile[num1151, num1152].type == 375)
{
                                    Main.tile[num1151, num1152].type = 373;
                                }
                            }
                            else
{
                                Main.tile[num1151, num1152].liquid = 0;
                            }
                        }
                        if (Main.tile[num1151, num1152].active())
{
                            if (Main.tile[num1151, num1152].type == 137)
{
                                int num1160 = (int)(Main.tile[num1151, num1152].frameY / 18);
                                if (num1160 <= 2 || num1160 == 5)
{
                                    int num1161 = -1;
                                    if (Main.tile[num1151, num1152].frameX >= 18)
{
                                        num1161 = 1;
                                    }
                                    if (Main.tile[num1151 + num1161, num1152].halfBrick() || Main.tile[num1151 + num1161, num1152].slope() != 0)
{
                                        Main.tile[num1151 + num1161, num1152].active(false);
                                    }
                                }
                            }
                            else if (Main.tile[num1151, num1152].type == 162 && Main.tile[num1151, num1152 + 1].liquid == 0 && WorldGen.CanKillTile(num1151, num1152))
{
                                Main.tile[num1151, num1152].active(false);
                            }
                            if (Main.tile[num1151, num1152].type == 31)
{
                                int num1162 = (int)(Main.tile[num1151, num1152].frameX / 18);
                                int num1163 = 0;
                                int num1164 = num1151;
                                num1163 += num1162 / 2;
                                if (WorldGen.drunkWorldGen)
{
                                    if (Main.tile[num1151, num1152].wall == 83)
{
                                        num1163 = 1;
                                    }
                                    else
{
                                        num1163 = 0;
                                    }
                                }
                                else
{
                                    num1163 = (WorldGen.crimson ? 1 : 0);
                                }
                                num1162 %= 2;
                                num1164 -= num1162;
                                int num1165 = (int)(Main.tile[num1151, num1152].frameY / 18);
                                int num1166 = 0;
                                int num1167 = num1152;
                                num1166 += num1165 / 2;
                                num1165 %= 2;
                                num1167 -= num1165;
                                for (int num1168 = 0; num1168 < 2; num1168++)
{
                                    for (int num1169 = 0; num1169 < 2; num1169++)
{
                                        int num1170 = num1164 + num1168;
                                        int num1171 = num1167 + num1169;
                                        Main.tile[num1170, num1171].active(true);
                                        Main.tile[num1170, num1171].slope(0);
                                        Main.tile[num1170, num1171].halfBrick(false);
                                        Main.tile[num1170, num1171].type = 31;
                                        Main.tile[num1170, num1171].frameX = (short)(num1168 * 18 + 36 * num1163);
                                        Main.tile[num1170, num1171].frameY = (short)(num1169 * 18 + 36 * num1166);
                                    }
                                }
                            }
                            if (Main.tile[num1151, num1152].type == 12)
{
                                int num1172 = (int)(Main.tile[num1151, num1152].frameX / 18);
                                int num1173 = 0;
                                int num1174 = num1151;
                                num1173 += num1172 / 2;
                                num1172 %= 2;
                                num1174 -= num1172;
                                int num1175 = (int)(Main.tile[num1151, num1152].frameY / 18);
                                int num1176 = 0;
                                int num1177 = num1152;
                                num1176 += num1175 / 2;
                                num1175 %= 2;
                                num1177 -= num1175;
                                for (int num1178 = 0; num1178 < 2; num1178++)
{
                                    for (int num1179 = 0; num1179 < 2; num1179++)
{
                                        int num1180 = num1174 + num1178;
                                        int num1181 = num1177 + num1179;
                                        Main.tile[num1180, num1181].active(true);
                                        Main.tile[num1180, num1181].slope(0);
                                        Main.tile[num1180, num1181].halfBrick(false);
                                        Main.tile[num1180, num1181].type = 12;
                                        Main.tile[num1180, num1181].frameX = (short)(num1178 * 18 + 36 * num1173);
                                        Main.tile[num1180, num1181].frameY = (short)(num1179 * 18 + 36 * num1176);
                                    }
                                    if (!Main.tile[num1174 + num1178, num1177 + 2].active())
{
                                        Main.tile[num1174 + num1178, num1177 + 2].active(true);
                                        Main.tile[num1174 + num1178, num1177 + 2].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[num1174 + num1178, num1177 + 2].wall];
                                    }
                                    Main.tile[num1174 + num1178, num1177 + 2].slope(0);
                                    Main.tile[num1174 + num1178, num1177 + 2].halfBrick(false);
                                }
                            }
                            if (Main.tile[num1151, num1152].type == 639)
{
                                int num1182 = (int)(Main.tile[num1151, num1152].frameX / 18);
                                int num1183 = 0;
                                int num1184 = num1151;
                                num1183 += num1182 / 2;
                                num1182 %= 2;
                                num1184 -= num1182;
                                int num1185 = (int)(Main.tile[num1151, num1152].frameY / 18);
                                int num1186 = 0;
                                int num1187 = num1152;
                                num1186 += num1185 / 2;
                                num1185 %= 2;
                                num1187 -= num1185;
                                for (int num1188 = 0; num1188 < 2; num1188++)
{
                                    for (int num1189 = 0; num1189 < 2; num1189++)
{
                                        int num1190 = num1184 + num1188;
                                        int num1191 = num1187 + num1189;
                                        Main.tile[num1190, num1191].active(true);
                                        Main.tile[num1190, num1191].slope(0);
                                        Main.tile[num1190, num1191].halfBrick(false);
                                        Main.tile[num1190, num1191].type = 639;
                                        Main.tile[num1190, num1191].frameX = (short)(num1188 * 18 + 36 * num1183);
                                        Main.tile[num1190, num1191].frameY = (short)(num1189 * 18 + 36 * num1186);
                                    }
                                    if (!Main.tile[num1184 + num1188, num1187 + 2].active())
{
                                        Main.tile[num1184 + num1188, num1187 + 2].active(true);
                                        Main.tile[num1184 + num1188, num1187 + 2].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[num1184 + num1188, num1187 + 2].wall];
                                    }
                                    Main.tile[num1184 + num1188, num1187 + 2].slope(0);
                                    Main.tile[num1184 + num1188, num1187 + 2].halfBrick(false);
                                }
                            }
                            if (TileID.Sets.BasicChest[(int)Main.tile[num1151, num1152].type])
{
                                int num1192 = (int)(Main.tile[num1151, num1152].frameX / 18);
                                int num1193 = 0;
                                ushort num1194 = 21;
                                int num1195 = num1151;
                                int num1196 = num1152 - (int)(Main.tile[num1151, num1152].frameY / 18);
                                if (Main.tile[num1151, num1152].type == 467)
{
                                    num1194 = 467;
                                }
                                while (num1192 >= 2)
{
                                    num1193++;
                                    num1192 -= 2;
                                }
                                num1195 -= num1192;
                                int num1197 = Chest.FindChest(num1195, num1196);
                                if (num1197 != -1)
{
                                    int type11 = Main.chest[num1197].item[0].type;
                                    if (type11 != 1156)
{
                                        if (type11 != 1260)
{
                                            switch (type11)
{
                                            case 1569:
                                                num1193 = 25;
                                                break;
                                            case 1571:
                                                num1193 = 24;
                                                break;
                                            case 1572:
                                                num1193 = 27;
                                                break;
                                            }
                                        }
                                        else
{
                                            num1193 = 26;
                                        }
                                    }
                                    else
{
                                        num1193 = 23;
                                    }
                                }
                                for (int num1198 = 0; num1198 < 2; num1198++)
{
                                    for (int num1199 = 0; num1199 < 2; num1199++)
{
                                        int num1200 = num1195 + num1198;
                                        int num1201 = num1196 + num1199;
                                        Main.tile[num1200, num1201].active(true);
                                        Main.tile[num1200, num1201].slope(0);
                                        Main.tile[num1200, num1201].halfBrick(false);
                                        Main.tile[num1200, num1201].type = num1194;
                                        Main.tile[num1200, num1201].frameX = (short)(num1198 * 18 + 36 * num1193);
                                        Main.tile[num1200, num1201].frameY = (short)(num1199 * 18);
                                    }
                                    if (!Main.tile[num1195 + num1198, num1196 + 2].active())
{
                                        Main.tile[num1195 + num1198, num1196 + 2].active(true);
                                        Main.tile[num1195 + num1198, num1196 + 2].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[num1195 + num1198, num1196 + 2].wall];
                                    }
                                    Main.tile[num1195 + num1198, num1196 + 2].slope(0);
                                    Main.tile[num1195 + num1198, num1196 + 2].halfBrick(false);
                                }
                            }
                            if (Main.tile[num1151, num1152].type == 28)
{
                                int num1202 = (int)(Main.tile[num1151, num1152].frameX / 18);
                                int num1203 = 0;
                                int num1204 = num1151;
                                while (num1202 >= 2)
{
                                    num1203++;
                                    num1202 -= 2;
                                }
                                num1204 -= num1202;
                                int num1205 = (int)(Main.tile[num1151, num1152].frameY / 18);
                                int num1206 = 0;
                                int num1207 = num1152;
                                while (num1205 >= 2)
{
                                    num1206++;
                                    num1205 -= 2;
                                }
                                num1207 -= num1205;
                                for (int num1208 = 0; num1208 < 2; num1208++)
{
                                    for (int num1209 = 0; num1209 < 2; num1209++)
{
                                        int num1210 = num1204 + num1208;
                                        int num1211 = num1207 + num1209;
                                        Main.tile[num1210, num1211].active(true);
                                        Main.tile[num1210, num1211].slope(0);
                                        Main.tile[num1210, num1211].halfBrick(false);
                                        Main.tile[num1210, num1211].type = 28;
                                        Main.tile[num1210, num1211].frameX = (short)(num1208 * 18 + 36 * num1203);
                                        Main.tile[num1210, num1211].frameY = (short)(num1209 * 18 + 36 * num1206);
                                    }
                                    if (!Main.tile[num1204 + num1208, num1207 + 2].active())
{
                                        Main.tile[num1204 + num1208, num1207 + 2].active(true);
                                        Main.tile[num1204 + num1208, num1207 + 2].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[num1204 + num1208, num1207 + 2].wall];
                                    }
                                    Main.tile[num1204 + num1208, num1207 + 2].slope(0);
                                    Main.tile[num1204 + num1208, num1207 + 2].halfBrick(false);
                                }
                            }
                            if (Main.tile[num1151, num1152].type == 26)
{
                                int num1212 = (int)(Main.tile[num1151, num1152].frameX / 18);
                                int num1213 = 0;
                                int num1214 = num1151;
                                int num1215 = num1152 - (int)(Main.tile[num1151, num1152].frameY / 18);
                                while (num1212 >= 3)
{
                                    num1213++;
                                    num1212 -= 3;
                                }
                                num1214 -= num1212;
                                if (WorldGen.drunkWorldGen)
{
                                    if (Main.tile[num1151, num1152].wall == 83)
{
                                        num1213 = 1;
                                    }
                                    else
{
                                        num1213 = 0;
                                    }
                                }
                                else if (WorldGen.crimson)
{
                                    num1213 = 1;
                                }
                                else
{
                                    num1213 = 0;
                                }
                                for (int num1216 = 0; num1216 < 3; num1216++)
{
                                    for (int num1217 = 0; num1217 < 2; num1217++)
{
                                        int num1218 = num1214 + num1216;
                                        int num1219 = num1215 + num1217;
                                        Main.tile[num1218, num1219].active(true);
                                        Main.tile[num1218, num1219].slope(0);
                                        Main.tile[num1218, num1219].halfBrick(false);
                                        Main.tile[num1218, num1219].type = 26;
                                        Main.tile[num1218, num1219].frameX = (short)(num1216 * 18 + 54 * num1213);
                                        Main.tile[num1218, num1219].frameY = (short)(num1217 * 18);
                                    }
                                    if (!Main.tile[num1214 + num1216, num1215 + 2].active())
{
                                        Main.tile[num1214 + num1216, num1215 + 2].active(true);
                                        Main.tile[num1214 + num1216, num1215 + 2].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[num1214 + num1216, num1215 + 2].wall];
                                    }
                                    if ((!Main.tileSolid[(int)Main.tile[num1214 + num1216, num1215 + 2].type] || Main.tileSolidTop[(int)Main.tile[num1214 + num1216, num1215 + 2].type]) && !TileID.Sets.Platforms[(int)Main.tile[num1214 + num1216, num1215 + 2].type])
{
                                        Main.tile[num1214 + num1216, num1215 + 2].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[num1214 + num1216, num1215 + 2].wall];
                                    }
                                    Main.tile[num1214 + num1216, num1215 + 2].slope(0);
                                    Main.tile[num1214 + num1216, num1215 + 2].halfBrick(false);
                                    if (Main.tile[num1214 + num1216, num1215 + 3].type == 28 && Main.tile[num1214 + num1216, num1215 + 3].frameY % 36 >= 18)
{
                                        Main.tile[num1214 + num1216, num1215 + 3].type = 0;
                                        Main.tile[num1214 + num1216, num1215 + 3].active(false);
                                    }
                                }
                                for (int num1220 = 0; num1220 < 3; num1220++)
{
                                    if ((Main.tile[num1214 - 1, num1215 + num1220].type == 28 || Main.tile[num1214 - 1, num1215 + num1220].type == 12 || Main.tile[num1214 - 1, num1215 + num1220].type == 639) && Main.tile[num1214 - 1, num1215 + num1220].frameX % 36 < 18)
{
                                        Main.tile[num1214 - 1, num1215 + num1220].type = 0;
                                        Main.tile[num1214 - 1, num1215 + num1220].active(false);
                                    }
                                    if ((Main.tile[num1214 + 3, num1215 + num1220].type == 28 || Main.tile[num1214 + 3, num1215 + num1220].type == 12 || Main.tile[num1214 - 1, num1215 + num1220].type == 639) && Main.tile[num1214 + 3, num1215 + num1220].frameX % 36 >= 18)
{
                                        Main.tile[num1214 + 3, num1215 + num1220].type = 0;
                                        Main.tile[num1214 + 3, num1215 + num1220].active(false);
                                    }
                                }
                            }
                            if (Main.tile[num1151, num1152].type == 237 && Main.tile[num1151, num1152 + 1].type == 232)
{
                                Main.tile[num1151, num1152 + 1].type = 226;
                            }
                        }
                    }
                }
                Main.tileSolid[379] = true;
            });
            WorldGen.AddGenerationPass(GenPassNameID.LihzahrdAltar, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Set(1.0);
                for (int num1221 = 0; num1221 < 3; num1221++)
                {
                    for (int num1222 = 0; num1222 < 2; num1222++)
                    {
                        int num1223 = GenVars.lAltarX + num1221;
                        int num1224 = GenVars.lAltarY + num1222;
                        Main.tile[num1223, num1224].active(true);
                        Main.tile[num1223, num1224].type = 237;
                        Main.tile[num1223, num1224].frameX = (short)(num1221 * 18);
                        Main.tile[num1223, num1224].frameY = (short)(num1222 * 18);
                    }
                    Main.tile[GenVars.lAltarX + num1221, GenVars.lAltarY + 2].active(true);
                    Main.tile[GenVars.lAltarX + num1221, GenVars.lAltarY + 2].slope(0);
                    Main.tile[GenVars.lAltarX + num1221, GenVars.lAltarY + 2].halfBrick(false);
                    Main.tile[GenVars.lAltarX + num1221, GenVars.lAltarY + 2].type = 226;
                }
                for (int num1225 = 0; num1225 < 3; num1225++)
                {
                    for (int num1226 = 0; num1226 < 2; num1226++)
                    {
                        int num1227 = GenVars.lAltarX + num1225;
                        int num1228 = GenVars.lAltarY + num1226;
                        WorldGen.SquareTileFrame(num1227, num1228, true);
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.MicroBiomes, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[76].Value;
                double num1229 = (double)(Main.maxTilesX * Main.maxTilesY) / 5040000.0;
                double num1230 = 10.0;
                float num1231 = 0f;
                float num1232 = 1f / (float)num1230;
                int num1233 = 3000;
                if (!WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
                {
                    if (WorldGen.getGoodWorldGen || WorldGen.noTrapsWorldGen)
                    {
                        num1230 *= 3.0;
                    }
                    DeadMansChestBiome deadMansChestBiome = GenVars.configuration.CreateBiome<DeadMansChestBiome>();
                    List<int> possibleChestsToTrapify = deadMansChestBiome.GetPossibleChestsToTrapify(GenVars.structures);
                    int random4 = passConfig.Get<WorldGenRange>("DeadManChests").GetRandom(WorldGen.genRand);
                    int num1234 = 0;
                    while (num1234 < random4 && possibleChestsToTrapify.Count > 0)
                    {
                        float num1235 = (float)num1234 / (float)random4;
                        progress.Set((double)(num1231 + num1235 * num1232));
                        num1233--;
                        if (num1233 <= 0)
{
                            break;
                        }
                        int num1236 = possibleChestsToTrapify[WorldGen.genRand.Next(possibleChestsToTrapify.Count)];
                        Point point7 = new Point(Main.chest[num1236].x, Main.chest[num1236].y);
                        deadMansChestBiome.Place(point7, GenVars.structures);
                        num1234++;
                        possibleChestsToTrapify.Remove(num1236);
                    }
                }
                progress.Set((double)num1232);
                if (!WorldGen.notTheBees || WorldGen.remixWorldGen)
                {
                    num1231 = 1f / (float)num1230;
                    ThinIceBiome thinIceBiome = GenVars.configuration.CreateBiome<ThinIceBiome>();
                    int random5 = passConfig.Get<WorldGenRange>("ThinIcePatchCount").GetRandom(WorldGen.genRand);
                    int num1237 = 0;
                    int num1238 = 1000;
                    int num1239 = 0;
                    while (num1239 < random5)
                    {
                        float num1240 = (float)num1239 / (float)random5;
                        progress.Set((double)(num1231 + num1240 * num1232));
                        Point point8 = WorldGen.RandomWorldPoint((int)Main.worldSurface + 20, 50, 200, 50);
                        bool flag79 = true;
                        if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(point8.X, point8.Y, 0, false))
{
                            flag79 = false;
                        }
                        if (flag79 && thinIceBiome.Place(point8, GenVars.structures))
{
                            num1239++;
                            num1237 = 0;
                        }
                        else
{
                            num1237++;
                            if (num1237 > num1238)
{
                                num1239++;
                                num1237 = 0;
                            }
                        }
                    }
                }
                progress.Set(0.1);
                progress.Set((double)(num1232 * 2f));
                if (!WorldGen.SecretSeed.Variations.noSurfaceNoSwordShrines)
                {
                    num1231 = 2f / (float)num1230;
                    EnchantedSwordBiome enchantedSwordBiome = GenVars.configuration.CreateBiome<EnchantedSwordBiome>();
                    int num1241 = passConfig.Get<WorldGenRange>("SwordShrineAttempts").GetRandom(WorldGen.genRand);
                    double num1242 = passConfig.Get<double>("SwordShrinePlacementChance");
                    if (WorldGen.tenthAnniversaryWorldGen)
                    {
                        num1241 *= 2;
                        num1242 /= 2.0;
                    }
                    if (WorldGen.SecretSeed.errorWorld.Enabled && 6 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0) > 1)
                    {
                        num1241 *= 6 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0);
                        num1242 /= (double)(6 / WorldGen.SecretSeed.Variations.errorWorldAdjustment(1.0));
                    }
                    for (int num1243 = 0; num1243 < num1241; num1243++)
                    {
                        float num1244 = (float)num1243 / (float)num1241;
                        progress.Set((double)(num1231 + num1244 * num1232));
                        if ((num1243 == 0 && WorldGen.tenthAnniversaryWorldGen) || WorldGen.genRand.NextDouble() >= num1242)
{
                            int num1245 = 0;
                            while (num1245++ <= Main.maxTilesX)
{
                                Point point9;
                                point9.Y = (int)GenVars.worldSurface + WorldGen.genRand.Next(50, 100);
                                if (WorldGen.SecretSeed.errorWorld.Enabled && (WorldGen.genRand.Next(3) != 0 || WorldGen.SecretSeed.noSurface.Enabled))
{
                                    point9.Y = WorldGen.genRand.Next((int)GenVars.worldSurface + WorldGen.genRand.Next(50, 100), Main.UnderworldLayer - 100);
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    point9.X = WorldGen.genRand.Next(50, (int)((double)Main.maxTilesX * 0.3));
                                }
                                else
{
                                    point9.X = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.7), Main.maxTilesX - 50);
                                }
                                if (WorldGen.SecretSeed.dualDungeons.Enabled)
{
                                    DungeonUtils.InAnyPotentialDungeonBounds(point9.X, point9.Y, 0, false);
                                }
                                if (enchantedSwordBiome.Place(point9, GenVars.structures))
{
                                    break;
                                }
                            }
                        }
                    }
                }
                progress.Set(0.2);
                progress.Set((double)(num1232 * 3f));
                if (!WorldGen.notTheBees || WorldGen.remixWorldGen)
                {
                    num1231 = 3f / (float)num1230;
                    CampsiteBiome campsiteBiome = GenVars.configuration.CreateBiome<CampsiteBiome>();
                    int random6 = passConfig.Get<WorldGenRange>("CampsiteCount").GetRandom(WorldGen.genRand);
                    num1233 = 1000;
                    int num1246 = 0;
                    while (num1246 < random6)
                    {
                        float num1247 = (float)num1246 / (float)random6;
                        progress.Set((double)(num1231 + num1247 * num1232));
                        num1233--;
                        if (num1233 <= 0)
{
                            break;
                        }
                        int num1248 = (int)Main.worldSurface;
                        if (WorldGen.SecretSeed.noSurface.Enabled)
{
                            num1248 = (int)Main.rockLayer / 4;
                        }
                        Point point10 = WorldGen.RandomWorldPoint(num1248, WorldGen.beachDistance, 200, WorldGen.beachDistance);
                        bool flag80 = true;
                        if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(point10.X, point10.Y, 0, false))
{
                            flag80 = false;
                        }
                        if (flag80 && campsiteBiome.Place(point10, GenVars.structures))
{
                            num1246++;
                        }
                    }
                }
                progress.Set((double)(num1232 * 4f));
                if (!WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
                {
                    num1231 = 4f / (float)num1230;
                    if (!WorldGen.notTheBees || WorldGen.remixWorldGen)
                    {
                        MiningExplosivesBiome miningExplosivesBiome = GenVars.configuration.CreateBiome<MiningExplosivesBiome>();
                        int num1249 = passConfig.Get<WorldGenRange>("ExplosiveTrapCount").GetRandom(WorldGen.genRand);
                        if ((WorldGen.getGoodWorldGen || WorldGen.noTrapsWorldGen) && !WorldGen.notTheBees)
{
                            num1249 = (int)((double)num1249 * 1.5);
                        }
                        num1233 = 3000;
                        int num1250 = 0;
                        while (num1250 < num1249)
{
                            float num1251 = (float)num1250 / (float)num1249;
                            progress.Set((double)(num1231 + num1251 * num1232));
                            num1233--;
                            if (num1233 <= 0)
{
                                break;
                            }
                            int num1252 = (int)GenVars.rockLayer;
                            int num1253 = 200;
                            if (WorldGen.remixWorldGen)
{
                                num1252 = (int)Main.worldSurface;
                                num1253 = (int)GenVars.rockLayer;
                            }
                            Point point11 = WorldGen.RandomWorldPoint(num1252, WorldGen.beachDistance, num1253, WorldGen.beachDistance);
                            bool flag81 = true;
                            if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(point11.X, point11.Y, 0, false))
{
                                flag81 = false;
                            }
                            if (flag81 && miningExplosivesBiome.Place(point11, GenVars.structures))
{
                                num1250++;
                            }
                        }
                    }
                }
                progress.Set(0.3);
                progress.Set((double)(num1232 * 5f));
                num1231 = 5f / (float)num1230;
                MahoganyTreeBiome mahoganyTreeBiome = GenVars.configuration.CreateBiome<MahoganyTreeBiome>();
                int random7 = passConfig.Get<WorldGenRange>("LivingTreeCount").GetRandom(WorldGen.genRand);
                int num1254 = 0;
                int num1255 = 0;
                while (num1254 < random7 && num1255 < 20000)
                {
                    float num1256 = (float)num1254 / (float)random7;
                    progress.Set((double)(num1231 + num1256 * num1232));
                    Point point12 = WorldGen.RandomWorldPoint((int)Main.worldSurface + 50, 50, 500, 50);
                    bool flag82 = true;
                    if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(point12.X, point12.Y, 0, false))
                    {
                        flag82 = false;
                    }
                    if (flag82 && mahoganyTreeBiome.Place(point12, GenVars.structures))
                    {
                        num1254++;
                    }
                    num1255++;
                }
                progress.Set(0.4);
                progress.Set((double)(num1232 * 6f));
                progress.Set((double)(num1232 * 7f));
                num1231 = 7f / (float)num1230;
                TrackGenerator trackGenerator = new TrackGenerator();
                int num1257 = passConfig.Get<WorldGenRange>("LongTrackCount").GetRandom(WorldGen.genRand);
                WorldGenRange worldGenRange = passConfig.Get<WorldGenRange>("LongTrackLength");
                int num1258 = Main.maxTilesX / 2;
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    num1258 /= 2;
                }
                if (WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    num1257 /= 2;
                }
                int num1259 = 0;
                int num1260 = 0;
                while (num1260 < num1257)
                {
                    float num1261 = (float)num1260 / (float)num1257;
                    progress.Set((double)(num1231 + num1261 * num1232));
                    Point point13 = WorldGen.RandomWorldPoint((int)Main.worldSurface, 10, 200, 10);
                    bool flag83 = true;
                    if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(point13.X, point13.Y, 0, false))
                    {
                        flag83 = false;
                    }
                    if (flag83 && trackGenerator.Place(point13, worldGenRange.ScaledMinimum, worldGenRange.ScaledMaximum))
                    {
                        num1260++;
                        num1259 = 0;
                    }
                    else
                    {
                        num1259++;
                        if (num1259 > num1258)
{
                            num1260++;
                            num1259 = 0;
                        }
                    }
                }
                progress.Set((double)(num1232 * 8f));
                num1231 = 8f / (float)num1230;
                num1257 = passConfig.Get<WorldGenRange>("StandardTrackCount").GetRandom(WorldGen.genRand);
                worldGenRange = passConfig.Get<WorldGenRange>("StandardTrackLength");
                num1259 = 0;
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    num1257 = (int)((double)num1257 * 1.5);
                }
                if (WorldGen.SecretSeed.dualDungeons.Enabled)
                {
                    num1257 /= 2;
                }
                int num1262 = 0;
                while (num1262 < num1257)
                {
                    float num1263 = (float)num1262 / (float)num1257;
                    progress.Set((double)(num1231 + num1263 * num1232));
                    Point point14 = WorldGen.RandomWorldPoint((int)Main.worldSurface, 10, 200, 10);
                    bool flag84 = true;
                    if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(point14.X, point14.Y, 0, false))
                    {
                        flag84 = false;
                    }
                    if (flag84 && trackGenerator.Place(point14, worldGenRange.ScaledMinimum, worldGenRange.ScaledMaximum))
                    {
                        num1262++;
                        num1259 = 0;
                    }
                    else
                    {
                        num1259++;
                        if (num1259 > num1258)
{
                            num1262++;
                            num1259 = 0;
                        }
                    }
                }
                progress.Set((double)(num1232 * 9f));
                if (!WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
                {
                    num1231 = 9f / (float)num1230;
                    if (!WorldGen.notTheBees)
                    {
                        double num1264 = (double)Main.maxTilesX * 0.02;
                        if (WorldGen.noTrapsWorldGen)
{
                            num1230 *= 5.0;
                        }
                        else if (WorldGen.getGoodWorldGen)
{
                            num1230 *= 2.0;
                        }
                        int num1265 = 0;
                        while ((double)num1265 < num1264)
{
                            float num1266 = (float)num1265 / (float)num1264;
                            progress.Set((double)(num1231 + num1266 * num1232));
                            for (int num1267 = 0; num1267 < 10150; num1267++)
{
                                int num1268 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                                int num1269 = WorldGen.genRand.Next(GenVars.lavaLine - 100, Main.maxTilesY - 210);
                                bool flag85 = true;
                                if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(num1268, num1269, 0, false))
{
                                    flag85 = false;
                                }
                                if (flag85 && WorldGen.placeLavaTrap(num1268, num1269))
{
                                    break;
                                }
                            }
                            num1265++;
                        }
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.LilypadsCattailsBambooAndSeaweed, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (WorldGen.Skyblock.denyAllGeneration)
                {
                    return;
                }
                progress.Message = Lang.gen[88].Value;
                int num1270 = (int)Main.worldSurface;
                if (WorldGen.remixWorldGen)
                {
                    num1270 = Main.maxTilesY - 200;
                }
                for (int num1271 = 20; num1271 < Main.maxTilesX - 20; num1271++)
                {
                    progress.Set((double)num1271 / (double)Main.maxTilesX);
                    for (int num1272 = 1; num1272 < num1270; num1272++)
                    {
                        if (WorldGen.genRand.Next(5) == 0 && Main.tile[num1271, num1272].liquid > 0)
{
                            if (!Main.tile[num1271, num1272].active())
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    WorldGen.PlaceLilyPad(num1271, num1272);
                                }
                                else
{
                                    Point point15 = WorldGen.PlaceCatTail(num1271, num1272);
                                    if (WorldGen.InWorld(point15.X, point15.Y, 0))
{
                                        int num1273 = WorldGen.genRand.Next(14);
                                        for (int num1274 = 0; num1274 < num1273; num1274++)
{
                                            WorldGen.GrowCatTail(point15.X, point15.Y);
                                        }
                                        WorldGen.SquareTileFrame(point15.X, point15.Y, true);
                                    }
                                }
                            }
                            if ((!Main.tile[num1271, num1272].active() || Main.tile[num1271, num1272].type == 61 || Main.tile[num1271, num1272].type == 74) && WorldGen.PlaceBamboo(num1271, num1272))
{
                                int num1275 = WorldGen.genRand.Next(10, 20);
                                int num1276 = 0;
                                while (num1276 < num1275 && WorldGen.PlaceBamboo(num1271, num1272 - num1276))
{
                                    num1276++;
                                }
                            }
                        }
                    }
                    int num1277 = Main.UnderworldLayer;
                    while ((double)num1277 > Main.worldSurface)
                    {
                        if (Main.tile[num1271, num1277].active())
{
                            if (Main.tile[num1271, num1277].type == 53 && WorldGen.genRand.Next(3) != 0)
{
                                WorldGen.GrowCheckSeaweed(num1271, num1277);
                            }
                            else if (Main.tile[num1271, num1277].type == 549)
{
                                WorldGen.GrowCheckSeaweed(num1271, num1277);
                            }
                        }
                        num1277--;
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.SpeleothemsAndGemTrees, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                progress.Message = Language.GetTextValue("WorldGeneration.Speleothems");
                progress.Set(0.0);
                int num1278 = Main.maxTilesX - 20;
                for (int num1279 = 20; num1279 < Main.maxTilesX - 20; num1279++)
                {
                    if (progress != null)
                    {
                        float num1280 = (float)num1279 / (float)num1278;
                        progress.Set((double)num1280);
                    }
                    for (int num1281 = (int)Main.worldSurface; num1281 < Main.maxTilesY - 20; num1281++)
                    {
                        if ((Main.tenthAnniversaryWorld || WorldGen.drunkWorldGen || WorldGen.genRand.Next(5) == 0) && Main.tile[num1279, num1281 - 1].liquid == 0)
{
                            int num1282 = WorldGen.genRand.Next(7);
                            int num1283 = 0;
                            switch (num1282)
{
                            case 0:
                                num1283 = 583;
                                break;
                            case 1:
                                num1283 = 584;
                                break;
                            case 2:
                                num1283 = 585;
                                break;
                            case 3:
                                num1283 = 586;
                                break;
                            case 4:
                                num1283 = 587;
                                break;
                            case 5:
                                num1283 = 588;
                                break;
                            case 6:
                                num1283 = 589;
                                break;
                            }
                            WorldGen.TryGrowingTreeByType(num1283, num1279, num1281, 0, false);
                        }
                        if (!WorldGen.oceanDepths(num1279, num1281) && !Main.tile[num1279, num1281].active() && WorldGen.genRand.Next(5) == 0)
{
                            if ((Main.tile[num1279, num1281 - 1].type == 1 || Main.tile[num1279, num1281 - 1].type == 147 || Main.tile[num1279, num1281 - 1].type == 161 || Main.tile[num1279, num1281 - 1].type == 25 || Main.tile[num1279, num1281 - 1].type == 203 || Main.tileStone[(int)Main.tile[num1279, num1281 - 1].type] || Main.tileMoss[(int)Main.tile[num1279, num1281 - 1].type]) && !Main.tile[num1279, num1281].active() && !Main.tile[num1279, num1281 + 1].active())
{
                                Main.tile[num1279, num1281 - 1].slope(0);
                            }
                            if ((Main.tile[num1279, num1281 + 1].type == 1 || Main.tile[num1279, num1281 + 1].type == 147 || Main.tile[num1279, num1281 + 1].type == 161 || Main.tile[num1279, num1281 + 1].type == 25 || Main.tile[num1279, num1281 + 1].type == 203 || Main.tileStone[(int)Main.tile[num1279, num1281 + 1].type] || Main.tileMoss[(int)Main.tile[num1279, num1281 + 1].type]) && !Main.tile[num1279, num1281].active() && !Main.tile[num1279, num1281 - 1].active())
{
                                Main.tile[num1279, num1281 + 1].slope(0);
                            }
                            WorldGen.PlaceTight(num1279, num1281, false);
                        }
                    }
                    for (int num1284 = 5; num1284 < (int)Main.worldSurface; num1284++)
                    {
                        if (Main.tile[num1279, num1284 - 1].active() && (Main.tile[num1279, num1284 - 1].type == 147 || Main.tile[num1279, num1284 - 1].type == 161) && WorldGen.genRand.Next(5) == 0)
{
                            if (!Main.tile[num1279, num1284].active() && !Main.tile[num1279, num1284 + 1].active())
{
                                Main.tile[num1279, num1284 - 1].slope(0);
                            }
                            WorldGen.PlaceTight(num1279, num1284, false);
                        }
                        if (Main.tile[num1279, num1284 - 1].active() && (Main.tile[num1279, num1284 - 1].type == 25 || Main.tile[num1279, num1284 - 1].type == 203) && WorldGen.genRand.Next(5) == 0)
{
                            if (!Main.tile[num1279, num1284].active() && !Main.tile[num1279, num1284 + 1].active())
{
                                Main.tile[num1279, num1284 - 1].slope(0);
                            }
                            WorldGen.PlaceTight(num1279, num1284, false);
                        }
                        if (Main.tile[num1279, num1284 + 1].active() && (Main.tile[num1279, num1284 + 1].type == 25 || Main.tile[num1279, num1284 + 1].type == 203) && WorldGen.genRand.Next(5) == 0)
{
                            if (!Main.tile[num1279, num1284].active() && !Main.tile[num1279, num1284 - 1].active())
{
                                Main.tile[num1279, num1284 + 1].slope(0);
                            }
                            WorldGen.PlaceTight(num1279, num1284, false);
                        }
                    }
                }
                progress.Set(1.0);
            });
            WorldGen.AddGenerationPass(GenPassNameID.BrokenTrapCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                if (!WorldGen.noTrapsWorldGen || WorldGen.tenthAnniversaryWorldGen || WorldGen.notTheBees)
                {
                    progress.Message = Lang.gen[82].Value;
                    List<Point> list2 = new List<Point>();
                    int num1285 = 50;
                    for (int num1286 = num1285; num1286 < Main.maxTilesX - num1285; num1286++)
                    {
                        double num1287 = (double)(num1286 - num1285) / (double)(Main.maxTilesX - num1285 * 2);
                        progress.Set(num1287);
                        for (int num1288 = 50; num1288 < Main.maxTilesY - 50; num1288++)
{
                            if (Main.tile[num1286, num1288].wire() && !list2.Contains(new Point(num1286, num1288)))
{
                                WorldGen.ClearBrokenTraps(new Point(num1286, num1288), list2);
                            }
                        }
                    }
                }
            });
            WorldGen.AddGenerationPass(GenPassNameID.FinalCleanup, delegate(GenerationProgress progress, GameConfiguration passConfig)
            {
                Main.tileSolid[484] = false;
                WorldGen.FillWallHolesInArea(new Rectangle(0, 0, Main.maxTilesX, (int)Main.worldSurface));
                progress.Message = Lang.gen[86].Value;
                if (WorldGen.SecretSeed.Variations.surfaceIsDesertNormalFunction)
                {
                    WorldGen.SecretSeed.DoSurfaceIsDesert();
                }
                for (int num1289 = 0; num1289 < Main.maxTilesX; num1289++)
                {
                    progress.Set((double)num1289 / (double)Main.maxTilesX);
                    for (int num1290 = 0; num1290 < Main.maxTilesY; num1290++)
                    {
                        if (Main.tile[num1289, num1290].active() && !WorldGen.SolidTile(num1289, num1290 + 1, false) && (Main.tile[num1289, num1290].type == 53 || Main.tile[num1289, num1290].type == 112 || Main.tile[num1289, num1290].type == 234 || Main.tile[num1289, num1290].type == 224 || Main.tile[num1289, num1290].type == 123))
{
                            if ((double)num1290 < Main.worldSurface + 10.0 && !Main.tile[num1289, num1290 + 1].active() && Main.tile[num1289, num1290 + 1].wall != 191 && !WorldGen.oceanDepths(num1289, num1290))
{
                                int num1291 = 10;
                                int num1292 = num1290 + 1;
                                int num1293 = num1292;
                                while (num1293 < num1292 + 10)
{
                                    if (Main.tile[num1289, num1293].active() && Main.tile[num1289, num1293].type == 314)
{
                                        num1291 = 0;
                                        IL_025A:
                                        while (!Main.tile[num1289, num1292].active() && num1291 > 0 && num1292 < Main.maxTilesY - 50)
{
                                            Main.tile[num1289, num1292 - 1].slope(0);
                                            Main.tile[num1289, num1292 - 1].halfBrick(false);
                                            Main.tile[num1289, num1292].active(true);
                                            Main.tile[num1289, num1292].type = Main.tile[num1289, num1290].type;
                                            Main.tile[num1289, num1292].slope(0);
                                            Main.tile[num1289, num1292].halfBrick(false);
                                            num1292++;
                                            num1291--;
                                        }
                                        if (num1291 == 0 && !Main.tile[num1289, num1292].active())
{
                                            ushort num1294 = Main.tile[num1289, num1290].type;
                                            if (num1294 <= 112)
{
                                                if (num1294 == 53)
{
                                                    Main.tile[num1289, num1292].type = 397;
                                                    Main.tile[num1289, num1292].active(true);
                                                    goto IL_05BE;
                                                }
                                                if (num1294 != 112)
{
                                                    goto IL_05BE;
                                                }
                                                Main.tile[num1289, num1292].type = 398;
                                                Main.tile[num1289, num1292].active(true);
                                                goto IL_05BE;
                                            }
                                            else
{
                                                if (num1294 == 123)
{
                                                    Main.tile[num1289, num1292].type = 1;
                                                    Main.tile[num1289, num1292].active(true);
                                                    goto IL_05BE;
                                                }
                                                if (num1294 == 224)
{
                                                    Main.tile[num1289, num1292].type = 147;
                                                    Main.tile[num1289, num1292].active(true);
                                                    goto IL_05BE;
                                                }
                                                if (num1294 != 234)
{
                                                    goto IL_05BE;
                                                }
                                                Main.tile[num1289, num1292].type = 399;
                                                Main.tile[num1289, num1292].active(true);
                                                goto IL_05BE;
                                            }
                                        }
                                        else
{
                                            if (Main.tile[num1289, num1292].active() && Main.tileSolid[(int)Main.tile[num1289, num1292].type] && !Main.tileSolidTop[(int)Main.tile[num1289, num1292].type])
{
                                                Main.tile[num1289, num1292].slope(0);
                                                Main.tile[num1289, num1292].halfBrick(false);
                                                goto IL_05BE;
                                            }
                                            goto IL_05BE;
                                        }
                                    }
                                    else
{
                                        num1293++;
                                    }
                                }
                                goto IL_025A;
                            }
                            if (Main.tileSolid[(int)Main.tile[num1289, num1290 + 1].type] && !Main.tileSolidTop[(int)Main.tile[num1289, num1290 + 1].type] && (Main.tile[num1289, num1290 + 1].topSlope() || Main.tile[num1289, num1290 + 1].halfBrick()))
{
                                Main.tile[num1289, num1290 + 1].slope(0);
                                Main.tile[num1289, num1290 + 1].halfBrick(false);
                            }
                            else
{
                                ushort num1294 = Main.tile[num1289, num1290].type;
                                if (num1294 <= 112)
{
                                    if (num1294 != 53)
{
                                        if (num1294 == 112)
{
                                            Main.tile[num1289, num1290].type = 398;
                                        }
                                    }
                                    else
{
                                        Main.tile[num1289, num1290].type = 397;
                                    }
                                }
                                else if (num1294 != 123)
{
                                    if (num1294 != 224)
{
                                        if (num1294 == 234)
{
                                            Main.tile[num1289, num1290].type = 399;
                                        }
                                    }
                                    else
{
                                        Main.tile[num1289, num1290].type = 147;
                                    }
                                }
                                else
{
                                    Main.tile[num1289, num1290].type = 1;
                                }
                            }
                            IL_05BE:
                            if (Main.tile[num1289, num1290 - 1].type == 323)
{
                                WorldGen.TileFrame(num1289, num1290 - 1, false, false);
                            }
                        }
                        if ((Main.tile[num1289, num1290].wall == 187 || Main.tile[num1289, num1290].wall == 216) && Main.tile[num1289, num1290].liquid > 0 && !WorldGen.remixWorldGen && !Main.dualDungeonsSeed)
{
                            Main.tile[num1289, num1290].liquid = byte.MaxValue;
                            Main.tile[num1289, num1290].lava(true);
                        }
                        if (Main.tile[num1289, num1290].type == 137)
{
                            Main.tile[num1289, num1290].slope(0);
                            Main.tile[num1289, num1290].halfBrick(false);
                        }
                        if (Main.tile[num1289, num1290].active() && TileID.Sets.Boulders[(int)Main.tile[num1289, num1290].type])
{
                            int num1295 = (int)(Main.tile[num1289, num1290].frameX / 18);
                            int num1296 = num1289;
                            num1296 -= num1295;
                            int num1297 = (int)(Main.tile[num1289, num1290].frameY / 18);
                            int num1298 = num1290;
                            num1298 -= num1297;
                            bool flag86 = false;
                            for (int num1299 = 0; num1299 < 2; num1299++)
{
                                Tile tile32 = Main.tile[num1296 + num1299, num1298 - 1];
                                if (tile32 != null && tile32.active() && tile32.type == 26)
{
                                    flag86 = true;
                                    break;
                                }
                                for (int num1300 = 0; num1300 < 2; num1300++)
{
                                    int num1301 = num1296 + num1299;
                                    int num1302 = num1298 + num1300;
                                    Main.tile[num1301, num1302].active(true);
                                    Main.tile[num1301, num1302].slope(0);
                                    Main.tile[num1301, num1302].halfBrick(false);
                                    Main.tile[num1301, num1302].type = Main.tile[num1289, num1290].type;
                                    Main.tile[num1301, num1302].frameX = (short)(num1299 * 18);
                                    Main.tile[num1301, num1302].frameY = (short)(num1300 * 18);
                                }
                            }
                            if (flag86)
{
                                ushort num1303 = 0;
                                if (Main.tile[num1289, num1290].type == 484)
{
                                    num1303 = 397;
                                }
                                for (int num1304 = 0; num1304 < 2; num1304++)
{
                                    for (int num1305 = 0; num1305 < 2; num1305++)
{
                                        int num1306 = num1296 + num1304;
                                        int num1307 = num1298 + num1305;
                                        Main.tile[num1306, num1307].active(true);
                                        Main.tile[num1306, num1307].slope(0);
                                        Main.tile[num1306, num1307].halfBrick(false);
                                        Main.tile[num1306, num1307].type = num1303;
                                        Main.tile[num1306, num1307].frameX = 0;
                                        Main.tile[num1306, num1307].frameY = 0;
                                    }
                                }
                            }
                        }
                        if (Main.tile[num1289, num1290].type == 323 && Main.tile[num1289, num1290].liquid > 0)
{
                            WorldGen.KillTile(num1289, num1290, false, false, false);
                        }
                        if (Main.wallDungeon[(int)Main.tile[num1289, num1290].wall])
{
                            Main.tile[num1289, num1290].liquidType(0);
                            if (Main.tile[num1289, num1290].type == 374)
{
                                Main.tile[num1289, num1290].type = 373;
                            }
                            if (Main.tile[num1289, num1290].active() && Main.tile[num1289, num1290].type == 56)
{
                                WorldGen.KillTile(num1289, num1290, false, false, false);
                                Main.tile[num1289, num1290].liquidType(0);
                                Main.tile[num1289, num1290].liquid = byte.MaxValue;
                            }
                        }
                        if (Main.tile[num1289, num1290].active() && Main.tile[num1289, num1290].type == 314 && !WorldGen.SecretSeed.extraLiquid.Enabled)
{
                            int num1308 = 15;
                            int num1309 = 1;
                            int num1310 = num1290;
                            while (num1290 - num1310 < num1308)
{
                                Main.tile[num1289, num1310].liquid = 0;
                                num1310--;
                            }
                            num1310 = num1290;
                            while (num1310 - num1290 < num1309)
{
                                Main.tile[num1289, num1310].liquid = 0;
                                num1310++;
                            }
                        }
                        if (Main.tile[num1289, num1290].active() && Main.tile[num1289, num1290].type == 332 && !Main.tile[num1289, num1290 + 1].active())
{
                            Main.tile[num1289, num1290 + 1].ClearEverything();
                            Main.tile[num1289, num1290 + 1].active(true);
                            Main.tile[num1289, num1290 + 1].type = 332;
                        }
                        if (num1289 > WorldGen.beachDistance && num1289 < Main.maxTilesX - WorldGen.beachDistance && (double)num1290 < Main.worldSurface && Main.tile[num1289, num1290].liquid > 0 && Main.tile[num1289, num1290].liquid < 255 && Main.tile[num1289 - 1, num1290].liquid < 255 && Main.tile[num1289 + 1, num1290].liquid < 255 && Main.tile[num1289, num1290 + 1].liquid < 255 && (!Main.tile[num1289 - 1, num1290].active() || !TileID.Sets.Clouds[(int)Main.tile[num1289 - 1, num1290].type]) && (!Main.tile[num1289 + 1, num1290].active() || !TileID.Sets.Clouds[(int)Main.tile[num1289 + 1, num1290].type]) && (!Main.tile[num1289, num1290 + 1].active() || !TileID.Sets.Clouds[(int)Main.tile[num1289, num1290 + 1].type]))
{
                            Main.tile[num1289, num1290].liquid = 0;
                        }
                        if (Main.tile[num1289, num1290].active() && Main.tile[num1289, num1290].type >= 0 && TileID.Sets.Paintings[(int)Main.tile[num1289, num1290].type])
{
                            Tile tile33 = Main.tile[num1289, num1290];
                            if (tile33.wall <= 0 && WorldGen.InWorld(num1289, num1290, 2))
{
                                Tile tile34 = Main.tile[num1289 - 1, num1290];
                                Tile tile35 = Main.tile[num1289 + 1, num1290];
                                Tile tile36 = Main.tile[num1289, num1290 - 1];
                                Tile tile37 = Main.tile[num1289, num1290 + 1];
                                ushort num1311 = 0;
                                if (num1311 == 0 && tile34.wall > 0)
{
                                    num1311 = tile34.wall;
                                }
                                if (num1311 == 0 && tile35.wall > 0)
{
                                    num1311 = tile35.wall;
                                }
                                if (num1311 == 0 && tile36.wall > 0)
{
                                    num1311 = tile36.wall;
                                }
                                if (num1311 == 0 && tile37.wall > 0)
{
                                    num1311 = tile37.wall;
                                }
                                if (num1311 != 0)
{
                                    tile33.wall = num1311;
                                }
                            }
                        }
                        WorldGen.TileFrame(num1289, num1290, false, false);
                    }
                }
                int num1312 = 0;
                int num1313;
                switch (WorldGen.GetWorldSize())
                {
                default:
                    num1313 = 3;
                    break;
                case 1:
                    num1313 = 6;
                    break;
                case 2:
                    num1313 = 9;
                    break;
                }
                if (WorldGen.tenthAnniversaryWorldGen)
                {
                    num1313 *= 5;
                }
                int num1314 = 50;
                int num1315 = num1314;
                int num1316 = num1314;
                int num1317 = Main.maxTilesX - num1314;
                int num1318 = Main.maxTilesY - 200;
                int num1319 = 3000;
                while (num1312 < num1313)
                {
                    num1319--;
                    if (num1319 <= 0)
                    {
                        break;
                    }
                    int num1320 = WorldGen.genRand.Next(num1315, num1317);
                    int num1321 = WorldGen.genRand.Next(num1316, num1318);
                    Tile tile38 = Main.tile[num1320, num1321];
                    if (tile38.active() && tile38.type >= 0 && tile38.type < TileID.Count)
                    {
                        bool flag87 = TileID.Sets.Dirt[(int)tile38.type];
                        if (WorldGen.notTheBees)
{
                            flag87 = flag87 || TileID.Sets.Mud[(int)tile38.type];
                        }
                        if (flag87)
{
                            num1312++;
                            tile38.ClearTile();
                            tile38.active(true);
                            tile38.type = 668;
                        }
                    }
                }
                if (WorldGen.noTrapsWorldGen)
                {
                    WorldGen.FinishNoTraps();
                }
                if (Main.tenthAnniversaryWorld)
                {
                    WorldGen.FinishTenthAnniversaryWorld();
                }
                if (WorldGen.drunkWorldGen)
                {
                    WorldGen.FinishDrunkGen();
                }
                if (WorldGen.notTheBees)
                {
                    WorldGen.NotTheBees();
                    WorldGen.FinishNotTheBees();
                }
                if (WorldGen.getGoodWorldGen)
                {
                    WorldGen.FinishGetGoodWorld();
                }
                if (WorldGen.remixWorldGen)
                {
                    WorldGen.FinishRemixWorld();
                }
                if (SpecialSeedFeatures.ShimmerSpawnHalfOfWorld)
                {
                    int num1322 = Main.maxTilesX / 2;
                    WorldGen.ShimmerifySideOfWorld(Main.spawnTileX <= num1322);
                }
                if (SpecialSeedFeatures.RainbowSandAndBlackSandWalls)
                {
                    WorldGen.PaintTheSandRainbowAndSandWallsBlack();
                }
                Point point16 = new Point(Main.spawnTileX, Main.spawnTileY);
                if (Main.vampireSeed)
                {
                    if (!GenVars.worldSpawnHasBeenRandomized)
                    {
                        WorldGen.RandomizeWorldSpawn();
                        WorldGen.PlaceTorchesAroundSpawn(-1, -1);
                    }
                    WorldGen.PutMonsterVanityInChests();
                }
                WorldGen.SecretSeed.FinalizeSecretSeeds();
                if (Main.tenthAnniversaryWorld)
                {
                    WorldGen.FinishTenthAnniversaryWorldPaintTreesAndMushrooms();
                }
                WorldGen.ShimmerCleanUp();
                for (int num1323 = 0; num1323 < Main.maxTilesY; num1323++)
                {
                    for (int num1324 = 0; num1324 < Main.maxTilesX; num1324++)
                    {
                        Tile tile39 = Main.tile[num1324, num1323];
                        if (tile39.liquid > 0)
{
                            Liquid.LiquidCheck(num1324, num1323, (int)tile39.liquidType(), true);
                        }
                    }
                }
                ExtraSpawnPointManager.PrepareExtraSpawns();
                WorldGen.TownNPCPositionsCleanup(point16);
                WorldGen.notTheBees = false;
                WorldGen.getGoodWorldGen = false;
                Main.AnglerQuestSwap();
                progress.Message = Lang.gen[87].Value;
            });
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.AddGenerationPass(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldBuilding.StructureMap.AddProtectedStructure(), Terraria.WorldGen.AddSpikeCaves(), Terraria.WorldGen.SecretSeed.addTeleporters, System.array, Terraria.WorldGen.beachDistance, Terraria.ID.GenPassNameID.BeachesAndOceanCleanup, Terraria.ID.GenPassNameID.Beehives, Terraria.Tile.blockType(), Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration, Terraria.GameContent.Biomes.GraniteBiome.CanPlace(), Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldGen.CaveOpenater(), Terraria.WorldGen.Caverer(), Terraria.ID.GenPassNameID.CaveWallVariety, Terraria.WorldGen.Cavinator(), Microsoft.Xna.Framework.Rectangle.Center, Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldGen.ChasmRunner(), Terraria.ID.GenPassNameID.Clay, Terraria.WorldBuilding.ShapeData.Clear(), Terraria.WorldGen.ClearPendingLiquid(), Terraria.Tile.ClearSlope(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.WorldBuilding.GenVars.configuration, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.WorldBuilding.GenVars.copper, Terraria.ID.GenPassNameID.CorruptionAndCrimson, System.Math.Cos(), System.Collections.Generic.List< T >.Count, Terraria.WorldBuilding.ShapeData.Count, Terraria.WorldGen.CrimPlaceHearts(), Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldGen.CrimStart(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.ID.GenPassNameID.DemonAndCrimsonAltars, Terraria.WorldGen.Skyblock.denyAllGeneration, Terraria.WorldGen.Skyblock.denyFloatingIslands, Terraria.WorldGen.Skyblock.denySomeGeneration, Terraria.ID.GenPassNameID.DesertBiome, Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.SecretSeed.digExtraHoles, Terraria.ID.GenPassNameID.DirtInRocks, Terraria.ID.GenPassNameID.DirtLayerCaves, Terraria.ID.GenPassNameID.DirtRockWallRunner, Terraria.ID.GenPassNameID.DirtToMud, Terraria.ID.GenPassNameID.DirtWallBackgrounds, Terraria.ID.GenPassNameID.DirtWallCleanup, Terraria.WorldGen.DirtyRockRunner(), ReLogic.Utilities.Vector2D.Distance(), Terraria.WorldGen.SecretSeed.DoAddTeleporters(), Terraria.WorldGen.SecretSeed.DoDigExtraHoles(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddLiquid(), Terraria.WorldGen.SecretSeed.DoNoSurfaceFillTheTop(), Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.SecretSeed.DoPooEverywhere(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesertNoSurfaceCleanup(), Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms(), Terraria.WorldGen.SecretSeed.DoWorldIsFrozen(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.ID.GenPassNameID.DualDungeonsDitherSnake, Terraria.ID.GenPassNameID.DunesAndPyramidLocations, Terraria.ID.GenPassNameID.Dungeon, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.dungeonData, Terraria.WorldGen.DungeonDesertCleanup(), Terraria.WorldBuilding.GenVars.dungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonLocation, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonSide, System.E, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.Variations.errorWorldAdjustment(), Terraria.WorldBuilding.GenVars.evilBiomeAvoidanceMidFixer, Terraria.WorldBuilding.GenVars.evilBiomeBeachAvoidance, Terraria.WorldGen.SecretSeed.extraFloatingIslands, Terraria.WorldGen.SecretSeed.Variations.extraFloatingIslandsNormalAmount, Terraria.WorldGen.SecretSeed.Variations.extraFloatingIslandsReducedAmount, Terraria.WorldGen.SecretSeed.extraLiquid, Terraria.WorldGen.SecretSeed.extraLivingTrees, Terraria.WorldGen.SecretSeed.Variations.extraLivingTreesReducedAmount, Terraria.ID.TileID.Sets.Falling, Terraria.WorldGen.FindLowestCloud(), Terraria.WorldBuilding.GenVars.flipInfections, Terraria.WorldBuilding.GenVars.floatingIslandHouseX, Terraria.WorldBuilding.GenVars.floatingIslandHouseY, Terraria.ID.GenPassNameID.FloatingIslands, Terraria.WorldBuilding.GenVars.floatingIslandStyle, Terraria.ID.GenPassNameID.FragileIceOverIceBiomeWater, Terraria.ID.GenPassNameID.Gems, Terraria.Lang.gen, Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.WorldGen.GenerateSkyBlockWorld(), Terraria.WorldGen.GenerateUnderworldStartingMound(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionX, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Localization.Language.GetTextValue(), Terraria.ID.GenPassNameID.GlowingMushroomPatches, Terraria.WorldBuilding.GenVars.gold, Terraria.ID.GenPassNameID.Granite, Terraria.ID.GenPassNameID.Grass, Terraria.ID.GenPassNameID.GravitatingSandCleanup, Terraria.WorldGen.GrowLivingTree(), Terraria.Tile.halfBrick(), Terraria.ID.GenPassNameID.IceBiome, Terraria.GameContent.Generation.Dungeon.DungeonUtils.InAnyPotentialDungeonBounds(), int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IntersectsAnyPotentialDungeonBounds(), Terraria.WorldGen.InWorld(), Terraria.WorldBuilding.GenVars.iron, Terraria.WorldGen.IsTileNearby(), Terraria.WorldBuilding.GenVars.JChestX, Terraria.WorldBuilding.GenVars.JChestY, Terraria.WorldBuilding.GenVars.jungleHut, Terraria.WorldBuilding.GenVars.jungleOriginX, Terraria.ID.GenPassNameID.JungleShrines, Terraria.WorldGen.KillTile(), System.L, Terraria.ID.GenPassNameID.Lakes, Terraria.WorldBuilding.GenVars.lakesBeachAvoidance, Terraria.WorldBuilding.GenVars.LakeX, Terraria.Tile.lava(), Terraria.WorldGen.LavaLayerCaverer(), Terraria.WorldBuilding.GenVars.lavaLine, Terraria.WorldBuilding.DungeonSide.Left, Terraria.WorldBuilding.GenVars.leftBeachEnd, Terraria.ID.GenPassNameID.LihzahrdTemple, Terraria.Tile.liquid, Terraria.Tile.liquidType(), System.list, Terraria.ID.GenPassNameID.LivingTrees, Terraria.ID.GenPassNameID.LivingTreeWalls, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.ID.GenPassNameID.Marble, Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldBuilding.GenVars.maxLakes, Terraria.WorldBuilding.GenVars.maxMushroomBiomes, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldBuilding.GenVars.maxTunnels, Terraria.WorldBuilding.GenVars.mCaveX, Terraria.WorldBuilding.GenVars.mCaveY, System.Math.Min(), Terraria.ID.GenPassNameID.MountainCaveOpenings, Terraria.ID.GenPassNameID.MountainCaves, Terraria.WorldGen.Mountinater(), Terraria.ID.GenPassNameID.MudCavesToJungleGrass, Terraria.WorldBuilding.GenVars.mushroomBiomesPosition, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves, Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.SecretSeed.Variations.noSurfaceNoFloatingIslands, Terraria.WorldGen.SecretSeed.Variations.noSurfaceNoLivingTrees, Terraria.WorldGen.SecretSeed.Variations.noSurfaceNoPyramids, Terraria.WorldBuilding.GenVars.noTrapsAndForTheWorthyNoCelebration, Terraria.WorldGen.NotTheBees(), Terraria.WorldGen.notTheBees, Terraria.WorldBuilding.GenVars.notTheBeesAndForTheWorthyNoCelebration, Terraria.WorldBuilding.GenVars.numIslandHouses, Terraria.WorldBuilding.GenVars.numJChests, Terraria.WorldBuilding.GenVars.numLakes, Terraria.Liquid.numLiquid, Terraria.LiquidBuffer.numLiquidBuffer, Terraria.WorldBuilding.GenVars.numMCaves, Terraria.WorldBuilding.GenVars.numMushroomBiomes, Terraria.WorldBuilding.GenVars.numPyr, Terraria.WorldBuilding.GenVars.numTunnels, Terraria.ID.GenPassNameID.Oasis, Terraria.WorldGen.oceanCave(), Terraria.ID.GenPassNameID.OceanCaves, Terraria.WorldGen.oceanDepths(), Terraria.ID.GenPassNameID.OceanSand, Terraria.WorldBuilding.GenVars.oceanWaterForcedJungleLength, Terraria.WorldBuilding.GenVars.oceanWaterStartRandomMax, Terraria.WorldBuilding.GenVars.oceanWaterStartRandomMin, Terraria.ID.GenPassNameID.OresAndShinies, Terraria.WorldBuilding.GenAction.Output(), Terraria.GameContent.Biomes.DesertBiome.Place(), Terraria.GameContent.Biomes.DunesBiome.Place(), Terraria.GameContent.Biomes.GraniteBiome.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.MarbleBiome.Place(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.SecretSeed.pooEverywhere, Terraria.WorldGen.PoundTile(), Terraria.ID.TileID.Sets.PreventsSlopesDuringGeneration, Terraria.WorldGen.Pyramid(), Terraria.ID.GenPassNameID.Pyramids, Terraria.WorldBuilding.GenVars.PyrX, Terraria.WorldBuilding.GenVars.PyrY, Terraria.Liquid.QuickWater(), Terraria.WorldGen.RandomRectanglePoint(), Terraria.WorldGen.RandomWorldPoint(), Terraria.WorldBuilding.GenVars.remixMushroomLayerLow, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.ID.GenPassNameID.RemoveSurfaceWaterAboveSand, Terraria.Tile.ResetToType(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.WorldBuilding.DungeonSide.Right, Terraria.WorldBuilding.GenVars.rightBeachStart, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenVars.rockLayer, Terraria.ID.GenPassNameID.RockLayerCaves, Terraria.WorldBuilding.GenVars.rockLayerHigh, Terraria.WorldBuilding.GenVars.rockLayerLow, Terraria.ID.GenPassNameID.RocksInDirt, Terraria.WorldGen.SecretSeed.roundLandmasses, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.GenPassNameID.SandPatches, Terraria.WorldGen.ScanTileColumnAndRemoveClumps(), Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SetCrackedBrickSolidity(), Terraria.ID.GenPassNameID.SettleLiquids, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonData(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonDataVariables(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.SetupDungeonGenVarVariables(), Terraria.WorldGen.ShellPile(), Terraria.ID.GenPassNameID.ShellPilesMarblePilesAndSpikePits, Terraria.WorldBuilding.GenVars.shellStartXLeft, Terraria.WorldBuilding.GenVars.shellStartXRight, Terraria.WorldBuilding.GenVars.shellStartYLeft, Terraria.WorldBuilding.GenVars.shellStartYRight, Terraria.ID.GenPassNameID.Shimmer, Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldBuilding.GenVars.shimmerPosition, Terraria.WorldGen.shimmerSafetyDistance, Terraria.WorldGen.ShroomPatch(), Terraria.ID.GenPassNameID.Silt, Terraria.WorldBuilding.GenVars.silver, System.Math.Sin(), Terraria.ID.GenPassNameID.Skyblock, Terraria.WorldGen.skyblockWorldGen, Terraria.WorldBuilding.GenVars.skyLake, Terraria.WorldBuilding.GenVars.skyLakes, Terraria.Tile.slope(), Terraria.WorldGen.SlopeTile(), Terraria.ID.GenPassNameID.SmallHoles, Terraria.WorldBuilding.GenVars.smallHolesBeachAvoidance, Terraria.Tile.SmoothSlope(), Terraria.ID.GenPassNameID.SmoothWorld, Terraria.WorldBuilding.GenVars.snowBottom, Terraria.WorldGen.SnowCloudIsland(), Terraria.WorldBuilding.GenVars.snowMaxX, Terraria.WorldBuilding.GenVars.snowMinX, Terraria.WorldBuilding.GenVars.snowOriginLeft, Terraria.WorldBuilding.GenVars.snowOriginRight, Terraria.WorldBuilding.GenVars.snowTop, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SonOfLakinater(), Terraria.WorldGen.SpreadGrass(), Terraria.ID.GenPassNameID.StoneToIceAndSiltPlusMudIntoSlush, Terraria.WorldBuilding.GenVars.structures, Terraria.ID.GenPassNameID.SurfaceCaves, Terraria.WorldBuilding.GenVars.surfaceCavesBeachAvoidance2, Terraria.WorldGen.SecretSeed.surfaceIsDesert, Terraria.WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes, Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.WorldGen.SecretSeed.surfaceIsMushrooms, Terraria.ID.GenPassNameID.SurfaceWaterInJungle, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.WorldGen.TileRunner(), Terraria.Main.tileSand, Terraria.Main.tileSolid, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.WorldGen.TuneOceanDepth(), Terraria.ID.GenPassNameID.Tunnels, Terraria.WorldBuilding.GenVars.tunnelX, Terraria.Tile.type, Terraria.WorldBuilding.GenVars.UndergroundDesertLocation, Terraria.ID.GenPassNameID.Underworld, Terraria.Main.UnderworldLayer, Terraria.Liquid.UpdateLiquid(), Terraria.Localization.LocalizedText.Value, Terraria.Tile.wall, Terraria.WorldGen.WaterCheck(), Terraria.ID.GenPassNameID.Waterfalls, Terraria.WorldGen.WavyCaverer(), Terraria.ID.GenPassNameID.WavyCaves, Terraria.ID.GenPassNameID.Webs, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Liquid.worldGenTilesIgnoreWater(), Terraria.WorldGen.SecretSeed.worldIsFrozen, Terraria.Main.worldSurface, Terraria.WorldBuilding.GenVars.worldSurface, Terraria.WorldBuilding.GenVars.worldSurfaceHigh, Terraria.WorldBuilding.GenVars.worldSurfaceLow, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.WorldGen.GenerateWorld().