Terraria Decompiled: Terraria.WorldGen.GrowCheckSeaweed
GrowCheckSeaweed()
static void Terraria.WorldGen.GrowCheckSeaweed (int x, int y) inline static
Definition at line 57635 of file WorldGen.cs.
        {
            int num = 1;
            if (Main.netMode != 1)
            {
                if ((Main.tile[x, y].type == 549 && Main.tile[x, y].liquid < 200) || Main.tile[x, y - 1].liquid < 200)
                {
                    if (Main.tile[x, y].active() && Main.tile[x, y].type == 549 && WorldGen.genRand.Next(2) == 0)
                    {
                        WorldGen.KillTile(x, y, false, false, false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
                else if (!Main.tile[x, y - 1].active() && !Main.tile[x, y - 2].active() && WorldGen.genRand.Next(num) == 0 && Main.tile[x, y - 2].liquid == 255 && Main.tile[x, y - 3].liquid == 255)
                {
                    int num2 = 17;
                    int num3 = 4;
                    int num4 = 30;
                    int num5 = 0;
                    for (int i = x - num3; i <= x + num3; i++)
                    {
                        for (int j = y; j <= y + num3 * 3; j++)
{
                            if (Main.tile[i, j].active() && Main.tile[i, j].type == 549)
{
                                num5++;
                                if (num5 > num4)
{
                                    return;
                                }
                            }
                        }
                    }
                    int num6 = y;
                    while (!WorldGen.SolidTile(x, num6, false) && num6 < Main.maxTilesY - 50)
                    {
                        num6++;
                    }
                    if (num6 - y >= num2 - WorldGen.genRand.Next(20))
                    {
                        return;
                    }
                    WorldGen.PlaceTile(x, y - 1, 549, true, false, -1, 0);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y - 1, TileChangeType.None);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.UpdateWorld_UndergroundTile().