Terraria Decompiled: Terraria.WorldGen.CanKillTile
CanKillTile() [3/3]
static bool Terraria.WorldGen.CanKillTile (int i, int j, WorldGen::SpecialKillTileContext context) inline static
Definition at line 61124 of file WorldGen.cs.
        {
            if (context == WorldGen.SpecialKillTileContext.MowingTheGrass)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    return false;
                }
                if (tile.type == 2 || tile.type == 109)
                {
                    return true;
                }
            }
            return WorldGen.CanKillTile(i, j);
        }
References Terraria.WorldGen.CanKillTile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.MinecartDiggerHelper.CanGetPastTile(), Terraria.WorldGen.CanKillTile(), Terraria.WorldGen.CanKillTile(), Terraria.WorldGen.CanPoundTile(), Terraria.Wiring.DeActive(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs_CanPlaceTile(), Terraria.Wiring.HitWireSingle(), Terraria.Player.ItemCheck_CheckCanUse_Inner(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.MowGrassTile(), Terraria.Player.PickTile_DetermineDamage(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.GameContent.SmartCursorHelper.Step_ForceCursorToAnyMinableThing(), and Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids().