Terraria Decompiled: Terraria.WorldGen.CheckChest
CheckChest()
static void Terraria.WorldGen.CheckChest (int i, int j, int type) inline static
Definition at line 56628 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k = 0;
            k += (int)(Main.tile[i, j].frameX / 18);
            int num = j + (int)(Main.tile[i, j].frameY / 18 * -1);
            while (k > 1)
            {
                k -= 2;
            }
            k *= -1;
            k += i;
            for (int l = k; l < k + 2; l++)
            {
                for (int m = num; m < num + 2; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    int n;
                    for (n = (int)(Main.tile[l, m].frameX / 18); n > 1; n -= 2)
                    {
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || n != l - k || (int)Main.tile[l, m].frameY != (m - num) * 18)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[l, num + 2] == null)
                {
                    Main.tile[l, num + 2] = new Tile();
                }
                if ((!Main.tile[l, num + 2].active() || !Main.tileSolid[(int)Main.tile[l, num + 2].type]) && Chest.CanDestroyChest(k, num))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                int itemDrop_Chests = WorldGen.GetItemDrop_Chests(i, j, type);
                WorldGen.destroyObject = true;
                for (int num2 = k; num2 < k + 2; num2++)
                {
                    for (int num3 = num; num3 < num + 3; num3++)
                    {
                        if ((int)Main.tile[num2, num3].type == type && Main.tile[num2, num3].active())
{
                            Chest.DestroyChest(num2, num3);
                            WorldGen.KillTile(num2, num3, false, false, false);
                        }
                    }
                }
                if (itemDrop_Chests > 0)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, itemDrop_Chests, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.Chest.CanDestroyChest(), Terraria.Chest.DestroyChest(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemDrop_Chests(), Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().