Terraria Decompiled: Terraria.WorldGen.KillWall_MakeWallDust
KillWall_MakeWallDust()
static void Terraria.WorldGen.KillWall_MakeWallDust (int i, int j, Tile tileCache) inline static private
Definition at line 60022 of file WorldGen.cs.
        {
            int num = 0;
            ushort wall = tileCache.wall;
            switch (wall)
            {
            case 3:
            case 246:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 14;
                    goto IL_07E6;
                }
                num = 1;
                goto IL_07E6;
            case 4:
            case 5:
            case 6:
            case 10:
            case 11:
            case 12:
            case 13:
            case 14:
            case 16:
            case 20:
            case 21:
            case 23:
            case 24:
            case 25:
            case 26:
            case 27:
            case 29:
            case 30:
            case 31:
            case 32:
            case 33:
            case 34:
            case 35:
            case 36:
            case 37:
            case 38:
            case 39:
            case 41:
            case 42:
            case 43:
            case 44:
            case 45:
            case 46:
            case 47:
            case 60:
            case 63:
            case 64:
            case 65:
            case 66:
            case 67:
            case 68:
            case 72:
            case 73:
            case 74:
            case 75:
            case 76:
            case 77:
            case 78:
            case 80:
            case 82:
            case 84:
            case 85:
            case 86:
            case 87:
            case 88:
            case 89:
            case 90:
            case 91:
            case 92:
            case 93:
            case 106:
            case 107:
            case 108:
            case 109:
            case 110:
            case 111:
            case 112:
            case 113:
            case 114:
            case 115:
            case 116:
            case 117:
            case 118:
            case 119:
            case 120:
            case 121:
            case 122:
            case 123:
            case 124:
            case 125:
            case 126:
            case 127:
            case 128:
            case 129:
            case 130:
            case 131:
            case 132:
            case 133:
            case 134:
            case 135:
            case 136:
            case 137:
            case 138:
            case 139:
            case 140:
            case 141:
            case 142:
            case 143:
            case 144:
            case 145:
            case 146:
            case 147:
            case 148:
            case 149:
            case 150:
            case 151:
            case 152:
            case 153:
            case 154:
            case 155:
            case 156:
            case 157:
            case 158:
            case 159:
            case 160:
            case 161:
            case 162:
            case 163:
            case 164:
            case 165:
            case 166:
            case 167:
            case 168:
            case 169:
            case 172:
            case 173:
            case 174:
            case 175:
            case 176:
            case 177:
            case 178:
            case 179:
            case 180:
            case 181:
            case 182:
            case 183:
            case 184:
            case 186:
            case 224:
            case 225:
            case 226:
            case 227:
            case 228:
            case 229:
            case 230:
            case 235:
            case 236:
            case 241:
            case 242:
            case 243:
            case 244:
            case 245:
            case 272:
            case 273:
                goto IL_07E6;
            case 7:
            case 17:
            case 94:
            case 95:
            case 100:
            case 101:
                break;
            case 8:
            case 18:
            case 98:
            case 99:
            case 104:
            case 105:
                goto IL_0646;
            case 9:
            case 19:
            case 96:
            case 97:
            case 102:
            case 103:
                goto IL_0651;
            case 15:
            case 247:
                num = 38;
                goto IL_07E6;
            case 22:
            case 28:
            case 248:
                num = 51;
                goto IL_07E6;
            case 40:
            case 249:
                num = 51;
                goto IL_07E6;
            case 48:
            case 49:
            case 50:
            case 51:
            case 52:
            case 53:
            case 54:
            case 55:
            case 56:
            case 57:
            case 58:
            case 185:
            case 250:
            case 251:
            case 252:
            case 253:
            case 254:
            case 255:
            case 256:
            case 257:
            case 258:
            case 259:
            case 260:
            case 274:
            case 314:
                num = 1;
                goto IL_07E6;
            case 59:
            case 61:
            case 261:
            case 262:
                num = 0;
                goto IL_07E6;
            case 62:
            case 263:
                num = 0;
                goto IL_07E6;
            case 69:
            case 264:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 14;
                    goto IL_07E6;
                }
                num = 17;
                goto IL_07E6;
            case 70:
            case 265:
                num = 47;
                goto IL_07E6;
            case 71:
            case 266:
                num = 80;
                goto IL_07E6;
            case 79:
            case 267:
                num = 37;
                goto IL_07E6;
            case 81:
            case 268:
                num = 123;
                goto IL_07E6;
            case 83:
            case 234:
            case 269:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 1;
                    goto IL_07E6;
                }
                num = 117;
                goto IL_07E6;
            case 170:
            case 171:
            case 270:
            case 271:
                num = 0;
                goto IL_07E6;
            case 187:
            case 275:
                num = 0;
                goto IL_07E6;
            case 188:
            case 189:
            case 190:
            case 191:
            case 276:
            case 277:
            case 278:
            case 279:
                num = 37;
                goto IL_07E6;
            case 192:
            case 193:
            case 194:
            case 195:
            case 280:
            case 281:
            case 282:
            case 283:
                num = 117;
                goto IL_07E6;
            case 196:
            case 197:
            case 198:
            case 199:
            case 284:
            case 285:
            case 286:
            case 287:
                num = 0;
                goto IL_07E6;
            case 200:
            case 202:
            case 288:
            case 290:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 69;
                    goto IL_07E6;
                }
                num = 70;
                goto IL_07E6;
            case 201:
            case 289:
                num = 17;
                goto IL_07E6;
            case 203:
            case 291:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 69;
                    goto IL_07E6;
                }
                num = 68;
                goto IL_07E6;
            case 204:
            case 205:
            case 207:
            case 292:
            case 293:
            case 295:
                num = 0;
                goto IL_07E6;
            case 206:
            case 294:
                num = 1;
                goto IL_07E6;
            case 208:
            case 209:
            case 210:
            case 211:
            case 296:
            case 297:
            case 298:
            case 299:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 155;
                    goto IL_07E6;
                }
                num = 125;
                goto IL_07E6;
            case 212:
            case 213:
            case 214:
            case 215:
            case 300:
            case 301:
            case 302:
            case 303:
                num = 1;
                goto IL_07E6;
            case 216:
            case 304:
                num = 0;
                goto IL_07E6;
            case 217:
            case 305:
                num = 37;
                goto IL_07E6;
            case 218:
            case 306:
                num = 155;
                goto IL_07E6;
            case 219:
            case 307:
                num = 17;
                goto IL_07E6;
            case 220:
            case 308:
                num = 37;
                goto IL_07E6;
            case 221:
            case 309:
                num = 155;
                goto IL_07E6;
            case 222:
            case 310:
                num = 37;
                goto IL_07E6;
            case 223:
            case 311:
                num = 0;
                goto IL_07E6;
            case 231:
                num = 8;
                goto IL_07E6;
            case 232:
                num = 82;
                goto IL_07E6;
            case 233:
                num = 18;
                goto IL_07E6;
            case 237:
                num = 6;
                goto IL_07E6;
            case 238:
                num = 61;
                goto IL_07E6;
            case 239:
                num = 242;
                goto IL_07E6;
            case 240:
                num = 135;
                goto IL_07E6;
            case 312:
            case 313:
            case 315:
                num = -1;
                goto IL_07E6;
            case 316:
            case 317:
                num = 36;
                goto IL_07E6;
            default:
                switch (wall)
                {
                case 331:
                    break;
                case 332:
                    goto IL_0646;
                case 333:
                    goto IL_0651;
                case 334:
                case 335:
                case 336:
                case 337:
                case 338:
                case 339:
                case 340:
                case 341:
                case 342:
                case 343:
                case 344:
                case 345:
                case 346:
                case 347:
                case 349:
                case 350:
                    goto IL_07E6;
                case 348:
                    num = 57;
                    goto IL_07E6;
                case 351:
                    num = 0;
                    goto IL_07E6;
                case 352:
                    num = 10;
                    goto IL_07E6;
                case 353:
                    num = 196;
                    goto IL_07E6;
                case 354:
                    num = 277;
                    goto IL_07E6;
                case 355:
                    num = 26;
                    goto IL_07E6;
                case 356:
                    num = 277;
                    goto IL_07E6;
                case 357:
                    num = 68;
                    goto IL_07E6;
                case 358:
                    num = 78;
                    goto IL_07E6;
                case 359:
                    num = 96;
                    goto IL_07E6;
                case 360:
                    num = 236;
                    goto IL_07E6;
                case 361:
                    num = 78;
                    goto IL_07E6;
                case 362:
                    num = 26;
                    goto IL_07E6;
                case 363:
                    num = 148;
                    goto IL_07E6;
                case 364:
                    num = 10;
                    goto IL_07E6;
                case 365:
                    num = 13;
                    goto IL_07E6;
                case 366:
                    num = 1;
                    goto IL_07E6;
                default:
                    goto IL_07E6;
                }
                break;
            }
            num = 275;
            goto IL_07E6;
            IL_0646:
            num = 276;
            goto IL_07E6;
            IL_0651:
            num = 277;
            IL_07E6:
            if (tileCache.wall == 148)
            {
                num = -1;
            }
            if (tileCache.wall == 1 || tileCache.wall == 5 || tileCache.wall == 6 || tileCache.wall == 107 || tileCache.wall == 349)
            {
                num = 1;
            }
            if (tileCache.wall == 35)
            {
                num = 37;
            }
            if (tileCache.wall == 4 || tileCache.wall == 106)
            {
                num = 7;
            }
            if (tileCache.wall == 12)
            {
                num = 9;
            }
            if (tileCache.wall == 336)
            {
                num = 9;
            }
            if (tileCache.wall == 10)
            {
                num = 10;
            }
            if (tileCache.wall == 334)
            {
                num = 10;
            }
            if (tileCache.wall == 11)
            {
                num = 11;
            }
            if (tileCache.wall == 335)
            {
                num = 11;
            }
            if (tileCache.wall == 21)
            {
                num = 13;
            }
            if (tileCache.wall == 34)
            {
                num = 32;
            }
            if (tileCache.wall == 225)
            {
                num = 1;
            }
            if (tileCache.wall == 145)
            {
                num = 8;
            }
            if (tileCache.wall == 23)
            {
                num = 38;
            }
            if (tileCache.wall == 24)
            {
                num = 36;
            }
            if (tileCache.wall == 25 || tileCache.wall == 339)
            {
                num = 48;
            }
            if (tileCache.wall == 179 || tileCache.wall == 178 || tileCache.wall == 183)
            {
                num = 236;
            }
            if (tileCache.wall == 181 || tileCache.wall == 180 || tileCache.wall == 184)
            {
                num = 240;
            }
            if (tileCache.wall == 113)
            {
                num = 189;
            }
            if (tileCache.wall == 114)
            {
                num = 190;
            }
            if (tileCache.wall == 115)
            {
                num = 191;
            }
            if (tileCache.wall == 177 || tileCache.wall == 13 || tileCache.wall == 338)
            {
                num = 25;
            }
            if (tileCache.wall == 186)
            {
                num = WorldGen.genRand.Next(68, 71);
            }
            if (tileCache.wall == 319)
            {
                num = 171;
            }
            if (tileCache.wall == 321)
            {
                num = 308;
            }
            if (tileCache.wall == 322)
            {
                num = 308;
            }
            if (tileCache.wall == 318)
            {
                num = 226;
            }
            if (tileCache.wall == 142)
            {
                num = 210;
            }
            if (tileCache.wall == 143)
            {
                num = 210;
            }
            if (tileCache.wall == 224)
            {
                num = 265;
            }
            if (tileCache.wall == 323)
            {
                num = 314;
            }
            if (tileCache.wall == 324)
            {
                num = 315;
            }
            if (tileCache.wall == 325)
            {
                num = 316;
            }
            if (tileCache.wall == 326)
            {
                num = 317;
            }
            if (tileCache.wall == 327)
            {
                num = 318;
            }
            if (tileCache.wall == 328)
            {
                num = 319;
            }
            if (tileCache.wall == 329)
            {
                num = 320;
            }
            if (tileCache.wall == 330)
            {
                num = 321;
            }
            if (tileCache.wall == 320)
            {
                num = 0;
            }
            if (tileCache.wall == 341)
            {
                num = 258;
            }
            if (tileCache.wall == 342)
            {
                num = 301;
            }
            if (tileCache.wall == 343)
            {
                num = 299;
            }
            if (tileCache.wall == 344)
            {
                num = 300;
            }
            if (tileCache.wall == 345)
            {
                num = 305;
            }
            if (tileCache.wall == 173)
            {
                num = 128;
            }
            if (tileCache.wall == 174)
            {
                num = 117;
            }
            if (tileCache.wall == 175)
            {
                num = 42;
            }
            if (tileCache.wall == 176)
            {
                num = 226;
            }
            if (tileCache.wall == 182)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 6;
                }
                else
                {
                    num = 23;
                }
            }
            if (tileCache.wall >= 153 && tileCache.wall <= 166)
            {
                switch (tileCache.wall)
                {
                case 153:
                case 157:
                    num = 138;
                    break;
                case 154:
                case 158:
                    num = 86;
                    break;
                case 155:
                case 159:
                    num = 91;
                    break;
                case 156:
                case 160:
                    num = 89;
                    break;
                case 161:
                case 164:
                    num = 90;
                    break;
                case 162:
                case 165:
                    num = 88;
                    break;
                case 163:
                case 166:
                    num = 87;
                    break;
                }
            }
            if (tileCache.wall == 26 || tileCache.wall == 30 || tileCache.wall == 340)
            {
                num = 49;
            }
            if (tileCache.wall == 29 || tileCache.wall == 32)
            {
                num = 50;
            }
            if (tileCache.wall == 31)
            {
                num = 51;
            }
            if (tileCache.wall == 14 || tileCache.wall == 20 || tileCache.wall == 337)
            {
                num = 109;
            }
            if (tileCache.wall == 241)
            {
                num = 286;
            }
            if (tileCache.wall >= 88 && tileCache.wall <= 93)
            {
                num = (int)(86 + tileCache.wall - 88);
                if (tileCache.wall == 93)
                {
                    num = WorldGen.genRand.Next(88, 94);
                }
            }
            if (tileCache.wall == 33)
            {
                num = 14;
            }
            if (tileCache.wall == 41)
            {
                num = 77;
            }
            if (tileCache.wall == 42)
            {
                num = 78;
            }
            if (tileCache.wall == 43)
            {
                num = 78;
            }
            if (tileCache.wall == 36)
            {
                num = 26;
            }
            if (tileCache.wall == 37)
            {
                num = 32;
            }
            if (tileCache.wall == 38)
            {
                num = 2;
            }
            if (tileCache.wall == 39)
            {
                num = 1;
            }
            if (tileCache.wall == 45)
            {
                num = 81;
            }
            if (tileCache.wall == 46)
            {
                num = 83;
            }
            if (tileCache.wall == 47)
            {
                num = 84;
            }
            if (tileCache.wall == 85)
            {
                num = 126;
            }
            if (tileCache.wall == 63)
            {
                num = 3;
            }
            if (tileCache.wall == 65)
            {
                num = 3;
            }
            if (tileCache.wall == 66)
            {
                num = 3;
            }
            if (tileCache.wall == 68)
            {
                num = 3;
            }
            if (tileCache.wall == 64)
            {
                num = 40;
            }
            if (tileCache.wall == 67)
            {
                num = 40;
            }
            if (tileCache.wall == 84)
            {
                num = 80;
            }
            if (tileCache.wall == 60)
            {
                num = 3;
            }
            if (tileCache.wall == 167)
            {
                num = 81;
            }
            if (tileCache.wall == 147)
            {
                num = 51;
            }
            if (tileCache.wall == 146)
            {
                num = 9;
            }
            if (tileCache.wall == 109)
            {
                num = 144;
            }
            if (tileCache.wall == 110)
            {
                num = 145;
            }
            if (tileCache.wall == 111)
            {
                num = 146;
            }
            if (tileCache.wall == 86 || tileCache.wall == 108)
            {
                num = 147;
            }
            if (tileCache.wall == 87)
            {
                num = 148;
            }
            if (tileCache.wall == 136)
            {
                num = 13;
            }
            if (tileCache.wall == 137)
            {
                num = 13;
            }
            if (tileCache.wall == 168)
            {
                num = 13;
            }
            if (tileCache.wall == 169)
            {
                num = 13;
            }
            if (tileCache.wall == 172)
            {
                num = 13;
            }
            if (tileCache.wall == 226)
            {
                num = 13;
            }
            if (tileCache.wall == 227)
            {
                num = 13;
            }
            if (tileCache.wall == 347)
            {
                num = 13;
            }
            if (tileCache.wall == 242)
            {
                num = 13;
            }
            if (tileCache.wall == 243)
            {
                num = 13;
            }
            if (tileCache.wall == 72)
            {
                num = 40;
            }
            if (tileCache.wall == 73)
            {
                num = 16;
            }
            if (tileCache.wall == 74 || tileCache.wall == 80)
            {
                num = 26;
            }
            if (tileCache.wall == 144)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 10;
                }
                else
                {
                    num = 118;
                }
            }
            if (tileCache.wall == 75)
            {
                num = 26;
            }
            if (tileCache.wall == 76)
            {
                num = 4;
            }
            if (tileCache.wall == 77 || tileCache.wall == 81)
            {
                num = 5;
            }
            if (tileCache.wall == 78 || tileCache.wall == 244)
            {
                num = 7;
            }
            if (tileCache.wall == 82)
            {
                num = 36;
            }
            if (tileCache.wall == 27)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 7;
                }
                else
                {
                    num = 1;
                }
            }
            if (tileCache.wall == 138)
            {
                num = 77;
            }
            if (tileCache.wall == 139)
            {
                num = 78;
            }
            if (tileCache.wall == 140)
            {
                num = 79;
            }
            if (tileCache.wall == 141)
            {
                num = 126;
            }
            if (tileCache.wall == 149 || tileCache.wall == 150)
            {
                num = 214;
            }
            if (tileCache.wall == 151 || tileCache.wall == 152)
            {
                num = 215;
            }
            if (tileCache.wall == 245)
            {
                num = 195;
            }
            if (tileCache.wall == 348)
            {
                Main.dust[Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, default(Color), 1f)].velocity *= 0.4f;
                return;
            }
            if (tileCache.wall == 44 || tileCache.wall == 346)
            {
                int num2 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 66, 0f, 0f, 100, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), 0.75f);
                Main.dust[num2].noGravity = true;
                return;
            }
            if ((tileCache.wall < 133 || tileCache.wall > 135) && (tileCache.wall < 116 || tileCache.wall > 125) && (tileCache.wall < 126 || tileCache.wall > 132))
            {
                if (tileCache.wall == 76)
                {
                    Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 75, new Color(0, 80, 255, 100), 0.75f);
                    return;
                }
                if (num >= 0)
                {
                    Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, default(Color), 1f);
                }
            }
        }
References Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.dust, Terraria.WorldGen.genRand, int, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.KillWall(), and Terraria.WorldGen.ReplaceWall().