Terraria Decompiled: Terraria.WorldGen.CheckSign
CheckSign()
static void Terraria.WorldGen.CheckSign (int x, int y, ushort type) inline static
Definition at line 41828 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int num = x - 2;
            int num2 = x + 3;
            int num3 = y - 2;
            int num4 = y + 3;
            if (num < 0)
            {
                return;
            }
            if (num2 > Main.maxTilesX)
            {
                return;
            }
            if (num3 < 0)
            {
                return;
            }
            if (num4 > Main.maxTilesY)
            {
                return;
            }
            bool flag = false;
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                }
            }
            int num5 = (int)(Main.tile[x, y].frameX / 18);
            int num6 = (int)(Main.tile[x, y].frameY / 18);
            num5 %= 2;
            num6 %= 2;
            int num7 = x - num5;
            int num8 = y - num6;
            int num9 = (int)(Main.tile[num7, num8].frameX / 18 / 2);
            int num10 = (int)(Main.tile[num7, num8].frameY / 18 / 2);
            int k = (int)(Main.tile[x, y].frameX / 18);
            int num11 = 0;
            while (k > 1)
            {
                k -= 2;
                num11++;
            }
            num = num7;
            num2 = num7 + 2;
            num3 = num8;
            num4 = num8 + 2;
            num5 = 0;
            for (int l = num; l < num2; l++)
            {
                num6 = 0;
                for (int m = num3; m < num4; m++)
                {
                    if (!Main.tile[l, m].active() || Main.tile[l, m].type != type)
                    {
                        flag = true;
                        break;
                    }
                    if ((int)(Main.tile[l, m].frameX / 18) != num5 + num9 * 2 || (int)(Main.tile[l, m].frameY / 18) != num6 + num10 * 2)
                    {
                        flag = true;
                        break;
                    }
                    num6++;
                }
                num5++;
            }
            if (!flag)
            {
                if (type == 85)
                {
                    if (WorldGen.SolidTileAllowBottomSlope(num7, num8 + 2) && WorldGen.SolidTileAllowBottomSlope(num7 + 1, num8 + 2))
                    {
                        num9 = num11;
                    }
                    else
                    {
                        flag = true;
                    }
                }
                else
                {
                    bool flag2;
                    switch (num11)
                    {
                    case 0:
                        flag2 = WorldGen.TopEdgeCanBeAttachedTo(num7, num8 + 2) && WorldGen.TopEdgeCanBeAttachedTo(num7 + 1, num8 + 2);
                        break;
                    case 1:
                        flag2 = WorldGen.BottomEdgeCanBeAttachedTo(num7, num8 - 1) && WorldGen.BottomEdgeCanBeAttachedTo(num7 + 1, num8 - 1);
                        break;
                    case 2:
                        flag2 = WorldGen.RightEdgeCanBeAttachedTo(num7 - 1, num8) && WorldGen.RightEdgeCanBeAttachedTo(num7 - 1, num8 + 1);
                        break;
                    case 3:
                        flag2 = WorldGen.LeftEdgeCanBeAttachedTo(num7 + 2, num8) && WorldGen.LeftEdgeCanBeAttachedTo(num7 + 2, num8 + 1);
                        break;
                    case 4:
                        flag2 = Main.tile[num7, num8].wall > 0 && Main.tile[num7 + 1, num8].wall > 0 && Main.tile[num7, num8 + 1].wall > 0 && Main.tile[num7 + 1, num8 + 1].wall > 0;
                        break;
                    default:
                        flag2 = false;
                        break;
                    }
                    if (!flag2)
                    {
                        if (WorldGen.TopEdgeCanBeAttachedTo(num7, num8 + 2) && WorldGen.TopEdgeCanBeAttachedTo(num7 + 1, num8 + 2))
{
                            num9 = 0;
                        }
                        else if (WorldGen.BottomEdgeCanBeAttachedTo(num7, num8 - 1) && WorldGen.BottomEdgeCanBeAttachedTo(num7 + 1, num8 - 1))
{
                            num9 = 1;
                        }
                        else if (WorldGen.RightEdgeCanBeAttachedTo(num7 - 1, num8) && WorldGen.RightEdgeCanBeAttachedTo(num7 - 1, num8 + 1))
{
                            num9 = 2;
                        }
                        else if (WorldGen.LeftEdgeCanBeAttachedTo(num7 + 2, num8) && WorldGen.LeftEdgeCanBeAttachedTo(num7 + 2, num8 + 1))
{
                            num9 = 3;
                        }
                        else if (Main.tile[num7, num8].wall > 0 && Main.tile[num7 + 1, num8].wall > 0 && Main.tile[num7, num8 + 1].wall > 0 && Main.tile[num7 + 1, num8 + 1].wall > 0)
{
                            num9 = 4;
                        }
                        else
{
                            flag = true;
                        }
                    }
                }
            }
            if (flag)
            {
                TEItemFrame teitemFrame;
                if (type == 395 && TileEntity.TryGetAt<TEItemFrame>(num7, num8, out teitemFrame) && teitemFrame.item.stack > 0)
                {
                    teitemFrame.DropItem();
                    if (Main.netMode != 2)
                    {
                        Main.LocalPlayer.InterruptItemUsageIfOverTile(395);
                    }
                }
                WorldGen.destroyObject = true;
                for (int n = num; n < num2; n++)
                {
                    for (int num12 = num3; num12 < num4; num12++)
                    {
                        if (Main.tile[n, num12].type == type)
{
                            WorldGen.KillTile(n, num12, false, false, false);
                        }
                    }
                }
                if (type != 395)
                {
                    Sign.KillSign(num7, num8);
                }
                if (type == 85)
                {
                    int num13 = 321;
                    if (num11 >= 6 && num11 <= 10)
                    {
                        num13 = 3229 + num11 - 6;
                    }
                    else if (num11 >= 1 && num11 <= 5)
                    {
                        num13 = 1173 + num11 - 1;
                    }
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, num13, 1, false, 0, false);
                    if (Main.netMode != 1)
                    {
                        int num14 = 8;
                        if (Main.Difficulty >= GameDifficultyLevel.Master)
{
                            num14 = 2;
                        }
                        else if (Main.Difficulty >= GameDifficultyLevel.Expert)
{
                            num14 = 4;
                        }
                        if (WorldGen.genRand.Next(num14) == 0 && NPC.CountNPCS(316) < 2)
{
                            int num15 = (int)Player.FindClosest(new Vector2((float)(x * 16), (float)(y * 16)), 16, 16);
                            if (Main.player[num15].ZoneGraveyard || !Main.dayTime || (double)y > Main.worldSurface)
{
                                NPC.SpawnOnPlayer(num15, 316, 0f, 0f, 0f, 1f);
                            }
                        }
                    }
                }
                else if (type == 395)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 3270, 1, false, 0, false);
                    TileEntityType<TEItemFrame>.Kill(num7, num8);
                }
                else if (type == 425)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 3617, 1, false, 0, false);
                }
                else if (type == 573)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 4710, 1, false, 0, false);
                }
                else if (type == 511)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 4320, 1, false, 0, false);
                }
                else if (type == 510)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num7, num8), num7 * 16, num8 * 16, 32, 32, 4319, 1, false, 0, false);
                }
                else
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 171, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                return;
            }
            int num16 = 36 * num9;
            for (int num17 = 0; num17 < 2; num17++)
            {
                for (int num18 = 0; num18 < 2; num18++)
                {
                    Main.tile[num7 + num17, num8 + num18].active(true);
                    Main.tile[num7 + num17, num8 + num18].type = type;
                    Main.tile[num7 + num17, num8 + num18].frameX = (short)(num16 + 18 * num17);
                    Main.tile[num7 + num17, num8 + num18].frameY = (short)(18 * num18 + num10 * 36);
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.BottomEdgeCanBeAttachedTo(), Terraria.NPC.CountNPCS(), Terraria.Main.dayTime, Terraria.WorldGen.destroyObject, Terraria.Main.Difficulty, Terraria.GameContent.Tile_Entities.TEItemFrame.DropItem(), Terraria.DataStructures.GameDifficultyLevel.Expert, Terraria.Player.FindClosest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.Player.InterruptItemUsageIfOverTile(), Terraria.DataStructures.TileEntityType< T >.Kill(), Terraria.Sign.KillSign(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.Main.LocalPlayer, Terraria.DataStructures.GameDifficultyLevel.Master, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.WorldGen.RightEdgeCanBeAttachedTo(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.NPC.SpawnOnPlayer(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, and Terraria.Player.ZoneGraveyard.
Referenced by Terraria.WorldGen.TileFrameImportant().