Terraria Decompiled: Terraria.WorldGen.worldGenCallback
worldGenCallback()
static void Terraria.WorldGen.worldGenCallback (GenerationProgress customProgressObject, WorldGenerator::Controller customGenController, WorldGen::WorldGenerationFinishCallback afterGeneration) inline static
Definition at line 2388 of file WorldGen.cs.
        {
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            bool flag = WorldGen.GenerateWorld(customProgressObject, customGenController);
            if (flag)
            {
                WorldFile.SaveNewWorld();
            }
            if (Main.menuMode == 10 || Main.menuMode == 888)
            {
                Main.menuMode = 6;
            }
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            if (afterGeneration != null)
            {
                afterGeneration(flag);
            }
        }
References Terraria.WorldGen.GenerateWorld(), Terraria.Main.menuMode, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.IO.WorldFile.SaveNewWorld().
Referenced by Terraria.WorldGen.CreateNewWorld().