Terraria Decompiled: Terraria.WorldGen.CheckTallGate
CheckTallGate()
static void Terraria.WorldGen.CheckTallGate (int x, int y, int type) inline static
Definition at line 50166 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            Tile tile = Framing.GetTileSafely(x, y);
            Point point = new Point((int)(tile.frameX / 18), 0);
            TileObjectData tileData = TileObjectData.GetTileData(type, point.X, 0);
            point.Y = (int)tile.frameY / tileData.CoordinateFullHeight;
            int width = tileData.Width;
            int height = tileData.Height;
            int num = 0;
            int num2 = (int)tile.frameY % tileData.CoordinateFullHeight;
            while (num < height && num2 - tileData.CoordinateHeights[num] >= 0)
            {
                num2 -= tileData.CoordinateHeights[num];
                num++;
            }
            int coordinateFullHeight = tileData.CoordinateFullHeight;
            y -= num;
            int num3 = point.Y * tileData.CoordinateFullHeight;
            for (int i = 0; i < height; i++)
            {
                tile = Framing.GetTileSafely(x, y + i);
                if ((int)tile.frameX != point.X * tileData.CoordinateFullWidth || (int)tile.frameY != num3)
                {
                    flag = true;
                    break;
                }
                num3 += tileData.CoordinateHeights[i] + tileData.CoordinatePadding;
            }
            if (!flag && WorldGen.CheckTileAnchors(x, y, width, height, 2, AnchorType.SolidTile))
            {
                return;
            }
            WorldGen.destroyObject = true;
            for (int j = x; j < x + width; j++)
            {
                for (int k = y; k < y + height; k++)
                {
                    Tile tile2 = Main.tile[j, k];
                    if (tile2 != null && tile2.active() && (int)tile2.type == type)
                    {
                        WorldGen.KillTile(j, k, false, false, false);
                    }
                }
            }
            int num4 = 3240;
            if (point.Y == 0)
            {
                num4 = 3240;
            }
            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, width * 16, height * 16, num4, 1, false, 0, false);
            WorldGen.destroyObject = false;
            for (int l = x - 1; l < x + width + 1; l++)
            {
                for (int m = y - 1; m < y + height + 1; m++)
                {
                    WorldGen.TileFrame(l, m, false, false);
                }
            }
            WorldGen.CheckExploitDestroyQueue();
        }
References Terraria.Tile.active(), Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.CheckTileAnchors(), Terraria.ObjectData.TileObjectData.CoordinateFullHeight, Terraria.ObjectData.TileObjectData.CoordinateFullWidth, Terraria.ObjectData.TileObjectData.CoordinateHeights, Terraria.ObjectData.TileObjectData.CoordinatePadding, Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Terraria.ObjectData.TileObjectData.Height, int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, Terraria.ObjectData.TileObjectData.Width, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.TileFrameImportant().