Terraria Decompiled: Terraria.WorldGen.SpawnStormLightningNearPlayer
SpawnStormLightningNearPlayer()
static void Terraria.WorldGen.SpawnStormLightningNearPlayer (List< Rectangle > safespots, Player player) inline static private
Definition at line 72304 of file WorldGen.cs.
        {
            Rectangle rectangle = Utils.CenteredRectangle(player.Center.ToTileCoordinates(), Point.Zero);
            rectangle.Inflate(Main.MaxWorldViewSize.X / 32, Main.MaxWorldViewSize.Y / 32);
            rectangle = WorldUtils.ClampToWorld(rectangle, 10);
            if (rectangle.Width == 0 || rectangle.Height == 0)
            {
                return;
            }
            int i = 0;
            while (i < 400)
            {
                int num = Main.rand.Next(rectangle.Left, rectangle.Right + 1);
                int num2 = Main.rand.Next(rectangle.Top, rectangle.Bottom + 1);
                Tile tile = Main.tile[num, num2];
                while (num2 > 0 && WorldGen.IsLightningAttractor(Main.tile[num, num2 - 1]))
                {
                    tile = Main.tile[num, --num2];
                }
                if (i < 350)
                {
                    if (WorldGen.IsLightningAttractor(tile))
                    {
                        goto IL_00EE;
                    }
                }
                else if (tile.liquid != 0 || WorldGen.SolidTile(tile))
                {
                    goto IL_00EE;
                }
                IL_013F:
                i++;
                continue;
                IL_00EE:
                if (num2 > 0 && Main.tile[num, num2 - 1].liquid != 0)
                {
                    goto IL_013F;
                }
                bool flag = false;
                if (WorldGen.TrySpawnLightningBolt(safespots, num, num2, ref flag))
                {
                    WorldGen.DebugLogLightning((i < 350) ? "attracted" : "spawned");
                    return;
                }
                if (flag)
                {
                    WorldGen.DebugLogLightning("too close to existing strike");
                    return;
                }
                goto IL_013F;
            }
            WorldGen.DebugLogLightning("no target");
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Terraria.WorldGen.DebugLogLightning(), Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.WorldGen.IsLightningAttractor(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Tile.liquid, Terraria.Main.MaxWorldViewSize, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rand, Microsoft.Xna.Framework.Rectangle.Right, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Terraria.WorldGen.TrySpawnLightningBolt(), Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.WorldGen.SpawnStormLightning().