Terraria Decompiled: Terraria.WorldGen.CheckTileFrames
CheckTileFrames()
static bool Terraria.WorldGen.CheckTileFrames (int type, int sx, int sy, int w, int h, int styleX, int frameXinc, int styleY, int frameYinc) inline static
Definition at line 50307 of file WorldGen.cs.
        {
            for (int i = 0; i < w; i++)
            {
                for (int j = 0; j < h; j++)
                {
                    Tile tileSafely = Framing.GetTileSafely(sx + i, sy + j);
                    if (!tileSafely.active() || (int)tileSafely.type != type || (int)tileSafely.frameX != styleX * w * frameXinc + i * frameXinc || (int)tileSafely.frameY != styleY * h * frameYinc + j * frameYinc)
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CheckTrapDoor().