Terraria Decompiled: Terraria.WorldGen.KillTile_GetTreeDrops
KillTile_GetTreeDrops()
static void Terraria.WorldGen.KillTile_GetTreeDrops (int i, int j, Tile tileCache, ref bool dropIsWood, ref bool bonusWood, ref int dropItem, ref int secondaryItem) inline static private
Definition at line 65596 of file WorldGen.cs.
        {
            if (tileCache.frameX >= 22 && tileCache.frameY >= 198)
            {
                if (Main.netMode != 1)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        if (WorldGen.TreeTypeDropsAcorns(WorldGen.GetTreeType(i, j)))
{
                            dropItem = 9;
                            secondaryItem = 27;
                        }
                        else
{
                            dropItem = 9;
                        }
                    }
                    else
                    {
                        dropItem = 9;
                    }
                }
            }
            else
            {
                dropItem = 9;
            }
            if (dropItem == 9)
            {
                dropIsWood = true;
                int num;
                int num2;
                switch (WorldGen.GetTreeTypeAndTreeBottom(i, j, out num, out num2))
                {
                case TreeTypes.Corrupt:
                    dropItem = 619;
                    break;
                case TreeTypes.Mushroom:
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        dropItem = 183;
                    }
                    else
                    {
                        dropItem = 0;
                    }
                    break;
                case TreeTypes.Crimson:
                    dropItem = 911;
                    break;
                case TreeTypes.Jungle:
                    dropItem = 620;
                    break;
                case TreeTypes.Snow:
                    dropItem = 2503;
                    break;
                case TreeTypes.Hallowed:
                    dropItem = 621;
                    break;
                case TreeTypes.Ash:
                    dropItem = 5215;
                    break;
                }
                int num3 = (int)Player.FindClosest(new Vector2((float)(num * 16), (float)(num2 * 16)), 16, 16);
                int axe = Main.player[num3].inventory[Main.player[num3].selectedItem].axe;
                if (WorldGen.genRand.Next(35) <= axe || Main.rand.Next(3) == 0)
                {
                    bonusWood = true;
                }
            }
        }
References Terraria.Item.axe, Terraria.Player.FindClosest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.GetTreeType(), Terraria.WorldGen.GetTreeTypeAndTreeBottom(), int, Terraria.Player.inventory, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.player, Terraria.Main.rand, Terraria.Player.selectedItem, and Terraria.WorldGen.TreeTypeDropsAcorns().
Referenced by Terraria.WorldGen.KillTile_GetItemDrops().