Terraria Decompiled: Terraria.WorldGen.SpawnTravelNPC
SpawnTravelNPC()
static void Terraria.WorldGen.SpawnTravelNPC () inline static
Definition at line 929 of file WorldGen.cs.
        {
            if (Main.eclipse || !Main.dayTime)
            {
                return;
            }
            if (Main.invasionType > 0 && Main.invasionDelay == 0 && Main.invasionSize > 0)
            {
                return;
            }
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == 368)
                {
                    return;
                }
            }
            Chest.SetupTravelShop();
            NetMessage.SendTravelShop(-1);
            Point zero = Point.Zero;
            int[] array = new int[Main.maxNPCs];
            Point[] array2 = new Point[Main.maxNPCs];
            int num = 0;
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.active && npc.townNPC && npc.type != 37 && !npc.homeless)
                {
                    array[num] = j;
                    array2[num] = new Point(npc.homeTileX, npc.homeTileY);
                    num++;
                }
            }
            if (num == 0)
            {
                for (int k = 0; k < Main.maxNPCs; k++)
                {
                    NPC npc2 = Main.npc[k];
                    if (npc2.active && npc2.townNPC && npc2.type != 37 && npc2.homeless)
                    {
                        Point zero2 = Point.Zero;
                        if (WorldGen.TownManager.HasRoom(npc2.type, out zero2))
{
                            array[num] = k;
                            array2[num] = zero2;
                            num++;
                        }
                    }
                }
            }
            if (num == 0)
            {
                return;
            }
            int num2 = Main.rand.Next(num);
            int num3 = array[num2];
            Point point = array2[num2];
            WorldGen.bestX = point.X;
            WorldGen.bestY = point.Y;
            int num4 = WorldGen.bestX;
            int num5 = WorldGen.bestX;
            int num6 = WorldGen.bestY;
            int num7 = WorldGen.bestX;
            while (num7 > WorldGen.bestX - 10 && (WorldGen.SolidTile(num7, num6, false) || Main.tileSolidTop[(int)Main.tile[num7, num6].type]) && (!Main.tile[num7, num6 - 1].active() || !Main.tileSolid[(int)Main.tile[num7, num6 - 1].type] || Main.tileSolidTop[(int)Main.tile[num7, num6 - 1].type]) && (!Main.tile[num7, num6 - 2].active() || !Main.tileSolid[(int)Main.tile[num7, num6 - 2].type] || Main.tileSolidTop[(int)Main.tile[num7, num6 - 2].type]) && (!Main.tile[num7, num6 - 3].active() || !Main.tileSolid[(int)Main.tile[num7, num6 - 3].type] || Main.tileSolidTop[(int)Main.tile[num7, num6 - 3].type]))
            {
                num4 = num7;
                num7--;
            }
            int num8 = WorldGen.bestX;
            while (num8 < WorldGen.bestX + 10 && (WorldGen.SolidTile(num8, num6, false) || Main.tileSolidTop[(int)Main.tile[num8, num6].type]) && (!Main.tile[num8, num6 - 1].active() || !Main.tileSolid[(int)Main.tile[num8, num6 - 1].type] || Main.tileSolidTop[(int)Main.tile[num8, num6 - 1].type]) && (!Main.tile[num8, num6 - 2].active() || !Main.tileSolid[(int)Main.tile[num8, num6 - 2].type] || Main.tileSolidTop[(int)Main.tile[num8, num6 - 2].type]) && (!Main.tile[num8, num6 - 3].active() || !Main.tileSolid[(int)Main.tile[num8, num6 - 3].type] || Main.tileSolidTop[(int)Main.tile[num8, num6 - 3].type]))
            {
                num5 = num8;
                num8++;
            }
            for (int l = 0; l < 30; l++)
            {
                int num9 = Main.rand.Next(num4, num5 + 1);
                if (l < 20)
                {
                    if (num9 < WorldGen.bestX - 1 || num9 > WorldGen.bestX + 1)
                    {
                        WorldGen.bestX = num9;
                        break;
                    }
                }
                else if (num9 != WorldGen.bestX)
                {
                    WorldGen.bestX = num9;
                    break;
                }
            }
            int num10 = WorldGen.bestX;
            int num11 = WorldGen.bestY;
            bool flag = false;
            if (!flag && (double)num11 <= Main.worldSurface)
            {
                for (int m = 20; m < 500; m++)
                {
                    for (int n = 0; n < 2; n++)
                    {
                        if (n == 0)
{
                            num10 = WorldGen.bestX + m * 2;
                        }
                        else
{
                            num10 = WorldGen.bestX - m * 2;
                        }
                        if (num10 > 10 && num10 < Main.maxTilesX - 10)
{
                            int num12 = WorldGen.bestY - m;
                            double num13 = (double)(WorldGen.bestY + m);
                            if (num12 < 10)
{
                                num12 = 10;
                            }
                            if (num13 > Main.worldSurface)
{
                                num13 = Main.worldSurface;
                            }
                            int num14 = num12;
                            while ((double)num14 < num13)
{
                                num11 = num14;
                                if (Main.tile[num10, num11].nactive() && Main.tileSolid[(int)Main.tile[num10, num11].type])
{
                                    if (Main.tile[num10, num11 - 3].liquid == 0 && Main.tile[num10, num11 - 2].liquid == 0 && Main.tile[num10, num11 - 1].liquid == 0 && !Collision.SolidTiles(num10 - 1, num10 + 1, num11 - 3, num11 - 1))
{
                                        flag = true;
                                        Rectangle rectangle = new Rectangle(num10 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num11 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                                        for (int num15 = 0; num15 < 255; num15++)
{
                                            if (Main.player[num15].active)
{
                                                Rectangle rectangle2 = new Rectangle((int)Main.player[num15].position.X, (int)Main.player[num15].position.Y, Main.player[num15].width, Main.player[num15].height);
                                                if (rectangle2.Intersects(rectangle))
{
                                                    flag = false;
                                                    break;
                                                }
                                            }
                                        }
                                        break;
                                    }
                                    break;
                                }
                                else
{
                                    num14++;
                                }
                            }
                        }
                        if (flag)
{
                            break;
                        }
                    }
                    if (flag)
                    {
                        break;
                    }
                }
            }
            int num16 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), num10 * 16, num11 * 16, 368, 1, 0f, 0f, 0f, 0f, 255);
            Main.npc[num16].homeTileX = WorldGen.bestX;
            Main.npc[num16].homeTileY = WorldGen.bestY;
            Main.npc[num16].homeless = true;
            if (num10 < WorldGen.bestX)
            {
                Main.npc[num16].direction = 1;
            }
            else if (num10 > WorldGen.bestX)
            {
                Main.npc[num16].direction = -1;
            }
            Main.npc[num16].netUpdate = true;
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey("Announcement.HasArrived", new object[] { Main.npc[num16].GetFullNetName() }), ChatColors.NPCTravel, -1);
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Tile.active(), System.array, Terraria.WorldGen.bestX, Terraria.WorldGen.bestY, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Main.dayTime, Terraria.Entity.direction, Terraria.Main.eclipse, Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.GetSpawnSourceForTownSpawn(), Terraria.GameContent.TownRoomManager.HasRoom(), Terraria.Entity.height, Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.invasionDelay, Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.Tile.liquid, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Tile.nactive(), Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Chat.ChatColors.NPCTravel, Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.NetMessage.SendTravelShop(), Terraria.Chest.SetupTravelShop(), Terraria.NPC.sHeight, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), Terraria.NPC.sWidth, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.WorldGen.TownManager, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Tile.type, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.Main.UpdateTime().