Terraria Decompiled: Terraria.WorldGen.KillTile_GetTileDustAmount
KillTile_GetTileDustAmount()
static int Terraria.WorldGen.KillTile_GetTileDustAmount (bool fail, Tile tileCache) inline static
Definition at line 65996 of file WorldGen.cs.
        {
            ushort type = tileCache.type;
            if (type <= 499)
            {
                if (type <= 287)
                {
                    if (type <= 172)
                    {
                        if (type == 125 || type == 138 || type == 172)
{
                            return 0;
                        }
                    }
                    else if (type != 184)
                    {
                        if (type != 231)
{
                            if (type == 287)
{
                                return 0;
                            }
                        }
                        else
{
                            if (!fail)
{
                                return 6;
                            }
                            return 3;
                        }
                    }
                    else
                    {
                        if (tileCache.frameX / 22 >= 5)
{
                            return 5;
                        }
                        if (!fail)
{
                            return 10;
                        }
                        return 3;
                    }
                }
                else if (type <= 376)
                {
                    if (type - 300 <= 8 || type - 354 <= 1 || type - 373 <= 3)
                    {
                        return 0;
                    }
                }
                else if (type <= 483)
                {
                    if (type == 461)
                    {
                        return 0;
                    }
                    if (type - 481 <= 2)
                    {
                        return 3;
                    }
                }
                else if (type == 484 || type == 499)
                {
                    return 0;
                }
            }
            else
            {
                if (type <= 594)
                {
                    if (type <= 539)
                    {
                        if (type != 534 && type != 536 && type != 539)
{
                            goto IL_01C4;
                        }
                    }
                    else if (type <= 549)
                    {
                        if (type == 541)
{
                            return 1;
                        }
                        if (type != 549)
{
                            goto IL_01C4;
                        }
                        return 2;
                    }
                    else
                    {
                        if (type - 564 > 1 && type - 593 > 1)
{
                            goto IL_01C4;
                        }
                        return 0;
                    }
                }
                else if (type <= 654)
                {
                    if (type == 617)
                    {
                        return 0;
                    }
                    switch (type)
                    {
                    case 625:
                    case 627:
                        break;
                    case 626:
                    case 628:
                    case 629:
                        goto IL_01C4;
                    case 630:
                    case 631:
                        return 0;
                    default:
                        if (type != 654)
{
                            goto IL_01C4;
                        }
                        return 0;
                    }
                }
                else if (type <= 699)
                {
                    if (type - 664 > 1 && type != 699)
                    {
                        goto IL_01C4;
                    }
                    return 0;
                }
                else
                {
                    if (type != 709 && type - 711 > 5)
                    {
                        goto IL_01C4;
                    }
                    return 0;
                }
                if (!fail)
                {
                    return 5;
                }
                return 3;
            }
            IL_01C4:
            if (!fail)
            {
                return 10;
            }
            return 3;
        }
References Terraria.Tile.frameX, and Terraria.Tile.type.
Referenced by Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.Mount.EmitGolfCartWheelDust(), Terraria.WorldGen.KillTile(), Terraria.Player.MowGrassTile(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.WorldGen.ReplaceTile(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning().