Terraria Decompiled: Terraria.WorldGen.templePart2
templePart2()
static void Terraria.WorldGen.templePart2 () inline static
Definition at line 31783 of file WorldGen.cs.
        {
            int tLeft = GenVars.tLeft;
            int tRight = GenVars.tRight;
            int tTop = GenVars.tTop;
            int tBottom = GenVars.tBottom;
            int tRooms = GenVars.tRooms;
            double num = (double)tRooms * 1.9;
            num *= 1.0 + (double)WorldGen.genRand.Next(-15, 16) * 0.01;
            int num2 = 0;
            while (num > 0.0)
            {
                int num3 = WorldGen.genRand.Next(tLeft, tRight);
                int num4 = WorldGen.genRand.Next(tTop, tBottom);
                if (Main.tile[num3, num4].wall == 87 && !Main.tile[num3, num4].active())
                {
                    if (WorldGen.mayanTrap(num3, num4))
                    {
                        num -= 1.0;
                        num2 = 0;
                    }
                    else
                    {
                        num2++;
                    }
                }
                else
                {
                    num2++;
                }
                if (num2 > 100)
                {
                    num2 = 0;
                    num -= 1.0;
                }
            }
            Main.tileSolid[232] = false;
            double num5 = (double)tRooms * 0.35;
            num5 *= 1.0 + (double)WorldGen.genRand.Next(-15, 16) * 0.01;
            short num6 = 1293;
            num2 = 0;
            while (num5 > 0.0)
            {
                int num7 = WorldGen.genRand.Next(tLeft, tRight);
                int num8 = WorldGen.genRand.Next(tTop, tBottom);
                if (Main.tile[num7, num8].wall == 87 && !Main.tile[num7, num8].active() && WorldGen.AddBuriedChest(num7, num8, (int)num6, true, 16, false, 0))
                {
                    num5 -= 1.0;
                    num2 = 0;
                }
                num2++;
                if (num2 > 10000)
                {
                    break;
                }
            }
            double num9 = (double)tRooms * 1.25;
            num9 *= 1.0 + (double)WorldGen.genRand.Next(-25, 36) * 0.01;
            num2 = 0;
            while (num9 > 0.0)
            {
                num2++;
                int num10 = WorldGen.genRand.Next(tLeft, tRight);
                int num11 = WorldGen.genRand.Next(tTop, tBottom);
                if (Main.tile[num10, num11].wall == 87 && !Main.tile[num10, num11].active())
                {
                    int num12 = num10;
                    int num13 = num11;
                    while (!Main.tile[num12, num13].active())
                    {
                        num13++;
                        if (num13 > tBottom)
{
                            break;
                        }
                    }
                    num13--;
                    if (num13 <= tBottom)
                    {
                        WorldGen.PlaceTile(num12, num13, 105, true, false, -1, WorldGen.genRand.Next(43, 46));
                        if (Main.tile[num12, num13].type == 105)
{
                            num9 -= 1.0;
                        }
                    }
                }
                if (num2 > 10000)
                {
                    break;
                }
            }
            double num14 = (double)tRooms * 1.35;
            num14 *= 1.0 + (double)WorldGen.genRand.Next(-15, 26) * 0.01;
            num2 = 0;
            while (num14 > 0.0)
            {
                num2++;
                int num15 = WorldGen.genRand.Next(tLeft, tRight);
                int num16 = WorldGen.genRand.Next(tTop, tBottom);
                if (Main.tile[num15, num16].wall == 87 && !Main.tile[num15, num16].active())
                {
                    int num17 = num15;
                    int num18 = num16;
                    while (!Main.tile[num17, num18].active())
                    {
                        num18++;
                        if (num18 > tBottom)
{
                            break;
                        }
                    }
                    num18--;
                    if (num18 <= tBottom)
                    {
                        int num19 = WorldGen.genRand.Next(3);
                        if (num19 == 0)
{
                            WorldGen.PlaceTile(num17, num18, 18, true, false, -1, 10);
                            if (Main.tile[num17, num18].type == 18)
{
                                num14 -= 1.0;
                            }
                        }
                        else if (num19 == 1)
{
                            WorldGen.PlaceTile(num17, num18, 14, true, false, -1, 9);
                            if (Main.tile[num17, num18].type == 14)
{
                                num14 -= 1.0;
                            }
                        }
                        else if (num19 == 2)
{
                            WorldGen.PlaceTile(num17, num18, 15, true, false, -1, 12);
                            if (Main.tile[num17, num18].type == 15)
{
                                num14 -= 1.0;
                            }
                        }
                    }
                }
                if (num2 > 10000)
                {
                    break;
                }
            }
            int i = 1;
            if (Main.maxTilesX > 4200)
            {
                i++;
            }
            if (Main.maxTilesX > 6400)
            {
                i += WorldGen.genRand.Next(2);
            }
            num2 = 0;
            while (i > 0)
            {
                num2++;
                int num20 = WorldGen.genRand.Next(tLeft, tRight);
                int num21 = WorldGen.genRand.Next(tTop, tBottom);
                if (Main.tile[num20, num21].wall == 87 && !Main.tile[num20, num21].active())
                {
                    bool flag = false;
                    for (int j = -70; j <= 70; j++)
                    {
                        for (int k = -70; k <= 70; k++)
{
                            int num22 = j + num20;
                            int num23 = k + num21;
                            if (WorldGen.InWorld(num22, num23, 5))
{
                                Tile tile = Main.tile[num22, num23];
                                if (tile.active())
{
                                    if (tile.type == 240)
{
                                        flag = true;
                                        break;
                                    }
                                    if (j >= -4 && j <= 4 && k >= -4 && k <= 4 && tile.type == 226)
{
                                        flag = true;
                                        break;
                                    }
                                }
                            }
                        }
                        if (flag)
{
                            break;
                        }
                    }
                    if (flag)
                    {
                        continue;
                    }
                    if (WorldGen.PlaceTile(num20, num21, 240, true, false, -1, 88))
                    {
                        i--;
                    }
                }
                if (num2 > 10000)
                {
                    break;
                }
            }
            Main.tileSolid[232] = true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.Main.maxTilesX, Terraria.WorldGen.mayanTrap(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldBuilding.GenVars.tBottom, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.WorldBuilding.GenVars.tLeft, Terraria.WorldBuilding.GenVars.tRight, Terraria.WorldBuilding.GenVars.tRooms, Terraria.WorldBuilding.GenVars.tTop, Terraria.Tile.type, and Terraria.Tile.wall.