Terraria Decompiled: Terraria.WorldGen.GrowPalmTree
GrowPalmTree()
static bool Terraria.WorldGen.GrowPalmTree (int i, int y, int treeHeightAddon = 0, bool ignoreWalls = false) inline static
Definition at line 24216 of file WorldGen.cs.
        {
            int num = y;
            if (!WorldGen.InWorld(i, y, 0))
            {
                return false;
            }
            while (Main.tile[i, num].active() && Main.tile[i, num].type == 20)
            {
                num++;
                if (Main.tile[i, num] == null)
                {
                    return false;
                }
            }
            Tile tile = Main.tile[i, num];
            Tile tile2 = Main.tile[i, num - 1];
            TileColorCache tileColorCache = Main.tile[i, num].BlockColorAndCoating();
            if (Main.tenthAnniversaryWorld && !WorldGen.isGeneratingOrLoadingWorld)
            {
                tileColorCache.Color = (byte)WorldGen.genRand.Next(1, 13);
            }
            tile.slope();
            tile.halfBrick();
            if (!tile.active() || tile.halfBrick() || tile.slope() != 0)
            {
                return false;
            }
            bool flag = ignoreWalls || WorldGen.DefaultTreeWallTest((int)Main.tile[i, num - 1].wall);
            if (!flag || tile2.liquid != 0)
            {
                return false;
            }
            if (tile.type != 53 && tile.type != 234 && tile.type != 116 && tile.type != 112)
            {
                return false;
            }
            int num2 = 20 + treeHeightAddon;
            if (!WorldGen.EmptyTileCheck(i, i, num - 2, num - 1, 20))
            {
                return false;
            }
            if (!WorldGen.EmptyTileCheck(i - 1, i + 1, num - num2, num - 3, 20))
            {
                return false;
            }
            int num3 = WorldGen.genRand.Next(10, 21) + treeHeightAddon;
            int num4 = WorldGen.genRand.Next(-8, 9);
            num4 *= 2;
            short num5 = 0;
            for (int j = 0; j < num3; j++)
            {
                tile = Main.tile[i, num - 1 - j];
                if (j == 0)
                {
                    tile.active(true);
                    tile.type = 323;
                    tile.frameX = 66;
                    tile.frameY = 0;
                    tile.UseBlockColors(tileColorCache);
                }
                else if (j == num3 - 1)
                {
                    tile.active(true);
                    tile.type = 323;
                    tile.frameX = (short)(22 * WorldGen.genRand.Next(4, 7));
                    tile.frameY = num5;
                    tile.UseBlockColors(tileColorCache);
                }
                else
                {
                    if ((int)num5 != num4)
                    {
                        double num6 = (double)j / (double)num3;
                        bool flag2 = num6 >= 0.25 && ((num6 < 0.5 && WorldGen.genRand.Next(13) == 0) || (num6 < 0.7 && WorldGen.genRand.Next(9) == 0) || num6 >= 0.95 || WorldGen.genRand.Next(5) != 0 || true);
                        if (flag2)
{
                            short num7 = (short)Math.Sign(num4);
                            num5 += num7 * 2;
                        }
                    }
                    tile.active(true);
                    tile.type = 323;
                    tile.frameX = (short)(22 * WorldGen.genRand.Next(0, 3));
                    tile.frameY = num5;
                    tile.UseBlockColors(tileColorCache);
                }
            }
            WorldGen.RangeFrame(i - 2, num - num3 - 1, i + 2, num + 1);
            NetMessage.SendTileSquare(-1, i, num - num3, 1, num3, TileChangeType.None);
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.WorldGen.DefaultTreeWallTest(), Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendTileSquare(), System.Math.Sign(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TryGrowingTreeByType().