Terraria Decompiled: Terraria.WorldGen.PlaceJunglePlant
PlaceJunglePlant()
static void Terraria.WorldGen.PlaceJunglePlant (int X2, int Y2, ushort type, int styleX, int styleY, bool inheritPaint) inline static
Definition at line 46155 of file WorldGen.cs.
        {
            if (styleY > 0 || type == 236 || type == 238 || type == 702)
            {
                int num = Y2;
                if (type == 95 || type == 126)
                {
                    num++;
                }
                if (X2 < 5 || X2 > Main.maxTilesX - 5 || num < 5 || num > Main.maxTilesY - 5)
                {
                    return;
                }
                bool flag = true;
                for (int i = X2 - 1; i < X2 + 1; i++)
                {
                    for (int j = num - 1; j < num + 1; j++)
                    {
                        if (Main.tile[i, j] == null)
{
                            Main.tile[i, j] = new Tile();
                        }
                        Tile tile = Main.tile[i, j];
                        if (tile.active() && tile.type != 61 && tile.type != 703 && tile.type != 62 && tile.type != 655 && tile.type != 69 && tile.type != 74 && (type != 236 || tile.type != 233) && (type != 702 || tile.type != 233) && (type != 238 || tile.type != 233) && (tile.type != 185 || tile.frameY != 0))
{
                            flag = false;
                        }
                        if (type == 98 && tile.liquid > 0)
{
                            flag = false;
                        }
                    }
                    if (Main.tile[i, num + 1] == null)
                    {
                        Main.tile[i, num + 1] = new Tile();
                    }
                    if (!WorldGen.SolidTile(i, num + 1, false) || Main.tile[i, num + 1].type != 60)
                    {
                        flag = false;
                    }
                }
                if (flag)
                {
                    for (int k = X2 - 1; k < X2 + 1; k++)
                    {
                        for (int l = num - 1; l < num + 1; l++)
{
                            if (Main.tile[k, l] != null && Main.tile[k, l].active())
{
                                WorldGen.KillTile(k, l, false, false, true);
                            }
                        }
                    }
                    short num2 = (short)(36 * styleX);
                    short num3 = 36;
                    if (type == 236 || type == 238 || type == 702)
                    {
                        num3 = 0;
                    }
                    Main.tile[X2 - 1, num - 1].active(true);
                    Main.tile[X2 - 1, num - 1].frameX = num2;
                    Main.tile[X2 - 1, num - 1].frameY = num3;
                    Main.tile[X2 - 1, num - 1].type = type;
                    Main.tile[X2, num - 1].active(true);
                    Main.tile[X2, num - 1].frameX = num2 + 18;
                    Main.tile[X2, num - 1].frameY = num3;
                    Main.tile[X2, num - 1].type = type;
                    Main.tile[X2 - 1, num].active(true);
                    Main.tile[X2 - 1, num].frameX = num2;
                    Main.tile[X2 - 1, num].frameY = num3 + 18;
                    Main.tile[X2 - 1, num].type = type;
                    Main.tile[X2, num].active(true);
                    Main.tile[X2, num].frameX = num2 + 18;
                    Main.tile[X2, num].frameY = num3 + 18;
                    Main.tile[X2, num].type = type;
                    if (inheritPaint)
                    {
                        Tile tile2 = Main.tile[X2, num + 1];
                        Main.tile[X2 - 1, num - 1].CopyPaintAndCoating(tile2);
                        Main.tile[X2, num - 1].CopyPaintAndCoating(tile2);
                        Main.tile[X2 - 1, num].CopyPaintAndCoating(tile2);
                        Main.tile[X2, num].CopyPaintAndCoating(tile2);
                        return;
                    }
                }
            }
            else
            {
                if (X2 < 5 || X2 > Main.maxTilesX - 5 || Y2 < 5 || Y2 > Main.maxTilesY - 5)
                {
                    return;
                }
                bool flag2 = true;
                for (int m = X2 - 1; m < X2 + 2; m++)
                {
                    for (int n = Y2 - 1; n < Y2 + 1; n++)
                    {
                        if (Main.tile[m, n] == null)
{
                            Main.tile[m, n] = new Tile();
                        }
                        if (Main.tile[m, n].active() && Main.tile[m, n].type != 61 && Main.tile[m, n].type != 703 && Main.tile[m, n].type != 62 && Main.tile[m, n].type != 69 && Main.tile[m, n].type != 655 && Main.tile[m, n].type != 74 && (Main.tile[m, n].type != 185 || Main.tile[m, n].frameY != 0))
{
                            flag2 = false;
                        }
                    }
                    if (Main.tile[m, Y2 + 1] == null)
                    {
                        Main.tile[m, Y2 + 1] = new Tile();
                    }
                    if (!WorldGen.SolidTile(m, Y2 + 1, false) || Main.tile[m, Y2 + 1].type != 60)
                    {
                        flag2 = false;
                    }
                }
                if (flag2)
                {
                    for (int num4 = X2 - 1; num4 < X2 + 2; num4++)
                    {
                        for (int num5 = Y2 - 1; num5 < Y2 + 1; num5++)
{
                            if (Main.tile[num4, num5] != null && Main.tile[num4, num5].active())
{
                                WorldGen.KillTile(num4, num5, false, false, true);
                            }
                        }
                    }
                    short num6 = (short)(54 * styleX);
                    Main.tile[X2 - 1, Y2 - 1].active(true);
                    Main.tile[X2 - 1, Y2 - 1].frameY = 0;
                    Main.tile[X2 - 1, Y2 - 1].frameX = num6;
                    Main.tile[X2 - 1, Y2 - 1].type = type;
                    Main.tile[X2, Y2 - 1].active(true);
                    Main.tile[X2, Y2 - 1].frameY = 0;
                    Main.tile[X2, Y2 - 1].frameX = num6 + 18;
                    Main.tile[X2, Y2 - 1].type = type;
                    Main.tile[X2 + 1, Y2 - 1].active(true);
                    Main.tile[X2 + 1, Y2 - 1].frameY = 0;
                    Main.tile[X2 + 1, Y2 - 1].frameX = num6 + 36;
                    Main.tile[X2 + 1, Y2 - 1].type = type;
                    Main.tile[X2 - 1, Y2].active(true);
                    Main.tile[X2 - 1, Y2].frameY = 18;
                    Main.tile[X2 - 1, Y2].frameX = num6;
                    Main.tile[X2 - 1, Y2].type = type;
                    Main.tile[X2, Y2].active(true);
                    Main.tile[X2, Y2].frameY = 18;
                    Main.tile[X2, Y2].frameX = num6 + 18;
                    Main.tile[X2, Y2].type = type;
                    Main.tile[X2 + 1, Y2].active(true);
                    Main.tile[X2 + 1, Y2].frameY = 18;
                    Main.tile[X2 + 1, Y2].frameX = num6 + 36;
                    Main.tile[X2 + 1, Y2].type = type;
                    if (inheritPaint)
                    {
                        Tile tile3 = Main.tile[X2, Y2 + 1];
                        Main.tile[X2 - 1, Y2 - 1].CopyPaintAndCoating(tile3);
                        Main.tile[X2, Y2 - 1].CopyPaintAndCoating(tile3);
                        Main.tile[X2 + 1, Y2 - 1].CopyPaintAndCoating(tile3);
                        Main.tile[X2 - 1, Y2].CopyPaintAndCoating(tile3);
                        Main.tile[X2, Y2].CopyPaintAndCoating(tile3);
                        Main.tile[X2 + 1, Y2].CopyPaintAndCoating(tile3);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt(), Terraria.WorldGen.PlaceTile(), and Terraria.WorldGen.UpdateWorld_GrassGrowth().