Terraria Decompiled: Terraria.WorldGen.RandomizeCaveBackgrounds
RandomizeCaveBackgrounds()
static void Terraria.WorldGen.RandomizeCaveBackgrounds () inline static
Definition at line 4133 of file WorldGen.cs.
        {
            int num = 8;
            if (Main.maxTilesX == 4200)
            {
                Main.caveBackX[0] = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.5 - (double)Main.maxTilesX * 0.25), (int)((double)Main.maxTilesX * 0.5 + (double)Main.maxTilesX * 0.25));
                Main.caveBackX[1] = Main.maxTilesX;
                Main.caveBackX[2] = Main.maxTilesX;
                Main.caveBackStyle[0] = WorldGen.genRand.Next(num);
                Main.caveBackStyle[1] = WorldGen.genRand.Next(num);
                while (Main.caveBackStyle[1] == Main.caveBackStyle[0])
                {
                    Main.caveBackStyle[1] = WorldGen.genRand.Next(num);
                }
            }
            else if (Main.maxTilesX == 6400)
            {
                Main.caveBackX[0] = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.334 - (double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.334 + (double)Main.maxTilesX * 0.2));
                Main.caveBackX[1] = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.667 - (double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.667 + (double)Main.maxTilesX * 0.2));
                Main.caveBackX[2] = Main.maxTilesX;
                Main.caveBackStyle[0] = WorldGen.genRand.Next(num);
                Main.caveBackStyle[1] = WorldGen.genRand.Next(num);
                Main.caveBackStyle[2] = WorldGen.genRand.Next(num);
                while (Main.caveBackStyle[1] == Main.caveBackStyle[0])
                {
                    Main.caveBackStyle[1] = WorldGen.genRand.Next(num);
                }
                while (Main.caveBackStyle[2] == Main.caveBackStyle[0] || Main.caveBackStyle[2] == Main.caveBackStyle[1])
                {
                    Main.caveBackStyle[2] = WorldGen.genRand.Next(num);
                }
            }
            else
            {
                Main.caveBackX[0] = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.25 - (double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.25 + (double)Main.maxTilesX * 0.15));
                Main.caveBackX[1] = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.5 - (double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.5 + (double)Main.maxTilesX * 0.15));
                Main.caveBackX[2] = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.75 - (double)Main.maxTilesX * 0.15), (int)((double)Main.maxTilesX * 0.75 + (double)Main.maxTilesX * 0.15));
                Main.caveBackStyle[0] = WorldGen.genRand.Next(num);
                Main.caveBackStyle[1] = WorldGen.genRand.Next(num);
                Main.caveBackStyle[2] = WorldGen.genRand.Next(num);
                Main.caveBackStyle[3] = WorldGen.genRand.Next(num);
                while (Main.caveBackStyle[1] == Main.caveBackStyle[0])
                {
                    Main.caveBackStyle[1] = WorldGen.genRand.Next(num);
                }
                while (Main.caveBackStyle[2] == Main.caveBackStyle[0] || Main.caveBackStyle[2] == Main.caveBackStyle[1])
                {
                    Main.caveBackStyle[2] = WorldGen.genRand.Next(num);
                }
                while (Main.caveBackStyle[3] == Main.caveBackStyle[0] || Main.caveBackStyle[3] == Main.caveBackStyle[1] || Main.caveBackStyle[3] == Main.caveBackStyle[2])
                {
                    Main.caveBackStyle[3] = WorldGen.genRand.Next(num);
                }
            }
            Main.iceBackStyle = WorldGen.genRand.Next(4);
            Main.hellBackStyle = WorldGen.genRand.Next(3);
            Main.jungleBackStyle = WorldGen.genRand.Next(2);
        }
References Terraria.Main.caveBackStyle, Terraria.Main.caveBackX, Terraria.WorldGen.genRand, Terraria.Main.maxTilesX, and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.Main.Initialize_AlmostEverything(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), and Terraria.WorldGen.Reset().