Terraria Decompiled: Terraria.WorldGen.randGemTile
randGemTile()
static ushort Terraria.WorldGen.randGemTile () inline static
Definition at line 5674 of file WorldGen.cs.
        {
            if (WorldGen.genRand.Next(20) != 0)
            {
                return 1;
            }
            ushort num = (ushort)WorldGen.randGem();
            if (num == 0)
            {
                return 67;
            }
            if (num == 1)
            {
                return 66;
            }
            if (num == 2)
            {
                return 63;
            }
            if (num == 3)
            {
                return 65;
            }
            if (num == 4)
            {
                return 64;
            }
            return 68;
        }
References Terraria.WorldGen.genRand, Terraria.Utilities.UnifiedRandom.Next(), and Terraria.WorldGen.randGem().
Referenced by Terraria.WorldGen.Spread.Gem().