Terraria Decompiled: Terraria.WorldGen.AddHellHouses
AddHellHouses()
static void Terraria.WorldGen.AddHellHouses () inline static
Definition at line 29537 of file WorldGen.cs.
        {
            int num = (int)((double)Main.maxTilesX * 0.25);
            for (int i = 100; i < Main.maxTilesX - 100; i++)
            {
                if (((!WorldGen.drunkWorldGen && !WorldGen.remixWorldGen) || i <= num || i >= Main.maxTilesX - num) && (WorldGen.drunkWorldGen || WorldGen.remixWorldGen || (i >= num && i <= Main.maxTilesX - num)))
                {
                    int num2 = Main.maxTilesY - 40;
                    while (Main.tile[i, num2].active() || Main.tile[i, num2].liquid > 0)
                    {
                        num2--;
                    }
                    if (Main.tile[i, num2 + 1].active())
                    {
                        ushort num3 = (ushort)WorldGen.genRand.Next(75, 77);
                        byte b = 13;
                        if (WorldGen.genRand.Next(5) > 0)
{
                            num3 = 75;
                        }
                        if (num3 == 75)
{
                            b = 14;
                        }
                        if (WorldGen.getGoodWorldGen)
{
                            num3 = 76;
                        }
                        WorldGen.HellFort(i, num2, num3, b);
                        i += WorldGen.genRand.Next(30, 130);
                        if (WorldGen.genRand.Next(10) == 0)
{
                            i += WorldGen.genRand.Next(0, 200);
                        }
                    }
                }
            }
            float num4 = (float)(Main.maxTilesX / 4200);
            int num5 = 0;
            while ((float)num5 < 200f * num4)
            {
                int num6 = 0;
                bool flag = false;
                while (!flag)
                {
                    num6++;
                    int num7 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                    int num8 = WorldGen.genRand.Next(Main.maxTilesY - 300, Main.maxTilesY - 20);
                    if (Main.tile[num7, num8].active() && (Main.tile[num7, num8].type == 75 || Main.tile[num7, num8].type == 76))
                    {
                        int num9 = 0;
                        if (Main.tile[num7 - 1, num8].wall > 0)
{
                            num9 = -1;
                        }
                        else if (Main.tile[num7 + 1, num8].wall > 0)
{
                            num9 = 1;
                        }
                        if (!Main.tile[num7 + num9, num8].active() && !Main.tile[num7 + num9, num8 + 1].active())
{
                            bool flag2 = false;
                            for (int j = num7 - 8; j < num7 + 8; j++)
{
                                for (int k = num8 - 8; k < num8 + 8; k++)
{
                                    if (Main.tile[j, k].active() && Main.tile[j, k].type == 4)
{
                                        flag2 = true;
                                        break;
                                    }
                                }
                            }
                            if (!flag2)
{
                                WorldGen.PlaceTile(num7 + num9, num8, 4, true, true, -1, 7);
                                flag = true;
                            }
                        }
                    }
                    if (num6 > 1000)
                    {
                        flag = true;
                    }
                }
                num5++;
            }
            double num10 = 4200000.0 / (double)Main.maxTilesX;
            int num11 = 0;
            while ((double)num11 < num10)
            {
                int num12 = 0;
                int num13 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                int num14 = WorldGen.genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 20);
                while ((Main.tile[num13, num14].wall != 13 && Main.tile[num13, num14].wall != 14) || Main.tile[num13, num14].active())
                {
                    num13 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    num14 = WorldGen.genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 20);
                    if (WorldGen.drunkWorldGen || WorldGen.remixWorldGen)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num13 = WorldGen.genRand.Next(50, num);
                        }
                        else
{
                            num13 = WorldGen.genRand.Next(Main.maxTilesX - num, Main.maxTilesX - 50);
                        }
                    }
                    num12++;
                    if (num12 > 100000)
                    {
                        break;
                    }
                }
                if (num12 <= 100000 && (Main.tile[num13, num14].wall == 13 || Main.tile[num13, num14].wall == 14) && !Main.tile[num13, num14].active())
                {
                    while (!WorldGen.SolidTile(num13, num14, false) && num14 < Main.maxTilesY - 20)
                    {
                        num14++;
                    }
                    num14--;
                    int num15 = num13;
                    int num16 = num13;
                    while (!Main.tile[num15, num14].active() && WorldGen.SolidTile(num15, num14 + 1, false))
                    {
                        num15--;
                    }
                    num15++;
                    while (!Main.tile[num16, num14].active() && WorldGen.SolidTile(num16, num14 + 1, false))
                    {
                        num16++;
                    }
                    num16--;
                    int num17 = num16 - num15;
                    int num18 = (num16 + num15) / 2;
                    if (!Main.tile[num18, num14].active() && (Main.tile[num18, num14].wall == 13 || Main.tile[num18, num14].wall == 14) && WorldGen.SolidTile(num18, num14 + 1, false))
                    {
                        int num19 = 16;
                        int num20 = 13;
                        int num21 = 14;
                        int num22 = 49;
                        int num23 = 4;
                        int num24 = 8;
                        int num25 = 15;
                        int num26 = 9;
                        int num27 = 10;
                        int num28 = 17;
                        int num29 = 25;
                        int num30 = 25;
                        int num31 = 23;
                        int num32 = 25;
                        int num33 = WorldGen.genRand.Next(13);
                        int num34 = 0;
                        int num35 = 0;
                        if (num33 == 0)
{
                            num34 = 5;
                            num35 = 4;
                        }
                        if (num33 == 1)
{
                            num34 = 4;
                            num35 = 3;
                        }
                        if (num33 == 2)
{
                            num34 = 3;
                            num35 = 5;
                        }
                        if (num33 == 3)
{
                            num34 = 4;
                            num35 = 6;
                        }
                        if (num33 == 4)
{
                            num34 = 3;
                            num35 = 3;
                        }
                        if (num33 == 5)
{
                            num34 = 5;
                            num35 = 3;
                        }
                        if (num33 == 6)
{
                            num34 = 5;
                            num35 = 4;
                        }
                        if (num33 == 7)
{
                            num34 = 5;
                            num35 = 4;
                        }
                        if (num33 == 8)
{
                            num34 = 5;
                            num35 = 4;
                        }
                        if (num33 == 9)
{
                            num34 = 3;
                            num35 = 5;
                        }
                        if (num33 == 10)
{
                            num34 = 5;
                            num35 = 3;
                        }
                        if (num33 == 11)
{
                            num34 = 2;
                            num35 = 4;
                        }
                        if (num33 == 12)
{
                            num34 = 3;
                            num35 = 3;
                        }
                        for (int l = num18 - num34; l <= num18 + num34; l++)
{
                            for (int m = num14 - num35; m <= num14; m++)
{
                                if (Main.tile[l, m].active())
{
                                    num33 = -1;
                                    break;
                                }
                            }
                        }
                        if ((double)num17 < (double)num34 * 1.75)
{
                            num33 = -1;
                        }
                        if (num33 == 0)
{
                            WorldGen.PlaceTile(num18, num14, 14, true, false, -1, num20);
                            int num36 = WorldGen.genRand.Next(6);
                            if (num36 < 3)
{
                                WorldGen.PlaceTile(num18 + num36, num14 - 2, 33, true, false, -1, num30);
                            }
                            if (Main.tile[num18, num14].active())
{
                                if (!Main.tile[num18 - 2, num14].active())
{
                                    WorldGen.PlaceTile(num18 - 2, num14, 15, true, false, -1, num19);
                                    if (Main.tile[num18 - 2, num14].active())
{
                                        Tile tile = Main.tile[num18 - 2, num14];
                                        tile.frameX += 18;
                                        Tile tile2 = Main.tile[num18 - 2, num14 - 1];
                                        tile2.frameX += 18;
                                    }
                                }
                                if (!Main.tile[num18 + 2, num14].active())
{
                                    WorldGen.PlaceTile(num18 + 2, num14, 15, true, false, -1, num19);
                                }
                            }
                        }
                        else if (num33 == 1)
{
                            WorldGen.PlaceTile(num18, num14, 18, true, false, -1, num21);
                            int num37 = WorldGen.genRand.Next(4);
                            if (num37 < 2)
{
                                WorldGen.PlaceTile(num18 + num37, num14 - 1, 33, true, false, -1, num30);
                            }
                            if (Main.tile[num18, num14].active())
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    if (!Main.tile[num18 - 1, num14].active())
{
                                        WorldGen.PlaceTile(num18 - 1, num14, 15, true, false, -1, num19);
                                        if (Main.tile[num18 - 1, num14].active())
{
                                            Tile tile3 = Main.tile[num18 - 1, num14];
                                            tile3.frameX += 18;
                                            Tile tile4 = Main.tile[num18 - 1, num14 - 1];
                                            tile4.frameX += 18;
                                        }
                                    }
                                }
                                else if (!Main.tile[num18 + 2, num14].active())
{
                                    WorldGen.PlaceTile(num18 + 2, num14, 15, true, false, -1, num19);
                                }
                            }
                        }
                        else if (num33 == 2)
{
                            WorldGen.PlaceTile(num18, num14, 105, true, false, -1, num22);
                        }
                        else if (num33 == 3)
{
                            WorldGen.PlaceTile(num18, num14, 101, true, false, -1, num23);
                        }
                        else if (num33 == 4)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.PlaceTile(num18, num14, 15, true, false, -1, num19);
                                Tile tile5 = Main.tile[num18, num14];
                                tile5.frameX += 18;
                                Tile tile6 = Main.tile[num18, num14 - 1];
                                tile6.frameX += 18;
                            }
                            else
{
                                WorldGen.PlaceTile(num18, num14, 15, true, false, -1, num19);
                            }
                        }
                        else if (num33 == 5)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.Place4x2(num18, num14, 79, 1, num24);
                            }
                            else
{
                                WorldGen.Place4x2(num18, num14, 79, -1, num24);
                            }
                        }
                        else if (num33 == 6)
{
                            WorldGen.PlaceTile(num18, num14, 87, true, false, -1, num25);
                        }
                        else if (num33 == 7)
{
                            WorldGen.PlaceTile(num18, num14, 88, true, false, -1, num26);
                        }
                        else if (num33 == 8)
{
                            WorldGen.PlaceTile(num18, num14, 89, true, false, -1, num27);
                        }
                        else if (num33 == 9)
{
                            WorldGen.PlaceTile(num18, num14, 104, true, false, -1, num28);
                        }
                        else if (num33 == 10)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.Place4x2(num18, num14, 90, 1, num32);
                            }
                            else
{
                                WorldGen.Place4x2(num18, num14, 90, -1, num32);
                            }
                        }
                        else if (num33 == 11)
{
                            WorldGen.PlaceTile(num18, num14, 93, true, false, -1, num31);
                        }
                        else if (num33 == 12)
{
                            WorldGen.PlaceTile(num18, num14, 100, true, false, -1, num29);
                        }
                    }
                }
                num11++;
            }
            num10 = 420000.0 / (double)Main.maxTilesX;
            int num38 = 0;
            while ((double)num38 < num10)
            {
                int num39 = 0;
                int num40 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                int num41 = WorldGen.genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 20);
                while ((Main.tile[num40, num41].wall != 13 && Main.tile[num40, num41].wall != 14) || Main.tile[num40, num41].active())
                {
                    num40 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    num41 = WorldGen.genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 20);
                    if (WorldGen.drunkWorldGen || WorldGen.remixWorldGen)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num40 = WorldGen.genRand.Next(50, num);
                        }
                        else
{
                            num40 = WorldGen.genRand.Next(Main.maxTilesX - num, Main.maxTilesX - 50);
                        }
                    }
                    num39++;
                    if (num39 > 100000)
                    {
                        break;
                    }
                }
                if (num39 <= 100000)
                {
                    int num42;
                    int num43;
                    int num44;
                    int num45;
                    for (int n = 0; n < 2; n++)
                    {
                        num42 = num40;
                        num43 = num40;
                        while (!Main.tile[num42, num41].active() && (Main.tile[num42, num41].wall == 13 || Main.tile[num42, num41].wall == 14) && num42 > 10)
{
                            num42--;
                        }
                        num42++;
                        while (!Main.tile[num43, num41].active() && (Main.tile[num43, num41].wall == 13 || Main.tile[num43, num41].wall == 14) && num43 < Main.maxTilesX - 10)
{
                            num43++;
                        }
                        num43--;
                        num40 = (num42 + num43) / 2;
                        num44 = num41;
                        num45 = num41;
                        while (!Main.tile[num40, num44].active() && (Main.tile[num40, num44].wall == 13 || Main.tile[num40, num44].wall == 14))
{
                            num44--;
                        }
                        num44++;
                        while (!Main.tile[num40, num45].active() && (Main.tile[num40, num45].wall == 13 || Main.tile[num40, num45].wall == 14))
{
                            num45++;
                        }
                        num45--;
                        num41 = (num44 + num45) / 2;
                    }
                    num42 = num40;
                    num43 = num40;
                    while (!Main.tile[num42, num41].active() && !Main.tile[num42, num41 - 1].active() && !Main.tile[num42, num41 + 1].active() && num42 > 10)
                    {
                        num42--;
                    }
                    num42++;
                    while (!Main.tile[num43, num41].active() && !Main.tile[num43, num41 - 1].active() && !Main.tile[num43, num41 + 1].active() && num43 < Main.maxTilesX - 10)
                    {
                        num43++;
                    }
                    num43--;
                    num44 = num41;
                    num45 = num41;
                    while (!Main.tile[num40, num44].active() && !Main.tile[num40 - 1, num44].active() && !Main.tile[num40 + 1, num44].active())
                    {
                        num44--;
                    }
                    num44++;
                    while (!Main.tile[num40, num45].active() && !Main.tile[num40 - 1, num45].active() && !Main.tile[num40 + 1, num45].active())
                    {
                        num45++;
                    }
                    num45--;
                    num40 = (num42 + num43) / 2;
                    num41 = (num44 + num45) / 2;
                    int num46 = num43 - num42;
                    int num47 = num45 - num44;
                    if (num46 > 7 && num47 > 5)
                    {
                        int num48 = 0;
                        if (WorldGen.nearPicture2(num40, num41))
{
                            num48 = -1;
                        }
                        if (num48 == 0)
{
                            PaintingEntry paintingEntry = WorldGen.RandHellPicture();
                            if (!WorldGen.nearPicture(num40, num41))
{
                                WorldGen.PlaceTile(num40, num41, paintingEntry.tileType, true, false, -1, paintingEntry.style);
                            }
                        }
                    }
                }
                num38++;
            }
            int[] array = new int[]
            {
                WorldGen.genRand.Next(16, 22),
                WorldGen.genRand.Next(16, 22),
                WorldGen.genRand.Next(16, 22)
            };
            while (array[1] == array[0])
            {
                array[1] = WorldGen.genRand.Next(16, 22);
            }
            while (array[2] == array[0] || array[2] == array[1])
            {
                array[2] = WorldGen.genRand.Next(16, 22);
            }
            num10 = 420000.0 / (double)Main.maxTilesX;
            int num49 = 0;
            while ((double)num49 < num10)
            {
                int num50 = 0;
                int num51;
                int num52;
                do
                {
                    num51 = WorldGen.genRand.Next(num, Main.maxTilesX - num);
                    num52 = WorldGen.genRand.Next(Main.maxTilesY - 250, Main.maxTilesY - 20);
                    if (WorldGen.drunkWorldGen || WorldGen.remixWorldGen)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num51 = WorldGen.genRand.Next(50, num);
                        }
                        else
{
                            num51 = WorldGen.genRand.Next(Main.maxTilesX - num, Main.maxTilesX - 50);
                        }
                    }
                    num50++;
                }
                while (num50 <= 100000 && ((Main.tile[num51, num52].wall != 13 && Main.tile[num51, num52].wall != 14) || Main.tile[num51, num52].active()));
                if (num50 <= 100000)
                {
                    while (!WorldGen.SolidTile(num51, num52, false) && num52 > 10)
                    {
                        num52--;
                    }
                    num52++;
                    if (Main.tile[num51, num52].wall == 13 || Main.tile[num51, num52].wall == 14)
                    {
                        int num53 = WorldGen.genRand.Next(3);
                        int num54 = 32;
                        int num55 = 32;
                        int num56;
                        int num57;
                        switch (num53)
{
                        default:
                            num56 = 1;
                            num57 = 3;
                            break;
                        case 1:
                            num56 = 3;
                            num57 = 3;
                            break;
                        case 2:
                            num56 = 1;
                            num57 = 2;
                            break;
                        }
                        for (int num58 = num51 - 1; num58 <= num51 + num56; num58++)
{
                            for (int num59 = num52; num59 <= num52 + num57; num59++)
{
                                Tile tile7 = Main.tile[num51, num52];
                                if (num58 < num51 || num58 == num51 + num56)
{
                                    if (tile7.active())
{
                                        ushort type = tile7.type;
                                        if (type <= 34)
{
                                            if (type - 10 > 1 && type != 34)
{
                                                goto IL_11DD;
                                            }
                                        }
                                        else if (type != 42 && type != 91)
{
                                            goto IL_11DD;
                                        }
                                        num53 = -1;
                                    }
                                }
                                else if (tile7.active())
{
                                    num53 = -1;
                                }
                                IL_11DD:;
                            }
                        }
                        switch (num53)
{
                        case 0:
                            WorldGen.PlaceTile(num51, num52, 91, true, false, -1, array[WorldGen.genRand.Next(3)]);
                            break;
                        case 1:
                            WorldGen.PlaceTile(num51, num52, 34, true, false, -1, num54);
                            break;
                        case 2:
                            WorldGen.PlaceTile(num51, num52, 42, true, false, -1, num55);
                            break;
                        }
                    }
                }
                num49++;
            }
        }
References Terraria.Tile.active(), System.array, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.WorldGen.HellFort(), int, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.nearPicture(), Terraria.WorldGen.nearPicture2(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.RandHellPicture(), Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.SolidTile(), Terraria.GameContent.Generation.PaintingEntry.style, Terraria.Main.tile, Terraria.GameContent.Generation.PaintingEntry.tileType, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.AddPasses().