Terraria Decompiled: Terraria.WorldGen.TileFrameCosmetic
TileFrameCosmetic()
static void Terraria.WorldGen.TileFrameCosmetic (int i, int j, Tile tileCache, bool resetFrame = false) inline static
Definition at line 82128 of file WorldGen.cs.
        {
            if (tileCache == null || !tileCache.active())
            {
                return;
            }
            if (i <= 0 || j <= 0 || i >= Main.maxTilesX - 1 || j >= Main.maxTilesY - 1)
            {
                return;
            }
            int num = (int)tileCache.type;
            if (Main.tileFrameImportant[num])
            {
                return;
            }
            if (num == 80)
            {
                WorldGen.CactusFrame(i, j);
                return;
            }
            if ((num >= 255 && num <= 268) || num == 385 || (num >= 446 && num <= 448))
            {
                Framing.SelfFrame8Way(i, j, tileCache, resetFrame);
                return;
            }
            if (Main.tileStone[num])
            {
                num = 1;
            }
            int frameX = (int)tileCache.frameX;
            int frameY = (int)tileCache.frameY;
            Rectangle rectangle = new Rectangle(-1, -1, 0, 0);
            Tile tile = Main.tile[i, j - 1];
            Tile tile2 = Main.tile[i, j + 1];
            Tile tile3 = Main.tile[i - 1, j];
            Tile tile4 = Main.tile[i + 1, j];
            Tile tile5 = Main.tile[i - 1, j + 1];
            Tile tile6 = Main.tile[i + 1, j + 1];
            Tile tile7 = Main.tile[i - 1, j - 1];
            Tile tile8 = Main.tile[i + 1, j - 1];
            WorldGen.TileMergeCullCache tileMergeCulling = WorldGen.GetTileMergeCulling(tileCache, tile, tile2, tile3, tile4, tile5, tile6, tile7, tile8);
            int num2 = -1;
            int num3 = -1;
            int num4 = -1;
            int num5 = -1;
            int num6 = -1;
            int num7 = -1;
            int num8 = -1;
            int num9 = -1;
            if (tile3 != null && tile3.active())
            {
                if (Main.tileStone[(int)tile3.type])
                {
                    num5 = 1;
                }
                else
                {
                    num5 = (int)tile3.type;
                }
                if (tile3.slope() == 1 || tile3.slope() == 3)
                {
                    num5 = -1;
                }
            }
            if (tile4 != null && tile4.active())
            {
                if (Main.tileStone[(int)tile4.type])
                {
                    num6 = 1;
                }
                else
                {
                    num6 = (int)tile4.type;
                }
                if (tile4.slope() == 2 || tile4.slope() == 4)
                {
                    num6 = -1;
                }
            }
            if (tile != null && tile.active())
            {
                if (Main.tileStone[(int)tile.type])
                {
                    num3 = 1;
                }
                else
                {
                    num3 = (int)tile.type;
                }
                if (tile.slope() == 3 || tile.slope() == 4)
                {
                    num3 = -1;
                }
            }
            if (tile2 != null && tile2.active())
            {
                if (Main.tileStone[(int)tile2.type])
                {
                    num8 = 1;
                }
                else
                {
                    num8 = (int)tile2.type;
                }
                if (tile2.slope() == 1 || tile2.slope() == 2)
                {
                    num8 = -1;
                }
            }
            if (tile7 != null && tile7.active())
            {
                if (Main.tileStone[(int)tile7.type])
                {
                    num2 = 1;
                }
                else
                {
                    num2 = (int)tile7.type;
                }
            }
            if (tile8 != null && tile8.active())
            {
                if (Main.tileStone[(int)tile8.type])
                {
                    num4 = 1;
                }
                else
                {
                    num4 = (int)tile8.type;
                }
            }
            if (tile5 != null && tile5.active())
            {
                if (Main.tileStone[(int)tile5.type])
                {
                    num7 = 1;
                }
                else
                {
                    num7 = (int)tile5.type;
                }
            }
            if (tile6 != null && tile6.active())
            {
                if (Main.tileStone[(int)tile6.type])
                {
                    num9 = 1;
                }
                else
                {
                    num9 = (int)tile6.type;
                }
            }
            if (tileCache.slope() == 2)
            {
                num3 = -1;
                num5 = -1;
            }
            if (tileCache.slope() == 1)
            {
                num3 = -1;
                num6 = -1;
            }
            if (tileCache.slope() == 4)
            {
                num8 = -1;
                num5 = -1;
            }
            if (tileCache.slope() == 3)
            {
                num8 = -1;
                num6 = -1;
            }
            if (num == 668)
            {
                num = 0;
            }
            if (num == 697)
            {
                num = 51;
            }
            WorldGen.TileMergeAttempt(0, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            if (num == 147)
            {
                WorldGen.TileMergeAttempt(num, Main.tileBrick, TileID.Sets.DontMergeWithSnow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 161 || num == 163 || num == 164 || num == 200)
            {
                WorldGen.TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Snow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 162)
            {
                WorldGen.TileMergeAttempt(num, Main.tileBrick, TileID.Sets.IcesSnow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 738)
            {
                WorldGen.TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Snow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 747)
            {
                WorldGen.TileMergeAttempt(num, Main.tileBrick, 53, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (Main.tileBrick[num])
            {
                if (num == 60 || num == 70 || num == 662 || num == 661)
                {
                    WorldGen.TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                else if (num == 633)
                {
                    WorldGen.TileMergeAttempt(num, Main.tileBrick, TileID.Sets.Ash, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                else
                {
                    WorldGen.TileMergeAttempt(num, Main.tileBrick, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
            }
            else if (Main.tilePile[num])
            {
                WorldGen.TileMergeAttempt(num, Main.tilePile, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            int num10 = (int)((tile2 == null) ? -1 : tile2.frameY);
            int num11 = (int)((tile == null) ? -1 : tile.frameY);
            if (num <= 147)
            {
                if (num <= 25)
                {
                    if (num == 1 || num == 25)
                    {
                        goto IL_0599;
                    }
                }
                else if (num == 117 || num == 147)
                {
                    goto IL_0599;
                }
            }
            else if (num <= 164)
            {
                if (num == 161 || num - 163 <= 1)
                {
                    goto IL_0599;
                }
            }
            else if (num == 200 || num == 203 || num == 225)
            {
                goto IL_0599;
            }
            bool flag = false;
            goto IL_059C;
            IL_0599:
            flag = true;
            IL_059C:
            if (Main.tileMoss[num])
            {
                flag = true;
            }
            bool flag2 = num10 == 0 || num10 == 72;
            bool flag3 = num11 == 54 || num11 == 90;
            if (num8 == 165 && flag && flag2)
            {
                num8 = num;
            }
            if (num3 == 165 && flag && flag3)
            {
                num3 = num;
            }
            int num12 = (int)((tile2 == null) ? -1 : tile2.frameY);
            int num13 = (int)((tile == null) ? -1 : tile.frameY);
            if (num <= 147)
            {
                if (num <= 25)
                {
                    if (num == 1 || num == 25)
                    {
                        goto IL_0673;
                    }
                }
                else if (num == 117 || num == 147)
                {
                    goto IL_0673;
                }
            }
            else if (num <= 164)
            {
                if (num == 161 || num - 163 <= 1)
                {
                    goto IL_0673;
                }
            }
            else if (num == 200 || num == 203 || num == 225)
            {
                goto IL_0673;
            }
            bool flag4 = false;
            goto IL_0676;
            IL_0673:
            flag4 = true;
            IL_0676:
            if (Main.tileMoss[num])
            {
                flag4 = true;
            }
            bool flag5 = num12 == 0;
            bool flag6 = ((num3 == 693) ? (num13 >= 18) : (num13 >= 36));
            if ((num8 == 693 || num8 == 694) && flag4 && flag5)
            {
                num8 = num;
            }
            if ((num3 == 693 || num3 == 694) && flag4 && flag6)
            {
                num3 = num;
            }
            if ((tileCache.slope() == 1 || tileCache.slope() == 2) && num8 > -1 && !TileID.Sets.Platforms[num8])
            {
                num8 = num;
            }
            if (num3 > -1 && tile != null && (tile.slope() == 1 || tile.slope() == 2) && !TileID.Sets.Platforms[num3])
            {
                num3 = num;
            }
            if ((tileCache.slope() == 3 || tileCache.slope() == 4) && num3 > -1 && !TileID.Sets.Platforms[num3])
            {
                num3 = num;
            }
            if (num8 > -1 && tile2 != null && (tile2.slope() == 3 || tile2.slope() == 4) && !TileID.Sets.Platforms[num8])
            {
                num8 = num;
            }
            if (num == 124)
            {
                if (num3 > -1 && Main.tileSolid[num3] && !TileID.Sets.Platforms[num3])
                {
                    num3 = num;
                }
                if (num8 > -1 && Main.tileSolid[num8] && !TileID.Sets.Platforms[num8])
                {
                    num8 = num;
                }
            }
            if (num3 > -1 && tile != null && tile.halfBrick() && !TileID.Sets.Platforms[num3])
            {
                num3 = num;
            }
            if (num5 > -1 && tile3 != null && tile3.halfBrick())
            {
                if (tileCache.halfBrick())
                {
                    num5 = num;
                }
                else if ((int)tile3.type != num)
                {
                    num5 = -1;
                }
            }
            if (num6 > -1 && tile4 != null && tile4.halfBrick())
            {
                if (tileCache.halfBrick())
                {
                    num6 = num;
                }
                else if ((int)tile4.type != num)
                {
                    num6 = -1;
                }
            }
            if (tileCache.halfBrick())
            {
                if (num5 != num)
                {
                    num5 = -1;
                }
                if (num6 != num)
                {
                    num6 = -1;
                }
                num3 = -1;
            }
            if (tile2 != null && tile2.halfBrick())
            {
                num8 = -1;
            }
            WorldGen.mergeUp = false;
            WorldGen.mergeDown = false;
            WorldGen.mergeLeft = false;
            WorldGen.mergeRight = false;
            int num14;
            if (resetFrame)
            {
                num14 = WorldGen.genRand.Next(0, 3);
                tileCache.frameNumber((byte)num14);
            }
            else
            {
                num14 = (int)tileCache.frameNumber();
            }
            if (Main.tileLargeFrames[num] == 1)
            {
                int num15 = j % 4;
                int num16 = i % 3;
                num14 = (new int[,]
                {
                    { 2, 4, 2 },
                    { 1, 3, 1 },
                    { 2, 2, 4 },
                    { 1, 1, 3 }
                })[num15, num16] - 1;
            }
            if (Main.tileLargeFrames[num] == 2)
            {
                int num17 = i % 2;
                int num18 = j % 2;
                num14 = num17 + num18 * 2;
            }
            if (!Main.tileRope[num] && TileID.Sets.BlockMergesWithMergeAllBlock[num])
            {
                WorldGen.TileMergeAttempt(num, Main.tileBlendAll, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (Main.tileBlendAll[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.BlockMergesWithMergeAllBlock, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (TileID.Sets.ForcedDirtMerging[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (TileID.Sets.Dirt[num])
            {
                if (num3 > -1 && Main.tileMergeDirt[num3])
                {
                    WorldGen.TileFrame(i, j - 1, false, false);
                    if (WorldGen.mergeDown)
                    {
                        num3 = num;
                    }
                }
                else if (num3 == 147)
                {
                    WorldGen.TileFrame(i, j - 1, false, false);
                    if (WorldGen.mergeDown)
                    {
                        num3 = num;
                    }
                }
                if (num8 > -1 && Main.tileMergeDirt[num8])
                {
                    WorldGen.TileFrame(i, j + 1, false, false);
                    if (WorldGen.mergeUp)
                    {
                        num8 = num;
                    }
                }
                else if (num8 == 147)
                {
                    WorldGen.TileFrame(i, j + 1, false, false);
                    if (WorldGen.mergeUp)
                    {
                        num8 = num;
                    }
                }
                if (num5 > -1 && Main.tileMergeDirt[num5])
                {
                    WorldGen.TileFrame(i - 1, j, false, false);
                    if (WorldGen.mergeRight)
                    {
                        num5 = num;
                    }
                }
                else if (num5 == 147)
                {
                    WorldGen.TileFrame(i - 1, j, false, false);
                    if (WorldGen.mergeRight)
                    {
                        num5 = num;
                    }
                }
                if (num6 > -1 && Main.tileMergeDirt[num6])
                {
                    WorldGen.TileFrame(i + 1, j, false, false);
                    if (WorldGen.mergeLeft)
                    {
                        num6 = num;
                    }
                }
                else if (num6 == 147)
                {
                    WorldGen.TileFrame(i + 1, j, false, false);
                    if (WorldGen.mergeLeft)
                    {
                        num6 = num;
                    }
                }
                bool[] mergesWithDirtInASpecialWay = TileID.Sets.Conversion.MergesWithDirtInASpecialWay;
                if (num3 > -1 && mergesWithDirtInASpecialWay[num3])
                {
                    num3 = num;
                }
                if (num8 > -1 && mergesWithDirtInASpecialWay[num8])
                {
                    num8 = num;
                }
                if (num5 > -1 && mergesWithDirtInASpecialWay[num5])
                {
                    num5 = num;
                }
                if (num6 > -1 && mergesWithDirtInASpecialWay[num6])
                {
                    num6 = num;
                }
                if (num2 > -1 && Main.tileMergeDirt[num2])
                {
                    num2 = num;
                }
                else if (num2 > -1 && mergesWithDirtInASpecialWay[num2])
                {
                    num2 = num;
                }
                if (num4 > -1 && Main.tileMergeDirt[num4])
                {
                    num4 = num;
                }
                else if (num4 > -1 && mergesWithDirtInASpecialWay[num4])
                {
                    num4 = num;
                }
                if (num7 > -1 && Main.tileMergeDirt[num7])
                {
                    num7 = num;
                }
                else if (num7 > -1 && mergesWithDirtInASpecialWay[num7])
                {
                    num7 = num;
                }
                if (num9 > -1 && Main.tileMergeDirt[num9])
                {
                    num9 = num;
                }
                else if (num9 > -1 && mergesWithDirtInASpecialWay[num9])
                {
                    num9 = num;
                }
                int num19 = 0;
                WorldGen.TileMergeAttempt(num19, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num19, 191, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                if (num3 > -1 && TileID.Sets.ForcedDirtMerging[num3])
                {
                    num3 = num;
                }
                if (num8 > -1 && TileID.Sets.ForcedDirtMerging[num8])
                {
                    num8 = num;
                }
                if (num5 > -1 && TileID.Sets.ForcedDirtMerging[num5])
                {
                    num5 = num;
                }
                if (num6 > -1 && TileID.Sets.ForcedDirtMerging[num6])
                {
                    num6 = num;
                }
                if (num2 > -1 && TileID.Sets.ForcedDirtMerging[num2])
                {
                    num2 = num;
                }
                if (num4 > -1 && TileID.Sets.ForcedDirtMerging[num4])
                {
                    num4 = num;
                }
                if (num7 > -1 && TileID.Sets.ForcedDirtMerging[num7])
                {
                    num7 = num;
                }
                if (num9 > -1 && TileID.Sets.ForcedDirtMerging[num9])
                {
                    num9 = num;
                }
            }
            else if (Main.tileRope[num])
            {
                if (num != 504 && num3 != num && WorldGen.IsRope(i, j - 1, 5))
                {
                    num3 = num;
                }
                if (num8 != num && (WorldGen.IsRope(i, j + 1, 5) || num8 == 698))
                {
                    num8 = num;
                }
                if (num != 504 && num3 > -1 && Main.tileSolid[num3] && !Main.tileSolidTop[num3])
                {
                    num3 = num;
                }
                if (num8 > -1 && Main.tileSolid[num8])
                {
                    num8 = num;
                }
                if (num != 504 && num3 != num)
                {
                    if (num5 > -1 && Main.tileSolid[num5])
                    {
                        num5 = num;
                    }
                    if (num6 > -1 && Main.tileSolid[num6])
                    {
                        num6 = num;
                    }
                }
                if (num3 == -1)
                {
                    WorldGen.TileFrame(i, j - 1, false, false);
                }
                if (num8 == -1)
                {
                    WorldGen.TileFrame(i, j + 1, false, false);
                }
            }
            else if (num == 53)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 397, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 396, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 234)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 399, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 401, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 112)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 398, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 400, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 116)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 402, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 403, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (Main.tileMergeDirt[num])
            {
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                if (num == 1)
                {
                    if ((double)j > Main.rockLayer)
                    {
                        WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                    }
                    WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.Ash, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
            }
            else if (num == 58 || num == 76 || num == 75)
            {
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Ash, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 57)
            {
                WorldGen.TileMergeAttempt(-2, 1, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, 633, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.HellSpecial, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 59)
            {
                if ((double)j > Main.rockLayer)
                {
                    WorldGen.TileMergeAttempt(-2, 1, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                WorldGen.TileMergeAttempt(num, TileID.Sets.GrassSpecial, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.JungleSpecial, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                if ((double)j < Main.rockLayer)
                {
                    WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                else
                {
                    WorldGen.TileMergeAttempt(num, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6);
                }
            }
            else if (num == 211)
            {
                WorldGen.TileMergeAttempt(59, 60, ref num3, ref num8, ref num5, ref num6);
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 225 || num == 226)
            {
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 60)
            {
                WorldGen.TileMergeAttempt(59, 211, ref num3, ref num8, ref num5, ref num6);
            }
            else if (num == 189)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.MergesWithClouds, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 196)
            {
                WorldGen.TileMergeAttempt(-2, 189, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, 460, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 460)
            {
                WorldGen.TileMergeAttempt(-2, 189, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, 196, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 717)
            {
                WorldGen.TileMergeAttempt(-2, 189, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, 717, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 718)
            {
                WorldGen.TileMergeAttempt(-2, 189, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, 718, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 719)
            {
                WorldGen.TileMergeAttempt(-2, 189, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, 719, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 147)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, TileID.Sets.IcesSlush, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 161 || num == 163 || num == 164 || num == 200 || num == 224)
            {
                WorldGen.TileMergeAttempt(-2, 147, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 162)
            {
                WorldGen.TileMergeAttempt(-2, TileID.Sets.IcesSnow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 32)
            {
                if (num8 == 23)
                {
                    num8 = num;
                }
            }
            else if (num == 352)
            {
                if (num8 == 199)
                {
                    num8 = num;
                }
            }
            else if (num == 69)
            {
                if (num8 == 60)
                {
                    num8 = num;
                }
            }
            else if (num == 655)
            {
                if (num8 == 60)
                {
                    num8 = num;
                }
            }
            else if (num == 51)
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.AllTiles, Main.tileNoAttach, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 192)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 191, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 191)
            {
                WorldGen.TileMergeAttempt(-2, 192, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 384)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 383, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 383)
            {
                WorldGen.TileMergeAttempt(-2, 384, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 407)
            {
                WorldGen.TileMergeAttempt(-2, 404, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 404)
            {
                WorldGen.TileMergeAttempt(-2, 396, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 407, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 397)
            {
                WorldGen.TileMergeAttempt(-2, 53, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 396, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 396)
            {
                WorldGen.TileMergeAttempt(-2, 397, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(-2, 53, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 404, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 398)
            {
                WorldGen.TileMergeAttempt(-2, 112, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 400, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 400)
            {
                WorldGen.TileMergeAttempt(-2, 398, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(-2, 112, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 399)
            {
                WorldGen.TileMergeAttempt(-2, 234, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 401, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 401)
            {
                WorldGen.TileMergeAttempt(-2, 399, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(-2, 234, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 402)
            {
                WorldGen.TileMergeAttempt(-2, 116, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttemptFrametest(i, j, num, 403, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 403)
            {
                WorldGen.TileMergeAttempt(-2, 402, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(-2, 116, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (num == 0)
            {
                WorldGen.TileMergeAttempt(num, Main.tileMoss, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                WorldGen.TileMergeAttempt(num, TileID.Sets.tileMossBrick, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (Main.tileMoss[num] || TileID.Sets.tileMossBrick[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (Main.tileStone[num] || num == 1)
            {
                WorldGen.TileMergeAttempt(num, Main.tileMoss, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 38)
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.tileMossBrick, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (TileID.Sets.Conversion.Grass[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.Ore, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (TileID.Sets.Ore[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.Conversion.Grass, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (num == 53)
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 747, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 747)
            {
                WorldGen.TileMergeAttempt(-2, 53, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (TileID.Sets.Snow[num])
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 170, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 170)
            {
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Snow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (TileID.Sets.Snow[num])
            {
                WorldGen.TileMergeAttemptFrametest(i, j, num, 738, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (num == 738)
            {
                WorldGen.TileMergeAttempt(-2, TileID.Sets.Snow, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            if (num >= 0 && num < (int)TileID.Count && TileID.Sets.Mud[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.OreMergesWithMud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            else if (TileID.Sets.OreMergesWithMud[num])
            {
                WorldGen.TileMergeAttempt(num, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            bool flag7 = false;
            if (num == 2 || num == 23 || num == 661 || num == 662 || num == 60 || num == 477 || num == 492 || num == 70 || num == 109 || num == 199 || Main.tileMoss[num] || TileID.Sets.NeedsGrassFraming[num] || TileID.Sets.tileMossBrick[num])
            {
                flag7 = true;
                WorldGen.TileMergeAttemptWeird(num, -1, Main.tileSolid, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                int num20 = TileID.Sets.NeedsGrassFramingDirt[num];
                if (num == 60 || num == 70 || num == 661 || num == 662)
                {
                    num20 = 59;
                }
                else if (Main.tileMoss[num])
                {
                    num20 = 1;
                }
                else if (TileID.Sets.tileMossBrick[num])
                {
                    num20 = 38;
                }
                else if (num == 2 || num == 477)
                {
                    WorldGen.TileMergeAttempt(num20, 23, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                else if (num == 23)
                {
                    WorldGen.TileMergeAttempt(num20, 2, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                tileMergeCulling.Cull(ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                if (num3 != num && num3 != num20 && (num8 == num || num8 == num20))
                {
                    if (num5 == num20 && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 198;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 198;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 198;
                        }
                    }
                    else if (num5 == num && num6 == num20)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 198;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 198;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 198;
                        }
                    }
                }
                else if (num8 != num && num8 != num20 && (num3 == num || num3 == num20))
                {
                    if (num5 == num20 && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 216;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 216;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 216;
                        }
                    }
                    else if (num5 == num && num6 == num20)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 216;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 216;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 216;
                        }
                    }
                }
                else if (num5 != num && num5 != num20 && (num6 == num || num6 == num20))
                {
                    if (num3 == num20 && num8 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 72;
                            rectangle.Y = 144;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 162;
                        }
                        else
{
                            rectangle.X = 72;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num8 == num && num3 == num20)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 72;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 108;
                        }
                        else
{
                            rectangle.X = 72;
                            rectangle.Y = 126;
                        }
                    }
                }
                else if (num6 != num && num6 != num20 && (num5 == num || num5 == num20))
                {
                    if (num3 == num20 && num8 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 90;
                            rectangle.Y = 144;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 90;
                            rectangle.Y = 162;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num8 == num && num6 == num3)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 90;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 90;
                            rectangle.Y = 108;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 126;
                        }
                    }
                }
                else if (num3 == num && num8 == num && num5 == num && num6 == num)
                {
                    if (num2 != num && num4 != num && num7 != num && num9 != num)
                    {
                        if (num9 == num20)
{
                            if (num14 == 0)
{
                                rectangle.X = 108;
                                rectangle.Y = 324;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 126;
                                rectangle.Y = 324;
                            }
                            else
{
                                rectangle.X = 144;
                                rectangle.Y = 324;
                            }
                        }
                        else if (num4 == num20)
{
                            if (num14 == 0)
{
                                rectangle.X = 108;
                                rectangle.Y = 342;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 126;
                                rectangle.Y = 342;
                            }
                            else
{
                                rectangle.X = 144;
                                rectangle.Y = 342;
                            }
                        }
                        else if (num7 == num20)
{
                            if (num14 == 0)
{
                                rectangle.X = 108;
                                rectangle.Y = 360;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 126;
                                rectangle.Y = 360;
                            }
                            else
{
                                rectangle.X = 144;
                                rectangle.Y = 360;
                            }
                        }
                        else if (num2 == num20)
{
                            if (num14 == 0)
{
                                rectangle.X = 108;
                                rectangle.Y = 378;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 126;
                                rectangle.Y = 378;
                            }
                            else
{
                                rectangle.X = 144;
                                rectangle.Y = 378;
                            }
                        }
                        else if (num14 == 0)
{
                            rectangle.X = 144;
                            rectangle.Y = 234;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 198;
                            rectangle.Y = 234;
                        }
                        else
{
                            rectangle.X = 252;
                            rectangle.Y = 234;
                        }
                    }
                    else if (num2 != num && num9 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 306;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 306;
                        }
                        else
{
                            rectangle.X = 72;
                            rectangle.Y = 306;
                        }
                    }
                    else if (num4 != num && num7 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 90;
                            rectangle.Y = 306;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 108;
                            rectangle.Y = 306;
                        }
                        else
{
                            rectangle.X = 126;
                            rectangle.Y = 306;
                        }
                    }
                    else if (num2 != num && num4 == num && num7 == num && num9 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num2 == num && num4 != num && num7 == num && num9 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num2 == num && num4 == num && num7 != num && num9 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 162;
                        }
                    }
                    else if (num2 == num && num4 == num && num7 == num && num9 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 162;
                        }
                    }
                }
                else if (num3 == num && num8 == num20 && num5 == num && num6 == num && num2 == -1 && num4 == -1)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 18;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 126;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 144;
                        rectangle.Y = 18;
                    }
                }
                else if (num3 == num20 && num8 == num && num5 == num && num6 == num && num7 == -1 && num9 == -1)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 36;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 126;
                        rectangle.Y = 36;
                    }
                    else
                    {
                        rectangle.X = 144;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 == num && num8 == num && num5 == num20 && num6 == num && num4 == -1 && num9 == -1)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 198;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 == num && num8 == num && num5 == num && num6 == num20 && num2 == -1 && num7 == -1)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 180;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 180;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 180;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 == num && num8 == num20 && num5 == num && num6 == num)
                {
                    if (num4 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num2 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 180;
                        }
                    }
                }
                else if (num3 == num20 && num8 == num && num5 == num && num6 == num)
                {
                    if (num9 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 162;
                        }
                    }
                    else if (num7 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 162;
                        }
                    }
                }
                else if (num3 == num && num8 == num && num5 == num && num6 == num20)
                {
                    if (num2 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 162;
                        }
                    }
                    else if (num7 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 180;
                        }
                    }
                }
                else if (num3 == num && num8 == num && num5 == num20 && num6 == num)
                {
                    if (num4 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 162;
                        }
                    }
                    else if (num9 != -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 180;
                        }
                    }
                }
                else if ((num3 == num20 && num8 == num && num5 == num && num6 == num) || (num3 == num && num8 == num20 && num5 == num && num6 == num) || (num3 == num && num8 == num && num5 == num20 && num6 == num) || (num3 == num && num8 == num && num5 == num && num6 == num20))
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 18;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 54;
                        rectangle.Y = 18;
                    }
                }
                if ((num3 == num || num3 == num20) && (num8 == num || num8 == num20) && (num5 == num || num5 == num20) && (num6 == num || num6 == num20))
                {
                    if (num2 != num && num2 != num20 && (num4 == num || num4 == num20) && (num7 == num || num7 == num20) && (num9 == num || num9 == num20))
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num4 != num && num4 != num20 && (num2 == num || num2 == num20) && (num7 == num || num7 == num20) && (num9 == num || num9 == num20))
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 180;
                        }
                    }
                    else if (num7 != num && num7 != num20 && (num2 == num || num2 == num20) && (num4 == num || num4 == num20) && (num9 == num || num9 == num20))
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 162;
                        }
                    }
                    else if (num9 != num && num9 != num20 && (num2 == num || num2 == num20) && (num7 == num || num7 == num20) && (num4 == num || num4 == num20))
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 162;
                        }
                    }
                }
                if (num3 != num20 && num3 != num && num8 == num && num5 != num20 && num5 != num && num6 == num && num9 != num20 && num9 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 90;
                        rectangle.Y = 270;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 270;
                    }
                    else
                    {
                        rectangle.X = 126;
                        rectangle.Y = 270;
                    }
                }
                else if (num3 != num20 && num3 != num && num8 == num && num5 == num && num6 != num20 && num6 != num && num7 != num20 && num7 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 144;
                        rectangle.Y = 270;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 270;
                    }
                    else
                    {
                        rectangle.X = 180;
                        rectangle.Y = 270;
                    }
                }
                else if (num8 != num20 && num8 != num && num3 == num && num5 != num20 && num5 != num && num6 == num && num4 != num20 && num4 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 90;
                        rectangle.Y = 288;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 288;
                    }
                    else
                    {
                        rectangle.X = 126;
                        rectangle.Y = 288;
                    }
                }
                else if (num8 != num20 && num8 != num && num3 == num && num5 == num && num6 != num20 && num6 != num && num2 != num20 && num2 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 144;
                        rectangle.Y = 288;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 288;
                    }
                    else
                    {
                        rectangle.X = 180;
                        rectangle.Y = 288;
                    }
                }
                else if (num3 != num && num3 != num20 && num8 == num && num5 == num && num6 == num && num7 != num && num7 != num20 && num9 != num && num9 != num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 144;
                        rectangle.Y = 216;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 216;
                    }
                    else
                    {
                        rectangle.X = 252;
                        rectangle.Y = 216;
                    }
                }
                else if (num8 != num && num8 != num20 && num3 == num && num5 == num && num6 == num && num2 != num && num2 != num20 && num4 != num && num4 != num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 144;
                        rectangle.Y = 252;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 252;
                    }
                    else
                    {
                        rectangle.X = 252;
                        rectangle.Y = 252;
                    }
                }
                else if (num5 != num && num5 != num20 && num8 == num && num3 == num && num6 == num && num4 != num && num4 != num20 && num9 != num && num9 != num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 126;
                        rectangle.Y = 234;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 180;
                        rectangle.Y = 234;
                    }
                    else
                    {
                        rectangle.X = 234;
                        rectangle.Y = 234;
                    }
                }
                else if (num6 != num && num6 != num20 && num8 == num && num3 == num && num5 == num && num2 != num && num2 != num20 && num7 != num && num7 != num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 234;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 216;
                        rectangle.Y = 234;
                    }
                    else
                    {
                        rectangle.X = 270;
                        rectangle.Y = 234;
                    }
                }
                else if (num3 != num20 && num3 != num && (num8 == num20 || num8 == num) && num5 == num20 && num6 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 270;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 54;
                        rectangle.Y = 270;
                    }
                    else
                    {
                        rectangle.X = 72;
                        rectangle.Y = 270;
                    }
                }
                else if (num8 != num20 && num8 != num && (num3 == num20 || num3 == num) && num5 == num20 && num6 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 288;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 54;
                        rectangle.Y = 288;
                    }
                    else
                    {
                        rectangle.X = 72;
                        rectangle.Y = 288;
                    }
                }
                else if (num5 != num20 && num5 != num && (num6 == num20 || num6 == num) && num3 == num20 && num8 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 0;
                        rectangle.Y = 270;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 0;
                        rectangle.Y = 288;
                    }
                    else
                    {
                        rectangle.X = 0;
                        rectangle.Y = 306;
                    }
                }
                else if (num6 != num20 && num6 != num && (num5 == num20 || num5 == num) && num3 == num20 && num8 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 270;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 288;
                    }
                    else
                    {
                        rectangle.X = 18;
                        rectangle.Y = 306;
                    }
                }
                else if (num3 == num && num8 == num20 && num5 == num20 && num6 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 288;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 216;
                        rectangle.Y = 288;
                    }
                    else
                    {
                        rectangle.X = 234;
                        rectangle.Y = 288;
                    }
                }
                else if (num3 == num20 && num8 == num && num5 == num20 && num6 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 270;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 216;
                        rectangle.Y = 270;
                    }
                    else
                    {
                        rectangle.X = 234;
                        rectangle.Y = 270;
                    }
                }
                else if (num3 == num20 && num8 == num20 && num5 == num && num6 == num20)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 198;
                        rectangle.Y = 306;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 216;
                        rectangle.Y = 306;
                    }
                    else
                    {
                        rectangle.X = 234;
                        rectangle.Y = 306;
                    }
                }
                else if (num3 == num20 && num8 == num20 && num5 == num20 && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 144;
                        rectangle.Y = 306;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 306;
                    }
                    else
                    {
                        rectangle.X = 180;
                        rectangle.Y = 306;
                    }
                }
                if (num3 != num && num3 != num20 && num8 == num && num5 == num && num6 == num)
                {
                    if ((num7 == num20 || num7 == num) && num9 != num20 && num9 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 324;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 324;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 324;
                        }
                    }
                    else if ((num9 == num20 || num9 == num) && num7 != num20 && num7 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 324;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 324;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 324;
                        }
                    }
                }
                else if (num8 != num && num8 != num20 && num3 == num && num5 == num && num6 == num)
                {
                    if ((num2 == num20 || num2 == num) && num4 != num20 && num4 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 342;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 342;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 342;
                        }
                    }
                    else if ((num4 == num20 || num4 == num) && num2 != num20 && num2 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 342;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 342;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 342;
                        }
                    }
                }
                else if (num5 != num && num5 != num20 && num3 == num && num8 == num && num6 == num)
                {
                    if ((num4 == num20 || num4 == num) && num9 != num20 && num9 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 360;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 360;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 360;
                        }
                    }
                    else if ((num9 == num20 || num9 == num) && num4 != num20 && num4 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 360;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 360;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 360;
                        }
                    }
                }
                else if (num6 != num && num6 != num20 && num3 == num && num8 == num && num5 == num)
                {
                    if ((num2 == num20 || num2 == num) && num7 != num20 && num7 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 378;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 378;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 378;
                        }
                    }
                    else if ((num7 == num20 || num7 == num) && num2 != num20 && num2 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 378;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 378;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 378;
                        }
                    }
                }
                if ((num3 == num || num3 == num20) && (num8 == num || num8 == num20) && (num5 == num || num5 == num20) && (num6 == num || num6 == num20) && num2 != -1 && num4 != -1 && num7 != -1 && num9 != -1)
                {
                    if ((i + j) % 2 == 1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 108;
                            rectangle.Y = 198;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 126;
                            rectangle.Y = 198;
                        }
                        else
{
                            rectangle.X = 144;
                            rectangle.Y = 198;
                        }
                    }
                    else if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 18;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 54;
                        rectangle.Y = 18;
                    }
                }
                if (num20 >= 0 && num20 < (int)TileID.Count && TileID.Sets.Dirt[num20])
                {
                    WorldGen.TileMergeAttempt(-2, TileID.Sets.Dirt, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                else if (num20 >= 0 && num20 < (int)TileID.Count && TileID.Sets.Mud[num20])
                {
                    WorldGen.TileMergeAttempt(-2, TileID.Sets.Mud, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                else
                {
                    WorldGen.TileMergeAttempt(-2, num20, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                tileMergeCulling.Cull(ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            }
            WorldGen.TileMergeAttempt(num, Main.tileMerge[num], ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
            if (rectangle.X == -1 && rectangle.Y == -1 && (Main.tileMergeDirt[num] || (num > -1 && TileID.Sets.ChecksForMerge[num])))
            {
                if (!flag7)
                {
                    flag7 = true;
                    WorldGen.TileMergeAttemptWeird(num, -1, Main.tileSolid, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                if (num3 > -1 && num3 != num)
                {
                    num3 = -1;
                }
                if (num8 > -1 && num8 != num)
                {
                    num8 = -1;
                }
                if (num5 > -1 && num5 != num)
                {
                    num5 = -1;
                }
                if (num6 > -1 && num6 != num)
                {
                    num6 = -1;
                }
                tileMergeCulling.Cull(ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                if (num3 != -1 && num8 != -1 && num5 != -1 && num6 != -1)
                {
                    if (num3 == -2 && num8 == num && num5 == num && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 144;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 162;
                            rectangle.Y = 108;
                        }
                        else
{
                            rectangle.X = 180;
                            rectangle.Y = 108;
                        }
                        WorldGen.mergeUp = true;
                    }
                    else if (num3 == num && num8 == -2 && num5 == num && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 144;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 162;
                            rectangle.Y = 90;
                        }
                        else
{
                            rectangle.X = 180;
                            rectangle.Y = 90;
                        }
                        WorldGen.mergeDown = true;
                    }
                    else if (num3 == num && num8 == num && num5 == -2 && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 162;
                            rectangle.Y = 126;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 162;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 162;
                            rectangle.Y = 162;
                        }
                        WorldGen.mergeLeft = true;
                    }
                    else if (num3 == num && num8 == num && num5 == num && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 144;
                            rectangle.Y = 126;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 144;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 144;
                            rectangle.Y = 162;
                        }
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == -2 && num8 == num && num5 == -2 && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 162;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeLeft = true;
                    }
                    else if (num3 == -2 && num8 == num && num5 == num && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 126;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 162;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == num && num8 == -2 && num5 == -2 && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 36;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 36;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 180;
                        }
                        WorldGen.mergeDown = true;
                        WorldGen.mergeLeft = true;
                    }
                    else if (num3 == num && num8 == -2 && num5 == num && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 108;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 54;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 54;
                            rectangle.Y = 180;
                        }
                        WorldGen.mergeDown = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == num && num8 == num && num5 == -2 && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 180;
                            rectangle.Y = 126;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 180;
                            rectangle.Y = 144;
                        }
                        else
{
                            rectangle.X = 180;
                            rectangle.Y = 162;
                        }
                        WorldGen.mergeLeft = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == -2 && num8 == -2 && num5 == num && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 144;
                            rectangle.Y = 180;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 162;
                            rectangle.Y = 180;
                        }
                        else
{
                            rectangle.X = 180;
                            rectangle.Y = 180;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeDown = true;
                    }
                    else if (num3 == -2 && num8 == num && num5 == -2 && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 198;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 198;
                            rectangle.Y = 108;
                        }
                        else
{
                            rectangle.X = 198;
                            rectangle.Y = 126;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeLeft = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == num && num8 == -2 && num5 == -2 && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 198;
                            rectangle.Y = 144;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 198;
                            rectangle.Y = 162;
                        }
                        else
{
                            rectangle.X = 198;
                            rectangle.Y = 180;
                        }
                        WorldGen.mergeDown = true;
                        WorldGen.mergeLeft = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == -2 && num8 == -2 && num5 == num && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 216;
                            rectangle.Y = 144;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 216;
                            rectangle.Y = 162;
                        }
                        else
{
                            rectangle.X = 216;
                            rectangle.Y = 180;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeDown = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == -2 && num8 == -2 && num5 == -2 && num6 == num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 216;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 216;
                            rectangle.Y = 108;
                        }
                        else
{
                            rectangle.X = 216;
                            rectangle.Y = 126;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeDown = true;
                        WorldGen.mergeLeft = true;
                    }
                    else if (num3 == -2 && num8 == -2 && num5 == -2 && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 108;
                            rectangle.Y = 198;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 126;
                            rectangle.Y = 198;
                        }
                        else
{
                            rectangle.X = 144;
                            rectangle.Y = 198;
                        }
                        WorldGen.mergeUp = true;
                        WorldGen.mergeDown = true;
                        WorldGen.mergeLeft = true;
                        WorldGen.mergeRight = true;
                    }
                    else if (num3 == num && num8 == num && num5 == num && num6 == num)
                    {
                        if (num2 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 18;
                                rectangle.Y = 108;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 18;
                                rectangle.Y = 144;
                            }
                            else
{
                                rectangle.X = 18;
                                rectangle.Y = 180;
                            }
                        }
                        if (num4 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 0;
                                rectangle.Y = 108;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 0;
                                rectangle.Y = 144;
                            }
                            else
{
                                rectangle.X = 0;
                                rectangle.Y = 180;
                            }
                        }
                        if (num7 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 18;
                                rectangle.Y = 90;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 18;
                                rectangle.Y = 126;
                            }
                            else
{
                                rectangle.X = 18;
                                rectangle.Y = 162;
                            }
                        }
                        if (num9 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 0;
                                rectangle.Y = 90;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 0;
                                rectangle.Y = 126;
                            }
                            else
{
                                rectangle.X = 0;
                                rectangle.Y = 162;
                            }
                        }
                    }
                }
                else
                {
                    if (num != 2 && num != 23 && num != 60 && num != 70 && num != 109 && num != 199 && num != 477 && num != 492 && num != 633 && num != 661 && num != 662)
                    {
                        if (num3 == -1 && num8 == -2 && num5 == num && num6 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 234;
                                rectangle.Y = 0;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 252;
                                rectangle.Y = 0;
                            }
                            else
{
                                rectangle.X = 270;
                                rectangle.Y = 0;
                            }
                            WorldGen.mergeDown = true;
                        }
                        else if (num3 == -2 && num8 == -1 && num5 == num && num6 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 234;
                                rectangle.Y = 18;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 252;
                                rectangle.Y = 18;
                            }
                            else
{
                                rectangle.X = 270;
                                rectangle.Y = 18;
                            }
                            WorldGen.mergeUp = true;
                        }
                        else if (num3 == num && num8 == num && num5 == -1 && num6 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 234;
                                rectangle.Y = 36;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 252;
                                rectangle.Y = 36;
                            }
                            else
{
                                rectangle.X = 270;
                                rectangle.Y = 36;
                            }
                            WorldGen.mergeRight = true;
                        }
                        else if (num3 == num && num8 == num && num5 == -2 && num6 == -1)
{
                            if (num14 == 0)
{
                                rectangle.X = 234;
                                rectangle.Y = 54;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 252;
                                rectangle.Y = 54;
                            }
                            else
{
                                rectangle.X = 270;
                                rectangle.Y = 54;
                            }
                            WorldGen.mergeLeft = true;
                        }
                    }
                    if (num3 != -1 && num8 != -1 && num5 == -1 && num6 == num)
                    {
                        if (num3 == -2 && num8 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 72;
                                rectangle.Y = 144;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 72;
                                rectangle.Y = 162;
                            }
                            else
{
                                rectangle.X = 72;
                                rectangle.Y = 180;
                            }
                            WorldGen.mergeUp = true;
                        }
                        else if (num8 == -2 && num3 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 72;
                                rectangle.Y = 90;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 72;
                                rectangle.Y = 108;
                            }
                            else
{
                                rectangle.X = 72;
                                rectangle.Y = 126;
                            }
                            WorldGen.mergeDown = true;
                        }
                    }
                    else if (num3 != -1 && num8 != -1 && num5 == num && num6 == -1)
                    {
                        if (num3 == -2 && num8 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 90;
                                rectangle.Y = 144;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 90;
                                rectangle.Y = 162;
                            }
                            else
{
                                rectangle.X = 90;
                                rectangle.Y = 180;
                            }
                            WorldGen.mergeUp = true;
                        }
                        else if (num8 == -2 && num3 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 90;
                                rectangle.Y = 90;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 90;
                                rectangle.Y = 108;
                            }
                            else
{
                                rectangle.X = 90;
                                rectangle.Y = 126;
                            }
                            WorldGen.mergeDown = true;
                        }
                    }
                    else if (num3 == -1 && num8 == num && num5 != -1 && num6 != -1)
                    {
                        if (num5 == -2 && num6 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 0;
                                rectangle.Y = 198;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 18;
                                rectangle.Y = 198;
                            }
                            else
{
                                rectangle.X = 36;
                                rectangle.Y = 198;
                            }
                            WorldGen.mergeLeft = true;
                        }
                        else if (num6 == -2 && num5 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 54;
                                rectangle.Y = 198;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 72;
                                rectangle.Y = 198;
                            }
                            else
{
                                rectangle.X = 90;
                                rectangle.Y = 198;
                            }
                            WorldGen.mergeRight = true;
                        }
                    }
                    else if (num3 == num && num8 == -1 && num5 != -1 && num6 != -1)
                    {
                        if (num5 == -2 && num6 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 0;
                                rectangle.Y = 216;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 18;
                                rectangle.Y = 216;
                            }
                            else
{
                                rectangle.X = 36;
                                rectangle.Y = 216;
                            }
                            WorldGen.mergeLeft = true;
                        }
                        else if (num6 == -2 && num5 == num)
{
                            if (num14 == 0)
{
                                rectangle.X = 54;
                                rectangle.Y = 216;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 72;
                                rectangle.Y = 216;
                            }
                            else
{
                                rectangle.X = 90;
                                rectangle.Y = 216;
                            }
                            WorldGen.mergeRight = true;
                        }
                    }
                    else if (num3 != -1 && num8 != -1 && num5 == -1 && num6 == -1)
                    {
                        if (num3 == -2 && num8 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 108;
                                rectangle.Y = 216;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 108;
                                rectangle.Y = 234;
                            }
                            else
{
                                rectangle.X = 108;
                                rectangle.Y = 252;
                            }
                            WorldGen.mergeUp = true;
                            WorldGen.mergeDown = true;
                        }
                        else if (num3 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 126;
                                rectangle.Y = 144;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 126;
                                rectangle.Y = 162;
                            }
                            else
{
                                rectangle.X = 126;
                                rectangle.Y = 180;
                            }
                            WorldGen.mergeUp = true;
                        }
                        else if (num8 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 126;
                                rectangle.Y = 90;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 126;
                                rectangle.Y = 108;
                            }
                            else
{
                                rectangle.X = 126;
                                rectangle.Y = 126;
                            }
                            WorldGen.mergeDown = true;
                        }
                    }
                    else if (num3 == -1 && num8 == -1 && num5 != -1 && num6 != -1)
                    {
                        if (num5 == -2 && num6 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 162;
                                rectangle.Y = 198;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 180;
                                rectangle.Y = 198;
                            }
                            else
{
                                rectangle.X = 198;
                                rectangle.Y = 198;
                            }
                            WorldGen.mergeLeft = true;
                            WorldGen.mergeRight = true;
                        }
                        else if (num5 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 0;
                                rectangle.Y = 252;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 18;
                                rectangle.Y = 252;
                            }
                            else
{
                                rectangle.X = 36;
                                rectangle.Y = 252;
                            }
                            WorldGen.mergeLeft = true;
                        }
                        else if (num6 == -2)
{
                            if (num14 == 0)
{
                                rectangle.X = 54;
                                rectangle.Y = 252;
                            }
                            else if (num14 == 1)
{
                                rectangle.X = 72;
                                rectangle.Y = 252;
                            }
                            else
{
                                rectangle.X = 90;
                                rectangle.Y = 252;
                            }
                            WorldGen.mergeRight = true;
                        }
                    }
                    else if (num3 == -2 && num8 == -1 && num5 == -1 && num6 == -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 108;
                            rectangle.Y = 144;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 108;
                            rectangle.Y = 162;
                        }
                        else
{
                            rectangle.X = 108;
                            rectangle.Y = 180;
                        }
                        WorldGen.mergeUp = true;
                    }
                    else if (num3 == -1 && num8 == -2 && num5 == -1 && num6 == -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 108;
                            rectangle.Y = 90;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 108;
                            rectangle.Y = 108;
                        }
                        else
{
                            rectangle.X = 108;
                            rectangle.Y = 126;
                        }
                        WorldGen.mergeDown = true;
                    }
                    else if (num3 == -1 && num8 == -1 && num5 == -2 && num6 == -1)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 0;
                            rectangle.Y = 234;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 18;
                            rectangle.Y = 234;
                        }
                        else
{
                            rectangle.X = 36;
                            rectangle.Y = 234;
                        }
                        WorldGen.mergeLeft = true;
                    }
                    else if (num3 == -1 && num8 == -1 && num5 == -1 && num6 == -2)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 54;
                            rectangle.Y = 234;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 72;
                            rectangle.Y = 234;
                        }
                        else
{
                            rectangle.X = 90;
                            rectangle.Y = 234;
                        }
                        WorldGen.mergeRight = true;
                    }
                }
            }
            int num21 = tileCache.blockType();
            if (TileID.Sets.HasSlopeFrames[num])
            {
                if (num21 == 0)
                {
                    bool flag8 = num == num3 && tile != null && tile.topSlope();
                    bool flag9 = num == num5 && tile3 != null && tile3.leftSlope();
                    bool flag10 = num == num6 && tile4 != null && tile4.rightSlope();
                    bool flag11 = num == num8 && tile2 != null && tile2.bottomSlope();
                    int num22 = 0;
                    int num23 = 0;
                    if (flag8.ToInt() + flag9.ToInt() + flag10.ToInt() + flag11.ToInt() > 2)
                    {
                        int num24 = (tile != null && tile.slope() == 1).ToInt() + (tile4 != null && tile4.slope() == 1).ToInt() + (tile2 != null && tile2.slope() == 4).ToInt() + (tile3 != null && tile3.slope() == 4).ToInt();
                        int num25 = (tile != null && tile.slope() == 2).ToInt() + (tile4 != null && tile4.slope() == 3).ToInt() + (tile2 != null && tile2.slope() == 3).ToInt() + (tile3 != null && tile3.slope() == 2).ToInt();
                        if (num24 == num25)
{
                            num22 = 2;
                            num23 = 4;
                        }
                        else if (num24 > num25)
{
                            bool flag12 = num == num2 && tile7 != null && tile7.slope() == 0;
                            bool flag13 = num == num9 && tile6 != null && tile6.slope() == 0;
                            if (flag12 && flag13)
{
                                num23 = 4;
                            }
                            else if (flag13)
{
                                num22 = 6;
                            }
                            else
{
                                num22 = 7;
                                num23 = 1;
                            }
                        }
                        else
{
                            bool flag14 = num == num4 && tile8 != null && tile8.slope() == 0;
                            bool flag15 = num == num7 && tile5 != null && tile5.slope() == 0;
                            if (flag14 && flag15)
{
                                num23 = 4;
                                num22 = 1;
                            }
                            else if (flag15)
{
                                num22 = 7;
                            }
                            else
{
                                num22 = 6;
                                num23 = 1;
                            }
                        }
                        rectangle.X = (18 + num22) * 18;
                        rectangle.Y = num23 * 18;
                    }
                    else
                    {
                        if (flag8 && flag9 && num == num8 && num == num6)
{
                            num23 = 2;
                        }
                        else if (flag8 && flag10 && num == num8 && num == num5)
{
                            num22 = 1;
                            num23 = 2;
                        }
                        else if (flag10 && flag11 && num == num3 && num == num5)
{
                            num22 = 1;
                            num23 = 3;
                        }
                        else if (flag11 && flag9 && num == num3 && num == num6)
{
                            num23 = 3;
                        }
                        if (num22 != 0 || num23 != 0)
{
                            rectangle.X = (18 + num22) * 18;
                            rectangle.Y = num23 * 18;
                        }
                    }
                }
                if (num21 >= 2 && (rectangle.X < 0 || rectangle.Y < 0))
                {
                    int num26 = -1;
                    int num27 = -1;
                    int num28 = -1;
                    int num29 = 0;
                    int num30 = 0;
                    switch (num21)
                    {
                    case 2:
                        num26 = num5;
                        num27 = num8;
                        num28 = num7;
                        num29++;
                        break;
                    case 3:
                        num26 = num6;
                        num27 = num8;
                        num28 = num9;
                        break;
                    case 4:
                        num26 = num5;
                        num27 = num3;
                        num28 = num2;
                        num29++;
                        num30++;
                        break;
                    case 5:
                        num26 = num6;
                        num27 = num3;
                        num28 = num4;
                        num30++;
                        break;
                    }
                    if (num != num26 || num != num27 || num != num28)
                    {
                        if (num == num26 && num == num27)
{
                            num29 += 2;
                        }
                        else if (num == num26)
{
                            num29 += 4;
                        }
                        else if (num == num27)
{
                            num29 += 4;
                            num30 += 2;
                        }
                        else
{
                            num29 += 2;
                            num30 += 2;
                        }
                    }
                    rectangle.X = (18 + num29) * 18;
                    rectangle.Y = num30 * 18;
                }
            }
            if (rectangle.X < 0 || rectangle.Y < 0)
            {
                if (!flag7)
                {
                    WorldGen.TileMergeAttemptWeird(num, -1, Main.tileSolid, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                    tileMergeCulling.Cull(ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                if (num == 2 || num == 23 || num == 60 || num == 70 || num == 109 || num == 199 || num == 477 || num == 492 || num == 633 || num == 661 || num == 662 || Main.tileMoss[num] || TileID.Sets.tileMossBrick[num])
                {
                    WorldGen.TileMergeAttempt(num, -2, ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                    tileMergeCulling.Cull(ref num3, ref num8, ref num5, ref num6, ref num2, ref num4, ref num7, ref num9);
                }
                if (num3 == num && num8 == num && num5 == num && num6 == num)
                {
                    if (num2 != num && num4 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 108;
                            rectangle.Y = 18;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 126;
                            rectangle.Y = 18;
                        }
                        else
{
                            rectangle.X = 144;
                            rectangle.Y = 18;
                        }
                    }
                    else if (num7 != num && num9 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 108;
                            rectangle.Y = 36;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 126;
                            rectangle.Y = 36;
                        }
                        else
{
                            rectangle.X = 144;
                            rectangle.Y = 36;
                        }
                    }
                    else if (num2 != num && num7 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 180;
                            rectangle.Y = 0;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 180;
                            rectangle.Y = 18;
                        }
                        else
{
                            rectangle.X = 180;
                            rectangle.Y = 36;
                        }
                    }
                    else if (num4 != num && num9 != num)
                    {
                        if (num14 == 0)
{
                            rectangle.X = 198;
                            rectangle.Y = 0;
                        }
                        else if (num14 == 1)
{
                            rectangle.X = 198;
                            rectangle.Y = 18;
                        }
                        else
{
                            rectangle.X = 198;
                            rectangle.Y = 36;
                        }
                    }
                    else if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 18;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 54;
                        rectangle.Y = 18;
                    }
                }
                else if (num3 != num && num8 == num && num5 == num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 0;
                    }
                    else
                    {
                        rectangle.X = 54;
                        rectangle.Y = 0;
                    }
                }
                else if (num3 == num && num8 != num && num5 == num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 36;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 36;
                    }
                    else
                    {
                        rectangle.X = 54;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 == num && num8 == num && num5 != num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 0;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 0;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 0;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 == num && num8 == num && num5 == num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 72;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 72;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 72;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 != num && num8 == num && num5 != num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 0;
                        rectangle.Y = 54;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 54;
                    }
                    else
                    {
                        rectangle.X = 72;
                        rectangle.Y = 54;
                    }
                }
                else if (num3 != num && num8 == num && num5 == num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 54;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 54;
                        rectangle.Y = 54;
                    }
                    else
                    {
                        rectangle.X = 90;
                        rectangle.Y = 54;
                    }
                }
                else if (num3 == num && num8 != num && num5 != num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 0;
                        rectangle.Y = 72;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 36;
                        rectangle.Y = 72;
                    }
                    else
                    {
                        rectangle.X = 72;
                        rectangle.Y = 72;
                    }
                }
                else if (num3 == num && num8 != num && num5 == num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 18;
                        rectangle.Y = 72;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 54;
                        rectangle.Y = 72;
                    }
                    else
                    {
                        rectangle.X = 90;
                        rectangle.Y = 72;
                    }
                }
                else if (num3 == num && num8 == num && num5 != num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 90;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 90;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 90;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 != num && num8 != num && num5 == num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 72;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 126;
                        rectangle.Y = 72;
                    }
                    else
                    {
                        rectangle.X = 144;
                        rectangle.Y = 72;
                    }
                }
                else if (num3 != num && num8 == num && num5 != num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 126;
                        rectangle.Y = 0;
                    }
                    else
                    {
                        rectangle.X = 144;
                        rectangle.Y = 0;
                    }
                }
                else if (num3 == num && num8 != num && num5 != num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 108;
                        rectangle.Y = 54;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 126;
                        rectangle.Y = 54;
                    }
                    else
                    {
                        rectangle.X = 144;
                        rectangle.Y = 54;
                    }
                }
                else if (num3 != num && num8 != num && num5 != num && num6 == num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 162;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 != num && num8 != num && num5 == num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 216;
                        rectangle.Y = 0;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 216;
                        rectangle.Y = 18;
                    }
                    else
                    {
                        rectangle.X = 216;
                        rectangle.Y = 36;
                    }
                }
                else if (num3 != num && num8 != num && num5 != num && num6 != num)
                {
                    if (num14 == 0)
                    {
                        rectangle.X = 162;
                        rectangle.Y = 54;
                    }
                    else if (num14 == 1)
                    {
                        rectangle.X = 180;
                        rectangle.Y = 54;
                    }
                    else
                    {
                        rectangle.X = 198;
                        rectangle.Y = 54;
                    }
                }
            }
            if (rectangle.X <= -1 || rectangle.Y <= -1)
            {
                if (num14 <= 0)
                {
                    rectangle.X = 18;
                    rectangle.Y = 18;
                }
                else if (num14 == 1)
                {
                    rectangle.X = 36;
                    rectangle.Y = 18;
                }
                if (num14 >= 2)
                {
                    rectangle.X = 54;
                    rectangle.Y = 18;
                }
            }
            if (Main.tileLargeFrames[num] == 1 && num14 == 3)
            {
                rectangle.Y += 90;
            }
            if (Main.tileLargeFrames[num] == 2 && num14 == 3)
            {
                rectangle.Y += 90;
            }
            tileCache.frameX = (short)rectangle.X;
            tileCache.frameY = (short)rectangle.Y;
            if (rectangle.X != frameX && rectangle.Y != frameY && frameX >= 0 && frameY >= 0)
            {
                WorldGen.tileReframeCount++;
                if (WorldGen.tileReframeCount < 25)
                {
                    bool flag16 = WorldGen.mergeUp;
                    bool flag17 = WorldGen.mergeDown;
                    bool flag18 = WorldGen.mergeLeft;
                    bool flag19 = WorldGen.mergeRight;
                    WorldGen.TileFrameCosmetic(i - 1, j, tile3, false);
                    WorldGen.TileFrameCosmetic(i + 1, j, tile4, false);
                    WorldGen.TileFrameCosmetic(i, j - 1, tile, false);
                    WorldGen.TileFrameCosmetic(i, j + 1, tile2, false);
                    WorldGen.mergeUp = flag16;
                    WorldGen.mergeDown = flag17;
                    WorldGen.mergeLeft = flag18;
                    WorldGen.mergeRight = flag19;
                }
                WorldGen.tileReframeCount--;
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.AllTiles, Terraria.ID.TileID.Sets.Ash, Terraria.ID.TileID.Sets.BlockMergesWithMergeAllBlock, Terraria.Tile.blockType(), Terraria.Tile.bottomSlope(), Terraria.WorldGen.CactusFrame(), Terraria.ID.TileID.Sets.ChecksForMerge, Terraria.WorldGen.TileMergeCullCache.Cull(), Terraria.ID.TileID.Sets.Dirt, Terraria.ID.TileID.Sets.DontMergeWithSnow, Terraria.ID.TileID.Sets.ForcedDirtMerging, Terraria.Tile.frameNumber(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.GetTileMergeCulling(), Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.ID.TileID.Sets.GrassSpecial, Terraria.Tile.halfBrick(), Terraria.ID.TileID.Sets.HasSlopeFrames, Terraria.ID.TileID.Sets.HellSpecial, Terraria.ID.TileID.Sets.IcesSlush, Terraria.ID.TileID.Sets.IcesSnow, int, Terraria.WorldGen.IsRope(), Terraria.ID.TileID.Sets.JungleSpecial, Terraria.Tile.leftSlope(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.mergeDown, Terraria.WorldGen.mergeLeft, Terraria.WorldGen.mergeRight, Terraria.ID.TileID.Sets.MergesWithClouds, Terraria.ID.TileID.Sets.Conversion.MergesWithDirtInASpecialWay, Terraria.WorldGen.mergeUp, Terraria.ID.TileID.Sets.Mud, Terraria.ID.TileID.Sets.NeedsGrassFraming, Terraria.ID.TileID.Sets.NeedsGrassFramingDirt, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Ore, Terraria.ID.TileID.Sets.OreMergesWithMud, Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.rightSlope(), Terraria.Main.rockLayer, Terraria.Framing.SelfFrame8Way(), Terraria.Tile.slope(), Terraria.ID.TileID.Sets.Snow, Terraria.Main.tile, Terraria.Main.tileBlendAll, Terraria.Main.tileBrick, Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.Main.tileFrameImportant, Terraria.Main.tileLargeFrames, Terraria.Main.tileMerge, Terraria.WorldGen.TileMergeAttempt(), Terraria.WorldGen.TileMergeAttemptFrametest(), Terraria.WorldGen.TileMergeAttemptWeird(), Terraria.Main.tileMergeDirt, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.Main.tileNoAttach, Terraria.Main.tilePile, Terraria.WorldGen.tileReframeCount, Terraria.Main.tileRope, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileStone, Terraria.Tile.topSlope(), Terraria.Tile.type, Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.WorldGen.CactusFrame(), Terraria.WorldGen.Reframe(), Terraria.WorldGen.TileFrame(), and Terraria.WorldGen.TileFrameCosmetic().