Terraria Decompiled: Terraria.WorldGen.KillTile_PlaySounds
KillTile_PlaySounds()
static void Terraria.WorldGen.KillTile_PlaySounds (int i, int j, bool fail, Tile tileCache) inline static
Definition at line 65835 of file WorldGen.cs.
        {
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                return;
            }
            int type = (int)tileCache.type;
            if (type == 127 || type == 623)
            {
                SoundEngine.PlaySound(SoundID.Item27, i * 16, j * 16, 0f, 1f);
            }
            else if (type == 147 || type == 224)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    SoundEngine.PlaySound(SoundID.Item48, i * 16, j * 16, 0f, 1f);
                }
                else
                {
                    SoundEngine.PlaySound(SoundID.Item49, i * 16, j * 16, 0f, 1f);
                }
            }
            else if (type == 161 || type == 163 || type == 164 || type == 200 || type == 541 || type == 736)
            {
                SoundEngine.PlaySound(SoundID.Item50, i * 16, j * 16, 0f, 1f);
            }
            else if (type == 518 || type == 519 || type == 528 || type == 529 || type == 549 || type == 637 || type == 638 || type == 636)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 530 && tileCache.frameX < 270)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 705 && tileCache.frameX % 6 < 270)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 3 || type == 110)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 254)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 24)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (Main.tileAlch[type] || type == 384 || type == 227 || type == 32 || type == 51 || type == 697 || type == 52 || type == 61 || type == 703 || type == 62 || type == 69 || type == 655 || type == 71 || type == 73 || type == 74 || type == 113 || type == 115 || type == 184 || type == 192 || type == 205 || type == 233 || type == 352 || type == 382 || type == 624 || type == 656 || type == 700 || type == 701)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 485)
            {
                SoundEngine.PlaySound(4, i * 16, j * 16, 11, 1f, 0f);
            }
            else if (type == 201)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 481 || type == 482 || type == 483)
            {
                SoundEngine.PlaySound(SoundID.Item127, i * 16, j * 16, 0f, 1f);
            }
            else if (type == 1 || type == 6 || type == 7 || type == 8 || type == 9 || type == 22 || type == 140 || type == 25 || type == 37 || type == 38 || type == 39 || type == 41 || type == 43 || type == 44 || type == 45 || type == 46 || type == 47 || type == 48 || type == 56 || type == 58 || type == 63 || type == 64 || type == 65 || type == 66 || type == 67 || type == 68 || type == 75 || type == 76 || type == 107 || type == 108 || type == 111 || type == 117 || type == 118 || type == 119 || type == 120 || type == 121 || type == 122 || type == 150 || type == 151 || type == 152 || type == 153 || type == 154 || type == 155 || type == 156 || type == 160 || type == 161 || type == 166 || type == 167 || type == 168 || type == 169 || type == 175 || type == 176 || type == 177 || type == 203 || type == 202 || type == 204 || type == 206 || type == 211 || type == 221 || type == 222 || type == 223 || type == 226 || type == 248 || type == 249 || type == 250 || type == 272 || type == 273 || type == 274 || type == 478 || type == 284 || type == 325 || type == 346 || type == 347 || type == 348 || type == 350 || type == 367 || type == 357 || type == 368 || type == 369 || type == 370 || type == 407 || type == 472 || type == 473 || type == 500 || type == 501 || type == 502 || type == 503 || type == 546 || type == 557 || type == 566 || type == 618 || type == 408 || type == 409 || type == 669 || type == 670 || type == 671 || type == 672 || type == 673 || type == 674 || type == 675 || type == 676 || type == 677 || type == 678 || type == 679 || type == 680 || type == 681 || type == 682 || type == 683 || type == 684 || type == 685 || type == 686 || type == 687 || type == 689 || type == 688 || type == 690 || type == 691 || type == 692 || type == 726 || type == 749 || type == 747 || type == 743 || type == 735 || type == 737 || type == 745 || type == 750)
            {
                SoundEngine.PlaySound(21, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 666)
            {
                SoundEngine.PlaySound(SoundID.Item177, i * 16, j * 16, 0f, 1f);
            }
            else if (type == 739)
            {
                SoundEngine.PlaySound(SoundID.NPCHit25, i * 16, j * 16, 0f, 1f);
            }
            else if (type == 231 || type == 195 || type == 474)
            {
                SoundEngine.PlaySound(4, i * 16, j * 16, 1, 1f, 0f);
                if (type == 231)
                {
                    SoundEngine.PlaySound(SoundID.Item173, i * 16, j * 16, 0f, 1f);
                }
            }
            else if ((type == 26 || type == 695) && tileCache.frameX >= 54)
            {
                SoundEngine.PlaySound(4, i * 16, j * 16, 1, 1f, 0f);
            }
            else if (type == 314)
            {
                SoundEngine.PlaySound(SoundID.Item52, i * 16, j * 16, 0f, 1f);
            }
            else if (type >= 330 && type <= 333)
            {
                SoundEngine.PlaySound(18, i * 16, j * 16, 1, 1f, 0f);
            }
            else if ((type == 162 || type == 385 || type == 129 || (type == 165 && tileCache.frameX < 54)) && !fail)
            {
                SoundEngine.PlaySound(SoundID.Item27, i * 16, j * 16, 0f, 1f);
            }
            else if (type != 138)
            {
                SoundEngine.PlaySound(0, i * 16, j * 16, 1, 1f, 0f);
            }
            if (!fail)
            {
                ushort type2 = tileCache.type;
                if (type2 <= 345)
                {
                    if (type2 <= 54)
                    {
                        if (type2 != 13 && type2 != 54)
{
                            return;
                        }
                    }
                    else if (type2 - 326 > 3 && type2 != 345)
                    {
                        return;
                    }
                }
                else if (type2 <= 508)
                {
                    if (type2 - 458 > 1 && type2 - 507 > 1)
                    {
                        return;
                    }
                }
                else if (type2 != 708 && type2 != 748)
                {
                    return;
                }
                SoundEngine.PlaySound(13, i * 16, j * 16, 1, 1f, 0f);
            }
        }
References Terraria.Tile.frameX, Terraria.WorldGen.genRand, int, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.ID.SoundID.Item127, Terraria.ID.SoundID.Item173, Terraria.ID.SoundID.Item177, Terraria.ID.SoundID.Item27, Terraria.ID.SoundID.Item48, Terraria.ID.SoundID.Item49, Terraria.ID.SoundID.Item50, Terraria.ID.SoundID.Item52, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.SoundID.NPCHit25, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.tileAlch, and Terraria.Tile.type.
Referenced by Terraria.Projectile.AI_144_DD2Pet(), Terraria.WorldGen.KillTile(), Terraria.Player.PlaceThing_TryReplacingTiles(), and Terraria.WorldGen.ReplaceTile().