Terraria Decompiled: Terraria.WorldGen.CreateNewWorld
CreateNewWorld()
static Task Terraria.WorldGen.CreateNewWorld (GenerationProgress progress = null, WorldGenerator::Controller controller = null, WorldGen::WorldGenerationFinishCallback afterGeneration = null) inline static
Definition at line 2408 of file WorldGen.cs.
        {
            UIWorldSelect.NewlyGeneratedWorld = Main.ActiveWorldFileData;
            WorldGen.generatingWorld = true;
            Main.rand = new UnifiedRandom(Main.ActiveWorldFileData.Seed);
            WorldGen.isGeneratingOrLoadingWorld = true;
            Main.menuMode = 888;
            try
            {
                Main.MenuUI.SetState(new UIWorldLoad());
            }
            catch
            {
            }
            return Task.Factory.StartNew(delegate
            {
                WorldGen.worldGenCallback(progress, controller, afterGeneration);
            });
        }
References Terraria.Main.ActiveWorldFileData, System.Threading.Tasks.Task< TResult >.Factory, Terraria.Main.MenuUI, Terraria.IO.WorldFileData.Seed, Terraria.UI.UserInterface.SetState(), System.Threading.Tasks.TaskFactory< TResult >.StartNew(), and Terraria.WorldGen.worldGenCallback().
Referenced by Terraria.Main.DedServ(), Terraria.GameContent.UI.States.UIWorldCreation.FinishCreatingWorld(), Terraria.Testing.QuickLoad.RegenWorld.GenerateWorld(), and Terraria.Main.OnSeedSelected().