Terraria Decompiled: Terraria.WorldGen.DungeonDesertCleanup
DungeonDesertCleanup()
static void Terraria.WorldGen.DungeonDesertCleanup (int x) inline static private
Definition at line 32509 of file WorldGen.cs.
        {
            int i = (int)Main.worldSurface - 10 + GenVars.CurrentDungeonGenVars.preGenDungeonEntranceSettings.BuriedEntranceSandDugoutYOffset;
            i -= WorldGen.genRand.Next(25, 46);
            int num = 1;
            int num2 = 1;
            while (i > WorldGen.FindLowestCloud())
            {
                for (int j = x - num; j <= x + num2; j++)
                {
                    if (WorldGen.InWorld(j, i, 5))
                    {
                        Tile tile = Main.tile[j, i];
                        Tile tile2 = Main.tile[j, i + 1];
                        tile.active(false);
                        tile.wall = 0;
                        tile2.wall = 0;
                    }
                }
                i--;
                if (num < 20)
                {
                    num += WorldGen.genRand.Next(4, 5);
                }
                else if (num < 40)
                {
                    num += WorldGen.genRand.Next(2, 4);
                }
                else
                {
                    num += WorldGen.genRand.Next(1, 3);
                }
                if (num2 < 20)
                {
                    num2 += WorldGen.genRand.Next(4, 5);
                }
                else if (num2 < 40)
                {
                    num2 += WorldGen.genRand.Next(2, 4);
                }
                else
                {
                    num2 += WorldGen.genRand.Next(1, 3);
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.WorldGen.FindLowestCloud(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.preGenDungeonEntranceSettings, Terraria.Main.tile, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses().