Terraria Decompiled: Terraria.WorldGen.OreRunner
OreRunner()
static void Terraria.WorldGen.OreRunner (int i, int j, double strength, int steps, int tileType = -1, int wallType = -1, Rectangle? stayInArea = null, int onlyReplaceTileType = -1, int onlyReplaceWallType = -1) inline static
Definition at line 47265 of file WorldGen.cs.
        {
            double num = strength;
            double num2 = (double)steps;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            vector2D2.Y = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            while (num > 0.0 && num2 > 0.0)
            {
                if (vector2D.Y < 0.0 && num2 > 0.0 && tileType == 59)
                {
                    num2 = 0.0;
                }
                num = strength * (num2 / (double)steps);
                num2 -= 1.0;
                int num3 = (int)(vector2D.X - num * 0.5);
                int num4 = (int)(vector2D.X + num * 0.5);
                int num5 = (int)(vector2D.Y - num * 0.5);
                int num6 = (int)(vector2D.Y + num * 0.5);
                if (num3 < 0)
                {
                    num3 = 0;
                }
                if (num4 > Main.maxTilesX)
                {
                    num4 = Main.maxTilesX;
                }
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesY)
                {
                    num6 = Main.maxTilesY;
                }
                for (int k = num3; k < num4; k++)
                {
                    for (int l = num5; l < num6; l++)
                    {
                        if (Math.Abs((double)k - vector2D.X) + Math.Abs((double)l - vector2D.Y) < strength * 0.5 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015) && (stayInArea == null || stayInArea.Value.Contains(k, l)))
{
                            Tile tile = Main.tile[k, l];
                            if (tileType != -1 && tile.active())
{
                                if (onlyReplaceTileType != -1 && (int)tile.type != onlyReplaceTileType)
{
                                    goto IL_04A6;
                                }
                                if (tile.type == 0 || tile.type == 1 || tile.type == 23 || tile.type == 25 || tile.type == 40 || tile.type == 53 || tile.type == 57 || tile.type == 59 || tile.type == 60 || tile.type == 70 || tile.type == 109 || tile.type == 112 || tile.type == 116 || tile.type == 117 || tile.type == 147 || tile.type == 161 || tile.type == 163 || tile.type == 164 || Main.tileMoss[(int)tile.type] || tile.type == 199 || tile.type == 200 || tile.type == 203 || tile.type == 234 || tile.type == 396 || tile.type == 397 || tile.type == 401 || tile.type == 403 || tile.type == 400 || tile.type == 398 || tile.type == 399 || tile.type == 402 || (Main.notTheBeesWorld && tile.type == 230) || (tile.type == 225 && tile.wall != 108))
{
                                    Main.tile[k, l].type = (ushort)tileType;
                                    WorldGen.paintTile(k, l, 0, !WorldGen.generatingWorld && Main.netMode == 2, false);
                                    if (!WorldGen.generatingWorld)
{
                                        WorldGen.SquareTileFrame(k, l, true);
                                        if (Main.netMode == 2)
{
                                            NetMessage.SendTileSquare(-1, k, l, TileChangeType.None);
                                        }
                                    }
                                }
                            }
                            if (wallType != -1 && (onlyReplaceWallType == -1 || (int)tile.wall == onlyReplaceWallType))
{
                                Main.tile[k, l].wall = (ushort)wallType;
                                WorldGen.paintWall(k, l, 0, !WorldGen.generatingWorld && Main.netMode == 2, false);
                                if (!WorldGen.generatingWorld)
{
                                    WorldGen.SquareWallFrame(k, l, true);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, k, l, TileChangeType.None);
                                    }
                                }
                            }
                        }
                        IL_04A6:;
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.generatingWorld, Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.paintTile(), Terraria.WorldGen.paintWall(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tile, Terraria.Main.tileMoss, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.SmashAltar().