Terraria Decompiled: Terraria.WorldGen.HandleRopeEndFraming_Inner
HandleRopeEndFraming_Inner()
static void Terraria.WorldGen.HandleRopeEndFraming_Inner (int i, int j) inline static private
Definition at line 82022 of file WorldGen.cs.
        {
            if (WorldGen._preventInfiniteRopeFraming)
            {
                return;
            }
            WorldGen._preventInfiniteRopeFraming = true;
            if (!WorldGen.InWorld(i, j, 1))
            {
                return;
            }
            Tile tile = Main.tile[i, j - 1];
            Tile tile2 = Main.tile[i, j + 1];
            if (tile == null || tile2 == null)
            {
                return;
            }
            object obj = tile.active() && tile.type >= 0 && (tile2.type == 314 || TileID.Sets.Platforms[(int)tile.type] || tile.type == 380 || Main.tileRope[(int)tile.type]);
            bool flag = false;
            object obj2 = obj;
            if (obj2 == null)
            {
                flag = tile2.active() && tile2.type >= 0 && (tile2.type == 314 || TileID.Sets.Platforms[(int)tile2.type] || tile2.type == 380 || Main.tileRope[(int)tile2.type]);
            }
            if (obj2 == null && !flag)
            {
                return;
            }
            int num = -1;
            int num2 = -1;
            WorldGen.GetRopeEnds(i, j, out num, out num2, true, 5);
            if (num != -1 && num != j)
            {
                WorldGen.TileFrame(i, num, false, false);
            }
            if (num2 != -1 && num2 != j)
            {
                WorldGen.TileFrame(i, num2, false, false);
            }
        }
References Terraria.WorldGen._preventInfiniteRopeFraming, Terraria.Tile.active(), Terraria.WorldGen.GetRopeEnds(), int, Terraria.WorldGen.InWorld(), System.obj, Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Main.tileRope, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.HandleRopeEndFraming().