Terraria Decompiled: Terraria.WorldGen.Place3x1
Place3x1()
static void Terraria.WorldGen.Place3x1 (int x, int y, ushort type, int style = 0) inline static
Definition at line 50549 of file WorldGen.cs.
        {
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            bool flag = true;
            for (int i = x - 1; i < x + 2; i++)
            {
                if (Main.tile[i, y] == null)
                {
                    Main.tile[i, y] = new Tile();
                }
                if (Main.tile[i, y].active())
                {
                    flag = false;
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (!WorldGen.SolidTile2(i, y + 1))
                {
                    flag = false;
                }
            }
            if (flag)
            {
                short num = (short)(54 * style);
                Main.tile[x - 1, y].active(true);
                Main.tile[x - 1, y].frameY = 0;
                Main.tile[x - 1, y].frameX = num;
                Main.tile[x - 1, y].type = type;
                Main.tile[x, y].active(true);
                Main.tile[x, y].frameY = 0;
                Main.tile[x, y].frameX = num + 18;
                Main.tile[x, y].type = type;
                Main.tile[x + 1, y].active(true);
                Main.tile[x + 1, y].frameY = 0;
                Main.tile[x + 1, y].frameX = num + 36;
                Main.tile[x + 1, y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().