Terraria Decompiled: Terraria.WorldGen.GrowEpicTree
GrowEpicTree()
static bool Terraria.WorldGen.GrowEpicTree (int i, int y) inline static
Definition at line 24316 of file WorldGen.cs.
        {
            int num = y;
            while (Main.tile[i, num].active() && Main.tile[i, num].type == 20)
            {
                num++;
            }
            if (Main.tile[i, num].active() && !Main.tile[i, num].halfBrick() && Main.tile[i, num].slope() == 0 && Main.tile[i, num].type == 2 && Main.tile[i, num - 1].wall == 0 && Main.tile[i, num - 1].liquid == 0 && ((Main.tile[i - 1, num].active() && (Main.tile[i - 1, num].type == 2 || Main.tile[i - 1, num].type == 23 || Main.tile[i - 1, num].type == 60 || Main.tile[i - 1, num].type == 109)) || (Main.tile[i + 1, num].active() && (Main.tile[i + 1, num].type == 2 || Main.tile[i + 1, num].type == 23 || Main.tile[i + 1, num].type == 60 || Main.tile[i + 1, num].type == 109))))
            {
                int num2 = 2;
                if (WorldGen.EmptyTileCheck(i - num2, i + num2, num - 55, num - 1, 20))
                {
                    bool flag = false;
                    bool flag2 = false;
                    int num3 = WorldGen.genRand.Next(20, 30);
                    if (WorldGen.drunkWorldGen)
                    {
                        num3 = WorldGen.genRand.Next(3, 7);
                    }
                    int num4;
                    for (int j = num - num3; j < num; j++)
                    {
                        Main.tile[i, j].active(true);
                        Main.tile[i, j].type = 5;
                        num4 = WorldGen.genRand.Next(3);
                        int num5 = WorldGen.genRand.Next(10);
                        if (j == num - 1 || j == num - num3)
{
                            num5 = 0;
                        }
                        while (((num5 == 5 || num5 == 7) && flag) || ((num5 == 6 || num5 == 7) && flag2))
{
                            num5 = WorldGen.genRand.Next(10);
                        }
                        flag = false;
                        flag2 = false;
                        if (num5 == 5 || num5 == 7)
{
                            flag = true;
                        }
                        if (num5 == 6 || num5 == 7)
{
                            flag2 = true;
                        }
                        if (num5 == 1)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 2)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 44;
                            }
                        }
                        else if (num5 == 3)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 44;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 44;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 44;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 4)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 5)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 88;
                                Main.tile[i, j].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 88;
                                Main.tile[i, j].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 88;
                                Main.tile[i, j].frameY = 44;
                            }
                        }
                        else if (num5 == 6)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 66;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 66;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 66;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 7)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 110;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 110;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 110;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 44;
                            }
                        }
                        if (num5 == 5 || num5 == 7)
{
                            Main.tile[i - 1, j].active(true);
                            Main.tile[i - 1, j].type = 5;
                            num4 = WorldGen.genRand.Next(3);
                            if (WorldGen.genRand.Next(3) < 2)
{
                                if (num4 == 0)
{
                                    Main.tile[i - 1, j].frameX = 44;
                                    Main.tile[i - 1, j].frameY = 198;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i - 1, j].frameX = 44;
                                    Main.tile[i - 1, j].frameY = 220;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i - 1, j].frameX = 44;
                                    Main.tile[i - 1, j].frameY = 242;
                                }
                            }
                            else
{
                                if (num4 == 0)
{
                                    Main.tile[i - 1, j].frameX = 66;
                                    Main.tile[i - 1, j].frameY = 0;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i - 1, j].frameX = 66;
                                    Main.tile[i - 1, j].frameY = 22;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i - 1, j].frameX = 66;
                                    Main.tile[i - 1, j].frameY = 44;
                                }
                            }
                        }
                        if (num5 == 6 || num5 == 7)
{
                            Main.tile[i + 1, j].active(true);
                            Main.tile[i + 1, j].type = 5;
                            num4 = WorldGen.genRand.Next(3);
                            if (WorldGen.genRand.Next(3) < 2)
{
                                if (num4 == 0)
{
                                    Main.tile[i + 1, j].frameX = 66;
                                    Main.tile[i + 1, j].frameY = 198;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i + 1, j].frameX = 66;
                                    Main.tile[i + 1, j].frameY = 220;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i + 1, j].frameX = 66;
                                    Main.tile[i + 1, j].frameY = 242;
                                }
                            }
                            else
{
                                if (num4 == 0)
{
                                    Main.tile[i + 1, j].frameX = 88;
                                    Main.tile[i + 1, j].frameY = 66;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i + 1, j].frameX = 88;
                                    Main.tile[i + 1, j].frameY = 88;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i + 1, j].frameX = 88;
                                    Main.tile[i + 1, j].frameY = 110;
                                }
                            }
                        }
                    }
                    int num6 = WorldGen.genRand.Next(3);
                    bool flag3 = false;
                    bool flag4 = false;
                    if (Main.tile[i - 1, num].active() && !Main.tile[i - 1, num].halfBrick() && Main.tile[i - 1, num].slope() == 0 && (Main.tile[i - 1, num].type == 2 || Main.tile[i - 1, num].type == 23 || Main.tile[i - 1, num].type == 60 || Main.tile[i - 1, num].type == 109))
                    {
                        flag3 = true;
                    }
                    if (Main.tile[i + 1, num].active() && !Main.tile[i + 1, num].halfBrick() && Main.tile[i + 1, num].slope() == 0 && (Main.tile[i + 1, num].type == 2 || Main.tile[i + 1, num].type == 23 || Main.tile[i + 1, num].type == 60 || Main.tile[i + 1, num].type == 109))
                    {
                        flag4 = true;
                    }
                    if (!flag3)
                    {
                        if (num6 == 0)
{
                            num6 = 2;
                        }
                        if (num6 == 1)
{
                            num6 = 3;
                        }
                    }
                    if (!flag4)
                    {
                        if (num6 == 0)
{
                            num6 = 1;
                        }
                        if (num6 == 2)
{
                            num6 = 3;
                        }
                    }
                    if (flag3 && !flag4)
                    {
                        num6 = 2;
                    }
                    if (flag4 && !flag3)
                    {
                        num6 = 1;
                    }
                    if (num6 == 0 || num6 == 1)
                    {
                        Main.tile[i + 1, num - 1].active(true);
                        Main.tile[i + 1, num - 1].type = 5;
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i + 1, num - 1].frameX = 22;
                            Main.tile[i + 1, num - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i + 1, num - 1].frameX = 22;
                            Main.tile[i + 1, num - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i + 1, num - 1].frameX = 22;
                            Main.tile[i + 1, num - 1].frameY = 176;
                        }
                    }
                    if (num6 == 0 || num6 == 2)
                    {
                        Main.tile[i - 1, num - 1].active(true);
                        Main.tile[i - 1, num - 1].type = 5;
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i - 1, num - 1].frameX = 44;
                            Main.tile[i - 1, num - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i - 1, num - 1].frameX = 44;
                            Main.tile[i - 1, num - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i - 1, num - 1].frameX = 44;
                            Main.tile[i - 1, num - 1].frameY = 176;
                        }
                    }
                    num4 = WorldGen.genRand.Next(3);
                    if (num6 == 0)
                    {
                        if (num4 == 0)
{
                            Main.tile[i, num - 1].frameX = 88;
                            Main.tile[i, num - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, num - 1].frameX = 88;
                            Main.tile[i, num - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, num - 1].frameX = 88;
                            Main.tile[i, num - 1].frameY = 176;
                        }
                    }
                    else if (num6 == 1)
                    {
                        if (num4 == 0)
{
                            Main.tile[i, num - 1].frameX = 0;
                            Main.tile[i, num - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, num - 1].frameX = 0;
                            Main.tile[i, num - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, num - 1].frameX = 0;
                            Main.tile[i, num - 1].frameY = 176;
                        }
                    }
                    else if (num6 == 2)
                    {
                        if (num4 == 0)
{
                            Main.tile[i, num - 1].frameX = 66;
                            Main.tile[i, num - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, num - 1].frameX = 66;
                            Main.tile[i, num - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, num - 1].frameX = 66;
                            Main.tile[i, num - 1].frameY = 176;
                        }
                    }
                    if (WorldGen.genRand.Next(13) != 0)
                    {
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i, num - num3].frameX = 22;
                            Main.tile[i, num - num3].frameY = 198;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, num - num3].frameX = 22;
                            Main.tile[i, num - num3].frameY = 220;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, num - num3].frameX = 22;
                            Main.tile[i, num - num3].frameY = 242;
                        }
                    }
                    else
                    {
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i, num - num3].frameX = 0;
                            Main.tile[i, num - num3].frameY = 198;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, num - num3].frameX = 0;
                            Main.tile[i, num - num3].frameY = 220;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, num - num3].frameX = 0;
                            Main.tile[i, num - num3].frameY = 242;
                        }
                    }
                    WorldGen.RangeFrame(i - 2, num - num3 - 1, i + 2, num + 1);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, (int)((double)num - (double)num3 * 0.5), num3 + 1, TileChangeType.None);
                    }
                    return true;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.EmptyTileCheck(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.