Terraria Decompiled: Terraria.WorldGen.PaintTheTemple
PaintTheTemple()
static void Terraria.WorldGen.PaintTheTemple (byte tilePaintColor, byte wallPaintColor) inline static private
Definition at line 21678 of file WorldGen.cs.
        {
            for (int i = 10; i < Main.maxTilesX - 10; i++)
            {
                for (int j = 10; j < Main.maxTilesY - 10; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active())
                    {
                        bool flag = false;
                        if (tile.type == 226)
{
                            flag = true;
                        }
                        if (tile.type == 61 && Main.tile[i, j + 1].type == 226)
{
                            flag = true;
                        }
                        if (tile.type == 137)
{
                            int num = (int)(tile.frameY / 18);
                            if (num >= 1 && num <= 4)
{
                                flag = true;
                            }
                        }
                        if (flag)
{
                            if (WorldGen.notTheBees)
{
                                Main.tile[i, j].color(0);
                            }
                            else
{
                                tile.color(tilePaintColor);
                            }
                        }
                    }
                    if (tile.wall == 87)
                    {
                        tile.wallColor(wallPaintColor);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Tile.frameY, int, Terraria.WorldGen.notTheBees, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.WorldGen.FinishTenthAnniversaryWorld().