Terraria Decompiled: Terraria.WorldGen.UpdateStalagtiteStyle
UpdateStalagtiteStyle()
static bool Terraria.WorldGen.UpdateStalagtiteStyle (int x, int j) inline static
Definition at line 36115 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return true;
            }
            if (Main.tile[x, j] == null)
            {
                return true;
            }
            int num;
            bool flag;
            WorldGen.GetStalagtiteStyle(x, j, out num, out flag);
            if (flag)
            {
                return false;
            }
            bool flag2;
            int num2;
            int num3;
            int num4;
            WorldGen.GetDesiredStalagtiteStyle(x, j, out flag2, out num2, out num3, out num4);
            if (flag2)
            {
                return false;
            }
            if (num != num2)
            {
                int num5 = WorldGen.genRand.Next(3) * 18;
                if (num2 == 0)
                {
                    num5 += 54;
                }
                else if (num2 == 1)
                {
                    num5 += 216;
                }
                else if (num2 == 2)
                {
                    num5 += 270;
                }
                else if (num2 == 3)
                {
                    num5 += 324;
                }
                else if (num2 == 4)
                {
                    num5 += 378;
                }
                else if (num2 == 5)
                {
                    num5 += 432;
                }
                else if (num2 == 6)
                {
                    num5 += 486;
                }
                else if (num2 == 7)
                {
                    num5 = num5;
                }
                else if (num2 == 8)
                {
                    num5 += 540;
                }
                else if (num2 == 9)
                {
                    num5 += 594;
                }
                else if (num2 == 10)
                {
                    num5 += 648;
                }
                else if (num2 == 11)
                {
                    num5 += 108;
                }
                else if (num2 == 12)
                {
                    num5 += 162;
                }
                for (int i = num4; i < num4 + num3; i++)
                {
                    Main.tile[x, i].frameX = (short)num5;
                }
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x, num4, 1, 2, TileChangeType.None);
                }
            }
            return true;
        }
References Terraria.Tile.frameX, Terraria.WorldGen.genRand, Terraria.WorldGen.GetDesiredStalagtiteStyle(), Terraria.WorldGen.GetStalagtiteStyle(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NetMessage.SendTileSquare(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.CheckStalactite().