Terraria Decompiled: Terraria.WorldGen.Reset
Reset()
static void Terraria.WorldGen.Reset () inline static
Definition at line 7129 of file WorldGen.cs.
        {
            WorldGen.Manifest.Version = Main.versionNumber;
            WorldGen.Manifest.GitSHA = GitStatus.GitSHA;
            WorldGen.tileSolidBackup = (bool[])Main.tileSolid.Clone();
            int seed = Main.ActiveWorldFileData.Seed;
            Main.drunkWorld = (WorldGen.drunkWorldGen = WorldGenerationOptions.Get<WorldSeedOption_Drunk>().Enabled);
            Main.notTheBeesWorld = (WorldGen.notTheBees = WorldGenerationOptions.Get<WorldSeedOption_NotTheBees>().Enabled);
            Main.noTrapsWorld = (WorldGen.noTrapsWorldGen = WorldGenerationOptions.Get<WorldSeedOption_NoTraps>().Enabled);
            Main.getGoodWorld = (WorldGen.getGoodWorldGen = WorldGenerationOptions.Get<WorldSeedOption_ForTheWorthy>().Enabled);
            Main.tenthAnniversaryWorld = (WorldGen.tenthAnniversaryWorldGen = WorldGenerationOptions.Get<WorldSeedOption_Anniversary>().Enabled);
            Main.dontStarveWorld = (WorldGen.dontStarveWorldGen = WorldGenerationOptions.Get<WorldSeedOption_DontStarve>().Enabled);
            Main.remixWorld = (WorldGen.remixWorldGen = WorldGenerationOptions.Get<WorldSeedOption_Remix>().Enabled);
            Main.zenithWorld = (WorldGen.everythingWorldGen = WorldGenerationOptions.Get<WorldSeedOption_Everything>().Enabled);
            Main.skyblockWorld = (WorldGen.skyblockWorldGen = WorldGenerationOptions.Get<WorldSeedOption_Skyblock>().Enabled);
            WorldGen.SecretSeed.InitializeSecretSeeds();
            GenVars.notTheBeesAndForTheWorthyNoCelebration = Main.notTheBeesWorld && Main.getGoodWorld && !Main.tenthAnniversaryWorld;
            GenVars.noTrapsAndForTheWorthyNoCelebration = Main.noTrapsWorld && Main.getGoodWorld && !Main.tenthAnniversaryWorld;
            GenVars.flipInfections = Main.drunkWorld && Main.getGoodWorld && !Main.remixWorld;
            Main.afterPartyOfDoom = false;
            if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.skyblockWorldGen)
            {
                BirthdayParty.GenuineParty = true;
                BirthdayParty.PartyDaysOnCooldown = 5;
                if (WorldGen.getGoodWorldGen)
                {
                    Main.afterPartyOfDoom = true;
                }
            }
            WorldGen.drunkWorldGenText = WorldGen.drunkWorldGen;
            if (WorldGen.drunkWorldGen && !Main.dayTime)
            {
                Main.time = 0.0;
            }
            Main.lockMenuBGChange = true;
            Main.rand = new UnifiedRandom(seed);
            GenVars.structures = new StructureMap();
            ExtraSpawnPointManager.ResetExtraSpawns();
            GenVars.desertHiveHigh = Main.maxTilesY;
            GenVars.desertHiveLow = 0;
            GenVars.desertHiveLeft = Main.maxTilesX;
            GenVars.desertHiveRight = 0;
            GenVars.worldSurfaceLow = 0.0;
            GenVars.worldSurface = 0.0;
            GenVars.worldSurfaceHigh = 0.0;
            GenVars.rockLayerLow = 0.0;
            GenVars.rockLayer = 0.0;
            GenVars.rockLayerHigh = 0.0;
            GenVars.remixMushroomLayerLow = 0;
            GenVars.remixMushroomLayerHigh = 0;
            GenVars.remixSurfaceLayerLow = 0;
            GenVars.remixSurfaceLayerHigh = 0;
            GenVars.copper = 7;
            GenVars.iron = 6;
            GenVars.silver = 9;
            GenVars.gold = 8;
            GenVars.dungeonGenVars.Clear();
            GenVars.CurrentDungeon = 0;
            GenVars.jungleHut = (ushort)WorldGen.genRand.Next(5);
            GenVars.shellStartXLeft = 0;
            GenVars.shellStartYLeft = 0;
            GenVars.shellStartXRight = 0;
            GenVars.shellStartYRight = 0;
            GenVars.PyrX = null;
            GenVars.PyrY = null;
            GenVars.numPyr = 0;
            GenVars.lowestCloud = -1;
            GenVars.jungleMinX = -1;
            GenVars.jungleMaxX = -1;
            GenVars.snowMinX = new int[Main.maxTilesY];
            GenVars.snowMaxX = new int[Main.maxTilesY];
            GenVars.snowTop = 0;
            GenVars.snowBottom = 0;
            GenVars.skyLakes = 1;
            if (Main.maxTilesX > 8000)
            {
                GenVars.skyLakes++;
            }
            if (Main.maxTilesX > 6000)
            {
                GenVars.skyLakes++;
            }
            GenVars.beachBordersWidth = 275;
            GenVars.beachSandRandomCenter = GenVars.beachBordersWidth + 5 + 40;
            GenVars.beachSandRandomWidthRange = 20;
            GenVars.beachSandDungeonExtraWidth = 40;
            GenVars.beachSandJungleExtraWidth = 20;
            GenVars.oceanWaterStartRandomMin = 220;
            GenVars.oceanWaterStartRandomMax = GenVars.oceanWaterStartRandomMin + 40;
            GenVars.oceanWaterForcedJungleLength = 275;
            GenVars.leftBeachEnd = 0;
            GenVars.rightBeachStart = 0;
            GenVars.evilBiomeBeachAvoidance = GenVars.beachSandRandomCenter + 60;
            GenVars.evilBiomeAvoidanceMidFixer = 50;
            GenVars.lakesBeachAvoidance = GenVars.beachSandRandomCenter + 20;
            GenVars.smallHolesBeachAvoidance = GenVars.beachSandRandomCenter + 20;
            GenVars.surfaceCavesBeachAvoidance = GenVars.beachSandRandomCenter + 20;
            GenVars.surfaceCavesBeachAvoidance2 = GenVars.beachSandRandomCenter + 20;
            GenVars.jungleOriginX = 0;
            GenVars.snowOriginLeft = 0;
            GenVars.snowOriginRight = 0;
            GenVars.logX = -1;
            GenVars.logY = -1;
            if (WorldGen.everythingWorldGen)
            {
                Main.starGame = true;
            }
            if (WorldGen.genRand.Next(2) == 0)
            {
                GenVars.crimsonLeft = false;
            }
            else
            {
                GenVars.crimsonLeft = true;
            }
            GenVars.numOceanCaveTreasure = 0;
            GenVars.skipDesertTileCheck = false;
            WorldGen.growGrassUnderground = false;
            Liquid.ReInit();
            WorldGen.SetupStatueList();
            WorldGen.RandomizeWeather();
            Main.cloudAlpha = 0f;
            Main.maxRaining = 0f;
            Main.raining = false;
            if (WorldGen.SecretSeed.rainsForAYear.Enabled)
            {
                WorldGen.SecretSeed.DoRainsForAYear();
            }
            WorldGen.heartCount = 0;
            GenVars.extraBastStatueCount = 0;
            GenVars.extraBastStatueCountMax = 2;
            Main.checkXMas();
            Main.checkHalloween();
            WorldGen.ResetGenerator();
            GenVars.UndergroundDesertLocation = Rectangle.Empty;
            GenVars.UndergroundDesertHiveLocation = Rectangle.Empty;
            GenVars.numLarva = 0;
            List<int> list = new List<int> { 274, 220, 112, 218, 3019 };
            if (WorldGen.remixWorldGen)
            {
                list = new List<int> { 274, 220, 683, 218, 3019 };
            }
            List<int> list2 = new List<int>();
            while (list.Count > 0)
            {
                int num = WorldGen.genRand.Next(list.Count);
                int num2 = list[num];
                list2.Add(num2);
                list.RemoveAt(num);
            }
            GenVars.hellChestItem = list2.ToArray();
            int num3 = 86400;
            Main.slimeRainTime = (double)(-(double)WorldGen.genRand.Next(num3 * 2, num3 * 3));
            if (WorldGen.skyblockWorldGen)
            {
                Main.slimeRainTime = 0.0;
            }
            Main.cloudBGActive = (float)(-(float)WorldGen.genRand.Next(8640, 86400));
            WorldGen.SavedOreTiers.Copper = 7;
            WorldGen.SavedOreTiers.Iron = 6;
            WorldGen.SavedOreTiers.Silver = 9;
            WorldGen.SavedOreTiers.Gold = 8;
            GenVars.copperBar = 20;
            GenVars.ironBar = 22;
            GenVars.silverBar = 21;
            GenVars.goldBar = 19;
            if (WorldGen.genRand.Next(2) == 0)
            {
                GenVars.copper = 166;
                GenVars.copperBar = 703;
                WorldGen.SavedOreTiers.Copper = 166;
            }
            if ((!WorldGen.dontStarveWorldGen || WorldGen.drunkWorldGen) && WorldGen.genRand.Next(2) == 0)
            {
                GenVars.iron = 167;
                GenVars.ironBar = 704;
                WorldGen.SavedOreTiers.Iron = 167;
            }
            if (WorldGen.genRand.Next(2) == 0)
            {
                GenVars.silver = 168;
                GenVars.silverBar = 705;
                WorldGen.SavedOreTiers.Silver = 168;
            }
            if ((!WorldGen.dontStarveWorldGen || WorldGen.drunkWorldGen) && WorldGen.genRand.Next(2) == 0)
            {
                GenVars.gold = 169;
                GenVars.goldBar = 706;
                WorldGen.SavedOreTiers.Gold = 169;
            }
            if (GenVars.flipInfections)
            {
                GenVars.crimStoneWall = 3;
                GenVars.crimStone = 25;
                GenVars.ebonStoneWall = 83;
                GenVars.ebonStone = 203;
            }
            WorldGen.crimson = WorldGen.genRand.Next(2) == 0;
            WorldGen.generatingRandomEvil = true;
            if (WorldGen.WorldGenParam_Evil == 0)
            {
                WorldGen.generatingRandomEvil = false;
                WorldGen.crimson = false;
            }
            if (WorldGen.WorldGenParam_Evil == 1)
            {
                WorldGen.generatingRandomEvil = false;
                WorldGen.crimson = true;
            }
            if (GenVars.jungleHut == 0)
            {
                GenVars.jungleHut = 119;
            }
            else if (GenVars.jungleHut == 1)
            {
                GenVars.jungleHut = 120;
            }
            else if (GenVars.jungleHut == 2)
            {
                GenVars.jungleHut = 158;
            }
            else if (GenVars.jungleHut == 3)
            {
                GenVars.jungleHut = 175;
            }
            else if (GenVars.jungleHut == 4)
            {
                GenVars.jungleHut = 45;
            }
            Main.ActiveWorldFileData.WorldId = WorldGen.genRand.Next(int.MaxValue);
            WorldGen.RandomizeTreeStyle();
            WorldGen.RandomizeCaveBackgrounds();
            WorldGen.RandomizeBackgrounds(WorldGen.genRand);
            WorldGen.RandomizeMoonState(WorldGen.genRand, false);
            WorldGen.TreeTops.CopyExistingWorldInfoForWorldGeneration();
            WorldGen.GenerateWorld_SetupDungeonGenVars(0, true);
            int num4 = (GenVars.CurrentDungeonGenVars.dungeonSide = (int)((WorldGen.genRand.Next(2) == 0) ? DungeonSide.Left : DungeonSide.Right));
            if (WorldGen.remixWorldGen)
            {
                if (num4 <= (int)DungeonSide.Left)
                {
                    double num5 = 1.0 - (double)WorldGen.genRand.Next(20, 35) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num5);
                }
                else
                {
                    double num6 = (double)WorldGen.genRand.Next(20, 35) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num6);
                }
            }
            else
            {
                int num7 = 15;
                int num8 = 30;
                if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
                {
                    num7 = 25;
                    num8 = 35;
                }
                if (num4 <= (int)DungeonSide.Left)
                {
                    double num9 = 1.0 - (double)WorldGen.genRand.Next(num7, num8) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num9);
                }
                else
                {
                    double num10 = (double)WorldGen.genRand.Next(num7, num8) * 0.01;
                    GenVars.jungleOriginX = (int)((double)Main.maxTilesX * num10);
                }
            }
            int num11 = WorldGen.genRand.Next(Main.maxTilesX);
            if (WorldGen.drunkWorldGen && (!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen))
            {
                num4 = (GenVars.CurrentDungeonGenVars.dungeonSide = (int)((num4 == (int)DungeonSide.Left) ? DungeonSide.Right : DungeonSide.Left));
            }
            if (num4 == (int)DungeonSide.Right)
            {
                while ((double)num11 < (double)Main.maxTilesX * 0.6 || (double)num11 > (double)Main.maxTilesX * 0.75)
                {
                    num11 = WorldGen.genRand.Next(Main.maxTilesX);
                }
            }
            else
            {
                while ((double)num11 < (double)Main.maxTilesX * 0.25 || (double)num11 > (double)Main.maxTilesX * 0.4)
                {
                    num11 = WorldGen.genRand.Next(Main.maxTilesX);
                }
            }
            if (WorldGen.drunkWorldGen && (!WorldGen.dontStarveWorldGen || WorldGen.tenthAnniversaryWorldGen))
            {
                num4 = (GenVars.CurrentDungeonGenVars.dungeonSide = (int)((num4 == (int)DungeonSide.Left) ? DungeonSide.Right : DungeonSide.Left));
            }
            int num12 = WorldGen.genRand.Next(50, 90);
            double num13 = (double)Main.maxTilesX / 4200.0;
            num12 += (int)((double)WorldGen.genRand.Next(20, 40) * num13);
            num12 += (int)((double)WorldGen.genRand.Next(20, 40) * num13);
            int num14 = num11 - num12;
            num12 = WorldGen.genRand.Next(50, 90);
            num12 += (int)((double)WorldGen.genRand.Next(20, 40) * num13);
            num12 += (int)((double)WorldGen.genRand.Next(20, 40) * num13);
            int num15 = num11 + num12;
            if (num14 < 0)
            {
                num14 = 0;
            }
            if (num15 > Main.maxTilesX)
            {
                num15 = Main.maxTilesX;
            }
            GenVars.snowOriginLeft = num14;
            GenVars.snowOriginRight = num15;
            GenVars.leftBeachEnd = WorldGen.genRand.Next(GenVars.beachSandRandomCenter - GenVars.beachSandRandomWidthRange, GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
            {
                GenVars.leftBeachEnd = GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange;
            }
            if (num4 == (int)DungeonSide.Right)
            {
                GenVars.leftBeachEnd += GenVars.beachSandDungeonExtraWidth;
            }
            else
            {
                GenVars.leftBeachEnd += GenVars.beachSandJungleExtraWidth;
            }
            GenVars.rightBeachStart = Main.maxTilesX - WorldGen.genRand.Next(GenVars.beachSandRandomCenter - GenVars.beachSandRandomWidthRange, GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.remixWorldGen)
            {
                GenVars.rightBeachStart = Main.maxTilesX - (GenVars.beachSandRandomCenter + GenVars.beachSandRandomWidthRange);
            }
            if (num4 == (int)DungeonSide.Left)
            {
                GenVars.rightBeachStart -= GenVars.beachSandDungeonExtraWidth;
            }
            else
            {
                GenVars.rightBeachStart -= GenVars.beachSandJungleExtraWidth;
            }
            if (num4 <= (int)DungeonSide.Left)
            {
                GenVars.CurrentDungeonGenVars.dungeonLocation = WorldGen.genRand.Next(GenVars.leftBeachEnd + GenVars.dungeonBeachPadding, (int)((double)Main.maxTilesX * 0.2));
            }
            else
            {
                GenVars.CurrentDungeonGenVars.dungeonLocation = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.8), GenVars.rightBeachStart - GenVars.dungeonBeachPadding);
            }
            GenVars.CurrentDungeonGenVars.outerPotentialDungeonBounds.Reset();
            GenVars.CurrentDungeonGenVars.innerPotentialDungeonBounds.Reset();
            if (WorldGen.SecretSeed.dualDungeons.Enabled)
            {
                WorldGen.GenerateWorld_SetupDungeonGenVars(1, false);
                if (num4 == (int)DungeonSide.Left)
                {
                    num4 = (GenVars.CurrentDungeonGenVars.dungeonSide = (int)DungeonSide.Right);
                }
                else
                {
                    num4 = (GenVars.CurrentDungeonGenVars.dungeonSide = (int)DungeonSide.Left);
                }
                if (num4 <= (int)DungeonSide.Left)
                {
                    GenVars.CurrentDungeonGenVars.dungeonLocation = WorldGen.genRand.Next(GenVars.leftBeachEnd + GenVars.dungeonBeachPadding, (int)((double)Main.maxTilesX * 0.2));
                }
                else
                {
                    GenVars.CurrentDungeonGenVars.dungeonLocation = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.8), GenVars.rightBeachStart - GenVars.dungeonBeachPadding);
                }
                GenVars.CurrentDungeonGenVars.outerPotentialDungeonBounds.Reset();
                GenVars.CurrentDungeonGenVars.innerPotentialDungeonBounds.Reset();
                GenVars.CurrentDungeon = 0;
                double num16 = (double)Main.maxTilesY / 1200.0;
                GenVars.DualDungeon_NormalizedDistanceSafeFromDither = 1.0 - 0.075 * num16;
            }
            int num17 = 0;
            if (Main.maxTilesX >= 8400)
            {
                num17 = 2;
            }
            else if (Main.maxTilesX >= 6400)
            {
                num17 = 1;
            }
            GenVars.extraBastStatueCountMax = 2 + num17;
            Main.tileSolid[659] = false;
            if (!Main.gameMenu)
            {
                Main.QueueMainThreadAction(new Action(Main.sectionManager.SetAllSectionsLoaded));
            }
        }
References System.Action(), Terraria.Main.ActiveWorldFileData, System.Collections.Generic.List< T >.Add(), Terraria.WorldBuilding.GenVars.beachSandDungeonExtraWidth, Terraria.WorldBuilding.GenVars.beachSandJungleExtraWidth, Terraria.WorldBuilding.GenVars.beachSandRandomCenter, Terraria.WorldBuilding.GenVars.beachSandRandomWidthRange, Terraria.Main.checkHalloween(), Terraria.Main.checkXMas(), System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.TreeTopsInfo.CopyExistingWorldInfoForWorldGeneration(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.Main.dayTime, Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.SecretSeed.DoRainsForAYear(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldBuilding.GenVars.dungeonBeachPadding, Terraria.WorldBuilding.GenVars.dungeonGenVars, Microsoft.Xna.Framework.Rectangle.Empty, Terraria.WorldGen.everythingWorldGen, Terraria.WorldBuilding.GenVars.flipInfections, Terraria.Main.gameMenu, Terraria.WorldGen.GenerateWorld_SetupDungeonGenVars(), Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Testing.GitStatus.GitSHA, Terraria.WorldGen.SecretSeed.InitializeSecretSeeds(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.innerPotentialDungeonBounds, int, Terraria.WorldBuilding.GenVars.jungleHut, Terraria.WorldBuilding.DungeonSide.Left, Terraria.WorldBuilding.GenVars.leftBeachEnd, System.list, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.outerPotentialDungeonBounds, Terraria.Main.QueueMainThreadAction(), Terraria.WorldGen.SecretSeed.rainsForAYear, Terraria.WorldGen.RandomizeBackgrounds(), Terraria.WorldGen.RandomizeCaveBackgrounds(), Terraria.WorldGen.RandomizeMoonState(), Terraria.WorldGen.RandomizeTreeStyle(), Terraria.WorldGen.RandomizeWeather(), Terraria.Liquid.ReInit(), Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Reset(), Terraria.GameContent.ExtraSpawnPointManager.ResetExtraSpawns(), Terraria.WorldGen.ResetGenerator(), Terraria.WorldBuilding.DungeonSide.Right, Terraria.Main.sectionManager, Terraria.IO.WorldFileData.Seed, Terraria.WorldSections.SetAllSectionsLoaded(), Terraria.WorldGen.SetupStatueList(), Terraria.WorldGen.skyblockWorldGen, Terraria.WorldBuilding.GenVars.skyLakes, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tileSolid, System.Collections.Generic.List< T >.ToArray(), Terraria.WorldGen.TreeTops, Terraria.Main.versionNumber, and Terraria.WorldGen.WorldGenParam_Evil.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__46_0(), Terraria.WorldGen.GenerateWorld(), Terraria.WorldBuilding.WorldGenSnapshot.Restore(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryReset().