Terraria Decompiled: Terraria.WorldGen.CheckTorch
CheckTorch()
static void Terraria.WorldGen.CheckTorch (int x, int y) inline static
Definition at line 86936 of file WorldGen.cs.
        {
            for (int i = x - 1; i <= x + 1; i++)
            {
                for (int j = y - 1; j <= y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        return;
                    }
                }
            }
            Tile tile = Main.tile[x, y];
            Tile tile2 = Main.tile[x, y - 1];
            Tile tile3 = Main.tile[x, y + 1];
            Tile tile4 = Main.tile[x - 1, y];
            Tile tile5 = Main.tile[x + 1, y];
            Tile tile6 = Main.tile[x - 1, y + 1];
            Tile tile7 = Main.tile[x + 1, y + 1];
            Tile tile8 = Main.tile[x - 1, y - 1];
            Tile tile9 = Main.tile[x + 1, y - 1];
            short num = 0;
            if (tile.frameX >= 66)
            {
                num = 66;
            }
            int num2 = -1;
            int num3 = -1;
            int num4 = -1;
            int num5 = -1;
            int num6 = -1;
            int num7 = -1;
            int num8 = -1;
            if (tile2 != null && tile2.active() && !tile2.bottomSlope())
            {
                ushort type = tile2.type;
            }
            if (tile3 != null && tile3.active() && ((TileID.Sets.Platforms[(int)tile3.type] && WorldGen.TopEdgeCanBeAttachedTo(x, y + 1)) || (!tile3.halfBrick() && !tile3.topSlope())))
            {
                num2 = (int)tile3.type;
            }
            if (tile4 != null && tile4.active() && (tile4.slope() == 0 || tile4.slope() % 2 != 1))
            {
                num3 = (int)tile4.type;
            }
            if (tile5 != null && tile5.active() && (tile5.slope() == 0 || tile5.slope() % 2 != 0))
            {
                num4 = (int)tile5.type;
            }
            if (tile6 != null && tile6.active())
            {
                num5 = (int)tile6.type;
            }
            if (tile7 != null && tile7.active())
            {
                num6 = (int)tile7.type;
            }
            if (tile8 != null && tile8.active())
            {
                num7 = (int)tile8.type;
            }
            if (tile9 != null && tile9.active())
            {
                num8 = (int)tile9.type;
            }
            if (num2 >= 0 && Main.tileSolid[num2] && (!Main.tileNoAttach[num2] || TileID.Sets.Platforms[num2]))
            {
                tile.frameX = num;
                return;
            }
            if ((num3 >= 0 && Main.tileSolid[num3] && !Main.tileNoAttach[num3]) || (num3 >= 0 && TileID.Sets.IsBeam[num3]) || (WorldGen.IsTreeType(num3) && WorldGen.IsTreeType(num7) && WorldGen.IsTreeType(num5)))
            {
                tile.frameX = 22 + num;
                return;
            }
            if ((num4 >= 0 && Main.tileSolid[num4] && !Main.tileNoAttach[num4]) || (num4 >= 0 && TileID.Sets.IsBeam[num4]) || (WorldGen.IsTreeType(num4) && WorldGen.IsTreeType(num8) && WorldGen.IsTreeType(num6)))
            {
                tile.frameX = 44 + num;
                return;
            }
            if (tile.wall > 0)
            {
                tile.frameX = num;
                return;
            }
            WorldGen.KillTile(x, y, false, false, false);
        }
References Terraria.Tile.active(), Terraria.Tile.bottomSlope(), Terraria.Tile.frameX, Terraria.Tile.halfBrick(), int, Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsTreeType(), Terraria.WorldGen.KillTile(), Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.Tile.topSlope(), Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrameImportant().