Terraria Decompiled: Terraria.WorldGen.PlayerLOS
PlayerLOS()
static bool Terraria.WorldGen.PlayerLOS (int x, int y) inline static
Definition at line 69767 of file WorldGen.cs.
        {
            Rectangle rectangle = new Rectangle(x * 16, y * 16, 16, 16);
            for (int i = 0; i < 255; i++)
            {
                if (Main.player[i].active)
                {
                    Rectangle rectangle2 = new Rectangle((int)((double)Main.player[i].position.X + (double)Main.player[i].width * 0.5 - (double)NPC.sWidth * 0.6), (int)((double)Main.player[i].position.Y + (double)Main.player[i].height * 0.5 - (double)NPC.sHeight * 0.6), (int)((double)NPC.sWidth * 1.2), (int)((double)NPC.sHeight * 1.2));
                    if (rectangle.Intersects(rectangle2))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Player.active, Terraria.Entity.height, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.player, Terraria.Entity.position, Terraria.NPC.sHeight, Terraria.NPC.sWidth, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.WorldGen.TriggerLunarApocalypse(), Terraria.GameContent.Events.CultistRitual.TrySpawning(), Terraria.GameContent.Events.MysticLogFairiesEvent.TrySpawningFairies(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().