Terraria Decompiled: Terraria.WorldGen.CheckProjectilePressurePad
CheckProjectilePressurePad()
static void Terraria.WorldGen.CheckProjectilePressurePad (int i, int j) inline static
Definition at line 87025 of file WorldGen.cs.
        {
            bool flag;
            bool flag2;
            bool flag3;
            bool flag4;
            WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(i, j, out flag, out flag2, out flag3, out flag4);
            Tile tile = Main.tile[i, j];
            bool flag5;
            switch (tile.frameX / 22)
            {
            case 0:
                flag5 = !flag4;
                break;
            case 1:
                flag5 = !flag;
                break;
            case 2:
                flag5 = !flag2;
                break;
            case 3:
                flag5 = !flag3;
                break;
            default:
                flag5 = true;
                break;
            }
            if (flag5)
            {
                if (flag4)
                {
                    tile.frameX = 0;
                    return;
                }
                if (flag)
                {
                    tile.frameX = 22;
                    return;
                }
                if (flag2)
                {
                    tile.frameX = 44;
                    return;
                }
                if (flag3)
                {
                    tile.frameX = 66;
                    return;
                }
                WorldGen.KillTile(i, j, false, false, false);
            }
        }
References Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.Tile.frameX, Terraria.WorldGen.KillTile(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.TileFrameImportant().