Terraria Decompiled: Terraria.WorldGen.AddMonsterVoiceChangeItemToChest
AddMonsterVoiceChangeItemToChest()
static void Terraria.WorldGen.AddMonsterVoiceChangeItemToChest (Chest chest, ref int itemIndex) inline static
Definition at line 35005 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(4);
            short num2 = 5509;
            switch (num)
            {
            case 1:
                num2 = 5505;
                break;
            case 2:
                num2 = 5506;
                break;
            case 3:
                num2 = 5508;
                break;
            }
            chest.item[itemIndex].SetDefaults((int)num2, null);
            chest.item[itemIndex].Prefix(-1);
            itemIndex++;
        }
References Terraria.WorldGen.genRand, Terraria.Chest.item, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Item.Prefix(), and Terraria.Item.SetDefaults().
Referenced by Terraria.WorldGen.AddBuriedChest().