Terraria Decompiled: Terraria.WorldGen.FixSunflowers
FixSunflowers()
static void Terraria.WorldGen.FixSunflowers () inline static
Definition at line 52184 of file WorldGen.cs.
        {
            for (int i = 5; i < Main.maxTilesX - 5; i++)
            {
                int num = 5;
                while ((double)num < Main.worldSurface)
                {
                    if (Main.tile[i, num].active() && Main.tile[i, num].type == 27)
                    {
                        WorldGen.FixSunflower(i, num);
                    }
                    num++;
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.FixSunflower(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88().