Terraria Decompiled: Terraria.WorldGen.CheckTileBreakability2_ShouldTileSurvive
CheckTileBreakability2_ShouldTileSurvive()
static bool Terraria.WorldGen.CheckTileBreakability2_ShouldTileSurvive (int x, int y) inline static
Definition at line 61447 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return false;
            }
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            Tile tile = Main.tile[x, y];
            if (TileID.Sets.BasicChest[(int)tile.type])
            {
                int i = (int)(tile.frameX / 18);
                int num = y - (int)(tile.frameY / 18);
                while (i > 1)
                {
                    i -= 2;
                }
                i = x - i;
                if (!Chest.DestroyChest(i, num))
                {
                    return true;
                }
            }
            if (tile.type == 88)
            {
                int num2 = (int)(tile.frameX / 18);
                int num3 = y - (int)(tile.frameY / 18);
                num2 %= 3;
                num2 = x - num2;
                if (!Chest.DestroyChest(num2, num3))
                {
                    return true;
                }
            }
            if (tile.type == 470)
            {
                return !TEDisplayDoll.IsBreakable(x, y);
            }
            return tile.type == 475 && !TEHatRack.IsBreakable(x, y);
        }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.Chest.DestroyChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.GameContent.Tile_Entities.TEDisplayDoll.IsBreakable(), Terraria.GameContent.Tile_Entities.TEHatRack.IsBreakable(), Terraria.Main.netMode, Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.MinecartDiggerHelper.CanGetPastTile(), Terraria.MessageBuffer.GetData(), and Terraria.WorldGen.KillTile().