Terraria Decompiled: Terraria.WorldGen.ShimmerMakeBiomeOpening
ShimmerMakeBiomeOpening()
static void Terraria.WorldGen.ShimmerMakeBiomeOpening (int direction, int X, int Y, int caveOpeningSize) inline static private
Definition at line 32409 of file WorldGen.cs.
        {
            int num = X;
            caveOpeningSize--;
            bool flag;
            do
            {
                num += direction;
                flag = true;
                for (int i = Y - caveOpeningSize + 1; i < Y - 1; i++)
                {
                    if (WorldGen.SolidTile(num, i, false))
                    {
                        flag = false;
                    }
                    if (WorldGen.SolidTile(num + direction, i, false))
                    {
                        flag = false;
                    }
                    if (WorldGen.SolidTile(num + direction * 2, i, false))
                    {
                        flag = false;
                    }
                    Main.tile[num, i].active(false);
                }
                for (int j = Y - caveOpeningSize; j < Y; j++)
                {
                    Main.tile[num - direction, j].active(false);
                }
                if (WorldGen.SolidTile(num - direction, Y - caveOpeningSize - 1, false))
                {
                    Main.tile[num - direction, Y - caveOpeningSize - 1].wall = 0;
                }
                if (WorldGen.SolidTile(num - direction, Y, false))
                {
                    Main.tile[num - direction, Y].wall = 0;
                }
                if (WorldGen.genRand.Next(2) == 0)
                {
                    Y += WorldGen.genRand.Next(-1, 2);
                }
            }
            while (!flag && num >= 50 && num <= Main.maxTilesX - 50 && Math.Abs(num - X) <= 100);
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.wall, System.X, and System.Y.
Referenced by Terraria.WorldGen.ShimmerMakeBiome().