Terraria Decompiled: Terraria.WorldGen.JustQuit
JustQuit()
static void Terraria.WorldGen.JustQuit () inline static
Definition at line 2429 of file WorldGen.cs.
        {
            try
            {
                SoundEngine.PlaySound(34, -1, -1, 0, 1f, 0f);
                SoundEngine.PlaySound(35, -1, -1, 0, 1f, 0f);
            }
            catch
            {
            }
            Main.invasionProgress = -1;
            Main.invasionProgressDisplayLeft = 0;
            Main.invasionProgressAlpha = 0f;
            Main.invasionProgressIcon = 0;
            Main.menuMode = 10;
            Main.gameMenu = true;
            SoundEngine.StopTrackedSounds();
            CaptureInterface.ResetFocus();
            Main.ActivePlayerFileData.StopPlayTimer();
            Main.fastForwardTimeToDawn = false;
            Main.fastForwardTimeToDusk = false;
            Main.UpdateTimeRate();
            Main.QueueMainThreadAction(new Action(Main.ClearVisualPostProcessEffects));
            if (Main.netMode == 0)
            {
                Main.GoToWorldSelect();
                Main.player[Main.myPlayer].position = new Vector2(0f, 0f);
                return;
            }
            if (Main.netMode == 1)
            {
                Main.menuMode = 0;
                Netplay.Disconnect = true;
                Main.netMode = 0;
            }
        }
References System.Action(), Terraria.Main.ActivePlayerFileData, Terraria.Main.ClearVisualPostProcessEffects(), Terraria.Main.GoToWorldSelect(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.QueueMainThreadAction(), Terraria.Graphics.Capture.CaptureInterface.ResetFocus(), Terraria.IO.PlayerFileData.StopPlayTimer(), Terraria.Audio.SoundEngine.StopTrackedSounds(), and Terraria.Main.UpdateTimeRate().
Referenced by Terraria.Testing.ChatCommands.ToolkitDebugCommands.QuitCommand().