Terraria Decompiled: Terraria.WorldGen.PaintTheDungeon
PaintTheDungeon()
static void Terraria.WorldGen.PaintTheDungeon (byte tilePaintColor, byte wallPaintColor) inline static private
Definition at line 21745 of file WorldGen.cs.
        {
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active())
                    {
                        if (Main.tileDungeon[(int)tile.type] || TileID.Sets.CrackedBricks[(int)tile.type])
{
                            tile.color(tilePaintColor);
                        }
                        if (tile.type == 19)
{
                            int num = (int)(tile.frameY / 18);
                            if (num >= 6 && num <= 12)
{
                                tile.color(tilePaintColor);
                            }
                        }
                    }
                    if (Main.wallDungeon[(int)tile.wall])
                    {
                        tile.wallColor(wallPaintColor);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Tile.frameY, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.FinishTenthAnniversaryWorld().