Terraria Decompiled: Terraria.WorldGen.NotTheBees
NotTheBees()
static void Terraria.WorldGen.NotTheBees () inline static private
Definition at line 22230 of file WorldGen.cs.
        {
            if (WorldGen.skyblockWorldGen)
            {
                return;
            }
            int num = Main.maxTilesX / 7;
            if (!WorldGen.notTheBees)
            {
                return;
            }
            int num2 = (GenVars.lavaLine + Main.maxTilesY - 180) / 2;
            if (WorldGen.remixWorldGen)
            {
                num2 = Main.maxTilesY - 180;
            }
            for (int i = 5; i < Main.maxTilesX - 5; i++)
            {
                for (int j = 5; j < Main.maxTilesY - 180; j++)
                {
                    bool flag = WorldGen.oceanDepths(i, j) || ((double)j < (Main.worldSurface + Main.rockLayer * 2.0) / 3.0 + (double)WorldGen.genRand.Next(3) && (i < WorldGen.beachDistance - 50 - WorldGen.genRand.Next(3) || i > Main.maxTilesX - WorldGen.beachDistance + 50 + WorldGen.genRand.Next(3)));
                    if (!WorldGen.remixWorldGen || (i >= num + WorldGen.genRand.Next(3) && i < Main.maxTilesX - num - WorldGen.genRand.Next(3) && ((double)j <= (Main.worldSurface * 2.0 + Main.rockLayer) / 3.0 + (double)WorldGen.genRand.Next(3) || j >= Main.maxTilesY - 350 - WorldGen.genRand.Next(3))))
                    {
                        if ((WorldGen.tenthAnniversaryWorldGen || WorldGen.dontStarveWorldGen || (GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left && i < Main.maxTilesX / 2) || (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right && i > Main.maxTilesX / 2)) && !WorldGen.remixWorldGen && flag)
{
                            if (Main.tile[i, j].active() && Main.tile[i, j].type == 229)
{
                                Main.tile[i, j].active(false);
                                Main.tile[i, j].liquidType(0);
                                Main.tile[i, j].liquid = byte.MaxValue;
                            }
                        }
                        else if (!WorldGen.remixWorldGen && (WorldGen.tenthAnniversaryWorldGen || WorldGen.dontStarveWorldGen || WorldGen.drunkWorldGen) && (double)i > (double)Main.maxTilesX * 0.4 - (double)WorldGen.genRand.Next(3) && (double)i < (double)Main.maxTilesX * 0.6 + (double)WorldGen.genRand.Next(3))
{
                            if ((double)j < Main.rockLayer - 1.0)
{
                                if (Main.tile[i, j].type == 0 && (!Main.tile[i - 1, j - 1].active() || !Main.tile[i, j - 1].active() || !Main.tile[i + 1, j - 1].active() || !Main.tile[i - 1, j].active() || !Main.tile[i + 1, j].active() || !Main.tile[i - 1, j + 1].active() || !Main.tile[i, j + 1].active() || !Main.tile[i + 1, j - 1].active()))
{
                                    Main.tile[i, j].type = 2;
                                }
                                if (Main.tile[i, j].wall == 15)
{
                                    ushort num3 = 65;
                                    if (WorldGen.genRand.Next(2) == 0)
{
                                        num3 = 63;
                                    }
                                    if (WorldGen.dontStarveWorldGen)
{
                                        num3 = 63;
                                    }
                                    else if (WorldGen.tenthAnniversaryWorldGen)
{
                                        num3 = 65;
                                    }
                                    Main.tile[i, j].wall = num3;
                                }
                            }
                            if (Main.tile[i, j].type == 60)
{
                                Main.tile[i, j].type = 59;
                            }
                        }
                        else
{
                            if (Main.tile[i, j].type == 52 || Main.tile[i, j].type == 382)
{
                                Main.tile[i, j].type = 62;
                            }
                            if ((WorldGen.SolidOrSlopedTile(i, j) || (Main.tile[i, j].active() && TileID.Sets.CrackedBricks[(int)Main.tile[i, j].type])) && (!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen || (Main.tile[i, j].type != 1 && Main.tile[i, j].type != 147 && Main.tile[i, j].type != 161 && Main.tile[i, j].type != 30 && Main.tile[i, j].type != 321 && Main.tile[i, j].type != 158 && Main.tile[i, j].type != 190 && Main.tile[i, j].type != 162)) && !TileID.Sets.Ore[(int)Main.tile[i, j].type] && Main.tile[i, j].type != 368 && Main.tile[i, j].type != 367 && Main.tile[i, j].type != 123 && Main.tile[i, j].type != 40 && Main.tile[i, j].type != 379 && (Main.tile[i, j].type != 56 || !WorldGen.skyblockWorldGen))
{
                                if (Main.tile[i, j].type == 191 || Main.tile[i, j].type == 383)
{
                                    if (!WorldGen.remixWorldGen)
{
                                        Main.tile[i, j].type = 383;
                                    }
                                }
                                else if (Main.tile[i, j].type == 192 || Main.tile[i, j].type == 384)
{
                                    if (!WorldGen.remixWorldGen)
{
                                        Main.tile[i, j].type = 384;
                                    }
                                }
                                else if (Main.tile[i, j].type != 151 && Main.tile[i, j].type != 662 && Main.tile[i, j].type != 661 && !TileID.Sets.Clouds[(int)Main.tile[i, j].type] && Main.tile[i, j].type != 120 && Main.tile[i, j].type != 158 && Main.tile[i, j].type != 175 && Main.tile[i, j].type != 45 && Main.tile[i, j].type != 119 && (Main.tile[i, j].type < 63 || Main.tile[i, j].type > 68) && Main.tile[i, j].type != 57 && Main.tile[i, j].type != 76 && Main.tile[i, j].type != 75 && Main.tile[i, j].type != 229 && Main.tile[i, j].type != 230 && Main.tile[i, j].type != 407 && Main.tile[i, j].type != 404)
{
                                    if (Main.tile[i, j].type == 224)
{
                                        if (!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen)
{
                                            Main.tile[i, j].type = 229;
                                        }
                                    }
                                    else if (Main.tile[i, j].type == 53)
{
                                        if ((!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen) && (i < WorldGen.beachDistance + WorldGen.genRand.Next(3) || i > Main.maxTilesX - WorldGen.beachDistance - WorldGen.genRand.Next(3)))
{
                                            Main.tile[i, j].type = 229;
                                        }
                                    }
                                    else if ((i <= WorldGen.beachDistance - WorldGen.genRand.Next(3) || i >= Main.maxTilesX - WorldGen.beachDistance + WorldGen.genRand.Next(3) || (Main.tile[i, j].type != 397 && Main.tile[i, j].type != 396)) && Main.tile[i, j].type != 10 && Main.tile[i, j].type != 203 && Main.tile[i, j].type != 25 && Main.tile[i, j].type != 137 && (Main.tile[i, j].type < 0 || !TileID.Sets.Boulders[(int)Main.tile[i, j].type]) && Main.tile[i, j].type != 141)
{
                                        if (Main.tileDungeon[(int)Main.tile[i, j].type] || TileID.Sets.CrackedBricks[(int)Main.tile[i, j].type])
{
                                            Main.tile[i, j].color(14);
                                        }
                                        else if (Main.tile[i, j].type != 226 && Main.tile[i, j].type != 202 && Main.tile[i, j].type != 70 && Main.tile[i, j].type != 48 && Main.tile[i, j].type != 232)
{
                                            if (TileID.Sets.Conversion.Grass[(int)Main.tile[i, j].type] || Main.tile[i, j].type == 60 || Main.tile[i, j].type == 70)
{
                                                if (j > GenVars.lavaLine + WorldGen.genRand.Next(-2, 3) + 2)
{
                                                    Main.tile[i, j].type = 70;
                                                }
                                                else
{
                                                    Main.tile[i, j].type = 60;
                                                }
                                            }
                                            else if (Main.tile[i, j].type == 0 || Main.tile[i, j].type == 59)
{
                                                Main.tile[i, j].type = 59;
                                            }
                                            else if (Main.tile[i, j].type != 633 && Main.tile[i, j].type != 562 && Main.tile[i, j].type != 563 && (!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen))
{
                                                if (j > GenVars.lavaLine + WorldGen.genRand.Next(-2, 3) + 2)
{
                                                    if (j <= num2 + WorldGen.genRand.Next(3))
{
                                                        Main.tile[i, j].type = 230;
                                                    }
                                                }
                                                else if (!WorldGen.remixWorldGen || (double)j > Main.worldSurface + (double)WorldGen.genRand.Next(-1, 2))
{
                                                    Main.tile[i, j].type = 225;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                            if (!WorldGen.remixWorldGen && j < Main.maxTilesY - 50 && j > 50 && i > WorldGen.beachDistance + 220 && i < Main.maxTilesX - WorldGen.beachDistance - 220)
{
                                if (Main.tile[i, j].active() && Main.tile[i, j].type == 225 && (!Main.tile[i - 1, j - 1].active() || !Main.tile[i, j - 1].active() || !Main.tile[i + 1, j - 1].active() || !Main.tile[i - 1, j].active() || !Main.tile[i + 1, j].active() || !Main.tile[i - 1, j + 1].active() || !Main.tile[i, j + 1].active() || !Main.tile[i + 1, j - 1].active()) && ((double)j < Main.worldSurface || (Main.tile[i - 1, j - 1].wall == 0 && Main.tile[i, j - 1].wall == 0 && Main.tile[i + 1, j - 1].wall == 0 && Main.tile[i - 1, j].wall == 0 && Main.tile[i + 1, j].wall == 0 && Main.tile[i - 1, j + 1].wall == 0 && Main.tile[i, j + 1].wall == 0 && Main.tile[i + 1, j - 1].wall == 0)))
{
                                    Main.tile[i, j].type = 60;
                                    for (int k = 0; k < 8; k++)
{
                                        int num4 = i + WorldGen.genRand.Next(-2, 3);
                                        int num5 = j + WorldGen.genRand.Next(-2, 3);
                                        if (Main.tile[num4, num5].active() && Main.tile[num4, num5].type == 225 && Main.tile[num4 - 1, num5 - 1].active() && Main.tile[num4, num5 - 1].active() && Main.tile[num4 + 1, num5 - 1].active() && Main.tile[num4 - 1, num5].active() && Main.tile[num4 + 1, num5].active() && Main.tile[num4 - 1, num5 + 1].active() && Main.tile[num4, num5 + 1].active() && Main.tile[num4 + 1, num5 - 1].active())
{
                                            Main.tile[num4, num5].type = 59;
                                        }
                                    }
                                }
                                if (Main.tile[i, j].active() && Main.tile[i, j].type == 230 && (!Main.tile[i - 1, j - 1].active() || !Main.tile[i, j - 1].active() || !Main.tile[i + 1, j - 1].active() || !Main.tile[i - 1, j].active() || !Main.tile[i + 1, j].active() || !Main.tile[i - 1, j + 1].active() || !Main.tile[i, j + 1].active() || !Main.tile[i + 1, j - 1].active()) && ((double)j < Main.worldSurface || (Main.tile[i - 1, j - 1].wall == 0 && Main.tile[i, j - 1].wall == 0 && Main.tile[i + 1, j - 1].wall == 0 && Main.tile[i - 1, j].wall == 0 && Main.tile[i + 1, j].wall == 0 && Main.tile[i - 1, j + 1].wall == 0 && Main.tile[i, j + 1].wall == 0 && Main.tile[i + 1, j - 1].wall == 0)))
{
                                    Main.tile[i, j].type = 70;
                                    for (int l = 0; l < 8; l++)
{
                                        int num6 = i + WorldGen.genRand.Next(-2, 3);
                                        int num7 = j + WorldGen.genRand.Next(-2, 3);
                                        if (Main.tile[num6, num7].active() && Main.tile[num6, num7].type == 230 && Main.tile[num6 - 1, num7 - 1].active() && Main.tile[num6, num7 - 1].active() && Main.tile[num6 + 1, num7 - 1].active() && Main.tile[num6 - 1, num7].active() && Main.tile[num6 + 1, num7].active() && Main.tile[num6 - 1, num7 + 1].active() && Main.tile[num6, num7 + 1].active() && Main.tile[num6 + 1, num7 - 1].active())
{
                                            Main.tile[num6, num7].type = 59;
                                        }
                                    }
                                }
                            }
                            if (Main.tile[i, j].wall != 15 && Main.tile[i, j].wall != 64 && Main.tile[i, j].wall != 204 && Main.tile[i, j].wall != 205 && Main.tile[i, j].wall != 206 && Main.tile[i, j].wall != 207 && Main.tile[i, j].wall != 87)
{
                                if (Main.wallDungeon[(int)Main.tile[i, j].wall])
{
                                    Main.tile[i, j].wallColor(14);
                                }
                                else if ((WorldGen.remixWorldGen || (!WorldGen.tenthAnniversaryWorldGen && !WorldGen.dontStarveWorldGen && !WorldGen.drunkWorldGen) || (double)i <= (double)Main.maxTilesX * 0.4 - (double)WorldGen.genRand.Next(3) || (double)i >= (double)Main.maxTilesX * 0.6 + (double)WorldGen.genRand.Next(3)) && (!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen) && Main.tile[i, j].wall != 23 && Main.tile[i, j].wall != 24 && Main.tile[i, j].wall != 42 && Main.tile[i, j].wall != 10 && Main.tile[i, j].wall != 21 && Main.tile[i, j].wall != 82 && Main.tile[i, j].wall != 187 && Main.tile[i, j].wall != 216 && Main.tile[i, j].wall != 34 && Main.tile[i, j].wall != 244)
{
                                    if (Main.tile[i, j].wall == 2)
{
                                        Main.tile[i, j].wall = 2;
                                    }
                                    else if (Main.tile[i, j].wall == 196)
{
                                        Main.tile[i, j].wall = 196;
                                    }
                                    else if (Main.tile[i, j].wall == 197)
{
                                        Main.tile[i, j].wall = 197;
                                    }
                                    else if (Main.tile[i, j].wall == 198)
{
                                        Main.tile[i, j].wall = 198;
                                    }
                                    else if (Main.tile[i, j].wall == 199)
{
                                        Main.tile[i, j].wall = 199;
                                    }
                                    else if (Main.tile[i, j].wall == 63)
{
                                        Main.tile[i, j].wall = 64;
                                    }
                                    else if (Main.tile[i, j].wall != 3 && Main.tile[i, j].wall != 83 && Main.tile[i, j].wall != 73 && Main.tile[i, j].wall != 62 && Main.tile[i, j].wall != 180 && Main.tile[i, j].wall != 178 && Main.tile[i, j].wall != 13 && Main.tile[i, j].wall != 14 && Main.tile[i, j].wall != 312 && Main.tile[i, j].wall != 313 && Main.tile[i, j].wall > 0 && (!WorldGen.remixWorldGen || (double)j > Main.worldSurface + (double)WorldGen.genRand.Next(-1, 2)) && j <= num2 + WorldGen.genRand.Next(3))
{
                                        Main.tile[i, j].wall = 86;
                                    }
                                }
                            }
                            if ((!WorldGen.tenthAnniversaryWorldGen || WorldGen.remixWorldGen || (double)j >= Main.worldSurface) && (!WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen) && Main.tile[i, j].liquid > 0 && j <= GenVars.lavaLine + 2)
{
                                if ((double)i > (double)Main.maxTilesX * 0.4 && (double)i < (double)Main.maxTilesX * 0.6)
{
                                    Main.tile[i, j].honey(false);
                                }
                                else if ((double)j > Main.rockLayer && (i < WorldGen.beachDistance + 200 || i > Main.maxTilesX - WorldGen.beachDistance - 200))
{
                                    Main.tile[i, j].honey(false);
                                }
                                else if (Main.wallDungeon[(int)Main.tile[i, j].wall])
{
                                    Main.tile[i, j].honey(false);
                                }
                                else if (!WorldGen.skyblockWorldGen)
{
                                    Main.tile[i, j].honey(true);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Terraria.ID.TileID.Sets.Boulders, Terraria.ID.TileID.Sets.Clouds, Terraria.Tile.color(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGen, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonSide, Terraria.WorldGen.genRand, Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.Tile.honey(), int, Terraria.WorldBuilding.GenVars.lavaLine, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.oceanDepths(), Terraria.ID.TileID.Sets.Ore, Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidOrSlopedTile(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses().