Terraria Decompiled: Terraria.WorldGen.SlopeTile
SlopeTile()
static bool Terraria.WorldGen.SlopeTile (int i, int j, int slope = 0, bool noEffects = false, bool quiet = true) inline static
Definition at line 81450 of file WorldGen.cs.
        {
            if (!WorldGen.CanPoundTile(i, j))
            {
                return false;
            }
            Main.tile[i, j].halfBrick(false);
            Main.tile[i, j].slope((byte)slope);
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                if (!noEffects)
                {
                    WorldGen.KillTile(i, j, true, true, false);
                }
                SoundEngine.PlaySound(0, i * 16, j * 16, 1, 1f, 0f);
                WorldGen.SquareTileFrame(i, j, true);
                slope = (int)Main.tile[i, j].slope();
                if (slope == 0)
                {
                    Rectangle rectangle = new Rectangle(i * 16, j * 16, 16, 16);
                    for (int k = 0; k < 255; k++)
                    {
                        if (Main.player[k].active && !Main.player[k].dead && rectangle.Intersects(new Rectangle((int)Main.player[k].position.X, (int)Main.player[k].position.Y, Main.player[k].width, Main.player[k].height)))
{
                            Main.player[k].gfxOffY += Main.player[k].position.Y + (float)Main.player[k].height - (float)rectangle.Y;
                            Main.player[k].position.Y = (float)(rectangle.Y - Main.player[k].height);
                        }
                    }
                }
            }
            if (!quiet)
            {
                NetMessage.SendData(17, -1, -1, null, 14, (float)i, (float)j, (float)slope, 0, 0, 0);
            }
            return true;
        }
References Terraria.Player.active, Terraria.WorldGen.CanPoundTile(), Terraria.Player.dead, Terraria.Player.gfxOffY, Terraria.Tile.halfBrick(), Terraria.Entity.height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.KillTile(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.Tile.slope(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.Projectile.AI_010(), Terraria.WorldBuilding.Actions.SetSlope.Apply(), Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.mayanTrap(), Terraria.TileObject.Place(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.WorldGen.PoundPlatform(), and Terraria.DelegateMethods.SpreadTile().