Terraria Decompiled: Terraria.WorldGen.PlaceSunflower
PlaceSunflower()
static void Terraria.WorldGen.PlaceSunflower (int x, int y, ushort type = 27) inline static
Definition at line 52132 of file WorldGen.cs.
        {
            if ((double)y > Main.worldSurface - 1.0 && !Main.remixWorld)
            {
                return;
            }
            bool flag = true;
            for (int i = x; i < x + 2; i++)
            {
                for (int j = y - 3; j < y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active() || Main.tile[i, j].wall > 0)
                    {
                        flag = false;
                    }
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (!Main.tile[i, y + 1].nactive() || Main.tile[i, y + 1].halfBrick() || Main.tile[i, y + 1].slope() != 0 || (Main.tile[i, y + 1].type != 2 && Main.tile[i, y + 1].type != 109))
                {
                    flag = false;
                }
            }
            if (flag)
            {
                int num = WorldGen.genRand.Next(3);
                for (int k = 0; k < 2; k++)
                {
                    for (int l = -3; l < 1; l++)
                    {
                        int num2 = k * 18 + WorldGen.genRand.Next(3) * 36;
                        if (l <= -2)
{
                            num2 = k * 18 + num * 36;
                        }
                        int num3 = (l + 3) * 18;
                        Main.tile[x + k, y + l].active(true);
                        Main.tile[x + k, y + l].frameX = (short)num2;
                        Main.tile[x + k, y + l].frameY = (short)num3;
                        Main.tile[x + k, y + l].type = type;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.remixWorld, Terraria.Tile.slope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.PlaceTile().