Terraria Decompiled: Terraria.WorldGen.GrowPumpkin
GrowPumpkin()
static void Terraria.WorldGen.GrowPumpkin (int i, int j, int type) inline static
Definition at line 51002 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k;
            for (k = (int)(Main.tile[i, j].frameY / 18); k > 1; k -= 2)
            {
            }
            int num = j - k;
            int l = (int)(Main.tile[i, j].frameX / 18);
            int num2 = 0;
            while (l > 1)
            {
                l -= 2;
                num2++;
            }
            l = i - l;
            int num3 = num2 * 36;
            if (num2 >= 4)
            {
                return;
            }
            for (int m = l; m < l + 2; m++)
            {
                for (int n = num; n < num + 2; n++)
                {
                    if (Main.tile[m, n] == null)
                    {
                        Main.tile[m, n] = new Tile();
                    }
                    if (!Main.tile[m, n].active() || (int)Main.tile[m, n].type != type || (int)Main.tile[m, n].frameX != (m - l) * 18 + num3)
                    {
                        flag = true;
                    }
                }
                if (!WorldGen.SolidTile(m, num + 2, false) || (Main.tile[m, num + 2].type != 2 && Main.tile[m, num + 2].type != 477 && Main.tile[m, num + 2].type != 492 && Main.tile[m, num + 2].type != 109))
                {
                    flag = true;
                }
            }
            if (!flag)
            {
                for (int num4 = l; num4 < l + 2; num4++)
                {
                    for (int num5 = num; num5 < num + 2; num5++)
                    {
                        if (Main.tile[num4, num5] == null)
{
                            Main.tile[num4, num5] = new Tile();
                        }
                        if ((int)Main.tile[num4, num5].type == type && Main.tile[num4, num5].active())
{
                            Tile tile = Main.tile[num4, num5];
                            tile.frameX += 36;
                        }
                    }
                }
            }
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, l, num, 2, 2, TileChangeType.None);
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Main.netMode, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile().