Terraria Decompiled: Terraria.WorldGen.CountTiles
CountTiles()
static void Terraria.WorldGen.CountTiles (int X) inline static
Definition at line 71439 of file WorldGen.cs.
        {
            if (X == 0)
            {
                WorldGen.totalEvil = WorldGen.totalEvil2;
                WorldGen.totalBlood = WorldGen.totalBlood2;
                WorldGen.totalSolid = WorldGen.totalSolid2;
                WorldGen.totalGood = WorldGen.totalGood2;
                WorldGen.tGood = (byte)Math.Round((double)WorldGen.totalGood / (double)WorldGen.totalSolid * 100.0);
                WorldGen.tEvil = (byte)Math.Round((double)WorldGen.totalEvil / (double)WorldGen.totalSolid * 100.0);
                WorldGen.tBlood = (byte)Math.Round((double)WorldGen.totalBlood / (double)WorldGen.totalSolid * 100.0);
                if (WorldGen.tGood == 0 && WorldGen.totalGood > 0)
                {
                    WorldGen.tGood = 1;
                }
                if (WorldGen.tEvil == 0 && WorldGen.totalEvil > 0)
                {
                    WorldGen.tEvil = 1;
                }
                if (WorldGen.tBlood == 0 && WorldGen.totalBlood > 0)
                {
                    WorldGen.tBlood = 1;
                }
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(57, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
                }
                WorldGen.totalEvil2 = 0;
                WorldGen.totalSolid2 = 0;
                WorldGen.totalGood2 = 0;
                WorldGen.totalBlood2 = 0;
            }
            ushort num = 0;
            int num2 = 0;
            int num3 = 0;
            int num4 = 0;
            do
            {
                int num5;
                int num6;
                if (num3 == 0)
                {
                    num5 = 40;
                    num4 = (int)(Main.worldSurface + 1.0);
                    num6 = 5;
                }
                else
                {
                    num5 = num4;
                    num4 = Main.maxTilesY - 40;
                    num6 = 1;
                }
                for (int i = num5; i < num4; i++)
                {
                    Tile tile = Main.tile[X, i];
                    if (tile == null)
                    {
                        tile = (Main.tile[X, i] = new Tile());
                    }
                    WorldGen.Skyblock.hasWall[(int)tile.wall] = true;
                    if (tile.active())
                    {
                        WorldGen.Skyblock.currentActiveTiles++;
                        WorldGen.Skyblock.hasTile[(int)tile.type] = true;
                        ushort type = tile.type;
                        if (type != 0)
{
                            if (type == num)
{
                                num2 += num6;
                            }
                            else
{
                                WorldGen.tileCounts[(int)num] += num2;
                                num = type;
                                num2 = num6;
                            }
                        }
                    }
                }
                WorldGen.tileCounts[(int)num] += num2;
                num2 = 0;
                num3++;
            }
            while (num3 < 2);
            WorldGen.AddUpAlignmentCounts(false);
            if (X == Main.maxTilesX - 1)
            {
                WorldGen.Skyblock.Calculate();
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddUpAlignmentCounts(), Terraria.WorldGen.Skyblock.Calculate(), Terraria.WorldGen.Skyblock.currentActiveTiles, Terraria.WorldGen.Skyblock.hasTile, Terraria.WorldGen.Skyblock.hasWall, int, Terraria.Main.maxTilesX, Terraria.Main.netMode, System.Math.Round(), Terraria.NetMessage.SendData(), Terraria.WorldGen.tBlood, Terraria.WorldGen.tEvil, Terraria.WorldGen.tGood, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.tileCounts, Terraria.WorldGen.totalBlood, Terraria.WorldGen.totalBlood2, Terraria.WorldGen.totalEvil, Terraria.WorldGen.totalEvil2, Terraria.WorldGen.totalGood, Terraria.WorldGen.totalGood2, Terraria.WorldGen.totalSolid, Terraria.WorldGen.totalSolid2, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, and System.X.
Referenced by Terraria.WorldGen.UpdateWorld().