Terraria Decompiled: Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer
RandomizeBackgroundBasedOnPlayer()
static void Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer (UnifiedRandom random, Player player) inline static
Definition at line 3731 of file WorldGen.cs.
        {
            if (player.ZoneGlowshroom)
            {
                int num = WorldGen.mushroomBG;
                while (num == WorldGen.mushroomBG)
                {
                    WorldGen.setBG(8, random.Next(5));
                }
            }
            else if (player.ZoneUnderworldHeight)
            {
                int num = WorldGen.underworldBG;
                while (num == WorldGen.underworldBG)
                {
                    WorldGen.setBG(9, random.Next(3));
                }
            }
            else if (player.ZoneDesert)
            {
                int num = WorldGen.desertBG;
                do
                {
                    WorldGen.desertBG = WorldGen.RandomizeBackgrounds_Desert(random);
                }
                while (num == WorldGen.desertBG);
                WorldGen.setBG(6, WorldGen.desertBG);
            }
            else if (player.ZoneHallow)
            {
                int num = WorldGen.hallowBG;
                while (num == WorldGen.hallowBG)
                {
                    WorldGen.setBG(4, random.Next(6));
                }
            }
            else if (player.ZoneCorrupt)
            {
                int num = WorldGen.corruptBG;
                do
                {
                    WorldGen.corruptBG = WorldGen.RandomizeBackgrounds_Corruption(random);
                }
                while (num == WorldGen.corruptBG);
                WorldGen.setBG(1, WorldGen.corruptBG);
            }
            else if (player.ZoneCrimson)
            {
                int num = WorldGen.crimsonBG;
                while (num == WorldGen.crimsonBG)
                {
                    WorldGen.setBG(5, random.Next(7));
                }
            }
            else if (player.ZoneJungle)
            {
                int num = WorldGen.jungleBG;
                while (num == WorldGen.jungleBG)
                {
                    WorldGen.setBG(2, random.Next(7));
                }
            }
            else if (player.ZoneSnow)
            {
                int num = WorldGen.snowBG;
                while (num == WorldGen.snowBG)
                {
                    WorldGen.snowBG = random.Next(9);
                    if (WorldGen.snowBG == 2 && random.Next(2) == 0)
                    {
                        if (random.Next(2) == 0)
{
                            WorldGen.snowBG = 21;
                        }
                        else
{
                            WorldGen.snowBG = 22;
                        }
                    }
                    if (WorldGen.snowBG == 3 && random.Next(2) == 0)
                    {
                        if (random.Next(2) == 0)
{
                            WorldGen.snowBG = 31;
                        }
                        else
{
                            WorldGen.snowBG = 32;
                        }
                    }
                    if (WorldGen.snowBG == 4 && random.Next(2) == 0)
                    {
                        if (random.Next(2) == 0)
{
                            WorldGen.snowBG = 41;
                        }
                        else
{
                            WorldGen.snowBG = 42;
                        }
                    }
                    WorldGen.setBG(3, WorldGen.snowBG);
                }
            }
            else if (player.ZoneBeach)
            {
                int num = WorldGen.oceanBG;
                while (num == WorldGen.oceanBG)
                {
                    WorldGen.setBG(7, random.Next(8));
                }
            }
            else
            {
                int num2 = (int)(player.Center.X / 16f);
                if (num2 < Main.treeX[0])
                {
                    int num = WorldGen.treeBG1;
                    while (WorldGen.IsBackgroundConsideredTheSame(num, WorldGen.treeBG1))
                    {
                        WorldGen.treeBG1 = WorldGen.RollRandomForestBGStyle(random);
                    }
                    WorldGen.setBG(0, WorldGen.treeBG1);
                }
                else if (num2 < Main.treeX[1])
                {
                    int num = WorldGen.treeBG2;
                    while (WorldGen.IsBackgroundConsideredTheSame(num, WorldGen.treeBG2))
                    {
                        WorldGen.treeBG2 = WorldGen.RollRandomForestBGStyle(random);
                    }
                    WorldGen.setBG(10, WorldGen.treeBG2);
                }
                else if (num2 < Main.treeX[2])
                {
                    int num = WorldGen.treeBG3;
                    while (WorldGen.IsBackgroundConsideredTheSame(num, WorldGen.treeBG3))
                    {
                        WorldGen.treeBG3 = WorldGen.RollRandomForestBGStyle(random);
                    }
                    WorldGen.setBG(11, WorldGen.treeBG3);
                }
                else
                {
                    int num = WorldGen.treeBG4;
                    while (WorldGen.IsBackgroundConsideredTheSame(num, WorldGen.treeBG4))
                    {
                        WorldGen.treeBG4 = WorldGen.RollRandomForestBGStyle(random);
                    }
                    WorldGen.setBG(12, WorldGen.treeBG4);
                }
            }
            WorldGen.BackgroundsCache.UpdateCache();
        }
References Terraria.WorldGen.BackgroundsCache, Terraria.Entity.Center, Terraria.WorldGen.corruptBG, Terraria.WorldGen.crimsonBG, Terraria.WorldGen.desertBG, Terraria.WorldGen.hallowBG, int, Terraria.WorldGen.IsBackgroundConsideredTheSame(), Terraria.WorldGen.jungleBG, Terraria.WorldGen.mushroomBG, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.oceanBG, Terraria.WorldGen.RandomizeBackgrounds_Corruption(), Terraria.WorldGen.RandomizeBackgrounds_Desert(), Terraria.WorldGen.RollRandomForestBGStyle(), Terraria.WorldGen.setBG(), Terraria.WorldGen.snowBG, Terraria.WorldGen.treeBG1, Terraria.WorldGen.treeBG2, Terraria.WorldGen.treeBG3, Terraria.WorldGen.treeBG4, Terraria.Main.treeX, Terraria.WorldGen.underworldBG, Terraria.GameContent.BackgroundChangeFlashInfo.UpdateCache(), Microsoft.Xna.Framework.Vector2.X, Terraria.Player.ZoneBeach, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneDesert, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneHallow, Terraria.Player.ZoneJungle, Terraria.Player.ZoneSnow, and Terraria.Player.ZoneUnderworldHeight.