Terraria Decompiled: Terraria.WorldGen.SpawnFallingObjects
SpawnFallingObjects()
static void Terraria.WorldGen.SpawnFallingObjects () inline static private
Definition at line 72039 of file WorldGen.cs.
        {
            if (!Main.isThereAWorldSurface)
            {
                return;
            }
            bool flag = Main.drunkWorld && Main.getGoodWorld && !Main.remixWorld && Main.IsItStorming;
            if (!flag && WorldGen._isRainingBoulders)
            {
                AchievementsHelper.NotifyProgressionEvent(34);
            }
            WorldGen._isRainingBoulders = flag;
            if (flag)
            {
                int num = 3;
                if (Main.dontStarveWorld)
                {
                    num = 5;
                }
                if (Main.rand.Next(num) == 0)
                {
                    int num2 = Main.rand.Next(Main.maxTilesX - 50) + 100;
                    num2 *= 16;
                    int num3 = Main.rand.Next((int)((double)Main.maxTilesY * 0.05));
                    num3 *= 16;
                    Vector2 vector = new Vector2((float)num2, (float)num3);
                    int num4 = -1;
                    if (!Collision.SolidCollision(vector, 32, 32))
                    {
                        float num5 = Main.windSpeedCurrent * 16f;
                        num5 = Utils.Clamp<float>(num5, -16f, 16f);
                        float num6 = 8f;
                        EntitySource_ByProjectileSourceId entitySource_ByProjectileSourceId = new EntitySource_ByProjectileSourceId(19);
                        if (Main.rand.Next(50) == 0)
{
                            Projectile.NewProjectile(entitySource_ByProjectileSourceId, vector.X, vector.Y, num5, num6, 1013, 70, 10f, Main.myPlayer, 0f, (float)num4, 0f, new NewProjectileModifier(NewProjectileModifiers.RainHazard));
                        }
                        else
{
                            Projectile.NewProjectile(entitySource_ByProjectileSourceId, vector.X, vector.Y, num5, num6, 99, 70, 10f, Main.myPlayer, 0f, (float)num4, 0f, new NewProjectileModifier(NewProjectileModifiers.RainHazard));
                        }
                    }
                }
            }
            if (Main.dontStarveWorld && Main.getGoodWorld && !Main.remixWorld && Main.IsItStorming)
            {
                int num7 = 3;
                if (Main.drunkWorld)
                {
                    num7 = 2;
                }
                if (Main.rand.Next(num7) != 0)
                {
                    int num8 = Main.rand.Next(Main.maxTilesX - 50) + 100;
                    num8 *= 16;
                    int num9 = Main.rand.Next((int)((float)Main.maxTilesY * 0.05f));
                    num9 *= 16;
                    Vector2 vector2 = new Vector2((float)num8, (float)num9);
                    int num10 = -1;
                    if (!Collision.SolidCollision(vector2, 32, 32))
                    {
                        Vector2 vector3 = new Vector2(Utils.Clamp<float>(Main.windSpeedCurrent * 16f, -16f, 16f), 8f);
                        IEntitySource entitySource = new EntitySource_ByProjectileSourceId(20);
                        vector3 = vector3.RotatedByRandom(0.13089969754219055);
                        Projectile.NewProjectile(entitySource, vector2.X, vector2.Y, vector3.X, vector3.Y, 1049, 70, 10f, Main.myPlayer, 0f, (float)num10, 0f, new NewProjectileModifier(NewProjectileModifiers.RainHazard));
                    }
                }
            }
            if (WorldGen.meteorShowerCount > 0)
            {
                if (Main.fastForwardTimeToDawn || Main.fastForwardTimeToDusk)
                {
                    WorldGen.meteorShowerCount = 0;
                }
                int num11 = 4;
                if (Main.rand.Next(num11) == 0)
                {
                    int num12 = 12;
                    int num13 = Main.rand.Next(Main.maxTilesX - 50) + 100;
                    num13 *= 16;
                    int num14 = Main.rand.Next((int)((double)Main.maxTilesY * 0.05));
                    num14 *= 16;
                    Vector2 vector4 = new Vector2((float)num13, (float)num14);
                    int num15 = (int)Player.FindClosest(vector4, 12, 12);
                    if (Main.player[num15].active && !Main.player[num15].dead && Main.rand.Next(2) == 0)
                    {
                        num13 = (int)Main.player[num15].Center.X + Main.rand.Next(-2400, 2400);
                        num13 = Utils.Clamp<int>(num13, 800, (Main.maxTilesX - 50) * 16);
                        vector4.X = (float)num13;
                    }
                    if (!Collision.SolidCollision(vector4, 16, 16))
                    {
                        WorldGen.meteorShowerCount--;
                        float num16 = (float)Main.rand.Next(-100, 101);
                        float num17 = (float)(Main.rand.Next(200) + 100);
                        float num18 = (float)Math.Sqrt((double)(num16 * num16 + num17 * num17));
                        num18 = (float)num12 / num18;
                        num16 *= num18;
                        num17 *= num18;
                        IEntitySource entitySource2 = new EntitySource_ByProjectileSourceId(21);
                        int num19 = 50;
                        if (Main.masterMode)
{
                            num19 = 35;
                        }
                        else if (Main.expertMode)
{
                            num19 = 40;
                        }
                        Projectile.NewProjectile(entitySource2, vector4.X, vector4.Y, num16, num17, 1078, num19, 5f, -1, 0f, 0f, 0f, null);
                    }
                }
            }
            if (Main.coinRain > 0)
            {
                if (!Main.raining || Main.IsItStorming)
                {
                    Main.coinRain = 0;
                }
                else if (Main.rand.Next(30) == 0)
                {
                    int num20 = Main.rand.Next(50, Main.maxTilesX - 50);
                    num20 *= 16;
                    int num21 = Main.rand.Next((int)((double)Main.maxTilesY * 0.05));
                    num21 *= 16;
                    Vector2 vector5 = new Vector2((float)num20, (float)num21);
                    int num22 = (int)Player.FindClosest(vector5, 12, 12);
                    if (Main.player[num22].active && !Main.player[num22].dead && Main.rand.Next(2) == 0)
                    {
                        num20 = (int)Main.player[num22].Center.X + Main.rand.Next(-2400, 2400);
                        num20 = Utils.Clamp<int>(num20, 800, (Main.maxTilesX - 50) * 16);
                        vector5.X = (float)num20;
                    }
                    if (!Collision.SolidCollision(vector5, 32, 32))
                    {
                        int num23 = 71;
                        int num24 = Main.rand.Next(50, 100);
                        int num25 = num24;
                        if (Main.rand.Next(3) == 0)
{
                            num23 = 72;
                            num24 = Main.rand.Next(25, 100);
                            num25 = num24 * 100;
                        }
                        if (Main.rand.Next(9) == 0)
{
                            num23 = 73;
                            num24 = 1;
                            num25 = num24 * 100 * 100;
                        }
                        int num26 = Item.NewItem(WorldGen.GetItemSource_FromCoinRain(num20, num21), num20, num21, 16, 16, num23, num24, false, 0, false);
                        Main.coinRain -= num25;
                        if (num26 > 390)
{
                            Main.coinRain = 0;
                        }
                        if (Main.coinRain < 0)
{
                            Main.coinRain = 0;
                        }
                    }
                }
            }
            if (!Main.dayTime || Main.remixWorld)
            {
                for (int i = 0; i < Main.dayRate; i++)
                {
                    double num27 = (double)Main.maxTilesX / 4200.0;
                    num27 *= (double)Star.starfallBoost;
                    if ((double)Main.rand.Next(8000) < 10.0 * num27)
                    {
                        int num28 = 12;
                        int num29 = Main.rand.Next(Main.maxTilesX - 50) + 100;
                        num29 *= 16;
                        int num30 = Main.rand.Next((int)((double)Main.maxTilesY * 0.05));
                        num30 *= 16;
                        Vector2 vector6 = new Vector2((float)num29, (float)num30);
                        int num31 = -1;
                        int num32 = 15;
                        int num33 = (int)Player.FindClosest(vector6, 1, 1);
                        if (Main.remixWorld)
{
                            num32 = Main.player[num33].RollBadLuck(num32);
                        }
                        else
{
                            num32 = Main.player[num33].RollLuck(num32);
                        }
                        if (num32 == 0 && (double)Main.player[num33].position.Y < Main.worldSurface * 16.0 && Main.player[num33].afkCounter < Player.AFKTimeNeededForNoLuckyStars)
{
                            int num34 = Main.rand.Next(1, 640);
                            vector6.X = Main.player[num33].position.X + (float)Main.rand.Next(-num34, num34 + 1);
                            num31 = num33;
                        }
                        if (!Collision.SolidCollision(vector6, 16, 16))
{
                            float num35 = (float)Main.rand.Next(-100, 101);
                            float num36 = (float)(Main.rand.Next(200) + 100);
                            float num37 = (float)Math.Sqrt((double)(num35 * num35 + num36 * num36));
                            num37 = (float)num28 / num37;
                            num35 *= num37;
                            num36 *= num37;
                            Projectile.NewProjectile(new EntitySource_ByProjectileSourceId(11), vector6.X, vector6.Y, num35, num36, 720, 0, 0f, Main.myPlayer, 0f, (float)num31, 0f, null);
                        }
                    }
                }
            }
        }
References Terraria.WorldGen._isRainingBoulders, Terraria.Player.active, Terraria.Player.afkCounter, Terraria.Player.AFKTimeNeededForNoLuckyStars, Terraria.Entity.Center, Terraria.Utils.Clamp(), Terraria.Main.coinRain, Terraria.Main.dayRate, Terraria.Main.dayTime, Terraria.Player.dead, Terraria.Main.dontStarveWorld, Terraria.Main.drunkWorld, Terraria.Main.expertMode, Terraria.Main.fastForwardTimeToDawn, Terraria.Main.fastForwardTimeToDusk, Terraria.Player.FindClosest(), Terraria.Main.getGoodWorld, Terraria.WorldGen.GetItemSource_FromCoinRain(), int, Terraria.Main.IsItStorming, Terraria.Main.isThereAWorldSurface, Terraria.Main.masterMode, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.meteorShowerCount, Terraria.Main.myPlayer, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.NewProjectileModifier(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.player, Terraria.Entity.position, Terraria.NewProjectileModifiers.RainHazard(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Player.RollBadLuck(), Terraria.Player.RollLuck(), Terraria.Collision.SolidCollision(), System.Math.Sqrt(), Terraria.Star.starfallBoost, Terraria.Main.windSpeedCurrent, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.UpdateWorld().