Terraria Decompiled: Terraria.WorldGen.GenerateUnderworldStartingMound
GenerateUnderworldStartingMound()
static void Terraria.WorldGen.GenerateUnderworldStartingMound () inline static private
Definition at line 20687 of file WorldGen.cs.
        {
            int num = (int)((float)Main.maxTilesX * 0.38f);
            int num2 = (int)((float)Main.maxTilesX * 0.62f);
            int num3 = num;
            int num4 = Main.maxTilesY - 1;
            int num5 = Main.maxTilesY - 135;
            int num6 = Main.maxTilesY - 160;
            bool flag = false;
            Liquid.QuickWater(-2, -1, -1);
            while (num4 < Main.maxTilesY - 1 || num3 < num2)
            {
                if (!flag)
                {
                    num4 -= WorldGen.genRand.Next(1, 4);
                    if (num4 < num5)
                    {
                        flag = true;
                    }
                }
                else if (num3 >= num2)
                {
                    num4 += WorldGen.genRand.Next(1, 4);
                    if (num4 > Main.maxTilesY - 1)
                    {
                        num4 = Main.maxTilesY - 1;
                    }
                }
                else
                {
                    if ((num3 <= Main.maxTilesX / 2 - 5 || num3 >= Main.maxTilesX / 2 + 5) && WorldGen.genRand.Next(4) == 0)
                    {
                        if (WorldGen.genRand.Next(3) == 0)
{
                            num4 += WorldGen.genRand.Next(-1, 2);
                        }
                        else if (WorldGen.genRand.Next(6) == 0)
{
                            num4 += WorldGen.genRand.Next(-2, 3);
                        }
                        else if (WorldGen.genRand.Next(8) == 0)
{
                            num4 += WorldGen.genRand.Next(-4, 5);
                        }
                    }
                    if (num4 < num6)
                    {
                        num4 = num6;
                    }
                    if (num4 > num5)
                    {
                        num4 = num5;
                    }
                }
                for (int i = num4; i > num4 - 20; i--)
                {
                    Main.tile[num3, i].liquid = 0;
                }
                for (int j = num4; j < Main.maxTilesY; j++)
                {
                    Main.tile[num3, j] = new Tile();
                    Main.tile[num3, j].active(true);
                    Main.tile[num3, j].type = 57;
                }
                num3++;
            }
            Liquid.QuickWater(-2, -1, -1);
            for (int k = num; k < num2 + 15; k++)
            {
                for (int l = Main.maxTilesY - 300; l < num5 + 20; l++)
                {
                    Main.tile[k, l].liquid = 0;
                    if (Main.tile[k, l].type == 57 && Main.tile[k, l].active() && (!Main.tile[k - 1, l - 1].active() || !Main.tile[k, l - 1].active() || !Main.tile[k + 1, l - 1].active() || !Main.tile[k - 1, l].active() || !Main.tile[k + 1, l].active() || !Main.tile[k - 1, l + 1].active() || !Main.tile[k, l + 1].active() || !Main.tile[k + 1, l + 1].active()))
                    {
                        Main.tile[k, l].type = 633;
                    }
                }
            }
            for (int m = num; m < num2 + 15; m++)
            {
                for (int n = Main.maxTilesY - 200; n < num5 + 20; n++)
                {
                    if (Main.tile[m, n].type == 633 && Main.tile[m, n].active() && !Main.tile[m, n - 1].active() && WorldGen.genRand.Next(3) == 0)
                    {
                        WorldGen.TryGrowingTreeByType(634, m, n, 0, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, int, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Liquid.QuickWater(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TryGrowingTreeByType(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AddPasses().