Terraria Decompiled: Terraria.WorldGen.SonOfLakinater
SonOfLakinater()
static void Terraria.WorldGen.SonOfLakinater (int i, int j, double strengthMultiplier = 1::0) inline static
Definition at line 80328 of file WorldGen.cs.
        {
            short num = 0;
            if (WorldGen.genRand.Next(3) == 0)
            {
                if (WorldGen.drunkWorldGen && WorldGen.tenthAnniversaryWorldGen && WorldGen.remixWorldGen && !WorldGen.notTheBees)
                {
                    num = 3;
                }
                else if (WorldGen.getGoodWorldGen && ((double)i < (double)Main.maxTilesX * 0.45 || (double)i > (double)Main.maxTilesX * 0.55))
                {
                    num = 1;
                }
            }
            double num2 = (double)WorldGen.genRand.Next(15, 31) * strengthMultiplier;
            double num3 = (double)WorldGen.genRand.Next(30, 61);
            if (WorldGen.genRand.Next(5) == 0)
            {
                num2 *= 1.3;
                num3 *= 1.3;
            }
            if (WorldGen.drunkWorldGen)
            {
                num2 *= 1.3;
                num3 *= 1.3;
            }
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            double num4 = WorldGen.genRand.NextDouble() * 0.002;
            Vector2D vector2D2;
            if (WorldGen.genRand.Next(4) != 0)
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-15, 16) * 0.01;
            }
            else
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-50, 51) * 0.01;
                num4 = WorldGen.genRand.NextDouble() * 0.004 + 0.001;
            }
            vector2D2.Y = (double)WorldGen.genRand.Next(101) * 0.01;
            double num5 = num3;
            while (num2 > 3.0 && num3 > 0.0)
            {
                num2 -= (double)WorldGen.genRand.Next(11) * 0.1;
                num3 -= 1.0;
                int num6 = (int)(vector2D.X - num2 * 4.0);
                int num7 = (int)(vector2D.X + num2 * 4.0);
                int num8 = (int)(vector2D.Y - num2 * 3.0);
                int num9 = (int)(vector2D.Y + num2 * 2.0);
                if (num6 < 0)
                {
                    num6 = 0;
                }
                if (num7 > Main.maxTilesX)
                {
                    num7 = Main.maxTilesX;
                }
                if (num8 < 0)
                {
                    num8 = 0;
                }
                if (num9 > Main.maxTilesY)
                {
                    num9 = Main.maxTilesY;
                }
                double num10 = num2;
                for (int k = num6; k < num7; k++)
                {
                    for (int l = num8; l < num9; l++)
                    {
                        double num11 = Math.Abs((double)k - vector2D.X) * 0.6;
                        double num12 = Math.Abs((double)l - vector2D.Y) * 1.4;
                        double num13 = Math.Abs((double)k - vector2D.X) * 0.3;
                        double num14 = Math.Abs((double)l - vector2D.Y) * 5.0;
                        num11 = Utils.Lerp(num11, num13, num3 / num5);
                        num12 = Utils.Lerp(num12, num14, num3 / num5);
                        double num15 = Math.Sqrt(num11 * num11 + num12 * num12);
                        int num16 = j + 5;
                        if (num15 < num10 * 0.4)
{
                            if (l >= j)
{
                                if (l <= j + 1)
{
                                    if (WorldGen.WillWaterPlacedHereStayPut(k, l))
{
                                        Main.tile[k, l].liquid = byte.MaxValue;
                                        Main.tile[k, l].liquidType((int)num);
                                    }
                                }
                                else
{
                                    Main.tile[k, l].liquid = byte.MaxValue;
                                    Main.tile[k, l].liquidType((int)num);
                                }
                            }
                            Main.tile[k, l].active(false);
                            if (!WorldGen.isGeneratingOrLoadingWorld)
{
                                WorldGen.SquareTileFrame(k, l, true);
                            }
                            if (Main.tile[k, l].type == 59 || Main.tile[k, l].type == 60)
{
                                WorldGen.SpreadGrass(k - 1, l, 59, 60, true, default(TileColorCache));
                                WorldGen.SpreadGrass(k + 1, l, 59, 60, true, default(TileColorCache));
                                WorldGen.SpreadGrass(k, l + 1, 59, 60, true, default(TileColorCache));
                            }
                        }
                        else if (l > j + 1 && num15 < num10 && Main.tile[k, l].liquid == 0)
{
                            if (Math.Abs((double)k - vector2D.X) * 0.8 < num10 && !Main.tile[k, l].active() && Main.tile[k, l].wall > 0 && Main.tile[k - 1, l].wall > 0 && Main.tile[k + 1, l].wall > 0 && Main.tile[k, l + 1].wall > 0)
{
                                Main.tile[k, l].type = WallID.Sets.WallTypeToTerrainTileType[(int)Main.tile[k, l].wall];
                                Main.tile[k, l].active(true);
                            }
                        }
                        else if (l < j && num3 == num5 - 1.0 && (double)l > GenVars.worldSurfaceLow - 20.0 && Main.tile[k, l].active() && !TileID.Sets.Clouds[(int)Main.tile[k, l].type])
{
                            num11 = (double)Math.Abs(k - i) * 0.7;
                            num12 = (double)Math.Abs(l - num16) * 1.35;
                            num15 = Math.Sqrt(num11 * num11 + num12 * num12);
                            double num17 = num10 * 0.4;
                            double num18 = (double)Math.Abs(k - i) / (double)(num7 - i);
                            num18 = 1.0 - num18;
                            num18 *= 2.3;
                            num18 *= num18;
                            num18 *= num18;
                            if (l < num16 && num11 < num17 + (double)Math.Abs(l - num16) * 0.5 * num18)
{
                                Main.tile[k, l].active(false);
                                if (Main.tile[k, l].type == 59 || Main.tile[k, l].type == 60)
{
                                    WorldGen.SpreadGrass(k - 1, l, 59, 60, true, default(TileColorCache));
                                    WorldGen.SpreadGrass(k + 1, l, 59, 60, true, default(TileColorCache));
                                    WorldGen.SpreadGrass(k, l + 1, 59, 60, true, default(TileColorCache));
                                }
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-100, 101) * num4;
                vector2D2.Y += (double)WorldGen.genRand.Next(-100, 101) * 0.01;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                if (vector2D2.Y > 1.0)
                {
                    vector2D2.Y = 1.0;
                }
                double num19 = 0.5 * (1.0 - num3 / num5);
                if (vector2D2.Y < num19)
                {
                    vector2D2.Y = num19;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, int, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Utils.Lerp(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.SpreadGrass(), System.Math.Sqrt(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.ID.WallID.Sets.WallTypeToTerrainTileType, Terraria.WorldGen.WillWaterPlacedHereStayPut(), Terraria.WorldBuilding.GenVars.worldSurfaceLow, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().