Terraria Decompiled: Terraria.WorldGen.Place1x1
Place1x1()
static void Terraria.WorldGen.Place1x1 (int x, int y, int type, int style = 0) inline static
Definition at line 43457 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 2))
            {
                return;
            }
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            if (Main.tile[x, y + 1] == null)
            {
                Main.tile[x, y + 1] = new Tile();
            }
            Tile tile = Main.tile[x, y];
            Tile tile2 = Main.tile[x, y + 1];
            if (type == 324)
            {
                if (WorldGen.SolidTile2(x, y + 1) || (tile2.nactive() && Main.tileTable[(int)tile2.type]))
                {
                    tile.active(true);
                    tile.type = (ushort)type;
                    tile.frameX = (short)(22 * WorldGen.genRand.Next(3));
                    tile.frameY = (short)(22 * style);
                }
                return;
            }
            if (type >= 0 && TileID.Sets.Wiring.IsAMechanism[type] && tile2.type >= 0 && TileID.Sets.Boulders[(int)tile2.type])
            {
                return;
            }
            if (WorldGen.SolidTile2(x, y + 1) && !tile.active())
            {
                tile.active(true);
                tile.type = (ushort)type;
                if (type == 324)
                {
                    tile.frameX = (short)(22 * WorldGen.RollRandomSeaShellStyle());
                    tile.frameY = (short)(22 * style);
                    return;
                }
                if (type == 144 || type == 239 || type == 36)
                {
                    tile.frameX = (short)(style * 18);
                    tile.frameY = 0;
                    return;
                }
                tile.frameY = (short)(style * 18);
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.Wiring.IsAMechanism, Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RollRandomSeaShellStyle(), Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileTable, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().