Terraria Decompiled: Terraria.WorldGen.Pyramid
Pyramid()
static bool Terraria.WorldGen.Pyramid (int i, int j, int pyramidMinDepth = 75, int pyramidMaxDepth = 125, bool noTunnel = false) inline static
Definition at line 24777 of file WorldGen.cs.
        {
            ushort num = 151;
            ushort num2 = 34;
            if (Main.tile[i, j].active() && (Main.tile[i, j].type == 151 || Main.tile[i, j].wall == 151))
            {
                return false;
            }
            if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(i, j + pyramidMaxDepth, 5, false))
            {
                return false;
            }
            if (WorldGen.SecretSeed.surfaceIsDesert.Enabled || WorldGen.SecretSeed.errorWorld.Enabled || WorldGen.SecretSeed.dualDungeons.Enabled)
            {
                if (WorldGen.SecretSeed.surfaceIsDesert.Enabled || WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    if (WorldGen.IsTileNearby(i, j, 151, 100))
                    {
                        return false;
                    }
                    if (WorldGen.IsTileNearby(i, j, 203, 100))
                    {
                        return false;
                    }
                    if (WorldGen.IsTileNearby(i, j, 25, 100))
                    {
                        return false;
                    }
                }
                if (WorldGen.IsTileNearby(i, j, 41, 100))
                {
                    return false;
                }
                if (WorldGen.IsTileNearby(i, j, 43, 100))
                {
                    return false;
                }
                if (WorldGen.IsTileNearby(i, j, 44, 100))
                {
                    return false;
                }
            }
            int num3 = j - WorldGen.genRand.Next(0, 7);
            int num4 = WorldGen.genRand.Next(9, 13);
            int num5 = 1;
            int num6 = j + WorldGen.genRand.Next(pyramidMinDepth, pyramidMaxDepth);
            for (int k = num3; k < num6; k++)
            {
                for (int l = i - num5; l < i + num5 - 1; l++)
                {
                    Main.tile[l, k].type = num;
                    Main.tile[l, k].active(true);
                    Main.tile[l, k].halfBrick(false);
                    Main.tile[l, k].slope(0);
                }
                num5++;
            }
            for (int m = i - num5 - 5; m <= i + num5 + 5; m++)
            {
                for (int n = j - 1; n <= num6 + 1; n++)
                {
                    bool flag = true;
                    for (int num7 = m - 1; num7 <= m + 1; num7++)
                    {
                        for (int num8 = n - 1; num8 <= n + 1; num8++)
{
                            if (!Main.tile[num7, num8].active() || Main.tile[num7, num8].type != num)
{
                                flag = false;
                            }
                        }
                    }
                    if (flag)
                    {
                        Main.tile[m, n].wall = 34;
                        WorldGen.SquareWallFrame(m, n, true);
                    }
                }
            }
            int num9 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num9 = -1;
            }
            int num10 = i - num4 * num9;
            int num11 = j + num4;
            int num12 = WorldGen.genRand.Next(5, 8);
            bool flag2 = true;
            int num13 = WorldGen.genRand.Next(20, 30);
            while (flag2)
            {
                flag2 = false;
                bool flag3 = false;
                for (int num14 = num11; num14 <= num11 + num12; num14++)
                {
                    int num15 = num10;
                    if (Main.tile[num15, num14 - 1].active() && Main.tile[num15, num14 - 1].type == 53)
                    {
                        flag3 = true;
                    }
                    if (Main.tile[num15, num14].active() && Main.tile[num15, num14].type == num)
                    {
                        Main.tile[num15, num14 + 1].wall = num2;
                        Main.tile[num15 + num9, num14].wall = num2;
                        Main.tile[num15, num14].active(false);
                        flag2 = true;
                    }
                    if (flag3)
                    {
                        Main.tile[num15, num14].type = 53;
                        Main.tile[num15, num14].active(true);
                        Main.tile[num15, num14].halfBrick(false);
                        Main.tile[num15, num14].slope(0);
                    }
                }
                num10 -= num9;
            }
            num10 = i - num4 * num9;
            bool flag4 = true;
            bool flag5 = false;
            flag2 = true;
            while (flag2)
            {
                for (int num16 = num11; num16 <= num11 + num12; num16++)
                {
                    int num17 = num10;
                    Main.tile[num17, num16].active(false);
                }
                num10 += num9;
                num11++;
                num13--;
                if (num11 >= num6 - num12 * 2)
                {
                    num13 = 10;
                }
                if (num13 <= 0)
                {
                    bool flag6 = false;
                    if (!flag4 && !flag5)
                    {
                        if (noTunnel)
{
                            flag2 = false;
                        }
                        flag5 = true;
                        flag6 = true;
                        int num18 = WorldGen.genRand.Next(7, 13);
                        int num19 = WorldGen.genRand.Next(23, 28);
                        int num20 = num19;
                        int num21 = num10;
                        while (num19 > 0)
{
                            for (int num22 = num11 - num18 + num12; num22 <= num11 + num12; num22++)
{
                                if (num19 == num20 || num19 == 1)
{
                                    if (num22 >= num11 - num18 + num12 + 2)
{
                                        Main.tile[num10, num22].active(false);
                                    }
                                }
                                else if (num19 == num20 - 1 || num19 == 2 || num19 == num20 - 2 || num19 == 3)
{
                                    if (num22 >= num11 - num18 + num12 + 1)
{
                                        Main.tile[num10, num22].active(false);
                                    }
                                }
                                else
{
                                    Main.tile[num10, num22].active(false);
                                }
                            }
                            num19--;
                            num10 += num9;
                        }
                        int num23 = num10 - num9;
                        int num24 = num23;
                        int num25 = num21;
                        if (num23 > num21)
{
                            num24 = num21;
                            num25 = num23;
                        }
                        int num26 = WorldGen.genRand.Next(3);
                        if (num26 == 0)
{
                            num26 = WorldGen.genRand.Next(3);
                        }
                        if (Main.tenthAnniversaryWorld && num26 == 0)
{
                            num26 = 1;
                        }
                        if (num26 == 0)
{
                            num26 = 848;
                        }
                        else if (num26 == 1)
{
                            num26 = 857;
                        }
                        else if (num26 == 2)
{
                            num26 = 934;
                        }
                        WorldGen.AddBuriedChest((num24 + num25) / 2, num11, num26, false, 1, false, 0);
                        int num27 = WorldGen.genRand.Next(1, 10);
                        for (int num28 = 0; num28 < num27; num28++)
{
                            int num29 = WorldGen.genRand.Next(num24, num25);
                            int num30 = num11 + num12;
                            WorldGen.PlaceSmallPile(num29, num30, WorldGen.genRand.Next(16, 19), 1, 185);
                        }
                        WorldGen.PlaceTile(num24 + 2, num11 - num18 + num12 + 1, 91, true, false, -1, WorldGen.genRand.Next(4, 7));
                        WorldGen.PlaceTile(num24 + 3, num11 - num18 + num12, 91, true, false, -1, WorldGen.genRand.Next(4, 7));
                        WorldGen.PlaceTile(num25 - 2, num11 - num18 + num12 + 1, 91, true, false, -1, WorldGen.genRand.Next(4, 7));
                        WorldGen.PlaceTile(num25 - 3, num11 - num18 + num12, 91, true, false, -1, WorldGen.genRand.Next(4, 7));
                        for (int num31 = num24; num31 <= num25; num31++)
{
                            WorldGen.PlacePot(num31, num11 + num12, 28, WorldGen.genRand.Next(25, 28));
                        }
                    }
                    if (flag4)
                    {
                        flag4 = false;
                        num9 *= -1;
                        num13 = WorldGen.genRand.Next(15, 20);
                    }
                    else if (flag6)
                    {
                        num13 = WorldGen.genRand.Next(10, 15);
                    }
                    else
                    {
                        num9 *= -1;
                        num13 = WorldGen.genRand.Next(20, 40);
                    }
                }
                if (num11 >= num6 - num12)
                {
                    flag2 = false;
                }
            }
            if (noTunnel)
            {
                return true;
            }
            int num32 = WorldGen.genRand.Next(100, 200);
            int num33 = WorldGen.genRand.Next(500, 800);
            flag2 = true;
            int num34 = num12;
            num13 = WorldGen.genRand.Next(10, 50);
            if (num9 == 1)
            {
                num10 -= num34;
            }
            int num35 = WorldGen.genRand.Next(5, 10);
            while (flag2)
            {
                num32--;
                num33--;
                num13--;
                for (int num36 = num10 - num35 - WorldGen.genRand.Next(0, 2); num36 <= num10 + num34 + num35 + WorldGen.genRand.Next(0, 2); num36++)
                {
                    int num37 = num11;
                    if (num36 >= num10 && num36 <= num10 + num34)
                    {
                        Main.tile[num36, num37].active(false);
                    }
                    else if (!Main.wallDungeon[(int)Main.tile[num36, num37].wall])
                    {
                        Main.tile[num36, num37].type = num;
                        Main.tile[num36, num37].active(true);
                        Main.tile[num36, num37].halfBrick(false);
                        Main.tile[num36, num37].slope(0);
                    }
                    if (num36 >= num10 - 1 && num36 <= num10 + 1 + num34 && !Main.wallDungeon[(int)Main.tile[num36, num37].wall])
                    {
                        Main.tile[num36, num37].wall = num2;
                    }
                }
                num11++;
                num10 += num9;
                if (num32 <= 0)
                {
                    flag2 = false;
                    for (int num38 = num10 + 1; num38 <= num10 + num34 - 1; num38++)
                    {
                        if (Main.tile[num38, num11].active())
{
                            flag2 = true;
                        }
                    }
                }
                if (num13 < 0)
                {
                    num13 = WorldGen.genRand.Next(10, 50);
                    num9 *= -1;
                }
                if (num33 <= 0)
                {
                    flag2 = false;
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.InAnyPotentialDungeonBounds(), Terraria.WorldGen.IsTileNearby(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceTile(), Terraria.Tile.slope(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldGen.SecretSeed.surfaceIsDesert, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.AddPasses().