Terraria Decompiled: Terraria.WorldGen.PaintTheSand
PaintTheSand()
static void Terraria.WorldGen.PaintTheSand (byte tilePaintColor, byte wallPaintColor) inline static private
Definition at line 21527 of file WorldGen.cs.
        {
            for (int i = 20; i < Main.maxTilesX - 20; i++)
            {
                for (int j = 20; j < Main.maxTilesY - 20; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && (tile.type == 53 || tile.type == 396 || tile.type == 397))
                    {
                        tile.color(tilePaintColor);
                        if ((double)j > Main.worldSurface)
{
                            if (Main.tile[i, j - 1].type == 165 || Main.tile[i, j - 1].type == 185 || Main.tile[i, j - 1].type == 186 || Main.tile[i, j - 1].type == 187)
{
                                Main.tile[i, j - 1].color(tilePaintColor);
                            }
                            if (Main.tile[i, j - 2].type == 165 || Main.tile[i, j - 2].type == 185 || Main.tile[i, j - 2].type == 186 || Main.tile[i, j - 2].type == 187)
{
                                Main.tile[i, j - 2].color(tilePaintColor);
                            }
                            if (Main.tile[i, j + 1].type == 165)
{
                                Main.tile[i, j + 1].color(tilePaintColor);
                            }
                            if (Main.tile[i, j + 2].type == 165)
{
                                Main.tile[i, j + 2].color(tilePaintColor);
                            }
                        }
                    }
                    if (tile.wall == 187 || tile.wall == 216)
                    {
                        tile.wallColor(tilePaintColor);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.FinishTenthAnniversaryWorld().