Terraria Decompiled: Terraria.WorldGen.ReplaceTile
ReplaceTile()
static bool Terraria.WorldGen.ReplaceTile (int x, int y, int targetType, int targetStyle) inline static
Definition at line 61520 of file WorldGen.cs.
        {
            Tile tileSafely = Framing.GetTileSafely(x, y);
            if (!WorldGen.WouldTileReplacementWork(targetType, x, y))
            {
                return false;
            }
            if (!WorldGen.IsTileReplaceable(x, y))
            {
                return false;
            }
            WorldGen.MoveReplaceTileAnchor(ref x, ref y, targetType, tileSafely);
            int num = WorldGen.KillTile_GetTileDustAmount(false, tileSafely);
            for (int i = 0; i < num; i++)
            {
                WorldGen.KillTile_MakeTileDust(x, y, tileSafely);
            }
            WorldGen.KillTile_PlaySounds(x, y, false, tileSafely);
            WorldGen.KillTile_DropItems(x, y, tileSafely, true);
            WorldGen.AttemptFossilShattering(x, y, tileSafely, false);
            WorldGen.ReplaceTile_DoActualReplacement(targetType, targetStyle, x, y, tileSafely);
            return true;
        }
References Terraria.WorldGen.AttemptFossilShattering(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.IsTileReplaceable(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillTile_PlaySounds(), Terraria.WorldGen.MoveReplaceTileAnchor(), Terraria.WorldGen.ReplaceTile_DoActualReplacement(), and Terraria.WorldGen.WouldTileReplacementWork().
Referenced by Terraria.Liquid.CreateLiquidMergeTile(), Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_TryReplacingTiles().