Terraria Decompiled: Terraria.WorldGen.GrowLivingTree_HorizontalTunnel
GrowLivingTree_HorizontalTunnel()
static bool Terraria.WorldGen.GrowLivingTree_HorizontalTunnel (int i, int j) inline static private
Definition at line 25811 of file WorldGen.cs.
        {
            int num = i;
            int num2 = i;
            int num3 = 80;
            if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
            {
                if (WorldGen.genRand.Next(5) == 0)
                {
                    num3 = WorldGen.genRand.Next(400, 600);
                }
                else if (WorldGen.genRand.Next(2) == 0)
                {
                    num3 = WorldGen.genRand.Next(200, 400);
                }
                else
                {
                    num3 = WorldGen.genRand.Next(80, 200);
                }
            }
            else if (WorldGen.notTheBees && !WorldGen.drunkWorldGen)
            {
                num3 *= 3;
            }
            int num4 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num4 *= -1;
            }
            for (int k = 0; k < 2; k++)
            {
                bool flag = false;
                if (num == i && num4 > 0)
                {
                    int num5;
                    if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.IntersectsAnyPotentialDungeonBounds(out num5, new Rectangle(i + 5, j - 7, i + num3, j + 7), false))
                    {
                        return false;
                    }
                    int l = i + 5;
                    while (l < i + num3)
                    {
                        if (!WorldGen.InWorld(l, j, 10))
{
                            return false;
                        }
                        if ((double)j < Main.worldSurface)
{
                            int num6 = j - 7;
                            while (num6 <= j + 7 && Main.tile[l, num6].wall != 0)
{
                                num6++;
                            }
                        }
                        if (Main.tile[l, j].type == 48)
{
                            break;
                        }
                        if (Main.tile[l, j].type == 191)
{
                            for (int m = j - 2; m <= j; m++)
{
                                if (Main.tile[l + 2, m].wall != 244)
{
                                    flag = true;
                                }
                            }
                            if (!flag)
{
                                k = 2;
                                num2 = l + 2;
                                break;
                            }
                            break;
                        }
                        else
{
                            if (!Main.tile[l, j].active())
{
                                bool flag2 = true;
                                for (int n = j - 2; n <= j; n++)
{
                                    if ((double)j < Main.worldSurface + 3.0 && (Main.tile[l + 1, n].wall == 0 || Main.tile[l + 2, n].wall == 0 || Main.tile[l + 3, n].wall == 0))
{
                                        return false;
                                    }
                                    if (Main.tile[l, n].active() || Main.tile[l + 1, n].active() || Main.tile[l + 2, n].active())
{
                                        flag2 = false;
                                    }
                                }
                                if (flag2)
{
                                    k = 2;
                                    num2 = l;
                                    break;
                                }
                            }
                            l++;
                        }
                    }
                }
                flag = false;
                if (num2 == i && num4 < 0)
                {
                    int num7;
                    if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.IntersectsAnyPotentialDungeonBounds(out num7, new Rectangle(i - num3, j - 7, i - 5, j + 7), false))
                    {
                        return false;
                    }
                    int num8 = i - 5;
                    while (num8 > i - num3)
                    {
                        if (!WorldGen.InWorld(num8, j, 10))
{
                            return false;
                        }
                        if ((double)j < Main.worldSurface)
{
                            int num9 = j - 7;
                            while (num9 <= j + 7 && Main.tile[num8, num9].wall != 0)
{
                                num9++;
                            }
                        }
                        if (Main.tile[num8, j].type == 48)
{
                            break;
                        }
                        if (Main.tile[num8, j].type == 191)
{
                            for (int num10 = j - 2; num10 <= j; num10++)
{
                                if (Main.tile[num8 - 3, num10].wall != 244)
{
                                    flag = true;
                                }
                            }
                            if (!flag)
{
                                k = 2;
                                num = num8 - 2;
                                break;
                            }
                            break;
                        }
                        else
{
                            if (!Main.tile[num8, j].active())
{
                                bool flag3 = true;
                                for (int num11 = j - 2; num11 <= j; num11++)
{
                                    if ((double)j < Main.worldSurface + 3.0 && (Main.tile[num8 - 1, num11].wall == 0 || Main.tile[num8 - 2, num11].wall == 0 || Main.tile[num8 - 3, num11].wall == 0))
{
                                        return false;
                                    }
                                    if (Main.tile[num8, num11].active() || Main.tile[num8 - 1, num11].active() || Main.tile[num8 - 2, num11].active())
{
                                        flag3 = false;
                                    }
                                }
                                if (flag3)
{
                                    k = 2;
                                    num = num8;
                                    break;
                                }
                            }
                            num8--;
                        }
                    }
                }
                num4 *= -1;
            }
            if (num == num2)
            {
                return false;
            }
            bool flag4 = false;
            bool flag5 = false;
            for (int num12 = j - 5; num12 <= j + 1; num12++)
            {
                for (int num13 = num; num13 <= num2; num13++)
                {
                    int num14 = 2;
                    if (Math.Abs(num13 - num2) > 3 && Math.Abs(num13 - num) > 3)
                    {
                        num14 = 4;
                    }
                    if (Main.tile[num13, num12].wall != 244 && Main.tile[num13, num12].type != 19 && Main.tile[num13, num12].type != 15 && Main.tile[num13, num12].type != 304 && Main.tile[num13, num12].type != 21 && Main.tile[num13, num12].type != 10)
                    {
                        if (!Main.wallDungeon[(int)Main.tile[num13, num12].wall] && (!Main.tile[num13, num12].active() || (!Main.wallDungeon[(int)Main.tile[num13, num12 - 1].wall] && !Main.wallDungeon[(int)Main.tile[num13, num12 + 1].wall])) && (Main.tile[num13, num12].active() || Main.tile[num13, num12].wall != 34))
{
                            Main.tile[num13, num12].active(true);
                            Main.tile[num13, num12].type = 191;
                            Main.tile[num13, num12].halfBrick(false);
                        }
                        if (Main.tile[num13, num12 - 1].type == 40)
{
                            Main.tile[num13, num12 - 1].type = 0;
                        }
                        if (Main.tile[num13, num12 + 1].type == 40)
{
                            Main.tile[num13, num12 + 1].type = 0;
                        }
                    }
                    if (num12 >= j - num14 && num12 <= j && Main.tile[num13, num12].type != 19 && Main.tile[num13, num12].type != 15 && Main.tile[num13, num12].type != 304 && Main.tile[num13, num12].type != 21 && Main.tile[num13, num12].type != 10 && Main.tile[num13, num12 - 1].type != 15 && Main.tile[num13, num12 - 1].type != 304 && Main.tile[num13, num12 - 1].type != 21 && Main.tile[num13, num12 - 1].type != 10 && Main.tile[num13, num12 + 1].type != 10)
                    {
                        if (!Main.wallDungeon[(int)Main.tile[num13, num12].wall])
{
                            Main.tile[num13, num12].wall = 244;
                        }
                        Main.tile[num13, num12].liquid = 0;
                        Main.tile[num13, num12].active(false);
                    }
                    if (num12 == j)
                    {
                        int num15 = 7;
                        if (Main.wallDungeon[(int)Main.tile[num13, num12].wall] || Main.wallDungeon[(int)Main.tile[num13, num12 - 1].wall] || Main.wallDungeon[(int)Main.tile[num13, num12 - 2].wall])
{
                            num15 = 13;
                        }
                        if (num13 <= num + 4 && !flag4)
{
                            if (Main.tile[num13 - 1, num12].type == 10 || Main.tile[num13 + 1, num12].type == 10)
{
                                flag4 = true;
                            }
                            else if (WorldGen.genRand.Next(3) == 0)
{
                                WorldGen.PlaceTile(num13, num12, 10, true, false, -1, num15);
                                if (Main.tile[num13, num12].type == 10)
{
                                    flag4 = true;
                                }
                            }
                        }
                        if (num13 >= num2 - 4 && !flag5)
{
                            if (Main.tile[num13 - 1, num12].type == 10 || Main.tile[num13 + 1, num12].type == 10)
{
                                flag5 = true;
                            }
                            else if (WorldGen.genRand.Next(3) == 0)
{
                                WorldGen.PlaceTile(num13, num12, 10, true, false, -1, num15);
                                if (Main.tile[num13, num12].type == 10)
{
                                    flag5 = true;
                                }
                            }
                        }
                    }
                }
            }
            return true;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldGen.SecretSeed.extraLivingTrees, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IntersectsAnyPotentialDungeonBounds(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceTile(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.GrowLivingTree_MakePassage().