Terraria Decompiled: Terraria.WorldGen.moveRoom
moveRoom()
static void Terraria.WorldGen.moveRoom (int x, int y, int n) inline static
Definition at line 479 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                NetMessage.SendData(60, -1, -1, null, n, (float)x, (float)y, 0f, 0, 0, 0);
                return;
            }
            WorldGen.prioritizedTownNPCType = Main.npc[n].type;
            Main.npc[n].homeless = true;
            Main.npc[n].lookForHomeTimeout = 0;
            WorldGen.SpawnTownNPC(x, y, true);
            WorldGen.TownManager.SetRoom(Main.npc[n].type, Main.npc[n].homeTileX, Main.npc[n].homeTileY);
        }
References Terraria.NPC.homeless, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.NPC.lookForHomeTimeout, Terraria.Main.netMode, Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.GameContent.TownRoomManager.SetRoom(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.TownManager, and Terraria.NPC.type.
Referenced by Terraria.Main.TryMovingNPC().