Terraria Decompiled: Terraria.WorldGen.CrimPlaceHearts
CrimPlaceHearts()
static void Terraria.WorldGen.CrimPlaceHearts () inline static
Definition at line 76235 of file WorldGen.cs.
        {
            for (int i = 0; i < WorldGen.heartCount; i++)
            {
                int num = WorldGen.genRand.Next(16, 21);
                int x = WorldGen.heartPos[i].X;
                int y = WorldGen.heartPos[i].Y;
                for (int j = x - num / 2; j < x + num / 2; j++)
                {
                    for (int k = y - num / 2; k < y + num / 2; k++)
                    {
                        double num2 = (double)Math.Abs(j - x);
                        double num3 = (double)Math.Abs(k - y);
                        if (Math.Sqrt(num2 * num2 + num3 * num3) < (double)num * 0.4)
{
                            Main.tile[j, k].active(true);
                            Main.tile[j, k].type = GenVars.crimStone;
                            Main.tile[j, k].wall = GenVars.crimStoneWall;
                        }
                    }
                }
            }
            for (int l = 0; l < WorldGen.heartCount; l++)
            {
                int num = WorldGen.genRand.Next(10, 14);
                int x2 = WorldGen.heartPos[l].X;
                int y2 = WorldGen.heartPos[l].Y;
                for (int m = x2 - num / 2; m < x2 + num / 2; m++)
                {
                    for (int n = y2 - num / 2; n < y2 + num / 2; n++)
                    {
                        double num4 = (double)Math.Abs(m - x2);
                        double num5 = (double)Math.Abs(n - y2);
                        if (Math.Sqrt(num4 * num4 + num5 * num5) < (double)num * 0.3)
{
                            Main.tile[m, n].active(false);
                            Main.tile[m, n].wall = GenVars.crimStoneWall;
                        }
                    }
                }
            }
            for (int num6 = 0; num6 < WorldGen.heartCount; num6++)
            {
                WorldGen.AddShadowOrb(WorldGen.heartPos[num6].X, WorldGen.heartPos[num6].Y, true);
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.AddShadowOrb(), Terraria.WorldBuilding.GenVars.crimStone, Terraria.WorldBuilding.GenVars.crimStoneWall, Terraria.WorldGen.genRand, Terraria.WorldGen.heartCount, Terraria.WorldGen.heartPos, Terraria.Utilities.UnifiedRandom.Next(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.AddPasses().