Terraria Decompiled: Terraria.WorldGen.Check2x3Wall
Check2x3Wall()
static void Terraria.WorldGen.Check2x3Wall (int x, int y) inline static
Definition at line 42913 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return;
            }
            int type = (int)tile.type;
            int num = 0;
            int i = (int)(tile.frameX / 18);
            while (i >= 2)
            {
                i -= 2;
                num++;
            }
            int num2 = x - i;
            int num3 = y - (int)(tile.frameY / 18);
            i = num * 36;
            for (int j = num2; j < num2 + 2; j++)
            {
                for (int k = num3; k < num3 + 3; k++)
                {
                    Tile tile2 = Main.tile[j, k];
                    if (tile2 != null && ((int)tile2.type != type || !tile2.active() || tile2.wall <= 0 || (int)tile2.frameX != i + (j - num2) * 18 || (int)tile2.frameY != (k - num3) * 18))
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int l = num2; l < num2 + 2; l++)
                {
                    for (int m = num3; m < num3 + 3; m++)
                    {
                        Tile tile3 = Main.tile[l, m];
                        if (tile3 != null && (int)tile3.type == type && tile3.active())
{
                            WorldGen.KillTile(l, m, false, false, false);
                        }
                    }
                }
                if (type == 245)
                {
                    if (num == 31)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5634, 1, false, 0, false);
                    }
                    else if (num == 30)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5530, 1, false, 0, false);
                    }
                    else if (num == 29)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5488, 1, false, 0, false);
                    }
                    else if (num >= 19 && num <= 28)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5248 + num - 19, 1, false, 0, false);
                    }
                    else if (num >= 15 && num <= 18)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5247, 1, false, 0, false);
                    }
                    else if (num == 14)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5246, 1, false, 0, false);
                    }
                    else if (num == 13)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5086, 1, false, 0, false);
                    }
                    else if (num == 12)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4728, 1, false, 0, false);
                    }
                    else if (num == 11)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4727, 1, false, 0, false);
                    }
                    else if (num == 10)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4726, 1, false, 0, false);
                    }
                    else if (num == 9)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4659, 1, false, 0, false);
                    }
                    else if (num == 8)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4639, 1, false, 0, false);
                    }
                    else if (num == 7)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4638, 1, false, 0, false);
                    }
                    else if (num == 6)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1577, 1, false, 0, false);
                    }
                    else if (num == 5)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1495, 1, false, 0, false);
                    }
                    else
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1474 + num, 1, false, 0, false);
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrameImportant().