Terraria Decompiled: Terraria.WorldGen.CheckSuper
CheckSuper()
static void Terraria.WorldGen.CheckSuper (int x, int y, int type) inline static
Definition at line 46488 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            Tile tile = Main.tile[x, y];
            int num = 0;
            if (type == 376)
            {
                num = (int)(tile.frameX / 36);
            }
            if (type == 443)
            {
                num = (int)(tile.frameX / 36);
            }
            if (type == 485)
            {
                num = (int)(tile.frameX / 36);
            }
            bool flag = type == 376;
            bool flag2 = type == 443;
            bool flag3 = type == 444;
            bool flag4 = type == 485;
            TileObjectData tileData = TileObjectData.GetTileData(type, num, 0);
            bool styleHorizontal = tileData.StyleHorizontal;
            int width = tileData.Width;
            int height = tileData.Height;
            int num2 = x - (int)(tile.frameX / 18) % width;
            int num3 = y - (int)(tile.frameY / 18) % height;
            int num4 = 0;
            int num5 = 0;
            if (styleHorizontal)
            {
                num4 = (int)tile.frameX / tileData.CoordinateFullWidth;
            }
            else
            {
                num5 = (int)tile.frameY / tileData.CoordinateFullHeight;
            }
            bool flag5 = false;
            bool flag6 = false;
            for (int i = 0; i < width; i++)
            {
                for (int j = 0; j < height; j++)
                {
                    Tile tile2 = Framing.GetTileSafely(num2 + i, num3 + j);
                    if (!tile2.active() || (int)tile2.type != type || (int)tile2.frameX != num4 * tileData.CoordinateFullWidth + i * (tileData.CoordinateWidth + 2) || (int)tile2.frameY != num5 * tileData.CoordinateFullHeight + j * (tileData.CoordinateHeights[0] + 2))
                    {
                        flag5 = true;
                    }
                }
            }
            if (flag)
            {
                for (int k = 0; k < width; k++)
                {
                    Tile tile2 = Framing.GetTileSafely(num2 + k, num3 + height);
                    if (!tile2.active() || (!Main.tileSolid[(int)tile2.type] && !Main.tileTable[(int)tile2.type]))
                    {
                        flag5 = true;
                    }
                    if (tile2.halfBrick())
                    {
                        flag5 = true;
                    }
                }
            }
            if (flag2)
            {
                bool flag7 = true;
                bool flag8 = true;
                for (int l = 0; l < width; l++)
                {
                    if (!WorldGen.AnchorValid(Framing.GetTileSafely(num2 + l, num3 + height), AnchorType.SolidTile | AnchorType.SolidWithTop | AnchorType.SolidSide))
                    {
                        flag8 = false;
                    }
                    if (!WorldGen.AnchorValid(Framing.GetTileSafely(num2 + l, num3 - 1), AnchorType.SolidBottom))
                    {
                        flag7 = false;
                    }
                }
                if (!flag7 && !flag8)
                {
                    flag5 = true;
                }
                if (!flag5)
                {
                    int num6 = 0;
                    if (flag8)
                    {
                        for (int m = 0; m < width; m++)
{
                            Framing.GetTileSafely(num2 + m, num3).frameX = (short)(m * 18 + num / 2 * 36 + num6 * 36);
                        }
                    }
                    else
                    {
                        for (int n = 0; n < width; n++)
{
                            Framing.GetTileSafely(num2 + n, num3).frameX = (short)(n * 18 + (num - 2) / 2 * 36 + 72 + num6 * 36);
                        }
                    }
                }
            }
            if (flag3)
            {
                bool flag9 = true;
                for (int num7 = 0; num7 < width; num7++)
                {
                    if (!WorldGen.AnchorValid(Framing.GetTileSafely(num2 + num7, num3 - 1), AnchorType.SolidTile))
                    {
                        flag9 = false;
                    }
                }
                if (!flag9)
                {
                    flag5 = true;
                }
                for (int num8 = 0; num8 < width; num8++)
                {
                    for (int num9 = 0; num9 < height; num9++)
                    {
                        Tile tile2 = Framing.GetTileSafely(num2 + num8, num3 + num9);
                        if (tile2.liquid > 0)
{
                            flag5 = true;
                            flag6 = true;
                        }
                    }
                }
            }
            if (flag4)
            {
                bool flag10 = true;
                for (int num10 = 0; num10 < width; num10++)
                {
                    if (!WorldGen.AnchorValid(Framing.GetTileSafely(num2 + num10, num3 + height), AnchorType.SolidTile))
                    {
                        flag10 = false;
                    }
                }
                if (!flag10)
                {
                    flag5 = true;
                }
            }
            if (!flag5)
            {
                return;
            }
            WorldGen.destroyObject = true;
            for (int num11 = 0; num11 < width; num11++)
            {
                for (int num12 = 0; num12 < height; num12++)
                {
                    if ((int)Main.tile[num2 + num11, num3 + num12].type == type && Main.tile[num2 + num11, num3 + num12].active())
                    {
                        WorldGen.KillTile(num2 + num11, num3 + num12, false, false, false);
                    }
                }
            }
            int num13 = 0;
            if (type == 376)
            {
                switch (num)
                {
                case 0:
                    num13 = 2334;
                    break;
                case 1:
                    num13 = 2335;
                    break;
                case 2:
                    num13 = 2336;
                    break;
                case 3:
                    num13 = 3203;
                    break;
                case 4:
                    num13 = 3204;
                    break;
                case 5:
                    num13 = 3205;
                    break;
                case 6:
                    num13 = 3206;
                    break;
                case 7:
                    num13 = 3207;
                    break;
                case 8:
                    num13 = 3208;
                    break;
                case 9:
                    num13 = 3979;
                    break;
                case 10:
                    num13 = 3980;
                    break;
                case 11:
                    num13 = 3981;
                    break;
                case 12:
                    num13 = 3982;
                    break;
                case 13:
                    num13 = 3983;
                    break;
                case 14:
                    num13 = 3984;
                    break;
                case 15:
                    num13 = 3985;
                    break;
                case 16:
                    num13 = 3986;
                    break;
                case 17:
                    num13 = 3987;
                    break;
                case 18:
                    num13 = 4405;
                    break;
                case 19:
                    num13 = 4406;
                    break;
                case 20:
                    num13 = 4407;
                    break;
                case 21:
                    num13 = 4408;
                    break;
                case 22:
                    num13 = 4877;
                    break;
                case 23:
                    num13 = 4878;
                    break;
                case 24:
                    num13 = 5002;
                    break;
                case 25:
                    num13 = 5003;
                    break;
                }
            }
            if (type == 443)
            {
                num13 = 3722;
            }
            if (type == 485 && !WorldGen.isGeneratingOrLoadingWorld && Main.netMode != 1)
            {
                int availableAmountOfNPCsToSpawnUpToSlot = NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(1, 100);
                for (int num14 = 0; num14 < availableAmountOfNPCsToSpawnUpToSlot; num14++)
                {
                    int num15 = NPC.NewNPC(WorldGen.GetNPCSource_TileBreak(num2, num3), num2 * 16, num3 * 16 + 32, 582, 0, 0f, 0f, 0f, 0f, 255);
                    Main.npc[num15].TargetClosest(true);
                    Main.npc[num15].velocity = new Vector2((float)Main.npc[num15].direction * 1.5f, -5f);
                    Main.npc[num15].CanBeReplacedByOtherNPCs = true;
                    NetMessage.SendData(23, -1, -1, null, num15, 0f, 0f, 0f, 0, 0, 0);
                    int num16 = 20;
                    int num17 = -1;
                    Main.npc[num15].GetImmuneTime(num17, num16);
                    NetMessage.SendData(131, -1, -1, null, num15, 1f, (float)num17, (float)num16, 0, 0, 0);
                }
            }
            if (type == 444 && Main.netMode != 1 && !flag6)
            {
                Projectile.NewProjectile(WorldGen.GetProjectileSource_TileBreak(num2, num3), (float)(num2 * 16 + 16), (float)(num3 * 16 + 16), 0f, 0f, 655, 0, 0f, Main.myPlayer, 0f, 0f, 0f, null);
            }
            if (num13 != 0)
            {
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num2, num3), num2 * 16, num3 * 16, tileData.CoordinateFullWidth, tileData.CoordinateFullHeight, num13, 1, false, 0, false);
            }
            WorldGen.destroyObject = false;
            for (int num18 = -1; num18 < width + 1; num18++)
            {
                for (int num19 = -1; num19 < height + 1; num19++)
                {
                    WorldGen.TileFrame(num2 + num18, num3 + num19, false, false);
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AnchorValid(), Terraria.NPC.CanBeReplacedByOtherNPCs, Terraria.ObjectData.TileObjectData.CoordinateFullHeight, Terraria.ObjectData.TileObjectData.CoordinateFullWidth, Terraria.ObjectData.TileObjectData.CoordinateHeights, Terraria.ObjectData.TileObjectData.CoordinateWidth, Terraria.WorldGen.destroyObject, Terraria.Entity.direction, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.NPC.GetAvailableAmountOfNPCsToSpawnUpToSlot(), Terraria.NPC.GetImmuneTime(), Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.WorldGen.GetNPCSource_TileBreak(), Terraria.WorldGen.GetProjectileSource_TileBreak(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Terraria.Tile.halfBrick(), Terraria.ObjectData.TileObjectData.Height, int, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.ObjectData.TileObjectData.StyleHorizontal, Terraria.NPC.TargetClosest(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Main.tileSolid, Terraria.Main.tileTable, Terraria.Tile.type, Terraria.Entity.velocity, and Terraria.ObjectData.TileObjectData.Width.
Referenced by Terraria.WorldGen.TileFrameImportant().