Terraria Decompiled: Terraria.WorldGen.GrowLivingTree
GrowLivingTree()
static bool Terraria.WorldGen.GrowLivingTree (int i, int j, bool patch = false) inline static
Definition at line 25085 of file WorldGen.cs.
        {
            int num = 0;
            int[] array = new int[1000];
            int[] array2 = new int[1000];
            int[] array3 = new int[1000];
            int[] array4 = new int[1000];
            int num2 = 0;
            int[] array5 = new int[2000];
            int[] array6 = new int[2000];
            bool[] array7 = new bool[2000];
            if (WorldGen.skyblockWorldGen)
            {
                while (!Main.tile[i, j].active() && j < Main.maxTilesY - 1)
                {
                    j++;
                }
                if (j > Main.maxTilesY - 30)
                {
                    return false;
                }
                while (Main.tile[i, j].active())
                {
                    if (j <= 0)
                    {
                        break;
                    }
                    j--;
                }
            }
            else
            {
                if (!WorldGen.SolidTile(i, j + 1, false))
                {
                    return false;
                }
                if (Main.tile[i, j].active())
                {
                    return false;
                }
            }
            if (!WorldGen.SecretSeed.errorWorld.Enabled && !WorldGen.skyblockWorldGen && Main.tile[i, j + 1].type != 0 && Main.tile[i, j + 1].type != 2 && Main.tile[i, j + 1].type != 1 && Main.tile[i, j + 1].type != 40 && !TileID.Sets.Ore[(int)Main.tile[i, j + 1].type] && (!WorldGen.notTheBees || (Main.tile[i, j + 1].type != 60 && Main.tile[i, j + 1].type != 59)))
            {
                if (!WorldGen.notTheBees || !WorldGen.tenthAnniversaryWorldGen || WorldGen.drunkWorldGen)
                {
                    return false;
                }
                if (Main.tile[i, j + 1].type == 191 || Main.tile[i, j + 1].type == 192 || Main.tile[i, j + 1].type == 383 || Main.tile[i, j + 1].type == 384)
                {
                    return false;
                }
            }
            if (j < 150 && !WorldGen.skyblockWorldGen)
            {
                return false;
            }
            int num3 = i - WorldGen.genRand.Next(2, 3);
            int num4 = i + WorldGen.genRand.Next(2, 3);
            if (WorldGen.skyblockWorldGen)
            {
                num3--;
                num4++;
            }
            else if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
            {
                num3 -= WorldGen.genRand.Next(0, 3);
                num4 += WorldGen.genRand.Next(0, 3);
            }
            else if (WorldGen.notTheBees && !WorldGen.drunkWorldGen)
            {
                num3 -= WorldGen.genRand.Next(0, 2);
                num4 += WorldGen.genRand.Next(0, 2);
            }
            if (WorldGen.genRand.Next(5) == 0)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num3--;
                }
                else
                {
                    num4++;
                }
            }
            int num5 = num4 - num3;
            bool flag = num5 >= 4;
            int num6 = i - 50;
            int num7 = i + 50;
            if (patch)
            {
                num6 = i - 20;
                num7 = i + 20;
                num3 = i - WorldGen.genRand.Next(1, 3);
                num4 = i + WorldGen.genRand.Next(1, 3);
                if (WorldGen.notTheBees && !WorldGen.drunkWorldGen)
                {
                    num3 -= WorldGen.genRand.Next(0, 2);
                    num4 += WorldGen.genRand.Next(0, 2);
                }
                flag = num5 >= 4;
            }
            if (WorldGen.skyblockWorldGen)
            {
                flag = false;
            }
            if (!WorldGen.skyblockWorldGen)
            {
                int num8 = 5;
                if (WorldGen.SecretSeed.extraLivingTrees.Enabled || WorldGen.SecretSeed.extraFloatingIslands.Enabled)
                {
                    num8 = WorldGen.FindLowestCloud() + 1;
                }
                if (!WorldGen.SecretSeed.noSurface.Enabled)
                {
                    for (int k = num6; k <= num7; k++)
                    {
                        for (int l = num8; l < j - 5; l++)
{
                            if (Main.tile[k, l].active())
{
                                if (!patch)
{
                                    return false;
                                }
                                int type = (int)Main.tile[k, l].type;
                                if (type != 2 && type != 0 && type != 1 && type != 191 && type != 192 && type != 383 && type != 384)
{
                                    return false;
                                }
                            }
                        }
                    }
                }
            }
            Main.tileSolid[48] = false;
            int num9 = num3;
            int num10 = num4;
            int num11 = num3;
            int num12 = num4;
            int num13 = j;
            bool flag2 = true;
            int num14 = WorldGen.genRand.Next(-8, -4);
            int num15 = WorldGen.genRand.Next(2);
            int num16 = WorldGen.genRand.Next(5, 15);
            int num17 = 2;
            bool flag3 = false;
            if (!WorldGen.skyblockWorldGen && WorldGen.SecretSeed.extraLivingTrees.Enabled && num4 - num3 >= 7)
            {
                flag3 = true;
                num17 = 7;
            }
            while (flag2 && (WorldGen.skyblockWorldGen || !WorldGen.SecretSeed.extraLivingTrees.Enabled || (double)num13 >= Main.worldSurface || !WorldGen.AreAnyTilesInSetNearby((num3 + num4) / 2, num13 - 35, TileID.Sets.Clouds, 10)))
            {
                if (flag3)
                {
                    if (num13 < 130)
                    {
                        num17 = 1;
                    }
                    else if (num13 < 180)
                    {
                        num17 = 2;
                    }
                }
                num14++;
                if (num14 > num16)
                {
                    num16 = WorldGen.genRand.Next(5, 15);
                    num14 = 0;
                    array2[num] = num13 + WorldGen.genRand.Next(5);
                    if (WorldGen.genRand.Next(5) == 0)
                    {
                        if (num15 == 0)
{
                            num15 = 1;
                        }
                        else
{
                            num15 = 0;
                        }
                    }
                    if (num15 == 0)
                    {
                        array3[num] = -1;
                        array[num] = num3;
                        array4[num] = num4 - num3;
                        if (WorldGen.genRand.Next(num17) == 0)
{
                            num3++;
                            if (flag3)
{
                                num9++;
                            }
                            if (WorldGen.SecretSeed.extraLivingTrees.Enabled && !Main.wallDungeon[(int)Main.tile[num3, num13 + 1].wall])
{
                                Main.tile[num3, num13 + 1].active(true);
                                Main.tile[num3, num13 + 1].type = 191;
                                Main.tile[num3, num13 + 1].wall = 0;
                            }
                        }
                        if (!flag3)
{
                            num9++;
                        }
                        num15 = 1;
                    }
                    else
                    {
                        array3[num] = 1;
                        array[num] = num4;
                        array4[num] = num4 - num3;
                        if (WorldGen.genRand.Next(num17) == 0)
{
                            num4--;
                            if (flag3)
{
                                num10--;
                            }
                            if (WorldGen.SecretSeed.extraLivingTrees.Enabled && !Main.wallDungeon[(int)Main.tile[num3, num13 + 1].wall])
{
                                Main.tile[num4, num13 + 1].active(true);
                                Main.tile[num4, num13 + 1].type = 191;
                                Main.tile[num4, num13 + 1].wall = 0;
                            }
                        }
                        if (!flag3)
{
                            num10--;
                        }
                        num15 = 0;
                    }
                    if (num9 == num10)
                    {
                        flag2 = false;
                    }
                    num++;
                }
                for (int m = num3; m <= num4; m++)
                {
                    if (!WorldGen.skyblockWorldGen && WorldGen.SecretSeed.extraLivingTrees.Enabled && num4 - num3 > 2)
                    {
                        if (m == num3 || m == num4)
{
                            if (!Main.wallDungeon[(int)Main.tile[m, num13].wall])
{
                                Main.tile[m, num13].type = 191;
                                Main.tile[m, num13].active(true);
                                Main.tile[m, num13].halfBrick(false);
                            }
                        }
                        else if (!Main.wallDungeon[(int)Main.tile[m, num13].wall])
{
                            Main.tile[m, num13].wall = 244;
                            Main.tile[m, num13].active(false);
                            int num18 = 1;
                            while (!Main.tile[(num3 + num4) / 2, num13 + num18].active())
{
                                num18++;
                            }
                            if (num18 >= 6)
{
                                Main.tile[m, num13].active(false);
                                WorldGen.PlaceTile(m, num13, 19, true, false, -1, 23);
                            }
                        }
                    }
                    else if (!Main.wallDungeon[(int)Main.tile[m, num13].wall])
                    {
                        Main.tile[m, num13].type = 191;
                        Main.tile[m, num13].active(true);
                        Main.tile[m, num13].halfBrick(false);
                    }
                }
                num13--;
            }
            for (int n = 0; n < num - 1; n++)
            {
                int num19 = array[n] + array3[n];
                int num20 = array2[n];
                int num21 = (int)((double)array4[n] * (1.0 + (double)WorldGen.genRand.Next(20, 30) * 0.1));
                if (!Main.wallDungeon[(int)Main.tile[num19, num20 + 1].wall])
                {
                    Main.tile[num19, num20 + 1].type = 191;
                    Main.tile[num19, num20 + 1].active(true);
                    Main.tile[num19, num20 + 1].halfBrick(false);
                }
                int num22 = WorldGen.genRand.Next(3, 5);
                while (num21 > 0)
                {
                    num21--;
                    if (!Main.wallDungeon[(int)Main.tile[num19, num20].wall])
                    {
                        Main.tile[num19, num20].type = 191;
                        Main.tile[num19, num20].active(true);
                        Main.tile[num19, num20].halfBrick(false);
                    }
                    if (WorldGen.genRand.Next(10) == 0)
                    {
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num20--;
                        }
                        else
{
                            num20++;
                        }
                    }
                    else
                    {
                        num19 += array3[n];
                    }
                    if (num22 > 0)
                    {
                        num22--;
                    }
                    else if (WorldGen.genRand.Next(2) == 0)
                    {
                        num22 = WorldGen.genRand.Next(2, 5);
                        if (!Main.wallDungeon[(int)Main.tile[num19, num20].wall])
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                Main.tile[num19, num20].type = 191;
                                Main.tile[num19, num20].active(true);
                                Main.tile[num19, num20].halfBrick(false);
                                Main.tile[num19, num20 - 1].type = 191;
                                Main.tile[num19, num20 - 1].active(true);
                                Main.tile[num19, num20 - 1].halfBrick(false);
                                array5[num2] = num19;
                                array6[num2] = num20;
                                num2++;
                            }
                            else
{
                                Main.tile[num19, num20].type = 191;
                                Main.tile[num19, num20].active(true);
                                Main.tile[num19, num20].halfBrick(false);
                                Main.tile[num19, num20 + 1].type = 191;
                                Main.tile[num19, num20 + 1].active(true);
                                Main.tile[num19, num20 + 1].halfBrick(false);
                                array5[num2] = num19;
                                array6[num2] = num20;
                                num2++;
                            }
                        }
                    }
                    if (num21 == 0)
                    {
                        array5[num2] = num19;
                        array6[num2] = num20;
                        num2++;
                    }
                }
            }
            int num23 = (num3 + num4) / 2;
            int num24 = num13;
            int num25 = WorldGen.genRand.Next(num5 * 3, num5 * 5);
            int num26 = 0;
            int num27 = 0;
            while (num25 > 0 && num24 >= 30)
            {
                if (!Main.wallDungeon[(int)Main.tile[num23, num24].wall])
                {
                    Main.tile[num23, num24].type = 191;
                    Main.tile[num23, num24].active(true);
                    Main.tile[num23, num24].halfBrick(false);
                }
                if (num26 > 0)
                {
                    num26--;
                }
                if (num27 > 0)
                {
                    num27--;
                }
                for (int num28 = -1; num28 < 2; num28++)
                {
                    if (num28 != 0 && ((num28 < 0 && num26 == 0) || (num28 > 0 && num27 == 0)) && WorldGen.genRand.Next(2) == 0)
                    {
                        int num29 = num23;
                        int num30 = num24;
                        int num31 = WorldGen.genRand.Next(num5, num5 * 3);
                        if (num28 < 0)
{
                            num26 = WorldGen.genRand.Next(3, 5);
                        }
                        if (num28 > 0)
{
                            num27 = WorldGen.genRand.Next(3, 5);
                        }
                        int num32 = 0;
                        while (num31 > 0)
{
                            num31--;
                            num29 += num28;
                            if (!Main.wallDungeon[(int)Main.tile[num29, num30].wall])
{
                                Main.tile[num29, num30].type = 191;
                                Main.tile[num29, num30].active(true);
                                Main.tile[num29, num30].halfBrick(false);
                            }
                            if (num31 == 0)
{
                                array5[num2] = num29;
                                array6[num2] = num30;
                                array7[num2] = true;
                                num2++;
                            }
                            if (WorldGen.genRand.Next(5) == 0)
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    num30--;
                                }
                                else
{
                                    num30++;
                                }
                                if (!Main.wallDungeon[(int)Main.tile[num29, num30].wall])
{
                                    Main.tile[num29, num30].type = 191;
                                    Main.tile[num29, num30].active(true);
                                    Main.tile[num29, num30].halfBrick(false);
                                }
                            }
                            if (num32 > 0)
{
                                num32--;
                            }
                            else if (WorldGen.genRand.Next(3) == 0)
{
                                num32 = WorldGen.genRand.Next(2, 4);
                                int num33 = num29;
                                int num34 = num30;
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    num34--;
                                }
                                else
{
                                    num34++;
                                }
                                if (!Main.wallDungeon[(int)Main.tile[num33, num34].wall])
{
                                    Main.tile[num33, num34].type = 191;
                                    Main.tile[num33, num34].active(true);
                                    Main.tile[num33, num34].halfBrick(false);
                                }
                                array5[num2] = num33;
                                array6[num2] = num34;
                                array7[num2] = true;
                                num2++;
                                array5[num2] = num33 + WorldGen.genRand.Next(-5, 6);
                                array6[num2] = num34 + WorldGen.genRand.Next(-5, 6);
                                array7[num2] = true;
                                num2++;
                            }
                        }
                    }
                }
                array5[num2] = num23;
                array6[num2] = num24;
                num2++;
                if (WorldGen.genRand.Next(4) == 0)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num23--;
                    }
                    else
                    {
                        num23++;
                    }
                    if (!Main.wallDungeon[(int)Main.tile[num23, num24].wall])
                    {
                        Main.tile[num23, num24].type = 191;
                        Main.tile[num23, num24].active(true);
                        Main.tile[num23, num24].halfBrick(false);
                    }
                }
                num24--;
                num25--;
            }
            for (int num35 = num11; num35 <= num12; num35++)
            {
                int num36 = WorldGen.genRand.Next(1, 6);
                int num37 = j + 1;
                while (num36 > 0)
                {
                    if (WorldGen.SolidTile(num35, num37, false))
                    {
                        num36--;
                    }
                    Main.tile[num35, num37].type = 191;
                    Main.tile[num35, num37].active(true);
                    Main.tile[num35, num37].halfBrick(false);
                    num37++;
                }
                int num38 = num37;
                int num39 = WorldGen.genRand.Next(2, num5 + 1);
                for (int num40 = 0; num40 < num39; num40++)
                {
                    num37 = num38;
                    int num41 = (num11 + num12) / 2;
                    int num42 = 1;
                    int num43;
                    if (num35 < num41)
                    {
                        num43 = -1;
                    }
                    else
                    {
                        num43 = 1;
                    }
                    if (num35 == num41 || (num5 > 6 && (num35 == num41 - 1 || num35 == num41 + 1)))
                    {
                        num43 = 0;
                    }
                    int num44 = num43;
                    int num45 = num35;
                    num36 = WorldGen.genRand.Next((int)((double)num5 * 3.5), num5 * 6);
                    while (num36 > 0)
                    {
                        num36--;
                        num45 += num43;
                        if (Main.tile[num45, num37].wall != 244)
{
                            Main.tile[num45, num37].type = 191;
                            Main.tile[num45, num37].active(true);
                            Main.tile[num45, num37].halfBrick(false);
                        }
                        num37 += num42;
                        if (Main.tile[num45, num37].wall != 244)
{
                            Main.tile[num45, num37].type = 191;
                            Main.tile[num45, num37].active(true);
                            Main.tile[num45, num37].halfBrick(false);
                        }
                        if (!Main.tile[num45, num37 + 1].active())
{
                            num43 = 0;
                            num42 = 1;
                        }
                        if (WorldGen.genRand.Next(3) == 0)
{
                            if (num44 < 0)
{
                                if (num43 == 0)
{
                                    num43 = -1;
                                }
                                else
{
                                    num43 = 0;
                                }
                            }
                            else if (num44 > 0)
{
                                if (num43 == 0)
{
                                    num43 = 1;
                                }
                                else
{
                                    num43 = 0;
                                }
                            }
                            else
{
                                num43 = WorldGen.genRand.Next(-1, 2);
                            }
                        }
                        if (WorldGen.genRand.Next(3) == 0)
{
                            if (num42 == 0)
{
                                num42 = 1;
                            }
                            else
{
                                num42 = 0;
                            }
                        }
                    }
                }
            }
            if (WorldGen.remixWorldGen)
            {
                num2 = 0;
            }
            for (int num46 = 0; num46 < num2; num46++)
            {
                int num47 = WorldGen.genRand.Next(5, 8);
                if (WorldGen.SecretSeed.errorWorld.Enabled)
                {
                    num47 = WorldGen.genRand.Next(3, 12);
                }
                num47 = (int)((double)num47 * (1.0 + (double)num5 * 0.05));
                if (array7[num46])
                {
                    num47 = WorldGen.genRand.Next(6, 12) + num5;
                }
                int num48 = array5[num46] - num47 * 2;
                int num49 = array5[num46] + num47 * 2;
                int num50 = array6[num46] - num47 * 2;
                int num51 = array6[num46] + num47 * 2;
                double num52 = 2.0 - (double)WorldGen.genRand.Next(5) * 0.1;
                for (int num53 = num48; num53 <= num49; num53++)
                {
                    for (int num54 = num50; num54 <= num51; num54++)
                    {
                        if (WorldGen.GrowLivingTree_CanPlaceLeaves(num53, num54))
{
                            if (array7[num46])
{
                                Vector2D vector2D = new Vector2D((double)array5[num46], (double)array6[num46]) - new Vector2D((double)num53, (double)num54);
                                if (vector2D.Length() < (double)num47 * 0.9)
{
                                    Main.tile[num53, num54].type = 192;
                                    Main.tile[num53, num54].active(true);
                                    Main.tile[num53, num54].halfBrick(false);
                                }
                                if (WorldGen.SecretSeed.extraLivingTrees.Enabled && vector2D.Length() < (double)num47 * 0.7)
{
                                    Main.tile[num53, num54].wall = 60;
                                }
                            }
                            else if ((double)Math.Abs(array5[num46] - num53) + (double)Math.Abs(array6[num46] - num54) * num52 < (double)num47)
{
                                Main.tile[num53, num54].type = 192;
                                Main.tile[num53, num54].active(true);
                                Main.tile[num53, num54].halfBrick(false);
                            }
                        }
                    }
                    if (WorldGen.genRand.Next(30) == 0)
                    {
                        int num55 = num50;
                        if (WorldGen.InWorld(num53, num55, 5) && !Main.tile[num53, num55].active())
{
                            while (!Main.tile[num53, num55 + 1].active() && num55 < num51)
{
                                num55++;
                            }
                            if (Main.tile[num53, num55 + 1].type == 192)
{
                                WorldGen.PlaceTile(num53, num55, 187, true, false, -1, WorldGen.genRand.Next(50, 52));
                            }
                        }
                    }
                    if (!array7[num46] && WorldGen.genRand.Next(15) == 0)
                    {
                        int num56 = num51;
                        int num57 = num56 + 100;
                        if (!Main.tile[num53, num56].active())
{
                            while (!Main.tile[num53, num56 + 1].active() && num56 < num57)
{
                                num56++;
                            }
                            if (Main.tile[num53, num56 + 1].type != 192)
{
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    WorldGen.PlaceTile(num53, num56, 187, true, false, -1, WorldGen.genRand.Next(47, 50));
                                }
                                else
{
                                    int num58 = WorldGen.genRand.Next(2);
                                    int num59 = 72;
                                    if (num58 == 1)
{
                                        num59 = WorldGen.genRand.Next(59, 62);
                                    }
                                    WorldGen.PlaceSmallPile(num53, num56, num59, num58, 185);
                                }
                            }
                        }
                    }
                }
            }
            if (flag)
            {
                bool flag4 = false;
                if (!WorldGen.skyblockWorldGen)
                {
                    int num60 = j;
                    int num61 = j + 20;
                    if (!flag4)
                    {
                        int num62 = num60;
                        while (num62 < num61 && (double)num62 < Main.worldSurface - 2.0)
{
                            for (int num63 = num11; num63 <= num12; num63++)
{
                                if (Main.tile[num63, num62].wall == 0 && !WorldGen.SolidTile(num63, num62, false))
{
                                    flag4 = true;
                                    break;
                                }
                            }
                            num62++;
                        }
                    }
                }
                if (!flag4)
                {
                    WorldGen.GrowLivingTree_MakePassage(j, num5, ref num11, ref num12, patch);
                }
            }
            Main.tileSolid[48] = true;
            return true;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.AreAnyTilesInSetNearby(), System.array, Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.extraFloatingIslands, Terraria.WorldGen.SecretSeed.extraLivingTrees, Terraria.WorldGen.FindLowestCloud(), Terraria.WorldGen.genRand, Terraria.WorldGen.GrowLivingTree_CanPlaceLeaves(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.Tile.halfBrick(), int, Terraria.WorldGen.InWorld(), ReLogic.Utilities.Vector2D.Length(), Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.notTheBees, Terraria.ID.TileID.Sets.Ore, Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses(), and Terraria.WorldGen.GenerateSkyBlockWorld().