Terraria Decompiled: Terraria.WorldGen.paintWall
paintWall()
static bool Terraria.WorldGen.paintWall (int x, int y, byte color, bool broadCast = false, bool paintEffects = true) inline static
Definition at line 42526 of file WorldGen.cs.
        {
            Tile tile = Main.tile[x, y];
            if (tile == null || tile.wall == 0)
            {
                return false;
            }
            byte b = tile.wallColor();
            if (b == color)
            {
                return false;
            }
            tile.wallColor(color);
            if (broadCast)
            {
                NetMessage.SendData(64, -1, -1, null, x, (float)y, (float)color, 0f, 0, 0, 0);
            }
            if (paintEffects)
            {
                WorldGen.paintEffect(x, y, color, b);
            }
            return true;
        }
References Terraria.WorldGen.paintEffect(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.WorldGen.AddWireFromPointToPoint(), Terraria.Player.ApplyPaint(), Terraria.WorldGen.Convert_ActuallyConvertWall(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateDungeonSquareHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.WorldGen.OreRunner(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump().