Terraria Decompiled: Terraria.WorldGen.CheckStalactite
CheckStalactite()
static void Terraria.WorldGen.CheckStalactite (int x, int j) inline static
Definition at line 36487 of file WorldGen.cs.
        {
            if (Main.tile[x, j] == null)
            {
                return;
            }
            int num = j;
            if (Main.tile[x, num].frameY == 72)
            {
                if (Main.tile[x, num - 1] == null)
                {
                    Main.tile[x, num - 1] = new Tile();
                }
                if (Main.tile[x, num] == null)
                {
                    Main.tile[x, num] = new Tile();
                }
                if (Main.tile[x, num + 1] == null)
                {
                    Main.tile[x, num + 1] = new Tile();
                }
                bool flag = false;
                if (!WorldGen.SolidTile(x, num - 1, false))
                {
                    flag = true;
                }
                if (!flag && !WorldGen.UpdateStalagtiteStyle(x, num))
                {
                    flag = true;
                }
                if (flag)
                {
                    WorldGen.destroyObject = true;
                    if (Main.tile[x, num].type == Main.tile[x, j].type)
                    {
                        WorldGen.KillTile(x, num, false, false, false);
                    }
                    WorldGen.destroyObject = false;
                    return;
                }
            }
            else if (Main.tile[x, num].frameY == 90)
            {
                if (Main.tile[x, num - 1] == null)
                {
                    Main.tile[x, num - 1] = new Tile();
                }
                if (Main.tile[x, num] == null)
                {
                    Main.tile[x, num] = new Tile();
                }
                if (Main.tile[x, num + 1] == null)
                {
                    Main.tile[x, num + 1] = new Tile();
                }
                bool flag2 = false;
                if (!WorldGen.SolidTile(x, num + 1, false))
                {
                    flag2 = true;
                }
                if (!flag2 && WorldGen.InvalidTileForPilesOrSpeleothems(x, num + 1))
                {
                    flag2 = true;
                }
                if (!flag2 && !WorldGen.UpdateStalagtiteStyle(x, num))
                {
                    flag2 = true;
                }
                if (flag2)
                {
                    WorldGen.destroyObject = true;
                    if (Main.tile[x, num].type == Main.tile[x, j].type)
                    {
                        WorldGen.KillTile(x, num, false, false, false);
                    }
                    WorldGen.destroyObject = false;
                    return;
                }
            }
            else if (Main.tile[x, num].frameY >= 36)
            {
                if (Main.tile[x, num].frameY == 54)
                {
                    num--;
                }
                if (Main.tile[x, num] == null)
                {
                    Main.tile[x, num] = new Tile();
                }
                if (Main.tile[x, num + 1] == null)
                {
                    Main.tile[x, num + 1] = new Tile();
                }
                if (Main.tile[x, num + 2] == null)
                {
                    Main.tile[x, num + 2] = new Tile();
                }
                bool flag3 = false;
                if (!WorldGen.SolidTile(x, num + 2, false))
                {
                    flag3 = true;
                }
                if (!Main.tile[x, num].active() || !Main.tile[x, num + 1].active() || Main.tile[x, num + 1].type != Main.tile[x, num].type)
                {
                    flag3 = true;
                }
                if (Main.tile[x, num + 1].frameX != Main.tile[x, num].frameX)
                {
                    flag3 = true;
                }
                if (!flag3 && WorldGen.InvalidTileForPilesOrSpeleothems(x, num + 2))
                {
                    flag3 = true;
                }
                if (!flag3 && !WorldGen.UpdateStalagtiteStyle(x, num))
                {
                    flag3 = true;
                }
                if (flag3)
                {
                    WorldGen.destroyObject = true;
                    if (Main.tile[x, num].type == Main.tile[x, j].type)
                    {
                        WorldGen.KillTile(x, num, false, false, false);
                    }
                    if (Main.tile[x, num + 1].type == Main.tile[x, j].type)
                    {
                        WorldGen.KillTile(x, num + 1, false, false, false);
                    }
                    WorldGen.destroyObject = false;
                    return;
                }
            }
            else
            {
                if (Main.tile[x, num].frameY == 18)
                {
                    num--;
                }
                if (Main.tile[x, num - 1] == null)
                {
                    Main.tile[x, num - 1] = new Tile();
                }
                if (Main.tile[x, num] == null)
                {
                    Main.tile[x, num] = new Tile();
                }
                if (Main.tile[x, num + 1] == null)
                {
                    Main.tile[x, num + 1] = new Tile();
                }
                bool flag4 = false;
                if (!WorldGen.SolidTile(x, num - 1, false))
                {
                    flag4 = true;
                }
                if (!Main.tile[x, num].active() || !Main.tile[x, num + 1].active() || Main.tile[x, num + 1].type != Main.tile[x, num].type)
                {
                    flag4 = true;
                }
                if (Main.tile[x, num + 1].frameX != Main.tile[x, num].frameX)
                {
                    flag4 = true;
                }
                if (!flag4 && !WorldGen.UpdateStalagtiteStyle(x, num))
                {
                    flag4 = true;
                }
                if (flag4)
                {
                    WorldGen.destroyObject = true;
                    if (Main.tile[x, num].type == Main.tile[x, j].type)
                    {
                        WorldGen.KillTile(x, num, false, false, false);
                    }
                    if (Main.tile[x, num + 1].type == Main.tile[x, j].type)
                    {
                        WorldGen.KillTile(x, num + 1, false, false, false);
                    }
                    WorldGen.destroyObject = false;
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.InvalidTileForPilesOrSpeleothems(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Tile.type, and Terraria.WorldGen.UpdateStalagtiteStyle().
Referenced by Terraria.WorldGen.PlaceTight(), and Terraria.WorldGen.TileFrameImportant().