Terraria Decompiled: Terraria.WorldGen.QuickFindHome
QuickFindHome()
static void Terraria.WorldGen.QuickFindHome (int npc) inline static
Definition at line 1479 of file WorldGen.cs.
        {
            bool flag = Main.tileSolid[379];
            Main.tileSolid[379] = true;
            if (Main.npc[npc].homeTileX > 10 && Main.npc[npc].homeTileY > 10 && Main.npc[npc].homeTileX < Main.maxTilesX - 10 && Main.npc[npc].homeTileY < Main.maxTilesY)
            {
                WorldGen.canSpawn = false;
                WorldGen.StartRoomCheck(Main.npc[npc].homeTileX, Main.npc[npc].homeTileY - 1, null);
                if (!WorldGen.canSpawn)
                {
                    for (int i = Main.npc[npc].homeTileX - 1; i < Main.npc[npc].homeTileX + 2; i++)
                    {
                        int num = Main.npc[npc].homeTileY - 1;
                        while (num < Main.npc[npc].homeTileY + 2 && !WorldGen.StartRoomCheck(i, num, null))
{
                            num++;
                        }
                    }
                }
                if (!WorldGen.canSpawn)
                {
                    int num2 = 10;
                    for (int j = Main.npc[npc].homeTileX - num2; j <= Main.npc[npc].homeTileX + num2; j += 2)
                    {
                        int num3 = Main.npc[npc].homeTileY - num2;
                        while (num3 <= Main.npc[npc].homeTileY + num2 && !WorldGen.StartRoomCheck(j, num3, null))
{
                            num3 += 2;
                        }
                    }
                }
                if (!WorldGen.CheckSpecialTownNPCSpawningConditions(Main.npc[npc].type))
                {
                    WorldGen.canSpawn = false;
                }
                if (WorldGen.canSpawn)
                {
                    WorldGen.RoomNeeds();
                    if (WorldGen.canSpawn)
                    {
                        WorldGen.ScoreRoom(npc, Main.npc[npc].type, null);
                    }
                    if (WorldGen.canSpawn && WorldGen.hiScore > 0)
                    {
                        WorldGen.canSpawn = WorldGen.IsRoomConsideredOccupiedForNPCIndex(npc);
                    }
                    if (WorldGen.canSpawn && WorldGen.hiScore > 0)
                    {
                        Main.npc[npc].homeTileX = WorldGen.bestX;
                        Main.npc[npc].homeTileY = WorldGen.bestY;
                        Main.npc[npc].homeless = false;
                        Main.npc[npc].homelessDespawn = false;
                        AchievementsHelper.NotifyProgressionEvent(8);
                        WorldGen.canSpawn = false;
                    }
                    else
                    {
                        Main.npc[npc].homeless = true;
                    }
                }
                else
                {
                    Main.npc[npc].homeless = true;
                }
            }
            Main.tileSolid[379] = flag;
        }
References Terraria.WorldGen.bestX, Terraria.WorldGen.bestY, Terraria.WorldGen.canSpawn, Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.WorldGen.hiScore, Terraria.NPC.homeless, Terraria.NPC.homelessDespawn, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, Terraria.WorldGen.IsRoomConsideredOccupiedForNPCIndex(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.npc, Terraria.WorldGen.RoomNeeds(), Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.StartRoomCheck(), Terraria.Main.tileSolid, and Terraria.NPC.type.
Referenced by Terraria.NPC.AI_007_TownEntities_TeleportToHome(), Terraria.WorldGen.SpawnHomelessNPC(), and Terraria.Main.UpdateTime_SpawnTownNPCs().