Terraria Decompiled: Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections
CheckProjectilePressurePad_GetPossiblePlacementDirections()
static void Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections (int i, int j, out bool canUp, out bool canLeft, out bool canRight, out bool canDown) inline static private
Definition at line 87079 of file WorldGen.cs.
        {
            canUp = false;
            canLeft = false;
            canRight = false;
            canDown = false;
            Main.tile[i, j];
            Tile tile = Main.tile[i, j - 1];
            Tile tile2 = Main.tile[i, j + 1];
            Tile tile3 = Main.tile[i - 1, j];
            Tile tile4 = Main.tile[i + 1, j];
            Tile tile5 = Main.tile[i - 1, j + 1];
            Tile tile6 = Main.tile[i + 1, j + 1];
            Tile tile7 = Main.tile[i - 1, j - 1];
            Tile tile8 = Main.tile[i + 1, j - 1];
            int num = -1;
            int num2 = -1;
            int num3 = -1;
            int num4 = -1;
            int num5 = -1;
            int num6 = -1;
            int num7 = -1;
            int num8 = -1;
            if (tile != null && tile.nactive() && !tile.bottomSlope())
            {
                num2 = (int)tile.type;
            }
            if (tile2 != null && tile2.nactive() && !tile2.halfBrick() && !tile2.topSlope())
            {
                num = (int)tile2.type;
            }
            if (tile3 != null && tile3.nactive() && (tile3.slope() == 0 || tile3.slope() % 2 != 1))
            {
                num3 = (int)tile3.type;
            }
            if (tile4 != null && tile4.nactive() && (tile4.slope() == 0 || tile4.slope() % 2 != 0))
            {
                num4 = (int)tile4.type;
            }
            if (tile5 != null && tile5.nactive())
            {
                num5 = (int)tile5.type;
            }
            if (tile6 != null && tile6.nactive())
            {
                num6 = (int)tile6.type;
            }
            if (tile7 != null && tile7.nactive())
            {
                num7 = (int)tile7.type;
            }
            if (tile8 != null && tile8.nactive())
            {
                num8 = (int)tile8.type;
            }
            if (num >= 0 && Main.tileSolid[num] && (!Main.tileNoAttach[num] || TileID.Sets.Platforms[num]) && (tile2.bottomSlope() || tile2.slope() == 0) && !tile2.halfBrick())
            {
                canDown = true;
            }
            if (num2 >= 0 && Main.tileSolid[num2] && (!Main.tileNoAttach[num2] || (TileID.Sets.Platforms[num2] && tile.halfBrick())) && (tile.topSlope() || tile.slope() == 0 || tile.halfBrick()))
            {
                canUp = true;
            }
            if ((num3 >= 0 && Main.tileSolid[num3] && !Main.tileNoAttach[num3] && (tile3.leftSlope() || tile3.slope() == 0) && !tile3.halfBrick()) || (num3 >= 0 && TileID.Sets.IsBeam[num3]) || (WorldGen.IsTreeType(num3) && WorldGen.IsTreeType(num7) && WorldGen.IsTreeType(num5)))
            {
                canLeft = true;
            }
            if ((num4 >= 0 && Main.tileSolid[num4] && !Main.tileNoAttach[num4] && (tile4.rightSlope() || tile4.slope() == 0) && !tile4.halfBrick()) || (num4 >= 0 && TileID.Sets.IsBeam[num4]) || (WorldGen.IsTreeType(num4) && WorldGen.IsTreeType(num8) && WorldGen.IsTreeType(num6)))
            {
                canRight = true;
            }
        }
References Terraria.Tile.bottomSlope(), Terraria.Tile.halfBrick(), int, Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsTreeType(), Terraria.Tile.leftSlope(), Terraria.Tile.nactive(), Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.rightSlope(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CanPlaceProjectilePressurePad(), and Terraria.WorldGen.CheckProjectilePressurePad().