Terraria Decompiled: Terraria.WorldGen.SquareWallFrame
SquareWallFrame()
static void Terraria.WorldGen.SquareWallFrame (int i, int j, bool resetFrame = true) inline static
Definition at line 80844 of file WorldGen.cs.
        {
            Framing.WallFrame(i - 1, j - 1, false);
            Framing.WallFrame(i - 1, j, false);
            Framing.WallFrame(i - 1, j + 1, false);
            Framing.WallFrame(i, j - 1, false);
            Framing.WallFrame(i, j, resetFrame);
            Framing.WallFrame(i, j + 1, false);
            Framing.WallFrame(i + 1, j - 1, false);
            Framing.WallFrame(i + 1, j, false);
            Framing.WallFrame(i + 1, j + 1, false);
        }
References Terraria.Framing.WallFrame().
Referenced by Terraria.WorldBuilding.Actions.PlaceWall.Apply(), Terraria.GameContent.Biomes.DesertBiome.CleanupArea(), Terraria.WorldBuilding.WorldUtils.ClearWall(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.Convert_ActuallyConvertWall(), Terraria.WorldGen.DesertCloudIsland(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillWall(), Terraria.WorldGen.meteor(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.paintCoatWall(), Terraria.GameContent.Biomes.Desert.PitEntrance.PlaceAt(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceWall(), Terraria.WorldGen.Pyramid(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.WorldGen.ReplaceWall(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.SnowCloudIsland(), and Terraria.WorldGen.Spread.Spider().