Terraria Decompiled: Terraria.WorldGen.FloatingIsland
FloatingIsland()
static void Terraria.WorldGen.FloatingIsland (int i, int j) inline static
Definition at line 79513 of file WorldGen.cs.
        {
            double num = (double)WorldGen.genRand.Next(80, 120);
            double num2 = (double)WorldGen.genRand.Next(20, 25);
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            while (vector2D2.X > -2.0 && vector2D2.X < 2.0)
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            }
            vector2D2.Y = (double)WorldGen.genRand.Next(-20, -10) * 0.02;
            while (num > 0.0 && num2 > 0.0)
            {
                num -= (double)WorldGen.genRand.Next(4);
                num2 -= 1.0;
                int num3 = (int)(vector2D.X - num * 0.5);
                int num4 = (int)(vector2D.X + num * 0.5);
                int num5 = (int)(vector2D.Y - num * 0.5);
                int num6 = (int)(vector2D.Y + num * 0.5);
                if (num3 < 0)
                {
                    num3 = 0;
                }
                if (num4 > Main.maxTilesX)
                {
                    num4 = Main.maxTilesX;
                }
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesY)
                {
                    num6 = Main.maxTilesY;
                }
                double num7 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                double num8 = vector2D.Y + 1.0;
                for (int k = num3; k < num4; k++)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num8 += (double)WorldGen.genRand.Next(-1, 2);
                    }
                    if (num8 < vector2D.Y)
                    {
                        num8 = vector2D.Y;
                    }
                    if (num8 > vector2D.Y + 2.0)
                    {
                        num8 = vector2D.Y + 2.0;
                    }
                    for (int l = num5; l < num6; l++)
                    {
                        if ((double)l > num8)
{
                            double num9 = Math.Abs((double)k - vector2D.X);
                            double num10 = Math.Abs((double)l - vector2D.Y) * 2.0;
                            if (Math.Sqrt(num9 * num9 + num10 * num10) < num7 * 0.4)
{
                                Main.tile[k, l].active(true);
                                if (Main.tile[k, l].type == 59)
{
                                    Main.tile[k, l].type = 0;
                                }
                            }
                        }
                    }
                }
                num3 = (int)(vector2D.X - num * 0.4);
                num4 = (int)(vector2D.X + num * 0.4);
                num5 = (int)(vector2D.Y - num * 0.4);
                num6 = (int)(vector2D.Y + num * 0.4);
                if (num3 < 0)
                {
                    num3 = 0;
                }
                if (num4 > Main.maxTilesX)
                {
                    num4 = Main.maxTilesX;
                }
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesY)
                {
                    num6 = Main.maxTilesY;
                }
                num7 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                for (int m = num3; m < num4; m++)
                {
                    for (int n = num5; n < num6; n++)
                    {
                        if ((double)n > vector2D.Y + 2.0)
{
                            double num11 = Math.Abs((double)m - vector2D.X);
                            double num12 = Math.Abs((double)n - vector2D.Y) * 2.0;
                            if (Math.Sqrt(num11 * num11 + num12 * num12) < num7 * 0.4)
{
                                Main.tile[m, n].wall = 2;
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.Y += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                if (vector2D2.Y > 0.2)
                {
                    vector2D2.Y = -0.2;
                }
                if (vector2D2.Y < -0.2)
                {
                    vector2D2.Y = -0.2;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.