Terraria Decompiled: Terraria.WorldGen.SwitchMB
SwitchMB()
static void Terraria.WorldGen.SwitchMB (int i, int j) inline static
Definition at line 49442 of file WorldGen.cs.
        {
            int k;
            for (k = (int)(Main.tile[i, j].frameY / 18); k >= 2; k -= 2)
            {
            }
            int num = (int)(Main.tile[i, j].frameX / 18);
            if (num >= 2)
            {
                num -= 2;
            }
            int num2 = i - num;
            int num3 = j - k;
            for (int l = num2; l < num2 + 2; l++)
            {
                for (int m = num3; m < num3 + 2; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (Main.tile[l, m].active() && (Main.tile[l, m].type == 139 || Main.tile[l, m].type == 35))
                    {
                        if (Main.tile[l, m].frameX < 36)
{
                            Tile tile = Main.tile[l, m];
                            tile.frameX += 36;
                        }
                        else
{
                            Tile tile2 = Main.tile[l, m];
                            tile2.frameX -= 36;
                        }
                    }
                }
            }
            if (Wiring.running)
            {
                Wiring.SkipWire(num2, num3);
                Wiring.SkipWire(num2 + 1, num3);
                Wiring.SkipWire(num2, num3 + 1);
                Wiring.SkipWire(num2 + 1, num3 + 1);
            }
            NetMessage.SendTileSquare(-1, num2, num3, 2, 2, TileChangeType.None);
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Wiring.running, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Wiring.HitWireSingle(), Terraria.WorldGen.SkyblockIsland(), and Terraria.Player.TileInteractionsUse().