Terraria Decompiled: Terraria.WorldGen.CheckBamboo
CheckBamboo()
static void Terraria.WorldGen.CheckBamboo (int x, int y) inline static
Definition at line 57162 of file WorldGen.cs.
        {
            Tile tile = Main.tile[x, y + 1];
            if (tile == null)
            {
                return;
            }
            if (!tile.active() || (tile.type != 60 && tile.type != 571))
            {
                WorldGen.KillTile(x, y, false, false, false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                }
                WorldGen.SquareTileFrame(x, y, true);
                return;
            }
            Tile tile2 = Main.tile[x, y - 1];
            if (tile2 == null)
            {
                return;
            }
            Tile tile3 = Main.tile[x, y];
            if (tile3 == null)
            {
                return;
            }
            bool flag = tile2.active() && tile2.type == 571;
            bool flag2 = tile.active() && tile.type == 571;
            int num = (int)(tile3.frameX / 18);
            tile3.frameY = 0;
            if (flag)
            {
                if (flag2)
                {
                    if (num < 5 || num > 14)
                    {
                        tile3.frameX = (short)(WorldGen.genRand.Next(5, 15) * 18);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            return;
                        }
                    }
                }
                else if (num < 1 || num > 4)
                {
                    tile3.frameX = (short)(WorldGen.genRand.Next(1, 5) * 18);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                        return;
                    }
                }
            }
            else if (flag2)
            {
                if (num < 15 || num > 19)
                {
                    tile3.frameX = (short)(WorldGen.genRand.Next(15, 20) * 18);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                        return;
                    }
                }
            }
            else if (num != 0)
            {
                tile3.frameX = 0;
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.WorldGen.genRand, int, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().