Terraria Decompiled: Terraria.WorldGen.TownNPCPositionsCleanup
TownNPCPositionsCleanup()
static void Terraria.WorldGen.TownNPCPositionsCleanup (Point originalSpawnPoint) inline static private
Definition at line 21075 of file WorldGen.cs.
        {
            bool flag = originalSpawnPoint.X != Main.spawnTileX || originalSpawnPoint.Y != Main.spawnTileY;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                NPC npc = Main.npc[i];
                if (npc != null && npc.active && npc.isLikeATownNPC && npc.type != 37)
                {
                    Point point = npc.Bottom.ToTileCoordinates();
                    if (WorldGen.InWorld(point.X, point.Y, 2))
                    {
                        if (flag)
{
                            int num = point.X - originalSpawnPoint.X;
                            point = new Point(Main.spawnTileX + num, Main.spawnTileY);
                            npc.homeTileX = Main.spawnTileX;
                            npc.homeTileY = Main.spawnTileY;
                        }
                        bool flag2 = true;
                        bool flag3 = false;
                        WorldGen.Scan3By3(point.X, point.Y, out flag2, out flag3);
                        if (!flag2)
{
                            Point adjustedFloorPosition = WorldGen.GetAdjustedFloorPosition(point.X, point.Y);
                            npc.Bottom = adjustedFloorPosition.ToWorldCoordinates(8f, 0f);
                        }
                        else if (flag)
{
                            npc.Bottom = point.ToWorldCoordinates(8f, 0f);
                        }
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.Entity.Bottom, Terraria.WorldGen.GetAdjustedFloorPosition(), Terraria.WorldGen.InWorld(), Terraria.NPC.isLikeATownNPC, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.WorldGen.Scan3By3(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.NPC.type, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.