Terraria Decompiled: Terraria.WorldGen.RandomizeBackgrounds
RandomizeBackgrounds()
static void Terraria.WorldGen.RandomizeBackgrounds (UnifiedRandom random) inline static
Definition at line 3887 of file WorldGen.cs.
        {
            WorldGen.treeBG1 = WorldGen.RollRandomForestBGStyle(random);
            WorldGen.treeBG2 = WorldGen.RollRandomForestBGStyle(random);
            while (WorldGen.treeBG2 == WorldGen.treeBG1)
            {
                WorldGen.treeBG2 = WorldGen.RollRandomForestBGStyle(random);
            }
            WorldGen.treeBG3 = WorldGen.RollRandomForestBGStyle(random);
            while (WorldGen.treeBG3 == WorldGen.treeBG1 || WorldGen.treeBG3 == WorldGen.treeBG2)
            {
                WorldGen.treeBG3 = WorldGen.RollRandomForestBGStyle(random);
            }
            WorldGen.treeBG4 = WorldGen.RollRandomForestBGStyle(random);
            while (WorldGen.treeBG4 == WorldGen.treeBG1 || WorldGen.treeBG4 == WorldGen.treeBG2 || WorldGen.treeBG4 == WorldGen.treeBG3)
            {
                WorldGen.treeBG4 = WorldGen.RollRandomForestBGStyle(random);
            }
            WorldGen.setBG(0, WorldGen.treeBG1);
            WorldGen.setBG(10, WorldGen.treeBG2);
            WorldGen.setBG(11, WorldGen.treeBG3);
            WorldGen.setBG(12, WorldGen.treeBG4);
            WorldGen.setBG(1, WorldGen.RandomizeBackgrounds_Corruption(random));
            WorldGen.setBG(2, random.Next(7));
            WorldGen.snowBG = random.Next(9);
            if (WorldGen.snowBG == 2 && random.Next(2) == 0)
            {
                if (random.Next(2) == 0)
                {
                    WorldGen.snowBG = 21;
                }
                else
                {
                    WorldGen.snowBG = 22;
                }
            }
            if (WorldGen.snowBG == 3 && random.Next(2) == 0)
            {
                if (random.Next(2) == 0)
                {
                    WorldGen.snowBG = 31;
                }
                else
                {
                    WorldGen.snowBG = 32;
                }
            }
            if (WorldGen.snowBG == 4 && random.Next(2) == 0)
            {
                if (random.Next(2) == 0)
                {
                    WorldGen.snowBG = 41;
                }
                else
                {
                    WorldGen.snowBG = 42;
                }
            }
            WorldGen.setBG(3, WorldGen.snowBG);
            WorldGen.setBG(4, random.Next(6));
            WorldGen.setBG(5, random.Next(7));
            WorldGen.setBG(6, WorldGen.RandomizeBackgrounds_Desert(random));
            WorldGen.setBG(7, random.Next(8));
            WorldGen.setBG(8, random.Next(5));
            WorldGen.setBG(9, random.Next(3));
        }
References Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RandomizeBackgrounds_Corruption(), Terraria.WorldGen.RandomizeBackgrounds_Desert(), Terraria.WorldGen.RollRandomForestBGStyle(), Terraria.WorldGen.setBG(), Terraria.WorldGen.snowBG, Terraria.WorldGen.treeBG1, Terraria.WorldGen.treeBG2, Terraria.WorldGen.treeBG3, and Terraria.WorldGen.treeBG4.
Referenced by Terraria.Main.Initialize_AlmostEverything(), Terraria.WorldGen.Reset(), and Terraria.Main.UpdateMenu().