Terraria Decompiled: Terraria.WorldGen.GenerateWorld_SetupDungeonGenVars
GenerateWorld_SetupDungeonGenVars()
static void Terraria.WorldGen.GenerateWorld_SetupDungeonGenVars (int currentDungeon, bool clearOld = false) inline static
Definition at line 7056 of file WorldGen.cs.
        {
            if (clearOld)
            {
                GenVars.dungeonGenVars.Clear();
            }
            GenVars.CurrentDungeon = currentDungeon;
            GenVars.dungeonGenVars.Add(new DungeonGenVars());
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), and Terraria.WorldBuilding.GenVars.dungeonGenVars.
Referenced by Terraria.WorldGen.Reset().