Terraria Decompiled: Terraria.WorldGen.PaintTheSandRainbowAndSandWallsBlack
PaintTheSandRainbowAndSandWallsBlack()
static void Terraria.WorldGen.PaintTheSandRainbowAndSandWallsBlack () inline static private
Definition at line 21566 of file WorldGen.cs.
        {
            byte b = 25;
            for (int i = 20; i < Main.maxTilesX - 20; i++)
            {
                for (int j = 20; j < Main.maxTilesY - 20; j++)
                {
                    byte rainbowPaintIDForPosition = WorldGen.GetRainbowPaintIDForPosition(i, j, true);
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && (tile.type == 53 || tile.type == 396 || tile.type == 397))
                    {
                        tile.color(rainbowPaintIDForPosition);
                        if ((double)j > Main.worldSurface || tile.wall == 187 || tile.wall == 216)
{
                            if (Main.tile[i, j - 1].type == 165 || Main.tile[i, j - 1].type == 185 || Main.tile[i, j - 1].type == 186 || Main.tile[i, j - 1].type == 187)
{
                                Main.tile[i, j - 1].color(rainbowPaintIDForPosition);
                            }
                            if (Main.tile[i, j - 2].type == 165 || Main.tile[i, j - 2].type == 185 || Main.tile[i, j - 2].type == 186 || Main.tile[i, j - 2].type == 187)
{
                                Main.tile[i, j - 2].color(rainbowPaintIDForPosition);
                            }
                            if (Main.tile[i, j + 1].type == 165)
{
                                Main.tile[i, j + 1].color(rainbowPaintIDForPosition);
                            }
                            if (Main.tile[i, j + 2].type == 165)
{
                                Main.tile[i, j + 2].color(rainbowPaintIDForPosition);
                            }
                        }
                    }
                    if (tile.wall == 187 || tile.wall == 216)
                    {
                        tile.wallColor(b);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.WorldGen.GetRainbowPaintIDForPosition(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), and Terraria.Main.worldSurface.