Terraria Decompiled: Terraria.WorldGen.Check3x6
Check3x6()
static void Terraria.WorldGen.Check3x6 (int i, int j, int type) inline static
Definition at line 51941 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k = (int)(Main.tile[i, j].frameX / 18);
            int num = 0;
            while (k >= 3)
            {
                num++;
                k -= 3;
            }
            int num2 = i - k;
            int num3 = 54 * num;
            int num4 = (int)(Main.tile[i, j].frameY % 96 / 18);
            if (k >= 4)
            {
                k -= 3;
            }
            k = i - k;
            int num5 = j - num4;
            for (int l = k; l < k + 3; l++)
            {
                for (int m = num5; m < num5 + 6; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || (int)Main.tile[l, m].frameX != (l - num2) * 18 + num3 || (int)Main.tile[l, m].frameY != (m - num5) * 18)
                    {
                        flag = true;
                    }
                }
            }
            for (int n = k; n < k + 3; n++)
            {
                if (Main.tile[n, num5 + 6] == null)
                {
                    Main.tile[n, num5 + 6] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(n, num5 + 6))
                {
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int num6 = k; num6 < k + 3; num6++)
                {
                    for (int num7 = num5; num7 < num5 + 6; num7++)
                    {
                        if ((int)Main.tile[num6, num7].type == type && Main.tile[num6, num7].active())
{
                            WorldGen.KillTile(num6, num7, false, false, false);
                        }
                    }
                }
                if (type == 548)
                {
                    if (num >= 7)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4902 + num - 7, 1, false, 0, false);
                    }
                    else
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4435 + num, 1, false, 0, false);
                    }
                }
                if (type == 614)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4906, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                for (int num8 = k - 1; num8 < k + 4; num8++)
                {
                    for (int num9 = num5 - 1; num9 < num5 + 7; num9++)
                    {
                        WorldGen.TileFrame(num8, num9, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().