Terraria Decompiled: Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated
GeneratePlanteraBulbOnAllMechsDefeated()
static bool Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated () inline static
Definition at line 74595 of file WorldGen.cs.
        {
            bool flag = (double)Main.dungeonX > (double)Main.maxTilesX * 0.5;
            int num = (int)(flag ? ((double)Main.maxTilesX * 0.15) : ((double)Main.maxTilesX * 0.65));
            int num2 = (int)(flag ? ((double)Main.maxTilesX * 0.35) : ((double)Main.maxTilesX * 0.85));
            int num3 = (int)Main.worldSurface;
            int underworldLayer = Main.UnderworldLayer;
            int num4 = num2 - num;
            int num5 = underworldLayer - num3;
            Rectangle rectangle = new Rectangle(num, num3, num4, num5);
            int i = 2500;
            while (i > 0)
            {
                bool flag2 = i < 500;
                bool flag3 = i < 200;
                i--;
                Point point = new Point(rectangle.X + WorldGen.genRand.Next(rectangle.Width), rectangle.Y + WorldGen.genRand.Next(rectangle.Height));
                Tile tile = Main.tile[point.X, point.Y];
                int num6 = 500;
                bool flag4 = false;
                while (!flag4)
                {
                    num6--;
                    if (num6 <= 0)
                    {
                        flag4 = true;
                    }
                    point.Y--;
                    if (point.Y < rectangle.Y)
                    {
                        break;
                    }
                    tile = Main.tile[point.X, point.Y];
                    if (tile != null && (flag3 || tile.active()))
                    {
                        if (tile.type == 60)
{
                            flag4 = true;
                        }
                        else if (flag2 && tile.type == 59)
{
                            flag4 = true;
                        }
                    }
                }
                if (tile != null)
                {
                    bool flag5 = tile.active() || flag3;
                    bool flag6 = tile.type == 60 || (flag2 && tile.type == 59);
                    if (flag5 && flag6)
                    {
                        if (WorldGen.AttemptToGeneratePlanteraBulbAt(point.X, point.Y - 1, flag2))
{
                            return true;
                        }
                        if (WorldGen.AttemptToGeneratePlanteraBulbAt(point.X - 1, point.Y - 1, flag2))
{
                            return true;
                        }
                        if (WorldGen.AttemptToGeneratePlanteraBulbAt(point.X + 1, point.Y - 1, flag2))
{
                            return true;
                        }
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt(), Terraria.Main.dungeonX, Terraria.WorldGen.genRand, Microsoft.Xna.Framework.Rectangle.Height, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Microsoft.Xna.Framework.Rectangle.Width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.NPC.OnGameEventClearedForTheFirstTime().