Terraria Decompiled: Terraria.WorldGen.GetCommonTreeFoliageData
GetCommonTreeFoliageData()
static bool Terraria.WorldGen.GetCommonTreeFoliageData (int i, int j, int xoffset, ref int treeFrame, ref int treeStyle, out int floorY, out int topTextureFrameWidth, out int topTextureFrameHeight) inline static
Definition at line 61860 of file WorldGen.cs.
        {
            Main.tile[i, j];
            int num = i + xoffset;
            topTextureFrameWidth = 80;
            topTextureFrameHeight = 80;
            floorY = j;
            int k = 0;
            while (k < 100)
            {
                floorY = j + k;
                Tile tile = Main.tile[num, floorY];
                if (tile == null)
                {
                    return false;
                }
                ushort type = tile.type;
                if (type > 109)
                {
                    if (type <= 477)
                    {
                        if (type == 147)
{
                            treeStyle = 4;
                            int num2 = WorldGen.TreeTops.GetTreeStyle(6);
                            if (num2 == 0)
{
                                treeStyle = 12;
                                if (i % 10 == 0)
{
                                    treeStyle = 18;
                                }
                            }
                            if (num2 == 2 || num2 == 3 || num2 == 32 || num2 == 4 || num2 == 42 || num2 == 5 || num2 == 7)
{
                                if (num2 % 2 == 0)
{
                                    if (i < Main.maxTilesX / 2)
{
                                        treeStyle = 16;
                                    }
                                    else
{
                                        treeStyle = 17;
                                    }
                                }
                                else if (i > Main.maxTilesX / 2)
{
                                    treeStyle = 16;
                                }
                                else
{
                                    treeStyle = 17;
                                }
                            }
                            return true;
                        }
                        if (type != 199)
{
                            if (type != 477)
{
                                goto IL_02B5;
                            }
                            goto IL_00E4;
                        }
                    }
                    else
                    {
                        if (type == 492)
{
                            goto IL_0226;
                        }
                        if (type == 661)
{
                            goto IL_015E;
                        }
                        if (type != 662)
{
                            goto IL_02B5;
                        }
                    }
                    treeStyle = 5;
                    return true;
                }
                if (type <= 23)
                {
                    if (type == 2)
                    {
                        goto IL_00E4;
                    }
                    if (type == 23)
                    {
                        goto IL_015E;
                    }
                }
                else
                {
                    if (type == 60)
                    {
                        topTextureFrameHeight = 96;
                        topTextureFrameWidth = 114;
                        treeStyle = 2;
                        int num2 = WorldGen.TreeTops.GetTreeStyle(5);
                        if (num2 == 1)
{
                            treeStyle = 11;
                            topTextureFrameWidth = 116;
                        }
                        if ((double)floorY > Main.worldSurface)
{
                            treeStyle = 13;
                            topTextureFrameWidth = 116;
                        }
                        return true;
                    }
                    if (type == 70)
                    {
                        treeStyle = 14;
                        return true;
                    }
                    if (type == 109)
                    {
                        goto IL_0226;
                    }
                }
                IL_02B5:
                k++;
                continue;
                IL_00E4:
                int num3;
                if (num <= Main.treeX[0])
                {
                    num3 = WorldGen.TreeTops.GetTreeStyle(0);
                }
                else if (num <= Main.treeX[1])
                {
                    num3 = WorldGen.TreeTops.GetTreeStyle(1);
                }
                else if (num <= Main.treeX[2])
                {
                    num3 = WorldGen.TreeTops.GetTreeStyle(2);
                }
                else
                {
                    num3 = WorldGen.TreeTops.GetTreeStyle(3);
                }
                if (num3 == 0)
                {
                    treeStyle = 0;
                }
                else if (num3 == 5)
                {
                    treeStyle = 10;
                }
                else
                {
                    treeStyle = 5 + num3;
                }
                return true;
                IL_015E:
                treeStyle = 1;
                return true;
                IL_0226:
                topTextureFrameHeight = 140;
                int hollowTreeFoliageStyle = WorldGen.GetHollowTreeFoliageStyle();
                treeStyle = hollowTreeFoliageStyle;
                if (hollowTreeFoliageStyle == 19)
                {
                    topTextureFrameWidth = 120;
                }
                if (hollowTreeFoliageStyle == 20)
                {
                    treeStyle = 20;
                    if (i % 6 == 1)
                    {
                        treeFrame += 3;
                    }
                    else if (i % 6 == 2)
                    {
                        treeFrame += 6;
                    }
                    else if (i % 6 == 3)
                    {
                        treeFrame += 9;
                    }
                    else if (i % 6 == 4)
                    {
                        treeFrame += 12;
                    }
                    else if (i % 6 == 5)
                    {
                        treeFrame += 15;
                    }
                }
                else if (i % 3 == 1)
                {
                    treeFrame += 3;
                }
                else if (i % 3 == 2)
                {
                    treeFrame += 6;
                }
                return true;
            }
            return false;
        }
References Terraria.WorldGen.GetHollowTreeFoliageStyle(), Terraria.GameContent.TreeTopsInfo.GetTreeStyle(), Terraria.Main.maxTilesX, Terraria.Main.tile, Terraria.WorldGen.TreeTops, Terraria.Main.treeX, Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), and Terraria.GameContent.Drawing.TileDrawing.MakeExtraPreparations().