Terraria Decompiled: Terraria.WorldGen.UpdateWorld_GrassGrowth
UpdateWorld_GrassGrowth()
static void Terraria.WorldGen.UpdateWorld_GrassGrowth (int i, int j, int minI, int maxI, int minJ, int maxJ, bool underground) inline static private
Definition at line 74749 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(i, j, 10))
            {
                return;
            }
            if (underground)
            {
                int type = (int)Main.tile[i, j].type;
                int num = -1;
                int num2 = -1;
                int num3 = -1;
                int num4 = 1;
                int num5 = type;
                int num6 = -1;
                if (type <= 199)
                {
                    if (type <= 60)
                    {
                        if (type != 23)
{
                            if (type == 60)
{
                                num = 59;
                                num3 = 61;
                                num4 = 10;
                            }
                        }
                        else
{
                            num = 0;
                            num2 = 59;
                            num5 = 23;
                            num6 = 661;
                            num3 = 24;
                            num4 = 2;
                            if (!WorldGen.AllowedToSpreadInfections)
{
                                return;
                            }
                        }
                    }
                    else if (type != 70)
                    {
                        if (type == 199)
{
                            num = 0;
                            num2 = 59;
                            num5 = 199;
                            num6 = 662;
                            num3 = 201;
                            num4 = 2;
                            if (!WorldGen.AllowedToSpreadInfections)
{
                                return;
                            }
                        }
                    }
                    else
                    {
                        num = 59;
                        num3 = 71;
                        num4 = 10;
                    }
                }
                else if (type <= 633)
                {
                    if (type != 226)
                    {
                        if (type == 633)
{
                            num = 57;
                            num3 = 637;
                            num4 = 2;
                        }
                    }
                    else
                    {
                        num = -1;
                        num3 = 61;
                        num4 = 10;
                    }
                }
                else if (type != 661)
                {
                    if (type == 662)
                    {
                        num = 59;
                        num2 = 0;
                        num5 = 662;
                        num6 = 199;
                        num3 = 201;
                        num4 = 2;
                        if (!WorldGen.AllowedToSpreadInfections)
{
                            return;
                        }
                    }
                }
                else
                {
                    num = 59;
                    num2 = 0;
                    num5 = 661;
                    num6 = 23;
                    num3 = 24;
                    num4 = 2;
                    if (!WorldGen.AllowedToSpreadInfections)
                    {
                        return;
                    }
                }
                bool flag = false;
                if (num3 != -1 && !Main.tile[i, minJ].active() && WorldGen.genRand.Next(num4) == 0)
                {
                    bool flag2 = true;
                    if (type == 226 && WorldGen.TooManyJunglePlantsNearby(i, minJ, 2))
                    {
                        flag2 = false;
                    }
                    if (flag2)
                    {
                        flag = true;
                        WorldGen.PlaceTile(i, minJ, num3, true, false, -1, 0);
                        if (Main.tile[i, minJ].active() && (int)Main.tile[i, minJ].type == num3)
{
                            Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                            if (Main.netMode == 2 && Main.tile[i, minJ].active())
{
                                NetMessage.SendTileSquare(-1, i, minJ, TileChangeType.None);
                            }
                        }
                    }
                }
                if (num != -1)
                {
                    bool flag3 = false;
                    TileColorCache tileColorCache = Main.tile[i, j].BlockColorAndCoating();
                    for (int k = minI; k < maxI; k++)
                    {
                        for (int l = minJ; l < maxJ; l++)
{
                            if (WorldGen.InWorld(k, l, 10) && (i != k || j != l) && Main.tile[k, l].active())
{
                                if ((int)Main.tile[k, l].type == num)
{
                                    WorldGen.SpreadGrass(k, l, num, num5, false, tileColorCache);
                                    if ((int)Main.tile[k, l].type == num5)
{
                                        WorldGen.SquareTileFrame(k, l, true);
                                        flag3 = true;
                                    }
                                }
                                else if (num2 > -1 && num6 > -1 && (int)Main.tile[k, l].type == num2)
{
                                    WorldGen.SpreadGrass(k, l, num2, num6, false, tileColorCache);
                                    if ((int)Main.tile[k, l].type == num6)
{
                                        WorldGen.SquareTileFrame(k, l, true);
                                        flag3 = true;
                                    }
                                }
                            }
                        }
                    }
                    if (Main.netMode == 2 && flag3)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                    }
                }
                if (type == 60)
                {
                    if (!flag && WorldGen.genRand.Next(25) == 0 && Main.tile[i, minJ].liquid == 0)
                    {
                        if (Main.hardMode && NPC.downedMechBoss1 && NPC.downedMechBoss2 && NPC.downedMechBoss3 && WorldGen.genRand.Next(60) == 0)
{
                            bool flag4 = true;
                            int num7 = 150;
                            for (int m = i - num7; m < i + num7; m += 2)
{
                                for (int n = j - num7; n < j + num7; n += 2)
{
                                    if (m > 1 && m < Main.maxTilesX - 2 && n > 1 && n < Main.maxTilesY - 2 && Main.tile[m, n].active() && Main.tile[m, n].type == 238)
{
                                        flag4 = false;
                                        break;
                                    }
                                }
                            }
                            if (flag4)
{
                                WorldGen.PlaceJunglePlant(i, minJ, 238, 0, 0, true);
                                WorldGen.SquareTileFrame(i, minJ, true);
                                WorldGen.SquareTileFrame(i + 2, minJ, true);
                                WorldGen.SquareTileFrame(i - 1, minJ, true);
                                if (Main.tile[i, minJ].type == 238 && Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, minJ, 5, TileChangeType.None);
                                }
                            }
                        }
                        int num8 = (Main.expertMode ? 30 : 40);
                        if (Main.hardMode && NPC.downedMechBossAny && WorldGen.genRand.Next(num8) == 0)
{
                            bool flag5 = true;
                            int num9 = 60;
                            if (Main.expertMode)
{
                                num9 -= 10;
                            }
                            for (int num10 = i - num9; num10 < i + num9; num10 += 2)
{
                                for (int num11 = j - num9; num11 < j + num9; num11 += 2)
{
                                    if (num10 > 1 && num10 < Main.maxTilesX - 2 && num11 > 1 && num11 < Main.maxTilesY - 2 && Main.tile[num10, num11].active() && Main.tile[num10, num11].type == 236)
{
                                        flag5 = false;
                                        break;
                                    }
                                }
                            }
                            if (flag5)
{
                                WorldGen.PlaceJunglePlant(i, minJ, 236, WorldGen.genRand.Next(3), 0, true);
                                WorldGen.SquareTileFrame(i, minJ, true);
                                WorldGen.SquareTileFrame(i + 1, minJ + 1, true);
                                if (Main.tile[i, minJ].type == 236 && Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, minJ, 4, TileChangeType.None);
                                    return;
                                }
                            }
                        }
                        else
{
                            WorldGen.PlaceJunglePlant(i, minJ, 233, WorldGen.genRand.Next(8), 0, true);
                            if (Main.tile[i, minJ].type == 233)
{
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, minJ, 4, TileChangeType.None);
                                    return;
                                }
                            }
                            else
{
                                WorldGen.PlaceJunglePlant(i, minJ, 233, WorldGen.genRand.Next(12), 1, true);
                                if (Main.tile[i, minJ].type == 233 && Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, minJ, 3, TileChangeType.None);
                                    return;
                                }
                            }
                        }
                    }
                }
                else if (type == 70)
                {
                    if (Main.tile[i, j - 1].liquid > 0)
                    {
                        WorldGen.PlaceCatTail(i, j - 1);
                    }
                    if (WorldGen.genRand.Next(250) == 0 && WorldGen.TryGrowingTreeByType(5, i, j, 0, false) && WorldGen.PlayerLOS(i, j))
                    {
                        WorldGen.TreeGrowFXCheck(i, j - 1);
                        return;
                    }
                }
            }
            else
            {
                int num12 = (int)Main.tile[i, j].type;
                if (num12 == 2 || num12 == 23 || num12 == 32 || num12 == 109 || num12 == 199 || num12 == 352 || num12 == 477 || num12 == 492 || num12 == 661 || num12 == 662)
                {
                    if (Main.halloween && WorldGen.genRand.Next(75) == 0 && (num12 == 2 || num12 == 109))
                    {
                        int num13 = 100;
                        int num14 = 0;
                        for (int num15 = i - num13; num15 < i + num13; num15 += 2)
{
                            for (int num16 = j - num13; num16 < j + num13; num16 += 2)
{
                                if (num15 > 1 && num15 < Main.maxTilesX - 2 && num16 > 1 && num16 < Main.maxTilesY - 2 && Main.tile[num15, num16].active() && Main.tile[num15, num16].type == 254)
{
                                    num14++;
                                }
                            }
                        }
                        if (num14 < 6)
{
                            WorldGen.PlacePumpkin(i, minJ);
                            if (Main.netMode == 2 && Main.tile[i, minJ].type == 254)
{
                                NetMessage.SendTileSquare(-1, i - 1, minJ - 1, 2, 2, TileChangeType.None);
                            }
                        }
                    }
                    if (!Main.tile[i, minJ].active() && Main.tile[i, minJ].liquid == 0)
                    {
                        int num17 = -1;
                        if (num12 == 2 && WorldGen.genRand.Next(12) == 0)
{
                            num17 = 3;
                        }
                        else if (num12 == 23 && WorldGen.genRand.Next(10) == 0)
{
                            num17 = 24;
                        }
                        else if (num12 == 199 && WorldGen.genRand.Next(10) == 0)
{
                            num17 = 201;
                        }
                        else if (num12 == 661 && WorldGen.genRand.Next(10) == 0)
{
                            num17 = 24;
                        }
                        else if (num12 == 662 && WorldGen.genRand.Next(10) == 0)
{
                            num17 = 201;
                        }
                        else if (num12 == 109 && WorldGen.genRand.Next(10) == 0)
{
                            num17 = 110;
                        }
                        else if (num12 == 633 && WorldGen.genRand.Next(10) == 0)
{
                            num17 = 637;
                        }
                        if (num17 != -1)
{
                            WorldGen.PlaceTile(i, minJ, num17, true, false, -1, 0);
                            if (Main.tile[i, minJ].active() && (int)Main.tile[i, minJ].type == num17)
{
                                Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                                if (Main.netMode == 2 && Main.tile[i, minJ].active())
{
                                    NetMessage.SendTileSquare(-1, i, minJ, TileChangeType.None);
                                }
                            }
                        }
                    }
                    bool flag6 = false;
                    if (num12 == 32)
                    {
                        num12 = 23;
                        if (!WorldGen.AllowedToSpreadInfections)
{
                            return;
                        }
                    }
                    else if (num12 == 352)
                    {
                        num12 = 199;
                        if (!WorldGen.AllowedToSpreadInfections)
{
                            return;
                        }
                    }
                    else if (num12 == 477)
                    {
                        num12 = 2;
                    }
                    else if (num12 == 492)
                    {
                        num12 = 109;
                    }
                    int num18 = num12;
                    int num19 = -1;
                    if (num12 == 23 || num12 == 661)
                    {
                        num18 = 23;
                        num19 = 661;
                    }
                    if (num12 == 199 || num12 == 662)
                    {
                        num18 = 199;
                        num19 = 662;
                    }
                    bool flag7 = WorldGen.AllowedToSpreadInfections && (num12 == 23 || num12 == 199 || num12 == 109 || num12 == 492 || num12 == 661 || num12 == 662) && WorldGen.InWorld(i, j, 10);
                    for (int num20 = minI; num20 < maxI; num20++)
                    {
                        for (int num21 = minJ; num21 < maxJ; num21++)
{
                            if (WorldGen.InWorld(num20, num21, 10) && (i != num20 || j != num21) && Main.tile[num20, num21].active())
{
                                int type2 = (int)Main.tile[num20, num21].type;
                                if (flag7 || type2 == 0 || (num19 != -1 && type2 == 59))
{
                                    TileColorCache tileColorCache2 = Main.tile[i, j].BlockColorAndCoating();
                                    if (type2 == 0 || (num19 > -1 && type2 == 59) || ((num12 == 23 || num12 == 661 || num12 == 199 || num12 == 662) && (type2 == 2 || type2 == 109 || type2 == 477 || type2 == 492)))
{
                                        WorldGen.SpreadGrass(num20, num21, 0, num18, false, tileColorCache2);
                                        if (num19 > -1)
{
                                            WorldGen.SpreadGrass(num20, num21, 59, num19, false, tileColorCache2);
                                        }
                                        if (WorldGen.AllowedToSpreadInfections && (num12 == 23 || num12 == 199 || num12 == 661 || num12 == 662))
{
                                            WorldGen.SpreadGrass(num20, num21, 2, num18, false, tileColorCache2);
                                            WorldGen.SpreadGrass(num20, num21, 109, num18, false, tileColorCache2);
                                            WorldGen.SpreadGrass(num20, num21, 477, num18, false, tileColorCache2);
                                            WorldGen.SpreadGrass(num20, num21, 492, num18, false, tileColorCache2);
                                            if (num19 > -1)
{
                                                WorldGen.SpreadGrass(num20, num21, 60, num19, false, tileColorCache2);
                                            }
                                        }
                                        if ((int)Main.tile[num20, num21].type == num12 || (num19 > -1 && (int)Main.tile[num20, num21].type == num19))
{
                                            WorldGen.SquareTileFrame(num20, num21, true);
                                            flag6 = true;
                                        }
                                    }
                                    if (type2 == 0 || ((num12 == 109 || num12 == 492) && (type2 == 2 || type2 == 477 || type2 == 23 || type2 == 199)))
{
                                        WorldGen.SpreadGrass(num20, num21, 0, num18, false, tileColorCache2);
                                        if (num12 == 109)
{
                                            WorldGen.SpreadGrass(num20, num21, 2, num18, false, tileColorCache2);
                                        }
                                        if (num12 == 492)
{
                                            WorldGen.SpreadGrass(num20, num21, 477, num18, false, tileColorCache2);
                                        }
                                        else if (num12 == 109)
{
                                            WorldGen.SpreadGrass(num20, num21, 477, 492, false, tileColorCache2);
                                        }
                                        if ((num12 == 492 || num12 == 109) && WorldGen.AllowedToSpreadInfections)
{
                                            WorldGen.SpreadGrass(num20, num21, 23, 109, false, tileColorCache2);
                                        }
                                        if ((num12 == 492 || num12 == 109) && WorldGen.AllowedToSpreadInfections)
{
                                            WorldGen.SpreadGrass(num20, num21, 199, 109, false, tileColorCache2);
                                        }
                                        if ((int)Main.tile[num20, num21].type == num12)
{
                                            WorldGen.SquareTileFrame(num20, num21, true);
                                            flag6 = true;
                                        }
                                    }
                                }
                            }
                        }
                    }
                    if (Main.netMode == 2 && flag6)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                        return;
                    }
                }
                else if (num12 == 70)
                {
                    if (!Main.tile[i, j].inActive())
                    {
                        if (!Main.tile[i, minJ].active() && WorldGen.genRand.Next(10) == 0)
{
                            WorldGen.PlaceTile(i, minJ, 71, true, false, -1, 0);
                            if (Main.tile[i, minJ].active())
{
                                Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                            }
                            if (Main.netMode == 2 && Main.tile[i, minJ].active())
{
                                NetMessage.SendTileSquare(-1, i, minJ, TileChangeType.None);
                            }
                        }
                        if (WorldGen.genRand.Next(300) == 0)
{
                            bool flag8 = WorldGen.PlayerLOS(i, j);
                            if (WorldGen.TryGrowingTreeByType(5, i, j, 0, false) && flag8)
{
                                WorldGen.TreeGrowFXCheck(i, j - 1);
                            }
                        }
                    }
                    bool flag9 = false;
                    TileColorCache tileColorCache3 = Main.tile[i, j].BlockColorAndCoating();
                    for (int num22 = minI; num22 < maxI; num22++)
                    {
                        for (int num23 = minJ; num23 < maxJ; num23++)
{
                            if ((i != num22 || j != num23) && Main.tile[num22, num23].active() && Main.tile[num22, num23].type == 59)
{
                                WorldGen.SpreadGrass(num22, num23, 59, num12, false, tileColorCache3);
                                if ((int)Main.tile[num22, num23].type == num12)
{
                                    WorldGen.SquareTileFrame(num22, num23, true);
                                    flag9 = true;
                                }
                            }
                        }
                    }
                    if (Main.netMode == 2 && flag9)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                        return;
                    }
                }
                else if (num12 == 60)
                {
                    if (!Main.tile[i, minJ].active() && WorldGen.genRand.Next(7) == 0)
                    {
                        WorldGen.PlaceTile(i, minJ, 61, true, false, -1, 0);
                        if (Main.tile[i, minJ].active())
{
                            Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                        }
                        if (Main.netMode == 2 && Main.tile[i, minJ].active())
{
                            NetMessage.SendTileSquare(-1, i, minJ, TileChangeType.None);
                        }
                    }
                    else if (WorldGen.genRand.Next(500) == 0 && (!Main.tile[i, minJ].active() || Main.tile[i, minJ].type == 61 || Main.tile[i, minJ].type == 74 || Main.tile[i, minJ].type == 69))
                    {
                        if (WorldGen.TryGrowingTreeByType(5, i, j, 0, false) && WorldGen.PlayerLOS(i, j))
{
                            WorldGen.TreeGrowFXCheck(i, j - 1);
                        }
                    }
                    else if (WorldGen.genRand.Next(25) == 0 && Main.tile[i, minJ].liquid == 0)
                    {
                        WorldGen.PlaceJunglePlant(i, minJ, 233, WorldGen.genRand.Next(8), 0, true);
                        if (Main.tile[i, minJ].type == 233)
{
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, minJ, 4, TileChangeType.None);
                            }
                        }
                        else
{
                            WorldGen.PlaceJunglePlant(i, minJ, 233, WorldGen.genRand.Next(12), 1, true);
                            if (Main.tile[i, minJ].type == 233 && Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, minJ, 3, TileChangeType.None);
                            }
                        }
                    }
                    bool flag10 = false;
                    TileColorCache tileColorCache4 = Main.tile[i, j].BlockColorAndCoating();
                    for (int num24 = minI; num24 < maxI; num24++)
                    {
                        for (int num25 = minJ; num25 < maxJ; num25++)
{
                            if ((i != num24 || j != num25) && Main.tile[num24, num25].active() && Main.tile[num24, num25].type == 59)
{
                                WorldGen.SpreadGrass(num24, num25, 59, num12, false, tileColorCache4);
                                if ((int)Main.tile[num24, num25].type == num12)
{
                                    WorldGen.SquareTileFrame(num24, num25, true);
                                    flag10 = true;
                                }
                            }
                        }
                    }
                    if (Main.netMode == 2 && flag10)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                        return;
                    }
                }
                else if (num12 == 226)
                {
                    if (!Main.tile[i, minJ].active() && WorldGen.genRand.Next(7) == 0 && !WorldGen.TooManyJunglePlantsNearby(i, minJ, 2))
                    {
                        WorldGen.PlaceTile(i, minJ, 61, true, false, -1, 0);
                        if (Main.tile[i, minJ].active())
{
                            Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                        }
                        if (Main.netMode == 2 && Main.tile[i, minJ].active())
{
                            NetMessage.SendTileSquare(-1, i, minJ, TileChangeType.None);
                            return;
                        }
                    }
                }
                else if (num12 == 633)
                {
                    if (!Main.tile[i, minJ].active() && WorldGen.genRand.Next(10) == 0)
                    {
                        WorldGen.PlaceTile(i, minJ, 637, true, false, -1, 0);
                        if (Main.tile[i, minJ].active() && Main.tile[i, minJ].type == 637)
{
                            Main.tile[i, minJ].CopyPaintAndCoating(Main.tile[i, j]);
                        }
                        if (Main.netMode == 2 && Main.tile[i, minJ].active())
{
                            NetMessage.SendTileSquare(-1, i, minJ, TileChangeType.None);
                        }
                    }
                    TileColorCache tileColorCache5 = Main.tile[i, j].BlockColorAndCoating();
                    bool flag11 = false;
                    for (int num26 = minI; num26 < maxI; num26++)
                    {
                        for (int num27 = minJ; num27 < maxJ; num27++)
{
                            if ((i != num26 || j != num27) && Main.tile[num26, num27].active() && Main.tile[num26, num27].type == 57)
{
                                WorldGen.SpreadGrass(num26, num27, 57, num12, false, tileColorCache5);
                                if ((int)Main.tile[num26, num27].type == num12)
{
                                    WorldGen.SquareTileFrame(num26, num27, true);
                                    flag11 = true;
                                }
                            }
                        }
                    }
                    if (Main.netMode == 2 && flag11)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AllowedToSpreadInfections, Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.CopyPaintAndCoating(), Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedMechBossAny, Terraria.Main.expertMode, Terraria.WorldGen.genRand, Terraria.Main.halloween, Terraria.Main.hardMode, Terraria.Tile.inActive(), int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.WorldGen.PlacePumpkin(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlayerLOS(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.WorldGen.TooManyJunglePlantsNearby(), Terraria.WorldGen.TreeGrowFXCheck(), Terraria.WorldGen.TryGrowingTreeByType(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().