Terraria Decompiled: Terraria.WorldGen.SolidTile3
SolidTile3() [2/3]
static bool Terraria.WorldGen.SolidTile3 (Point p) inline static
Definition at line 70741 of file WorldGen.cs.
        {
            return WorldGen.SolidTile3(p.X, p.Y);
        }
References Terraria.WorldGen.SolidTile3(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_204_Digtoise(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.Player.DoEyebrellaRainEffect(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesertFinish(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.Collision.ExpandVertically(), Terraria.NPC.Spawner.GetProperGroundSpawnTileTypeAndWallType(), Terraria.WorldGen.isTileSurroundedBySolidTiles(), Terraria.StrayMethods.SendWalker(), Terraria.NPC.Spawner.SharkSpawnChance(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTile3(), Terraria.Player.UpdateBuffs(), Terraria.WorldGen.UpdateWorld(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), and Terraria.Player.VampireSeedSunlightExposure().