Terraria Decompiled: Terraria.WorldGen.Check6x3
Check6x3()
static void Terraria.WorldGen.Check6x3 (int i, int j, int type) inline static
Definition at line 48721 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int num = i + (int)(Main.tile[i, j].frameX / 18 * -1);
            int num2 = j + (int)(Main.tile[i, j].frameY / 18 * -1);
            for (int k = num; k < num + 6; k++)
            {
                for (int l = num2; l < num2 + 3; l++)
                {
                    int num3 = (k - num) * 18;
                    if (Main.tile[k, l] == null)
                    {
                        Main.tile[k, l] = new Tile();
                    }
                    if (!Main.tile[k, l].active() || (int)Main.tile[k, l].type != type || (int)Main.tile[k, l].frameX != num3 || (int)Main.tile[k, l].frameY != (l - num2) * 18)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[k, num2 + 3] == null)
                {
                    Main.tile[k, num2 + 3] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(k, num2 + 3) && (!Main.tile[k, num2 + 3].nactive() || !Main.tileSolidTop[(int)Main.tile[k, num2 + 3].type] || Main.tile[k, num2 + 3].frameY != 0))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int m = num; m < num + 6; m++)
                {
                    for (int n = num2; n < num2 + 3; n++)
                    {
                        if ((int)Main.tile[m, n].type == type && Main.tile[m, n].active())
{
                            WorldGen.KillTile(m, n, false, false, false);
                        }
                    }
                }
                if (type == 275)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2162, 1, false, 0, false);
                }
                if (type == 413)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3565, 1, false, 0, false);
                }
                if (type == 414)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3566, 1, false, 0, false);
                }
                if (type == 276)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2163, 1, false, 0, false);
                }
                if (type == 277)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2164, 1, false, 0, false);
                }
                if (type == 278)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2165, 1, false, 0, false);
                }
                if (type == 279)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2166, 1, false, 0, false);
                }
                if (type == 280)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2167, 1, false, 0, false);
                }
                if (type == 281)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2168, 1, false, 0, false);
                }
                if (type == 296)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2186, 1, false, 0, false);
                }
                if (type == 297)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2187, 1, false, 0, false);
                }
                if (type == 309)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2206, 1, false, 0, false);
                }
                if (type == 358)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3070, 1, false, 0, false);
                }
                if (type == 359)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3071, 1, false, 0, false);
                }
                if (type == 542)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4396, 1, false, 0, false);
                }
                if (type == 550)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4461, 1, false, 0, false);
                }
                if (type == 551)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4462, 1, false, 0, false);
                }
                if (type == 553)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4473, 1, false, 0, false);
                }
                if (type == 554)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4474, 1, false, 0, false);
                }
                if (type == 558)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4481, 1, false, 0, false);
                }
                if (type == 559)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4483, 1, false, 0, false);
                }
                if (type == 599)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4882, 1, false, 0, false);
                }
                if (type == 600)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4883, 1, false, 0, false);
                }
                if (type == 601)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4884, 1, false, 0, false);
                }
                if (type == 602)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4885, 1, false, 0, false);
                }
                if (type == 603)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4886, 1, false, 0, false);
                }
                if (type == 604)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4887, 1, false, 0, false);
                }
                if (type == 605)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4888, 1, false, 0, false);
                }
                if (type == 606)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4889, 1, false, 0, false);
                }
                if (type == 607)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4890, 1, false, 0, false);
                }
                if (type == 608)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4891, 1, false, 0, false);
                }
                if (type == 609)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4892, 1, false, 0, false);
                }
                if (type == 610)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4893, 1, false, 0, false);
                }
                if (type == 611)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4894, 1, false, 0, false);
                }
                if (type == 612)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4895, 1, false, 0, false);
                }
                if (type == 632)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5213, 1, false, 0, false);
                }
                if (type == 640)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5301, 1, false, 0, false);
                }
                if (type == 643)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5314, 1, false, 0, false);
                }
                if (type == 644)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5315, 1, false, 0, false);
                }
                if (type == 645)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5316, 1, false, 0, false);
                }
                if (type == 710)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5512, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                for (int num4 = num - 1; num4 < num + 7; num4++)
                {
                    for (int num5 = num2 - 1; num5 < num2 + 4; num5++)
                    {
                        WorldGen.TileFrame(num4, num5, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().