Terraria Decompiled: Terraria.WorldGen.plantDye
plantDye()
static void Terraria.WorldGen.plantDye (int i, int j, bool exoticPlant = false) inline static
Definition at line 71579 of file WorldGen.cs.
        {
            UnifiedRandom unifiedRandom = (WorldGen.isGeneratingOrLoadingWorld ? WorldGen.genRand : Main.rand);
            if (Main.tile[i, j].active())
            {
                if (i < 95 || i > Main.maxTilesX - 95 || j < 95 || j > Main.maxTilesY - 95)
                {
                    return;
                }
                int num = 90;
                if (exoticPlant)
                {
                    num = 240;
                }
                if (((double)j < Main.worldSurface || WorldGen.remixWorldGen) && (!Main.tile[i, j - 1].active() || Main.tile[i, j - 1].type == 3 || Main.tile[i, j - 1].type == 51 || Main.tile[i, j - 1].type == 61 || Main.tile[i, j - 1].type == 73 || Main.tile[i, j - 1].type == 74 || Main.tile[i, j - 1].type == 184))
                {
                    int num2 = Utils.Clamp<int>(i - num, 1, Main.maxTilesX - 1 - 1);
                    int num3 = Utils.Clamp<int>(i + num, 1, Main.maxTilesX - 1 - 1);
                    int num4 = Utils.Clamp<int>(j - num, 1, Main.maxTilesY - 1 - 1);
                    int num5 = Utils.Clamp<int>(j + num, 1, Main.maxTilesY - 1 - 1);
                    for (int k = num2; k < num3; k++)
                    {
                        for (int l = num4; l < num5; l++)
{
                            if (Main.tile[k, l].active() && Main.tile[k, l].type == 227 && (!exoticPlant || Main.tile[k, l].frameX >= 272) && (exoticPlant || Main.tile[k, l].frameX < 272))
{
                                return;
                            }
                        }
                    }
                    if (exoticPlant)
                    {
                        int type = (int)Main.tile[i, j].type;
                        bool flag = TileID.Sets.Conversion.Grass[type] || TileID.Sets.Conversion.Moss[type] || type == 0;
                        if (Main.tile[i, j - 1].liquid > 0 && (Main.tile[i, j - 1].lava() || Main.tile[i, j - 1].honey()))
{
                            flag = false;
                        }
                        if (flag)
{
                            WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, WorldGen.genRand.Next(8, 12));
                        }
                    }
                    else if (Main.tile[i, j].type == 2 || Main.tile[i, j].type == 109)
                    {
                        if (unifiedRandom.Next(4) == 0)
{
                            WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 4);
                        }
                        else
{
                            WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 3);
                        }
                    }
                    else if (Main.tile[i, j].type == 60)
                    {
                        if (unifiedRandom.Next(2) == 0)
{
                            WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 2);
                        }
                        else
{
                            WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 4);
                        }
                    }
                    else if (Main.tile[i, j].type == 53 && Main.tile[i, j - 1].liquid == 255 && Main.tile[i, j - 2].liquid == 255)
                    {
                        WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 2);
                    }
                    else if (Main.tile[i, j].type == 80 && !Main.tile[i - 1, j - 1].active() && !Main.tile[i + 1, j - 1].active())
                    {
                        try
{
                            bool flag2 = true;
                            for (int m = i - 5; m <= i + 5; m++)
{
                                for (int n = j - 5; n <= j + 15; n++)
{
                                    if (Main.tile[m, n].active() && (Main.tile[m, n].type == 112 || Main.tile[m, n].type == 234))
{
                                        flag2 = false;
                                    }
                                }
                            }
                            if (flag2)
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 6);
                            }
                        }
                        catch
{
                        }
                    }
                }
                if (((double)j >= Main.worldSurface || WorldGen.remixWorldGen) && j < Main.UnderworldLayer)
                {
                    if (!Main.tile[i, j - 1].active() || Main.tile[i, j - 1].type == 3 || Main.tile[i, j - 1].type == 51 || Main.tile[i, j - 1].type == 61 || Main.tile[i, j - 1].type == 73 || Main.tile[i, j - 1].type == 74 || Main.tile[i, j - 1].type == 184)
                    {
                        int num6 = Utils.Clamp<int>(i - num, 1, Main.maxTilesX - 1 - 1);
                        int num7 = Utils.Clamp<int>(i + num, 1, Main.maxTilesX - 1 - 1);
                        int num8 = Utils.Clamp<int>(j - num, 1, Main.maxTilesY - 1 - 1);
                        int num9 = Utils.Clamp<int>(j + num, 1, Main.maxTilesY - 1 - 1);
                        for (int num10 = num6; num10 < num7; num10++)
{
                            for (int num11 = num8; num11 < num9; num11++)
{
                                if (Main.tile[num10, num11].active() && Main.tile[num10, num11].type == 227 && (!exoticPlant || Main.tile[num10, num11].frameX >= 272) && (exoticPlant || Main.tile[num10, num11].frameX < 272))
{
                                    return;
                                }
                            }
                        }
                        if (exoticPlant)
{
                            int type2 = (int)Main.tile[i, j].type;
                            if (TileID.Sets.Conversion.Grass[type2] || TileID.Sets.Conversion.Moss[type2] || type2 == 0)
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, WorldGen.genRand.Next(8, 12));
                            }
                        }
                        else if (Main.tile[i, j].type == 60)
{
                            if (unifiedRandom.Next(2) == 0)
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 2);
                            }
                            else if (unifiedRandom.Next(2) == 0)
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 0);
                            }
                            else
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 1);
                            }
                        }
                        else if (Main.tile[i, j].type == 0 || Main.tile[i, j].type == 1 || Main.tile[i, j].type == 59)
{
                            if (unifiedRandom.Next(2) == 0)
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 0);
                            }
                            else
{
                                WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 1);
                            }
                        }
                        else if (Main.tile[i, j - 1].liquid == 255 && Main.tile[i, j - 2].liquid == 255)
{
                            WorldGen.PlaceTile(i, j - 1, 227, true, false, -1, 5);
                        }
                    }
                    if (!Main.tile[i, j + 1].active() && !exoticPlant)
                    {
                        for (int num12 = i - num; num12 < i + num; num12++)
{
                            for (int num13 = j - num; num13 < j + num; num13++)
{
                                if (Main.tile[num12, num13].active() && Main.tile[num12, num13].type == 227)
{
                                    return;
                                }
                            }
                        }
                        if (Main.tile[i, j].type == 0)
{
                            WorldGen.PlaceTile(i, j + 1, 227, true, false, -1, 7);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.Tile.frameX, Terraria.WorldGen.genRand, Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.Tile.honey(), int, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Conversion.Moss, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Main.rand, Terraria.WorldGen.remixWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().