Terraria Decompiled: Terraria.WorldGen.GenerateSkyBlockWorld
GenerateSkyBlockWorld()
static void Terraria.WorldGen.GenerateSkyBlockWorld (GenerationProgress progress) inline static private
Definition at line 19619 of file WorldGen.cs.
        {
            bool flag = false;
            int num = Main.maxTilesX / 420;
            bool flag2 = false;
            int num2 = 0;
            int num3 = 7;
            if (flag || WorldGen.SecretSeed.extraLiquid.Enabled || WorldGen.SecretSeed.noInfection.Enabled || WorldGen.SecretSeed.surfaceIsDesert.Enabled || WorldGen.SecretSeed.worldIsFrozen.Enabled || WorldGen.SecretSeed.hallowOnTheSurface.Enabled || WorldGen.SecretSeed.worldIsInfected.Enabled || WorldGen.SecretSeed.surfaceIsMushrooms.Enabled)
            {
                flag2 = true;
                num3 += num;
            }
            float num4 = 1f / (float)num3;
            progress.Set(0.0);
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    Main.tile[i, j].active(false);
                    Main.tile[i, j].type = 0;
                }
            }
            progress.Set((double)((float)num2++ * num4));
            int num5;
            int num6;
            if (WorldGen.SecretSeed.randomSpawn.Enabled || Main.vampireSeed)
            {
                num5 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.2), (int)((double)Main.maxTilesX * 0.8));
                num6 = WorldGen.genRand.Next((int)(Main.worldSurface + 200.0), Main.maxTilesY - 400);
            }
            else if (WorldGen.remixWorldGen)
            {
                num5 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.45), (int)((double)Main.maxTilesX * 0.55));
                num6 = WorldGen.genRand.Next(Main.UnderworldLayer + 80, Main.UnderworldLayer + 120);
            }
            else if (WorldGen.SecretSeed.noSurface.Enabled)
            {
                num5 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.45), (int)((double)Main.maxTilesX * 0.55));
                num6 = WorldGen.genRand.Next((int)(Main.rockLayer * 0.3), (int)(Main.rockLayer * 0.8));
            }
            else if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled)
            {
                num5 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.45), (int)((double)Main.maxTilesX * 0.55));
                int num7 = (int)((double)Main.maxTilesY * 0.05);
                if (num7 < 100)
                {
                    num7 = 100;
                }
                int num8 = (int)((double)Main.maxTilesY * 0.08);
                if (num8 < 130)
                {
                    num8 = 130;
                }
                num6 = WorldGen.genRand.Next(num7, num8);
            }
            else
            {
                num5 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.45), (int)((double)Main.maxTilesX * 0.55));
                num6 = WorldGen.genRand.Next((int)(Main.worldSurface * 0.6), (int)(Main.worldSurface * 0.8));
            }
            progress.Set((double)((float)num2++ * num4));
            WorldGen.SkyblockIsland(num5, num6, 0, false);
            progress.Set((double)((float)num2++ * num4));
            bool flag3 = false;
            if (WorldGen.SecretSeed.teamBasedSpawns.Enabled)
            {
                flag3 = true;
                for (int k = 0; k < (int)PlayerTeamID.Count; k++)
                {
                    float num9 = (float)k / (float)PlayerTeamID.Count;
                    float num10 = 0.1f;
                    float num11 = 0.1f;
                    float num12;
                    if (num9 < 0.5f)
                    {
                        num12 = Utils.Remap(num9, 0f, 0.5f, num11, 0.5f - num10, true);
                    }
                    else
                    {
                        num12 = Utils.Remap(num9, 0.5f, 1f, 0.5f + num10, 1f - num11, true);
                    }
                    WorldGen.SkyblockIsland((int)((float)Main.maxTilesX * num12), num6 + WorldGen.genRand.Next(-30, 30), 13, false);
                }
            }
            progress.Set((double)((float)num2++ * num4));
            int num13;
            if (flag || WorldGen.Skyblock.spawnShimmerPool)
            {
                bool flag4 = false;
                for (int l = 200; l > 0; l--)
                {
                    num13 = num6 + WorldGen.genRand.Next(-50, 50);
                    if (l < 25)
                    {
                        num13 = 90 + WorldGen.genRand.Next(30);
                    }
                    int num14;
                    if (num5 < Main.maxTilesX / 2)
                    {
                        num14 = WorldGen.genRand.Next((int)((float)Main.maxTilesX * 0.7f), Main.maxTilesX - WorldGen.beachDistance - 200);
                    }
                    else
                    {
                        num14 = WorldGen.genRand.Next(WorldGen.beachDistance + 200, (int)((float)Main.maxTilesX * 0.3f));
                    }
                    num14 = (int)MathHelper.Clamp((float)num14, (float)(WorldGen.beachDistance + 200), (float)(Main.maxTilesX - WorldGen.beachDistance - 200));
                    num13 = (int)MathHelper.Clamp((float)num13, 80f, (float)(Main.maxTilesY - 80));
                    if (l < 100)
                    {
                        float num15 = WorldGen.genRand.NextFloat();
                        float num16 = 0.1f;
                        float num17 = 0.05f;
                        if (num15 < 0.5f)
{
                            num15 = Utils.Remap(num15, 0f, 0.5f, num17, 0.5f - num16, true);
                        }
                        else
{
                            num15 = Utils.Remap(num15, 0.5f, 1f, 0.5f + num16, 1f - num17, true);
                        }
                        num14 = (int)((float)Main.maxTilesX * num15);
                    }
                    if (WorldGen.SkyblockIsland(num14, num13, 1, flag3))
                    {
                        flag4 = true;
                        break;
                    }
                }
                if (!flag4)
                {
                    int num18;
                    if (num5 < Main.maxTilesX / 2)
                    {
                        num18 = WorldGen.genRand.Next((int)((float)Main.maxTilesX * 0.7f), Main.maxTilesX - WorldGen.beachDistance - 200);
                    }
                    else
                    {
                        num18 = WorldGen.genRand.Next(WorldGen.beachDistance + 200, (int)((float)Main.maxTilesX * 0.3f));
                    }
                    int num19 = 90;
                    WorldGen.SkyblockIsland(num18, num19, 1, false);
                }
                progress.Set((double)((float)num2++ * num4));
            }
            num13 = num6;
            while ((!Main.tile[num5, num13].active() || Main.tile[num5, num13].type != 0) && num13 < Main.maxTilesY - 1)
            {
                num13++;
            }
            if (num13 > Main.maxTilesY - 10)
            {
                num13 = 0;
                while (!Main.tile[num5, num13].active() && num13 < Main.maxTilesY)
                {
                    num13++;
                }
            }
            if (num13 > Main.maxTilesY - 10)
            {
                num13 = num6;
            }
            Main.spawnTileX = num5;
            Main.spawnTileY = num13;
            progress.Set((double)((float)num2++ * num4));
            int num20 = (int)Main.worldSurface;
            if (num20 < 200)
            {
                num20 = (int)(200.0 + Main.rockLayer / 2.0) / 2;
            }
            if (flag2)
            {
                for (int m = 0; m < num; m++)
                {
                    if (flag || WorldGen.SecretSeed.extraLiquid.Enabled)
                    {
                        if (m == 0)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 9, false);
                        }
                        else if (m == 1)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(num20 + 200, Main.maxTilesY - 70), 10, false);
                        }
                        else if (WorldGen.notTheBees && m == 2)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), 11, false);
                        }
                        else if (WorldGen.tenthAnniversaryWorldGen && WorldGen.drunkWorldGen && m == 3)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(num20 + 200, Main.UnderworldLayer - 100), 11, false);
                        }
                        else
{
                            int num21 = WorldGen.genRand.Next(4);
                            while ((num21 == 2 && !WorldGen.notTheBees) || (num21 == 3 && (!WorldGen.tenthAnniversaryWorldGen || !WorldGen.drunkWorldGen)))
{
                                num21 = WorldGen.genRand.Next(4);
                            }
                            int num22 = WorldGen.genRand.Next(100, Main.UnderworldLayer - 100);
                            if (num21 <= 1)
{
                                if ((double)num22 > (Main.rockLayer + (double)Main.UnderworldLayer) / 2.0)
{
                                    num21 = 1;
                                }
                                else
{
                                    num21 = 0;
                                }
                            }
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), num22, 9 + num21, false);
                        }
                    }
                    if (flag || WorldGen.SecretSeed.noInfection.Enabled)
                    {
                        if (m == 0)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 4, false);
                        }
                        else if (m <= num / 5 + 1)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(Main.UnderworldLayer + 30, Main.maxTilesY - 70), 4, false);
                        }
                        else
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.maxTilesY - 100), 4, false);
                        }
                    }
                    if (flag || WorldGen.SecretSeed.surfaceIsDesert.Enabled)
                    {
                        if (m == 0)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 3, false);
                        }
                        else
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), 3, false);
                        }
                    }
                    if (flag || WorldGen.SecretSeed.worldIsFrozen.Enabled)
                    {
                        if (m == 0)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 2, false);
                        }
                        else
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), 2, false);
                        }
                    }
                    if (flag || WorldGen.SecretSeed.hallowOnTheSurface.Enabled)
                    {
                        if (m == 0)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 5, false);
                        }
                        else
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), 5, false);
                        }
                    }
                    if (flag || WorldGen.SecretSeed.worldIsInfected.Enabled)
                    {
                        if (m == 0)
{
                            if (Main.drunkWorld)
{
                                WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), WorldGen.genRand.Next(6, 8), false);
                            }
                            else if (WorldGen.crimson)
{
                                WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 7, false);
                            }
                            else
{
                                WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, num20 - 50), 6, false);
                            }
                        }
                        else if (Main.drunkWorld)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), WorldGen.genRand.Next(6, 8), false);
                        }
                        else if (WorldGen.crimson)
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), 7, false);
                        }
                        else
{
                            WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(100, Main.UnderworldLayer - 100), 6, false);
                        }
                    }
                    if (flag || WorldGen.SecretSeed.surfaceIsMushrooms.Enabled)
                    {
                        WorldGen.SkyblockIsland(WorldGen.genRand.Next(WorldGen.beachDistance, Main.maxTilesX - WorldGen.beachDistance), WorldGen.genRand.Next(num20 + 200, Main.UnderworldLayer - 100), 8, false);
                    }
                    progress.Set((double)((float)num2++ * num4));
                }
            }
            Main.dungeonX = -1;
            Main.dungeonY = -1;
            if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
            {
                int num23 = WorldGen.genRand.Next(40, 80);
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num23 *= -1;
                }
                int num14 = num5 + num23;
                num13 = num6;
                WorldGen.GrowLivingTree(num14, num13, false);
            }
            if (WorldGen.SecretSeed.pooEverywhere.Enabled)
            {
                WorldGen.SecretSeed.DoPooEverywhere();
            }
            if (WorldGen.SecretSeed.errorWorld.Enabled)
            {
                WorldGen.SecretSeed.DoErrorWorldShuffleBlocks();
            }
            GenVars.worldSpawnHasBeenRandomized = true;
            if ((double)num6 > Main.worldSurface && num6 < Main.UnderworldLayer)
            {
                WorldGen.PlaceTorchesAroundSpawn(-1, -1);
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.ID.PlayerTeamID.Count, Terraria.WorldGen.crimson, Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.WorldGen.SecretSeed.DoPooEverywhere(), Terraria.Main.drunkWorld, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.extraLiquid, Terraria.WorldGen.SecretSeed.extraLivingTrees, Terraria.WorldGen.genRand, Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.SecretSeed.hallowOnTheSurface, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noInfection, Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceTorchesAroundSpawn(), Terraria.WorldGen.SecretSeed.pooEverywhere, Terraria.WorldGen.SecretSeed.randomSpawn, Terraria.Utils.Remap(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.Skyblock.spawnShimmerPool, Terraria.WorldGen.SecretSeed.surfaceIsDesert, Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.WorldGen.SecretSeed.surfaceIsMushrooms, Terraria.WorldGen.SecretSeed.teamBasedSpawns, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Main.vampireSeed, Terraria.WorldGen.SecretSeed.worldIsFrozen, Terraria.WorldGen.SecretSeed.worldIsInfected, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses().