Terraria Decompiled: Terraria.WorldGen.CheckOasisPlant
CheckOasisPlant()
static void Terraria.WorldGen.CheckOasisPlant (int i, int j, int type = 530) inline static
Definition at line 45981 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            Tile tileSafely = Framing.GetTileSafely(i, j);
            int num = (int)(tileSafely.frameY % 36);
            int num2 = j + num / 18 * -1;
            int k = (int)(tileSafely.frameX / 18);
            int num3 = 0;
            short num4 = Framing.GetTileSafely(k, num2).frameY / 36;
            while (k > 2)
            {
                k -= 3;
                num3++;
            }
            k = i - k;
            int num5 = num3 * 54;
            for (int l = k; l < k + 3; l++)
            {
                for (int m = num2; m < num2 + 2; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || (int)Main.tile[l, m].frameX != (l - k) * 18 + num5 || (int)Main.tile[l, m].frameY != (m - num2) * 18)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[l, num2 + 2] == null)
                {
                    Main.tile[l, num2 + 2] = new Tile();
                }
                if (!WorldGen.SolidTile(l, num2 + 2, false) || !TileID.Sets.Conversion.Sand[(int)Main.tile[l, num2 + 2].type])
                {
                    flag = true;
                }
            }
            if (flag)
            {
                short frameX = Main.tile[i, j].frameX;
                WorldGen.destroyObject = true;
                for (int n = k; n < k + 3; n++)
                {
                    for (int num6 = num2; num6 < num2 + 2; num6++)
                    {
                        if (Main.tile[n, num6] == null)
{
                            Main.tile[n, num6] = new Tile();
                        }
                        if ((int)Main.tile[n, num6].type == type && Main.tile[n, num6].active())
{
                            WorldGen.KillTile(n, num6, false, false, false);
                        }
                    }
                }
                WorldGen.destroyObject = false;
                for (int num7 = k - 1; num7 < k + 4; num7++)
                {
                    for (int num8 = num2 - 1; num8 < num2 + 3; num8++)
                    {
                        WorldGen.TileFrame(num7, num8, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), int, Terraria.WorldGen.KillTile(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().