Terraria Decompiled: Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single
ReplaceTile_DoActualReplacement_Single()
static void Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single (int targetType, int targetStyle, int topLeftX, int topLeftY, Tile t) inline static private
Definition at line 61572 of file WorldGen.cs.
        {
            WorldGen.ReplaceTile_EliminateNaturalExtras(topLeftX, topLeftY);
            int type = (int)t.type;
            t.type = (ushort)targetType;
            if (TileID.Sets.Platforms[(int)t.type] || t.type == 380)
            {
                t.frameY = (short)(targetStyle * 18);
            }
            if (TileID.Sets.Torches[(int)t.type])
            {
                t.frameY = (short)(targetStyle * 22);
            }
            t.ClearBlockPaintAndCoating();
            bool flag = !WorldGen.CanPoundTile(topLeftX, topLeftY);
            if (TileID.Sets.Platforms[type] && TileID.Sets.Platforms[(int)t.type])
            {
                flag = false;
            }
            if (flag)
            {
                t.slope(0);
                t.halfBrick(false);
            }
            if (t.type == 53 || t.type == 396 || t.type == 397)
            {
                if (SpecialSeedFeatures.RainbowSandAndBlackSandWalls)
                {
                    t.color(WorldGen.GetRainbowPaintIDForPosition(topLeftX, topLeftY, true));
                }
                else if (Main.tenthAnniversaryWorld && !Main.remixWorld && !Main.notTheBeesWorld && !Main.dontStarveWorld)
                {
                    t.color(7);
                }
            }
            if (TileID.Sets.TruncatesWalls[targetType] != TileID.Sets.TruncatesWalls[type])
            {
                WorldGen.SquareWallFrame(topLeftX, topLeftY, true);
            }
            WorldGen.SquareTileFrame(topLeftX, topLeftY, true);
        }
References Terraria.WorldGen.CanPoundTile(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.color(), Terraria.Main.dontStarveWorld, Terraria.WorldGen.GetRainbowPaintIDForPosition(), Terraria.Tile.halfBrick(), int, Terraria.Main.notTheBeesWorld, Terraria.ID.TileID.Sets.Platforms, Terraria.GameContent.SpecialSeedFeatures.RainbowSandAndBlackSandWalls, Terraria.Main.remixWorld, Terraria.WorldGen.ReplaceTile_EliminateNaturalExtras(), Terraria.Tile.slope(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tenthAnniversaryWorld, Terraria.ID.TileID.Sets.Torches, Terraria.ID.TileID.Sets.TruncatesWalls, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.ReplaceTile_DoActualReplacement().