Terraria Decompiled: Terraria.WorldGen.ConsideredSolidTileForAnchor
ConsideredSolidTileForAnchor()
static bool Terraria.WorldGen.ConsideredSolidTileForAnchor (int x, int y) inline static private
Definition at line 52391 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 0))
            {
                return true;
            }
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return true;
            }
            if (!tile.active())
            {
                return false;
            }
            int num = 0;
            return tile.type >= 0 && (tile.type == 323 || (TileID.Sets.IsATreeTrunk[(int)tile.type] && !WorldGen.IsTileATreeBranch(x, y, out num))) && !WorldGen.IsTileALeafyTreeTop(tile);
        }
References Terraria.Tile.active(), int, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.WorldGen.IsTileALeafyTreeTop(), Terraria.WorldGen.IsTileATreeBranch(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.ValidateOrAttemptReorientingAnchor().