Terraria Decompiled: Terraria.WorldGen.ShimmerCleanUp
ShimmerCleanUp()
static void Terraria.WorldGen.ShimmerCleanUp () inline static private
Definition at line 32042 of file WorldGen.cs.
        {
            if (GenVars.shimmerPosition.X == 0.0 && GenVars.shimmerPosition.Y == 0.0)
            {
                return;
            }
            WorldGen.ShimmerRemoveWater();
            int num = 120;
            int num2 = 90;
            int num3 = (int)GenVars.shimmerPosition.X - num;
            int num4 = (int)GenVars.shimmerPosition.X + num;
            int num5 = (int)GenVars.shimmerPosition.Y - num;
            int num6 = (int)GenVars.shimmerPosition.Y + num;
            int num7 = num / 4;
            for (int i = num5; i <= num6; i++)
            {
                for (int j = num3; j <= num4; j++)
                {
                    int num8 = (int)Math.Sqrt(Math.Pow(Math.Abs((double)j - GenVars.shimmerPosition.X), 2.0) + Math.Pow(Math.Abs((double)i - GenVars.shimmerPosition.Y), 2.0));
                    if (num8 < num)
                    {
                        if (Main.tile[j, i].type == 22 || Main.tile[j, i].type == 204)
{
                            Main.tile[j, i].type = 1;
                        }
                        if (Main.tile[j, i].type == 51 || Main.tile[j, i].type == 56 || Main.tile[j, i].type == 229 || Main.tile[j, i].type == 230 || Main.tile[j, i].type == 659)
{
                            Main.tile[j, i].active(false);
                        }
                        if (TileID.Sets.Conversion.Moss[(int)Main.tile[j, i].type])
{
                            Main.tile[j, i].type = 1;
                        }
                        if (Main.tile[j, i].type == 184)
{
                            Main.tile[j, i].active(false);
                        }
                    }
                    if ((double)i > GenVars.shimmerPosition.Y)
                    {
                        num8 = (int)Math.Sqrt(Math.Pow(Math.Abs((double)j - GenVars.shimmerPosition.X) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0) + Math.Pow(Math.Abs((double)i - GenVars.shimmerPosition.Y) * 1.2 * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0));
                    }
                    else
                    {
                        num8 = (int)Math.Sqrt(Math.Pow(Math.Abs((double)j - GenVars.shimmerPosition.X) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0) + Math.Pow(Math.Abs((double)i - GenVars.shimmerPosition.Y) * 1.4 * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0));
                    }
                    if (num8 < num2)
                    {
                        if (Main.tile[j, i].type == 162)
{
                            Main.tile[j, i].active(false);
                        }
                        Main.tile[j, i].wall = 0;
                        WorldGen.Convert(j, i, 0, 3, true, true);
                    }
                }
            }
            int num9 = (int)GenVars.shimmerPosition.X;
            int num10 = (int)GenVars.shimmerPosition.Y;
            byte b = 127;
            Liquid.tilesIgnoreWater(true);
            while (Main.tile[num9, num10].liquid <= b || !Main.tile[num9, num10].shimmer())
            {
                while (!Main.tile[num9, num10].active())
                {
                    Main.tile[num9, num10].liquid = b;
                    Main.tile[num9, num10].shimmer(true);
                    num9--;
                }
                num9 = (int)GenVars.shimmerPosition.X;
                while (!Main.tile[num9, num10].active())
                {
                    Main.tile[num9, num10].liquid = b;
                    Main.tile[num9, num10].shimmer(true);
                    num9++;
                }
                num9 = (int)GenVars.shimmerPosition.X;
                num10++;
                b = byte.MaxValue;
                if (Main.tile[num9, num10].active())
                {
                    break;
                }
            }
            if (WorldGen.tenthAnniversaryWorldGen)
            {
                int num11 = 170;
                int num12 = (int)GenVars.shimmerPosition.X - num11;
                while ((double)num12 <= GenVars.shimmerPosition.X + (double)num11)
                {
                    for (int k = (int)GenVars.shimmerPosition.Y + 40; k < Main.maxTilesY - 330 - 100; k++)
                    {
                        if (WorldGen.InWorld(num12, k, 0) && Main.tile[num12, k].wall != 86)
{
                            if (Main.tile[num12, k].type == 375 || Main.tile[num12, k].type == 374 || Main.tile[num12, k].type == 373)
{
                                Main.tile[num12, k].type = 709;
                            }
                            if (Main.tile[num12, k].liquid > 0 && !Main.tile[num12, k].shimmer() && !Main.tile[num12, k].honey())
{
                                WorldGen.Shimmerator(num12, k, false, false);
                            }
                        }
                    }
                    num12++;
                }
            }
            Liquid.tilesIgnoreWater(false);
            for (int l = 10; l < Main.maxTilesX - 10; l++)
            {
                for (int m = 10; m < Main.maxTilesY - 10; m++)
                {
                    if (Main.tile[l, m].liquid > 0 && Main.tile[l, m].shimmer() && Main.tile[l, m].type == 5)
                    {
                        WorldGen.KillTile(l, m, false, false, false);
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.Convert(), Terraria.WorldGen.genRand, Terraria.Tile.honey(), int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.ID.TileID.Sets.Conversion.Moss, Terraria.Utilities.UnifiedRandom.NextDouble(), System.Math.Pow(), Terraria.Tile.shimmer(), Terraria.WorldGen.Shimmerator(), Terraria.WorldBuilding.GenVars.shimmerPosition, Terraria.WorldGen.ShimmerRemoveWater(), System.Math.Sqrt(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Liquid.tilesIgnoreWater(), Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.