Terraria Decompiled: Terraria.WorldGen.CheckWoman
CheckWoman()
static void Terraria.WorldGen.CheckWoman (int i, int j) inline static
Definition at line 44964 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int num = j - (int)(Main.tile[i, j].frameY / 18);
            int k;
            for (k = (int)Main.tile[i, j].frameX; k >= 100; k -= 100)
            {
            }
            while (k >= 36)
            {
                k -= 36;
            }
            int num2 = i - k / 18;
            bool flag = false;
            for (int l = 0; l <= 1; l++)
            {
                for (int m = 0; m <= 2; m++)
                {
                    int num3 = num2 + l;
                    int num4 = num + m;
                    int n;
                    for (n = (int)Main.tile[num3, num4].frameX; n >= 100; n -= 100)
                    {
                    }
                    if (n >= 36)
                    {
                        n -= 36;
                    }
                    if (!Main.tile[num3, num4].active() || Main.tile[num3, num4].type != 269 || (int)Main.tile[num3, num4].frameY != m * 18 || n != l * 18)
                    {
                        flag = true;
                    }
                }
            }
            if (!WorldGen.SolidTileAllowBottomSlope(num2, num + 3) || !WorldGen.SolidTileAllowBottomSlope(num2 + 1, num + 3))
            {
                flag = true;
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1989, 1, false, 0, false);
                for (int num5 = 0; num5 <= 1; num5++)
                {
                    for (int num6 = 0; num6 <= 2; num6++)
                    {
                        int num7 = num2 + num5;
                        int num8 = num + num6;
                        if (Main.tile[num7, num8].active() && Main.tile[num7, num8].type == 269)
{
                            WorldGen.KillTile(num7, num8, false, false, false);
                        }
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().