Terraria Decompiled: Terraria.WorldGen.serverLoadWorld
serverLoadWorld()
static Task Terraria.WorldGen.serverLoadWorld () inline static
Definition at line 2761 of file WorldGen.cs.
        {
            return Task.Factory.StartNew(new Action(WorldGen.serverLoadWorldCallBack));
        }
References System.Action(), System.Threading.Tasks.Task< TResult >.Factory, Terraria.WorldGen.serverLoadWorldCallBack(), and System.Threading.Tasks.TaskFactory< TResult >.StartNew().
Referenced by Terraria.Main.DedServ().