Terraria Decompiled: Terraria.WorldGen.PlayLiquidChangeSound
PlayLiquidChangeSound()
static void Terraria.WorldGen.PlayLiquidChangeSound (TileChangeType eventType, int x, int y, int count = 1) inline static
Definition at line 260 of file WorldGen.cs.
        {
            switch (eventType)
            {
            case TileChangeType.LavaWater:
                SoundEngine.PlaySound(SoundID.LiquidsWaterLava, x * 16 + count * 8, y * 16 + count * 8, 0f, 1f);
                return;
            case TileChangeType.HoneyWater:
                SoundEngine.PlaySound(SoundID.LiquidsHoneyWater, x * 16 + count * 8, y * 16 + count * 8, 0f, 1f);
                return;
            case TileChangeType.HoneyLava:
                SoundEngine.PlaySound(SoundID.LiquidsHoneyLava, x * 16 + count * 8, y * 16 + count * 8, 0f, 1f);
                return;
            case TileChangeType.ShimmerWater:
                SoundEngine.PlaySound(19, x * 16 + count * 8, y * 16 + count * 8, 4, 1f, 0f);
                return;
            case TileChangeType.ShimmerLava:
                SoundEngine.PlaySound(19, x * 16 + count * 8, y * 16 + count * 8, 4, 1f, 0f);
                return;
            case TileChangeType.ShimmerHoney:
                SoundEngine.PlaySound(19, x * 16 + count * 8, y * 16 + count * 8, 4, 1f, 0f);
                return;
            default:
                return;
            }
        }
References System.count, Terraria.ID.SoundID.LiquidsHoneyLava, Terraria.ID.SoundID.LiquidsHoneyWater, Terraria.ID.SoundID.LiquidsWaterLava, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.Liquid.CreateLiquidMergeTile(), and Terraria.Main.OnTileChangeEvent().