Terraria Decompiled: Terraria.WorldGen.Convert
Convert() [1/2]
static void Terraria.WorldGen.Convert (int i, int j, int conversionType, int size, bool tiles = true, bool walls = true) inline static
Definition at line 53630 of file WorldGen.cs.
        {
            if (!tiles && !walls)
            {
                return;
            }
            for (int k = i - size; k <= i + size; k++)
            {
                for (int l = j - size; l <= j + size; l++)
                {
                    if (WorldGen.InWorld(k, l, 1) && Math.Abs(k - i) + Math.Abs(l - j) < 6)
                    {
                        WorldGen.Convert(k, l, conversionType, tiles, walls);
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.WorldGen.Convert(), and Terraria.WorldGen.InWorld().
Referenced by Terraria.Projectile.AI(), Terraria.WorldGen.ChlorophyteDefense(), Terraria.WorldGen.Convert(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.WorldGen.SecretSeed.DoHallowOnSurface(), Terraria.WorldGen.SecretSeed.DoNoInfection(), Terraria.WorldGen.SecretSeed.DoSurfaceIsMushrooms(), Terraria.WorldGen.SecretSeed.DoWorldIsInfected(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.hardUpdateWorld(), Terraria.WorldGen.initializeHardMode(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.WorldGen.SpreadGrass(), and Terraria.WorldGen.SpreadGrassWalls().