Terraria Decompiled: Terraria.WorldGen.WavyCaverer
WavyCaverer()
static void Terraria.WorldGen.WavyCaverer (int startX, int startY, double waveStrengthScalar, double wavePercentScalar, int steps, int type) inline static
Definition at line 77275 of file WorldGen.cs.
        {
            Vector2D vector2D;
            vector2D..ctor((double)startX, (double)startY);
            bool flag = startX > Main.maxTilesX / 2;
            int num = 2 + WorldGen.genRand.Next(2);
            int num2 = 15 + WorldGen.genRand.Next(11);
            int num3 = 1 + WorldGen.genRand.Next(2);
            int num4 = (int)Math.Ceiling((double)num2 / (double)num3);
            double num5 = 1.0;
            double num6 = 1.0;
            int num7 = (int)(-1.0 + WorldGen.genRand.NextDouble() * 3.0);
            int num8 = num;
            int num9 = 0;
            for (int i = 0; i < steps; i++)
            {
                bool flag2 = i < num4;
                bool flag3 = i >= steps - num4;
                vector2D.X += (double)(flag ? (-1) : 1);
                if (!flag2 && !flag3)
                {
                    num9++;
                    num5 = Math.Min(2.0, Math.Max(0.5, num5 + (-0.5 + WorldGen.genRand.NextDouble()) * 0.25));
                    num6 = Math.Min(1.1, Math.Max(0.9, num6 + (-0.5 + WorldGen.genRand.NextDouble()) * 0.02));
                }
                double num10 = Math.Sin((double)num9 * 0.1 * num6 * wavePercentScalar) * num5 * waveStrengthScalar;
                vector2D.Y = (double)startY + num10 + (double)(num9 * num7);
                int num11 = num8;
                if (flag2)
                {
                    num8 = Math.Min(num2, num8 + num3);
                }
                else if (flag3)
                {
                    num8 = Math.Max(num, num8 - num3);
                }
                vector2D.Y -= (double)((num11 + num8) / 4);
                for (int j = 0; j < num8; j++)
                {
                    int num12 = (int)vector2D.X;
                    int num13 = (int)vector2D.Y + j;
                    if (WorldGen.InWorld(num12, num13, 20))
                    {
                        if (type >= 0)
{
                            WorldGen.PlaceTile(num12, num13, type, true, true, -1, 0);
                        }
                        else
{
                            WorldGen.KillTile(num12, num13, false, false, false);
                        }
                    }
                }
            }
        }
References System.Math.Ceiling(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile(), System.Math.Max(), System.Math.Min(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.PlaceTile(), System.Math.Sin(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().