Terraria Decompiled: Terraria.WorldGen.FillWallHolesInSpot
FillWallHolesInSpot()
static bool Terraria.WorldGen.FillWallHolesInSpot (int originX, int originY, int maxWallsThreshold) inline static private
Definition at line 5886 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(originX, originY, 2))
            {
                return false;
            }
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            HashSet<Point> hashSet = new HashSet<Point>();
            Dictionary<ushort, int> dictionary = new Dictionary<ushort, int>();
            list2.Add(new Point(originX, originY));
            while (list2.Count > 0)
            {
                list.Clear();
                list.AddRange(list2);
                list2.Clear();
                while (list.Count > 0)
                {
                    if (hashSet.Count >= maxWallsThreshold)
                    {
                        return false;
                    }
                    Point point = list[0];
                    if (hashSet.Contains(point))
                    {
                        list.Remove(point);
                    }
                    else if (!WorldGen.InWorld(point.X, point.Y, 1))
                    {
                        list.Remove(point);
                    }
                    else
                    {
                        hashSet.Add(point);
                        list.Remove(point);
                        Tile tile = Main.tile[point.X, point.Y];
                        if (tile.wall != 0)
{
                            if (dictionary.ContainsKey(tile.wall))
{
                                dictionary[tile.wall] = dictionary[tile.wall] + 1;
                            }
                            else
{
                                dictionary[tile.wall] = 1;
                            }
                        }
                        else
{
                            bool flag = false;
                            if (!flag)
{
                                int y = point.Y;
                                for (int i = point.X - 1; i <= point.X + 1; i++)
{
                                    if (!Main.tile[i, y].active())
{
                                        flag = true;
                                        break;
                                    }
                                }
                            }
                            if (!flag)
{
                                int x = point.X;
                                for (int j = point.Y - 1; j <= point.Y + 1; j++)
{
                                    if (!Main.tile[x, j].active())
{
                                        flag = true;
                                        break;
                                    }
                                }
                            }
                            if (flag)
{
                                Point point2 = new Point(point.X - 1, point.Y);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X + 1, point.Y);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X, point.Y - 1);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                                point2 = new Point(point.X, point.Y + 1);
                                if (!hashSet.Contains(point2))
{
                                    list2.Add(point2);
                                }
                            }
                        }
                    }
                }
            }
            if (hashSet.Count == 1)
            {
                return false;
            }
            ushort num = 0;
            int num2 = -1;
            foreach (KeyValuePair<ushort, int> keyValuePair in dictionary)
            {
                if (keyValuePair.Value > num2)
                {
                    num = keyValuePair.Key;
                    num2 = keyValuePair.Value;
                }
            }
            if (num2 == -1)
            {
                num = 2;
            }
            foreach (Point point3 in hashSet)
            {
                Tile tile2 = Main.tile[point3.X, point3.Y];
                if (tile2.wall == 0)
                {
                    tile2.wall = num;
                }
            }
            return true;
        }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, System.dictionary, Terraria.WorldGen.InWorld(), System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, System.list, Terraria.Main.tile, System.Collections.Generic.KeyValuePair< TKey, TValue >.Value, Terraria.Tile.wall, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.FillWallHolesInColumn().