Terraria Decompiled: Terraria.WorldGen.GrowLivingTree_MakePassage
GrowLivingTree_MakePassage()
static void Terraria.WorldGen.GrowLivingTree_MakePassage (int j, int W, ref int minl, ref int minr, bool noSecretRoom = false) inline static
Definition at line 26071 of file WorldGen.cs.
        {
            bool flag = noSecretRoom;
            int num = minl;
            int num2 = minr;
            bool flag2 = false;
            int num3 = (minl + minr) / 2;
            int num4 = 5;
            int num5 = j - 6;
            int num6 = 50;
            int i = WorldGen.genRand.Next(400, 700);
            if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
            {
                float num7 = (float)(Main.maxTilesY / 1200);
                i *= 5;
                if (WorldGen.genRand.Next(3) == 0)
                {
                    num6 = (int)((float)WorldGen.genRand.Next(200, 1500) * num7);
                }
                else if (WorldGen.genRand.Next(2) == 0)
                {
                    num6 = (int)((float)WorldGen.genRand.Next(50, 400) * num7);
                }
            }
            else if (WorldGen.notTheBees && WorldGen.tenthAnniversaryWorldGen && !WorldGen.drunkWorldGen)
            {
                i *= 5;
            }
            int num8 = 0;
            bool flag3 = true;
            int num9 = WorldGen.genRand.Next(5, 16);
            int num10;
            if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.IntersectsAnyPotentialDungeonBounds(out num10, new Rectangle(minl, num5, Math.Max(1, minr - minl), i), false))
            {
                i = GenVars.dungeonGenVars[num10].outerPotentialDungeonBounds.Top - num5 - 2;
            }
            while (i > 0)
            {
                if (WorldGen.skyblockWorldGen)
                {
                    if (num5 < Main.maxTilesY - 20)
                    {
                        i = 100;
                        num6 = 100;
                    }
                    else
                    {
                        i = 0;
                        num6 = 0;
                    }
                }
                else
                {
                    if (num5 > Main.UnderworldLayer + WorldGen.genRand.Next(15, 31))
                    {
                        i = 0;
                    }
                    if (WorldGen.SecretSeed.extraLivingTrees.Enabled && Vector2D.Distance(new Vector2D((double)((minl + minr) / 2), (double)num5), GenVars.shimmerPosition) < 120.0)
                    {
                        num6 = 0;
                        i = 0;
                    }
                }
                num5++;
                i--;
                num6--;
                int num11 = (minl + minr) / 2;
                if (!Main.tile[minl, num5].active() && Main.tile[minl, num5].wall == 244 && !Main.tile[minr, num5].active() && Main.tile[minr, num5].wall == 244)
                {
                    break;
                }
                int num12 = 1;
                if (num5 > j && W <= 4)
                {
                    num12++;
                }
                for (int k = minl - num12; k <= minr + num12; k++)
                {
                    if (Main.wallDungeon[(int)Main.tile[k, num5].wall])
                    {
                        flag = true;
                        flag2 = true;
                    }
                    if (k > num11 - 2 && k <= num11 + 1)
                    {
                        if (num5 > j - 4)
{
                            bool flag4 = true;
                            if (!Main.tile[k, num5 + 1].active() && Main.tile[k, num5 + 1].wall == 34)
{
                                flag4 = false;
                            }
                            if (Main.tile[k, num5].type != 19 && Main.tile[k, num5].type != 15 && Main.tile[k, num5].type != 304 && Main.tile[k, num5].type != 21 && Main.tile[k, num5].type != 10 && Main.tile[k, num5 - 1].type != 15 && Main.tile[k, num5 - 1].type != 304 && Main.tile[k, num5 - 1].type != 21 && Main.tile[k, num5 - 1].type != 10 && Main.tile[k, num5 + 1].type != 10)
{
                                Main.tile[k, num5].active(false);
                            }
                            if (!Main.wallDungeon[(int)Main.tile[k, num5].wall] && Main.tile[k, num5].wall != 3 && Main.tile[k, num5].wall != 83)
{
                                Main.tile[k, num5].wall = 244;
                            }
                            if (!Main.wallDungeon[(int)Main.tile[k - 1, num5].wall] && (Main.tile[k - 1, num5].wall > 0 || (double)num5 >= Main.worldSurface))
{
                                Main.tile[k - 1, num5].wall = 244;
                            }
                            if (!Main.wallDungeon[(int)Main.tile[k + 1, num5].wall] && (Main.tile[k + 1, num5].wall > 0 || (double)num5 >= Main.worldSurface))
{
                                Main.tile[k + 1, num5].wall = 244;
                            }
                            if (num5 == j && k > num11 - 2 && k <= num11 + 1 && flag4)
{
                                Main.tile[k, num5 + 1].active(false);
                                WorldGen.PlaceTile(k, num5 + 1, 19, true, false, -1, 23);
                            }
                        }
                    }
                    else
                    {
                        if (Main.tile[k, num5].type != 15 && Main.tile[k, num5].type != 304 && Main.tile[k, num5].type != 21 && Main.tile[k, num5].type != 10 && Main.tile[k - 1, num5].type != 10 && Main.tile[k + 1, num5].type != 10)
{
                            if (!Main.wallDungeon[(int)Main.tile[k, num5].wall] && Main.tile[k, num5].wall != 3 && Main.tile[k, num5].wall != 83 && (Main.tile[k, num5].active() || Main.tile[k, num5].wall != 34))
{
                                Main.tile[k, num5].type = 191;
                                Main.tile[k, num5].active(true);
                                Main.tile[k, num5].halfBrick(false);
                            }
                            if (Main.tile[k - 1, num5].type == 40)
{
                                Main.tile[k - 1, num5].type = 0;
                            }
                            if (Main.tile[k + 1, num5].type == 40)
{
                                Main.tile[k + 1, num5].type = 0;
                            }
                        }
                        if (num5 <= j && num5 > j - 4 && k > minl - num12 && k <= minr + num12 - 1)
{
                            Main.tile[k, num5].wall = 244;
                        }
                    }
                    if (!WorldGen.isGeneratingOrLoadingWorld)
                    {
                        WorldGen.SquareTileFrame(k, num5, true);
                        WorldGen.SquareWallFrame(k, num5, true);
                    }
                }
                num8++;
                if (num8 >= 6)
                {
                    num8 = 0;
                    int num13 = WorldGen.genRand.Next(3);
                    if (num13 == 0)
                    {
                        num13 = -1;
                    }
                    if (flag3)
                    {
                        num13 = 2;
                    }
                    if (num13 == -1 && Main.tile[minl - num4, num5].wall == 244)
                    {
                        num13 = 1;
                    }
                    else if (num13 == 1 && Main.tile[minr + num4, num5].wall == 244)
                    {
                        num13 = -1;
                    }
                    if (num13 == 2)
                    {
                        flag3 = false;
                        int num14 = 23;
                        if (Main.wallDungeon[(int)Main.tile[minl, num5 + 1].wall] || Main.wallDungeon[(int)Main.tile[minl + 1, num5 + 1].wall] || Main.wallDungeon[(int)Main.tile[minl + 2, num5 + 1].wall])
{
                            num14 = 12;
                        }
                        for (int l = minl; l <= minr; l++)
{
                            if (l > num11 - 2 && l <= num11 + 1)
{
                                Main.tile[l, num5 + 1].active(false);
                                WorldGen.PlaceTile(l, num5 + 1, 19, true, false, -1, num14);
                            }
                        }
                    }
                    else
                    {
                        minl += num13;
                        minr += num13;
                    }
                    if (noSecretRoom)
                    {
                        num9--;
                        if (num9 <= 0)
{
                            if (WorldGen.GrowLivingTree_HorizontalTunnel(num11, num5))
{
                                num9 = WorldGen.genRand.Next(5, 21);
                            }
                            else
{
                                num9 = WorldGen.genRand.Next(2, 11);
                            }
                        }
                    }
                    if (num6 <= 0 && !flag)
                    {
                        flag = true;
                        WorldGen.GrowLivingTreePassageRoom(minl, minr, num5);
                    }
                }
                if (flag2)
                {
                    bool flag5 = true;
                    for (int m = minl; m <= minr; m++)
                    {
                        for (int n = num5 + 1; n <= num5 + 2; n++)
{
                            if (WorldGen.SolidTile(m, n, false))
{
                                flag5 = false;
                            }
                        }
                    }
                    if (flag5)
                    {
                        i = 0;
                    }
                }
                else if (num6 <= 0)
                {
                    bool flag6 = true;
                    for (int num15 = minl; num15 <= minr; num15++)
                    {
                        for (int num16 = num5 + 1; num16 <= num5 + 4; num16++)
{
                            if (WorldGen.SolidTile(num15, num16, false))
{
                                flag6 = false;
                            }
                        }
                    }
                    if (flag6)
                    {
                        i = 0;
                    }
                }
            }
            minl = num;
            minr = num2;
            int num17 = (minl + minr) / 2;
            for (int num18 = minl; num18 <= minr; num18++)
            {
                for (int num19 = j - 3; num19 <= j; num19++)
                {
                    Main.tile[num18, num19].active(false);
                    bool flag7 = true;
                    for (int num20 = num18 - 1; num20 <= num18 + 1; num20++)
                    {
                        for (int num21 = num19 - 1; num21 <= num19 + 1; num21++)
{
                            if (!Main.tile[num20, num21].active() && Main.tile[num20, num21].wall == 0)
{
                                flag7 = false;
                            }
                        }
                    }
                    if (flag7 && !Main.wallDungeon[(int)Main.tile[num18, num19].wall])
                    {
                        Main.tile[num18, num19].wall = 244;
                    }
                }
            }
        }
References Terraria.Tile.active(), ReLogic.Utilities.Vector2D.Distance(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldBuilding.GenVars.dungeonGenVars, Terraria.WorldGen.SecretSeed.extraLivingTrees, Terraria.WorldGen.genRand, Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.Tile.halfBrick(), int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IntersectsAnyPotentialDungeonBounds(), Terraria.WorldGen.isGeneratingOrLoadingWorld, System.Math.Max(), Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceTile(), Terraria.WorldBuilding.GenVars.shimmerPosition, Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, System.W, Terraria.Tile.wall, Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.GrowLivingTree().