Terraria Decompiled: Terraria.WorldGen.PlaceLiquid
PlaceLiquid()
static bool Terraria.WorldGen.PlaceLiquid (int x, int y, byte liquidType, byte amount) inline static
Definition at line 205 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 0))
            {
                return false;
            }
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return false;
            }
            byte b = tile.liquidType();
            if (tile.nactive() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
            {
                return false;
            }
            if (tile.liquid == 0 || liquidType == b)
            {
                tile.liquidType((int)liquidType);
                if (amount + tile.liquid > 255)
                {
                    amount = byte.MaxValue - tile.liquid;
                }
                Tile tile2 = tile;
                tile2.liquid += amount;
                WorldGen.SquareTileFrame(x, y, true);
                if (Main.netMode != 0)
                {
                    NetMessage.sendWater(x, y);
                }
                return true;
            }
            int num = 0;
            bool flag = b == 0;
            bool flag2 = b == 1;
            bool flag3 = b == 2;
            bool flag4 = b == 3;
            int num2 = 0;
            Liquid.GetLiquidMergeTypes((int)liquidType, out num, out num2, flag, flag2, flag3, flag4);
            if (num != 0)
            {
                tile.liquid = 0;
                tile.liquidType(0);
                WorldGen.PlaceTile(x, y, num, true, false, -1, 0);
                WorldGen.SquareTileFrame(x, y, true);
                if (Main.netMode != 0)
                {
                    NetMessage.SendTileSquare(-1, x, y, WorldGen.GetLiquidChangeType((int)liquidType, (int)b));
                }
                return true;
            }
            return false;
        }
References Terraria.WorldGen.GetLiquidChangeType(), Terraria.Liquid.GetLiquidMergeTypes(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.WorldGen.PlaceTile(), Terraria.NetMessage.SendTileSquare(), Terraria.NetMessage.sendWater(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.Projectile.LavaBoulderExplosion(), Terraria.DelegateMethods.SpreadHoney(), Terraria.DelegateMethods.SpreadLava(), and Terraria.DelegateMethods.SpreadWater().