Terraria Decompiled: Terraria.WorldGen.InvalidTileForPilesOrSpeleothems
InvalidTileForPilesOrSpeleothems()
static bool Terraria.WorldGen.InvalidTileForPilesOrSpeleothems (int x, int y) inline static
Definition at line 36481 of file WorldGen.cs.
        {
            return WorldGen.InWorld(x, y, 2) && Main.tile[x, y] != null && Main.tile[x, y].active() && TileID.Sets.Boulders[(int)Main.tile[x, y].type];
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, int, Terraria.WorldGen.InWorld(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.CheckStalactite(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.PlaceSmallPile(), and Terraria.WorldGen.TileFrameImportant().