Terraria Decompiled: Terraria.WorldGen.PoundPlatform
PoundPlatform()
static void Terraria.WorldGen.PoundPlatform (int x, int y) inline static
Definition at line 81524 of file WorldGen.cs.
        {
            if (Main.tile[x, y].halfBrick())
            {
                WorldGen.PoundTile(x, y);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 7, (float)x, (float)y, 1f, 0, 0, 0);
                    return;
                }
            }
            else
            {
                int num = 1;
                int num2 = 2;
                if (TileID.Sets.Platforms[(int)Main.tile[x + 1, y - 1].type] || TileID.Sets.Platforms[(int)Main.tile[x - 1, y + 1].type] || (WorldGen.SolidTile(x + 1, y, false) && !WorldGen.SolidTile(x - 1, y, false)))
                {
                    num = 2;
                    num2 = 1;
                }
                if (Main.tile[x, y].slope() == 0)
                {
                    WorldGen.SlopeTile(x, y, num, false, true);
                    int num3 = (int)Main.tile[x, y].slope();
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)y, (float)num3, 0, 0, 0);
                        return;
                    }
                }
                else if ((int)Main.tile[x, y].slope() == num)
                {
                    WorldGen.SlopeTile(x, y, num2, false, true);
                    int num4 = (int)Main.tile[x, y].slope();
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)y, (float)num4, 0, 0, 0);
                        return;
                    }
                }
                else
                {
                    WorldGen.SlopeTile(x, y, 0, false, true);
                    int num5 = (int)Main.tile[x, y].slope();
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 14, (float)x, (float)y, (float)num5, 0, 0, 0);
                    }
                    WorldGen.PoundTile(x, y);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 7, (float)x, (float)y, 1f, 0, 0, 0);
                    }
                }
            }
        }
References Terraria.Tile.halfBrick(), int, Terraria.Main.netMode, Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.PoundTile(), Terraria.NetMessage.SendData(), Terraria.Tile.slope(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.