Terraria Decompiled: Terraria.WorldGen.ShiftTallGate
ShiftTallGate()
static bool Terraria.WorldGen.ShiftTallGate (int x, int y, bool closing, bool forced = false) inline static
Definition at line 50233 of file WorldGen.cs.
        {
            ushort num = (closing ? 388 : 389);
            ushort num2 = (closing ? 389 : 388);
            Tile tile = Framing.GetTileSafely(x, y);
            if (tile.type != num2)
            {
                return false;
            }
            Point point = new Point((int)(tile.frameX / 18), 0);
            TileObjectData tileData = TileObjectData.GetTileData(388, point.X, 0);
            point.Y = (int)tile.frameY / tileData.CoordinateFullHeight;
            int width = tileData.Width;
            int height = tileData.Height;
            int num3 = 0;
            int num4 = (int)tile.frameY % tileData.CoordinateFullHeight;
            while (num3 < height && num4 - tileData.CoordinateHeights[num3] >= 0)
            {
                num4 -= tileData.CoordinateHeights[num3];
                num3++;
            }
            int coordinateFullHeight = tileData.CoordinateFullHeight;
            y -= num3;
            if (!WorldGen.ValidateTileSquareIsActiveAndOfType(x, y, width, height, (int)num2))
            {
                return false;
            }
            if (Main.netMode != 1 && Wiring.running)
            {
                for (int i = 0; i < height; i++)
                {
                    Wiring.SkipWire(x, y + i);
                }
            }
            for (int j = 0; j < height; j++)
            {
                if (!forced && !Collision.EmptyTile(x, y + j, true))
                {
                    return false;
                }
            }
            SoundEngine.PlaySound(8, x * 16 + 16, y * 16 + 16, 1, 1f, 0f);
            for (int k = 0; k < height; k++)
            {
                tile = Framing.GetTileSafely(x, y + k);
                tile.type = num;
            }
            for (int l = -1; l < 2; l++)
            {
                for (int m = -1; m < height + 1; m++)
                {
                    WorldGen.TileFrame(x + l, y + m, false, false);
                }
            }
            return true;
        }
References Terraria.ObjectData.TileObjectData.CoordinateFullHeight, Terraria.ObjectData.TileObjectData.CoordinateHeights, Terraria.Collision.EmptyTile(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.Framing.GetTileSafely(), Terraria.ObjectData.TileObjectData.Height, int, Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Wiring.running, Terraria.Wiring.SkipWire(), Terraria.WorldGen.TileFrame(), Terraria.Tile.type, Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType(), Terraria.ObjectData.TileObjectData.Width, and Microsoft.Xna.Framework.Point.X.
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), Terraria.Player.TileInteractionsUse(), Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryCloseDoor(), and Terraria.GameContent.DoorOpeningHelper.TallGateOpeningInfoProvider.TryOpenDoor().