Terraria Decompiled: Terraria.WorldGen.FillWallHolesInArea
FillWallHolesInArea()
static void Terraria.WorldGen.FillWallHolesInArea (Rectangle worldCoordsArea) inline static
Definition at line 5842 of file WorldGen.cs.
        {
            int num = Math.Max(worldCoordsArea.Left, 0);
            int num2 = Math.Min(worldCoordsArea.Right, Main.maxTilesX);
            int num3 = 0;
            for (int i = num; i <= num2; i++)
            {
                if (i >= 0 && i < Main.maxTilesX)
                {
                    num3 += WorldGen.FillWallHolesInColumn(i, worldCoordsArea.Top, worldCoordsArea.Bottom);
                }
            }
        }
References Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.WorldGen.FillWallHolesInColumn(), Microsoft.Xna.Framework.Rectangle.Left, System.Math.Max(), Terraria.Main.maxTilesX, System.Math.Min(), Microsoft.Xna.Framework.Rectangle.Right, and Microsoft.Xna.Framework.Rectangle.Top.