Terraria Decompiled: Terraria.WorldGen.CountNearBlocksTypes
CountNearBlocksTypes()
static int Terraria.WorldGen.CountNearBlocksTypes (int i, int j, int radius, int cap = 0, params int[] tiletypes) inline static
Definition at line 69889 of file WorldGen.cs.
        {
            if (tiletypes.Length == 0)
            {
                return 0;
            }
            int num = i - radius;
            int num2 = i + radius;
            int num3 = j - radius;
            int num4 = j + radius;
            int num5 = Utils.Clamp<int>(num, 0, Main.maxTilesX - 1);
            num2 = Utils.Clamp<int>(num2, 0, Main.maxTilesX - 1);
            num3 = Utils.Clamp<int>(num3, 0, Main.maxTilesY - 1);
            num4 = Utils.Clamp<int>(num4, 0, Main.maxTilesY - 1);
            int num6 = 0;
            for (int k = num5; k <= num2; k++)
            {
                for (int l = num3; l <= num4; l++)
                {
                    if (Main.tile[k, l].active())
                    {
                        int m = 0;
                        while (m < tiletypes.Length)
{
                            if (tiletypes[m] == (int)Main.tile[k, l].type)
{
                                num6++;
                                if (cap > 0 && num6 >= cap)
{
                                    return num6;
                                }
                                break;
                            }
                            else
{
                                m++;
                            }
                        }
                    }
                }
            }
            return num6;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.hardUpdateWorld(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().