Terraria Decompiled: Terraria.WorldGen.AttemptToGrowTreeFromSapling
AttemptToGrowTreeFromSapling()
static bool Terraria.WorldGen.AttemptToGrowTreeFromSapling (int x, int y, bool underground, int treeHeightAddon = 0, bool ignoreWalls = false) inline static
Definition at line 73206 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return false;
            }
            if (!WorldGen.InWorld(x, y, 2))
            {
                return false;
            }
            Tile tile = Main.tile[x, y];
            if (tile == null || !tile.active())
            {
                return false;
            }
            ushort type = tile.type;
            if (type <= 590)
            {
                if (type == 20)
                {
                    int num = (int)(tile.frameX / 54);
                    bool flag;
                    if (num - 6 > 3)
                    {
                        if (num == 10)
{
                            flag = WorldGen.TryGrowingTreeByType(634, x, y, treeHeightAddon, ignoreWalls);
                        }
                        else
{
                            if (underground && !Main.notTheBeesWorld && !Main.remixWorld)
{
                                return false;
                            }
                            flag = WorldGen.TryGrowingTreeByType(5, x, y, treeHeightAddon, ignoreWalls);
                        }
                    }
                    else
                    {
                        if (underground && !Main.notTheBeesWorld && !Main.remixWorld)
{
                            return false;
                        }
                        flag = WorldGen.TryGrowingTreeByType(323, x, y, treeHeightAddon, ignoreWalls);
                    }
                    if (flag && WorldGen.PlayerLOS(x, y))
                    {
                        WorldGen.TreeGrowFXCheck(x, y);
                    }
                    return flag;
                }
                if (type == 590)
                {
                    if (!underground)
                    {
                        return false;
                    }
                    int num = (int)(tile.frameX / 54);
                    int num2 = 587;
                    switch (num)
                    {
                    case 0:
                        num2 = 583;
                        break;
                    case 1:
                        num2 = 584;
                        break;
                    case 2:
                        num2 = 585;
                        break;
                    case 3:
                        num2 = 586;
                        break;
                    case 4:
                        num2 = 587;
                        break;
                    case 5:
                        num2 = 588;
                        break;
                    case 6:
                        num2 = 589;
                        break;
                    }
                    bool flag = WorldGen.TryGrowingTreeByType(num2, x, y, treeHeightAddon, ignoreWalls);
                    if (flag && WorldGen.PlayerLOS(x, y))
                    {
                        WorldGen.TreeGrowFXCheck(x, y);
                    }
                    return flag;
                }
            }
            else
            {
                if (type == 595)
                {
                    int num = (int)(tile.frameX / 54);
                    int num2 = 596;
                    if (num == 0)
                    {
                        num2 = 596;
                    }
                    bool flag = WorldGen.TryGrowingTreeByType(num2, x, y, treeHeightAddon, ignoreWalls);
                    if (flag && WorldGen.PlayerLOS(x, y))
                    {
                        WorldGen.TreeGrowFXCheck(x, y);
                    }
                    return flag;
                }
                if (type == 615)
                {
                    int num = (int)(tile.frameX / 54);
                    int num2 = 616;
                    if (num == 0)
                    {
                        num2 = 616;
                    }
                    bool flag = WorldGen.TryGrowingTreeByType(num2, x, y, treeHeightAddon, ignoreWalls);
                    if (flag && WorldGen.PlayerLOS(x, y))
                    {
                        WorldGen.TreeGrowFXCheck(x, y);
                    }
                    return flag;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, int, Terraria.WorldGen.InWorld(), Terraria.Main.netMode, Terraria.Main.notTheBeesWorld, Terraria.WorldGen.PlayerLOS(), Terraria.Main.remixWorld, Terraria.Main.tile, Terraria.WorldGen.TreeGrowFXCheck(), Terraria.WorldGen.TryGrowingTreeByType(), and Terraria.Tile.type.
Referenced by Terraria.Projectile.AI(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().