Terraria Decompiled: Terraria.WorldGen.ChasmRunnerSideways
ChasmRunnerSideways()
static void Terraria.WorldGen.ChasmRunnerSideways (int i, int j, int direction, int steps) inline static
Definition at line 75772 of file WorldGen.cs.
        {
            double num = (double)steps;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(10, 21) * 0.1 * (double)direction;
            vector2D2.Y = (double)WorldGen.genRand.Next(-10, 10) * 0.01;
            double num2 = (double)(WorldGen.genRand.Next(5) + 7);
            while (num2 > 0.0)
            {
                if (num > 0.0)
                {
                    num2 += (double)WorldGen.genRand.Next(3);
                    num2 -= (double)WorldGen.genRand.Next(3);
                    if (num2 < 7.0)
                    {
                        num2 = 7.0;
                    }
                    if (num2 > 20.0)
                    {
                        num2 = 20.0;
                    }
                    if (num == 1.0 && num2 < 10.0)
                    {
                        num2 = 10.0;
                    }
                }
                else
                {
                    num2 -= (double)WorldGen.genRand.Next(4);
                }
                if (vector2D.Y > Main.rockLayer && num > 0.0 && !WorldGen.SecretSeed.noSurface.Enabled)
                {
                    num = 0.0;
                }
                num -= 1.0;
                int num3 = (int)(vector2D.X - num2 * 0.5);
                int num4 = (int)(vector2D.X + num2 * 0.5);
                int num5 = (int)(vector2D.Y - num2 * 0.5);
                int num6 = (int)(vector2D.Y + num2 * 0.5);
                if (num3 < 0)
                {
                    num3 = 0;
                }
                if (num4 > Main.maxTilesX - 1)
                {
                    num4 = Main.maxTilesX - 1;
                }
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesY)
                {
                    num6 = Main.maxTilesY;
                }
                for (int k = num3; k < num4; k++)
                {
                    for (int l = num5; l < num6; l++)
                    {
                        if (WorldGen.CanEvilReplace(k, l) && Math.Abs((double)k - vector2D.X) + Math.Abs((double)l - vector2D.Y) < num2 * 0.5 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015) && Main.tile[k, l].type != 31 && Main.tile[k, l].type != 22 && Main.tile[k, l].type != 204)
{
                            Main.tile[k, l].active(false);
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.Y += (double)WorldGen.genRand.Next(-10, 10) * 0.1;
                if (vector2D.Y < (double)(j - 20))
                {
                    vector2D2.Y += (double)WorldGen.genRand.Next(20) * 0.01;
                }
                if (vector2D.Y > (double)(j + 20))
                {
                    vector2D2.Y -= (double)WorldGen.genRand.Next(20) * 0.01;
                }
                if (vector2D2.Y < -0.5)
                {
                    vector2D2.Y = -0.5;
                }
                if (vector2D2.Y > 0.5)
                {
                    vector2D2.Y = 0.5;
                }
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.01;
                if (direction == -1)
                {
                    if (vector2D2.X > -0.5)
                    {
                        vector2D2.X = -0.5;
                    }
                    if (vector2D2.X < -2.0)
                    {
                        vector2D2.X = -2.0;
                    }
                }
                else if (direction == 1)
                {
                    if (vector2D2.X < 0.5)
                    {
                        vector2D2.X = 0.5;
                    }
                    if (vector2D2.X > 2.0)
                    {
                        vector2D2.X = 2.0;
                    }
                }
                num3 = (int)(vector2D.X - num2 * 1.1);
                num4 = (int)(vector2D.X + num2 * 1.1);
                num5 = (int)(vector2D.Y - num2 * 1.1);
                num6 = (int)(vector2D.Y + num2 * 1.1);
                if (num3 < 1)
                {
                    num3 = 1;
                }
                if (num4 > Main.maxTilesX - 1)
                {
                    num4 = Main.maxTilesX - 1;
                }
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesY)
                {
                    num6 = Main.maxTilesY;
                }
                for (int m = num3; m < num4; m++)
                {
                    for (int n = num5; n < num6; n++)
                    {
                        if (WorldGen.CanEvilReplace(m, n) && Math.Abs((double)m - vector2D.X) + Math.Abs((double)n - vector2D.Y) < num2 * 1.1 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015) && Main.tile[m, n].wall != GenVars.ebonStoneWall)
{
                            if (!Main.tile[m, n].active() || (Main.tile[m, n].type != 31 && Main.tile[m, n].type != 22 && Main.tile[m, n].type != 204))
{
                                Main.tile[m, n].type = GenVars.ebonStone;
                            }
                            Main.tile[m, n].active(true);
                            if (Main.tile[m, n].wall == 2)
{
                                Main.tile[m, n].wall = 0;
                            }
                        }
                    }
                }
                for (int num7 = num3; num7 < num4; num7++)
                {
                    for (int num8 = num5; num8 < num6; num8++)
                    {
                        if (WorldGen.CanEvilReplace(num7, num8) && Math.Abs((double)num7 - vector2D.X) + Math.Abs((double)num8 - vector2D.Y) < num2 * 1.1 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015) && Main.tile[num7, num8].wall != GenVars.ebonStoneWall)
{
                            if (!Main.tile[num7, num8].active() || (Main.tile[num7, num8].type != 31 && Main.tile[num7, num8].type != 22 && Main.tile[num7, num8].type != 204))
{
                                Main.tile[num7, num8].type = GenVars.ebonStone;
                            }
                            Main.tile[num7, num8].active(true);
                            WorldGen.PlaceWall(num7, num8, (int)GenVars.ebonStoneWall, true);
                        }
                    }
                }
            }
            if (WorldGen.genRand.Next(3) == 0)
            {
                int num9 = (int)vector2D.X;
                int num10 = (int)vector2D.Y;
                while (!Main.tile[num9, num10].active())
                {
                    num10++;
                }
                WorldGen.TileRunner(num9, num10, (double)WorldGen.genRand.Next(2, 6), WorldGen.genRand.Next(3, 7), 22, false, 0.0, 0.0, false, true, -1);
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.CanEvilReplace(), Terraria.WorldBuilding.GenVars.ebonStone, Terraria.WorldBuilding.GenVars.ebonStoneWall, Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.PlaceWall(), Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.WorldGen.TileRunner(), Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.ChasmRunner().