Terraria Decompiled: Terraria.WorldGen.GetTreeLeaf
GetTreeLeaf()
static void Terraria.WorldGen.GetTreeLeaf (int x, Tile topTile, Tile t, ref int treeHeight, out int treeFrame, out int passStyle) inline static
Definition at line 26597 of file WorldGen.cs.
        {
            treeFrame = 0;
            passStyle = -1;
            if (topTile.frameX == 22 || topTile.frameX == 44 || topTile.frameX == 66)
            {
                if (topTile.frameY == 220)
                {
                    treeFrame = 1;
                }
                else if (topTile.frameY == 242)
                {
                    treeFrame = 2;
                }
            }
            if (topTile.frameX == 44 || topTile.frameX == 66)
            {
                if (topTile.frameY == 220)
                {
                    treeFrame = 1;
                }
                else if (topTile.frameY == 242)
                {
                    treeFrame = 2;
                }
            }
            ushort num = topTile.type;
            if (num <= 596)
            {
                if (num - 583 > 6)
                {
                    if (num == 596)
                    {
                        passStyle = 1248;
                    }
                }
                else
                {
                    passStyle = (int)(1249 + (topTile.type - 583));
                }
            }
            else if (num != 616)
            {
                if (num == 634)
                {
                    passStyle = 1278;
                }
            }
            else
            {
                passStyle = 1257;
            }
            if (passStyle > -1)
            {
                return;
            }
            num = t.type;
            if (num <= 112)
            {
                if (num <= 53)
                {
                    if (num == 2)
                    {
                        goto IL_017D;
                    }
                    if (num != 23)
                    {
                        if (num != 53)
{
                            return;
                        }
                        passStyle = 911;
                        return;
                    }
                }
                else if (num <= 70)
                {
                    if (num == 60)
                    {
                        passStyle = 914;
                        return;
                    }
                    if (num != 70)
                    {
                        return;
                    }
                    passStyle = 912;
                    return;
                }
                else
                {
                    if (num == 109)
                    {
                        goto IL_01CE;
                    }
                    if (num != 112)
                    {
                        return;
                    }
                }
                passStyle = 915;
                return;
            }
            if (num <= 199)
            {
                if (num == 116)
                {
                    passStyle = 919;
                    return;
                }
                if (num == 147)
                {
                    passStyle = 913;
                    return;
                }
                if (num != 199)
                {
                    return;
                }
            }
            else if (num <= 477)
            {
                if (num != 234)
                {
                    if (num != 477)
                    {
                        return;
                    }
                    goto IL_017D;
                }
            }
            else
            {
                if (num == 492)
                {
                    goto IL_01CE;
                }
                if (num != 633)
                {
                    return;
                }
                passStyle = 1278;
                return;
            }
            passStyle = 916;
            return;
            IL_017D:
            passStyle = 910;
            return;
            IL_01CE:
            int num2 = 917;
            int hollowTreeFoliageStyle = WorldGen.GetHollowTreeFoliageStyle();
            if (hollowTreeFoliageStyle != 20)
            {
                if (x % 3 == 1)
                {
                    treeFrame += 3;
                }
                if (x % 3 == 2)
                {
                    treeFrame += 6;
                }
                switch (treeFrame)
                {
                case 0:
                    passStyle = 2;
                    break;
                case 1:
                    passStyle = 1;
                    break;
                case 2:
                    passStyle = 7;
                    break;
                case 3:
                    passStyle = 4;
                    break;
                case 4:
                    passStyle = 5;
                    break;
                case 5:
                    passStyle = 6;
                    break;
                case 6:
                    passStyle = 3;
                    break;
                case 7:
                    passStyle = 8;
                    break;
                case 8:
                    passStyle = 0;
                    break;
                }
            }
            else
            {
                int num3 = 196;
                if (x % 6 == 1)
                {
                    treeFrame += 3;
                }
                else if (x % 6 == 2)
                {
                    treeFrame += 6;
                }
                else if (x % 6 == 3)
                {
                    treeFrame += 9;
                }
                else if (x % 6 == 4)
                {
                    treeFrame += 12;
                }
                else if (x % 6 == 5)
                {
                    treeFrame += 15;
                }
                switch (treeFrame)
                {
                case 0:
                    passStyle = num3;
                    break;
                case 1:
                    passStyle = num3;
                    break;
                case 2:
                    passStyle = num3;
                    break;
                case 3:
                    passStyle = num3 + 1;
                    break;
                case 4:
                    passStyle = num3 + 2;
                    break;
                case 5:
                    passStyle = num3 + 1;
                    break;
                case 6:
                    passStyle = num3 + 3;
                    break;
                case 7:
                    passStyle = num3 + 4;
                    break;
                case 8:
                    passStyle = num3 + 5;
                    break;
                case 9:
                    passStyle = num3 + 6;
                    break;
                case 10:
                    passStyle = num3 + 6;
                    break;
                case 11:
                    passStyle = num3 + 6;
                    break;
                case 12:
                    passStyle = num3 + 7;
                    break;
                case 13:
                    passStyle = num3 + 7;
                    break;
                case 14:
                    passStyle = num3 + 7;
                    break;
                case 15:
                    passStyle = num3 + 8;
                    break;
                case 16:
                    passStyle = num3 + 8;
                    break;
                case 17:
                    passStyle = num3 + 8;
                    break;
                }
            }
            passStyle += num2;
            treeHeight += 5;
        }
References Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetHollowTreeFoliageStyle(), int, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), and Terraria.WorldGen.TreeGrowFXCheck().