Terraria Decompiled: Terraria.WorldGen.KillTile_GetItemDrops
KillTile_GetItemDrops()
static void Terraria.WorldGen.KillTile_GetItemDrops (int x, int y, Tile tileCache, out int dropItem, out int dropItemStack, out int secondaryItem, out int secondaryItemStack, out bool noPrefix, bool includeLargeObjectDrops = false) inline static
Definition at line 63252 of file WorldGen.cs.
        {
            dropItem = 0;
            dropItemStack = 1;
            secondaryItem = 0;
            secondaryItemStack = 1;
            noPrefix = false;
            if (includeLargeObjectDrops)
            {
                ushort num = tileCache.type;
                if (num <= 88)
                {
                    if (num != 21)
                    {
                        if (num != 88)
{
                            goto IL_0078;
                        }
                        int num2 = (int)(tileCache.frameX / 54);
                        dropItem = WorldGen.GetItemDrop_Dressers(num2);
                        goto IL_0078;
                    }
                }
                else
                {
                    if (num == 215)
                    {
                        int num2 = (int)(tileCache.frameX / 54);
                        dropItem = WorldGen.GetCampfireItemDrop(num2);
                        goto IL_0078;
                    }
                    if (num != 467)
                    {
                        goto IL_0078;
                    }
                }
                dropItem = WorldGen.GetItemDrop_Chests(x, y, (int)tileCache.type);
            }
            IL_0078:
            switch (tileCache.type)
            {
            case 0:
            case 2:
            case 109:
            case 199:
            case 477:
            case 492:
                dropItem = 2;
                return;
            case 1:
                dropItem = 3;
                return;
            case 3:
                if (tileCache.frameX == 144)
                {
                    dropItem = 5;
                    return;
                }
                if (WorldGen.KillTile_ShouldDropSeeds(x, y))
                {
                    dropItem = 283;
                    return;
                }
                break;
            case 4:
            {
                int num2 = (int)(tileCache.frameY / 22);
                if (num2 == 0)
                {
                    dropItem = 8;
                    return;
                }
                if (num2 == 8)
                {
                    dropItem = 523;
                    return;
                }
                if (num2 == 9)
                {
                    dropItem = 974;
                    return;
                }
                if (num2 == 10)
                {
                    dropItem = 1245;
                    return;
                }
                if (num2 == 11)
                {
                    dropItem = 1333;
                    return;
                }
                if (num2 == 12)
                {
                    dropItem = 2274;
                    return;
                }
                if (num2 == 13)
                {
                    dropItem = 3004;
                    return;
                }
                if (num2 == 14)
                {
                    dropItem = 3045;
                    return;
                }
                if (num2 == 15)
                {
                    dropItem = 3114;
                    return;
                }
                if (num2 == 16)
                {
                    dropItem = 4383;
                    return;
                }
                if (num2 == 17)
                {
                    dropItem = 4384;
                    return;
                }
                if (num2 == 18)
                {
                    dropItem = 4385;
                    return;
                }
                if (num2 == 19)
                {
                    dropItem = 4386;
                    return;
                }
                if (num2 == 20)
                {
                    dropItem = 4387;
                    return;
                }
                if (num2 == 21)
                {
                    dropItem = 4388;
                    return;
                }
                if (num2 == 22)
                {
                    dropItem = 5293;
                    return;
                }
                if (num2 == 23)
                {
                    dropItem = 5353;
                    return;
                }
                dropItem = 426 + num2;
                return;
            }
            case 5:
            case 596:
            case 616:
            case 634:
            {
                bool flag = false;
                bool flag2 = false;
                WorldGen.KillTile_GetTreeDrops(x, y, tileCache, ref flag2, ref flag, ref dropItem, ref secondaryItem);
                if (flag)
                {
                    dropItemStack++;
                }
                if (SpecialSeedFeatures.ShouldDropExtraWood && flag2)
                {
                    dropItemStack *= 2;
                    return;
                }
                break;
            }
            case 6:
                dropItem = 11;
                return;
            case 7:
                dropItem = 12;
                return;
            case 8:
                dropItem = 13;
                return;
            case 9:
                dropItem = 14;
                return;
            case 10:
            case 11:
            case 12:
            case 14:
            case 15:
            case 16:
            case 17:
            case 18:
            case 20:
            case 21:
            case 26:
            case 27:
            case 28:
            case 29:
            case 31:
            case 32:
            case 34:
            case 35:
            case 42:
            case 55:
            case 69:
            case 77:
            case 79:
            case 82:
            case 85:
            case 86:
            case 87:
            case 88:
            case 89:
            case 90:
            case 91:
            case 92:
            case 93:
            case 94:
            case 95:
            case 96:
            case 97:
            case 98:
            case 99:
            case 100:
            case 101:
            case 102:
            case 103:
            case 104:
            case 105:
            case 106:
            case 113:
            case 114:
            case 115:
            case 125:
            case 126:
            case 127:
            case 128:
            case 132:
            case 133:
            case 134:
            case 138:
            case 139:
            case 142:
            case 143:
            case 162:
            case 165:
            case 172:
            case 173:
            case 184:
            case 185:
            case 186:
            case 187:
            case 192:
            case 205:
            case 207:
            case 209:
            case 212:
            case 215:
            case 216:
            case 217:
            case 218:
            case 219:
            case 220:
            case 228:
            case 231:
            case 233:
            case 235:
            case 236:
            case 237:
            case 238:
            case 240:
            case 241:
            case 242:
            case 243:
            case 244:
            case 245:
            case 246:
            case 247:
            case 254:
            case 269:
            case 270:
            case 271:
            case 275:
            case 276:
            case 277:
            case 278:
            case 279:
            case 280:
            case 281:
            case 282:
            case 283:
            case 285:
            case 286:
            case 287:
            case 288:
            case 289:
            case 290:
            case 291:
            case 292:
            case 293:
            case 294:
            case 295:
            case 296:
            case 297:
            case 298:
            case 299:
            case 300:
            case 301:
            case 302:
            case 303:
            case 304:
            case 305:
            case 306:
            case 307:
            case 308:
            case 309:
            case 310:
            case 316:
            case 317:
            case 318:
            case 319:
            case 320:
            case 334:
            case 335:
            case 337:
            case 338:
            case 339:
            case 349:
            case 352:
            case 354:
            case 355:
            case 356:
            case 358:
            case 359:
            case 360:
            case 361:
            case 362:
            case 363:
            case 364:
            case 373:
            case 374:
            case 375:
            case 376:
            case 377:
            case 378:
            case 384:
            case 386:
            case 387:
            case 388:
            case 389:
            case 390:
            case 391:
            case 392:
            case 393:
            case 394:
            case 395:
            case 405:
            case 406:
            case 410:
            case 411:
            case 412:
            case 413:
            case 414:
            case 425:
            case 440:
            case 441:
            case 443:
            case 444:
            case 452:
            case 453:
            case 454:
            case 455:
            case 456:
            case 457:
            case 461:
            case 462:
            case 463:
            case 464:
            case 465:
            case 466:
            case 467:
            case 468:
            case 469:
            case 470:
            case 471:
            case 475:
            case 480:
            case 481:
            case 482:
            case 483:
            case 484:
            case 485:
            case 486:
            case 487:
            case 488:
            case 489:
            case 490:
            case 491:
            case 493:
            case 497:
            case 499:
            case 504:
            case 505:
            case 506:
            case 509:
            case 510:
            case 511:
            case 518:
            case 521:
            case 522:
            case 523:
            case 524:
            case 525:
            case 526:
            case 527:
            case 529:
            case 530:
            case 531:
            case 532:
            case 533:
            case 538:
            case 542:
            case 543:
            case 544:
            case 545:
            case 547:
            case 548:
            case 549:
            case 550:
            case 551:
            case 552:
            case 553:
            case 554:
            case 555:
            case 556:
            case 558:
            case 559:
            case 560:
            case 564:
            case 565:
            case 567:
            case 568:
            case 569:
            case 570:
            case 572:
            case 573:
            case 580:
            case 581:
            case 582:
            case 590:
            case 591:
            case 592:
            case 594:
            case 595:
            case 597:
            case 598:
            case 599:
            case 600:
            case 601:
            case 602:
            case 603:
            case 604:
            case 605:
            case 606:
            case 607:
            case 608:
            case 609:
            case 610:
            case 611:
            case 612:
            case 613:
            case 614:
            case 615:
            case 617:
            case 619:
            case 620:
            case 621:
            case 622:
            case 623:
            case 629:
            case 632:
            case 636:
            case 638:
            case 639:
            case 640:
            case 642:
            case 643:
            case 644:
            case 645:
            case 647:
            case 648:
            case 649:
            case 651:
            case 652:
            case 653:
            case 654:
            case 655:
            case 657:
            case 658:
            case 660:
            case 663:
            case 664:
            case 665:
            case 694:
            case 695:
            case 696:
            case 698:
            case 699:
            case 702:
            case 704:
            case 705:
            case 706:
            case 709:
            case 710:
            case 711:
            case 712:
            case 713:
            case 714:
            case 715:
            case 716:
            case 720:
            case 721:
            case 723:
            case 724:
            case 725:
            case 733:
                break;
            case 13:
            {
                int num2 = (int)(tileCache.frameX / 18);
                dropItem = WorldGen.GetItemDrop_Bottles(num2);
                return;
            }
            case 19:
            {
                int num2 = (int)(tileCache.frameY / 18);
                dropItem = WorldGen.GetItemDrop_Platforms(num2);
                return;
            }
            case 22:
                dropItem = 56;
                return;
            case 23:
                dropItem = 2;
                return;
            case 24:
                if (tileCache.frameX == 144)
                {
                    dropItem = 60;
                    return;
                }
                break;
            case 25:
                dropItem = 61;
                return;
            case 30:
                dropItem = 9;
                return;
            case 33:
            {
                int num2 = (int)(tileCache.frameY / 22);
                dropItem = WorldGen.GetItemDrop_Candles(num2);
                return;
            }
            case 36:
                dropItem = 1869;
                return;
            case 37:
                dropItem = 116;
                return;
            case 38:
                dropItem = 129;
                return;
            case 39:
                dropItem = 131;
                return;
            case 40:
                dropItem = 133;
                return;
            case 41:
                dropItem = 134;
                return;
            case 43:
                dropItem = 137;
                return;
            case 44:
                dropItem = 139;
                return;
            case 45:
                dropItem = 141;
                return;
            case 46:
                dropItem = 143;
                return;
            case 47:
                dropItem = 145;
                return;
            case 48:
                dropItem = 147;
                return;
            case 49:
                dropItem = 148;
                return;
            case 50:
                if (tileCache.frameX == 90)
                {
                    dropItem = 165;
                    return;
                }
                dropItem = 149;
                return;
            case 51:
                dropItem = 150;
                return;
            case 52:
            case 62:
            case 382:
                if (Main.rand.Next(2) == 0 && WorldGen.GetPlayerForTile(x, y).cordage)
                {
                    dropItem = 2996;
                    return;
                }
                break;
            case 53:
                dropItem = 169;
                return;
            case 54:
                dropItem = 170;
                return;
            case 56:
                dropItem = 173;
                return;
            case 57:
                dropItem = 172;
                return;
            case 58:
                dropItem = 174;
                return;
            case 59:
            case 60:
            case 661:
            case 662:
                dropItem = 176;
                return;
            case 61:
            case 74:
                if (tileCache.frameX == 144 && tileCache.type == 61)
                {
                    dropItem = 331;
                    dropItemStack = Main.rand.Next(2, 4);
                    return;
                }
                if (tileCache.frameX == 162 && tileCache.type == 61)
                {
                    dropItem = 223;
                    return;
                }
                if (tileCache.frameX >= 108 && tileCache.frameX <= 126 && tileCache.type == 61 && Main.rand.Next(20) == 0)
                {
                    dropItem = 208;
                    return;
                }
                if (Main.rand.Next(100) == 0)
                {
                    dropItem = 195;
                    return;
                }
                break;
            case 63:
            case 64:
            case 65:
            case 66:
            case 67:
            case 68:
                dropItem = (int)(tileCache.type - 63 + 177);
                return;
            case 70:
                dropItem = 176;
                return;
            case 71:
            case 72:
                if (Main.rand.Next(40) == 0)
                {
                    dropItem = 194;
                    return;
                }
                if (Main.rand.Next(2) == 0)
                {
                    dropItem = 183;
                    return;
                }
                break;
            case 73:
                if (WorldGen.KillTile_ShouldDropSeeds(x, y))
                {
                    dropItem = 283;
                    return;
                }
                break;
            case 75:
                dropItem = 192;
                return;
            case 76:
                dropItem = 214;
                return;
            case 78:
                dropItem = 222;
                return;
            case 80:
                dropItem = 276;
                return;
            case 81:
                dropItem = 275;
                return;
            case 83:
            case 84:
            {
                int num2 = (int)(tileCache.frameX / 18);
                dropItem = 313 + num2;
                int num3 = 307 + num2;
                if (num2 == 6)
                {
                    dropItem = 2358;
                    num3 = 2357;
                }
                bool flag3 = WorldGen.IsHarvestableHerbWithSeed((int)tileCache.type, num2, y);
                if (WorldGen.GetPlayerForTile(x, y).staffOfRegrowthBonus)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    secondaryItem = num3;
                    secondaryItemStack = Main.rand.Next(1, 6);
                    return;
                }
                if (flag3)
                {
                    secondaryItem = num3;
                    secondaryItemStack = Main.rand.Next(1, 4);
                    return;
                }
                break;
            }
            case 107:
                dropItem = 364;
                return;
            case 108:
                dropItem = 365;
                return;
            case 110:
                if (tileCache.frameX == 144)
                {
                    dropItem = 5;
                    return;
                }
                break;
            case 111:
                dropItem = 366;
                return;
            case 112:
                dropItem = 370;
                return;
            case 116:
                dropItem = 408;
                return;
            case 117:
                dropItem = 409;
                return;
            case 118:
                dropItem = 412;
                return;
            case 119:
                dropItem = 413;
                return;
            case 120:
                dropItem = 414;
                return;
            case 121:
                dropItem = 415;
                return;
            case 122:
                dropItem = 416;
                return;
            case 123:
                dropItem = 424;
                return;
            case 124:
                dropItem = 480;
                return;
            case 129:
                if (tileCache.frameX >= 324)
                {
                    dropItem = 4988;
                    return;
                }
                dropItem = 502;
                return;
            case 130:
                dropItem = 511;
                return;
            case 131:
                dropItem = 512;
                return;
            case 135:
            {
                int num2 = (int)(tileCache.frameY / 18);
                if (num2 == 0)
                {
                    dropItem = 529;
                }
                if (num2 == 1)
                {
                    dropItem = 541;
                }
                if (num2 == 2)
                {
                    dropItem = 542;
                }
                if (num2 == 3)
                {
                    dropItem = 543;
                }
                if (num2 == 4)
                {
                    dropItem = 852;
                }
                if (num2 == 5)
                {
                    dropItem = 853;
                }
                if (num2 == 6)
                {
                    dropItem = 1151;
                    return;
                }
                break;
            }
            case 136:
                dropItem = 538;
                return;
            case 137:
            {
                int num2 = (int)(tileCache.frameY / 18);
                if (num2 == 0)
                {
                    dropItem = 539;
                }
                if (num2 == 1)
                {
                    dropItem = 1146;
                }
                if (num2 == 2)
                {
                    dropItem = 1147;
                }
                if (num2 == 3)
                {
                    dropItem = 1148;
                }
                if (num2 == 4)
                {
                    dropItem = 1149;
                }
                if (num2 == 5)
                {
                    dropItem = 5135;
                    return;
                }
                break;
            }
            case 140:
                dropItem = 577;
                return;
            case 141:
                dropItem = 580;
                return;
            case 144:
                if (tileCache.frameX == 0)
                {
                    dropItem = 583;
                }
                if (tileCache.frameX == 18)
                {
                    dropItem = 584;
                }
                if (tileCache.frameX == 36)
                {
                    dropItem = 585;
                }
                if (tileCache.frameX == 54)
                {
                    dropItem = 4484;
                }
                if (tileCache.frameX == 72)
                {
                    dropItem = 4485;
                    return;
                }
                break;
            case 145:
                dropItem = 586;
                return;
            case 146:
                dropItem = 591;
                return;
            case 147:
                dropItem = 593;
                return;
            case 148:
                dropItem = 594;
                return;
            case 149:
                if (tileCache.frameX == 0 || tileCache.frameX == 54)
                {
                    dropItem = 596;
                    return;
                }
                if (tileCache.frameX == 18 || tileCache.frameX == 72)
                {
                    dropItem = 597;
                    return;
                }
                if (tileCache.frameX == 36 || tileCache.frameX == 90)
                {
                    dropItem = 598;
                    return;
                }
                break;
            case 150:
                dropItem = 604;
                return;
            case 151:
                dropItem = 607;
                return;
            case 152:
                dropItem = 609;
                return;
            case 153:
                dropItem = 611;
                return;
            case 154:
                dropItem = 612;
                return;
            case 155:
                dropItem = 613;
                return;
            case 156:
                dropItem = 614;
                return;
            case 157:
                dropItem = 619;
                return;
            case 158:
                dropItem = 620;
                return;
            case 159:
                dropItem = 621;
                return;
            case 160:
                dropItem = 662;
                return;
            case 161:
                dropItem = 664;
                return;
            case 163:
                dropItem = 833;
                return;
            case 164:
                dropItem = 834;
                return;
            case 166:
                dropItem = 699;
                return;
            case 167:
                dropItem = 700;
                return;
            case 168:
                dropItem = 701;
                return;
            case 169:
                dropItem = 702;
                return;
            case 170:
                dropItem = 1872;
                return;
            case 171:
                if (tileCache.frameX >= 10)
                {
                    WorldGen.dropXmasTree(x, y, 0);
                    WorldGen.dropXmasTree(x, y, 1);
                    WorldGen.dropXmasTree(x, y, 2);
                    WorldGen.dropXmasTree(x, y, 3);
                    return;
                }
                break;
            case 174:
                dropItem = 713;
                return;
            case 175:
                dropItem = 717;
                return;
            case 176:
                dropItem = 718;
                return;
            case 177:
                dropItem = 719;
                return;
            case 178:
            {
                int num2 = (int)(tileCache.frameX / 18);
                if (num2 == 0)
                {
                    dropItem = 181;
                    return;
                }
                if (num2 == 1)
                {
                    dropItem = 180;
                    return;
                }
                if (num2 == 2)
                {
                    dropItem = 177;
                    return;
                }
                if (num2 == 3)
                {
                    dropItem = 179;
                    return;
                }
                if (num2 == 4)
                {
                    dropItem = 178;
                    return;
                }
                if (num2 == 5)
                {
                    dropItem = 182;
                    return;
                }
                if (num2 == 6)
                {
                    dropItem = 999;
                    return;
                }
                break;
            }
            case 179:
            case 180:
            case 181:
            case 182:
            case 183:
            case 381:
            case 534:
            case 536:
            case 539:
            case 625:
            case 627:
                dropItem = 3;
                return;
            case 188:
                dropItem = 276;
                return;
            case 189:
                dropItem = 751;
                return;
            case 190:
                dropItem = 183;
                return;
            case 191:
                dropItem = 9;
                return;
            case 193:
                dropItem = 762;
                return;
            case 194:
                dropItem = 154;
                return;
            case 195:
                dropItem = 763;
                return;
            case 196:
                dropItem = 765;
                return;
            case 197:
                dropItem = 767;
                return;
            case 198:
                dropItem = 775;
                return;
            case 200:
                dropItem = 835;
                return;
            case 201:
                if (tileCache.frameX == 270)
                {
                    dropItem = 2887;
                    return;
                }
                break;
            case 202:
                dropItem = 824;
                return;
            case 203:
                dropItem = 836;
                return;
            case 204:
                dropItem = 880;
                return;
            case 206:
                dropItem = 883;
                return;
            case 208:
                dropItem = 911;
                return;
            case 210:
                dropItem = 937;
                return;
            case 211:
                dropItem = 947;
                return;
            case 213:
                dropItem = 965;
                return;
            case 214:
                dropItem = 85;
                return;
            case 221:
                dropItem = 1104;
                return;
            case 222:
                dropItem = 1105;
                return;
            case 223:
                dropItem = 1106;
                return;
            case 224:
                dropItem = 1103;
                return;
            case 225:
                if (Main.rand.Next(3) == 0)
                {
                    tileCache.honey(true);
                    tileCache.liquid = byte.MaxValue;
                    return;
                }
                dropItem = 1124;
                if (Main.netMode != 1 && Main.rand.Next(2) == 0)
                {
                    int num4 = 1;
                    if (Main.rand.Next(3) == 0)
                    {
                        num4 = 2;
                    }
                    for (int i = 0; i < num4; i++)
                    {
                        int num5 = Main.rand.Next(210, 212);
                        int num6 = NPC.NewNPC(WorldGen.GetNPCSource_TileBreak(x, y), x * 16 + 8, y * 16 + 15, num5, 1, 0f, 0f, 0f, 0f, 255);
                        Main.npc[num6].velocity.X = (float)Main.rand.Next(-200, 201) * 0.002f;
                        Main.npc[num6].velocity.Y = (float)Main.rand.Next(-200, 201) * 0.002f;
                        Main.npc[num6].netUpdate = true;
                    }
                    return;
                }
                break;
            case 226:
                dropItem = 1101;
                return;
            case 227:
            {
                int num2 = (int)(tileCache.frameX / 34);
                dropItem = 1107 + num2;
                if (num2 >= 8 && num2 <= 11)
                {
                    dropItem = 3385 + num2 - 8;
                    return;
                }
                break;
            }
            case 229:
                dropItem = 1125;
                return;
            case 230:
                dropItem = 1127;
                return;
            case 232:
                dropItem = 1150;
                return;
            case 234:
                dropItem = 1246;
                return;
            case 239:
            {
                int num2 = (int)(tileCache.frameX / 18);
                if (num2 == 0)
                {
                    dropItem = 20;
                }
                if (num2 == 1)
                {
                    dropItem = 703;
                }
                if (num2 == 2)
                {
                    dropItem = 22;
                }
                if (num2 == 3)
                {
                    dropItem = 704;
                }
                if (num2 == 4)
                {
                    dropItem = 21;
                }
                if (num2 == 5)
                {
                    dropItem = 705;
                }
                if (num2 == 6)
                {
                    dropItem = 19;
                }
                if (num2 == 7)
                {
                    dropItem = 706;
                }
                if (num2 == 8)
                {
                    dropItem = 57;
                }
                if (num2 == 9)
                {
                    dropItem = 117;
                }
                if (num2 == 10)
                {
                    dropItem = 175;
                }
                if (num2 == 11)
                {
                    dropItem = 381;
                }
                if (num2 == 12)
                {
                    dropItem = 1184;
                }
                if (num2 == 13)
                {
                    dropItem = 382;
                }
                if (num2 == 14)
                {
                    dropItem = 1191;
                }
                if (num2 == 15)
                {
                    dropItem = 391;
                }
                if (num2 == 16)
                {
                    dropItem = 1198;
                }
                if (num2 == 17)
                {
                    dropItem = 1006;
                }
                if (num2 == 18)
                {
                    dropItem = 1225;
                }
                if (num2 == 19)
                {
                    dropItem = 1257;
                }
                if (num2 == 20)
                {
                    dropItem = 1552;
                }
                if (num2 == 21)
                {
                    dropItem = 3261;
                }
                if (num2 == 22)
                {
                    dropItem = 3467;
                    return;
                }
                break;
            }
            case 248:
                dropItem = 1589;
                return;
            case 249:
                dropItem = 1591;
                return;
            case 250:
                dropItem = 1593;
                return;
            case 251:
                dropItem = 1725;
                return;
            case 252:
                dropItem = 1727;
                return;
            case 253:
                dropItem = 1729;
                return;
            case 255:
            case 256:
            case 257:
            case 258:
            case 259:
            case 260:
            case 261:
                dropItem = (int)(1970 + tileCache.type - 255);
                return;
            case 262:
            case 263:
            case 264:
            case 265:
            case 266:
            case 267:
            case 268:
                dropItem = (int)(1970 + tileCache.type - 262);
                return;
            case 272:
                dropItem = 1344;
                return;
            case 273:
                dropItem = 2119;
                return;
            case 274:
                dropItem = 2120;
                return;
            case 284:
                dropItem = 2173;
                return;
            case 311:
                dropItem = 2260;
                return;
            case 312:
                dropItem = 2261;
                return;
            case 313:
                dropItem = 2262;
                return;
            case 314:
                dropItem = Minecart.GetTrackItem(tileCache);
                return;
            case 315:
                dropItem = 2435;
                return;
            case 321:
                dropItem = 2503;
                return;
            case 322:
                dropItem = 2504;
                return;
            case 323:
            {
                dropItem = 2504;
                if (Main.tenthAnniversaryWorld)
                {
                    dropItemStack += WorldGen.genRand.Next(2, 5);
                }
                if (tileCache.frameX <= 132 && tileCache.frameX >= 88)
                {
                    secondaryItem = 27;
                }
                int num7 = y;
                while (!Main.tile[x, num7].active() || !Main.tileSolid[(int)Main.tile[x, num7].type])
                {
                    num7++;
                }
                if (Main.tile[x, num7].active())
                {
                    ushort num = Main.tile[x, num7].type;
                    if (num != 112)
                    {
                        if (num != 116)
{
                            if (num == 234)
{
                                dropItem = 911;
                            }
                        }
                        else
{
                            dropItem = 621;
                        }
                    }
                    else
                    {
                        dropItem = 619;
                    }
                }
                if (SpecialSeedFeatures.ShouldDropExtraWood)
                {
                    dropItemStack *= 3;
                    return;
                }
                break;
            }
            case 324:
                switch (tileCache.frameY / 22)
                {
                case 0:
                    dropItem = 2625;
                    return;
                case 1:
                    dropItem = 2626;
                    return;
                case 2:
                    dropItem = 4072;
                    return;
                case 3:
                    dropItem = 4073;
                    return;
                case 4:
                    dropItem = 4071;
                    return;
                default:
                    return;
                }
                break;
            case 325:
                dropItem = 2692;
                return;
            case 326:
                dropItem = 2693;
                return;
            case 327:
                dropItem = 2694;
                return;
            case 328:
                dropItem = 2695;
                return;
            case 329:
                dropItem = 2697;
                return;
            case 330:
                dropItem = 71;
                return;
            case 331:
                dropItem = 72;
                return;
            case 332:
                dropItem = 73;
                return;
            case 333:
                dropItem = 74;
                return;
            case 336:
                dropItem = 2701;
                return;
            case 340:
                dropItem = 2751;
                return;
            case 341:
                dropItem = 2752;
                return;
            case 342:
                dropItem = 2753;
                return;
            case 343:
                dropItem = 2754;
                return;
            case 344:
                dropItem = 2755;
                return;
            case 345:
                dropItem = 2787;
                return;
            case 346:
                dropItem = 2792;
                return;
            case 347:
                dropItem = 2793;
                return;
            case 348:
                dropItem = 2794;
                return;
            case 350:
                dropItem = 2860;
                return;
            case 351:
                dropItem = 2868;
                return;
            case 353:
                dropItem = 2996;
                return;
            case 357:
                dropItem = 3066;
                return;
            case 365:
                dropItem = 3077;
                return;
            case 366:
                dropItem = 3078;
                return;
            case 367:
                dropItem = 3081;
                return;
            case 368:
                dropItem = 3086;
                return;
            case 369:
                dropItem = 3087;
                return;
            case 370:
                dropItem = 3100;
                return;
            case 371:
                dropItem = 3113;
                return;
            case 372:
                dropItem = 3117;
                return;
            case 379:
                dropItem = 3214;
                return;
            case 380:
            {
                int num2 = (int)(tileCache.frameY / 18);
                dropItem = 3215 + num2;
                return;
            }
            case 383:
                dropItem = 620;
                return;
            case 385:
                dropItem = 3234;
                return;
            case 396:
                dropItem = 3271;
                return;
            case 397:
                dropItem = 3272;
                return;
            case 398:
                dropItem = 3274;
                return;
            case 399:
                dropItem = 3275;
                return;
            case 400:
                dropItem = 3276;
                return;
            case 401:
                dropItem = 3277;
                return;
            case 402:
                dropItem = 3338;
                return;
            case 403:
                dropItem = 3339;
                return;
            case 404:
                dropItem = 3347;
                return;
            case 407:
                dropItem = 3380;
                return;
            case 408:
                dropItem = 3460;
                return;
            case 409:
                dropItem = 3461;
                return;
            case 415:
                dropItem = 3573;
                return;
            case 416:
                dropItem = 3574;
                return;
            case 417:
                dropItem = 3575;
                return;
            case 418:
                dropItem = 3576;
                return;
            case 419:
                switch (tileCache.frameX / 18)
                {
                case 0:
                    dropItem = 3602;
                    return;
                case 1:
                    dropItem = 3618;
                    return;
                case 2:
                    dropItem = 3663;
                    return;
                default:
                    return;
                }
                break;
            case 420:
                switch (tileCache.frameY / 18)
                {
                case 0:
                    dropItem = 3603;
                    return;
                case 1:
                    dropItem = 3604;
                    return;
                case 2:
                    dropItem = 3605;
                    return;
                case 3:
                    dropItem = 3606;
                    return;
                case 4:
                    dropItem = 3607;
                    return;
                case 5:
                    dropItem = 3608;
                    return;
                default:
                    return;
                }
                break;
            case 421:
                dropItem = 3609;
                return;
            case 422:
                dropItem = 3610;
                return;
            case 423:
                TELogicSensor.Kill(x, y);
                switch (tileCache.frameY / 18)
                {
                case 0:
                    dropItem = 3613;
                    return;
                case 1:
                    dropItem = 3614;
                    return;
                case 2:
                    dropItem = 3615;
                    return;
                case 3:
                    dropItem = 3726;
                    return;
                case 4:
                    dropItem = 3727;
                    return;
                case 5:
                    dropItem = 3728;
                    return;
                case 6:
                    dropItem = 3729;
                    return;
                default:
                    return;
                }
                break;
            case 424:
                dropItem = 3616;
                return;
            case 426:
                dropItem = 3621;
                return;
            case 427:
                dropItem = 3622;
                return;
            case 428:
                switch (tileCache.frameY / 18)
                {
                case 0:
                    dropItem = 3630;
                    break;
                case 1:
                    dropItem = 3632;
                    break;
                case 2:
                    dropItem = 3631;
                    break;
                case 3:
                    dropItem = 3626;
                    break;
                }
                PressurePlateHelper.DestroyPlate(new Point(x, y));
                return;
            case 429:
                dropItem = 3629;
                return;
            case 430:
                dropItem = 3633;
                return;
            case 431:
                dropItem = 3634;
                return;
            case 432:
                dropItem = 3635;
                return;
            case 433:
                dropItem = 3636;
                return;
            case 434:
                dropItem = 3637;
                return;
            case 435:
                dropItem = 3638;
                return;
            case 436:
                dropItem = 3639;
                return;
            case 437:
                dropItem = 3640;
                return;
            case 438:
                dropItem = 3641;
                return;
            case 439:
                dropItem = 3642;
                return;
            case 442:
                dropItem = 3707;
                return;
            case 445:
                dropItem = 3725;
                return;
            case 446:
                dropItem = 3736;
                return;
            case 447:
                dropItem = 3737;
                return;
            case 448:
                dropItem = 3738;
                return;
            case 449:
                dropItem = 3739;
                return;
            case 450:
                dropItem = 3740;
                return;
            case 451:
                dropItem = 3741;
                return;
            case 458:
                dropItem = 3754;
                return;
            case 459:
                dropItem = 3755;
                return;
            case 460:
                dropItem = 3756;
                return;
            case 472:
                dropItem = 3951;
                return;
            case 473:
                dropItem = 3953;
                return;
            case 474:
                dropItem = 3955;
                return;
            case 476:
                dropItem = 4040;
                return;
            case 478:
                dropItem = 4050;
                return;
            case 479:
                dropItem = 4051;
                return;
            case 494:
                dropItem = 4089;
                return;
            case 495:
                dropItem = 4090;
                return;
            case 496:
                dropItem = 4091;
                return;
            case 498:
                dropItem = 4139;
                return;
            case 500:
                dropItem = 4229;
                return;
            case 501:
                dropItem = 4230;
                return;
            case 502:
                dropItem = 4231;
                return;
            case 503:
                dropItem = 4232;
                return;
            case 507:
                dropItem = 4277;
                return;
            case 508:
                dropItem = 4278;
                return;
            case 512:
            case 513:
            case 514:
            case 515:
            case 516:
            case 517:
            case 535:
            case 537:
            case 540:
            case 626:
            case 628:
                dropItem = 129;
                return;
            case 519:
                if (tileCache.frameY == 90 && WorldGen.genRand.Next(2) == 0)
                {
                    dropItem = 183;
                    return;
                }
                break;
            case 520:
                dropItem = 4326;
                return;
            case 528:
                if (WorldGen.genRand.Next(2) == 0)
                {
                    dropItem = 183;
                    return;
                }
                break;
            case 541:
                dropItem = 4392;
                return;
            case 546:
            case 557:
                dropItem = 4422;
                return;
            case 561:
                dropItem = 4554;
                return;
            case 562:
                dropItem = 4564;
                return;
            case 563:
                dropItem = 4547;
                return;
            case 566:
                dropItem = 999;
                return;
            case 571:
                dropItem = 4564;
                dropItemStack = WorldGen.genRand.Next(1, 3);
                return;
            case 574:
                dropItem = 4717;
                return;
            case 575:
                dropItem = 4718;
                return;
            case 576:
                dropItem = 4719;
                return;
            case 577:
                dropItem = 4720;
                return;
            case 578:
                dropItem = 4721;
                return;
            case 579:
                dropItem = 4761;
                return;
            case 583:
                WorldGen.SetGemTreeDrops(180, 4851, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    return;
                }
                break;
            case 584:
                WorldGen.SetGemTreeDrops(181, 4852, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    return;
                }
                break;
            case 585:
                WorldGen.SetGemTreeDrops(177, 4853, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    return;
                }
                break;
            case 586:
                WorldGen.SetGemTreeDrops(179, 4854, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    return;
                }
                break;
            case 587:
                WorldGen.SetGemTreeDrops(178, 4855, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    return;
                }
                break;
            case 588:
                WorldGen.SetGemTreeDrops(182, 4856, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                }
                break;
            case 589:
                WorldGen.SetGemTreeDrops(999, 4857, tileCache, ref dropItem, ref secondaryItem);
                if (dropItem == 3)
                {
                    dropItemStack = Main.rand.Next(1, 3);
                    return;
                }
                break;
            case 593:
                dropItem = 4868;
                return;
            case 618:
                dropItem = 4962;
                return;
            case 624:
                dropItem = 5114;
                return;
            case 630:
                dropItem = 5137;
                return;
            case 631:
                dropItem = 5138;
                return;
            case 633:
                dropItem = 172;
                return;
            case 635:
                dropItem = 5215;
                return;
            case 637:
                if (Main.rand.Next(100) == 0)
                {
                    dropItem = 5214;
                    return;
                }
                break;
            case 641:
                dropItem = 5306;
                return;
            case 646:
                dropItem = 5322;
                return;
            case 650:
            {
                int num2 = (int)(tileCache.frameX / 18);
                if (num2 < 6)
                {
                    dropItem = 3;
                    return;
                }
                if (num2 < 12)
                {
                    dropItem = 2;
                    return;
                }
                if (num2 < 20)
                {
                    dropItem = 154;
                    return;
                }
                if (num2 < 28)
                {
                    dropItem = 154;
                    return;
                }
                if (num2 < 36)
                {
                    dropItem = 9;
                    return;
                }
                if (num2 < 42)
                {
                    dropItem = 593;
                    return;
                }
                if (num2 < 48)
                {
                    dropItem = 664;
                    return;
                }
                if (num2 < 54)
                {
                    dropItem = 150;
                    return;
                }
                if (num2 < 60)
                {
                    dropItem = 3271;
                    return;
                }
                if (num2 < 66)
                {
                    dropItem = 3086;
                    return;
                }
                if (num2 < 72)
                {
                    dropItem = 3081;
                    return;
                }
                if (num2 < 73)
                {
                    dropItem = 62;
                    return;
                }
                if (num2 == 73 || num2 == 74 || num2 == 76 || (num2 >= 78 && num2 <= 81))
                {
                    dropItem = 169;
                    return;
                }
                if (num2 == 75 || num2 == 77)
                {
                    dropItem = 276;
                    return;
                }
                break;
            }
            case 656:
                dropItem = 5333;
                return;
            case 659:
                dropItem = 5349;
                return;
            case 666:
                dropItem = 5395;
                return;
            case 667:
                dropItem = 5398;
                return;
            case 668:
                dropItem = 5400;
                return;
            case 669:
                dropItem = 5401;
                return;
            case 670:
                dropItem = 5402;
                return;
            case 671:
                dropItem = 5403;
                return;
            case 672:
                dropItem = 5404;
                return;
            case 673:
                dropItem = 5405;
                return;
            case 674:
                dropItem = 5406;
                return;
            case 675:
                dropItem = 5407;
                return;
            case 676:
                dropItem = 5408;
                return;
            case 677:
                dropItem = 5417;
                return;
            case 678:
                dropItem = 5419;
                return;
            case 679:
                dropItem = 5421;
                return;
            case 680:
                dropItem = 5423;
                return;
            case 681:
                dropItem = 5425;
                return;
            case 682:
                dropItem = 5427;
                return;
            case 683:
                dropItem = 5433;
                return;
            case 684:
                dropItem = 5435;
                return;
            case 685:
                dropItem = 5429;
                return;
            case 686:
                dropItem = 5431;
                return;
            case 687:
                dropItem = 5439;
                return;
            case 688:
                dropItem = 5440;
                return;
            case 689:
                dropItem = 5441;
                return;
            case 690:
                dropItem = 5442;
                return;
            case 691:
                dropItem = 5443;
                return;
            case 692:
                dropItem = 5444;
                return;
            case 693:
                dropItem = WorldGen.GetStalactiteEchoDrop(x, y, (int)(tileCache.frameX / 18));
                return;
            case 697:
                dropItem = 5471;
                return;
            case 700:
                dropItem = 5114;
                noPrefix = true;
                return;
            case 701:
                dropItem = 5333;
                return;
            case 703:
                switch (tileCache.frameX / 18)
                {
                case 6:
                case 7:
                    dropItem = 208;
                    return;
                case 8:
                    dropItem = 331;
                    return;
                case 9:
                    dropItem = 223;
                    noPrefix = true;
                    return;
                default:
                    dropItem = 195;
                    return;
                }
                break;
            case 707:
                if (tileCache.frameX == 90)
                {
                    dropItem = 165;
                    noPrefix = true;
                    return;
                }
                dropItem = 149;
                return;
            case 708:
                dropItem = 5493;
                return;
            case 717:
                dropItem = 5569;
                return;
            case 718:
                dropItem = 5570;
                return;
            case 719:
                dropItem = 5571;
                return;
            case 722:
                dropItem = 5622;
                return;
            case 726:
                dropItem = 929;
                return;
            case 727:
                dropItem = 5674;
                return;
            case 728:
                dropItem = 5675;
                return;
            case 729:
                dropItem = 5676;
                return;
            case 730:
                dropItem = 5677;
                return;
            case 731:
                dropItem = 5678;
                return;
            case 732:
                dropItem = 5679;
                return;
            case 734:
                dropItem = 5710;
                return;
            case 735:
                dropItem = 5733;
                return;
            case 736:
                dropItem = 5920;
                return;
            case 737:
                dropItem = 5922;
                return;
            case 738:
                dropItem = 5924;
                return;
            case 739:
                dropItem = 5926;
                return;
            case 740:
                dropItem = 5928;
                return;
            case 741:
                dropItem = 5930;
                return;
            case 742:
                dropItem = 5953;
                return;
            case 743:
                dropItem = 5996;
                return;
            case 744:
                dropItem = 6019;
                return;
            case 745:
                dropItem = 6042;
                return;
            case 746:
                dropItem = 6065;
                return;
            case 747:
                dropItem = 6088;
                return;
            case 748:
                dropItem = 6109;
                return;
            case 749:
                dropItem = 6132;
                return;
            case 750:
                dropItem = 6134;
                return;
            default:
                return;
            }
        }
References Terraria.Tile.active(), Terraria.Player.cordage, Terraria.GameContent.PressurePlateHelper.DestroyPlate(), Terraria.WorldGen.dropXmasTree(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.GetCampfireItemDrop(), Terraria.WorldGen.GetItemDrop_Bottles(), Terraria.WorldGen.GetItemDrop_Candles(), Terraria.WorldGen.GetItemDrop_Chests(), Terraria.WorldGen.GetItemDrop_Dressers(), Terraria.WorldGen.GetItemDrop_Platforms(), Terraria.WorldGen.GetNPCSource_TileBreak(), Terraria.WorldGen.GetPlayerForTile(), Terraria.WorldGen.GetStalactiteEchoDrop(), Terraria.Minecart.GetTrackItem(), Terraria.Tile.honey(), int, Terraria.WorldGen.IsHarvestableHerbWithSeed(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.WorldGen.KillTile_GetTreeDrops(), Terraria.WorldGen.KillTile_ShouldDropSeeds(), Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.rand, Terraria.WorldGen.SetGemTreeDrops(), Terraria.GameContent.SpecialSeedFeatures.ShouldDropExtraWood, Terraria.Player.staffOfRegrowthBonus, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.KillTile_DropItems(), Terraria.Player.PlaceThing_ValidTileForReplacement(), and Terraria.WorldGen.ShakeTree().