Terraria Decompiled: Terraria.WorldGen.SpreadGrassWalls
SpreadGrassWalls()
static void Terraria.WorldGen.SpreadGrassWalls (int wallDist, int i, int j) inline static
Definition at line 75390 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(i, j, 10))
            {
                return;
            }
            Tile tile = Main.tile[i, j];
            if (WallID.Sets.SpreadsCrimson[(int)tile.wall] || (tile.active() && tile.type >= 0 && TileID.Sets.SpreadsCrimson[(int)tile.type]))
            {
                int num = i + WorldGen.genRand.Next(-2, 3);
                int num2 = j + WorldGen.genRand.Next(-2, 3);
                if (WorldGen.InWorld(num, num2, 10) && Main.tile[num, num2].wall >= 63 && Main.tile[num, num2].wall <= 68)
                {
                    bool flag = false;
                    for (int k = i - wallDist; k <= i + wallDist; k++)
                    {
                        for (int l = j - wallDist; l <= j + wallDist; l++)
{
                            if (Main.tile[k, l].active())
{
                                int type = (int)Main.tile[k, l].type;
                                if (type >= 0 && TileID.Sets.SpreadsCrimson[type])
{
                                    flag = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag)
                    {
                        WorldGen.Convert(num, num2, 4, false, true);
                        return;
                    }
                }
            }
            else if (WallID.Sets.SpreadsCorruption[(int)tile.wall] || (tile.active() && tile.type >= 0 && TileID.Sets.SpreadsCorruption[(int)tile.type]))
            {
                int num3 = i + WorldGen.genRand.Next(-2, 3);
                int num4 = j + WorldGen.genRand.Next(-2, 3);
                if (WorldGen.InWorld(num3, num4, 10) && Main.tile[num3, num4].wall >= 63 && Main.tile[num3, num4].wall <= 68)
                {
                    bool flag2 = false;
                    for (int m = i - wallDist; m <= i + wallDist; m++)
                    {
                        for (int n = j - wallDist; n <= j + wallDist; n++)
{
                            if (Main.tile[m, n].active())
{
                                int type2 = (int)Main.tile[m, n].type;
                                if (type2 >= 0 && TileID.Sets.SpreadsCorruption[type2])
{
                                    flag2 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag2)
                    {
                        WorldGen.Convert(num3, num4, 1, false, true);
                        return;
                    }
                }
            }
            else if (WallID.Sets.SpreadsHallow[(int)tile.wall] || (tile.active() && tile.type >= 0 && TileID.Sets.SpreadsHallow[(int)tile.type]))
            {
                int num5 = i + WorldGen.genRand.Next(-2, 3);
                int num6 = j + WorldGen.genRand.Next(-2, 3);
                if ((WorldGen.InWorld(num5, num6, 10) && Main.tile[num5, num6].wall == 63) || Main.tile[num5, num6].wall == 65 || Main.tile[num5, num6].wall == 66 || Main.tile[num5, num6].wall == 68)
                {
                    bool flag3 = false;
                    for (int num7 = i - wallDist; num7 <= i + wallDist; num7++)
                    {
                        for (int num8 = j - wallDist; num8 <= j + wallDist; num8++)
{
                            if (Main.tile[num7, num8].active())
{
                                int type3 = (int)Main.tile[num7, num8].type;
                                if (type3 >= 0 && TileID.Sets.SpreadsHallow[type3])
{
                                    flag3 = true;
                                    break;
                                }
                            }
                        }
                    }
                    if (flag3)
                    {
                        WorldGen.Convert(num5, num6, 2, false, true);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.Convert(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.SpreadsCorruption, Terraria.ID.WallID.Sets.SpreadsCorruption, Terraria.ID.TileID.Sets.SpreadsCrimson, Terraria.ID.WallID.Sets.SpreadsCrimson, Terraria.ID.TileID.Sets.SpreadsHallow, Terraria.ID.WallID.Sets.SpreadsHallow, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().