Terraria Decompiled: Terraria.WorldGen.LavaLayerCaverer
LavaLayerCaverer()
static void Terraria.WorldGen.LavaLayerCaverer () inline static
Definition at line 74418 of file WorldGen.cs.
        {
            int num = 2;
            int num2 = 8;
            int num3 = 30;
            int num4 = -1;
            int num5 = GenVars.waterLine - 1;
            int num6 = GenVars.waterLine + 1;
            int num7 = GenVars.waterLine - num3;
            int num8 = num7;
            int i = 10;
            while (i < Main.maxTilesX - 10)
            {
                i++;
                if (WorldGen.genRand.Next(4) == 0)
                {
                    num8 += WorldGen.genRand.Next(-4, 5);
                    if (num8 < num7 - num3)
                    {
                        num8 = num7 - num3;
                    }
                    if (num8 > num7 + num3)
                    {
                        num8 = num7 + num3;
                    }
                }
                if (WorldGen.genRand.Next(3) == 0)
                {
                    num5 += WorldGen.genRand.Next(-4, 5);
                    if (num5 < num8 - num2)
                    {
                        num5 = num8 - num2;
                    }
                    if (num5 > num8 - num)
                    {
                        num5 = num8 - num;
                    }
                }
                if (WorldGen.genRand.Next(3) == 0)
                {
                    num6 += WorldGen.genRand.Next(-4, 5);
                    if (num6 > num8 + num2)
                    {
                        num6 = num8 + num2;
                    }
                    if (num6 < num8 + num)
                    {
                        num6 = num8 + num;
                    }
                }
                for (int j = num5; j <= num6; j++)
                {
                    WorldGen.KillTile(i, j, false, false, false);
                    if (!Main.tile[i, j].active() && !Main.wallDungeon[(int)Main.tile[i, j].wall] && WorldGen.genRand.Next(15) == 0)
                    {
                        Main.tile[i, j].liquid = byte.MaxValue;
                        Main.tile[i, j].lava(true);
                    }
                }
                bool flag = true;
                for (int k = num5 - 1; k <= num6 + 1; k++)
                {
                    if (Main.wallDungeon[(int)Main.tile[i, k].wall])
                    {
                        if (k > num5 && k < num6)
{
                            flag = false;
                        }
                        if (Main.wallDungeon[(int)Main.tile[i, num5].wall] && Main.tile[i, num5].wall == Main.tile[i, num6].wall)
{
                            num4 = (int)Main.tile[i, num5].wall;
                        }
                        if (num4 < 0)
{
                            num4 = (int)Main.tile[i, k].wall;
                        }
                        else
{
                            Main.tile[i, k].wall = (ushort)num4;
                        }
                        if ((!Main.wallDungeon[(int)Main.tile[i, num5 - 2].wall] && !Main.tileDungeon[(int)Main.tile[i, num5 - 2].type]) || (!Main.wallDungeon[(int)Main.tile[i, num6 + 2].wall] && !Main.tileDungeon[(int)Main.tile[i, num6 + 3].type]))
{
                            Main.tile[i, k].wall = 0;
                        }
                    }
                }
                if (flag)
                {
                    num4 = -1;
                }
                for (int l = num5; l < Main.maxTilesY - 50; l++)
                {
                    if (!Main.wallDungeon[(int)Main.tile[i, l].wall] && Main.tile[i, l].liquid > 0)
                    {
                        Main.tile[i, l].lava(true);
                    }
                    if (Main.tile[i, l].type == 161)
                    {
                        Main.tile[i, l].type = 1;
                    }
                    if (Main.tile[i, l].type == 147)
                    {
                        Main.tile[i, l].type = 0;
                    }
                }
            }
            for (int m = 10; m < Main.maxTilesX - 10; m++)
            {
                for (int n = num7 - num3 - 10; n < num7 + num3 + 10; n++)
                {
                    if (Main.wallDungeon[(int)Main.tile[m, n].wall])
                    {
                        int num9 = m + 20;
                        for (int num10 = m + 1; num10 <= num9; num10++)
{
                            if (Main.wallDungeon[(int)Main.tile[num10, n].wall])
{
                                num9 = num10;
                                break;
                            }
                        }
                        if (Main.wallDungeon[(int)Main.tile[num9, n].wall])
{
                            for (int num11 = m; num11 <= num9; num11++)
{
                                if (!Main.wallDungeon[(int)Main.tile[num11, n].wall])
{
                                    Main.tile[num11, n].wall = Main.tile[m, n].wall;
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.AddPasses().