Terraria Decompiled: Terraria.WorldGen.AnchorValid
AnchorValid()
static bool Terraria.WorldGen.AnchorValid (Tile tileCache, AnchorType anchor) inline static
Definition at line 50358 of file WorldGen.cs.
        {
            bool flag = false;
            if (tileCache.nactive())
            {
                if ((anchor & AnchorType.SolidTile) == AnchorType.SolidTile && Main.tileSolid[(int)tileCache.type] && !Main.tileSolidTop[(int)tileCache.type] && !Main.tileNoAttach[(int)tileCache.type] && tileCache.blockType() == 0)
                {
                    flag = true;
                }
                if ((anchor & AnchorType.SolidBottom) == AnchorType.SolidBottom && ((Main.tileSolid[(int)tileCache.type] && (!Main.tileSolidTop[(int)tileCache.type] || (TileID.Sets.Platforms[(int)tileCache.type] && (tileCache.halfBrick() || tileCache.topSlope())))) || tileCache.topSlope() || tileCache.halfBrick()) && !TileID.Sets.NotReallySolid[(int)tileCache.type] && !tileCache.bottomSlope())
                {
                    flag = true;
                }
                if (!flag && ((anchor & AnchorType.SolidWithTop) == AnchorType.SolidWithTop || (anchor & AnchorType.Table) == AnchorType.Table))
                {
                    if (TileID.Sets.Platforms[(int)tileCache.type])
                    {
                        int num = (int)tileCache.frameX / TileObjectData.PlatformFrameWidth();
                        if ((!tileCache.halfBrick() && num >= 0 && num <= 7) || (num >= 12 && num <= 16) || (num >= 25 && num <= 26))
{
                            flag = true;
                        }
                    }
                    else if (Main.tileSolid[(int)tileCache.type] && Main.tileSolidTop[(int)tileCache.type])
                    {
                        flag = true;
                    }
                }
                if (!flag && (anchor & AnchorType.Table) == AnchorType.Table && !TileID.Sets.Platforms[(int)tileCache.type] && Main.tileTable[(int)tileCache.type] && tileCache.blockType() == 0)
                {
                    flag = true;
                }
                if (!flag && (anchor & AnchorType.SolidSide) == AnchorType.SolidSide && Main.tileSolid[(int)tileCache.type] && !Main.tileSolidTop[(int)tileCache.type])
                {
                    int num2 = tileCache.blockType();
                    if (num2 - 4 <= 1)
                    {
                        flag = true;
                    }
                }
            }
            else if (!flag && (anchor & AnchorType.EmptyTile) == AnchorType.EmptyTile)
            {
                flag = true;
            }
            return flag;
        }
References Terraria.Tile.blockType(), Terraria.Tile.bottomSlope(), Terraria.Tile.frameX, Terraria.Tile.halfBrick(), int, Terraria.Tile.nactive(), Terraria.ID.TileID.Sets.NotReallySolid, Terraria.ObjectData.TileObjectData.PlatformFrameWidth(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileTable, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTileAnchors(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().