Terraria Decompiled: Terraria.WorldGen.SkyblockIsland
SkyblockIsland()
static bool Terraria.WorldGen.SkyblockIsland (int i, int j, int islandStyle, bool forceProximityCheck = false) inline static
Definition at line 19946 of file WorldGen.cs.
        {
            if (forceProximityCheck || islandStyle > 1)
            {
                for (int k = i - 200; k <= i + 200; k++)
                {
                    for (int l = j - 100; l <= j + 100; l++)
                    {
                        if (WorldGen.InWorld(k, l, 0) && Main.tile[k, l].active())
{
                            return false;
                        }
                    }
                }
            }
            double num = (double)WorldGen.genRand.Next(220, 250);
            float num2 = 4.5f;
            float num3 = 4f;
            int num4 = 0;
            int num5 = -1;
            int num6 = -1;
            int num7 = 189;
            int num8 = 189;
            int num9 = 196;
            int num10 = 73;
            int num11 = 56;
            if (islandStyle <= 1 || islandStyle == 13)
            {
                if (j > Main.UnderworldLayer)
                {
                    num4 = 57;
                }
                else if (WorldGen.notTheBees && (islandStyle == 0 || islandStyle == 13))
                {
                    num4 = 59;
                    num7 = 225;
                    num10 = 86;
                }
            }
            if (islandStyle == 1)
            {
                num = (double)WorldGen.genRand.Next(145, 156);
                num2 = 2.25f;
                num3 = 1.75f;
            }
            else if (islandStyle != 0 && islandStyle != 13)
            {
                num = (double)WorldGen.genRand.Next(145, 156);
                num2 = 2.5f;
                num3 = 2.5f;
            }
            if (islandStyle == 2)
            {
                if ((double)j > Main.worldSurface)
                {
                    num4 = 161;
                }
                else
                {
                    num4 = 147;
                }
                num9 = 460;
            }
            if (islandStyle == 3)
            {
                num4 = 53;
                num9 = 189;
            }
            if (islandStyle == 4)
            {
                if (j > Main.UnderworldLayer)
                {
                    num4 = 57;
                    num6 = 633;
                    num9 = 717;
                }
                else if ((double)j > Main.worldSurface)
                {
                    num4 = 1;
                }
                else
                {
                    num6 = 2;
                }
            }
            if (islandStyle == 5)
            {
                if ((double)j > Main.worldSurface)
                {
                    num4 = 117;
                }
                else
                {
                    num6 = 109;
                }
            }
            if (islandStyle == 6)
            {
                if ((double)j > Main.worldSurface)
                {
                    num4 = 25;
                }
                else
                {
                    num6 = 23;
                }
            }
            if (islandStyle == 7)
            {
                if ((double)j > Main.worldSurface)
                {
                    num4 = 203;
                }
                else
                {
                    num6 = 199;
                }
            }
            if (islandStyle == 8)
            {
                num4 = 59;
                num6 = 70;
            }
            if (islandStyle == 9)
            {
                num5 = 0;
                num7 = 196;
                num8 = 196;
                num9 = 189;
            }
            if (islandStyle == 10)
            {
                num5 = 1;
                num9 = 189;
                num7 = 717;
            }
            if (islandStyle == 11)
            {
                num5 = 2;
                num9 = 189;
            }
            if (islandStyle == 12)
            {
                num5 = 3;
                num9 = 189;
            }
            if (num9 == 196 && (double)j > (Main.rockLayer + (double)Main.UnderworldLayer) / 2.0)
            {
                num9 = 717;
            }
            double num12 = (double)WorldGen.genRand.Next(20, 30);
            double num13 = num;
            int num14 = i;
            int num15 = i;
            int num16 = j;
            int num17 = j;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            while (vector2D2.X > -2.0 && vector2D2.X < 2.0)
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            }
            vector2D2.Y = (double)WorldGen.genRand.Next(-20, -10) * 0.02;
            while (num > 0.0 && num12 > 0.0)
            {
                num -= (double)WorldGen.genRand.Next(4);
                num12 -= 1.0;
                int num18 = (int)(vector2D.X - num * 0.5);
                int num19 = (int)(vector2D.X + num * 0.5);
                int num20 = (int)(vector2D.Y - num * 0.5);
                int num21 = (int)(vector2D.Y + num * 0.5);
                if (num18 < 0)
                {
                    num18 = 0;
                }
                if (num19 > Main.maxTilesX)
                {
                    num19 = Main.maxTilesX;
                }
                if (num20 < 0)
                {
                    num20 = 0;
                }
                if (num21 > Main.maxTilesY)
                {
                    num21 = Main.maxTilesY;
                }
                double num22 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                double num23 = vector2D.Y + 1.0;
                for (int m = num18; m < num19; m++)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num23 += (double)WorldGen.genRand.Next(-1, 2);
                    }
                    if (num23 < vector2D.Y)
                    {
                        num23 = vector2D.Y;
                    }
                    if (num23 > vector2D.Y + 2.0)
                    {
                        num23 = vector2D.Y + 2.0;
                    }
                    for (int n = num20; n < num21; n++)
                    {
                        if (WorldGen.InWorld(m, n, 5) && (double)n > num23 + 1.0)
{
                            double num24 = Math.Abs((double)m - vector2D.X);
                            double num25 = Math.Abs((double)n - vector2D.Y) * (double)num2;
                            if (Math.Sqrt(num24 * num24 + num25 * num25) < num22 * 0.4)
{
                                if (m < num14)
{
                                    num14 = m;
                                }
                                if (m > num15)
{
                                    num15 = m;
                                }
                                if (n < num16)
{
                                    num16 = n;
                                }
                                if (n > num17)
{
                                    num17 = n;
                                }
                                Main.tile[m, n].active(true);
                                Main.tile[m, n].type = (ushort)num7;
                                WorldGen.SquareTileFrame(m, n, true);
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-20, 21) * 0.05;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                if (vector2D2.Y > 0.2)
                {
                    vector2D2.Y = -0.2;
                }
                if (vector2D2.Y < -0.2)
                {
                    vector2D2.Y = -0.2;
                }
            }
            int num26 = num14;
            num26 += WorldGen.genRand.Next(5);
            while (num26 < num15)
            {
                int num27 = num17 + 10;
                while (!Main.tile[num26, num27].active())
                {
                    num27--;
                    if (num27 <= 0)
                    {
                        break;
                    }
                }
                if (num27 <= 0)
                {
                    num26 += WorldGen.genRand.Next(5);
                }
                else
                {
                    num27 += WorldGen.genRand.Next(-3, 4);
                    int num28 = WorldGen.genRand.Next(4, 8);
                    int num29 = num7;
                    if (WorldGen.genRand.Next(4) == 0)
                    {
                        num29 = num9;
                    }
                    for (int num30 = num26 - num28; num30 <= num26 + num28; num30++)
                    {
                        for (int num31 = num27 - num28; num31 <= num27 + num28; num31++)
{
                            if (WorldGen.InWorld(num30, num31, 5) && num31 > num16)
{
                                double num32 = (double)Math.Abs(num30 - num26);
                                double num33 = (double)(Math.Abs(num31 - num27) * 2);
                                if (Math.Sqrt(num32 * num32 + num33 * num33) < (double)(num28 + WorldGen.genRand.Next(2)))
{
                                    Main.tile[num30, num31].active(true);
                                    Main.tile[num30, num31].type = (ushort)num29;
                                    WorldGen.SquareTileFrame(num30, num31, true);
                                }
                            }
                        }
                    }
                    num26 += WorldGen.genRand.Next(num28, (int)((double)num28 * 1.5));
                }
            }
            num = num13 * 0.800000011920929;
            num12 = (double)WorldGen.genRand.Next(10, 15);
            vector2D.X = (double)i;
            vector2D.Y = (double)num16;
            vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            while (vector2D2.X > -2.0 && vector2D2.X < 2.0)
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            }
            vector2D2.Y = (double)WorldGen.genRand.Next(-20, -10) * 0.02;
            while (num > 0.0 && num12 > 0.0)
            {
                num -= (double)WorldGen.genRand.Next(4);
                num12 -= 1.0;
                int num18 = (int)(vector2D.X - num * 0.5);
                int num19 = (int)(vector2D.X + num * 0.5);
                int num20 = num16 - 1;
                int num21 = (int)(vector2D.Y + num * 0.5);
                if (num18 < 0)
                {
                    num18 = 0;
                }
                if (num19 > Main.maxTilesX)
                {
                    num19 = Main.maxTilesX;
                }
                if (num20 < 0)
                {
                    num20 = 0;
                }
                if (num21 > Main.maxTilesY)
                {
                    num21 = Main.maxTilesY;
                }
                double num22 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                double num34 = vector2D.Y + 1.0;
                for (int num35 = num18; num35 < num19; num35++)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num34 += (double)WorldGen.genRand.Next(-1, 2);
                    }
                    if (num34 < vector2D.Y)
                    {
                        num34 = vector2D.Y;
                    }
                    if (num34 > vector2D.Y + 2.0)
                    {
                        num34 = vector2D.Y + 2.0;
                    }
                    for (int num36 = num20; num36 < num21; num36++)
                    {
                        if (WorldGen.InWorld(num35, num36, 5) && (double)num36 > num34)
{
                            double num37 = Math.Abs((double)num35 - vector2D.X);
                            double num38 = Math.Abs((double)num36 - vector2D.Y) * (double)num3;
                            if (Math.Sqrt(num37 * num37 + num38 * num38) < num22 * 0.4 && (int)Main.tile[num35, num36].type == num7)
{
                                if (num5 >= 0)
{
                                    Main.tile[num35, num36].liquid = byte.MaxValue;
                                    Main.tile[num35, num36].liquidType(num5);
                                    Main.tile[num35, num36].active(false);
                                }
                                else
{
                                    Main.tile[num35, num36].type = (ushort)num4;
                                }
                                WorldGen.SquareTileFrame(num35, num36, true);
                            }
                        }
                    }
                }
                if (num5 >= 0)
                {
                    vector2D.X += vector2D2.X;
                    vector2D.Y -= 0.5;
                }
                else
                {
                    vector2D += vector2D2;
                    vector2D2.X += (double)WorldGen.genRand.Next(-20, 21) * 0.05;
                }
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                if (vector2D2.Y > 0.2)
                {
                    vector2D2.Y = -0.2;
                }
                if (vector2D2.Y < -0.2)
                {
                    vector2D2.Y = -0.2;
                }
            }
            int num39 = num14;
            num39 += WorldGen.genRand.Next(5);
            while (num39 < num15)
            {
                int num40 = num17;
                if (num5 >= 0)
                {
                    while (Main.tile[num39, num40].liquid == 0)
                    {
                        if (num39 >= num15)
{
                            break;
                        }
                        num40--;
                        if (num40 < num16)
{
                            num40 = num17;
                            num39 += WorldGen.genRand.Next(1, 4);
                        }
                    }
                }
                else
                {
                    while ((!Main.tile[num39, num40].active() || (int)Main.tile[num39, num40].type != num4) && num39 < num15)
                    {
                        num40--;
                        if (num40 < num16)
{
                            num40 = num17;
                            num39 += WorldGen.genRand.Next(1, 4);
                        }
                    }
                }
                if (num39 < num15)
                {
                    num40 += WorldGen.genRand.Next(0, 4);
                    int num41 = WorldGen.genRand.Next(2, 8);
                    int num42 = num7;
                    for (int num43 = num39 - num41; num43 <= num39 + num41; num43++)
                    {
                        for (int num44 = num40 - num41; num44 <= num40 + num41; num44++)
{
                            if (WorldGen.InWorld(num43, num44, 5) && num44 > num16)
{
                                double num45 = (double)Math.Abs(num43 - num39);
                                double num46 = (double)(Math.Abs(num44 - num40) * 2);
                                if (Math.Sqrt(num45 * num45 + num46 * num46) < (double)num41)
{
                                    Main.tile[num43, num44].type = (ushort)num42;
                                    if (num5 >= 0)
{
                                        Main.tile[num43, num44].active(true);
                                    }
                                    WorldGen.SquareTileFrame(num43, num44, true);
                                }
                            }
                        }
                    }
                    num39 += WorldGen.genRand.Next(num41, (int)((double)num41 * 1.5));
                }
            }
            if (islandStyle == 1)
            {
                num = (double)WorldGen.genRand.Next(40, 51);
                num12 = (double)WorldGen.genRand.Next(3, 5);
                vector2D.X = (double)i;
                vector2D.Y = (double)num16;
                vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
                while (vector2D2.X > -2.0)
                {
                    if (vector2D2.X >= 2.0)
                    {
                        break;
                    }
                    vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
                }
                while (num > 0.0 && num12 > 0.0)
                {
                    num -= (double)WorldGen.genRand.Next(4);
                    num12 -= 1.0;
                    int num18 = (int)(vector2D.X - num * 0.5);
                    int num19 = (int)(vector2D.X + num * 0.5);
                    int num20 = num16 - 1;
                    int num21 = (int)(vector2D.Y + num * 0.5);
                    if (num18 < 0)
                    {
                        num18 = 0;
                    }
                    if (num19 > Main.maxTilesX)
                    {
                        num19 = Main.maxTilesX;
                    }
                    if (num20 < 0)
                    {
                        num20 = 0;
                    }
                    if (num21 > Main.maxTilesY)
                    {
                        num21 = Main.maxTilesY;
                    }
                    double num22 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                    double num47 = vector2D.Y + 1.0;
                    for (int num48 = num18; num48 < num19; num48++)
                    {
                        if (num47 < vector2D.Y)
{
                            num47 = vector2D.Y;
                        }
                        if (num47 > vector2D.Y + 2.0)
{
                            num47 = vector2D.Y + 2.0;
                        }
                        for (int num49 = num20; num49 < num21; num49++)
{
                            if (WorldGen.InWorld(num48, num49, 5))
{
                                if ((double)num49 > num47)
{
                                    double num50 = Math.Abs((double)num48 - vector2D.X);
                                    double num51 = Math.Abs((double)num49 - vector2D.Y) * 1.3;
                                    double num52 = Math.Sqrt(num50 * num50 + num51 * num51);
                                    if (num52 < num22 * 0.4)
{
                                        if (!Main.tile[num48, num49].anyShimmer())
{
                                            Main.tile[num48, num49].type = (ushort)num11;
                                            Main.tile[num48, num49].active(true);
                                        }
                                        if (!Main.tile[num48, num49 + 1].anyShimmer())
{
                                            Main.tile[num48, num49 + 1].type = (ushort)num11;
                                            Main.tile[num48, num49 + 1].active(true);
                                        }
                                        WorldGen.SquareTileFrame(num48, num49, true);
                                    }
                                    if (num52 < num22 * 0.3)
{
                                        Main.tile[num48, num49].active(false);
                                        Main.tile[num48, num49].liquid = byte.MaxValue;
                                        Main.tile[num48, num49].shimmer(true);
                                        if (Main.tile[num48, num49 - 1].active())
{
                                            Main.tile[num48, num49 - 1].active(false);
                                            Main.tile[num48, num49 - 1].liquid = byte.MaxValue;
                                            Main.tile[num48, num49 - 1].shimmer(true);
                                        }
                                        WorldGen.SquareTileFrame(num48, num49, true);
                                    }
                                }
                                if ((double)num49 > num47 - 5.0 && (double)num49 <= num47)
{
                                    Main.tile[num48, num49].active(false);
                                }
                            }
                        }
                    }
                    vector2D.X += vector2D2.X;
                    vector2D2.X += (double)WorldGen.genRand.Next(-20, 21) * 0.05;
                    if (vector2D2.X > 1.0)
                    {
                        vector2D2.X = 1.0;
                    }
                    if (vector2D2.X < -1.0)
                    {
                        vector2D2.X = -1.0;
                    }
                }
            }
            for (int num53 = num14 - 20; num53 <= num15 + 20; num53++)
            {
                for (int num54 = num16 - 20; num54 <= num17 + 20; num54++)
                {
                    if (WorldGen.InWorld(num53, num54, 5))
                    {
                        bool flag = true;
                        for (int num55 = num53 - 1; num55 <= num53 + 1; num55++)
{
                            for (int num56 = num54 - 1; num56 <= num54 + 1; num56++)
{
                                if (WorldGen.InWorld(num55, num56, 0) && (!Main.tile[num55, num56].active() || (Main.tile[num55, num56].wall > 0 && (int)Main.tile[num55, num56].wall != num10)))
{
                                    flag = false;
                                }
                            }
                        }
                        if (flag)
{
                            Main.tile[num53, num54].wall = (ushort)num10;
                            WorldGen.SquareWallFrame(num53, num54, true);
                        }
                    }
                }
            }
            if ((islandStyle == 0 || islandStyle == 13) && WorldGen.Skyblock.spawnSolidifier)
            {
                bool flag2 = true;
                int num57 = 10000;
                int num58 = 20;
                while (flag2 && num57 > 0)
                {
                    num57--;
                    if (num57 % 20 == 0)
                    {
                        num58++;
                    }
                    int num59 = WorldGen.genRand.Next(i - num58, i + num58);
                    num59 = Utils.Clamp<int>(num59, num14, num15);
                    int num60 = 5;
                    int num61 = num60 + 1;
                    if (WorldGen.InWorld(num59, num61, num60))
                    {
                        while (!Main.tile[num59, num61].active() && num61 < Main.maxTilesY - 10)
{
                            num61++;
                        }
                        if ((int)Main.tile[num59, num61].type == num4)
{
                            num61--;
                            WorldGen.PlaceTile(num59, num61, 220, false, false, -1, 0);
                            if (Main.tile[num59, num61 - 1].type == 220)
{
                                flag2 = false;
                            }
                        }
                    }
                }
            }
            if (islandStyle == 1)
            {
                for (int num62 = 0; num62 < 2; num62++)
                {
                    bool flag3 = true;
                    int num63 = 10000;
                    int num64 = 10;
                    while (flag3 && num63 > 0)
                    {
                        num63--;
                        if (num63 % 50 == 0)
{
                            num64++;
                        }
                        int num65 = WorldGen.genRand.Next(i - num64, i + num64);
                        num65 = Utils.Clamp<int>(num65, num14, num15);
                        int num66 = num16 - 30;
                        if (WorldGen.InWorld(num65, num66, 5))
{
                            while (!Main.tile[num65, num66].active() && num66 < Main.maxTilesY - 10)
{
                                num66++;
                            }
                            if ((int)Main.tile[num65, num66].type == num4 || (int)Main.tile[num65, num66].type == num11)
{
                                num66--;
                                if (Main.tile[num65, num66].liquid == 0 && Main.tile[num65 + 2, num66 + 1].liquid == 0 && Main.tile[num65 - 1, num66 + 1].liquid == 0)
{
                                    if (num62 == 0)
{
                                        WorldGen.PlaceTile(num65, num66, 658, false, false, -1, 0);
                                        if (Main.tile[num65, num66].type == 658)
{
                                            WorldGen.SwitchMonolith(num65, num66);
                                            flag3 = false;
                                        }
                                    }
                                    else if (num62 == 1 && (num63 <= 2000 || !WorldGen.IsTileNearby(num65, num66, 658, 10)))
{
                                        WorldGen.PlaceTile(num65, num66, 139, true, false, -1, 87);
                                        if (Main.tile[num65, num66].type == 139)
{
                                            WorldGen.SwitchMB(num65, num66);
                                            flag3 = false;
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            int num67 = WorldGen.genRand.Next(4);
            for (int num68 = 0; num68 <= num67; num68++)
            {
                int num69 = WorldGen.genRand.Next(num14 - 5, num15 + 5);
                int num70 = num16 - WorldGen.genRand.Next(20, 40);
                int num71 = WorldGen.genRand.Next(4, 8);
                int num72 = num8;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num72 = num9;
                }
                for (int num73 = num69 - num71; num73 <= num69 + num71; num73++)
                {
                    for (int num74 = num70 - num71; num74 <= num70 + num71; num74++)
                    {
                        double num75 = (double)Math.Abs(num73 - num69);
                        double num76 = (double)(Math.Abs(num74 - num70) * 2);
                        if (Math.Sqrt(num75 * num75 + num76 * num76) < (double)(num71 + WorldGen.genRand.Next(-1, 2)) && WorldGen.InWorld(num73, num74, 0))
{
                            Main.tile[num73, num74].active(true);
                            Main.tile[num73, num74].type = (ushort)num72;
                            WorldGen.SquareTileFrame(num73, num74, true);
                        }
                    }
                }
            }
            if (num6 > 0)
            {
                int num77 = 0;
                if (num6 == 60 || num6 == 70)
                {
                    num77 = 59;
                }
                if (num6 == 633)
                {
                    num77 = 57;
                }
                for (int num78 = num14 - 20; num78 <= num15 + 20; num78++)
                {
                    for (int num79 = j - 50; num79 <= j + 50; num79++)
                    {
                        if (WorldGen.InWorld(num78, num79, 5) && Main.tile[num78, num79].active() && (int)Main.tile[num78, num79].type == num77 && !WorldGen.isTileSurroundedBySolidTiles(num78, num79))
{
                            Main.tile[num78, num79].type = (ushort)num6;
                        }
                    }
                }
            }
            LandmassData landmassData = new LandmassData
            {
                DataType = LandmassDataType.SkyblockIsland,
                Position = new Vector2((float)i, (float)j),
                RadiusOrHalfSize = 10,
                Style = islandStyle
            };
            GenVars.landmassData.Add(landmassData);
            return true;
        }
References System.Math.Abs(), Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.Tile.anyShimmer(), Terraria.Utils.Clamp(), Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTileNearby(), Terraria.WorldGen.isTileSurroundedBySolidTiles(), Terraria.WorldBuilding.GenVars.landmassData, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceTile(), Terraria.Tile.shimmer(), Terraria.WorldGen.Skyblock.spawnSolidifier, System.Math.Sqrt(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldGen.SwitchMB(), Terraria.WorldGen.SwitchMonolith(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.GenerateSkyBlockWorld().