Terraria Decompiled: Terraria.WorldGen.ToggleGemLock
ToggleGemLock()
static void Terraria.WorldGen.ToggleGemLock (int i, int j, bool on) inline static
Definition at line 44840 of file WorldGen.cs.
        {
            Tile tileSafely = Framing.GetTileSafely(i, j);
            if (!tileSafely.active() || tileSafely.type != 440)
            {
                return;
            }
            if (tileSafely.frameY < 54 && !on)
            {
                return;
            }
            bool flag = false;
            int num = -1;
            if (tileSafely.frameY >= 54)
            {
                flag = true;
            }
            int num2 = (int)(Main.tile[i, j].frameX / 54);
            int num3 = (int)(Main.tile[i, j].frameX % 54 / 18);
            int num4 = (int)(Main.tile[i, j].frameY % 54 / 18);
            switch (num2)
            {
            case 0:
                num = 1526;
                break;
            case 1:
                num = 1524;
                break;
            case 2:
                num = 1525;
                break;
            case 3:
                num = 1523;
                break;
            case 4:
                num = 1522;
                break;
            case 5:
                num = 1527;
                break;
            case 6:
                num = 3643;
                break;
            }
            for (int k = i - num3; k < i - num3 + 3; k++)
            {
                for (int l = j - num4; l < j - num4 + 3; l++)
                {
                    Main.tile[k, l].frameY = (short)((on ? 54 : 0) + (l - j + num4) * 18);
                }
            }
            if (num != -1 && flag)
            {
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num, 1, false, 0, false);
            }
            WorldGen.SquareTileFrame(i, j, true);
            NetMessage.SendTileSquare(-1, i - num3, j - num4, 3, 3, TileChangeType.None);
            Wiring.HitSwitch(i - num3, j - num4);
            NetMessage.SendData(59, -1, -1, null, i - num3, (float)(j - num4), 0f, 0f, 0, 0, 0);
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.Framing.GetTileSafely(), Terraria.Wiring.HitSwitch(), int, Terraria.Item.NewItem(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Player.TileInteractionsUse().