Terraria Decompiled: Terraria.WorldGen.Caverer
Caverer()
static void Terraria.WorldGen.Caverer (int X, int Y) inline static
Definition at line 79642 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(2);
            if (num == 0)
            {
                int num2 = WorldGen.genRand.Next(7, 9);
                double num3 = (double)WorldGen.genRand.Next(100) * 0.01;
                double num4 = 1.0 - num3;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num3 = -num3;
                }
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num4 = -num4;
                }
                Vector2D vector2D;
                vector2D..ctor((double)X, (double)Y);
                for (int i = 0; i < num2; i++)
                {
                    vector2D = WorldGen.digTunnel(vector2D.X, vector2D.Y, num3, num4, WorldGen.genRand.Next(6, 20), WorldGen.genRand.Next(4, 9), false);
                    num3 += (double)WorldGen.genRand.Next(-20, 21) * 0.1;
                    num4 += (double)WorldGen.genRand.Next(-20, 21) * 0.1;
                    if (num3 < -1.5)
                    {
                        num3 = -1.5;
                    }
                    if (num3 > 1.5)
                    {
                        num3 = 1.5;
                    }
                    if (num4 < -1.5)
                    {
                        num4 = -1.5;
                    }
                    if (num4 > 1.5)
                    {
                        num4 = 1.5;
                    }
                    double num5 = (double)WorldGen.genRand.Next(100) * 0.01;
                    double num6 = 1.0 - num5;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num5 = -num5;
                    }
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num6 = -num6;
                    }
                    Vector2D vector2D2 = WorldGen.digTunnel(vector2D.X, vector2D.Y, num5, num6, WorldGen.genRand.Next(30, 50), WorldGen.genRand.Next(3, 6), false);
                    WorldGen.TileRunner((int)vector2D2.X, (int)vector2D2.Y, (double)WorldGen.genRand.Next(10, 20), WorldGen.genRand.Next(5, 10), -1, false, 0.0, 0.0, false, true, -1);
                }
                return;
            }
            if (num == 1)
            {
                int num7 = WorldGen.genRand.Next(15, 30);
                double num8 = (double)WorldGen.genRand.Next(100) * 0.01;
                double num9 = 1.0 - num8;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num8 = -num8;
                }
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num9 = -num9;
                }
                Vector2D vector2D3;
                vector2D3..ctor((double)X, (double)Y);
                for (int j = 0; j < num7; j++)
                {
                    vector2D3 = WorldGen.digTunnel(vector2D3.X, vector2D3.Y, num8, num9, WorldGen.genRand.Next(5, 15), WorldGen.genRand.Next(2, 6), true);
                    num8 += (double)WorldGen.genRand.Next(-20, 21) * 0.1;
                    num9 += (double)WorldGen.genRand.Next(-20, 21) * 0.1;
                    if (num8 < -1.5)
                    {
                        num8 = -1.5;
                    }
                    if (num8 > 1.5)
                    {
                        num8 = 1.5;
                    }
                    if (num9 < -1.5)
                    {
                        num9 = -1.5;
                    }
                    if (num9 > 1.5)
                    {
                        num9 = 1.5;
                    }
                }
            }
        }
References Terraria.WorldGen.digTunnel(), Terraria.WorldGen.genRand, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.TileRunner(), System.X, ReLogic.Utilities.Vector2D.X, System.Y, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().