Terraria Decompiled: Terraria.WorldGen.ValidateOrAttemptReorientingAnchor
ValidateOrAttemptReorientingAnchor()
static bool Terraria.WorldGen.ValidateOrAttemptReorientingAnchor (int x, int y, int wall, ref int style, bool switchToWallIfInvalid = false) inline static
Definition at line 52341 of file WorldGen.cs.
        {
            if (style == 0 && !WorldGen.SolidTileAllowBottomSlope(x, y + 1) && !WorldGen.ConsideredSolidTileForAnchor(x, y + 1))
            {
                style = -1;
            }
            if (style == 1 && !WorldGen.SolidTileAllowTopSlope(x, y - 1) && !WorldGen.ConsideredSolidTileForAnchor(x, y - 1))
            {
                style = -1;
            }
            if (style == 2 && !WorldGen.SolidTileAllowLeftSlope(x - 1, y) && !WorldGen.ConsideredSolidTileForAnchor(x - 1, y))
            {
                style = -1;
            }
            if (style == 3 && !WorldGen.SolidTileAllowRightSlope(x + 1, y) && !WorldGen.ConsideredSolidTileForAnchor(x + 1, y))
            {
                style = -1;
            }
            if (style == 4 && wall <= 0)
            {
                style = -1;
            }
            if (style == -1 && (WorldGen.SolidTileAllowBottomSlope(x, y + 1) || WorldGen.ConsideredSolidTileForAnchor(x, y + 1)))
            {
                style = 0;
            }
            if (style == -1 && (WorldGen.SolidTileAllowTopSlope(x, y - 1) || WorldGen.ConsideredSolidTileForAnchor(x, y - 1)))
            {
                style = 1;
            }
            if (style == -1 && (WorldGen.SolidTileAllowLeftSlope(x - 1, y) || WorldGen.ConsideredSolidTileForAnchor(x - 1, y)))
            {
                style = 2;
            }
            if (style == -1 && (WorldGen.SolidTileAllowRightSlope(x + 1, y) || WorldGen.ConsideredSolidTileForAnchor(x + 1, y)))
            {
                style = 3;
            }
            if (style == -1 && wall > 0)
            {
                style = 4;
            }
            if (switchToWallIfInvalid && style == -1)
            {
                style = 4;
            }
            return style > -1;
        }
References Terraria.WorldGen.ConsideredSolidTileForAnchor(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), and Terraria.WorldGen.SolidTileAllowTopSlope().
Referenced by Terraria.WorldGen.CheckAnchor(), and Terraria.WorldGen.CheckStinkbugBlocker().