Terraria Decompiled: Terraria.WorldGen.InWorld
InWorld() [2/3]
static bool Terraria.WorldGen.InWorld (Point p, int fluff = 0) inline static
Definition at line 5622 of file WorldGen.cs.
        {
            return WorldGen.InWorld(p.X, p.Y, fluff);
        }
References Terraria.WorldGen.InWorld(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddPasses(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.WorldGen.AddWireFromPointToPoint(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.AdvanceTargetPosition(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.Projectile.AI_003_Boomerang(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TryForcingSitting(), Terraria.Projectile.AI_010(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_016_CanAcornPlant(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.Projectile.AI_197_CeilingAndHoverTurret(), Terraria.Projectile.AI_202_TorchGodHelper(), Terraria.Projectile.AI_204_Digtoise(), Terraria.NPC.AI_AttemptToFindTeleportSpotNearBooks(), Terraria.WorldGen.AnyLiquidAt(), Terraria.WorldGen.AreAnyTilesInSetNearby(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.AreRoomLocationsValid(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.WorldGen.BiomeTileCheck(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformAndDoorsOnHallway(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.CalculatePlatformsAndDoorsOnEdgesOfRoom(), Terraria.WorldGen.CanChlorophyteGrow(), Terraria.Player.CanDoWireStuffHere(), Terraria.GameContent.Generation.Dungeon.DungeonData.CanGenerateFeatureAt(), Terraria.WorldGen.CanGeneratePressurePlateAt(), Terraria.Player.CanShowWireStuffHere(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.WorldGen.CheckAndAdjustMultiDirectionalTile(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.Utils.CheckForGoodTeleportationSpot_CheckNoInvalidTiles(), Terraria.WorldItem.CheckInWorld(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldBuilding.Conditions.IsTile.CheckValidity(), Terraria.WorldBuilding.Conditions.InWorld.CheckValidity(), Terraria.WorldBuilding.Conditions.IsSolid.CheckValidity(), Terraria.GameContent.Biomes.GraniteBiome.CleanupTiles(), Terraria.WorldGen.ClearBrokenTraps(), Terraria.WorldGen.closeEnoughToDungeonToSpawnGhoulder(), Terraria.WorldGen.closeEnoughToLavaToSpawnLavaBoulder(), Terraria.WorldGen.closeEnoughToSpidersToSpawnSpiderBoulder(), Terraria.WorldGen.CloudIsland(), Terraria.NPC.Collision_MoveSlopesAndStairFall(), Terraria.WorldGen.ConsideredSolidTileForAnchor(), Terraria.WorldGen.Convert(), Terraria.WorldGen.Convert(), Terraria.IO.WorldFile.ConvertOldTileEntities(), Terraria.WorldGen.ConvertTreeAndGround(), Terraria.StrayMethods.CountSandHorizontally(), Terraria.WorldGen.countWires(), Terraria.Projectile.CreateGroundExplosion(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.DelegateMethods.CutTiles(), Terraria.Gore.DeactivateIfOutsideOfWorld(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.Player.DoEyebrellaRainEffect(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance_TreeOnPillar(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.Main.DrawBackground_DirtBackground(), Terraria.Main.DrawBackground_DrawMagmaLayer(), Terraria.Main.DrawBackground_DrawRockLayer(), Terraria.Main.DrawBlack(), Terraria.HitTile.DrawFreshAnimations(), Terraria.Main.DrawMapFullscreenBackground(), Terraria.Main.DrawProjDirect(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_BackRope(), Terraria.Main.DrawTileCracks(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.dropMeteor(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.WorldGen.DungeonDesertCleanup(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Mount.EmitGolfCartWheelDust(), Terraria.WorldGen.EmptyLiquid(), Terraria.Collision.ExpandVertically(), Terraria.GameContent.Tile_Entities.TELogicSensor.FigureCheckType(), Terraria.WorldGen.FillWallHolesInSpot(), Terraria.NPC.FindCattailTop(), Terraria.NPC.FindTreeBranch(), Terraria.Utils.FloodFillTile(), Terraria.WorldGen.Spread.Gem(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonTree(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateTileStrip(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip(), Terraria.Projectile.GetAlpha(), Terraria.GameContent.NearbyChests.GetBanksInRangeOf(), Terraria.NPC.GetBirdFlightRecommendation(), Terraria.WorldGen.GetCactusType(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.GetFruitForPot(), Terraria.NPC.Spawner.GetProperGroundSpawnTileTypeAndWallType(), Terraria.WorldGen.GetRopeEnds(), Terraria.Framing.GetTileSafely(), Terraria.Collision.GetWaterLine(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_CanPlaceLeaves(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowMoreVines(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.HandleRopeEndFraming_Inner(), Terraria.WorldGen.hardUpdateWorld(), Terraria.NPC.Spawner.HasTileSpawnSpace(), Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), Terraria.WorldGen.HasValidGroundForChilletEggBelowSpot(), Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), Terraria.WorldGen.HellFort(), Terraria.Wiring.HitSwitch(), Terraria.WorldGen.InAPlaceWithWind(), Terraria.WorldGen.InvalidTileForPilesOrSpeleothems(), Terraria.WorldGen.InWorld(), Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot(), Terraria.GameContent.RGB.CommonConditions.Depth.IsInFrontOfDirtWall(), Terraria.WorldGen.IslandHouse(), Terraria.WorldGen.IsTileATreeBranch(), Terraria.WorldGen.IsTileATreeRoot(), Terraria.WorldGen.IsTileNearby(), Terraria.Graphics.Light.TileLightScanner.IsTileNullOrTouchingNull(), Terraria.Collision.IsWorldPointSolid(), Terraria.Player.ItemCheck_PlayInstruments(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.Projectile.LightningKillLambda_Step(), Terraria.GameContent.UnbreakableWallScan.LineScan(), Terraria.Liquid.LiquidCheck(), Terraria.IO.WorldFile.LoadTileEntities(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.Wiring.MassWireOperationStep(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.meteor(), Terraria.WorldGen.Spread.Moss(), Terraria.WorldGen.OasisPlantWaterCheck(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.CaveHouseBiome.Place(), Terraria.WorldGen.Place1x1(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), Terraria.DataStructures.TileEntity.PlaceEntityNet(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.WorldGen.PlaceLiquid(), Terraria.WorldGen.PlaceStatueTrap(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceTorchesAroundSpawn(), Terraria.WorldGen.placeTrap(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPlatforms.Platforms(), Terraria.Projectile.RainbowBoulder_HighlightNearbyTreasure(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall(), Terraria.WorldGen.ReplaceTile_EliminateNaturalExtras(), Terraria.GameContent.TeleportHelpers.RequestMagicConchTeleportPosition(), Terraria.WorldGen.SeaOatWaterCheck(), Terraria.DelegateMethods.SearchAvoidedByNPCs(), Terraria.NPC.Spawner.SetSpawnFlags(), Terraria.WorldGen.ShellPile(), Terraria.Projectile.Shimmer(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldItem.Shimmering(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.GameContent.ObjectInteractions.BlockBecauseYouAreOverAnImportantTile.ShouldBlockSmartInteract(), Terraria.GameContent.Biomes.GraniteBiome.ShouldUseLava(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), Terraria.GameContent.Biomes.DungeonControlLine.SkipPaintForEdge(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.SnowCloudIsland(), Terraria.Main.snowing(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileNoPlatforms(), Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_IsAreaValidSpawn(), Terraria.WorldGen.SpawnGraveyardBiome(), Terraria.NPC.Spawner.Spawning_FlyingAntlionCheck(), Terraria.NPC.Spawner.Spawning_SandstoneCheck(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.NPC.Spawner.SpawnTileOrAboveHasAnyWallInSet(), Terraria.NPC.SpawnWOF(), Terraria.WorldGen.Spread.Spider(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.SpreadGrassWalls(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepDown(), Terraria.Collision.StepUp(), Terraria.Projectile.StormLightningLiquidCollisionCheck(), Terraria.WorldGen.templePart2(), Terraria.GameContent.LightningGenerator.TileCollision(), Terraria.Player.TileInteractionsCheckLongDistance(), Terraria.WorldGen.TileIsExposedToAir(), Terraria.Player.TorchGodsFlavor(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), Terraria.WorldGen.TownNPCPositionsCleanup(), Terraria.WorldGen.TreeGrowFX(), Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid(), Terraria.Collision.TryFindingConveyorBeltRising(), Terraria.GameContent.DoorOpeningHelper.TryGetHandler(), Terraria.Player.TryInteractingWithMinecartTrackInNearbyArea(), Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.Player.TryPlacingAGolfBallNearANearbyTee(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.Liquid.UndergroundDesertCheck(), Terraria.Map.WorldMap.UnlockMapTilePretty(), Terraria.Gore.Update(), Terraria.Player.Update(), Terraria.Main.UpdateAudio_DecideOnNewMusic(), Terraria.Main.UpdateAudio_DecideOnTOWMusic(), Terraria.Player.UpdateBiomes(), Terraria.WorldItem.UpdateItem(), Terraria.Wiring.UpdateMech(), Terraria.NPC.UpdateNPC(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.Mount.UseDrill(), Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType(), Terraria.WorldGen.Spread.Wall(), Terraria.WorldGen.Spread.Wall2(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.WallVariants(), Terraria.WorldGen.WavyCaverer(), and Terraria.WorldGen.WouldTileReplacementWork().