Terraria Decompiled: Terraria.WorldGen.OverGrownDungeon
OverGrownDungeon()
static void Terraria.WorldGen.OverGrownDungeon () inline static private
Definition at line 21111 of file WorldGen.cs.
        {
            int maxTilesX = Main.maxTilesX;
            for (int i = 0; i < maxTilesX; i++)
            {
                int num = WorldGen.genRand.Next(50, Main.maxTilesX / 2);
                if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
                {
                    num = WorldGen.genRand.Next(Main.maxTilesX / 2, Main.maxTilesX - 50);
                }
                int num2 = WorldGen.genRand.Next(50, Main.maxTilesY - 50);
                if (Main.wallDungeon[(int)Main.tile[num, num2].wall])
                {
                    int num3 = WorldGen.genRand.Next(5, 16);
                    for (int j = num - num3; j <= num + num3; j++)
                    {
                        for (int k = num2 - num3; k <= num2 + num3; k++)
{
                            if (Main.tile[j, k].active() && Main.tileDungeon[(int)Main.tile[j, k].type] && (!Main.tile[j - 1, k - 1].active() || !Main.tile[j, k - 1].active() || !Main.tile[j + 1, k - 1].active() || !Main.tile[j - 1, k].active() || !Main.tile[j + 1, k].active() || !Main.tile[j - 1, k + 1].active() || !Main.tile[j, k + 1].active() || !Main.tile[j + 1, k - 1].active()))
{
                                Main.tile[j, k].type = 60;
                                Main.tile[j, k].color(0);
                                if (!Main.tile[j, k - 1].active() && !WorldGen.GrowTree(j, k, 0, false))
{
                                    WorldGen.PlaceTile(j, k - 1, 61, true, false, -1, 0);
                                }
                                if (!Main.tile[j, k + 1].active() && WorldGen.genRand.Next(3) != 0)
{
                                    WorldGen.PlaceTile(j, k + 1, 62, false, false, -1, 0);
                                    if (!Main.tile[j, k + 2].active())
{
                                        WorldGen.PlaceTile(j, k + 2, 62, false, false, -1, 0);
                                        if (!Main.tile[j, k + 3].active())
{
                                            WorldGen.PlaceTile(j, k + 3, 62, false, false, -1, 0);
                                            if (!Main.tile[j, k + 4].active() && WorldGen.genRand.Next(4) != 0)
{
                                                WorldGen.PlaceTile(j, k + 4, 62, false, false, -1, 0);
                                            }
                                            if (!Main.tile[j, k + 5].active() && WorldGen.genRand.Next(3) != 0)
{
                                                WorldGen.PlaceTile(j, k + 5, 62, false, false, -1, 0);
                                            }
                                            if (!Main.tile[j, k + 6].active() && WorldGen.genRand.Next(2) != 0)
{
                                                WorldGen.PlaceTile(j, k + 6, 62, false, false, -1, 0);
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonSide, Terraria.WorldGen.genRand, Terraria.WorldGen.GrowTree(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldBuilding.DungeonSide.Right, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.FinishNotTheBees().