Terraria Decompiled: Terraria.WorldGen.PlaceOasisPlant
PlaceOasisPlant()
static void Terraria.WorldGen.PlaceOasisPlant (int X, int Y, ushort type = 530) inline static
Definition at line 45900 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(9);
            int num2 = 0;
            if (X < WorldGen.beachDistance || X > Main.maxTilesX - WorldGen.beachDistance || Y < 5 || Y > Main.maxTilesY - 5)
            {
                return;
            }
            bool flag = true;
            for (int i = X - 1; i < X + 2; i++)
            {
                for (int j = Y - 1; j < Y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active() && Main.tile[i, j].type != 529)
                    {
                        flag = false;
                    }
                    if (Main.tile[i, j].liquid > 0)
                    {
                        flag = false;
                    }
                }
                if (Main.tile[i, Y + 1] == null)
                {
                    Main.tile[i, Y + 1] = new Tile();
                }
                if (!WorldGen.SolidTile(i, Y + 1, false) || !TileID.Sets.Conversion.Sand[(int)Main.tile[i, Y + 1].type])
                {
                    flag = false;
                }
            }
            if (flag)
            {
                if (!WorldGen.OasisPlantWaterCheck(X, Y, false))
                {
                    return;
                }
                for (int k = X - 1; k < X + 2; k++)
                {
                    for (int l = Y - 1; l < Y + 1; l++)
                    {
                        if (Main.tile[k, l] != null && Main.tile[k, l].active())
{
                            WorldGen.KillTile(k, l, false, false, true);
                        }
                    }
                }
                short num3 = (short)(54 * num);
                short num4 = (short)(36 * num2);
                Main.tile[X - 1, Y - 1].active(true);
                Main.tile[X - 1, Y - 1].frameY = num4;
                Main.tile[X - 1, Y - 1].frameX = num3;
                Main.tile[X - 1, Y - 1].type = type;
                Main.tile[X, Y - 1].active(true);
                Main.tile[X, Y - 1].frameY = num4;
                Main.tile[X, Y - 1].frameX = num3 + 18;
                Main.tile[X, Y - 1].type = type;
                Main.tile[X + 1, Y - 1].active(true);
                Main.tile[X + 1, Y - 1].frameY = num4;
                Main.tile[X + 1, Y - 1].frameX = num3 + 36;
                Main.tile[X + 1, Y - 1].type = type;
                Main.tile[X - 1, Y].active(true);
                Main.tile[X - 1, Y].frameY = num4 + 18;
                Main.tile[X - 1, Y].frameX = num3;
                Main.tile[X - 1, Y].type = type;
                Main.tile[X, Y].active(true);
                Main.tile[X, Y].frameY = num4 + 18;
                Main.tile[X, Y].frameX = num3 + 18;
                Main.tile[X, Y].type = type;
                Main.tile[X + 1, Y].active(true);
                Main.tile[X + 1, Y].frameY = num4 + 18;
                Main.tile[X + 1, Y].frameX = num3 + 36;
                Main.tile[X + 1, Y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.OasisPlantWaterCheck(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Tile.type, System.X, and System.Y.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile().