Terraria Decompiled: Terraria.WorldGen.CheckBanner
CheckBanner()
static void Terraria.WorldGen.CheckBanner (int x, int j, byte type) inline static
Definition at line 44456 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int i = (int)(Main.tile[x, j].frameY / 18);
            int num = 0;
            while (i >= 3)
            {
                i -= 3;
                num++;
            }
            i = j - i;
            int frameX = (int)Main.tile[x, j].frameX;
            bool flag = false;
            for (int k = 0; k < 3; k++)
            {
                if (Main.tile[x, i + k] == null)
                {
                    Main.tile[x, i + k] = new Tile();
                }
                if (!Main.tile[x, i + k].active())
                {
                    flag = true;
                }
                else if (Main.tile[x, i + k].type != (ushort)type)
                {
                    flag = true;
                }
                else if ((int)Main.tile[x, i + k].frameY != k * 18 + num * 18 * 3)
                {
                    flag = true;
                }
                else if ((int)Main.tile[x, i + k].frameX != frameX)
                {
                    flag = true;
                }
            }
            if (Main.tile[x, i - 1] == null)
            {
                Main.tile[x, i - 1] = new Tile();
            }
            Tile tile = Main.tile[x, i - 1];
            if (!tile.nactive())
            {
                flag = true;
            }
            bool flag2 = tile.topSlope() || tile.halfBrick() || Main.tileSolid[(int)tile.type];
            bool flag3 = !Main.tileSolidTop[(int)tile.type] || (TileID.Sets.Platforms[(int)tile.type] && (tile.halfBrick() || tile.topSlope()));
            bool flag4 = flag2 && flag3 && !TileID.Sets.NotReallySolid[(int)tile.type] && !tile.bottomSlope();
            if (TileID.Sets.Platforms[(int)tile.type] || tile.type == 380)
            {
                flag4 = true;
            }
            if (!flag4)
            {
                flag = true;
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int l = 0; l < 3; l++)
                {
                    if (Main.tile[x, i + l].type == (ushort)type)
                    {
                        WorldGen.KillTile(x, i + l, false, false, false);
                    }
                }
                if (type == 91)
                {
                    int num2 = frameX / 18;
                    num2 += num * 111;
                    if (num2 == 315)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 5673, 1, false, 0, false);
                    }
                    else if (num2 == 314)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 5672, 1, false, 0, false);
                    }
                    else if (num2 == 313)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 5651, 1, false, 0, false);
                    }
                    else if (num2 == 312)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 5498, 1, false, 0, false);
                    }
                    else if (num2 == 311)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 5497, 1, false, 0, false);
                    }
                    else if (num2 == 310)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 5352, 1, false, 0, false);
                    }
                    else if (num2 >= 297)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 4668 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 295)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 4392 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 294)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 4602, 1, false, 0, false);
                    }
                    else if (num2 >= 288)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 4253 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 278)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 3559 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 273)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 3516 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 272)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 3780, 1, false, 0, false);
                    }
                    else if (num2 >= 270)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 3323 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 207)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 3183 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 109)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 2788 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 22)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 1593 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 10 && num2 <= 15)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 1441 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 16 && num2 <= 21)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 1448 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 7 && num2 <= 9)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 838 + num2, 1, false, 0, false);
                    }
                    else if (num2 >= 4 && num2 <= 6)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 785 + num2, 1, false, 0, false);
                    }
                    else
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, i + 1), x * 16, (i + 1) * 16, 32, 32, 337 + num2, 1, false, 0, false);
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.bottomSlope(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.Tile.halfBrick(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Item.NewItem(), Terraria.ID.TileID.Sets.NotReallySolid, Terraria.ID.TileID.Sets.Platforms, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().