Terraria Decompiled: Terraria.WorldGen.TryPlacingChilletEgg
TryPlacingChilletEgg()
static bool Terraria.WorldGen.TryPlacingChilletEgg (int i, int j) inline static private
Definition at line 44035 of file WorldGen.cs.
        {
            int num = 5;
            for (int k = 0; k < num; k++)
            {
                int num2 = WorldGen.genRand.Next(Math.Max(10, i - 10), Math.Min(Main.maxTilesX - 10, i + 10));
                int num3 = WorldGen.genRand.Next(Math.Max(10, j - 10), Math.Min(Main.maxTilesY - 10, j + 10));
                if (WorldGen.HasValidGroundForChilletEggBelowSpot(num2, num3) && WorldGen.NoNearbyChilletEggs(num2, num3))
                {
                    WorldGen.PlaceTile(num2, num3, 752, true, false, -1, 0);
                    Tile tile = Main.tile[num2, num3];
                    if (tile.active() && tile.type == 752)
                    {
                        if (!WorldGen.generatingWorld && Main.netMode == 2 && Main.tile[num2, num3] != null && Main.tile[num2, num3].active())
{
                            NetMessage.SendTileSquare(-1, num2, num3, TileChangeType.None);
                        }
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.generatingWorld, Terraria.WorldGen.genRand, Terraria.WorldGen.HasValidGroundForChilletEggBelowSpot(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.NoNearbyChilletEggs(), Terraria.WorldGen.PlaceTile(), Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceChilletEggs().