Terraria Decompiled: Terraria.WorldGen.KillTile_MakeTileDust
KillTile_MakeTileDust()
static int Terraria.WorldGen.KillTile_MakeTileDust (int i, int j, Tile tileCache) inline static
Definition at line 66153 of file WorldGen.cs.
        {
            int num = 0;
            if (tileCache.type == 216)
            {
                num = -1;
            }
            if (tileCache.type == 324)
            {
                if (tileCache.frameY == 0)
                {
                    num = 280;
                }
                else
                {
                    num = (int)(281 + tileCache.frameX / 18);
                }
            }
            if (tileCache.type == 216)
            {
                num = -1;
            }
            if (tileCache.type == 335)
            {
                num = -1;
            }
            if (tileCache.type == 338)
            {
                num = -1;
            }
            if (tileCache.type == 0)
            {
                num = 0;
            }
            if (tileCache.type == 192)
            {
                num = 3;
            }
            if (tileCache.type == 208)
            {
                num = 126;
            }
            else if (tileCache.type == 408 || tileCache.type == 409)
            {
                num = 265;
            }
            else if (tileCache.type == 669)
            {
                num = 314;
            }
            else if (tileCache.type == 670)
            {
                num = 315;
            }
            else if (tileCache.type == 671)
            {
                num = 316;
            }
            else if (tileCache.type == 672)
            {
                num = 317;
            }
            else if (tileCache.type == 673)
            {
                num = 318;
            }
            else if (tileCache.type == 674)
            {
                num = 319;
            }
            else if (tileCache.type == 675)
            {
                num = 320;
            }
            else if (tileCache.type == 676)
            {
                num = 321;
            }
            if (tileCache.type == 16)
            {
                num = 1;
                if (tileCache.frameX >= 36)
                {
                    num = 82;
                }
            }
            else if (tileCache.type == 415 || tileCache.type == 500)
            {
                num = 6;
            }
            else if (tileCache.type == 416 || tileCache.type == 501)
            {
                num = 61;
            }
            else if (tileCache.type == 417 || tileCache.type == 502)
            {
                num = 242;
            }
            else if (tileCache.type == 418 || tileCache.type == 503)
            {
                num = 135;
            }
            else if (tileCache.type == 474)
            {
                num = 18;
            }
            if (tileCache.type == 1 || tileCache.type == 17 || tileCache.type == 38 || tileCache.type == 39 || tileCache.type == 41 || tileCache.type == 43 || tileCache.type == 44 || tileCache.type == 481 || tileCache.type == 482 || tileCache.type == 483 || tileCache.type == 48 || Main.tileStone[(int)tileCache.type] || tileCache.type == 85 || tileCache.type == 90 || tileCache.type == 92 || tileCache.type == 96 || tileCache.type == 97 || tileCache.type == 99 || tileCache.type == 117 || tileCache.type == 130 || tileCache.type == 131 || tileCache.type == 132 || tileCache.type == 135 || tileCache.type == 142 || tileCache.type == 143 || tileCache.type == 144 || tileCache.type == 210 || tileCache.type == 207 || tileCache.type == 235 || tileCache.type == 247 || tileCache.type == 272 || tileCache.type == 273 || tileCache.type == 283 || tileCache.type == 410 || tileCache.type == 480 || tileCache.type == 509 || tileCache.type == 618 || tileCache.type == 657 || tileCache.type == 658 || tileCache.type == 677 || tileCache.type == 678 || tileCache.type == 679 || tileCache.type == 720 || tileCache.type == 721 || tileCache.type == 725 || tileCache.type == 733)
            {
                num = 1;
            }
            if (tileCache.type == 379)
            {
                num = 257;
            }
            if (tileCache.type == 751 || tileCache.type == 752)
            {
                num = -1;
            }
            if (tileCache.type == 311)
            {
                num = 207;
            }
            if (tileCache.type == 312)
            {
                num = 208;
            }
            if (tileCache.type == 313)
            {
                num = 209;
            }
            if (tileCache.type == 104)
            {
                num = -1;
            }
            if (tileCache.type == 95 || tileCache.type == 98 || tileCache.type == 100 || tileCache.type == 174 || tileCache.type == 173)
            {
                num = 6;
            }
            if (tileCache.type == 30 || tileCache.type == 86 || tileCache.type == 94 || tileCache.type == 106 || tileCache.type == 114 || tileCache.type == 124 || tileCache.type == 128 || tileCache.type == 269)
            {
                num = 7;
            }
            if (tileCache.type == 372)
            {
                num = 242;
            }
            if (tileCache.type == 646)
            {
                num = 29;
            }
            if (tileCache.type == 49)
            {
                num = 29;
            }
            if (tileCache.type == 371)
            {
                num = 243;
            }
            if (tileCache.type == 334)
            {
                num = 7;
            }
            ushort num2 = tileCache.type;
            if (num2 > 320)
            {
                if (num2 <= 638)
                {
                    if (num2 > 390)
                    {
                        switch (num2)
{
                        case 405:
                        case 406:
                        case 411:
                        case 412:
                        case 419:
                        case 420:
                        case 421:
                        case 422:
                        case 423:
                        case 424:
                        case 425:
                        case 428:
                        case 429:
                        case 441:
                        case 442:
                        case 445:
                        case 446:
                        case 447:
                        case 448:
                        case 449:
                        case 450:
                        case 451:
                        case 452:
                        case 453:
                        case 455:
                        case 456:
                        case 457:
                        case 462:
                        case 463:
                        case 464:
                        case 465:
                        case 466:
                        case 468:
                        case 476:
                        case 486:
                        case 487:
                        case 489:
                        case 490:
                        case 491:
                        case 493:
                        case 494:
                        case 497:
                        case 510:
                        case 511:
                        case 520:
                        case 521:
                        case 522:
                        case 523:
                        case 524:
                        case 525:
                        case 526:
                        case 527:
                        case 531:
                        case 545:
                        case 547:
                        case 548:
                            goto IL_0AC4;
                        case 407:
                            num = 10;
                            goto IL_0D04;
                        case 408:
                        case 409:
                        case 410:
                        case 413:
                        case 414:
                        case 415:
                        case 416:
                        case 417:
                        case 418:
                        case 426:
                        case 427:
                        case 430:
                        case 431:
                        case 432:
                        case 433:
                        case 434:
                        case 435:
                        case 436:
                        case 437:
                        case 438:
                        case 439:
                        case 440:
                        case 443:
                        case 444:
                        case 458:
                        case 459:
                        case 460:
                        case 461:
                        case 467:
                        case 469:
                        case 470:
                        case 471:
                        case 474:
                        case 475:
                        case 477:
                        case 478:
                        case 479:
                        case 480:
                        case 484:
                        case 485:
                        case 488:
                        case 492:
                        case 495:
                        case 496:
                        case 499:
                        case 500:
                        case 501:
                        case 502:
                        case 503:
                        case 504:
                        case 505:
                        case 506:
                        case 507:
                        case 508:
                        case 509:
                        case 518:
                        case 519:
                        case 528:
                        case 529:
                        case 530:
                        case 532:
                        case 533:
                        case 534:
                        case 536:
                        case 538:
                        case 539:
                        case 542:
                        case 543:
                        case 544:
                            goto IL_0D04;
                        case 454:
                            num = 139;
                            goto IL_0D04;
                        case 472:
                        case 546:
                            break;
                        case 473:
                            num = 82;
                            goto IL_0D04;
                        case 481:
                            goto IL_0AE5;
                        case 482:
                            goto IL_0AF0;
                        case 483:
                            goto IL_0AFB;
                        case 498:
                            num = 30;
                            goto IL_0D04;
                        case 512:
                            num = 93;
                            goto IL_0D04;
                        case 513:
                            num = 94;
                            goto IL_0D04;
                        case 514:
                            num = 95;
                            goto IL_0D04;
                        case 515:
                            num = 96;
                            goto IL_0D04;
                        case 516:
                            num = 97;
                            goto IL_0D04;
                        case 517:
                            goto IL_0B1D;
                        case 535:
                            goto IL_0B28;
                        case 537:
                            goto IL_0B33;
                        case 540:
                            goto IL_0B3E;
                        case 541:
                            num = 226;
                            goto IL_0D04;
                        default:
                            switch (num2)
{
                            case 557:
                                break;
                            case 558:
                            case 559:
                            case 561:
                            case 562:
                            case 563:
                            case 566:
                            case 568:
                            case 569:
                            case 570:
                            case 571:
                            case 573:
                            case 574:
                            case 575:
                            case 576:
                            case 577:
                            case 578:
                            case 580:
                            case 581:
                            case 582:
                                goto IL_0D04;
                            case 560:
                            case 564:
                            case 565:
                            case 567:
                            case 572:
                            case 579:
                            case 591:
                            case 592:
                            case 593:
                            case 594:
                                goto IL_0AC4;
                            case 583:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 87 : 1);
                                goto IL_0D04;
                            case 584:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 86 : 1);
                                goto IL_0D04;
                            case 585:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 88 : 1);
                                goto IL_0D04;
                            case 586:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 89 : 1);
                                goto IL_0D04;
                            case 587:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 90 : 1);
                                goto IL_0D04;
                            case 588:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 91 : 1);
                                goto IL_0D04;
                            case 589:
                                num = ((WorldGen.genRand.Next(10) == 0) ? 138 : 1);
                                goto IL_0D04;
                            case 590:
                                num = 1;
                                goto IL_0D04;
                            case 595:
                                num = 78;
                                goto IL_0D04;
                            case 596:
                                num = 78;
                                goto IL_0D04;
                            default:
                                switch (num2)
{
                                case 613:
                                case 614:
                                case 621:
                                case 622:
                                case 623:
                                case 624:
                                case 630:
                                case 631:
                                    goto IL_0AC4;
                                case 615:
                                    num = 78;
                                    goto IL_0D04;
                                case 616:
                                    num = 78;
                                    goto IL_0D04;
                                case 617:
                                case 618:
                                case 619:
                                case 620:
                                case 625:
                                case 627:
                                case 628:
                                case 629:
                                case 632:
                                case 635:
                                case 636:
                                    goto IL_0D04;
                                case 626:
                                    goto IL_0B49;
                                case 633:
                                    num = ((WorldGen.genRand.Next(6) != 0) ? 237 : 36);
                                    goto IL_0D04;
                                case 634:
                                    num = ((WorldGen.genRand.Next(10) != 0) ? 36 : 31);
                                    if (WorldGen.genRand.Next(12) == 0)
{
                                        num = 6;
                                        goto IL_0D04;
                                    }
                                    goto IL_0D04;
                                case 637:
                                case 638:
                                    num = 237;
                                    goto IL_0D04;
                                default:
                                    goto IL_0D04;
                                }
                                break;
                            }
                            break;
                        }
                        num = 8;
                        goto IL_0D04;
                    }
                    if (num2 - 386 > 1 && num2 != 390)
                    {
                        goto IL_0D04;
                    }
                    goto IL_0AC4;
                }
                else if (num2 <= 668)
                {
                    if (num2 == 656)
                    {
                        goto IL_0AC4;
                    }
                    if (num2 != 668)
                    {
                        goto IL_0D04;
                    }
                    num = 0;
                    goto IL_0D04;
                }
                else
                {
                    switch (num2)
                    {
                    case 677:
                        goto IL_0AE5;
                    case 678:
                        goto IL_0AF0;
                    case 679:
                        goto IL_0AFB;
                    case 680:
                    case 681:
                    case 682:
                    case 683:
                    case 684:
                    case 685:
                    case 686:
                        goto IL_0D04;
                    case 687:
                        break;
                    case 688:
                        goto IL_0B3E;
                    case 689:
                        goto IL_0B28;
                    case 690:
                        goto IL_0B33;
                    case 691:
                        goto IL_0B49;
                    default:
                        if (num2 - 700 <= 1 || num2 == 726)
{
                            goto IL_0AC4;
                        }
                        goto IL_0D04;
                    }
                }
                IL_0B1D:
                num = 258;
                goto IL_0D04;
                IL_0B28:
                num = 299;
                goto IL_0D04;
                IL_0B33:
                num = 300;
                goto IL_0D04;
                IL_0B3E:
                num = 301;
                goto IL_0D04;
                IL_0B49:
                num = 305;
                goto IL_0D04;
            }
            if (num2 <= 89)
            {
                if (num2 <= 44)
                {
                    if (num2 - 10 > 1)
                    {
                        switch (num2)
{
                        case 41:
                            goto IL_0AE5;
                        case 42:
                            goto IL_0D04;
                        case 43:
                            goto IL_0AF0;
                        case 44:
                            goto IL_0AFB;
                        default:
                            goto IL_0D04;
                        }
                    }
                }
                else if (num2 != 87 && num2 != 89)
                {
                    goto IL_0D04;
                }
            }
            else if (num2 <= 139)
            {
                if (num2 != 93 && num2 != 139)
                {
                    goto IL_0D04;
                }
            }
            else if (num2 != 184)
            {
                if (num2 != 209 && num2 - 319 > 1)
                {
                    goto IL_0D04;
                }
            }
            else
            {
                int num3 = (int)(tileCache.frameX / 22);
                if (num3 == 5)
                {
                    num = 258;
                    goto IL_0D04;
                }
                if (num3 == 6)
                {
                    num = 299;
                    goto IL_0D04;
                }
                if (num3 == 7)
                {
                    num = 300;
                    goto IL_0D04;
                }
                if (num3 == 8)
                {
                    num = 301;
                    goto IL_0D04;
                }
                if (num3 == 9)
                {
                    num = 305;
                    goto IL_0D04;
                }
                if (num3 == 10)
                {
                    num = 267;
                    goto IL_0D04;
                }
                num = 93 + num3;
                goto IL_0D04;
            }
            IL_0AC4:
            num = -1;
            goto IL_0D04;
            IL_0AE5:
            num = 275;
            goto IL_0D04;
            IL_0AF0:
            num = 276;
            goto IL_0D04;
            IL_0AFB:
            num = 277;
            IL_0D04:
            if (Main.tileMoss[(int)tileCache.type])
            {
                if (tileCache.type == 381)
                {
                    num = 258;
                }
                else if (tileCache.type == 534)
                {
                    num = 299;
                }
                else if (tileCache.type == 536)
                {
                    num = 300;
                }
                else if (tileCache.type == 539)
                {
                    num = 301;
                }
                else if (tileCache.type == 625)
                {
                    num = 305;
                }
                else if (tileCache.type == 627)
                {
                    num = 267;
                }
                else
                {
                    num = (int)(tileCache.type - 179 + 93);
                }
            }
            if (tileCache.type == 240)
            {
                int num4 = (int)(tileCache.frameX / 54);
                if (tileCache.frameY >= 54)
                {
                    num4 += (int)(36 * (tileCache.frameY / 54));
                }
                num = 7;
                if (num4 == 16 || num4 == 17)
                {
                    num = 26;
                }
                if (num4 >= 46 && num4 <= 49)
                {
                    num = -1;
                }
                if (num4 == 100)
                {
                    num = -1;
                }
            }
            if (tileCache.type == 241)
            {
                num = 1;
            }
            if (tileCache.type == 242)
            {
                num = -1;
            }
            if (tileCache.type == 529)
            {
                int type = (int)Main.tile[i, j + 1].type;
                if (type == 116)
                {
                    num = 47;
                }
                else if (type == 234)
                {
                    num = 125;
                }
                else if (type == 112)
                {
                    num = 17;
                }
                else if (i < WorldGen.beachDistance || i > Main.maxTilesX - WorldGen.beachDistance)
                {
                    num = 290;
                }
                else
                {
                    num = 289;
                }
            }
            if (tileCache.type == 356)
            {
                num = -1;
            }
            if (tileCache.type == 663)
            {
                num = -1;
            }
            if (tileCache.type == 351)
            {
                num = -1;
            }
            if (tileCache.type == 246)
            {
                num = -1;
            }
            if (tileCache.type == 36)
            {
                num = -1;
            }
            if (tileCache.type == 365)
            {
                num = 239;
            }
            if (tileCache.type == 366)
            {
                num = 30;
            }
            if (tileCache.type == 504)
            {
                num = -1;
            }
            if (tileCache.type == 357 || tileCache.type == 367 || tileCache.type == 561)
            {
                num = 236;
            }
            if (tileCache.type == 368 || tileCache.type == 369 || tileCache.type == 576)
            {
                num = 240;
            }
            if (tileCache.type == 170)
            {
                num = 196;
            }
            if (tileCache.type == 315)
            {
                num = 225;
            }
            if (tileCache.type == 641)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 243;
                }
                else
                {
                    num = 161;
                }
            }
            if (tileCache.type == 659)
            {
                num = 308;
            }
            if (tileCache.type == 667)
            {
                num = 308;
            }
            if (tileCache.type == 346)
            {
                num = 128;
            }
            if (tileCache.type == 347)
            {
                num = 117;
            }
            if (tileCache.type == 348)
            {
                num = 42;
            }
            if (tileCache.type == 350)
            {
                num = 226;
            }
            if (tileCache.type == 370)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 6;
                }
                else
                {
                    num = 23;
                }
            }
            if (tileCache.type == 171)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 196;
                }
                else
                {
                    num = -1;
                }
            }
            if (tileCache.type == 326)
            {
                num = 13;
            }
            if (tileCache.type == 327)
            {
                num = 13;
            }
            if (tileCache.type == 345)
            {
                num = 13;
            }
            if (tileCache.type == 708)
            {
                num = 13;
            }
            if (tileCache.type == 458)
            {
                num = 13;
            }
            if (tileCache.type == 459)
            {
                num = 13;
            }
            if (tileCache.type == 336)
            {
                num = 6;
            }
            if (tileCache.type == 340)
            {
                num = 75;
            }
            if (tileCache.type == 341)
            {
                num = 65;
            }
            if (tileCache.type == 342)
            {
                num = 135;
            }
            if (tileCache.type == 343)
            {
                num = 169;
            }
            if (tileCache.type == 344)
            {
                num = 156;
            }
            if (tileCache.type == 328)
            {
                num = 13;
            }
            if (tileCache.type == 329)
            {
                num = 13;
            }
            if (tileCache.type == 507)
            {
                num = 13;
            }
            if (tileCache.type == 508)
            {
                num = 13;
            }
            if (tileCache.type == 562)
            {
                num = 273;
            }
            if (tileCache.type == 571)
            {
                num = 40;
            }
            if (tileCache.type == 563)
            {
                num = 273;
            }
            if (tileCache.type == 330)
            {
                num = 9;
            }
            if (tileCache.type == 331)
            {
                num = 11;
            }
            if (tileCache.type == 332)
            {
                num = 19;
            }
            if (tileCache.type == 333)
            {
                num = 11;
            }
            if (tileCache.type == 722)
            {
                num = 57;
            }
            if (tileCache.type == 734)
            {
                num = 0;
            }
            if (tileCache.type == 735)
            {
                num = 10;
            }
            if (tileCache.type == 736)
            {
                num = 277;
            }
            if (tileCache.type == 737)
            {
                num = 26;
            }
            if (tileCache.type == 738)
            {
                num = 277;
            }
            if (tileCache.type == 739)
            {
                num = 68;
            }
            if (tileCache.type == 740)
            {
                num = 1;
            }
            if (tileCache.type == 741)
            {
                num = 78;
            }
            switch (tileCache.type)
            {
            case 742:
                num = 96;
                break;
            case 743:
                num = 236;
                break;
            case 744:
                num = 78;
                break;
            case 745:
                num = 26;
                break;
            case 746:
                num = 148;
                break;
            case 747:
                num = 10;
                break;
            case 748:
                num = 13;
                break;
            case 749:
                num = 1;
                break;
            case 750:
                num = 26;
                break;
            }
            if (tileCache.type == 101)
            {
                num = -1;
            }
            if (tileCache.type == 19)
            {
                int num5 = (int)(tileCache.frameY / 18);
                if (num5 == 0)
                {
                    num = 7;
                }
                else if (num5 == 1)
                {
                    num = 77;
                }
                else if (num5 == 2)
                {
                    num = 78;
                }
                else if (num5 == 3)
                {
                    num = 79;
                }
                else if (num5 == 4)
                {
                    num = 26;
                }
                else if (num5 == 5)
                {
                    num = 126;
                }
                else if (num5 == 6)
                {
                    num = 275;
                }
                else if (num5 == 7)
                {
                    num = 277;
                }
                else if (num5 == 8)
                {
                    num = 276;
                }
                else if (num5 == 9)
                {
                    num = 1;
                }
                else if (num5 == 10)
                {
                    num = 214;
                }
                else if (num5 == 11)
                {
                    num = 214;
                }
                else if (num5 == 12)
                {
                    num = 214;
                }
                else if (num5 == 13)
                {
                    num = 109;
                }
                else if (num5 == 14)
                {
                    num = 13;
                }
                else if (num5 == 15)
                {
                    num = 189;
                }
                else if (num5 == 16)
                {
                    num = 191;
                }
                else if (num5 == 17)
                {
                    num = 215;
                }
                else if (num5 == 18)
                {
                    num = 26;
                }
                else if (num5 == 19)
                {
                    num = 214;
                }
                else if (num5 == 20)
                {
                    num = 4;
                }
                else if (num5 == 21)
                {
                    num = 10;
                }
                else if (num5 == 22)
                {
                    num = 32;
                }
                else if (num5 == 23)
                {
                    num = 78;
                }
                else if (num5 == 24)
                {
                    num = 147;
                }
                else if (num5 == 25)
                {
                    num = 40;
                }
                else if (num5 == 26)
                {
                    num = 226;
                }
                else if (num5 == 27)
                {
                    num = 23;
                }
                else if (num5 == 28)
                {
                    num = 240;
                }
                else if (num5 == 29)
                {
                    num = 236;
                }
                else if (num5 == 30)
                {
                    num = 68 + Main.rand.Next(3);
                }
                else if (num5 == 31)
                {
                    num = 10;
                }
                else if (num5 == 32)
                {
                    num = 78;
                }
                else if (num5 == 33)
                {
                    num = 148;
                }
                else if (num5 == 34)
                {
                    num = 5;
                }
                else if (num5 == 35)
                {
                    num = 80;
                }
                else if (num5 == 37)
                {
                    num = 18;
                }
                else if (num5 == 38)
                {
                    num = 6;
                }
                else if (num5 == 39)
                {
                    num = 61;
                }
                else if (num5 == 40)
                {
                    num = 242;
                }
                else if (num5 == 41)
                {
                    num = 135;
                }
                else if (num5 == 42)
                {
                    num = 287;
                }
                else if (num5 == 44)
                {
                    num = 273;
                }
                else if (num5 == 45)
                {
                    num = 243;
                }
                else if (num5 == 46)
                {
                    num = 243;
                }
                else if (num5 == 47)
                {
                    num = 36;
                }
                else if (num5 == 48)
                {
                    num = 226;
                }
                else if (num5 == 49)
                {
                    num = 16;
                }
                else if (num5 == 50)
                {
                    num = 309;
                }
                else
                {
                    num = 1;
                }
            }
            if (tileCache.type == 79)
            {
                int num6 = (int)(tileCache.frameY / 36);
                if (num6 == 0)
                {
                    num = 7;
                }
                else if (num6 == 1)
                {
                    num = 77;
                }
                else if (num6 == 2)
                {
                    num = 78;
                }
                else if (num6 == 3)
                {
                    num = 79;
                }
                else if (num6 == 4)
                {
                    num = 126;
                }
                else if (num6 == 8)
                {
                    num = 109;
                }
                else if (num6 >= 9)
                {
                    num = -1;
                }
                else
                {
                    num = 1;
                }
            }
            if (tileCache.type == 18)
            {
                int num7 = (int)(tileCache.frameX / 36);
                if (num7 == 0)
                {
                    num = 7;
                }
                else if (num7 == 1)
                {
                    num = 77;
                }
                else if (num7 == 2)
                {
                    num = 78;
                }
                else if (num7 == 3)
                {
                    num = 79;
                }
                else if (num7 == 4)
                {
                    num = 26;
                }
                else if (num7 == 5)
                {
                    num = 40;
                }
                else if (num7 == 6)
                {
                    num = 5;
                }
                else if (num7 == 7)
                {
                    num = 26;
                }
                else if (num7 == 8)
                {
                    num = 4;
                }
                else if (num7 == 9)
                {
                    num = 126;
                }
                else if (num7 == 10)
                {
                    num = 148;
                }
                else if (num7 == 11 || num7 == 12 || num7 == 13)
                {
                    num = 1;
                }
                else if (num7 == 14)
                {
                    num = 109;
                }
                else if (num7 == 15)
                {
                    num = 126;
                }
                else
                {
                    num = -1;
                }
            }
            if (tileCache.type == 14 || tileCache.type == 87 || tileCache.type == 88 || tileCache.type == 469)
            {
                num = -1;
            }
            if (tileCache.type >= 255 && tileCache.type <= 261)
            {
                int num8 = (int)(tileCache.type - 255);
                num = 86 + num8;
                if (num8 == 6)
                {
                    num = 138;
                }
            }
            if (tileCache.type >= 262 && tileCache.type <= 268)
            {
                int num9 = (int)(tileCache.type - 262);
                num = 86 + num9;
                if (num9 == 6)
                {
                    num = 138;
                }
            }
            if (tileCache.type == 178)
            {
                int num10 = (int)(tileCache.frameX / 18);
                num = 86 + num10;
                if (num10 == 6)
                {
                    num = 138;
                }
            }
            if (tileCache.type == 440)
            {
                switch (tileCache.frameX / 54)
                {
                case 0:
                    num = 90;
                    break;
                case 1:
                    num = 88;
                    break;
                case 2:
                    num = 89;
                    break;
                case 3:
                    num = 87;
                    break;
                case 4:
                    num = 86;
                    break;
                case 5:
                    num = 91;
                    break;
                case 6:
                    num = 138;
                    break;
                default:
                    num = -1;
                    break;
                }
                if (tileCache.frameY < 54)
                {
                    num = -1;
                }
            }
            num2 = tileCache.type;
            if (num2 <= 496)
            {
                switch (num2)
                {
                case 426:
                case 427:
                    break;
                case 428:
                case 429:
                    goto IL_18E0;
                case 430:
                case 435:
                    goto IL_18BB;
                case 431:
                case 436:
                    goto IL_18C0;
                case 432:
                case 437:
                    goto IL_18C5;
                case 433:
                case 438:
                    goto IL_18CA;
                case 434:
                case 439:
                    goto IL_18CF;
                default:
                    if (num2 != 496)
                    {
                        goto IL_18E0;
                    }
                    num = 109;
                    goto IL_18E0;
                }
            }
            else
            {
                if (num2 == 549)
                {
                    num = 3;
                    goto IL_18E0;
                }
                if (num2 == 552)
                {
                    num = 32;
                    goto IL_18E0;
                }
                switch (num2)
                {
                case 727:
                    break;
                case 728:
                    goto IL_18BB;
                case 729:
                    goto IL_18C0;
                case 730:
                    goto IL_18C5;
                case 731:
                    goto IL_18CA;
                case 732:
                    goto IL_18CF;
                default:
                    goto IL_18E0;
                }
            }
            num = 90;
            goto IL_18E0;
            IL_18BB:
            num = 89;
            goto IL_18E0;
            IL_18C0:
            num = 88;
            goto IL_18E0;
            IL_18C5:
            num = 87;
            goto IL_18E0;
            IL_18CA:
            num = 86;
            goto IL_18E0;
            IL_18CF:
            num = 91;
            IL_18E0:
            if (tileCache.type == 186)
            {
                if (tileCache.frameX <= 360)
                {
                    num = 26;
                }
                else if (tileCache.frameX <= 846)
                {
                    num = 1;
                }
                else if (tileCache.frameX <= 954)
                {
                    num = 9;
                }
                else if (tileCache.frameX <= 1062)
                {
                    num = 11;
                }
                else if (tileCache.frameX <= 1170)
                {
                    num = 10;
                }
                else if (tileCache.frameX <= 1332)
                {
                    num = 0;
                }
                else if (tileCache.frameX <= 1386)
                {
                    num = 10;
                }
                else
                {
                    num = 80;
                }
            }
            if (tileCache.type == 187)
            {
                if (tileCache.frameX <= 144)
                {
                    num = 1;
                }
                else if (tileCache.frameX <= 306)
                {
                    num = 38;
                }
                else if (tileCache.frameX <= 468)
                {
                    num = 36;
                }
                else if (tileCache.frameX <= 738)
                {
                    num = 30;
                }
                else if (tileCache.frameX <= 970)
                {
                    num = 1;
                }
                else if (tileCache.frameX <= 1132)
                {
                    num = 148;
                }
                else if (tileCache.frameX <= 1132)
                {
                    num = 155;
                }
                else if (tileCache.frameX <= 1348)
                {
                    num = 1;
                }
                else if (tileCache.frameX <= 1564)
                {
                    num = 0;
                }
                else if (tileCache.frameX <= 1890)
                {
                    num = 250;
                }
                else if (tileCache.frameX <= 2196)
                {
                    num = 240;
                }
                else if (tileCache.frameX <= 2520)
                {
                    num = 236;
                }
            }
            if (tileCache.type == 647)
            {
                int num11 = (int)(tileCache.frameX / 54);
                if (num11 < 7)
                {
                    num = 26;
                }
                else if (num11 < 16)
                {
                    num = 1;
                }
                else if (num11 < 18)
                {
                    num = 9;
                }
                else if (num11 < 20)
                {
                    num = 11;
                }
                else if (num11 < 22)
                {
                    num = 10;
                }
                else if (num11 < 26)
                {
                    num = 7;
                }
                else if (num11 < 32)
                {
                    num = 80;
                }
                else if (num11 < 35)
                {
                    num = 80;
                }
            }
            if (tileCache.type == 648)
            {
                int num12 = (int)(tileCache.frameX / 54);
                num12 += (int)(tileCache.frameY / 36 * 35);
                if (num12 < 3)
                {
                    num = 1;
                }
                else if (num12 < 6)
                {
                    num = 38;
                }
                else if (num12 < 9)
                {
                    num = 36;
                }
                else if (num12 < 14)
                {
                    num = 30;
                }
                else if (num12 < 17)
                {
                    num = 1;
                }
                else if (num12 < 18)
                {
                    num = 1;
                }
                else if (num12 < 21)
                {
                    num = 148;
                }
                else if (num12 < 29)
                {
                    num = 155;
                }
                else if (num12 < 35)
                {
                    num = 287;
                }
                else if (num12 < 41)
                {
                    num = 240;
                }
                else if (num12 < 47)
                {
                    num = 236;
                }
                else if (num12 < 50)
                {
                    num = 0;
                }
                else if (num12 < 52)
                {
                    num = 2;
                }
                else if (num12 < 55)
                {
                    num = 26;
                }
            }
            if (tileCache.type == 706)
            {
                num = 1;
            }
            if (tileCache.type == 105)
            {
                num = 1;
                if (tileCache.frameX >= 1548 && tileCache.frameX <= 1654 && tileCache.frameY < 54)
                {
                    num = 148;
                }
            }
            if (tileCache.type == 349)
            {
                num = 1;
            }
            if (tileCache.type == 337 || tileCache.type == 506)
            {
                num = 1;
            }
            if (tileCache.type == 239)
            {
                short num13 = tileCache.frameX / 18;
                if (num13 == 0)
                {
                    num = 9;
                }
                if (num13 == 1)
                {
                    num = 81;
                }
                if (num13 == 2)
                {
                    num = 8;
                }
                if (num13 == 3)
                {
                    num = 82;
                }
                if (num13 == 4)
                {
                    num = 11;
                }
                if (num13 == 5)
                {
                    num = 83;
                }
                if (num13 == 6)
                {
                    num = 10;
                }
                if (num13 == 7)
                {
                    num = 84;
                }
                if (num13 == 8)
                {
                    num = 14;
                }
                if (num13 == 9)
                {
                    num = 23;
                }
                if (num13 == 10)
                {
                    num = 25;
                }
                if (num13 == 11)
                {
                    num = 48;
                }
                if (num13 == 12)
                {
                    num = 144;
                }
                if (num13 == 13)
                {
                    num = 49;
                }
                if (num13 == 14)
                {
                    num = 145;
                }
                if (num13 == 15)
                {
                    num = 50;
                }
                if (num13 == 16)
                {
                    num = 146;
                }
                if (num13 == 17)
                {
                    num = 128;
                }
                if (num13 == 18)
                {
                    num = 84;
                }
                if (num13 == 19)
                {
                    num = 117;
                }
                if (num13 == 20)
                {
                    num = 42;
                }
                if (num13 == 21)
                {
                    num = -1;
                }
                if (num13 == 22)
                {
                    num = 265;
                }
            }
            if (tileCache.type == 185)
            {
                if (tileCache.frameY == 18)
                {
                    int num14 = (int)(tileCache.frameX / 36);
                    if (num14 < 6)
                    {
                        num = 1;
                    }
                    else if (num14 < 16)
                    {
                        num = 26;
                    }
                    else if (num14 == 16)
                    {
                        num = 9;
                    }
                    else if (num14 == 17)
                    {
                        num = 11;
                    }
                    else if (num14 == 18)
                    {
                        num = 10;
                    }
                    else if (num14 == 19)
                    {
                        num = 86;
                    }
                    else if (num14 == 20)
                    {
                        num = 87;
                    }
                    else if (num14 == 21)
                    {
                        num = 88;
                    }
                    else if (num14 == 22)
                    {
                        num = 89;
                    }
                    else if (num14 == 23)
                    {
                        num = 90;
                    }
                    else if (num14 == 24)
                    {
                        num = 91;
                    }
                    else if (num14 < 31)
                    {
                        num = 80;
                    }
                    else if (num14 < 33)
                    {
                        num = 7;
                    }
                    else if (num14 < 34)
                    {
                        num = 8;
                    }
                    else if (num14 < 38)
                    {
                        num = 30;
                    }
                    else if (num14 < 41)
                    {
                        num = 1;
                    }
                    else if (num14 < 47)
                    {
                        num = 287;
                    }
                    else if (num14 < 53)
                    {
                        num = 240;
                    }
                    else if (num14 < 59)
                    {
                        num = 236;
                    }
                }
                else
                {
                    int num15 = (int)(tileCache.frameX / 18);
                    if (num15 < 6)
                    {
                        num = 1;
                    }
                    else if (num15 < 12)
                    {
                        num = 0;
                    }
                    else if (num15 < 28)
                    {
                        num = 26;
                    }
                    else if (num15 < 33)
                    {
                        num = 1;
                    }
                    else if (num15 < 36)
                    {
                        num = 0;
                    }
                    else if (num15 < 48)
                    {
                        num = 80;
                    }
                    else if (num15 < 54)
                    {
                        num = 30;
                    }
                    else if (num15 < 60)
                    {
                        num = 287;
                    }
                    else if (num15 < 66)
                    {
                        num = 240;
                    }
                    else if (num15 < 72)
                    {
                        num = 236;
                    }
                    else if (num15 < 73)
                    {
                        num = 0;
                    }
                    else if (num15 < 77)
                    {
                        num = 32;
                    }
                }
            }
            if (tileCache.type == 649)
            {
                int num16 = (int)(tileCache.frameX / 36 + tileCache.frameY / 18 * 53);
                if (num16 < 6)
                {
                    num = 1;
                }
                else if (num16 < 16)
                {
                    num = 26;
                }
                else if (num16 == 16)
                {
                    num = 9;
                }
                else if (num16 == 17)
                {
                    num = 11;
                }
                else if (num16 == 18)
                {
                    num = 10;
                }
                else if (num16 == 19)
                {
                    num = 86;
                }
                else if (num16 == 20)
                {
                    num = 87;
                }
                else if (num16 == 21)
                {
                    num = 88;
                }
                else if (num16 == 22)
                {
                    num = 89;
                }
                else if (num16 == 23)
                {
                    num = 90;
                }
                else if (num16 == 24)
                {
                    num = 91;
                }
                else if (num16 < 31)
                {
                    num = 80;
                }
                else if (num16 < 33)
                {
                    num = 7;
                }
                else if (num16 < 34)
                {
                    num = 8;
                }
                else if (num16 < 38)
                {
                    num = 30;
                }
                else if (num16 < 41)
                {
                    num = 1;
                }
                else if (num16 < 47)
                {
                    num = 287;
                }
                else if (num16 < 53)
                {
                    num = 240;
                }
                else if (num16 < 59)
                {
                    num = 236;
                }
                else if (num16 < 62)
                {
                    num = 0;
                }
                else if (num16 < 64 || (num16 >= 65 && num16 <= 67))
                {
                    num = 32;
                }
                else if (num16 == 64)
                {
                    num = 40;
                }
            }
            if (tileCache.type == 650)
            {
                int num17 = (int)(tileCache.frameX / 18);
                if (num17 < 6)
                {
                    num = 1;
                }
                else if (num17 < 12)
                {
                    num = 0;
                }
                else if (num17 < 28)
                {
                    num = 26;
                }
                else if (num17 < 33)
                {
                    num = 1;
                }
                else if (num17 < 36)
                {
                    num = 0;
                }
                else if (num17 < 48)
                {
                    num = 80;
                }
                else if (num17 < 54)
                {
                    num = 30;
                }
                else if (num17 < 60)
                {
                    num = 287;
                }
                else if (num17 < 66)
                {
                    num = 240;
                }
                else if (num17 < 72)
                {
                    num = 236;
                }
                else if (num17 < 73)
                {
                    num = 0;
                }
                else if (num17 == 73 || num17 == 74 || num17 == 76 || (num17 >= 78 && num17 <= 81))
                {
                    num = 32;
                }
                else if (num17 == 75 || num17 == 77)
                {
                    num = 40;
                }
            }
            if (tileCache.type == 237)
            {
                num = 148;
            }
            if (tileCache.type == 157)
            {
                num = 77;
            }
            if (tileCache.type == 158 || tileCache.type == 232 || tileCache.type == 383 || tileCache.type == 575)
            {
                num = 78;
            }
            if (tileCache.type == 159)
            {
                num = 78;
            }
            if (tileCache.type == 15)
            {
                num = -1;
            }
            if (tileCache.type == 191)
            {
                num = 7;
            }
            if (tileCache.type == 5)
            {
                num = 7;
                if (i > 5 && i < Main.maxTilesX - 5)
                {
                    int num18 = i;
                    int num19 = j;
                    if (tileCache.frameX == 66 && tileCache.frameY <= 45)
                    {
                        num18++;
                    }
                    if (tileCache.frameX == 88 && tileCache.frameY >= 66 && tileCache.frameY <= 110)
                    {
                        num18--;
                    }
                    if (tileCache.frameX == 22 && tileCache.frameY >= 132 && tileCache.frameY <= 176)
                    {
                        num18--;
                    }
                    if (tileCache.frameX == 44 && tileCache.frameY >= 132 && tileCache.frameY <= 176)
                    {
                        num18++;
                    }
                    if (tileCache.frameX == 44 && tileCache.frameY >= 132 && tileCache.frameY <= 176)
                    {
                        num18++;
                    }
                    if (tileCache.frameX == 44 && tileCache.frameY >= 198)
                    {
                        num18++;
                    }
                    if (tileCache.frameX == 66 && tileCache.frameY >= 198)
                    {
                        num18--;
                    }
                    while (Main.tile[num18, num19] != null && (!Main.tile[num18, num19].active() || !Main.tileSolid[(int)Main.tile[num18, num19].type]))
                    {
                        num19++;
                    }
                    if (Main.tile[num18, num19] != null)
                    {
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 23)
{
                            num = 77;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 661)
{
                            num = 77;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 60)
{
                            num = 78;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 70)
{
                            num = 26;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 109)
{
                            num = 79;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 199)
{
                            num = 121;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 662)
{
                            num = 121;
                        }
                        if (Main.tile[num18, num19].active() && Main.tile[num18, num19].type == 147)
{
                            num = 122;
                        }
                    }
                }
            }
            if (tileCache.type == 323)
            {
                num = 215;
                if (i > 5 && i < Main.maxTilesX - 5)
                {
                    int num20 = j;
                    while (Main.tile[i, num20] != null && (!Main.tile[i, num20].active() || !Main.tileSolid[(int)Main.tile[i, num20].type]))
                    {
                        num20++;
                    }
                    if (Main.tile[i, num20] != null)
                    {
                        if (Main.tile[i, num20].active() && Main.tile[i, num20].type == 234)
{
                            num = 121;
                        }
                        if (Main.tile[i, num20].active() && Main.tile[i, num20].type == 116)
{
                            num = 79;
                        }
                        if (Main.tile[i, num20].active() && Main.tile[i, num20].type == 112)
{
                            num = 77;
                        }
                    }
                }
            }
            if (tileCache.type == 137)
            {
                switch (tileCache.frameY / 18)
                {
                default:
                    num = 1;
                    break;
                case 1:
                case 2:
                case 3:
                case 4:
                    num = 148;
                    break;
                case 5:
                    num = 1;
                    break;
                }
            }
            if (tileCache.type == 443)
            {
                num = 1;
            }
            if (tileCache.type == 444)
            {
                num = -1;
            }
            if (tileCache.type == 212)
            {
                num = -1;
            }
            if (tileCache.type == 213)
            {
                num = 129;
            }
            if (tileCache.type == 214)
            {
                num = 1;
            }
            if (tileCache.type == 215)
            {
                num = -6;
            }
            if (tileCache.type == 325)
            {
                num = 81;
            }
            if (tileCache.type == 251)
            {
                num = 189;
            }
            if (tileCache.type == 252)
            {
                num = 190;
            }
            if (tileCache.type == 253)
            {
                num = 191;
            }
            if (tileCache.type == 254)
            {
                if (tileCache.frameX < 72)
                {
                    num = 3;
                }
                else if (tileCache.frameX < 108)
                {
                    num = 3;
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        num = 189;
                    }
                }
                else if (tileCache.frameX < 144)
                {
                    num = 3;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num = 189;
                    }
                }
                else
                {
                    num = 3;
                    if (WorldGen.genRand.Next(4) != 0)
                    {
                        num = 189;
                    }
                }
            }
            if (tileCache.type == 467)
            {
                num = -1;
            }
            if (tileCache.type == 21)
            {
                if (tileCache.frameX >= 1008)
                {
                    num = -1;
                }
                else if (tileCache.frameX >= 612)
                {
                    num = 11;
                }
                else if (tileCache.frameX >= 576)
                {
                    num = 148;
                }
                else if (tileCache.frameX >= 540)
                {
                    num = 26;
                }
                else if (tileCache.frameX >= 504)
                {
                    num = 126;
                }
                else if (tileCache.frameX >= 468)
                {
                    num = 116;
                }
                else if (tileCache.frameX >= 432)
                {
                    num = 7;
                }
                else if (tileCache.frameX >= 396)
                {
                    num = 11;
                }
                else if (tileCache.frameX >= 360)
                {
                    num = 10;
                }
                else if (tileCache.frameX >= 324)
                {
                    num = 79;
                }
                else if (tileCache.frameX >= 288)
                {
                    num = 78;
                }
                else if (tileCache.frameX >= 252)
                {
                    num = 77;
                }
                else if (tileCache.frameX >= 216)
                {
                    num = 1;
                }
                else if (tileCache.frameX >= 180)
                {
                    num = 7;
                }
                else if (tileCache.frameX >= 108)
                {
                    num = 37;
                }
                else if (tileCache.frameX >= 36)
                {
                    num = 10;
                }
                else
                {
                    num = 7;
                }
            }
            if (tileCache.type == 382)
            {
                num = 3;
            }
            if (tileCache.type == 2 || tileCache.type == 477)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 0;
                }
                else
                {
                    num = 2;
                }
            }
            if (tileCache.type == 127)
            {
                num = 67;
            }
            if (tileCache.type == 91)
            {
                num = -1;
            }
            if (tileCache.type == 198)
            {
                num = 109;
            }
            if (tileCache.type == 34)
            {
                num = -1;
            }
            if (tileCache.type == 6)
            {
                num = 8;
            }
            if (tileCache.type == 7 || tileCache.type == 47 || tileCache.type == 284 || tileCache.type == 682)
            {
                num = 9;
            }
            if (tileCache.type == 8 || tileCache.type == 45 || tileCache.type == 102 || tileCache.type == 680)
            {
                num = 10;
            }
            if (tileCache.type == 9 || tileCache.type == 42 || tileCache.type == 46 || tileCache.type == 126 || tileCache.type == 136 || tileCache.type == 681)
            {
                num = 11;
            }
            if (tileCache.type == 166 || tileCache.type == 175)
            {
                num = 81;
            }
            if (tileCache.type == 167)
            {
                num = 82;
            }
            if (tileCache.type == 168 || tileCache.type == 176)
            {
                num = 83;
            }
            if (tileCache.type == 169 || tileCache.type == 177)
            {
                num = 84;
            }
            if (tileCache.type == 199 || tileCache.type == 662)
            {
                num = 117;
            }
            if (tileCache.type == 205)
            {
                num = 125;
            }
            if (tileCache.type == 201)
            {
                num = 125;
            }
            if (tileCache.type == 211)
            {
                num = 128;
            }
            if (tileCache.type == 227)
            {
                int num21 = (int)(tileCache.frameX / 34);
                if (num21 == 0 || num21 == 1)
                {
                    num = 26;
                }
                else if (num21 == 3)
                {
                    num = 3;
                }
                else if (num21 == 2 || num21 == 4 || num21 == 5 || num21 == 6)
                {
                    num = 40;
                }
                else if (num21 == 7)
                {
                    num = 117;
                }
                else if (num21 == 8)
                {
                    num = 17;
                }
                else if (num21 == 9)
                {
                    num = 6;
                }
                else if (num21 == 10)
                {
                    num = 3;
                }
                else if (num21 == 11)
                {
                    num = 26;
                }
            }
            if (tileCache.type == 204 || tileCache.type == 478)
            {
                num = 117;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 1;
                }
            }
            if (tileCache.type == 203)
            {
                num = 117;
            }
            if (tileCache.type == 243)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 7;
                }
                else
                {
                    num = 13;
                }
            }
            if (tileCache.type == 219)
            {
                num = -1;
            }
            if (tileCache.type == 642)
            {
                num = -128;
            }
            if (tileCache.type == 244)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 1;
                }
                else
                {
                    num = 13;
                }
            }
            if (tileCache.type == 597)
            {
                num = -1;
            }
            else if ((tileCache.type >= 358 && tileCache.type <= 364) || (tileCache.type >= 275 && tileCache.type <= 282) || (tileCache.type == 285 || tileCache.type == 286 || (tileCache.type >= 288 && tileCache.type <= 297)) || (tileCache.type >= 316 && tileCache.type <= 318) || tileCache.type == 298 || tileCache.type == 299 || tileCache.type == 309 || tileCache.type == 310 || tileCache.type == 339 || tileCache.type == 538 || tileCache.type == 413 || tileCache.type == 414 || tileCache.type == 505 || tileCache.type == 521 || tileCache.type == 522 || tileCache.type == 523 || tileCache.type == 524 || tileCache.type == 525 || tileCache.type == 526 || tileCache.type == 527 || tileCache.type == 532 || tileCache.type == 543 || tileCache.type == 544 || tileCache.type == 550 || tileCache.type == 551 || tileCache.type == 533 || tileCache.type == 553 || tileCache.type == 554 || tileCache.type == 555 || tileCache.type == 556 || tileCache.type == 558 || tileCache.type == 559 || tileCache.type == 542 || tileCache.type == 391 || tileCache.type == 394 || tileCache.type == 392 || tileCache.type == 393 || tileCache.type == 568 || tileCache.type == 569 || tileCache.type == 570 || tileCache.type == 582 || tileCache.type == 580 || tileCache.type == 598 || tileCache.type == 599 || tileCache.type == 600 || tileCache.type == 601 || tileCache.type == 602 || tileCache.type == 603 || tileCache.type == 604 || tileCache.type == 605 || tileCache.type == 606 || tileCache.type == 607 || tileCache.type == 608 || tileCache.type == 609 || tileCache.type == 610 || tileCache.type == 611 || tileCache.type == 612 || tileCache.type == 619 || tileCache.type == 620 || tileCache.type == 629 || tileCache.type == 632 || tileCache.type == 640 || tileCache.type == 643 || tileCache.type == 644 || tileCache.type == 645 || tileCache.type == 710)
            {
                num = 13;
                if (WorldGen.genRand.Next(3) != 0)
                {
                    num = -1;
                }
            }
            if (tileCache.type == 13)
            {
                if (tileCache.frameX >= 90)
                {
                    num = -1;
                }
                else
                {
                    num = 13;
                }
            }
            if (tileCache.type == 189)
            {
                num = 16;
            }
            if (tileCache.type == 717)
            {
                num = 326;
            }
            if (tileCache.type == 718)
            {
                num = 327;
            }
            if (tileCache.type == 719)
            {
                num = 328;
            }
            if (tileCache.type == 460)
            {
                num = 16;
            }
            if (tileCache.type == 530)
            {
                int type2 = (int)Main.tile[i, j + 2 - (int)(tileCache.frameY / 18)].type;
                if (type2 == 116)
                {
                    num = 47;
                }
                else if (type2 == 234)
                {
                    num = 125;
                }
                else if (type2 == 112)
                {
                    num = 17;
                }
                else if (tileCache.frameX < 270)
                {
                    num = 40;
                }
                else
                {
                    num = 291;
                }
            }
            if (tileCache.type == 705)
            {
                int num22 = (int)(tileCache.frameX / 54 + tileCache.frameY / 36 * 10);
                bool flag = tileCache.frameX % 486 < 270;
                if (num22 >= 0 && num22 <= 8)
                {
                    num = (flag ? 291 : 40);
                }
                else if (num22 >= 9 && num22 <= 17)
                {
                    num = 47;
                }
                else if (num22 >= 18 && num22 <= 26)
                {
                    num = 125;
                }
                else
                {
                    num = 17;
                }
            }
            if (tileCache.type == 518)
            {
                if (tileCache.frameY == 0)
                {
                    num = 3;
                }
                else if (tileCache.frameY == 18)
                {
                    num = 47;
                }
                else if (tileCache.frameY == 36)
                {
                    num = 40;
                }
            }
            else if (tileCache.type == 519)
            {
                if (tileCache.frameY == 0)
                {
                    num = 3;
                }
                else if (tileCache.frameY == 18)
                {
                    num = 40;
                }
                else if (tileCache.frameY == 36)
                {
                    num = 47;
                }
                else if (tileCache.frameY == 54)
                {
                    num = 125;
                }
                else if (tileCache.frameY == 72)
                {
                    num = 17;
                }
                else if (tileCache.frameY == 90)
                {
                    num = 26;
                }
            }
            else if (tileCache.type == 636)
            {
                num = 17;
            }
            else if (tileCache.type == 528)
            {
                num = 26;
            }
            if (tileCache.type == 12)
            {
                num = 12;
            }
            if (tileCache.type == 639)
            {
                num = 48;
            }
            if (tileCache.type == 3 || tileCache.type == 73)
            {
                num = 3;
            }
            if (tileCache.type == 54)
            {
                num = 13;
            }
            if (tileCache.type == 22 || tileCache.type == 140)
            {
                num = 14;
            }
            if (tileCache.type == 78)
            {
                num = 22;
            }
            if (tileCache.type == 28 || tileCache.type == 653)
            {
                num = 22;
                if (tileCache.frameY >= 72 && tileCache.frameY <= 90)
                {
                    num = 1;
                }
                if (tileCache.frameY >= 144 && tileCache.frameY <= 234)
                {
                    num = 48;
                }
                if (tileCache.frameY >= 252 && tileCache.frameY <= 358)
                {
                    num = 85;
                }
                if (tileCache.frameY >= 360 && tileCache.frameY <= 466)
                {
                    num = 26;
                }
                if (tileCache.frameY >= 468 && tileCache.frameY <= 574)
                {
                    num = 36;
                }
                if (tileCache.frameY >= 576 && tileCache.frameY <= 790)
                {
                    num = 18;
                }
                if (tileCache.frameY >= 792 && tileCache.frameY <= 898)
                {
                    num = 5;
                }
                if (tileCache.frameY >= 900 && tileCache.frameY <= 1006)
                {
                    num = 0;
                }
                if (tileCache.frameY >= 1008 && tileCache.frameY <= 1114)
                {
                    num = 148;
                }
                if (tileCache.frameY >= 1116 && tileCache.frameY <= 1222)
                {
                    num = 241;
                }
                if (tileCache.frameY >= 1224 && tileCache.frameY <= 1330)
                {
                    num = 287;
                }
            }
            if (tileCache.type == 163)
            {
                num = 118;
            }
            if (tileCache.type == 164)
            {
                num = 119;
            }
            if (tileCache.type == 200)
            {
                num = 120;
            }
            if (tileCache.type == 221 || tileCache.type == 248)
            {
                num = 144;
            }
            if (tileCache.type == 222 || tileCache.type == 249)
            {
                num = 145;
            }
            if (tileCache.type == 223 || tileCache.type == 250)
            {
                num = 146;
            }
            if (tileCache.type == 224)
            {
                num = 149;
            }
            if (tileCache.type == 225)
            {
                num = 147;
            }
            if (tileCache.type == 229)
            {
                num = 153;
            }
            if (tileCache.type == 231)
            {
                num = 153;
                if (WorldGen.genRand.Next(3) == 0)
                {
                    num = 26;
                }
            }
            if (tileCache.type == 226)
            {
                num = 148;
            }
            if (tileCache.type == 103)
            {
                num = -1;
            }
            if (tileCache.type == 29)
            {
                num = 23;
            }
            if (tileCache.type == 40)
            {
                num = 28;
            }
            if (tileCache.type == 50 || tileCache.type == 707)
            {
                num = 22;
            }
            if (tileCache.type == 51 || tileCache.type == 697)
            {
                num = 30;
            }
            if (tileCache.type == 52 || tileCache.type == 353)
            {
                num = 3;
            }
            if (tileCache.type == 53 || tileCache.type == 81 || tileCache.type == 151 || tileCache.type == 202 || tileCache.type == 274 || tileCache.type == 495)
            {
                num = 32;
            }
            if (tileCache.type == 56 || tileCache.type == 152)
            {
                num = 37;
            }
            if (tileCache.type == 75 || tileCache.type == 683)
            {
                num = 109;
            }
            if (tileCache.type == 57 || tileCache.type == 119 || tileCache.type == 141 || tileCache.type == 234 || tileCache.type == 635 || tileCache.type == 654)
            {
                num = 36;
            }
            if (tileCache.type == 59 || tileCache.type == 120)
            {
                num = 38;
            }
            if (tileCache.type == 61 || tileCache.type == 703 || tileCache.type == 62 || tileCache.type == 74 || tileCache.type == 80 || tileCache.type == 188 || tileCache.type == 233 || tileCache.type == 236 || tileCache.type == 702 || tileCache.type == 384 || tileCache.type == 652 || tileCache.type == 651)
            {
                num = 40;
            }
            if (tileCache.type == 485)
            {
                num = 32;
            }
            if (tileCache.type == 238)
            {
                if (WorldGen.genRand.Next(3) == 0)
                {
                    num = 167;
                }
                else
                {
                    num = 166;
                }
            }
            if (tileCache.type == 69)
            {
                num = 7;
            }
            if (tileCache.type == 655)
            {
                num = 166;
            }
            if (tileCache.type == 71 || tileCache.type == 72 || tileCache.type == 190 || tileCache.type == 578)
            {
                num = 26;
            }
            if (tileCache.type == 70)
            {
                num = 17;
            }
            if (tileCache.type == 112)
            {
                num = 14;
            }
            if (tileCache.type == 123)
            {
                num = 53;
            }
            if (tileCache.type == 161)
            {
                num = 80;
            }
            if (tileCache.type == 206)
            {
                num = 80;
            }
            if (tileCache.type == 162)
            {
                num = 80;
            }
            if (tileCache.type == 165 || tileCache.type == 693 || tileCache.type == 694)
            {
                switch (tileCache.frameX / 54)
                {
                case 0:
                    num = 80;
                    break;
                case 1:
                    num = 1;
                    break;
                case 2:
                    num = 30;
                    break;
                case 3:
                    num = 147;
                    break;
                case 4:
                    num = 51;
                    break;
                case 5:
                    num = 14;
                    break;
                case 6:
                    num = 117;
                    break;
                case 7:
                    num = 250;
                    break;
                case 8:
                    num = 240;
                    break;
                case 9:
                    num = 236;
                    break;
                case 10:
                    num = 119;
                    break;
                case 11:
                    num = 118;
                    break;
                case 12:
                    num = 120;
                    break;
                default:
                    num = 1;
                    break;
                }
            }
            if (tileCache.type == 666)
            {
                num = 322;
            }
            if (tileCache.type == 193)
            {
                num = 4;
            }
            if (tileCache.type == 194)
            {
                num = 26;
            }
            if (tileCache.type == 195)
            {
                num = 5;
            }
            if (tileCache.type == 196)
            {
                num = 108;
            }
            if (tileCache.type == 460)
            {
                num = 108;
            }
            if (tileCache.type == 197)
            {
                num = 4;
            }
            if (tileCache.type == 153)
            {
                num = 26;
            }
            if (tileCache.type == 154)
            {
                num = 32;
            }
            if (tileCache.type == 155)
            {
                num = 2;
            }
            if (tileCache.type == 156)
            {
                num = 1;
            }
            if (tileCache.type == 116 || tileCache.type == 117 || tileCache.type == 118 || tileCache.type == 147 || tileCache.type == 148)
            {
                num = 51;
            }
            if (tileCache.type == 109 || tileCache.type == 492)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 0;
                }
                else
                {
                    num = 47;
                }
            }
            if (tileCache.type == 110 || tileCache.type == 113 || tileCache.type == 115)
            {
                num = 47;
            }
            if (tileCache.type == 107 || tileCache.type == 121 || tileCache.type == 685)
            {
                num = 48;
            }
            if (tileCache.type == 108 || tileCache.type == 122 || tileCache.type == 146 || tileCache.type == 686)
            {
                num = 49;
            }
            if (tileCache.type == 111 || tileCache.type == 145 || tileCache.type == 150)
            {
                num = 50;
            }
            if (tileCache.type == 133)
            {
                num = 50;
                if (tileCache.frameX >= 54)
                {
                    num = 146;
                }
            }
            if (tileCache.type == 134)
            {
                num = 49;
                if (tileCache.frameX >= 36)
                {
                    num = 145;
                }
            }
            if (tileCache.type == 149)
            {
                num = 49;
            }
            if (Main.tileAlch[(int)tileCache.type])
            {
                short num23 = tileCache.frameX / 18;
                if (num23 == 0)
                {
                    num = 3;
                }
                if (num23 == 1)
                {
                    num = 3;
                }
                if (num23 == 2)
                {
                    num = 7;
                }
                if (num23 == 3)
                {
                    num = 17;
                }
                if (num23 == 4)
                {
                    num = 289;
                }
                if (num23 == 5)
                {
                    num = 6;
                }
                if (num23 == 6)
                {
                    num = 224;
                }
            }
            if (tileCache.type == 58 || tileCache.type == 76 || tileCache.type == 77 || tileCache.type == 684)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 6;
                }
                else
                {
                    num = 25;
                }
            }
            if (tileCache.type == 37)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 6;
                }
                else
                {
                    num = 23;
                }
            }
            if (tileCache.type == 32)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 14;
                }
                else
                {
                    num = 24;
                }
            }
            if (tileCache.type == 352)
            {
                if (WorldGen.genRand.Next(3) == 0)
                {
                    num = 5;
                }
                else
                {
                    num = 125;
                }
            }
            if (tileCache.type == 23 || tileCache.type == 24 || tileCache.type == 661)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 14;
                }
                else
                {
                    num = 17;
                }
            }
            if (tileCache.type == 25 || tileCache.type == 31 || tileCache.type == 696)
            {
                if ((tileCache.type == 31 || tileCache.type == 696) && tileCache.frameX >= 36)
                {
                    num = 5;
                }
                else if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 14;
                }
                else
                {
                    num = 1;
                }
            }
            if (tileCache.type == 26 || tileCache.type == 695)
            {
                if (tileCache.frameX >= 54)
                {
                    num = 5;
                }
                else if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 14;
                }
                else
                {
                    num = 1;
                }
            }
            if (tileCache.type == 20)
            {
                int num24 = (int)(tileCache.frameX / 54);
                if (num24 == 1)
                {
                    num = 122;
                }
                else if (num24 == 2)
                {
                    num = 78;
                }
                else if (num24 == 3)
                {
                    num = 77;
                }
                else if (num24 == 4)
                {
                    num = 121;
                }
                else if (num24 == 5)
                {
                    num = 79;
                }
                else
                {
                    num = 7;
                }
            }
            if (tileCache.type == 27)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 3;
                }
                else
                {
                    num = 19;
                }
            }
            if (tileCache.type == 129)
            {
                if (tileCache.frameX >= 324)
                {
                }
                if (tileCache.frameX == 0 || tileCache.frameX == 54 || tileCache.frameX == 108)
                {
                    num = 68;
                }
                else if (tileCache.frameX == 18 || tileCache.frameX == 72 || tileCache.frameX == 126)
                {
                    num = 69;
                }
                else
                {
                    num = 70;
                }
            }
            if (tileCache.type == 385)
            {
                num = WorldGen.genRand.Next(68, 71);
            }
            if (tileCache.type == 4)
            {
                int num25 = (int)MathHelper.Clamp((float)(tileCache.frameY / 22), 0f, (float)(TorchID.Count - 1));
                num = TorchID.Dust[num25];
            }
            if (tileCache.type == 35)
            {
                num = 189;
                if (tileCache.frameX < 36 && WorldGen.genRand.Next(2) == 0)
                {
                    num = 6;
                }
            }
            if ((tileCache.type == 34 || tileCache.type == 42) && WorldGen.genRand.Next(2) == 0)
            {
                num = 6;
            }
            if (tileCache.type == 270)
            {
                num = -1;
            }
            if (tileCache.type == 271)
            {
                num = -1;
            }
            if (tileCache.type == 581)
            {
                num = -1;
            }
            if (tileCache.type == 660)
            {
                num = -1;
            }
            if (tileCache.type == 698)
            {
                num = -1;
            }
            if (tileCache.type == 79 || tileCache.type == 90 || tileCache.type == 101)
            {
                num = -1;
            }
            if (tileCache.type == 33 || tileCache.type == 34 || tileCache.type == 42 || tileCache.type == 93 || tileCache.type == 100)
            {
                num = -1;
            }
            if (tileCache.type == 321 || tileCache.type == 574)
            {
                num = 214;
            }
            if (tileCache.type == 322)
            {
                num = 215;
            }
            if (tileCache.type == 635)
            {
                num = 36;
            }
            bool flag2 = tileCache.type == 178 || tileCache.type == 440;
            num2 = tileCache.type;
            if (num2 <= 427)
            {
                if (num2 != 178 && num2 - 426 > 1)
                {
                    goto IL_3E3B;
                }
            }
            else if (num2 - 430 > 10 && num2 - 727 > 5)
            {
                goto IL_3E3B;
            }
            flag2 = true;
            IL_3E3B:
            if (num < 0)
            {
                return 6000;
            }
            if (tileCache.type == 627 || tileCache.type == 628 || (tileCache.type == 184 && tileCache.frameX / 22 == 10))
            {
                int num26 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), 1f);
                Main.dust[num26].noGravity = true;
                Main.dust[num26].noLightEmittance = true;
                return num26;
            }
            if (tileCache.type == 518)
            {
                int num27 = (int)(tileCache.liquid / 16);
                num27 -= 3;
                if (WorldGen.SolidTile(i, j - 1, false) && num27 > 8)
                {
                    num27 = 8;
                }
                return Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16 - num27)), 16, 16, num, 0f, 0f, 0, default(Color), 1f);
            }
            if (tileCache.type == 352 && num == 5)
            {
                int num28 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 5, 0f, 0f, 100, default(Color), 1f);
                Main.dust[num28].scale = 1.5f;
                Main.dust[num28].noGravity = true;
                Main.dust[num28].velocity *= 1.65f;
                Main.dust[num28].fadeIn = 1.6f;
                return num28;
            }
            if (tileCache.type == 160 || tileCache.type == 692)
            {
                int num29 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 66, 0f, 0f, 100, new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB), 0.75f);
                Main.dust[num29].noGravity = true;
                return num29;
            }
            if (tileCache.type == 323)
            {
                int frameY = (int)tileCache.frameY;
                return Dust.NewDust(new Vector2((float)(i * 16 + frameY), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, default(Color), 1f);
            }
            if (tileCache.type == 314)
            {
                int num30 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 213, (float)WorldGen.genRand.Next(-2, 3), (float)WorldGen.genRand.Next(-2, 3), 0, default(Color), 1f);
                Main.dust[num30].noGravity = true;
                Main.dust[num30].fadeIn = Main.dust[num30].scale + 1f + 0.01f * (float)WorldGen.genRand.Next(0, 51);
                Main.dust[num30].noGravity = true;
                return num30;
            }
            if (flag2)
            {
                int num31 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 75, default(Color), 0.75f);
                Main.dust[num31].noLight = true;
                return num31;
            }
            if (tileCache.type == 193 || (tileCache.type == 18 && num == 4) || (tileCache.type == 19 && num == 4))
            {
                return Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 75, new Color(0, 80, 255, 100), 0.75f);
            }
            if (tileCache.type == 197)
            {
                return Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 75, new Color(97, 200, 255, 100), 0.75f);
            }
            if (tileCache.type == 185 && num >= 86 && num <= 91)
            {
                int num32 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 75, default(Color), 0.75f);
                Main.dust[num32].noLight = true;
                return num32;
            }
            if (tileCache.type == 4 && num == 66)
            {
                int num33 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, new Color((float)Main.DiscoR / 255f, (float)Main.DiscoG / 255f, (float)Main.DiscoB / 255f), 1f);
                Main.dust[num33].noGravity = true;
                return num33;
            }
            if (num == 139)
            {
                int num34 = num + Main.rand.Next(4);
                return Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num34, 0f, 0f, 0, default(Color), 1f);
            }
            if (tileCache.type == 722)
            {
                int num35 = Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num35].velocity *= 0.4f;
                return num35;
            }
            return Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, num, 0f, 0f, 0, default(Color), 1f);
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Microsoft.Xna.Framework.MathHelper.Clamp(), Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.ID.TorchID.Dust, Terraria.Main.dust, Terraria.Dust.fadeIn, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, int, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.Dust.noLightEmittance, Terraria.Main.rand, Terraria.Dust.scale, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileMoss, Terraria.Main.tileSolid, Terraria.Main.tileStone, Terraria.Tile.type, and Terraria.Dust.velocity.
Referenced by Terraria.NPC.AI_110_Betsy(), Terraria.Projectile.AI_135_OgreStomp(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.CreateGroundExplosion(), Terraria.Projectile.CreateImpactExplosion(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_EmitParticles(), Terraria.Mount.EmitGolfCartWheelDust(), Terraria.WorldGen.KillTile(), Terraria.Player.MowGrassTile(), Terraria.Player.PlaceThing_TryReplacingTiles(), Terraria.WorldGen.ReplaceTile(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsDownDashExplosion(), Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_DeadCellsFlint(), and Terraria.GameContent.Drawing.ParticleOrchestrator.Spawn_StormLightning().