Terraria Decompiled: Terraria.WorldGen.SaveAndQuit
SaveAndQuit()
static void Terraria.WorldGen.SaveAndQuit (Action callback = null) inline static
Definition at line 2511 of file WorldGen.cs.
        {
            SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
            WorldGen.StopWaterfallAmbienceAudio();
            Main.invasionProgress = -1;
            Main.invasionProgressDisplayLeft = 0;
            Main.invasionProgressAlpha = 0f;
            Main.invasionProgressIcon = 0;
            Main.menuMode = 10;
            Main.gameMenu = true;
            InGameNotificationsTracker.Clear();
            SoundEngine.StopTrackedSounds();
            CaptureInterface.ResetFocus();
            WorldFile.SetTempToOngoing();
            ThreadPool.QueueUserWorkItem(new WaitCallback(WorldGen.SaveAndQuitCallBack), new Tuple<int, Action>(Main.netMode, callback));
        }
References Terraria.UI.InGameNotificationsTracker.Clear(), Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), System.Threading.ThreadPool.QueueUserWorkItem(), Terraria.Graphics.Capture.CaptureInterface.ResetFocus(), Terraria.WorldGen.SaveAndQuitCallBack(), Terraria.IO.WorldFile.SetTempToOngoing(), Terraria.Audio.SoundEngine.StopTrackedSounds(), Terraria.WorldGen.StopWaterfallAmbienceAudio(), and System.Threading.WaitCallback().
Referenced by Terraria.IngameOptions.Draw(), Terraria.Main.OpenPlayerSelect(), and Terraria.Social.WeGame.CoreSocialModule.ProcessRailSystemStateChange().