Terraria Decompiled: Terraria.WorldGen.SolidTileAllowBottomSlope
SolidTileAllowBottomSlope()
static bool Terraria.WorldGen.SolidTileAllowBottomSlope (int i, int j) inline static
Definition at line 70487 of file WorldGen.cs.
        {
            try
            {
                if (!WorldGen.InWorld(i, j, 0))
                {
                    return true;
                }
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    return true;
                }
                if (tile.active() && (Main.tileSolid[(int)tile.type] || Main.tileSolidTop[(int)tile.type]) && (!tile.topSlope() || (TileID.Sets.Platforms[(int)tile.type] && WorldGen.PlatformProperTopFrame(tile.frameX))) && !tile.halfBrick() && !tile.inActive())
                {
                    return true;
                }
            }
            catch
            {
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.PlatformProperTopFrame(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_026(), Terraria.WorldGen.CanGeneratePressurePlateAt(), Terraria.WorldGen.Check1x1(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x4(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.CheckCannon(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.WorldGen.CheckFoodPlatter(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckGolf1x1(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPile(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckRockGolemHead(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckStalactiteEcho(), Terraria.WorldGen.CheckWoman(), Terraria.StrayMethods.CountSandHorizontally(), Terraria.Player.DoBootsEffect_PlaceFlamesOnTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.FirstSolid(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), Terraria.WorldGen.HasValidGroundForChilletEggBelowSpot(), Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), Terraria.WorldGen.mayanTrap(), Terraria.Player.MinionRestTargetAim(), Terraria.Player.PetAnimal(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PlantCheck_CanPlaceHook(), Terraria.WorldGen.PlantSeaOat(), Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.ValidAnchorForMultiDirectionalTile(), and Terraria.WorldGen.ValidateOrAttemptReorientingAnchor().