Terraria Decompiled: Terraria.WorldGen.PlaceSmallPile
PlaceSmallPile()
static bool Terraria.WorldGen.PlaceSmallPile (int i, int j, int pileStyle, int pileSize, ushort type = 185) inline static
Definition at line 45200 of file WorldGen.cs.
        {
            short num = (short)(pileSize * 18);
            short num2 = (short)(pileStyle * 18);
            if (Main.tile[i, j] == null)
            {
                Main.tile[i, j] = new Tile();
            }
            if (Main.tile[i + 1, j] == null)
            {
                Main.tile[i + 1, j] = new Tile();
            }
            if (Main.tile[i, j + 1] == null)
            {
                Main.tile[i, j + 1] = new Tile();
            }
            if (Main.tile[i + 1, j + 1] == null)
            {
                Main.tile[i + 1, j + 1] = new Tile();
            }
            if (Main.tile[i, j].anyLava())
            {
                return false;
            }
            if (pileSize == 1)
            {
                num2 = (short)(pileStyle * 36);
                bool flag = false;
                if (WorldGen.SolidTile2(i, j + 1) && WorldGen.SolidTile2(i + 1, j + 1) && !Main.tile[i, j].active() && !Main.tile[i + 1, j].active())
                {
                    flag = true;
                }
                if (flag && type == 185 && (WorldGen.InvalidTileForPilesOrSpeleothems(i, j + 1) || WorldGen.InvalidTileForPilesOrSpeleothems(i + 1, j + 1)))
                {
                    flag = false;
                }
                if (flag)
                {
                    Main.tile[i, j].active(true);
                    Main.tile[i, j].frameY = num;
                    Main.tile[i, j].frameX = num2;
                    Main.tile[i, j].type = type;
                    Main.tile[i + 1, j].active(true);
                    Main.tile[i + 1, j].frameY = num;
                    Main.tile[i + 1, j].frameX = num2 + 18;
                    Main.tile[i + 1, j].type = type;
                    return true;
                }
            }
            else if (WorldGen.SolidTile2(i, j + 1) && !Main.tile[i, j].active())
            {
                Main.tile[i, j].active(true);
                Main.tile[i, j].frameY = num;
                Main.tile[i, j].frameX = num2;
                Main.tile[i, j].type = type;
                return true;
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.anyLava(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.InvalidTileForPilesOrSpeleothems(), Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.Pyramid(), Terraria.WorldGen.Spread.Spider(), and Terraria.WorldGen.StonePatch().