Terraria Decompiled: Terraria.WorldGen.GERunner
GERunner()
static void Terraria.WorldGen.GERunner (int i, int j, double speedX = 0::0, double speedY = 0::0, bool good = true) inline static
Definition at line 76728 of file WorldGen.cs.
        {
            if (WorldGen.Skyblock.lowTiles)
            {
                return;
            }
            int num = 0;
            for (int k = 20; k < Main.maxTilesX - 20; k++)
            {
                for (int l = 20; l < Main.maxTilesY - 20; l++)
                {
                    if (Main.tile[k, l].active() && Main.tile[k, l].type == 225)
                    {
                        num++;
                    }
                }
            }
            bool flag = false;
            if (num > 200000)
            {
                flag = true;
            }
            int num2 = WorldGen.genRand.Next(200, 250);
            double num3 = (double)Main.maxTilesX / 4200.0;
            num2 = (int)((double)num2 * num3);
            double num4 = (double)num2;
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            vector2D2.Y = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            if (speedX != 0.0 || speedY != 0.0)
            {
                vector2D2.X = speedX;
                vector2D2.Y = speedY;
            }
            bool flag2 = true;
            while (flag2)
            {
                int num5 = (int)(vector2D.X - num4 * 0.5);
                int num6 = (int)(vector2D.X + num4 * 0.5);
                int num7 = (int)(vector2D.Y - num4 * 0.5);
                int num8 = (int)(vector2D.Y + num4 * 0.5);
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesX)
                {
                    num6 = Main.maxTilesX;
                }
                if (num7 < 0)
                {
                    num7 = 0;
                }
                if (num8 > Main.maxTilesY - 5)
                {
                    num8 = Main.maxTilesY - 5;
                }
                for (int m = num5; m < num6; m++)
                {
                    for (int n = num7; n < num8; n++)
                    {
                        if (Math.Abs((double)m - vector2D.X) + Math.Abs((double)n - vector2D.Y) < (double)num2 * 0.5 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.015))
{
                            if (good)
{
                                if (Main.tile[m, n].wall == 63 || Main.tile[m, n].wall == 65 || Main.tile[m, n].wall == 66 || Main.tile[m, n].wall == 68 || Main.tile[m, n].wall == 69 || Main.tile[m, n].wall == 81)
{
                                    Main.tile[m, n].wall = 70;
                                }
                                else if (Main.tile[m, n].wall == 216)
{
                                    Main.tile[m, n].wall = 219;
                                }
                                else if (Main.tile[m, n].wall == 187)
{
                                    Main.tile[m, n].wall = 222;
                                }
                                else if (Main.tile[m, n].wall == 3 || Main.tile[m, n].wall == 83)
{
                                    Main.tile[m, n].wall = 28;
                                }
                                if (flag && Main.tile[m, n].type == 225)
{
                                    Main.tile[m, n].type = 117;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (flag && Main.tile[m, n].type == 230)
{
                                    Main.tile[m, n].type = 402;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 2)
{
                                    Main.tile[m, n].type = 109;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 1 || Main.tile[m, n].type == 25 || Main.tile[m, n].type == 203)
{
                                    Main.tile[m, n].type = 117;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 53 || Main.tile[m, n].type == 123 || Main.tile[m, n].type == 112 || Main.tile[m, n].type == 234)
{
                                    Main.tile[m, n].type = 116;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 661 || Main.tile[m, n].type == 662)
{
                                    Main.tile[m, n].type = 60;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 23 || Main.tile[m, n].type == 199)
{
                                    Main.tile[m, n].type = 109;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 161 || Main.tile[m, n].type == 163 || Main.tile[m, n].type == 200)
{
                                    Main.tile[m, n].type = 164;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 396)
{
                                    Main.tile[m, n].type = 403;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 397)
{
                                    Main.tile[m, n].type = 402;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                            }
                            else if (WorldGen.crimson)
{
                                if (Main.tile[m, n].wall == 63 || Main.tile[m, n].wall == 65 || Main.tile[m, n].wall == 66 || Main.tile[m, n].wall == 68)
{
                                    Main.tile[m, n].wall = 81;
                                }
                                else if (Main.tile[m, n].wall == 216)
{
                                    Main.tile[m, n].wall = 218;
                                }
                                else if (Main.tile[m, n].wall == 187)
{
                                    Main.tile[m, n].wall = 221;
                                }
                                if (flag && Main.tile[m, n].type == 225)
{
                                    Main.tile[m, n].type = 203;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (flag && Main.tile[m, n].type == 230)
{
                                    Main.tile[m, n].type = 399;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 60 || Main.tile[m, n].type == 661)
{
                                    Main.tile[m, n].type = 662;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 2 || Main.tile[m, n].type == 109)
{
                                    Main.tile[m, n].type = 199;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 1 || Main.tile[m, n].type == 117)
{
                                    Main.tile[m, n].type = 203;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 53 || Main.tile[m, n].type == 123 || Main.tile[m, n].type == 116)
{
                                    Main.tile[m, n].type = 234;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 161 || Main.tile[m, n].type == 164)
{
                                    Main.tile[m, n].type = 200;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 396)
{
                                    Main.tile[m, n].type = 401;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 397)
{
                                    Main.tile[m, n].type = 399;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                            }
                            else
{
                                if (Main.tile[m, n].wall == 63 || Main.tile[m, n].wall == 65 || Main.tile[m, n].wall == 66 || Main.tile[m, n].wall == 68)
{
                                    Main.tile[m, n].wall = 69;
                                }
                                else if (Main.tile[m, n].wall == 216)
{
                                    Main.tile[m, n].wall = 217;
                                }
                                else if (Main.tile[m, n].wall == 187)
{
                                    Main.tile[m, n].wall = 220;
                                }
                                if (flag && Main.tile[m, n].type == 225)
{
                                    Main.tile[m, n].type = 25;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (flag && Main.tile[m, n].type == 230)
{
                                    Main.tile[m, n].type = 398;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 60 || Main.tile[m, n].type == 662)
{
                                    Main.tile[m, n].type = 661;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 2 || Main.tile[m, n].type == 109)
{
                                    Main.tile[m, n].type = 23;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 1 || Main.tile[m, n].type == 117)
{
                                    Main.tile[m, n].type = 25;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 53 || Main.tile[m, n].type == 123 || Main.tile[m, n].type == 116)
{
                                    Main.tile[m, n].type = 112;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 161 || Main.tile[m, n].type == 164)
{
                                    Main.tile[m, n].type = 163;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 396)
{
                                    Main.tile[m, n].type = 400;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                                else if (Main.tile[m, n].type == 397)
{
                                    Main.tile[m, n].type = 398;
                                    WorldGen.SquareTileFrame(m, n, true);
                                }
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.X > speedX + 1.0)
                {
                    vector2D2.X = speedX + 1.0;
                }
                if (vector2D2.X < speedX - 1.0)
                {
                    vector2D2.X = speedX - 1.0;
                }
                if (vector2D.X < (double)(-(double)num2) || vector2D.Y < (double)(-(double)num2) || vector2D.X > (double)(Main.maxTilesX + num2) || vector2D.Y > (double)(Main.maxTilesY + num2))
                {
                    flag2 = false;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.crimson, Terraria.WorldGen.genRand, int, Terraria.WorldGen.Skyblock.lowTiles, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.initializeHardMode().