Terraria Decompiled: Terraria.WorldGen.AddLifeCrystal
AddLifeCrystal()
static bool Terraria.WorldGen.AddLifeCrystal (int i, int j) inline static
Definition at line 29294 of file WorldGen.cs.
        {
            int k = j;
            while (k < Main.maxTilesY)
            {
                if (Main.tile[i, k].active() && Main.tileSolid[(int)Main.tile[i, k].type])
                {
                    int num = k - 1;
                    if (Main.tile[i, num - 1].anyLava() || Main.tile[i - 1, num - 1].anyLava())
                    {
                        return false;
                    }
                    if (Main.tile[i, num - 1].anyShimmer())
                    {
                        return false;
                    }
                    if (!WorldGen.EmptyTileCheck(i - 1, i, num - 1, num, -1))
                    {
                        return false;
                    }
                    if (Main.wallDungeon[(int)Main.tile[i, num].wall])
                    {
                        return false;
                    }
                    if (WorldGen.skyblockWorldGen && WorldGen.IsTileNearby(i, num, 12, 50))
                    {
                        return false;
                    }
                    Tile tile = Main.tile[i - 1, num + 1];
                    Tile tile2 = Main.tile[i, num + 1];
                    if (!tile.nactive() || !Main.tileSolid[(int)tile.type])
                    {
                        return false;
                    }
                    if (!tile2.nactive() || !Main.tileSolid[(int)tile2.type])
                    {
                        return false;
                    }
                    if (tile.blockType() != 0)
                    {
                        tile.slope(0);
                        tile.halfBrick(false);
                    }
                    if (tile2.blockType() != 0)
                    {
                        tile2.slope(0);
                        tile2.halfBrick(false);
                    }
                    Main.tile[i - 1, num - 1].active(true);
                    Main.tile[i - 1, num - 1].type = 12;
                    Main.tile[i - 1, num - 1].frameX = 0;
                    Main.tile[i - 1, num - 1].frameY = 0;
                    Main.tile[i, num - 1].active(true);
                    Main.tile[i, num - 1].type = 12;
                    Main.tile[i, num - 1].frameX = 18;
                    Main.tile[i, num - 1].frameY = 0;
                    Main.tile[i - 1, num].active(true);
                    Main.tile[i - 1, num].type = 12;
                    Main.tile[i - 1, num].frameX = 0;
                    Main.tile[i - 1, num].frameY = 18;
                    Main.tile[i, num].active(true);
                    Main.tile[i, num].type = 12;
                    Main.tile[i, num].frameX = 18;
                    Main.tile[i, num].frameY = 18;
                    return true;
                }
                else
                {
                    k++;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.anyLava(), Terraria.Tile.anyShimmer(), Terraria.Tile.blockType(), Terraria.WorldGen.EmptyTileCheck(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.WorldGen.IsTileNearby(), Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.WorldGen.skyblockWorldGen, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.