Terraria Decompiled: Terraria.WorldGen.CheckWeaponsRack
CheckWeaponsRack()
static void Terraria.WorldGen.CheckWeaponsRack (int i, int j) inline static
Definition at line 44764 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int num = j - (int)(Main.tile[i, j].frameY / 18);
            int k = (int)Main.tile[i, j].frameX;
            int num2 = 0;
            while (k >= 5000)
            {
                k -= 5000;
                num2++;
            }
            if (num2 != 0)
            {
                k = (num2 - 1) * 18;
            }
            k %= 54;
            int num3 = i - k / 18;
            bool flag = false;
            for (int l = 0; l < 3; l++)
            {
                for (int m = 0; m < 3; m++)
                {
                    int num4 = num3 + l;
                    int num5 = num + m;
                    int n = (int)Main.tile[num4, num5].frameX;
                    int num6 = 0;
                    while (n >= 5000)
                    {
                        n -= 5000;
                        num6++;
                    }
                    if (num6 != 0)
                    {
                        n = (num6 - 1) * 18;
                    }
                    n %= 54;
                    if (!Main.tile[num4, num5].active() || Main.tile[num4, num5].type != 334 || Main.tile[num4, num5].wall <= 0 || (int)Main.tile[num4, num5].frameY != m * 18 || n != l * 18)
                    {
                        flag = true;
                    }
                }
            }
            if (flag)
            {
                TEWeaponsRack teweaponsRack;
                if (TileEntity.TryGetAt<TEWeaponsRack>(num3, num, out teweaponsRack) && teweaponsRack.item.stack > 0)
                {
                    teweaponsRack.DropItem();
                    if (Main.netMode != 2)
                    {
                        Main.LocalPlayer.InterruptItemUsageIfOverTile(471);
                    }
                }
                WorldGen.destroyObject = true;
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 48, 48, 2699, 1, false, 0, false);
                TileEntityType<TEWeaponsRack>.Kill(num3, num);
                for (int num7 = 0; num7 < 3; num7++)
                {
                    for (int num8 = 0; num8 < 3; num8++)
                    {
                        int num9 = num3 + num7;
                        int num10 = num + num8;
                        if (Main.tile[num9, num10].active() && Main.tile[num9, num10].type == 334)
{
                            WorldGen.KillTile(num9, num10, false, false, false);
                        }
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.Player.InterruptItemUsageIfOverTile(), Terraria.DataStructures.TileEntityType< T >.Kill(), Terraria.WorldGen.KillTile(), Terraria.Main.LocalPlayer, Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrameImportant().