Terraria Decompiled: Terraria.WorldGen.PrepForRegen
PrepForRegen()
static void Terraria.WorldGen.PrepForRegen () inline static
Definition at line 7067 of file WorldGen.cs.
        {
            using (BinaryReader binaryReader = new BinaryReader(File.OpenRead(Main.ActiveWorldFileData.Path)))
            {
                bool[] array;
                int[] array2;
                WorldFile.LoadFileFormatHeader(binaryReader, out array, out array2);
                WorldFile.LoadHeader(binaryReader);
            }
            string text;
            string text2;
            List<string> list;
            WorldFileData.TryApplyingCopiedSeed(Main.ActiveWorldFileData.GetFullSeedText(false), false, out text, out text2, out list);
        }
References Terraria.Main.ActiveWorldFileData, System.array, Terraria.IO.WorldFileData.GetFullSeedText(), System.list, Terraria.IO.WorldFile.LoadFileFormatHeader(), Terraria.IO.WorldFile.LoadHeader(), System.IO.File.OpenRead(), Terraria.IO.FileData.Path, System.text, and Terraria.IO.WorldFileData.TryApplyingCopiedSeed().
Referenced by Terraria.Testing.QuickLoad.JoinWorld.CreateRegenController().