Terraria Decompiled: Terraria.WorldGen.LaunchRocket
LaunchRocket()
static void Terraria.WorldGen.LaunchRocket (int x, int y, bool fromWiring) inline static
Definition at line 61080 of file WorldGen.cs.
        {
            int i = (int)Main.tile[x, y].frameY;
            int num = 0;
            while (i >= 40)
            {
                i -= 40;
                num++;
            }
            if (i == 18)
            {
                y--;
            }
            Vector2 vector = new Vector2((float)(x * 16 + 8), (float)(y * 16 + 4));
            int num2 = 167 + num;
            int num3 = 150;
            int num4 = 7;
            int num5 = Projectile.NewProjectile(WorldGen.GetProjectileSource_PlayerOrWires(x, y, fromWiring, Main.LocalPlayer), vector.X, vector.Y + 2f, 0f, -8f, num2, num3, (float)num4, Main.myPlayer, 0f, 0f, 0f, null);
            Main.projectile[num5].originatedFromActivableTile = true;
            Main.tile[x, y].active(false);
            Main.tile[x, y + 1].active(false);
            NetMessage.SendTileSquare(-1, x, y, 1, 2, TileChangeType.None);
        }
References Terraria.Tile.active(), Terraria.Tile.frameY, Terraria.WorldGen.GetProjectileSource_PlayerOrWires(), int, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Projectile.NewProjectile(), Terraria.Projectile.originatedFromActivableTile, Terraria.Main.projectile, Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Wiring.HitWireSingle(), and Terraria.Player.TileInteractionsUse().