Terraria Decompiled: Terraria.WorldGen.NoNearbyAbigailsFlower
NoNearbyAbigailsFlower()
static bool Terraria.WorldGen.NoNearbyAbigailsFlower (int i, int j) inline static private
Definition at line 73550 of file WorldGen.cs.
        {
            int num = Utils.Clamp<int>(i - 120, 10, Main.maxTilesX - 1 - 10);
            int num2 = Utils.Clamp<int>(i + 120, 10, Main.maxTilesX - 1 - 10);
            int num3 = Utils.Clamp<int>(j - 120, 10, Main.maxTilesY - 1 - 10);
            int num4 = Utils.Clamp<int>(j + 120, 10, Main.maxTilesY - 1 - 10);
            for (int k = num; k <= num2; k++)
            {
                for (int l = num3; l <= num4; l++)
                {
                    Tile tile = Main.tile[k, l];
                    if (tile.active() && tile.type == 624)
                    {
                        return false;
                    }
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.TryGrowingAbigailsFlower().