Terraria Decompiled: Terraria.WorldGen.EmptyTileCheck
EmptyTileCheck()
static bool Terraria.WorldGen.EmptyTileCheck (int startX, int endX, int startY, int endY, int ignoreID = -1) inline static
Definition at line 28759 of file WorldGen.cs.
        {
            if (startX < 0)
            {
                return false;
            }
            if (endX >= Main.maxTilesX)
            {
                return false;
            }
            if (startY < 0)
            {
                return false;
            }
            if (endY >= Main.maxTilesY)
            {
                return false;
            }
            bool flag = false;
            if (ignoreID != -1 && TileID.Sets.CommonSapling[ignoreID])
            {
                flag = true;
            }
            for (int i = startX; i < endX + 1; i++)
            {
                for (int j = startY; j < endY + 1; j++)
                {
                    if (Main.tile[i, j].active())
                    {
                        if (ignoreID == -1)
{
                            return false;
                        }
                        if (ignoreID == 11)
{
                            ushort num = Main.tile[i, j].type;
                            if (num != 11)
{
                                return false;
                            }
                        }
                        else if (ignoreID == 71)
{
                            ushort num = Main.tile[i, j].type;
                            if (num != 71)
{
                                return false;
                            }
                        }
                        else if (flag && !TileID.Sets.CommonSapling[(int)Main.tile[i, j].type])
{
                            ushort num = Main.tile[i, j].type;
                            if (num <= 113)
{
                                if (num <= 62)
{
                                    if (num <= 24)
{
                                        if (num == 3 || num == 24)
{
                                            goto IL_01AD;
                                        }
                                    }
                                    else if (num == 32 || num - 61 <= 1)
{
                                        goto IL_01AD;
                                    }
                                }
                                else if (num <= 84)
{
                                    switch (num)
{
                                    case 69:
                                    case 71:
                                    case 73:
                                    case 74:
                                        goto IL_01AD;
                                    case 70:
                                    case 72:
                                        break;
                                    default:
                                        if (num - 82 <= 2)
{
                                            goto IL_01AD;
                                        }
                                        break;
                                    }
                                }
                                else if (num == 110 || num == 113)
{
                                    goto IL_01AD;
                                }
                            }
                            else if (num <= 352)
{
                                if (num <= 201)
{
                                    if (num == 184 || num == 201)
{
                                        goto IL_01AD;
                                    }
                                }
                                else if (num == 233 || num == 352)
{
                                    goto IL_01AD;
                                }
                            }
                            else if (num <= 530)
{
                                if (num == 485 || num - 529 <= 1)
{
                                    goto IL_01AD;
                                }
                            }
                            else if (num == 637 || num == 655)
{
                                goto IL_01AD;
                            }
                            return false;
                        }
                    }
                    IL_01AD:;
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.CommonSapling, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddManaCrystal(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), and Terraria.GameContent.SmartCursorHelper.Step_GemCorns().