Terraria Decompiled: Terraria.WorldGen.Place2x2Style
Place2x2Style()
static void Terraria.WorldGen.Place2x2Style (int x, int y, ushort type, int style = 0) inline static
Definition at line 50714 of file WorldGen.cs.
        {
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            short num = 0;
            if (type == 254)
            {
                num = (short)(x % 12 / 2);
                num *= 36;
            }
            bool flag = true;
            for (int i = x - 1; i < x + 1; i++)
            {
                for (int j = y - 1; j < y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active())
                    {
                        flag = false;
                    }
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (!WorldGen.SolidTile(i, y + 1, false))
                {
                    flag = false;
                }
                if (type == 254 && Main.tile[i, y + 1].type != 2 && Main.tile[i, y + 1].type != 477 && Main.tile[i, y + 1].type != 492 && Main.tile[i, y + 1].type != 109)
                {
                    flag = false;
                }
            }
            if (flag)
            {
                short num2 = (short)(36 * style);
                Main.tile[x - 1, y - 1].active(true);
                Main.tile[x - 1, y - 1].frameY = num;
                Main.tile[x - 1, y - 1].frameX = num2;
                Main.tile[x - 1, y - 1].type = type;
                Main.tile[x, y - 1].active(true);
                Main.tile[x, y - 1].frameY = num;
                Main.tile[x, y - 1].frameX = num2 + 18;
                Main.tile[x, y - 1].type = type;
                Main.tile[x - 1, y].active(true);
                Main.tile[x - 1, y].frameY = num + 18;
                Main.tile[x - 1, y].frameX = num2;
                Main.tile[x - 1, y].type = type;
                Main.tile[x, y].active(true);
                Main.tile[x, y].frameY = num + 18;
                Main.tile[x, y].frameX = num2 + 18;
                Main.tile[x, y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().