Terraria Decompiled: Terraria.WorldGen.TryGrowingTreeByType
TryGrowingTreeByType()
static bool Terraria.WorldGen.TryGrowingTreeByType (int treeTileType, int checkedX, int checkedY, int treeHeightAddon = 0, bool ignoreWalls = false) inline static
Definition at line 27602 of file WorldGen.cs.
        {
            bool flag = false;
            if (treeTileType <= 323)
            {
                if (treeTileType != 5)
                {
                    if (treeTileType == 323)
                    {
                        flag = WorldGen.GrowPalmTree(checkedX, checkedY, treeHeightAddon, ignoreWalls);
                    }
                }
                else
                {
                    flag = WorldGen.GrowTree(checkedX, checkedY, treeHeightAddon, ignoreWalls);
                }
            }
            else
            {
                switch (treeTileType)
                {
                case 583:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Topaz, treeHeightAddon, ignoreWalls);
                    break;
                case 584:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Amethyst, treeHeightAddon, ignoreWalls);
                    break;
                case 585:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Sapphire, treeHeightAddon, ignoreWalls);
                    break;
                case 586:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Emerald, treeHeightAddon, ignoreWalls);
                    break;
                case 587:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Ruby, treeHeightAddon, ignoreWalls);
                    break;
                case 588:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Diamond, treeHeightAddon, ignoreWalls);
                    break;
                case 589:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.GemTree_Amber, treeHeightAddon, ignoreWalls);
                    break;
                case 590:
                case 591:
                case 592:
                case 593:
                case 594:
                case 595:
                    break;
                case 596:
                    flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.VanityTree_Sakura, treeHeightAddon, ignoreWalls);
                    break;
                default:
                    if (treeTileType != 616)
                    {
                        if (treeTileType == 634)
{
                            flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.Tree_Ash, treeHeightAddon, ignoreWalls);
                        }
                    }
                    else
                    {
                        flag = WorldGen.GrowTreeWithSettings(checkedX, checkedY, WorldGen.GrowTreeSettings.Profiles.VanityTree_Willow, treeHeightAddon, ignoreWalls);
                    }
                    break;
                }
            }
            return flag;
        }
References Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Amber, Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Amethyst, Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Diamond, Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Emerald, Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Ruby, Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Sapphire, Terraria.WorldGen.GrowTreeSettings.Profiles.GemTree_Topaz, Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowTreeSettings.Profiles.Tree_Ash, Terraria.WorldGen.GrowTreeSettings.Profiles.VanityTree_Sakura, and Terraria.WorldGen.GrowTreeSettings.Profiles.VanityTree_Willow.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.WorldGen.AddTrees(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance_TreeOnPillar(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.GenerateUnderworldStartingMound(), Terraria.WorldGen.IslandHouse(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_TreeOnPillar(), and Terraria.WorldGen.UpdateWorld_GrassGrowth().