Terraria Decompiled: Terraria.WorldGen.Check3x2Wall
Check3x2Wall()
static void Terraria.WorldGen.Check3x2Wall (int x, int y) inline static
Definition at line 43067 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int type = (int)Main.tile[x, y].type;
            int num = 0;
            int i = (int)(Main.tile[x, y].frameY / 18);
            while (i >= 2)
            {
                i -= 2;
                num++;
            }
            int num2 = y - i;
            int num3 = x - (int)(Main.tile[x, y].frameX / 18);
            i = num * 36;
            for (int j = num3; j < num3 + 3; j++)
            {
                for (int k = num2; k < num2 + 2; k++)
                {
                    if ((int)Main.tile[j, k].type != type || !Main.tile[j, k].active() || Main.tile[j, k].wall <= 0 || (int)Main.tile[j, k].frameY != i + (k - num2) * 18 || (int)Main.tile[j, k].frameX != (j - num3) * 18)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int l = num3; l < num3 + 3; l++)
                {
                    for (int m = num2; m < num2 + 2; m++)
                    {
                        if ((int)Main.tile[l, m].type == type && Main.tile[l, m].active())
{
                            WorldGen.KillTile(l, m, false, false, false);
                        }
                    }
                }
                if (type == 246)
                {
                    if (num == 16)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1541, 1, false, 0, false);
                    }
                    else if (num == 17)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1542, 1, false, 0, false);
                    }
                    else if (num == 18)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1908, 1, false, 0, false);
                    }
                    else if (num == 19)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4661, 1, false, 0, false);
                    }
                    else if (num == 20)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4729, 1, false, 0, false);
                    }
                    else if (num >= 21 && num <= 36)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5258 + num - 21, 1, false, 0, false);
                    }
                    else
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1479 + num, 1, false, 0, false);
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrameImportant().