Terraria Decompiled: Terraria.WorldGen.ShellPile
ShellPile()
static bool Terraria.WorldGen.ShellPile (int X, int Y) inline static
Definition at line 6324 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(X, Y, 0))
            {
                return false;
            }
            int num = Y;
            while (!WorldGen.SolidTile(X, num, false))
            {
                num++;
                if ((double)num > Main.worldSurface)
                {
                    return false;
                }
            }
            if (Main.tile[X, num].type != 53)
            {
                return false;
            }
            if (Main.tile[X, num].wall > 0)
            {
                return false;
            }
            num--;
            Vector2D vector2D;
            vector2D..ctor((double)X, (double)num);
            Vector2D vector2D2;
            vector2D2.X = WorldGen.genRand.NextDouble() * 0.6 - 0.3;
            vector2D2.Y = WorldGen.genRand.NextDouble() * 0.5 + 0.5;
            double num2 = (double)WorldGen.genRand.Next(2, 4);
            if (WorldGen.genRand.Next(10) == 0)
            {
                num2 += 1.0;
            }
            int i = WorldGen.genRand.Next(3, 6);
            while (i > 0)
            {
                i--;
                int num3 = X - (int)num2 * 4;
                while ((double)num3 <= (double)X + num2 * 4.0)
                {
                    int num4 = num + (int)num2 * 4;
                    while ((double)num4 > (double)num - num2 * 4.0)
                    {
                        double num5 = num2 * (double)WorldGen.genRand.Next(70, 91) * 0.01;
                        Vector2D vector2D3 = vector2D - new Vector2D((double)num3, (double)num4);
                        vector2D3.X *= 0.6;
                        if (vector2D3.Length() < num5)
{
                            if (num4 <= num + 1 || WorldGen.genRand.Next(6) == 0)
{
                                Main.tile[num3, num4].type = 495;
                                Main.tile[num3, num4].active(true);
                                Main.tile[num3, num4].halfBrick(false);
                                Main.tile[num3, num4].slope(0);
                                if (!Main.tile[num3, num4 + 1].active())
{
                                    Main.tile[num3, num4 + 1].type = 495;
                                    Main.tile[num3, num4 + 1].active(true);
                                    Main.tile[num3, num4 + 1].halfBrick(false);
                                    Main.tile[num3, num4 + 1].slope(0);
                                    if (!Main.tile[num3, num4 + 2].active())
{
                                        Main.tile[num3, num4 + 2].type = 53;
                                        Main.tile[num3, num4 + 2].active(true);
                                        Main.tile[num3, num4 + 2].halfBrick(false);
                                        Main.tile[num3, num4 + 2].slope(0);
                                        if (!Main.tile[num3, num4 + 3].active())
{
                                            Main.tile[num3, num4 + 3].type = 397;
                                            Main.tile[num3, num4 + 3].active(true);
                                            Main.tile[num3, num4 + 3].halfBrick(false);
                                            Main.tile[num3, num4 + 3].slope(0);
                                        }
                                    }
                                }
                                if (!WorldGen.isGeneratingOrLoadingWorld)
{
                                    WorldGen.SquareTileFrame(num3, num4, true);
                                }
                            }
                            else if (Main.tile[num3, num4].type != 495)
{
                                Main.tile[num3, num4].active(true);
                                Main.tile[num3, num4].halfBrick(false);
                                Main.tile[num3, num4].slope(0);
                                Main.tile[num3, num4].type = 53;
                                if (!WorldGen.isGeneratingOrLoadingWorld)
{
                                    WorldGen.SquareTileFrame(num3, num4, true);
                                }
                            }
                        }
                        num4--;
                    }
                    num3++;
                }
                vector2D += vector2D2;
                vector2D2.X += WorldGen.genRand.NextDouble() * 0.2 - 0.1;
                vector2D2.Y += WorldGen.genRand.NextDouble() * 0.2 - 0.1;
                Utils.Clamp<double>(vector2D2.X, -0.3, 0.3);
                Utils.Clamp<double>(vector2D2.Y, 0.5, 1.0);
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.isGeneratingOrLoadingWorld, ReLogic.Utilities.Vector2D.Length(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, System.X, ReLogic.Utilities.Vector2D.X, System.Y, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().