Terraria Decompiled: Terraria.WorldGen.SpawnGraveyardBiome
SpawnGraveyardBiome()
static void Terraria.WorldGen.SpawnGraveyardBiome (int X, int Y) inline static
Definition at line 22054 of file WorldGen.cs.
        {
            int num = 40;
            int num2 = 3;
            int num3 = 5000;
            while (Main.tile[X, Y].active())
            {
                Y--;
                if (Y < 100)
                {
                    return;
                }
            }
            Y++;
            while (!Main.tile[X, Y].active())
            {
                Y++;
                if (Y > Main.UnderworldLayer - 100)
                {
                    return;
                }
            }
            for (int i = X - num; i <= X + num; i++)
            {
                for (int j = Y - num; j <= Y + num; j++)
                {
                    if (Main.tile[i, j].active() && (Main.tile[i, j].anyShimmer() || Main.tile[i, j].type == 25 || Main.tile[i, j].type == 203 || Main.tile[i, j].type == 53 || Main.tile[i, j].type == 191 || Main.tile[i, j].type == 383 || Main.tileDungeon[(int)Main.tile[i, j].type] || Main.tile[i, j].type == 226 || Main.tile[i, j].type == 225 || Main.tile[i, j].type == 367 || Main.tile[i, j].type == 368 || Main.tile[i, j].type == 57 || Main.tile[i, j].type == 70 || Main.tile[i, j].type == 189))
                    {
                        return;
                    }
                }
            }
            for (int k = 0; k < num3; k++)
            {
                int num4 = X + WorldGen.genRand.Next(-num, num + 1);
                int num5 = Y + WorldGen.genRand.Next(-num, num + 1);
                if (WorldGen.InWorld(num4, num5, 50) && !Main.tile[num4, num5].active())
                {
                    while (!Main.tile[num4, num5].active())
                    {
                        num5++;
                        if (!WorldGen.InWorld(num4, num5, 55))
{
                            num5 = Main.maxTilesY - 50;
                            break;
                        }
                    }
                    num5--;
                    if (!Main.tile[num4 + 1, num5].active() && !WorldGen.IsTileNearby(num4, num5, 85, num2) && Main.tile[num4, num5].liquid == 0 && Main.tile[num4, num5 + 1].active() && Main.tile[num4 + 1, num5 + 1].active() && Main.tileSolid[(int)Main.tile[num4, num5 + 1].type] && Main.tileSolid[(int)Main.tile[num4 + 1, num5 + 1].type])
                    {
                        Main.tile[num4, num5 + 1].slope(0);
                        Main.tile[num4, num5 + 1].halfBrick(false);
                        Main.tile[num4 + 1, num5 + 1].slope(0);
                        Main.tile[num4 + 1, num5 + 1].halfBrick(false);
                        if (WorldGen.PlaceTile(num4, num5, 85, true, false, -1, WorldGen.genRand.Next(6)))
{
                            int num6 = Sign.ReadSign(num4, num5, true);
                            if (num6 >= 0)
{
                                Sign.TextSign(num6, Language.RandomFromCategory("Epitaph", WorldGen.genRand).Value);
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.anyShimmer(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTileNearby(), Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Localization.Language.RandomFromCategory(), Terraria.Sign.ReadSign(), Terraria.Tile.slope(), Terraria.Sign.TextSign(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Localization.LocalizedText.Value, System.X, and System.Y.
Referenced by Terraria.WorldGen.SpawnGraveyardBiomesEverywhere().