Terraria Decompiled: Terraria.WorldGen.FixHeart
FixHeart()
static void Terraria.WorldGen.FixHeart (int i, int j) inline static
Definition at line 51107 of file WorldGen.cs.
        {
            if (i < Main.offLimitBorderTiles || i >= Main.maxTilesX - Main.offLimitBorderTiles || j < Main.offLimitBorderTiles || j >= Main.maxTilesY - Main.offLimitBorderTiles)
            {
                WorldGen.DestroyHeart(i, j);
                return;
            }
            Tile tile = Main.tile[i, j + 2];
            Tile tile2 = Main.tile[i + 1, j + 2];
            if (tile.active() && !Main.tileSolid[(int)tile.type] && Main.tileCut[(int)tile.type])
            {
                WorldGen.KillTile(i, j + 2, false, false, false);
            }
            if (tile2.active() && !Main.tileSolid[(int)tile2.type] && Main.tileCut[(int)tile2.type])
            {
                WorldGen.KillTile(i + 1, j + 2, false, false, false);
            }
            if (!tile.active())
            {
                if (!tile2.active())
                {
                    WorldGen.DestroyHeart(i, j);
                    return;
                }
                if (Main.tileSolid[(int)tile2.type])
                {
                    tile.type = tile2.type;
                    tile.active(true);
                }
            }
            if (!tile2.active() && Main.tileSolid[(int)tile.type])
            {
                tile2.type = tile.type;
                tile2.active(true);
            }
            if (!tile.nactive() || !Main.tileSolid[(int)tile.type] || !tile2.nactive() || !Main.tileSolid[(int)tile2.type])
            {
                WorldGen.DestroyHeart(i, j);
                return;
            }
            if (tile.blockType() != 0)
            {
                tile.slope(0);
                tile.halfBrick(false);
            }
            if (tile2.blockType() != 0)
            {
                tile2.slope(0);
                tile2.halfBrick(false);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.blockType(), Terraria.WorldGen.DestroyHeart(), Terraria.Tile.halfBrick(), Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.offLimitBorderTiles, Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileCut, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.FixHearts().