Terraria Decompiled: Terraria.WorldGen.PlaceTile
PlaceTile()
static bool Terraria.WorldGen.PlaceTile (int i, int j, int Type, bool mute = false, bool forced = false, int plr = -1, int style = 0) inline static
Definition at line 58061 of file WorldGen.cs.
        {
            int num = Type;
            if (WorldGen.isGeneratingOrLoadingWorld && Main.tile[i, j].active() && Main.tile[i, j].type == 488)
            {
                return false;
            }
            if (num >= (int)TileID.Count)
            {
                return false;
            }
            bool flag = false;
            if (i >= 0 && j >= 0 && i < Main.maxTilesX && j < Main.maxTilesY)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    tile = new Tile();
                    Main.tile[i, j] = tile;
                }
                if (tile.active())
                {
                    if (num == 23 && tile.type == 59)
                    {
                        num = 661;
                    }
                    if (num == 199 && tile.type == 59)
                    {
                        num = 662;
                    }
                }
                if (forced || Collision.EmptyTile(i, j, false) || !Main.tileSolid[num] || (num == 23 && tile.type == 0 && tile.active()) || (num == 199 && tile.type == 0 && tile.active()) || (num == 2 && tile.type == 0 && tile.active()) || (num == 109 && tile.type == 0 && tile.active()) || (num == 60 && tile.type == 59 && tile.active()) || (num == 661 && tile.type == 59 && tile.active()) || (num == 662 && tile.type == 59 && tile.active()) || (num == 70 && tile.type == 59 && tile.active()) || (num == 633 && tile.type == 57 && tile.active()) || (Main.tileMoss[num] && (tile.type == 1 || tile.type == 38) && tile.active()))
                {
                    if (num == 23 && (tile.type != 0 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 199 && (tile.type != 0 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 2 && (tile.type != 0 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 109 && (tile.type != 0 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 60 && (tile.type != 59 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 661 && (tile.type != 59 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 662 && (tile.type != 59 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 70 && (tile.type != 59 || !tile.active()))
                    {
                        return false;
                    }
                    if (num == 633 && (tile.type != 57 || !tile.active()))
                    {
                        return false;
                    }
                    if (Main.tileMoss[num])
                    {
                        if ((tile.type != 1 && tile.type != 38) || !tile.active())
{
                            return false;
                        }
                        if (tile.type == 38)
{
                            if (num == 381)
{
                                num = 517;
                            }
                            else if (num == 534)
{
                                num = 535;
                            }
                            else if (num == 536)
{
                                num = 537;
                            }
                            else if (num == 539)
{
                                num = 540;
                            }
                            else if (num == 625)
{
                                num = 626;
                            }
                            else if (num == 627)
{
                                num = 628;
                            }
                            else
{
                                num = 512 + num - 179;
                            }
                        }
                    }
                    if (num == 81)
                    {
                        if (Main.tile[i, j - 1] == null)
{
                            Main.tile[i, j - 1] = new Tile();
                        }
                        if (Main.tile[i, j + 1] == null)
{
                            Main.tile[i, j + 1] = new Tile();
                        }
                        if (Main.tile[i, j - 1].active())
{
                            return false;
                        }
                        if (!Main.tile[i, j + 1].active() || !Main.tileSolid[(int)Main.tile[i, j + 1].type] || Main.tile[i, j + 1].halfBrick() || Main.tile[i, j + 1].slope() != 0)
{
                            return false;
                        }
                    }
                    if (TileID.Sets.IsADripTile[num] && (Main.tile[i, j - 1] == null || Main.tile[i, j - 1].bottomSlope()))
                    {
                        return false;
                    }
                    if (tile.liquid > 0 || tile.checkingLiquid())
                    {
                        if (TileID.Sets.Torches[num])
{
                            if (num == 4 && style != 8 && style != 11 && style != 17)
{
                                return false;
                            }
                            TileObjectData tileData = TileObjectData.GetTileData(num, style, 0);
                            if (tileData != null && tileData.WaterPlacement != LiquidPlacement.Allowed)
{
                                return false;
                            }
                        }
                        else if (num == 3 || num == 20 || num == 24 || num == 27 || num == 32 || num == 51 || num == 69 || num == 72 || num == 201 || num == 352 || num == 529 || num == 624 || num == 700 || num == 637 || num == 656 || num == 701 || num == 697)
{
                            return false;
                        }
                    }
                    if (!tile.active())
                    {
                        tile.Clear(TileDataType.Tile | TileDataType.TilePaint | TileDataType.Slope);
                    }
                    else if (TileID.Sets.ResetsHalfBrickPlacementAttempt[num] && (!tile.active() || !Main.tileFrameImportant[(int)tile.type]))
                    {
                        tile.halfBrick(false);
                        tile.frameY = 0;
                        tile.frameX = 0;
                    }
                    if (num == 624 || num == 700)
                    {
                        if ((!tile.active() || Main.tileCut[(int)tile.type] || TileID.Sets.BreakableWhenPlacing[(int)tile.type]) && WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(i, j))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.halfBrick(false);
                            tile.slope(0);
                            tile.frameX = 0;
                            tile.frameY = 0;
                        }
                    }
                    else if (num == 656 || num == 701)
                    {
                        if ((!tile.active() || Main.tileCut[(int)tile.type] || TileID.Sets.BreakableWhenPlacing[(int)tile.type]) && WorldGen.HasValidGroundForGlowTulipBelowSpot(i, j))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.halfBrick(false);
                            tile.slope(0);
                            tile.frameX = 0;
                            tile.frameY = 0;
                        }
                    }
                    else if (num == 3 || num == 24 || num == 110 || num == 201 || num == 637)
                    {
                        if (WorldGen.IsFitToPlaceFlowerIn(i, j, num))
{
                            if (num == 24 && WorldGen.genRand.Next(13) == 0)
{
                                tile.active(true);
                                tile.type = 32;
                                WorldGen.SquareTileFrame(i, j, true);
                            }
                            else if (num == 201 && WorldGen.genRand.Next(13) == 0)
{
                                tile.active(true);
                                tile.type = 352;
                                WorldGen.SquareTileFrame(i, j, true);
                            }
                            else if (Main.tile[i, j + 1].type == 78 || Main.tile[i, j + 1].type == 380 || Main.tile[i, j + 1].type == 579)
{
                                tile.active(true);
                                tile.type = (ushort)num;
                                int num2 = WorldGen.genRand.NextFromList(new int[]
{
                                    6, 7, 9, 10, 11, 12, 13, 14, 15, 16,
                                    17, 18, 19, 20, 21, 24, 27, 30, 33, 36,
                                    39, 42
                                });
                                if (num2 <= 30)
{
                                    if (num2 <= 24)
{
                                        if (num2 != 21 && num2 != 24)
{
                                            goto IL_07B4;
                                        }
                                    }
                                    else if (num2 != 27 && num2 != 30)
{
                                        goto IL_07B4;
                                    }
                                }
                                else if (num2 <= 36)
{
                                    if (num2 != 33 && num2 != 36)
{
                                        goto IL_07B4;
                                    }
                                }
                                else if (num2 != 39 && num2 != 42)
{
                                    goto IL_07B4;
                                }
                                num2 += WorldGen.genRand.Next(3);
                                IL_07B4:
                                tile.frameX = (short)(num2 * 18);
                            }
                            else if (tile.wall >= 0 && tile.wall < WallID.Count && WallID.Sets.AllowsPlantsToGrow[(int)tile.wall] && Main.tile[i, j + 1].wall >= 0 && Main.tile[i, j + 1].wall < WallID.Count && WallID.Sets.AllowsPlantsToGrow[(int)Main.tile[i, j + 1].wall])
{
                                if (WorldGen.genRand.Next(50) == 0 || ((num == 24 || num == 201) && WorldGen.genRand.Next(40) == 0))
{
                                    tile.active(true);
                                    tile.type = (ushort)num;
                                    if (num == 201)
{
                                        tile.frameX = 270;
                                    }
                                    else
{
                                        tile.frameX = 144;
                                    }
                                }
                                else if (WorldGen.genRand.Next(35) == 0 || (Main.tile[i, j].wall >= 63 && Main.tile[i, j].wall <= 70))
{
                                    tile.active(true);
                                    tile.type = (ushort)num;
                                    int num3 = WorldGen.genRand.NextFromList(new int[]
{
                                        6, 7, 9, 10, 11, 12, 13, 14, 15, 16,
                                        17, 18, 19, 20
                                    });
                                    if (num == 201)
{
                                        num3 = WorldGen.genRand.NextFromList(new int[]
{
                                            6, 7, 8, 9, 10, 11, 12, 13, 14, 16,
                                            17, 18, 19, 20, 21, 22
                                        });
                                    }
                                    if (num == 637)
{
                                        num3 = WorldGen.genRand.NextFromList(new int[] { 6, 7, 8, 9, 10 });
                                    }
                                    tile.frameX = (short)(num3 * 18);
                                }
                                else
{
                                    tile.active(true);
                                    tile.type = (ushort)num;
                                    tile.frameX = (short)(WorldGen.genRand.Next(6) * 18);
                                }
                            }
                        }
                    }
                    else if (num == 61)
                    {
                        if (j + 1 < Main.maxTilesY && Main.tile[i, j + 1].active() && Main.tile[i, j + 1].slope() == 0 && !Main.tile[i, j + 1].halfBrick() && (Main.tile[i, j + 1].type == 60 || Main.tile[i, j + 1].type == 226))
{
                            bool flag2 = Main.tile[i, j + 1].type == 226;
                            bool flag3 = (double)j > Main.rockLayer || Main.remixWorld || WorldGen.remixWorldGen;
                            if (flag2)
{
                                flag3 = false;
                            }
                            if (WorldGen.genRand.Next(16) == 0 && (double)j > Main.worldSurface && !flag2)
{
                                tile.active(true);
                                tile.type = 69;
                                WorldGen.SquareTileFrame(i, j, true);
                            }
                            else if (WorldGen.genRand.Next(60) == 0 && flag3)
{
                                tile.active(true);
                                tile.type = (ushort)num;
                                tile.frameX = 144;
                            }
                            else if (WorldGen.genRand.Next(230) == 0 && flag3)
{
                                tile.active(true);
                                tile.type = (ushort)num;
                                tile.frameX = 162;
                            }
                            else if (WorldGen.genRand.Next(15) == 0 && !flag2)
{
                                tile.active(true);
                                tile.type = (ushort)num;
                                if (WorldGen.genRand.Next(3) != 0)
{
                                    tile.frameX = (short)(WorldGen.genRand.Next(2) * 18 + 108);
                                }
                                else
{
                                    tile.frameX = (short)(WorldGen.genRand.Next(13) * 18 + 180);
                                }
                            }
                            else
{
                                tile.active(true);
                                tile.type = (ushort)num;
                                tile.frameX = (short)(WorldGen.genRand.Next(6) * 18);
                            }
                        }
                    }
                    else if (num == 518)
                    {
                        WorldGen.PlaceLilyPad(i, j);
                    }
                    else if (num == 519)
                    {
                        WorldGen.PlaceCatTail(i, j);
                    }
                    else if (num == 529)
                    {
                        WorldGen.PlantSeaOat(i, j);
                    }
                    else if (num == 571)
                    {
                        WorldGen.PlaceBamboo(i, j);
                    }
                    else if (num == 549)
                    {
                        WorldGen.PlaceUnderwaterPlant(549, i, j);
                    }
                    else if (num == 71)
                    {
                        if (j + 1 < Main.maxTilesY && Main.tile[i, j + 1].active() && Main.tile[i, j + 1].slope() == 0 && !Main.tile[i, j + 1].halfBrick() && Main.tile[i, j + 1].type == 70)
{
                            Point point = new Point(-1, -1);
                            if ((double)j > Main.worldSurface)
{
                                point = WorldGen.PlaceCatTail(i, j);
                            }
                            if (WorldGen.InWorld(point.X, point.Y, 0))
{
                                if (WorldGen.isGeneratingOrLoadingWorld)
{
                                    int num4 = WorldGen.genRand.Next(14);
                                    for (int k = 0; k < num4; k++)
{
                                        WorldGen.GrowCatTail(point.X, point.Y);
                                    }
                                    WorldGen.SquareTileFrame(point.X, point.Y, true);
                                }
                            }
                            else
{
                                tile.active(true);
                                tile.type = (ushort)num;
                                tile.frameX = (short)(WorldGen.genRand.Next(5) * 18);
                            }
                        }
                    }
                    else if (num == 129)
                    {
                        int num5 = 0;
                        if (WorldGen.CheckAndAdjustMultiDirectionalTile(i, j, num, out num5))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.frameX = (short)(style * 18);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 178)
                    {
                        int num6 = 0;
                        if (WorldGen.CheckAndAdjustMultiDirectionalTile(i, j, num, out num6))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.frameX = (short)(style * 18);
                            tile.frameY = (short)(WorldGen.genRand.Next(3) * 18);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 184)
                    {
                        if ((Main.tileMoss[(int)Main.tile[i - 1, j].type] && WorldGen.SolidTile(i - 1, j, false)) || (Main.tileMoss[(int)Main.tile[i + 1, j].type] && WorldGen.SolidTile(i + 1, j, false)) || (Main.tileMoss[(int)Main.tile[i, j - 1].type] && WorldGen.SolidTile(i, j - 1, false)) || (Main.tileMoss[(int)Main.tile[i, j + 1].type] && WorldGen.SolidTile(i, j + 1, false)))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.frameX = (short)(style * 18);
                            tile.frameY = (short)(WorldGen.genRand.Next(3) * 18);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                        if ((TileID.Sets.tileMossBrick[(int)Main.tile[i - 1, j].type] && WorldGen.SolidTile(i - 1, j, false)) || (TileID.Sets.tileMossBrick[(int)Main.tile[i + 1, j].type] && WorldGen.SolidTile(i + 1, j, false)) || (TileID.Sets.tileMossBrick[(int)Main.tile[i, j - 1].type] && WorldGen.SolidTile(i, j - 1, false)) || (TileID.Sets.tileMossBrick[(int)Main.tile[i, j + 1].type] && WorldGen.SolidTile(i, j + 1, false)))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.frameX = (short)(style * 18);
                            tile.frameY = (short)(WorldGen.genRand.Next(3) * 18);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 485)
                    {
                        WorldGen.PlaceObject(i, j, num, mute, style, 0, -1, -1);
                    }
                    else if (num == 171)
                    {
                        WorldGen.PlaceXmasTree(i, j, 171);
                    }
                    else if (num == 254)
                    {
                        WorldGen.Place2x2Style(i, j, (ushort)num, style);
                    }
                    else if (num == 335 || num == 564 || num == 594)
                    {
                        WorldGen.Place2x2(i, j, (ushort)num, 0);
                    }
                    else if (num == 654 || num == 319 || num == 132 || num == 484 || num == 138 || num == 664 || num == 711 || num == 712 || num == 142 || num == 143 || num == 282 || (num >= 288 && num <= 295) || (num >= 316 && num <= 318) || num == 713 || num == 714 || num == 715 || num == 716)
                    {
                        WorldGen.Place2x2(i, j, (ushort)num, 0);
                    }
                    else if (num == 411)
                    {
                        WorldGen.Place2x2(i, j, (ushort)num, 0);
                    }
                    else if (num == 457)
                    {
                        WorldGen.Place2x2Horizontal(i, j, 457, style);
                    }
                    else if (num == 137)
                    {
                        tile.active(true);
                        tile.type = (ushort)num;
                        tile.frameY = (short)(18 * style);
                    }
                    else if (num == 136)
                    {
                        if (Main.tile[i - 1, j] == null)
{
                            Main.tile[i - 1, j] = new Tile();
                        }
                        if (Main.tile[i + 1, j] == null)
{
                            Main.tile[i + 1, j] = new Tile();
                        }
                        if (Main.tile[i, j + 1] == null)
{
                            Main.tile[i, j + 1] = new Tile();
                        }
                        if ((Main.tile[i - 1, j].nactive() && !Main.tile[i - 1, j].halfBrick() && !TileID.Sets.NotReallySolid[(int)Main.tile[i - 1, j].type] && Main.tile[i - 1, j].slope() == 0 && (WorldGen.SolidTile(i - 1, j, false) || TileID.Sets.IsBeam[(int)Main.tile[i - 1, j].type] || (Main.tile[i - 1, j].type == 5 && Main.tile[i - 1, j - 1].type == 5 && Main.tile[i - 1, j + 1].type == 5))) || (Main.tile[i + 1, j].nactive() && !Main.tile[i + 1, j].halfBrick() && !TileID.Sets.NotReallySolid[(int)Main.tile[i + 1, j].type] && Main.tile[i + 1, j].slope() == 0 && (WorldGen.SolidTile(i + 1, j, false) || TileID.Sets.IsBeam[(int)Main.tile[i + 1, j].type] || (Main.tile[i + 1, j].type == 5 && Main.tile[i + 1, j - 1].type == 5 && Main.tile[i + 1, j + 1].type == 5))) || (Main.tile[i, j + 1].nactive() && !Main.tile[i, j + 1].halfBrick() && WorldGen.SolidTile(i, j + 1, false) && Main.tile[i, j + 1].slope() == 0) || tile.wall > 0)
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 442)
                    {
                        if (Main.tile[i - 1, j] == null)
{
                            Main.tile[i - 1, j] = new Tile();
                        }
                        if (Main.tile[i + 1, j] == null)
{
                            Main.tile[i + 1, j] = new Tile();
                        }
                        if (Main.tile[i, j + 1] == null)
{
                            Main.tile[i, j + 1] = new Tile();
                        }
                        if ((Main.tile[i - 1, j].nactive() && !Main.tile[i - 1, j].halfBrick() && !TileID.Sets.NotReallySolid[(int)Main.tile[i - 1, j].type] && Main.tile[i - 1, j].slope() == 0 && (WorldGen.SolidTile(i - 1, j, false) || TileID.Sets.IsBeam[(int)Main.tile[i - 1, j].type] || (Main.tile[i - 1, j].type == 5 && Main.tile[i - 1, j - 1].type == 5 && Main.tile[i - 1, j + 1].type == 5))) || (Main.tile[i + 1, j].nactive() && !Main.tile[i + 1, j].halfBrick() && !TileID.Sets.NotReallySolid[(int)Main.tile[i + 1, j].type] && Main.tile[i + 1, j].slope() == 0 && (WorldGen.SolidTile(i + 1, j, false) || TileID.Sets.IsBeam[(int)Main.tile[i + 1, j].type] || (Main.tile[i + 1, j].type == 5 && Main.tile[i + 1, j - 1].type == 5 && Main.tile[i + 1, j + 1].type == 5))) || (Main.tile[i, j + 1].nactive() && !Main.tile[i, j + 1].halfBrick() && WorldGen.SolidTile(i, j + 1, false) && Main.tile[i, j + 1].slope() == 0))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 4)
                    {
                        if (Main.tile[i - 1, j] == null)
{
                            Main.tile[i - 1, j] = new Tile();
                        }
                        if (Main.tile[i + 1, j] == null)
{
                            Main.tile[i + 1, j] = new Tile();
                        }
                        if (Main.tile[i, j + 1] == null)
{
                            Main.tile[i, j + 1] = new Tile();
                        }
                        if (Main.tile[i - 1, j - 1] == null)
{
                            Main.tile[i - 1, j - 1] = new Tile();
                        }
                        if (Main.tile[i + 1, j - 1] == null)
{
                            Main.tile[i + 1, j - 1] = new Tile();
                        }
                        if (Main.tile[i - 1, j + 1] == null)
{
                            Main.tile[i - 1, j + 1] = new Tile();
                        }
                        if (Main.tile[i + 1, j + 1] == null)
{
                            Main.tile[i + 1, j + 1] = new Tile();
                        }
                        Tile tile2 = Main.tile[i - 1, j];
                        Tile tile3 = Main.tile[i + 1, j];
                        Tile tile4 = Main.tile[i, j + 1];
                        Tile tile5 = Main.tile[i - 1, j + 1];
                        Tile tile6 = Main.tile[i + 1, j + 1];
                        Tile tile7 = Main.tile[i - 1, j - 1];
                        Tile tile8 = Main.tile[i + 1, j - 1];
                        if (tile.wall > 0 || (tile2.active() && (tile2.slope() == 0 || tile2.slope() % 2 != 1) && ((Main.tileSolid[(int)tile2.type] && !Main.tileSolidTop[(int)tile2.type] && !TileID.Sets.NotReallySolid[(int)tile2.type]) || TileID.Sets.IsBeam[(int)tile2.type] || (WorldGen.IsTreeType((int)tile2.type) && WorldGen.IsTreeType((int)tile7.type) && WorldGen.IsTreeType((int)tile5.type)))) || (tile3.active() && (tile3.slope() == 0 || tile3.slope() % 2 != 0) && ((Main.tileSolid[(int)tile3.type] && !Main.tileSolidTop[(int)tile3.type] && !TileID.Sets.NotReallySolid[(int)tile3.type]) || TileID.Sets.IsBeam[(int)tile3.type] || (WorldGen.IsTreeType((int)tile3.type) && WorldGen.IsTreeType((int)tile8.type) && WorldGen.IsTreeType((int)tile6.type)))) || (tile4.active() && Main.tileSolid[(int)tile4.type] && ((TileID.Sets.Platforms[(int)tile4.type] && WorldGen.TopEdgeCanBeAttachedTo(i, j + 1)) || ((!Main.tileSolidTop[(int)tile4.type] || (tile4.type == 380 && tile4.slope() == 0)) && !TileID.Sets.NotReallySolid[(int)tile4.type] && !tile4.halfBrick() && tile4.slope() == 0))))
{
                            tile.active(true);
                            tile.type = (ushort)num;
                            tile.frameY = (short)(22 * style);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 10)
                    {
                        if (Main.tile[i, j - 1] == null)
{
                            Main.tile[i, j - 1] = new Tile();
                        }
                        if (Main.tile[i, j - 2] == null)
{
                            Main.tile[i, j - 2] = new Tile();
                        }
                        if (Main.tile[i, j - 3] == null)
{
                            Main.tile[i, j - 3] = new Tile();
                        }
                        if (Main.tile[i, j + 1] == null)
{
                            Main.tile[i, j + 1] = new Tile();
                        }
                        if (Main.tile[i, j + 2] == null)
{
                            Main.tile[i, j + 2] = new Tile();
                        }
                        if (Main.tile[i, j + 3] == null)
{
                            Main.tile[i, j + 3] = new Tile();
                        }
                        if (!Main.tile[i, j - 1].active() && !Main.tile[i, j - 2].active() && Main.tile[i, j - 3].active() && Main.tileSolid[(int)Main.tile[i, j - 3].type])
{
                            WorldGen.PlaceDoor(i, j - 1, num, style);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                        else
{
                            if (Main.tile[i, j + 1].active() || Main.tile[i, j + 2].active() || !Main.tile[i, j + 3].active() || !Main.tileSolid[(int)Main.tile[i, j + 3].type])
{
                                return false;
                            }
                            WorldGen.PlaceDoor(i, j + 1, num, style);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if ((num >= 275 && num <= 281) || num == 296 || num == 297 || num == 309 || num == 358 || num == 359 || num == 413 || num == 414 || num == 542)
                    {
                        WorldGen.Place6x3(i, j, (ushort)num, -1, 0);
                    }
                    else if (num == 237 || num == 244 || num == 285 || num == 286 || num == 298 || num == 299 || num == 310 || num == 339 || num == 538 || (num >= 361 && num <= 364) || num == 532 || num == 533 || num == 486 || num == 488 || num == 544 || num == 582 || num == 619 || num == 629)
                    {
                        WorldGen.Place3x2(i, j, (ushort)num, 0);
                    }
                    else if (num == 128)
                    {
                        WorldGen.PlaceMan(i, j, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 269)
                    {
                        WorldGen.PlaceWoman(i, j, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 334)
                    {
                        int num7 = 0;
                        if (style == -1)
{
                            num7 = 1;
                        }
                        WorldGen.Place3x3Wall(i, j, 334, num7);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 149)
                    {
                        int num8 = 0;
                        if (WorldGen.CheckAndAdjustMultiDirectionalTile(i, j, num, out num8))
{
                            tile.frameX = (short)(18 * style);
                            tile.active(true);
                            tile.type = (ushort)num;
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 139 || num == 35)
                    {
                        WorldGen.PlaceMB(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 165)
                    {
                        WorldGen.PlaceTight(i, j, false);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 235)
                    {
                        WorldGen.Place3x1(i, j, (ushort)num, 0);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 240)
                    {
                        WorldGen.Place3x3Wall(i, j, (ushort)num, style);
                    }
                    else if (num == 440)
                    {
                        WorldGen.Place3x3Wall(i, j, (ushort)num, style);
                    }
                    else if (num == 245)
                    {
                        WorldGen.Place2x3Wall(i, j, (ushort)num, style);
                    }
                    else if (num == 246)
                    {
                        WorldGen.Place3x2Wall(i, j, (ushort)num, style);
                    }
                    else if (num == 241)
                    {
                        WorldGen.Place4x3Wall(i, j, (ushort)num, style);
                    }
                    else if (num == 242)
                    {
                        WorldGen.Place6x4Wall(i, j, (ushort)num, style);
                    }
                    else if (num == 34)
                    {
                        WorldGen.PlaceChand(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 106 || num == 212 || num == 219 || num == 220 || num == 228 || num == 231 || num == 243 || num == 247 || num == 283 || (num >= 300 && num <= 308) || num == 354 || num == 355 || num == 491 || num == 642 || num == 733)
                    {
                        WorldGen.Place3x3(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 13 || num == 33 || num == 49 || num == 50 || num == 78 || num == 174 || num == 372 || num == 646)
                    {
                        WorldGen.PlaceOnTable1x1(i, j, num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 14 || num == 469 || num == 26 || num == 86 || num == 87 || num == 88 || num == 89 || num == 114 || num == 186 || num == 187 || num == 215 || num == 217 || num == 218 || num == 377)
                    {
                        WorldGen.Place3x2(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 236 || num == 702)
                    {
                        WorldGen.PlaceJunglePlant(i, j, (ushort)num, WorldGen.genRand.Next(3), 0, num != 702);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 238)
                    {
                        WorldGen.PlaceJunglePlant(i, j, (ushort)num, 0, 0, true);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 20)
                    {
                        if (Main.tile[i, j + 1] == null)
{
                            Main.tile[i, j + 1] = new Tile();
                        }
                        int type = (int)Main.tile[i, j + 1].type;
                        if (Main.tile[i, j + 1].active() && (type == 2 || type == 109 || type == 147 || type == 60 || type == 23 || type == 199 || type == 661 || type == 662 || type == 53 || type == 234 || type == 116 || type == 112 || type == 633))
{
                            WorldGen.Place1x2(i, j, (ushort)num, style);
                            WorldGen.SquareTileFrame(i, j, true);
                        }
                    }
                    else if (num == 15 || num == 216 || num == 338 || num == 390)
                    {
                        if (Main.tile[i, j - 1] == null)
{
                            Main.tile[i, j - 1] = new Tile();
                        }
                        if (Main.tile[i, j] == null)
{
                            Main.tile[i, j] = new Tile();
                        }
                        WorldGen.Place1x2(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 227)
                    {
                        WorldGen.PlaceDye(i, j, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 567)
                    {
                        WorldGen.PlaceGnome(i, j, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 16 || num == 18 || num == 29 || num == 103 || num == 134 || num == 462)
                    {
                        WorldGen.Place2x1(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 92 || num == 93 || num == 453)
                    {
                        WorldGen.Place1xX(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 104 || num == 105 || num == 320 || num == 337 || num == 349 || num == 356 || num == 663 || num == 378 || num == 456 || num == 506 || num == 545)
                    {
                        WorldGen.Place2xX(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 17 || num == 77 || num == 133)
                    {
                        WorldGen.Place3x2(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 207)
                    {
                        WorldGen.Place2xX(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 410 || num == 480 || num == 509 || num == 657 || num == 658 || num == 720 || num == 721 || num == 725)
                    {
                        WorldGen.Place2xX(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 465 || num == 531 || num == 591 || num == 592)
                    {
                        WorldGen.Place2xX(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (TileID.Sets.BasicChest[num])
                    {
                        WorldGen.PlaceChest(i, j, (ushort)num, false, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 91)
                    {
                        WorldGen.PlaceBanner(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 419 || num == 420 || num == 423 || num == 424 || num == 429 || num == 445)
                    {
                        WorldGen.PlaceLogicTiles(i, j, num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 135 || num == 141 || num == 144 || num == 210 || num == 239 || num == 36 || num == 324 || num == 476 || num == 494)
                    {
                        WorldGen.Place1x1(i, j, num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 101 || num == 102 || num == 463)
                    {
                        WorldGen.Place3x4(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 464 || num == 466)
                    {
                        WorldGen.Place5x4(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 27)
                    {
                        WorldGen.PlaceSunflower(i, j, 27);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 28)
                    {
                        WorldGen.PlacePot(i, j, 28, WorldGen.genRand.Next(4));
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 42 || num == 270 || num == 271)
                    {
                        WorldGen.Place1x2Top(i, j, (ushort)num, style);
                        WorldGen.SquareTileFrame(i, j, true);
                    }
                    else if (num == 55 || num == 425 || num == 511 || num == 510)
                    {
                        WorldGen.PlaceSign(i, j, (ushort)num, style);
                    }
                    else if (num == 85 || num == 376)
                    {
                        WorldGen.Place2x2Horizontal(i, j, (ushort)num, style);
                    }
                    else if (Main.tileAlch[num])
                    {
                        WorldGen.PlaceAlch(i, j, style);
                    }
                    else if (num == 94 || num == 95 || num == 97 || num == 98 || num == 99 || num == 100 || num == 125 || num == 126 || num == 173 || num == 287 || num == 172 || num == 751 || num == 752)
                    {
                        WorldGen.Place2x2(i, j, (ushort)num, style);
                    }
                    else if (num == 96)
                    {
                        WorldGen.Place2x2Style(i, j, (ushort)num, style);
                    }
                    else if (num == 79 || num == 90)
                    {
                        int num9 = 1;
                        if (plr > -1)
{
                            num9 = Main.player[plr].direction;
                        }
                        WorldGen.Place4x2(i, j, (ushort)num, num9, style);
                    }
                    else if (num == 209)
                    {
                        WorldGen.PlaceCannon(i, j, (ushort)num, style);
                    }
                    else if (num == 81)
                    {
                        tile.frameX = (short)(26 * WorldGen.genRand.Next(6));
                        tile.active(true);
                        tile.type = (ushort)num;
                    }
                    else if (num == 19)
                    {
                        tile.frameY = (short)(18 * style);
                        tile.active(true);
                        tile.type = (ushort)num;
                    }
                    else if (num == 380)
                    {
                        tile.frameY = (short)(18 * style);
                        tile.active(true);
                        tile.type = (ushort)num;
                    }
                    else if (num == 314)
                    {
                        Minecart.PlaceTrack(tile, style);
                    }
                    else
                    {
                        tile.active(true);
                        tile.type = (ushort)num;
                        if (num == 53 || num == 396 || num == 397)
{
                            if (SpecialSeedFeatures.RainbowSandAndBlackSandWalls)
{
                                tile.color(WorldGen.GetRainbowPaintIDForPosition(i, j, true));
                            }
                            else if (Main.tenthAnniversaryWorld && !Main.remixWorld && !Main.notTheBeesWorld && !Main.dontStarveWorld)
{
                                tile.color(7);
                            }
                        }
                    }
                    if (tile.active())
                    {
                        if (TileID.Sets.TruncatesWalls[(int)tile.type])
{
                            WorldGen.SquareWallFrame(i, j, true);
                        }
                        WorldGen.SquareTileFrame(i, j, true);
                        flag = true;
                        if (!mute)
{
                            if (num == 127)
{
                                SoundEngine.PlaySound(SoundID.Item30, i * 16, j * 16, 0f, 1f);
                            }
                            else if (num == 314)
{
                                SoundEngine.PlaySound(SoundID.Item52, i * 16, j * 16, 0f, 1f);
                            }
                            else if (num >= 330 && num <= 333)
{
                                SoundEngine.PlaySound(18, i * 16, j * 16, 1, 1f, 0f);
                            }
                            else
{
                                SoundEngine.PlaySound(0, i * 16, j * 16, 1, 1f, 0f);
                            }
                            if (num == 22 || num == 140)
{
                                for (int l = 0; l < 3; l++)
{
                                    Dust.NewDust(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16, 14, 0f, 0f, 0, default(Color), 1f);
                                }
                            }
                        }
                    }
                }
            }
            return flag;
        }
References Terraria.Tile.active(), Terraria.ID.WallID.Sets.AllowsPlantsToGrow, Terraria.ID.TileID.Sets.BasicChest, Terraria.Tile.bottomSlope(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.WorldGen.CheckAndAdjustMultiDirectionalTile(), Terraria.Tile.checkingLiquid(), Terraria.Tile.Clear(), Terraria.Tile.color(), Terraria.ID.TileID.Count, Terraria.ID.WallID.Count, Terraria.Entity.direction, Terraria.Main.dontStarveWorld, Terraria.Collision.EmptyTile(), Terraria.WorldGen.genRand, Terraria.WorldGen.GetRainbowPaintIDForPosition(), Terraria.ObjectData.TileObjectData.GetTileData(), Terraria.WorldGen.GrowCatTail(), Terraria.Tile.halfBrick(), Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), Terraria.WorldGen.HasValidGroundForGlowTulipBelowSpot(), int, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsADripTile, Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsFitToPlaceFlowerIn(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.IsTreeType(), Terraria.ID.SoundID.Item30, Terraria.ID.SoundID.Item52, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Dust.NewDust(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.NotReallySolid, Terraria.Main.notTheBeesWorld, Terraria.WorldGen.Place1x1(), Terraria.WorldGen.Place1x2(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place1xX(), Terraria.WorldGen.Place2x1(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place2x2Horizontal(), Terraria.WorldGen.Place2x2Style(), Terraria.WorldGen.Place2x3Wall(), Terraria.WorldGen.Place2xX(), Terraria.WorldGen.Place3x1(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x2Wall(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.Place3x3Wall(), Terraria.WorldGen.Place3x4(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.Place4x3Wall(), Terraria.WorldGen.Place5x4(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.Place6x4Wall(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceBanner(), Terraria.WorldGen.PlaceCannon(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChand(), Terraria.WorldGen.PlaceChest(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.PlaceGnome(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLogicTiles(), Terraria.WorldGen.PlaceMan(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceObject(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlaceSign(), Terraria.WorldGen.PlaceSunflower(), Terraria.WorldGen.PlaceTight(), Terraria.Minecart.PlaceTrack(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.WorldGen.PlaceWoman(), Terraria.WorldGen.PlaceXmasTree(), Terraria.WorldGen.PlantSeaOat(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.SpecialSeedFeatures.RainbowSandAndBlackSandWalls, Terraria.Main.remixWorld, Terraria.WorldGen.remixWorldGen, Terraria.ID.TileID.Sets.ResetsHalfBrickPlacementAttempt, Terraria.Main.rockLayer, Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tenthAnniversaryWorld, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileCut, Terraria.Main.tileFrameImportant, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.ID.TileID.Sets.Torches, Terraria.ID.TileID.Sets.TruncatesWalls, Terraria.Tile.type, Terraria.Tile.wall, Terraria.ObjectData.TileObjectData.WaterPlacement, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.WorldGen.AddBeeLarva(), Terraria.WorldGen.AddHellHouses(), Terraria.WorldGen.AddPasses(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.Projectile.AI(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_155_MysticSnakeCoil(), Terraria.GameContent.Generation.ActionGrass.Apply(), Terraria.GameContent.Generation.ActionPlaceStatue.Apply(), Terraria.WorldBuilding.Actions.PlaceTile.Apply(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.Liquid.CreateLiquidMergeTile(), Terraria.WorldGen.SecretSeed.DoAddTeleporters(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance_Door(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.Spread.Gem(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonBook(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonPotionBottle(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonWaterCandle(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.WorldGen.GrowWeb(), Terraria.WorldGen.hardUpdateWorld(), Terraria.WorldGen.HellFort(), Terraria.WorldGen.IslandHouse(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.OverGrownDungeon(), Terraria.WorldGen.OverGrownDungeonWithRainbowMoss(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_PlacePainting(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.GameContent.MinecartDiggerHelper.PlaceATrack(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificPriorityTool(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceBiomeSpecificTool(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceDoors(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLiquid(), Terraria.GameContent.Generation.TrackGenerator.PlacePath(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceStatueTrap(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.WorldGen.placeTNTBarrel(), Terraria.WorldGen.PlaceTorchesAroundSpawn(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.plantDye(), Terraria.WorldGen.Pyramid(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.SpawnGraveyardBiome(), Terraria.WorldGen.SpawnPlanteraThorns(), Terraria.Projectile.SpawnWebs(), Terraria.WorldGen.Spread.Spider(), Terraria.DelegateMethods.SpreadTile(), Terraria.WorldGen.Statue(), Terraria.WorldGen.StonePatch(), Terraria.WorldGen.templePart2(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_Door(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_OuterPillar(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TryGrowingGlowTulip(), Terraria.WorldGen.TryPlacingChilletEgg(), Terraria.Player.TryReplantingHerbs(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), and Terraria.WorldGen.WavyCaverer().