Terraria Decompiled: Terraria.WorldGen.CrimStart
CrimStart()
static void Terraria.WorldGen.CrimStart (int i, int j) inline static
Definition at line 75957 of file WorldGen.cs.
        {
            double num = Main.worldSurface;
            if (WorldGen.SecretSeed.noSurface.Enabled)
            {
                num = Main.rockLayer;
            }
            int num2 = 1;
            int num3 = j;
            if ((double)num3 > num)
            {
                num3 = (int)num;
            }
            while (!WorldGen.SolidTile(i, num3, false))
            {
                num3++;
            }
            int num4 = num3;
            Vector2D vector2D;
            vector2D..ctor((double)i, (double)num3);
            Vector2D vector2D2;
            vector2D2..ctor((double)WorldGen.genRand.Next(-20, 21) * 0.1, (double)WorldGen.genRand.Next(20, 201) * 0.01);
            if (vector2D2.X < 0.0)
            {
                num2 = -1;
            }
            double num5 = (double)WorldGen.genRand.Next(15, 26);
            bool flag = true;
            int num6 = 0;
            while (flag)
            {
                num5 += (double)WorldGen.genRand.Next(-50, 51) * 0.01;
                if (num5 < 15.0)
                {
                    num5 = 15.0;
                }
                if (num5 > 25.0)
                {
                    num5 = 25.0;
                }
                int num7 = (int)(vector2D.X - num5 / 2.0);
                while ((double)num7 < vector2D.X + num5 / 2.0)
                {
                    int num8 = (int)(vector2D.Y - num5 / 2.0);
                    while ((double)num8 < vector2D.Y + num5 / 2.0)
                    {
                        if (WorldGen.CanEvilReplace(num7, num8))
{
                            if (num8 > num4)
{
                                if (Math.Abs((double)num7 - vector2D.X) + Math.Abs((double)num8 - vector2D.Y) < num5 * 0.3)
{
                                    Main.tile[num7, num8].active(false);
                                    Main.tile[num7, num8].wall = GenVars.crimStoneWall;
                                }
                                else if (Math.Abs((double)num7 - vector2D.X) + Math.Abs((double)num8 - vector2D.Y) < num5 * 0.8 && Main.tile[num7, num8].wall != GenVars.crimStoneWall)
{
                                    Main.tile[num7, num8].active(true);
                                    Main.tile[num7, num8].type = GenVars.crimStone;
                                    if (Math.Abs((double)num7 - vector2D.X) + Math.Abs((double)num8 - vector2D.Y) < num5 * 0.6)
{
                                        Main.tile[num7, num8].wall = GenVars.crimStoneWall;
                                    }
                                }
                            }
                            else if (Math.Abs((double)num7 - vector2D.X) + Math.Abs((double)num8 - vector2D.Y) < num5 * 0.3 && Main.tile[num7, num8].active())
{
                                Main.tile[num7, num8].active(false);
                                Main.tile[num7, num8].wall = GenVars.crimStoneWall;
                            }
                        }
                        num8++;
                    }
                    num7++;
                }
                if (vector2D.X > (double)(i + 50))
                {
                    num6 = -100;
                }
                if (vector2D.X < (double)(i - 50))
                {
                    num6 = 100;
                }
                if (num6 < 0)
                {
                    vector2D2.X -= (double)WorldGen.genRand.Next(20, 51) * 0.01;
                }
                else if (num6 > 0)
                {
                    vector2D2.X += (double)WorldGen.genRand.Next(20, 51) * 0.01;
                }
                else
                {
                    vector2D2.X += (double)WorldGen.genRand.Next(-50, 51) * 0.01;
                }
                vector2D2.Y += (double)WorldGen.genRand.Next(-50, 51) * 0.01;
                if (vector2D2.Y < 0.25)
                {
                    vector2D2.Y = 0.25;
                }
                if (vector2D2.Y > 2.0)
                {
                    vector2D2.Y = 2.0;
                }
                if (vector2D2.X < -2.0)
                {
                    vector2D2.X = -2.0;
                }
                if (vector2D2.X > 2.0)
                {
                    vector2D2.X = 2.0;
                }
                vector2D += vector2D2;
                if (vector2D.Y > num + 100.0)
                {
                    flag = false;
                }
            }
            num5 = (double)WorldGen.genRand.Next(40, 55);
            for (int k = 0; k < 50; k++)
            {
                int num9 = (int)vector2D.X + WorldGen.genRand.Next(-20, 21);
                int num10 = (int)vector2D.Y + WorldGen.genRand.Next(-20, 21);
                int num11 = (int)((double)num9 - num5 / 2.0);
                while ((double)num11 < (double)num9 + num5 / 2.0)
                {
                    int num12 = (int)((double)num10 - num5 / 2.0);
                    while ((double)num12 < (double)num10 + num5 / 2.0)
                    {
                        if (WorldGen.CanEvilReplace(num11, num12))
{
                            double num13 = (double)Math.Abs(num11 - num9);
                            double num14 = (double)Math.Abs(num12 - num10);
                            double num15 = 1.0 + (double)WorldGen.genRand.Next(-20, 21) * 0.01;
                            double num16 = 1.0 + (double)WorldGen.genRand.Next(-20, 21) * 0.01;
                            double num17 = num13 * num15;
                            num14 *= num16;
                            double num18 = Math.Sqrt(num17 * num17 + num14 * num14);
                            if (num18 < num5 * 0.25)
{
                                Main.tile[num11, num12].active(false);
                                Main.tile[num11, num12].wall = GenVars.crimStoneWall;
                            }
                            else if (num18 < num5 * 0.4 && Main.tile[num11, num12].wall != GenVars.crimStoneWall)
{
                                Main.tile[num11, num12].active(true);
                                Main.tile[num11, num12].type = GenVars.crimStone;
                                if (num18 < num5 * 0.35)
{
                                    Main.tile[num11, num12].wall = GenVars.crimStoneWall;
                                }
                            }
                        }
                        num12++;
                    }
                    num11++;
                }
            }
            int num19 = WorldGen.genRand.Next(5, 9);
            Vector2D[] array = new Vector2D[num19];
            for (int l = 0; l < num19; l++)
            {
                int num20 = (int)vector2D.X;
                int num21 = (int)vector2D.Y;
                int num22 = 0;
                bool flag2 = true;
                Vector2D vector2D3;
                vector2D3..ctor((double)WorldGen.genRand.Next(-20, 21) * 0.15, (double)WorldGen.genRand.Next(0, 21) * 0.15);
                while (flag2)
                {
                    vector2D3..ctor((double)WorldGen.genRand.Next(-20, 21) * 0.15, (double)WorldGen.genRand.Next(0, 21) * 0.15);
                    while (Math.Abs(vector2D3.X) + Math.Abs(vector2D3.Y) < 1.5)
                    {
                        vector2D3..ctor((double)WorldGen.genRand.Next(-20, 21) * 0.15, (double)WorldGen.genRand.Next(0, 21) * 0.15);
                    }
                    flag2 = false;
                    for (int m = 0; m < l; m++)
                    {
                        if (vector2D2.X > array[m].X - 0.75 && vector2D2.X < array[m].X + 0.75 && vector2D2.Y > array[m].Y - 0.75 && vector2D2.Y < array[m].Y + 0.75)
{
                            flag2 = true;
                            num22++;
                            break;
                        }
                    }
                    if (num22 > 10000)
                    {
                        break;
                    }
                }
                array[l] = vector2D3;
                WorldGen.CrimVein(new Vector2D((double)num20, (double)num21), vector2D3);
            }
            int num23 = Main.maxTilesX;
            int num24 = 0;
            vector2D.X = (double)i;
            vector2D.Y = (double)num4;
            num5 = (double)WorldGen.genRand.Next(25, 35);
            double num25 = (double)WorldGen.genRand.Next(0, 6);
            for (int n = 0; n < 50; n++)
            {
                if (num25 > 0.0)
                {
                    double num26 = (double)WorldGen.genRand.Next(10, 30) * 0.01;
                    num25 -= num26;
                    vector2D.Y -= num26;
                }
                int num27 = (int)vector2D.X + WorldGen.genRand.Next(-2, 3);
                int num28 = (int)vector2D.Y + WorldGen.genRand.Next(-2, 3);
                int num29 = (int)((double)num27 - num5 / 2.0);
                while ((double)num29 < (double)num27 + num5 / 2.0)
                {
                    int num30 = (int)((double)num28 - num5 / 2.0);
                    while ((double)num30 < (double)num28 + num5 / 2.0)
                    {
                        if (WorldGen.CanEvilReplace(num29, num30))
{
                            double num31 = (double)Math.Abs(num29 - num27);
                            double num32 = (double)Math.Abs(num30 - num28);
                            double num33 = 1.0 + (double)WorldGen.genRand.Next(-20, 21) * 0.005;
                            double num34 = 1.0 + (double)WorldGen.genRand.Next(-20, 21) * 0.005;
                            double num35 = num31 * num33;
                            num32 *= num34;
                            double num36 = Math.Sqrt(num35 * num35 + num32 * num32);
                            if (num36 < num5 * 0.2 * ((double)WorldGen.genRand.Next(90, 111) * 0.01))
{
                                Main.tile[num29, num30].active(false);
                                Main.tile[num29, num30].wall = GenVars.crimStoneWall;
                            }
                            else if (num36 < num5 * 0.45)
{
                                if (num29 < num23)
{
                                    num23 = num29;
                                }
                                if (num29 > num24)
{
                                    num24 = num29;
                                }
                                if (Main.tile[num29, num30].wall != GenVars.crimStoneWall)
{
                                    Main.tile[num29, num30].active(true);
                                    Main.tile[num29, num30].type = GenVars.crimStone;
                                    if (num36 < num5 * 0.35)
{
                                        Main.tile[num29, num30].wall = GenVars.crimStoneWall;
                                    }
                                }
                            }
                        }
                        num30++;
                    }
                    num29++;
                }
            }
            for (int num37 = num23; num37 <= num24; num37++)
            {
                int num38 = num4;
                while ((Main.tile[num37, num38].type == GenVars.crimStone && Main.tile[num37, num38].active()) || Main.tile[num37, num38].wall == GenVars.crimStoneWall)
                {
                    num38++;
                }
                int num39 = WorldGen.genRand.Next(15, 20);
                while (!Main.tile[num37, num38].active() && num39 > 0 && Main.tile[num37, num38].wall != GenVars.crimStoneWall)
                {
                    if (WorldGen.CanEvilReplace(num37, num38))
                    {
                        num39--;
                        Main.tile[num37, num38].type = GenVars.crimStone;
                        Main.tile[num37, num38].active(true);
                        num38++;
                    }
                }
            }
            WorldGen.CrimEnt(vector2D, num2);
        }
References System.Math.Abs(), Terraria.Tile.active(), System.array, Terraria.WorldGen.CanEvilReplace(), Terraria.WorldGen.CrimEnt(), Terraria.WorldBuilding.GenVars.crimStone, Terraria.WorldBuilding.GenVars.crimStoneWall, Terraria.WorldGen.CrimVein(), Terraria.WorldGen.genRand, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.Main.rockLayer, Terraria.WorldGen.SolidTile(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().