Terraria Decompiled: Terraria.WorldGen.meteor
meteor()
static bool Terraria.WorldGen.meteor (int i, int j, bool ignorePlayers = false) inline static
Definition at line 2152 of file WorldGen.cs.
        {
            if (i < 50 || i > Main.maxTilesX - 50)
            {
                return false;
            }
            if (j < 50 || j > Main.maxTilesY - 50)
            {
                return false;
            }
            int num = 35;
            int num2 = num * 2 + 5;
            Rectangle rectangle = new Rectangle((i - num) * 16, (j - num) * 16, num * 2 * 16, num * 2 * 16);
            if (!WorldGen.InWorld(i - num, j - num, 10) || !WorldGen.InWorld(i + num, j + num, 10))
            {
                return false;
            }
            for (int k = 0; k < 255; k++)
            {
                if (Main.player[k].active && !ignorePlayers)
                {
                    Rectangle rectangle2 = new Rectangle((int)(Main.player[k].position.X + (float)(Main.player[k].width / 2) - (float)(NPC.sWidth / 2) - (float)NPC.safeRangeX), (int)(Main.player[k].position.Y + (float)(Main.player[k].height / 2) - (float)(NPC.sHeight / 2) - (float)NPC.safeRangeY), NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                    if (rectangle.Intersects(rectangle2))
                    {
                        return false;
                    }
                }
            }
            for (int l = 0; l < Main.maxNPCs; l++)
            {
                if (Main.npc[l].active)
                {
                    Rectangle rectangle3 = new Rectangle((int)Main.npc[l].position.X, (int)Main.npc[l].position.Y, Main.npc[l].width, Main.npc[l].height);
                    if (rectangle.Intersects(rectangle3))
                    {
                        return false;
                    }
                }
            }
            for (int m = i - num; m < i + num; m++)
            {
                for (int n = j - num; n < j + num; n++)
                {
                    if (Main.tile[m, n].active())
                    {
                        if (TileID.Sets.BasicChest[(int)Main.tile[m, n].type] || Main.tileDungeon[(int)Main.tile[m, n].type])
{
                            return false;
                        }
                        ushort type = Main.tile[m, n].type;
                        if (type <= 470)
{
                            if (type != 26 && type != 226 && type != 470)
{
                                goto IL_025B;
                            }
                        }
                        else if (type != 475 && type != 488 && type != 597)
{
                            goto IL_025B;
                        }
                        return false;
                    }
                    IL_025B:;
                }
            }
            WorldGen.stopDrops = true;
            num = WorldGen.genRand.Next(17, 23);
            for (int num3 = i - num; num3 < i + num; num3++)
            {
                for (int num4 = j - num; num4 < j + num; num4++)
                {
                    if (num4 > j + Main.rand.Next(-2, 3) - 5)
                    {
                        double num5 = (double)Math.Abs(i - num3);
                        double num6 = (double)Math.Abs(j - num4);
                        if (Math.Sqrt(num5 * num5 + num6 * num6) < (double)num * 0.9 + (double)Main.rand.Next(-4, 5))
{
                            if (!Main.tileSolid[(int)Main.tile[num3, num4].type])
{
                                Main.tile[num3, num4].active(false);
                            }
                            WorldGen.paintTile(num3, num4, 0, Main.netMode == 2, false);
                            WorldGen.paintCoatTile(num3, num4, 0, Main.netMode == 2, false);
                            Main.tile[num3, num4].ClearSlope();
                            Main.tile[num3, num4].type = 37;
                        }
                    }
                }
            }
            num = WorldGen.genRand.Next(8, 14);
            for (int num7 = i - num; num7 < i + num; num7++)
            {
                for (int num8 = j - num; num8 < j + num; num8++)
                {
                    if (num8 > j + Main.rand.Next(-2, 3) - 4)
                    {
                        double num9 = (double)Math.Abs(i - num7);
                        double num10 = (double)Math.Abs(j - num8);
                        if (Math.Sqrt(num9 * num9 + num10 * num10) < (double)num * 0.8 + (double)Main.rand.Next(-3, 4))
{
                            Main.tile[num7, num8].active(false);
                        }
                    }
                }
            }
            num = WorldGen.genRand.Next(25, 35);
            for (int num11 = i - num; num11 < i + num; num11++)
            {
                for (int num12 = j - num; num12 < j + num; num12++)
                {
                    double num13 = (double)Math.Abs(i - num11);
                    double num14 = (double)Math.Abs(j - num12);
                    if (Math.Sqrt(num13 * num13 + num14 * num14) < (double)num * 0.7)
                    {
                        if (TileID.Sets.GetsDestroyedForMeteors[(int)Main.tile[num11, num12].type])
{
                            WorldGen.KillTile(num11, num12, false, false, false);
                        }
                        Main.tile[num11, num12].liquid = 0;
                    }
                    if (Main.tile[num11, num12].type == 37)
                    {
                        if (!WorldGen.SolidTile(num11 - 1, num12, false) && !WorldGen.SolidTile(num11 + 1, num12, false) && !WorldGen.SolidTile(num11, num12 - 1, false) && !WorldGen.SolidTile(num11, num12 + 1, false))
{
                            Main.tile[num11, num12].active(false);
                        }
                        else if ((Main.tile[num11, num12].halfBrick() || Main.tile[num11 - 1, num12].topSlope()) && !WorldGen.SolidTile(num11, num12 + 1, false))
{
                            Main.tile[num11, num12].active(false);
                        }
                    }
                    WorldGen.SquareTileFrame(num11, num12, true);
                    WorldGen.SquareWallFrame(num11, num12, true);
                }
            }
            num = WorldGen.genRand.Next(23, 32);
            for (int num15 = i - num; num15 < i + num; num15++)
            {
                for (int num16 = j - num; num16 < j + num; num16++)
                {
                    if (num16 > j + WorldGen.genRand.Next(-3, 4) - 3 && Main.tile[num15, num16].active() && Main.rand.Next(10) == 0)
                    {
                        double num17 = (double)Math.Abs(i - num15);
                        double num18 = (double)Math.Abs(j - num16);
                        if (Math.Sqrt(num17 * num17 + num18 * num18) < (double)num * 0.8)
{
                            if (TileID.Sets.GetsDestroyedForMeteors[(int)Main.tile[num15, num16].type])
{
                                WorldGen.KillTile(num15, num16, false, false, false);
                            }
                            WorldGen.paintTile(num15, num16, 0, Main.netMode == 2, false);
                            WorldGen.paintCoatTile(num15, num16, 0, Main.netMode == 2, false);
                            Main.tile[num15, num16].ClearSlope();
                            Main.tile[num15, num16].type = 37;
                            WorldGen.SquareTileFrame(num15, num16, true);
                        }
                    }
                }
            }
            num = WorldGen.genRand.Next(30, 38);
            for (int num19 = i - num; num19 < i + num; num19++)
            {
                for (int num20 = j - num; num20 < j + num; num20++)
                {
                    if (num20 > j + WorldGen.genRand.Next(-2, 3) && Main.tile[num19, num20].active() && Main.rand.Next(20) == 0)
                    {
                        double num21 = (double)Math.Abs(i - num19);
                        double num22 = (double)Math.Abs(j - num20);
                        if (Math.Sqrt(num21 * num21 + num22 * num22) < (double)num * 0.85)
{
                            if (TileID.Sets.GetsDestroyedForMeteors[(int)Main.tile[num19, num20].type])
{
                                WorldGen.KillTile(num19, num20, false, false, false);
                            }
                            WorldGen.paintTile(num19, num20, 0, Main.netMode == 2, false);
                            WorldGen.paintCoatTile(num19, num20, 0, Main.netMode == 2, false);
                            Main.tile[num19, num20].ClearSlope();
                            Main.tile[num19, num20].type = 37;
                            WorldGen.SquareTileFrame(num19, num20, true);
                        }
                    }
                }
            }
            WorldGen.stopDrops = false;
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.gen[59].Key, new object[0]), ChatColors.World, -1);
            if (Main.netMode != 1)
            {
                NetMessage.SendTileSquare(-1, i, j, num2, TileChangeType.None);
            }
            return true;
        }
References System.Math.Abs(), Terraria.NPC.active, Terraria.Player.active, Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Tile.ClearSlope(), Terraria.Localization.NetworkText.FromKey(), Terraria.Lang.gen, Terraria.WorldGen.genRand, Terraria.ID.TileID.Sets.GetsDestroyedForMeteors, Terraria.Tile.halfBrick(), Terraria.Entity.height, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.InWorld(), Terraria.Localization.LocalizedText.Key, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.paintTile(), Terraria.Main.player, Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.NetMessage.SendTileSquare(), Terraria.NPC.sHeight, Terraria.WorldGen.SolidTile(), System.Math.Sqrt(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.NPC.sWidth, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileSolid, Terraria.Tile.topSlope(), Terraria.Tile.type, Terraria.Entity.width, Terraria.Chat.ChatColors.World, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.dropMeteor().