Terraria Decompiled: Terraria.WorldGen.CanPoundTile
CanPoundTile()
static bool Terraria.WorldGen.CanPoundTile (int x, int y) inline static
Definition at line 81357 of file WorldGen.cs.
        {
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            if (Main.tile[x, y - 1] == null)
            {
                Main.tile[x, y - 1] = new Tile();
            }
            if (Main.tile[x, y + 1] == null)
            {
                Main.tile[x, y + 1] = new Tile();
            }
            ushort type = Main.tile[x, y].type;
            if (type <= 232)
            {
                if (type <= 48)
                {
                    if (type != 10 && type != 48)
                    {
                        goto IL_00D0;
                    }
                }
                else if (type != 137 && type != 232)
                {
                    goto IL_00D0;
                }
            }
            else if (type <= 388)
            {
                if (type != 380 && type - 387 > 1)
                {
                    goto IL_00D0;
                }
            }
            else if (type != 476 && type != 484)
            {
                goto IL_00D0;
            }
            return false;
            IL_00D0:
            if (Main.tile[x, y].type >= 0 && TileID.Sets.Boulders[(int)Main.tile[x, y].type])
            {
                return false;
            }
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                if (Main.tile[x, y].type == 190)
                {
                    return false;
                }
                if (Main.tile[x, y].type == 30)
                {
                    return false;
                }
            }
            return (!Main.tile[x, y - 1].active() || !WorldGen.ForbidsSloping(x, y - 1)) && WorldGen.CanKillTile(x, y);
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.WorldGen.CanKillTile(), Terraria.WorldGen.ForbidsSloping(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.PoundTile(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.WorldGen.SlopeTile(), and Terraria.Tile.SmoothSlope().