Terraria Decompiled: Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid
TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid()
static bool Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid (int i, int j, int newFloorType) inline static
Definition at line 53331 of file WorldGen.cs.
        {
            if (newFloorType < 0 || newFloorType >= (int)TileID.Count)
            {
                return false;
            }
            if (!WorldGen.InWorld(i, j, 2))
            {
                return false;
            }
            Tile tile = Main.tile[i, j];
            if (tile == null || !tile.active())
            {
                return false;
            }
            Tile tile2 = Main.tile[i, j - 1];
            if (tile2 == null || !tile2.active())
            {
                return false;
            }
            ushort type = tile2.type;
            if (!WorldGen.IsTreeType((int)tile2.type) && tile2.type != 323)
            {
                return false;
            }
            bool flag = true;
            if (flag)
            {
                if (type != 5)
                {
                    if (type == 323)
                    {
                        flag = TileID.Sets.Conversion.Sand[newFloorType];
                    }
                }
                else
                {
                    flag = TileID.Sets.Conversion.Grass[newFloorType] || TileID.Sets.Conversion.JungleGrass[newFloorType] || TileID.Sets.Conversion.Snow[newFloorType] || TileID.Sets.Conversion.MushroomGrass[newFloorType];
                }
            }
            WorldGen.GrowTreeSettings growTreeSettings;
            if (flag && WorldGen.GrowTreeSettings.Profiles.TryGetFromTreeId((int)type, out growTreeSettings))
            {
                flag = growTreeSettings.GroundTest(newFloorType);
            }
            if (!flag)
            {
                if (type <= 323)
                {
                    if (type != 5)
                    {
                        if (type == 323)
{
                            if (TileID.Sets.Conversion.Grass[newFloorType] || TileID.Sets.Conversion.JungleGrass[newFloorType] || TileID.Sets.Conversion.Snow[newFloorType] || TileID.Sets.Conversion.MushroomGrass[newFloorType])
{
                                WorldGen.ConvertTreeAndGround(i, j - 1, newFloorType, (int)type, 5);
                                return true;
                            }
                            WorldGen.KillTile(i, j - 1, false, false, false);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)(j - 1), 0f, 0, 0, 0);
                                return true;
                            }
                            return true;
                        }
                    }
                    else
                    {
                        if (TileID.Sets.Conversion.Sand[newFloorType])
{
                            WorldGen.ConvertTreeAndGround(i, j - 1, newFloorType, (int)type, 323);
                            return true;
                        }
                        WorldGen.KillTile(i, j - 1, false, false, false);
                        if (Main.netMode == 1)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)(j - 1), 0f, 0, 0, 0);
                            return true;
                        }
                        return true;
                    }
                }
                else if (type == 596 || type == 616)
                {
                    if (TileID.Sets.Conversion.Grass[newFloorType] || TileID.Sets.Conversion.JungleGrass[newFloorType] || TileID.Sets.Conversion.Snow[newFloorType] || TileID.Sets.Conversion.MushroomGrass[newFloorType])
                    {
                        WorldGen.ConvertTreeAndGround(i, j - 1, newFloorType, (int)type, 5);
                        return true;
                    }
                    if (TileID.Sets.Conversion.Sand[newFloorType])
                    {
                        WorldGen.ConvertTreeAndGround(i, j - 1, newFloorType, (int)type, 323);
                        return true;
                    }
                    WorldGen.KillTile(i, j - 1, false, false, false);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)(j - 1), 0f, 0, 0, 0);
                        return true;
                    }
                    return true;
                }
                WorldGen.KillTile(i, j - 1, false, false, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)(j - 1), 0f, 0, 0, 0);
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.ConvertTreeAndGround(), Terraria.ID.TileID.Count, Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.WorldGen.GrowTreeSettings.GroundTest, Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTreeType(), Terraria.ID.TileID.Sets.Conversion.JungleGrass, Terraria.WorldGen.KillTile(), Terraria.ID.TileID.Sets.Conversion.MushroomGrass, Terraria.Main.netMode, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.NetMessage.SendData(), Terraria.ID.TileID.Sets.Conversion.Snow, Terraria.Main.tile, Terraria.WorldGen.GrowTreeSettings.Profiles.TryGetFromTreeId(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.Convert_ActuallyConvertTile(), and Terraria.WorldGen.SpreadGrass().