Terraria Decompiled: Terraria.WorldGen.IslandHouse
IslandHouse()
static void Terraria.WorldGen.IslandHouse (int i, int j, int islandStyle) inline static
Definition at line 79807 of file WorldGen.cs.
        {
            bool flag = WorldGen.crimson;
            int num = 30;
            for (int k = i - num; k <= i + num; k++)
            {
                for (int l = j - num; l <= j + num; l++)
                {
                    if (WorldGen.InWorld(k, l, 0))
                    {
                        if (Main.wallDungeon[(int)Main.tile[k, l].wall])
{
                            return;
                        }
                        if (Main.tile[k, l].wall == 87)
{
                            return;
                        }
                        if (Main.tile[k, l].wall == 3)
{
                            return;
                        }
                        if (Main.tile[k, l].wall == 83)
{
                            return;
                        }
                    }
                }
            }
            if (WorldGen.drunkWorldGen)
            {
                flag = (GenVars.crimsonLeft && i < Main.maxTilesX / 2) || (!GenVars.crimsonLeft && i > Main.maxTilesX / 2);
            }
            ushort num2 = 202;
            ushort num3 = 82;
            Vector2D vector2D;
            vector2D..ctor((double)i, (double)j);
            int num4 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num4 = -1;
            }
            int num5 = WorldGen.genRand.Next(7, 12);
            int num6 = WorldGen.genRand.Next(5, 7);
            vector2D.X = (double)(i + (num5 + 2) * num4);
            if ((double)j > Main.worldSurface)
            {
                vector2D.Y = (double)(j - 5);
            }
            else
            {
                for (int m = j - 15; m < j + 30; m++)
                {
                    Tile tile = Main.tile[(int)vector2D.X, m];
                    if (tile.wall > 0 && tile.active() && WorldGen.SolidTile((int)vector2D.X, m, false) && tile.type != 192 && tile.type != 191 && tile.type != 384 && tile.type != 384)
                    {
                        vector2D.Y = (double)(m - 1);
                        break;
                    }
                }
            }
            vector2D.X = (double)i;
            int num7 = (int)(vector2D.X - (double)num5 - 1.0);
            int num8 = (int)(vector2D.X + (double)num5 + 1.0);
            int num9 = (int)(vector2D.Y - (double)num6 - 1.0);
            int num10 = (int)(vector2D.Y + 2.0);
            if (num7 < 0)
            {
                num7 = 0;
            }
            if (num8 > Main.maxTilesX)
            {
                num8 = Main.maxTilesX;
            }
            if (num9 < 0)
            {
                num9 = 0;
            }
            if (num10 > Main.maxTilesY)
            {
                num10 = Main.maxTilesY;
            }
            for (int n = num7; n <= num8; n++)
            {
                for (int num11 = num9 - 1; num11 < num10 + 1; num11++)
                {
                    if (num11 != num9 - 1 || (n != num7 && n != num8))
                    {
                        Main.tile[n, num11].active(true);
                        Main.tile[n, num11].liquid = 0;
                        Main.tile[n, num11].type = num2;
                        Main.tile[n, num11].wall = 0;
                        Main.tile[n, num11].halfBrick(false);
                        Main.tile[n, num11].slope(0);
                    }
                }
            }
            num7 = (int)(vector2D.X - (double)num5);
            num8 = (int)(vector2D.X + (double)num5);
            num9 = (int)(vector2D.Y - (double)num6);
            num10 = (int)(vector2D.Y + 1.0);
            if (num7 < 0)
            {
                num7 = 0;
            }
            if (num8 > Main.maxTilesX)
            {
                num8 = Main.maxTilesX;
            }
            if (num9 < 0)
            {
                num9 = 0;
            }
            if (num10 > Main.maxTilesY)
            {
                num10 = Main.maxTilesY;
            }
            for (int num12 = num7; num12 <= num8; num12++)
            {
                for (int num13 = num9; num13 < num10; num13++)
                {
                    if ((num13 != num9 || (num12 != num7 && num12 != num8)) && Main.tile[num12, num13].wall == 0)
                    {
                        Main.tile[num12, num13].active(false);
                        Main.tile[num12, num13].wall = num3;
                    }
                }
            }
            int num14 = i + (num5 + 1) * num4;
            int num15 = (int)vector2D.Y;
            for (int num16 = num14 - 2; num16 <= num14 + 2; num16++)
            {
                Main.tile[num16, num15].active(false);
                Main.tile[num16, num15 - 1].active(false);
                Main.tile[num16, num15 - 2].active(false);
            }
            if (WorldGen.remixWorldGen && (!WorldGen.tenthAnniversaryWorldGen || WorldGen.getGoodWorldGen))
            {
                if (flag)
                {
                    WorldGen.PlaceTile(num14, num15, 10, true, false, -1, 5);
                }
                else
                {
                    WorldGen.PlaceTile(num14, num15, 10, true, false, -1, 38);
                }
            }
            else
            {
                WorldGen.PlaceTile(num14, num15, 10, true, false, -1, 9);
            }
            num14 = i + (num5 + 1) * -num4 - num4;
            for (int num17 = num9; num17 <= num10 + 1; num17++)
            {
                Main.tile[num14, num17].active(true);
                Main.tile[num14, num17].liquid = 0;
                Main.tile[num14, num17].type = num2;
                Main.tile[num14, num17].wall = 0;
                Main.tile[num14, num17].halfBrick(false);
                Main.tile[num14, num17].slope(0);
            }
            int num18 = 0;
            int num19 = GenVars.skyIslandHouseCount;
            if (num19 > 3)
            {
                num19 = WorldGen.genRand.Next(4);
            }
            if (num19 == 0)
            {
                num18 = 159;
            }
            else if (num19 == 1)
            {
                num18 = 65;
            }
            else if (num19 == 2)
            {
                num18 = 158;
            }
            else if (num19 == 3)
            {
                num18 = 2219;
            }
            if (WorldGen.getGoodWorldGen)
            {
                WorldGen.AddBuriedChest(i, num15 - 3, num18, false, 2, false, 0);
            }
            else
            {
                WorldGen.AddBuriedChest(i, num15 - 3, num18, false, 13, false, 0);
            }
            if (islandStyle > 0)
            {
                for (int num20 = 0; num20 < 100000; num20++)
                {
                    int num21 = i + WorldGen.genRand.Next(-50, 51);
                    int num22 = num15 + WorldGen.genRand.Next(21);
                    if ((num20 >= 50000 || Main.tile[num21, num22].type != 202) && !Main.tile[num21, num22].active())
                    {
                        WorldGen.Place2xX(num21, num22, 207, islandStyle);
                        if (Main.tile[num21, num22].active())
{
                            WorldGen.SwitchFountain(num21, num22);
                            break;
                        }
                    }
                }
            }
            GenVars.skyIslandHouseCount++;
            if (!WorldGen.remixWorldGen || (WorldGen.tenthAnniversaryWorldGen && !WorldGen.getGoodWorldGen))
            {
                int num23 = i - num5 / 2 + 1;
                int num24 = i + num5 / 2 - 1;
                int num25 = 1;
                if (num5 > 10)
                {
                    num25 = 2;
                }
                int num26 = (num9 + num10) / 2 - 1;
                for (int num27 = num23 - num25; num27 <= num23 + num25; num27++)
                {
                    for (int num28 = num26 - 1; num28 <= num26 + 1; num28++)
                    {
                        Main.tile[num27, num28].wall = 21;
                    }
                }
                for (int num29 = num24 - num25; num29 <= num24 + num25; num29++)
                {
                    for (int num30 = num26 - 1; num30 <= num26 + 1; num30++)
                    {
                        Main.tile[num29, num30].wall = 21;
                    }
                }
            }
            int num31 = i + (num5 / 2 + 1) * -num4;
            if (WorldGen.remixWorldGen && (!WorldGen.tenthAnniversaryWorldGen || WorldGen.getGoodWorldGen))
            {
                if (flag)
                {
                    WorldGen.PlaceTile(num31, num10 - 1, 14, true, false, -1, 5);
                    WorldGen.PlaceTile(num31 - 2, num10 - 1, 15, true, false, 0, 8);
                    WorldGen.PlaceTile(num31 + 2, num10 - 1, 15, true, false, 0, 8);
                }
                else
                {
                    WorldGen.PlaceTile(num31, num10 - 1, 469, true, false, -1, 2);
                    WorldGen.PlaceTile(num31 - 2, num10 - 1, 15, true, false, 0, 38);
                    WorldGen.PlaceTile(num31 + 2, num10 - 1, 15, true, false, 0, 38);
                }
            }
            else
            {
                WorldGen.PlaceTile(num31, num10 - 1, 14, true, false, -1, 7);
                WorldGen.PlaceTile(num31 - 2, num10 - 1, 15, true, false, 0, 10);
                WorldGen.PlaceTile(num31 + 2, num10 - 1, 15, true, false, 0, 10);
            }
            Tile tile2 = Main.tile[num31 - 2, num10 - 1];
            tile2.frameX += 18;
            Tile tile3 = Main.tile[num31 - 2, num10 - 2];
            tile3.frameX += 18;
            if (!WorldGen.remixWorldGen || (WorldGen.tenthAnniversaryWorldGen && !WorldGen.getGoodWorldGen))
            {
                int num32 = num7 + 1;
                int num33 = num9;
                WorldGen.PlaceTile(num32, num33, 91, true, false, -1, WorldGen.genRand.Next(7, 10));
                num32 = num8 - 1;
                num33 = num9;
                WorldGen.PlaceTile(num32, num33, 91, true, false, -1, WorldGen.genRand.Next(7, 10));
                if (num4 > 0)
                {
                    num32 = num7;
                    num33 = num9 + 1;
                }
                else
                {
                    num32 = num8;
                    num33 = num9 + 1;
                }
                WorldGen.PlaceTile(num32, num33, 91, true, false, -1, WorldGen.genRand.Next(7, 10));
            }
            if (islandStyle == 1)
            {
                int num34 = WorldGen.genRand.Next(3, 6);
                for (int num35 = 0; num35 < 100000; num35++)
                {
                    int num36 = i + WorldGen.genRand.Next(-50, 51);
                    int num37 = num15 + WorldGen.genRand.Next(-10, 21);
                    if (!Main.tile[num36, num37].active())
                    {
                        WorldGen.TryGrowingTreeByType(323, num36, num37 + 1, 0, false);
                        if (Main.tile[num36, num37].active())
{
                            num34--;
                        }
                    }
                    if (num34 <= 0)
                    {
                        break;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.Place2xX(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.WorldBuilding.GenVars.skyIslandHouseCount, Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SwitchFountain(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.