Terraria Decompiled: Terraria.WorldGen.Place2x1
Place2x1()
static void Terraria.WorldGen.Place2x1 (int x, int y, ushort type, int style = 0) inline static
Definition at line 45724 of file WorldGen.cs.
        {
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            if (Main.tile[x + 1, y] == null)
            {
                Main.tile[x + 1, y] = new Tile();
            }
            if (Main.tile[x, y + 1] == null)
            {
                Main.tile[x, y + 1] = new Tile();
            }
            if (Main.tile[x + 1, y + 1] == null)
            {
                Main.tile[x + 1, y + 1] = new Tile();
            }
            bool flag = false;
            if (type != 29 && type != 103 && WorldGen.SolidTile2(x, y + 1) && WorldGen.SolidTile2(x + 1, y + 1) && !Main.tile[x, y].active() && !Main.tile[x + 1, y].active())
            {
                flag = true;
            }
            else if ((type == 29 || type == 103) && Main.tile[x, y + 1].active() && Main.tile[x + 1, y + 1].active() && Main.tileTable[(int)Main.tile[x, y + 1].type] && Main.tileTable[(int)Main.tile[x + 1, y + 1].type] && !Main.tile[x, y].active() && !Main.tile[x + 1, y].active())
            {
                flag = true;
            }
            if (flag)
            {
                Main.tile[x, y].active(true);
                Main.tile[x, y].frameY = 0;
                Main.tile[x, y].frameX = (short)(36 * style);
                Main.tile[x, y].type = type;
                Main.tile[x + 1, y].active(true);
                Main.tile[x + 1, y].frameY = 0;
                Main.tile[x + 1, y].frameX = (short)(36 * style + 18);
                Main.tile[x + 1, y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileTable, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().