Terraria Decompiled: Terraria.WorldGen.CheckDoorClosed
CheckDoorClosed()
static void Terraria.WorldGen.CheckDoorClosed (int i, int j, Tile tileCache, int type) inline static private
Definition at line 87296 of file WorldGen.cs.
        {
            if (!WorldGen.destroyObject)
            {
                bool flag = false;
                int frameY = (int)tileCache.frameY;
                int num = frameY / 54;
                num += (int)(tileCache.frameX / 54 * 36);
                int num2 = j - frameY % 54 / 18;
                Tile tile = Main.tile[i, num2 - 1];
                Tile tile2 = Main.tile[i, num2];
                Tile tile3 = Main.tile[i, num2 + 1];
                Tile tile4 = Main.tile[i, num2 + 2];
                Tile tile5 = Main.tile[i, num2 + 3];
                if (tile == null)
                {
                    tile = new Tile();
                    Main.tile[i, num2 - 1] = tile;
                }
                if (tile2 == null)
                {
                    tile2 = new Tile();
                    Main.tile[i, num2] = tile2;
                }
                if (tile3 == null)
                {
                    tile3 = new Tile();
                    Main.tile[i, num2 + 1] = tile3;
                }
                if (tile4 == null)
                {
                    tile4 = new Tile();
                    Main.tile[i, num2 + 2] = tile4;
                }
                if (tile5 == null)
                {
                    tile5 = new Tile();
                    Main.tile[i, num2 + 3] = tile5;
                }
                if (!WorldGen.SolidTile(tile))
                {
                    flag = true;
                }
                if (!WorldGen.SolidTile(tile5))
                {
                    flag = true;
                }
                if (!tile2.active() || (int)tile2.type != type)
                {
                    flag = true;
                }
                if (!tile3.active() || (int)tile3.type != type)
                {
                    flag = true;
                }
                if (!tile4.active() || (int)tile4.type != type)
                {
                    flag = true;
                }
                if (flag)
                {
                    WorldGen.destroyObject = true;
                    if (tile2.type == 10)
                    {
                        WorldGen.KillTile(i, num2, false, false, false);
                    }
                    if (tile3.type == 10)
                    {
                        WorldGen.KillTile(i, num2 + 1, false, false, false);
                    }
                    if (tile4.type == 10)
                    {
                        WorldGen.KillTile(i, num2 + 2, false, false, false);
                    }
                    WorldGen.DropDoorItem(i, j, num);
                }
                WorldGen.destroyObject = false;
                WorldGen.CheckExploitDestroyQueue();
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.destroyObject, Terraria.WorldGen.DropDoorItem(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.WorldGen.KillTile(), Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().