Terraria Decompiled: Terraria.WorldGen.PaintTheTrees
PaintTheTrees()
static void Terraria.WorldGen.PaintTheTrees () inline static private
Definition at line 21492 of file WorldGen.cs.
        {
            int num = 20;
            if (WorldGen.remixWorldGen)
            {
                num = (int)Main.worldSurface;
            }
            byte b = (byte)WorldGen.genRand.Next(1, 13);
            bool flag = false;
            for (int i = 20; i < Main.maxTilesX - 20; i++)
            {
                bool flag2 = false;
                for (int j = num; j < Main.maxTilesY - 20; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && (tile.type == 5 || tile.type == 323 || tile.type == 596 || tile.type == 616))
                    {
                        tile.color(b);
                        flag2 = true;
                        flag = true;
                    }
                }
                if (flag && !flag2)
                {
                    flag = false;
                    b += 1;
                    if (b > 12)
                    {
                        b = 1;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.WorldGen.genRand, int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.remixWorldGen, Terraria.Main.tile, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.FinishTenthAnniversaryWorldPaintTreesAndMushrooms().