Terraria Decompiled: Terraria.WorldGen.SwitchFountain
SwitchFountain()
static void Terraria.WorldGen.SwitchFountain (int i, int j) inline static
Definition at line 49653 of file WorldGen.cs.
        {
            int k;
            for (k = (int)(Main.tile[i, j].frameX / 18); k >= 2; k -= 2)
            {
            }
            int num = (int)(Main.tile[i, j].frameY / 18);
            if (num >= 4)
            {
                num -= 4;
            }
            int num2 = i - k;
            int num3 = j - num;
            for (int l = num2; l < num2 + 2; l++)
            {
                for (int m = num3; m < num3 + 4; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (Main.tile[l, m].active() && Main.tile[l, m].type == 207)
                    {
                        if (Main.tile[l, m].frameY < 72)
{
                            Tile tile = Main.tile[l, m];
                            tile.frameY += 72;
                        }
                        else
{
                            Tile tile2 = Main.tile[l, m];
                            tile2.frameY -= 72;
                        }
                    }
                }
            }
            if (Wiring.running)
            {
                Wiring.SkipWire(num2, num3);
                Wiring.SkipWire(num2, num3 + 1);
                Wiring.SkipWire(num2, num3 + 2);
                Wiring.SkipWire(num2, num3 + 3);
                Wiring.SkipWire(num2 + 1, num3);
                Wiring.SkipWire(num2 + 1, num3 + 1);
                Wiring.SkipWire(num2 + 1, num3 + 2);
                Wiring.SkipWire(num2 + 1, num3 + 3);
            }
            NetMessage.SendTileSquare(-1, num2, num3, 2, 4, TileChangeType.None);
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Wiring.running, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Wiring.HitWireSingle(), Terraria.WorldGen.IslandHouse(), and Terraria.Player.TileInteractionsUse().