Terraria Decompiled: Terraria.WorldGen.Check4x4
Check4x4()
static void Terraria.WorldGen.Check4x4 (int i, int j, int type) inline static
Definition at line 51494 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k = (int)(Main.tile[i, j].frameX / 18);
            int num = 0;
            while (k >= 4)
            {
                num++;
                k -= 4;
            }
            int num2 = i - k;
            int num3 = 72 * num;
            int num4 = (int)(Main.tile[i, j].frameY / 72);
            int num5 = (int)(Main.tile[i, j].frameY % 72 / 18);
            if (k >= 4)
            {
                k -= 4;
            }
            k = i - k;
            int num6 = j - num5;
            for (int l = k; l < k + 4; l++)
            {
                for (int m = num6; m < num6 + 4; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || (int)Main.tile[l, m].frameX != (l - num2) * 18 + num3 || (int)Main.tile[l, m].frameY != (m - num6) * 18 + num4 * 72)
                    {
                        flag = true;
                    }
                }
            }
            for (int n = k; n < k + 4; n++)
            {
                if (Main.tile[n, num6 + 4] == null)
                {
                    Main.tile[n, num6 + 4] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(n, num6 + 4))
                {
                    flag = true;
                    break;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int num7 = k; num7 < k + 4; num7++)
                {
                    for (int num8 = num6; num8 < num6 + 4; num8++)
                    {
                        if ((int)Main.tile[num7, num8].type == type && Main.tile[num7, num8].active())
{
                            WorldGen.KillTile(num7, num8, false, false, false);
                        }
                    }
                }
                if (type == 699)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 40, 32, 5482, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                for (int num9 = k - 1; num9 < k + 5; num9++)
                {
                    for (int num10 = num6 - 1; num10 < num6 + 5; num10++)
                    {
                        WorldGen.TileFrame(num9, num10, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().