Terraria Decompiled: Terraria.WorldGen.ShiftTrapdoor
ShiftTrapdoor()
static bool Terraria.WorldGen.ShiftTrapdoor (int x, int y, bool playerAbove, int onlyCloseOrOpen = -1) inline static
Definition at line 49950 of file WorldGen.cs.
        {
            Tile tile = Framing.GetTileSafely(x, y);
            if (tile.type == 386 && onlyCloseOrOpen != 1)
            {
                Point topLeftAndStyles = WorldGen.GetTopLeftAndStyles(ref x, ref y, 2, 2, 18, 18);
                if (topLeftAndStyles.X == 0)
                {
                    if (!WorldGen.ValidateTileSquareIsActiveAndOfType(x, y, 2, 2, 386))
                    {
                        return false;
                    }
                    if (Main.netMode != 1 && Wiring.running)
                    {
                        Wiring.SkipWire(x, y);
                        Wiring.SkipWire(x, y + 1);
                        Wiring.SkipWire(x + 1, y);
                        Wiring.SkipWire(x + 1, y + 1);
                    }
                    if (!Collision.EmptyTile(x, y + 1, true) || !Collision.EmptyTile(x + 1, y + 1, true))
                    {
                        return false;
                    }
                    SoundEngine.PlaySound(8, x * 16 + 16, y * 16 + 16, 1, 1f, 0f);
                    for (int i = 0; i < 2; i++)
                    {
                        tile = Framing.GetTileSafely(x + i, y);
                        if (tile.active() && tile.type == 386)
{
                            tile.ClearTile();
                        }
                    }
                    for (int j = 0; j < 2; j++)
                    {
                        tile = Framing.GetTileSafely(x + j, y + 1);
                        tile.type = 387;
                        tile.frameX = (short)(j * 18);
                        tile.frameY = (short)(topLeftAndStyles.Y * 18);
                    }
                    for (int k = -1; k < 3; k++)
                    {
                        for (int l = 0; l < 3; l++)
{
                            WorldGen.TileFrame(x + k, y + l, false, false);
                        }
                    }
                    return true;
                }
                else if (topLeftAndStyles.X == 1)
                {
                    if (!WorldGen.ValidateTileSquareIsActiveAndOfType(x, y, 2, 2, 386))
                    {
                        return false;
                    }
                    if (Main.netMode != 1 && Wiring.running)
                    {
                        Wiring.SkipWire(x, y - 1);
                        Wiring.SkipWire(x, y);
                        Wiring.SkipWire(x + 1, y - 1);
                        Wiring.SkipWire(x + 1, y);
                    }
                    if (!Collision.EmptyTile(x, y, true) || !Collision.EmptyTile(x + 1, y, true))
                    {
                        return false;
                    }
                    SoundEngine.PlaySound(8, x * 16 + 16, y * 16, 1, 1f, 0f);
                    for (int m = 0; m < 2; m++)
                    {
                        tile = Framing.GetTileSafely(x + m, y + 1);
                        tile.ClearTile();
                    }
                    for (int n = 0; n < 2; n++)
                    {
                        tile = Framing.GetTileSafely(x + n, y);
                        tile.type = 387;
                        tile.frameX = (short)(n * 18);
                        tile.frameY = (short)(topLeftAndStyles.Y * 18);
                    }
                    for (int num = -1; num < 3; num++)
                    {
                        for (int num2 = -1; num2 < 2; num2++)
{
                            WorldGen.TileFrame(x + num, y + num2, false, false);
                        }
                    }
                    return true;
                }
            }
            if (tile.type != 387 || onlyCloseOrOpen == 0)
            {
                SoundEngine.PlaySound(9, x * 16, y * 16, 1, 1f, 0f);
                return false;
            }
            WorldGen.GetTopLeftAndStyles(ref x, ref y, 2, 1, 18, 18);
            Tile tileSafely = Framing.GetTileSafely(x, y);
            Tile tileSafely2 = Framing.GetTileSafely(x + 1, y);
            if ((tileSafely.active() && tileSafely.type == 387 && !WorldGen.CanKillTile(x, y)) || (tileSafely2.active() && tileSafely2.type == 387 && !WorldGen.CanKillTile(x + 1, y)))
            {
                return false;
            }
            if (!WorldGen.ValidateTileSquareIsActiveAndOfType(x, y, 2, 1, 387))
            {
                return false;
            }
            int num3 = playerAbove.ToDirectionInt();
            for (int num4 = 0; num4 < 2; num4++)
            {
                tile = Framing.GetTileSafely(x + num4, y + num3);
                if (tile.active() && !Main.tileCut[(int)tile.type] && !TileID.Sets.IsADripTile[(int)tile.type])
                {
                    return false;
                }
            }
            if (Main.netMode != 1 && Wiring.running)
            {
                Wiring.SkipWire(x, y);
                Wiring.SkipWire(x, y + num3);
                Wiring.SkipWire(x + 1, y);
                Wiring.SkipWire(x + 1, y + num3);
            }
            SoundEngine.PlaySound(8, x * 16 + 16, y * 16, 1, 1f, 0f);
            for (int num5 = 0; num5 < 2; num5++)
            {
                tile = Framing.GetTileSafely(x + num5, y + num3);
                if (tile.active() && (Main.tileCut[(int)tile.type] || TileID.Sets.IsADripTile[(int)tile.type]))
                {
                    WorldGen.KillTile(x + num5, y + num3, false, false, false);
                }
            }
            for (int num6 = 0; num6 < 2; num6++)
            {
                tile = Framing.GetTileSafely(x + num6, y);
                TileColorCache tileColorCache = tile.BlockColorAndCoating();
                for (int num7 = 0; num7 < 2; num7++)
                {
                    tile = Framing.GetTileSafely(x + num6, y + num7 - (!playerAbove).ToInt());
                    tile.type = 386;
                    tile.frameX = (short)(num6 * 18 + playerAbove.ToInt() * 36);
                    tile.frameY = (short)(num7 * 18);
                    tile.UseBlockColors(tileColorCache);
                    tile.active(true);
                }
            }
            for (int num8 = -1; num8 < 3; num8++)
            {
                for (int num9 = -1; num9 < 3; num9++)
                {
                    WorldGen.TileFrame(x + num8, y + num9 - (!playerAbove).ToInt() * 2, false, false);
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.WorldGen.CanKillTile(), Terraria.Tile.ClearTile(), Terraria.Collision.EmptyTile(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.GetTopLeftAndStyles(), int, Terraria.ID.TileID.Sets.IsADripTile, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Wiring.running, Terraria.Wiring.SkipWire(), Terraria.Main.tileCut, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, Terraria.Tile.UseBlockColors(), Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), and Terraria.Player.TileInteractionsUse().