Terraria Decompiled: Terraria.WorldGen.GrowSpike
GrowSpike()
static void Terraria.WorldGen.GrowSpike (int i, int j, ushort spikeType, ushort landType) inline static
Definition at line 43765 of file WorldGen.cs.
        {
            int num = -1;
            if (landType != 23)
            {
                if (landType == 199)
                {
                    num = 662;
                }
            }
            else
            {
                num = 661;
            }
            int num2 = i;
            int num3 = j;
            int num4 = 0;
            if (Main.tile[num2 + 1, num3].active() && Main.tile[num2 + 1, num3].type == spikeType)
            {
                num4++;
            }
            if (Main.tile[num2 - 1, num3].active() && Main.tile[num2 - 1, num3].type == spikeType)
            {
                num4++;
            }
            if (Main.tile[num2, num3 + 1].active() && Main.tile[num2, num3 + 1].type == spikeType)
            {
                num4++;
            }
            if (Main.tile[num2, num3 - 1].active() && Main.tile[num2, num3 - 1].type == spikeType)
            {
                num4++;
            }
            if (num4 < 3 || Main.tile[i, j].type == landType || (int)Main.tile[i, j].type == num)
            {
                int num5 = WorldGen.genRand.Next(4);
                if (num5 == 0)
                {
                    num3--;
                }
                else if (num5 == 1)
                {
                    num3++;
                }
                else if (num5 == 2)
                {
                    num2--;
                }
                else if (num5 == 3)
                {
                    num2++;
                }
                if (!Main.tile[num2, num3].active())
                {
                    num4 = 0;
                    if (Main.tile[num2 + 1, num3].active() && Main.tile[num2 + 1, num3].type == spikeType)
                    {
                        num4++;
                    }
                    if (Main.tile[num2 - 1, num3].active() && Main.tile[num2 - 1, num3].type == spikeType)
                    {
                        num4++;
                    }
                    if (Main.tile[num2, num3 + 1].active() && Main.tile[num2, num3 + 1].type == spikeType)
                    {
                        num4++;
                    }
                    if (Main.tile[num2, num3 - 1].active() && Main.tile[num2, num3 - 1].type == spikeType)
                    {
                        num4++;
                    }
                    if (num4 < 2)
                    {
                        int num6 = 7;
                        int num7 = num2 - num6;
                        int num8 = num2 + num6;
                        int num9 = num3 - num6;
                        int num10 = num3 + num6;
                        bool flag = false;
                        for (int k = num7; k < num8; k++)
{
                            for (int l = num9; l < num10; l++)
{
                                if (Math.Abs(k - num2) * 2 + Math.Abs(l - num3) < 9 && Main.tile[k, l].active() && (Main.tile[k, l].type == landType || (int)Main.tile[k, l].type == num) && Main.tile[k, l - 1].active() && Main.tile[k, l - 1].type == spikeType && Main.tile[k, l - 1].liquid == 0)
{
                                    flag = true;
                                    break;
                                }
                            }
                        }
                        if (flag)
{
                            Main.tile[num2, num3].type = spikeType;
                            Main.tile[num2, num3].active(true);
                            Main.tile[num2, num3].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(num2, num3, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, num2, num3, 1, TileChangeType.None);
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.CopyPaintAndCoating(), Terraria.WorldGen.genRand, Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().