Terraria Decompiled: Terraria.WorldGen.HellHouse
HellHouse()
static void Terraria.WorldGen.HellHouse (int i, int j, byte type = 76, byte wall = 13) inline static
Definition at line 30598 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(8, 20);
            int num2 = WorldGen.genRand.Next(1, 3);
            int num3 = WorldGen.genRand.Next(4, 13);
            int num4 = j;
            for (int k = 0; k < num2; k++)
            {
                int num5 = WorldGen.genRand.Next(5, 9);
                WorldGen.HellRoom(i, num4, num, num5, type, wall);
                num4 -= num5;
            }
            num4 = j;
            for (int l = 0; l < num3; l++)
            {
                int num6 = WorldGen.genRand.Next(5, 9);
                num4 += num6;
                WorldGen.HellRoom(i, num4, num, num6, type, wall);
            }
            for (int m = i - num / 2; m <= i + num / 2; m++)
            {
                num4 = j;
                while (num4 < Main.maxTilesY && ((Main.tile[m, num4].active() && (Main.tile[m, num4].type == 76 || Main.tile[m, num4].type == 75)) || Main.tile[i, num4].wall == 13 || Main.tile[i, num4].wall == 14))
                {
                    num4++;
                }
                int num7 = 6 + WorldGen.genRand.Next(3);
                while (num4 < Main.maxTilesY && !Main.tile[m, num4].active())
                {
                    num7--;
                    Main.tile[m, num4].active(true);
                    Main.tile[m, num4].type = 57;
                    num4++;
                    if (num7 <= 0)
                    {
                        break;
                    }
                }
            }
            int num8 = 0;
            int num9 = 0;
            num4 = j;
            while (num4 < Main.maxTilesY && ((Main.tile[i, num4].active() && (Main.tile[i, num4].type == 76 || Main.tile[i, num4].type == 75)) || Main.tile[i, num4].wall == 13 || Main.tile[i, num4].wall == 14))
            {
                num4++;
            }
            num4--;
            num9 = num4;
            while ((Main.tile[i, num4].active() && (Main.tile[i, num4].type == 76 || Main.tile[i, num4].type == 75)) || Main.tile[i, num4].wall == 13 || Main.tile[i, num4].wall == 14)
            {
                num4--;
                if (Main.tile[i, num4].active() && (Main.tile[i, num4].type == 76 || Main.tile[i, num4].type == 75))
                {
                    int num10 = WorldGen.genRand.Next(i - num / 2 + 1, i + num / 2 - 1);
                    int num11 = WorldGen.genRand.Next(i - num / 2 + 1, i + num / 2 - 1);
                    if (num10 > num11)
                    {
                        int num12 = num10;
                        num10 = num11;
                        num11 = num12;
                    }
                    if (num10 == num11)
                    {
                        if (num10 < i)
{
                            num11++;
                        }
                        else
{
                            num10--;
                        }
                    }
                    for (int n = num10; n <= num11; n++)
                    {
                        if (Main.tile[n, num4 - 1].wall == 13)
{
                            Main.tile[n, num4].wall = 13;
                        }
                        if (Main.tile[n, num4 - 1].wall == 14)
{
                            Main.tile[n, num4].wall = 14;
                        }
                        Main.tile[n, num4].type = 19;
                        Main.tile[n, num4].active(true);
                    }
                    num4--;
                }
            }
            num8 = num4;
            double num13 = (double)((num9 - num8) * num) * 0.02;
            int num14 = 0;
            while ((double)num14 < num13)
            {
                int num15 = WorldGen.genRand.Next(i - num / 2, i + num / 2 + 1);
                int num16 = WorldGen.genRand.Next(num8, num9);
                int num17 = WorldGen.genRand.Next(3, 8);
                for (int num18 = num15 - num17; num18 <= num15 + num17; num18++)
                {
                    for (int num19 = num16 - num17; num19 <= num16 + num17; num19++)
                    {
                        double num20 = (double)Math.Abs(num18 - num15);
                        double num21 = (double)Math.Abs(num19 - num16);
                        if (Math.Sqrt(num20 * num20 + num21 * num21) < (double)num17 * 0.4)
{
                            try
{
                                if (Main.tile[num18, num19].type == 76 || Main.tile[num18, num19].type == 19)
{
                                    Main.tile[num18, num19].active(false);
                                }
                                Main.tile[num18, num19].wall = 0;
                            }
                            catch
{
                            }
                        }
                    }
                }
                num14++;
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.HellRoom(), Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.