Terraria Decompiled: Terraria.WorldGen.Check3x3
Check3x3()
static void Terraria.WorldGen.Check3x3 (int i, int j, int type) inline static
Definition at line 51573 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k = (int)(Main.tile[i, j].frameX / 18);
            int num = 0;
            while (k >= 3)
            {
                num++;
                k -= 3;
            }
            int num2 = i - k;
            int num3 = 54 * num;
            int num4 = (int)(Main.tile[i, j].frameY / 54);
            int num5 = (int)(Main.tile[i, j].frameY % 54 / 18);
            if (k >= 3)
            {
                k -= 3;
            }
            k = i - k;
            int num6 = j - num5;
            for (int l = k; l < k + 3; l++)
            {
                for (int m = num6; m < num6 + 3; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || (int)Main.tile[l, m].frameX != (l - num2) * 18 + num3 || (int)Main.tile[l, m].frameY != (m - num6) * 18 + num4 * 54)
                    {
                        flag = true;
                    }
                }
            }
            if (type == 106 || type == 212 || type == 219 || type == 220 || type == 228 || type == 231 || type == 243 || type == 247 || type == 283 || (type >= 300 && type <= 308) || type == 354 || type == 355 || type == 499 || type == 406 || type == 412 || type == 452 || type == 455 || type == 491 || type == 642 || type == 733)
            {
                for (int n = k; n < k + 3; n++)
                {
                    if (Main.tile[n, num6 + 3] == null)
                    {
                        Main.tile[n, num6 + 3] = new Tile();
                    }
                    if (!WorldGen.SolidTileAllowBottomSlope(n, num6 + 3))
                    {
                        flag = true;
                        break;
                    }
                }
            }
            else
            {
                if (Main.tile[k + 1, num6 - 1] == null)
                {
                    Main.tile[k + 1, num6 - 1] = new Tile();
                }
                if (!Main.tile[k + 1, num6 - 1].nactive() || !Main.tileSolid[(int)Main.tile[k + 1, num6 - 1].type] || Main.tileSolidTop[(int)Main.tile[k + 1, num6 - 1].type])
                {
                    flag = true;
                }
            }
            if (WorldGen.generatingWorld && !Main.tileSolid[225] && type == 231)
            {
                flag = false;
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int num7 = k; num7 < k + 3; num7++)
                {
                    for (int num8 = num6; num8 < num6 + 3; num8++)
                    {
                        if ((int)Main.tile[num7, num8].type == type && Main.tile[num7, num8].active())
{
                            WorldGen.KillTile(num7, num8, false, false, false);
                        }
                    }
                }
                if (type == 106)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 363, 1, false, 0, false);
                }
                else if (type == 243)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1430, 1, false, 0, false);
                }
                else if (type == 212)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 951, 1, false, 0, false);
                }
                else if (type == 219)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 997, 1, false, 0, false);
                }
                else if (type == 642)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5296, 1, false, 0, false);
                }
                else if (type == 220)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 998, 1, false, 0, false);
                }
                else if (type == 228)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1120, 1, false, 0, false);
                }
                else if (type == 247)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 1551, 1, false, 0, false);
                }
                else if (type == 283)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2172, 1, false, 0, false);
                }
                else if (type >= 300 && type <= 306)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2192 + type - 300, 1, false, 0, false);
                }
                else if (type == 307)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2203, 1, false, 0, false);
                }
                else if (type == 308)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2204, 1, false, 0, false);
                }
                else if (type == 406)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3365, 1, false, 0, false);
                }
                else if (type == 452)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3742, 1, false, 0, false);
                }
                else if (type == 354)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 2999, 1, false, 0, false);
                }
                else if (type == 355)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3000, 1, false, 0, false);
                }
                else if (type == 499)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4142, 1, false, 0, false);
                }
                else if (type == 412)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3549, 1, false, 0, false);
                }
                else if (type == 455)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3747, 1, false, 0, false);
                }
                else if (type == 491)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 4076, 1, false, 0, false);
                }
                else if (type == 231)
                {
                    int num9 = (i + 1) * 16 + 8;
                    int num10 = j * 16;
                    Gore.NewGore(new Vector2((float)num9, (float)num10), default(Vector2), 300, 1f);
                    Gore.NewGore(new Vector2((float)num9, (float)(num10 + 8)), default(Vector2), 301, 1f);
                    Gore.NewGore(new Vector2((float)num9, (float)(num10 + 16)), default(Vector2), 302, 1f);
                    float num11 = (float)(i * 16);
                    float num12 = (float)(j * 16);
                    float num13 = -1f;
                    int num14 = 0;
                    for (int num15 = 0; num15 < 255; num15++)
                    {
                        if (Main.player[num15].active && !Main.player[num15].dead)
{
                            float num16 = Math.Abs(Main.player[num15].position.X - num11) + Math.Abs(Main.player[num15].position.Y - num12);
                            if (num16 < num13 || num13 == -1f)
{
                                num14 = num15;
                                num13 = num16;
                            }
                        }
                    }
                    if (num13 < 4800f && !Main.gameMenu)
                    {
                        NPC.SpawnOnPlayer(num14, 222, 0f, 0f, 0f, 0f);
                    }
                }
                else if (type == 733)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 5113, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                for (int num17 = k - 1; num17 < k + 4; num17++)
                {
                    for (int num18 = num6 - 1; num18 < num6 + 4; num18++)
                    {
                        WorldGen.TileFrame(num17, num18, false, false);
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Player.active, Terraria.Tile.active(), Terraria.Player.dead, Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.gameMenu, Terraria.WorldGen.generatingWorld, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Gore.NewGore(), Terraria.Item.NewItem(), Terraria.Main.player, Terraria.Entity.position, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.NPC.SpawnOnPlayer(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.TileFrameImportant().