Terraria Decompiled: Terraria.WorldGen.PlaceUncheckedStalactite
PlaceUncheckedStalactite()
static void Terraria.WorldGen.PlaceUncheckedStalactite (int x, int y, bool preferSmall, int variation, bool spiders) inline static
Definition at line 35798 of file WorldGen.cs.
        {
            ushort num = 165;
            variation = Utils.Clamp<int>(variation, 0, 2);
            if (WorldGen.SolidTile(x, y - 1, false) && !Main.tile[x, y].active() && !Main.tile[x, y + 1].active())
            {
                Tile tile = Main.tile[x, y - 1];
                if (spiders)
                {
                    int num2 = 108 + variation * 18;
                    Main.tile[x, y].type = num;
                    Main.tile[x, y].active(true);
                    Main.tile[x, y].ClearSlope();
                    Main.tile[x, y].frameX = (short)num2;
                    Main.tile[x, y].frameY = 0;
                    Main.tile[x, y].CopyPaintAndCoating(tile);
                    Main.tile[x, y + 1].type = num;
                    Main.tile[x, y + 1].active(true);
                    Main.tile[x, y + 1].ClearSlope();
                    Main.tile[x, y + 1].frameX = (short)num2;
                    Main.tile[x, y + 1].frameY = 18;
                    Main.tile[x, y + 1].CopyPaintAndCoating(tile);
                    return;
                }
                if (Main.tile[x, y - 1].type == 147 || Main.tile[x, y - 1].type == 161 || Main.tile[x, y - 1].type == 163 || Main.tile[x, y - 1].type == 164 || Main.tile[x, y - 1].type == 200)
                {
                    if (preferSmall)
                    {
                        int num3 = variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num3;
                        Main.tile[x, y].frameY = 72;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                    }
                    else
                    {
                        int num4 = variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num4;
                        Main.tile[x, y].frameY = 0;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                        Main.tile[x, y + 1].type = num;
                        Main.tile[x, y + 1].active(true);
                        Main.tile[x, y + 1].ClearSlope();
                        Main.tile[x, y + 1].frameX = (short)num4;
                        Main.tile[x, y + 1].frameY = 18;
                        Main.tile[x, y + 1].CopyPaintAndCoating(tile);
                    }
                }
                if (Main.tile[x, y - 1].type == 1 || Main.tileMoss[(int)Main.tile[x, y - 1].type] || Main.tile[x, y - 1].type == 117 || Main.tile[x, y - 1].type == 25 || Main.tile[x, y - 1].type == 203)
                {
                    if (preferSmall)
                    {
                        int num5 = 54 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num5;
                        Main.tile[x, y].frameY = 72;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                    }
                    else
                    {
                        int num6 = 54 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num6;
                        Main.tile[x, y].frameY = 0;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                        Main.tile[x, y + 1].type = num;
                        Main.tile[x, y + 1].active(true);
                        Main.tile[x, y + 1].ClearSlope();
                        Main.tile[x, y + 1].frameX = (short)num6;
                        Main.tile[x, y + 1].frameY = 18;
                        Main.tile[x, y + 1].CopyPaintAndCoating(tile);
                    }
                }
                if (Main.tile[x, y - 1].type == 225)
                {
                    int num7 = 162 + variation * 18;
                    Main.tile[x, y].type = num;
                    Main.tile[x, y].active(true);
                    Main.tile[x, y].ClearSlope();
                    Main.tile[x, y].frameX = (short)num7;
                    Main.tile[x, y].frameY = 72;
                    Main.tile[x, y].CopyPaintAndCoating(tile);
                }
                if (Main.tile[x, y - 1].type == 396 || Main.tile[x, y - 1].type == 397)
                {
                    if (preferSmall)
                    {
                        int num8 = 378 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num8;
                        Main.tile[x, y].frameY = 72;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                    }
                    else
                    {
                        int num9 = 378 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num9;
                        Main.tile[x, y].frameY = 0;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                        Main.tile[x, y + 1].type = num;
                        Main.tile[x, y + 1].active(true);
                        Main.tile[x, y + 1].ClearSlope();
                        Main.tile[x, y + 1].frameX = (short)num9;
                        Main.tile[x, y + 1].frameY = 18;
                        Main.tile[x, y + 1].CopyPaintAndCoating(tile);
                    }
                }
                if (Main.tile[x, y - 1].type == 368)
                {
                    if (preferSmall)
                    {
                        int num10 = 432 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num10;
                        Main.tile[x, y].frameY = 72;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                    }
                    else
                    {
                        int num11 = 432 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num11;
                        Main.tile[x, y].frameY = 0;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                        Main.tile[x, y + 1].type = num;
                        Main.tile[x, y + 1].active(true);
                        Main.tile[x, y + 1].ClearSlope();
                        Main.tile[x, y + 1].frameX = (short)num11;
                        Main.tile[x, y + 1].frameY = 18;
                        Main.tile[x, y + 1].CopyPaintAndCoating(tile);
                    }
                }
                if (Main.tile[x, y - 1].type == 367)
                {
                    if (preferSmall)
                    {
                        int num12 = 486 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num12;
                        Main.tile[x, y].frameY = 72;
                        Main.tile[x, y].CopyPaintAndCoating(tile);
                        return;
                    }
                    int num13 = 486 + variation * 18;
                    Main.tile[x, y].type = num;
                    Main.tile[x, y].active(true);
                    Main.tile[x, y].ClearSlope();
                    Main.tile[x, y].frameX = (short)num13;
                    Main.tile[x, y].frameY = 0;
                    Main.tile[x, y].CopyPaintAndCoating(tile);
                    Main.tile[x, y + 1].type = num;
                    Main.tile[x, y + 1].active(true);
                    Main.tile[x, y + 1].ClearSlope();
                    Main.tile[x, y + 1].frameX = (short)num13;
                    Main.tile[x, y + 1].frameY = 18;
                    Main.tile[x, y + 1].CopyPaintAndCoating(tile);
                    return;
                }
            }
            else
            {
                if (spiders)
                {
                    return;
                }
                if (WorldGen.SolidTile(x, y + 1, false) && !Main.tile[x, y].active() && !Main.tile[x, y - 1].active())
                {
                    Tile tile2 = Main.tile[x, y + 1];
                    if (Main.tile[x, y + 1].type == 1 || Main.tileMoss[(int)Main.tile[x, y + 1].type] || Main.tile[x, y + 1].type == 117 || Main.tile[x, y + 1].type == 25 || Main.tile[x, y + 1].type == 203)
                    {
                        if (preferSmall)
{
                            int num14 = 54 + variation * 18;
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num14;
                            Main.tile[x, y].frameY = 90;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                        }
                        else
{
                            int num15 = 54 + variation * 18;
                            Main.tile[x, y - 1].type = num;
                            Main.tile[x, y - 1].active(true);
                            Main.tile[x, y - 1].ClearSlope();
                            Main.tile[x, y - 1].frameX = (short)num15;
                            Main.tile[x, y - 1].frameY = 36;
                            Main.tile[x, y - 1].CopyPaintAndCoating(tile2);
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num15;
                            Main.tile[x, y].frameY = 54;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                        }
                    }
                    if (Main.tile[x, y + 1].type == 225)
                    {
                        int num16 = 162 + variation * 18;
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num16;
                        Main.tile[x, y].frameY = 90;
                        Main.tile[x, y].CopyPaintAndCoating(tile2);
                    }
                    if (Main.tile[x, y + 1].type == 396 || Main.tile[x, y + 1].type == 397)
                    {
                        if (preferSmall)
{
                            int num17 = 378 + variation * 18;
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num17;
                            Main.tile[x, y].frameY = 90;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                        }
                        else
{
                            int num18 = 378 + variation * 18;
                            Main.tile[x, y - 1].type = num;
                            Main.tile[x, y - 1].active(true);
                            Main.tile[x, y - 1].ClearSlope();
                            Main.tile[x, y - 1].frameX = (short)num18;
                            Main.tile[x, y - 1].frameY = 36;
                            Main.tile[x, y - 1].CopyPaintAndCoating(tile2);
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num18;
                            Main.tile[x, y].frameY = 54;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                        }
                    }
                    if (Main.tile[x, y + 1].type == 368)
                    {
                        if (preferSmall)
{
                            int num19 = 432 + variation * 18;
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num19;
                            Main.tile[x, y].frameY = 90;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                        }
                        else
{
                            int num20 = 432 + variation * 18;
                            Main.tile[x, y - 1].type = num;
                            Main.tile[x, y - 1].active(true);
                            Main.tile[x, y - 1].ClearSlope();
                            Main.tile[x, y - 1].frameX = (short)num20;
                            Main.tile[x, y - 1].frameY = 36;
                            Main.tile[x, y - 1].CopyPaintAndCoating(tile2);
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num20;
                            Main.tile[x, y].frameY = 54;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                        }
                    }
                    if (Main.tile[x, y + 1].type == 367)
                    {
                        if (preferSmall)
{
                            int num21 = 486 + variation * 18;
                            Main.tile[x, y].type = num;
                            Main.tile[x, y].active(true);
                            Main.tile[x, y].ClearSlope();
                            Main.tile[x, y].frameX = (short)num21;
                            Main.tile[x, y].frameY = 90;
                            Main.tile[x, y].CopyPaintAndCoating(tile2);
                            return;
                        }
                        int num22 = 486 + variation * 18;
                        Main.tile[x, y - 1].type = num;
                        Main.tile[x, y - 1].active(true);
                        Main.tile[x, y - 1].ClearSlope();
                        Main.tile[x, y - 1].frameX = (short)num22;
                        Main.tile[x, y - 1].frameY = 36;
                        Main.tile[x, y - 1].CopyPaintAndCoating(tile2);
                        Main.tile[x, y].type = num;
                        Main.tile[x, y].active(true);
                        Main.tile[x, y].ClearSlope();
                        Main.tile[x, y].frameX = (short)num22;
                        Main.tile[x, y].frameY = 54;
                        Main.tile[x, y].CopyPaintAndCoating(tile2);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.Tile.ClearSlope(), Terraria.Tile.CopyPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Main.tileMoss, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Biomes.GraniteBiome.PlaceDecorations(), and Terraria.WorldGen.PlaceTight().