Terraria Decompiled: Terraria.WorldGen.AnyLiquidAt
AnyLiquidAt() [2/2]
static bool Terraria.WorldGen.AnyLiquidAt (int x, int y, int range, int liquidType = -1) inline static
Definition at line 70548 of file WorldGen.cs.
        {
            if (range <= 0)
            {
                return WorldGen.AnyLiquidAt(x, y, liquidType);
            }
            int num = 5;
            int num2 = Math.Max(num, x - range);
            int num3 = Math.Max(num, y - range);
            int num4 = Math.Min(Main.maxTilesX - num, x + range);
            int num5 = Math.Min(Main.maxTilesY - num, y + range);
            for (int i = num2; i < num4; i++)
            {
                for (int j = num3; j < num5; j++)
                {
                    if (WorldGen.AnyLiquidAt(i, j, liquidType))
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.WorldGen.AnyLiquidAt(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, and System.Math.Min().