Terraria Decompiled: Terraria.WorldGen.CheckTreeWithSettings
CheckTreeWithSettings()
static void Terraria.WorldGen.CheckTreeWithSettings (int x, int y, WorldGen::CheckTreeSettings settings) inline static
Definition at line 52928 of file WorldGen.cs.
        {
            int num = -1;
            int num2 = -1;
            int num3 = -1;
            int num4 = -1;
            Tile tile = Main.tile[x, y];
            int type = (int)tile.type;
            int frameX = (int)tile.frameX;
            int frameY = (int)tile.frameY;
            if (Main.tile[x - 1, y] != null && Main.tile[x - 1, y].active())
            {
                num2 = (int)Main.tile[x - 1, y].type;
            }
            if (Main.tile[x + 1, y] != null && Main.tile[x + 1, y].active())
            {
                num3 = (int)Main.tile[x + 1, y].type;
            }
            if (Main.tile[x, y - 1] != null && Main.tile[x, y - 1].active())
            {
                num = (int)Main.tile[x, y - 1].type;
            }
            if (Main.tile[x, y + 1] != null && Main.tile[x, y + 1].active())
            {
                num4 = (int)Main.tile[x, y + 1].type;
            }
            bool flag = settings.IsGroundValid(num4);
            bool flag2 = num3 == type;
            bool flag3 = num2 == type;
            if (!flag && num4 != type && ((tile.frameX == 0 && tile.frameY <= 130) || (tile.frameX == 22 && tile.frameY <= 130) || (tile.frameX == 44 && tile.frameY <= 130)))
            {
                WorldGen.KillTile(x, y, false, false, false);
            }
            if (tile.frameX >= 22 && tile.frameX <= 44 && tile.frameY >= 132 && tile.frameY <= 176)
            {
                if (!flag)
                {
                    WorldGen.KillTile(x, y, false, false, false);
                }
                else if ((tile.frameX != 22 || !flag3) && (tile.frameX != 44 || !flag2))
                {
                    WorldGen.KillTile(x, y, false, false, false);
                }
            }
            else if ((tile.frameX == 88 && tile.frameY >= 0 && tile.frameY <= 44) || (tile.frameX == 66 && tile.frameY >= 66 && tile.frameY <= 130) || (tile.frameX == 110 && tile.frameY >= 66 && tile.frameY <= 110) || (tile.frameX == 132 && tile.frameY >= 0 && tile.frameY <= 176))
            {
                int num5 = (int)(tile.frameY % 66);
                if (flag3 && flag2)
                {
                    tile.frameX = 110;
                    tile.frameY = (short)(66 + num5);
                }
                else if (flag3)
                {
                    tile.frameX = 88;
                    tile.frameY = (short)num5;
                }
                else if (flag2)
                {
                    tile.frameX = 66;
                    tile.frameY = (short)(66 + num5);
                }
                else
                {
                    tile.frameX = 0;
                    tile.frameY = (short)num5;
                }
            }
            if (tile.frameY >= 132 && tile.frameY <= 176 && (tile.frameX == 0 || tile.frameX == 66 || tile.frameX == 88))
            {
                int num6 = (int)(tile.frameY % 66);
                if (!flag)
                {
                    WorldGen.KillTile(x, y, false, false, false);
                }
                else if (!flag3 && !flag2)
                {
                    tile.frameX = 0;
                    tile.frameY = (short)num6;
                }
                else if (!flag3)
                {
                    tile.frameX = 0;
                    tile.frameY = (short)(132 + num6);
                }
                else if (!flag2)
                {
                    tile.frameX = 66;
                    tile.frameY = (short)(132 + num6);
                }
                else
                {
                    tile.frameX = 88;
                    tile.frameY = (short)(132 + num6);
                }
            }
            if ((tile.frameX == 66 && (tile.frameY == 0 || tile.frameY == 22 || tile.frameY == 44)) || (tile.frameX == 44 && (tile.frameY == 198 || tile.frameY == 220 || tile.frameY == 242)))
            {
                if (!flag2)
                {
                    WorldGen.KillTile(x, y, false, false, false);
                }
            }
            else if ((tile.frameX == 88 && (tile.frameY == 66 || tile.frameY == 88 || tile.frameY == 110)) || (tile.frameX == 66 && (tile.frameY == 198 || tile.frameY == 220 || tile.frameY == 242)))
            {
                if (!flag3)
                {
                    WorldGen.KillTile(x, y, false, false, false);
                }
            }
            else if (num4 == -1)
            {
                WorldGen.KillTile(x, y, false, false, false);
            }
            else if (num != type && tile.frameY < 198 && ((tile.frameX != 22 && tile.frameX != 44) || tile.frameY < 132))
            {
                int num7 = (int)(tile.frameY % 66);
                if (flag3 || flag2)
                {
                    if (num4 == type)
                    {
                        if (flag3 && flag2)
{
                            tile.frameX = 132;
                            tile.frameY = (short)(132 + num7);
                        }
                        else if (flag3)
{
                            tile.frameX = 132;
                            tile.frameY = (short)num7;
                        }
                        else if (flag2)
{
                            tile.frameX = 132;
                            tile.frameY = (short)(66 + num7);
                        }
                    }
                    else if (flag3 && flag2)
                    {
                        tile.frameX = 154;
                        tile.frameY = (short)(132 + num7);
                    }
                    else if (flag3)
                    {
                        tile.frameX = 154;
                        tile.frameY = (short)num7;
                    }
                    else if (flag2)
                    {
                        tile.frameX = 154;
                        tile.frameY = (short)(66 + num7);
                    }
                }
                else
                {
                    tile.frameX = 110;
                    tile.frameY = (short)num7;
                }
            }
            if ((int)tile.frameX != frameX && (int)tile.frameY != frameY && frameX >= 0 && frameY >= 0)
            {
                WorldGen.TileFrame(x - 1, y, false, false);
                WorldGen.TileFrame(x + 1, y, false, false);
                WorldGen.TileFrame(x, y - 1, false, false);
                WorldGen.TileFrame(x, y + 1, false, false);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.WorldGen.KillTile(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().