Terraria Decompiled: Terraria.WorldGen.WaterCheck
WaterCheck()
static void Terraria.WorldGen.WaterCheck () inline static
Definition at line 81077 of file WorldGen.cs.
        {
            Liquid.tilesIgnoreWater(true);
            Liquid.numLiquid = 0;
            LiquidBuffer.numLiquidBuffer = 0;
            for (int i = 1; i < Main.maxTilesX - 1; i++)
            {
                for (int j = Main.maxTilesY - 2; j > 0; j--)
                {
                    Tile tile = Main.tile[i, j];
                    tile.checkingLiquid(false);
                    if (tile.liquid > 0 && tile.nactive() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
                    {
                        if (tile.type != 379)
{
                            tile.liquid = 0;
                        }
                    }
                    else if (tile.liquid > 0)
                    {
                        if (tile.active())
{
                            if (tile.lava())
{
                                if (TileObjectData.CheckLavaDeath(tile))
{
                                    WorldGen.KillTile(i, j, false, false, false);
                                }
                            }
                            else if (TileObjectData.CheckWaterDeath(tile))
{
                                WorldGen.KillTile(i, j, false, false, false);
                            }
                        }
                        Tile tile2 = Main.tile[i, j + 1];
                        if ((!tile2.nactive() || !Main.tileSolid[(int)tile2.type] || Main.tileSolidTop[(int)tile2.type]) && tile2.liquid < 255)
{
                            if (tile2.liquid > 250)
{
                                tile2.liquid = byte.MaxValue;
                            }
                            else
{
                                Liquid.AddWater(i, j);
                            }
                        }
                        Tile tile3 = Main.tile[i - 1, j];
                        Tile tile4 = Main.tile[i + 1, j];
                        if ((!tile3.nactive() || !Main.tileSolid[(int)tile3.type] || Main.tileSolidTop[(int)tile3.type]) && tile3.liquid != tile.liquid)
{
                            Liquid.AddWater(i, j);
                        }
                        else if ((!tile4.nactive() || !Main.tileSolid[(int)tile4.type] || Main.tileSolidTop[(int)tile4.type]) && tile4.liquid != tile.liquid)
{
                            Liquid.AddWater(i, j);
                        }
                        if (tile.lava())
{
                            if (tile3.liquid > 0 && !tile3.lava())
{
                                Liquid.AddWater(i, j);
                            }
                            else if (tile4.liquid > 0 && !tile4.lava())
{
                                Liquid.AddWater(i, j);
                            }
                            else if (Main.tile[i, j - 1].liquid > 0 && !Main.tile[i, j - 1].lava())
{
                                Liquid.AddWater(i, j);
                            }
                            else if (tile2.liquid > 0 && !tile2.lava())
{
                                Liquid.AddWater(i, j);
                            }
                        }
                    }
                }
            }
            Liquid.tilesIgnoreWater(false);
        }
References Terraria.Tile.active(), Terraria.Liquid.AddWater(), Terraria.Tile.checkingLiquid(), Terraria.ObjectData.TileObjectData.CheckLavaDeath(), Terraria.ObjectData.TileObjectData.CheckWaterDeath(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Liquid.tilesIgnoreWater(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.Liquid.UpdateLiquid().