Terraria Decompiled: Terraria.WorldGen.oceanCave
oceanCave()
static void Terraria.WorldGen.oceanCave (int i, int j) inline static
Definition at line 77010 of file WorldGen.cs.
        {
            if (GenVars.numOceanCaveTreasure >= GenVars.maxOceanCaveTreasure)
            {
                GenVars.numOceanCaveTreasure = 0;
            }
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            if (i < Main.maxTilesX / 2)
            {
                vector2D2.X = 0.25 + WorldGen.genRand.NextDouble() * 0.25;
            }
            else
            {
                vector2D2.X = -0.35 - WorldGen.genRand.NextDouble() * 0.5;
            }
            vector2D2.Y = 0.4 + WorldGen.genRand.NextDouble() * 0.25;
            ushort num = 264;
            ushort num2 = 53;
            ushort num3 = 397;
            double num4 = (double)WorldGen.genRand.Next(17, 25);
            double num5 = (double)WorldGen.genRand.Next(600, 800);
            double num6 = 4.0;
            bool flag = true;
            bool flag2 = false;
            while (num4 > num6 && num5 > 0.0)
            {
                bool flag3 = true;
                bool flag4 = true;
                bool flag5 = true;
                if (flag2 || (vector2D.X > (double)(WorldGen.beachDistance - 50) && vector2D.X < (double)(Main.maxTilesX - WorldGen.beachDistance + 50)))
                {
                    num4 *= 0.96;
                    num5 *= 0.96;
                }
                if (num4 < num6 + 2.0 || num5 < 20.0)
                {
                    flag5 = false;
                }
                if (flag)
                {
                    num4 -= 0.01 + WorldGen.genRand.NextDouble() * 0.01;
                    num5 -= 0.5;
                }
                else
                {
                    num4 -= 0.02 + WorldGen.genRand.NextDouble() * 0.02;
                    num5 -= 1.0;
                }
                if (flag5)
                {
                    GenVars.oceanCaveTreasure[GenVars.numOceanCaveTreasure].X = (int)vector2D.X;
                    GenVars.oceanCaveTreasure[GenVars.numOceanCaveTreasure].Y = (int)vector2D.Y;
                }
                int num7 = (int)(vector2D.X - num4 * 3.0);
                int num8 = (int)(vector2D.X + num4 * 3.0);
                int num9 = (int)(vector2D.Y - num4 * 3.0);
                int num10 = (int)(vector2D.Y + num4 * 3.0);
                if (num7 < 1)
                {
                    num7 = 1;
                }
                if (num8 > Main.maxTilesX - 1)
                {
                    num8 = Main.maxTilesX - 1;
                }
                if (num9 < 1)
                {
                    num9 = 1;
                }
                if (num10 > Main.maxTilesY - 1)
                {
                    num10 = Main.maxTilesY - 1;
                }
                for (int k = num7; k < num8; k++)
                {
                    for (int l = num9; l < num10; l++)
                    {
                        if (!flag2 && WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.InAnyPotentialDungeonBounds(k, l, 5, false))
{
                            flag2 = true;
                        }
                        if (!WorldGen.badOceanCaveTiles(k, l))
{
                            double num11 = new Vector2D(Math.Abs((double)k - vector2D.X), Math.Abs((double)l - vector2D.Y)).Length();
                            if (flag5 && num11 < num4 * 0.5 + 1.0)
{
                                Main.tile[k, l].type = num;
                                Main.tile[k, l].active(false);
                            }
                            else if (num11 < num4 * 1.5 + 1.0 && Main.tile[k, l].type != num)
{
                                if ((double)l < vector2D.Y)
{
                                    if ((vector2D2.X < 0.0 && (double)k < vector2D.X) || (vector2D2.X > 0.0 && (double)k > vector2D.X))
{
                                        if (num11 < num4 * 1.1 + 1.0)
{
                                            Main.tile[k, l].type = num3;
                                            if (Main.tile[k, l].liquid == 255)
{
                                                Main.tile[k, l].wall = 0;
                                            }
                                        }
                                        else if (Main.tile[k, l].type != num3)
{
                                            Main.tile[k, l].type = num2;
                                        }
                                    }
                                }
                                else if ((vector2D2.X < 0.0 && k < i) || (vector2D2.X > 0.0 && k > i))
{
                                    if (Main.tile[k, l].liquid == 255)
{
                                        Main.tile[k, l].wall = 0;
                                    }
                                    Main.tile[k, l].type = num2;
                                    Main.tile[k, l].active(true);
                                    if (k == (int)vector2D.X && flag3)
{
                                        flag3 = false;
                                        int num12 = 50 + WorldGen.genRand.Next(3);
                                        int num13 = 43 + WorldGen.genRand.Next(3);
                                        int num14 = 20 + WorldGen.genRand.Next(3);
                                        int num15 = k;
                                        int num16 = k + num14;
                                        if (vector2D2.X < 0.0)
{
                                            num15 = k - num14;
                                            num16 = k;
                                        }
                                        if (num5 < 100.0)
{
                                            num12 = (int)((double)num12 * (num5 / 100.0));
                                            num13 = (int)((double)num13 * (num5 / 100.0));
                                            num14 = (int)((double)num14 * (num5 / 100.0));
                                        }
                                        if (num4 < num6 + 5.0)
{
                                            double num17 = (num4 - num6) / 5.0;
                                            num12 = (int)((double)num12 * num17);
                                            num13 = (int)((double)num13 * num17);
                                            num14 = (int)((double)num14 * num17);
                                        }
                                        for (int m = num15; m <= num16; m++)
{
                                            int num18 = l;
                                            while (num18 < l + num12 && !WorldGen.badOceanCaveTiles(m, num18))
{
                                                if (num18 > l + num13)
{
                                                    if (WorldGen.SolidTile(m, num18, false) && Main.tile[m, num18].type != num2)
{
                                                        break;
                                                    }
                                                    Main.tile[m, num18].type = num3;
                                                }
                                                else
{
                                                    Main.tile[m, num18].type = num2;
                                                }
                                                Main.tile[m, num18].active(true);
                                                if (WorldGen.genRand.Next(3) == 0)
{
                                                    Main.tile[m - 1, num18].type = num2;
                                                    Main.tile[m - 1, num18].active(true);
                                                }
                                                if (WorldGen.genRand.Next(3) == 0)
{
                                                    Main.tile[m + 1, num18].type = num2;
                                                    Main.tile[m + 1, num18].active(true);
                                                }
                                                num18++;
                                            }
                                        }
                                    }
                                }
                            }
                            if (num11 < num4 * 1.3 + 1.0 && l > j - 10)
{
                                Main.tile[k, l].liquid = byte.MaxValue;
                                Main.tile[k, l].liquidType(0);
                            }
                            if (flag4 && k == (int)vector2D.X && (double)l > vector2D.Y)
{
                                flag4 = false;
                                int num19 = 100;
                                int num20 = 2;
                                for (int n = k - num20; n <= k + num20; n++)
{
                                    for (int num21 = l; num21 < l + num19; num21++)
{
                                        if (!WorldGen.badOceanCaveTiles(n, num21))
{
                                            Main.tile[n, num21].liquid = byte.MaxValue;
                                            Main.tile[n, num21].liquidType(0);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += WorldGen.genRand.NextDouble() * 0.1 - 0.05;
                vector2D2.Y += WorldGen.genRand.NextDouble() * 0.1 - 0.05;
                if (flag)
                {
                    if (vector2D.Y > (Main.worldSurface * 2.0 + Main.rockLayer) / 3.0 && vector2D.Y > (double)(j + 30))
                    {
                        flag = false;
                    }
                    vector2D2.Y = Utils.Clamp<double>(vector2D2.Y, 0.35, 1.0);
                }
                else
                {
                    if (vector2D.X < (double)(Main.maxTilesX / 2))
                    {
                        if (vector2D2.X < 0.5)
{
                            vector2D2.X += 0.02;
                        }
                    }
                    else if (vector2D2.X > -0.5)
                    {
                        vector2D2.X -= 0.02;
                    }
                    if (!flag5)
                    {
                        if (vector2D2.Y < 0.0)
{
                            vector2D2.Y *= 0.95;
                        }
                        vector2D2.Y += 0.04;
                    }
                    else if (vector2D.Y < (Main.worldSurface * 4.0 + Main.rockLayer) / 5.0)
                    {
                        if (vector2D2.Y < 0.0)
{
                            vector2D2.Y *= 0.97;
                        }
                        vector2D2.Y += 0.02;
                    }
                    else if (vector2D2.Y > -0.1)
                    {
                        vector2D2.Y *= 0.99;
                        vector2D2.Y -= 0.01;
                    }
                    vector2D2.Y = Utils.Clamp<double>(vector2D2.Y, -1.0, 1.0);
                }
                if (vector2D.X < (double)(Main.maxTilesX / 2))
                {
                    vector2D2.X = Utils.Clamp<double>(vector2D2.X, 0.1, 1.0);
                }
                else
                {
                    vector2D2.X = Utils.Clamp<double>(vector2D2.X, -1.0, -0.1);
                }
            }
            GenVars.numOceanCaveTreasure++;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.badOceanCaveTiles(), Terraria.WorldGen.beachDistance, Terraria.Utils.Clamp(), Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonUtils.InAnyPotentialDungeonBounds(), int, ReLogic.Utilities.Vector2D.Length(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.WorldBuilding.GenVars.maxOceanCaveTreasure, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldBuilding.GenVars.numOceanCaveTreasure, Terraria.WorldBuilding.GenVars.oceanCaveTreasure, Terraria.Main.rockLayer, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, ReLogic.Utilities.Vector2D.X, Microsoft.Xna.Framework.Point.Y, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().