Terraria Decompiled: Terraria.WorldGen.GrowLivingTreePassageRoom
GrowLivingTreePassageRoom()
static void Terraria.WorldGen.GrowLivingTreePassageRoom (int minl, int minr, int Y) inline static private
Definition at line 26345 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(2);
            if (num == 0)
            {
                num = -1;
            }
            int num2 = Y - 2;
            int num3 = (minl + minr) / 2;
            if (num < 0)
            {
                num3--;
            }
            if (num > 0)
            {
                num3++;
            }
            int num4 = WorldGen.genRand.Next(15, 30);
            int num5 = num3 + num4;
            if (num < 0)
            {
                num5 = num3;
                num3 -= num4;
            }
            for (int i = num3; i < num5; i++)
            {
                for (int j = Y - 20; j < Y + 10; j++)
                {
                    if (Main.tile[i, j].wall == 0 && !Main.tile[i, j].active() && (double)j < Main.worldSurface)
                    {
                        return;
                    }
                }
            }
            int num6;
            if (WorldGen.SecretSeed.dualDungeons.Enabled && DungeonUtils.IntersectsAnyPotentialDungeonBounds(out num6, new Rectangle(num3, Y - 20, num5, Y + 10), false))
            {
                return;
            }
            for (int k = num3; k <= num5; k++)
            {
                for (int l = num2 - 2; l <= Y + 2; l++)
                {
                    if (Main.tile[k - 1, l].type == 40)
                    {
                        Main.tile[k - 1, l].type = 0;
                    }
                    if (Main.tile[k + 1, l].type == 40)
                    {
                        Main.tile[k + 1, l].type = 0;
                    }
                    if (Main.tile[k, l - 1].type == 40)
                    {
                        Main.tile[k, l - 1].type = 0;
                    }
                    if (Main.tile[k, l + 1].type == 40)
                    {
                        Main.tile[k, l + 1].type = 0;
                    }
                    if (Main.tile[k, l].wall != 244 && Main.tile[k, l].type != 19)
                    {
                        Main.tile[k, l].active(true);
                        Main.tile[k, l].type = 191;
                        Main.tile[k, l].halfBrick(false);
                    }
                    if (l >= num2 && l <= Y)
                    {
                        Main.tile[k, l].liquid = 0;
                        Main.tile[k, l].wall = 244;
                        Main.tile[k, l].active(false);
                    }
                }
            }
            int num7 = (minl + minr) / 2 + 3 * num;
            WorldGen.PlaceTile(num7, Y, 10, true, false, -1, 7);
            int num8 = WorldGen.genRand.Next(5, 9);
            int num9 = WorldGen.genRand.Next(4, 6);
            if (num < 0)
            {
                num5 = num3 + num8;
                num3 -= num8;
            }
            else
            {
                num3 = num5 - num8;
                num5 += num8;
            }
            num2 = Y - num9;
            for (int m = num3 - 2; m <= num5 + 2; m++)
            {
                for (int n = num2 - 2; n <= Y + 2; n++)
                {
                    if (Main.tile[m - 1, n].type == 40)
                    {
                        Main.tile[m - 1, n].type = 40;
                    }
                    if (Main.tile[m + 1, n].type == 40)
                    {
                        Main.tile[m + 1, n].type = 40;
                    }
                    if (Main.tile[m, n - 1].type == 40)
                    {
                        Main.tile[m, n - 1].type = 40;
                    }
                    if (Main.tile[m, n + 1].type == 40)
                    {
                        Main.tile[m, n + 1].type = 40;
                    }
                    if (Main.tile[m, n].wall != 244 && Main.tile[m, n].type != 19)
                    {
                        Main.tile[m, n].active(true);
                        Main.tile[m, n].type = 191;
                        Main.tile[m, n].halfBrick(false);
                    }
                    if (n >= num2 && n <= Y && m >= num3 && m <= num5)
                    {
                        Main.tile[m, n].liquid = 0;
                        Main.tile[m, n].wall = 244;
                        Main.tile[m, n].active(false);
                    }
                }
            }
            num7 = num3 - 2;
            if (num < 0)
            {
                num7 = num5 + 2;
            }
            WorldGen.PlaceTile(num7, Y, 10, true, false, -1, 7);
            int num10 = num5;
            if (num < 0)
            {
                num10 = num3;
            }
            int num11 = 2;
            if (WorldGen.genRand.Next(num11) == 0)
            {
                num11 += 2;
                WorldGen.PlaceTile(num10, Y, 15, true, false, -1, 5);
                if (num < 0)
                {
                    Tile tile = Main.tile[num10, Y - 1];
                    tile.frameX += 18;
                    Tile tile2 = Main.tile[num10, Y];
                    tile2.frameX += 18;
                }
            }
            num10 = num5 - 2;
            if (num < 0)
            {
                num10 = num3 + 2;
            }
            WorldGen.PlaceTile(num10, Y, 304, true, false, -1, 0);
            num10 = num5 - 4;
            if (num < 0)
            {
                num10 = num3 + 4;
            }
            if (WorldGen.genRand.Next(num11) == 0)
            {
                WorldGen.PlaceTile(num10, Y, 15, true, false, -1, 5);
                if (num > 0)
                {
                    Tile tile3 = Main.tile[num10, Y - 1];
                    tile3.frameX += 18;
                    Tile tile4 = Main.tile[num10, Y];
                    tile4.frameX += 18;
                }
            }
            num10 = num5 - 7;
            if (num < 0)
            {
                num10 = num3 + 8;
            }
            int num12 = 832;
            if (WorldGen.genRand.Next(3) == 0)
            {
                num12 = 4281;
            }
            if (!WorldGen.remixWorldGen)
            {
                WorldGen.AddBuriedChest(num10, Y, num12, false, 12, false, 0);
                return;
            }
            int num13 = WorldGen.genRand.Next(1, 3);
            for (int num14 = 0; num14 < num13; num14++)
            {
                bool flag = false;
                int num15 = 1000;
                while (!flag)
                {
                    num15--;
                    if (num15 <= 0)
                    {
                        break;
                    }
                    int num16 = WorldGen.genRand.Next(Main.maxTilesX / 8, Main.maxTilesX - Main.maxTilesX / 8);
                    int num17 = WorldGen.genRand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                    if (!WorldGen.IsTileNearby(num16, num17, 53, 20) && !WorldGen.IsTileNearby(num16, num17, 147, 20) && !WorldGen.IsTileNearby(num16, num17, 59, 20))
                    {
                        flag = WorldGen.AddBuriedChest(num16, num17, num12, false, 12, false, 0);
                    }
                }
            }
            if (WorldGen.crimson)
            {
                WorldGen.AddBuriedChest(num10, Y, 0, false, 14, false, 0);
                return;
            }
            WorldGen.AddBuriedChest(num10, Y, 0, false, 7, false, 0);
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.crimson, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IntersectsAnyPotentialDungeonBounds(), Terraria.WorldGen.IsTileNearby(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, and System.Y.
Referenced by Terraria.WorldGen.GrowLivingTree_MakePassage().