Terraria Decompiled: Terraria.WorldGen.TileFrameImportant
TileFrameImportant()
static void Terraria.WorldGen.TileFrameImportant (int i, int j, int type, Tile tileCache, bool resetFrame) inline static private
Definition at line 85762 of file WorldGen.cs.
        {
            if (type == 518)
            {
                WorldGen.CheckLilyPad(i, j);
                return;
            }
            if (type == 519)
            {
                WorldGen.CheckCatTail(i, j);
                return;
            }
            if (type == 549)
            {
                WorldGen.CheckUnderwaterPlant(549, i, j);
                return;
            }
            if (type == 571)
            {
                WorldGen.CheckBamboo(i, j);
                return;
            }
            if (TileID.Sets.Torches[type])
            {
                WorldGen.CheckTorch(i, j);
                return;
            }
            if (type == 442)
            {
                WorldGen.CheckProjectilePressurePad(i, j);
                return;
            }
            if (type == 136)
            {
                Tile tile = Main.tile[i, j - 1];
                Tile tile2 = Main.tile[i, j + 1];
                Tile tile3 = Main.tile[i - 1, j];
                Tile tile4 = Main.tile[i + 1, j];
                Tile tile5 = Main.tile[i - 1, j + 1];
                Tile tile6 = Main.tile[i + 1, j + 1];
                Tile tile7 = Main.tile[i - 1, j - 1];
                Tile tile8 = Main.tile[i + 1, j - 1];
                int num = -1;
                int num2 = -1;
                int num3 = -1;
                int num4 = -1;
                int num5 = -1;
                int num6 = -1;
                int num7 = -1;
                if (tile != null && tile.nactive())
                {
                    ushort type2 = tile.type;
                }
                if (tile2 != null && tile2.nactive() && !tile2.halfBrick() && !tile2.topSlope())
                {
                    num = (int)tile2.type;
                }
                if (tile3 != null && tile3.nactive())
                {
                    num2 = (int)tile3.type;
                }
                if (tile4 != null && tile4.nactive())
                {
                    num3 = (int)tile4.type;
                }
                if (tile5 != null && tile5.nactive())
                {
                    num4 = (int)tile5.type;
                }
                if (tile6 != null && tile6.nactive())
                {
                    num5 = (int)tile6.type;
                }
                if (tile7 != null && tile7.nactive())
                {
                    num6 = (int)tile7.type;
                }
                if (tile8 != null && tile8.nactive())
                {
                    num7 = (int)tile8.type;
                }
                if (num >= 0 && Main.tileSolid[num] && !Main.tileNoAttach[num] && tile2 != null && !tile2.halfBrick() && (tile2.slope() == 0 || tile2.bottomSlope()))
                {
                    tileCache.frameX = 0;
                    return;
                }
                if ((num2 >= 0 && Main.tileSolid[num2] && !Main.tileNoAttach[num2] && tile3 != null && (tile3.leftSlope() || tile3.slope() == 0) && !tile3.halfBrick()) || (num2 >= 0 && TileID.Sets.IsBeam[num2]) || (WorldGen.IsTreeType(num2) && WorldGen.IsTreeType(num6) && WorldGen.IsTreeType(num4)))
                {
                    tileCache.frameX = 18;
                    return;
                }
                if ((num3 >= 0 && Main.tileSolid[num3] && !Main.tileNoAttach[num3] && tile4 != null && (tile4.rightSlope() || tile4.slope() == 0) && !tile4.halfBrick()) || (num3 >= 0 && TileID.Sets.IsBeam[num3]) || (WorldGen.IsTreeType(num3) && WorldGen.IsTreeType(num7) && WorldGen.IsTreeType(num5)))
                {
                    tileCache.frameX = 36;
                    return;
                }
                if (tileCache.wall > 0)
                {
                    tileCache.frameX = 54;
                    return;
                }
                WorldGen.KillTile(i, j, false, false, false);
                return;
            }
            else
            {
                if (type != 129 && type != 149)
                {
                    if (TileID.Sets.IsADripTile[type])
                    {
                        Tile tile9 = Main.tile[i, j - 1];
                        if (tile9 == null || !tile9.active() || tile9.bottomSlope() || !Main.tileSolid[(int)tile9.type] || Main.tileSolidTop[(int)tile9.type])
{
                            WorldGen.KillTile(i, j, false, false, false);
                            return;
                        }
                    }
                    else if (type == 178)
                    {
                        int frameY = (int)tileCache.frameY;
                        int num8 = 0;
                        if (!WorldGen.CheckAndAdjustMultiDirectionalTile(i, j, type, out num8))
{
                            WorldGen.KillTile(i, j, false, false, false);
                            return;
                        }
                        int num9 = ((!resetFrame) ? ((int)(tileCache.frameY % 54)) : (WorldGen.genRand.Next(3) * 18));
                        int num10 = -1;
                        switch (num8)
{
                        case 0:
                            if (frameY < 0 || frameY > 36)
{
                                num10 = 0;
                            }
                            break;
                        case 1:
                            if (frameY < 54 || frameY > 90)
{
                                num10 = 54;
                            }
                            break;
                        case 2:
                            if (frameY < 108 || frameY > 144)
{
                                num10 = 108;
                            }
                            break;
                        case 3:
                            if (frameY < 162 || frameY > 198)
{
                                num10 = 162;
                            }
                            break;
                        }
                        if (num10 > -1)
{
                            tileCache.frameY = (short)(num10 + num9);
                            return;
                        }
                    }
                    else if (type == 184)
                    {
                        Tile tile10 = Main.tile[i, j - 1];
                        Tile tile11 = Main.tile[i, j + 1];
                        Tile tile12 = Main.tile[i - 1, j];
                        Tile tile13 = Main.tile[i + 1, j];
                        int num11 = -1;
                        int num12 = -1;
                        int num13 = -1;
                        int num14 = -1;
                        if (tile10 != null && tile10.active() && !tile10.bottomSlope())
{
                            num12 = (int)tile10.type;
                        }
                        if (tile11 != null && tile11.active() && !tile11.halfBrick() && !tile11.topSlope())
{
                            num11 = (int)tile11.type;
                        }
                        if (tile12 != null && tile12.active())
{
                            num13 = (int)tile12.type;
                        }
                        if (tile13 != null && tile13.active())
{
                            num14 = (int)tile13.type;
                        }
                        short num15 = (short)(WorldGen.genRand.Next(3) * 18);
                        if (num11 >= 0 && WorldGen.GetTileMossColor(num11) != -1)
{
                            tileCache.frameX = (short)(22 * WorldGen.GetTileMossColor(num11));
                            if (tileCache.frameY < 0 || tileCache.frameY > 36)
{
                                tileCache.frameY = num15;
                                return;
                            }
                        }
                        else if (num12 >= 0 && WorldGen.GetTileMossColor(num12) != -1)
{
                            tileCache.frameX = (short)(22 * WorldGen.GetTileMossColor(num12));
                            if (tileCache.frameY < 54 || tileCache.frameY > 90)
{
                                tileCache.frameY = 54 + num15;
                                return;
                            }
                        }
                        else if (num13 >= 0 && WorldGen.GetTileMossColor(num13) != -1)
{
                            tileCache.frameX = (short)(22 * WorldGen.GetTileMossColor(num13));
                            if (tileCache.frameY < 108 || tileCache.frameY > 144)
{
                                tileCache.frameY = 108 + num15;
                                return;
                            }
                        }
                        else
{
                            if (num14 < 0 || WorldGen.GetTileMossColor(num14) == -1)
{
                                WorldGen.KillTile(i, j, false, false, false);
                                return;
                            }
                            tileCache.frameX = (short)(22 * WorldGen.GetTileMossColor(num14));
                            if (tileCache.frameY < 162 || tileCache.frameY > 198)
{
                                tileCache.frameY = 162 + num15;
                                return;
                            }
                        }
                    }
                    else if (type == 529)
                    {
                        if (!WorldGen.SolidTileAllowBottomSlope(i, j + 1))
{
                            WorldGen.KillTile(i, j, false, false, false);
                            return;
                        }
                        Tile tile14 = Main.tile[i, j + 1];
                        short num16 = Main.tile[i, j].frameY / 34;
                        if (tile14 == null || !tile14.active() || (tile14.type >= 0 && tile14.type < TileID.Count && !TileID.Sets.Conversion.Sand[(int)tile14.type]))
{
                            WorldGen.KillTile(i, j, false, false, false);
                            return;
                        }
                    }
                    else
                    {
                        if (type == 3 || type == 24 || type == 61 || type == 703 || type == 71 || type == 73 || type == 74 || type == 110 || type == 113 || type == 201 || type == 637)
{
                            WorldGen.PlantCheck(i, j);
                            return;
                        }
                        if (type == 227)
{
                            WorldGen.CheckDye(i, j);
                            return;
                        }
                        if (type == 579)
{
                            WorldGen.CheckRockGolemHead(i, j);
                            return;
                        }
                        if (type == 12 || type == 31 || type == 639 || type == 696)
{
                            WorldGen.CheckOrb(i, j, type);
                            return;
                        }
                        if (type == 165)
{
                            WorldGen.CheckStalactite(i, j);
                            return;
                        }
                        if (type == 693 || type == 694)
{
                            WorldGen.CheckStalactiteEcho(i, j);
                            return;
                        }
                        if (type == 324)
{
                            if (!WorldGen.SolidTileAllowBottomSlope(i, j + 1))
{
                                WorldGen.KillTile(i, j, false, false, false);
                            }
                            if (WorldGen.InvalidTileForPilesOrSpeleothems(i, j + 1))
{
                                WorldGen.KillTile(i, j, false, false, false);
                                return;
                            }
                        }
                        else
{
                            if (type == 235)
{
                                WorldGen.Check3x1(i, j, type);
                                return;
                            }
                            if (type == 185)
{
                                WorldGen.CheckPile(i, j);
                                return;
                            }
                            if ((type >= 275 && type <= 281) || type == 296 || type == 297 || type == 309 || type == 358 || type == 359 || type == 413 || type == 414 || type == 542 || type == 550 || type == 551 || type == 553 || type == 554 || type == 558 || type == 559 || type == 599 || type == 600 || type == 601 || type == 602 || type == 603 || type == 604 || type == 605 || type == 606 || type == 607 || type == 608 || type == 609 || type == 610 || type == 611 || type == 612 || type == 632 || type == 640 || type == 643 || type == 644 || type == 645 || type == 710)
{
                                WorldGen.Check6x3(i, j, type);
                                return;
                            }
                            if (type == 10)
{
                                WorldGen.CheckDoorClosed(i, j, tileCache, type);
                                return;
                            }
                            if (type == 11)
{
                                WorldGen.CheckDoorOpen(i, j, tileCache);
                                return;
                            }
                            if (type == 314)
{
                                Minecart.FrameTrack(i, j, false, false);
                                WorldGen.HandleRopeEndFraming(i, j);
                                return;
                            }
                            if (type == 380)
{
                                Tile tile15 = Main.tile[i, j - 1];
                                if (tile15 == null)
{
                                    return;
                                }
                                Tile tile16 = Main.tile[i, j + 1];
                                if (tile16 == null)
{
                                    return;
                                }
                                Tile tile17 = Main.tile[i - 1, j];
                                if (tile17 == null)
{
                                    return;
                                }
                                Tile tile18 = Main.tile[i + 1, j];
                                if (tile18 == null)
{
                                    return;
                                }
                                Tile tile19 = Main.tile[i - 1, j + 1];
                                if (tile19 == null)
{
                                    return;
                                }
                                Tile tile20 = Main.tile[i + 1, j + 1];
                                if (tile20 == null)
{
                                    return;
                                }
                                Tile tile21 = Main.tile[i - 1, j - 1];
                                if (tile21 == null)
{
                                    return;
                                }
                                Tile tile22 = Main.tile[i + 1, j - 1];
                                if (tile22 == null)
{
                                    return;
                                }
                                WorldGen.TileMergeCullCache tileMergeCulling = WorldGen.GetTileMergeCulling(tileCache, tile15, tile16, tile17, tile18, tile19, tile20, tile21, tile22);
                                int num17 = -1;
                                int num18 = -1;
                                if (tile17 != null && tile17.active())
{
                                    if (Main.tileStone[(int)tile17.type])
{
                                        num18 = 1;
                                    }
                                    else
{
                                        num18 = (int)tile17.type;
                                    }
                                }
                                if (tile18 != null && tile18.active())
{
                                    if (Main.tileStone[(int)tile18.type])
{
                                        num17 = 1;
                                    }
                                    else
{
                                        num17 = (int)tile18.type;
                                    }
                                }
                                if (num17 >= 0 && tileMergeCulling.CullRight)
{
                                    num17 = -1;
                                }
                                if (num18 >= 0 && tileMergeCulling.CullLeft)
{
                                    num18 = -1;
                                }
                                if (num17 >= 0 && !Main.tileSolid[num17])
{
                                    num17 = -1;
                                }
                                if (num18 >= 0 && !Main.tileSolid[num18])
{
                                    num18 = -1;
                                }
                                int num19;
                                if (num18 == type && num17 == type)
{
                                    num19 = 18;
                                }
                                else if (num18 == type && num17 != type)
{
                                    num19 = 36;
                                }
                                else if (num18 != type && num17 == type)
{
                                    num19 = 0;
                                }
                                else
{
                                    num19 = 54;
                                }
                                tileCache.frameX = (short)num19;
                                WorldGen.HandleRopeEndFraming(i, j);
                                return;
                            }
                            else if (type >= 0 && TileID.Sets.Platforms[type])
{
                                Tile tile23 = Main.tile[i, j - 1];
                                if (tile23 == null)
{
                                    return;
                                }
                                Tile tile24 = Main.tile[i, j + 1];
                                if (tile24 == null)
{
                                    return;
                                }
                                Tile tile25 = Main.tile[i - 1, j];
                                if (tile25 == null)
{
                                    return;
                                }
                                Tile tile26 = Main.tile[i + 1, j];
                                if (tile26 == null)
{
                                    return;
                                }
                                Tile tile27 = Main.tile[i - 1, j + 1];
                                if (tile27 == null)
{
                                    return;
                                }
                                Tile tile28 = Main.tile[i + 1, j + 1];
                                if (tile28 == null)
{
                                    return;
                                }
                                Tile tile29 = Main.tile[i - 1, j - 1];
                                if (tile29 == null)
{
                                    return;
                                }
                                Tile tile30 = Main.tile[i + 1, j - 1];
                                if (tile30 == null)
{
                                    return;
                                }
                                WorldGen.TileMergeCullCache tileMergeCulling2 = WorldGen.GetTileMergeCulling(tileCache, tile23, tile24, tile25, tile26, tile27, tile28, tile29, tile30);
                                int num20 = -1;
                                int num21 = -1;
                                if (tile25 != null && tile25.active())
{
                                    if (Main.tileStone[(int)tile25.type])
{
                                        num21 = 1;
                                    }
                                    else if (TileID.Sets.Platforms[(int)tile25.type])
{
                                        num21 = type;
                                    }
                                    else
{
                                        num21 = (int)tile25.type;
                                    }
                                }
                                if (tile26 != null && tile26.active())
{
                                    if (Main.tileStone[(int)tile26.type])
{
                                        num20 = 1;
                                    }
                                    else if (TileID.Sets.Platforms[(int)tile26.type])
{
                                        num20 = type;
                                    }
                                    else
{
                                        num20 = (int)tile26.type;
                                    }
                                }
                                if (num20 >= 0 && tileMergeCulling2.CullRight)
{
                                    num20 = -1;
                                }
                                if (num21 >= 0 && tileMergeCulling2.CullLeft)
{
                                    num21 = -1;
                                }
                                if (num20 >= 0 && !Main.tileSolid[num20])
{
                                    num20 = -1;
                                }
                                if (num21 >= 0 && !Main.tileSolid[num21])
{
                                    num21 = -1;
                                }
                                if (num21 == type && tile25.halfBrick() != tileCache.halfBrick())
{
                                    num21 = -1;
                                }
                                if (num20 == type && tile26.halfBrick() != tileCache.halfBrick())
{
                                    num20 = -1;
                                }
                                if (num21 != -1 && num21 != type && tileCache.halfBrick())
{
                                    num21 = -1;
                                }
                                if (num20 != -1 && num20 != type && tileCache.halfBrick())
{
                                    num20 = -1;
                                }
                                if (num21 == -1 && tile29.active() && (int)tile29.type == type && tile29.slope() == 1 && !tileMergeCulling2.CullTopLeft)
{
                                    num21 = type;
                                }
                                if (num20 == -1 && tile30.active() && (int)tile30.type == type && tile30.slope() == 2 && !tileMergeCulling2.CullTopRight)
{
                                    num20 = type;
                                }
                                if (num21 == type && tile25.slope() == 2 && num20 != type)
{
                                    num20 = -1;
                                }
                                if (num20 == type && tile26.slope() == 1 && num21 != type)
{
                                    num21 = -1;
                                }
                                bool flag = WorldGen.ForbidsSloping(i, j - 1);
                                int num22;
                                if (tileCache.slope() == 1)
{
                                    if (TileID.Sets.Platforms[(int)tile26.type] && tile26.slope() == 0 && !tile26.halfBrick() && !tileMergeCulling2.CullRight)
{
                                        num22 = 468;
                                    }
                                    else if (flag)
{
                                        num22 = 468;
                                    }
                                    else if ((!tile28.active() || tileMergeCulling2.CullBottomRight) && (!TileID.Sets.Platforms[(int)tile28.type] || tile28.slope() == 2 || tileMergeCulling2.CullBottomRight))
{
                                        if ((!tile25.active() || tileMergeCulling2.CullLeft) && (!TileID.Sets.Platforms[(int)tile29.type] || tile29.slope() != 1 || tileMergeCulling2.CullTopLeft))
{
                                            num22 = 432;
                                        }
                                        else
{
                                            num22 = 360;
                                        }
                                    }
                                    else if ((!tile25.active() || tileMergeCulling2.CullLeft) && (!TileID.Sets.Platforms[(int)tile29.type] || tile29.slope() != 1 || tileMergeCulling2.CullTopLeft))
{
                                        num22 = 396;
                                    }
                                    else
{
                                        num22 = 180;
                                    }
                                }
                                else if (tileCache.slope() == 2)
{
                                    if (TileID.Sets.Platforms[(int)tile25.type] && tile25.slope() == 0 && !tile25.halfBrick() && !tileMergeCulling2.CullLeft)
{
                                        num22 = 450;
                                    }
                                    else if (flag)
{
                                        num22 = 450;
                                    }
                                    else if ((!tile27.active() || tileMergeCulling2.CullBottomLeft) && (!TileID.Sets.Platforms[(int)tile27.type] || tile27.slope() == 1 || tileMergeCulling2.CullBottomLeft))
{
                                        if ((!tile26.active() || tileMergeCulling2.CullRight) && (!TileID.Sets.Platforms[(int)tile30.type] || tile30.slope() != 2 || tileMergeCulling2.CullTopRight))
{
                                            num22 = 414;
                                        }
                                        else
{
                                            num22 = 342;
                                        }
                                    }
                                    else if ((!tile26.active() || tileMergeCulling2.CullRight) && (!TileID.Sets.Platforms[(int)tile30.type] || tile30.slope() != 2 || tileMergeCulling2.CullTopRight))
{
                                        num22 = 378;
                                    }
                                    else
{
                                        num22 = 144;
                                    }
                                }
                                else if (num21 == type && num20 == type)
{
                                    if (tile25.slope() == 2 && tile26.slope() == 1)
{
                                        num22 = 252;
                                    }
                                    else if (tile25.slope() == 2)
{
                                        num22 = 216;
                                    }
                                    else if (tile26.slope() == 1)
{
                                        num22 = 234;
                                    }
                                    else
{
                                        num22 = 0;
                                    }
                                }
                                else if (num21 == type && num20 == -1)
{
                                    if (tile25.slope() == 2)
{
                                        num22 = 270;
                                    }
                                    else
{
                                        num22 = 18;
                                    }
                                }
                                else if (num21 == -1 && num20 == type)
{
                                    if (tile26.slope() == 1)
{
                                        num22 = 288;
                                    }
                                    else
{
                                        num22 = 36;
                                    }
                                }
                                else if (num21 != type && num20 == type)
{
                                    num22 = 54;
                                }
                                else if (num21 == type && num20 != type)
{
                                    num22 = 72;
                                }
                                else if (num21 != type && num21 != -1 && num20 == -1)
{
                                    num22 = 108;
                                }
                                else if (num21 == -1 && num20 != type && num20 != -1)
{
                                    num22 = 126;
                                }
                                else
{
                                    num22 = 90;
                                }
                                tileCache.frameX = (short)num22;
                                WorldGen.HandleRopeEndFraming(i, j);
                                return;
                            }
                            else
{
                                if (type == 233 || type == 236 || type == 238 || type == 702)
{
                                    WorldGen.CheckJunglePlant(i, j, type);
                                    return;
                                }
                                if (type == 530)
{
                                    WorldGen.CheckOasisPlant(i, j, type);
                                    return;
                                }
                                if (type == 240 || type == 440)
{
                                    WorldGen.Check3x3Wall(i, j);
                                    return;
                                }
                                if (type == 245)
{
                                    WorldGen.Check2x3Wall(i, j);
                                    return;
                                }
                                if (type == 246)
{
                                    WorldGen.Check3x2Wall(i, j);
                                    return;
                                }
                                if (type == 241)
{
                                    WorldGen.Check4x3Wall(i, j);
                                    return;
                                }
                                if (type == 242)
{
                                    WorldGen.Check6x4Wall(i, j);
                                    return;
                                }
                                if (type == 464 || type == 466)
{
                                    WorldGen.Check5x4(i, j, type);
                                    return;
                                }
                                if (type == 334)
{
                                    WorldGen.CheckWeaponsRack(i, j);
                                    return;
                                }
                                if (type == 471)
{
                                    TEWeaponsRack.Framing_CheckTile(i, j);
                                    return;
                                }
                                if (type == 34 || type == 454)
{
                                    WorldGen.CheckChand(i, j, type);
                                    return;
                                }
                                if (type == 547 || type == 623)
{
                                    WorldGen.Check2x5(i, j, type);
                                    return;
                                }
                                if (type == 548 || type == 614)
{
                                    WorldGen.Check3x6(i, j, type);
                                    return;
                                }
                                if (type == 613)
{
                                    WorldGen.Check3x5(i, j, type);
                                    return;
                                }
                                if (type == 106 || type == 212 || type == 219 || type == 220 || type == 228 || type == 231 || type == 243 || type == 247 || type == 283 || (type >= 300 && type <= 308) || type == 354 || type == 406 || type == 412 || type == 355 || type == 452 || type == 455 || type == 491 || type == 499 || type == 642 || type == 733)
{
                                    WorldGen.Check3x3(i, j, (int)((ushort)type));
                                    return;
                                }
                                if (type == 15 || type == 497 || type == 20 || type == 590 || type == 216 || type == 338 || type == 390 || type == 493 || type == 595 || type == 615)
{
                                    WorldGen.Check1x2(i, j, (ushort)type);
                                    return;
                                }
                                if (type == 14 || type == 469 || type == 17 || type == 26 || type == 77 || type == 86 || type == 87 || type == 377 || type == 88 || type == 89 || type == 114 || type == 133 || type == 186 || type == 187 || type == 215 || type == 217 || type == 218 || type == 237 || type == 244 || type == 285 || type == 286 || type == 298 || type == 299 || type == 310 || type == 339 || type == 538 || (type >= 361 && type <= 364) || (type >= 391 && type <= 394) || type == 405 || type == 486 || type == 488 || type == 532 || type == 544 || type == 533 || type == 552 || type == 555 || type == 556 || type == 582 || type == 619 || type == 629 || type == 647 || type == 648 || type == 651 || type == 695 || type == 704 || type == 705 || type == 706)
{
                                    WorldGen.Check3x2(i, j, (int)((ushort)type));
                                    return;
                                }
                                if (type == 135 || type == 141 || type == 650 || type == 210 || type == 239 || type == 36 || type == 428 || type == 593 || type == 624 || type == 656 || type == 700 || type == 701)
{
                                    WorldGen.Check1x1(i, j, type);
                                    return;
                                }
                                if (type == 476)
{
                                    WorldGen.CheckGolf1x1(i, j, type);
                                    return;
                                }
                                if (type == 494)
{
                                    WorldGen.CheckGolf1x1(i, j, type);
                                    return;
                                }
                                if (type == 419 || type == 420 || type == 423 || type == 424 || type == 429 || type == 445)
{
                                    WorldGen.CheckLogicTiles(i, j, type);
                                    return;
                                }
                                if (type == 16 || type == 18 || type == 29 || type == 103 || type == 134 || type == 462 || type == 649)
{
                                    WorldGen.Check2x1(i, j, (ushort)type);
                                    return;
                                }
                                if (type == 13 || type == 33 || type == 50 || type == 707 || type == 78 || type == 174 || type == 372 || type == 49 || type == 646)
{
                                    WorldGen.CheckOnTable1x1(i, j, type);
                                    return;
                                }
                                if (TileID.Sets.BasicChest[type])
{
                                    WorldGen.CheckChest(i, j, type);
                                    return;
                                }
                                if (type == 128)
{
                                    WorldGen.CheckMan(i, j);
                                    return;
                                }
                                if (type == 269)
{
                                    WorldGen.CheckWoman(i, j);
                                    return;
                                }
                                if (type == 470)
{
                                    TEDisplayDoll.Framing_CheckTile(i, j);
                                    return;
                                }
                                if (type == 475)
{
                                    TEHatRack.Framing_CheckTile(i, j);
                                    return;
                                }
                                if (type == 597)
{
                                    TETeleportationPylon.Framing_CheckTile(i, j);
                                    return;
                                }
                                if (type == 27)
{
                                    WorldGen.CheckSunflower(i, j, 27);
                                    return;
                                }
                                if (type == 28 || type == 653)
{
                                    WorldGen.CheckPot(i, j, type);
                                    return;
                                }
                                if (type == 171)
{
                                    WorldGen.CheckXmasTree(i, j);
                                    return;
                                }
                                if (type == 254 || TileID.Sets.BasicChestFake[type] || type == 457)
{
                                    WorldGen.Check2x2Style(i, j, type);
                                    return;
                                }
                                if (type == 335 || type == 411 || type == 490 || type == 564 || type == 565 || type == 594)
{
                                    WorldGen.Check2x2(i, j, type);
                                    return;
                                }
                                if (type == 132 || type == 138 || type == 484 || type == 664 || type == 711 || type == 665 || type == 712 || type == 142 || type == 143 || (type >= 288 && type <= 295) || (type >= 316 && type <= 318) || type == 172 || type == 360 || type == 505 || type == 521 || type == 522 || type == 523 || type == 524 || type == 525 || type == 526 || type == 527 || type == 543 || type == 568 || type == 569 || type == 570 || type == 580 || type == 598 || type == 620 || type == 652 || type == 654 || type == 713 || type == 714 || type == 715 || type == 716 || type == 751 || type == 752)
{
                                    WorldGen.Check2x2(i, j, type);
                                    return;
                                }
                                if (type == 376 || type == 443 || type == 444 || type == 485)
{
                                    WorldGen.CheckSuper(i, j, type);
                                    return;
                                }
                                if (type == 91)
{
                                    WorldGen.CheckBanner(i, j, (byte)type);
                                    return;
                                }
                                if (type == 139 || type == 35)
{
                                    WorldGen.CheckMB(i, j, (int)((byte)type));
                                    return;
                                }
                                if (type == 386 || type == 387)
{
                                    WorldGen.CheckTrapDoor(i, j, type);
                                    return;
                                }
                                if (type == 389 || type == 388)
{
                                    WorldGen.CheckTallGate(i, j, type);
                                    return;
                                }
                                if (type == 92 || type == 93 || type == 453)
{
                                    WorldGen.Check1xX(i, j, (short)type);
                                    return;
                                }
                                if (type == 104 || type == 105 || type == 207 || type == 320 || type == 337 || type == 349 || type == 356 || type == 378 || type == 410 || type == 456 || type == 465 || type == 480 || type == 489 || type == 506 || type == 509 || type == 531 || type == 545 || type == 560 || type == 591 || type == 592 || type == 657 || type == 658 || type == 663 || type == 720 || type == 721 || type == 725)
{
                                    WorldGen.Check2xX(i, j, (ushort)type);
                                    return;
                                }
                                if (type == 101 || type == 102 || type == 463 || type == 617)
{
                                    WorldGen.Check3x4(i, j, type);
                                    return;
                                }
                                if (type == 42 || type == 270 || type == 271 || type == 572 || type == 581 || type == 660 || type == 698)
{
                                    WorldGen.Check1x2Top(i, j, (ushort)type);
                                    return;
                                }
                                if (type == 55 || type == 85 || type == 395 || type == 425 || type == 510 || type == 511 || type == 573)
{
                                    WorldGen.CheckSign(i, j, (ushort)type);
                                    return;
                                }
                                if (type == 520)
{
                                    WorldGen.CheckFoodPlatter(i, j, (int)((ushort)type));
                                    return;
                                }
                                if (type == 209)
{
                                    WorldGen.CheckCannon(i, j, type);
                                    return;
                                }
                                if (type == 79 || type == 90 || type == 487)
{
                                    WorldGen.Check4x2(i, j, type);
                                    return;
                                }
                                if (type == 699)
{
                                    WorldGen.Check4x4(i, j, (int)((ushort)type));
                                    return;
                                }
                                if (type == 94 || type == 95 || type == 97 || type == 319 || type == 98 || type == 99 || type == 100 || type == 125 || type == 126 || type == 173 || type == 282 || type == 287 || type == 621 || type == 622)
{
                                    WorldGen.Check2x2(i, j, type);
                                    return;
                                }
                                if (type == 96)
{
                                    WorldGen.Check2x2Style(i, j, type);
                                    return;
                                }
                                if (type == 81)
{
                                    Tile tile31 = Main.tile[i, j - 1];
                                    Tile tile32 = Main.tile[i, j + 1];
                                    Main.tile[i - 1, j];
                                    Main.tile[i + 1, j];
                                    int num23 = -1;
                                    int num24 = -1;
                                    if (tile31 != null && tile31.active())
{
                                        num24 = (int)tile31.type;
                                    }
                                    if (tile32 != null && tile32.active())
{
                                        num23 = (int)tile32.type;
                                    }
                                    if (num24 != -1)
{
                                        WorldGen.KillTile(i, j, false, false, false);
                                        return;
                                    }
                                    if (num23 < 0 || !Main.tileSolid[num23] || (tile32 != null && (tile32.halfBrick() || tile32.topSlope())))
{
                                        WorldGen.KillTile(i, j, false, false, false);
                                    }
                                    return;
                                }
                                else
{
                                    if (Main.tileAlch[type])
{
                                        WorldGen.CheckAlch(i, j);
                                        return;
                                    }
                                    if (type == 72)
{
                                        Tile tile33 = Main.tile[i, j - 1];
                                        Tile tile34 = Main.tile[i, j + 1];
                                        int num25 = -1;
                                        int num26 = -1;
                                        if (tile33 != null && tile33.active())
{
                                            num26 = (int)tile33.type;
                                        }
                                        if (tile34 != null && tile34.active())
{
                                            num25 = (int)tile34.type;
                                        }
                                        if (num25 != type && num25 != 70)
{
                                            WorldGen.KillTile(i, j, false, false, false);
                                            return;
                                        }
                                        if (num26 != type && tileCache.frameX == 0)
{
                                            int num27 = WorldGen.genRand.Next(3);
                                            if (num27 == 0)
{
                                                tileCache.frameX = 18;
                                                tileCache.frameY = 0;
                                            }
                                            if (num27 == 1)
{
                                                tileCache.frameX = 18;
                                                tileCache.frameY = 18;
                                            }
                                            if (num27 == 2)
{
                                                tileCache.frameX = 18;
                                                tileCache.frameY = 36;
                                                return;
                                            }
                                        }
                                    }
                                    else
{
                                        if (type == 5)
{
                                            WorldGen.CheckTree(i, j);
                                            return;
                                        }
                                        if (type == 583 || type == 584 || type == 585 || type == 586 || type == 587 || type == 588 || type == 589)
{
                                            WorldGen.CheckTreeWithSettings(i, j, new WorldGen.CheckTreeSettings
{
                                                IsGroundValid = new WorldGen.CheckTreeSettings.GroundValidTest(WorldGen.GemTreeGroundTest)
                                            });
                                            return;
                                        }
                                        if (type == 596)
{
                                            WorldGen.CheckTreeWithSettings(i, j, new WorldGen.CheckTreeSettings
{
                                                IsGroundValid = new WorldGen.CheckTreeSettings.GroundValidTest(WorldGen.VanityTreeGroundTest)
                                            });
                                            return;
                                        }
                                        if (type == 616)
{
                                            WorldGen.CheckTreeWithSettings(i, j, new WorldGen.CheckTreeSettings
{
                                                IsGroundValid = new WorldGen.CheckTreeSettings.GroundValidTest(WorldGen.VanityTreeGroundTest)
                                            });
                                            return;
                                        }
                                        if (type == 634)
{
                                            WorldGen.CheckTreeWithSettings(i, j, new WorldGen.CheckTreeSettings
{
                                                IsGroundValid = new WorldGen.CheckTreeSettings.GroundValidTest(WorldGen.AshTreeGroundTest)
                                            });
                                            return;
                                        }
                                        if (type == 323)
{
                                            WorldGen.CheckPalmTree(i, j);
                                            return;
                                        }
                                        if (type == 567)
{
                                            WorldGen.CheckGnome(i, j);
                                            return;
                                        }
                                        if (type == 630 || type == 631)
{
                                            WorldGen.CheckStinkbugBlocker(i, j);
                                            return;
                                        }
                                        if (type == 723 || type == 724)
{
                                            WorldGen.CheckAnchor(i, j);
                                        }
                                    }
                                }
                            }
                        }
                    }
                    return;
                }
                int frameY2 = (int)tileCache.frameY;
                int num28 = 0;
                if (WorldGen.CheckAndAdjustMultiDirectionalTile(i, j, type, out num28))
                {
                    int num29 = frameY2;
                    switch (num28)
                    {
                    case 0:
                        num29 = 0;
                        break;
                    case 1:
                        num29 = 18;
                        break;
                    case 2:
                        num29 = 54;
                        break;
                    case 3:
                        num29 = 36;
                        break;
                    }
                    tileCache.frameY = (short)num29;
                    return;
                }
                WorldGen.KillTile(i, j, false, false, false);
                return;
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicChestFake, Terraria.Tile.bottomSlope(), Terraria.WorldGen.Check1x1(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check4x4(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckAlch(), Terraria.WorldGen.CheckAnchor(), Terraria.WorldGen.CheckAndAdjustMultiDirectionalTile(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.WorldGen.CheckDoorClosed(), Terraria.WorldGen.CheckDoorOpen(), Terraria.WorldGen.CheckDye(), Terraria.WorldGen.CheckFoodPlatter(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckGolf1x1(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckLogicTiles(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOasisPlant(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPalmTree(), Terraria.WorldGen.CheckPile(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckProjectilePressurePad(), Terraria.WorldGen.CheckRockGolemHead(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckStalactite(), Terraria.WorldGen.CheckStalactiteEcho(), Terraria.WorldGen.CheckStinkbugBlocker(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTorch(), Terraria.WorldGen.CheckTrapDoor(), Terraria.WorldGen.CheckTree(), Terraria.WorldGen.CheckTreeWithSettings(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.WorldGen.TileMergeCullCache.CullBottomLeft, Terraria.WorldGen.TileMergeCullCache.CullBottomRight, Terraria.WorldGen.TileMergeCullCache.CullLeft, Terraria.WorldGen.TileMergeCullCache.CullRight, Terraria.WorldGen.TileMergeCullCache.CullTopLeft, Terraria.WorldGen.TileMergeCullCache.CullTopRight, Terraria.WorldGen.ForbidsSloping(), Terraria.Minecart.FrameTrack(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.WorldGen.genRand, Terraria.WorldGen.GetTileMergeCulling(), Terraria.WorldGen.GetTileMossColor(), Terraria.Tile.halfBrick(), Terraria.WorldGen.HandleRopeEndFraming(), int, Terraria.WorldGen.InvalidTileForPilesOrSpeleothems(), Terraria.ID.TileID.Sets.IsADripTile, Terraria.ID.TileID.Sets.IsBeam, Terraria.WorldGen.IsTreeType(), Terraria.WorldGen.KillTile(), Terraria.Tile.leftSlope(), Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlantCheck(), Terraria.ID.TileID.Sets.Platforms, Terraria.Tile.rightSlope(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.Tile.slope(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Main.tileStone, Terraria.Tile.topSlope(), Terraria.ID.TileID.Sets.Torches, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrame().