Terraria Decompiled: Terraria.WorldGen.Place2xX
Place2xX()
static void Terraria.WorldGen.Place2xX (int x, int y, ushort type, int style = 0) inline static
Definition at line 37194 of file WorldGen.cs.
        {
            int num = style * 36;
            int num2 = 0;
            int num3 = 3;
            if (type == 105 && style == 34)
            {
                type = 349;
                style = 0;
                num = 0;
            }
            if (type == 105)
            {
                int num4 = style / 55;
                num -= 1980 * num4;
                num2 += 54 * num4;
            }
            if (type == 104)
            {
                num3 = 5;
            }
            if (type == 207)
            {
                num3 = 4;
            }
            bool flag = true;
            for (int i = y - num3 + 1; i < y + 1; i++)
            {
                if (Main.tile[x, i] == null)
                {
                    Main.tile[x, i] = new Tile();
                }
                if (Main.tile[x, i].active())
                {
                    flag = false;
                }
                if (Main.tile[x + 1, i] == null)
                {
                    Main.tile[x + 1, i] = new Tile();
                }
                if (Main.tile[x + 1, i].active())
                {
                    flag = false;
                }
            }
            if (flag && WorldGen.SolidTile2(x, y + 1) && WorldGen.SolidTile2(x + 1, y + 1))
            {
                for (int j = 0; j < num3; j++)
                {
                    Main.tile[x, y - num3 + 1 + j].active(true);
                    Main.tile[x, y - num3 + 1 + j].frameY = (short)(num2 + j * 18);
                    Main.tile[x, y - num3 + 1 + j].frameX = (short)num;
                    Main.tile[x, y - num3 + 1 + j].type = type;
                    Main.tile[x + 1, y - num3 + 1 + j].active(true);
                    Main.tile[x + 1, y - num3 + 1 + j].frameY = (short)(num2 + j * 18);
                    Main.tile[x + 1, y - num3 + 1 + j].frameX = (short)(num + 18);
                    Main.tile[x + 1, y - num3 + 1 + j].type = type;
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.IslandHouse(), and Terraria.WorldGen.PlaceTile().