Terraria Decompiled: Terraria.WorldGen.nearbyChlorophyte
nearbyChlorophyte()
static bool Terraria.WorldGen.nearbyChlorophyte (int i, int j) inline static private
Definition at line 69845 of file WorldGen.cs.
        {
            double num = 0.0;
            int num2 = 5;
            if (i <= num2 + 5 || i >= Main.maxTilesX - num2 - 5)
            {
                return false;
            }
            if (j <= num2 + 5 || j >= Main.maxTilesY - num2 - 5)
            {
                return false;
            }
            for (int k = i - num2; k <= i + num2; k++)
            {
                for (int l = j - num2; l <= j + num2; l++)
                {
                    if (Main.tile[k, l].active() && (Main.tile[k, l].type == 211 || Main.tile[k, l].type == 346))
                    {
                        num += 1.0;
                        if (num >= 3.0)
{
                            return true;
                        }
                    }
                }
            }
            if (num > 0.0)
            {
                if (Main.remixWorld)
                {
                    if ((double)WorldGen.genRand.Next(-1, 3) < num)
                    {
                        return true;
                    }
                }
                else if ((double)WorldGen.genRand.Next(-1, 4) < num)
                {
                    return true;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.remixWorld, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.hardUpdateWorld().