Terraria Decompiled: Terraria.WorldGen.StonePatch
StonePatch()
static bool Terraria.WorldGen.StonePatch (int X, int Y) inline static
Definition at line 6228 of file WorldGen.cs.
        {
            int num = Y;
            while (!WorldGen.SolidTile(X, num, false))
            {
                num++;
                if ((double)num > Main.worldSurface)
                {
                    return false;
                }
            }
            if (!TileID.Sets.Conversion.Grass[(int)Main.tile[X, num].type] || !TileID.Sets.Conversion.Grass[(int)Main.tile[X - 1, num].type] || !TileID.Sets.Conversion.Grass[(int)Main.tile[X + 1, num].type])
            {
                return false;
            }
            if (Main.tile[X, num].wall > 0)
            {
                return false;
            }
            for (int i = X - 10; i <= X + 10; i++)
            {
                for (int j = num + 7; j <= num + 30; j++)
                {
                    if (!Main.tile[i, j].active() || Main.tileDungeon[(int)Main.tile[i, j].type] || TileID.Sets.Clouds[(int)Main.tile[i, j].type] || TileID.Sets.Conversion.Sand[(int)Main.tile[i, j].type] || Main.tile[i, j].wall == 0 || Main.tile[i, j].type == 199 || Main.tile[i, j].type == 23)
                    {
                        return false;
                    }
                }
            }
            Vector2D vector2D;
            vector2D..ctor((double)X, (double)num);
            Vector2D vector2D2;
            vector2D2.X = WorldGen.genRand.NextDouble() * 0.6 - 0.3;
            vector2D2.Y = WorldGen.genRand.NextDouble() * 0.5 + 0.5;
            double num2 = (double)WorldGen.genRand.Next(13, 18);
            int k = WorldGen.genRand.Next(13, 19);
            if (WorldGen.genRand.Next(3) == 0)
            {
                num2 += (double)WorldGen.genRand.Next(3);
            }
            if (WorldGen.genRand.Next(3) == 0)
            {
                k += WorldGen.genRand.Next(3);
            }
            while (k > 0)
            {
                k--;
                int num3 = X - (int)num2 * 4;
                while ((double)num3 <= (double)X + num2 * 4.0)
                {
                    int num4 = num - (int)num2 * 4;
                    while ((double)num4 <= (double)num + num2 * 4.0)
                    {
                        double num5 = num2 * (0.7 + WorldGen.genRand.NextDouble() * 0.6) * 0.3;
                        if (WorldGen.genRand.Next(8) == 0)
{
                            num5 *= 2.0;
                        }
                        Vector2D vector2D3 = vector2D - new Vector2D((double)num3, (double)num4);
                        if (vector2D3.Length() < num5 * 2.0 && !Main.tile[num3, num4].active() && Main.tile[num3, num4 + 1].active() && Main.tile[num3, num4 + 1].type == 1 && WorldGen.genRand.Next(7) == 0 && WorldGen.SolidTile(num3 - 1, num4 + 1, false) && WorldGen.SolidTile(num3 + 1, num4 + 1, false))
{
                            if (WorldGen.genRand.Next(3) != 0)
{
                                WorldGen.PlaceTile(num3, num4, 186, true, false, -1, WorldGen.genRand.Next(7, 13));
                            }
                            if (WorldGen.genRand.Next(3) != 0)
{
                                WorldGen.PlaceSmallPile(num3, num4, WorldGen.genRand.Next(6), 1, 185);
                            }
                            WorldGen.PlaceSmallPile(num3, num4, WorldGen.genRand.Next(6), 0, 185);
                        }
                        if (vector2D3.Length() < num5)
{
                            if (Main.tileSolid[(int)Main.tile[num3, num4].type])
{
                                Main.tile[num3, num4].type = 1;
                            }
                            if (!WorldGen.isGeneratingOrLoadingWorld)
{
                                WorldGen.SquareTileFrame(num3, num4, true);
                            }
                        }
                        num4++;
                    }
                    num3++;
                }
                vector2D += vector2D2;
                vector2D2.X += WorldGen.genRand.NextDouble() * 0.2 - 0.1;
                vector2D2.Y += WorldGen.genRand.NextDouble() * 0.2 - 0.1;
                Utils.Clamp<double>(vector2D2.X, -0.3, 0.3);
                Utils.Clamp<double>(vector2D2.Y, 0.5, 1.0);
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.genRand, Terraria.ID.TileID.Sets.Conversion.Grass, int, Terraria.WorldGen.isGeneratingOrLoadingWorld, ReLogic.Utilities.Vector2D.Length(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceTile(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, System.X, ReLogic.Utilities.Vector2D.X, System.Y, and ReLogic.Utilities.Vector2D.Y.