Terraria Decompiled: Terraria.WorldGen.KillTile
KillTile()
static void Terraria.WorldGen.KillTile (int i, int j, bool fail = false, bool effectOnly = false, bool noItem = false) inline static
Definition at line 62763 of file WorldGen.cs.
        {
            if (i < 0 || j < 0 || i >= Main.maxTilesX || j >= Main.maxTilesY)
            {
                return;
            }
            Tile tile = Main.tile[i, j];
            if (tile == null)
            {
                tile = new Tile();
                Main.tile[i, j] = tile;
            }
            if (!tile.active())
            {
                return;
            }
            if (j >= 1 && Main.tile[i, j - 1] == null)
            {
                Main.tile[i, j - 1] = new Tile();
            }
            int num = WorldGen.CheckTileBreakability(i, j);
            if (num == 1)
            {
                fail = true;
            }
            if (num == 2)
            {
                return;
            }
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                noItem = true;
            }
            if (!effectOnly && !WorldGen.stopDrops)
            {
                if (!noItem && FixExploitManEaters.SpotProtected(i, j))
                {
                    return;
                }
                if (!Main.dedServ && !WorldGen.isGeneratingOrLoadingWorld && !Main.gameMenu)
                {
                    WorldGen.KillTile_PlaySounds(i, j, fail, tile);
                }
            }
            if (tile.type == 128 || tile.type == 269)
            {
                int num2 = i;
                int k = (int)tile.frameX;
                int l;
                for (l = (int)tile.frameX; l >= 100; l -= 100)
                {
                }
                while (l >= 36)
                {
                    l -= 36;
                }
                if (l == 18)
                {
                    k = (int)Main.tile[i - 1, j].frameX;
                    num2--;
                }
                if (k >= 100)
                {
                    int num3 = 0;
                    while (k >= 100)
                    {
                        k -= 100;
                        num3++;
                    }
                    short num4 = Main.tile[num2, j].frameY / 18;
                    if (num4 == 0)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, Item.headType[num3], 1, false, 0, false);
                    }
                    if (num4 == 1)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, Item.bodyType[num3], 1, false, 0, false);
                    }
                    if (num4 == 2)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, Item.legType[num3], 1, false, 0, false);
                    }
                    for (k = (int)Main.tile[num2, j].frameX; k >= 100; k -= 100)
                    {
                    }
                    Main.tile[num2, j].frameX = (short)k;
                }
            }
            if (tile.type == 334)
            {
                int num5 = i;
                int m = (int)tile.frameX;
                int n = (int)tile.frameX;
                int num6 = 0;
                while (n >= 5000)
                {
                    n -= 5000;
                    num6++;
                }
                if (num6 != 0)
                {
                    n = (num6 - 1) * 18;
                }
                n %= 54;
                if (n == 18)
                {
                    m = (int)Main.tile[i - 1, j].frameX;
                    num5--;
                }
                if (n == 36)
                {
                    m = (int)Main.tile[i - 2, j].frameX;
                    num5 -= 2;
                }
                if (m >= 5000)
                {
                    int num7 = m % 5000;
                    num7 -= 100;
                    int num8 = (int)Main.tile[num5 + 1, j].frameX;
                    if (num8 >= 25000)
                    {
                        num8 -= 25000;
                    }
                    else
                    {
                        num8 -= 10000;
                    }
                    if (Main.netMode != 1)
                    {
                        Item item = new Item();
                        item.netDefaults(num7);
                        item.Prefix(num8);
                        int num9 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num7, 1, true, 0, false);
                        Main.item[num9].OverrideWith(item);
                        NetMessage.SendData(21, -1, -1, null, num9, 0f, 0f, 0f, 0, 0, 0);
                    }
                    m = (int)Main.tile[num5, j].frameX;
                    int num10 = 0;
                    while (m >= 5000)
                    {
                        m -= 5000;
                        num10++;
                    }
                    if (num10 != 0)
                    {
                        m = (num10 - 1) * 18;
                    }
                    Main.tile[num5, j].frameX = (short)m;
                    Main.tile[num5 + 1, j].frameX = (short)(m + 18);
                }
            }
            TEItemFrame teitemFrame;
            if (tile.type == 395 && TileEntity.TryGetAt<TEItemFrame>(i - (int)(tile.frameX % 36 / 18), j - (int)(tile.frameY % 36 / 18), out teitemFrame) && teitemFrame.item.stack > 0)
            {
                teitemFrame.DropItem();
                if (Main.netMode != 2)
                {
                    Main.LocalPlayer.InterruptItemUsageIfOverTile(395);
                }
                return;
            }
            TEDeadCellsDisplayJar tedeadCellsDisplayJar;
            if (tile.type == 698 && TileEntity.TryGetAt<TEDeadCellsDisplayJar>(i - (int)(tile.frameX % 18 / 18), j - (int)(tile.frameY % 32 / 18), out tedeadCellsDisplayJar) && tedeadCellsDisplayJar.item.stack > 0)
            {
                tedeadCellsDisplayJar.DropItem();
                if (Main.netMode != 2)
                {
                    Main.LocalPlayer.InterruptItemUsageIfOverTile(698);
                }
                return;
            }
            TEWeaponsRack teweaponsRack;
            if (tile.type == 471 && TileEntity.TryGetAt<TEWeaponsRack>(i - (int)(tile.frameX % 54 / 18), j - (int)(tile.frameY % 54 / 18), out teweaponsRack) && teweaponsRack.item.stack > 0)
            {
                teweaponsRack.DropItem();
                if (Main.netMode != 2)
                {
                    Main.LocalPlayer.InterruptItemUsageIfOverTile(471);
                }
                return;
            }
            TEFoodPlatter tefoodPlatter;
            if (tile.type == 520 && TileEntity.TryGetAt<TEFoodPlatter>(i, j, out tefoodPlatter) && tefoodPlatter.item.stack > 0)
            {
                tefoodPlatter.DropItem();
                if (Main.netMode != 2)
                {
                    Main.LocalPlayer.InterruptItemUsageIfOverTile(520);
                }
                return;
            }
            TELeashedEntityAnchorWithItem teleashedEntityAnchorWithItem;
            if (!fail && (tile.type == 723 || tile.type == 724) && TileEntity.TryGetAt<TELeashedEntityAnchorWithItem>(i, j, out teleashedEntityAnchorWithItem))
            {
                teleashedEntityAnchorWithItem.DropItemForTileBreak();
            }
            if (tile.type == 470 && (WorldGen.CheckTileBreakability2_ShouldTileSurvive(i, j) || fail))
            {
                return;
            }
            if (tile.type == 475 && (WorldGen.CheckTileBreakability2_ShouldTileSurvive(i, j) || fail))
            {
                return;
            }
            int num11 = WorldGen.KillTile_GetTileDustAmount(fail, tile);
            for (int num12 = 0; num12 < num11; num12++)
            {
                WorldGen.KillTile_MakeTileDust(i, j, tile);
            }
            if (effectOnly)
            {
                return;
            }
            WorldGen.AttemptFossilShattering(i, j, tile, fail);
            if (fail)
            {
                if (Main.netMode != 1 && TileID.Sets.IsShakeable[(int)tile.type])
                {
                    WorldGen.ShakeTree(i, j);
                }
                if (tile.type == 2 || tile.type == 23 || tile.type == 109 || tile.type == 199 || tile.type == 477 || tile.type == 492)
                {
                    tile.type = 0;
                }
                if (tile.type == 633)
                {
                    tile.type = 57;
                }
                if (tile.type == 60 || tile.type == 661 || tile.type == 662 || tile.type == 70)
                {
                    tile.type = 59;
                }
                if (Main.tileMoss[(int)tile.type])
                {
                    tile.type = 1;
                }
                if (TileID.Sets.tileMossBrick[(int)tile.type])
                {
                    tile.type = 38;
                }
                WorldGen.SquareTileFrame(i, j, true);
                return;
            }
            if (Main.getGoodWorld && Main.netMode != 1 && tile.type == 57)
            {
                for (int num13 = 0; num13 < 8; num13++)
                {
                    int num14 = 2;
                    int num15 = i;
                    int num16 = j;
                    if (num13 == 0)
                    {
                        num15--;
                    }
                    else if (num13 == 1)
                    {
                        num15++;
                    }
                    else if (num13 == 2)
                    {
                        num16--;
                    }
                    else if (num13 == 3)
                    {
                        num16++;
                    }
                    else if (num13 == 4)
                    {
                        num15--;
                        num16--;
                    }
                    else if (num13 == 5)
                    {
                        num15++;
                        num16--;
                    }
                    else if (num13 == 6)
                    {
                        num15--;
                        num16++;
                    }
                    else if (num13 == 7)
                    {
                        num15++;
                        num16++;
                    }
                    Tile tile2 = Main.tile[num15, num16];
                    if (tile2.active() && WorldGen.genRand.Next(num14) == 0 && tile2.type == 57 && !WorldGen.SolidTile(num15, num16 + 1, false))
                    {
                        WorldGen.KillTile(num15, num16, false, false, true);
                        if (Main.netMode == 2)
{
                            NetMessage.TrySendData(17, -1, -1, null, 20, (float)num15, (float)num16, 0f, 0, 0, 0);
                        }
                        int num17 = Projectile.NewProjectile(WorldGen.GetProjectileSource_TileBreak(num15, num16), (float)(num15 * 16 + 8), (float)(num16 * 16 + 8), 0f, 0.41f, 40, 15, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        Main.projectile[num17].netUpdate = true;
                    }
                }
            }
            if (Main.netMode != 1 && tile.type >= 481 && tile.type <= 483)
            {
                for (int num18 = 0; num18 < 8; num18++)
                {
                    int num19 = 6;
                    int num20 = i;
                    int num21 = j;
                    if (num18 == 0)
                    {
                        num20--;
                    }
                    else if (num18 == 1)
                    {
                        num20++;
                    }
                    else if (num18 == 2)
                    {
                        num21--;
                        num19 /= 2;
                    }
                    else if (num18 == 3)
                    {
                        num21++;
                    }
                    else if (num18 == 4)
                    {
                        num20--;
                        num21--;
                    }
                    else if (num18 == 5)
                    {
                        num20++;
                        num21--;
                    }
                    else if (num18 == 6)
                    {
                        num20--;
                        num21++;
                    }
                    else if (num18 == 7)
                    {
                        num20++;
                        num21++;
                    }
                    Tile tile3 = Main.tile[num20, num21];
                    if (tile3.active() && WorldGen.genRand.Next(num19) == 0 && tile3.type >= 481 && tile3.type <= 483)
                    {
                        tile.active(false);
                        WorldGen.KillTile(num20, num21, false, false, true);
                        if (Main.netMode == 2)
{
                            NetMessage.TrySendData(17, -1, -1, null, 20, (float)num20, (float)num21, 0f, 0, 0, 0);
                        }
                    }
                }
                int num22 = (int)(tile.type - 481 + 736);
                int num23 = 20;
                EntitySource_TileBreak projectileSource_TileBreak = WorldGen.GetProjectileSource_TileBreak(i, j);
                if (Main.netMode == 0)
                {
                    Projectile.NewProjectile(projectileSource_TileBreak, (float)(i * 16 + 8), (float)(j * 16 + 8), 0f, 0.41f, num22, num23, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                }
                else if (Main.netMode == 2)
                {
                    int num24 = Projectile.NewProjectile(projectileSource_TileBreak, (float)(i * 16 + 8), (float)(j * 16 + 8), 0f, 0.41f, num22, num23, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                    Main.projectile[num24].netUpdate = true;
                }
            }
            if (WorldGen.CheckTileBreakability2_ShouldTileSurvive(i, j))
            {
                return;
            }
            if (tile.type == 51 && tile.wall == 62 && WorldGen.genRand.Next(4) != 0)
            {
                noItem = true;
            }
            if (!noItem && !WorldGen.stopDrops && Main.netMode != 1)
            {
                WorldGen.KillTile_DropBait(i, j, tile);
                WorldGen.KillTile_DropItems(i, j, tile, false);
            }
            if (tile.type == 520)
            {
                TileEntityType<TEFoodPlatter>.Kill(i, j);
            }
            if (tile.type == 423)
            {
                TELogicSensor.Kill(i, j);
            }
            if (tile.type == 723)
            {
                TEKiteAnchor.Kill(i, j);
            }
            if (tile.type == 724)
            {
                TECritterAnchor.Kill(i, j);
            }
            if (Main.netMode != 2)
            {
                AchievementsHelper.NotifyTileDestroyed(Main.player[Main.myPlayer], tile.type);
            }
            tile.active(false);
            tile.halfBrick(false);
            tile.frameX = -1;
            tile.frameY = -1;
            tile.ClearBlockPaintAndCoating();
            tile.frameNumber(0);
            if (Main.netMode != 1)
            {
                if (tile.type == 58 && j > Main.UnderworldLayer)
                {
                    tile.lava(true);
                    tile.liquid = 128;
                }
                else if (tile.type == 230 && Main.getGoodWorld && WorldGen.genRand.Next(2) == 0)
                {
                    tile.lava(true);
                    tile.liquid = 128;
                }
                else if (tile.type > 0 && tile.type < TileID.Count && (tile.type == 147 || tile.type == 224 || TileID.Sets.Ices[(int)tile.type]) && Main.getGoodWorld && Main.remixWorld && !Main.drunkWorld && WorldGen.genRand.Next(2) == 0)
                {
                    tile.liquidType(0);
                    tile.liquid = 64;
                }
            }
            if (tile.type == 419)
            {
                Wiring.PokeLogicGate(i, j + 1);
            }
            else if (TileID.Sets.TruncatesWalls[(int)tile.type])
            {
                WorldGen.SquareWallFrame(i, j, true);
            }
            tile.type = 0;
            tile.inActive(false);
            WorldGen.SquareTileFrame(i, j, true);
            WorldGen.CheckExploitDestroyQueue();
        }
References Terraria.Tile.active(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.Item.bodyType, Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.CheckTileBreakability(), Terraria.WorldGen.CheckTileBreakability2_ShouldTileSurvive(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.ID.TileID.Count, Terraria.Main.dedServ, Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.DropItem(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.DropItem(), Terraria.GameContent.Tile_Entities.TEItemFrame.DropItem(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.DropItem(), Terraria.GameContent.Tile_Entities.TELeashedEntityAnchorWithItem.DropItemForTileBreak(), Terraria.Main.drunkWorld, Terraria.Tile.frameNumber(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.gameMenu, Terraria.WorldGen.genRand, Terraria.Main.getGoodWorld, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.WorldGen.GetProjectileSource_TileBreak(), Terraria.Tile.halfBrick(), Terraria.Item.headType, Terraria.ID.TileID.Sets.Ices, Terraria.Tile.inActive(), int, Terraria.Player.InterruptItemUsageIfOverTile(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.ID.TileID.Sets.IsShakeable, System.item, Terraria.Main.item, Terraria.DataStructures.TileEntityType< T >.Kill(), Terraria.GameContent.Tile_Entities.TECritterAnchor.Kill(), Terraria.GameContent.Tile_Entities.TEKiteAnchor.Kill(), Terraria.GameContent.Tile_Entities.TELogicSensor.Kill(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.KillTile_GetTileDustAmount(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.WorldGen.KillTile_PlaySounds(), Terraria.Tile.lava(), Terraria.Item.legType, Terraria.Tile.liquidType(), Terraria.Main.LocalPlayer, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netUpdate, Terraria.Item.NewItem(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyTileDestroyed(), Terraria.WorldItem.OverrideWith(), Terraria.Main.player, Terraria.Wiring.PokeLogicGate(), Terraria.Main.projectile, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.SolidTile(), Terraria.GameContent.FixExploitManEaters.SpotProtected(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldGen.stopDrops, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.ID.TileID.Sets.TruncatesWalls, Terraria.NetMessage.TrySendData(), Terraria.Tile.type, Terraria.Main.UnderworldLayer, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.Liquid.AddWater(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.Projectile.AI_010(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.Projectile.AI_155_RemoveRope(), Terraria.Player.ApplyTouchDamage(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.WorldGen.Check1x1(), Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check4x4(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckAlch(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCactus(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.WorldGen.CheckDoorClosed(), Terraria.WorldGen.CheckDoorOpen(), Terraria.WorldGen.CheckDye(), Terraria.WorldGen.CheckFoodPlatter(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckGolf1x1(), Terraria.Player.CheckIceBreak(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckLogicTiles(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOasisPlant(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPalmTree(), Terraria.WorldGen.CheckPile(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckProjectilePressurePad(), Terraria.WorldGen.CheckRockGolemHead(), Terraria.WorldGen.CheckSeaOat(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckStalactite(), Terraria.WorldGen.CheckStalactiteEcho(), Terraria.WorldGen.CheckStinkbugBlocker(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTorch(), Terraria.WorldGen.CheckTrapDoor(), Terraria.WorldGen.CheckTree(), Terraria.WorldGen.CheckTreeWithSettings(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.WorldGen.CheckVines(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.WorldGen.ClearBrokenTraps(), Terraria.IO.WorldFile.ClearTempTiles(), Terraria.WorldGen.Convert(), Terraria.WorldGen.ConvertSkyIslands(), Terraria.WorldGen.ConvertTreeAndGround(), Terraria.Liquid.CreateLiquidMergeTile(), Terraria.DelegateMethods.CutTiles(), Terraria.Projectile.CutTilesAt(), Terraria.WorldGen.DestroyHeart(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.DontStarveTryWateringTile(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.Projectile.ExplodeCrackedTiles(), Terraria.Wiring.ExplodeMine(), Terraria.Projectile.ExplodeTiles(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.FixHeart(), Terraria.Minecart.FrameTrack(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEHatRack.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.Framing_CheckTile(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.Framing_CheckTile(), Terraria.GameContent.Biomes.JunglePass.GenerateTunnelToSurface(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.Projectile.HandleMovement(), Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Wiring.HitWireSingle(), Terraria.Player.ItemCheck_CheckCanUse_KillDirtBlock(), Terraria.Player.ItemCheck_CutTiles(), Terraria.Player.ItemCheck_TryPlacingWearablesOnMannequins(), Terraria.Player.ItemCheck_UseMiningTools_ActuallyUseMiningTool(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.LavaLayerCaverer(), Terraria.Liquid.LiquidCheck(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.meteor(), Terraria.GameContent.MinecartDiggerHelper.MineTheTileIfNecessary(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEItemFrame.OnPlayerInteraction(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.OnPlayerInteraction(), Terraria.WorldGen.OpenDoor(), Terraria.Player.PickTile(), Terraria.TileObject.Place(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEItemFrame.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.PlaceItemInFrame(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.PlaceItemInJar(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.GameContent.Generation.TrackGenerator.PlacePath(), Terraria.WorldGen.PlaceSandTrap(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.WorldGen.placeTrap(), Terraria.Player.PlaceWeapon(), Terraria.WorldGen.PlaceXmasTree_Direct(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PoundTile(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.RejectPlacementFromNet(), Terraria.WorldGen.ReplaceTile_EliminateNaturalExtras(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.Shimminate(), Terraria.WorldGen.SlopeTile(), Terraria.Player.Spawn_ForceClearArea(), Terraria.DelegateMethods.SpreadTile(), Terraria.Player.StickyMovement(), Terraria.Collision.SwitchTiles(), Terraria.WorldGen.TileFrameImportant(), Terraria.Player.TileInteractionsUse(), Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid(), Terraria.WorldGen.TryKillingReplaceableTile(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType(), Terraria.WorldGen.WaterCheck(), and Terraria.WorldGen.WavyCaverer().