Terraria Decompiled: Terraria.WorldGen.SquareTileFrame
SquareTileFrame()
static void Terraria.WorldGen.SquareTileFrame (int i, int j, bool resetFrame = true) inline static
Definition at line 80830 of file WorldGen.cs.
        {
            WorldGen.TileFrame(i - 1, j - 1, false, false);
            WorldGen.TileFrame(i - 1, j, false, false);
            WorldGen.TileFrame(i - 1, j + 1, false, false);
            WorldGen.TileFrame(i, j - 1, false, false);
            WorldGen.TileFrame(i, j, resetFrame, false);
            WorldGen.TileFrame(i, j + 1, false, false);
            WorldGen.TileFrame(i + 1, j - 1, false, false);
            WorldGen.TileFrame(i + 1, j, false, false);
            WorldGen.TileFrame(i + 1, j + 1, false, false);
        }
References Terraria.WorldGen.TileFrame().
Referenced by Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.CheckBamboo(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.CheckLilyPad(), Terraria.Wiring.CheckLogicGate(), Terraria.WorldGen.CheckUnderwaterPlant(), Terraria.WorldGen.CheckVines(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.WorldGen.Convert_ActuallyConvertTile(), Terraria.WorldGen.Convert_ActuallyConvertTorch(), Terraria.NPC.CreateBrickBoxForWallOfFlesh(), Terraria.Liquid.CreateLiquidMergeTile(), Terraria.Wiring.DeActive(), Terraria.Liquid.DelWater(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.WorldGen.EmptyLiquid(), Terraria.WorldGen.FinishRemixWorld(), Terraria.GameContent.Biomes.HiveBiome.FrameOutAllHiveContents(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonPot(), Terraria.WorldGen.GERunner(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowSpike(), Terraria.Wiring.HitWireSingle(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.meteor(), Terraria.WorldGen.OrePatch(), Terraria.WorldGen.OreRunner(), Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLiquid(), Terraria.WorldGen.PlaceObject(), Terraria.Player.PlaceThing_Tiles_PlaceIt(), Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.WorldGen.PoundTile(), Terraria.Wiring.ReActive(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Area(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.SlopeTile(), Terraria.WorldGen.SnowCloudIsland(), Terraria.WorldGen.SonOfLakinater(), Terraria.Player.Spawn_ForceClearArea(), Terraria.WorldGen.SpawnFallingBlockProjectile(), Terraria.WorldGen.SpreadGrass(), Terraria.DelegateMethods.SpreadTile(), Terraria.WorldGen.StonePatch(), Terraria.WorldGen.ToggleGemLock(), Terraria.Player.TryReplantingTree(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), and Terraria.Wiring.XferWater().