Terraria Decompiled: Terraria.WorldGen.GrowMoreVines
GrowMoreVines()
static bool Terraria.WorldGen.GrowMoreVines (int x, int y) inline static private
Definition at line 43872 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 30))
            {
                return false;
            }
            int num = 4;
            int num2 = 6;
            int num3 = 10;
            int num4 = 60;
            int num5 = 0;
            if (Main.tile[x, y].type == 528)
            {
                num4 /= 5;
            }
            for (int i = x - num; i <= x + num; i++)
            {
                for (int j = y - num2; j <= y + num3; j++)
                {
                    if (TileID.Sets.IsVine[(int)Main.tile[i, j].type])
                    {
                        num5++;
                        if (j > y && Collision.CanHitLine(new Vector2((float)(x * 16), (float)(y * 16)), 1, 1, new Vector2((float)(i * 16), (float)(j * 16)), 1, 1))
{
                            if (Main.tile[i, j].type == 528)
{
                                num5 += (j - y) * 20;
                            }
                            else
{
                                num5 += (j - y) * 2;
                            }
                        }
                        if (num5 > num4)
{
                            return false;
                        }
                    }
                }
            }
            return true;
        }
References Terraria.Collision.CanHitLine(), Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsVine, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().