Terraria Decompiled: Terraria.WorldGen.PlaceChestDirect
PlaceChestDirect()
static void Terraria.WorldGen.PlaceChestDirect (int x, int y, ushort type, int style, int id) inline static
Definition at line 56551 of file WorldGen.cs.
        {
            Chest.CreateChest(x, y - 1, id);
            for (int i = 0; i <= 1; i++)
            {
                for (int j = -1; j <= 0; j++)
                {
                    if (Main.tile[x + i, y + j] == null)
                    {
                        Main.tile[x + i, y + j] = new Tile();
                    }
                }
            }
            Main.tile[x, y - 1].active(true);
            Main.tile[x, y - 1].frameY = 0;
            Main.tile[x, y - 1].frameX = (short)(36 * style);
            Main.tile[x, y - 1].type = type;
            Main.tile[x, y - 1].halfBrick(false);
            Main.tile[x + 1, y - 1].active(true);
            Main.tile[x + 1, y - 1].frameY = 0;
            Main.tile[x + 1, y - 1].frameX = (short)(18 + 36 * style);
            Main.tile[x + 1, y - 1].type = type;
            Main.tile[x + 1, y - 1].halfBrick(false);
            Main.tile[x, y].active(true);
            Main.tile[x, y].frameY = 18;
            Main.tile[x, y].frameX = (short)(36 * style);
            Main.tile[x, y].type = type;
            Main.tile[x, y].halfBrick(false);
            Main.tile[x + 1, y].active(true);
            Main.tile[x + 1, y].frameY = 18;
            Main.tile[x + 1, y].frameX = (short)(18 + 36 * style);
            Main.tile[x + 1, y].type = type;
            Main.tile[x + 1, y].halfBrick(false);
        }
References Terraria.Tile.active(), Terraria.Chest.CreateChest(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.