Terraria Decompiled: Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt
AttemptToGeneratePlanteraBulbAt()
static bool Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt (int i, int j, bool forceBulb) inline static private
Definition at line 74665 of file WorldGen.cs.
        {
            if (forceBulb)
            {
                int num = 0;
                for (int k = -2; k < 2; k++)
                {
                    for (int l = -2; l < 2; l++)
                    {
                        int num2 = i + k;
                        int num3 = j + l;
                        Tile tile = Main.tile[num2, num3];
                        if (tile.type == 59 || tile.type == 60)
{
                            num++;
                        }
                        else if (tile.active())
{
                            num--;
                        }
                        if (WorldGen.IsAContainer(tile) || tile.type == 226 || tile.type == 237 || tile.type == 10 || tile.type == 11 || tile.type == 26 || tile.type == 16 || tile.type == 15 || tile.type == 14 || tile.type == 104 || TileID.Sets.Paintings[(int)tile.type] || tile.type == 158 || tile.type == 105 || tile.type == 531 || tile.type == 349 || tile.type == 137 || tile.type == 443 || tile.type == 12 || tile.type == 314 || (tile.type >= 0 && TileID.Sets.Boulders[(int)tile.type]))
{
                            num = -1;
                            break;
                        }
                    }
                    if (num <= -1)
                    {
                        break;
                    }
                }
                if (num < 12)
                {
                    return false;
                }
                for (int m = -2; m < 2; m++)
                {
                    for (int n = -2; n < 2; n++)
                    {
                        int num4 = i + m;
                        int num5 = j + n;
                        bool flag = m == -2 || m == 1 || n == -2 || n == 1;
                        Tile tile2 = Main.tile[num4, num5];
                        tile2.ClearTile();
                        if (flag)
{
                            tile2.type = 60;
                            tile2.active(true);
                        }
                        WorldGen.SquareTileFrame(num4, num5, true);
                    }
                }
                WorldGen.PlaceJunglePlant(i, j, 238, 0, 0, true);
                if (Main.tile[i, j].type == 238)
                {
                    WorldGen.SquareTileFrame(i, j, true);
                    WorldGen.SquareTileFrame(i + 2, j, true);
                    WorldGen.SquareTileFrame(i - 1, j, true);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 8, TileChangeType.None);
                    }
                    return true;
                }
            }
            else
            {
                WorldGen.PlaceJunglePlant(i, j, 238, 0, 0, true);
                if (Main.tile[i, j].type == 238)
                {
                    WorldGen.SquareTileFrame(i, j, true);
                    WorldGen.SquareTileFrame(i + 2, j, true);
                    WorldGen.SquareTileFrame(i - 1, j, true);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, 5, TileChangeType.None);
                    }
                    return true;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.Tile.ClearTile(), Terraria.WorldGen.IsAContainer(), Terraria.Main.netMode, Terraria.ID.TileID.Sets.Paintings, Terraria.WorldGen.PlaceJunglePlant(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.GeneratePlanteraBulbOnAllMechsDefeated().