Terraria Decompiled: Terraria.WorldGen.MakeWateryIceThing
MakeWateryIceThing()
static void Terraria.WorldGen.MakeWateryIceThing (int i, int j) inline static
Definition at line 80188 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(i, j, 1))
            {
                return;
            }
            if (Main.tile[i, j].liquid > 0 && !Main.tile[i, j].active() && (!Main.tile[i, j].lava() || Main.remixWorld))
            {
                int num = j;
                while (!Main.tile[i, num].active() && Main.tile[i, num].liquid > 0)
                {
                    num++;
                    if (num > Main.maxTilesY - 50)
                    {
                        return;
                    }
                }
                if (Main.tile[i, num].active() && (TileID.Sets.Snow[(int)Main.tile[i, num].type] || TileID.Sets.Ices[(int)Main.tile[i, num].type]))
                {
                    num--;
                    while (Main.tile[i, num].liquid > 0)
                    {
                        num--;
                        if (num < 10)
{
                            return;
                        }
                    }
                    if (Main.tile[i, num].active())
                    {
                        return;
                    }
                    num++;
                    if (Main.tile[i, num].active())
                    {
                        return;
                    }
                    int num2 = i;
                    while (WorldGen.InWorld(num2, num, 1) && !Main.tile[num2, num].active() && Main.tile[num2, num].liquid > 0 && Main.tile[num2, num - 1].liquid == 0 && !Main.tile[num2, num - 1].active() && !Main.tile[num2 - 1, num].halfBrick())
                    {
                        WorldGen.PlaceTile(num2, num, 162, true, false, -1, 0);
                        num2--;
                    }
                    num2 = i + 1;
                    while (WorldGen.InWorld(num2, num, 1) && !Main.tile[num2, num].active() && Main.tile[num2, num].liquid > 0 && Main.tile[num2, num - 1].liquid == 0 && !Main.tile[num2, num - 1].active() && !Main.tile[num2 + 1, num].halfBrick())
                    {
                        WorldGen.PlaceTile(num2, num, 162, true, false, -1, 0);
                        num2++;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.ID.TileID.Sets.Ices, Terraria.WorldGen.InWorld(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.WorldGen.PlaceTile(), Terraria.Main.remixWorld, Terraria.ID.TileID.Sets.Snow, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AddPasses().