Terraria Decompiled: Terraria.WorldGen.CloseDoor
CloseDoor()
static bool Terraria.WorldGen.CloseDoor (int i, int j, bool forced = false) inline static
Definition at line 29185 of file WorldGen.cs.
        {
            int num = 0;
            int num2 = i;
            if (Main.tile[i, j] == null)
            {
                Main.tile[i, j] = new Tile();
            }
            int frameX = (int)Main.tile[i, j].frameX;
            Tile tile = Main.tile[i, j];
            if (tile.type != 11)
            {
                return false;
            }
            int k = (int)tile.frameY;
            int num3 = 0;
            int num4 = 0;
            while (k >= 54)
            {
                k -= 54;
                num3++;
            }
            if (frameX >= 72)
            {
                num3 += 36 * (frameX / 72);
                num4 += 54 * (frameX / 72);
            }
            int num5 = j - k / 18;
            int num6 = frameX % 72;
            if (num6 == 0)
            {
                num2 = i;
                num = 1;
            }
            else if (num6 == 18)
            {
                num2 = i - 1;
                num = 1;
            }
            else if (num6 == 36)
            {
                num2 = i + 1;
                num = -1;
            }
            else if (num6 == 54)
            {
                num2 = i;
                num = -1;
            }
            int num7 = num2;
            if (num == -1)
            {
                num7 = num2 - 1;
            }
            if (!forced)
            {
                for (int l = num5; l < num5 + 3; l++)
                {
                    if (!Collision.EmptyTile(num2, l, true))
                    {
                        return false;
                    }
                }
            }
            if (!WorldGen.ValidateTileSquareIsActiveAndOfType(num7, num5, 2, 3, 11))
            {
                return false;
            }
            for (int m = num7; m < num7 + 2; m++)
            {
                for (int n = num5; n < num5 + 3; n++)
                {
                    if (Main.tile[m, n] == null)
                    {
                        Main.tile[m, n] = new Tile();
                    }
                    Tile tile2 = Main.tile[m, n];
                    if (tile2.active() && tile2.type == 11)
                    {
                        if (m == num2)
{
                            tile2.type = 10;
                            tile2.frameX = (short)(WorldGen.genRand.Next(3) * 18 + num4);
                        }
                        else
{
                            tile2.active(false);
                        }
                    }
                }
            }
            if (Main.netMode != 1 && Wiring.running)
            {
                Wiring.SkipWire(num2, num5);
                Wiring.SkipWire(num2, num5 + 1);
                Wiring.SkipWire(num2, num5 + 2);
            }
            for (int num8 = num2 - 1; num8 <= num2 + 1; num8++)
            {
                for (int num9 = num5 - 1; num9 <= num5 + 2; num9++)
                {
                    WorldGen.TileFrame(num8, num9, false, false);
                }
            }
            SoundEngine.PlaySound(9, i * 16, j * 16, 1, 1f, 0f);
            return true;
        }
References Terraria.Tile.active(), Terraria.Collision.EmptyTile(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, int, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Wiring.running, Terraria.Wiring.SkipWire(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, and Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType().
Referenced by Terraria.NPC.AI_007_TownEntities(), Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), Terraria.Player.TileInteractionsUse(), and Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryCloseDoor().