Terraria Decompiled: Terraria.WorldGen.SpawnFallingBlockProjectile
SpawnFallingBlockProjectile()
static bool Terraria.WorldGen.SpawnFallingBlockProjectile (int i, int j, int type, Tile tileCache) inline static private
Definition at line 86876 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return false;
            }
            Tile tile = Main.tile[i, j - 1];
            Tile tile2 = Main.tile[i, j + 1];
            if (tileCache == null || tile == null || tile2 == null)
            {
                return false;
            }
            if (!WorldGen.BlockBelowMakesSandFall(i, j))
            {
                return false;
            }
            if (!WorldGen.AllowsSandfall(tile))
            {
                return false;
            }
            int num;
            int num2;
            WorldGen.GetSandfallProjData(type, out num, out num2);
            tileCache.ClearTile();
            if (Main.netMode == 0)
            {
                int num3 = Projectile.NewProjectile(WorldGen.GetProjectileSource_TileBreak(i, j), (float)(i * 16 + 8), (float)(j * 16 + 8), 0f, 0.41f, num, num2, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                Main.projectile[num3].ai[0] = 1f;
                WorldGen.SquareTileFrame(i, j, true);
                WorldGen.ExploitDestroyQueue.Enqueue(new Point(i, j));
                WorldGen.ExploitDestroyQueue.Enqueue(new Point(i, j - 1));
            }
            if (Main.netMode == 2)
            {
                bool flag = false;
                for (int k = 0; k < 1000; k++)
                {
                    if (Main.projectile[k].active && Main.projectile[k].owner == Main.myPlayer && Main.projectile[k].type == num && Math.Abs(Main.projectile[k].timeLeft - 3600) < 60 && Main.projectile[k].Distance(new Vector2((float)(i * 16 + 8), (float)(j * 16 + 10))) < 4f)
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    int num4 = Projectile.NewProjectile(WorldGen.GetProjectileSource_TileBreak(i, j), (float)(i * 16 + 8), (float)(j * 16 + 8), 0f, 2.5f, num, num2, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                    Main.projectile[num4].velocity.Y = 0.5f;
                    Projectile projectile = Main.projectile[num4];
                    projectile.position.Y = projectile.position.Y + 2f;
                    Main.projectile[num4].netUpdate = true;
                }
                WorldGen.SquareTileFrame(i, j, true);
                NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                WorldGen.ExploitDestroyQueue.Enqueue(new Point(i, j));
                WorldGen.ExploitDestroyQueue.Enqueue(new Point(i, j - 1));
            }
            return true;
        }
References System.Math.Abs(), Terraria.Projectile.active, Terraria.Projectile.ai, Terraria.WorldGen.AllowsSandfall(), Terraria.WorldGen.BlockBelowMakesSandFall(), Terraria.Tile.ClearTile(), Terraria.Entity.Distance(), System.Collections.Generic.Queue< T >.Enqueue(), Terraria.WorldGen.ExploitDestroyQueue, Terraria.WorldGen.GetProjectileSource_TileBreak(), Terraria.WorldGen.GetSandfallProjData(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.netUpdate, Terraria.Projectile.NewProjectile(), Terraria.Projectile.owner, Terraria.Main.projectile, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Projectile.timeLeft, Terraria.Projectile.type, Terraria.Entity.velocity, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.TileFrame().