Terraria Decompiled: Terraria.WorldGen.PlaceBamboo
PlaceBamboo()
static bool Terraria.WorldGen.PlaceBamboo (int x, int y) inline static private
Definition at line 57102 of file WorldGen.cs.
        {
            int num = 2;
            int num2 = 5;
            int num3 = WorldGen.genRand.Next(1, 21);
            Tile tile = Main.tile[x, y];
            if (tile.wall > 0 && (double)y <= Main.worldSurface)
            {
                return false;
            }
            if (tile.active() && tile.type == 314)
            {
                return false;
            }
            Tile tile2 = Main.tile[x, y + 1];
            if (!tile2.active() || (tile2.type != 571 && tile2.type != 60))
            {
                return false;
            }
            int waterDepth = WorldGen.GetWaterDepth(x, y);
            if (waterDepth < num || waterDepth > num2)
            {
                return false;
            }
            int num4 = WorldGen.CountGrowingPlantTiles(x, y, 5, 571);
            int num5 = 1;
            if (tile2.type == 571)
            {
                while (!WorldGen.SolidTile(x, y + num5, false))
                {
                    num5++;
                }
                if (num5 + num4 / WorldGen.genRand.Next(1, 21) > num3)
                {
                    return false;
                }
            }
            else
            {
                num4 += 25;
            }
            num4 += num5 * 2;
            if (num4 > WorldGen.genRand.Next(40, 61))
            {
                return false;
            }
            TileColorCache tileColorCache = tile2.BlockColorAndCoating();
            tile = Main.tile[x, y];
            tile.active(true);
            tile.type = 571;
            tile.frameX = 0;
            tile.frameY = 0;
            tile.slope(0);
            tile.halfBrick(false);
            tile.UseBlockColors(tileColorCache);
            WorldGen.SquareTileFrame(x, y, true);
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.WorldGen.CountGrowingPlantTiles(), Terraria.WorldGen.genRand, Terraria.WorldGen.GetWaterDepth(), Terraria.Tile.halfBrick(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.PlaceTile(), and Terraria.WorldGen.UpdateWorld_OvergroundTile().