Terraria Decompiled: Terraria.WorldGen.PlantSeaOat
PlantSeaOat()
static bool Terraria.WorldGen.PlantSeaOat (int x, int y) inline static private
Definition at line 57003 of file WorldGen.cs.
        {
            if (Main.tile[x, y].wall > 0 || Main.tile[x, y].active() || Main.tile[x, y].liquid > 0 || !WorldGen.SolidTileAllowBottomSlope(x, y + 1) || !TileID.Sets.Conversion.Sand[(int)Main.tile[x, y + 1].type])
            {
                return false;
            }
            if (!WorldGen.SeaOatWaterCheck(x, y))
            {
                return false;
            }
            if (Main.tile[x, y + 1] == null)
            {
                return false;
            }
            TileColorCache tileColorCache = Main.tile[x, y + 1].BlockColorAndCoating();
            Main.tile[x, y].active(true);
            Main.tile[x, y].slope(0);
            Main.tile[x, y].halfBrick(false);
            Main.tile[x, y].type = 529;
            Main.tile[x, y].UseBlockColors(tileColorCache);
            Main.tile[x, y].frameX = (short)(WorldGen.genRand.Next(5) * 18);
            int num = 0;
            Main.tile[x, y].frameY = (short)(num * 34);
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.Tile.liquid, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.WorldGen.SeaOatWaterCheck(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.PlaceTile(), and Terraria.WorldGen.UpdateWorld_OvergroundTile().