Terraria Decompiled: Terraria.WorldGen.PlaceCannon
PlaceCannon()
static void Terraria.WorldGen.PlaceCannon (int x, int y, ushort type, int style = 0) inline static
Definition at line 49357 of file WorldGen.cs.
        {
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            bool flag = true;
            for (int i = x - 1; i < x + 3; i++)
            {
                for (int j = y - 2; j < y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active())
                    {
                        flag = false;
                    }
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (!WorldGen.SolidTile2(i, y + 1) && i != x - 1 && i != x + 2)
                {
                    flag = false;
                }
            }
            int num = 72 * style;
            int num2 = 0;
            if (flag)
            {
                Main.tile[x - 1, y - 2].active(true);
                Main.tile[x - 1, y - 2].frameY = (short)num2;
                Main.tile[x - 1, y - 2].frameX = (short)num;
                Main.tile[x - 1, y - 2].type = type;
                Main.tile[x, y - 2].active(true);
                Main.tile[x, y - 2].frameY = (short)num2;
                Main.tile[x, y - 2].frameX = (short)(18 + num);
                Main.tile[x, y - 2].type = type;
                Main.tile[x + 1, y - 2].active(true);
                Main.tile[x + 1, y - 2].frameY = (short)num2;
                Main.tile[x + 1, y - 2].frameX = (short)(36 + num);
                Main.tile[x + 1, y - 2].type = type;
                Main.tile[x + 2, y - 2].active(true);
                Main.tile[x + 2, y - 2].frameY = (short)num2;
                Main.tile[x + 2, y - 2].frameX = (short)(54 + num);
                Main.tile[x + 2, y - 2].type = type;
                Main.tile[x - 1, y - 1].active(true);
                Main.tile[x - 1, y - 1].frameY = (short)(num2 + 18);
                Main.tile[x - 1, y - 1].frameX = (short)num;
                Main.tile[x - 1, y - 1].type = type;
                Main.tile[x, y - 1].active(true);
                Main.tile[x, y - 1].frameY = (short)(num2 + 18);
                Main.tile[x, y - 1].frameX = (short)(18 + num);
                Main.tile[x, y - 1].type = type;
                Main.tile[x + 1, y - 1].active(true);
                Main.tile[x + 1, y - 1].frameY = (short)(num2 + 18);
                Main.tile[x + 1, y - 1].frameX = (short)(36 + num);
                Main.tile[x + 1, y - 1].type = type;
                Main.tile[x + 2, y - 1].active(true);
                Main.tile[x + 2, y - 1].frameY = (short)(num2 + 18);
                Main.tile[x + 2, y - 1].frameX = (short)(54 + num);
                Main.tile[x + 2, y - 1].type = type;
                Main.tile[x - 1, y].active(true);
                Main.tile[x - 1, y].frameY = (short)(num2 + 36);
                Main.tile[x - 1, y].frameX = (short)num;
                Main.tile[x - 1, y].type = type;
                Main.tile[x, y].active(true);
                Main.tile[x, y].frameY = (short)(num2 + 36);
                Main.tile[x, y].frameX = (short)(18 + num);
                Main.tile[x, y].type = type;
                Main.tile[x + 1, y].active(true);
                Main.tile[x + 1, y].frameY = (short)(num2 + 36);
                Main.tile[x + 1, y].frameX = (short)(36 + num);
                Main.tile[x + 1, y].type = type;
                Main.tile[x + 2, y].active(true);
                Main.tile[x + 2, y].frameY = (short)(num2 + 36);
                Main.tile[x + 2, y].frameX = (short)(54 + num);
                Main.tile[x + 2, y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.SolidTile2(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().