Terraria Decompiled: Terraria.WorldGen.UpdateWorld
UpdateWorld()
static void Terraria.WorldGen.UpdateWorld () inline static
Definition at line 71854 of file WorldGen.cs.
        {
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                return;
            }
            WorldGen.hardModeWorldUpdates = Main.hardMode || (Main.remixWorld && Main.getGoodWorld && !Main.tenthAnniversaryWorld);
            WorldGen.AllowedToSpreadInfections = true;
            CreativePowers.StopBiomeSpreadPower power = CreativePowerManager.Instance.GetPower<CreativePowers.StopBiomeSpreadPower>();
            if (power != null && power.GetIsUnlocked())
            {
                WorldGen.AllowedToSpreadInfections = !power.Enabled;
            }
            int num = 3;
            Wiring.UpdateMech();
            TileEntity.PerformUpdates();
            WorldGen.UpdateLunarApocalypse();
            if (Main.netMode != 1)
            {
                WorldGen.totalD++;
                if (WorldGen.totalD >= 30)
                {
                    WorldGen.totalD = 0;
                    WorldGen.CountTiles(WorldGen.totalX);
                    WorldGen.totalX++;
                    if (WorldGen.totalX >= Main.maxTilesX)
                    {
                        WorldGen.totalX = 0;
                    }
                }
            }
            Liquid.skipCount++;
            if (Liquid.skipCount > 1)
            {
                Liquid.UpdateLiquid();
                Liquid.skipCount = 0;
            }
            WorldGen.SpawnStormLightning();
            int worldUpdateRate = WorldGen.GetWorldUpdateRate();
            if (worldUpdateRate == 0)
            {
                return;
            }
            double num2 = (double)(3E-05f * (float)worldUpdateRate);
            double num3 = (double)(6E-05f * (float)worldUpdateRate);
            double num4 = (double)(1.5E-05f * (float)worldUpdateRate);
            double num5 = (double)(2.5E-05f * (float)worldUpdateRate);
            WorldGen.npcSpawnPeriod = 20 * worldUpdateRate;
            WorldGen.UpdatePrioritizedTownNPC();
            WorldGen.CheckForHousesNearAPlayer();
            if (Main.isThereAWorldSurface)
            {
                double num6 = (double)(Main.maxTilesX * Main.maxTilesY) * num2;
                int num7 = (int)Main.worldSurface - 1;
                if (!Main.remixWorld && Main.notTheBeesWorld)
                {
                    num6 = (double)(Main.maxTilesX * Main.maxTilesY) * num3;
                    num7 = (int)Main.rockLayer - 1;
                    WorldGen.growGrassUnderground = true;
                }
                if (Main.IsItRaining)
                {
                    num6 *= 1.5;
                }
                int num8 = 151;
                int num9 = (int)Utils.Lerp((double)num8, (double)num8 * 2.8, Utils.Clamp<double>((double)Main.maxTilesX / 4200.0 - 1.0, 0.0, 1.0));
                int num10 = 0;
                while ((double)num10 < num6)
                {
                    if (Main.rand.Next(num9 * 100) == 0)
                    {
                        WorldGen.PlantAlch();
                    }
                    int num11 = WorldGen.genRand.Next(10, Main.maxTilesX - 10);
                    int num12 = WorldGen.genRand.Next(10, num7);
                    if (Main.dontStarveWorld && Main.getGoodWorld && !Main.remixWorld && num11 > WorldGen.beachDistance && num11 < Main.maxTilesX - WorldGen.beachDistance && Main.tile[num11, num12].wall == 0 && Main.raining && (float)Main.rand.Next(300000) < 100f * Main.maxRaining)
                    {
                        int num13 = WorldGen.genRand.Next(50, (int)Main.worldSurface - 50);
                        while (!WorldGen.SolidTile3(num11, num13) && Main.tile[num11, num13].liquid == 0 && (double)num13 < Main.worldSurface)
{
                            num13++;
                        }
                        if ((double)num13 < Main.worldSurface)
{
                            if (WorldGen.SolidTile3(num11, num13) || Main.tile[num11, num13].liquid == 255)
{
                                num13--;
                            }
                            if (!TileID.Sets.isDesertBiomeSand[(int)Main.tile[num11, num13 + 1].type] && Main.tile[num11, num13 + 1].type != 112 && Main.tile[num11, num13 + 1].type != 234 && Main.tile[num11, num13 + 1].type != 147 && Main.tile[num11, num13 + 1].type != 161 && (Main.tile[num11, num13 + 1].liquid == 0 || Main.tile[num11, num13 + 1].water()) && !WorldGen.SolidTile3(num11, num13) && Main.tile[num11, num13].liquid < 255)
{
                                int num14 = (int)Main.tile[num11, num13].liquid;
                                num14 += Main.rand.Next(127, 255);
                                if (num14 > 255)
{
                                    num14 = 255;
                                }
                                Main.tile[num11, num13].liquid = (byte)num14;
                                Main.tile[num11, num13].liquidType(0);
                                WorldGen.TileFrame(num11, num13, false, false);
                            }
                        }
                    }
                    WorldGen.UpdateWorld_OvergroundTile(num11, num12, num);
                    num10++;
                }
            }
            WorldGen.growGrassUnderground = false;
            if (Main.remixWorld)
            {
                int num15 = 0;
                while ((double)num15 < (double)(Main.maxTilesX * Main.maxTilesY) * num5)
                {
                    int num16 = WorldGen.genRand.Next(10, Main.maxTilesX - 10);
                    int num17 = WorldGen.genRand.Next((int)Main.worldSurface - 1, Main.maxTilesY - 20);
                    WorldGen.growGrassUnderground = true;
                    WorldGen.UpdateWorld_UndergroundTile(num16, num17, num);
                    WorldGen.UpdateWorld_OvergroundTile(num16, num17, num);
                    WorldGen.growGrassUnderground = false;
                    num15++;
                }
            }
            else
            {
                int num18 = 0;
                while ((double)num18 < (double)(Main.maxTilesX * Main.maxTilesY) * num4)
                {
                    int num19 = WorldGen.genRand.Next(10, Main.maxTilesX - 10);
                    int num20 = WorldGen.genRand.Next((int)Main.worldSurface - 1, Main.maxTilesY - 20);
                    WorldGen.UpdateWorld_UndergroundTile(num19, num20, num);
                    num18++;
                }
            }
            WorldGen.SpawnFallingObjects();
        }
References Terraria.WorldGen.beachDistance, Terraria.WorldGen.CheckForHousesNearAPlayer(), Terraria.Utils.Clamp(), Terraria.WorldGen.CountTiles(), Terraria.Main.dontStarveWorld, System.E, Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.Enabled, Terraria.WorldGen.genRand, Terraria.Main.getGoodWorld, Terraria.GameContent.Creative.CreativePowers.StopBiomeSpreadPower.GetIsUnlocked(), Terraria.WorldGen.GetWorldUpdateRate(), Terraria.GameContent.Creative.CreativePowerManager.Instance, int, Terraria.ID.TileID.Sets.isDesertBiomeSand, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Main.IsItRaining, Terraria.Main.isThereAWorldSurface, Terraria.Utils.Lerp(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.DataStructures.TileEntity.PerformUpdates(), Terraria.WorldGen.PlantAlch(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Liquid.skipCount, Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SpawnFallingObjects(), Terraria.WorldGen.SpawnStormLightning(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.WorldGen.totalD, Terraria.WorldGen.totalX, Terraria.Tile.type, Terraria.Liquid.UpdateLiquid(), Terraria.WorldGen.UpdateLunarApocalypse(), Terraria.Wiring.UpdateMech(), Terraria.WorldGen.UpdatePrioritizedTownNPC(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.Tile.wall, Terraria.Tile.water(), and Terraria.Main.worldSurface.
Referenced by Terraria.Main.DoUpdateInWorld().