Terraria Decompiled: Terraria.WorldGen.ShootFromCannon
ShootFromCannon()
static void Terraria.WorldGen.ShootFromCannon (int x, int y, int angle, int ammo, int Damage, float KnockBack, int owner, bool fromWire) inline static
Definition at line 49064 of file WorldGen.cs.
        {
            float num = 14f;
            float num2 = 0f;
            float num3 = 0f;
            int num4 = 162;
            if (ammo == 2)
            {
                num4 = 281;
            }
            if (ammo == 3)
            {
                num4 = 178;
            }
            if (ammo == 4)
            {
                num4 = 601;
                num = 3f;
            }
            if (ammo == 5)
            {
                num4 = 601;
                num = 3f;
            }
            int num5 = 0;
            int num6 = 0;
            if (ammo == 5)
            {
                num5 = 1;
            }
            if (ammo == 2)
            {
                num6 = owner + 1;
            }
            if (angle == 0)
            {
                num2 = 10f;
                num3 = 0f;
            }
            if (angle == 1)
            {
                num2 = 7.5f;
                num3 = -2.5f;
            }
            if (angle == 2)
            {
                num2 = 5f;
                num3 = -5f;
            }
            if (angle == 3)
            {
                num2 = 2.75f;
                num3 = -6f;
            }
            if (angle == 4)
            {
                num2 = 0f;
                num3 = -10f;
            }
            if (angle == 5)
            {
                num2 = -2.75f;
                num3 = -6f;
            }
            if (angle == 6)
            {
                num2 = -5f;
                num3 = -5f;
            }
            if (angle == 7)
            {
                num2 = -7.5f;
                num3 = -2.5f;
            }
            if (angle == 8)
            {
                num2 = -10f;
                num3 = 0f;
            }
            Vector2 vector = new Vector2((float)((x + 2) * 16), (float)((y + 2) * 16));
            float num7 = num2;
            float num8 = num3;
            float num9 = (float)Math.Sqrt((double)(num7 * num7 + num8 * num8));
            if (ammo == 4 || ammo == 5)
            {
                if (angle == 4)
                {
                    vector.X += 5f;
                }
                vector.Y += 5f;
            }
            bool flag = true;
            if (ammo == 2 && !WorldGen.BunnyCannonCanFire())
            {
                flag = false;
            }
            if (flag)
            {
                num9 = num / num9;
                num7 *= num9;
                num8 *= num9;
                if (Main.myPlayer != owner && Main.netMode == 2 && (ammo == 4 || ammo == 5))
                {
                    NetMessage.SendData(108, owner, -1, null, Damage, KnockBack, (float)x, (float)y, angle, ammo, owner);
                    return;
                }
                if (Main.netMode == 2)
                {
                    owner = Main.myPlayer;
                }
                int num10 = Projectile.NewProjectile(WorldGen.GetProjectileSource_PlayerOrWires(x, y, fromWire, Main.player[owner]), vector.X, vector.Y, num7, num8, num4, Damage, KnockBack, owner, (float)num5, (float)num6, 0f, null);
                Main.projectile[num10].originatedFromActivableTile = true;
            }
        }
References Terraria.WorldGen.BunnyCannonCanFire(), Terraria.GameContent.Damage, Terraria.WorldGen.GetProjectileSource_PlayerOrWires(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Projectile.NewProjectile(), Terraria.Projectile.originatedFromActivableTile, Terraria.Main.player, Terraria.Main.projectile, Terraria.NetMessage.SendData(), System.Math.Sqrt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Wiring.HitWireSingle(), Terraria.Player.ShootFromCannon(), and Terraria.Player.TileInteractionsUse().