Terraria Decompiled: Terraria.WorldGen.SpreadDesertWalls
SpreadDesertWalls()
static void Terraria.WorldGen.SpreadDesertWalls (int wallDist, int i, int j) inline static
Definition at line 75486 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(i, j, 10))
            {
                return;
            }
            if (WallID.Sets.Conversion.Sandstone[(int)Main.tile[i, j].wall] || (Main.tile[i, j].active() && TileID.Sets.Conversion.Sandstone[(int)Main.tile[i, j].type]) || WallID.Sets.Conversion.HardenedSand[(int)Main.tile[i, j].wall])
            {
                int num = 0;
                int wall = (int)Main.tile[i, j].wall;
                int type = (int)Main.tile[i, j].type;
                if (WallID.Sets.SpreadsCorruption[wall] || TileID.Sets.SpreadsCorruption[type])
                {
                    num = 1;
                }
                if (WallID.Sets.SpreadsHallow[wall] || TileID.Sets.SpreadsHallow[type])
                {
                    num = 2;
                }
                if (WallID.Sets.SpreadsCrimson[wall] || TileID.Sets.SpreadsCrimson[type])
                {
                    num = 3;
                }
                if (num != 0)
                {
                    int num2 = 1;
                    if (num == 2)
                    {
                        num2 = 2;
                    }
                    if (num == 3)
                    {
                        num2 = 4;
                    }
                    int num3 = i + WorldGen.genRand.Next(-2, 3);
                    int num4 = j + WorldGen.genRand.Next(-2, 3);
                    bool flag = false;
                    if (WallID.Sets.Conversion.PureSand[(int)Main.tile[num3, num4].wall])
                    {
                        if (num == 3)
{
                            for (int k = i - wallDist; k <= i + wallDist; k++)
{
                                for (int l = j - wallDist; l <= j + wallDist; l++)
{
                                    if (Main.tile[k, l].active() && TileID.Sets.SpreadsCrimson[(int)Main.tile[k, l].type])
{
                                        flag = true;
                                        break;
                                    }
                                }
                                if (flag)
{
                                    break;
                                }
                            }
                        }
                        else if (num == 2)
{
                            for (int m = i - wallDist; m <= i + wallDist; m++)
{
                                for (int n = j - wallDist; n <= j + wallDist; n++)
{
                                    if (Main.tile[m, n].active() && TileID.Sets.SpreadsHallow[(int)Main.tile[m, n].type])
{
                                        flag = true;
                                        break;
                                    }
                                }
                                if (flag)
{
                                    break;
                                }
                            }
                        }
                        else if (num == 1)
{
                            for (int num5 = i - wallDist; num5 <= i + wallDist; num5++)
{
                                for (int num6 = j - wallDist; num6 <= j + wallDist; num6++)
{
                                    if (Main.tile[num5, num6].active() && TileID.Sets.SpreadsCorruption[(int)Main.tile[num5, num6].type])
{
                                        flag = true;
                                        break;
                                    }
                                }
                                if (flag)
{
                                    break;
                                }
                            }
                        }
                    }
                    if (flag)
                    {
                        ushort? num7 = null;
                        if (WallID.Sets.Conversion.Sandstone[(int)Main.tile[num3, num4].wall])
{
                            switch (num)
{
                            case 1:
                                num7 = new ushort?(220);
                                break;
                            case 2:
                                num7 = new ushort?(222);
                                break;
                            case 3:
                                num7 = new ushort?(221);
                                break;
                            }
                        }
                        if (WallID.Sets.Conversion.HardenedSand[(int)Main.tile[num3, num4].wall])
{
                            switch (num)
{
                            case 1:
                                num7 = new ushort?(217);
                                break;
                            case 2:
                                num7 = new ushort?(219);
                                break;
                            case 3:
                                num7 = new ushort?(218);
                                break;
                            }
                        }
                        if (num7 != null && Main.tile[num3, num4].wall != num7.Value)
{
                            WorldGen.Convert(num3, num4, num2, false, true);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.Convert(), Terraria.WorldGen.genRand, Terraria.ID.WallID.Sets.Conversion.HardenedSand, int, Terraria.WorldGen.InWorld(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.WallID.Sets.Conversion.PureSand, Terraria.ID.TileID.Sets.Conversion.Sandstone, Terraria.ID.WallID.Sets.Conversion.Sandstone, Terraria.ID.TileID.Sets.SpreadsCorruption, Terraria.ID.WallID.Sets.SpreadsCorruption, Terraria.ID.TileID.Sets.SpreadsCrimson, Terraria.ID.WallID.Sets.SpreadsCrimson, Terraria.ID.TileID.Sets.SpreadsHallow, Terraria.ID.WallID.Sets.SpreadsHallow, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().