Terraria Decompiled: Terraria.WorldGen.SmashAltar
SmashAltar()
static void Terraria.WorldGen.SmashAltar (int i, int j) inline static
Definition at line 47361 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            if (!Main.hardMode)
            {
                return;
            }
            if (WorldGen.generatingWorld)
            {
                return;
            }
            if (WorldGen.isGeneratingOrLoadingWorld)
            {
                return;
            }
            int num = WorldGen.altarCount % 3;
            int num2 = WorldGen.altarCount / 3 + 1;
            double num3 = (double)Main.maxTilesX / 4200.0;
            int num4 = 1;
            num3 = num3 * 310.0 - (double)(85 * num);
            num3 *= 0.85;
            num3 /= (double)num2;
            bool flag = false;
            if (Main.drunkWorld)
            {
                if (WorldGen.SavedOreTiers.Adamantite == 111)
                {
                    WorldGen.SavedOreTiers.Adamantite = 223;
                }
                else if (WorldGen.SavedOreTiers.Adamantite == 223)
                {
                    WorldGen.SavedOreTiers.Adamantite = 111;
                }
            }
            if (num == 0)
            {
                if (WorldGen.SavedOreTiers.Cobalt == -1)
                {
                    flag = true;
                    WorldGen.SavedOreTiers.Cobalt = 107;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        WorldGen.SavedOreTiers.Cobalt = 221;
                    }
                }
                int num5 = 12;
                if (WorldGen.SavedOreTiers.Cobalt == 221)
                {
                    num5 += 9;
                    num3 *= 0.8999999761581421;
                }
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[num5].Key, new object[0]), ChatColors.World, -1);
                num = WorldGen.SavedOreTiers.Cobalt;
                num3 *= 1.0499999523162842;
            }
            else if (num == 1)
            {
                if (Main.drunkWorld)
                {
                    if (WorldGen.SavedOreTiers.Mythril == 108)
                    {
                        WorldGen.SavedOreTiers.Mythril = 222;
                    }
                    else if (WorldGen.SavedOreTiers.Mythril == 222)
                    {
                        WorldGen.SavedOreTiers.Mythril = 108;
                    }
                }
                if (WorldGen.SavedOreTiers.Mythril == -1)
                {
                    flag = true;
                    WorldGen.SavedOreTiers.Mythril = 108;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        WorldGen.SavedOreTiers.Mythril = 222;
                    }
                }
                int num6 = 13;
                if (WorldGen.SavedOreTiers.Mythril == 222)
                {
                    num6 += 9;
                    num3 *= 0.8999999761581421;
                }
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[num6].Key, new object[0]), ChatColors.World, -1);
                num = WorldGen.SavedOreTiers.Mythril;
            }
            else
            {
                if (Main.drunkWorld)
                {
                    if (WorldGen.SavedOreTiers.Cobalt == 107)
                    {
                        WorldGen.SavedOreTiers.Cobalt = 221;
                    }
                    else if (WorldGen.SavedOreTiers.Cobalt == 221)
                    {
                        WorldGen.SavedOreTiers.Cobalt = 107;
                    }
                }
                if (WorldGen.SavedOreTiers.Adamantite == -1)
                {
                    flag = true;
                    WorldGen.SavedOreTiers.Adamantite = 111;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        WorldGen.SavedOreTiers.Adamantite = 223;
                    }
                }
                int num7 = 14;
                if (WorldGen.SavedOreTiers.Adamantite == 223)
                {
                    num7 += 9;
                    num3 *= 0.8999999761581421;
                }
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[num7].Key, new object[0]), ChatColors.World, -1);
                num = WorldGen.SavedOreTiers.Adamantite;
            }
            if (flag)
            {
                NetMessage.SendData(7, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
            }
            int num8 = 0;
            while ((double)num8 < num3)
            {
                int num9 = WorldGen.genRand.Next(100, Main.maxTilesX - 100);
                double num10 = Main.worldSurface;
                if (num == 108 || num == 222)
                {
                    num10 = Main.rockLayer;
                }
                if (num == 111 || num == 223)
                {
                    num10 = (Main.rockLayer + Main.rockLayer + (double)Main.maxTilesY) / 3.0;
                }
                int num11 = WorldGen.genRand.Next((int)num10, Main.maxTilesY - 150);
                if (Main.remixWorld)
                {
                    double num12 = (double)(Main.maxTilesX - 350);
                    if (num == 108 || num == 222)
                    {
                        num12 = (Main.rockLayer + Main.rockLayer + (double)Main.maxTilesY - 350.0) / 3.0;
                    }
                    if (num == 111 || num == 223)
                    {
                        num12 = Main.rockLayer - 25.0;
                    }
                    num11 = WorldGen.genRand.Next((int)Main.worldSurface + 15, (int)num12);
                }
                if (Main.tenthAnniversaryWorld)
                {
                    WorldGen.OreRunner(num9, num11, (double)WorldGen.genRand.Next(5, 11 + num4), WorldGen.genRand.Next(5, 11 + num4), (int)((ushort)num), -1, null, -1, -1);
                }
                else
                {
                    WorldGen.OreRunner(num9, num11, (double)WorldGen.genRand.Next(5, 9 + num4), WorldGen.genRand.Next(5, 9 + num4), (int)((ushort)num), -1, null, -1, -1);
                }
                num8++;
            }
            if (Main.netMode != 1)
            {
                int num13 = Main.rand.Next(2) + 1;
                for (int k = 0; k < num13; k++)
                {
                    NPC.SpawnOnPlayer((int)Player.FindClosest(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16), 82, 0f, 0f, 0f, 0f);
                }
            }
            WorldGen.altarCount++;
            AchievementsHelper.NotifyProgressionEvent(6);
        }
References Terraria.WorldGen.SavedOreTiers.Adamantite, Terraria.WorldGen.altarCount, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.WorldGen.SavedOreTiers.Cobalt, Terraria.Main.drunkWorld, Terraria.Player.FindClosest(), Terraria.Localization.NetworkText.FromKey(), Terraria.WorldGen.generatingWorld, Terraria.WorldGen.genRand, Terraria.Main.hardMode, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Localization.LocalizedText.Key, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Lang.misc, Terraria.WorldGen.SavedOreTiers.Mythril, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.WorldGen.OreRunner(), Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnOnPlayer(), Terraria.Main.tenthAnniversaryWorld, Terraria.Chat.ChatColors.World, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.Check3x2().