Terraria Decompiled: Terraria.WorldGen.CheckPile
CheckPile()
static void Terraria.WorldGen.CheckPile (int i, int y) inline static
Definition at line 45261 of file WorldGen.cs.
        {
            if (Main.tile[i, y] == null)
            {
                Main.tile[i, y] = new Tile();
            }
            if (Main.tile[i + 1, y] == null)
            {
                Main.tile[i + 1, y] = new Tile();
            }
            if (Main.tile[i, y + 1] == null)
            {
                Main.tile[i, y + 1] = new Tile();
            }
            if (Main.tile[i + 1, y + 1] == null)
            {
                Main.tile[i + 1, y + 1] = new Tile();
            }
            Tile tile = Main.tile[i, y];
            if (tile.frameY == 18 || tile.type == 649)
            {
                WorldGen.Check2x1(i, y, tile.type);
                return;
            }
            if (!WorldGen.SolidTileAllowBottomSlope(i, y + 1))
            {
                WorldGen.KillTile(i, y, false, false, false);
                return;
            }
            if (tile.type == 185)
            {
                int num = (int)(tile.frameX / 18);
                Tile tile2 = Main.tile[i, y + 1];
                if (tile2 != null && tile2.active() && tile2.type >= 0 && tile2.type < TileID.Count)
                {
                    ushort type = tile2.type;
                    switch (num)
                    {
                    case 36:
                    case 37:
                    case 38:
                    case 39:
                    case 40:
                    case 41:
                    case 42:
                    case 43:
                    case 44:
                    case 45:
                    case 46:
                    case 47:
                        if (!TileID.Sets.Snow[(int)type] && !TileID.Sets.Conversion.Ice[(int)type] && type != 162 && type != 224)
{
                            WorldGen.KillTile(i, y, false, false, false);
                            return;
                        }
                        break;
                    case 48:
                    case 49:
                    case 50:
                    case 51:
                    case 52:
                    case 53:
                    case 60:
                    case 61:
                    case 62:
                    case 63:
                    case 64:
                    case 65:
                    case 66:
                    case 67:
                    case 68:
                    case 69:
                    case 70:
                    case 71:
                    case 72:
                        break;
                    case 54:
                    case 55:
                    case 56:
                    case 57:
                    case 58:
                    case 59:
                    case 73:
                    case 74:
                    case 75:
                    case 76:
                        if (!TileID.Sets.Conversion.Sand[(int)type] && !TileID.Sets.Conversion.HardenedSand[(int)type] && !TileID.Sets.Conversion.Sandstone[(int)type])
{
                            WorldGen.KillTile(i, y, false, false, false);
                        }
                        break;
                    default:
                        return;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.Check2x1(), Terraria.ID.TileID.Count, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.ID.TileID.Sets.Conversion.HardenedSand, Terraria.ID.TileID.Sets.Conversion.Ice, int, Terraria.WorldGen.KillTile(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.TileID.Sets.Conversion.Sandstone, Terraria.ID.TileID.Sets.Snow, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().