Terraria Decompiled: Terraria.WorldGen.CanKillTile
CanKillTile() [2/3]
static bool Terraria.WorldGen.CanKillTile (int i, int j, out bool blockDamaged) inline static
Definition at line 61149 of file WorldGen.cs.
        {
            blockDamaged = false;
            if (i < 0 || j < 0 || i >= Main.maxTilesX || j >= Main.maxTilesY)
            {
                return false;
            }
            Tile tile = Main.tile[i, j];
            Tile tile2 = null;
            if (tile == null)
            {
                return false;
            }
            if (!tile.active())
            {
                return false;
            }
            if (tile.wall == 350)
            {
                return false;
            }
            if (j >= 1)
            {
                tile2 = Main.tile[i, j - 1];
            }
            if (tile2 != null && tile2.active())
            {
                int type = (int)tile2.type;
                if (TileID.Sets.IsATreeTrunk[type] && (int)tile.type != type && (tile2.frameX != 66 || tile2.frameY < 0 || tile2.frameY > 44) && (tile2.frameX != 88 || tile2.frameY < 66 || tile2.frameY > 110) && tile2.frameY < 198)
                {
                    return false;
                }
                if (type <= 77)
                {
                    if (type <= 26)
                    {
                        if (type != 21 && type != 26)
{
                            goto IL_016D;
                        }
                    }
                    else if (type != 72 && type != 77)
                    {
                        goto IL_016D;
                    }
                }
                else if (type <= 88)
                {
                    if (type != 80)
                    {
                        if (type != 88)
{
                            goto IL_016D;
                        }
                    }
                    else
                    {
                        if ((int)tile.type == type)
{
                            goto IL_016D;
                        }
                        int num = (int)(tile2.frameX / 18);
                        if (num <= 1 || num - 4 <= 1)
{
                            return false;
                        }
                        goto IL_016D;
                    }
                }
                else if (type != 323)
                {
                    if (type != 467 && type != 488)
                    {
                        goto IL_016D;
                    }
                }
                else
                {
                    if ((int)tile.type != type && (tile2.frameX == 66 || tile2.frameX == 220))
                    {
                        return false;
                    }
                    goto IL_016D;
                }
                if ((int)tile.type != type)
                {
                    return false;
                }
            }
            IL_016D:
            if (TileID.Sets.Boulders[(int)tile.type] && WorldGen.CheckBoulderChest(i, j))
            {
                blockDamaged = true;
                return false;
            }
            ushort type2 = tile.type;
            if (type2 <= 21)
            {
                if (type2 != 10)
                {
                    if (type2 != 21)
                    {
                        return true;
                    }
                }
                else
                {
                    if (WorldGen.IsLockedDoor(tile))
                    {
                        blockDamaged = true;
                        return false;
                    }
                    return true;
                }
            }
            else if (type2 != 88)
            {
                if (type2 == 235)
                {
                    int num2 = i - (int)(tile.frameX % 54 / 18);
                    for (int k = 0; k < 3; k++)
                    {
                        Tile tile3 = Main.tile[num2 + k, j - 1];
                        if (tile3.active() && WorldGen.CheckTileBreakability_HasReasonToReturnEarly((int)tile.type, tile3, true))
{
                            blockDamaged = true;
                            return false;
                        }
                    }
                    return true;
                }
                if (type2 != 467)
                {
                    return true;
                }
            }
            else
            {
                if (!Chest.CanDestroyChest(i - (int)(tile.frameX / 18 % 3), j - (int)(tile.frameY / 18)))
                {
                    return false;
                }
                return true;
            }
            if (!Chest.CanDestroyChest(i - (int)(tile.frameX / 18 % 2), j - (int)(tile.frameY / 18)))
            {
                return false;
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.Chest.CanDestroyChest(), Terraria.WorldGen.CheckBoulderChest(), Terraria.WorldGen.CheckTileBreakability_HasReasonToReturnEarly(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.WorldGen.IsLockedDoor(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.