Terraria Decompiled: Terraria.WorldGen.KillWall_PlaySounds
KillWall_PlaySounds()
static void Terraria.WorldGen.KillWall_PlaySounds (int i, int j, Tile tileCache) inline static private
Definition at line 59100 of file WorldGen.cs.
        {
            if (tileCache.wall == 241 || (tileCache.wall >= 88 && tileCache.wall <= 93) || tileCache.wall == 21 || tileCache.wall == 186 || tileCache.wall == 136 || tileCache.wall == 137 || tileCache.wall == 168 || tileCache.wall == 169 || tileCache.wall == 172 || tileCache.wall == 226 || tileCache.wall == 227 || tileCache.wall == 242 || tileCache.wall == 243 || tileCache.wall == 347 || tileCache.wall == 365)
            {
                SoundEngine.PlaySound(13, i * 16, j * 16, 1, 1f, 0f);
                return;
            }
            if ((tileCache.wall >= 63 && tileCache.wall <= 70) || tileCache.wall == 264 || tileCache.wall == 268 || tileCache.wall == 265)
            {
                SoundEngine.PlaySound(6, i * 16, j * 16, 1, 1f, 0f);
                return;
            }
            if (tileCache.wall == 357)
            {
                SoundEngine.PlaySound(SoundID.NPCHit25, i * 16, j * 16, 0f, 1f);
                return;
            }
            SoundEngine.PlaySound(0, i * 16, j * 16, 1, 1f, 0f);
        }
References Terraria.ID.SoundID.NPCHit25, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.KillWall(), and Terraria.WorldGen.ReplaceWall().