Terraria Decompiled: Terraria.WorldGen.PlaceXmasTree
PlaceXmasTree()
static void Terraria.WorldGen.PlaceXmasTree (int x, int y, ushort type = 171) inline static
Definition at line 37088 of file WorldGen.cs.
        {
            bool flag = true;
            int num = x - 1;
            int num2 = y - 7;
            for (int i = num; i < num + 4; i++)
            {
                for (int j = num2; j < num2 + 8; j++)
                {
                    if (Main.tile[i, j].active())
                    {
                        flag = false;
                    }
                }
                if (i > num && i < num + 3 && !WorldGen.SolidTile(i, num2 + 8, false))
                {
                    flag = false;
                }
            }
            if (flag)
            {
                int num3 = 0;
                for (int k = num; k < num + 4; k++)
                {
                    int num4 = 0;
                    for (int l = num2; l < num2 + 8; l++)
                    {
                        Main.tile[k, l].active(true);
                        if (num3 == 0 && num4 == 0)
{
                            Main.tile[k, l].frameX = 10;
                            Main.tile[k, l].frameY = 0;
                        }
                        else
{
                            Main.tile[k, l].frameX = (short)num3;
                            Main.tile[k, l].frameY = (short)num4;
                        }
                        Main.tile[k, l].type = type;
                        Main.tile[k, l].active(true);
                        num4++;
                    }
                    num3++;
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.PlaceTile().