Terraria Decompiled: Terraria.WorldGen.OverGrownDungeonWithRainbowMoss
OverGrownDungeonWithRainbowMoss()
static void Terraria.WorldGen.OverGrownDungeonWithRainbowMoss () inline static private
Definition at line 21169 of file WorldGen.cs.
        {
            int num = Main.maxTilesX / 2;
            for (int i = 0; i < num; i++)
            {
                int num2 = WorldGen.genRand.Next(50, Main.maxTilesX / 2);
                if (GenVars.CurrentDungeonGenVars.dungeonSide >= (int)DungeonSide.Right)
                {
                    num2 = WorldGen.genRand.Next(Main.maxTilesX / 2, Main.maxTilesX - 50);
                }
                int num3 = WorldGen.genRand.Next(50, Main.maxTilesY - 50);
                if (Main.wallDungeon[(int)Main.tile[num2, num3].wall])
                {
                    int num4 = WorldGen.genRand.Next(4, 13);
                    for (int j = num2 - num4; j <= num2 + num4; j++)
                    {
                        for (int k = num3 - num4; k <= num3 + num4; k++)
{
                            if (Main.tileDungeon[(int)Main.tile[j, k].type] && (!Main.tile[j - 1, k - 1].active() || !Main.tile[j, k - 1].active() || !Main.tile[j + 1, k - 1].active() || !Main.tile[j - 1, k].active() || !Main.tile[j + 1, k].active() || !Main.tile[j - 1, k + 1].active() || !Main.tile[j, k + 1].active() || !Main.tile[j + 1, k - 1].active()))
{
                                Main.tile[j, k].type = 628;
                                Main.tile[j, k].ClearBlockPaintAndCoating();
                                if (!Main.tile[j, k - 1].active())
{
                                    WorldGen.PlaceTile(j, k - 1, 184, true, false, -1, 10);
                                }
                                if (!Main.tile[j, k + 1].active())
{
                                    WorldGen.PlaceTile(j, k + 1, 184, true, false, -1, 10);
                                }
                                if (!Main.tile[j - 1, k].active())
{
                                    WorldGen.PlaceTile(j - 1, k, 184, true, false, -1, 10);
                                }
                                if (!Main.tile[j + 1, k].active())
{
                                    WorldGen.PlaceTile(j + 1, k, 184, true, false, -1, 10);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonSide, Terraria.WorldGen.genRand, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldBuilding.DungeonSide.Right, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.wallDungeon.
Referenced by Terraria.WorldGen.SecretSeed.DoRainbowStuff().