Terraria Decompiled: Terraria.WorldGen.Check3x3Wall
Check3x3Wall()
static void Terraria.WorldGen.Check3x3Wall (int x, int y) inline static
Definition at line 42591 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            Tile tile = Main.tile[x, y];
            if (tile == null)
            {
                return;
            }
            int type = (int)tile.type;
            int num = 0;
            int num2 = 0;
            int i = (int)(tile.frameX / 18);
            while (i >= 3)
            {
                i -= 3;
                num++;
            }
            int num3 = x - i;
            int j = (int)(tile.frameY / 18);
            while (j >= 3)
            {
                j -= 3;
                num2++;
            }
            int num4 = y - j;
            j = num2 * 54;
            i = num * 54;
            for (int k = num3; k < num3 + 3; k++)
            {
                for (int l = num4; l < num4 + 3; l++)
                {
                    Tile tile2 = Main.tile[k, l];
                    if (tile2 != null && ((int)tile2.type != type || !tile2.active() || tile2.wall <= 0 || (int)tile2.frameX != i + (k - num3) * 18 || (int)tile2.frameY != j + (l - num4) * 18))
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int m = num3; m < num3 + 3; m++)
                {
                    for (int n = num4; n < num4 + 3; n++)
                    {
                        if (Main.tile[m, n] != null && (int)Main.tile[m, n].type == type && Main.tile[m, n].active())
{
                            WorldGen.KillTile(m, n, false, false, false);
                        }
                    }
                }
                if (type == 240)
                {
                    num += num2 * 36;
                    if (num == 37)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1856, 1, false, 0, false);
                    }
                    else if (num == 36)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1855, 1, false, 0, false);
                    }
                    else if (num == 38)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1960, 1, false, 0, false);
                    }
                    else if (num == 39)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1961, 1, false, 0, false);
                    }
                    else if (num == 40)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1962, 1, false, 0, false);
                    }
                    else if (num == 33)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1574, 1, false, 0, false);
                    }
                    else if (num == 34)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1575, 1, false, 0, false);
                    }
                    else if (num == 35)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1576, 1, false, 0, false);
                    }
                    else if (num == 18)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1419, 1, false, 0, false);
                    }
                    else if (num == 19)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1420, 1, false, 0, false);
                    }
                    else if (num == 20)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1427, 1, false, 0, false);
                    }
                    else if (num == 21)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1428, 1, false, 0, false);
                    }
                    else if (num == 54)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2489, 1, false, 0, false);
                    }
                    else if (num == 55)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2589, 1, false, 0, false);
                    }
                    else if (num == 56)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3357, 1, false, 0, false);
                    }
                    else if (num == 57)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3358, 1, false, 0, false);
                    }
                    else if (num == 58)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3359, 1, false, 0, false);
                    }
                    else if (num == 59)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3595, 1, false, 0, false);
                    }
                    else if (num == 60)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3867, 1, false, 0, false);
                    }
                    else if (num == 61)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3866, 1, false, 0, false);
                    }
                    else if (num == 62)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3868, 1, false, 0, false);
                    }
                    else if (num == 69)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4660, 1, false, 0, false);
                    }
                    else if (num == 70)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4723, 1, false, 0, false);
                    }
                    else if (num == 71)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4724, 1, false, 0, false);
                    }
                    else if (num == 72)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4783, 1, false, 0, false);
                    }
                    else if (num == 73)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4958, 1, false, 0, false);
                    }
                    else if (num == 74)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5087, 1, false, 0, false);
                    }
                    else if (num == 75)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5108, 1, false, 0, false);
                    }
                    else if (num == 94)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5527, 1, false, 0, false);
                    }
                    else if (num == 95)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5528, 1, false, 0, false);
                    }
                    else if (num == 96)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5529, 1, false, 0, false);
                    }
                    else if (num == 97)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5632, 1, false, 0, false);
                    }
                    else if (num == 98)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5631, 1, false, 0, false);
                    }
                    else if (num == 99)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5633, 1, false, 0, false);
                    }
                    else if (num == 100)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5929, 1, false, 0, false);
                    }
                    else if (num == 93)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5490, 1, false, 0, false);
                    }
                    else if (num == 92)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5388, 1, false, 0, false);
                    }
                    else if (num >= 76 && num <= 91)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5218 + num - 76, 1, false, 0, false);
                    }
                    else if (num >= 63 && num <= 68)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4626 + num - 63, 1, false, 0, false);
                    }
                    else if (num >= 41 && num <= 45)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2114 + num - 41, 1, false, 0, false);
                    }
                    else if (num >= 46 && num <= 53)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2442 + num - 46, 1, false, 0, false);
                    }
                    else if (num >= 22 && num <= 25)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1440 + num - 22, 1, false, 0, false);
                    }
                    else if (num >= 26 && num <= 29)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1496 + num - 26, 1, false, 0, false);
                    }
                    else if (num >= 30 && num <= 32)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1538 + num - 30, 1, false, 0, false);
                    }
                    else
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1360 + num, 1, false, 0, false);
                    }
                }
                else if (type == 440)
                {
                    int num5 = -1;
                    int num6 = -1;
                    switch (num)
                    {
                    case 0:
                        num5 = 3644;
                        num6 = 1526;
                        break;
                    case 1:
                        num5 = 3645;
                        num6 = 1524;
                        break;
                    case 2:
                        num5 = 3646;
                        num6 = 1525;
                        break;
                    case 3:
                        num5 = 3647;
                        num6 = 1523;
                        break;
                    case 4:
                        num5 = 3648;
                        num6 = 1522;
                        break;
                    case 5:
                        num5 = 3649;
                        num6 = 1527;
                        break;
                    case 6:
                        num5 = 3650;
                        num6 = 3643;
                        break;
                    }
                    if (num5 != -1)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, num5, 1, false, 0, false);
                    }
                    if (num6 != -1 && num2 == 1)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, num6, 1, false, 0, false);
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().