Terraria Decompiled: Terraria.WorldGen.GetItemDrop_Dressers
GetItemDrop_Dressers()
static int Terraria.WorldGen.GetItemDrop_Dressers (int style) inline static
Definition at line 48306 of file WorldGen.cs.
        {
            int num = 334;
            if (style >= 1 && style <= 3)
            {
                num = 646 + style;
            }
            else if (style == 4)
            {
                num = 918;
            }
            else if (style >= 5 && style <= 15)
            {
                num = 2386 + style - 5;
            }
            else if (style == 16)
            {
                num = 2529;
            }
            else if (style == 17)
            {
                num = 2545;
            }
            else if (style == 18)
            {
                num = 2562;
            }
            else if (style == 19)
            {
                num = 2577;
            }
            else if (style == 20)
            {
                num = 2637;
            }
            else if (style == 21)
            {
                num = 2638;
            }
            else if (style == 22)
            {
                num = 2639;
            }
            else if (style == 23)
            {
                num = 2640;
            }
            else if (style == 24)
            {
                num = 2816;
            }
            else if (style == 25)
            {
                num = 3132;
            }
            else if (style == 26)
            {
                num = 3134;
            }
            else if (style == 27)
            {
                num = 3133;
            }
            else if (style == 28)
            {
                num = 3911;
            }
            else if (style == 29)
            {
                num = 3912;
            }
            else if (style == 30)
            {
                num = 3913;
            }
            else if (style == 31)
            {
                num = 3914;
            }
            else if (style == 32)
            {
                num = 3934;
            }
            else if (style == 33)
            {
                num = 3968;
            }
            else if (style == 34)
            {
                num = 4148;
            }
            else if (style == 35)
            {
                num = 4169;
            }
            else if (style == 36)
            {
                num = 4190;
            }
            else if (style == 37)
            {
                num = 4211;
            }
            else if (style == 38)
            {
                num = 4301;
            }
            else if (style == 39)
            {
                num = 4569;
            }
            else if (style == 40)
            {
                num = 5151;
            }
            else if (style == 41)
            {
                num = 5172;
            }
            else if (style == 42)
            {
                num = 5193;
            }
            else if (style == 43)
            {
                num = 5551;
            }
            else if (style == 44)
            {
                num = 5604;
            }
            else if (style == 45)
            {
                num = 5692;
            }
            else if (style == 46)
            {
                num = 5715;
            }
            else if (style == 47)
            {
                num = 5741;
            }
            else if (style == 48)
            {
                num = 5766;
            }
            else if (style == 49)
            {
                num = 5787;
            }
            else if (style == 50)
            {
                num = 5808;
            }
            else if (style == 51)
            {
                num = 5829;
            }
            else if (style == 52)
            {
                num = 5848;
            }
            else if (style == 53)
            {
                num = 5868;
            }
            else if (style == 54)
            {
                num = 5888;
            }
            else if (style == 55)
            {
                num = 5908;
            }
            else if (style == 56)
            {
                num = 5942;
            }
            else if (style == 57)
            {
                num = 5965;
            }
            else if (style == 58)
            {
                num = 5985;
            }
            else if (style == 59)
            {
                num = 6008;
            }
            else if (style == 60)
            {
                num = 6031;
            }
            else if (style == 61)
            {
                num = 6054;
            }
            else if (style == 62)
            {
                num = 6077;
            }
            else if (style == 63)
            {
                num = 6099;
            }
            else if (style == 64)
            {
                num = 6121;
            }
            return num;
        }
Referenced by Terraria.WorldGen.Check3x2(), Terraria.Chest.Initialize(), and Terraria.WorldGen.KillTile_GetItemDrops().