Terraria Decompiled: Terraria.WorldGen.TriggerLunarApocalypse
TriggerLunarApocalypse()
static void Terraria.WorldGen.TriggerLunarApocalypse () inline static
Definition at line 87511 of file WorldGen.cs.
        {
            List<int> list = new List<int> { 517, 422, 507, 493 };
            int[] array = new int[4];
            for (int i = 0; i < 4; i++)
            {
                array[i] = list[Main.rand.Next(list.Count)];
                list.Remove(array[i]);
            }
            int num = Main.maxTilesX / 5;
            int num2 = (int)Main.worldSurface;
            for (int j = 0; j < 4; j++)
            {
                int num3 = num * (1 + j);
                bool flag = false;
                for (int k = 0; k < 30; k++)
                {
                    int num4 = Main.rand.Next(-100, 101);
                    if ((Main.remixWorld && Main.getGoodWorld) || !Main.isThereAWorldSurface)
                    {
                        int num5 = Main.rand.Next((int)Main.worldSurface, Main.maxTilesY - 350);
                        if (!Main.isThereAWorldSurface)
{
                            num5 = Main.rand.Next((int)Main.rockLayer, Main.maxTilesY - 350);
                        }
                        if (!WorldGen.PlayerLOS(num3 + num4 - 10, num5) && !WorldGen.PlayerLOS(num3 + num4 + 10, num5) && !WorldGen.PlayerLOS(num3 + num4 - 10, num5 - 20) && !WorldGen.PlayerLOS(num3 + num4 + 10, num5 - 20))
{
                            int num6 = NPC.NewNPC(new EntitySource_WorldEvent(), (num3 + num4) * 16, num5 * 16, array[j], 0, 0f, 0f, 0f, 0f, 255);
                            if (Main.netMode == 2 && num6 < Main.maxNPCs)
{
                                NetMessage.SendData(23, -1, -1, null, num6, 0f, 0f, 0f, 0, 0, 0);
                            }
                            flag = true;
                            break;
                        }
                    }
                    else
                    {
                        for (int l = num2; l > 100; l--)
{
                            if (!Collision.SolidTiles(num3 + num4 - 10, num3 + num4 + 10, l - 20, l + 15) && !WorldGen.PlayerLOS(num3 + num4 - 10, l) && !WorldGen.PlayerLOS(num3 + num4 + 10, l) && !WorldGen.PlayerLOS(num3 + num4 - 10, l - 20) && !WorldGen.PlayerLOS(num3 + num4 + 10, l - 20))
{
                                int num7 = NPC.NewNPC(new EntitySource_WorldEvent(), (num3 + num4) * 16, l * 16, array[j], 0, 0f, 0f, 0f, 0f, 255);
                                if (Main.netMode == 2 && num7 < Main.maxNPCs)
{
                                    NetMessage.SendData(23, -1, -1, null, num7, 0f, 0f, 0f, 0, 0, 0);
                                }
                                flag = true;
                                break;
                            }
                        }
                        if (flag)
{
                            break;
                        }
                    }
                }
                if (!flag)
                {
                    NPC.NewNPC(new EntitySource_WorldEvent(), num3 * 16, (num2 - 40) * 16, array[j], 0, 0f, 0f, 0f, 0f, 255);
                }
            }
            NPC.TowerActiveVortex = (NPC.TowerActiveNebula = (NPC.TowerActiveSolar = (NPC.TowerActiveStardust = true)));
            NPC.LunarApocalypseIsUp = true;
            NPC.ShieldStrengthTowerSolar = (NPC.ShieldStrengthTowerVortex = (NPC.ShieldStrengthTowerNebula = (NPC.ShieldStrengthTowerStardust = NPC.ShieldStrengthTowerMax)));
            NetMessage.SendData(101, -1, -1, null, 0, 0f, 0f, 0f, 0, 0, 0);
            WorldGen.MessageLunarApocalypse();
        }
References System.array, Terraria.Main.getGoodWorld, int, Terraria.Main.isThereAWorldSurface, System.list, Terraria.Main.maxNPCs, Terraria.WorldGen.MessageLunarApocalypse(), Terraria.Main.netMode, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlayerLOS(), Terraria.Main.rand, Terraria.Main.remixWorld, System.Collections.Generic.List< T >.Remove(), Terraria.Main.rockLayer, Terraria.NetMessage.SendData(), Terraria.NPC.ShieldStrengthTowerMax, Terraria.Collision.SolidTiles(), and Terraria.Main.worldSurface.
Referenced by Terraria.NPC.DoDeathEvents().