Terraria Decompiled: Terraria.WorldGen.StartRoomCheck
StartRoomCheck()
static bool Terraria.WorldGen.StartRoomCheck (int x, int y, IRoomCheckFeedback feedback = null) inline static
Definition at line 1827 of file WorldGen.cs.
        {
            if (feedback == null)
            {
                feedback = NoRoomCheckFeedback.WithText;
            }
            WorldGen.roomHasStinkbug = false;
            WorldGen.roomHasEchoStinkbug = false;
            WorldGen.roomX1 = x;
            WorldGen.roomX2 = x;
            WorldGen.roomY1 = y;
            WorldGen.roomY2 = y;
            WorldGen.roomTiles.Reset(new Point(x, y), WorldGen.maxRoomSize);
            WorldGen.numRoomTiles = 0;
            for (int i = 0; i < (int)TileID.Count; i++)
            {
                WorldGen.houseTile[i] = false;
            }
            WorldGen.canSpawn = true;
            if (x < 10 || y < 10 || x >= Main.maxTilesX - 10 || y >= WorldGen.lastMaxTilesY - 10)
            {
                feedback.TooCloseToWorldEdge(x, y, 0);
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.TooCloseToWorldEdge;
                WorldGen.canSpawn = false;
                return false;
            }
            if (Main.tile[x, y].nactive() && Main.tileSolid[(int)Main.tile[x, y].type])
            {
                feedback.StartedInASolidTile(x, y);
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomCheckStartedInASolidTile;
                WorldGen.canSpawn = false;
                return false;
            }
            WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.None;
            Stack<Point> roomCheckStack = WorldGen._roomCheckStack;
            roomCheckStack.Clear();
            roomCheckStack.Push(new Point(x, y));
            while (roomCheckStack.Count > 0 && (WorldGen.canSpawn || !feedback.StopOnFail))
            {
                Point point = roomCheckStack.Pop();
                if (WorldGen.CheckRoom(point.X, point.Y, roomCheckStack.Count, feedback))
                {
                    for (int j = -1; j <= 1; j++)
                    {
                        for (int k = -1; k <= 1; k++)
{
                            if (j != 0 || k != 0)
{
                                roomCheckStack.Push(new Point(point.X + j, point.Y + k));
                            }
                        }
                    }
                }
            }
            if (!WorldGen.canSpawn)
            {
                return false;
            }
            if (WorldGen.numRoomTiles < 60)
            {
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooSmall;
                WorldGen.canSpawn = false;
                return false;
            }
            return WorldGen.canSpawn;
        }
References Terraria.WorldGen._roomCheckStack, Terraria.WorldGen.canSpawn, Terraria.WorldGen.CheckRoom(), System.Collections.Generic.Stack< T >.Clear(), System.Collections.Generic.Stack< T >.Count, Terraria.ID.TileID.Count, Terraria.WorldGen.houseTile, int, Terraria.WorldGen.lastMaxTilesY, Terraria.WorldGen.maxRoomSize, Terraria.Main.maxTilesX, Terraria.Tile.nactive(), Terraria.WorldGen.numRoomTiles, System.Collections.Generic.Stack< T >.Pop(), System.Collections.Generic.Stack< T >.Push(), Terraria.Utilities.BitSet2D.Reset(), Terraria.WorldGen.roomTiles, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.DataStructures.NoRoomCheckFeedback.WithText, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Player.CheckSpawn_Internal(), Terraria.IO.WorldFile.FixAgainstExploits(), Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().