Terraria Decompiled: Terraria.WorldGen.PlaceMB
PlaceMB()
static void Terraria.WorldGen.PlaceMB (int X, int y, ushort type, int style) inline static
Definition at line 49782 of file WorldGen.cs.
        {
            int num = X + 1;
            if (num < 5 || num > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            bool flag = true;
            for (int i = num - 1; i < num + 1; i++)
            {
                for (int j = y - 1; j < y + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    if (Main.tile[i, j].active())
                    {
                        flag = false;
                    }
                }
                if (Main.tile[i, y + 1] == null)
                {
                    Main.tile[i, y + 1] = new Tile();
                }
                if (!Main.tile[i, y + 1].active() || Main.tile[i, y + 1].halfBrick() || (!Main.tileSolid[(int)Main.tile[i, y + 1].type] && !Main.tileTable[(int)Main.tile[i, y + 1].type]))
                {
                    flag = false;
                }
            }
            if (flag)
            {
                Main.tile[num - 1, y - 1].active(true);
                Main.tile[num - 1, y - 1].frameY = (short)(style * 36);
                Main.tile[num - 1, y - 1].frameX = 0;
                Main.tile[num - 1, y - 1].type = type;
                Main.tile[num, y - 1].active(true);
                Main.tile[num, y - 1].frameY = (short)(style * 36);
                Main.tile[num, y - 1].frameX = 18;
                Main.tile[num, y - 1].type = type;
                Main.tile[num - 1, y].active(true);
                Main.tile[num - 1, y].frameY = (short)(style * 36 + 18);
                Main.tile[num - 1, y].frameX = 0;
                Main.tile[num - 1, y].type = type;
                Main.tile[num, y].active(true);
                Main.tile[num, y].frameY = (short)(style * 36 + 18);
                Main.tile[num, y].frameX = 18;
                Main.tile[num, y].type = type;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileTable, Terraria.Tile.type, and System.X.
Referenced by Terraria.WorldGen.PlaceTile().