Terraria Decompiled: Terraria.WorldGen.CheckAlch
CheckAlch()
static void Terraria.WorldGen.CheckAlch (int x, int y) inline static
Definition at line 44330 of file WorldGen.cs.
        {
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            if (Main.tile[x, y + 1] == null)
            {
                Main.tile[x, y + 1] = new Tile();
            }
            bool flag = false;
            if (!Main.tile[x, y + 1].nactive())
            {
                flag = true;
            }
            if (Main.tile[x, y + 1].halfBrick())
            {
                flag = true;
            }
            int num = (int)(Main.tile[x, y].frameX / 18);
            Main.tile[x, y].frameY = 0;
            if (!flag)
            {
                if (num == 0)
                {
                    if (Main.tile[x, y + 1].type != 109 && Main.tile[x, y + 1].type != 2 && Main.tile[x, y + 1].type != 477 && Main.tile[x, y + 1].type != 492 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                    {
                        flag = true;
                    }
                }
                else if (num == 1)
                {
                    if (Main.tile[x, y + 1].type != 60 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                    {
                        flag = true;
                    }
                }
                else if (num == 2)
                {
                    if (Main.tile[x, y + 1].type != 0 && Main.tile[x, y + 1].type != 59 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                    {
                        flag = true;
                    }
                }
                else if (num == 3)
                {
                    if (Main.tile[x, y + 1].type != 661 && Main.tile[x, y + 1].type != 662 && Main.tile[x, y + 1].type != 199 && Main.tile[x, y + 1].type != 203 && Main.tile[x, y + 1].type != 23 && Main.tile[x, y + 1].type != 25 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                    {
                        flag = true;
                    }
                }
                else if (num == 4)
                {
                    if (Main.tile[x, y + 1].type != 53 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380 && Main.tile[x, y + 1].type != 116)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                    {
                        flag = true;
                    }
                }
                else if (num == 5)
                {
                    if (Main.tile[x, y + 1].type != 57 && Main.tile[x, y + 1].type != 633 && Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].type != 82 && Main.tile[x, y].anyLava() && Main.netMode != 1)
                    {
                        if (Main.tile[x, y].liquid > 16)
{
                            if (Main.tile[x, y].type == 83)
{
                                Main.tile[x, y].type = 84;
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                                }
                            }
                        }
                        else if (Main.tile[x, y].type == 84)
{
                            Main.tile[x, y].type = 83;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                            }
                        }
                    }
                }
                else if (num == 6)
                {
                    if (Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380 && Main.tile[x, y + 1].type != 147 && Main.tile[x, y + 1].type != 161 && Main.tile[x, y + 1].type != 163 && Main.tile[x, y + 1].type != 164 && Main.tile[x, y + 1].type != 200)
                    {
                        flag = true;
                    }
                    if (Main.tile[x, y].liquid > 0 && Main.tile[x, y].lava())
                    {
                        flag = true;
                    }
                }
            }
            if (flag)
            {
                WorldGen.KillTile(x, y, false, false, false);
            }
        }
References Terraria.Tile.anyLava(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.NetMessage.SendTileSquare(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Liquid.DelWater(), and Terraria.WorldGen.TileFrameImportant().