Terraria Decompiled: Terraria.WorldGen.CheckBoulderChest
CheckBoulderChest()
static bool Terraria.WorldGen.CheckBoulderChest (int i, int j) inline static
Definition at line 47241 of file WorldGen.cs.
        {
            int num = (int)(Main.tile[i, j].frameX / 18 * -1);
            if (num < -1)
            {
                num += 2;
            }
            num += i;
            int k;
            for (k = (int)Main.tile[i, j].frameY; k >= 36; k -= 36)
            {
            }
            k = j - k / 18;
            ushort type = Main.tile[i, j].type;
            return WorldGen.CheckTileBreakability_HasReasonToReturnEarly((int)type, Main.tile[num, k - 1], true) || WorldGen.CheckTileBreakability_HasReasonToReturnEarly((int)type, Main.tile[num + 1, k - 1], true);
        }
References Terraria.WorldGen.CheckTileBreakability_HasReasonToReturnEarly(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CanKillTile(), and Terraria.WorldGen.CheckTileBreakability().