Terraria Decompiled: Terraria.WorldGen.setBG
setBG()
static void Terraria.WorldGen.setBG (int bg, int style) inline static
Definition at line 3068 of file WorldGen.cs.
        {
            if (bg == 0)
            {
                WorldGen.treeBG1 = style;
                WorldGen.SetForestBGSet(style, Main.treeMntBGSet1, Main.treeBGSet1);
                return;
            }
            if (bg == 10)
            {
                WorldGen.treeBG2 = style;
                WorldGen.SetForestBGSet(style, Main.treeMntBGSet2, Main.treeBGSet2);
                return;
            }
            if (bg == 11)
            {
                WorldGen.treeBG3 = style;
                WorldGen.SetForestBGSet(style, Main.treeMntBGSet3, Main.treeBGSet3);
                return;
            }
            if (bg == 12)
            {
                WorldGen.treeBG4 = style;
                WorldGen.SetForestBGSet(style, Main.treeMntBGSet4, Main.treeBGSet4);
                return;
            }
            if (bg == 1)
            {
                WorldGen.corruptBG = style;
                switch (style)
                {
                case 1:
                    Main.corruptBG[0] = 56;
                    Main.corruptBG[1] = 57;
                    Main.corruptBG[2] = 58;
                    return;
                case 2:
                    Main.corruptBG[0] = 211;
                    Main.corruptBG[1] = 212;
                    Main.corruptBG[2] = 213;
                    return;
                case 3:
                    Main.corruptBG[0] = 225;
                    Main.corruptBG[1] = 226;
                    Main.corruptBG[2] = 227;
                    return;
                case 4:
                    Main.corruptBG[0] = 240;
                    Main.corruptBG[1] = 241;
                    Main.corruptBG[2] = 242;
                    return;
                default:
                    if (style == 51)
                    {
                        Main.corruptBG[0] = 324;
                        Main.corruptBG[1] = 323;
                        Main.corruptBG[2] = 322;
                        return;
                    }
                    if (style != 52)
                    {
                        Main.corruptBG[0] = 12;
                        Main.corruptBG[1] = 13;
                        Main.corruptBG[2] = 14;
                        return;
                    }
                    Main.corruptBG[0] = 324;
                    Main.corruptBG[1] = 226;
                    Main.corruptBG[2] = 322;
                    return;
                }
            }
            else if (bg == 2)
            {
                WorldGen.jungleBG = style;
                switch (style)
                {
                case 1:
                    Main.jungleBG[0] = 59;
                    Main.jungleBG[1] = 60;
                    Main.jungleBG[2] = 61;
                    return;
                case 2:
                    Main.jungleBG[0] = 222;
                    Main.jungleBG[1] = 223;
                    Main.jungleBG[2] = 224;
                    return;
                case 3:
                    Main.jungleBG[0] = 237;
                    Main.jungleBG[1] = 238;
                    Main.jungleBG[2] = 239;
                    return;
                case 4:
                    Main.jungleBG[0] = 284;
                    Main.jungleBG[1] = 285;
                    Main.jungleBG[2] = 286;
                    return;
                case 5:
                    Main.jungleBG[0] = 271;
                    Main.jungleBG[1] = 272;
                    Main.jungleBG[2] = 273;
                    return;
                case 6:
                    Main.jungleBG[0] = 302;
                    Main.jungleBG[1] = 301;
                    Main.jungleBG[2] = 300;
                    return;
                default:
                    Main.jungleBG[0] = 15;
                    Main.jungleBG[1] = 16;
                    Main.jungleBG[2] = 17;
                    return;
                }
            }
            else
            {
                if (bg == 3)
                {
                    WorldGen.snowBG = style;
                    Main.snowMntBG[0] = 35;
                    Main.snowMntBG[1] = 36;
                    if (style <= 22)
                    {
                        switch (style)
{
                        case 1:
                            Main.snowBG[0] = 97;
                            Main.snowBG[1] = 96;
                            Main.snowBG[2] = 95;
                            return;
                        case 2:
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 99;
                            Main.snowBG[0] = -1;
                            Main.snowBG[1] = -1;
                            Main.snowBG[2] = -1;
                            return;
                        case 3:
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 100;
                            Main.snowBG[0] = -1;
                            Main.snowBG[1] = -1;
                            Main.snowBG[2] = -1;
                            return;
                        case 4:
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 101;
                            Main.snowBG[0] = -1;
                            Main.snowBG[1] = -1;
                            Main.snowBG[2] = -1;
                            return;
                        case 5:
                            Main.snowMntBG[0] = -1;
                            Main.snowMntBG[1] = -1;
                            Main.snowBG[0] = 258;
                            Main.snowBG[1] = 259;
                            Main.snowBG[2] = 260;
                            return;
                        case 6:
                            Main.snowMntBG[0] = -1;
                            Main.snowMntBG[1] = -1;
                            Main.snowBG[0] = 263;
                            Main.snowBG[1] = 264;
                            Main.snowBG[2] = 265;
                            return;
                        case 7:
                            Main.snowMntBG[0] = 269;
                            Main.snowMntBG[1] = 270;
                            Main.snowBG[0] = 267;
                            Main.snowBG[1] = 266;
                            Main.snowBG[2] = 268;
                            return;
                        case 8:
                            Main.snowBG[0] = 299;
                            Main.snowBG[1] = 298;
                            Main.snowBG[2] = -1;
                            return;
                        default:
                            if (style == 21)
{
                                Main.snowMntBG[0] = 98;
                                Main.snowMntBG[1] = 99;
                                Main.snowBG[0] = 95;
                                Main.snowBG[1] = 96;
                                Main.snowBG[2] = 97;
                                return;
                            }
                            if (style == 22)
{
                                Main.snowMntBG[0] = 98;
                                Main.snowMntBG[1] = 99;
                                Main.snowBG[0] = 37;
                                Main.snowBG[1] = 38;
                                Main.snowBG[2] = 39;
                                return;
                            }
                            break;
                        }
                    }
                    else if (style <= 32)
                    {
                        if (style == 31)
{
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 100;
                            Main.snowBG[0] = 95;
                            Main.snowBG[1] = 96;
                            Main.snowBG[2] = 97;
                            return;
                        }
                        if (style == 32)
{
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 100;
                            Main.snowBG[0] = 37;
                            Main.snowBG[1] = 38;
                            Main.snowBG[2] = 39;
                            return;
                        }
                    }
                    else
                    {
                        if (style == 41)
{
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 101;
                            Main.snowBG[0] = 95;
                            Main.snowBG[1] = 96;
                            Main.snowBG[2] = 97;
                            return;
                        }
                        if (style == 42)
{
                            Main.snowMntBG[0] = 98;
                            Main.snowMntBG[1] = 101;
                            Main.snowBG[0] = 37;
                            Main.snowBG[1] = 38;
                            Main.snowBG[2] = 39;
                            return;
                        }
                    }
                    Main.snowBG[0] = 37;
                    Main.snowBG[1] = 38;
                    Main.snowBG[2] = 39;
                    return;
                }
                if (bg == 4)
                {
                    WorldGen.hallowBG = style;
                    switch (style)
                    {
                    case 1:
                        Main.hallowBG[0] = 102;
                        Main.hallowBG[1] = 103;
                        Main.hallowBG[2] = 104;
                        return;
                    case 2:
                        Main.hallowBG[0] = 219;
                        Main.hallowBG[1] = 220;
                        Main.hallowBG[2] = 221;
                        return;
                    case 3:
                        Main.hallowBG[0] = 243;
                        Main.hallowBG[1] = 244;
                        Main.hallowBG[2] = 245;
                        return;
                    case 4:
                        Main.hallowBG[0] = -1;
                        Main.hallowBG[1] = 261;
                        Main.hallowBG[2] = 262;
                        return;
                    case 5:
                        Main.hallowBG[0] = 327;
                        Main.hallowBG[1] = 326;
                        Main.hallowBG[2] = 325;
                        return;
                    default:
                        Main.hallowBG[0] = 29;
                        Main.hallowBG[1] = 30;
                        Main.hallowBG[2] = 31;
                        return;
                    }
                }
                else if (bg == 5)
                {
                    WorldGen.crimsonBG = style;
                    switch (style)
                    {
                    case 1:
                        Main.crimsonBG[0] = 105;
                        Main.crimsonBG[1] = 106;
                        Main.crimsonBG[2] = 107;
                        return;
                    case 2:
                        Main.crimsonBG[0] = 174;
                        Main.crimsonBG[1] = -1;
                        Main.crimsonBG[2] = 175;
                        return;
                    case 3:
                        Main.crimsonBG[0] = 214;
                        Main.crimsonBG[1] = 215;
                        Main.crimsonBG[2] = 216;
                        return;
                    case 4:
                        Main.crimsonBG[0] = -1;
                        Main.crimsonBG[1] = 229;
                        Main.crimsonBG[2] = 230;
                        return;
                    case 5:
                        Main.crimsonBG[0] = 255;
                        Main.crimsonBG[1] = 256;
                        Main.crimsonBG[2] = 257;
                        return;
                    case 6:
                        Main.crimsonBG[0] = 339;
                        Main.crimsonBG[1] = 338;
                        Main.crimsonBG[2] = 337;
                        return;
                    default:
                        Main.crimsonBG[0] = 43;
                        Main.crimsonBG[1] = 44;
                        Main.crimsonBG[2] = 45;
                        return;
                    }
                }
                else if (bg == 6)
                {
                    WorldGen.desertBG = style;
                    switch (style)
                    {
                    case 1:
                        Main.desertBackgroundSet.Clear();
                        Main.desertBackgroundSet.Pure.Set(108, 109, -1);
                        return;
                    case 2:
                        Main.desertBackgroundSet.Clear();
                        Main.desertBackgroundSet.Pure.Set(207, 208, -1);
                        return;
                    case 3:
                        Main.desertBackgroundSet.Clear();
                        Main.desertBackgroundSet.Pure.Set(217, 218, -1);
                        return;
                    case 4:
                        Main.desertBackgroundSet.Clear();
                        Main.desertBackgroundSet.Pure.Set(248, 249, 250);
                        return;
                    default:
                        switch (style)
{
                        case 51:
                            Main.desertBackgroundSet.Clear();
                            Main.desertBackgroundSet.Pure.Set(306, 303, -1);
                            Main.desertBackgroundSet.Corrupt.Set(310, 307, -1);
                            Main.desertBackgroundSet.Hallow.Set(314, 311, -1);
                            Main.desertBackgroundSet.Crimson.Set(318, 315, -1);
                            return;
                        case 52:
                            Main.desertBackgroundSet.Clear();
                            Main.desertBackgroundSet.Pure.Set(306, 304, -1);
                            Main.desertBackgroundSet.Corrupt.Set(310, 308, -1);
                            Main.desertBackgroundSet.Hallow.Set(314, 312, -1);
                            Main.desertBackgroundSet.Crimson.Set(318, 316, -1);
                            return;
                        case 53:
                            Main.desertBackgroundSet.Clear();
                            Main.desertBackgroundSet.Pure.Set(306, 305, -1);
                            Main.desertBackgroundSet.Corrupt.Set(310, 309, -1);
                            Main.desertBackgroundSet.Hallow.Set(314, 313, -1);
                            Main.desertBackgroundSet.Crimson.Set(318, 317, -1);
                            return;
                        default:
                            Main.desertBackgroundSet.Clear();
                            Main.desertBackgroundSet.Pure.Set(21, 20, -1);
                            return;
                        }
                        break;
                    }
                }
                else if (bg == 7)
                {
                    WorldGen.oceanBG = style;
                    switch (style)
                    {
                    case 1:
                        Main.oceanBG = 110;
                        return;
                    case 2:
                        Main.oceanBG = 111;
                        return;
                    case 3:
                        Main.oceanBG = 209;
                        return;
                    case 4:
                        Main.oceanBG = 210;
                        return;
                    case 5:
                        Main.oceanBG = 283;
                        return;
                    case 6:
                        Main.oceanBG = 332;
                        return;
                    case 7:
                        Main.oceanBG = 340;
                        return;
                    default:
                        Main.oceanBG = 28;
                        return;
                    }
                }
                else
                {
                    if (bg != 8)
                    {
                        if (bg == 9)
{
                            WorldGen.underworldBG = style;
                            if (style == 1)
{
                                Main.underworldBG[0] = 5;
                                Main.underworldBG[1] = 6;
                                Main.underworldBG[2] = 7;
                                Main.underworldBG[3] = 8;
                                Main.underworldBG[4] = 9;
                                return;
                            }
                            if (style != 2)
{
                                Main.underworldBG[0] = 0;
                                Main.underworldBG[1] = 1;
                                Main.underworldBG[2] = 2;
                                Main.underworldBG[3] = 3;
                                Main.underworldBG[4] = 4;
                                return;
                            }
                            Main.underworldBG[0] = 10;
                            Main.underworldBG[1] = 11;
                            Main.underworldBG[2] = 12;
                            Main.underworldBG[3] = 13;
                            Main.underworldBG[4] = 9;
                        }
                        return;
                    }
                    WorldGen.mushroomBG = style;
                    switch (style)
                    {
                    case 1:
                        Main.mushroomBG[0] = 231;
                        Main.mushroomBG[1] = 232;
                        Main.mushroomBG[2] = 233;
                        return;
                    case 2:
                        Main.mushroomBG[0] = 234;
                        Main.mushroomBG[1] = 235;
                        Main.mushroomBG[2] = 236;
                        return;
                    case 3:
                        Main.mushroomBG[0] = 287;
                        Main.mushroomBG[1] = 288;
                        Main.mushroomBG[2] = 289;
                        return;
                    case 4:
                        Main.mushroomBG[0] = 321;
                        Main.mushroomBG[1] = 320;
                        Main.mushroomBG[2] = 319;
                        return;
                    default:
                        Main.mushroomBG[0] = 46;
                        Main.mushroomBG[1] = 47;
                        Main.mushroomBG[2] = 48;
                        return;
                    }
                }
            }
        }
References Terraria.DataStructures.BackgroundVariantSet.Clear(), Terraria.DataStructures.BackgroundVariantSet.Corrupt, Terraria.Main.corruptBG, Terraria.DataStructures.BackgroundVariantSet.Crimson, Terraria.Main.crimsonBG, Terraria.Main.desertBackgroundSet, Terraria.DataStructures.BackgroundVariantSet.Hallow, Terraria.Main.hallowBG, Terraria.Main.jungleBG, Terraria.Main.mushroomBG, Terraria.DataStructures.BackgroundVariantSet.Pure, Terraria.DataStructures.BackgroundVariant.Set(), Terraria.WorldGen.SetForestBGSet(), Terraria.Main.snowBG, Terraria.Main.snowMntBG, Terraria.Main.treeBGSet1, Terraria.Main.treeBGSet2, Terraria.Main.treeBGSet3, Terraria.Main.treeBGSet4, Terraria.Main.treeMntBGSet1, Terraria.Main.treeMntBGSet2, Terraria.Main.treeMntBGSet3, Terraria.Main.treeMntBGSet4, and Terraria.Main.underworldBG.
Referenced by Terraria.MessageBuffer.GetData(), Terraria.IO.WorldFile.LoadHeader(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.WorldGen.RandomizeBackgroundBasedOnPlayer(), Terraria.WorldGen.RandomizeBackgrounds(), and Terraria.Main.UpdateMenu().