Terraria Decompiled: Terraria.WorldGen.GetItemSource_FromTileBreak
GetItemSource_FromTileBreak()
static IEntitySource Terraria.WorldGen.GetItemSource_FromTileBreak (int x, int y) inline static
Definition at line 69737 of file WorldGen.cs.
        {
            return new EntitySource_TileBreak(x, y);
        }
Referenced by Terraria.WorldGen.Check1x2(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check1xX(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check2x2Style(), Terraria.WorldGen.Check2x3Wall(), Terraria.WorldGen.Check2x5(), Terraria.WorldGen.Check2xX(), Terraria.WorldGen.Check3x1(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x2Wall(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check3x3Wall(), Terraria.WorldGen.Check3x4(), Terraria.WorldGen.Check3x5(), Terraria.WorldGen.Check3x6(), Terraria.WorldGen.Check4x2(), Terraria.WorldGen.Check4x3Wall(), Terraria.WorldGen.Check4x4(), Terraria.WorldGen.Check5x4(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.Check6x4Wall(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCannon(), Terraria.WorldGen.CheckChand(), Terraria.WorldGen.CheckChest(), Terraria.WorldGen.CheckGnome(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckMan(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckStalactiteEcho(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTrapDoor(), Terraria.WorldGen.CheckWeaponsRack(), Terraria.WorldGen.CheckWoman(), Terraria.WorldGen.CheckXmasTree(), Terraria.WorldGen.DropDoorItem(), Terraria.WorldGen.dropXmasTree(), Terraria.Player.ItemCheck_CutTiles(), Terraria.WorldGen.KillActuator(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_DropBait(), Terraria.WorldGen.KillTile_DropItems(), Terraria.WorldGen.KillWire(), Terraria.WorldGen.KillWire2(), Terraria.WorldGen.KillWire3(), Terraria.WorldGen.KillWire4(), Terraria.Player.PlaceThing_PaintScrapper_LongMoss(), Terraria.WorldGen.ShakeTree(), Terraria.WorldGen.SpawnThingsFromPot(), and Terraria.WorldGen.ToggleGemLock().