Terraria Decompiled: Terraria.WorldGen.RoomNeeds
RoomNeeds()
static bool Terraria.WorldGen.RoomNeeds () inline static
Definition at line 1429 of file WorldGen.cs.
        {
            WorldGen.roomChair = false;
            WorldGen.roomDoor = false;
            WorldGen.roomTable = false;
            WorldGen.roomTorch = false;
            for (int i = 0; i < TileID.Sets.RoomNeeds.CountsAsChairTypes.Length; i++)
            {
                if (WorldGen.houseTile[TileID.Sets.RoomNeeds.CountsAsChairTypes[i]])
                {
                    WorldGen.roomChair = true;
                    break;
                }
            }
            for (int j = 0; j < TileID.Sets.RoomNeeds.CountsAsTableTypes.Length; j++)
            {
                if (WorldGen.houseTile[TileID.Sets.RoomNeeds.CountsAsTableTypes[j]])
                {
                    WorldGen.roomTable = true;
                    break;
                }
            }
            for (int k = 0; k < TileID.Sets.RoomNeeds.CountsAsTorchTypes.Length; k++)
            {
                if (WorldGen.houseTile[TileID.Sets.RoomNeeds.CountsAsTorchTypes[k]])
                {
                    WorldGen.roomTorch = true;
                    break;
                }
            }
            for (int l = 0; l < TileID.Sets.RoomNeeds.CountsAsDoorTypes.Length; l++)
            {
                if (WorldGen.houseTile[TileID.Sets.RoomNeeds.CountsAsDoorTypes[l]])
                {
                    WorldGen.roomDoor = true;
                    break;
                }
            }
            if (WorldGen.roomChair && WorldGen.roomTable && WorldGen.roomDoor && WorldGen.roomTorch)
            {
                WorldGen.canSpawn = true;
            }
            else
            {
                WorldGen.canSpawn = false;
            }
            return WorldGen.canSpawn;
        }
References Terraria.WorldGen.canSpawn, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsChairTypes, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsDoorTypes, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsTableTypes, Terraria.ID.TileID.Sets.RoomNeeds.CountsAsTorchTypes, Terraria.WorldGen.houseTile, Terraria.WorldGen.roomChair, Terraria.WorldGen.roomDoor, Terraria.WorldGen.roomTable, and Terraria.WorldGen.roomTorch.
Referenced by Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().