Terraria Decompiled: Terraria.WorldGen.TransformWorldOnBackgroundThread
TransformWorldOnBackgroundThread()
static void Terraria.WorldGen.TransformWorldOnBackgroundThread (Action transform, Action mainThreadFollowup) inline static
Definition at line 29092 of file WorldGen.cs.
        {
            Interlocked.Increment(ref WorldGen._transformingWorld);
            Task.Factory.StartNew(delegate
            {
                try
                {
                    object iolock = WorldFile.IOLock;
                    lock (iolock)
                    {
                        transform();
                    }
                }
                finally
                {
                    Interlocked.Decrement(ref WorldGen._transformingWorld);
                    if (mainThreadFollowup != null)
                    {
                        Main.QueueMainThreadAction(mainThreadFollowup);
                    }
                }
            });
        }
References Terraria.WorldGen._transformingWorld, System.Threading.Interlocked.Decrement(), System.Threading.Tasks.Task< TResult >.Factory, System.Threading.Interlocked.Increment(), Terraria.IO.WorldFile.IOLock, Terraria.Main.QueueMainThreadAction(), and System.Threading.Tasks.TaskFactory< TResult >.StartNew().
Referenced by Terraria.WorldGen.ClearUnbreakableWallsWithPaintUpTo(), and Terraria.WorldGen.StartHardmode().