Terraria Decompiled: Terraria.WorldGen.Check5x4
Check5x4()
static void Terraria.WorldGen.Check5x4 (int i, int j, int type) inline static
Definition at line 48651 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int num = 0;
            int k;
            for (k = (int)(Main.tile[i, j].frameX / 18); k >= 5; k -= 5)
            {
                num++;
            }
            int num2 = i - k;
            int num3 = j + (int)(Main.tile[i, j].frameY / 18 * -1);
            for (int l = num2; l < num2 + 5; l++)
            {
                for (int m = num3; m < num3 + 4; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || (int)Main.tile[l, m].frameX != num * 90 + (l - num2) * 18 || (int)Main.tile[l, m].frameY != (m - num3) * 18)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[l, num3 + 4] == null)
                {
                    Main.tile[l, num3 + 4] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(l, num3 + 4))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int n = num2; n < num2 + 5; n++)
                {
                    for (int num4 = num3; num4 < num3 + 4; num4++)
                    {
                        if ((int)Main.tile[n, num4].type == type && Main.tile[n, num4].active())
{
                            WorldGen.KillTile(n, num4, false, false, false);
                        }
                    }
                }
                if (type == 464)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3814, 1, false, 0, false);
                }
                if (type == 466)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3816, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                for (int num5 = num2 - 1; num5 < num2 + 6; num5++)
                {
                    for (int num6 = num3 - 1; num6 < num3 + 5; num6++)
                    {
                        WorldGen.TileFrame(num5, num6, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().