Terraria Decompiled: Terraria.WorldGen.KillWall
KillWall()
static void Terraria.WorldGen.KillWall (int i, int j, bool fail = false) inline static
Definition at line 59045 of file WorldGen.cs.
        {
            if (i >= 0 && j >= 0 && i < Main.maxTilesX && j < Main.maxTilesY)
            {
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    tile = new Tile();
                    Main.tile[i, j] = tile;
                }
                if (tile.wall > 0)
                {
                    fail = WorldGen.KillWall_CheckFailure(fail, tile);
                    WorldGen.KillWall_PlaySounds(i, j, tile);
                    int num = 10;
                    if (fail)
                    {
                        num = 3;
                    }
                    for (int k = 0; k < num; k++)
                    {
                        WorldGen.KillWall_MakeWallDust(i, j, tile);
                    }
                    if (fail)
                    {
                        WorldGen.SquareWallFrame(i, j, true);
                        return;
                    }
                    WorldGen.KillWall_DropItems(i, j, tile);
                    tile.wall = 0;
                    tile.ClearWallPaintAndCoating();
                    WorldGen.SquareWallFrame(i, j, true);
                    if (tile.type >= 0 && tile.type < TileID.Count && TileID.Sets.FramesOnKillWall[(int)tile.type])
                    {
                        WorldGen.TileFrame(i, j, false, false);
                    }
                }
            }
        }
References Terraria.Tile.ClearWallPaintAndCoating(), Terraria.ID.TileID.Count, Terraria.ID.TileID.Sets.FramesOnKillWall, Terraria.WorldGen.KillWall_CheckFailure(), Terraria.WorldGen.KillWall_DropItems(), Terraria.WorldGen.KillWall_MakeWallDust(), Terraria.WorldGen.KillWall_PlaySounds(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.SquareWallFrame(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.Projectile.ExplodeTiles(), Terraria.MessageBuffer.GetData(), and Terraria.Player.PickWall().