Terraria Decompiled: Terraria.WorldGen.countWires
countWires()
static int Terraria.WorldGen.countWires (int x, int y, int size) inline static
Definition at line 5447 of file WorldGen.cs.
        {
            int num = 0;
            for (int i = x - size; i <= x + size; i++)
            {
                for (int j = y - size; j <= y + size; j++)
                {
                    if (WorldGen.InWorld(i, j, 0))
                    {
                        if (Main.tile[i, j].wire())
{
                            num++;
                        }
                        if (Main.tile[i, j].wire2())
{
                            num++;
                        }
                        if (Main.tile[i, j].wire3())
{
                            num++;
                        }
                        if (Main.tile[i, j].wire4())
{
                            num++;
                        }
                    }
                }
            }
            return num;
        }
References Terraria.WorldGen.InWorld(), Terraria.Main.tile, Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.IsAGoodSpot().