Terraria Decompiled: Terraria.WorldGen.OrePatch
OrePatch()
static bool Terraria.WorldGen.OrePatch (int X, int Y) inline static
Definition at line 6578 of file WorldGen.cs.
        {
            ushort num = (ushort)WorldGen.SavedOreTiers.Copper;
            if (WorldGen.genRand.Next(3) == 0)
            {
                num = (ushort)WorldGen.SavedOreTiers.Iron;
            }
            int num2 = X;
            int i = Y;
            while (!WorldGen.SolidTile(num2, i, false))
            {
                i++;
                if ((double)i > Main.worldSurface)
                {
                    return false;
                }
            }
            if (!TileID.Sets.Conversion.Grass[(int)Main.tile[num2, i].type] || !TileID.Sets.Conversion.Grass[(int)Main.tile[num2 - 1, i].type] || !TileID.Sets.Conversion.Grass[(int)Main.tile[num2 + 1, i].type])
            {
                return false;
            }
            if (Main.tile[num2, i].wall > 0)
            {
                return false;
            }
            for (int j = num2 - 10; j <= num2 + 10; j++)
            {
                for (int k = i + 7; k <= i + 30; k++)
                {
                    if (!Main.tile[j, k].active() || Main.tileDungeon[(int)Main.tile[j, k].type] || TileID.Sets.Clouds[(int)Main.tile[j, k].type] || TileID.Sets.Conversion.Sand[(int)Main.tile[j, k].type] || Main.tile[j, k].wall == 0)
                    {
                        return false;
                    }
                }
            }
            i += WorldGen.genRand.Next(2);
            Main.tile[num2, i].type = num;
            Main.tile[num2, i].active(true);
            WorldGen.OreHelper(num2, i);
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                WorldGen.SquareTileFrame(num2, i, true);
            }
            int num3 = i;
            while (i < num3 + WorldGen.genRand.Next(8, 13))
            {
                num2 += WorldGen.genRand.Next(-1, 2);
                i += WorldGen.genRand.Next(1, 3);
                if (WorldGen.genRand.Next(3) == 0)
                {
                    i++;
                }
                Main.tile[num2, i].type = num;
                Main.tile[num2, i].active(true);
                WorldGen.OreHelper(num2, i);
                if (!WorldGen.isGeneratingOrLoadingWorld)
                {
                    WorldGen.SquareTileFrame(num2, i, true);
                }
                if (WorldGen.genRand.Next(4) == 0)
                {
                    int num4 = num2 + WorldGen.genRand.Next(-2, 3);
                    int num5 = i + WorldGen.genRand.Next(2);
                    Main.tile[num4, num5].type = num;
                    Main.tile[num4, num5].active(true);
                    WorldGen.OreHelper(num4, num5);
                    if (!WorldGen.isGeneratingOrLoadingWorld)
                    {
                        WorldGen.SquareTileFrame(num4, num5, true);
                    }
                }
            }
            Vector2D vector2D;
            vector2D..ctor((double)num2, (double)i);
            Vector2D vector2D2;
            vector2D2.X = WorldGen.genRand.NextDouble() * 0.6 - 0.3;
            vector2D2.Y = WorldGen.genRand.NextDouble() * 0.5 + 0.5;
            double num6 = (double)WorldGen.genRand.Next(5, 9);
            int l = WorldGen.genRand.Next(9, 14);
            if (WorldGen.genRand.Next(3) == 0)
            {
                num6 += (double)WorldGen.genRand.Next(2);
            }
            if (WorldGen.genRand.Next(3) == 0)
            {
                l += WorldGen.genRand.Next(2);
            }
            while (l > 0)
            {
                l--;
                int num7 = num2 - (int)num6 * 4;
                while ((double)num7 <= (double)num2 + num6 * 4.0)
                {
                    int num8 = i - (int)num6 * 4;
                    while ((double)num8 <= (double)i + num6 * 4.0)
                    {
                        double num9 = num6 * (0.5 + WorldGen.genRand.NextDouble() * 0.5) * 0.1;
                        double num10 = num6 * (0.7 + WorldGen.genRand.NextDouble() * 0.6) * 0.3;
                        if (WorldGen.genRand.Next(8) == 0)
{
                            num10 *= 2.0;
                        }
                        Vector2D vector2D3 = vector2D - new Vector2D((double)num7, (double)num8);
                        if (vector2D3.Length() < num9)
{
                            Main.tile[num7, num8].active(false);
                        }
                        else if (vector2D3.Length() < num10)
{
                            Main.tile[num7, num8].type = num;
                            if (WorldGen.genRand.Next(4) == 0)
{
                                Main.tile[num7, num8].active(true);
                            }
                            WorldGen.OreHelper(num7, num8);
                            if (!WorldGen.isGeneratingOrLoadingWorld)
{
                                WorldGen.SquareTileFrame(num7, num8, true);
                            }
                        }
                        num8++;
                    }
                    num7++;
                }
                vector2D += vector2D2;
                vector2D2.X += WorldGen.genRand.NextDouble() * 0.2 - 0.1;
                vector2D2.Y += WorldGen.genRand.NextDouble() * 0.2 - 0.1;
                Utils.Clamp<double>(vector2D2.X, -0.3, 0.3);
                Utils.Clamp<double>(vector2D2.Y, 0.5, 1.0);
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.SavedOreTiers.Copper, Terraria.WorldGen.genRand, Terraria.ID.TileID.Sets.Conversion.Grass, int, Terraria.WorldGen.SavedOreTiers.Iron, Terraria.WorldGen.isGeneratingOrLoadingWorld, ReLogic.Utilities.Vector2D.Length(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.OreHelper(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.worldSurface, System.X, ReLogic.Utilities.Vector2D.X, System.Y, and ReLogic.Utilities.Vector2D.Y.