Terraria Decompiled: Terraria.WorldGen.TryToggleLight
TryToggleLight()
static bool Terraria.WorldGen.TryToggleLight (int x, int y, bool? forcedState, bool skipWires) inline static
Definition at line 73397 of file WorldGen.cs.
        {
            Tile tile = Main.tile[x, y];
            if (!tile.active())
            {
                return false;
            }
            if (TileID.Sets.Torches[(int)tile.type])
            {
                Wiring.ToggleTorch(x, y, tile, forcedState);
                return true;
            }
            if (TileID.Sets.Campfires[(int)tile.type])
            {
                Wiring.ToggleCampFire(x, y, tile, forcedState, skipWires);
                return true;
            }
            ushort type = tile.type;
            if (type <= 126)
            {
                if (type <= 42)
                {
                    if (type == 33)
                    {
                        goto IL_00FA;
                    }
                    if (type == 34)
                    {
                        Wiring.ToggleChandelier(x, y, tile, forcedState, skipWires);
                        return true;
                    }
                    if (type == 42)
                    {
                        Wiring.ToggleHangingLantern(x, y, tile, forcedState, skipWires);
                        return true;
                    }
                }
                else if (type <= 95)
                {
                    if (type == 49)
                    {
                        goto IL_00FA;
                    }
                    switch (type)
                    {
                    case 92:
                        Wiring.ToggleLampPost(x, y, tile, forcedState, skipWires);
                        return true;
                    case 93:
                        Wiring.ToggleLamp(x, y, tile, forcedState, skipWires);
                        return true;
                    case 95:
                        goto IL_0111;
                    }
                }
                else if (type == 100 || type == 126)
                {
                    goto IL_0111;
                }
            }
            else if (type <= 174)
            {
                if (type == 149)
                {
                    Wiring.ToggleHolidayLight(x, y, tile, forcedState);
                    return true;
                }
                if (type == 173)
                {
                    goto IL_0111;
                }
                if (type == 174)
                {
                    goto IL_00FA;
                }
            }
            else if (type <= 405)
            {
                if (type == 372)
                {
                    goto IL_00FA;
                }
                if (type == 405)
                {
                    Wiring.ToggleFirePlace(x, y, tile, forcedState, skipWires);
                    return true;
                }
            }
            else
            {
                if (type == 564)
                {
                    goto IL_0111;
                }
                if (type == 646)
                {
                    goto IL_00FA;
                }
            }
            return false;
            IL_00FA:
            Wiring.ToggleCandle(x, y, tile, forcedState);
            return true;
            IL_0111:
            Wiring.Toggle2x2Light(x, y, tile, forcedState, skipWires);
            return true;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Campfires, Terraria.Main.tile, Terraria.Wiring.Toggle2x2Light(), Terraria.Wiring.ToggleCampFire(), Terraria.Wiring.ToggleCandle(), Terraria.Wiring.ToggleChandelier(), Terraria.Wiring.ToggleFirePlace(), Terraria.Wiring.ToggleHangingLantern(), Terraria.Wiring.ToggleHolidayLight(), Terraria.Wiring.ToggleLamp(), Terraria.Wiring.ToggleLampPost(), Terraria.Wiring.ToggleTorch(), Terraria.ID.TileID.Sets.Torches, and Terraria.Tile.type.
Referenced by Terraria.Projectile.AI(), and Terraria.WorldGen.DontStarveTryWateringTile().