Terraria Decompiled: Terraria.WorldGen.PlaceTight
PlaceTight()
static void Terraria.WorldGen.PlaceTight (int x, int y, bool spiders = false) inline static
Definition at line 35768 of file WorldGen.cs.
        {
            if (Main.tile[x, y - 1] == null)
            {
                Main.tile[x, y - 1] = new Tile();
            }
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            if (Main.tile[x, y + 1] == null)
            {
                Main.tile[x, y + 1] = new Tile();
            }
            if (Main.tile[x, y].anyShimmer())
            {
                return;
            }
            if (Main.tile[x, y].active() && Main.tile[x, y].type == 231)
            {
                return;
            }
            WorldGen.PlaceUncheckedStalactite(x, y, WorldGen.genRand.Next(2) == 0, WorldGen.genRand.Next(3), spiders);
            if (Main.tile[x, y].active() && Main.tile[x, y].type == 165)
            {
                WorldGen.CheckStalactite(x, y);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.anyShimmer(), Terraria.WorldGen.CheckStalactite(), Terraria.WorldGen.genRand, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceUncheckedStalactite(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Generation.ActionStalagtite.Apply(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.Spread.Spider(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().