Terraria Decompiled: Terraria.WorldGen.nextCount
nextCount()
static void Terraria.WorldGen.nextCount (int x, int y, bool jungle = false, bool lavaOk = false) inline static
Definition at line 5493 of file WorldGen.cs.
        {
            if (WorldGen.numTileCount >= WorldGen.maxTileCount)
            {
                return;
            }
            if (x <= 1 || x >= Main.maxTilesX - 1 || y <= 1 || y >= Main.maxTilesY - 1)
            {
                WorldGen.numTileCount = WorldGen.maxTileCount;
                return;
            }
            if (WorldGen.CountedTiles.ContainsKey(new Point(x, y)))
            {
                return;
            }
            if (Main.tile[x, y].wall == 244)
            {
                WorldGen.numTileCount = WorldGen.maxTileCount;
                return;
            }
            if (Main.tile[x, y].shimmer() && Main.tile[x, y].liquid > 0)
            {
                WorldGen.numTileCount = WorldGen.maxTileCount;
                return;
            }
            if (!jungle)
            {
                if (Main.tile[x, y].wall != 0)
                {
                    WorldGen.numTileCount = WorldGen.maxTileCount;
                    return;
                }
                if (!lavaOk)
                {
                    if (Main.tile[x, y].lava() && Main.tile[x, y].liquid > 0)
                    {
                        WorldGen.lavaCount++;
                        WorldGen.numTileCount = WorldGen.maxTileCount;
                        return;
                    }
                }
                else if (Main.tile[x, y].lava() && Main.tile[x, y].liquid > 0)
                {
                    WorldGen.lavaCount++;
                }
            }
            if (Main.tile[x, y].active())
            {
                if (Main.tile[x, y].type == 70)
                {
                    WorldGen.shroomCount++;
                }
                if (Main.tile[x, y].type == 1)
                {
                    WorldGen.rockCount++;
                }
                if (Main.tile[x, y].type == 147 || Main.tile[x, y].type == 161)
                {
                    WorldGen.iceCount++;
                }
                if (Main.tile[x, y].type == 53 || Main.tile[x, y].type == 396 || Main.tile[x, y].type == 397)
                {
                    WorldGen.sandCount++;
                }
            }
            if (!WorldGen.SolidTile(x, y, false))
            {
                WorldGen.CountedTiles.Add(new Point(x, y), true);
                WorldGen.numTileCount++;
                WorldGen.nextCount(x - 1, y, jungle, lavaOk);
                WorldGen.nextCount(x + 1, y, jungle, lavaOk);
                WorldGen.nextCount(x, y - 1, jungle, lavaOk);
                WorldGen.nextCount(x, y + 1, jungle, lavaOk);
            }
        }
References Terraria.Tile.active(), System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), Terraria.WorldGen.CountedTiles, Terraria.WorldGen.iceCount, Terraria.Tile.lava(), Terraria.WorldGen.lavaCount, Terraria.Tile.liquid, Terraria.WorldGen.maxTileCount, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.nextCount(), Terraria.WorldGen.numTileCount, Terraria.WorldGen.rockCount, Terraria.WorldGen.sandCount, Terraria.Tile.shimmer(), Terraria.WorldGen.shroomCount, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.countTiles(), and Terraria.WorldGen.nextCount().