Terraria Decompiled: Terraria.WorldGen.MatureTheHerbPlants
MatureTheHerbPlants()
static void Terraria.WorldGen.MatureTheHerbPlants () inline static private
Definition at line 44076 of file WorldGen.cs.
        {
            for (int i = 10; i < Main.maxTilesX - 10; i++)
            {
                for (int j = 10; j < Main.maxTilesY - 10; j++)
                {
                    if ((double)j > Main.rockLayer && (Main.tile[i, j + 1].type == 59 || Main.tile[i, j + 1].type == 0) && WorldGen.SolidTile(i, j + 1, false) && !Main.tile[i, j].active() && Main.tile[i, j].liquid == 0 && WorldGen.genRand.Next(25) == 0)
                    {
                        Main.tile[i, j].active(true);
                        Main.tile[i, j].type = 82;
                        Main.tile[i, j].frameX = 36;
                        Main.tile[i, j].frameY = 0;
                    }
                    if (Main.tile[i, j].type == 82 && WorldGen.genRand.Next(3) == 0)
                    {
                        Main.tile[i, j].type = 83;
                        if (Main.tile[i, j].frameX == 36 && WorldGen.genRand.Next(2) == 0)
{
                            Main.tile[i, j].type = 84;
                        }
                        if (Main.tile[i, j].frameX == 108 && WorldGen.genRand.Next(3) == 0)
{
                            Main.tile[i, j].type = 84;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rockLayer, Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.