Terraria Decompiled: Terraria.WorldGen.GetTileMergeCulling
GetTileMergeCulling()
static WorldGen.TileMergeCullCache Terraria.WorldGen.GetTileMergeCulling (Tile tileCache, Tile tileTopCache, Tile tileBottomCache, Tile tileLeftCache, Tile tileRightCache, Tile tileBottomLeftCache, Tile tileBottomRightCache, Tile tileTopLeftCache, Tile tileTopRightCache) inline static
Definition at line 85633 of file WorldGen.cs.
        {
            WorldGen.TileMergeCullCache tileMergeCullCache;
            if (Main.ShouldShowInvisibleBlocksAndWalls())
            {
                tileMergeCullCache = default(WorldGen.TileMergeCullCache);
                return tileMergeCullCache;
            }
            bool flag = tileCache.invisibleBlock();
            tileMergeCullCache = new WorldGen.TileMergeCullCache
            {
                CullTop = (tileTopCache != null && tileTopCache.invisibleBlock() != flag),
                CullBottom = (tileBottomCache != null && tileBottomCache.invisibleBlock() != flag),
                CullLeft = (tileLeftCache != null && tileLeftCache.invisibleBlock() != flag),
                CullRight = (tileRightCache != null && tileRightCache.invisibleBlock() != flag),
                CullTopLeft = (tileTopLeftCache != null && tileTopLeftCache.invisibleBlock() != flag),
                CullTopRight = (tileTopRightCache != null && tileTopRightCache.invisibleBlock() != flag),
                CullBottomLeft = (tileBottomLeftCache != null && tileBottomLeftCache.invisibleBlock() != flag),
                CullBottomRight = (tileBottomRightCache != null && tileBottomRightCache.invisibleBlock() != flag)
            };
            return tileMergeCullCache;
        }
References Terraria.Tile.invisibleBlock(), and Terraria.Main.ShouldShowInvisibleBlocksAndWalls().
Referenced by Terraria.WorldGen.TileFrameCosmetic(), and Terraria.WorldGen.TileFrameImportant().