Terraria Decompiled: Terraria.WorldGen.AddBeeLarva
AddBeeLarva()
static void Terraria.WorldGen.AddBeeLarva (int x, int y) inline static
Definition at line 29444 of file WorldGen.cs.
        {
            for (int i = x - 1; i <= x + 1; i++)
            {
                for (int j = y - 2; j <= y + 1; j++)
                {
                    if (j != y + 1)
                    {
                        Main.tile[i, j].ClearTile();
                    }
                    else
                    {
                        ushort wall = Main.tile[i, j].wall;
                        Main.tile[i, j].ClearEverything();
                        Main.tile[i, j].active(true);
                        Main.tile[i, j].type = 225;
                        Main.tile[i, j].wall = wall;
                    }
                }
            }
            WorldGen.PlaceTile(x, y, 231, true, false, -1, 0);
        }
References Terraria.Tile.active(), Terraria.Tile.ClearEverything(), Terraria.Tile.ClearTile(), Terraria.WorldGen.PlaceTile(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures().