Terraria Decompiled: Terraria.WorldGen.TopEdgeCanBeAttachedTo
TopEdgeCanBeAttachedTo()
static bool Terraria.WorldGen.TopEdgeCanBeAttachedTo (int i, int j) inline static
Definition at line 70657 of file WorldGen.cs.
        {
            try
            {
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    return true;
                }
                if (tile.active() && (Main.tileSolid[(int)tile.type] || Main.tileSolidTop[(int)tile.type]) && (!tile.topSlope() || (TileID.Sets.Platforms[(int)tile.type] && WorldGen.PlatformProperTopFrame(tile.frameX))) && !tile.halfBrick() && !tile.inActive())
                {
                    return true;
                }
            }
            catch
            {
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.WorldGen.PlatformProperTopFrame(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.WorldGen.CheckSign(), Terraria.WorldGen.CheckTorch(), Terraria.GameContent.Drawing.TileDrawing.CrawlToBottomOfReverseVineAndAddSpecialPoint(), and Terraria.WorldGen.PlaceTile().