Terraria Decompiled: Terraria.WorldGen.PlaceCatTail
PlaceCatTail()
static Point Terraria.WorldGen.PlaceCatTail (int x, int j) inline static
Definition at line 57350 of file WorldGen.cs.
        {
            int num = j;
            Point point = new Point(-1, -1);
            if (x < 50 || x > Main.maxTilesX - 50 || num < 50 || num > Main.maxTilesY - 50)
            {
                return point;
            }
            if ((Main.tile[x, num].active() && Main.tile[x, num].type != 71) || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
            {
                return point;
            }
            while (Main.tile[x, num].liquid > 0 && num > 50)
            {
                num--;
            }
            num++;
            if (Main.tile[x, num].active() || Main.tile[x, num - 1].active() || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
            {
                return point;
            }
            if (Main.tile[x, num].wall != 0 && Main.tile[x, num].wall != 80 && Main.tile[x, num].wall != 81 && Main.tile[x, num].wall != 69 && (Main.tile[x, num].wall < 63 || Main.tile[x, num].wall > 68))
            {
                return point;
            }
            int num2 = 7;
            int num3 = 0;
            for (int i = x - num2; i <= x + num2; i++)
            {
                for (int k = num - num2; k <= num + num2; k++)
                {
                    if (Main.tile[i, k].active() && Main.tile[i, k].type == 519)
                    {
                        num3++;
                        break;
                    }
                }
            }
            if (num3 > 3)
            {
                return point;
            }
            int num4 = num;
            while ((!Main.tile[x, num4].active() || !Main.tileSolid[(int)Main.tile[x, num4].type] || Main.tileSolidTop[(int)Main.tile[x, num4].type]) && num4 < Main.maxTilesY - 50)
            {
                if (Main.tile[x, num4].active() && Main.tile[x, num4].type != 71)
                {
                    return point;
                }
                num4++;
            }
            int num5 = WorldGen.catTailDistance - 1;
            if (num4 - num > num5)
            {
                return point;
            }
            if (num4 - num < 2)
            {
                return point;
            }
            int type = (int)Main.tile[x, num4].type;
            if (!Main.tile[x, num4].nactive())
            {
                return point;
            }
            int num6 = -1;
            if (type == 2 || type == 477)
            {
                num6 = 0;
            }
            else if (type == 53)
            {
                if (x < WorldGen.beachDistance || x > Main.maxTilesX - WorldGen.beachDistance)
                {
                    return point;
                }
                num6 = 18;
            }
            else if (type == 199 || type == 662 || type == 234)
            {
                num6 = 54;
            }
            else if (type == 23 || type == 661 || type == 112)
            {
                num6 = 72;
            }
            else if (type == 70)
            {
                num6 = 90;
            }
            if (num6 < 0)
            {
                return point;
            }
            if (Main.tile[x, num4].topSlope() && WorldGen.isGeneratingOrLoadingWorld && WorldGen.genRand.Next(3) != 0)
            {
                Main.tile[x, num4].slope(0);
            }
            else if (Main.tile[x, num4].topSlope() || Main.tile[x, num4].halfBrick())
            {
                return point;
            }
            num = num4 - 1;
            Main.tile[x, num].active(true);
            Main.tile[x, num].type = 519;
            Main.tile[x, num].frameX = 0;
            Main.tile[x, num].frameY = (short)num6;
            Main.tile[x, num].halfBrick(false);
            Main.tile[x, num].slope(0);
            Main.tile[x, num].CopyPaintAndCoating(Main.tile[x, num + 1]);
            WorldGen.SquareTileFrame(x, num, true);
            point = new Point(x, num);
            return point;
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Terraria.Tile.CopyPaintAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Tile.slope(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.topSlope(), Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.PlaceTile(), and Terraria.WorldGen.UpdateWorld_GrassGrowth().