Terraria Decompiled: Terraria.WorldGen.PlaceTorchesAroundSpawn
PlaceTorchesAroundSpawn()
static void Terraria.WorldGen.PlaceTorchesAroundSpawn (int spawnX = -1, int spawnY = -1) inline static
Definition at line 22122 of file WorldGen.cs.
        {
            if (spawnX == -1)
            {
                spawnX = Main.spawnTileX;
            }
            if (spawnY == -1)
            {
                spawnY = Main.spawnTileY;
            }
            int num = 1;
            int num2 = 20;
            if (WorldGen.skyblockWorldGen)
            {
                num2 = 15;
            }
            int num3 = 2000;
            for (int i = 0; i < num3; i++)
            {
                if (num < 120)
                {
                    num++;
                }
                int num4 = spawnX - num;
                int num5 = spawnX + num;
                int num6 = spawnY - num;
                int num7 = spawnY + num;
                int num8 = WorldGen.genRand.Next(num4, num5);
                int num9 = WorldGen.genRand.Next(num6, num7);
                int num10 = 200;
                while (num10 > 0 && !WorldGen.InWorld(num8, num9, 50))
                {
                    num10--;
                    num8 = WorldGen.genRand.Next(num4, num5);
                    num9 = WorldGen.genRand.Next(num6, num7);
                }
                if (num10 <= 0)
                {
                    break;
                }
                int num11 = 1;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num11 *= -1;
                }
                if (!Main.tile[num8, num9].active() && Main.tile[num8, num9].liquid == 0)
                {
                    num10 = Main.maxTilesX / 2;
                    while (!Main.tile[num8, num9].active())
                    {
                        num10--;
                        if (num10 <= 0)
{
                            break;
                        }
                        num8 += num11;
                        if (!WorldGen.InWorld(num8, num9, 50))
{
                            num8 -= num11;
                            break;
                        }
                    }
                    if (num10 > 0)
                    {
                        num8 -= num11;
                        if (!WorldGen.IsTileNearby(num8, num9, 4, num2))
{
                            int num12 = 0;
                            if (WorldGen.IsTileNearby(num8, num9, 60, 25))
{
                                num12 = 21;
                            }
                            else if (WorldGen.IsTileNearby(num8, num9, 70, 25))
{
                                num12 = 22;
                            }
                            else if (WorldGen.IsTileNearby(num8, num9, 161, 25))
{
                                num12 = 9;
                            }
                            else if (WorldGen.IsTileNearby(num8, num9, 147, 25))
{
                                num12 = 9;
                            }
                            else if (WorldGen.IsTileNearby(num8, num9, 53, 25))
{
                                num12 = 16;
                            }
                            else if (WorldGen.IsTileNearby(num8, num9, 25, 25))
{
                                num12 = 18;
                            }
                            else if (WorldGen.IsTileNearby(num8, num9, 203, 25))
{
                                num12 = 19;
                            }
                            WorldGen.PlaceTile(num8, num9, 4, true, false, -1, num12);
                        }
                    }
                }
                else
                {
                    i--;
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsTileNearby(), Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.skyblockWorldGen, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, and Terraria.Main.tile.
Referenced by Terraria.WorldGen.SecretSeed.DoNoSurface(), Terraria.WorldGen.SecretSeed.DoRandomSpawn(), Terraria.WorldGen.GenerateSkyBlockWorld(), and Terraria.GameContent.ExtraSpawnPointManager.PrepareExtraSpawns().