Terraria Decompiled: Terraria.WorldGen.CloudIsland
CloudIsland()
static void Terraria.WorldGen.CloudIsland (int i, int j) inline static
Definition at line 78733 of file WorldGen.cs.
        {
            double num = (double)WorldGen.genRand.Next(100, 150);
            double num2 = (double)WorldGen.genRand.Next(20, 30);
            int num3 = i;
            int num4 = i;
            int num5 = j;
            int num6 = j;
            ushort num7 = 189;
            if (WorldGen.SecretSeed.extraFloatingIslands.Enabled && WorldGen.genRand.Next(3) == 0)
            {
                num7 = 718;
            }
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            while (vector2D2.X > -2.0 && vector2D2.X < 2.0)
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            }
            vector2D2.Y = (double)WorldGen.genRand.Next(-20, -10) * 0.02;
            while (num > 0.0 && num2 > 0.0)
            {
                num -= (double)WorldGen.genRand.Next(4);
                num2 -= 1.0;
                int num8 = (int)(vector2D.X - num * 0.5);
                int num9 = (int)(vector2D.X + num * 0.5);
                int num10 = (int)(vector2D.Y - num * 0.5);
                int num11 = (int)(vector2D.Y + num * 0.5);
                if (num8 < 0)
                {
                    num8 = 0;
                }
                if (num9 > Main.maxTilesX)
                {
                    num9 = Main.maxTilesX;
                }
                if (num10 < 0)
                {
                    num10 = 0;
                }
                if (num11 > Main.maxTilesY)
                {
                    num11 = Main.maxTilesY;
                }
                double num12 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                double num13 = vector2D.Y + 1.0;
                for (int k = num8; k < num9; k++)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num13 += (double)WorldGen.genRand.Next(-1, 2);
                    }
                    if (num13 < vector2D.Y)
                    {
                        num13 = vector2D.Y;
                    }
                    if (num13 > vector2D.Y + 2.0)
                    {
                        num13 = vector2D.Y + 2.0;
                    }
                    if (WorldGen.SecretSeed.surfaceIsInSpace.Enabled && !WorldGen.SecretSeed.errorWorld.Enabled)
                    {
                        double num14 = num13;
                        if (num14 < (double)num10)
{
                            num14 = (double)num10;
                        }
                        if (num14 > (double)num11)
{
                            num14 = (double)num11;
                        }
                        int num15 = 0;
                        while ((double)num15 <= num14)
{
                            if (TileID.Sets.Clouds[(int)Main.tile[k, num15].type])
{
                                Main.tile[k, num15].active(false);
                            }
                            num15++;
                        }
                    }
                    for (int l = num10; l < num11; l++)
                    {
                        if ((double)l > num13)
{
                            double num16 = Math.Abs((double)k - vector2D.X);
                            double num17 = Math.Abs((double)l - vector2D.Y) * 3.0;
                            if (Math.Sqrt(num16 * num16 + num17 * num17) < num12 * 0.4)
{
                                if (k < num3)
{
                                    num3 = k;
                                }
                                if (k > num4)
{
                                    num4 = k;
                                }
                                if (l < num5)
{
                                    num5 = l;
                                }
                                if (l > num6)
{
                                    num6 = l;
                                }
                                Main.tile[k, l].active(true);
                                Main.tile[k, l].type = num7;
                                WorldGen.SquareTileFrame(k, l, true);
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-20, 21) * 0.05;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                if (vector2D2.Y > 0.2)
                {
                    vector2D2.Y = -0.2;
                }
                if (vector2D2.Y < -0.2)
                {
                    vector2D2.Y = -0.2;
                }
            }
            int m = num3;
            int num19;
            for (m += WorldGen.genRand.Next(5); m < num4; m += WorldGen.genRand.Next(num19, (int)((double)num19 * 1.5)))
            {
                int num18 = num6;
                while (WorldGen.InWorld(m, num18, 15) && !Main.tile[m, num18].active())
                {
                    num18--;
                }
                num18 += WorldGen.genRand.Next(-3, 4);
                num19 = WorldGen.genRand.Next(4, 8);
                int num20 = (int)num7;
                if (WorldGen.genRand.Next(4) == 0)
                {
                    num20 = 196;
                }
                for (int n = m - num19; n <= m + num19; n++)
                {
                    for (int num21 = num18 - num19; num21 <= num18 + num19; num21++)
                    {
                        if (num21 > num5)
{
                            double num22 = (double)Math.Abs(n - m);
                            double num23 = (double)(Math.Abs(num21 - num18) * 2);
                            if (Math.Sqrt(num22 * num22 + num23 * num23) < (double)(num19 + WorldGen.genRand.Next(2)))
{
                                Main.tile[n, num21].active(true);
                                Main.tile[n, num21].type = (ushort)num20;
                                WorldGen.SquareTileFrame(n, num21, true);
                            }
                        }
                    }
                }
            }
            num = (double)WorldGen.genRand.Next(80, 95);
            num2 = (double)WorldGen.genRand.Next(10, 15);
            vector2D.X = (double)i;
            vector2D.Y = (double)num5;
            vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            while (vector2D2.X > -2.0 && vector2D2.X < 2.0)
            {
                vector2D2.X = (double)WorldGen.genRand.Next(-20, 21) * 0.2;
            }
            vector2D2.Y = (double)WorldGen.genRand.Next(-20, -10) * 0.02;
            while (num > 0.0 && num2 > 0.0)
            {
                num -= (double)WorldGen.genRand.Next(4);
                num2 -= 1.0;
                int num8 = (int)(vector2D.X - num * 0.5);
                int num9 = (int)(vector2D.X + num * 0.5);
                int num10 = num5 - 1;
                int num11 = (int)(vector2D.Y + num * 0.5);
                if (num8 < 0)
                {
                    num8 = 0;
                }
                if (num9 > Main.maxTilesX)
                {
                    num9 = Main.maxTilesX;
                }
                if (num10 < 0)
                {
                    num10 = 0;
                }
                if (num11 > Main.maxTilesY)
                {
                    num11 = Main.maxTilesY;
                }
                double num12 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                double num24 = vector2D.Y + 1.0;
                for (int num25 = num8; num25 < num9; num25++)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num24 += (double)WorldGen.genRand.Next(-1, 2);
                    }
                    if (num24 < vector2D.Y)
                    {
                        num24 = vector2D.Y;
                    }
                    if (num24 > vector2D.Y + 2.0)
                    {
                        num24 = vector2D.Y + 2.0;
                    }
                    for (int num26 = num10; num26 < num11; num26++)
                    {
                        if ((double)num26 > num24)
{
                            double num27 = Math.Abs((double)num25 - vector2D.X);
                            double num28 = Math.Abs((double)num26 - vector2D.Y) * 3.0;
                            if (Math.Sqrt(num27 * num27 + num28 * num28) < num12 * 0.4 && Main.tile[num25, num26].type == num7)
{
                                Main.tile[num25, num26].type = 0;
                                WorldGen.SquareTileFrame(num25, num26, true);
                            }
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-20, 21) * 0.05;
                if (vector2D2.X > 1.0)
                {
                    vector2D2.X = 1.0;
                }
                if (vector2D2.X < -1.0)
                {
                    vector2D2.X = -1.0;
                }
                if (vector2D2.Y > 0.2)
                {
                    vector2D2.Y = -0.2;
                }
                if (vector2D2.Y < -0.2)
                {
                    vector2D2.Y = -0.2;
                }
            }
            int num29 = num3;
            num29 += WorldGen.genRand.Next(5);
            while (num29 < num4)
            {
                int num30 = num6;
                while ((!Main.tile[num29, num30].active() || Main.tile[num29, num30].type != 0) && num29 < num4)
                {
                    num30--;
                    if (num30 < num5)
                    {
                        num30 = num6;
                        num29 += WorldGen.genRand.Next(1, 4);
                    }
                }
                if (num29 < num4)
                {
                    num30 += WorldGen.genRand.Next(0, 4);
                    int num31 = WorldGen.genRand.Next(2, 5);
                    int num32 = (int)num7;
                    for (int num33 = num29 - num31; num33 <= num29 + num31; num33++)
                    {
                        for (int num34 = num30 - num31; num34 <= num30 + num31; num34++)
{
                            if (num34 > num5)
{
                                double num35 = (double)Math.Abs(num33 - num29);
                                double num36 = (double)(Math.Abs(num34 - num30) * 2);
                                if (Math.Sqrt(num35 * num35 + num36 * num36) < (double)num31)
{
                                    Main.tile[num33, num34].type = (ushort)num32;
                                    WorldGen.SquareTileFrame(num33, num34, true);
                                }
                            }
                        }
                    }
                    num29 += WorldGen.genRand.Next(num31, (int)((double)num31 * 1.5));
                }
            }
            for (int num37 = num3 - 20; num37 <= num4 + 20; num37++)
            {
                for (int num38 = num5 - 20; num38 <= num6 + 20; num38++)
                {
                    bool flag = true;
                    for (int num39 = num37 - 1; num39 <= num37 + 1; num39++)
                    {
                        for (int num40 = num38 - 1; num40 <= num38 + 1; num40++)
{
                            if (!Main.tile[num39, num40].active() || (Main.tile[num39, num40].wall > 0 && Main.tile[num39, num40].wall != 73))
{
                                flag = false;
                            }
                        }
                    }
                    if (flag)
                    {
                        Main.tile[num37, num38].wall = 73;
                        WorldGen.SquareWallFrame(num37, num38, true);
                    }
                }
            }
            for (int num41 = num3; num41 <= num4; num41++)
            {
                int num42 = num5 - 10;
                while (!Main.tile[num41, num42 + 1].active())
                {
                    num42++;
                }
                if (num42 < num6 && Main.tile[num41, num42 + 1].type == num7)
                {
                    if (WorldGen.genRand.Next(10) == 0)
                    {
                        int num43 = WorldGen.genRand.Next(1, 3);
                        for (int num44 = num41 - num43; num44 <= num41 + num43; num44++)
{
                            if (Main.tile[num44, num42].type == num7 && WorldGen.WillWaterPlacedHereStayPut(num44, num42))
{
                                Main.tile[num44, num42].active(false);
                                Main.tile[num44, num42].liquid = byte.MaxValue;
                                Main.tile[num44, num42].liquidType(0);
                                WorldGen.SquareTileFrame(num41, num42, true);
                            }
                            if (Main.tile[num44, num42 + 1].type == num7 && WorldGen.WillWaterPlacedHereStayPut(num44, num42 + 1))
{
                                Main.tile[num44, num42 + 1].active(false);
                                Main.tile[num44, num42 + 1].liquid = byte.MaxValue;
                                Main.tile[num44, num42 + 1].liquidType(0);
                                WorldGen.SquareTileFrame(num41, num42 + 1, true);
                            }
                            if (num44 > num41 - num43 && num44 < num41 + 2 && Main.tile[num44, num42 + 2].type == num7 && WorldGen.WillWaterPlacedHereStayPut(num44, num42 + 2))
{
                                Main.tile[num44, num42 + 2].active(false);
                                Main.tile[num44, num42 + 2].liquid = byte.MaxValue;
                                Main.tile[num44, num42 + 2].liquidType(0);
                                WorldGen.SquareTileFrame(num41, num42 + 2, true);
                            }
                        }
                    }
                    if (WorldGen.genRand.Next(5) == 0 && WorldGen.WillWaterPlacedHereStayPut(num41, num42))
                    {
                        Main.tile[num41, num42].liquid = byte.MaxValue;
                    }
                    Main.tile[num41, num42].liquidType(0);
                    WorldGen.SquareTileFrame(num41, num42, true);
                }
            }
            int num45 = WorldGen.genRand.Next(4);
            for (int num46 = 0; num46 <= num45; num46++)
            {
                int num47 = WorldGen.genRand.Next(num3 - 5, num4 + 5);
                int num48 = num5 - WorldGen.genRand.Next(20, 40);
                int num49 = WorldGen.genRand.Next(4, 8);
                int num50 = (int)num7;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num50 = 196;
                }
                for (int num51 = num47 - num49; num51 <= num47 + num49; num51++)
                {
                    for (int num52 = num48 - num49; num52 <= num48 + num49; num52++)
                    {
                        double num53 = (double)Math.Abs(num51 - num47);
                        double num54 = (double)(Math.Abs(num52 - num48) * 2);
                        if (Math.Sqrt(num53 * num53 + num54 * num54) < (double)(num49 + WorldGen.genRand.Next(-1, 2)))
{
                            Main.tile[num51, num52].active(true);
                            Main.tile[num51, num52].type = (ushort)num50;
                            WorldGen.SquareTileFrame(num51, num52, true);
                        }
                    }
                }
                for (int num55 = num47 - num49 + 2; num55 <= num47 + num49 - 2; num55++)
                {
                    int num56 = num48 - num49;
                    while (!Main.tile[num55, num56].active())
                    {
                        num56++;
                    }
                    if (WorldGen.WillWaterPlacedHereStayPut(num55, num56))
                    {
                        Main.tile[num55, num56].active(false);
                        Main.tile[num55, num56].liquid = byte.MaxValue;
                        Main.tile[num55, num56].liquidType(0);
                        WorldGen.SquareTileFrame(num55, num56, true);
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.extraFloatingIslands, Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), System.Math.Sqrt(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SquareWallFrame(), Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Terraria.WorldGen.WillWaterPlacedHereStayPut(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().