Terraria Decompiled: Terraria.WorldGen.placeLavaTrap
placeLavaTrap()
static bool Terraria.WorldGen.placeLavaTrap (int x, int y) inline static
Definition at line 4630 of file WorldGen.cs.
        {
            if (WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
            {
                return true;
            }
            int num = 5;
            int num2 = 50;
            int num3 = 40;
            int num4 = 20;
            int num5 = 4;
            if (Main.tile[x, y].active() || Main.tile[x, y].liquid < 255 || !Main.tile[x, y].lava())
            {
                return false;
            }
            int num6 = 0;
            for (int i = x - num; i <= x + num; i++)
            {
                for (int j = y - num; j <= y + num; j++)
                {
                    if (Main.tile[i, j].lava() && !Main.tile[i, j].active() && Main.tile[i, j].liquid == 255)
                    {
                        num6++;
                    }
                }
            }
            if (num6 < num2)
            {
                return false;
            }
            int num7 = y;
            while (!Main.tile[x, num7].active())
            {
                num7++;
                if (num7 > Main.maxTilesY - 200)
                {
                    return false;
                }
            }
            if (!Main.tileSolid[(int)Main.tile[x, num7].type] || Main.tileSolidTop[(int)Main.tile[x, num7].type])
            {
                return false;
            }
            int num8 = num7;
            for (int k = x - num4; k <= x + num4; k++)
            {
                for (int l = num7 - num4; l <= num7 + num4; l++)
                {
                    if (Main.tile[k, l].wire())
                    {
                        return false;
                    }
                }
            }
            while (Main.tile[x, num7].active() && Main.tileSolid[(int)Main.tile[x, num7].type] && !Main.tileSolidTop[(int)Main.tile[x, num7].type])
            {
                num7++;
                if (num7 > Main.maxTilesY - 200)
                {
                    return false;
                }
            }
            Tile tile = Main.tile[x, num7 - 1];
            if (Main.tileDungeon[(int)tile.type] || tile.type == 225 || tile.type == 226)
            {
                return false;
            }
            int num9 = num7;
            while (!Main.tile[x, num7].active())
            {
                num7++;
                if (num7 > Main.maxTilesY - 200 || Main.tile[x, num7].liquid > 0)
                {
                    return false;
                }
            }
            if (!Main.tileSolid[(int)Main.tile[x, num7].type] || Main.tileSolidTop[(int)Main.tile[x, num7].type] || Main.tile[x, num7].type == 162)
            {
                return false;
            }
            int num10 = num7 - 1;
            if (num10 - num8 > num3)
            {
                return false;
            }
            if (num10 - num9 < num5)
            {
                return false;
            }
            Main.tile[x, num7].slope(0);
            Main.tile[x, num7].halfBrick(false);
            WorldGen.PlaceTile(x, num10, 135, false, true, -1, 7);
            for (int m = num8; m <= num10; m++)
            {
                Main.tile[x, m].wire(true);
                if (m < num9)
                {
                    Main.tile[x, m].slope(0);
                    Main.tile[x, m].halfBrick(false);
                    Main.tile[x, m].actuator(true);
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt, Terraria.Tile.actuator(), Terraria.Tile.halfBrick(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.WorldGen.PlaceTile(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.Tile.wire().