Terraria Decompiled: Terraria.WorldGen.saveAndPlay
saveAndPlay()
static void Terraria.WorldGen.saveAndPlay () inline static
Definition at line 2687 of file WorldGen.cs.
        {
            WorldFile.SetTempToOngoing();
            ThreadPool.QueueUserWorkItem(new WaitCallback(WorldGen.saveAndPlayCallBack), 1);
        }
References System.Threading.ThreadPool.QueueUserWorkItem(), Terraria.WorldGen.saveAndPlayCallBack(), Terraria.IO.WorldFile.SetTempToOngoing(), and System.Threading.WaitCallback().
Referenced by Terraria.Main.DedServ(), and Terraria.Main.DoUpdate_AutoSave().