Terraria Decompiled: Terraria.WorldGen.CheckOrb
CheckOrb()
static void Terraria.WorldGen.CheckOrb (int i, int j, int type) inline static
Definition at line 52669 of file WorldGen.cs.
        {
            if (Main.tile[i, j] == null)
            {
                return;
            }
            int frameX = (int)Main.tile[i, j].frameX;
            bool flag = false;
            if (frameX >= 36)
            {
                flag = true;
            }
            if (!WorldGen.destroyObject)
            {
                int num;
                if (Main.tile[i, j].frameX == 0 || Main.tile[i, j].frameX == 36)
                {
                    num = i;
                }
                else
                {
                    num = i - 1;
                }
                int num2;
                if (Main.tile[i, j].frameY == 0)
                {
                    num2 = j;
                }
                else
                {
                    num2 = j - 1;
                }
                for (int k = 0; k < 2; k++)
                {
                    for (int l = 0; l < 2; l++)
                    {
                        Tile tile = Main.tile[num + k, num2 + l];
                        if (tile != null && (!tile.nactive() || (int)tile.type != type))
{
                            WorldGen.destroyObject = true;
                            break;
                        }
                    }
                    if (WorldGen.destroyObject)
                    {
                        break;
                    }
                    if (type == 12 || type == 639)
                    {
                        Tile tile = Main.tile[num + k, num2 + 2];
                        if (tile != null && !WorldGen.SolidTileAllowBottomSlope(num + k, num2 + 2))
{
                            WorldGen.destroyObject = true;
                            break;
                        }
                    }
                }
                if (!WorldGen.destroyObject)
                {
                    return;
                }
                for (int m = num; m < num + 2; m++)
                {
                    for (int n = num2; n < num2 + 2; n++)
                    {
                        if (Main.tile[m, n] != null && (int)Main.tile[m, n].type == type)
{
                            WorldGen.KillTile(m, n, false, false, false);
                        }
                    }
                }
                if (Main.netMode != 1 && !WorldGen.generatingWorld)
                {
                    if (type == 696)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, (!flag) ? 5469 : 5470, 1, false, 0, false);
                    }
                    else if (type == 12)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 29, 1, false, 0, false);
                    }
                    else if (type == 639)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 109, 1, false, 0, false);
                    }
                    else if (type == 31)
                    {
                        if (flag)
{
                            int num3 = Main.rand.Next(5);
                            if (!WorldGen.shadowOrbSmashed)
{
                                num3 = 0;
                            }
                            if (num3 == 0)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 800, 1, false, -1, false);
                                int num4 = WorldGen.genRand.Next(100, 101);
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 97, num4, false, 0, false);
                            }
                            else if (num3 == 1)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 1256, 1, false, -1, false);
                            }
                            else if (num3 == 2)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 802, 1, false, -1, false);
                            }
                            else if (num3 == 3)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 3062, 1, false, -1, false);
                            }
                            else if (num3 == 4)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 1290, 1, false, -1, false);
                            }
                        }
                        else
{
                            int num5 = Main.rand.Next(5);
                            if (!WorldGen.shadowOrbSmashed)
{
                                num5 = 0;
                            }
                            if (num5 == 0)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 96, 1, false, -1, false);
                                int num6 = WorldGen.genRand.Next(100, 101);
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 97, num6, false, 0, false);
                            }
                            else if (num5 == 1)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 64, 1, false, -1, false);
                            }
                            else if (num5 == 2)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 162, 1, false, -1, false);
                            }
                            else if (num5 == 3)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 115, 1, false, -1, false);
                            }
                            else if (num5 == 4)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(num, num2), num * 16, num2 * 16, 32, 32, 111, 1, false, -1, false);
                            }
                        }
                        WorldGen.shadowOrbSmashed = true;
                        WorldGen.shadowOrbCount++;
                        if (WorldGen.shadowOrbCount >= 3 || (Main.dontStarveWorld && Main.getGoodWorld && !Main.remixWorld))
{
                            if ((!NPC.AnyNPCs(266) || !flag) && (!NPC.AnyNPCs(13) || flag))
{
                                WorldGen.shadowOrbCount = 0;
                                float num7 = (float)(num * 16);
                                float num8 = (float)(num2 * 16);
                                float num9 = -1f;
                                int num10 = 0;
                                for (int num11 = 0; num11 < 255; num11++)
{
                                    float num12 = Math.Abs(Main.player[num11].position.X - num7) + Math.Abs(Main.player[num11].position.Y - num8);
                                    if (num12 < num9 || num9 == -1f)
{
                                        num10 = num11;
                                        num9 = num12;
                                    }
                                }
                                if (flag)
{
                                    NPC.SpawnOnPlayer(num10, 266, 0f, 0f, 0f, 0f);
                                }
                                else
{
                                    NPC.SpawnOnPlayer(num10, 13, 0f, 0f, 0f, 0f);
                                }
                            }
                        }
                        else
{
                            LocalizedText localizedText = Lang.misc[10];
                            if (WorldGen.shadowOrbCount == 2)
{
                                localizedText = Lang.misc[11];
                            }
                            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(localizedText.Key, new object[0]), ChatColors.World, -1);
                        }
                        AchievementsHelper.NotifyProgressionEvent(7);
                    }
                }
                if (flag)
                {
                    SoundEngine.PlaySound(4, i * 16, j * 16, 1, 1f, 0f);
                }
                else
                {
                    SoundEngine.PlaySound(13, i * 16, j * 16, 1, 1f, 0f);
                }
                WorldGen.destroyObject = false;
            }
        }
References System.Math.Abs(), Terraria.NPC.AnyNPCs(), Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.WorldGen.destroyObject, Terraria.Main.dontStarveWorld, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Localization.NetworkText.FromKey(), Terraria.WorldGen.generatingWorld, Terraria.WorldGen.genRand, Terraria.Main.getGoodWorld, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.Localization.LocalizedText.Key, Terraria.WorldGen.KillTile(), Terraria.Lang.misc, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Achievements.AchievementsHelper.NotifyProgressionEvent(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.shadowOrbCount, Terraria.WorldGen.shadowOrbSmashed, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.NPC.SpawnOnPlayer(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Chat.ChatColors.World, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.TileFrameImportant().