Terraria Decompiled: Terraria.WorldGen.Check1xX
Check1xX()
static void Terraria.WorldGen.Check1xX (int x, int j, short type) inline static
Definition at line 35218 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int frameX = (int)Main.tile[x, j].frameX;
            int num = 3;
            if (type == 92)
            {
                num = 6;
            }
            int i = (int)Main.tile[x, j].frameY;
            int num2 = 0;
            while (i >= 18 * num)
            {
                i -= 18 * num;
                num2++;
            }
            int num3 = (int)(Main.tile[x, j].frameX / 18);
            int num4 = j - i / 18;
            bool flag = false;
            for (int k = 0; k < num; k++)
            {
                if (Main.tile[x, num4 + k] == null)
                {
                    Main.tile[x, num4 + k] = new Tile();
                }
                if (!Main.tile[x, num4 + k].active())
                {
                    flag = true;
                }
                else if (Main.tile[x, num4 + k].type != (ushort)type)
                {
                    flag = true;
                }
                else if ((int)Main.tile[x, num4 + k].frameY != k * 18 + num2 * num * 18)
                {
                    flag = true;
                }
                else if ((int)Main.tile[x, num4 + k].frameX != frameX)
                {
                    flag = true;
                }
            }
            if (Main.tile[x, num4 + num] == null)
            {
                Main.tile[x, num4 + num] = new Tile();
            }
            if (!WorldGen.SolidTileAllowBottomSlope(x, num4 + num))
            {
                flag = true;
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int l = 0; l < num; l++)
                {
                    if (Main.tile[x, num4 + l].type == (ushort)type)
                    {
                        WorldGen.KillTile(x, num4 + l, false, false, false);
                    }
                }
                if (type == 92)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, j), x * 16, j * 16, 32, 32, 341, 1, false, 0, false);
                }
                if (type == 453)
                {
                    int num5;
                    if (num3 < 2)
                    {
                        num5 = 3744;
                    }
                    else if (num3 < 4)
                    {
                        num5 = 3745;
                    }
                    else
                    {
                        num5 = 3743;
                    }
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, j), x * 16, j * 16, 16, 32, num5, 1, false, 0, false);
                }
                if (type == 93)
                {
                    int itemDrop_Lamps = WorldGen.GetItemDrop_Lamps(num2);
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, j), x * 16, j * 16, 32, 32, itemDrop_Lamps, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemDrop_Lamps(), Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().