Terraria Decompiled: Terraria.WorldGen.FinishNotTheBees
FinishNotTheBees()
static void Terraria.WorldGen.FinishNotTheBees () inline static private
Definition at line 22494 of file WorldGen.cs.
        {
            if (!WorldGen.notTheBees)
            {
                return;
            }
            if (WorldGen.skyblockWorldGen)
            {
                return;
            }
            Main.tileSolid[379] = false;
            int num = 0;
            int num2 = 20;
            while ((double)num2 < Main.worldSurface)
            {
                for (int i = 20; i < Main.maxTilesX - 20; i++)
                {
                    if (Main.tile[i, num2].active() && TileID.Sets.Clouds[(int)Main.tile[i, num2].type])
                    {
                        num = num2;
                        break;
                    }
                }
                num2++;
            }
            if (WorldGen.getGoodWorldGen && !WorldGen.tenthAnniversaryWorldGen)
            {
                for (int j = 0; j < Main.maxTilesX / 4; j++)
                {
                    int num3 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num4 = WorldGen.genRand.Next(Main.UnderworldLayer + 10, Main.maxTilesY - 20);
                    int num5 = 10000;
                    while (Main.tile[num3, num4].wall != 62 && num5 > 0)
                    {
                        num5--;
                        num3 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                        num4 = WorldGen.genRand.Next(Main.UnderworldLayer + 10, Main.maxTilesY - 20);
                    }
                    WorldGen.SpiderWallRemover(num3, num4);
                }
                for (int k = 0; k < Main.maxTilesX / 3; k++)
                {
                    int num6 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                    int num7 = WorldGen.genRand.Next((int)Main.worldSurface, Main.UnderworldLayer - 30);
                    int num8 = 10000;
                    while (Main.tile[num6, num7].wall != 62 && num8 > 0)
                    {
                        num8--;
                        num6 = WorldGen.genRand.Next(20, Main.maxTilesX - 20);
                        num7 = WorldGen.genRand.Next((int)Main.worldSurface, Main.UnderworldLayer - 30);
                    }
                    WorldGen.SpiderWallRemover(num6, num7);
                }
            }
            for (int l = 25; l < Main.maxTilesX - 25; l++)
            {
                for (int m = 25; m < Main.maxTilesY - 25; m++)
                {
                    int num9 = (Main.tile[l, m].active() ? ((int)Main.tile[l, m].type) : (-1));
                    if (WorldGen.getGoodWorldGen && !WorldGen.tenthAnniversaryWorldGen && num9 == 76)
                    {
                        Main.tile[l, m].type = 230;
                    }
                    if (m < num && num9 == 229)
                    {
                        Main.tile[l, m].active(false);
                        Main.tile[l, m].liquid = byte.MaxValue;
                        Main.tile[l, m].liquidType(0);
                    }
                    if ((WorldGen.dontStarveWorldGen || WorldGen.noTrapsWorldGen) && !WorldGen.tenthAnniversaryWorldGen && num9 == 48)
                    {
                        Main.tile[l, m].type = 232;
                    }
                    if (num9 == 571)
                    {
                        WorldGen.TileFrame(l, m, false, false);
                    }
                    int num10 = 20;
                    if (WorldGen.remixWorldGen)
                    {
                        num10 = 10;
                    }
                    if (num9 == 25 || (WorldGen.remixWorldGen && num9 == 23 && (double)m < Main.worldSurface))
                    {
                        for (int n = l - num10; n <= l + num10; n++)
{
                            for (int num11 = m - num10; num11 <= m + num10; num11++)
{
                                if (Main.tile[n, num11].active() && Main.tile[n, num11].type == 60)
{
                                    if (Main.tile[n, num11 + 1].type == 444)
{
                                        WorldGen.KillTile(n, num11 + 1, false, false, false);
                                    }
                                    Main.tile[n, num11].type = 661;
                                    if (Main.tile[n, num11 - 1].active() && (Main.tile[n, num11 - 1].type == 61 || Main.tile[n, num11 - 1].type == 74))
{
                                        Main.tile[n, num11 - 1].active(false);
                                        WorldGen.PlaceTile(n, num11 - 1, 24, false, false, -1, 0);
                                    }
                                }
                                else if (Main.tile[n, num11 - 1].type == 233 || Main.tile[n, num11 - 1].type == 82)
{
                                    WorldGen.KillTile(n, num11 - 1, false, false, false);
                                }
                            }
                        }
                    }
                    else if (num9 == 203 || (WorldGen.remixWorldGen && num9 == 199 && (double)m < Main.worldSurface))
                    {
                        for (int num12 = l - num10; num12 <= l + num10; num12++)
{
                            for (int num13 = m - num10; num13 <= m + num10; num13++)
{
                                if (Main.tile[num12, num13].active() && Main.tile[num12, num13].type == 60)
{
                                    if (Main.tile[num12, num13 + 1].type == 444)
{
                                        WorldGen.KillTile(num12, num13 + 1, false, false, false);
                                    }
                                    Main.tile[num12, num13].type = 662;
                                    if (Main.tile[num12, num13 - 1].active() && (Main.tile[num12, num13 - 1].type == 61 || Main.tile[num12, num13 - 1].type == 74))
{
                                        Main.tile[num12, num13 - 1].active(false);
                                        WorldGen.PlaceTile(num12, num13 - 1, 201, false, false, -1, 0);
                                    }
                                    else if (Main.tile[num12, num13 - 1].type == 233 || Main.tile[num12, num13 - 1].type == 82)
{
                                        WorldGen.KillTile(num12, num13 - 1, false, false, false);
                                    }
                                }
                            }
                        }
                    }
                    if ((num9 == 382 || num9 == 52) && Main.tile[l, m - 1].active() && (Main.tile[l, m - 1].type == 62 || Main.tile[l, m - 1].type == 60 || Main.tile[l, m - 1].type == 384))
                    {
                        Main.tile[l, m].type = 62;
                    }
                    if (m > GenVars.lavaLine + WorldGen.genRand.Next(-2, 3) + 2)
                    {
                        if (!WorldGen.remixWorldGen)
{
                            WorldGen.SpreadGrass(l, m, 59, 70, true, default(TileColorCache));
                        }
                    }
                    else
                    {
                        WorldGen.SpreadGrass(l, m, 59, 60, true, default(TileColorCache));
                    }
                    int num14 = GenVars.lavaLine + WorldGen.genRand.Next(5);
                    int num15 = (int)Main.worldSurface + WorldGen.genRand.Next(-2, 3) + 35;
                    int num16 = (num14 + num15) / 2;
                    if (m > num15 && m <= num14 && (l < WorldGen.beachDistance + 200 - 20 - WorldGen.genRand.Next(-2, 3) || l > Main.maxTilesX - WorldGen.beachDistance - 200 + 20 + WorldGen.genRand.Next(-2, 3)))
                    {
                        if (Main.tile[l, m].wall == 86)
{
                            Main.tile[l, m].wall = 0;
                        }
                        if (Main.tile[l, m].liquid > 0)
{
                            Main.tile[l, m].honey(false);
                            Main.tile[l, m].lava(false);
                        }
                        if (num9 == 59)
{
                            bool flag = false;
                            for (int num17 = l - 1; num17 <= l + 1; num17++)
{
                                for (int num18 = m - 1; num18 <= m + 1; num18++)
{
                                    if (Main.tile[num17, num18].type == 60)
{
                                        flag = true;
                                    }
                                }
                            }
                            if (!flag)
{
                                if (m < num16)
{
                                    Main.tile[l, m].type = 161;
                                }
                                else
{
                                    Main.tile[l, m].type = 147;
                                }
                            }
                        }
                        if (num9 == 225 || num9 == 230)
{
                            if (m > num16)
{
                                Main.tile[l, m].type = 161;
                            }
                            else
{
                                Main.tile[l, m].type = 147;
                            }
                        }
                    }
                    if (!WorldGen.remixWorldGen && !WorldGen.dontStarveWorldGen)
                    {
                        if (num9 == 7 || num9 == 166 || num9 == 6 || num9 == 167)
{
                            if ((double)m > ((double)GenVars.lavaLine + Main.rockLayer * 2.0) / 3.0 + (double)WorldGen.genRand.Next(-2, 3) + 2.0)
{
                                Main.tile[l, m].type = 0;
                            }
                        }
                        else if ((num9 == 123 || num9 == 40) && (double)m > ((double)GenVars.lavaLine + Main.rockLayer) / 2.0 + (double)WorldGen.genRand.Next(-2, 3) + 2.0)
{
                            Main.tile[l, m].type = 1;
                        }
                    }
                    if (m > num && l > 350 && l < Main.maxTilesX - 350 && (Main.tile[l, m].liquid == 0 || Main.tile[l, m].honey()) && (!WorldGen.tenthAnniversaryWorldGen || WorldGen.remixWorldGen))
                    {
                        if (WorldGen.dontStarveWorldGen || WorldGen.remixWorldGen)
{
                            if (WorldGen.genRand.Next(600) == 0)
{
                                WorldGen.PlaceTile(l, m, 231, true, false, -1, 0);
                            }
                        }
                        else if (WorldGen.noTrapsWorldGen)
{
                            if (WorldGen.genRand.Next(150) == 0)
{
                                WorldGen.PlaceTile(l, m, 231, true, false, -1, 0);
                            }
                        }
                        else if (WorldGen.genRand.Next(225) == 0)
{
                            WorldGen.PlaceTile(l, m, 231, true, false, -1, 0);
                        }
                    }
                }
            }
            if (WorldGen.dontStarveWorldGen && !WorldGen.remixWorldGen && !WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves)
            {
                for (int num19 = 50; num19 < Main.maxTilesX - 50; num19++)
                {
                    int num20 = 50;
                    while ((double)num20 < Main.worldSurface + (double)WorldGen.genRand.Next(3))
                    {
                        bool flag2 = WorldGen.genRand.Next(3) == 0;
                        if (WorldGen.getGoodWorldGen)
{
                            flag2 = !flag2;
                        }
                        if (flag2)
{
                            bool flag3 = false;
                            int num21 = -1;
                            int num22 = -1;
                            if (Main.tile[num19, num20].active() && Main.tile[num19, num20].type == 60 && Main.tile[num19, num20].wall == 15)
{
                                for (int num23 = num19 - 1; num23 <= num19 + 1; num23++)
{
                                    for (int num24 = num20 - 1; num24 <= num20 + 1; num24++)
{
                                        if (Main.tile[num23, num24].wall == 0 && !WorldGen.SolidTile(num23, num24, false))
{
                                            flag3 = true;
                                        }
                                    }
                                }
                                if (flag3)
{
                                    for (int num25 = num19 - 1; num25 <= num19 + 1; num25++)
{
                                        for (int num26 = num20 - 1; num26 <= num20 + 1; num26++)
{
                                            if (Main.tile[num25, num26].wall == 15 && !WorldGen.SolidTile(num25, num26, false))
{
                                                num21 = num25;
                                                num22 = num26;
                                            }
                                        }
                                    }
                                }
                            }
                            if (WorldGen.dontStarveWorldGen && Main.tile[num19, num20].active() && Main.tile[num19, num20].type == 2 && Main.tile[num19, num20].wall == 63)
{
                                for (int num27 = num19 - 1; num27 <= num19 + 1; num27++)
{
                                    for (int num28 = num20 - 1; num28 <= num20 + 1; num28++)
{
                                        if (Main.tile[num27, num28].wall == 0 && !WorldGen.SolidTile(num27, num28, false))
{
                                            flag3 = true;
                                        }
                                    }
                                }
                                if (flag3)
{
                                    for (int num29 = num19 - 1; num29 <= num19 + 1; num29++)
{
                                        for (int num30 = num20 - 1; num30 <= num20 + 1; num30++)
{
                                            if (Main.tile[num29, num30].wall == 63 && !WorldGen.SolidTile(num29, num30, false))
{
                                                num21 = num29;
                                                num22 = num30;
                                            }
                                        }
                                    }
                                }
                            }
                            if (flag3 && num21 > -1 && num22 > -1)
{
                                try
{
                                    WorldGen.Spread.Wall2(num21, num22, 62);
                                }
                                catch
{
                                }
                            }
                        }
                        num20++;
                    }
                }
                for (int num31 = 200; num31 < Main.maxTilesX - 200; num31++)
                {
                    int num32 = 50;
                    while ((double)num32 < Main.rockLayer)
                    {
                        if (Main.tile[num31, num32].wall == 62)
{
                            Main.tile[num31, num32].liquid = 0;
                            Main.tile[num31, num32].lava(false);
                        }
                        if (Main.tile[num31, num32].wall == 62 && !Main.tile[num31, num32].active() && WorldGen.genRand.Next(10) != 0)
{
                            int num33 = WorldGen.genRand.Next(2, 5);
                            int num34 = num31 - num33;
                            int num35 = num31 + num33;
                            int num36 = num32 - num33;
                            int num37 = num32 + num33;
                            bool flag4 = false;
                            for (int num38 = num34; num38 <= num35; num38++)
{
                                for (int num39 = num36; num39 <= num37; num39++)
{
                                    if (WorldGen.SolidTile(num38, num39, false))
{
                                        flag4 = true;
                                        break;
                                    }
                                }
                            }
                            if (flag4)
{
                                WorldGen.PlaceTile(num31, num32, 51, true, false, -1, 0);
                                WorldGen.TileFrame(num31, num32, false, false);
                            }
                        }
                        num32++;
                    }
                }
            }
            for (int num40 = 20; num40 < num; num40++)
            {
                for (int num41 = 20; num41 <= Main.maxTilesX - 20; num41++)
                {
                    Main.tile[num41, num40].honey(false);
                    if (Main.tile[num41, num40].type == 375)
                    {
                        Main.tile[num41, num40].type = 373;
                    }
                    if (!WorldGen.remixWorldGen)
                    {
                        if (Main.tile[num41, num40].type == 60)
{
                            Main.tile[num41, num40].type = 2;
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.TryGrowingTreeByType(616, num41, num40, 0, false);
                            }
                            else
{
                                WorldGen.TryGrowingTreeByType(596, num41, num40, 0, false);
                            }
                            if (!Main.tile[num41, num40 - 1].active())
{
                                WorldGen.PlaceTile(num41, num40 - 1, 3, false, false, -1, 0);
                            }
                        }
                        if (Main.tile[num41, num40].type == 59)
{
                            Main.tile[num41, num40].type = 0;
                        }
                    }
                    else
                    {
                        WorldGen.TryGrowingTreeByType(5, num41, num40, 0, false);
                    }
                }
            }
            Main.tileSolid[379] = true;
            if (!WorldGen.remixWorldGen)
            {
                WorldGen.OverGrownDungeon();
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Tile.honey(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.WorldBuilding.GenVars.lavaLine, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.Variations.noSpiderCavesActuallyNoSpiderCaves, Terraria.WorldGen.noTrapsWorldGen, Terraria.WorldGen.notTheBees, Terraria.WorldGen.OverGrownDungeon(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.WorldGen.skyblockWorldGen, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SpiderWallRemover(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Main.tileSolid, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, Terraria.WorldGen.Spread.Wall2(), and Terraria.Main.worldSurface.