Terraria Decompiled: Terraria.WorldGen.CheckForHousesNearAPlayer
CheckForHousesNearAPlayer()
static void Terraria.WorldGen.CheckForHousesNearAPlayer () inline static private
Definition at line 72006 of file WorldGen.cs.
        {
            int num = Main.CurrentFrameFlags.ActivePlayersCount;
            if (num <= 0)
            {
                num = 1;
            }
            int num2 = (int)((ulong)Main.GameUpdateCount % (ulong)((long)num));
            for (int i = 0; i < 255; i++)
            {
                Player player = Main.player[i];
                if (player.active && num2-- == 0)
                {
                    Rectangle rectangle = Utils.CenteredRectangle(player.Center.ToTileCoordinates(), Point.Zero);
                    rectangle.Inflate(Main.MaxWorldViewSize.X / 32, Main.MaxWorldViewSize.Y / 32);
                    rectangle = WorldUtils.ClampToWorld(rectangle, 10);
                    for (int j = 0; j < 300; j++)
                    {
                        Point point = Main.rand.NextFromRectangle(rectangle);
                        if (Main.wallHouse[(int)Main.tile[point.X, point.Y].wall])
{
                            bool flag = Main.tileSolid[379];
                            Main.tileSolid[379] = true;
                            WorldGen.SpawnTownNPC(point.X, point.Y, false);
                            Main.tileSolid[379] = flag;
                            break;
                        }
                    }
                }
            }
        }
References Terraria.Player.active, Terraria.Main.CurrentFrameFlags.ActivePlayersCount, Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.WorldBuilding.WorldUtils.ClampToWorld(), Microsoft.Xna.Framework.Rectangle.Inflate(), int, Terraria.Main.MaxWorldViewSize, Terraria.Main.player, Terraria.Main.rand, Terraria.WorldGen.SpawnTownNPC(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.wall, Terraria.Main.wallHouse, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.WorldGen.UpdateWorld().