Terraria Decompiled: Terraria.WorldGen.RefreshSection
RefreshSection()
static void Terraria.WorldGen.RefreshSection (int sectionX, int sectionY) inline static
Definition at line 80900 of file WorldGen.cs.
        {
            int num;
            int num2;
            int num3;
            int num4;
            WorldGen.GetSectionBounds(sectionX, sectionY, sectionX, sectionY, out num, out num2, out num3, out num4);
            if (WorldGen.generatingWorld)
            {
                for (int i = num; i < num2; i++)
                {
                    for (int j = num3; j < num4; j++)
                    {
                        WorldGen.Reframe(i, j, false);
                    }
                }
            }
            else
            {
                int num5 = 0;
                int num6 = 0;
                for (int k = num3; k < num4; k += 50)
                {
                    for (int l = num; l < num2; l += 200)
                    {
                        WorldGen.RefreshStrip(l, k, Math.Min(l + 200, num2), Math.Min(k + 50, num4), ref num5, ref num6);
                    }
                }
            }
            Main.sectionManager.SetSectionAsRefreshed(sectionX, sectionY);
        }
References Terraria.WorldGen.generatingWorld, Terraria.WorldGen.GetSectionBounds(), System.Math.Min(), Terraria.WorldGen.Reframe(), Terraria.WorldGen.RefreshStrip(), Terraria.Main.sectionManager, and Terraria.WorldSections.SetSectionAsRefreshed().
Referenced by Terraria.WorldGen.RefreshSections().