Terraria Decompiled: Terraria.WorldGen.GetRainbowPaintIDForPosition
GetRainbowPaintIDForPosition()
static byte Terraria.WorldGen.GetRainbowPaintIDForPosition (int x, int y, bool wiggly = false) inline static
Definition at line 21607 of file WorldGen.cs.
        {
            int num = x;
            int num2 = y;
            if (wiggly)
            {
                num += (int)(Math.Sin((double)((float)(y % 50) / 50f * 6.2831855f)) * 10.0) - 5;
                num2 = 0;
            }
            int num3 = num % 44 + num2 % 44;
            num3 %= 11;
            return (byte)(13 + num3);
        }
References int, and System.Math.Sin().
Referenced by Terraria.WorldBuilding.Actions.SetTileAndWallRainbowPaint.Apply(), Terraria.WorldGen.PaintTheSandRainbowAndSandWallsBlack(), Terraria.WorldGen.PlaceTile(), and Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single().