Terraria Decompiled: Terraria.WorldGen.TryKillingReplaceableTile
TryKillingReplaceableTile()
static bool Terraria.WorldGen.TryKillingReplaceableTile (int x, int y, int tileType) inline static
Definition at line 58030 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 2))
            {
                return false;
            }
            if (!Main.tile[x, y].active() || (!Main.tileCut[(int)Main.tile[x, y].type] && !TileID.Sets.BreakableWhenPlacing[(int)Main.tile[x, y].type] && !TileID.Sets.IsADripTile[(int)Main.tile[x, y].type]))
            {
                return false;
            }
            if ((int)Main.tile[x, y].type == tileType)
            {
                return false;
            }
            bool flag = Main.tile[x, y + 1].type != 78 && Main.tile[x, y + 1].type != 380 && Main.tile[x, y + 1].type != 579;
            bool flag2 = Main.tile[x, y].type == 3 || Main.tile[x, y].type == 73;
            bool flag3 = Main.tileAlch[(int)Main.tile[x, y].type] && WorldGen.IsHarvestableHerbWithSeed((int)Main.tile[x, y].type, (int)(Main.tile[x, y].frameX / 18), y);
            bool flag4 = Main.tileAlch[tileType];
            if (flag || ((flag2 || flag3) && flag4))
            {
                WorldGen.KillTile(x, y, false, false, false);
                if (!Main.tile[x, y].active() && Main.netMode != 0)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                }
                return true;
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.BreakableWhenPlacing, Terraria.Tile.frameX, int, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsADripTile, Terraria.WorldGen.IsHarvestableHerbWithSeed(), Terraria.WorldGen.KillTile(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileCut, and Terraria.Tile.type.
Referenced by Terraria.DelegateMethods.SpreadTile().