Terraria Decompiled: Terraria.WorldGen.SpawnHomelessNPC
SpawnHomelessNPC()
static void Terraria.WorldGen.SpawnHomelessNPC () inline static
Definition at line 684 of file WorldGen.cs.
        {
            if (Main.eclipse || !Main.dayTime)
            {
                return;
            }
            if (Main.invasionType > 0 && Main.invasionDelay == 0 && Main.invasionSize > 0)
            {
                return;
            }
            if (WorldGen.prioritizedTownNPCType == 0)
            {
                return;
            }
            if (WorldGen.FindAnyHomelessTownNPC(true) != -1)
            {
                return;
            }
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active && Main.npc[i].type == WorldGen.prioritizedTownNPCType)
                {
                    return;
                }
            }
            bool flag = Main.tileSolid[379];
            Main.tileSolid[379] = true;
            try
            {
                if (WorldGen.SpawnTownNPC(WorldGen.LastFoundHouse.X, WorldGen.LastFoundHouse.Y, true) == TownNPCSpawnResult.Successful)
                {
                    return;
                }
            }
            finally
            {
                Main.tileSolid[379] = flag;
            }
            Point zero = Point.Zero;
            int[] array = new int[Main.maxNPCs];
            Point[] array2 = new Point[Main.maxNPCs];
            int num = 0;
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.active && npc.townNPC && npc.type != 37 && !npc.homeless)
                {
                    array[num] = j;
                    array2[num] = new Point(npc.homeTileX, npc.homeTileY);
                    num++;
                }
            }
            if (num == 0)
            {
                return;
            }
            int num2 = Main.rand.Next(num);
            int num3 = array[num2];
            Point point = array2[num2];
            WorldGen.bestX = point.X;
            WorldGen.bestY = point.Y;
            int num4 = WorldGen.bestX;
            int num5 = WorldGen.bestX;
            int num6 = WorldGen.bestY;
            int num7 = WorldGen.bestX;
            while (num7 > WorldGen.bestX - 10 && (WorldGen.SolidTile(num7, num6, false) || Main.tileSolidTop[(int)Main.tile[num7, num6].type]) && (!Main.tile[num7, num6 - 1].active() || !Main.tileSolid[(int)Main.tile[num7, num6 - 1].type] || Main.tileSolidTop[(int)Main.tile[num7, num6 - 1].type]) && (!Main.tile[num7, num6 - 2].active() || !Main.tileSolid[(int)Main.tile[num7, num6 - 2].type] || Main.tileSolidTop[(int)Main.tile[num7, num6 - 2].type]) && (!Main.tile[num7, num6 - 3].active() || !Main.tileSolid[(int)Main.tile[num7, num6 - 3].type] || Main.tileSolidTop[(int)Main.tile[num7, num6 - 3].type]))
            {
                num4 = num7;
                num7--;
            }
            int num8 = WorldGen.bestX;
            while (num8 < WorldGen.bestX + 10 && (WorldGen.SolidTile(num8, num6, false) || Main.tileSolidTop[(int)Main.tile[num8, num6].type]) && (!Main.tile[num8, num6 - 1].active() || !Main.tileSolid[(int)Main.tile[num8, num6 - 1].type] || Main.tileSolidTop[(int)Main.tile[num8, num6 - 1].type]) && (!Main.tile[num8, num6 - 2].active() || !Main.tileSolid[(int)Main.tile[num8, num6 - 2].type] || Main.tileSolidTop[(int)Main.tile[num8, num6 - 2].type]) && (!Main.tile[num8, num6 - 3].active() || !Main.tileSolid[(int)Main.tile[num8, num6 - 3].type] || Main.tileSolidTop[(int)Main.tile[num8, num6 - 3].type]))
            {
                num5 = num8;
                num8++;
            }
            for (int k = 0; k < 30; k++)
            {
                int num9 = Main.rand.Next(num4, num5 + 1);
                if (k < 20)
                {
                    if (num9 < WorldGen.bestX - 1 || num9 > WorldGen.bestX + 1)
                    {
                        WorldGen.bestX = num9;
                        break;
                    }
                }
                else if (num9 != WorldGen.bestX)
                {
                    WorldGen.bestX = num9;
                    break;
                }
            }
            int num10 = WorldGen.bestX;
            int num11 = WorldGen.bestY;
            bool flag2 = false;
            if (!flag2 && (double)num11 <= Main.worldSurface)
            {
                for (int l = 20; l < 500; l++)
                {
                    for (int m = 0; m < 2; m++)
                    {
                        if (m == 0)
{
                            num10 = WorldGen.bestX + l * 2;
                        }
                        else
{
                            num10 = WorldGen.bestX - l * 2;
                        }
                        if (num10 > 10 && num10 < Main.maxTilesX - 10)
{
                            int num12 = WorldGen.bestY - l;
                            double num13 = (double)(WorldGen.bestY + l);
                            if (num12 < 10)
{
                                num12 = 10;
                            }
                            if (num13 > Main.worldSurface)
{
                                num13 = Main.worldSurface;
                            }
                            int num14 = num12;
                            while ((double)num14 < num13)
{
                                num11 = num14;
                                if (Main.tile[num10, num11].nactive() && Main.tileSolid[(int)Main.tile[num10, num11].type])
{
                                    if (Main.tile[num10, num11 - 3].liquid == 0 && Main.tile[num10, num11 - 2].liquid == 0 && Main.tile[num10, num11 - 1].liquid == 0 && !Collision.SolidTiles(num10 - 1, num10 + 1, num11 - 3, num11 - 1))
{
                                        flag2 = true;
                                        Rectangle rectangle = new Rectangle(num10 * 16 + 8 - NPC.sWidth / 2 - NPC.safeRangeX, num11 * 16 + 8 - NPC.sHeight / 2 - NPC.safeRangeY, NPC.sWidth + NPC.safeRangeX * 2, NPC.sHeight + NPC.safeRangeY * 2);
                                        for (int n = 0; n < 255; n++)
{
                                            if (Main.player[n].active)
{
                                                Rectangle rectangle2 = new Rectangle((int)Main.player[n].position.X, (int)Main.player[n].position.Y, Main.player[n].width, Main.player[n].height);
                                                if (rectangle2.Intersects(rectangle))
{
                                                    flag2 = false;
                                                    break;
                                                }
                                            }
                                        }
                                        break;
                                    }
                                    break;
                                }
                                else
{
                                    num14++;
                                }
                            }
                        }
                        if (flag2)
{
                            break;
                        }
                    }
                    if (flag2)
                    {
                        break;
                    }
                }
            }
            int num15 = NPC.NewNPC(NPC.GetSpawnSourceForTownSpawn(), num10 * 16, num11 * 16, WorldGen.prioritizedTownNPCType, 1, 0f, 0f, 0f, 0f, 255);
            Main.npc[num15].homeTileX = WorldGen.bestX;
            Main.npc[num15].homeTileY = WorldGen.bestY;
            Main.npc[num15].homeless = true;
            Main.npc[num15].homelessDespawn = true;
            if (num10 < WorldGen.bestX)
            {
                Main.npc[num15].direction = 1;
            }
            else if (num10 > WorldGen.bestX)
            {
                Main.npc[num15].direction = -1;
            }
            Main.npc[num15].netUpdate = true;
            WorldGen.QuickFindHome(num15);
            int num16 = Main.rand.Next(6);
            string fullName = Main.npc[num15].FullName;
            string text;
            if (Main.npc[num15].homeless)
            {
                text = "Announcement.HomelessArrived_" + num16;
            }
            else
            {
                text = "Announcement.HasArrived";
            }
            ChatHelper.BroadcastChatMessage(NetworkText.FromKey(text, new object[] { Main.npc[num15].GetFullNetName() }), ChatColors.NPCTravel, -1);
        }
References Terraria.NPC.active, Terraria.Player.active, Terraria.Tile.active(), System.array, Terraria.WorldGen.bestX, Terraria.WorldGen.bestY, Terraria.Chat.ChatHelper.BroadcastChatMessage(), Terraria.Main.dayTime, Terraria.Entity.direction, Terraria.Main.eclipse, Terraria.WorldGen.FindAnyHomelessTownNPC(), Terraria.Localization.NetworkText.FromKey(), Terraria.NPC.FullName, Terraria.NPC.GetSpawnSourceForTownSpawn(), Terraria.Entity.height, Terraria.NPC.homeless, Terraria.NPC.homelessDespawn, Terraria.NPC.homeTileX, Terraria.NPC.homeTileY, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.invasionDelay, Terraria.Main.invasionSize, Terraria.Main.invasionType, Terraria.WorldGen.LastFoundHouse, Terraria.Tile.liquid, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Tile.nactive(), Terraria.NPC.netUpdate, Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Chat.ChatColors.NPCTravel, Terraria.Main.player, Terraria.Entity.position, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.QuickFindHome(), Terraria.Main.rand, Terraria.NPC.safeRangeX, Terraria.NPC.safeRangeY, Terraria.NPC.sHeight, Terraria.WorldGen.SolidTile(), Terraria.Collision.SolidTiles(), Terraria.WorldGen.SpawnTownNPC(), Terraria.NPC.sWidth, System.text, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.NPC.townNPC, Terraria.NPC.type, Terraria.Tile.type, Terraria.Entity.width, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.Main.UpdateTime().