Terraria Decompiled: Terraria.WorldGen.HellFort
HellFort()
static void Terraria.WorldGen.HellFort (int i, int j, ushort tileType = 75, byte wallType = 14) inline static
Definition at line 30130 of file WorldGen.cs.
        {
            int[] array = new int[5];
            int[] array2 = new int[5];
            int[] array3 = new int[10];
            int[] array4 = new int[10];
            int num = 8;
            int num2 = 20;
            if (WorldGen.drunkWorldGen)
            {
                num /= 2;
                num2 *= 2;
            }
            if (WorldGen.SecretSeed.errorWorld.Enabled)
            {
                if (WorldGen.genRand.Next(15) == 0)
                {
                    num2 *= 3;
                }
                if (WorldGen.genRand.Next(15) == 0)
                {
                    j -= WorldGen.genRand.Next(400);
                }
            }
            array[2] = i - WorldGen.genRand.Next(num / 2, num2 / 2);
            array2[2] = i + WorldGen.genRand.Next(num / 2, num2 / 2);
            array[3] = array2[2];
            array2[3] = array[3] + WorldGen.genRand.Next(num, num2);
            array[4] = array2[3];
            array2[4] = array[4] + WorldGen.genRand.Next(num, num2);
            array2[1] = array[2];
            array[1] = array2[1] - WorldGen.genRand.Next(num, num2);
            array2[0] = array[1];
            array[0] = array2[0] - WorldGen.genRand.Next(num, num2);
            num = 6;
            num2 = 12;
            array3[3] = j - WorldGen.genRand.Next(num, num2);
            array4[3] = j;
            for (int k = 4; k < 10; k++)
            {
                array3[k] = array4[k - 1];
                array4[k] = array3[k] + WorldGen.genRand.Next(num, num2);
            }
            for (int l = 2; l >= 0; l--)
            {
                array4[l] = array3[l + 1];
                array3[l] = array4[l] - WorldGen.genRand.Next(num, num2);
            }
            bool flag = false;
            bool flag2 = false;
            bool[,] array5 = new bool[5, 10];
            int num3 = 3;
            int num4 = 3;
            for (int m = 0; m < 2; m++)
            {
                if (WorldGen.genRand.Next(3) == 0 || WorldGen.drunkWorldGen)
                {
                    flag = true;
                    int num5 = WorldGen.genRand.Next(10);
                    if (num5 < num3)
                    {
                        num3 = num5;
                    }
                    if (num5 > num4)
                    {
                        num4 = num5;
                    }
                    int num6 = 1;
                    if (WorldGen.genRand.Next(2) == 0 || WorldGen.drunkWorldGen)
                    {
                        array5[0, num5] = true;
                        array5[1, num5] = true;
                        num6 = 0;
                    }
                    else
                    {
                        array5[1, num5] = true;
                    }
                    int num7 = WorldGen.genRand.Next(2);
                    if (num7 == 0)
                    {
                        num7 = -1;
                    }
                    int num8 = WorldGen.genRand.Next(10);
                    while (num8 > 0 && num5 >= 0 && num5 < 10)
                    {
                        array5[num6, num5] = true;
                        num5 += num7;
                    }
                }
                if (WorldGen.genRand.Next(3) == 0 || WorldGen.drunkWorldGen)
                {
                    flag2 = true;
                    int num9 = WorldGen.genRand.Next(10);
                    if (num9 < num3)
                    {
                        num3 = num9;
                    }
                    if (num9 > num4)
                    {
                        num4 = num9;
                    }
                    int num10 = 3;
                    if (WorldGen.genRand.Next(2) == 0 || WorldGen.drunkWorldGen)
                    {
                        array5[3, num9] = true;
                        array5[4, num9] = true;
                        num10 = 4;
                    }
                    else
                    {
                        array5[3, num9] = true;
                    }
                    int num11 = WorldGen.genRand.Next(2);
                    if (num11 == 0)
                    {
                        num11 = -1;
                    }
                    int num12 = WorldGen.genRand.Next(10);
                    while (num12 > 0 && num9 >= 0 && num9 < 10)
                    {
                        array5[num10, num9] = true;
                        num9 += num11;
                    }
                }
            }
            for (int n = 0; n < 5; n++)
            {
                int num13 = array[n];
                bool flag3 = false;
                if (num13 < 10 || num13 > Main.maxTilesX - 10)
                {
                    flag3 = true;
                }
                else
                {
                    for (int num14 = Main.UnderworldLayer; num14 < Main.maxTilesY; num14++)
                    {
                        if (Main.tile[num13, num14].wall > 0)
{
                            flag3 = true;
                        }
                    }
                }
                if (flag3)
                {
                    for (int num15 = 0; num15 < 10; num15++)
                    {
                        array5[n, num15] = false;
                    }
                }
            }
            int num16 = WorldGen.genRand.Next(10);
            if (num16 < num3)
            {
                num3 = num16;
            }
            num16 = WorldGen.genRand.Next(10);
            if (num16 > num4)
            {
                num4 = num16;
            }
            if (!flag && !flag2)
            {
                while (num4 - num3 < 5)
                {
                    num16 = WorldGen.genRand.Next(10);
                    if (num16 < num3)
                    {
                        num3 = num16;
                    }
                    num16 = WorldGen.genRand.Next(10);
                    if (num16 > num4)
                    {
                        num4 = num16;
                    }
                }
            }
            for (int num17 = num3; num17 <= num4; num17++)
            {
                array5[2, num17] = true;
            }
            for (int num18 = 0; num18 < 5; num18++)
            {
                for (int num19 = 0; num19 < 10; num19++)
                {
                    if (array5[num18, num19])
                    {
                        if (array3[num19] < Main.UnderworldLayer && !WorldGen.SecretSeed.errorWorld.Enabled)
{
                            array5[num18, num19] = false;
                        }
                        if (array4[num19] > Main.maxTilesY - 20)
{
                            array5[num18, num19] = false;
                        }
                    }
                }
            }
            for (int num20 = 0; num20 < 5; num20++)
            {
                for (int num21 = 0; num21 < 10; num21++)
                {
                    if (array5[num20, num21])
                    {
                        for (int num22 = array[num20]; num22 <= array2[num20]; num22++)
{
                            int num23 = array3[num21];
                            while (num23 <= array4[num21] && WorldGen.InWorld(num22, num23, 10))
{
                                Main.tile[num22, num23].liquid = 0;
                                if (num22 == array[num20] || num22 == array2[num20] || num23 == array3[num21] || num23 == array4[num21])
{
                                    Main.tile[num22, num23].active(true);
                                    Main.tile[num22, num23].type = tileType;
                                    Main.tile[num22, num23].halfBrick(false);
                                    Main.tile[num22, num23].slope(0);
                                }
                                else
{
                                    Main.tile[num22, num23].wall = (ushort)wallType;
                                    Main.tile[num22, num23].active(false);
                                }
                                num23++;
                            }
                        }
                    }
                }
            }
            int num24 = 19;
            int num25 = 13;
            for (int num26 = 0; num26 < 4; num26++)
            {
                bool[] array6 = new bool[10];
                bool flag4 = false;
                for (int num27 = 0; num27 < 10; num27++)
                {
                    if (array5[num26, num27] && array5[num26 + 1, num27])
                    {
                        array6[num27] = true;
                        flag4 = true;
                    }
                }
                while (flag4)
                {
                    int num28 = WorldGen.genRand.Next(10);
                    if (array6[num28])
                    {
                        flag4 = false;
                        if (WorldGen.InWorld(array2[num26], array4[num28], 10))
{
                            Main.tile[array2[num26], array4[num28] - 1].active(false);
                            Main.tile[array2[num26], array4[num28] - 2].active(false);
                            Main.tile[array2[num26], array4[num28] - 3].active(false);
                            Main.tile[array2[num26], array4[num28] - 1].wall = (ushort)wallType;
                            Main.tile[array2[num26], array4[num28] - 2].wall = (ushort)wallType;
                            Main.tile[array2[num26], array4[num28] - 3].wall = (ushort)wallType;
                            WorldGen.PlaceTile(array2[num26], array4[num28] - 1, 10, true, false, -1, num24);
                        }
                    }
                }
            }
            for (int num29 = 0; num29 < 5; num29++)
            {
                for (int num30 = 0; num30 < 10; num30++)
                {
                    if (array5[num29, num30] && WorldGen.InWorld(array2[num29], array4[num30], 10))
                    {
                        if (num30 > 0 && array5[num29, num30 - 1])
{
                            int num31 = WorldGen.genRand.Next(array[num29] + 2, array2[num29] - 1);
                            int num32 = WorldGen.genRand.Next(array[num29] + 2, array2[num29] - 1);
                            int num33 = 0;
                            while (num32 - num31 < 2 || num32 - num31 > 5)
{
                                num31 = WorldGen.genRand.Next(array[num29] + 2, array2[num29] - 1);
                                num32 = WorldGen.genRand.Next(array[num29] + 2, array2[num29] - 1);
                                num33++;
                                if (num33 > 10000)
{
                                    break;
                                }
                            }
                            if (num33 > 10000)
{
                                break;
                            }
                            int num34 = num31;
                            while (num34 <= num32 && num34 >= 20 && num34 <= Main.maxTilesX - 20 && WorldGen.InWorld(num34, array3[num30], 5))
{
                                Main.tile[num34, array3[num30]].active(false);
                                WorldGen.PlaceTile(num34, array3[num30], 19, true, true, -1, num25);
                                Main.tile[num34, array3[num30]].wall = (ushort)wallType;
                                num34++;
                            }
                        }
                        if (num29 < 4 && array5[num29 + 1, num30] && WorldGen.genRand.Next(3) == 0)
{
                            Main.tile[array2[num29], array4[num30] - 1].active(false);
                            Main.tile[array2[num29], array4[num30] - 2].active(false);
                            Main.tile[array2[num29], array4[num30] - 3].active(false);
                            Main.tile[array2[num29], array4[num30] - 1].wall = (ushort)wallType;
                            Main.tile[array2[num29], array4[num30] - 2].wall = (ushort)wallType;
                            Main.tile[array2[num29], array4[num30] - 3].wall = (ushort)wallType;
                            WorldGen.PlaceTile(array2[num29], array4[num30] - 1, 10, true, false, -1, num24);
                        }
                    }
                }
            }
            bool flag5 = false;
            for (int num35 = 0; num35 < 5; num35++)
            {
                bool[] array7 = new bool[10];
                for (int num36 = 0; num36 < 10; num36++)
                {
                    if (array5[num35, num36])
                    {
                        flag5 = true;
                        array7[num36] = true;
                    }
                }
                if (flag5)
                {
                    bool flag6 = false;
                    for (int num37 = 0; num37 < 10; num37++)
                    {
                        if (array7[num37])
{
                            if (!Main.tile[array[num35] - 1, array4[num37] - 1].active() && !Main.tile[array[num35] - 1, array4[num37] - 2].active() && !Main.tile[array[num35] - 1, array4[num37] - 3].active() && Main.tile[array[num35] - 1, array4[num37] - 1].liquid == 0 && Main.tile[array[num35] - 1, array4[num37] - 2].liquid == 0 && Main.tile[array[num35] - 1, array4[num37] - 3].liquid == 0)
{
                                flag6 = true;
                            }
                            else
{
                                array7[num37] = false;
                            }
                        }
                    }
                    while (flag6)
                    {
                        int num38 = WorldGen.genRand.Next(10);
                        if (array7[num38])
{
                            flag6 = false;
                            Main.tile[array[num35], array4[num38] - 1].active(false);
                            Main.tile[array[num35], array4[num38] - 2].active(false);
                            Main.tile[array[num35], array4[num38] - 3].active(false);
                            WorldGen.PlaceTile(array[num35], array4[num38] - 1, 10, true, false, -1, num24);
                        }
                    }
                    break;
                }
            }
            bool flag7 = false;
            for (int num39 = 4; num39 >= 0; num39--)
            {
                bool[] array8 = new bool[10];
                for (int num40 = 0; num40 < 10; num40++)
                {
                    if (array5[num39, num40])
                    {
                        flag7 = true;
                        array8[num40] = true;
                    }
                }
                if (flag7)
                {
                    bool flag8 = false;
                    for (int num41 = 0; num41 < 10; num41++)
                    {
                        if (array8[num41])
{
                            if (num39 < 20 || num39 > Main.maxTilesX - 20)
{
                                IL_0CF7:
                                while (flag8)
{
                                    int num42 = WorldGen.genRand.Next(10);
                                    if (array8[num42])
{
                                        flag8 = false;
                                        Main.tile[array2[num39], array4[num42] - 1].active(false);
                                        Main.tile[array2[num39], array4[num42] - 2].active(false);
                                        Main.tile[array2[num39], array4[num42] - 3].active(false);
                                        WorldGen.PlaceTile(array2[num39], array4[num42] - 1, 10, true, false, -1, num24);
                                    }
                                }
                                goto IL_0D0E;
                            }
                            if (!Main.tile[array2[num39] + 1, array4[num41] - 1].active() && !Main.tile[array2[num39] + 1, array4[num41] - 2].active() && !Main.tile[array2[num39] + 1, array4[num41] - 3].active() && Main.tile[array2[num39] + 1, array4[num41] - 1].liquid == 0 && Main.tile[array2[num39] + 1, array4[num41] - 2].liquid == 0 && Main.tile[array2[num39] + 1, array4[num41] - 3].liquid == 0)
{
                                flag8 = true;
                            }
                            else
{
                                array8[num41] = false;
                            }
                        }
                    }
                    goto IL_0CF7;
                }
            }
            IL_0D0E:
            bool flag9 = false;
            for (int num43 = 0; num43 < 10; num43++)
            {
                bool[] array9 = new bool[10];
                for (int num44 = 0; num44 < 5; num44++)
                {
                    if (array5[num44, num43])
                    {
                        flag9 = true;
                        array9[num44] = true;
                    }
                }
                if (flag9)
                {
                    bool flag10 = true;
                    while (flag10)
                    {
                        int num45 = WorldGen.genRand.Next(5);
                        if (array9[num45])
{
                            int num46 = WorldGen.genRand.Next(array[num45] + 2, array2[num45] - 1);
                            int num47 = WorldGen.genRand.Next(array[num45] + 2, array2[num45] - 1);
                            int num48 = 0;
                            while (num47 - num46 < 2 || num47 - num46 > 5)
{
                                num46 = WorldGen.genRand.Next(array[num45] + 2, array2[num45] - 1);
                                num47 = WorldGen.genRand.Next(array[num45] + 2, array2[num45] - 1);
                                num48++;
                                if (num48 > 10000)
{
                                    break;
                                }
                            }
                            if (num48 > 10000)
{
                                return;
                            }
                            int num49 = num46;
                            while (num49 <= num47 && num49 >= 10 && num49 <= Main.maxTilesX - 10)
{
                                if (Main.tile[num49, array3[num43] - 1].active() || Main.tile[num49, array3[num43] - 1].liquid > 0)
{
                                    flag10 = false;
                                }
                                num49++;
                            }
                            if (flag10)
{
                                int num50 = num46;
                                while (num50 <= num47 && num50 >= 10 && num50 <= Main.maxTilesX - 10)
{
                                    Main.tile[num50, array3[num43]].active(false);
                                    WorldGen.PlaceTile(num50, array3[num43], 19, true, true, -1, num25);
                                    num50++;
                                }
                            }
                            flag10 = false;
                        }
                    }
                    return;
                }
            }
        }
References Terraria.Tile.active(), System.array, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.AddHellHouses().