Terraria Decompiled: Terraria.WorldGen.ClearBrokenTraps
ClearBrokenTraps()
static void Terraria.WorldGen.ClearBrokenTraps (Point startTileCoords, List< Point > pointsWeAlreadyWentOver) inline static
Definition at line 23936 of file WorldGen.cs.
        {
            List<Point> list = new List<Point>();
            List<Point> list2 = new List<Point>();
            List<Point> list3 = new List<Point>();
            bool flag = false;
            bool flag2 = false;
            list2.Add(startTileCoords);
            int num = 2000;
            while (list2.Count > 0)
            {
                num--;
                if (num <= 0)
                {
                    break;
                }
                Utils.Swap<List<Point>>(ref list, ref list2);
                int num2 = 2000;
                while (list.Count > 0)
                {
                    num2--;
                    if (num2 <= 0)
                    {
                        break;
                    }
                    Point point = list[0];
                    list.RemoveAt(0);
                    if (WorldGen.InWorld(point.X, point.Y, 5))
                    {
                        Tile tile = Main.tile[point.X, point.Y];
                        if (tile.wire())
{
                            pointsWeAlreadyWentOver.Add(point);
                            list3.Add(point);
                            if (WorldGen.IsItATrap(tile))
{
                                flag = true;
                            }
                            if (WorldGen.IsItATrigger(tile))
{
                                flag2 = true;
                            }
                            if (flag2 && flag)
{
                                break;
                            }
                            Point point2 = new Point(point.X - 1, point.Y);
                            if (!list3.Contains(point2))
{
                                list2.Add(point2);
                            }
                            point2 = new Point(point.X + 1, point.Y);
                            if (!list3.Contains(point2))
{
                                list2.Add(point2);
                            }
                            point2 = new Point(point.X, point.Y - 1);
                            if (!list3.Contains(point2))
{
                                list2.Add(point2);
                            }
                            point2 = new Point(point.X, point.Y + 1);
                            if (!list3.Contains(point2))
{
                                list2.Add(point2);
                            }
                        }
                    }
                }
                if (flag2 && flag)
                {
                    break;
                }
            }
            if (!flag2 || !flag)
            {
                foreach (Point point3 in list3)
                {
                    Tile tile2 = Main.tile[point3.X, point3.Y];
                    tile2.wire(false);
                    if (tile2.actuator())
                    {
                        tile2.actuator(false);
                        Tile tile3 = Main.tile[point3.X, point3.Y - 1];
                        if (TileID.Sets.Boulders[(int)tile3.type] && tile3.frameX % 16 == 0)
{
                            for (int i = 0; i < 2; i++)
{
                                for (int j = -2; j < 0; j++)
{
                                    Tile tile4 = Main.tile[point3.X + i, point3.Y + j];
                                    if (tile4.active() && TileID.Sets.Boulders[(int)tile4.type])
{
                                        tile4.ResetToType(1);
                                    }
                                }
                            }
                        }
                    }
                    if (WorldGen.IsItATrap(tile2) && tile2.type != 105)
                    {
                        WorldGen.KillTile(point3.X, point3.Y, false, false, false);
                    }
                    else if (WorldGen.IsItATrigger(tile2))
                    {
                        if (tile2.type == 314)
{
                            tile2.frameX = 1;
                        }
                        else
{
                            WorldGen.KillTile(point3.X, point3.Y, false, false, false);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.actuator(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.Boulders, System.Collections.Generic.List< T >.Contains(), System.Collections.Generic.List< T >.Count, Terraria.Tile.frameX, Terraria.WorldGen.InWorld(), Terraria.WorldGen.IsItATrap(), Terraria.WorldGen.IsItATrigger(), Terraria.WorldGen.KillTile(), System.list, Terraria.Tile.ResetToType(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wire(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.ClearAllBrokenTraps().