Terraria Decompiled: Terraria.WorldGen.CheckExploitDestroyQueue
CheckExploitDestroyQueue()
static void Terraria.WorldGen.CheckExploitDestroyQueue () inline static
Definition at line 63202 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            while (WorldGen.ExploitDestroyQueue.Count > 0)
            {
                Point point = WorldGen.ExploitDestroyQueue.Dequeue();
                if (Framing.GetTileSafely(point.X, point.Y).active())
                {
                    WorldGen.SquareTileFrame(point.X, point.Y, true);
                    if (Main.netMode != 0)
                    {
                        NetMessage.SendTileSquare(-1, point.X, point.Y, TileChangeType.None);
                    }
                }
            }
        }
References Terraria.Tile.active(), System.Collections.Generic.Queue< T >.Count, System.Collections.Generic.Queue< T >.Dequeue(), Terraria.WorldGen.destroyObject, Terraria.WorldGen.ExploitDestroyQueue, Terraria.Framing.GetTileSafely(), Terraria.Main.netMode, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.CheckDoorClosed(), Terraria.WorldGen.CheckDoorOpen(), Terraria.WorldGen.CheckTallGate(), Terraria.WorldGen.CheckTrapDoor(), and Terraria.WorldGen.KillTile().