Terraria Decompiled: Terraria.WorldGen.RandHousePicture
RandHousePicture()
static PaintingEntry Terraria.WorldGen.RandHousePicture () inline static
Definition at line 32691 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(4);
            if (num >= 3 && WorldGen.genRand.Next(2) != 0)
            {
                num = WorldGen.genRand.Next(3);
            }
            int num3;
            if (num <= 1)
            {
                num = 240;
                int num2 = 18;
                num3 = WorldGen.genRand.Next(num2);
                if (num3 == 0)
                {
                    num3 = 26;
                }
                else if (num3 == 1)
                {
                    num3 = 28;
                }
                else if (num3 == 2)
                {
                    num3 = 20;
                }
                else if (num3 == 3)
                {
                    num3 = 21;
                }
                else if (num3 == 4)
                {
                    num3 = 22;
                }
                else if (num3 == 5)
                {
                    num3 = 24;
                }
                else if (num3 == 6)
                {
                    num3 = 25;
                }
                else if (num3 == 7)
                {
                    num3 = 33;
                }
                else if (num3 == 8)
                {
                    num3 = 34;
                }
                else if (num3 == 9)
                {
                    num3 = 35;
                }
                else if (num3 == 10)
                {
                    num3 = 76;
                }
                else if (num3 == 11)
                {
                    num3 = 77;
                }
                else if (num3 == 12)
                {
                    num3 = 78;
                }
                else if (num3 == 13)
                {
                    num3 = 79;
                }
                else if (num3 == 14)
                {
                    num3 = 82;
                }
                else if (num3 == 15)
                {
                    num3 = 96;
                }
                else if (num3 == 16)
                {
                    num3 = 98;
                }
                else if (num3 == 17)
                {
                    num3 = 100;
                }
            }
            else if (num == 2)
            {
                int num4 = 9;
                num = 245;
                num3 = WorldGen.genRand.Next(num4);
                if (num3 == 0 && WorldGen.genRand.Next(3) != 0)
                {
                    num3 = WorldGen.genRand.Next(num4);
                }
                if (num3 == 0)
                {
                    num3 = 0;
                }
                else if (num3 == 1)
                {
                    num3 = 3;
                }
                else if (num3 == 2)
                {
                    num3 = 5;
                }
                else if (num3 == 3)
                {
                    num3 = 6;
                }
                else if (num3 == 4)
                {
                    num3 = 14;
                }
                else if (num3 == 5)
                {
                    int num5 = WorldGen.genRand.Next(4);
                    if (num5 == 0)
                    {
                        num3 = 15;
                    }
                    if (num5 == 1)
                    {
                        num3 = 16;
                    }
                    if (num5 == 2)
                    {
                        num3 = 17;
                    }
                    if (num5 == 3)
                    {
                        num3 = 18;
                    }
                }
                else if (num3 == 6)
                {
                    num3 = 19;
                }
                else if (num3 == 7)
                {
                    num3 = 20;
                }
                else if (num3 == 8)
                {
                    num3 = 21;
                }
            }
            else
            {
                num = 246;
                int num6 = 8;
                num3 = WorldGen.genRand.Next(num6);
                if (num3 == 0)
                {
                    num3 = 1;
                }
                else if (num3 == 1)
                {
                    num3 = 30;
                }
                else if (num3 == 2)
                {
                    num3 = 31;
                }
                else if (num3 == 3)
                {
                    num3 = 32;
                }
                else if (num3 == 4)
                {
                    num3 = 33;
                }
                else if (num3 == 5)
                {
                    num3 = 34;
                }
                else if (num3 == 6)
                {
                    num3 = 35;
                }
                else if (num3 == 7)
                {
                    num3 = 36;
                }
            }
            return new PaintingEntry
            {
                tileType = num,
                style = num3
            };
        }
References Terraria.WorldGen.genRand, and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.FillRooms(), Terraria.WorldGen.MineHouse(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPaintings.Paintings_GetPaintingEntry().