Terraria Decompiled: Terraria.WorldGen.PlaceObject
PlaceObject()
static bool Terraria.WorldGen.PlaceObject (int x, int y, int type, bool mute = false, int style = 0, int alternate = 0, int random = -1, int direction = -1) inline static
Definition at line 49926 of file WorldGen.cs.
        {
            if (type >= (int)TileID.Count)
            {
                return false;
            }
            TileObject tileObject;
            if (!TileObject.CanPlace(x, y, type, style, direction, out tileObject, false, null))
            {
                return false;
            }
            tileObject.random = random;
            if (TileObject.Place(tileObject))
            {
                WorldGen.SquareTileFrame(x, y, true);
                if (!mute)
                {
                    SoundEngine.PlaySound(0, x * 16, y * 16, 1, 1f, 0f);
                }
            }
            return true;
        }
References Terraria.TileObject.CanPlace(), Terraria.ID.TileID.Count, Terraria.TileObject.Place(), Terraria.Audio.SoundEngine.PlaySound(), and Terraria.WorldGen.SquareTileFrame().
Referenced by Terraria.WorldGen.PlaceGnome(), and Terraria.WorldGen.PlaceTile().