Terraria Decompiled: Terraria.WorldGen.SpawnPlanteraThorns
SpawnPlanteraThorns()
static void Terraria.WorldGen.SpawnPlanteraThorns (Vector2 position) inline static
Definition at line 76646 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            int num = Main.rand.Next(3, 6);
            for (int i = 0; i < num; i++)
            {
                int j = Main.rand.Next(15, 31);
                int num2 = (int)(position.X / 16f);
                int num3 = (int)(position.Y / 16f);
                int num4 = 0;
                int num5 = 0;
                if (Main.rand.Next(2) == 0)
                {
                    if (Main.rand.Next(2) == 0)
                    {
                        num4 = 1;
                    }
                    else
                    {
                        num4 = -1;
                    }
                }
                else if (Main.rand.Next(2) == 0)
                {
                    num5 = 1;
                }
                else
                {
                    num5 = -1;
                }
                while (j > 0)
                {
                    j--;
                    if (!Main.tile[num2, num3].active())
                    {
                        WorldGen.PlaceTile(num2, num3, 655, false, false, -1, 0);
                        if (Main.tile[num2, num3].active() && Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, num2, num3, TileChangeType.None);
                        }
                    }
                    num2 += num4;
                    num3 += num5;
                    if (!WorldGen.InWorld(num2, num3, 0))
                    {
                        return;
                    }
                    if (Main.rand.Next(5) == 0)
                    {
                        if (num5 == 0)
{
                            num4 = 0;
                            if (Main.rand.Next(2) == 0)
{
                                num5 = 1;
                            }
                            else
{
                                num5 = -1;
                            }
                        }
                        else
{
                            num5 = 0;
                            if (Main.rand.Next(2) == 0)
{
                                num4 = 1;
                            }
                            else
{
                                num4 = -1;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), int, Terraria.WorldGen.InWorld(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTile(), Terraria.Main.rand, Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.AI().