Terraria Decompiled: Terraria.WorldGen.CheckRoom
CheckRoom()
static bool Terraria.WorldGen.CheckRoom (int x, int y, int iteration, IRoomCheckFeedback feedback) inline static private
Definition at line 1895 of file WorldGen.cs.
        {
            bool stopOnFail = feedback.StopOnFail;
            if (x < 10 || y < 10 || x >= Main.maxTilesX - 10 || y >= WorldGen.lastMaxTilesY - 10)
            {
                feedback.TooCloseToWorldEdge(x, y, iteration);
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.TooCloseToWorldEdge;
                WorldGen.canSpawn = false;
                return false;
            }
            if (!WorldGen.roomTiles.InBounds(new Point(x, y)))
            {
                feedback.RoomTooBig(x, y, iteration);
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooBig;
                WorldGen.canSpawn = false;
                return false;
            }
            if (!WorldGen.roomTiles.Add(new Point(x, y)))
            {
                return false;
            }
            WorldGen.numRoomTiles++;
            if (stopOnFail && WorldGen.numRoomTiles >= WorldGen.maxRoomTiles)
            {
                feedback.RoomTooBig(x, y, iteration);
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooBig;
                WorldGen.canSpawn = false;
                return false;
            }
            if (x < WorldGen.roomX1)
            {
                WorldGen.roomX1 = x;
            }
            if (x > WorldGen.roomX2)
            {
                WorldGen.roomX2 = x;
            }
            if (y < WorldGen.roomY1)
            {
                WorldGen.roomY1 = y;
            }
            if (y > WorldGen.roomY2)
            {
                WorldGen.roomY2 = y;
            }
            if (stopOnFail && (WorldGen.roomX2 - WorldGen.roomX1 >= WorldGen.maxRoomSize || WorldGen.roomY2 - WorldGen.roomY1 >= WorldGen.maxRoomSize))
            {
                feedback.RoomTooBig(x, y, iteration);
                WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.RoomIsTooBig;
                WorldGen.canSpawn = false;
                return false;
            }
            feedback.AnyBlockScannedHere(x, y, iteration);
            if (Main.tile[x, y].nactive())
            {
                WorldGen.houseTile[(int)Main.tile[x, y].type] = true;
                if (Main.tileSolid[(int)Main.tile[x, y].type])
                {
                    feedback.BlockingWall(x, y, iteration);
                    return false;
                }
                if (Main.tile[x, y].type == 11 && (Main.tile[x, y].frameX == 0 || Main.tile[x, y].frameX == 54 || Main.tile[x, y].frameX == 72 || Main.tile[x, y].frameX == 126))
                {
                    feedback.BlockingOpenGate(x, y, iteration);
                    return false;
                }
                if (Main.tile[x, y].type == 389)
                {
                    feedback.BlockingOpenGate(x, y, iteration);
                    return false;
                }
                if (Main.tile[x, y].type == 386 && ((Main.tile[x, y].frameX < 36 && Main.tile[x, y].frameY == 18) || (Main.tile[x, y].frameX >= 36 && Main.tile[x, y].frameY == 0)))
                {
                    feedback.BlockingOpenGate(x, y, iteration);
                    return false;
                }
                if (Main.tile[x, y].type == 630)
                {
                    WorldGen.roomHasStinkbug = true;
                    feedback.Stinkbug(x, y, iteration);
                }
                if (Main.tile[x, y].type == 631)
                {
                    WorldGen.roomHasEchoStinkbug = true;
                    feedback.EchoStinkbug(x, y, iteration);
                }
            }
            bool flag = false;
            bool flag2 = false;
            for (int i = -2; i < 3; i++)
            {
                if (Main.wallHouse[(int)Main.tile[x + i, y].wall])
                {
                    flag = true;
                }
                if (Main.tile[x + i, y].nactive() && (Main.tileSolid[(int)Main.tile[x + i, y].type] || TileID.Sets.HousingWalls[(int)Main.tile[x + i, y].type]))
                {
                    flag = true;
                }
                if (Main.wallHouse[(int)Main.tile[x, y + i].wall])
                {
                    flag2 = true;
                }
                if (Main.tile[x, y + i].nactive() && (Main.tileSolid[(int)Main.tile[x, y + i].type] || TileID.Sets.HousingWalls[(int)Main.tile[x, y + i].type]))
                {
                    flag2 = true;
                }
            }
            if (!flag || !flag2)
            {
                if (Main.tile[x, y].wall > 0)
                {
                    feedback.UnsafeWall(x, y, iteration);
                    WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.TooManyUnsafeWalls;
                }
                else
                {
                    feedback.MissingAWall(x, y, iteration);
                    WorldGen.roomCheckFailureReason = TownNPCRoomCheckFailureReason.HoleInWallIsTooBig;
                }
                WorldGen.canSpawn = false;
                return false;
            }
            return true;
        }
References Terraria.Utilities.BitSet2D.Add(), Terraria.DataStructures.IRoomCheckFeedback_Spread.AnyBlockScannedHere(), Terraria.DataStructures.IRoomCheckFeedback_Spread.BlockingOpenGate(), Terraria.DataStructures.IRoomCheckFeedback_Spread.BlockingWall(), Terraria.DataStructures.IRoomCheckFeedback_Spread.EchoStinkbug(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.houseTile, Terraria.ID.TileID.Sets.HousingWalls, Terraria.Utilities.BitSet2D.InBounds(), int, Terraria.WorldGen.lastMaxTilesY, Terraria.WorldGen.maxRoomSize, Terraria.WorldGen.maxRoomTiles, Terraria.Main.maxTilesX, Terraria.DataStructures.IRoomCheckFeedback_Spread.MissingAWall(), Terraria.Tile.nactive(), Terraria.WorldGen.numRoomTiles, Terraria.WorldGen.roomTiles, Terraria.DataStructures.IRoomCheckFeedback_Spread.RoomTooBig(), Terraria.WorldGen.roomX1, Terraria.WorldGen.roomX2, Terraria.WorldGen.roomY1, Terraria.WorldGen.roomY2, Terraria.DataStructures.IRoomCheckFeedback_Spread.Stinkbug(), Terraria.DataStructures.IRoomCheckFeedback_Spread.StopOnFail, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.DataStructures.IRoomCheckFeedback_Spread.TooCloseToWorldEdge(), Terraria.Tile.type, Terraria.DataStructures.IRoomCheckFeedback_Spread.UnsafeWall(), Terraria.Tile.wall, and Terraria.Main.wallHouse.
Referenced by Terraria.WorldGen.StartRoomCheck().