Terraria Decompiled: Terraria.WorldGen.GrowTree
GrowTree()
static bool Terraria.WorldGen.GrowTree (int i, int y, int treeHeightAddon = 0, bool ignoreWalls = false) inline static
Definition at line 27058 of file WorldGen.cs.
        {
            int num = y;
            while (Main.tile[i, num].active() && Main.tile[i, num].type == 20)
            {
                num++;
            }
            if ((Main.tile[i - 1, num - 1].liquid != 0 || Main.tile[i, num - 1].liquid != 0 || Main.tile[i + 1, num - 1].liquid != 0) && !WorldGen.notTheBees)
            {
                return false;
            }
            if (Main.tile[i, num].nactive() && !Main.tile[i, num].halfBrick() && Main.tile[i, num].slope() == 0)
            {
                bool flag = ignoreWalls || WorldGen.DefaultTreeWallTest((int)Main.tile[i, num - 1].wall);
                if (WorldGen.IsTileTypeFitForTree(Main.tile[i, num].type) && ((Main.remixWorld && (double)num > Main.worldSurface) || Main.notTheBeesWorld || Main.tile[i, num - 1].wall == 0 || flag) && ((Main.tile[i - 1, num].active() && WorldGen.IsTileTypeFitForTree(Main.tile[i - 1, num].type)) || (Main.tile[i + 1, num].active() && WorldGen.IsTileTypeFitForTree(Main.tile[i + 1, num].type))))
                {
                    ushort type = Main.tile[i, num].type;
                    TileColorCache tileColorCache = Main.tile[i, num].BlockColorAndCoating();
                    if (Main.tenthAnniversaryWorld && !WorldGen.isGeneratingOrLoadingWorld && ((!Main.notTheBeesWorld && !Main.dontStarveWorld) || Main.remixWorld))
                    {
                        tileColorCache.Color = (byte)WorldGen.genRand.Next(1, 13);
                    }
                    int num2 = 2;
                    int num3 = WorldGen.genRand.Next(5, 17) + treeHeightAddon;
                    if (WorldGen.SecretSeed.errorWorld.Enabled && WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(3.0)) == 0)
                    {
                        num3 = WorldGen.genRand.Next(2, 101);
                    }
                    else if (WorldGen.SecretSeed.extraLivingTrees.Enabled)
                    {
                        num3 += WorldGen.genRand.Next(0, 11);
                    }
                    int num4 = num3 + 4;
                    if (Main.tile[i, num].type == 60)
                    {
                        num4 += 5;
                    }
                    bool flag2 = false;
                    if (Main.tile[i, num].type == 70 && WorldGen.EmptyTileCheck(i - num2, i + num2, num - num4, num - 3, 20) && WorldGen.EmptyTileCheck(i - 1, i + 1, num - 2, num - 1, 20))
                    {
                        flag2 = true;
                    }
                    if (WorldGen.EmptyTileCheck(i - num2, i + num2, num - num4, num - 1, 20))
                    {
                        flag2 = true;
                    }
                    if (flag2)
                    {
                        bool flag3 = Main.remixWorld && (double)num < Main.worldSurface;
                        bool flag4 = false;
                        bool flag5 = false;
                        int num5;
                        for (int j = num - num3; j < num; j++)
{
                            Main.tile[i, j].active(true);
                            Main.tile[i, j].type = 5;
                            Main.tile[i, j].UseBlockColors(tileColorCache);
                            num5 = WorldGen.genRand.Next(3);
                            int num6 = WorldGen.genRand.Next(10);
                            if (j == num - 1 || j == num - num3)
{
                                num6 = 0;
                            }
                            while (((num6 == 5 || num6 == 7) && flag4) || ((num6 == 6 || num6 == 7) && flag5))
{
                                num6 = WorldGen.genRand.Next(10);
                            }
                            flag4 = false;
                            flag5 = false;
                            if (num6 == 5 || num6 == 7)
{
                                flag4 = true;
                            }
                            if (num6 == 6 || num6 == 7)
{
                                flag5 = true;
                            }
                            if (num6 == 1)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 0;
                                    Main.tile[i, j].frameY = 66;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 0;
                                    Main.tile[i, j].frameY = 88;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 0;
                                    Main.tile[i, j].frameY = 110;
                                }
                            }
                            else if (num6 == 2)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 22;
                                    Main.tile[i, j].frameY = 0;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 22;
                                    Main.tile[i, j].frameY = 22;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 22;
                                    Main.tile[i, j].frameY = 44;
                                }
                            }
                            else if (num6 == 3)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 44;
                                    Main.tile[i, j].frameY = 66;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 44;
                                    Main.tile[i, j].frameY = 88;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 44;
                                    Main.tile[i, j].frameY = 110;
                                }
                            }
                            else if (num6 == 4)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 22;
                                    Main.tile[i, j].frameY = 66;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 22;
                                    Main.tile[i, j].frameY = 88;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 22;
                                    Main.tile[i, j].frameY = 110;
                                }
                            }
                            else if (num6 == 5)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 88;
                                    Main.tile[i, j].frameY = 0;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 88;
                                    Main.tile[i, j].frameY = 22;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 88;
                                    Main.tile[i, j].frameY = 44;
                                }
                            }
                            else if (num6 == 6)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 66;
                                    Main.tile[i, j].frameY = 66;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 66;
                                    Main.tile[i, j].frameY = 88;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 66;
                                    Main.tile[i, j].frameY = 110;
                                }
                            }
                            else if (num6 == 7)
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 110;
                                    Main.tile[i, j].frameY = 66;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 110;
                                    Main.tile[i, j].frameY = 88;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 110;
                                    Main.tile[i, j].frameY = 110;
                                }
                            }
                            else
{
                                if (num5 == 0)
{
                                    Main.tile[i, j].frameX = 0;
                                    Main.tile[i, j].frameY = 0;
                                }
                                if (num5 == 1)
{
                                    Main.tile[i, j].frameX = 0;
                                    Main.tile[i, j].frameY = 22;
                                }
                                if (num5 == 2)
{
                                    Main.tile[i, j].frameX = 0;
                                    Main.tile[i, j].frameY = 44;
                                }
                            }
                            if (num6 == 5 || num6 == 7)
{
                                Main.tile[i - 1, j].active(true);
                                Main.tile[i - 1, j].type = 5;
                                Main.tile[i - 1, j].UseBlockColors(tileColorCache);
                                num5 = WorldGen.genRand.Next(3);
                                if (WorldGen.genRand.Next(3) < 2 && !flag3)
{
                                    if (num5 == 0)
{
                                        Main.tile[i - 1, j].frameX = 44;
                                        Main.tile[i - 1, j].frameY = 198;
                                    }
                                    if (num5 == 1)
{
                                        Main.tile[i - 1, j].frameX = 44;
                                        Main.tile[i - 1, j].frameY = 220;
                                    }
                                    if (num5 == 2)
{
                                        Main.tile[i - 1, j].frameX = 44;
                                        Main.tile[i - 1, j].frameY = 242;
                                    }
                                }
                                else
{
                                    if (num5 == 0)
{
                                        Main.tile[i - 1, j].frameX = 66;
                                        Main.tile[i - 1, j].frameY = 0;
                                    }
                                    if (num5 == 1)
{
                                        Main.tile[i - 1, j].frameX = 66;
                                        Main.tile[i - 1, j].frameY = 22;
                                    }
                                    if (num5 == 2)
{
                                        Main.tile[i - 1, j].frameX = 66;
                                        Main.tile[i - 1, j].frameY = 44;
                                    }
                                }
                            }
                            if (num6 == 6 || num6 == 7)
{
                                Main.tile[i + 1, j].active(true);
                                Main.tile[i + 1, j].type = 5;
                                Main.tile[i + 1, j].UseBlockColors(tileColorCache);
                                num5 = WorldGen.genRand.Next(3);
                                if (WorldGen.genRand.Next(3) < 2 && !flag3)
{
                                    if (num5 == 0)
{
                                        Main.tile[i + 1, j].frameX = 66;
                                        Main.tile[i + 1, j].frameY = 198;
                                    }
                                    if (num5 == 1)
{
                                        Main.tile[i + 1, j].frameX = 66;
                                        Main.tile[i + 1, j].frameY = 220;
                                    }
                                    if (num5 == 2)
{
                                        Main.tile[i + 1, j].frameX = 66;
                                        Main.tile[i + 1, j].frameY = 242;
                                    }
                                }
                                else
{
                                    if (num5 == 0)
{
                                        Main.tile[i + 1, j].frameX = 88;
                                        Main.tile[i + 1, j].frameY = 66;
                                    }
                                    if (num5 == 1)
{
                                        Main.tile[i + 1, j].frameX = 88;
                                        Main.tile[i + 1, j].frameY = 88;
                                    }
                                    if (num5 == 2)
{
                                        Main.tile[i + 1, j].frameX = 88;
                                        Main.tile[i + 1, j].frameY = 110;
                                    }
                                }
                            }
                        }
                        int num7 = WorldGen.genRand.Next(3);
                        bool flag6 = false;
                        bool flag7 = false;
                        if (Main.tile[i - 1, num].nactive() && !Main.tile[i - 1, num].halfBrick() && Main.tile[i - 1, num].slope() == 0 && WorldGen.IsTileTypeFitForTree(Main.tile[i - 1, num].type))
{
                            flag6 = true;
                        }
                        if (Main.tile[i + 1, num].nactive() && !Main.tile[i + 1, num].halfBrick() && Main.tile[i + 1, num].slope() == 0 && WorldGen.IsTileTypeFitForTree(Main.tile[i + 1, num].type))
{
                            flag7 = true;
                        }
                        if (!flag6)
{
                            if (num7 == 0)
{
                                num7 = 2;
                            }
                            if (num7 == 1)
{
                                num7 = 3;
                            }
                        }
                        if (!flag7)
{
                            if (num7 == 0)
{
                                num7 = 1;
                            }
                            if (num7 == 2)
{
                                num7 = 3;
                            }
                        }
                        if (flag6 && !flag7)
{
                            num7 = 2;
                        }
                        if (flag7 && !flag6)
{
                            num7 = 1;
                        }
                        if (num7 == 0 || num7 == 1)
{
                            Main.tile[i + 1, num - 1].active(true);
                            Main.tile[i + 1, num - 1].type = 5;
                            Main.tile[i + 1, num - 1].UseBlockColors(tileColorCache);
                            num5 = WorldGen.genRand.Next(3);
                            if (num5 == 0)
{
                                Main.tile[i + 1, num - 1].frameX = 22;
                                Main.tile[i + 1, num - 1].frameY = 132;
                            }
                            if (num5 == 1)
{
                                Main.tile[i + 1, num - 1].frameX = 22;
                                Main.tile[i + 1, num - 1].frameY = 154;
                            }
                            if (num5 == 2)
{
                                Main.tile[i + 1, num - 1].frameX = 22;
                                Main.tile[i + 1, num - 1].frameY = 176;
                            }
                        }
                        if (num7 == 0 || num7 == 2)
{
                            Main.tile[i - 1, num - 1].active(true);
                            Main.tile[i - 1, num - 1].type = 5;
                            Main.tile[i - 1, num - 1].UseBlockColors(tileColorCache);
                            num5 = WorldGen.genRand.Next(3);
                            if (num5 == 0)
{
                                Main.tile[i - 1, num - 1].frameX = 44;
                                Main.tile[i - 1, num - 1].frameY = 132;
                            }
                            if (num5 == 1)
{
                                Main.tile[i - 1, num - 1].frameX = 44;
                                Main.tile[i - 1, num - 1].frameY = 154;
                            }
                            if (num5 == 2)
{
                                Main.tile[i - 1, num - 1].frameX = 44;
                                Main.tile[i - 1, num - 1].frameY = 176;
                            }
                        }
                        num5 = WorldGen.genRand.Next(3);
                        if (num7 == 0)
{
                            if (num5 == 0)
{
                                Main.tile[i, num - 1].frameX = 88;
                                Main.tile[i, num - 1].frameY = 132;
                            }
                            if (num5 == 1)
{
                                Main.tile[i, num - 1].frameX = 88;
                                Main.tile[i, num - 1].frameY = 154;
                            }
                            if (num5 == 2)
{
                                Main.tile[i, num - 1].frameX = 88;
                                Main.tile[i, num - 1].frameY = 176;
                            }
                        }
                        else if (num7 == 1)
{
                            if (num5 == 0)
{
                                Main.tile[i, num - 1].frameX = 0;
                                Main.tile[i, num - 1].frameY = 132;
                            }
                            if (num5 == 1)
{
                                Main.tile[i, num - 1].frameX = 0;
                                Main.tile[i, num - 1].frameY = 154;
                            }
                            if (num5 == 2)
{
                                Main.tile[i, num - 1].frameX = 0;
                                Main.tile[i, num - 1].frameY = 176;
                            }
                        }
                        else if (num7 == 2)
{
                            if (num5 == 0)
{
                                Main.tile[i, num - 1].frameX = 66;
                                Main.tile[i, num - 1].frameY = 132;
                            }
                            if (num5 == 1)
{
                                Main.tile[i, num - 1].frameX = 66;
                                Main.tile[i, num - 1].frameY = 154;
                            }
                            if (num5 == 2)
{
                                Main.tile[i, num - 1].frameX = 66;
                                Main.tile[i, num - 1].frameY = 176;
                            }
                        }
                        if (WorldGen.genRand.Next(13) != 0 && !flag3)
{
                            num5 = WorldGen.genRand.Next(3);
                            if (num5 == 0)
{
                                Main.tile[i, num - num3].frameX = 22;
                                Main.tile[i, num - num3].frameY = 198;
                            }
                            if (num5 == 1)
{
                                Main.tile[i, num - num3].frameX = 22;
                                Main.tile[i, num - num3].frameY = 220;
                            }
                            if (num5 == 2)
{
                                Main.tile[i, num - num3].frameX = 22;
                                Main.tile[i, num - num3].frameY = 242;
                            }
                        }
                        else
{
                            num5 = WorldGen.genRand.Next(3);
                            if (num5 == 0)
{
                                Main.tile[i, num - num3].frameX = 0;
                                Main.tile[i, num - num3].frameY = 198;
                            }
                            if (num5 == 1)
{
                                Main.tile[i, num - num3].frameX = 0;
                                Main.tile[i, num - num3].frameY = 220;
                            }
                            if (num5 == 2)
{
                                Main.tile[i, num - num3].frameX = 0;
                                Main.tile[i, num - num3].frameY = 242;
                            }
                        }
                        WorldGen.RangeFrame(i - 2, num - num3 - 1, i + 2, num + 1);
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i - 1, num - num3, 3, num3, TileChangeType.None);
                        }
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.WorldGen.DefaultTreeWallTest(), Terraria.Main.dontStarveWorld, Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.Variations.errorWorldAdjustment(), Terraria.WorldGen.SecretSeed.extraLivingTrees, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.IsTileTypeFitForTree(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.Main.notTheBeesWorld, Terraria.WorldGen.RangeFrame(), Terraria.Main.remixWorld, Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.OverGrownDungeon(), and Terraria.WorldGen.TryGrowingTreeByType().