Terraria Decompiled: Terraria.WorldGen.GetLeftMostDungeonTile
GetLeftMostDungeonTile()
static int Terraria.WorldGen.GetLeftMostDungeonTile () inline static private
Definition at line 20961 of file WorldGen.cs.
        {
            if (GenVars.dungeonGenVars[0] == null)
            {
                return Main.maxTilesX - 300;
            }
            DungeonBounds outerPotentialDungeonBounds = GenVars.dungeonGenVars[0].outerPotentialDungeonBounds;
            int num = outerPotentialDungeonBounds.Right;
            for (int i = num; i > outerPotentialDungeonBounds.Left; i--)
            {
                for (int j = outerPotentialDungeonBounds.Top; j < outerPotentialDungeonBounds.Bottom; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if ((tile.active() && DungeonUtils.IsConsideredDungeonTile((int)tile.type, false)) || DungeonUtils.IsConsideredDungeonWall((int)tile.wall, false))
                    {
                        num = i;
                        break;
                    }
                }
            }
            return num;
        }
References Terraria.Tile.active(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Bottom, Terraria.WorldBuilding.GenVars.dungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.GameContent.Generation.Dungeon.DungeonBounds.Left, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Right, Terraria.Main.tile, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.RandomizeWorldSpawn().