Terraria Decompiled: Terraria.WorldGen.OasisPlantWaterCheck
OasisPlantWaterCheck()
static bool Terraria.WorldGen.OasisPlantWaterCheck (int x, int y, bool boost = false) inline static private
Definition at line 45872 of file WorldGen.cs.
        {
            int num = 45;
            int num2 = 20;
            if (boost)
            {
                num += 4;
                num2 += 3;
            }
            int num3 = 20;
            int num4 = 0;
            for (int i = x - num; i <= x + num; i++)
            {
                if (x > WorldGen.beachDistance && x < Main.maxTilesX - WorldGen.beachDistance)
                {
                    for (int j = y - num2; j <= y + num2; j++)
                    {
                        if (WorldGen.InWorld(i, j, 0) && !WorldGen.SolidTile(i, j, false))
{
                            num4 += (int)Main.tile[i, j].liquid;
                        }
                    }
                }
            }
            return num4 / 255 >= num3;
        }
References Terraria.WorldGen.beachDistance, int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.WorldGen.SolidTile(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.PlaceOasisPlant(), and Terraria.WorldGen.UpdateWorld_OvergroundTile().