Terraria Decompiled: Terraria.WorldGen.Finish
Finish()
static void Terraria.WorldGen.Finish () inline static
Definition at line 19611 of file WorldGen.cs.
        {
            Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
            Main.NotifyOfEvent(GameNotificationType.WorldGen);
            WorldGen.drunkWorldGenText = false;
        }
References Terraria.IO.FileMetadata.FromCurrentSettings(), and Terraria.Main.NotifyOfEvent().
Referenced by Terraria.WorldGen.GenerateWorld().