Terraria Decompiled: Terraria.WorldGen.GetTileTypeCountByCategory
GetTileTypeCountByCategory()
static int Terraria.WorldGen.GetTileTypeCountByCategory (int[] tileTypeCounts, TileScanGroup group) inline static
Definition at line 1600 of file WorldGen.cs.
        {
            switch (group)
            {
            case TileScanGroup.None:
                return 0;
            case TileScanGroup.Corruption:
                return tileTypeCounts[23] + tileTypeCounts[24] + tileTypeCounts[25] + tileTypeCounts[32] + tileTypeCounts[112] + tileTypeCounts[163] + tileTypeCounts[400] + tileTypeCounts[398] + -5 * tileTypeCounts[27];
            case TileScanGroup.Crimson:
                return tileTypeCounts[199] + tileTypeCounts[203] + tileTypeCounts[200] + tileTypeCounts[401] + tileTypeCounts[399] + tileTypeCounts[234] + tileTypeCounts[352] - 5 * tileTypeCounts[27];
            case TileScanGroup.Hallow:
                return tileTypeCounts[109] + tileTypeCounts[110] + tileTypeCounts[113] + tileTypeCounts[117] + tileTypeCounts[116] + tileTypeCounts[164] + tileTypeCounts[403] + tileTypeCounts[402];
            case TileScanGroup.TotalGoodEvil:
            {
                int tileTypeCountByCategory = WorldGen.GetTileTypeCountByCategory(tileTypeCounts, TileScanGroup.Hallow);
                int tileTypeCountByCategory2 = WorldGen.GetTileTypeCountByCategory(tileTypeCounts, TileScanGroup.Corruption);
                int tileTypeCountByCategory3 = WorldGen.GetTileTypeCountByCategory(tileTypeCounts, TileScanGroup.Crimson);
                int num = 5 * tileTypeCounts[27];
                int num2 = tileTypeCountByCategory2 + tileTypeCountByCategory3 + num;
                return tileTypeCountByCategory - num2;
            }
            default:
                return 0;
            }
        }
References Terraria.WorldGen.GetTileTypeCountByCategory().
Referenced by Terraria.WorldGen.GetTileTypeCountByCategory(), and Terraria.WorldGen.ScoreRoom().