Terraria Decompiled: Terraria.WorldGen.Check4x3Wall
Check4x3Wall()
static void Terraria.WorldGen.Check4x3Wall (int x, int y) inline static
Definition at line 43179 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int type = (int)Main.tile[x, y].type;
            int num = 0;
            int i = (int)(Main.tile[x, y].frameY / 18);
            while (i >= 3)
            {
                i -= 3;
                num++;
            }
            int num2 = y - i;
            int num3 = x - (int)(Main.tile[x, y].frameX / 18);
            i = num * 54;
            for (int j = num3; j < num3 + 4; j++)
            {
                for (int k = num2; k < num2 + 3; k++)
                {
                    if ((int)Main.tile[j, k].type != type || !Main.tile[j, k].active() || Main.tile[j, k].wall <= 0 || (int)Main.tile[j, k].frameY != i + (k - num2) * 18 || (int)Main.tile[j, k].frameX != (j - num3) * 18)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int l = num3; l < num3 + 4; l++)
                {
                    for (int m = num2; m < num2 + 3; m++)
                    {
                        if ((int)Main.tile[l, m].type == type && Main.tile[l, m].active())
{
                            WorldGen.KillTile(l, m, false, false, false);
                        }
                    }
                }
                if (type == 241)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1417, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrameImportant().