Terraria Decompiled: Terraria.WorldGen.CrimVein
CrimVein()
static void Terraria.WorldGen.CrimVein (Vector2D position, Vector2D velocity) inline static
Definition at line 76333 of file WorldGen.cs.
        {
            double num = (double)WorldGen.genRand.Next(15, 26);
            bool flag = true;
            Vector2D vector2D = velocity;
            Vector2D vector2D2 = position;
            int num2 = WorldGen.genRand.Next(100, 150);
            if (velocity.Y < 0.0)
            {
                num2 -= 25;
            }
            while (flag)
            {
                num += (double)WorldGen.genRand.Next(-50, 51) * 0.02;
                if (num < 15.0)
                {
                    num = 15.0;
                }
                if (num > 25.0)
                {
                    num = 25.0;
                }
                int num3 = (int)(position.X - num / 2.0);
                while ((double)num3 < position.X + num / 2.0)
                {
                    int num4 = (int)(position.Y - num / 2.0);
                    while ((double)num4 < position.Y + num / 2.0)
                    {
                        if (WorldGen.CanEvilReplace(num3, num4))
{
                            double num5 = Math.Abs((double)num3 - position.X);
                            double num6 = Math.Abs((double)num4 - position.Y);
                            double num7 = Math.Sqrt(num5 * num5 + num6 * num6);
                            if (num7 < num * 0.2)
{
                                Main.tile[num3, num4].active(false);
                                Main.tile[num3, num4].wall = GenVars.crimStoneWall;
                            }
                            else if (num7 < num * 0.5 && Main.tile[num3, num4].wall != GenVars.crimStoneWall)
{
                                Main.tile[num3, num4].active(true);
                                Main.tile[num3, num4].type = GenVars.crimStone;
                                if (num7 < num * 0.4)
{
                                    Main.tile[num3, num4].wall = GenVars.crimStoneWall;
                                }
                            }
                        }
                        num4++;
                    }
                    num3++;
                }
                velocity.X += (double)WorldGen.genRand.Next(-50, 51) * 0.05;
                velocity.Y += (double)WorldGen.genRand.Next(-50, 51) * 0.05;
                if (velocity.Y < vector2D.Y - 0.75)
                {
                    velocity.Y = vector2D.Y - 0.75;
                }
                if (velocity.Y > vector2D.Y + 0.75)
                {
                    velocity.Y = vector2D.Y + 0.75;
                }
                if (velocity.X < vector2D.X - 0.75)
                {
                    velocity.X = vector2D.X - 0.75;
                }
                if (velocity.X > vector2D.X + 0.75)
                {
                    velocity.X = vector2D.X + 0.75;
                }
                position += velocity;
                if (Math.Abs(position.X - vector2D2.X) + Math.Abs(position.Y - vector2D2.Y) > (double)num2)
                {
                    flag = false;
                }
            }
            WorldGen.heartPos[WorldGen.heartCount] = position.ToPoint();
            WorldGen.heartCount++;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.CanEvilReplace(), Terraria.WorldBuilding.GenVars.crimStone, Terraria.WorldBuilding.GenVars.crimStoneWall, Terraria.WorldGen.genRand, Terraria.WorldGen.heartCount, Terraria.WorldGen.heartPos, int, Terraria.Utilities.UnifiedRandom.Next(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.CrimStart().