Terraria Decompiled: Terraria.WorldGen.AddLihzahrdAltar
AddLihzahrdAltar()
static void Terraria.WorldGen.AddLihzahrdAltar (int x, int y) inline static
Definition at line 29468 of file WorldGen.cs.
        {
            for (int i = 0; i < 3; i++)
            {
                for (int j = 0; j < 2; j++)
                {
                    int num = x + i;
                    int num2 = y + j;
                    ushort wall = Main.tile[num, num2].wall;
                    Main.tile[num, num2].ClearEverything();
                    Main.tile[num, num2].active(true);
                    Main.tile[num, num2].type = 237;
                    Main.tile[num, num2].frameX = (short)(i * 18);
                    Main.tile[num, num2].frameY = (short)(j * 18);
                    Main.tile[num, num2].wall = wall;
                }
                Main.tile[x + i, y + 2].ClearEverything();
                Main.tile[x + i, y + 2].active(true);
                Main.tile[x + i, y + 2].slope(0);
                Main.tile[x + i, y + 2].halfBrick(false);
                Main.tile[x + i, y + 2].type = 226;
            }
        }
References Terraria.Tile.active(), Terraria.Tile.ClearEverything(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures().