Terraria Decompiled: Terraria.WorldGen.FinishRemixWorld
FinishRemixWorld()
static void Terraria.WorldGen.FinishRemixWorld () inline static private
Definition at line 23449 of file WorldGen.cs.
        {
            int num = 0;
            for (int i = 25; i < Main.maxTilesX - 25; i++)
            {
                for (int j = 25; j < Main.maxTilesY - 25; j++)
                {
                    if (Main.tile[i, j].active() && (TileID.Sets.Clouds[(int)Main.tile[i, j].type] || Main.tile[i, j].type == 202))
                    {
                        if (j > num)
{
                            num = j;
                        }
                        if (!WorldGen.tenthAnniversaryWorldGen || WorldGen.getGoodWorldGen)
{
                            if (WorldGen.drunkWorldGen)
{
                                if (GenVars.crimsonLeft)
{
                                    if (i < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                        Main.tile[i, j].type = 195;
                                    }
                                    else
{
                                        Main.tile[i, j].type = 474;
                                    }
                                }
                                else if (i < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                    Main.tile[i, j].type = 474;
                                }
                                else
{
                                    Main.tile[i, j].type = 195;
                                }
                            }
                            else if (WorldGen.crimson)
{
                                Main.tile[i, j].type = 195;
                            }
                            else
{
                                Main.tile[i, j].type = 474;
                            }
                        }
                    }
                    if ((Main.tile[i, j].wall == 73 || Main.tile[i, j].wall == 82) && (!WorldGen.tenthAnniversaryWorldGen || WorldGen.getGoodWorldGen))
                    {
                        if (WorldGen.drunkWorldGen)
{
                            if (GenVars.crimsonLeft)
{
                                if (i < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                    Main.tile[i, j].wall = 77;
                                }
                                else
{
                                    Main.tile[i, j].wall = 233;
                                }
                            }
                            else if (i < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                Main.tile[i, j].wall = 233;
                            }
                            else
{
                                Main.tile[i, j].wall = 77;
                            }
                        }
                        else if (WorldGen.crimson)
{
                            Main.tile[i, j].wall = 77;
                        }
                        else
{
                            Main.tile[i, j].wall = 233;
                        }
                    }
                }
            }
            for (int k = 25; k < Main.maxTilesX - 25; k++)
            {
                for (int l = 25; l < Main.maxTilesY - 25; l++)
                {
                    int num2 = 1;
                    if (WorldGen.crimson)
                    {
                        num2 = 4;
                    }
                    if ((l > num || WorldGen.SecretSeed.errorWorld.Enabled || WorldGen.SecretSeed.surfaceIsInSpace.Enabled) && (double)l < Main.worldSurface && k > WorldGen.beachDistance && k < Main.maxTilesX - WorldGen.beachDistance)
                    {
                        if (Main.tile[k, l].wall == 87)
{
                            if (Main.tile[k, l].liquid > 0)
{
                                Main.tile[k, l].liquidType(0);
                            }
                        }
                        else if (WorldGen.getGoodWorldGen)
{
                            if (Main.tile[k, l].liquid > 0)
{
                                if (Main.tileLavaDeath[(int)Main.tile[k, l].type])
{
                                    WorldGen.KillTile(k, l, false, false, false);
                                }
                                Main.tile[k, l].lava(true);
                            }
                            if (Main.tile[k, l].type == 375 || Main.tile[k, l].type == 373 || Main.tile[k, l].type == 709)
{
                                Main.tile[k, l].type = 374;
                            }
                            if (Main.tile[k, l].type == 230 || Main.tile[k, l].type == 229 || Main.tile[k, l].type == 659 || Main.tile[k, l].type == 56)
{
                                WorldGen.KillTile(k, l, false, false, false);
                            }
                            if (Main.tile[k, l].type == 82 || Main.tile[k, l].type == 83 || Main.tile[k, l].type == 84)
{
                                WorldGen.TileFrame(k, l, false, false);
                            }
                        }
                        else if (WorldGen.notTheBees)
{
                            if (Main.tile[k, l].liquid > 0)
{
                                Main.tile[k, l].honey(true);
                            }
                            if (Main.tile[k, l].type == 374 || Main.tile[k, l].type == 373 || Main.tile[k, l].type == 709)
{
                                Main.tile[k, l].type = 375;
                            }
                            if (Main.tile[k, l].type == 230 || Main.tile[k, l].type == 229 || Main.tile[k, l].type == 659 || Main.tile[k, l].type == 56)
{
                                WorldGen.KillTile(k, l, false, false, false);
                            }
                            if (Main.tile[k, l].type == 82 || Main.tile[k, l].type == 83 || Main.tile[k, l].type == 84)
{
                                WorldGen.TileFrame(k, l, false, false);
                            }
                        }
                        else if (WorldGen.drunkWorldGen && WorldGen.tenthAnniversaryWorldGen)
{
                            if (Main.tile[k, l].liquid > 0)
{
                                if (Main.tileLavaDeath[(int)Main.tile[k, l].type])
{
                                    WorldGen.KillTile(k, l, false, false, false);
                                }
                                Main.tile[k, l].shimmer(true);
                            }
                            if (Main.tile[k, l].type == 374 || Main.tile[k, l].type == 373 || Main.tile[k, l].type == 375)
{
                                Main.tile[k, l].type = 709;
                            }
                            if (Main.tile[k, l].type == 230 || Main.tile[k, l].type == 229 || Main.tile[k, l].type == 659 || Main.tile[k, l].type == 56)
{
                                WorldGen.KillTile(k, l, false, false, false);
                            }
                            if (Main.tile[k, l].type == 82 || Main.tile[k, l].type == 83 || Main.tile[k, l].type == 84)
{
                                WorldGen.TileFrame(k, l, false, false);
                            }
                        }
                    }
                    if ((double)l < Main.worldSurface + (double)WorldGen.genRand.Next(3))
                    {
                        if (WorldGen.tenthAnniversaryWorldGen && !WorldGen.getGoodWorldGen)
{
                            if (Main.tile[k, l].wall != 3 && Main.tile[k, l].wall != 83)
{
                                WorldGen.Convert(k, l, 2, true, true);
                                if (Main.tile[k, l].type == 661 || Main.tile[k, l].type == 662)
{
                                    Main.tile[k, l].type = 109;
                                    WorldGen.SquareTileFrame(k, l, true);
                                    if (WorldGen.SolidTile(k, l, false) && !Main.tile[k, l - 1].active())
{
                                        WorldGen.PlaceTile(k, l, 110, false, false, -1, 0);
                                    }
                                    for (int m = k - 3; m <= k + 3; m++)
{
                                        for (int n = l - 3; n <= l + 3; n++)
{
                                            if (Main.tile[m, n].type == 59)
{
                                                Main.tile[m, n].type = 0;
                                            }
                                        }
                                    }
                                }
                            }
                        }
                        else if (WorldGen.drunkWorldGen)
{
                            if (GenVars.crimsonLeft)
{
                                if (k < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                    WorldGen.Convert(k, l, 4, true, true);
                                }
                                else
{
                                    WorldGen.Convert(k, l, 1, true, true);
                                }
                            }
                            else if (k < Main.maxTilesX / 2 + WorldGen.genRand.Next(-2, 3))
{
                                WorldGen.Convert(k, l, 1, true, true);
                            }
                            else
{
                                WorldGen.Convert(k, l, 4, true, true);
                            }
                        }
                        else
{
                            WorldGen.Convert(k, l, num2, true, true);
                        }
                    }
                    if ((double)l < Main.worldSurface - (double)WorldGen.genRand.Next(19, 22) && (Main.tile[k, l].wall == 178 || Main.tile[k, l].wall == 180))
                    {
                        Main.tile[k, l].wall = 0;
                    }
                    if (Main.tile[k, l].active() && Main.tile[k, l].type == 56)
                    {
                        WorldGen.KillTile(k, l, false, false, false);
                    }
                    if ((double)l > Main.rockLayer && l < Main.maxTilesY - 350 && Main.tile[k, l].type == 0 && Main.tile[k, l].active() && (!Main.tile[k - 1, l - 1].active() || !WorldGen.SolidTile(k, l - 1, false) || !Main.tile[k + 1, l - 1].active() || !Main.tile[k - 1, l].active() || !Main.tile[k + 1, l].active() || !Main.tile[k - 1, l + 1].active() || !Main.tile[k, l + 1].active() || !Main.tile[k + 1, l + 1].active()))
                    {
                        Main.tile[k, l].type = 2;
                    }
                }
            }
            Liquid.QuickWater(-2, -1, -1);
            bool flag = true;
            if (WorldGen.SecretSeed.randomSpawn.Enabled)
            {
                flag = false;
            }
            while (flag)
            {
                int num3 = (int)((double)Main.maxTilesX * 0.38);
                int num4 = (int)((double)Main.maxTilesX * 0.62);
                int maxTilesY = Main.maxTilesY;
                int num5 = Main.maxTilesY - 135;
                int maxTilesY2 = Main.maxTilesY;
                for (int num6 = num3; num6 < num4 + 15; num6++)
                {
                    for (int num7 = Main.maxTilesY - 200; num7 < num5 + 10; num7++)
                    {
                        Main.tile[num6, num7].liquid = 0;
                        if (Main.tile[num6, num7].type == 58)
{
                            Main.tile[num6, num7].type = 57;
                        }
                        if (Main.tile[num6, num7].type == 230)
{
                            Main.tile[num6, num7].active(false);
                        }
                        if (Main.tile[num6, num7].type == 56)
{
                            Main.tile[num6, num7].active(false);
                        }
                        if (Main.tile[num6, num7].type == 659)
{
                            Main.tile[num6, num7].active(false);
                        }
                    }
                }
                Liquid.QuickWater(-2, -1, -1);
                flag = false;
                for (int num8 = -10; num8 < 15; num8++)
                {
                    if (Main.tile[Main.spawnTileX, Main.spawnTileY - num8].liquid > 0)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            WorldGen.AddTrees(true);
            if (!WorldGen.tenthAnniversaryWorldGen || WorldGen.getGoodWorldGen)
            {
                for (int num9 = 10; num9 < Main.maxTilesX - 10; num9++)
                {
                    byte b = 22;
                    byte b2 = 22;
                    if (WorldGen.drunkWorldGen)
                    {
                        if ((GenVars.crimsonLeft && num9 < Main.maxTilesX / 2) || (!GenVars.crimsonLeft && num9 > Main.maxTilesX / 2))
{
                            b2 = 13;
                            b = 13;
                        }
                    }
                    else if (WorldGen.crimson)
                    {
                        b2 = 13;
                        b = 13;
                    }
                    for (int num10 = 10; num10 < Main.maxTilesY - 10; num10++)
                    {
                        if (Main.tile[num9, num10].active() && (Main.tileDungeon[(int)Main.tile[num9, num10].type] || TileID.Sets.CrackedBricks[(int)Main.tile[num9, num10].type]))
{
                            Main.tile[num9, num10].color(b);
                        }
                        if (Main.wallDungeon[(int)Main.tile[num9, num10].wall])
{
                            Main.tile[num9, num10].wallColor(25);
                            if (Main.tile[num9, num10].type == 19 && Main.tile[num9, num10].frameY != 180)
{
                                Main.tile[num9, num10].color(b);
                            }
                        }
                        if (Main.tile[num9, num10].active())
{
                            bool flag2 = false;
                            if (Main.tenthAnniversaryWorld)
{
                                if (!WorldGen.SecretSeed.noSurface.Enabled && Main.tile[num9, num10].type == 191)
{
                                    flag2 = true;
                                }
                                if (Main.tile[num9, num10].active() && Main.tile[num9, num10].type == 151)
{
                                    Main.tile[num9, num10].color(b);
                                }
                            }
                            if (Main.tile[num9, num10].type == 226)
{
                                flag2 = true;
                            }
                            if (Main.tile[num9, num10].type == 61 && Main.tile[num9, num10 + 1].type == 226)
{
                                flag2 = true;
                            }
                            if (Main.tile[num9, num10].type == 137)
{
                                int num11 = (int)(Main.tile[num9, num10].frameY / 18);
                                if (num11 >= 1 && num11 <= 4)
{
                                    flag2 = true;
                                }
                            }
                            if (flag2)
{
                                Main.tile[num9, num10].color(b2);
                            }
                        }
                        if (!WorldGen.SecretSeed.noSurface.Enabled && Main.tile[num9, num10].wall == 244)
{
                            Main.tile[num9, num10].wallColor(25);
                        }
                        if (Main.tile[num9, num10].wall == 34)
{
                            Main.tile[num9, num10].wallColor(25);
                        }
                        if (Main.tile[num9, num10].wall == 87)
{
                            Main.tile[num9, num10].wallColor(25);
                            Main.tile[num9, num10].color(b2);
                        }
                    }
                }
            }
            double num12 = (double)Main.maxTilesX / 4200.0;
            num12 *= (double)WorldGen.genRand.Next(2, 5);
            int num13 = 0;
            while ((double)num13 < num12)
            {
                int num14 = WorldGen.genRand.Next((int)((double)Main.maxTilesX * 0.39), (int)((double)Main.maxTilesX * 0.61));
                int num15 = WorldGen.genRand.Next(10, 31);
                for (int num16 = num14 - num15; num16 <= num14 + num15; num16++)
                {
                    for (int num17 = Main.maxTilesY - 250; num17 < Main.maxTilesY - 25; num17++)
                    {
                        if (Main.tile[num16, num17].type == 637)
{
                            Main.tile[num16, num17].frameX = (short)(18 * Main.rand.Next(6, 11));
                        }
                    }
                }
                num13++;
            }
            if (WorldGen.notTheBees)
            {
                for (int num18 = 3; num18 < Main.maxTilesX - 3; num18++)
                {
                    bool flag3 = true;
                    int num19 = 0;
                    while ((double)num19 < Main.worldSurface)
                    {
                        if (flag3)
{
                            if (Main.tile[num18, num19].wall == 86)
{
                                Main.tile[num18, num19].wall = 0;
                            }
                            if (Main.tile[num18, num19].active())
{
                                flag3 = false;
                            }
                        }
                        else if (Main.tile[num18, num19].wall == 0 && Main.tile[num18, num19 + 1].wall == 0 && Main.tile[num18, num19 + 2].wall == 0 && Main.tile[num18, num19 + 3].wall == 0 && Main.tile[num18, num19 + 4].wall == 0 && Main.tile[num18 - 1, num19].wall == 0 && Main.tile[num18 + 1, num19].wall == 0 && Main.tile[num18 - 2, num19].wall == 0 && Main.tile[num18 + 2, num19].wall == 0 && !Main.tile[num18, num19].active() && !Main.tile[num18, num19 + 1].active() && !Main.tile[num18, num19 + 2].active() && !Main.tile[num18, num19 + 3].active())
{
                            flag3 = true;
                        }
                        num19++;
                    }
                }
            }
            Liquid.QuickWater(-2, -1, -1);
            for (int num20 = 0; num20 < Main.maxTilesX; num20++)
            {
                for (int num21 = 0; num21 < Main.maxTilesY; num21++)
                {
                    if (Main.tile[num20, num21].type == 518)
                    {
                        WorldGen.CheckLilyPad(num20, num21);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddTrees(), Terraria.WorldGen.beachDistance, Terraria.WorldGen.CheckLilyPad(), Terraria.ID.TileID.Sets.Clouds, Terraria.Tile.color(), Terraria.WorldGen.Convert(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Tile.honey(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.SecretSeed.noSurface, Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceTile(), Terraria.Liquid.QuickWater(), Terraria.Main.rand, Terraria.WorldGen.SecretSeed.randomSpawn, Terraria.Main.rockLayer, Terraria.Tile.shimmer(), Terraria.WorldGen.SolidTile(), Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.SecretSeed.surfaceIsInSpace, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.WorldGen.TileFrame(), Terraria.Main.tileLavaDeath, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.