Terraria Decompiled: Terraria.WorldGen.Convert
Convert() [2/2]
static void Terraria.WorldGen.Convert (int i2, int j2, int conversionType, bool tiles = true, bool walls = true) inline static
Definition at line 53649 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(i2, j2, 1) || (!tiles && !walls))
            {
                return;
            }
            Tile tile = Main.tile[i2, j2];
            ushort type = tile.type;
            ushort wall = tile.wall;
            if (!tile.active() && wall <= 0)
            {
                return;
            }
            if (conversionType == 4)
            {
                if (walls)
                {
                    if (WallID.Sets.Conversion.Grass[(int)wall] && wall != 81)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 81);
                    }
                    else if (WallID.Sets.Conversion.Stone[(int)wall] && wall != 83)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 83);
                    }
                    else if (WallID.Sets.Conversion.HardenedSand[(int)wall] && wall != 218)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 218);
                    }
                    else if (WallID.Sets.Conversion.Sandstone[(int)wall] && wall != 221)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 221);
                    }
                    else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 192)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 192);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 193)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 193);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 194)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 194);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 195)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 195);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 19);
                        return;
                    }
                    if ((Main.tileMoss[(int)type] || TileID.Sets.Conversion.Stone[(int)type]) && type != 203)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 203);
                        return;
                    }
                    if (TileID.Sets.Conversion.JungleGrass[(int)type] && type != 662)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 662);
                        return;
                    }
                    if (TileID.Sets.Conversion.Grass[(int)type] && type != 199)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 199);
                        return;
                    }
                    if (TileID.Sets.Conversion.Ice[(int)type] && type != 200)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 200);
                        return;
                    }
                    if (TileID.Sets.Conversion.Sand[(int)type] && type != 234)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 234);
                        return;
                    }
                    if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 399)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 399);
                        return;
                    }
                    if (TileID.Sets.Conversion.Sandstone[(int)type] && type != 401)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 401);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 352)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 352);
                        return;
                    }
                }
            }
            else if (conversionType == 2)
            {
                if (walls)
                {
                    if (WallID.Sets.Conversion.Grass[(int)wall] && wall != 70)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 70);
                    }
                    else if (WallID.Sets.Conversion.Stone[(int)wall] && wall != 28)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 28);
                    }
                    else if (WallID.Sets.Conversion.HardenedSand[(int)wall] && wall != 219)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 219);
                    }
                    else if (WallID.Sets.Conversion.Sandstone[(int)wall] && wall != 222)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 222);
                    }
                    else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 200)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 200);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 201)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 201);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 202)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 202);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 203)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 203);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 20);
                    }
                    else if ((Main.tileMoss[(int)type] || TileID.Sets.Conversion.Stone[(int)type]) && type != 117)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 117);
                    }
                    else if (TileID.Sets.Conversion.GolfGrass[(int)type] && type != 492)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 492);
                    }
                    else if (TileID.Sets.Conversion.Grass[(int)type] && type != 109 && type != 492)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 109);
                    }
                    else if (TileID.Sets.Conversion.Ice[(int)type] && type != 164)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 164);
                    }
                    else if (TileID.Sets.Conversion.Sand[(int)type] && type != 116)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 116);
                    }
                    else if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 402)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 402);
                    }
                    else if (TileID.Sets.Conversion.Sandstone[(int)type] && type != 403)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 403);
                    }
                    else if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                        }
                    }
                    if (type == 59 && (Main.tile[i2 - 1, j2].type == 109 || Main.tile[i2 + 1, j2].type == 109 || Main.tile[i2, j2 - 1].type == 109 || Main.tile[i2, j2 + 1].type == 109))
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 0);
                        return;
                    }
                }
            }
            else if (conversionType == 1)
            {
                if (walls)
                {
                    if (WallID.Sets.Conversion.Grass[(int)wall] && wall != 69)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 69);
                    }
                    else if (WallID.Sets.Conversion.Stone[(int)wall] && wall != 3)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 3);
                    }
                    else if (WallID.Sets.Conversion.HardenedSand[(int)wall] && wall != 217)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 217);
                    }
                    else if (WallID.Sets.Conversion.Sandstone[(int)wall] && wall != 220)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 220);
                    }
                    else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 188)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 188);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 189)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 189);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 190)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 190);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 191)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 191);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 18);
                        return;
                    }
                    if ((Main.tileMoss[(int)type] || TileID.Sets.Conversion.Stone[(int)type]) && type != 25)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 25);
                        return;
                    }
                    if (TileID.Sets.Conversion.JungleGrass[(int)type] && type != 661)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 661);
                        return;
                    }
                    if (TileID.Sets.Conversion.Grass[(int)type] && type != 23)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 23);
                        return;
                    }
                    if (TileID.Sets.Conversion.Ice[(int)type] && type != 163)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 163);
                        return;
                    }
                    if (TileID.Sets.Conversion.Sand[(int)type] && type != 112)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 112);
                        return;
                    }
                    if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 398)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 398);
                        return;
                    }
                    if (TileID.Sets.Conversion.Sandstone[(int)type] && type != 400)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 400);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 32)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 32);
                        return;
                    }
                }
            }
            else if (conversionType == 3)
            {
                if (walls && WallID.Sets.CanBeConvertedToGlowingMushroom[(int)wall])
                {
                    WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 80);
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 22);
                        return;
                    }
                    if (tile.type == 60)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 70);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 5)
            {
                if (walls)
                {
                    if ((WallID.Sets.Conversion.Stone[(int)wall] || WallID.Sets.Conversion.NewWall1[(int)wall] || WallID.Sets.Conversion.NewWall2[(int)wall] || WallID.Sets.Conversion.NewWall3[(int)wall] || WallID.Sets.Conversion.NewWall4[(int)wall] || WallID.Sets.Conversion.Ice[(int)wall] || WallID.Sets.Conversion.Sandstone[(int)wall]) && wall != 187)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 187);
                    }
                    else if ((WallID.Sets.Conversion.HardenedSand[(int)wall] || WallID.Sets.Conversion.Dirt[(int)wall] || WallID.Sets.Conversion.Snow[(int)wall]) && wall != 216)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 216);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 16);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Grass[(int)type] || TileID.Sets.Conversion.Sand[(int)type] || TileID.Sets.Conversion.Snow[(int)type] || TileID.Sets.Conversion.Dirt[(int)type]) && type != 53)
                    {
                        int num = 53;
                        if (WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(i2, j2))
{
                            num = 397;
                        }
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, num);
                        return;
                    }
                    if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 397)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 397);
                        return;
                    }
                    if ((Main.tileMoss[(int)type] || TileID.Sets.Conversion.Stone[(int)type] || TileID.Sets.Conversion.Ice[(int)type] || TileID.Sets.Conversion.Sandstone[(int)type]) && type != 396)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 396);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 69)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 6)
            {
                if (walls)
                {
                    if ((WallID.Sets.Conversion.Stone[(int)wall] || WallID.Sets.Conversion.NewWall1[(int)wall] || WallID.Sets.Conversion.NewWall2[(int)wall] || WallID.Sets.Conversion.NewWall3[(int)wall] || WallID.Sets.Conversion.NewWall4[(int)wall] || WallID.Sets.Conversion.Ice[(int)wall] || WallID.Sets.Conversion.Sandstone[(int)wall]) && wall != 71)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 71);
                    }
                    else if ((WallID.Sets.Conversion.HardenedSand[(int)wall] || WallID.Sets.Conversion.Dirt[(int)wall] || WallID.Sets.Conversion.Snow[(int)wall]) && wall != 40)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 40);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 9);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Grass[(int)type] || TileID.Sets.Conversion.Sand[(int)type] || TileID.Sets.Conversion.HardenedSand[(int)type] || TileID.Sets.Conversion.Snow[(int)type] || TileID.Sets.Conversion.Dirt[(int)type]) && type != 147)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 147);
                        return;
                    }
                    if ((Main.tileMoss[(int)type] || TileID.Sets.Conversion.Stone[(int)type] || TileID.Sets.Conversion.Ice[(int)type] || TileID.Sets.Conversion.Sandstone[(int)type]) && type != 161)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 161);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 69)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 7)
            {
                if (walls)
                {
                    bool flag = wall == 61 || wall == 185 || wall == 262 || wall == 274;
                    if ((WallID.Sets.Conversion.Stone[(int)wall] || WallID.Sets.Conversion.Ice[(int)wall] || WallID.Sets.Conversion.Sandstone[(int)wall]) && wall != 349 && !flag)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 349);
                    }
                    else if (wall == 262)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 61);
                    }
                    else if (wall == 274)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 185);
                    }
                    else if ((WallID.Sets.Conversion.HardenedSand[(int)wall] || WallID.Sets.Conversion.Snow[(int)wall] || WallID.Sets.Conversion.Dirt[(int)wall]) && wall != 2)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 2);
                    }
                    else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 212)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 212);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 213)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 213);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 214)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 214);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 215)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 215);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 0);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Stone[(int)type] || TileID.Sets.Conversion.Ice[(int)type] || TileID.Sets.Conversion.Sandstone[(int)type]) && type != 1)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 1);
                        return;
                    }
                    if (TileID.Sets.Conversion.GolfGrass[(int)type] && type != 477)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 477);
                        return;
                    }
                    if (TileID.Sets.Conversion.Grass[(int)type] && type != 2 && type != 477)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 2);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Sand[(int)type] || TileID.Sets.Conversion.HardenedSand[(int)type] || TileID.Sets.Conversion.Snow[(int)type] || TileID.Sets.Conversion.Dirt[(int)type]) && type != 0)
                    {
                        int num2 = 0;
                        if (WorldGen.TileIsExposedToAir(i2, j2))
{
                            num2 = 2;
                        }
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, num2);
                        return;
                    }
                    if (tiles && TileID.Sets.Conversion.Thorn[(int)type] && type != 69)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 0)
            {
                if (walls)
                {
                    if (tile.wall == 69 || tile.wall == 70 || tile.wall == 81)
                    {
                        ushort num3 = 64;
                        if ((double)j2 < Main.worldSurface)
{
                            if (WorldGen.genRand.Next(10) == 0)
{
                                num3 = 65;
                            }
                            else
{
                                num3 = 63;
                            }
                        }
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, (int)num3);
                    }
                    else if (wall != 61 && wall != 185 && wall != 204 && wall != 205 && wall != 206 && wall != 207)
                    {
                        if (wall == 262)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 61);
                        }
                        else if (wall == 274)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 185);
                        }
                        else if (wall == 292)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 204);
                        }
                        else if (wall == 293)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 205);
                        }
                        else if (wall == 294)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 206);
                        }
                        else if (wall == 295)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 207);
                        }
                        else if (WallID.Sets.Conversion.Stone[(int)wall] && wall != 349)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 349);
                        }
                        else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 212)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 212);
                        }
                        else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 213)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 213);
                        }
                        else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 214)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 214);
                        }
                        else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 215)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 215);
                        }
                        else if (tile.wall == 80)
{
                            if ((double)j2 < Main.worldSurface + 4.0 + (double)WorldGen.genRand.Next(3) || (double)j2 > ((double)Main.maxTilesY + Main.rockLayer) / 2.0 - 3.0 + (double)WorldGen.genRand.Next(3))
{
                                WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 15);
                            }
                            else
{
                                WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 64);
                            }
                        }
                        else if (WallID.Sets.Conversion.HardenedSand[(int)wall] && wall != 216)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 216);
                        }
                        else if (WallID.Sets.Conversion.Sandstone[(int)wall] && wall != 187)
{
                            WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 187);
                        }
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 0);
                        return;
                    }
                    if (tile.type == 492)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 477);
                        return;
                    }
                    if (TileID.Sets.Conversion.JungleGrass[(int)type] && type != 60)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 60);
                        return;
                    }
                    if (TileID.Sets.Conversion.Grass[(int)type] && type != 2 && type != 477)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 2);
                        return;
                    }
                    if (TileID.Sets.Conversion.Stone[(int)type] && type != 1)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 1);
                        return;
                    }
                    if (TileID.Sets.Conversion.Sand[(int)type] && type != 53)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 53);
                        return;
                    }
                    if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 397)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 397);
                        return;
                    }
                    if (TileID.Sets.Conversion.Sandstone[(int)type] && type != 396)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 396);
                        return;
                    }
                    if (TileID.Sets.Conversion.Ice[(int)type] && type != 161)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 161);
                        return;
                    }
                    if (TileID.Sets.Conversion.MushroomGrass[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 60);
                        return;
                    }
                    if (tile.type == 32 || Main.tile[i2, j2].type == 352)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 8)
            {
                if (tiles && (type == 59 || type == 60))
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 211);
                    return;
                }
            }
            else if (conversionType == 9)
            {
                if (tiles)
                {
                    if (type == 23 || type == 199 || type == 661 || type == 662 || type == 2 || type == 477 || type == 109 || type == 492)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 60);
                        return;
                    }
                    if (type == 0)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 59);
                        return;
                    }
                    if (type == 25 || type == 203)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 1);
                        return;
                    }
                    if (type == 112 || type == 234)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 53);
                        return;
                    }
                    if (type == 398 || type == 399)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 397);
                        return;
                    }
                    if (type == 400 || type == 401)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 396);
                        return;
                    }
                    if (type == 24 || type == 201 || type == 32 || type == 352 || type == 636 || type == 205)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 10)
            {
                if (tiles)
                {
                    if (type == 23 || type == 199 || type == 661 || type == 662)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 60);
                        return;
                    }
                    if (type == 25 || type == 203)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 1);
                        return;
                    }
                    if (type == 112 || type == 234)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 53);
                        return;
                    }
                    if (type == 398 || type == 399)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 397);
                        return;
                    }
                    if (type == 400 || type == 401)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 396);
                        return;
                    }
                    if (type == 24 || type == 201 || type == 32 || type == 352 || type == 636 || type == 205)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                }
            }
            else if (conversionType == 11)
            {
                if (walls)
                {
                    bool flag2 = wall == 61 || wall == 185 || wall == 262 || wall == 274;
                    if (WallID.Sets.Conversion.Stone[(int)wall] && wall != 349 && !flag2)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 349);
                    }
                    else if (wall == 69 || wall == 70 || wall == 81)
                    {
                        ushort num4 = 64;
                        if ((double)j2 < Main.worldSurface)
{
                            if (WorldGen.genRand.Next(10) == 0)
{
                                num4 = 65;
                            }
                            else
{
                                num4 = 63;
                            }
                        }
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, (int)num4);
                    }
                    else if (wall == 262)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 61);
                    }
                    else if (wall == 274)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 185);
                    }
                    else if (WallID.Sets.Conversion.Dirt[(int)wall] && wall != 2)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 2);
                    }
                    else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 212)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 212);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 213)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 213);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 214)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 214);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 215)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 215);
                    }
                    else if (WallID.Sets.Conversion.HardenedSand[(int)wall] && wall != 216)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 216);
                    }
                    else if (WallID.Sets.Conversion.Sandstone[(int)wall] && wall != 187)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 187);
                    }
                }
                if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                {
                    WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 0);
                    return;
                }
                if (TileID.Sets.Conversion.JungleGrass[(int)type] && type != 60)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 60);
                    return;
                }
                if (TileID.Sets.Conversion.GolfGrass[(int)type] && type != 477)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 477);
                    return;
                }
                if (TileID.Sets.Conversion.Grass[(int)type] && type != 2 && type != 477)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 2);
                    return;
                }
                if (TileID.Sets.Conversion.Stone[(int)type] && type != 1)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 1);
                    return;
                }
                if (TileID.Sets.Ices[(int)type] && type != 161)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 161);
                    return;
                }
                if (TileID.Sets.Conversion.Sand[(int)type] && type != 53)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 53);
                    return;
                }
                if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 397)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 397);
                    return;
                }
                if (TileID.Sets.Conversion.Sandstone[(int)type] && type != 396)
                {
                    WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 396);
                    return;
                }
            }
            else if (conversionType == 12)
            {
                if (walls)
                {
                    if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 188)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 188);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 189)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 189);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 190)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 190);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 191)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 191);
                    }
                    else if (wall != 0 && wall != 3)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 3);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 18);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 32)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 32);
                        return;
                    }
                    if (type != 25 && !Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 25);
                        return;
                    }
                }
            }
            else if (conversionType == 13)
            {
                if (walls)
                {
                    if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 192)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 192);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 193)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 193);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 194)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 194);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 195)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 195);
                    }
                    else if (wall != 0 && wall != 83)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 83);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 19);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 352)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 352);
                        return;
                    }
                    if (type != 203 && !Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 203);
                        return;
                    }
                }
            }
            else if (conversionType == 14)
            {
                if (walls)
                {
                    if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 200)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 200);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 201)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 201);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 202)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 202);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 203)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 203);
                    }
                    else if (wall != 0 && wall != 28)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 28);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 20);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                    else if (type != 117 && !Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 117);
                        return;
                    }
                }
            }
            else if (conversionType == 15)
            {
                if (walls)
                {
                    WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 80);
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 22);
                    }
                    else if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                        }
                    }
                    if (!Main.tileFrameImportant[(int)type])
                    {
                        if (WorldGen.TileIsExposedToAir(i2, j2))
{
                            WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 70);
                            return;
                        }
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 59);
                        return;
                    }
                }
            }
            else if (conversionType == 16)
            {
                if (walls)
                {
                    if ((WallID.Sets.Conversion.HardenedSand[(int)wall] || WallID.Sets.Conversion.Dirt[(int)wall] || WallID.Sets.Conversion.Snow[(int)wall]) && wall != 216)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 216);
                    }
                    else if (wall != 187)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 187);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 16);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Grass[(int)type] || TileID.Sets.Conversion.Sand[(int)type] || TileID.Sets.Conversion.Snow[(int)type] || TileID.Sets.Conversion.Dirt[(int)type]) && type != 53)
                    {
                        int num5 = 53;
                        if (WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(i2, j2))
{
                            num5 = 397;
                        }
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, num5);
                        return;
                    }
                    if (TileID.Sets.Conversion.HardenedSand[(int)type] && type != 397)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 397);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 69)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                    else if (type != 396 && !Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 396);
                        return;
                    }
                }
            }
            else if (conversionType == 17)
            {
                if (walls)
                {
                    if ((WallID.Sets.Conversion.Stone[(int)wall] || WallID.Sets.Conversion.NewWall1[(int)wall] || WallID.Sets.Conversion.NewWall2[(int)wall] || WallID.Sets.Conversion.NewWall3[(int)wall] || WallID.Sets.Conversion.NewWall4[(int)wall] || WallID.Sets.Conversion.Ice[(int)wall] || WallID.Sets.Conversion.Sandstone[(int)wall]) && wall != 71)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 71);
                    }
                    else if (wall != 40)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 40);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 9);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Grass[(int)type] || TileID.Sets.Conversion.Sand[(int)type] || TileID.Sets.Conversion.HardenedSand[(int)type] || TileID.Sets.Conversion.Snow[(int)type] || TileID.Sets.Conversion.Dirt[(int)type]) && type != 147)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 147);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type] && type != 69)
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                    else if (type != 161 && !Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 161);
                        return;
                    }
                }
            }
            else if (conversionType == 18)
            {
                if (walls)
                {
                    if ((WallID.Sets.Conversion.HardenedSand[(int)wall] || WallID.Sets.Conversion.Snow[(int)wall] || WallID.Sets.Conversion.Dirt[(int)wall]) && wall != 2)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 2);
                    }
                    else if (WallID.Sets.Conversion.NewWall1[(int)wall] && wall != 212)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 212);
                    }
                    else if (WallID.Sets.Conversion.NewWall2[(int)wall] && wall != 213)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 213);
                    }
                    else if (WallID.Sets.Conversion.NewWall3[(int)wall] && wall != 214)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 214);
                    }
                    else if (WallID.Sets.Conversion.NewWall4[(int)wall] && wall != 215)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 215);
                    }
                    else if (wall != 349)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 349);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 0);
                        return;
                    }
                    if (TileID.Sets.Conversion.GolfGrass[(int)type] && type != 477)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 477);
                        return;
                    }
                    if (TileID.Sets.Conversion.Grass[(int)type] && type != 2 && type != 477)
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 2);
                        return;
                    }
                    if ((TileID.Sets.Conversion.Sand[(int)type] || TileID.Sets.Conversion.HardenedSand[(int)type] || TileID.Sets.Conversion.Snow[(int)type] || TileID.Sets.Conversion.Dirt[(int)type]) && type != 0)
                    {
                        int num6 = 0;
                        if (WorldGen.TileIsExposedToAir(i2, j2))
{
                            num6 = 2;
                        }
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, num6);
                        return;
                    }
                    if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                            return;
                        }
                    }
                    else if (type != 1 && !Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 1);
                        return;
                    }
                }
            }
            else if (conversionType == 19)
            {
                if (walls && wall > 0)
                {
                    if (wall == 63 || wall == 69 || wall == 81 || wall == 70)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 64);
                    }
                    else if (wall != 15)
                    {
                        WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 15);
                    }
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 21);
                    }
                    else if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 69);
                    }
                    if (!Main.tileFrameImportant[(int)type])
                    {
                        if (WorldGen.TileIsExposedToAir(i2, j2))
{
                            WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 60);
                            return;
                        }
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 59);
                        return;
                    }
                }
            }
            else if (conversionType == 20)
            {
                if (walls)
                {
                    WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, 87);
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 21);
                    }
                    else if (type != 69 && TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 69);
                    }
                    if (!Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, 226);
                        return;
                    }
                }
            }
            else if (conversionType == 21)
            {
                DungeonGenVars currentDungeonGenVars = GenVars.CurrentDungeonGenVars;
                ushort num7 = ((currentDungeonGenVars == null) ? 41 : currentDungeonGenVars.brickTileType);
                ushort num8 = ((currentDungeonGenVars == null) ? 17 : currentDungeonGenVars.brickWallType);
                if (walls)
                {
                    WorldGen.Convert_ActuallyConvertWall(conversionType, i2, j2, ref tile, (int)num8);
                }
                if (tiles)
                {
                    if (type == 4 && TileID.Sets.Conversion.Torch(tile, conversionType))
                    {
                        WorldGen.Convert_ActuallyConvertTorch(conversionType, i2, j2, ref tile, 21);
                    }
                    else if (TileID.Sets.Conversion.Thorn[(int)type])
                    {
                        WorldGen.KillTile(i2, j2, false, false, false);
                        if (Main.netMode != 0)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i2, (float)j2, 0f, 0, 0, 0);
                        }
                    }
                    if (!Main.tileFrameImportant[(int)type])
                    {
                        WorldGen.Convert_ActuallyConvertTile(conversionType, i2, j2, ref tile, (int)num7);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.brickTileType, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.brickWallType, Terraria.ID.WallID.Sets.CanBeConvertedToGlowingMushroom, Terraria.WorldGen.Convert_ActuallyConvertTile(), Terraria.WorldGen.Convert_ActuallyConvertTorch(), Terraria.WorldGen.Convert_ActuallyConvertWall(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.ID.TileID.Sets.Conversion.Dirt, Terraria.ID.WallID.Sets.Conversion.Dirt, Terraria.WorldGen.genRand, Terraria.ID.TileID.Sets.Conversion.GolfGrass, Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.ID.WallID.Sets.Conversion.Grass, Terraria.ID.TileID.Sets.Conversion.HardenedSand, Terraria.ID.WallID.Sets.Conversion.HardenedSand, Terraria.ID.TileID.Sets.Conversion.Ice, Terraria.ID.WallID.Sets.Conversion.Ice, Terraria.ID.TileID.Sets.Ices, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.Conversion.JungleGrass, Terraria.WorldGen.KillTile(), Terraria.Main.maxTilesY, Terraria.ID.TileID.Sets.Conversion.MushroomGrass, Terraria.Main.netMode, Terraria.ID.WallID.Sets.Conversion.NewWall1, Terraria.ID.WallID.Sets.Conversion.NewWall2, Terraria.ID.WallID.Sets.Conversion.NewWall3, Terraria.ID.WallID.Sets.Conversion.NewWall4, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rockLayer, Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.ID.TileID.Sets.Conversion.Sandstone, Terraria.ID.WallID.Sets.Conversion.Sandstone, Terraria.NetMessage.SendData(), Terraria.ID.TileID.Sets.Conversion.Snow, Terraria.ID.WallID.Sets.Conversion.Snow, Terraria.ID.TileID.Sets.Conversion.Stone, Terraria.ID.WallID.Sets.Conversion.Stone, Terraria.ID.TileID.Sets.Conversion.Thorn, Terraria.Main.tile, Terraria.Main.tileFrameImportant, Terraria.WorldGen.TileIsExposedToAir(), Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.Conversion.Torch(), Terraria.Tile.type, Terraria.Tile.wall, and Terraria.Main.worldSurface.