Terraria Decompiled: Terraria.WorldGen.Check1x2
Check1x2()
static void Terraria.WorldGen.Check1x2 (int x, int j, ushort type) inline static
Definition at line 41606 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int num = j;
            bool flag = true;
            if (Main.tile[x, num] == null)
            {
                Main.tile[x, num] = new Tile();
            }
            if (Main.tile[x, num + 1] == null)
            {
                Main.tile[x, num + 1] = new Tile();
            }
            short num2 = Main.tile[x, num].frameY;
            int num3 = 0;
            while (num2 >= 40)
            {
                num2 -= 40;
                num3++;
            }
            if (num2 == 18)
            {
                num--;
            }
            if (Main.tile[x, num] == null)
            {
                Main.tile[x, num] = new Tile();
            }
            int num4 = (int)(Main.tile[x, num].frameX / 18);
            if (Main.tile[x, num].frameX == -1)
            {
                num4 = (int)(Main.tile[x, num + 1].frameX / 18);
            }
            if ((int)Main.tile[x, num].frameY == 40 * num3 && (int)Main.tile[x, num + 1].frameY == 40 * num3 + 18 && Main.tile[x, num].type == type && Main.tile[x, num + 1].type == type)
            {
                flag = false;
            }
            if (Main.tile[x, num + 2] == null)
            {
                Main.tile[x, num + 2] = new Tile();
            }
            if (!WorldGen.SolidTileAllowBottomSlope(x, num + 2) && !TileID.Sets.Platforms[(int)Main.tile[x, num + 2].type])
            {
                flag = true;
            }
            if (Main.tile[x, num].type == 20)
            {
                int num5 = (int)(Main.tile[x, num].frameX / 54);
                ushort type2 = Main.tile[x, num + 2].type;
                int num6 = -1;
                if (type2 == 2 || type2 == 477)
                {
                    num6 = 0;
                }
                else if (type2 == 147)
                {
                    num6 = 1;
                }
                else if (type2 == 60)
                {
                    num6 = 2;
                }
                else if (type2 == 23 || type2 == 661)
                {
                    num6 = 3;
                }
                else if (type2 == 199 || type2 == 662)
                {
                    num6 = 4;
                }
                else if (type2 == 109 || type2 == 492)
                {
                    num6 = 5;
                }
                else if (type2 == 53)
                {
                    num6 = 6;
                }
                else if (type2 == 116)
                {
                    num6 = 7;
                }
                else if (type2 == 234)
                {
                    num6 = 8;
                }
                else if (type2 == 112)
                {
                    num6 = 9;
                }
                else if (type2 == 633)
                {
                    num6 = 10;
                }
                else
                {
                    flag = true;
                }
                if (!flag && num5 != num6)
                {
                    int num7 = 54 * num6;
                    num7 += WorldGen.genRand.Next(3) * 18;
                    Main.tile[x, num].frameX = (short)num7;
                    Main.tile[x, num + 1].frameX = (short)num7;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                if (Main.tile[x, num].type == type)
                {
                    WorldGen.KillTile(x, num, false, false, false);
                }
                if (Main.tile[x, num + 1].type == type)
                {
                    WorldGen.KillTile(x, num + 1, false, false, false);
                }
                if (type == 216)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 970 + num3, 1, false, 0, false);
                }
                if (type == 338)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, 2738, 1, false, 0, false);
                }
                if (type == 390)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 16, 32, 3253, 1, false, 0, false);
                }
                if (type == 493)
                {
                    int num8 = 0;
                    switch (num4)
                    {
                    case 0:
                        num8 = 4083;
                        break;
                    case 1:
                        num8 = 4084;
                        break;
                    case 2:
                        num8 = 4085;
                        break;
                    case 3:
                        num8 = 4086;
                        break;
                    case 4:
                        num8 = 4087;
                        break;
                    case 5:
                        num8 = 4088;
                        break;
                    }
                    if (num8 > 0)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, num8, 1, false, 0, false);
                    }
                }
                if (type == 15)
                {
                    int itemDrop_Chair = WorldGen.GetItemDrop_Chair(num3);
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, itemDrop_Chair, 1, false, 0, false);
                }
                if (type == 497)
                {
                    int itemDrop_Toilet = WorldGen.GetItemDrop_Toilet(num3);
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num), x * 16, num * 16, 32, 32, itemDrop_Toilet, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.GetItemDrop_Chair(), Terraria.WorldGen.GetItemDrop_Toilet(), Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().