Terraria Decompiled: Terraria.WorldGen.AddTrees
AddTrees()
static void Terraria.WorldGen.AddTrees (bool undergroundOnly = false) inline static
Definition at line 28671 of file WorldGen.cs.
        {
            double num = 0.1 + WorldGen.genRand.NextDouble() * 0.35;
            double num2 = 0.1 + WorldGen.genRand.NextDouble() * 0.35;
            int num3 = 20;
            int num4 = (int)Main.worldSurface;
            if (!undergroundOnly)
            {
                for (int i = 1; i < Main.maxTilesX - 1; i++)
                {
                    for (int j = num3; j < num4; j++)
                    {
                        if (i < 380)
{
                            if (WorldGen.genRand.NextDouble() < num && Main.tile[i, j].liquid == 0)
{
                                WorldGen.TryGrowingTreeByType(323, i, j, 0, false);
                            }
                        }
                        else if (i > Main.maxTilesX - 380 && WorldGen.genRand.NextDouble() < num2 && Main.tile[i, j].liquid == 0)
{
                            WorldGen.TryGrowingTreeByType(323, i, j, 0, false);
                        }
                        int num5 = 20;
                        if (WorldGen.drunkWorldGen)
{
                            num5 /= 3;
                        }
                        if (WorldGen.remixWorldGen)
{
                            num5 /= 2;
                        }
                        if (Main.tile[i, j].active() && Main.tile[i, j].type == 2 && (Main.tenthAnniversaryWorld || WorldGen.genRand.Next(num5) == 0))
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.TryGrowingTreeByType(616, i, j, 0, false);
                            }
                            else
{
                                WorldGen.TryGrowingTreeByType(596, i, j, 0, false);
                            }
                        }
                        else
{
                            WorldGen.TryGrowingTreeByType(5, i, j, 0, false);
                        }
                    }
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        i++;
                    }
                    if (WorldGen.genRand.Next(4) == 0)
                    {
                        i++;
                    }
                }
            }
            if (WorldGen.remixWorldGen)
            {
                num3 = (int)Main.worldSurface;
                num4 = Main.maxTilesY - 300;
                for (int k = 1; k < Main.maxTilesX - 1; k++)
                {
                    for (int l = num3; l < num4; l++)
                    {
                        int num6 = 7;
                        if (Main.tile[k, l].active() && Main.tile[k, l].type == 2 && (Main.tenthAnniversaryWorld || WorldGen.genRand.Next(num6) == 0))
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                WorldGen.TryGrowingTreeByType(616, k, l, 0, false);
                            }
                            else
{
                                WorldGen.TryGrowingTreeByType(596, k, l, 0, false);
                            }
                        }
                        else
{
                            WorldGen.TryGrowingTreeByType(5, k, l, 0, false);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.genRand, int, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.remixWorldGen, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.FinishRemixWorld().