Terraria Decompiled: Terraria.WorldGen.dropMeteor
dropMeteor()
static bool Terraria.WorldGen.dropMeteor (bool spawnUnderGround = false) inline static
Definition at line 2030 of file WorldGen.cs.
        {
            bool flag = true;
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                if (Main.netMode == 1)
                {
                    return false;
                }
                if (!Main.isThereAWorldSurface)
                {
                    return false;
                }
                for (int i = 0; i < 255; i++)
                {
                    if (Main.player[i].active)
                    {
                        flag = false;
                        break;
                    }
                }
            }
            else
            {
                flag = false;
            }
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                int num = 0;
                double num2 = (double)Main.maxTilesX / 4200.0;
                int num3 = (int)(400.0 * num2);
                for (int j = 5; j < Main.maxTilesX - 5; j++)
                {
                    int num4 = 5;
                    while ((double)num4 < Main.worldSurface)
                    {
                        if (Main.tile[j, num4].active() && Main.tile[j, num4].type == 37)
{
                            num++;
                            if (num > num3)
{
                                return false;
                            }
                        }
                        num4++;
                    }
                }
            }
            double num5 = 600.0;
            int num6 = 0;
            int num7 = (int)(Main.worldSurface * 0.3);
            if (spawnUnderGround)
            {
                num7 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.UnderworldLayer);
            }
            while (!flag)
            {
                double num8 = (double)Main.maxTilesX * 0.08;
                int num9 = Main.rand.Next(150, Main.maxTilesX - 150);
                while ((double)num9 > (double)Main.spawnTileX - num8 && (double)num9 < (double)Main.spawnTileX + num8)
                {
                    num9 = Main.rand.Next(150, Main.maxTilesX - 150);
                }
                for (int k = num7; k < Main.maxTilesY; k++)
                {
                    if (WorldGen.InWorld(num9, k, 2))
                    {
                        Tile tile = Main.tile[num9, k];
                        if (tile.active() && Main.tileSolid[(int)tile.type] && !TileID.Sets.Platforms[(int)tile.type])
{
                            int num10 = 0;
                            int num11 = 15;
                            for (int l = num9 - num11; l < num9 + num11; l++)
{
                                for (int m = k - num11; m < k + num11; m++)
{
                                    if (WorldGen.InWorld(l, m, 2))
{
                                        if (WorldGen.SolidTile(l, m, false))
{
                                            Tile tile2 = Main.tile[l, m];
                                            num10++;
                                            if ((tile2.type >= 0 && TileID.Sets.Clouds[(int)tile2.type]) || tile2.type == 202)
{
                                                num10 -= 100;
                                            }
                                        }
                                        else if (Main.tile[l, m].liquid > 0)
{
                                            num10--;
                                        }
                                    }
                                }
                            }
                            if ((double)num10 < num5)
{
                                num5 -= 0.5;
                                break;
                            }
                            flag = WorldGen.meteor(num9, k, false);
                            if (flag)
{
                                return flag;
                            }
                            break;
                        }
                    }
                }
                num6++;
                if (num5 < 100.0)
                {
                    return false;
                }
                if (num6 >= Main.maxTilesX * 5)
                {
                    return false;
                }
            }
            return false;
        }
References Terraria.Player.active, Terraria.Tile.active(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldGen.genRand, int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Main.isThereAWorldSurface, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.meteor(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Platforms, Terraria.Main.player, Terraria.Main.rand, Terraria.Main.rockLayer, Terraria.WorldGen.SolidTile(), Terraria.Main.spawnTileX, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.SecretSeed.DoNoSurface(), and Terraria.Main.HandleMeteorFall().