Terraria Decompiled: Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand
BlockBelowMakesSandConvertIntoHardenedSand()
static bool Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand (int i, int j) inline static
Definition at line 87444 of file WorldGen.cs.
        {
            bool flag = false;
            if (j >= Main.maxTilesY - 1)
            {
                return false;
            }
            Tile tile = Main.tile[i, j + 1];
            if (tile == null)
            {
                return false;
            }
            if (!tile.nactive())
            {
                flag = true;
            }
            else if (tile.type >= 0 && tile.type < TileID.Count && !Main.tileSolid[(int)tile.type])
            {
                flag = true;
            }
            return flag;
        }
References Terraria.ID.TileID.Count, Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.tile, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_SandySurface(), and Terraria.WorldGen.Convert().