Terraria Decompiled: Terraria.WorldGen.paintCoatWall
paintCoatWall()
static bool Terraria.WorldGen.paintCoatWall (int x, int y, byte paintCoatId, bool broadcast = false, bool coatingEffects = true) inline static
Definition at line 42477 of file WorldGen.cs.
        {
            Tile tile = Main.tile[x, y];
            if (tile == null || tile.wall == 0)
            {
                return false;
            }
            List<Color> list = WorldGen.coatingColors(tile, false);
            switch (paintCoatId)
            {
            case 0:
                if (!tile.fullbrightWall() && !tile.invisibleWall())
                {
                    return false;
                }
                tile.fullbrightWall(false);
                tile.invisibleWall(false);
                WorldGen.SquareWallFrame(x, y, false);
                break;
            case 1:
                if (tile.fullbrightWall())
                {
                    return false;
                }
                tile.fullbrightWall(true);
                break;
            case 2:
                if (tile.invisibleWall())
                {
                    return false;
                }
                tile.invisibleWall(true);
                WorldGen.SquareWallFrame(x, y, false);
                break;
            default:
                return false;
            }
            if (broadcast)
            {
                NetMessage.SendData(64, -1, -1, null, x, (float)y, (float)paintCoatId, 1f, 0, 0, 0);
            }
            if (coatingEffects)
            {
                WorldGen.paintCoatEffect(x, y, paintCoatId, list);
            }
            return true;
        }
References Terraria.WorldGen.coatingColors(), Terraria.Tile.fullbrightWall(), Terraria.Tile.invisibleWall(), System.list, Terraria.WorldGen.paintCoatEffect(), Terraria.NetMessage.SendData(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.Player.ApplyCoating(), Terraria.WorldGen.Convert_ActuallyConvertWall(), and Terraria.Player.PlaceThing_PaintScrapper_TryScrapping().