Terraria Decompiled: Terraria.WorldGen.digTunnel
digTunnel()
static Vector2D Terraria.WorldGen.digTunnel (double X, double Y, double xDir, double yDir, int Steps, int Size, bool Wet = false) inline static
Definition at line 79737 of file WorldGen.cs.
        {
            double num = X;
            double num2 = Y;
            try
            {
                double num3 = 0.0;
                double num4 = 0.0;
                double num5 = (double)Size;
                num = Utils.Clamp<double>(num, num5 + 1.0, (double)Main.maxTilesX - num5 - 1.0);
                num2 = Utils.Clamp<double>(num2, num5 + 1.0, (double)Main.maxTilesY - num5 - 1.0);
                for (int i = 0; i < Steps; i++)
                {
                    int num6 = (int)(num - num5);
                    while ((double)num6 <= num + num5)
                    {
                        int num7 = (int)(num2 - num5);
                        while ((double)num7 <= num2 + num5)
{
                            if (Math.Abs((double)num6 - num) + Math.Abs((double)num7 - num2) < num5 * (1.0 + (double)WorldGen.genRand.Next(-10, 11) * 0.005) && num6 >= 0 && num6 < Main.maxTilesX && num7 >= 0 && num7 < Main.maxTilesY)
{
                                Main.tile[num6, num7].active(false);
                                if (Wet)
{
                                    Main.tile[num6, num7].liquid = byte.MaxValue;
                                    Main.tile[num6, num7].liquidType(0);
                                }
                            }
                            num7++;
                        }
                        num6++;
                    }
                    num5 += (double)WorldGen.genRand.Next(-50, 51) * 0.03;
                    if (num5 < (double)Size * 0.6)
                    {
                        num5 = (double)Size * 0.6;
                    }
                    if (num5 > (double)(Size * 2))
                    {
                        num5 = (double)(Size * 2);
                    }
                    num3 += (double)WorldGen.genRand.Next(-20, 21) * 0.01;
                    num4 += (double)WorldGen.genRand.Next(-20, 21) * 0.01;
                    if (num3 < -1.0)
                    {
                        num3 = -1.0;
                    }
                    if (num3 > 1.0)
                    {
                        num3 = 1.0;
                    }
                    if (num4 < -1.0)
                    {
                        num4 = -1.0;
                    }
                    if (num4 > 1.0)
                    {
                        num4 = 1.0;
                    }
                    num += (xDir + num3) * 0.6;
                    num2 += (yDir + num4) * 0.6;
                }
            }
            catch
            {
            }
            return new Vector2D(num, num2);
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Utils.Clamp(), Terraria.WorldGen.genRand, int, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, System.X, and System.Y.
Referenced by Terraria.WorldGen.Caverer().