Terraria Decompiled: Terraria.WorldGen.SolidTile
SolidTile() [3/3]
static bool Terraria.WorldGen.SolidTile (Tile testTile) inline static
Definition at line 70290 of file WorldGen.cs.
        {
            try
            {
                if (testTile == null)
                {
                    return true;
                }
                if (testTile.nactive() && Main.tileSolid[(int)testTile.type] && !Main.tileSolidTop[(int)testTile.type] && !testTile.halfBrick() && testTile.slope() == 0)
                {
                    return true;
                }
            }
            catch
            {
            }
            return false;
        }
References Terraria.Tile.halfBrick(), Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddHellHouses(), Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.WorldGen.AddPasses(), Terraria.GameContent.Biomes.Desert.DesertHive.AddTileVariance(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Projectile.AI_001(), Terraria.NPC.AI_001_Slimes(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_005_EaterOfSouls(), Terraria.NPC.AI_007_TownEntities(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_111_DD2LightningBug(), Terraria.NPC.AI_112_FairyCritter(), Terraria.NPC.AI_114_Dragonflies(), Terraria.Projectile.AI_121_StardustDragon(), Terraria.NPC.AI_123_Deerclops_ShootRubbleUp(), Terraria.NPC.AI_123_Deerclops_TryMakingSpike_FindBestY(), Terraria.Projectile.AI_137_CanHit(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_144_DD2Pet(), Terraria.Projectile.AI_170_FairyGlowstick(), Terraria.WorldBuilding.Actions.SwapSolidTile.Apply(), Terraria.WorldGen.AttemptFossilShattering(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBanners.Banners(), Terraria.GameContent.Biomes.GraniteBiome.BuildMagmaMap(), Terraria.GameContent.Generation.TrackGenerator.CalculateStateForLocation(), Terraria.WorldGen.CanPlaceSink(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.NPC.checkDead(), Terraria.WorldGen.CheckDoorClosed(), Terraria.WorldGen.CheckDoorOpen(), Terraria.WorldGen.CheckDye(), Terraria.GameContent.Events.CultistRitual.CheckFloor(), Terraria.GameContent.Events.CultistRitual.CheckFloor2(), Terraria.Player.CheckIceBreak(), Terraria.WorldGen.CheckJunglePlant(), Terraria.WorldGen.CheckOasisPlant(), Terraria.GameContent.Events.CultistRitual.CheckRitual(), Terraria.WorldGen.CheckStalactite(), Terraria.WorldGen.CheckSunflower(), Terraria.NPC.Spawner.CheckToSpawnRockGolem(), Terraria.WorldGen.checkUnderground(), Terraria.GameContent.Biomes.GraniteBiome.CleanupTiles(), Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall(), Terraria.WorldGen.CrimStart(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_CanPutTeleporterHere(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoPooEverywhere(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesert(), Terraria.Main.DrawBlack(), Terraria.TileObject.DrawPreview(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileInWater(), Terraria.GameContent.Drawing.WallDrawing.DrawWalls(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.dropMeteor(), Terraria.Mount.EmitGolfCartWheelDust(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Below(), Terraria.GameContent.Drawing.TileDrawing.EmitLivingTreeLeaf_Sideways(), Terraria.GameContent.Drawing.TileDrawing.EmitTreeLeaves(), Terraria.Projectile.FindBlockCeiling(), Terraria.Projectile.FindBlockSurface(), Terraria.Cinematics.DSTFilm.FindFloorAt(), Terraria.Player.FindSharpTearsOpening(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.WorldGen.Spread.Gem(), Terraria.Projectile.GetAlpha(), Terraria.Projectile.GetFishingPondState(), Terraria.Projectile.GetFishingPondWidth(), Terraria.Player.GetSmartPlatformSlope(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.WorldGen.GetWaterDepth(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalGroundFurniture.GroundFurniture_ActuallyGenerateFurniture(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowPumpkin(), Terraria.WorldGen.GrowWeb(), Terraria.WorldGen.IslandHouse(), Terraria.Player.ItemCheck_CheckCanUse_Inner(), Terraria.Player.ItemCheck_ReleaseCritter(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.KillTile_MakeTileDust(), Terraria.GameContent.Drawing.TileDrawing.LavaLightA(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch(), Terraria.Liquid.LiquidCheck(), Terraria.Rain.MakeRain(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.MatureTheHerbPlants(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.Spread.Moss(), Terraria.Player.MowTheLawn(), Terraria.WorldGen.nextCount(), Terraria.WorldGen.nextDirtCount(), Terraria.WorldGen.OasisPlantWaterCheck(), Terraria.WorldGen.oceanCave(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.OrePatch(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.CorruptionPitBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.GameContent.Biomes.SpikePitBiome.Place(), Terraria.WorldGen.Place2x2Style(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceDye(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.WorldGen.PlaceJunglePlant(), Terraria.Cinematics.DD2Film.PlaceNPCOnGround(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlacePumpkin(), Terraria.GameContent.Biomes.MarbleBiome.PlaceSlab(), Terraria.Player.PlaceThing_Tiles_PlaceIt_KillGrassForSolids(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlaceUncheckedStalactite(), Terraria.WorldGen.PlaceXmasTree(), Terraria.WorldGen.PoundPlatform(), Terraria.Projectile.ReduceRemainingChumsInPool(), Terraria.WorldGen.Scan3By3(), Terraria.WorldGen.SeaOatWaterCheck(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.ShimmeratorNext(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.WorldGen.SolidTile(), Terraria.NPC.Spawner.SpawnAnNPC(), Terraria.Projectile.SpawnFakeFishInWater(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.NPC.SpawnOnPlayer(), Terraria.WorldGen.SpawnStormLightningNearPlayer(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.NPC.SpawnWOF(), Terraria.WorldGen.Spread.Spider(), Terraria.DelegateMethods.SpreadTest(), Terraria.DelegateMethods.SpreadTile(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalWallVariants.SpreadWallDungeon(), Terraria.GameContent.SmartCursorHelper.Step_Pigronata(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.WorldGen.StonePatch(), Terraria.Player.TrySpawnDigtoiseAt(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.Map.WorldMap.UnlockMapTilePretty(), Terraria.Gore.UpdateAmbientAirborneCloud(), Terraria.Gore.UpdateAmbientFloorCloud(), Terraria.Player.UpdateBlacklistedTilesForGrappling(), Terraria.Dust.UpdateDust(), Terraria.Mount.UpdateEffects(), Terraria.Gore.UpdateFogMachineCloud(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.Spread.Wall(), Terraria.WorldGen.Spread.Wall2(), Terraria.Player.WallClimbMovement(), and Terraria.Player.WallslideMovement().