Terraria Decompiled: Terraria.WorldGen.Check3x4
Check3x4()
static void Terraria.WorldGen.Check3x4 (int i, int j, int type) inline static
Definition at line 48555 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int num = 0;
            int num2 = 0;
            int k = (int)(Main.tile[i, j].frameX / 18);
            int l = (int)(Main.tile[i, j].frameY / 18);
            while (k >= 3)
            {
                num++;
                k -= 3;
            }
            while (l >= 4)
            {
                num2++;
                l -= 4;
            }
            int num3 = i - k;
            int num4 = j - l;
            for (int m = num3; m < num3 + 3; m++)
            {
                for (int n = num4; n < num4 + 4; n++)
                {
                    if (Main.tile[m, n] == null)
                    {
                        Main.tile[m, n] = new Tile();
                    }
                    if (!Main.tile[m, n].active() || (int)Main.tile[m, n].type != type || (int)Main.tile[m, n].frameX != num * 54 + (m - num3) * 18 || (int)Main.tile[m, n].frameY != num2 * 72 + (n - num4) * 18)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[m, num4 + 4] == null)
                {
                    Main.tile[m, num4 + 4] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(m, num4 + 4))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int num5 = num3; num5 < num3 + 3; num5++)
                {
                    for (int num6 = num4; num6 < num4 + 4; num6++)
                    {
                        if ((int)Main.tile[num5, num6].type == type && Main.tile[num5, num6].active())
{
                            WorldGen.KillTile(num5, num6, false, false, false);
                        }
                    }
                }
                if (type == 101)
                {
                    int itemDrop_Bookcases = WorldGen.GetItemDrop_Bookcases(num);
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, itemDrop_Bookcases, 1, false, 0, false);
                }
                else if (type == 102)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 355, 1, false, 0, false);
                }
                else if (type == 463)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 3813, 1, false, 0, false);
                }
                else if (type == 617)
                {
                    if (num == 27)
                    {
                        short num7 = 5110;
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, (int)num7, 1, false, 0, false);
                    }
                    else
                    {
                        int num8 = 4924 + num;
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, num8, 1, false, 0, false);
                    }
                }
                WorldGen.destroyObject = false;
                for (int num9 = num3 - 1; num9 < num3 + 4; num9++)
                {
                    for (int num10 = num4 - 1; num10 < num4 + 4; num10++)
                    {
                        WorldGen.TileFrame(num9, num10, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemDrop_Bookcases(), Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().