Terraria Decompiled: Terraria.WorldGen.templePather
templePather()
static Vector2D Terraria.WorldGen.templePather (Vector2D templePath, int destX, int destY) inline static
Definition at line 30801 of file WorldGen.cs.
        {
            int num = (int)templePath.X;
            int num2 = (int)templePath.Y;
            int num3 = WorldGen.genRand.Next(5, 20);
            int num4 = WorldGen.genRand.Next(2, 5);
            while (num3 > 0 && (num != destX || num2 != destY))
            {
                num3--;
                if (num > destX)
                {
                    num--;
                }
                if (num < destX)
                {
                    num++;
                }
                if (num2 > destY)
                {
                    num2--;
                }
                if (num2 < destY)
                {
                    num2++;
                }
                for (int i = num - num4; i < num + num4; i++)
                {
                    for (int j = num2 - num4; j < num2 + num4; j++)
                    {
                        Main.tile[i, j].active(false);
                        Main.tile[i, j].wall = 87;
                    }
                }
            }
            return new Vector2D((double)num, (double)num2);
        }
References Terraria.Tile.active(), Terraria.WorldGen.genRand, int, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.Tile.wall, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.makeTemple().