Terraria Decompiled: Terraria.WorldGen.ReplaceTile_DoActualReplacement
ReplaceTile_DoActualReplacement()
static void Terraria.WorldGen.ReplaceTile_DoActualReplacement (int targetType, int targetStyle, int topLeftX, int topLeftY, Tile t) inline static private
Definition at line 61545 of file WorldGen.cs.
        {
            if (TileID.Sets.BasicChest[targetType])
            {
                if (WorldGen.IsChestRigged(topLeftX, topLeftY) && Main.netMode != 1)
                {
                    Wiring.HitSwitch(topLeftX, topLeftY);
                    NetMessage.SendData(59, -1, -1, null, topLeftX, (float)topLeftY, 0f, 0f, 0, 0, 0);
                }
                WorldGen.ReplaceTile_DoActualReplacement_Area(targetType, targetStyle, topLeftX, topLeftY, 2, 2, 0, 0);
                return;
            }
            if (TileID.Sets.BasicDresser[targetType])
            {
                WorldGen.ReplaceTile_DoActualReplacement_Area(targetType, targetStyle, topLeftX, topLeftY, 3, 2, 0, 0);
                return;
            }
            if (TileID.Sets.Campfires[targetType])
            {
                bool flag = t.frameY >= 36;
                WorldGen.ReplaceTile_DoActualReplacement_Area(targetType, targetStyle, topLeftX, topLeftY, 3, 2, 0, flag ? 36 : 0);
                return;
            }
            WorldGen.ReplaceTile_DoActualReplacement_Single(targetType, targetStyle, topLeftX, topLeftY, t);
        }
References Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Sets.BasicDresser, Terraria.ID.TileID.Sets.Campfires, Terraria.Wiring.HitSwitch(), Terraria.WorldGen.IsChestRigged(), Terraria.Main.netMode, Terraria.WorldGen.ReplaceTile_DoActualReplacement_Area(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), and Terraria.NetMessage.SendData().
Referenced by Terraria.WorldGen.ReplaceTile().