Terraria Decompiled: Terraria.WorldGen.CheckSunflower
CheckSunflower()
static void Terraria.WorldGen.CheckSunflower (int i, int j, int type = 27) inline static
Definition at line 52229 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int k = 0;
            k += (int)(Main.tile[i, j].frameX / 18);
            int num = j + (int)(Main.tile[i, j].frameY / 18 * -1);
            while (k > 1)
            {
                k -= 2;
            }
            k *= -1;
            k += i;
            for (int l = k; l < k + 2; l++)
            {
                for (int m = num; m < num + 4; m++)
                {
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    int n;
                    for (n = (int)(Main.tile[l, m].frameX / 18); n > 1; n -= 2)
                    {
                    }
                    if (!Main.tile[l, m].nactive() || (int)Main.tile[l, m].type != type || n != l - k || (int)Main.tile[l, m].frameY != (m - num) * 18)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[l, num + 4] == null)
                {
                    Main.tile[l, num + 4] = new Tile();
                }
                if (!Main.tile[l, num + 4].nactive() || (Main.tile[l, num + 4].type != 2 && Main.tile[l, num + 4].type != 477 && Main.tile[l, num + 4].type != 492 && Main.tile[l, num + 4].type != 109 && Main.tile[l, num + 4].type != 60 && Main.tile[l, num + 4].type != 633))
                {
                    flag = true;
                }
                if (!WorldGen.SolidTile(l, num + 4, false))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int num2 = k; num2 < k + 2; num2++)
                {
                    for (int num3 = num; num3 < num + 4; num3++)
                    {
                        if ((int)Main.tile[num2, num3].type == type && Main.tile[num2, num3].active())
{
                            WorldGen.KillTile(num2, num3, false, false, false);
                        }
                    }
                }
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, 63, 1, false, 0, false);
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Item.NewItem(), Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().