Terraria Decompiled: Terraria.WorldGen.ShimmerRemoveWater
ShimmerRemoveWater()
static void Terraria.WorldGen.ShimmerRemoveWater () inline static
Definition at line 32163 of file WorldGen.cs.
        {
            if (!WorldGen.generatingWorld)
            {
                return;
            }
            int num = 150;
            int num2 = (int)GenVars.shimmerPosition.X - num;
            int num3 = (int)GenVars.shimmerPosition.X + num;
            int num4 = (int)GenVars.shimmerPosition.Y - num;
            int num5 = (int)GenVars.shimmerPosition.Y + num / 2;
            for (int i = num4; i <= num5; i++)
            {
                for (int j = num2; j <= num3; j++)
                {
                    if (WorldGen.InWorld(j, i, 0) && (int)Math.Sqrt(Math.Pow((double)Math.Abs(j - (int)GenVars.shimmerPosition.X), 2.0) + Math.Pow((double)Math.Abs(i - (int)GenVars.shimmerPosition.Y), 2.0)) < num)
                    {
                        if (!Main.tile[j, i].shimmer())
{
                            Main.tile[j, i].liquid = 0;
                        }
                        if (Main.tile[j, i].type == 162)
{
                            Main.tile[j, i].active(false);
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.generatingWorld, int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, System.Math.Pow(), Terraria.Tile.shimmer(), Terraria.WorldBuilding.GenVars.shimmerPosition, System.Math.Sqrt(), Terraria.Main.tile, Terraria.Tile.type, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.Liquid.QuickWater(), and Terraria.WorldGen.ShimmerCleanUp().