Terraria Decompiled: Terraria.WorldGen.UpdateWorld_OvergroundTile
UpdateWorld_OvergroundTile()
static void Terraria.WorldGen.UpdateWorld_OvergroundTile (int i, int j, int wallDist) inline static private
Definition at line 72421 of file WorldGen.cs.
        {
            int num = i - 1;
            int num2 = i + 2;
            int num3 = j - 1;
            int num4 = j + 2;
            if (num < 10)
            {
                num = 10;
            }
            if (num2 > Main.maxTilesX - 10)
            {
                num2 = Main.maxTilesX - 10;
            }
            if (num3 < 10)
            {
                num3 = 10;
            }
            if (num4 > Main.maxTilesY - 10)
            {
                num4 = Main.maxTilesY - 10;
            }
            if (Main.tile[i, j] == null)
            {
                return;
            }
            if (Main.tile[i, j].type == 655 && !NPC.AnyNPCs(262))
            {
                WorldGen.KillTile(i, j, false, false, false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                }
            }
            if (Main.tile[i, j].type == 85)
            {
                WorldGen.TryGrowingAbigailsFlower(i, j);
            }
            else if (Main.tileAlch[(int)Main.tile[i, j].type])
            {
                WorldGen.GrowAlch(i, j);
            }
            else if ((double)j < Main.worldSurface + 10.0 && (i < WorldGen.beachDistance || i > Main.maxTilesX - WorldGen.beachDistance) && !Main.tile[i, j].active())
            {
                int num5 = 3000;
                num5 -= (int)(Math.Abs(Main.windSpeedCurrent) * 1250f);
                if (Main.raining)
                {
                    num5 -= (int)(1250f * Main.maxRaining);
                }
                if (num5 < 300)
                {
                    num5 = 300;
                }
                if (WorldGen.genRand.Next(num5) == 0)
                {
                    int num6 = j;
                    while ((double)num6 < Main.worldSurface + 10.0 && !Main.tile[i, num6].active() && num6 - j < 15)
                    {
                        num6++;
                    }
                    if (Main.tile[i, num6].active() && Main.tile[i, num6].type == 53 && WorldGen.SolidTileAllowBottomSlope(i, num6))
                    {
                        Tile tile = Main.tile[i, num6];
                        num6--;
                        if (Main.tile[i, num6].active() && Main.tile[i, num6].type == 324)
{
                            return;
                        }
                        int num7 = WorldGen.genRand.Next(2, 5);
                        int num8 = WorldGen.genRand.Next(8, 11);
                        int num9 = 0;
                        for (int k = i - num8; k <= i + num8; k++)
{
                            for (int l = num6 - num8; l <= num6 + num8; l++)
{
                                if (Main.tile[k, l].active() && (Main.tile[k, l].type == 324 || Main.tile[k, l].type == 81))
{
                                    num9++;
                                }
                            }
                        }
                        if (num9 < num7)
{
                            if (WorldGen.genRand.Next(2) == 0 && Main.tile[i, num6].liquid >= 230)
{
                                WorldGen.PlaceTile(i, num6, 81, true, false, -1, 0);
                                if (Main.tile[i, num6].active())
{
                                    if (Main.tile[i, num6].type == 81)
{
                                        Main.tile[i, num6].CopyPaintAndCoating(tile);
                                    }
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, i, num6, TileChangeType.None);
                                    }
                                }
                            }
                            else
{
                                WorldGen.PlaceTile(i, num6, 324, true, false, -1, WorldGen.RollRandomSeaShellStyle());
                                if (Main.tile[i, num6].active())
{
                                    if (Main.tile[i, num6].type == 324)
{
                                        Main.tile[i, num6].CopyPaintAndCoating(tile);
                                    }
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, i, num6, TileChangeType.None);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            if ((Main.tile[i, j].type == 596 || Main.tile[i, j].type == 616 || Main.tile[i, j].type == 595 || Main.tile[i, j].type == 615) && (Main.tile[i, j + 1].type == 199 || Main.tile[i, j + 1].type == 23))
            {
                WorldGen.KillTile(i, j, false, false, false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                }
            }
            if ((Main.tile[i, j].type == 571 || (Main.tile[i, j].type == 60 && Main.tile[i, j - 1].liquid > 0)) && WorldGen.genRand.Next(5) == 0 && (!Main.tile[i, j - 1].active() || Main.tile[i, j - 1].type == 61 || Main.tile[i, j - 1].type == 74 || Main.tile[i, j - 1].type == 518) && (Main.tile[i, j].type != 60 || WorldGen.genRand.Next(30) == 0) && WorldGen.PlaceBamboo(i, j - 1))
            {
                NetMessage.SendTileSquare(-1, i, j - 1, 1, 2, TileChangeType.None);
            }
            if (Main.tile[i, j].type == 518)
            {
                if (Main.tile[i, j].liquid == 0 || (Main.tile[i, j].liquid / 16 >= 9 && WorldGen.SolidTile(i, j - 1, false)) || (Main.tile[i, j - 1].liquid > 0 && Main.tile[i, j - 1].active()))
                {
                    WorldGen.KillTile(i, j, false, false, false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                    }
                }
                else
                {
                    WorldGen.CheckLilyPad(i, j);
                }
            }
            else if (Main.tile[i, j].type == 519)
            {
                WorldGen.CheckCatTail(i, j);
                if (Main.tile[i, j].active() && WorldGen.genRand.Next(8) == 0)
                {
                    WorldGen.GrowCatTail(i, j);
                    WorldGen.CheckCatTail(i, j);
                }
            }
            else if (Main.tile[i, j].liquid > 32)
            {
                if (Main.tile[i, j].active())
                {
                    if (TileID.Sets.SlowlyDiesInWater[(int)Main.tile[i, j].type])
                    {
                        WorldGen.KillTile(i, j, false, false, false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                        }
                    }
                    else if (Main.tile[i, j].type == 60 || Main.tile[i, j].type == 226)
                    {
                        WorldGen.UpdateWorld_GrassGrowth(i, j, num, num2, num3, num4, false);
                    }
                }
                else if (WorldGen.genRand.Next(600) == 0)
                {
                    WorldGen.PlaceTile(i, j, 518, true, false, -1, 0);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                    }
                }
                else if (WorldGen.genRand.Next(600) == 0)
                {
                    WorldGen.PlaceTile(i, j, 519, true, false, -1, 0);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                    }
                }
            }
            else if (Main.tile[i, j].nactive())
            {
                WorldGen.hardUpdateWorld(i, j);
                if (Main.rand.Next(3000) == 0)
                {
                    WorldGen.plantDye(i, j, false);
                }
                else if (Main.hardMode && ((double)i < (double)Main.maxTilesX * 0.4 || (double)i > (double)Main.maxTilesX * 0.6) && Main.rand.Next(15000) == 0)
                {
                    WorldGen.plantDye(i, j, true);
                }
                if (Main.tile[i, j].type == 80)
                {
                    if (WorldGen.genRand.Next(15) == 0)
                    {
                        WorldGen.GrowCactus(i, j);
                    }
                }
                else if (Main.tile[i, j].type == 529)
                {
                    if (WorldGen.CheckSeaOat(i, j) && WorldGen.genRand.Next(20) == 0)
                    {
                        WorldGen.GrowSeaOat(i, j);
                    }
                }
                else if (TileID.Sets.Conversion.Sand[(int)Main.tile[i, j].type])
                {
                    if (!Main.tile[i, num3].active())
                    {
                        if (WorldGen.genRand.Next(25) == 0)
{
                            WorldGen.PlaceOasisPlant(i, num3, 530);
                            if (Main.tile[i, num3].type == 530 && Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i - 1, num3 - 1, 3, 2, TileChangeType.None);
                            }
                        }
                        if (WorldGen.genRand.Next(20) != 0 || !WorldGen.PlantSeaOat(i, num3))
{
                            if (i < WorldGen.oceanDistance || i > Main.maxTilesX - WorldGen.oceanDistance)
{
                                if (WorldGen.genRand.Next(500) == 0)
{
                                    int num10 = 7;
                                    int num11 = 6;
                                    int num12 = 0;
                                    for (int m = i - num10; m <= i + num10; m++)
{
                                        for (int n = num3 - num10; n <= num3 + num10; n++)
{
                                            if (Main.tile[m, n].active() && Main.tile[m, n].type == 81)
{
                                                num12++;
                                            }
                                        }
                                    }
                                    if (num12 < num11 && Main.tile[i, num3].liquid == 255 && Main.tile[i, num3 - 1].liquid == 255 && Main.tile[i, num3 - 2].liquid == 255 && Main.tile[i, num3 - 3].liquid == 255 && Main.tile[i, num3 - 4].liquid == 255)
{
                                        WorldGen.PlaceTile(i, num3, 81, true, false, -1, 0);
                                        if (Main.netMode == 2 && Main.tile[i, num3].active())
{
                                            NetMessage.SendTileSquare(-1, i, num3, TileChangeType.None);
                                        }
                                    }
                                }
                            }
                            else if (i > WorldGen.beachDistance + 20 && i < Main.maxTilesX - WorldGen.beachDistance - 20 && WorldGen.genRand.Next(300) == 0)
{
                                WorldGen.GrowCactus(i, j);
                            }
                        }
                    }
                }
                else if (Main.tile[i, j].type == 530)
                {
                    if (!WorldGen.OasisPlantWaterCheck(i, j, true))
                    {
                        WorldGen.KillTile(i, j, false, false, false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                        }
                    }
                }
                else if (Main.tile[i, j].type == 147 || Main.tile[i, j].type == 161 || Main.tile[i, j].type == 163 || Main.tile[i, j].type == 164 || Main.tile[i, j].type == 200)
                {
                    if (Main.rand.Next(10) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 2].active())
                    {
                        int num13 = i - 3;
                        int num14 = i + 4;
                        int num15 = 0;
                        for (int num16 = num13; num16 < num14; num16++)
{
                            if (Main.tile[num16, j].type == 165 && Main.tile[num16, j].active())
{
                                num15++;
                            }
                            if (Main.tile[num16, j + 1].type == 165 && Main.tile[num16, j + 1].active())
{
                                num15++;
                            }
                            if (Main.tile[num16, j + 2].type == 165 && Main.tile[num16, j + 2].active())
{
                                num15++;
                            }
                            if (Main.tile[num16, j + 3].type == 165 && Main.tile[num16, j + 3].active())
{
                                num15++;
                            }
                        }
                        if (num15 < 2)
{
                            WorldGen.PlaceTight(i, j + 1, false);
                            WorldGen.SquareTileFrame(i, j + 1, true);
                            if (Main.netMode == 2 && Main.tile[i, j + 1].active())
{
                                NetMessage.SendTileSquare(-1, i, j + 1, 1, 2, TileChangeType.None);
                            }
                        }
                    }
                }
                else if (Main.tile[i, j].type == 254)
                {
                    if (Main.rand.Next((int)((Main.tile[i, j].frameX + 10) / 10)) == 0)
                    {
                        WorldGen.GrowPumpkin(i, j, 254);
                    }
                }
                else if (Main.tile[i, j].type == 78 || Main.tile[i, j].type == 380 || Main.tile[i, j].type == 579)
                {
                    if (!Main.tile[i, num3].active() && WorldGen.genRand.Next(2) == 0)
                    {
                        WorldGen.PlaceTile(i, num3, 3, true, false, -1, 0);
                        if (Main.netMode == 2 && Main.tile[i, num3].active())
{
                            NetMessage.SendTileSquare(-1, i, num3, TileChangeType.None);
                        }
                    }
                }
                else if (TileID.Sets.SpreadOverground[(int)Main.tile[i, j].type])
                {
                    WorldGen.UpdateWorld_GrassGrowth(i, j, num, num2, num3, num4, false);
                    int type = (int)Main.tile[i, j].type;
                    if ((type == 32 || type == 352) && WorldGen.genRand.Next(3) == 0)
                    {
                        if (type == 32)
{
                            WorldGen.GrowSpike(i, j, 32, 23);
                        }
                        else
{
                            WorldGen.GrowSpike(i, j, 352, 199);
                        }
                    }
                }
                else if (Main.tileMoss[(int)Main.tile[i, j].type] || TileID.Sets.tileMossBrick[(int)Main.tile[i, j].type])
                {
                    if (WorldGen.genRand.NextDouble() < 0.5)
                    {
                        int type2 = (int)Main.tile[i, j].type;
                        bool flag = false;
                        TileColorCache tileColorCache = Main.tile[i, j].BlockColorAndCoating();
                        for (int num17 = num; num17 < num2; num17++)
{
                            for (int num18 = num3; num18 < num4; num18++)
{
                                if ((i != num17 || j != num18) && Main.tile[num17, num18].active() && (Main.tile[num17, num18].type == 1 || Main.tile[num17, num18].type == 38))
{
                                    int type3 = (int)Main.tile[num17, num18].type;
                                    int num19 = WorldGen.MossConversion(type2, type3);
                                    WorldGen.SpreadGrass(num17, num18, (int)Main.tile[num17, num18].type, num19, false, tileColorCache);
                                    if ((int)Main.tile[num17, num18].type == num19)
{
                                        WorldGen.SquareTileFrame(num17, num18, true);
                                        flag = true;
                                    }
                                }
                            }
                        }
                        if (Main.netMode == 2 && flag)
{
                            NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                        }
                        if (WorldGen.genRand.Next(6) == 0)
{
                            int num20 = i;
                            int num21 = j;
                            int num22 = WorldGen.genRand.Next(4);
                            if (num22 == 0)
{
                                num20--;
                            }
                            else if (num22 == 1)
{
                                num20++;
                            }
                            else if (num22 == 2)
{
                                num21--;
                            }
                            else
{
                                num21++;
                            }
                            if (!Main.tile[num20, num21].active())
{
                                if (WorldGen.PlaceTile(num20, num21, 184, true, false, -1, 0))
{
                                    Main.tile[num20, num21].CopyPaintAndCoating(Main.tile[i, j]);
                                }
                                if (Main.netMode == 2 && Main.tile[num20, num21].active())
{
                                    NetMessage.SendTileSquare(-1, num20, num21, TileChangeType.None);
                                }
                            }
                        }
                    }
                }
                else if (Main.tile[i, j].type == 20)
                {
                    if (WorldGen.genRand.Next(20) == 0)
                    {
                        WorldGen.AttemptToGrowTreeFromSapling(i, j, false, 0, false);
                    }
                }
                else if (Main.tile[i, j].type == 595)
                {
                    if (WorldGen.genRand.Next(5) == 0)
                    {
                        WorldGen.AttemptToGrowTreeFromSapling(i, j, false, 0, false);
                    }
                }
                else if (Main.tile[i, j].type == 615)
                {
                    if (WorldGen.genRand.Next(5) == 0)
                    {
                        WorldGen.AttemptToGrowTreeFromSapling(i, j, false, 0, false);
                    }
                }
                else if (Main.tile[i, j].type == 3 && WorldGen.genRand.Next(20) == 0)
                {
                    if (Main.tile[i, j].frameX != 144)
                    {
                        Main.tile[i, j].type = 73;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                        }
                    }
                }
                else if (Main.tile[i, j].type == 110 && WorldGen.genRand.Next(20) == 0 && Main.tile[i, j].frameX < 144)
                {
                    Main.tile[i, j].type = 113;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                    }
                }
                if ((Main.dungeonX < 0 || Main.dungeonY < 0) && (double)j < Main.worldSurface && Main.tileDungeon[(int)Main.tile[i, j].type])
                {
                    bool flag2 = true;
                    for (int num23 = i - 1; num23 <= i + 1; num23++)
                    {
                        for (int num24 = j - 3; num24 <= j - 1; num24++)
{
                            if (WorldGen.SolidTile3(num23, num24))
{
                                flag2 = false;
                            }
                        }
                    }
                    if (flag2)
                    {
                        Main.dungeonX = i;
                        Main.dungeonY = j;
                    }
                }
            }
            else
            {
                if (Main.tile[i, j].wall == 62 && Main.tile[i, j].liquid == 0)
                {
                    WorldGen.GrowWeb(i, j);
                }
                WorldGen.TrySpawningTownNPC(i, j);
            }
            if (WorldGen.AllowedToSpreadInfections)
            {
                WorldGen.SpreadGrassWalls(wallDist, i, j);
                WorldGen.SpreadDesertWalls(wallDist, i, j);
            }
            if (Main.tile[i, j].nactive())
            {
                if (Main.tile[i, j].type == 2 || Main.tile[i, j].type == 52 || Main.tile[i, j].type == 382 || (Main.tile[i, j].type == 192 && WorldGen.genRand.Next(10) == 0))
                {
                    if (Main.tile[i, j].type == 52 || Main.tile[i, j].type == 382)
                    {
                    }
                    int num25 = 1;
                    if (WorldGen.genRand.Next(num25) == 0 && WorldGen.GrowMoreVines(i, j) && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag3 = false;
                        ushort num26 = 52;
                        if (Main.tile[i, j].type == 382)
{
                            num26 = 382;
                        }
                        else if (Main.tile[i, j].type != 52)
{
                            if (Main.tile[i, j].wall == 68 || Main.tile[i, j].wall == 65 || Main.tile[i, j].wall == 66 || Main.tile[i, j].wall == 63)
{
                                num26 = 382;
                            }
                            else if (Main.tile[i, j + 1].wall == 68 || Main.tile[i, j + 1].wall == 65 || Main.tile[i, j + 1].wall == 66 || Main.tile[i, j + 1].wall == 63)
{
                                num26 = 382;
                            }
                            if (Main.remixWorld && WorldGen.genRand.Next(5) == 0)
{
                                num26 = 382;
                            }
                        }
                        for (int num27 = j; num27 > j - 10; num27--)
{
                            if (Main.tile[i, num27].bottomSlope())
{
                                flag3 = false;
                                break;
                            }
                            if (Main.tile[i, num27].active() && Main.tile[i, num27].type == 2 && !Main.tile[i, num27].bottomSlope())
{
                                flag3 = true;
                                break;
                            }
                        }
                        if (flag3)
{
                            int num28 = j + 1;
                            Main.tile[i, num28].type = num26;
                            Main.tile[i, num28].active(true);
                            Main.tile[i, num28].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num28, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num28, TileChangeType.None);
                            }
                        }
                    }
                }
                else if (Main.tile[i, j].type == 61 && WorldGen.genRand.Next(3) == 0 && Main.tile[i, j + 1].type != 226 && Main.tile[i, j].frameX < 144)
                {
                    if (Main.rand.Next(4) == 0)
                    {
                        Main.tile[i, j].frameX = (short)(162 + WorldGen.genRand.Next(8) * 18);
                    }
                    Main.tile[i, j].type = 74;
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                    }
                }
                if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62 || Main.tile[i, j].type == 384 || Main.tile[i, j].type == 226) && WorldGen.GrowMoreVines(i, j))
                {
                    bool flag4 = true;
                    int num29 = 30;
                    if (Main.tile[i, j].type == 62)
                    {
                        num29 = 10;
                    }
                    if (Main.tile[i, j].type == 226)
                    {
                        flag4 = !WorldGen.TooManyJungleVinesNearby(i, j, 6);
                        num29 = 20;
                    }
                    if (flag4 && WorldGen.genRand.Next(num29) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag5 = false;
                        for (int num30 = j; num30 > j - 10; num30--)
{
                            if (Main.tile[i, num30].bottomSlope())
{
                                flag5 = false;
                                break;
                            }
                            if (Main.tile[i, num30].active() && (Main.tile[i, num30].type == 60 || Main.tile[i, num30].type == 384 || Main.tile[i, num30].type == 226))
{
                                flag5 = true;
                                break;
                            }
                        }
                        if (flag5)
{
                            int num31 = j + 1;
                            Main.tile[i, num31].type = 62;
                            Main.tile[i, num31].active(true);
                            Main.tile[i, num31].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num31, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num31, TileChangeType.None);
                            }
                        }
                    }
                }
                else if ((Main.tile[i, j].type == 70 || Main.tile[i, j].type == 528) && WorldGen.GrowMoreVines(i, j))
                {
                    int num32 = 70;
                    if (Main.tile[i, j].type == 528)
                    {
                        num32 = 7;
                    }
                    if (WorldGen.genRand.Next(num32) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag6 = false;
                        for (int num33 = j; num33 > j - 10; num33--)
{
                            if (Main.tile[i, num33].bottomSlope())
{
                                flag6 = false;
                                break;
                            }
                            if (Main.tile[i, num33].active() && Main.tile[i, num33].type == 70 && !Main.tile[i, num33].bottomSlope())
{
                                flag6 = true;
                                break;
                            }
                        }
                        if (flag6)
{
                            int num34 = j + 1;
                            Main.tile[i, num34].type = 528;
                            Main.tile[i, num34].active(true);
                            Main.tile[i, num34].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num34, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num34, TileChangeType.None);
                            }
                        }
                    }
                }
                else if ((Main.tile[i, j].type == 109 || Main.tile[i, j].type == 115) && WorldGen.GrowMoreVines(i, j))
                {
                    int num35 = 60;
                    if (Main.tile[i, j].type == 115)
                    {
                        num35 = 20;
                    }
                    if (WorldGen.genRand.Next(num35) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag7 = false;
                        for (int num36 = j; num36 > j - 10; num36--)
{
                            if (Main.tile[i, num36].bottomSlope())
{
                                flag7 = false;
                                break;
                            }
                            if (Main.tile[i, num36].active() && Main.tile[i, num36].type == 109 && !Main.tile[i, num36].bottomSlope())
{
                                flag7 = true;
                                break;
                            }
                        }
                        if (flag7)
{
                            int num37 = j + 1;
                            Main.tile[i, num37].type = 115;
                            Main.tile[i, num37].active(true);
                            Main.tile[i, num37].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num37, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num37, TileChangeType.None);
                            }
                        }
                    }
                }
                else if ((Main.tile[i, j].type == 23 || Main.tile[i, j].type == 661 || Main.tile[i, j].type == 636) && WorldGen.GrowMoreVines(i, j))
                {
                    int num38 = 60;
                    if (Main.tile[i, j].type == 636)
                    {
                        num38 = 20;
                    }
                    if (WorldGen.genRand.Next(num38) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag8 = false;
                        for (int num39 = j; num39 > j - 10; num39--)
{
                            if (Main.tile[i, num39].bottomSlope())
{
                                flag8 = false;
                                break;
                            }
                            if (Main.tile[i, num39].active() && (Main.tile[i, num39].type == 23 || Main.tile[i, num39].type == 661) && !Main.tile[i, num39].bottomSlope())
{
                                flag8 = true;
                                break;
                            }
                        }
                        if (flag8)
{
                            int num40 = j + 1;
                            Main.tile[i, num40].type = 636;
                            Main.tile[i, num40].active(true);
                            Main.tile[i, num40].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num40, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num40, TileChangeType.None);
                            }
                        }
                    }
                }
                else if ((Main.tile[i, j].type == 199 || Main.tile[i, j].type == 662 || Main.tile[i, j].type == 205) && WorldGen.GrowMoreVines(i, j))
                {
                    int num41 = 60;
                    if (Main.tile[i, j].type == 205)
                    {
                        num41 = 20;
                    }
                    if (WorldGen.genRand.Next(num41) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag9 = false;
                        for (int num42 = j; num42 > j - 10; num42--)
{
                            if (Main.tile[i, num42].bottomSlope())
{
                                flag9 = false;
                                break;
                            }
                            if (Main.tile[i, num42].active() && (Main.tile[i, num42].type == 199 || Main.tile[i, num42].type == 662) && !Main.tile[i, num42].bottomSlope())
{
                                flag9 = true;
                                break;
                            }
                        }
                        if (flag9)
{
                            int num43 = j + 1;
                            Main.tile[i, num43].type = 205;
                            Main.tile[i, num43].active(true);
                            Main.tile[i, num43].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num43, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num43, TileChangeType.None);
                            }
                        }
                    }
                }
                else if ((Main.tile[i, j].type == 633 || Main.tile[i, j].type == 638) && WorldGen.GrowMoreVines(i, j))
                {
                    int num44 = 70;
                    if (Main.tile[i, j].type == 638)
                    {
                        num44 = 7;
                    }
                    if (WorldGen.genRand.Next(num44) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
                    {
                        bool flag10 = false;
                        for (int num45 = j; num45 > j - 10; num45--)
{
                            if (Main.tile[i, num45].bottomSlope())
{
                                flag10 = false;
                                break;
                            }
                            if (Main.tile[i, num45].active() && Main.tile[i, num45].type == 633 && !Main.tile[i, num45].bottomSlope())
{
                                flag10 = true;
                                break;
                            }
                        }
                        if (flag10)
{
                            int num46 = j + 1;
                            Main.tile[i, num46].type = 638;
                            Main.tile[i, num46].active(true);
                            Main.tile[i, num46].CopyPaintAndCoating(Main.tile[i, j]);
                            WorldGen.SquareTileFrame(i, num46, true);
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num46, TileChangeType.None);
                            }
                        }
                    }
                }
            }
            if (!Main.remixWorld && Main.dontStarveWorld && (float)Main.rand.Next(200) < 100f * Main.maxRaining && Main.maxRaining >= 0.2f)
            {
                WorldGen.DontStarveTryWateringTile(i, j);
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.AllowedToSpreadInfections, Terraria.Tile.anyLava(), Terraria.NPC.AnyNPCs(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.WorldGen.beachDistance, Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.bottomSlope(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckSeaOat(), Terraria.Tile.CopyPaintAndCoating(), Terraria.WorldGen.DontStarveTryWateringTile(), Terraria.Main.dontStarveWorld, Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.Tile.frameX, Terraria.WorldGen.genRand, Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowMoreVines(), Terraria.WorldGen.GrowPumpkin(), Terraria.WorldGen.GrowSeaOat(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.GrowWeb(), Terraria.Main.hardMode, Terraria.WorldGen.hardUpdateWorld(), int, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.maxRaining, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.MossConversion(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.OasisPlantWaterCheck(), Terraria.WorldGen.oceanDistance, Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceOasisPlant(), Terraria.WorldGen.PlaceTight(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.plantDye(), Terraria.WorldGen.PlantSeaOat(), Terraria.Main.raining, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.WorldGen.RollRandomSeaShellStyle(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.ID.TileID.Sets.SlowlyDiesInWater, Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.SpreadGrassWalls(), Terraria.ID.TileID.Sets.SpreadOverground, Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileDungeon, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.WorldGen.TooManyJungleVinesNearby(), Terraria.WorldGen.TryGrowingAbigailsFlower(), Terraria.WorldGen.TrySpawningTownNPC(), Terraria.Tile.type, Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.Tile.wall, Terraria.Main.windSpeedCurrent, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.UpdateWorld().