Terraria Decompiled: Terraria.WorldGen.FinishGetGoodWorld
FinishGetGoodWorld()
static void Terraria.WorldGen.FinishGetGoodWorld () inline static private
Definition at line 22901 of file WorldGen.cs.
        {
            int num = 0;
            int num2 = 20;
            while ((double)num2 < Main.worldSurface)
            {
                for (int i = 20; i < Main.maxTilesX - 20; i++)
                {
                    if (Main.tile[i, num2].active() && TileID.Sets.Clouds[(int)Main.tile[i, num2].type])
                    {
                        num = num2;
                        break;
                    }
                }
                num2++;
            }
            byte b = (byte)WorldGen.genRand.Next(13, 25);
            for (int j = 0; j < Main.maxTilesX; j++)
            {
                bool flag = false;
                for (int k = 0; k < Main.maxTilesY; k++)
                {
                    if (Main.tile[j, k].active() && Main.tileDungeon[(int)Main.tile[j, k].type])
                    {
                        if (Main.tile[j, k].color() == 14)
{
                            flag = true;
                            b = 14;
                        }
                        else
{
                            if (Main.tile[j, k].type == 44)
{
                                flag = true;
                                b = (byte)WorldGen.genRand.Next(13, 15);
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    b = (byte)WorldGen.genRand.Next(23, 25);
                                }
                            }
                            if (Main.tile[j, k].type == 43)
{
                                flag = true;
                                b = (byte)WorldGen.genRand.Next(15, 19);
                            }
                            if (Main.tile[j, k].type == 41)
{
                                flag = true;
                                b = (byte)WorldGen.genRand.Next(19, 23);
                            }
                        }
                    }
                }
                if (flag)
                {
                    break;
                }
            }
            for (int l = 10; l < Main.maxTilesX - 10; l++)
            {
                for (int m = 10; m < Main.maxTilesY - 10; m++)
                {
                    if (Main.tile[l, m].active() && (Main.tileDungeon[(int)Main.tile[l, m].type] || TileID.Sets.CrackedBricks[(int)Main.tile[l, m].type]))
                    {
                        Main.tile[l, m].color(b);
                    }
                    if (Main.wallDungeon[(int)Main.tile[l, m].wall] && !WorldGen.drunkWorldGen && !WorldGen.notTheBees)
                    {
                        Main.tile[l, m].wallColor(b);
                    }
                    if (Main.tile[l, m].active())
                    {
                        bool flag2 = false;
                        if (Main.tile[l, m].type == 226)
{
                            flag2 = true;
                        }
                        if (Main.tile[l, m].type == 60 && Main.tile[l, m + 1].type == 226)
{
                            flag2 = true;
                        }
                        if (Main.tile[l, m].type == 137)
{
                            int num3 = (int)(Main.tile[l, m].frameY / 18);
                            if (num3 >= 1 && num3 <= 4)
{
                                flag2 = true;
                            }
                        }
                        if (flag2 && !WorldGen.notTheBees)
{
                            Main.tile[l, m].color(17);
                        }
                    }
                    if (Main.tile[l, m].wall == 87)
                    {
                        Main.tile[l, m].wallColor(25);
                    }
                    if (Main.tile[l, m].active())
                    {
                        if (!WorldGen.remixWorldGen && Main.tile[l, m].type == 57 && WorldGen.genRand.Next(15) == 0)
{
                            if (Main.tile[l, m - 1].type == 57)
{
                                Main.tile[l, m].active(false);
                            }
                            Main.tile[l, m].liquid = byte.MaxValue;
                            Main.tile[l, m].lava(true);
                        }
                        if (!WorldGen.tenthAnniversaryWorldGen && !WorldGen.notTheBees && m < num && Main.tile[l, m].type == 2)
{
                            if (WorldGen.crimson)
{
                                Main.tile[l, m].type = 199;
                            }
                            else
{
                                Main.tile[l, m].type = 23;
                            }
                            if (Main.tile[l, m - 1].type == 3)
{
                                Main.tile[l, m - 1].active(false);
                            }
                            if (Main.tile[l, m - 1].type == 73)
{
                                Main.tile[l, m - 1].active(false);
                            }
                            if (Main.tile[l, m - 1].type == 27)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 596)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 616)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 82)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 83)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 186)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 187)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 185)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                            if (Main.tile[l, m - 1].type == 227)
{
                                WorldGen.KillTile(l, m - 1, false, false, false);
                            }
                        }
                    }
                }
            }
            for (int n = 0; n < 8000; n++)
            {
                Chest chest = Main.chest[n];
                if (chest == null)
                {
                    break;
                }
                if (WorldGen.genRand.Next(10) == 0 && chest.item[1].stack != 0)
                {
                    for (int num4 = 1; num4 < chest.maxItems; num4++)
                    {
                        if (chest.item[num4].stack == 0)
{
                            chest.item[num4].SetDefaults(678, null);
                            break;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.chest, Terraria.ID.TileID.Sets.Clouds, Terraria.Tile.color(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.WorldGen.crimson, Terraria.Tile.frameY, Terraria.WorldGen.genRand, int, Terraria.Chest.item, Terraria.WorldGen.KillTile(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Chest.maxItems, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.WorldGen.remixWorldGen, Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), Terraria.Main.wallDungeon, and Terraria.Main.worldSurface.