Terraria Decompiled: Terraria.WorldGen.SpawnThingsFromPot
SpawnThingsFromPot()
static void Terraria.WorldGen.SpawnThingsFromPot (int i, int j, int x2, int y2, int style) inline static private
Definition at line 55741 of file WorldGen.cs.
        {
            bool flag = (double)j < Main.rockLayer;
            bool flag2 = j < Main.UnderworldLayer;
            if (Main.remixWorld)
            {
                flag = (double)j > Main.rockLayer && j < Main.UnderworldLayer;
                flag2 = (double)j > Main.worldSurface && (double)j < Main.rockLayer;
            }
            bool flag3 = (double)j > Main.worldSurface && Main.dontStarveWorld && !Main.remixWorld;
            float num = 1f;
            bool flag4 = style >= 34 && style <= 36;
            if (style != 0 && style != 1 && style != 2 && style != 3)
            {
                if (style >= 4 && style <= 6)
                {
                    num = 1.25f;
                }
                else if (style >= 7 && style <= 9)
                {
                    num = 1.75f;
                }
                else if (style >= 10 && style <= 12)
                {
                    num = 1.9f;
                }
                else if (style >= 13 && style <= 15)
                {
                    num = 2.1f;
                }
                else if (style >= 16 && style <= 18)
                {
                    num = 1.6f;
                }
                else if (style >= 19 && style <= 21)
                {
                    num = 3.5f;
                }
                else if (style >= 22 && style <= 24)
                {
                    num = 1.6f;
                }
                else if (style >= 25 && style <= 27)
                {
                    num = 10f;
                }
                else if (style >= 28 && style <= 30)
                {
                    if (Main.hardMode)
                    {
                        num = 4f;
                    }
                }
                else if (style >= 31 && style <= 33)
                {
                    num = 2f;
                }
                else if (style >= 34 && style <= 36)
                {
                    num = 1.25f;
                }
            }
            num = (num * 2f + 1f) / 3f;
            int num2 = 6;
            int num3 = 28;
            if (Main.tenthAnniversaryWorld && !Main.remixWorld)
            {
                num2 *= 2;
                num3 = 75;
            }
            if (!WorldGen.isGeneratingOrLoadingWorld && Main.tenthAnniversaryWorld && Main.notTheBeesWorld && !Main.drunkWorld && WorldGen.genRand.Next(50) == 0)
            {
                int num4 = Main.rand.Next(12, 21);
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 1130, num4, false, 0, false);
            }
            int num5 = (int)(500f / ((num + 1f) / 2f));
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                if (Player.GetClosestRollLuck(i, j, num5) == 0f)
                {
                    if (Main.netMode != 1)
                    {
                        Projectile.NewProjectile(WorldGen.GetProjectileSource_TileBreak(i, j), (float)(i * 16 + 16), (float)(j * 16 + 16), 0f, -12f, 518, 0, 0f, Main.myPlayer, 0f, 0f, 0f, null);
                        return;
                    }
                }
                else
                {
                    if (WorldGen.genRand.Next(35) == 0 && Main.wallDungeon[(int)Main.tile[i, j].wall] && (double)j > Main.worldSurface)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 327, 1, false, 0, false);
                        return;
                    }
                    if (flag3 && WorldGen.genRand.Next(20) == 0)
                    {
                        int fruitForPot = WorldGen.GetFruitForPot(i, j, style);
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, fruitForPot, WorldGen.genRand.Next(1, 3), false, 0, false);
                        return;
                    }
                    if (Main.getGoodWorld && WorldGen.genRand.Next(num2) == 0)
                    {
                        Projectile.NewProjectile(WorldGen.GetProjectileSource_TileBreak(i, j), (float)(i * 16 + 16), (float)(j * 16 + 8), (float)Main.rand.Next(-100, 101) * 0.002f, 0f, num3, 0, 0f, Main.myPlayer, 16f, 16f, 0f, null);
                        return;
                    }
                    if (Main.remixWorld && Main.netMode != 1 && WorldGen.genRand.Next(5) == 0)
                    {
                        Player player = Main.player[(int)Player.FindClosest(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16)];
                        if (Main.rand.Next(2) == 0)
{
                            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 75, 1, false, 0, false);
                            return;
                        }
                        if (player.ZoneJungle)
{
                            int num6 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, -10, 0, 0f, 0f, 0f, 0f, 255);
                            if (num6 > -1)
{
                                Main.npc[num6].ai[1] = 75f;
                                Main.npc[num6].netUpdate = true;
                                return;
                            }
                        }
                        else if ((double)j > Main.rockLayer && j < Main.maxTilesY - 350)
{
                            int num7;
                            if (Main.rand.Next(9) == 0)
{
                                num7 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, -7, 0, 0f, 0f, 0f, 0f, 255);
                            }
                            else if (Main.rand.Next(7) == 0)
{
                                num7 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, -8, 0, 0f, 0f, 0f, 0f, 255);
                            }
                            else if (Main.rand.Next(6) == 0)
{
                                num7 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, -9, 0, 0f, 0f, 0f, 0f, 255);
                            }
                            else if (Main.rand.Next(3) == 0)
{
                                num7 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, -3, 0, 0f, 0f, 0f, 0f, 255);
                            }
                            else
{
                                num7 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, 1, 0, 0f, 0f, 0f, 0f, 255);
                            }
                            if (num7 > -1)
{
                                Main.npc[num7].ai[1] = 75f;
                                Main.npc[num7].netUpdate = true;
                                return;
                            }
                        }
                        else
{
                            if ((double)j <= Main.worldSurface || (double)j > Main.rockLayer)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 75, 1, false, 0, false);
                                return;
                            }
                            int num8 = NPC.NewNPC(WorldGen.GetNPCSource_FromTileBreak(i, j), x2 * 16 + 16, y2 * 16 + 32, -6, 0, 0f, 0f, 0f, 0f, 255);
                            if (num8 > -1)
{
                                Main.npc[num8].ai[1] = 75f;
                                Main.npc[num8].netUpdate = true;
                                return;
                            }
                        }
                    }
                    else
                    {
                        if (Main.remixWorld && (double)i > (double)Main.maxTilesX * 0.37 && (double)i < (double)Main.maxTilesX * 0.63 && j > Main.maxTilesY - 220)
{
                            int num9 = Main.rand.Next(20, 41);
                            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 965, num9, false, 0, false);
                            return;
                        }
                        if (WorldGen.genRand.Next(45) == 0 || (Main.rand.Next(45) == 0 && Main.expertMode))
{
                            if ((double)j < Main.worldSurface)
{
                                int num10 = WorldGen.genRand.Next(10);
                                if (num10 == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 292, 1, false, 0, false);
                                }
                                if (num10 == 1)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 298, 1, false, 0, false);
                                }
                                if (num10 == 2)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 299, 1, false, 0, false);
                                }
                                if (num10 == 3)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 290, 1, false, 0, false);
                                }
                                if (num10 == 4)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2322, 1, false, 0, false);
                                }
                                if (num10 == 5)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2324, 1, false, 0, false);
                                }
                                if (num10 == 6)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2325, 1, false, 0, false);
                                }
                                if (num10 >= 7)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2350, WorldGen.genRand.Next(1, 3), false, 0, false);
                                    return;
                                }
                            }
                            else if (flag)
{
                                int num11 = WorldGen.genRand.Next(11);
                                if (num11 == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 289, 1, false, 0, false);
                                }
                                if (num11 == 1)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 298, 1, false, 0, false);
                                }
                                if (num11 == 2)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 299, 1, false, 0, false);
                                }
                                if (num11 == 3)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 290, 1, false, 0, false);
                                }
                                if (num11 == 4)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 303, 1, false, 0, false);
                                }
                                if (num11 == 5)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 291, 1, false, 0, false);
                                }
                                if (num11 == 6)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 304, 1, false, 0, false);
                                }
                                if (num11 == 7)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2322, 1, false, 0, false);
                                }
                                if (num11 == 8)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2329, 1, false, 0, false);
                                }
                                if (num11 >= 7)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2350, WorldGen.genRand.Next(1, 3), false, 0, false);
                                    return;
                                }
                            }
                            else if (flag2)
{
                                int num12 = WorldGen.genRand.Next(15);
                                if (num12 == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 296, 1, false, 0, false);
                                }
                                if (num12 == 1)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 295, 1, false, 0, false);
                                }
                                if (num12 == 2)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 299, 1, false, 0, false);
                                }
                                if (num12 == 3)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 302, 1, false, 0, false);
                                }
                                if (num12 == 4)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 303, 1, false, 0, false);
                                }
                                if (num12 == 5)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 305, 1, false, 0, false);
                                }
                                if (num12 == 6)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 301, 1, false, 0, false);
                                }
                                if (num12 == 7)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 302, 1, false, 0, false);
                                }
                                if (num12 == 8)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 297, 1, false, 0, false);
                                }
                                if (num12 == 9)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 304, 1, false, 0, false);
                                }
                                if (num12 == 10)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2322, 1, false, 0, false);
                                }
                                if (num12 == 11)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2323, 1, false, 0, false);
                                }
                                if (num12 == 12)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2327, 1, false, 0, false);
                                }
                                if (num12 == 13)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2329, 1, false, 0, false);
                                }
                                if (num12 >= 7)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2350, WorldGen.genRand.Next(1, 3), false, 0, false);
                                }
                                if (WorldGen.genRand.Next(15) == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 4870, 1, false, 0, false);
                                    return;
                                }
                            }
                            else
{
                                int num13 = WorldGen.genRand.Next(14);
                                if (num13 == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 296, 1, false, 0, false);
                                }
                                if (num13 == 1)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 295, 1, false, 0, false);
                                }
                                if (num13 == 2)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 293, 1, false, 0, false);
                                }
                                if (num13 == 3)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 288, 1, false, 0, false);
                                }
                                if (num13 == 4)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 294, 1, false, 0, false);
                                }
                                if (num13 == 5)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 297, 1, false, 0, false);
                                }
                                if (num13 == 6)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 304, 1, false, 0, false);
                                }
                                if (num13 == 7)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 305, 1, false, 0, false);
                                }
                                if (num13 == 8)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 301, 1, false, 0, false);
                                }
                                if (num13 == 9)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 302, 1, false, 0, false);
                                }
                                if (num13 == 10)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 288, 1, false, 0, false);
                                }
                                if (num13 == 11)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 300, 1, false, 0, false);
                                }
                                if (num13 == 12)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2323, 1, false, 0, false);
                                }
                                if (num13 == 13)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2326, 1, false, 0, false);
                                }
                                if (WorldGen.genRand.Next(5) == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 4870, 1, false, 0, false);
                                    return;
                                }
                            }
                        }
                        else
{
                            if (Main.netMode == 2 && Main.rand.Next(30) == 0)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 2997, 1, false, 0, false);
                                return;
                            }
                            int num14 = Main.rand.Next(7);
                            if (Main.expertMode)
{
                                num14--;
                            }
                            Player player2 = Main.player[(int)Player.FindClosest(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16)];
                            int num15 = 0;
                            int num16 = 20;
                            if (Main.vampireSeed)
{
                                num16 = 30;
                            }
                            for (int k = 0; k < 50; k++)
{
                                Item item = player2.inventory[k];
                                if (!item.IsAir && item.createTile >= 0 && (item.createTile < 0 || TileID.Sets.Torches[item.createTile]))
{
                                    num15 += item.stack;
                                    if (num15 >= num16)
{
                                        break;
                                    }
                                }
                            }
                            bool flag5 = num15 < num16;
                            if (flag5 && Main.vampireSeed)
{
                                num14 = 1;
                            }
                            if (num14 == 0 && player2.statLife < player2.statLifeMax2)
{
                                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 58, 1, false, 0, false);
                                if (Main.rand.Next(2) == 0)
{
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 58, 1, false, 0, false);
                                }
                                if (Main.expertMode)
{
                                    if (Main.rand.Next(2) == 0)
{
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 58, 1, false, 0, false);
                                    }
                                    if (Main.rand.Next(2) == 0)
{
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 58, 1, false, 0, false);
                                        return;
                                    }
                                }
                            }
                            else
{
                                if (Main.vampireSeed && (flag2 || flag) && WorldGen.genRand.Next(6) == 0)
{
                                    int num17 = 9;
                                    if (style >= 4 && style <= 6)
{
                                        num17 = 2503;
                                    }
                                    else if (style >= 7 && style <= 9)
{
                                        num17 = 620;
                                    }
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num17, Main.rand.Next(10, 31), false, 0, false);
                                    return;
                                }
                                if (num14 == 1 || (num14 == 0 && flag5))
{
                                    int num18 = Main.rand.Next(2, 7);
                                    if (Main.expertMode)
{
                                        num18 += Main.rand.Next(1, 7);
                                    }
                                    if (Main.vampireSeed)
{
                                        num18 += Main.rand.Next(2, 7);
                                    }
                                    int num19 = 8;
                                    int num20 = 282;
                                    if (player2.ZoneHallow)
{
                                        num18 += Main.rand.Next(2, 7);
                                        num19 = 4387;
                                    }
                                    else if ((style >= 22 && style <= 24) || player2.ZoneCrimson)
{
                                        num18 += Main.rand.Next(2, 7);
                                        num19 = 4386;
                                    }
                                    else if ((style >= 16 && style <= 18) || player2.ZoneCorrupt)
{
                                        num18 += Main.rand.Next(2, 7);
                                        num19 = 4385;
                                    }
                                    else if (style >= 7 && style <= 9)
{
                                        num18 += Main.rand.Next(2, 7);
                                        num18 = (int)((float)num18 * 1.5f);
                                        num19 = 4388;
                                    }
                                    else if (style >= 4 && style <= 6)
{
                                        num19 = 974;
                                        num20 = 286;
                                    }
                                    else if (style >= 34 && style <= 36)
{
                                        num18 += Main.rand.Next(2, 7);
                                        num19 = 4383;
                                    }
                                    else if (player2.ZoneGlowshroom)
{
                                        num18 += Main.rand.Next(2, 7);
                                        num19 = 5293;
                                    }
                                    if (Main.tile[i, j].liquid > 0)
{
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num20, num18, false, 0, false);
                                        return;
                                    }
                                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num19, num18, false, 0, false);
                                    return;
                                }
                                else
{
                                    if (num14 == 2)
{
                                        int num21 = Main.rand.Next(10, 21);
                                        int num22 = 40;
                                        if (flag && WorldGen.genRand.Next(2) == 0)
{
                                            if (Main.hardMode)
{
                                                num22 = 168;
                                            }
                                            else
{
                                                num22 = 42;
                                            }
                                        }
                                        if (j > Main.UnderworldLayer)
{
                                            num22 = 265;
                                        }
                                        else if (Main.hardMode)
{
                                            if (Main.rand.Next(2) == 0)
{
                                                if (WorldGen.SavedOreTiers.Silver == 168)
{
                                                    num22 = 4915;
                                                }
                                                else
{
                                                    num22 = 278;
                                                }
                                            }
                                            else
{
                                                num22 = 47;
                                            }
                                        }
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num22, num21, false, 0, false);
                                        return;
                                    }
                                    if (num14 == 3)
{
                                        int num23 = 28;
                                        if (j > Main.UnderworldLayer || Main.hardMode)
{
                                            num23 = 188;
                                        }
                                        int num24 = 1;
                                        if (Main.expertMode && Main.rand.Next(3) != 0)
{
                                            num24++;
                                        }
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num23, num24, false, 0, false);
                                        return;
                                    }
                                    if (num14 == 4 && (flag4 || flag2))
{
                                        int num25 = 166;
                                        if (flag4)
{
                                            num25 = 4423;
                                        }
                                        int num26 = Main.rand.Next(4) + 1;
                                        if (Main.expertMode)
{
                                            num26 += Main.rand.Next(4);
                                        }
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, num25, num26, false, 0, false);
                                        return;
                                    }
                                    if ((num14 == 4 || num14 == 5) && j < Main.UnderworldLayer && !Main.hardMode)
{
                                        int num27 = Main.rand.Next(20, 41);
                                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 965, num27, false, 0, false);
                                        return;
                                    }
                                    float num28 = (float)(200 + WorldGen.genRand.Next(-100, 101));
                                    if ((double)j < Main.worldSurface)
{
                                        num28 *= 0.5f;
                                    }
                                    else if (flag)
{
                                        num28 *= 0.75f;
                                    }
                                    else if (j > Main.maxTilesY - 250)
{
                                        num28 *= 1.25f;
                                    }
                                    num28 *= 1f + (float)Main.rand.Next(-20, 21) * 0.01f;
                                    if (Main.rand.Next(4) == 0)
{
                                        num28 *= 1f + (float)Main.rand.Next(5, 11) * 0.01f;
                                    }
                                    if (Main.rand.Next(8) == 0)
{
                                        num28 *= 1f + (float)Main.rand.Next(10, 21) * 0.01f;
                                    }
                                    if (Main.rand.Next(12) == 0)
{
                                        num28 *= 1f + (float)Main.rand.Next(20, 41) * 0.01f;
                                    }
                                    if (Main.rand.Next(16) == 0)
{
                                        num28 *= 1f + (float)Main.rand.Next(40, 81) * 0.01f;
                                    }
                                    if (Main.rand.Next(20) == 0)
{
                                        num28 *= 1f + (float)Main.rand.Next(50, 101) * 0.01f;
                                    }
                                    if (Main.expertMode)
{
                                        num28 *= 2.5f;
                                    }
                                    if (Main.expertMode && Main.rand.Next(2) == 0)
{
                                        num28 *= 1.25f;
                                    }
                                    if (Main.expertMode && Main.rand.Next(3) == 0)
{
                                        num28 *= 1.5f;
                                    }
                                    if (Main.expertMode && Main.rand.Next(4) == 0)
{
                                        num28 *= 1.75f;
                                    }
                                    num28 *= num;
                                    if (NPC.downedBoss1)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedBoss2)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedBoss3)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedMechBoss1)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedMechBoss2)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedMechBoss3)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedPlantBoss)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedQueenBee)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedGolemBoss)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedPirates)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedGoblins)
{
                                        num28 *= 1.1f;
                                    }
                                    if (NPC.downedFrost)
{
                                        num28 *= 1.1f;
                                    }
                                    while ((int)num28 > 0)
{
                                        if (num28 > 1000000f)
{
                                            int num29 = (int)(num28 / 1000000f);
                                            if (num29 > 50 && Main.rand.Next(2) == 0)
{
                                                num29 /= Main.rand.Next(3) + 1;
                                            }
                                            if (Main.rand.Next(2) == 0)
{
                                                num29 /= Main.rand.Next(3) + 1;
                                            }
                                            num28 -= (float)(1000000 * num29);
                                            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 74, num29, false, 0, false);
                                        }
                                        else if (num28 > 10000f)
{
                                            int num30 = (int)(num28 / 10000f);
                                            if (num30 > 50 && Main.rand.Next(2) == 0)
{
                                                num30 /= Main.rand.Next(3) + 1;
                                            }
                                            if (Main.rand.Next(2) == 0)
{
                                                num30 /= Main.rand.Next(3) + 1;
                                            }
                                            num28 -= (float)(10000 * num30);
                                            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 73, num30, false, 0, false);
                                        }
                                        else if (num28 > 100f)
{
                                            int num31 = (int)(num28 / 100f);
                                            if (num31 > 50 && Main.rand.Next(2) == 0)
{
                                                num31 /= Main.rand.Next(3) + 1;
                                            }
                                            if (Main.rand.Next(2) == 0)
{
                                                num31 /= Main.rand.Next(3) + 1;
                                            }
                                            num28 -= (float)(100 * num31);
                                            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 72, num31, false, 0, false);
                                        }
                                        else
{
                                            int num32 = (int)num28;
                                            if (num32 > 50 && Main.rand.Next(2) == 0)
{
                                                num32 /= Main.rand.Next(3) + 1;
                                            }
                                            if (Main.rand.Next(2) == 0)
{
                                                num32 /= Main.rand.Next(4) + 1;
                                            }
                                            if (num32 < 1)
{
                                                num32 = 1;
                                            }
                                            num28 -= (float)num32;
                                            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 71, num32, false, 0, false);
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.NPC.ai, Terraria.Main.dontStarveWorld, Terraria.NPC.downedBoss1, Terraria.NPC.downedBoss2, Terraria.NPC.downedBoss3, Terraria.NPC.downedFrost, Terraria.NPC.downedGoblins, Terraria.NPC.downedGolemBoss, Terraria.NPC.downedMechBoss1, Terraria.NPC.downedMechBoss2, Terraria.NPC.downedMechBoss3, Terraria.NPC.downedPirates, Terraria.NPC.downedPlantBoss, Terraria.NPC.downedQueenBee, Terraria.Main.drunkWorld, Terraria.Main.expertMode, Terraria.Player.FindClosest(), Terraria.WorldGen.genRand, Terraria.Player.GetClosestRollLuck(), Terraria.WorldGen.GetFruitForPot(), Terraria.Main.getGoodWorld, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.WorldGen.GetNPCSource_FromTileBreak(), Terraria.WorldGen.GetProjectileSource_TileBreak(), Terraria.Main.hardMode, int, Terraria.Player.inventory, Terraria.WorldGen.isGeneratingOrLoadingWorld, System.item, Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.NPC.netUpdate, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.Main.npc, Terraria.Main.player, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.WorldGen.SavedOreTiers.Silver, Terraria.Player.statLife, Terraria.Player.statLifeMax2, Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.ID.TileID.Sets.Torches, Terraria.Main.UnderworldLayer, Terraria.Main.vampireSeed, Terraria.Tile.wall, Terraria.Main.wallDungeon, Terraria.Main.worldSurface, Terraria.Player.ZoneCorrupt, Terraria.Player.ZoneCrimson, Terraria.Player.ZoneGlowshroom, Terraria.Player.ZoneHallow, and Terraria.Player.ZoneJungle.
Referenced by Terraria.WorldGen.CheckPot().