Terraria Decompiled: Terraria.WorldGen.AddSpikeCaves
AddSpikeCaves()
static void Terraria.WorldGen.AddSpikeCaves (GenerationProgress progress) inline static private
Definition at line 21215 of file WorldGen.cs.
        {
            progress.Message = Language.GetTextValue("WorldGeneration.SpikeCaves");
            progress.Set(0.0);
            WorldGen.maxTileCount = 3500;
            int num = Main.maxTilesX / 2;
            int num2 = 3;
            switch (WorldGen.GetWorldSize())
            {
            case 0:
                num2 = 3;
                break;
            case 1:
                num2 = 5;
                break;
            case 2:
                num2 = 7;
                break;
            }
            num2 += WorldGen.genRand.Next(2);
            int num3 = 500;
            int num4 = 3500;
            SpikePitBiome spikePitBiome = GenVars.configuration.CreateBiome<SpikePitBiome>();
            bool flag = Main.tileSolid[225];
            if (WorldGen.notTheBees)
            {
                Main.tileSolid[225] = true;
            }
            for (int i = 0; i < num2; i++)
            {
                progress.Set((double)((float)i / (float)num2));
                int num5 = 0;
                int num6 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                int num7 = WorldGen.genRand.Next((int)(Main.worldSurface + Main.rockLayer) / 2, Main.maxTilesY - 230);
                if (WorldGen.remixWorldGen)
                {
                    num7 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                }
                int num8 = WorldGen.countTiles(num6, num7, false, true);
                while ((num8 >= num4 || num8 < num3) && num5 < num)
                {
                    num5++;
                    num6 = WorldGen.genRand.Next(200, Main.maxTilesX - 200);
                    num7 = WorldGen.genRand.Next((int)Main.rockLayer + 30, Main.maxTilesY - 230);
                    if (WorldGen.remixWorldGen)
                    {
                        num7 = WorldGen.genRand.Next((int)Main.worldSurface, (int)Main.rockLayer);
                    }
                    num8 = WorldGen.countTiles(num6, num7, false, true);
                    if (WorldGen.shroomCount > 1)
                    {
                        num8 = 0;
                    }
                }
                if (num5 < num)
                {
                    spikePitBiome.Place(new Point(num6, num7), GenVars.structures);
                }
            }
            if (WorldGen.notTheBees)
            {
                Main.tileSolid[225] = flag;
            }
        }
References Terraria.WorldBuilding.GenVars.configuration, Terraria.WorldGen.countTiles(), Terraria.WorldGen.genRand, Terraria.Localization.Language.GetTextValue(), Terraria.WorldGen.GetWorldSize(), int, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.GameContent.Biomes.SpikePitBiome.Place(), Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.shroomCount, Terraria.WorldBuilding.GenVars.structures, Terraria.Main.tileSolid, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses().