Terraria Decompiled: Terraria.WorldGen.SpreadGrass
SpreadGrass()
static void Terraria.WorldGen.SpreadGrass (int i, int j, int dirt = 0, int grass = 2, bool repeat = true, TileColorCache color = default(TileColorCache)) inline static
Definition at line 75645 of file WorldGen.cs.
        {
            try
            {
                if (WorldGen.InWorld(i, j, 10))
                {
                    if (Main.tile[i, j].active() && (int)Main.tile[i, j].type == dirt)
                    {
                        if (WorldGen.isGeneratingOrLoadingWorld && (grass == 199 || grass == 23))
{
                            int num = WorldGen.beachDistance;
                            if (!WorldGen.tenthAnniversaryWorldGen && (double)i > (double)Main.maxTilesX * 0.45 && (double)i <= (double)Main.maxTilesX * 0.55)
{
                                return;
                            }
                            if (i < num || i >= Main.maxTilesX - num)
{
                                return;
                            }
                        }
                        else if ((WorldGen.isGeneratingOrLoadingWorld || (grass != 199 && grass != 23 && grass != 661 && grass != 662)) && ((int)Main.tile[i, j].type != dirt || !Main.tile[i, j].active() || ((double)j >= Main.worldSurface && dirt == 0)) && !WorldGen.growGrassUnderground)
{
                            return;
                        }
                        int num2 = i - 1;
                        int num3 = i + 2;
                        int num4 = j - 1;
                        int num5 = j + 2;
                        if (num2 < 0)
{
                            num2 = 0;
                        }
                        if (num3 > Main.maxTilesX)
{
                            num3 = Main.maxTilesX;
                        }
                        if (num4 < 0)
{
                            num4 = 0;
                        }
                        if (num5 > Main.maxTilesY)
{
                            num5 = Main.maxTilesY;
                        }
                        bool flag = true;
                        for (int k = num2; k < num3; k++)
{
                            for (int l = num4; l < num5; l++)
{
                                if (!Main.tile[k, l].active() || !Main.tileSolid[(int)Main.tile[k, l].type])
{
                                    flag = false;
                                }
                                if (Main.tile[k, l].lava() && Main.tile[k, l].liquid > 0)
{
                                    flag = true;
                                    break;
                                }
                            }
                        }
                        if (!flag && WorldGen.CanBeClearedDuringGeneration((int)Main.tile[i, j].type, i, j, true))
{
                            if ((grass != 23 && grass != 661) || Main.tile[i, j - 1].type != 27)
{
                                if ((grass != 199 && grass != 662) || Main.tile[i, j - 1].type != 27)
{
                                    if (grass != 109 || Main.tile[i, j - 1].type != 27)
{
                                        bool flag2 = dirt > 0 && TileID.Sets.Conversion.Grass[dirt];
                                        bool flag3 = grass == 23 || grass == 661 || grass == 199 || grass == 662 || grass == 109 || grass == 492;
                                        if (flag2 && (grass == 23 || grass == 661))
{
                                            WorldGen.Convert(i, j, 1, true, false);
                                        }
                                        else if (flag2 && (grass == 199 || grass == 662))
{
                                            WorldGen.Convert(i, j, 4, true, false);
                                        }
                                        else if (flag2 && grass == 109)
{
                                            WorldGen.Convert(i, j, 2, true, false);
                                        }
                                        else
{
                                            WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid(i, j, grass);
                                            Main.tile[i, j].type = (ushort)grass;
                                            WorldGen.SquareTileFrame(i, j, true);
                                        }
                                        if (!flag3 || !SpecialSeedFeatures.RainbowSandAndBlackSandWalls)
{
                                            Main.tile[i, j].UseBlockColors(color);
                                        }
                                        NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                                        for (int m = num2; m < num3; m++)
{
                                            for (int n = num4; n < num5; n++)
{
                                                if (Main.tile[m, n].active() && (int)Main.tile[m, n].type == dirt)
{
                                                    try
{
                                                        if (repeat && WorldGen.grassSpread < 1000)
{
                                                            WorldGen.grassSpread++;
                                                            WorldGen.SpreadGrass(m, n, dirt, grass, true, default(TileColorCache));
                                                            WorldGen.grassSpread--;
                                                        }
                                                    }
                                                    catch
{
                                                    }
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch
            {
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.beachDistance, Terraria.WorldGen.CanBeClearedDuringGeneration(), Terraria.WorldGen.Convert(), Terraria.ID.TileID.Sets.Conversion.Grass, Terraria.WorldGen.grassSpread, Terraria.WorldGen.growGrassUnderground, int, Terraria.WorldGen.InWorld(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.GameContent.SpecialSeedFeatures.RainbowSandAndBlackSandWalls, Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid(), Terraria.Tile.type, Terraria.Tile.UseBlockColors(), and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.neonMossBiome(), Terraria.WorldGen.SonOfLakinater(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().