Terraria Decompiled: Terraria.WorldGen.CheckDoorOpen
CheckDoorOpen()
static void Terraria.WorldGen.CheckDoorOpen (int i, int j, Tile tileCache) inline static private
Definition at line 87201 of file WorldGen.cs.
        {
            if (!WorldGen.destroyObject)
            {
                int num = 0;
                int num2 = i;
                int frameX = (int)tileCache.frameX;
                int frameY = (int)tileCache.frameY;
                int num3 = frameY / 54;
                num3 += (int)(tileCache.frameX / 72 * 36);
                int num4 = j - frameY % 54 / 18;
                bool flag = false;
                int num5 = frameX % 72;
                if (num5 == 0)
                {
                    num2 = i;
                    num = 1;
                }
                else if (num5 == 18)
                {
                    num2 = i - 1;
                    num = 1;
                }
                else if (num5 == 36)
                {
                    num2 = i + 1;
                    num = -1;
                }
                else if (num5 == 54)
                {
                    num2 = i;
                    num = -1;
                }
                Tile tile = Main.tile[num2, num4 - 1];
                Tile tile2 = Main.tile[num2, num4 + 3];
                if (tile == null)
                {
                    tile = new Tile();
                    Main.tile[num2, num4 - 1] = tile;
                }
                if (tile2 == null)
                {
                    tile2 = new Tile();
                    Main.tile[num2, num4 + 3] = tile2;
                }
                if (!WorldGen.SolidTile(tile) || !WorldGen.SolidTile(tile2))
                {
                    flag = true;
                }
                int num6 = num2;
                if (num == -1)
                {
                    num6 = num2 - 1;
                }
                if (!flag)
                {
                    for (int k = num6; k < num6 + 2; k++)
                    {
                        for (int l = num4; l < num4 + 3; l++)
{
                            Tile tile3 = Main.tile[k, l];
                            if (tile3 != null && (!tile3.active() || tile3.type != 11))
{
                                flag = true;
                                break;
                            }
                        }
                        if (flag)
{
                            break;
                        }
                    }
                }
                if (flag)
                {
                    WorldGen.destroyObject = true;
                    WorldGen.DropDoorItem(i, j, num3);
                    for (int m = num6; m < num6 + 2; m++)
                    {
                        for (int n = num4; n < num4 + 3; n++)
{
                            Tile tile4 = Main.tile[m, n];
                            if (tile4 != null && tile4.active() && tile4.type == 11)
{
                                WorldGen.KillTile(m, n, false, false, false);
                            }
                        }
                    }
                }
                WorldGen.destroyObject = false;
                WorldGen.CheckExploitDestroyQueue();
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.destroyObject, Terraria.WorldGen.DropDoorItem(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.WorldGen.KillTile(), Terraria.WorldGen.SolidTile(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().