Terraria Decompiled: Terraria.WorldGen.Check4x2
Check4x2()
static void Terraria.WorldGen.Check4x2 (int i, int j, int type) inline static
Definition at line 45765 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int num;
            if (type == 487)
            {
                num = i + (int)(Main.tile[i, j].frameX / 18 % 4 * -1);
            }
            else
            {
                num = i + (int)(Main.tile[i, j].frameX / 18 * -1);
            }
            if ((type == 79 || type == 90) && Main.tile[i, j].frameX >= 72)
            {
                num += 4;
            }
            int k = (int)(Main.tile[i, j].frameY / 18);
            int num2 = 0;
            while (k > 1)
            {
                k -= 2;
                num2++;
            }
            k = j - k;
            if (type == 487)
            {
                num2 = (int)(Main.tile[i, j].frameX / 72);
            }
            for (int l = num; l < num + 4; l++)
            {
                for (int m = k; m < k + 2; m++)
                {
                    int num3 = (l - num) * 18;
                    int num4 = (m - k) * 18;
                    if ((type == 79 || type == 90) && Main.tile[i, j].frameX >= 72)
                    {
                        num3 = (l - num + 4) * 18;
                    }
                    if (type == 487)
                    {
                        num3 += num2 * 72;
                    }
                    else
                    {
                        num4 += num2 * 36;
                    }
                    if (Main.tile[l, m] == null)
                    {
                        Main.tile[l, m] = new Tile();
                    }
                    if (!Main.tile[l, m].active() || (int)Main.tile[l, m].type != type || (int)Main.tile[l, m].frameX != num3 || (int)Main.tile[l, m].frameY != num4)
                    {
                        flag = true;
                    }
                }
                if (Main.tile[l, k + 2] == null)
                {
                    Main.tile[l, k + 2] = new Tile();
                }
                if (!WorldGen.SolidTileAllowBottomSlope(l, k + 2) && (!Main.tile[l, k + 2].active() || !TileID.Sets.Platforms[(int)Main.tile[l, k + 2].type]))
                {
                    flag = true;
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int n = num; n < num + 4; n++)
                {
                    for (int num5 = k; num5 < k + 3; num5++)
                    {
                        if ((int)Main.tile[n, num5].type == type && Main.tile[n, num5].active())
{
                            WorldGen.KillTile(n, num5, false, false, false);
                        }
                    }
                }
                if (type == 79)
                {
                    int itemDrop_Beds = WorldGen.GetItemDrop_Beds(num2);
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, itemDrop_Beds, 1, false, 0, false);
                }
                if (type == 487)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, WorldGen.GetItemDrop_PicnicTables(num2), 1, false, 0, false);
                }
                if (type == 90)
                {
                    int itemDrop_Bathtubs = WorldGen.GetItemDrop_Bathtubs(num2);
                    Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 32, 32, itemDrop_Bathtubs, 1, false, 0, false);
                }
                WorldGen.destroyObject = false;
                for (int num6 = num - 1; num6 < num + 4; num6++)
                {
                    for (int num7 = k - 1; num7 < k + 4; num7++)
                    {
                        WorldGen.TileFrame(num6, num7, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemDrop_Bathtubs(), Terraria.WorldGen.GetItemDrop_Beds(), Terraria.WorldGen.GetItemDrop_PicnicTables(), Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().