Terraria Decompiled: Terraria.WorldGen.PlaceDye
PlaceDye()
static void Terraria.WorldGen.PlaceDye (int x, int y, int style) inline static
Definition at line 52489 of file WorldGen.cs.
        {
            bool flag = false;
            if (Main.tile[x, y + 1] == null || Main.tile[x, y - 1] == null)
            {
                return;
            }
            if (style == 7)
            {
                if (Main.tile[x, y + 1].active() && Main.tile[x, y + 1].type != 3 && Main.tile[x, y + 1].type != 51 && Main.tile[x, y + 1].type != 697 && Main.tile[x, y + 1].type != 61 && Main.tile[x, y + 1].type != 703 && Main.tile[x, y + 1].type != 73 && Main.tile[x, y + 1].type != 74 && Main.tile[x, y + 1].type != 184)
                {
                    return;
                }
                if (WorldGen.SolidTile(x, y - 1, false) && !Main.tile[x, y + 1].active())
                {
                    flag = true;
                }
            }
            else
            {
                if (Main.tile[x, y - 1].active() && Main.tile[x, y - 1].type != 3 && Main.tile[x, y - 1].type != 51 && Main.tile[x, y - 1].type != 697 && Main.tile[x, y - 1].type != 61 && Main.tile[x, y - 1].type != 703 && Main.tile[x, y - 1].type != 73 && Main.tile[x, y - 1].type != 74 && Main.tile[x, y - 1].type != 184)
                {
                    return;
                }
                if (style == 6)
                {
                    if (Main.tile[x, y + 1].nactive() && Main.tile[x, y + 1].type == 80 && !Main.tile[x - 1, y + 1].active() && !Main.tile[x + 1, y + 1].active())
                    {
                        flag = true;
                    }
                }
                else if (WorldGen.SolidTile(x, y + 1, false) && !Main.tile[x, y - 1].active())
                {
                    if (style == 5)
                    {
                        if (Main.tile[x, y].liquid == 255 && !Main.tile[x, y].lava() && !Main.tile[x, y].honey() && !Main.tile[x, y].shimmer())
{
                            flag = true;
                        }
                    }
                    else if (style >= 8 && style <= 11)
                    {
                        flag = true;
                    }
                    else if (Main.tile[x, y].liquid == 0)
                    {
                        if (style == 3 || style == 4)
{
                            if (Main.tile[x, y].wall == 0)
{
                                flag = true;
                            }
                        }
                        else
{
                            flag = true;
                        }
                    }
                }
            }
            if (flag)
            {
                Main.tile[x, y].type = 227;
                Main.tile[x, y].active(true);
                Main.tile[x, y].halfBrick(false);
                Main.tile[x, y].slope(0);
                Main.tile[x, y].frameY = 0;
                Main.tile[x, y].frameX = (short)(34 * style);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.halfBrick(), Terraria.Tile.honey(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Tile.shimmer(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.PlaceTile().