Terraria Decompiled: Terraria.WorldGen.CheckOnTable1x1
CheckOnTable1x1()
static void Terraria.WorldGen.CheckOnTable1x1 (int x, int y, int type) inline static
Definition at line 41782 of file WorldGen.cs.
        {
            Tile tile = Main.tile[x, y + 1];
            if (tile == null)
            {
                return;
            }
            if (tile.topSlope())
            {
                if (!TileID.Sets.Platforms[(int)tile.type])
                {
                    WorldGen.KillTile(x, y, false, false, false);
                    return;
                }
                if ((tile.blockType() != 3 || !Main.tile[x - 1, y + 1].active() || Main.tile[x - 1, y + 1].blockType() != 0 || !TileID.Sets.Platforms[(int)Main.tile[x - 1, y + 1].type]) && (tile.blockType() != 2 || !Main.tile[x + 1, y + 1].active() || Main.tile[x + 1, y + 1].blockType() != 0 || !TileID.Sets.Platforms[(int)Main.tile[x + 1, y + 1].type]))
                {
                    WorldGen.KillTile(x, y, false, false, false);
                    return;
                }
            }
            else
            {
                if (tile.halfBrick())
                {
                    WorldGen.KillTile(x, y, false, false, false);
                    return;
                }
                if (!WorldGen.AnchorValid(tile, AnchorType.Table) && (!tile.active() || !Main.tileTable[(int)tile.type]))
                {
                    if (type == 78)
                    {
                        if (!WorldGen.SolidTileAllowBottomSlope(x, y + 1))
{
                            WorldGen.KillTile(x, y, false, false, false);
                            return;
                        }
                    }
                    else
                    {
                        WorldGen.KillTile(x, y, false, false, false);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AnchorValid(), Terraria.Tile.blockType(), Terraria.Tile.halfBrick(), Terraria.WorldGen.KillTile(), Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.Main.tile, Terraria.Main.tileTable, Terraria.Tile.topSlope(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrame(), and Terraria.WorldGen.TileFrameImportant().