Terraria Decompiled: Terraria.WorldGen.TryGrowingAbigailsFlower
TryGrowingAbigailsFlower()
static bool Terraria.WorldGen.TryGrowingAbigailsFlower (int i, int j) inline static private
Definition at line 73522 of file WorldGen.cs.
        {
            if (Main.rand.Next(30) != 0)
            {
                return false;
            }
            int num = 1;
            if (Main.dontStarveWorld)
            {
                num = 2;
            }
            for (int k = 0; k < num; k++)
            {
                int num2 = WorldGen.genRand.Next(Math.Max(10, i - 10), Math.Min(Main.maxTilesX - 10, i + 10));
                int num3 = WorldGen.genRand.Next(Math.Max(10, j - 10), Math.Min(Main.maxTilesY - 10, j + 10));
                if (WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(num2, num3) && WorldGen.NoNearbyAbigailsFlower(num2, num3) && WorldGen.PlaceTile(num2, num3, 624, true, false, -1, 0))
                {
                    if (Main.netMode == 2 && Main.tile[num2, num3] != null && Main.tile[num2, num3].active())
                    {
                        NetMessage.SendTileSquare(-1, num2, num3, TileChangeType.None);
                    }
                    return true;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Main.dontStarveWorld, Terraria.WorldGen.genRand, Terraria.WorldGen.HasValidGroundForAbigailsFlowerBelowSpot(), System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.NoNearbyAbigailsFlower(), Terraria.WorldGen.PlaceTile(), Terraria.Main.rand, Terraria.NetMessage.SendTileSquare(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.UpdateWorld_OvergroundTile().