Terraria Decompiled: Terraria.WorldGen.CanUnderwaterPlantGrowHere
CanUnderwaterPlantGrowHere()
static bool Terraria.WorldGen.CanUnderwaterPlantGrowHere (ushort type, int x, int y, bool ignoreSelf) inline static
Definition at line 57262 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 50))
            {
                return false;
            }
            Tile tile = Framing.GetTileSafely(x, y);
            if (!ignoreSelf && tile.active())
            {
                return false;
            }
            for (int i = 0; i < 3; i++)
            {
                tile = Framing.GetTileSafely(x, y - i);
                if (tile.liquid == 0 || tile.liquidType() != 0)
                {
                    return false;
                }
            }
            Tile tileSafely = Framing.GetTileSafely(x, y + 1);
            if (!tileSafely.nactive())
            {
                return false;
            }
            if ((!TileID.Sets.Conversion.Sand[(int)tileSafely.type] || !WorldGen.TopEdgeCanBeAttachedTo(x, y + 1)) && type != tileSafely.type)
            {
                return false;
            }
            tile = Framing.GetTileSafely(x, y);
            ushort wall = tile.wall;
            return wall == 0 || wall - 63 <= 6 || wall - 80 <= 1;
        }
References Terraria.Tile.active(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Tile.nactive(), Terraria.ID.TileID.Sets.Conversion.Sand, Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.CheckUnderwaterPlant(), and Terraria.WorldGen.PlaceUnderwaterPlant().