Terraria Decompiled: Terraria.WorldGen.CheckPalmTree
CheckPalmTree()
static void Terraria.WorldGen.CheckPalmTree (int i, int j) inline static
Definition at line 52871 of file WorldGen.cs.
        {
            int num = -1;
            int num2 = -1;
            int type = (int)Main.tile[i, j].type;
            int frameX = (int)Main.tile[i, j].frameX;
            int frameY = (int)Main.tile[i, j].frameY;
            if (Main.tile[i, j - 1] != null && Main.tile[i, j - 1].active())
            {
                num = (int)Main.tile[i, j - 1].type;
            }
            if (Main.tile[i, j + 1] != null && Main.tile[i, j + 1].active())
            {
                num2 = (int)Main.tile[i, j + 1].type;
            }
            if (num2 == 53)
            {
                num2 = 53;
            }
            if (num2 == 234)
            {
                num2 = 53;
            }
            if (num2 == 116)
            {
                num2 = 53;
            }
            if (num2 == 112)
            {
                num2 = 53;
            }
            if (num2 != 53 && num2 != type)
            {
                WorldGen.KillTile(i, j, false, false, false);
            }
            if ((Main.tile[i, j].frameX == 66 || Main.tile[i, j].frameX == 220) && num2 != 53)
            {
                WorldGen.KillTile(i, j, false, false, false);
            }
            if (num != type && Main.tile[i, j].frameX <= 44)
            {
                Main.tile[i, j].frameX = (short)(WorldGen.genRand.Next(7, 10) * 22);
            }
            else if (num != type && Main.tile[i, j].frameX == 66)
            {
                Main.tile[i, j].frameX = 220;
            }
            if ((int)Main.tile[i, j].frameX != frameX && (int)Main.tile[i, j].frameY != frameY && frameX >= 0 && frameY >= 0)
            {
                WorldGen.TileFrame(i - 1, j, false, false);
                WorldGen.TileFrame(i + 1, j, false, false);
                WorldGen.TileFrame(i, j - 1, false, false);
                WorldGen.TileFrame(i, j + 1, false, false);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, int, Terraria.WorldGen.KillTile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.tile, Terraria.WorldGen.TileFrame(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().