Terraria Decompiled: Terraria.WorldGen.GetFruitForPot
GetFruitForPot()
static int Terraria.WorldGen.GetFruitForPot (int x, int y, int potStyle) inline static
Definition at line 55634 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 2))
            {
                return -1;
            }
            bool flag = potStyle >= 4 && potStyle <= 6;
            bool flag2 = (potStyle >= 7 && potStyle <= 9) || (potStyle >= 28 && potStyle <= 30);
            bool flag3 = potStyle >= 13 && potStyle <= 15;
            bool flag4 = potStyle >= 16 && potStyle <= 18;
            bool flag5 = potStyle >= 22 && potStyle <= 24;
            bool flag6 = (potStyle >= 25 && potStyle <= 27) || (potStyle >= 34 && potStyle <= 36);
            int num;
            if (flag)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 4286;
                }
                else
                {
                    num = 4295;
                }
            }
            else if (flag2)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 4294;
                }
                else
                {
                    num = 4292;
                }
            }
            else if (flag6)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 4283;
                }
                else
                {
                    num = 4287;
                }
            }
            else if (flag4)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 4284;
                }
                else
                {
                    num = 4289;
                }
            }
            else if (flag5)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 4296;
                }
                else
                {
                    num = 4285;
                }
            }
            else if (flag3)
            {
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num = 5277;
                }
                else
                {
                    num = 5278;
                }
            }
            else
            {
                int num2 = WorldGen.genRand.Next(5);
                if (num2 == 0)
                {
                    num = 4009;
                }
                else if (num2 == 1)
                {
                    num = 4293;
                }
                else if (num2 == 2)
                {
                    num = 4282;
                }
                else if (num2 == 3)
                {
                    num = 4290;
                }
                else
                {
                    num = 4291;
                }
            }
            return num;
        }
References Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), and Terraria.Utilities.UnifiedRandom.Next().
Referenced by Terraria.WorldGen.SpawnThingsFromPot().