Terraria Decompiled: Terraria.WorldGen.dropXmasTree
dropXmasTree()
static void Terraria.WorldGen.dropXmasTree (int x, int y, int obj) inline static
Definition at line 36798 of file WorldGen.cs.
        {
            int num = x;
            int num2 = y;
            if (Main.tile[x, y].frameX < 10)
            {
                num -= (int)Main.tile[x, y].frameX;
                num2 -= (int)Main.tile[x, y].frameY;
            }
            int num3 = 0;
            if ((Main.tile[num, num2].frameY & 1) == 1)
            {
                num3++;
            }
            if ((Main.tile[num, num2].frameY & 2) == 2)
            {
                num3 += 2;
            }
            if ((Main.tile[num, num2].frameY & 4) == 4)
            {
                num3 += 4;
            }
            int num4 = 0;
            if ((Main.tile[num, num2].frameY & 8) == 8)
            {
                num4++;
            }
            if ((Main.tile[num, num2].frameY & 16) == 16)
            {
                num4 += 2;
            }
            if ((Main.tile[num, num2].frameY & 32) == 32)
            {
                num4 += 4;
            }
            int num5 = 0;
            if ((Main.tile[num, num2].frameY & 64) == 64)
            {
                num5++;
            }
            if ((Main.tile[num, num2].frameY & 128) == 128)
            {
                num5 += 2;
            }
            if ((Main.tile[num, num2].frameY & 256) == 256)
            {
                num5 += 4;
            }
            if ((Main.tile[num, num2].frameY & 512) == 512)
            {
                num5 += 8;
            }
            int num6 = 0;
            if ((Main.tile[num, num2].frameY & 1024) == 1024)
            {
                num6++;
            }
            if ((Main.tile[num, num2].frameY & 2048) == 2048)
            {
                num6 += 2;
            }
            if ((Main.tile[num, num2].frameY & 4096) == 4096)
            {
                num6 += 4;
            }
            if ((Main.tile[num, num2].frameY & 8192) == 8192)
            {
                num6 += 8;
            }
            if (obj == 0 && num3 > 0)
            {
                int num7 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1874 + num3 - 1, 1, false, 0, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num7, 1f, 0f, 0f, 0, 0, 0);
                    return;
                }
            }
            else if (obj == 1 && num4 > 0)
            {
                int num8 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1878 + num4 - 1, 1, false, 0, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num8, 1f, 0f, 0f, 0, 0, 0);
                    return;
                }
            }
            else if (obj == 2 && num5 > 0)
            {
                int num9 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1884 + num5 - 1, 1, false, 0, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num9, 1f, 0f, 0f, 0, 0, 0);
                    return;
                }
            }
            else if (obj == 3 && num6 > 0)
            {
                int num10 = Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 16, 16, 1895 + num6 - 1, 1, false, 0, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(21, -1, -1, null, num10, 1f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.Main.netMode, Terraria.Item.NewItem(), System.obj, Terraria.NetMessage.SendData(), and Terraria.Main.tile.
Referenced by Terraria.WorldGen.KillTile_GetItemDrops(), and Terraria.Player.PlaceThing_XMasTreeTops().