Terraria Decompiled: Terraria.WorldGen.ConvertTreeAndGround_Branches
ConvertTreeAndGround_Branches()
static void Terraria.WorldGen.ConvertTreeAndGround_Branches (int x, int y, int newType) inline static private
Definition at line 53616 of file WorldGen.cs.
        {
            int num = 0;
            if ((WorldGen.IsTileATreeBranch(x - 1, y, out num) && num == 1) || (WorldGen.IsTileATreeRoot(x - 1, y, out num) && num == 1))
            {
                Main.tile[x - 1, y].type = (ushort)newType;
            }
            if ((WorldGen.IsTileATreeBranch(x + 1, y, out num) && num == -1) || (WorldGen.IsTileATreeRoot(x + 1, y, out num) && num == -1))
            {
                Main.tile[x + 1, y].type = (ushort)newType;
            }
        }
References Terraria.WorldGen.IsTileATreeBranch(), Terraria.WorldGen.IsTileATreeRoot(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.ConvertTreeAndGround().