Terraria Decompiled: Terraria.WorldGen.PaintTheMushrooms
PaintTheMushrooms()
static void Terraria.WorldGen.PaintTheMushrooms () inline static private
Definition at line 21424 of file WorldGen.cs.
        {
            int num = Main.maxTilesY - 20;
            byte b = (byte)WorldGen.genRand.Next(1, 13);
            if (WorldGen.remixWorldGen)
            {
                b = 2;
                num = Main.maxTilesY - 500;
                int num2 = WorldGen.genRand.Next(5, 31);
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num2 = WorldGen.genRand.Next(5, 16);
                }
                for (int i = 20; i < Main.maxTilesX - 20; i++)
                {
                    if (i % num2 == 0)
                    {
                        b += 1;
                        if (b > 12)
{
                            b = 1;
                        }
                    }
                    for (int j = Main.maxTilesY - 450; j < Main.maxTilesY - 20; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.active() && (tile.type == 70 || tile.type == 578 || tile.type == 190 || tile.type == 71 || tile.type == 528 || (tile.type == 519 && tile.frameY == 90)))
{
                            tile.color(b);
                        }
                        if (tile.wall == 80 || tile.wall == 74)
{
                            tile.wallColor(b);
                        }
                    }
                }
            }
            b = (byte)WorldGen.genRand.Next(1, 13);
            int num3 = 0;
            for (int k = 20; k < Main.maxTilesX - 20; k++)
            {
                for (int l = 20; l < num; l++)
                {
                    Tile tile2 = Main.tile[k, l];
                    if (tile2.active() && (tile2.type == 70 || tile2.type == 578 || tile2.type == 190 || tile2.type == 71 || tile2.type == 528 || (tile2.type == 519 && tile2.frameY == 90)))
                    {
                        tile2.color(b);
                        num3 = 10;
                    }
                    if (tile2.wall == 80 || tile2.wall == 74)
                    {
                        tile2.wallColor(b);
                        num3 = 10;
                    }
                }
                num3--;
                if (num3 == 0)
                {
                    b += (byte)WorldGen.genRand.Next(1, 3);
                    if (b > 12)
                    {
                        b = 1;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.WorldGen.genRand, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.remixWorldGen, Terraria.Main.tile, Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.WorldGen.FinishTenthAnniversaryWorldPaintTreesAndMushrooms().