Terraria Decompiled: Terraria.WorldGen.SolidTile2
SolidTile2() [3/3]
static bool Terraria.WorldGen.SolidTile2 (Tile testTile) inline static
Definition at line 70460 of file WorldGen.cs.
        {
            try
            {
                if (testTile == null)
                {
                    return true;
                }
                if (testTile.active() && Main.tileSolid[(int)testTile.type] && testTile.slope() == 0 && !testTile.halfBrick() && !testTile.inActive())
                {
                    return true;
                }
            }
            catch
            {
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.slope(), Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.AdvanceTargetPosition(), Terraria.NPC.AI(), Terraria.NPC.AI_006_Worms(), Terraria.NPC.AI_126_StatueMimic(), Terraria.WorldGen.CheckPot(), Terraria.WorldGen.CheckXmasTree(), Terraria.Player.FindSentryRestingSpot(), Terraria.Player.FindSharpTearsSpot(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.HandleFalling(), Terraria.NPC.IsThisAGoodPlaceForAStatueMimic(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move_NoObstruction(), Terraria.Player.PickSentryLandingSpot(), Terraria.WorldGen.Place1x1(), Terraria.WorldGen.Place1x2(), Terraria.WorldGen.Place1xX(), Terraria.WorldGen.Place2x1(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place2x2Horizontal(), Terraria.WorldGen.Place2xX(), Terraria.WorldGen.Place3x1(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.Place3x4(), Terraria.WorldGen.Place4x2(), Terraria.WorldGen.Place5x4(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.PlaceCannon(), Terraria.WorldGen.PlaceMan(), Terraria.WorldGen.PlaceSign(), Terraria.WorldGen.PlaceSmallPile(), Terraria.WorldGen.PlaceStatueTrap(), Terraria.WorldGen.PlaceWoman(), Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Spawn(), Terraria.GameContent.SmartCursorHelper.Step_Acorns(), Terraria.GameContent.SmartCursorHelper.Step_GemCorns(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryGetReachableTile(), and Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.Update().