Terraria Decompiled: Terraria.WorldGen.CheckTrapDoor
CheckTrapDoor()
static void Terraria.WorldGen.CheckTrapDoor (int x, int y, int type) inline static
Definition at line 50104 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int num = 0;
            int num2 = 0;
            Point point = default(Point);
            if (type == 387)
            {
                num = 2;
                num2 = 1;
                point = WorldGen.GetTopLeftAndStyles(ref x, ref y, num, num2, 18, 18);
                flag = flag || !WorldGen.CheckTileFrames(type, x, y, num, num2, point.X, 18, point.Y, 18) || !WorldGen.CheckTileAnchors(x, y, num, num2, 1, AnchorType.SolidTile);
            }
            if (type == 386)
            {
                num = 2;
                num2 = 2;
                point = WorldGen.GetTopLeftAndStyles(ref x, ref y, num, num2, 18, 18);
                flag = flag || !WorldGen.CheckTileFrames(type, x, y, num, num2, point.X, 18, point.Y, 18);
                if (point.X == 0)
                {
                    flag = flag || !WorldGen.CheckTileAnchors(x, y + 1, num, 1, 1, AnchorType.SolidTile);
                }
                else if (point.X == 1)
                {
                    flag = flag || !WorldGen.CheckTileAnchors(x, y, num, 1, 1, AnchorType.SolidTile);
                }
            }
            if (!flag)
            {
                return;
            }
            WorldGen.destroyObject = true;
            for (int i = x; i < x + num; i++)
            {
                for (int j = y; j < y + num2; j++)
                {
                    WorldGen.KillTile(i, j, false, false, false);
                }
            }
            int num3 = 3239;
            if (point.Y == 0)
            {
                num3 = 3239;
            }
            Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, num * 16, num2 * 16, num3, 1, false, 0, false);
            WorldGen.destroyObject = false;
            for (int k = x - 1; k < x + num + 1; k++)
            {
                for (int l = y - 1; l < y + num2 + 1; l++)
                {
                    WorldGen.TileFrame(k, l, false, false);
                }
            }
            WorldGen.CheckExploitDestroyQueue();
        }
References Terraria.WorldGen.CheckExploitDestroyQueue(), Terraria.WorldGen.CheckTileAnchors(), Terraria.WorldGen.CheckTileFrames(), Terraria.WorldGen.destroyObject, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.WorldGen.GetTopLeftAndStyles(), Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.WorldGen.TileFrame(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.TileFrameImportant().