Terraria Decompiled: Terraria.WorldGen.StartHardmode
StartHardmode()
static void Terraria.WorldGen.StartHardmode (bool force = false) inline static
Definition at line 29071 of file WorldGen.cs.
        {
            if (Main.netMode == 1 || (Main.hardMode && !force))
            {
                return;
            }
            Main.hardMode = true;
            WorldGen.TryProtectingSpawnedItems();
            WorldGen.TransformWorldOnBackgroundThread(new Action(WorldGen.initializeHardMode), delegate
            {
                ChatHelper.BroadcastChatMessage(NetworkText.FromKey(Lang.misc[15].Key, new object[0]), ChatColors.World, -1);
                AchievementsHelper.NotifyProgressionEvent(9);
                if (Main.netMode == 2)
                {
                    Netplay.ResetSections();
                }
                WorldGen.UndoSpawnedItemProtection();
            });
        }
References System.Action(), Terraria.Main.hardMode, Terraria.WorldGen.initializeHardMode(), Terraria.Main.netMode, Terraria.WorldGen.TransformWorldOnBackgroundThread(), Terraria.WorldGen.TryProtectingSpawnedItems(), and Terraria.WorldGen.UndoSpawnedItemProtection().
Referenced by Terraria.NPC.DoDeathEvents().