Terraria Decompiled: Terraria.WorldGen.initializeHardMode
initializeHardMode()
static void Terraria.WorldGen.initializeHardMode () inline static private
Definition at line 28919 of file WorldGen.cs.
        {
            if (Main.rand == null)
            {
                Main.rand = new UnifiedRandom((int)DateTime.Now.Ticks);
            }
            bool flag = true;
            if (Main.dualDungeonsSeed)
            {
                flag = false;
            }
            double num = (double)WorldGen.genRand.Next(300, 400) * 0.001;
            double num2 = (double)WorldGen.genRand.Next(200, 300) * 0.001;
            int num3 = (int)((double)Main.maxTilesX * num);
            int num4 = (int)((double)Main.maxTilesX * (1.0 - num));
            int num5 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num4 = (int)((double)Main.maxTilesX * num);
                num3 = (int)((double)Main.maxTilesX * (1.0 - num));
                num5 = -1;
            }
            int num6 = 1;
            if (Main.dungeonX < Main.maxTilesX / 2)
            {
                num6 = -1;
            }
            if (num6 < 0)
            {
                if (num4 < num3)
                {
                    num4 = (int)((double)Main.maxTilesX * num2);
                }
                else
                {
                    num3 = (int)((double)Main.maxTilesX * num2);
                }
            }
            else if (num4 > num3)
            {
                num4 = (int)((double)Main.maxTilesX * (1.0 - num2));
            }
            else
            {
                num3 = (int)((double)Main.maxTilesX * (1.0 - num2));
            }
            if (flag)
            {
                if (Main.remixWorld)
                {
                    int num7 = Main.maxTilesX / 7;
                    int num8 = Main.maxTilesX / 14;
                    if (Main.dungeonX < Main.maxTilesX / 2)
                    {
                        for (int i = Main.maxTilesX - num7 - num8; i < Main.maxTilesX; i++)
{
                            for (int j = (int)Main.worldSurface + WorldGen.genRand.Next(-1, 2); j < Main.maxTilesY - 10; j++)
{
                                if (i > Main.maxTilesX - num7)
{
                                    WorldGen.Convert(i, j, 2, true, true);
                                }
                                else if (TileID.Sets.Crimson[(int)Main.tile[i, j].type] || TileID.Sets.Corrupt[(int)Main.tile[i, j].type])
{
                                    WorldGen.Convert(i, j, 2, true, true);
                                }
                            }
                        }
                    }
                    else
                    {
                        for (int k = 0; k < num7 + num8; k++)
{
                            for (int l = (int)Main.worldSurface + WorldGen.genRand.Next(-1, 2); l < Main.maxTilesY - 10; l++)
{
                                if (k < num7)
{
                                    WorldGen.Convert(k, l, 2, true, true);
                                }
                                else if (TileID.Sets.Crimson[(int)Main.tile[k, l].type] || TileID.Sets.Corrupt[(int)Main.tile[k, l].type])
{
                                    WorldGen.Convert(k, l, 2, true, true);
                                }
                            }
                        }
                    }
                }
                else
                {
                    WorldGen.GERunner(num3, 0, (double)(3 * num5), 5.0, true);
                    WorldGen.GERunner(num4, 0, (double)(3 * -(double)num5), 5.0, false);
                }
            }
            double num9 = (double)Main.maxTilesX / 4200.0;
            int m = (int)(25.0 * num9);
            ShapeData shapeData = new ShapeData();
            int num10 = 0;
            while (m > 0)
            {
                if (++num10 % 15000 == 0)
                {
                    m--;
                }
                Point point;
                if (Main.worldSurface > 100.0)
                {
                    point = WorldGen.RandomWorldPoint((int)Main.worldSurface - 100, 1, 190, 1);
                }
                else
                {
                    point = WorldGen.RandomWorldPoint(20, 1, 190, 1);
                }
                Tile tile = Main.tile[point.X, point.Y];
                Tile tile2 = Main.tile[point.X, point.Y - 1];
                ushort num11 = 0;
                if (TileID.Sets.Crimson[(int)tile.type])
                {
                    num11 = (ushort)(192 + WorldGen.genRand.Next(4));
                }
                else if (TileID.Sets.Corrupt[(int)tile.type])
                {
                    num11 = (ushort)(188 + WorldGen.genRand.Next(4));
                }
                else if (TileID.Sets.Hallow[(int)tile.type])
                {
                    num11 = (ushort)(200 + WorldGen.genRand.Next(4));
                }
                if (tile.active() && num11 != 0 && !tile2.active())
                {
                    bool flag2 = WorldUtils.Gen(new Point(point.X, point.Y - 1), new ShapeFloodFill(1000), Actions.Chain(new GenAction[]
                    {
                        new Modifiers.IsNotSolid(),
                        new Modifiers.OnlyWalls(new ushort[]
{
                            0, 54, 55, 56, 57, 58, 59, 61, 185, 212,
                            213, 214, 215, 2, 196, 197, 198, 199, 15, 40,
                            71, 64, 204, 205, 206, 207, 208, 209, 210, 211,
                            71
                        }),
                        new Actions.Blank().Output(shapeData)
                    }));
                    if (shapeData.Count > 50 && flag2)
                    {
                        WorldUtils.Gen(new Point(point.X, point.Y), new ModShapes.OuterOutline(shapeData, true, true), new Actions.PlaceWall(num11, true));
                        m--;
                    }
                    shapeData.Clear();
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldBuilding.ShapeData.Clear(), Terraria.WorldGen.Convert(), Terraria.ID.TileID.Sets.Corrupt, Terraria.WorldBuilding.ShapeData.Count, Terraria.ID.TileID.Sets.Crimson, Terraria.Main.dualDungeonsSeed, Terraria.Main.dungeonX, Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.WorldGen.genRand, Terraria.WorldGen.GERunner(), Terraria.ID.TileID.Sets.Hallow, int, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), System.DateTime.Now, Terraria.WorldBuilding.GenAction.Output(), Terraria.Main.rand, Terraria.WorldGen.RandomWorldPoint(), Terraria.Main.remixWorld, System.DateTime.Ticks, Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.SecretSeed.DoStartInHardmode(), and Terraria.WorldGen.StartHardmode().