Terraria Decompiled: Terraria.WorldGen.SwitchMonolith
SwitchMonolith()
static void Terraria.WorldGen.SwitchMonolith (int i, int j) inline static
Definition at line 49489 of file WorldGen.cs.
        {
            int num = 2;
            int num2 = 3;
            ushort type = Main.tile[i, j].type;
            if (type == 733)
            {
                num = 3;
            }
            int k;
            for (k = (int)(Main.tile[i, j].frameX / 18); k >= num; k -= num)
            {
            }
            int l;
            for (l = (int)(Main.tile[i, j].frameY / 18); l >= num2; l -= num2)
            {
            }
            int num3 = i - k;
            int num4 = j - l;
            for (int m = num3; m < num3 + num; m++)
            {
                for (int n = num4; n < num4 + num2; n++)
                {
                    if (Main.tile[m, n] == null)
                    {
                        Main.tile[m, n] = new Tile();
                    }
                    Tile tile = Main.tile[m, n];
                    if (tile.active())
                    {
                        if (tile.type == 410)
{
                            if (tile.frameY < 56)
{
                                Tile tile2 = tile;
                                tile2.frameY += 56;
                            }
                            else
{
                                Tile tile3 = tile;
                                tile3.frameY -= 56;
                            }
                        }
                        else if (tile.type == 480)
{
                            if (tile.frameY < 54)
{
                                Tile tile4 = tile;
                                tile4.frameY += 54;
                            }
                            else
{
                                Tile tile5 = tile;
                                tile5.frameY -= 54;
                            }
                        }
                        else if (tile.type == 509)
{
                            if (tile.frameY < 54)
{
                                Tile tile6 = tile;
                                tile6.frameY += 54;
                            }
                            else
{
                                Tile tile7 = tile;
                                tile7.frameY -= 54;
                            }
                        }
                        else if (tile.type == 657)
{
                            if (tile.frameY < 54)
{
                                Tile tile8 = tile;
                                tile8.frameY += 54;
                            }
                            else
{
                                Tile tile9 = tile;
                                tile9.frameY -= 54;
                            }
                        }
                        else if (tile.type == 658)
{
                            short num5 = 54;
                            short num6 = 3;
                            short num7 = num5 * num6;
                            Tile tile10 = tile;
                            tile10.frameY += num5;
                            if (tile.frameY >= num7)
{
                                Tile tile11 = tile;
                                tile11.frameY -= num7;
                            }
                        }
                        else if (tile.type == 720)
{
                            if (tile.frameY < 54)
{
                                Tile tile12 = tile;
                                tile12.frameY += 54;
                            }
                            else
{
                                Tile tile13 = tile;
                                tile13.frameY -= 54;
                            }
                        }
                        else if (tile.type == 721)
{
                            if (tile.frameY < 54)
{
                                Tile tile14 = tile;
                                tile14.frameY += 54;
                            }
                            else
{
                                Tile tile15 = tile;
                                tile15.frameY -= 54;
                            }
                        }
                        else if (tile.type == 725)
{
                            if (tile.frameY < 54)
{
                                Tile tile16 = tile;
                                tile16.frameY += 54;
                            }
                            else
{
                                Tile tile17 = tile;
                                tile17.frameY -= 54;
                            }
                        }
                        else if (tile.type == 733)
{
                            if (tile.frameY < 54)
{
                                Tile tile18 = tile;
                                tile18.frameY += 54;
                            }
                            else
{
                                Tile tile19 = tile;
                                tile19.frameY -= 54;
                            }
                        }
                    }
                }
            }
            if (Wiring.running)
            {
                for (int num8 = num3; num8 < num3 + num; num8++)
                {
                    for (int num9 = num4; num9 < num4 + num2; num9++)
                    {
                        Wiring.SkipWire(num8, num9);
                    }
                }
            }
            NetMessage.SendTileSquare(-1, num3, num4, num, num2, TileChangeType.None);
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Wiring.running, Terraria.NetMessage.SendTileSquare(), Terraria.Wiring.SkipWire(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Wiring.HitWireSingle(), Terraria.WorldGen.SkyblockIsland(), and Terraria.Player.TileInteractionsUse().