Terraria Decompiled: Terraria.WorldGen.ReplaceWall
ReplaceWall()
static bool Terraria.WorldGen.ReplaceWall (int x, int y, ushort targetWall) inline static
Definition at line 61491 of file WorldGen.cs.
        {
            if (targetWall >= WallID.Count)
            {
                return false;
            }
            Tile tile = Main.tile[x, y];
            if (tile.wall == 0 || targetWall == 0 || tile.wall == 350)
            {
                return false;
            }
            if (WorldGen.KillWall_CheckFailure(false, tile))
            {
                return false;
            }
            int num = 10;
            for (int i = 0; i < num; i++)
            {
                WorldGen.KillWall_MakeWallDust(x, y, tile);
            }
            WorldGen.KillWall_PlaySounds(x, y, tile);
            WorldGen.KillWall_DropItems(x, y, tile);
            tile.wall = targetWall;
            tile.ClearWallPaintAndCoating();
            WorldGen.SquareWallFrame(x, y, true);
            return true;
        }
References Terraria.Tile.ClearWallPaintAndCoating(), Terraria.ID.WallID.Count, Terraria.WorldGen.KillWall_CheckFailure(), Terraria.WorldGen.KillWall_DropItems(), Terraria.WorldGen.KillWall_MakeWallDust(), Terraria.WorldGen.KillWall_PlaySounds(), Terraria.WorldGen.SquareWallFrame(), Terraria.Main.tile, and Terraria.Tile.wall.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.Player.PlaceThing_TryReplacingWalls().