Terraria Decompiled: Terraria.WorldGen.CheckCactus
CheckCactus()
static bool Terraria.WorldGen.CheckCactus (int i, int j) inline static
Definition at line 52612 of file WorldGen.cs.
        {
            int num = j;
            int num2 = i;
            while (Main.tile[num2, num] != null && Main.tile[num2, num].active() && Main.tile[num2, num].type == 80)
            {
                num++;
                if (Main.tile[num2, num] == null)
                {
                    return false;
                }
                if (!Main.tile[num2, num].active() || Main.tile[num2, num].type != 80)
                {
                    if (Main.tile[num2 - 1, num] != null && Main.tile[num2 - 1, num].active() && Main.tile[num2 - 1, num].type == 80 && Main.tile[num2 - 1, num - 1] != null && Main.tile[num2 - 1, num - 1].active() && Main.tile[num2 - 1, num - 1].type == 80 && num2 >= i)
                    {
                        num2--;
                    }
                    if (Main.tile[num2 + 1, num] != null && Main.tile[num2 + 1, num].active() && Main.tile[num2 + 1, num].type == 80 && Main.tile[num2 + 1, num - 1] != null && Main.tile[num2 + 1, num - 1].active() && Main.tile[num2 + 1, num - 1].type == 80 && num2 <= i)
                    {
                        num2++;
                    }
                }
            }
            if (!Main.tile[num2, num].nactive() || Main.tile[num2, num].halfBrick() || Main.tile[num2, num].slope() != 0 || (Main.tile[num2, num].type != 53 && Main.tile[num2, num].type != 112 && Main.tile[num2, num].type != 116 && Main.tile[num2, num].type != 234))
            {
                WorldGen.KillTile(i, j, false, false, false);
                return true;
            }
            if (i != num2)
            {
                if ((!Main.tile[i, j + 1].active() || Main.tile[i, j + 1].type != 80) && (!Main.tile[i - 1, j].active() || Main.tile[i - 1, j].type != 80) && (!Main.tile[i + 1, j].active() || Main.tile[i + 1, j].type != 80))
                {
                    WorldGen.KillTile(i, j, false, false, false);
                    return true;
                }
            }
            else if (i == num2 && (!Main.tile[i, j + 1].active() || (Main.tile[i, j + 1].type != 80 && Main.tile[i, j + 1].type != 53 && Main.tile[i, j + 1].type != 112 && Main.tile[i, j + 1].type != 116 && Main.tile[i, j + 1].type != 234)))
            {
                WorldGen.KillTile(i, j, false, false, false);
                return true;
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.WorldGen.KillTile(), Terraria.Tile.nactive(), Terraria.Tile.slope(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CactusFrame(), and Terraria.WorldGen.TileFrame().