Terraria Decompiled: Terraria.WorldGen.FindLowestCloud
FindLowestCloud()
static int Terraria.WorldGen.FindLowestCloud () inline static private
Definition at line 22465 of file WorldGen.cs.
        {
            if (WorldGen.SecretSeed.noSurface.Enabled)
            {
                GenVars.lowestCloud = 150;
            }
            if (GenVars.lowestCloud > -1)
            {
                return GenVars.lowestCloud;
            }
            int num = 0;
            int num2 = 20;
            while ((double)num2 < Main.worldSurface)
            {
                for (int i = 20; i < Main.maxTilesX - 20; i++)
                {
                    if (Main.tile[i, num2].active() && TileID.Sets.Clouds[(int)Main.tile[i, num2].type])
                    {
                        num = num2;
                        break;
                    }
                }
                num2++;
            }
            GenVars.lowestCloud = num;
            return num;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Clouds, Terraria.WorldBuilding.GenVars.lowestCloud, Terraria.WorldGen.SecretSeed.noSurface, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.WorldGen.SecretSeed.DoSurfaceIsDesertFinish(), Terraria.WorldGen.DungeonDesertCleanup(), and Terraria.WorldGen.GrowLivingTree().