Terraria Decompiled: Terraria.WorldGen.ScoreRoom
ScoreRoom()
static void Terraria.WorldGen.ScoreRoom (int ignoreNPC = -1, int npcTypeAskingToScoreRoom = -1, IRoomCheckFeedback feedback = null) inline static
Definition at line 1627 of file WorldGen.cs.
        {
            if (feedback == null)
            {
                feedback = NoRoomCheckFeedback.WithText;
            }
            WorldGen.roomOccupied = false;
            WorldGen.roomHasStandingSpace = false;
            WorldGen.roomEvil = false;
            WorldGen.sharedRoomX = -1;
            if (WorldGen.ScoreRoom_IsThisRoomOccupiedBySomeone(ignoreNPC, npcTypeAskingToScoreRoom))
            {
                WorldGen.roomOccupied = true;
                WorldGen.hiScore = -1;
                return;
            }
            WorldGen.hiScore = 0;
            int num = 50;
            int num2;
            int num3;
            int num4;
            int num5;
            WorldGen.Housing_GetTestedRoomBounds(out num2, out num3, out num4, out num5);
            int[] array = new int[(int)TileID.Count];
            WorldGen.CountTileTypesInArea(array, num2 + 1, num3 - 1, num4 + 2, num5 + 1);
            int num6 = -WorldGen.GetTileTypeCountByCategory(array, TileScanGroup.TotalGoodEvil);
            if (num6 < 50)
            {
                num6 = 0;
            }
            num -= num6;
            if (num6 > 0)
            {
                WorldGen.roomEvil = true;
            }
            if (num <= -250)
            {
                WorldGen.hiScore = num;
                return;
            }
            num2 = WorldGen.roomX1;
            num3 = WorldGen.roomX2;
            num4 = WorldGen.roomY1;
            num5 = WorldGen.roomY2;
            for (int i = num2 + 1; i < num3; i++)
            {
                for (int j = num4 + 2; j < num5 + 2; j++)
                {
                    if (Main.tile[i, j].nactive() && WorldGen.ScoreRoom_CanBeHomeSpot(i, j) && Main.tileSolid[(int)Main.tile[i, j].type] && !Collision.SolidTiles(i - 1, i + 1, j - 3, j - 1) && Main.tile[i - 1, j].nactive() && Main.tileSolid[(int)Main.tile[i - 1, j].type] && Main.tile[i + 1, j].nactive() && Main.tileSolid[(int)Main.tile[i + 1, j].type])
                    {
                        int num7 = num;
                        int num8 = 0;
                        int num9 = 0;
                        for (int k = i - 2; k < i + 3; k++)
{
                            for (int l = j - 4; l < j; l++)
{
                                Tile tile = Main.tile[k, l];
                                if (tile.nactive() && !TileID.Sets.IgnoredInHouseScore[(int)tile.type] && (tile.type != 11 || WorldGen.IsOpenDoorAnchorFrame(k, l)))
{
                                    if (k == i)
{
                                        num8++;
                                    }
                                    else if (TileID.Sets.BasicChest[(int)tile.type])
{
                                        num9++;
                                    }
                                    else if (tile.type == 10 || tile.type == 388)
{
                                        num7 -= 20;
                                    }
                                    else if (WorldGen.IsOpenDoorAnchorFrame(k, l) || tile.type == 389)
{
                                        num7 -= 20;
                                    }
                                    else if (Main.tileSolid[(int)tile.type])
{
                                        num7 -= 5;
                                    }
                                    else
{
                                        num7 += 5;
                                    }
                                }
                            }
                        }
                        if (num7 > 0)
{
                            WorldGen.roomHasStandingSpace = true;
                        }
                        if (WorldGen.sharedRoomX >= 0 && num7 >= 1 && Math.Abs(WorldGen.sharedRoomX - i) < 3)
{
                            num7 = 1;
                        }
                        if (num7 > 0 && num9 > 0)
{
                            num7 -= 30 * num9;
                            if (num7 < 1)
{
                                num7 = 1;
                            }
                        }
                        if (num7 > 0 && num8 > 0)
{
                            num7 -= 15 * num8;
                            if (num7 < 1)
{
                                num7 = 1;
                            }
                        }
                        feedback.ReportScore(i, j, num7);
                        if (num7 > WorldGen.hiScore)
{
                            bool flag = WorldGen.Housing_CheckIfInRoom(i, j);
                            bool[] array2 = new bool[3];
                            for (int m = 1; m <= 3; m++)
{
                                if (!Main.tile[i, j - m].active() || !Main.tileSolid[(int)Main.tile[i, j - m].type])
{
                                    array2[m - 1] = true;
                                }
                                if (!WorldGen.Housing_CheckIfInRoom(i, j - m))
{
                                    array2[m - 1] = false;
                                }
                            }
                            bool[] array3 = array2;
                            for (int n = 0; n < array3.Length; n++)
{
                                if (!array3[n])
{
                                    flag = false;
                                    break;
                                }
                            }
                            if (flag && WorldGen.Housing_CheckIfInRoom(i, j - 1))
{
                                feedback.SetAsHighScore(i, j, num7);
                                WorldGen.hiScore = num7;
                                WorldGen.bestX = i;
                                WorldGen.bestY = j;
                            }
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), System.array, Terraria.ID.TileID.Sets.BasicChest, Terraria.ID.TileID.Count, Terraria.WorldGen.CountTileTypesInArea(), Terraria.WorldGen.GetTileTypeCountByCategory(), Terraria.WorldGen.hiScore, Terraria.WorldGen.Housing_CheckIfInRoom(), Terraria.WorldGen.Housing_GetTestedRoomBounds(), Terraria.ID.TileID.Sets.IgnoredInHouseScore, int, Terraria.WorldGen.IsOpenDoorAnchorFrame(), Terraria.Tile.nactive(), Terraria.WorldGen.roomX1, Terraria.WorldGen.roomX2, Terraria.WorldGen.roomY1, Terraria.WorldGen.roomY2, Terraria.WorldGen.ScoreRoom_CanBeHomeSpot(), Terraria.WorldGen.ScoreRoom_IsThisRoomOccupiedBySomeone(), Terraria.WorldGen.sharedRoomX, Terraria.Collision.SolidTiles(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.type, and Terraria.DataStructures.NoRoomCheckFeedback.WithText.
Referenced by Terraria.WorldGen.MoveTownNPC(), Terraria.WorldGen.QuickFindHome(), and Terraria.WorldGen.SpawnTownNPC().