Terraria Decompiled: Terraria.WorldGen.LiquidInteractionsCleanup
LiquidInteractionsCleanup()
static void Terraria.WorldGen.LiquidInteractionsCleanup () inline static
Definition at line 20805 of file WorldGen.cs.
        {
            for (int i = 1; i < Main.maxTilesX - 1 - 1; i++)
            {
                for (int j = 1; j < Main.maxTilesY - 1 - 1; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile.active() && (tile.type == 56 || tile.type == 659))
                    {
                        tile.liquid = 0;
                        tile.liquidType(0);
                        Tile tile2 = Main.tile[i - 1, j];
                        Tile tile3 = Main.tile[i + 1, j];
                        Tile tile4 = Main.tile[i, j - 1];
                        Tile tile5 = Main.tile[i, j + 1];
                        object obj = ((!tile2.active() && tile2.liquid > 0) ? ((int)tile2.liquidType()) : (-1));
                        int num = ((!tile3.active() && tile3.liquid > 0) ? ((int)tile3.liquidType()) : (-1));
                        int num2 = ((!tile4.active() && tile4.liquid > 0) ? ((int)tile4.liquidType()) : (-1));
                        int num3 = ((!tile5.active() && tile5.liquid > 0) ? ((int)tile5.liquidType()) : (-1));
                        int num4 = 0;
                        int num5 = 0;
                        int num6 = 0;
                        int num7 = 0;
                        object obj2 = obj;
                        if (obj2 == null)
{
                            num4++;
                        }
                        if (num == 0)
{
                            num4++;
                        }
                        if (num2 == 0)
{
                            num4++;
                        }
                        if (num3 == 0)
{
                            num4++;
                        }
                        if (obj2 == 1)
{
                            num5++;
                        }
                        if (num == 1)
{
                            num5++;
                        }
                        if (num2 == 1)
{
                            num5++;
                        }
                        if (num3 == 1)
{
                            num5++;
                        }
                        if (obj2 == 2)
{
                            num6++;
                        }
                        if (num == 2)
{
                            num6++;
                        }
                        if (num2 == 2)
{
                            num6++;
                        }
                        if (num3 == 2)
{
                            num6++;
                        }
                        if (obj2 == 3)
{
                            num7++;
                        }
                        if (num == 3)
{
                            num7++;
                        }
                        if (num2 == 3)
{
                            num4++;
                        }
                        if (num3 == 3)
{
                            num7++;
                        }
                        if ((num4 <= 0 || (num5 <= 0 && num6 <= 0 && num7 <= 0)) && (num5 <= 0 || (num4 <= 0 && num6 <= 0 && num7 <= 0)) && (num6 <= 0 || (num4 <= 0 && num5 <= 0 && num7 <= 0)) && (num7 <= 0 || (num4 <= 0 && num5 <= 0 && num6 <= 0)))
{
                            short num8 = 0;
                            if (num4 == 0 && num5 == 0 && num6 == 0 && num7 == 0)
{
                                ushort type = tile.type;
                                if (type != 56)
{
                                    if (type == 659)
{
                                        num8 = 3;
                                    }
                                }
                                else
{
                                    num8 = 1;
                                }
                            }
                            if (num4 > 0)
{
                                num8 = 0;
                            }
                            else if (num5 > 0)
{
                                num8 = 1;
                            }
                            else if (num6 > 0)
{
                                num8 = 2;
                            }
                            else if (num7 > 0)
{
                                num8 = 3;
                            }
                            tile.ClearEverything();
                            tile.liquid = byte.MaxValue;
                            tile.liquidType((int)num8);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.ClearEverything(), Terraria.Tile.liquidType(), System.obj, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.Liquid.QuickWater().