Terraria Decompiled: Terraria.WorldGen.PoundTile
PoundTile()
static bool Terraria.WorldGen.PoundTile (int i, int j) inline static
Definition at line 81488 of file WorldGen.cs.
        {
            if (!WorldGen.CanPoundTile(i, j))
            {
                return false;
            }
            if (!Main.tile[i, j].halfBrick())
            {
                Main.tile[i, j].halfBrick(true);
            }
            else
            {
                Main.tile[i, j].halfBrick(false);
            }
            if (!WorldGen.isGeneratingOrLoadingWorld)
            {
                WorldGen.KillTile(i, j, true, true, false);
                SoundEngine.PlaySound(0, i * 16, j * 16, 1, 1f, 0f);
                WorldGen.SquareTileFrame(i, j, true);
                if (!Main.tile[i, j].halfBrick())
                {
                    Rectangle rectangle = new Rectangle(i * 16, j * 16, 16, 16);
                    for (int k = 0; k < 255; k++)
                    {
                        if (Main.player[k].active && !Main.player[k].dead && rectangle.Intersects(new Rectangle((int)Main.player[k].position.X, (int)Main.player[k].position.Y, Main.player[k].width, Main.player[k].height)))
{
                            Main.player[k].gfxOffY += Main.player[k].position.Y + (float)Main.player[k].height - (float)rectangle.Y;
                            Main.player[k].position.Y = (float)(rectangle.Y - Main.player[k].height);
                        }
                    }
                }
            }
            return true;
        }
References Terraria.Player.active, Terraria.WorldGen.CanPoundTile(), Terraria.Player.dead, Terraria.Player.gfxOffY, Terraria.Tile.halfBrick(), Terraria.Entity.height, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.KillTile(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Rectangle.Y, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall(), Terraria.MessageBuffer.GetData(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), and Terraria.WorldGen.PoundPlatform().