Terraria Decompiled: Terraria.WorldGen.CheckCatTail
CheckCatTail()
static void Terraria.WorldGen.CheckCatTail (int x, int j) inline static
Definition at line 57466 of file WorldGen.cs.
        {
            if (Main.tile[x, j] == null)
            {
                return;
            }
            bool flag = false;
            int num = j;
            while ((!Main.tile[x, num].active() || !Main.tileSolid[(int)Main.tile[x, num].type] || Main.tileSolidTop[(int)Main.tile[x, num].type]) && num < Main.maxTilesY - 50)
            {
                if (Main.tile[x, num].active() && Main.tile[x, num].type != 519)
                {
                    flag = true;
                }
                if (!Main.tile[x, num].active())
                {
                    break;
                }
                num++;
                if (Main.tile[x, num] == null)
                {
                    return;
                }
            }
            int num2 = num - 1;
            if (Main.tile[x, num2] == null)
            {
                return;
            }
            while (Main.tile[x, num2] != null && Main.tile[x, num2].liquid > 0 && num2 > 50)
            {
                if ((Main.tile[x, num2].active() && Main.tile[x, num2].type != 519) || Main.tile[x, num2].liquidType() != 0)
                {
                    flag = true;
                }
                num2--;
                if (Main.tile[x, num2] == null)
                {
                    return;
                }
            }
            num2++;
            if (Main.tile[x, num2] == null)
            {
                return;
            }
            int num3 = num2;
            int num4 = WorldGen.catTailDistance;
            if (num - num3 > num4)
            {
                flag = true;
            }
            int type = (int)Main.tile[x, num].type;
            int num5 = -1;
            if (type == 2 || type == 477)
            {
                num5 = 0;
            }
            else if (type == 53)
            {
                num5 = 18;
            }
            else if (type == 199 || type == 662 || type == 234)
            {
                num5 = 54;
            }
            else if (type == 23 || type == 661 || type == 112)
            {
                num5 = 72;
            }
            else if (type == 70)
            {
                num5 = 90;
            }
            if (!Main.tile[x, num].nactive())
            {
                flag = true;
            }
            if (num5 < 0)
            {
                flag = true;
            }
            num2 = num - 1;
            if (Main.tile[x, num2] != null && !Main.tile[x, num2].active())
            {
                for (int i = num2; i >= num3; i--)
                {
                    if (Main.tile[x, i] == null)
                    {
                        return;
                    }
                    if (Main.tile[x, i].active() && Main.tile[x, i].type == 519)
                    {
                        num2 = i;
                        break;
                    }
                }
            }
            while (Main.tile[x, num2] != null && Main.tile[x, num2].active() && Main.tile[x, num2].type == 519)
            {
                num2--;
            }
            num2++;
            if (Main.tile[x, num - 1] != null && Main.tile[x, num - 1].liquid < 127 && (WorldGen.isGeneratingOrLoadingWorld || WorldGen.genRand.Next(4) == 0))
            {
                flag = true;
            }
            if (Main.tile[x, num2] != null && Main.tile[x, num2].frameX >= 180 && Main.tile[x, num2].liquid > 127 && (WorldGen.isGeneratingOrLoadingWorld || WorldGen.genRand.Next(4) == 0))
            {
                flag = true;
            }
            if (Main.tile[x, num2] != null && Main.tile[x, num - 1] != null && Main.tile[x, num2].frameX > 18)
            {
                if (Main.tile[x, num - 1].frameX < 36 || Main.tile[x, num - 1].frameX > 72)
                {
                    flag = true;
                }
                else if (Main.tile[x, num2].frameX < 90)
                {
                    flag = true;
                }
                else if (Main.tile[x, num2].frameX >= 108 && Main.tile[x, num2].frameX <= 162)
                {
                    Main.tile[x, num2].frameX = 90;
                }
            }
            if (num > num2 + 4 && Main.tile[x, num2 + 4] != null && Main.tile[x, num2 + 3] != null && Main.tile[x, num2 + 4].liquid == 0 && Main.tile[x, num2 + 3].type == 519)
            {
                flag = true;
            }
            if (flag)
            {
                int num6 = num3;
                if (num2 < num3)
                {
                    num6 = num2;
                }
                num6 -= 4;
                for (int k = num6; k <= num; k++)
                {
                    if (Main.tile[x, k] != null && Main.tile[x, k].active() && Main.tile[x, k].type == 519)
                    {
                        WorldGen.KillTile(x, k, false, false, false);
                        if (Main.netMode == 2)
{
                            NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)k, 0f, 0, 0, 0);
                        }
                        WorldGen.SquareTileFrame(x, k, true);
                    }
                }
                return;
            }
            if (num5 != (int)Main.tile[x, num2].frameY)
            {
                for (int l = num2; l < num; l++)
                {
                    if (Main.tile[x, l] != null && Main.tile[x, l].active() && Main.tile[x, l].type == 519)
                    {
                        Main.tile[x, l].frameY = (short)num5;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, x, num2, TileChangeType.None);
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.catTailDistance, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, int, Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesY, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().