Terraria Decompiled: Terraria.WorldGen.PlaceLilyPad
PlaceLilyPad()
static bool Terraria.WorldGen.PlaceLilyPad (int x, int j) inline static
Definition at line 57804 of file WorldGen.cs.
        {
            int num = j;
            if (x < 50 || x > Main.maxTilesX - 50 || num < 50 || num > Main.maxTilesY - 50)
            {
                return false;
            }
            if (Main.tile[x, num].active() || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
            {
                return false;
            }
            while (Main.tile[x, num].liquid > 0 && num > 50)
            {
                num--;
            }
            num++;
            if (Main.tile[x, num].active() || Main.tile[x, num - 1].active() || Main.tile[x, num].liquid == 0 || Main.tile[x, num].liquidType() != 0)
            {
                return false;
            }
            if (Main.tile[x, num].wall != 0 && Main.tile[x, num].wall != 15 && Main.tile[x, num].wall != 70 && (Main.tile[x, num].wall < 63 || Main.tile[x, num].wall > 68))
            {
                return false;
            }
            int num2 = 5;
            int num3 = 0;
            for (int i = x - num2; i <= x + num2; i++)
            {
                for (int k = num - num2; k <= num + num2; k++)
                {
                    if (Main.tile[i, k].active() && Main.tile[i, k].type == 518)
                    {
                        num3++;
                    }
                }
            }
            if (num3 > 3)
            {
                return false;
            }
            int num4 = num;
            while ((!Main.tile[x, num4].active() || !Main.tileSolid[(int)Main.tile[x, num4].type] || Main.tileSolidTop[(int)Main.tile[x, num4].type]) && num4 < Main.maxTilesY - 50)
            {
                if (Main.tile[x, num4].active() && Main.tile[x, num4].type == 519)
                {
                    return false;
                }
                num4++;
            }
            int num5 = 12;
            if (num4 - num > num5)
            {
                return false;
            }
            if (num4 - num < 3)
            {
                return false;
            }
            int type = (int)Main.tile[x, num4].type;
            int num6 = -1;
            if (type == 2 || type == 477)
            {
                num6 = 0;
            }
            if (type == 109 || type == 492 || type == 116)
            {
                num6 = 18;
            }
            if (type == 60)
            {
                num6 = 36;
            }
            if (num6 < 0)
            {
                return false;
            }
            byte b = Main.tile[x, num4].color();
            Main.tile[x, num].active(true);
            Main.tile[x, num].type = 518;
            Main.tile[x, num].color(b);
            if (WorldGen.genRand.Next(2) == 0)
            {
                Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(3));
            }
            else if (WorldGen.genRand.Next(15) == 0)
            {
                Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(18));
            }
            else
            {
                int num7 = Main.maxTilesX / 5;
                if (x < num7)
                {
                    Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(6, 9));
                }
                else if (x < num7 * 2)
                {
                    Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(9, 12));
                }
                else if (x < num7 * 3)
                {
                    Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(3, 6));
                }
                else if (x < num7 * 4)
                {
                    Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(15, 18));
                }
                else
                {
                    Main.tile[x, num].frameX = (short)(18 * WorldGen.genRand.Next(12, 15));
                }
            }
            Main.tile[x, num].frameY = (short)num6;
            Main.tile[x, num].halfBrick(false);
            Main.tile[x, num].slope(0);
            WorldGen.SquareTileFrame(x, num, true);
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Tile.slope(), Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.PlaceTile().