Terraria Decompiled: Terraria.WorldGen.AddBuriedChest
AddBuriedChest() [2/3]
static bool Terraria.WorldGen.AddBuriedChest (int i, int j, out Point chestLocation, int mainItemInChest = 0, bool notNearOtherChests = false, int chestStyle = -1, bool trySlope = false, ushort chestTileType = 0) inline static
Definition at line 33288 of file WorldGen.cs.
        {
            chestLocation = Point.Zero;
            if (chestTileType == 0)
            {
                chestTileType = 21;
            }
            int num = 15;
            if (WorldGen.tenthAnniversaryWorldGen)
            {
                num *= 3;
            }
            int k = j;
            while (k < Main.maxTilesY - 10)
            {
                bool flag = false;
                bool flag2 = false;
                bool flag3 = false;
                bool flag4 = false;
                bool flag5 = false;
                bool flag6 = false;
                bool flag7 = false;
                bool flag8 = false;
                bool flag9 = false;
                bool flag10 = false;
                bool flag11 = false;
                bool flag12 = false;
                bool flag13 = false;
                int num2 = -1;
                int num3 = -1;
                if (Main.tile[i, k].anyShimmer())
                {
                    return false;
                }
                if (Main.tile[i, k].active() && Main.tile[i, k].type == 231)
                {
                    return false;
                }
                if (trySlope && Main.tile[i, k].active() && Main.tileSolid[(int)Main.tile[i, k].type] && !Main.tileSolidTop[(int)Main.tile[i, k].type])
                {
                    if (chestStyle == 17)
                    {
                        int num4 = 30;
                        for (int l = i - num4; l <= i + num4; l++)
{
                            for (int m = k - num4; m <= k + num4; m++)
{
                                if (!WorldGen.InWorld(l, m, 5))
{
                                    return false;
                                }
                                if (Main.tile[l, m].active() && (Main.tile[l, m].type == 21 || Main.tile[l, m].type == 467))
{
                                    return false;
                                }
                            }
                        }
                    }
                    if (Main.tile[i - 1, k].topSlope())
                    {
                        num2 = (int)Main.tile[i - 1, k].slope();
                        Main.tile[i - 1, k].slope(0);
                    }
                    if (Main.tile[i, k].topSlope())
                    {
                        num3 = (int)Main.tile[i, k].slope();
                        Main.tile[i, k].slope(0);
                    }
                }
                if (WorldGen.remixWorldGen && (double)i > (double)Main.maxTilesX * 0.37 && (double)i < (double)Main.maxTilesX * 0.63 && k > Main.maxTilesY - 250)
                {
                    return false;
                }
                int num5 = 2;
                for (int n = i - num5; n <= i + num5; n++)
                {
                    for (int num6 = k - num5; num6 <= k + num5; num6++)
                    {
                        if (WorldGen.InWorld(n, num6, 100) && Main.tile[n, num6].active() && (TileID.Sets.Boulders[(int)Main.tile[n, num6].type] || Main.tile[n, num6].type == 26 || Main.tile[n, num6].type == 237))
{
                            return false;
                        }
                    }
                }
                if (WorldGen.SolidTile(i, k, false))
                {
                    bool flag14 = false;
                    int num7 = k;
                    int num8 = 0;
                    int num9 = 0;
                    bool flag15 = (double)num7 >= Main.worldSurface + 25.0;
                    if (WorldGen.remixWorldGen)
                    {
                        flag15 = num7 < Main.maxTilesY - 400;
                    }
                    if (flag15 || num9 > 0)
                    {
                        num8 = 1;
                    }
                    if (chestStyle >= 0)
                    {
                        num8 = chestStyle;
                    }
                    if (mainItemInChest >= 0)
                    {
                        num9 = mainItemInChest;
                    }
                    if (WorldGen.SecretSeed.errorWorld.Enabled && chestTileType == 21 && WorldGen.genRand.Next(2) == 0)
                    {
                        int num10 = -1;
                        if (num8 == 1 || num8 == 11 || num8 == 12 || num8 == 13 || num8 == 15)
{
                            num10 = 6;
                        }
                        else if (num8 == 0)
{
                            num10 = 5;
                        }
                        if (num10 > -1)
{
                            if (WorldGen.genRand.Next(3) == 0)
{
                                num10 = WorldGen.genRand.Next(52);
                                while (num10 >= 18 && num10 <= 27)
{
                                    num10 = WorldGen.genRand.Next(53);
                                }
                            }
                            num8 = num10;
                        }
                    }
                    bool flag16 = Main.remixWorld && Main.getGoodWorld;
                    bool flag17 = Main.drunkWorld && Main.tenthAnniversaryWorld;
                    bool flag18 = Main.notTheBeesWorld && Main.tenthAnniversaryWorld;
                    bool flag19 = chestTileType == 21;
                    if (chestTileType == 21 && (chestStyle == 0 || (chestStyle == -1 && num8 == 0)))
                    {
                        flag = true;
                    }
                    if ((chestTileType == 467 && chestStyle == 10) || (chestTileType == 21 && chestStyle == 42 && flag16) || (num9 == 0 && num7 <= Main.maxTilesY - 205 && WorldGen.IsUndergroundDesert(i, k)))
                    {
                        flag3 = true;
                        num8 = 10;
                        chestTileType = 467;
                        if (flag16 && chestStyle == 42 && flag19)
{
                            num8 = 42;
                            chestTileType = 21;
                        }
                        bool flag20;
                        if (WorldGen.SecretSeed.dualDungeons.Enabled)
{
                            flag20 = GenVars.CurrentDungeonGenVars.desertChestLootState;
                            GenVars.CurrentDungeonGenVars.desertChestLootState = !GenVars.CurrentDungeonGenVars.desertChestLootState;
                        }
                        else
{
                            flag20 = num7 > (GenVars.desertHiveHigh * 3 + GenVars.desertHiveLow * 4) / 7;
                        }
                        if (flag20)
{
                            num9 = (int)Utils.SelectRandom<short>(WorldGen.genRand, new short[] { 4061, 4062, 4276 });
                        }
                        else
{
                            num9 = (int)Utils.SelectRandom<short>(WorldGen.genRand, new short[] { 4056, 4055, 4262, 4263 });
                        }
                        if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                            num9 = 52;
                        }
                    }
                    bool flag21 = false;
                    if (WorldGen.notTheBees && !WorldGen.remixWorldGen && !WorldGen.dontStarveWorldGen)
                    {
                        int num11 = GenVars.lavaLine + WorldGen.genRand.Next(5);
                        int num12 = (int)Main.worldSurface + WorldGen.genRand.Next(-2, 3) + 35;
                        int num13 = (num11 + num12) / 2;
                        if (num7 > num12 && num7 <= num11 && (i < WorldGen.beachDistance + 200 - 20 - WorldGen.genRand.Next(-2, 3) || i > Main.maxTilesX - WorldGen.beachDistance - 200 + 20 + WorldGen.genRand.Next(-2, 3)))
{
                            flag21 = true;
                        }
                    }
                    if ((chestTileType == 21 && chestStyle == 11) || (chestTileType == 467 && chestStyle == 24) || (num9 == 0 && (double)num7 >= Main.worldSurface + 25.0 && num7 <= Main.maxTilesY - 205 && (Main.tile[i, k].type == 147 || Main.tile[i, k].type == 161 || Main.tile[i, k].type == 162 || Main.tile[i, k].type == 197 || flag21)))
                    {
                        flag2 = true;
                        if (chestTileType == 21)
{
                            num8 = 11;
                        }
                        if (flag17 && chestTileType == 21 && chestStyle == 34)
{
                            num8 = 34;
                        }
                        int num14 = WorldGen.genRand.Next(6);
                        if (num14 == 0)
{
                            num9 = 670;
                        }
                        else if (num14 == 1)
{
                            num9 = 724;
                        }
                        else if (num14 == 2)
{
                            num9 = 950;
                        }
                        else if (num14 == 3)
{
                            if (WorldGen.remixWorldGen)
{
                                num9 = 725;
                            }
                            else
{
                                num9 = 1319;
                            }
                        }
                        else if (num14 == 4)
{
                            num9 = 987;
                        }
                        else
{
                            num9 = 1579;
                        }
                        if (WorldGen.genRand.Next(20) == 0)
{
                            num9 = 997;
                        }
                        if (WorldGen.genRand.Next(50) == 0)
{
                            num9 = 669;
                        }
                        if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                            num9 = 52;
                        }
                    }
                    if ((chestTileType == 21 && (chestStyle == 10 || ((chestStyle == 8 || chestStyle == 29) && WorldGen.SecretSeed.dualDungeons.Enabled) || (chestStyle == 29 && flag18))) || (chestTileType == 467 && chestStyle == 11 && flag18) || num9 == 211 || num9 == 212 || num9 == 213 || num9 == 753)
                    {
                        flag4 = true;
                        if (!GenVars.CurrentDungeonGenVars.GeneratingDungeon)
{
                            num8 = 10;
                            chestTileType = 21;
                        }
                        if (flag18)
{
                            if (chestStyle == 29 && flag19)
{
                                num8 = 29;
                                chestTileType = 21;
                            }
                            else if (chestStyle == 11 && !flag19)
{
                                num8 = 11;
                                chestTileType = 467;
                            }
                        }
                        if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                            num9 = 52;
                        }
                    }
                    if (chestTileType == 21 && (chestStyle == 4 || (num7 > Main.maxTilesY - 205 && num9 == 0)))
                    {
                        flag8 = true;
                        num9 = GenVars.hellChestItem[GenVars.hellChest];
                        num8 = 4;
                        flag14 = true;
                        if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                            num9 = 52;
                        }
                    }
                    if (chestTileType == 21 && num8 == 17)
                    {
                        flag5 = true;
                        if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                            num9 = 52;
                        }
                    }
                    if (chestTileType == 21 && num8 == 12)
                    {
                        if (Main.tile[i - 1, num7 - 1].wall != 244)
{
                            num8 = 0;
                            num9 = 0;
                            flag = true;
                        }
                        else
{
                            flag6 = true;
                            if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                                num9 = 52;
                            }
                        }
                    }
                    if (chestTileType == 21 && num8 == 32)
                    {
                        flag7 = true;
                        if (WorldGen.getGoodWorldGen && WorldGen.genRand.Next(num) == 0)
{
                            num9 = 52;
                        }
                    }
                    if (chestTileType == 21 && num8 == 16)
                    {
                        flag13 = true;
                    }
                    if (chestTileType == 21 && num8 != 0 && WorldGen.IsDungeon(i, k))
                    {
                        flag9 = true;
                    }
                    if (WorldGen.IsLockedDungeonBiomeChest(chestTileType, num8))
                    {
                        flag9 = true;
                        flag10 = true;
                    }
                    if (chestTileType == 21 && num8 != 0 && (num9 == 848 || num9 == 857 || num9 == 934))
                    {
                        flag11 = true;
                    }
                    if (chestTileType == 21 && (num8 == 13 || num9 == 159 || num9 == 65 || num9 == 158 || num9 == 2219))
                    {
                        flag12 = true;
                        if (WorldGen.remixWorldGen && !WorldGen.getGoodWorldGen && !WorldGen.tenthAnniversaryWorldGen)
{
                            bool flag22 = WorldGen.crimson;
                            if (WorldGen.drunkWorldGen)
{
                                flag22 = (GenVars.crimsonLeft && i < Main.maxTilesX / 2) || (!GenVars.crimsonLeft && i > Main.maxTilesX / 2);
                            }
                            if (flag22)
{
                                num8 = 43;
                            }
                            else
{
                                chestTileType = 467;
                                num8 = 3;
                            }
                        }
                    }
                    if ((num9 == 939 || (chestTileType == 21 && num8 == 15) || (chestTileType == 467 && num8 == 2)) && num9 == 0)
                    {
                        num9 = 939;
                    }
                    if (WorldGen.noTrapsWorldGen && num8 == 1 && chestTileType == 21 && (!WorldGen.remixWorldGen || WorldGen.genRand.Next(3) == 0))
                    {
                        num8 = 4;
                        chestTileType = 467;
                    }
                    int num15;
                    if (chestTileType == 467)
                    {
                        num15 = WorldGen.PlaceChest(i - 1, num7 - 1, chestTileType, notNearOtherChests, num8);
                    }
                    else
                    {
                        num15 = WorldGen.PlaceChest(i - 1, num7 - 1, chestTileType, notNearOtherChests, num8);
                    }
                    if (num15 >= 0)
                    {
                        chestLocation = new Point(i - 1, num7 - 1);
                        if (flag14)
{
                            GenVars.hellChest++;
                            if (GenVars.hellChest >= GenVars.hellChestItem.Length)
{
                                GenVars.hellChest = 0;
                            }
                        }
                        Chest chest = Main.chest[num15];
                        int num16 = 0;
                        while (num16 == 0)
{
                            bool flag23 = (double)num7 < Main.worldSurface + 25.0;
                            if (WorldGen.remixWorldGen)
{
                                flag23 = (double)num7 >= (Main.rockLayer + (double)((Main.maxTilesY - 350) * 2)) / 3.0;
                            }
                            if ((flag23 && (flag || flag6)) || flag11)
{
                                if (num9 > 0)
{
                                    chest.item[num16].SetDefaults(num9, null);
                                    chest.item[num16].Prefix(-1);
                                    num16++;
                                    if (num9 == 848)
{
                                        chest.item[num16].SetDefaults(866, null);
                                        num16++;
                                    }
                                    else if (num9 == 832)
{
                                        chest.item[num16].SetDefaults(933, null);
                                        num16++;
                                    }
                                    if (flag6 && WorldGen.genRand.Next(3) == 0)
{
                                        chest.item[num16++].SetDefaults(5629, null);
                                    }
                                    if (flag6 && WorldGen.genRand.Next(6) == 0)
{
                                        int num17 = WorldGen.genRand.Next(2);
                                        if (num17 != 0)
{
                                            if (num17 == 1)
{
                                                num17 = 4427;
                                            }
                                        }
                                        else
{
                                            num17 = 4429;
                                        }
                                        chest.item[num16++].SetDefaults(num17, null);
                                    }
                                    if (flag6 && WorldGen.genRand.Next(3) != 0)
{
                                        chest.item[num16++].SetDefaults(5528, null);
                                    }
                                    if (Main.tenthAnniversaryWorld && flag11)
{
                                        chest.item[num16++].SetDefaults(848, null);
                                        chest.item[num16++].SetDefaults(866, null);
                                    }
                                }
                                else
{
                                    int num18 = WorldGen.genRand.Next(10);
                                    if (num18 == 0)
{
                                        chest.item[num16].SetDefaults(280, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 1)
{
                                        chest.item[num16].SetDefaults(281, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 2)
{
                                        chest.item[num16].SetDefaults(284, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 3)
{
                                        chest.item[num16].SetDefaults(285, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 4)
{
                                        chest.item[num16].SetDefaults(953, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 5)
{
                                        chest.item[num16].SetDefaults(946, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 6)
{
                                        chest.item[num16].SetDefaults(3068, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 7)
{
                                        if (WorldGen.remixWorldGen)
{
                                            chest.item[num16].SetDefaults(517, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        else
{
                                            chest.item[num16].SetDefaults(3069, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                    }
                                    if (num18 == 8)
{
                                        chest.item[num16].SetDefaults(3084, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num18 == 9)
{
                                        chest.item[num16].SetDefaults(4341, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(6) == 0)
{
                                    int num19 = WorldGen.genRand.Next(40, 76);
                                    short num20 = 282;
                                    if (WorldGen.SecretSeed.GenerateRainbowGlowsticks)
{
                                        num20 = 5643;
                                    }
                                    chest.item[num16].SetDefaults((int)num20, null);
                                    chest.item[num16].stack = num19;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(6) == 0)
{
                                    int num21 = WorldGen.genRand.Next(150, 301);
                                    chest.item[num16].SetDefaults(279, null);
                                    chest.item[num16].stack = num21;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(6) == 0)
{
                                    chest.item[num16].SetDefaults(3093, null);
                                    chest.item[num16].stack = 1;
                                    if (WorldGen.genRand.Next(5) == 0)
{
                                        chest.item[num16].stack += WorldGen.genRand.Next(2);
                                    }
                                    if (WorldGen.genRand.Next(10) == 0)
{
                                        chest.item[num16].stack += WorldGen.genRand.Next(3);
                                    }
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(6) == 0)
{
                                    chest.item[num16].SetDefaults(4345, null);
                                    chest.item[num16].stack = 1;
                                    if (WorldGen.genRand.Next(5) == 0)
{
                                        chest.item[num16].stack += WorldGen.genRand.Next(2);
                                    }
                                    if (WorldGen.genRand.Next(10) == 0)
{
                                        chest.item[num16].stack += WorldGen.genRand.Next(3);
                                    }
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) == 0)
{
                                    chest.item[num16].SetDefaults(168, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(3, 6);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num22 = WorldGen.genRand.Next(2);
                                    int num23 = WorldGen.genRand.Next(8) + 3;
                                    if (num22 == 0)
{
                                        chest.item[num16].SetDefaults(GenVars.copperBar, null);
                                    }
                                    if (num22 == 1)
{
                                        chest.item[num16].SetDefaults(GenVars.ironBar, null);
                                    }
                                    chest.item[num16].stack = num23;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num24 = WorldGen.genRand.Next(50, 101);
                                    chest.item[num16].SetDefaults(965, null);
                                    chest.item[num16].stack = num24;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) != 0)
{
                                    int num25 = WorldGen.genRand.Next(2);
                                    int num26 = WorldGen.genRand.Next(26) + 25;
                                    if (num25 == 0)
{
                                        chest.item[num16].SetDefaults(40, null);
                                    }
                                    if (num25 == 1)
{
                                        chest.item[num16].SetDefaults(42, null);
                                    }
                                    chest.item[num16].stack = num26;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num27 = WorldGen.genRand.Next(3) + 3;
                                    chest.item[num16].SetDefaults(28, null);
                                    chest.item[num16].stack = num27;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) != 0)
{
                                    chest.item[num16].SetDefaults(2350, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(3, 6);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) > 0)
{
                                    int num28 = WorldGen.genRand.Next(6);
                                    int num29 = WorldGen.genRand.Next(1, 3);
                                    if (num28 == 0)
{
                                        chest.item[num16].SetDefaults(292, null);
                                    }
                                    if (num28 == 1)
{
                                        chest.item[num16].SetDefaults(298, null);
                                    }
                                    if (num28 == 2)
{
                                        chest.item[num16].SetDefaults(299, null);
                                    }
                                    if (num28 == 3)
{
                                        chest.item[num16].SetDefaults(290, null);
                                    }
                                    if (num28 == 4)
{
                                        chest.item[num16].SetDefaults(2322, null);
                                    }
                                    if (num28 == 5)
{
                                        chest.item[num16].SetDefaults(2325, null);
                                    }
                                    chest.item[num16].stack = num29;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    bool flag24 = WorldGen.genRand.Next(2) != 0;
                                    int num30 = WorldGen.genRand.Next(11) + 10;
                                    if (!flag24)
{
                                        chest.item[num16].SetDefaults(8, null);
                                    }
                                    else
{
                                        chest.item[num16].SetDefaults(31, null);
                                    }
                                    chest.item[num16].stack = num30;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16].SetDefaults(72, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(10, 30);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16].SetDefaults(9, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(50, 100);
                                    num16++;
                                }
                            }
                            else if ((!WorldGen.remixWorldGen && (double)num7 < Main.rockLayer) || (WorldGen.remixWorldGen && (double)num7 > Main.rockLayer && num7 < Main.maxTilesY - 250))
{
                                if (num9 > 0)
{
                                    if (num9 == 832)
{
                                        chest.item[num16].SetDefaults(933, null);
                                        num16++;
                                    }
                                    chest.item[num16].SetDefaults(num9, null);
                                    chest.item[num16].Prefix(-1);
                                    num16++;
                                    if (flag5)
{
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            chest.item[num16++].SetDefaults(4425, null);
                                        }
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            chest.item[num16++].SetDefaults(4460, null);
                                        }
                                    }
                                    if (flag12 && WorldGen.genRand.Next(40) == 0)
{
                                        chest.item[num16].SetDefaults(4978, null);
                                        chest.item[num16].Prefix(-1);
                                        num16++;
                                    }
                                    if (flag6 && WorldGen.genRand.Next(3) == 0)
{
                                        chest.item[num16++].SetDefaults(5629, null);
                                    }
                                    if (flag6 && WorldGen.genRand.Next(6) == 0)
{
                                        int num31 = WorldGen.genRand.Next(2);
                                        if (num31 != 0)
{
                                            if (num31 == 1)
{
                                                num31 = 4427;
                                            }
                                        }
                                        else
{
                                            num31 = 4429;
                                        }
                                        chest.item[num16].SetDefaults(num31, null);
                                        num16++;
                                    }
                                    if (flag6 && WorldGen.genRand.Next(3) != 0)
{
                                        chest.item[num16++].SetDefaults(5528, null);
                                    }
                                    if (flag9 && !flag10)
{
                                        if (!GenVars.generatedShadowKey || WorldGen.genRand.Next(3) == 0)
{
                                            GenVars.generatedShadowKey = true;
                                            chest.item[num16].SetDefaults(329, null);
                                            num16++;
                                        }
                                        if (!GenVars.generatedRamRune || WorldGen.genRand.Next(8) == 0)
{
                                            GenVars.generatedRamRune = true;
                                            chest.item[num16].SetDefaults(5465, null);
                                            chest.item[num16].Prefix(-1);
                                            num16++;
                                        }
                                    }
                                }
                                else
{
                                    int num32 = WorldGen.genRand.Next(6);
                                    if (num32 == 0)
{
                                        chest.item[num16].SetDefaults(49, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else if (num32 == 1)
{
                                        chest.item[num16].SetDefaults(50, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else if (num32 == 2)
{
                                        chest.item[num16].SetDefaults(53, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else if (num32 == 3)
{
                                        chest.item[num16].SetDefaults(54, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else if (num32 == 4)
{
                                        chest.item[num16].SetDefaults(5011, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else
{
                                        chest.item[num16].SetDefaults(975, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (Main.vampireSeed && WorldGen.genRand.Next(10) == 1)
{
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            chest.item[num16].SetDefaults(1800, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        else
{
                                            chest.item[num16].SetDefaults(900, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                    }
                                    if (WorldGen.SecretSeed.errorWorld.Enabled && WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(3.0)) == 0)
{
                                        num32 = WorldGen.SecretSeed.DoErrorWorldFindChestItem();
                                        if (num32 > 0)
{
                                            chest.item[num16].SetDefaults(num32, null);
                                        }
                                        chest.item[num16].Prefix(-1);
                                    }
                                    num16++;
                                    if (WorldGen.genRand.Next(20) == 0)
{
                                        chest.item[num16].SetDefaults(997, null);
                                        chest.item[num16].Prefix(-1);
                                        num16++;
                                    }
                                    else if (WorldGen.genRand.Next(20) == 0)
{
                                        chest.item[num16].SetDefaults(930, null);
                                        chest.item[num16].Prefix(-1);
                                        num16++;
                                        if (WorldGen.SecretSeed.rainbowStuff.Enabled)
{
                                            chest.item[num16].SetDefaults(5379, null);
                                            chest.item[num16].stack = WorldGen.genRand.Next(50) + 50;
                                        }
                                        else
{
                                            chest.item[num16].SetDefaults(931, null);
                                            chest.item[num16].stack = WorldGen.genRand.Next(26) + 25;
                                        }
                                        num16++;
                                    }
                                    if (flag7 && WorldGen.genRand.Next(2) == 0)
{
                                        chest.item[num16].SetDefaults(4450, null);
                                        num16++;
                                    }
                                    if (flag7 && WorldGen.genRand.Next(3) == 0)
{
                                        chest.item[num16].SetDefaults(4779, null);
                                        num16++;
                                        chest.item[num16].SetDefaults(4780, null);
                                        num16++;
                                        chest.item[num16].SetDefaults(4781, null);
                                        num16++;
                                    }
                                }
                                if (flag3)
{
                                    if (WorldGen.genRand.Next(3) == 0)
{
                                        chest.item[num16].SetDefaults(4423, null);
                                        chest.item[num16].stack = WorldGen.genRand.Next(10, 20);
                                        num16++;
                                    }
                                }
                                else if (WorldGen.genRand.Next(3) == 0)
{
                                    chest.item[num16].SetDefaults(166, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(10, 20);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(5) == 0)
{
                                    chest.item[num16].SetDefaults(52, null);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) == 0)
{
                                    int num33 = WorldGen.genRand.Next(50, 101);
                                    chest.item[num16].SetDefaults(965, null);
                                    chest.item[num16].stack = num33;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num34 = WorldGen.genRand.Next(2);
                                    int num35 = WorldGen.genRand.Next(10) + 5;
                                    if (num34 == 0)
{
                                        chest.item[num16].SetDefaults(GenVars.ironBar, null);
                                    }
                                    if (num34 == 1)
{
                                        chest.item[num16].SetDefaults(GenVars.silverBar, null);
                                    }
                                    chest.item[num16].stack = num35;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num36 = WorldGen.genRand.Next(2);
                                    int num37 = WorldGen.genRand.Next(25) + 25;
                                    if (num36 == 0)
{
                                        chest.item[num16].SetDefaults(40, null);
                                    }
                                    if (num36 == 1)
{
                                        chest.item[num16].SetDefaults(42, null);
                                    }
                                    chest.item[num16].stack = num37;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num38 = WorldGen.genRand.Next(3) + 3;
                                    chest.item[num16].SetDefaults(28, null);
                                    chest.item[num16].stack = num38;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) > 0)
{
                                    int num39 = WorldGen.genRand.Next(9);
                                    int num40 = WorldGen.genRand.Next(1, 3);
                                    if (num39 == 0)
{
                                        chest.item[num16].SetDefaults(289, null);
                                    }
                                    if (num39 == 1)
{
                                        chest.item[num16].SetDefaults(298, null);
                                    }
                                    if (num39 == 2)
{
                                        chest.item[num16].SetDefaults(299, null);
                                    }
                                    if (num39 == 3)
{
                                        chest.item[num16].SetDefaults(290, null);
                                    }
                                    if (num39 == 4)
{
                                        chest.item[num16].SetDefaults(303, null);
                                    }
                                    if (num39 == 5)
{
                                        chest.item[num16].SetDefaults(291, null);
                                    }
                                    if (num39 == 6)
{
                                        chest.item[num16].SetDefaults(304, null);
                                    }
                                    if (num39 == 7)
{
                                        chest.item[num16].SetDefaults(2322, null);
                                    }
                                    if (num39 == 8)
{
                                        chest.item[num16].SetDefaults(2329, null);
                                    }
                                    chest.item[num16].stack = num40;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) != 0)
{
                                    int num41 = WorldGen.genRand.Next(2, 5);
                                    chest.item[num16].SetDefaults(2350, null);
                                    chest.item[num16].stack = num41;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num42 = WorldGen.genRand.Next(11) + 10;
                                    if (flag2)
{
                                        chest.item[num16].SetDefaults(974, null);
                                    }
                                    else
{
                                        chest.item[num16].SetDefaults(8, null);
                                    }
                                    chest.item[num16].stack = num42;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16].SetDefaults(72, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(50, 90);
                                    num16++;
                                }
                            }
                            else if (num7 < Main.maxTilesY - 250 || (WorldGen.remixWorldGen && (chestStyle == 7 || chestStyle == 14)))
{
                                if (num9 > 0)
{
                                    chest.item[num16].SetDefaults(num9, null);
                                    chest.item[num16].Prefix(-1);
                                    num16++;
                                    if (flag2 && WorldGen.genRand.Next(5) == 0)
{
                                        chest.item[num16].SetDefaults(3199, null);
                                        num16++;
                                    }
                                    if (flag3)
{
                                        if (WorldGen.genRand.Next(7) == 0)
{
                                            chest.item[num16].SetDefaults(4346, null);
                                            num16++;
                                        }
                                        if (WorldGen.genRand.Next(15) == 0)
{
                                            chest.item[num16].SetDefaults(4066, null);
                                            num16++;
                                        }
                                    }
                                    if (flag4)
{
                                        if (!GenVars.gennedLivingMahoganyWands || WorldGen.genRand.Next(5) == 0)
{
                                            GenVars.gennedLivingMahoganyWands = true;
                                            chest.item[num16++].SetDefaults(3360, null);
                                            chest.item[num16++].SetDefaults(3361, null);
                                        }
                                        if (WorldGen.genRand.Next(10) == 0)
{
                                            chest.item[num16++].SetDefaults(4426, null);
                                        }
                                        if (WorldGen.genRand.Next(10) == 0)
{
                                            chest.item[num16++].SetDefaults(5525, null);
                                        }
                                    }
                                    if (flag5)
{
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            chest.item[num16++].SetDefaults(4425, null);
                                        }
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            chest.item[num16++].SetDefaults(4460, null);
                                        }
                                    }
                                    if (flag9 && !flag10)
{
                                        if (!GenVars.generatedShadowKey || WorldGen.genRand.Next(3) == 0)
{
                                            GenVars.generatedShadowKey = true;
                                            chest.item[num16].SetDefaults(329, null);
                                            num16++;
                                        }
                                        if (!GenVars.generatedRamRune || WorldGen.genRand.Next(8) == 0)
{
                                            GenVars.generatedRamRune = true;
                                            chest.item[num16].SetDefaults(5465, null);
                                            chest.item[num16].Prefix(-1);
                                            num16++;
                                        }
                                    }
                                }
                                else
{
                                    int num43 = WorldGen.genRand.Next(7);
                                    bool flag25 = num7 > GenVars.lavaLine;
                                    if (WorldGen.remixWorldGen)
{
                                        flag25 = (double)num7 > Main.worldSurface && (double)num7 < Main.rockLayer;
                                    }
                                    int num44 = 20;
                                    if (WorldGen.tenthAnniversaryWorldGen)
{
                                        num44 = 15;
                                    }
                                    if (WorldGen.genRand.Next(num44) == 0 && flag25)
{
                                        chest.item[num16].SetDefaults(906, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else if (WorldGen.genRand.Next(15) == 0)
{
                                        chest.item[num16].SetDefaults(997, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    else
{
                                        if (num43 == 0)
{
                                            chest.item[num16].SetDefaults(49, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        if (num43 == 1)
{
                                            chest.item[num16].SetDefaults(50, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        if (num43 == 2)
{
                                            chest.item[num16].SetDefaults(53, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        if (num43 == 3)
{
                                            chest.item[num16].SetDefaults(54, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        if (num43 == 4)
{
                                            chest.item[num16].SetDefaults(5011, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        if (num43 == 5)
{
                                            chest.item[num16].SetDefaults(975, null);
                                            chest.item[num16].Prefix(-1);
                                        }
                                        if (num43 == 6)
{
                                            chest.item[num16].SetDefaults(930, null);
                                            chest.item[num16].Prefix(-1);
                                            num16++;
                                            if (WorldGen.SecretSeed.rainbowStuff.Enabled)
{
                                                chest.item[num16].SetDefaults(5379, null);
                                                chest.item[num16].stack = WorldGen.genRand.Next(50) + 50;
                                            }
                                            else
{
                                                chest.item[num16].SetDefaults(931, null);
                                                chest.item[num16].stack = WorldGen.genRand.Next(26) + 25;
                                            }
                                        }
                                        else
{
                                            if (Main.vampireSeed && WorldGen.genRand.Next(10) == 0)
{
                                                if (WorldGen.genRand.Next(2) == 0)
{
                                                    chest.item[num16].SetDefaults(1800, null);
                                                    chest.item[num16].Prefix(-1);
                                                }
                                                else
{
                                                    chest.item[num16].SetDefaults(900, null);
                                                    chest.item[num16].Prefix(-1);
                                                }
                                            }
                                            if (WorldGen.SecretSeed.errorWorld.Enabled && WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(3.0)) == 0)
{
                                                num43 = WorldGen.SecretSeed.DoErrorWorldFindChestItem();
                                                if (num43 > 0)
{
                                                    chest.item[num16].SetDefaults(num43, null);
                                                }
                                                chest.item[num16].Prefix(-1);
                                            }
                                        }
                                    }
                                    num16++;
                                    if (flag7)
{
                                        if (WorldGen.genRand.Next(2) == 0)
{
                                            chest.item[num16].SetDefaults(4450, null);
                                            num16++;
                                        }
                                        else
{
                                            chest.item[num16].SetDefaults(4779, null);
                                            num16++;
                                            chest.item[num16].SetDefaults(4780, null);
                                            num16++;
                                            chest.item[num16].SetDefaults(4781, null);
                                            num16++;
                                        }
                                    }
                                }
                                if (WorldGen.genRand.Next(5) == 0)
{
                                    if (flag2)
{
                                        chest.item[num16].SetDefaults(5120, null);
                                    }
                                    else
{
                                        chest.item[num16].SetDefaults(43, null);
                                    }
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) == 0)
{
                                    chest.item[num16].SetDefaults(167, null);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(4) == 0)
{
                                    chest.item[num16].SetDefaults(51, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(26) + 25;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num45 = WorldGen.genRand.Next(2);
                                    int num46 = WorldGen.genRand.Next(8) + 3;
                                    if (num45 == 0)
{
                                        chest.item[num16].SetDefaults(GenVars.goldBar, null);
                                    }
                                    if (num45 == 1)
{
                                        chest.item[num16].SetDefaults(GenVars.silverBar, null);
                                    }
                                    chest.item[num16].stack = num46;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num47 = WorldGen.genRand.Next(2);
                                    int num48 = WorldGen.genRand.Next(26) + 25;
                                    if (num47 == 0)
{
                                        chest.item[num16].SetDefaults(41, null);
                                    }
                                    if (num47 == 1)
{
                                        chest.item[num16].SetDefaults(279, null);
                                    }
                                    chest.item[num16].stack = num48;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num49 = WorldGen.genRand.Next(3) + 3;
                                    chest.item[num16].SetDefaults(188, null);
                                    chest.item[num16].stack = num49;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) > 0)
{
                                    int num50 = WorldGen.genRand.Next(6);
                                    int num51 = WorldGen.genRand.Next(1, 3);
                                    if (num50 == 0)
{
                                        chest.item[num16].SetDefaults(296, null);
                                    }
                                    if (num50 == 1)
{
                                        chest.item[num16].SetDefaults(295, null);
                                    }
                                    if (num50 == 2)
{
                                        chest.item[num16].SetDefaults(299, null);
                                    }
                                    if (num50 == 3)
{
                                        chest.item[num16].SetDefaults(302, null);
                                    }
                                    if (num50 == 4)
{
                                        chest.item[num16].SetDefaults(303, null);
                                    }
                                    if (num50 == 5)
{
                                        chest.item[num16].SetDefaults(305, null);
                                    }
                                    chest.item[num16].stack = num51;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) > 1)
{
                                    int num52 = WorldGen.genRand.Next(6);
                                    int num53 = WorldGen.genRand.Next(1, 3);
                                    if (num52 == 0)
{
                                        chest.item[num16].SetDefaults(301, null);
                                    }
                                    if (num52 == 1)
{
                                        chest.item[num16].SetDefaults(297, null);
                                    }
                                    if (num52 == 2)
{
                                        chest.item[num16].SetDefaults(304, null);
                                    }
                                    if (num52 == 3)
{
                                        chest.item[num16].SetDefaults(2329, null);
                                    }
                                    if (num52 == 4)
{
                                        chest.item[num16].SetDefaults(2351, null);
                                    }
                                    if (num52 == 5)
{
                                        chest.item[num16].SetDefaults(2326, null);
                                    }
                                    chest.item[num16].stack = num53;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num54 = WorldGen.genRand.Next(2, 5);
                                    chest.item[num16].SetDefaults(2350, null);
                                    chest.item[num16].stack = num54;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0 || (Main.vampireSeed && WorldGen.genRand.Next(2) == 0))
{
                                    bool flag26 = WorldGen.genRand.Next(2) != 0;
                                    int num55 = WorldGen.genRand.Next(15, 31);
                                    if (Main.vampireSeed)
{
                                        num55 *= 2;
                                    }
                                    if (!flag26)
{
                                        if (flag2)
{
                                            chest.item[num16].SetDefaults(974, null);
                                        }
                                        else
{
                                            chest.item[num16].SetDefaults(8, null);
                                        }
                                    }
                                    else
{
                                        short num56 = 282;
                                        if (WorldGen.SecretSeed.GenerateRainbowGlowsticks)
{
                                            num56 = 5643;
                                        }
                                        chest.item[num16].SetDefaults((int)num56, null);
                                    }
                                    chest.item[num16].stack = num55;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16].SetDefaults(73, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(1, 3);
                                    num16++;
                                }
                            }
                            else
{
                                if (num9 > 0)
{
                                    chest.item[num16].SetDefaults(num9, null);
                                    chest.item[num16].Prefix(-1);
                                    num16++;
                                    if (flag8 && WorldGen.genRand.Next(5) == 0)
{
                                        chest.item[num16].SetDefaults(5010, null);
                                        chest.item[num16].Prefix(-1);
                                        num16++;
                                    }
                                    if (flag8 && WorldGen.genRand.Next(10) == 0)
{
                                        chest.item[num16].SetDefaults(4443, null);
                                        num16++;
                                    }
                                    if (flag8 && WorldGen.genRand.Next(10) == 0)
{
                                        chest.item[num16].SetDefaults(4737, null);
                                        num16++;
                                    }
                                    if (flag8 && WorldGen.genRand.Next(10) == 0)
{
                                        chest.item[num16].SetDefaults(4551, null);
                                        num16++;
                                    }
                                }
                                else
{
                                    int num57 = WorldGen.genRand.Next(4);
                                    if (num57 == 0)
{
                                        chest.item[num16].SetDefaults(49, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num57 == 1)
{
                                        chest.item[num16].SetDefaults(50, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num57 == 2)
{
                                        chest.item[num16].SetDefaults(53, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    if (num57 == 3)
{
                                        chest.item[num16].SetDefaults(54, null);
                                        chest.item[num16].Prefix(-1);
                                    }
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) == 0)
{
                                    chest.item[num16].SetDefaults(167, null);
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num58 = WorldGen.genRand.Next(2);
                                    int num59 = WorldGen.genRand.Next(15) + 15;
                                    if (num58 == 0)
{
                                        chest.item[num16].SetDefaults(117, null);
                                    }
                                    if (num58 == 1)
{
                                        chest.item[num16].SetDefaults(GenVars.goldBar, null);
                                    }
                                    chest.item[num16].stack = num59;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num60 = WorldGen.genRand.Next(2);
                                    int num61 = WorldGen.genRand.Next(25) + 50;
                                    if (num60 == 0)
{
                                        chest.item[num16].SetDefaults(265, null);
                                    }
                                    if (num60 == 1)
{
                                        if (WorldGen.SavedOreTiers.Silver == 168)
{
                                            chest.item[num16].SetDefaults(4915, null);
                                        }
                                        else
{
                                            chest.item[num16].SetDefaults(278, null);
                                        }
                                    }
                                    chest.item[num16].stack = num61;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    int num62 = WorldGen.genRand.Next(6) + 15;
                                    chest.item[num16].SetDefaults(227, null);
                                    chest.item[num16].stack = num62;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(4) > 0)
{
                                    int num63 = WorldGen.genRand.Next(8);
                                    int num64 = WorldGen.genRand.Next(1, 3);
                                    if (num63 == 0)
{
                                        chest.item[num16].SetDefaults(296, null);
                                    }
                                    if (num63 == 1)
{
                                        chest.item[num16].SetDefaults(295, null);
                                    }
                                    if (num63 == 2)
{
                                        chest.item[num16].SetDefaults(293, null);
                                    }
                                    if (num63 == 3)
{
                                        chest.item[num16].SetDefaults(288, null);
                                    }
                                    if (num63 == 4)
{
                                        chest.item[num16].SetDefaults(294, null);
                                    }
                                    if (num63 == 5)
{
                                        chest.item[num16].SetDefaults(297, null);
                                    }
                                    if (num63 == 6)
{
                                        chest.item[num16].SetDefaults(304, null);
                                    }
                                    if (num63 == 7)
{
                                        chest.item[num16].SetDefaults(2323, null);
                                    }
                                    chest.item[num16].stack = num64;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) > 0)
{
                                    int num65 = WorldGen.genRand.Next(8);
                                    int num66 = WorldGen.genRand.Next(1, 3);
                                    if (num65 == 0)
{
                                        chest.item[num16].SetDefaults(305, null);
                                    }
                                    if (num65 == 1)
{
                                        chest.item[num16].SetDefaults(301, null);
                                    }
                                    if (num65 == 2)
{
                                        chest.item[num16].SetDefaults(302, null);
                                    }
                                    if (num65 == 3)
{
                                        chest.item[num16].SetDefaults(288, null);
                                    }
                                    if (num65 == 4)
{
                                        chest.item[num16].SetDefaults(300, null);
                                    }
                                    if (num65 == 5)
{
                                        chest.item[num16].SetDefaults(2351, null);
                                    }
                                    if (num65 == 6)
{
                                        chest.item[num16].SetDefaults(2348, null);
                                    }
                                    if (num65 == 7)
{
                                        chest.item[num16].SetDefaults(2345, null);
                                    }
                                    chest.item[num16].stack = num66;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(3) == 0)
{
                                    int num67 = WorldGen.genRand.Next(1, 3);
                                    if (WorldGen.genRand.Next(2) == 0)
{
                                        chest.item[num16].SetDefaults(2350, null);
                                    }
                                    else
{
                                        chest.item[num16].SetDefaults(4870, null);
                                    }
                                    chest.item[num16].stack = num67;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    bool flag27 = WorldGen.genRand.Next(2) != 0;
                                    int num68 = WorldGen.genRand.Next(15) + 15;
                                    if (!flag27)
{
                                        chest.item[num16].SetDefaults(8, null);
                                    }
                                    else
{
                                        short num69 = 282;
                                        if (WorldGen.SecretSeed.GenerateRainbowGlowsticks)
{
                                            num69 = 5643;
                                        }
                                        chest.item[num16].SetDefaults((int)num69, null);
                                    }
                                    chest.item[num16].stack = num68;
                                    num16++;
                                }
                                if (WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16].SetDefaults(73, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(2, 5);
                                    num16++;
                                }
                            }
                            if (num16 > 0 && chestTileType == 21)
{
                                if (flag4 && WorldGen.genRand.Next(4) == 0)
{
                                    chest.item[num16++].SetDefaults(2204, null);
                                }
                                if (flag2 && WorldGen.genRand.Next(7) == 0)
{
                                    chest.item[num16++].SetDefaults(2198, null);
                                }
                                if (flag12 && WorldGen.genRand.Next(3) == 0)
{
                                    chest.item[num16++].SetDefaults(2197, null);
                                }
                                if (flag13)
{
                                    chest.item[num16++].SetDefaults(2195, null);
                                }
                                if (flag9 && WorldGen.genRand.Next(8) == 0)
{
                                    chest.item[num16++].SetDefaults(2192, null);
                                }
                                if (flag9 && Main.getGoodWorld && WorldGen.genRand.Next(5) == 0)
{
                                    chest.item[num16++].SetDefaults(5515, null);
                                }
                                if (flag12)
{
                                    int num70 = WorldGen.genRand.Next(6);
                                    if (num70 == 0)
{
                                        chest.item[num16].SetDefaults(5258, null);
                                    }
                                    if (num70 == 1)
{
                                        chest.item[num16].SetDefaults(5226, null);
                                    }
                                    if (num70 == 2)
{
                                        chest.item[num16].SetDefaults(5254, null);
                                    }
                                    if (num70 == 3)
{
                                        chest.item[num16].SetDefaults(5238, null);
                                    }
                                    if (num70 == 4)
{
                                        chest.item[num16].SetDefaults(5255, null);
                                    }
                                    if (num70 == 5)
{
                                        chest.item[num16].SetDefaults(5388, null);
                                    }
                                    num16++;
                                }
                                if (flag12)
{
                                    chest.item[num16].SetDefaults(751, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(50, 101);
                                    num16++;
                                }
                                if ((num8 == 23 || num8 == 24 || num8 == 25 || num8 == 26 || num8 == 27) && WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16++].SetDefaults(5234, null);
                                }
                                if (flag13)
{
                                    if (WorldGen.genRand.Next(5) == 0)
{
                                        chest.item[num16++].SetDefaults(2767, null);
                                    }
                                    else
{
                                        chest.item[num16].SetDefaults(2766, null);
                                        chest.item[num16].stack = WorldGen.genRand.Next(3, 8);
                                        num16++;
                                    }
                                }
                            }
                            if (num16 > 0 && chestTileType == 467)
{
                                if (flag4 && WorldGen.genRand.Next(4) == 0)
{
                                    chest.item[num16++].SetDefaults(2204, null);
                                }
                                if (flag2 && WorldGen.genRand.Next(7) == 0)
{
                                    chest.item[num16++].SetDefaults(2198, null);
                                }
                                if (flag12 && WorldGen.genRand.Next(3) == 0)
{
                                    chest.item[num16++].SetDefaults(2197, null);
                                }
                                if (flag12)
{
                                    int num71 = WorldGen.genRand.Next(6);
                                    if (num71 == 0)
{
                                        chest.item[num16].SetDefaults(5258, null);
                                    }
                                    if (num71 == 1)
{
                                        chest.item[num16].SetDefaults(5226, null);
                                    }
                                    if (num71 == 2)
{
                                        chest.item[num16].SetDefaults(5254, null);
                                    }
                                    if (num71 == 3)
{
                                        chest.item[num16].SetDefaults(5238, null);
                                    }
                                    if (num71 == 4)
{
                                        chest.item[num16].SetDefaults(5255, null);
                                    }
                                    if (num71 == 5)
{
                                        chest.item[num16].SetDefaults(5388, null);
                                    }
                                    num16++;
                                }
                                if (flag12)
{
                                    chest.item[num16].SetDefaults(751, null);
                                    chest.item[num16].stack = WorldGen.genRand.Next(50, 101);
                                    num16++;
                                }
                                if (num8 == 13 && WorldGen.genRand.Next(2) == 0)
{
                                    chest.item[num16++].SetDefaults(5234, null);
                                }
                            }
                            if (WorldGen.SecretSeed.rainbowStuff.Enabled && (num9 == 1156 || num9 == 1571 || num9 == 1569 || num9 == 1572 || num9 == 4607))
{
                                chest.item[num16].SetDefaults(1260, null);
                                chest.item[num16].Prefix(-1);
                                num16++;
                            }
                            if (Main.vampireSeed && !flag9 && !flag13 && !flag12 && !flag8 && WorldGen.genRand.Next(4) == 0)
{
                                chest.item[num16++].SetDefaults(5597, null);
                            }
                            if (WorldGen.genRand.Next(12) == 0)
{
                                WorldGen.AddVoiceChangeItemToChest(chest, ref num16);
                            }
                            else if (Main.vampireSeed && WorldGen.genRand.Next(12) == 0)
{
                                WorldGen.AddMonsterVoiceChangeItemToChest(chest, ref num16);
                            }
                        }
                        return true;
                    }
                    if (trySlope)
                    {
                        if (num2 > -1)
{
                            Main.tile[i - 1, k].slope((byte)num2);
                        }
                        if (num3 > -1)
{
                            Main.tile[i, k].slope((byte)num3);
                        }
                    }
                    return false;
                }
                else
                {
                    k++;
                }
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.WorldGen.AddMonsterVoiceChangeItemToChest(), Terraria.WorldGen.AddVoiceChangeItemToChest(), Terraria.Tile.anyShimmer(), Terraria.WorldGen.beachDistance, Terraria.ID.TileID.Sets.Boulders, Terraria.Main.chest, Terraria.WorldBuilding.GenVars.copperBar, Terraria.WorldGen.crimson, Terraria.WorldBuilding.GenVars.crimsonLeft, Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.desertChestLootState, Terraria.WorldGen.SecretSeed.DoErrorWorldFindChestItem(), Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.Variations.errorWorldAdjustment(), Terraria.WorldBuilding.GenVars.generatedRamRune, Terraria.WorldBuilding.GenVars.generatedShadowKey, Terraria.WorldGen.SecretSeed.GenerateRainbowGlowsticks, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.GeneratingDungeon, Terraria.WorldBuilding.GenVars.gennedLivingMahoganyWands, Terraria.WorldGen.genRand, Terraria.Main.getGoodWorld, Terraria.WorldGen.getGoodWorldGen, Terraria.WorldBuilding.GenVars.goldBar, Terraria.WorldBuilding.GenVars.hellChest, Terraria.WorldBuilding.GenVars.hellChestItem, int, Terraria.WorldGen.InWorld(), Terraria.WorldBuilding.GenVars.ironBar, Terraria.WorldGen.IsDungeon(), Terraria.WorldGen.IsLockedDungeonBiomeChest(), Terraria.WorldGen.IsUndergroundDesert(), Terraria.Chest.item, Terraria.WorldBuilding.GenVars.lavaLine, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.noTrapsWorldGen, Terraria.WorldGen.notTheBees, Terraria.WorldGen.PlaceChest(), Terraria.Item.Prefix(), Terraria.WorldGen.SecretSeed.rainbowStuff, Terraria.WorldGen.remixWorldGen, Terraria.Main.rockLayer, Terraria.Item.SetDefaults(), Terraria.WorldGen.SavedOreTiers.Silver, Terraria.WorldBuilding.GenVars.silverBar, Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Item.stack, Terraria.Main.tenthAnniversaryWorld, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.topSlope(), Terraria.Tile.type, Terraria.Main.vampireSeed, Terraria.Tile.wall, Terraria.Main.worldSurface, and Microsoft.Xna.Framework.Point.Zero.