Terraria Decompiled: Terraria.WorldGen.GrowTreeWithSettings
GrowTreeWithSettings()
static bool Terraria.WorldGen.GrowTreeWithSettings (int checkedX, int checkedY, WorldGen::GrowTreeSettings settings, int treeHeightAddon = 0, bool ignoreWalls = false) inline static
Definition at line 27673 of file WorldGen.cs.
        {
            int num = checkedY;
            while (Main.tile[checkedX, checkedY].active() && Main.tile[checkedX, num].type == settings.SaplingTileType)
            {
                num++;
            }
            if (Main.tile[checkedX - 1, num - 1].liquid != 0 || Main.tile[checkedX, num - 1].liquid != 0 || Main.tile[checkedX + 1, num - 1].liquid != 0)
            {
                return false;
            }
            Tile tile = Main.tile[checkedX, num];
            if (!tile.nactive() || tile.halfBrick() || tile.slope() != 0)
            {
                return false;
            }
            bool flag = ignoreWalls || settings.WallTest((int)Main.tile[checkedX, num - 1].wall);
            if (!settings.GroundTest((int)tile.type) || !flag)
            {
                return false;
            }
            if ((!Main.tile[checkedX - 1, num].active() || !settings.GroundTest((int)Main.tile[checkedX - 1, num].type)) && (!Main.tile[checkedX + 1, num].active() || !settings.GroundTest((int)Main.tile[checkedX + 1, num].type)))
            {
                return false;
            }
            TileColorCache tileColorCache = Main.tile[checkedX, num].BlockColorAndCoating();
            if (Main.tenthAnniversaryWorld && !WorldGen.isGeneratingOrLoadingWorld && ((!Main.notTheBeesWorld && !Main.dontStarveWorld) || Main.remixWorld) && (settings.TreeTileType == 596 || settings.TreeTileType == 616))
            {
                tileColorCache.Color = (byte)WorldGen.genRand.Next(1, 13);
            }
            int num2 = 2;
            int num3 = WorldGen.genRand.Next(settings.TreeHeightMin, settings.TreeHeightMax + 1) + treeHeightAddon;
            if (WorldGen.SecretSeed.errorWorld.Enabled && WorldGen.genRand.Next(WorldGen.SecretSeed.Variations.errorWorldAdjustment(2.0)) == 0)
            {
                if ((double)checkedY < Main.worldSurface)
                {
                    num3 = WorldGen.genRand.Next(3, 50);
                }
                else
                {
                    num3 = WorldGen.genRand.Next(3, 15);
                }
            }
            int num4 = num3 + settings.TreeTopPaddingNeeded;
            if (!WorldGen.EmptyTileCheck(checkedX - num2, checkedX + num2, num - num4, num - 1, 20))
            {
                return false;
            }
            bool flag2 = false;
            bool flag3 = false;
            int num5;
            for (int i = num - num3; i < num; i++)
            {
                Tile tile2 = Main.tile[checkedX, i];
                tile2.active(true);
                tile2.type = settings.TreeTileType;
                tile2.UseBlockColors(tileColorCache);
                num5 = WorldGen.genRand.Next(3);
                int num6 = WorldGen.genRand.Next(10);
                if (i == num - 1 || i == num - num3)
                {
                    num6 = 0;
                }
                while (((num6 == 5 || num6 == 7) && flag2) || ((num6 == 6 || num6 == 7) && flag3))
                {
                    num6 = WorldGen.genRand.Next(10);
                }
                flag2 = false;
                flag3 = false;
                if (num6 == 5 || num6 == 7)
                {
                    flag2 = true;
                }
                if (num6 == 6 || num6 == 7)
                {
                    flag3 = true;
                }
                if (num6 == 1)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 0;
                        tile2.frameY = 66;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 0;
                        tile2.frameY = 88;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 0;
                        tile2.frameY = 110;
                    }
                }
                else if (num6 == 2)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 22;
                        tile2.frameY = 0;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 22;
                        tile2.frameY = 22;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 22;
                        tile2.frameY = 44;
                    }
                }
                else if (num6 == 3)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 44;
                        tile2.frameY = 66;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 44;
                        tile2.frameY = 88;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 44;
                        tile2.frameY = 110;
                    }
                }
                else if (num6 == 4)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 22;
                        tile2.frameY = 66;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 22;
                        tile2.frameY = 88;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 22;
                        tile2.frameY = 110;
                    }
                }
                else if (num6 == 5)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 88;
                        tile2.frameY = 0;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 88;
                        tile2.frameY = 22;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 88;
                        tile2.frameY = 44;
                    }
                }
                else if (num6 == 6)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 66;
                        tile2.frameY = 66;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 66;
                        tile2.frameY = 88;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 66;
                        tile2.frameY = 110;
                    }
                }
                else if (num6 == 7)
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 110;
                        tile2.frameY = 66;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 110;
                        tile2.frameY = 88;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 110;
                        tile2.frameY = 110;
                    }
                }
                else
                {
                    if (num5 == 0)
                    {
                        tile2.frameX = 0;
                        tile2.frameY = 0;
                    }
                    if (num5 == 1)
                    {
                        tile2.frameX = 0;
                        tile2.frameY = 22;
                    }
                    if (num5 == 2)
                    {
                        tile2.frameX = 0;
                        tile2.frameY = 44;
                    }
                }
                if (num6 == 5 || num6 == 7)
                {
                    Tile tile3 = Main.tile[checkedX - 1, i];
                    tile3.active(true);
                    tile3.type = settings.TreeTileType;
                    tile3.UseBlockColors(tileColorCache);
                    num5 = WorldGen.genRand.Next(3);
                    if (WorldGen.genRand.Next(3) < 2)
                    {
                        if (num5 == 0)
{
                            tile3.frameX = 44;
                            tile3.frameY = 198;
                        }
                        if (num5 == 1)
{
                            tile3.frameX = 44;
                            tile3.frameY = 220;
                        }
                        if (num5 == 2)
{
                            tile3.frameX = 44;
                            tile3.frameY = 242;
                        }
                    }
                    else
                    {
                        if (num5 == 0)
{
                            tile3.frameX = 66;
                            tile3.frameY = 0;
                        }
                        if (num5 == 1)
{
                            tile3.frameX = 66;
                            tile3.frameY = 22;
                        }
                        if (num5 == 2)
{
                            tile3.frameX = 66;
                            tile3.frameY = 44;
                        }
                    }
                }
                if (num6 == 6 || num6 == 7)
                {
                    Tile tile4 = Main.tile[checkedX + 1, i];
                    tile4.active(true);
                    tile4.type = settings.TreeTileType;
                    tile4.UseBlockColors(tileColorCache);
                    num5 = WorldGen.genRand.Next(3);
                    if (WorldGen.genRand.Next(3) < 2)
                    {
                        if (num5 == 0)
{
                            tile4.frameX = 66;
                            tile4.frameY = 198;
                        }
                        if (num5 == 1)
{
                            tile4.frameX = 66;
                            tile4.frameY = 220;
                        }
                        if (num5 == 2)
{
                            tile4.frameX = 66;
                            tile4.frameY = 242;
                        }
                    }
                    else
                    {
                        if (num5 == 0)
{
                            tile4.frameX = 88;
                            tile4.frameY = 66;
                        }
                        if (num5 == 1)
{
                            tile4.frameX = 88;
                            tile4.frameY = 88;
                        }
                        if (num5 == 2)
{
                            tile4.frameX = 88;
                            tile4.frameY = 110;
                        }
                    }
                }
            }
            bool flag4 = false;
            bool flag5 = false;
            if (Main.tile[checkedX - 1, num].nactive() && !Main.tile[checkedX - 1, num].halfBrick() && Main.tile[checkedX - 1, num].slope() == 0 && WorldGen.IsTileTypeFitForTree(Main.tile[checkedX - 1, num].type))
            {
                flag4 = true;
            }
            if (Main.tile[checkedX + 1, num].nactive() && !Main.tile[checkedX + 1, num].halfBrick() && Main.tile[checkedX + 1, num].slope() == 0 && WorldGen.IsTileTypeFitForTree(Main.tile[checkedX + 1, num].type))
            {
                flag5 = true;
            }
            if (WorldGen.genRand.Next(3) == 0)
            {
                flag4 = false;
            }
            if (WorldGen.genRand.Next(3) == 0)
            {
                flag5 = false;
            }
            if (flag5)
            {
                Main.tile[checkedX + 1, num - 1].active(true);
                Main.tile[checkedX + 1, num - 1].type = settings.TreeTileType;
                Main.tile[checkedX + 1, num - 1].UseBlockColors(tileColorCache);
                num5 = WorldGen.genRand.Next(3);
                if (num5 == 0)
                {
                    Main.tile[checkedX + 1, num - 1].frameX = 22;
                    Main.tile[checkedX + 1, num - 1].frameY = 132;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX + 1, num - 1].frameX = 22;
                    Main.tile[checkedX + 1, num - 1].frameY = 154;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX + 1, num - 1].frameX = 22;
                    Main.tile[checkedX + 1, num - 1].frameY = 176;
                }
            }
            if (flag4)
            {
                Main.tile[checkedX - 1, num - 1].active(true);
                Main.tile[checkedX - 1, num - 1].type = settings.TreeTileType;
                Main.tile[checkedX - 1, num - 1].UseBlockColors(tileColorCache);
                num5 = WorldGen.genRand.Next(3);
                if (num5 == 0)
                {
                    Main.tile[checkedX - 1, num - 1].frameX = 44;
                    Main.tile[checkedX - 1, num - 1].frameY = 132;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX - 1, num - 1].frameX = 44;
                    Main.tile[checkedX - 1, num - 1].frameY = 154;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX - 1, num - 1].frameX = 44;
                    Main.tile[checkedX - 1, num - 1].frameY = 176;
                }
            }
            num5 = WorldGen.genRand.Next(3);
            if (flag4 && flag5)
            {
                if (num5 == 0)
                {
                    Main.tile[checkedX, num - 1].frameX = 88;
                    Main.tile[checkedX, num - 1].frameY = 132;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX, num - 1].frameX = 88;
                    Main.tile[checkedX, num - 1].frameY = 154;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX, num - 1].frameX = 88;
                    Main.tile[checkedX, num - 1].frameY = 176;
                }
            }
            else if (flag4)
            {
                if (num5 == 0)
                {
                    Main.tile[checkedX, num - 1].frameX = 0;
                    Main.tile[checkedX, num - 1].frameY = 132;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX, num - 1].frameX = 0;
                    Main.tile[checkedX, num - 1].frameY = 154;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX, num - 1].frameX = 0;
                    Main.tile[checkedX, num - 1].frameY = 176;
                }
            }
            else if (flag5)
            {
                if (num5 == 0)
                {
                    Main.tile[checkedX, num - 1].frameX = 66;
                    Main.tile[checkedX, num - 1].frameY = 132;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX, num - 1].frameX = 66;
                    Main.tile[checkedX, num - 1].frameY = 154;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX, num - 1].frameX = 66;
                    Main.tile[checkedX, num - 1].frameY = 176;
                }
            }
            if (WorldGen.genRand.Next(13) != 0)
            {
                num5 = WorldGen.genRand.Next(3);
                if (num5 == 0)
                {
                    Main.tile[checkedX, num - num3].frameX = 22;
                    Main.tile[checkedX, num - num3].frameY = 198;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX, num - num3].frameX = 22;
                    Main.tile[checkedX, num - num3].frameY = 220;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX, num - num3].frameX = 22;
                    Main.tile[checkedX, num - num3].frameY = 242;
                }
            }
            else
            {
                num5 = WorldGen.genRand.Next(3);
                if (num5 == 0)
                {
                    Main.tile[checkedX, num - num3].frameX = 0;
                    Main.tile[checkedX, num - num3].frameY = 198;
                }
                if (num5 == 1)
                {
                    Main.tile[checkedX, num - num3].frameX = 0;
                    Main.tile[checkedX, num - num3].frameY = 220;
                }
                if (num5 == 2)
                {
                    Main.tile[checkedX, num - num3].frameX = 0;
                    Main.tile[checkedX, num - num3].frameY = 242;
                }
            }
            WorldGen.RangeFrame(checkedX - 2, num - num3 - 1, checkedX + 2, num + 1);
            if (Main.netMode == 2)
            {
                NetMessage.SendTileSquare(-1, checkedX - 1, num - num3, 3, num3, TileChangeType.None);
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.Main.dontStarveWorld, Terraria.WorldGen.EmptyTileCheck(), Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.SecretSeed.Variations.errorWorldAdjustment(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.WorldGen.IsTileTypeFitForTree(), Terraria.Tile.liquid, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.WorldGen.RangeFrame(), Terraria.Main.remixWorld, Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.UseBlockColors(), Terraria.Tile.wall, and Terraria.Main.worldSurface.
Referenced by Terraria.WorldGen.TryGrowingTreeByType().