Terraria Decompiled: Terraria.WorldGen.TreeGrowFXCheck
TreeGrowFXCheck()
static void Terraria.WorldGen.TreeGrowFXCheck (int x, int y) inline static
Definition at line 26557 of file WorldGen.cs.
        {
            int num = 1;
            int num2 = -1;
            Tile tile = null;
            for (int i = -1; i > -100; i--)
            {
                Tile tile2 = Main.tile[x, y + i];
                if (!tile2.active() || !TileID.Sets.GetsCheckedForLeaves[(int)tile2.type])
                {
                    break;
                }
                tile = tile2;
                num++;
            }
            for (int j = 1; j < 5; j++)
            {
                Tile tile3 = Main.tile[x, y + j];
                if (!tile3.active() || !TileID.Sets.GetsCheckedForLeaves[(int)tile3.type])
                {
                    int num3;
                    WorldGen.GetTreeLeaf(x, tile, tile3, ref num, out num3, out num2);
                    break;
                }
                num++;
            }
            if (num > 0 && num2 > 0)
            {
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(112, -1, -1, null, 1, (float)x, (float)y, (float)num, num2, 0, 0);
                }
                if (Main.netMode == 0)
                {
                    WorldGen.TreeGrowFX(x, y, num, num2, false);
                }
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.GetsCheckedForLeaves, Terraria.WorldGen.GetTreeLeaf(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.WorldGen.TreeGrowFX(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.AttemptToGrowTreeFromSapling(), and Terraria.WorldGen.UpdateWorld_GrassGrowth().