Terraria Decompiled: Terraria.WorldGen.RenameWorld
RenameWorld()
static void Terraria.WorldGen.RenameWorld (WorldFileData data, string newName, Action< string > callback = null) inline static
Definition at line 2529 of file WorldGen.cs.
        {
            data.SetAsActive();
            ThreadPool.QueueUserWorkItem(new WaitCallback(WorldGen.RenameWorldCallBack), Tuple.Create<string, Action<string>>(newName, callback));
        }
References System.Threading.ThreadPool.QueueUserWorkItem(), Terraria.WorldGen.RenameWorldCallBack(), Terraria.IO.WorldFileData.SetAsActive(), and System.Threading.WaitCallback().
Referenced by Terraria.IO.WorldFileData.CopyToLocal(), and Terraria.IO.WorldFileData.Rename().