Terraria Decompiled: Terraria.WorldGen.OpenDoor
OpenDoor()
static bool Terraria.WorldGen.OpenDoor (int i, int j, int direction) inline static
Definition at line 35060 of file WorldGen.cs.
        {
            if (Main.tile[i, j - 1] == null)
            {
                Main.tile[i, j - 1] = new Tile();
            }
            if (Main.tile[i, j - 2] == null)
            {
                Main.tile[i, j - 2] = new Tile();
            }
            if (Main.tile[i, j + 1] == null)
            {
                Main.tile[i, j + 1] = new Tile();
            }
            if (Main.tile[i, j] == null)
            {
                Main.tile[i, j] = new Tile();
            }
            Tile tile = Main.tile[i, j];
            if (tile.type != 10)
            {
                return false;
            }
            if (WorldGen.IsLockedDoor(tile))
            {
                return false;
            }
            short num = 0;
            int k = (int)tile.frameY;
            int num2 = 0;
            while (k >= 54)
            {
                k -= 54;
                num2++;
            }
            if (tile.frameX >= 54)
            {
                int num3 = (int)(tile.frameX / 54);
                num2 += 36 * num3;
                num += (short)(72 * num3);
            }
            int num4 = j - k / 18;
            if (!WorldGen.ValidateTileSquareIsActiveAndOfType(i, num4, 1, 3, 10))
            {
                return false;
            }
            TileColorCache tileColorCache = Main.tile[i, num4].BlockColorAndCoating();
            if (Main.tile[i, num4 + 1] == null)
            {
                Main.tile[i, num4 + 1] = new Tile();
            }
            TileColorCache tileColorCache2 = Main.tile[i, num4 + 1].BlockColorAndCoating();
            if (Main.tile[i, num4 + 2] == null)
            {
                Main.tile[i, num4 + 2] = new Tile();
            }
            TileColorCache tileColorCache3 = Main.tile[i, num4 + 2].BlockColorAndCoating();
            int num5;
            int num6;
            if (direction == -1)
            {
                num5 = i - 1;
                num += 36;
                num6 = i - 1;
            }
            else
            {
                num5 = i;
                num6 = i + 1;
            }
            for (int l = num4; l < num4 + 3; l++)
            {
                tile = Framing.GetTileSafely(num6, l);
                if (tile.active() && !Main.tileCut[(int)tile.type] && tile.type != 165 && !TileID.Sets.IsADripTile[(int)tile.type])
                {
                    return false;
                }
            }
            for (int m = num4; m < num4 + 3; m++)
            {
                tile = Main.tile[num6, m];
                if (tile != null && tile.active() && (Main.tileCut[(int)tile.type] || tile.type == 165 || TileID.Sets.IsADripTile[(int)tile.type]))
                {
                    WorldGen.KillTile(num6, m, false, false, false);
                }
            }
            if (Main.netMode != 1 && Wiring.running)
            {
                Wiring.SkipWire(num5, num4);
                Wiring.SkipWire(num5, num4 + 1);
                Wiring.SkipWire(num5, num4 + 2);
                Wiring.SkipWire(num5 + 1, num4);
                Wiring.SkipWire(num5 + 1, num4 + 1);
                Wiring.SkipWire(num5 + 1, num4 + 2);
            }
            int num7 = num2 % 36 * 54;
            SoundEngine.PlaySound(8, i * 16, j * 16, 1, 1f, 0f);
            Main.tile[num5, num4].active(true);
            Main.tile[num5, num4].type = 11;
            Main.tile[num5, num4].frameY = (short)num7;
            Main.tile[num5, num4].frameX = num;
            Main.tile[num5, num4].UseBlockColors(tileColorCache);
            if (Main.tile[num5 + 1, num4] == null)
            {
                Main.tile[num5 + 1, num4] = new Tile();
            }
            Main.tile[num5 + 1, num4].active(true);
            Main.tile[num5 + 1, num4].type = 11;
            Main.tile[num5 + 1, num4].frameY = (short)num7;
            Main.tile[num5 + 1, num4].frameX = num + 18;
            Main.tile[num5 + 1, num4].UseBlockColors(tileColorCache);
            if (Main.tile[num5, num4 + 1] == null)
            {
                Main.tile[num5, num4 + 1] = new Tile();
            }
            Main.tile[num5, num4 + 1].active(true);
            Main.tile[num5, num4 + 1].type = 11;
            Main.tile[num5, num4 + 1].frameY = (short)(num7 + 18);
            Main.tile[num5, num4 + 1].frameX = num;
            Main.tile[num5, num4 + 1].UseBlockColors(tileColorCache2);
            if (Main.tile[num5 + 1, num4 + 1] == null)
            {
                Main.tile[num5 + 1, num4 + 1] = new Tile();
            }
            Main.tile[num5 + 1, num4 + 1].active(true);
            Main.tile[num5 + 1, num4 + 1].type = 11;
            Main.tile[num5 + 1, num4 + 1].frameY = (short)(num7 + 18);
            Main.tile[num5 + 1, num4 + 1].frameX = num + 18;
            Main.tile[num5 + 1, num4 + 1].UseBlockColors(tileColorCache2);
            if (Main.tile[num5, num4 + 2] == null)
            {
                Main.tile[num5, num4 + 2] = new Tile();
            }
            Main.tile[num5, num4 + 2].active(true);
            Main.tile[num5, num4 + 2].type = 11;
            Main.tile[num5, num4 + 2].frameY = (short)(num7 + 36);
            Main.tile[num5, num4 + 2].frameX = num;
            Main.tile[num5, num4 + 2].UseBlockColors(tileColorCache3);
            if (Main.tile[num5 + 1, num4 + 2] == null)
            {
                Main.tile[num5 + 1, num4 + 2] = new Tile();
            }
            Main.tile[num5 + 1, num4 + 2].active(true);
            Main.tile[num5 + 1, num4 + 2].type = 11;
            Main.tile[num5 + 1, num4 + 2].frameY = (short)(num7 + 36);
            Main.tile[num5 + 1, num4 + 2].frameX = num + 18;
            Main.tile[num5 + 1, num4 + 2].UseBlockColors(tileColorCache3);
            for (int n = num5 - 1; n <= num5 + 2; n++)
            {
                for (int num8 = num4 - 1; num8 <= num4 + 2; num8++)
                {
                    WorldGen.TileFrame(n, num8, false, false);
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), int, Terraria.ID.TileID.Sets.IsADripTile, Terraria.WorldGen.IsLockedDoor(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Wiring.running, Terraria.Wiring.SkipWire(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileCut, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, Terraria.Tile.UseBlockColors(), and Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType().
Referenced by Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), Terraria.Player.TileInteractionsUse(), and Terraria.GameContent.DoorOpeningHelper.CommonDoorOpeningInfoProvider.TryOpenDoor().