Terraria Decompiled: Terraria.WorldGen.Check6x4Wall
Check6x4Wall()
static void Terraria.WorldGen.Check6x4Wall (int x, int y) inline static
Definition at line 43265 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            bool flag = false;
            int type = (int)Main.tile[x, y].type;
            int num = (int)(Main.tile[x, y].frameY / 18);
            int num2 = (int)(Main.tile[x, y].frameX / 18);
            int num3 = 27 * (num2 / 6) + (num >> 2);
            num %= 4;
            num2 %= 6;
            int num4 = y - num;
            int num5 = x - (int)(Main.tile[x, y].frameX / 18 % 6);
            num = num3 % 27 * 72;
            num2 = num3 / 27 * 108;
            for (int i = num5; i < num5 + 6; i++)
            {
                for (int j = num4; j < num4 + 4; j++)
                {
                    if ((int)Main.tile[i, j].type != type || !Main.tile[i, j].active() || Main.tile[i, j].wall <= 0 || (int)Main.tile[i, j].frameY != num + (j - num4) * 18 || (int)Main.tile[i, j].frameX != num2 + (i - num5) * 18)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                for (int k = num5; k < num5 + 6; k++)
                {
                    for (int l = num4; l < num4 + 4; l++)
                    {
                        if ((int)Main.tile[k, l].type == type && Main.tile[k, l].active())
{
                            WorldGen.KillTile(k, l, false, false, false);
                        }
                    }
                }
                if (type == 242)
                {
                    if (num3 == 30)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2995, 1, false, 0, false);
                    }
                    else if (num3 == 74)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5636, 1, false, 0, false);
                    }
                    else if (num3 == 73)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5630, 1, false, 0, false);
                    }
                    else if (num3 == 72)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5635, 1, false, 0, false);
                    }
                    else if (num3 == 71)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5531, 1, false, 0, false);
                    }
                    else if (num3 == 70)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5491, 1, false, 0, false);
                    }
                    else if (num3 == 69)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5489, 1, false, 0, false);
                    }
                    else if (num3 == 68)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5487, 1, false, 0, false);
                    }
                    else if (num3 == 67)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5486, 1, false, 0, false);
                    }
                    else if (num3 == 66)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5483, 1, false, 0, false);
                    }
                    else if (num3 == 65)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5389, 1, false, 0, false);
                    }
                    else if (num3 == 64)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5310, 1, false, 0, false);
                    }
                    else if (num3 == 63)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5308, 1, false, 0, false);
                    }
                    else if (num3 == 62)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5274, 1, false, 0, false);
                    }
                    else if (num3 >= 50 && num3 <= 61)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5234 + num3 - 50, 1, false, 0, false);
                    }
                    else if (num3 >= 46 && num3 <= 49)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5121 + num3 - 46, 1, false, 0, false);
                    }
                    else if (num3 == 45)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 5085, 1, false, 0, false);
                    }
                    else if (num3 == 44)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4725, 1, false, 0, false);
                    }
                    else if (num3 == 43)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4658, 1, false, 0, false);
                    }
                    else if (num3 >= 37 && num3 <= 42)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 4632 + num3 - 37, 1, false, 0, false);
                    }
                    else if (num3 >= 31 && num3 <= 35)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3055 + num3 - 31, 1, false, 0, false);
                    }
                    else if (num3 >= 27 && num3 <= 29)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2865 + num3 - 27, 1, false, 0, false);
                    }
                    else if (num3 == 36)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 3596, 1, false, 0, false);
                    }
                    else if (num3 == 26)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2497, 1, false, 0, false);
                    }
                    else if (num3 == 25)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2495, 1, false, 0, false);
                    }
                    else if (num3 >= 22)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 2281 + num3 - 22, 1, false, 0, false);
                    }
                    else if (num3 >= 17)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1846 + num3 - 17, 1, false, 0, false);
                    }
                    else if (num3 == 16)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1573, 1, false, 0, false);
                    }
                    else if (num3 >= 13)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1500 + num3 - 13, 1, false, 0, false);
                    }
                    else if (num3 >= 6)
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1433 + num3 - 6, 1, false, 0, false);
                    }
                    else
                    {
                        Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, y), x * 16, y * 16, 32, 32, 1421 + num3, 1, false, 0, false);
                    }
                }
                WorldGen.destroyObject = false;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.destroyObject, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), int, Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.TileFrameImportant().