Terraria Decompiled: Terraria.WorldGen.ShakeTree
ShakeTree()
static void Terraria.WorldGen.ShakeTree (int i, int j) inline static private
Definition at line 62247 of file WorldGen.cs.
        {
            if (WorldGen.numTreeShakes == WorldGen.maxTreeShakes)
            {
                return;
            }
            int num;
            int num2;
            TreeTypes treeTypeAndTreeBottom = WorldGen.GetTreeTypeAndTreeBottom(i, j, out num, out num2);
            int num3 = num2;
            if (treeTypeAndTreeBottom == TreeTypes.None)
            {
                return;
            }
            for (int k = 0; k < WorldGen.numTreeShakes; k++)
            {
                if (WorldGen.treeShakeX[k] == num && WorldGen.treeShakeY[k] == num2)
                {
                    return;
                }
            }
            WorldGen.treeShakeX[WorldGen.numTreeShakes] = num;
            WorldGen.treeShakeY[WorldGen.numTreeShakes] = num2;
            WorldGen.numTreeShakes++;
            num2--;
            while (num2 > 10 && Main.tile[num, num2].active() && TileID.Sets.IsShakeable[(int)Main.tile[num, num2].type])
            {
                num2--;
            }
            num2++;
            if (!WorldGen.IsTileALeafyTreeTop(num, num2) || Collision.SolidTiles(num - 2, num + 2, num2 - 2, num2 + 2))
            {
                return;
            }
            int num4 = 17;
            int num5 = 28;
            if (Main.tenthAnniversaryWorld && !Main.remixWorld)
            {
                num4 *= 2;
                num5 = 75;
            }
            if (Main.tenthAnniversaryWorld && Main.notTheBeesWorld && !Main.drunkWorld && WorldGen.genRand.Next(50) == 0)
            {
                int num6 = Main.rand.Next(12, 21);
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 1130, num6, false, 0, false);
            }
            else if (Main.getGoodWorld && WorldGen.genRand.Next(num4) == 0)
            {
                Projectile.NewProjectile(WorldGen.GetProjectileSource_ShakeTree(num, num2), (float)(num * 16), (float)(num2 * 16), (float)Main.rand.Next(-100, 101) * 0.002f, 0f, num5, 0, 0f, Main.myPlayer, 16f, 16f, 0f, null);
            }
            else if (WorldGen.genRand.Next(300) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 832, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(300) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 933, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(200) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 3360, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(200) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 3361, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(1000) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 5517, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(1000) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 4366, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(100) == 0 && (treeTypeAndTreeBottom == TreeTypes.Forest || treeTypeAndTreeBottom == TreeTypes.Snow || treeTypeAndTreeBottom == TreeTypes.Hallowed || treeTypeAndTreeBottom == TreeTypes.Ash))
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 5629, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(7) == 0 && (treeTypeAndTreeBottom == TreeTypes.Forest || treeTypeAndTreeBottom == TreeTypes.Snow || treeTypeAndTreeBottom == TreeTypes.Hallowed || treeTypeAndTreeBottom == TreeTypes.Ash))
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 27, WorldGen.genRand.Next(1, 3), false, 0, false);
            }
            else if (WorldGen.genRand.Next(8) == 0 && treeTypeAndTreeBottom == TreeTypes.Mushroom)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 194, WorldGen.genRand.Next(1, 2), false, 0, false);
            }
            else if (WorldGen.genRand.Next(35) == 0 && Main.halloween)
            {
                Item.NewItem(WorldGen.GetItemSource_ShakeTree(num, num2), num * 16, num2 * 16, 16, 16, 1809, WorldGen.genRand.Next(1, 3), false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0)
            {
                int num7 = 0;
                int num8;
                int num9;
                int num10;
                bool flag;
                WorldGen.KillTile_GetItemDrops(i, j, Main.tile[i, j], out num7, out num8, out num9, out num10, out flag, false);
                if (num7 > 0)
                {
                    Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num7, WorldGen.genRand.Next(1, 4), false, flag ? (-4) : 0, false);
                }
            }
            else if (WorldGen.genRand.Next(20) == 0)
            {
                int num11 = 71;
                int num12 = WorldGen.genRand.Next(50, 100);
                if (WorldGen.genRand.Next(30) == 0)
                {
                    num11 = 73;
                    num12 = 1;
                    if (WorldGen.genRand.Next(5) == 0)
                    {
                        num12++;
                    }
                    if (WorldGen.genRand.Next(10) == 0)
                    {
                        num12++;
                    }
                }
                else if (WorldGen.genRand.Next(10) == 0)
                {
                    num11 = 72;
                    num12 = WorldGen.genRand.Next(1, 21);
                    if (WorldGen.genRand.Next(3) == 0)
                    {
                        num12 += WorldGen.genRand.Next(1, 21);
                    }
                    if (WorldGen.genRand.Next(4) == 0)
                    {
                        num12 += WorldGen.genRand.Next(1, 21);
                    }
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num11, num12, false, 0, false);
            }
            else if (WorldGen.genRand.Next(15) == 0 && (treeTypeAndTreeBottom == TreeTypes.Forest || treeTypeAndTreeBottom == TreeTypes.Hallowed))
            {
                int num13 = WorldGen.genRand.Next(5);
                int num14;
                if (num13 == 0)
                {
                    num14 = 74;
                }
                else if (num13 == 1)
                {
                    num14 = 297;
                }
                else if (num13 == 2)
                {
                    num14 = 298;
                }
                else if (num13 == 3)
                {
                    num14 = 299;
                }
                else
                {
                    num14 = 538;
                }
                if (Player.GetClosestRollLuck(num, num2, NPC.goldCritterChance) == 0f)
                {
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        num14 = 442;
                    }
                    else
                    {
                        num14 = 539;
                    }
                }
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, num14, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(50) == 0 && treeTypeAndTreeBottom == TreeTypes.Hallowed && !Main.dayTime)
            {
                int num15 = (int)Main.rand.NextFromList(new short[] { 583, 584, 585 });
                if (Main.tenthAnniversaryWorld && Main.rand.Next(4) != 0)
                {
                    num15 = 583;
                }
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, num15, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(50) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest && !Main.dayTime)
            {
                NPC npc = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, 611, 0, 0f, 0f, 0f, 0f, 255)];
                npc.velocity.Y = 1f;
                npc.netUpdate = true;
            }
            else if (WorldGen.genRand.Next(50) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle && Main.dayTime)
            {
                NPC npc2 = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, (int)Main.rand.NextFromList(new short[] { 671, 672, 673, 674, 675 }), 0, 0f, 0f, 0f, 0f, 255)];
                npc2.velocity.Y = 1f;
                npc2.netUpdate = true;
            }
            else if (WorldGen.genRand.Next(40) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest && !Main.dayTime && Main.halloween)
            {
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, 301, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(50) == 0 && (treeTypeAndTreeBottom == TreeTypes.Forest || treeTypeAndTreeBottom == TreeTypes.Hallowed))
            {
                for (int l = 0; l < 5; l++)
                {
                    Point point = new Point(num + Main.rand.Next(-2, 2), num2 - 1 + Main.rand.Next(-2, 2));
                    int num16;
                    if (Player.GetClosestRollLuck(num, num2, NPC.goldCritterChance) == 0f)
                    {
                        num16 = 442;
                    }
                    else
                    {
                        num16 = (int)Main.rand.NextFromList(new short[] { 74, 297, 298 });
                    }
                    NPC npc3 = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(num, num2), point.X * 16, point.Y * 16, num16, 0, 0f, 0f, 0f, 0f, 255)];
                    npc3.velocity = Main.rand.NextVector2CircularEdge(3f, 3f);
                    npc3.netUpdate = true;
                }
            }
            else if (WorldGen.genRand.Next(40) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle)
            {
                for (int m = 0; m < 5; m++)
                {
                    Point point2 = new Point(num + Main.rand.Next(-2, 2), num2 - 1 + Main.rand.Next(-2, 2));
                    NPC npc4 = Main.npc[NPC.NewNPC(new EntitySource_ShakeTree(num, num2), point2.X * 16, point2.Y * 16, (int)Main.rand.NextFromList(new short[] { 210, 211 }), 0, 0f, 0f, 0f, 0f, 255)];
                    npc4.ai[1] = 65f;
                    npc4.CanBeReplacedByOtherNPCs = true;
                    npc4.netUpdate = true;
                }
            }
            else if (WorldGen.genRand.Next(20) == 0 && (treeTypeAndTreeBottom == TreeTypes.Palm || treeTypeAndTreeBottom == TreeTypes.PalmCorrupt || treeTypeAndTreeBottom == TreeTypes.PalmCrimson || treeTypeAndTreeBottom == TreeTypes.PalmHallowed) && !WorldGen.IsPalmOasisTree(num))
            {
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, 603, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(30) == 0 && (treeTypeAndTreeBottom == TreeTypes.Crimson || treeTypeAndTreeBottom == TreeTypes.PalmCrimson))
            {
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16 + 8, (num2 - 1) * 16, -22, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(30) == 0 && (treeTypeAndTreeBottom == TreeTypes.Corrupt || treeTypeAndTreeBottom == TreeTypes.PalmCorrupt))
            {
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16 + 8, (num2 - 1) * 16, -11, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(30) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle && !Main.dayTime)
            {
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, 51, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(40) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle)
            {
                Projectile.NewProjectile(WorldGen.GetProjectileSource_ShakeTree(num, num2), (float)(num * 16 + 8), (float)((num2 - 1) * 16), 0f, 0f, 655, 0, 0f, Main.myPlayer, 0f, 0f, 0f, null);
            }
            else if (WorldGen.genRand.Next(20) == 0 && (treeTypeAndTreeBottom == TreeTypes.Forest || treeTypeAndTreeBottom == TreeTypes.Hallowed) && !Main.raining && !NPC.TooWindyForButterflies && Main.dayTime)
            {
                int num17 = 356;
                if (Player.GetClosestRollLuck(num, num2, NPC.goldCritterChance) == 0f)
                {
                    num17 = 444;
                }
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, num17, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (WorldGen.genRand.Next(20) == 0 && treeTypeAndTreeBottom == TreeTypes.Ash && num2 > Main.maxTilesY - 250)
            {
                int num18 = WorldGen.genRand.Next(3);
                if (num18 == 0)
                {
                    num18 = 654;
                }
                else if (num18 == 1)
                {
                    num18 = 653;
                }
                else
                {
                    num18 = 655;
                }
                NPC.NewNPC(new EntitySource_ShakeTree(num, num2), num * 16, num2 * 16, num18, 0, 0f, 0f, 0f, 0f, 255);
            }
            else if (Main.remixWorld && WorldGen.genRand.Next(20) == 0 && treeTypeAndTreeBottom == TreeTypes.Ash && num2 > Main.maxTilesY - 250)
            {
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, 965, WorldGen.genRand.Next(20, 41), false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && treeTypeAndTreeBottom == TreeTypes.Forest)
            {
                int num19 = WorldGen.genRand.Next(5);
                int num20;
                if (num19 == 0)
                {
                    num20 = 4009;
                }
                else if (num19 == 1)
                {
                    num20 = 4293;
                }
                else if (num19 == 2)
                {
                    num20 = 4282;
                }
                else if (num19 == 3)
                {
                    num20 = 4290;
                }
                else
                {
                    num20 = 4291;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num20, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && treeTypeAndTreeBottom == TreeTypes.Snow)
            {
                int num21;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num21 = 4286;
                }
                else
                {
                    num21 = 4295;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num21, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && treeTypeAndTreeBottom == TreeTypes.Jungle)
            {
                int num22;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num22 = 4294;
                }
                else
                {
                    num22 = 4292;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num22, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && (treeTypeAndTreeBottom == TreeTypes.Palm || treeTypeAndTreeBottom == TreeTypes.PalmCorrupt || treeTypeAndTreeBottom == TreeTypes.PalmCrimson || treeTypeAndTreeBottom == TreeTypes.PalmHallowed) && !WorldGen.IsPalmOasisTree(num))
            {
                int num23;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num23 = 4283;
                }
                else
                {
                    num23 = 4287;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num23, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && (treeTypeAndTreeBottom == TreeTypes.Corrupt || treeTypeAndTreeBottom == TreeTypes.PalmCorrupt))
            {
                int num24;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num24 = 4284;
                }
                else
                {
                    num24 = 4289;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num24, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && (treeTypeAndTreeBottom == TreeTypes.Hallowed || treeTypeAndTreeBottom == TreeTypes.PalmHallowed))
            {
                int num25;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num25 = 4297;
                }
                else
                {
                    num25 = 4288;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num25, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && (treeTypeAndTreeBottom == TreeTypes.Crimson || treeTypeAndTreeBottom == TreeTypes.PalmCrimson))
            {
                int num26;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num26 = 4296;
                }
                else
                {
                    num26 = 4285;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num26, 1, false, 0, false);
            }
            else if (WorldGen.genRand.Next(12) == 0 && treeTypeAndTreeBottom == TreeTypes.Ash)
            {
                int num27;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num27 = 5277;
                }
                else
                {
                    num27 = 5278;
                }
                Item.NewItem(WorldGen.GetItemSource_FromTreeShake(num, num2), num * 16, num2 * 16, 16, 16, num27, 1, false, 0, false);
            }
            int num28 = 0;
            int num29 = 0;
            int num30 = 0;
            WorldGen.GetTreeLeaf(num, Main.tile[num, num2], Main.tile[num, num3], ref num28, out num29, out num30);
            if (num30 != -1)
            {
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(112, -1, -1, null, 1, (float)num, (float)num2, 1f, num30, 1, 0);
                }
                if (Main.netMode == 0)
                {
                    WorldGen.TreeGrowFX(num, num2, 1, num30, true);
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.dayTime, Terraria.Main.drunkWorld, Terraria.WorldGen.genRand, Terraria.Player.GetClosestRollLuck(), Terraria.Main.getGoodWorld, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.WorldGen.GetItemSource_FromTreeShake(), Terraria.WorldGen.GetItemSource_ShakeTree(), Terraria.WorldGen.GetProjectileSource_ShakeTree(), Terraria.WorldGen.GetTreeTypeAndTreeBottom(), Terraria.NPC.goldCritterChance, Terraria.Main.halloween, int, Terraria.ID.TileID.Sets.IsShakeable, Terraria.WorldGen.IsTileALeafyTreeTop(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.WorldGen.maxTreeShakes, Terraria.Main.myPlayer, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Projectile.NewProjectile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.notTheBeesWorld, Terraria.WorldGen.numTreeShakes, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.Collision.SolidTiles(), Terraria.Main.tenthAnniversaryWorld, Terraria.Main.tile, Terraria.WorldGen.treeShakeX, Terraria.WorldGen.treeShakeY, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.KillTile().