Terraria Decompiled: Terraria.WorldGen.FinishDrunkGen
FinishDrunkGen()
static void Terraria.WorldGen.FinishDrunkGen () inline static private
Definition at line 23326 of file WorldGen.cs.
        {
            byte b = (byte)WorldGen.genRand.Next(13, 25);
            byte b2 = 16;
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                bool flag = false;
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    if (Main.tile[i, j].active() && Main.tileDungeon[(int)Main.tile[i, j].type])
                    {
                        if (Main.tile[i, j].type == 44)
{
                            b = (byte)WorldGen.genRand.Next(13, 15);
                            if (WorldGen.genRand.Next(2) == 0)
{
                                b = (byte)WorldGen.genRand.Next(23, 25);
                            }
                        }
                        if (Main.tile[i, j].type == 43)
{
                            b = (byte)WorldGen.genRand.Next(15, 19);
                        }
                        if (Main.tile[i, j].type == 41)
{
                            b = (byte)WorldGen.genRand.Next(19, 23);
                        }
                    }
                }
                if (flag)
                {
                    break;
                }
            }
            for (int k = 10; k < Main.maxTilesX - 10; k++)
            {
                for (int l = 10; l < Main.maxTilesY - 10; l++)
                {
                    if (Main.tile[k, l].active() && (Main.tileDungeon[(int)Main.tile[k, l].type] || TileID.Sets.CrackedBricks[(int)Main.tile[k, l].type]))
                    {
                        Main.tile[k, l].color(b);
                    }
                    if (Main.wallDungeon[(int)Main.tile[k, l].wall])
                    {
                        Main.tile[k, l].wallColor(25);
                    }
                    if (Main.tile[k, l].active())
                    {
                        if (Main.tile[k, l].type == 60)
{
                            int num = 1;
                            for (int m = k - num; m <= k + num; m++)
{
                                for (int n = l - num; n <= l + num; n++)
{
                                    if (Main.tile[m, n].type == 147 || Main.tile[m, n].type == 161)
{
                                        Main.tile[m, n].type = 59;
                                    }
                                }
                            }
                        }
                        bool flag2 = false;
                        if (Main.tile[k, l].type == 226)
{
                            flag2 = true;
                        }
                        if (Main.tile[k, l].type == 60 && Main.tile[k, l + 1].type == 226)
{
                            flag2 = true;
                        }
                        if (Main.tile[k, l].type == 137)
{
                            int num2 = (int)(Main.tile[k, l].frameY / 18);
                            if (num2 >= 1 && num2 <= 4)
{
                                flag2 = true;
                            }
                        }
                        if (flag2 && !WorldGen.notTheBees)
{
                            Main.tile[k, l].color(b2);
                        }
                    }
                    if (Main.tile[k, l].wall == 87)
                    {
                        Main.tile[k, l].wallColor(b2);
                    }
                }
            }
            for (int num3 = 0; num3 < 8000; num3++)
            {
                Chest chest = Main.chest[num3];
                if (chest == null)
                {
                    break;
                }
                if (WorldGen.genRand.Next(15) == 0 && chest.item[1].stack != 0)
                {
                    for (int num4 = 1; num4 < chest.maxItems; num4++)
                    {
                        if (chest.item[num4].stack == 0)
{
                            chest.item[num4].SetDefaults(5001, null);
                            break;
                        }
                    }
                }
                if (WorldGen.genRand.Next(30) == 0 && chest.item[1].stack != 0)
                {
                    for (int num5 = 1; num5 < chest.maxItems; num5++)
                    {
                        if (chest.item[num5].stack == 0)
{
                            chest.item[num5].SetDefaults(678, null);
                            break;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.chest, Terraria.Tile.color(), Terraria.ID.TileID.Sets.CrackedBricks, Terraria.Tile.frameY, Terraria.WorldGen.genRand, int, Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.notTheBees, Terraria.Item.SetDefaults(), Terraria.Item.stack, Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), and Terraria.Main.wallDungeon.