Terraria Decompiled: Terraria.WorldGen.PlaceChest
PlaceChest()
static int Terraria.WorldGen.PlaceChest (int x, int y, ushort type = 21, bool notNearOtherChests = false, int style = 0) inline static
Definition at line 56514 of file WorldGen.cs.
        {
            int num = -1;
            if (TileID.Sets.Boulders[(int)Main.tile[x, y + 1].type] || TileID.Sets.Boulders[(int)Main.tile[x + 1, y + 1].type])
            {
                return -1;
            }
            TileObject tileObject;
            if (TileObject.CanPlace(x, y, (int)type, style, 1, out tileObject, false, null))
            {
                bool flag = true;
                if (notNearOtherChests && Chest.NearOtherChests(x - 1, y - 1))
                {
                    flag = false;
                }
                if (flag)
                {
                    TileObject.Place(tileObject);
                    num = Chest.CreateChest(tileObject.xCoord, tileObject.yCoord, -1);
                }
            }
            else
            {
                num = -1;
            }
            if (num != -1 && Main.netMode == 1 && type == 21)
            {
                NetMessage.SendData(34, -1, -1, null, 0, (float)x, (float)y, (float)style, 0, 0, 0);
            }
            if (num != -1 && Main.netMode == 1 && type == 467)
            {
                NetMessage.SendData(34, -1, -1, null, 4, (float)x, (float)y, (float)style, 0, 0, 0);
            }
            return num;
        }
References Terraria.ID.TileID.Sets.Boulders, Terraria.TileObject.CanPlace(), Terraria.Chest.CreateChest(), Terraria.Chest.NearOtherChests(), Terraria.Main.netMode, Terraria.TileObject.Place(), Terraria.NetMessage.SendData(), Terraria.Main.tile, Terraria.Tile.type, Terraria.TileObject.xCoord, and Terraria.TileObject.yCoord.
Referenced by Terraria.WorldGen.AddBuriedChest(), and Terraria.WorldGen.PlaceTile().