Terraria Decompiled: Terraria.WorldGen.ConvertTreeAndGround
ConvertTreeAndGround()
static void Terraria.WorldGen.ConvertTreeAndGround (int x, int y, int newFloorType, int oldTreeType, int newTreeType) inline static
Definition at line 53444 of file WorldGen.cs.
        {
            if (!WorldGen.InWorld(x, y, 5))
            {
                return;
            }
            Tile tile = Main.tile[x, y + 1];
            if (tile == null || !tile.active())
            {
                return;
            }
            int i = 100;
            int num = 1;
            int num2 = 0;
            while (i > 0)
            {
                i--;
                if (!WorldGen.InWorld(x, y - 1 - num, 5))
                {
                    break;
                }
                Tile tile2 = Main.tile[x, y - 1 - num];
                if (tile2 == null || !tile2.active() || (tile2.type != 323 && !TileID.Sets.IsATreeTrunk[(int)tile2.type]) || WorldGen.IsTileATreeBranch(x, y - 1, out num2))
                {
                    break;
                }
                num++;
            }
            if (WorldGen.IsTileATreeBranch(x, y, out num2) || WorldGen.IsTileATreeRoot(x, y, out num2))
            {
                WorldGen.KillTile(x, y, false, false, false);
                if (Main.netMode == 1)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                }
                return;
            }
            if (newTreeType == 323)
            {
                for (int j = 0; j <= num; j++)
                {
                    Tile tile3 = Main.tile[x, y - j];
                    if (tile3 != null && tile3.active())
                    {
                        int num3 = 0;
                        if ((WorldGen.IsTileATreeBranch(x - 1, y - j, out num3) && num3 == 1) || (WorldGen.IsTileATreeRoot(x - 1, y - j, out num3) && num3 == 1))
{
                            WorldGen.KillTile(x - 1, y - j, false, false, false);
                        }
                        if ((WorldGen.IsTileATreeBranch(x + 1, y - j, out num3) && num3 == -1) || (WorldGen.IsTileATreeRoot(x + 1, y - j, out num3) && num3 == -1))
{
                            WorldGen.KillTile(x + 1, y - j, false, false, false);
                        }
                    }
                }
            }
            for (int k = 0; k <= num; k++)
            {
                Tile tile4 = Main.tile[x, y - k];
                if (tile4 != null && tile4.active())
                {
                    tile4.type = (ushort)newTreeType;
                    bool flag = k == 0;
                    bool flag2 = k == num;
                    if (flag)
                    {
                        if (newTreeType <= 323)
{
                            if (newTreeType != 5)
{
                                if (newTreeType != 323)
{
                                    goto IL_03D8;
                                }
                                tile4.frameX = 66;
                                tile4.frameY = 0;
                                goto IL_03D8;
                            }
                        }
                        else if (newTreeType != 596 && newTreeType != 616)
{
                            goto IL_03D8;
                        }
                        if (oldTreeType == 323)
{
                            tile4.frameX = 0;
                            tile4.frameY = (short)(22 * WorldGen.genRand.Next(0, 3));
                        }
                        else
{
                            WorldGen.ConvertTreeAndGround_Branches(x, y - k, newTreeType);
                        }
                    }
                    else if (flag2)
                    {
                        if (newTreeType <= 323)
{
                            if (newTreeType != 5)
{
                                if (newTreeType != 323)
{
                                    goto IL_03D8;
                                }
                                tile4.frameX = (short)(22 * WorldGen.genRand.Next(4, 7));
                                tile4.frameY = 0;
                                goto IL_03D8;
                            }
                        }
                        else if (newTreeType != 596 && newTreeType != 616)
{
                            goto IL_03D8;
                        }
                        if (oldTreeType == 323)
{
                            tile4.frameX = 22;
                            tile4.frameY = (short)(22 * WorldGen.genRand.Next(9, 12));
                        }
                        else
{
                            WorldGen.ConvertTreeAndGround_Branches(x, y - k, newTreeType);
                        }
                    }
                    else
                    {
                        if (newTreeType <= 323)
{
                            if (newTreeType != 5)
{
                                if (newTreeType != 323)
{
                                    goto IL_03D8;
                                }
                                tile4.frameX = (short)(22 * WorldGen.genRand.Next(0, 3));
                                tile4.frameY = 0;
                                goto IL_03D8;
                            }
                        }
                        else if (newTreeType != 596 && newTreeType != 616)
{
                            goto IL_03D8;
                        }
                        if (oldTreeType == 323)
{
                            if (WorldGen.genRand.Next(2) == 0)
{
                                tile4.frameX = 44;
                                tile4.frameY = (short)(22 * WorldGen.genRand.Next(3, 6));
                            }
                            else if (WorldGen.genRand.Next(2) == 0)
{
                                tile4.frameX = 22;
                                tile4.frameY = (short)(22 * WorldGen.genRand.Next(0, 6));
                            }
                            else
{
                                tile4.frameX = 0;
                                tile4.frameY = (short)(22 * WorldGen.genRand.Next(0, 6));
                            }
                        }
                        else
{
                            WorldGen.ConvertTreeAndGround_Branches(x, y - k, newTreeType);
                        }
                    }
                }
                IL_03D8:;
            }
            tile.type = (ushort)newFloorType;
            NetMessage.SendTileSquare(-1, x - 1, y - num - 1, 3, num + 3, TileChangeType.None);
        }
References Terraria.Tile.active(), Terraria.WorldGen.ConvertTreeAndGround_Branches(), Terraria.WorldGen.genRand, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.WorldGen.IsTileATreeBranch(), Terraria.WorldGen.IsTileATreeRoot(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TryConvertingOrKillingTreesAboveIfTheyWouldBecomeInvalid().