Terraria Decompiled: Terraria.WorldGen.RandomizeWorldSpawn
RandomizeWorldSpawn()
static void Terraria.WorldGen.RandomizeWorldSpawn () inline static private
Definition at line 20985 of file WorldGen.cs.
        {
            GenVars.worldSpawnHasBeenRandomized = true;
            int spawnTileX = Main.spawnTileX;
            int spawnTileY = Main.spawnTileY;
            bool flag = false;
            int num = Main.maxTilesX / 10;
            int num2 = num;
            int num3 = Main.maxTilesX - num2 * 2;
            if (GenVars.CurrentDungeonGenVars.dungeonSide <= (int)DungeonSide.Left)
            {
                num2 = WorldGen.GetRightMostDungeonTile();
                num3 = Main.maxTilesX - num2 - num;
            }
            else
            {
                num2 = num;
                num3 = WorldGen.GetLeftMostDungeonTile() - num2;
            }
            int num4 = (int)Main.worldSurface + 200;
            int num5 = (int)Main.rockLayer;
            int[] array = new int[]
            {
                60, 70, 23, 199, 661, 662, 161, 147, 162, 41,
                43, 44, 226, 57, 633, 53, 397, 396, 25, 163,
                112, 398, 400, 203, 200, 234, 399, 401, 117, 164,
                116, 402, 403, 379, 135, 37
            };
            int num6 = 60;
            for (int i = 0; i < array.Length; i++)
            {
                if (Main.noTrapsWorld && array[i] == 135)
                {
                    array[i] = -1;
                }
                if (WorldGen.SecretSeed.errorWorld.Enabled && (array[i] == 57 || array[i] == 70 || array[i] == 161 || array[i] == 53 || array[i] == 397 || array[i] == 396 || array[i] == 163 || array[i] == 200 || array[i] == 135 || array[i] == 379 || array[i] == 37))
                {
                    array[i] = -1;
                }
                if (WorldGen.SecretSeed.worldIsFrozen.Enabled)
                {
                    if (array[i] == 161 || array[i] == 147 || array[i] == 162)
                    {
                        array[i] = -1;
                    }
                    if (WorldGen.SecretSeed.worldIsInfected.Enabled && (array[i] == 163 || array[i] == 200))
                    {
                        array[i] = -1;
                    }
                }
                if (WorldGen.notTheBees)
                {
                    if (array[i] == 60)
                    {
                        array[i] = -1;
                    }
                    if (WorldGen.SecretSeed.worldIsInfected.Enabled && (array[i] == 661 || array[i] == 662))
                    {
                        array[i] = -1;
                    }
                }
                if (WorldGen.SecretSeed.worldIsInfected.Enabled && (array[i] == 23 || array[i] == 199 || array[i] == 25 || array[i] == 203))
                {
                    array[i] = -1;
                }
            }
            Vector2 vector = Utils.CheckForGoodTeleportationSpot(ref flag, num2, num3, num4, num5, new Utils.RandomTeleportationAttemptSettings
            {
                teleporteeSize = new Vector2(20f, 42f),
                teleporteeVelocity = Vector2.Zero,
                teleporteeGravityDirection = 1f,
                avoidLava = true,
                avoidAnyLiquid = true,
                avoidHurtTiles = true,
                avoidWalls = true,
                mostlySolidFloor = true,
                strictRange = true,
                maximumFallDistanceFromOrignalPoint = 100,
                attemptsBeforeGivingUp = 5000,
                tilesToAvoid = array,
                tilesToAvoidRange = num6
            });
            if (flag)
            {
                Main.spawnTileX = (int)(vector.X / 16f);
                Main.spawnTileY = (int)(vector.Y / 16f);
            }
        }
References System.array, Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.WorldBuilding.GenVars.CurrentDungeonGenVars, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonSide, Terraria.WorldGen.SecretSeed.errorWorld, Terraria.WorldGen.GetLeftMostDungeonTile(), Terraria.WorldGen.GetRightMostDungeonTile(), int, Terraria.WorldBuilding.DungeonSide.Left, Terraria.Main.noTrapsWorld, Terraria.WorldGen.notTheBees, Terraria.Main.rockLayer, Terraria.Main.spawnTileX, Terraria.Main.spawnTileY, Terraria.WorldGen.SecretSeed.worldIsFrozen, Terraria.WorldGen.SecretSeed.worldIsInfected, Terraria.Main.worldSurface, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldGen.SecretSeed.DoNoSurface(), and Terraria.WorldGen.SecretSeed.DoRandomSpawn().