Terraria Decompiled: Terraria.WorldGen.clearWorld
clearWorld()
static void Terraria.WorldGen.clearWorld () inline static
Definition at line 2767 of file WorldGen.cs.
        {
            TimeLogger.Reset();
            WorldGen.ResetTreeShakes();
            WorldGen._isRainingBoulders = false;
            WorldGen.meteorShowerCount = 0;
            Main.coinRain = 0;
            Main.ladyBugRainBoost = 0;
            Main.ClearWorldSeedFlags();
            Main.afterPartyOfDoom = false;
            Main.shimmerAlpha = 0f;
            Main.shimmerDarken = 0f;
            NPC.ResetBadgerHatTime();
            NPC.freeCake = false;
            NPC.mechQueen = -1;
            Main.mapDelay = 2;
            Main.waterStyle = 0;
            Main.ResetWindCounter(true);
            WorldGen.TownManager = new TownRoomManager();
            PressurePlateHelper.Reset();
            WorldGen.TownManager.Clear();
            BannerSystem.Clear();
            Main.instance.ClearCachedTileDraws();
            TileEntity.Clear();
            Main.checkXMas();
            Main.checkHalloween();
            DontStarveDarknessDamageDealer.Reset();
            Wiring.ClearAll();
            Main.ParticleSystem_World_BehindPlayers.Particles.Clear();
            Main.ParticleSystem_World_OverPlayers.Particles.Clear();
            if (Main.mapReady)
            {
                for (int i = 0; i < WorldGen.lastMaxTilesX; i++)
                {
                    float num = (float)i / (float)WorldGen.lastMaxTilesX;
                    Main.statusText = Lang.gen[65].Value;
                }
                if (Main.Map != null)
                {
                    Main.Map.Clear();
                }
            }
            Main.Pings.Clear();
            NPC.MoonLordCountdown = 0;
            Main.forceHalloweenForToday = false;
            Main.forceXMasForToday = false;
            Main.forceHalloweenForever = false;
            Main.forceXMasForever = false;
            NPC.RevengeManager.Reset();
            Main.pumpkinMoon = false;
            Main.clearMap = true;
            Main.mapTime = 0;
            Main.updateMap = null;
            Main.mapReady = false;
            Main.refreshMap = false;
            Main.eclipse = false;
            Main.slimeRain = false;
            Main.slimeRainTime = 0.0;
            Main.slimeWarningTime = 0;
            Main.sundialCooldown = 0;
            Main.moondialCooldown = 0;
            Main.fastForwardTimeToDawn = false;
            Main.fastForwardTimeToDusk = false;
            BirthdayParty.WorldClear();
            LanternNight.WorldClear();
            WorldGen.mysticLogsEvent.WorldClear();
            CreditsRollEvent.Reset();
            Sandstorm.WorldClear();
            Main.DroneCameraTracker.WorldClear();
            Main.LocalGolfState.WorldClear();
            Main.CurrentPan = Vector2.Zero;
            Main.UpdateTimeRate();
            Main.wofNPCIndex = -1;
            NPC.waveKills = 0f;
            WorldGen.spawnHardBoss = 0;
            WorldGen.totalSolid2 = 0;
            WorldGen.totalGood2 = 0;
            WorldGen.totalEvil2 = 0;
            WorldGen.totalBlood2 = 0;
            WorldGen.totalSolid = 0;
            WorldGen.totalGood = 0;
            WorldGen.totalEvil = 0;
            WorldGen.totalBlood = 0;
            WorldFile.ResetTemps();
            Main.maxRaining = 0f;
            WorldGen.totalX = 0;
            WorldGen.totalD = 0;
            WorldGen.tEvil = 0;
            WorldGen.tBlood = 0;
            WorldGen.tGood = 0;
            WorldGen.spawnEye = false;
            WorldGen.prioritizedTownNPCType = 0;
            WorldGen.shadowOrbCount = 0;
            WorldGen.altarCount = 0;
            WorldGen.builtHouseWithNoFurniture = false;
            WorldGen.builtHouseWithNoLight = false;
            WorldGen.SavedOreTiers.Copper = -1;
            WorldGen.SavedOreTiers.Iron = -1;
            WorldGen.SavedOreTiers.Silver = -1;
            WorldGen.SavedOreTiers.Gold = -1;
            WorldGen.SavedOreTiers.Cobalt = -1;
            WorldGen.SavedOreTiers.Mythril = -1;
            WorldGen.SavedOreTiers.Adamantite = -1;
            GenVars.shimmerPosition = Vector2D.Zero;
            Main.cloudBGActive = 0f;
            Main.raining = false;
            Main.rainTime = 0;
            Main.maxRaining = 0f;
            Main.hardMode = false;
            Main.helpText = 0;
            Main.BartenderHelpTextIndex = 0;
            Main.dungeonX = 0;
            Main.dungeonY = 0;
            NPC.downedBoss1 = false;
            NPC.downedBoss2 = false;
            NPC.downedBoss3 = false;
            NPC.downedQueenBee = false;
            NPC.downedSlimeKing = false;
            NPC.downedMechBossAny = false;
            NPC.downedMechBoss1 = false;
            NPC.downedMechBoss2 = false;
            NPC.downedMechBoss3 = false;
            NPC.downedFishron = false;
            NPC.downedAncientCultist = false;
            NPC.downedMoonlord = false;
            NPC.downedHalloweenKing = false;
            NPC.downedHalloweenTree = false;
            NPC.downedChristmasIceQueen = false;
            NPC.downedChristmasSantank = false;
            NPC.downedChristmasTree = false;
            NPC.downedPlantBoss = false;
            NPC.downedGolemBoss = false;
            NPC.downedEmpressOfLight = false;
            NPC.downedQueenSlime = false;
            NPC.downedDeerclops = false;
            NPC.combatBookWasUsed = false;
            NPC.combatBookVolumeTwoWasUsed = false;
            NPC.peddlersSatchelWasUsed = false;
            NPC.savedStylist = false;
            NPC.savedGoblin = false;
            NPC.savedWizard = false;
            NPC.savedMech = false;
            NPC.savedTaxCollector = false;
            NPC.savedAngler = false;
            NPC.savedBartender = false;
            NPC.savedGolfer = false;
            NPC.boughtCat = false;
            NPC.boughtDog = false;
            NPC.boughtBunny = false;
            NPC.unlockedSlimeBlueSpawn = false;
            NPC.unlockedSlimeGreenSpawn = false;
            NPC.unlockedSlimeOldSpawn = false;
            NPC.unlockedSlimePurpleSpawn = false;
            NPC.unlockedSlimeRainbowSpawn = false;
            NPC.unlockedSlimeRedSpawn = false;
            NPC.unlockedSlimeYellowSpawn = false;
            NPC.unlockedSlimeCopperSpawn = false;
            NPC.unlockedMerchantSpawn = false;
            NPC.unlockedDemolitionistSpawn = false;
            NPC.unlockedPartyGirlSpawn = false;
            NPC.unlockedDyeTraderSpawn = false;
            NPC.unlockedTruffleSpawn = false;
            NPC.unlockedArmsDealerSpawn = false;
            NPC.unlockedNurseSpawn = false;
            NPC.unlockedPrincessSpawn = false;
            Array.Clear(NPC.ShimmeredTownNPCs, 0, NPC.ShimmeredTownNPCs.Length);
            NPC.downedGoblins = false;
            NPC.downedClown = false;
            NPC.downedFrost = false;
            NPC.downedPirates = false;
            NPC.downedMartians = false;
            NPC.downedTowerSolar = (NPC.downedTowerVortex = (NPC.downedTowerNebula = (NPC.downedTowerStardust = (NPC.LunarApocalypseIsUp = false))));
            NPC.TowerActiveSolar = (NPC.TowerActiveVortex = (NPC.TowerActiveNebula = (NPC.TowerActiveStardust = false)));
            DD2Event.ResetProgressEntirely();
            NPC.ClearFoundActiveNPCs();
            Main.BestiaryTracker.Reset();
            Main.PylonSystem.Reset();
            CreativePowerManager.Instance.Reset();
            Main.CreativeMenu.Reset();
            NPCDamageTracker.Reset();
            WorldGen.shadowOrbSmashed = false;
            WorldGen.spawnMeteor = false;
            WorldGen.stopDrops = false;
            Main.invasionDelay = 0;
            Main.invasionType = 0;
            Main.invasionSize = 0;
            Main.invasionWarn = 0;
            Main.invasionX = 0.0;
            Main.invasionSizeStart = 0;
            Main.treeX[0] = Main.maxTilesX;
            Main.treeX[1] = Main.maxTilesX;
            Main.treeX[2] = Main.maxTilesX;
            Main.treeStyle[0] = 0;
            Main.treeStyle[1] = 0;
            Main.treeStyle[2] = 0;
            Main.treeStyle[3] = 0;
            Liquid.numLiquid = 0;
            LiquidBuffer.numLiquidBuffer = 0;
            if (Main.netMode == 1 || WorldGen.lastMaxTilesX > Main.maxTilesX || WorldGen.lastMaxTilesY > Main.maxTilesY)
            {
                for (int j = 0; j < WorldGen.lastMaxTilesX; j++)
                {
                    float num2 = (float)j / (float)WorldGen.lastMaxTilesX;
                    Main.statusText = string.Concat(new object[]
                    {
                        Lang.gen[46].Value,
                        " ",
                        (int)(num2 * 100f + 1f),
                        "%"
                    });
                    for (int k = 0; k < WorldGen.lastMaxTilesY; k++)
                    {
                        Main.tile[j, k] = null;
                    }
                }
            }
            WorldGen.lastMaxTilesX = Main.maxTilesX;
            WorldGen.lastMaxTilesY = Main.maxTilesY;
            if (Main.netMode != 2)
            {
                Main.sectionManager = new WorldSections(Main.maxTilesX / 200, Main.maxTilesY / 150);
            }
            if (Main.netMode != 1)
            {
                for (int l = 0; l < Main.maxTilesX; l++)
                {
                    float num3 = (float)l / (float)Main.maxTilesX;
                    Main.statusText = string.Concat(new object[]
                    {
                        Lang.gen[47].Value,
                        " ",
                        (int)(num3 * 100f + 1f),
                        "%"
                    });
                    for (int m = 0; m < Main.maxTilesY; m++)
                    {
                        if (Main.tile[l, m] == null)
{
                            Main.tile[l, m] = new Tile();
                        }
                        else
{
                            Main.tile[l, m].ClearEverything();
                        }
                    }
                }
            }
            for (int n = 0; n < Main.countsAsHostForGameplay.Length; n++)
            {
                Main.countsAsHostForGameplay[n] = false;
            }
            CombatText.clearAll();
            PopupText.ClearAll();
            for (int num4 = 0; num4 < 6000; num4++)
            {
                Main.dust[num4] = new Dust();
                Main.dust[num4].dustIndex = num4;
            }
            for (int num5 = 0; num5 < 600; num5++)
            {
                Main.gore[num5] = new Gore();
            }
            for (int num6 = 0; num6 < 400; num6++)
            {
                Main.item[num6] = new WorldItem();
                Main.item[num6].whoAmI = num6;
                Main.timeItemSlotCannotBeReusedFor[num6] = 0;
            }
            for (int num7 = 0; num7 < Main.maxNPCs; num7++)
            {
                Main.npc[num7] = new NPC();
                Main.npc[num7].whoAmI = num7;
                NPC.spawnSlotProtected[num7] = 0;
            }
            for (int num8 = 0; num8 < 1000; num8++)
            {
                Main.projectile[num8] = new Projectile();
                Main.projectile[num8].whoAmI = num8;
            }
            Chest.Clear();
            for (int num9 = 0; num9 < 32000; num9++)
            {
                Main.sign[num9] = null;
            }
            for (int num10 = 0; num10 < Liquid.maxLiquid; num10++)
            {
                Main.liquid[num10] = new Liquid();
            }
            for (int num11 = 0; num11 < 50000; num11++)
            {
                Main.liquidBuffer[num11] = new LiquidBuffer();
            }
            WorldGen.setWorldSize();
            Star.SpawnStars(-1);
            ActiveSections.Reset();
            LeashedEntity.Clear(false);
            WorldGen.Manifest = new WorldManifest();
            WorldGen.worldCleared = true;
        }
References Terraria.Main.BestiaryTracker, Terraria.Main.checkHalloween(), Terraria.Main.checkXMas(), System.Array.Clear(), Terraria.Chest.Clear(), Terraria.DataStructures.TileEntity.Clear(), Terraria.GameContent.BannerSystem.Clear(), Terraria.GameContent.TownRoomManager.Clear(), Terraria.Map.PingMapLayer.Clear(), Terraria.Map.WorldMap.Clear(), Terraria.GameContent.LeashedEntity.Clear(), Terraria.CombatText.clearAll(), Terraria.PopupText.ClearAll(), Terraria.Wiring.ClearAll(), Terraria.Main.ClearCachedTileDraws(), Terraria.Tile.ClearEverything(), Terraria.NPC.ClearFoundActiveNPCs(), Terraria.Main.ClearWorldSeedFlags(), Terraria.Main.countsAsHostForGameplay, Terraria.Main.CreativeMenu, Terraria.Main.DroneCameraTracker, Terraria.Main.dust, Terraria.Dust.dustIndex, Terraria.Lang.gen, Terraria.Main.gore, Terraria.GameContent.Creative.CreativePowerManager.Instance, Terraria.Main.instance, int, Terraria.Main.item, Terraria.WorldGen.lastMaxTilesX, Terraria.WorldGen.lastMaxTilesY, Terraria.Main.liquid, Terraria.Main.liquidBuffer, Terraria.Main.LocalGolfState, Terraria.Main.Map, Terraria.Main.mapReady, Terraria.Liquid.maxLiquid, Terraria.Main.maxNPCs, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.mysticLogsEvent, Terraria.Main.netMode, Terraria.Enums.NPC, Terraria.Main.npc, Terraria.Main.ParticleSystem_World_BehindPlayers, Terraria.Main.ParticleSystem_World_OverPlayers, Terraria.Main.Pings, Terraria.Main.projectile, Terraria.Main.PylonSystem, Terraria.DataStructures.ActiveSections.Reset(), Terraria.GameContent.CoinLossRevengeSystem.Reset(), Terraria.GameContent.Creative.CreativePowerManager.Reset(), Terraria.GameContent.Creative.CreativeUI.Reset(), Terraria.GameContent.DontStarveDarknessDamageDealer.Reset(), Terraria.GameContent.Events.CreditsRollEvent.Reset(), Terraria.GameContent.NPCDamageTracker.Reset(), Terraria.GameContent.PressurePlateHelper.Reset(), Terraria.GameContent.TeleportPylonsSystem.Reset(), Terraria.TimeLogger.Reset(), Terraria.NPC.ResetBadgerHatTime(), Terraria.GameContent.Events.DD2Event.ResetProgressEntirely(), Terraria.IO.WorldFile.ResetTemps(), Terraria.WorldGen.ResetTreeShakes(), Terraria.Main.ResetWindCounter(), Terraria.NPC.RevengeManager, Terraria.WorldGen.setWorldSize(), Terraria.NPC.ShimmeredTownNPCs, Terraria.Main.sign, Terraria.NPC.spawnSlotProtected, Terraria.Star.SpawnStars(), Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.timeItemSlotCannotBeReusedFor, Terraria.WorldGen.TownManager, Terraria.Main.treeStyle, Terraria.Main.treeX, Terraria.Main.UpdateTimeRate(), Terraria.Localization.LocalizedText.Value, Terraria.Entity.whoAmI, Terraria.DataStructures.DroneCameraTracker.WorldClear(), Terraria.GameContent.Events.BirthdayParty.WorldClear(), Terraria.GameContent.Events.LanternNight.WorldClear(), Terraria.GameContent.Events.MysticLogFairiesEvent.WorldClear(), Terraria.GameContent.Events.Sandstorm.WorldClear(), Microsoft.Xna.Framework.Vector2.Zero, and ReLogic.Utilities.Vector2D.Zero.
Referenced by Terraria.WorldBuilding.WorldGenerator.Controller.b__46_0(), Terraria.WorldGen.GenerateWorld(), Terraria.Netplay.InnerClientLoop(), Terraria.IO.WorldFile.LoadHeader(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), and Terraria.WorldBuilding.WorldGenerator.Controller.TryReset().