Terraria Decompiled: Terraria.WorldGen.KillTile_DropBait
KillTile_DropBait()
static void Terraria.WorldGen.KillTile_DropBait (int i, int j, Tile tileCache) inline static private
Definition at line 65670 of file WorldGen.cs.
        {
            int num = -1;
            int num2 = -1;
            int num3 = -1;
            int num4 = -1;
            int num5 = -1;
            int num6 = (int)Player.FindClosest(new Vector2((float)(i * 16), (float)(j * 16)), 16, 16);
            if (tileCache.type == 3)
            {
                num = 400;
                num2 = 100;
                if (Main.player[num6].flowerBoots && tileCache.frameX >= 108)
                {
                    num *= 10000;
                    num2 *= 10000;
                }
            }
            if (tileCache.type == 73)
            {
                if (tileCache.frameX < 108)
                {
                    num3 = 1000;
                }
                num = 200;
                num2 = 50;
                if (Main.player[num6].flowerBoots && tileCache.frameX >= 108)
                {
                    num *= 10000;
                    num2 *= 10000;
                }
            }
            if (tileCache.type == 637)
            {
                num5 = 100;
                if (Main.player[num6].flowerBoots && tileCache.frameX >= 108)
                {
                    num5 *= 10000;
                }
            }
            if (tileCache.type == 61)
            {
                num4 = 80;
                if (Main.player[num6].flowerBoots && tileCache.frameX >= 108)
                {
                    num4 *= 10000;
                }
            }
            if (tileCache.type == 74)
            {
                num4 = 40;
                if (Main.player[num6].flowerBoots && tileCache.frameX >= 108)
                {
                    num4 *= 10000;
                }
            }
            if (tileCache.type == 62)
            {
                num4 = 250;
            }
            if (tileCache.type == 185)
            {
                if (tileCache.frameY == 0 && tileCache.frameX < 214)
                {
                    num = 6;
                }
                if (tileCache.frameY == 18 && (tileCache.frameX < 214 || tileCache.frameX >= 1368))
                {
                    num = 6;
                }
            }
            else if (tileCache.type == 186)
            {
                if (tileCache.frameX >= 378 && tileCache.frameX <= 700)
                {
                    num = 6;
                }
            }
            else if (tileCache.type == 187)
            {
                if (tileCache.frameX >= 756 && tileCache.frameX <= 916)
                {
                    num = 6;
                }
                if (tileCache.frameX <= 322)
                {
                    num = 6;
                }
            }
            else if (tileCache.type == 233)
            {
                num4 = 10;
            }
            int num7 = 357;
            if (Main.player[num6].ZoneGraveyard)
            {
                num7 = 606;
            }
            if (num > 0 && NPC.CountNPCS(num7) < 5 && WorldGen.genRand.Next(num) == 0)
            {
                int num8 = num7;
                if (num7 == 357 && Player.GetClosestRollLuck(i, j, NPC.goldCritterChance) == 0f)
                {
                    num8 = 448;
                }
                int num9 = NPC.NewNPC(WorldGen.GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, num8, 0, 0f, 0f, 0f, 0f, 255);
                Main.npc[num9].TargetClosest(true);
                Main.npc[num9].velocity.Y = (float)WorldGen.genRand.Next(-50, -21) * 0.1f;
                Main.npc[num9].velocity.X = (float)WorldGen.genRand.Next(0, 26) * 0.1f * (float)(-(float)Main.npc[num9].direction);
                Main.npc[num9].direction *= -1;
                Main.npc[num9].netUpdate = true;
            }
            if (num3 > 0 && WorldGen.genRand.Next(num3) == 0)
            {
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(i, j), i * 16, j * 16, 16, 16, 5574, 1, false, 0, false);
            }
            if (num2 > 0 && NPC.CountNPCS(377) < 5 && WorldGen.genRand.Next(num2) == 0)
            {
                int num10 = 377;
                if (Player.GetClosestRollLuck(i, j, NPC.goldCritterChance) == 0f)
                {
                    num10 = 446;
                }
                int num11 = NPC.NewNPC(WorldGen.GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, num10, 0, 0f, 0f, 0f, 0f, 255);
                Main.npc[num11].TargetClosest(true);
                Main.npc[num11].velocity.Y = (float)WorldGen.genRand.Next(-50, -21) * 0.1f;
                Main.npc[num11].velocity.X = (float)WorldGen.genRand.Next(0, 26) * 0.1f * (float)(-(float)Main.npc[num11].direction);
                Main.npc[num11].direction *= -1;
                Main.npc[num11].netUpdate = true;
            }
            if (num4 > 0 && NPC.CountNPCS(485) + NPC.CountNPCS(486) + NPC.CountNPCS(487) < 8 && WorldGen.genRand.Next((int)((double)num4 * 1.25)) == 0)
            {
                int num12 = 485;
                if (WorldGen.genRand.Next(4) == 0)
                {
                    num12 = 486;
                }
                if (WorldGen.genRand.Next(12) == 0)
                {
                    num12 = 487;
                }
                int num13 = NPC.NewNPC(WorldGen.GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, num12, 0, 0f, 0f, 0f, 0f, 255);
                Main.npc[num13].TargetClosest(true);
                Main.npc[num13].velocity.Y = (float)WorldGen.genRand.Next(-50, -21) * 0.1f;
                Main.npc[num13].velocity.X = (float)WorldGen.genRand.Next(0, 26) * 0.1f * (float)(-(float)Main.npc[num13].direction);
                Main.npc[num13].direction *= -1;
                Main.npc[num13].netUpdate = true;
            }
            if (num5 > 0 && NPC.CountNPCS(654) + NPC.CountNPCS(653) < 8 && WorldGen.genRand.Next(num5) == 0)
            {
                int num14 = 653;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num14 = 654;
                }
                int num15 = NPC.NewNPC(WorldGen.GetNPCSource_TileBreak(i, j), i * 16 + 10, j * 16, num14, 0, 0f, 0f, 0f, 0f, 255);
                Main.npc[num15].TargetClosest(true);
                Main.npc[num15].velocity.Y = (float)WorldGen.genRand.Next(-50, -21) * 0.1f;
                Main.npc[num15].velocity.X = (float)WorldGen.genRand.Next(0, 26) * 0.1f * (float)(-(float)Main.npc[num15].direction);
                Main.npc[num15].direction *= -1;
                Main.npc[num15].netUpdate = true;
            }
        }
References Terraria.NPC.CountNPCS(), Terraria.Entity.direction, Terraria.Player.FindClosest(), Terraria.Player.flowerBoots, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Player.GetClosestRollLuck(), Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.WorldGen.GetNPCSource_TileBreak(), Terraria.NPC.goldCritterChance, int, Terraria.NPC.netUpdate, Terraria.Item.NewItem(), Terraria.NPC.NewNPC(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.npc, Terraria.Main.player, Terraria.NPC.TargetClosest(), Terraria.Tile.type, Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Terraria.Player.ZoneGraveyard.
Referenced by Terraria.WorldGen.KillTile().