Terraria Decompiled: Terraria.WorldGen.GetItemDrop_Chests
GetItemDrop_Chests() [1/2]
static int Terraria.WorldGen.GetItemDrop_Chests (int style, bool secondType) inline static
Definition at line 39605 of file WorldGen.cs.
        {
            int num;
            if (secondType)
            {
                num = 3884;
                switch (style)
                {
                case 1:
                    num = 3885;
                    break;
                case 2:
                    num = 3939;
                    break;
                case 3:
                    num = 3965;
                    break;
                case 4:
                    num = 3988;
                    break;
                case 5:
                    num = 4153;
                    break;
                case 6:
                    num = 4174;
                    break;
                case 7:
                    num = 4195;
                    break;
                case 8:
                    num = 4216;
                    break;
                case 9:
                    num = 4265;
                    break;
                case 10:
                    num = 4267;
                    break;
                case 11:
                    num = 4574;
                    break;
                case 12:
                    num = 4712;
                    break;
                case 13:
                    num = 4712;
                    break;
                case 14:
                    num = 5156;
                    break;
                case 15:
                    num = 5177;
                    break;
                case 16:
                    num = 5198;
                    break;
                case 17:
                    num = 5556;
                    break;
                case 18:
                    num = 5609;
                    break;
                case 19:
                    num = 5697;
                    break;
                case 20:
                    num = 5720;
                    break;
                case 21:
                    num = 5745;
                    break;
                case 22:
                    num = 5763;
                    break;
                case 23:
                    num = 5784;
                    break;
                case 24:
                    num = 5805;
                    break;
                case 25:
                    num = 5826;
                    break;
                case 26:
                    num = 5846;
                    break;
                case 27:
                    num = 5865;
                    break;
                case 28:
                    num = 5886;
                    break;
                case 29:
                    num = 5905;
                    break;
                case 30:
                    num = 5939;
                    break;
                case 31:
                    num = 5962;
                    break;
                case 32:
                    num = 5982;
                    break;
                case 33:
                    num = 6005;
                    break;
                case 34:
                    num = 6028;
                    break;
                case 35:
                    num = 6051;
                    break;
                case 36:
                    num = 6074;
                    break;
                case 37:
                    num = 6118;
                    break;
                }
            }
            else
            {
                num = 48;
                switch (style)
                {
                case 0:
                    num = 48;
                    break;
                case 1:
                    num = 306;
                    break;
                case 2:
                    num = 306;
                    break;
                case 3:
                    num = 328;
                    break;
                case 4:
                    num = 328;
                    break;
                case 5:
                    num = 343;
                    break;
                case 6:
                    num = 348;
                    break;
                case 7:
                    num = 625;
                    break;
                case 8:
                    num = 626;
                    break;
                case 9:
                    num = 627;
                    break;
                case 10:
                    num = 680;
                    break;
                case 11:
                    num = 681;
                    break;
                case 12:
                    num = 831;
                    break;
                case 13:
                    num = 838;
                    break;
                case 14:
                    num = 914;
                    break;
                case 15:
                    num = 952;
                    break;
                case 16:
                    num = 1142;
                    break;
                case 17:
                    num = 1298;
                    break;
                case 18:
                    num = 1528;
                    break;
                case 19:
                    num = 1529;
                    break;
                case 20:
                    num = 1530;
                    break;
                case 21:
                    num = 1531;
                    break;
                case 22:
                    num = 1532;
                    break;
                case 23:
                    num = 1528;
                    break;
                case 24:
                    num = 1529;
                    break;
                case 25:
                    num = 1530;
                    break;
                case 26:
                    num = 1531;
                    break;
                case 27:
                    num = 1532;
                    break;
                case 28:
                    num = 2230;
                    break;
                case 29:
                    num = 2249;
                    break;
                case 30:
                    num = 2250;
                    break;
                case 31:
                    num = 2526;
                    break;
                case 32:
                    num = 2544;
                    break;
                case 33:
                    num = 2559;
                    break;
                case 34:
                    num = 2574;
                    break;
                case 35:
                    num = 2612;
                    break;
                case 36:
                    num = 2612;
                    break;
                case 37:
                    num = 2613;
                    break;
                case 38:
                    num = 2613;
                    break;
                case 39:
                    num = 2614;
                    break;
                case 40:
                    num = 2614;
                    break;
                case 41:
                    num = 2615;
                    break;
                case 42:
                    num = 2616;
                    break;
                case 43:
                    num = 2617;
                    break;
                case 44:
                    num = 2618;
                    break;
                case 45:
                    num = 2619;
                    break;
                case 46:
                    num = 2620;
                    break;
                case 47:
                    num = 2748;
                    break;
                case 48:
                    num = 2814;
                    break;
                case 49:
                    num = 3180;
                    break;
                case 50:
                    num = 3125;
                    break;
                case 51:
                    num = 3181;
                    break;
                }
            }
            return num;
        }
Referenced by Terraria.WorldGen.CheckChest(), Terraria.WorldGen.GetItemDrop_Chests(), Terraria.Chest.Initialize(), and Terraria.WorldGen.KillTile_GetItemDrops().