Terraria Decompiled: Terraria.WorldGen.GenerateWorld
GenerateWorld()
static bool Terraria.WorldGen.GenerateWorld (GenerationProgress customProgressObject = null, WorldGenerator::Controller customController = null) inline static
Definition at line 7083 of file WorldGen.cs.
        {
            WorldGen.generatingWorld = true;
            WorldGen.isGeneratingOrLoadingWorld = true;
            WorldGen.generatingWorldOnThisThread = true;
            bool flag = false;
            try
            {
                Console.WriteLine("Creating world - Seed: {0}, Width: {1}, Height: {2}, Evil: {3}, Difficulty: {4}", new object[]
                {
                    Main.ActiveWorldFileData.SeedText,
                    Main.maxTilesX,
                    Main.maxTilesY,
                    WorldGen.WorldGenParam_Evil,
                    Main.GameMode
                });
                GenVars.configuration = WorldGenConfiguration.FromEmbeddedPath("Terraria.GameContent.WorldBuilding.Configuration.json");
                WorldGen.Hooks.ProcessWorldGenConfig(ref GenVars.configuration);
                WorldGen._generator = new WorldGenerator(Main.ActiveWorldFileData.Seed, GenVars.configuration, customProgressObject, customController);
                WorldGen.clearWorld();
                WorldGen.Reset();
                WorldGen.AddPasses();
                WorldGen.DisablePassesForSpecialSeeds(WorldGen._generator._passes);
                flag = WorldGen._generator.GenerateWorld();
                WorldGen.Finish();
            }
            finally
            {
                WorldGen.RestoreTemporaryStateChanges();
                WorldGen.generatingWorld = false;
                WorldGen.isGeneratingOrLoadingWorld = false;
                WorldGen.generatingWorldOnThisThread = false;
                WorldGen.drunkWorldGen = false;
                WorldGen.notTheBees = false;
                WorldGen.noTrapsWorldGen = false;
                WorldGen.getGoodWorldGen = false;
                WorldGen.tenthAnniversaryWorldGen = false;
                WorldGen.dontStarveWorldGen = false;
                WorldGen.remixWorldGen = false;
                WorldGen.everythingWorldGen = false;
                WorldGen.skyblockWorldGen = false;
            }
            return flag;
        }
References Terraria.WorldGen._generator, Terraria.WorldBuilding.WorldGenerator._passes, Terraria.Main.ActiveWorldFileData, Terraria.WorldGen.AddPasses(), Terraria.WorldGen.clearWorld(), Terraria.WorldBuilding.GenVars.configuration, Terraria.WorldGen.DisablePassesForSpecialSeeds(), Terraria.WorldGen.Finish(), Terraria.WorldBuilding.WorldGenConfiguration.FromEmbeddedPath(), Terraria.WorldBuilding.WorldGenerator.GenerateWorld(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.Hooks.ProcessWorldGenConfig(), Terraria.WorldGen.Reset(), Terraria.WorldGen.RestoreTemporaryStateChanges(), Terraria.IO.WorldFileData.Seed, Terraria.IO.WorldFileData.SeedText, Terraria.WorldGen.WorldGenParam_Evil, and System.Console.WriteLine().
Referenced by Terraria.WorldBuilding.WorldUtils.DebugRegen(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.WorldGen.worldGenCallback().