Terraria Decompiled: Terraria.WorldGen.CheckGnome
CheckGnome()
static void Terraria.WorldGen.CheckGnome (int x, int j) inline static
Definition at line 52436 of file WorldGen.cs.
        {
            if (WorldGen.destroyObject)
            {
                return;
            }
            int num = 567;
            int num2 = j;
            bool flag = true;
            Tile tile = Framing.GetTileSafely(x, num2);
            Tile tile2 = Framing.GetTileSafely(x, num2 + 1);
            if (tile.frameY > 0)
            {
                num2--;
                tile = Framing.GetTileSafely(x, num2);
                tile2 = Framing.GetTileSafely(x, num2 + 1);
            }
            short num3 = tile.frameX / 28;
            if (tile.frameY == 0 && tile2.frameY == 20 && (int)tile.type == num && (int)tile2.type == num)
            {
                flag = false;
            }
            if (Main.tile[x, num2 + 2] == null)
            {
                Main.tile[x, num2 + 2] = new Tile();
            }
            if (!WorldGen.SolidTileAllowBottomSlope(x, num2 + 2) && !TileID.Sets.Platforms[(int)Main.tile[x, num2 + 2].type])
            {
                flag = true;
            }
            if (flag)
            {
                WorldGen.destroyObject = true;
                if ((int)tile.type == num)
                {
                    WorldGen.KillTile(x, num2, false, false, false);
                }
                if ((int)tile2.type == num)
                {
                    WorldGen.KillTile(x, num2 + 1, false, false, false);
                }
                Item.NewItem(WorldGen.GetItemSource_FromTileBreak(x, num2), x * 16, num2 * 16, 16, 32, 4609, 1, false, 0, false);
                WorldGen.destroyObject = false;
            }
        }
References Terraria.WorldGen.destroyObject, Terraria.Tile.frameY, Terraria.WorldGen.GetItemSource_FromTileBreak(), Terraria.Framing.GetTileSafely(), Terraria.WorldGen.KillTile(), Terraria.Item.NewItem(), Terraria.ID.TileID.Sets.Platforms, Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.DataStructures.Tile, Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameImportant().