Terraria Decompiled: Terraria.WorldGen.Lakinater
Lakinater()
static void Terraria.WorldGen.Lakinater (int i, int j, double strengthMultiplier = 1::0) inline static
Definition at line 80242 of file WorldGen.cs.
        {
            double num = (double)WorldGen.genRand.Next(25, 50) * strengthMultiplier;
            double num2 = num;
            double num3 = (double)WorldGen.genRand.Next(30, 80);
            if (WorldGen.genRand.Next(5) == 0)
            {
                num *= 1.5;
                num2 *= 1.5;
                num3 *= 1.2;
            }
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j - num3 * 0.3;
            Vector2D vector2D2;
            vector2D2.X = (double)WorldGen.genRand.Next(-10, 11) * 0.1;
            vector2D2.Y = (double)WorldGen.genRand.Next(-20, -10) * 0.1;
            while (num > 0.0 && num3 > 0.0)
            {
                if (vector2D.Y + num2 * 0.5 > Main.worldSurface)
                {
                    num3 = 0.0;
                }
                num -= (double)WorldGen.genRand.Next(3);
                num3 -= 1.0;
                int num4 = (int)(vector2D.X - num * 0.5);
                int num5 = (int)(vector2D.X + num * 0.5);
                int num6 = (int)(vector2D.Y - num * 0.5);
                int num7 = (int)(vector2D.Y + num * 0.5);
                if (num4 < 0)
                {
                    num4 = 0;
                }
                if (num5 > Main.maxTilesX)
                {
                    num5 = Main.maxTilesX;
                }
                if (num6 < 0)
                {
                    num6 = 0;
                }
                if (num7 > Main.maxTilesY)
                {
                    num7 = Main.maxTilesY;
                }
                num2 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                for (int k = num4; k < num5; k++)
                {
                    for (int l = num6; l < num7; l++)
                    {
                        double num8 = Math.Abs((double)k - vector2D.X);
                        double num9 = Math.Abs((double)l - vector2D.Y);
                        if (Math.Sqrt(num8 * num8 + num9 * num9) < num2 * 0.4)
{
                            if (Main.tile[k, l].active())
{
                                Main.tile[k, l].liquid = byte.MaxValue;
                                Main.tile[k, l].liquidType(0);
                            }
                            Main.tile[k, l].active(false);
                        }
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                vector2D2.Y += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.X > 0.5)
                {
                    vector2D2.X = 0.5;
                }
                if (vector2D2.X < -0.5)
                {
                    vector2D2.X = -0.5;
                }
                if (vector2D2.Y > 1.5)
                {
                    vector2D2.Y = 1.5;
                }
                if (vector2D2.Y < 0.5)
                {
                    vector2D2.Y = 0.5;
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.genRand, int, Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.Main.worldSurface, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.