Terraria Decompiled: Terraria.WorldGen.TreeGrowFX
TreeGrowFX()
static void Terraria.WorldGen.TreeGrowFX (int x, int y, int height, int treeGore, bool hitTree = false) inline static
Definition at line 26876 of file WorldGen.cs.
        {
            Vector2 vector = new Vector2((float)x, (float)y) * 16f + new Vector2(8f, 8f);
            if (treeGore == 1278)
            {
                WorldGen.TreeGrowFX_AshShake(x, y, height, hitTree);
                return;
            }
            byte b = 0;
            if (WorldGen.InWorld(x, y, 2))
            {
                Tile tile = Main.tile[x, y];
                if (tile != null && tile.active() && (TileID.Sets.IsATreeTrunk[(int)tile.type] || tile.type == 323))
                {
                    b = Main.tile[x, y].color();
                }
            }
            for (int i = 0; i > -height; i--)
            {
                float num = 10f;
                Vector2 vector2 = new Vector2(5f, 7f);
                Main.gore[Gore.NewGore(vector + new Vector2(-16f, (float)(i * 16)) - vector2, Utils.RandomVector2(Main.rand, -num, num), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f)].Frame.CurrentColumn = b;
                Main.gore[Gore.NewGore(vector + new Vector2(0f, (float)(i * 16)) - vector2, Utils.RandomVector2(Main.rand, -num, num), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f)].Frame.CurrentColumn = b;
                Main.gore[Gore.NewGore(vector + new Vector2(16f, (float)(i * 16)) - vector2, Utils.RandomVector2(Main.rand, -num, num), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f)].Frame.CurrentColumn = b;
                if (i == -height + 1)
                {
                    int num2 = 20;
                    if (hitTree)
                    {
                        num2 = 5;
                    }
                    for (int j = 0; j < num2; j++)
                    {
                        Main.gore[Gore.NewGore(vector + new Vector2(0f, (float)(i * 16 - 40)) + Utils.RandomVector2(Main.rand, -40f, 40f) - vector2, Utils.RandomVector2(Main.rand, -10f, 10f), treeGore, 0.7f + Main.rand.NextFloat() * 0.6f)].Frame.CurrentColumn = b;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.DataStructures.SpriteFrame.CurrentColumn, Terraria.Gore.Frame, Terraria.Main.gore, Terraria.WorldGen.InWorld(), Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.Gore.NewGore(), Terraria.Main.rand, Terraria.Utils.RandomVector2(), Terraria.Main.tile, Terraria.WorldGen.TreeGrowFX_AshShake(), and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TreeGrowFXCheck().