Terraria Decompiled: Terraria.WorldGen.makeTemple
makeTemple()
static void Terraria.WorldGen.makeTemple (int x, int y, GenerationProgress progress = null) inline static
Definition at line 30868 of file WorldGen.cs.
        {
            double num = (double)Main.maxTilesX / 4200.0;
            int num2 = WorldGen.genRand.Next((int)(num * 10.0), (int)(num * 16.0));
            if (WorldGen.drunkWorldGen)
            {
                num2 *= 3;
            }
            else if (WorldGen.getGoodWorldGen)
            {
                num2 *= 3;
            }
            else if (WorldGen.remixWorldGen)
            {
                num2 *= 2;
            }
            Rectangle[] array = new Rectangle[num2 + 10];
            int num3 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num3 = -1;
            }
            int num4 = num3;
            int num5 = x;
            int num6 = y;
            int num7 = x;
            int num8 = y;
            int num9 = WorldGen.genRand.Next(1, 3);
            int num10 = 0;
            float num11 = 11f;
            float num12 = 1f / num11;
            for (int i = 0; i < num2; i++)
            {
                if (progress != null)
                {
                    float num13 = (float)i / (float)num2;
                    progress.Set((double)(num13 * num12));
                }
                num10++;
                int num14 = num3;
                int num15 = num7;
                int num16 = num8;
                bool flag = true;
                int num17 = 0;
                int num18 = 0;
                int num19 = -10;
                Rectangle rectangle = new Rectangle(num15 - num17 / 2, num16 - num18 / 2, num17, num18);
                while (flag)
                {
                    num15 = num7;
                    num16 = num8;
                    num17 = WorldGen.genRand.Next(25, 50);
                    num18 = WorldGen.genRand.Next(20, 35);
                    if (num18 > num17)
                    {
                        num18 = num17;
                    }
                    bool flag2 = num16 + 70 >= Main.UnderworldLayer - 10;
                    if (i == num2 - 1 || flag2)
                    {
                        num2 = i + 1;
                        num17 = WorldGen.genRand.Next(55, 65);
                        num18 = WorldGen.genRand.Next(45, 50);
                        if (num18 > num17)
{
                            num18 = num17;
                        }
                        num17 = (int)((double)num17 * 1.6);
                        num18 = (int)((double)num18 * 1.35);
                        num16 += WorldGen.genRand.Next(5, 10);
                    }
                    if (num10 > num9)
                    {
                        num16 += WorldGen.genRand.Next(num18 + 1, num18 + 3) + num19;
                        num15 += WorldGen.genRand.Next(-5, 6);
                        num14 = num3 * -1;
                    }
                    else
                    {
                        num15 += (WorldGen.genRand.Next(num17 + 1, num17 + 3) + num19) * num14;
                        num16 += WorldGen.genRand.Next(-5, 6);
                    }
                    flag = false;
                    int num20 = num15 - num17 / 2;
                    int num21 = num16 - num18 / 2;
                    rectangle = new Rectangle(num20, num21, num17, num18);
                    if (flag2)
                    {
                        break;
                    }
                    for (int j = 0; j < i; j++)
                    {
                        if (rectangle.Intersects(array[j]))
{
                            flag = true;
                        }
                        if (WorldGen.genRand.Next(100) == 0)
{
                            num19++;
                        }
                    }
                }
                if (num10 > num9)
                {
                    num9++;
                    num10 = 1;
                }
                array[i] = rectangle;
                num3 = num14;
                num7 = num15;
                num8 = num16;
            }
            for (int k = 0; k < num2; k++)
            {
                if (progress != null)
                {
                    float num22 = (float)k / (float)num2;
                    progress.Set((double)(num12 + num22 * num12 * 5f));
                }
                for (int l = 0; l < 2; l++)
                {
                    for (int m = 0; m < num2; m++)
                    {
                        for (int n = 0; n < 2; n++)
{
                            int num23 = array[k].X;
                            if (l == 1)
{
                                num23 += array[k].Width - 1;
                            }
                            int num24 = array[k].Y;
                            int num25 = num24 + array[k].Height;
                            int num26 = array[m].X;
                            if (n == 1)
{
                                num26 += array[m].Width - 1;
                            }
                            int y2 = array[m].Y;
                            int num27 = y2 + array[m].Height;
                            while (num23 != num26 || num24 != y2 || num25 != num27)
{
                                if (num23 < num26)
{
                                    num23++;
                                }
                                if (num23 > num26)
{
                                    num23--;
                                }
                                if (num24 < y2)
{
                                    num24++;
                                }
                                if (num24 > y2)
{
                                    num24--;
                                }
                                if (num25 < num27)
{
                                    num25++;
                                }
                                if (num25 > num27)
{
                                    num25--;
                                }
                                int num28 = num23;
                                for (int num29 = num24; num29 < num25; num29++)
{
                                    Main.tile[num28, num29].active(true);
                                    Main.tile[num28, num29].type = 226;
                                    Main.tile[num28, num29].liquid = 0;
                                    Main.tile[num28, num29].slope(0);
                                    Main.tile[num28, num29].halfBrick(false);
                                }
                            }
                        }
                    }
                }
            }
            for (int num30 = 0; num30 < num2; num30++)
            {
                if (progress != null)
                {
                    float num31 = (float)num30 / (float)num2;
                    progress.Set((double)(num12 * 6f + num31 * num12));
                }
                if (!false)
                {
                    for (int num32 = array[num30].X; num32 < array[num30].X + array[num30].Width; num32++)
                    {
                        for (int num33 = array[num30].Y; num33 < array[num30].Y + array[num30].Height; num33++)
{
                            Main.tile[num32, num33].active(true);
                            Main.tile[num32, num33].type = 226;
                            Main.tile[num32, num33].liquid = 0;
                            Main.tile[num32, num33].slope(0);
                            Main.tile[num32, num33].halfBrick(false);
                        }
                    }
                    int num34 = array[num30].X;
                    int num35 = num34 + array[num30].Width;
                    int num36 = array[num30].Y;
                    int num37 = num36 + array[num30].Height;
                    num34 += WorldGen.genRand.Next(3, 8);
                    num35 -= WorldGen.genRand.Next(3, 8);
                    num36 += WorldGen.genRand.Next(3, 8);
                    num37 -= WorldGen.genRand.Next(3, 8);
                    int num38 = num34;
                    int num39 = num35;
                    int num40 = num36;
                    int num41 = num37;
                    int num42 = (num34 + num35) / 2;
                    int num43 = (num36 + num37) / 2;
                    for (int num44 = num34; num44 < num35; num44++)
                    {
                        for (int num45 = num36; num45 < num37; num45++)
{
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num40 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num41 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num38 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num39 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (num38 < num34)
{
                                num38 = num34;
                            }
                            if (num39 > num35)
{
                                num39 = num35;
                            }
                            if (num40 < num36)
{
                                num40 = num36;
                            }
                            if (num41 > num37)
{
                                num41 = num37;
                            }
                            if (num38 > num42)
{
                                num38 = num42;
                            }
                            if (num39 < num42)
{
                                num39 = num42;
                            }
                            if (num40 > num43)
{
                                num40 = num43;
                            }
                            if (num41 < num43)
{
                                num41 = num43;
                            }
                            if (num44 >= num38 && ((num44 < num39) & (num45 >= num40)) && num45 <= num41)
{
                                Main.tile[num44, num45].active(false);
                                Main.tile[num44, num45].wall = 87;
                            }
                        }
                    }
                    for (int num46 = num37; num46 > num36; num46--)
                    {
                        for (int num47 = num35; num47 > num34; num47--)
{
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num40 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num41 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num38 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (WorldGen.genRand.Next(20) == 0)
{
                                num39 += WorldGen.genRand.Next(-1, 2);
                            }
                            if (num38 < num34)
{
                                num38 = num34;
                            }
                            if (num39 > num35)
{
                                num39 = num35;
                            }
                            if (num40 < num36)
{
                                num40 = num36;
                            }
                            if (num41 > num37)
{
                                num41 = num37;
                            }
                            if (num38 > num42)
{
                                num38 = num42;
                            }
                            if (num39 < num42)
{
                                num39 = num42;
                            }
                            if (num40 > num43)
{
                                num40 = num43;
                            }
                            if (num41 < num43)
{
                                num41 = num43;
                            }
                            if (num47 >= num38 && ((num47 < num39) & (num46 >= num40)) && num46 <= num41)
{
                                Main.tile[num47, num46].active(false);
                                Main.tile[num47, num46].wall = 87;
                            }
                        }
                    }
                }
            }
            Vector2D vector2D;
            vector2D..ctor((double)num5, (double)num6);
            for (int num48 = 0; num48 < num2; num48++)
            {
                if (progress != null)
                {
                    float num49 = (float)num48 / (float)num2;
                    progress.Set((double)(num12 * 7f + num49 * num12));
                }
                Rectangle rectangle2 = array[num48];
                rectangle2.X += 8;
                rectangle2.Y += 8;
                rectangle2.Width -= 16;
                rectangle2.Height -= 16;
                bool flag3 = true;
                while (flag3)
                {
                    int num50 = WorldGen.genRand.Next(rectangle2.X, rectangle2.X + rectangle2.Width);
                    int num51 = WorldGen.genRand.Next(rectangle2.Y, rectangle2.Y + rectangle2.Height);
                    if (num48 == num2 - 1)
                    {
                        num50 = rectangle2.X + rectangle2.Width / 2 + WorldGen.genRand.Next(-10, 10);
                        num51 = rectangle2.Y + rectangle2.Height / 2 + WorldGen.genRand.Next(-10, 10);
                    }
                    vector2D = WorldGen.templePather(vector2D, num50, num51);
                    if (vector2D.X == (double)num50 && vector2D.Y == (double)num51)
                    {
                        flag3 = false;
                    }
                }
                if (num48 < num2 - 1)
                {
                    if (WorldGen.genRand.Next(3) != 0)
                    {
                        int num52 = num48 + 1;
                        if (array[num52].Y >= array[num48].Y + array[num48].Height)
{
                            rectangle2.X = array[num52].X;
                            if (num48 == 0)
{
                                if (num3 > 0)
{
                                    rectangle2.X += (int)((double)array[num52].Width * 0.8);
                                }
                                else
{
                                    rectangle2.X += (int)((double)array[num52].Width * 0.2);
                                }
                            }
                            else if (array[num52].X < array[num48].X)
{
                                rectangle2.X += (int)((double)array[num52].Width * 0.2);
                            }
                            else
{
                                rectangle2.X += (int)((double)array[num52].Width * 0.8);
                            }
                            rectangle2.Y = array[num52].Y;
                        }
                        else
{
                            rectangle2.X = (array[num48].X + array[num48].Width / 2 + array[num52].X + array[num52].Width / 2) / 2;
                            rectangle2.Y = (int)((double)array[num52].Y + (double)array[num52].Height * 0.8);
                        }
                        int x2 = rectangle2.X;
                        int y3 = rectangle2.Y;
                        flag3 = true;
                        while (flag3)
{
                            int num53 = WorldGen.genRand.Next(x2 - 6, x2 + 7);
                            int num54 = WorldGen.genRand.Next(y3 - 6, y3 + 7);
                            vector2D = WorldGen.templePather(vector2D, num53, num54);
                            if (vector2D.X == (double)num53 && vector2D.Y == (double)num54)
{
                                flag3 = false;
                            }
                        }
                    }
                    else
                    {
                        int num55 = num48 + 1;
                        int num56 = (array[num48].X + array[num48].Width / 2 + array[num55].X + array[num55].Width / 2) / 2;
                        int num57 = (array[num48].Y + array[num48].Height / 2 + array[num55].Y + array[num55].Height / 2) / 2;
                        flag3 = true;
                        while (flag3)
{
                            int num58 = WorldGen.genRand.Next(num56 - 6, num56 + 7);
                            int num59 = WorldGen.genRand.Next(num57 - 6, num57 + 7);
                            vector2D = WorldGen.templePather(vector2D, num58, num59);
                            if (vector2D.X == (double)num58 && vector2D.Y == (double)num59)
{
                                flag3 = false;
                            }
                        }
                    }
                }
            }
            int num60 = Main.maxTilesX - 20;
            int num61 = 20;
            int num62 = Main.maxTilesY - 20;
            int num63 = 20;
            for (int num64 = 0; num64 < num2; num64++)
            {
                if (array[num64].X != 0 && array[num64].Y != 0 && array[num64].Width != 0 && array[num64].Height != 0)
                {
                    if (array[num64].X < num60)
                    {
                        num60 = array[num64].X;
                    }
                    if (array[num64].X + array[num64].Width > num61)
                    {
                        num61 = array[num64].X + array[num64].Width;
                    }
                    if (array[num64].Y < num62)
                    {
                        num62 = array[num64].Y;
                    }
                    if (array[num64].Y + array[num64].Height > num63)
                    {
                        num63 = array[num64].Y + array[num64].Height;
                    }
                }
            }
            num60 -= 10;
            num61 += 10;
            num62 -= 10;
            num63 += 10;
            float num65 = num12 / 4f;
            for (int num66 = num60; num66 < num61; num66++)
            {
                if (progress != null)
                {
                    float num67 = (float)num66 / (float)num61;
                    progress.Set((double)(num12 * 8f + num67 * num65));
                }
                for (int num68 = num62; num68 < num63; num68++)
                {
                    WorldGen.outerTempled(num66, num68);
                }
            }
            for (int num69 = num61; num69 >= num60; num69--)
            {
                if (progress != null)
                {
                    float num70 = 1f - (float)num69 / (float)num61;
                    progress.Set((double)(num12 * 8f + num65 + num70 * num65));
                }
                for (int num71 = num62; num71 < num63; num71++)
                {
                    WorldGen.outerTempled(num69, num71);
                }
            }
            for (int num72 = num62; num72 < num63; num72++)
            {
                if (progress != null)
                {
                    float num73 = (float)num72 / (float)num63;
                    progress.Set((double)(num12 * 8f + num65 * 2f + num73 * num65));
                }
                for (int num74 = num60; num74 < num61; num74++)
                {
                    WorldGen.outerTempled(num74, num72);
                }
            }
            for (int num75 = num63; num75 >= num62; num75--)
            {
                if (progress != null)
                {
                    float num76 = 1f - (float)num75 / (float)num63;
                    progress.Set((double)(num12 * 8f + num65 * 3f + num76 * num65));
                }
                for (int num77 = num60; num77 < num61; num77++)
                {
                    WorldGen.outerTempled(num77, num75);
                }
            }
            int num78 = num6;
            num3 = -num4;
            Vector2D vector2D2;
            vector2D2..ctor((double)num5, (double)num6);
            int num79 = WorldGen.genRand.Next(2, 5);
            bool flag4 = true;
            int num80 = 0;
            int num81 = WorldGen.genRand.Next(9, 14);
            while (flag4)
            {
                num80++;
                if (num80 >= num81)
                {
                    num80 = 0;
                    vector2D2.Y -= 1.0;
                }
                vector2D2.X += (double)num3;
                int num82 = (int)vector2D2.X;
                flag4 = false;
                int num83 = (int)vector2D2.Y - num79;
                while ((double)num83 < vector2D2.Y + (double)num79)
                {
                    if (Main.tile[num82, num83].wall == 87 || (Main.tile[num82, num83].active() && Main.tile[num82, num83].type == 226))
                    {
                        flag4 = true;
                    }
                    if (Main.tile[num82, num83].active() && Main.tile[num82, num83].type == 226)
                    {
                        if (num83 > num78)
{
                            num78 = num83;
                        }
                        Main.tile[num82, num83].active(false);
                        Main.tile[num82, num83].wall = 87;
                    }
                    num83++;
                }
            }
            num78 += 2;
            int num84 = num5;
            int num85 = num6;
            while (!Main.tile[num84, num85].active())
            {
                num85++;
                if (num85 >= num78)
                {
                    num85 = num78;
                    Main.tile[num84, num85].ClearEverything();
                    Main.tile[num84, num85].active(true);
                    Main.tile[num84, num85].type = 226;
                    break;
                }
            }
            num85 -= 4;
            int num86 = num85;
            while ((Main.tile[num84, num86].active() && Main.tile[num84, num86].type == 226) || Main.tile[num84, num86].wall == 87)
            {
                num86--;
            }
            num86 += 2;
            for (int num87 = num84 - 1; num87 <= num84 + 1; num87++)
            {
                for (int num88 = num86; num88 <= num85; num88++)
                {
                    Main.tile[num87, num88].active(true);
                    Main.tile[num87, num88].type = 226;
                    Main.tile[num87, num88].liquid = 0;
                    Main.tile[num87, num88].slope(0);
                    Main.tile[num87, num88].halfBrick(false);
                }
            }
            for (int num89 = num84 - 4; num89 <= num84 + 4; num89++)
            {
                for (int num90 = num85 - 1; num90 < num85 + 3; num90++)
                {
                    Main.tile[num89, num90].active(false);
                    Main.tile[num89, num90].wall = 87;
                }
            }
            for (int num91 = num84 - 1; num91 <= num84 + 1; num91++)
            {
                for (int num92 = num85 - 5; num92 <= num85 + 8; num92++)
                {
                    Main.tile[num91, num92].active(true);
                    Main.tile[num91, num92].type = 226;
                    Main.tile[num91, num92].liquid = 0;
                    Main.tile[num91, num92].slope(0);
                    Main.tile[num91, num92].halfBrick(false);
                }
            }
            for (int num93 = num84 - 3; num93 <= num84 + 3; num93++)
            {
                for (int num94 = num85 - 2; num94 < num85 + 3; num94++)
                {
                    if (num94 >= num85 || num93 < num5 - 1 || num93 > num5 + 1)
                    {
                        Main.tile[num93, num94].active(false);
                        Main.tile[num93, num94].wall = 87;
                    }
                }
            }
            WorldGen.PlaceTile(num84, num85, 10, true, false, -1, 11);
            for (int num95 = num60; num95 < num61; num95++)
            {
                for (int num96 = num62; num96 < num63; num96++)
                {
                    WorldGen.templeCleaner(num95, num96);
                }
            }
            for (int num97 = num63; num97 >= num62; num97--)
            {
                for (int num98 = num61; num98 >= num60; num98--)
                {
                    WorldGen.templeCleaner(num98, num97);
                }
            }
            for (int num99 = num60; num99 < num61; num99++)
            {
                if (progress != null)
                {
                    float num100 = (float)num99 / (float)num61;
                    progress.Set((double)(num12 * 9f + num100 * num12));
                }
                for (int num101 = num62; num101 < num63; num101++)
                {
                    bool flag5 = true;
                    for (int num102 = num99 - 1; num102 <= num99 + 1; num102++)
                    {
                        for (int num103 = num101 - 1; num103 <= num101 + 1; num103++)
{
                            if ((!Main.tile[num102, num103].active() || Main.tile[num102, num103].type != 226) && Main.tile[num102, num103].wall != 87)
{
                                flag5 = false;
                                break;
                            }
                        }
                    }
                    if (flag5)
                    {
                        Main.tile[num99, num101].wall = 87;
                    }
                }
            }
            int num104 = 0;
            Rectangle rectangle3 = array[num2 - 1];
            int num105 = rectangle3.Width / 2;
            int num106 = rectangle3.Height / 2;
            int num107;
            int num108;
            for (;;)
            {
                num104++;
                num107 = rectangle3.X + num105 + 15 - WorldGen.genRand.Next(30);
                num108 = rectangle3.Y + num106 + 15 - WorldGen.genRand.Next(30);
                WorldGen.PlaceTile(num107, num108, 237, false, false, -1, 0);
                if (Main.tile[num107, num108].type == 237)
                {
                    break;
                }
                if (num104 >= 1000)
                {
                    goto Block_139;
                }
            }
            GenVars.lAltarX = num107 - (int)(Main.tile[num107, num108].frameX / 18);
            GenVars.lAltarY = num108 - (int)(Main.tile[num107, num108].frameY / 18);
            goto IL_1898;
            Block_139:
            num107 = rectangle3.X + num105;
            num108 = rectangle3.Y + num106;
            num107 += WorldGen.genRand.Next(-10, 11);
            num108 += WorldGen.genRand.Next(-10, 11);
            while (!Main.tile[num107, num108].active())
            {
                num108++;
            }
            Main.tile[num107 - 1, num108].active(true);
            Main.tile[num107 - 1, num108].slope(0);
            Main.tile[num107 - 1, num108].halfBrick(false);
            Main.tile[num107 - 1, num108].type = 226;
            Main.tile[num107, num108].active(true);
            Main.tile[num107, num108].slope(0);
            Main.tile[num107, num108].halfBrick(false);
            Main.tile[num107, num108].type = 226;
            Main.tile[num107 + 1, num108].active(true);
            Main.tile[num107 + 1, num108].slope(0);
            Main.tile[num107 + 1, num108].halfBrick(false);
            Main.tile[num107 + 1, num108].type = 226;
            num108 -= 2;
            num107--;
            for (int num109 = -1; num109 <= 3; num109++)
            {
                for (int num110 = -1; num110 <= 1; num110++)
                {
                    x = num107 + num109;
                    y = num108 + num110;
                    Main.tile[x, y].active(false);
                }
            }
            GenVars.lAltarX = num107;
            GenVars.lAltarY = num108;
            for (int num111 = 0; num111 <= 2; num111++)
            {
                for (int num112 = 0; num112 <= 1; num112++)
                {
                    x = num107 + num111;
                    y = num108 + num112;
                    Main.tile[x, y].active(true);
                    Main.tile[x, y].type = 237;
                    Main.tile[x, y].frameX = (short)(num111 * 18);
                    Main.tile[x, y].frameY = (short)(num112 * 18);
                }
            }
            for (int num113 = 0; num113 <= 2; num113++)
            {
                for (int num114 = 0; num114 <= 1; num114++)
                {
                    x = num107 + num113;
                    y = num108 + num114;
                    WorldGen.SquareTileFrame(x, y, true);
                }
            }
            IL_1898:
            double num115 = (double)num2 * 1.1;
            num115 *= 1.0 + (double)WorldGen.genRand.Next(-25, 26) * 0.01;
            if (WorldGen.drunkWorldGen)
            {
                num115 *= 1.5;
            }
            double num116 = num115;
            int num117 = 0;
            while (num115 > 0.0)
            {
                num117++;
                if (progress != null)
                {
                    double num118 = 1.0 - num115 / num116;
                    progress.Set((double)(num12 * 10f) + num118 * (double)num12);
                }
                int num119 = WorldGen.genRand.Next(num2);
                int num120 = WorldGen.genRand.Next(array[num119].X, array[num119].X + array[num119].Width);
                int num121 = WorldGen.genRand.Next(array[num119].Y, array[num119].Y + array[num119].Height);
                if (Main.tile[num120, num121].wall == 87 && !Main.tile[num120, num121].active())
                {
                    bool flag6 = false;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        int num122 = 1;
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num122 = -1;
                        }
                        while (!Main.tile[num120, num121].active())
{
                            num121 += num122;
                        }
                        num121 -= num122;
                        int num123 = WorldGen.genRand.Next(2);
                        int num124 = WorldGen.genRand.Next(3, 10);
                        bool flag7 = true;
                        for (int num125 = num120 - num124; num125 < num120 + num124; num125++)
{
                            for (int num126 = num121 - num124; num126 < num121 + num124; num126++)
{
                                if (Main.tile[num125, num126].active() && (Main.tile[num125, num126].type == 10 || Main.tile[num125, num126].type == 237))
{
                                    flag7 = false;
                                    break;
                                }
                            }
                        }
                        if (flag7)
{
                            for (int num127 = num120 - num124; num127 < num120 + num124; num127++)
{
                                for (int num128 = num121 - num124; num128 < num121 + num124; num128++)
{
                                    if (WorldGen.SolidTile(num127, num128, false) && Main.tile[num127, num128].type != 232 && !WorldGen.SolidTile(num127, num128 - num122, false))
{
                                        Main.tile[num127, num128].type = 232;
                                        flag6 = true;
                                        if (num123 == 0)
{
                                            Main.tile[num127, num128 - 1].type = 232;
                                            Main.tile[num127, num128 - 1].active(true);
                                            if (WorldGen.drunkWorldGen)
{
                                                Main.tile[num127, num128 - 2].type = 232;
                                                Main.tile[num127, num128 - 2].active(true);
                                            }
                                        }
                                        else
{
                                            Main.tile[num127, num128 + 1].type = 232;
                                            Main.tile[num127, num128 + 1].active(true);
                                            if (WorldGen.drunkWorldGen)
{
                                                Main.tile[num127, num128 + 2].type = 232;
                                                Main.tile[num127, num128 + 2].active(true);
                                            }
                                        }
                                        num123++;
                                        if (num123 > 1)
{
                                            num123 = 0;
                                        }
                                    }
                                }
                            }
                        }
                        if (flag6)
{
                            num117 = 0;
                            num115 -= 1.0;
                        }
                    }
                    else
                    {
                        int num129 = 1;
                        if (WorldGen.genRand.Next(2) == 0)
{
                            num129 = -1;
                        }
                        while (!Main.tile[num120, num121].active())
{
                            num120 += num129;
                        }
                        num120 -= num129;
                        int num130 = WorldGen.genRand.Next(2);
                        int num131 = WorldGen.genRand.Next(3, 10);
                        bool flag8 = true;
                        for (int num132 = num120 - num131; num132 < num120 + num131; num132++)
{
                            for (int num133 = num121 - num131; num133 < num121 + num131; num133++)
{
                                if (Main.tile[num132, num133].active() && Main.tile[num132, num133].type == 10)
{
                                    flag8 = false;
                                    break;
                                }
                            }
                        }
                        if (flag8)
{
                            for (int num134 = num120 - num131; num134 < num120 + num131; num134++)
{
                                for (int num135 = num121 - num131; num135 < num121 + num131; num135++)
{
                                    if (WorldGen.SolidTile(num134, num135, false) && Main.tile[num134, num135].type != 232 && !WorldGen.SolidTile(num134 - num129, num135, false))
{
                                        Main.tile[num134, num135].type = 232;
                                        flag6 = true;
                                        if (num130 == 0)
{
                                            Main.tile[num134 - 1, num135].type = 232;
                                            Main.tile[num134 - 1, num135].active(true);
                                            if (WorldGen.drunkWorldGen)
{
                                                Main.tile[num134 - 2, num135].type = 232;
                                                Main.tile[num134 - 2, num135].active(true);
                                            }
                                        }
                                        else
{
                                            Main.tile[num134 + 1, num135].type = 232;
                                            Main.tile[num134 + 1, num135].active(true);
                                            if (WorldGen.drunkWorldGen)
{
                                                Main.tile[num134 - 2, num135].type = 232;
                                                Main.tile[num134 - 2, num135].active(true);
                                            }
                                        }
                                        num130++;
                                        if (num130 > 1)
{
                                            num130 = 0;
                                        }
                                    }
                                }
                            }
                        }
                        if (flag6)
{
                            num117 = 0;
                            num115 -= 1.0;
                        }
                    }
                }
                if (num117 > 1000)
                {
                    num117 = 0;
                    num115 -= 1.0;
                }
            }
            if (progress != null)
            {
                progress.Set(1.0);
            }
            GenVars.tLeft = num60;
            GenVars.tRight = num61;
            GenVars.tTop = num62;
            GenVars.tBottom = num63;
            GenVars.tRooms = num2;
        }
References Terraria.Tile.active(), System.array, Terraria.Tile.ClearEverything(), Terraria.WorldGen.drunkWorldGen, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Tile.halfBrick(), Microsoft.Xna.Framework.Rectangle.Height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.outerTempled(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SquareTileFrame(), Terraria.WorldGen.templeCleaner(), Terraria.WorldGen.templePather(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Tile.wall, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, System.X, ReLogic.Utilities.Vector2D.X, Microsoft.Xna.Framework.Rectangle.Y, System.Y, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses().