Terraria Decompiled: Terraria.WorldGen.MoveTownNPC
MoveTownNPC()
static bool Terraria.WorldGen.MoveTownNPC (int x, int y, int n, IRoomCheckFeedback feedback = null) inline static
Definition at line 318 of file WorldGen.cs.
        {
            if (feedback == null)
            {
                feedback = NoRoomCheckFeedback.WithText;
            }
            bool stopOnFail = feedback.StopOnFail;
            bool displayText = feedback.DisplayText;
            feedback.BeginSpread(x, y);
            bool flag = WorldGen.StartRoomCheck(x, y, feedback);
            feedback.EndSpread();
            if (!flag)
            {
                string text = Lang.inter[40].Value;
                switch (WorldGen.roomCheckFailureReason)
                {
                case TownNPCRoomCheckFailureReason.TooCloseToWorldEdge:
                    text = Language.GetTextValue("TownNPCHousingFailureReasons.TooCloseToWorldEdge");
                    break;
                case TownNPCRoomCheckFailureReason.RoomIsTooBig:
                    text = Language.GetTextValue("TownNPCHousingFailureReasons.RoomIsTooBig");
                    break;
                case TownNPCRoomCheckFailureReason.RoomIsTooSmall:
                    text = Language.GetTextValue("TownNPCHousingFailureReasons.RoomIsTooSmall");
                    break;
                case TownNPCRoomCheckFailureReason.HoleInWallIsTooBig:
                    text = Language.GetTextValue("TownNPCHousingFailureReasons.HoleInWallIsTooBig");
                    break;
                case TownNPCRoomCheckFailureReason.RoomCheckStartedInASolidTile:
                    text = Language.GetTextValue("TownNPCHousingFailureReasons.RoomCheckStartedInASolidTile");
                    break;
                case TownNPCRoomCheckFailureReason.TooManyUnsafeWalls:
                    text = Language.GetTextValue("TownNPCHousingFailureReasons.RoomHasUnsafeWalls");
                    break;
                }
                if (displayText)
                {
                    Main.NewText(text, byte.MaxValue, 240, 20);
                }
                if (stopOnFail)
                {
                    return false;
                }
            }
            if (!WorldGen.RoomNeeds())
            {
                int num = 0;
                int num2 = (WorldGen.roomTorch ? 0 : 1) + (WorldGen.roomDoor ? 0 : 1) + (WorldGen.roomTable ? 0 : 1) + (WorldGen.roomChair ? 0 : 1);
                string[] array = new string[num2];
                if (!WorldGen.roomTorch)
                {
                    array[num] = Language.GetTextValue("Game.HouseLightSource");
                    num++;
                }
                if (!WorldGen.roomDoor)
                {
                    array[num] = Language.GetTextValue("Game.HouseDoor");
                    num++;
                }
                if (!WorldGen.roomTable)
                {
                    array[num] = Language.GetTextValue("Game.HouseTable");
                    num++;
                }
                if (!WorldGen.roomChair)
                {
                    array[num] = Language.GetTextValue("Game.HouseChair");
                    num++;
                }
                string text2 = "Game.HouseMissing_" + num2;
                object[] array2 = array;
                string textValue = Language.GetTextValue(text2, array2);
                if (!WorldGen.roomTable || !WorldGen.roomChair)
                {
                    WorldGen.builtHouseWithNoFurniture = true;
                }
                if (!WorldGen.roomTorch)
                {
                    WorldGen.builtHouseWithNoLight = true;
                }
                if (displayText)
                {
                    Main.NewText(textValue, byte.MaxValue, 240, 20);
                }
                if (stopOnFail)
                {
                    return false;
                }
            }
            int type = WorldGen.prioritizedTownNPCType;
            if (n >= 0)
            {
                type = Main.npc[n].type;
            }
            bool flag2 = NPCID.Sets.IsTownPet[type];
            if (WorldGen.roomHasStinkbug && !flag2)
            {
                if (displayText)
                {
                    Main.NewText(Language.GetTextValue("TownNPCHousingFailureReasons.RoomHasAStinkbug"), byte.MaxValue, 240, 20);
                }
                if (stopOnFail)
                {
                    return false;
                }
            }
            if (WorldGen.roomHasEchoStinkbug && !flag2)
            {
                if (displayText)
                {
                    Main.NewText(Language.GetTextValue("TownNPCHousingFailureReasons.RoomHasAnEchoStinkbug"), byte.MaxValue, 240, 20);
                }
                if (stopOnFail)
                {
                    return false;
                }
            }
            feedback.BeginScoring();
            WorldGen.ScoreRoom(-1, type, feedback);
            feedback.EndScoring();
            if (WorldGen.hiScore <= 0)
            {
                if (displayText)
                {
                    if (WorldGen.roomOccupied)
                    {
                        Main.NewText(Lang.inter[41].Value, byte.MaxValue, 240, 20);
                    }
                    else if (WorldGen.roomEvil)
                    {
                        Main.NewText(Lang.inter[42].Value, byte.MaxValue, 240, 20);
                    }
                    else if (!WorldGen.roomHasStandingSpace)
                    {
                        Main.NewText(Language.GetTextValue("TownNPCHousingFailureReasons.RoomHasNoStandingSpace"), byte.MaxValue, 240, 20);
                    }
                    else
                    {
                        Main.NewText(Lang.inter[40].Value, byte.MaxValue, 240, 20);
                    }
                }
                if (stopOnFail)
                {
                    return false;
                }
            }
            if (n >= 0 && !WorldGen.CheckSpecialTownNPCSpawningConditions(Main.npc[n].type))
            {
                if (displayText)
                {
                    Main.NewText(Lang.inter[55].Value + " " + Main.npc[n].TypeName, byte.MaxValue, 240, 20);
                }
                if (stopOnFail)
                {
                    return false;
                }
            }
            return true;
        }
References System.array, Terraria.WorldGen.CheckSpecialTownNPCSpawningConditions(), Terraria.Localization.Language.GetTextValue(), Terraria.WorldGen.hiScore, Terraria.Lang.inter, Terraria.ID.NPCID.Sets.IsTownPet, Terraria.Main.NewText(), Terraria.Main.npc, Terraria.WorldGen.prioritizedTownNPCType, Terraria.WorldGen.roomChair, Terraria.WorldGen.roomCheckFailureReason, Terraria.WorldGen.roomDoor, Terraria.WorldGen.roomEvil, Terraria.WorldGen.roomHasEchoStinkbug, Terraria.WorldGen.roomHasStandingSpace, Terraria.WorldGen.roomHasStinkbug, Terraria.WorldGen.RoomNeeds(), Terraria.WorldGen.roomOccupied, Terraria.WorldGen.roomTable, Terraria.WorldGen.roomTorch, Terraria.WorldGen.ScoreRoom(), Terraria.WorldGen.StartRoomCheck(), Terraria.DataStructures.NoRoomCheckFeedback.StopOnFail, System.text, Terraria.NPC.type, Terraria.NPC.TypeName, Terraria.Localization.LocalizedText.Value, and Terraria.DataStructures.NoRoomCheckFeedback.WithText.
Referenced by Terraria.Main.PerformHousingCheck(), and Terraria.Main.TryMovingNPC().