Terraria Decompiled: Terraria.WorldGen.SectionTileFrame
SectionTileFrame()
static void Terraria.WorldGen.SectionTileFrame (int sectionStartX, int sectionStartY, int sectionEndXInclusive, int sectionEndYInclusive) inline static
Definition at line 80998 of file WorldGen.cs.
        {
            Main.mapTime = Main.mapTimeMax + 10;
            int num;
            int num2;
            int num3;
            int num4;
            WorldGen.GetSectionBounds(sectionStartX, sectionStartY, sectionEndXInclusive, sectionEndYInclusive, out num, out num2, out num3, out num4);
            MapUpdateQueue.Add(new Rectangle(num - 2, num3 - 2, num2 - num + 4, num4 - num3 + 4));
            for (int i = num - 1; i < num2 + 1; i++)
            {
                for (int j = num3 - 1; j < num4 + 1; j++)
                {
                    if (Main.tile[i, j] == null)
                    {
                        Main.tile[i, j] = new Tile();
                    }
                    WorldGen.Reframe(i, j, true);
                }
            }
            for (int k = sectionStartX; k <= sectionEndXInclusive; k++)
            {
                for (int l = sectionStartY; l <= sectionEndYInclusive; l++)
                {
                    Main.sectionManager.SetSectionFramed(k, l);
                }
            }
        }
References Terraria.Map.MapUpdateQueue.Add(), Terraria.WorldGen.GetSectionBounds(), Terraria.WorldGen.Reframe(), Terraria.Main.sectionManager, Terraria.WorldSections.SetSectionFramed(), Terraria.DataStructures.Tile, and Terraria.Main.tile.
Referenced by Terraria.MessageBuffer.GetData(), and Terraria.WorldGen.SectionTileFrameWithCheck().