Terraria Decompiled: Terraria.WorldGen.GrowUndergroundTree
GrowUndergroundTree()
static void Terraria.WorldGen.GrowUndergroundTree (int i, int y, int treeHeightAddon = 0) inline static
Definition at line 28147 of file WorldGen.cs.
        {
            if (Main.tile[i, y].type != 60)
            {
                return;
            }
            if (Main.tile[i, y].nactive() && !Main.tile[i, y].halfBrick() && Main.tile[i, y].slope() == 0 && Main.tile[i, y].type == 60 && ((Main.tile[i - 1, y].active() && Main.tile[i - 1, y].type == 60) || (Main.tile[i + 1, y].active() && Main.tile[i + 1, y].type == 60)))
            {
                int num = 1;
                int num2 = WorldGen.genRand.Next(5, 15) + treeHeightAddon;
                int num3 = num2 + 2;
                if (Main.tile[i, y].type == 60)
                {
                    num3 += 5;
                }
                if (WorldGen.EmptyTileCheck(i - num, i + num, y - num3, y - 1, 20))
                {
                    bool flag = false;
                    bool flag2 = false;
                    int num4;
                    for (int j = y - num2; j < y; j++)
                    {
                        Main.tile[i, j].active(true);
                        Main.tile[i, j].type = 5;
                        num4 = WorldGen.genRand.Next(3);
                        int num5 = WorldGen.genRand.Next(10);
                        if (j == y - 1 || j == y - num2)
{
                            num5 = 0;
                        }
                        while (((num5 == 5 || num5 == 7) && flag) || ((num5 == 6 || num5 == 7) && flag2))
{
                            num5 = WorldGen.genRand.Next(10);
                        }
                        flag = false;
                        flag2 = false;
                        if (num5 == 5 || num5 == 7)
{
                            flag = true;
                        }
                        if (num5 == 6 || num5 == 7)
{
                            flag2 = true;
                        }
                        if (num5 == 1)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 2)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 44;
                            }
                        }
                        else if (num5 == 3)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 44;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 44;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 44;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 4)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 22;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 5)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 88;
                                Main.tile[i, j].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 88;
                                Main.tile[i, j].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 88;
                                Main.tile[i, j].frameY = 44;
                            }
                        }
                        else if (num5 == 6)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 66;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 66;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 66;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else if (num5 == 7)
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 110;
                                Main.tile[i, j].frameY = 66;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 110;
                                Main.tile[i, j].frameY = 88;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 110;
                                Main.tile[i, j].frameY = 110;
                            }
                        }
                        else
{
                            if (num4 == 0)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 0;
                            }
                            if (num4 == 1)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 22;
                            }
                            if (num4 == 2)
{
                                Main.tile[i, j].frameX = 0;
                                Main.tile[i, j].frameY = 44;
                            }
                        }
                        if (num5 == 5 || num5 == 7)
{
                            Main.tile[i - 1, j].active(true);
                            Main.tile[i - 1, j].type = 5;
                            num4 = WorldGen.genRand.Next(3);
                            if (WorldGen.genRand.Next(3) < 2)
{
                                if (num4 == 0)
{
                                    Main.tile[i - 1, j].frameX = 44;
                                    Main.tile[i - 1, j].frameY = 198;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i - 1, j].frameX = 44;
                                    Main.tile[i - 1, j].frameY = 220;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i - 1, j].frameX = 44;
                                    Main.tile[i - 1, j].frameY = 242;
                                }
                            }
                            else
{
                                if (num4 == 0)
{
                                    Main.tile[i - 1, j].frameX = 66;
                                    Main.tile[i - 1, j].frameY = 0;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i - 1, j].frameX = 66;
                                    Main.tile[i - 1, j].frameY = 22;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i - 1, j].frameX = 66;
                                    Main.tile[i - 1, j].frameY = 44;
                                }
                            }
                        }
                        if (num5 == 6 || num5 == 7)
{
                            Main.tile[i + 1, j].active(true);
                            Main.tile[i + 1, j].type = 5;
                            num4 = WorldGen.genRand.Next(3);
                            if (WorldGen.genRand.Next(3) < 2)
{
                                if (num4 == 0)
{
                                    Main.tile[i + 1, j].frameX = 66;
                                    Main.tile[i + 1, j].frameY = 198;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i + 1, j].frameX = 66;
                                    Main.tile[i + 1, j].frameY = 220;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i + 1, j].frameX = 66;
                                    Main.tile[i + 1, j].frameY = 242;
                                }
                            }
                            else
{
                                if (num4 == 0)
{
                                    Main.tile[i + 1, j].frameX = 88;
                                    Main.tile[i + 1, j].frameY = 66;
                                }
                                if (num4 == 1)
{
                                    Main.tile[i + 1, j].frameX = 88;
                                    Main.tile[i + 1, j].frameY = 88;
                                }
                                if (num4 == 2)
{
                                    Main.tile[i + 1, j].frameX = 88;
                                    Main.tile[i + 1, j].frameY = 110;
                                }
                            }
                        }
                    }
                    int num6 = WorldGen.genRand.Next(3);
                    bool flag3 = false;
                    bool flag4 = false;
                    if (Main.tile[i - 1, y].nactive() && !Main.tile[i - 1, y].halfBrick() && Main.tile[i - 1, y].slope() == 0 && (Main.tile[i - 1, y].type == 2 || Main.tile[i - 1, y].type == 23 || Main.tile[i - 1, y].type == 60 || Main.tile[i - 1, y].type == 109 || Main.tile[i - 1, y].type == 147))
                    {
                        flag3 = true;
                    }
                    if (Main.tile[i + 1, y].nactive() && !Main.tile[i + 1, y].halfBrick() && Main.tile[i + 1, y].slope() == 0 && (Main.tile[i + 1, y].type == 2 || Main.tile[i + 1, y].type == 23 || Main.tile[i + 1, y].type == 60 || Main.tile[i + 1, y].type == 109 || Main.tile[i + 1, y].type == 147))
                    {
                        flag4 = true;
                    }
                    if (!flag3)
                    {
                        if (num6 == 0)
{
                            num6 = 2;
                        }
                        if (num6 == 1)
{
                            num6 = 3;
                        }
                    }
                    if (!flag4)
                    {
                        if (num6 == 0)
{
                            num6 = 1;
                        }
                        if (num6 == 2)
{
                            num6 = 3;
                        }
                    }
                    if (flag3 && !flag4)
                    {
                        num6 = 2;
                    }
                    if (flag4 && !flag3)
                    {
                        num6 = 1;
                    }
                    if (num6 == 0 || num6 == 1)
                    {
                        Main.tile[i + 1, y - 1].active(true);
                        Main.tile[i + 1, y - 1].type = 5;
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i + 1, y - 1].frameX = 22;
                            Main.tile[i + 1, y - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i + 1, y - 1].frameX = 22;
                            Main.tile[i + 1, y - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i + 1, y - 1].frameX = 22;
                            Main.tile[i + 1, y - 1].frameY = 176;
                        }
                    }
                    if (num6 == 0 || num6 == 2)
                    {
                        Main.tile[i - 1, y - 1].active(true);
                        Main.tile[i - 1, y - 1].type = 5;
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i - 1, y - 1].frameX = 44;
                            Main.tile[i - 1, y - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i - 1, y - 1].frameX = 44;
                            Main.tile[i - 1, y - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i - 1, y - 1].frameX = 44;
                            Main.tile[i - 1, y - 1].frameY = 176;
                        }
                    }
                    num4 = WorldGen.genRand.Next(3);
                    if (num6 == 0)
                    {
                        if (num4 == 0)
{
                            Main.tile[i, y - 1].frameX = 88;
                            Main.tile[i, y - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, y - 1].frameX = 88;
                            Main.tile[i, y - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, y - 1].frameX = 88;
                            Main.tile[i, y - 1].frameY = 176;
                        }
                    }
                    else if (num6 == 1)
                    {
                        if (num4 == 0)
{
                            Main.tile[i, y - 1].frameX = 0;
                            Main.tile[i, y - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, y - 1].frameX = 0;
                            Main.tile[i, y - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, y - 1].frameX = 0;
                            Main.tile[i, y - 1].frameY = 176;
                        }
                    }
                    else if (num6 == 2)
                    {
                        if (num4 == 0)
{
                            Main.tile[i, y - 1].frameX = 66;
                            Main.tile[i, y - 1].frameY = 132;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, y - 1].frameX = 66;
                            Main.tile[i, y - 1].frameY = 154;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, y - 1].frameX = 66;
                            Main.tile[i, y - 1].frameY = 176;
                        }
                    }
                    if (WorldGen.genRand.Next(8) != 0)
                    {
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i, y - num2].frameX = 22;
                            Main.tile[i, y - num2].frameY = 198;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, y - num2].frameX = 22;
                            Main.tile[i, y - num2].frameY = 220;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, y - num2].frameX = 22;
                            Main.tile[i, y - num2].frameY = 242;
                        }
                    }
                    else
                    {
                        num4 = WorldGen.genRand.Next(3);
                        if (num4 == 0)
{
                            Main.tile[i, y - num2].frameX = 0;
                            Main.tile[i, y - num2].frameY = 198;
                        }
                        if (num4 == 1)
{
                            Main.tile[i, y - num2].frameX = 0;
                            Main.tile[i, y - num2].frameY = 220;
                        }
                        if (num4 == 2)
{
                            Main.tile[i, y - num2].frameX = 0;
                            Main.tile[i, y - num2].frameY = 242;
                        }
                    }
                    WorldGen.RangeFrame(i - 2, y - num2 - 1, i + 2, y + 1);
                    if (Main.netMode == 2 && !WorldGen.isGeneratingOrLoadingWorld)
                    {
                        NetMessage.SendTileSquare(-1, i - 1, y - num2, 3, num2, TileChangeType.None);
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.EmptyTileCheck(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), Terraria.WorldGen.isGeneratingOrLoadingWorld, Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.RangeFrame(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.Main.tile, and Terraria.Tile.type.