Terraria Decompiled: Terraria.WorldGen.CactusFrame
CactusFrame()
static void Terraria.WorldGen.CactusFrame (int i, int j) inline static
Definition at line 54959 of file WorldGen.cs.
        {
            try
            {
                int num = j;
                int num2 = i;
                if (!WorldGen.CheckCactus(i, j))
                {
                    while (Main.tile[num2, num].active() && Main.tile[num2, num].type == 80)
                    {
                        num++;
                        if (Main.tile[num2, num] == null)
{
                            return;
                        }
                        if (!Main.tile[num2, num].active() || Main.tile[num2, num].type != 80)
{
                            if (Main.tile[num2 - 1, num] != null && Main.tile[num2 - 1, num].active() && Main.tile[num2 - 1, num].type == 80 && Main.tile[num2 - 1, num - 1].active() && Main.tile[num2 - 1, num - 1].type == 80 && num2 >= i)
{
                                num2--;
                            }
                            if (Main.tile[num2 + 1, num] != null && Main.tile[num2 + 1, num].active() && Main.tile[num2 + 1, num].type == 80 && Main.tile[num2 + 1, num - 1].active() && Main.tile[num2 + 1, num - 1].type == 80 && num2 <= i)
{
                                num2++;
                            }
                        }
                    }
                    num--;
                    int num3 = i - num2;
                    if (Main.tile[i - 2, j] != null)
                    {
                        int num4 = (int)Main.tile[i - 2, j].type;
                        if (Main.tile[i - 1, j] != null)
{
                            int num5 = (int)Main.tile[i - 1, j].type;
                            if (Main.tile[i + 1, j] != null)
{
                                int num6 = (int)Main.tile[i + 1, j].type;
                                if (Main.tile[i, j - 1] != null)
{
                                    int num7 = (int)Main.tile[i, j - 1].type;
                                    if (num7 == 227)
{
                                        num7 = 80;
                                    }
                                    int num8 = (int)Main.tile[i, j + 1].type;
                                    int num9 = (int)Main.tile[i - 1, j + 1].type;
                                    int num10 = (int)Main.tile[i + 1, j + 1].type;
                                    if (!Main.tile[i - 2, j].active())
{
                                        num4 = -1;
                                    }
                                    if (!Main.tile[i - 1, j].active())
{
                                        num5 = -1;
                                    }
                                    if (!Main.tile[i + 1, j].active())
{
                                        num6 = -1;
                                    }
                                    if (!Main.tile[i, j - 1].active())
{
                                        num7 = -1;
                                    }
                                    if (!Main.tile[i, j + 1].active())
{
                                        num8 = -1;
                                    }
                                    if (!Main.tile[i - 1, j + 1].active())
{
                                        num9 = -1;
                                    }
                                    if (!Main.tile[i + 1, j + 1].active())
{
                                        num10 = -1;
                                    }
                                    short num11 = Main.tile[i, j].frameX;
                                    short num12 = Main.tile[i, j].frameY;
                                    if (num3 == 0)
{
                                        if (num7 != 80)
{
                                            if (num5 == 80 && num6 == 80 && num9 != 80 && num10 != 80 && num4 != 80)
{
                                                num11 = 90;
                                                num12 = 0;
                                            }
                                            else if (num5 == 80 && num9 != 80 && num4 != 80)
{
                                                num11 = 72;
                                                num12 = 0;
                                            }
                                            else if (num6 == 80 && num10 != 80)
{
                                                num11 = 18;
                                                num12 = 0;
                                            }
                                            else
{
                                                num11 = 0;
                                                num12 = 0;
                                            }
                                        }
                                        else if (num5 == 80 && num6 == 80 && num9 != 80 && num10 != 80 && num4 != 80)
{
                                            num11 = 90;
                                            num12 = 36;
                                        }
                                        else if (num5 == 80 && num9 != 80 && num4 != 80)
{
                                            num11 = 72;
                                            num12 = 36;
                                        }
                                        else if (num6 == 80 && num10 != 80)
{
                                            num11 = 18;
                                            num12 = 36;
                                        }
                                        else if (num8 >= 0 && Main.tileSolid[num8])
{
                                            num11 = 0;
                                            num12 = 36;
                                        }
                                        else
{
                                            num11 = 0;
                                            num12 = 18;
                                        }
                                    }
                                    else if (num3 == -1)
{
                                        if (num6 == 80)
{
                                            if (num7 != 80 && num8 != 80)
{
                                                num11 = 108;
                                                num12 = 36;
                                            }
                                            else if (num8 != 80)
{
                                                num11 = 54;
                                                num12 = 36;
                                            }
                                            else if (num7 != 80)
{
                                                num11 = 54;
                                                num12 = 0;
                                            }
                                            else
{
                                                num11 = 54;
                                                num12 = 18;
                                            }
                                        }
                                        else if (num7 != 80)
{
                                            num11 = 54;
                                            num12 = 0;
                                        }
                                        else
{
                                            num11 = 54;
                                            num12 = 18;
                                        }
                                    }
                                    else if (num3 == 1)
{
                                        if (num5 == 80)
{
                                            if (num7 != 80 && num8 != 80)
{
                                                num11 = 108;
                                                num12 = 18;
                                            }
                                            else if (num8 != 80)
{
                                                num11 = 36;
                                                num12 = 36;
                                            }
                                            else if (num7 != 80)
{
                                                num11 = 36;
                                                num12 = 0;
                                            }
                                            else
{
                                                num11 = 36;
                                                num12 = 18;
                                            }
                                        }
                                        else if (num7 != 80)
{
                                            num11 = 36;
                                            num12 = 0;
                                        }
                                        else
{
                                            num11 = 36;
                                            num12 = 18;
                                        }
                                    }
                                    if (num11 != Main.tile[i, j].frameX || num12 != Main.tile[i, j].frameY)
{
                                        Main.tile[i, j].frameX = num11;
                                        Main.tile[i, j].frameY = num12;
                                        WorldGen.TileFrameCosmetic(i - 1, j, Main.tile[i - 1, j], false);
                                        WorldGen.TileFrameCosmetic(i, j - 1, Main.tile[i, j - 1], false);
                                        WorldGen.TileFrameCosmetic(i, j + 1, Main.tile[i, j + 1], false);
                                        WorldGen.TileFrameCosmetic(i + 1, j, Main.tile[i + 1, j], false);
                                    }
                                }
                            }
                        }
                    }
                }
            }
            catch
            {
                Main.tile[i, j].frameX = 0;
                Main.tile[i, j].frameY = 0;
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CheckCactus(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Main.tile, Terraria.WorldGen.TileFrameCosmetic(), Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.TileFrameCosmetic().