Terraria Decompiled: Terraria.WorldGen.CheckUnderwaterPlant
CheckUnderwaterPlant()
static void Terraria.WorldGen.CheckUnderwaterPlant (ushort type, int x, int y) inline static
Definition at line 57296 of file WorldGen.cs.
        {
            if (!WorldGen.CanUnderwaterPlantGrowHere(type, x, y, true))
            {
                WorldGen.KillTile(x, y, false, false, false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(17, -1, -1, null, 0, (float)x, (float)y, 0f, 0, 0, 0);
                }
                WorldGen.SquareTileFrame(x, y, true);
                return;
            }
            Tile tileSafely = Framing.GetTileSafely(x, y - 1);
            Tile tileSafely2 = Framing.GetTileSafely(x, y);
            Tile tileSafely3 = Framing.GetTileSafely(x, y + 1);
            bool flag = tileSafely.active() && tileSafely.type == type;
            bool flag2 = tileSafely3.active() && tileSafely3.type == type;
            int num = (int)(tileSafely2.frameX / 18);
            tileSafely2.frameY = 0;
            if (flag)
            {
                if (1 > num || num > 7)
                {
                    tileSafely2.frameX = (short)(WorldGen.genRand.Next(1, 8) * 18);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                        return;
                    }
                }
            }
            else if (flag2)
            {
                if (7 > num || num > 12)
                {
                    tileSafely2.frameX = (short)(WorldGen.genRand.Next(7, 13) * 18);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                        return;
                    }
                }
            }
            else if (num != 0)
            {
                tileSafely2.frameX = 0;
                if (Main.netMode == 2)
                {
                    NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.Tile.frameX, Terraria.WorldGen.genRand, Terraria.Framing.GetTileSafely(), int, Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), and Terraria.WorldGen.SquareTileFrame().
Referenced by Terraria.WorldGen.TileFrameImportant().