Terraria Decompiled: Terraria.WorldGen.Convert_ActuallyConvertTorch
Convert_ActuallyConvertTorch()
static void Terraria.WorldGen.Convert_ActuallyConvertTorch (int conversionType, int x, int y, ref Tile theTile, int newStyle) inline static
Definition at line 54895 of file WorldGen.cs.
        {
            if (!theTile.active() || theTile.type != 4)
            {
                return;
            }
            int num = (int)(theTile.frameY / 22);
            if (conversionType == 0 && num == 22)
            {
                newStyle = 21;
            }
            if (num == newStyle)
            {
                return;
            }
            bool flag = conversionType == 1 || conversionType == 4 || conversionType == 2;
            theTile.frameY = (short)(newStyle * 22);
            if (flag && SpecialSeedFeatures.RainbowSandAndBlackSandWalls)
            {
                WorldGen.paintTile(x, y, 0, true, true);
                WorldGen.paintCoatTile(x, y, 0, true, true);
            }
            WorldGen.SquareTileFrame(x, y, true);
            NetMessage.SendTileSquare(-1, x, y, TileChangeType.None);
        }
References int, Terraria.WorldGen.paintCoatTile(), Terraria.WorldGen.paintTile(), Terraria.GameContent.SpecialSeedFeatures.RainbowSandAndBlackSandWalls, Terraria.NetMessage.SendTileSquare(), and Terraria.WorldGen.SquareTileFrame().
Referenced by Terraria.WorldGen.Convert().