Terraria Decompiled: Terraria.WorldGen.RenameWorldCallBack
RenameWorldCallBack()
static void Terraria.WorldGen.RenameWorldCallBack (object threadContext) inline static
Definition at line 2536 of file WorldGen.cs.
        {
            if (threadContext == null)
            {
                return;
            }
            Tuple<string, Action<string>> tuple = threadContext as Tuple<string, Action<string>>;
            if (tuple == null)
            {
                return;
            }
            string item = tuple.Item1;
            Action<string> item2 = tuple.Item2;
            Main.ToggleGameplayUpdates(false);
            WorldFile.LoadWorld();
            if (WorldGen.loadFailed)
            {
                Main.QueueMainThreadAction(delegate
                {
                    Main.LoadWorlds();
                    Main.GoToWorldSelect();
                });
                return;
            }
            Main.sectionManager.SetAllSectionsLoaded();
            Main.worldName = item;
            WorldFile.SaveWorld(false, true, false);
            Rain.ClearRain();
            Main.fastForwardTimeToDawn = false;
            Main.fastForwardTimeToDusk = false;
            Main.UpdateTimeRate();
            UIWorldSelect.NewlyGeneratedWorld = Main.ActiveWorldFileData;
            if (item2 != null)
            {
                item2(item);
            }
        }
References Terraria.Main.ActiveWorldFileData, Terraria.Rain.ClearRain(), Terraria.Main.GoToWorldSelect(), System.item, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, Terraria.WorldGen.loadFailed, Terraria.IO.WorldFile.LoadWorld(), Terraria.Main.LoadWorlds(), Terraria.Main.QueueMainThreadAction(), Terraria.IO.WorldFile.SaveWorld(), Terraria.Main.sectionManager, Terraria.WorldSections.SetAllSectionsLoaded(), Terraria.Main.ToggleGameplayUpdates(), and Terraria.Main.UpdateTimeRate().
Referenced by Terraria.WorldGen.RenameWorld().