Terraria Decompiled: Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType
ValidateTileSquareIsActiveAndOfType()
static bool Terraria.WorldGen.ValidateTileSquareIsActiveAndOfType (int topLeftX, int topLeftY, int width, int height, int type) inline static
Definition at line 35312 of file WorldGen.cs.
        {
            bool flag = false;
            for (int i = 0; i < width; i++)
            {
                for (int j = 0; j < height; j++)
                {
                    int num = topLeftX + i;
                    int num2 = topLeftY + j;
                    if (!WorldGen.InWorld(num, num2, 0))
                    {
                        return false;
                    }
                    Tile tile = Main.tile[num, num2];
                    if (tile != null && (!tile.active() || (int)tile.type != type))
                    {
                        flag = true;
                        break;
                    }
                }
                if (flag)
                {
                    break;
                }
            }
            if (flag)
            {
                for (int k = 0; k < width; k++)
                {
                    for (int l = 0; l < height; l++)
                    {
                        int num3 = topLeftX + k;
                        int num4 = topLeftY + l;
                        Tile tile2 = Main.tile[num3, num4];
                        if (tile2 != null && tile2.active() && (int)tile2.type == type)
{
                            WorldGen.KillTile(num3, num4, false, false, false);
                            if (Main.netMode != 0)
{
                                NetMessage.SendData(17, -1, -1, null, 0, (float)num3, (float)num4, 0f, 0, 0, 0);
                            }
                        }
                    }
                }
                return false;
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.InWorld(), Terraria.WorldGen.KillTile(), Terraria.Main.netMode, Terraria.NetMessage.SendData(), Terraria.Main.tile, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CloseDoor(), Terraria.Wiring.HitWireSingle(), Terraria.WorldGen.OpenDoor(), Terraria.WorldGen.ShiftTallGate(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.Player.TileInteractionsUse(), and Terraria.Wiring.ToggleCampFire().