Terraria Decompiled: Terraria.WorldGen.ShimmerMakeBiome
ShimmerMakeBiome()
static bool Terraria.WorldGen.ShimmerMakeBiome (int X, int Y) inline static
Definition at line 32194 of file WorldGen.cs.
        {
            int num = WorldGen.genRand.Next(2);
            double num2 = 0.6;
            double num3 = 1.3;
            double num4 = 0.3;
            if (num == 0)
            {
                num2 = 0.55;
                num3 = 2.0;
            }
            num2 *= 1.05 - WorldGen.genRand.NextDouble() * 0.1;
            num3 *= 1.05 - WorldGen.genRand.NextDouble() * 0.1;
            num4 *= 1.0 - WorldGen.genRand.NextDouble() * 0.1;
            int num5 = WorldGen.genRand.Next(105, 125);
            int num6 = (int)((double)num5 * num4);
            int num7 = (int)((double)num5 * num2);
            int num8 = WorldGen.genRand.Next(9, 13);
            int num9 = X - num5;
            int num10 = X + num5;
            int num11 = Y - num5;
            int num12 = Y + num5;
            for (int i = num11; i <= num12; i++)
            {
                for (int j = num9; j <= num10; j++)
                {
                    if (!WorldGen.InWorld(j, i, 50))
                    {
                        return false;
                    }
                    if (Main.tile[j, i].type == 203 || Main.tile[j, i].type == 25)
                    {
                        return false;
                    }
                }
            }
            int num13 = Y;
            if (WorldGen.genRand.Next(4) == 0)
            {
                num13 = Y - WorldGen.genRand.Next(2);
            }
            int num14 = Y - num8;
            if (WorldGen.genRand.Next(4) == 0)
            {
                num14 = Y - num8 - WorldGen.genRand.Next(2);
            }
            for (int k = num11; k <= num12; k++)
            {
                for (int l = num9; l <= num10; l++)
                {
                    Main.tile[l, k].liquid = 0;
                    if (WorldGen.genRand.Next(4) == 0)
                    {
                        num13 = Y - WorldGen.genRand.Next(2);
                    }
                    if (WorldGen.genRand.Next(4) == 0)
                    {
                        num14 = Y - num8 + WorldGen.genRand.Next(2);
                    }
                    int num15;
                    if (k > Y)
                    {
                        num15 = (int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)Math.Abs(k - Y) * 1.2 * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0));
                    }
                    else
                    {
                        num15 = (int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)Math.Abs(k - Y) * 1.4 * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0));
                    }
                    if (num15 < num5)
                    {
                        Main.tile[l, k].color(0);
                        Main.tile[l, k].wallColor(0);
                        Main.tile[l, k].slope(0);
                        Main.tile[l, k].halfBrick(false);
                        Main.tile[l, k].type = 1;
                        if (l > num9 + 5 + WorldGen.genRand.Next(2) && l < num10 - 5 - WorldGen.genRand.Next(2))
{
                            Main.tile[l, k].active(true);
                        }
                        if ((double)num15 < (double)num5 * 0.9)
{
                            Main.tile[l, k].wall = 0;
                        }
                    }
                    num15 = (int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)Math.Abs(k - Y) * num3 * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0));
                    if (k > num14 && k < num13)
                    {
                        Main.tile[l, k].active(false);
                    }
                    if (k < num13 && num15 < (int)((double)num7 * (1.0 + WorldGen.genRand.NextDouble() * 0.02)))
                    {
                        Main.tile[l, k].active(false);
                    }
                    num15 = (int)Math.Sqrt(Math.Pow((double)Math.Abs(l - X) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0) + Math.Pow((double)(Math.Abs(k - Y) * 2) * (1.0 + WorldGen.genRand.NextDouble() * 0.02), 2.0));
                    if (k >= Y - 1 && num15 < (int)((double)num6 * (1.0 + WorldGen.genRand.NextDouble() * 0.025)))
                    {
                        if (k <= Y + 2 || num15 != num6 - 1 || WorldGen.genRand.Next(2) != 0)
{
                            Main.tile[l, k].active(false);
                        }
                        if (k >= Y)
{
                            if (k == Y)
{
                                Main.tile[l, k].liquid = 127;
                            }
                            else
{
                                Main.tile[l, k].liquid = byte.MaxValue;
                            }
                            Main.tile[l, k].shimmer(true);
                        }
                    }
                }
            }
            if (num == 0)
            {
                num9 = (int)((double)X - (double)num5 * num4) - WorldGen.genRand.Next(-15, 1) - 5;
                num10 = (int)((double)X + (double)num5 * num4) + WorldGen.genRand.Next(0, 16);
                int m = num9;
                int num16 = 0;
                while (m < num10)
                {
                    int num17 = Y - 3;
                    while (!Main.tile[m, num17].active())
                    {
                        num17--;
                    }
                    num17 -= 4;
                    int n = WorldGen.genRand.Next(5, 10);
                    int num18 = WorldGen.genRand.Next(15, 21);
                    int num19 = m - n;
                    while (n > 0)
                    {
                        for (num19 = m - n; num19 < m + n; num19++)
{
                            Main.tile[num19, num17].active(true);
                            Main.tile[num19, num17].type = 1;
                        }
                        num16++;
                        if (WorldGen.genRand.Next(3) < num16)
{
                            num16 = 0;
                            n--;
                            m += WorldGen.genRand.Next(-1, 2);
                        }
                        if (num18 <= 0)
{
                            n--;
                        }
                        num18--;
                        num17++;
                    }
                    num19 -= WorldGen.genRand.Next(1, 3);
                    Main.tile[num19, num17 - 2].active(true);
                    Main.tile[num19, num17 - 2].type = 1;
                    Main.tile[num19, num17 - 1].active(true);
                    Main.tile[num19, num17 - 1].type = 1;
                    Main.tile[num19, num17].active(true);
                    Main.tile[num19, num17].type = 1;
                    if (WorldGen.genRand.Next(2) == 0)
                    {
                        Main.tile[num19, num17 + 1].active(true);
                        Main.tile[num19, num17 + 1].type = 1;
                        WorldGen.PlaceTight(num19, num17 + 2, false);
                    }
                    else
                    {
                        WorldGen.PlaceTight(num19, num17 + 1, false);
                    }
                    m += WorldGen.genRand.Next(9, 14);
                }
            }
            WorldGen.ShimmerMakeBiomeOpening(-1, X - num5, Y, num8);
            WorldGen.ShimmerMakeBiomeOpening(1, X + num5, Y, num8);
            int num20 = 70;
            for (int num21 = 0; num21 < 500; num21++)
            {
                int num22 = WorldGen.genRand.Next(X - num20, X + num20);
                int num23 = WorldGen.genRand.Next(Y - 2, Y + 3);
                int num24 = WorldGen.genRand.Next(7);
                int num25 = 0;
                switch (num24)
                {
                case 0:
                    num25 = 583;
                    break;
                case 1:
                    num25 = 584;
                    break;
                case 2:
                    num25 = 585;
                    break;
                case 3:
                    num25 = 586;
                    break;
                case 4:
                    num25 = 587;
                    break;
                case 5:
                    num25 = 588;
                    break;
                case 6:
                    num25 = 589;
                    break;
                }
                if (WorldGen.SolidTile(num22 - 1, num23, false) && WorldGen.SolidTile(num22 + 1, num23, false))
                {
                    WorldGen.TryGrowingTreeByType(num25, num22, num23, 0, false);
                }
            }
            return true;
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Tile.color(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.InWorld(), Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.UnifiedRandom.NextDouble(), Terraria.WorldGen.PlaceTight(), System.Math.Pow(), Terraria.Tile.shimmer(), Terraria.WorldGen.ShimmerMakeBiomeOpening(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), System.Math.Sqrt(), Terraria.Main.tile, Terraria.WorldGen.TryGrowingTreeByType(), Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), System.X, and System.Y.
Referenced by Terraria.WorldGen.AddPasses().