Terraria Decompiled: Terraria.WorldGen.tileCounterNext
tileCounterNext()
static void Terraria.WorldGen.tileCounterNext (int x, int y) inline static
Definition at line 6040 of file WorldGen.cs.
        {
            if (WorldGen.tileCounterNum >= WorldGen.tileCounterMax)
            {
                return;
            }
            if (x < 5 || x > Main.maxTilesX - 5 || y < 5 || y > Main.maxTilesY - 5)
            {
                return;
            }
            if (Main.tile[x, y].active() && Main.tileSolid[(int)Main.tile[x, y].type] && TileID.Sets.CanBeClearedDuringGeneration[(int)Main.tile[x, y].type])
            {
                for (int i = 0; i < WorldGen.tileCounterNum; i++)
                {
                    if (WorldGen.tileCounterX[i] == x && WorldGen.tileCounterY[i] == y)
                    {
                        return;
                    }
                }
                WorldGen.tileCounterX[WorldGen.tileCounterNum] = x;
                WorldGen.tileCounterY[WorldGen.tileCounterNum] = y;
                WorldGen.tileCounterNum++;
                WorldGen.tileCounterNext(x - 1, y);
                WorldGen.tileCounterNext(x + 1, y);
                WorldGen.tileCounterNext(x, y - 1);
                WorldGen.tileCounterNext(x, y + 1);
            }
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.CanBeClearedDuringGeneration, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.WorldGen.tileCounterMax, Terraria.WorldGen.tileCounterNext(), Terraria.WorldGen.tileCounterNum, Terraria.WorldGen.tileCounterX, Terraria.WorldGen.tileCounterY, Terraria.Main.tileSolid, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.tileCounter(), and Terraria.WorldGen.tileCounterNext().