Terraria Decompiled: Terraria.WorldGen.FinishNoTraps
FinishNoTraps()
static void Terraria.WorldGen.FinishNoTraps () inline static private
Definition at line 23090 of file WorldGen.cs.
        {
            WorldGen.SetBoulderSolidity(false);
            int num = 5;
            if (WorldGen.getGoodWorldGen && !WorldGen.tenthAnniversaryWorldGen)
            {
                num = 2;
            }
            for (int i = 50; i < Main.maxTilesX - 50; i++)
            {
                for (int j = 50; j < Main.maxTilesY - 50; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (WorldGen.genRand.Next(num) == 0 && tile.active() && tile.type == 12 && tile.frameX == 0 && tile.frameY == 0)
                    {
                        Main.tile[i, j].type = 665;
                        Main.tile[i, j + 1].type = 665;
                        Main.tile[i + 1, j].type = 665;
                        Main.tile[i + 1, j + 1].type = 665;
                    }
                    if (i % 2 == 0 && j % 2 == 0 && Main.tile[i, j].active() && (Main.tile[i, j].type == 105 || (Main.tile[i, j].type == 467 && (Main.tile[i, j].frameX == 144 || Main.tile[i, j].frameX == 162))))
                    {
                        bool flag = false;
                        for (int k = i - 1; k <= i + 1; k++)
{
                            for (int l = j - 1; l <= j + 1; l++)
{
                                if (Main.tile[k, l].wire())
{
                                    flag = true;
                                }
                            }
                        }
                        if (!flag)
{
                            bool flag2 = false;
                            int num2 = 25;
                            int num3 = -1;
                            int num4 = -1;
                            for (int m = 0; m < num2 * num2; m++)
{
                                num3 = WorldGen.genRand.Next(i - num2, i + num2 + 1);
                                num4 = WorldGen.genRand.Next(j - num2, j + num2 + 1);
                                if (Main.tile[num3, num4].wire())
{
                                    flag2 = true;
                                    break;
                                }
                            }
                            if (flag2)
{
                                int num5 = i;
                                int num6 = j;
                                Main.tile[num5, num6].wire(true);
                                while (num5 != num3)
{
                                    if (num5 < num3)
{
                                        num5++;
                                    }
                                    if (num5 > num3)
{
                                        num5--;
                                    }
                                    Main.tile[num5, num6].wire(true);
                                }
                                while (num6 != num4)
{
                                    if (num6 < num4)
{
                                        num6++;
                                    }
                                    if (num6 > num4)
{
                                        num6--;
                                    }
                                    Main.tile[num5, num6].wire(true);
                                }
                            }
                            else if (Main.tile[i, j].type == 105)
{
                                num2 = 15;
                                bool flag3 = false;
                                for (int n = 0; n < num2 * num2; n++)
{
                                    num3 = i + WorldGen.genRand.Next(-num2, num2 + 1);
                                    num4 = j + WorldGen.genRand.Next(-num2, num2 + 1);
                                    WorldGen.PlaceTile(num3, num4, 135, true, true, -1, WorldGen.genRand.Next(2, 4));
                                    if (Main.tile[num3, num4].type == 135)
{
                                        flag3 = true;
                                        break;
                                    }
                                }
                                if (flag3)
{
                                    int num7 = i;
                                    int num8 = j;
                                    Main.tile[num7, num8].wire(true);
                                    while (num7 != num3)
{
                                        if (num7 < num3)
{
                                            num7++;
                                        }
                                        if (num7 > num3)
{
                                            num7--;
                                        }
                                        Main.tile[num7, num8].wire(true);
                                    }
                                    while (num8 != num4)
{
                                        if (num8 < num4)
{
                                            num8++;
                                        }
                                        if (num8 > num4)
{
                                            num8--;
                                        }
                                        Main.tile[num7, num8].wire(true);
                                    }
                                }
                            }
                        }
                        if (Main.tile[i, j].type == 467 && (!WorldGen.tenthAnniversaryWorldGen || WorldGen.remixWorldGen))
{
                            int num9 = 8;
                            for (int num10 = 0; num10 < num9 * num9; num10++)
{
                                int num11 = i + WorldGen.genRand.Next(-num9, num9 + 1);
                                int num12 = j + WorldGen.genRand.Next(-num9, num9 + 1);
                                if (Main.tile[num11, num12].type == 0 || Main.tile[num11, num12].type == 1 || TileID.Sets.Ore[(int)Main.tile[num11, num12].type] || Main.tile[num11, num12].type == 59 || Main.tile[num11, num12].type == 151)
{
                                    bool flag4 = true;
                                    for (int num13 = num11 - 1; num13 <= num11 + 1; num13++)
{
                                        for (int num14 = num12 - 1; num14 <= num12 + 1; num14++)
{
                                            if (!WorldGen.SolidTile(num13, num14, false))
{
                                                flag4 = false;
                                            }
                                        }
                                    }
                                    if (flag4)
{
                                        Tile tile2 = Main.tile[num11, num12];
                                        tile2.type = 141;
                                        tile2.frameX = (tile2.frameY = 0);
                                        tile2.slope(0);
                                        tile2.halfBrick(false);
                                        WorldGen.TileFrame(num11, num12, true, false);
                                        if (Main.tile[num11, num12].type == 141)
{
                                            int num15 = i;
                                            int num16 = j;
                                            Main.tile[num15, num16].wire(true);
                                            while (num15 != num11)
{
                                                if (num15 < num11)
{
                                                    num15++;
                                                }
                                                if (num15 > num11)
{
                                                    num15--;
                                                }
                                                Main.tile[num15, num16].wire(true);
                                            }
                                            while (num16 != num12)
{
                                                if (num16 < num12)
{
                                                    num16++;
                                                }
                                                if (num16 > num12)
{
                                                    num16--;
                                                }
                                                Main.tile[num15, num16].wire(true);
                                            }
                                            break;
                                        }
                                    }
                                }
                            }
                        }
                        else
{
                            j++;
                        }
                    }
                }
            }
            WorldGen.SetBoulderSolidity(true);
            for (int num17 = 20; num17 < Main.maxTilesX - 20; num17++)
            {
                for (int num18 = 20; num18 < Main.maxTilesY - 20; num18++)
                {
                    if (Main.tile[num17, num18].active() && Main.tile[num17, num18].type == 467 && Main.tile[num17, num18].frameX == 144 && Main.tile[num17, num18].frameY == 0 && !Main.tile[num17, num18].wire() && !Main.tile[num17 + 1, num18].wire() && !Main.tile[num17, num18 + 1].wire() && !Main.tile[num17 + 1, num18 + 1].wire())
                    {
                        Main.tile[num17, num18].type = 21;
                        Main.tile[num17, num18].frameX = 36;
                        Main.tile[num17 + 1, num18].type = 21;
                        Main.tile[num17 + 1, num18].frameX = 54;
                        Main.tile[num17, num18 + 1].type = 21;
                        Main.tile[num17, num18 + 1].frameX = 36;
                        Main.tile[num17 + 1, num18 + 1].type = 21;
                        Main.tile[num17 + 1, num18 + 1].frameX = 54;
                    }
                }
            }
            for (int num19 = 0; num19 < 8000; num19++)
            {
                Chest chest = Main.chest[num19];
                if (chest == null)
                {
                    break;
                }
                if (WorldGen.genRand.Next(15) == 0 && chest.item[1].stack != 0)
                {
                    for (int num20 = 1; num20 < chest.maxItems; num20++)
                    {
                        if (chest.item[num20].stack == 0)
{
                            chest.item[num20].SetDefaults(5346, null);
                            break;
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.chest, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.WorldGen.getGoodWorldGen, Terraria.Tile.halfBrick(), Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Ore, Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.remixWorldGen, Terraria.WorldGen.SetBoulderSolidity(), Terraria.Item.SetDefaults(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.Item.stack, Terraria.WorldGen.tenthAnniversaryWorldGen, Terraria.Main.tile, Terraria.WorldGen.TileFrame(), Terraria.Tile.type, and Terraria.Tile.wire().