Terraria Decompiled: Terraria.WorldGen.Cavinator
Cavinator()
static void Terraria.WorldGen.Cavinator (int i, int j, int steps) inline static
Definition at line 80617 of file WorldGen.cs.
        {
            double num = (double)WorldGen.genRand.Next(7, 15);
            int num2 = 1;
            if (WorldGen.genRand.Next(2) == 0)
            {
                num2 = -1;
            }
            Vector2D vector2D;
            vector2D.X = (double)i;
            vector2D.Y = (double)j;
            int k = WorldGen.genRand.Next(20, 40);
            Vector2D vector2D2;
            vector2D2.Y = (double)WorldGen.genRand.Next(10, 20) * 0.01;
            vector2D2.X = (double)num2;
            while (k > 0)
            {
                k--;
                int num3 = (int)(vector2D.X - num * 0.5);
                int num4 = (int)(vector2D.X + num * 0.5);
                int num5 = (int)(vector2D.Y - num * 0.5);
                int num6 = (int)(vector2D.Y + num * 0.5);
                if (num3 < 0)
                {
                    num3 = 0;
                }
                if (num4 > Main.maxTilesX)
                {
                    num4 = Main.maxTilesX;
                }
                if (num5 < 0)
                {
                    num5 = 0;
                }
                if (num6 > Main.maxTilesY)
                {
                    num6 = Main.maxTilesY;
                }
                double num7 = num * (double)WorldGen.genRand.Next(80, 120) * 0.01;
                for (int l = num3; l < num4; l++)
                {
                    int m = num5;
                    while (m < num6)
                    {
                        double num8 = Math.Abs((double)l - vector2D.X);
                        double num9 = Math.Abs((double)m - vector2D.Y);
                        if (Math.Sqrt(num8 * num8 + num9 * num9) >= num7 * 0.4)
{
                            goto IL_021B;
                        }
                        Tile tile = Main.tile[l, m];
                        if (WorldGen.SecretSeed.dualDungeons.Enabled && ((tile.active() && DungeonUtils.IsConsideredDungeonTile((int)tile.type, true)) || DungeonUtils.IsConsideredDungeonWall((int)tile.wall, true)))
{
                            k = 0;
                            break;
                        }
                        if ((tile.active() && Main.tileDungeon[(int)tile.type]) || Main.wallDungeon[(int)tile.wall])
{
                            k = 0;
                            break;
                        }
                        if (!tile.active() || (WorldGen.CanBeClearedDuringGeneration((int)tile.type, l, m, false) && tile.type != 53))
{
                            Main.tile[l, m].active(false);
                            goto IL_021B;
                        }
                        IL_0220:
                        m++;
                        continue;
                        IL_021B:
                        if (k > 0)
{
                            goto IL_0220;
                        }
                        break;
                    }
                    if (k <= 0)
                    {
                        break;
                    }
                }
                vector2D += vector2D2;
                vector2D2.X += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                vector2D2.Y += (double)WorldGen.genRand.Next(-10, 11) * 0.05;
                if (vector2D2.X > (double)num2 + 0.5)
                {
                    vector2D2.X = (double)num2 + 0.5;
                }
                if (vector2D2.X < (double)num2 - 0.5)
                {
                    vector2D2.X = (double)num2 - 0.5;
                }
                if (vector2D2.Y > 2.0)
                {
                    vector2D2.Y = 2.0;
                }
                if (vector2D2.Y < 0.0)
                {
                    vector2D2.Y = 0.0;
                }
            }
            if (steps > 0 && (double)((int)vector2D.Y) < Main.rockLayer + 50.0)
            {
                WorldGen.Cavinator((int)vector2D.X, (int)vector2D.Y, steps - 1);
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.WorldGen.CanBeClearedDuringGeneration(), Terraria.WorldGen.Cavinator(), Terraria.WorldGen.SecretSeed.dualDungeons, Terraria.WorldGen.genRand, int, Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonTile(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.IsConsideredDungeonWall(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.rockLayer, System.Math.Sqrt(), Terraria.Main.tile, Terraria.Main.tileDungeon, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Main.wallDungeon, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses(), and Terraria.WorldGen.Cavinator().