Terraria Decompiled: Terraria.WorldGen.CheckTileBreakability
CheckTileBreakability()
static int Terraria.WorldGen.CheckTileBreakability (int x, int y) inline static
Definition at line 61335 of file WorldGen.cs.
        {
            if (Main.tile[x, y] == null)
            {
                Main.tile[x, y] = new Tile();
            }
            Tile tile = Main.tile[x, y];
            if (y >= 1 && y <= Main.maxTilesY - 1)
            {
                if (Main.tile[x, y - 1] == null)
                {
                    Main.tile[x, y - 1] = new Tile();
                }
                if (Main.tile[x, y + 1] == null)
                {
                    Main.tile[x, y + 1] = new Tile();
                }
                Tile tile2 = Main.tile[x, y - 1];
                Tile tile3 = Main.tile[x, y + 1];
                if (tile3 != null && tile3.active() && WorldGen.IsLockedDoor(tile3))
                {
                    return 2;
                }
                if (!Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
                {
                    return 0;
                }
                if (tile2.active())
                {
                    bool flag = WorldGen.IsAContainer(tile);
                    if (WorldGen.CheckTileBreakability_HasReasonToReturnEarly((int)tile.type, tile2, !flag))
                    {
                        if (TileID.Sets.IsATreeTrunk[(int)tile2.type])
{
                            if ((tile2.frameX == 66 && tile2.frameY >= 0 && tile2.frameY <= 44) || (tile2.frameX == 88 && tile2.frameY >= 66 && tile2.frameY <= 110) || tile2.frameY >= 198)
{
                                return 0;
                            }
                            return 2;
                        }
                        else
{
                            if (tile2.type != 323)
{
                                return 2;
                            }
                            if (tile2.frameX == 66 || tile2.frameX == 220)
{
                                return 2;
                            }
                            return 0;
                        }
                    }
                    else
                    {
                        if (tile2.type == 80 && tile2.type != tile.type)
{
                            int num = (int)(tile2.frameX / 18);
                            if (num <= 1 || num - 4 <= 1)
{
                                return 2;
                            }
                        }
                        if (tile.type == 10 && WorldGen.IsLockedDoor(tile))
{
                            return 1;
                        }
                        if (TileID.Sets.Boulders[(int)tile.type])
{
                            if (WorldGen.CheckBoulderChest(x, y))
{
                                return 1;
                            }
                            return 0;
                        }
                    }
                }
                if (tile.type == 235)
                {
                    int frameX = (int)tile.frameX;
                    int num2 = x - frameX % 54 / 18;
                    for (int i = 0; i < 3; i++)
                    {
                        Tile tile4 = Main.tile[num2 + i, y - 1];
                        if (tile4.active() && WorldGen.CheckTileBreakability_HasReasonToReturnEarly((int)tile.type, tile4, true))
{
                            return 2;
                        }
                    }
                }
            }
            return 0;
        }
References Terraria.Tile.active(), Terraria.ID.TileID.Sets.Boulders, Terraria.WorldGen.CheckBoulderChest(), Terraria.WorldGen.CheckTileBreakability_HasReasonToReturnEarly(), Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.WorldGen.IsAContainer(), Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.WorldGen.IsLockedDoor(), Terraria.Main.maxTilesY, Terraria.DataStructures.Tile, Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.GameContent.MinecartDiggerHelper.CanGetPastTile(), Terraria.WorldGen.Check3x1(), and Terraria.WorldGen.KillTile().