Terraria Decompiled: Terraria.WorldGen.UpdateWorld_UndergroundTile
UpdateWorld_UndergroundTile()
static void Terraria.WorldGen.UpdateWorld_UndergroundTile (int i, int j, int wallDist) inline static private
Definition at line 73685 of file WorldGen.cs.
        {
            int num = i - 1;
            int num2 = i + 2;
            int num3 = j - 1;
            int num4 = j + 2;
            if (num < 10)
            {
                num = 10;
            }
            if (num2 > Main.maxTilesX - 10)
            {
                num2 = Main.maxTilesX - 10;
            }
            if (num3 < 10)
            {
                num3 = 10;
            }
            if (num4 > Main.maxTilesY - 10)
            {
                num4 = Main.maxTilesY - 10;
            }
            if (Main.tile[i, j] != null)
            {
                if (Main.tile[i, j].type == 655 && !NPC.AnyNPCs(262))
                {
                    WorldGen.KillTile(i, j, false, false, false);
                    if (Main.netMode == 2)
                    {
                        NetMessage.SendData(17, -1, -1, null, 0, (float)i, (float)j, 0f, 0, 0, 0);
                    }
                }
                if (Main.tileAlch[(int)Main.tile[i, j].type])
                {
                    WorldGen.GrowAlch(i, j);
                }
                else if (Main.tile[i, j].nactive())
                {
                    WorldGen.hardUpdateWorld(i, j);
                    if (Main.rand.Next(2500) == 0)
                    {
                        WorldGen.plantDye(i, j, false);
                    }
                    else if (Main.hardMode && Main.rand.Next(10000) == 0)
                    {
                        WorldGen.plantDye(i, j, true);
                    }
                    if (Main.tile[i, j].type == 519)
                    {
                        WorldGen.CheckCatTail(i, j);
                        if (Main.tile[i, j].active() && WorldGen.genRand.Next(2) == 0)
{
                            WorldGen.GrowCatTail(i, j);
                            WorldGen.CheckCatTail(i, j);
                        }
                    }
                    if (Main.tile[i, j].type == 549)
                    {
                        WorldGen.GrowCheckSeaweed(i, j);
                    }
                    else if (Main.tile[i, j].type == 53 && !Main.tile[i, j].topSlope() && !Main.tile[i, j].halfBrick() && !Main.tile[i, j - 1].active() && WorldGen.genRand.Next(20) == 0)
                    {
                        WorldGen.GrowCheckSeaweed(i, j);
                    }
                    else if (TileID.Sets.SpreadUnderground[(int)Main.tile[i, j].type])
                    {
                        WorldGen.UpdateWorld_GrassGrowth(i, j, num, num2, num3, num4, true);
                        int type = (int)Main.tile[i, j].type;
                        if ((type == 32 || type == 352) && WorldGen.genRand.Next(3) == 0)
{
                            if (type == 32)
{
                                WorldGen.GrowSpike(i, j, 32, 23);
                            }
                            else
{
                                WorldGen.GrowSpike(i, j, 352, 199);
                            }
                        }
                    }
                    else if (Main.tile[i, j].type == 61 && WorldGen.genRand.Next(3) == 0)
                    {
                        if (Main.tile[i, j + 1].type != 226 && Main.tile[i, j].frameX < 144)
{
                            if (Main.rand.Next(4) == 0)
{
                                Main.tile[i, j].frameX = (short)(162 + WorldGen.genRand.Next(8) * 18);
                            }
                            Main.tile[i, j].type = 74;
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62) && WorldGen.genRand.Next(5) == 0 && WorldGen.GrowMoreVines(i, j))
                    {
                        if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            bool flag = false;
                            for (int k = j; k > j - 10; k--)
{
                                if (Main.tile[i, k].bottomSlope())
{
                                    flag = false;
                                    break;
                                }
                                if (Main.tile[i, k].active() && Main.tile[i, k].type == 60 && !Main.tile[i, k].bottomSlope())
{
                                    flag = true;
                                    break;
                                }
                            }
                            if (flag)
{
                                int num5 = j + 1;
                                Main.tile[i, num5].type = 62;
                                Main.tile[i, num5].active(true);
                                WorldGen.SquareTileFrame(i, num5, true);
                                Main.tile[i, num5].CopyPaintAndCoating(Main.tile[i, num5 - 1]);
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, num5, TileChangeType.None);
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 633 || Main.tile[i, j].type == 638) && WorldGen.GrowMoreVines(i, j))
                    {
                        if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            int num6 = 70;
                            if (Main.tile[i, j].type == 638)
{
                                num6 = 7;
                            }
                            if (WorldGen.genRand.Next(num6) == 0)
{
                                bool flag2 = false;
                                for (int l = j; l > j - 10; l--)
{
                                    if (Main.tile[i, l].bottomSlope())
{
                                        flag2 = false;
                                        break;
                                    }
                                    if (Main.tile[i, l].active() && Main.tile[i, l].type == 633 && !Main.tile[i, l].bottomSlope())
{
                                        flag2 = true;
                                        break;
                                    }
                                }
                                if (flag2)
{
                                    int num7 = j + 1;
                                    Main.tile[i, num7].type = 638;
                                    Main.tile[i, num7].active(true);
                                    Main.tile[i, num7].CopyPaintAndCoating(Main.tile[i, num7 - 1]);
                                    WorldGen.SquareTileFrame(i, num7, true);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, i, num7, TileChangeType.None);
                                    }
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 70 || Main.tile[i, j].type == 528) && WorldGen.GrowMoreVines(i, j))
                    {
                        if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            int num8 = 70;
                            if (Main.tile[i, j].type == 528)
{
                                num8 = 7;
                            }
                            if (WorldGen.genRand.Next(num8) == 0)
{
                                bool flag3 = false;
                                for (int m = j; m > j - 10; m--)
{
                                    if (Main.tile[i, m].bottomSlope())
{
                                        flag3 = false;
                                        break;
                                    }
                                    if (Main.tile[i, m].active() && Main.tile[i, m].type == 70 && !Main.tile[i, m].bottomSlope())
{
                                        flag3 = true;
                                        break;
                                    }
                                }
                                if (flag3)
{
                                    int num9 = j + 1;
                                    Main.tile[i, num9].type = 528;
                                    Main.tile[i, num9].active(true);
                                    Main.tile[i, num9].CopyPaintAndCoating(Main.tile[i, num9 - 1]);
                                    WorldGen.SquareTileFrame(i, num9, true);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, i, num9, TileChangeType.None);
                                    }
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 661 || Main.tile[i, j].type == 636) && WorldGen.GrowMoreVines(i, j))
                    {
                        if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            int num10 = 70;
                            if (Main.tile[i, j].type == 636)
{
                                num10 = 7;
                            }
                            if (WorldGen.genRand.Next(num10) == 0)
{
                                bool flag4 = false;
                                for (int n = j; n > j - 10; n--)
{
                                    if (Main.tile[i, n].bottomSlope())
{
                                        flag4 = false;
                                        break;
                                    }
                                    if (Main.tile[i, n].active() && Main.tile[i, n].type == 661 && !Main.tile[i, n].bottomSlope())
{
                                        flag4 = true;
                                        break;
                                    }
                                }
                                if (flag4)
{
                                    int num11 = j + 1;
                                    Main.tile[i, num11].type = 636;
                                    Main.tile[i, num11].active(true);
                                    Main.tile[i, num11].CopyPaintAndCoating(Main.tile[i, num11 - 1]);
                                    WorldGen.SquareTileFrame(i, num11, true);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, i, num11, TileChangeType.None);
                                    }
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 662 || Main.tile[i, j].type == 205) && WorldGen.GrowMoreVines(i, j))
                    {
                        if (!Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            int num12 = 70;
                            if (Main.tile[i, j].type == 205)
{
                                num12 = 7;
                            }
                            if (WorldGen.genRand.Next(num12) == 0)
{
                                bool flag5 = false;
                                for (int num13 = j; num13 > j - 10; num13--)
{
                                    if (Main.tile[i, num13].bottomSlope())
{
                                        flag5 = false;
                                        break;
                                    }
                                    if (Main.tile[i, num13].active() && Main.tile[i, num13].type == 662 && !Main.tile[i, num13].bottomSlope())
{
                                        flag5 = true;
                                        break;
                                    }
                                }
                                if (flag5)
{
                                    int num14 = j + 1;
                                    Main.tile[i, num14].type = 205;
                                    Main.tile[i, num14].active(true);
                                    Main.tile[i, num14].CopyPaintAndCoating(Main.tile[i, num14 - 1]);
                                    WorldGen.SquareTileFrame(i, num14, true);
                                    if (Main.netMode == 2)
{
                                        NetMessage.SendTileSquare(-1, i, num14, TileChangeType.None);
                                    }
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 62) && WorldGen.genRand.Next(80) == 0 && !WorldGen.PlayerLOS(i, j))
                    {
                        bool flag6 = true;
                        int num15 = j;
                        if (Main.tile[i, j].type == 60)
{
                            num15++;
                        }
                        for (int num16 = i; num16 < i + 2; num16++)
{
                            int num17 = num15 - 1;
                            if (!WorldGen.AnchorValid(Framing.GetTileSafely(num16, num17), AnchorType.SolidTile) || Main.tile[num16, num17].bottomSlope())
{
                                flag6 = false;
                            }
                            if (Main.tile[num16, num17].liquid > 0 || Main.wallHouse[(int)Main.tile[num16, num17].wall])
{
                                flag6 = false;
                            }
                            if (!flag6)
{
                                break;
                            }
                            for (int num18 = num15; num18 < num15 + 2; num18++)
{
                                if ((Main.tile[num16, num18].active() && (!Main.tileCut[(int)Main.tile[num16, num18].type] || Main.tile[num16, num18].type == 444)) || Main.tile[num16, num18].anyLava())
{
                                    flag6 = false;
                                }
                                if (!flag6)
{
                                    break;
                                }
                            }
                            if (!flag6)
{
                                break;
                            }
                        }
                        if (flag6 && WorldGen.CountNearBlocksTypes(i, j, 20, 1, new int[] { 444 }) > 0)
{
                            flag6 = false;
                        }
                        if (flag6)
{
                            for (int num19 = i; num19 < i + 2; num19++)
{
                                Main.tile[num19, num15 - 1].slope(0);
                                Main.tile[num19, num15 - 1].halfBrick(false);
                                for (int num20 = num15; num20 < num15 + 2; num20++)
{
                                    if (Main.tile[num19, num20].active())
{
                                        WorldGen.KillTile(num19, num20, false, false, false);
                                    }
                                }
                            }
                            for (int num21 = i; num21 < i + 2; num21++)
{
                                for (int num22 = num15; num22 < num15 + 2; num22++)
{
                                    Main.tile[num21, num22].active(true);
                                    Main.tile[num21, num22].type = 444;
                                    Main.tile[num21, num22].frameX = (short)((num21 - i) * 18);
                                    Main.tile[num21, num22].frameY = (short)((num22 - num15) * 18);
                                }
                            }
                            if (Main.netMode == 2)
{
                                NetMessage.SendTileSquare(-1, i, num15 - 1, 2, 3, TileChangeType.None);
                            }
                        }
                    }
                    else if (Main.tile[i, j].type == 396 && WorldGen.genRand.Next(80) == 0 && !WorldGen.PlayerLOS(i, j))
                    {
                        bool flag7 = true;
                        int num23 = j - 1;
                        for (int num24 = i; num24 < i + 2; num24++)
{
                            int num25 = num23 + 1;
                            if (!WorldGen.AnchorValid(Framing.GetTileSafely(num24, num25), AnchorType.SolidTile) || Main.tile[num24, num25].topSlope())
{
                                flag7 = false;
                            }
                            if (Main.tile[num24, num25].liquid > 0 || Main.wallHouse[(int)Main.tile[num24, num25].wall])
{
                                flag7 = false;
                            }
                            if (!flag7)
{
                                break;
                            }
                            for (int num26 = num23 - 2; num26 < num23; num26++)
{
                                if ((Main.tile[num24, num26].active() && (!Main.tileCut[(int)Main.tile[num24, num26].type] || Main.tile[num24, num26].type == 485)) || Main.tile[num24, num26].anyLava())
{
                                    flag7 = false;
                                }
                                if (!flag7)
{
                                    break;
                                }
                            }
                            if (!flag7)
{
                                break;
                            }
                        }
                        if (flag7 && WorldGen.CountNearBlocksTypes(i, j, 20, 1, new int[] { 485 }) > 0)
{
                            flag7 = false;
                        }
                        if (flag7)
{
                            bool flag8 = true;
                            for (int num27 = -1; num27 >= -3; num27--)
{
                                if (Main.tile[i, j + num27].active())
{
                                    flag8 = false;
                                    break;
                                }
                            }
                            if (flag8)
{
                                ushort num28 = 485;
                                int num29 = WorldGen.genRand.Next(4);
                                if (WorldGen.genRand.Next(100) == 0)
{
                                    num28 = 751;
                                    num29 = 0;
                                }
                                WorldGen.PlaceTile(i, j - 1, (int)num28, true, false, -1, num29);
                                if (Main.tile[i, j - 1].active() && Main.tile[i, j - 1].type == num28)
{
                                    Tile tile = Main.tile[i, j];
                                    for (int num30 = 0; num30 < 3; num30++)
{
                                        for (int num31 = 0; num31 > -2; num31--)
{
                                            Tile tile2 = Main.tile[i + num30, j - 1 + num31];
                                            if (tile2.active() && tile2.type == num28)
{
                                                tile2.CopyPaintAndCoating(tile);
                                            }
                                        }
                                    }
                                }
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, j - 2, 2, 2, TileChangeType.None);
                                }
                            }
                        }
                    }
                    else if (Main.tile[i, j].type == 69)
                    {
                        WorldGen.GrowSpike(i, j, 69, 60);
                    }
                    else if (Main.tile[i, j].type == 147 || Main.tile[i, j].type == 161 || Main.tile[i, j].type == 163 || Main.tile[i, j].type == 164 || Main.tile[i, j].type == 200)
                    {
                        if (Main.rand.Next(10) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 2].active())
{
                            int num32 = i - 3;
                            int num33 = i + 4;
                            int num34 = 0;
                            for (int num35 = num32; num35 < num33; num35++)
{
                                if (Main.tile[num35, j].type == 165 && Main.tile[num35, j].active())
{
                                    num34++;
                                }
                                if (Main.tile[num35, j + 1].type == 165 && Main.tile[num35, j + 1].active())
{
                                    num34++;
                                }
                                if (Main.tile[num35, j + 2].type == 165 && Main.tile[num35, j + 2].active())
{
                                    num34++;
                                }
                                if (Main.tile[num35, j + 3].type == 165 && Main.tile[num35, j + 3].active())
{
                                    num34++;
                                }
                            }
                            if (num34 < 2)
{
                                WorldGen.PlaceTight(i, j + 1, false);
                                WorldGen.SquareTileFrame(i, j + 1, true);
                                if (Main.netMode == 2 && Main.tile[i, j + 1].active())
{
                                    NetMessage.SendTileSquare(-1, i, j + 1, 1, 2, TileChangeType.None);
                                }
                            }
                        }
                    }
                    else if (Main.tileMoss[(int)Main.tile[i, j].type] || TileID.Sets.tileMossBrick[(int)Main.tile[i, j].type])
                    {
                        int type2 = (int)Main.tile[i, j].type;
                        bool flag9 = false;
                        TileColorCache tileColorCache = Main.tile[i, j].BlockColorAndCoating();
                        for (int num36 = num; num36 < num2; num36++)
{
                            for (int num37 = num3; num37 < num4; num37++)
{
                                if ((i != num36 || j != num37) && Main.tile[num36, num37].active() && (Main.tile[num36, num37].type == 1 || Main.tile[num36, num37].type == 38))
{
                                    int type3 = (int)Main.tile[num36, num37].type;
                                    int num38 = WorldGen.MossConversion(type2, type3);
                                    WorldGen.SpreadGrass(num36, num37, (int)Main.tile[num36, num37].type, num38, false, tileColorCache);
                                    if ((int)Main.tile[num36, num37].type == num38)
{
                                        WorldGen.SquareTileFrame(num36, num37, true);
                                        flag9 = true;
                                    }
                                }
                            }
                        }
                        if (Main.netMode == 2 && flag9)
{
                            NetMessage.SendTileSquare(-1, i, j, 3, TileChangeType.None);
                        }
                        if (WorldGen.genRand.Next(6) == 0)
{
                            int num39 = i;
                            int num40 = j;
                            int num41 = WorldGen.genRand.Next(4);
                            if (num41 == 0)
{
                                num39--;
                            }
                            else if (num41 == 1)
{
                                num39++;
                            }
                            else if (num41 == 2)
{
                                num40--;
                            }
                            else
{
                                num40++;
                            }
                            if (!Main.tile[num39, num40].active())
{
                                if (WorldGen.PlaceTile(num39, num40, 184, true, false, -1, 0))
{
                                    Main.tile[num39, num40].CopyPaintAndCoating(Main.tile[i, j]);
                                }
                                if (Main.netMode == 2 && Main.tile[num39, num40].active())
{
                                    NetMessage.SendTileSquare(-1, num39, num40, TileChangeType.None);
                                }
                            }
                        }
                    }
                    else if (Main.tile[i, j].type == 20)
                    {
                        if (WorldGen.genRand.Next(5) == 0)
{
                            WorldGen.AttemptToGrowTreeFromSapling(i, j, true, 0, false);
                        }
                    }
                    else if (Main.tile[i, j].type == 590)
                    {
                        if (WorldGen.genRand.Next(5) == 0)
{
                            WorldGen.AttemptToGrowTreeFromSapling(i, j, true, 0, false);
                        }
                    }
                    else if (Main.tile[i, j].type == 595)
                    {
                        if (WorldGen.genRand.Next(5) == 0)
{
                            WorldGen.AttemptToGrowTreeFromSapling(i, j, true, 0, false);
                        }
                    }
                    else if (Main.tile[i, j].type == 615 && WorldGen.genRand.Next(5) == 0)
                    {
                        WorldGen.AttemptToGrowTreeFromSapling(i, j, true, 0, false);
                    }
                    if (!Main.isThereAWorldSurface && (Main.dungeonX < 0 || Main.dungeonY < 0) && (double)j < Main.rockLayer && Main.tileDungeon[(int)Main.tile[i, j].type])
                    {
                        bool flag10 = true;
                        for (int num42 = i - 1; num42 <= i + 1; num42++)
{
                            for (int num43 = j - 3; num43 <= j - 1; num43++)
{
                                if (WorldGen.SolidTile3(num42, num43))
{
                                    flag10 = false;
                                }
                            }
                        }
                        if (flag10)
{
                            Main.dungeonX = i;
                            Main.dungeonY = j;
                        }
                    }
                }
                else
                {
                    if (Main.tile[i, j].wall == 62 && Main.tile[i, j].liquid == 0)
                    {
                        WorldGen.GrowWeb(i, j);
                    }
                    WorldGen.TrySpawningTownNPC(i, j);
                }
                if (WorldGen.AllowedToSpreadInfections)
                {
                    WorldGen.SpreadGrassWalls(wallDist, i, j);
                    WorldGen.SpreadDesertWalls(wallDist, i, j);
                }
                if (Main.tile[i, j].nactive())
                {
                    if (Main.tile[i, j].type == 61 && WorldGen.genRand.Next(3) == 0 && Main.tile[i, j + 1].type != 226 && Main.tile[i, j].frameX < 144)
                    {
                        if (Main.rand.Next(4) == 0)
{
                            Main.tile[i, j].frameX = (short)(162 + WorldGen.genRand.Next(8) * 18);
                        }
                        Main.tile[i, j].type = 74;
                        if (Main.netMode == 2)
{
                            NetMessage.SendTileSquare(-1, i, j, TileChangeType.None);
                        }
                    }
                    if ((Main.tile[i, j].type == 60 || Main.tile[i, j].type == 226 || Main.tile[i, j].type == 62) && WorldGen.GrowMoreVines(i, j))
                    {
                        int num44 = 30;
                        if (Main.tile[i, j].type == 62)
{
                            num44 = 10;
                        }
                        if (WorldGen.genRand.Next(num44) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            bool flag11 = false;
                            for (int num45 = j; num45 > j - 10; num45--)
{
                                if (Main.tile[i, num45].bottomSlope())
{
                                    flag11 = false;
                                    break;
                                }
                                if (Main.tile[i, num45].active() && (Main.tile[i, num45].type == 60 || Main.tile[i, num45].type == 226) && !Main.tile[i, num45].bottomSlope())
{
                                    flag11 = true;
                                    break;
                                }
                            }
                            if (flag11)
{
                                int num46 = j + 1;
                                Main.tile[i, num46].type = 62;
                                Main.tile[i, num46].active(true);
                                Main.tile[i, num46].CopyPaintAndCoating(Main.tile[i, num46 - 1]);
                                WorldGen.SquareTileFrame(i, num46, true);
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, num46, TileChangeType.None);
                                    return;
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 633 || Main.tile[i, j].type == 638) && WorldGen.GrowMoreVines(i, j))
                    {
                        int num47 = 70;
                        if (Main.tile[i, j].type == 638)
{
                            num47 = 7;
                        }
                        if (WorldGen.genRand.Next(num47) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            bool flag12 = false;
                            for (int num48 = j; num48 > j - 10; num48--)
{
                                if (Main.tile[i, num48].bottomSlope())
{
                                    flag12 = false;
                                    break;
                                }
                                if (Main.tile[i, num48].active() && Main.tile[i, num48].type == 633 && !Main.tile[i, num48].bottomSlope())
{
                                    flag12 = true;
                                    break;
                                }
                            }
                            if (flag12)
{
                                int num49 = j + 1;
                                Main.tile[i, num49].type = 638;
                                Main.tile[i, num49].active(true);
                                Main.tile[i, num49].CopyPaintAndCoating(Main.tile[i, num49 - 1]);
                                WorldGen.SquareTileFrame(i, num49, true);
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, num49, TileChangeType.None);
                                    return;
                                }
                            }
                        }
                    }
                    else if ((Main.tile[i, j].type == 70 || Main.tile[i, j].type == 528) && WorldGen.GrowMoreVines(i, j))
                    {
                        int num50 = 70;
                        if (Main.tile[i, j].type == 528)
{
                            num50 = 7;
                        }
                        if (WorldGen.genRand.Next(num50) == 0 && !Main.tile[i, j + 1].active() && !Main.tile[i, j + 1].anyLava())
{
                            bool flag13 = false;
                            for (int num51 = j; num51 > j - 10; num51--)
{
                                if (Main.tile[i, num51].bottomSlope())
{
                                    flag13 = false;
                                    break;
                                }
                                if (Main.tile[i, num51].active() && Main.tile[i, num51].type == 70 && !Main.tile[i, num51].bottomSlope())
{
                                    flag13 = true;
                                    break;
                                }
                            }
                            if (flag13)
{
                                int num52 = j + 1;
                                Main.tile[i, num52].type = 528;
                                Main.tile[i, num52].active(true);
                                Main.tile[i, num52].CopyPaintAndCoating(Main.tile[i, num52 - 1]);
                                WorldGen.SquareTileFrame(i, num52, true);
                                if (Main.netMode == 2)
{
                                    NetMessage.SendTileSquare(-1, i, num52, TileChangeType.None);
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.WorldGen.AllowedToSpreadInfections, Terraria.WorldGen.AnchorValid(), Terraria.Tile.anyLava(), Terraria.NPC.AnyNPCs(), Terraria.WorldGen.AttemptToGrowTreeFromSapling(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.bottomSlope(), Terraria.WorldGen.CheckCatTail(), Terraria.Tile.CopyPaintAndCoating(), Terraria.WorldGen.CountNearBlocksTypes(), Terraria.Main.dungeonX, Terraria.Main.dungeonY, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.genRand, Terraria.Framing.GetTileSafely(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowCheckSeaweed(), Terraria.WorldGen.GrowMoreVines(), Terraria.WorldGen.GrowSpike(), Terraria.WorldGen.GrowWeb(), Terraria.Tile.halfBrick(), Terraria.Main.hardMode, Terraria.WorldGen.hardUpdateWorld(), int, Terraria.Main.isThereAWorldSurface, Terraria.WorldGen.KillTile(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.WorldGen.MossConversion(), Terraria.Tile.nactive(), Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.WorldGen.PlaceTight(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.plantDye(), Terraria.WorldGen.PlayerLOS(), Terraria.Main.rand, Terraria.Main.rockLayer, Terraria.NetMessage.SendData(), Terraria.NetMessage.SendTileSquare(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SpreadDesertWalls(), Terraria.WorldGen.SpreadGrass(), Terraria.WorldGen.SpreadGrassWalls(), Terraria.ID.TileID.Sets.SpreadUnderground, Terraria.WorldGen.SquareTileFrame(), Terraria.Main.tile, Terraria.Main.tileAlch, Terraria.Main.tileCut, Terraria.Main.tileDungeon, Terraria.Main.tileMoss, Terraria.ID.TileID.Sets.tileMossBrick, Terraria.Tile.topSlope(), Terraria.WorldGen.TrySpawningTownNPC(), Terraria.Tile.type, Terraria.WorldGen.UpdateWorld_GrassGrowth(), Terraria.Tile.wall, and Terraria.Main.wallHouse.
Referenced by Terraria.WorldGen.UpdateWorld().