Terraria Decompiled: Terraria.WorldGen.AddUpAlignmentCounts
AddUpAlignmentCounts()
static void Terraria.WorldGen.AddUpAlignmentCounts (bool clearCounts = false) inline static
Definition at line 71532 of file WorldGen.cs.
        {
            if (clearCounts)
            {
                WorldGen.totalEvil2 = 0;
                WorldGen.totalSolid2 = 0;
                WorldGen.totalGood2 = 0;
                WorldGen.totalBlood2 = 0;
            }
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            for (int i = 0; i < TileID.Sets.HallowCountCollection.Count; i++)
            {
                int num4 = WorldGen.tileCounts[TileID.Sets.HallowCountCollection[i]];
                WorldGen.totalGood2 += num4;
                num += num4;
            }
            for (int j = 0; j < TileID.Sets.CorruptCountCollection.Count; j++)
            {
                int num5 = WorldGen.tileCounts[TileID.Sets.CorruptCountCollection[j]];
                WorldGen.totalEvil2 += num5;
                num2 += num5;
            }
            for (int k = 0; k < TileID.Sets.CrimsonCountCollection.Count; k++)
            {
                int num6 = WorldGen.tileCounts[TileID.Sets.CrimsonCountCollection[k]];
                WorldGen.totalBlood2 += num6;
                num3 += num6;
            }
            if (Main.remixWorld)
            {
                int num7 = WorldGen.tileCounts[474];
                WorldGen.totalEvil2 += num7;
                num2 += num7;
                num7 = WorldGen.tileCounts[195];
                WorldGen.totalBlood2 += num7;
                num3 += num7;
            }
            WorldGen.totalSolid2 += WorldGen.tileCounts[2] + WorldGen.tileCounts[477] + WorldGen.tileCounts[1] + WorldGen.tileCounts[60] + WorldGen.tileCounts[53] + WorldGen.tileCounts[161];
            WorldGen.totalSolid2 += num;
            WorldGen.totalSolid2 += num2;
            WorldGen.totalSolid2 += num3;
            Array.Clear(WorldGen.tileCounts, 0, WorldGen.tileCounts.Length);
        }
References System.Array.Clear(), Terraria.ID.TileID.Sets.CorruptCountCollection, System.Collections.Generic.List< T >.Count, Terraria.ID.TileID.Sets.CrimsonCountCollection, Terraria.ID.TileID.Sets.HallowCountCollection, Terraria.Main.remixWorld, and Terraria.WorldGen.tileCounts.
Referenced by Terraria.WorldGen.CountTiles(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), and Terraria.IO.WorldFile.LoadWorldTiles().