Terraria Decompiled: Terraria.WorldGen.GetTreeBottom
GetTreeBottom()
static void Terraria.WorldGen.GetTreeBottom (int i, int j, out int x, out int y) inline static
Definition at line 62675 of file WorldGen.cs.
        {
            x = i;
            y = j;
            Tile tile = Framing.GetTileSafely(x, y);
            if (tile.type == 323)
            {
                while (y < Main.maxTilesY - 1)
                {
                    if (tile.active() && tile.type != 323)
                    {
                        return;
                    }
                    y++;
                    tile = Framing.GetTileSafely(x, y);
                }
            }
            else
            {
                int num = (int)(tile.frameX / 22);
                int num2 = (int)(tile.frameY / 22);
                if (num == 3 && num2 <= 2)
                {
                    x++;
                }
                else if (num == 4 && num2 >= 3 && num2 <= 5)
                {
                    x--;
                }
                else if (num == 1 && num2 >= 6 && num2 <= 8)
                {
                    x--;
                }
                else if (num == 2 && num2 >= 6 && num2 <= 8)
                {
                    x++;
                }
                else if (num == 2 && num2 >= 9)
                {
                    x++;
                }
                else if (num == 3 && num2 >= 9)
                {
                    x--;
                }
                tile = Framing.GetTileSafely(x, y);
                while (y < Main.maxTilesY - 1 && (!tile.active() || TileID.Sets.IsATreeTrunk[(int)tile.type] || tile.type == 72))
                {
                    y++;
                    tile = Framing.GetTileSafely(x, y);
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Framing.GetTileSafely(), int, Terraria.ID.TileID.Sets.IsATreeTrunk, Terraria.Main.maxTilesY, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.GetTreeTypeAndTreeBottom().