Terraria Decompiled: Terraria.WorldGen.RightEdgeCanBeAttachedTo
RightEdgeCanBeAttachedTo()
static bool Terraria.WorldGen.RightEdgeCanBeAttachedTo (int i, int j) inline static
Definition at line 70678 of file WorldGen.cs.
        {
            try
            {
                Tile tile = Main.tile[i, j];
                if (tile == null)
                {
                    return true;
                }
                if (tile.active() && Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type] && !tile.rightSlope() && !tile.halfBrick() && !tile.inActive() && !Main.tileNoAttach[(int)tile.type])
                {
                    return true;
                }
            }
            catch
            {
            }
            return false;
        }
References Terraria.Tile.active(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.rightSlope(), Terraria.Main.tile, Terraria.Main.tileNoAttach, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, and Terraria.Tile.type.
Referenced by Terraria.WorldGen.CheckSign().