Terraria Decompiled: Terraria.WorldGen.HellRoom
HellRoom()
static void Terraria.WorldGen.HellRoom (int i, int j, int width, int height, byte type = 76, byte wall = 13) inline static
Definition at line 30721 of file WorldGen.cs.
        {
            if (j > Main.maxTilesY - 40)
            {
                return;
            }
            for (int k = i - width / 2; k <= i + width / 2; k++)
            {
                for (int l = j - height; l <= j; l++)
                {
                    try
                    {
                        Main.tile[k, l].active(true);
                        Main.tile[k, l].type = (ushort)type;
                        Main.tile[k, l].liquid = 0;
                        Main.tile[k, l].lava(false);
                    }
                    catch
                    {
                    }
                }
            }
            for (int m = i - width / 2 + 1; m <= i + width / 2 - 1; m++)
            {
                for (int n = j - height + 1; n <= j - 1; n++)
                {
                    try
                    {
                        Main.tile[m, n].active(false);
                        Main.tile[m, n].wall = (ushort)wall;
                        Main.tile[m, n].liquid = 0;
                        Main.tile[m, n].lava(false);
                    }
                    catch
                    {
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesY, Terraria.Main.tile, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.WorldGen.HellHouse().