Terraria Decompiled: Terraria.WorldGen.PlaceSandTrap
PlaceSandTrap()
static bool Terraria.WorldGen.PlaceSandTrap (int i, int j) inline static
Definition at line 32885 of file WorldGen.cs.
        {
            if (WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt)
            {
                return true;
            }
            int num = 6;
            int num2 = 4;
            int num3 = 25;
            int num4 = j;
            while (!Main.tile[i, num4].active() && num4 < Main.UnderworldLayer)
            {
                num4++;
            }
            if (num4 >= Main.UnderworldLayer)
            {
                return false;
            }
            if (!Main.tileSolid[(int)Main.tile[i, num4].type] || Main.tile[i, num4].halfBrick() || Main.tile[i, num4].topSlope())
            {
                return false;
            }
            if ((Main.tile[i, num4].type != 53 && Main.tile[i, num4].type != 397 && Main.tile[i, num4].type != 396) || (Main.tile[i, num4].wall != 216 && Main.tile[i, num4].wall != 187))
            {
                return false;
            }
            num4--;
            int num5 = -1;
            int num6 = WorldGen.genRand.Next(6, 12);
            int num7 = WorldGen.genRand.Next(6, 14);
            for (int k = i - num3; k <= i + num3; k++)
            {
                for (int l = num4 - num3; l < num4 + num3; l++)
                {
                    if (Main.tile[k, l].wire())
                    {
                        return false;
                    }
                    if (TileID.Sets.BasicChest[(int)Main.tile[k, l].type])
                    {
                        return false;
                    }
                    if (TileID.Sets.Paintings[(int)Main.tile[k, l].type])
                    {
                        return false;
                    }
                    if (Main.tile[k, l].type == 10)
                    {
                        return false;
                    }
                    if (Main.tile[k, l].type == 19)
                    {
                        return false;
                    }
                    if (Main.tile[k, l].type == 15)
                    {
                        return false;
                    }
                    if (Main.tile[k, l].type == 219)
                    {
                        return false;
                    }
                    if (Main.tile[k, l].type == 314)
                    {
                        return false;
                    }
                }
            }
            for (int m = i - 2; m <= i + 2; m++)
            {
                for (int n = num4 + 1; n <= num4 + 3; n++)
                {
                    if (!Main.tile[m, n].active() || !Main.tileSolid[(int)Main.tile[m, n].type])
                    {
                        return false;
                    }
                }
            }
            if (Main.tile[i, num4 + 1].type == 162)
            {
                return false;
            }
            int num8 = num4;
            while (num8 > num4 - 30)
            {
                if (Main.tile[i, num8].active())
                {
                    if (Main.tile[i, num8].type == 396)
                    {
                        num5 = num8;
                        break;
                    }
                    return false;
                }
                else
                {
                    num8--;
                }
            }
            if (num5 <= -1)
            {
                return false;
            }
            if (num4 - num5 < num7 + num2)
            {
                return false;
            }
            int num9 = 0;
            int num10 = (num4 + num5) / 2;
            for (int num11 = i - num6; num11 <= i + num6; num11++)
            {
                if (Main.tile[num11, num10].active() && Main.tileSolid[(int)Main.tile[num11, num10].type])
                {
                    return false;
                }
                for (int num12 = num5 - num7; num12 <= num5; num12++)
                {
                    if (Main.tile[num11, num12].active())
                    {
                        if (TileID.Sets.Ore[(int)Main.tile[num11, num12].type] || Main.tile[num11, num12].type == 404)
{
                            return false;
                        }
                        if (Main.tileSolid[(int)Main.tile[num11, num12].type])
{
                            num9++;
                        }
                    }
                }
            }
            double num13 = (double)((num6 * 2 + 1) * (num7 + 1)) * 0.75;
            if ((double)num9 < num13)
            {
                return false;
            }
            for (int num14 = i - num6 - 1; num14 <= i + num6 + 1; num14++)
            {
                for (int num15 = num5 - num7; num15 <= num5; num15++)
                {
                    bool flag = false;
                    if (Main.tile[num14, num15].active() && Main.tileSolid[(int)Main.tile[num14, num15].type])
                    {
                        flag = true;
                    }
                    if (num15 == num5)
                    {
                        Main.tile[num14, num15].slope(0);
                        Main.tile[num14, num15].halfBrick(false);
                        if (!flag)
{
                            Main.tile[num14, num15].active(true);
                            Main.tile[num14, num15].type = 396;
                        }
                    }
                    else if (num15 == num5 - num7)
                    {
                        Main.tile[num14, num15].ClearTile();
                        Main.tile[num14, num15].active(true);
                        if (flag && Main.tile[num14, num15 - 1].active() && Main.tileSolid[(int)Main.tile[num14, num15 - 1].type])
{
                            Main.tile[num14, num15].type = 397;
                        }
                        else
{
                            Main.tile[num14, num15].type = 396;
                        }
                    }
                    else if (num14 == i - num6 - 1 || num14 == i + num6 + 1)
                    {
                        if (!flag)
{
                            Main.tile[num14, num15].ClearTile();
                            Main.tile[num14, num15].active(true);
                            Main.tile[num14, num15].type = 396;
                        }
                        else
{
                            Main.tile[num14, num15].slope(0);
                            Main.tile[num14, num15].halfBrick(false);
                        }
                    }
                    else
                    {
                        Main.tile[num14, num15].ClearTile();
                        Main.tile[num14, num15].active(true);
                        Main.tile[num14, num15].type = 53;
                    }
                }
            }
            int num16 = (int)((double)num5 - (double)num7 * 0.666);
            while ((double)num16 <= (double)num5 - (double)num7 * 0.333)
            {
                if ((double)num16 < (double)num5 - (double)num7 * 0.4)
                {
                    if (Main.tile[i - num6 - 2, num16].bottomSlope())
                    {
                        Main.tile[i - num6 - 2, num16].slope(0);
                    }
                }
                else if ((double)num16 > (double)num5 - (double)num7 * 0.6)
                {
                    if (Main.tile[i - num6 - 2, num16].topSlope())
                    {
                        Main.tile[i - num6 - 2, num16].slope(0);
                    }
                    Main.tile[i - num6 - 2, num16].halfBrick(false);
                }
                else
                {
                    Main.tile[i - num6 - 2, num16].halfBrick(false);
                    Main.tile[i - num6 - 2, num16].slope(0);
                }
                if (!Main.tile[i - num6 - 2, num16].active() || !Main.tileSolid[(int)Main.tile[i - num6 - 2, num16].type])
                {
                    Main.tile[i - num6 - 2, num16].active(true);
                    Main.tile[i - num6 - 2, num16].type = 396;
                }
                if (!Main.tile[i + num6 + 2, num16].active() || !Main.tileSolid[(int)Main.tile[i + num6 + 2, num16].type])
                {
                    Main.tile[i + num6 + 2, num16].active(true);
                    Main.tile[i + num6 + 2, num16].type = 396;
                }
                num16++;
            }
            for (int num17 = num5 - num7; num17 <= num5; num17++)
            {
                Main.tile[i - num6 - 2, num17].slope(0);
                Main.tile[i - num6 - 2, num17].halfBrick(false);
                Main.tile[i - num6 - 1, num17].slope(0);
                Main.tile[i - num6 - 1, num17].halfBrick(false);
                Main.tile[i - num6 + 1, num17].slope(0);
                Main.tile[i - num6 + 1, num17].halfBrick(false);
                Main.tile[i - num6 + 2, num17].slope(0);
                Main.tile[i - num6 + 2, num17].halfBrick(false);
            }
            for (int num18 = i - num6 - 1; num18 < i + num6 + 1; num18++)
            {
                int num19 = num4 - num7 - 1;
                if (Main.tile[num18, num19].bottomSlope())
                {
                    Main.tile[num18, num19].slope(0);
                }
                Main.tile[num18, num19].halfBrick(false);
            }
            WorldGen.KillTile(i - 2, num4, false, false, false);
            WorldGen.KillTile(i - 1, num4, false, false, false);
            WorldGen.KillTile(i + 1, num4, false, false, false);
            WorldGen.KillTile(i + 2, num4, false, false, false);
            WorldGen.PlaceTile(i, num4, 135, true, false, -1, 7);
            for (int num20 = i - num6; num20 <= i + num6; num20++)
            {
                int num21 = num4;
                if ((double)num20 < (double)i - (double)num6 * 0.8 || (double)num20 > (double)i + (double)num6 * 0.8)
                {
                    num21 = num4 - 3;
                }
                else if ((double)num20 < (double)i - (double)num6 * 0.6 || (double)num20 > (double)i + (double)num6 * 0.6)
                {
                    num21 = num4 - 2;
                }
                else if ((double)num20 < (double)i - (double)num6 * 0.4 || (double)num20 > (double)i + (double)num6 * 0.4)
                {
                    num21 = num4 - 1;
                }
                for (int num22 = num5; num22 <= num4; num22++)
                {
                    if (num20 == i && num22 <= num4)
                    {
                        Main.tile[i, num22].wire(true);
                    }
                    if (Main.tile[num20, num22].active() && Main.tileSolid[(int)Main.tile[num20, num22].type])
                    {
                        if (num22 < num5 + num - 4)
{
                            Main.tile[num20, num22].actuator(true);
                            Main.tile[num20, num22].wire(true);
                        }
                        else if (num22 < num21)
{
                            WorldGen.KillTile(num20, num22, false, false, false);
                        }
                    }
                }
            }
            return true;
        }
References Terraria.Tile.active(), Terraria.WorldGen.SecretSeed.Variations.actuallyNoTrapsForRealIMeanIt, Terraria.Tile.actuator(), Terraria.ID.TileID.Sets.BasicChest, Terraria.Tile.bottomSlope(), Terraria.Tile.ClearTile(), Terraria.WorldGen.genRand, Terraria.Tile.halfBrick(), int, Terraria.WorldGen.KillTile(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.ID.TileID.Sets.Ore, Terraria.ID.TileID.Sets.Paintings, Terraria.WorldGen.PlaceTile(), Terraria.Tile.slope(), Terraria.Main.tile, Terraria.Main.tileSolid, Terraria.Tile.topSlope(), Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, and Terraria.Tile.wire().