Terraria Decompiled: Terraria.WorldGen.UpdateLunarApocalypse
UpdateLunarApocalypse()
static void Terraria.WorldGen.UpdateLunarApocalypse () inline static
Definition at line 87581 of file WorldGen.cs.
        {
            if (!NPC.LunarApocalypseIsUp)
            {
                return;
            }
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            for (int i = 0; i < Main.maxNPCs; i++)
            {
                if (Main.npc[i].active)
                {
                    int type = Main.npc[i].type;
                    if (type <= 422)
                    {
                        if (type != 398)
{
                            if (type == 422)
{
                                flag3 = true;
                            }
                        }
                        else
{
                            flag = true;
                        }
                    }
                    else if (type != 493)
                    {
                        if (type != 507)
{
                            if (type == 517)
{
                                flag2 = true;
                            }
                        }
                        else
{
                            flag4 = true;
                        }
                    }
                    else
                    {
                        flag5 = true;
                    }
                }
            }
            if (!flag2)
            {
                NPC.TowerActiveSolar = false;
            }
            if (!flag3)
            {
                NPC.TowerActiveVortex = false;
            }
            if (!flag4)
            {
                NPC.TowerActiveNebula = false;
            }
            if (!flag5)
            {
                NPC.TowerActiveStardust = false;
            }
            if (!NPC.TowerActiveSolar && !NPC.TowerActiveVortex && !NPC.TowerActiveNebula && !NPC.TowerActiveStardust && !flag)
            {
                WorldGen.StartImpendingDoom(3600);
            }
        }
References Terraria.NPC.active, Terraria.NPC.LunarApocalypseIsUp, Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.WorldGen.StartImpendingDoom(), Terraria.NPC.TowerActiveNebula, Terraria.NPC.TowerActiveSolar, Terraria.NPC.TowerActiveStardust, Terraria.NPC.TowerActiveVortex, and Terraria.NPC.type.
Referenced by Terraria.NPC.DoDeathEvents(), and Terraria.WorldGen.UpdateWorld().