Terraria Decompiled: Terraria.WorldGen.SpawnStormLightning
SpawnStormLightning()
static void Terraria.WorldGen.SpawnStormLightning () inline static private
Definition at line 72254 of file WorldGen.cs.
        {
            if (!Main.IsItStorming)
            {
                return;
            }
            int num = 150;
            if (NPC.AnyDanger(false, false))
            {
                num = (int)(1.5 * (double)num);
            }
            List<Rectangle> spawnThunderStorm_SafeSpots = WorldGen._SpawnThunderStorm_SafeSpots;
            spawnThunderStorm_SafeSpots.Clear();
            for (int i = 0; i < 255; i++)
            {
                Player player = Main.player[i];
                if (player.active && !player.dead)
                {
                    Point point = new Point(24, 24);
                    Rectangle rectangle = Utils.CenteredRectangle(player.Center.ToTileCoordinates(), point);
                    Rectangle rectangle2 = rectangle;
                    double num2 = Utils.Clamp<double>((double)player.velocity.X, -5.75, 5.75);
                    rectangle2.Offset(new Point((int)(num2 * 60.0 / 16.0), 0));
                    rectangle = Rectangle.Union(rectangle, rectangle2);
                    spawnThunderStorm_SafeSpots.Add(rectangle);
                }
            }
            for (int j = 0; j < 255; j++)
            {
                Player player2 = Main.player[j];
                if (player2.active && !player2.dead && player2.ZoneRain && !player2.ZoneSnow && player2.afkCounter < Player.AFKTimeNeededForNoLuckyStars)
                {
                    int num3 = num;
                    if (player2.sleeping.isSleeping)
                    {
                        num3 *= 2;
                    }
                    if (player2.HeldItem.fishingPole > 0)
                    {
                        num3 *= 2;
                    }
                    if (Main.rand.Next(num3) == 0)
                    {
                        WorldGen.SpawnStormLightningNearPlayer(spawnThunderStorm_SafeSpots, player2);
                    }
                }
            }
        }
References Terraria.WorldGen._SpawnThunderStorm_SafeSpots, Terraria.Player.active, System.Collections.Generic.List< T >.Add(), Terraria.Player.afkCounter, Terraria.Player.AFKTimeNeededForNoLuckyStars, Terraria.NPC.AnyDanger(), Terraria.Entity.Center, Terraria.Utils.CenteredRectangle(), Terraria.Utils.Clamp(), System.Collections.Generic.List< T >.Clear(), Terraria.Player.dead, Terraria.Item.fishingPole, Terraria.Player.HeldItem, int, Terraria.Main.IsItStorming, Terraria.GameContent.PlayerSleepingHelper.isSleeping, Terraria.Utilities.UnifiedRandom.Next(), Microsoft.Xna.Framework.Rectangle.Offset(), Terraria.Main.player, Terraria.Main.rand, Terraria.Player.sleeping, Terraria.WorldGen.SpawnStormLightningNearPlayer(), Microsoft.Xna.Framework.Rectangle.Union(), Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, Terraria.Player.ZoneRain, and Terraria.Player.ZoneSnow.
Referenced by Terraria.WorldGen.UpdateWorld().