Terraria Decompiled: Terraria.WorldGen.ClearUnbreakableWallsWithPaintUpTo
ClearUnbreakableWallsWithPaintUpTo()
static void Terraria.WorldGen.ClearUnbreakableWallsWithPaintUpTo (int tierColor) inline static
Definition at line 29117 of file WorldGen.cs.
        {
            if (Main.netMode == 1)
            {
                return;
            }
            WorldGen.TransformWorldOnBackgroundThread(delegate
            {
                for (int i = 0; i < Main.maxTilesX; i++)
                {
                    for (int j = 0; j < Main.maxTilesY; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (tile.wall == 350 && (int)(tile.wallColor() & 15) <= tierColor)
{
                            tile.wall = TileID.Sets.MatchingUnsafeWall[(int)tile.type];
                            tile.wallColor(0);
                        }
                    }
                }
            }, delegate
            {
                if (Main.netMode == 2)
                {
                    Netplay.ResetSections();
                }
            });
        }
References Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.netMode, Terraria.Main.tile, Terraria.WorldGen.TransformWorldOnBackgroundThread(), Terraria.Tile.wall, and Terraria.Tile.wallColor().
Referenced by Terraria.NPC.OnGameEventClearedForTheFirstTime().