Terraria Decompiled: Terraria.WorldGen.ShimmerifySideOfWorld
ShimmerifySideOfWorld()
static void Terraria.WorldGen.ShimmerifySideOfWorld (bool left) inline static private
Definition at line 21281 of file WorldGen.cs.
        {
            int num = Main.maxTilesX / 2;
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                if ((!left || i < num) && (left || i > num))
                {
                    for (int j = 0; j < Main.UnderworldLayer; j++)
                    {
                        Tile tile = Main.tile[i, j];
                        if (!Main.wallDungeon[(int)tile.wall])
{
                            if (tile.liquid > 0 && !tile.shimmer() && !tile.honey())
{
                                tile.liquidType(3);
                            }
                            if (tile.type == 373 || tile.type == 374 || tile.type == 375)
{
                                tile.type = 709;
                            }
                        }
                    }
                }
            }
        }
References Terraria.Tile.honey(), Terraria.Tile.liquid, Terraria.Tile.liquidType(), Terraria.Main.maxTilesX, Terraria.Tile.shimmer(), Terraria.Main.tile, Terraria.Tile.type, Terraria.Main.UnderworldLayer, Terraria.Tile.wall, and Terraria.Main.wallDungeon.