Terraria Decompiled: System.Resources.Win32ResFileReader.read_int16
read_int16()
int System.Resources.Win32ResFileReader.read_int16 () inline private
Definition at line 18 of file Win32ResFileReader.cs.
        {
            int num = this.res_file.ReadByte();
            if (num == -1)
            {
                return -1;
            }
            int num2 = this.res_file.ReadByte();
            if (num2 == -1)
            {
                return -1;
            }
            return num | (num2 << 8);
        }
References System.IO.Stream.ReadByte(), and System.Resources.Win32ResFileReader.res_file.
Referenced by System.Resources.Win32ResFileReader.read_int32(), System.Resources.Win32ResFileReader.read_ordinal(), System.Resources.Win32ResFileReader.read_padding(), and System.Resources.Win32ResFileReader.ReadResources().