Terraria Decompiled: System.Resources.Win32ResFileReader.ReadResources
ReadResources()
ICollection System.Resources.Win32ResFileReader.ReadResources () inline
Definition at line 92 of file Win32ResFileReader.cs.
        {
            ArrayList arrayList = new ArrayList();
            while (this.read_padding())
            {
                int num = this.read_int32();
                if (num == -1)
                {
                    break;
                }
                this.read_int32();
                NameOrId nameOrId = this.read_ordinal();
                NameOrId nameOrId2 = this.read_ordinal();
                if (!this.read_padding())
                {
                    break;
                }
                this.read_int32();
                this.read_int16();
                int num2 = this.read_int16();
                this.read_int32();
                this.read_int32();
                if (num != 0)
                {
                    byte[] array = new byte[num];
                    if (this.res_file.Read(array, 0, num) != num)
                    {
                        break;
                    }
                    arrayList.Add(new Win32EncodedResource(nameOrId, nameOrId2, num2, array));
                }
            }
            return arrayList;
        }
References System.Collections.ArrayList.Add(), System.array, System.IO.Stream.Read(), System.Resources.Win32ResFileReader.read_int16(), System.Resources.Win32ResFileReader.read_int32(), System.Resources.Win32ResFileReader.read_ordinal(), System.Resources.Win32ResFileReader.read_padding(), and System.Resources.Win32ResFileReader.res_file.
Referenced by System.Reflection.Emit.AssemblyBuilder.DefineUnmanagedResource().