Terraria Decompiled: System.Runtime.Serialization.ObjectIDGenerator.Rehash
Rehash()
void System.Runtime.Serialization.ObjectIDGenerator.Rehash () inline private
Definition at line 102 of file ObjectIDGenerator.cs.
        {
            int num = 0;
            int currentSize = this.m_currentSize;
            while (num < ObjectIDGenerator.sizes.Length && ObjectIDGenerator.sizes[num] <= currentSize)
            {
                num++;
            }
            if (num == ObjectIDGenerator.sizes.Length)
            {
                throw new SerializationException(Environment.GetResourceString("The internal array cannot expand to greater than Int32.MaxValue elements."));
            }
            this.m_currentSize = ObjectIDGenerator.sizes[num];
            long[] array = new long[this.m_currentSize * 4];
            object[] array2 = new object[this.m_currentSize * 4];
            long[] ids = this.m_ids;
            object[] objs = this.m_objs;
            this.m_ids = array;
            this.m_objs = array2;
            for (int i = 0; i < objs.Length; i++)
            {
                if (objs[i] != null)
                {
                    bool flag;
                    int num2 = this.FindElement(objs[i], out flag);
                    this.m_objs[num2] = objs[i];
                    this.m_ids[num2] = ids[i];
                }
            }
        }
References System.array, System.Runtime.Serialization.ObjectIDGenerator.FindElement(), System.Environment.GetResourceString(), System.Runtime.Serialization.ObjectIDGenerator.m_currentSize, System.Runtime.Serialization.ObjectIDGenerator.m_ids, System.Runtime.Serialization.ObjectIDGenerator.m_objs, and System.Runtime.Serialization.ObjectIDGenerator.sizes.
Referenced by System.Runtime.Serialization.ObjectIDGenerator.GetId().