Terraria Decompiled: System.Runtime.Serialization.ObjectIDGenerator.FindElement
FindElement()
int System.Runtime.Serialization.ObjectIDGenerator.FindElement (object obj, out bool found) inline private
Definition at line 22 of file ObjectIDGenerator.cs.
        {
            int num = RuntimeHelpers.GetHashCode(obj);
            int num2 = 1 + (num & int.MaxValue) % (this.m_currentSize - 2);
            int i;
            for (;;)
            {
                int num3 = (num & int.MaxValue) % this.m_currentSize * 4;
                for (i = num3; i < num3 + 4; i++)
                {
                    if (this.m_objs[i] == null)
                    {
                        goto Block_1;
                    }
                    if (this.m_objs[i] == obj)
                    {
                        goto Block_2;
                    }
                }
                num += num2;
            }
            Block_1:
            found = false;
            return i;
            Block_2:
            found = true;
            return i;
        }
References System.Runtime.CompilerServices.RuntimeHelpers.GetHashCode(), System.Runtime.Serialization.ObjectIDGenerator.m_currentSize, System.Runtime.Serialization.ObjectIDGenerator.m_objs, and System.obj.
Referenced by System.Runtime.Serialization.ObjectIDGenerator.GetId(), System.Runtime.Serialization.ObjectIDGenerator.HasId(), and System.Runtime.Serialization.ObjectIDGenerator.Rehash().