Terraria Decompiled: System.Runtime.Serialization.ObjectIDGenerator.GetId
GetId()
virtual long System.Runtime.Serialization.ObjectIDGenerator.GetId (object obj, out bool firstTime) inline virtual
Definition at line 52 of file ObjectIDGenerator.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj", Environment.GetResourceString("Object cannot be null."));
            }
            bool flag;
            int num = this.FindElement(obj, out flag);
            long num3;
            if (!flag)
            {
                this.m_objs[num] = obj;
                long[] ids = this.m_ids;
                int num2 = num;
                int currentCount = this.m_currentCount;
                this.m_currentCount = currentCount + 1;
                ids[num2] = (long)currentCount;
                num3 = this.m_ids[num];
                if (this.m_currentCount > this.m_currentSize * 4 / 2)
                {
                    this.Rehash();
                }
            }
            else
            {
                num3 = this.m_ids[num];
            }
            firstTime = !flag;
            return num3;
        }
References System.Runtime.Serialization.ObjectIDGenerator.FindElement(), System.Environment.GetResourceString(), long, System.Runtime.Serialization.ObjectIDGenerator.m_currentCount, System.Runtime.Serialization.ObjectIDGenerator.m_currentSize, System.Runtime.Serialization.ObjectIDGenerator.m_ids, System.Runtime.Serialization.ObjectIDGenerator.m_objs, System.obj, and System.Runtime.Serialization.ObjectIDGenerator.Rehash().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectWriter.InternalGetId(), and System.Runtime.Serialization.Formatter.Schedule().