Terraria Decompiled: System.Runtime.Remoting.Contexts.SynchronizedContextReplySink.SyncProcessMessage
SyncProcessMessage()
IMessage System.Runtime.Remoting.Contexts.SynchronizedContextReplySink.SyncProcessMessage (IMessage msg) inline
Implements System.Runtime.Remoting.Messaging.IMessageSink.
Definition at line 34 of file SynchronizedContextReplySink.cs.
        {
            if (this._newLock)
            {
                this._att.AcquireLock();
            }
            else
            {
                this._att.ReleaseLock();
            }
            IMessage message;
            try
            {
                message = this._next.SyncProcessMessage(msg);
            }
            finally
            {
                if (this._newLock)
                {
                    this._att.ReleaseLock();
                }
            }
            return message;
        }
References System.Runtime.Remoting.Contexts.SynchronizedContextReplySink._att, System.Runtime.Remoting.Contexts.SynchronizedContextReplySink._newLock, System.Runtime.Remoting.Contexts.SynchronizedContextReplySink._next, System.Runtime.Remoting.Contexts.SynchronizationAttribute.AcquireLock(), System.Runtime.Remoting.Contexts.SynchronizationAttribute.ReleaseLock(), and System.Runtime.Remoting.Messaging.IMessageSink.SyncProcessMessage().