Terraria Decompiled: rail.IRailGlobalAchievementImpl.GetGlobalAchievedPercentDescending
GetGlobalAchievedPercentDescending()
virtual RailResult rail.IRailGlobalAchievementImpl.GetGlobalAchievedPercentDescending (int index, out string name, out double percent) inline virtual
Implements rail.IRailGlobalAchievement.
Definition at line 32 of file IRailGlobalAchievementImpl.cs.
        {
            IntPtr intPtr = RAIL_API_PINVOKE.new_RailString__SWIG_0();
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailGlobalAchievement_GetGlobalAchievedPercentDescending(this.swigCPtr_, index, intPtr, out percent);
            }
            finally
            {
                name = RAIL_API_PINVOKE.RailString_c_str(intPtr);
                RAIL_API_PINVOKE.delete_RailString(intPtr);
            }
            return railResult;
        }
References rail.RAIL_API_PINVOKE.delete_RailString(), System.index, rail.RAIL_API_PINVOKE.IRailGlobalAchievement_GetGlobalAchievedPercentDescending(), System.name, rail.RAIL_API_PINVOKE.new_RailString__SWIG_0(), and rail.RAIL_API_PINVOKE.RailString_c_str().