Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.ProvidePowerButtons
ProvidePowerButtons()
void Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.ProvidePowerButtons (CreativePowerUIElementRequestInfo info, List< UIElement > elements) inline
Implements Terraria.GameContent.Creative.ICreativePower.
Definition at line 905 of file CreativePowers.cs.
            {
                GroupOptionButton<bool> groupOptionButton = CreativePowersHelper.CreateToggleButton(info);
                CreativePowersHelper.UpdateUnlockStateByPower(this, groupOptionButton, Main.OurFavoriteColor);
                this.CustomizeButton(groupOptionButton);
                groupOptionButton.OnLeftClick += this.button_OnClick;
                groupOptionButton.OnUpdate += this.button_OnUpdate;
                elements.Add(groupOptionButton);
            }
References System.Collections.Generic.List< T >.Add(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnClick(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.button_OnUpdate(), Terraria.GameContent.Creative.CreativePowersHelper.CreateToggleButton(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.CustomizeButton(), System.info, Terraria.Main.OurFavoriteColor, and Terraria.GameContent.Creative.CreativePowersHelper.UpdateUnlockStateByPower().