Terraria Decompiled: Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage
DeserializeNetMessage()
void Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.DeserializeNetMessage (BinaryReader reader, int userId) inline
Implements Terraria.GameContent.Creative.ICreativePower.
Definition at line 880 of file CreativePowers.cs.
            {
                bool flag = reader.ReadBoolean();
                if (Main.netMode == 2 && !CreativePowersHelper.IsAvailableForPlayer(this, userId))
                {
                    return;
                }
                this.SetPowerInfo(flag);
                if (Main.netMode == 2)
                {
                    NetPacket netPacket = NetCreativePowersModule.PreparePacket(this.PowerId, 1);
                    netPacket.Writer.Write(this.Enabled);
                    NetManager.Instance.Broadcast(netPacket, -1);
                }
            }
References Terraria.Net.NetManager.Broadcast(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.Enabled, Terraria.Net.NetManager.Instance, Terraria.GameContent.Creative.CreativePowersHelper.IsAvailableForPlayer(), Terraria.Main.netMode, Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.PowerId, Terraria.GameContent.NetModules.NetCreativePowersModule.PreparePacket(), System.IO.BinaryReader.ReadBoolean(), Terraria.GameContent.Creative.CreativePowers.ASharedTogglePower.SetPowerInfo(), System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.