Terraria Decompiled: ReLogic.OS.Windows.Clipboard.InvokeInStaThread
InvokeInStaThread()
static void ReLogic.OS.Windows.Clipboard.InvokeInStaThread (Action callback) inline static private
Definition at line 73 of file Clipboard.cs.
        {
            if (Clipboard.GetApartmentStateSafely() == null)
            {
                callback.Invoke();
                return;
            }
            Thread thread = new Thread(delegate
            {
                callback.Invoke();
            });
            thread.SetApartmentState(0);
            thread.Start();
            thread.Join();
        }
References ReLogic.OS.Windows.Clipboard.GetApartmentStateSafely(), System.Threading.Thread.Join(), System.Threading.Thread.SetApartmentState(), and System.Threading.Thread.Start().
Referenced by ReLogic.OS.Windows.Clipboard.SetClipboard(), and ReLogic.OS.Windows.Clipboard.TryToGetClipboardText().