Terraria Decompiled: System.IO.BufferedStream.d__42.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.BufferedStream.d__42.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1414 of file BufferedStream.cs.
            {
                int num2;
                int num = num2;
                BufferedStream bufferedStream = this;
                try
                {
                    ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                    ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                    if (num != 0)
                    {
                        if (num == 1)
{
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num2 = -1;
                            goto IL_010D;
                        }
                        configuredValueTaskAwaiter = bufferedStream._stream.WriteAsync(new ReadOnlyMemory<byte>(bufferedStream._buffer, 0, bufferedStream._writePos), cancellationToken).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num2 = 0;
                            ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter, BufferedStream.<FlushWriteAsync>d__42>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                    }
                    configuredValueTaskAwaiter.GetResult();
                    bufferedStream._writePos = 0;
                    configuredTaskAwaiter = bufferedStream._stream.FlushAsync(cancellationToken).ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter.IsCompleted)
                    {
                        num2 = 1;
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, BufferedStream.<FlushWriteAsync>d__42>(ref configuredTaskAwaiter, ref this);
                        return;
                    }
                    IL_010D:
                    configuredTaskAwaiter.GetResult();
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.IO.BufferedStream._buffer, System.IO.BufferedStream._stream, System.IO.BufferedStream._writePos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.Stream.FlushAsync(), System.IO.BufferedStream.FlushWriteAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable< TResult >.ConfiguredValueTaskAwaiter.IsCompleted, and System.IO.Stream.WriteAsync().