Terraria Decompiled: Terraria.Initializers.AssetInitializer.CreateAssetServices
CreateAssetServices()
static void Terraria.Initializers.AssetInitializer.CreateAssetServices (GameServiceContainer services) inline static
Definition at line 22 of file AssetInitializer.cs.
        {
            AssetReaderCollection assetReaderCollection = new AssetReaderCollection();
            assetReaderCollection.RegisterReader(new PngReader(XnaExtensions.Get<IGraphicsDeviceService>(services).GraphicsDevice), new string[] { ".png" });
            assetReaderCollection.RegisterReader(new XnbReader(services), new string[] { ".xnb" });
            AsyncAssetLoader asyncAssetLoader = new AsyncAssetLoader(assetReaderCollection, 20);
            asyncAssetLoader.RequireTypeCreationOnTransfer(typeof(Texture2D));
            asyncAssetLoader.RequireTypeCreationOnTransfer(typeof(DynamicSpriteFont));
            asyncAssetLoader.RequireTypeCreationOnTransfer(typeof(SpriteFont));
            IAssetRepository assetRepository = new AssetRepository(new AssetLoader(assetReaderCollection), asyncAssetLoader);
            IAssetRepository assetRepository2 = assetRepository;
            assetRepository2.AssetValueUpdatedHandler = (AssetValueUpdated)Delegate.Combine(assetRepository2.AssetValueUpdatedHandler, new AssetValueUpdated(AssetInitializer.TagAsset));
            services.AddService(typeof(AssetReaderCollection), assetReaderCollection);
            services.AddService(typeof(IAssetRepository), assetRepository);
        }
References Microsoft.Xna.Framework.GameServiceContainer.AddService(), ReLogic.Content.AssetValueUpdated(), ReLogic.Content.IAssetRepository.AssetValueUpdatedHandler, System.Delegate.Combine(), Microsoft.Xna.Framework.Graphics.IGraphicsDeviceService.GraphicsDevice, ReLogic.Content.AssetReaderCollection.RegisterReader(), ReLogic.Content.AsyncAssetLoader.RequireTypeCreationOnTransfer(), and Terraria.Initializers.AssetInitializer.TagAsset().
Referenced by Terraria.Main.LoadContent().