Terraria Decompiled: Terraria.UI.ItemSlot.TryEnteringFastUseMode
TryEnteringFastUseMode()
static bool Terraria.UI.ItemSlot.TryEnteringFastUseMode (Item[] inv, int context, int slot, Player player, ref string s) inline static private
Definition at line 4192 of file ItemSlot.cs.
        {
            int num = 0;
            if (Main.mouseItem.CanBeQuickUsed)
            {
                num = 1;
            }
            if (num == 0 && Main.mouseItem.stack <= 0 && context == 0 && inv[slot].CanBeQuickUsed)
            {
                num = 2;
            }
            if (num > 0)
            {
                s += PlayerInput.BuildCommand(Language.GetTextValue("UI.QuickUseItem"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["QuickMount"] });
                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.QuickMount)
                {
                    if (num == 1)
                    {
                        PlayerInput.TryEnteringFastUseModeForMouseItem();
                    }
                    else if (num == 2)
                    {
                        PlayerInput.TryEnteringFastUseModeForInventorySlot(slot);
                    }
                }
                return true;
            }
            return false;
        }
References Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.Item.CanBeQuickUsed, Terraria.UI.ItemSlot.CanExecuteCommand(), Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.TriggersPack.JustPressed, Terraria.Main.mouseItem, Terraria.GameInput.TriggersSet.QuickMount, System.s, Terraria.Item.stack, Terraria.GameInput.PlayerInput.Triggers, Terraria.GameInput.PlayerInput.TryEnteringFastUseModeForInventorySlot(), and Terraria.GameInput.PlayerInput.TryEnteringFastUseModeForMouseItem().