Terraria Decompiled: Terraria.UI.ItemSlot.Draw
Draw() [2/2]
static void Terraria.UI.ItemSlot.Draw (SpriteBatch spriteBatch, ref Item inv, int context, Vector2 position, Color lightColor = default(Color)) inline static
Definition at line 1835 of file ItemSlot.cs.
        {
            ItemSlot.singleSlotArray[0] = inv;
            ItemSlot.Draw(spriteBatch, ItemSlot.singleSlotArray, context, 0, position, lightColor);
            inv = ItemSlot.singleSlotArray[0];
        }
References Terraria.UI.ItemSlot.Draw(), and Terraria.UI.ItemSlot.singleSlotArray.
Referenced by Terraria.Graphics.Renderers.ItemTransferParticle.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.UI.BannerClaimingUI.DrawBannersGrid(), Terraria.UI.BannerClaimingUI.DrawBannersList(), Terraria.Main.DrawInterface_38_MouseCarriedObject(), Terraria.Main.DrawInventory(), Terraria.UI.ItemSlot.DrawRadialCircular(), Terraria.UI.ItemSlot.DrawRadialDpad(), Terraria.UI.ItemSlot.DrawRadialQuicks(), Terraria.UI.CraftingUI.DrawRecipesGrid(), Terraria.UI.CraftingUI.DrawRecipesList(), Terraria.GameContent.UI.NewCraftingUI.DrawRecipeSlot(), Terraria.GameContent.UI.Elements.UIItemSlot.DrawSelf(), Terraria.GameContent.UI.Elements.UICreativeItemGrid.DrawSlot(), Terraria.GameContent.UI.NewCraftingUI.ItemGrid.DrawSlot(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.DrawSlotMisc(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.DrawSlotPairSet(), Terraria.GameContent.Tile_Entities.TEHatRack.DrawSlotPairSet(), Terraria.UI.ChestUI.DrawSlots(), Terraria.Main.DrawTrashItemSlot(), Terraria.Main.GUIHotbarDrawInner(), and Terraria.GameContent.UI.Chat.ItemTagHandler.ItemSnippet.UniqueDraw().