Terraria Decompiled: Terraria.UI.ItemSlot.GetAlternateClickAction
GetAlternateClickAction()
static ItemSlot.? AlternateClickAction Terraria.UI.ItemSlot.GetAlternateClickAction (Item[] inv, int context, int slot) inline static
Definition at line 335 of file ItemSlot.cs.
        {
            Item item = inv[slot];
            if (item.IsAir || item.favorited)
            {
                return null;
            }
            bool flag = ItemSlot.Options.DisableLeftShiftTrashCan && !PlayerInput.UsingGamepad;
            if (ItemSlot.ControlInUse && !ItemSlot.Options.DisableQuickTrash && flag)
            {
                if (context <= 4 || context == 7 || context == 32)
                {
                    return ItemSlot.AlternateClickAction.GetSellOrTrash(item);
                }
            }
            else if (ItemSlot.ShiftInUse)
            {
                if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity())
                {
                    ItemSlot.AlternateClickAction? shiftClickAction = Main.LocalPlayer.tileEntityAnchor.GetTileEntity().GetShiftClickAction(inv, context, slot);
                    if (shiftClickAction != null)
                    {
                        return shiftClickAction;
                    }
                }
                switch (context)
                {
                case 0:
                case 1:
                case 2:
                    if (Main.CreativeMenu.IsShowingResearchMenu())
                    {
                        if (context == 0)
{
                            return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.TransferToChest);
                        }
                    }
                    else if (Main.InReforgeMenu)
                    {
                        if (context == 0 && item.CanHavePrefixes())
{
                            return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.TransferToChest);
                        }
                    }
                    else if (Main.InGuideCraftMenu)
                    {
                        if (context == 0 && item.material)
{
                            return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.TransferToChest);
                        }
                    }
                    else if (Main.player[Main.myPlayer].chest != -1)
                    {
                        if (ChestUI.TryPlacingInChest(inv, slot, true, context))
{
                            return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.TransferToChest);
                        }
                    }
                    else if (!ItemSlot.Options.DisableQuickTrash && !flag)
                    {
                        return ItemSlot.AlternateClickAction.GetSellOrTrash(item);
                    }
                    break;
                case 3:
                case 4:
                case 32:
                    if (Main.player[Main.myPlayer].ItemSpace(item).CanTakeItemToPersonalInventory)
                    {
                        return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.TransferFromChest);
                    }
                    break;
                case 5:
                case 6:
                case 7:
                case 29:
                    if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
                    {
                        return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.TransferToBackpack);
                    }
                    break;
                case 8:
                case 9:
                case 10:
                case 11:
                case 12:
                case 16:
                case 17:
                case 18:
                case 19:
                case 20:
                case 33:
                    if (Main.player[Main.myPlayer].ItemSpace(inv[slot]).CanTakeItemToPersonalInventory)
                    {
                        return new ItemSlot.AlternateClickAction?(ItemSlot.AlternateClickAction.Unequip);
                    }
                    break;
                }
            }
            return null;
        }
References Terraria.Player.chest, Terraria.UI.ItemSlot.ControlInUse, Terraria.Main.CreativeMenu, Terraria.UI.ItemSlot.Options.DisableQuickTrash, Terraria.UI.ItemSlot.AlternateClickAction.GetSellOrTrash(), Terraria.DataStructures.TileEntity.GetShiftClickAction(), Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.DataStructures.PlayerInteractionAnchor.IsInValidUseTileEntity(), Terraria.GameContent.Creative.CreativeUI.IsShowingResearchMenu(), System.item, Terraria.Player.ItemSpace(), Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.UI.ItemSlot.ShiftInUse, Terraria.Player.tileEntityAnchor, Terraria.UI.ItemSlot.AlternateClickAction.TransferFromChest, Terraria.UI.ItemSlot.AlternateClickAction.TransferToBackpack, Terraria.UI.ItemSlot.AlternateClickAction.TransferToChest, Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.UI.ItemSlot.AlternateClickAction.Unequip, and Terraria.GameInput.PlayerInput.UsingGamepad.
Referenced by Terraria.UI.ItemSlot.OverrideHover().