Terraria Decompiled: Terraria.UI.ItemSlot.TryOpenContainer_GrantItems
TryOpenContainer_GrantItems()
static bool Terraria.UI.ItemSlot.TryOpenContainer_GrantItems (Item item, Player player) inline static private
Definition at line 1475 of file ItemSlot.cs.
        {
            if (ItemID.Sets.BossBag[item.type])
            {
                player.OpenBossBag(item.type);
            }
            else if (ItemID.Sets.IsFishingCrate[item.type])
            {
                player.OpenFishingCrate(item.type);
            }
            else if (item.type == 3093)
            {
                player.OpenHerbBag(3093);
            }
            else if (item.type == 4345)
            {
                player.OpenCanofWorms(item.type);
            }
            else if (item.type == 4410)
            {
                player.OpenOyster(item.type);
            }
            else if (item.type == 1774)
            {
                player.OpenGoodieBag(1774);
            }
            else if (item.type == 6142)
            {
                player.OpenChilletEgg(6142);
            }
            else if (item.type == 3085)
            {
                if (!player.ConsumeItem(327, false, true))
                {
                    return false;
                }
                player.OpenLockBox(3085);
            }
            else if (item.type == 4879)
            {
                if (!player.HasItemInInventoryOrOpenVoidBag(329))
                {
                    return false;
                }
                player.OpenShadowLockbox(4879);
            }
            else if (item.type == 1869)
            {
                player.OpenPresent(1869);
            }
            else
            {
                if (item.type != 599 && item.type != 600 && item.type != 601)
                {
                    return false;
                }
                player.OpenLegacyPresent(item.type);
            }
            return true;
        }
References Terraria.ID.ItemID.Sets.BossBag, Terraria.Player.ConsumeItem(), Terraria.Player.HasItemInInventoryOrOpenVoidBag(), Terraria.ID.ItemID.Sets.IsFishingCrate, System.item, Terraria.Player.OpenBossBag(), Terraria.Player.OpenCanofWorms(), Terraria.Player.OpenChilletEgg(), Terraria.Player.OpenFishingCrate(), Terraria.Player.OpenGoodieBag(), Terraria.Player.OpenHerbBag(), Terraria.Player.OpenLegacyPresent(), Terraria.Player.OpenLockBox(), Terraria.Player.OpenOyster(), Terraria.Player.OpenPresent(), and Terraria.Player.OpenShadowLockbox().
Referenced by Terraria.UI.ItemSlot.TryOpenContainer().