Terraria Decompiled: Terraria.UI.ItemSlot.LeftClick
LeftClick()
static void Terraria.UI.ItemSlot.LeftClick (Item[] inv, int context = 0, int slot = 0) inline static
Definition at line 582 of file ItemSlot.cs.
        {
            if (Main.LocalPlayerHasPendingInventoryActions())
            {
                return;
            }
            Player player = Main.player[Main.myPlayer];
            inv[slot].newAndShiny = false;
            bool flag = Main.mouseLeftRelease && Main.mouseLeft;
            if (flag)
            {
                if (ItemSlot.OverrideLeftClick(inv, context, slot))
                {
                    return;
                }
                if (player.itemAnimation != 0 || player.itemTime != 0)
                {
                    return;
                }
            }
            int num = ItemSlot.PickItemMovementAction(inv, context, slot, Main.mouseItem);
            if (num != 3 && !flag)
            {
                return;
            }
            if (num == 0)
            {
                bool flag2 = false;
                if (context == 6 && Main.mouseItem.type != 0)
                {
                    Item item = Main.mouseItem.DeepClone();
                    if (ItemSlot.TryResearchingItem(ref item, true) | ItemSlot.TryResearchingItem(inv, slot, false))
                    {
                        flag2 = true;
                    }
                    inv[slot].SetDefaults(0, null);
                }
                Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                if (inv[slot].stack > 0)
                {
                    ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], 21, context, inv[slot].stack));
                }
                else
                {
                    ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(Main.mouseItem, context, 21, Main.mouseItem.stack));
                }
                if (inv[slot].stack > 0)
                {
                    if (context <= 17)
                    {
                        if (context == 0)
{
                            AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                            goto IL_013F;
                        }
                        if (context - 8 > 4 && context - 16 > 1)
{
                            goto IL_013F;
                        }
                    }
                    else if (context != 25 && context != 27 && context != 33)
                    {
                        goto IL_013F;
                    }
                    AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                }
                IL_013F:
                if (inv[slot].type == 0 || inv[slot].stack < 1)
                {
                    inv[slot] = new Item();
                }
                if (Item.CanStack(Main.mouseItem, inv[slot]))
                {
                    Utils.Swap<bool>(ref inv[slot].favorited, ref Main.mouseItem.favorited);
                    if (inv[slot].stack != inv[slot].maxStack && Main.mouseItem.stack != Main.mouseItem.maxStack)
                    {
                        if (Main.mouseItem.stack + inv[slot].stack <= Main.mouseItem.maxStack)
{
                            inv[slot].stack += Main.mouseItem.stack;
                            Main.mouseItem.stack = 0;
                            ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], 21, context, inv[slot].stack));
                        }
                        else
{
                            int num2 = Main.mouseItem.maxStack - inv[slot].stack;
                            inv[slot].stack += num2;
                            Main.mouseItem.stack -= num2;
                            ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], 21, context, num2));
                        }
                    }
                }
                if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                {
                    Main.mouseItem = new Item();
                }
                if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                {
                    if (context == 6 && Main.mouseItem.type == 0 && !flag2)
                    {
                        SoundEngine.PlaySound(SoundID.TrashItem, -1, -1, 0f, 1f);
                    }
                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                }
                if (context == 3 && Main.netMode == 1)
                {
                    NetMessage.SendData(32, -1, -1, null, player.chest, (float)slot, 0f, 0f, 0, 0, 0);
                }
                CoinSlot.ForceSlotState(slot, context, inv[slot]);
            }
            else if (num == 1)
            {
                if (Main.mouseItem.stack == 1 && Main.mouseItem.type > 0 && inv[slot].type > 0 && inv[slot].IsNotTheSameAs(Main.mouseItem))
                {
                    Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    if (inv[slot].stack > 0)
                    {
                        if (context <= 12)
{
                            if (context == 0)
{
                                AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                                goto IL_0595;
                            }
                            if (context - 8 > 4)
{
                                goto IL_0595;
                            }
                        }
                        else if (context - 16 > 1 && context != 33)
{
                            goto IL_0595;
                        }
                        AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                    }
                }
                else if (Main.mouseItem.type == 0 && inv[slot].type > 0)
                {
                    Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                    if (inv[slot].type == 0 || inv[slot].stack < 1)
                    {
                        inv[slot] = new Item();
                    }
                    if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                    {
                        Main.mouseItem = new Item();
                    }
                    if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                    {
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    }
                }
                else if (Main.mouseItem.type > 0 && inv[slot].type == 0)
                {
                    if (Main.mouseItem.stack == 1)
                    {
                        Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                        if (inv[slot].type == 0 || inv[slot].stack < 1)
{
                            inv[slot] = new Item();
                        }
                        if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
{
                            Main.mouseItem = new Item();
                        }
                        if (Main.mouseItem.type > 0 || inv[slot].type > 0)
{
                            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        }
                    }
                    else
                    {
                        inv[slot] = Main.mouseItem.Clone();
                        Main.mouseItem.stack--;
                        inv[slot].stack = 1;
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    }
                    if (inv[slot].stack > 0)
                    {
                        if (context <= 17)
{
                            if (context == 0)
{
                                AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                                goto IL_0595;
                            }
                            if (context - 8 > 4 && context - 16 > 1)
{
                                goto IL_0595;
                            }
                        }
                        else if (context != 25 && context != 27 && context != 33)
{
                            goto IL_0595;
                        }
                        AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                    }
                }
                IL_0595:
                if ((context == 23 || context == 24 || context == 39) && Main.netMode == 1)
                {
                    NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 0f, 0, 0, 0);
                }
                if (context == 38 && Main.netMode == 1)
                {
                    NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 3f, 0, 0, 0);
                }
                if (context == 26 && Main.netMode == 1)
                {
                    NetMessage.SendData(124, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 0f, 0, 0, 0);
                }
                CoinSlot.ForceSlotState(slot, context, inv[slot]);
            }
            else if (num == 2)
            {
                if (Main.mouseItem.stack == 1 && Main.mouseItem.dye > 0 && inv[slot].type > 0 && inv[slot].type != Main.mouseItem.type)
                {
                    Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    if (inv[slot].stack > 0)
                    {
                        if (context <= 17)
{
                            if (context == 0)
{
                                AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                                goto IL_08D7;
                            }
                            if (context - 8 > 4 && context - 16 > 1)
{
                                goto IL_08D7;
                            }
                        }
                        else if (context != 25 && context != 27 && context != 33)
{
                            goto IL_08D7;
                        }
                        AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                    }
                }
                else if (Main.mouseItem.type == 0 && inv[slot].type > 0)
                {
                    Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                    if (inv[slot].type == 0 || inv[slot].stack < 1)
                    {
                        inv[slot] = new Item();
                    }
                    if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
                    {
                        Main.mouseItem = new Item();
                    }
                    if (Main.mouseItem.type > 0 || inv[slot].type > 0)
                    {
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    }
                }
                else if (Main.mouseItem.dye > 0 && inv[slot].type == 0)
                {
                    if (Main.mouseItem.stack == 1)
                    {
                        Utils.Swap<Item>(ref inv[slot], ref Main.mouseItem);
                        if (inv[slot].type == 0 || inv[slot].stack < 1)
{
                            inv[slot] = new Item();
                        }
                        if (Main.mouseItem.type == 0 || Main.mouseItem.stack < 1)
{
                            Main.mouseItem = new Item();
                        }
                        if (Main.mouseItem.type > 0 || inv[slot].type > 0)
{
                            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        }
                    }
                    else
                    {
                        Main.mouseItem.stack--;
                        inv[slot].SetDefaults(Main.mouseItem.type, null);
                        SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    }
                    if (inv[slot].stack > 0)
                    {
                        if (context <= 17)
{
                            if (context == 0)
{
                                AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                                goto IL_08D7;
                            }
                            if (context - 8 > 4 && context - 16 > 1)
{
                                goto IL_08D7;
                            }
                        }
                        else if (context != 25 && context != 27 && context != 33)
{
                            goto IL_08D7;
                        }
                        AchievementsHelper.HandleOnEquip(player, inv[slot], context);
                    }
                }
                IL_08D7:
                if (context == 25 && Main.netMode == 1)
                {
                    NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 1f, 0, 0, 0);
                }
                if (context == 27 && Main.netMode == 1)
                {
                    NetMessage.SendData(124, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 1f, 0, 0, 0);
                }
            }
            else if (num == 3)
            {
                ItemSlot.HandleShopSlot(inv, slot, false, true);
            }
            else if (num == 4)
            {
                Chest chest = Main.instance.shop[Main.npcShop];
                if (player.SellItem(Main.mouseItem, -1))
                {
                    chest.AddItemToShop(Main.mouseItem);
                    Main.mouseItem.SetDefaults(0, null);
                    SoundEngine.PlaySound(18, -1, -1, 1, 1f, 0f);
                    ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], 21, 15, 0));
                }
                else if (Main.mouseItem.value == 0)
                {
                    chest.AddItemToShop(Main.mouseItem);
                    Main.mouseItem.SetDefaults(0, null);
                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], 21, 15, 0));
                }
                Main.stackSplit = 9999;
            }
            else if (num == 5 && Main.mouseItem.IsAir)
            {
                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                Main.mouseItem.SetDefaults(inv[slot].type, null);
                Main.mouseItem.stack = (Main.mouseItem.OnlyNeedOneInInventory() ? 1 : Main.mouseItem.maxStack);
                Main.mouseItem.OnCreated(new JourneyDuplicationItemCreationContext());
                ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], 29, 21, 0));
            }
            if (context > 2 && context != 5 && context != 32)
            {
                inv[slot].favorited = false;
            }
        }
References Terraria.Chest.AddItemToShop(), Terraria.UI.ItemSlot.AnnounceTransfer(), Terraria.Item.CanStack(), Terraria.Player.chest, Terraria.Item.Clone(), Terraria.Item.DeepClone(), Terraria.Item.dye, Terraria.Item.favorited, Terraria.UI.CoinSlot.ForceSlotState(), Terraria.GameContent.Achievements.AchievementsHelper.HandleOnEquip(), Terraria.UI.ItemSlot.HandleShopSlot(), Terraria.Main.instance, Terraria.DataStructures.PlayerInteractionAnchor.interactEntityID, Terraria.Item.IsAir, Terraria.Item.IsNotTheSameAs(), System.item, Terraria.Player.itemAnimation, Terraria.Player.itemTime, Terraria.Main.LocalPlayerHasPendingInventoryActions(), Terraria.Item.maxStack, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.newAndShiny, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Main.npcShop, Terraria.Item.OnCreated(), Terraria.Item.OnlyNeedOneInInventory(), Terraria.UI.ItemSlot.OverrideLeftClick(), Terraria.UI.ItemSlot.PickItemMovementAction(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Player.SellItem(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.Main.shop, System.stack, Terraria.Item.stack, Terraria.Player.tileEntityAnchor, Terraria.ID.SoundID.TrashItem, Terraria.UI.ItemSlot.TryResearchingItem(), Terraria.Item.type, and Terraria.Item.value.
Referenced by Terraria.UI.ItemSlot.Handle().