Terraria Decompiled: Terraria.UI.ItemSlot.SwapEquip
SwapEquip() [1/2]
static void Terraria.UI.ItemSlot.SwapEquip (Item[] inv, int context, int slot) inline static
Definition at line 3000 of file ItemSlot.cs.
        {
            Player player = Main.player[Main.myPlayer];
            if (inv[slot].IsAir)
            {
                return;
            }
            if (inv[slot].dye > 0)
            {
                bool flag;
                int num;
                inv[slot] = ItemSlot.DyeSwap(inv[slot], out flag, out num);
                if (flag)
                {
                    Main.EquipPageSelected = 0;
                    AchievementsHelper.HandleOnEquip(player, inv[slot], 12);
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.dye, 12, num);
                }
            }
            else if (Main.projHook[inv[slot].shoot])
            {
                bool flag;
                inv[slot] = ItemSlot.EquipSwap(inv[slot], player.miscEquips, 4, out flag);
                if (flag)
                {
                    Main.EquipPageSelected = 2;
                    AchievementsHelper.HandleOnEquip(player, player.miscEquips[4], 16);
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.miscEquips, 16, 4);
                }
            }
            else if (inv[slot].mountType != -1 && !MountID.Sets.Cart[inv[slot].mountType])
            {
                bool flag;
                inv[slot] = ItemSlot.EquipSwap(inv[slot], player.miscEquips, 3, out flag);
                if (flag)
                {
                    Main.EquipPageSelected = 2;
                    AchievementsHelper.HandleOnEquip(player, inv[slot], 17);
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.miscEquips, 17, 3);
                }
            }
            else if (inv[slot].mountType != -1 && MountID.Sets.Cart[inv[slot].mountType])
            {
                bool flag;
                inv[slot] = ItemSlot.EquipSwap(inv[slot], player.miscEquips, 2, out flag);
                if (flag)
                {
                    Main.EquipPageSelected = 2;
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.miscEquips, 18, 2);
                }
            }
            else if (inv[slot].buffType > 0 && Main.lightPet[inv[slot].buffType])
            {
                bool flag;
                inv[slot] = ItemSlot.EquipSwap(inv[slot], player.miscEquips, 1, out flag);
                if (flag)
                {
                    Main.EquipPageSelected = 2;
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.miscEquips, 20, 1);
                }
            }
            else if (inv[slot].buffType > 0 && Main.vanityPet[inv[slot].buffType])
            {
                bool flag;
                inv[slot] = ItemSlot.EquipSwap(inv[slot], player.miscEquips, 0, out flag);
                if (flag)
                {
                    Main.EquipPageSelected = 2;
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.miscEquips, 19, 0);
                }
            }
            else
            {
                int num2 = (inv[slot].accessory ? 10 : (inv[slot].vanity ? 9 : 8));
                bool flag;
                int num3;
                inv[slot] = ItemSlot.ArmorSwap(inv[slot], out flag, out num3);
                if (flag)
                {
                    Main.EquipPageSelected = 0;
                    Item item = player.armor[num3];
                    AchievementsHelper.HandleOnEquip(player, item, num2);
                    ItemSlot.DisplayTransfer_TwoWay(inv, context, slot, player.armor, num2, num3);
                }
            }
            if (context == 3 && Main.netMode == 1)
            {
                NetMessage.SendData(32, -1, -1, null, player.chest, (float)slot, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.Item.accessory, Terraria.Player.armor, Terraria.UI.ItemSlot.ArmorSwap(), Terraria.Item.buffType, Terraria.ID.MountID.Sets.Cart, Terraria.Player.chest, Terraria.UI.ItemSlot.DisplayTransfer_TwoWay(), Terraria.Player.dye, Terraria.UI.ItemSlot.DyeSwap(), Terraria.UI.ItemSlot.EquipSwap(), Terraria.GameContent.Achievements.AchievementsHelper.HandleOnEquip(), System.item, Terraria.Main.lightPet, Terraria.Player.miscEquips, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.player, Terraria.Main.projHook, Terraria.NetMessage.SendData(), Terraria.Item.shoot, Terraria.Item.vanity, and Terraria.Main.vanityPet.