Terraria Decompiled: Terraria.UI.ItemSlot.HandleShopSlot
HandleShopSlot()
static void Terraria.UI.ItemSlot.HandleShopSlot (Item[] inv, int slot, bool rightClickIsValid, bool leftClickIsValid) inline static private
Definition at line 1766 of file ItemSlot.cs.
        {
            if (Main.cursorOverride == 2)
            {
                return;
            }
            Chest chest = Main.instance.shop[Main.npcShop];
            bool flag = (Main.mouseRight && rightClickIsValid) || (Main.mouseLeft && leftClickIsValid);
            if (Main.stackSplit <= 1 && flag && inv[slot].type > 0 && (Item.CanStack(Main.mouseItem, inv[slot]) || Main.mouseItem.type == 0))
            {
                int num = Main.superFastStack + 1;
                if (ItemSlot.CanBulkBuy(inv[slot]))
                {
                    num *= ItemSlot.GetBulkBuyAmount(inv[slot]);
                }
                Player localPlayer = Main.LocalPlayer;
                for (int i = 0; i < num; i++)
                {
                    if (Main.mouseItem.stack < Main.mouseItem.maxStack || Main.mouseItem.type == 0)
                    {
                        long num2;
                        long num3;
                        localPlayer.GetItemExpectedPrice(inv[slot], out num2, out num3);
                        if (localPlayer.BuyItem(num3, inv[slot].shopSpecialCurrency) && inv[slot].stack > 0)
{
                            if (i == 0)
{
                                if (inv[slot].value > 0)
{
                                    SoundEngine.PlaySound(18, -1, -1, 1, 1f, 0f);
                                }
                                else
{
                                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                                }
                            }
                            if (Main.mouseItem.type == 0)
{
                                Main.mouseItem.SetDefaults(inv[slot].type, null);
                                if (inv[slot].prefix != 0)
{
                                    Main.mouseItem.Prefix((int)inv[slot].prefix);
                                }
                                Main.mouseItem.stack = 0;
                            }
                            if (!inv[slot].buyOnce && inv[slot].shopSpecialCurrency == -1)
{
                                Main.shopSellbackHelper.Add(inv[slot]);
                            }
                            Main.mouseItem.stack++;
                            ItemSlot.RefreshStackSplitCooldown();
                            if (inv[slot].buyOnce)
{
                                Item item = inv[slot];
                                int num4 = item.stack - 1;
                                item.stack = num4;
                                if (num4 <= 0)
{
                                    inv[slot].SetDefaults(0, null);
                                }
                            }
                            ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(Main.mouseItem, 15, 21, 0));
                        }
                    }
                }
            }
        }
References Terraria.GameContent.ItemShopSellbackHelper.Add(), Terraria.UI.ItemSlot.AnnounceTransfer(), Terraria.Player.BuyItem(), Terraria.UI.ItemSlot.CanBulkBuy(), Terraria.Item.CanStack(), Terraria.Main.cursorOverride, Terraria.UI.ItemSlot.GetBulkBuyAmount(), Terraria.Player.GetItemExpectedPrice(), Terraria.Main.instance, System.item, Terraria.Main.LocalPlayer, Terraria.Item.maxStack, Terraria.Main.mouseItem, Terraria.Main.mouseLeft, Terraria.Main.npcShop, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Item.Prefix(), Terraria.Item.prefix, Terraria.UI.ItemSlot.RefreshStackSplitCooldown(), Terraria.Item.SetDefaults(), Terraria.Main.shop, Terraria.Main.shopSellbackHelper, Terraria.Item.shopSpecialCurrency, Terraria.Item.stack, Terraria.Main.stackSplit, Terraria.Item.type, and System.value.
Referenced by Terraria.UI.ItemSlot.LeftClick(), and Terraria.UI.ItemSlot.RightClick().