Terraria Decompiled: Terraria.UI.ItemSlot.AddCooldown
AddCooldown()
static void Terraria.UI.ItemSlot.AddCooldown (int context, int slot, int time) inline static private
Definition at line 3174 of file ItemSlot.cs.
        {
            ItemSlot._nextTickDrawAvailable[new ItemSlot.ItemDisplayKey
            {
                Slot = slot,
                Context = context
            }] = Main.EverLastingTicker + (ulong)((long)time);
        }
References Terraria.UI.ItemSlot._nextTickDrawAvailable.
Referenced by Terraria.UI.ItemSlot.DisplayTransfer_GetItem(), Terraria.UI.ItemSlot.DisplayTransfer_OneWay(), Terraria.UI.ItemSlot.DisplayTransfer_TwoWay(), and Terraria.UI.ItemSlot.DisplayTransfer_TwoWay().