Terraria Decompiled: Terraria.UI.ItemSlot.DrawMoney
DrawMoney()
static void Terraria.UI.ItemSlot.DrawMoney (SpriteBatch sb, string text, float shopx, float shopy, int[] coinsArray, bool horizontal = false, bool fromSavings = false) inline static
Definition at line 3351 of file ItemSlot.cs.
        {
            Utils.DrawBorderStringFourWay(sb, FontAssets.MouseText.Value, text, shopx, shopy + 40f, Color.White * ((float)Main.mouseTextColor / 255f), Color.Black, Vector2.Zero, 1f);
            CoinSlot.CoinDrawState coinDrawState = default(CoinSlot.CoinDrawState);
            coinDrawState.coinAnimFrame = 0;
            coinDrawState.coinYOffset = 0f;
            coinDrawState.stackTextScale = 1f;
            if (horizontal)
            {
                for (int i = 0; i < 4; i++)
                {
                    Main.instance.LoadItem(74 - i);
                    if (i == 0)
                    {
                        int num = coinsArray[3 - i];
                    }
                    int num2 = coinsArray[3 - i];
                    if (num2 > 999)
                    {
                        num2 = 999;
                    }
                    if (fromSavings)
                    {
                        CoinSlot.UpdateSavings(i, num2, out coinDrawState);
                    }
                    Vector2 vector = new Vector2(shopx + ChatManager.GetStringSize(FontAssets.MouseText.Value, text, Vector2.One, -1f).X + (float)(24 * i) + 45f, shopy + 50f);
                    CoinSlot.DrawItemCoin(sb, vector + new Vector2(0f, -coinDrawState.coinYOffset), 74 - i, coinDrawState.coinAnimFrame, 1f, 1024f, Color.White, 1f);
                    Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, num2.ToString(), vector.X - 11f, vector.Y + (float)FontAssets.ItemStack.Value.LineSpacing * 0.75f, Color.White, Color.Black, new Vector2(0f, (float)FontAssets.ItemStack.Value.LineSpacing), 0.75f * coinDrawState.stackTextScale);
                }
                return;
            }
            for (int j = 0; j < 4; j++)
            {
                Main.instance.LoadItem(74 - j);
                int num3 = ((j == 0 && coinsArray[3 - j] > 99) ? (-6) : 0);
                int num4 = coinsArray[3 - j];
                if (num4 > 999)
                {
                    num4 = 999;
                }
                if (fromSavings)
                {
                    CoinSlot.UpdateSavings(j, num4, out coinDrawState);
                }
                CoinSlot.DrawItemCoin(sb, new Vector2(shopx + 11f + (float)(24 * j), shopy + 75f - coinDrawState.coinYOffset), 74 - j, coinDrawState.coinAnimFrame, 1f, 1024f, Color.White, 1f);
                Utils.DrawBorderStringFourWay(sb, FontAssets.ItemStack.Value, num4.ToString(), shopx + (float)(24 * j) + (float)num3, shopy + 75f + (float)FontAssets.ItemStack.Value.LineSpacing * 0.75f, Color.White, Color.Black, new Vector2(0f, (float)FontAssets.ItemStack.Value.LineSpacing), 0.75f * coinDrawState.stackTextScale);
            }
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.UI.CoinSlot.CoinDrawState.coinAnimFrame, Terraria.UI.CoinSlot.CoinDrawState.coinYOffset, Terraria.Utils.DrawBorderStringFourWay(), Terraria.UI.CoinSlot.DrawItemCoin(), Terraria.UI.Chat.ChatManager.GetStringSize(), Terraria.Main.instance, Terraria.GameContent.FontAssets.ItemStack, Terraria.Main.LoadItem(), Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseTextColor, Microsoft.Xna.Framework.Vector2.One, Terraria.UI.CoinSlot.CoinDrawState.stackTextScale, System.text, Terraria.UI.CoinSlot.UpdateSavings(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.NPCChatPanel.DrawButtons(), Terraria.UI.ItemSlot.DrawSavings(), and Terraria.GameContent.CoinLossRevengeSystem.RevengeMarker.UseMouseOver().