Terraria Decompiled: Terraria.UI.ItemSlot.ShouldHighlightSlotForMouseItem
ShouldHighlightSlotForMouseItem()
static bool Terraria.UI.ItemSlot.ShouldHighlightSlotForMouseItem (int context, int slot, Item checkItem) inline static
Definition at line 965 of file ItemSlot.cs.
        {
            bool flag = false;
            if (!checkItem.IsAir)
            {
                if (context == 8)
                {
                    flag = !ItemSlot.HasSameItemInSlot(checkItem, new ArraySegment<Item>(Main.LocalPlayer.armor, 10, 3)) && Main.LocalPlayer.armor[slot].type != checkItem.type && !checkItem.vanity && ((checkItem.headSlot > -1 && slot == 0) || (checkItem.bodySlot > -1 && slot == 1) || (checkItem.legSlot > -1 && slot == 2));
                }
                else if (context == 23)
                {
                    flag = (checkItem.headSlot > -1 && slot == 0) || (checkItem.bodySlot > -1 && slot == 1) || (checkItem.legSlot > -1 && slot == 2);
                }
                else if (context == 26)
                {
                    flag = checkItem.headSlot > -1;
                }
                else if (context == 9)
                {
                    flag = !ItemSlot.HasSameItemInSlot(checkItem, new ArraySegment<Item>(Main.LocalPlayer.armor, 0, 3)) && Main.LocalPlayer.armor[slot].type != checkItem.type && checkItem.vanity && ((checkItem.headSlot > -1 && slot == 10) || (checkItem.vanity && checkItem.bodySlot > -1 && slot == 11) || (checkItem.vanity && checkItem.legSlot > -1 && slot == 12));
                }
                else if (context == 12)
                {
                    flag = Main.LocalPlayer.IsItemSlotUnlockedAndUsable(slot) && checkItem.dye > 0;
                }
                else if (context == 33 || context == 25 || context == 27)
                {
                    flag = checkItem.dye > 0;
                }
                else if (context == 16)
                {
                    flag = checkItem.mountType == -1 && Main.projHook[checkItem.shoot];
                }
                else if (context == 17)
                {
                    flag = checkItem.mountType != -1 && !MountID.Sets.Cart[checkItem.mountType];
                }
                else if (context == 39)
                {
                    flag = checkItem.mountType != -1;
                }
                else if (context == 19)
                {
                    flag = checkItem.buffType > 0 && Main.vanityPet[checkItem.buffType] && !Main.lightPet[checkItem.buffType];
                }
                else if (context == 18)
                {
                    flag = checkItem.mountType != -1 && MountID.Sets.Cart[checkItem.mountType];
                }
                else if (context == 20)
                {
                    flag = checkItem.buffType > 0 && Main.lightPet[checkItem.buffType];
                }
                else if (context == 10)
                {
                    flag = Main.LocalPlayer.armor[slot].type != checkItem.type && !checkItem.vanity && checkItem.accessory && Main.LocalPlayer.IsItemSlotUnlockedAndUsable(slot) && ItemSlot.CanEquipAccessoryInSlot(checkItem, slot);
                }
                else if (context == 24)
                {
                    TEDisplayDoll tedisplayDoll = Main.LocalPlayer.tileEntityAnchor.GetTileEntity() as TEDisplayDoll;
                    flag = checkItem.accessory && ItemSlot.CanEquipAccessoryInSlot(checkItem, new ArraySegment<Item>(tedisplayDoll.Equipment, 3, 5), slot);
                }
                else if (context == 38)
                {
                    flag = TEDisplayDoll.AcceptedInWeaponSlot(checkItem);
                }
                else if (context == 11)
                {
                    flag = Main.LocalPlayer.armor[slot].type != checkItem.type && checkItem.vanity && checkItem.accessory && Main.LocalPlayer.IsItemSlotUnlockedAndUsable(slot) && ItemSlot.CanEquipAccessoryInVanitySlot(checkItem, slot);
                }
            }
            return flag;
        }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll.AcceptedInWeaponSlot(), Terraria.Player.armor, Terraria.Item.bodySlot, Terraria.Item.buffType, Terraria.UI.ItemSlot.CanEquipAccessoryInSlot(), Terraria.UI.ItemSlot.CanEquipAccessoryInVanitySlot(), Terraria.ID.MountID.Sets.Cart, Terraria.GameContent.Tile_Entities.TEDisplayDoll.Equipment, Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.UI.ItemSlot.HasSameItemInSlot(), Terraria.Item.headSlot, Terraria.Item.IsAir, Terraria.Player.IsItemSlotUnlockedAndUsable(), Terraria.Item.legSlot, Terraria.Main.lightPet, Terraria.Main.LocalPlayer, Terraria.Item.mountType, Terraria.Main.projHook, Terraria.Item.shoot, Terraria.Player.tileEntityAnchor, Terraria.Item.type, Terraria.Item.vanity, and Terraria.Main.vanityPet.
Referenced by Terraria.UI.ItemSlot.Draw().