Terraria Decompiled: Terraria.UI.ItemSlot.DrawItemIcon
DrawItemIcon()
static float Terraria.UI.ItemSlot.DrawItemIcon (Item item, int context, SpriteBatch spriteBatch, Vector2 screenPositionForItemCenter, float scale, float sizeLimit, Color environmentColor, float itemFade = 1f, bool flip = false) inline static
Definition at line 2553 of file ItemSlot.cs.
        {
            Color color = Color.White;
            Color color2 = Color.White;
            int type = item.type;
            Main.instance.LoadItem(type);
            Texture2D value = TextureAssets.Item[type].Value;
            Rectangle rectangle = value.Frame(1, 1, 0, 0, 0, 0);
            DrawAnimation drawAnimation = Main.itemAnimations[type];
            if (drawAnimation != null)
            {
                int num = -1;
                if (type == 5644 && context != 31 && !Main.LocalPlayer.AnyoneToSpectate())
                {
                    num = 0;
                }
                rectangle = drawAnimation.GetFrame(value, num);
            }
            float num2 = 1f;
            if (context == 37)
            {
                color = ItemSlot.OverdrawGlowColorMultiplier;
                color2 = ItemSlot.OverdrawGlowColorMultiplier;
                environmentColor = Color.White;
                num2 = ItemSlot.OverdrawGlowSize;
            }
            Color color3;
            float num3;
            ItemSlot.DrawItem_GetColorAndScale(item, scale, ref environmentColor, sizeLimit, ref rectangle, out color3, out num3);
            SpriteEffects spriteEffects = SpriteEffects.None;
            if (flip)
            {
                spriteEffects = SpriteEffects.FlipHorizontally;
            }
            Vector2 vector = rectangle.Size() / 2f;
            Color color4 = item.GetAlpha(color3).MultiplyRGBA(color);
            spriteBatch.Draw(value, screenPositionForItemCenter, new Rectangle?(rectangle), color4 * itemFade, 0f, vector, num3 * num2, spriteEffects, 0f);
            if (item.color != Color.Transparent)
            {
                Color color5 = environmentColor;
                if (context == 13)
                {
                    color5.A = byte.MaxValue;
                }
                spriteBatch.Draw(value, screenPositionForItemCenter, new Rectangle?(rectangle), item.GetColor(color5).MultiplyRGBA(color2) * itemFade, 0f, vector, num3 * num2, spriteEffects, 0f);
            }
            if (item.glowMask != -1 && item.type != 3779 && item.type != 46 && item.type != 5462)
            {
                Rectangle rectangle2 = rectangle;
                Color color6 = Color.White;
                int type2 = item.type;
                if (type2 <= 5146)
                {
                    if (type2 != 3858)
                    {
                        if (type2 == 5146)
{
                            color6 = new Color(Main.DiscoR, Main.DiscoG, Main.DiscoB);
                        }
                    }
                    else
                    {
                        color6 = new Color(255, 255, 255, 63) * 0.75f;
                        rectangle2 = TextureAssets.GlowMask[233].Value.Frame(1, 3, 0, Main.LocalPlayer.miscCounter % 15 / 5, 0, 0);
                        rectangle2.Height -= 2;
                    }
                }
                else if (type2 != 5462)
                {
                    if (type2 != 5669)
                    {
                        if (type2 - 5670 <= 1)
{
                            color6 = Item.GetPhaseColor(item.shoot, false);
                        }
                    }
                    else
                    {
                        float num4 = Utils.WrappedLerp(0.5f, 1f, (float)(Main.LocalPlayer.miscCounter % 100) / 100f);
                        color6 = Color.Lerp(color6, new Color(180, 85, 30), num4);
                        color6.A = (byte)item.alpha;
                    }
                }
                else
                {
                    color6 = new Color(255, 140, 0, 5);
                }
                if (item.type == 5670 || item.type == 5671)
                {
                    spriteBatch.Draw(TextureAssets.GlowMask[(int)item.glowMask].Value, screenPositionForItemCenter, new Rectangle?(rectangle2), color6 * itemFade, 0f, rectangle2.Size() / 2f, num3 * num2, spriteEffects, 0f);
                    color6 = Item.GetPhaseColor(item.shoot, true);
                }
                spriteBatch.Draw(TextureAssets.GlowMask[(int)item.glowMask].Value, screenPositionForItemCenter, new Rectangle?(rectangle2), color6 * itemFade, 0f, rectangle2.Size() / 2f, num3 * num2, spriteEffects, 0f);
            }
            if (ItemID.Sets.TrapSigned[item.type])
            {
                Vector2 vector2 = new Vector2(1f, -1f);
                Vector2 vector3 = rectangle.Size() * 0.45f * vector2 * num3 * num2;
                spriteBatch.Draw(TextureAssets.Wire.Value, screenPositionForItemCenter + vector3, new Rectangle?(new Rectangle(4, 58, 8, 8)), environmentColor * itemFade, 0f, new Vector2(4f), num3 * num2, SpriteEffects.None, 0f);
            }
            if (ItemID.Sets.DrawUnsafeIndicator[item.type])
            {
                Vector2 vector4 = new Vector2(1f, -1f);
                Vector2 vector5 = (rectangle.Size() * 0.45f + new Vector2(-4f, -4f)) * vector4 * num3 * num2;
                Texture2D value2 = TextureAssets.Extra[258].Value;
                Rectangle rectangle3 = value2.Frame(1, 1, 0, 0, 0, 0);
                spriteBatch.Draw(value2, screenPositionForItemCenter + vector5, new Rectangle?(rectangle3), environmentColor * itemFade, 0f, rectangle3.Size() / 2f, num3 * num2, SpriteEffects.None, 0f);
            }
            return num3;
        }
References Terraria.Player.AnyoneToSpectate(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.ItemSlot.DrawItem_GetColorAndScale(), Terraria.ID.ItemID.Sets.DrawUnsafeIndicator, Terraria.GameContent.TextureAssets.Extra, Terraria.DataStructures.DrawAnimation.GetFrame(), Terraria.Item.GetPhaseColor(), Terraria.GameContent.TextureAssets.GlowMask, Terraria.Main.instance, System.item, Terraria.GameContent.TextureAssets.Item, Terraria.Main.itemAnimations, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.LoadItem(), Terraria.Main.LocalPlayer, Terraria.Player.miscCounter, Terraria.UI.ItemSlot.OverdrawGlowColorMultiplier, Terraria.UI.ItemSlot.OverdrawGlowSize, Microsoft.Xna.Framework.Color.Transparent, Terraria.ID.ItemID.Sets.TrapSigned, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.GameContent.TextureAssets.Wire, and Terraria.Utils.WrappedLerp().
Referenced by Terraria.Graphics.Renderers.ItemTransferParticle.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Main.DrawInterface_40_InteractItemIcon(), Terraria.GameContent.Drawing.TileDrawing.DrawMultiTileVinesInWind(), Terraria.GameContent.UI.Elements.UIItemIcon.DrawSelf(), and Terraria.GameContent.Drawing.TileDrawing.DrawSpecialTilesLegacy().