Terraria Decompiled: Terraria.UI.ItemSlot.SetGlow
SetGlow()
static void Terraria.UI.ItemSlot.SetGlow (int index, float hue, bool chest) inline static
Definition at line 188 of file ItemSlot.cs.
        {
            if (!chest)
            {
                ItemSlot.inventoryGlowTime[index] = 300;
                ItemSlot.inventoryGlowHue[index] = hue;
                return;
            }
            if (hue < 0f)
            {
                ItemSlot.inventoryGlowTimeChest[index] = 0;
                ItemSlot.inventoryGlowHueChest[index] = 0f;
                return;
            }
            ItemSlot.inventoryGlowTimeChest[index] = 300;
            ItemSlot.inventoryGlowHueChest[index] = hue;
        }
References System.index, Terraria.UI.ItemSlot.inventoryGlowHue, Terraria.UI.ItemSlot.inventoryGlowHueChest, Terraria.UI.ItemSlot.inventoryGlowTime, and Terraria.UI.ItemSlot.inventoryGlowTimeChest.
Referenced by Terraria.UI.ItemSorting.FillAmmoFromInventory(), Terraria.UI.ItemSlot.SetGlowForChest(), and Terraria.UI.ItemSorting.Sort().