Terraria Decompiled: Terraria.UI.ItemSlot.PickupItemIntoMouse
PickupItemIntoMouse()
static void Terraria.UI.ItemSlot.PickupItemIntoMouse (Item[] inv, int context, int slot, Player player) inline static
Definition at line 1384 of file ItemSlot.cs.
        {
            if (Main.mouseItem.type == 0)
            {
                Main.mouseItem = inv[slot].Clone();
                if (context == 29)
                {
                    Main.mouseItem.SetDefaults(Main.mouseItem.type, null);
                    Main.mouseItem.OnCreated(new JourneyDuplicationItemCreationContext());
                }
                Main.mouseItem.stack = 0;
                if (inv[slot].favorited && inv[slot].stack == 1)
                {
                    Main.mouseItem.favorited = true;
                }
                else
                {
                    Main.mouseItem.favorited = false;
                }
                ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(inv[slot], context, 21, 0));
            }
            Main.mouseItem.stack++;
            if (context != 29)
            {
                inv[slot].stack--;
            }
            if (inv[slot].stack <= 0)
            {
                inv[slot] = new Item();
            }
            CoinSlot.ForceSlotState(slot, context, inv[slot]);
            if (context == 3 && Main.netMode == 1)
            {
                NetMessage.SendData(32, -1, -1, null, player.chest, (float)slot, 0f, 0f, 0, 0, 0);
            }
            if ((context == 23 || context == 24 || context == 39) && Main.netMode == 1)
            {
                NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 0f, 0, 0, 0);
            }
            if (context == 25 && Main.netMode == 1)
            {
                NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 1f, 0, 0, 0);
            }
            if (context == 38 && Main.netMode == 1)
            {
                NetMessage.SendData(121, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 3f, 0, 0, 0);
            }
            if (context == 26 && Main.netMode == 1)
            {
                NetMessage.SendData(124, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 0f, 0, 0, 0);
            }
            if (context == 27 && Main.netMode == 1)
            {
                NetMessage.SendData(124, -1, -1, null, Main.myPlayer, (float)player.tileEntityAnchor.interactEntityID, (float)slot, 1f, 0, 0, 0);
            }
        }
References Terraria.UI.ItemSlot.AnnounceTransfer(), Terraria.Player.chest, Terraria.Item.Clone(), Terraria.UI.CoinSlot.ForceSlotState(), Terraria.DataStructures.PlayerInteractionAnchor.interactEntityID, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Item.OnCreated(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), System.stack, Terraria.Item.stack, Terraria.Player.tileEntityAnchor, and Terraria.Item.type.
Referenced by Terraria.UI.ItemSlot.RightClick(), and Terraria.GameInput.PlayerInput.FastUseItemMemory.TryStartForItemSlot().