Terraria Decompiled: Terraria.UI.ItemSlot.OverrideLeftClick
OverrideLeftClick()
static bool Terraria.UI.ItemSlot.OverrideLeftClick (Item[] inv, int context = 0, int slot = 0) inline static private
Definition at line 437 of file ItemSlot.cs.
        {
            if (Main.LocalPlayer.tileEntityAnchor.IsInValidUseTileEntity() && ItemSlot.ShiftInUse && Main.LocalPlayer.tileEntityAnchor.GetTileEntity().PerformShiftClickAction(inv, context, slot))
            {
                return true;
            }
            Item item = inv[slot];
            if (Main.cursorOverride == 2)
            {
                if (ChatManager.AddChatText(FontAssets.MouseText.Value, ItemTagHandler.GenerateTag(item), Vector2.One))
                {
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
                return true;
            }
            if (Main.cursorOverride == 3)
            {
                if (!ItemSlot.canFavoriteAt[context])
                {
                    return false;
                }
                item.favorited = !item.favorited;
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                return true;
            }
            else
            {
                if (Main.cursorOverride == 6)
                {
                    Item item2 = item.DeepClone();
                    if (!(ItemSlot.TryResearchingItem(ref item2, true) | ItemSlot.TryResearchingItem(ref Main.LocalPlayer.trashItem, false)))
                    {
                        SoundEngine.PlaySound(SoundID.TrashItem, -1, -1, 0f, 1f);
                    }
                    SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                    Main.LocalPlayer.trashItem = item.Clone();
                    ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(Main.LocalPlayer.trashItem, context, 6, 0));
                    item.TurnToAir(false);
                    if (context == 3 && Main.netMode == 1)
                    {
                        NetMessage.SendData(32, -1, -1, null, Main.LocalPlayer.chest, (float)slot, 0f, 0f, 0, 0, 0);
                    }
                    CoinSlot.ForceSlotState(slot, context, inv[slot]);
                    return true;
                }
                if (Main.cursorOverride == 7)
                {
                    if (context == 29)
                    {
                        Item item3 = new Item();
                        item3.SetDefaults(inv[slot].type, null);
                        item3.stack = (item3.OnlyNeedOneInInventory() ? 1 : item3.maxStack);
                        item3.OnCreated(new JourneyDuplicationItemCreationContext());
                        Player.GetItemLogger.Start();
                        item3 = Main.LocalPlayer.GetItem(item3, GetItemSettings.QuickTransferFromSlot);
                        Player.GetItemLogger.Stop();
                        ItemSlot.DisplayTransfer_GetItem(inv, context, slot);
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        return true;
                    }
                    Player.GetItemLogger.Start();
                    inv[slot] = Main.LocalPlayer.GetItem(inv[slot], GetItemSettings.QuickTransferFromSlot);
                    Player.GetItemLogger.Stop();
                    ItemSlot.DisplayTransfer_GetItem(inv, context, slot);
                    CoinSlot.ForceSlotState(slot, context, inv[slot]);
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    return true;
                }
                else
                {
                    if (Main.cursorOverride == 8)
                    {
                        Player.GetItemLogger.Start();
                        inv[slot] = Main.LocalPlayer.GetItem(inv[slot], GetItemSettings.QuickTransferFromSlot);
                        Player.GetItemLogger.Stop();
                        ItemSlot.DisplayTransfer_GetItem(inv, context, slot);
                        if (Main.player[Main.myPlayer].chest > -1)
{
                            NetMessage.SendData(32, -1, -1, null, Main.player[Main.myPlayer].chest, (float)slot, 0f, 0f, 0, 0, 0);
                        }
                        CoinSlot.ForceSlotState(slot, context, inv[slot]);
                        return true;
                    }
                    if (Main.cursorOverride == 9)
                    {
                        if (Main.CreativeMenu.IsShowingResearchMenu())
{
                            Main.CreativeMenu.SwapItem(ref inv[slot]);
                            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                            Main.CreativeMenu.SacrificeItemInSacrificeSlot();
                        }
                        else if (Main.InReforgeMenu)
{
                            if (item.stack <= 1)
{
                                Utils.Swap<Item>(ref inv[slot], ref Main.reforgeItem);
                                ItemSlot.DisplayTransfer_TwoWay(inv, slot, context, Main.reforgeItem, 5);
                                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                            }
                            else if (Main.reforgeItem.IsAir)
{
                                Main.reforgeItem = item.Clone();
                                Main.reforgeItem.stack = 1;
                                item.stack--;
                                ItemSlot.DisplayTransfer_TwoWay(inv, slot, context, Main.reforgeItem, 5);
                                SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                            }
                        }
                        else if (Main.InGuideCraftMenu)
{
                            Utils.Swap<Item>(ref inv[slot], ref Main.guideItem);
                            ItemSlot.DisplayTransfer_TwoWay(inv, slot, context, Main.guideItem, 7);
                            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        }
                        else
{
                            ChestUI.TryPlacingInChest(inv, slot, false, context);
                        }
                        return true;
                    }
                    if (Main.cursorOverride == 10)
                    {
                        Chest chest = Main.instance.shop[Main.npcShop];
                        if (Main.LocalPlayer.SellItem(item, -1))
{
                            chest.AddItemToShop(item);
                            ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(item, context, 15, 0));
                            item.TurnToAir(false);
                            SoundEngine.PlaySound(18, -1, -1, 1, 1f, 0f);
                        }
                        else if (item.value == 0)
{
                            chest.AddItemToShop(item);
                            ItemSlot.AnnounceTransfer(new ItemSlot.ItemTransferInfo(item, context, 15, 0));
                            item.TurnToAir(false);
                            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
                        }
                        return true;
                    }
                    return false;
                }
            }
        }
References Terraria.UI.Chat.ChatManager.AddChatText(), Terraria.Chest.AddItemToShop(), Terraria.UI.ItemSlot.AnnounceTransfer(), Terraria.UI.ItemSlot.canFavoriteAt, Terraria.Player.chest, Terraria.Main.CreativeMenu, Terraria.Main.cursorOverride, Terraria.Item.DeepClone(), Terraria.UI.ItemSlot.DisplayTransfer_GetItem(), Terraria.UI.ItemSlot.DisplayTransfer_TwoWay(), Terraria.UI.CoinSlot.ForceSlotState(), Terraria.GameContent.UI.Chat.ItemTagHandler.GenerateTag(), Terraria.Player.GetItem(), Terraria.Player.GetItemLogger, Terraria.DataStructures.PlayerInteractionAnchor.GetTileEntity(), Terraria.Main.guideItem, Terraria.Main.InGuideCraftMenu, Terraria.Main.InReforgeMenu, Terraria.Main.instance, Terraria.Item.IsAir, Terraria.DataStructures.PlayerInteractionAnchor.IsInValidUseTileEntity(), Terraria.GameContent.Creative.CreativeUI.IsShowingResearchMenu(), System.item, Terraria.Main.LocalPlayer, Terraria.Item.maxStack, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.npcShop, Terraria.Item.OnCreated(), Microsoft.Xna.Framework.Vector2.One, Terraria.Item.OnlyNeedOneInInventory(), Terraria.DataStructures.TileEntity.PerformShiftClickAction(), Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GetItemSettings.QuickTransferFromSlot, Terraria.Main.reforgeItem, Terraria.GameContent.Creative.CreativeUI.SacrificeItemInSacrificeSlot(), Terraria.Player.SellItem(), Terraria.NetMessage.SendData(), Terraria.Item.SetDefaults(), Terraria.UI.ItemSlot.ShiftInUse, Terraria.Main.shop, Terraria.DataStructures.PlayerGetItemLogger.Start(), Terraria.DataStructures.PlayerGetItemLogger.Stop(), Terraria.GameContent.Creative.CreativeUI.SwapItem(), Terraria.Player.tileEntityAnchor, Terraria.ID.SoundID.TrashItem, Terraria.Player.trashItem, Terraria.UI.ChestUI.TryPlacingInChest(), Terraria.UI.ItemSlot.TryResearchingItem(), and ReLogic.Content.Asset< T >.Value.
Referenced by Terraria.UI.ItemSlot.HoverOverrideClick(), and Terraria.UI.ItemSlot.LeftClick().