Terraria Decompiled: Terraria.UI.ItemSlot.GetGamepadInstructions
GetGamepadInstructions() [2/3]
static string Terraria.UI.ItemSlot.GetGamepadInstructions (Item[] inv, int context = 0, int slot = 0) inline static
Definition at line 3675 of file ItemSlot.cs.
        {
            Player player = Main.player[Main.myPlayer];
            string text = "";
            if (inv == null || inv[slot] == null || Main.mouseItem == null)
            {
                return text;
            }
            if (context == 0 || context == 1 || context == 2)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        if (inv[slot].type == Main.mouseItem.type && Main.mouseItem.stack < inv[slot].maxStack && inv[slot].maxStack > 1)
{
                            text += PlayerInput.BuildCommand(Lang.misc[55].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                        }
                    }
                    else
                    {
                        if (context == 0 && player.chest == -1 && PlayerInput.AllowExecutionOfGamepadInstructions)
{
                            player.DpadRadial.ChangeBinding(slot);
                        }
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        if (inv[slot].maxStack > 1)
{
                            text += PlayerInput.BuildCommand(Lang.misc[55].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                        }
                    }
                    if (ItemID.Sets.OpenableBag[inv[slot].type])
                    {
                        text += PlayerInput.BuildCommand(Language.GetTextValue("UI.ActionOpen"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            ItemSlot.TryOpenContainer(inv, context, slot, player);
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                    else if (ItemID.Sets.HasItemSwap[inv[slot].type])
                    {
                        text += PlayerInput.BuildCommand(Language.GetTextValue("UI.ActionChangeType"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            ItemSlot.TryItemSwap(inv[slot]);
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                    else if (inv[slot].stack == 1 && inv[slot].CanBeEquipped())
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[67].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            ItemSlot.SwapEquip(inv, context, slot);
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                    text += PlayerInput.BuildCommand(Lang.misc[83].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"] });
                    if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
                    {
                        inv[slot].favorited = !inv[slot].favorited;
                        PlayerInput.LockGamepadButtons("SmartCursor");
                        PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                    }
                }
                else if (Main.mouseItem.type > 0)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
            }
            if (context == 3 || context == 4 || context == 32)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        if (inv[slot].type == Main.mouseItem.type && Main.mouseItem.stack < inv[slot].maxStack && inv[slot].maxStack > 1)
{
                            text += PlayerInput.BuildCommand(Lang.misc[55].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                        }
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        if (inv[slot].maxStack > 1)
{
                            text += PlayerInput.BuildCommand(Lang.misc[55].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                        }
                    }
                    if (inv[slot].stack == 1 && inv[slot].CanBeEquipped())
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[67].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            ItemSlot.SwapEquip(inv, context, slot);
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                    if (context == 32)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[83].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
{
                            inv[slot].favorited = !inv[slot].favorited;
                            PlayerInput.LockGamepadButtons("SmartCursor");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                }
                else if (Main.mouseItem.type > 0)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
            }
            if (context == 15)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        if (inv[slot].type == Main.mouseItem.type && Main.mouseItem.stack < inv[slot].maxStack && inv[slot].maxStack > 1)
{
                            text += PlayerInput.BuildCommand(Lang.misc[91].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"] });
                        }
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[90].Value, new List<string>[]
{
                            PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"],
                            PlayerInput.ProfileGamepadUI.KeyStatus["MouseRight"]
                        });
                    }
                }
                else if (Main.mouseItem.type > 0)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[92].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
            }
            if (context == 8 || context == 9 || context == 10 || context == 11 || context == 16 || context == 17 || context == 19 || context == 20)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        if (Main.mouseItem.stack == 1 && Main.mouseItem.CanBeEquipped())
{
                            text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        }
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                    if (context == 10)
                    {
                        bool flag = player.hideVisibleAccessory[slot];
                        text += PlayerInput.BuildCommand(Lang.misc[flag ? 77 : 78].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            player.hideVisibleAccessory[slot] = !player.hideVisibleAccessory[slot];
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                            }
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                    if ((context == 16 || context == 17 || context == 18 || context == 19 || context == 20) && slot < 2)
                    {
                        bool flag2 = player.hideMisc[slot];
                        text += PlayerInput.BuildCommand(Lang.misc[flag2 ? 77 : 78].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            if (slot == 0)
{
                                player.TogglePet();
                            }
                            if (slot == 1)
{
                                player.ToggleLight();
                            }
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                            }
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                }
                else
                {
                    if (Main.mouseItem.type > 0 && Main.mouseItem.CanBeEquipped())
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                    if (context == 10)
                    {
                        bool flag3 = player.hideVisibleAccessory[slot];
                        text += PlayerInput.BuildCommand(Lang.misc[flag3 ? 77 : 78].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            player.hideVisibleAccessory[slot] = !player.hideVisibleAccessory[slot];
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                            }
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                    if ((context == 16 || context == 17 || context == 18 || context == 19 || context == 20) && slot < 2)
                    {
                        bool flag4 = player.hideMisc[slot];
                        text += PlayerInput.BuildCommand(Lang.misc[flag4 ? 77 : 78].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                        if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                            if (slot == 0)
{
                                player.TogglePet();
                            }
                            if (slot == 1)
{
                                player.ToggleLight();
                            }
                            Main.mouseLeftRelease = false;
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            if (Main.netMode == 1)
{
                                NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                            }
                            PlayerInput.LockGamepadButtons("Grapple");
                            PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                        }
                    }
                }
            }
            if (context == 12 || context == 25 || context == 27 || context == 33)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        if (Main.mouseItem.dye > 0)
{
                            text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        }
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                    if (context == 12 || context == 25 || context == 27 || context == 33)
                    {
                        int num = -1;
                        if (inv == player.dye)
{
                            num = slot;
                        }
                        if (inv == player.miscDyes)
{
                            num = 10 + slot;
                        }
                        if (num != -1)
{
                            if (num < 10)
{
                                bool flag5 = player.hideVisibleAccessory[slot];
                                text += PlayerInput.BuildCommand(Lang.misc[flag5 ? 77 : 78].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                                    player.hideVisibleAccessory[slot] = !player.hideVisibleAccessory[slot];
                                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                                    if (Main.netMode == 1)
{
                                        NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                                    }
                                    PlayerInput.LockGamepadButtons("Grapple");
                                    PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                                }
                            }
                            else
{
                                bool flag6 = player.hideMisc[slot];
                                text += PlayerInput.BuildCommand(Lang.misc[flag6 ? 77 : 78].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
{
                                    player.hideMisc[slot] = !player.hideMisc[slot];
                                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                                    if (Main.netMode == 1)
{
                                        NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                                    }
                                    PlayerInput.LockGamepadButtons("Grapple");
                                    PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                                }
                            }
                        }
                    }
                }
                else if (Main.mouseItem.type > 0 && Main.mouseItem.dye > 0)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
                return text;
            }
            if (context == 18)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        if (Main.mouseItem.dye > 0)
{
                            text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        }
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                }
                else if (Main.mouseItem.type > 0 && Main.mouseItem.dye > 0)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
                bool enabledSuperCart = player.enabledSuperCart;
                text += PlayerInput.BuildCommand(Language.GetTextValue((!enabledSuperCart) ? "UI.EnableSuperCart" : "UI.DisableSuperCart"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["Grapple"] });
                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.Grapple)
                {
                    player.enabledSuperCart = !player.enabledSuperCart;
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                    if (Main.netMode == 1)
                    {
                        NetMessage.SendData(4, -1, -1, null, Main.myPlayer, 0f, 0f, 0f, 0, 0, 0);
                    }
                    PlayerInput.LockGamepadButtons("Grapple");
                    PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                }
                return text;
            }
            if (context == 6)
            {
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[74].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                }
                else if (Main.mouseItem.type > 0)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[74].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
                return text;
            }
            if (context == 5 || context == 7)
            {
                bool flag7 = false;
                if (context == 5)
                {
                    flag7 = Main.mouseItem.CanHavePrefixes() || Main.mouseItem.type == 0;
                }
                if (context == 7)
                {
                    flag7 = Main.mouseItem.material;
                }
                if (inv[slot].type > 0 && inv[slot].stack > 0)
                {
                    if (Main.mouseItem.type > 0)
                    {
                        if (flag7)
{
                            text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                        }
                    }
                    else
                    {
                        text += PlayerInput.BuildCommand(Lang.misc[54].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                    }
                }
                else if (Main.mouseItem.type > 0 && flag7)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[65].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["MouseLeft"] });
                }
            }
            if (!Main.mouseItem.IsAir)
            {
                if (ItemSlot.canQuickDropAt[context])
                {
                    text += PlayerInput.BuildCommand(Lang.inter[121].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"] });
                    if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
                    {
                        player.DropSelectedItem();
                        PlayerInput.LockGamepadButtons("SmartSelect");
                        PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                    }
                }
                else if (player.ItemSpace(Main.mouseItem).CanTakeItemToPersonalInventory)
                {
                    text += PlayerInput.BuildCommand(Lang.misc[76].Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"] });
                    if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
                    {
                        Main.mouseItem = player.GetItem(Main.mouseItem, GetItemSettings.ReturnItemShowAsNew);
                        PlayerInput.LockGamepadButtons("SmartSelect");
                        PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                    }
                }
            }
            else if (context == 22 || context == 42 || context == 43 || context == 41)
            {
                bool flag8 = Player.Settings.CraftingGridControl == Player.Settings.CraftingGridMode.Classic;
                text += PlayerInput.BuildCommand(Language.GetTextValue(CraftingUI.CraftingWindowTextKey), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"] });
                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
                {
                    if (flag8)
                    {
                        NewCraftingUI.Close(true, true);
                        if (UILinkPointNavigator.CurrentPage == 10)
{
                            UILinkPointNavigator.ChangePage(9);
                        }
                        else
{
                            UILinkPointNavigator.ChangePage(10);
                        }
                    }
                    else
                    {
                        NewCraftingUI.ToggleInInventory(false);
                    }
                }
                if (!Main.InGuideCraftMenu && Main.bannerUI.AnyAvailableBanners && context == 22)
                {
                    text += PlayerInput.BuildCommand(Language.GetTextValue("UI.CyclePipsToBanners"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"] });
                    if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
                    {
                        Main.TryChangePipsPage(Main.PipPage.Banners);
                        UILinkPointNavigator.ChangePage(22);
                        PlayerInput.LockGamepadButtons("SmartSelect");
                    }
                }
            }
            else if (context == 35)
            {
                text += PlayerInput.BuildCommand(Language.GetTextValue("GameUI.BannersWindow"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartCursor"] });
                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartCursor)
                {
                    if (UILinkPointNavigator.CurrentPage == 23)
                    {
                        UILinkPointNavigator.ChangePage(22);
                    }
                    else
                    {
                        UILinkPointNavigator.ChangePage(23);
                    }
                }
                text += PlayerInput.BuildCommand(Language.GetTextValue("UI.CyclePipsToCrafting"), new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"] });
                if (ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
                {
                    Main.TryChangePipsPage(Main.PipPage.Recipes);
                    UILinkPointNavigator.ChangePage(9);
                    PlayerInput.LockGamepadButtons("SmartSelect");
                }
            }
            else
            {
                ItemSlot.ShiftForcedOn = true;
                ItemSlot.AlternateClickAction? alternateClickAction = ItemSlot.GetAlternateClickAction(inv, context, slot);
                if (alternateClickAction != null)
                {
                    text += PlayerInput.BuildCommand(alternateClickAction.Value.gamepadHintText.Value, new List<string>[] { PlayerInput.ProfileGamepadUI.KeyStatus["SmartSelect"] });
                    if (ItemSlot.CanDoSimulatedClickAction() && ItemSlot.CanExecuteCommand() && PlayerInput.Triggers.JustPressed.SmartSelect)
                    {
                        bool mouseLeft = Main.mouseLeft;
                        int cursorOverride = Main.cursorOverride;
                        Main.mouseLeft = true;
                        Main.cursorOverride = alternateClickAction.Value.cursorOverride;
                        ItemSlot.LeftClick(inv, context, slot);
                        Main.cursorOverride = cursorOverride;
                        Main.mouseLeft = mouseLeft;
                        PlayerInput.LockGamepadButtons("SmartSelect");
                        PlayerInput.SettingsForUI.TryRevertingToMouseMode();
                    }
                }
                ItemSlot.ShiftForcedOn = false;
            }
            if (!ItemSlot.TryEnteringFastUseMode(inv, context, slot, player, ref text))
            {
                ItemSlot.TryEnteringBuildingMode(inv, context, slot, player, ref text);
            }
            return text;
        }
References Terraria.GameInput.PlayerInput.AllowExecutionOfGamepadInstructions, Terraria.GameInput.PlayerInput.BuildCommand(), Terraria.Item.CanBeEquipped(), Terraria.UI.ItemSlot.CanExecuteCommand(), Terraria.Player.chest, Terraria.Player.DpadRadial, Terraria.Item.favorited, Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.TriggersSet.Grapple, Terraria.ID.ItemID.Sets.HasItemSwap, Terraria.Player.hideMisc, Terraria.Player.hideVisibleAccessory, Terraria.GameInput.TriggersPack.JustPressed, Terraria.GameInput.KeyConfiguration.KeyStatus, Terraria.GameInput.PlayerInput.LockGamepadButtons(), Terraria.Item.maxStack, Terraria.Lang.misc, Terraria.Main.mouseItem, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.ID.ItemID.Sets.OpenableBag, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameInput.PlayerInput.ProfileGamepadUI, Terraria.NetMessage.SendData(), Terraria.GameInput.TriggersSet.SmartCursor, System.stack, Terraria.Item.stack, Terraria.UI.ItemSlot.SwapEquip(), System.text, Terraria.Player.ToggleLight(), Terraria.Player.TogglePet(), Terraria.GameInput.PlayerInput.Triggers, Terraria.UI.ItemSlot.TryItemSwap(), Terraria.UI.ItemSlot.TryOpenContainer(), Terraria.GameInput.PlayerInput.SettingsForUI.TryRevertingToMouseMode(), Terraria.Item.type, and Terraria.Localization.LocalizedText.Value.