Terraria Decompiled: Terraria.UI.ItemSlot.ArmorSwap
ArmorSwap()
static Item Terraria.UI.ItemSlot.ArmorSwap (Item item, out bool success, out int targetSlot) inline static private
Definition at line 3265 of file ItemSlot.cs.
        {
            targetSlot = -1;
            success = false;
            if (item.stack < 1)
            {
                return item;
            }
            if (item.headSlot == -1 && item.bodySlot == -1 && item.legSlot == -1 && !item.accessory)
            {
                return item;
            }
            Player player = Main.player[Main.myPlayer];
            int num = (item.vanity ? 10 : 0);
            if (item.headSlot != -1 || item.bodySlot != -1 || item.legSlot != -1)
            {
                if (ItemSlot.HasSameItemInSlot(item, new ArraySegment<Item>(Main.LocalPlayer.armor, 0, 3)) || ItemSlot.HasSameItemInSlot(item, new ArraySegment<Item>(Main.LocalPlayer.armor, 10, 3)))
                {
                    return item;
                }
            }
            else if (item.accessory && (item.vanity ? ItemSlot.HasSameItemInSlot(item, new ArraySegment<Item>(player.armor, 3, 7)) : ItemSlot.HasSameItemInSlot(item, new ArraySegment<Item>(player.armor, 13, 7))))
            {
                return item;
            }
            if (item.headSlot != -1)
            {
                targetSlot = num;
            }
            else if (item.bodySlot != -1)
            {
                targetSlot = num + 1;
            }
            else if (item.legSlot != -1)
            {
                targetSlot = num + 2;
            }
            else if (item.accessory)
            {
                ArraySegment<Item> arraySegment = new ArraySegment<Item>(player.armor, 3 + num, 7);
                if (ItemSlot.HasIncompatibleAccessory(item, arraySegment, out targetSlot))
                {
                    if (!player.IsItemSlotUnlockedAndUsable(targetSlot))
                    {
                        return item;
                    }
                }
                else
                {
                    targetSlot = arraySegment.Offset;
                    for (int i = 0; i < arraySegment.Count; i++)
                    {
                        int num2 = i + arraySegment.Offset;
                        if (player.IsItemSlotUnlockedAndUsable(num2) && arraySegment.Array[num2].IsAir)
{
                            targetSlot = num2;
                            break;
                        }
                    }
                }
            }
            if (targetSlot == -1)
            {
                return item;
            }
            item.favorited = false;
            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
            Utils.Swap<Item>(ref item, ref player.armor[targetSlot]);
            success = true;
            return item;
        }
References Terraria.Player.armor, System.ArraySegment< T >.Array, System.ArraySegment< T >.Count, Terraria.UI.ItemSlot.HasIncompatibleAccessory(), Terraria.UI.ItemSlot.HasSameItemInSlot(), Terraria.Player.IsItemSlotUnlockedAndUsable(), System.item, Terraria.Main.LocalPlayer, Terraria.Main.myPlayer, System.ArraySegment< T >.Offset, Terraria.Main.player, and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.UI.ItemSlot.SwapEquip().