Terraria Decompiled: Terraria.UI.ItemSlot.PickItemMovementAction
PickItemMovementAction()
static int Terraria.UI.ItemSlot.PickItemMovementAction (Item[] inv, int context, int slot, Item checkItem) inline static
Definition at line 1131 of file ItemSlot.cs.
        {
            Player player = Main.player[Main.myPlayer];
            int num = -1;
            if (context == 0)
            {
                num = 0;
            }
            else if (context == 1)
            {
                if (checkItem.type == 0 || checkItem.type == 71 || checkItem.type == 72 || checkItem.type == 73 || checkItem.type == 74)
                {
                    num = 0;
                }
            }
            else if (context == 2)
            {
                if (checkItem.FitsAmmoSlot())
                {
                    num = 0;
                }
            }
            else if (context == 3)
            {
                num = 0;
            }
            else if (context == 4 || context == 32)
            {
                Item[] item = Main.LocalPlayer.GetCurrentContainer().item;
                if (!ChestUI.IsBlockedFromTransferIntoChest(checkItem, item))
                {
                    num = 0;
                }
            }
            else if (context == 5)
            {
                if (checkItem.CanHavePrefixes() || checkItem.type == 0)
                {
                    num = 1;
                }
            }
            else if (context == 6)
            {
                num = 0;
            }
            else if (context == 7)
            {
                if (checkItem.material || checkItem.type == 0)
                {
                    num = 0;
                }
            }
            else if (context == 8)
            {
                if ((ItemID.Sets.DualEquipArmor[checkItem.type] || !ItemSlot.HasSameItemInSlot(checkItem, new ArraySegment<Item>(Main.LocalPlayer.armor, 10, 3))) && Main.LocalPlayer.armor[slot].type != checkItem.type && (checkItem.type == 0 || (checkItem.headSlot > -1 && slot == 0) || (checkItem.bodySlot > -1 && slot == 1) || (checkItem.legSlot > -1 && slot == 2)))
                {
                    num = 1;
                }
            }
            else if (context == 23)
            {
                if (checkItem.type == 0 || (checkItem.headSlot > 0 && slot == 0) || (checkItem.bodySlot > 0 && slot == 1) || (checkItem.legSlot > 0 && slot == 2))
                {
                    num = 1;
                }
            }
            else if (context == 26)
            {
                if (checkItem.type == 0 || checkItem.headSlot > 0)
                {
                    num = 1;
                }
            }
            else if (context == 9)
            {
                if ((ItemID.Sets.DualEquipArmor[checkItem.type] || !ItemSlot.HasSameItemInSlot(checkItem, new ArraySegment<Item>(Main.LocalPlayer.armor, 0, 3))) && Main.LocalPlayer.armor[slot].type != checkItem.type && (checkItem.type == 0 || (checkItem.headSlot > -1 && slot == 10) || (checkItem.bodySlot > -1 && slot == 11) || (checkItem.legSlot > -1 && slot == 12)))
                {
                    num = 1;
                }
            }
            else if (context == 10)
            {
                if (checkItem.type == 0 || ItemSlot.CanEquipAccessoryInSlot(checkItem, slot))
                {
                    num = 1;
                }
            }
            else if (context == 24)
            {
                if (checkItem.type == 0 || (checkItem.accessory && ItemSlot.CanEquipAccessoryInSlot(checkItem, new ArraySegment<Item>(inv, 3, 5), slot)))
                {
                    num = 1;
                }
            }
            else if (context == 11)
            {
                if (checkItem.type == 0 || ItemSlot.CanEquipAccessoryInVanitySlot(checkItem, slot))
                {
                    num = 1;
                }
            }
            else if (context == 12 || context == 25 || context == 27 || context == 33)
            {
                num = 2;
            }
            else if (context == 15)
            {
                if (checkItem.type == 0 && inv[slot].type > 0)
                {
                    num = 3;
                }
                else if (checkItem.type == inv[slot].type && checkItem.type > 0 && checkItem.stack < checkItem.maxStack && inv[slot].stack > 0)
                {
                    num = 3;
                }
                else if (inv[slot].type == 0 && checkItem.type > 0 && (checkItem.type < 71 || checkItem.type > 74))
                {
                    num = 4;
                }
            }
            else if (context == 16)
            {
                if (checkItem.type == 0 || Main.projHook[checkItem.shoot])
                {
                    num = 1;
                }
            }
            else if (context == 17)
            {
                if (checkItem.type == 0 || (checkItem.mountType != -1 && !MountID.Sets.Cart[checkItem.mountType]))
                {
                    num = 1;
                }
            }
            else if (context == 39)
            {
                if (checkItem.type == 0 || checkItem.mountType != -1)
                {
                    num = 1;
                }
            }
            else if (context == 38)
            {
                if (checkItem.type == 0 || TEDisplayDoll.AcceptedInWeaponSlot(checkItem))
                {
                    num = 1;
                }
            }
            else if (context == 19)
            {
                if (checkItem.type == 0 || (checkItem.buffType > 0 && Main.vanityPet[checkItem.buffType] && !Main.lightPet[checkItem.buffType]))
                {
                    num = 1;
                }
            }
            else if (context == 18)
            {
                if (checkItem.type == 0 || (checkItem.mountType != -1 && MountID.Sets.Cart[checkItem.mountType]))
                {
                    num = 1;
                }
            }
            else if (context == 20)
            {
                if (checkItem.type == 0 || (checkItem.buffType > 0 && Main.lightPet[checkItem.buffType]))
                {
                    num = 1;
                }
            }
            else if (context == 29 && checkItem.type == 0 && inv[slot].type > 0)
            {
                num = 5;
            }
            if (context == 30)
            {
                num = 0;
            }
            return num;
        }
References Terraria.GameContent.Tile_Entities.TEDisplayDoll.AcceptedInWeaponSlot(), Terraria.Item.accessory, Terraria.Player.armor, Terraria.Item.bodySlot, Terraria.Item.buffType, Terraria.UI.ItemSlot.CanEquipAccessoryInSlot(), Terraria.UI.ItemSlot.CanEquipAccessoryInVanitySlot(), Terraria.Item.CanHavePrefixes(), Terraria.ID.MountID.Sets.Cart, Terraria.ID.ItemID.Sets.DualEquipArmor, Terraria.Item.FitsAmmoSlot(), Terraria.Player.GetCurrentContainer(), Terraria.UI.ItemSlot.HasSameItemInSlot(), Terraria.Item.headSlot, Terraria.UI.ChestUI.IsBlockedFromTransferIntoChest(), System.item, Terraria.Chest.item, Terraria.Item.legSlot, Terraria.Main.lightPet, Terraria.Main.LocalPlayer, Terraria.Item.material, Terraria.Item.maxStack, Terraria.Item.mountType, Terraria.Main.myPlayer, Terraria.Main.player, Terraria.Main.projHook, Terraria.Item.shoot, Terraria.Item.stack, Terraria.Item.type, and Terraria.Main.vanityPet.
Referenced by Terraria.UI.ItemSlot.LeftClick(), and Terraria.UI.ChestUI.Restock().