Terraria Decompiled: Terraria.UI.ItemSlot.TryItemSwap
TryItemSwap()
static void Terraria.UI.ItemSlot.TryItemSwap (Item item) inline static private
Definition at line 1584 of file ItemSlot.cs.
        {
            int type = item.type;
            if (type > 5309)
            {
                if (type <= 5391)
                {
                    switch (type)
                    {
                    case 5323:
                        break;
                    case 5324:
                        item.ChangeItemType(5329);
                        ItemSlot.AfterItemSwap(type, item.type);
                        return;
                    case 5325:
                        goto IL_00E8;
                    case 5326:
                    case 5327:
                    case 5328:
                        return;
                    case 5329:
                        item.ChangeItemType(5330);
                        ItemSlot.AfterItemSwap(type, item.type);
                        return;
                    case 5330:
                        item.ChangeItemType(5324);
                        ItemSlot.AfterItemSwap(type, item.type);
                        return;
                    default:
                        switch (type)
{
                        case 5358:
                            item.ChangeItemType(5360);
                            ItemSlot.AfterItemSwap(type, item.type);
                            return;
                        case 5359:
                            item.ChangeItemType(5358);
                            ItemSlot.AfterItemSwap(type, item.type);
                            return;
                        case 5360:
                            item.ChangeItemType(5361);
                            ItemSlot.AfterItemSwap(type, item.type);
                            return;
                        case 5361:
                            item.ChangeItemType(5359);
                            ItemSlot.AfterItemSwap(type, item.type);
                            return;
                        default:
                            if (type != 5391)
{
                                return;
                            }
                            goto IL_0188;
                        }
                        break;
                    }
                }
                else
                {
                    if (type == 5437)
                    {
                        item.ChangeItemType(5358);
                        ItemSlot.AfterItemSwap(type, item.type);
                        return;
                    }
                    switch (type)
                    {
                    case 5453:
                        goto IL_01E0;
                    case 5454:
                        goto IL_020C;
                    case 5455:
                        break;
                    default:
                        if (type != 5526)
{
                            return;
                        }
                        goto IL_02B0;
                    }
                }
                item.ChangeItemType((item.type == 5323) ? 5455 : 5323);
                ItemSlot.AfterItemSwap(type, item.type);
                return;
            }
            if (type <= 4346)
            {
                if (type == 2611)
                {
                    goto IL_02B0;
                }
                if (type != 4131)
                {
                    if (type != 4346)
                    {
                        return;
                    }
                    goto IL_0188;
                }
            }
            else
            {
                if (type == 4767)
                {
                    goto IL_01E0;
                }
                if (type - 5059 <= 1)
                {
                    item.ChangeItemType((item.type == 5059) ? 5060 : 5059);
                    ItemSlot.AfterItemSwap(type, item.type);
                    return;
                }
                if (type != 5309)
                {
                    return;
                }
                goto IL_020C;
            }
            IL_00E8:
            item.ChangeItemType((item.type == 5325) ? 4131 : 5325);
            ItemSlot.AfterItemSwap(type, item.type);
            return;
            IL_0188:
            item.ChangeItemType((item.type == 4346) ? 5391 : 4346);
            ItemSlot.AfterItemSwap(type, item.type);
            return;
            IL_01E0:
            item.ChangeItemType((item.type == 4767) ? 5453 : 4767);
            ItemSlot.AfterItemSwap(type, item.type);
            return;
            IL_020C:
            item.ChangeItemType((item.type == 5309) ? 5454 : 5309);
            ItemSlot.AfterItemSwap(type, item.type);
            return;
            IL_02B0:
            item.ChangeItemType((item.type == 2611) ? 5526 : 2611);
            ItemSlot.AfterItemSwap(type, item.type);
        }
References Terraria.UI.ItemSlot.AfterItemSwap(), and System.item.
Referenced by Terraria.UI.ItemSlot.GetGamepadInstructions(), and Terraria.UI.ItemSlot.RightClick().