Terraria Decompiled: Terraria.UI.ItemSlot.SwapVanityEquip
SwapVanityEquip()
static void Terraria.UI.ItemSlot.SwapVanityEquip (Item[] inv, int context, int slot, Player player) inline static private
Definition at line 1537 of file ItemSlot.cs.
        {
            if (Main.npcShop > 0)
            {
                return;
            }
            Item item = inv[slot - 10];
            if (inv[slot].IsAir && item.IsAir)
            {
                return;
            }
            if (context == 11)
            {
                if (!inv[slot].IsAir && !ItemSlot.CanEquipAccessoryInSlot(inv[slot], new ArraySegment<Item>(Main.LocalPlayer.armor, 3, 7), slot - 10))
                {
                    return;
                }
                if (!item.IsAir && !ItemSlot.CanEquipAccessoryInSlot(item, new ArraySegment<Item>(Main.LocalPlayer.armor, 13, 7), slot))
                {
                    return;
                }
            }
            Utils.Swap<Item>(ref inv[slot], ref inv[slot - 10]);
            SoundEngine.PlaySound(7, -1, -1, 1, 1f, 0f);
            if (inv[slot].stack > 0)
            {
                if (context <= 12)
                {
                    if (context == 0)
                    {
                        AchievementsHelper.NotifyItemPickup(player, inv[slot]);
                        return;
                    }
                    if (context - 8 > 4)
                    {
                        return;
                    }
                }
                else if (context - 16 > 1 && context != 33)
                {
                    return;
                }
                AchievementsHelper.HandleOnEquip(player, inv[slot], context);
            }
        }
References Terraria.Player.armor, Terraria.UI.ItemSlot.CanEquipAccessoryInSlot(), Terraria.GameContent.Achievements.AchievementsHelper.HandleOnEquip(), Terraria.Item.IsAir, System.item, Terraria.Main.LocalPlayer, Terraria.GameContent.Achievements.AchievementsHelper.NotifyItemPickup(), Terraria.Main.npcShop, Terraria.Audio.SoundEngine.PlaySound(), and System.stack.
Referenced by Terraria.UI.ItemSlot.RightClick().