Terraria Decompiled: Mono.RuntimeGenericParamInfoHandle.GetConstraints
GetConstraints()
unsafe Type[] Mono.RuntimeGenericParamInfoHandle.GetConstraints () inline private
Definition at line 42 of file RuntimeGenericParamInfoHandle.cs.
        {
            int constraintsCount = this.GetConstraintsCount();
            Type[] array = new Type[constraintsCount];
            for (int i = 0; i < constraintsCount; i++)
            {
                RuntimeClassHandle runtimeClassHandle = new RuntimeClassHandle(*(IntPtr*)(this.value->constraints + (IntPtr)i * (IntPtr)sizeof(RuntimeStructs.MonoClass*) / (IntPtr)sizeof(RuntimeStructs.MonoClass*)));
                array[i] = Type.GetTypeFromHandle(runtimeClassHandle.GetTypeHandle());
            }
            return array;
        }
References System.array, Mono.RuntimeGenericParamInfoHandle.GetConstraintsCount(), System.Type.GetTypeFromHandle(), Mono.RuntimeClassHandle.GetTypeHandle(), and Mono.RuntimeGenericParamInfoHandle.value.