Terraria Decompiled: Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.FillPotentialTargetTiles
FillPotentialTargetTiles()
void Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.FillPotentialTargetTiles (SmartInteractScanSettings settings) inline private
Definition at line 597 of file TileSmartInteractCandidateProvider.cs.
        {
            for (int i = settings.LX; i <= settings.HX; i++)
            {
                for (int j = settings.LY; j <= settings.HY; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile != null && tile.active())
                    {
                        if (TileID.Sets.Campfires[(int)tile.type])
{
                            this.targets.Add(new Tuple<int, int>(i, j));
                        }
                        else if (Recipe.TileUsedInRecipes[(int)tile.type])
{
                            this.targets.Add(new Tuple<int, int>(i, j));
                        }
                        else if (TileID.Sets.CountsAsWaterForCrafting[(int)tile.type])
{
                            this.targets.Add(new Tuple<int, int>(i, j));
                        }
                        else
{
                            ushort type = tile.type;
                            if (type <= 338)
{
                                if (type <= 125)
{
                                    if (type <= 79)
{
                                        if (type <= 21)
{
                                            if (type - 10 > 1)
{
                                                if (type == 15)
{
                                                    goto IL_039E;
                                                }
                                                if (type != 21)
{
                                                    goto IL_046A;
                                                }
                                            }
                                        }
                                        else if (type != 29 && type != 55 && type != 79)
{
                                            goto IL_046A;
                                        }
                                    }
                                    else if (type <= 97)
{
                                        if (type != 85 && type - 88 > 1 && type != 97)
{
                                            goto IL_046A;
                                        }
                                    }
                                    else if (type != 102 && type != 104 && type != 125)
{
                                        goto IL_046A;
                                    }
                                }
                                else if (type <= 209)
{
                                    if (type <= 139)
{
                                        if (type != 132 && type != 136 && type != 139)
{
                                            goto IL_046A;
                                        }
                                    }
                                    else if (type != 144 && type != 207 && type != 209)
{
                                        goto IL_046A;
                                    }
                                }
                                else if (type <= 237)
{
                                    if (type != 212)
{
                                        if (type != 216)
{
                                            if (type != 237)
{
                                                goto IL_046A;
                                            }
                                            if (settings.player.HasItem(1293))
{
                                                this.targets.Add(new Tuple<int, int>(i, j));
                                                goto IL_046A;
                                            }
                                            goto IL_046A;
                                        }
                                    }
                                    else
{
                                        if (settings.player.HasItem(949))
{
                                            this.targets.Add(new Tuple<int, int>(i, j));
                                            goto IL_046A;
                                        }
                                        goto IL_046A;
                                    }
                                }
                                else if (type != 287 && type != 335 && type != 338)
{
                                    goto IL_046A;
                                }
                            }
                            else if (type <= 487)
{
                                if (type <= 425)
{
                                    if (type <= 377)
{
                                        if (type != 354)
{
                                            if (type != 356)
{
                                                if (type != 377)
{
                                                    goto IL_046A;
                                                }
                                            }
                                            else
{
                                                if (!Main.fastForwardTimeToDawn && (Main.netMode == 1 || Main.sundialCooldown == 0))
{
                                                    this.targets.Add(new Tuple<int, int>(i, j));
                                                    goto IL_046A;
                                                }
                                                goto IL_046A;
                                            }
                                        }
                                    }
                                    else if (type - 386 > 3 && type - 410 > 1 && type != 425)
{
                                        goto IL_046A;
                                    }
                                }
                                else if (type <= 470)
{
                                    if (type != 441 && type != 455)
{
                                        switch (type)
{
                                        case 463:
                                        case 464:
                                        case 467:
                                        case 468:
                                        case 470:
                                            break;
                                        case 465:
                                        case 466:
                                        case 469:
                                            goto IL_046A;
                                        default:
                                            goto IL_046A;
                                        }
                                    }
                                }
                                else if (type != 475 && type != 480 && type != 487)
{
                                    goto IL_046A;
                                }
                            }
                            else if (type <= 597)
{
                                if (type <= 497)
{
                                    if (type != 491 && type != 494)
{
                                        if (type != 497)
{
                                            goto IL_046A;
                                        }
                                        goto IL_039E;
                                    }
                                }
                                else if (type - 509 > 2 && type != 573 && type != 597)
{
                                    goto IL_046A;
                                }
                            }
                            else if (type <= 663)
{
                                if (type != 621 && type - 657 > 1)
{
                                    if (type != 663)
{
                                        goto IL_046A;
                                    }
                                    if (!Main.fastForwardTimeToDusk && (Main.netMode == 1 || Main.moondialCooldown == 0))
{
                                        this.targets.Add(new Tuple<int, int>(i, j));
                                        goto IL_046A;
                                    }
                                    goto IL_046A;
                                }
                            }
                            else if (type <= 721)
{
                                if (type != 699 && type - 720 > 1)
{
                                    goto IL_046A;
                                }
                            }
                            else if (type != 725 && type != 733)
{
                                goto IL_046A;
                            }
                            this.targets.Add(new Tuple<int, int>(i, j));
                            goto IL_046A;
                            IL_039E:
                            if (settings.player.IsWithinSnappngRangeToTile(i, j, 40))
{
                                this.targets.Add(new Tuple<int, int>(i, j));
                            }
                        }
                    }
                    IL_046A:;
                }
            }
        }
References Terraria.Tile.active(), System.Collections.Generic.List< T >.Add(), Terraria.ID.TileID.Sets.Campfires, Terraria.ID.TileID.Sets.CountsAsWaterForCrafting, Terraria.Main.fastForwardTimeToDawn, Terraria.Main.fastForwardTimeToDusk, Terraria.Player.HasItem(), Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.HX, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.HY, Terraria.Player.IsWithinSnappngRangeToTile(), Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.LX, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.LY, Terraria.Main.moondialCooldown, Terraria.Main.netMode, Terraria.GameContent.ObjectInteractions.SmartInteractScanSettings.player, Terraria.Main.sundialCooldown, Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.targets, Terraria.Main.tile, Terraria.Recipe.TileUsedInRecipes, and Terraria.Tile.type.
Referenced by Terraria.GameContent.ObjectInteractions.TileSmartInteractCandidateProvider.ProvideCandidate().