Terraria Decompiled: Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryGetReachableTile
TryGetReachableTile()
bool Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryGetReachableTile (int startX, out Point16 tile) inline private
Definition at line 224 of file JumperLeashedCritter.cs.
        {
            tile = Point16.Zero;
            int num = Math.Sign((int)base.AnchorPosition.X - startX);
            if (num == 0)
            {
                return false;
            }
            for (int num2 = startX; num2 != (int)base.AnchorPosition.X; num2 += num)
            {
                tile = new Point16(num2, (int)base.AnchorPosition.Y);
                if (WorldGen.SolidTile2(tile))
                {
                    float num3 = this.maxJumpHeight / 16f;
                    int num4 = 0;
                    while ((float)num4 < num3)
                    {
                        tile.Y -= 1;
                        if (!WorldGen.SolidTile2(tile))
{
                            return true;
                        }
                        num4++;
                    }
                }
                else
                {
                    for (int i = 0; i < this.strayingRangeInBlocks; i++)
                    {
                        tile.Y += 1;
                        if (WorldGen.SolidTile2(tile) || (this.canStandOnWater && WorldGen.AnyLiquidAt((int)tile.X, (int)tile.Y, 0)))
{
                            tile.Y -= 1;
                            return true;
                        }
                    }
                }
            }
            return false;
        }
References Terraria.WorldGen.AnyLiquidAt(), int, System.Math.Sign(), Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntities.LeashedCritter.strayingRangeInBlocks, and Terraria.DataStructures.Point16.Zero.
Referenced by Terraria.GameContent.LeashedEntities.JumperLeashedCritter.PickNewTarget().