Terraria Decompiled: Terraria.GameContent.LeashedEntities.JumperLeashedCritter.PickNewTarget
PickNewTarget()
void Terraria.GameContent.LeashedEntities.JumperLeashedCritter.PickNewTarget () inline private
Definition at line 186 of file JumperLeashedCritter.cs.
        {
            int num = (int)(this.maxJumpWidth / 16f);
            int num2 = (int)(this.minJumpWidth / 16f);
            int num3 = (int)this.TargetPosition.X - ((int)base.AnchorPosition.X - this.strayingRangeInBlocks);
            int num4 = (int)base.AnchorPosition.X + this.strayingRangeInBlocks - (int)this.TargetPosition.X;
            bool flag = num3 >= num2;
            bool flag2 = num4 >= num2;
            if (!flag && !flag2)
            {
                return;
            }
            int num5;
            if (flag && flag2)
            {
                num5 = this.rand.Next(2) * 2 - 1;
            }
            else
            {
                num5 = (flag ? (-1) : 1);
            }
            int num6 = ((num5 < 1) ? num3 : num4);
            int num7 = this.rand.Next(1, num6 / num + 1);
            int num8 = num6 % num;
            if (num8 < num2)
            {
                num8 = 0;
            }
            int num9 = (int)this.TargetPosition.X + (num7 * num + num8) * num5;
            Point16 point;
            if (!this.TryGetReachableTile(num9, out point))
            {
                return;
            }
            this.TargetPosition = point;
        }
References int, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.maxJumpWidth, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.minJumpWidth, Terraria.GameContent.LeashedEntities.LeashedCritter.rand, Terraria.GameContent.LeashedEntities.LeashedCritter.strayingRangeInBlocks, Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryGetReachableTile(), and Terraria.DataStructures.Point16.X.
Referenced by Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Spawn(), and Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Update().