Terraria Decompiled: Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move_NoObstruction
Move_NoObstruction()
void Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move_NoObstruction (Point currentTile, float nextY) inline private
Definition at line 159 of file JumperLeashedCritter.cs.
        {
            if (this.velocity.Y >= 0f && nextY % 16f >= 8f)
            {
                Point point = currentTile;
                point.Y++;
                if (WorldGen.SolidTile2(point) || (this.canStandOnWater && WorldGen.AnyLiquidAt(point.X, point.Y, 0)))
                {
                    base.Center = currentTile.ToWorldCoordinates(8f, 8f);
                    this.velocity = Vector2.Zero;
                    return;
                }
            }
            base.Center += this.velocity;
            this.velocity.Y = this.velocity.Y + LeashedCritter.gravity;
            if (this.velocity.Y > LeashedCritter.maxFallSpeed)
            {
                this.velocity.Y = LeashedCritter.maxFallSpeed;
            }
            if (this.State != 1 && currentTile.Y - (int)base.AnchorPosition.Y > this.strayingRangeInBlocks)
            {
                this.State = 1;
                this.WaitTime = 20;
            }
        }
References Terraria.WorldGen.AnyLiquidAt(), Terraria.GameContent.LeashedEntities.LeashedCritter.gravity, Terraria.GameContent.LeashedEntities.LeashedCritter.maxFallSpeed, Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntities.LeashedCritter.State, Terraria.GameContent.LeashedEntity.velocity, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move().