Terraria Decompiled: Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Update
Update()
override void Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Update () inline virtual
Reimplemented from Terraria.GameContent.LeashedEntity.
Definition at line 32 of file JumperLeashedCritter.cs.
        {
            base.Update();
            this.WaitTime -= 1;
            if (this.WaitTime <= 0)
            {
                byte state = this.State;
                if (state != 0)
                {
                    if (state == 1)
                    {
                        base.Recall();
                        this.PickNewTarget();
                        this.SetJumpCooldown();
                        this.State = 0;
                    }
                }
                else if (!this.TryStartJump())
                {
                    this.PickNewTarget();
                    this.SetJumpCooldown();
                }
            }
            bool flag;
            this.Move(out flag);
            if (flag && this.State != 1)
            {
                this.PickNewTarget();
                this.SetJumpCooldown();
            }
            if ((this.TargetPosition.ToWorldCoordinates(8f, 8f) - base.Center).Length() < 8f)
            {
                base.Center = this.TargetPosition.ToWorldCoordinates(8f, 8f);
                this.velocity = Vector2.Zero;
                this.PickNewTarget();
                this.SetJumpCooldown();
            }
            this.spriteDirection = this.direction;
            if (Main.netMode != 2)
            {
                this.VisualEffects();
            }
            this.CopyToDummy();
            LeashedCritter._dummy.FindFrame();
            base.CopyFromDummy();
        }
References Terraria.GameContent.LeashedEntities.LeashedCritter._dummy, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.CopyToDummy(), Terraria.GameContent.LeashedEntity.direction, Terraria.NPC.FindFrame(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move(), Terraria.Main.netMode, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.PickNewTarget(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.SetJumpCooldown(), System.state, Terraria.GameContent.LeashedEntities.LeashedCritter.State, Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryStartJump(), Terraria.GameContent.LeashedEntities.LeashedCritter.VisualEffects(), Terraria.GameContent.LeashedEntities.LeashedCritter.WaitTime, and Microsoft.Xna.Framework.Vector2.Zero.