Terraria Decompiled: Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move
Move()
void Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move (out bool hitSomething) inline private
Definition at line 112 of file JumperLeashedCritter.cs.
        {
            hitSomething = false;
            Point point = base.Center.ToTileCoordinates();
            int num = Math.Sign((int)this.velocity.X);
            if (num != 0)
            {
                this.direction = num;
            }
            int num2 = Math.Sign((int)this.velocity.Y);
            Vector2 vector = new Vector2((float)num, (float)num2) * base.Size * 0.5f;
            Vector2 vector2 = base.Center + vector + this.velocity;
            if (!WorldGen.SolidTile2(vector2.ToTileCoordinates()))
            {
                this.Move_NoObstruction(point, vector2.Y);
                return;
            }
            hitSomething = true;
            bool flag = false;
            if (num2 != 0)
            {
                Point point2 = point;
                point2.Y += num2;
                flag = WorldGen.SolidTile2(point2);
            }
            bool flag2 = false;
            if (num != 0)
            {
                Point point3 = point;
                point3.X += num;
                flag2 = WorldGen.SolidTile2(point3);
            }
            if (flag)
            {
                this.velocity.Y = 0f;
            }
            if (flag2)
            {
                this.velocity.X = 0f;
            }
            if (!flag && !flag2)
            {
                this.velocity = Vector2.Zero;
            }
        }
References Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Move_NoObstruction(), System.Math.Sign(), Terraria.WorldGen.SolidTile2(), Terraria.GameContent.LeashedEntity.velocity, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Update().