Terraria Decompiled: Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryStartJump
TryStartJump()
bool Terraria.GameContent.LeashedEntities.JumperLeashedCritter.TryStartJump () inline private
Definition at line 86 of file JumperLeashedCritter.cs.
        {
            Vector2 vector = this.TargetPosition.ToWorldCoordinates(8f, 8f) - base.Center;
            if (vector.Y * -1f > this.maxJumpHeight)
            {
                return false;
            }
            float num = Math.Min(Math.Abs(vector.X), this.maxJumpWidth);
            if (num <= this.minJumpWidth)
            {
                return false;
            }
            this.direction = Math.Sign(vector.X);
            float num2 = num / this.maxJumpWidth;
            float num3 = this.maxJumpDuration * num2;
            this.velocity.X = num / num3 * (float)this.direction;
            this.velocity.Y = vector.Y * num2 / num3 - 0.5f * LeashedCritter.gravity * num3;
            if (this.velocity.Y >= 0f)
            {
                return false;
            }
            this.WaitTime = (short)(num3 + (float)this.jumpCooldown);
            return true;
        }
References System.Math.Abs(), Terraria.GameContent.LeashedEntity.direction, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.jumpCooldown, Terraria.GameContent.LeashedEntities.JumperLeashedCritter.maxJumpWidth, System.Math.Min(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.minJumpWidth, System.Math.Sign(), Terraria.GameContent.LeashedEntities.LeashedCritter.TargetPosition, Terraria.GameContent.LeashedEntity.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.LeashedEntities.JumperLeashedCritter.Update().