Terraria Decompiled: Terraria.Net.NetPacket.ShrinkToFit
ShrinkToFit()
void Terraria.Net.NetPacket.ShrinkToFit () inline
Definition at line 71 of file NetPacket.cs.
        {
            if (this.Length == (int)this.Writer.BaseStream.Position)
            {
                return;
            }
            if (this.Writer.BaseStream.Position > (long)this.Length)
            {
                throw new IndexOutOfRangeException("Overwrite on supplied Length. Consider letting Length default to max packet size if you don't know how long it will be");
            }
            this.Length = (int)this.Writer.BaseStream.Position;
            this.Writer.Seek(0, SeekOrigin.Begin);
            this.Writer.Write((ushort)this.Length);
            this.Writer.Seek(this.Length, SeekOrigin.Begin);
        }
References System.IO.BinaryWriter.BaseStream, int, Terraria.Net.NetPacket.Length, System.IO.Stream.Position, System.IO.BinaryWriter.Seek(), System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.Net.NetManager.SendData().