Terraria Decompiled: Microsoft.Xna.Framework.Graphics.ModelMesh.Draw
Draw()
void Microsoft.Xna.Framework.Graphics.ModelMesh.Draw () inline
Definition at line 125 of file ModelMesh.cs.
        {
            foreach (ModelMeshPart modelMeshPart in this.MeshParts)
            {
                Effect effect = modelMeshPart.Effect;
                if (modelMeshPart.PrimitiveCount > 0)
                {
                    this.graphicsDevice.SetVertexBuffer(modelMeshPart.VertexBuffer);
                    this.graphicsDevice.Indices = modelMeshPart.IndexBuffer;
                    foreach (EffectPass effectPass in effect.CurrentTechnique.Passes)
                    {
                        effectPass.Apply();
                        this.graphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, modelMeshPart.VertexOffset, 0, modelMeshPart.NumVertices, modelMeshPart.StartIndex, modelMeshPart.PrimitiveCount);
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.EffectPass.Apply(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.GraphicsDevice.DrawIndexedPrimitives(), Microsoft.Xna.Framework.Graphics.ModelMeshPart.Effect, Microsoft.Xna.Framework.Graphics.ModelMesh.graphicsDevice, Microsoft.Xna.Framework.Graphics.ModelMeshPart.IndexBuffer, Microsoft.Xna.Framework.Graphics.ModelMesh.MeshParts, Microsoft.Xna.Framework.Graphics.ModelMeshPart.NumVertices, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Microsoft.Xna.Framework.Graphics.ModelMeshPart.PrimitiveCount, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(), Microsoft.Xna.Framework.Graphics.ModelMeshPart.StartIndex, Microsoft.Xna.Framework.Graphics.ModelMeshPart.VertexBuffer, and Microsoft.Xna.Framework.Graphics.ModelMeshPart.VertexOffset.
Referenced by Microsoft.Xna.Framework.Graphics.Model.Draw().