Terraria Decompiled: Terraria.Map.MapHelper.SaveMap
SaveMap()
static void Terraria.Map.MapHelper.SaveMap () inline static
Definition at line 3108 of file MapHelper.cs.
        {
            if ((Main.ActivePlayerFileData.IsCloudSave && SocialAPI.Cloud == null) || !Main.mapEnabled)
            {
                return;
            }
            if (!Monitor.TryEnter(MapHelper.IOLock))
            {
                return;
            }
            try
            {
                FileUtilities.ProtectedInvoke(new Action(MapHelper.InternalSaveMap));
            }
            catch (Exception ex)
            {
                using (StreamWriter streamWriter = new StreamWriter("client-crashlog.txt", true))
                {
                    streamWriter.WriteLine(DateTime.Now);
                    streamWriter.WriteLine(ex);
                    streamWriter.WriteLine("");
                }
            }
            finally
            {
                Monitor.Exit(MapHelper.IOLock);
            }
        }
References System.Action(), Terraria.Main.ActivePlayerFileData, Terraria.Social.SocialAPI.Cloud, System.Threading.Monitor.Exit(), Terraria.Map.MapHelper.InternalSaveMap(), Terraria.Map.MapHelper.IOLock, Terraria.IO.FileData.IsCloudSave, Terraria.Main.mapEnabled, System.DateTime.Now, Terraria.Utilities.FileUtilities.ProtectedInvoke(), System.Threading.Monitor.TryEnter(), and System.IO.StreamWriter.WriteLine().
Referenced by Terraria.Map.WorldMap.Save().