Terraria Decompiled: Terraria.Map.MapHelper.LoadMapVersion1
LoadMapVersion1()
static void Terraria.Map.MapHelper.LoadMapVersion1 (BinaryReader fileIO, int release) inline static
Definition at line 3747 of file MapHelper.cs.
        {
            string text = fileIO.ReadString();
            int num = fileIO.ReadInt32();
            int num2 = fileIO.ReadInt32();
            int num3 = fileIO.ReadInt32();
            if (text != Main.worldName || num != Main.worldID || num3 != Main.maxTilesX || num2 != Main.maxTilesY)
            {
                throw new Exception("Map meta-data is invalid.");
            }
            for (int i = 0; i < Main.maxTilesX; i++)
            {
                float num4 = (float)i / (float)Main.maxTilesX;
                Main.statusText = string.Concat(new object[]
                {
                    Lang.gen[67].Value,
                    " ",
                    (int)(num4 * 100f + 1f),
                    "%"
                });
                for (int j = 0; j < Main.maxTilesY; j++)
                {
                    if (fileIO.ReadBoolean())
                    {
                        int num5;
                        if (release > 77)
{
                            num5 = (int)fileIO.ReadUInt16();
                        }
                        else
{
                            num5 = (int)fileIO.ReadByte();
                        }
                        byte b = fileIO.ReadByte();
                        MapHelper.OldMapHelper oldMapHelper;
                        oldMapHelper.misc = fileIO.ReadByte();
                        if (release >= 50)
{
                            oldMapHelper.misc2 = fileIO.ReadByte();
                        }
                        else
{
                            oldMapHelper.misc2 = 0;
                        }
                        bool flag = false;
                        int num6 = (int)oldMapHelper.option();
                        int num7;
                        if (oldMapHelper.active())
{
                            num7 = num6 + (int)MapHelper.tileLookup[num5];
                        }
                        else if (oldMapHelper.water())
{
                            num7 = (int)MapHelper.liquidPosition;
                        }
                        else if (oldMapHelper.lava())
{
                            num7 = (int)(MapHelper.liquidPosition + 1);
                        }
                        else if (oldMapHelper.honey())
{
                            num7 = (int)(MapHelper.liquidPosition + 2);
                        }
                        else if (oldMapHelper.wall())
{
                            num7 = num6 + (int)MapHelper.wallLookup[num5];
                        }
                        else if ((double)j < Main.worldSurface)
{
                            flag = true;
                            num7 = MapHelper.CalcSkyGradient(MapHelper.skyPosition, 256, j);
                        }
                        else if ((double)j < Main.rockLayer)
{
                            flag = true;
                            if (num5 > 255)
{
                                num5 = 255;
                            }
                            num7 = num5 + (int)MapHelper.dirtPosition;
                        }
                        else if (j < Main.UnderworldLayer)
{
                            flag = true;
                            if (num5 > 255)
{
                                num5 = 255;
                            }
                            num7 = num5 + (int)MapHelper.rockPosition;
                        }
                        else
{
                            num7 = (int)MapHelper.hellPosition;
                        }
                        MapTile mapTile = MapTile.Create((ushort)num7, b, 0);
                        Main.Map.SetTile(i, j, ref mapTile);
                        int k = (int)fileIO.ReadInt16();
                        if (b == 255)
{
                            while (k > 0)
{
                                k--;
                                j++;
                                if (flag)
{
                                    if ((double)j < Main.worldSurface)
{
                                        flag = true;
                                        num7 = MapHelper.CalcSkyGradient(MapHelper.skyPosition, 256, j);
                                    }
                                    else if ((double)j < Main.rockLayer)
{
                                        flag = true;
                                        num7 = num5 + (int)MapHelper.dirtPosition;
                                    }
                                    else if (j < Main.UnderworldLayer)
{
                                        flag = true;
                                        num7 = num5 + (int)MapHelper.rockPosition;
                                    }
                                    else
{
                                        flag = true;
                                        num7 = (int)MapHelper.hellPosition;
                                    }
                                    mapTile.Type = (ushort)num7;
                                }
                                Main.Map.SetTile(i, j, ref mapTile);
                            }
                        }
                        else
{
                            while (k > 0)
{
                                j++;
                                k--;
                                b = fileIO.ReadByte();
                                if (b > 18)
{
                                    mapTile.Light = b;
                                    if (flag)
{
                                        if ((double)j < Main.worldSurface)
{
                                            flag = true;
                                            num7 = MapHelper.CalcSkyGradient(MapHelper.skyPosition, 256, j);
                                        }
                                        else if ((double)j < Main.rockLayer)
{
                                            flag = true;
                                            num7 = num5 + (int)MapHelper.dirtPosition;
                                        }
                                        else if (j < Main.UnderworldLayer)
{
                                            flag = true;
                                            num7 = num5 + (int)MapHelper.rockPosition;
                                        }
                                        else
{
                                            flag = true;
                                            num7 = (int)MapHelper.hellPosition;
                                        }
                                        mapTile.Type = (ushort)num7;
                                    }
                                    Main.Map.SetTile(i, j, ref mapTile);
                                }
                            }
                        }
                    }
                    else
                    {
                        int num8 = (int)fileIO.ReadInt16();
                        j += num8;
                    }
                }
            }
        }
References Terraria.Map.MapHelper.OldMapHelper.active(), Terraria.Map.MapHelper.CalcSkyGradient(), Terraria.Map.MapTile.Create(), Terraria.Map.MapHelper.dirtPosition, Terraria.Lang.gen, Terraria.Map.MapHelper.hellPosition, Terraria.Map.MapHelper.OldMapHelper.honey(), int, Terraria.Map.MapHelper.OldMapHelper.lava(), Terraria.Map.MapHelper.liquidPosition, Terraria.Main.Map, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Map.MapHelper.OldMapHelper.option(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt16(), Terraria.Main.rockLayer, Terraria.Map.MapHelper.rockPosition, Terraria.Map.MapHelper.skyPosition, System.text, Terraria.Map.MapHelper.tileLookup, Terraria.Main.UnderworldLayer, Terraria.Map.MapHelper.OldMapHelper.wall(), Terraria.Map.MapHelper.wallLookup, Terraria.Map.MapHelper.OldMapHelper.water(), Terraria.Main.worldID, Terraria.Main.worldName, and Terraria.Main.worldSurface.
Referenced by Terraria.Map.WorldMap.Load().