Terraria Decompiled: Terraria.Map.MapHelper.GetWallType
GetWallType()
static void Terraria.Map.MapHelper.GetWallType (int i, int j, Tile tileCache, ref int newColor, ref int newLight, ref int baseType, ref int baseOption) inline static private
Definition at line 1814 of file MapHelper.cs.
        {
            bool flag = tileCache.invisibleWall();
            if (tileCache.wall > 0 && tileCache.fullbrightWall() && !flag)
            {
                newLight = 255;
            }
            if (tileCache.liquid > 32)
            {
                int num = (int)tileCache.liquidType();
                baseType = (int)MapHelper.liquidPosition + num;
                return;
            }
            if (!tileCache.invisibleWall() && tileCache.wall > 0 && tileCache.wall < WallID.Count)
            {
                int wall = (int)tileCache.wall;
                baseType = (int)MapHelper.wallLookup[wall];
                newColor = (int)tileCache.wallColor();
                if (wall <= 27)
                {
                    if (wall != 21)
                    {
                        if (wall != 27)
{
                            goto IL_00A9;
                        }
                        baseOption = i % 2;
                        return;
                    }
                }
                else if (wall - 88 > 5 && wall != 168 && wall != 241)
                {
                    goto IL_00A9;
                }
                newColor = 0;
                return;
                IL_00A9:
                baseOption = 0;
            }
        }
References Terraria.ID.WallID.Count, Terraria.Tile.fullbrightWall(), int, Terraria.Tile.invisibleWall(), Terraria.Tile.liquid, Terraria.Map.MapHelper.liquidPosition, Terraria.Tile.liquidType(), Terraria.Tile.wall, Terraria.Tile.wallColor(), and Terraria.Map.MapHelper.wallLookup.
Referenced by Terraria.Map.MapHelper.CreateMapTile().