Terraria Decompiled: Terraria.Map.MapHelper.CalcSkyGradient
CalcSkyGradient()
static int Terraria.Map.MapHelper.CalcSkyGradient (ushort skyPosition, int maxSkyGradients, int j) inline static
Definition at line 1911 of file MapHelper.cs.
        {
            int num = (int)((byte)((double)(maxSkyGradients - 1) * ((double)j / Main.worldSurface)));
            return (int)skyPosition + num;
        }
References int, Terraria.Map.MapHelper.maxSkyGradients, Terraria.Map.MapHelper.skyPosition, and Terraria.Main.worldSurface.
Referenced by Terraria.Map.MapHelper.GetBackgroundType(), Terraria.Map.MapHelper.LoadMapVersion1(), and Terraria.Map.MapHelper.LoadMapVersion2().