Terraria Decompiled: Terraria.Map.MapHelper.GetTileType
GetTileType()
static void Terraria.Map.MapHelper.GetTileType (int i, int j, Tile tileCache, ref int newColor, ref int newLight, ref int baseType, ref int baseOption) inline static private
Definition at line 1734 of file MapHelper.cs.
        {
            if ((!DebugOptions.ShowUnbreakableWall || tileCache.wall != 350) && tileCache.active())
            {
                int num = (int)tileCache.type;
                baseType = (int)MapHelper.tileLookup[num];
                bool flag = tileCache.invisibleBlock();
                if (tileCache.fullbrightBlock() && !flag)
                {
                    newLight = 255;
                }
                if (flag)
                {
                    baseType = 0;
                    return;
                }
                if (num == 5)
                {
                    if (WorldGen.IsThisAMushroomTree(i, j))
                    {
                        baseOption = 1;
                    }
                    newColor = (int)tileCache.color();
                    return;
                }
                if (num <= 51)
                {
                    if (num != 19)
                    {
                        if (num != 51)
{
                            goto IL_00CD;
                        }
                    }
                    else
                    {
                        if (tileCache.frameY == 864)
{
                            baseType = 0;
                            goto IL_00CD;
                        }
                        goto IL_00CD;
                    }
                }
                else if (num != 184)
                {
                    if (num != 697)
                    {
                        goto IL_00CD;
                    }
                }
                else
                {
                    if (tileCache.frameX / 22 == 10)
                    {
                        num = 627;
                        baseType = (int)MapHelper.tileLookup[num];
                        goto IL_00CD;
                    }
                    goto IL_00CD;
                }
                if ((i + j) % 2 == 0)
                {
                    baseType = 0;
                }
                IL_00CD:
                if (baseType != 0)
                {
                    MapHelper.GetTileBaseOption(i, j, num, tileCache, ref baseOption);
                    if (num == 160)
                    {
                        newColor = 0;
                        return;
                    }
                    newColor = (int)tileCache.color();
                }
            }
        }
References Terraria.Tile.active(), Terraria.Tile.color(), Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Map.MapHelper.GetTileBaseOption(), int, Terraria.Tile.invisibleBlock(), Terraria.WorldGen.IsThisAMushroomTree(), Terraria.Testing.DebugOptions.ShowUnbreakableWall, Terraria.Map.MapHelper.tileLookup, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.Map.MapHelper.CreateMapTile().