Terraria Decompiled: Terraria.Map.MapHelper.DecompressChunk
DecompressChunk()
static void Terraria.Map.MapHelper.DecompressChunk (byte[] srcData, long srcLength, byte[] dstData, long dstLength, out long resultLength) inline static
Definition at line 3461 of file MapHelper.cs.
        {
            resultLength = 0L;
            ZlibCodec zlibCodec = MapHelper.zlibDecompress;
            zlibCodec.InitializeInflate();
            zlibCodec.InputBuffer = srcData;
            zlibCodec.OutputBuffer = dstData;
            zlibCodec.NextIn = 0;
            zlibCodec.AvailableBytesIn = (int)srcLength;
            zlibCodec.NextOut = 0;
            zlibCodec.AvailableBytesOut = dstData.Length;
            int num = zlibCodec.Inflate(4);
            if ((num == 0 || 1 == num) && zlibCodec.TotalBytesOut > 0L)
            {
                resultLength = zlibCodec.TotalBytesOut;
            }
            int num2 = (int)resultLength;
            while ((long)num2 < dstLength)
            {
                dstData[num2] = 0;
                num2++;
            }
        }
References Ionic.Zlib.ZlibCodec.Inflate(), Ionic.Zlib.ZlibCodec.InitializeInflate(), int, System.L, Ionic.Zlib.ZlibCodec.TotalBytesOut, and Terraria.Map.MapHelper.zlibDecompress.
Referenced by Terraria.Map.MapHelper.LoadMapVersionCompressed().