Terraria Decompiled: Terraria.Map.MapHelper.LoadMapVersionCompressed
LoadMapVersionCompressed()
static unsafe void Terraria.Map.MapHelper.LoadMapVersionCompressed (BinaryReader fileIO, int release) inline static
Definition at line 3486 of file MapHelper.cs.
        {
            if (release >= 135)
            {
                Main.MapFileMetadata = FileMetadata.Read(fileIO, FileType.Map);
            }
            else
            {
                Main.MapFileMetadata = FileMetadata.FromCurrentSettings(FileType.Map);
            }
            DateTime now = DateTime.Now;
            fileIO.ReadString();
            int num = fileIO.ReadInt32();
            int num2 = fileIO.ReadInt32();
            int num3 = fileIO.ReadInt32();
            if (num != Main.worldID || num3 != Main.maxTilesX || num2 != Main.maxTilesY)
            {
                throw new Exception("Map meta-data is invalid.");
            }
            short num4 = fileIO.ReadInt16();
            short num5 = fileIO.ReadInt16();
            short num6 = fileIO.ReadInt16();
            short num7 = fileIO.ReadInt16();
            short num8 = fileIO.ReadInt16();
            short num9 = fileIO.ReadInt16();
            byte[] array = new byte[2048];
            byte[] array2 = new byte[sizeof(MapTile) * 64 * 64];
            bool[] array3 = new bool[(int)num4];
            byte b = 0;
            byte b2 = 128;
            for (int i = 0; i < (int)num4; i++)
            {
                if (b2 == 128)
                {
                    b = fileIO.ReadByte();
                    b2 = 1;
                }
                else
                {
                    b2 = (byte)(b2 << 1);
                }
                if ((b & b2) == b2)
                {
                    array3[i] = true;
                }
            }
            bool[] array4 = new bool[(int)num5];
            b = 0;
            b2 = 128;
            for (int i = 0; i < (int)num5; i++)
            {
                if (b2 == 128)
                {
                    b = fileIO.ReadByte();
                    b2 = 1;
                }
                else
                {
                    b2 = (byte)(b2 << 1);
                }
                if ((b & b2) == b2)
                {
                    array4[i] = true;
                }
            }
            byte[] array5 = new byte[(int)num4];
            ushort num10 = 0;
            for (int i = 0; i < (int)num4; i++)
            {
                if (array3[i])
                {
                    array5[i] = fileIO.ReadByte();
                }
                else
                {
                    array5[i] = 1;
                }
                num10 += (ushort)array5[i];
            }
            byte[] array6 = new byte[(int)num5];
            ushort num11 = 0;
            for (int i = 0; i < (int)num5; i++)
            {
                if (array4[i])
                {
                    array6[i] = fileIO.ReadByte();
                }
                else
                {
                    array6[i] = 1;
                }
                num11 += (ushort)array6[i];
            }
            ushort[] array7 = new ushort[(int)(num10 + num11 + (ushort)num6 + (ushort)num7 + (ushort)num8 + (ushort)num9 + 2)];
            array7[0] = 0;
            ushort num12 = 1;
            ushort num13 = 1;
            for (int i = 0; i < (int)TileID.Count; i++)
            {
                if (i < (int)num4)
                {
                    int num14 = (int)array5[i];
                    int num15 = MapHelper.tileOptionCounts[i];
                    for (int j = 0; j < num15; j++)
                    {
                        if (j < num14)
{
                            array7[(int)num13] = num12;
                            num13 += 1;
                        }
                        num12 += 1;
                    }
                }
                else
                {
                    num12 += (ushort)MapHelper.tileOptionCounts[i];
                }
            }
            for (int i = 0; i < (int)WallID.Count; i++)
            {
                if (i < (int)num5)
                {
                    int num16 = (int)array6[i];
                    int num17 = MapHelper.wallOptionCounts[i];
                    for (int k = 0; k < num17; k++)
                    {
                        if (k < num16)
{
                            array7[(int)num13] = num12;
                            num13 += 1;
                        }
                        num12 += 1;
                    }
                }
                else
                {
                    num12 += (ushort)MapHelper.wallOptionCounts[i];
                }
            }
            for (int i = 0; i < 4; i++)
            {
                if (i < (int)num6)
                {
                    array7[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            for (int i = 0; i < 256; i++)
            {
                if (i < (int)num7)
                {
                    array7[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            for (int i = 0; i < 256; i++)
            {
                if (i < (int)num8)
                {
                    array7[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            for (int i = 0; i < 256; i++)
            {
                if (i < (int)num9)
                {
                    array7[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            array7[(int)num13] = num12;
            bool flag = num13 != num12;
            int num18 = (Main.maxTilesX + 63) / 64;
            int num19 = (Main.maxTilesY + 63) / 64;
            int num20 = num18 * num19;
            int num21 = 4096;
            for (int l = 0; l < num20; l++)
            {
                float num22 = (float)l / (float)num20;
                Main.statusText = string.Concat(new object[]
                {
                    Lang.gen[66].Value,
                    " ",
                    (int)(num22 * 100f + 1f),
                    "%"
                });
                int num23 = fileIO.ReadInt32();
                int num24 = l % num18;
                int num25 = l / num18;
                if (num23 > 0)
                {
                    if (array.Length < num23)
                    {
                        array = new byte[(num23 + 1023) / 1024 * 1024];
                    }
                    for (int m = 0; m < num23; m++)
                    {
                        array[m] = fileIO.ReadByte();
                    }
                    long num26;
                    MapHelper.DecompressChunk(array, (long)num23, array2, (long)array2.Length, out num26);
                    byte[] array8;
                    byte* ptr;
                    if ((array8 = array2) == null || array8.Length == 0)
                    {
                        ptr = null;
                    }
                    else
                    {
                        ptr = &array8[0];
                    }
                    MapTile* ptr2 = (MapTile*)ptr;
                    if (flag)
                    {
                        for (int n = 0; n < num21; n++)
{
                            int num27 = n % 64 + num24 * 64;
                            int num28 = n / 64 + num25 * 64;
                            ptr2[n].Type = array7[(int)ptr2[n].Type];
                            if (num27 < Main.maxTilesX && num28 < Main.maxTilesY)
{
                                Main.Map.SetTile(num27, num28, ref ptr2[n]);
                            }
                        }
                    }
                    else
                    {
                        for (int num29 = 0; num29 < num21; num29++)
{
                            int num30 = num29 % 64 + num24 * 64;
                            int num31 = num29 / 64 + num25 * 64;
                            if (num30 < Main.maxTilesX && num31 < Main.maxTilesY)
{
                                Main.Map.SetTile(num30, num31, ref ptr2[num29]);
                            }
                        }
                    }
                    array8 = null;
                }
                else
                {
                    MapTile mapTile = default(MapTile);
                    for (int num32 = 0; num32 < num21; num32++)
                    {
                        int num33 = num32 % 64 + num24 * 64;
                        int num34 = num32 / 64 + num25 * 64;
                        if (num33 < Main.maxTilesX && num34 < Main.maxTilesY)
{
                            Main.Map.SetTile(num33, num34, ref mapTile);
                        }
                    }
                }
            }
        }
References System.array, Terraria.ID.TileID.Count, Terraria.ID.WallID.Count, Terraria.Map.MapHelper.DecompressChunk(), Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.Lang.gen, int, long, Terraria.Main.Map, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.DateTime.Now, Terraria.IO.FileMetadata.Read(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), Terraria.Map.MapHelper.tileOptionCounts, Terraria.Map.MapTile.Type, Terraria.Map.MapHelper.wallOptionCounts, and Terraria.Main.worldID.
Referenced by Terraria.Map.WorldMap.Load().