Terraria Decompiled: Terraria.Map.MapHelper.GetTileBaseOption
GetTileBaseOption()
static void Terraria.Map.MapHelper.GetTileBaseOption (int x, int y, int tileType, Tile tileCache, ref int baseOption) inline static
Definition at line 1918 of file MapHelper.cs.
        {
            int num4;
            if (tileType <= 242)
            {
                if (tileType <= 105)
                {
                    if (tileType <= 21)
                    {
                        if (tileType <= 15)
{
                            if (tileType == 4)
{
                                if (tileCache.frameX < 66)
{
                                    baseOption = 1;
                                }
                                baseOption = 0;
                                return;
                            }
                            if (tileType != 15)
{
                                goto IL_0ECF;
                            }
                            int num = (int)(tileCache.frameY / 40);
                            baseOption = 0;
                            if (num == 1 || num == 20)
{
                                baseOption = 1;
                                return;
                            }
                            return;
                        }
                        else if (tileType != 19)
{
                            if (tileType != 21)
{
                                goto IL_0ECF;
                            }
                            goto IL_04F0;
                        }
                        else
{
                            int num2 = (int)(tileCache.frameY / 18);
                            baseOption = 0;
                            if (num2 == 48)
{
                                baseOption = 1;
                                return;
                            }
                            return;
                        }
                    }
                    else if (tileType <= 80)
                    {
                        switch (tileType)
{
                        case 26:
                            goto IL_06DE;
                        case 27:
                            if (tileCache.frameY < 34)
{
                                baseOption = 1;
                                return;
                            }
                            baseOption = 0;
                            return;
                        case 28:
                            goto IL_05D1;
                        case 29:
                        case 30:
                            goto IL_0ECF;
                        case 31:
                            goto IL_06CA;
                        default:
{
                            if (tileType != 80)
{
                                goto IL_0ECF;
                            }
                            bool flag;
                            bool flag2;
                            bool flag3;
                            WorldGen.GetCactusType(x, y, (int)tileCache.frameX, (int)tileCache.frameY, out flag, out flag2, out flag3);
                            if (flag)
{
                                baseOption = 1;
                                return;
                            }
                            if (flag2)
{
                                baseOption = 2;
                                return;
                            }
                            if (flag3)
{
                                baseOption = 3;
                                return;
                            }
                            baseOption = 0;
                            return;
                        }
                        }
                    }
                    else if (tileType - 82 > 2)
                    {
                        if (tileType == 89)
{
                            int num3 = (int)(tileCache.frameX / 54);
                            if (num3 <= 21)
{
                                if (num3 != 0 && num3 != 21)
{
                                    goto IL_0313;
                                }
                            }
                            else if (num3 != 23)
{
                                if (num3 != 43)
{
                                    goto IL_0313;
                                }
                                baseOption = 2;
                                return;
                            }
                            baseOption = 0;
                            return;
                            IL_0313:
                            baseOption = 1;
                            return;
                        }
                        if (tileType != 105)
{
                            goto IL_0ECF;
                        }
                        if (tileCache.frameX >= 1548 && tileCache.frameX <= 1654)
{
                            baseOption = 1;
                            return;
                        }
                        if (tileCache.frameX >= 1656 && tileCache.frameX <= 1798)
{
                            baseOption = 2;
                            return;
                        }
                        baseOption = 0;
                        return;
                    }
                    else
                    {
                        if (tileCache.frameX < 18)
{
                            baseOption = 0;
                            return;
                        }
                        if (tileCache.frameX < 36)
{
                            baseOption = 1;
                            return;
                        }
                        if (tileCache.frameX < 54)
{
                            baseOption = 2;
                            return;
                        }
                        if (tileCache.frameX < 72)
{
                            baseOption = 3;
                            return;
                        }
                        if (tileCache.frameX < 90)
{
                            baseOption = 4;
                            return;
                        }
                        if (tileCache.frameX < 108)
{
                            baseOption = 5;
                            return;
                        }
                        baseOption = 6;
                        return;
                    }
                }
                else if (tileType <= 165)
                {
                    if (tileType <= 137)
                    {
                        if (tileType != 129)
{
                            switch (tileType)
{
                            case 133:
                                if (tileCache.frameX < 52)
{
                                    baseOption = 0;
                                    return;
                                }
                                baseOption = 1;
                                return;
                            case 134:
                                if (tileCache.frameX < 28)
{
                                    baseOption = 0;
                                    return;
                                }
                                baseOption = 1;
                                return;
                            case 135:
                            case 136:
                                goto IL_0ECF;
                            case 137:
                                switch (tileCache.frameY / 18)
{
                                default:
                                    baseOption = 0;
                                    return;
                                case 1:
                                case 2:
                                case 3:
                                case 4:
                                    baseOption = 1;
                                    return;
                                case 5:
                                    baseOption = 2;
                                    return;
                                }
                                break;
                            default:
                                goto IL_0ECF;
                            }
                        }
                        else
{
                            if (tileCache.frameX >= 324)
{
                                baseOption = 1;
                                return;
                            }
                            baseOption = 0;
                            return;
                        }
                    }
                    else
                    {
                        if (tileType == 149)
{
                            baseOption = y % 3;
                            return;
                        }
                        if (tileType != 160)
{
                            if (tileType != 165)
{
                                goto IL_0ECF;
                            }
                            goto IL_0807;
                        }
                    }
                }
                else if (tileType <= 187)
                {
                    if (tileType != 178)
                    {
                        switch (tileType)
{
                        case 184:
                            if (tileCache.frameX < 22)
{
                                baseOption = 0;
                                return;
                            }
                            if (tileCache.frameX < 44)
{
                                baseOption = 1;
                                return;
                            }
                            if (tileCache.frameX < 66)
{
                                baseOption = 2;
                                return;
                            }
                            if (tileCache.frameX < 88)
{
                                baseOption = 3;
                                return;
                            }
                            if (tileCache.frameX < 110)
{
                                baseOption = 4;
                                return;
                            }
                            if (tileCache.frameX < 132)
{
                                baseOption = 5;
                                return;
                            }
                            if (tileCache.frameX < 154)
{
                                baseOption = 6;
                                return;
                            }
                            if (tileCache.frameX < 176)
{
                                baseOption = 7;
                                return;
                            }
                            if (tileCache.frameX < 198)
{
                                baseOption = 8;
                                return;
                            }
                            if (tileCache.frameX < 220)
{
                                baseOption = 9;
                                return;
                            }
                            if (tileCache.frameX < 242)
{
                                baseOption = 10;
                                return;
                            }
                            return;
                        case 185:
                            if (tileCache.frameY < 18)
{
                                num4 = (int)(tileCache.frameX / 18);
                                if (num4 < 6 || num4 == 28 || num4 == 29 || num4 == 30 || num4 == 31 || num4 == 32)
{
                                    baseOption = 0;
                                    return;
                                }
                                if (num4 < 12 || num4 == 33 || num4 == 34 || num4 == 35)
{
                                    baseOption = 1;
                                    return;
                                }
                                if (num4 < 28)
{
                                    baseOption = 2;
                                    return;
                                }
                                if (num4 < 48)
{
                                    baseOption = 3;
                                    return;
                                }
                                if (num4 < 54)
{
                                    baseOption = 4;
                                    return;
                                }
                                if (num4 < 72)
{
                                    baseOption = 0;
                                    return;
                                }
                                if (num4 == 72)
{
                                    baseOption = 1;
                                    return;
                                }
                                if (num4 < 78)
{
                                    baseOption = 11;
                                    return;
                                }
                                return;
                            }
                            else
{
                                num4 = (int)(tileCache.frameX / 36);
                                int num5 = (int)(tileCache.frameY / 18 - 1);
                                num4 += num5 * 18;
                                if (num4 < 6 || num4 == 19 || num4 == 20 || num4 == 21 || num4 == 22 || num4 == 23 || num4 == 24 || num4 == 33 || num4 == 38 || num4 == 39 || num4 == 40)
{
                                    baseOption = 0;
                                    return;
                                }
                                if (num4 < 16)
{
                                    baseOption = 2;
                                    return;
                                }
                                if (num4 < 19 || num4 == 31 || num4 == 32)
{
                                    baseOption = 1;
                                    return;
                                }
                                if (num4 < 31)
{
                                    baseOption = 3;
                                    return;
                                }
                                if (num4 < 38)
{
                                    baseOption = 4;
                                    return;
                                }
                                if (num4 < 59)
{
                                    baseOption = 0;
                                    return;
                                }
                                if (num4 < 62)
{
                                    baseOption = 1;
                                    return;
                                }
                                if (num4 < 65)
{
                                    baseOption = 11;
                                    return;
                                }
                                return;
                            }
                            break;
                        case 186:
                            goto IL_0BDC;
                        case 187:
                            goto IL_0C29;
                        default:
                            goto IL_0ECF;
                        }
                    }
                    else
                    {
                        if (tileCache.frameX < 18)
{
                            baseOption = 0;
                            return;
                        }
                        if (tileCache.frameX < 36)
{
                            baseOption = 1;
                            return;
                        }
                        if (tileCache.frameX < 54)
{
                            baseOption = 2;
                            return;
                        }
                        if (tileCache.frameX < 72)
{
                            baseOption = 3;
                            return;
                        }
                        if (tileCache.frameX < 90)
{
                            baseOption = 4;
                            return;
                        }
                        if (tileCache.frameX < 108)
{
                            baseOption = 5;
                            return;
                        }
                        baseOption = 6;
                        return;
                    }
                }
                else
                {
                    if (tileType == 227)
                    {
                        baseOption = (int)(tileCache.frameX / 34);
                        return;
                    }
                    if (tileType != 240)
                    {
                        if (tileType != 242)
{
                            goto IL_0ECF;
                        }
                        num4 = (int)(tileCache.frameY / 72);
                        if (tileCache.frameX / 106 == 0 && num4 >= 22 && num4 <= 24)
{
                            baseOption = 1;
                            return;
                        }
                        baseOption = 0;
                        return;
                    }
                    else
                    {
                        num4 = (int)(tileCache.frameX / 54);
                        int num6 = (int)(tileCache.frameY / 54);
                        num4 += num6 * 36;
                        if ((num4 >= 0 && num4 <= 11) || (num4 >= 47 && num4 <= 53) || num4 == 72 || num4 == 73 || num4 == 75)
{
                            baseOption = 0;
                            return;
                        }
                        if ((num4 >= 12 && num4 <= 15) || (num4 >= 18 && num4 <= 35) || (num4 >= 63 && num4 <= 71) || num4 == 74 || (num4 >= 76 && num4 <= 100))
{
                            baseOption = 1;
                            return;
                        }
                        if (num4 == 16 || num4 == 17)
{
                            baseOption = 2;
                            return;
                        }
                        if (num4 >= 41 && num4 <= 45)
{
                            baseOption = 3;
                            return;
                        }
                        if (num4 == 46)
{
                            baseOption = 4;
                            return;
                        }
                        return;
                    }
                }
            }
            else if (tileType <= 519)
            {
                if (tileType <= 453)
                {
                    if (tileType <= 428)
                    {
                        switch (tileType)
{
                        case 419:
                            num4 = (int)(tileCache.frameX / 18);
                            if (num4 > 2)
{
                                num4 = 2;
                            }
                            baseOption = num4;
                            return;
                        case 420:
                            num4 = (int)(tileCache.frameY / 18);
                            if (num4 > 5)
{
                                num4 = 5;
                            }
                            baseOption = num4;
                            return;
                        case 421:
                        case 422:
                            goto IL_0ECF;
                        case 423:
                            num4 = (int)(tileCache.frameY / 18);
                            if (num4 > 6)
{
                                num4 = 6;
                            }
                            baseOption = num4;
                            return;
                        default:
                            if (tileType != 428)
{
                                goto IL_0ECF;
                            }
                            num4 = (int)(tileCache.frameY / 18);
                            if (num4 > 3)
{
                                num4 = 3;
                            }
                            baseOption = num4;
                            return;
                        }
                    }
                    else
                    {
                        if (tileType == 440)
{
                            num4 = (int)(tileCache.frameX / 54);
                            if (num4 > 6)
{
                                num4 = 6;
                            }
                            baseOption = num4;
                            return;
                        }
                        if (tileType == 441)
{
                            goto IL_04F0;
                        }
                        if (tileType != 453)
{
                            goto IL_0ECF;
                        }
                        num4 = (int)(tileCache.frameX / 36);
                        if (num4 > 2)
{
                            num4 = 2;
                        }
                        baseOption = num4;
                        return;
                    }
                }
                else if (tileType <= 461)
                {
                    if (tileType == 457)
                    {
                        num4 = (int)(tileCache.frameX / 36);
                        if (num4 > 4)
{
                            num4 = 4;
                        }
                        baseOption = num4;
                        return;
                    }
                    if (tileType != 461)
                    {
                        goto IL_0ECF;
                    }
                    if (Main.SceneMetrics.ZoneCorrupt)
                    {
                        baseOption = 1;
                        return;
                    }
                    if (Main.SceneMetrics.ZoneCrimson)
                    {
                        baseOption = 2;
                        return;
                    }
                    if (Main.SceneMetrics.ZoneHallow)
                    {
                        baseOption = 3;
                        return;
                    }
                    return;
                }
                else if (tileType - 467 > 1)
                {
                    if (tileType != 493)
                    {
                        if (tileType - 518 > 1)
{
                            goto IL_0ECF;
                        }
                        baseOption = (int)(tileCache.frameY / 18);
                        return;
                    }
                    else
                    {
                        if (tileCache.frameX < 18)
{
                            baseOption = 0;
                            return;
                        }
                        if (tileCache.frameX < 36)
{
                            baseOption = 1;
                            return;
                        }
                        if (tileCache.frameX < 54)
{
                            baseOption = 2;
                            return;
                        }
                        if (tileCache.frameX < 72)
{
                            baseOption = 3;
                            return;
                        }
                        if (tileCache.frameX < 90)
{
                            baseOption = 4;
                            return;
                        }
                        baseOption = 5;
                        return;
                    }
                }
                else
                {
                    num4 = (int)(tileCache.frameX / 36);
                    switch (num4)
                    {
                    case 0:
                    case 1:
                    case 2:
                    case 3:
                    case 4:
                    case 5:
                    case 6:
                    case 7:
                    case 8:
                    case 9:
                    case 10:
                    case 11:
                        baseOption = num4;
                        return;
                    case 12:
                    case 13:
                    case 15:
                    case 18:
                        baseOption = 10;
                        return;
                    case 14:
                    case 17:
                        baseOption = 7;
                        return;
                    case 16:
                        baseOption = 3;
                        return;
                    default:
                        baseOption = 12;
                        return;
                    }
                }
            }
            else if (tileType <= 572)
            {
                if (tileType <= 530)
                {
                    if (tileType == 529)
                    {
                        int num7 = y + 1;
                        int num8;
                        int num9;
                        int num10;
                        WorldGen.GetBiomeInfluence(x, x, num7, num7, out num8, out num9, out num10);
                        int num11 = num8;
                        if (num11 < num9)
{
                            num11 = num9;
                        }
                        if (num11 < num10)
{
                            num11 = num10;
                        }
                        int num12;
                        if (num8 == 0 && num9 == 0 && num10 == 0)
{
                            if (x < WorldGen.beachDistance || x > Main.maxTilesX - WorldGen.beachDistance)
{
                                num12 = 1;
                            }
                            else
{
                                num12 = 0;
                            }
                        }
                        else if (num10 == num11)
{
                            num12 = 2;
                        }
                        else if (num9 == num11)
{
                            num12 = 3;
                        }
                        else
{
                            num12 = 4;
                        }
                        baseOption = num12;
                        return;
                    }
                    if (tileType != 530)
                    {
                        goto IL_0ECF;
                    }
                    int num13 = y - (int)(tileCache.frameY % 36 / 18) + 2;
                    int num14 = x - (int)(tileCache.frameX % 54 / 18);
                    int num15;
                    int num16;
                    int num17;
                    WorldGen.GetBiomeInfluence(num14, num14 + 3, num13, num13, out num15, out num16, out num17);
                    int num18 = num15;
                    if (num18 < num16)
                    {
                        num18 = num16;
                    }
                    if (num18 < num17)
                    {
                        num18 = num17;
                    }
                    int num19;
                    if (num15 == 0 && num16 == 0 && num17 == 0)
                    {
                        num19 = 0;
                    }
                    else if (num17 == num18)
                    {
                        num19 = 1;
                    }
                    else if (num16 == num18)
                    {
                        num19 = 2;
                    }
                    else
                    {
                        num19 = 3;
                    }
                    baseOption = num19;
                    return;
                }
                else if (tileType != 548)
                {
                    if (tileType != 560)
                    {
                        if (tileType != 572)
{
                            goto IL_0ECF;
                        }
                        baseOption = (int)(tileCache.frameY / 36);
                        return;
                    }
                    else
                    {
                        num4 = (int)(tileCache.frameX / 36);
                        if (num4 <= 2)
{
                            baseOption = num4;
                            return;
                        }
                        baseOption = 0;
                        return;
                    }
                }
                else
                {
                    if (tileCache.frameX / 54 < 7)
                    {
                        baseOption = 0;
                        return;
                    }
                    baseOption = 1;
                    return;
                }
            }
            else if (tileType <= 597)
            {
                if (tileType == 591)
                {
                    baseOption = (int)(tileCache.frameX / 36);
                    return;
                }
                if (tileType != 597)
                {
                    goto IL_0ECF;
                }
                num4 = (int)(tileCache.frameX / 54);
                if (num4 <= 10)
                {
                    baseOption = num4;
                    return;
                }
                baseOption = 0;
                return;
            }
            else if (tileType - 627 > 1)
            {
                switch (tileType)
                {
                case 647:
                    goto IL_0BDC;
                case 648:
                    goto IL_0C29;
                case 649:
                {
                    num4 = (int)(tileCache.frameX / 36);
                    int num20 = (int)(tileCache.frameY / 18 - 1);
                    num4 += num20 * 18;
                    if (num4 < 6 || num4 == 19 || num4 == 20 || num4 == 21 || num4 == 22 || num4 == 23 || num4 == 24 || num4 == 33 || num4 == 38 || num4 == 39 || num4 == 40)
                    {
                        baseOption = 0;
                        return;
                    }
                    if (num4 < 16)
                    {
                        baseOption = 2;
                        return;
                    }
                    if (num4 < 19 || num4 == 31 || num4 == 32)
                    {
                        baseOption = 1;
                        return;
                    }
                    if (num4 < 31)
                    {
                        baseOption = 3;
                        return;
                    }
                    if (num4 < 38)
                    {
                        baseOption = 4;
                        return;
                    }
                    if (num4 < 59)
                    {
                        baseOption = 0;
                        return;
                    }
                    if (num4 < 62)
                    {
                        baseOption = 1;
                        return;
                    }
                    if (num4 < 65)
                    {
                        baseOption = 11;
                        return;
                    }
                    return;
                }
                case 650:
                    num4 = (int)(tileCache.frameX / 18);
                    if (num4 < 6 || num4 == 28 || num4 == 29 || num4 == 30 || num4 == 31 || num4 == 32)
                    {
                        baseOption = 0;
                        return;
                    }
                    if (num4 < 12 || num4 == 33 || num4 == 34 || num4 == 35)
                    {
                        baseOption = 1;
                        return;
                    }
                    if (num4 < 28)
                    {
                        baseOption = 2;
                        return;
                    }
                    if (num4 < 48)
                    {
                        baseOption = 3;
                        return;
                    }
                    if (num4 < 54)
                    {
                        baseOption = 4;
                        return;
                    }
                    if (num4 < 72)
                    {
                        baseOption = 0;
                        return;
                    }
                    if (num4 == 72)
                    {
                        baseOption = 1;
                        return;
                    }
                    if (num4 < 78)
                    {
                        baseOption = 11;
                        return;
                    }
                    return;
                case 651:
                case 652:
                    goto IL_0ECF;
                case 653:
                    goto IL_05D1;
                default:
                    switch (tileType)
                    {
                    case 692:
                        break;
                    case 693:
                    case 694:
                        goto IL_0807;
                    case 695:
                        goto IL_06DE;
                    case 696:
                        goto IL_06CA;
                    default:
                        goto IL_0ECF;
                    }
                    break;
                }
            }
            baseOption = (x + y) % 9;
            return;
            IL_04F0:
            num4 = (int)(tileCache.frameX / 36);
            if (num4 == 1 || num4 == 2 || num4 == 10 || num4 == 13 || num4 == 15)
            {
                baseOption = 1;
                return;
            }
            if (num4 == 3 || num4 == 4)
            {
                baseOption = 2;
                return;
            }
            if (num4 == 6)
            {
                baseOption = 3;
                return;
            }
            if (num4 == 11 || num4 == 17)
            {
                baseOption = 4;
                return;
            }
            baseOption = 0;
            return;
            IL_05D1:
            if (tileCache.frameY < 144)
            {
                baseOption = 0;
                return;
            }
            if (tileCache.frameY < 252)
            {
                baseOption = 1;
                return;
            }
            if (tileCache.frameY < 360 || (tileCache.frameY >= 900 && tileCache.frameY < 1008))
            {
                baseOption = 2;
                return;
            }
            if (tileCache.frameY < 468)
            {
                baseOption = 3;
                return;
            }
            if (tileCache.frameY < 576)
            {
                baseOption = 4;
                return;
            }
            if (tileCache.frameY < 684)
            {
                baseOption = 5;
                return;
            }
            if (tileCache.frameY < 792)
            {
                baseOption = 6;
                return;
            }
            if (tileCache.frameY < 900)
            {
                baseOption = 8;
                return;
            }
            if (tileCache.frameY < 1008)
            {
                baseOption = 7;
                return;
            }
            if (tileCache.frameY < 1116)
            {
                baseOption = 0;
                return;
            }
            if (tileCache.frameY < 1224)
            {
                baseOption = 3;
                return;
            }
            baseOption = 7;
            return;
            IL_06CA:
            if (tileCache.frameX >= 36)
            {
                baseOption = 1;
                return;
            }
            baseOption = 0;
            return;
            IL_06DE:
            if (tileCache.frameX >= 54)
            {
                baseOption = 1;
                return;
            }
            baseOption = 0;
            return;
            IL_0807:
            if (tileCache.frameX < 54)
            {
                baseOption = 0;
                return;
            }
            if (tileCache.frameX < 106)
            {
                baseOption = 1;
                return;
            }
            if (tileCache.frameX >= 216)
            {
                baseOption = 1;
                return;
            }
            if (tileCache.frameX < 162)
            {
                baseOption = 2;
                return;
            }
            baseOption = 3;
            return;
            IL_0BDC:
            num4 = (int)(tileCache.frameX / 54);
            if (num4 < 7)
            {
                baseOption = 2;
                return;
            }
            if (num4 < 22 || num4 == 33 || num4 == 34 || num4 == 35)
            {
                baseOption = 0;
                return;
            }
            if (num4 < 25)
            {
                baseOption = 1;
                return;
            }
            if (num4 == 25)
            {
                baseOption = 5;
                return;
            }
            if (num4 < 32)
            {
                baseOption = 3;
                return;
            }
            return;
            IL_0C29:
            num4 = (int)(tileCache.frameX / 54);
            int num21 = (int)(tileCache.frameY / 36);
            num4 += num21 * 36;
            if (num4 < 3 || num4 == 14 || num4 == 15 || num4 == 16)
            {
                baseOption = 0;
                return;
            }
            if (num4 < 6)
            {
                baseOption = 6;
                return;
            }
            if (num4 < 9)
            {
                baseOption = 7;
                return;
            }
            if (num4 < 14)
            {
                baseOption = 4;
                return;
            }
            if (num4 < 18)
            {
                baseOption = 4;
                return;
            }
            if (num4 < 23)
            {
                baseOption = 8;
                return;
            }
            if (num4 < 25)
            {
                baseOption = 0;
                return;
            }
            if (num4 < 29)
            {
                baseOption = 1;
                return;
            }
            if (num4 < 47)
            {
                baseOption = 0;
                return;
            }
            if (num4 < 50)
            {
                baseOption = 1;
                return;
            }
            if (num4 < 52)
            {
                baseOption = 10;
                return;
            }
            if (num4 < 55)
            {
                baseOption = 2;
                return;
            }
            return;
            IL_0ECF:
            baseOption = 0;
        }
References Terraria.WorldGen.beachDistance, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.WorldGen.GetBiomeInfluence(), Terraria.WorldGen.GetCactusType(), int, Terraria.Main.maxTilesX, Terraria.Main.SceneMetrics, Terraria.SceneMetrics.ZoneCorrupt, Terraria.SceneMetrics.ZoneCrimson, and Terraria.SceneMetrics.ZoneHallow.
Referenced by Terraria.Main.DrawInfoAccs(), Terraria.Player.GetCraftingFilterForTile(), and Terraria.Map.MapHelper.GetTileType().