Terraria Decompiled: Terraria.Map.MapHelper.LoadMapVersion2
LoadMapVersion2()
static void Terraria.Map.MapHelper.LoadMapVersion2 (BinaryReader fileIO, int release) inline static
Definition at line 3926 of file MapHelper.cs.
        {
            if (release >= 135)
            {
                Main.MapFileMetadata = FileMetadata.Read(fileIO, FileType.Map);
            }
            else
            {
                Main.MapFileMetadata = FileMetadata.FromCurrentSettings(FileType.Map);
            }
            fileIO.ReadString();
            int num = fileIO.ReadInt32();
            int num2 = fileIO.ReadInt32();
            int num3 = fileIO.ReadInt32();
            if (num != Main.worldID || num3 != Main.maxTilesX || num2 != Main.maxTilesY)
            {
                throw new Exception("Map meta-data is invalid.");
            }
            short num4 = fileIO.ReadInt16();
            short num5 = fileIO.ReadInt16();
            short num6 = fileIO.ReadInt16();
            short num7 = fileIO.ReadInt16();
            short num8 = fileIO.ReadInt16();
            short num9 = fileIO.ReadInt16();
            bool[] array = new bool[(int)num4];
            byte b = 0;
            byte b2 = 128;
            for (int i = 0; i < (int)num4; i++)
            {
                if (b2 == 128)
                {
                    b = fileIO.ReadByte();
                    b2 = 1;
                }
                else
                {
                    b2 = (byte)(b2 << 1);
                }
                if ((b & b2) == b2)
                {
                    array[i] = true;
                }
            }
            bool[] array2 = new bool[(int)num5];
            b = 0;
            b2 = 128;
            for (int i = 0; i < (int)num5; i++)
            {
                if (b2 == 128)
                {
                    b = fileIO.ReadByte();
                    b2 = 1;
                }
                else
                {
                    b2 = (byte)(b2 << 1);
                }
                if ((b & b2) == b2)
                {
                    array2[i] = true;
                }
            }
            byte[] array3 = new byte[(int)num4];
            ushort num10 = 0;
            for (int i = 0; i < (int)num4; i++)
            {
                if (array[i])
                {
                    array3[i] = fileIO.ReadByte();
                }
                else
                {
                    array3[i] = 1;
                }
                num10 += (ushort)array3[i];
            }
            byte[] array4 = new byte[(int)num5];
            ushort num11 = 0;
            for (int i = 0; i < (int)num5; i++)
            {
                if (array2[i])
                {
                    array4[i] = fileIO.ReadByte();
                }
                else
                {
                    array4[i] = 1;
                }
                num11 += (ushort)array4[i];
            }
            ushort[] array5 = new ushort[(int)(num10 + num11 + (ushort)num6 + (ushort)num7 + (ushort)num8 + (ushort)num9 + 2)];
            array5[0] = 0;
            ushort num12 = 1;
            ushort num13 = 1;
            ushort num14 = num13;
            for (int i = 0; i < (int)TileID.Count; i++)
            {
                if (i < (int)num4)
                {
                    int num15 = (int)array3[i];
                    int num16 = MapHelper.tileOptionCounts[i];
                    for (int j = 0; j < num16; j++)
                    {
                        if (j < num15)
{
                            array5[(int)num13] = num12;
                            num13 += 1;
                        }
                        num12 += 1;
                    }
                }
                else
                {
                    num12 += (ushort)MapHelper.tileOptionCounts[i];
                }
            }
            ushort num17 = num13;
            for (int i = 0; i < (int)WallID.Count; i++)
            {
                if (i < (int)num5)
                {
                    int num18 = (int)array4[i];
                    int num19 = MapHelper.wallOptionCounts[i];
                    for (int k = 0; k < num19; k++)
                    {
                        if (k < num18)
{
                            array5[(int)num13] = num12;
                            num13 += 1;
                        }
                        num12 += 1;
                    }
                }
                else
                {
                    num12 += (ushort)MapHelper.wallOptionCounts[i];
                }
            }
            ushort num20 = num13;
            for (int i = 0; i < 4; i++)
            {
                if (i < (int)num6)
                {
                    array5[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            ushort num21 = num13;
            for (int i = 0; i < 256; i++)
            {
                if (i < (int)num7)
                {
                    array5[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            ushort num22 = num13;
            for (int i = 0; i < 256; i++)
            {
                if (i < (int)num8)
                {
                    array5[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            ushort num23 = num13;
            for (int i = 0; i < 256; i++)
            {
                if (i < (int)num9)
                {
                    array5[(int)num13] = num12;
                    num13 += 1;
                }
                num12 += 1;
            }
            ushort num24 = num13;
            array5[(int)num13] = num12;
            BinaryReader binaryReader;
            if (release >= 93)
            {
                binaryReader = new BinaryReader(new DeflateStream(fileIO.BaseStream, 1));
            }
            else
            {
                binaryReader = new BinaryReader(fileIO.BaseStream);
            }
            for (int l = 0; l < Main.maxTilesY; l++)
            {
                float num25 = (float)l / (float)Main.maxTilesY;
                Main.statusText = string.Concat(new object[]
                {
                    Lang.gen[67].Value,
                    " ",
                    (int)(num25 * 100f + 1f),
                    "%"
                });
                for (int m = 0; m < Main.maxTilesX; m++)
                {
                    byte b3 = binaryReader.ReadByte();
                    byte b4;
                    if ((b3 & 1) == 1)
                    {
                        b4 = binaryReader.ReadByte();
                    }
                    else
                    {
                        b4 = 0;
                    }
                    if ((b4 & 1) == 1)
                    {
                        binaryReader.ReadByte();
                    }
                    byte b5 = (byte)((b3 & 14) >> 1);
                    bool flag;
                    switch (b5)
                    {
                    case 0:
                        flag = false;
                        break;
                    case 1:
                    case 2:
                    case 7:
                        flag = true;
                        break;
                    case 3:
                    case 4:
                    case 5:
                        flag = false;
                        break;
                    case 6:
                        flag = false;
                        break;
                    default:
                        flag = false;
                        break;
                    }
                    ushort num26;
                    if (flag)
                    {
                        if ((b3 & 16) == 16)
{
                            num26 = binaryReader.ReadUInt16();
                        }
                        else
{
                            num26 = (ushort)binaryReader.ReadByte();
                        }
                    }
                    else
                    {
                        num26 = 0;
                    }
                    byte b6;
                    if ((b3 & 32) == 32)
                    {
                        b6 = binaryReader.ReadByte();
                    }
                    else
                    {
                        b6 = byte.MaxValue;
                    }
                    int n;
                    switch ((byte)((b3 & 192) >> 6))
                    {
                    case 0:
                        n = 0;
                        break;
                    case 1:
                        n = (int)binaryReader.ReadByte();
                        break;
                    case 2:
                        n = (int)binaryReader.ReadInt16();
                        break;
                    default:
                        n = 0;
                        break;
                    }
                    if (b5 == 0)
                    {
                        m += n;
                    }
                    else
                    {
                        switch (b5)
{
                        case 1:
                            num26 += num14;
                            break;
                        case 2:
                            num26 += num17;
                            break;
                        case 3:
                        case 4:
                        case 5:
{
                            int num27 = (int)(b5 - 3);
                            if ((b4 & 64) == 64)
{
                                num27 = 3;
                            }
                            num26 += (ushort)((int)num20 + num27);
                            break;
                        }
                        case 6:
                            if ((double)l < Main.worldSurface)
{
                                num26 += (ushort)MapHelper.CalcSkyGradient(num21, (int)num7, l);
                            }
                            else
{
                                num26 = num24;
                            }
                            break;
                        case 7:
                            if ((double)l < Main.rockLayer)
{
                                num26 += num22;
                            }
                            else
{
                                num26 += num23;
                            }
                            break;
                        }
                        MapTile mapTile = MapTile.Create(array5[(int)num26], b6, (byte)((b4 >> 1) & 31));
                        Main.Map.SetTile(m, l, ref mapTile);
                        if (b6 == 255)
{
                            while (n > 0)
{
                                m++;
                                Main.Map.SetTile(m, l, ref mapTile);
                                n--;
                            }
                        }
                        else
{
                            while (n > 0)
{
                                m++;
                                mapTile = mapTile.WithLight(binaryReader.ReadByte());
                                Main.Map.SetTile(m, l, ref mapTile);
                                n--;
                            }
                        }
                    }
                }
            }
            binaryReader.Close();
        }
References System.array, System.IO.BinaryReader.BaseStream, Terraria.Map.MapHelper.CalcSkyGradient(), Terraria.ID.TileID.Count, Terraria.ID.WallID.Count, Terraria.Map.MapTile.Create(), Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.Lang.gen, int, Terraria.Main.Map, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.IO.FileMetadata.Read(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), Terraria.Main.rockLayer, Terraria.Map.MapHelper.tileOptionCounts, Terraria.Map.MapHelper.wallOptionCounts, Terraria.Map.MapTile.WithLight(), Terraria.Main.worldID, and Terraria.Main.worldSurface.
Referenced by Terraria.Map.WorldMap.Load().