Terraria Decompiled: Terraria.Map.MapHelper.CreateMapTile
CreateMapTile()
static MapTile Terraria.Map.MapHelper.CreateMapTile (int i, int j, byte Light, int backgroundOverride = 0) inline static
Definition at line 1701 of file MapHelper.cs.
        {
            Tile tile = Main.tile[i, j];
            if (tile == null)
            {
                return default(MapTile);
            }
            int num = 0;
            int num2 = (int)Light;
            int num3 = 0;
            int num4 = 0;
            MapHelper.GetTileType(i, j, tile, ref num, ref num2, ref num3, ref num4);
            if (num3 == 0)
            {
                MapHelper.GetWallType(i, j, tile, ref num, ref num2, ref num3, ref num4);
            }
            if (num3 == 0)
            {
                num = 0;
                num2 = (int)Light;
                if (backgroundOverride != 0)
                {
                    num3 = backgroundOverride;
                }
                else
                {
                    num3 = MapHelper.GetBackgroundType(i, j, ref num2);
                }
            }
            return MapTile.Create((ushort)(num3 + num4), (byte)num2, (byte)num);
        }
References Terraria.Map.MapTile.Create(), Terraria.Map.MapHelper.GetBackgroundType(), Terraria.Map.MapHelper.GetTileType(), Terraria.Map.MapHelper.GetWallType(), int, and Terraria.Main.tile.
Referenced by Terraria.Map.WorldMap.Update(), Terraria.Map.WorldMap.UpdateLighting(), and Terraria.Map.WorldMap.UpdateType().