Terraria Decompiled: Terraria.Map.MapHelper.GetBackgroundType
GetBackgroundType()
static int Terraria.Map.MapHelper.GetBackgroundType (int i, int j, ref int newLight) inline static private
Definition at line 1856 of file MapHelper.cs.
        {
            if ((double)j < Main.worldSurface)
            {
                if (Main.remixWorld)
                {
                    newLight = 5;
                    return 100;
                }
                newLight = 255;
                return MapHelper.CalcSkyGradient(MapHelper.skyPosition, 256, j);
            }
            else
            {
                if (j >= Main.UnderworldLayer)
                {
                    return (int)MapHelper.hellPosition;
                }
                byte b = 0;
                if (!WorldGen.generatingWorld)
                {
                    if (!MapHelper.sceneArea.Contains(i, j))
                    {
                        for (int k = i - 36; k <= i + 30; k += 10)
{
                            for (int l = j - 36; l <= j + 30; l += 10)
{
                                int type = (int)Main.Map[k, l].Type;
                                for (int m = 0; m < MapHelper.snowTypes.Length; m++)
{
                                    if ((int)MapHelper.snowTypes[m] == type)
{
                                        b = byte.MaxValue;
                                        k = i + 31;
                                        l = j + 31;
                                        break;
                                    }
                                }
                            }
                        }
                    }
                    else
                    {
                        b = (byte)(Utils.Clamp<float>(MapHelper.sceneSnowiness, 0f, 1f) * 255f);
                    }
                }
                if ((double)j < Main.rockLayer)
                {
                    return (int)(MapHelper.dirtPosition + (ushort)b);
                }
                return (int)(MapHelper.rockPosition + (ushort)b);
            }
        }
References Terraria.Map.MapHelper.CalcSkyGradient(), Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.WorldGen.generatingWorld, Terraria.Map.MapHelper.hellPosition, int, Terraria.Main.Map, Terraria.Main.remixWorld, Terraria.Main.rockLayer, Terraria.Map.MapHelper.sceneArea, Terraria.Map.MapHelper.sceneSnowiness, Terraria.Map.MapHelper.skyPosition, Terraria.Map.MapHelper.snowTypes, Terraria.Main.UnderworldLayer, and Terraria.Main.worldSurface.
Referenced by Terraria.Map.MapHelper.CreateMapTile().