Terraria Decompiled: Terraria.Map.MapHelper.InternalSaveMap
InternalSaveMap()
static void Terraria.Map.MapHelper.InternalSaveMap () inline static private
Definition at line 3138 of file MapHelper.cs.
        {
            bool isCloudSave = Main.ActivePlayerFileData.IsCloudSave;
            string text = Main.playerPathName.Substring(0, Main.playerPathName.Length - 4);
            if (!isCloudSave)
            {
                Utils.TryCreatingDirectory(text);
            }
            text = text + Path.DirectorySeparatorChar.ToString() + Main.ActiveWorldFileData.MapFileName + ".map";
            new Stopwatch().Start();
            if (!Main.gameMenu)
            {
                MapHelper.noStatusText = true;
            }
            using (MemoryStream memoryStream = new MemoryStream(4000))
            {
                using (BinaryWriter binaryWriter = new BinaryWriter(memoryStream))
                {
                    using (DeflateStream deflateStream = new DeflateStream(memoryStream, 0))
                    {
                        int num = 0;
                        byte[] array = new byte[16384];
                        binaryWriter.Write(319);
                        Main.MapFileMetadata.IncrementAndWrite(binaryWriter);
                        binaryWriter.Write(Main.worldName);
                        binaryWriter.Write(Main.worldID);
                        binaryWriter.Write(Main.maxTilesY);
                        binaryWriter.Write(Main.maxTilesX);
                        binaryWriter.Write((short)TileID.Count);
                        binaryWriter.Write((short)WallID.Count);
                        binaryWriter.Write(4);
                        binaryWriter.Write(256);
                        binaryWriter.Write(256);
                        binaryWriter.Write(256);
                        byte b = 1;
                        byte b2 = 0;
                        int i;
                        for (i = 0; i < (int)TileID.Count; i++)
{
                            if (MapHelper.tileOptionCounts[i] != 1)
{
                                b2 |= b;
                            }
                            if (b == 128)
{
                                binaryWriter.Write(b2);
                                b2 = 0;
                                b = 1;
                            }
                            else
{
                                b = (byte)(b << 1);
                            }
                        }
                        if (b != 1)
{
                            binaryWriter.Write(b2);
                        }
                        i = 0;
                        b = 1;
                        b2 = 0;
                        while (i < (int)WallID.Count)
{
                            if (MapHelper.wallOptionCounts[i] != 1)
{
                                b2 |= b;
                            }
                            if (b == 128)
{
                                binaryWriter.Write(b2);
                                b2 = 0;
                                b = 1;
                            }
                            else
{
                                b = (byte)(b << 1);
                            }
                            i++;
                        }
                        if (b != 1)
{
                            binaryWriter.Write(b2);
                        }
                        for (i = 0; i < (int)TileID.Count; i++)
{
                            if (MapHelper.tileOptionCounts[i] != 1)
{
                                binaryWriter.Write((byte)MapHelper.tileOptionCounts[i]);
                            }
                        }
                        for (i = 0; i < (int)WallID.Count; i++)
{
                            if (MapHelper.wallOptionCounts[i] != 1)
{
                                binaryWriter.Write((byte)MapHelper.wallOptionCounts[i]);
                            }
                        }
                        binaryWriter.Flush();
                        for (int j = 0; j < Main.maxTilesY; j++)
{
                            if (!MapHelper.noStatusText)
{
                                float num2 = (float)j / (float)Main.maxTilesY;
                                Main.statusText = string.Concat(new object[]
{
                                    Lang.gen[66].Value,
                                    " ",
                                    (int)(num2 * 100f + 1f),
                                    "%"
                                });
                            }
                            for (int k = 0; k < Main.maxTilesX; k++)
{
                                MapTile mapTile = Main.Map[k, j];
                                byte b5;
                                byte b4;
                                byte b3 = (b4 = (b5 = 0));
                                bool flag = true;
                                bool flag2 = true;
                                int num3 = 0;
                                int num4 = 0;
                                byte b6 = 0;
                                int num5;
                                ushort num6;
                                int num7;
                                if (mapTile.Light <= 18)
{
                                    flag2 = false;
                                    flag = false;
                                    num5 = 0;
                                    num6 = 0;
                                    num7 = 0;
                                    int num8 = k + 1;
                                    int l = Main.maxTilesX - k - 1;
                                    while (l > 0)
{
                                        if (Main.Map[num8, j].Light > 18)
{
                                            break;
                                        }
                                        num7++;
                                        l--;
                                        num8++;
                                    }
                                }
                                else
{
                                    b6 = mapTile.Color;
                                    num6 = mapTile.Type;
                                    if (num6 < MapHelper.wallPosition)
{
                                        num5 = 1;
                                        num6 -= MapHelper.tilePosition;
                                    }
                                    else if (num6 < MapHelper.liquidPosition)
{
                                        num5 = 2;
                                        num6 -= MapHelper.wallPosition;
                                    }
                                    else if (num6 < MapHelper.skyPosition)
{
                                        int num9 = (int)(num6 - MapHelper.liquidPosition);
                                        if (num9 == 3)
{
                                            b3 |= 64;
                                            num9 = 0;
                                        }
                                        num5 = 3 + num9;
                                        flag = false;
                                    }
                                    else if (num6 < MapHelper.dirtPosition)
{
                                        num5 = 6;
                                        flag2 = false;
                                        flag = false;
                                    }
                                    else if (num6 < MapHelper.hellPosition)
{
                                        num5 = 7;
                                        if (num6 < MapHelper.rockPosition)
{
                                            num6 -= MapHelper.dirtPosition;
                                        }
                                        else
{
                                            num6 -= MapHelper.rockPosition;
                                        }
                                    }
                                    else
{
                                        num5 = 6;
                                        flag = false;
                                    }
                                    if (mapTile.Light == 255)
{
                                        flag2 = false;
                                    }
                                    if (flag2)
{
                                        num7 = 0;
                                        int num8 = k + 1;
                                        int l = Main.maxTilesX - k - 1;
                                        num3 = num8;
                                        while (l > 0)
{
                                            if (!mapTile.EqualsWithoutLight(Main.Map[num8, j]))
{
                                                num4 = num8;
                                                break;
                                            }
                                            l--;
                                            num7++;
                                            num8++;
                                        }
                                    }
                                    else
{
                                        num7 = 0;
                                        int num8 = k + 1;
                                        int l = Main.maxTilesX - k - 1;
                                        while (l > 0 && mapTile.Equals(Main.Map[num8, j]))
{
                                            l--;
                                            num7++;
                                            num8++;
                                        }
                                    }
                                }
                                if (b6 > 0)
{
                                    b3 |= (byte)(b6 << 1);
                                }
                                if (b5 != 0)
{
                                    b3 |= 1;
                                }
                                if (b3 != 0)
{
                                    b4 |= 1;
                                }
                                b4 |= (byte)(num5 << 1);
                                if (flag && num6 > 255)
{
                                    b4 |= 16;
                                }
                                if (flag2)
{
                                    b4 |= 32;
                                }
                                if (num7 > 0)
{
                                    if (num7 > 255)
{
                                        b4 |= 128;
                                    }
                                    else
{
                                        b4 |= 64;
                                    }
                                }
                                array[num] = b4;
                                num++;
                                if (b3 != 0)
{
                                    array[num] = b3;
                                    num++;
                                }
                                if (b5 != 0)
{
                                    array[num] = b5;
                                    num++;
                                }
                                if (flag)
{
                                    array[num] = (byte)num6;
                                    num++;
                                    if (num6 > 255)
{
                                        array[num] = (byte)(num6 >> 8);
                                        num++;
                                    }
                                }
                                if (flag2)
{
                                    array[num] = mapTile.Light;
                                    num++;
                                }
                                if (num7 > 0)
{
                                    array[num] = (byte)num7;
                                    num++;
                                    if (num7 > 255)
{
                                        array[num] = (byte)(num7 >> 8);
                                        num++;
                                    }
                                }
                                for (int m = num3; m < num4; m++)
{
                                    array[num] = Main.Map[m, j].Light;
                                    num++;
                                }
                                k += num7;
                                if (num >= 4096)
{
                                    deflateStream.Write(array, 0, num);
                                    num = 0;
                                }
                            }
                        }
                        if (num > 0)
{
                            deflateStream.Write(array, 0, num);
                        }
                        deflateStream.Dispose();
                        FileUtilities.WriteAllBytes(text, memoryStream.ToArray(), isCloudSave);
                    }
                }
            }
            MapHelper.noStatusText = false;
        }
References Terraria.Main.ActivePlayerFileData, System.array, Terraria.Map.MapTile.Color, Terraria.ID.TileID.Count, Terraria.ID.WallID.Count, System.IO.Path.DirectorySeparatorChar, Terraria.Map.MapHelper.dirtPosition, Ionic.Zlib.DeflateStream.Dispose(), Terraria.Map.MapTile.Equals(), Terraria.Map.MapTile.EqualsWithoutLight(), System.IO.BinaryWriter.Flush(), Terraria.Main.gameMenu, Terraria.Lang.gen, Terraria.Map.MapHelper.hellPosition, Terraria.IO.FileMetadata.IncrementAndWrite(), int, Terraria.IO.FileData.IsCloudSave, Terraria.Map.MapTile.Light, Terraria.Map.MapHelper.liquidPosition, Terraria.Main.Map, Terraria.Main.MapFileMetadata, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Map.MapHelper.noStatusText, Terraria.Main.playerPathName, Terraria.Map.MapHelper.rockPosition, Terraria.Map.MapHelper.skyPosition, System.text, Terraria.Map.MapHelper.tileOptionCounts, Terraria.Map.MapHelper.tilePosition, System.IO.MemoryStream.ToArray(), Terraria.Utils.TryCreatingDirectory(), Terraria.Map.MapTile.Type, Terraria.Map.MapHelper.wallOptionCounts, Terraria.Map.MapHelper.wallPosition, Terraria.Main.worldID, Terraria.Main.worldName, Ionic.Zlib.DeflateStream.Write(), System.IO.BinaryWriter.Write(), and Terraria.Utilities.FileUtilities.WriteAllBytes().
Referenced by Terraria.Map.MapHelper.SaveMap().