Terraria Decompiled: Microsoft.Xna.Framework.Graphics.EffectPass.Apply
Apply()
void Microsoft.Xna.Framework.Graphics.EffectPass.Apply () inline
Definition at line 54 of file EffectPass.cs.
        {
            if (this.parentTechnique != this.parentEffect.CurrentTechnique.TechniquePointer)
            {
                throw new InvalidOperationException("Applied a pass not in the current technique!");
            }
            this.parentEffect.OnApply();
            this.parentEffect.INTERNAL_applyEffect(this.pass);
        }
References Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Microsoft.Xna.Framework.Graphics.Effect.INTERNAL_applyEffect(), Microsoft.Xna.Framework.Graphics.Effect.OnApply(), Microsoft.Xna.Framework.Graphics.EffectPass.parentEffect, Microsoft.Xna.Framework.Graphics.EffectPass.parentTechnique, Microsoft.Xna.Framework.Graphics.EffectPass.pass, and Microsoft.Xna.Framework.Graphics.EffectTechnique.TechniquePointer.
Referenced by Terraria.Graphics.Shaders.ShaderData.Apply(), Microsoft.Xna.Framework.Graphics.ModelMesh.Draw(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawLensFlare(), Microsoft.Xna.Framework.Graphics.SpriteBatch.DrawPrimitives(), Terraria.GameContent.AnOutlinedDrawRenderTargetContent.HandleUseRequest(), and Microsoft.Xna.Framework.Graphics.SpriteBatch.PrepRenderState().