Terraria Decompiled: Terraria.StrayMethods.SendWalker
SendWalker()
static void Terraria.StrayMethods.SendWalker (Point startFloorPosition, int height, int direction, out int distanceCoveredInTiles, out Point lastIteratedFloorSpot, int maxDistance = 100, bool showDebug = false) inline static
Definition at line 123 of file StrayMethods.cs.
        {
            distanceCoveredInTiles = 0;
            startFloorPosition.Y--;
            lastIteratedFloorSpot = startFloorPosition;
            for (int i = 0; i < maxDistance; i++)
            {
                int num = 0;
                while (num < 3 && WorldGen.SolidTile3(startFloorPosition.X, startFloorPosition.Y))
                {
                    startFloorPosition.Y--;
                    num++;
                }
                int num2;
                int num3;
                Collision.ExpandVertically(startFloorPosition.X, startFloorPosition.Y, out num2, out num3, height, 2);
                num2++;
                num3--;
                if (!WorldGen.SolidTile3(startFloorPosition.X, num3 + 1))
                {
                    int num4;
                    int num5;
                    Collision.ExpandVertically(startFloorPosition.X, num3, out num4, out num5, 0, 6);
                    if (showDebug)
                    {
                        Dust.QuickBox(new Vector2((float)(startFloorPosition.X * 16 + 8), (float)(num4 * 16)), new Vector2((float)(startFloorPosition.X * 16 + 8), (float)(num5 * 16)), 1, Color.Blue, 1f, 1f, null);
                    }
                    if (!WorldGen.SolidTile3(startFloorPosition.X, num5))
                    {
                        break;
                    }
                }
                if (num3 - num2 < height - 1)
                {
                    break;
                }
                if (showDebug)
                {
                    Dust.QuickDust(startFloorPosition, Color.Green).scale = 1f;
                    Dust.QuickBox(new Vector2((float)(startFloorPosition.X * 16 + 8), (float)(num2 * 16)), new Vector2((float)(startFloorPosition.X * 16 + 8), (float)(num3 * 16 + 16)), 1, Color.Red, 1f, 1f, null);
                }
                distanceCoveredInTiles += direction;
                startFloorPosition.X += direction;
                startFloorPosition.Y = num3;
                lastIteratedFloorSpot = startFloorPosition;
                if (Math.Abs(distanceCoveredInTiles) >= maxDistance)
                {
                    break;
                }
            }
            distanceCoveredInTiles = Math.Abs(distanceCoveredInTiles);
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Color.Blue, Terraria.Collision.ExpandVertically(), Microsoft.Xna.Framework.Color.Green, Terraria.Dust.QuickBox(), Terraria.Dust.QuickDust(), Microsoft.Xna.Framework.Color.Red, Terraria.Dust.scale, Terraria.WorldGen.SolidTile3(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.StrayMethods.CheckArenaScore().