Terraria Decompiled: NVorbis.Contracts.IPacket.SkipBits
SkipBits()
void NVorbis.Contracts.IPacket.SkipBits (int count)
Implemented in NVorbis.DataPacket.
Referenced by NVorbis.Codebook.DecodeScalar(), NVorbis.Mapping.Init(), NVorbis.StreamDecoder.LoadBooks(), NVorbis.Extensions.Read(), and NVorbis.Extensions.SkipBytes().