Terraria Decompiled: NVorbis.Contracts.IPacket.ReadBits
ReadBits()
ulong NVorbis.Contracts.IPacket.ReadBits (int count)
Implemented in NVorbis.DataPacket.
Referenced by NVorbis.Factory.CreateFloor(), NVorbis.Factory.CreateMapping(), NVorbis.Factory.CreateResidue(), NVorbis.StreamDecoder.DecodeNextPacket(), NVorbis.StreamDecoder.GetInvalidStreamException(), NVorbis.StreamDecoder.GetPacketGranules(), NVorbis.Codebook.Init(), NVorbis.Residue0.Init(), NVorbis.Mapping.Init(), NVorbis.Floor0.Init(), NVorbis.Floor1.Init(), NVorbis.Mode.Init(), NVorbis.Codebook.InitLookupTable(), NVorbis.Codebook.InitTree(), NVorbis.StreamDecoder.LoadBooks(), NVorbis.StreamDecoder.LoadComments(), NVorbis.StreamDecoder.LoadStreamHeader(), NVorbis.Extensions.ReadBit(), NVorbis.Extensions.ReadByte(), NVorbis.Extensions.ReadInt16(), NVorbis.Extensions.ReadInt32(), NVorbis.Extensions.ReadInt64(), NVorbis.StreamDecoder.ReadString(), NVorbis.Extensions.ReadUInt16(), NVorbis.Extensions.ReadUInt32(), NVorbis.Extensions.ReadUInt64(), NVorbis.Floor0.Unpack(), NVorbis.Floor1.Unpack(), and NVorbis.StreamDecoder.ValidateHeader().