Terraria Decompiled: Terraria.GameContent.ItemDropRules.Chains.ReportDroprates
ReportDroprates()
static void Terraria.GameContent.ItemDropRules.Chains.ReportDroprates (List< IItemDropRuleChainAttempt > ChainedRules, float personalDropRate, List< DropRateInfo > drops, DropRateInfoChainFeed ratesInfo) inline static
Definition at line 11 of file Chains.cs.
        {
            foreach (IItemDropRuleChainAttempt itemDropRuleChainAttempt in ChainedRules)
            {
                itemDropRuleChainAttempt.ReportDroprates(personalDropRate, drops, ratesInfo);
            }
        }
References Terraria.GameContent.ItemDropRules.IItemDropRuleChainAttempt.ReportDroprates().
Referenced by Terraria.GameContent.ItemDropRules.CommonDrop.ReportDroprates(), Terraria.GameContent.ItemDropRules.CommonDropWithRerolls.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnExpertMode.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnExtraGel.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnMasterAndExpertMode.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropBasedOnMasterMode.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropNothing.ReportDroprates(), Terraria.GameContent.ItemDropRules.DropOneByOne.ReportDroprates(), Terraria.GameContent.ItemDropRules.FromOptionsWithoutRepeatsDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.ItemDropWithConditionRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.LeadingConditionRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.MechBossSpawnersDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.OneFromOptionsDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.OneFromOptionsNotScaledWithLuckDropRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.OneFromRulesRule.ReportDroprates(), Terraria.GameContent.ItemDropRules.SlimeBodyItemDropRule.ReportDroprates(), and Terraria.GameContent.ItemDropRules.StatueMimicItemDropRule.ReportDroprates().