Terraria Decompiled: System.TimeZoneInfo.StringSerializer.GetSerializedString
GetSerializedString()
static string System.TimeZoneInfo.StringSerializer.GetSerializedString (TimeZoneInfo zone) inline static
Definition at line 2804 of file TimeZoneInfo.cs.
            {
                StringBuilder stringBuilder = StringBuilderCache.Acquire(16);
                TimeZoneInfo.StringSerializer.SerializeSubstitute(zone.Id, stringBuilder);
                stringBuilder.Append(';');
                stringBuilder.Append(zone.BaseUtcOffset.TotalMinutes.ToString(CultureInfo.InvariantCulture));
                stringBuilder.Append(';');
                TimeZoneInfo.StringSerializer.SerializeSubstitute(zone.DisplayName, stringBuilder);
                stringBuilder.Append(';');
                TimeZoneInfo.StringSerializer.SerializeSubstitute(zone.StandardName, stringBuilder);
                stringBuilder.Append(';');
                TimeZoneInfo.StringSerializer.SerializeSubstitute(zone.DaylightName, stringBuilder);
                stringBuilder.Append(';');
                foreach (TimeZoneInfo.AdjustmentRule adjustmentRule in zone.GetAdjustmentRules())
                {
                    stringBuilder.Append('[');
                    stringBuilder.Append(adjustmentRule.DateStart.ToString("MM:dd:yyyy", DateTimeFormatInfo.InvariantInfo));
                    stringBuilder.Append(';');
                    stringBuilder.Append(adjustmentRule.DateEnd.ToString("MM:dd:yyyy", DateTimeFormatInfo.InvariantInfo));
                    stringBuilder.Append(';');
                    stringBuilder.Append(adjustmentRule.DaylightDelta.TotalMinutes.ToString(CultureInfo.InvariantCulture));
                    stringBuilder.Append(';');
                    TimeZoneInfo.StringSerializer.SerializeTransitionTime(adjustmentRule.DaylightTransitionStart, stringBuilder);
                    stringBuilder.Append(';');
                    TimeZoneInfo.StringSerializer.SerializeTransitionTime(adjustmentRule.DaylightTransitionEnd, stringBuilder);
                    stringBuilder.Append(';');
                    if (adjustmentRule.BaseUtcOffsetDelta != TimeSpan.Zero)
                    {
                        stringBuilder.Append(adjustmentRule.BaseUtcOffsetDelta.TotalMinutes.ToString(CultureInfo.InvariantCulture));
                        stringBuilder.Append(';');
                    }
                    if (adjustmentRule.NoDaylightTransitions)
                    {
                        stringBuilder.Append('1');
                        stringBuilder.Append(';');
                    }
                    stringBuilder.Append(']');
                }
                stringBuilder.Append(';');
                return StringBuilderCache.GetStringAndRelease(stringBuilder);
            }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), System.TimeZoneInfo.BaseUtcOffset, System.TimeZoneInfo.DaylightName, System.TimeZoneInfo.DisplayName, System.TimeZoneInfo.GetAdjustmentRules(), System.Text.StringBuilderCache.GetStringAndRelease(), System.TimeZoneInfo.Id, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.DateTimeFormatInfo.InvariantInfo, System.TimeZoneInfo.StringSerializer.SerializeSubstitute(), System.TimeZoneInfo.StringSerializer.SerializeTransitionTime(), System.TimeZoneInfo.StandardName, System.TimeSpan.TotalMinutes, and System.TimeSpan.Zero.
Referenced by System.TimeZoneInfo.ToSerializedString().