Terraria Decompiled: System.TimeZoneInfo.StringSerializer.GetNextStringValue
GetNextStringValue()
string System.TimeZoneInfo.StringSerializer.GetNextStringValue () inline private
Definition at line 2978 of file TimeZoneInfo.cs.
            {
                if (this._state == TimeZoneInfo.StringSerializer.State.EndOfLine)
                {
                    throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.");
                }
                if (this._currentTokenStartIndex < 0 || this._currentTokenStartIndex >= this._serializedText.Length)
                {
                    throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.");
                }
                TimeZoneInfo.StringSerializer.State state = TimeZoneInfo.StringSerializer.State.NotEscaped;
                StringBuilder stringBuilder = StringBuilderCache.Acquire(64);
                for (int i = this._currentTokenStartIndex; i < this._serializedText.Length; i++)
                {
                    if (state == TimeZoneInfo.StringSerializer.State.Escaped)
                    {
                        TimeZoneInfo.StringSerializer.VerifyIsEscapableCharacter(this._serializedText[i]);
                        stringBuilder.Append(this._serializedText[i]);
                        state = TimeZoneInfo.StringSerializer.State.NotEscaped;
                    }
                    else if (state == TimeZoneInfo.StringSerializer.State.NotEscaped)
                    {
                        char c = this._serializedText[i];
                        if (c == '\0')
{
                            throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.");
                        }
                        if (c == ';')
{
                            this._currentTokenStartIndex = i + 1;
                            if (this._currentTokenStartIndex >= this._serializedText.Length)
{
                                this._state = TimeZoneInfo.StringSerializer.State.EndOfLine;
                            }
                            else
{
                                this._state = TimeZoneInfo.StringSerializer.State.StartOfToken;
                            }
                            return StringBuilderCache.GetStringAndRelease(stringBuilder);
                        }
                        switch (c)
{
                        case '[':
                            throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.");
                        case '\\':
                            state = TimeZoneInfo.StringSerializer.State.Escaped;
                            break;
                        case ']':
                            throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.");
                        default:
                            stringBuilder.Append(this._serializedText[i]);
                            break;
                        }
                    }
                }
                if (state == TimeZoneInfo.StringSerializer.State.Escaped)
                {
                    throw new SerializationException(SR.Format("The serialized data contained an invalid escape sequence '\\\\{0}'.", string.Empty));
                }
                throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.");
            }
References System.Text.StringBuilderCache.Acquire(), System.Text.StringBuilder.Append(), SR.Format(), System.Text.StringBuilderCache.GetStringAndRelease(), System.state, and System.TimeZoneInfo.StringSerializer.VerifyIsEscapableCharacter().
Referenced by System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo().