Terraria Decompiled: System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo
GetDeserializedTimeZoneInfo()
static TimeZoneInfo System.TimeZoneInfo.StringSerializer.GetDeserializedTimeZoneInfo (string source) inline static
Definition at line 2847 of file TimeZoneInfo.cs.
            {
                TimeZoneInfo.StringSerializer stringSerializer = new TimeZoneInfo.StringSerializer(source);
                string nextStringValue = stringSerializer.GetNextStringValue();
                TimeSpan nextTimeSpanValue = stringSerializer.GetNextTimeSpanValue();
                string nextStringValue2 = stringSerializer.GetNextStringValue();
                string nextStringValue3 = stringSerializer.GetNextStringValue();
                string nextStringValue4 = stringSerializer.GetNextStringValue();
                TimeZoneInfo.AdjustmentRule[] nextAdjustmentRuleArrayValue = stringSerializer.GetNextAdjustmentRuleArrayValue();
                TimeZoneInfo timeZoneInfo;
                try
                {
                    timeZoneInfo = new TimeZoneInfo(nextStringValue, nextTimeSpanValue, nextStringValue2, nextStringValue3, nextStringValue4, nextAdjustmentRuleArrayValue, false);
                }
                catch (ArgumentException ex)
                {
                    throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.", ex);
                }
                catch (InvalidTimeZoneException ex2)
                {
                    throw new SerializationException("An error occurred while deserializing the object.  The serialized data is corrupt.", ex2);
                }
                return timeZoneInfo;
            }
References System.TimeZoneInfo.StringSerializer.GetNextAdjustmentRuleArrayValue(), System.TimeZoneInfo.StringSerializer.GetNextStringValue(), System.TimeZoneInfo.StringSerializer.GetNextTimeSpanValue(), and System.source.
Referenced by System.TimeZoneInfo.FromSerializedString().