Terraria Decompiled: Terraria.Social.WeGame.Lobby.Create
Create()
void Terraria.Social.WeGame.Lobby.Create (bool inviteOnly) inline
Definition at line 70 of file Lobby.cs.
        {
            if (this.State == LobbyState.Inactive)
            {
                this.RegisterGameServerEvent();
            }
            IRailGameServer railGameServer = rail_api.RailFactory().RailGameServerHelper().AsyncCreateGameServer(new CreateGameServerOptions
            {
                has_password = false,
                enable_team_voice = false
            }, "terraria", "terraria");
            this.RailServerHelper = railGameServer;
            this.State = LobbyState.Creating;
        }
References rail.IRailGameServerHelper.AsyncCreateGameServer(), rail.rail_api.RailFactory(), rail.IRailFactory.RailGameServerHelper(), Terraria.Social.WeGame.Lobby.RegisterGameServerEvent(), and Terraria.Social.WeGame.Lobby.State.
Referenced by Terraria.Social.WeGame.NetServerSocialModule.Initialize().