Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.TryMakeRegularRoomOnLine
TryMakeRegularRoomOnLine()
bool Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.TryMakeRegularRoomOnLine (DungeonData data, DungeonControlLine line, double normalizedDistanceAlong, double normalizedDistanceFrom, out DungeonRoom room) inline private
Definition at line 186 of file DualDungeonLayoutProvider.cs.
        {
            int num = 10;
            DungeonRoomSettings dungeonRoomSettings = DungeonCrawler.MakeDungeon_GetRoomSettings(DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralRoomType(WorldGen.genRand), data, line);
            int boundingRadius = dungeonRoomSettings.GetBoundingRadius();
            SnakeOrientation orientation = dungeonRoomSettings.Orientation;
            Point point = data.genVars.dungeonDitherSnake.GetRoomPositionInsideBorder(line, normalizedDistanceAlong, normalizedDistanceFrom, boundingRadius, out orientation).ToPoint();
            dungeonRoomSettings.Orientation = orientation;
            dungeonRoomSettings.RoomPosition = new Point(point.X, point.Y);
            room = DungeonCrawler.MakeDungeon_TryRoom(data, point.X, point.Y, dungeonRoomSettings, true, boundingRadius + num, true);
            if (room == null)
            {
                return false;
            }
            room.CalculateRoom(data);
            return true;
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculateRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.DualDungeonLayout_GetGeneralRoomType(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonDitherSnake, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.GetBoundingRadius(), Terraria.GameContent.Biomes.DitherSnake.GetRoomPositionInsideBorder(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_TryRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.Orientation, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms().