Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedRooms
ConvertSpecializedRooms()
void Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedRooms (DungeonData data, List< DungeonRoom > rooms) inline
Definition at line 303 of file DualDungeonLayoutProvider.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            DitherSnake dungeonDitherSnake = data.genVars.dungeonDitherSnake;
            int num = 2;
            int num2 = 2;
            int num3 = 2;
            int num4 = 2;
            int num5 = 5;
            int num6 = 6;
            switch (WorldGen.GetWorldSize())
            {
            case 0:
                num = 2;
                num2 = 2;
                num3 = 2;
                num4 = 2;
                num5 = 5;
                num6 = 6;
                break;
            case 1:
                num = 4;
                num2 = 6;
                num3 = 6;
                num4 = 6;
                num5 = 8;
                num6 = 10;
                break;
            case 2:
                num = 6;
                num2 = 10;
                num3 = 10;
                num4 = 8;
                num5 = 11;
                num6 = 14;
                break;
            }
            List<DungeonRoom> list = new List<DungeonRoom>();
            List<DungeonRoom> list2 = new List<DungeonRoom>();
            List<DungeonRoom> list3 = new List<DungeonRoom>();
            foreach (DungeonRoom dungeonRoom in rooms)
            {
                byte style = dungeonRoom.settings.StyleData.Style;
                if (style != 1)
                {
                    if (style != 6)
                    {
                        if (style == 8)
{
                            list2.Add(dungeonRoom);
                        }
                    }
                    else
                    {
                        list3.Add(dungeonRoom);
                    }
                }
                else
                {
                    list.Add(dungeonRoom);
                }
            }
            List<DungeonRoom> list4 = list.ToList<DungeonRoom>();
            int count = list4.Count;
            int num7 = 2000;
            while (num7 > 0 && list4.Count > 0 && num > 0)
            {
                num7--;
                if (num7 <= 0)
                {
                    break;
                }
                DungeonRoom dungeonRoom2 = list4[genRand.Next(list4.Count)];
                if (dungeonRoom2.settings.OnCurvedLine || dungeonRoom2.settings.Orientation != SnakeOrientation.Bottom)
                {
                    list4.Remove(dungeonRoom2);
                }
                else if (dungeonRoom2.settings is GenShapeDungeonRoomSettings && ((GenShapeDungeonRoomSettings)dungeonRoom2.settings).ShapeType == GenShapeType.Doughnut)
                {
                    list4.Remove(dungeonRoom2);
                }
                else if (dungeonRoom2.GetFloodedRoomTileCount() < SceneMetrics.ShimmerTileThreshold)
                {
                    list4.Remove(dungeonRoom2);
                }
                else
                {
                    dungeonRoom2.settings.StyleData = DungeonGenerationStyles.Shimmer;
                    dungeonRoom2.settings.HallwayConnectionPointOverride = new DungeonUtils.GetHallwayConnectionPoint(DualDungeonLayoutProvider.ConnectToTopOfRoomOnly);
                    num--;
                    list.Remove(dungeonRoom2);
                    list4.Remove(dungeonRoom2);
                }
            }
            if (num > 0)
            {
                list4 = list.ToList<DungeonRoom>();
                int count2 = list4.Count;
                num7 = 2000;
                while (num7 > 0 && list4.Count > 0 && num > 0)
                {
                    num7--;
                    if (num7 <= 0)
                    {
                        break;
                    }
                    DungeonRoom dungeonRoom3 = list4[genRand.Next(list4.Count)];
                    if (dungeonRoom3.settings.OnCurvedLine || dungeonRoom3.settings.Orientation != SnakeOrientation.Bottom)
                    {
                        list4.Remove(dungeonRoom3);
                    }
                    else if (dungeonRoom3.settings is GenShapeDungeonRoomSettings && ((GenShapeDungeonRoomSettings)dungeonRoom3.settings).ShapeType == GenShapeType.Doughnut)
                    {
                        list4.Remove(dungeonRoom3);
                    }
                    else
                    {
                        dungeonRoom3.settings.StyleData = DungeonGenerationStyles.Shimmer;
                        dungeonRoom3.settings.HallwayConnectionPointOverride = new DungeonUtils.GetHallwayConnectionPoint(DualDungeonLayoutProvider.ConnectToTopOfRoomOnly);
                        num--;
                        list.Remove(dungeonRoom3);
                        list4.Remove(dungeonRoom3);
                    }
                }
            }
            list4 = list.ToList<DungeonRoom>();
            num7 = 2000;
            while (num7 > 0 && list4.Count > 0 && num2 > 0)
            {
                num7--;
                if (num7 <= 0)
                {
                    break;
                }
                DungeonRoom dungeonRoom4 = list4[genRand.Next(list4.Count)];
                if (dungeonRoom4.settings.OnCurvedLine)
                {
                    list4.Remove(dungeonRoom4);
                }
                else
                {
                    DungeonControlLine controlLine = dungeonRoom4.settings.ControlLine;
                    DungeonRoomSettings dungeonRoomSettings = DungeonCrawler.MakeDungeon_GetRoomSettings(DungeonRoomType.LivingTree, data, controlLine);
                    dungeonRoomSettings.RoomPosition = new Point(dungeonRoom4.settings.RoomPosition.X, dungeonRoom4.settings.RoomPosition.Y);
                    if (dungeonDitherSnake.IsCircleInsideBorderWithMatchingStyle(controlLine, dungeonRoomSettings.RoomPosition, dungeonRoomSettings.GetBoundingRadius()))
                    {
                        int num8 = data.dungeonRooms.IndexOf(dungeonRoom4);
                        int num9 = rooms.IndexOf(dungeonRoom4);
                        list.Remove(dungeonRoom4);
                        list4.Remove(dungeonRoom4);
                        rooms.Remove(dungeonRoom4);
                        data.dungeonRooms.Remove(dungeonRoom4);
                        dungeonRoom4 = DungeonCrawler.MakeDungeon_GetRoom(dungeonRoomSettings, false);
                        dungeonRoom4.CalculateRoom(data);
                        if (num8 > -1)
{
                            data.dungeonRooms.Insert(num8, dungeonRoom4);
                        }
                        else
{
                            data.dungeonRooms.Add(dungeonRoom4);
                        }
                        if (num9 > -1)
{
                            rooms.Insert(num9, dungeonRoom4);
                        }
                        else
{
                            rooms.Add(dungeonRoom4);
                        }
                        dungeonRoom4.settings.StyleData = DungeonGenerationStyles.LivingWood;
                        dungeonRoom4.settings.HallwayConnectionPointOverride = new DungeonUtils.GetHallwayConnectionPoint(DualDungeonLayoutProvider.ConnectToBottomOfRoomOnly);
                        num2--;
                    }
                }
            }
            list4 = list.ToList<DungeonRoom>();
            num7 = 2000;
            while (num7 > 0 && list4.Count > 0 && num4 > 0)
            {
                num7--;
                if (num7 <= 0)
                {
                    break;
                }
                DungeonRoom dungeonRoom5 = list4[genRand.Next(list4.Count)];
                if (dungeonRoom5.settings.OnCurvedLine)
                {
                    list4.Remove(dungeonRoom5);
                }
                else
                {
                    dungeonRoom5.settings.StyleData = DungeonGenerationStyles.Spider;
                    num4--;
                    list.Remove(dungeonRoom5);
                    list4.Remove(dungeonRoom5);
                }
            }
            list4 = list2.ToList<DungeonRoom>();
            num7 = 2000;
            while (num7 > 0 && list4.Count > 0 && num5 > 0)
            {
                num7--;
                if (num7 <= 0)
                {
                    break;
                }
                DungeonRoom dungeonRoom6 = list4[genRand.Next(list4.Count)];
                if (dungeonRoom6.settings.OnCurvedLine || dungeonRoom6.settings.Orientation != SnakeOrientation.Bottom)
                {
                    list4.Remove(dungeonRoom6);
                }
                else if (dungeonRoom6.settings is GenShapeDungeonRoomSettings && ((GenShapeDungeonRoomSettings)dungeonRoom6.settings).ShapeType == GenShapeType.Doughnut)
                {
                    list4.Remove(dungeonRoom6);
                }
                else
                {
                    dungeonRoom6.settings.StyleData = DungeonGenerationStyles.Beehive;
                    dungeonRoom6.settings.HallwayConnectionPointOverride = new DungeonUtils.GetHallwayConnectionPoint(DualDungeonLayoutProvider.ConnectToTopOfRoomOnly);
                    num5--;
                    list2.Remove(dungeonRoom6);
                    list4.Remove(dungeonRoom6);
                }
            }
            list4 = list2.ToList<DungeonRoom>();
            num7 = 2000;
            while (num7 > 0 && list4.Count > 0 && num3 > 0)
            {
                num7--;
                if (num7 <= 0)
                {
                    break;
                }
                DungeonRoom dungeonRoom7 = list4[genRand.Next(list4.Count)];
                if (dungeonRoom7.settings.OnCurvedLine)
                {
                    list4.Remove(dungeonRoom7);
                }
                else
                {
                    DungeonControlLine controlLine2 = dungeonRoom7.settings.ControlLine;
                    DungeonRoomSettings dungeonRoomSettings2 = DungeonCrawler.MakeDungeon_GetRoomSettings(DungeonRoomType.LivingTree, data, controlLine2);
                    dungeonRoomSettings2.RoomPosition = new Point(dungeonRoom7.settings.RoomPosition.X, dungeonRoom7.settings.RoomPosition.Y);
                    if (dungeonDitherSnake.IsCircleInsideBorderWithMatchingStyle(controlLine2, dungeonRoomSettings2.RoomPosition, dungeonRoomSettings2.GetBoundingRadius()))
                    {
                        int num10 = data.dungeonRooms.IndexOf(dungeonRoom7);
                        int num11 = rooms.IndexOf(dungeonRoom7);
                        list.Remove(dungeonRoom7);
                        list4.Remove(dungeonRoom7);
                        rooms.Remove(dungeonRoom7);
                        data.dungeonRooms.Remove(dungeonRoom7);
                        dungeonRoom7 = DungeonCrawler.MakeDungeon_GetRoom(dungeonRoomSettings2, false);
                        dungeonRoom7.CalculateRoom(data);
                        if (num10 > -1)
{
                            data.dungeonRooms.Insert(num10, dungeonRoom7);
                        }
                        else
{
                            data.dungeonRooms.Add(dungeonRoom7);
                        }
                        if (num11 > -1)
{
                            rooms.Insert(num11, dungeonRoom7);
                        }
                        else
{
                            rooms.Add(dungeonRoom7);
                        }
                        dungeonRoom7.settings.StyleData = DungeonGenerationStyles.LivingMahogany;
                        dungeonRoom7.settings.HallwayConnectionPointOverride = new DungeonUtils.GetHallwayConnectionPoint(DualDungeonLayoutProvider.ConnectToBottomOfRoomOnly);
                        num3--;
                    }
                }
            }
            list4 = list3.ToList<DungeonRoom>();
            num7 = 2000;
            while (num7 > 0 && list4.Count > 0 && num6 > 0)
            {
                num7--;
                if (num7 <= 0)
                {
                    break;
                }
                DungeonRoom dungeonRoom8 = list4[genRand.Next(list4.Count)];
                if (dungeonRoom8.settings.OnCurvedLine)
                {
                    list4.Remove(dungeonRoom8);
                }
                else
                {
                    dungeonRoom8.settings.StyleData = DungeonGenerationStyles.Crystal;
                    num6--;
                    list3.Remove(dungeonRoom8);
                    list4.Remove(dungeonRoom8);
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Beehive, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculateRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConnectToBottomOfRoomOnly(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConnectToTopOfRoomOnly(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.ControlLine, System.Collections.Generic.List< T >.Count, System.count, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Crystal, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonDitherSnake, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.GetBoundingRadius(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetFloodedRoomTileCount(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GetHallwayConnectionPoint(), Terraria.WorldGen.GetWorldSize(), System.list, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.LivingMahogany, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.LivingWood, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.OnCurvedLine, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.Orientation, System.Collections.Generic.List< T >.Remove(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.RoomPosition, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoomSettings.ShapeType, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Shimmer, Terraria.SceneMetrics.ShimmerTileThreshold, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Spider, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().