Terraria Decompiled: CsvHelper.ReflectionHelper.CreateInstance
CreateInstance()
static object CsvHelper.ReflectionHelper.CreateInstance (Type type, params object[] args) inline static
Definition at line 21 of file ReflectionHelper.cs.
        {
            Type[] array = Enumerable.ToArray<Type>(Enumerable.Select<object, Type>(args, (object a) => a.GetType()));
            ParameterExpression[] array2 = Enumerable.ToArray<ParameterExpression>(Enumerable.Select<Type, ParameterExpression>(array, (Type t, int i) => Expression.Parameter(t, "var" + i)));
            Delegate @delegate = Expression.Lambda(Expression.New(type.GetConstructor(array), array2), array2).Compile();
            object obj;
            try
            {
                obj = @delegate.DynamicInvoke(args);
            }
            catch (TargetInvocationException ex)
            {
                throw ex.InnerException;
            }
            return obj;
        }
References System.array, System.Delegate.DynamicInvoke(), System.Type.GetConstructor(), System.Exception.InnerException, and System.obj.
Referenced by CsvHelper.Configuration.CsvConfiguration.AutoMap(), CsvHelper.Configuration.CsvClassMap< T >.AutoMapInternal(), CsvHelper.ReflectionHelper.CreateInstance< T >(), CsvHelper.CsvReader.GetField< T, TConverter >(), CsvHelper.CsvReader.GetField< T, TConverter >(), CsvHelper.CsvReader.GetField< T, TConverter >(), CsvHelper.Configuration.CsvClassMap< T >.References(), CsvHelper.Configuration.CsvClassMap< T >.References< TClassMap >(), CsvHelper.Configuration.CsvConfiguration.RegisterClassMap(), CsvHelper.Configuration.CsvConfiguration.RegisterClassMap< TMap >(), CsvHelper.CsvReader.TryGetField< T, TConverter >(), CsvHelper.CsvReader.TryGetField< T, TConverter >(), CsvHelper.CsvReader.TryGetField< T, TConverter >(), and CsvHelper.Configuration.CsvPropertyMap.TypeConverter< T >().