Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceHall
CalculateEntranceHall()
DungeonHall Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceHall (DungeonData data, DungeonRoom entranceRoom, DungeonRoom startingRoom) inline private
Definition at line 121 of file DualDungeonLayoutProvider.cs.
        {
            StairwellDungeonHallSettings stairwellDungeonHallSettings = (StairwellDungeonHallSettings)DungeonCrawler.MakeDungeon_GetHallSettings(DungeonHallType.Stairwell, data, Vector2.Zero, Vector2.Zero, startingRoom.settings.StyleData);
            stairwellDungeonHallSettings.IsEntranceHall = true;
            DungeonHall dungeonHall = DungeonCrawler.MakeDungeon_GetHall(stairwellDungeonHallSettings, true);
            Vector2D vector2D;
            Vector2D vector2D2;
            DualDungeonLayoutProvider.GetHallwayConnectionPoints(entranceRoom, startingRoom, out vector2D, out vector2D2);
            dungeonHall.CalculateHall(data, vector2D, vector2D2);
            return dungeonHall;
        }
References Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CalculateHall(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.GetHallwayConnectionPoints(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHall(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetHallSettings(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().