Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceRoom
CalculateEntranceRoom()
static DungeonRoom Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceRoom (DungeonData data) inline static private
Definition at line 234 of file DualDungeonLayoutProvider.cs.
        {
            DungeonBounds outerPotentialDungeonBounds = data.genVars.outerPotentialDungeonBounds;
            if (data.genVars.generatingDungeonPositionY > outerPotentialDungeonBounds.Top - 10)
            {
                data.genVars.generatingDungeonPositionY = outerPotentialDungeonBounds.Top - 10;
            }
            if (data.genVars.preGenDungeonEntranceSettings.PrecalculateEntrancePosition)
            {
                data.genVars.generatingDungeonPositionX = -10 + (int)data.genVars.dungeonEntrancePosition.X + WorldGen.genRand.Next(20);
                data.genVars.generatingDungeonPositionY = (int)data.genVars.dungeonEntrancePosition.Y + 30;
            }
            if (SpecialSeedFeatures.DungeonEntranceIsBuried)
            {
                data.genVars.generatingDungeonPositionY = (int)Main.worldSurface + 15;
            }
            if (SpecialSeedFeatures.DungeonEntranceIsUnderground)
            {
                data.genVars.generatingDungeonPositionY = (int)GenVars.worldSurfaceHigh + 15;
            }
            DungeonRoom dungeonRoom = DungeonCrawler.MakeDungeon_GetRoom(new LegacyDungeonRoomSettings
            {
                StyleData = data.genVars.dungeonStyle,
                RoomPosition = new Point(data.genVars.generatingDungeonPositionX, data.genVars.generatingDungeonPositionY),
                IsEntranceRoom = true
            }, true);
            dungeonRoom.CalculateRoom(data);
            return dungeonRoom;
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculateRoom(), Terraria.GameContent.SpecialSeedFeatures.DungeonEntranceIsBuried, Terraria.GameContent.SpecialSeedFeatures.DungeonEntranceIsUnderground, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonEntrancePosition, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonStyle, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionX, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.generatingDungeonPositionY, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, int, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.outerPotentialDungeonBounds, Terraria.GameContent.Generation.Dungeon.DungeonGenVars.preGenDungeonEntranceSettings, Terraria.GameContent.Generation.Dungeon.DungeonBounds.Top, Terraria.Main.worldSurface, Terraria.WorldBuilding.GenVars.worldSurfaceHigh, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().