Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateBiomeRooms
CalculateBiomeRooms()
List< DungeonRoom > Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateBiomeRooms (DungeonData data) inline private
Definition at line 134 of file DualDungeonLayoutProvider.cs.
        {
            List<DungeonRoom> list = new List<DungeonRoom>();
            foreach (DungeonControlLine dungeonControlLine in data.genVars.dungeonDitherSnake)
            {
                if (dungeonControlLine.Next == null || dungeonControlLine.Next.ProgressionStage != dungeonControlLine.ProgressionStage)
                {
                    Vector2D vector2D = ((dungeonControlLine.Next != null) ? dungeonControlLine.Start : dungeonControlLine.End);
                    DungeonRoomSettings dungeonRoomSettings = DungeonCrawler.MakeDungeon_GetRoomSettings(dungeonControlLine.Style.BiomeRoomType, data, dungeonControlLine);
                    dungeonRoomSettings.RoomPosition = new Point((int)vector2D.X, (int)vector2D.Y);
                    DungeonRoom dungeonRoom = DungeonCrawler.MakeDungeon_GetRoom(dungeonRoomSettings, true);
                    dungeonRoom.CalculateRoom(data);
                    list.Add(dungeonRoom);
                }
            }
            return list;
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculateRoom(), Terraria.GameContent.Biomes.DungeonControlLine.End, System.list, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoomSettings(), Terraria.GameContent.Biomes.DungeonControlLine.Next, Terraria.GameContent.Biomes.DungeonControlLine.ProgressionStage, Terraria.GameContent.Biomes.DungeonControlLine.Start, Terraria.GameContent.Biomes.DungeonControlLine.Style, ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().