Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateStartingRoom
CalculateStartingRoom()
DungeonRoom Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateStartingRoom (DungeonData data) inline private
Definition at line 101 of file DualDungeonLayoutProvider.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            DungeonControlLine dungeonControlLine = data.genVars.dungeonDitherSnake[0];
            Vector2D start = dungeonControlLine.Start;
            DungeonRoom dungeonRoom = DungeonCrawler.MakeDungeon_GetRoom(new RegularDungeonRoomSettings
            {
                RoomType = DungeonRoomType.Regular,
                RoomPosition = new Point((int)start.X, (int)start.Y),
                RandomSeed = genRand.Next(),
                ProgressionStage = dungeonControlLine.ProgressionStage,
                StyleData = dungeonControlLine.Style,
                OverrideOuterBoundsSize = 8,
                OverrideInnerBoundsSize = (int)(20.0 * data.roomStrengthScalar)
            }, true);
            dungeonRoom.CalculateRoom(data);
            return dungeonRoom;
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.CalculateRoom(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonDitherSnake, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, int, Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon_GetRoom(), Terraria.Utilities.UnifiedRandom.Next(), Terraria.GameContent.Biomes.DungeonControlLine.ProgressionStage, Terraria.GameContent.Generation.Dungeon.DungeonData.roomStrengthScalar, System.start, Terraria.GameContent.Biomes.DungeonControlLine.Start, and Terraria.GameContent.Biomes.DungeonControlLine.Style.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().