Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout
ProvideLayout()
override void Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout (DungeonData data, GenerationProgress progress, UnifiedRandom genRand, ref int roomDelay) inline
Definition at line 26 of file DualDungeonLayoutProvider.cs.
        {
            DungeonRoom dungeonRoom = DualDungeonLayoutProvider.CalculateEntranceRoom(data);
            DungeonRoom dungeonRoom2 = this.CalculateStartingRoom(data);
            this.CalculateEntranceHall(data, dungeonRoom, dungeonRoom2);
            List<DungeonRoom> list = this.CalculateBiomeRooms(data);
            List<DungeonRoom> list2 = this.CalculateRooms(data);
            this.ConvertSpecializedRooms(data, list2);
            List<DungeonHall> list3 = new DualDungeonLayoutProvider.HallwayCalculator(data, list.Concat(list2).Concat(new DungeonRoom[] { dungeonRoom2 }).ToList<DungeonRoom>()).Generate();
            this.ConvertSpecializedHalls(list3);
            DualDungeonLayoutProvider.CalculateDungeonBounds(data, list2.Concat(new DungeonRoom[] { dungeonRoom2 }), list3);
            for (int i = 0; i < data.dungeonRooms.Count; i++)
            {
                double num = Math.Round((double)((float)(i + 1) / (float)data.dungeonRooms.Count * 100f));
                DungeonUtils.UpdateDungeonProgress(progress, Utils.Remap((float)i, 0f, (float)data.dungeonRooms.Count, 0.35f, 0.4f, true), Language.GetTextValue("WorldGeneration.DungeonRooms", num), true);
                data.dungeonRooms[i].GenerateRoom(data);
            }
            for (int j = 0; j < data.dungeonRooms.Count; j++)
            {
                data.dungeonRooms[j].GeneratePreHallwaysDungeonFeaturesInRoom(data);
            }
            List<DungeonHall> list4 = data.dungeonHalls.FindAll(new Predicate<DungeonHall>(DualDungeonLayoutProvider.HallwayCheck_IsCrackedBrickHall));
            List<DungeonHall> list5 = data.dungeonHalls.FindAll(new Predicate<DungeonHall>(DualDungeonLayoutProvider.HallwayCheck_IsSpiderHall));
            int num2 = 0;
            for (int k = 0; k < list4.Count; k++)
            {
                DungeonHall dungeonHall = list4[k];
                double num3 = Math.Round((double)((float)(num2 + 1) / (float)data.dungeonHalls.Count * 100f));
                DungeonUtils.UpdateDungeonProgress(progress, Utils.Remap((float)num2, 0f, (float)data.dungeonHalls.Count, 0.4f, 0.6f, true), Language.GetTextValue("WorldGeneration.DungeonHalls", num3), true);
                if (dungeonHall.calculated)
                {
                    dungeonHall.GenerateHall(data);
                    num2++;
                }
            }
            for (int l = 0; l < list5.Count; l++)
            {
                DungeonHall dungeonHall2 = list5[l];
                double num4 = Math.Round((double)((float)(num2 + 1) / (float)data.dungeonHalls.Count * 100f));
                DungeonUtils.UpdateDungeonProgress(progress, Utils.Remap((float)num2, 0f, (float)data.dungeonHalls.Count, 0.4f, 0.6f, true), Language.GetTextValue("WorldGeneration.DungeonHalls", num4), true);
                if (dungeonHall2.calculated)
                {
                    dungeonHall2.GenerateHall(data);
                    num2++;
                }
            }
            for (int m = 0; m < data.dungeonHalls.Count; m++)
            {
                DungeonHall dungeonHall3 = data.dungeonHalls[m];
                if (!DualDungeonLayoutProvider.HallwayCheck_IsCrackedBrickHall(dungeonHall3) && !DualDungeonLayoutProvider.HallwayCheck_IsSpiderHall(dungeonHall3))
                {
                    double num5 = Math.Round((double)((float)(num2 + 1) / (float)data.dungeonHalls.Count * 100f));
                    DungeonUtils.UpdateDungeonProgress(progress, Utils.Remap((float)num2, 0f, (float)data.dungeonHalls.Count, 0.4f, 0.6f, true), Language.GetTextValue("WorldGeneration.DungeonHalls", num5), true);
                    if (dungeonHall3.calculated)
                    {
                        dungeonHall3.GenerateHall(data);
                        num2++;
                    }
                }
            }
        }
References Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateBiomeRooms(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.calculated, Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateDungeonBounds(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceHall(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateStartingRoom(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedHalls(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedRooms(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonHalls, Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, System.Collections.Generic.List< T >.FindAll(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.Generate(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateHall(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCheck_IsCrackedBrickHall(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCheck_IsSpiderHall(), System.list, Terraria.Utils.Remap(), System.Math.Round(), and Terraria.GameContent.Generation.Dungeon.DungeonUtils.UpdateDungeonProgress().