Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.GetHallwayConnectionPoints
GetHallwayConnectionPoints()
static ConnectionPointQuality Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.GetHallwayConnectionPoints (DungeonRoom room1, DungeonRoom room2, out Vector2D point1, out Vector2D point2) inline static
Definition at line 696 of file DualDungeonLayoutProvider.cs.
        {
            int hallwayConnectionPoint = (int)room1.GetHallwayConnectionPoint(room2.Center, out point1);
            ConnectionPointQuality hallwayConnectionPoint2 = room2.GetHallwayConnectionPoint(room1.Center, out point2);
            return (ConnectionPointQuality)Math.Max(hallwayConnectionPoint, (int)hallwayConnectionPoint2);
        }
References Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.Center, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GetHallwayConnectionPoint(), int, and System.Math.Max().
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateEntranceHall(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.SelectGoodRoomForHallway().