Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms
CalculateRooms()
List< DungeonRoom > Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.CalculateRooms (DungeonData data) inline private
Definition at line 153 of file DualDungeonLayoutProvider.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            IEnumerable<DungeonControlLine> dungeonDitherSnake = data.genVars.dungeonDitherSnake;
            List<DungeonRoom> list = new List<DungeonRoom>();
            foreach (DungeonControlLine dungeonControlLine in dungeonDitherSnake.Skip(1))
            {
                if (dungeonControlLine.ProgressionStage != dungeonControlLine.Prev.ProgressionStage)
                {
                    DungeonRoom dungeonRoom;
                    if (this.TryMakeRegularRoomOnLine(data, dungeonControlLine, 0.8, genRand.NextDouble() - 0.5, out dungeonRoom))
                    {
                        list.Add(dungeonRoom);
                    }
                }
                else
                {
                    for (int i = 0; i < 20; i++)
                    {
                        double num = genRand.NextDouble() * 2.0 - 1.0;
                        num = (double)Math.Sign(num) * Math.Pow(Math.Abs(num), 0.5);
                        DungeonRoom dungeonRoom;
                        if (this.TryMakeRegularRoomOnLine(data, dungeonControlLine, genRand.NextDouble(), num, out dungeonRoom))
{
                            list.Add(dungeonRoom);
                        }
                    }
                }
            }
            return list;
        }
References System.Math.Abs(), Terraria.GameContent.Generation.Dungeon.DungeonGenVars.dungeonDitherSnake, Terraria.WorldGen.genRand, Terraria.GameContent.Generation.Dungeon.DungeonData.genVars, System.list, System.Math.Pow(), Terraria.GameContent.Biomes.DungeonControlLine.Prev, Terraria.GameContent.Biomes.DungeonControlLine.ProgressionStage, System.Math.Sign(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.TryMakeRegularRoomOnLine().
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().