Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedHalls
ConvertSpecializedHalls()
void Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ConvertSpecializedHalls (List< DungeonHall > halls) inline
Definition at line 604 of file DualDungeonLayoutProvider.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            int num = 3;
            switch (WorldGen.GetWorldSize())
            {
            case 0:
                num = 3;
                break;
            case 1:
                num = 4;
                break;
            case 2:
                num = 5;
                break;
            }
            List<DungeonHall> list = new List<DungeonHall>();
            foreach (DungeonHall dungeonHall in halls)
            {
                byte style = dungeonHall.settings.StyleData.Style;
                if (style == 1)
                {
                    list.Add(dungeonHall);
                }
            }
            List<DungeonHall> list2 = list.ToList<DungeonHall>();
            int num2 = 2000;
            while (num2 > 0 && list2.Count > 0 && num > 0)
            {
                num2--;
                if (num2 <= 0)
                {
                    break;
                }
                DungeonHall dungeonHall2 = list2[genRand.Next(list2.Count)];
                if (dungeonHall2.CrackedBrick)
                {
                    list2.Remove(dungeonHall2);
                }
                else
                {
                    dungeonHall2.settings.StyleData = DungeonGenerationStyles.Spider;
                    num--;
                    list.Remove(dungeonHall2);
                    list2.Remove(dungeonHall2);
                }
            }
        }
References System.Collections.Generic.List< T >.Count, Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.CrackedBrick, Terraria.WorldGen.genRand, Terraria.WorldGen.GetWorldSize(), System.list, System.Collections.Generic.List< T >.Remove(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.settings, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyles.Spider, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, and Terraria.GameContent.Generation.Dungeon.Halls.DungeonHallSettings.StyleData.
Referenced by Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.ProvideLayout().