Terraria Decompiled: Terraria.WorldBuilding.WorldGenerationOptions.GetOptionFromSeedText
GetOptionFromSeedText()
static AWorldGenerationOption Terraria.WorldBuilding.WorldGenerationOptions.GetOptionFromSeedText (string processedSeed) inline static
Definition at line 73 of file WorldGenerationOptions.cs.
        {
            int num = WorldFileData.TranslateSeed(processedSeed);
            string text = Regex.Replace(processedSeed.ToLower(), "[^a-z0-9]+", "");
            foreach (AWorldGenerationOption aworldGenerationOption in WorldGenerationOptions.Options)
            {
                foreach (int num2 in aworldGenerationOption.SpecialSeedValues)
                {
                    if (num == num2)
                    {
                        return aworldGenerationOption;
                    }
                }
                foreach (string text2 in aworldGenerationOption.SpecialSeedNames)
                {
                    if (text == text2)
                    {
                        return aworldGenerationOption;
                    }
                }
            }
            return null;
        }
References Terraria.WorldBuilding.WorldGenerationOptions.Options, Terraria.WorldBuilding.AWorldGenerationOption.SpecialSeedNames, Terraria.WorldBuilding.AWorldGenerationOption.SpecialSeedValues, System.text, and Terraria.IO.WorldFileData.TranslateSeed().
Referenced by Terraria.Main.DedServ(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed().