Terraria Decompiled: Terraria.DataStructures.ArmorSetBonuses.Initialize
Initialize()
static void Terraria.DataStructures.ArmorSetBonuses.Initialize () inline static
Definition at line 14 of file ArmorSetBonuses.cs.
        {
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Shroomite), "ArmorSetBonus.Shroomite", ArmorSetBonus.PartType.None).Set(1548, 1549, 1550).Set(1546, 1549, 1550)
                .Set(1547, 1549, 1550)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Wood), "ArmorSetBonus.Wood", ArmorSetBonus.PartType.None).Set(727, 728, 729).Set(733, 734, 735)
                .Set(730, 731, 732)
                .Set(736, 737, 738)
                .Set(924, 925, 926)
                .Set(2509, 2510, 2511)
                .Set(2512, 2513, 2514)
                .Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.AshWood), "ArmorSetBonus.AshWood", 5279, 5280, 5281);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MetalTier1), "ArmorSetBonus.MetalTier1", ArmorSetBonus.PartType.None).Set(89, 80, 76).Set(687, 688, 689)
                .Set(90, 81, 77)
                .Set(954, 81, 77)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MetalTier2), "ArmorSetBonus.MetalTier2", ArmorSetBonus.PartType.None).Set(91, 82, 78).Set(92, 83, 79)
                .Set(955, 83, 79)
                .Set(690, 691, 692)
                .Set(693, 694, 695)
                .Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Platinum), "ArmorSetBonus.Platinum", 696, 697, 698);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Pumpkin), "ArmorSetBonus.Pumpkin", 1731, 1732, 1733);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Gladiator), "ArmorSetBonus.Gladiator", 3187, 3188, 3189);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Ninja), "ArmorSetBonus.Ninja", 256, 257, 258);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Fossil), "ArmorSetBonus.Fossil", 3374, 3375, 3376);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Necro), "ArmorSetBonus.Bone", ArmorSetBonus.PartType.None).Set(151, 152, 153).Set(959, 152, 153)
                .Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.BeetleDamage), "ArmorSetBonus.BeetleDamage", ArmorSetBonus.PartType.Body, 2199, 2200, 2202);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.BeetleDefense), "ArmorSetBonus.BeetleDefense", ArmorSetBonus.PartType.Body, 2199, 2201, 2202);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Wizard), "ArmorSetBonus.Wizard", ArmorSetBonus.PartType.Head).Set(238, 1282, 0).Set(238, 1283, 0)
                .Set(238, 1284, 0)
                .Set(238, 1285, 0)
                .Set(238, 1286, 0)
                .Set(238, 1287, 0)
                .Set(238, 2279, 0)
                .Set(238, 4256, 0)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MagicHat), "ArmorSetBonus.MagicHat", ArmorSetBonus.PartType.Head).Set(2275, 1282, 0).Set(2275, 1283, 0)
                .Set(2275, 1284, 0)
                .Set(2275, 1285, 0)
                .Set(2275, 1286, 0)
                .Set(2275, 1287, 0)
                .Set(2275, 2279, 0)
                .Set(2275, 4256, 0)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.ShadowScale), "ArmorSetBonus.ShadowScale", ArmorSetBonus.PartType.None).Set(new int[] { 102, 956 }, new int[] { 101, 957 }, new int[] { 100, 958 }).Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Crimson), "ArmorSetBonus.Crimson", 792, 793, 794);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.SpectreHealing), "ArmorSetBonus.SpectreHealing", ArmorSetBonus.PartType.Head, 1503, 1504, 1505);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.SpectreDamage), "ArmorSetBonus.SpectreDamage", ArmorSetBonus.PartType.Head, 2189, 1504, 1505);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Meteor), "ArmorSetBonus.Meteor", 123, 124, 125);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Frost), "ArmorSetBonus.Frost", 684, 685, 686);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Jungle), "ArmorSetBonus.Jungle", ArmorSetBonus.PartType.None).Set(new int[] { 228, 960 }, new int[] { 229, 961 }, new int[] { 230, 962 }).Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Molten), "ArmorSetBonus.Molten", 231, 232, 233);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Snow), "ArmorSetBonus.Snow", ArmorSetBonus.PartType.None).Set(new int[] { 803, 978 }, new int[] { 804, 979 }, new int[] { 805, 980 }).Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Mining), "ArmorSetBonus.Mining", ArmorSetBonus.PartType.None).Set(new int[] { 88, 5588, 4008 }, new int[] { 410, 5589 }, new int[] { 411, 5590 }).Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.ChlorophyteMelee), "ArmorSetBonus.ChlorophyteMelee", ArmorSetBonus.PartType.Head, 1001, 1004, 1005);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.ChlorophyteSummon), "ArmorSetBonus.ChlorophyteSummon", ArmorSetBonus.PartType.Head, 5524, 1004, 1005);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Chlorophyte), "ArmorSetBonus.Chlorophyte", ArmorSetBonus.PartType.Head).Set(1003, 1004, 1005).Set(1002, 1004, 1005)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Angler), "ArmorSetBonus.Angler", ArmorSetBonus.PartType.None).Set(new int[] { 2367, 5591 }, new int[] { 2368, 5592 }, new int[] { 2369, 5593 }).Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Cactus), "ArmorSetBonus.Cactus", 894, 895, 896);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Turtle), "ArmorSetBonus.Turtle", 1316, 1317, 1318);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.CobaltCaster), "ArmorSetBonus.CobaltCaster", ArmorSetBonus.PartType.Head, 371, 374, 375);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.CobaltMelee), "ArmorSetBonus.CobaltMelee", ArmorSetBonus.PartType.Head, 372, 374, 375);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.CobaltRanged), "ArmorSetBonus.CobaltRanged", ArmorSetBonus.PartType.Head, 373, 374, 375);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MythrilCaster), "ArmorSetBonus.MythrilCaster", ArmorSetBonus.PartType.Head, 376, 379, 380);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MythrilMelee), "ArmorSetBonus.MythrilMelee", ArmorSetBonus.PartType.Head, 377, 379, 380);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MythrilRanged), "ArmorSetBonus.MythrilRanged", ArmorSetBonus.PartType.Head, 378, 379, 380);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.AdamantiteCaster), "ArmorSetBonus.AdamantiteCaster", ArmorSetBonus.PartType.Head, 400, 403, 404);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.AdamantiteMelee), "ArmorSetBonus.AdamantiteMelee", ArmorSetBonus.PartType.Head, 401, 403, 404);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.AdamantiteRanged), "ArmorSetBonus.AdamantiteRanged", ArmorSetBonus.PartType.Head, 402, 403, 404);
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Palladium), "ArmorSetBonus.Palladium", ArmorSetBonus.PartType.None).Set(1205, 1208, 1209).Set(1206, 1208, 1209)
                .Set(1207, 1208, 1209)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Orichalcum), "ArmorSetBonus.Orichalcum", ArmorSetBonus.PartType.None).Set(1210, 1213, 1214).Set(1211, 1213, 1214)
                .Set(1212, 1213, 1214)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Titanium), "ArmorSetBonus.Titanium", ArmorSetBonus.PartType.None).Set(1215, 1218, 1219).Set(1216, 1218, 1219)
                .Set(1217, 1218, 1219)
                .Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.HallowedSummoner), "ArmorSetBonus.HallowedSummoner", ArmorSetBonus.PartType.Head).Set(new int[] { 4873, 4899 }, new int[] { 551, 4900 }, new int[] { 552, 4901 }).Add();
            ArmorSetBonuses.Create(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Hallowed), "ArmorSetBonus.Hallowed", ArmorSetBonus.PartType.Head).Set(new int[] { 558, 553, 559, 4898, 4897, 4896 }, new int[] { 551, 4900 }, new int[] { 552, 4901 }).Add();
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.CrystalAssassin), "ArmorSetBonus.CrystalNinja", 4982, 4983, 4984);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Tiki), "ArmorSetBonus.Tiki", 1159, 1160, 1161);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Spooky), "ArmorSetBonus.Spooky", 1832, 1833, 1834);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Bee), "ArmorSetBonus.Bee", 2361, 2362, 2363);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Spider), "ArmorSetBonus.Spider", 2370, 2371, 2372);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Solar), "ArmorSetBonus.Solar", 2763, 2764, 2765);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Vortex), "ArmorSetBonus.Vortex", 2757, 2758, 2759);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Nebula), "ArmorSetBonus.Nebula", 2760, 2761, 2762);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Stardust), "ArmorSetBonus.Stardust", 3381, 3382, 3383);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.Forbidden), "ArmorSetBonus.Forbidden", 3776, 3777, 3778);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.SquireTier2), "ArmorSetBonus.SquireTier2", 3800, 3801, 3802);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.ApprenticeTier2), "ArmorSetBonus.ApprenticeTier2", 3797, 3798, 3799);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.HuntressTier2), "ArmorSetBonus.HuntressTier2", 3803, 3804, 3805);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MonkTier2), "ArmorSetBonus.MonkTier2", 3806, 3807, 3808);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.SquireTier3), "ArmorSetBonus.SquireTier3", 3871, 3872, 3873);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.ApprenticeTier3), "ArmorSetBonus.ApprenticeTier3", 3874, 3875, 3876);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.HuntressTier3), "ArmorSetBonus.HuntressTier3", 3877, 3878, 3879);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.MonkTier3), "ArmorSetBonus.MonkTier3", 3880, 3881, 3882);
            ArmorSetBonuses.Add(new ArmorSetBonus.ArmorSetEffect(ArmorSetBonuses.Benefits.ObsidianOutlaw), "ArmorSetBonus.ObsidianOutlaw", 3266, 3267, 3268);
        }
References Terraria.DataStructures.ArmorSetBonuses.Benefits.AdamantiteCaster(), Terraria.DataStructures.ArmorSetBonuses.Benefits.AdamantiteMelee(), Terraria.DataStructures.ArmorSetBonuses.Benefits.AdamantiteRanged(), System.Add, Terraria.DataStructures.ArmorSetBonuses.Add(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Angler(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ApprenticeTier2(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ApprenticeTier3(), Terraria.DataStructures.ArmorSetBonus.ArmorSetEffect(), Terraria.DataStructures.ArmorSetBonuses.Benefits.AshWood(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Bee(), Terraria.DataStructures.ArmorSetBonuses.Benefits.BeetleDamage(), Terraria.DataStructures.ArmorSetBonuses.Benefits.BeetleDefense(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Cactus(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Chlorophyte(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ChlorophyteMelee(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ChlorophyteSummon(), Terraria.DataStructures.ArmorSetBonuses.Benefits.CobaltCaster(), Terraria.DataStructures.ArmorSetBonuses.Benefits.CobaltMelee(), Terraria.DataStructures.ArmorSetBonuses.Benefits.CobaltRanged(), Terraria.DataStructures.ArmorSetBonuses.Create(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Crimson(), Terraria.DataStructures.ArmorSetBonuses.Benefits.CrystalAssassin(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Forbidden(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Fossil(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Frost(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Gladiator(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Hallowed(), Terraria.DataStructures.ArmorSetBonuses.Benefits.HallowedSummoner(), Terraria.DataStructures.ArmorSetBonuses.Benefits.HuntressTier2(), Terraria.DataStructures.ArmorSetBonuses.Benefits.HuntressTier3(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Jungle(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MagicHat(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MetalTier1(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MetalTier2(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Meteor(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Mining(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Molten(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MonkTier2(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MonkTier3(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MythrilCaster(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MythrilMelee(), Terraria.DataStructures.ArmorSetBonuses.Benefits.MythrilRanged(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Nebula(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Necro(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Ninja(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ObsidianOutlaw(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Orichalcum(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Palladium(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Platinum(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Pumpkin(), Terraria.DataStructures.ArmorSetBonuses.Benefits.ShadowScale(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Shroomite(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Snow(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Solar(), Terraria.DataStructures.ArmorSetBonuses.Benefits.SpectreDamage(), Terraria.DataStructures.ArmorSetBonuses.Benefits.SpectreHealing(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Spider(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Spooky(), Terraria.DataStructures.ArmorSetBonuses.Benefits.SquireTier2(), Terraria.DataStructures.ArmorSetBonuses.Benefits.SquireTier3(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Stardust(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Tiki(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Titanium(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Turtle(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Vortex(), Terraria.DataStructures.ArmorSetBonuses.Benefits.Wizard(), and Terraria.DataStructures.ArmorSetBonuses.Benefits.Wood().
Referenced by Terraria.Main.Initialize_AlmostEverything().