Terraria Decompiled: Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIScrollbar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 97 of file UIScrollbar.cs.
        {
            if (this.AutoHide && !this.CanScroll)
            {
                return;
            }
            CalculatedStyle dimensions = base.GetDimensions();
            CalculatedStyle innerDimensions = base.GetInnerDimensions();
            if (this._isDragging)
            {
                float num = UserInterface.ActiveInstance.MousePosition.Y - innerDimensions.Y - this._dragYOffset;
                this._viewPosition = MathHelper.Clamp(num / innerDimensions.Height * this._maxViewSize, 0f, this._maxViewSize - this._viewSize);
            }
            Rectangle handleRectangle = this.GetHandleRectangle();
            Vector2 mousePosition = UserInterface.ActiveInstance.MousePosition;
            bool isHoveringOverHandle = this._isHoveringOverHandle;
            this._isHoveringOverHandle = handleRectangle.Contains(new Point((int)mousePosition.X, (int)mousePosition.Y));
            if (!isHoveringOverHandle && this._isHoveringOverHandle && FocusHelper.AllowUIInputs)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
            this.DrawBar(spriteBatch, this._texture.Value, dimensions.ToRectangle(), Color.White);
            this.DrawBar(spriteBatch, this._innerTexture.Value, handleRectangle, Color.White * ((this._isDragging || this._isHoveringOverHandle) ? 1f : 0.85f));
        }
References Terraria.GameContent.UI.Elements.UIScrollbar._dragYOffset, Terraria.GameContent.UI.Elements.UIScrollbar._innerTexture, Terraria.GameContent.UI.Elements.UIScrollbar._isDragging, Terraria.GameContent.UI.Elements.UIScrollbar._isHoveringOverHandle, Terraria.GameContent.UI.Elements.UIScrollbar._texture, Terraria.UI.UserInterface.ActiveInstance, Terraria.FocusHelper.AllowUIInputs, Terraria.GameContent.UI.Elements.UIScrollbar.AutoHide, Terraria.GameContent.UI.Elements.UIScrollbar.CanScroll, Microsoft.Xna.Framework.MathHelper.Clamp(), Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.GameContent.UI.Elements.UIScrollbar.DrawBar(), Terraria.GameContent.UI.Elements.UIScrollbar.GetHandleRectangle(), Terraria.UI.CalculatedStyle.Height, Terraria.UI.UserInterface.MousePosition, Terraria.Audio.SoundEngine.PlaySound(), Microsoft.Xna.Framework.Graphics.Point, Terraria.UI.CalculatedStyle.ToRectangle(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.