Terraria Decompiled: Terraria.GameContent.UI.Elements.UIScrollbar.SetView
SetView()
void Terraria.GameContent.UI.Elements.UIScrollbar.SetView (float viewSize, float maxViewSize) inline
Definition at line 62 of file UIScrollbar.cs.
        {
            viewSize = MathHelper.Clamp(viewSize, 0f, maxViewSize);
            this._viewPosition = MathHelper.Clamp(this._viewPosition, 0f, maxViewSize - viewSize);
            this._viewSize = viewSize;
            this._maxViewSize = maxViewSize;
        }
References Terraria.GameContent.UI.Elements.UIScrollbar._viewPosition, and Microsoft.Xna.Framework.MathHelper.Clamp().
Referenced by Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.AddUIList(), Terraria.GameContent.UI.States.UIDebugCommandsList.BuildPage(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UIEmotesMenu.InitializePage(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairstylesMenu(), Terraria.GameContent.UI.States.UICharacterSelect.OnInitialize(), Terraria.GameContent.UI.States.UIManageControls.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.OnInitialize(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.OnInitialize(), Terraria.GameContent.UI.States.UIWorldSelect.OnInitialize(), Terraria.GameContent.UI.States.UITextWrappingTest.UITextWrappingTest(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug(), and Terraria.GameContent.UI.Elements.UIList.UpdateScrollbar().