Terraria Decompiled: System.Runtime.Serialization.SafeSerializationManager.GetRealObject
GetRealObject()
object IObjectReference. System.Runtime.Serialization.SafeSerializationManager.GetRealObject (StreamingContext context) inline private
Implements System.Runtime.Serialization.IObjectReference.
Definition at line 114 of file SafeSerializationManager.cs.
        {
            if (this.m_realObject != null)
            {
                return this.m_realObject;
            }
            if (this.m_realType == null)
            {
                return this;
            }
            Stack stack = new Stack();
            RuntimeType runtimeType = this.m_realType;
            do
            {
                stack.Push(runtimeType);
                runtimeType = runtimeType.BaseType as RuntimeType;
            }
            while (runtimeType != typeof(object));
            RuntimeType runtimeType2;
            RuntimeConstructorInfo runtimeConstructorInfo;
            do
            {
                runtimeType2 = runtimeType;
                runtimeType = stack.Pop() as RuntimeType;
                runtimeConstructorInfo = runtimeType.GetSerializationCtor();
            }
            while (runtimeConstructorInfo != null && runtimeConstructorInfo.IsSecurityCritical);
            runtimeConstructorInfo = ObjectManager.GetConstructor(runtimeType2);
            object uninitializedObject = FormatterServices.GetUninitializedObject(this.m_realType);
            runtimeConstructorInfo.SerializationInvoke(uninitializedObject, this.m_savedSerializationInfo, context);
            this.m_savedSerializationInfo = null;
            this.m_realType = null;
            this.m_realObject = uninitializedObject;
            return uninitializedObject;
        }
References System.Runtime.Serialization.ObjectManager.GetConstructor(), System.RuntimeType.GetSerializationCtor(), System.Runtime.Serialization.FormatterServices.GetUninitializedObject(), System.Reflection.RuntimeConstructorInfo.IsSecurityCritical, System.Runtime.Serialization.SafeSerializationManager.m_realObject, System.Runtime.Serialization.SafeSerializationManager.m_realType, System.Runtime.Serialization.SafeSerializationManager.m_savedSerializationInfo, System.Collections.Generic.Stack< T >.Push(), System.Reflection.RuntimeConstructorInfo.SerializationInvoke(), and System.stack.