Terraria Decompiled: System.Security.Util.Tokenizer.StringMaker.MakeString
MakeString()
string System.Security.Util.Tokenizer.StringMaker.MakeString () inline
Definition at line 756 of file Tokenizer.cs.
            {
                char[] outChars = this._outChars;
                int outIndex = this._outIndex;
                if (this._outStringBuilder != null)
                {
                    this._outStringBuilder.Append(this._outChars, 0, this._outIndex);
                    return this._outStringBuilder.ToString();
                }
                uint num3;
                if (this.cStringsUsed > this.cStringsMax / 4U * 3U)
                {
                    uint num = this.cStringsMax * 2U;
                    string[] array = new string[num];
                    int num2 = 0;
                    while ((long)num2 < (long)((ulong)this.cStringsMax))
                    {
                        if (this.aStrings[num2] != null)
{
                            num3 = Tokenizer.StringMaker.HashString(this.aStrings[num2]) % num;
                            while (array[(int)num3] != null)
{
                                if ((num3 += 1U) >= num)
{
                                    num3 = 0U;
                                }
                            }
                            array[(int)num3] = this.aStrings[num2];
                        }
                        num2++;
                    }
                    this.cStringsMax = num;
                    this.aStrings = array;
                }
                num3 = Tokenizer.StringMaker.HashCharArray(outChars, outIndex) % this.cStringsMax;
                string text;
                while ((text = this.aStrings[(int)num3]) != null)
                {
                    if (this.CompareStringAndChars(text, outChars, outIndex))
                    {
                        return text;
                    }
                    if ((num3 += 1U) >= this.cStringsMax)
                    {
                        num3 = 0U;
                    }
                }
                text = new string(outChars, 0, outIndex);
                this.aStrings[(int)num3] = text;
                this.cStringsUsed += 1U;
                return text;
            }
References System.Security.Util.Tokenizer.StringMaker._outChars, System.Security.Util.Tokenizer.StringMaker._outIndex, System.Security.Util.Tokenizer.StringMaker._outStringBuilder, System.Text.StringBuilder.Append(), System.array, System.Security.Util.Tokenizer.StringMaker.aStrings, System.Security.Util.Tokenizer.StringMaker.CompareStringAndChars(), System.Security.Util.Tokenizer.StringMaker.cStringsMax, System.Security.Util.Tokenizer.StringMaker.cStringsUsed, System.Security.Util.Tokenizer.StringMaker.HashCharArray(), System.Security.Util.Tokenizer.StringMaker.HashString(), int, System.text, System.Text.StringBuilder.ToString(), and System.U.
Referenced by System.Security.SecurityDocument.GetString().