Terraria Decompiled: FullSerializer.Internal.fsIEnumerableConverter.GetElementType
GetElementType()
static Type FullSerializer.Internal.fsIEnumerableConverter.GetElementType (Type objectType) inline static private
Definition at line 111 of file fsIEnumerableConverter.cs.
        {
            if (objectType.HasElementType)
            {
                return objectType.GetElementType();
            }
            Type @interface = fsReflectionUtility.GetInterface(objectType, typeof(IEnumerable));
            if (@interface != null)
            {
                return @interface.GetGenericArguments()[0];
            }
            return typeof(object);
        }
References System.Type.GetElementType(), System.Type.GetGenericArguments(), and System.Type.HasElementType.
Referenced by FullSerializer.Internal.fsIEnumerableConverter.TryDeserialize(), and FullSerializer.Internal.fsIEnumerableConverter.TrySerialize().