Terraria Decompiled: FullSerializer.Internal.fsIEnumerableConverter.TrySerialize
TrySerialize()
override fsResult FullSerializer.Internal.fsIEnumerableConverter.TrySerialize (object instance_, out fsData serialized, Type storageType) inline
Definition at line 24 of file fsIEnumerableConverter.cs.
        {
            IEnumerable enumerable = (IEnumerable)instance_;
            fsResult success = fsResult.Success;
            Type elementType = fsIEnumerableConverter.GetElementType(storageType);
            serialized = fsData.CreateList(fsIEnumerableConverter.HintSize(enumerable));
            List<fsData> asList = serialized.AsList;
            foreach (object obj in enumerable)
            {
                fsData fsData;
                fsResult fsResult = this.Serializer.TrySerialize(elementType, obj, out fsData);
                success.AddMessages(fsResult);
                if (!fsResult.Failed)
                {
                    asList.Add(fsData);
                }
            }
            if (this.IsStack(enumerable.GetType()))
            {
                asList.Reverse();
            }
            return success;
        }
References FullSerializer.fsResult.AddMessages(), FullSerializer.fsData.CreateList(), FullSerializer.fsResult.Failed, FullSerializer.Internal.fsIEnumerableConverter.GetElementType(), FullSerializer.Internal.fsIEnumerableConverter.HintSize(), FullSerializer.Internal.fsIEnumerableConverter.IsStack(), System.obj, FullSerializer.fsBaseConverter.Serializer, FullSerializer.fsResult.Success, and FullSerializer.fsSerializer.TrySerialize().