Terraria Decompiled: Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UISearchBar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 297 of file UISearchBar.cs.
        {
            base.DrawSelf(spriteBatch);
            if (!this.IsWritingText)
            {
                return;
            }
            PlayerInput.WritingText = true;
            Main.instance.HandleIME();
            Rectangle rectangle = this._text.GetDimensions().ToRectangle();
            Vector2 vector = new Vector2((float)rectangle.Left, (float)(rectangle.Bottom + 32));
            Main.instance.SetIMEPanelAnchor(vector, 0f);
            string inputText = Main.GetInputText(this.actualContents, false);
            if (Main.inputTextEnter)
            {
                this.ToggleTakingText();
            }
            else if (Main.inputTextEscape)
            {
                Main.inputTextEscape = false;
                this.ToggleTakingText();
            }
            this.SetContents(inputText, false);
        }
References Terraria.GameContent.UI.Elements.UISearchBar._text, Terraria.GameContent.UI.Elements.UISearchBar.actualContents, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Main.GetInputText(), Terraria.Main.HandleIME(), Terraria.Main.inputTextEnter, Terraria.Main.inputTextEscape, Terraria.Main.instance, Terraria.GameContent.UI.Elements.UISearchBar.IsWritingText, Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.UI.Elements.UISearchBar.SetContents(), Terraria.Main.SetIMEPanelAnchor(), Terraria.GameContent.UI.Elements.UISearchBar.ToggleTakingText(), and Microsoft.Xna.Framework.Graphics.Vector2.