Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.GetString
GetString()
string Newtonsoft.Json.Bson.BsonReader.GetString (int length) inline private
Definition at line 539 of file BsonReader.cs.
        {
            if (length == 0)
            {
                return string.Empty;
            }
            this.EnsureBuffers();
            StringBuilder stringBuilder = null;
            int num = 0;
            int num2 = 0;
            int num4;
            for (;;)
            {
                int num3 = ((length - num > 128 - num2) ? (128 - num2) : (length - num));
                num4 = this._reader.Read(this._byteBuffer, num2, num3);
                if (num4 == 0)
                {
                    break;
                }
                num += num4;
                num4 += num2;
                if (num4 == length)
                {
                    goto Block_4;
                }
                int lastFullCharStop = this.GetLastFullCharStop(num4 - 1);
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(length);
                }
                int chars = Encoding.UTF8.GetChars(this._byteBuffer, 0, lastFullCharStop + 1, this._charBuffer, 0);
                stringBuilder.Append(this._charBuffer, 0, chars);
                if (lastFullCharStop < num4 - 1)
                {
                    num2 = num4 - lastFullCharStop - 1;
                    Array.Copy(this._byteBuffer, lastFullCharStop + 1, this._byteBuffer, 0, num2);
                }
                else
                {
                    num2 = 0;
                }
                if (num >= length)
                {
                    goto Block_7;
                }
            }
            throw new EndOfStreamException("Unable to read beyond the end of the stream.");
            Block_4:
            int chars2 = Encoding.UTF8.GetChars(this._byteBuffer, 0, num4, this._charBuffer, 0);
            return new string(this._charBuffer, 0, chars2);
            Block_7:
            return stringBuilder.ToString();
        }
References Newtonsoft.Json.Bson.BsonReader._byteBuffer, Newtonsoft.Json.Bson.BsonReader._charBuffer, Newtonsoft.Json.Bson.BsonReader._reader, System.Text.StringBuilder.Append(), System.Array.Copy(), Newtonsoft.Json.Bson.BsonReader.EnsureBuffers(), System.Text.Encoding.GetChars(), Newtonsoft.Json.Bson.BsonReader.GetLastFullCharStop(), System.length, System.IO.BinaryReader.Read(), System.Text.StringBuilder.ToString(), and System.Text.Encoding.UTF8.
Referenced by Newtonsoft.Json.Bson.BsonReader.ReadLengthString().