Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadBinary
ReadBinary()
byte[] Newtonsoft.Json.Bson.BsonReader.ReadBinary (out BsonBinaryType binaryType) inline private
Definition at line 466 of file BsonReader.cs.
        {
            int num = this.ReadInt32();
            binaryType = (BsonBinaryType)this.ReadByte();
            if (binaryType == BsonBinaryType.BinaryOld && !this._jsonNet35BinaryCompatibility)
            {
                num = this.ReadInt32();
            }
            return this.ReadBytes(num);
        }
References Newtonsoft.Json.Bson.BsonReader.ReadByte(), Newtonsoft.Json.Bson.BsonReader.ReadBytes(), and Newtonsoft.Json.Bson.BsonReader.ReadInt32().
Referenced by Newtonsoft.Json.Bson.BsonReader.ReadType().