Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.Read
Read()
override bool Newtonsoft.Json.Bson.BsonReader.Read () inline
Definition at line 100 of file BsonReader.cs.
        {
            bool flag2;
            try
            {
                bool flag;
                switch (this._bsonReaderState)
                {
                case BsonReader.BsonReaderState.Normal:
                    flag = this.ReadNormal();
                    break;
                case BsonReader.BsonReaderState.ReferenceStart:
                case BsonReader.BsonReaderState.ReferenceRef:
                case BsonReader.BsonReaderState.ReferenceId:
                    flag = this.ReadReference();
                    break;
                case BsonReader.BsonReaderState.CodeWScopeStart:
                case BsonReader.BsonReaderState.CodeWScopeCode:
                case BsonReader.BsonReaderState.CodeWScopeScope:
                case BsonReader.BsonReaderState.CodeWScopeScopeObject:
                case BsonReader.BsonReaderState.CodeWScopeScopeEnd:
                    flag = this.ReadCodeWScope();
                    break;
                default:
                    throw JsonReaderException.Create(this, "Unexpected state: {0}".FormatWith(CultureInfo.InvariantCulture, this._bsonReaderState));
                }
                if (!flag)
                {
                    base.SetToken(JsonToken.None);
                    flag2 = false;
                }
                else
                {
                    flag2 = true;
                }
            }
            catch (EndOfStreamException)
            {
                base.SetToken(JsonToken.None);
                flag2 = false;
            }
            return flag2;
        }
References Newtonsoft.Json.Bson.BsonReader._bsonReaderState, Newtonsoft.Json.JsonReaderException.Create(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Bson.BsonReader.ReadCodeWScope(), Newtonsoft.Json.Bson.BsonReader.ReadNormal(), and Newtonsoft.Json.Bson.BsonReader.ReadReference().