Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.EnsureBuffers
EnsureBuffers()
void Newtonsoft.Json.Bson.BsonReader.EnsureBuffers () inline private
Definition at line 645 of file BsonReader.cs.
        {
            if (this._byteBuffer == null)
            {
                this._byteBuffer = new byte[128];
            }
            if (this._charBuffer == null)
            {
                int maxCharCount = Encoding.UTF8.GetMaxCharCount(128);
                this._charBuffer = new char[maxCharCount];
            }
        }
References Newtonsoft.Json.Bson.BsonReader._byteBuffer, Newtonsoft.Json.Bson.BsonReader._charBuffer, System.Text.Encoding.GetMaxCharCount(), and System.Text.Encoding.UTF8.
Referenced by Newtonsoft.Json.Bson.BsonReader.GetString(), and Newtonsoft.Json.Bson.BsonReader.ReadString().