Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadType
ReadType() [2/2]
void Newtonsoft.Json.Bson.BsonReader.ReadType (BsonType type) inline private
Definition at line 350 of file BsonReader.cs.
        {
            switch (type)
            {
            case BsonType.Number:
            {
                double num = this.ReadDouble();
                if (this._floatParseHandling == FloatParseHandling.Decimal)
                {
                    base.SetToken(JsonToken.Float, Convert.ToDecimal(num, CultureInfo.InvariantCulture));
                    return;
                }
                base.SetToken(JsonToken.Float, num);
                return;
            }
            case BsonType.String:
            case BsonType.Symbol:
                base.SetToken(JsonToken.String, this.ReadLengthString());
                return;
            case BsonType.Object:
            {
                base.SetToken(JsonToken.StartObject);
                BsonReader.ContainerContext containerContext = new BsonReader.ContainerContext(BsonType.Object);
                this.PushContext(containerContext);
                containerContext.Length = this.ReadInt32();
                return;
            }
            case BsonType.Array:
            {
                base.SetToken(JsonToken.StartArray);
                BsonReader.ContainerContext containerContext2 = new BsonReader.ContainerContext(BsonType.Array);
                this.PushContext(containerContext2);
                containerContext2.Length = this.ReadInt32();
                return;
            }
            case BsonType.Binary:
            {
                BsonBinaryType bsonBinaryType;
                byte[] array = this.ReadBinary(out bsonBinaryType);
                object obj = ((bsonBinaryType != BsonBinaryType.Uuid) ? array : new Guid(array));
                base.SetToken(JsonToken.Bytes, obj);
                return;
            }
            case BsonType.Undefined:
                base.SetToken(JsonToken.Undefined);
                return;
            case BsonType.Oid:
            {
                byte[] array2 = this.ReadBytes(12);
                base.SetToken(JsonToken.Bytes, array2);
                return;
            }
            case BsonType.Boolean:
            {
                bool flag = Convert.ToBoolean(this.ReadByte());
                base.SetToken(JsonToken.Boolean, flag);
                return;
            }
            case BsonType.Date:
            {
                DateTime dateTime = DateTimeUtils.ConvertJavaScriptTicksToDateTime(this.ReadInt64());
                DateTimeKind dateTimeKindHandling = this.DateTimeKindHandling;
                DateTime dateTime2;
                if (dateTimeKindHandling != null)
                {
                    if (dateTimeKindHandling != 2)
                    {
                        dateTime2 = dateTime;
                    }
                    else
                    {
                        dateTime2 = dateTime.ToLocalTime();
                    }
                }
                else
                {
                    dateTime2 = DateTime.SpecifyKind(dateTime, 0);
                }
                base.SetToken(JsonToken.Date, dateTime2);
                return;
            }
            case BsonType.Null:
                base.SetToken(JsonToken.Null);
                return;
            case BsonType.Regex:
            {
                string text = this.ReadString();
                string text2 = this.ReadString();
                string text3 = "/" + text + "/" + text2;
                base.SetToken(JsonToken.String, text3);
                return;
            }
            case BsonType.Reference:
                base.SetToken(JsonToken.StartObject);
                this._bsonReaderState = BsonReader.BsonReaderState.ReferenceStart;
                return;
            case BsonType.Code:
                base.SetToken(JsonToken.String, this.ReadLengthString());
                return;
            case BsonType.CodeWScope:
                base.SetToken(JsonToken.StartObject);
                this._bsonReaderState = BsonReader.BsonReaderState.CodeWScopeStart;
                return;
            case BsonType.Integer:
                base.SetToken(JsonToken.Integer, (long)this.ReadInt32());
                return;
            case BsonType.TimeStamp:
            case BsonType.Long:
                base.SetToken(JsonToken.Integer, this.ReadInt64());
                return;
            default:
                throw new ArgumentOutOfRangeException("type", "Unexpected BsonType value: " + type);
            }
        }
References Newtonsoft.Json.JsonReader._floatParseHandling, System.array, Newtonsoft.Json.Utilities.DateTimeUtils.ConvertJavaScriptTicksToDateTime(), Newtonsoft.Json.Bson.BsonReader.DateTimeKindHandling, Newtonsoft.Json.Utilities.Guid, System.Globalization.CultureInfo.InvariantCulture, System.obj, Newtonsoft.Json.Bson.BsonReader.PushContext(), Newtonsoft.Json.Bson.BsonReader.ReadBinary(), Newtonsoft.Json.Bson.BsonReader.ReadByte(), Newtonsoft.Json.Bson.BsonReader.ReadBytes(), Newtonsoft.Json.Bson.BsonReader.ReadDouble(), Newtonsoft.Json.Bson.BsonReader.ReadInt32(), Newtonsoft.Json.Bson.BsonReader.ReadInt64(), Newtonsoft.Json.Bson.BsonReader.ReadString(), System.DateTime.SpecifyKind(), System.text, System.Convert.ToBoolean(), System.Convert.ToDecimal(), and System.DateTime.ToLocalTime().