Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadLengthString
ReadLengthString()
string Newtonsoft.Json.Bson.BsonReader.ReadLengthString () inline private
Definition at line 529 of file BsonReader.cs.
        {
            int num = this.ReadInt32();
            this.MovePosition(num);
            string @string = this.GetString(num - 1);
            this._reader.ReadByte();
            return @string;
        }
References Newtonsoft.Json.Bson.BsonReader._reader, Newtonsoft.Json.Bson.BsonReader.GetString(), Newtonsoft.Json.Bson.BsonReader.MovePosition(), System.IO.BinaryReader.ReadByte(), and Newtonsoft.Json.Bson.BsonReader.ReadInt32().