Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.GetLastFullCharStop
GetLastFullCharStop()
int Newtonsoft.Json.Bson.BsonReader.GetLastFullCharStop (int start) inline private
Definition at line 594 of file BsonReader.cs.
        {
            int i = start;
            int num = 0;
            while (i >= 0)
            {
                num = this.BytesInSequence(this._byteBuffer[i]);
                if (num == 0)
                {
                    i--;
                }
                else
                {
                    if (num != 1)
                    {
                        i--;
                        break;
                    }
                    break;
                }
            }
            if (num == start - i)
            {
                return start;
            }
            return i;
        }
References Newtonsoft.Json.Bson.BsonReader._byteBuffer, Newtonsoft.Json.Bson.BsonReader.BytesInSequence(), and System.start.
Referenced by Newtonsoft.Json.Bson.BsonReader.GetString(), and Newtonsoft.Json.Bson.BsonReader.ReadString().