Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadNormal
ReadNormal()
bool Newtonsoft.Json.Bson.BsonReader.ReadNormal () inline private
Definition at line 252 of file BsonReader.cs.
        {
            switch (base.CurrentState)
            {
            case JsonReader.State.Start:
            {
                JsonToken jsonToken = ((!this._readRootValueAsArray) ? JsonToken.StartObject : JsonToken.StartArray);
                BsonType bsonType = ((!this._readRootValueAsArray) ? BsonType.Object : BsonType.Array);
                base.SetToken(jsonToken);
                BsonReader.ContainerContext containerContext = new BsonReader.ContainerContext(bsonType);
                this.PushContext(containerContext);
                containerContext.Length = this.ReadInt32();
                return true;
            }
            case JsonReader.State.Complete:
            case JsonReader.State.Closed:
                return false;
            case JsonReader.State.Property:
                this.ReadType(this._currentElementType);
                return true;
            case JsonReader.State.ObjectStart:
            case JsonReader.State.ArrayStart:
            case JsonReader.State.PostValue:
            {
                BsonReader.ContainerContext currentContext = this._currentContext;
                if (currentContext == null)
                {
                    return false;
                }
                int num = currentContext.Length - 1;
                if (currentContext.Position < num)
                {
                    if (currentContext.Type == BsonType.Array)
                    {
                        this.ReadElement();
                        this.ReadType(this._currentElementType);
                        return true;
                    }
                    base.SetToken(JsonToken.PropertyName, this.ReadElement());
                    return true;
                }
                else
                {
                    if (currentContext.Position != num)
                    {
                        throw JsonReaderException.Create(this, "Read past end of current container context.");
                    }
                    if (this.ReadByte() != 0)
                    {
                        throw JsonReaderException.Create(this, "Unexpected end of object byte value.");
                    }
                    this.PopContext();
                    if (this._currentContext != null)
                    {
                        this.MovePosition(currentContext.Length);
                    }
                    JsonToken jsonToken2 = ((currentContext.Type == BsonType.Object) ? JsonToken.EndObject : JsonToken.EndArray);
                    base.SetToken(jsonToken2);
                    return true;
                }
                break;
            }
            case JsonReader.State.ConstructorStart:
            case JsonReader.State.Constructor:
            case JsonReader.State.Error:
            case JsonReader.State.Finished:
                return false;
            }
            throw new ArgumentOutOfRangeException();
        }
References Newtonsoft.Json.Bson.BsonReader._currentContext, Newtonsoft.Json.Bson.BsonReader._currentElementType, Newtonsoft.Json.Bson.BsonReader._readRootValueAsArray, Newtonsoft.Json.JsonReaderException.Create(), Newtonsoft.Json.Bson.BsonReader.ContainerContext.Length, Newtonsoft.Json.Bson.BsonReader.MovePosition(), Newtonsoft.Json.Bson.BsonReader.PopContext(), Newtonsoft.Json.Bson.BsonReader.ContainerContext.Position, Newtonsoft.Json.Bson.BsonReader.PushContext(), Newtonsoft.Json.Bson.BsonReader.ReadByte(), Newtonsoft.Json.Bson.BsonReader.ReadElement(), Newtonsoft.Json.Bson.BsonReader.ReadInt32(), Newtonsoft.Json.Bson.BsonReader.ReadType(), and Newtonsoft.Json.Bson.BsonReader.ContainerContext.Type.
Referenced by Newtonsoft.Json.Bson.BsonReader.Read(), and Newtonsoft.Json.Bson.BsonReader.ReadCodeWScope().