Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadCodeWScope
ReadCodeWScope()
bool Newtonsoft.Json.Bson.BsonReader.ReadCodeWScope () inline private
Definition at line 160 of file BsonReader.cs.
        {
            switch (this._bsonReaderState)
            {
            case BsonReader.BsonReaderState.CodeWScopeStart:
                base.SetToken(JsonToken.PropertyName, "$code");
                this._bsonReaderState = BsonReader.BsonReaderState.CodeWScopeCode;
                return true;
            case BsonReader.BsonReaderState.CodeWScopeCode:
                this.ReadInt32();
                base.SetToken(JsonToken.String, this.ReadLengthString());
                this._bsonReaderState = BsonReader.BsonReaderState.CodeWScopeScope;
                return true;
            case BsonReader.BsonReaderState.CodeWScopeScope:
            {
                if (base.CurrentState == JsonReader.State.PostValue)
                {
                    base.SetToken(JsonToken.PropertyName, "$scope");
                    return true;
                }
                base.SetToken(JsonToken.StartObject);
                this._bsonReaderState = BsonReader.BsonReaderState.CodeWScopeScopeObject;
                BsonReader.ContainerContext containerContext = new BsonReader.ContainerContext(BsonType.Object);
                this.PushContext(containerContext);
                containerContext.Length = this.ReadInt32();
                return true;
            }
            case BsonReader.BsonReaderState.CodeWScopeScopeObject:
            {
                bool flag = this.ReadNormal();
                if (flag && this.TokenType == JsonToken.EndObject)
                {
                    this._bsonReaderState = BsonReader.BsonReaderState.CodeWScopeScopeEnd;
                }
                return flag;
            }
            case BsonReader.BsonReaderState.CodeWScopeScopeEnd:
                base.SetToken(JsonToken.EndObject);
                this._bsonReaderState = BsonReader.BsonReaderState.Normal;
                return true;
            default:
                throw new ArgumentOutOfRangeException();
            }
        }
References Newtonsoft.Json.Bson.BsonReader._bsonReaderState, Newtonsoft.Json.Bson.BsonReader.PushContext(), Newtonsoft.Json.Bson.BsonReader.ReadInt32(), and Newtonsoft.Json.Bson.BsonReader.ReadNormal().
Referenced by Newtonsoft.Json.Bson.BsonReader.Read().