Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadDouble
ReadDouble()
double Newtonsoft.Json.Bson.BsonReader.ReadDouble () inline private
Definition at line 659 of file BsonReader.cs.
        {
            this.MovePosition(8);
            return this._reader.ReadDouble();
        }
References Newtonsoft.Json.Bson.BsonReader._reader, Newtonsoft.Json.Bson.BsonReader.MovePosition(), and System.IO.BinaryReader.ReadDouble().
Referenced by Newtonsoft.Json.Bson.BsonReader.ReadType().