Terraria Decompiled: Newtonsoft.Json.Bson.BsonReader.ReadString
ReadString()
string Newtonsoft.Json.Bson.BsonReader.ReadString () inline private
Definition at line 478 of file BsonReader.cs.
        {
            this.EnsureBuffers();
            StringBuilder stringBuilder = null;
            int num = 0;
            int num2 = 0;
            int num4;
            for (;;)
            {
                int num3 = num2;
                byte b;
                while (num3 < 128 && (b = this._reader.ReadByte()) > 0)
                {
                    this._byteBuffer[num3++] = b;
                }
                num4 = num3 - num2;
                num += num4;
                if (num3 < 128 && stringBuilder == null)
                {
                    break;
                }
                int lastFullCharStop = this.GetLastFullCharStop(num3 - 1);
                int chars = Encoding.UTF8.GetChars(this._byteBuffer, 0, lastFullCharStop + 1, this._charBuffer, 0);
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(256);
                }
                stringBuilder.Append(this._charBuffer, 0, chars);
                if (lastFullCharStop < num4 - 1)
                {
                    num2 = num4 - lastFullCharStop - 1;
                    Array.Copy(this._byteBuffer, lastFullCharStop + 1, this._byteBuffer, 0, num2);
                }
                else
                {
                    if (num3 < 128)
                    {
                        goto Block_6;
                    }
                    num2 = 0;
                }
            }
            int chars2 = Encoding.UTF8.GetChars(this._byteBuffer, 0, num4, this._charBuffer, 0);
            this.MovePosition(num + 1);
            return new string(this._charBuffer, 0, chars2);
            Block_6:
            this.MovePosition(num + 1);
            return stringBuilder.ToString();
        }
References Newtonsoft.Json.Bson.BsonReader._byteBuffer, Newtonsoft.Json.Bson.BsonReader._charBuffer, Newtonsoft.Json.Bson.BsonReader._reader, System.Text.StringBuilder.Append(), System.Array.Copy(), Newtonsoft.Json.Bson.BsonReader.EnsureBuffers(), System.Text.Encoding.GetChars(), Newtonsoft.Json.Bson.BsonReader.GetLastFullCharStop(), Newtonsoft.Json.Bson.BsonReader.MovePosition(), System.IO.BinaryReader.ReadByte(), System.Text.StringBuilder.ToString(), and System.Text.Encoding.UTF8.
Referenced by Newtonsoft.Json.Bson.BsonReader.ReadElement(), and Newtonsoft.Json.Bson.BsonReader.ReadType().