Terraria Decompiled: System.Collections.Concurrent.Partitioner.DynamicPartitionerForIEnumerable.InternalPartitionEnumerable.TryCopyFromFillBuffer
TryCopyFromFillBuffer()
void System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.TryCopyFromFillBuffer (KeyValuePair< long, TSource >[] destArray, int requestedChunkSize, ref int actualNumElementsGrabbed) inline private
Definition at line 404 of file Partitioner.2.cs.
                {
                    actualNumElementsGrabbed = 0;
                    KeyValuePair<long, TSource>[] fillBuffer = this._fillBuffer;
                    if (fillBuffer == null)
                    {
                        return;
                    }
                    if (this._fillBufferCurrentPosition >= this._fillBufferSize)
                    {
                        return;
                    }
                    Interlocked.Increment(ref this._activeCopiers);
                    int num = Interlocked.Add(ref this._fillBufferCurrentPosition, requestedChunkSize);
                    int num2 = num - requestedChunkSize;
                    if (num2 < this._fillBufferSize)
                    {
                        actualNumElementsGrabbed = ((num < this._fillBufferSize) ? num : (this._fillBufferSize - num2));
                        Array.Copy(fillBuffer, num2, destArray, 0, actualNumElementsGrabbed);
                    }
                    Interlocked.Decrement(ref this._activeCopiers);
                }
References System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._activeCopiers, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._fillBuffer, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._fillBufferCurrentPosition, System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable._fillBufferSize, System.Threading.Interlocked.Add(), System.Array.Copy(), System.Threading.Interlocked.Decrement(), and System.Threading.Interlocked.Increment().
Referenced by System.Collections.Concurrent.Partitioner< TSource >.DynamicPartitionerForIEnumerable< TSource >.InternalPartitionEnumerable.GrabChunk_Buffered().