Terraria Decompiled: System.ParseNumbers.IntToString
IntToString()
static unsafe string System.ParseNumbers.IntToString (int n, int radix, int width, char paddingChar, int flags) inline static
Definition at line 172 of file ParseNumbers.cs.
        {
            Span<char> span = new Span<char>(stackalloc byte[(UIntPtr)132], 66);
            if (radix < 2 || radix > 36)
            {
                throw new ArgumentException("Invalid Base.", "radix");
            }
            bool flag = false;
            uint num;
            if (n < 0)
            {
                flag = true;
                num = (uint)((10 == radix) ? (-(uint)n) : n);
            }
            else
            {
                num = (uint)n;
            }
            if ((flags & 64) != 0)
            {
                num &= 255U;
            }
            else if ((flags & 128) != 0)
            {
                num &= 65535U;
            }
            int num2;
            if (num == 0U)
            {
                *span[0] = '0';
                num2 = 1;
            }
            else
            {
                num2 = 0;
                for (int i = 0; i < span.Length; i++)
                {
                    uint num3 = num / (uint)radix;
                    uint num4 = num - num3 * (uint)radix;
                    num = num3;
                    *span[i] = ((num4 < 10U) ? ((char)(num4 + 48U)) : ((char)(num4 + 97U - 10U)));
                    if (num == 0U)
                    {
                        num2 = i + 1;
                        break;
                    }
                }
            }
            if (radix != 10 && (flags & 32) != 0)
            {
                if (16 == radix)
                {
                    *span[num2++] = 'x';
                    *span[num2++] = '0';
                }
                else if (8 == radix)
                {
                    *span[num2++] = '0';
                }
            }
            if (10 == radix)
            {
                if (flag)
                {
                    *span[num2++] = '-';
                }
                else if ((flags & 16) != 0)
                {
                    *span[num2++] = '+';
                }
                else if ((flags & 8) != 0)
                {
                    *span[num2++] = ' ';
                }
            }
            string text = string.FastAllocateString(Math.Max(width, num2));
            fixed (string text2 = text)
            {
                char* ptr = text2;
                if (ptr != null)
                {
                    ptr += RuntimeHelpers.OffsetToStringData / 2;
                }
                char* ptr2 = ptr;
                int num5 = text.Length - num2;
                if ((flags & 1) != 0)
                {
                    for (int j = 0; j < num5; j++)
                    {
                        *(ptr2++) = paddingChar;
                    }
                    for (int k = 0; k < num2; k++)
                    {
                        *(ptr2++) = *span[num2 - k - 1];
                    }
                }
                else
                {
                    for (int l = 0; l < num2; l++)
                    {
                        *(ptr2++) = *span[num2 - l - 1];
                    }
                    for (int m = 0; m < num5; m++)
                    {
                        *(ptr2++) = paddingChar;
                    }
                }
            }
            return text;
        }
References System.Span< T >.Length, System.Math.Max(), System.text, and System.U.
Referenced by System.Convert.ToString(), System.Convert.ToString(), and System.Convert.ToString().