Terraria Decompiled: System.ParseNumbers.GrabInts
GrabInts()
static unsafe int System.ParseNumbers.GrabInts (int radix, ReadOnlySpan< char > s, ref int i, bool isUnsigned) inline static private
Definition at line 461 of file ParseNumbers.cs.
        {
            uint num = 0U;
            if (radix == 10 && !isUnsigned)
            {
                uint num2 = 214748364U;
                int num3;
                while (i < s.Length && ParseNumbers.IsDigit((char)(*s[i]), radix, out num3))
                {
                    if (num > num2 || num < 0U)
                    {
                        ParseNumbers.ThrowOverflowInt32Exception();
                    }
                    num = num * (uint)radix + (uint)num3;
                    i++;
                }
                if (num < 0U && num != 2147483648U)
                {
                    ParseNumbers.ThrowOverflowInt32Exception();
                }
            }
            else
            {
                uint num2 = ((radix == 10) ? 429496729U : ((radix == 16) ? 268435455U : ((radix == 8) ? 536870911U : 2147483647U)));
                int num4;
                while (i < s.Length && ParseNumbers.IsDigit((char)(*s[i]), radix, out num4))
                {
                    if (num > num2)
                    {
                        throw new OverflowException("Value was either too large or too small for a UInt32.");
                    }
                    uint num5 = num * (uint)radix + (uint)num4;
                    if (num5 < num)
                    {
                        ParseNumbers.ThrowOverflowUInt32Exception();
                    }
                    num = num5;
                    i++;
                }
            }
            return (int)num;
        }
References System.ParseNumbers.IsDigit(), System.s, System.ParseNumbers.ThrowOverflowInt32Exception(), System.ParseNumbers.ThrowOverflowUInt32Exception(), and System.U.
Referenced by System.ParseNumbers.StringToInt().