Terraria Decompiled: System.ParseNumbers.GrabLongs
GrabLongs()
static unsafe long System.ParseNumbers.GrabLongs (int radix, ReadOnlySpan< char > s, ref int i, bool isUnsigned) inline static private
Definition at line 417 of file ParseNumbers.cs.
        {
            ulong num = 0UL;
            if (radix == 10 && !isUnsigned)
            {
                ulong num2 = 922337203685477580UL;
                int num3;
                while (i < s.Length && ParseNumbers.IsDigit((char)(*s[i]), radix, out num3))
                {
                    if (num > num2 || num < 0UL)
                    {
                        ParseNumbers.ThrowOverflowInt64Exception();
                    }
                    num = num * (ulong)((long)radix) + (ulong)((long)num3);
                    i++;
                }
                if (num < 0UL && num != 9223372036854775808UL)
                {
                    ParseNumbers.ThrowOverflowInt64Exception();
                }
            }
            else
            {
                ulong num2 = ((radix == 10) ? 1844674407370955161UL : ((radix == 16) ? 1152921504606846975UL : ((radix == 8) ? 2305843009213693951UL : 9223372036854775807UL)));
                int num4;
                while (i < s.Length && ParseNumbers.IsDigit((char)(*s[i]), radix, out num4))
                {
                    if (num > num2)
                    {
                        ParseNumbers.ThrowOverflowUInt64Exception();
                    }
                    ulong num5 = num * (ulong)((long)radix) + (ulong)((long)num4);
                    if (num5 < num)
                    {
                        ParseNumbers.ThrowOverflowUInt64Exception();
                    }
                    num = num5;
                    i++;
                }
            }
            return (long)num;
        }
References System.ParseNumbers.IsDigit(), long, System.s, System.ParseNumbers.ThrowOverflowInt64Exception(), and System.ParseNumbers.ThrowOverflowUInt64Exception().
Referenced by System.ParseNumbers.StringToLong().