Terraria Decompiled: ReLogic.Utilities.Vector2D.Distance
Distance() [2/2]
static double ReLogic.Utilities.Vector2D.Distance (Vector2D value1, Vector2D value2) inline static
Definition at line 182 of file Vector2D.cs.
        {
            double num = value1.X - value2.X;
            double num2 = value1.Y - value2.Y;
            return Math.Sqrt(num * num + num2 * num2);
        }
References System.Math.Sqrt(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.WorldGen.AddPasses(), Terraria.WorldBuilding.Modifiers.RadialDither.Apply(), Terraria.GameContent.Generation.Dungeon.Halls.StairwellDungeonHall.CalculateZigZagSlope(), Terraria.Utils.Distance(), Terraria.Utils.Distance(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.GameContent.Biomes.DitherSnake.GetClosestLineTo(), Terraria.GameContent.Biomes.DitherSnake.GetRoomPositionInsideBorder(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.GameContent.Generation.Dungeon.DungeonCrawler.MakeDungeon(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.placeTrap(), and Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.SelectGoodRoomForHallway().