Terraria Decompiled: ReLogic.Utilities.Vector2D.Length
Length()
double ReLogic.Utilities.Vector2D.Length () inline
Definition at line 95 of file Vector2D.cs.
        {
            return Math.Sqrt(this.X * this.X + this.Y * this.Y);
        }
References System.Math.Sqrt(), ReLogic.Utilities.Vector2D.X, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.DungeonControlLine.CanPaint(), Terraria.GameContent.Biomes.DungeonControlLine.DungeonControlLine(), Terraria.WorldGen.GrowLivingTree(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.LegacyRoom(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.neonMossBiome(), Terraria.WorldGen.oceanCave(), Terraria.WorldGen.OrePatch(), Terraria.GameContent.Generation.ShapeBranch.Perform(), Terraria.Utils.PlotTileLine(), Terraria.Utils.PlotTileTale(), Terraria.GameContent.Generation.Dungeon.Halls.RegularDungeonHall.RegularHall(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreHallway(), Terraria.GameContent.Generation.Dungeon.LayoutProviders.DualDungeonLayoutProvider.HallwayCalculator.ScoreStairwell(), Terraria.WorldGen.ShellPile(), Terraria.GameContent.Biomes.GraniteBiome.SimulatePressure(), Terraria.GameContent.Generation.Dungeon.Halls.SineDungeonHall.SineHall(), and Terraria.WorldGen.StonePatch().