Terraria Decompiled: System.IO.Directory.InsecureSetCurrentDirectory
InsecureSetCurrentDirectory()
static void System.IO.Directory.InsecureSetCurrentDirectory (string path) inline static package
Definition at line 460 of file Directory.cs.
        {
            if (path == null)
            {
                throw new ArgumentNullException("path");
            }
            if (path.Trim().Length == 0)
            {
                throw new ArgumentException("path string must not be an empty string or whitespace string");
            }
            if (!Directory.Exists(path))
            {
                throw new DirectoryNotFoundException("Directory \"" + path + "\" not found.");
            }
            MonoIOError monoIOError;
            MonoIO.SetCurrentDirectory(path, out monoIOError);
            if (monoIOError != MonoIOError.ERROR_SUCCESS)
            {
                throw MonoIO.GetException(path, monoIOError);
            }
        }
References System.IO.Directory.Exists(), System.IO.MonoIO.GetException(), and System.IO.MonoIO.SetCurrentDirectory().