Terraria Decompiled: Steamworks.InteropHelp.SteamParamStringArray.SteamParamStringArray
SteamParamStringArray()
Steamworks.InteropHelp.SteamParamStringArray.SteamParamStringArray (IList< string > strings) inline
Definition at line 116 of file InteropHelp.cs.
            {
                if (strings == null)
                {
                    this.m_pSteamParamStringArray = IntPtr.Zero;
                    return;
                }
                this.m_Strings = new IntPtr[strings.Count];
                for (int i = 0; i < strings.Count; i++)
                {
                    byte[] array = new byte[Encoding.UTF8.GetByteCount(strings[i]) + 1];
                    Encoding.UTF8.GetBytes(strings[i], 0, strings[i].Length, array, 0);
                    this.m_Strings[i] = Marshal.AllocHGlobal(array.Length);
                    Marshal.Copy(array, 0, this.m_Strings[i], array.Length);
                }
                this.m_ptrStrings = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(IntPtr)) * this.m_Strings.Length);
                SteamParamStringArray_t steamParamStringArray_t = new SteamParamStringArray_t
                {
                    m_ppStrings = this.m_ptrStrings,
                    m_nNumStrings = this.m_Strings.Length
                };
                Marshal.Copy(this.m_Strings, 0, steamParamStringArray_t.m_ppStrings, this.m_Strings.Length);
                this.m_pSteamParamStringArray = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(SteamParamStringArray_t)));
                Marshal.StructureToPtr(steamParamStringArray_t, this.m_pSteamParamStringArray, false);
            }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.array, System.Runtime.InteropServices.Marshal.Copy(), System.Collections.Generic.ICollection< T >.Count, System.Text.Encoding.GetByteCount(), System.Text.Encoding.GetBytes(), Steamworks.SteamParamStringArray_t.m_ppStrings, Steamworks.InteropHelp.SteamParamStringArray.m_pSteamParamStringArray, Steamworks.InteropHelp.SteamParamStringArray.m_ptrStrings, Steamworks.InteropHelp.SteamParamStringArray.m_Strings, System.Runtime.InteropServices.Marshal.SizeOf(), System.Runtime.InteropServices.Marshal.StructureToPtr(), System.Text.Encoding.UTF8, and System.IntPtr.Zero.