Terraria Decompiled: Terraria.GameContent.LeashedEntity.NetModule.Sync
Sync()
static void Terraria.GameContent.LeashedEntity.NetModule.Sync (LeashedEntity entity, bool full, int toClient = -1) inline static
Definition at line 428 of file LeashedEntity.cs.
            {
                NetPacket netPacket = Terraria.Net.NetModule.CreatePacket<LeashedEntity.NetModule>(65530);
                netPacket.Writer.Write(full ? 1 : 2);
                netPacket.Writer.Write7BitEncodedInt(entity.whoAmI);
                netPacket.Writer.Write7BitEncodedInt(entity.Type);
                if (full)
                {
                    netPacket.Writer.Write(entity.AnchorPosition.X);
                    netPacket.Writer.Write(entity.AnchorPosition.Y);
                }
                entity.NetSend(netPacket.Writer, full);
                if (toClient >= 0)
                {
                    NetManager.Instance.SendToClient(netPacket, toClient);
                    return;
                }
                NetManager.Instance.Broadcast(netPacket, (int i) => Netplay.Clients[i].IsSectionActive(entity.SectionCoordinates), -1);
            }
References Terraria.GameContent.LeashedEntity.AnchorPosition, Terraria.Net.NetManager.Broadcast(), Terraria.Netplay.Clients, Terraria.Net.NetManager.Instance, Terraria.RemoteClient.IsSectionActive(), Terraria.GameContent.LeashedEntity.NetSend(), Terraria.GameContent.LeashedEntity.SectionCoordinates, Terraria.Net.NetManager.SendToClient(), Terraria.GameContent.LeashedEntity.Type, Terraria.GameContent.LeashedEntity.whoAmI, System.IO.BinaryWriter.Write(), System.IO.BinaryWriter.Write7BitEncodedInt(), Terraria.Net.NetPacket.Writer, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.
Referenced by Terraria.GameContent.LeashedEntity.AddNewEntity(), Terraria.GameContent.LeashedEntity.StreamNetUpdates(), and Terraria.GameContent.LeashedEntity.SectionEntityList.Sync().