Terraria Decompiled: Terraria.GameContent.LeashedEntity.NetModule.Deserialize
Deserialize()
override bool Terraria.GameContent.LeashedEntity.NetModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 397 of file LeashedEntity.cs.
            {
                LeashedEntity.NetModule.MessageType messageType = (LeashedEntity.NetModule.MessageType)reader.ReadByte();
                int num = reader.Read7BitEncodedInt();
                switch (messageType)
                {
                case LeashedEntity.NetModule.MessageType.Remove:
                    this.HandleRemove(num);
                    break;
                case LeashedEntity.NetModule.MessageType.FullSync:
                    LeashedEntity.NetModule.HandleFullSync(num, reader.Read7BitEncodedInt(), new Point16(reader.ReadInt16(), reader.ReadInt16()), reader);
                    break;
                case LeashedEntity.NetModule.MessageType.PartialSync:
                    LeashedEntity.NetModule.HandlePartialSync(num, reader.Read7BitEncodedInt(), reader);
                    break;
                default:
                    return false;
                }
                return true;
            }
References Terraria.GameContent.LeashedEntity.NetModule.HandleFullSync(), Terraria.GameContent.LeashedEntity.NetModule.HandlePartialSync(), Terraria.GameContent.LeashedEntity.NetModule.HandleRemove(), System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadByte(), and System.IO.BinaryReader.ReadInt16().