Terraria Decompiled: Terraria.GameContent.LeashedEntity.NetModule.HandleFullSync
HandleFullSync()
static void Terraria.GameContent.LeashedEntity.NetModule.HandleFullSync (int slot, int type, Point16 anchorPos, BinaryReader reader) inline static private
Definition at line 459 of file LeashedEntity.cs.
            {
                while (slot >= LeashedEntity.ByWhoAmI.Count)
                {
                    LeashedEntity.ByWhoAmI.Add(null);
                }
                LeashedEntity leashedEntity = LeashedEntity.ByWhoAmI[slot];
                if (leashedEntity == null)
                {
                    leashedEntity = LeashedEntity.Registry.Get(type).NewInstance();
                    LeashedEntity.AddNewEntity(leashedEntity, anchorPos, slot);
                }
                else if (leashedEntity.Type != type || leashedEntity.AnchorPosition != anchorPos)
                {
                    throw new Exception(string.Concat(new object[] { "LeashedEntity type mismatch for full sync. Slot: ", slot, " Existing: ", leashedEntity.Type, " @ ", leashedEntity.AnchorPosition, " New: ", type, " @ ", anchorPos }));
                }
                leashedEntity.NetReceive(reader, true);
            }
References Terraria.GameContent.LeashedEntity.AddNewEntity(), Terraria.GameContent.LeashedEntity.AnchorPosition, Terraria.GameContent.LeashedEntity.ByWhoAmI, Terraria.GameContent.LeashedEntity.Registry.Get(), Terraria.GameContent.LeashedEntity.NetReceive(), Terraria.GameContent.LeashedEntity.NewInstance(), and Terraria.GameContent.LeashedEntity.Type.
Referenced by Terraria.GameContent.LeashedEntity.NetModule.Deserialize().