Terraria Decompiled: Newtonsoft.Json.JsonTextWriter.WriteIntegerValue
WriteIntegerValue() [1/2]
void Newtonsoft.Json.JsonTextWriter.WriteIntegerValue (long value) inline private
Definition at line 601 of file JsonTextWriter.cs.
        {
            if (value >= 0L && value <= 9L)
            {
                this._writer.Write((char)(48L + value));
                return;
            }
            bool flag = value < 0L;
            this.WriteIntegerValue((ulong)(flag ? (-(ulong)value) : value), flag);
        }
References Newtonsoft.Json.JsonTextWriter._writer, System.L, System.value, System.IO.TextWriter.Write(), and Newtonsoft.Json.JsonTextWriter.WriteIntegerValue().
Referenced by Newtonsoft.Json.JsonTextWriter.WriteIntegerValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), Newtonsoft.Json.JsonTextWriter.WriteValue(), and Newtonsoft.Json.JsonTextWriter.WriteValue().