Terraria Decompiled: Newtonsoft.Json.JsonTextWriter.WriteValue
WriteValue() [3/23]
override void Newtonsoft.Json.JsonTextWriter.WriteValue (byte[] value) inline virtual
Reimplemented from Newtonsoft.Json.JsonWriter.
Definition at line 503 of file JsonTextWriter.cs.
        {
            if (value == null)
            {
                this.WriteNull();
                return;
            }
            base.InternalWriteValue(JsonToken.Bytes);
            this._writer.Write(this._quoteChar);
            this.Base64Encoder.Encode(value, 0, value.Length);
            this.Base64Encoder.Flush();
            this._writer.Write(this._quoteChar);
        }
References Newtonsoft.Json.JsonTextWriter._quoteChar, Newtonsoft.Json.JsonTextWriter._writer, Newtonsoft.Json.Utilities.Base64Encoder.Encode(), Newtonsoft.Json.Utilities.Base64Encoder.Flush(), System.value, System.IO.TextWriter.Write(), and Newtonsoft.Json.JsonTextWriter.WriteNull().