Terraria Decompiled: Newtonsoft.Json.JsonTextWriter.WriteValue
WriteValue() [5/23]
override void Newtonsoft.Json.JsonTextWriter.WriteValue (DateTime value) inline virtual
Reimplemented from Newtonsoft.Json.JsonWriter.
Definition at line 476 of file JsonTextWriter.cs.
        {
            base.InternalWriteValue(JsonToken.Date);
            value = DateTimeUtils.EnsureDateTime(value, base.DateTimeZoneHandling);
            if (string.IsNullOrEmpty(base.DateFormatString))
            {
                int num = this.WriteValueToBuffer(value);
                this._writer.Write(this._writeBuffer, 0, num);
                return;
            }
            this._writer.Write(this._quoteChar);
            this._writer.Write(value.ToString(base.DateFormatString, base.Culture));
            this._writer.Write(this._quoteChar);
        }
References Newtonsoft.Json.JsonTextWriter._quoteChar, Newtonsoft.Json.JsonTextWriter._writeBuffer, Newtonsoft.Json.JsonTextWriter._writer, Newtonsoft.Json.Utilities.DateTimeUtils.EnsureDateTime(), System.DateTime.ToString(), System.value, System.IO.TextWriter.Write(), and Newtonsoft.Json.JsonTextWriter.WriteValueToBuffer().