Terraria Decompiled: Newtonsoft.Json.JsonTextWriter.WriteValue
WriteValue() [6/23]
override void Newtonsoft.Json.JsonTextWriter.WriteValue (DateTimeOffset value) inline virtual
Reimplemented from Newtonsoft.Json.JsonWriter.
Definition at line 518 of file JsonTextWriter.cs.
        {
            base.InternalWriteValue(JsonToken.Date);
            if (string.IsNullOrEmpty(base.DateFormatString))
            {
                int num = this.WriteValueToBuffer(value);
                this._writer.Write(this._writeBuffer, 0, num);
                return;
            }
            this._writer.Write(this._quoteChar);
            this._writer.Write(value.ToString(base.DateFormatString, base.Culture));
            this._writer.Write(this._quoteChar);
        }
References Newtonsoft.Json.JsonTextWriter._quoteChar, Newtonsoft.Json.JsonTextWriter._writeBuffer, Newtonsoft.Json.JsonTextWriter._writer, System.DateTimeOffset.ToString(), System.IO.TextWriter.Write(), and Newtonsoft.Json.JsonTextWriter.WriteValueToBuffer().