Terraria Decompiled: Newtonsoft.Json.JsonTextWriter.WriteIndent
WriteIndent()
override void Newtonsoft.Json.JsonTextWriter.WriteIndent () inline protected virtual
Reimplemented from Newtonsoft.Json.JsonWriter.
Definition at line 251 of file JsonTextWriter.cs.
        {
            int num = base.Top * this._indentation;
            int num2 = this.SetIndentChars();
            this._writer.Write(this._indentChars, 0, num2 + Math.Min(num, 12));
            while ((num -= 12) > 0)
            {
                this._writer.Write(this._indentChars, num2, Math.Min(num, 12));
            }
        }
References Newtonsoft.Json.JsonTextWriter._indentation, Newtonsoft.Json.JsonTextWriter._indentChars, Newtonsoft.Json.JsonTextWriter._writer, System.Math.Min(), Newtonsoft.Json.JsonTextWriter.SetIndentChars(), and System.IO.TextWriter.Write().