Terraria Decompiled: Newtonsoft.Json.JsonTextWriter.WriteNumberToBuffer
WriteNumberToBuffer()
int Newtonsoft.Json.JsonTextWriter.WriteNumberToBuffer (ulong value, bool negative) inline private
Definition at line 625 of file JsonTextWriter.cs.
        {
            this.EnsureWriteBuffer();
            int num = MathUtils.IntLength(value);
            if (negative)
            {
                num++;
                this._writeBuffer[0] = '-';
            }
            int num2 = num;
            do
            {
                this._writeBuffer[--num2] = (char)(48UL + value % 10UL);
                value /= 10UL;
            }
            while (value != 0UL);
            return num;
        }
References Newtonsoft.Json.JsonTextWriter._writeBuffer, Newtonsoft.Json.JsonTextWriter.EnsureWriteBuffer(), Newtonsoft.Json.Utilities.MathUtils.IntLength(), and System.value.
Referenced by Newtonsoft.Json.JsonTextWriter.WriteIntegerValue().