Terraria Decompiled: Terraria.Map.TeleportPylonsMapLayer.DrawLine
DrawLine()
static void Terraria.Map.TeleportPylonsMapLayer.DrawLine (SpriteBatch spriteBatch, Vector2 start, Vector2 end, Color col, float width) inline static
Definition at line 18 of file TeleportPylonsMapLayer.cs.
        {
            float num = Vector2.Distance(start, end);
            float num2 = (end - start).ToRotation();
            int num3 = Math.Min(5, (int)num);
            Rectangle rectangle = TextureAssets.BlackTile.Value.Frame(1, 1, 0, 0, 0, 0);
            for (int i = 0; i < num3; i++)
            {
                spriteBatch.Draw(TextureAssets.BlackTile.Value, Vector2.Lerp(start, end, (float)i / (float)num3), new Rectangle?(rectangle), col, num2, new Vector2(0f, (float)rectangle.Width * 0.5f), new Vector2(num / (float)num3 / 16f, width / 16f), SpriteEffects.None, 0f);
            }
        }
References Terraria.GameContent.TextureAssets.BlackTile, Microsoft.Xna.Framework.Vector2.Distance(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Vector2.Lerp(), System.Math.Min(), System.start, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Map.TeleportPylonsMapLayer.Draw().