Terraria Decompiled: Terraria.Map.TeleportPylonsMapLayer.Draw
Draw()
void Terraria.Map.TeleportPylonsMapLayer.Draw (ref MapOverlayDrawContext context, ref string text) inline
Implements Terraria.Map.IMapLayer.
Definition at line 31 of file TeleportPylonsMapLayer.cs.
        {
            List<TeleportPylonInfo> pylons = Main.PylonSystem.Pylons;
            float num = 1f;
            float num2 = num * 2f;
            float num3 = num * 0.5f;
            Texture2D value = TextureAssets.Extra[182].Value;
            Texture2D value2 = TextureAssets.Extra[299].Value;
            Color color = Color.White;
            if (!TeleportPylonsSystem.IsPlayerNearAPylon(Main.LocalPlayer))
            {
                color = Color.Gray * 0.5f;
            }
            bool flag = false;
            int num4 = -1;
            if (Main.mapFullscreen && Main.MapPylonTile.X != -1 && Main.MapPylonTile.Y != -1)
            {
                Texture2D texture2D = value;
                Vector2 vector = Main.MapPylonTile.ToVector2() + new Vector2(1.5f, 2f);
                SpriteFrame spriteFrame = new SpriteFrame(11, 1, 0, 0)
                {
                    PaddingY = 0
                };
                Point center = context.GetUnclampedDrawRegion(texture2D, vector, spriteFrame, num, Alignment.Center).Center;
                for (int i = 0; i < pylons.Count; i++)
                {
                    TeleportPylonInfo teleportPylonInfo = pylons[i];
                    if (TeleportPylonsMapLayer.IsRevealed(teleportPylonInfo) && !(teleportPylonInfo.PositionInTiles == Main.MapPylonTile))
                    {
                        Texture2D texture2D2 = value;
                        Vector2 vector2 = teleportPylonInfo.PositionInTiles.ToVector2() + new Vector2(1.5f, 2f);
                        spriteFrame = new SpriteFrame(11, 1, 0, 0)
{
                            PaddingY = 0
                        };
                        Point center2 = context.GetUnclampedDrawRegion(texture2D2, vector2, spriteFrame, num, Alignment.Center).Center;
                        TeleportPylonsMapLayer.DrawLine(Main.spriteBatch, center.ToVector2(), center2.ToVector2(), Color.Black, 6f);
                        TeleportPylonsMapLayer.DrawLine(Main.spriteBatch, center.ToVector2(), center2.ToVector2(), Color.White, 2f);
                    }
                }
            }
            for (int j = 0; j < pylons.Count; j++)
            {
                TeleportPylonInfo teleportPylonInfo2 = pylons[j];
                if (TeleportPylonsMapLayer.IsRevealed(teleportPylonInfo2))
                {
                    bool flag2 = true;
                    MapOverlayDrawContext.DrawResult drawResult;
                    if (Main.mapFullscreen)
                    {
                        Texture2D texture2D3 = value;
                        Texture2D texture2D4 = value2;
                        Vector2 vector3 = teleportPylonInfo2.PositionInTiles.ToVector2() + new Vector2(1.5f, 2f);
                        Color color2 = color;
                        SpriteFrame spriteFrame = new SpriteFrame(11, 1, (byte)teleportPylonInfo2.TypeOfPylon, 0)
{
                            PaddingY = 0
                        };
                        drawResult = context.DrawClamped(texture2D3, texture2D4, vector3, color2, spriteFrame, num, num2, num3, Alignment.Center, 10, out flag2);
                    }
                    else
                    {
                        Texture2D texture2D5 = value;
                        Vector2 vector4 = teleportPylonInfo2.PositionInTiles.ToVector2() + new Vector2(1.5f, 2f);
                        Color color3 = color;
                        SpriteFrame spriteFrame = new SpriteFrame(11, 1, (byte)teleportPylonInfo2.TypeOfPylon, 0)
{
                            PaddingY = 0
                        };
                        drawResult = context.Draw(texture2D5, vector4, color3, spriteFrame, num, num2, Alignment.Center);
                    }
                    if (drawResult.IsMouseOver)
                    {
                        Main.cancelWormHole = true;
                        string itemNameValue = Lang.GetItemNameValue(TETeleportationPylon.GetPylonItemTypeFromTileStyle((int)teleportPylonInfo2.TypeOfPylon));
                        text = itemNameValue;
                        if (Main.mouseLeft && Main.mouseLeftRelease)
{
                            flag = flag2;
                            num4 = j;
                        }
                    }
                }
            }
            if (num4 != -1 && Main.mouseLeft && Main.mouseLeftRelease)
            {
                TeleportPylonInfo teleportPylonInfo3 = pylons[num4];
                if (flag)
                {
                    Main.mouseLeftRelease = false;
                    Main.mapFullscreen = false;
                    PlayerInput.LockGamepadButtons("MouseLeft");
                    Main.PylonSystem.RequestTeleportation(teleportPylonInfo3, Main.LocalPlayer);
                    SoundEngine.PlaySound(11, -1, -1, 1, 1f, 0f);
                    return;
                }
                Main.mouseLeftRelease = false;
                PlayerInput.LockGamepadButtons("MouseLeft");
                Main.PanTargetMapFullscreen = true;
                Main.PanTargetMapFullscreenEnd.X = (float)teleportPylonInfo3.PositionInTiles.X;
                Main.PanTargetMapFullscreenEnd.Y = (float)teleportPylonInfo3.PositionInTiles.Y;
            }
        }
References Microsoft.Xna.Framework.Color.Black, Terraria.UI.Alignment.Center, System.Collections.Generic.List< T >.Count, Terraria.Map.TeleportPylonsMapLayer.DrawLine(), Terraria.GameContent.TextureAssets.Extra, Terraria.Lang.GetItemNameValue(), Terraria.GameContent.Tile_Entities.TETeleportationPylon.GetPylonItemTypeFromTileStyle(), Terraria.Map.MapOverlayDrawContext.DrawResult.IsMouseOver, Terraria.GameContent.TeleportPylonsSystem.IsPlayerNearAPylon(), Terraria.Map.TeleportPylonsMapLayer.IsRevealed(), Terraria.Main.LocalPlayer, Terraria.GameInput.PlayerInput.LockGamepadButtons(), Terraria.Main.mapFullscreen, Terraria.Main.MapPylonTile, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Audio.SoundEngine.PlaySound(), Terraria.GameContent.TeleportPylonInfo.PositionInTiles, Terraria.GameContent.TeleportPylonsSystem.Pylons, Terraria.Main.PylonSystem, Terraria.GameContent.TeleportPylonsSystem.RequestTeleportation(), Terraria.Main.spriteBatch, System.text, Terraria.GameContent.TeleportPylonInfo.TypeOfPylon, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.DataStructures.Point16.X, and Terraria.DataStructures.Point16.Y.