Terraria Decompiled: System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >
AwaitUnsafeOnCompleted< TAwaiter, TStateMachine >()
void System.Runtime.CompilerServices.AsyncVoidMethodBuilder.AwaitUnsafeOnCompleted< TAwaiter, TStateMachine > (ref TAwaiter awaiter, ref TStateMachine stateMachine) inline
Type Constraints
TAwaiter : ICriticalNotifyCompletion
TStateMachine : IAsyncStateMachine
Definition at line 81 of file AsyncVoidMethodBuilder.cs.
                                                                                                                                         : ICriticalNotifyCompletion where TStateMachine : IAsyncStateMachine
        {
            try
            {
                AsyncMethodBuilderCore.MoveNextRunner moveNextRunner = null;
                Action completionAction = this.m_coreState.GetCompletionAction(AsyncCausalityTracer.LoggingOn ? this.Task : null, ref moveNextRunner);
                if (this.m_coreState.m_stateMachine == null)
                {
                    if (AsyncCausalityTracer.LoggingOn)
                    {
                        AsyncCausalityTracer.TraceOperationCreation(CausalityTraceLevel.Required, this.Task.Id, "Async: " + stateMachine.GetType().Name, 0UL);
                    }
                    this.m_coreState.PostBoxInitialization(stateMachine, moveNextRunner, null);
                }
                awaiter.UnsafeOnCompleted(completionAction);
            }
            catch (Exception ex)
            {
                AsyncMethodBuilderCore.ThrowAsync(ex, null);
            }
        }
References System.Runtime.CompilerServices.AsyncMethodBuilderCore.GetCompletionAction(), System.Threading.Tasks.AsyncCausalityTracer.LoggingOn, System.Runtime.CompilerServices.AsyncVoidMethodBuilder.m_coreState, System.Runtime.CompilerServices.AsyncMethodBuilderCore.m_stateMachine, System.Runtime.CompilerServices.AsyncMethodBuilderCore.PostBoxInitialization(), System.Runtime.CompilerServices.AsyncMethodBuilderCore.ThrowAsync(), and System.Threading.Tasks.AsyncCausalityTracer.TraceOperationCreation().