Terraria Decompiled: ReLogic.Peripherals.RGB.Corsair.CorsairHelper.GetLedPositionsForMouseMatOrKeyboard
GetLedPositionsForMouseMatOrKeyboard()
static CorsairLedPosition[] ReLogic.Peripherals.RGB.Corsair.CorsairHelper.GetLedPositionsForMouseMatOrKeyboard (int deviceIndex) inline static
Definition at line 47 of file CorsairHelper.cs.
        {
            IntPtr intPtr = NativeMethods.CorsairGetLedPositionsByDeviceIndex(deviceIndex);
            if (intPtr == IntPtr.Zero)
            {
                return new CorsairLedPosition[0];
            }
            CorsairLedPositions corsairLedPositions = (CorsairLedPositions)Marshal.PtrToStructure(intPtr, typeof(CorsairLedPositions));
            int numberOfLed = corsairLedPositions.NumberOfLed;
            CorsairLedPosition[] array = new CorsairLedPosition[numberOfLed];
            int num = Marshal.SizeOf(typeof(CorsairLedPosition));
            for (int i = 0; i < numberOfLed; i++)
            {
                array[i] = (CorsairLedPosition)Marshal.PtrToStructure(corsairLedPositions.LedPositionPtr, typeof(CorsairLedPosition));
                corsairLedPositions.LedPositionPtr += num;
            }
            return array;
        }
References System.array, ReLogic.Peripherals.RGB.Corsair.NativeMethods.CorsairGetLedPositionsByDeviceIndex(), ReLogic.Peripherals.RGB.Corsair.CorsairLedPositions.LedPositionPtr, ReLogic.Peripherals.RGB.Corsair.CorsairLedPositions.NumberOfLed, System.Runtime.InteropServices.Marshal.PtrToStructure(), System.Runtime.InteropServices.Marshal.SizeOf(), and System.IntPtr.Zero.
Referenced by ReLogic.Peripherals.RGB.Corsair.CorsairKeyboard.Create(), and ReLogic.Peripherals.RGB.Corsair.CorsairMousepad.Create().