Terraria Decompiled: Microsoft.Win32.UnixRegistryApi.DeleteKey
DeleteKey()
void Microsoft.Win32.UnixRegistryApi.DeleteKey (RegistryKey rkey, string keyname, bool throw_if_missing) inline
Implements Microsoft.Win32.IRegistryApi.
Definition at line 159 of file UnixRegistryApi.cs.
        {
            KeyHandler keyHandler = KeyHandler.Lookup(rkey, true);
            if (keyHandler == null)
            {
                if (!throw_if_missing)
                {
                    return;
                }
                throw new ArgumentException("the given value does not exist");
            }
            else
            {
                if (!KeyHandler.Delete(Path.Combine(keyHandler.Dir, UnixRegistryApi.ToUnix(keyname))) && throw_if_missing)
                {
                    throw new ArgumentException("the given value does not exist");
                }
                return;
            }
        }
References System.IO.Path.Combine(), Microsoft.Win32.KeyHandler.Delete(), Microsoft.Win32.KeyHandler.Dir, Microsoft.Win32.KeyHandler.Lookup(), and Microsoft.Win32.UnixRegistryApi.ToUnix().