Terraria Decompiled: rail.IRailZoneServerImpl.GetChildrenZoneIDs
GetChildrenZoneIDs()
virtual RailResult rail.IRailZoneServerImpl.GetChildrenZoneIDs (List< RailZoneID > zone_ids) inline virtual
Implements rail.IRailZoneServer.
Definition at line 144 of file IRailZoneServerImpl.cs.
        {
            IntPtr intPtr = ((zone_ids == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailArrayRailZoneID__SWIG_0());
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailZoneServer_GetChildrenZoneIDs(this.swigCPtr_, intPtr);
            }
            finally
            {
                if (zone_ids != null)
                {
                    RailConverter.Cpp2Csharp(intPtr, zone_ids);
                }
                RAIL_API_PINVOKE.delete_RailArrayRailZoneID(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Cpp2Csharp(), rail.RAIL_API_PINVOKE.delete_RailArrayRailZoneID(), rail.RAIL_API_PINVOKE.IRailZoneServer_GetChildrenZoneIDs(), rail.RAIL_API_PINVOKE.new_RailArrayRailZoneID__SWIG_0(), and System.IntPtr.Zero.