Terraria Decompiled: Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 43 of file UIGenProgressBar.cs.
        {
            if (!this._texOuterCorrupt.IsLoaded || !this._texOuterCrimson.IsLoaded || !this._texOuterRandom.IsLoaded || !this._texOuterLower.IsLoaded)
            {
                return;
            }
            bool flag = WorldGen.crimson;
            bool flag2 = WorldGen.generatingRandomEvil;
            if (WorldGen.drunkWorldGen && Main.rand.Next(2) == 0)
            {
                flag = Main.rand.Next(2) == 0;
                flag2 = Main.rand.Next(4) == 0;
            }
            this._visualOverallProgress = this._targetOverallProgress;
            this._visualCurrentProgress = this._targetCurrentProgress;
            CalculatedStyle dimensions = base.GetDimensions();
            int num = (int)(this._visualOverallProgress * (float)this._longBarWidth);
            int num2 = (int)(this._visualCurrentProgress * (float)this._smallBarWidth);
            Vector2 vector = new Vector2(dimensions.X, dimensions.Y);
            Color color = default(Color);
            color.PackedValue = (flag2 ? 4292696893U : (flag ? 4286836223U : 4283888223U));
            this.DrawFilling2(spriteBatch, vector + new Vector2(20f, 40f), 16, num, this._longBarWidth, color, Color.Lerp(color, Color.Black, 0.5f), new Color(48, 48, 48));
            color.PackedValue = 4290947159U;
            this.DrawFilling2(spriteBatch, vector + new Vector2(50f, 60f), 8, num2, this._smallBarWidth, color, Color.Lerp(color, Color.Black, 0.5f), new Color(33, 33, 33));
            Rectangle rectangle = base.GetDimensions().ToRectangle();
            rectangle.X -= 8;
            Texture2D texture2D = (flag2 ? this._texOuterRandom.Value : (flag ? this._texOuterCrimson.Value : this._texOuterCorrupt.Value));
            spriteBatch.Draw(texture2D, rectangle.TopLeft(), Color.White);
            spriteBatch.Draw(this._texOuterLower.Value, rectangle.TopLeft() + new Vector2(44f, 60f), Color.White);
        }
References Terraria.GameContent.UI.Elements.UIGenProgressBar._longBarWidth, Terraria.GameContent.UI.Elements.UIGenProgressBar._smallBarWidth, Terraria.GameContent.UI.Elements.UIGenProgressBar._targetCurrentProgress, Terraria.GameContent.UI.Elements.UIGenProgressBar._targetOverallProgress, Terraria.GameContent.UI.Elements.UIGenProgressBar._texOuterCorrupt, Terraria.GameContent.UI.Elements.UIGenProgressBar._texOuterLower, Terraria.GameContent.UI.Elements.UIGenProgressBar._visualCurrentProgress, Terraria.GameContent.UI.Elements.UIGenProgressBar._visualOverallProgress, Microsoft.Xna.Framework.Color.Black, Terraria.WorldGen.crimson, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.Elements.UIGenProgressBar.DrawFilling2(), Terraria.WorldGen.drunkWorldGen, Terraria.WorldGen.generatingRandomEvil, int, ReLogic.Content.Asset< T >.IsLoaded, Microsoft.Xna.Framework.Color.Lerp(), Terraria.Main.rand, System.U, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Terraria.UI.CalculatedStyle.X, and Terraria.UI.CalculatedStyle.Y.