Terraria Decompiled: System.TermInfoReader.TermInfoReader
TermInfoReader() [1/2]
System.TermInfoReader.TermInfoReader (string term, string filename) inline
Definition at line 11 of file TermInfoReader.cs.
        {
            using (FileStream fileStream = File.OpenRead(filename))
            {
                long length = fileStream.Length;
                if (length > 4096L)
                {
                    throw new Exception("File must be smaller than 4K");
                }
                this.buffer = new byte[(int)length];
                if (fileStream.Read(this.buffer, 0, this.buffer.Length) != this.buffer.Length)
                {
                    throw new Exception("Short read");
                }
                this.ReadHeader(this.buffer, ref this.booleansOffset);
                this.ReadNames(this.buffer, ref this.booleansOffset);
            }
        }
References System.TermInfoReader.booleansOffset, System.TermInfoReader.buffer, int, System.L, System.length, System.IO.FileStream.Length, System.IO.File.OpenRead(), System.IO.FileStream.Read(), System.TermInfoReader.ReadHeader(), and System.TermInfoReader.ReadNames().