Terraria Decompiled: Steamworks.SteamVideo.GetOPFStringForApp
GetOPFStringForApp()
static bool Steamworks.SteamVideo.GetOPFStringForApp (AppId_t unVideoAppID, out string pchBuffer, ref int pnBufferSize) inline static
Definition at line 31 of file SteamVideo.cs.
        {
            InteropHelp.TestIfAvailableClient();
            IntPtr intPtr = Marshal.AllocHGlobal(pnBufferSize);
            bool flag = NativeMethods.ISteamVideo_GetOPFStringForApp(CSteamAPIContext.GetSteamVideo(), unVideoAppID, intPtr, ref pnBufferSize);
            pchBuffer = (flag ? InteropHelp.PtrToStringUTF8(intPtr) : null);
            Marshal.FreeHGlobal(intPtr);
            return flag;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CSteamAPIContext.GetSteamVideo(), Steamworks.NativeMethods.ISteamVideo_GetOPFStringForApp(), Steamworks.InteropHelp.PtrToStringUTF8(), and Steamworks.InteropHelp.TestIfAvailableClient().