Terraria Decompiled: Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall
CreateDentForHoneyFall()
static void Terraria.GameContent.Biomes.HiveBiome.CreateDentForHoneyFall (int x, int y, int dir) inline static private
Definition at line 301 of file HiveBiome.cs.
        {
            dir *= -1;
            y++;
            int num = 0;
            while ((num < 4 || WorldGen.SolidTile(x, y, false)) && x > 10 && x < Main.maxTilesX - 10)
            {
                num++;
                x += dir;
                if (WorldGen.SolidTile(x, y, false))
                {
                    WorldGen.PoundTile(x, y);
                    if (!Main.tile[x, y + 1].active())
                    {
                        Main.tile[x, y + 1].active(true);
                        Main.tile[x, y + 1].type = 225;
                    }
                }
            }
        }
References Terraria.Tile.active(), Terraria.Main.maxTilesX, Terraria.WorldGen.PoundTile(), Terraria.WorldGen.SolidTile(), Terraria.Main.tile, and Terraria.Tile.type.