Terraria Decompiled: Terraria.GameContent.Biomes.HiveBiome.Place
Place()
override bool Terraria.GameContent.Biomes.HiveBiome.Place (Point origin, StructureMap structures, GenerationProgress progress) inline
Definition at line 13 of file HiveBiome.cs.
        {
            if (!structures.CanPlace(new Rectangle(origin.X - 50, origin.Y - 50, 100, 100), 0))
            {
                return false;
            }
            if (HiveBiome.TooCloseToImportantLocations(origin))
            {
                return false;
            }
            Ref<int> @ref = new Ref<int>(0);
            Ref<int> ref2 = new Ref<int>(0);
            Ref<int> ref3 = new Ref<int>(0);
            WorldUtils.Gen(origin, new Shapes.Circle(15), Actions.Chain(new GenAction[]
            {
                new Modifiers.IsSolid(),
                new Actions.Scanner(@ref),
                new Modifiers.OnlyTiles(new ushort[] { 60, 59 }),
                new Actions.Scanner(ref2),
                new Modifiers.OnlyTiles(new ushort[] { 60 }),
                new Actions.Scanner(ref3)
            }));
            if ((double)ref2.Value / (double)@ref.Value < 0.75 || ref3.Value < 2)
            {
                return false;
            }
            int num = 0;
            int[] array = new int[1000];
            int[] array2 = new int[1000];
            Vector2D vector2D = origin.ToVector2D();
            int num2 = WorldGen.genRand.Next(2, 5);
            if (WorldGen.drunkWorldGen)
            {
                num2 += WorldGen.genRand.Next(7, 10);
            }
            else if (WorldGen.remixWorldGen)
            {
                num2 += WorldGen.genRand.Next(2, 5);
            }
            for (int i = 0; i < num2; i++)
            {
                Vector2D vector2D2 = vector2D;
                int num3 = WorldGen.genRand.Next(2, 5);
                for (int j = 0; j < num3; j++)
                {
                    vector2D2 = HiveBiome.CreateHiveTunnel((int)vector2D.X, (int)vector2D.Y, WorldGen.genRand);
                }
                vector2D = vector2D2;
                array[num] = (int)vector2D.X;
                array2[num] = (int)vector2D.Y;
                num++;
            }
            HiveBiome.FrameOutAllHiveContents(origin, 50);
            for (int k = 0; k < num; k++)
            {
                int num4 = array[k];
                int num5 = array2[k];
                int num6 = 1;
                if (WorldGen.genRand.Next(2) == 0)
                {
                    num6 = -1;
                }
                bool flag = false;
                while (WorldGen.InWorld(num4, num5, 10) && HiveBiome.BadSpotForHoneyFall(num4, num5))
                {
                    num4 += num6;
                    if (Math.Abs(num4 - array[k]) > 50)
                    {
                        flag = true;
                        break;
                    }
                }
                if (!flag)
                {
                    num4 += num6;
                    if (!HiveBiome.SpotActuallyNotInHive(num4, num5))
                    {
                        HiveBiome.CreateBlockedHoneyCube(num4, num5);
                        HiveBiome.CreateDentForHoneyFall(num4, num5, num6);
                    }
                }
            }
            HiveBiome.CreateStandForLarva(vector2D);
            if (WorldGen.drunkWorldGen)
            {
                for (int l = 0; l < 1000; l++)
                {
                    Vector2D vector2D3 = vector2D;
                    vector2D3.X += (double)WorldGen.genRand.Next(-50, 51);
                    vector2D3.Y += (double)WorldGen.genRand.Next(-50, 51);
                    if (WorldGen.InWorld((int)vector2D3.X, (int)vector2D3.Y, 0) && Vector2D.Distance(vector2D, vector2D3) > 10.0 && !Main.tile[(int)vector2D3.X, (int)vector2D3.Y].active() && Main.tile[(int)vector2D3.X, (int)vector2D3.Y].wall == 86)
                    {
                        HiveBiome.CreateStandForLarva(vector2D3);
                        break;
                    }
                }
            }
            structures.AddProtectedStructure(new Rectangle(origin.X - 50, origin.Y - 50, 100, 100), 5);
            return true;
        }
References Terraria.WorldBuilding.StructureMap.CanPlace(), Terraria.WorldBuilding.Actions.Chain(), Terraria.WorldBuilding.WorldUtils.Gen(), Terraria.GameContent.Biomes.HiveBiome.TooCloseToImportantLocations(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldGen.AddPasses().