Terraria Decompiled: Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary
PrepareTextureIfNecessary()
void Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareTextureIfNecessary (Texture2D originalTexture, Rectangle? sourceRect = null) inline protected
Definition at line 311 of file TilePaintSystemV2.cs.
            {
                if (this.Target != null && !this.Target.IsContentLost)
                {
                    return;
                }
                Main instance = Main.instance;
                if (sourceRect == null)
                {
                    sourceRect = new Rectangle?(originalTexture.Frame(1, 1, 0, 0, 0, 0));
                }
                this.Target = new RenderTarget2D(instance.GraphicsDevice, sourceRect.Value.Width, sourceRect.Value.Height, false, instance.GraphicsDevice.PresentationParameters.BackBufferFormat, DepthFormat.None, 0, RenderTargetUsage.PreserveContents);
                this.Target.ContentLost += this.Target_ContentLost;
                this.Target.Disposing += this.Target_Disposing;
                this.Target.Name = originalTexture.Name;
                instance.GraphicsDevice.SetRenderTarget(this.Target);
                instance.GraphicsDevice.Clear(Color.Transparent);
                Main.spriteBatch.Begin(SpriteSortMode.Immediate, BlendState.AlphaBlend);
                this.PrepareShader();
                Rectangle value = sourceRect.Value;
                value.X = 0;
                value.Y = 0;
                Main.spriteBatch.Draw(originalTexture, value, Color.White);
                Main.spriteBatch.End();
                instance.GraphicsDevice.SetRenderTarget(null);
                this._wasPrepared = true;
            }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.PresentationParameters.BackBufferFormat, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.Clear(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Microsoft.Xna.Framework.Game.GraphicsDevice, Terraria.Main.instance, Microsoft.Xna.Framework.Graphics.RenderTarget2D.IsContentLost, Microsoft.Xna.Framework.Graphics.Texture.Name, Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.PrepareShader(), Microsoft.Xna.Framework.Graphics.GraphicsDevice.PresentationParameters, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetRenderTarget(), Terraria.Main.spriteBatch, Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.Target, Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.Target_ContentLost(), Terraria.GameContent.TilePaintSystemV2.ARenderTargetHolder.Target_Disposing(), Microsoft.Xna.Framework.Color.Transparent, System.value, and Microsoft.Xna.Framework.Color.White.