Terraria Decompiled: Terraria.GameContent.NPCInteractions.Initialize
Initialize()
static void Terraria.GameContent.NPCInteractions.Initialize () inline static
Definition at line 16 of file NPCInteractions.cs.
        {
            NPCInteractions.Shop(17, 1, null);
            NPCInteractions.Shop(19, 2, null);
            NPCInteractions.Shop(20, 3, null);
            NPCInteractions.Shop(38, 4, null);
            NPCInteractions.Shop(54, 5, null);
            NPCInteractions.Shop(107, 6, null);
            NPCInteractions.Shop(108, 7, null);
            NPCInteractions.Shop(124, 8, null);
            NPCInteractions.Shop(142, 9, null);
            NPCInteractions.Shop(160, 10, null);
            NPCInteractions.Shop(178, 11, null);
            NPCInteractions.Shop(207, 12, null);
            NPCInteractions.Shop(208, 13, null);
            NPCInteractions.Shop(209, 14, null);
            NPCInteractions.Shop(227, 15, null);
            NPCInteractions.Shop(228, 16, null);
            NPCInteractions.Shop(229, 17, null);
            NPCInteractions.Shop(353, 18, null);
            NPCInteractions.Shop(368, 19, null);
            NPCInteractions.Shop(453, 20, null);
            NPCInteractions.Shop(550, 21, null);
            NPCInteractions.Shop(588, 22, null);
            NPCInteractions.Shop(633, 23, null);
            NPCInteractions.Shop(663, 24, null);
            NPCInteractions.Shop(227, 25, "GameUI.PainterDecor");
            NPCInteractions.Register(new NPCInteractions.Actions.TaxCollectorCollectTaxes());
            NPCInteractions.Register(new NPCInteractions.Actions.NurseHeal());
            NPCInteractions.Register(new NPCInteractions.Actions.CloseChat());
            NPCInteractions.Register(new NPCInteractions.Actions.OpenSign());
            NPCInteractions.Register(new NPCInteractions.Actions.StardewValleyBit());
            NPCInteractions.Register(new NPCInteractions.Actions.DryadPurification());
            NPCInteractions.Register(new NPCInteractions.Actions.AnglerQuest());
            NPCInteractions.Register(new NPCInteractions.Actions.PetAnimal());
            NPCInteractions.Register(new NPCInteractions.Actions.OldManCurse());
            NPCInteractions.Register(new NPCInteractions.Actions.GuideTip());
            NPCInteractions.Register(new NPCInteractions.Actions.PartyGirlMusicSwap());
            NPCInteractions.Register(new NPCInteractions.Actions.GuideReverseCrafting());
            NPCInteractions.Register(new NPCInteractions.Actions.TinkererReforge());
            NPCInteractions.Register(new NPCInteractions.Actions.StylistHairWindow());
            NPCInteractions.Register(new NPCInteractions.Actions.DyeTraderRarePlant());
            NPCInteractions.Register(new NPCInteractions.Actions.TavernkeepAdvice());
            NPCInteractions.Register(new NPCInteractions.Actions.ReportHappiness());
            NPCInteractions.Register(new NPCInteractions.Actions.RequestHome());
        }
References Terraria.GameContent.NPCInteractions.Register(), and Terraria.GameContent.NPCInteractions.Shop().
Referenced by Terraria.Main.Initialize_AlmostEverything().