Terraria Decompiled: Terraria.UI.CoinSlot.DrawItemCoin
DrawItemCoin()
static float Terraria.UI.CoinSlot.DrawItemCoin (SpriteBatch spriteBatch, Vector2 screenPositionForItemCenter, int coinType, int coinFrame, float scale, float sizeLimit, Color itemColor, float itemFade = 1f) inline static
Definition at line 32 of file CoinSlot.cs.
        {
            int num = coinType - 71;
            Texture2D value = TextureAssets.Coin[num].Value;
            Rectangle rectangle = value.Frame(1, 8, 0, coinFrame, 0, 0);
            Color white = Color.White;
            Color white2 = Color.White;
            float num2 = 1f;
            if ((float)rectangle.Width > sizeLimit || (float)rectangle.Height > sizeLimit)
            {
                if (rectangle.Width > rectangle.Height)
                {
                    num2 = sizeLimit / (float)rectangle.Width;
                }
                else
                {
                    num2 = sizeLimit / (float)rectangle.Height;
                }
            }
            float num3 = scale * num2;
            SpriteEffects spriteEffects = SpriteEffects.None;
            Vector2 vector = rectangle.Size() / 2f;
            Color color = ContentSamples.ItemsByType[coinType].GetAlpha(itemColor).MultiplyRGBA(white);
            spriteBatch.Draw(value, screenPositionForItemCenter, new Rectangle?(rectangle), color * itemFade, 0f, vector, num3, spriteEffects, 0f);
            return num3;
        }
References Terraria.GameContent.TextureAssets.Coin, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.ID.ContentSamples.ItemsByType, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Rectangle.Width.
Referenced by Terraria.UI.ItemSlot.Draw(), and Terraria.UI.ItemSlot.DrawMoney().