Terraria Decompiled: Terraria.GameInput.PlayerInputProfile.Initialize
Initialize()
void Terraria.GameInput.PlayerInputProfile.Initialize (PresetProfiles style) inline
Definition at line 39 of file PlayerInputProfile.cs.
        {
            foreach (KeyValuePair<InputMode, KeyConfiguration> keyValuePair in this.InputModes)
            {
                keyValuePair.Value.SetupKeys();
                PlayerInput.Reset(keyValuePair.Value, style, keyValuePair.Key);
            }
        }
References Terraria.GameInput.PlayerInputProfile.InputModes, System.Collections.Generic.KeyValuePair< TKey, TValue >.Key, Terraria.GameInput.PlayerInput.Reset(), and System.Collections.Generic.KeyValuePair< TKey, TValue >.Value.
Referenced by Terraria.GameInput.PlayerInput.Initialize(), and Terraria.GameInput.PlayerInput.Load().