Terraria Decompiled: System.Reflection.RuntimePropertyInfo.GetValue
GetValue() [2/2]
override object System.Reflection.RuntimePropertyInfo.GetValue (object obj, object[] index) inline virtual
Reimplemented from System.Reflection.PropertyInfo.
Definition at line 346 of file RuntimePropertyInfo.cs.
        {
            if (index == null || index.Length == 0)
            {
                if (this.cached_getter == null)
                {
                    MethodInfo getMethod = this.GetGetMethod(true);
                    if (getMethod == null)
                    {
                        throw new ArgumentException("Get Method not found for '" + this.Name + "'");
                    }
                    if (this.DeclaringType.IsValueType || this.PropertyType.IsByRef || getMethod.ContainsGenericParameters)
                    {
                        goto IL_0097;
                    }
                    this.cached_getter = RuntimePropertyInfo.CreateGetterDelegate(getMethod);
                    try
                    {
                        return this.cached_getter(obj);
                    }
                    catch (Exception ex)
                    {
                        throw new TargetInvocationException(ex);
                    }
                }
                try
                {
                    return this.cached_getter(obj);
                }
                catch (Exception ex2)
                {
                    throw new TargetInvocationException(ex2);
                }
            }
            IL_0097:
            return this.GetValue(obj, BindingFlags.Default, null, index, null);
        }
References System.Reflection.RuntimePropertyInfo.cached_getter, System.Reflection.MethodBase.ContainsGenericParameters, System.Reflection.RuntimePropertyInfo.CreateGetterDelegate(), System.Reflection.RuntimePropertyInfo.DeclaringType, System.Reflection.PropertyInfo.GetGetMethod(), System.Reflection.RuntimePropertyInfo.GetValue(), System.index, System.Type.IsValueType, and System.Reflection.RuntimePropertyInfo.Name.
Referenced by System.Reflection.RuntimePropertyInfo.GetValue().