Terraria Decompiled: System.Reflection.RuntimePropertyInfo.CachePropertyInfo
CachePropertyInfo()
void System.Reflection.RuntimePropertyInfo.CachePropertyInfo (PInfo flags) inline private
Definition at line 111 of file RuntimePropertyInfo.cs.
        {
            if ((this.cached & flags) != flags)
            {
                RuntimePropertyInfo.get_property_info(this, ref this.info, flags);
                this.cached |= flags;
            }
        }
References System.Reflection.RuntimePropertyInfo.cached, System.Reflection.RuntimePropertyInfo.get_property_info(), and System.Reflection.RuntimePropertyInfo.info.
Referenced by System.Reflection.RuntimePropertyInfo.GetAccessors(), System.Reflection.RuntimePropertyInfo.GetGetMethod(), System.Reflection.RuntimePropertyInfo.GetIndexParameters(), and System.Reflection.RuntimePropertyInfo.GetSetMethod().