Terraria Decompiled: System.Reflection.RuntimePropertyInfo.FormatNameAndSig
FormatNameAndSig()
string System.Reflection.RuntimePropertyInfo.FormatNameAndSig (bool serialization) inline private
Definition at line 79 of file RuntimePropertyInfo.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(this.PropertyType.FormatTypeName(serialization));
            stringBuilder.Append(" ");
            stringBuilder.Append(this.Name);
            ParameterInfo[] indexParameters = this.GetIndexParameters();
            if (indexParameters.Length != 0)
            {
                stringBuilder.Append(" [");
                RuntimeParameterInfo.FormatParameters(stringBuilder, indexParameters, (CallingConventions)0, serialization);
                stringBuilder.Append("]");
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Reflection.RuntimeParameterInfo.FormatParameters(), System.Type.FormatTypeName(), System.Reflection.RuntimePropertyInfo.GetIndexParameters(), System.Reflection.RuntimePropertyInfo.Name, System.Reflection.RuntimePropertyInfo.PropertyType, and System.Text.StringBuilder.ToString().
Referenced by System.Reflection.RuntimePropertyInfo.SerializationToString(), and System.Reflection.RuntimePropertyInfo.ToString().