Terraria Decompiled: Terraria.Map.MapOverlayDrawContext.Draw
Draw() [2/3]
MapOverlayDrawContext.DrawResult Terraria.Map.MapOverlayDrawContext.Draw (Texture2D texture, Vector2 position, Color color, SpriteFrame frame, float scaleIfNotSelected, float scaleIfSelected, Alignment alignment) inline
Definition at line 214 of file MapOverlayDrawContext.cs.
        {
            if (this._opacity == 0f)
            {
                return new MapOverlayDrawContext.DrawResult(false);
            }
            position = (position - this._mapPosition) * this._mapScale + this._mapOffset;
            if (this._clippingRect != null && !this._clippingRect.Value.Contains(position.ToPoint()))
            {
                return MapOverlayDrawContext.DrawResult.Culled;
            }
            Rectangle sourceRectangle = frame.GetSourceRectangle(texture);
            Vector2 vector = sourceRectangle.Size() * alignment.OffsetMultiplier;
            Vector2 vector2 = position;
            float num = this._drawScale * scaleIfNotSelected;
            Vector2 vector3 = position - vector * num;
            Rectangle rectangle = new Rectangle((int)vector3.X, (int)vector3.Y, (int)((float)sourceRectangle.Width * num), (int)((float)sourceRectangle.Height * num));
            bool flag = rectangle.Contains(Main.MouseScreen.ToPoint());
            float num2 = num;
            if (flag)
            {
                num2 = this._drawScale * scaleIfSelected;
            }
            Main.spriteBatch.Draw(texture, vector2, new Rectangle?(sourceRectangle), color * this._opacity, 0f, vector, num2, SpriteEffects.None, 0f);
            return new MapOverlayDrawContext.DrawResult(flag);
        }
References Terraria.Map.MapOverlayDrawContext._clippingRect, Terraria.Map.MapOverlayDrawContext._mapOffset, Terraria.Map.MapOverlayDrawContext._mapPosition, Terraria.Map.MapOverlayDrawContext._mapScale, Terraria.Map.MapOverlayDrawContext._opacity, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Map.MapOverlayDrawContext.DrawResult.Culled, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.DataStructures.SpriteFrame.GetSourceRectangle(), Microsoft.Xna.Framework.Rectangle.Height, Terraria.Main.MouseScreen, Terraria.UI.Alignment.OffsetMultiplier, Terraria.Main.spriteBatch, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.