Terraria Decompiled: Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise
GetDynamicNoise() [3/3]
static float Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoise (Vector2 position, float currentTime) inline static
Definition at line 59 of file NoiseHelper.cs.
        {
            position *= 10f;
            currentTime %= 1f;
            Vector2 vector = new Vector2((float)Math.Floor((double)position.X), (float)Math.Floor((double)position.Y));
            Point point = new Point((int)vector.X, (int)vector.Y);
            Vector2 vector2 = new Vector2(position.X - vector.X, position.Y - vector.Y);
            float num = MathHelper.Lerp(NoiseHelper.GetDynamicNoiseInternal(point.X, point.Y, currentTime), NoiseHelper.GetDynamicNoiseInternal(point.X, point.Y + 1, currentTime), vector2.Y);
            float num2 = MathHelper.Lerp(NoiseHelper.GetDynamicNoiseInternal(point.X + 1, point.Y, currentTime), NoiseHelper.GetDynamicNoiseInternal(point.X + 1, point.Y + 1, currentTime), vector2.Y);
            return MathHelper.Lerp(num, num2, vector2.X);
        }
References System.Math.Floor(), Terraria.GameContent.RGB.NoiseHelper.GetDynamicNoiseInternal(), Microsoft.Xna.Framework.MathHelper.Lerp(), Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector2.Y.