Terraria Decompiled: Terraria.Cloud.resetClouds
resetClouds()
static void Terraria.Cloud.resetClouds () inline static
Definition at line 13 of file Cloud.cs.
        {
            if (Main.dedServ)
            {
                return;
            }
            Main.windSpeedCurrent = Main.windSpeedTarget;
            for (int i = 0; i < 200; i++)
            {
                Main.cloud[i].active = false;
            }
            for (int j = 0; j < Main.numClouds; j++)
            {
                Cloud.addCloud();
                Main.cloud[j].Alpha = 1f;
            }
            for (int k = 0; k < 200; k++)
            {
                Main.cloud[k].Alpha = 1f;
            }
        }
References Terraria.Cloud.active, Terraria.Cloud.addCloud(), Terraria.Cloud.Alpha, Terraria.Main.cloud, Terraria.Main.dedServ, Terraria.Main.numClouds, and Terraria.Main.windSpeedTarget.
Referenced by Terraria.Main.DrawBG(), Terraria.Netplay.InnerClientLoop(), Terraria.IO.WorldFile.LoadWorld(), and Terraria.WorldGen.RandomizeWeather().