Terraria Decompiled: Terraria.Cloud.Update
Update()
void Terraria.Cloud.Update () inline
Definition at line 344 of file Cloud.cs.
        {
            if (WorldGen.drunkWorldGenText && Main.gameMenu)
            {
                if (Main.onlyShimmerOceanWorlds)
                {
                    this.type = 29;
                }
                else if (WorldGen.dontStarveWorldGen)
                {
                    if ((double)this.scale < 0.7)
                    {
                        this.type = 40;
                    }
                    else if ((double)this.scale < 0.8)
                    {
                        this.type = 39;
                    }
                    else if ((double)this.scale < 0.9)
                    {
                        this.type = 38;
                    }
                    else
                    {
                        this.type = 37;
                    }
                }
                else if (WorldGen.getGoodWorldGen)
                {
                    if ((double)this.scale < 0.8)
                    {
                        this.type = 25;
                    }
                    else
                    {
                        this.type = 26;
                    }
                }
                else
                {
                    this.type = 28;
                }
            }
            if (this.scale == 1f)
            {
                this.scale -= 0.0001f;
            }
            if ((double)this.scale == 1.15)
            {
                this.scale -= 0.0001f;
            }
            this.position.X = this.position.X + Main.windSpeedCurrent * 9f * this.GetParallax() * (float)Main.dayRate;
            float num = 600f;
            if (Main.bgAlphaFrontLayer[4] == 1f && this.position.Y > 200f)
            {
                this.kill = true;
                this.Alpha -= 0.005f * (float)Main.dayRate;
            }
            if (!this.kill)
            {
                if (this.Alpha < 1f)
                {
                    this.Alpha += 0.001f * (float)Main.dayRate;
                    if (this.Alpha > 1f)
                    {
                        this.Alpha = 1f;
                    }
                }
            }
            else
            {
                this.Alpha -= 0.001f * (float)Main.dayRate;
                if (this.Alpha <= 0f)
                {
                    this.active = false;
                }
            }
            if (this.position.X + (float)TextureAssets.Cloud[this.type].Width() * this.scale < -num || this.position.X > (float)Main.screenWidth + num)
            {
                this.active = false;
            }
            this.rSpeed += (float)Cloud.rand.Next(-10, 11) * 2E-05f;
            if ((double)this.rSpeed > 0.0002)
            {
                this.rSpeed = 0.0002f;
            }
            if ((double)this.rSpeed < -0.0002)
            {
                this.rSpeed = -0.0002f;
            }
            if ((double)this.rotation > 0.02)
            {
                this.rotation = 0.02f;
            }
            if ((double)this.rotation < -0.02)
            {
                this.rotation = -0.02f;
            }
            this.rotation += this.rSpeed;
            this.width = (int)((float)TextureAssets.Cloud[this.type].Width() * this.scale);
            this.height = (int)((float)TextureAssets.Cloud[this.type].Height() * this.scale);
            if (this.type >= 9 && this.type <= 13 && (Main.cloudAlpha > 0f || Main.cloudBGActive >= 1f))
            {
                this.kill = true;
            }
        }
References Terraria.Cloud.Alpha, Terraria.Main.bgAlphaFrontLayer, Terraria.GameContent.TextureAssets.Cloud, Terraria.Main.cloudAlpha, Terraria.Main.cloudBGActive, Terraria.Main.dayRate, Terraria.WorldGen.dontStarveWorldGen, Terraria.WorldGen.drunkWorldGenText, System.E, Terraria.Main.gameMenu, Terraria.WorldGen.getGoodWorldGen, Terraria.Cloud.GetParallax(), int, Terraria.Cloud.kill, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.onlyShimmerOceanWorlds, Terraria.Cloud.position, Terraria.Cloud.rand, Terraria.Cloud.rSpeed, Terraria.Cloud.scale, Terraria.Main.screenWidth, Terraria.Cloud.type, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.Cloud.UpdateClouds().