Terraria Decompiled: System.Threading.ThreadLocal.SetValueSlow
SetValueSlow()
void System.Threading.ThreadLocal< T >.SetValueSlow (T value, ThreadLocal< T >::LinkedSlotVolatile[] slotArray) inline private
Definition at line 167 of file ThreadLocal.cs.
        {
            int num = ~this.m_idComplement;
            if (num < 0)
            {
                throw new ObjectDisposedException(Environment.GetResourceString("The ThreadLocal object has been disposed."));
            }
            if (slotArray == null)
            {
                slotArray = new ThreadLocal<T>.LinkedSlotVolatile[ThreadLocal<T>.GetNewTableSize(num + 1)];
                ThreadLocal<T>.ts_finalizationHelper = new ThreadLocal<T>.FinalizationHelper(slotArray, this.m_trackAllValues);
                ThreadLocal<T>.ts_slotArray = slotArray;
            }
            if (num >= slotArray.Length)
            {
                this.GrowTable(ref slotArray, num + 1);
                ThreadLocal<T>.ts_finalizationHelper.SlotArray = slotArray;
                ThreadLocal<T>.ts_slotArray = slotArray;
            }
            if (slotArray[num].Value == null)
            {
                this.CreateLinkedSlot(slotArray, num, value);
                return;
            }
            ThreadLocal<T>.LinkedSlot value2 = slotArray[num].Value;
            if (!this.m_initialized)
            {
                throw new ObjectDisposedException(Environment.GetResourceString("The ThreadLocal object has been disposed."));
            }
            value2.Value = value;
        }
References System.Threading.ThreadLocal< T >.CreateLinkedSlot(), System.Threading.ThreadLocal< T >.GetNewTableSize(), System.Environment.GetResourceString(), System.Threading.ThreadLocal< T >.GrowTable(), System.Threading.ThreadLocal< T >.m_initialized, System.Threading.ThreadLocal< T >.m_trackAllValues, System.Threading.ThreadLocal< T >.FinalizationHelper.SlotArray, System.Threading.ThreadLocal< T >.ts_finalizationHelper, System.Threading.ThreadLocal< T >.ts_slotArray, System.value, and System.Threading.ThreadLocal< T >.Value.