Terraria Decompiled: Terraria.Cloud.addCloud
addCloud()
static void Terraria.Cloud.addCloud () inline static
Definition at line 36 of file Cloud.cs.
        {
            if (Main.netMode == 2)
            {
                return;
            }
            int num = -1;
            for (int i = 0; i < 200; i++)
            {
                if (!Main.cloud[i].active)
                {
                    num = i;
                    break;
                }
            }
            if (num >= 0)
            {
                Main.cloud[num].kill = false;
                Main.cloud[num].rSpeed = 0f;
                Main.cloud[num].sSpeed = 0f;
                Main.cloud[num].scale = (float)Cloud.rand.Next(70, 131) * 0.01f;
                Main.cloud[num].rotation = (float)Cloud.rand.Next(-10, 11) * 0.01f;
                Main.cloud[num].width = (int)((float)TextureAssets.Cloud[Main.cloud[num].type].Width() * Main.cloud[num].scale);
                Main.cloud[num].height = (int)((float)TextureAssets.Cloud[Main.cloud[num].type].Height() * Main.cloud[num].scale);
                Main.cloud[num].Alpha = 0f;
                Main.cloud[num].spriteDir = SpriteEffects.None;
                if (Cloud.rand.Next(2) == 0)
                {
                    Main.cloud[num].spriteDir = SpriteEffects.FlipHorizontally;
                }
                float num2 = Main.windSpeedCurrent;
                if (!Main.gameMenu)
                {
                    num2 = Main.windSpeedCurrent - Main.player[Main.myPlayer].velocity.X * 0.1f;
                }
                int num3 = 0;
                int num4 = 0;
                if (num2 > 0f)
                {
                    num3 -= 200;
                }
                if (num2 < 0f)
                {
                    num4 += 200;
                }
                int num5 = 300;
                float num6 = (float)Cloud.rand.Next(num3 - num5, Main.screenWidth + num4 + num5);
                Main.cloud[num].Alpha = 0f;
                Main.cloud[num].position.Y = (float)Cloud.rand.Next((int)((float)(-(float)Main.screenHeight) * 0.25f), (int)((float)Main.screenHeight * 0.15f));
                if (Cloud.rand.Next(3) == 0)
                {
                    Cloud cloud = Main.cloud[num];
                    cloud.position.Y = cloud.position.Y - (float)Cloud.rand.Next((int)((float)Main.screenHeight * 0.1f));
                }
                Main.cloud[num].type = Cloud.rand.Next(4);
                if ((Main.cloudAlpha > 0f && Cloud.rand.Next(4) != 0) || (Main.cloudBGActive >= 1f && Cloud.rand.Next(2) == 0))
                {
                    Main.cloud[num].type = Cloud.rand.Next(18, 22);
                    if ((double)Main.cloud[num].scale >= 1.15)
                    {
                        Cloud cloud2 = Main.cloud[num];
                        cloud2.position.Y = cloud2.position.Y - 150f;
                    }
                    if (Main.cloud[num].scale >= 1f)
                    {
                        Cloud cloud3 = Main.cloud[num];
                        cloud3.position.Y = cloud3.position.Y - 150f;
                    }
                }
                else if (Main.cloudBGActive <= 0f && Main.cloudAlpha == 0f && Main.cloud[num].scale < 1f && Main.cloud[num].position.Y < (float)(-(float)Main.screenHeight) * 0.15f && (double)Main.numClouds <= 80.0)
                {
                    Main.cloud[num].type = Cloud.rand.Next(9, 14);
                }
                else if ((((double)Main.cloud[num].scale < 1.15 && Main.cloud[num].position.Y < (float)(-(float)Main.screenHeight) * 0.3f) || ((double)Main.cloud[num].scale < 0.85 && Main.cloud[num].position.Y < (float)Main.screenHeight * 0.15f)) && ((double)Main.numClouds > 70.0 || Main.cloudBGActive >= 1f))
                {
                    Main.cloud[num].type = Cloud.rand.Next(4, 9);
                }
                else if (Main.cloud[num].position.Y > (float)(-(float)Main.screenHeight) * 0.15f && Cloud.rand.Next(2) == 0 && (double)Main.numClouds > 20.0)
                {
                    Main.cloud[num].type = Cloud.rand.Next(14, 18);
                }
                if (Cloud.rand.Next((Main.dontStarveWorld || Main.tenthAnniversaryWorld) ? 25 : 150) == 0)
                {
                    Main.cloud[num].type = Cloud.RollRareCloud();
                }
                else if (Main.tenthAnniversaryWorld && Cloud.rand.Next(3) == 0)
                {
                    Main.cloud[num].type = Cloud.RollRareCloud();
                }
                if ((double)Main.cloud[num].scale > 1.2)
                {
                    Cloud cloud4 = Main.cloud[num];
                    cloud4.position.Y = cloud4.position.Y + 100f;
                }
                if ((double)Main.cloud[num].scale > 1.3)
                {
                    Main.cloud[num].scale = 1.3f;
                }
                if ((double)Main.cloud[num].scale < 0.7)
                {
                    Main.cloud[num].scale = 0.7f;
                }
                Main.cloud[num].active = true;
                Main.cloud[num].position.X = num6;
                if (Main.cloud[num].position.X > (float)(Main.screenWidth + 400))
                {
                    Main.cloud[num].Alpha = 1f;
                }
                if (Main.cloud[num].position.X + (float)TextureAssets.Cloud[Main.cloud[num].type].Width() * Main.cloud[num].scale < -400f)
                {
                    Main.cloud[num].Alpha = 1f;
                }
                Rectangle rectangle = new Rectangle((int)Main.cloud[num].position.X, (int)Main.cloud[num].position.Y, Main.cloud[num].width, Main.cloud[num].height);
                for (int j = 0; j < 200; j++)
                {
                    if (num != j && Main.cloud[j].active)
                    {
                        Rectangle rectangle2 = new Rectangle((int)Main.cloud[j].position.X, (int)Main.cloud[j].position.Y, Main.cloud[j].width, Main.cloud[j].height);
                        if (rectangle.Intersects(rectangle2))
{
                            Main.cloud[num].active = false;
                        }
                    }
                }
            }
        }
References Terraria.Cloud.active, Terraria.Cloud.Alpha, Terraria.GameContent.TextureAssets.Cloud, Terraria.Main.cloud, Terraria.Main.cloudAlpha, Terraria.Main.cloudBGActive, Terraria.Main.dontStarveWorld, Terraria.Main.gameMenu, Terraria.Cloud.height, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Cloud.kill, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Main.numClouds, Terraria.Main.player, Terraria.Cloud.position, Terraria.Cloud.rand, Terraria.Cloud.RollRareCloud(), Terraria.Cloud.rotation, Terraria.Cloud.rSpeed, Terraria.Cloud.scale, Terraria.Main.screenHeight, Terraria.Main.screenWidth, Terraria.Cloud.spriteDir, Terraria.Cloud.sSpeed, Terraria.Main.tenthAnniversaryWorld, Terraria.Cloud.type, Terraria.Entity.velocity, Terraria.Cloud.width, Terraria.Main.windSpeedCurrent, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Cloud.resetClouds(), and Terraria.Cloud.UpdateClouds().