Terraria Decompiled: Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters
PlaceClusters()
static void Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters (DesertDescription description, DesertHive::ClusterGroup clusters, GenerationProgress progress, float progressMin, float progressMax) inline static private
Definition at line 22 of file DesertHive.cs.
        {
            Rectangle hive = description.Hive;
            hive.Inflate(20, 20);
            DesertHive.PostPlacementEffect[,] array = new DesertHive.PostPlacementEffect[hive.Width, hive.Height];
            DesertHive.PlaceClustersArea(description, clusters, hive, array, Point.Zero, progress, progressMin, progressMax);
            for (int i = hive.Left; i < hive.Right; i++)
            {
                for (int j = hive.Top; j < hive.Bottom; j++)
                {
                    if ((array[i - hive.Left, j - hive.Top] & DesertHive.PostPlacementEffect.Smooth) != DesertHive.PostPlacementEffect.None)
                    {
                        Tile.SmoothSlope(i, j, false, false);
                    }
                }
            }
        }
References System.array, Microsoft.Xna.Framework.Rectangle.Bottom, Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Tile.SmoothSlope(), Microsoft.Xna.Framework.Rectangle.Top, Microsoft.Xna.Framework.Rectangle.Width, and Microsoft.Xna.Framework.Point.Zero.
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.Place().