Terraria Decompiled: Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea
PlaceClustersArea()
static void Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea (DesertDescription description, DesertHive::ClusterGroup clusters, Rectangle area, DesertHive::PostPlacementEffect postEffectMap[,], Point postEffectMapOffset, GenerationProgress progress, float progressMin, float progressMax) inline static private
Definition at line 41 of file DesertHive.cs.
        {
            FastRandom fastRandom = new FastRandom(Main.ActiveWorldFileData.Seed).WithModifier(57005UL);
            Vector2D vector2D;
            vector2D..ctor((double)description.Hive.Width, (double)description.Hive.Height);
            Vector2D vector2D2;
            vector2D2..ctor((double)clusters.Width, (double)clusters.Height);
            Vector2D vector2D3 = description.BlockScale / 2.0;
            for (int i = area.Left; i < area.Right; i++)
            {
                progress.Set((double)((float)(i - area.Left) / (float)(area.Right - area.Left)), (double)progressMin, (double)progressMax);
                for (int j = area.Top; j < area.Bottom; j++)
                {
                    if (WorldGen.InWorld(i, j, 1))
                    {
                        byte liquid = Main.tile[i, j].liquid;
                        double num = 0.0;
                        int num2 = -1;
                        double num3 = 0.0;
                        ushort num4 = 53;
                        if (fastRandom.Next(3) == 0)
{
                            num4 = 397;
                        }
                        int num5 = i - description.Hive.X;
                        int num6 = j - description.Hive.Y;
                        Vector2D vector2D4 = (new Vector2D((double)num5, (double)num6) - vector2D3) / vector2D * vector2D2;
                        for (int k = 0; k < clusters.Count; k++)
{
                            DesertHive.Cluster cluster = clusters[k];
                            if (Math.Abs(cluster[0].Position.X - vector2D4.X) <= 10.0 && Math.Abs(cluster[0].Position.Y - vector2D4.Y) <= 10.0)
{
                                double num7 = 0.0;
                                foreach (DesertHive.Block block in cluster)
{
                                    num7 += 1.0 / Vector2D.DistanceSquared(block.Position, vector2D4);
                                }
                                if (num7 > num)
{
                                    if (num > num3)
{
                                        num3 = num;
                                    }
                                    num = num7;
                                    num2 = k;
                                }
                                else if (num7 > num3)
{
                                    num3 = num7;
                                }
                            }
                        }
                        double num8 = num + num3;
                        Tile tile = Main.tile[i, j];
                        bool flag = ((new Vector2D((double)num5, (double)num6) - vector2D3) / vector2D * 2.0 - Vector2D.One).Length() >= 0.8;
                        DesertHive.PostPlacementEffect postPlacementEffect = DesertHive.PostPlacementEffect.None;
                        bool flag2 = true;
                        if (num8 > 3.5)
{
                            postPlacementEffect = DesertHive.PostPlacementEffect.Smooth;
                            tile.ClearEverything();
                            if (!WorldGen.remixWorldGen || (double)j <= Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2) || WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                tile.wall = 187;
                                if (num2 % 15 == 2)
{
                                    tile.ResetToType(404);
                                }
                            }
                        }
                        else if (num8 > 1.8)
{
                            if (!WorldGen.remixWorldGen || (double)j <= Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2) || WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                tile.wall = 187;
                            }
                            if (!WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                if ((double)j < Main.worldSurface)
{
                                    tile.liquid = 0;
                                }
                                else if (!WorldGen.remixWorldGen)
{
                                    tile.lava(true);
                                }
                            }
                            if (!flag || tile.active())
{
                                tile.ResetToType(396);
                                postPlacementEffect = DesertHive.PostPlacementEffect.Smooth;
                            }
                        }
                        else if (num8 > 0.7 || !flag)
{
                            if (!WorldGen.remixWorldGen || (double)j <= Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2) || WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                tile.wall = 216;
                                if (!WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                    tile.liquid = 0;
                                }
                            }
                            if (!flag || tile.active())
{
                                tile.ResetToType(num4);
                                postPlacementEffect = DesertHive.PostPlacementEffect.Smooth;
                            }
                        }
                        else if (num8 > 0.25)
{
                            FastRandom fastRandom2 = fastRandom.WithModifier(num5, num6);
                            double num9 = (num8 - 0.25) / 0.45;
                            if (fastRandom2.NextDouble() < num9)
{
                                if (!WorldGen.remixWorldGen || (double)j <= Main.rockLayer + (double)WorldGen.genRand.Next(-1, 2) || WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                    tile.wall = 187;
                                }
                                if (!WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                                    if ((double)j < Main.worldSurface)
{
                                        tile.liquid = 0;
                                    }
                                    else if (!WorldGen.remixWorldGen)
{
                                        tile.lava(true);
                                    }
                                }
                                if (tile.active())
{
                                    tile.ResetToType(num4);
                                    postPlacementEffect = DesertHive.PostPlacementEffect.Smooth;
                                }
                            }
                        }
                        else
{
                            flag2 = false;
                        }
                        if (flag2)
{
                            WorldGen.UpdateDesertHiveBounds(i, j);
                        }
                        postEffectMap[i - area.X + postEffectMapOffset.X, j - area.Y + postEffectMapOffset.Y] = postPlacementEffect;
                        if (WorldGen.remixWorldGen)
{
                            Main.tile[i, j].liquid = liquid;
                        }
                        else if (WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes)
{
                            Main.tile[i, j].liquid = liquid;
                        }
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Tile.active(), Terraria.Main.ActiveWorldFileData, Microsoft.Xna.Framework.Rectangle.Bottom, Terraria.Tile.ClearEverything(), ReLogic.Utilities.Vector2D.DistanceSquared(), Terraria.WorldGen.genRand, Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameContent.Biomes.Desert.DesertDescription.Hive, Terraria.WorldGen.InWorld(), Terraria.Tile.lava(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Tile.liquid, Terraria.Utilities.UnifiedRandom.Next(), Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextDouble(), ReLogic.Utilities.Vector2D.One, Terraria.WorldGen.remixWorldGen, Terraria.Tile.ResetToType(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Main.rockLayer, Terraria.WorldBuilding.GenerationProgress.Set(), Terraria.WorldGen.SecretSeed.Variations.surfaceIsDesertSwapDesertAndSnowBiomes, Terraria.Main.tile, Microsoft.Xna.Framework.Rectangle.Top, Terraria.WorldGen.UpdateDesertHiveBounds(), Microsoft.Xna.Framework.Rectangle.Width, Terraria.Utilities.FastRandom.WithModifier(), Terraria.Main.worldSurface, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Rectangle.X, ReLogic.Utilities.Vector2D.X, Microsoft.Xna.Framework.Point.Y, Microsoft.Xna.Framework.Rectangle.Y, and ReLogic.Utilities.Vector2D.Y.
Referenced by Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClusters().