Terraria Decompiled: Microsoft.Xna.Framework.Matrix.Decompose
Decompose()
bool Microsoft.Xna.Framework.Matrix.Decompose (out Vector3 scale, out Quaternion rotation, out Vector3 translation) inline
Definition at line 213 of file Matrix.cs.
        {
            translation.X = this.M41;
            translation.Y = this.M42;
            translation.Z = this.M43;
            float num = (float)((Math.Sign(this.M11 * this.M12 * this.M13 * this.M14) < 0) ? (-1) : 1);
            float num2 = (float)((Math.Sign(this.M21 * this.M22 * this.M23 * this.M24) < 0) ? (-1) : 1);
            float num3 = (float)((Math.Sign(this.M31 * this.M32 * this.M33 * this.M34) < 0) ? (-1) : 1);
            scale.X = num * (float)Math.Sqrt((double)(this.M11 * this.M11 + this.M12 * this.M12 + this.M13 * this.M13));
            scale.Y = num2 * (float)Math.Sqrt((double)(this.M21 * this.M21 + this.M22 * this.M22 + this.M23 * this.M23));
            scale.Z = num3 * (float)Math.Sqrt((double)(this.M31 * this.M31 + this.M32 * this.M32 + this.M33 * this.M33));
            if (MathHelper.WithinEpsilon(scale.X, 0f) || MathHelper.WithinEpsilon(scale.Y, 0f) || MathHelper.WithinEpsilon(scale.Z, 0f))
            {
                rotation = Quaternion.Identity;
                return false;
            }
            Matrix matrix = new Matrix(this.M11 / scale.X, this.M12 / scale.X, this.M13 / scale.X, 0f, this.M21 / scale.Y, this.M22 / scale.Y, this.M23 / scale.Y, 0f, this.M31 / scale.Z, this.M32 / scale.Z, this.M33 / scale.Z, 0f, 0f, 0f, 0f, 1f);
            rotation = Quaternion.CreateFromRotationMatrix(matrix);
            return true;
        }
References Microsoft.Xna.Framework.Quaternion.CreateFromRotationMatrix(), Microsoft.Xna.Framework.Quaternion.Identity, Microsoft.Xna.Framework.Matrix.M11, Microsoft.Xna.Framework.Matrix.M13, Microsoft.Xna.Framework.Matrix.M23, Microsoft.Xna.Framework.Matrix.M33, Microsoft.Xna.Framework.Matrix.M41, Microsoft.Xna.Framework.Matrix.M42, Microsoft.Xna.Framework.Matrix.M43, Microsoft.Xna.Framework.Matrix.Matrix(), System.Math.Sign(), System.Math.Sqrt(), and Microsoft.Xna.Framework.MathHelper.WithinEpsilon().