Terraria Decompiled: Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard
CreateConstrainedBillboard() [1/2]
static void Microsoft.Xna.Framework.Matrix.CreateConstrainedBillboard (ref Vector3 objectPosition, ref Vector3 cameraPosition, ref Vector3 rotateAxis, Vector3? cameraForwardVector, Vector3? objectForwardVector, out Matrix result) inline static
Definition at line 408 of file Matrix.cs.
        {
            Vector3 vector;
            vector.X = objectPosition.X - cameraPosition.X;
            vector.Y = objectPosition.Y - cameraPosition.Y;
            vector.Z = objectPosition.Z - cameraPosition.Z;
            float num = vector.LengthSquared();
            if (num < 0.0001f)
            {
                vector = ((cameraForwardVector != null) ? (-cameraForwardVector.Value) : Vector3.Forward);
            }
            else
            {
                Vector3.Multiply(ref vector, 1f / (float)Math.Sqrt((double)num), out vector);
            }
            Vector3 vector2 = rotateAxis;
            float num2;
            Vector3.Dot(ref rotateAxis, ref vector, out num2);
            Vector3 vector3;
            Vector3 vector4;
            if (Math.Abs(num2) > 0.9982547f)
            {
                if (objectForwardVector != null)
                {
                    vector3 = objectForwardVector.Value;
                    Vector3.Dot(ref rotateAxis, ref vector3, out num2);
                    if (Math.Abs(num2) > 0.9982547f)
                    {
                        num2 = rotateAxis.X * Vector3.Forward.X + rotateAxis.Y * Vector3.Forward.Y + rotateAxis.Z * Vector3.Forward.Z;
                        vector3 = ((Math.Abs(num2) > 0.9982547f) ? Vector3.Right : Vector3.Forward);
                    }
                }
                else
                {
                    num2 = rotateAxis.X * Vector3.Forward.X + rotateAxis.Y * Vector3.Forward.Y + rotateAxis.Z * Vector3.Forward.Z;
                    vector3 = ((Math.Abs(num2) > 0.9982547f) ? Vector3.Right : Vector3.Forward);
                }
                Vector3.Cross(ref rotateAxis, ref vector3, out vector4);
                vector4.Normalize();
                Vector3.Cross(ref vector4, ref rotateAxis, out vector3);
                vector3.Normalize();
            }
            else
            {
                Vector3.Cross(ref rotateAxis, ref vector, out vector4);
                vector4.Normalize();
                Vector3.Cross(ref vector4, ref vector2, out vector3);
                vector3.Normalize();
            }
            result.M11 = vector4.X;
            result.M12 = vector4.Y;
            result.M13 = vector4.Z;
            result.M14 = 0f;
            result.M21 = vector2.X;
            result.M22 = vector2.Y;
            result.M23 = vector2.Z;
            result.M24 = 0f;
            result.M31 = vector3.X;
            result.M32 = vector3.Y;
            result.M33 = vector3.Z;
            result.M34 = 0f;
            result.M41 = objectPosition.X;
            result.M42 = objectPosition.Y;
            result.M43 = objectPosition.Z;
            result.M44 = 1f;
        }
References System.Math.Abs(), Microsoft.Xna.Framework.Vector3.Cross(), Microsoft.Xna.Framework.Vector3.Dot(), Microsoft.Xna.Framework.Vector3.Forward, Microsoft.Xna.Framework.Vector3.LengthSquared(), Microsoft.Xna.Framework.Vector3.Multiply(), Microsoft.Xna.Framework.Vector3.Normalize(), Microsoft.Xna.Framework.Vector3.Right, System.Math.Sqrt(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.