Terraria Decompiled: Terraria.UI.BannerClaimingUI.DrawBannersList
DrawBannersList()
void Terraria.UI.BannerClaimingUI.DrawBannersList (SpriteBatch spriteBatch, int adjY, int middleY, Color craftingTipColor) inline
Definition at line 81 of file BannerClaimingUI.cs.
        {
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
            int num = this.UpdateAndGetClaimableItemsCount();
            BannerSystem.AnyNewClaimableBanners = false;
            if (num <= 0)
            {
                Main.TryChangePipsPage(Main.PipPage.Recipes);
                return;
            }
            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, Language.GetTextValue("GameUI.BannersTitle"), new Vector2(76f, (float)(414 + adjY)), craftingTipColor, 0f, default(Vector2), 1f, SpriteEffects.None, 0f, null, null);
            this.DrawBannersList_Move(num);
            if (Main.PipsFastScroll)
            {
                this._currentElementOffset = (float)this._focusedElementIndex;
                Main.PipsFastScroll = false;
            }
            bool flag = Main.mouseLeft || Main.mouseRight;
            if (!flag)
            {
                this._bannerStackRequestLimiter = 0;
            }
            for (int i = 0; i < num; i++)
            {
                float num2 = ((float)i - this._currentElementOffset) * 65f;
                if (Math.Abs(num2) <= (float)middleY)
                {
                    BannerClaimingUI.Entry entry = this._squashedItemTypesToShow[i];
                    Item item;
                    if (ContentSamples.ItemsByType.TryGetValue(entry.Type, out item))
                    {
                        this.inventoryScale = 100f / (Math.Abs(num2) + 100f);
                        if ((double)this.inventoryScale < 0.75)
{
                            this.inventoryScale = 0.75f;
                        }
                        double num3;
                        Color color;
                        this.GetItemSlotColors(num2, middleY, 100f, i, out num3, out color);
                        int num4 = (int)(46f - 26f * this.inventoryScale);
                        int num5 = (int)(410f + num2 * this.inventoryScale - 30f * this.inventoryScale + (float)adjY);
                        if (!Main.LocalPlayer.creativeInterface && Main.mouseX >= num4 && (float)Main.mouseX <= (float)num4 + (float)TextureAssets.InventoryBack.Width() * this.inventoryScale && Main.mouseY >= num5 && (float)Main.mouseY <= (float)num5 + (float)TextureAssets.InventoryBack.Height() * this.inventoryScale && !PlayerInput.IgnoreMouseInterface)
{
                            Main.craftingHide = true;
                            Main.LocalPlayer.mouseInterface = true;
                            if (flag)
{
                                if (this._focusedElementIndex != i)
{
                                    if ((Main.mouseLeft && Main.mouseLeftRelease) || (Main.mouseRight && Main.mouseRightRelease))
{
                                        this._focusedElementIndex = i;
                                        this._bannerStackRequestLimiter = -1;
                                    }
                                }
                                else if (num2 == 0f)
{
                                    this.TryClaimingBanner(entry);
                                }
                            }
                            ItemSlot.MouseHover(item, 35);
                        }
                        num3 -= 50.0;
                        if (num3 < 0.0)
{
                            num3 = 0.0;
                        }
                        if (i == this._focusedElementIndex)
{
                            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = 0;
                            if (PlayerInput.SettingsForUI.HighlightThingsForMouse)
{
                                ItemSlot.DrawGoldBGForCraftingMaterial = true;
                            }
                        }
                        else
{
                            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
                        }
                        Color inventoryBack = this.inventoryBack;
                        this.inventoryBack = new Color((int)((byte)num3), (int)((byte)num3), (int)((byte)num3), (int)((byte)num3));
                        int stack = item.stack;
                        item.stack = entry.Stack;
                        ItemSlot.Draw(spriteBatch, ref item, 35, new Vector2((float)num4, (float)num5), color);
                        item.stack = stack;
                        this.inventoryBack = inventoryBack;
                    }
                }
            }
        }
References Terraria.UI.BannerClaimingUI._currentElementOffset, Terraria.UI.BannerClaimingUI._focusedElementIndex, Terraria.UI.BannerClaimingUI._squashedItemTypesToShow, System.Math.Abs(), Microsoft.Xna.Framework.Graphics.Color, Terraria.Player.creativeInterface, Terraria.UI.ItemSlot.Draw(), Terraria.UI.BannerClaimingUI.DrawBannersList_Move(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.UI.BannerClaimingUI.GetItemSlotColors(), Terraria.Localization.Language.GetTextValue(), Terraria.GameInput.PlayerInput.SettingsForUI.HighlightThingsForMouse, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, int, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.UI.BannerClaimingUI.inventoryBack, Terraria.UI.BannerClaimingUI.inventoryScale, System.item, Terraria.ID.ContentSamples.ItemsByType, Terraria.Main.LocalPlayer, Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseRight, Terraria.Main.mouseRightRelease, Terraria.GameContent.FontAssets.MouseText, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Main.PipsFastScroll, System.stack, Terraria.UI.BannerClaimingUI.Entry.Stack, Terraria.Main.TryChangePipsPage(), Terraria.UI.BannerClaimingUI.TryClaimingBanner(), Terraria.UI.BannerClaimingUI.Entry.Type, Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount(), ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawInventory().