Terraria Decompiled: Terraria.UI.BannerClaimingUI.DrawBannersList_Move
DrawBannersList_Move()
void Terraria.UI.BannerClaimingUI.DrawBannersList_Move (int claimableItemsCount) inline private
Definition at line 174 of file BannerClaimingUI.cs.
        {
            this._focusedElementIndex = Utils.Clamp<int>(this._focusedElementIndex, 0, claimableItemsCount - 1);
            this._currentElementOffset = Utils.Clamp<float>(this._currentElementOffset, 0f, (float)(claimableItemsCount - 1));
            int num = (int)this._currentElementOffset;
            this._currentElementOffset = MathHelper.Lerp(this._currentElementOffset, (float)this._focusedElementIndex, 0.03f);
            this._currentElementOffset = Utils.MoveTowards(this._currentElementOffset, (float)this._focusedElementIndex, 0.1f);
            if (num != (int)this._currentElementOffset)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
        }
References Terraria.UI.BannerClaimingUI._currentElementOffset, Terraria.UI.BannerClaimingUI._focusedElementIndex, Terraria.Utils.Clamp(), int, Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.Utils.MoveTowards(), and Terraria.Audio.SoundEngine.PlaySound().
Referenced by Terraria.UI.BannerClaimingUI.DrawBannersList().