Terraria Decompiled: Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount
UpdateAndGetClaimableItemsCount()
int Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount () inline private
Definition at line 201 of file BannerClaimingUI.cs.
        {
            ushort[] claimableBannerCounts = BannerSystem.GetClaimableBannerCounts();
            BannerClaimingUI.Entry[] squashedItemTypesToShow = this._squashedItemTypesToShow;
            int num = 0;
            Array.Clear(squashedItemTypesToShow, 0, squashedItemTypesToShow.Length);
            for (int i = 1; i < claimableBannerCounts.Length; i++)
            {
                ushort num2 = claimableBannerCounts[i];
                if (num2 > 0)
                {
                    squashedItemTypesToShow[num++] = new BannerClaimingUI.Entry
                    {
                        Index = i,
                        Type = BannerSystem.BannerToItem(i),
                        Stack = (int)num2
                    };
                }
            }
            this.AnyAvailableBanners = num > 0;
            this._availableItemsCount = num;
            if (!this.AnyAvailableBanners)
            {
                BannerSystem.AnyNewClaimableBanners = false;
            }
            return num;
        }
References Terraria.UI.BannerClaimingUI._squashedItemTypesToShow, Terraria.UI.BannerClaimingUI.AnyAvailableBanners, Terraria.GameContent.BannerSystem.BannerToItem(), System.Array.Clear(), Terraria.GameContent.BannerSystem.GetClaimableBannerCounts(), and int.
Referenced by Terraria.UI.BannerClaimingUI.DrawBannersGrid(), Terraria.UI.BannerClaimingUI.DrawBannersList(), and Terraria.UI.BannerClaimingUI.DrawGridToggle().