Terraria Decompiled: Terraria.UI.BannerClaimingUI.DrawGridToggle
DrawGridToggle()
void Terraria.UI.BannerClaimingUI.DrawGridToggle (SpriteBatch spriteBatch, int adjY) inline
Definition at line 244 of file BannerClaimingUI.cs.
        {
            if (this.UpdateAndGetClaimableItemsCount() == 0)
            {
                if (Main.PipsCurrentPage == Main.PipPage.Banners)
                {
                    Main.PipsUseGrid = false;
                }
                return;
            }
            int num = 128;
            int num2 = 450 + adjY;
            if (Main.InGuideCraftMenu)
            {
                num2 -= 150;
            }
            UILinkPointNavigator.SetPosition(11002, new Vector2((float)num, (float)num2));
            bool flag = Main.mouseX > num - 15 && Main.mouseX < num + 15 && Main.mouseY > num2 - 15 && Main.mouseY < num2 + 15 && !PlayerInput.IgnoreMouseInterface;
            if (Main.PipsCurrentPage == Main.PipPage.Banners)
            {
                Utils.DrawSelectedCraftingBarIndicator(spriteBatch, num, num2);
            }
            int num3 = 2 - (Main.PipsCurrentPage == Main.PipPage.Banners && Main.PipsUseGrid).ToInt() * 2 + flag.ToInt();
            Asset<Texture2D> asset = TextureAssets.BannerToggle[num3];
            spriteBatch.Draw(asset.Value, new Vector2((float)num, (float)num2), null, Color.White, 0f, asset.Size() / 2f, 1f, SpriteEffects.None, 0f);
            if (flag)
            {
                Main.instance.MouseTextNoOverride(Language.GetTextValue("GameUI.BannersWindow"), 0, 0, -1, -1, -1, -1, 0);
                Main.player[Main.myPlayer].mouseInterface = true;
                if (Main.mouseLeft && Main.mouseLeftRelease)
                {
                    if (!Main.TryChangePipsPage(Main.PipPage.Banners))
                    {
                        Main.PipsUseGrid = !Main.PipsUseGrid;
                    }
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
            }
            Main.DoStatefulTickSound(ref Main.GridToggleMouseOverBanners, flag);
            if (BannerSystem.AnyNewClaimableBanners)
            {
                Utils.DrawNotificationIcon(spriteBatch, new Vector2((float)num, (float)(num2 - 7)), 1f, false);
            }
        }
References Terraria.GameContent.BannerSystem.AnyNewClaimableBanners, Terraria.GameContent.TextureAssets.BannerToggle, Terraria.Main.DoStatefulTickSound(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Utils.DrawNotificationIcon(), Terraria.Utils.DrawSelectedCraftingBarIndicator(), Terraria.Localization.Language.GetTextValue(), Terraria.Main.GridToggleMouseOverBanners, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.InGuideCraftMenu, Terraria.Main.instance, Terraria.Player.mouseInterface, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.MouseTextNoOverride(), Terraria.Main.myPlayer, Terraria.Main.PipsCurrentPage, Terraria.Main.PipsUseGrid, Terraria.Main.player, Terraria.Audio.SoundEngine.PlaySound(), Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), Terraria.Main.TryChangePipsPage(), Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount(), ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Microsoft.Xna.Framework.Color.White.
Referenced by Terraria.Main.DrawInventory().