Terraria Decompiled: Terraria.UI.BannerClaimingUI.DrawBannersGrid
DrawBannersGrid()
void Terraria.UI.BannerClaimingUI.DrawBannersGrid (SpriteBatch spriteBatch) inline
Definition at line 290 of file BannerClaimingUI.cs.
        {
            int num = this.UpdateAndGetClaimableItemsCount();
            BannerSystem.AnyNewClaimableBanners = false;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = -1;
            UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeSmall = -1;
            int num2 = 42;
            this.inventoryScale = 0.75f;
            int num3 = 340;
            int num4 = 310;
            int num5 = (Main.screenWidth - num4 - 280) / num2;
            int num6 = (Main.screenHeight - num3 - 20) / num2;
            UILinkPointNavigator.Shortcuts.CRAFT_IconsPerRow = num5;
            UILinkPointNavigator.Shortcuts.CRAFT_IconsPerColumn = num6;
            int num7 = 0;
            int num8 = 0;
            int num9 = num4;
            int num10 = num3;
            int mouseX = Main.mouseX;
            int mouseY = Main.mouseY;
            int num11 = num4 - 20;
            int num12 = num3 + 2;
            if (this._gridStartingElementIndex > num - num5 * num6)
            {
                this._gridStartingElementIndex = num - num5 * num6;
                if (this._gridStartingElementIndex < 0)
                {
                    this._gridStartingElementIndex = 0;
                }
            }
            if (this._gridStartingElementIndex > 0)
            {
                if (mouseX >= num11 && mouseX <= num11 + TextureAssets.CraftUpButton.Width() && mouseY >= num12 && mouseY <= num12 + TextureAssets.CraftUpButton.Height() && !PlayerInput.IgnoreMouseInterface)
                {
                    Main.LocalPlayer.mouseInterface = true;
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        this._gridStartingElementIndex -= num5;
                        if (this._gridStartingElementIndex < 0)
{
                            this._gridStartingElementIndex = 0;
                        }
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        Main.mouseLeftRelease = false;
                    }
                }
                spriteBatch.Draw(TextureAssets.CraftUpButton.Value, new Vector2((float)num11, (float)num12), null, new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            if (this._gridStartingElementIndex < num - num5 * num6)
            {
                num12 += 20;
                if (mouseX >= num11 && mouseX <= num11 + TextureAssets.CraftUpButton.Width() && mouseY >= num12 && mouseY <= num12 + TextureAssets.CraftUpButton.Height() && !PlayerInput.IgnoreMouseInterface)
                {
                    Main.LocalPlayer.mouseInterface = true;
                    if (Main.mouseLeftRelease && Main.mouseLeft)
                    {
                        this._gridStartingElementIndex += num5;
                        SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                        if (this._gridStartingElementIndex > num - num5)
{
                            this._gridStartingElementIndex = num - num5;
                        }
                        Main.mouseLeftRelease = false;
                    }
                }
                spriteBatch.Draw(TextureAssets.CraftDownButton.Value, new Vector2((float)num11, (float)num12), null, new Color(200, 200, 200, 200), 0f, default(Vector2), 1f, SpriteEffects.None, 0f);
            }
            this._gridStartingElementIndex = Utils.Clamp<int>(this._gridStartingElementIndex, 0, num - 1);
            this._gridSelectionCandidateIndex = Utils.Clamp<int>(this._gridSelectionCandidateIndex, 0, num - 1);
            int num13 = this._gridStartingElementIndex;
            while (num13 < num && num13 < num)
            {
                int num14 = num9;
                int num15 = num10;
                double num16 = (double)(this.inventoryBack.A + 50);
                double num17 = 255.0;
                BannerClaimingUI.Entry entry = this._squashedItemTypesToShow[num13];
                Item item;
                if (ContentSamples.ItemsByType.TryGetValue(entry.Type, out item))
                {
                    new Color((int)((byte)num16), (int)((byte)num16), (int)((byte)num16), (int)((byte)num16));
                    new Color((int)((byte)num17), (int)((byte)num17), (int)((byte)num17), (int)((byte)num17));
                    if (mouseX >= num14 && (float)mouseX <= (float)num14 + (float)TextureAssets.InventoryBack.Width() * this.inventoryScale && mouseY >= num15 && (float)mouseY <= (float)num15 + (float)TextureAssets.InventoryBack.Height() * this.inventoryScale && !PlayerInput.IgnoreMouseInterface)
                    {
                        Main.LocalPlayer.mouseInterface = true;
                        if (Main.mouseLeftRelease && Main.mouseLeft)
{
                            this._focusedElementIndex = num13;
                            Main.PipsFastScroll = true;
                            Main.PipsUseGrid = false;
                            SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                            Main.mouseLeftRelease = false;
                            if (PlayerInput.UsingGamepadUI)
{
                                UILinkPointNavigator.ChangePage(22);
                                Main.LockCraftingForThisCraftClickDuration();
                            }
                        }
                        Main.craftingHide = true;
                        Main.HoverItem = item.Clone();
                        Main.HoverItem.stack = entry.Stack;
                        ItemSlot.MouseHover(35);
                        Main.hoverItemName = item.Name;
                        if (item.stack > 1)
{
                            Main.hoverItemName = string.Concat(new object[]
{
                                Main.hoverItemName,
                                " (",
                                item.stack,
                                ")"
                            });
                        }
                    }
                    if (num > 0)
                    {
                        num16 -= 50.0;
                        if (num16 < 0.0)
{
                            num16 = 0.0;
                        }
                        UILinkPointNavigator.Shortcuts.CRAFT_CurrentRecipeBig = ((this._gridSelectionCandidateIndex == num13) ? 0 : (-1));
                        Color inventoryBack = this.inventoryBack;
                        this.inventoryBack = new Color((int)((byte)num16), (int)((byte)num16), (int)((byte)num16), (int)((byte)num16));
                        int stack = item.stack;
                        item.stack = entry.Stack;
                        ItemSlot.Draw(spriteBatch, ref item, 35, new Vector2((float)num14, (float)num15), default(Color));
                        item.stack = stack;
                        this.inventoryBack = inventoryBack;
                    }
                    num9 += num2;
                    num7++;
                    if (num7 >= num5)
                    {
                        num9 = num4;
                        num10 += num2;
                        num7 = 0;
                        num8++;
                        if (num8 >= num6)
{
                            break;
                        }
                    }
                }
                num13++;
            }
        }
References Terraria.UI.BannerClaimingUI._gridSelectionCandidateIndex, Terraria.UI.BannerClaimingUI._gridStartingElementIndex, Terraria.UI.BannerClaimingUI._squashedItemTypesToShow, Microsoft.Xna.Framework.Color.A, Terraria.UI.Gamepad.UILinkPointNavigator.ChangePage(), Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.TextureAssets.CraftDownButton, Terraria.GameContent.TextureAssets.CraftUpButton, Terraria.UI.ItemSlot.Draw(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.Main.hoverItemName, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.GameContent.TextureAssets.InventoryBack, Terraria.UI.BannerClaimingUI.inventoryBack, System.item, Terraria.ID.ContentSamples.ItemsByType, Terraria.Main.LockCraftingForThisCraftClickDuration(), Terraria.UI.ItemSlot.MouseHover(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.Main.mouseX, Terraria.Main.mouseY, Terraria.Audio.SoundEngine.PlaySound(), System.stack, Terraria.UI.BannerClaimingUI.Entry.Stack, Terraria.UI.BannerClaimingUI.Entry.Type, Terraria.UI.BannerClaimingUI.UpdateAndGetClaimableItemsCount(), Terraria.GameInput.PlayerInput.UsingGamepadUI, ReLogic.Content.Asset< T >.Value, and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.Main.DrawInventory().