Terraria Decompiled: Terraria.UI.BannerClaimingUI.NavigatePipsGrid
NavigatePipsGrid()
void Terraria.UI.BannerClaimingUI.NavigatePipsGrid (int xOffset, int yOffset) inline
Implements Terraria.UI.IPipsUI.
Definition at line 466 of file BannerClaimingUI.cs.
        {
            int craft_IconsPerRow = UILinkPointNavigator.Shortcuts.CRAFT_IconsPerRow;
            int num = Math.Min(UILinkPointNavigator.Shortcuts.CRAFT_IconsPerColumn, (int)Math.Ceiling((double)((float)this._availableItemsCount / (float)craft_IconsPerRow)));
            int num2 = this._gridSelectionCandidateIndex - this._gridStartingElementIndex;
            int num3 = num2 % craft_IconsPerRow;
            int num4 = num2 / craft_IconsPerRow;
            if (xOffset < 0 && num3 == 0)
            {
                xOffset = 0;
            }
            if (xOffset > 0 && num3 >= craft_IconsPerRow)
            {
                xOffset = 0;
            }
            if (yOffset < 0 && this._gridStartingElementIndex > 0 && num4 == 0)
            {
                this._gridStartingElementIndex -= craft_IconsPerRow;
            }
            if (yOffset > 0 && num4 == craft_IconsPerRow - 1)
            {
                this._gridStartingElementIndex += craft_IconsPerRow;
            }
            this._gridStartingElementIndex = Utils.Clamp<int>(this._gridStartingElementIndex, 0, Math.Max(0, this._availableItemsCount - 1 - craft_IconsPerRow * num));
            int num5 = this._gridSelectionCandidateIndex - this._gridStartingElementIndex;
            num3 = num5 % craft_IconsPerRow;
            num4 = num5 / craft_IconsPerRow;
            if (yOffset < 0 && this._gridStartingElementIndex == 0 && num4 == 0)
            {
                yOffset = 0;
            }
            if (yOffset > 0 && num4 == num - 1)
            {
                yOffset = 0;
            }
            int num6 = (this._availableItemsCount - this._gridStartingElementIndex) % craft_IconsPerRow;
            if (yOffset > 0 && num6 != 0 && num4 == num - 2 && num3 >= num6)
            {
                yOffset = 0;
            }
            int gridSelectionCandidateIndex = this._gridSelectionCandidateIndex;
            int num7 = xOffset + yOffset * craft_IconsPerRow;
            this._gridSelectionCandidateIndex = Utils.Clamp<int>(this._gridSelectionCandidateIndex + num7, 0, this._availableItemsCount - 1);
            if (gridSelectionCandidateIndex != this._gridSelectionCandidateIndex)
            {
                SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
            }
        }
References Terraria.UI.BannerClaimingUI._availableItemsCount, Terraria.UI.BannerClaimingUI._gridSelectionCandidateIndex, Terraria.UI.BannerClaimingUI._gridStartingElementIndex, System.Math.Ceiling(), Terraria.Utils.Clamp(), Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.CRAFT_IconsPerColumn, Terraria.UI.Gamepad.UILinkPointNavigator.Shortcuts.CRAFT_IconsPerRow, System.Math.Max(), System.Math.Min(), and Terraria.Audio.SoundEngine.PlaySound().