Terraria Decompiled: System.Security.CodeAccessPermission.ThrowInvalidPermission
ThrowInvalidPermission()
static void System.Security.CodeAccessPermission.ThrowInvalidPermission (IPermission target, Type expected) inline static package
Definition at line 208 of file CodeAccessPermission.cs.
        {
            throw new ArgumentException(string.Format(Locale.GetText("Invalid permission type '{0}', expected type '{1}'."), target.GetType(), expected), "target");
        }
References System.Security.Format, and Locale.GetText().
Referenced by System.Security.Permissions.EnvironmentPermission.Cast(), System.Security.Permissions.FileDialogPermission.Cast(), System.Security.Permissions.FileIOPermission.Cast(), System.Security.Permissions.GacIdentityPermission.Cast(), System.Security.Permissions.HostProtectionPermission.Cast(), System.Security.Permissions.IsolatedStorageFilePermission.Cast(), System.Security.Permissions.KeyContainerPermission.Cast(), System.Security.Permissions.PrincipalPermission.Cast(), System.Security.Permissions.PublisherIdentityPermission.Cast(), System.Security.Permissions.ReflectionPermission.Cast(), System.Security.Permissions.RegistryPermission.Cast(), System.Security.Permissions.SecurityPermission.Cast(), System.Security.Permissions.SiteIdentityPermission.Cast(), System.Security.Permissions.StrongNameIdentityPermission.Cast(), System.Security.Permissions.UIPermission.Cast(), System.Security.Permissions.UrlIdentityPermission.Cast(), and System.Security.Permissions.ZoneIdentityPermission.Cast().