Terraria Decompiled: Terraria.Social.WeGame.NetSocialModule.GetSessionState
GetSessionState()
bool Terraria.Social.WeGame.NetSocialModule.GetSessionState (RailID userId, RailNetworkSessionState state) inline protected
Definition at line 50 of file NetSocialModule.cs.
        {
            IRailNetwork railNetwork = rail_api.RailFactory().RailNetworkHelper();
            if (railNetwork.GetSessionState(userId, state) != null)
            {
                WeGameHelper.WriteDebugString("GetSessionState Failed user:{0}", new object[] { userId.id_ });
                return false;
            }
            return true;
        }
References rail.IRailNetwork.GetSessionState(), rail.rail_api.RailFactory(), rail.IRailFactory.RailNetworkHelper(), System.state, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().