Terraria Decompiled: System.Security.CodeAccessPermission.IsUnrestricted
IsUnrestricted()
static bool System.Security.CodeAccessPermission.IsUnrestricted (SecurityElement se) inline static package
Definition at line 201 of file CodeAccessPermission.cs.
        {
            string text = se.Attribute("Unrestricted");
            return text != null && string.Compare(text, bool.TrueString, true, CultureInfo.InvariantCulture) == 0;
        }
References System.Security.SecurityElement.Attribute(), System.Globalization.CultureInfo.InvariantCulture, and System.text.
Referenced by System.Security.Permissions.PermissionSetAttribute.CreateFromXml(), System.Security.Permissions.EnvironmentPermission.FromXml(), System.Security.Permissions.FileDialogPermission.FromXml(), System.Security.Permissions.FileIOPermission.FromXml(), System.Security.Permissions.IsolatedStoragePermission.FromXml(), System.Security.Permissions.ReflectionPermission.FromXml(), System.Security.Permissions.RegistryPermission.FromXml(), System.Security.Permissions.SecurityPermission.FromXml(), System.Security.Permissions.UIPermission.FromXml(), System.Security.PermissionSet.FromXml(), and System.Security.Permissions.KeyContainerPermission.FromXml().