Terraria Decompiled: Ionic.Zlib.InfTree.inflate_trees_dynamic
inflate_trees_dynamic()
int Ionic.Zlib.InfTree.inflate_trees_dynamic (int nl, int nd, int[] c, int[] bl, int[] bd, int[] tl, int[] td, int[] hp, ZlibCodec z) inline package
Definition at line 199 of file InfTree.cs.
        {
            this.initWorkArea(288);
            this.hn[0] = 0;
            int num = this.huft_build(c, 0, nl, 257, InfTree.cplens, InfTree.cplext, tl, bl, hp, this.hn, this.v);
            if (num != 0 || bl[0] == 0)
            {
                if (num == -3)
                {
                    z.Message = "oversubscribed literal/length tree";
                }
                else if (num != -4)
                {
                    z.Message = "incomplete literal/length tree";
                    num = -3;
                }
                return num;
            }
            this.initWorkArea(288);
            num = this.huft_build(c, nl, nd, 0, InfTree.cpdist, InfTree.cpdext, td, bd, hp, this.hn, this.v);
            if (num != 0 || (bd[0] == 0 && nl > 257))
            {
                if (num == -3)
                {
                    z.Message = "oversubscribed distance tree";
                }
                else if (num == -5)
                {
                    z.Message = "incomplete distance tree";
                    num = -3;
                }
                else if (num != -4)
                {
                    z.Message = "empty distance tree with lengths";
                    num = -3;
                }
                return num;
            }
            return 0;
        }
References Ionic.Zlib.InfTree.cpdext, Ionic.Zlib.InfTree.cpdist, Ionic.Zlib.InfTree.cplens, Ionic.Zlib.InfTree.cplext, Ionic.Zlib.InfTree.hn, Ionic.Zlib.InfTree.huft_build(), and Ionic.Zlib.InfTree.initWorkArea().
Referenced by Ionic.Zlib.InflateBlocks.Process().