Terraria Decompiled: Ionic.Zlib.InfTree.initWorkArea
initWorkArea()
void Ionic.Zlib.InfTree.initWorkArea (int vsize) inline private
Definition at line 251 of file InfTree.cs.
        {
            if (this.hn == null)
            {
                this.hn = new int[1];
                this.v = new int[vsize];
                this.c = new int[16];
                this.r = new int[3];
                this.u = new int[15];
                this.x = new int[16];
                return;
            }
            if (this.v.Length < vsize)
            {
                this.v = new int[vsize];
            }
            Array.Clear(this.v, 0, vsize);
            Array.Clear(this.c, 0, 16);
            this.r[0] = 0;
            this.r[1] = 0;
            this.r[2] = 0;
            Array.Clear(this.u, 0, 15);
            Array.Clear(this.x, 0, 16);
        }
References Ionic.Zlib.InfTree.c, System.Array.Clear(), Ionic.Zlib.InfTree.hn, Ionic.Zlib.InfTree.r, Ionic.Zlib.InfTree.u, Ionic.Zlib.InfTree.v, and Ionic.Zlib.InfTree.x.
Referenced by Ionic.Zlib.InfTree.inflate_trees_bits(), and Ionic.Zlib.InfTree.inflate_trees_dynamic().