Terraria Decompiled: Ionic.Zlib.InfTree.inflate_trees_bits
inflate_trees_bits()
int Ionic.Zlib.InfTree.inflate_trees_bits (int[] c, int[] bb, int[] tb, int[] hp, ZlibCodec z) inline package
Definition at line 181 of file InfTree.cs.
        {
            this.initWorkArea(19);
            this.hn[0] = 0;
            int num = this.huft_build(c, 0, 19, 19, null, null, tb, bb, hp, this.hn, this.v);
            if (num == -3)
            {
                z.Message = "oversubscribed dynamic bit lengths tree";
            }
            else if (num == -5 || bb[0] == 0)
            {
                z.Message = "incomplete dynamic bit lengths tree";
                num = -3;
            }
            return num;
        }
References Ionic.Zlib.InfTree.hn, Ionic.Zlib.InfTree.huft_build(), Ionic.Zlib.InfTree.initWorkArea(), and Ionic.Zlib.InfTree.v.
Referenced by Ionic.Zlib.InflateBlocks.Process().