Terraria Decompiled: System.Text.UTF32Encoding.GetChars
GetChars() [2/3]
unsafe override int System.Text.UTF32Encoding.GetChars (byte * bytes, int byteCount, char * chars, int charCount, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 653 of file UTF32Encoding.cs.
        {
            UTF32Encoding.UTF32Decoder utf32Decoder = (UTF32Encoding.UTF32Decoder)baseDecoder;
            char* ptr = chars;
            char* ptr2 = chars + charCount;
            byte* ptr3 = bytes;
            byte* ptr4 = bytes + byteCount;
            int num = 0;
            uint num2 = 0U;
            DecoderFallbackBuffer decoderFallbackBuffer;
            if (utf32Decoder != null)
            {
                num = utf32Decoder.readByteCount;
                num2 = (uint)utf32Decoder.iChar;
                decoderFallbackBuffer = baseDecoder.FallbackBuffer;
            }
            else
            {
                decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
            }
            decoderFallbackBuffer.InternalInitialize(bytes, chars + charCount);
            while (bytes < ptr4)
            {
                if (this._bigEndian)
                {
                    num2 <<= 8;
                    num2 += (uint)(*(bytes++));
                }
                else
                {
                    num2 >>= 8;
                    num2 += (uint)((uint)(*(bytes++)) << 24);
                }
                num++;
                if (num >= 4)
                {
                    num = 0;
                    if (num2 > 1114111U || (num2 >= 55296U && num2 <= 57343U))
                    {
                        byte[] array;
                        if (this._bigEndian)
{
                            array = new byte[]
{
                                (byte)(num2 >> 24),
                                (byte)(num2 >> 16),
                                (byte)(num2 >> 8),
                                (byte)num2
                            };
                        }
                        else
{
                            array = new byte[]
{
                                (byte)num2,
                                (byte)(num2 >> 8),
                                (byte)(num2 >> 16),
                                (byte)(num2 >> 24)
                            };
                        }
                        char* ptr5 = chars;
                        bool flag = decoderFallbackBuffer.InternalFallback(array, bytes, ref ptr5);
                        chars = ptr5;
                        if (!flag)
{
                            bytes -= 4;
                            num2 = 0U;
                            decoderFallbackBuffer.InternalReset();
                            base.ThrowCharsOverflow(utf32Decoder, chars == ptr);
                            break;
                        }
                        num2 = 0U;
                    }
                    else
                    {
                        if (num2 >= 65536U)
{
                            if (chars >= ptr2 - 1)
{
                                bytes -= 4;
                                num2 = 0U;
                                base.ThrowCharsOverflow(utf32Decoder, chars == ptr);
                                break;
                            }
                            *(chars++) = this.GetHighSurrogate(num2);
                            num2 = (uint)this.GetLowSurrogate(num2);
                        }
                        else if (chars >= ptr2)
{
                            bytes -= 4;
                            num2 = 0U;
                            base.ThrowCharsOverflow(utf32Decoder, chars == ptr);
                            break;
                        }
                        *(chars++) = (char)num2;
                        num2 = 0U;
                    }
                }
            }
            if (num > 0 && (utf32Decoder == null || utf32Decoder.MustFlush))
            {
                byte[] array2 = new byte[num];
                int i = num;
                if (this._bigEndian)
                {
                    while (i > 0)
                    {
                        array2[--i] = (byte)num2;
                        num2 >>= 8;
                    }
                }
                else
                {
                    while (i > 0)
                    {
                        array2[--i] = (byte)(num2 >> 24);
                        num2 <<= 8;
                    }
                }
                char* ptr5 = chars;
                bool flag2 = decoderFallbackBuffer.InternalFallback(array2, bytes, ref ptr5);
                chars = ptr5;
                if (!flag2)
                {
                    decoderFallbackBuffer.InternalReset();
                    base.ThrowCharsOverflow(utf32Decoder, chars == ptr);
                }
                else
                {
                    num = 0;
                    num2 = 0U;
                }
            }
            if (utf32Decoder != null)
            {
                utf32Decoder.iChar = (int)num2;
                utf32Decoder.readByteCount = num;
                utf32Decoder._bytesUsed = (int)((long)(bytes - ptr3));
            }
            return (int)((long)(chars - ptr));
        }
References System.Text.UTF32Encoding._bigEndian, System.array, System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.decoderFallback, System.Text.Decoder.FallbackBuffer, System.Text.UTF32Encoding.GetHighSurrogate(), System.Text.UTF32Encoding.GetLowSurrogate(), System.Text.UTF32Encoding.UTF32Decoder.iChar, int, System.Text.DecoderFallbackBuffer.InternalFallback(), System.Text.DecoderFallbackBuffer.InternalInitialize(), System.Text.DecoderFallbackBuffer.InternalReset(), long, System.Text.DecoderNLS.MustFlush, System.Text.UTF32Encoding.UTF32Decoder.readByteCount, and System.U.