Terraria Decompiled: System.Text.UTF32Encoding.GetBytes
GetBytes() [2/4]
unsafe override int System.Text.UTF32Encoding.GetBytes (char * chars, int charCount, byte * bytes, int byteCount, EncoderNLS encoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 412 of file UTF32Encoding.cs.
        {
            char* ptr = chars;
            char* ptr2 = chars + charCount;
            byte* ptr3 = bytes;
            byte* ptr4 = bytes + byteCount;
            char c = '\0';
            EncoderFallbackBuffer encoderFallbackBuffer;
            if (encoder != null)
            {
                c = encoder._charLeftOver;
                encoderFallbackBuffer = encoder.FallbackBuffer;
                if (encoder._throwOnOverflow && encoderFallbackBuffer.Remaining > 0)
                {
                    throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, encoder.Fallback.GetType()));
                }
            }
            else
            {
                encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
            }
            encoderFallbackBuffer.InternalInitialize(ptr, ptr2, encoder, true);
            for (;;)
            {
                char c2;
                char* ptr5;
                if ((c2 = encoderFallbackBuffer.InternalGetNextChar()) != '\0' || chars < ptr2)
                {
                    if (c2 == '\0')
                    {
                        c2 = *chars;
                        chars++;
                    }
                    if (c != '\0')
                    {
                        if (!char.IsLowSurrogate(c2))
{
                            chars--;
                            ptr5 = chars;
                            encoderFallbackBuffer.InternalFallback(c, ref ptr5);
                            chars = ptr5;
                            c = '\0';
                            continue;
                        }
                        uint surrogate = this.GetSurrogate(c, c2);
                        c = '\0';
                        if (bytes + 3 >= ptr4)
{
                            if (encoderFallbackBuffer.bFallingBack)
{
                                encoderFallbackBuffer.MovePrevious();
                                encoderFallbackBuffer.MovePrevious();
                            }
                            else
{
                                chars -= 2;
                            }
                            base.ThrowBytesOverflow(encoder, bytes == ptr3);
                            c = '\0';
                        }
                        else
{
                            if (this._bigEndian)
{
                                *(bytes++) = 0;
                                *(bytes++) = (byte)(surrogate >> 16);
                                *(bytes++) = (byte)(surrogate >> 8);
                                *(bytes++) = (byte)surrogate;
                                continue;
                            }
                            *(bytes++) = (byte)surrogate;
                            *(bytes++) = (byte)(surrogate >> 8);
                            *(bytes++) = (byte)(surrogate >> 16);
                            *(bytes++) = 0;
                            continue;
                        }
                    }
                    else
                    {
                        if (char.IsHighSurrogate(c2))
{
                            c = c2;
                            continue;
                        }
                        if (char.IsLowSurrogate(c2))
{
                            ptr5 = chars;
                            encoderFallbackBuffer.InternalFallback(c2, ref ptr5);
                            chars = ptr5;
                            continue;
                        }
                        if (bytes + 3 >= ptr4)
{
                            if (encoderFallbackBuffer.bFallingBack)
{
                                encoderFallbackBuffer.MovePrevious();
                            }
                            else
{
                                chars--;
                            }
                            base.ThrowBytesOverflow(encoder, bytes == ptr3);
                        }
                        else
{
                            if (this._bigEndian)
{
                                *(bytes++) = 0;
                                *(bytes++) = 0;
                                *(bytes++) = (byte)(c2 >> 8);
                                *(bytes++) = (byte)c2;
                                continue;
                            }
                            *(bytes++) = (byte)c2;
                            *(bytes++) = (byte)(c2 >> 8);
                            *(bytes++) = 0;
                            *(bytes++) = 0;
                            continue;
                        }
                    }
                }
                if ((encoder != null && !encoder.MustFlush) || c <= '\0')
                {
                    break;
                }
                ptr5 = chars;
                encoderFallbackBuffer.InternalFallback(c, ref ptr5);
                chars = ptr5;
                c = '\0';
            }
            if (encoder != null)
            {
                encoder._charLeftOver = c;
                encoder._charsUsed = (int)((long)(chars - ptr));
            }
            return (int)((long)(bytes - ptr3));
        }
References System.Text.UTF32Encoding._bigEndian, System.Text.EncoderNLS._charLeftOver, System.Text.EncoderNLS._throwOnOverflow, System.Text.EncoderFallbackBuffer.bFallingBack, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), System.Text.UTF32Encoding.GetSurrogate(), int, System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.EncoderFallbackBuffer.InternalInitialize(), long, System.Text.EncoderFallbackBuffer.MovePrevious(), System.Text.EncoderNLS.MustFlush, and System.Text.EncoderFallbackBuffer.Remaining.