Terraria Decompiled: System.Text.UTF32Encoding.GetByteCount
GetByteCount() [2/4]
unsafe override int System.Text.UTF32Encoding.GetByteCount (char * chars, int count, EncoderNLS encoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 330 of file UTF32Encoding.cs.
        {
            char* ptr = chars + count;
            char* ptr2 = chars;
            int num = 0;
            char c = '\0';
            EncoderFallbackBuffer encoderFallbackBuffer;
            if (encoder != null)
            {
                c = encoder._charLeftOver;
                encoderFallbackBuffer = encoder.FallbackBuffer;
                if (encoderFallbackBuffer.Remaining > 0)
                {
                    throw new ArgumentException(SR.Format("Must complete Convert() operation or call Encoder.Reset() before calling GetBytes() or GetByteCount(). Encoder '{0}' fallback '{1}'.", this.EncodingName, encoder.Fallback.GetType()));
                }
            }
            else
            {
                encoderFallbackBuffer = this.encoderFallback.CreateFallbackBuffer();
            }
            encoderFallbackBuffer.InternalInitialize(ptr2, ptr, encoder, false);
            for (;;)
            {
                char c2;
                if ((c2 = encoderFallbackBuffer.InternalGetNextChar()) == '\0' && chars >= ptr)
                {
                    if ((encoder != null && !encoder.MustFlush) || c <= '\0')
                    {
                        break;
                    }
                    char* ptr3 = chars;
                    encoderFallbackBuffer.InternalFallback(c, ref ptr3);
                    chars = ptr3;
                    c = '\0';
                }
                else
                {
                    if (c2 == '\0')
                    {
                        c2 = *chars;
                        chars++;
                    }
                    if (c != '\0')
                    {
                        if (char.IsLowSurrogate(c2))
{
                            c = '\0';
                            num += 4;
                        }
                        else
{
                            chars--;
                            char* ptr3 = chars;
                            encoderFallbackBuffer.InternalFallback(c, ref ptr3);
                            chars = ptr3;
                            c = '\0';
                        }
                    }
                    else if (char.IsHighSurrogate(c2))
                    {
                        c = c2;
                    }
                    else if (char.IsLowSurrogate(c2))
                    {
                        char* ptr3 = chars;
                        encoderFallbackBuffer.InternalFallback(c2, ref ptr3);
                        chars = ptr3;
                    }
                    else
                    {
                        num += 4;
                    }
                }
            }
            if (num < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Too many characters. The resulting number of bytes is larger than what can be returned as an int.");
            }
            return num;
        }
References System.Text.EncoderNLS._charLeftOver, System.count, System.Text.EncoderFallback.CreateFallbackBuffer(), System.Text.Encoding.encoderFallback, System.Text.Encoder.Fallback, System.Text.Encoder.FallbackBuffer, SR.Format(), System.Text.EncoderFallbackBuffer.InternalFallback(), System.Text.EncoderFallbackBuffer.InternalGetNextChar(), System.Text.EncoderFallbackBuffer.InternalInitialize(), System.Text.EncoderNLS.MustFlush, and System.Text.EncoderFallbackBuffer.Remaining.