Terraria Decompiled: System.Text.UTF32Encoding.GetCharCount
GetCharCount() [2/3]
unsafe override int System.Text.UTF32Encoding.GetCharCount (byte * bytes, int count, DecoderNLS baseDecoder) inline package virtual
Reimplemented from System.Text.Encoding.
Definition at line 551 of file UTF32Encoding.cs.
        {
            UTF32Encoding.UTF32Decoder utf32Decoder = (UTF32Encoding.UTF32Decoder)baseDecoder;
            int num = 0;
            byte* ptr = bytes + count;
            byte* ptr2 = bytes;
            int i = 0;
            uint num2 = 0U;
            DecoderFallbackBuffer decoderFallbackBuffer;
            if (utf32Decoder != null)
            {
                i = utf32Decoder.readByteCount;
                num2 = (uint)utf32Decoder.iChar;
                decoderFallbackBuffer = utf32Decoder.FallbackBuffer;
            }
            else
            {
                decoderFallbackBuffer = this.decoderFallback.CreateFallbackBuffer();
            }
            decoderFallbackBuffer.InternalInitialize(ptr2, null);
            while (bytes < ptr && num >= 0)
            {
                if (this._bigEndian)
                {
                    num2 <<= 8;
                    num2 += (uint)(*(bytes++));
                }
                else
                {
                    num2 >>= 8;
                    num2 += (uint)((uint)(*(bytes++)) << 24);
                }
                i++;
                if (i >= 4)
                {
                    i = 0;
                    if (num2 > 1114111U || (num2 >= 55296U && num2 <= 57343U))
                    {
                        byte[] array;
                        if (this._bigEndian)
{
                            array = new byte[]
{
                                (byte)(num2 >> 24),
                                (byte)(num2 >> 16),
                                (byte)(num2 >> 8),
                                (byte)num2
                            };
                        }
                        else
{
                            array = new byte[]
{
                                (byte)num2,
                                (byte)(num2 >> 8),
                                (byte)(num2 >> 16),
                                (byte)(num2 >> 24)
                            };
                        }
                        num += decoderFallbackBuffer.InternalFallback(array, bytes);
                        num2 = 0U;
                    }
                    else
                    {
                        if (num2 >= 65536U)
{
                            num++;
                        }
                        num++;
                        num2 = 0U;
                    }
                }
            }
            if (i > 0 && (utf32Decoder == null || utf32Decoder.MustFlush))
            {
                byte[] array2 = new byte[i];
                if (this._bigEndian)
                {
                    while (i > 0)
                    {
                        array2[--i] = (byte)num2;
                        num2 >>= 8;
                    }
                }
                else
                {
                    while (i > 0)
                    {
                        array2[--i] = (byte)(num2 >> 24);
                        num2 <<= 8;
                    }
                }
                num += decoderFallbackBuffer.InternalFallback(array2, bytes);
            }
            if (num < 0)
            {
                throw new ArgumentOutOfRangeException("count", "Too many characters. The resulting number of bytes is larger than what can be returned as an int.");
            }
            return num;
        }
References System.Text.UTF32Encoding._bigEndian, System.array, System.count, System.Text.DecoderFallback.CreateFallbackBuffer(), System.Text.Encoding.decoderFallback, System.Text.Decoder.FallbackBuffer, System.Text.UTF32Encoding.UTF32Decoder.iChar, System.Text.DecoderFallbackBuffer.InternalFallback(), System.Text.DecoderFallbackBuffer.InternalInitialize(), System.Text.DecoderNLS.MustFlush, System.Text.UTF32Encoding.UTF32Decoder.readByteCount, and System.U.