Terraria Decompiled: Newtonsoft.Json.Linq.Extensions.Convert< T, U >
Convert< T, U >() [2/2]
static U Newtonsoft.Json.Linq.Extensions.Convert< T, U > (this T token) inline static package
Type Constraints
T : JToken
Definition at line 161 of file Extensions.cs.
                                                              : JToken
        {
            if (token == null)
            {
                return default(U);
            }
            if (token is U && typeof(U) != typeof(IComparable) && typeof(U) != typeof(IFormattable))
            {
                return (U)((object)token);
            }
            JValue jvalue = token as JValue;
            if (jvalue == null)
            {
                throw new InvalidCastException("Cannot cast {0} to {1}.".FormatWith(CultureInfo.InvariantCulture, token.GetType(), typeof(T)));
            }
            if (jvalue.Value is U)
            {
                return (U)((object)jvalue.Value);
            }
            Type type = typeof(U);
            if (ReflectionUtils.IsNullableType(type))
            {
                if (jvalue.Value == null)
                {
                    return default(U);
                }
                type = Nullable.GetUnderlyingType(type);
            }
            return (U)((object)global::System.Convert.ChangeType(jvalue.Value, type, CultureInfo.InvariantCulture));
        }
References System.Convert.ChangeType(), System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), Newtonsoft.Json.Linq.Extensions.object, Newtonsoft.Json.Linq.Extensions.U, and Newtonsoft.Json.Linq.JValue.Value.