Terraria Decompiled: Newtonsoft.Json.Linq.Extensions.MoveNext
MoveNext() [2/2]
bool IEnumerator. Newtonsoft.Json.Linq.Extensions.MoveNext () inline private
Definition at line 682 of file Extensions.cs.
            {
                bool flag;
                try
                {
                    int num = this.<>1__state;
                    if (num != 0)
                    {
                        if (num != 1)
{
                            return false;
                        }
                        this.<>1__state = -3;
                    }
                    else
                    {
                        this.<>1__state = -1;
                        ValidationUtils.ArgumentNotNull(source, "source");
                        enumerator = source.GetEnumerator();
                        this.<>1__state = -3;
                    }
                    if (!enumerator.MoveNext())
                    {
                        this.<>m__Finally1();
                        enumerator = null;
                        flag = false;
                    }
                    else
                    {
                        T t = enumerator.Current;
                        this.<>2__current = t.Convert<JToken, U>();
                        this.<>1__state = 1;
                        flag = true;
                    }
                }
                catch
                {
                    this.System.IDisposable.Dispose();
                    throw;
                }
                return flag;
            }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.IDisposable.Dispose(), System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), Newtonsoft.Json.Linq.Extensions.m__Finally1(), Newtonsoft.Json.Linq.Extensions.source, and Newtonsoft.Json.Linq.Extensions.U.