Terraria Decompiled: rail.IRailNetworkImpl.CloseSession
CloseSession()
virtual RailResult rail.IRailNetworkImpl.CloseSession (RailID local_peer, RailID remote_peer) inline virtual
Implements rail.IRailNetwork.
Definition at line 283 of file IRailNetworkImpl.cs.
        {
            IntPtr intPtr = ((local_peer == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailID__SWIG_0());
            if (local_peer != null)
            {
                RailConverter.Csharp2Cpp(local_peer, intPtr);
            }
            IntPtr intPtr2 = ((remote_peer == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailID__SWIG_0());
            if (remote_peer != null)
            {
                RailConverter.Csharp2Cpp(remote_peer, intPtr2);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailNetwork_CloseSession(this.swigCPtr_, intPtr, intPtr2);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailID(intPtr);
                RAIL_API_PINVOKE.delete_RailID(intPtr2);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailID(), rail.RAIL_API_PINVOKE.IRailNetwork_CloseSession(), rail.RAIL_API_PINVOKE.new_RailID__SWIG_0(), and System.IntPtr.Zero.