Terraria Decompiled: System.Globalization.CalendarData.CalendarData
CalendarData() [3/3]
System.Globalization.CalendarData.CalendarData (string localeName, int calendarId, bool bUseUserOverrides) inline package
Definition at line 73 of file CalendarData.cs.
        {
            this.bUseUserOverrides = bUseUserOverrides;
            if (!CalendarData.nativeGetCalendarData(this, localeName, calendarId))
            {
                if (this.sNativeName == null)
                {
                    this.sNativeName = string.Empty;
                }
                if (this.saShortDates == null)
                {
                    this.saShortDates = CalendarData.Invariant.saShortDates;
                }
                if (this.saYearMonths == null)
                {
                    this.saYearMonths = CalendarData.Invariant.saYearMonths;
                }
                if (this.saLongDates == null)
                {
                    this.saLongDates = CalendarData.Invariant.saLongDates;
                }
                if (this.sMonthDay == null)
                {
                    this.sMonthDay = CalendarData.Invariant.sMonthDay;
                }
                if (this.saEraNames == null)
                {
                    this.saEraNames = CalendarData.Invariant.saEraNames;
                }
                if (this.saAbbrevEraNames == null)
                {
                    this.saAbbrevEraNames = CalendarData.Invariant.saAbbrevEraNames;
                }
                if (this.saAbbrevEnglishEraNames == null)
                {
                    this.saAbbrevEnglishEraNames = CalendarData.Invariant.saAbbrevEnglishEraNames;
                }
                if (this.saDayNames == null)
                {
                    this.saDayNames = CalendarData.Invariant.saDayNames;
                }
                if (this.saAbbrevDayNames == null)
                {
                    this.saAbbrevDayNames = CalendarData.Invariant.saAbbrevDayNames;
                }
                if (this.saSuperShortDayNames == null)
                {
                    this.saSuperShortDayNames = CalendarData.Invariant.saSuperShortDayNames;
                }
                if (this.saMonthNames == null)
                {
                    this.saMonthNames = CalendarData.Invariant.saMonthNames;
                }
                if (this.saAbbrevMonthNames == null)
                {
                    this.saAbbrevMonthNames = CalendarData.Invariant.saAbbrevMonthNames;
                }
            }
            this.saShortDates = CultureData.ReescapeWin32Strings(this.saShortDates);
            this.saLongDates = CultureData.ReescapeWin32Strings(this.saLongDates);
            this.saYearMonths = CultureData.ReescapeWin32Strings(this.saYearMonths);
            this.sMonthDay = CultureData.ReescapeWin32String(this.sMonthDay);
            if ((ushort)calendarId == 4)
            {
                if (CultureInfo.IsTaiwanSku)
                {
                    this.sNativeName = "中華民國曆";
                }
                else
                {
                    this.sNativeName = string.Empty;
                }
            }
            if (this.saMonthGenitiveNames == null || string.IsNullOrEmpty(this.saMonthGenitiveNames[0]))
            {
                this.saMonthGenitiveNames = this.saMonthNames;
            }
            if (this.saAbbrevMonthGenitiveNames == null || string.IsNullOrEmpty(this.saAbbrevMonthGenitiveNames[0]))
            {
                this.saAbbrevMonthGenitiveNames = this.saAbbrevMonthNames;
            }
            if (this.saLeapYearMonthNames == null || string.IsNullOrEmpty(this.saLeapYearMonthNames[0]))
            {
                this.saLeapYearMonthNames = this.saMonthNames;
            }
            this.InitializeEraNames(localeName, calendarId);
            this.InitializeAbbreviatedEraNames(localeName, calendarId);
            if (!GlobalizationMode.Invariant && calendarId == 3)
            {
                this.saAbbrevEnglishEraNames = CalendarData.GetJapaneseEnglishEraNames();
            }
            else
            {
                this.saAbbrevEnglishEraNames = new string[] { "" };
            }
            this.iCurrentEra = this.saEraNames.Length;
        }
References System.Globalization.CalendarData.bUseUserOverrides, System.Globalization.CalendarData.GetJapaneseEnglishEraNames(), System.Globalization.CalendarData.InitializeAbbreviatedEraNames(), System.Globalization.CalendarData.InitializeEraNames(), System.Globalization.CalendarData.Invariant, System.Globalization.GlobalizationMode.Invariant, System.Globalization.CultureInfo.IsTaiwanSku, System.Globalization.CalendarData.nativeGetCalendarData(), System.Globalization.CultureData.ReescapeWin32String(), System.Globalization.CultureData.ReescapeWin32Strings(), System.Globalization.CalendarData.saAbbrevDayNames, System.Globalization.CalendarData.saAbbrevEnglishEraNames, System.Globalization.CalendarData.saAbbrevEraNames, System.Globalization.CalendarData.saAbbrevMonthGenitiveNames, System.Globalization.CalendarData.saAbbrevMonthNames, System.Globalization.CalendarData.saDayNames, System.Globalization.CalendarData.saEraNames, System.Globalization.CalendarData.saLeapYearMonthNames, System.Globalization.CalendarData.saLongDates, System.Globalization.CalendarData.saMonthGenitiveNames, System.Globalization.CalendarData.saMonthNames, System.Globalization.CalendarData.saShortDates, System.Globalization.CalendarData.saSuperShortDayNames, System.Globalization.CalendarData.saYearMonths, System.Globalization.CalendarData.sMonthDay, and System.Globalization.CalendarData.sNativeName.