Terraria Decompiled: Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.GetLight
GetLight()
Color Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.GetLight () inline
Definition at line 197 of file MoonlordDeathDrama.cs.
            {
                Vector3 vector = Vector3.Zero;
                float num = 0f;
                int num2 = 5;
                Point point = this._position.ToTileCoordinates();
                for (int i = point.X - num2; i <= point.X + num2; i++)
                {
                    for (int j = point.Y - num2; j <= point.Y + num2; j++)
                    {
                        vector += Lighting.GetColor(i, j).ToVector3();
                        num += 1f;
                    }
                }
                if (num == 0f)
                {
                    return Color.White;
                }
                return new Color(vector / num);
            }
References Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece._position, Microsoft.Xna.Framework.Graphics.Color, Terraria.Lighting.GetColor(), Microsoft.Xna.Framework.Color.ToVector3(), Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Point.X, Microsoft.Xna.Framework.Point.Y, and Microsoft.Xna.Framework.Vector3.Zero.
Referenced by Terraria.GameContent.Events.MoonlordDeathDrama.MoonlordPiece.Draw().