Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_Door
TowerEntrance_Door()
void Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_Door (DungeonData data, int i, int entranceFloor, int outerSize, int innerSize, bool leftDungeonDoor, bool buried) inline
Definition at line 473 of file TowerDungeonEntrance.cs.
        {
            int num = (leftDungeonDoor ? (innerSize - 1) : (-outerSize - 2));
            int num2 = (leftDungeonDoor ? (outerSize + 2) : (-innerSize + 1));
            if (buried)
            {
                num += 2 * (leftDungeonDoor ? 0 : 1);
                num2 += 2 * (leftDungeonDoor ? (-1) : 0);
            }
            Point point = new Point(i + (leftDungeonDoor ? (outerSize - 1) : (-outerSize + 1)), entranceFloor);
            Point point2 = new Point(i + (leftDungeonDoor ? (innerSize + 1) : (-innerSize - 1)), entranceFloor);
            for (int j = num; j <= num2; j++)
            {
                for (int k = -3; k <= 1; k++)
                {
                    int num3 = j + i;
                    int num4 = k + entranceFloor;
                    Tile tile = Main.tile[num3, num4];
                    if (!buried && ((leftDungeonDoor && num3 >= point.X) || (!leftDungeonDoor && num3 <= point.X)))
                    {
                        tile.wall = 0;
                    }
                    if (k >= -2 && k <= 0)
                    {
                        tile.ClearTile();
                    }
                }
            }
            WorldGen.PlaceTile(point.X, point.Y, 10, true, true, -1, 13);
            WorldGen.PlaceTile(point2.X, point2.Y, 10, true, true, -1, 13);
        }
References Terraria.Tile.ClearTile(), Terraria.WorldGen.PlaceTile(), Terraria.Main.tile, Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().