Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_OuterPillar
TowerEntrance_OuterPillar()
void Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_OuterPillar (DungeonData data, int pillarX, int pillarY, ushort tileType) inline
Definition at line 522 of file TowerDungeonEntrance.cs.
        {
            DungeonPillarSettings dungeonPillarSettings = new DungeonPillarSettings();
            dungeonPillarSettings.Style = this.settings.StyleData;
            dungeonPillarSettings.PillarType = PillarType.Block;
            dungeonPillarSettings.Width = 7;
            dungeonPillarSettings.Height = 3;
            new DungeonPillar(dungeonPillarSettings).GenerateFeature(data, pillarX, pillarY - 1);
            dungeonPillarSettings.Width = 5;
            dungeonPillarSettings.Height = 7;
            new DungeonPillar(dungeonPillarSettings).GenerateFeature(data, pillarX, pillarY - 4);
            if (pillarY - 11 >= 10)
            {
                WorldGen.PlaceTile(pillarX, pillarY - 11, 215, true, false, -1, 0);
            }
            for (int i = 0; i < 5; i++)
            {
                WorldGen.PlaceWall(pillarX - 2 + i, pillarY - 11, 245, true);
            }
            if (pillarY - 12 >= 10)
            {
                WorldGen.PlaceWall(pillarX - 2, pillarY - 12, 245, true);
                WorldGen.PlaceWall(pillarX + 2, pillarY - 12, 245, true);
            }
            if (pillarY - 10 >= 10)
            {
                WorldGen.PlaceWall(pillarX - 2, pillarY - 10, 245, true);
                WorldGen.PlaceWall(pillarX + 2, pillarY - 10, 245, true);
            }
        }
References Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateFeature(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceWall(), Terraria.GameContent.Generation.Dungeon.Entrances.DungeonEntrance.settings, and Terraria.GameContent.Generation.Dungeon.Entrances.DungeonEntranceSettings.StyleData.
Referenced by Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().