Terraria Decompiled: Terraria.ID.ContentSamples.FillNpcRarities
FillNpcRarities()
static void Terraria.ID.ContentSamples.FillNpcRarities () inline static private
Definition at line 260 of file ContentSamples.cs.
        {
            NPCSpawnParams npcspawnParams = new NPCSpawnParams
            {
                difficultyOverride = new float?(GameDifficultyLevel.Classic)
            };
            for (int i = -65; i < (int)NPCID.Count; i++)
            {
                NPC npc = new NPC();
                npc.SetDefaults(i, npcspawnParams);
                ContentSamples.NpcBestiaryRarityStars[i] = ContentSamples.GetNPCBestiaryRarityStarsCount(npc);
            }
            ContentSamples.NpcBestiaryRarityStars[22] = 1;
            ContentSamples.NpcBestiaryRarityStars[17] = 1;
            ContentSamples.NpcBestiaryRarityStars[18] = 1;
            ContentSamples.NpcBestiaryRarityStars[38] = 1;
            ContentSamples.NpcBestiaryRarityStars[369] = 2;
            ContentSamples.NpcBestiaryRarityStars[20] = 3;
            ContentSamples.NpcBestiaryRarityStars[19] = 1;
            ContentSamples.NpcBestiaryRarityStars[227] = 2;
            ContentSamples.NpcBestiaryRarityStars[353] = 2;
            ContentSamples.NpcBestiaryRarityStars[550] = 2;
            ContentSamples.NpcBestiaryRarityStars[588] = 2;
            ContentSamples.NpcBestiaryRarityStars[107] = 3;
            ContentSamples.NpcBestiaryRarityStars[228] = 2;
            ContentSamples.NpcBestiaryRarityStars[124] = 2;
            ContentSamples.NpcBestiaryRarityStars[54] = 2;
            ContentSamples.NpcBestiaryRarityStars[108] = 3;
            ContentSamples.NpcBestiaryRarityStars[178] = 3;
            ContentSamples.NpcBestiaryRarityStars[216] = 3;
            ContentSamples.NpcBestiaryRarityStars[160] = 5;
            ContentSamples.NpcBestiaryRarityStars[441] = 5;
            ContentSamples.NpcBestiaryRarityStars[209] = 3;
            ContentSamples.NpcBestiaryRarityStars[208] = 4;
            ContentSamples.NpcBestiaryRarityStars[142] = 5;
            ContentSamples.NpcBestiaryRarityStars[368] = 3;
            ContentSamples.NpcBestiaryRarityStars[453] = 4;
            ContentSamples.NpcBestiaryRarityStars[37] = 2;
            ContentSamples.NpcBestiaryRarityStars[633] = 5;
            ContentSamples.NpcBestiaryRarityStars[663] = 5;
            ContentSamples.NpcBestiaryRarityStars[638] = 3;
            ContentSamples.NpcBestiaryRarityStars[637] = 3;
            ContentSamples.NpcBestiaryRarityStars[656] = 3;
            ContentSamples.NpcBestiaryRarityStars[670] = 3;
            ContentSamples.NpcBestiaryRarityStars[678] = 3;
            ContentSamples.NpcBestiaryRarityStars[679] = 3;
            ContentSamples.NpcBestiaryRarityStars[680] = 3;
            ContentSamples.NpcBestiaryRarityStars[681] = 3;
            ContentSamples.NpcBestiaryRarityStars[682] = 3;
            ContentSamples.NpcBestiaryRarityStars[683] = 3;
            ContentSamples.NpcBestiaryRarityStars[684] = 3;
            ContentSamples.NpcBestiaryRarityStars[664] = 5;
            ContentSamples.NpcBestiaryRarityStars[484] = 5;
            ContentSamples.NpcBestiaryRarityStars[614] = 4;
            ContentSamples.NpcBestiaryRarityStars[303] = 4;
            ContentSamples.NpcBestiaryRarityStars[337] = 4;
            ContentSamples.NpcBestiaryRarityStars[360] = 3;
            ContentSamples.NpcBestiaryRarityStars[655] = 2;
            ContentSamples.NpcBestiaryRarityStars[374] = 3;
            ContentSamples.NpcBestiaryRarityStars[661] = 3;
            ContentSamples.NpcBestiaryRarityStars[362] = 2;
            ContentSamples.NpcBestiaryRarityStars[364] = 2;
            ContentSamples.NpcBestiaryRarityStars[616] = 2;
            ContentSamples.NpcBestiaryRarityStars[298] = 2;
            ContentSamples.NpcBestiaryRarityStars[671] = 3;
            ContentSamples.NpcBestiaryRarityStars[672] = 3;
            ContentSamples.NpcBestiaryRarityStars[673] = 3;
            ContentSamples.NpcBestiaryRarityStars[674] = 3;
            ContentSamples.NpcBestiaryRarityStars[675] = 3;
            ContentSamples.NpcBestiaryRarityStars[599] = 3;
            ContentSamples.NpcBestiaryRarityStars[355] = 2;
            ContentSamples.NpcBestiaryRarityStars[358] = 3;
            ContentSamples.NpcBestiaryRarityStars[654] = 3;
            ContentSamples.NpcBestiaryRarityStars[653] = 2;
            ContentSamples.NpcBestiaryRarityStars[540] = 2;
            ContentSamples.NpcBestiaryRarityStars[604] = 3;
            ContentSamples.NpcBestiaryRarityStars[611] = 3;
            ContentSamples.NpcBestiaryRarityStars[612] = 2;
            ContentSamples.NpcBestiaryRarityStars[608] = 2;
            ContentSamples.NpcBestiaryRarityStars[607] = 2;
            ContentSamples.NpcBestiaryRarityStars[615] = 3;
            ContentSamples.NpcBestiaryRarityStars[626] = 2;
            ContentSamples.NpcBestiaryRarityStars[486] = 2;
            ContentSamples.NpcBestiaryRarityStars[487] = 3;
            ContentSamples.NpcBestiaryRarityStars[669] = 3;
            ContentSamples.NpcBestiaryRarityStars[677] = 5;
            ContentSamples.NpcBestiaryRarityStars[676] = 5;
            ContentSamples.NpcBestiaryRarityStars[149] = 2;
            ContentSamples.NpcBestiaryRarityStars[366] = 2;
            ContentSamples.NpcBestiaryRarityStars[47] = 3;
            ContentSamples.NpcBestiaryRarityStars[57] = 3;
            ContentSamples.NpcBestiaryRarityStars[168] = 3;
            ContentSamples.NpcBestiaryRarityStars[464] = 3;
            ContentSamples.NpcBestiaryRarityStars[465] = 3;
            ContentSamples.NpcBestiaryRarityStars[470] = 3;
            ContentSamples.NpcBestiaryRarityStars[691] = 4;
            ContentSamples.NpcBestiaryRarityStars[690] = 5;
            ContentSamples.NpcBestiaryRarityStars[301] = 2;
            ContentSamples.NpcBestiaryRarityStars[316] = 3;
            ContentSamples.NpcBestiaryRarityStars[546] = 2;
            ContentSamples.NpcBestiaryRarityStars[170] = 3;
            ContentSamples.NpcBestiaryRarityStars[180] = 3;
            ContentSamples.NpcBestiaryRarityStars[171] = 3;
            ContentSamples.NpcBestiaryRarityStars[29] = 2;
            ContentSamples.NpcBestiaryRarityStars[471] = 4;
            ContentSamples.NpcBestiaryRarityStars[66] = 3;
            ContentSamples.NpcBestiaryRarityStars[223] = 2;
            ContentSamples.NpcBestiaryRarityStars[161] = 2;
            ContentSamples.NpcBestiaryRarityStars[491] = 4;
            ContentSamples.NpcBestiaryRarityStars[-9] = 3;
            ContentSamples.NpcBestiaryRarityStars[594] = 2;
            ContentSamples.NpcBestiaryRarityStars[628] = 2;
            ContentSamples.NpcBestiaryRarityStars[225] = 2;
            ContentSamples.NpcBestiaryRarityStars[224] = 2;
            ContentSamples.NpcBestiaryRarityStars[250] = 3;
            ContentSamples.NpcBestiaryRarityStars[16] = 2;
            ContentSamples.NpcBestiaryRarityStars[481] = 2;
            ContentSamples.NpcBestiaryRarityStars[483] = 2;
            ContentSamples.NpcBestiaryRarityStars[184] = 2;
            ContentSamples.NpcBestiaryRarityStars[185] = 3;
            ContentSamples.NpcBestiaryRarityStars[206] = 3;
            ContentSamples.NpcBestiaryRarityStars[541] = 4;
            ContentSamples.NpcBestiaryRarityStars[537] = 2;
            ContentSamples.NpcBestiaryRarityStars[205] = 4;
            ContentSamples.NpcBestiaryRarityStars[499] = 2;
            ContentSamples.NpcBestiaryRarityStars[494] = 2;
            ContentSamples.NpcBestiaryRarityStars[496] = 2;
            ContentSamples.NpcBestiaryRarityStars[302] = 3;
            ContentSamples.NpcBestiaryRarityStars[317] = 3;
            ContentSamples.NpcBestiaryRarityStars[318] = 3;
            ContentSamples.NpcBestiaryRarityStars[319] = 3;
            ContentSamples.NpcBestiaryRarityStars[320] = 3;
            ContentSamples.NpcBestiaryRarityStars[321] = 3;
            ContentSamples.NpcBestiaryRarityStars[331] = 3;
            ContentSamples.NpcBestiaryRarityStars[332] = 3;
            ContentSamples.NpcBestiaryRarityStars[322] = 3;
            ContentSamples.NpcBestiaryRarityStars[323] = 3;
            ContentSamples.NpcBestiaryRarityStars[324] = 3;
            ContentSamples.NpcBestiaryRarityStars[335] = 3;
            ContentSamples.NpcBestiaryRarityStars[336] = 3;
            ContentSamples.NpcBestiaryRarityStars[333] = 3;
            ContentSamples.NpcBestiaryRarityStars[334] = 3;
            ContentSamples.NpcBestiaryRarityStars[4] = 2;
            ContentSamples.NpcBestiaryRarityStars[50] = 2;
            ContentSamples.NpcBestiaryRarityStars[35] = 3;
            ContentSamples.NpcBestiaryRarityStars[13] = 3;
            ContentSamples.NpcBestiaryRarityStars[134] = 4;
            ContentSamples.NpcBestiaryRarityStars[262] = 4;
            ContentSamples.NpcBestiaryRarityStars[668] = 3;
        }
References Terraria.DataStructures.GameDifficultyLevel.Classic, Terraria.ID.NPCID.Count, Terraria.ID.ContentSamples.GetNPCBestiaryRarityStarsCount(), int, Terraria.ID.ContentSamples.NpcBestiaryRarityStars, and Terraria.NPC.SetDefaults().
Referenced by Terraria.ID.ContentSamples.Initialize().