Terraria Decompiled: Terraria.ID.ContentSamples.Initialize
Initialize()
static void Terraria.ID.ContentSamples.Initialize () inline static
Definition at line 15 of file ContentSamples.cs.
        {
            ContentSamples.NpcsByNetId.Clear();
            ContentSamples.NpcNetIdsByPersistentIds.Clear();
            ContentSamples.NpcPersistentIdsByNetIds.Clear();
            ContentSamples.NpcBestiarySortingId.Clear();
            for (int i = -65; i < (int)NPCID.Count; i++)
            {
                NPC npc = new NPC();
                npc.SetDefaults(i, default(NPCSpawnParams));
                ContentSamples.NpcsByNetId[i] = npc;
                string name = NPCID.Search.GetName(npc.netID);
                ContentSamples.NpcPersistentIdsByNetIds[i] = name;
                ContentSamples.NpcBestiaryCreditIdsByNpcNetIds[i] = name;
                ContentSamples.NpcNetIdsByPersistentIds[name] = i;
            }
            ContentSamples.ModifyNPCIds();
            ContentSamples.ProjectilesByType.Clear();
            for (int j = 0; j < (int)ProjectileID.Count; j++)
            {
                Projectile projectile = new Projectile();
                projectile.SetDefaults(j);
                ContentSamples.ProjectilesByType[j] = projectile;
            }
            ContentSamples.ItemsByType.Clear();
            for (int k = 0; k < (int)ItemID.Count; k++)
            {
                Item item = new Item();
                item.SetDefaults(k, null);
                ContentSamples.ItemsByType[k] = item;
                string name2 = ItemID.Search.GetName(item.type);
                ContentSamples.ItemPersistentIdsByNetIds[k] = name2;
                ContentSamples.ItemNetIdsByPersistentIds[name2] = k;
            }
            foreach (int num in ItemID.Sets.ItemsThatAreProcessedAfterNormalContentSample)
            {
                Item item2 = new Item();
                item2.SetDefaults(num, null);
                ContentSamples.ItemsByType[num] = item2;
                string name3 = ItemID.Search.GetName(item2.type);
                ContentSamples.ItemPersistentIdsByNetIds[num] = name3;
                ContentSamples.ItemNetIdsByPersistentIds[name3] = num;
            }
            ContentSamples.FillResearchItemOverrides();
            ContentSamples.FillNpcRarities();
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Terraria.ID.ItemID.Count, Terraria.ID.NPCID.Count, Terraria.ID.ProjectileID.Count, Terraria.ID.ContentSamples.FillNpcRarities(), Terraria.ID.ContentSamples.FillResearchItemOverrides(), int, System.item, Terraria.ID.ContentSamples.ItemNetIdsByPersistentIds, Terraria.ID.ContentSamples.ItemPersistentIdsByNetIds, Terraria.ID.ContentSamples.ItemsByType, Terraria.ID.ItemID.Sets.ItemsThatAreProcessedAfterNormalContentSample, Terraria.ID.ContentSamples.ModifyNPCIds(), System.name, Terraria.NPC.netID, Terraria.ID.ContentSamples.NpcBestiaryCreditIdsByNpcNetIds, Terraria.ID.ContentSamples.NpcBestiarySortingId, Terraria.ID.ContentSamples.NpcNetIdsByPersistentIds, Terraria.ID.ContentSamples.NpcPersistentIdsByNetIds, Terraria.ID.ContentSamples.NpcsByNetId, Terraria.ID.ContentSamples.ProjectilesByType, Terraria.ID.ItemID.Search, Terraria.ID.NPCID.Search, Terraria.Projectile.SetDefaults(), Terraria.Item.SetDefaults(), Terraria.NPC.SetDefaults(), and Terraria.Item.type.
Referenced by Terraria.Main.Initialize().