Terraria Decompiled: Terraria.WorldBuilding.WorldManifest.Clone
Clone()
WorldManifest Terraria.WorldBuilding.WorldManifest.Clone () inline
Definition at line 84 of file WorldManifest.cs.
        {
            return JsonConvert.DeserializeObject<WorldManifest>(JsonConvert.SerializeObject(this, WorldManifest.SerializerSettings), WorldManifest.SerializerSettings);
        }
References Newtonsoft.Json.JsonConvert.DeserializeObject(), Newtonsoft.Json.JsonConvert.SerializeObject(), and Terraria.WorldBuilding.WorldManifest.SerializerSettings.
Referenced by Terraria.WorldBuilding.WorldGenSnapshot.Restore().