Terraria Decompiled: Terraria.WorldBuilding.WorldManifest.Deserialize
Deserialize()
static WorldManifest Terraria.WorldBuilding.WorldManifest.Deserialize (string json) inline static
Definition at line 61 of file WorldManifest.cs.
        {
            try
            {
                if (!string.IsNullOrEmpty(json))
                {
                    return JsonConvert.DeserializeObject<WorldManifest>(json, WorldManifest.SerializerSettings);
                }
            }
            catch (Exception ex)
            {
                Trace.WriteLine(ex);
            }
            return new WorldManifest();
        }
References Newtonsoft.Json.JsonConvert.DeserializeObject(), Terraria.WorldBuilding.WorldManifest.SerializerSettings, System.Trace, and Terraria.WorldBuilding.WorldManifest.WorldManifest().
Referenced by Terraria.IO.WorldFile.LoadHeader(), and Terraria.WorldBuilding.WorldGenSnapshot.ReadSnapshot().