Terraria Decompiled: Terraria.GameContent.Events.Sandstorm.ShowSandstormVisuals
ShowSandstormVisuals()
static bool Terraria.GameContent.Events.Sandstorm.ShowSandstormVisuals () inline static
Definition at line 136 of file Sandstorm.cs.
        {
            return Sandstorm.Happening && Main.SceneMetrics.ZoneSandstorm && SurfaceBackgroundID.Sets.IsDesertVariant[Main.bgStyle] && Main.bgDelay < 50;
        }
References Terraria.Main.bgStyle, and Terraria.ID.SurfaceBackgroundID.Sets.IsDesertVariant.
Referenced by Terraria.SceneState.ApplyVisuals(), Terraria.GameContent.Events.Sandstorm.EmitDust(), Terraria.Dust.UpdateDust(), and Terraria.GameContent.UI.UIDust.UpdateDust().