Terraria Decompiled: System.IO.StreamReader.ReadSpan
ReadSpan()
int System.IO.StreamReader.ReadSpan (Span< char > buffer) inline private
Definition at line 310 of file StreamReader.cs.
        {
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            int num = 0;
            bool flag = false;
            int i = buffer.Length;
            while (i > 0)
            {
                int num2 = this._charLen - this._charPos;
                if (num2 == 0)
                {
                    num2 = this.ReadBuffer(buffer.Slice(num), out flag);
                }
                if (num2 == 0)
                {
                    break;
                }
                if (num2 > i)
                {
                    num2 = i;
                }
                if (!flag)
                {
                    new Span<char>(this._charBuffer, this._charPos, num2).CopyTo(buffer.Slice(num));
                    this._charPos += num2;
                }
                num += num2;
                i -= num2;
                if (this._isBlocked)
                {
                    break;
                }
            }
            return num;
        }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charPos, System.IO.StreamReader._isBlocked, System.IO.StreamReader._stream, System.IO.StreamReader.CheckAsyncTaskInProgress(), System.Span< T >.CopyTo(), System.Span< T >.Length, System.IO.StreamReader.ReadBuffer(), and System.Span< T >.Slice().
Referenced by System.IO.StreamReader.Read(), System.IO.StreamReader.Read(), and System.IO.StreamReader.ReadBlock().