Terraria Decompiled: System.IO.StreamReader.ReadBlockAsync
ReadBlockAsync() [2/2]
override ValueTask< int > System.IO.StreamReader.ReadBlockAsync (Memory< char > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.TextReader.
Definition at line 1058 of file StreamReader.cs.
        {
            if (base.GetType() != typeof(StreamReader))
            {
                return base.ReadBlockAsync(buffer, cancellationToken);
            }
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            if (cancellationToken.IsCancellationRequested)
            {
                return new ValueTask<int>(Task.FromCanceled<int>(cancellationToken));
            }
            ValueTask<int> valueTask = base.ReadBlockAsyncInternal(buffer, cancellationToken);
            if (valueTask.IsCompletedSuccessfully)
            {
                return valueTask;
            }
            Task<int> task = valueTask.AsTask();
            this._asyncReadTask = task;
            return new ValueTask<int>(task);
        }
References System.IO.StreamReader._stream, System.Threading.Tasks.ValueTask< TResult >.AsTask(), System.IO.StreamReader.CheckAsyncTaskInProgress(), System.Threading.Tasks.Task< TResult >.FromCanceled(), System.Threading.Tasks.ValueTask< TResult >.IsCompletedSuccessfully, and System.task.