Terraria Decompiled: System.IO.StreamReader.ReadBuffer
ReadBuffer() [2/2]
int System.IO.StreamReader.ReadBuffer (Span< char > userBuffer, out bool readToUserBuffer) inline private
Definition at line 561 of file StreamReader.cs.
        {
            this._charLen = 0;
            this._charPos = 0;
            if (!this._checkPreamble)
            {
                this._byteLen = 0;
            }
            int num = 0;
            readToUserBuffer = userBuffer.Length >= this._maxCharsPerBuffer;
            for (;;)
            {
                if (this._checkPreamble)
                {
                    int num2 = this._stream.Read(this._byteBuffer, this._bytePos, this._byteBuffer.Length - this._bytePos);
                    if (num2 == 0)
                    {
                        break;
                    }
                    this._byteLen += num2;
                }
                else
                {
                    this._byteLen = this._stream.Read(this._byteBuffer, 0, this._byteBuffer.Length);
                    if (this._byteLen == 0)
                    {
                        goto IL_01CD;
                    }
                }
                this._isBlocked = this._byteLen < this._byteBuffer.Length;
                if (!this.IsPreamble())
                {
                    if (this._detectEncoding && this._byteLen >= 2)
                    {
                        this.DetectEncoding();
                        readToUserBuffer = userBuffer.Length >= this._maxCharsPerBuffer;
                    }
                    this._charPos = 0;
                    if (readToUserBuffer)
                    {
                        num += this._decoder.GetChars(new ReadOnlySpan<byte>(this._byteBuffer, 0, this._byteLen), userBuffer.Slice(num), false);
                        this._charLen = 0;
                    }
                    else
                    {
                        num = this._decoder.GetChars(this._byteBuffer, 0, this._byteLen, this._charBuffer, num);
                        this._charLen += num;
                    }
                }
                if (num != 0)
                {
                    goto IL_01CD;
                }
            }
            if (this._byteLen > 0)
            {
                if (readToUserBuffer)
                {
                    num = this._decoder.GetChars(new ReadOnlySpan<byte>(this._byteBuffer, 0, this._byteLen), userBuffer.Slice(num), false);
                    this._charLen = 0;
                }
                else
                {
                    num = this._decoder.GetChars(this._byteBuffer, 0, this._byteLen, this._charBuffer, num);
                    this._charLen += num;
                }
            }
            return num;
            IL_01CD:
            this._isBlocked &= num < userBuffer.Length;
            return num;
        }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._maxCharsPerBuffer, System.IO.StreamReader._stream, System.IO.StreamReader.DetectEncoding(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), System.Span< T >.Length, System.IO.Stream.Read(), and System.Span< T >.Slice().