Terraria Decompiled: System.IO.StreamReader.IsPreamble
IsPreamble()
unsafe bool System.IO.StreamReader.IsPreamble () inline private
Definition at line 476 of file StreamReader.cs.
        {
            if (!this._checkPreamble)
            {
                return this._checkPreamble;
            }
            ReadOnlySpan<byte> preamble = this._encoding.Preamble;
            int num = ((this._byteLen >= preamble.Length) ? (preamble.Length - this._bytePos) : (this._byteLen - this._bytePos));
            int i = 0;
            while (i < num)
            {
                if (this._byteBuffer[this._bytePos] != *preamble[this._bytePos])
                {
                    this._bytePos = 0;
                    this._checkPreamble = false;
                    break;
                }
                i++;
                this._bytePos++;
            }
            if (this._checkPreamble && this._bytePos == preamble.Length)
            {
                this.CompressBuffer(preamble.Length);
                this._bytePos = 0;
                this._checkPreamble = false;
                this._detectEncoding = false;
            }
            return this._checkPreamble;
        }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._bytePos, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._encoding, System.IO.StreamReader.CompressBuffer(), System.ReadOnlySpan< T >.Length, and System.Text.Encoding.Preamble.
Referenced by System.IO.StreamReader.d__66.MoveNext(), System.IO.StreamReader.d__69.MoveNext(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadBuffer(), System.IO.StreamReader.ReadBuffer(), and System.IO.StreamReader.ReadBufferAsync().