Terraria Decompiled: System.IO.StreamReader.ReadAsync
ReadAsync() [1/2]
override Task< int > System.IO.StreamReader.ReadAsync (char[] buffer, int index, int count) inline virtual
Reimplemented from System.IO.TextReader.
Definition at line 851 of file StreamReader.cs.
        {
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer", "Buffer cannot be null.");
            }
            if (index < 0 || count < 0)
            {
                throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", "Non-negative number required.");
            }
            if (buffer.Length - index < count)
            {
                throw new ArgumentException("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection.");
            }
            if (base.GetType() != typeof(StreamReader))
            {
                return base.ReadAsync(buffer, index, count);
            }
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            Task<int> task = this.ReadAsyncInternal(new Memory<char>(buffer, index, count), default(CancellationToken)).AsTask();
            this._asyncReadTask = task;
            return task;
        }
References System.IO.StreamReader._stream, System.IO.StreamReader.CheckAsyncTaskInProgress(), System.count, System.index, System.IO.StreamReader.ReadAsyncInternal(), and System.task.
Referenced by System.IO.File.InternalReadAllTextAsync().