Terraria Decompiled: System.IO.StreamReader.Read
Read() [1/3]
override int System.IO.StreamReader.Read () inline virtual
Reimplemented from System.IO.TextReader.
Reimplemented in System.IO.UnexceptionalStreamReader.
Definition at line 265 of file StreamReader.cs.
        {
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            if (this._charPos == this._charLen && this.ReadBuffer() == 0)
            {
                return -1;
            }
            int num = (int)this._charBuffer[this._charPos];
            this._charPos++;
            return num;
        }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._stream, System.IO.StreamReader.CheckAsyncTaskInProgress(), int, and System.IO.StreamReader.ReadBuffer().
Referenced by System.TermInfoDriver.GetCursorPosition(), System.Security.Util.Tokenizer.StreamTokenReader.Read(), and System.TermInfoDriver.ReadKeyInternal().