Terraria Decompiled: System.IO.StreamReader.ReadLineAsyncInternal
ReadLineAsyncInternal()
async Task< string > System.IO.StreamReader.ReadLineAsyncInternal () inline private
Definition at line 712 of file StreamReader.cs.
        {
            bool flag = this._charPos == this._charLen;
            ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter2;
            if (flag)
            {
                ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter = this.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                if (!configuredTaskAwaiter.IsCompleted)
                {
                    await configuredTaskAwaiter;
                    configuredTaskAwaiter = configuredTaskAwaiter2;
                    configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                }
                flag = configuredTaskAwaiter.GetResult() == 0;
            }
            string text;
            if (flag)
            {
                text = null;
            }
            else
            {
                StringBuilder sb = null;
                char[] charBuffer;
                int charLen;
                int num2;
                int num;
                char c;
                for (;;)
                {
                    charBuffer = this._charBuffer;
                    charLen = this._charLen;
                    num = (num2 = this._charPos);
                    do
                    {
                        c = charBuffer[num2];
                        if (c == '\r' || c == '\n')
{
                            goto IL_00E1;
                        }
                        num2++;
                    }
                    while (num2 < charLen);
                    num2 = charLen - num;
                    if (sb == null)
                    {
                        sb = new StringBuilder(num2 + 80);
                    }
                    sb.Append(charBuffer, num, num2);
                    ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter = this.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter.IsCompleted)
                    {
                        await configuredTaskAwaiter;
                        configuredTaskAwaiter = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                    }
                    if (configuredTaskAwaiter.GetResult() <= 0)
                    {
                        goto Block_14;
                    }
                }
                IL_00E1:
                string s;
                if (sb != null)
                {
                    sb.Append(charBuffer, num, num2 - num);
                    s = sb.ToString();
                }
                else
                {
                    s = new string(charBuffer, num, num2 - num);
                }
                int num3 = num2 + 1;
                this._charPos = num3;
                flag = c == '\r';
                if (flag)
                {
                    bool flag2 = num3 < charLen;
                    if (!flag2)
                    {
                        ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter = this.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter.IsCompleted)
{
                            await configuredTaskAwaiter;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                        }
                        flag2 = configuredTaskAwaiter.GetResult() > 0;
                    }
                    flag = flag2;
                }
                if (flag)
                {
                    num = this._charPos;
                    if (this._charBuffer[num] == '\n')
                    {
                        this._charPos = num + 1;
                    }
                }
                return s;
                Block_14:
                text = sb.ToString();
            }
            return text;
        }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.Text.StringBuilder.Append(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.IO.StreamReader.ReadBufferAsync(), System.s, System.text, and System.Text.StringBuilder.ToString().
Referenced by System.IO.StreamReader.d__61.MoveNext(), and System.IO.StreamReader.ReadLineAsync().