Terraria Decompiled: System.IO.StreamReader.ReadAsync
ReadAsync() [2/2]
override ValueTask< int > System.IO.StreamReader.ReadAsync (Memory< char > buffer, CancellationToken cancellationToken = default(CancellationToken)) inline virtual
Reimplemented from System.IO.TextReader.
Definition at line 880 of file StreamReader.cs.
        {
            if (base.GetType() != typeof(StreamReader))
            {
                return base.ReadAsync(buffer, cancellationToken);
            }
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            if (cancellationToken.IsCancellationRequested)
            {
                return new ValueTask<int>(Task.FromCanceled<int>(cancellationToken));
            }
            return this.ReadAsyncInternal(buffer, cancellationToken);
        }
References System.IO.StreamReader._stream, System.IO.StreamReader.CheckAsyncTaskInProgress(), System.Threading.Tasks.Task< TResult >.FromCanceled(), and System.IO.StreamReader.ReadAsyncInternal().