Terraria Decompiled: System.IO.StreamReader.ReadToEnd
ReadToEnd()
override string System.IO.StreamReader.ReadToEnd () inline virtual
Reimplemented from System.IO.TextReader.
Reimplemented in System.IO.UnexceptionalStreamReader.
Definition at line 351 of file StreamReader.cs.
        {
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            StringBuilder stringBuilder = new StringBuilder(this._charLen - this._charPos);
            do
            {
                stringBuilder.Append(this._charBuffer, this._charPos, this._charLen - this._charPos);
                this._charPos = this._charLen;
                this.ReadBuffer();
            }
            while (this._charLen > 0);
            return stringBuilder.ToString();
        }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._stream, System.Text.StringBuilder.Append(), System.IO.StreamReader.CheckAsyncTaskInProgress(), System.IO.StreamReader.ReadBuffer(), and System.Text.StringBuilder.ToString().
Referenced by ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection._sendMsg(), System.Security.Permissions.PermissionSetAttribute.CreatePermissionSet(), Terraria.GameContent.Metadata.TileMaterials.DeserializeEmbeddedResource< T >(), Terraria.WorldBuilding.WorldGenConfiguration.FromEmbeddedPath(), System.IO.File.InternalReadAllText(), Microsoft.Win32.KeyHandler.Load(), Mono.Security.Cryptography.KeyPairPersistence.Load(), Mono.Security.StrongNameManager.LoadConfig(), Terraria.Localization.LanguageManager.LoadFromContentSources(), System.Security.Policy.PolicyLevel.LoadFromFile(), Terraria.IO.ResourcePack.LoadManifest(), Terraria.Utils.ReadEmbeddedResource(), ReLogic.Peripherals.RGB.SteelSeries.GameSenseConnection.SendJson(), Terraria.Social.WeGame.WeGameHelper.Serialize< T >(), and Ionic.Zlib.ZlibBaseStream.UncompressString().