Terraria Decompiled: System.IO.StreamReader.DetectEncoding
DetectEncoding()
void System.IO.StreamReader.DetectEncoding () inline private
Definition at line 418 of file StreamReader.cs.
        {
            if (this._byteLen < 2)
            {
                return;
            }
            this._detectEncoding = false;
            bool flag = false;
            if (this._byteBuffer[0] == 254 && this._byteBuffer[1] == 255)
            {
                this._encoding = Encoding.BigEndianUnicode;
                this.CompressBuffer(2);
                flag = true;
            }
            else if (this._byteBuffer[0] == 255 && this._byteBuffer[1] == 254)
            {
                if (this._byteLen < 4 || this._byteBuffer[2] != 0 || this._byteBuffer[3] != 0)
                {
                    this._encoding = Encoding.Unicode;
                    this.CompressBuffer(2);
                    flag = true;
                }
                else
                {
                    this._encoding = Encoding.UTF32;
                    this.CompressBuffer(4);
                    flag = true;
                }
            }
            else if (this._byteLen >= 3 && this._byteBuffer[0] == 239 && this._byteBuffer[1] == 187 && this._byteBuffer[2] == 191)
            {
                this._encoding = Encoding.UTF8;
                this.CompressBuffer(3);
                flag = true;
            }
            else if (this._byteLen >= 4 && this._byteBuffer[0] == 0 && this._byteBuffer[1] == 0 && this._byteBuffer[2] == 254 && this._byteBuffer[3] == 255)
            {
                this._encoding = new UTF32Encoding(true, true);
                this.CompressBuffer(4);
                flag = true;
            }
            else if (this._byteLen == 2)
            {
                this._detectEncoding = true;
            }
            if (flag)
            {
                this._decoder = this._encoding.GetDecoder();
                int maxCharCount = this._encoding.GetMaxCharCount(this._byteBuffer.Length);
                if (maxCharCount > this._maxCharsPerBuffer)
                {
                    this._charBuffer = new char[maxCharCount];
                }
                this._maxCharsPerBuffer = maxCharCount;
            }
        }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._encoding, System.IO.StreamReader._maxCharsPerBuffer, System.Text.Encoding.BigEndianUnicode, System.IO.StreamReader.CompressBuffer(), System.Text.Encoding.GetDecoder(), System.Text.Encoding.GetMaxCharCount(), System.Text.Encoding.Unicode, System.Text.Encoding.UTF32, and System.Text.Encoding.UTF8.
Referenced by System.IO.StreamReader.d__66.MoveNext(), System.IO.StreamReader.d__69.MoveNext(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadBuffer(), System.IO.StreamReader.ReadBuffer(), and System.IO.StreamReader.ReadBufferAsync().