Terraria Decompiled: System.IO.StreamReader.ReadAsyncInternal
ReadAsyncInternal()
override async ValueTask< int > System.IO.StreamReader.ReadAsyncInternal (Memory< char > buffer, CancellationToken cancellationToken) inline package virtual
Reimplemented from System.IO.TextReader.
Definition at line 899 of file StreamReader.cs.
        {
            bool flag = this._charPos == this._charLen;
            if (flag)
            {
                ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter = this.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                if (!configuredTaskAwaiter.IsCompleted)
                {
                    await configuredTaskAwaiter;
                    ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                    configuredTaskAwaiter = configuredTaskAwaiter2;
                    configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                }
                flag = configuredTaskAwaiter.GetResult() == 0;
            }
            int num;
            if (flag)
            {
                num = 0;
            }
            else
            {
                int charsRead = 0;
                bool readToUserBuffer = false;
                byte[] tmpByteBuffer = this._byteBuffer;
                Stream tmpStream = this._stream;
                int count = buffer.Length;
                while (count > 0)
                {
                    int i = this._charLen - this._charPos;
                    if (i == 0)
                    {
                        this._charLen = 0;
                        this._charPos = 0;
                        if (!this._checkPreamble)
{
                            this._byteLen = 0;
                        }
                        readToUserBuffer = count >= this._maxCharsPerBuffer;
                        do
{
                            if (this._checkPreamble)
{
                                int bytePos = this._bytePos;
                                int num2 = await tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer, bytePos, tmpByteBuffer.Length - bytePos), cancellationToken).ConfigureAwait(false);
                                if (num2 == 0)
{
                                    goto Block_7;
                                }
                                this._byteLen += num2;
                            }
                            else
{
                                this._byteLen = await tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer), cancellationToken).ConfigureAwait(false);
                                if (this._byteLen == 0)
{
                                    goto Block_10;
                                }
                            }
                            this._isBlocked = this._byteLen < tmpByteBuffer.Length;
                            if (!this.IsPreamble())
{
                                if (this._detectEncoding && this._byteLen >= 2)
{
                                    this.DetectEncoding();
                                    readToUserBuffer = count >= this._maxCharsPerBuffer;
                                }
                                this._charPos = 0;
                                if (readToUserBuffer)
{
                                    i += this._decoder.GetChars(new ReadOnlySpan<byte>(tmpByteBuffer, 0, this._byteLen), buffer.Span.Slice(charsRead), false);
                                    this._charLen = 0;
                                }
                                else
{
                                    i = this._decoder.GetChars(tmpByteBuffer, 0, this._byteLen, this._charBuffer, 0);
                                    this._charLen += i;
                                }
                            }
                        }
                        while (i == 0);
                        IL_0423:
                        if (i != 0)
{
                            goto IL_042E;
                        }
                        break;
                        Block_10:
                        this._isBlocked = true;
                        goto IL_0423;
                        Block_7:
                        if (this._byteLen > 0)
{
                            if (readToUserBuffer)
{
                                i = this._decoder.GetChars(new ReadOnlySpan<byte>(tmpByteBuffer, 0, this._byteLen), buffer.Span.Slice(charsRead), false);
                                this._charLen = 0;
                            }
                            else
{
                                i = this._decoder.GetChars(tmpByteBuffer, 0, this._byteLen, this._charBuffer, 0);
                                this._charLen += i;
                            }
                        }
                        this._isBlocked = true;
                        goto IL_0423;
                    }
                    IL_042E:
                    if (i > count)
                    {
                        i = count;
                    }
                    if (!readToUserBuffer)
                    {
                        new Span<char>(this._charBuffer, this._charPos, i).CopyTo(buffer.Span.Slice(charsRead));
                        this._charPos += i;
                    }
                    charsRead += i;
                    count -= i;
                    if (this._isBlocked)
                    {
                        break;
                    }
                }
                num = charsRead;
            }
            return num;
        }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._isBlocked, System.IO.StreamReader._maxCharsPerBuffer, System.IO.StreamReader._stream, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Span< T >.CopyTo(), System.count, System.IO.StreamReader.DetectEncoding(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), System.Memory< T >.Length, System.IO.Stream.ReadAsync(), System.IO.StreamReader.ReadBufferAsync(), and System.Memory< T >.Span.
Referenced by System.IO.StreamReader.d__66.MoveNext(), System.IO.StreamReader.ReadAsync(), and System.IO.StreamReader.ReadAsync().