Terraria Decompiled: System.IO.StreamReader.ReadLine
ReadLine()
override string System.IO.StreamReader.ReadLine () inline virtual
Reimplemented from System.IO.TextReader.
Reimplemented in System.IO.UnexceptionalStreamReader.
Definition at line 635 of file StreamReader.cs.
        {
            if (this._stream == null)
            {
                throw new ObjectDisposedException(null, "Cannot read from a closed TextReader.");
            }
            this.CheckAsyncTaskInProgress();
            if (this._charPos == this._charLen && this.ReadBuffer() == 0)
            {
                return null;
            }
            StringBuilder stringBuilder = null;
            int num;
            char c;
            for (;;)
            {
                num = this._charPos;
                do
                {
                    c = this._charBuffer[num];
                    if (c == '\r' || c == '\n')
                    {
                        goto IL_0051;
                    }
                    num++;
                }
                while (num < this._charLen);
                num = this._charLen - this._charPos;
                if (stringBuilder == null)
                {
                    stringBuilder = new StringBuilder(num + 80);
                }
                stringBuilder.Append(this._charBuffer, this._charPos, num);
                if (this.ReadBuffer() <= 0)
                {
                    goto Block_11;
                }
            }
            IL_0051:
            string text;
            if (stringBuilder != null)
            {
                stringBuilder.Append(this._charBuffer, this._charPos, num - this._charPos);
                text = stringBuilder.ToString();
            }
            else
            {
                text = new string(this._charBuffer, this._charPos, num - this._charPos);
            }
            this._charPos = num + 1;
            if (c == '\r' && (this._charPos < this._charLen || this.ReadBuffer() > 0) && this._charBuffer[this._charPos] == '\n')
            {
                this._charPos++;
            }
            return text;
            Block_11:
            return stringBuilder.ToString();
        }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.IO.StreamReader._stream, System.Text.StringBuilder.Append(), System.IO.StreamReader.CheckAsyncTaskInProgress(), System.IO.StreamReader.ReadBuffer(), System.text, and System.Text.StringBuilder.ToString().
Referenced by Microsoft.Win32.KeyHandler.GetRegisteredBootTime(), Microsoft.Win32.KeyHandler.GetSystemBootTime(), System.TimeZoneInfo.GetTimeZoneIds(), System.IO.File.InternalReadAllLines(), Terraria.Netplay.IsBanned(), Terraria.Main.LoadDedConfig(), and System.IO.ReadLinesIterator.MoveNext().