Terraria Decompiled: System.IO.StreamReader.ReadBufferAsync
ReadBufferAsync()
async Task< int > System.IO.StreamReader.ReadBufferAsync () inline private
Definition at line 1084 of file StreamReader.cs.
        {
            this._charLen = 0;
            this._charPos = 0;
            byte[] tmpByteBuffer = this._byteBuffer;
            Stream tmpStream = this._stream;
            if (!this._checkPreamble)
            {
                this._byteLen = 0;
            }
            for (;;)
            {
                if (this._checkPreamble)
                {
                    int bytePos = this._bytePos;
                    int num = await tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer, bytePos, tmpByteBuffer.Length - bytePos), default(CancellationToken)).ConfigureAwait(false);
                    if (num == 0)
                    {
                        break;
                    }
                    this._byteLen += num;
                }
                else
                {
                    this._byteLen = await tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer), default(CancellationToken)).ConfigureAwait(false);
                    if (this._byteLen == 0)
                    {
                        goto Block_5;
                    }
                }
                this._isBlocked = this._byteLen < tmpByteBuffer.Length;
                if (!this.IsPreamble())
                {
                    if (this._detectEncoding && this._byteLen >= 2)
                    {
                        this.DetectEncoding();
                    }
                    this._charLen += this._decoder.GetChars(tmpByteBuffer, 0, this._byteLen, this._charBuffer, this._charLen);
                }
                if (this._charLen != 0)
                {
                    goto Block_9;
                }
            }
            if (this._byteLen > 0)
            {
                this._charLen += this._decoder.GetChars(tmpByteBuffer, 0, this._byteLen, this._charBuffer, this._charLen);
                this._bytePos = 0;
                this._byteLen = 0;
            }
            return this._charLen;
            Block_5:
            return this._charLen;
            Block_9:
            return this._charLen;
        }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._stream, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.StreamReader.DetectEncoding(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), and System.IO.Stream.ReadAsync().
Referenced by System.IO.StreamReader.d__61.MoveNext(), System.IO.StreamReader.d__63.MoveNext(), System.IO.StreamReader.d__66.MoveNext(), System.IO.StreamReader.d__69.MoveNext(), System.IO.StreamReader.ReadAsyncInternal(), System.IO.StreamReader.ReadLineAsyncInternal(), and System.IO.StreamReader.ReadToEndAsyncInternal().