Terraria Decompiled: Mono.Security.StrongNameManager.LoadConfig
LoadConfig()
static void Mono.Security.StrongNameManager.LoadConfig (string filename) inline static
Definition at line 17 of file StrongNameManager.cs.
        {
            if (File.Exists(filename))
            {
                SecurityParser securityParser = new SecurityParser();
                using (StreamReader streamReader = new StreamReader(filename))
                {
                    string text = streamReader.ReadToEnd();
                    securityParser.LoadXml(text);
                }
                SecurityElement securityElement = securityParser.ToXml();
                if (securityElement != null && securityElement.Tag == "configuration")
                {
                    SecurityElement securityElement2 = securityElement.SearchForChildByTag("strongNames");
                    if (securityElement2 != null && securityElement2.Children.Count > 0)
                    {
                        SecurityElement securityElement3 = securityElement2.SearchForChildByTag("pubTokenMapping");
                        if (securityElement3 != null && securityElement3.Children.Count > 0)
{
                            StrongNameManager.LoadMapping(securityElement3);
                        }
                        SecurityElement securityElement4 = securityElement2.SearchForChildByTag("verificationSettings");
                        if (securityElement4 != null && securityElement4.Children.Count > 0)
{
                            StrongNameManager.LoadVerificationSettings(securityElement4);
                        }
                    }
                }
            }
        }
References System.Security.SecurityElement.Children, System.Collections.ArrayList.Count, System.IO.File.Exists(), Mono.Security.StrongNameManager.LoadMapping(), Mono.Security.StrongNameManager.LoadVerificationSettings(), Mono.Xml.SecurityParser.LoadXml(), System.IO.StreamReader.ReadToEnd(), System.Security.SecurityElement.SearchForChildByTag(), System.Security.SecurityElement.Tag, System.text, and Mono.Xml.SecurityParser.ToXml().
Referenced by Mono.Security.StrongName.IsAssemblyStrongnamed().