Terraria Decompiled: Mono.Security.StrongNameManager.LoadVerificationSettings
LoadVerificationSettings()
static void Mono.Security.StrongNameManager.LoadVerificationSettings (SecurityElement settings) inline static private
Definition at line 86 of file StrongNameManager.cs.
        {
            if (StrongNameManager.tokens == null)
            {
                StrongNameManager.tokens = new Hashtable();
            }
            object syncRoot = StrongNameManager.tokens.SyncRoot;
            lock (syncRoot)
            {
                foreach (object obj in settings.Children)
                {
                    SecurityElement securityElement = (SecurityElement)obj;
                    if (!(securityElement.Tag != "skip"))
                    {
                        string text = securityElement.Attribute("Token");
                        if (text != null)
{
                            text = text.ToUpper(CultureInfo.InvariantCulture);
                            string text2 = securityElement.Attribute("Assembly");
                            if (text2 == null)
{
                                text2 = "*";
                            }
                            string text3 = securityElement.Attribute("Users");
                            if (text3 == null)
{
                                text3 = "*";
                            }
                            StrongNameManager.Element element = (StrongNameManager.Element)StrongNameManager.tokens[text];
                            if (element == null)
{
                                element = new StrongNameManager.Element(text2, text3);
                                StrongNameManager.tokens.Add(text, element);
                            }
                            else if ((string)element.assemblies[text2] == null)
{
                                element.assemblies.Add(text2, text3);
                            }
                            else if (text3 == "*")
{
                                element.assemblies[text2] = "*";
                            }
                            else
{
                                string text4 = (string)element.assemblies[text2] + "," + text3;
                                element.assemblies[text2] = text4;
                            }
                        }
                    }
                }
            }
        }
References System.Collections.Hashtable.Add(), Mono.Security.StrongNameManager.Element.assemblies, System.Security.SecurityElement.Attribute(), System.Security.SecurityElement.Children, System.Globalization.CultureInfo.InvariantCulture, System.obj, System.Collections.Hashtable.SyncRoot, System.Security.SecurityElement.Tag, System.text, and Mono.Security.StrongNameManager.tokens.
Referenced by Mono.Security.StrongNameManager.LoadConfig().