Terraria Decompiled: Mono.Security.StrongNameManager.MustVerify
MustVerify()
static bool Mono.Security.StrongNameManager.MustVerify (AssemblyName an) inline static
Definition at line 156 of file StrongNameManager.cs.
        {
            if (an == null || StrongNameManager.tokens == null)
            {
                return true;
            }
            string text = CryptoConvert.ToHex(an.GetPublicKeyToken());
            StrongNameManager.Element element = (StrongNameManager.Element)StrongNameManager.tokens[text];
            if (element != null)
            {
                string text2 = element.GetUsers(an.Name);
                if (text2 == null)
                {
                    text2 = element.GetUsers("*");
                }
                if (text2 != null)
                {
                    return !(text2 == "*") && text2.IndexOf(Environment.UserName) < 0;
                }
            }
            return true;
        }
References System.Reflection.AssemblyName.GetPublicKeyToken(), Mono.Security.StrongNameManager.Element.GetUsers(), System.Reflection.AssemblyName.Name, System.text, Mono.Security.Cryptography.CryptoConvert.ToHex(), and Mono.Security.StrongNameManager.tokens.
Referenced by Mono.Security.StrongName.IsAssemblyStrongnamed().