Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.Segment.TryDequeue
TryDequeue()
bool System.Collections.Concurrent.ConcurrentQueue< T >.Segment.TryDequeue (out T item) inline
Definition at line 564 of file ConcurrentQueue.cs.
            {
                SpinWait spinWait = default(SpinWait);
                int num;
                int num2;
                for (;;)
                {
                    num = Volatile.Read(ref this._headAndTail.Head);
                    num2 = num & this._slotsMask;
                    int num3 = Volatile.Read(ref this._slots[num2].SequenceNumber) - (num + 1);
                    if (num3 == 0)
                    {
                        if (Interlocked.CompareExchange(ref this._headAndTail.Head, num + 1, num) == num)
{
                            break;
                        }
                    }
                    else if (num3 < 0)
                    {
                        bool frozenForEnqueues = this._frozenForEnqueues;
                        int num4 = Volatile.Read(ref this._headAndTail.Tail);
                        if (num4 - num <= 0 || (frozenForEnqueues && num4 - this.FreezeOffset - num <= 0))
{
                            goto IL_00EE;
                        }
                    }
                    spinWait.SpinOnce();
                }
                item = this._slots[num2].Item;
                if (!Volatile.Read(ref this._preservedForObservation))
                {
                    this._slots[num2].Item = default(T);
                    Volatile.Write(ref this._slots[num2].SequenceNumber, num + this._slots.Length);
                }
                return true;
                IL_00EE:
                item = default(T);
                return false;
            }
References System.Collections.Concurrent.ConcurrentQueue< T >.Segment._frozenForEnqueues, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._headAndTail, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._slots, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._slotsMask, System.Threading.Interlocked.CompareExchange(), System.Collections.Concurrent.ConcurrentQueue< T >.Segment.FreezeOffset, System.Collections.Concurrent.PaddedHeadAndTail.Head, System.item, System.Threading.Volatile.Read(), System.Threading.SpinWait.SpinOnce(), System.Collections.Concurrent.PaddedHeadAndTail.Tail, and System.Threading.Volatile.Write().
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.TryDequeue().