Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.Segment.TryPeek
TryPeek()
bool System.Collections.Concurrent.ConcurrentQueue< T >.Segment.TryPeek (out T result, bool resultUsed) inline
Definition at line 605 of file ConcurrentQueue.cs.
            {
                if (resultUsed)
                {
                    this._preservedForObservation = true;
                    Interlocked.MemoryBarrier();
                }
                SpinWait spinWait = default(SpinWait);
                int num2;
                for (;;)
                {
                    int num = Volatile.Read(ref this._headAndTail.Head);
                    num2 = num & this._slotsMask;
                    int num3 = Volatile.Read(ref this._slots[num2].SequenceNumber) - (num + 1);
                    if (num3 == 0)
                    {
                        break;
                    }
                    if (num3 < 0)
                    {
                        bool frozenForEnqueues = this._frozenForEnqueues;
                        int num4 = Volatile.Read(ref this._headAndTail.Tail);
                        if (num4 - num <= 0 || (frozenForEnqueues && num4 - this.FreezeOffset - num <= 0))
{
                            goto IL_00AE;
                        }
                    }
                    spinWait.SpinOnce();
                }
                result = (resultUsed ? this._slots[num2].Item : default(T));
                return true;
                IL_00AE:
                result = default(T);
                return false;
            }
References System.Collections.Concurrent.ConcurrentQueue< T >.Segment._frozenForEnqueues, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._headAndTail, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._slots, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._slotsMask, System.Collections.Concurrent.ConcurrentQueue< T >.Segment.FreezeOffset, System.Collections.Concurrent.PaddedHeadAndTail.Head, System.Threading.Interlocked.MemoryBarrier(), System.Threading.Volatile.Read(), System.Threading.SpinWait.SpinOnce(), and System.Collections.Concurrent.PaddedHeadAndTail.Tail.