Terraria Decompiled: System.Collections.Concurrent.ConcurrentQueue.Segment.EnsureFrozenForEnqueues
EnsureFrozenForEnqueues()
void System.Collections.Concurrent.ConcurrentQueue< T >.Segment.EnsureFrozenForEnqueues () inline package
Definition at line 545 of file ConcurrentQueue.cs.
            {
                if (!this._frozenForEnqueues)
                {
                    this._frozenForEnqueues = true;
                    SpinWait spinWait = default(SpinWait);
                    for (;;)
                    {
                        int num = Volatile.Read(ref this._headAndTail.Tail);
                        if (Interlocked.CompareExchange(ref this._headAndTail.Tail, num + this.FreezeOffset, num) == num)
{
                            break;
                        }
                        spinWait.SpinOnce();
                    }
                }
            }
References System.Collections.Concurrent.ConcurrentQueue< T >.Segment._frozenForEnqueues, System.Collections.Concurrent.ConcurrentQueue< T >.Segment._headAndTail, System.Threading.Interlocked.CompareExchange(), System.Threading.Volatile.Read(), System.Threading.SpinWait.SpinOnce(), and System.Collections.Concurrent.PaddedHeadAndTail.Tail.
Referenced by System.Collections.Concurrent.ConcurrentQueue< T >.Clear(), and System.Collections.Concurrent.ConcurrentQueue< T >.SnapForObservation().