Terraria Decompiled: Terraria.ID.SoundID.FillAccessMap
FillAccessMap()
static void Terraria.ID.SoundID.FillAccessMap () inline static
Definition at line 70 of file SoundID.cs.
        {
            Dictionary<string, LegacySoundStyle> ret = new Dictionary<string, LegacySoundStyle>();
            Dictionary<string, ushort> ret2 = new Dictionary<string, ushort>();
            Dictionary<ushort, LegacySoundStyle> ret3 = new Dictionary<ushort, LegacySoundStyle>();
            ushort nextIndex = 0;
            List<FieldInfo> list = (from f in typeof(SoundID).GetFields(BindingFlags.Static | BindingFlags.Public)
                where f.FieldType == typeof(LegacySoundStyle)
                select f).ToList<FieldInfo>();
            list.Sort((FieldInfo a, FieldInfo b) => string.Compare(a.Name, b.Name));
            list.ForEach(delegate(FieldInfo field)
            {
                ret[field.Name] = (LegacySoundStyle)field.GetValue(null);
                ret2[field.Name] = nextIndex;
                ret3[nextIndex] = (LegacySoundStyle)field.GetValue(null);
                ushort nextIndex2 = nextIndex;
                nextIndex = nextIndex2 + 1;
            });
            SoundID.SoundByName = ret;
            SoundID.IndexByName = ret2;
            SoundID.SoundByIndex = ret3;
        }
References System.Reflection.FieldInfo.GetValue(), System.list, System.Reflection.MemberInfo.Name, and System.Collections.Generic.List< T >.Sort().
Referenced by Terraria.Main.Initialize_AlmostEverything().