Terraria Decompiled: Terraria.Graphics.Shaders.MiscShaderData.Apply
Apply()
virtual void Terraria.Graphics.Shaders.MiscShaderData.Apply (DrawData? drawData = null) inline virtual
Definition at line 41 of file MiscShaderData.cs.
        {
            this.CheckCachedParameters();
            this.uColor.SetValue(this._uColor);
            this.uSaturation.SetValue(this._uSaturation);
            this.uSecondaryColor.SetValue(this._uSecondaryColor);
            this.uTime.SetValue(Main.GlobalTimeWrappedHourly);
            this.uOpacity.SetValue(this._uOpacity);
            this.uShaderSpecificData.SetValue(this._shaderSpecificData);
            if (drawData != null)
            {
                DrawData value = drawData.Value;
                Vector4 zero = Vector4.Zero;
                if (drawData.Value.sourceRect != null)
                {
                    zero = new Vector4((float)value.sourceRect.Value.X, (float)value.sourceRect.Value.Y, (float)value.sourceRect.Value.Width, (float)value.sourceRect.Value.Height);
                }
                this.uSourceRect.SetValue(zero);
                this.uDrawPosition.SetValue(value.position);
                this.uImageSize0.SetValue(new Vector2((float)value.texture.Width, (float)value.texture.Height));
            }
            else
            {
                this.uSourceRect.SetValue(new Vector4(0f, 0f, 4f, 4f));
            }
            SamplerState samplerState = SamplerState.LinearWrap;
            if (this._customSamplerState != null)
            {
                samplerState = this._customSamplerState;
            }
            Texture texture = ((this._uImage0 != null) ? this._uImage0.Value : this._uImage0Tex);
            if (texture != null)
            {
                Main.graphics.GraphicsDevice.Textures[0] = texture;
                Main.graphics.GraphicsDevice.SamplerStates[0] = samplerState;
                if (texture is Texture2D)
                {
                    this.uImageSize0.SetValue(((Texture2D)texture).Size());
                }
            }
            texture = ((this._uImage1 != null) ? this._uImage1.Value : this._uImage1Tex);
            if (texture != null)
            {
                Main.graphics.GraphicsDevice.Textures[1] = texture;
                Main.graphics.GraphicsDevice.SamplerStates[1] = samplerState;
                if (texture is Texture2D)
                {
                    this.uImageSize1.SetValue(((Texture2D)texture).Size());
                }
            }
            texture = ((this._uImage2 != null) ? this._uImage2.Value : this._uImage2Tex);
            if (texture != null)
            {
                Main.graphics.GraphicsDevice.Textures[2] = texture;
                Main.graphics.GraphicsDevice.SamplerStates[2] = samplerState;
                if (texture is Texture2D)
                {
                    this.uImageSize2.SetValue(((Texture2D)texture).Size());
                }
            }
            if (this._useProjectionMatrix)
            {
                this.MatrixTransform.SetValue(Main.GameViewMatrix.NormalizedTransformationMatrix);
            }
            if (this._transformMatrix != null)
            {
                this.MatrixTransform.SetValue(this._transformMatrix.Value);
            }
            base.Apply();
        }
References Terraria.Graphics.Shaders.MiscShaderData._customSamplerState, Terraria.Graphics.Shaders.MiscShaderData._shaderSpecificData, Terraria.Graphics.Shaders.MiscShaderData._transformMatrix, Terraria.Graphics.Shaders.MiscShaderData._uColor, Terraria.Graphics.Shaders.MiscShaderData._uImage0, Terraria.Graphics.Shaders.MiscShaderData._uImage0Tex, Terraria.Graphics.Shaders.MiscShaderData._uImage1, Terraria.Graphics.Shaders.MiscShaderData._uImage1Tex, Terraria.Graphics.Shaders.MiscShaderData._uImage2, Terraria.Graphics.Shaders.MiscShaderData._uImage2Tex, Terraria.Graphics.Shaders.MiscShaderData._uOpacity, Terraria.Graphics.Shaders.MiscShaderData._uSaturation, Terraria.Graphics.Shaders.MiscShaderData._uSecondaryColor, Terraria.Graphics.Shaders.MiscShaderData._useProjectionMatrix, Terraria.Graphics.Shaders.ShaderData.Apply(), Terraria.Graphics.Shaders.MiscShaderData.CheckCachedParameters(), Terraria.Main.GameViewMatrix, Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.graphics, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDevice, Microsoft.Xna.Framework.Graphics.SamplerState.LinearWrap, Terraria.Graphics.Shaders.MiscShaderData.MatrixTransform, Terraria.DataStructures.DrawData.position, Microsoft.Xna.Framework.Graphics.GraphicsDevice.SamplerStates, Terraria.DataStructures.DrawData.texture, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Textures, Terraria.Graphics.Shaders.MiscShaderData.uColor, Terraria.Graphics.Shaders.MiscShaderData.uDrawPosition, Terraria.Graphics.Shaders.MiscShaderData.uImageSize0, Terraria.Graphics.Shaders.MiscShaderData.uImageSize1, Terraria.Graphics.Shaders.MiscShaderData.uImageSize2, Terraria.Graphics.Shaders.MiscShaderData.uOpacity, Terraria.Graphics.Shaders.MiscShaderData.uSaturation, Terraria.Graphics.Shaders.MiscShaderData.uSecondaryColor, Terraria.Graphics.Shaders.MiscShaderData.uShaderSpecificData, Terraria.Graphics.Shaders.MiscShaderData.uSourceRect, Terraria.Graphics.Shaders.MiscShaderData.uTime, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Graphics.Vector4, Microsoft.Xna.Framework.Graphics.Texture2D.Width, and Microsoft.Xna.Framework.Vector4.Zero.
Referenced by Terraria.GameContent.Animations.Segments.SpriteSegment.MaskedFadeEffect.BeforeDrawing(), Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd(), Terraria.Graphics.EmpressBladeDrawer.Draw(), Terraria.Graphics.FinalFractalHelper.Draw(), Terraria.Graphics.FlameLashDrawer.Draw(), Terraria.Graphics.LightDiscDrawer.Draw(), Terraria.Graphics.MagicMissileDrawer.Draw(), Terraria.Graphics.RainbowRodDrawer.Draw(), Terraria.UI.ItemSlot.Draw(), Terraria.Graphics.StormLightningDrawer.Draw(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.GameContent.Drawing.NextHorizonRenderer.DrawLensFlare(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing(), Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader(), and Terraria.GameContent.PlayerTitaniumStormBuffTextureContent.HandleUseRequest().