Terraria Decompiled: Terraria.Graphics.Shaders.MiscShaderData.UseSpriteTransformMatrix
UseSpriteTransformMatrix()
MiscShaderData Terraria.Graphics.Shaders.MiscShaderData.UseSpriteTransformMatrix (Matrix? transform) inline
Definition at line 250 of file MiscShaderData.cs.
        {
            if (transform == null)
            {
                this._transformMatrix = null;
                return this;
            }
            Viewport viewport = Main.graphics.GraphicsDevice.Viewport;
            float num = ((viewport.Width > 0) ? (1f / (float)viewport.Width) : 0f);
            float num2 = ((viewport.Height > 0) ? (-1f / (float)viewport.Height) : 0f);
            Matrix matrix = new Matrix
            {
                M11 = num * 2f,
                M22 = num2 * 2f,
                M33 = 1f,
                M44 = 1f,
                M41 = -1f - num,
                M42 = 1f - num2
            };
            this._transformMatrix = new Matrix?(transform.Value * matrix);
            return this;
        }
References Terraria.Main.graphics, Microsoft.Xna.Framework.GraphicsDeviceManager.GraphicsDevice, Microsoft.Xna.Framework.Graphics.Viewport.Height, Microsoft.Xna.Framework.Graphics.GraphicsDevice.Viewport, and Microsoft.Xna.Framework.Graphics.Viewport.Width.
Referenced by Terraria.GameContent.Drawing.NextHorizonRenderer.CloudsEnd(), Terraria.GameContent.Skies.AuroraSky.DrawAuroraSky(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing(), and Terraria.GameContent.Drawing.NextNatureRenderer.DrawWithLitNatureShader().