Terraria Decompiled: Terraria.GameContent.UI.Elements.AWorldListItem.GetIcons
GetIcons()
List< Asset< Texture2D > > Terraria.GameContent.UI.Elements.AWorldListItem.GetIcons () inline protected
Definition at line 131 of file AWorldListItem.cs.
        {
            List<Asset<Texture2D>> list = new List<Asset<Texture2D>>();
            if (this._data.DrunkWorld)
            {
                list.Add(this.GetSeedIcon("CorruptionCrimson", true, false));
            }
            if (this._data.ForTheWorthy)
            {
                list.Add(this.GetSeedIcon("FTW", true, true));
            }
            if (this._data.NotTheBees)
            {
                list.Add(this.GetSeedIcon("NotTheBees", true, true));
            }
            if (this._data.Anniversary)
            {
                list.Add(this.GetSeedIcon("Anniversary", true, true));
            }
            if (this._data.DontStarve)
            {
                list.Add(this.GetSeedIcon("DontStarve", true, true));
            }
            if (this._data.RemixWorld)
            {
                list.Add(this.GetSeedIcon("Remix", true, true));
            }
            if (this._data.NoTrapsWorld)
            {
                list.Add(this.GetSeedIcon("Traps", true, true));
            }
            if (this._data.SkyblockWorld)
            {
                list.Add(this.GetSeedIcon("Skyblock", false, false));
            }
            if (list.Count > 0)
            {
                return list;
            }
            list.Add(this.GetSeedIcon("", true, true));
            return list;
        }
References Terraria.GameContent.UI.Elements.AWorldListItem._data, System.Collections.Generic.List< T >.Add(), Terraria.IO.WorldFileData.Anniversary, System.Collections.Generic.List< T >.Count, Terraria.IO.WorldFileData.DontStarve, Terraria.IO.WorldFileData.DrunkWorld, Terraria.IO.WorldFileData.ForTheWorthy, Terraria.GameContent.UI.Elements.AWorldListItem.GetSeedIcon(), System.list, Terraria.IO.WorldFileData.NoTrapsWorld, Terraria.IO.WorldFileData.NotTheBees, Terraria.IO.WorldFileData.RemixWorld, and Terraria.IO.WorldFileData.SkyblockWorld.
Referenced by Terraria.GameContent.UI.Elements.AWorldListItem.GetIconElement().