Terraria Decompiled: System.Security.Cryptography.DSA.FromXmlString
FromXmlString()
override void System.Security.Cryptography.DSA.FromXmlString (string xmlString) inline virtual
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 154 of file DSA.cs.
        {
            if (xmlString == null)
            {
                throw new ArgumentNullException("xmlString");
            }
            DSAParameters dsaparameters = default(DSAParameters);
            SecurityElement topElement = new Parser(xmlString).GetTopElement();
            string text = topElement.SearchForTextOfLocalName("P");
            if (text == null)
            {
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "DSA", "P" }));
            }
            dsaparameters.P = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text));
            string text2 = topElement.SearchForTextOfLocalName("Q");
            if (text2 == null)
            {
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "DSA", "Q" }));
            }
            dsaparameters.Q = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text2));
            string text3 = topElement.SearchForTextOfLocalName("G");
            if (text3 == null)
            {
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "DSA", "G" }));
            }
            dsaparameters.G = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text3));
            string text4 = topElement.SearchForTextOfLocalName("Y");
            if (text4 == null)
            {
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "DSA", "Y" }));
            }
            dsaparameters.Y = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text4));
            string text5 = topElement.SearchForTextOfLocalName("J");
            if (text5 != null)
            {
                dsaparameters.J = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text5));
            }
            string text6 = topElement.SearchForTextOfLocalName("X");
            if (text6 != null)
            {
                dsaparameters.X = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text6));
            }
            string text7 = topElement.SearchForTextOfLocalName("Seed");
            string text8 = topElement.SearchForTextOfLocalName("PgenCounter");
            if (text7 != null && text8 != null)
            {
                dsaparameters.Seed = Convert.FromBase64String(Utils.DiscardWhiteSpaces(text7));
                dsaparameters.Counter = Utils.ConvertByteArrayToInt(Convert.FromBase64String(Utils.DiscardWhiteSpaces(text8)));
            }
            else if (text7 != null || text8 != null)
            {
                if (text7 == null)
                {
                    throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "DSA", "Seed" }));
                }
                throw new CryptographicException(Environment.GetResourceString("Input string does not contain a valid encoding of the '{0}' '{1}' parameter.", new object[] { "DSA", "PgenCounter" }));
            }
            this.ImportParameters(dsaparameters);
        }
References System.Security.Cryptography.Utils.ConvertByteArrayToInt(), System.Security.Cryptography.Utils.DiscardWhiteSpaces(), System.Convert.FromBase64String(), System.Environment.GetResourceString(), System.Security.Util.Parser.GetTopElement(), System.Security.Cryptography.DSA.ImportParameters(), System.Security.SecurityElement.SearchForTextOfLocalName(), and System.text.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.Common().