Terraria Decompiled: System.Security.Cryptography.DSA.VerifyData
VerifyData() [3/4]
virtual bool System.Security.Cryptography.DSA.VerifyData (ReadOnlySpan< byte > data, ReadOnlySpan< byte > signature, HashAlgorithmName hashAlgorithm) inline virtual
Definition at line 355 of file DSA.cs.
        {
            if (string.IsNullOrEmpty(hashAlgorithm.Name))
            {
                throw DSA.HashAlgorithmNameNullOrEmpty();
            }
            int num = 256;
            checked
            {
                bool flag;
                for (;;)
                {
                    int num2 = 0;
                    byte[] array = ArrayPool<byte>.Shared.Rent(num);
                    try
                    {
                        if (this.TryHashData(data, array, hashAlgorithm, out num2))
{
                            flag = this.VerifySignature(new ReadOnlySpan<byte>(array, 0, num2), signature);
                            break;
                        }
                    }
                    finally
                    {
                        Array.Clear(array, 0, num2);
                        ArrayPool<byte>.Shared.Return(array, false);
                    }
                    num *= 2;
                }
                return flag;
            }
        }
References System.array, System.Array.Clear(), System.Security.Cryptography.DSA.HashAlgorithmNameNullOrEmpty(), System.Security.Cryptography.HashAlgorithmName.Name, System.Buffers.ArrayPool< T >.Shared, System.Security.Cryptography.DSA.TryHashData(), and System.Security.Cryptography.DSA.VerifySignature().