Terraria Decompiled: System.Security.Cryptography.DSA.ToXmlString
ToXmlString()
override string System.Security.Cryptography.DSA.ToXmlString (bool includePrivateParameters) inline virtual
Reimplemented from System.Security.Cryptography.AsymmetricAlgorithm.
Definition at line 215 of file DSA.cs.
        {
            DSAParameters dsaparameters = this.ExportParameters(includePrivateParameters);
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.Append("<DSAKeyValue>");
            stringBuilder.Append("<P>" + Convert.ToBase64String(dsaparameters.P) + "</P>");
            stringBuilder.Append("<Q>" + Convert.ToBase64String(dsaparameters.Q) + "</Q>");
            stringBuilder.Append("<G>" + Convert.ToBase64String(dsaparameters.G) + "</G>");
            stringBuilder.Append("<Y>" + Convert.ToBase64String(dsaparameters.Y) + "</Y>");
            if (dsaparameters.J != null)
            {
                stringBuilder.Append("<J>" + Convert.ToBase64String(dsaparameters.J) + "</J>");
            }
            if (dsaparameters.Seed != null)
            {
                stringBuilder.Append("<Seed>" + Convert.ToBase64String(dsaparameters.Seed) + "</Seed>");
                stringBuilder.Append("<PgenCounter>" + Convert.ToBase64String(Utils.ConvertIntToByteArray(dsaparameters.Counter)) + "</PgenCounter>");
            }
            if (includePrivateParameters)
            {
                stringBuilder.Append("<X>" + Convert.ToBase64String(dsaparameters.X) + "</X>");
            }
            stringBuilder.Append("</DSAKeyValue>");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Security.Cryptography.Utils.ConvertIntToByteArray(), System.Security.Cryptography.DSAParameters.Counter, System.Security.Cryptography.DSA.ExportParameters(), System.Security.Cryptography.DSAParameters.G, System.Security.Cryptography.DSAParameters.J, System.Security.Cryptography.DSAParameters.P, System.Security.Cryptography.DSAParameters.Q, System.Security.Cryptography.DSAParameters.Seed, System.Convert.ToBase64String(), System.Text.StringBuilder.ToString(), System.Security.Cryptography.DSAParameters.X, and System.Security.Cryptography.DSAParameters.Y.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.OnKeyGenerated().