Terraria Decompiled: Terraria.Audio.WAVAudioTrack.WAVAudioTrack
WAVAudioTrack()
Terraria.Audio.WAVAudioTrack.WAVAudioTrack (Stream stream) inline
Definition at line 11 of file WAVAudioTrack.cs.
        {
            this._stream = stream;
            BinaryReader binaryReader = new BinaryReader(stream);
            binaryReader.ReadInt32();
            binaryReader.ReadInt32();
            binaryReader.ReadInt32();
            AudioChannels audioChannels = AudioChannels.Mono;
            uint num = 0U;
            bool flag = false;
            int num2 = 0;
            while (!flag && num2 < 10)
            {
                uint num3 = binaryReader.ReadUInt32();
                int num4 = binaryReader.ReadInt32();
                if (num3 != 544501094U)
                {
                    if (num3 == 1263424842U)
                    {
                        WAVAudioTrack.SkipJunk(binaryReader, num4);
                    }
                }
                else
                {
                    binaryReader.ReadInt16();
                    audioChannels = (AudioChannels)binaryReader.ReadUInt16();
                    num = binaryReader.ReadUInt32();
                    binaryReader.ReadInt32();
                    binaryReader.ReadInt16();
                    binaryReader.ReadInt16();
                    flag = true;
                }
                if (!flag)
                {
                    num2++;
                }
            }
            binaryReader.ReadInt32();
            binaryReader.ReadInt32();
            this._streamContentStartIndex = stream.Position;
            base.CreateSoundEffect((int)num, audioChannels);
        }
References System.IO.Stream.Position, System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), Terraria.Audio.WAVAudioTrack.SkipJunk(), and System.U.