Terraria Decompiled: Mono.Security.Cryptography.MD4Managed.Initialize
Initialize()
override void Mono.Security.Cryptography.MD4Managed.Initialize () inline
Definition at line 20 of file MD4Managed.cs.
        {
            this.count[0] = 0U;
            this.count[1] = 0U;
            this.state[0] = 1732584193U;
            this.state[1] = 4023233417U;
            this.state[2] = 2562383102U;
            this.state[3] = 271733878U;
            Array.Clear(this.buffer, 0, 64);
            Array.Clear(this.x, 0, 16);
        }
References Mono.Security.Cryptography.MD4Managed.buffer, System.Array.Clear(), Mono.Security.Cryptography.MD4Managed.count, Mono.Security.Cryptography.MD4Managed.state, System.U, and Mono.Security.Cryptography.MD4Managed.x.
Referenced by Mono.Security.Cryptography.MD4Managed.HashFinal(), and Mono.Security.Cryptography.MD4Managed.MD4Managed().