Terraria Decompiled: System.Text.EncodingHelper.InvokeI18N
InvokeI18N()
static object System.Text.EncodingHelper.InvokeI18N (string name, params object[] args) inline static package
Definition at line 134 of file EncodingHelper.cs.
        {
            object obj = EncodingHelper.lockobj;
            object obj2;
            lock (obj)
            {
                if (EncodingHelper.i18nDisabled)
                {
                    obj2 = null;
                }
                else
                {
                    if (EncodingHelper.i18nAssembly == null)
                    {
                        try
{
                            try
{
                                EncodingHelper.i18nAssembly = Assembly.Load("I18N, Version=4.0.0.0, Culture=neutral, PublicKeyToken=0738eb9f132ed756");
                            }
                            catch (NotImplementedException)
{
                                EncodingHelper.i18nDisabled = true;
                                return null;
                            }
                            if (EncodingHelper.i18nAssembly == null)
{
                                return null;
                            }
                        }
                        catch (SystemException)
{
                            return null;
                        }
                    }
                    Type type;
                    try
                    {
                        type = EncodingHelper.i18nAssembly.GetType("I18N.Common.Manager");
                    }
                    catch (NotImplementedException)
                    {
                        EncodingHelper.i18nDisabled = true;
                        return null;
                    }
                    if (type == null)
                    {
                        obj2 = null;
                    }
                    else
                    {
                        object obj3;
                        try
{
                            obj3 = type.InvokeMember("PrimaryManager", BindingFlags.Static | BindingFlags.Public | BindingFlags.GetProperty, null, null, null, null, null, null);
                            if (obj3 == null)
{
                                return null;
                            }
                        }
                        catch (MissingMethodException)
{
                            return null;
                        }
                        catch (SecurityException)
{
                            return null;
                        }
                        catch (NotImplementedException)
{
                            EncodingHelper.i18nDisabled = true;
                            return null;
                        }
                        try
{
                            obj2 = type.InvokeMember(name, BindingFlags.Instance | BindingFlags.Public | BindingFlags.InvokeMethod, null, obj3, args, null, null, null);
                        }
                        catch (MissingMethodException)
{
                            obj2 = null;
                        }
                        catch (SecurityException)
{
                            obj2 = null;
                        }
                    }
                }
            }
            return obj2;
        }
References System.Reflection.Assembly.GetType(), System.Text.EncodingHelper.i18nAssembly, System.Text.EncodingHelper.i18nDisabled, System.Type.InvokeMember(), System.Reflection.Assembly.Load(), System.Text.EncodingHelper.lockobj, System.name, and System.obj.
Referenced by System.Text.Encoding.GetEncoding().