Terraria Decompiled: Mono.Security.Cryptography.MD4Managed.MD4Transform
MD4Transform()
void Mono.Security.Cryptography.MD4Managed.MD4Transform (uint[] state, byte[] block, int index) inline private
Definition at line 158 of file MD4Managed.cs.
        {
            uint num = state[0];
            uint num2 = state[1];
            uint num3 = state[2];
            uint num4 = state[3];
            this.Decode(this.x, block, index);
            this.FF(ref num, num2, num3, num4, this.x[0], 3);
            this.FF(ref num4, num, num2, num3, this.x[1], 7);
            this.FF(ref num3, num4, num, num2, this.x[2], 11);
            this.FF(ref num2, num3, num4, num, this.x[3], 19);
            this.FF(ref num, num2, num3, num4, this.x[4], 3);
            this.FF(ref num4, num, num2, num3, this.x[5], 7);
            this.FF(ref num3, num4, num, num2, this.x[6], 11);
            this.FF(ref num2, num3, num4, num, this.x[7], 19);
            this.FF(ref num, num2, num3, num4, this.x[8], 3);
            this.FF(ref num4, num, num2, num3, this.x[9], 7);
            this.FF(ref num3, num4, num, num2, this.x[10], 11);
            this.FF(ref num2, num3, num4, num, this.x[11], 19);
            this.FF(ref num, num2, num3, num4, this.x[12], 3);
            this.FF(ref num4, num, num2, num3, this.x[13], 7);
            this.FF(ref num3, num4, num, num2, this.x[14], 11);
            this.FF(ref num2, num3, num4, num, this.x[15], 19);
            this.GG(ref num, num2, num3, num4, this.x[0], 3);
            this.GG(ref num4, num, num2, num3, this.x[4], 5);
            this.GG(ref num3, num4, num, num2, this.x[8], 9);
            this.GG(ref num2, num3, num4, num, this.x[12], 13);
            this.GG(ref num, num2, num3, num4, this.x[1], 3);
            this.GG(ref num4, num, num2, num3, this.x[5], 5);
            this.GG(ref num3, num4, num, num2, this.x[9], 9);
            this.GG(ref num2, num3, num4, num, this.x[13], 13);
            this.GG(ref num, num2, num3, num4, this.x[2], 3);
            this.GG(ref num4, num, num2, num3, this.x[6], 5);
            this.GG(ref num3, num4, num, num2, this.x[10], 9);
            this.GG(ref num2, num3, num4, num, this.x[14], 13);
            this.GG(ref num, num2, num3, num4, this.x[3], 3);
            this.GG(ref num4, num, num2, num3, this.x[7], 5);
            this.GG(ref num3, num4, num, num2, this.x[11], 9);
            this.GG(ref num2, num3, num4, num, this.x[15], 13);
            this.HH(ref num, num2, num3, num4, this.x[0], 3);
            this.HH(ref num4, num, num2, num3, this.x[8], 9);
            this.HH(ref num3, num4, num, num2, this.x[4], 11);
            this.HH(ref num2, num3, num4, num, this.x[12], 15);
            this.HH(ref num, num2, num3, num4, this.x[2], 3);
            this.HH(ref num4, num, num2, num3, this.x[10], 9);
            this.HH(ref num3, num4, num, num2, this.x[6], 11);
            this.HH(ref num2, num3, num4, num, this.x[14], 15);
            this.HH(ref num, num2, num3, num4, this.x[1], 3);
            this.HH(ref num4, num, num2, num3, this.x[9], 9);
            this.HH(ref num3, num4, num, num2, this.x[5], 11);
            this.HH(ref num2, num3, num4, num, this.x[13], 15);
            this.HH(ref num, num2, num3, num4, this.x[3], 3);
            this.HH(ref num4, num, num2, num3, this.x[11], 9);
            this.HH(ref num3, num4, num, num2, this.x[7], 11);
            this.HH(ref num2, num3, num4, num, this.x[15], 15);
            state[0] += num;
            state[1] += num2;
            state[2] += num3;
            state[3] += num4;
        }
References Mono.Security.Cryptography.MD4Managed.Decode(), Mono.Security.Cryptography.MD4Managed.FF(), Mono.Security.Cryptography.MD4Managed.GG(), Mono.Security.Cryptography.MD4Managed.HH(), System.index, Mono.Security.Cryptography.MD4Managed.state, and Mono.Security.Cryptography.MD4Managed.x.
Referenced by Mono.Security.Cryptography.MD4Managed.HashCore().