Terraria Decompiled: Mono.Security.Cryptography.MD4Managed.HashFinal
HashFinal()
override byte[] Mono.Security.Cryptography.MD4Managed.HashFinal () inline protected
Definition at line 60 of file MD4Managed.cs.
        {
            byte[] array = new byte[8];
            this.Encode(array, this.count);
            uint num = (this.count[0] >> 3) & 63U;
            int num2 = (int)((num < 56U) ? (56U - num) : (120U - num));
            this.HashCore(this.Padding(num2), 0, num2);
            this.HashCore(array, 0, 8);
            this.Encode(this.digest, this.state);
            this.Initialize();
            return this.digest;
        }
References System.array, Mono.Security.Cryptography.MD4Managed.count, Mono.Security.Cryptography.MD4Managed.digest, Mono.Security.Cryptography.MD4Managed.Encode(), Mono.Security.Cryptography.MD4Managed.HashCore(), Mono.Security.Cryptography.MD4Managed.Initialize(), int, Mono.Security.Cryptography.MD4Managed.Padding(), Mono.Security.Cryptography.MD4Managed.state, and System.U.