Terraria Decompiled: rail.IRailUtilsImpl.GetLaunchAppParameters
GetLaunchAppParameters()
virtual RailResult rail.IRailUtilsImpl.GetLaunchAppParameters (EnumRailLaunchAppType app_type, out string parameter) inline virtual
Implements rail.IRailUtils.
Definition at line 85 of file IRailUtilsImpl.cs.
        {
            IntPtr intPtr = RAIL_API_PINVOKE.new_RailString__SWIG_0();
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailUtils_GetLaunchAppParameters(this.swigCPtr_, (int)app_type, intPtr);
            }
            finally
            {
                parameter = RAIL_API_PINVOKE.RailString_c_str(intPtr);
                RAIL_API_PINVOKE.delete_RailString(intPtr);
            }
            return railResult;
        }
References rail.RAIL_API_PINVOKE.delete_RailString(), rail.RAIL_API_PINVOKE.IRailUtils_GetLaunchAppParameters(), rail.RAIL_API_PINVOKE.new_RailString__SWIG_0(), and rail.RAIL_API_PINVOKE.RailString_c_str().