Terraria Decompiled: System.Threading.Tasks.StandardTaskContinuation.Run
Run()
override void System.Threading.Tasks.StandardTaskContinuation.Run (Task completedTask, bool bCanInlineContinuationTask) inline package
Definition at line 26 of file StandardTaskContinuation.cs.
        {
            TaskContinuationOptions options = this.m_options;
            bool flag = (completedTask.IsCompletedSuccessfully ? ((options & TaskContinuationOptions.NotOnRanToCompletion) == TaskContinuationOptions.None) : (completedTask.IsCanceled ? ((options & TaskContinuationOptions.NotOnCanceled) == TaskContinuationOptions.None) : ((options & TaskContinuationOptions.NotOnFaulted) == TaskContinuationOptions.None)));
            Task task = this.m_task;
            if (flag)
            {
                if (!task.IsCanceled && DebuggerSupport.LoggingOn)
                {
                    DebuggerSupport.TraceOperationRelation(CausalityTraceLevel.Important, task, CausalityRelation.AssignDelegate);
                }
                task.m_taskScheduler = this.m_taskScheduler;
                if (bCanInlineContinuationTask && (options & TaskContinuationOptions.ExecuteSynchronously) != TaskContinuationOptions.None)
                {
                    TaskContinuation.InlineIfPossibleOrElseQueue(task, true);
                    return;
                }
                try
                {
                    task.ScheduleAndStart(true);
                    return;
                }
                catch (TaskSchedulerException)
                {
                    return;
                }
            }
            task.InternalCancel(false);
        }
References System.Threading.Tasks.TaskContinuation.InlineIfPossibleOrElseQueue(), System.Threading.Tasks.DebuggerSupport.LoggingOn, System.Threading.Tasks.StandardTaskContinuation.m_options, System.Threading.Tasks.StandardTaskContinuation.m_task, System.Threading.Tasks.StandardTaskContinuation.m_taskScheduler, System.options, System.task, and System.Threading.Tasks.DebuggerSupport.TraceOperationRelation().
Referenced by System.Threading.Tasks.Task< TResult >.FinishContinuations().