Terraria Decompiled: System.Globalization.IdnMapping.ToUnicode
ToUnicode()
string System.Globalization.IdnMapping.ToUnicode (string s, int offset) inline private
Definition at line 319 of file IdnMapping.cs.
        {
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] >= '\u0080')
                {
                    s = this.NamePrep(s, offset);
                    break;
                }
            }
            if (!s.StartsWith("xn--", StringComparison.OrdinalIgnoreCase))
            {
                return s;
            }
            s = s.ToLower(CultureInfo.InvariantCulture);
            string text = s;
            s = s.Substring(4);
            s = this.puny.Decode(s, offset);
            string text2 = s;
            s = this.ToAscii(s, offset);
            if (string.Compare(text, s, StringComparison.OrdinalIgnoreCase) != 0)
            {
                throw new ArgumentException(string.Format("ToUnicode() failed at verifying the result, at label part from {0}", offset));
            }
            return text2;
        }
References System.Globalization.Bootstring.Decode(), System.Globalization.Format, System.Globalization.CultureInfo.InvariantCulture, System.Globalization.IdnMapping.NamePrep(), System.offset, System.Globalization.IdnMapping.puny, System.s, System.text, and System.Globalization.IdnMapping.ToAscii().
Referenced by System.Globalization.IdnMapping.Convert().