Terraria Decompiled: System.Globalization.IdnMapping.ToAscii
ToAscii()
string System.Globalization.IdnMapping.ToAscii (string s, int offset) inline private
Definition at line 128 of file IdnMapping.cs.
        {
            for (int i = 0; i < s.Length; i++)
            {
                if (s[i] < ' ' || s[i] == '\u007f')
                {
                    throw new ArgumentException(string.Format("Not allowed character was found, at {0}", offset + i));
                }
                if (s[i] >= '\u0080')
                {
                    s = this.NamePrep(s, offset);
                    break;
                }
            }
            if (this.use_std3)
            {
                this.VerifyStd3AsciiRules(s, offset);
            }
            int j = 0;
            while (j < s.Length)
            {
                if (s[j] >= '\u0080')
                {
                    if (s.StartsWith("xn--", StringComparison.OrdinalIgnoreCase))
                    {
                        throw new ArgumentException(string.Format("The input string must not start with ACE (xn--), at {0}", offset + j));
                    }
                    s = this.puny.Encode(s, offset);
                    s = "xn--" + s;
                    break;
                }
                else
                {
                    j++;
                }
            }
            this.VerifyLength(s, offset);
            return s;
        }
References System.Globalization.Bootstring.Encode(), System.Globalization.Format, System.Globalization.IdnMapping.NamePrep(), System.offset, System.Globalization.IdnMapping.puny, System.s, System.Globalization.IdnMapping.use_std3, System.Globalization.IdnMapping.VerifyLength(), and System.Globalization.IdnMapping.VerifyStd3AsciiRules().
Referenced by System.Globalization.IdnMapping.Convert(), and System.Globalization.IdnMapping.ToUnicode().