Terraria Decompiled: Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryBinaryOperation
TryBinaryOperation()
override bool Newtonsoft.Json.Linq.JValue.JValueDynamicProxy.TryBinaryOperation (JValue instance, BinaryOperationBinder binder, object arg, out object result) inline
Definition at line 1065 of file JValue.cs.
            {
                JValue jvalue = arg as JValue;
                object obj = ((jvalue != null) ? jvalue.Value : arg);
                ExpressionType operation = binder.Operation;
                if (operation <= 35)
                {
                    if (operation <= 21)
                    {
                        if (operation != null)
{
                            switch (operation)
{
                            case 12:
                                break;
                            case 13:
                                result = JValue.Compare(instance.Type, instance.Value, obj) == 0;
                                return true;
                            case 14:
                            case 17:
                            case 18:
                            case 19:
                                goto IL_018D;
                            case 15:
                                result = JValue.Compare(instance.Type, instance.Value, obj) > 0;
                                return true;
                            case 16:
                                result = JValue.Compare(instance.Type, instance.Value, obj) >= 0;
                                return true;
                            case 20:
                                result = JValue.Compare(instance.Type, instance.Value, obj) < 0;
                                return true;
                            case 21:
                                result = JValue.Compare(instance.Type, instance.Value, obj) <= 0;
                                return true;
                            default:
                                goto IL_018D;
                            }
                        }
                    }
                    else if (operation != 26)
                    {
                        if (operation != 35)
{
                            goto IL_018D;
                        }
                        result = JValue.Compare(instance.Type, instance.Value, obj) != 0;
                        return true;
                    }
                }
                else if (operation <= 63)
                {
                    if (operation != 42 && operation != 63)
                    {
                        goto IL_018D;
                    }
                }
                else if (operation != 65 && operation != 69 && operation != 73)
                {
                    goto IL_018D;
                }
                if (JValue.Operation(binder.Operation, instance.Value, obj, out result))
                {
                    result = new JValue(result);
                    return true;
                }
                IL_018D:
                result = null;
                return false;
            }
References Newtonsoft.Json.Linq.JValue.Compare(), Newtonsoft.Json.Linq.JValue.JValue(), System.obj, Newtonsoft.Json.Linq.JValue.Operation(), Newtonsoft.Json.Linq.JValue.Type, and Newtonsoft.Json.Linq.JValue.Value.