Terraria Decompiled: Terraria.EquipmentLoadout.Serialize
Serialize()
void Terraria.EquipmentLoadout.Serialize (BinaryWriter writer) inline
Definition at line 30 of file EquipmentLoadout.cs.
        {
            ItemSerializationContext itemSerializationContext = ItemSerializationContext.SavingAndLoading;
            for (int i = 0; i < this.Armor.Length; i++)
            {
                this.Armor[i].Serialize(writer, itemSerializationContext);
            }
            for (int j = 0; j < this.Dye.Length; j++)
            {
                this.Dye[j].Serialize(writer, itemSerializationContext);
            }
            for (int k = 0; k < this.Hide.Length; k++)
            {
                writer.Write(this.Hide[k]);
            }
        }
References Terraria.EquipmentLoadout.Armor, Terraria.EquipmentLoadout.Dye, Terraria.EquipmentLoadout.Hide, Terraria.Item.Serialize(), and System.IO.BinaryWriter.Write().
Referenced by Terraria.Player.Serialize().