Terraria Decompiled: rail.IRailStorageHelperImpl.OpenStreamFile
OpenStreamFile() [2/2]
virtual IRailStreamFile rail.IRailStorageHelperImpl.OpenStreamFile (string filename, RailStreamFileOption option, out RailResult result) inline virtual
Implements rail.IRailStorageHelper.
Definition at line 190 of file IRailStorageHelperImpl.cs.
        {
            IntPtr intPtr = ((option == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailStreamFileOption__SWIG_0());
            if (option != null)
            {
                RailConverter.Csharp2Cpp(option, intPtr);
            }
            IRailStreamFile railStreamFile;
            try
            {
                IntPtr intPtr2 = RAIL_API_PINVOKE.IRailStorageHelper_OpenStreamFile__SWIG_0(this.swigCPtr_, filename, intPtr, out result);
                railStreamFile = ((intPtr2 == IntPtr.Zero) ? null : new IRailStreamFileImpl(intPtr2));
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailStreamFileOption(intPtr);
            }
            return railStreamFile;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailStreamFileOption(), rail.RAIL_API_PINVOKE.IRailStorageHelper_OpenStreamFile__SWIG_0(), rail.RAIL_API_PINVOKE.new_RailStreamFileOption__SWIG_0(), rail.RailObject.swigCPtr_, and System.IntPtr.Zero.