Terraria Decompiled: Newtonsoft.Json.JsonWriterException.Create
Create() [1/2]
static JsonWriterException Newtonsoft.Json.JsonWriterException.Create (JsonWriter writer, string message, Exception ex) inline static package
Definition at line 53 of file JsonWriterException.cs.
        {
            return JsonWriterException.Create(writer.ContainerPath, message, ex);
        }
References Newtonsoft.Json.JsonWriter.ContainerPath, and Newtonsoft.Json.JsonWriterException.Create().
Referenced by Newtonsoft.Json.Bson.BsonWriter.AddToken(), Newtonsoft.Json.JsonWriter.AutoComplete(), Newtonsoft.Json.JsonWriter.CalculateLevelsToComplete(), Newtonsoft.Json.JsonWriterException.Create(), Newtonsoft.Json.JsonWriter.CreateUnsupportedTypeException(), Newtonsoft.Json.JsonWriter.GetCloseTokenForType(), Newtonsoft.Json.JsonWriter.InternalWriteWhitespace(), Newtonsoft.Json.JsonWriter.UpdateCurrentState(), Newtonsoft.Json.Bson.BsonWriter.WriteComment(), Newtonsoft.Json.JsonWriter.WriteConstructorDate(), Newtonsoft.Json.JsonWriter.WriteEnd(), Newtonsoft.Json.JsonTextWriter.WriteEnd(), Newtonsoft.Json.Bson.BsonWriter.WriteObjectId(), Newtonsoft.Json.Bson.BsonWriter.WriteRaw(), Newtonsoft.Json.Bson.BsonWriter.WriteRawValue(), Newtonsoft.Json.Bson.BsonWriter.WriteStartConstructor(), Newtonsoft.Json.Bson.BsonWriter.WriteValue(), and Newtonsoft.Json.Bson.BsonWriter.WriteValue().