Terraria Decompiled: Terraria.WorldBuilding.WorldUtils.Gen
Gen() [1/2]
static bool Terraria.WorldBuilding.WorldUtils.Gen (Point origin, GenShape shape, GenAction action) inline static
Definition at line 40 of file WorldUtils.cs.
        {
            return shape.Perform(origin, action);
        }
References System.action, and Terraria.WorldBuilding.GenShape.Perform().
Referenced by Terraria.WorldGen.AddPasses(), Terraria.GameContent.Biomes.CaveHouse.DesertHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.GraniteHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.IceHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.JungleHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.MarbleHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.MushroomHouseBuilder.AgeRoom(), Terraria.GameContent.Biomes.CaveHouse.WoodHouseBuilder.AgeRoom(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LegacyDungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.WormlikeDungeonRoom.FloodRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenerateEarlyDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateShimmerPool(), Terraria.GameContent.Generation.Dungeon.Rooms.GenShapeDungeonRoom.GenShapeRoom(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetHouseType(), Terraria.GameContent.Biomes.CaveHouse.HouseUtils.GetRoomSolidPrecentage(), Terraria.WorldGen.initializeHardMode(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PaintSeedHouses(), Terraria.GameContent.Biomes.CampsiteBiome.Place(), Terraria.GameContent.Biomes.EnchantedSwordBiome.Place(), Terraria.GameContent.Biomes.HiveBiome.Place(), Terraria.GameContent.Biomes.HoneyPatchBiome.Place(), Terraria.GameContent.Biomes.MahoganyTreeBiome.Place(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.GameContent.Biomes.ThinIceBiome.Place(), Terraria.GameContent.Biomes.Desert.ChambersEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.AnthillEntrance.PlaceAt(), Terraria.GameContent.Biomes.Desert.LarvaHoleEntrance.PlaceAt(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceDoors(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceEmptyRooms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlacePlatforms(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceStairs(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams(), Terraria.Player.PlaceThing_Tiles_PlaceIt_StaffOfRegrowthCheck(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.RainbowifyOnTenthAnniversaryWorlds(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance().