Terraria Decompiled: Mono.Security.Cryptography.MD2Managed.HashFinal
HashFinal()
override byte[] Mono.Security.Cryptography.MD2Managed.HashFinal () inline protected
Definition at line 70 of file MD2Managed.cs.
        {
            int num = this.count;
            int num2 = 16 - num;
            if (num2 > 0)
            {
                this.HashCore(this.Padding(num2), 0, num2);
            }
            this.HashCore(this.checksum, 0, 16);
            byte[] array = (byte[])this.state.Clone();
            this.Initialize();
            return array;
        }
References System.array, Mono.Security.Cryptography.MD2Managed.checksum, Mono.Security.Cryptography.MD2Managed.count, Mono.Security.Cryptography.MD2Managed.HashCore(), Mono.Security.Cryptography.MD2Managed.Initialize(), Mono.Security.Cryptography.MD2Managed.Padding(), and Mono.Security.Cryptography.MD2Managed.state.