Terraria Decompiled: Mono.Security.Cryptography.MD2Managed.HashCore
HashCore()
override void Mono.Security.Cryptography.MD2Managed.HashCore (byte[] array, int ibStart, int cbSize) inline protected
Definition at line 44 of file MD2Managed.cs.
        {
            int num = this.count;
            this.count = (num + cbSize) & 15;
            int num2 = 16 - num;
            int num3;
            if (cbSize >= num2)
            {
                Buffer.BlockCopy(array, ibStart, this.buffer, num, num2);
                this.MD2Transform(this.state, this.checksum, this.buffer, 0);
                num3 = num2;
                while (num3 + 15 < cbSize)
                {
                    this.MD2Transform(this.state, this.checksum, array, ibStart + num3);
                    num3 += 16;
                }
                num = 0;
            }
            else
            {
                num3 = 0;
            }
            Buffer.BlockCopy(array, ibStart + num3, this.buffer, num, cbSize - num3);
        }
References System.array, System.Buffer.BlockCopy(), Mono.Security.Cryptography.MD2Managed.buffer, Mono.Security.Cryptography.MD2Managed.checksum, Mono.Security.Cryptography.MD2Managed.count, Mono.Security.Cryptography.MD2Managed.MD2Transform(), and Mono.Security.Cryptography.MD2Managed.state.
Referenced by Mono.Security.Cryptography.MD2Managed.HashFinal().