Terraria Decompiled: Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose
Dispose()
override void Microsoft.Xna.Framework.Graphics.VertexBuffer.Dispose (bool disposing) inline protected virtual
Reimplemented from Microsoft.Xna.Framework.Graphics.GraphicsResource.
Definition at line 94 of file VertexBuffer.cs.
        {
            if (!base.IsDisposed)
            {
                IntPtr intPtr = Interlocked.Exchange(ref this.buffer, IntPtr.Zero);
                if (intPtr != IntPtr.Zero)
                {
                    FNA3D.FNA3D_AddDisposeVertexBuffer(base.GraphicsDevice.GLDevice, intPtr);
                }
            }
            base.Dispose(disposing);
        }
References Microsoft.Xna.Framework.Graphics.VertexBuffer.buffer, System.Threading.Interlocked.Exchange(), Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_AddDisposeVertexBuffer(), and System.IntPtr.Zero.
Referenced by Terraria.DataStructures.SpriteDrawBuffer.CheckBuffers(), Terraria.Graphics.TileBatch.Dispose(), Microsoft.Xna.Framework.Graphics.SpriteBatch.Dispose(), and Microsoft.Xna.Framework.Media.BaseYUVPlayer.GL_dispose().