Terraria Decompiled: Microsoft.Xna.Framework.Graphics.GraphicsAdapter.AdaptersChanged
AdaptersChanged()
static void Microsoft.Xna.Framework.Graphics.GraphicsAdapter.AdaptersChanged () inline static package
Definition at line 241 of file GraphicsAdapter.cs.
        {
            GraphicsAdapter.adapters = new ReadOnlyCollection<GraphicsAdapter>(FNAPlatform.GetGraphicsAdapters());
        }
References Microsoft.Xna.Framework.FNAPlatform.GetGraphicsAdapters.
Referenced by Microsoft.Xna.Framework.SDL3_FNAPlatform.FetchDisplayAdapter(), Microsoft.Xna.Framework.SDL2_FNAPlatform.PollEvents(), and Microsoft.Xna.Framework.SDL3_FNAPlatform.PollEvents().