Terraria Decompiled: System.Security.Cryptography.FromBase64Transform.TransformFinalBlock
TransformFinalBlock()
byte[] System.Security.Cryptography.FromBase64Transform.TransformFinalBlock (byte[] inputBuffer, int inputOffset, int inputCount) inline
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 117 of file FromBase64Transform.cs.
        {
            if (inputBuffer == null)
            {
                throw new ArgumentNullException("inputBuffer");
            }
            if (inputOffset < 0)
            {
                throw new ArgumentOutOfRangeException("inputOffset", Environment.GetResourceString("Non-negative number required."));
            }
            if (inputCount < 0 || inputCount > inputBuffer.Length)
            {
                throw new ArgumentException(Environment.GetResourceString("Value was invalid."));
            }
            if (inputBuffer.Length - inputCount < inputOffset)
            {
                throw new ArgumentException(Environment.GetResourceString("Offset and length were out of bounds for the array or count is greater than the number of elements from index to the end of the source collection."));
            }
            if (this._inputBuffer == null)
            {
                throw new ObjectDisposedException(null, Environment.GetResourceString("Cannot access a disposed object."));
            }
            byte[] array = new byte[inputCount];
            int num;
            if (this._whitespaces == FromBase64TransformMode.IgnoreWhiteSpaces)
            {
                array = this.DiscardWhiteSpaces(inputBuffer, inputOffset, inputCount);
                num = array.Length;
            }
            else
            {
                Buffer.InternalBlockCopy(inputBuffer, inputOffset, array, 0, inputCount);
                num = inputCount;
            }
            if (num + this._inputIndex < 4)
            {
                this.Reset();
                return EmptyArray<byte>.Value;
            }
            int num2 = (num + this._inputIndex) / 4;
            byte[] array2 = new byte[this._inputIndex + num];
            Buffer.InternalBlockCopy(this._inputBuffer, 0, array2, 0, this._inputIndex);
            Buffer.InternalBlockCopy(array, 0, array2, this._inputIndex, num);
            this._inputIndex = (num + this._inputIndex) % 4;
            Buffer.InternalBlockCopy(array, num - this._inputIndex, this._inputBuffer, 0, this._inputIndex);
            byte[] array3 = Convert.FromBase64CharArray(Encoding.ASCII.GetChars(array2, 0, 4 * num2), 0, 4 * num2);
            this.Reset();
            return array3;
        }
References System.Security.Cryptography.FromBase64Transform._inputBuffer, System.Security.Cryptography.FromBase64Transform._inputIndex, System.Security.Cryptography.FromBase64Transform._whitespaces, System.array, System.Text.Encoding.ASCII, System.Security.Cryptography.FromBase64Transform.DiscardWhiteSpaces(), System.Convert.FromBase64CharArray(), System.Text.Encoding.GetChars(), System.Environment.GetResourceString(), System.Buffer.InternalBlockCopy(), System.Security.Cryptography.FromBase64Transform.Reset(), and System.EmptyArray< T >.Value.