Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffectInstance.SoundEffectInstance
SoundEffectInstance() [1/2]
Microsoft.Xna.Framework.Audio.SoundEffectInstance.SoundEffectInstance (SoundEffect parent = null) inline package
Definition at line 136 of file SoundEffectInstance.cs.
        {
            SoundEffect.Device();
            this.selfReference = new WeakReference(this, true);
            this.parentEffect = parent;
            this.isDynamic = this is DynamicSoundEffectInstance;
            this.hasStarted = false;
            this.is3D = false;
            this.usingReverb = false;
            this.INTERNAL_state = SoundState.Stopped;
            if (!this.isDynamic)
            {
                this.InitDSPSettings((uint)this.parentEffect.channels);
            }
            if (this.parentEffect != null)
            {
                this.parentEffect.Instances.Add(this.selfReference);
            }
        }
References System.Collections.Generic.List< T >.Add(), Microsoft.Xna.Framework.Audio.SoundEffect.channels, Microsoft.Xna.Framework.Audio.SoundEffect.Device(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.InitDSPSettings(), Microsoft.Xna.Framework.Audio.SoundEffect.Instances, Microsoft.Xna.Framework.Audio.SoundEffectInstance.isDynamic, Microsoft.Xna.Framework.Audio.SoundEffectInstance.parentEffect, and Microsoft.Xna.Framework.Audio.SoundEffectInstance.selfReference.