Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffectInstance.UpdatePitch
UpdatePitch()
void Microsoft.Xna.Framework.Audio.SoundEffectInstance.UpdatePitch () inline private
Definition at line 442 of file SoundEffectInstance.cs.
        {
            float dopplerScale = SoundEffect.Device().DopplerScale;
            float num;
            if (!this.is3D || dopplerScale == 0f)
            {
                num = 1f;
            }
            else
            {
                num = this.dspSettings.DopplerFactor * dopplerScale;
            }
            FAudio.FAudioSourceVoice_SetFrequencyRatio(this.handle, (float)Math.Pow(2.0, (double)this.INTERNAL_pitch) * num, 0U);
        }
References Microsoft.Xna.Framework.Audio.SoundEffect.Device(), Microsoft.Xna.Framework.Audio.SoundEffect.DopplerScale, FAudio.FAudioSourceVoice_SetFrequencyRatio(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.handle, Microsoft.Xna.Framework.Audio.SoundEffectInstance.is3D, System.Math.Pow(), and System.U.
Referenced by Microsoft.Xna.Framework.Audio.SoundEffectInstance.Apply3D(), and Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play().