Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffectInstance.InitDSPSettings
InitDSPSettings()
unsafe void Microsoft.Xna.Framework.Audio.SoundEffectInstance.InitDSPSettings (uint srcChannels) inline package
Definition at line 362 of file SoundEffectInstance.cs.
        {
            this.dspSettings = default(FAudio.F3DAUDIO_DSP_SETTINGS);
            this.dspSettings.DopplerFactor = 1f;
            this.dspSettings.SrcChannelCount = srcChannels;
            this.dspSettings.DstChannelCount = (uint)SoundEffect.Device().DeviceDetails.OutputFormat.Format.nChannels;
            int num = (int)(4U * this.dspSettings.SrcChannelCount * this.dspSettings.DstChannelCount);
            this.dspSettings.pMatrixCoefficients = FNAPlatform.Malloc(num);
            byte* ptr = (byte*)(void*)this.dspSettings.pMatrixCoefficients;
            for (int i = 0; i < num; i++)
            {
                ptr[i] = 0;
            }
            this.SetPanMatrixCoefficients();
        }
References Microsoft.Xna.Framework.Audio.SoundEffect.Device(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.dspSettings, int, Microsoft.Xna.Framework.FNAPlatform.Malloc, Microsoft.Xna.Framework.Audio.SoundEffectInstance.SetPanMatrixCoefficients(), and System.U.
Referenced by Microsoft.Xna.Framework.Audio.SoundEffectInstance.SoundEffectInstance().