Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffectInstance.Stop
Stop() [2/2]
void Microsoft.Xna.Framework.Audio.SoundEffectInstance.Stop (bool immediate) inline
Definition at line 309 of file SoundEffectInstance.cs.
        {
            if (this.handle == IntPtr.Zero)
            {
                return;
            }
            if (immediate)
            {
                FAudio.FAudioSourceVoice_Stop(this.handle, 0U, 0U);
                FAudio.FAudioSourceVoice_FlushSourceBuffers(this.handle);
                FAudio.FAudioVoice_DestroyVoice(this.handle);
                FAudio.FAudio_Release(SoundEffect.Device().Handle);
                this.handle = IntPtr.Zero;
                this.usingReverb = false;
                this.INTERNAL_state = SoundState.Stopped;
                if (this.isDynamic)
                {
                    List<DynamicSoundEffectInstance> streams = FrameworkDispatcher.Streams;
                    lock (streams)
                    {
                        FrameworkDispatcher.Streams.Remove(this as DynamicSoundEffectInstance);
                    }
                    (this as DynamicSoundEffectInstance).ClearBuffers();
                    return;
                }
            }
            else
            {
                if (this.isDynamic)
                {
                    throw new InvalidOperationException();
                }
                FAudio.FAudioSourceVoice_ExitLoop(this.handle, 0U);
            }
        }
References Microsoft.Xna.Framework.Audio.SoundEffect.Device(), FAudio.FAudio_Release(), FAudio.FAudioSourceVoice_ExitLoop(), FAudio.FAudioSourceVoice_FlushSourceBuffers(), FAudio.FAudioSourceVoice_Stop(), FAudio.FAudioVoice_DestroyVoice(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.handle, Microsoft.Xna.Framework.Audio.SoundEffectInstance.isDynamic, System.Collections.Generic.List< T >.Remove(), Microsoft.Xna.Framework.FrameworkDispatcher.Streams, System.U, and System.IntPtr.Zero.