Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play
Play()
virtual void Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play () inline virtual
Reimplemented in Microsoft.Xna.Framework.Audio.DynamicSoundEffectInstance.
Definition at line 219 of file SoundEffectInstance.cs.
        {
            if (this.State == SoundState.Playing)
            {
                return;
            }
            if (this.State == SoundState.Paused)
            {
                FAudio.FAudioSourceVoice_Start(this.handle, 0U, 0U);
                this.INTERNAL_state = SoundState.Playing;
                return;
            }
            SoundEffect.FAudioContext faudioContext = SoundEffect.Device();
            if (this.isDynamic)
            {
                FAudio.FAudio_CreateSourceVoice(faudioContext.Handle, out this.handle, ref (this as DynamicSoundEffectInstance).format, 8U, SoundEffectInstance.maxFreqRatio, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
            }
            else
            {
                FAudio.FAudio_CreateSourceVoice(faudioContext.Handle, out this.handle, this.parentEffect.formatPtr, 8U, SoundEffectInstance.maxFreqRatio, IntPtr.Zero, IntPtr.Zero, IntPtr.Zero);
            }
            if (this.handle == IntPtr.Zero)
            {
                return;
            }
            FAudio.FAudio_AddRef(faudioContext.Handle);
            FAudio.FAudioVoice_SetVolume(this.handle, this.INTERNAL_volume, 0U);
            this.UpdatePitch();
            if (this.is3D || this.Pan != 0f)
            {
                FAudio.FAudioVoice_SetOutputMatrix(this.handle, SoundEffect.Device().MasterVoice, this.dspSettings.SrcChannelCount, this.dspSettings.DstChannelCount, this.dspSettings.pMatrixCoefficients, 0U);
            }
            if (this.isDynamic)
            {
                (this as DynamicSoundEffectInstance).QueueInitialBuffers();
            }
            else
            {
                if (this.IsLooped)
                {
                    this.parentEffect.handle.LoopCount = 255U;
                    this.parentEffect.handle.LoopBegin = this.parentEffect.loopStart;
                    this.parentEffect.handle.LoopLength = this.parentEffect.loopLength;
                }
                else
                {
                    this.parentEffect.handle.LoopCount = 0U;
                    this.parentEffect.handle.LoopBegin = 0U;
                    this.parentEffect.handle.LoopLength = 0U;
                }
                FAudio.FAudioSourceVoice_SubmitSourceBuffer(this.handle, ref this.parentEffect.handle, IntPtr.Zero);
            }
            FAudio.FAudioSourceVoice_Start(this.handle, 0U, 0U);
            this.INTERNAL_state = SoundState.Playing;
            this.hasStarted = true;
        }
References Microsoft.Xna.Framework.Audio.SoundEffect.Device(), FAudio.FAudio_AddRef(), FAudio.FAudio_CreateSourceVoice(), FAudio.FAudioSourceVoice_Start(), FAudio.FAudioSourceVoice_SubmitSourceBuffer(), FAudio.FAudioVoice_SetOutputMatrix(), FAudio.FAudioVoice_SetVolume(), System.format, Microsoft.Xna.Framework.Audio.SoundEffect.handle, Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.Handle, Microsoft.Xna.Framework.Audio.SoundEffectInstance.handle, Microsoft.Xna.Framework.Audio.SoundEffectInstance.INTERNAL_volume, Microsoft.Xna.Framework.Audio.SoundEffectInstance.is3D, Microsoft.Xna.Framework.Audio.SoundEffectInstance.isDynamic, Microsoft.Xna.Framework.Audio.SoundEffectInstance.IsLooped, Microsoft.Xna.Framework.Audio.SoundEffect.loopLength, Microsoft.Xna.Framework.Audio.SoundEffect.loopStart, Microsoft.Xna.Framework.Audio.SoundEffectInstance.maxFreqRatio, Microsoft.Xna.Framework.Audio.SoundEffectInstance.Pan, Microsoft.Xna.Framework.Audio.SoundEffectInstance.parentEffect, Microsoft.Xna.Framework.Audio.SoundEffectInstance.State, System.U, Microsoft.Xna.Framework.Audio.SoundEffectInstance.UpdatePitch(), and System.IntPtr.Zero.
Referenced by Terraria.Audio.ActiveSound.Play(), Microsoft.Xna.Framework.Audio.SoundEffect.Play(), Terraria.Audio.ActiveSound.PlayLooped(), Terraria.Audio.LegacySoundPlayer.PlaySound(), and Microsoft.Xna.Framework.Audio.SoundEffectInstance.Resume().