Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffectInstance.Resume
Resume()
void Microsoft.Xna.Framework.Audio.SoundEffectInstance.Resume () inline
Definition at line 287 of file SoundEffectInstance.cs.
        {
            SoundState state = this.State;
            if (this.handle == IntPtr.Zero)
            {
                this.Play();
                return;
            }
            if (state == SoundState.Paused)
            {
                FAudio.FAudioSourceVoice_Start(this.handle, 0U, 0U);
                this.INTERNAL_state = SoundState.Playing;
            }
        }
References FAudio.FAudioSourceVoice_Start(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.handle, Microsoft.Xna.Framework.Audio.SoundEffectInstance.Play(), Microsoft.Xna.Framework.Audio.SoundEffectInstance.State, System.state, System.U, and System.IntPtr.Zero.
Referenced by Microsoft.Xna.Framework.Media.VideoPlayerTheora.Resume(), Terraria.Audio.ActiveSound.Resume(), and Terraria.Audio.ASoundEffectBasedAudioTrack.Resume().