Terraria Decompiled: Terraria.Testing.QuickLoad.JoinWorld.RestoreWindowBounds
RestoreWindowBounds()
void Terraria.Testing.QuickLoad.JoinWorld.RestoreWindowBounds () inline private
Definition at line 261 of file QuickLoad.cs.
            {
                if (this.WindowedBounds == null)
                {
                    return;
                }
                Rectangle value = this.WindowedBounds.Value;
                if (Platform.Get<IWindowService>().IsSizeable(Main.instance.Window))
                {
                    Main.SetResolution(value.Width, value.Height);
                    Platform.Get<IWindowService>().SetPosition(Main.instance.Window, value.X, value.Y);
                }
            }
References Terraria.Main.instance, ReLogic.OS.IWindowService.IsSizeable(), Terraria.Main.SetResolution(), System.value, Microsoft.Xna.Framework.Game.Window, and Terraria.Testing.QuickLoad.JoinWorld.WindowedBounds.
Referenced by Terraria.Testing.QuickLoad.JoinWorld.Start().