Terraria Decompiled: Terraria.Testing.QuickLoad.JoinWorld.SelectPlayerAndWorld
SelectPlayerAndWorld()
void Terraria.Testing.QuickLoad.JoinWorld.SelectPlayerAndWorld () inline protected
Definition at line 294 of file QuickLoad.cs.
            {
                Main.LoadPlayers();
                Main.SelectPlayer(Main.PlayerList.Single((PlayerFileData p) => p.Path == this.PlayerPath));
                if (!string.IsNullOrEmpty(this.WorldPath))
                {
                    Main.WorldList.Single((WorldFileData w) => w.Path == this.WorldPath).SetAsActive();
                }
            }
References Terraria.Main.LoadPlayers(), Terraria.IO.FileData.Path, Terraria.Main.PlayerList, Terraria.Main.SelectPlayer(), Terraria.Main.WorldList, and Terraria.Testing.QuickLoad.JoinWorld.WorldPath.
Referenced by Terraria.Testing.QuickLoad.JoinWorld.Start().