Terraria Decompiled: Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad
OnWorldLoad()
void Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad () inline private
Definition at line 327 of file QuickLoad.cs.
            {
                WorldGen.Hooks.OnWorldLoad -= this.OnWorldLoad;
                if (Main.ActiveWorldFileData.Path != this.WorldPath || Main.ActivePlayerFileData.Path != this.PlayerPath || (this.ServerIPText != null && Main.netMode != 1) || (Main.netMode == 1 && this.ServerIPText != Netplay.ServerIPText))
                {
                    return;
                }
                if (this.PlayerPosition != Vector2.Zero)
                {
                    Main.LocalPlayer.position = this.PlayerPosition;
                }
                if (this.MountType != 0)
                {
                    Main.LocalPlayer.mount.SetMount(this.MountType, Main.LocalPlayer);
                }
                DebugUtils.QuickSPMessage("/onquickload");
            }
References Terraria.Main.ActivePlayerFileData, Terraria.Main.ActiveWorldFileData, Terraria.Main.LocalPlayer, Terraria.Player.mount, Terraria.Testing.QuickLoad.JoinWorld.MountType, Terraria.Main.netMode, Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad(), Terraria.IO.FileData.Path, Terraria.Testing.QuickLoad.JoinWorld.PlayerPosition, Terraria.Testing.DebugUtils.QuickSPMessage(), Terraria.Netplay.ServerIPText, Terraria.Mount.SetMount(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad(), and Terraria.Testing.QuickLoad.JoinWorld.PlayWorldOrJoinServer().