Terraria Decompiled: Terraria.Testing.QuickLoad.JoinWorld.Start
Start()
override void Terraria.Testing.QuickLoad.JoinWorld.Start () inline protected
Definition at line 242 of file QuickLoad.cs.
            {
                string text;
                int num;
                if (Program.LaunchParameters.TryGetValue("-quickloadclient", out text) && int.TryParse(text, out num) && num < this.ExtraClients.Count)
                {
                    this.ExtraClients[num].Start();
                    return;
                }
                if (this.ExtraClients != null)
                {
                    this.LaunchExtraClients();
                }
                this.RestoreWindowBounds();
                this.SelectPlayerAndWorld();
                this.PlayWorldOrJoinServer();
            }
References Terraria.Testing.QuickLoad.JoinWorld.ExtraClients, Terraria.Testing.QuickLoad.JoinWorld.LaunchExtraClients(), Terraria.Program.LaunchParameters, Terraria.Testing.QuickLoad.JoinWorld.PlayWorldOrJoinServer(), Terraria.Testing.QuickLoad.JoinWorld.RestoreWindowBounds(), Terraria.Testing.QuickLoad.JoinWorld.SelectPlayerAndWorld(), System.text, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().