Terraria Decompiled: System.Reflection.Emit.GenericInstanceKey.TypeEquals
TypeEquals()
static bool System.Reflection.Emit.GenericInstanceKey.TypeEquals (Type a, Type b) inline static private
Definition at line 32 of file GenericInstanceKey.cs.
        {
            if (a == b)
            {
                return true;
            }
            if (!a.HasElementType)
            {
                if (a.IsGenericType)
                {
                    if (!b.IsGenericType)
                    {
                        return false;
                    }
                    if (a.IsGenericParameter)
                    {
                        return a == b;
                    }
                    if (a.IsGenericParameter)
                    {
                        return false;
                    }
                    if (a.IsGenericTypeDefinition)
                    {
                        if (!b.IsGenericTypeDefinition)
{
                            return false;
                        }
                    }
                    else
                    {
                        if (b.IsGenericTypeDefinition)
{
                            return false;
                        }
                        if (!GenericInstanceKey.TypeEquals(a.GetGenericTypeDefinition(), b.GetGenericTypeDefinition()))
{
                            return false;
                        }
                        Type[] genericArguments = a.GetGenericArguments();
                        Type[] genericArguments2 = b.GetGenericArguments();
                        for (int i = 0; i < genericArguments.Length; i++)
{
                            if (!GenericInstanceKey.TypeEquals(genericArguments[i], genericArguments2[i]))
{
                                return false;
                            }
                        }
                    }
                }
                return a == b;
            }
            if (!b.HasElementType)
            {
                return false;
            }
            if (!GenericInstanceKey.TypeEquals(a.GetElementType(), b.GetElementType()))
            {
                return false;
            }
            if (a.IsArray)
            {
                if (!b.IsArray)
                {
                    return false;
                }
                int arrayRank = a.GetArrayRank();
                if (arrayRank != b.GetArrayRank())
                {
                    return false;
                }
                if (arrayRank == 1 && GenericInstanceKey.IsBoundedVector(a) != GenericInstanceKey.IsBoundedVector(b))
                {
                    return false;
                }
            }
            else if (a.IsByRef)
            {
                if (!b.IsByRef)
                {
                    return false;
                }
            }
            else if (a.IsPointer && !b.IsPointer)
            {
                return false;
            }
            return true;
        }
References System.Type.GetArrayRank(), System.Type.GetElementType(), System.Type.GetGenericArguments(), System.Type.GetGenericTypeDefinition(), System.Type.HasElementType, System.Type.IsArray, System.Reflection.Emit.GenericInstanceKey.IsBoundedVector(), System.Type.IsByRef, System.Type.IsGenericParameter, System.Type.IsGenericType, System.Type.IsGenericTypeDefinition, System.Type.IsPointer, and System.Reflection.Emit.GenericInstanceKey.TypeEquals().
Referenced by System.Reflection.Emit.GenericInstanceKey.TypeEquals().