Terraria Decompiled: Terraria.Testing.QuickLoad.JoinWorld.PlayWorldOrJoinServer
PlayWorldOrJoinServer()
void Terraria.Testing.QuickLoad.JoinWorld.PlayWorldOrJoinServer () inline protected
Definition at line 305 of file QuickLoad.cs.
            {
                WorldGen.Hooks.OnWorldLoad += this.OnWorldLoad;
                Main.menuMode = 10;
                if (this.ServerIPText == null)
                {
                    WorldGen.playWorld();
                    return;
                }
                Netplay.ServerPassword = this.ServerPassword;
                if (this.IsHostAndPlay)
                {
                    Main.HostAndPlay();
                    return;
                }
                Main.autoPass = true;
                Netplay.SetRemoteIP(this.ServerIPText);
                Netplay.StartTcpClient();
                Main.statusText = Language.GetTextValue("Net.ConnectingTo", this.ServerIPText);
            }
References Terraria.Localization.Language.GetTextValue(), Terraria.Main.HostAndPlay(), Terraria.Testing.QuickLoad.JoinWorld.IsHostAndPlay, Terraria.Testing.QuickLoad.JoinWorld.OnWorldLoad(), Terraria.WorldGen.playWorld(), Terraria.Testing.QuickLoad.JoinWorld.ServerIPText, Terraria.Testing.QuickLoad.JoinWorld.ServerPassword, Terraria.Netplay.SetRemoteIP(), and Terraria.Netplay.StartTcpClient().
Referenced by Terraria.Testing.QuickLoad.JoinWorld.Start().