Terraria Decompiled: Terraria.Testing.QuickLoad.JoinWorld.WithCurrentState
WithCurrentState()
virtual QuickLoad.JoinWorld Terraria.Testing.QuickLoad.JoinWorld.WithCurrentState () inline virtual
Definition at line 346 of file QuickLoad.cs.
            {
                this.SaveWindowBounds();
                Main.SaveSettings();
                if (!Main.gameMenu)
                {
                    Player.SavePlayer(Main.ActivePlayerFileData, false);
                }
                if (Main.WorldFileMetadata == null)
                {
                    Main.WorldFileMetadata = FileMetadata.FromCurrentSettings(FileType.World);
                }
                if (Main.netMode != 1)
                {
                    WorldFile.SaveWorld(false, false, false);
                }
                this.PlayerPath = Main.ActivePlayerFileData.Path;
                this.WorldPath = Main.ActiveWorldFileData.Path;
                if (Main.netMode == 1)
                {
                    this.ServerIPText = Netplay.ServerIPText;
                    this.ServerPassword = Netplay.ServerPassword;
                    this.IsHostAndPlay = Netplay.IsHostAndPlay;
                    if (this.IsHostAndPlay)
                    {
                        NetMessage.SendData(94, -1, -1, NetworkText.FromLiteral("/quickload-clientprobe"), 0, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
                if (!Main.gameMenu)
                {
                    this.PlayerPosition = Main.LocalPlayer.position;
                    this.MountType = Main.LocalPlayer.mount.Type;
                }
                this.InDebugRegenUI = UIWorldGenDebug.ActiveInstance != null;
                if (this.InDebugRegenUI)
                {
                    if (UIWorldGenDebug.CurrentTargetOrLatestPass != null)
                    {
                        this.RegenTargetPassName = UIWorldGenDebug.CurrentTargetOrLatestPass.Name;
                    }
                    this.RegenSnapshotFrequency = WorldGenerator.CurrentController.SnapshotFrequency;
                    this.RegenPauseOnHashMismatch = WorldGenerator.CurrentController.PauseOnHashMismatch;
                }
                return this;
            }
References Terraria.Main.ActivePlayerFileData, Terraria.Main.ActiveWorldFileData, Terraria.WorldBuilding.WorldGenerator.CurrentController, Terraria.GameContent.UI.States.UIWorldGenDebug.CurrentTargetOrLatestPass, Terraria.IO.FileMetadata.FromCurrentSettings(), Terraria.Localization.NetworkText.FromLiteral(), Terraria.Main.gameMenu, Terraria.Testing.QuickLoad.JoinWorld.InDebugRegenUI, Terraria.Netplay.IsHostAndPlay, Terraria.Testing.QuickLoad.JoinWorld.IsHostAndPlay, Terraria.Main.LocalPlayer, Terraria.Player.mount, Terraria.WorldBuilding.GenPass.Name, Terraria.Main.netMode, Terraria.IO.FileData.Path, Terraria.Entity.position, Terraria.Player.SavePlayer(), Terraria.Main.SaveSettings(), Terraria.Testing.QuickLoad.JoinWorld.SaveWindowBounds(), Terraria.IO.WorldFile.SaveWorld(), Terraria.NetMessage.SendData(), Terraria.Netplay.ServerIPText, Terraria.Netplay.ServerPassword, Terraria.Mount.Type, and Terraria.Main.WorldFileMetadata.
Referenced by Terraria.Testing.ChatCommands.ToolkitDebugCommands.QuickLoadRegenCommand(), and Terraria.Testing.ChatCommands.ToolkitDebugCommands.QuickLoadRejoinCommand().