Terraria Decompiled: Terraria.GameContent.ItemDropRules.ItemDropResolver.ResolveRule
ResolveRule()
ItemDropAttemptResult Terraria.GameContent.ItemDropRules.ItemDropResolver.ResolveRule (IItemDropRule rule, DropAttemptInfo info) inline private
Definition at line 26 of file ItemDropResolver.cs.
        {
            if (!rule.CanDrop(info))
            {
                ItemDropAttemptResult itemDropAttemptResult = new ItemDropAttemptResult
                {
                    State = ItemDropAttemptResultState.DoesntFillConditions
                };
                this.ResolveRuleChains(rule, info, itemDropAttemptResult);
                return itemDropAttemptResult;
            }
            INestedItemDropRule nestedItemDropRule = rule as INestedItemDropRule;
            ItemDropAttemptResult itemDropAttemptResult2;
            if (nestedItemDropRule != null)
            {
                itemDropAttemptResult2 = nestedItemDropRule.TryDroppingItem(info, new ItemDropRuleResolveAction(this.ResolveRule));
            }
            else
            {
                itemDropAttemptResult2 = rule.TryDroppingItem(info);
            }
            this.ResolveRuleChains(rule, info, itemDropAttemptResult2);
            return itemDropAttemptResult2;
        }
References Terraria.GameContent.ItemDropRules.IItemDropRule.CanDrop(), System.info, Terraria.GameContent.ItemDropRules.ItemDropRuleResolveAction(), Terraria.GameContent.ItemDropRules.ItemDropResolver.ResolveRule(), Terraria.GameContent.ItemDropRules.ItemDropResolver.ResolveRuleChains(), Terraria.GameContent.ItemDropRules.IItemDropRule.TryDroppingItem(), and Terraria.GameContent.ItemDropRules.INestedItemDropRule.TryDroppingItem().
Referenced by Terraria.GameContent.ItemDropRules.ItemDropResolver.ResolveRule(), Terraria.GameContent.ItemDropRules.ItemDropResolver.ResolveRuleChains(), and Terraria.GameContent.ItemDropRules.ItemDropResolver.TryDropping().