Terraria Decompiled: Ionic.Zlib.InflateManager.Inflate
Inflate()
int Ionic.Zlib.InflateManager.Inflate (FlushType flush) inline package
Definition at line 73 of file InflateManager.cs.
        {
            if (this._codec.InputBuffer == null)
            {
                throw new ZlibException("InputBuffer is null. ");
            }
            int num = 0;
            int num2 = -5;
            for (;;)
            {
                switch (this.mode)
                {
                case InflateManager.InflateManagerMode.METHOD:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    if (((this.method = (int)this._codec.InputBuffer[this._codec.NextIn++]) & 15) != 8)
                    {
                        this.mode = InflateManager.InflateManagerMode.BAD;
                        this._codec.Message = string.Format("unknown compression method (0x{0:X2})", this.method);
                        this.marker = 5;
                        continue;
                    }
                    if ((this.method >> 4) + 8 > this.wbits)
                    {
                        this.mode = InflateManager.InflateManagerMode.BAD;
                        this._codec.Message = string.Format("invalid window size ({0})", (this.method >> 4) + 8);
                        this.marker = 5;
                        continue;
                    }
                    this.mode = InflateManager.InflateManagerMode.FLAG;
                    continue;
                case InflateManager.InflateManagerMode.FLAG:
                {
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    int num3 = (int)(this._codec.InputBuffer[this._codec.NextIn++] & byte.MaxValue);
                    if (((this.method << 8) + num3) % 31 != 0)
                    {
                        this.mode = InflateManager.InflateManagerMode.BAD;
                        this._codec.Message = "incorrect header check";
                        this.marker = 5;
                        continue;
                    }
                    this.mode = (((num3 & 32) == 0) ? InflateManager.InflateManagerMode.BLOCKS : InflateManager.InflateManagerMode.DICT4);
                    continue;
                }
                case InflateManager.InflateManagerMode.DICT4:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck = (uint)((long)((long)this._codec.InputBuffer[this._codec.NextIn++] << 24) & (long)((ulong)(-16777216)));
                    this.mode = InflateManager.InflateManagerMode.DICT3;
                    continue;
                case InflateManager.InflateManagerMode.DICT3:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck += (uint)(((int)this._codec.InputBuffer[this._codec.NextIn++] << 16) & 16711680);
                    this.mode = InflateManager.InflateManagerMode.DICT2;
                    continue;
                case InflateManager.InflateManagerMode.DICT2:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck += (uint)(((int)this._codec.InputBuffer[this._codec.NextIn++] << 8) & 65280);
                    this.mode = InflateManager.InflateManagerMode.DICT1;
                    continue;
                case InflateManager.InflateManagerMode.DICT1:
                    goto IL_037E;
                case InflateManager.InflateManagerMode.DICT0:
                    goto IL_0407;
                case InflateManager.InflateManagerMode.BLOCKS:
                    num2 = this.blocks.Process(num2);
                    if (num2 == -3)
                    {
                        this.mode = InflateManager.InflateManagerMode.BAD;
                        this.marker = 0;
                        continue;
                    }
                    if (num2 == 0)
                    {
                        num2 = num;
                    }
                    if (num2 != 1)
                    {
                        return num2;
                    }
                    num2 = num;
                    this.computedCheck = this.blocks.Reset();
                    if (!this.HandleRfc1950HeaderBytes)
                    {
                        goto Block_16;
                    }
                    this.mode = InflateManager.InflateManagerMode.CHECK4;
                    continue;
                case InflateManager.InflateManagerMode.CHECK4:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck = (uint)((long)((long)this._codec.InputBuffer[this._codec.NextIn++] << 24) & (long)((ulong)(-16777216)));
                    this.mode = InflateManager.InflateManagerMode.CHECK3;
                    continue;
                case InflateManager.InflateManagerMode.CHECK3:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck += (uint)(((int)this._codec.InputBuffer[this._codec.NextIn++] << 16) & 16711680);
                    this.mode = InflateManager.InflateManagerMode.CHECK2;
                    continue;
                case InflateManager.InflateManagerMode.CHECK2:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck += (uint)(((int)this._codec.InputBuffer[this._codec.NextIn++] << 8) & 65280);
                    this.mode = InflateManager.InflateManagerMode.CHECK1;
                    continue;
                case InflateManager.InflateManagerMode.CHECK1:
                    if (this._codec.AvailableBytesIn == 0)
                    {
                        return num2;
                    }
                    num2 = num;
                    this._codec.AvailableBytesIn--;
                    this._codec.TotalBytesIn += 1L;
                    this.expectedCheck += (uint)(this._codec.InputBuffer[this._codec.NextIn++] & byte.MaxValue);
                    if (this.computedCheck != this.expectedCheck)
                    {
                        this.mode = InflateManager.InflateManagerMode.BAD;
                        this._codec.Message = "incorrect data check";
                        this.marker = 5;
                        continue;
                    }
                    goto IL_06A4;
                case InflateManager.InflateManagerMode.DONE:
                    return 1;
                case InflateManager.InflateManagerMode.BAD:
                    goto IL_06B0;
                }
                break;
            }
            throw new ZlibException("Stream error.");
            IL_037E:
            if (this._codec.AvailableBytesIn == 0)
            {
                return num2;
            }
            this._codec.AvailableBytesIn--;
            this._codec.TotalBytesIn += 1L;
            this.expectedCheck += (uint)(this._codec.InputBuffer[this._codec.NextIn++] & byte.MaxValue);
            this._codec._Adler32 = this.expectedCheck;
            this.mode = InflateManager.InflateManagerMode.DICT0;
            return 2;
            IL_0407:
            this.mode = InflateManager.InflateManagerMode.BAD;
            this._codec.Message = "need dictionary";
            this.marker = 0;
            return -2;
            Block_16:
            this.mode = InflateManager.InflateManagerMode.DONE;
            return 1;
            IL_06A4:
            this.mode = InflateManager.InflateManagerMode.DONE;
            return 1;
            IL_06B0:
            throw new ZlibException(string.Format("Bad state ({0})", this._codec.Message));
        }
References Ionic.Zlib.InflateManager._codec, Ionic.Zlib.ZlibCodec.AvailableBytesIn, Ionic.Zlib.InflateManager.blocks, Ionic.Zlib.InflateManager.computedCheck, Ionic.Zlib.InflateManager.expectedCheck, System.Format, Ionic.Zlib.InflateManager.HandleRfc1950HeaderBytes, Ionic.Zlib.ZlibCodec.InputBuffer, int, System.L, long, Ionic.Zlib.ZlibCodec.Message, Ionic.Zlib.InflateManager.method, Ionic.Zlib.InflateManager.mode, Ionic.Zlib.ZlibCodec.NextIn, Ionic.Zlib.InflateBlocks.Process(), Ionic.Zlib.InflateBlocks.Reset(), and Ionic.Zlib.InflateManager.wbits.
Referenced by Ionic.Zlib.ZlibCodec.Inflate().