Terraria Decompiled: Ionic.Zlib.InflateManager.SetDictionary
SetDictionary()
int Ionic.Zlib.InflateManager.SetDictionary (byte[] dictionary) inline package
Definition at line 275 of file InflateManager.cs.
        {
            int num = 0;
            int num2 = dictionary.Length;
            if (this.mode != InflateManager.InflateManagerMode.DICT0)
            {
                throw new ZlibException("Stream error.");
            }
            if (Adler.Adler32(1U, dictionary, 0, dictionary.Length) != this._codec._Adler32)
            {
                return -3;
            }
            this._codec._Adler32 = Adler.Adler32(0U, null, 0, 0);
            if (num2 >= 1 << this.wbits)
            {
                num2 = (1 << this.wbits) - 1;
                num = dictionary.Length - num2;
            }
            this.blocks.SetDictionary(dictionary, num, num2);
            this.mode = InflateManager.InflateManagerMode.BLOCKS;
            return 0;
        }
References Ionic.Zlib.Adler.Adler32(), Ionic.Zlib.InflateManager.blocks, System.dictionary, Ionic.Zlib.InflateManager.mode, Ionic.Zlib.InflateBlocks.SetDictionary(), System.U, and Ionic.Zlib.InflateManager.wbits.
Referenced by Ionic.Zlib.ZlibCodec.SetDictionary().