Terraria Decompiled: Terraria.Social.WeGame.IPCBase.ReadCallback
ReadCallback()
virtual void Terraria.Social.WeGame.IPCBase.ReadCallback (IAsyncResult result) inline virtual
Reimplemented in Terraria.Social.WeGame.IPCClient, and Terraria.Social.WeGame.IPCServer.
Definition at line 138 of file IPCBase.cs.
        {
            WeGameHelper.WriteDebugString("ReadCallback: " + Thread.CurrentThread.ManagedThreadId.ToString(), new object[0]);
            IPCContent ipccontent = (IPCContent)result.AsyncState;
            try
            {
                int num = this._pipeStream.EndRead(result);
                if (!ipccontent.CancelToken.IsCancellationRequested)
                {
                    if (num > 0)
                    {
                        this._totalData.AddRange(ipccontent.data.Take(num));
                        if (this._pipeStream.IsMessageComplete)
{
                            this.AddPackToList(this._totalData);
                            this._totalData = new List<byte>();
                        }
                    }
                }
                else
                {
                    WeGameHelper.WriteDebugString("IPCBase.ReadCallback.cancel", new object[0]);
                }
            }
            catch (IOException ex)
            {
                this._pipeBrokenFlag = true;
                WeGameHelper.WriteDebugString("ReadCallback Exception, {0}", new object[] { ex.Message });
            }
            catch (InvalidOperationException ex2)
            {
                this._pipeBrokenFlag = true;
                WeGameHelper.WriteDebugString("ReadCallback Exception, {0}", new object[] { ex2.Message });
            }
        }
References Terraria.Social.WeGame.IPCBase._pipeStream, Terraria.Social.WeGame.IPCBase._totalData, Terraria.Social.WeGame.IPCBase.AddPackToList(), System.Collections.Generic.List< T >.AddRange(), System.IAsyncResult.AsyncState, Terraria.Social.WeGame.IPCContent.CancelToken, System.Threading.Thread.CurrentThread, Terraria.Social.WeGame.IPCContent.data, System.Threading.CancellationToken.IsCancellationRequested, System.Threading.Thread.ManagedThreadId, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.IPCBase.BeginReadData().