Terraria Decompiled: System.IO.Stream.d.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.Stream.d.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1876 of file Stream.cs.
            {
                int num2;
                int num = num2;
                int num3;
                try
                {
                    try
                    {
                        ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter;
                        if (num != 0)
{
                            configuredTaskAwaiter = readTask.ConfigureAwait(false).GetAwaiter();
                            if (!configuredTaskAwaiter.IsCompleted)
{
                                num = (num2 = 0);
                                ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter, Stream.<<ReadAsync>g__FinishReadAsync|44_0>d>(ref configuredTaskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                        }
                        int result = configuredTaskAwaiter.GetResult();
                        new Span<byte>(localBuffer, 0, result).CopyTo(localDestination.Span);
                        num3 = result;
                    }
                    finally
                    {
                        if (num < 0)
{
                            ArrayPool<byte>.Shared.Return(localBuffer, false);
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult(num3);
            }
References System.Span< T >.CopyTo(), System.IO.Stream.g__FinishReadAsync(), System.IO.Stream.ReadAsync(), and System.Buffers.ArrayPool< T >.Shared.