Terraria Decompiled: Locale.GetText
GetText() [2/2]
static string Locale.GetText (string msg) inline static
Definition at line 12 of file Locale.cs.
    {
        return msg;
    }
Referenced by System.Security.Policy.ApplicationTrustCollection.Add(), System.Security.SecurityElement.AddAttribute(), System.Security.Policy.NetCodeGroup.AddConnectAccess(), System.Security.Policy.PolicyLevel.AddFullTrustAssembly(), System.Security.Policy.PolicyLevel.AddNamedPermissionSet(), System.Security.Policy.ApplicationTrustCollection.AddRange(), System.Security.Policy.ApplicationTrustCollection.AddRange(), System.Security.SecureString.AppendChar(), System.Security.Policy.ApplicationDirectory.ApplicationDirectory(), System.Security.Policy.PolicyLevel.ChangeNamedPermissionSet(), System.Security.Cryptography.RNGCryptoServiceProvider.Check(), Mono.Security.Cryptography.ARC4Managed.CheckInput(), Mono.Security.Cryptography.SymmetricTransform.CheckInput(), System.Security.CodeAccessPermission.CheckPermissionState(), System.Security.CodeAccessPermission.CheckSecurityElement(), System.Security.Permissions.PrincipalPermission.CheckSecurityElement(), System.Security.Policy.MembershipConditionHelper.CheckSecurityElement(), System.Security.Policy.UrlMembershipCondition.CheckUrl(), System.Security.SecureString.Clear(), System.Security.PermissionSet.ConvertPermissionSet(), System.Security.PermissionSet.CopyTo(), System.Security.PermissionSet.CreateFromBinaryFormat(), System.Security.Policy.Site.CreateFromUrl(), System.Runtime.Hosting.ApplicationActivator.CreateInstanceHelper(), System.IO.IsolatedStorage.IsolatedStorageFileStream.CreateIsolatedPath(), System.MarshalByRefObject.CreateObjRef(), System.Security.Permissions.StrongNameIdentityPermissionAttribute.CreatePermission(), System.Security.PermissionBuilder.CreatePermission(), Mono.Security.Cryptography.DSAManaged.CreateSignature(), System.Security.Cryptography.RSAPKCS1SignatureFormatter.CreateSignature(), System.Security.SecurityManager.Decode(), Mono.Security.Cryptography.RSAManaged.DecryptValue(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(), System.Security.Cryptography.DESTransform.DESTransform(), System.Security.HostSecurityManager.DetermineApplicationTrust(), System.Security.Cryptography.CryptoConfig.EncodeLongNumber(), System.Security.Cryptography.CryptoConfig.EncodeOID(), Mono.Security.Cryptography.DSAManaged.ExportParameters(), Mono.Security.Cryptography.RSAManaged.ExportParameters(), System.Security.Cryptography.DSACryptoServiceProvider.ExportParameters(), System.IO.FileStream.FileStream(), System.IO.FileStream.FileStream(), System.Security.Policy.PolicyLevel.FromString(), System.Security.SecurityElement.FromString(), System.Security.Policy.MonoTrustManager.FromXml(), System.Security.Policy.PolicyLevel.FromXml(), System.Security.PermissionSet.FromXml(), System.Security.Policy.PolicyStatement.FromXml(), System.AppDomainSetup.GetAppBase(), System.Security.Policy.Hash.GetData(), System.IO.IsolatedStorage.IsolatedStorageFile.GetEnumerator(), System.Security.Cryptography.X509Certificates.X509Helper.GetInvalidContextException(), System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageRoot(), System.IO.IsolatedStorage.IsolatedStorageFile.GetStore(), System.Security.Permissions.HostProtectionAttribute.HostProtectionAttribute(), Mono.Security.Cryptography.DSAManaged.ImportParameters(), Mono.Security.Cryptography.RSAManaged.ImportParameters(), System.IO.IsolatedStorage.IsolatedStorage.InitStore(), System.IO.Path.InsecureGetFullPath(), System.Security.SecureString.InsertAt(), System.Security.Permissions.StrongNameIdentityPermission.Intersect(), System.IO.IsolatedStorage.IsolatedStorageFile.IsolatedStorageFile(), System.AppDomain.Load(), System.Security.SecurityManager.LoadPolicyLevelFromFile(), System.Security.SecurityManager.LoadPolicyLevelFromString(), System.Security.Principal.NTAccount.NTAccount(), System.Security.Principal.NTAccount.NTAccount(), System.Threading.Mutex.OpenExisting(), System.IO.IsolatedStorage.IsolatedStorageFile.PostInit(), System.Security.Policy.Url.Prepare(), System.Security.Cryptography.RC2Transform.RC2Transform(), System.Security.Policy.PolicyLevel.Recover(), System.Security.Permissions.RegistryPermission.RegistryPermission(), System.Security.Policy.ApplicationTrustCollection.Remove(), System.Security.SecureString.RemoveAt(), System.Security.Policy.PolicyLevel.RemoveFullTrustAssembly(), System.Security.Policy.PolicyLevel.RemoveNamedPermissionSet(), System.Security.SecurityManager.ResolvePolicy(), System.Security.Policy.PolicyLevel.Save(), System.Security.SecurityElement.SecurityAttribute.SecurityAttribute(), System.Security.SecurityElement.SecurityElement(), System.AppDomain.SetAppDomainPolicy(), System.Security.SecureString.SetAt(), System.Security.Permissions.KeyContainerPermission.SetFlags(), System.AppDomain.SetThreadPrincipal(), System.Security.Cryptography.DSACryptoServiceProvider.SignHash(), System.Security.Policy.Site.Site(), System.Security.Policy.StrongName.StrongName(), Mono.Security.Cryptography.SymmetricTransform.SymmetricTransform(), Mono.Security.Cryptography.SymmetricTransform.ThrowBadPaddingException(), System.Security.Permissions.FileIOPermission.ThrowIfInvalidPath(), System.Security.Permissions.EnvironmentPermission.ThrowInvalidFlag(), System.Security.Permissions.FileIOPermission.ThrowInvalidFlag(), System.Security.Permissions.RegistryPermission.ThrowInvalidFlag(), System.Security.CodeAccessPermission.ThrowInvalidPermission(), System.Security.Policy.ApplicationDirectory.ThrowOnInvalid(), System.Diagnostics.StackFrame.ToString(), Mono.Security.Cryptography.ARC4Managed.TransformBlock(), Mono.Security.Cryptography.SymmetricTransform.TransformBlock(), System.Security.Cryptography.TripleDESTransform.TripleDESTransform(), System.Threading.Mutex.TryOpenExisting(), System.UIntPtr.UIntPtr(), System.Security.Permissions.SiteIdentityPermission.Union(), System.Security.Permissions.UrlIdentityPermission.Union(), System.Security.Permissions.ZoneIdentityPermission.Union(), System.IO.Path.Validate(), System.Reflection.Emit.SignatureHelper.ValidateCustomModifier(), System.Reflection.Emit.SignatureHelper.ValidateParameterModifiers(), System.Security.Cryptography.DSACryptoServiceProvider.VerifyHash(), Mono.Security.Cryptography.DSAManaged.VerifySignature(), System.Security.Cryptography.RSAPKCS1SignatureDeformatter.VerifySignature(), and System.Security.Policy.Zone.Zone().