Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor
InitReadConstructor()
void System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor (Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context) inline private
Definition at line 88 of file ReadObjectInfo.cs.
        {
            if (objectType.IsArray)
            {
                this.InitNoMembers();
                return;
            }
            ISurrogateSelector surrogateSelector2 = null;
            if (surrogateSelector != null)
            {
                this.serializationSurrogate = surrogateSelector.GetSurrogate(objectType, context, out surrogateSelector2);
            }
            if (this.serializationSurrogate != null)
            {
                this.isSi = true;
            }
            else if (objectType != Converter.typeofObject && Converter.typeofISerializable.IsAssignableFrom(objectType))
            {
                this.isSi = true;
            }
            if (this.isSi)
            {
                this.InitSiRead();
                return;
            }
            this.InitMemberInfo();
        }
References System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.context, System.Runtime.Serialization.ISurrogateSelector.GetSurrogate(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitNoMembers(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitSiRead(), System.Type.IsArray, System.Type.IsAssignableFrom(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.serializationSurrogate, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.surrogateSelector, System.Runtime.Serialization.Formatters.Binary.Converter.typeofISerializable, and System.Runtime.Serialization.Formatters.Binary.Converter.typeofObject.
Referenced by System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Init(), and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Init().