Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo
InitMemberInfo()
void System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo () inline private
Definition at line 133 of file ReadObjectInfo.cs.
        {
            this.cache = new SerObjectInfoCache(this.objectType);
            this.cache.memberInfos = FormatterServices.GetSerializableMembers(this.objectType, this.context);
            this.count = this.cache.memberInfos.Length;
            this.cache.memberNames = new string[this.count];
            this.cache.memberTypes = new Type[this.count];
            for (int i = 0; i < this.count; i++)
            {
                this.cache.memberNames[i] = this.cache.memberInfos[i].Name;
                this.cache.memberTypes[i] = this.GetMemberType(this.cache.memberInfos[i]);
            }
            this.isTyped = true;
            this.isNamed = true;
        }
References System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.context, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.count, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberType(), System.Runtime.Serialization.FormatterServices.GetSerializableMembers(), System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberInfos, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberNames, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberTypes, System.Reflection.MemberInfo.Name, and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectType.
Referenced by System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor().