Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Init
Init() [1/2]
void System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Init (Type objectType, ISurrogateSelector surrogateSelector, StreamingContext context, ObjectManager objectManager, SerObjectInfoInit serObjectInfoInit, IFormatterConverter converter, bool bSimpleAssembly) inline package
Definition at line 40 of file ReadObjectInfo.cs.
        {
            this.objectType = objectType;
            this.objectManager = objectManager;
            this.context = context;
            this.serObjectInfoInit = serObjectInfoInit;
            this.formatterConverter = converter;
            this.bSimpleAssembly = bSimpleAssembly;
            this.InitReadConstructor(objectType, surrogateSelector, context);
        }
References System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.bSimpleAssembly, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.context, System.converter, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitReadConstructor(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectManager, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.serObjectInfoInit, and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.surrogateSelector.
Referenced by System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Create(), and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Create().