Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.RecordFixup
RecordFixup()
void System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.RecordFixup (long objectId, string name, long idRef) inline package
Definition at line 243 of file ReadObjectInfo.cs.
        {
            if (this.isSi)
            {
                this.objectManager.RecordDelayedFixup(objectId, name, idRef);
                return;
            }
            int num = this.Position(name);
            if (num != -1)
            {
                this.objectManager.RecordFixup(objectId, this.cache.memberInfos[num], idRef);
            }
        }
References System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberInfos, System.name, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectManager, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Position(), System.Runtime.Serialization.ObjectManager.RecordDelayedFixup(), and System.Runtime.Serialization.ObjectManager.RecordFixup().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().