Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberType
GetMemberType()
Type System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberType (MemberInfo objMember) inline package
Definition at line 373 of file ReadObjectInfo.cs.
        {
            Type type;
            if (objMember is FieldInfo)
            {
                type = ((FieldInfo)objMember).FieldType;
            }
            else
            {
                if (!(objMember is PropertyInfo))
                {
                    throw new SerializationException(Environment.GetResourceString("MemberInfo type {0} cannot be serialized.", new object[] { objMember.GetType() }));
                }
                type = ((PropertyInfo)objMember).PropertyType;
            }
            return type;
        }
References System.Environment.GetResourceString().
Referenced by System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberTypes(), and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.InitMemberInfo().