Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetObjectInfo
GetObjectInfo()
static ReadObjectInfo System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetObjectInfo (SerObjectInfoInit serObjectInfoInit) inline static private
Definition at line 392 of file ReadObjectInfo.cs.
        {
            return new ReadObjectInfo
            {
                objectInfoId = Interlocked.Increment(ref ReadObjectInfo.readObjectInfoCounter)
            };
        }
References System.Threading.Interlocked.Increment(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectInfoId, and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.readObjectInfoCounter.
Referenced by System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Create(), and System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Create().