Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetType
GetType()
Type System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetType (string name) inline package
Definition at line 182 of file ReadObjectInfo.cs.
        {
            int num = this.Position(name);
            if (num == -1)
            {
                return null;
            }
            Type type;
            if (this.isTyped)
            {
                type = this.cache.memberTypes[num];
            }
            else
            {
                type = this.memberTypesList[num];
            }
            if (type == null)
            {
                string text = "Types not available for ISerializable object '{0}'.";
                object[] array = new object[1];
                int num2 = 0;
                Type type2 = this.objectType;
                array[num2] = ((type2 != null) ? type2.ToString() : null) + " " + name;
                throw new SerializationException(Environment.GetResourceString(text, array));
            }
            return type;
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.cache, System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isTyped, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberTypes, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.memberTypesList, System.name, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.objectType, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.Position(), System.text, and System.Type.ToString().
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectReader.ParseMember().