Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberTypes
GetMemberTypes()
Type[] System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberTypes (string[] inMemberNames, Type objectType) inline package
Definition at line 312 of file ReadObjectInfo.cs.
        {
            if (this.isSi)
            {
                throw new SerializationException(Environment.GetResourceString("Types not available for ISerializable object '{0}'.", new object[] { objectType }));
            }
            if (this.cache == null)
            {
                return null;
            }
            if (this.cache.memberTypes == null)
            {
                this.cache.memberTypes = new Type[this.count];
                for (int i = 0; i < this.count; i++)
                {
                    this.cache.memberTypes[i] = this.GetMemberType(this.cache.memberInfos[i]);
                }
            }
            bool flag = false;
            if (inMemberNames.Length < this.cache.memberInfos.Length)
            {
                flag = true;
            }
            Type[] array = new Type[this.cache.memberInfos.Length];
            for (int j = 0; j < this.cache.memberInfos.Length; j++)
            {
                if (!flag && inMemberNames[j].Equals(this.cache.memberInfos[j].Name))
                {
                    array[j] = this.cache.memberTypes[j];
                }
                else
                {
                    bool flag2 = false;
                    for (int k = 0; k < inMemberNames.Length; k++)
                    {
                        if (this.cache.memberInfos[j].Name.Equals(inMemberNames[k]))
{
                            array[j] = this.cache.memberTypes[j];
                            flag2 = true;
                            break;
                        }
                    }
                    if (!flag2)
                    {
                        object[] customAttributes = this.cache.memberInfos[j].GetCustomAttributes(typeof(OptionalFieldAttribute), false);
                        if ((customAttributes == null || customAttributes.Length == 0) && !this.bSimpleAssembly)
{
                            throw new SerializationException(Environment.GetResourceString("Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.", new object[]
{
                                this.cache.memberNames[j],
                                objectType,
                                typeof(OptionalFieldAttribute).FullName
                            }));
                        }
                    }
                }
            }
            return array;
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.cache, System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.count, System.Reflection.MemberInfo.GetCustomAttributes(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.GetMemberType(), System.Environment.GetResourceString(), System.Runtime.Serialization.Formatters.Binary.ReadObjectInfo.isSi, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberInfos, System.Runtime.Serialization.Formatters.Binary.SerObjectInfoCache.memberTypes, and System.Reflection.MemberInfo.Name.
Referenced by System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap(), and System.Runtime.Serialization.Formatters.Binary.ObjectMap.ObjectMap().