Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentReader.RecordDisposable< T >
RecordDisposable< T >()
void Microsoft.Xna.Framework.Content.ContentReader.RecordDisposable< T > (T result) inline private
Definition at line 298 of file ContentReader.cs.
        {
            IDisposable disposable = result as IDisposable;
            if (disposable == null)
            {
                return;
            }
            if (this.recordDisposableObject != null)
            {
                this.recordDisposableObject(disposable);
                return;
            }
            this.contentManager.RecordDisposable(disposable);
        }
References Microsoft.Xna.Framework.Content.ContentReader.contentManager, Microsoft.Xna.Framework.Content.ContentManager.RecordDisposable(), and Microsoft.Xna.Framework.Content.ContentReader.recordDisposableObject.
Referenced by Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject< T >(), Microsoft.Xna.Framework.Content.ContentReader.ReadObject< T >(), and Microsoft.Xna.Framework.Content.ContentReader.ReadObject< T >().