Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject< T >
InnerReadObject< T >()
T Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject< T > (T existingInstance) inline private
Definition at line 281 of file ContentReader.cs.
        {
            int num = this.Read7BitEncodedInt();
            if (num == 0)
            {
                return existingInstance;
            }
            if (num > this.typeReaders.Length)
            {
                throw new ContentLoadException("Incorrect type reader index found!");
            }
            T t = (T)((object)this.typeReaders[num - 1].Read(this, default(T)));
            this.RecordDisposable<T>(t);
            return t;
        }
References Microsoft.Xna.Framework.Content.ContentTypeReader< T >.Read(), Microsoft.Xna.Framework.Content.ContentReader.Read7BitEncodedInt(), Microsoft.Xna.Framework.Content.ContentReader.RecordDisposable< T >(), System.T, and Microsoft.Xna.Framework.Content.ContentReader.typeReaders.
Referenced by Microsoft.Xna.Framework.Content.ContentReader.ReadObject< T >().