Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentReader.ReadAsset< T >
ReadAsset< T >()
object Microsoft.Xna.Framework.Content.ContentReader.ReadAsset< T > () inline package
Definition at line 227 of file ContentReader.cs.
        {
            this.InitializeTypeReaders();
            object obj = this.ReadObject<T>();
            this.ReadSharedResources();
            return obj;
        }
References Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders(), System.obj, Microsoft.Xna.Framework.Content.ContentReader.ReadObject< T >(), and Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources().