Terraria Decompiled: Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders
InitializeTypeReaders()
void Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders () inline package
Definition at line 236 of file ContentReader.cs.
        {
            this.typeReaderManager = new ContentTypeReaderManager();
            this.typeReaders = this.typeReaderManager.LoadAssetReaders(this);
            this.sharedResourceCount = this.Read7BitEncodedInt();
            this.sharedResources = new object[this.sharedResourceCount];
            this.sharedResourceFixups = new List<Action<object>>[this.sharedResourceCount];
            for (int i = 0; i < this.sharedResourceCount; i++)
            {
                this.sharedResourceFixups[i] = new List<Action<object>>();
            }
        }
References Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(), Microsoft.Xna.Framework.Content.ContentReader.Read7BitEncodedInt(), Microsoft.Xna.Framework.Content.ContentReader.sharedResourceCount, Microsoft.Xna.Framework.Content.ContentReader.sharedResourceFixups, and Microsoft.Xna.Framework.Content.ContentReader.typeReaderManager.
Referenced by Microsoft.Xna.Framework.Content.ContentReader.ReadAsset< T >().