Terraria Decompiled: System.Resources.RuntimeResourceSet.GetObject
GetObject() [3/3]
object System.Resources.RuntimeResourceSet.GetObject (string key, bool ignoreCase, bool isString) inline private
Definition at line 107 of file RuntimeResourceSet.cs.
        {
            if (key == null)
            {
                throw new ArgumentNullException("key");
            }
            if (this.Reader == null || this._resCache == null)
            {
                throw new ObjectDisposedException(null, "Cannot access a closed resource set.");
            }
            object obj = null;
            IResourceReader reader = this.Reader;
            object obj3;
            lock (reader)
            {
                if (this.Reader == null)
                {
                    throw new ObjectDisposedException(null, "Cannot access a closed resource set.");
                }
                ResourceLocator resourceLocator;
                if (this._defaultReader != null)
                {
                    int num = -1;
                    if (this._resCache.TryGetValue(key, out resourceLocator))
                    {
                        obj = resourceLocator.Value;
                        num = resourceLocator.DataPosition;
                    }
                    if (num == -1 && obj == null)
                    {
                        num = this._defaultReader.FindPosForResource(key);
                    }
                    if (num != -1 && obj == null)
                    {
                        ResourceTypeCode resourceTypeCode;
                        if (isString)
{
                            obj = this._defaultReader.LoadString(num);
                            resourceTypeCode = ResourceTypeCode.String;
                        }
                        else
{
                            obj = this._defaultReader.LoadObject(num, out resourceTypeCode);
                        }
                        resourceLocator = new ResourceLocator(num, ResourceLocator.CanCache(resourceTypeCode) ? obj : null);
                        Dictionary<string, ResourceLocator> resCache = this._resCache;
                        lock (resCache)
{
                            this._resCache[key] = resourceLocator;
                        }
                    }
                    if (obj != null || !ignoreCase)
                    {
                        return obj;
                    }
                }
                if (!this._haveReadFromReader)
                {
                    if (ignoreCase && this._caseInsensitiveTable == null)
                    {
                        this._caseInsensitiveTable = new Dictionary<string, ResourceLocator>(StringComparer.OrdinalIgnoreCase);
                    }
                    if (this._defaultReader == null)
                    {
                        IDictionaryEnumerator enumerator = this.Reader.GetEnumerator();
                        while (enumerator.MoveNext())
{
                            DictionaryEntry entry = enumerator.Entry;
                            string text = (string)entry.Key;
                            ResourceLocator resourceLocator2 = new ResourceLocator(-1, entry.Value);
                            this._resCache.Add(text, resourceLocator2);
                            if (ignoreCase)
{
                                this._caseInsensitiveTable.Add(text, resourceLocator2);
                            }
                        }
                        if (!ignoreCase)
{
                            this.Reader.Close();
                        }
                    }
                    else
                    {
                        ResourceReader.ResourceEnumerator enumeratorInternal = this._defaultReader.GetEnumeratorInternal();
                        while (enumeratorInternal.MoveNext())
{
                            string text2 = (string)enumeratorInternal.Key;
                            int dataPosition = enumeratorInternal.DataPosition;
                            ResourceLocator resourceLocator3 = new ResourceLocator(dataPosition, null);
                            this._caseInsensitiveTable.Add(text2, resourceLocator3);
                        }
                    }
                    this._haveReadFromReader = true;
                }
                object obj2 = null;
                bool flag3 = false;
                bool flag4 = false;
                if (this._defaultReader != null && this._resCache.TryGetValue(key, out resourceLocator))
                {
                    flag3 = true;
                    obj2 = this.ResolveResourceLocator(resourceLocator, key, this._resCache, flag4);
                }
                if (!flag3 && ignoreCase && this._caseInsensitiveTable.TryGetValue(key, out resourceLocator))
                {
                    flag4 = true;
                    obj2 = this.ResolveResourceLocator(resourceLocator, key, this._resCache, flag4);
                }
                obj3 = obj2;
            }
            return obj3;
        }
References System.Resources.RuntimeResourceSet._caseInsensitiveTable, System.Resources.RuntimeResourceSet._defaultReader, System.Resources.RuntimeResourceSet._haveReadFromReader, System.Resources.RuntimeResourceSet._resCache, System.Resources.ResourceLocator.CanCache(), System.Resources.IResourceReader.Close(), System.Resources.ResourceReader.ResourceEnumerator.DataPosition, System.Collections.IDictionaryEnumerator.Entry, System.Resources.ResourceReader.FindPosForResource(), System.Resources.IResourceReader.GetEnumerator(), System.Resources.ResourceReader.GetEnumeratorInternal(), System.Collections.DictionaryEntry.Key, System.key, System.Resources.ResourceReader.ResourceEnumerator.Key, System.Resources.ResourceReader.LoadObject(), System.Resources.ResourceReader.LoadString(), System.Collections.IEnumerator.MoveNext(), System.Resources.ResourceReader.ResourceEnumerator.MoveNext(), System.obj, System.StringComparer.OrdinalIgnoreCase, System.Resources.ResourceSet.Reader, System.Resources.RuntimeResourceSet.ResolveResourceLocator(), System.text, System.Collections.DictionaryEntry.Value, and System.Resources.ResourceLocator.Value.