Terraria Decompiled: System.Resources.RuntimeResourceSet.ResolveResourceLocator
ResolveResourceLocator()
object System.Resources.RuntimeResourceSet.ResolveResourceLocator (ResourceLocator resLocation, string key, Dictionary< string, ResourceLocator > copyOfCache, bool keyInWrongCase) inline private
Definition at line 220 of file RuntimeResourceSet.cs.
        {
            object obj = resLocation.Value;
            if (obj == null)
            {
                IResourceReader reader = this.Reader;
                ResourceTypeCode resourceTypeCode;
                lock (reader)
                {
                    obj = this._defaultReader.LoadObject(resLocation.DataPosition, out resourceTypeCode);
                }
                if (!keyInWrongCase && ResourceLocator.CanCache(resourceTypeCode))
                {
                    resLocation.Value = obj;
                    copyOfCache[key] = resLocation;
                }
            }
            return obj;
        }
References System.Resources.RuntimeResourceSet._defaultReader, System.Resources.ResourceLocator.CanCache(), System.Resources.ResourceLocator.DataPosition, System.key, System.Resources.ResourceReader.LoadObject(), System.obj, System.Resources.ResourceSet.Reader, and System.Resources.ResourceLocator.Value.
Referenced by System.Resources.RuntimeResourceSet.GetObject().