Terraria Decompiled: Steamworks.SteamInventory.GetItemDefinitionProperty
GetItemDefinitionProperty()
static bool Steamworks.SteamInventory.GetItemDefinitionProperty (SteamItemDef_t iDefinition, string pchPropertyName, out string pchValueBuffer, ref uint punValueBufferSizeOut) inline static
Definition at line 181 of file SteamInventory.cs.
        {
            InteropHelp.TestIfAvailableClient();
            IntPtr intPtr = Marshal.AllocHGlobal((int)punValueBufferSizeOut);
            bool flag2;
            using (InteropHelp.UTF8StringHandle utf8StringHandle = new InteropHelp.UTF8StringHandle(pchPropertyName))
            {
                bool flag = NativeMethods.ISteamInventory_GetItemDefinitionProperty(CSteamAPIContext.GetSteamInventory(), iDefinition, utf8StringHandle, intPtr, ref punValueBufferSizeOut);
                pchValueBuffer = (flag ? InteropHelp.PtrToStringUTF8(intPtr) : null);
                Marshal.FreeHGlobal(intPtr);
                flag2 = flag;
            }
            return flag2;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), Steamworks.CSteamAPIContext.GetSteamInventory(), Steamworks.NativeMethods.ISteamInventory_GetItemDefinitionProperty(), Steamworks.InteropHelp.PtrToStringUTF8(), and Steamworks.InteropHelp.TestIfAvailableClient().