Terraria Decompiled: System.Runtime.InteropServices.SafeBuffer.Write< T >
Write< T >()
unsafe void System.Runtime.InteropServices.SafeBuffer.Write< T > (ulong byteOffset, T value) inline
Type Constraints
T : struct
Definition at line 182 of file SafeBuffer.cs.
                                                                       : struct
        {
            if (this._numBytes == SafeBuffer.Uninitialized)
            {
                throw SafeBuffer.NotInitialized();
            }
            uint num = SafeBuffer.SizeOf<T>();
            byte* ptr = (byte*)(void*)this.handle + byteOffset;
            this.SpaceCheck(ptr, (ulong)num);
            bool flag = false;
            try
            {
                base.DangerousAddRef(ref flag);
                try
                {
                    fixed (byte* ptr2 = Unsafe.As<T, byte>(ref value))
                    {
                        byte* ptr3 = ptr2;
                        Buffer.Memmove(ptr, ptr3, num);
                    }
                }
                finally
                {
                    byte* ptr2 = null;
                }
            }
            finally
            {
                if (flag)
                {
                    base.DangerousRelease();
                }
            }
        }
References System.Runtime.InteropServices.SafeBuffer._numBytes, System.byteOffset, System.Buffer.Memmove(), System.Runtime.InteropServices.SafeBuffer.NotInitialized(), System.Runtime.InteropServices.SafeBuffer.SpaceCheck(), System.Runtime.InteropServices.SafeBuffer.Uninitialized, and System.value.