Terraria Decompiled: Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull
ArgumentNotNull()
static void Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull (object value, string parameterName) inline static
Definition at line 9 of file ValidationUtils.cs.
        {
            if (value == null)
            {
                throw new ArgumentNullException(parameterName);
            }
        }
References System.value.
Referenced by Newtonsoft.Json.Linq.Extensions.Ancestors< T >(), Newtonsoft.Json.Linq.Extensions.AncestorsAndSelf< T >(), Newtonsoft.Json.Utilities.Base64Encoder.Base64Encoder(), Newtonsoft.Json.Bson.BsonObjectId.BsonObjectId(), Newtonsoft.Json.Bson.BsonReader.BsonReader(), Newtonsoft.Json.Bson.BsonReader.BsonReader(), Newtonsoft.Json.Bson.BsonWriter.BsonWriter(), Newtonsoft.Json.Bson.BsonWriter.BsonWriter(), Newtonsoft.Json.Linq.Extensions.Children< T, U >(), Newtonsoft.Json.Utilities.CollectionWrapper< T >.CollectionWrapper(), Newtonsoft.Json.Utilities.CollectionWrapper< T >.CollectionWrapper(), Newtonsoft.Json.Serialization.JsonFormatterConverter.Convert(), Newtonsoft.Json.Serialization.JsonFormatterConverter.Convert(), Newtonsoft.Json.Linq.Extensions.Convert< T, U >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateDefaultConstructor< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateDefaultConstructor< T >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJToken(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateMethodCall< T >(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObjectUsingCreatorWithParameters(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateParameterizedConstructor(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateSet< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateSet< T >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateSet< T >(), Newtonsoft.Json.Utilities.LateBoundReflectionDelegateFactory.CreateSet< T >(), Newtonsoft.Json.Linq.Extensions.Descendants< T >(), Newtonsoft.Json.Linq.Extensions.DescendantsAndSelf< T >(), Newtonsoft.Json.JsonSerializer.DeserializeInternal(), Newtonsoft.Json.JsonConvert.DeserializeObject(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.DictionaryEnumerator< TEnumeratorKey, TEnumeratorValue >.DictionaryEnumerator(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.DictionaryWrapper(), Newtonsoft.Json.Utilities.DictionaryWrapper< TKey, TValue >.DictionaryWrapper(), Newtonsoft.Json.Serialization.DynamicValueProvider.DynamicValueProvider(), Newtonsoft.Json.Serialization.DefaultContractResolver.EnumerableDictionaryWrapper< TEnumeratorKey, TEnumeratorValue >.EnumerableDictionaryWrapper(), Newtonsoft.Json.Serialization.ExpressionValueProvider.ExpressionValueProvider(), Newtonsoft.Json.Utilities.StringUtils.FormatWith(), Newtonsoft.Json.Linq.JToken.FromObjectInternal(), Newtonsoft.Json.Schema.JsonSchemaGenerator.Generate(), Newtonsoft.Json.Schema.JsonSchemaGenerator.GenerateInternal(), Newtonsoft.Json.Utilities.ReflectionUtils.GetAttributes(), Newtonsoft.Json.Utilities.ReflectionUtils.GetBaseDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.GetCollectionItemType(), Newtonsoft.Json.Utilities.ReflectionUtils.GetDictionaryKeyValueTypes(), Newtonsoft.Json.Utilities.ReflectionUtils.GetFields(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberUnderlyingType(), Newtonsoft.Json.Utilities.ReflectionUtils.GetMemberValue(), Newtonsoft.Json.Utilities.ReflectionUtils.GetProperties(), Newtonsoft.Json.Serialization.JsonFormatterConverter.GetTokenValue< T >(), Newtonsoft.Json.Linq.JToken.GetType(), Newtonsoft.Json.Utilities.ReflectionUtils.HasDefaultConstructor(), Newtonsoft.Json.Utilities.ReflectionUtils.ImplementsGenericDefinition(), Newtonsoft.Json.Utilities.ReflectionUtils.InheritsGenericDefinition(), Newtonsoft.Json.Utilities.CollectionUtils.IsDictionaryType(), Newtonsoft.Json.Utilities.ReflectionUtils.IsIndexedProperty(), Newtonsoft.Json.Utilities.ReflectionUtils.IsIndexedProperty(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullable(), Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), Newtonsoft.Json.Utilities.ReflectionUtils.IsVirtual(), Newtonsoft.Json.Linq.JContainer.JContainer(), Newtonsoft.Json.Linq.JEnumerable< T >.JEnumerable(), Newtonsoft.Json.Linq.JsonPath.JPath.JPath(), Newtonsoft.Json.Linq.JProperty.JProperty(), Newtonsoft.Json.Linq.JProperty.JProperty(), Newtonsoft.Json.Serialization.JsonContract.JsonContract(), Newtonsoft.Json.Serialization.JsonFormatterConverter.JsonFormatterConverter(), Newtonsoft.Json.Serialization.JsonPropertyCollection.JsonPropertyCollection(), Newtonsoft.Json.Schema.JsonSchemaWriter.JsonSchemaWriter(), Newtonsoft.Json.Serialization.JsonSerializerInternalBase.JsonSerializerInternalBase(), Newtonsoft.Json.Serialization.JsonSerializerProxy.JsonSerializerProxy(), Newtonsoft.Json.Serialization.JsonSerializerProxy.JsonSerializerProxy(), Newtonsoft.Json.JsonValidatingReader.JsonValidatingReader(), Newtonsoft.Json.Linq.JTokenReader.JTokenReader(), Newtonsoft.Json.Linq.JTokenWriter.JTokenWriter(), Newtonsoft.Json.Linq.JObject.Load(), Newtonsoft.Json.Linq.Extensions.MoveNext(), Newtonsoft.Json.Schema.JsonSchema.Parse(), Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Populate(), Newtonsoft.Json.JsonSerializer.PopulateInternal(), Newtonsoft.Json.Linq.Extensions.Properties(), Newtonsoft.Json.Schema.JsonSchema.Read(), Newtonsoft.Json.Linq.JContainer.ReadContentFrom(), Newtonsoft.Json.Linq.JToken.ReadFrom(), Newtonsoft.Json.Serialization.ReflectionAttributeProvider.ReflectionAttributeProvider(), Newtonsoft.Json.Serialization.ReflectionValueProvider.ReflectionValueProvider(), Newtonsoft.Json.JsonSerializer.SerializeInternal(), Newtonsoft.Json.Utilities.ReflectionUtils.SetMemberValue(), Newtonsoft.Json.Linq.JToken.ToObject(), Newtonsoft.Json.Serialization.JsonDynamicContract.TryGetMember(), Newtonsoft.Json.Serialization.JsonDynamicContract.TrySetMember(), Newtonsoft.Json.Schema.JsonSchemaGenerator.TypeSchema.TypeSchema(), Newtonsoft.Json.Schema.Extensions.Validate(), Newtonsoft.Json.Linq.JContainer.ValidateToken(), Newtonsoft.Json.Linq.JObject.ValidateToken(), Newtonsoft.Json.Schema.ValidationEventArgs.ValidationEventArgs(), Newtonsoft.Json.Linq.Extensions.Value< T, U >(), Newtonsoft.Json.Linq.Extensions.Values< T, U >(), Newtonsoft.Json.Bson.BsonWriter.WriteObjectId(), Newtonsoft.Json.Bson.BsonWriter.WriteRegex(), Newtonsoft.Json.Schema.JsonSchemaWriter.WriteSchema(), Newtonsoft.Json.Schema.JsonSchema.WriteTo(), Newtonsoft.Json.JsonWriter.WriteToken(), and Newtonsoft.Json.JsonWriter.WriteToken().