Terraria Decompiled: System.IO.StreamReader.d__61.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamReader.d__61.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1287 of file StreamReader.cs.
            {
                int num2;
                int num = num2;
                StreamReader streamReader = this;
                string text;
                try
                {
                    ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter configuredTaskAwaiter3;
                    bool flag;
                    switch (num)
                    {
                    case 0:
                        configuredTaskAwaiter3 = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                        num2 = -1;
                        break;
                    case 1:
                        configuredTaskAwaiter3 = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                        num2 = -1;
                        goto IL_01A9;
                    case 2:
                        configuredTaskAwaiter3 = configuredTaskAwaiter2;
                        configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter);
                        num2 = -1;
                        goto IL_0287;
                    default:
                        flag = streamReader._charPos == streamReader._charLen;
                        if (!flag)
{
                            goto IL_009E;
                        }
                        configuredTaskAwaiter3 = streamReader.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                        if (!configuredTaskAwaiter3.IsCompleted)
{
                            num2 = 0;
                            configuredTaskAwaiter2 = configuredTaskAwaiter3;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter, StreamReader.<ReadLineAsyncInternal>d__61>(ref configuredTaskAwaiter3, ref this);
                            return;
                        }
                        break;
                    }
                    flag = configuredTaskAwaiter3.GetResult() == 0;
                    IL_009E:
                    if (flag)
                    {
                        text = null;
                        goto IL_02C2;
                    }
                    sb = null;
                    IL_00AF:
                    char[] charBuffer = streamReader._charBuffer;
                    int charLen = streamReader._charLen;
                    int num3 = streamReader._charPos;
                    int num4 = num3;
                    char c;
                    for (;;)
                    {
                        c = charBuffer[num4];
                        if (c == '\r' || c == '\n')
{
                            break;
                        }
                        num4++;
                        if (num4 >= charLen)
{
                            goto Block_14;
                        }
                    }
                    if (sb != null)
                    {
                        sb.Append(charBuffer, num3, num4 - num3);
                        s = sb.ToString();
                    }
                    else
                    {
                        s = new string(charBuffer, num3, num4 - num3);
                    }
                    num3 = (streamReader._charPos = num4 + 1);
                    flag = c == '\r';
                    if (!flag)
                    {
                        goto IL_01B8;
                    }
                    bool flag2 = num3 < charLen;
                    if (flag2)
                    {
                        goto IL_01B5;
                    }
                    configuredTaskAwaiter3 = streamReader.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter3.IsCompleted)
                    {
                        num2 = 1;
                        configuredTaskAwaiter2 = configuredTaskAwaiter3;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter, StreamReader.<ReadLineAsyncInternal>d__61>(ref configuredTaskAwaiter3, ref this);
                        return;
                    }
                    goto IL_01A9;
                    Block_14:
                    num4 = charLen - num3;
                    if (sb == null)
                    {
                        sb = new StringBuilder(num4 + 80);
                    }
                    sb.Append(charBuffer, num3, num4);
                    configuredTaskAwaiter3 = streamReader.ReadBufferAsync().ConfigureAwait(false).GetAwaiter();
                    if (!configuredTaskAwaiter3.IsCompleted)
                    {
                        num2 = 2;
                        configuredTaskAwaiter2 = configuredTaskAwaiter3;
                        this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable<int>.ConfiguredTaskAwaiter, StreamReader.<ReadLineAsyncInternal>d__61>(ref configuredTaskAwaiter3, ref this);
                        return;
                    }
                    goto IL_0287;
                    IL_01A9:
                    flag2 = configuredTaskAwaiter3.GetResult() > 0;
                    IL_01B5:
                    flag = flag2;
                    IL_01B8:
                    if (flag)
                    {
                        num3 = streamReader._charPos;
                        if (streamReader._charBuffer[num3] == '\n')
{
                            streamReader._charPos = num3 + 1;
                        }
                    }
                    text = s;
                    goto IL_02C2;
                    IL_0287:
                    if (configuredTaskAwaiter3.GetResult() > 0)
                    {
                        goto IL_00AF;
                    }
                    text = sb.ToString();
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    sb = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_02C2:
                num2 = -2;
                sb = null;
                this.<>t__builder.SetResult(text);
            }
References System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._charPos, System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.IO.StreamReader.ReadBufferAsync(), System.IO.StreamReader.ReadLineAsyncInternal(), System.s, and System.text.