Terraria Decompiled: Terraria.Utilities.BitSet2D.Reset
Reset()
void Terraria.Utilities.BitSet2D.Reset (Point center, int maxDist) inline
Definition at line 10 of file BitSet2D.cs.
        {
            this.size = maxDist * 2 + 1;
            this.offset = new Point(center.X - maxDist, center.Y - maxDist);
            int num = this.size * this.size + 63 >> 6;
            if (this.bits == null || this.bits.Length < num)
            {
                Array.Resize<Bits64>(ref this.bits, num);
            }
            Array.Clear(this.bits, 0, this.bits.Length);
        }
References Terraria.Utilities.BitSet2D.bits, System.Array.Clear(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.Utils.FloodFillTile(), and Terraria.WorldGen.StartRoomCheck().