Terraria Decompiled: System.Resources.ResourceReader.FindPosForResource
FindPosForResource()
int System.Resources.ResourceReader.FindPosForResource (string name) inline package
Definition at line 178 of file ResourceReader.cs.
        {
            int num = FastResourceComparer.HashFunction(name);
            int i = 0;
            int num2 = this._numResources - 1;
            int num3 = -1;
            bool flag = false;
            while (i <= num2)
            {
                num3 = i + num2 >> 1;
                int nameHash = this.GetNameHash(num3);
                int num4;
                if (nameHash == num)
                {
                    num4 = 0;
                }
                else if (nameHash < num)
                {
                    num4 = -1;
                }
                else
                {
                    num4 = 1;
                }
                if (num4 == 0)
                {
                    flag = true;
                    break;
                }
                if (num4 < 0)
                {
                    i = num3 + 1;
                }
                else
                {
                    num2 = num3 - 1;
                }
            }
            if (!flag)
            {
                return -1;
            }
            if (i != num3)
            {
                i = num3;
                while (i > 0 && this.GetNameHash(i - 1) == num)
                {
                    i--;
                }
            }
            if (num2 != num3)
            {
                num2 = num3;
                while (num2 < this._numResources - 1 && this.GetNameHash(num2 + 1) == num)
                {
                    num2++;
                }
            }
            lock (this)
            {
                int j = i;
                while (j <= num2)
                {
                    this._store.BaseStream.Seek(this._nameSectionOffset + (long)this.GetNamePosition(j), SeekOrigin.Begin);
                    if (this.CompareStringEqualsName(name))
                    {
                        int num5 = this._store.ReadInt32();
                        if (num5 < 0 || (long)num5 >= this._store.BaseStream.Length - this._dataSectionOffset)
{
                            throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into data section.", new object[] { num5 }));
                        }
                        return num5;
                    }
                    else
                    {
                        j++;
                    }
                }
            }
            return -1;
        }
References System.Resources.ResourceReader._nameSectionOffset, System.Resources.ResourceReader._numResources, System.Resources.ResourceReader._store, System.IO.BinaryReader.BaseStream, System.Resources.ResourceReader.CompareStringEqualsName(), System.Resources.ResourceReader.GetNameHash(), System.Resources.ResourceReader.GetNamePosition(), System.Environment.GetResourceString(), System.Resources.FastResourceComparer.HashFunction(), System.IO.Stream.Length, System.name, System.IO.BinaryReader.ReadInt32(), and System.IO.Stream.Seek().
Referenced by System.Resources.RuntimeResourceSet.GetObject(), and System.Resources.ResourceReader.GetResourceData().