Terraria Decompiled: System.Resources.ResourceReader.LoadObjectV2
LoadObjectV2()
object System.Resources.ResourceReader.LoadObjectV2 (int pos, out ResourceTypeCode typeCode) inline package
Definition at line 558 of file ResourceReader.cs.
        {
            object obj;
            try
            {
                obj = this._LoadObjectV2(pos, out typeCode);
            }
            catch (EndOfStreamException ex)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified type doesn't match the available data in the stream."), ex);
            }
            catch (ArgumentOutOfRangeException ex2)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified type doesn't match the available data in the stream."), ex2);
            }
            return obj;
        }
References System.Resources.ResourceReader._LoadObjectV2(), System.Environment.GetResourceString(), and System.obj.
Referenced by System.Resources.ResourceReader.GetValueForNameIndex(), System.Resources.ResourceReader.LoadObject(), and System.Resources.ResourceReader.LoadObject().