Terraria Decompiled: System.Resources.ResourceReader.GetNamePosition
GetNamePosition()
int System.Resources.ResourceReader.GetNamePosition (int index) inline private
Definition at line 137 of file ResourceReader.cs.
        {
            int num;
            if (this._ums == null)
            {
                num = this._namePositions[index];
            }
            else
            {
                num = ResourceReader.ReadUnalignedI4(this._namePositionsPtr + index);
            }
            if (num < 0 || (long)num > this._dataSectionOffset - this._nameSectionOffset)
            {
                throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into name section.", new object[] { num }));
            }
            return num;
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._namePositions, System.Resources.ResourceReader._namePositionsPtr, System.Resources.ResourceReader._nameSectionOffset, System.Resources.ResourceReader._ums, System.Environment.GetResourceString(), System.index, and System.Resources.ResourceReader.ReadUnalignedI4().
Referenced by System.Resources.ResourceReader.AllocateStringForNameIndex(), System.Resources.ResourceReader.FindPosForResource(), System.Resources.ResourceReader.GetResourceData(), and System.Resources.ResourceReader.GetValueForNameIndex().