Terraria Decompiled: System.Resources.ResourceReader.LoadString
LoadString()
string System.Resources.ResourceReader.LoadString (int pos) inline package
Definition at line 399 of file ResourceReader.cs.
        {
            this._store.BaseStream.Seek(this._dataSectionOffset + (long)pos, SeekOrigin.Begin);
            string text = null;
            int num = this._store.Read7BitEncodedInt();
            if (this._version == 1)
            {
                if (num == -1)
                {
                    return null;
                }
                if (this.FindType(num) != typeof(string))
                {
                    throw new InvalidOperationException(Environment.GetResourceString("Resource was of type '{0}' instead of String - call GetObject instead.", new object[] { this.FindType(num).FullName }));
                }
                text = this._store.ReadString();
            }
            else
            {
                ResourceTypeCode resourceTypeCode = (ResourceTypeCode)num;
                if (resourceTypeCode != ResourceTypeCode.String && resourceTypeCode != ResourceTypeCode.Null)
                {
                    string text2;
                    if (resourceTypeCode < ResourceTypeCode.StartOfUserTypes)
                    {
                        text2 = resourceTypeCode.ToString();
                    }
                    else
                    {
                        text2 = this.FindType(resourceTypeCode - ResourceTypeCode.StartOfUserTypes).FullName;
                    }
                    throw new InvalidOperationException(Environment.GetResourceString("Resource was of type '{0}' instead of String - call GetObject instead.", new object[] { text2 }));
                }
                if (resourceTypeCode == ResourceTypeCode.String)
                {
                    text = this._store.ReadString();
                }
            }
            return text;
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._store, System.Resources.ResourceReader._version, System.IO.BinaryReader.BaseStream, System.Resources.ResourceReader.FindType(), System.RuntimeType.FullName, System.Environment.GetResourceString(), System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadString(), System.IO.Stream.Seek(), and System.text.
Referenced by System.Resources.RuntimeResourceSet.GetObject().