Terraria Decompiled: System.Resources.ResourceReader.ResourceReader
ResourceReader() [1/3]
System.Resources.ResourceReader.ResourceReader (string fileName) inline
Definition at line 20 of file ResourceReader.cs.
        {
            this._resCache = new Dictionary<string, ResourceLocator>(FastResourceComparer.Default);
            this._store = new BinaryReader(new FileStream(fileName, FileMode.Open, FileAccess.Read, FileShare.Read, 4096, FileOptions.RandomAccess, Path.GetFileName(fileName), false, false, false), Encoding.UTF8);
            try
            {
                this.ReadResources();
            }
            catch
            {
                this._store.Close();
                throw;
            }
        }
References System.Resources.ResourceReader._store, System.IO.BinaryReader.Close(), System.Resources.FastResourceComparer.Default, System.IO.Path.GetFileName(), System.Resources.ResourceReader.ReadResources(), and System.Text.Encoding.UTF8.