Terraria Decompiled: System.Resources.ResourceReader._LoadObjectV1
_LoadObjectV1()
object System.Resources.ResourceReader._LoadObjectV1 (int pos) inline private
Definition at line 484 of file ResourceReader.cs.
        {
            this._store.BaseStream.Seek(this._dataSectionOffset + (long)pos, SeekOrigin.Begin);
            int num = this._store.Read7BitEncodedInt();
            if (num == -1)
            {
                return null;
            }
            RuntimeType runtimeType = this.FindType(num);
            if (runtimeType == typeof(string))
            {
                return this._store.ReadString();
            }
            if (runtimeType == typeof(int))
            {
                return this._store.ReadInt32();
            }
            if (runtimeType == typeof(byte))
            {
                return this._store.ReadByte();
            }
            if (runtimeType == typeof(sbyte))
            {
                return this._store.ReadSByte();
            }
            if (runtimeType == typeof(short))
            {
                return this._store.ReadInt16();
            }
            if (runtimeType == typeof(long))
            {
                return this._store.ReadInt64();
            }
            if (runtimeType == typeof(ushort))
            {
                return this._store.ReadUInt16();
            }
            if (runtimeType == typeof(uint))
            {
                return this._store.ReadUInt32();
            }
            if (runtimeType == typeof(ulong))
            {
                return this._store.ReadUInt64();
            }
            if (runtimeType == typeof(float))
            {
                return this._store.ReadSingle();
            }
            if (runtimeType == typeof(double))
            {
                return this._store.ReadDouble();
            }
            if (runtimeType == typeof(DateTime))
            {
                return new DateTime(this._store.ReadInt64());
            }
            if (runtimeType == typeof(TimeSpan))
            {
                return new TimeSpan(this._store.ReadInt64());
            }
            if (runtimeType == typeof(decimal))
            {
                int[] array = new int[4];
                for (int i = 0; i < array.Length; i++)
                {
                    array[i] = this._store.ReadInt32();
                }
                return new decimal(array);
            }
            return this.DeserializeObject(num);
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._store, System.array, System.IO.BinaryReader.BaseStream, System.Resources.DateTime, System.Resources.ResourceReader.DeserializeObject(), System.Resources.ResourceReader.FindType(), System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSByte(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), System.IO.BinaryReader.ReadUInt64(), System.IO.Stream.Seek(), and System.Resources.TimeSpan.
Referenced by System.Resources.ResourceReader.LoadObjectV1().