Terraria Decompiled: System.Resources.ResourceReader.LoadObject
LoadObject() [1/2]
object System.Resources.ResourceReader.LoadObject (int pos) inline package
Definition at line 441 of file ResourceReader.cs.
        {
            if (this._version == 1)
            {
                return this.LoadObjectV1(pos);
            }
            ResourceTypeCode resourceTypeCode;
            return this.LoadObjectV2(pos, out resourceTypeCode);
        }
References System.Resources.ResourceReader._version, System.Resources.ResourceReader.LoadObjectV1(), and System.Resources.ResourceReader.LoadObjectV2().
Referenced by System.Resources.RuntimeResourceSet.GetObject(), and System.Resources.RuntimeResourceSet.ResolveResourceLocator().