Terraria Decompiled: System.Resources.ResourceReader.GetValueForNameIndex
GetValueForNameIndex()
object System.Resources.ResourceReader.GetValueForNameIndex (int index) inline private
Definition at line 372 of file ResourceReader.cs.
        {
            long num = (long)this.GetNamePosition(index);
            object obj;
            lock (this)
            {
                this._store.BaseStream.Seek(num + this._nameSectionOffset, SeekOrigin.Begin);
                this.SkipString();
                int num2 = this._store.ReadInt32();
                if (num2 < 0 || (long)num2 >= this._store.BaseStream.Length - this._dataSectionOffset)
                {
                    throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into data section.", new object[] { num2 }));
                }
                if (this._version == 1)
                {
                    obj = this.LoadObjectV1(num2);
                }
                else
                {
                    ResourceTypeCode resourceTypeCode;
                    obj = this.LoadObjectV2(num2, out resourceTypeCode);
                }
            }
            return obj;
        }
References System.Resources.ResourceReader._nameSectionOffset, System.Resources.ResourceReader._store, System.Resources.ResourceReader._version, System.IO.BinaryReader.BaseStream, System.Resources.ResourceReader.GetNamePosition(), System.Environment.GetResourceString(), System.IO.Stream.Length, System.Resources.ResourceReader.LoadObjectV1(), System.Resources.ResourceReader.LoadObjectV2(), long, System.obj, System.IO.BinaryReader.ReadInt32(), System.IO.Stream.Seek(), and System.Resources.ResourceReader.SkipString().