Terraria Decompiled: System.Resources.ResourceReader._ReadResources
_ReadResources()
unsafe void System.Resources.ResourceReader._ReadResources () inline private
Definition at line 710 of file ResourceReader.cs.
        {
            if (this._store.ReadInt32() != ResourceManager.MagicNumber)
            {
                throw new ArgumentException(Environment.GetResourceString("Stream is not a valid resource file."));
            }
            int num = this._store.ReadInt32();
            int num2 = this._store.ReadInt32();
            if (num2 < 0 || num < 0)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
            }
            if (num > 1)
            {
                this._store.BaseStream.Seek((long)num2, SeekOrigin.Current);
            }
            else
            {
                string text = this._store.ReadString();
                AssemblyName assemblyName = new AssemblyName(ResourceManager.MscorlibName);
                if (!ResourceManager.CompareNames(text, ResourceManager.ResReaderTypeName, assemblyName))
                {
                    throw new NotSupportedException(Environment.GetResourceString("This .resources file should not be read with this reader. The resource reader type is \"{0}\".", new object[] { text }));
                }
                this.SkipString();
            }
            int num3 = this._store.ReadInt32();
            if (num3 != 2 && num3 != 1)
            {
                throw new ArgumentException(Environment.GetResourceString("The ResourceReader class does not know how to read this version of .resources files. Expected version: {0}  This file: {1}", new object[] { 2, num3 }));
            }
            this._version = num3;
            this._numResources = this._store.ReadInt32();
            if (this._numResources < 0)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
            }
            int num4 = this._store.ReadInt32();
            if (num4 < 0)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
            }
            this._typeTable = new RuntimeType[num4];
            this._typeNamePositions = new int[num4];
            for (int i = 0; i < num4; i++)
            {
                this._typeNamePositions[i] = (int)this._store.BaseStream.Position;
                this.SkipString();
            }
            int num5 = (int)this._store.BaseStream.Position & 7;
            if (num5 != 0)
            {
                for (int j = 0; j < 8 - num5; j++)
                {
                    this._store.ReadByte();
                }
            }
            if (this._ums == null)
            {
                this._nameHashes = new int[this._numResources];
                for (int k = 0; k < this._numResources; k++)
                {
                    this._nameHashes[k] = this._store.ReadInt32();
                }
            }
            else
            {
                if (((long)this._numResources & (long)((ulong)(-536870912))) != 0L)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
                }
                int num6 = 4 * this._numResources;
                this._nameHashesPtr = (int*)this._ums.PositionPointer;
                this._ums.Seek((long)num6, SeekOrigin.Current);
                byte* positionPointer = this._ums.PositionPointer;
            }
            if (this._ums == null)
            {
                this._namePositions = new int[this._numResources];
                for (int l = 0; l < this._numResources; l++)
                {
                    int num7 = this._store.ReadInt32();
                    if (num7 < 0)
                    {
                        throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
                    }
                    this._namePositions[l] = num7;
                }
            }
            else
            {
                if (((long)this._numResources & (long)((ulong)(-536870912))) != 0L)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
                }
                int num8 = 4 * this._numResources;
                this._namePositionsPtr = (int*)this._ums.PositionPointer;
                this._ums.Seek((long)num8, SeekOrigin.Current);
                byte* positionPointer2 = this._ums.PositionPointer;
            }
            this._dataSectionOffset = (long)this._store.ReadInt32();
            if (this._dataSectionOffset < 0L)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
            }
            this._nameSectionOffset = this._store.BaseStream.Position;
            if (this._dataSectionOffset < this._nameSectionOffset)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. Unable to read resources from this file because of invalid header information. Try regenerating the .resources file."));
            }
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._nameHashes, System.Resources.ResourceReader._namePositions, System.Resources.ResourceReader._nameSectionOffset, System.Resources.ResourceReader._numResources, System.Resources.ResourceReader._store, System.Resources.ResourceReader._typeNamePositions, System.Resources.ResourceReader._ums, System.IO.BinaryReader.BaseStream, System.Resources.ResourceManager.CompareNames(), System.Environment.GetResourceString(), int, System.L, long, System.Resources.ResourceManager.MagicNumber, System.Resources.ResourceManager.MscorlibName, System.IO.Stream.Position, System.IO.UnmanagedMemoryStream.PositionPointer, System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadString(), System.Resources.ResourceManager.ResReaderTypeName, System.IO.UnmanagedMemoryStream.Seek(), System.IO.Stream.Seek(), System.Resources.ResourceReader.SkipString(), and System.text.
Referenced by System.Resources.ResourceReader.ReadResources().