Terraria Decompiled: System.Resources.ResourceReader._LoadObjectV2
_LoadObjectV2()
object System.Resources.ResourceReader._LoadObjectV2 (int pos, out ResourceTypeCode typeCode) inline private
Definition at line 578 of file ResourceReader.cs.
        {
            this._store.BaseStream.Seek(this._dataSectionOffset + (long)pos, SeekOrigin.Begin);
            typeCode = (ResourceTypeCode)this._store.Read7BitEncodedInt();
            switch (typeCode)
            {
            case ResourceTypeCode.Null:
                return null;
            case ResourceTypeCode.String:
                return this._store.ReadString();
            case ResourceTypeCode.Boolean:
                return this._store.ReadBoolean();
            case ResourceTypeCode.Char:
                return (char)this._store.ReadUInt16();
            case ResourceTypeCode.Byte:
                return this._store.ReadByte();
            case ResourceTypeCode.SByte:
                return this._store.ReadSByte();
            case ResourceTypeCode.Int16:
                return this._store.ReadInt16();
            case ResourceTypeCode.UInt16:
                return this._store.ReadUInt16();
            case ResourceTypeCode.Int32:
                return this._store.ReadInt32();
            case ResourceTypeCode.UInt32:
                return this._store.ReadUInt32();
            case ResourceTypeCode.Int64:
                return this._store.ReadInt64();
            case ResourceTypeCode.UInt64:
                return this._store.ReadUInt64();
            case ResourceTypeCode.Single:
                return this._store.ReadSingle();
            case ResourceTypeCode.Double:
                return this._store.ReadDouble();
            case ResourceTypeCode.Decimal:
                return this._store.ReadDecimal();
            case ResourceTypeCode.DateTime:
                return DateTime.FromBinary(this._store.ReadInt64());
            case ResourceTypeCode.TimeSpan:
                return new TimeSpan(this._store.ReadInt64());
            case ResourceTypeCode.ByteArray:
            {
                int num = this._store.ReadInt32();
                if (num < 0)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified data length '{0}' is not a valid position in the stream.", new object[] { num }));
                }
                if (this._ums == null)
                {
                    if ((long)num > this._store.BaseStream.Length)
                    {
                        throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified data length '{0}' is not a valid position in the stream.", new object[] { num }));
                    }
                    return this._store.ReadBytes(num);
                }
                else
                {
                    if ((long)num > this._ums.Length - this._ums.Position)
                    {
                        throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified data length '{0}' is not a valid position in the stream.", new object[] { num }));
                    }
                    byte[] array = new byte[num];
                    this._ums.Read(array, 0, num);
                    return array;
                }
                break;
            }
            case ResourceTypeCode.Stream:
            {
                int num2 = this._store.ReadInt32();
                if (num2 < 0)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified data length '{0}' is not a valid position in the stream.", new object[] { num2 }));
                }
                if (this._ums == null)
                {
                    return new PinnedBufferMemoryStream(this._store.ReadBytes(num2));
                }
                if ((long)num2 > this._ums.Length - this._ums.Position)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified data length '{0}' is not a valid position in the stream.", new object[] { num2 }));
                }
                return new UnmanagedMemoryStream(this._ums.PositionPointer, (long)num2, (long)num2, FileAccess.Read);
            }
            }
            if (typeCode < ResourceTypeCode.StartOfUserTypes)
            {
                throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified type doesn't match the available data in the stream."));
            }
            int num3 = typeCode - ResourceTypeCode.StartOfUserTypes;
            return this.DeserializeObject(num3);
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._store, System.Resources.ResourceReader._ums, System.array, System.IO.BinaryReader.BaseStream, System.Resources.ResourceReader.DeserializeObject(), System.DateTime.FromBinary(), System.Environment.GetResourceString(), System.IO.Stream.Length, System.IO.UnmanagedMemoryStream.Length, System.IO.UnmanagedMemoryStream.PositionPointer, System.IO.UnmanagedMemoryStream.Read(), System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadDecimal(), System.IO.BinaryReader.ReadDouble(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadInt64(), System.IO.BinaryReader.ReadSByte(), System.IO.BinaryReader.ReadSingle(), System.IO.BinaryReader.ReadString(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), System.IO.BinaryReader.ReadUInt64(), System.IO.Stream.Seek(), and System.Resources.TimeSpan.
Referenced by System.Resources.ResourceReader.LoadObjectV2().