Terraria Decompiled: System.Resources.ResourceReader.AllocateStringForNameIndex
AllocateStringForNameIndex()
unsafe string System.Resources.ResourceReader.AllocateStringForNameIndex (int index, out int dataOffset) inline private
Definition at line 294 of file ResourceReader.cs.
        {
            long num = (long)this.GetNamePosition(index);
            int num2;
            byte[] array3;
            lock (this)
            {
                this._store.BaseStream.Seek(num + this._nameSectionOffset, SeekOrigin.Begin);
                num2 = this._store.Read7BitEncodedInt();
                if (num2 < 0)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. String length must be non-negative."));
                }
                if (this._ums != null)
                {
                    if (this._ums.Position > this._ums.Length - (long)num2)
                    {
                        throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file. String for name index '{0}' extends past the end of the file.", new object[] { index }));
                    }
                    char* positionPointer = (char*)this._ums.PositionPointer;
                    string text;
                    if (!BitConverter.IsLittleEndian)
                    {
                        byte* ptr = (byte*)positionPointer;
                        byte[] array = new byte[num2];
                        for (int i = 0; i < num2; i += 2)
{
                            array[i] = (ptr + i)[1];
                            array[i + 1] = ptr[i];
                        }
                        byte[] array2;
                        byte* ptr2;
                        if ((array2 = array) == null || array2.Length == 0)
{
                            ptr2 = null;
                        }
                        else
{
                            ptr2 = &array2[0];
                        }
                        text = new string((char*)ptr2, 0, num2 / 2);
                        array2 = null;
                    }
                    else
                    {
                        text = new string(positionPointer, 0, num2 / 2);
                    }
                    this._ums.Position += (long)num2;
                    dataOffset = this._store.ReadInt32();
                    if (dataOffset < 0 || (long)dataOffset >= this._store.BaseStream.Length - this._dataSectionOffset)
                    {
                        throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into data section.", new object[] { dataOffset }));
                    }
                    return text;
                }
                else
                {
                    array3 = new byte[num2];
                    int num3;
                    for (int j = num2; j > 0; j -= num3)
                    {
                        num3 = this._store.Read(array3, num2 - j, j);
                        if (num3 == 0)
{
                            throw new EndOfStreamException(Environment.GetResourceString("Corrupt .resources file. The resource name for name index {0} extends past the end of the stream.", new object[] { index }));
                        }
                    }
                    dataOffset = this._store.ReadInt32();
                    if (dataOffset < 0 || (long)dataOffset >= this._store.BaseStream.Length - this._dataSectionOffset)
                    {
                        throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into data section.", new object[] { dataOffset }));
                    }
                }
            }
            return Encoding.Unicode.GetString(array3, 0, num2);
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._nameSectionOffset, System.Resources.ResourceReader._store, System.Resources.ResourceReader._ums, System.array, System.IO.BinaryReader.BaseStream, System.Resources.ResourceReader.GetNamePosition(), System.Environment.GetResourceString(), System.Text.Encoding.GetString(), System.BitConverter.IsLittleEndian, System.IO.Stream.Length, long, System.IO.UnmanagedMemoryStream.Position, System.IO.UnmanagedMemoryStream.PositionPointer, System.IO.BinaryReader.Read(), System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadInt32(), System.IO.Stream.Seek(), System.text, and System.Text.Encoding.Unicode.