Terraria Decompiled: System.Resources.ResourceReader.GetResourceData
GetResourceData()
void System.Resources.ResourceReader.GetResourceData (string resourceName, out string resourceType, out byte[] resourceData) inline
Definition at line 847 of file ResourceReader.cs.
        {
            if (resourceName == null)
            {
                throw new ArgumentNullException("resourceName");
            }
            if (this._resCache == null)
            {
                throw new InvalidOperationException(Environment.GetResourceString("ResourceReader is closed."));
            }
            int[] array = new int[this._numResources];
            int num = this.FindPosForResource(resourceName);
            if (num == -1)
            {
                throw new ArgumentException(Environment.GetResourceString("The specified resource name \"{0}\" does not exist in the resource file.", new object[] { resourceName }));
            }
            lock (this)
            {
                for (int i = 0; i < this._numResources; i++)
                {
                    this._store.BaseStream.Position = this._nameSectionOffset + (long)this.GetNamePosition(i);
                    int num2 = this._store.Read7BitEncodedInt();
                    if (num2 < 0)
                    {
                        throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into name section.", new object[] { num2 }));
                    }
                    this._store.BaseStream.Position += (long)num2;
                    int num3 = this._store.ReadInt32();
                    if (num3 < 0 || (long)num3 >= this._store.BaseStream.Length - this._dataSectionOffset)
                    {
                        throw new FormatException(Environment.GetResourceString("Corrupt .resources file. Invalid offset '{0}' into data section.", new object[] { num3 }));
                    }
                    array[i] = num3;
                }
                Array.Sort<int>(array);
                int num4 = Array.BinarySearch<int>(array, num);
                int num5 = (int)(((num4 < this._numResources - 1) ? ((long)array[num4 + 1] + this._dataSectionOffset) : this._store.BaseStream.Length) - ((long)num + this._dataSectionOffset));
                this._store.BaseStream.Position = this._dataSectionOffset + (long)num;
                ResourceTypeCode resourceTypeCode = (ResourceTypeCode)this._store.Read7BitEncodedInt();
                if (resourceTypeCode < ResourceTypeCode.Null || resourceTypeCode >= ResourceTypeCode.StartOfUserTypes + this._typeTable.Length)
                {
                    throw new BadImageFormatException(Environment.GetResourceString("Corrupt .resources file.  The specified type doesn't exist."));
                }
                resourceType = this.TypeNameFromTypeCode(resourceTypeCode);
                num5 -= (int)(this._store.BaseStream.Position - (this._dataSectionOffset + (long)num));
                byte[] array2 = this._store.ReadBytes(num5);
                if (array2.Length != num5)
                {
                    throw new FormatException(Environment.GetResourceString("Corrupt .resources file. A resource name extends past the end of the stream."));
                }
                resourceData = array2;
            }
        }
References System.Resources.ResourceReader._dataSectionOffset, System.Resources.ResourceReader._numResources, System.Resources.ResourceReader._resCache, System.Resources.ResourceReader._store, System.array, System.IO.BinaryReader.BaseStream, System.Array.BinarySearch(), System.Resources.ResourceReader.FindPosForResource(), System.Resources.ResourceReader.GetNamePosition(), System.Environment.GetResourceString(), int, System.IO.Stream.Length, long, System.IO.Stream.Position, System.IO.BinaryReader.Read7BitEncodedInt(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadInt32(), System.Array.Sort(), and System.Resources.ResourceReader.TypeNameFromTypeCode().