Terraria Decompiled: Terraria.Recipe.CollectItemsFromChests
CollectItemsFromChests()
static void Terraria.Recipe.CollectItemsFromChests (Player player) inline static private
Definition at line 303 of file Recipe.cs.
        {
            Recipe._recipeChests.Clear();
            if (player.chest != -1)
            {
                Recipe._recipeChests.Add(player.GetCurrentContainer());
            }
            if (player.useVoidBag() && player.chest != -5)
            {
                Recipe._recipeChests.Add(player.bank4);
            }
            if (Player.Settings.CraftFromNearbyChests)
            {
                foreach (PositionedChest positionedChest in NearbyChests.GetBanksInRangeOf(player, 0f))
                {
                    if (!Recipe._recipeChests.Contains(positionedChest.chest))
                    {
                        Recipe._recipeChests.Add(positionedChest.chest);
                    }
                }
                foreach (PositionedChest positionedChest2 in NearbyChests.GetChestsInRangeOf(player.position, 0f))
                {
                    if (!positionedChest2.chest.IsLockedOrInUse())
                    {
                        Recipe._recipeChests.Add(positionedChest2.chest);
                    }
                }
            }
            foreach (Chest chest in Recipe._recipeChests)
            {
                Recipe.CollectItems(chest.item, chest.maxItems);
            }
        }
References Terraria.Recipe._recipeChests, Terraria.Player.bank4, Terraria.GameContent.PositionedChest.chest, Terraria.Player.chest, Terraria.Recipe.CollectItems(), Terraria.Player.Settings.CraftFromNearbyChests, Terraria.GameContent.NearbyChests.GetBanksInRangeOf(), Terraria.GameContent.NearbyChests.GetChestsInRangeOf(), Terraria.Player.GetCurrentContainer(), Terraria.Chest.IsLockedOrInUse(), Terraria.Chest.item, Terraria.Chest.maxItems, Terraria.Entity.position, and Terraria.Player.useVoidBag().
Referenced by Terraria.Recipe.CollectItemsToCraftWithFrom().