Terraria Decompiled: Terraria.Recipe.PlayerMeetsEnvironmentConditions
PlayerMeetsEnvironmentConditions()
bool Terraria.Recipe.PlayerMeetsEnvironmentConditions (Player player, List< string > missingObjects = null) inline
Definition at line 244 of file Recipe.cs.
        {
            bool flag = true;
            if (this.requiredTile >= 0 && !player.adjTile[this.requiredTile])
            {
                flag &= Recipe.AddMissing(Recipe.GetRequiredTileName(this.requiredTile), missingObjects);
            }
            if (this.needWater && !player.adjWaterSource)
            {
                flag &= Recipe.AddMissing(Lang.inter[53].Value, missingObjects);
            }
            if (this.needHoney && !player.adjHoney)
            {
                flag &= Recipe.AddMissing(Lang.inter[58].Value, missingObjects);
            }
            if (this.needLava && !player.adjLava)
            {
                flag &= Recipe.AddMissing(Lang.inter[56].Value, missingObjects);
            }
            if (this.needSnowBiome && !player.ZoneSnow)
            {
                flag &= Recipe.AddMissing(Lang.inter[123].Value, missingObjects);
            }
            if (this.needGraveyardBiome && !player.ZoneGraveyard)
            {
                flag &= Recipe.AddMissing(Lang.inter[124].Value, missingObjects);
            }
            if (this.needMechdusa)
            {
                flag &= SpecialSeedFeatures.Mechdusa;
            }
            if (this.needTorchGodsFavor && !player.unlockedBiomeTorches)
            {
                flag &= Recipe.AddMissing(Lang.inter[125].Value, missingObjects);
            }
            return flag;
        }
References Terraria.Recipe.AddMissing(), Terraria.Player.adjHoney, Terraria.Player.adjLava, Terraria.Player.adjTile, Terraria.Player.adjWaterSource, Terraria.Recipe.GetRequiredTileName(), Terraria.Lang.inter, Terraria.GameContent.SpecialSeedFeatures.Mechdusa, Terraria.Recipe.needGraveyardBiome, Terraria.Recipe.needHoney, Terraria.Recipe.needLava, Terraria.Recipe.needMechdusa, Terraria.Recipe.needSnowBiome, Terraria.Recipe.needTorchGodsFavor, Terraria.Recipe.needWater, Terraria.Recipe.requiredTile, Terraria.Player.unlockedBiomeTorches, Terraria.Player.ZoneGraveyard, and Terraria.Player.ZoneSnow.
Referenced by Terraria.GameContent.UI.NewCraftingUI.GetReasonForRecipeNotAvailable(), and Terraria.Recipe.UpdateRecipeList().