Terraria Decompiled: Terraria.Recipe.AddCoralFurniture
AddCoralFurniture()
static void Terraria.Recipe.AddCoralFurniture () inline static private
Definition at line 15871 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(5148, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5149, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5150, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5151, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5152, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5153, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5154, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5155, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5156, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5157, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5158, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5159, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 5306, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5160, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5161, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5163, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5164, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5165, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5166, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5168, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5306, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().