Terraria Decompiled: Terraria.Recipe.AddAetheriumFurniture
AddAetheriumFurniture()
static void Terraria.Recipe.AddAetheriumFurniture () inline static private
Definition at line 16160 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(5548, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5549, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5550, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5551, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5552, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5553, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5554, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5555, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5556, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5557, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5558, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5559, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 5398, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5560, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5561, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5563, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5564, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5565, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5566, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5568, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5398, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().