Terraria Decompiled: Terraria.Recipe.CreateReverseWallRecipes
CreateReverseWallRecipes()
static void Terraria.Recipe.CreateReverseWallRecipes () inline static private
Definition at line 16611 of file Recipe.cs.
        {
            int num = Recipe.numRecipes;
            for (int i = 0; i < num; i++)
            {
                if (Main.recipe[i].createItem.createWall > 0 && Main.recipe[i].requiredItem[1].type == 0 && Main.recipe[i].requiredItem[0].createWall == -1)
                {
                    Recipe.currentRecipe.createItem.SetDefaults(Main.recipe[i].requiredItem[0].type, null);
                    Recipe.currentRecipe.createItem.stack = Main.recipe[i].requiredItem[0].stack;
                    Recipe.currentRecipe.requiredItem[0].SetDefaults(Main.recipe[i].createItem.type, null);
                    Recipe.currentRecipe.requiredItem[0].stack = Main.recipe[i].createItem.stack;
                    Recipe.currentRecipe.requiredTile = Main.recipe[i].requiredTile;
                    Recipe.AddRecipe();
                    Recipe recipe = Main.recipe[Recipe.numRecipes - 1];
                    for (int j = Recipe.numRecipes - 2; j > i; j--)
                    {
                        Main.recipe[j + 1] = Main.recipe[j];
                    }
                    Main.recipe[i + 1] = recipe;
                    Main.recipe[i + 1].notDecraftable = true;
                }
            }
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Item.createWall, Terraria.Recipe.currentRecipe, Terraria.Recipe.notDecraftable, Terraria.Recipe.numRecipes, Terraria.Main.recipe, Terraria.Recipe.requiredItem, Terraria.Recipe.requiredTile, Terraria.Item.SetDefaults(), Terraria.Item.stack, and Terraria.Item.type.
Referenced by Terraria.Recipe.SetupRecipes().