Terraria Decompiled: Terraria.GameContent.UI.Elements.UIList.Add
Add()
virtual void Terraria.GameContent.UI.Elements.UIList.Add (UIElement item) inline virtual
Definition at line 53 of file UIList.cs.
        {
            this._items.Add(item);
            this._innerList.Append(item);
            this.UpdateOrder();
            this._innerList.Recalculate();
        }
References Terraria.GameContent.UI.Elements.UIList._innerList, Terraria.GameContent.UI.Elements.UIList._items, System.Collections.Generic.List< T >.Add(), Terraria.UI.UIElement.Append(), Terraria.UI.UIElement.Recalculate(), and Terraria.GameContent.UI.Elements.UIList.UpdateOrder().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryInfoPage.AddInfoToList(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.AddSpecialSeedOptions(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents(), Terraria.GameContent.UI.NewCraftingUI.BuildInfinitesMenuContents(), Terraria.GameContent.UI.States.UIReportsPage.BuildPage(), Terraria.GameContent.UI.States.UIResourcePackInfoMenu.BuildPage(), Terraria.GameContent.UI.States.UIWorldCreationAdvancedSecretSeedsList.BuildPage(), Terraria.GameContent.UI.States.UIManageControls.CreateElementGroup(), Terraria.GameContent.UI.States.UIManageControls.FillList(), Terraria.GameContent.UI.States.AWorkshopPublishInfoState< TPublishedObjectType >.FillUIList(), Terraria.GameContent.UI.States.UIAchievementsMenu.FilterList(), Terraria.GameContent.UI.States.UIAchievementsMenu.InitializePage(), Terraria.GameContent.UI.States.UICharacterCreation.MakeHairstylesMenu(), Terraria.GameContent.UI.States.UIDebugCommandsList.PopulateCommandsList(), Terraria.GameContent.UI.States.UIWorkshopSelectResourcePackToPublish.PopulateEntries(), Terraria.GameContent.UI.States.UIWorkshopSelectWorldToPublish.PopulateEntries(), Terraria.GameContent.UI.States.UIReportsPage.PopulateLogs(), Terraria.GameContent.UI.States.UIResourcePackSelectionMenu.PopulatePackList(), Terraria.GameContent.UI.States.UITextWrappingTest.ResetList(), Terraria.GameContent.UI.States.UIDebugCommandsList.searchbar_OnSearchContentsChanged(), Terraria.GameContent.UI.States.UIWorldGenDebug.UIWorldGenDebug(), Terraria.GameContent.UI.States.UIWorldGenDebug.UpdateFilter(), Terraria.GameContent.UI.States.UICharacterSelect.UpdatePlayersList(), Terraria.GameContent.UI.States.UIWorkshopWorldImport.UpdateWorldsList(), and Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList().