Terraria Decompiled: Terraria.GameContent.UI.Elements.UIList.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIList.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Definition at line 164 of file UIList.cs.
        {
            if (this._scrollbar != null)
            {
                this._innerList.Top.Set(-this._scrollbar.GetValue(), 0f);
            }
            this.Recalculate();
        }
References Terraria.GameContent.UI.Elements.UIList._innerList, Terraria.GameContent.UI.Elements.UIList._scrollbar, Terraria.GameContent.UI.Elements.UIScrollbar.GetValue(), Terraria.GameContent.UI.Elements.UIList.Recalculate(), Terraria.UI.StyleDimension.Set(), and Terraria.UI.UIElement.Top.