Terraria Decompiled: Terraria.Recipe.AddAshWoodFurnitureArmorAndItems
AddAshWoodFurnitureArmorAndItems()
static void Terraria.Recipe.AddAshWoodFurnitureArmorAndItems () inline static private
Definition at line 16054 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(5279, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 20 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5280, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 30 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5281, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 25 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5284, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 7 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5283, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5282, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 10 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5190, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5191, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5192, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5193, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5194, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5195, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5196, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5197, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5198, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5199, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5200, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5201, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 5215, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5202, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5203, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5205, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5206, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5207, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5208, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5210, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5215, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().