Terraria Decompiled: Terraria.Recipe.AddNebulaFurniture
AddNebulaFurniture()
static void Terraria.Recipe.AddNebulaFurniture () inline static private
Definition at line 15277 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4231, null);
            Recipe.currentRecipe.createItem.stack = 10;
            Recipe.currentRecipe.SetIngredients(new int[] { 3, 10, 3457, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4235, null);
            Recipe.currentRecipe.createItem.stack = 4;
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4187, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 14 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4188, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4189, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4190, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 16 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4191, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4192, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4193, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 4 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4194, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4195, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4196, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4197, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4198, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4231, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4199, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4200, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4202, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4203, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4204, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 8 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4205, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4207, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4231, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().