Terraria Decompiled: Terraria.Recipe.UpdateRecipeList
UpdateRecipeList()
static void Terraria.Recipe.UpdateRecipeList () inline static
Definition at line 142 of file Recipe.cs.
        {
            int focusRecipe = Main.focusRecipe;
            int num = Main.availableRecipe[Main.focusRecipe];
            Recipe.ClearAvailableRecipes();
            if (!Main.guideItem.IsAir && Main.guideItem.Name != "")
            {
                Recipe.CollectGuideRecipes();
                Recipe.TryRefocusingRecipe(num);
                Main.craftingUI.VisuallyRepositionRecipes(focusRecipe);
                return;
            }
            Player localPlayer = Main.LocalPlayer;
            Recipe.CollectItemsToCraftWithFrom(localPlayer);
            NewCraftingUI.RecipeFilter recipeFilterHack = CraftingUI.RecipeFilterHack;
            for (int i = 0; i < Recipe.maxRecipes; i++)
            {
                Recipe recipe = Main.recipe[i];
                if (recipe.createItem.type == 0)
                {
                    break;
                }
                if ((recipeFilterHack == null || recipeFilterHack.Accepts(recipe)) && recipe.PlayerMeetsEnvironmentConditions(localPlayer, null) && Recipe.CollectedEnoughItemsToCraft(recipe))
                {
                    Recipe.AddToAvailableRecipes(i);
                }
            }
            Recipe.TryRefocusingRecipe(num);
            Main.craftingUI.VisuallyRepositionRecipes(focusRecipe);
        }
References Terraria.GameContent.UI.NewCraftingUI.RecipeFilter.Accepts(), Terraria.Recipe.AddToAvailableRecipes(), Terraria.Main.availableRecipe, Terraria.Recipe.ClearAvailableRecipes(), Terraria.Recipe.CollectedEnoughItemsToCraft(), Terraria.Recipe.CollectGuideRecipes(), Terraria.Recipe.CollectItemsToCraftWithFrom(), Terraria.Main.craftingUI, Terraria.Recipe.createItem, Terraria.Main.focusRecipe, Terraria.Main.guideItem, Terraria.Item.IsAir, Terraria.Main.LocalPlayer, Terraria.Recipe.maxRecipes, Terraria.Item.Name, Terraria.Recipe.PlayerMeetsEnvironmentConditions(), Terraria.Main.recipe, Terraria.UI.CraftingUI.RecipeFilterHack, Terraria.Recipe.TryRefocusingRecipe(), Terraria.Item.type, and Terraria.UI.CraftingUI.VisuallyRepositionRecipes().
Referenced by Terraria.Main.DrawInventory(), and Terraria.GameContent.UI.NewCraftingUI.UpdateContents().