Terraria Decompiled: Terraria.Recipe.AddStardustFurniture
AddStardustFurniture()
static void Terraria.Recipe.AddStardustFurniture () inline static private
Definition at line 15370 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4232, null);
            Recipe.currentRecipe.createItem.stack = 10;
            Recipe.currentRecipe.SetIngredients(new int[] { 3, 10, 3459, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4236, null);
            Recipe.currentRecipe.createItem.stack = 4;
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4208, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 14 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4209, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4210, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4211, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 16 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4212, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4213, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4214, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 4 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4215, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4216, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4217, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4218, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4219, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4232, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4220, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4221, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4223, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4224, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4225, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 8 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4226, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4228, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4232, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().