Terraria Decompiled: Terraria.Recipe.ToString
ToString()
override string Terraria.Recipe.ToString () inline
Definition at line 26 of file Recipe.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            stringBuilder.AppendLine(this.createItem.ToString());
            foreach (Item item in this.requiredItem)
            {
                if (item.IsAir)
                {
                    break;
                }
                stringBuilder.AppendLine("  " + item.ToString());
            }
            foreach (int num in this.acceptedGroups)
            {
                if (num < 0)
                {
                    break;
                }
                stringBuilder.AppendLine("  " + RecipeGroup.recipeGroups[num]);
            }
            return stringBuilder.ToString();
        }
References Terraria.Recipe.acceptedGroups, System.Text.StringBuilder.AppendLine(), Terraria.Recipe.createItem, Terraria.Item.IsAir, System.item, Terraria.RecipeGroup.recipeGroups, Terraria.Recipe.requiredItem, System.Text.StringBuilder.ToString(), and Terraria.Item.ToString().