Terraria Decompiled: Terraria.Recipe.AddFallenStarFurniture
AddFallenStarFurniture()
static void Terraria.Recipe.AddFallenStarFurniture () inline static private
Definition at line 16242 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(5601, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5602, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5603, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5604, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5605, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5606, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5607, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5608, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5609, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5610, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5611, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5612, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 5622, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5613, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5614, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5616, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5617, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5618, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5619, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5621, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 5622, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().