Terraria Decompiled: Terraria.Recipe.AddSolarFurniture
AddSolarFurniture()
static void Terraria.Recipe.AddSolarFurniture () inline static private
Definition at line 15091 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4229, null);
            Recipe.currentRecipe.createItem.stack = 10;
            Recipe.currentRecipe.SetIngredients(new int[] { 3, 10, 3458, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4233, null);
            Recipe.currentRecipe.createItem.stack = 4;
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4145, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 14 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4146, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4147, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4148, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 16 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4149, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4150, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4151, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 4 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4152, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4153, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4154, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4155, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4156, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4229, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4157, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4158, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4160, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4161, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4162, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 8 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4163, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4165, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4229, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().