Terraria Decompiled: Terraria.Recipe.AddSandstoneFurniture
AddSandstoneFurniture()
static void Terraria.Recipe.AddSandstoneFurniture () inline static private
Definition at line 15702 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4720, null);
            Recipe.currentRecipe.createItem.stack = 2;
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4298, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4299, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4300, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4301, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4302, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4303, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4304, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4305, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4267, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4306, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4307, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4308, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4051, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4309, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4310, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4312, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4313, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4314, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4315, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4316, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4051, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().