Terraria Decompiled: Terraria.Recipe.AddSpiderFurniture
AddSpiderFurniture()
static void Terraria.Recipe.AddSpiderFurniture () inline static private
Definition at line 15463 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4139, null);
            Recipe.currentRecipe.createItem.stack = 10;
            Recipe.currentRecipe.SetIngredients(new int[] { 150, 10, 2607, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4140, null);
            Recipe.currentRecipe.createItem.stack = 4;
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3931, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3932, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3933, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3934, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3935, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3936, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3937, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3938, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3939, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3940, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3941, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3942, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4139, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3943, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3944, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3946, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3947, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3948, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3949, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4125, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4139, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().