Terraria Decompiled: Terraria.Recipe.AddLesionFurniture
AddLesionFurniture()
static void Terraria.Recipe.AddLesionFurniture () inline static private
Definition at line 15555 of file Recipe.cs.
        {
            int num = 3955;
            Recipe.currentRecipe.createItem.SetDefaults(3955, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 61, 2 });
            Recipe.currentRecipe.SetCraftingStation(218);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3975, null);
            Recipe.currentRecipe.SetIngredients(new int[] { num, 10 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3956, null);
            Recipe.currentRecipe.createItem.stack = 4;
            Recipe.currentRecipe.SetIngredients(new int[] { 3955, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3967, null);
            Recipe.currentRecipe.SetIngredients(new int[] { num, 6 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3963, null);
            Recipe.currentRecipe.SetIngredients(new int[] { num, 4 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3965, null);
            Recipe recipe = Recipe.currentRecipe;
            int[] array = new int[] { 0, 8, 22, 2 };
            array[0] = num;
            recipe.SetIngredients(array);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3974, null);
            Recipe.currentRecipe.SetIngredients(new int[] { num, 8 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3972, null);
            Recipe recipe2 = Recipe.currentRecipe;
            int[] array2 = new int[] { 0, 6, 206, 1 };
            array2[0] = num;
            recipe2.SetIngredients(array2);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3970, null);
            Recipe recipe3 = Recipe.currentRecipe;
            int[] array3 = new int[] { 0, 6, 8, 1 };
            array3[0] = num;
            recipe3.SetIngredients(array3);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3962, null);
            Recipe recipe4 = Recipe.currentRecipe;
            int[] array4 = new int[] { 0, 4, 8, 1 };
            array4[0] = num;
            recipe4.SetIngredients(array4);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3969, null);
            Recipe recipe5 = Recipe.currentRecipe;
            int[] array5 = new int[] { 0, 3, 8, 1 };
            array5[0] = num;
            recipe5.SetIngredients(array5);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3961, null);
            Recipe recipe6 = Recipe.currentRecipe;
            int[] array6 = new int[] { 0, 5, 8, 3 };
            array6[0] = num;
            recipe6.SetIngredients(array6);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3959, null);
            Recipe recipe7 = Recipe.currentRecipe;
            int[] array7 = new int[] { 0, 15, 225, 5 };
            array7[0] = num;
            recipe7.SetIngredients(array7);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3968, null);
            Recipe.currentRecipe.SetIngredients(new int[] { num, 16 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3960, null);
            Recipe recipe8 = Recipe.currentRecipe;
            int[] array8 = new int[] { 0, 20, 149, 10 };
            array8[0] = num;
            recipe8.SetIngredients(array8);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3966, null);
            Recipe recipe9 = Recipe.currentRecipe;
            int[] array9 = new int[] { 22, 3, 170, 6, 0, 10 };
            array9[4] = num;
            recipe9.SetIngredients(array9);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3973, null);
            Recipe recipe10 = Recipe.currentRecipe;
            int[] array10 = new int[] { 0, 5, 225, 2 };
            array10[0] = num;
            recipe10.SetIngredients(array10);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3971, null);
            Recipe recipe11 = Recipe.currentRecipe;
            int[] array11 = new int[] { 154, 4, 0, 15, 149, 1 };
            array11[2] = num;
            recipe11.SetIngredients(array11);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3958, null);
            Recipe.currentRecipe.SetIngredients(new int[] { num, 14 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(3964, null);
            Recipe recipe12 = Recipe.currentRecipe;
            int[] array12 = new int[] { 0, 4, 8, 4, 85, 1 };
            array12[0] = num;
            recipe12.SetIngredients(array12);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Wood);
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4126, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3955, 6 });
            Recipe.currentRecipe.SetCraftingStation(499);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), System.array, Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), Terraria.Recipe.SetIngredients(), and Terraria.ID.RecipeGroups.Wood.
Referenced by Terraria.Recipe.SetupRecipes().