Terraria Decompiled: Terraria.Recipe.SetIngredients
SetIngredients()
void Terraria.Recipe.SetIngredients (params int[] ingredients) inline
Definition at line 16636 of file Recipe.cs.
        {
            if (ingredients.Length == 1)
            {
                ingredients = new int[]
                {
                    ingredients[0],
                    1
                };
            }
            if (ingredients.Length % 2 != 0)
            {
                throw new Exception("Bad ingredients amount");
            }
            for (int i = 0; i < ingredients.Length; i += 2)
            {
                int num = i / 2;
                this.requiredItem[num].SetDefaults(ingredients[i], null);
                this.requiredItem[num].stack = ingredients[i + 1];
            }
        }
References Terraria.Recipe.requiredItem, Terraria.Item.SetDefaults(), and Terraria.Item.stack.
Referenced by Terraria.Recipe.AddAetheriumFurniture(), Terraria.Recipe.AddAshWoodFurnitureArmorAndItems(), Terraria.Recipe.AddBalloonFurniture(), Terraria.Recipe.AddBambooFurniture(), Terraria.Recipe.AddCoralFurniture(), Terraria.Recipe.AddFallenStarFurniture(), Terraria.Recipe.AddLesionFurniture(), Terraria.Recipe.AddNebulaFurniture(), Terraria.Recipe.AddSandstoneFurniture(), Terraria.Recipe.AddSolarFurniture(), Terraria.Recipe.AddSpiderFurniture(), Terraria.Recipe.AddStandardFurnitureSetRecipes(), Terraria.Recipe.AddStardustFurniture(), Terraria.Recipe.AddVortexFurniture(), and Terraria.Recipe.SetupRecipes().