Terraria Decompiled: Terraria.Recipe.AddStandardFurnitureSetRecipes
AddStandardFurnitureSetRecipes()
static void Terraria.Recipe.AddStandardFurnitureSetRecipes (int primaryMaterial, int bathtub, int bed, int bookcase, int candelabra, int candle, int chair, int chandelier, int chest, int clock, int door, int dresser, int lamp, int lantern, int piano, int sink, int sofa, int table, int toilet, int workbench, int fake_chest, int overrideStation = -1) inline static private
Definition at line 16445 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(bathtub, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 14 });
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(bed, null);
            Recipe recipe = Recipe.currentRecipe;
            int[] array = new int[] { 0, 15, 225, 5 };
            array[0] = primaryMaterial;
            recipe.SetIngredients(array);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(bookcase, null);
            Recipe recipe2 = Recipe.currentRecipe;
            int[] array2 = new int[] { 0, 20, 149, 10 };
            array2[0] = primaryMaterial;
            recipe2.SetIngredients(array2);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(dresser, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 16 });
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(candelabra, null);
            Recipe recipe3 = Recipe.currentRecipe;
            int[] array3 = new int[] { 0, 5, 8, 3 };
            array3[0] = primaryMaterial;
            recipe3.SetIngredients(array3);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(candle, null);
            Recipe recipe4 = Recipe.currentRecipe;
            int[] array4 = new int[] { 0, 4, 8, 1 };
            array4[0] = primaryMaterial;
            recipe4.SetIngredients(array4);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(chair, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 4 });
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(chandelier, null);
            Recipe recipe5 = Recipe.currentRecipe;
            int[] array5 = new int[] { 0, 4, 8, 4, 85, 1 };
            array5[0] = primaryMaterial;
            recipe5.SetIngredients(array5);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(chest, null);
            Recipe recipe6 = Recipe.currentRecipe;
            int[] array6 = new int[] { 0, 8, 22, 2 };
            array6[0] = primaryMaterial;
            recipe6.SetIngredients(array6);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(clock, null);
            Recipe recipe7 = Recipe.currentRecipe;
            int[] array7 = new int[] { 0, 10, 22, 3, 170, 6 };
            array7[0] = primaryMaterial;
            recipe7.SetIngredients(array7);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(door, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 6 });
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(lamp, null);
            Recipe recipe8 = Recipe.currentRecipe;
            int[] array8 = new int[] { 8, 1, 0, 3 };
            array8[2] = primaryMaterial;
            recipe8.SetIngredients(array8);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(lantern, null);
            Recipe recipe9 = Recipe.currentRecipe;
            int[] array9 = new int[] { 0, 6, 8, 1 };
            array9[0] = primaryMaterial;
            recipe9.SetIngredients(array9);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(piano, null);
            Recipe recipe10 = Recipe.currentRecipe;
            int[] array10 = new int[] { 0, 15, 154, 4, 149, 1 };
            array10[0] = primaryMaterial;
            recipe10.SetIngredients(array10);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(sink, null);
            Recipe recipe11 = Recipe.currentRecipe;
            int[] array11 = new int[] { 0, 6, 206, 1 };
            array11[0] = primaryMaterial;
            recipe11.SetIngredients(array11);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(sofa, null);
            Recipe recipe12 = Recipe.currentRecipe;
            int[] array12 = new int[] { 0, 5, 225, 2 };
            array12[0] = primaryMaterial;
            recipe12.SetIngredients(array12);
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(table, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 8 });
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(workbench, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 10 });
            if (overrideStation >= 0)
            {
                Recipe.currentRecipe.SetCraftingStation(overrideStation);
            }
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(toilet, null);
            Recipe.currentRecipe.SetIngredients(new int[] { primaryMaterial, 6 });
            Recipe.currentRecipe.SetCraftingStation((overrideStation >= 0) ? overrideStation : 106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), System.array, Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.AddBoulderFurniture(), Terraria.Recipe.AddCloudFurniture(), Terraria.Recipe.AddCrimtaneFurniture(), Terraria.Recipe.AddDemoniteFurniture(), Terraria.Recipe.AddEasterFurniture(), Terraria.Recipe.AddFeywoodFurniture(), Terraria.Recipe.AddFlinxFurFurniture(), Terraria.Recipe.AddForbiddenFurniture(), Terraria.Recipe.AddGothicFurniture(), Terraria.Recipe.AddHallowedFurniture(), Terraria.Recipe.AddHarpyFurniture(), Terraria.Recipe.AddJellyfishFurniture(), Terraria.Recipe.AddLibrarianFurniture(), Terraria.Recipe.AddMoonplateFurniture(), Terraria.Recipe.AddOfficeFurniture(), Terraria.Recipe.AddPineFurniture(), Terraria.Recipe.AddSnowFurniture(), Terraria.Recipe.AddSpikeFurniture(), Terraria.Recipe.AddStoneFurniture(), and Terraria.Recipe.AddWaterFurniture().