Terraria Decompiled: Terraria.Recipe.AddBalloonFurniture
AddBalloonFurniture()
static void Terraria.Recipe.AddBalloonFurniture () inline static private
Definition at line 15953 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(5169, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 14 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5170, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 15, 225, 5 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5171, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 20, 149, 10 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5172, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 16 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5173, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 5, 8, 3 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5174, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 4, 8, 1 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5175, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 4 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5176, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5177, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 8, 22, 2 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5178, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5179, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 6 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5180, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 3738, 3 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5181, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 6, 8, 1 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5182, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5184, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 6, 206, 1 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5185, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 5, 225, 2 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5186, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 8 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5187, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 10 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(5189, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 3738, 6 });
            Recipe.currentRecipe.RequireGroup(RecipeGroups.Balloons);
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.ID.RecipeGroups.Balloons, Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().