Terraria Decompiled: Terraria.Recipe.AddBambooFurniture
AddBambooFurniture()
static void Terraria.Recipe.AddBambooFurniture () inline static private
Definition at line 15789 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4566, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 14 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4567, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4568, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4569, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 16 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4570, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4571, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4572, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 4 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4573, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(16);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4574, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4575, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4576, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 6 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4577, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4564, 3 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4578, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4579, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4581, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4582, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4583, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 8 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4584, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 10 });
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4586, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4564, 6 });
            Recipe.currentRecipe.SetCraftingStation(106);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().