Terraria Decompiled: Terraria.Recipe.AddVortexFurniture
AddVortexFurniture()
static void Terraria.Recipe.AddVortexFurniture () inline static private
Definition at line 15184 of file Recipe.cs.
        {
            Recipe.currentRecipe.createItem.SetDefaults(4230, null);
            Recipe.currentRecipe.createItem.stack = 10;
            Recipe.currentRecipe.SetIngredients(new int[] { 3, 10, 3456, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4234, null);
            Recipe.currentRecipe.createItem.stack = 4;
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 1 });
            Recipe.currentRecipe.SetCraftingStation(18);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4166, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 14 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4167, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 15, 225, 5 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4168, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 20, 149, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4169, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 16 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4170, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 5, 8, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4171, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 4, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4172, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 4 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4173, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 4, 8, 4, 85, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4174, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 8, 22, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4175, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 10, 22, 3, 170, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.currentRecipe.RequireGroup(RecipeGroups.IronBar);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4176, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4177, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 8, 1, 4230, 3 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4178, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 6, 8, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4179, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 15, 154, 4, 149, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4181, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 6, 206, 1 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4182, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 5, 225, 2 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4183, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 8 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4184, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 10 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
            Recipe.currentRecipe.createItem.SetDefaults(4186, null);
            Recipe.currentRecipe.SetIngredients(new int[] { 4230, 6 });
            Recipe.currentRecipe.SetCraftingStation(412);
            Recipe.AddRecipe();
        }
References Terraria.Recipe.AddRecipe(), Terraria.Recipe.createItem, Terraria.Recipe.currentRecipe, Terraria.ID.RecipeGroups.IronBar, Terraria.Recipe.RequireGroup(), Terraria.Recipe.SetCraftingStation(), Terraria.Item.SetDefaults(), and Terraria.Recipe.SetIngredients().
Referenced by Terraria.Recipe.SetupRecipes().