Terraria Decompiled: Terraria.WorldBuilding.WorldGenConfiguration.FromEmbeddedPath
FromEmbeddedPath()
static WorldGenConfiguration Terraria.WorldBuilding.WorldGenConfiguration.FromEmbeddedPath (string path) inline static
Definition at line 50 of file WorldGenConfiguration.cs.
        {
            WorldGenConfiguration worldGenConfiguration;
            using (Stream manifestResourceStream = Assembly.GetExecutingAssembly().GetManifestResourceStream(path))
            {
                using (StreamReader streamReader = new StreamReader(manifestResourceStream))
                {
                    worldGenConfiguration = new WorldGenConfiguration(JsonConvert.DeserializeObject<JObject>(streamReader.ReadToEnd()));
                }
            }
            return worldGenConfiguration;
        }
References Newtonsoft.Json.JsonConvert.DeserializeObject(), System.Reflection.Assembly.GetExecutingAssembly(), System.Reflection.Assembly.GetManifestResourceStream(), System.IO.StreamReader.ReadToEnd(), and Terraria.WorldBuilding.WorldGenConfiguration.WorldGenConfiguration().
Referenced by Terraria.WorldGen.GenerateWorld().