Terraria Decompiled: BCrypt.Net.BCrypt.CryptRaw
CryptRaw()
byte[] BCrypt.Net.BCrypt.CryptRaw (byte[] inputBytes, byte[] saltBytes, int workFactor) inline package
Definition at line 120 of file BCrypt.cs.
        {
            uint[] array = new uint[BCrypt.BfCryptCiphertext.Length];
            Array.Copy(BCrypt.BfCryptCiphertext, array, BCrypt.BfCryptCiphertext.Length);
            int num = array.Length;
            if (workFactor < 4 || workFactor > 31)
            {
                throw new ArgumentException("Bad number of rounds", "workFactor");
            }
            if (saltBytes.Length != 16)
            {
                throw new ArgumentException("Bad salt Length", "saltBytes");
            }
            uint num2 = 1U << workFactor;
            if (num2 < 1U)
            {
                throw new ArgumentException("Bad number of rounds", "workFactor");
            }
            this.InitializeKey();
            this.EKSKey(saltBytes, inputBytes);
            int i = 0;
            while ((long)i != (long)((ulong)num2))
            {
                this.Key(inputBytes);
                this.Key(saltBytes);
                i++;
            }
            int j;
            for (i = 0; i < 64; i++)
            {
                for (j = 0; j < num >> 1; j++)
                {
                    this.Encipher(array, j << 1);
                }
            }
            byte[] array2 = new byte[num * 4];
            i = 0;
            j = 0;
            while (i < num)
            {
                array2[j++] = (byte)((array[i] >> 24) & 255U);
                array2[j++] = (byte)((array[i] >> 16) & 255U);
                array2[j++] = (byte)((array[i] >> 8) & 255U);
                array2[j++] = (byte)(array[i] & 255U);
                i++;
            }
            return array2;
        }
References System.array, System.Array.Copy(), BCrypt.Net.BCrypt.EKSKey(), BCrypt.Net.BCrypt.Encipher(), BCrypt.Net.BCrypt.InitializeKey(), BCrypt.Net.BCrypt.Key(), and System.U.