Terraria Decompiled: BCrypt.Net.BCrypt.Encipher
Encipher()
void BCrypt.Net.BCrypt.Encipher (uint[] blockArray, int offset) inline private
Definition at line 20 of file BCrypt.cs.
        {
            uint num = blockArray[offset];
            uint num2 = blockArray[offset + 1];
            num ^= this._p[0];
            uint num3 = 0U;
            while (num3 <= 14U)
            {
                uint num4 = this._s[(int)((num >> 24) & 255U)];
                num4 += this._s[(int)(256U | ((num >> 16) & 255U))];
                num4 ^= this._s[(int)(512U | ((num >> 8) & 255U))];
                num4 += this._s[(int)(768U | (num & 255U))];
                num2 ^= num4 ^ this._p[(int)(num3 += 1U)];
                num4 = this._s[(int)((num2 >> 24) & 255U)];
                num4 += this._s[(int)(256U | ((num2 >> 16) & 255U))];
                num4 ^= this._s[(int)(512U | ((num2 >> 8) & 255U))];
                num4 += this._s[(int)(768U | (num2 & 255U))];
                num ^= num4 ^ this._p[(int)(num3 += 1U)];
            }
            blockArray[offset] = num2 ^ this._p[17];
            blockArray[offset + 1] = num;
        }
References BCrypt.Net.BCrypt._p, BCrypt.Net.BCrypt._s, int, System.offset, and System.U.
Referenced by BCrypt.Net.BCrypt.CryptRaw(), BCrypt.Net.BCrypt.EKSKey(), and BCrypt.Net.BCrypt.Key().