Terraria Decompiled: Terraria.Social.WeGame.AchievementsSocialModule.GetEncryptionKey
GetEncryptionKey()
override byte[] Terraria.Social.WeGame.AchievementsSocialModule.GetEncryptionKey () inline
Definition at line 99 of file AchievementsSocialModule.cs.
        {
            RailComparableID railID = rail_api.RailFactory().RailPlayer().GetRailID();
            byte[] array = new byte[16];
            byte[] bytes = BitConverter.GetBytes(railID.id_);
            Array.Copy(bytes, array, 8);
            Array.Copy(bytes, 0, array, 8, 8);
            return array;
        }
References System.array, System.Array.Copy(), System.BitConverter.GetBytes(), rail.IRailPlayer.GetRailID(), rail.RailComparableID.id_, rail.rail_api.RailFactory(), and rail.IRailFactory.RailPlayer().