Terraria Decompiled: ReLogic.OS.OSX.PathService.MoveToRecycleBin
MoveToRecycleBin()
override void ReLogic.OS.OSX.PathService.MoveToRecycleBin (string path) inline
Definition at line 50 of file PathService.cs.
        {
            IntPtr intPtr = PathService.NativeMethods.objc_getClass("NSFileManager");
            IntPtr intPtr2 = PathService.NativeMethods.sel_registerName("defaultManager");
            IntPtr intPtr3 = PathService.NativeMethods.objc_msgSend(intPtr, intPtr2);
            IntPtr intPtr4 = PathService.NativeMethods.objc_getClass("NSURL");
            IntPtr intPtr5 = PathService.NativeMethods.sel_registerName("fileURLWithPath:");
            IntPtr intPtr6 = PathService.MarshalNSString(path);
            IntPtr intPtr7 = PathService.NativeMethods.objc_msgSend(intPtr4, intPtr5, intPtr6);
            IntPtr intPtr8 = PathService.NativeMethods.sel_registerName("trashItemAtURL:resultingItemURL:error:");
            PathService.NativeMethods.objc_msgSend(intPtr3, intPtr8, intPtr7, IntPtr.Zero, IntPtr.Zero);
        }
References ReLogic.OS.OSX.PathService.MarshalNSString(), ReLogic.OS.OSX.PathService.NativeMethods.objc_getClass(), ReLogic.OS.OSX.PathService.NativeMethods.objc_msgSend(), ReLogic.OS.OSX.PathService.NativeMethods.sel_registerName(), and System.IntPtr.Zero.