Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.AddMonths
AddMonths()
override DateTime System.Globalization.EastAsianLunisolarCalendar.AddMonths (DateTime time, int months) inline
Definition at line 355 of file EastAsianLunisolarCalendar.cs.
        {
            if (months < -120000 || months > 120000)
            {
                throw new ArgumentOutOfRangeException("months", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[] { -120000, 120000 }));
            }
            this.CheckTicksRange(time.Ticks);
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            this.TimeToLunar(time, ref num, ref num2, ref num3);
            int i = num2 + months;
            if (i > 0)
            {
                int num4 = (this.InternalIsLeapYear(num) ? 13 : 12);
                while (i - num4 > 0)
                {
                    i -= num4;
                    num++;
                    num4 = (this.InternalIsLeapYear(num) ? 13 : 12);
                }
                num2 = i;
            }
            else
            {
                while (i <= 0)
                {
                    int num5 = (this.InternalIsLeapYear(num - 1) ? 13 : 12);
                    i += num5;
                    num--;
                }
                num2 = i;
            }
            int num6 = this.InternalGetDaysInMonth(num, num2);
            if (num3 > num6)
            {
                num3 = num6;
            }
            DateTime dateTime = this.LunarToTime(time, num, num2, num3);
            Calendar.CheckAddResult(dateTime.Ticks, this.MinSupportedDateTime, this.MaxSupportedDateTime);
            return dateTime;
        }
References System.Globalization.Calendar.CheckAddResult(), System.Globalization.EastAsianLunisolarCalendar.CheckTicksRange(), System.Environment.GetResourceString(), System.Globalization.EastAsianLunisolarCalendar.InternalGetDaysInMonth(), System.Globalization.EastAsianLunisolarCalendar.InternalIsLeapYear(), System.Globalization.EastAsianLunisolarCalendar.LunarToTime(), System.DateTime.Ticks, and System.Globalization.EastAsianLunisolarCalendar.TimeToLunar().