Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.AddYears
AddYears()
override DateTime System.Globalization.EastAsianLunisolarCalendar.AddYears (DateTime time, int years) inline
Definition at line 399 of file EastAsianLunisolarCalendar.cs.
        {
            this.CheckTicksRange(time.Ticks);
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            this.TimeToLunar(time, ref num, ref num2, ref num3);
            num += years;
            if (num2 == 13 && !this.InternalIsLeapYear(num))
            {
                num2 = 12;
                num3 = this.InternalGetDaysInMonth(num, num2);
            }
            int num4 = this.InternalGetDaysInMonth(num, num2);
            if (num3 > num4)
            {
                num3 = num4;
            }
            DateTime dateTime = this.LunarToTime(time, num, num2, num3);
            Calendar.CheckAddResult(dateTime.Ticks, this.MinSupportedDateTime, this.MaxSupportedDateTime);
            return dateTime;
        }
References System.Globalization.Calendar.CheckAddResult(), System.Globalization.EastAsianLunisolarCalendar.CheckTicksRange(), System.Globalization.EastAsianLunisolarCalendar.InternalGetDaysInMonth(), System.Globalization.EastAsianLunisolarCalendar.InternalIsLeapYear(), System.Globalization.EastAsianLunisolarCalendar.LunarToTime(), System.DateTime.Ticks, and System.Globalization.EastAsianLunisolarCalendar.TimeToLunar().