Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.TimeToLunar
TimeToLunar()
void System.Globalization.EastAsianLunisolarCalendar.TimeToLunar (DateTime time, ref int year, ref int month, ref int day) inline package
Definition at line 345 of file EastAsianLunisolarCalendar.cs.
        {
            Calendar defaultInstance = GregorianCalendar.GetDefaultInstance();
            int year2 = defaultInstance.GetYear(time);
            int month2 = defaultInstance.GetMonth(time);
            int dayOfMonth = defaultInstance.GetDayOfMonth(time);
            this.GregorianToLunar(year2, month2, dayOfMonth, ref year, ref month, ref day);
        }
References System.Globalization.Calendar.GetDayOfMonth(), System.Globalization.GregorianCalendar.GetDefaultInstance(), System.Globalization.Calendar.GetMonth(), System.Globalization.Calendar.GetYear(), and System.Globalization.EastAsianLunisolarCalendar.GregorianToLunar().
Referenced by System.Globalization.EastAsianLunisolarCalendar.AddMonths(), System.Globalization.EastAsianLunisolarCalendar.AddYears(), System.Globalization.EastAsianLunisolarCalendar.GetDayOfMonth(), System.Globalization.EastAsianLunisolarCalendar.GetDayOfYear(), System.Globalization.EastAsianLunisolarCalendar.GetMonth(), System.Globalization.EastAsianLunisolarCalendar.GetSexagenaryYear(), and System.Globalization.EastAsianLunisolarCalendar.GetYear().