Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.CheckYearRange
CheckYearRange()
int System.Globalization.EastAsianLunisolarCalendar.CheckYearRange (int year, int era) inline package
Definition at line 161 of file EastAsianLunisolarCalendar.cs.
        {
            this.CheckEraRange(era);
            year = this.GetGregorianYear(year, era);
            if (year < this.MinCalendarYear || year > this.MaxCalendarYear)
            {
                throw new ArgumentOutOfRangeException("year", Environment.GetResourceString("Valid values are between {0} and {1}, inclusive.", new object[]
                {
                    this.MinEraCalendarYear(era),
                    this.MaxEraCalendarYear(era)
                }));
            }
            return year;
        }
References System.Globalization.EastAsianLunisolarCalendar.CheckEraRange(), System.Globalization.EastAsianLunisolarCalendar.GetGregorianYear(), System.Environment.GetResourceString(), and System.Globalization.EastAsianLunisolarCalendar.MaxCalendarYear.
Referenced by System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange(), System.Globalization.EastAsianLunisolarCalendar.GetDaysInYear(), System.Globalization.EastAsianLunisolarCalendar.GetLeapMonth(), System.Globalization.EastAsianLunisolarCalendar.GetMonthsInYear(), System.Globalization.EastAsianLunisolarCalendar.IsLeapYear(), and System.Globalization.EastAsianLunisolarCalendar.ToFourDigitYear().