Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.GregorianToLunar
GregorianToLunar()
void System.Globalization.EastAsianLunisolarCalendar.GregorianToLunar (int nSYear, int nSMonth, int nSDate, ref int nLYear, ref int nLMonth, ref int nLDate) inline package
Definition at line 253 of file EastAsianLunisolarCalendar.cs.
        {
            int i = ((EastAsianLunisolarCalendar.GregorianIsLeapYear(nSYear) == 1) ? EastAsianLunisolarCalendar.DaysToMonth366[nSMonth - 1] : EastAsianLunisolarCalendar.DaysToMonth365[nSMonth - 1]) + nSDate;
            nLYear = nSYear;
            int num;
            int num2;
            if (nLYear == this.MaxCalendarYear + 1)
            {
                nLYear--;
                i += ((EastAsianLunisolarCalendar.GregorianIsLeapYear(nLYear) == 1) ? 366 : 365);
                num = this.GetYearInfo(nLYear, 1);
                num2 = this.GetYearInfo(nLYear, 2);
            }
            else
            {
                num = this.GetYearInfo(nLYear, 1);
                num2 = this.GetYearInfo(nLYear, 2);
                if (nSMonth < num || (nSMonth == num && nSDate < num2))
                {
                    nLYear--;
                    i += ((EastAsianLunisolarCalendar.GregorianIsLeapYear(nLYear) == 1) ? 366 : 365);
                    num = this.GetYearInfo(nLYear, 1);
                    num2 = this.GetYearInfo(nLYear, 2);
                }
            }
            i -= EastAsianLunisolarCalendar.DaysToMonth365[num - 1];
            i -= num2 - 1;
            int num3 = 32768;
            int yearInfo = this.GetYearInfo(nLYear, 3);
            int num4 = (((yearInfo & num3) != 0) ? 30 : 29);
            nLMonth = 1;
            while (i > num4)
            {
                i -= num4;
                nLMonth++;
                num3 >>= 1;
                num4 = (((yearInfo & num3) != 0) ? 30 : 29);
            }
            nLDate = i;
        }
References System.Globalization.EastAsianLunisolarCalendar.DaysToMonth365, System.Globalization.EastAsianLunisolarCalendar.DaysToMonth366, System.Globalization.EastAsianLunisolarCalendar.GetYearInfo(), System.Globalization.EastAsianLunisolarCalendar.GregorianIsLeapYear(), and System.Globalization.EastAsianLunisolarCalendar.MaxCalendarYear.
Referenced by System.Globalization.EastAsianLunisolarCalendar.TimeToLunar().