Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.MaxEraCalendarYear
MaxEraCalendarYear()
int System.Globalization.EastAsianLunisolarCalendar.MaxEraCalendarYear (int era) inline package
Definition at line 108 of file EastAsianLunisolarCalendar.cs.
        {
            EraInfo[] calEraInfo = this.CalEraInfo;
            if (calEraInfo == null)
            {
                return this.MaxCalendarYear;
            }
            if (era == 0)
            {
                era = this.CurrentEraValue;
            }
            if (era == this.GetEra(this.MaxDate))
            {
                return this.GetYear(this.MaxCalendarYear, this.MaxDate);
            }
            for (int i = 0; i < calEraInfo.Length; i++)
            {
                if (era == calEraInfo[i].era)
                {
                    return calEraInfo[i].maxEraYear;
                }
            }
            throw new ArgumentOutOfRangeException("era", Environment.GetResourceString("Era value was not valid."));
        }
References System.Globalization.EastAsianLunisolarCalendar.CalEraInfo, System.Globalization.Calendar.CurrentEraValue, System.Globalization.Calendar.GetEra(), System.Environment.GetResourceString(), System.Globalization.EastAsianLunisolarCalendar.GetYear(), System.Globalization.EastAsianLunisolarCalendar.MaxCalendarYear, System.Globalization.EastAsianLunisolarCalendar.MaxDate, and System.Globalization.EraInfo.maxEraYear.