Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.ToDateTime
ToDateTime()
override DateTime System.Globalization.EastAsianLunisolarCalendar.ToDateTime (int year, int month, int day, int hour, int minute, int second, int millisecond, int era) inline
Definition at line 234 of file EastAsianLunisolarCalendar.cs.
        {
            year = this.CheckYearMonthRange(year, month, era);
            int num = this.InternalGetDaysInMonth(year, month);
            if (day < 1 || day > num)
            {
                throw new ArgumentOutOfRangeException("day", Environment.GetResourceString("Day must be between 1 and {0} for month {1}.", new object[] { num, month }));
            }
            int num2 = 0;
            int num3 = 0;
            int num4 = 0;
            if (this.LunarToGregorian(year, month, day, ref num2, ref num3, ref num4))
            {
                return new DateTime(num2, num3, num4, hour, minute, second, millisecond);
            }
            throw new ArgumentOutOfRangeException(null, Environment.GetResourceString("Year, Month, and Day parameters describe an un-representable DateTime."));
        }
References System.Globalization.EastAsianLunisolarCalendar.CheckYearMonthRange(), System.DateTime, System.Environment.GetResourceString(), System.Globalization.EastAsianLunisolarCalendar.InternalGetDaysInMonth(), and System.Globalization.EastAsianLunisolarCalendar.LunarToGregorian().