Terraria Decompiled: System.Globalization.EastAsianLunisolarCalendar.LunarToTime
LunarToTime()
DateTime System.Globalization.EastAsianLunisolarCalendar.LunarToTime (DateTime time, int year, int month, int day) inline package
Definition at line 335 of file EastAsianLunisolarCalendar.cs.
        {
            int num = 0;
            int num2 = 0;
            int num3 = 0;
            this.LunarToGregorian(year, month, day, ref num, ref num2, ref num3);
            return GregorianCalendar.GetDefaultInstance().ToDateTime(num, num2, num3, time.Hour, time.Minute, time.Second, time.Millisecond);
        }
References System.Globalization.GregorianCalendar.GetDefaultInstance(), System.DateTime.Hour, System.Globalization.EastAsianLunisolarCalendar.LunarToGregorian(), System.DateTime.Millisecond, System.DateTime.Minute, System.DateTime.Second, and System.Globalization.Calendar.ToDateTime().
Referenced by System.Globalization.EastAsianLunisolarCalendar.AddMonths(), and System.Globalization.EastAsianLunisolarCalendar.AddYears().