Terraria Decompiled: Steamworks.ISteamMatchmakingPlayersResponse.ISteamMatchmakingPlayersResponse
ISteamMatchmakingPlayersResponse()
Steamworks.ISteamMatchmakingPlayersResponse.ISteamMatchmakingPlayersResponse (ISteamMatchmakingPlayersResponse::AddPlayerToList onAddPlayerToList, ISteamMatchmakingPlayersResponse::PlayersFailedToRespond onPlayersFailedToRespond, ISteamMatchmakingPlayersResponse::PlayersRefreshComplete onPlayersRefreshComplete) inline
Definition at line 10 of file ISteamMatchmakingPlayersResponse.cs.
        {
            if (onAddPlayerToList == null || onPlayersFailedToRespond == null || onPlayersRefreshComplete == null)
            {
                throw new ArgumentNullException();
            }
            this.m_AddPlayerToList = onAddPlayerToList;
            this.m_PlayersFailedToRespond = onPlayersFailedToRespond;
            this.m_PlayersRefreshComplete = onPlayersRefreshComplete;
            this.m_VTable = new ISteamMatchmakingPlayersResponse.VTable
            {
                m_VTAddPlayerToList = new ISteamMatchmakingPlayersResponse.InternalAddPlayerToList(this.InternalOnAddPlayerToList),
                m_VTPlayersFailedToRespond = new ISteamMatchmakingPlayersResponse.InternalPlayersFailedToRespond(this.InternalOnPlayersFailedToRespond),
                m_VTPlayersRefreshComplete = new ISteamMatchmakingPlayersResponse.InternalPlayersRefreshComplete(this.InternalOnPlayersRefreshComplete)
            };
            this.m_pVTable = Marshal.AllocHGlobal(Marshal.SizeOf(typeof(ISteamMatchmakingPlayersResponse.VTable)));
            Marshal.StructureToPtr(this.m_VTable, this.m_pVTable, false);
            this.m_pGCHandle = GCHandle.Alloc(this.m_pVTable, 3);
        }
References System.Runtime.InteropServices.GCHandle.Alloc(), System.Runtime.InteropServices.Marshal.AllocHGlobal(), Steamworks.ISteamMatchmakingPlayersResponse.InternalAddPlayerToList(), Steamworks.ISteamMatchmakingPlayersResponse.InternalOnAddPlayerToList(), Steamworks.ISteamMatchmakingPlayersResponse.InternalOnPlayersFailedToRespond(), Steamworks.ISteamMatchmakingPlayersResponse.InternalOnPlayersRefreshComplete(), Steamworks.ISteamMatchmakingPlayersResponse.InternalPlayersFailedToRespond(), Steamworks.ISteamMatchmakingPlayersResponse.InternalPlayersRefreshComplete(), Steamworks.ISteamMatchmakingPlayersResponse.m_pVTable, Steamworks.ISteamMatchmakingPlayersResponse.m_VTable, System.Runtime.InteropServices.Marshal.SizeOf(), and System.Runtime.InteropServices.Marshal.StructureToPtr().