Terraria Decompiled: Terraria.Graphics.Light.LightingEngine.ProcessScan
ProcessScan()
void Terraria.Graphics.Light.LightingEngine.ProcessScan (Rectangle area) inline private
Definition at line 83 of file LightingEngine.cs.
        {
            area.Inflate(28, 28);
            this._workingProcessedArea = area;
            this._workingLightMap.SetSize(area.Width, area.Height);
            this._workingLightMap.NonVisiblePadding = 18;
            this._tileScanner.Update();
            this._tileScanner.ExportTo(area, this._workingLightMap, new TileLightScannerOptions
            {
                DrawInvisibleWalls = Main.ShouldShowInvisibleBlocksAndWalls()
            });
        }
References Terraria.Graphics.Light.LightingEngine._tileScanner, Terraria.Graphics.Light.LightingEngine._workingLightMap, Terraria.Graphics.Light.TileLightScanner.ExportTo(), Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Graphics.Light.LightMap.SetSize(), Terraria.Main.ShouldShowInvisibleBlocksAndWalls(), Terraria.Graphics.Light.TileLightScanner.Update(), and Microsoft.Xna.Framework.Rectangle.Width.
Referenced by Terraria.Graphics.Light.LightingEngine.ProcessArea().