Terraria Decompiled: Terraria.Graphics.Light.LightingEngine.ApplyPerFrameLights
ApplyPerFrameLights()
void Terraria.Graphics.Light.LightingEngine.ApplyPerFrameLights () inline private
Definition at line 180 of file LightingEngine.cs.
        {
            List<LightingEngine.PerFrameLight> list = this._perFrameLights;
            if (Main.gamePaused)
            {
                list = this._oldPerFrameLights;
            }
            for (int i = 0; i < list.Count; i++)
            {
                Point position = list[i].Position;
                if (this._workingProcessedArea.Contains(position))
                {
                    Vector3 color = list[i].Color;
                    Vector3 vector = this._workingLightMap[position.X - this._workingProcessedArea.X, position.Y - this._workingProcessedArea.Y];
                    Vector3.Max(ref vector, ref color, out color);
                    this._workingLightMap[position.X - this._workingProcessedArea.X, position.Y - this._workingProcessedArea.Y] = color;
                }
            }
            if (!CaptureManager.Instance.IsCapturing && !Main.gamePaused)
            {
                Utils.Swap<List<LightingEngine.PerFrameLight>>(ref this._perFrameLights, ref this._oldPerFrameLights);
                this._perFrameLights.Clear();
            }
        }
References Terraria.Graphics.Light.LightingEngine._oldPerFrameLights, Terraria.Graphics.Light.LightingEngine._perFrameLights, Terraria.Graphics.Light.LightingEngine._workingLightMap, Terraria.Graphics.Light.LightingEngine._workingProcessedArea, Microsoft.Xna.Framework.Rectangle.Contains(), Terraria.Main.gamePaused, Terraria.Graphics.Capture.CaptureManager.Instance, Terraria.Graphics.Capture.CaptureManager.IsCapturing, System.list, Microsoft.Xna.Framework.Vector3.Max(), Microsoft.Xna.Framework.Rectangle.X, and Microsoft.Xna.Framework.Rectangle.Y.
Referenced by Terraria.Graphics.Light.LightingEngine.ProcessBlur().