Terraria Decompiled: Terraria.Graphics.Light.LightingEngine.ExportToMiniMap
ExportToMiniMap()
void Terraria.Graphics.Light.LightingEngine.ExportToMiniMap () inline private
Definition at line 216 of file LightingEngine.cs.
        {
            if (!Main.mapEnabled)
            {
                return;
            }
            if (this._activeProcessedArea.Width <= 0 || this._activeProcessedArea.Height <= 0)
            {
                return;
            }
            Rectangle area = new Rectangle(this._activeProcessedArea.X + 28, this._activeProcessedArea.Y + 28, this._activeProcessedArea.Width - 56, this._activeProcessedArea.Height - 56);
            Rectangle rectangle = new Rectangle(0, 0, Main.maxTilesX, Main.maxTilesY);
            rectangle.Inflate(-40, -40);
            area = Rectangle.Intersect(area, rectangle);
            area = Rectangle.Intersect(area, MapHelper.sceneArea);
            FastParallel.For(area.Left, area.Right, delegate(int start, int end, object context)
            {
                for (int i = start; i < end; i++)
                {
                    for (int j = area.Top; j < area.Bottom; j++)
                    {
                        Vector3 vector = this._activeLightMap[i - this._activeProcessedArea.X, j - this._activeProcessedArea.Y];
                        float num = Math.Max(Math.Max(vector.X, vector.Y), vector.Z);
                        byte b = (byte)Math.Min(255, (int)(num * 255f));
                        Main.Map.UpdateLighting(i, j, b);
                    }
                }
            }, null);
            Main.updateMap = new Rectangle?(area);
        }
References Terraria.Graphics.Light.LightingEngine._activeLightMap, Terraria.Graphics.Light.LightingEngine._activeProcessedArea, Microsoft.Xna.Framework.Rectangle.Bottom, ReLogic.Threading.FastParallel.For(), Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Rectangle.Intersect(), Microsoft.Xna.Framework.Rectangle.Left, Terraria.Main.Map, Terraria.Main.mapEnabled, System.Math.Max(), Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, System.Math.Min(), Microsoft.Xna.Framework.Rectangle.Right, Terraria.Map.MapHelper.sceneArea, System.start, Microsoft.Xna.Framework.Rectangle.Top, Terraria.Map.WorldMap.UpdateLighting(), Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Rectangle.X, Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Rectangle.Y, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Terraria.Graphics.Light.LightingEngine.ProcessArea().