Terraria Decompiled: ReLogic.Content.AssetChangeWatcher.UpdateSources
UpdateSources()
void ReLogic.Content.AssetChangeWatcher.UpdateSources (IEnumerable< IContentSource > sources) inline
Definition at line 14 of file AssetChangeWatcher.cs.
        {
            Dictionary<FileSystemWatcher, IContentSource> watchers = this._watchers;
            lock (watchers)
            {
                if (this._disposed)
                {
                    throw new ObjectDisposedException("AssetFileWatchers");
                }
                List<FileSystemWatcher> list = Enumerable.ToList<FileSystemWatcher>(this._watchers.Keys);
                this._watchers.Clear();
                foreach (IContentSource contentSource in sources)
                {
                    string path = contentSource.FileWatcherPath;
                    if (path != null && Directory.Exists(path))
                    {
                        FileSystemWatcher fileSystemWatcher = Enumerable.FirstOrDefault<FileSystemWatcher>(list, (FileSystemWatcher e) => e.Path == path);
                        if (fileSystemWatcher == null)
{
                            fileSystemWatcher = base.NewWatcher(contentSource, path);
                        }
                        this._watchers[fileSystemWatcher] = contentSource;
                    }
                }
                foreach (FileSystemWatcher fileSystemWatcher2 in list)
                {
                    if (!this._watchers.ContainsKey(fileSystemWatcher2))
                    {
                        fileSystemWatcher2.Dispose();
                    }
                }
            }
        }
References ReLogic.Content.FileChangeWatcher< IContentSource >._disposed, ReLogic.Content.AssetChangeWatcher._watchers, System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), System.Collections.Generic.Dictionary< TKey, TValue >.ContainsKey(), System.IO.Directory.Exists(), ReLogic.Content.Sources.IContentSource.FileWatcherPath, System.Collections.Generic.Dictionary< TKey, TValue >.Keys, and System.list.
Referenced by ReLogic.Content.AssetRepository.EnableAssetWatcher(), and ReLogic.Content.AssetRepository.SetSources().