Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents
BuildInfinitesMenuContents()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildInfinitesMenuContents (UIElement totalContainer) inline private
Definition at line 118 of file UICreativeInfiniteItemsDisplay.cs.
        {
            UIPanel uipanel = UICreativeInfiniteItemsDisplay.CreateBasicPanel();
            totalContainer.Append(uipanel);
            uipanel.OnUpdate += this.Hover_OnUpdate;
            uipanel.OnMouseOver += this.Hover_OnMouseOver;
            uipanel.OnMouseOut += this.Hover_OnMouseOut;
            this._itemGrid = new UICreativeItemGrid();
            UIWrappedSearchBar uiwrappedSearchBar = new UIWrappedSearchBar(new Action(this.GoBackFromVirtualKeyboard), null, UIWrappedSearchBar.ColorTheme.Blue);
            uiwrappedSearchBar.CustomOpenVirtualKeyboard = new Action<UIState>(IngameFancyUI.OpenUIState);
            uiwrappedSearchBar.OnSearchContentsChanged += this.OnSearchContentsChanged;
            uiwrappedSearchBar.SetSearchSnapPoint("CreativeInfinitesSearch", 0, null, null);
            uipanel.Append(uiwrappedSearchBar);
            UIList uilist = new UIList
            {
                Width = new StyleDimension(-25f, 1f),
                Height = new StyleDimension(-28f, 1f),
                VAlign = 1f,
                HAlign = 0f
            };
            uipanel.Append(uilist);
            float num = 4f;
            UIScrollbar uiscrollbar = new UIScrollbar(UIScrollbar.ColorTheme.Blue)
            {
                Height = new StyleDimension(-28f - num * 2f, 1f),
                Top = new StyleDimension(-num, 0f),
                VAlign = 1f,
                HAlign = 1f
            };
            uipanel.Append(uiscrollbar);
            uilist.SetScrollbar(uiscrollbar);
            uilist.Add(this._itemGrid);
            UICreativeItemsInfiniteFilteringOptions uicreativeItemsInfiniteFilteringOptions = new UICreativeItemsInfiniteFilteringOptions(this._filterer, "CreativeInfinitesFilter", UICreativeItemsInfiniteFilteringOptions.ColorTheme.Blue);
            uicreativeItemsInfiniteFilteringOptions.OnClickingOption += this.filtersHelper_OnClickingOption;
            uicreativeItemsInfiniteFilteringOptions.Left = new StyleDimension(20f, 0f);
            totalContainer.Append(uicreativeItemsInfiniteFilteringOptions);
            uicreativeItemsInfiniteFilteringOptions.OnUpdate += this.Hover_OnUpdate;
            uicreativeItemsInfiniteFilteringOptions.OnMouseOver += this.Hover_OnMouseOver;
            uicreativeItemsInfiniteFilteringOptions.OnMouseOut += this.Hover_OnMouseOut;
        }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._filterer, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._itemGrid, System.Action(), Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.CreateBasicPanel(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.filtersHelper_OnClickingOption(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.GoBackFromVirtualKeyboard(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Hover_OnMouseOut(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Hover_OnMouseOver(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Hover_OnUpdate(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.OnSearchContentsChanged(), Terraria.UI.IngameFancyUI.OpenUIState(), Terraria.GameContent.UI.Elements.UIList.SetScrollbar(), Terraria.GameContent.UI.Elements.UIWrappedSearchBar.SetSearchSnapPoint(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage().