Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddSymetricalCogsPair
AddSymetricalCogsPair()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddSymetricalCogsPair (UIElement sacrificesContainer, Vector2 cogOFfsetsInPixels, string assetPath, List< UIImage > imagesList) inline private
Definition at line 379 of file UICreativeInfiniteItemsDisplay.cs.
        {
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>(assetPath, 1);
            cogOFfsetsInPixels += -asset.Size() / 2f;
            UIImage uiimage = new UIImage(asset)
            {
                NormalizedOrigin = Vector2.One / 2f,
                Left = new StyleDimension(cogOFfsetsInPixels.X, 0f),
                Top = new StyleDimension(cogOFfsetsInPixels.Y, 0f)
            };
            imagesList.Add(uiimage);
            sacrificesContainer.Append(uiimage);
            uiimage = new UIImage(asset)
            {
                NormalizedOrigin = Vector2.One / 2f,
                HAlign = 1f,
                Left = new StyleDimension(-cogOFfsetsInPixels.X, 0f),
                Top = new StyleDimension(cogOFfsetsInPixels.Y, 0f)
            };
            imagesList.Add(uiimage);
            sacrificesContainer.Append(uiimage);
        }
References System.Collections.Generic.List< T >.Add(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.Top, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu().