Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents
BuildSacrificeMenuContents()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents (UIElement totalContainer) inline private
Definition at line 160 of file UICreativeInfiniteItemsDisplay.cs.
        {
            UIPanel uipanel = UICreativeInfiniteItemsDisplay.CreateBasicPanel();
            uipanel.VAlign = 0.5f;
            uipanel.Height = new StyleDimension(170f, 0f);
            uipanel.Width = new StyleDimension(170f, 0f);
            uipanel.Top = default(StyleDimension);
            totalContainer.Append(uipanel);
            uipanel.OnUpdate += this.Hover_OnUpdate;
            uipanel.OnMouseOver += this.Hover_OnMouseOver;
            uipanel.OnMouseOut += this.Hover_OnMouseOut;
            this.AddCogsForSacrificeMenu(uipanel);
            this._pistonParticleAsset = Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_Spark", 1);
            float num = 0f;
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_Slots", 1))
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                Top = new StyleDimension(-20f, 0f),
                Left = new StyleDimension(num, 0f)
            };
            uipanel.Append(uiimage);
            Asset<Texture2D> asset = Main.Assets.Request<Texture2D>("Images/UI/Creative/Research_FramedPistons", 1);
            UIImageFramed uiimageFramed = new UIImageFramed(asset, asset.Frame(1, 9, 0, 0, 0, 0))
            {
                HAlign = 0.5f,
                VAlign = 0.5f,
                Top = new StyleDimension(-20f, 0f),
                Left = new StyleDimension(num, 0f),
                IgnoresMouseInteraction = true
            };
            uipanel.Append(uiimageFramed);
            this._sacrificePistons = uiimageFramed;
            UIParticleLayer uiparticleLayer = new UIParticleLayer
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(0f, 1f),
                AnchorPositionOffsetByPercents = Vector2.One / 2f,
                AnchorPositionOffsetByPixels = Vector2.Zero
            };
            this._pistonParticleSystem = uiparticleLayer;
            uiimageFramed.Append(this._pistonParticleSystem);
            UIElement uielement = Main.CreativeMenu.ProvideItemSlotElement(0);
            uielement.HAlign = 0.5f;
            uielement.VAlign = 0.5f;
            uielement.Top = new StyleDimension(-15f, 0f);
            uielement.Left = new StyleDimension(num, 0f);
            uielement.SetSnapPoint("CreativeSacrificeSlot", 0, null, null);
            uiimage.Append(uielement);
            UIText uitext = new UIText("(0/50)", 0.8f, false)
            {
                Top = new StyleDimension(10f, 0f),
                Left = new StyleDimension(num, 0f),
                HAlign = 0.5f,
                VAlign = 0.5f,
                IgnoresMouseInteraction = true
            };
            uitext.OnUpdate += this.descriptionText_OnUpdate;
            uipanel.Append(uitext);
            UIPanel uipanel2 = new UIPanel
            {
                Top = new StyleDimension(0f, 0f),
                Left = new StyleDimension(num, 0f),
                HAlign = 0.5f,
                VAlign = 1f,
                Width = new StyleDimension(124f, 0f),
                Height = new StyleDimension(30f, 0f)
            };
            UIText uitext2 = new UIText(Language.GetText("CreativePowers.ConfirmInfiniteItemSacrifice"), 0.8f, false)
            {
                IgnoresMouseInteraction = true,
                HAlign = 0.5f,
                VAlign = 0.5f
            };
            uipanel2.Append(uitext2);
            uipanel2.SetSnapPoint("CreativeSacrificeConfirm", 0, null, null);
            uipanel2.OnLeftClick += this.sacrificeButton_OnClick;
            uipanel2.OnMouseOver += this.FadedMouseOver;
            uipanel2.OnMouseOut += this.FadedMouseOut;
            uipanel2.OnUpdate += this.research_OnUpdate;
            uipanel.Append(uipanel2);
            uipanel.OnUpdate += this.sacrificeWindow_OnUpdate;
        }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._pistonParticleSystem, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu(), Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.CreateBasicPanel(), Terraria.Main.CreativeMenu, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.descriptionText_OnUpdate(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.FadedMouseOut(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.FadedMouseOver(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Hover_OnMouseOut(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Hover_OnMouseOver(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.Hover_OnUpdate(), Terraria.UI.UIElement.IgnoresMouseInteraction, Terraria.UI.UIElement.Left, Terraria.GameContent.Creative.CreativeUI.ProvideItemSlotElement(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.research_OnUpdate(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.sacrificeButton_OnClick(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.sacrificeWindow_OnUpdate(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage().