Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay
UICreativeInfiniteItemsDisplay()
Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay () inline
Definition at line 21 of file UICreativeInfiniteItemsDisplay.cs.
        {
            this._filterer = new EntryFilterer<Item, IItemEntryFilter>();
            List<IItemEntryFilter> list = new List<IItemEntryFilter>
            {
                new ItemFilters.Weapon(),
                new ItemFilters.Armor(),
                new ItemFilters.Vanity(),
                new ItemFilters.BuildingBlock(),
                new ItemFilters.Furniture(),
                new ItemFilters.Accessories(),
                new ItemFilters.MiscAccessories(),
                new ItemFilters.Consumables(),
                new ItemFilters.Tools(),
                new ItemFilters.Materials()
            };
            List<IItemEntryFilter> list2 = new List<IItemEntryFilter>();
            list2.AddRange(list);
            list2.Add(new ItemFilters.MiscFallback(list));
            this._filterer.AddFilters(list2);
            this._filterer.SetSearchFilterObject<ItemFilters.BySearch>(new ItemFilters.BySearch());
            this._sorter = new EntrySorter<Item, ICreativeItemSortStep>();
            this._sorter.AddSortSteps(new List<ICreativeItemSortStep>
            {
                new SortingSteps.ByUnlockStatus(),
                new SortingSteps.ByCreativeSortingId(),
                new SortingSteps.Alphabetical()
            });
            this.BuildPage();
        }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._filterer, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sorter, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage(), and System.list.