Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate
UICreativeInfiniteItemsDisplay_OnUpdate()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UICreativeInfiniteItemsDisplay_OnUpdate (UIElement affectedElement) inline private
Definition at line 524 of file UICreativeInfiniteItemsDisplay.cs.
        {
            base.RemoveAllChildren();
            CreativeUnlocksTracker localPlayerCreativeTracker = Main.LocalPlayerCreativeTracker;
            if (this._lastTrackerCheckedForEdits != localPlayerCreativeTracker)
            {
                this._lastTrackerCheckedForEdits = localPlayerCreativeTracker;
                this._lastCheckedVersionForEdits = -1;
            }
            int lastEditId = localPlayerCreativeTracker.ItemSacrifices.LastEditId;
            if (this._lastCheckedVersionForEdits != lastEditId)
            {
                this._lastCheckedVersionForEdits = lastEditId;
                this.UpdateContents();
            }
            if (this._showSacrificesInsteadOfInfinites)
            {
                base.Append(this._containerSacrifice);
            }
            else
            {
                base.Append(this._containerInfinites);
            }
            this.UpdateSacrificeAnimation();
        }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._containerInfinites, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._containerSacrifice, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._lastCheckedVersionForEdits, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._lastTrackerCheckedForEdits, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._showSacrificesInsteadOfInfinites, Terraria.GameContent.Creative.CreativeUnlocksTracker.ItemSacrifices, Terraria.GameContent.Creative.ItemsSacrificedUnlocksTracker.LastEditId, Terraria.Main.LocalPlayerCreativeTracker, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateContents(), and Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.UpdateSacrificeAnimation().
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildPage().