Terraria Decompiled: Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu
AddCogsForSacrificeMenu()
void Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddCogsForSacrificeMenu (UIElement sacrificesContainer) inline private
Definition at line 267 of file UICreativeInfiniteItemsDisplay.cs.
        {
            UIElement uielement = new UIElement();
            uielement.IgnoresMouseInteraction = true;
            UICreativeInfiniteItemsDisplay.SetBasicSizesForCreativeSacrificeOrInfinitesPanel(uielement);
            uielement.VAlign = 0.5f;
            uielement.Height = new StyleDimension(170f, 0f);
            uielement.Width = new StyleDimension(280f, 0f);
            uielement.Top = default(StyleDimension);
            uielement.SetPadding(0f);
            sacrificesContainer.Append(uielement);
            Vector2 vector = new Vector2(-10f, -10f);
            this.AddSymetricalCogsPair(uielement, new Vector2(22f, 1f) + vector, "Images/UI/Creative/Research_GearC", this._sacrificeCogsSmall);
            this.AddSymetricalCogsPair(uielement, new Vector2(1f, 28f) + vector, "Images/UI/Creative/Research_GearB", this._sacrificeCogsMedium);
            this.AddSymetricalCogsPair(uielement, new Vector2(5f, 5f) + vector, "Images/UI/Creative/Research_GearA", this._sacrificeCogsBig);
        }
References Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeCogsBig, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeCogsMedium, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay._sacrificeCogsSmall, Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.AddSymetricalCogsPair(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.SetBasicSizesForCreativeSacrificeOrInfinitesPanel(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.UIElement(), and Microsoft.Xna.Framework.Graphics.Vector2.
Referenced by Terraria.GameContent.UI.Elements.UICreativeInfiniteItemsDisplay.BuildSacrificeMenuContents().