Terraria Decompiled: System.Globalization.CharUnicodeInfo.InternalGetNumericValue
InternalGetNumericValue()
static unsafe double System.Globalization.CharUnicodeInfo.InternalGetNumericValue (int ch) inline static package
Definition at line 69 of file CharUnicodeInfo.cs.
        {
            int num = ch >> 8;
            if (num >= CharUnicodeInfo.NumericLevel1Index.Length)
            {
                return -1.0;
            }
            num = (int)(*CharUnicodeInfo.NumericLevel1Index[num]);
            num = (int)(*CharUnicodeInfo.NumericLevel2Index[(num << 4) + ((ch >> 4) & 15)]);
            num = (int)(*CharUnicodeInfo.NumericLevel3Index[(num << 4) + (ch & 15)]);
            ref byte ptr = ref Unsafe.AsRef<byte>(CharUnicodeInfo.NumericValues[num * 8]);
            if (BitConverter.IsLittleEndian)
            {
                return Unsafe.ReadUnaligned<double>(ref ptr);
            }
            return BitConverter.Int64BitsToDouble(BinaryPrimitives.ReverseEndianness(Unsafe.ReadUnaligned<long>(ref ptr)));
        }
References int, System.BitConverter.Int64BitsToDouble(), System.BitConverter.IsLittleEndian, System.Globalization.CharUnicodeInfo.NumericLevel1Index, System.Globalization.CharUnicodeInfo.NumericLevel2Index, System.Globalization.CharUnicodeInfo.NumericLevel3Index, System.Globalization.CharUnicodeInfo.NumericValues, and System.Buffers.Binary.BinaryPrimitives.ReverseEndianness().
Referenced by System.Globalization.CharUnicodeInfo.GetNumericValue(), and System.Globalization.CharUnicodeInfo.GetNumericValue().