Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffect.FromStream
FromStream()
static SoundEffect Microsoft.Xna.Framework.Audio.SoundEffect.FromStream (Stream stream) inline static
Definition at line 268 of file SoundEffect.cs.
        {
            int num = 0;
            int num2 = 0;
            ushort num4;
            ushort num5;
            uint num6;
            uint num7;
            ushort num8;
            ushort num9;
            byte[] array;
            using (BinaryReader binaryReader = new BinaryReader(stream))
            {
                if (new string(binaryReader.ReadChars(4)) != "RIFF")
                {
                    throw new NotSupportedException("Specified stream is not a wave file.");
                }
                binaryReader.ReadUInt32();
                if (new string(binaryReader.ReadChars(4)) != "WAVE")
                {
                    throw new NotSupportedException("Specified stream is not a wave file.");
                }
                string text = new string(binaryReader.ReadChars(4));
                while (text != "fmt ")
                {
                    binaryReader.ReadBytes(binaryReader.ReadInt32());
                    text = new string(binaryReader.ReadChars(4));
                }
                int num3 = binaryReader.ReadInt32();
                num4 = binaryReader.ReadUInt16();
                num5 = binaryReader.ReadUInt16();
                num6 = binaryReader.ReadUInt32();
                num7 = binaryReader.ReadUInt32();
                num8 = binaryReader.ReadUInt16();
                num9 = binaryReader.ReadUInt16();
                if (num3 > 16)
                {
                    binaryReader.ReadBytes(num3 - 16);
                }
                string text2 = new string(binaryReader.ReadChars(4));
                while (text2.ToLowerInvariant() != "data")
                {
                    binaryReader.ReadBytes(binaryReader.ReadInt32());
                    text2 = new string(binaryReader.ReadChars(4));
                }
                if (text2 != "data")
                {
                    throw new NotSupportedException("Specified wave file is not supported.");
                }
                int num10 = binaryReader.ReadInt32();
                array = binaryReader.ReadBytes(num10);
                while (binaryReader.PeekChar() != -1)
                {
                    char[] array2 = binaryReader.ReadChars(4);
                    if (array2.Length < 4)
                    {
                        break;
                    }
                    byte[] array3 = binaryReader.ReadBytes(4);
                    if (array3.Length < 4)
                    {
                        break;
                    }
                    string text3 = new string(array2);
                    int num11 = BitConverter.ToInt32(array3, 0);
                    if (text3 == "smpl")
                    {
                        binaryReader.ReadUInt32();
                        binaryReader.ReadUInt32();
                        binaryReader.ReadUInt32();
                        binaryReader.ReadUInt32();
                        binaryReader.ReadUInt32();
                        binaryReader.ReadUInt32();
                        binaryReader.ReadUInt32();
                        uint num12 = binaryReader.ReadUInt32();
                        int num13 = binaryReader.ReadInt32();
                        int num14 = 0;
                        while ((long)num14 < (long)((ulong)num12))
{
                            binaryReader.ReadUInt32();
                            binaryReader.ReadUInt32();
                            int num15 = binaryReader.ReadInt32();
                            int num16 = binaryReader.ReadInt32();
                            binaryReader.ReadUInt32();
                            binaryReader.ReadUInt32();
                            if (num14 == 0)
{
                                num = num15;
                                num2 = num16;
                            }
                            num14++;
                        }
                        if (num13 != 0)
{
                            binaryReader.ReadBytes(num13);
                        }
                    }
                    else
                    {
                        binaryReader.ReadBytes(num11);
                    }
                }
            }
            return new SoundEffect(null, array, 0, array.Length, null, num4, num5, num6, num7, num8, num9, num, num2 - num);
        }
References System.array, System.IO.BinaryReader.PeekChar(), System.IO.BinaryReader.ReadBytes(), System.IO.BinaryReader.ReadChars(), System.IO.BinaryReader.ReadInt32(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), Microsoft.Xna.Framework.Audio.SoundEffect.SoundEffect(), System.text, and System.BitConverter.ToInt32().
Referenced by Microsoft.Xna.Framework.Content.ContentManager.ReadAsset< T >(), and Terraria.Audio.SoundEngine.TestAudioSupport().