Terraria Decompiled: Microsoft.Xna.Framework.Audio.SoundEffect.Dispose
Dispose()
void Microsoft.Xna.Framework.Audio.SoundEffect.Dispose () inline
Implements System.IDisposable.
Definition at line 205 of file SoundEffect.cs.
        {
            if (!this.IsDisposed)
            {
                WeakReference[] array = this.Instances.ToArray();
                for (int i = 0; i < array.Length; i++)
                {
                    object target = array[i].Target;
                    if (target != null)
                    {
                        (target as IDisposable).Dispose();
                    }
                }
                this.Instances.Clear();
                FNAPlatform.Free(this.formatPtr);
                FNAPlatform.Free(this.handle.pAudioData);
                this.IsDisposed = true;
            }
        }
References System.array, System.Collections.Generic.List< T >.Clear(), Microsoft.Xna.Framework.Audio.SoundEffect.Dispose(), Microsoft.Xna.Framework.Audio.SoundEffect.formatPtr, Microsoft.Xna.Framework.FNAPlatform.Free, Microsoft.Xna.Framework.Audio.SoundEffect.handle, Microsoft.Xna.Framework.Audio.SoundEffect.Instances, Microsoft.Xna.Framework.Audio.SoundEffect.IsDisposed, and System.Collections.Generic.List< T >.ToArray().
Referenced by Microsoft.Xna.Framework.Audio.SoundEffect.Dispose(), Microsoft.Xna.Framework.Audio.SoundEffect.FAudioContext.ProgramExit(), and Microsoft.Xna.Framework.Audio.SoundEffect.~SoundEffect().