Terraria Decompiled: Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.EyeballShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 102 of file EyeballShader.cs.
        {
            Vector2 vector = new Vector2(1.5f, 0.5f);
            Vector2 vector2 = vector + this._pupilOffset;
            for (int i = 0; i < fragment.Count; i++)
            {
                Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
                Vector2 vector3 = canvasPositionOfIndex - vector;
                Vector4 vector4 = Vector4.One;
                float num = (vector2 - canvasPositionOfIndex).Length();
                for (int j = 1; j < EyeballShader.Rings.Length; j++)
                {
                    EyeballShader.Ring ring = EyeballShader.Rings[j];
                    EyeballShader.Ring ring2 = EyeballShader.Rings[j - 1];
                    if (num < ring.Distance)
                    {
                        vector4 = Vector4.Lerp(ring2.Color, ring.Color, (num - ring2.Distance) / (ring.Distance - ring2.Distance));
                        break;
                    }
                }
                float num2 = (float)Math.Sqrt((double)(1f - 0.4f * vector3.Y * vector3.Y)) * 5f;
                float num3 = Math.Abs(vector3.X) - num2 * (1.1f * this._eyelidProgress - 0.1f);
                if (num3 > 0f)
                {
                    vector4 = Vector4.Lerp(vector4, this._eyelidColor, Math.Min(1f, num3 * 10f));
                }
                fragment.SetColor(i, vector4);
            }
        }
References Terraria.GameContent.RGB.EyeballShader._eyelidColor, Terraria.GameContent.RGB.EyeballShader._pupilOffset, System.Math.Abs(), Terraria.GameContent.RGB.EyeballShader.Ring.Color, ReLogic.Peripherals.RGB.Fragment.Count, Terraria.GameContent.RGB.EyeballShader.Ring.Distance, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Min(), Microsoft.Xna.Framework.Vector4.One, Terraria.GameContent.RGB.EyeballShader.Rings, ReLogic.Peripherals.RGB.Fragment.SetColor(), System.Math.Sqrt(), Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.