Terraria Decompiled: System.Text.EncodingNLS.GetChars
GetChars() [2/2]
unsafe override int System.Text.EncodingNLS.GetChars (byte[] bytes, int byteIndex, int byteCount, char[] chars, int charIndex) inline
Definition at line 209 of file EncodingNLS.cs.
        {
            if (bytes == null || chars == null)
            {
                throw new ArgumentNullException((bytes == null) ? "bytes" : "chars", "Array cannot be null.");
            }
            if (byteIndex < 0 || byteCount < 0)
            {
                throw new ArgumentOutOfRangeException((byteIndex < 0) ? "byteIndex" : "byteCount", "Non-negative number required.");
            }
            if (bytes.Length - byteIndex < byteCount)
            {
                throw new ArgumentOutOfRangeException("bytes", "Index and count must refer to a location within the buffer.");
            }
            if (charIndex < 0 || charIndex > chars.Length)
            {
                throw new ArgumentOutOfRangeException("charIndex", "Index was out of range. Must be non-negative and less than the size of the collection.");
            }
            if (byteCount == 0)
            {
                return 0;
            }
            int num = chars.Length - charIndex;
            byte* ptr;
            if (bytes == null || bytes.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &bytes[0];
            }
            fixed (char* reference = MemoryMarshal.GetReference<char>(chars))
            {
                char* ptr2 = reference;
                return this.GetChars(ptr + byteIndex, byteCount, ptr2 + charIndex, num, null);
            }
        }
References System.Text.EncodingNLS.GetChars().
Referenced by System.Text.EncodingNLS.GetChars(), and System.Text.EncodingNLS.GetChars().