Terraria Decompiled: System.Text.EncodingNLS.GetCharCount
GetCharCount() [2/2]
unsafe override int System.Text.EncodingNLS.GetCharCount (byte[] bytes, int index, int count) inline
Definition at line 164 of file EncodingNLS.cs.
        {
            if (bytes == null)
            {
                throw new ArgumentNullException("bytes", "Array cannot be null.");
            }
            if (index < 0 || count < 0)
            {
                throw new ArgumentOutOfRangeException((index < 0) ? "index" : "count", "Non-negative number required.");
            }
            if (bytes.Length - index < count)
            {
                throw new ArgumentOutOfRangeException("bytes", "Index and count must refer to a location within the buffer.");
            }
            if (count == 0)
            {
                return 0;
            }
            byte* ptr;
            if (bytes == null || bytes.Length == 0)
            {
                ptr = null;
            }
            else
            {
                ptr = &bytes[0];
            }
            return this.GetCharCount(ptr + index, count, null);
        }
References System.count, System.Text.EncodingNLS.GetCharCount(), and System.index.
Referenced by System.Text.EncodingNLS.GetCharCount(), and System.Text.EncodingNLS.GetCharCount().