Terraria Decompiled: Terraria.Social.Steam.CoreSocialModule.Initialize
Initialize()
void Terraria.Social.Steam.CoreSocialModule.Initialize () inline
Implements Terraria.Social.ISocialModule.
Definition at line 53 of file CoreSocialModule.cs.
        {
            CoreSocialModule._instance = this;
            if (!Main.dedServ && SteamAPI.RestartAppIfNecessary(new AppId_t(105600U)))
            {
                Environment.Exit(1);
                return;
            }
            if (!SteamAPI.Init())
            {
                MessageBox.Show(Language.GetTextValue("Error.LaunchFromSteam"), Language.GetTextValue("Error.Error"), MessageBoxButtons.OK, MessageBoxIcon.Error);
                Environment.Exit(1);
            }
            SteamInput.Init(false);
            this.IsSteamValid = true;
            new Thread(new ParameterizedThreadStart(this.SteamCallbackLoop))
            {
                IsBackground = true
            }.Start();
            new Thread(new ParameterizedThreadStart(this.SteamTickLoop))
            {
                IsBackground = true
            }.Start();
            Main.OnTickForThirdPartySoftwareOnly += this.PulseSteamTick;
            Main.OnTickForThirdPartySoftwareOnly += this.PulseSteamCallback;
            if (Platform.IsOSX && !Main.dedServ)
            {
                this._onOverlayActivated = Callback<GameOverlayActivated_t>.Create(new Callback<GameOverlayActivated_t>.DispatchDelegate(this.OnOverlayActivated));
            }
        }
References Steamworks.Callback< T >.Create(), Terraria.Main.dedServ, Terraria.Localization.Language.GetTextValue(), Steamworks.SteamAPI.Init(), Steamworks.SteamInput.Init(), ReLogic.OS.Platform.IsOSX, Terraria.Social.Steam.CoreSocialModule.OnOverlayActivated(), System.Threading.ParameterizedThreadStart(), Terraria.Social.Steam.CoreSocialModule.PulseSteamCallback(), Terraria.Social.Steam.CoreSocialModule.PulseSteamTick(), Steamworks.SteamAPI.RestartAppIfNecessary(), Terraria.Utilities.MessageBox.Show(), System.Threading.Thread.Start(), Terraria.Social.Steam.CoreSocialModule.SteamCallbackLoop(), Terraria.Social.Steam.CoreSocialModule.SteamTickLoop(), and System.U.