Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.IsValidType
IsValidType()
bool System.Reflection.Emit.CustomAttributeBuilder.IsValidType (Type t) inline private
Definition at line 119 of file CustomAttributeBuilder.cs.
        {
            if (t.IsArray && t.GetArrayRank() > 1)
            {
                return false;
            }
            if (t is TypeBuilder && t.IsEnum)
            {
                Enum.GetUnderlyingType(t);
            }
            return (!t.IsClass || t.IsArray || t == typeof(object) || t == typeof(Type) || t == typeof(string) || t.Assembly.GetName().Name == "mscorlib") && (!t.IsValueType || t.IsPrimitive || t.IsEnum || (t.Assembly is AssemblyBuilder && t.Assembly.GetName().Name == "mscorlib"));
        }
References System.Type.Assembly, System.Type.GetArrayRank(), System.Enum.GetUnderlyingType(), System.Type.IsArray, System.Type.IsClass, and System.Type.IsEnum.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.Initialize(), and System.Reflection.Emit.CustomAttributeBuilder.IsValidParam().