Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.IsValidParam
IsValidParam()
bool System.Reflection.Emit.CustomAttributeBuilder.IsValidParam (object o, Type paramType) inline private
Definition at line 133 of file CustomAttributeBuilder.cs.
        {
            Type type = o.GetType();
            if (!this.IsValidType(type))
            {
                return false;
            }
            if (paramType == typeof(object))
            {
                if (type.IsArray && type.GetArrayRank() == 1)
                {
                    return this.IsValidType(type.GetElementType());
                }
                if (!type.IsPrimitive && !typeof(Type).IsAssignableFrom(type) && type != typeof(string) && !type.IsEnum)
                {
                    return false;
                }
            }
            return true;
        }
References System.Type.GetArrayRank(), System.Type.GetElementType(), System.Type.IsArray, System.Type.IsEnum, System.Type.IsPrimitive, and System.Reflection.Emit.CustomAttributeBuilder.IsValidType().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.Initialize().