Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.GetParameters
GetParameters()
static ParameterInfo[] System.Reflection.Emit.CustomAttributeBuilder.GetParameters (ConstructorInfo ctor) inline static private
Definition at line 721 of file CustomAttributeBuilder.cs.
        {
            ConstructorBuilder constructorBuilder = ctor as ConstructorBuilder;
            if (constructorBuilder != null)
            {
                return constructorBuilder.GetParametersInternal();
            }
            return ctor.GetParametersInternal();
        }
References System.Reflection.Emit.CustomAttributeBuilder.ctor, System.Reflection.Emit.ConstructorBuilder.GetParametersInternal(), and System.Reflection.MethodBase.GetParametersInternal().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.decode_cattr(), System.Reflection.Emit.CustomAttributeBuilder.get_umarshal(), and System.Reflection.Emit.CustomAttributeBuilder.Initialize().