Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.decode_string
decode_string()
static string System.Reflection.Emit.CustomAttributeBuilder.decode_string (byte[] data, int pos, out int rpos) inline static package
Definition at line 364 of file CustomAttributeBuilder.cs.
        {
            if (data[pos] == 255)
            {
                rpos = pos + 1;
                return null;
            }
            int num = CustomAttributeBuilder.decode_len(data, pos, out pos);
            string text = CustomAttributeBuilder.string_from_bytes(data, pos, num);
            pos += num;
            rpos = pos;
            return text;
        }
References System.Reflection.Emit.CustomAttributeBuilder.data, System.Reflection.Emit.CustomAttributeBuilder.decode_len(), System.Reflection.Emit.CustomAttributeBuilder.string_from_bytes(), and System.text.
Referenced by System.Reflection.Emit.CustomAttributeBuilder.get_umarshal(), and System.Reflection.Emit.CustomAttributeBuilder.string_arg().