Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.decode_cattr
decode_cattr()
static CustomAttributeBuilder.CustomAttributeInfo System.Reflection.Emit.CustomAttributeBuilder.decode_cattr (CustomAttributeBuilder customBuilder) inline static package
Definition at line 652 of file CustomAttributeBuilder.cs.
        {
            byte[] array = customBuilder.Data;
            ConstructorInfo constructorInfo = customBuilder.Ctor;
            int num = 0;
            CustomAttributeBuilder.CustomAttributeInfo customAttributeInfo = default(CustomAttributeBuilder.CustomAttributeInfo);
            if (array.Length < 2)
            {
                throw new Exception("Custom attr length is only '" + array.Length.ToString() + "'");
            }
            if (array[0] != 1 || array[1] != 0)
            {
                throw new Exception("Prolog invalid");
            }
            num = 2;
            ParameterInfo[] parameters = CustomAttributeBuilder.GetParameters(constructorInfo);
            customAttributeInfo.ctor = constructorInfo;
            customAttributeInfo.ctorArgs = new object[parameters.Length];
            for (int i = 0; i < parameters.Length; i++)
            {
                customAttributeInfo.ctorArgs[i] = CustomAttributeBuilder.decode_cattr_value(parameters[i].ParameterType, array, num, out num);
            }
            int num2 = (int)array[num] + (int)array[num + 1] * 256;
            num += 2;
            customAttributeInfo.namedParamNames = new string[num2];
            customAttributeInfo.namedParamValues = new object[num2];
            for (int j = 0; j < num2; j++)
            {
                int num3 = (int)array[num++];
                int num4 = (int)array[num++];
                string text = null;
                if (num4 == 85)
                {
                    int num5 = CustomAttributeBuilder.decode_len(array, num, out num);
                    text = CustomAttributeBuilder.string_from_bytes(array, num, num5);
                    num += num5;
                }
                int num6 = CustomAttributeBuilder.decode_len(array, num, out num);
                string text2 = CustomAttributeBuilder.string_from_bytes(array, num, num6);
                customAttributeInfo.namedParamNames[j] = text2;
                num += num6;
                if (num3 != 83)
                {
                    throw new Exception("Unknown named type: " + num3.ToString());
                }
                FieldInfo field = constructorInfo.DeclaringType.GetField(text2, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
                if (field == null)
                {
                    string[] array2 = new string[5];
                    array2[0] = "Custom attribute type '";
                    int num7 = 1;
                    Type declaringType = constructorInfo.DeclaringType;
                    array2[num7] = ((declaringType != null) ? declaringType.ToString() : null);
                    array2[2] = "' doesn't contain a field named '";
                    array2[3] = text2;
                    array2[4] = "'";
                    throw new Exception(string.Concat(array2));
                }
                object obj = CustomAttributeBuilder.decode_cattr_value(field.FieldType, array, num, out num);
                if (text != null)
                {
                    obj = Enum.ToObject(Type.GetType(text), obj);
                }
                customAttributeInfo.namedParamValues[j] = obj;
            }
            return customAttributeInfo;
        }
References System.array, System.Reflection.Emit.CustomAttributeBuilder.Ctor, System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeInfo.ctorArgs, System.Reflection.Emit.CustomAttributeBuilder.Data, System.Reflection.MemberInfo.DeclaringType, System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value(), System.Reflection.Emit.CustomAttributeBuilder.decode_len(), System.Reflection.FieldInfo.FieldType, System.Type.GetField(), System.Reflection.Emit.CustomAttributeBuilder.GetParameters(), System.Type.GetType(), int, System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeInfo.namedParamNames, System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeInfo.namedParamValues, System.obj, System.Reflection.Emit.CustomAttributeBuilder.string_from_bytes(), System.text, System.Enum.ToObject(), and System.Type.ToString().
Referenced by System.Reflection.Emit.MethodBuilder.SetCustomAttribute(), and System.Reflection.Emit.ParameterBuilder.SetCustomAttribute().