Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.get_umarshal
get_umarshal()
static UnmanagedMarshal System.Reflection.Emit.CustomAttributeBuilder.get_umarshal (CustomAttributeBuilder customBuilder, bool is_field) inline static package
Definition at line 386 of file CustomAttributeBuilder.cs.
        {
            byte[] array = customBuilder.Data;
            UnmanagedType unmanagedType = (UnmanagedType)80;
            int num = -1;
            int num2 = -1;
            bool flag = false;
            string text = null;
            Type type = null;
            string text2 = string.Empty;
            int num3 = (int)array[2];
            num3 |= (int)array[3] << 8;
            string fullName = CustomAttributeBuilder.GetParameters(customBuilder.Ctor)[0].ParameterType.FullName;
            int num4 = 6;
            if (fullName == "System.Int16")
            {
                num4 = 4;
            }
            int num5 = (int)array[num4++];
            num5 |= (int)array[num4++] << 8;
            int i = 0;
            while (i < num5)
            {
                byte b = array[num4++];
                if (array[num4++] == 85)
                {
                    CustomAttributeBuilder.decode_string(array, num4, out num4);
                }
                string text3 = CustomAttributeBuilder.decode_string(array, num4, out num4);
                uint num6 = <PrivateImplementationDetails>.ComputeStringHash(text3);
                if (num6 <= 2523910760U)
                {
                    if (num6 <= 1554623949U)
                    {
                        if (num6 != 67206855U)
{
                            if (num6 != 1554623949U)
{
                                goto IL_030E;
                            }
                            if (!(text3 == "SafeArraySubType"))
{
                                goto IL_030E;
                            }
                            unmanagedType = (UnmanagedType)((int)array[num4++] | ((int)array[num4++] << 8) | ((int)array[num4++] << 16) | ((int)array[num4++] << 24));
                        }
                        else
{
                            if (!(text3 == "MarshalCookie"))
{
                                goto IL_030E;
                            }
                            text2 = CustomAttributeBuilder.decode_string(array, num4, out num4);
                        }
                    }
                    else if (num6 != 1823397059U)
                    {
                        if (num6 != 2523910760U)
{
                            goto IL_030E;
                        }
                        if (!(text3 == "IidParameterIndex"))
{
                            goto IL_030E;
                        }
                        num4 += 4;
                    }
                    else
                    {
                        if (!(text3 == "SizeParamIndex"))
{
                            goto IL_030E;
                        }
                        num2 = (int)array[num4++] | ((int)array[num4++] << 8);
                        flag = true;
                    }
                }
                else if (num6 <= 2658176172U)
                {
                    if (num6 != 2546868066U)
                    {
                        if (num6 != 2658176172U)
{
                            goto IL_030E;
                        }
                        if (!(text3 == "ArraySubType"))
{
                            goto IL_030E;
                        }
                        unmanagedType = (UnmanagedType)((int)array[num4++] | ((int)array[num4++] << 8) | ((int)array[num4++] << 16) | ((int)array[num4++] << 24));
                    }
                    else
                    {
                        if (!(text3 == "MarshalTypeRef"))
{
                            goto IL_030E;
                        }
                        text = CustomAttributeBuilder.decode_string(array, num4, out num4);
                        if (text != null)
{
                            type = Type.GetType(text);
                        }
                    }
                }
                else if (num6 != 2784686469U)
                {
                    if (num6 != 3888525279U)
                    {
                        if (num6 != 4141739223U)
{
                            goto IL_030E;
                        }
                        if (!(text3 == "SafeArrayUserDefinedSubType"))
{
                            goto IL_030E;
                        }
                        CustomAttributeBuilder.decode_string(array, num4, out num4);
                    }
                    else
                    {
                        if (!(text3 == "SizeConst"))
{
                            goto IL_030E;
                        }
                        num = (int)array[num4++] | ((int)array[num4++] << 8) | ((int)array[num4++] << 16) | ((int)array[num4++] << 24);
                        flag = true;
                    }
                }
                else
                {
                    if (!(text3 == "MarshalType"))
                    {
                        goto IL_030E;
                    }
                    text = CustomAttributeBuilder.decode_string(array, num4, out num4);
                }
                i++;
                continue;
                IL_030E:
                throw new Exception("Unknown MarshalAsAttribute field: " + text3);
            }
            UnmanagedType unmanagedType2 = (UnmanagedType)num3;
            if (unmanagedType2 <= UnmanagedType.SafeArray)
            {
                if (unmanagedType2 == UnmanagedType.ByValTStr)
                {
                    return UnmanagedMarshal.DefineByValTStr(num);
                }
                if (unmanagedType2 == UnmanagedType.SafeArray)
                {
                    return UnmanagedMarshal.DefineSafeArray(unmanagedType);
                }
            }
            else if (unmanagedType2 != UnmanagedType.ByValArray)
            {
                if (unmanagedType2 != UnmanagedType.LPArray)
                {
                    if (unmanagedType2 == UnmanagedType.CustomMarshaler)
                    {
                        return UnmanagedMarshal.DefineCustom(type, text2, text, Guid.Empty);
                    }
                }
                else
                {
                    if (flag)
                    {
                        return UnmanagedMarshal.DefineLPArrayInternal(unmanagedType, num, num2);
                    }
                    return UnmanagedMarshal.DefineLPArray(unmanagedType);
                }
            }
            else
            {
                if (!is_field)
                {
                    throw new ArgumentException("Specified unmanaged type is only valid on fields");
                }
                return UnmanagedMarshal.DefineByValArray(num);
            }
            return UnmanagedMarshal.DefineUnmanagedMarshal((UnmanagedType)num3);
        }
References System.array, System.Reflection.Emit.CustomAttributeBuilder.Ctor, System.Reflection.Emit.CustomAttributeBuilder.Data, System.Reflection.Emit.CustomAttributeBuilder.decode_string(), System.Reflection.Emit.UnmanagedMarshal.DefineByValArray(), System.Reflection.Emit.UnmanagedMarshal.DefineByValTStr(), System.Reflection.Emit.UnmanagedMarshal.DefineCustom(), System.Reflection.Emit.UnmanagedMarshal.DefineLPArray(), System.Reflection.Emit.UnmanagedMarshal.DefineLPArrayInternal(), System.Reflection.Emit.UnmanagedMarshal.DefineSafeArray(), System.Reflection.Emit.UnmanagedMarshal.DefineUnmanagedMarshal(), System.Guid.Empty, System.Type.FullName, System.Reflection.Emit.CustomAttributeBuilder.GetParameters(), System.Type.GetType(), int, System.Reflection.ParameterInfo.ParameterType, System.text, and System.Reflection.U.
Referenced by System.Reflection.Emit.FieldBuilder.SetCustomAttribute(), and System.Reflection.Emit.ParameterBuilder.SetCustomAttribute().