Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value
decode_cattr_value()
static object System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value (Type t, byte[] data, int pos, out int rpos) inline static private
Definition at line 605 of file CustomAttributeBuilder.cs.
        {
            TypeCode typeCode = Type.GetTypeCode(t);
            if (typeCode <= TypeCode.Boolean)
            {
                if (typeCode != TypeCode.Object)
                {
                    if (typeCode == TypeCode.Boolean)
                    {
                        rpos = pos + 1;
                        return data[pos] != 0;
                    }
                }
                else
                {
                    int num = (int)data[pos];
                    pos++;
                    if (num >= 2 && num <= 14)
                    {
                        return CustomAttributeBuilder.decode_cattr_value(CustomAttributeBuilder.elementTypeToType(num), data, pos, out rpos);
                    }
                    throw new Exception("Subtype '" + num.ToString() + "' of type object not yet handled in decode_cattr_value");
                }
            }
            else
            {
                if (typeCode == TypeCode.Int32)
                {
                    rpos = pos + 4;
                    return (int)data[pos] + ((int)data[pos + 1] << 8) + ((int)data[pos + 2] << 16) + ((int)data[pos + 3] << 24);
                }
                if (typeCode == TypeCode.String)
                {
                    if (data[pos] == 255)
                    {
                        rpos = pos + 1;
                        return null;
                    }
                    int num2 = CustomAttributeBuilder.decode_len(data, pos, out pos);
                    rpos = pos + num2;
                    return CustomAttributeBuilder.string_from_bytes(data, pos, num2);
                }
            }
            throw new Exception("FIXME: Type " + ((t != null) ? t.ToString() : null) + " not yet handled in decode_cattr_value.");
        }
References System.Reflection.Emit.CustomAttributeBuilder.data, System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value(), System.Reflection.Emit.CustomAttributeBuilder.decode_len(), System.Reflection.Emit.CustomAttributeBuilder.elementTypeToType(), System.Type.GetTypeCode(), int, System.Reflection.Emit.CustomAttributeBuilder.string_from_bytes(), and System.Type.ToString().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.decode_cattr(), and System.Reflection.Emit.CustomAttributeBuilder.decode_cattr_value().