Terraria Decompiled: System.Reflection.Emit.CustomAttributeBuilder.Initialize
Initialize()
void System.Reflection.Emit.CustomAttributeBuilder.Initialize (ConstructorInfo con, object[] constructorArgs, PropertyInfo[] namedProperties, object[] propertyValues, FieldInfo[] namedFields, object[] fieldValues) inline private
Definition at line 179 of file CustomAttributeBuilder.cs.
        {
            this.ctor = con;
            this.args = constructorArgs;
            this.namedProperties = namedProperties;
            this.propertyValues = propertyValues;
            this.namedFields = namedFields;
            this.fieldValues = fieldValues;
            if (con == null)
            {
                throw new ArgumentNullException("con");
            }
            if (constructorArgs == null)
            {
                throw new ArgumentNullException("constructorArgs");
            }
            if (namedProperties == null)
            {
                throw new ArgumentNullException("namedProperties");
            }
            if (propertyValues == null)
            {
                throw new ArgumentNullException("propertyValues");
            }
            if (namedFields == null)
            {
                throw new ArgumentNullException("namedFields");
            }
            if (fieldValues == null)
            {
                throw new ArgumentNullException("fieldValues");
            }
            if (con.GetParametersCount() != constructorArgs.Length)
            {
                throw new ArgumentException("Parameter count does not match passed in argument value count.");
            }
            if (namedProperties.Length != propertyValues.Length)
            {
                throw new ArgumentException("Array lengths must be the same.", "namedProperties, propertyValues");
            }
            if (namedFields.Length != fieldValues.Length)
            {
                throw new ArgumentException("Array lengths must be the same.", "namedFields, fieldValues");
            }
            if ((con.Attributes & MethodAttributes.Static) == MethodAttributes.Static || (con.Attributes & MethodAttributes.MemberAccessMask) == MethodAttributes.Private)
            {
                throw new ArgumentException("Cannot have private or static constructor.");
            }
            Type declaringType = this.ctor.DeclaringType;
            int num = 0;
            foreach (FieldInfo fieldInfo in namedFields)
            {
                Type declaringType2 = fieldInfo.DeclaringType;
                if (declaringType != declaringType2 && !declaringType2.IsSubclassOf(declaringType) && !declaringType.IsSubclassOf(declaringType2))
                {
                    throw new ArgumentException("Field '" + fieldInfo.Name + "' does not belong to the same class as the constructor");
                }
                if (!this.IsValidType(fieldInfo.FieldType))
                {
                    throw new ArgumentException("Field '" + fieldInfo.Name + "' does not have a valid type.");
                }
                if (!CustomAttributeBuilder.IsValidValue(fieldInfo.FieldType, fieldValues[num]))
                {
                    throw new ArgumentException("Field " + fieldInfo.Name + " is not a valid value.");
                }
                if (fieldValues[num] != null && !(fieldInfo.FieldType is TypeBuilder) && !fieldInfo.FieldType.IsEnum && !fieldInfo.FieldType.IsInstanceOfType(fieldValues[num]) && !fieldInfo.FieldType.IsArray)
                {
                    string text = "Value of field '";
                    string name = fieldInfo.Name;
                    string text2 = "' does not match field type: ";
                    Type fieldType = fieldInfo.FieldType;
                    throw new ArgumentException(text + name + text2 + ((fieldType != null) ? fieldType.ToString() : null));
                }
                num++;
            }
            num = 0;
            foreach (PropertyInfo propertyInfo in namedProperties)
            {
                if (!propertyInfo.CanWrite)
                {
                    throw new ArgumentException("Property '" + propertyInfo.Name + "' does not have a setter.");
                }
                Type declaringType3 = propertyInfo.DeclaringType;
                if (declaringType != declaringType3 && !declaringType3.IsSubclassOf(declaringType) && !declaringType.IsSubclassOf(declaringType3))
                {
                    throw new ArgumentException("Property '" + propertyInfo.Name + "' does not belong to the same class as the constructor");
                }
                if (!this.IsValidType(propertyInfo.PropertyType))
                {
                    throw new ArgumentException("Property '" + propertyInfo.Name + "' does not have a valid type.");
                }
                if (!CustomAttributeBuilder.IsValidValue(propertyInfo.PropertyType, propertyValues[num]))
                {
                    throw new ArgumentException("Property " + propertyInfo.Name + " is not a valid value.");
                }
                if (propertyValues[num] != null && !(propertyInfo.PropertyType is TypeBuilder) && !propertyInfo.PropertyType.IsEnum && !propertyInfo.PropertyType.IsInstanceOfType(propertyValues[num]) && !propertyInfo.PropertyType.IsArray)
                {
                    string[] array = new string[6];
                    array[0] = "Value of property '";
                    array[1] = propertyInfo.Name;
                    array[2] = "' does not match property type: ";
                    int num2 = 3;
                    Type propertyType = propertyInfo.PropertyType;
                    array[num2] = ((propertyType != null) ? propertyType.ToString() : null);
                    array[4] = " -> ";
                    int num3 = 5;
                    object obj = propertyValues[num];
                    array[num3] = ((obj != null) ? obj.ToString() : null);
                    throw new ArgumentException(string.Concat(array));
                }
                num++;
            }
            num = 0;
            foreach (ParameterInfo parameterInfo in CustomAttributeBuilder.GetParameters(con))
            {
                if (parameterInfo != null)
                {
                    Type parameterType = parameterInfo.ParameterType;
                    if (!this.IsValidType(parameterType))
                    {
                        throw new ArgumentException("Parameter " + num.ToString() + " does not have a valid type.");
                    }
                    if (!CustomAttributeBuilder.IsValidValue(parameterType, constructorArgs[num]))
                    {
                        throw new ArgumentException("Parameter " + num.ToString() + " is not a valid value.");
                    }
                    if (constructorArgs[num] != null)
                    {
                        if (!(parameterType is TypeBuilder) && !parameterType.IsEnum && !parameterType.IsInstanceOfType(constructorArgs[num]) && !parameterType.IsArray)
{
                            string[] array2 = new string[6];
                            array2[0] = "Value of argument ";
                            array2[1] = num.ToString();
                            array2[2] = " does not match parameter type: ";
                            int num4 = 3;
                            Type type = parameterType;
                            array2[num4] = ((type != null) ? type.ToString() : null);
                            array2[4] = " -> ";
                            int num5 = 5;
                            object obj2 = constructorArgs[num];
                            array2[num5] = ((obj2 != null) ? obj2.ToString() : null);
                            throw new ArgumentException(string.Concat(array2));
                        }
                        if (!this.IsValidParam(constructorArgs[num], parameterType))
{
                            string text3 = "Cannot emit a CustomAttribute with argument of type ";
                            Type type2 = constructorArgs[num].GetType();
                            throw new ArgumentException(text3 + ((type2 != null) ? type2.ToString() : null) + ".");
                        }
                    }
                }
                num++;
            }
            this.data = CustomAttributeBuilder.GetBlob(declaringType.Assembly, con, constructorArgs, namedProperties, propertyValues, namedFields, fieldValues);
        }
References System.array, System.Reflection.MethodBase.Attributes, System.Reflection.PropertyInfo.CanWrite, System.Reflection.Emit.CustomAttributeBuilder.ctor, System.Reflection.MemberInfo.DeclaringType, System.Reflection.FieldInfo.FieldType, System.Reflection.Emit.CustomAttributeBuilder.fieldValues, System.Reflection.Emit.CustomAttributeBuilder.GetBlob(), System.Reflection.Emit.CustomAttributeBuilder.GetParameters(), System.Reflection.MethodBase.GetParametersCount(), System.Type.GetType(), System.Type.IsArray, System.Type.IsEnum, System.Type.IsInstanceOfType(), System.Type.IsSubclassOf(), System.Reflection.Emit.CustomAttributeBuilder.IsValidParam(), System.Reflection.Emit.CustomAttributeBuilder.IsValidType(), System.Reflection.Emit.CustomAttributeBuilder.IsValidValue(), System.name, System.Reflection.MemberInfo.Name, System.Reflection.Emit.CustomAttributeBuilder.namedFields, System.Reflection.Emit.CustomAttributeBuilder.namedProperties, System.obj, System.Reflection.ParameterInfo.ParameterType, System.Reflection.PropertyInfo.PropertyType, System.Reflection.Emit.CustomAttributeBuilder.propertyValues, System.text, and System.Type.ToString().
Referenced by System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder(), and System.Reflection.Emit.CustomAttributeBuilder.CustomAttributeBuilder().