Terraria Decompiled: CsvHelper.TypeConversion.TypeConverterFactory.GetConverter
GetConverter()
static ITypeConverter CsvHelper.TypeConversion.TypeConverterFactory.GetConverter (Type type) inline static
Definition at line 70 of file TypeConverterFactory.cs.
        {
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }
            object obj = TypeConverterFactory.locker;
            lock (obj)
            {
                ITypeConverter typeConverter;
                if (TypeConverterFactory.typeConverters.TryGetValue(type, ref typeConverter))
                {
                    return typeConverter;
                }
            }
            if (typeof(IEnumerable).IsAssignableFrom(type))
            {
                return TypeConverterFactory.GetConverter(typeof(IEnumerable));
            }
            if (typeof(Enum).IsAssignableFrom(type))
            {
                TypeConverterFactory.AddConverter(type, new EnumConverter(type));
                return TypeConverterFactory.GetConverter(type);
            }
            if (type.GetTypeInfo().IsGenericType && type.GetGenericTypeDefinition() == typeof(Nullable))
            {
                TypeConverterFactory.AddConverter(type, new NullableConverter(type));
                return TypeConverterFactory.GetConverter(type);
            }
            return new DefaultTypeConverter();
        }
References CsvHelper.TypeConversion.TypeConverterFactory.AddConverter(), CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), System.Type.GetGenericTypeDefinition(), System.Type.GetTypeInfo(), CsvHelper.TypeConversion.TypeConverterFactory.locker, System.obj, and CsvHelper.TypeConversion.TypeConverterFactory.typeConverters.
Referenced by CsvHelper.Configuration.CsvClassMap< T >.AutoMapInternal(), CsvHelper.CsvWriter.CreateActionForPrimitive(), CsvHelper.CsvReader.CreateFuncForPrimitive(), CsvHelper.Configuration.CsvPropertyMap.CsvPropertyMap(), CsvHelper.TypeConversion.TypeConverterFactory.GetConverter(), CsvHelper.TypeConversion.TypeConverterFactory.GetConverter< T >(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.CsvReader.GetField< T >(), CsvHelper.TypeConversion.NullableConverter.NullableConverter(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvReader.TryGetField< T >(), CsvHelper.CsvWriter.WriteField(), CsvHelper.CsvWriter.WriteField< T >(), and CsvHelper.CsvWriter.WriteField< T, TConverter >().