Terraria Decompiled: Terraria.Graphics.CameraModifiers.PunchCameraModifier.Update
Update()
void Terraria.Graphics.CameraModifiers.PunchCameraModifier.Update (ref CameraInfo cameraInfo) inline
Implements Terraria.Graphics.CameraModifiers.ICameraModifier.
Definition at line 75 of file PunchCameraModifier.cs.
        {
            float num = (float)Math.Cos((double)((float)this._framesLasted / 60f * this._vibrationCyclesPerSecond * 6.2831855f));
            float num2 = Utils.Remap((float)this._framesLasted, 0f, (float)this._framesToLast, 1f, 0f, true);
            float num3 = Utils.Remap(Vector2.Distance(this._startPosition, cameraInfo.OriginalCameraCenter), 0f, this._distanceFalloff, 1f, 0f, true);
            if (this._distanceFalloff == -1f)
            {
                num3 = 1f;
            }
            cameraInfo.CameraPosition += this._direction * num * this._strength * num2 * num3;
            this._framesLasted++;
            if (this._framesLasted >= this._framesToLast)
            {
                this.Finished = true;
            }
        }
References Terraria.Graphics.CameraModifiers.PunchCameraModifier._distanceFalloff, Terraria.Graphics.CameraModifiers.PunchCameraModifier._framesLasted, Terraria.Graphics.CameraModifiers.PunchCameraModifier._framesToLast, Terraria.Graphics.CameraModifiers.PunchCameraModifier._vibrationCyclesPerSecond, System.Math.Cos(), Microsoft.Xna.Framework.Vector2.Distance(), and Terraria.Utils.Remap().