Terraria Decompiled: Terraria.Utilities.MessageBox.Show
Show() [3/3]
static unsafe int Terraria.Utilities.MessageBox.Show (string message, string title, string[] buttonLabels, int returnButtonIndex = -1, int cancelButtonIndex = -1, MessageBoxIcon icon = MessageBoxIcon::None) inline static
Definition at line 72 of file MessageBox.cs.
        {
            SDL.SDL_MessageBoxButtonData* ptr = (SDL.SDL_MessageBoxButtonData*)(void*)Marshal.AllocHGlobal(Marshal.SizeOf(typeof(SDL.SDL_MessageBoxButtonData)) * buttonLabels.Length);
            for (int i = 0; i < buttonLabels.Length; i++)
            {
                ptr[i] = new SDL.SDL_MessageBoxButtonData
                {
                    flags = ((i == returnButtonIndex) ? SDL.SDL_MessageBoxButtonFlags.SDL_MESSAGEBOX_BUTTON_RETURNKEY_DEFAULT : ((i == cancelButtonIndex) ? SDL.SDL_MessageBoxButtonFlags.SDL_MESSAGEBOX_BUTTON_ESCAPEKEY_DEFAULT : ((SDL.SDL_MessageBoxButtonFlags)0U))),
                    buttonID = i,
                    text = MessageBox.AllocUTF8(buttonLabels[i])
                };
            }
            SDL.SDL_MessageBoxData sdl_MessageBoxData = new SDL.SDL_MessageBoxData
            {
                flags = (SDL.SDL_MessageBoxFlags)(icon | (MessageBoxIcon)128U),
                message = MessageBox.AllocUTF8(message),
                title = MessageBox.AllocUTF8(title),
                buttons = ptr,
                numbuttons = buttonLabels.Length
            };
            int num2;
            try
            {
                int num;
                if (!SDL.SDL_ShowMessageBox(ref sdl_MessageBoxData, out num))
                {
                    num2 = -1;
                }
                else
                {
                    num2 = num;
                }
            }
            finally
            {
                for (int j = 0; j < buttonLabels.Length; j++)
                {
                    Marshal.FreeHGlobal((IntPtr)((void*)ptr[j].text));
                }
                Marshal.FreeHGlobal((IntPtr)((void*)sdl_MessageBoxData.message));
                Marshal.FreeHGlobal((IntPtr)((void*)sdl_MessageBoxData.title));
            }
            return num2;
        }
References System.Runtime.InteropServices.Marshal.AllocHGlobal(), Terraria.Utilities.MessageBox.AllocUTF8(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), SDL3.SDL.SDL_MessageBoxData.message, SDL3.SDL.SDL_ShowMessageBox(), System.Runtime.InteropServices.Marshal.SizeOf(), System.text, SDL3.SDL.SDL_MessageBoxData.title, and System.U.