Terraria Decompiled: Terraria.Utilities.MessageBox.Show
Show() [2/3]
static DialogResult Terraria.Utilities.MessageBox.Show (string message, string title, MessageBoxButtons buttons = MessageBoxButtons::OK, MessageBoxIcon icon = MessageBoxIcon::None) inline static
Definition at line 14 of file MessageBox.cs.
        {
            switch (buttons)
            {
            case MessageBoxButtons.OK:
                return MessageBox.Show(message, title, new DialogResult[] { DialogResult.OK }, icon, 0, 0);
            case MessageBoxButtons.OKCancel:
                return MessageBox.Show(message, title, new DialogResult[]
                {
                    DialogResult.Cancel,
                    DialogResult.OK
                }, icon, 0, 1);
            case MessageBoxButtons.YesNoCancel:
                return MessageBox.Show(message, title, new DialogResult[]
                {
                    DialogResult.Yes,
                    DialogResult.No,
                    DialogResult.Cancel
                }, icon, 0, 2);
            case MessageBoxButtons.YesNo:
                return MessageBox.Show(message, title, new DialogResult[]
                {
                    DialogResult.No,
                    DialogResult.Yes
                }, icon, 0, -1);
            case MessageBoxButtons.RetryCancel:
                return MessageBox.Show(message, title, new DialogResult[]
                {
                    DialogResult.Cancel,
                    DialogResult.Retry
                }, icon, 0, 1);
            default:
                throw new ArgumentOutOfRangeException("buttons");
            }
        }
References Terraria.Utilities.MessageBox.Show().
Referenced by Terraria.Program.DisplayException(), Terraria.Testing.GitStatus.Init(), Terraria.Social.Steam.CoreSocialModule.Initialize(), Terraria.Testing.QuickLoad.Load(), Terraria.Testing.QuickLoad.OnContentLoaded(), Terraria.Social.WeGame.CoreSocialModule.ProcessRailSystemStateChange(), Terraria.Utilities.MessageBox.Show(), Terraria.Utilities.MessageBox.Show(), and Terraria.UI.FancyErrorPrinter.ShowTheBox().