Terraria Decompiled: Terraria.Testing.LockstepDebug.Step
Step() [2/2]
static void Terraria.Testing.LockstepDebug.Step (string state) inline static
Definition at line 134 of file LockstepDebug.cs.
        {
            if (!LockstepDebug.Enabled)
            {
                return;
            }
            if (state.Length > LockstepDebug.BufSize / 2)
            {
                throw new ArgumentException("String too large");
            }
            LockstepDebug.stepCount += 1L;
            if (LockstepDebug.stepCount < LockstepDebug.lastSuccessfulStep)
            {
                return;
            }
            LockstepDebug.WriteStep(state);
            string text = LockstepDebug.ReadStep();
            if (!(text != state))
            {
                if (LockstepDebug.stepCount == LockstepDebug.lastSuccessfulStep && LockstepDebug.stopAtLastStep)
                {
                    Trace.WriteLine("LockstepDebug reached the last match from the previous run. Debug from here to identify desync");
                    if (Debugger.IsAttached)
                    {
                        Debugger.Break();
                    }
                    else
                    {
                        Debugger.Launch();
                    }
                }
                LockstepDebug.lastSuccessfulStep = LockstepDebug.stepCount;
                return;
            }
            LockstepDebug.Enabled = false;
            Trace.WriteLine(string.Format("Lockstep mismatch. Step: {0}\nSent: {1}\nRecv: {2}", LockstepDebug.stepCount, state, text));
            if (LockstepDebug.lastSuccessfulStep < LockstepDebug.stepCount - 1L)
            {
                Trace.WriteLine(string.Format("Expensive steps were skipped. Rerun to narrow down the mismatch. Last successful step was {0} steps ago", LockstepDebug.stepCount - LockstepDebug.lastSuccessfulStep));
                return;
            }
            if (LockstepDebug.lastSuccessfulStep == LockstepDebug.stepCount)
            {
                Trace.WriteLine("Last successful step mismatch. The rerun was not deterministic.");
            }
            if (Debugger.IsAttached)
            {
                Debugger.Break();
                return;
            }
            Debugger.Launch();
        }
References System.Diagnostics.Debugger.Break(), Terraria.Testing.LockstepDebug.BufSize, Terraria.Testing.LockstepDebug.Enabled, System.Format, System.Diagnostics.Debugger.IsAttached, System.L, Terraria.Testing.LockstepDebug.lastSuccessfulStep, System.Diagnostics.Debugger.Launch(), Terraria.Testing.LockstepDebug.ReadStep(), System.state, Terraria.Testing.LockstepDebug.stepCount, Terraria.Testing.LockstepDebug.stopAtLastStep, System.text, System.Trace, and Terraria.Testing.LockstepDebug.WriteStep().