Terraria Decompiled: Terraria.Testing.LockstepDebug.Enable
Enable()
static void Terraria.Testing.LockstepDebug.Enable () inline static
Definition at line 63 of file LockstepDebug.cs.
        {
            LockstepDebug.Init();
            LockstepDebug.Enabled = true;
            bool flag = false;
            if (LockstepDebug.lastSuccessfulStep == 0L)
            {
                Trace.WriteLine("LockstepDebug enabled.");
            }
            else if (LockstepDebug.stepCount == LockstepDebug.lastSuccessfulStep + 1L)
            {
                LockstepDebug.stopAtLastStep = true;
                Trace.WriteLine("LockstepDebug rerun detected. Skipping to and stopping at step " + LockstepDebug.lastSuccessfulStep);
            }
            else
            {
                Trace.WriteLine(string.Format("LockstepDebug rerun detected. Skipping to step {0}. Up to {1} steps to find mismatch.", LockstepDebug.lastSuccessfulStep, LockstepDebug.stepCount - LockstepDebug.lastSuccessfulStep));
                if (LockstepDebug.expensiveStepState.stepRateIncreaseCount == 1)
                {
                    flag = true;
                }
            }
            LockstepDebug.WriteStep("Enable");
            if (LockstepDebug.ReadStep() != "Enable")
            {
                throw new Exception("Enable sync failed");
            }
            LockstepDebug.stepCount = 0L;
            LockstepDebug.expensiveStepState = new LockstepDebug.ExpensiveStepRateState(flag);
        }
References Terraria.Testing.LockstepDebug.expensiveStepState, System.Format, Terraria.Testing.LockstepDebug.Init(), System.L, Terraria.Testing.LockstepDebug.lastSuccessfulStep, Terraria.Testing.LockstepDebug.ReadStep(), Terraria.Testing.LockstepDebug.stepCount, System.Trace, and Terraria.Testing.LockstepDebug.WriteStep().