Terraria Decompiled: System.Collections.ArrayList.IListWrapper.InsertRange
InsertRange()
override void System.Collections.ArrayList.IListWrapper.InsertRange (int index, ICollection c) inline virtual
Reimplemented from System.Collections.ArrayList.
Definition at line 1001 of file ArrayList.cs.
            {
                if (c == null)
                {
                    throw new ArgumentNullException("c", "Collection cannot be null.");
                }
                if (index < 0 || index > this.Count)
                {
                    throw new ArgumentOutOfRangeException("index", "Index was out of range. Must be non-negative and less than the size of the collection.");
                }
                if (c.Count > 0)
                {
                    ArrayList arrayList = this._list as ArrayList;
                    if (arrayList != null)
                    {
                        arrayList.InsertRange(index, c);
                    }
                    else
                    {
                        foreach (object obj in c)
{
                            this._list.Insert(index++, obj);
                        }
                    }
                    this._version++;
                }
            }
References System.Collections.ArrayList.IListWrapper._list, System.Collections.ArrayList.ArrayList(), System.Collections.ArrayList.IListWrapper.Count, System.Collections.ICollection.Count, System.index, System.Collections.IList.Insert(), System.Collections.ArrayList.InsertRange(), and System.obj.
Referenced by System.Collections.ArrayList.IListWrapper.AddRange().