Terraria Decompiled: System.AppDomain.DoTypeResolve
DoTypeResolve()
Assembly System.AppDomain.DoTypeResolve (string name) inline package
Definition at line 1387 of file AppDomain.cs.
        {
            if (this.TypeResolve == null)
            {
                return null;
            }
            Dictionary<string, object> dictionary = AppDomain.type_resolve_in_progress;
            if (dictionary == null)
            {
                dictionary = (AppDomain.type_resolve_in_progress = new Dictionary<string, object>());
            }
            if (dictionary.ContainsKey(name))
            {
                return null;
            }
            dictionary[name] = null;
            Assembly assembly2;
            try
            {
                Delegate[] invocationList = this.TypeResolve.GetInvocationList();
                for (int i = 0; i < invocationList.Length; i++)
                {
                    Assembly assembly = ((ResolveEventHandler)invocationList[i])(this, new ResolveEventArgs(name));
                    if (assembly != null)
                    {
                        return assembly;
                    }
                }
                assembly2 = null;
            }
            finally
            {
                dictionary.Remove(name);
            }
            return assembly2;
        }
References System.dictionary, System.Delegate.GetInvocationList(), System.name, System.ResolveEventHandler(), System.AppDomain.type_resolve_in_progress, and System.AppDomain.TypeResolve.
Referenced by System.AppDomain.DoTypeBuilderResolve().