Terraria Decompiled: System.AppDomain.SetAppDomainPolicy
SetAppDomainPolicy()
void System.AppDomain.SetAppDomainPolicy (PolicyLevel domainPolicy) inline
Definition at line 909 of file AppDomain.cs.
        {
            if (domainPolicy == null)
            {
                throw new ArgumentNullException("domainPolicy");
            }
            if (this._granted != null)
            {
                throw new PolicyException(Locale.GetText("An AppDomain policy is already specified."));
            }
            if (this.IsFinalizingForUnload())
            {
                throw new AppDomainUnloadedException();
            }
            PolicyStatement policyStatement = domainPolicy.Resolve(this._evidence);
            this._granted = policyStatement.PermissionSet;
        }
References System.AppDomain._evidence, System.AppDomain._granted, Locale.GetText(), System.AppDomain.IsFinalizingForUnload(), System.Security.Policy.PolicyStatement.PermissionSet, and System.Security.Policy.PolicyLevel.Resolve().
Referenced by System.AppDomainManager.CreateDomain().