Terraria Decompiled: System.AppDomain.Load
Load() [2/9]
Assembly System.AppDomain.Load (AssemblyName assemblyRef, Evidence assemblySecurity) inline
Implements System._AppDomain.
Definition at line 763 of file AppDomain.cs.
        {
            if (assemblyRef == null)
            {
                throw new ArgumentNullException("assemblyRef");
            }
            if (assemblyRef.Name == null || assemblyRef.Name.Length == 0)
            {
                if (assemblyRef.CodeBase != null)
                {
                    return Assembly.LoadFrom(assemblyRef.CodeBase, assemblySecurity);
                }
                throw new ArgumentException(Locale.GetText("assemblyRef.Name cannot be empty."), "assemblyRef");
            }
            else
            {
                StackCrawlMark stackCrawlMark = StackCrawlMark.LookForMyCaller;
                Assembly assembly = this.LoadAssembly(assemblyRef.FullName, assemblySecurity, false, ref stackCrawlMark);
                if (assembly != null)
                {
                    return assembly;
                }
                if (assemblyRef.CodeBase == null)
                {
                    throw new FileNotFoundException(null, assemblyRef.Name);
                }
                string text = assemblyRef.CodeBase;
                if (text.StartsWith("file://", StringComparison.OrdinalIgnoreCase))
                {
                    text = new Uri(text).LocalPath;
                }
                try
                {
                    assembly = Assembly.LoadFrom(text, assemblySecurity);
                }
                catch
                {
                    throw new FileNotFoundException(null, assemblyRef.Name);
                }
                AssemblyName name = assembly.GetName();
                if (assemblyRef.Name != name.Name)
                {
                    throw new FileNotFoundException(null, assemblyRef.Name);
                }
                if (assemblyRef.Version != null && assemblyRef.Version != new Version(0, 0, 0, 0) && assemblyRef.Version != name.Version)
                {
                    throw new FileNotFoundException(null, assemblyRef.Name);
                }
                if (assemblyRef.CultureInfo != null && assemblyRef.CultureInfo.Equals(name))
                {
                    throw new FileNotFoundException(null, assemblyRef.Name);
                }
                byte[] publicKeyToken = assemblyRef.GetPublicKeyToken();
                if (publicKeyToken != null && publicKeyToken.Length != 0)
                {
                    byte[] publicKeyToken2 = name.GetPublicKeyToken();
                    if (publicKeyToken2 == null || publicKeyToken.Length != publicKeyToken2.Length)
                    {
                        throw new FileNotFoundException(null, assemblyRef.Name);
                    }
                    for (int i = publicKeyToken.Length - 1; i >= 0; i--)
                    {
                        if (publicKeyToken2[i] != publicKeyToken[i])
{
                            throw new FileNotFoundException(null, assemblyRef.Name);
                        }
                    }
                }
                return assembly;
            }
        }
References System.Reflection.AssemblyName.CodeBase, System.Reflection.AssemblyName.CultureInfo, System.Globalization.CultureInfo.Equals(), System.Reflection.AssemblyName.FullName, System.Reflection.Assembly.GetName(), System.Reflection.AssemblyName.GetPublicKeyToken(), Locale.GetText(), System.AppDomain.LoadAssembly(), System.Reflection.Assembly.LoadFrom(), Mono.Security.Uri.LocalPath, System.name, System.Reflection.AssemblyName.Name, System.text, System.Reflection.AssemblyName.Version, and System.Version.Version().