Terraria Decompiled: System.AppDomain.InvokeInDomainByID
InvokeInDomainByID()
static object System.AppDomain.InvokeInDomainByID (int domain_id, MethodInfo method, object obj, object[] args) inline static package
Definition at line 1049 of file AppDomain.cs.
        {
            AppDomain currentDomain = AppDomain.CurrentDomain;
            bool flag = false;
            object obj3;
            try
            {
                AppDomain.InternalPushDomainRefByID(domain_id);
                flag = true;
                AppDomain.InternalSetDomainByID(domain_id);
                Exception ex;
                object obj2 = ((RuntimeMethodInfo)method).InternalInvoke(obj, args, out ex);
                if (ex != null)
                {
                    throw ex;
                }
                obj3 = obj2;
            }
            finally
            {
                AppDomain.InternalSetDomain(currentDomain);
                if (flag)
                {
                    AppDomain.InternalPopDomainRef();
                }
            }
            return obj3;
        }
References System.AppDomain.CurrentDomain, System.AppDomain.InternalPopDomainRef(), System.AppDomain.InternalPushDomainRefByID(), System.AppDomain.InternalSetDomain(), System.AppDomain.InternalSetDomainByID(), and System.obj.
Referenced by System.Runtime.Remoting.Channels.CrossAppDomainSink.SyncProcessMessage().