Terraria Decompiled: System.AppDomain.ProcessMessageInDomain
ProcessMessageInDomain()
void System.AppDomain.ProcessMessageInDomain (byte[] arrRequest, CADMethodCallMessage cadMsg, out byte[] arrResponse, out CADMethodReturnMessage cadMrm) inline package
Definition at line 1472 of file AppDomain.cs.
        {
            IMessage message;
            if (arrRequest != null)
            {
                message = CADSerializer.DeserializeMessage(new MemoryStream(arrRequest), null);
            }
            else
            {
                message = new MethodCall(cadMsg);
            }
            IMessage message2 = ChannelServices.SyncDispatchMessage(message);
            cadMrm = CADMethodReturnMessage.Create(message2);
            if (cadMrm == null)
            {
                arrResponse = CADSerializer.SerializeMessage(message2).GetBuffer();
                return;
            }
            arrResponse = null;
        }
References System.Runtime.Remoting.Messaging.CADMethodReturnMessage.Create(), System.Runtime.Remoting.Channels.CADSerializer.DeserializeMessage(), System.IO.MemoryStream.GetBuffer(), System.Runtime.Remoting.Channels.CADSerializer.SerializeMessage(), and System.Runtime.Remoting.Channels.ChannelServices.SyncDispatchMessage().
Referenced by System.Runtime.Remoting.Channels.CrossAppDomainSink.ProcessMessageInDomain().