Terraria Decompiled: System.AppDomain.GetMarshalledDomainObjRef
GetMarshalledDomainObjRef()
byte[] System.AppDomain.GetMarshalledDomainObjRef () inline package
Definition at line 1466 of file AppDomain.cs.
        {
            return CADSerializer.SerializeObject(RemotingServices.Marshal(AppDomain.CurrentDomain, null, typeof(AppDomain))).GetBuffer();
        }
References System.AppDomain.CurrentDomain, System.IO.MemoryStream.GetBuffer(), System.Runtime.Remoting.RemotingServices.Marshal(), and System.Runtime.Remoting.Channels.CADSerializer.SerializeObject().