Terraria Decompiled: System.AppDomain.InvokeInDomain
InvokeInDomain()
static object System.AppDomain.InvokeInDomain (AppDomain domain, MethodInfo method, object obj, object[] args) inline static package
Definition at line 1019 of file AppDomain.cs.
        {
            AppDomain currentDomain = AppDomain.CurrentDomain;
            bool flag = false;
            object obj3;
            try
            {
                AppDomain.InternalPushDomainRef(domain);
                flag = true;
                AppDomain.InternalSetDomain(domain);
                Exception ex;
                object obj2 = ((RuntimeMethodInfo)method).InternalInvoke(obj, args, out ex);
                if (ex != null)
                {
                    throw ex;
                }
                obj3 = obj2;
            }
            finally
            {
                AppDomain.InternalSetDomain(currentDomain);
                if (flag)
                {
                    AppDomain.InternalPopDomainRef();
                }
            }
            return obj3;
        }
References System.AppDomain.CurrentDomain, System.AppDomain.InternalPopDomainRef(), System.AppDomain.InternalPushDomainRef(), System.AppDomain.InternalSetDomain(), and System.obj.
Referenced by System.Runtime.Remoting.RemotingServices.GetDomainProxy().