Terraria Decompiled: System.AppDomain.ExecuteAssemblyInternal
ExecuteAssemblyInternal()
int System.AppDomain.ExecuteAssemblyInternal (Assembly a, string[] args) inline private
Definition at line 696 of file AppDomain.cs.
        {
            if (a.EntryPoint == null)
            {
                throw new MissingMethodException("Entry point not found in assembly '" + a.FullName + "'.");
            }
            return this.ExecuteAssembly(a, args);
        }
References System.Reflection.Assembly.EntryPoint, System.AppDomain.ExecuteAssembly(), and System.Reflection.Assembly.FullName.
Referenced by System.AppDomain.ExecuteAssembly(), System.AppDomain.ExecuteAssembly(), System.AppDomain.ExecuteAssembly(), System.AppDomain.ExecuteAssembly(), System.AppDomain.ExecuteAssemblyByName(), System.AppDomain.ExecuteAssemblyByName(), System.AppDomain.ExecuteAssemblyByName(), and System.AppDomain.ExecuteAssemblyByName().