Terraria Decompiled: System.AppDomain.CreateDomain
CreateDomain() [3/6]
static AppDomain System.AppDomain.CreateDomain (string friendlyName, Evidence securityInfo, AppDomainSetup info) inline static
Definition at line 1107 of file AppDomain.cs.
        {
            if (friendlyName == null)
            {
                throw new ArgumentNullException("friendlyName");
            }
            AppDomain defaultDomain = AppDomain.DefaultDomain;
            if (info == null)
            {
                if (defaultDomain == null)
                {
                    info = new AppDomainSetup();
                }
                else
                {
                    info = defaultDomain.SetupInformation;
                }
            }
            else
            {
                info = new AppDomainSetup(info);
            }
            if (defaultDomain != null)
            {
                if (!info.Equals(defaultDomain.SetupInformation))
                {
                    if (info.ApplicationBase == null)
                    {
                        info.ApplicationBase = defaultDomain.SetupInformation.ApplicationBase;
                    }
                    if (info.ConfigurationFile == null)
                    {
                        info.ConfigurationFile = Path.GetFileName(defaultDomain.SetupInformation.ConfigurationFile);
                    }
                }
            }
            else if (info.ConfigurationFile == null)
            {
                info.ConfigurationFile = "[I don't have a config file]";
            }
            if (info.AppDomainInitializer != null && !info.AppDomainInitializer.Method.IsStatic)
            {
                throw new ArgumentException("Non-static methods cannot be invoked as an appdomain initializer");
            }
            info.SerializeNonPrimitives();
            AppDomain appDomain = (AppDomain)RemotingServices.GetDomainProxy(AppDomain.createDomain(friendlyName, info));
            if (securityInfo == null)
            {
                if (defaultDomain == null)
                {
                    appDomain._evidence = null;
                }
                else
                {
                    appDomain._evidence = defaultDomain.Evidence;
                }
            }
            else
            {
                appDomain._evidence = new Evidence(securityInfo);
            }
            if (info.AppDomainInitializer != null)
            {
                AppDomain.Loader loader = new AppDomain.Loader(info.AppDomainInitializer.Method.DeclaringType.Assembly.Location);
                appDomain.DoCallBack(new CrossAppDomainDelegate(loader.Load));
                AppDomain.Initializer initializer = new AppDomain.Initializer(info.AppDomainInitializer, info.AppDomainInitializerArguments);
                appDomain.DoCallBack(new CrossAppDomainDelegate(initializer.Initialize));
            }
            return appDomain;
        }
References System.AppDomain.AppDomain(), System.AppDomainSetup.ApplicationBase, System.AppDomainSetup.ConfigurationFile, System.AppDomain.createDomain(), System.CrossAppDomainDelegate(), System.AppDomain.DefaultDomain, System.AppDomain.DoCallBack(), System.AppDomain.Evidence, System.Runtime.Remoting.RemotingServices.GetDomainProxy(), System.IO.Path.GetFileName(), System.info, System.AppDomain.Initializer.Initialize(), System.AppDomain.Loader.Load(), and System.AppDomain.SetupInformation.