Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read
Read()
void System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Read (__BinaryParser input) inline
Implements System.Runtime.Serialization.Formatters.Binary.IStreamable.
Definition at line 46 of file SerializationHeaderRecord.cs.
        {
            byte[] array = input.ReadBytes(17);
            if (array.Length < 17)
            {
                __Error.EndOfFile();
            }
            this.majorVersion = SerializationHeaderRecord.GetInt32(array, 9);
            if (this.majorVersion > this.binaryFormatterMajorVersion)
            {
                throw new SerializationException(Environment.GetResourceString("The input stream is not a valid binary format. The starting contents (in bytes) are: {0} ...", new object[] { BitConverter.ToString(array) }));
            }
            this.binaryHeaderEnum = (BinaryHeaderEnum)array[0];
            this.topId = SerializationHeaderRecord.GetInt32(array, 1);
            this.headerId = SerializationHeaderRecord.GetInt32(array, 5);
            this.minorVersion = SerializationHeaderRecord.GetInt32(array, 13);
        }
References System.array, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.binaryFormatterMajorVersion, System.IO.__Error.EndOfFile(), System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.GetInt32(), System.Environment.GetResourceString(), System.input, and System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.majorVersion.
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryParser.ReadSerializationHeaderRecord().