Terraria Decompiled: System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Write
Write()
void System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.Write (__BinaryWriter sout) inline
Implements System.Runtime.Serialization.Formatters.Binary.IStreamable.
Definition at line 27 of file SerializationHeaderRecord.cs.
        {
            this.majorVersion = this.binaryFormatterMajorVersion;
            this.minorVersion = this.binaryFormatterMinorVersion;
            sout.WriteByte((byte)this.binaryHeaderEnum);
            sout.WriteInt32(this.topId);
            sout.WriteInt32(this.headerId);
            sout.WriteInt32(this.binaryFormatterMajorVersion);
            sout.WriteInt32(this.binaryFormatterMinorVersion);
        }
References System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.binaryFormatterMajorVersion, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.binaryFormatterMinorVersion, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.binaryHeaderEnum, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.headerId, System.Runtime.Serialization.Formatters.Binary.SerializationHeaderRecord.topId, System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteByte(), and System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteInt32().
Referenced by System.Runtime.Serialization.Formatters.Binary.__BinaryWriter.WriteSerializationHeader().