Terraria Decompiled: Newtonsoft.Json.Converters.IsoDateTimeConverter.WriteJson
WriteJson()
override void Newtonsoft.Json.Converters.IsoDateTimeConverter.WriteJson (JsonWriter writer, object value, JsonSerializer serializer) inline
Definition at line 56 of file IsoDateTimeConverter.cs.
        {
            string text;
            if (value is DateTime)
            {
                DateTime dateTime = (DateTime)value;
                if ((this._dateTimeStyles & 16) == 16 || (this._dateTimeStyles & 64) == 64)
                {
                    dateTime = dateTime.ToUniversalTime();
                }
                text = dateTime.ToString(this._dateTimeFormat ?? "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK", this.Culture);
            }
            else
            {
                if (!(value is DateTimeOffset))
                {
                    throw new JsonSerializationException("Unexpected value when converting date. Expected DateTime or DateTimeOffset, got {0}.".FormatWith(CultureInfo.InvariantCulture, ReflectionUtils.GetObjectType(value)));
                }
                DateTimeOffset dateTimeOffset = (DateTimeOffset)value;
                if ((this._dateTimeStyles & 16) == 16 || (this._dateTimeStyles & 64) == 64)
                {
                    dateTimeOffset = dateTimeOffset.ToUniversalTime();
                }
                text = dateTimeOffset.ToString(this._dateTimeFormat ?? "yyyy'-'MM'-'dd'T'HH':'mm':'ss.FFFFFFFK", this.Culture);
            }
            writer.WriteValue(text);
        }
References Newtonsoft.Json.Converters.IsoDateTimeConverter._dateTimeFormat, Newtonsoft.Json.Converters.IsoDateTimeConverter._dateTimeStyles, Newtonsoft.Json.Converters.IsoDateTimeConverter.Culture, Newtonsoft.Json.DateTime, Newtonsoft.Json.DateTimeOffset, Newtonsoft.Json.Utilities.ReflectionUtils.GetObjectType(), System.Globalization.CultureInfo.InvariantCulture, System.text, System.DateTime.ToString(), System.DateTimeOffset.ToString(), System.DateTime.ToUniversalTime(), System.DateTimeOffset.ToUniversalTime(), System.value, and Newtonsoft.Json.JsonWriter.WriteValue().