Terraria Decompiled: Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups
DrawItemTextPopups()
void Terraria.GameContent.UI.UIPopupTextManager.DrawItemTextPopups (float scaleTarget) inline
Definition at line 128 of file UIPopupTextManager.cs.
        {
            SpriteBatch spriteBatch = Main.spriteBatch;
            for (int i = 0; i < 20; i++)
            {
                UIPopupText uipopupText = this.popupText[i];
                if (uipopupText.active)
                {
                    string displayText = uipopupText.displayText;
                    Vector2 vector = FontAssets.MouseText.Value.MeasureString(displayText);
                    Vector2 vector2 = new Vector2(vector.X * 0.5f, vector.Y * 0.5f);
                    float num = scaleTarget;
                    float num2 = uipopupText.scale / num;
                    int num3 = (int)(255f - 255f * num2);
                    float num4 = (float)uipopupText.color.R;
                    float num5 = (float)uipopupText.color.G;
                    float num6 = (float)uipopupText.color.B;
                    float num7 = (float)uipopupText.color.A;
                    num4 *= num2 * uipopupText.alpha * 0.3f;
                    float alpha = uipopupText.alpha;
                    float alpha2 = uipopupText.alpha;
                    num7 *= num2 * uipopupText.alpha;
                    Color color = Color.Black;
                    float num8 = 1f;
                    Texture2D texture2D = null;
                    if (uipopupText.context == UIPopupTextContext.SpecialSeed)
                    {
                        color = Main.hslToRgb(Main.GlobalTimeWrappedHourly * 0.6f % 1f, 1f, 0.6f, byte.MaxValue) * 0.6f;
                        num *= 0.5f;
                        num8 = 0.8f;
                    }
                    int num9 = 40;
                    Utils.EaseOutCirc((double)Utils.Remap((float)uipopupText.framesSinceSpawn, 0f, (float)num9, 0f, 1f, true));
                    float num10 = (float)num3 / 255f;
                    for (int j = 0; j < 5; j++)
                    {
                        Color color2 = color;
                        float num11 = 0f;
                        float num12 = 0f;
                        if (j == 0)
{
                            num11 -= num * 2f;
                        }
                        else if (j == 1)
{
                            num11 += num * 2f;
                        }
                        else if (j == 2)
{
                            num12 -= num * 2f;
                        }
                        else if (j == 3)
{
                            num12 += num * 2f;
                        }
                        else
{
                            color2 = uipopupText.color * num2 * uipopupText.alpha * num8;
                        }
                        if (j < 4)
{
                            num7 = (float)uipopupText.color.A * num2 * uipopupText.alpha;
                            color2 = new Color(0, 0, 0, (int)num7);
                        }
                        if (color != Color.Black && j < 4)
{
                            num11 *= 1.3f + 1.3f * num10;
                            num12 *= 1.3f + 1.3f * num10;
                        }
                        float num13 = uipopupText.position.X + num11;
                        float num14 = uipopupText.position.Y + num12;
                        if (color != Color.Black && j < 4)
{
                            Color color3 = color;
                            color3.A = (byte)MathHelper.Lerp(60f, 127f, Utils.GetLerpValue(0f, 255f, num7, true));
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, displayText, new Vector2(num13 + vector2.X, num14 + vector2.Y), Color.Lerp(color2, color3, 0.5f), uipopupText.rotation, vector2, uipopupText.scale, SpriteEffects.None, 0f, null, null);
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, displayText, new Vector2(num13 + vector2.X, num14 + vector2.Y), color3, uipopupText.rotation, vector2, uipopupText.scale, SpriteEffects.None, 0f, null, null);
                        }
                        else
{
                            DynamicSpriteFontExtensionMethods.DrawString(spriteBatch, FontAssets.MouseText.Value, displayText, new Vector2(num13 + vector2.X, num14 + vector2.Y), color2, uipopupText.rotation, vector2, uipopupText.scale, SpriteEffects.None, 0f, null, null);
                        }
                        if (texture2D != null)
{
                            float num15 = (1.3f - num10) * uipopupText.scale * 0.7f;
                            Vector2 vector3 = new Vector2(num13 + vector2.X, num14 + vector2.Y);
                            Color color4 = color * 0.6f;
                            if (j == 4)
{
                                color4 = Color.White * 0.6f;
                            }
                            color4.A = (byte)((float)color4.A * 0.5f);
                            int num16 = 25;
                            spriteBatch.Draw(texture2D, vector3 + new Vector2(vector2.X * -0.5f - (float)num16 - texture2D.Size().X / 2f, 0f), null, color4 * uipopupText.scale, 0f, texture2D.Size() / 2f, num15, SpriteEffects.None, 0f);
                            spriteBatch.Draw(texture2D, vector3 + new Vector2(vector2.X * 0.5f + (float)num16 + texture2D.Size().X / 2f, 0f), null, color4 * uipopupText.scale, 0f, texture2D.Size() / 2f, num15, SpriteEffects.None, 0f);
                        }
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Color.A, Terraria.GameContent.UI.UIPopupText.active, Terraria.GameContent.UI.UIPopupText.alpha, Microsoft.Xna.Framework.Color.B, Microsoft.Xna.Framework.Color.Black, Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.UI.UIPopupText.color, Terraria.GameContent.UI.UIPopupText.context, Terraria.GameContent.UI.UIPopupText.displayText, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), ReLogic.Graphics.DynamicSpriteFontExtensionMethods.DrawString(), Terraria.Utils.EaseOutCirc(), Terraria.GameContent.UI.UIPopupText.framesSinceSpawn, Microsoft.Xna.Framework.Color.G, Terraria.Utils.GetLerpValue(), Terraria.Main.GlobalTimeWrappedHourly, Terraria.Main.hslToRgb(), int, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.MathHelper.Lerp(), Terraria.GameContent.FontAssets.MouseText, Terraria.GameContent.UI.UIPopupTextManager.popupText, Microsoft.Xna.Framework.Color.R, Terraria.Utils.Remap(), Terraria.GameContent.UI.UIPopupText.rotation, Terraria.GameContent.UI.UIPopupText.scale, Terraria.Main.spriteBatch, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.