Terraria Decompiled: Newtonsoft.Json.Converters.IsoDateTimeConverter.ReadJson
ReadJson()
override object Newtonsoft.Json.Converters.IsoDateTimeConverter.ReadJson (JsonReader reader, Type objectType, object existingValue, JsonSerializer serializer) inline
Definition at line 85 of file IsoDateTimeConverter.cs.
        {
            bool flag = ReflectionUtils.IsNullableType(objectType);
            Type type = (flag ? Nullable.GetUnderlyingType(objectType) : objectType);
            if (reader.TokenType == JsonToken.Null)
            {
                if (!ReflectionUtils.IsNullableType(objectType))
                {
                    throw JsonSerializationException.Create(reader, "Cannot convert null value to {0}.".FormatWith(CultureInfo.InvariantCulture, objectType));
                }
                return null;
            }
            else if (reader.TokenType == JsonToken.Date)
            {
                if (type == typeof(DateTimeOffset))
                {
                    if (!(reader.Value is DateTimeOffset))
                    {
                        return new DateTimeOffset((DateTime)reader.Value);
                    }
                    return reader.Value;
                }
                else
                {
                    if (reader.Value is DateTimeOffset)
                    {
                        return ((DateTimeOffset)reader.Value).DateTime;
                    }
                    return reader.Value;
                }
            }
            else
            {
                if (reader.TokenType != JsonToken.String)
                {
                    throw JsonSerializationException.Create(reader, "Unexpected token parsing date. Expected String, got {0}.".FormatWith(CultureInfo.InvariantCulture, reader.TokenType));
                }
                string text = reader.Value.ToString();
                if (string.IsNullOrEmpty(text) && flag)
                {
                    return null;
                }
                if (type == typeof(DateTimeOffset))
                {
                    if (!string.IsNullOrEmpty(this._dateTimeFormat))
                    {
                        return DateTimeOffset.ParseExact(text, this._dateTimeFormat, this.Culture, this._dateTimeStyles);
                    }
                    return DateTimeOffset.Parse(text, this.Culture, this._dateTimeStyles);
                }
                else
                {
                    if (!string.IsNullOrEmpty(this._dateTimeFormat))
                    {
                        return DateTime.ParseExact(text, this._dateTimeFormat, this.Culture, this._dateTimeStyles);
                    }
                    return DateTime.Parse(text, this.Culture, this._dateTimeStyles);
                }
            }
        }
References Newtonsoft.Json.Converters.IsoDateTimeConverter._dateTimeFormat, Newtonsoft.Json.Converters.IsoDateTimeConverter._dateTimeStyles, Newtonsoft.Json.JsonSerializationException.Create(), Newtonsoft.Json.Converters.IsoDateTimeConverter.Culture, Newtonsoft.Json.DateTimeOffset, System.Nullable< T >.GetUnderlyingType(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Utilities.ReflectionUtils.IsNullableType(), System.DateTimeOffset.Parse(), System.DateTime.Parse(), System.DateTimeOffset.ParseExact(), System.DateTime.ParseExact(), System.text, Newtonsoft.Json.JsonReader.TokenType, and Newtonsoft.Json.JsonReader.Value.