Terraria Decompiled: System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CompleteTaskAsync
CompleteTaskAsync()
void System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CompleteTaskAsync () inline private
Definition at line 157 of file ConcurrentExclusiveSchedulerPair.cs.
        {
            ConcurrentExclusiveSchedulerPair.CompletionState completionState = this.EnsureCompletionStateInitialized();
            if (!completionState.m_completionQueued)
            {
                completionState.m_completionQueued = true;
                ThreadPool.QueueUserWorkItem(delegate(object state)
                {
                    ConcurrentExclusiveSchedulerPair concurrentExclusiveSchedulerPair = (ConcurrentExclusiveSchedulerPair)state;
                    List<Exception> exceptions = concurrentExclusiveSchedulerPair.m_completionState.m_exceptions;
                    if (exceptions == null || exceptions.Count <= 0)
                    {
                        concurrentExclusiveSchedulerPair.m_completionState.TrySetResult(default(VoidTaskResult));
                    }
                    else
                    {
                        concurrentExclusiveSchedulerPair.m_completionState.TrySetException(exceptions);
                    }
                    concurrentExclusiveSchedulerPair.m_threadProcessingMode.Dispose();
                }, this);
            }
        }
References System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.ConcurrentExclusiveSchedulerPair(), System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.EnsureCompletionStateInitialized(), System.exceptions, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CompletionState.m_completionQueued, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_completionState, System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.m_threadProcessingMode, System.Threading.ThreadPool.QueueUserWorkItem(), and System.state.
Referenced by System.Threading.Tasks.ConcurrentExclusiveSchedulerPair.CleanupStateIfCompletingAndQuiesced().