Terraria Decompiled: System.IO.Path.GetRandomFileName
GetRandomFileName()
static string System.IO.Path.GetRandomFileName () inline static
Definition at line 623 of file Path.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(12);
            RandomNumberGenerator randomNumberGenerator = RandomNumberGenerator.Create();
            byte[] array = new byte[11];
            randomNumberGenerator.GetBytes(array);
            for (int i = 0; i < array.Length; i++)
            {
                if (stringBuilder.Length == 8)
                {
                    stringBuilder.Append('.');
                }
                int num = (int)(array[i] % 36);
                char c = (char)((num < 26) ? (num + 97) : (num - 26 + 48));
                stringBuilder.Append(c);
            }
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.array, System.Security.Cryptography.RandomNumberGenerator.Create(), System.Security.Cryptography.RandomNumberGenerator.GetBytes(), int, System.Text.StringBuilder.Length, and System.Text.StringBuilder.ToString().