Terraria Decompiled: System.IO.Path.GetFileName
GetFileName() [2/2]
static string System.IO.Path.GetFileName (string path) inline static
Definition at line 251 of file Path.cs.
        {
            if (path == null || path.Length == 0)
            {
                return path;
            }
            if (path.IndexOfAny(Path.InvalidPathChars) != -1)
            {
                throw new ArgumentException("Illegal characters in path.");
            }
            int num = path.LastIndexOfAny(Path.PathSeparatorChars);
            if (num >= 0)
            {
                return path.Substring(num + 1);
            }
            return path;
        }
References System.IO.Path.InvalidPathChars, and System.IO.Path.PathSeparatorChars.
Referenced by System.Reflection.Emit.AssemblyBuilder.check_name_and_filename(), System.IO.FileSystem.CopyFile(), System.AppDomain.CreateDomain(), Terraria.IO.ResourcePackList.CreatePacksFromDirectories(), Terraria.IO.ResourcePackList.CreatePacksFromWorkshopFolders(), Terraria.IO.ResourcePackList.CreatePacksFromZips(), System.IO.FileInfo.FileInfo(), System.IO.FileInfo.FileInfo(), System.AppDomainSetup.GetAppBase(), System.IO.IsolatedStorage.IsolatedStorageFile.GetDirectoryNames(), System.IO.__Error.GetDisplayablePath(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames(), System.IO.Path.GetFileNameWithoutExtension(), System.IO.FileStream.GetSecureFileName(), System.IO.FileStream.GetSecureFileName(), System.IO.DirectoryInfo.Init(), System.IO.FileInfo.MoveTo(), ReLogic.OS.Linux.PathService.MoveToRecycleBin(), Ionic.Zip.ZipEntry.NameInArchive(), System.IO.FileSystem.RemoveDirectoryInternal(), Ionic.Zip.ZipFile.RemoveEntryForUpdate(), Terraria.IO.ResourcePack.ResourcePack(), System.Resources.ResourceReader.ResourceReader(), System.Security.Permissions.FileIOPermission.ThrowIfInvalidPath(), and Ionic.Zip.ZipEntry.ValidateOutput().