Terraria Decompiled: System.IO.Path.GetFullPathName
GetFullPathName() [1/2]
static string System.IO.Path.GetFullPathName (string path) inline static package
Definition at line 292 of file Path.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(260);
            IntPtr zero = IntPtr.Zero;
            int fullPathName = Path.GetFullPathName(path, 260, stringBuilder, ref zero);
            if (fullPathName == 0)
            {
                throw new IOException("Windows API call to GetFullPathName failed, Windows error code: " + Marshal.GetLastWin32Error().ToString());
            }
            if (fullPathName > 260)
            {
                stringBuilder = new StringBuilder(fullPathName);
                Path.GetFullPathName(path, fullPathName, stringBuilder, ref zero);
            }
            return stringBuilder.ToString();
        }
References System.IO.Path.GetFullPathName(), System.Runtime.InteropServices.Marshal.GetLastWin32Error(), System.Text.StringBuilder.ToString(), and System.IntPtr.Zero.