Terraria Decompiled: System.IO.Path.GetTempFileName
GetTempFileName()
static string System.IO.Path.GetTempFileName () inline static
Definition at line 498 of file Path.cs.
        {
            FileStream fileStream = null;
            int num = 0;
            Random random = new Random();
            string tempPath = Path.GetTempPath();
            string text;
            do
            {
                int num2 = random.Next();
                text = Path.Combine(tempPath, "tmp" + (num2 + 1).ToString("x", CultureInfo.InvariantCulture) + ".tmp");
                try
                {
                    fileStream = new FileStream(text, FileMode.CreateNew, FileAccess.ReadWrite, FileShare.Read, 8192, false, (FileOptions)1);
                }
                catch (IOException ex)
                {
                    if (ex._HResult != -2147024816 || num++ > 65536)
                    {
                        throw;
                    }
                }
                catch (UnauthorizedAccessException ex2)
                {
                    if (num++ > 65536)
                    {
                        throw new IOException(ex2.Message, ex2);
                    }
                }
            }
            while (fileStream == null);
            fileStream.Close();
            return text;
        }
References System.Exception._HResult, System.IO.Stream.Close(), System.IO.Path.Combine(), System.IO.Path.GetTempPath(), System.Globalization.CultureInfo.InvariantCulture, System.Exception.Message, System.Random.Next(), System.text, and System.ToString.
Referenced by System.Resources.ResourceWriter.Generate().