Terraria Decompiled: System.IO.Path.CanonicalizePath
CanonicalizePath()
static string System.IO.Path.CanonicalizePath (string path) inline static private
Definition at line 702 of file Path.cs.
        {
            if (path == null)
            {
                return path;
            }
            if (Environment.IsRunningOnWindows)
            {
                path = path.Trim();
            }
            if (path.Length == 0)
            {
                return path;
            }
            string pathRoot = Path.GetPathRoot(path);
            string[] array = path.Split(new char[]
            {
                Path.DirectorySeparatorChar,
                Path.AltDirectorySeparatorChar
            });
            int num = 0;
            bool flag = Environment.IsRunningOnWindows && pathRoot.Length > 2 && Path.IsDirectorySeparator(pathRoot[0]) && Path.IsDirectorySeparator(pathRoot[1]);
            int num2 = (flag ? 3 : 0);
            for (int i = 0; i < array.Length; i++)
            {
                if (Environment.IsRunningOnWindows)
                {
                    array[i] = array[i].TrimEnd();
                }
                if (((flag && i == 2) || !(array[i] == ".")) && (i == 0 || array[i].Length != 0))
                {
                    if (array[i] == "..")
                    {
                        if (num > num2)
{
                            num--;
                        }
                    }
                    else
                    {
                        array[num++] = array[i];
                    }
                }
            }
            if (num == 0 || (num == 1 && array[0] == ""))
            {
                return pathRoot;
            }
            string text = string.Join(Path.DirectorySeparatorStr, array, 0, num);
            if (!Environment.IsRunningOnWindows)
            {
                if (pathRoot != "" && text.Length > 0 && text[0] != '/')
                {
                    text = pathRoot + text;
                }
                return text;
            }
            if (flag)
            {
                text = Path.DirectorySeparatorStr + text;
            }
            if (!Path.SameRoot(pathRoot, text))
            {
                text = pathRoot + text;
            }
            if (flag)
            {
                return text;
            }
            if (!Path.IsDirectorySeparator(path[0]) && Path.SameRoot(pathRoot, path))
            {
                if (text.Length <= 2 && !text.EndsWith(Path.DirectorySeparatorStr))
                {
                    text += Path.DirectorySeparatorChar.ToString();
                }
                return text;
            }
            string currentDirectory = Directory.GetCurrentDirectory();
            if (currentDirectory.Length > 1 && currentDirectory[1] == Path.VolumeSeparatorChar)
            {
                if (text.Length == 0 || Path.IsDirectorySeparator(text[0]))
                {
                    text += "\\";
                }
                return currentDirectory.Substring(0, 2) + text;
            }
            if (Path.IsDirectorySeparator(currentDirectory[currentDirectory.Length - 1]) && Path.IsDirectorySeparator(text[0]))
            {
                return currentDirectory + text.Substring(1);
            }
            return currentDirectory + text;
        }
References System.array, System.IO.Path.DirectorySeparatorChar, System.IO.Path.DirectorySeparatorStr, System.IO.Directory.GetCurrentDirectory(), System.IO.Path.GetPathRoot(), System.IO.Path.IsDirectorySeparator(), System.IO.Path.SameRoot(), System.text, and System.IO.Path.VolumeSeparatorChar.
Referenced by System.IO.Path.InsecureGetFullPath().