Terraria Decompiled: System.IO.Path.GetPathRoot
GetPathRoot() [2/2]
static string System.IO.Path.GetPathRoot (string path) inline static
Definition at line 431 of file Path.cs.
        {
            if (path == null)
            {
                return null;
            }
            if (path.Trim().Length == 0)
            {
                throw new ArgumentException("The specified path is not of a legal form.");
            }
            if (!Path.IsPathRooted(path))
            {
                return string.Empty;
            }
            if (Path.DirectorySeparatorChar == '/')
            {
                if (!Path.IsDirectorySeparator(path[0]))
                {
                    return string.Empty;
                }
                return Path.DirectorySeparatorStr;
            }
            else
            {
                int num = 2;
                if (path.Length == 1 && Path.IsDirectorySeparator(path[0]))
                {
                    return Path.DirectorySeparatorStr;
                }
                if (path.Length < 2)
                {
                    return string.Empty;
                }
                if (Path.IsDirectorySeparator(path[0]) && Path.IsDirectorySeparator(path[1]))
                {
                    while (num < path.Length && !Path.IsDirectorySeparator(path[num]))
                    {
                        num++;
                    }
                    if (num < path.Length)
                    {
                        num++;
                        while (num < path.Length && !Path.IsDirectorySeparator(path[num]))
{
                            num++;
                        }
                    }
                    return Path.DirectorySeparatorStr + Path.DirectorySeparatorStr + path.Substring(2, num - 2).Replace(Path.AltDirectorySeparatorChar, Path.DirectorySeparatorChar);
                }
                if (Path.IsDirectorySeparator(path[0]))
                {
                    return Path.DirectorySeparatorStr;
                }
                if (path[1] == Path.VolumeSeparatorChar)
                {
                    if (path.Length >= 3 && Path.IsDirectorySeparator(path[2]))
                    {
                        num++;
                    }
                    return path.Substring(0, num);
                }
                return Directory.GetCurrentDirectory().Substring(0, 2);
            }
        }
References System.IO.Path.AltDirectorySeparatorChar, System.IO.Path.DirectorySeparatorChar, System.IO.Path.DirectorySeparatorStr, System.IO.Directory.GetCurrentDirectory(), System.IO.Path.IsDirectorySeparator(), System.IO.Path.IsPathRooted(), and System.IO.Path.VolumeSeparatorChar.
Referenced by System.IO.Path.CanonicalizePath(), System.IO.IsolatedStorage.IsolatedStorageFileStream.CreateIsolatedPath(), System.IO.Path.GetDirectoryName(), System.IO.Path.GetFileName(), System.IO.Path.GetPathRoot(), Microsoft.Xna.Framework.SDL2_FNAPlatform.MonoPathRootWorkaround(), Microsoft.Xna.Framework.SDL3_FNAPlatform.MonoPathRootWorkaround(), System.IO.Directory.Move(), System.IO.DirectoryInfo.MoveTo(), and System.IO.Path.WindowsDriveAdjustment().