Terraria Decompiled: System.IO.Path.Combine
Combine() [2/4]
static string System.IO.Path.Combine (string path1, string path2) inline static
Definition at line 70 of file Path.cs.
        {
            if (path1 == null)
            {
                throw new ArgumentNullException("path1");
            }
            if (path2 == null)
            {
                throw new ArgumentNullException("path2");
            }
            if (path1.Length == 0)
            {
                return path2;
            }
            if (path2.Length == 0)
            {
                return path1;
            }
            if (path1.IndexOfAny(Path.InvalidPathChars) != -1)
            {
                throw new ArgumentException("Illegal characters in path.");
            }
            if (path2.IndexOfAny(Path.InvalidPathChars) != -1)
            {
                throw new ArgumentException("Illegal characters in path.");
            }
            if (Path.IsPathRooted(path2))
            {
                return path2;
            }
            char c = path1[path1.Length - 1];
            if (c != Path.DirectorySeparatorChar && c != Path.AltDirectorySeparatorChar && c != Path.VolumeSeparatorChar)
            {
                return path1 + Path.DirectorySeparatorStr + path2;
            }
            return path1 + path2;
        }
References System.IO.Path.AltDirectorySeparatorChar, System.IO.Path.DirectorySeparatorChar, System.IO.Path.InvalidPathChars, System.IO.Path.IsPathRooted(), and System.IO.Path.VolumeSeparatorChar.
Referenced by Ionic.Zip.ZipFile._InternalExtractAll(), Ionic.Zip.ZipSegmentedStream._NameForSegment(), Ionic.Zip.ZipFile.AddFiles(), Ionic.Zip.ZipFile.AddOrUpdateDirectoryImpl(), System.Reflection.Emit.AssemblyBuilder.AddResourceFile(), System.Reflection.Emit.AssemblyBuilder.check_name_and_filename(), Microsoft.Xna.Framework.Content.ContentManager.CheckRawExtensions(), Microsoft.Win32.KeyHandler.CleanVolatileKeys(), System.IO.Path.Combine(), System.IO.Path.Combine(), System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile(), System.IO.FileSystem.CopyFile(), Ionic.Zip.SharedUtilities.CreateAndOpenUniqueTempFile(), Microsoft.Xna.Framework.Storage.StorageContainer.CreateDirectory(), Microsoft.Xna.Framework.Storage.StorageContainer.CreateFile(), System.IO.IsolatedStorage.IsolatedStorageFileStream.CreateIsolatedPath(), Terraria.IO.ResourcePackList.CreatePacksFromSavedJson(), System.IO.DirectoryInfo.CreateSubdirectory(), Microsoft.Xna.Framework.SDL2_FNAPlatform.CreateWindow(), Microsoft.Xna.Framework.SDL3_FNAPlatform.CreateWindow(), Microsoft.Xna.Framework.Storage.StorageContainer.DeleteDirectory(), Microsoft.Xna.Framework.Storage.StorageContainer.DeleteFile(), System.IO.IsolatedStorage.IsolatedStorageFile.DeleteFile(), Microsoft.Win32.UnixRegistryApi.DeleteKey(), Microsoft.Xna.Framework.Storage.StorageContainer.DirectoryExists(), System.IO.IsolatedStorage.IsolatedStorageFile.DirectoryExists(), Terraria.Testing.PacketHistory.Dump(), Microsoft.Win32.KeyHandler.Ensure(), Microsoft.Xna.Framework.Storage.StorageContainer.FileExists(), System.IO.IsolatedStorage.IsolatedStorageFile.FileExists(), System.Resources.FileBasedResourceGroveler.FindResourceFile(), System.TimeZoneInfo.FindTimeZoneId(), System.TimeZoneInfo.FindTimeZoneIdUsingReadLink(), Ionic.Zip.ZipSegmentedStream.ForUpdate(), Microsoft.Xna.Framework.Media.Song.FromUri(), Microsoft.Xna.Framework.Media.Video.FromUriEXT(), ReLogic.Content.Sources.XnaContentSource.GetAllAssetsStartingWith(), ReLogic.Content.Sources.XnaDirectContentSource.GetAllAssetsStartingWith(), Terraria.IO.ResourcePack.GetContentSource(), System.IO.IsolatedStorage.IsolatedStorageFile.GetCreationTime(), System.IO.PathInternal.GetIsCaseSensitive(), System.IO.IsolatedStorage.IsolatedStorageFile.GetIsolatedStorageRoot(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastAccessTime(), System.IO.IsolatedStorage.IsolatedStorageFile.GetLastWriteTime(), System.Reflection.RuntimeAssembly.GetManifestResourceStream(), Terraria.Initializers.AssetInitializer.GetResourcePacksFolderPathAndConfirmItExists(), ReLogic.OS.Windows.PathService.GetStoragePath(), ReLogic.OS.Base.PathService.GetStoragePath(), Microsoft.Xna.Framework.SDL2_FNAPlatform.GetStorageRoot(), Microsoft.Xna.Framework.SDL3_FNAPlatform.GetStorageRoot(), System.IO.Path.GetTempFileName(), System.TimeZoneInfo.GetTimeZoneIds(), Microsoft.Win32.KeyHandler.GetVolatileDir(), ReLogic.Content.Sources.XnaContentSource.HasAsset(), ReLogic.Content.Sources.XnaDirectContentSource.HasAsset(), Terraria.IO.ResourcePack.HasFile(), Terraria.Testing.GitStatus.HasGitFolder(), System.Security.SecurityManager.InitializePolicyHierarchy(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_GetIconName(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_GetIconName(), System.Reflection.Assembly.InternalGetSatelliteAssembly(), Microsoft.Win32.KeyHandler.KeyHandler(), Microsoft.Win32.KeyHandler.Lookup(), System.Reflection.Emit.ModuleBuilder.ModuleBuilder(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile(), ReLogic.OS.Linux.PathService.MoveToRecycleBin(), Ionic.Zip.ZipEntry.NameInArchive(), Microsoft.Xna.Framework.Storage.StorageContainer.OpenFile(), Terraria.Testing.ChatCommands.DebugCommandProcessor.OpenMemo(), Microsoft.Xna.Framework.Content.ContentManager.OpenStream(), ReLogic.Content.Sources.XnaContentSource.OpenStream(), ReLogic.Content.Sources.XnaDirectContentSource.OpenStream(), Terraria.IO.ResourcePack.OpenStream(), Microsoft.Xna.Framework.TitleContainer.OpenStream(), System.IO.IsolatedStorage.IsolatedStorageFile.PostInit(), Microsoft.Win32.KeyHandler.Probe(), Microsoft.Xna.Framework.SDL2_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.SDL3_FNAPlatform.ProgramInit(), Microsoft.Xna.Framework.Content.SongReader.Read(), Microsoft.Xna.Framework.Content.VideoReader.Read(), Microsoft.Xna.Framework.TitleContainer.ReadToPointer(), System.Reflection.Emit.ModuleBuilder.Save(), System.Reflection.Emit.AssemblyBuilder.Save(), Terraria.Graphics.Capture.CaptureCamera.SaveImage(), Terraria.Program.SetupLogging(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotLoadCommand(), Terraria.Testing.ChatCommands.ToolkitDebugCommands.SnapshotSaveCommand(), Microsoft.Xna.Framework.Storage.StorageContainer.StorageContainer(), System.TimeZoneInfo.TryGetLocalTzFile(), System.TimeZoneInfo.TryGetTimeZoneFromLocalMachine(), Terraria.Testing.ChatCommands.DebugCommandProcessor.TryProcessMemo(), System.TermInfoDriver.TryTermInfoDir(), Terraria.Graphics.Capture.CaptureInterface.UpdateButtons(), Ionic.Zip.ZipEntry.ValidateOutput(), Microsoft.Xna.Framework.Audio.WaveBank.WaveBank(), System.IO.Path.WindowsDriveAdjustment(), and Terraria.Utilities.CrashDump.Write().