Terraria Decompiled: System.IO.Path.WindowsDriveAdjustment
WindowsDriveAdjustment()
static string System.IO.Path.WindowsDriveAdjustment (string path) inline static package
Definition at line 310 of file Path.cs.
        {
            if (path.Length < 2)
            {
                if (path.Length == 1 && (path[0] == '\\' || path[0] == '/'))
                {
                    return Path.GetPathRoot(Directory.GetCurrentDirectory());
                }
                return path;
            }
            else
            {
                if (path[1] != ':' || !char.IsLetter(path[0]))
                {
                    return path;
                }
                string text = Directory.InsecureGetCurrentDirectory();
                if (path.Length == 2)
                {
                    if (text[0] == path[0])
                    {
                        path = text;
                    }
                    else
                    {
                        path = Path.GetFullPathName(path);
                    }
                }
                else if (path[2] != Path.DirectorySeparatorChar && path[2] != Path.AltDirectorySeparatorChar)
                {
                    if (text[0] == path[0])
                    {
                        path = Path.Combine(text, path.Substring(2, path.Length - 2));
                    }
                    else
                    {
                        path = Path.GetFullPathName(path);
                    }
                }
                return path;
            }
        }
References System.IO.Path.AltDirectorySeparatorChar, System.IO.Path.Combine(), System.IO.Path.DirectorySeparatorChar, System.IO.Directory.GetCurrentDirectory(), System.IO.Path.GetFullPathName(), System.IO.Path.GetPathRoot(), System.IO.Directory.InsecureGetCurrentDirectory(), and System.text.
Referenced by System.IO.Path.InsecureGetFullPath().