Terraria Decompiled: System.IO.Path.GetDirectoryName
GetDirectoryName() [2/2]
static string System.IO.Path.GetDirectoryName (string path) inline static
Definition at line 185 of file Path.cs.
        {
            if (path == string.Empty)
            {
                throw new ArgumentException("Invalid path");
            }
            if (path == null || Path.GetPathRoot(path) == path)
            {
                return null;
            }
            if (path.Trim().Length == 0)
            {
                throw new ArgumentException("Argument string consists of whitespace characters only.");
            }
            if (path.IndexOfAny(Path.InvalidPathChars) > -1)
            {
                throw new ArgumentException("Path contains invalid characters");
            }
            int num = path.LastIndexOfAny(Path.PathSeparatorChars);
            if (num == 0)
            {
                num++;
            }
            if (num <= 0)
            {
                return string.Empty;
            }
            string text = path.Substring(0, num);
            int length = text.Length;
            if (length >= 2 && Path.DirectorySeparatorChar == '\\' && text[length - 1] == Path.VolumeSeparatorChar)
            {
                return text + Path.DirectorySeparatorChar.ToString();
            }
            if (length == 1 && Path.DirectorySeparatorChar == '\\' && path.Length >= 2 && path[num] == Path.VolumeSeparatorChar)
            {
                return text + Path.VolumeSeparatorChar.ToString();
            }
            return Path.CleanPath(text);
        }
References System.IO.Path.CleanPath(), System.IO.Path.DirectorySeparatorChar, System.IO.Path.GetPathRoot(), System.IO.Path.InvalidPathChars, System.length, System.IO.Path.PathSeparatorChars, System.text, and System.IO.Path.VolumeSeparatorChar.
Referenced by Ionic.Zip.ZipSegmentedStream._NameForSegment(), Ionic.Zip.ZipFile.AddFiles(), System.IO.IsolatedStorage.IsolatedStorageFile.CopyFile(), System.IO.FileStream.FileStream(), Ionic.Zip.ZipSegmentedStream.ForUpdate(), Ionic.Zip.ZipSegmentedStream.ForWriting(), System.AppDomainSetup.GetAppBase(), System.IO.Path.GetDirectoryName(), System.IO.IsolatedStorage.IsolatedStorageFile.GetDirectoryNames(), System.IO.IsolatedStorage.IsolatedStorageFile.GetFileNames(), System.Reflection.RuntimeAssembly.GetManifestResourceStream(), System.IO.Directory.GetParent(), System.Runtime.InteropServices.RuntimeEnvironment.GetRuntimeDirectoryImpl(), ReLogic.Content.Sources.XnaContentSource.GetTitleLocationPath(), Terraria.Testing.GitStatus.HasGitFolder(), System.Resources.FileBasedResourceGroveler.HasNeutralResources(), System.Security.SecurityManager.InitializePolicyHierarchy(), Ionic.Zip.ZipEntry.InternalExtract(), System.Reflection.Assembly.InternalGetSatelliteAssembly(), System.IO.FileSystem.LinkOrCopyFile(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveDirectory(), System.IO.IsolatedStorage.IsolatedStorageFile.MoveFile(), System.IO.FileInfo.MoveTo(), System.IO.Enumeration.FileSystemEnumerableFactory.NormalizeInputs(), Ionic.Zip.ZipFile.RemoveEntryForUpdate(), System.Security.Permissions.FileIOPermission.ThrowIfInvalidPath(), and System.IO.FileSystemInfo.ThrowNotFound().