Terraria Decompiled: XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.PrepareForSampleRead
PrepareForSampleRead()
virtual void XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.PrepareForSampleRead (Header header, int allocation, int channel, float[] factor, int[] codelength, float[] c, float[] d) inline protected virtual
Definition at line 75 of file SubbandLayer2.cs.
        {
            int num = header.bitrate_index();
            if (header.Mode() != 3)
            {
                if (num == 4)
                {
                    num = 1;
                }
                else
                {
                    num -= 4;
                }
            }
            if (num == 1 || num == 2)
            {
                this.Groupingtable[channel] = SubbandLayer2.TableCdGroupingtables[allocation];
                factor[0] = SubbandLayer2.TableCdFactor[allocation];
                codelength[0] = SubbandLayer2.TableCdCodelength[allocation];
                c[0] = SubbandLayer2.TableCdC[allocation];
                d[0] = SubbandLayer2.TableCdD[allocation];
                return;
            }
            if (this.Subbandnumber <= 2)
            {
                this.Groupingtable[channel] = SubbandLayer2.TableAb1Groupingtables[allocation];
                factor[0] = SubbandLayer2.TableAb1Factor[allocation];
                codelength[0] = SubbandLayer2.TableAb1Codelength[allocation];
                c[0] = SubbandLayer2.TableAb1C[allocation];
                d[0] = SubbandLayer2.TableAb1D[allocation];
                return;
            }
            this.Groupingtable[channel] = SubbandLayer2.TableAb234Groupingtables[allocation];
            if (this.Subbandnumber <= 10)
            {
                factor[0] = SubbandLayer2.TableAb2Factor[allocation];
                codelength[0] = SubbandLayer2.TableAb2Codelength[allocation];
                c[0] = SubbandLayer2.TableAb2C[allocation];
                d[0] = SubbandLayer2.TableAb2D[allocation];
                return;
            }
            if (this.Subbandnumber <= 22)
            {
                factor[0] = SubbandLayer2.TableAb3Factor[allocation];
                codelength[0] = SubbandLayer2.TableAb3Codelength[allocation];
                c[0] = SubbandLayer2.TableAb3C[allocation];
                d[0] = SubbandLayer2.TableAb3D[allocation];
                return;
            }
            factor[0] = SubbandLayer2.TableAb4Factor[allocation];
            codelength[0] = SubbandLayer2.TableAb4Codelength[allocation];
            c[0] = SubbandLayer2.TableAb4C[allocation];
            d[0] = SubbandLayer2.TableAb4D[allocation];
        }
References XPT.Core.Audio.MP3Sharp.Decoding.Header.bitrate_index(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.Groupingtable, XPT.Core.Audio.MP3Sharp.Decoding.Header.Mode(), XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.Subbandnumber, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb1C, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb1Codelength, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb1D, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb1Factor, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb1Groupingtables, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb234Groupingtables, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb2C, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb2Codelength, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb2D, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb2Factor, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb3C, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb3Codelength, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb3D, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb3Factor, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb4C, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb4Codelength, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb4D, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableAb4Factor, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableCdC, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableCdCodelength, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableCdD, XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableCdFactor, and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.TableCdGroupingtables.
Referenced by XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2.ReadScaleFactor(), and XPT.Core.Audio.MP3Sharp.Decoding.Decoders.LayerII.SubbandLayer2Stereo.ReadScaleFactor().