Terraria Decompiled: System.Security.Policy.DefaultPolicies.BuildInternet
BuildInternet()
static NamedPermissionSet System.Security.Policy.DefaultPolicies.BuildInternet () inline static private
Definition at line 230 of file DefaultPolicies.cs.
        {
            NamedPermissionSet namedPermissionSet = new NamedPermissionSet("Internet", PermissionState.None);
            namedPermissionSet.AddPermission(new FileDialogPermission(FileDialogPermissionAccess.Open));
            namedPermissionSet.AddPermission(new IsolatedStorageFilePermission(PermissionState.None)
            {
                UsageAllowed = IsolatedStorageContainment.DomainIsolationByUser,
                UserQuota = 512000L
            });
            namedPermissionSet.AddPermission(new SecurityPermission(SecurityPermissionFlag.Execution));
            namedPermissionSet.AddPermission(new UIPermission(UIPermissionWindow.SafeTopLevelWindows, UIPermissionClipboard.OwnClipboard));
            namedPermissionSet.AddPermission(PermissionBuilder.Create(DefaultPolicies.PrintingPermission("SafePrinting")));
            return namedPermissionSet;
        }
References System.Security.PermissionSet.AddPermission(), System.Security.PermissionBuilder.Create(), and System.Security.Policy.DefaultPolicies.PrintingPermission().