Terraria Decompiled: System.Security.Policy.DefaultPolicies.BuildLocalIntranet
BuildLocalIntranet()
static NamedPermissionSet System.Security.Policy.DefaultPolicies.BuildLocalIntranet () inline static private
Definition at line 210 of file DefaultPolicies.cs.
        {
            NamedPermissionSet namedPermissionSet = new NamedPermissionSet("LocalIntranet", PermissionState.None);
            namedPermissionSet.AddPermission(new EnvironmentPermission(EnvironmentPermissionAccess.Read, "USERNAME;USER"));
            namedPermissionSet.AddPermission(new FileDialogPermission(PermissionState.Unrestricted));
            namedPermissionSet.AddPermission(new IsolatedStorageFilePermission(PermissionState.None)
            {
                UsageAllowed = IsolatedStorageContainment.AssemblyIsolationByUser,
                UserQuota = long.MaxValue
            });
            namedPermissionSet.AddPermission(new ReflectionPermission(ReflectionPermissionFlag.ReflectionEmit));
            SecurityPermissionFlag securityPermissionFlag = SecurityPermissionFlag.Assertion | SecurityPermissionFlag.Execution;
            namedPermissionSet.AddPermission(new SecurityPermission(securityPermissionFlag));
            namedPermissionSet.AddPermission(new UIPermission(PermissionState.Unrestricted));
            namedPermissionSet.AddPermission(PermissionBuilder.Create("System.Net.DnsPermission, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089", PermissionState.Unrestricted));
            namedPermissionSet.AddPermission(PermissionBuilder.Create(DefaultPolicies.PrintingPermission("SafePrinting")));
            return namedPermissionSet;
        }
References System.Security.PermissionSet.AddPermission(), System.Security.PermissionBuilder.Create(), and System.Security.Policy.DefaultPolicies.PrintingPermission().