Terraria Decompiled: Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T >
CreateGet< T >() [2/2]
override Func< T, object > Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T > (PropertyInfo propertyInfo) inline
Definition at line 157 of file ExpressionReflectionDelegateFactory.cs.
        {
            ValidationUtils.ArgumentNotNull(propertyInfo, "propertyInfo");
            Type typeFromHandle = typeof(T);
            Type typeFromHandle2 = typeof(object);
            ParameterExpression parameterExpression = Expression.Parameter(typeFromHandle, "instance");
            Expression expression;
            if (propertyInfo.GetGetMethod(true).IsStatic)
            {
                expression = Expression.MakeMemberAccess(null, propertyInfo);
            }
            else
            {
                expression = Expression.MakeMemberAccess(this.EnsureCastExpression(parameterExpression, propertyInfo.DeclaringType, false), propertyInfo);
            }
            expression = this.EnsureCastExpression(expression, typeFromHandle2, false);
            return (Func<T, object>)Expression.Lambda(typeof(Func<T, object>), expression, new ParameterExpression[] { parameterExpression }).Compile();
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Reflection.MemberInfo.DeclaringType, Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.EnsureCastExpression(), System.Reflection.PropertyInfo.GetGetMethod(), and System.Reflection.MethodBase.IsStatic.