Terraria Decompiled: Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateDefaultConstructor< T >
CreateDefaultConstructor< T >()
override Func< T > Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateDefaultConstructor< T > (Type type) inline
Definition at line 134 of file ExpressionReflectionDelegateFactory.cs.
        {
            ValidationUtils.ArgumentNotNull(type, "type");
            if (type.IsAbstract())
            {
                return () => (T)((object)Activator.CreateInstance(type));
            }
            Func<T> func;
            try
            {
                Type typeFromHandle = typeof(T);
                Expression expression = Expression.New(type);
                expression = this.EnsureCastExpression(expression, typeFromHandle, false);
                func = (Func<T>)Expression.Lambda(typeof(Func<T>), expression, new ParameterExpression[0]).Compile();
            }
            catch
            {
                func = () => (T)((object)Activator.CreateInstance(type));
            }
            return func;
        }
References Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), System.Activator.CreateInstance(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.EnsureCastExpression(), System.Type.IsAbstract, and System.T.