Terraria Decompiled: Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.BuildMethodCall
BuildMethodCall()
Expression Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.BuildMethodCall (MethodBase method, Type type, ParameterExpression targetParameterExpression, ParameterExpression argsParameterExpression) inline private
Definition at line 45 of file ExpressionReflectionDelegateFactory.cs.
        {
            ParameterInfo[] parameters = method.GetParameters();
            Expression[] array;
            IList<ExpressionReflectionDelegateFactory.ByRefParameter> list;
            if (parameters.Length == 0)
            {
                array = CollectionUtils.ArrayEmpty<Expression>();
                list = CollectionUtils.ArrayEmpty<ExpressionReflectionDelegateFactory.ByRefParameter>();
            }
            else
            {
                array = new Expression[parameters.Length];
                list = new List<ExpressionReflectionDelegateFactory.ByRefParameter>();
                for (int i = 0; i < parameters.Length; i++)
                {
                    ParameterInfo parameterInfo = parameters[i];
                    Type type2 = parameterInfo.ParameterType;
                    bool flag = false;
                    if (type2.IsByRef)
                    {
                        type2 = type2.GetElementType();
                        flag = true;
                    }
                    Expression expression = Expression.Constant(i);
                    Expression expression2 = Expression.ArrayIndex(argsParameterExpression, expression);
                    Expression expression3 = this.EnsureCastExpression(expression2, type2, !flag);
                    if (flag)
                    {
                        ParameterExpression parameterExpression = Expression.Variable(type2);
                        list.Add(new ExpressionReflectionDelegateFactory.ByRefParameter
{
                            Value = expression3,
                            Variable = parameterExpression,
                            IsOut = parameterInfo.IsOut
                        });
                        expression3 = parameterExpression;
                    }
                    array[i] = expression3;
                }
            }
            Expression expression4;
            if (method.IsConstructor)
            {
                expression4 = Expression.New((ConstructorInfo)method, array);
            }
            else if (method.IsStatic)
            {
                expression4 = Expression.Call((MethodInfo)method, array);
            }
            else
            {
                expression4 = Expression.Call(this.EnsureCastExpression(targetParameterExpression, method.DeclaringType, false), (MethodInfo)method, array);
            }
            MethodInfo methodInfo = method as MethodInfo;
            if (methodInfo != null)
            {
                if (methodInfo.ReturnType != typeof(void))
                {
                    expression4 = this.EnsureCastExpression(expression4, type, false);
                }
                else
                {
                    expression4 = Expression.Block(expression4, Expression.Constant(null));
                }
            }
            else
            {
                expression4 = this.EnsureCastExpression(expression4, type, false);
            }
            if (list.Count > 0)
            {
                IList<ParameterExpression> list2 = new List<ParameterExpression>();
                IList<Expression> list3 = new List<Expression>();
                foreach (ExpressionReflectionDelegateFactory.ByRefParameter byRefParameter in list)
                {
                    if (!byRefParameter.IsOut)
                    {
                        list3.Add(Expression.Assign(byRefParameter.Variable, byRefParameter.Value));
                    }
                    list2.Add(byRefParameter.Variable);
                }
                list3.Add(expression4);
                expression4 = Expression.Block(list2, list3);
            }
            return expression4;
        }
References System.Collections.Generic.ICollection< T >.Add(), System.array, System.Reflection.MemberInfo.DeclaringType, Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.EnsureCastExpression(), System.Type.GetElementType(), System.Reflection.MethodBase.GetParameters(), System.Type.IsByRef, System.Reflection.MethodBase.IsConstructor, System.Reflection.MethodBase.IsStatic, System.list, System.Reflection.ParameterInfo.ParameterType, and System.Reflection.MethodInfo.ReturnType.
Referenced by Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateMethodCall< T >(), and Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateParameterizedConstructor().