Terraria Decompiled: Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.EnsureCastExpression
EnsureCastExpression()
Expression Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.EnsureCastExpression (Expression expression, Type targetType, bool allowWidening = false) inline private
Definition at line 245 of file ExpressionReflectionDelegateFactory.cs.
        {
            Type type = expression.Type;
            if (type == targetType || (!type.IsValueType() && targetType.IsAssignableFrom(type)))
            {
                return expression;
            }
            if (targetType.IsValueType())
            {
                Expression expression2 = Expression.Unbox(expression, targetType);
                if (allowWidening && targetType.IsPrimitive())
                {
                    MethodInfo method = typeof(Convert).GetMethod("To" + targetType.Name, new Type[] { typeof(object) });
                    if (method != null)
                    {
                        expression2 = Expression.Condition(Expression.TypeIs(expression, targetType), expression2, Expression.Call(method, expression));
                    }
                }
                return Expression.Condition(Expression.Equal(expression, Expression.Constant(null, typeof(object))), Expression.Default(targetType), expression2);
            }
            return Expression.Convert(expression, targetType);
        }
References System.Type.IsAssignableFrom(), System.Type.IsPrimitive, System.Type.IsValueType, and System.Reflection.MemberInfo.Name.
Referenced by Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.BuildMethodCall(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateDefaultConstructor< T >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateGet< T >(), Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateSet< T >(), and Newtonsoft.Json.Utilities.ExpressionReflectionDelegateFactory.CreateSet< T >().