Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.InsertItem
InsertItem()
virtual void Newtonsoft.Json.Linq.JContainer.InsertItem (int index, JToken item, bool skipParentCheck) inline package virtual
Reimplemented in Newtonsoft.Json.Linq.JObject, and Newtonsoft.Json.Linq.JProperty.
Definition at line 288 of file JContainer.cs.
        {
            IList<JToken> childrenTokens = this.ChildrenTokens;
            if (index > childrenTokens.Count)
            {
                throw new ArgumentOutOfRangeException("index", "Index must be within the bounds of the List.");
            }
            this.CheckReentrancy();
            item = this.EnsureParentToken(item, skipParentCheck);
            JToken jtoken = ((index == 0) ? null : childrenTokens[index - 1]);
            JToken jtoken2 = ((index == childrenTokens.Count) ? null : childrenTokens[index]);
            this.ValidateToken(item, null);
            item.Parent = this;
            item.Previous = jtoken;
            if (jtoken != null)
            {
                jtoken.Next = item;
            }
            item.Next = jtoken2;
            if (jtoken2 != null)
            {
                jtoken2.Previous = item;
            }
            childrenTokens.Insert(index, item);
            if (this._listChanged != null)
            {
                this.OnListChanged(new ListChangedEventArgs(1, index));
            }
            if (this._collectionChanged != null)
            {
                this.OnCollectionChanged(new NotifyCollectionChangedEventArgs(0, item, index));
            }
        }
References Newtonsoft.Json.Linq.JContainer._collectionChanged, Newtonsoft.Json.Linq.JContainer._listChanged, Newtonsoft.Json.Linq.JContainer.CheckReentrancy(), Newtonsoft.Json.Linq.JContainer.ChildrenTokens, System.Collections.Generic.ICollection< T >.Count, Newtonsoft.Json.Linq.JContainer.EnsureParentToken(), System.index, System.Collections.Generic.IList< T >.Insert(), System.item, Newtonsoft.Json.Linq.JContainer.OnCollectionChanged(), Newtonsoft.Json.Linq.JContainer.OnListChanged(), and Newtonsoft.Json.Linq.JContainer.ValidateToken().
Referenced by Newtonsoft.Json.Linq.JContainer.AddInternal(), Newtonsoft.Json.Linq.JArray.Insert(), Newtonsoft.Json.Linq.JContainer.Insert(), and Newtonsoft.Json.Linq.JContainer.Insert().