Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.MergeEnumerableContent
MergeEnumerableContent()
static void Newtonsoft.Json.Linq.JContainer.MergeEnumerableContent (JContainer target, IEnumerable content, JsonMergeSettings settings) inline static package
Definition at line 1110 of file JContainer.cs.
        {
            switch (settings.MergeArrayHandling)
            {
            case MergeArrayHandling.Concat:
            {
                using (IEnumerator enumerator = content.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        object obj = enumerator.Current;
                        JToken jtoken = (JToken)obj;
                        target.Add(jtoken);
                    }
                    return;
                }
                break;
            }
            case MergeArrayHandling.Union:
                break;
            case MergeArrayHandling.Replace:
                goto IL_00B6;
            case MergeArrayHandling.Merge:
                goto IL_00FB;
            default:
                goto IL_018C;
            }
            HashSet<JToken> hashSet = new HashSet<JToken>(target, JToken.EqualityComparer);
            using (IEnumerator enumerator = content.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    object obj2 = enumerator.Current;
                    JToken jtoken2 = (JToken)obj2;
                    if (hashSet.Add(jtoken2))
                    {
                        target.Add(jtoken2);
                    }
                }
                return;
            }
            IL_00B6:
            target.ClearItems();
            using (IEnumerator enumerator = content.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    object obj3 = enumerator.Current;
                    JToken jtoken3 = (JToken)obj3;
                    target.Add(jtoken3);
                }
                return;
            }
            IL_00FB:
            int num = 0;
            using (IEnumerator enumerator = content.GetEnumerator())
            {
                while (enumerator.MoveNext())
                {
                    object obj4 = enumerator.Current;
                    if (num < target.Count)
                    {
                        JContainer jcontainer = target[num] as JContainer;
                        if (jcontainer != null)
{
                            jcontainer.Merge(obj4, settings);
                        }
                        else if (obj4 != null)
{
                            JToken jtoken4 = JContainer.CreateFromContent(obj4);
                            if (jtoken4.Type != JTokenType.Null)
{
                                target[num] = jtoken4;
                            }
                        }
                    }
                    else
                    {
                        target.Add(obj4);
                    }
                    num++;
                }
                return;
            }
            IL_018C:
            throw new ArgumentOutOfRangeException("settings", "Unexpected merge array handling when merging JSON.");
        }
References Newtonsoft.Json.Linq.JContainer.Add(), Newtonsoft.Json.Linq.JContainer.ClearItems(), Newtonsoft.Json.Linq.JContainer.Count, Newtonsoft.Json.Linq.JContainer.CreateFromContent(), System.Collections.Generic.IEnumerator< out T >.Current, Newtonsoft.Json.Linq.JToken.EqualityComparer, System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), Newtonsoft.Json.Linq.JContainer.JContainer(), Newtonsoft.Json.Linq.JToken.JToken, Newtonsoft.Json.Linq.JContainer.Merge(), Newtonsoft.Json.Linq.JsonMergeSettings.MergeArrayHandling, System.Collections.IEnumerator.MoveNext(), System.obj, and Newtonsoft.Json.Linq.JToken.Type.
Referenced by Newtonsoft.Json.Linq.JArray.MergeItem(), and Newtonsoft.Json.Linq.JConstructor.MergeItem().