Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.AddInternal
AddInternal()
void Newtonsoft.Json.Linq.JContainer.AddInternal (int index, object content, bool skipParentCheck) inline package
Definition at line 527 of file JContainer.cs.
        {
            if (this.IsMultiContent(content))
            {
                IEnumerable enumerable = (IEnumerable)content;
                int num = index;
                using (IEnumerator enumerator = enumerable.GetEnumerator())
                {
                    while (enumerator.MoveNext())
                    {
                        object obj = enumerator.Current;
                        this.AddInternal(num, obj, skipParentCheck);
                        num++;
                    }
                    return;
                }
            }
            JToken jtoken = JContainer.CreateFromContent(content);
            this.InsertItem(index, jtoken, skipParentCheck);
        }
References Newtonsoft.Json.Linq.JContainer.AddInternal(), Newtonsoft.Json.Linq.JContainer.CreateFromContent(), System.Collections.Generic.IEnumerator< out T >.Current, System.Collections.Generic.IEnumerable< out T >.GetEnumerator(), Newtonsoft.Json.Linq.JContainer.IEnumerable, System.index, Newtonsoft.Json.Linq.JContainer.InsertItem(), Newtonsoft.Json.Linq.JContainer.IsMultiContent(), System.Collections.IEnumerator.MoveNext(), and System.obj.
Referenced by Newtonsoft.Json.Linq.JContainer.Add(), Newtonsoft.Json.Linq.JToken.AddAfterSelf(), Newtonsoft.Json.Linq.JContainer.AddAndSkipParentCheck(), Newtonsoft.Json.Linq.JToken.AddBeforeSelf(), Newtonsoft.Json.Linq.JContainer.AddFirst(), Newtonsoft.Json.Linq.JContainer.AddInternal(), and Newtonsoft.Json.Linq.JContainer.JContainer().