Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.ClearItems
ClearItems()
virtual void Newtonsoft.Json.Linq.JContainer.ClearItems () inline package virtual
Reimplemented in Newtonsoft.Json.Linq.JProperty.
Definition at line 426 of file JContainer.cs.
        {
            this.CheckReentrancy();
            IList<JToken> childrenTokens = this.ChildrenTokens;
            foreach (JToken jtoken in childrenTokens)
            {
                jtoken.Parent = null;
                jtoken.Previous = null;
                jtoken.Next = null;
            }
            childrenTokens.Clear();
            if (this._listChanged != null)
            {
                this.OnListChanged(new ListChangedEventArgs(0, -1));
            }
            if (this._collectionChanged != null)
            {
                this.OnCollectionChanged(new NotifyCollectionChangedEventArgs(4));
            }
        }
References Newtonsoft.Json.Linq.JContainer._collectionChanged, Newtonsoft.Json.Linq.JContainer._listChanged, Newtonsoft.Json.Linq.JContainer.CheckReentrancy(), Newtonsoft.Json.Linq.JContainer.ChildrenTokens, Newtonsoft.Json.Linq.JContainer.OnCollectionChanged(), and Newtonsoft.Json.Linq.JContainer.OnListChanged().
Referenced by Newtonsoft.Json.Linq.JArray.Clear(), Newtonsoft.Json.Linq.JContainer.Clear(), Newtonsoft.Json.Linq.JContainer.MergeEnumerableContent(), Newtonsoft.Json.Linq.JContainer.RemoveAll(), and Newtonsoft.Json.Linq.JContainer.ReplaceAll().