Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.CopyItemsTo
CopyItemsTo()
virtual void Newtonsoft.Json.Linq.JContainer.CopyItemsTo (Array array, int arrayIndex) inline package virtual
Definition at line 465 of file JContainer.cs.
        {
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (arrayIndex < 0)
            {
                throw new ArgumentOutOfRangeException("arrayIndex", "arrayIndex is less than 0.");
            }
            if (arrayIndex >= array.Length && arrayIndex != 0)
            {
                throw new ArgumentException("arrayIndex is equal to or greater than the length of array.");
            }
            if (this.Count > array.Length - arrayIndex)
            {
                throw new ArgumentException("The number of elements in the source JObject is greater than the available space from arrayIndex to the end of the destination array.");
            }
            int num = 0;
            foreach (JToken jtoken in this.ChildrenTokens)
            {
                array.SetValue(jtoken, arrayIndex + num);
                num++;
            }
        }
References System.array, System.arrayIndex, Newtonsoft.Json.Linq.JContainer.ChildrenTokens, Newtonsoft.Json.Linq.JContainer.Count, and System.Array.Length.
Referenced by Newtonsoft.Json.Linq.JContainer.CopyTo(), Newtonsoft.Json.Linq.JArray.CopyTo(), and Newtonsoft.Json.Linq.JContainer.CopyTo().