Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.EnsureValue
EnsureValue()
JToken Newtonsoft.Json.Linq.JContainer.EnsureValue (object value) inline private
Definition at line 841 of file JContainer.cs.
        {
            if (value == null)
            {
                return null;
            }
            JToken jtoken = value as JToken;
            if (jtoken != null)
            {
                return jtoken;
            }
            throw new ArgumentException("Argument is not a JToken.");
        }
References Newtonsoft.Json.Linq.JToken.JToken, and System.value.
Referenced by Newtonsoft.Json.Linq.JContainer.Add(), Newtonsoft.Json.Linq.JContainer.Contains(), Newtonsoft.Json.Linq.JContainer.IndexOf(), Newtonsoft.Json.Linq.JContainer.Insert(), and Newtonsoft.Json.Linq.JContainer.Remove().