Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.RemoveItemAt
RemoveItemAt()
virtual void Newtonsoft.Json.Linq.JContainer.RemoveItemAt (int index) inline package virtual
Reimplemented in Newtonsoft.Json.Linq.JProperty.
Definition at line 323 of file JContainer.cs.
        {
            IList<JToken> childrenTokens = this.ChildrenTokens;
            if (index < 0)
            {
                throw new ArgumentOutOfRangeException("index", "Index is less than 0.");
            }
            if (index >= childrenTokens.Count)
            {
                throw new ArgumentOutOfRangeException("index", "Index is equal to or greater than Count.");
            }
            this.CheckReentrancy();
            JToken jtoken = childrenTokens[index];
            JToken jtoken2 = ((index == 0) ? null : childrenTokens[index - 1]);
            JToken jtoken3 = ((index == childrenTokens.Count - 1) ? null : childrenTokens[index + 1]);
            if (jtoken2 != null)
            {
                jtoken2.Next = jtoken3;
            }
            if (jtoken3 != null)
            {
                jtoken3.Previous = jtoken2;
            }
            jtoken.Parent = null;
            jtoken.Previous = null;
            jtoken.Next = null;
            childrenTokens.RemoveAt(index);
            if (this._listChanged != null)
            {
                this.OnListChanged(new ListChangedEventArgs(2, index));
            }
            if (this._collectionChanged != null)
            {
                this.OnCollectionChanged(new NotifyCollectionChangedEventArgs(1, jtoken, index));
            }
        }
References Newtonsoft.Json.Linq.JContainer._collectionChanged, Newtonsoft.Json.Linq.JContainer._listChanged, Newtonsoft.Json.Linq.JContainer.CheckReentrancy(), Newtonsoft.Json.Linq.JContainer.ChildrenTokens, System.Collections.Generic.ICollection< T >.Count, System.index, Newtonsoft.Json.Linq.JContainer.OnCollectionChanged(), Newtonsoft.Json.Linq.JContainer.OnListChanged(), and System.Collections.Generic.IList< T >.RemoveAt().
Referenced by Newtonsoft.Json.Linq.JArray.RemoveAt(), Newtonsoft.Json.Linq.JContainer.RemoveAt(), and Newtonsoft.Json.Linq.JContainer.RemoveItem().