Terraria Decompiled: Newtonsoft.Json.Linq.JContainer.ReadContentFrom
ReadContentFrom()
void Newtonsoft.Json.Linq.JContainer.ReadContentFrom (JsonReader r, JsonLoadSettings settings) inline package
Definition at line 609 of file JContainer.cs.
        {
            ValidationUtils.ArgumentNotNull(r, "r");
            IJsonLineInfo jsonLineInfo = r as IJsonLineInfo;
            JContainer jcontainer = this;
            for (;;)
            {
                JProperty jproperty = jcontainer as JProperty;
                if (((jproperty != null) ? jproperty.Value : null) != null)
                {
                    if (jcontainer == this)
                    {
                        break;
                    }
                    jcontainer = jcontainer.Parent;
                }
                switch (r.TokenType)
                {
                case JsonToken.None:
                    goto IL_0226;
                case JsonToken.StartObject:
                {
                    JObject jobject = new JObject();
                    jobject.SetLineInfo(jsonLineInfo, settings);
                    jcontainer.Add(jobject);
                    jcontainer = jobject;
                    goto IL_0226;
                }
                case JsonToken.StartArray:
                {
                    JArray jarray = new JArray();
                    jarray.SetLineInfo(jsonLineInfo, settings);
                    jcontainer.Add(jarray);
                    jcontainer = jarray;
                    goto IL_0226;
                }
                case JsonToken.StartConstructor:
                {
                    JConstructor jconstructor = new JConstructor(r.Value.ToString());
                    jconstructor.SetLineInfo(jsonLineInfo, settings);
                    jcontainer.Add(jconstructor);
                    jcontainer = jconstructor;
                    goto IL_0226;
                }
                case JsonToken.PropertyName:
                {
                    string text = r.Value.ToString();
                    JProperty jproperty2 = new JProperty(text);
                    jproperty2.SetLineInfo(jsonLineInfo, settings);
                    JProperty jproperty3 = ((JObject)jcontainer).Property(text);
                    if (jproperty3 == null)
                    {
                        jcontainer.Add(jproperty2);
                    }
                    else
                    {
                        jproperty3.Replace(jproperty2);
                    }
                    jcontainer = jproperty2;
                    goto IL_0226;
                }
                case JsonToken.Comment:
                    if (settings != null && settings.CommentHandling == CommentHandling.Load)
                    {
                        JValue jvalue = JValue.CreateComment(r.Value.ToString());
                        jvalue.SetLineInfo(jsonLineInfo, settings);
                        jcontainer.Add(jvalue);
                        goto IL_0226;
                    }
                    goto IL_0226;
                case JsonToken.Integer:
                case JsonToken.Float:
                case JsonToken.String:
                case JsonToken.Boolean:
                case JsonToken.Date:
                case JsonToken.Bytes:
                {
                    JValue jvalue = new JValue(r.Value);
                    jvalue.SetLineInfo(jsonLineInfo, settings);
                    jcontainer.Add(jvalue);
                    goto IL_0226;
                }
                case JsonToken.Null:
                {
                    JValue jvalue = JValue.CreateNull();
                    jvalue.SetLineInfo(jsonLineInfo, settings);
                    jcontainer.Add(jvalue);
                    goto IL_0226;
                }
                case JsonToken.Undefined:
                {
                    JValue jvalue = JValue.CreateUndefined();
                    jvalue.SetLineInfo(jsonLineInfo, settings);
                    jcontainer.Add(jvalue);
                    goto IL_0226;
                }
                case JsonToken.EndObject:
                    if (jcontainer == this)
                    {
                        return;
                    }
                    jcontainer = jcontainer.Parent;
                    goto IL_0226;
                case JsonToken.EndArray:
                    if (jcontainer == this)
                    {
                        return;
                    }
                    jcontainer = jcontainer.Parent;
                    goto IL_0226;
                case JsonToken.EndConstructor:
                    if (jcontainer == this)
                    {
                        return;
                    }
                    jcontainer = jcontainer.Parent;
                    goto IL_0226;
                }
                goto Block_4;
                IL_0226:
                if (!r.Read())
                {
                    return;
                }
            }
            return;
            Block_4:
            throw new InvalidOperationException("The JsonReader should not be on a token of type {0}.".FormatWith(CultureInfo.InvariantCulture, r.TokenType));
        }
References Newtonsoft.Json.Linq.JContainer.Add(), Newtonsoft.Json.Utilities.ValidationUtils.ArgumentNotNull(), Newtonsoft.Json.Linq.JsonLoadSettings.CommentHandling, Newtonsoft.Json.Linq.JValue.CreateComment(), Newtonsoft.Json.Linq.JValue.CreateNull(), Newtonsoft.Json.Linq.JValue.CreateUndefined(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JToken.Parent, Newtonsoft.Json.JsonReader.Read(), Newtonsoft.Json.Linq.JToken.Replace(), Newtonsoft.Json.Linq.JToken.SetLineInfo(), System.text, Newtonsoft.Json.JsonReader.TokenType, Newtonsoft.Json.JsonReader.Value, and Newtonsoft.Json.Linq.JProperty.Value.
Referenced by Newtonsoft.Json.Linq.JContainer.ReadTokenFrom().