Terraria Decompiled: Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.BiomeChests_DualDungeons
BiomeChests_DualDungeons()
void Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.BiomeChests_DualDungeons (DungeonData data) inline private
Definition at line 35 of file DungeonGlobalBiomeChests.cs.
        {
            UnifiedRandom genRand = WorldGen.genRand;
            List<int> list = new List<int>();
            list.Add(8);
            list.Add(WorldGen.crimson ? 5 : 4);
            list.Add(6);
            list.Add(2);
            list.Add(3);
            if (WorldGen.drunkWorldGen)
            {
                list.Add(WorldGen.crimson ? 4 : 5);
            }
            List<DungeonRoom>[] array = new List<DungeonRoom>[16];
            DungeonRoom[] array2 = new DungeonRoom[16];
            for (int i = 0; i < data.dungeonRooms.Count; i++)
            {
                DungeonRoom dungeonRoom = data.dungeonRooms[i];
                if (dungeonRoom is BiomeDungeonRoom)
                {
                    array2[(int)dungeonRoom.settings.StyleData.Style] = dungeonRoom;
                }
                else
                {
                    if (array[(int)dungeonRoom.settings.StyleData.Style] == null)
                    {
                        array[(int)dungeonRoom.settings.StyleData.Style] = new List<DungeonRoom>();
                    }
                    array[(int)dungeonRoom.settings.StyleData.Style].Add(dungeonRoom);
                }
            }
            for (int j = 0; j < list.Count; j++)
            {
                int num = list[j];
                bool flag = false;
                DungeonRoom dungeonRoom2 = array2[num];
                if (dungeonRoom2 != null)
                {
                    int k = 50;
                    while (k > 0)
                    {
                        k--;
                        if (dungeonRoom2.DualDungeons_TryGenerateBiomeChestInRoom(data, this))
{
                            flag = true;
                            break;
                        }
                    }
                }
                if (!flag)
                {
                    List<DungeonRoom> list2 = array[num];
                    if (list2 != null)
                    {
                        int num2 = 30 * list2.Count;
                        while (num2 > 0 && list2.Count > 0)
{
                            num2--;
                            DungeonRoom dungeonRoom3 = list2[genRand.Next(list2.Count)];
                            if (dungeonRoom3.DualDungeons_TryGenerateBiomeChestInRoom(data, this))
{
                                flag = true;
                            }
                            list2.Remove(dungeonRoom3);
                            if (flag)
{
                                break;
                            }
                        }
                    }
                }
            }
        }
References System.array, System.Collections.Generic.List< T >.Count, Terraria.WorldGen.crimson, Terraria.WorldGen.drunkWorldGen, Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.DualDungeons_TryGenerateBiomeChestInRoom(), Terraria.GameContent.Generation.Dungeon.DungeonData.dungeonRooms, Terraria.WorldGen.genRand, int, System.list, Terraria.Utilities.UnifiedRandom.Next(), System.Collections.Generic.List< T >.Remove(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.settings, Terraria.GameContent.Generation.Dungeon.DungeonGenerationStyleData.Style, and Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoomSettings.StyleData.
Referenced by Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBiomeChests.GenerateFeature().