Terraria Decompiled: Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize
Deserialize()
override bool Terraria.GameContent.BannerSystem.NetBannersModule.Deserialize (BinaryReader reader, int userId) inline
Definition at line 1681 of file BannerSystem.cs.
            {
                switch (reader.ReadByte())
                {
                case 0:
                    if (Main.netMode == 2)
                    {
                        return false;
                    }
                    BannerSystem.Load(reader, 319);
                    break;
                case 1:
                    if (Main.netMode == 2)
                    {
                        return false;
                    }
                    BannerSystem.killCount[(int)reader.ReadInt16()] = reader.ReadInt32();
                    break;
                case 2:
                    if (Main.netMode == 2)
                    {
                        return false;
                    }
                    BannerSystem.claimableBanners[(int)reader.ReadInt16()] = reader.ReadUInt16();
                    break;
                case 3:
                    BannerSystem.HandleBannerClaimRequest((int)reader.ReadInt16(), reader.ReadUInt16(), userId);
                    break;
                case 4:
                    if (Main.netMode == 2)
                    {
                        return false;
                    }
                    BannerSystem.HandleBannerClaimResponse((int)reader.ReadInt16(), reader.ReadUInt16(), reader.ReadBoolean());
                    break;
                }
                return true;
            }
References Terraria.GameContent.BannerSystem.claimableBanners, Terraria.GameContent.BannerSystem.HandleBannerClaimRequest(), Terraria.GameContent.BannerSystem.HandleBannerClaimResponse(), int, Terraria.GameContent.BannerSystem.killCount, Terraria.GameContent.BannerSystem.Load(), Terraria.Main.netMode, System.IO.BinaryReader.ReadBoolean(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadInt16(), System.IO.BinaryReader.ReadInt32(), and System.IO.BinaryReader.ReadUInt16().