Terraria Decompiled: Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt1Block
DecompressDxt1Block()
static void Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt1Block (BinaryReader imageReader, int x, int y, int blockCountX, int width, int height, byte[] imageData) inline static private
Definition at line 100 of file DxtUtil.cs.
        {
            ushort num = imageReader.ReadUInt16();
            ushort num2 = imageReader.ReadUInt16();
            byte b;
            byte b2;
            byte b3;
            DxtUtil.ConvertRgb565ToRgb888(num, out b, out b2, out b3);
            byte b4;
            byte b5;
            byte b6;
            DxtUtil.ConvertRgb565ToRgb888(num2, out b4, out b5, out b6);
            uint num3 = imageReader.ReadUInt32();
            for (int i = 0; i < 4; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    byte b7 = 0;
                    byte b8 = 0;
                    byte b9 = 0;
                    byte b10 = byte.MaxValue;
                    uint num4 = (num3 >> 2 * (4 * i + j)) & 3U;
                    if (num > num2)
                    {
                        switch (num4)
{
                        case 0U:
                            b7 = b;
                            b8 = b2;
                            b9 = b3;
                            break;
                        case 1U:
                            b7 = b4;
                            b8 = b5;
                            b9 = b6;
                            break;
                        case 2U:
                            b7 = (2 * b + b4) / 3;
                            b8 = (2 * b2 + b5) / 3;
                            b9 = (2 * b3 + b6) / 3;
                            break;
                        case 3U:
                            b7 = (b + 2 * b4) / 3;
                            b8 = (b2 + 2 * b5) / 3;
                            b9 = (b3 + 2 * b6) / 3;
                            break;
                        }
                    }
                    else
                    {
                        switch (num4)
{
                        case 0U:
                            b7 = b;
                            b8 = b2;
                            b9 = b3;
                            break;
                        case 1U:
                            b7 = b4;
                            b8 = b5;
                            b9 = b6;
                            break;
                        case 2U:
                            b7 = (b + b4) / 2;
                            b8 = (b2 + b5) / 2;
                            b9 = (b3 + b6) / 2;
                            break;
                        case 3U:
                            b7 = 0;
                            b8 = 0;
                            b9 = 0;
                            b10 = 0;
                            break;
                        }
                    }
                    int num5 = (x << 2) + j;
                    int num6 = (y << 2) + i;
                    if (num5 < width && num6 < height)
                    {
                        int num7 = num6 * width + num5 << 2;
                        imageData[num7] = b7;
                        imageData[num7 + 1] = b8;
                        imageData[num7 + 2] = b9;
                        imageData[num7 + 3] = b10;
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.DxtUtil.ConvertRgb565ToRgb888(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), and System.U.
Referenced by Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt1().