Terraria Decompiled: Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt5Block
DecompressDxt5Block()
static void Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt5Block (BinaryReader imageReader, int x, int y, int blockCountX, int width, int height, byte[] imageData) inline static private
Definition at line 311 of file DxtUtil.cs.
        {
            byte b = imageReader.ReadByte();
            byte b2 = imageReader.ReadByte();
            ulong num = (ulong)imageReader.ReadByte();
            num += (ulong)imageReader.ReadByte() << 8;
            num += (ulong)imageReader.ReadByte() << 16;
            num += (ulong)imageReader.ReadByte() << 24;
            num += (ulong)imageReader.ReadByte() << 32;
            num += (ulong)imageReader.ReadByte() << 40;
            ushort num2 = imageReader.ReadUInt16();
            ushort num3 = imageReader.ReadUInt16();
            byte b3;
            byte b4;
            byte b5;
            DxtUtil.ConvertRgb565ToRgb888(num2, out b3, out b4, out b5);
            byte b6;
            byte b7;
            byte b8;
            DxtUtil.ConvertRgb565ToRgb888(num3, out b6, out b7, out b8);
            uint num4 = imageReader.ReadUInt32();
            for (int i = 0; i < 4; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    byte b9 = 0;
                    byte b10 = 0;
                    byte b11 = 0;
                    uint num5 = (num4 >> 2 * (4 * i + j)) & 3U;
                    uint num6 = (uint)((num >> 3 * (4 * i + j)) & 7UL);
                    byte b12;
                    if (num6 == 0U)
                    {
                        b12 = b;
                    }
                    else if (num6 == 1U)
                    {
                        b12 = b2;
                    }
                    else if (b > b2)
                    {
                        b12 = (byte)(((8U - num6) * (uint)b + (num6 - 1U) * (uint)b2) / 7U);
                    }
                    else if (num6 == 6U)
                    {
                        b12 = 0;
                    }
                    else if (num6 == 7U)
                    {
                        b12 = byte.MaxValue;
                    }
                    else
                    {
                        b12 = (byte)(((6U - num6) * (uint)b + (num6 - 1U) * (uint)b2) / 5U);
                    }
                    switch (num5)
                    {
                    case 0U:
                        b9 = b3;
                        b10 = b4;
                        b11 = b5;
                        break;
                    case 1U:
                        b9 = b6;
                        b10 = b7;
                        b11 = b8;
                        break;
                    case 2U:
                        b9 = (2 * b3 + b6) / 3;
                        b10 = (2 * b4 + b7) / 3;
                        b11 = (2 * b5 + b8) / 3;
                        break;
                    case 3U:
                        b9 = (b3 + 2 * b6) / 3;
                        b10 = (b4 + 2 * b7) / 3;
                        b11 = (b5 + 2 * b8) / 3;
                        break;
                    }
                    int num7 = (x << 2) + j;
                    int num8 = (y << 2) + i;
                    if (num7 < width && num8 < height)
                    {
                        int num9 = num8 * width + num7 << 2;
                        imageData[num9] = b9;
                        imageData[num9 + 1] = b10;
                        imageData[num9 + 2] = b11;
                        imageData[num9 + 3] = b12;
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.DxtUtil.ConvertRgb565ToRgb888(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), and System.U.
Referenced by Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt5().