Terraria Decompiled: Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt3Block
DecompressDxt3Block()
static void Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt3Block (BinaryReader imageReader, int x, int y, int blockCountX, int width, int height, byte[] imageData) inline static private
Definition at line 190 of file DxtUtil.cs.
        {
            byte b = imageReader.ReadByte();
            byte b2 = imageReader.ReadByte();
            byte b3 = imageReader.ReadByte();
            byte b4 = imageReader.ReadByte();
            byte b5 = imageReader.ReadByte();
            byte b6 = imageReader.ReadByte();
            byte b7 = imageReader.ReadByte();
            byte b8 = imageReader.ReadByte();
            ushort num = imageReader.ReadUInt16();
            ushort num2 = imageReader.ReadUInt16();
            byte b9;
            byte b10;
            byte b11;
            DxtUtil.ConvertRgb565ToRgb888(num, out b9, out b10, out b11);
            byte b12;
            byte b13;
            byte b14;
            DxtUtil.ConvertRgb565ToRgb888(num2, out b12, out b13, out b14);
            uint num3 = imageReader.ReadUInt32();
            int num4 = 0;
            for (int i = 0; i < 4; i++)
            {
                for (int j = 0; j < 4; j++)
                {
                    byte b15 = 0;
                    byte b16 = 0;
                    byte b17 = 0;
                    byte b18 = 0;
                    uint num5 = (num3 >> 2 * (4 * i + j)) & 3U;
                    switch (num4)
                    {
                    case 0:
                        b18 = (byte)((int)(b & 15) | ((int)(b & 15) << 4));
                        break;
                    case 1:
                        b18 = (byte)((int)(b & 240) | ((b & 240) >> 4));
                        break;
                    case 2:
                        b18 = (byte)((int)(b2 & 15) | ((int)(b2 & 15) << 4));
                        break;
                    case 3:
                        b18 = (byte)((int)(b2 & 240) | ((b2 & 240) >> 4));
                        break;
                    case 4:
                        b18 = (byte)((int)(b3 & 15) | ((int)(b3 & 15) << 4));
                        break;
                    case 5:
                        b18 = (byte)((int)(b3 & 240) | ((b3 & 240) >> 4));
                        break;
                    case 6:
                        b18 = (byte)((int)(b4 & 15) | ((int)(b4 & 15) << 4));
                        break;
                    case 7:
                        b18 = (byte)((int)(b4 & 240) | ((b4 & 240) >> 4));
                        break;
                    case 8:
                        b18 = (byte)((int)(b5 & 15) | ((int)(b5 & 15) << 4));
                        break;
                    case 9:
                        b18 = (byte)((int)(b5 & 240) | ((b5 & 240) >> 4));
                        break;
                    case 10:
                        b18 = (byte)((int)(b6 & 15) | ((int)(b6 & 15) << 4));
                        break;
                    case 11:
                        b18 = (byte)((int)(b6 & 240) | ((b6 & 240) >> 4));
                        break;
                    case 12:
                        b18 = (byte)((int)(b7 & 15) | ((int)(b7 & 15) << 4));
                        break;
                    case 13:
                        b18 = (byte)((int)(b7 & 240) | ((b7 & 240) >> 4));
                        break;
                    case 14:
                        b18 = (byte)((int)(b8 & 15) | ((int)(b8 & 15) << 4));
                        break;
                    case 15:
                        b18 = (byte)((int)(b8 & 240) | ((b8 & 240) >> 4));
                        break;
                    }
                    num4++;
                    switch (num5)
                    {
                    case 0U:
                        b15 = b9;
                        b16 = b10;
                        b17 = b11;
                        break;
                    case 1U:
                        b15 = b12;
                        b16 = b13;
                        b17 = b14;
                        break;
                    case 2U:
                        b15 = (2 * b9 + b12) / 3;
                        b16 = (2 * b10 + b13) / 3;
                        b17 = (2 * b11 + b14) / 3;
                        break;
                    case 3U:
                        b15 = (b9 + 2 * b12) / 3;
                        b16 = (b10 + 2 * b13) / 3;
                        b17 = (b11 + 2 * b14) / 3;
                        break;
                    }
                    int num6 = (x << 2) + j;
                    int num7 = (y << 2) + i;
                    if (num6 < width && num7 < height)
                    {
                        int num8 = num7 * width + num6 << 2;
                        imageData[num8] = b15;
                        imageData[num8 + 1] = b16;
                        imageData[num8 + 2] = b17;
                        imageData[num8 + 3] = b18;
                    }
                }
            }
        }
References Microsoft.Xna.Framework.Graphics.DxtUtil.ConvertRgb565ToRgb888(), System.IO.BinaryReader.ReadByte(), System.IO.BinaryReader.ReadUInt16(), System.IO.BinaryReader.ReadUInt32(), and System.U.
Referenced by Microsoft.Xna.Framework.Graphics.DxtUtil.DecompressDxt3().