Terraria Decompiled: System.IO.StreamWriter.d__33.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamWriter.d__33.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 939 of file StreamWriter.cs.
            {
                int num2;
                int num = num2;
                StreamWriter streamWriter = this;
                try
                {
                    try
                    {
                        ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter;
                        if (num != 0)
{
                            if (streamWriter._stream == null)
{
                                goto IL_007D;
                            }
                            configuredTaskAwaiter = streamWriter.FlushAsync().ConfigureAwait(false).GetAwaiter();
                            if (!configuredTaskAwaiter.IsCompleted)
{
                                num = (num2 = 0);
                                ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2 = configuredTaskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredTaskAwaitable.ConfiguredTaskAwaiter, StreamWriter.<DisposeAsyncCore>d__33>(ref configuredTaskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            ConfiguredTaskAwaitable.ConfiguredTaskAwaiter configuredTaskAwaiter2;
                            configuredTaskAwaiter = configuredTaskAwaiter2;
                            configuredTaskAwaiter2 = default(ConfiguredTaskAwaitable.ConfiguredTaskAwaiter);
                            num = (num2 = -1);
                        }
                        configuredTaskAwaiter.GetResult();
                        IL_007D:;
                    }
                    finally
                    {
                        if (num < 0)
{
                            streamWriter.CloseStreamFromDispose(true);
                        }
                    }
                    GC.SuppressFinalize(streamWriter);
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                this.<>t__builder.SetResult();
            }
References System.IO.StreamWriter._stream, System.IO.StreamWriter.CloseStreamFromDispose(), System.Threading.Tasks.Task< TResult >.ConfigureAwait(), System.IO.StreamWriter.DisposeAsyncCore(), System.IO.StreamWriter.FlushAsync(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.GetAwaiter(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.GetResult(), System.Runtime.CompilerServices.ConfiguredTaskAwaitable< TResult >.ConfiguredTaskAwaiter.IsCompleted, and System.GC.SuppressFinalize().