Terraria Decompiled: Newtonsoft.Json.Serialization.TraceJsonReader.GetDeserializedJsonMessage
GetDeserializedJsonMessage()
string Newtonsoft.Json.Serialization.TraceJsonReader.GetDeserializedJsonMessage () inline
Definition at line 21 of file TraceJsonReader.cs.
        {
            return this._sw.ToString();
        }
References Newtonsoft.Json.Serialization.TraceJsonReader._sw, and System.IO.StringWriter.ToString().
Referenced by Newtonsoft.Json.JsonSerializer.DeserializeInternal(), and Newtonsoft.Json.JsonSerializer.PopulateInternal().