Terraria Decompiled: Mono.Security.Cryptography.DSAManaged.ImportParameters
ImportParameters()
override void Mono.Security.Cryptography.DSAManaged.ImportParameters (DSAParameters parameters) inline
Definition at line 259 of file DSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException(Locale.GetText("Keypair was disposed"));
            }
            if (parameters.P == null || parameters.Q == null || parameters.G == null)
            {
                throw new CryptographicException(Locale.GetText("Missing mandatory DSA parameters (P, Q or G)."));
            }
            if (parameters.X == null && parameters.Y == null)
            {
                throw new CryptographicException(Locale.GetText("Missing both public (Y) and private (X) keys."));
            }
            this.p = new BigInteger(parameters.P);
            this.q = new BigInteger(parameters.Q);
            this.g = new BigInteger(parameters.G);
            if (parameters.X != null)
            {
                this.x = new BigInteger(parameters.X);
            }
            else
            {
                this.x = null;
            }
            if (parameters.Y != null)
            {
                this.y = new BigInteger(parameters.Y);
            }
            else
            {
                this.y = this.g.ModPow(this.x, this.p);
            }
            if (parameters.J != null)
            {
                this.j = new BigInteger(parameters.J);
            }
            else
            {
                this.j = (this.p - 1) / this.q;
                this.j_missing = true;
            }
            if (parameters.Seed != null)
            {
                this.seed = new BigInteger(parameters.Seed);
                this.counter = parameters.Counter;
            }
            else
            {
                this.seed = 0;
            }
            this.keypairGenerated = true;
        }
References System.Security.Cryptography.DSAParameters.Counter, Mono.Security.Cryptography.DSAManaged.g, System.Security.Cryptography.DSAParameters.G, Locale.GetText(), System.Security.Cryptography.DSAParameters.J, Mono.Security.Cryptography.DSAManaged.m_disposed, Mono.Math.BigInteger.ModPow(), Mono.Security.Cryptography.DSAManaged.p, System.Security.Cryptography.DSAParameters.P, Mono.Security.Cryptography.DSAManaged.q, System.Security.Cryptography.DSAParameters.Q, System.Security.Cryptography.DSAParameters.Seed, Mono.Security.Cryptography.DSAManaged.x, System.Security.Cryptography.DSAParameters.X, and System.Security.Cryptography.DSAParameters.Y.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.ImportParameters().