Terraria Decompiled: Mono.Security.Cryptography.DSAManaged.ExportParameters
ExportParameters()
override DSAParameters Mono.Security.Cryptography.DSAManaged.ExportParameters (bool includePrivateParameters) inline
Definition at line 219 of file DSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException(Locale.GetText("Keypair was disposed"));
            }
            if (!this.keypairGenerated)
            {
                this.Generate();
            }
            if (includePrivateParameters && this.x == null)
            {
                throw new CryptographicException("no private key to export");
            }
            DSAParameters dsaparameters = default(DSAParameters);
            dsaparameters.P = this.NormalizeArray(this.p.GetBytes());
            dsaparameters.Q = this.NormalizeArray(this.q.GetBytes());
            dsaparameters.G = this.NormalizeArray(this.g.GetBytes());
            dsaparameters.Y = this.NormalizeArray(this.y.GetBytes());
            if (!this.j_missing)
            {
                dsaparameters.J = this.NormalizeArray(this.j.GetBytes());
            }
            if (this.seed != 0U)
            {
                dsaparameters.Seed = this.NormalizeArray(this.seed.GetBytes());
                dsaparameters.Counter = this.counter;
            }
            if (includePrivateParameters)
            {
                byte[] bytes = this.x.GetBytes();
                if (bytes.Length == 20)
                {
                    dsaparameters.X = this.NormalizeArray(bytes);
                }
            }
            return dsaparameters;
        }
References Mono.Security.Cryptography.DSAManaged.counter, Mono.Security.Cryptography.DSAManaged.g, Mono.Security.Cryptography.DSAManaged.Generate(), Mono.Math.BigInteger.GetBytes(), Locale.GetText(), Mono.Security.Cryptography.DSAManaged.j, Mono.Security.Cryptography.DSAManaged.j_missing, Mono.Security.Cryptography.DSAManaged.keypairGenerated, Mono.Security.Cryptography.DSAManaged.m_disposed, Mono.Security.Cryptography.DSAManaged.NormalizeArray(), Mono.Security.Cryptography.DSAManaged.p, Mono.Security.Cryptography.DSAManaged.q, Mono.Security.Cryptography.DSAManaged.seed, System.U, Mono.Security.Cryptography.DSAManaged.x, and Mono.Security.Cryptography.DSAManaged.y.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.ExportParameters(), and System.Security.Cryptography.DSACryptoServiceProvider.ImportCspBlob().