Terraria Decompiled: Mono.Security.Cryptography.DSAManaged.Generate
Generate()
void Mono.Security.Cryptography.DSAManaged.Generate () inline private
Definition at line 33 of file DSAManaged.cs.
        {
            this.GenerateParams(base.KeySize);
            this.GenerateKeyPair();
            this.keypairGenerated = true;
            if (this.KeyGenerated != null)
            {
                this.KeyGenerated(this, null);
            }
        }
References Mono.Security.Cryptography.DSAManaged.GenerateKeyPair(), Mono.Security.Cryptography.DSAManaged.GenerateParams(), and Mono.Security.Cryptography.DSAManaged.KeyGenerated.
Referenced by Mono.Security.Cryptography.DSAManaged.CreateSignature(), and Mono.Security.Cryptography.DSAManaged.ExportParameters().