Terraria Decompiled: Mono.Security.Cryptography.DSAManaged.VerifySignature
VerifySignature()
override bool Mono.Security.Cryptography.DSAManaged.VerifySignature (byte[] rgbHash, byte[] rgbSignature) inline
Definition at line 355 of file DSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException(Locale.GetText("Keypair was disposed"));
            }
            if (rgbHash == null)
            {
                throw new ArgumentNullException("rgbHash");
            }
            if (rgbSignature == null)
            {
                throw new ArgumentNullException("rgbSignature");
            }
            if (rgbHash.Length != 20)
            {
                throw new CryptographicException("invalid hash length");
            }
            if (rgbSignature.Length != 40)
            {
                throw new CryptographicException("invalid signature length");
            }
            if (!this.keypairGenerated)
            {
                return false;
            }
            bool flag;
            try
            {
                BigInteger bigInteger = new BigInteger(rgbHash);
                byte[] array = new byte[20];
                Array.Copy(rgbSignature, 0, array, 0, 20);
                BigInteger bigInteger2 = new BigInteger(array);
                Array.Copy(rgbSignature, 20, array, 0, 20);
                BigInteger bigInteger3 = new BigInteger(array);
                if (bigInteger2 < 0 || this.q <= bigInteger2)
                {
                    flag = false;
                }
                else if (bigInteger3 < 0 || this.q <= bigInteger3)
                {
                    flag = false;
                }
                else
                {
                    BigInteger bigInteger4 = bigInteger3.ModInverse(this.q);
                    BigInteger bigInteger5 = bigInteger * bigInteger4 % this.q;
                    BigInteger bigInteger6 = bigInteger2 * bigInteger4 % this.q;
                    bigInteger5 = this.g.ModPow(bigInteger5, this.p);
                    bigInteger6 = this.y.ModPow(bigInteger6, this.p);
                    flag = bigInteger5 * bigInteger6 % this.p % this.q == bigInteger2;
                }
            }
            catch
            {
                throw new CryptographicException("couldn't compute signature verification");
            }
            return flag;
        }
References System.array, System.Array.Copy(), Mono.Security.Cryptography.DSAManaged.g, Locale.GetText(), Mono.Security.Cryptography.DSAManaged.keypairGenerated, Mono.Security.Cryptography.DSAManaged.m_disposed, Mono.Math.BigInteger.ModInverse(), Mono.Math.BigInteger.ModPow(), Mono.Security.Cryptography.DSAManaged.p, Mono.Security.Cryptography.DSAManaged.q, and Mono.Security.Cryptography.DSAManaged.y.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.VerifyData(), System.Security.Cryptography.DSACryptoServiceProvider.VerifyHash(), and System.Security.Cryptography.DSACryptoServiceProvider.VerifySignature().