Terraria Decompiled: Mono.Security.Cryptography.DSAManaged.CreateSignature
CreateSignature()
override byte[] Mono.Security.Cryptography.DSAManaged.CreateSignature (byte[] rgbHash) inline
Definition at line 314 of file DSAManaged.cs.
        {
            if (this.m_disposed)
            {
                throw new ObjectDisposedException(Locale.GetText("Keypair was disposed"));
            }
            if (rgbHash == null)
            {
                throw new ArgumentNullException("rgbHash");
            }
            if (rgbHash.Length != 20)
            {
                throw new CryptographicException("invalid hash length");
            }
            if (!this.keypairGenerated)
            {
                this.Generate();
            }
            if (this.x == null)
            {
                throw new CryptographicException("no private key available for signature");
            }
            BigInteger bigInteger = new BigInteger(rgbHash);
            BigInteger bigInteger2 = BigInteger.GenerateRandom(160);
            while (bigInteger2 >= this.q)
            {
                bigInteger2.Randomize();
            }
            BigInteger bigInteger3 = this.g.ModPow(bigInteger2, this.p) % this.q;
            BigInteger bigInteger4 = bigInteger2.ModInverse(this.q) * (bigInteger + this.x * bigInteger3) % this.q;
            byte[] array = new byte[40];
            byte[] bytes = bigInteger3.GetBytes();
            byte[] bytes2 = bigInteger4.GetBytes();
            int num = 20 - bytes.Length;
            Array.Copy(bytes, 0, array, num, bytes.Length);
            num = 40 - bytes2.Length;
            Array.Copy(bytes2, 0, array, num, bytes2.Length);
            return array;
        }
References System.array, System.Array.Copy(), Mono.Security.Cryptography.DSAManaged.g, Mono.Security.Cryptography.DSAManaged.Generate(), Mono.Math.BigInteger.GenerateRandom(), Mono.Math.BigInteger.GetBytes(), Locale.GetText(), Mono.Security.Cryptography.DSAManaged.keypairGenerated, Mono.Security.Cryptography.DSAManaged.m_disposed, Mono.Math.BigInteger.ModInverse(), Mono.Math.BigInteger.ModPow(), Mono.Security.Cryptography.DSAManaged.p, Mono.Security.Cryptography.DSAManaged.q, Mono.Math.BigInteger.Randomize(), and Mono.Security.Cryptography.DSAManaged.x.
Referenced by System.Security.Cryptography.DSACryptoServiceProvider.CreateSignature(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), and System.Security.Cryptography.DSACryptoServiceProvider.SignHash().