Terraria Decompiled: Mono.Security.Cryptography.DSAManaged.GenerateParams
GenerateParams()
void Mono.Security.Cryptography.DSAManaged.GenerateParams (int keyLength) inline private
Definition at line 70 of file DSAManaged.cs.
        {
            byte[] array = new byte[20];
            byte[] array2 = new byte[20];
            byte[] array3 = new byte[20];
            byte[] array4 = new byte[20];
            SHA1 sha = SHA1.Create();
            int num = (keyLength - 1) / 160;
            byte[] array5 = new byte[keyLength / 8];
            bool flag = false;
            while (!flag)
            {
                do
                {
                    this.Random.GetBytes(array);
                    array2 = sha.ComputeHash(array);
                    Array.Copy(array, 0, array3, 0, array.Length);
                    this.add(array3, array, 1);
                    array3 = sha.ComputeHash(array3);
                    for (int num2 = 0; num2 != array4.Length; num2++)
                    {
                        array4[num2] = array2[num2] ^ array3[num2];
                    }
                    byte[] array6 = array4;
                    int num3 = 0;
                    array6[num3] |= 128;
                    byte[] array7 = array4;
                    int num4 = 19;
                    array7[num4] |= 1;
                    this.q = new BigInteger(array4);
                }
                while (!this.q.IsProbablePrime());
                this.counter = 0;
                int num5 = 2;
                while (this.counter < 4096)
                {
                    for (int i = 0; i < num; i++)
                    {
                        this.add(array2, array, num5 + i);
                        array2 = sha.ComputeHash(array2);
                        Array.Copy(array2, 0, array5, array5.Length - (i + 1) * array2.Length, array2.Length);
                    }
                    this.add(array2, array, num5 + num);
                    array2 = sha.ComputeHash(array2);
                    Array.Copy(array2, array2.Length - (array5.Length - num * array2.Length), array5, 0, array5.Length - num * array2.Length);
                    byte[] array8 = array5;
                    int num6 = 0;
                    array8[num6] |= 128;
                    BigInteger bigInteger = new BigInteger(array5);
                    BigInteger bigInteger2 = bigInteger % (this.q * 2);
                    this.p = bigInteger - (bigInteger2 - 1);
                    if (this.p.TestBit((uint)(keyLength - 1)) && this.p.IsProbablePrime())
                    {
                        flag = true;
                        break;
                    }
                    this.counter++;
                    num5 += num + 1;
                }
            }
            BigInteger bigInteger3 = (this.p - 1) / this.q;
            for (;;)
            {
                BigInteger bigInteger4 = BigInteger.GenerateRandom(keyLength);
                if (!(bigInteger4 <= 1) && !(bigInteger4 >= this.p - 1))
                {
                    this.g = bigInteger4.ModPow(bigInteger3, this.p);
                    if (!(this.g <= 1))
                    {
                        break;
                    }
                }
            }
            this.seed = new BigInteger(array);
            this.j = (this.p - 1) / this.q;
        }
References Mono.Security.Cryptography.DSAManaged.add(), System.array, System.Security.Cryptography.HashAlgorithm.ComputeHash(), System.Array.Copy(), Mono.Security.Cryptography.DSAManaged.counter, System.Security.Cryptography.SHA1.Create(), Mono.Security.Cryptography.DSAManaged.g, Mono.Math.BigInteger.GenerateRandom(), Mono.Math.BigInteger.IsProbablePrime(), Mono.Math.BigInteger.ModPow(), Mono.Security.Cryptography.DSAManaged.p, Mono.Security.Cryptography.DSAManaged.q, and Mono.Math.BigInteger.TestBit().
Referenced by Mono.Security.Cryptography.DSAManaged.Generate().