Terraria Decompiled: Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ProvideUIElement
ProvideUIElement()
UIElement Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ProvideUIElement (BestiaryUICollectionInfo info) inline
Implements Terraria.GameContent.Bestiary.IBestiaryInfoElement.
Definition at line 78 of file NPCStatsReportInfoElement.cs.
        {
            if (info.UnlockState == BestiaryEntryUnlockState.NotKnownAtAll_0)
            {
                return null;
            }
            this.RefreshStats(this._instance);
            UIElement uielement = new UIElement
            {
                Width = new StyleDimension(0f, 1f),
                Height = new StyleDimension(109f, 0f)
            };
            int num = 99;
            int num2 = 35;
            int num3 = 3;
            int num4 = 0;
            UIImage uiimage = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_HP", 1))
            {
                Top = new StyleDimension((float)num4, 0f),
                Left = new StyleDimension((float)num3, 0f)
            };
            UIImage uiimage2 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Attack", 1))
            {
                Top = new StyleDimension((float)(num4 + num2), 0f),
                Left = new StyleDimension((float)num3, 0f)
            };
            UIImage uiimage3 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Defense", 1))
            {
                Top = new StyleDimension((float)(num4 + num2), 0f),
                Left = new StyleDimension((float)(num3 + num), 0f)
            };
            UIImage uiimage4 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Knockback", 1))
            {
                Top = new StyleDimension((float)num4, 0f),
                Left = new StyleDimension((float)(num3 + num), 0f)
            };
            uielement.Append(uiimage);
            uielement.Append(uiimage2);
            uielement.Append(uiimage3);
            uielement.Append(uiimage4);
            int num5 = -10;
            int num6 = 0;
            int num7 = (int)this.MonetaryValue;
            string text = Utils.Clamp<int>(num7 / 1000000, 0, 999).ToString();
            string text2 = Utils.Clamp<int>(num7 % 1000000 / 10000, 0, 99).ToString();
            string text3 = Utils.Clamp<int>(num7 % 10000 / 100, 0, 99).ToString();
            string text4 = Utils.Clamp<int>(num7 % 100 / 1, 0, 99).ToString();
            if (num7 / 1000000 < 1)
            {
                text = "-";
            }
            if (num7 / 10000 < 1)
            {
                text2 = "-";
            }
            if (num7 / 100 < 1)
            {
                text3 = "-";
            }
            if (num7 < 1)
            {
                text4 = "-";
            }
            string text5 = this.LifeMax.ToString();
            string text6 = this.Damage.ToString();
            string text7 = this.Defense.ToString();
            string text8;
            if (this.KnockbackResist > 0.8f)
            {
                text8 = Language.GetText("BestiaryInfo.KnockbackHigh").Value;
            }
            else if (this.KnockbackResist > 0.4f)
            {
                text8 = Language.GetText("BestiaryInfo.KnockbackMedium").Value;
            }
            else if (this.KnockbackResist > 0f)
            {
                text8 = Language.GetText("BestiaryInfo.KnockbackLow").Value;
            }
            else
            {
                text8 = Language.GetText("BestiaryInfo.KnockbackNone").Value;
            }
            if (info.UnlockState < BestiaryEntryUnlockState.CanShowStats_2 || this.HideStats)
            {
                text2 = (text = (text3 = (text4 = "?")));
                text6 = (text5 = (text7 = (text8 = "???")));
            }
            UIText uitext = new UIText(text5, 1f, false)
            {
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension((float)num5, 0f),
                Top = new StyleDimension((float)num6, 0f),
                IgnoresMouseInteraction = true
            };
            UIText uitext2 = new UIText(text8, 1f, false)
            {
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension((float)num5, 0f),
                Top = new StyleDimension((float)num6, 0f),
                IgnoresMouseInteraction = true
            };
            UIText uitext3 = new UIText(text6, 1f, false)
            {
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension((float)num5, 0f),
                Top = new StyleDimension((float)num6, 0f),
                IgnoresMouseInteraction = true
            };
            UIText uitext4 = new UIText(text7, 1f, false)
            {
                HAlign = 1f,
                VAlign = 0.5f,
                Left = new StyleDimension((float)num5, 0f),
                Top = new StyleDimension((float)num6, 0f),
                IgnoresMouseInteraction = true
            };
            uiimage.Append(uitext);
            uiimage2.Append(uitext3);
            uiimage3.Append(uitext4);
            uiimage4.Append(uitext2);
            int num8 = 66;
            if (num7 > 0)
            {
                UIHorizontalSeparator uihorizontalSeparator = new UIHorizontalSeparator(2, true)
                {
                    Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                    Color = new Color(89, 116, 213, 255) * 0.9f,
                    Left = new StyleDimension(0f, 0f),
                    Top = new StyleDimension((float)(num6 + num2 * 2), 0f)
                };
                uielement.Append(uihorizontalSeparator);
                num8 += 4;
                int num9 = num3;
                int num10 = num8 + 8;
                int num11 = 49;
                UIImage uiimage5 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Platinum", 1))
                {
                    Top = new StyleDimension((float)num10, 0f),
                    Left = new StyleDimension((float)num9, 0f)
                };
                UIImage uiimage6 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Gold", 1))
                {
                    Top = new StyleDimension((float)num10, 0f),
                    Left = new StyleDimension((float)(num9 + num11), 0f)
                };
                UIImage uiimage7 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Silver", 1))
                {
                    Top = new StyleDimension((float)num10, 0f),
                    Left = new StyleDimension((float)(num9 + num11 * 2 + 1), 0f)
                };
                UIImage uiimage8 = new UIImage(Main.Assets.Request<Texture2D>("Images/UI/Bestiary/Stat_Copper", 1))
                {
                    Top = new StyleDimension((float)num10, 0f),
                    Left = new StyleDimension((float)(num9 + num11 * 3 + 1), 0f)
                };
                if (text != "-")
                {
                    uielement.Append(uiimage5);
                }
                if (text2 != "-")
                {
                    uielement.Append(uiimage6);
                }
                if (text3 != "-")
                {
                    uielement.Append(uiimage7);
                }
                if (text4 != "-")
                {
                    uielement.Append(uiimage8);
                }
                int num12 = num5 + 3;
                float num13 = 0.85f;
                UIText uitext5 = new UIText(text, num13, false)
                {
                    HAlign = 1f,
                    VAlign = 0.5f,
                    Left = new StyleDimension((float)num12, 0f),
                    Top = new StyleDimension((float)num6, 0f)
                };
                UIText uitext6 = new UIText(text2, num13, false)
                {
                    HAlign = 1f,
                    VAlign = 0.5f,
                    Left = new StyleDimension((float)num12, 0f),
                    Top = new StyleDimension((float)num6, 0f)
                };
                UIText uitext7 = new UIText(text3, num13, false)
                {
                    HAlign = 1f,
                    VAlign = 0.5f,
                    Left = new StyleDimension((float)num12, 0f),
                    Top = new StyleDimension((float)num6, 0f)
                };
                UIText uitext8 = new UIText(text4, num13, false)
                {
                    HAlign = 1f,
                    VAlign = 0.5f,
                    Left = new StyleDimension((float)num12, 0f),
                    Top = new StyleDimension((float)num6, 0f)
                };
                uiimage5.Append(uitext5);
                uiimage6.Append(uitext6);
                uiimage7.Append(uitext7);
                uiimage8.Append(uitext8);
                num8 += 34;
            }
            num8 += 4;
            uielement.Height.Pixels = (float)num8;
            uiimage2.OnUpdate += this.ShowStats_Attack;
            uiimage3.OnUpdate += this.ShowStats_Defense;
            uiimage.OnUpdate += this.ShowStats_Life;
            uiimage4.OnUpdate += this.ShowStats_Knockback;
            return uielement;
        }
References Terraria.GameContent.Bestiary.NPCStatsReportInfoElement._instance, Terraria.UI.UIElement.Append(), Terraria.Main.Assets, Terraria.Utils.Clamp(), Microsoft.Xna.Framework.Graphics.Color, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.Damage, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.Defense, Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.Localization.Language.GetText(), System.info, int, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.KnockbackResist, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.LifeMax, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.MonetaryValue, Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.RefreshStats(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Attack(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Defense(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Knockback(), Terraria.GameContent.Bestiary.NPCStatsReportInfoElement.ShowStats_Life(), System.text, System.ToString, and Terraria.Localization.LocalizedText.Value.