Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [56/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, GameServerListFilter ret) inline static
Definition at line 944 of file RailConverter.cs.
        {
            ret.tags_contained = RAIL_API_PINVOKE.GameServerListFilter_tags_contained_get(ptr);
            ret.tags_not_contained = RAIL_API_PINVOKE.GameServerListFilter_tags_not_contained_get(ptr);
            ret.filter_password = (EnumRailOptionalValue)RAIL_API_PINVOKE.GameServerListFilter_filter_password_get(ptr);
            ret.filter_game_server_name = RAIL_API_PINVOKE.GameServerListFilter_filter_game_server_name_get(ptr);
            ret.filter_zone_id = RAIL_API_PINVOKE.GameServerListFilter_filter_zone_id_get(ptr);
            ret.filter_friends_created = (EnumRailOptionalValue)RAIL_API_PINVOKE.GameServerListFilter_filter_friends_created_get(ptr);
            ret.filter_dedicated_server = (EnumRailOptionalValue)RAIL_API_PINVOKE.GameServerListFilter_filter_dedicated_server_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.GameServerListFilter_filters_get(ptr), ret.filters);
            ret.filter_game_server_map = RAIL_API_PINVOKE.GameServerListFilter_filter_game_server_map_get(ptr);
            ret.filter_game_server_host = RAIL_API_PINVOKE.GameServerListFilter_filter_game_server_host_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.GameServerListFilter_owner_id_get(ptr), ret.owner_id);
        }
References rail.RailConverter.Cpp2Csharp(), rail.GameServerListFilter.filters, rail.RAIL_API_PINVOKE.GameServerListFilter_filter_dedicated_server_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filter_friends_created_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filter_game_server_host_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filter_game_server_map_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filter_game_server_name_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filter_password_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filter_zone_id_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_filters_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_owner_id_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_tags_contained_get(), rail.RAIL_API_PINVOKE.GameServerListFilter_tags_not_contained_get(), and rail.GameServerListFilter.owner_id.