Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [195/282]
static void rail.RailConverter.Csharp2Cpp (RailNetworkSessionState data, IntPtr ptr) inline static
Definition at line 2487 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailNetworkSessionState_session_error_set(ptr, (int)data.session_error);
            RAIL_API_PINVOKE.RailNetworkSessionState_remote_port_set(ptr, data.remote_port);
            RAIL_API_PINVOKE.RailNetworkSessionState_packets_in_send_buffer_set(ptr, data.packets_in_send_buffer);
            RAIL_API_PINVOKE.RailNetworkSessionState_is_connecting_set(ptr, data.is_connecting);
            RAIL_API_PINVOKE.RailNetworkSessionState_bytes_in_send_buffer_set(ptr, data.bytes_in_send_buffer);
            RAIL_API_PINVOKE.RailNetworkSessionState_is_using_relay_set(ptr, data.is_using_relay);
            RAIL_API_PINVOKE.RailNetworkSessionState_is_connection_active_set(ptr, data.is_connection_active);
            RAIL_API_PINVOKE.RailNetworkSessionState_remote_ip_set(ptr, data.remote_ip);
        }
References rail.RailNetworkSessionState.bytes_in_send_buffer, rail.RailNetworkSessionState.is_connecting, rail.RailNetworkSessionState.is_connection_active, rail.RailNetworkSessionState.is_using_relay, rail.RailNetworkSessionState.packets_in_send_buffer, rail.RAIL_API_PINVOKE.RailNetworkSessionState_bytes_in_send_buffer_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_is_connecting_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_is_connection_active_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_is_using_relay_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_packets_in_send_buffer_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_remote_ip_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_remote_port_set(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_session_error_set(), rail.RailNetworkSessionState.remote_ip, rail.RailNetworkSessionState.remote_port, and rail.RailNetworkSessionState.session_error.