Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [245/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RequestLeaderboardEntryParam ret) inline static
Definition at line 3288 of file RailConverter.cs.
        {
            ret.range_end = RAIL_API_PINVOKE.RequestLeaderboardEntryParam_range_end_get(ptr);
            ret.range_start = RAIL_API_PINVOKE.RequestLeaderboardEntryParam_range_start_get(ptr);
            ret.type = (LeaderboardType)RAIL_API_PINVOKE.RequestLeaderboardEntryParam_type_get(ptr);
            ret.user_coordinate = RAIL_API_PINVOKE.RequestLeaderboardEntryParam_user_coordinate_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RequestLeaderboardEntryParam_range_end_get(), rail.RAIL_API_PINVOKE.RequestLeaderboardEntryParam_range_start_get(), rail.RAIL_API_PINVOKE.RequestLeaderboardEntryParam_type_get(), and rail.RAIL_API_PINVOKE.RequestLeaderboardEntryParam_user_coordinate_get().