Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [23/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, BrowserDamageRectNeedsPaintRequest ret) inline static
Definition at line 370 of file RailConverter.cs.
        {
            RailConverter.Cpp2Csharp(ptr, ret);
            ret.update_bgra_height = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_height_get(ptr);
            ret.scroll_x_pos = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_x_pos_get(ptr);
            ret.bgra_data = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_data_get(ptr);
            ret.update_bgra_width = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_width_get(ptr);
            ret.page_scale_factor = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_page_scale_factor_get(ptr);
            ret.update_offset_y = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_y_get(ptr);
            ret.update_offset_x = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_x_get(ptr);
            ret.offset_x = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_x_get(ptr);
            ret.offset_y = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_y_get(ptr);
            ret.bgra_height = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_height_get(ptr);
            ret.scroll_y_pos = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_y_pos_get(ptr);
            ret.bgra_width = RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_width_get(ptr);
        }
References rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_data_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_height_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_width_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_x_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_y_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_page_scale_factor_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_x_pos_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_y_pos_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_height_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_width_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_x_get(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_y_get(), and rail.RailConverter.Cpp2Csharp().