Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [148/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailAssetInfo ret) inline static
Definition at line 1758 of file RailConverter.cs.
        {
            ret.asset_id = RAIL_API_PINVOKE.RailAssetInfo_asset_id_get(ptr);
            ret.origin = RAIL_API_PINVOKE.RailAssetInfo_origin_get(ptr);
            ret.product_id = RAIL_API_PINVOKE.RailAssetInfo_product_id_get(ptr);
            ret.flag = RAIL_API_PINVOKE.RailAssetInfo_flag_get(ptr);
            ret.state = RAIL_API_PINVOKE.RailAssetInfo_state_get(ptr);
            ret.progress = RAIL_API_PINVOKE.RailAssetInfo_progress_get(ptr);
            ret.expire_time = RAIL_API_PINVOKE.RailAssetInfo_expire_time_get(ptr);
            ret.position = RAIL_API_PINVOKE.RailAssetInfo_position_get(ptr);
            ret.product_name = RAIL_API_PINVOKE.RailAssetInfo_product_name_get(ptr);
            ret.quantity = RAIL_API_PINVOKE.RailAssetInfo_quantity_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RailAssetInfo_asset_id_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_expire_time_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_flag_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_origin_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_position_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_product_id_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_product_name_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_progress_get(), rail.RAIL_API_PINVOKE.RailAssetInfo_quantity_get(), and rail.RAIL_API_PINVOKE.RailAssetInfo_state_get().