Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [94/282]
static void rail.RailConverter.Csharp2Cpp (List< RailAssetInfo > ret, IntPtr ptr) inline static
Definition at line 5060 of file RailConverter.cs.
        {
            int count = ret.Count;
            RAIL_API_PINVOKE.RailArrayRailAssetInfo_clear(ptr);
            for (int i = 0; i < count; i++)
            {
                IntPtr intPtr = RAIL_API_PINVOKE.new_RailAssetInfo__SWIG_0();
                RailConverter.Csharp2Cpp(ret[i], intPtr);
                RAIL_API_PINVOKE.RailArrayRailAssetInfo_push_back(ptr, intPtr);
                RAIL_API_PINVOKE.delete_RailAssetInfo(intPtr);
            }
        }
References System.Collections.Generic.List< T >.Count, System.count, rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailAssetInfo(), rail.RAIL_API_PINVOKE.new_RailAssetInfo__SWIG_0(), rail.RAIL_API_PINVOKE.RailArrayRailAssetInfo_clear(), and rail.RAIL_API_PINVOKE.RailArrayRailAssetInfo_push_back().