Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [34/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, CreateBrowserOptions ret) inline static
Definition at line 560 of file RailConverter.cs.
        {
            ret.has_minimum_button = RAIL_API_PINVOKE.CreateBrowserOptions_has_minimum_button_get(ptr);
            ret.has_border = RAIL_API_PINVOKE.CreateBrowserOptions_has_border_get(ptr);
            ret.is_movable = RAIL_API_PINVOKE.CreateBrowserOptions_is_movable_get(ptr);
            ret.has_maximum_button = RAIL_API_PINVOKE.CreateBrowserOptions_has_maximum_button_get(ptr);
            ret.margin_left = RAIL_API_PINVOKE.CreateBrowserOptions_margin_left_get(ptr);
            ret.margin_top = RAIL_API_PINVOKE.CreateBrowserOptions_margin_top_get(ptr);
        }
References rail.RAIL_API_PINVOKE.CreateBrowserOptions_has_border_get(), rail.RAIL_API_PINVOKE.CreateBrowserOptions_has_maximum_button_get(), rail.RAIL_API_PINVOKE.CreateBrowserOptions_has_minimum_button_get(), rail.RAIL_API_PINVOKE.CreateBrowserOptions_is_movable_get(), rail.RAIL_API_PINVOKE.CreateBrowserOptions_margin_left_get(), and rail.RAIL_API_PINVOKE.CreateBrowserOptions_margin_top_get().