Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [195/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailNetworkSessionState ret) inline static
Definition at line 2474 of file RailConverter.cs.
        {
            ret.session_error = (RailResult)RAIL_API_PINVOKE.RailNetworkSessionState_session_error_get(ptr);
            ret.remote_port = RAIL_API_PINVOKE.RailNetworkSessionState_remote_port_get(ptr);
            ret.packets_in_send_buffer = RAIL_API_PINVOKE.RailNetworkSessionState_packets_in_send_buffer_get(ptr);
            ret.is_connecting = RAIL_API_PINVOKE.RailNetworkSessionState_is_connecting_get(ptr);
            ret.bytes_in_send_buffer = RAIL_API_PINVOKE.RailNetworkSessionState_bytes_in_send_buffer_get(ptr);
            ret.is_using_relay = RAIL_API_PINVOKE.RailNetworkSessionState_is_using_relay_get(ptr);
            ret.is_connection_active = RAIL_API_PINVOKE.RailNetworkSessionState_is_connection_active_get(ptr);
            ret.remote_ip = RAIL_API_PINVOKE.RailNetworkSessionState_remote_ip_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RailNetworkSessionState_bytes_in_send_buffer_get(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_is_connecting_get(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_is_connection_active_get(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_is_using_relay_get(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_packets_in_send_buffer_get(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_remote_ip_get(), rail.RAIL_API_PINVOKE.RailNetworkSessionState_remote_port_get(), and rail.RAIL_API_PINVOKE.RailNetworkSessionState_session_error_get().