Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [139/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, PlayerPersonalInfo ret) inline static
Definition at line 1626 of file RailConverter.cs.
        {
            ret.error_code = (RailResult)RAIL_API_PINVOKE.PlayerPersonalInfo_error_code_get(ptr);
            ret.avatar_url = RAIL_API_PINVOKE.PlayerPersonalInfo_avatar_url_get(ptr);
            ret.rail_level = RAIL_API_PINVOKE.PlayerPersonalInfo_rail_level_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.PlayerPersonalInfo_rail_id_get(ptr), ret.rail_id);
            ret.rail_name = RAIL_API_PINVOKE.PlayerPersonalInfo_rail_name_get(ptr);
            ret.email_address = RAIL_API_PINVOKE.PlayerPersonalInfo_email_address_get(ptr);
        }
References rail.RailConverter.Cpp2Csharp(), rail.RAIL_API_PINVOKE.PlayerPersonalInfo_avatar_url_get(), rail.RAIL_API_PINVOKE.PlayerPersonalInfo_email_address_get(), rail.RAIL_API_PINVOKE.PlayerPersonalInfo_error_code_get(), rail.RAIL_API_PINVOKE.PlayerPersonalInfo_rail_id_get(), rail.RAIL_API_PINVOKE.PlayerPersonalInfo_rail_level_get(), rail.RAIL_API_PINVOKE.PlayerPersonalInfo_rail_name_get(), and rail.PlayerPersonalInfo.rail_id.