Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [55/282]
static void rail.RailConverter.Csharp2Cpp (GameServerInfo data, IntPtr ptr) inline static
Definition at line 919 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data.server_kvs, RAIL_API_PINVOKE.GameServerInfo_server_kvs_get(ptr));
            RailConverter.Csharp2Cpp(data.owner_rail_id, RAIL_API_PINVOKE.GameServerInfo_owner_rail_id_get(ptr));
            RAIL_API_PINVOKE.GameServerInfo_game_server_name_set(ptr, data.game_server_name);
            RAIL_API_PINVOKE.GameServerInfo_server_fullname_set(ptr, data.server_fullname);
            RAIL_API_PINVOKE.GameServerInfo_is_dedicated_set(ptr, data.is_dedicated);
            RAIL_API_PINVOKE.GameServerInfo_server_info_set(ptr, data.server_info);
            RAIL_API_PINVOKE.GameServerInfo_server_tags_set(ptr, data.server_tags);
            RAIL_API_PINVOKE.GameServerInfo_spectator_host_set(ptr, data.spectator_host);
            RAIL_API_PINVOKE.GameServerInfo_server_description_set(ptr, data.server_description);
            RAIL_API_PINVOKE.GameServerInfo_server_host_set(ptr, data.server_host);
            RailConverter.Csharp2Cpp(data.game_server_rail_id, RAIL_API_PINVOKE.GameServerInfo_game_server_rail_id_get(ptr));
            RAIL_API_PINVOKE.GameServerInfo_has_password_set(ptr, data.has_password);
            RAIL_API_PINVOKE.GameServerInfo_server_version_set(ptr, data.server_version);
            RailConverter.Csharp2Cpp(data.server_mods, RAIL_API_PINVOKE.GameServerInfo_server_mods_get(ptr));
            RAIL_API_PINVOKE.GameServerInfo_bot_players_set(ptr, data.bot_players);
            RAIL_API_PINVOKE.GameServerInfo_game_server_map_set(ptr, data.game_server_map);
            RAIL_API_PINVOKE.GameServerInfo_max_players_set(ptr, data.max_players);
            RAIL_API_PINVOKE.GameServerInfo_current_players_set(ptr, data.current_players);
            RAIL_API_PINVOKE.GameServerInfo_is_friend_only_set(ptr, data.is_friend_only);
            RAIL_API_PINVOKE.GameServerInfo_zone_id_set(ptr, data.zone_id);
        }
References rail.GameServerInfo.bot_players, rail.RailConverter.Csharp2Cpp(), rail.GameServerInfo.current_players, rail.GameServerInfo.game_server_map, rail.GameServerInfo.game_server_name, rail.GameServerInfo.game_server_rail_id, rail.RAIL_API_PINVOKE.GameServerInfo_bot_players_set(), rail.RAIL_API_PINVOKE.GameServerInfo_current_players_set(), rail.RAIL_API_PINVOKE.GameServerInfo_game_server_map_set(), rail.RAIL_API_PINVOKE.GameServerInfo_game_server_name_set(), rail.RAIL_API_PINVOKE.GameServerInfo_game_server_rail_id_get(), rail.RAIL_API_PINVOKE.GameServerInfo_has_password_set(), rail.RAIL_API_PINVOKE.GameServerInfo_is_dedicated_set(), rail.RAIL_API_PINVOKE.GameServerInfo_is_friend_only_set(), rail.RAIL_API_PINVOKE.GameServerInfo_max_players_set(), rail.RAIL_API_PINVOKE.GameServerInfo_owner_rail_id_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_description_set(), rail.RAIL_API_PINVOKE.GameServerInfo_server_fullname_set(), rail.RAIL_API_PINVOKE.GameServerInfo_server_host_set(), rail.RAIL_API_PINVOKE.GameServerInfo_server_info_set(), rail.RAIL_API_PINVOKE.GameServerInfo_server_kvs_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_mods_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_tags_set(), rail.RAIL_API_PINVOKE.GameServerInfo_server_version_set(), rail.RAIL_API_PINVOKE.GameServerInfo_spectator_host_set(), rail.RAIL_API_PINVOKE.GameServerInfo_zone_id_set(), rail.GameServerInfo.has_password, rail.GameServerInfo.is_dedicated, rail.GameServerInfo.is_friend_only, rail.GameServerInfo.max_players, rail.GameServerInfo.owner_rail_id, rail.GameServerInfo.server_description, rail.GameServerInfo.server_fullname, rail.GameServerInfo.server_host, rail.GameServerInfo.server_info, rail.GameServerInfo.server_kvs, rail.GameServerInfo.server_mods, rail.GameServerInfo.server_tags, rail.GameServerInfo.server_version, rail.GameServerInfo.spectator_host, and rail.GameServerInfo.zone_id.