Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [217/282]
static void rail.RailConverter.Csharp2Cpp (RailSpaceWorkUpdateOptions data, IntPtr ptr) inline static
Definition at line 2875 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_my_vote_set(ptr, data.with_my_vote);
            RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_vote_detail_set(ptr, data.with_vote_detail);
            RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_metadata_set(ptr, data.with_metadata);
            RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_detail_set(ptr, data.with_detail);
            RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_check_has_subscribed_set(ptr, data.check_has_subscribed);
            RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_check_has_favorited_set(ptr, data.check_has_favorited);
        }
References rail.RailSpaceWorkUpdateOptions.check_has_favorited, rail.RailSpaceWorkUpdateOptions.check_has_subscribed, rail.RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_check_has_favorited_set(), rail.RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_check_has_subscribed_set(), rail.RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_detail_set(), rail.RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_metadata_set(), rail.RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_my_vote_set(), rail.RAIL_API_PINVOKE.RailSpaceWorkUpdateOptions_with_vote_detail_set(), rail.RailSpaceWorkUpdateOptions.with_detail, rail.RailSpaceWorkUpdateOptions.with_metadata, rail.RailSpaceWorkUpdateOptions.with_my_vote, and rail.RailSpaceWorkUpdateOptions.with_vote_detail.