Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [23/282]
static void rail.RailConverter.Csharp2Cpp (BrowserDamageRectNeedsPaintRequest data, IntPtr ptr) inline static
Definition at line 388 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data, ptr);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_height_set(ptr, data.update_bgra_height);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_x_pos_set(ptr, data.scroll_x_pos);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_data_set(ptr, data.bgra_data);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_width_set(ptr, data.update_bgra_width);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_page_scale_factor_set(ptr, data.page_scale_factor);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_y_set(ptr, data.update_offset_y);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_x_set(ptr, data.update_offset_x);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_x_set(ptr, data.offset_x);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_y_set(ptr, data.offset_y);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_height_set(ptr, data.bgra_height);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_y_pos_set(ptr, data.scroll_y_pos);
            RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_width_set(ptr, data.bgra_width);
        }
References rail.BrowserDamageRectNeedsPaintRequest.bgra_data, rail.BrowserDamageRectNeedsPaintRequest.bgra_height, rail.BrowserDamageRectNeedsPaintRequest.bgra_width, rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_data_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_height_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_bgra_width_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_x_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_offset_y_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_page_scale_factor_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_x_pos_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_scroll_y_pos_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_height_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_bgra_width_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_x_set(), rail.RAIL_API_PINVOKE.BrowserDamageRectNeedsPaintRequest_update_offset_y_set(), rail.RailConverter.Csharp2Cpp(), rail.BrowserDamageRectNeedsPaintRequest.offset_x, rail.BrowserDamageRectNeedsPaintRequest.offset_y, rail.BrowserDamageRectNeedsPaintRequest.page_scale_factor, rail.BrowserDamageRectNeedsPaintRequest.scroll_x_pos, rail.BrowserDamageRectNeedsPaintRequest.scroll_y_pos, rail.BrowserDamageRectNeedsPaintRequest.update_bgra_height, rail.BrowserDamageRectNeedsPaintRequest.update_bgra_width, rail.BrowserDamageRectNeedsPaintRequest.update_offset_x, and rail.BrowserDamageRectNeedsPaintRequest.update_offset_y.