Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [81/282]
static void rail.RailConverter.Csharp2Cpp (LeaderboardUploaded data, IntPtr ptr) inline static
Definition at line 1363 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data, ptr);
            RAIL_API_PINVOKE.LeaderboardUploaded_old_rank_set(ptr, data.old_rank);
            RAIL_API_PINVOKE.LeaderboardUploaded_leaderboard_name_set(ptr, data.leaderboard_name);
            RAIL_API_PINVOKE.LeaderboardUploaded_score_set(ptr, data.score);
            RAIL_API_PINVOKE.LeaderboardUploaded_better_score_set(ptr, data.better_score);
            RAIL_API_PINVOKE.LeaderboardUploaded_new_rank_set(ptr, data.new_rank);
        }
References rail.LeaderboardUploaded.better_score, rail.RailConverter.Csharp2Cpp(), rail.LeaderboardUploaded.leaderboard_name, rail.RAIL_API_PINVOKE.LeaderboardUploaded_better_score_set(), rail.RAIL_API_PINVOKE.LeaderboardUploaded_leaderboard_name_set(), rail.RAIL_API_PINVOKE.LeaderboardUploaded_new_rank_set(), rail.RAIL_API_PINVOKE.LeaderboardUploaded_old_rank_set(), rail.RAIL_API_PINVOKE.LeaderboardUploaded_score_set(), rail.LeaderboardUploaded.new_rank, rail.LeaderboardUploaded.old_rank, and rail.LeaderboardUploaded.score.