Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [86/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, List< EnumRailWorkFileClass > ret) inline static
Definition at line 4986 of file RailConverter.cs.
        {
            ret.Clear();
            uint num = RAIL_API_PINVOKE.RailArrayEnumRailWorkFileClass_size(ptr);
            int num2 = 0;
            while ((long)num2 < (long)((ulong)num))
            {
                IntPtr intPtr = RAIL_API_PINVOKE.RailArrayEnumRailWorkFileClass_Item(ptr, (uint)num2);
                ret.Add((EnumRailWorkFileClass)RAIL_API_PINVOKE.GetInt(intPtr));
                num2++;
            }
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), rail.RAIL_API_PINVOKE.GetInt(), rail.RAIL_API_PINVOKE.RailArrayEnumRailWorkFileClass_Item(), and rail.RAIL_API_PINVOKE.RailArrayEnumRailWorkFileClass_size().