Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [57/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, GameServerListFilterKey ret) inline static
Definition at line 976 of file RailConverter.cs.
        {
            ret.filter_value = RAIL_API_PINVOKE.GameServerListFilterKey_filter_value_get(ptr);
            ret.key_name = RAIL_API_PINVOKE.GameServerListFilterKey_key_name_get(ptr);
            ret.value_type = (EnumRailPropertyValueType)RAIL_API_PINVOKE.GameServerListFilterKey_value_type_get(ptr);
            ret.comparison_type = (EnumRailComparisonType)RAIL_API_PINVOKE.GameServerListFilterKey_comparison_type_get(ptr);
        }
References rail.RAIL_API_PINVOKE.GameServerListFilterKey_comparison_type_get(), rail.RAIL_API_PINVOKE.GameServerListFilterKey_filter_value_get(), rail.RAIL_API_PINVOKE.GameServerListFilterKey_key_name_get(), and rail.RAIL_API_PINVOKE.GameServerListFilterKey_value_type_get().