Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [281/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, ZoneInfo ret) inline static
Definition at line 3892 of file RailConverter.cs.
        {
            ret.status = (EnumZoneStatus)RAIL_API_PINVOKE.ZoneInfo_status_get(ptr);
            ret.description = RAIL_API_PINVOKE.ZoneInfo_description_get(ptr);
            ret.name = RAIL_API_PINVOKE.ZoneInfo_name_get(ptr);
            ret.idc_id = RAIL_API_PINVOKE.ZoneInfo_idc_id_get(ptr);
            ret.country_code = RAIL_API_PINVOKE.ZoneInfo_country_code_get(ptr);
            ret.zone_id = RAIL_API_PINVOKE.ZoneInfo_zone_id_get(ptr);
        }
References rail.RAIL_API_PINVOKE.ZoneInfo_country_code_get(), rail.RAIL_API_PINVOKE.ZoneInfo_description_get(), rail.RAIL_API_PINVOKE.ZoneInfo_idc_id_get(), rail.RAIL_API_PINVOKE.ZoneInfo_name_get(), rail.RAIL_API_PINVOKE.ZoneInfo_status_get(), and rail.RAIL_API_PINVOKE.ZoneInfo_zone_id_get().