Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [55/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, GameServerInfo ret) inline static
Definition at line 894 of file RailConverter.cs.
        {
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.GameServerInfo_server_kvs_get(ptr), ret.server_kvs);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.GameServerInfo_owner_rail_id_get(ptr), ret.owner_rail_id);
            ret.game_server_name = RAIL_API_PINVOKE.GameServerInfo_game_server_name_get(ptr);
            ret.server_fullname = RAIL_API_PINVOKE.GameServerInfo_server_fullname_get(ptr);
            ret.is_dedicated = RAIL_API_PINVOKE.GameServerInfo_is_dedicated_get(ptr);
            ret.server_info = RAIL_API_PINVOKE.GameServerInfo_server_info_get(ptr);
            ret.server_tags = RAIL_API_PINVOKE.GameServerInfo_server_tags_get(ptr);
            ret.spectator_host = RAIL_API_PINVOKE.GameServerInfo_spectator_host_get(ptr);
            ret.server_description = RAIL_API_PINVOKE.GameServerInfo_server_description_get(ptr);
            ret.server_host = RAIL_API_PINVOKE.GameServerInfo_server_host_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.GameServerInfo_game_server_rail_id_get(ptr), ret.game_server_rail_id);
            ret.has_password = RAIL_API_PINVOKE.GameServerInfo_has_password_get(ptr);
            ret.server_version = RAIL_API_PINVOKE.GameServerInfo_server_version_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.GameServerInfo_server_mods_get(ptr), ret.server_mods);
            ret.bot_players = RAIL_API_PINVOKE.GameServerInfo_bot_players_get(ptr);
            ret.game_server_map = RAIL_API_PINVOKE.GameServerInfo_game_server_map_get(ptr);
            ret.max_players = RAIL_API_PINVOKE.GameServerInfo_max_players_get(ptr);
            ret.current_players = RAIL_API_PINVOKE.GameServerInfo_current_players_get(ptr);
            ret.is_friend_only = RAIL_API_PINVOKE.GameServerInfo_is_friend_only_get(ptr);
            ret.zone_id = RAIL_API_PINVOKE.GameServerInfo_zone_id_get(ptr);
        }
References rail.RailConverter.Cpp2Csharp(), rail.GameServerInfo.game_server_rail_id, rail.RAIL_API_PINVOKE.GameServerInfo_bot_players_get(), rail.RAIL_API_PINVOKE.GameServerInfo_current_players_get(), rail.RAIL_API_PINVOKE.GameServerInfo_game_server_map_get(), rail.RAIL_API_PINVOKE.GameServerInfo_game_server_name_get(), rail.RAIL_API_PINVOKE.GameServerInfo_game_server_rail_id_get(), rail.RAIL_API_PINVOKE.GameServerInfo_has_password_get(), rail.RAIL_API_PINVOKE.GameServerInfo_is_dedicated_get(), rail.RAIL_API_PINVOKE.GameServerInfo_is_friend_only_get(), rail.RAIL_API_PINVOKE.GameServerInfo_max_players_get(), rail.RAIL_API_PINVOKE.GameServerInfo_owner_rail_id_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_description_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_fullname_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_host_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_info_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_kvs_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_mods_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_tags_get(), rail.RAIL_API_PINVOKE.GameServerInfo_server_version_get(), rail.RAIL_API_PINVOKE.GameServerInfo_spectator_host_get(), rail.RAIL_API_PINVOKE.GameServerInfo_zone_id_get(), rail.GameServerInfo.owner_rail_id, rail.GameServerInfo.server_kvs, and rail.GameServerInfo.server_mods.