Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [58/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, GameServerListSorter ret) inline static
Definition at line 994 of file RailConverter.cs.
        {
            ret.sort_key = RAIL_API_PINVOKE.GameServerListSorter_sort_key_get(ptr);
            ret.sort_type = (EnumRailSortType)RAIL_API_PINVOKE.GameServerListSorter_sort_type_get(ptr);
            ret.sorter_key_type = (GameServerListSorterKeyType)RAIL_API_PINVOKE.GameServerListSorter_sorter_key_type_get(ptr);
            ret.sort_value_type = (EnumRailPropertyValueType)RAIL_API_PINVOKE.GameServerListSorter_sort_value_type_get(ptr);
        }
References rail.RAIL_API_PINVOKE.GameServerListSorter_sort_key_get(), rail.RAIL_API_PINVOKE.GameServerListSorter_sort_type_get(), rail.RAIL_API_PINVOKE.GameServerListSorter_sort_value_type_get(), and rail.RAIL_API_PINVOKE.GameServerListSorter_sorter_key_type_get().