Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [99/282]
static void rail.RailConverter.Csharp2Cpp (List< RailFriendInfo > ret, IntPtr ptr) inline static
Definition at line 4588 of file RailConverter.cs.
        {
            int count = ret.Count;
            RAIL_API_PINVOKE.RailArrayRailFriendInfo_clear(ptr);
            for (int i = 0; i < count; i++)
            {
                IntPtr intPtr = RAIL_API_PINVOKE.new_RailFriendInfo__SWIG_0();
                RailConverter.Csharp2Cpp(ret[i], intPtr);
                RAIL_API_PINVOKE.RailArrayRailFriendInfo_push_back(ptr, intPtr);
                RAIL_API_PINVOKE.delete_RailFriendInfo(intPtr);
            }
        }
References System.Collections.Generic.List< T >.Count, System.count, rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailFriendInfo(), rail.RAIL_API_PINVOKE.new_RailFriendInfo__SWIG_0(), rail.RAIL_API_PINVOKE.RailArrayRailFriendInfo_clear(), and rail.RAIL_API_PINVOKE.RailArrayRailFriendInfo_push_back().