Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [253/282]
static void rail.RailConverter.Csharp2Cpp (RoomMembersInfo data, IntPtr ptr) inline static
Definition at line 3463 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data, ptr);
            RailConverter.Csharp2Cpp(data.member_info, RAIL_API_PINVOKE.RoomMembersInfo_member_info_get(ptr));
            RAIL_API_PINVOKE.RoomMembersInfo_room_id_set(ptr, data.room_id);
            RAIL_API_PINVOKE.RoomMembersInfo_member_num_set(ptr, data.member_num);
        }
References rail.RailConverter.Csharp2Cpp(), rail.RoomMembersInfo.member_info, rail.RoomMembersInfo.member_num, rail.RoomMembersInfo.room_id, rail.RAIL_API_PINVOKE.RoomMembersInfo_member_info_get(), rail.RAIL_API_PINVOKE.RoomMembersInfo_member_num_set(), and rail.RAIL_API_PINVOKE.RoomMembersInfo_room_id_set().