Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [240/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailWindowLayout ret) inline static
Definition at line 3220 of file RailConverter.cs.
        {
            ret.x_margin = RAIL_API_PINVOKE.RailWindowLayout_x_margin_get(ptr);
            ret.y_margin = RAIL_API_PINVOKE.RailWindowLayout_y_margin_get(ptr);
            ret.position_type = (EnumRailNotifyWindowPosition)RAIL_API_PINVOKE.RailWindowLayout_position_type_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RailWindowLayout_position_type_get(), rail.RAIL_API_PINVOKE.RailWindowLayout_x_margin_get(), and rail.RAIL_API_PINVOKE.RailWindowLayout_y_margin_get().