Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [148/282]
static void rail.RailConverter.Csharp2Cpp (RailAssetInfo data, IntPtr ptr) inline static
Definition at line 1773 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailAssetInfo_asset_id_set(ptr, data.asset_id);
            RAIL_API_PINVOKE.RailAssetInfo_origin_set(ptr, data.origin);
            RAIL_API_PINVOKE.RailAssetInfo_product_id_set(ptr, data.product_id);
            RAIL_API_PINVOKE.RailAssetInfo_flag_set(ptr, data.flag);
            RAIL_API_PINVOKE.RailAssetInfo_state_set(ptr, data.state);
            RAIL_API_PINVOKE.RailAssetInfo_progress_set(ptr, data.progress);
            RAIL_API_PINVOKE.RailAssetInfo_expire_time_set(ptr, data.expire_time);
            RAIL_API_PINVOKE.RailAssetInfo_position_set(ptr, data.position);
            RAIL_API_PINVOKE.RailAssetInfo_product_name_set(ptr, data.product_name);
            RAIL_API_PINVOKE.RailAssetInfo_quantity_set(ptr, data.quantity);
        }
References rail.RailAssetInfo.asset_id, rail.RailAssetInfo.expire_time, rail.RailAssetInfo.flag, rail.RailAssetInfo.origin, rail.RailAssetInfo.position, rail.RailAssetInfo.product_id, rail.RailAssetInfo.product_name, rail.RailAssetInfo.progress, rail.RailAssetInfo.quantity, rail.RAIL_API_PINVOKE.RailAssetInfo_asset_id_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_expire_time_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_flag_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_origin_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_position_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_product_id_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_product_name_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_progress_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_quantity_set(), rail.RAIL_API_PINVOKE.RailAssetInfo_state_set(), and rail.RailAssetInfo.state.