Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [213/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailSpaceWorkDescriptor ret) inline static
Definition at line 2780 of file RailConverter.cs.
        {
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RailSpaceWorkDescriptor_vote_details_get(ptr), ret.vote_details);
            ret.description = RAIL_API_PINVOKE.RailSpaceWorkDescriptor_description_get(ptr);
            ret.preview_url = RAIL_API_PINVOKE.RailSpaceWorkDescriptor_preview_url_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RailSpaceWorkDescriptor_id_get(ptr), ret.id);
            ret.detail_url = RAIL_API_PINVOKE.RailSpaceWorkDescriptor_detail_url_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RailSpaceWorkDescriptor_uploader_ids_get(ptr), ret.uploader_ids);
            ret.name = RAIL_API_PINVOKE.RailSpaceWorkDescriptor_name_get(ptr);
        }
References rail.RailConverter.Cpp2Csharp(), rail.RailSpaceWorkDescriptor.id, rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_description_get(), rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_detail_url_get(), rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_id_get(), rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_name_get(), rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_preview_url_get(), rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_uploader_ids_get(), rail.RAIL_API_PINVOKE.RailSpaceWorkDescriptor_vote_details_get(), rail.RailSpaceWorkDescriptor.uploader_ids, and rail.RailSpaceWorkDescriptor.vote_details.