Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [237/282]
static void rail.RailConverter.Csharp2Cpp (RailVoiceCaptureSpecification data, IntPtr ptr) inline static
Definition at line 3185 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailVoiceCaptureSpecification_channels_set(ptr, (int)data.channels);
            RAIL_API_PINVOKE.RailVoiceCaptureSpecification_samples_per_second_set(ptr, data.samples_per_second);
            RAIL_API_PINVOKE.RailVoiceCaptureSpecification_bits_per_sample_set(ptr, data.bits_per_sample);
            RAIL_API_PINVOKE.RailVoiceCaptureSpecification_capture_format_set(ptr, (int)data.capture_format);
        }
References rail.RailVoiceCaptureSpecification.bits_per_sample, rail.RailVoiceCaptureSpecification.capture_format, rail.RailVoiceCaptureSpecification.channels, rail.RAIL_API_PINVOKE.RailVoiceCaptureSpecification_bits_per_sample_set(), rail.RAIL_API_PINVOKE.RailVoiceCaptureSpecification_capture_format_set(), rail.RAIL_API_PINVOKE.RailVoiceCaptureSpecification_channels_set(), rail.RAIL_API_PINVOKE.RailVoiceCaptureSpecification_samples_per_second_set(), and rail.RailVoiceCaptureSpecification.samples_per_second.