Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [251/282]
static void rail.RailConverter.Csharp2Cpp (RoomInfoListFilterKey data, IntPtr ptr) inline static
Definition at line 3427 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RoomInfoListFilterKey_filter_value_set(ptr, data.filter_value);
            RAIL_API_PINVOKE.RoomInfoListFilterKey_key_name_set(ptr, data.key_name);
            RAIL_API_PINVOKE.RoomInfoListFilterKey_value_type_set(ptr, (int)data.value_type);
            RAIL_API_PINVOKE.RoomInfoListFilterKey_comparison_type_set(ptr, (int)data.comparison_type);
        }
References rail.RoomInfoListFilterKey.comparison_type, rail.RoomInfoListFilterKey.filter_value, rail.RoomInfoListFilterKey.key_name, rail.RAIL_API_PINVOKE.RoomInfoListFilterKey_comparison_type_set(), rail.RAIL_API_PINVOKE.RoomInfoListFilterKey_filter_value_set(), rail.RAIL_API_PINVOKE.RoomInfoListFilterKey_key_name_set(), rail.RAIL_API_PINVOKE.RoomInfoListFilterKey_value_type_set(), and rail.RoomInfoListFilterKey.value_type.