Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [226/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailTextInputWindowOption ret) inline static
Definition at line 2996 of file RailConverter.cs.
        {
            ret.enable_multi_line_edit = RAIL_API_PINVOKE.RailTextInputWindowOption_enable_multi_line_edit_get(ptr);
            ret.description = RAIL_API_PINVOKE.RailTextInputWindowOption_description_get(ptr);
            ret.position_top = RAIL_API_PINVOKE.RailTextInputWindowOption_position_top_get(ptr);
            ret.position_left = RAIL_API_PINVOKE.RailTextInputWindowOption_position_left_get(ptr);
            ret.caption_text = RAIL_API_PINVOKE.RailTextInputWindowOption_caption_text_get(ptr);
            ret.show_password_input = RAIL_API_PINVOKE.RailTextInputWindowOption_show_password_input_get(ptr);
            ret.is_min_window = RAIL_API_PINVOKE.RailTextInputWindowOption_is_min_window_get(ptr);
            ret.content_placeholder = RAIL_API_PINVOKE.RailTextInputWindowOption_content_placeholder_get(ptr);
            ret.auto_cancel = RAIL_API_PINVOKE.RailTextInputWindowOption_auto_cancel_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RailTextInputWindowOption_auto_cancel_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_caption_text_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_content_placeholder_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_description_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_enable_multi_line_edit_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_is_min_window_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_position_left_get(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_position_top_get(), and rail.RAIL_API_PINVOKE.RailTextInputWindowOption_show_password_input_get().