Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [1/282]
static void rail.RailConverter.Csharp2Cpp (AcquireSessionTicketResponse data, IntPtr ptr) inline static
Definition at line 17 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data, ptr);
            RailConverter.Csharp2Cpp(data.session_ticket, RAIL_API_PINVOKE.AcquireSessionTicketResponse_session_ticket_get(ptr));
        }
References rail.RAIL_API_PINVOKE.AcquireSessionTicketResponse_session_ticket_get(), rail.RailConverter.Csharp2Cpp(), and rail.AcquireSessionTicketResponse.session_ticket.
Referenced by rail.IRailGameServerImpl.AbandonGameServerSessionTicket(), rail.IRailPlayerImpl.AbandonSessionTicket(), rail.IRailNetworkImpl.AcceptSessionRequest(), rail.IRailSpaceWorkImpl.AddAssociatedGameIDs(), rail.IRailScreenshotImpl.AssociatePublishedFiles(), rail.IRailGameServerHelperImpl.AsyncAddFavoriteGameServer(), rail.IRailGameServerHelperImpl.AsyncAddFavoriteGameServer(), rail.IRailFriendsImpl.AsyncAddFriend(), rail.IRailVoiceChannelImpl.AsyncAddUsers(), rail.IRailLeaderboardImpl.AsyncAttachSpaceWork(), rail.IRailRoomImpl.AsyncClearRoomMetadata(), rail.IRailBrowserHelperImpl.AsyncCreateBrowser(), rail.IRailBrowserHelperImpl.AsyncCreateBrowser(), rail.IRailGameServerHelperImpl.AsyncCreateGameServer(), rail.IRailGameServerHelperImpl.AsyncCreateGameServer(), rail.IRailGameServerHelperImpl.AsyncCreateGameServer(), rail.IRailRoomHelperImpl.AsyncCreateRoom(), rail.IRailVoiceHelperImpl.AsyncCreateVoiceChannel(), rail.IRailAssetsImpl.AsyncDirectConsumeAssets(), rail.IRailSmallObjectServiceHelperImpl.AsyncDownloadObjects(), rail.IRailAssetsImpl.AsyncExchangeAssets(), rail.IRailAssetsImpl.AsyncExchangeAssetsTo(), rail.IRailFriendsImpl.AsyncGetFriendMetadata(), rail.IRailGameServerHelperImpl.AsyncGetGameServerList(), rail.IRailGameServerHelperImpl.AsyncGetGameServerPlayerList(), rail.IRailFriendsImpl.AsyncGetInviteCommandLine(), rail.IRailUsersHelperImpl.AsyncGetInviteDetail(), rail.IRailRoomImpl.AsyncGetMemberMetadata(), rail.IRailGameServerImpl.AsyncGetMetadata(), rail.IRailUserSpaceHelperImpl.AsyncGetMyFavoritesWorks(), rail.IRailUserSpaceHelperImpl.AsyncGetMyFavoritesWorks(), rail.IRailUserSpaceHelperImpl.AsyncGetMySubscribedWorks(), rail.IRailUserSpaceHelperImpl.AsyncGetMySubscribedWorks(), rail.IRailFriendsImpl.AsyncGetPersonalInfo(), rail.IRailZoneHelperImpl.AsyncGetRoomListInZone(), rail.IRailRoomImpl.AsyncGetRoomMetadata(), rail.IRailUsersHelperImpl.AsyncGetUserLimits(), rail.IRailUsersHelperImpl.AsyncGetUsersInfo(), rail.IRailDlcHelperImpl.AsyncInstallDlc(), rail.IRailUsersHelperImpl.AsyncInviteUsers(), rail.IRailRoomImpl.AsyncKickOffMember(), rail.IRailStorageHelperImpl.AsyncListStreamFiles(), rail.IRailAssetsImpl.AsyncMergeAsset(), rail.IRailAssetsImpl.AsyncMergeAssetTo(), rail.IRailUserSpaceHelperImpl.AsyncModifyFavoritesWorks(), rail.IRailStorageHelperImpl.AsyncPublishFileToUserSpace(), rail.IRailInGamePurchaseImpl.AsyncPurchaseProducts(), rail.IRailInGamePurchaseImpl.AsyncPurchaseProductsToAssets(), rail.IRailFriendsImpl.AsyncQueryFriendPlayedGamesInfo(), rail.IRailDlcHelperImpl.AsyncQueryIsOwnedDlcsOnServer(), rail.IRailFriendsImpl.AsyncQueryPlayedWithFriendsGames(), rail.IRailFriendsImpl.AsyncQueryPlayedWithFriendsTime(), rail.IRailUserSpaceHelperImpl.AsyncQuerySpaceWorks(), rail.IRailUserSpaceHelperImpl.AsyncQuerySpaceWorks(), rail.IRailUserSpaceHelperImpl.AsyncQuerySpaceWorks(), rail.IRailUserSpaceHelperImpl.AsyncQuerySpaceWorks(), rail.IRailAppsImpl.AsyncQuerySubscribeWishPlayState(), rail.IRailDlcHelperImpl.AsyncRemoveDlc(), rail.IRailGameServerHelperImpl.AsyncRemoveFavoriteGameServer(), rail.IRailGameServerHelperImpl.AsyncRemoveFavoriteGameServer(), rail.IRailUserSpaceHelperImpl.AsyncRemoveSpaceWork(), rail.IRailVoiceChannelImpl.AsyncRemoveUsers(), rail.IRailFriendsImpl.AsyncReportPlayedWithUserList(), rail.IRailLeaderboardEntriesImpl.AsyncRequestLeaderboardEntries(), rail.IRailUserSpaceHelperImpl.AsyncSearchSpaceWork(), rail.IRailRoomImpl.AsyncSetMemberMetadata(), rail.IRailGameServerImpl.AsyncSetMetadata(), rail.IRailFriendsImpl.AsyncSetMyMetadata(), rail.IRailRoomImpl.AsyncSetRoomMetadata(), rail.IRailVoiceChannelImpl.AsyncSetUsersSpeakingState(), rail.IRailUsersHelperImpl.AsyncShowChatWindowWithFriend(), rail.IRailFloatingWindowImpl.AsyncShowStoreWindow(), rail.IRailUsersHelperImpl.AsyncShowUserHomepageWindow(), rail.IRailGameServerImpl.AsyncStartSessionWithPlayer(), rail.IRailPlayerImpl.AsyncStartSessionWithPlayer(), rail.IRailUserSpaceHelperImpl.AsyncSubscribeSpaceWorks(), rail.IRailZoneServerHelperImpl.AsyncSwitchPlayerSelectedZone(), rail.IRailAssetsImpl.AsyncUpdateAssetsProperty(), rail.IRailLeaderboardImpl.AsyncUploadLeaderboard(), rail.IRailUserSpaceHelperImpl.AsyncVoteSpaceWork(), rail.IRailNetworkImpl.BlockMessageType(), rail.IRailNetworkImpl.CloseSession(), rail.IRailBrowserHelperImpl.CreateCustomerDrawBrowser(), rail.IRailBrowserHelperImpl.CreateCustomerDrawBrowser(), rail.IRailAchievementHelperImpl.CreatePlayerAchievement(), rail.IRailStatisticHelperImpl.CreatePlayerStats(), rail.IRailRoomHelperImpl.CreateRoom(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.RailConverter.Csharp2Cpp(), rail.IRailIMEHelperImpl.EnableIMEHelperTextInputWindow(), rail.IRailRoomImpl.GetMemberMetadata(), rail.IRailNetworkImpl.GetSessionState(), rail.IRailDlcHelperImpl.IsDlcInstalled(), rail.IRailDlcHelperImpl.IsDlcInstalled(), rail.IRailAppsImpl.IsGameInstalled(), rail.IRailDlcHelperImpl.IsOwnedDlc(), rail.IRailGameServerImpl.IsUserInGameServer(), rail.IRailRoomImpl.IsUserInRoom(), rail.IRailUserSpaceHelperImpl.OpenSpaceWork(), rail.IRailStorageHelperImpl.OpenStreamFile(), rail.IRailStorageHelperImpl.OpenStreamFile(), rail.IRailVoiceHelperImpl.OpenVoiceChannel(), rail.IRailZoneServerHelperImpl.OpenZoneServer(), rail.rail_api.RailNeedRestartAppForCheckingEnvironment(), rail.IRailNetworkImpl.ReadData(), rail.IRailNetworkImpl.ReadData(), rail.IRailGameImpl.RegisterGameDefineGamePlayingState(), rail.IRailSpaceWorkImpl.RemoveAssociatedGameIDs(), rail.IRailGameServerImpl.ReportPlayerJoinGameServer(), rail.IRailGameServerImpl.ReportPlayerQuitGameServer(), rail.IRailNetworkImpl.SendData(), rail.IRailNetworkImpl.SendData(), rail.IRailRoomImpl.SendDataToMember(), rail.IRailRoomImpl.SendDataToMember(), rail.IRailNetworkImpl.SendReliableData(), rail.IRailNetworkImpl.SendReliableData(), rail.IRailSpaceWorkImpl.SetAdditionalPreviews(), rail.IRailSpaceWorkImpl.SetAssociatedSpaceWorks(), rail.IRailSpaceWorkImpl.SetLanguages(), rail.IRailRoomImpl.SetMemberMetadata(), rail.IRailGameServerImpl.SetMods(), rail.IRailRoomImpl.SetNewOwner(), rail.IRailFloatingWindowImpl.SetNotifyWindowPosition(), rail.IRailHttpSessionImpl.SetParameters(), rail.IRailHttpSessionImpl.SetRequestHeaders(), rail.IRailStorageHelperImpl.SetSyncFileOption(), rail.IRailSpaceWorkImpl.SetTags(), rail.IRailSpaceWorkImpl.SetUpdateOptions(), rail.IRailVoiceHelperImpl.SetupVoiceCapture(), rail.IRailVoiceHelperImpl.SetupVoiceCapture(), rail.IRailScreenshotImpl.SetUsers(), rail.IRailTextInputHelperImpl.ShowTextInputWindow(), rail.IRailGameServerImpl.TerminateSessionOfPlayer(), rail.IRailPlayerImpl.TerminateSessionOfPlayer(), rail.IRailNetworkImpl.UnblockMessageType(), rail.IRailGameServerImpl.UpdateGameServerPlayerList(), and rail.IRailIMEHelperImpl.UpdateIMEHelperTextInputWindowPosition().