Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [13/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, AsyncReadStreamFileResult ret) inline static
Definition at line 202 of file RailConverter.cs.
        {
            RailConverter.Cpp2Csharp(ptr, ret);
            ret.try_read_length = RAIL_API_PINVOKE.AsyncReadStreamFileResult_try_read_length_get(ptr);
            ret.offset = RAIL_API_PINVOKE.AsyncReadStreamFileResult_offset_get(ptr);
            ret.data = RAIL_API_PINVOKE.AsyncReadStreamFileResult_data_get(ptr);
            ret.filename = RAIL_API_PINVOKE.AsyncReadStreamFileResult_filename_get(ptr);
        }
References rail.RAIL_API_PINVOKE.AsyncReadStreamFileResult_data_get(), rail.RAIL_API_PINVOKE.AsyncReadStreamFileResult_filename_get(), rail.RAIL_API_PINVOKE.AsyncReadStreamFileResult_offset_get(), rail.RAIL_API_PINVOKE.AsyncReadStreamFileResult_try_read_length_get(), and rail.RailConverter.Cpp2Csharp().