Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [156/282]
static void rail.RailConverter.Csharp2Cpp (RailDlcInfo data, IntPtr ptr) inline static
Definition at line 1904 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailDlcInfo_original_price_set(ptr, data.original_price);
            RailConverter.Csharp2Cpp(data.dlc_id, RAIL_API_PINVOKE.RailDlcInfo_dlc_id_get(ptr));
            RAIL_API_PINVOKE.RailDlcInfo_description_set(ptr, data.description);
            RAIL_API_PINVOKE.RailDlcInfo_discount_price_set(ptr, data.discount_price);
            RAIL_API_PINVOKE.RailDlcInfo_version_set(ptr, data.version);
            RailConverter.Csharp2Cpp(data.game_id, RAIL_API_PINVOKE.RailDlcInfo_game_id_get(ptr));
            RAIL_API_PINVOKE.RailDlcInfo_name_set(ptr, data.name);
        }
References rail.RailConverter.Csharp2Cpp(), rail.RailDlcInfo.description, rail.RailDlcInfo.discount_price, rail.RailDlcInfo.dlc_id, rail.RailDlcInfo.game_id, rail.RailDlcInfo.name, rail.RailDlcInfo.original_price, rail.RAIL_API_PINVOKE.RailDlcInfo_description_set(), rail.RAIL_API_PINVOKE.RailDlcInfo_discount_price_set(), rail.RAIL_API_PINVOKE.RailDlcInfo_dlc_id_get(), rail.RAIL_API_PINVOKE.RailDlcInfo_game_id_get(), rail.RAIL_API_PINVOKE.RailDlcInfo_name_set(), rail.RAIL_API_PINVOKE.RailDlcInfo_original_price_set(), rail.RAIL_API_PINVOKE.RailDlcInfo_version_set(), and rail.RailDlcInfo.version.