Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [205/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailQueryWorkFileOptions ret) inline static
Definition at line 2662 of file RailConverter.cs.
        {
            ret.with_url = RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_url_get(ptr);
            ret.with_uploader_ids = RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_uploader_ids_get(ptr);
            ret.with_vote_detail = RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_vote_detail_get(ptr);
            ret.with_preview_url = RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_preview_url_get(ptr);
            ret.with_description = RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_description_get(ptr);
            ret.query_total_only = RAIL_API_PINVOKE.RailQueryWorkFileOptions_query_total_only_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RailQueryWorkFileOptions_query_total_only_get(), rail.RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_description_get(), rail.RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_preview_url_get(), rail.RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_uploader_ids_get(), rail.RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_url_get(), and rail.RAIL_API_PINVOKE.RailQueryWorkFileOptions_with_vote_detail_get().