Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [123/282]
static void rail.RailConverter.Csharp2Cpp (List< string > ret, IntPtr ptr) inline static
Definition at line 4618 of file RailConverter.cs.
        {
            int count = ret.Count;
            RAIL_API_PINVOKE.RailArrayRailString_clear(ptr);
            for (int i = 0; i < count; i++)
            {
                IntPtr intPtr = RAIL_API_PINVOKE.new_RailString__SWIG_0();
                RAIL_API_PINVOKE.RailString_SetValue(intPtr, ret[i]);
                RAIL_API_PINVOKE.RailArrayRailString_push_back(ptr, intPtr);
                RAIL_API_PINVOKE.delete_RailString(intPtr);
            }
        }
References System.Collections.Generic.List< T >.Count, System.count, rail.RAIL_API_PINVOKE.delete_RailString(), rail.RAIL_API_PINVOKE.new_RailString__SWIG_0(), rail.RAIL_API_PINVOKE.RailArrayRailString_clear(), rail.RAIL_API_PINVOKE.RailArrayRailString_push_back(), and rail.RAIL_API_PINVOKE.RailString_SetValue().