Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [248/282]
static void rail.RailConverter.Csharp2Cpp (RoomInfo data, IntPtr ptr) inline static
Definition at line 3358 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RoomInfo_zone_id_set(ptr, data.zone_id);
            RAIL_API_PINVOKE.RoomInfo_has_password_set(ptr, data.has_password);
            RAIL_API_PINVOKE.RoomInfo_create_time_set(ptr, data.create_time);
            RAIL_API_PINVOKE.RoomInfo_max_members_set(ptr, data.max_members);
            RAIL_API_PINVOKE.RoomInfo_room_name_set(ptr, data.room_name);
            RAIL_API_PINVOKE.RoomInfo_game_server_rail_id_set(ptr, data.game_server_rail_id);
            RAIL_API_PINVOKE.RoomInfo_room_id_set(ptr, data.room_id);
            RAIL_API_PINVOKE.RoomInfo_current_members_set(ptr, data.current_members);
            RAIL_API_PINVOKE.RoomInfo_is_joinable_set(ptr, data.is_joinable);
            RAIL_API_PINVOKE.RoomInfo_room_state_set(ptr, (int)data.room_state);
            RailConverter.Csharp2Cpp(data.room_kvs, RAIL_API_PINVOKE.RoomInfo_room_kvs_get(ptr));
            RAIL_API_PINVOKE.RoomInfo_type_set(ptr, (int)data.type);
            RailConverter.Csharp2Cpp(data.owner_id, RAIL_API_PINVOKE.RoomInfo_owner_id_get(ptr));
        }
References rail.RoomInfo.create_time, rail.RailConverter.Csharp2Cpp(), rail.RoomInfo.current_members, rail.RoomInfo.game_server_rail_id, rail.RoomInfo.has_password, rail.RoomInfo.is_joinable, rail.RoomInfo.max_members, rail.RoomInfo.owner_id, rail.RoomInfo.room_id, rail.RoomInfo.room_kvs, rail.RoomInfo.room_name, rail.RoomInfo.room_state, rail.RAIL_API_PINVOKE.RoomInfo_create_time_set(), rail.RAIL_API_PINVOKE.RoomInfo_current_members_set(), rail.RAIL_API_PINVOKE.RoomInfo_game_server_rail_id_set(), rail.RAIL_API_PINVOKE.RoomInfo_has_password_set(), rail.RAIL_API_PINVOKE.RoomInfo_is_joinable_set(), rail.RAIL_API_PINVOKE.RoomInfo_max_members_set(), rail.RAIL_API_PINVOKE.RoomInfo_owner_id_get(), rail.RAIL_API_PINVOKE.RoomInfo_room_id_set(), rail.RAIL_API_PINVOKE.RoomInfo_room_kvs_get(), rail.RAIL_API_PINVOKE.RoomInfo_room_name_set(), rail.RAIL_API_PINVOKE.RoomInfo_room_state_set(), rail.RAIL_API_PINVOKE.RoomInfo_type_set(), rail.RAIL_API_PINVOKE.RoomInfo_zone_id_set(), rail.RoomInfo.type, and rail.RoomInfo.zone_id.