Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [273/282]
static void rail.RailConverter.Csharp2Cpp (VoiceChannelAddUsersResult data, IntPtr ptr) inline static
Definition at line 3769 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data, ptr);
            RailConverter.Csharp2Cpp(data.success_ids, RAIL_API_PINVOKE.VoiceChannelAddUsersResult_success_ids_get(ptr));
            RailConverter.Csharp2Cpp(data.voice_channel_id, RAIL_API_PINVOKE.VoiceChannelAddUsersResult_voice_channel_id_get(ptr));
            RailConverter.Csharp2Cpp(data.failed_ids, RAIL_API_PINVOKE.VoiceChannelAddUsersResult_failed_ids_get(ptr));
        }
References rail.RailConverter.Csharp2Cpp(), rail.VoiceChannelAddUsersResult.failed_ids, rail.VoiceChannelAddUsersResult.success_ids, rail.VoiceChannelAddUsersResult.voice_channel_id, rail.RAIL_API_PINVOKE.VoiceChannelAddUsersResult_failed_ids_get(), rail.RAIL_API_PINVOKE.VoiceChannelAddUsersResult_success_ids_get(), and rail.RAIL_API_PINVOKE.VoiceChannelAddUsersResult_voice_channel_id_get().