Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [248/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RoomInfo ret) inline static
Definition at line 3340 of file RailConverter.cs.
        {
            ret.zone_id = RAIL_API_PINVOKE.RoomInfo_zone_id_get(ptr);
            ret.has_password = RAIL_API_PINVOKE.RoomInfo_has_password_get(ptr);
            ret.create_time = RAIL_API_PINVOKE.RoomInfo_create_time_get(ptr);
            ret.max_members = RAIL_API_PINVOKE.RoomInfo_max_members_get(ptr);
            ret.room_name = RAIL_API_PINVOKE.RoomInfo_room_name_get(ptr);
            ret.game_server_rail_id = RAIL_API_PINVOKE.RoomInfo_game_server_rail_id_get(ptr);
            ret.room_id = RAIL_API_PINVOKE.RoomInfo_room_id_get(ptr);
            ret.current_members = RAIL_API_PINVOKE.RoomInfo_current_members_get(ptr);
            ret.is_joinable = RAIL_API_PINVOKE.RoomInfo_is_joinable_get(ptr);
            ret.room_state = (EnumRoomStatus)RAIL_API_PINVOKE.RoomInfo_room_state_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RoomInfo_room_kvs_get(ptr), ret.room_kvs);
            ret.type = (EnumRoomType)RAIL_API_PINVOKE.RoomInfo_type_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RoomInfo_owner_id_get(ptr), ret.owner_id);
        }
References rail.RailConverter.Cpp2Csharp(), rail.RoomInfo.owner_id, rail.RoomInfo.room_kvs, rail.RAIL_API_PINVOKE.RoomInfo_create_time_get(), rail.RAIL_API_PINVOKE.RoomInfo_current_members_get(), rail.RAIL_API_PINVOKE.RoomInfo_game_server_rail_id_get(), rail.RAIL_API_PINVOKE.RoomInfo_has_password_get(), rail.RAIL_API_PINVOKE.RoomInfo_is_joinable_get(), rail.RAIL_API_PINVOKE.RoomInfo_max_members_get(), rail.RAIL_API_PINVOKE.RoomInfo_owner_id_get(), rail.RAIL_API_PINVOKE.RoomInfo_room_id_get(), rail.RAIL_API_PINVOKE.RoomInfo_room_kvs_get(), rail.RAIL_API_PINVOKE.RoomInfo_room_name_get(), rail.RAIL_API_PINVOKE.RoomInfo_room_state_get(), rail.RAIL_API_PINVOKE.RoomInfo_type_get(), and rail.RAIL_API_PINVOKE.RoomInfo_zone_id_get().