Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [181/282]
static void rail.RailConverter.Csharp2Cpp (RailImageDataDescriptor data, IntPtr ptr) inline static
Definition at line 2272 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailImageDataDescriptor_pixel_format_set(ptr, (int)data.pixel_format);
            RAIL_API_PINVOKE.RailImageDataDescriptor_image_height_set(ptr, data.image_height);
            RAIL_API_PINVOKE.RailImageDataDescriptor_stride_in_bytes_set(ptr, data.stride_in_bytes);
            RAIL_API_PINVOKE.RailImageDataDescriptor_image_width_set(ptr, data.image_width);
            RAIL_API_PINVOKE.RailImageDataDescriptor_bits_per_pixel_set(ptr, data.bits_per_pixel);
        }
References rail.RailImageDataDescriptor.bits_per_pixel, rail.RailImageDataDescriptor.image_height, rail.RailImageDataDescriptor.image_width, rail.RailImageDataDescriptor.pixel_format, rail.RAIL_API_PINVOKE.RailImageDataDescriptor_bits_per_pixel_set(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_image_height_set(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_image_width_set(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_pixel_format_set(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_stride_in_bytes_set(), and rail.RailImageDataDescriptor.stride_in_bytes.