Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [202/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailPublishFileToUserSpaceOption ret) inline static
Definition at line 2592 of file RailConverter.cs.
        {
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_key_value_get(ptr), ret.key_value);
            ret.description = RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_description_get(ptr);
            RailConverter.Cpp2Csharp(RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_tags_get(ptr), ret.tags);
            ret.level = (EnumRailSpaceWorkShareLevel)RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_level_get(ptr);
            ret.version = RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_version_get(ptr);
            ret.preview_path_filename = RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_preview_path_filename_get(ptr);
            ret.type = (EnumRailSpaceWorkType)RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_type_get(ptr);
            ret.space_work_name = RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_space_work_name_get(ptr);
        }
References rail.RailConverter.Cpp2Csharp(), rail.RailPublishFileToUserSpaceOption.key_value, rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_description_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_key_value_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_level_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_preview_path_filename_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_space_work_name_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_tags_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_type_get(), rail.RAIL_API_PINVOKE.RailPublishFileToUserSpaceOption_version_get(), and rail.RailPublishFileToUserSpaceOption.tags.