Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [181/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, RailImageDataDescriptor ret) inline static
Definition at line 2262 of file RailConverter.cs.
        {
            ret.pixel_format = (EnumRailImagePixelFormat)RAIL_API_PINVOKE.RailImageDataDescriptor_pixel_format_get(ptr);
            ret.image_height = RAIL_API_PINVOKE.RailImageDataDescriptor_image_height_get(ptr);
            ret.stride_in_bytes = RAIL_API_PINVOKE.RailImageDataDescriptor_stride_in_bytes_get(ptr);
            ret.image_width = RAIL_API_PINVOKE.RailImageDataDescriptor_image_width_get(ptr);
            ret.bits_per_pixel = RAIL_API_PINVOKE.RailImageDataDescriptor_bits_per_pixel_get(ptr);
        }
References rail.RAIL_API_PINVOKE.RailImageDataDescriptor_bits_per_pixel_get(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_image_height_get(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_image_width_get(), rail.RAIL_API_PINVOKE.RailImageDataDescriptor_pixel_format_get(), and rail.RAIL_API_PINVOKE.RailImageDataDescriptor_stride_in_bytes_get().