Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [126/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, MemberInfo ret) inline static
Definition at line 1406 of file RailConverter.cs.
        {
            ret.member_name = RAIL_API_PINVOKE.MemberInfo_member_name_get(ptr);
            ret.member_index = RAIL_API_PINVOKE.MemberInfo_member_index_get(ptr);
            ret.room_id = RAIL_API_PINVOKE.MemberInfo_room_id_get(ptr);
            ret.member_id = RAIL_API_PINVOKE.MemberInfo_member_id_get(ptr);
        }
References rail.RAIL_API_PINVOKE.MemberInfo_member_id_get(), rail.RAIL_API_PINVOKE.MemberInfo_member_index_get(), rail.RAIL_API_PINVOKE.MemberInfo_member_name_get(), and rail.RAIL_API_PINVOKE.MemberInfo_room_id_get().