Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [254/282]
static void rail.RailConverter.Csharp2Cpp (RoomOptions data, IntPtr ptr) inline static
Definition at line 3482 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RoomOptions_max_members_set(ptr, data.max_members);
            RAIL_API_PINVOKE.RoomOptions_password_set(ptr, data.password);
            RAIL_API_PINVOKE.RoomOptions_type_set(ptr, (int)data.type);
            RAIL_API_PINVOKE.RoomOptions_zone_id_set(ptr, data.zone_id);
            RAIL_API_PINVOKE.RoomOptions_enable_team_voice_set(ptr, data.enable_team_voice);
        }
References rail.RoomOptions.enable_team_voice, rail.RoomOptions.max_members, rail.RoomOptions.password, rail.RAIL_API_PINVOKE.RoomOptions_enable_team_voice_set(), rail.RAIL_API_PINVOKE.RoomOptions_max_members_set(), rail.RAIL_API_PINVOKE.RoomOptions_password_set(), rail.RAIL_API_PINVOKE.RoomOptions_type_set(), rail.RAIL_API_PINVOKE.RoomOptions_zone_id_set(), rail.RoomOptions.type, and rail.RoomOptions.zone_id.