Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [271/282]
static void rail.RailConverter.Csharp2Cpp (UploadLeaderboardParam data, IntPtr ptr) inline static
Definition at line 3739 of file RailConverter.cs.
        {
            RailConverter.Csharp2Cpp(data.data, RAIL_API_PINVOKE.UploadLeaderboardParam_data_get(ptr));
            RAIL_API_PINVOKE.UploadLeaderboardParam_type_set(ptr, (int)data.type);
        }
References rail.RailConverter.Csharp2Cpp(), rail.UploadLeaderboardParam.data, rail.UploadLeaderboardParam.type, rail.RAIL_API_PINVOKE.UploadLeaderboardParam_data_get(), and rail.RAIL_API_PINVOKE.UploadLeaderboardParam_type_set().