Terraria Decompiled: rail.RailConverter.Csharp2Cpp
Csharp2Cpp() [226/282]
static void rail.RailConverter.Csharp2Cpp (RailTextInputWindowOption data, IntPtr ptr) inline static
Definition at line 3010 of file RailConverter.cs.
        {
            RAIL_API_PINVOKE.RailTextInputWindowOption_enable_multi_line_edit_set(ptr, data.enable_multi_line_edit);
            RAIL_API_PINVOKE.RailTextInputWindowOption_description_set(ptr, data.description);
            RAIL_API_PINVOKE.RailTextInputWindowOption_position_top_set(ptr, data.position_top);
            RAIL_API_PINVOKE.RailTextInputWindowOption_position_left_set(ptr, data.position_left);
            RAIL_API_PINVOKE.RailTextInputWindowOption_caption_text_set(ptr, data.caption_text);
            RAIL_API_PINVOKE.RailTextInputWindowOption_show_password_input_set(ptr, data.show_password_input);
            RAIL_API_PINVOKE.RailTextInputWindowOption_is_min_window_set(ptr, data.is_min_window);
            RAIL_API_PINVOKE.RailTextInputWindowOption_content_placeholder_set(ptr, data.content_placeholder);
            RAIL_API_PINVOKE.RailTextInputWindowOption_auto_cancel_set(ptr, data.auto_cancel);
        }
References rail.RailTextInputWindowOption.auto_cancel, rail.RailTextInputWindowOption.caption_text, rail.RailTextInputWindowOption.content_placeholder, rail.RailTextInputWindowOption.description, rail.RailTextInputWindowOption.enable_multi_line_edit, rail.RailTextInputWindowOption.is_min_window, rail.RailTextInputWindowOption.position_left, rail.RailTextInputWindowOption.position_top, rail.RAIL_API_PINVOKE.RailTextInputWindowOption_auto_cancel_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_caption_text_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_content_placeholder_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_description_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_enable_multi_line_edit_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_is_min_window_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_position_left_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_position_top_set(), rail.RAIL_API_PINVOKE.RailTextInputWindowOption_show_password_input_set(), and rail.RailTextInputWindowOption.show_password_input.