Terraria Decompiled: rail.RailConverter.Cpp2Csharp
Cpp2Csharp() [36/282]
static void rail.RailConverter.Cpp2Csharp (IntPtr ptr, CreateCustomerDrawBrowserOptions ret) inline static
Definition at line 594 of file RailConverter.cs.
        {
            ret.content_offset_x = RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_offset_x_get(ptr);
            ret.content_offset_y = RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_offset_y_get(ptr);
            ret.content_window_height = RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_window_height_get(ptr);
            ret.has_scroll = RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_has_scroll_get(ptr);
            ret.content_window_width = RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_window_width_get(ptr);
        }
References rail.RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_offset_x_get(), rail.RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_offset_y_get(), rail.RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_window_height_get(), rail.RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_content_window_width_get(), and rail.RAIL_API_PINVOKE.CreateCustomerDrawBrowserOptions_has_scroll_get().