Terraria Decompiled: System.Buffers.Text.Number.NumberToDouble
NumberToDouble()
static unsafe double System.Buffers.Text.Number.NumberToDouble (ref NumberBuffer number) inline static private
Definition at line 172 of file Number.cs.
        {
            ReadOnlySpan<byte> readOnlySpan = number.Digits;
            int num = 0;
            int numDigits = number.NumDigits;
            int num2 = numDigits;
            while (*readOnlySpan[num] == 48)
            {
                num2--;
                num++;
            }
            if (num2 == 0)
            {
                return 0.0;
            }
            int num3 = Math.Min(num2, 9);
            num2 -= num3;
            ulong num4 = (ulong)Number.DigitsToInt(readOnlySpan, num3);
            if (num2 > 0)
            {
                num3 = Math.Min(num2, 9);
                num2 -= num3;
                uint num5 = (uint)(Number.s_rgval64Power10[num3 - 1] >> (int)(64 - Number.s_rgexp64Power10[num3 - 1]));
                num4 = Number.Mul32x32To64((uint)num4, num5) + (ulong)Number.DigitsToInt(readOnlySpan.Slice(9), num3);
            }
            int num6 = number.Scale - (numDigits - num2);
            int num7 = Number.abs(num6);
            if (num7 >= 352)
            {
                ulong num8 = ((num6 > 0) ? 9218868437227405312UL : 0UL);
                if (number.IsNegative)
                {
                    num8 |= 9223372036854775808UL;
                }
                return *(double*)(&num8);
            }
            int num9 = 64;
            if ((num4 & 18446744069414584320UL) == 0UL)
            {
                num4 <<= 32;
                num9 -= 32;
            }
            if ((num4 & 18446462598732840960UL) == 0UL)
            {
                num4 <<= 16;
                num9 -= 16;
            }
            if ((num4 & 18374686479671623680UL) == 0UL)
            {
                num4 <<= 8;
                num9 -= 8;
            }
            if ((num4 & 17293822569102704640UL) == 0UL)
            {
                num4 <<= 4;
                num9 -= 4;
            }
            if ((num4 & 13835058055282163712UL) == 0UL)
            {
                num4 <<= 2;
                num9 -= 2;
            }
            if ((num4 & 9223372036854775808UL) == 0UL)
            {
                num4 <<= 1;
                num9--;
            }
            int num10 = num7 & 15;
            if (num10 != 0)
            {
                int num11 = (int)Number.s_rgexp64Power10[num10 - 1];
                num9 += ((num6 < 0) ? (-num11 + 1) : num11);
                ulong num12 = Number.s_rgval64Power10[num10 + ((num6 < 0) ? 15 : 0) - 1];
                num4 = Number.Mul64Lossy(num4, num12, ref num9);
            }
            num10 = num7 >> 4;
            if (num10 != 0)
            {
                int num13 = (int)Number.s_rgexp64Power10By16[num10 - 1];
                num9 += ((num6 < 0) ? (-num13 + 1) : num13);
                ulong num14 = Number.s_rgval64Power10By16[num10 + ((num6 < 0) ? 21 : 0) - 1];
                num4 = Number.Mul64Lossy(num4, num14, ref num9);
            }
            if (((int)num4 & 1024) != 0)
            {
                ulong num15 = num4 + 1023UL + (ulong)((long)(((int)num4 >> 11) & 1));
                if (num15 < num4)
                {
                    num15 = (num15 >> 1) | 9223372036854775808UL;
                    num9++;
                }
                num4 = num15;
            }
            num9 += 1022;
            if (num9 <= 0)
            {
                if (num9 == -52 && num4 >= 9223372036854775896UL)
                {
                    num4 = 1UL;
                }
                else if (num9 <= -52)
                {
                    num4 = 0UL;
                }
                else
                {
                    num4 >>= -num9 + 11 + 1;
                }
            }
            else if (num9 >= 2047)
            {
                num4 = 9218868437227405312UL;
            }
            else
            {
                num4 = (ulong)(((long)num9 << 52) + (long)((num4 >> 11) & 4503599627370495UL));
            }
            if (number.IsNegative)
            {
                num4 |= 9223372036854775808UL;
            }
            return *(double*)(&num4);
        }
References System.Buffers.Text.Number.abs(), System.Buffers.Text.Number.DigitsToInt(), int, System.Math.Min(), System.Buffers.Text.Number.Mul32x32To64(), System.Buffers.Text.Number.Mul64Lossy(), System.Buffers.Text.Number.s_rgexp64Power10, System.Buffers.Text.Number.s_rgexp64Power10By16, System.Buffers.Text.Number.s_rgval64Power10, System.Buffers.Text.Number.s_rgval64Power10By16, and System.ReadOnlySpan< T >.Slice().
Referenced by System.Buffers.Text.Number.NumberBufferToDouble().