Terraria Decompiled: System.Buffers.Text.Number.NumberBufferToDecimal
NumberBufferToDecimal()
static unsafe bool System.Buffers.Text.Number.NumberBufferToDecimal (ref NumberBuffer number, ref decimal value) inline static
Definition at line 27 of file Number.cs.
        {
            MutableDecimal mutableDecimal = default(MutableDecimal);
            byte* ptr = number.UnsafeDigits;
            int num = number.Scale;
            if (*ptr == 0)
            {
                if (num > 0)
                {
                    num = 0;
                }
            }
            else
            {
                if (num > 29)
                {
                    return false;
                }
                while ((num > 0 || (*ptr != 0 && num > -28)) && (mutableDecimal.High < 429496729U || (mutableDecimal.High == 429496729U && (mutableDecimal.Mid < 2576980377U || (mutableDecimal.Mid == 2576980377U && (mutableDecimal.Low < 2576980377U || (mutableDecimal.Low == 2576980377U && *ptr <= 53)))))))
                {
                    DecimalDecCalc.DecMul10(ref mutableDecimal);
                    if (*ptr != 0)
                    {
                        DecimalDecCalc.DecAddInt32(ref mutableDecimal, (uint)(*(ptr++) - 48));
                    }
                    num--;
                }
                if (*(ptr++) >= 53)
                {
                    bool flag = true;
                    if (*(ptr - 1) == 53 && *(ptr - 2) % 2 == 0)
                    {
                        int num2 = 20;
                        while (*ptr == 48 && num2 != 0)
{
                            ptr++;
                            num2--;
                        }
                        if (*ptr == 0 || num2 == 0)
{
                            flag = false;
                        }
                    }
                    if (flag)
                    {
                        DecimalDecCalc.DecAddInt32(ref mutableDecimal, 1U);
                        if ((mutableDecimal.High | mutableDecimal.Mid | mutableDecimal.Low) == 0U)
{
                            mutableDecimal.High = 429496729U;
                            mutableDecimal.Mid = 2576980377U;
                            mutableDecimal.Low = 2576980378U;
                            num++;
                        }
                    }
                }
            }
            if (num > 0)
            {
                return false;
            }
            if (num <= -29)
            {
                mutableDecimal.High = 0U;
                mutableDecimal.Low = 0U;
                mutableDecimal.Mid = 0U;
                mutableDecimal.Scale = 28;
            }
            else
            {
                mutableDecimal.Scale = -num;
            }
            mutableDecimal.IsNegative = number.IsNegative;
            value = *Unsafe.As<MutableDecimal, decimal>(ref mutableDecimal);
            return true;
        }
References System.DecimalDecCalc.DecAddInt32(), System.DecimalDecCalc.DecMul10(), System.MutableDecimal.High, System.MutableDecimal.Low, System.MutableDecimal.Mid, System.MutableDecimal.Scale, System.U, and System.value.
Referenced by System.Buffers.Text.Utf8Parser.TryParse().