Terraria Decompiled: System.Runtime.Remoting.Lifetime.ClientSponsor.Register
Register()
bool System.Runtime.Remoting.Lifetime.ClientSponsor.Register (MarshalByRefObject obj) inline
Definition at line 61 of file ClientSponsor.cs.
        {
            if (this.registered_objects.ContainsKey(obj))
            {
                return false;
            }
            ILease lease = obj.GetLifetimeService() as ILease;
            if (lease == null)
            {
                return false;
            }
            lease.Register(this);
            this.registered_objects.Add(obj, obj);
            return true;
        }
References System.Collections.Hashtable.Add(), System.Collections.Hashtable.ContainsKey(), System.obj, System.Runtime.Remoting.Lifetime.ILease.Register(), and System.Runtime.Remoting.Lifetime.ClientSponsor.registered_objects.