Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.OnPacketRead
OnPacketRead()
bool Terraria.Social.WeGame.NetClientSocialModule.OnPacketRead (byte[] data, int size, RailID user) inline private
Definition at line 115 of file NetClientSocialModule.cs.
        {
            if (!this._connectionStateMap.ContainsKey(user))
            {
                return false;
            }
            NetSocialModule.ConnectionState connectionState = this._connectionStateMap[user];
            if (connectionState == NetSocialModule.ConnectionState.Authenticating)
            {
                if (!this.TryAuthUserByRecvData(user, data, size))
                {
                    WeGameHelper.WriteDebugString(" Auth Server Ticket Failed", new object[0]);
                    this.Close(user);
                }
                else
                {
                    WeGameHelper.WriteDebugString("OnRailAuthSessionTicket Auth Success..", new object[0]);
                    this.OnAuthSuccess(user);
                }
                return false;
            }
            return connectionState == NetSocialModule.ConnectionState.Connected;
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetClientSocialModule.Close(), Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess(), Terraria.Social.WeGame.NetClientSocialModule.TryAuthUserByRecvData(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().