Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.Initialize
Initialize()
override void Terraria.Social.WeGame.NetClientSocialModule.Initialize () inline
Definition at line 62 of file NetClientSocialModule.cs.
        {
            base.Initialize();
            this.RegisterRailEvent();
            this.AsyncGetFriendsInfo();
            this._reader.SetReadEvent(new WeGameP2PReader.OnReadEvent(this.OnPacketRead));
            this._reader.SetLocalPeer(base.GetLocalPeer());
            this._writer.SetLocalPeer(base.GetLocalPeer());
            Main.OnEngineLoad += this.CheckParameters;
        }
References Terraria.Social.WeGame.NetSocialModule._reader, Terraria.Social.WeGame.NetSocialModule._writer, Terraria.Social.WeGame.NetClientSocialModule.AsyncGetFriendsInfo(), Terraria.Social.WeGame.NetClientSocialModule.CheckParameters(), Terraria.Social.WeGame.WeGameP2PReader.OnReadEvent(), Terraria.Social.WeGame.NetClientSocialModule.RegisterRailEvent(), Terraria.Social.WeGame.WeGameP2PReader.SetLocalPeer(), Terraria.Social.WeGame.WeGameP2PWriter.SetLocalPeer(), and Terraria.Social.WeGame.WeGameP2PReader.SetReadEvent().