Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.ClearSeed
ClearSeed()
void Terraria.GameContent.UI.States.UIWorldCreation.ClearSeed () inline
Definition at line 464 of file UIWorldCreation.cs.
        {
            this._optionSeed = string.Empty;
            this._isSpecialSeedText = false;
            this._secretSeedTextsEntered.Clear();
            this._disabledSecretSeedTextsEntered.Clear();
            WorldGenerationOptions.Reset();
            WorldGen.SecretSeed.ClearAllSeeds();
            this.PreparePreviouslyUnlockedSecretSeeds();
            this.UpdateInputFields();
        }
References Terraria.GameContent.UI.States.UIWorldCreation._disabledSecretSeedTextsEntered, Terraria.GameContent.UI.States.UIWorldCreation._secretSeedTextsEntered, System.Collections.Generic.List< T >.Clear(), Terraria.WorldGen.SecretSeed.ClearAllSeeds(), Terraria.GameContent.UI.States.UIWorldCreation.PreparePreviouslyUnlockedSecretSeeds(), Terraria.WorldBuilding.WorldGenerationOptions.Reset(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions().