Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.RegisterRailEvent
RegisterRailEvent()
void Terraria.Social.WeGame.NetClientSocialModule.RegisterRailEvent () inline private
Definition at line 315 of file NetClientSocialModule.cs.
        {
            foreach (RAILEventID raileventID in new RAILEventID[] { 16001, 16002, 13503, 13501, 12003, 12002, 12010 })
            {
                this._callbackHelper.RegisterCallback(raileventID, new RailEventCallBackHandler(this.OnRailEvent));
            }
        }
References Terraria.Social.WeGame.NetClientSocialModule._callbackHelper, Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent(), RailEventCallBackHandler(), and rail.RailCallBackHelper.RegisterCallback().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.Initialize().