Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.AsyncGetServerIDByOwener
AsyncGetServerIDByOwener()
void Terraria.Social.WeGame.NetClientSocialModule.AsyncGetServerIDByOwener (RailID ownerID) inline private
Definition at line 572 of file NetClientSocialModule.cs.
        {
            List<string> list = new List<string>();
            list.Add(this._serverIDMedataKey);
            IRailFriends railFriends = rail_api.RailFactory().RailFriends();
            if (railFriends != null)
            {
                railFriends.AsyncGetFriendMetadata(ownerID, list, "");
            }
        }
References Terraria.Social.WeGame.NetClientSocialModule._serverIDMedataKey, rail.IRailFriends.AsyncGetFriendMetadata(), System.list, rail.rail_api.RailFactory(), and rail.IRailFactory.RailFriends().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnRailRespondInvation().