Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.OnGetFriendMetaData
OnGetFriendMetaData()
void Terraria.Social.WeGame.NetClientSocialModule.OnGetFriendMetaData (RailFriendsGetMetadataResult data) inline private
Definition at line 443 of file NetClientSocialModule.cs.
        {
            if (data.result == null && data.friend_kvs.Count > 0)
            {
                WeGameHelper.WriteDebugString("OnGetFriendMetaData - " + this.DumpMataDataString(data.friend_kvs), new object[0]);
                string valueByKey = this.GetValueByKey(this._serverIDMedataKey, data.friend_kvs);
                if (valueByKey != null)
                {
                    if (valueByKey.Length > 0)
                    {
                        RailID railID = new RailID();
                        railID.id_ = ulong.Parse(valueByKey);
                        if (railID.IsValid())
{
                            this.JoinServer(railID);
                            return;
                        }
                        WeGameHelper.WriteDebugString("JoinServer failed, invalid server id", new object[0]);
                        return;
                    }
                    else
                    {
                        WeGameHelper.WriteDebugString("can not find server id key", new object[0]);
                    }
                }
            }
        }
References Terraria.Social.WeGame.NetClientSocialModule._serverIDMedataKey, Terraria.Social.WeGame.NetClientSocialModule.DumpMataDataString(), rail.RailFriendsGetMetadataResult.friend_kvs, Terraria.Social.WeGame.NetClientSocialModule.GetValueByKey(), rail.RailComparableID.IsValid(), Terraria.Social.WeGame.NetClientSocialModule.JoinServer(), rail.EventBase.result, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent().