Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.OpenSeedInputMenu
OpenSeedInputMenu()
void Terraria.GameContent.UI.States.UIWorldCreation.OpenSeedInputMenu () inline
Definition at line 667 of file UIWorldCreation.cs.
        {
            SoundEngine.PlaySound(10, -1, -1, 1, 1f, 0f);
            Main.clrInput();
            UIVirtualKeyboard uivirtualKeyboard = new UIVirtualKeyboard(Language.GetTextValue("UI.EnterSeed"), "", new UIVirtualKeyboard.KeyboardSubmitEvent(this.OnFinishedSettingSeed), new Action(this.GoBackHere), 0, true, int.MaxValue);
            Main.MenuUI.SetState(uivirtualKeyboard);
        }
References Terraria.Main.clrInput(), Terraria.Localization.Language.GetTextValue(), Terraria.GameContent.UI.States.UIWorldCreation.GoBackHere(), Terraria.GameContent.UI.States.UIVirtualKeyboard.KeyboardSubmitEvent(), Terraria.Main.MenuUI, Terraria.Audio.SoundEngine.PlaySound(), and Terraria.UI.UserInterface.SetState().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.Click_SetSeed(), and Terraria.GameContent.UI.States.UIWorldCreationAdvanced.Click_SetSeed().