Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions
EnableSecretSeedOptions()
void Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions (bool enabled) inline
Definition at line 752 of file UIWorldCreation.cs.
        {
            if (enabled)
            {
                for (int i = 0; i < this._disabledSecretSeedTextsEntered.Count; i++)
                {
                    WorldGen.SecretSeed secretSeed;
                    if (WorldGen.SecretSeed.CheckInputForSecretSeed(this._disabledSecretSeedTextsEntered[i], out secretSeed) && !secretSeed.Enabled)
                    {
                        this._secretSeedTextsEntered.Add(this._disabledSecretSeedTextsEntered[i]);
                        WorldGen.SecretSeed.Enable(secretSeed, false);
                    }
                }
                this._disabledSecretSeedTextsEntered.Clear();
                return;
            }
            this._disabledSecretSeedTextsEntered.Clear();
            this._disabledSecretSeedTextsEntered.AddRange(this._secretSeedTextsEntered);
            WorldGen.SecretSeed.ClearAllSeeds();
            this._secretSeedTextsEntered.Clear();
        }
References Terraria.GameContent.UI.States.UIWorldCreation._disabledSecretSeedTextsEntered, Terraria.GameContent.UI.States.UIWorldCreation._secretSeedTextsEntered, System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.AddRange(), Terraria.WorldGen.SecretSeed.CheckInputForSecretSeed(), System.Collections.Generic.List< T >.Clear(), Terraria.WorldGen.SecretSeed.ClearAllSeeds(), System.Collections.Generic.List< T >.Count, Terraria.WorldGen.SecretSeed.Enable(), and Terraria.WorldGen.SecretSeed.Enabled.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed().