Terraria Decompiled: System.Resources.ResourceSet.GetString
GetString() [2/2]
virtual string System.Resources.ResourceSet.GetString (string name, bool ignoreCase) inline virtual
Reimplemented in System.Resources.RuntimeResourceSet.
Definition at line 142 of file ResourceSet.cs.
        {
            object obj = this.GetObjectInternal(name);
            string text;
            try
            {
                text = (string)obj;
            }
            catch (InvalidCastException)
            {
                throw new InvalidOperationException(Environment.GetResourceString("Resource '{0}' was not a String - call GetObject instead.", new object[] { name }));
            }
            if (text != null || !ignoreCase)
            {
                return text;
            }
            obj = this.GetCaseInsensitiveObjectInternal(name);
            string text2;
            try
            {
                text2 = (string)obj;
            }
            catch (InvalidCastException)
            {
                throw new InvalidOperationException(Environment.GetResourceString("Resource '{0}' was not a String - call GetObject instead.", new object[] { name }));
            }
            return text2;
        }
References System.Resources.ResourceSet.GetCaseInsensitiveObjectInternal(), System.Resources.ResourceSet.GetObjectInternal(), System.Environment.GetResourceString(), System.obj, and System.text.