Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.OnReportServerID
OnReportServerID()
void Terraria.Social.WeGame.NetClientSocialModule.OnReportServerID (ReportServerID reportServerID) inline private
Definition at line 54 of file NetClientSocialModule.cs.
        {
            WeGameHelper.WriteDebugString("OnReportServerID - " + reportServerID._serverID, new object[0]);
            this.AsyncSetMyMetaData(this._serverIDMedataKey, reportServerID._serverID);
            this.AsyncSetInviteCommandLine(reportServerID._serverID);
        }
References Terraria.Social.WeGame.ReportServerID._serverID, Terraria.Social.WeGame.NetClientSocialModule._serverIDMedataKey, Terraria.Social.WeGame.NetClientSocialModule.AsyncSetInviteCommandLine(), Terraria.Social.WeGame.NetClientSocialModule.AsyncSetMyMetaData(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnWegameMessage().