Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.SetupGamepadPoints
SetupGamepadPoints()
void Terraria.GameContent.UI.States.UIWorldCreation.SetupGamepadPoints (SpriteBatch spriteBatch) inline private
Definition at line 1212 of file UIWorldCreation.cs.
        {
            UILinkPointNavigator.Shortcuts.BackButtonCommand = 7;
            int num = 3000;
            List<SnapPoint> snapPoints = this.GetSnapPoints();
            SnapPoint snapPoint = null;
            SnapPoint snapPoint2 = null;
            SnapPoint snapPoint3 = null;
            SnapPoint snapPoint4 = null;
            SnapPoint snapPoint5 = null;
            SnapPoint snapPoint6 = null;
            for (int i = 0; i < snapPoints.Count; i++)
            {
                SnapPoint snapPoint7 = snapPoints[i];
                string name = snapPoint7.Name;
                if (!(name == "Back"))
                {
                    if (!(name == "Create"))
                    {
                        if (!(name == "Name"))
{
                            if (!(name == "Seed"))
{
                                if (!(name == "RandomizeName"))
{
                                    if (name == "RandomizeSeed")
{
                                        snapPoint6 = snapPoint7;
                                    }
                                }
                                else
{
                                    snapPoint5 = snapPoint7;
                                }
                            }
                            else
{
                                snapPoint4 = snapPoint7;
                            }
                        }
                        else
{
                            snapPoint3 = snapPoint7;
                        }
                    }
                    else
                    {
                        snapPoint2 = snapPoint7;
                    }
                }
                else
                {
                    snapPoint = snapPoint7;
                }
            }
            List<SnapPoint> snapGroup = this.GetSnapGroup(snapPoints, "size");
            List<SnapPoint> snapGroup2 = this.GetSnapGroup(snapPoints, "difficulty");
            List<SnapPoint> snapGroup3 = this.GetSnapGroup(snapPoints, "evil");
            UILinkPointNavigator.SetPosition(num, snapPoint.Position);
            UILinkPoint uilinkPoint = UILinkPointNavigator.Points[num];
            uilinkPoint.Unlink();
            UILinkPoint uilinkPoint2 = uilinkPoint;
            num++;
            UILinkPointNavigator.SetPosition(num, snapPoint2.Position);
            uilinkPoint = UILinkPointNavigator.Points[num];
            uilinkPoint.Unlink();
            UILinkPoint uilinkPoint3 = uilinkPoint;
            num++;
            UILinkPointNavigator.SetPosition(num, snapPoint5.Position);
            uilinkPoint = UILinkPointNavigator.Points[num];
            uilinkPoint.Unlink();
            UILinkPoint uilinkPoint4 = uilinkPoint;
            num++;
            UILinkPointNavigator.SetPosition(num, snapPoint3.Position);
            uilinkPoint = UILinkPointNavigator.Points[num];
            uilinkPoint.Unlink();
            UILinkPoint uilinkPoint5 = uilinkPoint;
            num++;
            UILinkPointNavigator.SetPosition(num, snapPoint6.Position);
            uilinkPoint = UILinkPointNavigator.Points[num];
            uilinkPoint.Unlink();
            UILinkPoint uilinkPoint6 = uilinkPoint;
            num++;
            UILinkPointNavigator.SetPosition(num, snapPoint4.Position);
            uilinkPoint = UILinkPointNavigator.Points[num];
            uilinkPoint.Unlink();
            UILinkPoint uilinkPoint7 = uilinkPoint;
            num++;
            UILinkPoint[] array = new UILinkPoint[snapGroup.Count];
            for (int j = 0; j < snapGroup.Count; j++)
            {
                UILinkPointNavigator.SetPosition(num, snapGroup[j].Position);
                uilinkPoint = UILinkPointNavigator.Points[num];
                uilinkPoint.Unlink();
                array[j] = uilinkPoint;
                num++;
            }
            UILinkPoint[] array2 = new UILinkPoint[snapGroup2.Count];
            for (int k = 0; k < snapGroup2.Count; k++)
            {
                UILinkPointNavigator.SetPosition(num, snapGroup2[k].Position);
                uilinkPoint = UILinkPointNavigator.Points[num];
                uilinkPoint.Unlink();
                array2[k] = uilinkPoint;
                num++;
            }
            UILinkPoint[] array3 = new UILinkPoint[snapGroup3.Count];
            for (int l = 0; l < snapGroup3.Count; l++)
            {
                UILinkPointNavigator.SetPosition(num, snapGroup3[l].Position);
                uilinkPoint = UILinkPointNavigator.Points[num];
                uilinkPoint.Unlink();
                array3[l] = uilinkPoint;
                num++;
            }
            this.LoopHorizontalLineLinks(array);
            this.LoopHorizontalLineLinks(array2);
            this.EstablishUpDownRelationship(array, array2);
            for (int m = 0; m < array.Length; m++)
            {
                array[m].Up = uilinkPoint7.ID;
            }
            if (true)
            {
                this.LoopHorizontalLineLinks(array3);
                this.EstablishUpDownRelationship(array2, array3);
                for (int n = 0; n < array3.Length; n++)
                {
                    array3[n].Down = uilinkPoint2.ID;
                }
                array3[array3.Length - 1].Down = uilinkPoint3.ID;
                uilinkPoint3.Up = array3[array3.Length - 1].ID;
                uilinkPoint2.Up = array3[0].ID;
            }
            else
            {
                for (int num2 = 0; num2 < array2.Length; num2++)
                {
                    array2[num2].Down = uilinkPoint2.ID;
                }
                array2[array2.Length - 1].Down = uilinkPoint3.ID;
                uilinkPoint3.Up = array2[array2.Length - 1].ID;
                uilinkPoint2.Up = array2[0].ID;
            }
            uilinkPoint3.Left = uilinkPoint2.ID;
            uilinkPoint2.Right = uilinkPoint3.ID;
            uilinkPoint5.Down = uilinkPoint7.ID;
            uilinkPoint5.Left = uilinkPoint4.ID;
            uilinkPoint4.Right = uilinkPoint5.ID;
            uilinkPoint7.Up = uilinkPoint5.ID;
            uilinkPoint7.Down = array[0].ID;
            uilinkPoint7.Left = uilinkPoint6.ID;
            uilinkPoint6.Right = uilinkPoint7.ID;
            uilinkPoint6.Up = uilinkPoint4.ID;
            uilinkPoint6.Down = array[0].ID;
            uilinkPoint4.Down = uilinkPoint6.ID;
        }
References System.array, System.Collections.Generic.List< T >.Count, Terraria.UI.Gamepad.UILinkPoint.Down, Terraria.GameContent.UI.States.UIWorldCreation.EstablishUpDownRelationship(), Terraria.GameContent.UI.States.UIWorldCreation.GetSnapGroup(), Terraria.UI.UIElement.GetSnapPoints(), Terraria.UI.Gamepad.UILinkPoint.ID, Terraria.GameContent.UI.States.UIWorldCreation.LoopHorizontalLineLinks(), System.name, Terraria.UI.SnapPoint.Name, Terraria.UI.Gamepad.UILinkPointNavigator.Points, Microsoft.Xna.Framework.Graphics.Position, Terraria.UI.SnapPoint.Position, Terraria.UI.Gamepad.UILinkPointNavigator.SetPosition(), and Terraria.UI.Gamepad.UILinkPoint.Unlink().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.Draw().