Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.LaunchLocalServer
LaunchLocalServer()
override void Terraria.Social.WeGame.NetClientSocialModule.LaunchLocalServer (Process process, ServerMode mode) inline
Definition at line 201 of file NetClientSocialModule.cs.
        {
            if (this._lobby.State != LobbyState.Inactive)
            {
                this._lobby.Leave();
            }
            this.LazyCreateWeGameMsgServer();
            ProcessStartInfo startInfo = process.StartInfo;
            startInfo.Arguments = startInfo.Arguments + " -wegame -localwegameid " + base.GetLocalPeer().id_;
            if ((mode & ServerMode.Lobby) != ServerMode.None)
            {
                this._hasLocalHost = true;
                if ((mode & ServerMode.FriendsCanJoin) != ServerMode.None)
                {
                    ProcessStartInfo startInfo2 = process.StartInfo;
                    startInfo2.Arguments += " -lobby friends";
                }
                else
                {
                    ProcessStartInfo startInfo3 = process.StartInfo;
                    startInfo3.Arguments += " -lobby private";
                }
                if ((mode & ServerMode.FriendsOfFriends) != ServerMode.None)
                {
                    ProcessStartInfo startInfo4 = process.StartInfo;
                    startInfo4.Arguments += " -friendsoffriends";
                }
            }
            string text;
            rail_api.RailFactory().RailUtils().GetLaunchAppParameters(2, ref text);
            ProcessStartInfo startInfo5 = process.StartInfo;
            startInfo5.Arguments = startInfo5.Arguments + " " + text;
            WeGameHelper.WriteDebugString("LaunchLocalServer,cmd_line:" + process.StartInfo.Arguments, new object[0]);
            this.AsyncSetMyMetaData("status", Language.GetTextValue("Social.StatusInGame"));
            Netplay.OnDisconnect += this.OnDisconnect;
            process.Start();
        }
References Terraria.Social.WeGame.NetSocialModule._lobby, Terraria.Social.WeGame.NetClientSocialModule.AsyncSetMyMetaData(), rail.IRailUtils.GetLaunchAppParameters(), Terraria.Localization.Language.GetTextValue(), Terraria.Social.WeGame.NetClientSocialModule.LazyCreateWeGameMsgServer(), Terraria.Social.WeGame.Lobby.Leave(), System.mode, Terraria.Social.WeGame.NetClientSocialModule.OnDisconnect(), rail.rail_api.RailFactory(), rail.IRailFactory.RailUtils(), Terraria.Social.WeGame.Lobby.State, System.text, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().