Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.AsyncGetFriendsInfo
AsyncGetFriendsInfo()
void Terraria.Social.WeGame.NetClientSocialModule.AsyncGetFriendsInfo () inline private
Definition at line 516 of file NetClientSocialModule.cs.
        {
            IRailFriends railFriends = rail_api.RailFactory().RailFriends();
            if (railFriends != null)
            {
                List<RailFriendInfo> list = new List<RailFriendInfo>();
                railFriends.GetFriendsList(list);
                List<RailID> list2 = new List<RailID>();
                foreach (RailFriendInfo railFriendInfo in list)
                {
                    list2.Add(railFriendInfo.friend_rail_id);
                }
                railFriends.AsyncGetPersonalInfo(list2, "");
            }
        }
References rail.IRailFriends.AsyncGetPersonalInfo(), rail.RailFriendInfo.friend_rail_id, rail.IRailFriends.GetFriendsList(), System.list, rail.rail_api.RailFactory(), and rail.IRailFactory.RailFriends().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.Initialize().