Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription
ShowOptionDescription()
void Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription (UIMouseEvent evt, UIElement listeningElement) inline
Definition at line 552 of file UIWorldCreation.cs.
        {
            LocalizedText localizedText = null;
            GroupOptionButton<UIWorldCreation.WorldSizeId> groupOptionButton = listeningElement as GroupOptionButton<UIWorldCreation.WorldSizeId>;
            if (groupOptionButton != null)
            {
                localizedText = groupOptionButton.Description;
            }
            GroupOptionButton<UIWorldCreation.WorldDifficultyId> groupOptionButton2 = listeningElement as GroupOptionButton<UIWorldCreation.WorldDifficultyId>;
            if (groupOptionButton2 != null)
            {
                localizedText = groupOptionButton2.Description;
            }
            GroupOptionButton<UIWorldCreation.WorldEvilId> groupOptionButton3 = listeningElement as GroupOptionButton<UIWorldCreation.WorldEvilId>;
            if (groupOptionButton3 != null)
            {
                localizedText = groupOptionButton3.Description;
            }
            UICharacterNameButton uicharacterNameButton = listeningElement as UICharacterNameButton;
            if (uicharacterNameButton != null)
            {
                localizedText = uicharacterNameButton.Description;
            }
            GroupOptionButton<bool> groupOptionButton4 = listeningElement as GroupOptionButton<bool>;
            if (groupOptionButton4 != null)
            {
                localizedText = groupOptionButton4.Description;
            }
            if (localizedText != null)
            {
                this._descriptionText.SetText(localizedText);
            }
        }
References Terraria.GameContent.UI.States.UIWorldCreation._descriptionText, Terraria.GameContent.UI.Elements.GroupOptionButton< T >.Description, Terraria.GameContent.UI.Elements.UICharacterNameButton.Description, and Terraria.GameContent.UI.Elements.UIText.SetText().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), and Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu().