Terraria Decompiled: System.Resources.ResourceSet.GetCaseInsensitiveObjectInternal
GetCaseInsensitiveObjectInternal()
object System.Resources.ResourceSet.GetCaseInsensitiveObjectInternal (string name) inline private
Definition at line 215 of file ResourceSet.cs.
        {
            Hashtable table = this.Table;
            if (table == null)
            {
                throw new ObjectDisposedException(null, Environment.GetResourceString("Cannot access a closed resource set."));
            }
            Hashtable hashtable = this._caseInsensitiveTable;
            if (hashtable == null)
            {
                hashtable = new Hashtable(StringComparer.OrdinalIgnoreCase);
                IDictionaryEnumerator enumerator = table.GetEnumerator();
                while (enumerator.MoveNext())
                {
                    hashtable.Add(enumerator.Key, enumerator.Value);
                }
                this._caseInsensitiveTable = hashtable;
            }
            return hashtable[name];
        }
References System.Resources.ResourceSet._caseInsensitiveTable, System.Collections.Hashtable.Add(), System.Collections.Hashtable.GetEnumerator(), System.Environment.GetResourceString(), System.Collections.IDictionaryEnumerator.Key, System.Collections.IEnumerator.MoveNext(), System.name, System.StringComparer.OrdinalIgnoreCase, System.Resources.ResourceSet.Table, and System.Collections.IDictionaryEnumerator.Value.
Referenced by System.Resources.ResourceSet.GetObject(), and System.Resources.ResourceSet.GetString().