Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu
MakeInfoMenu()
void Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu (UIElement parentContainer) inline private
Definition at line 136 of file UIWorldCreation.cs.
        {
            UIElement uielement = new UIElement
            {
                Width = StyleDimension.FromPixelsAndPercent(0f, 1f),
                Height = StyleDimension.FromPixelsAndPercent(0f, 1f),
                HAlign = 0.5f,
                VAlign = 0f
            };
            uielement.SetPadding(10f);
            uielement.PaddingBottom = 0f;
            uielement.PaddingTop = 0f;
            parentContainer.Append(uielement);
            float num = 0f;
            float num2 = 88f;
            float num3 = 44f;
            float num4 = num2 + num3;
            float num5 = num3;
            GroupOptionButton<bool> groupOptionButton = new GroupOptionButton<bool>(true, null, Language.GetText("UI.WorldCreationRandomizeNameDescription"), Color.White, "Images/UI/WorldCreation/IconRandomName", 1f, 0.5f, 10f)
            {
                Width = StyleDimension.FromPixelsAndPercent(40f, 0f),
                Height = new StyleDimension(40f, 0f),
                HAlign = 0f,
                Top = StyleDimension.FromPixelsAndPercent(num, 0f),
                ShowHighlightWhenSelected = false
            };
            groupOptionButton.OnLeftMouseDown += this.ClickRandomizeName;
            groupOptionButton.OnMouseOver += this.ShowOptionDescription;
            groupOptionButton.OnMouseOut += this.ClearOptionDescription;
            groupOptionButton.SetSnapPoint("RandomizeName", 0, null, null);
            uielement.Append(groupOptionButton);
            UICharacterNameButton uicharacterNameButton = new UICharacterNameButton(Language.GetText("UI.WorldCreationName"), Language.GetText("UI.WorldCreationNameEmpty"), Language.GetText("UI.WorldDescriptionName"))
            {
                Width = StyleDimension.FromPixelsAndPercent(-num4, 1f),
                HAlign = 0f,
                Left = new StyleDimension(num5, 0f),
                Top = StyleDimension.FromPixelsAndPercent(num, 0f)
            };
            uicharacterNameButton.OnLeftMouseDown += this.Click_SetName;
            uicharacterNameButton.OnMouseOver += this.ShowOptionDescription;
            uicharacterNameButton.OnMouseOut += this.ClearOptionDescription;
            uicharacterNameButton.SetSnapPoint("Name", 0, null, null);
            uielement.Append(uicharacterNameButton);
            this._namePlate = uicharacterNameButton;
            CalculatedStyle calculatedStyle = uicharacterNameButton.GetDimensions();
            num += calculatedStyle.Height + 4f;
            this._advancedSeedButton = new GroupOptionButton<bool>(true, null, Language.GetText("UI.WorldCreationSeedMenuDescription"), Color.White, "Images/UI/WorldCreation/IconRandomSeed", 1f, 0.5f, 10f)
            {
                Width = StyleDimension.FromPixelsAndPercent(40f, 0f),
                Height = new StyleDimension(40f, 0f),
                HAlign = 0f,
                Top = StyleDimension.FromPixelsAndPercent(num, 0f),
                ShowHighlightWhenSelected = false
            };
            this._advancedSeedButton.OnLeftMouseDown += this.ClickAdvancedSeedMenu;
            this._advancedSeedButton.OnMouseOver += this.ShowOptionDescription;
            this._advancedSeedButton.OnMouseOut += this.ClearOptionDescription;
            this._advancedSeedButton.SetSnapPoint("RandomizeSeed", 0, null, null);
            this._advancedSeedButton.OnDraw += this.DrawSpecialSeedRingCallback;
            uielement.Append(this._advancedSeedButton);
            UICharacterNameButton uicharacterNameButton2 = new UICharacterNameButton(Language.GetText("UI.WorldCreationSeed"), Language.GetText("UI.WorldCreationSeedEmpty"), Language.GetText("UI.WorldDescriptionSeed"))
            {
                Width = StyleDimension.FromPixelsAndPercent(-num4, 1f),
                HAlign = 0f,
                Left = new StyleDimension(num5, 0f),
                Top = StyleDimension.FromPixelsAndPercent(num, 0f),
                DistanceFromTitleToOption = 29f
            };
            uicharacterNameButton2.OnLeftMouseDown += this.Click_SetSeed;
            uicharacterNameButton2.OnMouseOver += this.ShowOptionDescription;
            uicharacterNameButton2.OnMouseOut += this.ClearOptionDescription;
            uicharacterNameButton2.SetSnapPoint("Seed", 0, null, null);
            uielement.Append(uicharacterNameButton2);
            this._seedPlate = uicharacterNameButton2;
            UIWorldCreationPreview uiworldCreationPreview = new UIWorldCreationPreview
            {
                Width = StyleDimension.FromPixels(84f),
                Height = StyleDimension.FromPixels(84f),
                HAlign = 1f,
                VAlign = 0f
            };
            uielement.Append(uiworldCreationPreview);
            this._previewPlate = uiworldCreationPreview;
            calculatedStyle = uicharacterNameButton2.GetDimensions();
            num += calculatedStyle.Height + 10f;
            UIWorldCreation.AddHorizontalSeparator(uielement, num + 2f);
            float num6 = 1f;
            this.AddWorldSizeOptions(uielement, num, new UIElement.MouseEvent(this.ClickSizeOption), "size", num6);
            num += 48f;
            UIWorldCreation.AddHorizontalSeparator(uielement, num);
            this.AddWorldDifficultyOptions(uielement, num, new UIElement.MouseEvent(this.ClickDifficultyOption), "difficulty", num6);
            num += 48f;
            UIWorldCreation.AddHorizontalSeparator(uielement, num);
            this.AddWorldEvilOptions(uielement, num, new UIElement.MouseEvent(this.ClickEvilOption), "evil", num6);
            num += 48f;
            UIWorldCreation.AddHorizontalSeparator(uielement, num);
            this.AddDescriptionPanel(uielement, num, "desc");
            this.SetDefaultOptions();
        }
References Terraria.GameContent.UI.States.UIWorldCreation._advancedSeedButton, Terraria.GameContent.UI.States.UIWorldCreation.AddDescriptionPanel(), Terraria.GameContent.UI.States.UIWorldCreation.AddHorizontalSeparator(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldDifficultyOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldEvilOptions(), Terraria.GameContent.UI.States.UIWorldCreation.AddWorldSizeOptions(), Terraria.UI.UIElement.Append(), Terraria.GameContent.UI.States.UIWorldCreation.ClearOptionDescription(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetName(), Terraria.GameContent.UI.States.UIWorldCreation.Click_SetSeed(), Terraria.GameContent.UI.States.UIWorldCreation.ClickAdvancedSeedMenu(), Terraria.GameContent.UI.States.UIWorldCreation.ClickRandomizeName(), Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback(), Terraria.UI.StyleDimension.FromPixels(), Terraria.UI.StyleDimension.FromPixelsAndPercent(), Terraria.UI.UIElement.GetDimensions(), Terraria.Localization.Language.GetText(), Terraria.UI.UIElement.HAlign, Terraria.UI.UIElement.Height, Terraria.UI.UIElement.Left, Terraria.UI.UIElement.MouseEvent(), Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions(), Terraria.UI.UIElement.SetPadding(), Terraria.UI.UIElement.SetSnapPoint(), Terraria.GameContent.UI.States.UIWorldCreation.ShowOptionDescription(), Terraria.UI.UIElement.Top, Terraria.UI.UIElement.VAlign, Microsoft.Xna.Framework.Color.White, and Terraria.UI.UIElement.Width.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.BuildPage().