Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess
OnAuthSuccess()
void Terraria.Social.WeGame.NetClientSocialModule.OnAuthSuccess (RailID remote_peer) inline private
Definition at line 140 of file NetClientSocialModule.cs.
        {
            if (!this._connectionStateMap.ContainsKey(remote_peer))
            {
                return;
            }
            this._connectionStateMap[remote_peer] = NetSocialModule.ConnectionState.Connected;
            this.AsyncSetPlayWith(this._inviter_id);
            this.AsyncSetMyMetaData("status", Language.GetTextValue("Social.StatusInGame"));
            this.AsyncSetMyMetaData(this._serverIDMedataKey, remote_peer.id_.ToString());
            Main.clrInput();
            Netplay.ServerPassword = "";
            Main.GetInputText("", false);
            Main.autoPass = false;
            Main.netMode = 1;
            Netplay.OnConnectedToSocialServer(new SocialSocket(new WeGameAddress(remote_peer, this.GetFriendNickname(this._inviter_id))));
            WeGameHelper.WriteDebugString("OnConnectToSocialServer server:" + remote_peer.id_.ToString(), new object[0]);
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, Terraria.Social.WeGame.NetClientSocialModule._inviter_id, Terraria.Social.WeGame.NetClientSocialModule._serverIDMedataKey, Terraria.Social.WeGame.NetClientSocialModule.AsyncSetMyMetaData(), Terraria.Social.WeGame.NetClientSocialModule.AsyncSetPlayWith(), Terraria.Main.clrInput(), Terraria.Social.WeGame.NetClientSocialModule.GetFriendNickname(), Terraria.Main.GetInputText(), Terraria.Localization.Language.GetTextValue(), rail.RailComparableID.id_, Terraria.Netplay.OnConnectedToSocialServer(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnPacketRead().