Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing
UpdateSpecialSeedRing()
void Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing (UIElement element) inline private
Definition at line 1100 of file UIWorldCreation.cs.
        {
            CalculatedStyle calculatedStyle = this._advancedSeedButton.GetDimensions();
            if (this._goBackTarget != this)
            {
                UIWorldCreationAdvanced uiworldCreationAdvanced = this._goBackTarget as UIWorldCreationAdvanced;
                if (uiworldCreationAdvanced != null)
                {
                    uiworldCreationAdvanced.RefreshSecretSeedButton();
                    calculatedStyle = uiworldCreationAdvanced.GetSecretSeedButton().GetDimensions();
                }
            }
            if (element is GroupOptionButton<WorldGen.SecretSeed>)
            {
                calculatedStyle = element.GetDimensions();
            }
            Rectangle rectangle = calculatedStyle.ToRectangle();
            rectangle.Inflate(-1, -1);
            int num = rectangle.Width * 2 + rectangle.Height * 2;
            float num2 = (float)num / 60f;
            this.ringPoint += num2;
            if (this.ringPoint >= (float)num)
            {
                this.ringPoint -= (float)num;
            }
            float num3 = (float)Math.Sqrt((double)(rectangle.Width / 2 * rectangle.Width / 2 + rectangle.Height / 2 * rectangle.Height / 2));
            float num4 = 6.2831855f * this.ringPoint / (float)num;
            Vector2 vector = new Vector2((float)Math.Cos((double)num4), (float)Math.Sin((double)num4));
            Vector2 vector2 = vector * num3;
            float num5 = Math.Abs(vector2.X) / ((float)rectangle.Width / 2f);
            float num6 = Math.Abs(vector2.Y) / ((float)rectangle.Height / 2f);
            if (num5 > num6)
            {
                vector2 /= num5;
                vector /= num5;
            }
            else
            {
                vector2 /= num6;
                vector /= num6;
            }
            vector2 += rectangle.Center.ToVector2();
            for (int i = this.oldPos.Length - 1; i > 0; i--)
            {
                this.oldPos[i] = this.oldPos[i - 1];
                this.oldTangent[i] = this.oldTangent[i - 1];
            }
            this.oldPos[0] = vector2;
            this.oldTangent[0] = vector;
        }
References Terraria.GameContent.UI.States.UIWorldCreation._advancedSeedButton, Terraria.GameContent.UI.States.UIWorldCreation._goBackTarget, System.Math.Abs(), Microsoft.Xna.Framework.Rectangle.Center, System.Math.Cos(), Terraria.UI.UIElement.GetDimensions(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.GetSecretSeedButton(), Microsoft.Xna.Framework.Rectangle.Height, Microsoft.Xna.Framework.Rectangle.Inflate(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.UI.States.UIWorldCreation.oldPos, Terraria.GameContent.UI.States.UIWorldCreation.oldTangent, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton(), Terraria.GameContent.UI.States.UIWorldCreation.ringPoint, System.Math.Sin(), System.Math.Sqrt(), Terraria.UI.CalculatedStyle.ToRectangle(), Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Rectangle.Width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback(), and Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallbackWithoutCondition().