Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.UpdatePreviewPlate
UpdatePreviewPlate()
void Terraria.GameContent.UI.States.UIWorldCreation.UpdatePreviewPlate () inline private
Definition at line 526 of file UIWorldCreation.cs.
        {
            this._previewPlate.UpdateOption((byte)this._optionDifficulty, (byte)this._optionEvil, (byte)this._optionSize);
        }
References Terraria.GameContent.UI.States.UIWorldCreation._optionDifficulty, Terraria.GameContent.UI.States.UIWorldCreation._optionEvil, Terraria.GameContent.UI.States.UIWorldCreation._optionSize, Terraria.GameContent.UI.States.UIWorldCreation._previewPlate, and Terraria.GameContent.UI.Elements.UIWorldCreationPreview.UpdateOption().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.ClickDifficultyOption(), Terraria.GameContent.UI.States.UIWorldCreation.ClickEvilOption(), Terraria.GameContent.UI.States.UIWorldCreation.ClickRandomizeName(), Terraria.GameContent.UI.States.UIWorldCreation.ClickSizeOption(), Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed(), Terraria.GameContent.UI.States.UIWorldCreation.RandomizeSeed(), Terraria.GameContent.UI.States.UIWorldCreation.SetDefaultOptions(), and Terraria.GameContent.UI.States.UIWorldCreation.ToggleSeedOption().