Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed
OnFinishedSettingSeed()
void Terraria.GameContent.UI.States.UIWorldCreation.OnFinishedSettingSeed (string seed) inline private
Definition at line 807 of file UIWorldCreation.cs.
        {
            this._optionSeed = seed.Trim();
            string text;
            string text2;
            List<string> list;
            if (WorldFileData.TryApplyingCopiedSeed(this._optionSeed, true, out text, out text2, out list))
            {
                this._optionSeed = text;
                this._secretSeedTextsEntered = list;
                this._disabledSecretSeedTextsEntered.Clear();
            }
            else
            {
                this._optionSeed = Utils.TrimUserString(this._optionSeed, WorldFileData.MAX_USER_SEED_TEXT_LENGTH);
                AWorldGenerationOption optionFromSeedText = WorldGenerationOptions.GetOptionFromSeedText(this._optionSeed);
                this._isSpecialSeedText = optionFromSeedText != null;
                if (this._isSpecialSeedText)
                {
                    WorldGenerationOptions.SelectOption(optionFromSeedText);
                    SoundEngine.PlaySound(24, -1, -1, 1, 1f, 0f);
                }
                WorldGen.SecretSeed secretSeed;
                if (WorldGen.SecretSeed.CheckInputForSecretSeed(this._optionSeed, out secretSeed))
                {
                    if (!secretSeed.Enabled)
                    {
                        this._secretSeedTextsEntered.Add(this._optionSeed);
                        WorldGen.SecretSeed.Enable(secretSeed, true);
                        this.EnableSecretSeedOptions(true);
                        CalculatedStyle calculatedStyle = this._advancedSeedButton.GetDimensions();
                        if (this._goBackTarget != this)
{
                            UIWorldCreationAdvanced uiworldCreationAdvanced = this._goBackTarget as UIWorldCreationAdvanced;
                            if (uiworldCreationAdvanced != null)
{
                                uiworldCreationAdvanced.RefreshSecretSeedButton();
                                calculatedStyle = uiworldCreationAdvanced.GetSecretSeedButton().GetDimensions();
                                uiworldCreationAdvanced.GetSecretSeedButton().SetCurrentOption(this.HasEnteredSpecialSeed);
                            }
                        }
                        Vector2 vector = calculatedStyle.Center();
                        Vector2 vector2 = Main.rand.NextVector2Circular(5f, 5f);
                        this.Spawn_RainbowRodHit(new ParticleOrchestraSettings
{
                            PositionInWorld = vector,
                            MovementVector = new Vector2(16f, 0f) + vector2
                        });
                        if (this._goBackTarget != this)
{
                            this.Spawn_RainbowRodHit(new ParticleOrchestraSettings
{
                                PositionInWorld = vector,
                                MovementVector = new Vector2(16f, 0f) - vector2
                            });
                        }
                        Vector2 vector3 = Main.rand.NextVector2Circular(5f, 5f);
                        this.Spawn_RainbowRodHit(new ParticleOrchestraSettings
{
                            PositionInWorld = vector,
                            MovementVector = new Vector2(0f, 16f) + vector3
                        });
                        if (this._goBackTarget != this)
{
                            this.Spawn_RainbowRodHit(new ParticleOrchestraSettings
{
                                PositionInWorld = vector,
                                MovementVector = new Vector2(0f, 16f) - vector3
                            });
                        }
                        for (int i = 0; i < 3; i++)
{
                            this.Spawn_BestReforge(new ParticleOrchestraSettings
{
                                PositionInWorld = vector + new Vector2(calculatedStyle.Width * 0.25f * (float)(i - 1), 0f)
                            });
                        }
                    }
                    this.ClearSeedText();
                }
            }
            this.UpdateInputFields();
            this.UpdateSliders();
            this.UpdatePreviewPlate();
            if (this.SubmitSeed != null)
            {
                this.SubmitSeed();
            }
            this.GoBackHere();
        }
References Terraria.GameContent.UI.States.UIWorldCreation._advancedSeedButton, Terraria.GameContent.UI.States.UIWorldCreation._disabledSecretSeedTextsEntered, Terraria.GameContent.UI.States.UIWorldCreation._goBackTarget, Terraria.GameContent.UI.States.UIWorldCreation._isSpecialSeedText, Terraria.GameContent.UI.States.UIWorldCreation._optionSeed, Terraria.GameContent.UI.States.UIWorldCreation._secretSeedTextsEntered, System.Collections.Generic.List< T >.Add(), Terraria.UI.CalculatedStyle.Center(), Terraria.WorldGen.SecretSeed.CheckInputForSecretSeed(), System.Collections.Generic.List< T >.Clear(), Terraria.GameContent.UI.States.UIWorldCreation.ClearSeedText(), Terraria.WorldGen.SecretSeed.Enable(), Terraria.WorldGen.SecretSeed.Enabled, Terraria.GameContent.UI.States.UIWorldCreation.EnableSecretSeedOptions(), Terraria.WorldBuilding.WorldGenerationOptions.GetOptionFromSeedText(), Terraria.GameContent.UI.States.UIWorldCreationAdvanced.GetSecretSeedButton(), Terraria.GameContent.UI.States.UIWorldCreation.GoBackHere(), Terraria.GameContent.UI.States.UIWorldCreation.HasEnteredSpecialSeed, System.list, Terraria.IO.WorldFileData.MAX_USER_SEED_TEXT_LENGTH, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton(), Terraria.WorldBuilding.WorldGenerationOptions.SelectOption(), Terraria.GameContent.UI.Elements.GroupOptionButton< T >.SetCurrentOption(), Terraria.GameContent.UI.States.UIWorldCreation.Spawn_BestReforge(), Terraria.GameContent.UI.States.UIWorldCreation.Spawn_RainbowRodHit(), Terraria.GameContent.UI.States.UIWorldCreation.SubmitSeed, System.text, Terraria.Utils.TrimUserString(), Terraria.IO.WorldFileData.TryApplyingCopiedSeed(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields(), Terraria.GameContent.UI.States.UIWorldCreation.UpdatePreviewPlate(), Terraria.GameContent.UI.States.UIWorldCreation.UpdateSliders(), Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.UI.CalculatedStyle.Width.