Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.RandomizeSeed
RandomizeSeed()
void Terraria.GameContent.UI.States.UIWorldCreation.RandomizeSeed () inline
Definition at line 477 of file UIWorldCreation.cs.
        {
            this._optionSeed = Main.rand.Next().ToString();
            this._isSpecialSeedText = false;
            this.UpdateInputFields();
            this.UpdateSliders();
            this.UpdatePreviewPlate();
        }
References Terraria.Main.rand, Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields(), Terraria.GameContent.UI.States.UIWorldCreation.UpdatePreviewPlate(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdateSliders().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.ClickRandomizeSeed().