Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing
DrawSpecialSeedRing()
void Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing () inline private
Definition at line 1152 of file UIWorldCreation.cs.
        {
            MiscShaderData miscShaderData = GameShaders.Misc["RainbowRod"];
            miscShaderData.UseSaturation(this.trial);
            miscShaderData.UseOpacity((this._goBackTarget != this) ? this.opacity2 : this.opacity);
            miscShaderData.UseSpriteTransformMatrix(new Matrix?(Main.UIScaleMatrix));
            miscShaderData.Apply(null);
            float num = 4f;
            if (this._goBackTarget != this)
            {
                num = 5f;
            }
            int num2 = this.oldPos.Length;
            UIWorldCreation._vertexStrip.Reset(num2 * 2);
            int num3 = num2;
            int num4 = 0;
            while (num4 < num2 && !(this.oldPos[num4] == Vector2.Zero))
            {
                Vector2 vector = this.oldPos[num4];
                float num5 = (float)num4 / (float)(num3 - 1);
                num5 *= 0.6f;
                Color color = this.StripColors(num5);
                float num6 = this.StripWidth(num5);
                Vector2 vector2 = this.oldTangent[num4] * num;
                Vector3 vector3 = new Vector3(num5, num6 / 2f, num6);
                Vector3 vector4 = new Vector3(num5, num6 / 2f, num6);
                UIWorldCreation._vertexStrip.AddVertexPair(vector + vector2, vector, vector3, vector4, color);
                num4++;
            }
            UIWorldCreation._vertexStrip.PrepareIndices(true);
            UIWorldCreation._vertexStrip.DrawTrail();
            Main.pixelShader.CurrentTechnique.Passes[0].Apply();
            miscShaderData.UseSpriteTransformMatrix(null);
        }
References Terraria.GameContent.UI.States.UIWorldCreation._goBackTarget, Terraria.GameContent.UI.States.UIWorldCreation._vertexStrip, Terraria.Graphics.VertexStrip.AddVertexPair(), Terraria.Graphics.Shaders.MiscShaderData.Apply(), Microsoft.Xna.Framework.Graphics.Effect.CurrentTechnique, Terraria.Graphics.VertexStrip.DrawTrail(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.Graphics.Shaders.GameShaders.Misc, Terraria.GameContent.UI.States.UIWorldCreation.oldPos, Terraria.GameContent.UI.States.UIWorldCreation.oldTangent, Terraria.GameContent.UI.States.UIWorldCreation.opacity, Terraria.GameContent.UI.States.UIWorldCreation.opacity2, Microsoft.Xna.Framework.Graphics.EffectTechnique.Passes, Terraria.Main.pixelShader, Terraria.Graphics.VertexStrip.PrepareIndices(), Terraria.Graphics.VertexStrip.Reset(), Terraria.GameContent.UI.States.UIWorldCreation.StripColors(), Terraria.GameContent.UI.States.UIWorldCreation.StripWidth(), Terraria.GameContent.UI.States.UIWorldCreation.trial, Terraria.Main.UIScaleMatrix, Terraria.Graphics.Shaders.MiscShaderData.UseOpacity(), Terraria.Graphics.Shaders.MiscShaderData.UseSaturation(), Terraria.Graphics.Shaders.MiscShaderData.UseSpriteTransformMatrix(), Microsoft.Xna.Framework.Graphics.Vector3, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback(), and Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallbackWithoutCondition().