Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.FillSeedContent
FillSeedContent()
void Terraria.GameContent.UI.States.UIWorldCreation.FillSeedContent (UICharacterNameButton button) inline
Definition at line 709 of file UIWorldCreation.cs.
        {
            button.SetContents(this._optionSeed);
            button.Recalculate();
            button.TrimDisplayIfOverElementDimensions(WorldFileData.MAX_USER_SEED_TEXT_LENGTH);
            button.Recalculate();
        }
References Terraria.GameContent.UI.States.UIWorldCreation._optionSeed, Terraria.IO.WorldFileData.MAX_USER_SEED_TEXT_LENGTH, Terraria.UI.UIElement.Recalculate(), Terraria.GameContent.UI.Elements.UICharacterNameButton.SetContents(), and Terraria.GameContent.UI.Elements.UICharacterNameButton.TrimDisplayIfOverElementDimensions().
Referenced by Terraria.GameContent.UI.States.UIWorldCreationAdvanced.UpdateContents(), and Terraria.GameContent.UI.States.UIWorldCreation.UpdateInputFields().