Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.JoinServer
JoinServer()
void Terraria.Social.WeGame.NetClientSocialModule.JoinServer (RailID server_id) inline private
Definition at line 472 of file NetClientSocialModule.cs.
        {
            WeGameHelper.WriteDebugString("JoinServer:{0}", new object[] { server_id.id_ });
            this._connectionStateMap[server_id] = NetSocialModule.ConnectionState.Authenticating;
            int num = 3;
            byte[] array = new byte[num];
            array[0] = (byte)(num & 255);
            array[1] = (byte)((num >> 8) & 255);
            array[2] = 93;
            rail_api.RailFactory().RailNetworkHelper().SendReliableData(base.GetLocalPeer(), server_id, array, (uint)num);
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, System.array, rail.rail_api.RailFactory(), rail.IRailFactory.RailNetworkHelper(), rail.IRailNetwork.SendReliableData(), and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.CheckParameters(), and Terraria.Social.WeGame.NetClientSocialModule.OnGetFriendMetaData().