Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.AsyncSetInviteCommandLine
AsyncSetInviteCommandLine()
void Terraria.Social.WeGame.NetClientSocialModule.AsyncSetInviteCommandLine (string cmdline) inline private
Definition at line 74 of file NetClientSocialModule.cs.
        {
            rail_api.RailFactory().RailFriends().AsyncSetInviteCommandLine(cmdline, "");
        }
References rail.IRailFriends.AsyncSetInviteCommandLine(), rail.rail_api.RailFactory(), and rail.IRailFactory.RailFriends().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnReportServerID(), and Terraria.Social.WeGame.NetClientSocialModule.Shutdown().