Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback
DrawSpecialSeedRingCallback()
void Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRingCallback (UIElement element, SpriteBatch spriteBatch) inline
Definition at line 1051 of file UIWorldCreation.cs.
        {
            if (this.HasEnteredSpecialSeed)
            {
                spriteBatch.End();
                spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.AnisotropicClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
                if (this.oldPos[0] == Vector2.Zero)
                {
                    for (int i = 0; i < 61; i++)
                    {
                        this.UpdateSpecialSeedRing(element);
                    }
                }
                else
                {
                    this.specialSeedIndex = (this.specialSeedIndex + 1) % 4;
                    if (this.specialSeedIndex % 4 == 0)
                    {
                        this.UpdateSpecialSeedRing(element);
                    }
                }
                this.DrawSpecialSeedRing();
                spriteBatch.End();
                spriteBatch.Begin(SpriteSortMode.Deferred, BlendState.AlphaBlend, SamplerState.AnisotropicClamp, DepthStencilState.None, RasterizerState.CullCounterClockwise, null, Main.UIScaleMatrix);
            }
        }
References Microsoft.Xna.Framework.Graphics.BlendState.AlphaBlend, Microsoft.Xna.Framework.Graphics.SamplerState.AnisotropicClamp, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Microsoft.Xna.Framework.Graphics.RasterizerState.CullCounterClockwise, Terraria.GameContent.UI.States.UIWorldCreation.DrawSpecialSeedRing(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.GameContent.UI.States.UIWorldCreation.HasEnteredSpecialSeed, Microsoft.Xna.Framework.Graphics.DepthStencilState.None, Terraria.GameContent.UI.States.UIWorldCreation.oldPos, Terraria.GameContent.UI.States.UIWorldCreation.specialSeedIndex, Terraria.Main.UIScaleMatrix, Terraria.GameContent.UI.States.UIWorldCreation.UpdateSpecialSeedRing(), and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.MakeInfoMenu(), and Terraria.GameContent.UI.States.UIWorldCreationAdvanced.RefreshSecretSeedButton().