Terraria Decompiled: Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionRequest
OnRailCreateSessionRequest()
void Terraria.Social.WeGame.NetClientSocialModule.OnRailCreateSessionRequest (CreateSessionRequest result) inline private
Definition at line 584 of file NetClientSocialModule.cs.
        {
            WeGameHelper.WriteDebugString("OnRailCreateSessionRequest", new object[0]);
            if (this._connectionStateMap.ContainsKey(result.remote_peer) && this._connectionStateMap[result.remote_peer] != NetSocialModule.ConnectionState.Inactive)
            {
                WeGameHelper.WriteDebugString("AcceptSessionRequest, local{0}, remote:{1}", new object[]
                {
                    result.local_peer.id_,
                    result.remote_peer.id_
                });
                rail_api.RailFactory().RailNetworkHelper().AcceptSessionRequest(result.local_peer, result.remote_peer);
            }
        }
References Terraria.Social.WeGame.NetSocialModule._connectionStateMap, rail.IRailNetwork.AcceptSessionRequest(), rail.RailComparableID.id_, rail.CreateSessionRequest.local_peer, rail.rail_api.RailFactory(), rail.IRailFactory.RailNetworkHelper(), rail.CreateSessionRequest.remote_peer, and Terraria.Social.WeGame.WeGameHelper.WriteDebugString().
Referenced by Terraria.Social.WeGame.NetClientSocialModule.OnRailEvent().