Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldCreation.DrawSeedSystems
DrawSeedSystems()
void Terraria.GameContent.UI.States.UIWorldCreation.DrawSeedSystems (SpriteBatch spriteBatch) inline
Definition at line 1203 of file UIWorldCreation.cs.
        {
            this.SeedDust.UpdateDust();
            this.SeedDust.DrawDust();
            this.SeedParticleSystem.Update();
            this.SeedParticleSystem.Draw(spriteBatch);
        }
References Terraria.Graphics.Renderers.ParticleRenderer.Draw(), Terraria.GameContent.UI.UIDust.DrawDust(), Terraria.GameContent.UI.States.UIWorldCreation.SeedDust, Terraria.GameContent.UI.States.UIWorldCreation.SeedParticleSystem, Terraria.Graphics.Renderers.ParticleRenderer.Update(), and Terraria.GameContent.UI.UIDust.UpdateDust().
Referenced by Terraria.GameContent.UI.States.UIWorldCreation.Draw(), and Terraria.GameContent.UI.States.UIWorldCreationAdvanced.Draw().