Terraria Decompiled: Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail
ProcessHighDetail()
void Terraria.GameContent.RGB.PirateInvasionShader.ProcessHighDetail (RgbDevice device, Fragment fragment, EffectDetailLevel quality, float time) inline private
Definition at line 33 of file PirateInvasionShader.cs.
        {
            for (int i = 0; i < fragment.Count; i++)
            {
                Point gridPositionOfIndex = fragment.GetGridPositionOfIndex(i);
                Vector2 canvasPositionOfIndex = fragment.GetCanvasPositionOfIndex(i);
                gridPositionOfIndex.X /= 2;
                float num = (NoiseHelper.GetStaticNoise(gridPositionOfIndex.X) * 40f + time * 1f) % 40f;
                float num2 = 0f;
                float num3 = num - canvasPositionOfIndex.Y / 1.2f;
                if (num > 1f)
                {
                    float num4 = 1f - canvasPositionOfIndex.Y / 1.2f;
                    num2 = (1f - Math.Min(1f, num3 - num4)) * (1f - Math.Min(1f, num4 / 1f));
                }
                Vector4 vector = this._backgroundColor;
                if (num3 > 0f)
                {
                    float num5 = Math.Max(0f, 1.2f - num3 * 4f);
                    if (num3 < 0.1f)
                    {
                        num5 = num3 / 0.1f;
                    }
                    vector = Vector4.Lerp(vector, this._cannonBallColor, num5);
                    vector = Vector4.Lerp(vector, this._splashColor, num2);
                }
                if (canvasPositionOfIndex.Y > 0.8f)
                {
                    vector = this._waterColor;
                }
                fragment.SetColor(i, vector);
            }
        }
References Terraria.GameContent.RGB.PirateInvasionShader._backgroundColor, Terraria.GameContent.RGB.PirateInvasionShader._cannonBallColor, Terraria.GameContent.RGB.PirateInvasionShader._splashColor, Terraria.GameContent.RGB.PirateInvasionShader._waterColor, ReLogic.Peripherals.RGB.Fragment.Count, ReLogic.Peripherals.RGB.Fragment.GetCanvasPositionOfIndex(), ReLogic.Peripherals.RGB.Fragment.GetGridPositionOfIndex(), Terraria.GameContent.RGB.NoiseHelper.GetStaticNoise(), Microsoft.Xna.Framework.Vector4.Lerp(), System.Math.Max(), System.Math.Min(), ReLogic.Peripherals.RGB.Fragment.SetColor(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Vector2.Y.