Terraria Decompiled: Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ChasePlayerTop
ChasePlayerTop()
void Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.ChasePlayerTop (int frameCount) inline private
Definition at line 1657 of file AmbientSky.cs.
            {
                Vector2 vector = Main.LocalPlayer.Center + new Vector2(0f, -500f) - this.Position;
                if (vector.Length() >= 100f)
                {
                    this.Velocity.X = this.Velocity.X + 0.1f * (float)Math.Sign(vector.X);
                    this.Velocity.Y = this.Velocity.Y + 0.1f * (float)Math.Sign(vector.Y);
                    this.Velocity = Vector2.Clamp(this.Velocity, new Vector2(-18f), new Vector2(18f));
                }
            }
References Microsoft.Xna.Framework.Vector2.Clamp(), Microsoft.Xna.Framework.Vector2.Length(), Terraria.GameContent.Skies.AmbientSky.SkyEntity.Position, System.Math.Sign(), Microsoft.Xna.Framework.Graphics.Vector2, Terraria.GameContent.Skies.AmbientSky.FadingSkyEntity.Velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.UpdateVelocity().