Terraria Decompiled: Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.EOCSkyEntity
EOCSkyEntity()
Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.EOCSkyEntity (Player player, FastRandom random) inline
Definition at line 1585 of file AmbientSky.cs.
            {
                VirtualCamera virtualCamera = new VirtualCamera(player);
                this.Texture = Main.Assets.Request<Texture2D>("Images/Backgrounds/Ambience/EOC", 1);
                this.Frame = new SpriteFrame(1, 3);
                this.Depth = random.NextFloat() * 3f + 4.5f;
                if (random.Next(4) != 0)
                {
                    this.BeginZigZag(ref random, virtualCamera, (random.Next(2) == 1) ? 1 : (-1));
                }
                else
                {
                    this.BeginChasingPlayer(ref random, virtualCamera);
                }
                base.SetPositionInWorldBasedOnScreenSpace(this.Position);
                this.OpacityNormalizedTimeToFadeIn = 0.1f;
                this.OpacityNormalizedTimeToFadeOut = 0.9f;
                this.BrightnessLerper = 0.2f;
                this.FinalOpacityMultiplier = 1f;
                this.FramingSpeed = 5;
            }
References Terraria.Main.Assets, Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.BeginChasingPlayer(), Terraria.GameContent.Skies.AmbientSky.EOCSkyEntity.BeginZigZag(), Terraria.Utilities.FastRandom.Next(), Terraria.Utilities.FastRandom.NextFloat(), and Terraria.GameContent.Skies.AmbientSky.SkyEntity.Position.