Terraria Decompiled: Terraria.GameContent.UI.Elements.UIImage.DrawSelf
DrawSelf()
override void Terraria.GameContent.UI.Elements.UIImage.DrawSelf (SpriteBatch spriteBatch) inline protected virtual
Reimplemented from Terraria.UI.UIElement.
Reimplemented in Terraria.GameContent.UI.Elements.UIImageWithBorder.
Definition at line 64 of file UIImage.cs.
        {
            CalculatedStyle dimensions = base.GetDimensions();
            Texture2D texture2D = null;
            if (this._texture != null)
            {
                texture2D = this._texture.Value;
            }
            if (this._nonReloadingTexture != null)
            {
                texture2D = this._nonReloadingTexture;
            }
            if (this.ScaleToFit)
            {
                spriteBatch.Draw(texture2D, dimensions.ToRectangle(), this.Frame, this.Color);
                return;
            }
            Vector2 vector = texture2D.Size();
            Vector2 vector2 = new Vector2(dimensions.Width, dimensions.Height);
            if (this.UseTextureSizeForOrigin)
            {
                vector2 = vector;
            }
            Vector2 vector3 = dimensions.Position() + vector2 * (1f - this.ImageScale) / 2f + vector2 * this.NormalizedOrigin;
            if (this.RemoveFloatingPointsFromDrawPosition)
            {
                vector3 = vector3.Floor();
            }
            spriteBatch.Draw(texture2D, vector3, this.Frame, this.Color, this.Rotation, vector * this.NormalizedOrigin, this.ImageScale, SpriteEffects.None, 0f);
        }
References Terraria.GameContent.UI.Elements.UIImage._nonReloadingTexture, Terraria.GameContent.UI.Elements.UIImage._texture, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.UI.Elements.UIImage.Frame, Terraria.UI.CalculatedStyle.Height, Terraria.GameContent.UI.Elements.UIImage.ImageScale, Terraria.GameContent.UI.Elements.UIImage.NormalizedOrigin, Terraria.UI.CalculatedStyle.Position(), Terraria.GameContent.UI.Elements.UIImage.RemoveFloatingPointsFromDrawPosition, Terraria.GameContent.UI.Elements.UIImage.Rotation, Terraria.GameContent.UI.Elements.UIImage.ScaleToFit, Terraria.UI.CalculatedStyle.ToRectangle(), Terraria.GameContent.UI.Elements.UIImage.UseTextureSizeForOrigin, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.UI.CalculatedStyle.Width.