Terraria Decompiled: System.Security.Cryptography.CryptoStream.d__37.MoveNext
MoveNext()
void IAsyncStateMachine. System.Security.Cryptography.CryptoStream.d__37.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 709 of file CryptoStream.cs.
            {
                int num2;
                int num = num2;
                CryptoStream cryptoStream = this;
                int result;
                try
                {
                    ForceAsyncAwaiter forceAsyncAwaiter;
                    if (num != 0)
                    {
                        if (num == 1)
{
                            goto IL_008A;
                        }
                        semaphore = cryptoStream.AsyncActiveSemaphore;
                        forceAsyncAwaiter = semaphore.WaitAsync().ForceAsync().GetAwaiter();
                        if (!forceAsyncAwaiter.IsCompleted)
{
                            num = (num2 = 0);
                            ForceAsyncAwaiter forceAsyncAwaiter2 = forceAsyncAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ForceAsyncAwaiter, CryptoStream.<ReadAsyncInternal>d__37>(ref forceAsyncAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        ForceAsyncAwaiter forceAsyncAwaiter2;
                        forceAsyncAwaiter = forceAsyncAwaiter2;
                        forceAsyncAwaiter2 = default(ForceAsyncAwaiter);
                        num = (num2 = -1);
                    }
                    forceAsyncAwaiter.GetResult();
                    IL_008A:
                    try
                    {
                        TaskAwaiter<int> taskAwaiter;
                        if (num != 1)
{
                            taskAwaiter = cryptoStream.ReadAsyncCore(buffer, offset, count, cancellationToken, true).GetAwaiter();
                            if (!taskAwaiter.IsCompleted)
{
                                num = (num2 = 1);
                                TaskAwaiter<int> taskAwaiter2 = taskAwaiter;
                                this.<>t__builder.AwaitUnsafeOnCompleted<TaskAwaiter<int>, CryptoStream.<ReadAsyncInternal>d__37>(ref taskAwaiter, ref this);
                                return;
                            }
                        }
                        else
{
                            TaskAwaiter<int> taskAwaiter2;
                            taskAwaiter = taskAwaiter2;
                            taskAwaiter2 = default(TaskAwaiter<int>);
                            num = (num2 = -1);
                        }
                        result = taskAwaiter.GetResult();
                    }
                    finally
                    {
                        if (num < 0)
{
                            semaphore.Release();
                        }
                    }
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    semaphore = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                num2 = -2;
                semaphore = null;
                this.<>t__builder.SetResult(result);
            }
References System.Security.Cryptography.CryptoStream.AsyncActiveSemaphore, System.count, System.Threading.Tasks.ForceAsyncAwaiter.GetAwaiter(), System.Threading.Tasks.Task< TResult >.GetAwaiter(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.GetResult(), System.Threading.Tasks.ForceAsyncAwaiter.GetResult(), System.Runtime.CompilerServices.TaskAwaiter< TResult >.IsCompleted, System.Threading.Tasks.ForceAsyncAwaiter.IsCompleted, System.offset, System.Security.Cryptography.CryptoStream.ReadAsyncCore(), and System.Security.Cryptography.CryptoStream.ReadAsyncInternal().