Terraria Decompiled: System.Runtime.Serialization.SerializationInfo.IsAssemblyNameAssignmentSafe
IsAssemblyNameAssignmentSafe()
static bool System.Runtime.Serialization.SerializationInfo.IsAssemblyNameAssignmentSafe (string originalAssemblyName, string newAssemblyName) inline static package
Definition at line 136 of file SerializationInfo.cs.
        {
            if (originalAssemblyName == newAssemblyName)
            {
                return true;
            }
            AssemblyName assemblyName = new AssemblyName(originalAssemblyName);
            AssemblyName assemblyName2 = new AssemblyName(newAssemblyName);
            return !string.Equals(assemblyName2.Name, "mscorlib", StringComparison.OrdinalIgnoreCase) && !string.Equals(assemblyName2.Name, "mscorlib.dll", StringComparison.OrdinalIgnoreCase) && SerializationInfo.Compare(assemblyName.GetPublicKeyToken(), assemblyName2.GetPublicKeyToken());
        }
References System.Runtime.Serialization.SerializationInfo.AssemblyName, System.Runtime.Serialization.SerializationInfo.Compare(), System.Reflection.AssemblyName.GetPublicKeyToken(), and System.Reflection.AssemblyName.Name.
Referenced by System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.CheckTypeForwardedFrom(), and System.Runtime.Serialization.SerializationInfo.DemandForUnsafeAssemblyNameAssignments().