Terraria Decompiled: System.Runtime.Serialization.SerializationInfo.GetValue
GetValue()
object System.Runtime.Serialization.SerializationInfo.GetValue (string name, Type type) inline
Definition at line 399 of file SerializationInfo.cs.
        {
            if (type == null)
            {
                throw new ArgumentNullException("type");
            }
            RuntimeType runtimeType = type as RuntimeType;
            if (runtimeType == null)
            {
                throw new ArgumentException(Environment.GetResourceString("Type must be a runtime Type object."));
            }
            Type type2;
            object element = this.GetElement(name, out type2);
            if (RemotingServices.IsTransparentProxy(element))
            {
                if (RemotingServices.ProxyCheckCast(RemotingServices.GetRealProxy(element), runtimeType))
                {
                    return element;
                }
            }
            else if (type2 == type || type.IsAssignableFrom(type2) || element == null)
            {
                return element;
            }
            return this.m_converter.Convert(element, type);
        }
References System.Runtime.Serialization.IFormatterConverter.Convert(), System.Runtime.Serialization.SerializationInfo.GetElement(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Environment.GetResourceString(), System.Type.IsAssignableFrom(), System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.Runtime.Serialization.SerializationInfo.m_converter, and System.Runtime.Remoting.RemotingServices.ProxyCheckCast().
Referenced by System.Reflection.AssemblyName.AssemblyName(), System.Collections.Generic.Dictionary< TKey, TValue >.OnDeserialization(), System.Collections.Hashtable.OnDeserialization(), and System.Security.Principal.WindowsIdentity.OnDeserialization().