Terraria Decompiled: System.Runtime.Serialization.SerializationInfo.GetElement
GetElement()
object System.Runtime.Serialization.SerializationInfo.GetElement (string name, out Type foundType) inline private
Definition at line 372 of file SerializationInfo.cs.
        {
            int num = this.FindElement(name);
            if (num == -1)
            {
                throw new SerializationException(Environment.GetResourceString("Member '{0}' was not found.", new object[] { name }));
            }
            foundType = this.m_types[num];
            return this.m_data[num];
        }
References System.Runtime.Serialization.SerializationInfo.FindElement(), System.Environment.GetResourceString(), System.Runtime.Serialization.SerializationInfo.m_data, and System.Runtime.Serialization.SerializationInfo.m_types.
Referenced by System.Runtime.Serialization.SerializationInfo.GetBoolean(), System.Runtime.Serialization.SerializationInfo.GetByte(), System.Runtime.Serialization.SerializationInfo.GetChar(), System.Runtime.Serialization.SerializationInfo.GetDateTime(), System.Runtime.Serialization.SerializationInfo.GetDecimal(), System.Runtime.Serialization.SerializationInfo.GetDouble(), System.Runtime.Serialization.SerializationInfo.GetInt16(), System.Runtime.Serialization.SerializationInfo.GetInt32(), System.Runtime.Serialization.SerializationInfo.GetInt64(), System.Runtime.Serialization.SerializationInfo.GetSByte(), System.Runtime.Serialization.SerializationInfo.GetSingle(), System.Runtime.Serialization.SerializationInfo.GetString(), System.Runtime.Serialization.SerializationInfo.GetUInt16(), System.Runtime.Serialization.SerializationInfo.GetUInt32(), System.Runtime.Serialization.SerializationInfo.GetUInt64(), and System.Runtime.Serialization.SerializationInfo.GetValue().