Terraria Decompiled: System.Runtime.Serialization.SerializationInfo.GetString
GetString()
string System.Runtime.Serialization.SerializationInfo.GetString (string name) inline
Definition at line 624 of file SerializationInfo.cs.
        {
            Type type;
            object element = this.GetElement(name, out type);
            if (type == typeof(string) || element == null)
            {
                return (string)element;
            }
            return this.m_converter.ToString(element);
        }
References System.Runtime.Serialization.SerializationInfo.GetElement(), System.Runtime.Serialization.SerializationInfo.m_converter, and System.Runtime.Serialization.IFormatterConverter.ToString().
Referenced by System.Reflection.AssemblyName.AssemblyName(), System.Security.Claims.ClaimsPrincipal.Deserialize(), System.Security.Claims.ClaimsIdentity.Deserialize(), and System.Security.Principal.WindowsIdentity.OnDeserialization().