Terraria Decompiled: System.Runtime.Serialization.SerializationInfo.FindElement
FindElement()
int System.Runtime.Serialization.SerializationInfo.FindElement (string name) inline private
Definition at line 357 of file SerializationInfo.cs.
        {
            if (name == null)
            {
                throw new ArgumentNullException("name");
            }
            int num;
            if (this.m_nameToIndex.TryGetValue(name, out num))
            {
                return num;
            }
            return -1;
        }
References System.Runtime.Serialization.SerializationInfo.m_nameToIndex, System.name, and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().
Referenced by System.Runtime.Serialization.SerializationInfo.GetElement(), System.Runtime.Serialization.SerializationInfo.GetElementNoThrow(), and System.Runtime.Serialization.SerializationInfo.UpdateValue().