Terraria Decompiled: System.Threading.Timer.Scheduler.FireTimer
FireTimer()
void System.Threading.Timer.Scheduler.FireTimer (Timer timer) inline private
Definition at line 367 of file Timer.cs.
            {
                long period_ms = timer.period_ms;
                long due_time_ms = timer.due_time_ms;
                if (period_ms == -1L || ((period_ms == 0L || period_ms == -1L) && due_time_ms != -1L))
                {
                    timer.next_run = long.MaxValue;
                    timer.is_dead = true;
                }
                else
                {
                    timer.next_run = Timer.GetTimeMonotonic() + 10000L * timer.period_ms;
                    timer.is_dead = false;
                }
                ThreadPool.UnsafeQueueUserWorkItem(new WaitCallback(Timer.Scheduler.TimerCB), timer);
            }
References System.Threading.Timer.due_time_ms, System.Threading.Timer.GetTimeMonotonic(), System.L, System.Threading.Timer.period_ms, System.Threading.Timer.Scheduler.TimerCB(), System.Threading.ThreadPool.UnsafeQueueUserWorkItem(), and System.Threading.WaitCallback().
Referenced by System.Threading.Timer.Scheduler.RunSchedulerLoop().