Terraria Decompiled: System.Threading.Timer.Scheduler.RunSchedulerLoop
RunSchedulerLoop()
int System.Threading.Timer.Scheduler.RunSchedulerLoop () inline private
Definition at line 385 of file Timer.cs.
            {
                long timeMonotonic = Timer.GetTimeMonotonic();
                Timer.TimerComparer timerComparer = default(Timer.TimerComparer);
                if (this.needReSort)
                {
                    this.list.Sort(timerComparer);
                    this.needReSort = false;
                }
                long num = long.MaxValue;
                for (int i = 0; i < this.list.Count; i++)
                {
                    Timer timer = this.list[i];
                    if (!timer.is_dead)
                    {
                        if (timer.next_run <= timeMonotonic)
{
                            this.FireTimer(timer);
                        }
                        num = Math.Min(num, timer.next_run);
                        if (timer.next_run > timeMonotonic && timer.next_run < 9223372036854775807L)
{
                            timer.is_dead = false;
                        }
                    }
                }
                for (int i = 0; i < this.list.Count; i++)
                {
                    Timer timer2 = this.list[i];
                    if (timer2.is_dead)
                    {
                        timer2.is_added = false;
                        this.needReSort = true;
                        this.list[i] = this.list[this.list.Count - 1];
                        i--;
                        this.list.RemoveAt(this.list.Count - 1);
                        if (this.list.Count == 0)
{
                            break;
                        }
                    }
                }
                if (this.needReSort)
                {
                    this.list.Sort(timerComparer);
                    this.needReSort = false;
                }
                int num2 = -1;
                this.current_next_run = num;
                if (num != 9223372036854775807L)
                {
                    long num3 = (num - Timer.GetTimeMonotonic()) / 10000L;
                    if (num3 > 2147483647L)
                    {
                        num2 = 2147483646;
                    }
                    else
                    {
                        num2 = (int)num3;
                        if (num2 < 0)
{
                            num2 = 0;
                        }
                    }
                }
                return num2;
            }
References System.Threading.Timer.Scheduler.FireTimer(), System.Threading.Timer.GetTimeMonotonic(), int, System.Threading.Timer.is_dead, System.L, System.Threading.Timer.Scheduler.list, System.Math.Min(), System.Threading.Timer.Scheduler.needReSort, and System.Threading.Timer.next_run.
Referenced by System.Threading.Timer.Scheduler.SchedulerThread().