Terraria Decompiled: System.Threading.Timer.Scheduler.SchedulerThread
SchedulerThread()
void System.Threading.Timer.Scheduler.SchedulerThread () inline private
Definition at line 261 of file Timer.cs.
            {
                Thread.CurrentThread.Name = "Timer-Scheduler";
                for (;;)
                {
                    int num = -1;
                    lock (this)
                    {
                        this.changed.Reset();
                        num = this.RunSchedulerLoop();
                    }
                    this.changed.WaitOne(num);
                }
            }
References System.Threading.Timer.Scheduler.changed, System.Threading.EventWaitHandle.Reset(), System.Threading.Timer.Scheduler.RunSchedulerLoop(), and System.Threading.WaitHandle.WaitOne().
Referenced by System.Threading.Timer.Scheduler.InitScheduler().