Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList
UpdateWorldsList()
void Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList () inline private
Definition at line 146 of file UIWorldSelect.cs.
        {
            this._worldList.Clear();
            IEnumerable<WorldFileData> enumerable = Main.WorldList.OrderByDescending(new Func<WorldFileData, bool>(UIWorldSelect.CanWorldBeJoinedByActivePlayer)).ThenByDescending(new Func<WorldFileData, bool>(UIWorldSelect.IsNewlyGenerated)).ThenByDescending((WorldFileData x) => x.IsFavorite)
                .ThenByDescending(new Func<WorldFileData, bool>(UIWorldSelect.HasWorldBeenPlayedByActivePlayer))
                .ThenByDescending((WorldFileData x) => x.LastPlayed)
                .ThenBy((WorldFileData x) => x.Name)
                .ThenBy((WorldFileData x) => x.GetFileName(true));
            int num = 0;
            foreach (WorldFileData worldFileData in enumerable)
            {
                this._worldList.Add(new UIWorldListItem(worldFileData, num++, UIWorldSelect.CanWorldBeJoinedByActivePlayer(worldFileData), UIWorldSelect.HasWorldBeenPlayedByActivePlayer(worldFileData), UIWorldSelect.IsNewlyGenerated(worldFileData)));
            }
        }
References Terraria.GameContent.UI.States.UIWorldSelect._worldList, Terraria.GameContent.UI.Elements.UIList.Add(), Terraria.GameContent.UI.States.UIWorldSelect.CanWorldBeJoinedByActivePlayer(), Terraria.GameContent.UI.Elements.UIList.Clear(), Terraria.IO.FileData.GetFileName(), Terraria.GameContent.UI.States.UIWorldSelect.HasWorldBeenPlayedByActivePlayer(), Terraria.IO.FileData.IsFavorite, Terraria.GameContent.UI.States.UIWorldSelect.IsNewlyGenerated(), Terraria.IO.WorldFileData.LastPlayed, Terraria.IO.FileData.Name, and Terraria.Main.WorldList.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.OnActivate(), and Terraria.GameContent.UI.States.UIWorldSelect.UpdateFavoritesCache().