Terraria Decompiled: Terraria.GameContent.UI.States.UIWorldSelect.UpdateFavoritesCache
UpdateFavoritesCache()
bool Terraria.GameContent.UI.States.UIWorldSelect.UpdateFavoritesCache () inline private
Definition at line 200 of file UIWorldSelect.cs.
        {
            List<WorldFileData> list = new List<WorldFileData>(Main.WorldList);
            list.Sort(delegate(WorldFileData x, WorldFileData y)
            {
                if (x.IsFavorite && !y.IsFavorite)
                {
                    return -1;
                }
                if (!x.IsFavorite && y.IsFavorite)
                {
                    return 1;
                }
                if (x.Name == null)
                {
                    return 1;
                }
                if (x.Name.CompareTo(y.Name) != 0)
                {
                    return x.Name.CompareTo(y.Name);
                }
                return x.GetFileName(true).CompareTo(y.GetFileName(true));
            });
            bool flag = false;
            if (!flag && list.Count != this.favoritesCache.Count)
            {
                flag = true;
            }
            if (!flag)
            {
                for (int i = 0; i < this.favoritesCache.Count; i++)
                {
                    Tuple<string, bool> tuple = this.favoritesCache[i];
                    if (!(list[i].Name == tuple.Item1) || list[i].IsFavorite != tuple.Item2)
                    {
                        flag = true;
                        break;
                    }
                }
            }
            if (flag)
            {
                this.favoritesCache.Clear();
                foreach (WorldFileData worldFileData in list)
                {
                    this.favoritesCache.Add(Tuple.Create<string, bool>(worldFileData.Name, worldFileData.IsFavorite));
                }
                this.UpdateWorldsList();
            }
            return flag;
        }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, Terraria.GameContent.UI.States.UIWorldSelect.favoritesCache, Terraria.IO.FileData.GetFileName(), Terraria.IO.FileData.IsFavorite, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item1, System.Tuple< T1, T2, T3, T4, T5, T6, T7, TRest >.Item2, System.list, System.Name, Terraria.IO.FileData.Name, Terraria.GameContent.UI.States.UIWorldSelect.UpdateWorldsList(), and Terraria.Main.WorldList.
Referenced by Terraria.GameContent.UI.States.UIWorldSelect.Draw().