Terraria Decompiled: Newtonsoft.Json.Linq.JProperty.WriteTo
WriteTo()
override void Newtonsoft.Json.Linq.JProperty.WriteTo (JsonWriter writer, params JsonConverter[] converters) inline
Definition at line 201 of file JProperty.cs.
        {
            writer.WritePropertyName(this._name);
            JToken value = this.Value;
            if (value != null)
            {
                value.WriteTo(writer, converters);
                return;
            }
            writer.WriteNull();
        }
References Newtonsoft.Json.Linq.JProperty._name, System.value, Newtonsoft.Json.Linq.JProperty.Value, Newtonsoft.Json.JsonWriter.WriteNull(), Newtonsoft.Json.JsonWriter.WritePropertyName(), and Newtonsoft.Json.Linq.JToken.WriteTo().