Terraria Decompiled: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush
LocalPush()
void System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPush (IThreadPoolWorkItem obj) inline
Definition at line 316 of file ThreadPoolWorkQueue.cs.
            {
                int num = this.m_tailIndex;
                if (num == 2147483647)
                {
                    bool flag = false;
                    try
                    {
                        this.m_foreignLock.Enter(ref flag);
                        if (this.m_tailIndex == 2147483647)
{
                            this.m_headIndex &= this.m_mask;
                            num = (this.m_tailIndex &= this.m_mask);
                        }
                    }
                    finally
                    {
                        if (flag)
{
                            this.m_foreignLock.Exit(true);
                        }
                    }
                }
                if (num < this.m_headIndex + this.m_mask)
                {
                    Volatile.Write<IThreadPoolWorkItem>(ref this.m_array[num & this.m_mask], obj);
                    this.m_tailIndex = num + 1;
                    return;
                }
                bool flag2 = false;
                try
                {
                    this.m_foreignLock.Enter(ref flag2);
                    int headIndex = this.m_headIndex;
                    int num2 = this.m_tailIndex - this.m_headIndex;
                    if (num2 >= this.m_mask)
                    {
                        IThreadPoolWorkItem[] array = new IThreadPoolWorkItem[this.m_array.Length << 1];
                        for (int i = 0; i < this.m_array.Length; i++)
{
                            array[i] = this.m_array[(i + headIndex) & this.m_mask];
                        }
                        this.m_array = array;
                        this.m_headIndex = 0;
                        num = (this.m_tailIndex = num2);
                        this.m_mask = (this.m_mask << 1) | 1;
                    }
                    Volatile.Write<IThreadPoolWorkItem>(ref this.m_array[num & this.m_mask], obj);
                    this.m_tailIndex = num + 1;
                }
                finally
                {
                    if (flag2)
                    {
                        this.m_foreignLock.Exit(false);
                    }
                }
            }
References System.array, System.Threading.SpinLock.Enter(), System.Threading.SpinLock.Exit(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_array, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_foreignLock, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_mask, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex, System.obj, and System.Threading.Volatile.Write().