Terraria Decompiled: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal
TrySteal() [2/2]
bool System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.TrySteal (out IThreadPoolWorkItem obj, ref bool missedSteal, int millisecondsTimeout) inline private
Definition at line 486 of file ThreadPoolWorkQueue.cs.
            {
                obj = null;
                while (this.m_headIndex < this.m_tailIndex)
                {
                    bool flag = false;
                    try
                    {
                        this.m_foreignLock.TryEnter(millisecondsTimeout, ref flag);
                        if (flag)
{
                            int headIndex = this.m_headIndex;
                            Interlocked.Exchange(ref this.m_headIndex, headIndex + 1);
                            if (headIndex < this.m_tailIndex)
{
                                int num = headIndex & this.m_mask;
                                obj = Volatile.Read<IThreadPoolWorkItem>(ref this.m_array[num]);
                                if (obj == null)
{
                                    continue;
                                }
                                this.m_array[num] = null;
                                return true;
                            }
                            else
{
                                this.m_headIndex = headIndex;
                                obj = null;
                                missedSteal = true;
                            }
                        }
                        else
{
                            missedSteal = true;
                        }
                    }
                    finally
                    {
                        if (flag)
{
                            this.m_foreignLock.Exit(false);
                        }
                    }
                    return false;
                }
                return false;
            }
References System.Threading.Interlocked.Exchange(), System.Threading.SpinLock.Exit(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_array, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_foreignLock, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_mask, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex, System.obj, System.Threading.Volatile.Read(), and System.Threading.SpinLock.TryEnter().