Terraria Decompiled: System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop
LocalPop()
bool System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalPop (out IThreadPoolWorkItem obj) inline
Definition at line 419 of file ThreadPoolWorkQueue.cs.
            {
                int num3;
                for (;;)
                {
                    int num = this.m_tailIndex;
                    if (this.m_headIndex >= num)
                    {
                        break;
                    }
                    num--;
                    Interlocked.Exchange(ref this.m_tailIndex, num);
                    if (this.m_headIndex > num)
                    {
                        bool flag = false;
                        bool flag2;
                        try
{
                            this.m_foreignLock.Enter(ref flag);
                            if (this.m_headIndex <= num)
{
                                int num2 = num & this.m_mask;
                                obj = Volatile.Read<IThreadPoolWorkItem>(ref this.m_array[num2]);
                                if (obj == null)
{
                                    continue;
                                }
                                this.m_array[num2] = null;
                                flag2 = true;
                            }
                            else
{
                                this.m_tailIndex = num + 1;
                                obj = null;
                                flag2 = false;
                            }
                        }
                        finally
{
                            if (flag)
{
                                this.m_foreignLock.Exit(false);
                            }
                        }
                        return flag2;
                    }
                    num3 = num & this.m_mask;
                    obj = Volatile.Read<IThreadPoolWorkItem>(ref this.m_array[num3]);
                    if (obj != null)
                    {
                        goto Block_2;
                    }
                }
                obj = null;
                return false;
                Block_2:
                this.m_array[num3] = null;
                return true;
            }
References System.Threading.SpinLock.Enter(), System.Threading.Interlocked.Exchange(), System.Threading.SpinLock.Exit(), System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_array, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_foreignLock, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_headIndex, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_mask, System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.m_tailIndex, System.obj, and System.Threading.Volatile.Read().
Referenced by System.Threading.ThreadPoolWorkQueue.Dequeue(), and System.Threading.ThreadPoolWorkQueue.WorkStealingQueue.LocalFindAndPop().