Terraria Decompiled: System.IO.FileStream.WriteInternal
WriteInternal()
void System.IO.FileStream.WriteInternal (byte[] src, int offset, int count) inline private
Definition at line 665 of file FileStream.cs.
        {
            if (count > this.buf_size)
            {
                this.FlushBuffer();
                if (this.CanSeek && !this.isExposed)
                {
                    MonoIOError monoIOError;
                    MonoIO.Seek(this.safeHandle, this.buf_start, SeekOrigin.Begin, out monoIOError);
                    if (monoIOError != MonoIOError.ERROR_SUCCESS)
                    {
                        throw MonoIO.GetException(this.GetSecureFileName(this.name), monoIOError);
                    }
                }
                int i = count;
                while (i > 0)
                {
                    MonoIOError monoIOError;
                    int num = MonoIO.Write(this.safeHandle, src, offset, i, out monoIOError);
                    if (monoIOError != MonoIOError.ERROR_SUCCESS)
                    {
                        throw MonoIO.GetException(this.GetSecureFileName(this.name), monoIOError);
                    }
                    i -= num;
                    offset += num;
                }
                this.buf_start += (long)count;
                return;
            }
            int num2 = 0;
            while (count > 0)
            {
                int num3 = this.WriteSegment(src, offset + num2, count);
                num2 += num3;
                count -= num3;
                if (count == 0)
                {
                    break;
                }
                this.FlushBuffer();
            }
        }
References System.IO.FileStream.buf_size, System.IO.FileStream.buf_start, System.IO.FileStream.CanSeek, System.count, System.IO.FileStream.FlushBuffer(), System.IO.MonoIO.GetException(), System.IO.FileStream.GetSecureFileName(), System.IO.FileStream.isExposed, long, System.IO.FileStream.name, System.offset, System.IO.FileStream.safeHandle, System.IO.MonoIO.Seek(), System.IO.MonoIO.Write(), and System.IO.FileStream.WriteSegment().
Referenced by System.IO.FileStream.BeginWrite(), and System.IO.FileStream.Write().