Terraria Decompiled: System.IO.FileStream.Read
Read()
override int System.IO.FileStream.Read ([Out] byte[] array, int offset, int count) inline
Definition at line 507 of file FileStream.cs.
        {
            if (this.safeHandle.IsClosed)
            {
                throw new ObjectDisposedException("Stream has been closed");
            }
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (!this.CanRead)
            {
                throw new NotSupportedException("Stream does not support reading");
            }
            int num = array.Length;
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "< 0");
            }
            if (count < 0)
            {
                throw new ArgumentOutOfRangeException("count", "< 0");
            }
            if (offset > num)
            {
                throw new ArgumentException("destination offset is beyond array size");
            }
            if (offset > num - count)
            {
                throw new ArgumentException("Reading would overrun buffer");
            }
            if (this.async)
            {
                IAsyncResult asyncResult = this.BeginRead(array, offset, count, null, null);
                return this.EndRead(asyncResult);
            }
            return this.ReadInternal(array, offset, count);
        }
References System.array, System.IO.FileStream.async, System.IO.FileStream.BeginRead(), System.IO.FileStream.CanRead, System.count, System.IO.FileStream.EndRead(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.offset, System.IO.FileStream.ReadInternal(), and System.IO.FileStream.safeHandle.
Referenced by System.TimeZoneInfo.CompareTimeZoneFile(), System.Reflection.Emit.AssemblyBuilder.EmbedResourceFile(), System.Security.Policy.Hash.GetData(), Terraria.Utilities.FileUtilities.Read(), System.IO.File.ReadAllBytes(), System.IO.File.ReadAllBytesUnknownLength(), System.Reflection.StrongNameKeyPair.StrongNameKeyPair(), and System.TermInfoReader.TermInfoReader().