Terraria Decompiled: System.IO.FileStream.Unlock
Unlock()
virtual void System.IO.FileStream.Unlock (long position, long length) inline virtual
Definition at line 896 of file FileStream.cs.
        {
            if (this.safeHandle.IsClosed)
            {
                throw new ObjectDisposedException("Stream has been closed");
            }
            if (position < 0L)
            {
                throw new ArgumentOutOfRangeException("position must not be negative");
            }
            if (length < 0L)
            {
                throw new ArgumentOutOfRangeException("length must not be negative");
            }
            MonoIOError monoIOError;
            MonoIO.Unlock(this.safeHandle, position, length, out monoIOError);
            if (monoIOError != MonoIOError.ERROR_SUCCESS)
            {
                throw MonoIO.GetException(this.GetSecureFileName(this.name), monoIOError);
            }
        }
References System.IO.MonoIO.GetException(), System.IO.FileStream.GetSecureFileName(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.L, System.length, System.IO.FileStream.name, System.IO.FileStream.safeHandle, and System.IO.MonoIO.Unlock().