Terraria Decompiled: System.IO.FileStream.InitBuffer
InitBuffer()
void System.IO.FileStream.InitBuffer (int size, bool isZeroSize) inline private
Definition at line 1120 of file FileStream.cs.
        {
            if (isZeroSize)
            {
                size = 0;
                this.buf = new byte[1];
            }
            else
            {
                if (size <= 0)
                {
                    throw new ArgumentOutOfRangeException("bufferSize", "Positive number required.");
                }
                size = Math.Max(size, 8);
                if (size <= 4096 && FileStream.buf_recycle != null)
                {
                    object obj = FileStream.buf_recycle_lock;
                    lock (obj)
                    {
                        if (FileStream.buf_recycle != null)
{
                            this.buf = FileStream.buf_recycle;
                            FileStream.buf_recycle = null;
                        }
                    }
                }
                if (this.buf == null)
                {
                    this.buf = new byte[size];
                }
                else
                {
                    Array.Clear(this.buf, 0, size);
                }
            }
            this.buf_size = size;
        }
References System.IO.FileStream.buf, System.IO.FileStream.buf_recycle, System.IO.FileStream.buf_recycle_lock, System.Array.Clear(), System.Math.Max(), and System.obj.
Referenced by System.IO.FileStream.ExposeHandle(), and System.IO.FileStream.FileStream().