Terraria Decompiled: System.IO.FileStream.Init
Init()
void System.IO.FileStream.Init (SafeFileHandle safeHandle, FileAccess access, bool ownsHandle, int bufferSize, bool isAsync, bool isConsoleWrapper) inline private
Definition at line 236 of file FileStream.cs.
        {
            if (!isConsoleWrapper && safeHandle.IsInvalid)
            {
                throw new ArgumentException(Environment.GetResourceString("Invalid handle."), "handle");
            }
            if (access < FileAccess.Read || access > FileAccess.ReadWrite)
            {
                throw new ArgumentOutOfRangeException("access");
            }
            if (!isConsoleWrapper && bufferSize <= 0)
            {
                throw new ArgumentOutOfRangeException("bufferSize", Environment.GetResourceString("Positive number required."));
            }
            MonoIOError monoIOError;
            MonoFileType fileType = MonoIO.GetFileType(safeHandle, out monoIOError);
            if (monoIOError != MonoIOError.ERROR_SUCCESS)
            {
                throw MonoIO.GetException(this.name, monoIOError);
            }
            if (fileType == MonoFileType.Unknown)
            {
                throw new IOException("Invalid handle.");
            }
            if (fileType == MonoFileType.Disk)
            {
                this.canseek = true;
            }
            else
            {
                this.canseek = false;
            }
            this.safeHandle = safeHandle;
            this.ExposeHandle();
            this.access = access;
            this.owner = ownsHandle;
            this.async = isAsync;
            this.anonymous = false;
            if (this.canseek)
            {
                this.buf_start = MonoIO.Seek(safeHandle, 0L, SeekOrigin.Current, out monoIOError);
                if (monoIOError != MonoIOError.ERROR_SUCCESS)
                {
                    throw MonoIO.GetException(this.name, monoIOError);
                }
            }
            this.append_startpos = 0L;
        }
References System.IO.FileStream.access, System.IO.FileStream.canseek, System.IO.FileStream.ExposeHandle(), System.IO.MonoIO.GetException(), System.IO.MonoIO.GetFileType(), System.Environment.GetResourceString(), Microsoft.Win32.SafeHandles.SafeHandleZeroOrMinusOneIsInvalid.IsInvalid, System.L, System.IO.FileStream.name, System.IO.FileStream.safeHandle, and System.IO.MonoIO.Seek().
Referenced by System.IO.FileStream.FileStream(), and System.IO.FileStream.FileStream().