Terraria Decompiled: System.IO.FileStream.ReadSegment
ReadSegment()
int System.IO.FileStream.ReadSegment (byte[] dest, int dest_offset, int count) inline private
Definition at line 1019 of file FileStream.cs.
        {
            count = Math.Min(count, this.buf_length - this.buf_offset);
            if (count > 0)
            {
                Buffer.InternalBlockCopy(this.buf, this.buf_offset, dest, dest_offset, count);
                this.buf_offset += count;
            }
            return count;
        }
References System.IO.FileStream.buf, System.IO.FileStream.buf_length, System.IO.FileStream.buf_offset, System.count, System.Buffer.InternalBlockCopy(), and System.Math.Min().
Referenced by System.IO.FileStream.ReadInternal().