Terraria Decompiled: System.IO.FileStream.Seek
Seek()
override long System.IO.FileStream.Seek (long offset, SeekOrigin origin) inline
Definition at line 772 of file FileStream.cs.
        {
            if (this.safeHandle.IsClosed)
            {
                throw new ObjectDisposedException("Stream has been closed");
            }
            if (!this.CanSeek)
            {
                throw new NotSupportedException("The stream does not support seeking");
            }
            long num;
            switch (origin)
            {
            case SeekOrigin.Begin:
                num = offset;
                break;
            case SeekOrigin.Current:
                num = this.Position + offset;
                break;
            case SeekOrigin.End:
                num = this.Length + offset;
                break;
            default:
                throw new ArgumentException("origin", "Invalid SeekOrigin");
            }
            if (num < 0L)
            {
                throw new IOException("Attempted to Seek before the beginning of the stream");
            }
            if (num < this.append_startpos)
            {
                throw new IOException("Can't seek back over pre-existing data in append mode");
            }
            this.FlushBuffer();
            MonoIOError monoIOError;
            this.buf_start = MonoIO.Seek(this.safeHandle, num, SeekOrigin.Begin, out monoIOError);
            if (monoIOError != MonoIOError.ERROR_SUCCESS)
            {
                throw MonoIO.GetException(this.GetSecureFileName(this.name), monoIOError);
            }
            return this.buf_start;
        }
References System.IO.FileStream.append_startpos, System.IO.FileStream.buf_start, System.IO.FileStream.CanSeek, System.IO.FileStream.FlushBuffer(), System.IO.MonoIO.GetException(), System.IO.FileStream.GetSecureFileName(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.L, System.IO.FileStream.name, System.offset, System.IO.FileStream.safeHandle, and System.IO.MonoIO.Seek().
Referenced by System.IO.FileStream.FileStream(), and Terraria.WorldBuilding.WorldGenSnapshot.ResaveForCurrentVersion().