Terraria Decompiled: System.IO.FileStream.BeginWrite
BeginWrite()
override IAsyncResult System.IO.FileStream.BeginWrite (byte[] array, int offset, int numBytes, AsyncCallback userCallback, object stateObject) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 709 of file FileStream.cs.
        {
            if (this.safeHandle.IsClosed)
            {
                throw new ObjectDisposedException("Stream has been closed");
            }
            if (!this.CanWrite)
            {
                throw new NotSupportedException("This stream does not support writing");
            }
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (numBytes < 0)
            {
                throw new ArgumentOutOfRangeException("numBytes", "Must be >= 0");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Must be >= 0");
            }
            if (numBytes > array.Length - offset)
            {
                throw new ArgumentException("array too small. numBytes/offset wrong.");
            }
            if (!this.async)
            {
                return base.BeginWrite(array, offset, numBytes, userCallback, stateObject);
            }
            FileStreamAsyncResult fileStreamAsyncResult = new FileStreamAsyncResult(userCallback, stateObject);
            fileStreamAsyncResult.BytesRead = -1;
            fileStreamAsyncResult.Count = numBytes;
            fileStreamAsyncResult.OriginalCount = numBytes;
            return new FileStream.WriteDelegate(this.WriteInternal).BeginInvoke(array, offset, numBytes, userCallback, stateObject);
        }
References System.array, System.IO.FileStream.async, System.IO.FileStream.CanWrite, System.Runtime.InteropServices.SafeHandle.IsClosed, System.offset, System.IO.FileStream.safeHandle, System.IO.FileStream.WriteDelegate(), and System.IO.FileStream.WriteInternal().
Referenced by System.IO.FileStream.Write().