Terraria Decompiled: System.IO.FileStream.FileStream
FileStream() [19/20]
System.IO.FileStream.FileStream (string path, FileMode mode, FileAccess access, FileShare share, int bufferSize, bool anonymous, FileOptions options) inline package
Definition at line 140 of file FileStream.cs.
        {
            this.name = "[Unknown]";
            base..ctor();
            if (path == null)
            {
                throw new ArgumentNullException("path");
            }
            if (path.Length == 0)
            {
                throw new ArgumentException("Path is empty");
            }
            this.anonymous = anonymous;
            share &= ~FileShare.Inheritable;
            if (bufferSize <= 0)
            {
                throw new ArgumentOutOfRangeException("bufferSize", "Positive number required.");
            }
            if (mode < FileMode.CreateNew || mode > FileMode.Append)
            {
                throw new ArgumentOutOfRangeException("mode", "Enum value was out of legal range.");
            }
            if (access < FileAccess.Read || access > FileAccess.ReadWrite)
            {
                throw new ArgumentOutOfRangeException("access", "Enum value was out of legal range.");
            }
            if ((share < FileShare.None) || share > (FileShare.Read | FileShare.Write | FileShare.Delete))
            {
                throw new ArgumentOutOfRangeException("share", "Enum value was out of legal range.");
            }
            if (path.IndexOfAny(Path.InvalidPathChars) != -1)
            {
                throw new ArgumentException("Name has invalid chars");
            }
            path = Path.InsecureGetFullPath(path);
            if (Directory.Exists(path))
            {
                throw new UnauthorizedAccessException(string.Format(Locale.GetText("Access to the path '{0}' is denied."), this.GetSecureFileName(path, false)));
            }
            if (mode == FileMode.Append && (access & FileAccess.Read) == FileAccess.Read)
            {
                throw new ArgumentException("Append access can be requested only in write-only mode.");
            }
            if ((access & FileAccess.Write) == (FileAccess)0 && mode != FileMode.Open && mode != FileMode.OpenOrCreate)
            {
                throw new ArgumentException(string.Format(Locale.GetText("Combining FileMode: {0} with FileAccess: {1} is invalid."), access, mode));
            }
            string directoryName = Path.GetDirectoryName(path);
            if (directoryName.Length > 0 && !Directory.Exists(Path.GetFullPath(directoryName)))
            {
                string text = Locale.GetText("Could not find a part of the path \"{0}\".");
                string text2 = (anonymous ? directoryName : Path.GetFullPath(path));
                throw new DirectoryNotFoundException(string.Format(text, text2));
            }
            if (!anonymous)
            {
                this.name = path;
            }
            MonoIOError monoIOError;
            IntPtr intPtr = MonoIO.Open(path, mode, access, share, options, out monoIOError);
            if (intPtr == MonoIO.InvalidHandle)
            {
                throw MonoIO.GetException(this.GetSecureFileName(path), monoIOError);
            }
            this.safeHandle = new SafeFileHandle(intPtr, false);
            this.access = access;
            this.owner = true;
            if (MonoIO.GetFileType(this.safeHandle, out monoIOError) == MonoFileType.Disk)
            {
                this.canseek = true;
                this.async = (options & FileOptions.Asynchronous) > FileOptions.None;
            }
            else
            {
                this.canseek = false;
                this.async = false;
            }
            if (access == FileAccess.Read && this.canseek && bufferSize == 4096)
            {
                long length = this.Length;
                if ((long)bufferSize > length)
                {
                    bufferSize = (int)((length < 1000L) ? 1000L : length);
                }
            }
            this.InitBuffer(bufferSize, false);
            if (mode == FileMode.Append)
            {
                this.Seek(0L, SeekOrigin.End);
                this.append_startpos = this.Position;
                return;
            }
            this.append_startpos = 0L;
        }
References System.IO.FileStream.access, System.IO.FileStream.anonymous, System.IO.Directory.Exists(), System.Format, System.IO.Path.GetDirectoryName(), System.IO.MonoIO.GetException(), System.IO.MonoIO.GetFileType(), System.IO.Path.GetFullPath(), System.IO.FileStream.GetSecureFileName(), Locale.GetText(), System.IO.FileStream.InitBuffer(), System.IO.Path.InsecureGetFullPath(), int, System.IO.MonoIO.InvalidHandle, System.IO.Path.InvalidPathChars, System.L, System.length, System.IO.FileStream.Length, System.mode, System.IO.MonoIO.Open(), System.options, System.IO.FileStream.Position, System.IO.FileStream.SafeFileHandle, System.IO.FileStream.Seek(), and System.text.