Terraria Decompiled: System.IO.FileStream.Dispose
Dispose()
override void System.IO.FileStream.Dispose (bool disposing) inline protected virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 925 of file FileStream.cs.
        {
            Exception ex = null;
            if (this.safeHandle != null && !this.safeHandle.IsClosed)
            {
                try
                {
                    this.FlushBuffer();
                }
                catch (Exception ex)
                {
                }
                if (this.owner)
                {
                    MonoIOError monoIOError;
                    MonoIO.Close(this.safeHandle.DangerousGetHandle(), out monoIOError);
                    if (monoIOError != MonoIOError.ERROR_SUCCESS)
                    {
                        throw MonoIO.GetException(this.GetSecureFileName(this.name), monoIOError);
                    }
                    this.safeHandle.DangerousRelease();
                }
            }
            this.canseek = false;
            this.access = (FileAccess)0;
            if (disposing && this.buf != null)
            {
                if (this.buf.Length == 4096 && FileStream.buf_recycle == null)
                {
                    object obj = FileStream.buf_recycle_lock;
                    lock (obj)
                    {
                        if (FileStream.buf_recycle == null)
{
                            FileStream.buf_recycle = this.buf;
                        }
                    }
                }
                this.buf = null;
                GC.SuppressFinalize(this);
            }
            if (ex != null)
            {
                throw ex;
            }
        }
References System.IO.FileStream.buf, System.IO.FileStream.buf_recycle, System.IO.FileStream.buf_recycle_lock, System.IO.MonoIO.Close(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), System.IO.FileStream.FlushBuffer(), System.IO.MonoIO.GetException(), System.IO.FileStream.GetSecureFileName(), System.Runtime.InteropServices.SafeHandle.IsClosed, System.IO.FileStream.name, System.obj, System.IO.FileStream.owner, System.IO.FileStream.safeHandle, and System.GC.SuppressFinalize().
Referenced by System.IO.File.AppendAllTextAsync(), System.IO.File.InternalReadAllBytesUnknownLengthAsync(), System.IO.File.ReadAllBytesAsync(), and System.IO.File.WriteAllTextAsync().