Terraria Decompiled: System.IO.FileStream.BeginRead
BeginRead()
override IAsyncResult System.IO.FileStream.BeginRead (byte[] array, int offset, int numBytes, AsyncCallback userCallback, object stateObject) inline virtual
Reimplemented from System.IO.Stream.
Reimplemented in System.IO.IsolatedStorage.IsolatedStorageFileStream.
Definition at line 571 of file FileStream.cs.
        {
            if (this.safeHandle.IsClosed)
            {
                throw new ObjectDisposedException("Stream has been closed");
            }
            if (!this.CanRead)
            {
                throw new NotSupportedException("This stream does not support reading");
            }
            if (array == null)
            {
                throw new ArgumentNullException("array");
            }
            if (numBytes < 0)
            {
                throw new ArgumentOutOfRangeException("numBytes", "Must be >= 0");
            }
            if (offset < 0)
            {
                throw new ArgumentOutOfRangeException("offset", "Must be >= 0");
            }
            if (numBytes > array.Length - offset)
            {
                throw new ArgumentException("Buffer too small. numBytes/offset wrong.");
            }
            if (!this.async)
            {
                return base.BeginRead(array, offset, numBytes, userCallback, stateObject);
            }
            return new FileStream.ReadDelegate(this.ReadInternal).BeginInvoke(array, offset, numBytes, userCallback, stateObject);
        }
References System.array, System.IO.FileStream.async, System.IO.FileStream.CanRead, System.Runtime.InteropServices.SafeHandle.IsClosed, System.offset, System.IO.FileStream.ReadDelegate(), System.IO.FileStream.ReadInternal(), and System.IO.FileStream.safeHandle.
Referenced by System.IO.FileStream.Read().