Terraria Decompiled: System.IO.FileStream.RefillBuffer
RefillBuffer()
void System.IO.FileStream.RefillBuffer () inline private
Definition at line 1093 of file FileStream.cs.
        {
            this.FlushBuffer();
            this.buf_length = this.ReadData(this.safeHandle, this.buf, 0, this.buf_size);
        }
References System.IO.FileStream.buf, System.IO.FileStream.buf_size, System.IO.FileStream.FlushBuffer(), System.Security.AccessControl.ReadData, and System.IO.FileStream.safeHandle.
Referenced by System.IO.FileStream.ReadByte(), and System.IO.FileStream.ReadInternal().