Terraria Decompiled: Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.TryGettingBackgroundImageProvider
TryGettingBackgroundImageProvider()
Asset< Texture2D > Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.TryGettingBackgroundImageProvider (BestiaryEntry entry) inline private
Definition at line 115 of file UIBestiaryEntryButton.cs.
        {
            IEnumerable<IBestiaryBackgroundImagePathAndColorProvider> enumerable = from x in entry.Info
                where x is IBestiaryBackgroundImagePathAndColorProvider
                select x as IBestiaryBackgroundImagePathAndColorProvider;
            IEnumerable<IPreferenceProviderElement> preferences = entry.Info.OfType<IPreferenceProviderElement>();
            foreach (IBestiaryBackgroundImagePathAndColorProvider bestiaryBackgroundImagePathAndColorProvider in enumerable.Where((IBestiaryBackgroundImagePathAndColorProvider provider) => preferences.Any((IPreferenceProviderElement preference) => preference.Matches(provider))))
            {
                Asset<Texture2D> asset = bestiaryBackgroundImagePathAndColorProvider.GetBackgroundImage();
                if (asset != null)
                {
                    return asset;
                }
            }
            foreach (IBestiaryBackgroundImagePathAndColorProvider bestiaryBackgroundImagePathAndColorProvider2 in enumerable)
            {
                Asset<Texture2D> asset = bestiaryBackgroundImagePathAndColorProvider2.GetBackgroundImage();
                if (asset != null)
                {
                    return asset;
                }
            }
            return null;
        }
References Terraria.GameContent.Bestiary.IBestiaryBackgroundImagePathAndColorProvider.GetBackgroundImage(), Terraria.GameContent.Bestiary.BestiaryEntry.Info, and Terraria.GameContent.Bestiary.IPreferenceProviderElement.Matches().
Referenced by Terraria.GameContent.UI.Elements.UIBestiaryEntryButton.UIBestiaryEntryButton().