Terraria Decompiled: System.Runtime.Remoting.RemotingServices.InternalExecuteMessage
InternalExecuteMessage()
static IMethodReturnMessage System.Runtime.Remoting.RemotingServices.InternalExecuteMessage (MarshalByRefObject target, IMethodCallMessage reqMsg) inline static package
Definition at line 64 of file RemotingServices.cs.
        {
            Type type = target.GetType();
            MethodBase methodBase;
            if (reqMsg.MethodBase.DeclaringType == type || reqMsg.MethodBase == RemotingServices.FieldSetterMethod || reqMsg.MethodBase == RemotingServices.FieldGetterMethod)
            {
                methodBase = reqMsg.MethodBase;
            }
            else
            {
                methodBase = RemotingServices.GetVirtualMethod(type, reqMsg.MethodBase);
                if (methodBase == null)
                {
                    throw new RemotingException(string.Format("Cannot resolve method {0}:{1}", type, reqMsg.MethodName));
                }
            }
            if (reqMsg.MethodBase.IsGenericMethod)
            {
                Type[] genericArguments = reqMsg.MethodBase.GetGenericArguments();
                methodBase = ((MethodInfo)methodBase).GetGenericMethodDefinition().MakeGenericMethod(genericArguments);
            }
            LogicalCallContext logicalCallContext = CallContext.SetLogicalCallContext(reqMsg.LogicalCallContext);
            ReturnMessage returnMessage;
            try
            {
                object[] array;
                object obj = RemotingServices.InternalExecute(methodBase, target, reqMsg.Args, out array);
                ParameterInfo[] parameters = methodBase.GetParameters();
                object[] array2 = new object[parameters.Length];
                int num = 0;
                int num2 = 0;
                foreach (ParameterInfo parameterInfo in parameters)
                {
                    if (parameterInfo.IsOut && !parameterInfo.ParameterType.IsByRef)
                    {
                        array2[num++] = reqMsg.GetArg(parameterInfo.Position);
                    }
                    else if (parameterInfo.ParameterType.IsByRef)
                    {
                        array2[num++] = array[num2++];
                    }
                    else
                    {
                        array2[num++] = null;
                    }
                }
                LogicalCallContext logicalCallContext2 = Thread.CurrentThread.GetMutableExecutionContext().LogicalCallContext;
                returnMessage = new ReturnMessage(obj, array2, num, logicalCallContext2, reqMsg);
            }
            catch (Exception ex)
            {
                returnMessage = new ReturnMessage(ex, reqMsg);
            }
            CallContext.SetLogicalCallContext(logicalCallContext);
            return returnMessage;
        }
References System.Runtime.Remoting.Messaging.IMethodMessage.Args, System.array, System.Threading.Thread.CurrentThread, System.Reflection.MemberInfo.DeclaringType, System.Runtime.Remoting.RemotingServices.FieldGetterMethod, System.Runtime.Remoting.RemotingServices.FieldSetterMethod, System.Format, System.Runtime.Remoting.Messaging.IMethodMessage.GetArg(), System.Reflection.MethodBase.GetGenericArguments(), System.Threading.Thread.GetMutableExecutionContext(), System.Reflection.MethodBase.GetParameters(), System.Runtime.Remoting.RemotingServices.GetVirtualMethod(), System.Runtime.Remoting.RemotingServices.InternalExecute(), System.Type.IsByRef, System.Reflection.MethodBase.IsGenericMethod, System.Reflection.ParameterInfo.IsOut, System.Runtime.Remoting.Messaging.IMethodMessage.LogicalCallContext, System.Threading.ExecutionContext.LogicalCallContext, System.Runtime.Remoting.Messaging.IMethodMessage.MethodBase, System.Runtime.Remoting.Messaging.IMethodMessage.MethodName, System.obj, System.Reflection.ParameterInfo.ParameterType, System.Reflection.ParameterInfo.Position, and System.Runtime.Remoting.Messaging.CallContext.SetLogicalCallContext().
Referenced by System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage(), System.Runtime.Remoting.Messaging.StackBuilderSink.ExecuteAsyncMessage(), System.Runtime.Remoting.RemotingServices.ExecuteMessage(), and System.Runtime.Remoting.Messaging.StackBuilderSink.SyncProcessMessage().