Terraria Decompiled: System.Runtime.Remoting.RemotingServices.GetMethodBaseFromMethodMessage
GetMethodBaseFromMethodMessage()
static MethodBase System.Runtime.Remoting.RemotingServices.GetMethodBaseFromMethodMessage (IMethodMessage msg) inline static
Definition at line 350 of file RemotingServices.cs.
        {
            Type type = Type.GetType(msg.TypeName);
            if (type == null)
            {
                throw new RemotingException("Type '" + msg.TypeName + "' not found.");
            }
            return RemotingServices.GetMethodBaseFromName(type, msg.MethodName, (Type[])msg.MethodSignature);
        }
References System.Runtime.Remoting.RemotingServices.GetMethodBaseFromName(), System.Type.GetType(), System.Runtime.Remoting.Messaging.IMethodMessage.MethodName, System.Runtime.Remoting.Messaging.IMethodMessage.MethodSignature, and System.Runtime.Remoting.Messaging.IMethodMessage.TypeName.
Referenced by System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod().