Terraria Decompiled: System.Runtime.Remoting.RemotingServices.GetOrCreateClientIdentity
GetOrCreateClientIdentity()
static ClientIdentity System.Runtime.Remoting.RemotingServices.GetOrCreateClientIdentity (ObjRef objRef, Type proxyType, out object clientProxy) inline static package
Definition at line 645 of file RemotingServices.cs.
        {
            object obj = ((objRef.ChannelInfo != null) ? objRef.ChannelInfo.ChannelData : null);
            string uri;
            IMessageSink clientChannelSinkChain = RemotingServices.GetClientChannelSinkChain(objRef.URI, obj, out uri);
            if (uri == null)
            {
                uri = objRef.URI;
            }
            Hashtable hashtable = RemotingServices.uri_hash;
            ClientIdentity clientIdentity2;
            lock (hashtable)
            {
                clientProxy = null;
                string normalizedUri = RemotingServices.GetNormalizedUri(objRef.URI);
                ClientIdentity clientIdentity = RemotingServices.uri_hash[normalizedUri] as ClientIdentity;
                if (clientIdentity != null)
                {
                    clientProxy = clientIdentity.ClientProxy;
                    if (clientProxy != null)
                    {
                        return clientIdentity;
                    }
                    RemotingServices.DisposeIdentity(clientIdentity);
                }
                clientIdentity = new ClientIdentity(uri, objRef);
                clientIdentity.ChannelSink = clientChannelSinkChain;
                RemotingServices.uri_hash[normalizedUri] = clientIdentity;
                if (proxyType != null)
                {
                    RemotingProxy remotingProxy = new RemotingProxy(proxyType, clientIdentity);
                    CrossAppDomainSink crossAppDomainSink = clientChannelSinkChain as CrossAppDomainSink;
                    if (crossAppDomainSink != null)
                    {
                        remotingProxy.SetTargetDomain(crossAppDomainSink.TargetDomainId);
                    }
                    clientProxy = remotingProxy.GetTransparentProxy();
                    clientIdentity.ClientProxy = (MarshalByRefObject)clientProxy;
                }
                clientIdentity2 = clientIdentity;
            }
            return clientIdentity2;
        }
References System.Runtime.Remoting.IChannelInfo.ChannelData, System.Runtime.Remoting.ObjRef.ChannelInfo, System.Runtime.Remoting.ClientIdentity.ClientProxy, System.Runtime.Remoting.RemotingServices.DisposeIdentity(), System.Runtime.Remoting.RemotingServices.GetClientChannelSinkChain(), System.Runtime.Remoting.RemotingServices.GetNormalizedUri(), System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy(), System.obj, System.Runtime.Remoting.Proxies.RealProxy.SetTargetDomain(), System.Runtime.Remoting.Channels.CrossAppDomainSink.TargetDomainId, System.Runtime.Remoting.ObjRef.URI, and System.Runtime.Remoting.RemotingServices.uri_hash.
Referenced by System.Runtime.Remoting.Activation.AppDomainLevelActivator.Activate(), and System.Runtime.Remoting.RemotingServices.GetRemoteObject().