Terraria Decompiled: System.Runtime.Remoting.RemotingServices.DeserializeCallData
DeserializeCallData()
static object System.Runtime.Remoting.RemotingServices.DeserializeCallData (byte[] array) inline static package
Definition at line 811 of file RemotingServices.cs.
        {
            if (array == null)
            {
                return null;
            }
            MemoryStream memoryStream = new MemoryStream(array);
            BinaryFormatter deserializationFormatter = RemotingServices._deserializationFormatter;
            object obj;
            lock (deserializationFormatter)
            {
                obj = RemotingServices._deserializationFormatter.Deserialize(memoryStream);
            }
            if (obj is RemotingServices.CACD)
            {
                RemotingServices.CACD cacd = (RemotingServices.CACD)obj;
                obj = cacd.d;
                LogicalCallContext logicalCallContext = (LogicalCallContext)cacd.c;
                if (logicalCallContext.HasInfo)
                {
                    Thread.CurrentThread.GetMutableExecutionContext().LogicalCallContext.Merge(logicalCallContext);
                }
            }
            return obj;
        }
References System.Runtime.Remoting.RemotingServices._deserializationFormatter, System.array, System.Runtime.Remoting.RemotingServices.CACD.c, System.Threading.Thread.CurrentThread, System.Runtime.Remoting.RemotingServices.CACD.d, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Deserialize(), System.Threading.Thread.GetMutableExecutionContext(), System.Runtime.Remoting.Messaging.LogicalCallContext.HasInfo, System.Threading.ExecutionContext.LogicalCallContext, System.Runtime.Remoting.Messaging.LogicalCallContext.Merge(), and System.obj.