Terraria Decompiled: System.Runtime.Remoting.RemotingServices.Unmarshal
Unmarshal() [2/2]
static object System.Runtime.Remoting.RemotingServices.Unmarshal (ObjRef objectRef, bool fRefine) inline static
Definition at line 210 of file RemotingServices.cs.
        {
            Type type = (fRefine ? objectRef.ServerType : typeof(MarshalByRefObject));
            if (type == null)
            {
                type = typeof(MarshalByRefObject);
            }
            if (objectRef.IsReferenceToWellKnow)
            {
                object remoteObject = RemotingServices.GetRemoteObject(objectRef, type);
                TrackingServices.NotifyUnmarshaledObject(remoteObject, objectRef);
                return remoteObject;
            }
            if (type.IsContextful)
            {
                ProxyAttribute proxyAttribute = (ProxyAttribute)Attribute.GetCustomAttribute(type, typeof(ProxyAttribute), true);
                if (proxyAttribute != null)
                {
                    object transparentProxy = proxyAttribute.CreateProxy(objectRef, type, null, null).GetTransparentProxy();
                    TrackingServices.NotifyUnmarshaledObject(transparentProxy, objectRef);
                    return transparentProxy;
                }
            }
            object proxyForRemoteObject = RemotingServices.GetProxyForRemoteObject(objectRef, type);
            TrackingServices.NotifyUnmarshaledObject(proxyForRemoteObject, objectRef);
            return proxyForRemoteObject;
        }
References System.Runtime.Remoting.Proxies.ProxyAttribute.CreateProxy(), System.Attribute.GetCustomAttribute(), System.Runtime.Remoting.RemotingServices.GetProxyForRemoteObject(), System.Runtime.Remoting.RemotingServices.GetRemoteObject(), System.Runtime.Remoting.Proxies.RealProxy.GetTransparentProxy(), System.Type.IsContextful, System.Runtime.Remoting.ObjRef.IsReferenceToWellKnow, and System.Runtime.Remoting.Services.TrackingServices.NotifyUnmarshaledObject().