Terraria Decompiled: System.Runtime.Remoting.RemotingServices.SerializeCallData
SerializeCallData()
static byte[] System.Runtime.Remoting.RemotingServices.SerializeCallData (object obj) inline static package
Definition at line 785 of file RemotingServices.cs.
        {
            LogicalCallContext.Reader logicalCallContext = Thread.CurrentThread.GetExecutionContextReader().LogicalCallContext;
            if (!logicalCallContext.IsNull)
            {
                obj = new RemotingServices.CACD
                {
                    d = obj,
                    c = logicalCallContext.Clone()
                };
            }
            if (obj == null)
            {
                return null;
            }
            MemoryStream memoryStream = new MemoryStream();
            BinaryFormatter serializationFormatter = RemotingServices._serializationFormatter;
            lock (serializationFormatter)
            {
                RemotingServices._serializationFormatter.Serialize(memoryStream, obj);
            }
            return memoryStream.ToArray();
        }
References System.Runtime.Remoting.RemotingServices._serializationFormatter, System.Runtime.Remoting.Messaging.LogicalCallContext.Reader.Clone(), System.Threading.Thread.CurrentThread, System.Threading.Thread.GetExecutionContextReader(), System.Runtime.Remoting.Messaging.LogicalCallContext.Reader.IsNull, System.Threading.ExecutionContext.LogicalCallContext, System.obj, System.Runtime.Serialization.Formatters.Binary.BinaryFormatter.Serialize(), and System.IO.MemoryStream.ToArray().