Terraria Decompiled: System.Runtime.Remoting.RemotingServices.CreateClientActivatedServerIdentity
CreateClientActivatedServerIdentity()
static ClientActivatedIdentity System.Runtime.Remoting.RemotingServices.CreateClientActivatedServerIdentity (MarshalByRefObject realObject, Type objectType, string objectUri) inline static package
Definition at line 714 of file RemotingServices.cs.
        {
            ClientActivatedIdentity clientActivatedIdentity = new ClientActivatedIdentity(objectUri, objectType);
            clientActivatedIdentity.AttachServerObject(realObject, Context.DefaultContext);
            RemotingServices.RegisterServerIdentity(clientActivatedIdentity);
            clientActivatedIdentity.StartTrackingLifetime((ILease)realObject.InitializeLifetimeService());
            return clientActivatedIdentity;
        }
References System.Runtime.Remoting.ServerIdentity.AttachServerObject(), System.Runtime.Remoting.Contexts.Context.DefaultContext, System.MarshalByRefObject.InitializeLifetimeService(), System.Runtime.Remoting.RemotingServices.RegisterServerIdentity(), and System.Runtime.Remoting.ServerIdentity.StartTrackingLifetime().
Referenced by System.Runtime.Remoting.RemotingServices.Marshal().