Terraria Decompiled: System.Runtime.Remoting.RemotingServices.Marshal
Marshal() [2/3]
static ObjRef System.Runtime.Remoting.RemotingServices.Marshal (MarshalByRefObject Obj, string ObjURI, Type RequestedType) inline static
Definition at line 251 of file RemotingServices.cs.
        {
            if (RemotingServices.IsTransparentProxy(Obj))
            {
                RealProxy realProxy = RemotingServices.GetRealProxy(Obj);
                Identity objectIdentity = realProxy.ObjectIdentity;
                if (objectIdentity != null)
                {
                    if (realProxy.GetProxiedType().IsContextful && !objectIdentity.IsConnected)
                    {
                        ClientActivatedIdentity clientActivatedIdentity = (ClientActivatedIdentity)objectIdentity;
                        if (ObjURI == null)
{
                            ObjURI = RemotingServices.NewUri();
                        }
                        clientActivatedIdentity.ObjectUri = ObjURI;
                        RemotingServices.RegisterServerIdentity(clientActivatedIdentity);
                        clientActivatedIdentity.StartTrackingLifetime((ILease)Obj.InitializeLifetimeService());
                        return clientActivatedIdentity.CreateObjRef(RequestedType);
                    }
                    if (ObjURI != null)
                    {
                        throw new RemotingException("It is not possible marshal a proxy of a remote object.");
                    }
                    ObjRef objRef = realProxy.ObjectIdentity.CreateObjRef(RequestedType);
                    TrackingServices.NotifyMarshaledObject(Obj, objRef);
                    return objRef;
                }
            }
            if (RequestedType == null)
            {
                RequestedType = Obj.GetType();
            }
            if (ObjURI == null)
            {
                if (Obj.ObjectIdentity == null)
                {
                    ObjURI = RemotingServices.NewUri();
                    RemotingServices.CreateClientActivatedServerIdentity(Obj, RequestedType, ObjURI);
                }
            }
            else
            {
                ClientActivatedIdentity clientActivatedIdentity2 = RemotingServices.GetIdentityForUri("/" + ObjURI) as ClientActivatedIdentity;
                if (clientActivatedIdentity2 == null || Obj != clientActivatedIdentity2.GetServerObject())
                {
                    RemotingServices.CreateClientActivatedServerIdentity(Obj, RequestedType, ObjURI);
                }
            }
            ObjRef objRef2;
            if (RemotingServices.IsTransparentProxy(Obj))
            {
                objRef2 = RemotingServices.GetRealProxy(Obj).ObjectIdentity.CreateObjRef(RequestedType);
            }
            else
            {
                objRef2 = Obj.CreateObjRef(RequestedType);
            }
            TrackingServices.NotifyMarshaledObject(Obj, objRef2);
            return objRef2;
        }
References System.Runtime.Remoting.RemotingServices.CreateClientActivatedServerIdentity(), System.MarshalByRefObject.CreateObjRef(), System.Runtime.Remoting.Identity.CreateObjRef(), System.Runtime.Remoting.ServerIdentity.CreateObjRef(), System.Runtime.Remoting.RemotingServices.GetIdentityForUri(), System.Runtime.Remoting.Proxies.RealProxy.GetProxiedType(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Runtime.Remoting.ClientActivatedIdentity.GetServerObject(), System.MarshalByRefObject.InitializeLifetimeService(), System.Runtime.Remoting.Identity.IsConnected, System.Type.IsContextful, System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.Runtime.Remoting.RemotingServices.NewUri(), System.Runtime.Remoting.Services.TrackingServices.NotifyMarshaledObject(), System.MarshalByRefObject.ObjectIdentity, System.Runtime.Remoting.Proxies.RealProxy.ObjectIdentity, System.Runtime.Remoting.RemotingServices.RegisterServerIdentity(), and System.Runtime.Remoting.ServerIdentity.StartTrackingLifetime().