Terraria Decompiled: System.Runtime.Remoting.RemotingServices.Disconnect
Disconnect()
static bool System.Runtime.Remoting.RemotingServices.Disconnect (MarshalByRefObject obj) inline static
Definition at line 146 of file RemotingServices.cs.
        {
            if (obj == null)
            {
                throw new ArgumentNullException("obj");
            }
            ServerIdentity serverIdentity;
            if (RemotingServices.IsTransparentProxy(obj))
            {
                RealProxy realProxy = RemotingServices.GetRealProxy(obj);
                if (!realProxy.GetProxiedType().IsContextful || !(realProxy.ObjectIdentity is ServerIdentity))
                {
                    throw new ArgumentException("The obj parameter is a proxy.");
                }
                serverIdentity = realProxy.ObjectIdentity as ServerIdentity;
            }
            else
            {
                serverIdentity = obj.ObjectIdentity;
                obj.ObjectIdentity = null;
            }
            if (serverIdentity == null || !serverIdentity.IsConnected)
            {
                return false;
            }
            LifetimeServices.StopTrackingLifetime(serverIdentity);
            RemotingServices.DisposeIdentity(serverIdentity);
            TrackingServices.NotifyDisconnectedObject(obj);
            return true;
        }
References System.Runtime.Remoting.RemotingServices.DisposeIdentity(), System.Runtime.Remoting.Proxies.RealProxy.GetProxiedType(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Runtime.Remoting.Identity.IsConnected, System.Type.IsContextful, System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.Runtime.Remoting.Services.TrackingServices.NotifyDisconnectedObject(), System.obj, System.Runtime.Remoting.Proxies.RealProxy.ObjectIdentity, and System.Runtime.Remoting.Lifetime.LifetimeServices.StopTrackingLifetime().