Terraria Decompiled: System.Runtime.Remoting.RemotingServices.NewUri
NewUri()
static string System.Runtime.Remoting.RemotingServices.NewUri () inline static private
Definition at line 314 of file RemotingServices.cs.
        {
            if (RemotingServices.app_id == null)
            {
                object obj = RemotingServices.app_id_lock;
                lock (obj)
                {
                    if (RemotingServices.app_id == null)
                    {
                        RemotingServices.app_id = Guid.NewGuid().ToString().Replace('-', '_') + "/";
                    }
                }
            }
            int num = Interlocked.Increment(ref RemotingServices.next_id);
            return string.Concat(new string[]
            {
                RemotingServices.app_id,
                Environment.TickCount.ToString("x"),
                "_",
                num.ToString(),
                ".rem"
            });
        }
References System.Runtime.Remoting.RemotingServices.app_id, System.Runtime.Remoting.RemotingServices.app_id_lock, System.Threading.Interlocked.Increment(), System.Guid.NewGuid(), System.Runtime.Remoting.RemotingServices.next_id, System.obj, and System.Guid.ToString().
Referenced by System.Runtime.Remoting.RemotingServices.Marshal().