Terraria Decompiled: System.Runtime.Remoting.RemotingServices.IsTransparentProxy
IsTransparentProxy()
static bool System.Runtime.Remoting.RemotingServices.IsTransparentProxy (object proxy)
Referenced by System.Runtime.Remoting.ServerIdentity.AttachServerObject(), System.Runtime.Serialization.ObjectManager.CanCallGetType(), System.DelegateSerializationHolder.DelegateEntry.DeserializeDelegate(), System.Runtime.Remoting.RemotingServices.Disconnect(), System.Runtime.Remoting.RemotingServices.ExecuteMessage(), System.Runtime.Remoting.Channels.ChannelServices.GetChannelSinkProperties(), System.Runtime.Remoting.Contexts.Context.GetDynamicPropertyCollection(), System.Runtime.Remoting.RemotingServices.GetEnvoyChainForProxy(), System.Runtime.Remoting.Messaging.RemotingSurrogate.GetObjectData(), System.Runtime.Serialization.ObjectCloneHelper.GetObjectData(), System.Runtime.Remoting.RemotingServices.GetObjectIdentity(), System.MarshalByRefObject.GetObjectIdentity(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Runtime.Serialization.Formatters.Binary.ObjectWriter.GetType(), System.Runtime.Serialization.SerializationInfo.GetValue(), System.Runtime.Serialization.SerializationInfo.GetValueNoThrow(), System.Runtime.Serialization.Formatters.Binary.WriteObjectInfo.InitSerialize(), System.RuntimeType.InvokeMember(), System.Delegate.IsTransparentProxy(), System.Runtime.Remoting.RemotingServices.Marshal(), System.Runtime.Remoting.Messaging.CADMessageBase.MarshalArgument(), System.Runtime.Remoting.RemotingServices.SetObjectUriForMarshal(), System.Runtime.Remoting.Messaging.StackBuilderSink.StackBuilderSink(), System.Threading.WaitHandle.WaitAll(), and System.Threading.WaitHandle.WaitAny().