Terraria Decompiled: System.Runtime.Remoting.RemotingServices.GetDomainProxy
GetDomainProxy()
static object System.Runtime.Remoting.RemotingServices.GetDomainProxy (AppDomain domain) inline static package
Definition at line 859 of file RemotingServices.cs.
        {
            byte[] array = null;
            Context currentContext = Thread.CurrentContext;
            try
            {
                array = (byte[])AppDomain.InvokeInDomain(domain, typeof(AppDomain).GetMethod("GetMarshalledDomainObjRef", BindingFlags.Instance | BindingFlags.NonPublic), domain, null);
            }
            finally
            {
                AppDomain.InternalSetContext(currentContext);
            }
            byte[] array2 = new byte[array.Length];
            array.CopyTo(array2, 0);
            return (AppDomain)RemotingServices.Unmarshal((ObjRef)CADSerializer.DeserializeObject(new MemoryStream(array2)));
        }
References System.array, System.Threading.Thread.CurrentContext, System.Runtime.Remoting.Channels.CADSerializer.DeserializeObject(), System.AppDomain.InternalSetContext(), System.AppDomain.InvokeInDomain(), and System.Runtime.Remoting.RemotingServices.Unmarshal().
Referenced by System.AppDomain.CreateDomain().