Terraria Decompiled: System.Runtime.Remoting.RemotingServices.GetMethodBaseFromName
GetMethodBaseFromName()
static MethodBase System.Runtime.Remoting.RemotingServices.GetMethodBaseFromName (Type type, string methodName, Type[] signature) inline static package
Definition at line 361 of file RemotingServices.cs.
        {
            if (type.IsInterface)
            {
                return RemotingServices.FindInterfaceMethod(type, methodName, signature);
            }
            MethodBase methodBase;
            if (signature == null)
            {
                methodBase = type.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic);
            }
            else
            {
                methodBase = type.GetMethod(methodName, BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, signature, null);
            }
            if (methodBase != null)
            {
                return methodBase;
            }
            if (methodName == "FieldSetter")
            {
                return RemotingServices.FieldSetterMethod;
            }
            if (methodName == "FieldGetter")
            {
                return RemotingServices.FieldGetterMethod;
            }
            if (signature == null)
            {
                return type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, Type.EmptyTypes, null);
            }
            return type.GetConstructor(BindingFlags.Instance | BindingFlags.Public | BindingFlags.NonPublic, null, signature, null);
        }
References System.Type.EmptyTypes, System.Runtime.Remoting.RemotingServices.FieldGetterMethod, System.Runtime.Remoting.RemotingServices.FieldSetterMethod, System.Runtime.Remoting.RemotingServices.FindInterfaceMethod(), System.Type.GetConstructor(), System.Type.GetMethod(), and System.Type.IsInterface.
Referenced by System.Runtime.Remoting.RemotingServices.GetMethodBaseFromMethodMessage(), and System.Runtime.Remoting.Messaging.MethodCall.ResolveMethod().