Terraria Decompiled: System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity
GetMessageTargetIdentity()
static Identity System.Runtime.Remoting.RemotingServices.GetMessageTargetIdentity (IMessage msg) inline static package
Definition at line 905 of file RemotingServices.cs.
        {
            if (msg is IInternalMessage)
            {
                return ((IInternalMessage)msg).TargetIdentity;
            }
            Hashtable hashtable = RemotingServices.uri_hash;
            Identity identity;
            lock (hashtable)
            {
                string normalizedUri = RemotingServices.GetNormalizedUri(((IMethodMessage)msg).Uri);
                identity = RemotingServices.uri_hash[normalizedUri] as ServerIdentity;
            }
            return identity;
        }
References System.Runtime.Remoting.RemotingServices.GetNormalizedUri(), and System.Runtime.Remoting.RemotingServices.uri_hash.
Referenced by System.Runtime.Remoting.Activation.ActivationServices.Activate(), System.Runtime.Remoting.Contexts.CrossContextChannel.AsyncProcessMessage(), System.Runtime.Remoting.Messaging.ClientContextTerminatorSink.AsyncProcessMessage(), System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.AsyncProcessMessage(), System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.AsyncProcessMessage(), System.Runtime.Remoting.Activation.ActivationServices.CreateInstanceFromMessage(), System.Runtime.Remoting.Lifetime.LeaseSink.RenewLease(), System.Runtime.Remoting.Contexts.CrossContextChannel.SyncProcessMessage(), System.Runtime.Remoting.Messaging.ClientContextTerminatorSink.SyncProcessMessage(), System.Runtime.Remoting.Messaging.ServerContextTerminatorSink.SyncProcessMessage(), and System.Runtime.Remoting.Messaging.ServerObjectTerminatorSink.SyncProcessMessage().