Terraria Decompiled: System.Runtime.Remoting.RemotingServices.SetObjectUriForMarshal
SetObjectUriForMarshal()
static void System.Runtime.Remoting.RemotingServices.SetObjectUriForMarshal (MarshalByRefObject obj, string uri) inline static
Definition at line 523 of file RemotingServices.cs.
        {
            if (RemotingServices.IsTransparentProxy(obj))
            {
                RealProxy realProxy = RemotingServices.GetRealProxy(obj);
                Identity objectIdentity = realProxy.ObjectIdentity;
                if (objectIdentity != null && !(objectIdentity is ServerIdentity) && !realProxy.GetProxiedType().IsContextful)
                {
                    throw new RemotingException("SetObjectUriForMarshal method should only be called for MarshalByRefObjects that exist in the current AppDomain.");
                }
            }
            RemotingServices.Marshal(obj, uri);
        }
References System.Runtime.Remoting.Proxies.RealProxy.GetProxiedType(), System.Runtime.Remoting.RemotingServices.GetRealProxy(), System.Type.IsContextful, System.Runtime.Remoting.RemotingServices.IsTransparentProxy(), System.Runtime.Remoting.RemotingServices.Marshal(), System.obj, and System.Runtime.Remoting.Proxies.RealProxy.ObjectIdentity.