Terraria Decompiled: Terraria.WaterfallManager.FindWaterfalls
FindWaterfalls()
void Terraria.WaterfallManager.FindWaterfalls (bool forced = false) inline
Definition at line 51 of file WaterfallManager.cs.
        {
            this.findWaterfallCount++;
            if (this.findWaterfallCount < 30 && !forced)
            {
                return;
            }
            this.findWaterfallCount = 0;
            TimeLogger.StartTimestamp startTimestamp = TimeLogger.Start();
            this.waterfallDist = (int)(75f * Main.gfxQuality) + 25;
            this.qualityMax = (int)((float)this.maxWaterfallCount * Main.gfxQuality);
            this.currentMax = 0;
            int num = (int)(Main.screenPosition.X / 16f - 1f);
            int num2 = (int)((Main.screenPosition.X + (float)Main.screenWidth) / 16f) + 2;
            int num3 = (int)(Main.screenPosition.Y / 16f - 1f);
            int num4 = (int)((Main.screenPosition.Y + (float)Main.screenHeight) / 16f) + 2;
            num -= this.waterfallDist;
            num2 += this.waterfallDist;
            num3 -= this.waterfallDist;
            num4 += 20;
            if (num < 0)
            {
                num = 0;
            }
            if (num2 > Main.maxTilesX)
            {
                num2 = Main.maxTilesX;
            }
            if (num3 < 0)
            {
                num3 = 0;
            }
            if (num4 > Main.maxTilesY)
            {
                num4 = Main.maxTilesY;
            }
            for (int i = num; i < num2; i++)
            {
                for (int j = num3; j < num4; j++)
                {
                    Tile tile = Main.tile[i, j];
                    if (tile == null)
                    {
                        tile = new Tile();
                        Main.tile[i, j] = tile;
                    }
                    if (tile.active())
                    {
                        if (tile.halfBrick())
{
                            Tile tile2 = Main.tile[i, j - 1];
                            if (tile2 == null)
{
                                tile2 = new Tile();
                                Main.tile[i, j - 1] = tile2;
                            }
                            if (tile2.liquid < 16 || WorldGen.SolidTile(tile2))
{
                                Tile tile3 = Main.tile[i - 1, j];
                                if (tile3 == null)
{
                                    tile3 = new Tile();
                                    Main.tile[i - 1, j] = tile3;
                                }
                                Tile tile4 = Main.tile[i + 1, j];
                                if (tile4 == null)
{
                                    tile4 = new Tile();
                                    Main.tile[i + 1, j] = tile4;
                                }
                                if ((tile3.liquid > 160 || tile4.liquid > 160) && ((tile3.liquid == 0 && !WorldGen.SolidTile(tile3) && tile3.slope() == 0) || (tile4.liquid == 0 && !WorldGen.SolidTile(tile4) && tile4.slope() == 0)) && this.currentMax < this.qualityMax)
{
                                    this.waterfalls[this.currentMax].type = 0;
                                    if (tile2.lava() || tile4.lava() || tile3.lava())
{
                                        this.waterfalls[this.currentMax].type = 1;
                                    }
                                    else if (tile2.honey() || tile4.honey() || tile3.honey())
{
                                        this.waterfalls[this.currentMax].type = 14;
                                    }
                                    else if (tile2.shimmer() || tile4.shimmer() || tile3.shimmer())
{
                                        this.waterfalls[this.currentMax].type = 25;
                                    }
                                    else
{
                                        this.waterfalls[this.currentMax].type = 0;
                                    }
                                    this.waterfalls[this.currentMax].x = i;
                                    this.waterfalls[this.currentMax].y = j;
                                    this.currentMax++;
                                }
                            }
                        }
                        if (tile.type == 196)
{
                            Tile tile5 = Main.tile[i, j + 1];
                            if (tile5 == null)
{
                                tile5 = new Tile();
                                Main.tile[i, j + 1] = tile5;
                            }
                            if (!WorldGen.SolidTile(tile5) && tile5.liquid == 0 && tile5.slope() == 0 && this.currentMax < this.qualityMax)
{
                                this.waterfalls[this.currentMax].type = 11;
                                this.waterfalls[this.currentMax].x = i;
                                this.waterfalls[this.currentMax].y = j + 1;
                                this.currentMax++;
                            }
                        }
                        if (tile.type == 460)
{
                            Tile tile6 = Main.tile[i, j + 1];
                            if (tile6 == null)
{
                                tile6 = new Tile();
                                Main.tile[i, j + 1] = tile6;
                            }
                            if (!WorldGen.SolidTile(tile6) && tile6.liquid == 0 && tile6.slope() == 0 && this.currentMax < this.qualityMax)
{
                                this.waterfalls[this.currentMax].type = 22;
                                this.waterfalls[this.currentMax].x = i;
                                this.waterfalls[this.currentMax].y = j + 1;
                                this.currentMax++;
                            }
                        }
                        if (tile.type == 717)
{
                            Tile tile7 = Main.tile[i, j + 1];
                            if (tile7 == null)
{
                                tile7 = new Tile();
                                Main.tile[i, j + 1] = tile7;
                            }
                            if (!WorldGen.SolidTile(tile7) && tile7.liquid == 0 && tile7.slope() == 0 && this.currentMax < this.qualityMax)
{
                                this.waterfalls[this.currentMax].type = 26;
                                this.waterfalls[this.currentMax].x = i;
                                this.waterfalls[this.currentMax].y = j + 1;
                                this.currentMax++;
                            }
                        }
                    }
                }
            }
            TimeLogger.FindingWaterfalls.AddTime(startTimestamp);
        }
References Terraria.Tile.active(), Terraria.WaterfallManager.currentMax, Terraria.TimeLogger.FindingWaterfalls, Terraria.WaterfallManager.findWaterfallCount, Terraria.Main.gfxQuality, Terraria.Tile.halfBrick(), Terraria.Tile.honey(), int, Terraria.Tile.lava(), Terraria.Tile.liquid, Terraria.Main.maxTilesX, Terraria.Main.maxTilesY, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Terraria.Tile.shimmer(), Terraria.Tile.slope(), Terraria.WorldGen.SolidTile(), Terraria.TimeLogger.Start(), Terraria.Main.tile, Terraria.Tile.type, Terraria.WaterfallManager.waterfallDist, Terraria.WaterfallManager.waterfalls, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.