Terraria Decompiled: Terraria.WaterfallManager.DrawWaterfall
DrawWaterfall() [2/2]
void Terraria.WaterfallManager.DrawWaterfall (int waterfallType, int x, int y, float opacity, Vector2 position, Rectangle sourceRect, Color color, SpriteEffects effects) inline private
Definition at line 909 of file WaterfallManager.cs.
        {
            Texture2D value = this.waterfallTexture[waterfallType].Value;
            if (waterfallType == 25)
            {
                VertexColors vertexColors;
                Lighting.GetCornerColors(x, y, out vertexColors, 1f);
                LiquidRenderer.SetShimmerVertexColors(ref vertexColors, opacity, x, y);
                Main.tileBatch.Draw(value, position + new Vector2(0f, 0f), new Rectangle?(sourceRect), vertexColors, default(Vector2), 1f, effects);
                sourceRect.Y += 42;
                LiquidRenderer.SetShimmerVertexColors_Sparkle(ref vertexColors, opacity, x, y, true);
                Main.tileBatch.Draw(value, position + new Vector2(0f, 0f), new Rectangle?(sourceRect), vertexColors, default(Vector2), 1f, effects);
                return;
            }
            Main.tileBatch.Draw(value, position, new Rectangle?(sourceRect), color, default(Vector2), 1f, effects);
        }
References Terraria.Graphics.TileBatch.Draw(), Terraria.Lighting.GetCornerColors(), Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors(), Terraria.GameContent.Liquid.LiquidRenderer.SetShimmerVertexColors_Sparkle(), Terraria.Main.tileBatch, System.value, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, and Terraria.WaterfallManager.waterfallTexture.