Terraria Decompiled: System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7 >
Combine< T1, T2, T3, T4, T5, T6, T7 >()
static int System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7 > (T1 value1, T2 value2, T3 value3, T4 value4, T5 value5, T6 value6, T7 value7) inline static
Definition at line 103 of file HashCode.cs.
        {
            uint num = (uint)((value1 != null) ? value1.GetHashCode() : 0);
            uint num2 = (uint)((value2 != null) ? value2.GetHashCode() : 0);
            uint num3 = (uint)((value3 != null) ? value3.GetHashCode() : 0);
            uint num4 = (uint)((value4 != null) ? value4.GetHashCode() : 0);
            uint num5 = (uint)((value5 != null) ? value5.GetHashCode() : 0);
            uint num6 = (uint)((value6 != null) ? value6.GetHashCode() : 0);
            uint num7 = (uint)((value7 != null) ? value7.GetHashCode() : 0);
            uint num8;
            uint num9;
            uint num10;
            uint num11;
            HashCode.Initialize(out num8, out num9, out num10, out num11);
            num8 = HashCode.Round(num8, num);
            num9 = HashCode.Round(num9, num2);
            num10 = HashCode.Round(num10, num3);
            num11 = HashCode.Round(num11, num4);
            return (int)HashCode.MixFinal(HashCode.QueueRound(HashCode.QueueRound(HashCode.QueueRound(HashCode.MixState(num8, num9, num10, num11) + 28U, num5), num6), num7));
        }
References System.HashCode.Initialize(), System.HashCode.MixFinal(), System.HashCode.MixState(), System.HashCode.QueueRound(), System.HashCode.Round(), and System.U.