Terraria Decompiled: System.HashCode.MixFinal
MixFinal()
static uint System.HashCode.MixFinal (uint hash) inline static private
Definition at line 201 of file HashCode.cs.
        {
            hash ^= hash >> 15;
            hash *= 2246822519U;
            hash ^= hash >> 13;
            hash *= 3266489917U;
            hash ^= hash >> 16;
            return hash;
        }
References System.U.
Referenced by System.HashCode.Combine< T1 >(), System.HashCode.Combine< T1, T2 >(), System.HashCode.Combine< T1, T2, T3 >(), System.HashCode.Combine< T1, T2, T3, T4 >(), System.HashCode.Combine< T1, T2, T3, T4, T5 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7, T8 >(), and System.HashCode.ToHashCode().