Terraria Decompiled: System.HashCode.MixState
MixState()
static uint System.HashCode.MixState (uint v1, uint v2, uint v3, uint v4) inline static private
Definition at line 188 of file HashCode.cs.
        {
            return HashCode.Rol(v1, 1) + HashCode.Rol(v2, 7) + HashCode.Rol(v3, 12) + HashCode.Rol(v4, 18);
        }
References System.HashCode.Rol().
Referenced by System.HashCode.Combine< T1, T2, T3, T4 >(), System.HashCode.Combine< T1, T2, T3, T4, T5 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7 >(), System.HashCode.Combine< T1, T2, T3, T4, T5, T6, T7, T8 >(), and System.HashCode.ToHashCode().