Terraria Decompiled: Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetTextureName
FNA3D_SetTextureName() [2/2]
static unsafe void Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetTextureName (IntPtr device, IntPtr texture, string text) inline static
Definition at line 352 of file FNA3D.cs.
        {
            byte* ptr = SDL.Utf8EncodeHeap(text);
            FNA3D.FNA3D_SetTextureName(device, texture, ptr);
            Marshal.FreeHGlobal((IntPtr)((void*)ptr));
        }
References Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_SetTextureName(), System.Runtime.InteropServices.Marshal.FreeHGlobal(), System.text, and SDL2.SDL.Utf8EncodeHeap().