Terraria Decompiled: Microsoft.Xna.Framework.Graphics.FNA3D.WriteJPGStream
WriteJPGStream()
static void Microsoft.Xna.Framework.Graphics.FNA3D.WriteJPGStream (Stream stream, int srcW, int srcH, int dstW, int dstH, IntPtr data, int quality) inline static
Definition at line 470 of file FNA3D.cs.
        {
            Dictionary<IntPtr, Stream> dictionary = FNA3D.writeStreams;
            IntPtr intPtr;
            lock (dictionary)
            {
                intPtr = (IntPtr)(FNA3D.writeGlobal++);
                FNA3D.writeStreams.Add(intPtr, stream);
            }
            FNA3D.FNA3D_Image_SaveJPG(FNA3D.writeFunc, intPtr, srcW, srcH, dstW, dstH, data, quality);
            dictionary = FNA3D.writeStreams;
            lock (dictionary)
            {
                FNA3D.writeStreams.Remove(intPtr);
            }
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_Image_SaveJPG(), System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), Microsoft.Xna.Framework.Graphics.FNA3D.writeFunc, Microsoft.Xna.Framework.Graphics.FNA3D.writeGlobal, and Microsoft.Xna.Framework.Graphics.FNA3D.writeStreams.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.SaveAsJpeg().