Terraria Decompiled: Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream
ReadImageStream()
static IntPtr Microsoft.Xna.Framework.Graphics.FNA3D.ReadImageStream (Stream stream, out int width, out int height, out int len, int forceW = -1, int forceH = -1, bool zoom = false) inline static
Definition at line 410 of file FNA3D.cs.
        {
            Dictionary<IntPtr, Stream> dictionary = FNA3D.readStreams;
            IntPtr intPtr;
            lock (dictionary)
            {
                intPtr = (IntPtr)(FNA3D.readGlobal++);
                FNA3D.readStreams.Add(intPtr, stream);
            }
            IntPtr intPtr2 = FNA3D.FNA3D_Image_Load(FNA3D.readFunc, FNA3D.skipFunc, FNA3D.eofFunc, intPtr, out width, out height, out len, forceW, forceH, (zoom > false) ? 1 : 0);
            dictionary = FNA3D.readStreams;
            lock (dictionary)
            {
                FNA3D.readStreams.Remove(intPtr);
            }
            return intPtr2;
        }
References System.Collections.Generic.Dictionary< TKey, TValue >.Add(), System.dictionary, Microsoft.Xna.Framework.Graphics.FNA3D.eofFunc, Microsoft.Xna.Framework.Graphics.FNA3D.FNA3D_Image_Load(), Microsoft.Xna.Framework.Graphics.FNA3D.readFunc, Microsoft.Xna.Framework.Graphics.FNA3D.readGlobal, Microsoft.Xna.Framework.Graphics.FNA3D.readStreams, System.Collections.Generic.Dictionary< TKey, TValue >.Remove(), and Microsoft.Xna.Framework.Graphics.FNA3D.skipFunc.
Referenced by Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Microsoft.Xna.Framework.Graphics.Texture2D.FromStream(), Microsoft.Xna.Framework.SDL2_FNAPlatform.INTERNAL_SetIcon(), Microsoft.Xna.Framework.SDL3_FNAPlatform.INTERNAL_SetIcon(), and Microsoft.Xna.Framework.Graphics.Texture2D.TextureDataFromStreamEXT().