Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.LazyCreateEvent
LazyCreateEvent()
void System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.LazyCreateEvent (ref EventWaitHandle waitEvent, bool makeAutoResetEvent) inline private
Definition at line 882 of file WindowsRuntimeMarshal.cs.
                {
                    this.ExitMyLock();
                    EventWaitHandle eventWaitHandle;
                    if (makeAutoResetEvent)
                    {
                        eventWaitHandle = new AutoResetEvent(false);
                    }
                    else
                    {
                        eventWaitHandle = new ManualResetEvent(false);
                    }
                    this.EnterMyLock();
                    if (waitEvent == null)
                    {
                        waitEvent = eventWaitHandle;
                    }
                }
References System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.EnterMyLock(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ExitMyLock().
Referenced by System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.AcquireReaderLock(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.AcquireWriterLock().