Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ExitAndWakeUpAppropriateWaiters
ExitAndWakeUpAppropriateWaiters()
void System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ExitAndWakeUpAppropriateWaiters () inline private
Definition at line 928 of file WindowsRuntimeMarshal.cs.
                {
                    if (this.owners == 0 && this.numWriteWaiters > 0U)
                    {
                        this.ExitMyLock();
                        this.writeEvent.Set();
                        return;
                    }
                    if (this.owners >= 0 && this.numReadWaiters != 0U)
                    {
                        this.ExitMyLock();
                        this.readEvent.Set();
                        return;
                    }
                    this.ExitMyLock();
                }
References System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ExitMyLock(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.numReadWaiters, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.numWriteWaiters, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.owners, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.readEvent, System.Threading.EventWaitHandle.Set(), System.U, and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.writeEvent.
Referenced by System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ReleaseReaderLock(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ReleaseWriterLock().