Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.WaitOnEvent
WaitOnEvent()
void System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.WaitOnEvent (EventWaitHandle waitEvent, ref uint numWaiters, int millisecondsTimeout) inline private
Definition at line 902 of file WindowsRuntimeMarshal.cs.
                {
                    waitEvent.Reset();
                    numWaiters += 1U;
                    bool flag = false;
                    this.ExitMyLock();
                    try
                    {
                        if (!waitEvent.WaitOne(millisecondsTimeout, false))
{
                            throw new WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.ReaderWriterLockTimedOutException();
                        }
                        flag = true;
                    }
                    finally
                    {
                        this.EnterMyLock();
                        numWaiters -= 1U;
                        if (!flag)
{
                            this.ExitMyLock();
                        }
                    }
                }
References System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.EnterMyLock(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ExitMyLock(), System.Threading.EventWaitHandle.Reset(), System.U, and System.Threading.WaitHandle.WaitOne().
Referenced by System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.AcquireReaderLock(), and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.AcquireWriterLock().