Terraria Decompiled: System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.AcquireReaderLock
AcquireReaderLock()
void System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.AcquireReaderLock (int millisecondsTimeout) inline package
Definition at line 828 of file WindowsRuntimeMarshal.cs.
                {
                    this.EnterMyLock();
                    while (this.owners < 0 || this.numWriteWaiters != 0U)
                    {
                        if (this.readEvent == null)
{
                            this.LazyCreateEvent(ref this.readEvent, false);
                        }
                        else
{
                            this.WaitOnEvent(this.readEvent, ref this.numReadWaiters, millisecondsTimeout);
                        }
                    }
                    this.owners++;
                    this.ExitMyLock();
                }
References System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.EnterMyLock(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.ExitMyLock(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.LazyCreateEvent(), System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.numReadWaiters, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.numWriteWaiters, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.owners, System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.readEvent, System.U, and System.Runtime.InteropServices.WindowsRuntime.WindowsRuntimeMarshal.NativeOrStaticEventRegistrationImpl.MyReaderWriterLock.WaitOnEvent().