Terraria Decompiled: CsvHelper.CsvParser.Read
Read()
virtual string[] CsvHelper.CsvParser.Read () inline virtual
Implements CsvHelper.ICsvParser.
Definition at line 133 of file CsvParser.cs.
        {
            this.CheckDisposed();
            string[] array2;
            try
            {
                if (this.configuration.HasExcelSeparator && !this.hasExcelSeparatorBeenRead)
                {
                    this.ReadExcelSeparator();
                }
                string[] array = this.ReadLine();
                if (this.configuration.DetectColumnCountChanges && array != null && this.FieldCount > 0)
                {
                    if (this.FieldCount == array.Length)
                    {
                        if (!Enumerable.Any<string>(array, (string field) => field == null))
{
                            goto IL_007E;
                        }
                    }
                    throw new CsvBadDataException("An inconsistent number of columns has been detected.");
                }
                IL_007E:
                array2 = array;
            }
            catch (Exception ex)
            {
                ExceptionHelper.AddExceptionDataMessage(ex, this, null, null, default(int?), null);
                throw;
            }
            return array2;
        }
References CsvHelper.ExceptionHelper.AddExceptionDataMessage(), System.array, CsvHelper.CsvParser.CheckDisposed(), CsvHelper.CsvParser.configuration, CsvHelper.Configuration.CsvConfiguration.DetectColumnCountChanges, CsvHelper.CsvParser.FieldCount, CsvHelper.Configuration.CsvConfiguration.HasExcelSeparator, CsvHelper.CsvParser.ReadExcelSeparator(), and CsvHelper.CsvParser.ReadLine().