Terraria Decompiled: CsvHelper.CsvParser.ReadLine
ReadLine()
virtual string[] CsvHelper.CsvParser.ReadLine () inline protected virtual
Definition at line 237 of file CsvParser.cs.
        {
            string text = null;
            int num = this.readerBufferPosition;
            int num2 = this.readerBufferPosition;
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            bool flag5 = false;
            bool flag6 = false;
            int num3 = 0;
            bool flag7 = false;
            int num4 = 0;
            this.record = new string[this.FieldCount];
            this.RawRecord = string.Empty;
            this.currentRow++;
            this.currentRawRow++;
            int num5;
            for (;;)
            {
                if (this.read)
                {
                    this.cPrev = new char?(this.c);
                }
                num5 = this.readerBufferPosition - num;
                this.read = this.GetChar(out this.c, ref num, ref num2, ref text, ref flag3, flag7, ref num4, ref num5, flag4, flag5, flag, false);
                if (!this.read)
                {
                    goto IL_0904;
                }
                this.readerBufferPosition++;
                long num6 = this.CharPosition;
                this.CharPosition = num6 + 1L;
                if (this.configuration.UseExcelLeadingZerosFormatForNumerics)
                {
                    if (this.c == '=' && !flag6)
                    {
                        if (!flag7)
{
                            char? c = this.cPrev;
                            if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 13))
{
                                c = this.cPrev;
                                if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 10) && this.cPrev != null)
{
                                    goto IL_01D3;
                                }
                            }
                        }
                        num5 = this.readerBufferPosition - num;
                        char c2;
                        this.GetChar(out c2, ref num, ref num2, ref text, ref flag3, flag7, ref num4, ref num5, flag4, flag5, flag, true);
                        if (c2 == '"')
{
                            flag6 = true;
                            continue;
                        }
                        goto IL_02ED;
                    }
                    IL_01D3:
                    if (flag6)
                    {
                        if (this.c == '"')
{
                            char? c = this.cPrev;
                            if (((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 61)
{
                                continue;
                            }
                        }
                        if (char.IsDigit(this.c))
{
                            continue;
                        }
                        if (this.c != '"')
{
                            flag6 = false;
                            continue;
                        }
                        char c3;
                        bool @char = this.GetChar(out c3, ref num, ref num2, ref text, ref flag3, flag7, ref num4, ref num5, flag4, flag5, flag, true);
                        if (c3 == this.configuration.Delimiter.get_Chars(0) || c3 == '\r' || c3 == '\n' || c3 == '\0')
{
                            this.AppendField(ref text, num, this.readerBufferPosition - num);
                            this.UpdateBytePosition(num, this.readerBufferPosition - num);
                            text = text.Trim(new char[] { '=', '"' });
                            num = this.readerBufferPosition;
                            if (!@char)
{
                                this.AddFieldToRecord(ref num4, text, ref flag3);
                            }
                            flag6 = false;
                            continue;
                        }
                        continue;
                    }
                }
                IL_02ED:
                if (this.c == this.configuration.Quote && !this.configuration.IgnoreQuotes)
                {
                    if (!flag2)
                    {
                        if (!flag7)
{
                            char? c = this.cPrev;
                            if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 13))
{
                                c = this.cPrev;
                                if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 10) && this.cPrev != null)
{
                                    goto IL_03BD;
                                }
                            }
                        }
                        flag2 = true;
                    }
                    IL_03BD:
                    if (!flag2)
                    {
                        flag3 = true;
                    }
                    else
                    {
                        flag = !flag;
                        if (num != this.readerBufferPosition - 1)
{
                            this.AppendField(ref text, num, this.readerBufferPosition - num - 1);
                            this.UpdateBytePosition(num, this.readerBufferPosition - num);
                        }
                        char? c = this.cPrev;
                        if (((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) != (int)this.configuration.Quote || !flag)
{
                            if (flag)
{
                                goto IL_04AB;
                            }
                            c = this.cPrev;
                            if (((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == (int)this.configuration.Quote || this.readerBufferPosition == 1)
{
                                goto IL_04AB;
                            }
                            IL_04BA:
                            num = this.readerBufferPosition;
                            goto IL_04C1;
                            IL_04AB:
                            this.UpdateBytePosition(num, this.readerBufferPosition - num);
                            goto IL_04BA;
                        }
                        IL_04C1:
                        flag7 = false;
                    }
                }
                else
                {
                    flag7 = false;
                    if (flag2 && flag)
                    {
                        if (this.c != '\r')
{
                            if (this.c != '\n')
{
                                continue;
                            }
                            char? c = this.cPrev;
                            if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) != 13))
{
                                continue;
                            }
                        }
                        this.currentRawRow++;
                    }
                    else
                    {
                        char? c = this.cPrev;
                        if (((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == (int)this.configuration.Quote && !this.configuration.IgnoreQuotes)
{
                            if (this.c != this.configuration.Delimiter.get_Chars(0) && this.c != '\r' && this.c != '\n')
{
                                flag3 = true;
                            }
                            flag2 = false;
                        }
                        if (!flag4 || this.c == '\r' || this.c == '\n')
{
                            if (this.c == this.configuration.Delimiter.get_Chars(0) || flag5)
{
                                if (!flag5)
{
                                    num3 = 0;
                                    this.AppendField(ref text, num, this.readerBufferPosition - num - 1);
                                    this.UpdateBytePosition(num, this.readerBufferPosition - num);
                                    this.AddFieldToRecord(ref num4, text, ref flag3);
                                    num = this.readerBufferPosition;
                                    text = null;
                                    flag5 = true;
                                }
                                if (num3 == this.configuration.Delimiter.Length - 1)
{
                                    this.UpdateBytePosition(num, this.readerBufferPosition - num);
                                    flag5 = false;
                                    flag7 = true;
                                    num = this.readerBufferPosition;
                                }
                                else if (this.configuration.Delimiter.get_Chars(num3) != this.c)
{
                                    num4--;
                                    num -= num3 + 1;
                                    flag5 = false;
                                }
                                else
{
                                    num3++;
                                }
                            }
                            else if (this.c == '\r' || this.c == '\n')
{
                                num5 = this.readerBufferPosition - num - 1;
                                if (this.c == '\r')
{
                                    char c4;
                                    this.GetChar(out c4, ref num, ref num2, ref text, ref flag3, flag7, ref num4, ref num5, flag4, flag5, flag, true);
                                    if (c4 == '\n')
{
                                        this.readerBufferPosition++;
                                        num6 = this.CharPosition;
                                        this.CharPosition = num6 + 1L;
                                    }
                                }
                                c = this.cPrev;
                                bool flag8;
                                if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 13))
{
                                    c = this.cPrev;
                                    flag8 = ((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 10;
                                }
                                else
{
                                    flag8 = true;
                                }
                                if (!flag8 && !flag4 && this.cPrev != null)
{
                                    break;
                                }
                                this.UpdateBytePosition(num, this.readerBufferPosition - num);
                                num = this.readerBufferPosition;
                                flag4 = false;
                                if (!this.configuration.IgnoreBlankLines)
{
                                    goto IL_0904;
                                }
                                this.currentRow++;
                            }
                            else if (this.configuration.AllowComments && this.c == this.configuration.Comment)
{
                                c = this.cPrev;
                                if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 13))
{
                                    c = this.cPrev;
                                    if (!(((c != null) ? new int?((int)c.GetValueOrDefault()) : default(int?)) == 10) && this.cPrev != null)
{
                                        continue;
                                    }
                                }
                                flag4 = true;
                            }
                        }
                    }
                }
            }
            this.AppendField(ref text, num, num5);
            this.UpdateBytePosition(num, this.readerBufferPosition - num);
            this.AddFieldToRecord(ref num4, text, ref flag3);
            IL_0904:
            if (this.record != null)
            {
                this.RawRecord += new string(this.readerBuffer, num2, this.readerBufferPosition - num2);
            }
            return this.record;
        }
References CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.Configuration.CsvConfiguration.AllowComments, CsvHelper.CsvParser.AppendField(), CsvHelper.CsvParser.c, CsvHelper.CsvParser.CharPosition, CsvHelper.CsvParser.configuration, CsvHelper.CsvParser.cPrev, CsvHelper.CsvParser.currentRawRow, CsvHelper.CsvParser.currentRow, CsvHelper.Configuration.CsvConfiguration.Delimiter, CsvHelper.CsvParser.FieldCount, CsvHelper.CsvParser.GetChar(), CsvHelper.Configuration.CsvConfiguration.IgnoreBlankLines, CsvHelper.Configuration.CsvConfiguration.IgnoreQuotes, int, System.L, CsvHelper.Configuration.CsvConfiguration.Quote, CsvHelper.CsvParser.read, CsvHelper.CsvParser.readerBuffer, CsvHelper.CsvParser.readerBufferPosition, CsvHelper.CsvParser.record, System.text, CsvHelper.CsvParser.UpdateBytePosition(), and CsvHelper.Configuration.CsvConfiguration.UseExcelLeadingZerosFormatForNumerics.
Referenced by CsvHelper.CsvParser.Read().