Terraria Decompiled: CsvHelper.CsvParser.GetChar
GetChar()
bool CsvHelper.CsvParser.GetChar (out char ch, ref int fieldStartPosition, ref int rawFieldStartPosition, ref string field, ref bool fieldIsBad, bool prevCharWasDelimiter, ref int recordPosition, ref int fieldLength, bool inComment, bool inDelimiter, bool inQuotes, bool isPeek) inline protected
Definition at line 519 of file CsvParser.cs.
        {
            if (this.readerBufferPosition == this.charsRead)
            {
                if (!inDelimiter && !inComment)
                {
                    this.AppendField(ref field, fieldStartPosition, fieldLength);
                }
                this.UpdateBytePosition(fieldStartPosition, this.readerBufferPosition - fieldStartPosition);
                fieldLength = 0;
                this.RawRecord += new string(this.readerBuffer, rawFieldStartPosition, this.readerBufferPosition - rawFieldStartPosition);
                this.charsRead = this.reader.Read(this.readerBuffer, 0, this.readerBuffer.Length);
                this.readerBufferPosition = 0;
                fieldStartPosition = 0;
                rawFieldStartPosition = 0;
                if (this.charsRead == 0)
                {
                    if (isPeek)
                    {
                        ch = '\0';
                        return false;
                    }
                    if ((this.c != '\r' && this.c != '\n' && this.c != '\0' && !inComment) || inQuotes)
                    {
                        if (prevCharWasDelimiter)
{
                            field = "";
                        }
                        this.AddFieldToRecord(ref recordPosition, field, ref fieldIsBad);
                    }
                    else
                    {
                        this.RawRecord = null;
                        this.record = null;
                    }
                    ch = '\0';
                    return false;
                }
            }
            ch = this.readerBuffer[this.readerBufferPosition];
            return true;
        }
References CsvHelper.CsvParser.AddFieldToRecord(), CsvHelper.CsvParser.AppendField(), CsvHelper.CsvParser.c, CsvHelper.CsvParser.charsRead, System.IO.TextReader.Read(), CsvHelper.CsvParser.reader, CsvHelper.CsvParser.readerBuffer, CsvHelper.CsvParser.readerBufferPosition, and CsvHelper.CsvParser.UpdateBytePosition().
Referenced by CsvHelper.CsvParser.ReadLine().