Terraria Decompiled: System.IO.MonoIO.GetException
GetException() [1/2]
static Exception System.IO.MonoIO.GetException (MonoIOError error) inline static
Definition at line 12 of file MonoIO.cs.
        {
            if (error == MonoIOError.ERROR_ACCESS_DENIED)
            {
                return new UnauthorizedAccessException("Access to the path is denied.");
            }
            if (error != MonoIOError.ERROR_FILE_EXISTS)
            {
                return MonoIO.GetException(string.Empty, error);
            }
            return new IOException("Cannot create a file that already exist.", -2147024816);
        }
References System.IO.MonoIO.GetException().
Referenced by System.IO.FileStream.Dispose(), System.IO.FileStream.FileStream(), System.IO.FileStream.FlushBuffer(), System.IO.DriveInfo.GetDiskFreeSpace(), System.IO.MonoIO.GetException(), System.IO.FileStream.Init(), System.IO.Directory.InsecureGetCurrentDirectory(), System.IO.Directory.InsecureSetCurrentDirectory(), System.IO.FileStream.Lock(), System.IO.FileStream.ReadData(), System.IO.FileStream.Seek(), System.IO.File.SetAttributes(), System.IO.FileStream.SetLength(), System.IO.FileStream.Unlock(), and System.IO.FileStream.WriteInternal().