Terraria Decompiled: System.IO.MonoIO.SetFileTime
SetFileTime() [3/4]
static bool System.IO.MonoIO.SetFileTime (string path, int type, long creation_time, long last_access_time, long last_write_time, DateTime dateTime, out MonoIOError error) inline static
Definition at line 607 of file MonoIO.cs.
        {
            IntPtr intPtr = MonoIO.Open(path, FileMode.Open, FileAccess.ReadWrite, FileShare.ReadWrite, FileOptions.None, out error);
            if (intPtr == MonoIO.InvalidHandle)
            {
                return false;
            }
            switch (type)
            {
            case 1:
                creation_time = dateTime.ToFileTime();
                break;
            case 2:
                last_access_time = dateTime.ToFileTime();
                break;
            case 3:
                last_write_time = dateTime.ToFileTime();
                break;
            }
            bool flag = MonoIO.SetFileTime(new SafeFileHandle(intPtr, false), creation_time, last_access_time, last_write_time, out error);
            MonoIOError monoIOError;
            MonoIO.Close(intPtr, out monoIOError);
            return flag;
        }
References System.IO.MonoIO.Close(), System.IO.MonoIO.InvalidHandle, System.IO.MonoIO.Open(), System.IO.MonoIO.SetFileTime(), and System.DateTime.ToFileTime().