Terraria Decompiled: System.IO.MonoIO.GetFileType
GetFileType() [2/2]
static MonoFileType System.IO.MonoIO.GetFileType (SafeHandle safeHandle, out MonoIOError error) inline static
Definition at line 283 of file MonoIO.cs.
        {
            bool flag = false;
            MonoFileType fileType;
            try
            {
                safeHandle.DangerousAddRef(ref flag);
                fileType = MonoIO.GetFileType(safeHandle.DangerousGetHandle(), out error);
            }
            finally
            {
                if (flag)
                {
                    safeHandle.DangerousRelease();
                }
            }
            return fileType;
        }
References System.Runtime.InteropServices.SafeHandle.DangerousAddRef(), System.Runtime.InteropServices.SafeHandle.DangerousGetHandle(), System.Runtime.InteropServices.SafeHandle.DangerousRelease(), and System.IO.MonoIO.GetFileType().