Terraria Decompiled: Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh
Refresh()
bool Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh (WorkshopIssueReporter issueReporter) inline
Definition at line 130 of file WorkshopHelper.cs.
                {
                    this.ResourcePackPaths.Clear();
                    this.WorldPaths.Clear();
                    foreach (string text in this.GetListOfSubscribedItemsPaths())
                    {
                        if (text != null)
{
                            try
{
                                string text2 = text + Path.DirectorySeparatorChar.ToString() + "workshop.json";
                                if (File.Exists(text2))
{
                                    string text3 = AWorkshopEntry.ReadHeader(File.ReadAllText(text2));
                                    if (!(text3 == "World"))
{
                                        if (text3 == "ResourcePack")
{
                                            this.ResourcePackPaths.Add(text);
                                        }
                                    }
                                    else
{
                                        this.WorldPaths.Add(text);
                                    }
                                }
                            }
                            catch (Exception ex)
{
                                issueReporter.ReportDownloadProblem("Workshop.ReportIssue_FailedToLoadSubscribedFile", text, ex);
                                return false;
                            }
                        }
                    }
                    return true;
                }
References System.Collections.Generic.List< T >.Add(), System.Collections.Generic.List< T >.Clear(), System.IO.Path.DirectorySeparatorChar, System.IO.File.Exists(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.GetListOfSubscribedItemsPaths(), System.IO.File.ReadAllText(), Terraria.Social.Base.AWorkshopEntry.ReadHeader(), Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.ResourcePackPaths, System.text, and Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.WorldPaths.
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Prepare().