Terraria Decompiled: Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.GetListOfSubscribedItemsPaths
GetListOfSubscribedItemsPaths()
List< string > Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.GetListOfSubscribedItemsPaths () inline
Definition at line 104 of file WorkshopHelper.cs.
                {
                    PublishedFileId_t[] array = new PublishedFileId_t[SteamUGC.GetNumSubscribedItems()];
                    SteamUGC.GetSubscribedItems(array, (uint)array.Length);
                    ulong num = 0UL;
                    string empty = string.Empty;
                    uint num2 = 0U;
                    List<string> list = new List<string>();
                    PublishedFileId_t[] array2 = array;
                    for (int i = 0; i < array2.Length; i++)
                    {
                        if (SteamUGC.GetItemInstallInfo(array2[i], ref num, ref empty, 1024U, ref num2))
{
                            list.Add(empty);
                        }
                    }
                    return list;
                }
References System.array, Steamworks.SteamUGC.GetItemInstallInfo(), Steamworks.SteamUGC.GetNumSubscribedItems(), Steamworks.SteamUGC.GetSubscribedItems(), System.list, and System.U.
Referenced by Terraria.Social.Steam.WorkshopHelper.UGCBased.Downloader.Refresh().