Terraria Decompiled: System.Security.Permissions.UrlIdentityPermission.Copy
Copy()
override IPermission System.Security.Permissions.UrlIdentityPermission.Copy () inline
Implements System.Security.IPermission.
Definition at line 45 of file UrlIdentityPermission.cs.
        {
            if (this.url == null)
            {
                return new UrlIdentityPermission(PermissionState.None);
            }
            return new UrlIdentityPermission(this.url);
        }
References System.Security.Permissions.UrlIdentityPermission.url, and System.Security.Permissions.UrlIdentityPermission.UrlIdentityPermission().
Referenced by System.Security.Permissions.UrlIdentityPermission.Intersect(), and System.Security.Permissions.UrlIdentityPermission.Union().