Terraria Decompiled: Terraria.Tile.bottomSlope
bottomSlope()
bool Terraria.Tile.bottomSlope () inline
Definition at line 284 of file Tile.cs.
        {
            byte b = this.slope();
            return b == 3 || b == 4;
        }
References Terraria.Tile.slope().
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.WorldGen.AnchorValid(), Terraria.WorldGen.BottomEdgeCanBeAttachedTo(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckTorch(), Terraria.WorldGen.CheckVines(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.Collision.HurtTiles(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.PlaceSandTrap(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.SolidTileAllowTopSlope(), Terraria.DelegateMethods.SpreadTile(), Terraria.Collision.StepUp(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), and Terraria.WorldGen.UpdateWorld_UndergroundTile().