Terraria Decompiled: Terraria.Tile.isTheSameAs
isTheSameAs()
bool Terraria.Tile.isTheSameAs (Tile compTile) inline
Definition at line 136 of file Tile.cs.
        {
            if (compTile == null)
            {
                return false;
            }
            if (this.sTileHeader != compTile.sTileHeader)
            {
                return false;
            }
            if (this.active())
            {
                if (this.type != compTile.type)
                {
                    return false;
                }
                if (Main.tileFrameImportant[(int)this.type] && (this.frameX != compTile.frameX || this.frameY != compTile.frameY))
                {
                    return false;
                }
            }
            if (this.wall != compTile.wall || this.liquid != compTile.liquid)
            {
                return false;
            }
            if (compTile.liquid == 0)
            {
                if (this.wallColor() != compTile.wallColor())
                {
                    return false;
                }
                if (this.wire4() != compTile.wire4())
                {
                    return false;
                }
            }
            else if (this.bTileHeader != compTile.bTileHeader)
            {
                return false;
            }
            return this.invisibleBlock() == compTile.invisibleBlock() && this.invisibleWall() == compTile.invisibleWall() && this.fullbrightBlock() == compTile.fullbrightBlock() && this.fullbrightWall() == compTile.fullbrightWall();
        }
References Terraria.Tile.active(), Terraria.Tile.bTileHeader, Terraria.Tile.frameX, Terraria.Tile.frameY, Terraria.Tile.fullbrightBlock(), Terraria.Tile.fullbrightWall(), Terraria.Tile.invisibleBlock(), Terraria.Tile.invisibleWall(), Terraria.Tile.liquid, Terraria.Tile.sTileHeader, Terraria.Main.tileFrameImportant, Terraria.Tile.type, Terraria.Tile.wall, Terraria.Tile.wallColor(), and Terraria.Tile.wire4().
Referenced by Terraria.NetMessage.CompressTileBlock_Inner(), and Terraria.IO.WorldFile.SaveWorldTiles().