Terraria Decompiled: Terraria.Tile.liquidType
liquidType() [2/2]
void Terraria.Tile.liquidType (int liquidType) inline
Definition at line 195 of file Tile.cs.
        {
            if (liquidType == 0)
            {
                this.bTileHeader &= 159;
                return;
            }
            if (liquidType == 1)
            {
                this.lava(true);
                return;
            }
            if (liquidType == 2)
            {
                this.honey(true);
                return;
            }
            if (liquidType == 3)
            {
                this.shimmer(true);
            }
        }
References Terraria.Tile.honey(), Terraria.Tile.lava(), Terraria.Tile.liquidType(), and Terraria.Tile.shimmer().
Referenced by Terraria.WorldGen.AddPasses(), Terraria.Player.AdjTiles(), Terraria.WorldGen.AnyLiquidAt(), Terraria.WorldBuilding.Actions.SetLiquid.Apply(), Terraria.WorldBuilding.Modifiers.HasLiquid.Apply(), Terraria.WorldBuilding.Modifiers.NoLiquid.Apply(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeSquareDungeonRoom.BiomeRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.BiomeDungeonRoom.BiomeRoom_FinishRoom(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.WorldGen.CheckCatTail(), Terraria.Physics.BallCollision.CheckForPassThrough(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldBuilding.Conditions.HasLava.CheckValidity(), Terraria.WorldGen.CloudIsland(), Terraria.WorldGen.CloudLake(), Terraria.Liquid.DelWater(), Terraria.GameContent.NetModules.NetLiquidModule.Deserialize(), Terraria.WorldGen.DesertCloudIsland(), Terraria.WorldGen.digTunnel(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.WorldGen.EmptyLiquid(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.FloodRoom(), Terraria.MessageBuffer.GetData(), Terraria.Testing.DebugUtils.GetTileDescription(), Terraria.Map.MapHelper.GetWallType(), Terraria.WorldGen.GrowAlch(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.Lakinater(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLateDualDungeonFeatures.LateDualDungeonFeatures_CleanOutEntrancesOfLiquids_ActuallyClearArea(), Terraria.Liquid.LiquidCheck(), Terraria.WorldGen.LiquidInteractionsCleanup(), Terraria.Liquid.LiquidOverwriteStrip(), Terraria.ObjectData.TileObjectData.LiquidPlace(), Terraria.ObjectData.TileObjectData.LiquidPlace(), Terraria.WorldGen.NotTheBees(), Terraria.WorldGen.oceanCave(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.WorldGen.PlaceCatTail(), Terraria.GameContent.Biomes.GraniteBiome.PlaceGranite(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceLiquid(), Terraria.Player.PlaceThing_ValidTileForReplacement(), Terraria.SceneMetrics.ScanTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.NetModules.NetLiquidModule.Serialize(), Terraria.GameContent.NetModules.NetLiquidModule.SerializeForPlayer(), Terraria.NPC.Spawner.SetSpawnFlagsForChosenTile(), Terraria.Liquid.SettleWaterAt(), Terraria.WorldGen.ShimmerifySideOfWorld(), Terraria.WorldGen.SkyblockIsland(), Terraria.WorldGen.SnowCloudIsland(), Terraria.WorldGen.SonOfLakinater(), Terraria.DelegateMethods.SpreadTile(), Terraria.GameContent.SmartCursorHelper.Step_EmptyBuckets(), Terraria.WorldGen.TileRunner(), Terraria.Player.TryRecalculatingTorchLuck(), Terraria.Liquid.Update(), Terraria.WorldGen.UpdateWorld(), and Terraria.Wiring.XferWater().