Terraria Decompiled: Terraria.Tile.slope
slope() [1/2]
byte Terraria.Tile.slope () inline
Definition at line 685 of file Tile.cs.
        {
            return (byte)((this.sTileHeader & 28672) >> 12);
        }
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceExplosive(), Terraria.WorldGen.AddBuriedChest(), Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddLihzahrdAltar(), Terraria.WorldGen.AddManaCrystal(), Terraria.WorldGen.AddPasses(), Terraria.Collision.AdvancedTileCollision(), Terraria.Projectile.AI_026(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Collision.ApplyConveyorBeltMovementToVelocity(), Terraria.Graphics.Light.TileLightScanner.ApplyHellLight(), Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight(), Terraria.Tile.blockType(), Terraria.Tile.bottomSlope(), Terraria.Collision.BuildTileContacts(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitWithCheck(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.CheckCactus(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckTorch(), Terraria.Tile.Clear(), Terraria.Tile.ClearSlope(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.TileDrawing.DrawPartialLiquid(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileCracks(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.NPC.FindFrame(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FixHeart(), Terraria.Player.FloorVisuals(), Terraria.MessageBuffer.GetData(), Terraria.Physics.BallCollision.GetLeftOrRightEdge(), Terraria.Physics.BallCollision.GetSlopeEdge(), Terraria.Player.GetSmartPlatformSlope(), Terraria.Graphics.Light.TileLightScanner.GetTileMask(), Terraria.Physics.BallCollision.GetTopOrBottomEdge(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.HellFort(), Terraria.Collision.HurtTiles(), Terraria.WorldGen.IsBelowANonHammeredPlatform(), Terraria.WorldGen.IsFitToPlaceFlowerIn(), Terraria.WorldGen.IslandHouse(), Terraria.Physics.BallCollision.IsPositionInsideTile(), Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous(), Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Tile.leftSlope(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.outerTempled(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceSunflower(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PlantCheck_CanPlaceHook(), Terraria.WorldGen.PlantSeaOat(), Terraria.WorldGen.PoundPlatform(), Terraria.WorldGen.Pyramid(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.Tile.rightSlope(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.Tile.slope(), Terraria.Collision.SlopeCollision(), Terraria.WorldGen.SlopeTile(), Terraria.Tile.SmoothSlope(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.WorldGen.SpawnGraveyardBiome(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_Platforms(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepUp(), Terraria.Collision.StickyTiles(), Terraria.GameContent.PortalHelper.SupportedNormal(), Terraria.GameContent.PortalHelper.SupportedSlope(), Terraria.WorldGen.templeCleaner(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.Tile.topSlope(), Terraria.Tile.ToString(), Terraria.Collision.TryFindingConveyorBeltRising(), Terraria.GameContent.PortalHelper.TryPlacingPortal(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.Collision.WalkDownSlope(), and Terraria.Collision.WetCollision().