Terraria Decompiled: Terraria.Tile.lava
lava() [1/2]
bool Terraria.Tile.lava () inline
Definition at line 323 of file Tile.cs.
        {
            return (this.bTileHeader & 96) == 32;
        }
References Terraria.Tile.bTileHeader.
Referenced by Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.WorldGen.AddPasses(), Terraria.Liquid.AddWater(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.Tile.anyLava(), Terraria.Graphics.Light.TileLightScanner.ApplyLiquidLight(), Terraria.Liquid.AttemptToMoveLava(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.WorldGen.CheckAlch(), Terraria.WorldGen.closeEnoughToLavaToSpawnLavaBoulder(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.NPC.CreateBrickBoxForWallOfFlesh(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Liquid.DelWater(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.Collision.DrownCollision(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishGetGoodWorld(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.Projectile.GetFishingPondState(), Terraria.GameContent.Tile_Entities.TELogicSensor.GetState(), Terraria.Graphics.Light.TileLightScanner.GetTileMask(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.WorldGen.GrowAlch(), Terraria.WorldGen.HellRoom(), Terraria.NPC.HitEffect(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.WorldGen.KillTile(), Terraria.Liquid.LavaCheck(), Terraria.Collision.LavaCollision(), Terraria.WorldGen.LavaLayerCaverer(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.Liquid.LiquidCheck(), Terraria.Tile.liquidType(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.WorldGen.mayanTrap(), Terraria.WorldGen.MineHouse(), Terraria.WorldGen.nextCount(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.PlaceAlch(), Terraria.GameContent.Biomes.Desert.DesertHive.PlaceClustersArea(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceOasis(), Terraria.Player.PlaceThing_Tiles_CheckRopeUsability(), Terraria.Player.PlaceThing_Tiles_IsBlockedByLava(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.plantDye(), Terraria.NPC.Spawner.PostCheckChosenSpawnTile(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.Liquid.SettleWaterAt(), Terraria.WorldGen.ShroomPatch(), Terraria.Player.Spawn_ForceClearArea(), Terraria.WorldGen.Spread.Spider(), Terraria.WorldGen.SpreadGrass(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.TeleportHelpers.TileIsDangerous(), Terraria.WorldGen.TileRunner(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), Terraria.Map.WorldMap.UnlockMapTilePretty(), Terraria.Liquid.Update(), Terraria.WorldGen.WaterCheck(), and Terraria.Collision.WaterCollision().