Terraria Decompiled: Terraria.Tile.blockType
blockType()
int Terraria.Tile.blockType () inline
Definition at line 180 of file Tile.cs.
        {
            if (this.halfBrick())
            {
                return 1;
            }
            int num = (int)this.slope();
            if (num > 0)
            {
                num++;
            }
            return num;
        }
References Terraria.Tile.halfBrick(), int, and Terraria.Tile.slope().
Referenced by Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddManaCrystal(), Terraria.WorldGen.AddPasses(), Terraria.Projectile.AI_137_LightningAura(), Terraria.Projectile.AI_205_RemoteControlCar(), Terraria.WorldGen.AnchorValid(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.Collision.DrownCollision(), Terraria.Framing.FindBlockStyle(), Terraria.WorldGen.FixHeart(), Terraria.Testing.DebugUtils.GetTileDescription(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.Collision.GetTileRotation(), Terraria.Collision.IsWorldPointSolid(), Terraria.TileObject.Place(), Terraria.Collision.SolidFullTiles(), Terraria.WorldGen.TileFrameCosmetic(), and Terraria.Player.TouchBlockSurfaceCenter().