Terraria Decompiled: Terraria.Tile.wire
wire() [1/2]
bool Terraria.Tile.wire () inline
Definition at line 600 of file Tile.cs.
        {
            return (this.sTileHeader & 128) == 128;
        }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.WorldGen.AddWire(), Terraria.Tile.Clear(), Terraria.WorldGen.ClearAllBrokenTraps(), Terraria.WorldGen.ClearBrokenTraps(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.WorldGen.countWires(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.Main.DrawWires(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.WorldGen.FinishNoTraps(), Terraria.MessageBuffer.GetData(), Terraria.WorldGen.HasAnyWireNearby(), Terraria.Wiring.HitWire(), Terraria.WorldGen.KillWire(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalLights.Lights_GenerateSwitch(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.Wiring.MassWireOperationStep(), Terraria.WorldGen.mayanTrap(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.CaveHouseBiome.Place(), Terraria.WorldGen.placeLavaTrap(), Terraria.GameContent.Generation.TrackGenerator.PlacePath(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlaceWire(), Terraria.GameContent.Biomes.DeadMansChestBiome.PlaceWireLine(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_ColoredWrenches(), Terraria.GameContent.SmartCursorHelper.Step_MulticolorWrench(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), and Terraria.Wiring.TripWire().