Terraria Decompiled: Terraria.Tile.Clear
Clear()
void Terraria.Tile.Clear (TileDataType types) inline
Definition at line 720 of file Tile.cs.
        {
            if ((types & TileDataType.Tile) != (TileDataType)0)
            {
                this.type = 0;
                this.active(false);
                this.frameX = 0;
                this.frameY = 0;
            }
            if ((types & TileDataType.Wall) != (TileDataType)0)
            {
                this.wall = 0;
                this.wallFrameX(0);
                this.wallFrameY(0);
            }
            if ((types & TileDataType.TilePaint) != (TileDataType)0)
            {
                this.ClearBlockPaintAndCoating();
            }
            if ((types & TileDataType.WallPaint) != (TileDataType)0)
            {
                this.ClearWallPaintAndCoating();
            }
            if ((types & TileDataType.Liquid) != (TileDataType)0)
            {
                this.liquid = 0;
                this.liquidType(0);
                this.checkingLiquid(false);
            }
            if ((types & TileDataType.Slope) != (TileDataType)0)
            {
                this.slope(0);
                this.halfBrick(false);
            }
            if ((types & TileDataType.Wiring) != (TileDataType)0)
            {
                this.wire(false);
                this.wire2(false);
                this.wire3(false);
                this.wire4(false);
            }
            if ((types & TileDataType.Actuator) != (TileDataType)0)
            {
                this.actuator(false);
                this.inActive(false);
            }
        }
References Terraria.Tile.active(), Terraria.Tile.actuator(), Terraria.Tile.checkingLiquid(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.Tile.ClearWallPaintAndCoating(), Terraria.Tile.halfBrick(), Terraria.Tile.inActive(), Terraria.Tile.liquidType(), Terraria.Tile.slope(), Terraria.Tile.wallFrameX(), Terraria.Tile.wallFrameY(), Terraria.Tile.wire(), Terraria.Tile.wire2(), Terraria.Tile.wire3(), and Terraria.Tile.wire4().
Referenced by Terraria.WorldBuilding.Actions.SetTile.Apply(), Terraria.WorldBuilding.Actions.SetWall.Apply(), Terraria.WorldBuilding.Actions.SetTileKeepWall.Apply(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalBookshelves.Bookshelves(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.ChangeTileType(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalDoors.Doors(), Terraria.WorldGen.EmptyLiquid(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateDungeonStairs(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GrowDungeonTree_MakePassage(), Terraria.GameContent.Generation.Dungeon.Entrances.LegacyDungeonEntrance.LegacyEntrance(), Terraria.WorldGen.PlaceTile(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalPlatforms.Platforms(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalSpikes.Spikes(), Terraria.DelegateMethods.SpreadTile(), Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonWindowBasic.Window().