Terraria Decompiled: Terraria.Tile.fullbrightBlock
fullbrightBlock() [1/2]
bool Terraria.Tile.fullbrightBlock () inline
Definition at line 537 of file Tile.cs.
        {
            return (this.bTileHeader3 & 128) == 128;
        }
References Terraria.Tile.bTileHeader3.
Referenced by Terraria.TileColorCache.ApplyToBlock(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.WorldGen.coatingColors(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.IO.WorldFile.ConvertIlluminantPaintToNewField(), Terraria.Tile.CopyPaintAndCoating(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidFinish(), Terraria.WorldGen.SecretSeed.DoRoundLandMasses(), Terraria.GameContent.Tile_Entities.TEDisplayDoll.Draw(), Terraria.GameContent.Drawing.TileDrawing.DrawMasterTrophies(), Terraria.GameContent.Drawing.TileDrawing.DrawRisingVineStrip(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile_SlicedBlock(), Terraria.GameContent.Drawing.TileDrawing.DrawTeleportationPylons(), Terraria.GameContent.Drawing.TileDrawing.DrawTiles_GetLightOverride(), Terraria.GameContent.Drawing.TileDrawing.DrawTrees(), Terraria.GameContent.Drawing.TileDrawing.DrawVineStrip(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.Testing.DebugUtils.GetTileDescription(), Terraria.Map.MapHelper.GetTileType(), Terraria.Tile.isTheSameAs(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.paintCoatTile(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), and Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper().