Terraria Decompiled: Terraria.Tile.ClearBlockPaintAndCoating
ClearBlockPaintAndCoating()
void Terraria.Tile.ClearBlockPaintAndCoating () inline
Definition at line 890 of file Tile.cs.
        {
            this.color(0);
            this.fullbrightBlock(false);
            this.invisibleBlock(false);
        }
References Terraria.Tile.color(), Terraria.Tile.fullbrightBlock(), and Terraria.Tile.invisibleBlock().
Referenced by Terraria.GameContent.Generation.Dungeon.Rooms.BiomeRuggedDungeonRoom.BiomeRoom(), Terraria.Tile.Clear(), Terraria.Tile.ClearTileAndPaint(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.OverGrownDungeonWithRainbowMoss(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Area(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), and Terraria.WorldGen.TileFrame().