Terraria Decompiled: Terraria.Tile.shimmer
shimmer() [1/2]
bool Terraria.Tile.shimmer () inline
Definition at line 357 of file Tile.cs.
        {
            return (this.bTileHeader & 96) == 96;
        }
References Terraria.Tile.bTileHeader.
Referenced by Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.Tile.anyShimmer(), Terraria.Graphics.Light.TileLightScanner.ApplyLiquidLight(), Terraria.Liquid.AttemptToMoveShimmer(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Liquid.DelWater(), Terraria.Collision.DrownCollision(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishRemixWorld(), Terraria.GameContent.Tile_Entities.TELogicSensor.GetState(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Liquid.LiquidCheck(), Terraria.Tile.liquidType(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.nextCount(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.PlaceDye(), Terraria.NPC.Spawner.PostCheckChosenSpawnTile(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.Liquid.SettleWaterAt(), Terraria.Projectile.Shimmer(), Terraria.WorldGen.ShimmeratorNext(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerifySideOfWorld(), Terraria.WorldItem.Shimmering(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.WorldGen.ShimmerRemoveWater(), Terraria.WorldGen.Shimminate(), Terraria.WorldGen.SkyblockIsland(), Terraria.NPC.Spawner.SpawnFaelings(), Terraria.Liquid.Update(), Terraria.WorldItem.UpdateItem(), and Terraria.Collision.WetCollision().