Terraria Decompiled: Terraria.Tile.ClearTile
ClearTile()
void Terraria.Tile.ClearTile () inline
Definition at line 74 of file Tile.cs.
        {
            this.ClearSlope();
            this.active(false);
            this.inActive(false);
        }
References Terraria.Tile.active(), Terraria.Tile.ClearSlope(), and Terraria.Tile.inActive().
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.WorldGen.AddBeeLarva(), Terraria.WorldGen.AttemptToGeneratePlanteraBulbAt(), Terraria.NPC.BigMimicSummonCheck(), Terraria.WorldBuilding.WorldUtils.ClearTile(), Terraria.Tile.ClearTileAndPaint(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea(), Terraria.GameContent.Generation.Dungeon.Entrances.DomeDungeonEntrance.DomeEntrance_Door(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.GameContent.Generation.Dungeon.Features.DungeonGlobalEarlyDualDungeonFeatures.EarlyDungeonFeatures(), Terraria.GameContent.Generation.Dungeon.Halls.DungeonHall.GenerateDungeonSquareHall(), Terraria.GameContent.Generation.Dungeon.Rooms.DungeonRoom.GenerateDungeonSquareRoom(), Terraria.GameContent.Generation.Dungeon.Rooms.LivingTreeDungeonRoom.GenerateLateDungeonFeaturesInRoom(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateTileStrip(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyDungeonHall.LegacyHall(), Terraria.GameContent.Generation.Dungeon.Halls.LegacyEntranceDungeonHall.LegacyHall(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.ShiftTrapdoor(), Terraria.WorldGen.SpawnFallingBlockProjectile(), and Terraria.GameContent.Generation.Dungeon.Entrances.TowerDungeonEntrance.TowerEntrance_Door().