Terraria Decompiled: Terraria.Tile.honey
honey() [1/2]
bool Terraria.Tile.honey () inline
Definition at line 340 of file Tile.cs.
        {
            return (this.bTileHeader & 96) == 64;
        }
References Terraria.Tile.bTileHeader.
Referenced by Terraria.Tile.anyHoney(), Terraria.Liquid.AttemptToMoveHoney(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.GameContent.Biomes.HiveBiome.CreateBlockedHoneyCube(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.Liquid.DelWater(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddLiquid(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishNotTheBees(), Terraria.WorldGen.FinishRemixWorld(), Terraria.Projectile.GetFishingPondState(), Terraria.GameContent.Tile_Entities.TELogicSensor.GetState(), Terraria.Graphics.Light.TileLightScanner.GetTileMask(), Terraria.Gore.Gore_UpdateLeaf(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.WorldGen.KillTile_GetItemDrops(), Terraria.Liquid.LiquidCheck(), Terraria.Tile.liquidType(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.NotTheBees(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.plantDye(), Terraria.NPC.Spawner.PostCheckChosenSpawnTile(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.Liquid.SettleWaterAt(), Terraria.WorldGen.ShimmerCleanUp(), Terraria.WorldGen.ShimmerifySideOfWorld(), Terraria.Liquid.Update(), and Terraria.Collision.WetCollision().