Terraria Decompiled: Terraria.Tile.inActive
inActive() [1/2]
bool Terraria.Tile.inActive () inline
Definition at line 583 of file Tile.cs.
        {
            return (this.sTileHeader & 64) == 64;
        }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.Tile.actColor(), Terraria.Tile.actColor(), Terraria.WorldGen.ActiveAndWalkableTile(), Terraria.Wiring.Actuate(), Terraria.Wiring.ActuateForced(), Terraria.Collision.AdvancedTileCollision(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.Collision.AnyCollision(), Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.WorldGen.BottomEdgeCanBeAttachedTo(), Terraria.Collision.BuildTileContacts(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitLine(), Terraria.Collision.CanHitWithCheck(), Terraria.DelegateMethods.CastLightOpen(), Terraria.DelegateMethods.CastLightOpen_StopForSolids(), Terraria.DelegateMethods.CastLightOpen_StopForSolids_ScaleWithDistance(), Terraria.Utils.CheckForGoodTeleportationSpot(), Terraria.DelegateMethods.CheckStopForSolids(), Terraria.Tile.Clear(), Terraria.Tile.ClearTile(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.Wiring.DeActive(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Mount.DrillSmartCursor_Blocks(), Terraria.DelegateMethods.EmitGolfCartDust_StopForSolids(), Terraria.GameContent.Generation.Dungeon.DungeonUtils.GenerateTileStrip(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPillar.GenerateTileStrip(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.GameContent.Drawing.TileDrawing.GetFinalLight(), Terraria.Graphics.Light.TileLightScanner.GetTileMask(), Terraria.WorldGen.hardUpdateWorld(), Terraria.Collision.HitLine(), Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Collision.HurtTiles(), Terraria.GameContent.Drawing.TileDrawing.IsTileDangerous(), Terraria.Collision.IsWorldPointSolid(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.Wiring.ReActive(), Terraria.WorldGen.RightEdgeCanBeAttachedTo(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.Collision.SlopeCollision(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidOrSlopedTile(), Terraria.NPC.SolidOrSlopedTileOrPlatform(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile3(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.WorldGen.SolidTileAllowTopSlope(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.WorldGen.SolidTileNoPlatforms(), Terraria.Collision.SolidTiles(), Terraria.Collision.SolidTiles(), Terraria.DelegateMethods.SpreadLightOpen_StopForSolids(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_GrassSeeds(), Terraria.GameContent.SmartCursorHelper.Step_Moss(), Terraria.GameContent.SmartCursorHelper.Step_Pickaxe_MineSolids(), Terraria.GameContent.SmartCursorHelper.Step_StaffOfRegrowth(), Terraria.Collision.StickyTiles(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TileEmpty(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), and Terraria.WorldGen.UpdateWorld_GrassGrowth().