Terraria Decompiled: Terraria.Tile.nactive
nactive()
bool Terraria.Tile.nactive () inline
Definition at line 225 of file Tile.cs.
        {
            return (this.sTileHeader & 96) == 32;
        }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.NPC.AddKingSlimeTeleportCacheTiles(), Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddManaCrystal(), Terraria.Liquid.AddWater(), Terraria.NPC.AI(), Terraria.Projectile.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.NPC.AI_006_Worms(), Terraria.Projectile.AI_007_GrapplingHooks(), Terraria.Projectile.AI_007_GrapplingHooks_CanTileBeLatchedOnTo(), Terraria.NPC.AI_007_TownEntities(), Terraria.NPC.AI_007_TownEntities_GetWalkPrediction(), Terraria.Projectile.AI_016_Bombs(), Terraria.Projectile.AI_016_CanAcornPlant(), Terraria.NPC.AI_026_Unicorns(), Terraria.NPC.AI_037_Destroyer(), Terraria.NPC.AI_065_Butterflies(), Terraria.NPC.AI_084_LunaticCultist(), Terraria.NPC.AI_107_ImprovedWalkers(), Terraria.NPC.AI_109_DarkMage(), Terraria.NPC.AI_112_FairyCritter(), Terraria.Projectile.AI_113_TargetSticker(), Terraria.NPC.AI_113_WindyBalloon(), Terraria.NPC.AI_114_Dragonflies(), Terraria.NPC.AI_115_LadyBugs(), Terraria.NPC.AI_125_ClumsySlimeBalloon(), Terraria.NPC.AI_AttemptToFindTeleportSpot(), Terraria.WorldGen.AnchorValid(), Terraria.WorldGen.BlockBelowMakesSandConvertIntoHardenedSand(), Terraria.WorldGen.BlockBelowMakesSandFall(), Terraria.NPC.BloodNautilus_CallForHelp(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.CanPlaceSink(), Terraria.NPC.Spawner.CanSpawnInTile(), Terraria.WorldGen.CanUnderwaterPlantGrowHere(), Terraria.WorldGen.Check1x2Top(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.Check3x3(), Terraria.WorldGen.Check6x3(), Terraria.WorldGen.CheckAlch(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCactus(), Terraria.WorldGen.CheckCatTail(), Terraria.WorldGen.CheckChand(), Terraria.Player.CheckCrackedBrickBreak(), Terraria.WorldGen.CheckDye(), Terraria.Physics.BallCollision.CheckForPassThrough(), Terraria.Player.CheckIceBreak(), Terraria.WorldGen.CheckMB(), Terraria.WorldGen.CheckOrb(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckRoom(), Terraria.Player.CheckSpawn_Internal(), Terraria.WorldGen.CheckSunflower(), Terraria.WorldGen.CheckVines(), Terraria.Liquid.DelWater(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.WorldGen.EmptyLiquid(), Terraria.NPC.Spawner.FindSpawnTile(), Terraria.WorldGen.FixHeart(), Terraria.NPC.GetBirdFlightRecommendation(), Terraria.Physics.BallCollision.GetCollisionPointForTile(), Terraria.Player.GetFloorTile(), Terraria.Player.GetHurtTile(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.WorldGen.GetTileVisualHitbox(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.NPC.HitEffect(), Terraria.WorldGen.IsLightningAttractor(), Terraria.Physics.BallCollision.IsNeighborSolid(), Terraria.NPC.Spawner.IsValidSpawningGroundTile(), Terraria.Player.ItemCheck_Shoot(), Terraria.Player.ItemCheck_UseBuckets(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.mayanTrap(), Terraria.Player.MinionRestTargetAim(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.Place1x1(), Terraria.WorldGen.Place1x2Top(), Terraria.WorldGen.Place2x2(), Terraria.WorldGen.Place3x2(), Terraria.WorldGen.Place3x3(), Terraria.WorldGen.Place6x3(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBanner(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChand(), Terraria.WorldGen.PlaceDoor(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.PlaceLiquid(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.WorldGen.PlaceSign(), Terraria.WorldGen.PlaceSunflower(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.placeTrap(), Terraria.WorldGen.PlantAlch(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PlantCheck_CanPlaceHook(), Terraria.WorldGen.ScoreRoom(), Terraria.Liquid.SettleWaterAt(), Terraria.Main.snowing(), Terraria.Collision.SolidFullTiles(), Terraria.WorldGen.SolidTile(), Terraria.Player.Spawn_DescendFromDefaultSpace(), Terraria.Player.Spawn_ForceClearArea(), Terraria.Player.Spawn_IsAreaValidSpawn(), Terraria.WorldGen.SpawnHomelessNPC(), Terraria.WorldGen.SpawnTownNPC(), Terraria.WorldGen.SpawnTravelNPC(), Terraria.WorldGen.StartRoomCheck(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepDown(), Terraria.Collision.StepUp(), Terraria.GameContent.PortalHelper.SupportedHalfbrick(), Terraria.GameContent.PortalHelper.SupportedNormal(), Terraria.GameContent.PortalHelper.SupportedSlope(), Terraria.WorldGen.TileFrameImportant(), Terraria.Minecart.TrackCollision(), Terraria.Player.TryBouncingBlocks(), Terraria.Collision.TryFindingConveyorBeltRising(), Terraria.NPC.TryFindingFloor(), Terraria.Liquid.Update(), Terraria.WorldGen.UpdateWorld_OvergroundTile(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), Terraria.Collision.WalkDownSlope(), and Terraria.WorldGen.WaterCheck().