Terraria Decompiled: Terraria.Tile.actuator
actuator() [1/2]
bool Terraria.Tile.actuator () inline
Definition at line 668 of file Tile.cs.
        {
            return (this.sTileHeader & 2048) == 2048;
        }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.Wiring.Actuate(), Terraria.Tile.Clear(), Terraria.WorldGen.ClearBrokenTraps(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.Main.DrawWires(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.FindDartTrapSpotSingle(), Terraria.MessageBuffer.GetData(), Terraria.Wiring.HitWireSingle(), Terraria.WorldGen.IsItATrap(), Terraria.Player.ItemCheck_UseWiringTools(), Terraria.WorldGen.KillActuator(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.Wiring.MassWireOperationStep(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.WorldGen.PlaceActuator(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.placeTrap(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.SmartCursorHelper.Step_ActuationRod(), Terraria.GameContent.SmartCursorHelper.Step_Actuators(), Terraria.GameContent.SmartCursorHelper.Step_WireCutter(), and Terraria.GameContent.Generation.Dungeon.Features.DungeonTileClump.TileClump().