Terraria Decompiled: Terraria.Tile.invisibleBlock
invisibleBlock() [1/2]
bool Terraria.Tile.invisibleBlock () inline
Definition at line 503 of file Tile.cs.
        {
            return (this.bTileHeader3 & 32) == 32;
        }
References Terraria.Tile.bTileHeader3.
Referenced by Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight(), Terraria.Graphics.Light.TileLightScanner.ApplyTileLight(), Terraria.TileColorCache.ApplyToBlock(), Terraria.Tile.BlockColorAndCoating(), Terraria.Tile.ClearBlockPaintAndCoating(), Terraria.WorldGen.coatingColors(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.Tile.CopyPaintAndCoating(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoCoatEverythingEcho(), Terraria.WorldGen.SecretSeed.DoCoatEverythingIlluminant(), Terraria.WorldGen.SecretSeed.DoErrorWorldFinish(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.Main.DrawBlack(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.Main.DrawTileCracks(), Terraria.GameContent.Drawing.WallDrawing.FullTile(), Terraria.MessageBuffer.GetData(), Terraria.Testing.DebugUtils.GetTileDescription(), Terraria.WorldGen.GetTileMergeCulling(), Terraria.Map.MapHelper.GetTileType(), Terraria.Tile.isTheSameAs(), Terraria.GameContent.Drawing.TileDrawing.IsVisible(), Terraria.Graphics.Light.TileLightScanner.LightIsBlocked(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.paintCoatTile(), Terraria.Player.PlaceThing_PaintScrapper_TryScrapping(), Terraria.WorldGen.RefreshStrip(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.GameContent.SmartCursorHelper.Step_PaintBrush(), Terraria.GameContent.SmartCursorHelper.Step_PaintScrapper(), Terraria.WorldGen.StopMergingByInvsibility(), and Terraria.Player.VampireSeedSunlightExposure().