Terraria Decompiled: Terraria.Tile.halfBrick
halfBrick() [1/2]
bool Terraria.Tile.halfBrick () inline
Definition at line 651 of file Tile.cs.
        {
            return (this.sTileHeader & 1024) == 1024;
        }
References Terraria.Tile.sTileHeader.
Referenced by Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceBoulderTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceDartTrap(), Terraria.GameContent.Biomes.DeadMansChestBiome.ActuallyPlaceExplosive(), Terraria.WorldGen.AddLifeCrystal(), Terraria.WorldGen.AddLihzahrdAltar(), Terraria.WorldGen.AddManaCrystal(), Terraria.WorldGen.AddPasses(), Terraria.Collision.AdvancedTileCollision(), Terraria.NPC.AI(), Terraria.NPC.AI_003_Fighters(), Terraria.Projectile.AI_016_CanAcornPlant(), Terraria.Projectile.AI_026(), Terraria.NPC.AI_026_Unicorns(), Terraria.Projectile.AI_067_FreakingPirates(), Terraria.WorldGen.AnchorValid(), Terraria.Collision.AnyCollision(), Terraria.Collision.AnyCollisionWithSpecificTiles(), Terraria.WorldBuilding.Actions.HalfBlock.Apply(), Terraria.WorldBuilding.Actions.SetHalfTile.Apply(), Terraria.Collision.ApplyConveyorBeltMovementToVelocity(), Terraria.Graphics.Light.TileLightScanner.ApplyHellLight(), Terraria.Graphics.Light.TileLightScanner.ApplySurfaceLight(), Terraria.Tile.blockType(), Terraria.Collision.BuildTileContacts(), Terraria.Collision.CanHit(), Terraria.Collision.CanHitWithCheck(), Terraria.TileObject.CanPlace(), Terraria.WorldGen.Check2x1(), Terraria.WorldGen.Check2x2(), Terraria.WorldGen.Check3x2(), Terraria.WorldGen.CheckAlch(), Terraria.WorldGen.CheckBanner(), Terraria.WorldGen.CheckCactus(), Terraria.WorldGen.CheckLilyPad(), Terraria.WorldGen.CheckOnTable1x1(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.WorldGen.CheckSuper(), Terraria.WorldGen.CheckTorch(), Terraria.Tile.Clear(), Terraria.Tile.ClearSlope(), Terraria.NetMessage.CompressTileBlock_Inner(), Terraria.GameContent.Biomes.HiveBiome.CreateHiveTunnel(), Terraria.GameContent.Biomes.HiveBiome.CreateStandForLarva(), Terraria.NetMessage.DecompressTileBlock_Inner(), Terraria.WorldGen.SecretSeed.DoActuallyNoTraps(), Terraria.WorldGen.SecretSeed.DoAddTeleporters_ClearArea(), Terraria.Player.DoBootsEffect_PlaceFlowersOnTile(), Terraria.WorldGen.SecretSeed.DoErrorWorldShuffleBlocks(), Terraria.WorldGen.SecretSeed.DoExtraLiquidAddBubbleBlocks(), Terraria.WorldGen.SecretSeed.DoRainbowStuff(), Terraria.GameContent.Drawing.TileDrawing.DrawBasicTile(), Terraria.Main.DrawBlack(), Terraria.HitTile.DrawFreshAnimations(), Terraria.GameContent.Drawing.TileDrawing.DrawSingleTile(), Terraria.GameContent.Drawing.TileDrawing.DrawTile_LiquidBehindTile(), Terraria.Main.DrawTileCracks(), Terraria.WaterfallManager.DrawWaterfall(), Terraria.GameContent.Generation.Dungeon.Features.DungeonDropTrap.DropTrap(), Terraria.WaterfallManager.FindWaterfalls(), Terraria.WorldGen.FinishNoTraps(), Terraria.WorldGen.FixHeart(), Terraria.MessageBuffer.GetData(), Terraria.GameContent.LeashedEntities.FlyerLeashedCritter.GetDrawOffset(), Terraria.GameContent.LeashedEntities.JumperLeashedCritter.GetDrawOffset(), Terraria.GameContent.LeashedEntities.WalkerLeashedCritter.GetDrawOffset(), Terraria.Physics.BallCollision.GetLeftOrRightEdge(), Terraria.GameContent.Drawing.TileDrawing.GetTileDrawData(), Terraria.WorldGen.GetTileVisualHitbox(), Terraria.Physics.BallCollision.GetTopOrBottomEdge(), Terraria.WorldGen.GrowCactus(), Terraria.WorldGen.GrowCatTail(), Terraria.WorldGen.GrowEpicTree(), Terraria.WorldGen.GrowLivingTree(), Terraria.WorldGen.GrowLivingTree_HorizontalTunnel(), Terraria.WorldGen.GrowLivingTree_MakePassage(), Terraria.WorldGen.GrowLivingTreePassageRoom(), Terraria.WorldGen.GrowPalmTree(), Terraria.WorldGen.GrowShroom(), Terraria.WorldGen.GrowTree(), Terraria.WorldGen.GrowTreeWithSettings(), Terraria.WorldGen.GrowUndergroundTree(), Terraria.WorldGen.HellFort(), Terraria.Collision.HitTiles(), Terraria.Collision.HitTilesInACircle(), Terraria.Wiring.HitWireSingle(), Terraria.Collision.HurtTiles(), Terraria.GameContent.Liquid.LiquidRenderer.InternalPrepareDraw(), Terraria.WorldGen.IsBelowANonHammeredPlatform(), Terraria.WorldGen.IsFitToPlaceFlowerIn(), Terraria.WorldGen.IslandHouse(), Terraria.Physics.BallCollision.IsPositionInsideTile(), Terraria.GameContent.SmartCursorHelper.IsValidSpotForTorch(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.Projectile.Kill_DirtAndFluidProjectiles_RunDelegateMethodPushUpForHalfBricks(), Terraria.WorldGen.KillTile(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.IO.WorldFile.LoadWorld_Version1_Old_BeforeRelease88(), Terraria.IO.WorldFile.LoadWorldTiles(), Terraria.WorldGen.makeTemple(), Terraria.WorldGen.MakeWateryIceThing(), Terraria.WorldGen.MarblePileWithStatues(), Terraria.WorldGen.meteor(), Terraria.WorldGen.MineHouse(), Terraria.Collision.noSlopeCollision(), Terraria.Main.oldDrawWater(), Terraria.WorldGen.outerTempled(), Terraria.GameContent.Generation.Dungeon.Features.DungeonPitTrap.PitTrap(), Terraria.GameContent.Biomes.MiningExplosivesBiome.Place(), Terraria.WorldGen.PlaceAlch(), Terraria.WorldGen.PlaceBamboo(), Terraria.WorldGen.PlaceCatTail(), Terraria.WorldGen.PlaceChestDirect(), Terraria.WorldGen.PlaceDye(), Terraria.WorldGen.placeLavaTrap(), Terraria.WorldGen.PlaceLilyPad(), Terraria.WorldGen.PlaceMB(), Terraria.WorldGen.PlaceOasis(), Terraria.WorldGen.PlaceOnTable1x1(), Terraria.WorldGen.PlacePot(), Terraria.GameContent.Biomes.Desert.SandMound.PlaceSandColumn(), Terraria.WorldGen.PlaceSandTrap(), Terraria.WorldGen.PlaceSunflower(), Terraria.GameContent.Biomes.CaveHouse.HouseBuilder.PlaceSupportBeams(), Terraria.Player.PlaceThing_Tiles_BlockPlacementForAssortedThings(), Terraria.Player.PlaceThing_Tiles_PlaceIt_SpinSmartPlatform(), Terraria.Player.PlaceThing_Tiles_PlaceIt_UnslopeForSolids(), Terraria.WorldGen.PlaceTile(), Terraria.WorldGen.PlaceUnderwaterPlant(), Terraria.WorldGen.PlantCheck(), Terraria.WorldGen.PlantCheck_CanPlaceHook(), Terraria.WorldGen.PlantSeaOat(), Terraria.WorldGen.PoundPlatform(), Terraria.WorldGen.PoundTile(), Terraria.WorldGen.Pyramid(), Terraria.WorldGen.ReplaceTile_DoActualReplacement_Single(), Terraria.WorldGen.RightEdgeCanBeAttachedTo(), Terraria.IO.WorldFile.SaveWorldTiles(), Terraria.NetMessage.SendData(), Terraria.WorldGen.ShellPile(), Terraria.WorldGen.ShimmerMakeBiome(), Terraria.Collision.SlopeCollision(), Terraria.WorldGen.SlopeTile(), Terraria.Tile.SmoothSlope(), Terraria.Collision.SolidCollision(), Terraria.Collision.SolidCollision(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTile2(), Terraria.WorldGen.SolidTileAllowBottomSlope(), Terraria.WorldGen.SolidTileAllowLeftSlope(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.WorldGen.SolidTileAllowTopSlope(), Terraria.WorldGen.SolidTileNoAttach(), Terraria.WorldGen.SpawnGraveyardBiome(), Terraria.DelegateMethods.SpreadTile(), Terraria.GameContent.SmartCursorHelper.Step_AlchemySeeds(), Terraria.GameContent.SmartCursorHelper.Step_Boulders(), Terraria.GameContent.SmartCursorHelper.Step_ClayPots(), Terraria.GameContent.SmartCursorHelper.Step_PumpkinSeeds(), Terraria.Collision.StepConveyorBelt(), Terraria.Collision.StepDown(), Terraria.Collision.StepUp(), Terraria.Collision.StickyTiles(), Terraria.GameContent.PortalHelper.SupportedHalfbrick(), Terraria.GameContent.PortalHelper.SupportedNormal(), Terraria.WorldGen.templeCleaner(), Terraria.Collision.TileCollision(), Terraria.WorldGen.TileFrame(), Terraria.WorldGen.TileFrameCosmetic(), Terraria.WorldGen.TileFrameImportant(), Terraria.WorldGen.TopEdgeCanBeAttachedTo(), Terraria.GameContent.PortalHelper.TryPlacingPortal(), Terraria.GameContent.AmbientWindSystem.TrySpawningWind(), Terraria.WorldGen.UpdateWorld_UndergroundTile(), and Terraria.Collision.WalkDownSlope().