Terraria Decompiled: Terraria.Tile.leftSlope
leftSlope()
bool Terraria.Tile.leftSlope () inline
Definition at line 291 of file Tile.cs.
        {
            byte b = this.slope();
            return b == 2 || b == 4;
        }
References Terraria.Tile.slope().
Referenced by Terraria.NPC.AI(), Terraria.WorldGen.CheckProjectilePressurePad_GetPossiblePlacementDirections(), Terraria.Collision.HurtTiles(), Terraria.Player.ItemCheck_UseMiningTools_TryPoundingTile(), Terraria.WorldGen.LeftEdgeCanBeAttachedTo(), Terraria.WorldGen.SolidTileAllowRightSlope(), Terraria.Collision.StepConveyorBelt(), Terraria.WorldGen.TileFrameCosmetic(), and Terraria.WorldGen.TileFrameImportant().