Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ParseSide
ParseSide()
object Newtonsoft.Json.Linq.JsonPath.JPath.ParseSide () inline private
Definition at line 420 of file JPath.cs.
        {
            this.EatWhitespace();
            List<PathFilter> list;
            if (this.TryParseExpression(out list))
            {
                this.EatWhitespace();
                this.EnsureLength("Path ended with open query.");
                return list;
            }
            object obj;
            if (this.TryParseValue(out obj))
            {
                this.EatWhitespace();
                this.EnsureLength("Path ended with open query.");
                return new JValue(obj);
            }
            throw this.CreateUnexpectedCharacterException();
        }
References Newtonsoft.Json.Linq.JsonPath.JPath.CreateUnexpectedCharacterException(), Newtonsoft.Json.Linq.JsonPath.JPath.EatWhitespace(), Newtonsoft.Json.Linq.JsonPath.JPath.EnsureLength(), System.list, System.obj, Newtonsoft.Json.Linq.JsonPath.JPath.TryParseExpression(), and Newtonsoft.Json.Linq.JsonPath.JPath.TryParseValue().
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression().