Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuery
ParseQuery()
PathFilter Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuery (char indexerCloseChar) inline private
Definition at line 365 of file JPath.cs.
        {
            this._currentIndex++;
            this.EnsureLength("Path ended with open indexer.");
            if (this._expression.get_Chars(this._currentIndex) != '(')
            {
                throw new JsonException("Unexpected character while parsing path indexer: " + this._expression.get_Chars(this._currentIndex).ToString());
            }
            this._currentIndex++;
            QueryExpression queryExpression = this.ParseExpression();
            this._currentIndex++;
            this.EnsureLength("Path ended with open indexer.");
            this.EatWhitespace();
            if (this._expression.get_Chars(this._currentIndex) != indexerCloseChar)
            {
                throw new JsonException("Unexpected character while parsing path indexer: " + this._expression.get_Chars(this._currentIndex).ToString());
            }
            return new QueryFilter
            {
                Expression = queryExpression
            };
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, Newtonsoft.Json.Linq.JsonPath.JPath.EatWhitespace(), Newtonsoft.Json.Linq.JsonPath.JPath.EnsureLength(), and Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression().
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer().