Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuotedField
ParseQuotedField()
PathFilter Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuotedField (char indexerCloseChar, bool scan) inline private
Definition at line 684 of file JPath.cs.
        {
            List<string> list = null;
            while (this._currentIndex < this._expression.Length)
            {
                string text = this.ReadQuotedString();
                this.EatWhitespace();
                this.EnsureLength("Path ended with open indexer.");
                if (this._expression.get_Chars(this._currentIndex) == indexerCloseChar)
                {
                    if (list == null)
                    {
                        return JPath.CreatePathFilter(text, scan);
                    }
                    list.Add(text);
                    if (!scan)
                    {
                        return new FieldMultipleFilter
{
                            Names = list
                        };
                    }
                    return new ScanMultipleFilter
                    {
                        Names = list
                    };
                }
                else
                {
                    if (this._expression.get_Chars(this._currentIndex) != ',')
                    {
                        throw new JsonException("Unexpected character while parsing path indexer: " + this._expression.get_Chars(this._currentIndex).ToString());
                    }
                    this._currentIndex++;
                    this.EatWhitespace();
                    if (list == null)
                    {
                        list = new List<string>();
                    }
                    list.Add(text);
                }
            }
            throw new JsonException("Path ended with open indexer.");
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, Newtonsoft.Json.Linq.JsonPath.JPath.CreatePathFilter(), Newtonsoft.Json.Linq.JsonPath.JPath.EatWhitespace(), Newtonsoft.Json.Linq.JsonPath.JPath.EnsureLength(), System.list, Newtonsoft.Json.Linq.JsonPath.JPath.ReadQuotedString(), and System.text.
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer().