Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.Evaluate
Evaluate() [1/2]
IEnumerable< JToken > Newtonsoft.Json.Linq.JsonPath.JPath.Evaluate (JToken root, JToken t, bool errorWhenNoMatch) inline package
Definition at line 739 of file JPath.cs.
        {
            return JPath.Evaluate(this.Filters, root, t, errorWhenNoMatch);
        }
References Newtonsoft.Json.Linq.JsonPath.JPath.Evaluate(), and Newtonsoft.Json.Linq.JsonPath.JPath.Filters.
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.Evaluate(), Newtonsoft.Json.Linq.JsonPath.BooleanQueryExpression.GetResult(), and Newtonsoft.Json.Linq.JToken.SelectTokens().