Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression
ParseExpression()
QueryExpression Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression () inline private
Definition at line 441 of file JPath.cs.
        {
            QueryExpression queryExpression = null;
            CompositeExpression compositeExpression = null;
            while (this._currentIndex < this._expression.Length)
            {
                object obj = this.ParseSide();
                object obj2 = null;
                QueryOperator queryOperator;
                if (this._expression.get_Chars(this._currentIndex) == ')' || this._expression.get_Chars(this._currentIndex) == '|' || this._expression.get_Chars(this._currentIndex) == '&')
                {
                    queryOperator = QueryOperator.Exists;
                }
                else
                {
                    queryOperator = this.ParseOperator();
                    obj2 = this.ParseSide();
                }
                BooleanQueryExpression booleanQueryExpression = new BooleanQueryExpression
                {
                    Left = obj,
                    Operator = queryOperator,
                    Right = obj2
                };
                if (this._expression.get_Chars(this._currentIndex) == ')')
                {
                    if (compositeExpression != null)
                    {
                        compositeExpression.Expressions.Add(booleanQueryExpression);
                        return queryExpression;
                    }
                    return booleanQueryExpression;
                }
                else
                {
                    if (this._expression.get_Chars(this._currentIndex) == '&')
                    {
                        if (!this.Match("&&"))
{
                            throw this.CreateUnexpectedCharacterException();
                        }
                        if (compositeExpression == null || compositeExpression.Operator != QueryOperator.And)
{
                            CompositeExpression compositeExpression2 = new CompositeExpression
{
                                Operator = QueryOperator.And
                            };
                            if (compositeExpression != null)
{
                                compositeExpression.Expressions.Add(compositeExpression2);
                            }
                            compositeExpression = compositeExpression2;
                            if (queryExpression == null)
{
                                queryExpression = compositeExpression;
                            }
                        }
                        compositeExpression.Expressions.Add(booleanQueryExpression);
                    }
                    if (this._expression.get_Chars(this._currentIndex) == '|')
                    {
                        if (!this.Match("||"))
{
                            throw this.CreateUnexpectedCharacterException();
                        }
                        if (compositeExpression == null || compositeExpression.Operator != QueryOperator.Or)
{
                            CompositeExpression compositeExpression3 = new CompositeExpression
{
                                Operator = QueryOperator.Or
                            };
                            if (compositeExpression != null)
{
                                compositeExpression.Expressions.Add(compositeExpression3);
                            }
                            compositeExpression = compositeExpression3;
                            if (queryExpression == null)
{
                                queryExpression = compositeExpression;
                            }
                        }
                        compositeExpression.Expressions.Add(booleanQueryExpression);
                    }
                }
            }
            throw new JsonException("Path ended with open query.");
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, Newtonsoft.Json.Linq.JsonPath.JPath.CreateUnexpectedCharacterException(), Newtonsoft.Json.Linq.JsonPath.CompositeExpression.Expressions, Newtonsoft.Json.Linq.JsonPath.JPath.Match(), System.obj, Newtonsoft.Json.Linq.JsonPath.QueryExpression.Operator, Newtonsoft.Json.Linq.JsonPath.JPath.ParseOperator(), and Newtonsoft.Json.Linq.JsonPath.JPath.ParseSide().
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuery().