Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ReadQuotedString
ReadQuotedString()
string Newtonsoft.Json.Linq.JsonPath.JPath.ReadQuotedString () inline private
Definition at line 594 of file JPath.cs.
        {
            StringBuilder stringBuilder = new StringBuilder();
            this._currentIndex++;
            while (this._currentIndex < this._expression.Length)
            {
                char c = this._expression.get_Chars(this._currentIndex);
                if (c == '\\' && this._currentIndex + 1 < this._expression.Length)
                {
                    this._currentIndex++;
                    if (this._expression.get_Chars(this._currentIndex) == '\'')
                    {
                        stringBuilder.Append('\'');
                    }
                    else
                    {
                        if (this._expression.get_Chars(this._currentIndex) != '\\')
{
                            throw new JsonException("Unknown escape character: \\" + this._expression.get_Chars(this._currentIndex).ToString());
                        }
                        stringBuilder.Append('\\');
                    }
                    this._currentIndex++;
                }
                else
                {
                    if (c == '\'')
                    {
                        this._currentIndex++;
                        return stringBuilder.ToString();
                    }
                    this._currentIndex++;
                    stringBuilder.Append(c);
                }
            }
            throw new JsonException("Path ended with an open string.");
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, System.Text.StringBuilder.Append(), and System.Text.StringBuilder.ToString().
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseQuotedField(), and Newtonsoft.Json.Linq.JsonPath.JPath.TryParseValue().