Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.TryParseValue
TryParseValue()
bool Newtonsoft.Json.Linq.JsonPath.JPath.TryParseValue (out object value) inline private
Definition at line 530 of file JPath.cs.
        {
            char c = this._expression.get_Chars(this._currentIndex);
            if (c == '\'')
            {
                value = this.ReadQuotedString();
                return true;
            }
            if (char.IsDigit(c) || c == '-')
            {
                StringBuilder stringBuilder = new StringBuilder();
                stringBuilder.Append(c);
                this._currentIndex++;
                while (this._currentIndex < this._expression.Length)
                {
                    c = this._expression.get_Chars(this._currentIndex);
                    if (c == ' ' || c == ')')
                    {
                        string text = stringBuilder.ToString();
                        if (text.IndexOfAny(new char[] { '.', 'E', 'e' }) != -1)
{
                            double num;
                            bool flag = double.TryParse(text, 231, CultureInfo.InvariantCulture, ref num);
                            value = num;
                            return flag;
                        }
                        long num2;
                        bool flag2 = long.TryParse(text, 7, CultureInfo.InvariantCulture, ref num2);
                        value = num2;
                        return flag2;
                    }
                    else
                    {
                        stringBuilder.Append(c);
                        this._currentIndex++;
                    }
                }
            }
            else if (c == 't')
            {
                if (this.Match("true"))
                {
                    value = true;
                    return true;
                }
            }
            else if (c == 'f')
            {
                if (this.Match("false"))
                {
                    value = false;
                    return true;
                }
            }
            else if (c == 'n' && this.Match("null"))
            {
                value = null;
                return true;
            }
            value = null;
            return false;
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, System.Text.StringBuilder.Append(), System.Globalization.CultureInfo.InvariantCulture, Newtonsoft.Json.Linq.JsonPath.JPath.Match(), Newtonsoft.Json.Linq.JsonPath.JPath.ReadQuotedString(), System.text, System.Text.StringBuilder.ToString(), and System.value.
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseSide().