Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.Match
Match()
bool Newtonsoft.Json.Linq.JsonPath.JPath.Match (string s) inline private
Definition at line 633 of file JPath.cs.
        {
            int num = this._currentIndex;
            for (int i = 0; i < s.Length; i++)
            {
                char c = s.get_Chars(i);
                if (num >= this._expression.Length || this._expression.get_Chars(num) != c)
                {
                    return false;
                }
                num++;
            }
            this._currentIndex = num;
            return true;
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, and System.s.
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseExpression(), Newtonsoft.Json.Linq.JsonPath.JPath.ParseOperator(), and Newtonsoft.Json.Linq.JsonPath.JPath.TryParseValue().