Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath
ParsePath()
bool Newtonsoft.Json.Linq.JsonPath.JPath.ParsePath (List< PathFilter > filters, int currentPartStartIndex, bool query) inline private
Definition at line 67 of file JPath.cs.
        {
            bool flag = false;
            bool flag2 = false;
            bool flag3 = false;
            bool flag4 = false;
            while (this._currentIndex < this._expression.Length && !flag4)
            {
                char c = this._expression.get_Chars(this._currentIndex);
                if (c <= ')')
                {
                    if (c != ' ')
                    {
                        if (c != '(')
{
                            if (c != ')')
{
                                goto IL_0187;
                            }
                            goto IL_00CB;
                        }
                    }
                    else
                    {
                        if (this._currentIndex < this._expression.Length)
{
                            flag4 = true;
                            continue;
                        }
                        continue;
                    }
                }
                else
                {
                    if (c == '.')
                    {
                        if (this._currentIndex > currentPartStartIndex)
{
                            string text = this._expression.Substring(currentPartStartIndex, this._currentIndex - currentPartStartIndex);
                            if (text == "*")
{
                                text = null;
                            }
                            filters.Add(JPath.CreatePathFilter(text, flag));
                            flag = false;
                        }
                        if (this._currentIndex + 1 < this._expression.Length && this._expression.get_Chars(this._currentIndex + 1) == '.')
{
                            flag = true;
                            this._currentIndex++;
                        }
                        this._currentIndex++;
                        currentPartStartIndex = this._currentIndex;
                        flag2 = false;
                        flag3 = true;
                        continue;
                    }
                    if (c != '[')
                    {
                        if (c != ']')
{
                            goto IL_0187;
                        }
                        goto IL_00CB;
                    }
                }
                if (this._currentIndex > currentPartStartIndex)
                {
                    string text2 = this._expression.Substring(currentPartStartIndex, this._currentIndex - currentPartStartIndex);
                    if (text2 == "*")
                    {
                        text2 = null;
                    }
                    filters.Add(JPath.CreatePathFilter(text2, flag));
                    flag = false;
                }
                filters.Add(this.ParseIndexer(c, flag));
                this._currentIndex++;
                currentPartStartIndex = this._currentIndex;
                flag2 = true;
                flag3 = false;
                continue;
                IL_00CB:
                flag4 = true;
                continue;
                IL_0187:
                if (query && (c == '=' || c == '<' || c == '!' || c == '>' || c == '|' || c == '&'))
                {
                    flag4 = true;
                }
                else
                {
                    if (flag2)
                    {
                        throw new JsonException("Unexpected character following indexer: " + c.ToString());
                    }
                    this._currentIndex++;
                }
            }
            bool flag5 = this._currentIndex == this._expression.Length;
            if (this._currentIndex > currentPartStartIndex)
            {
                string text3 = this._expression.Substring(currentPartStartIndex, this._currentIndex - currentPartStartIndex).TrimEnd(new char[0]);
                if (text3 == "*")
                {
                    text3 = null;
                }
                filters.Add(JPath.CreatePathFilter(text3, flag));
            }
            else if (flag3 && (flag5 || query))
            {
                throw new JsonException("Unexpected end while parsing path.");
            }
            return flag5;
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, System.Collections.Generic.List< T >.Add(), Newtonsoft.Json.Linq.JsonPath.JPath.CreatePathFilter(), Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer(), and System.text.
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseMain(), and Newtonsoft.Json.Linq.JsonPath.JPath.TryParseExpression().