Terraria Decompiled: Newtonsoft.Json.Linq.JsonPath.JPath.ParseArrayIndexer
ParseArrayIndexer()
PathFilter Newtonsoft.Json.Linq.JsonPath.JPath.ParseArrayIndexer (char indexerCloseChar) inline private
Definition at line 218 of file JPath.cs.
        {
            int num = this._currentIndex;
            int? num2 = default(int?);
            List<int> list = null;
            int num3 = 0;
            int? num4 = default(int?);
            int? num5 = default(int?);
            int? num6 = default(int?);
            while (this._currentIndex < this._expression.Length)
            {
                char c = this._expression.get_Chars(this._currentIndex);
                if (c == ' ')
                {
                    num2 = new int?(this._currentIndex);
                    this.EatWhitespace();
                }
                else if (c == indexerCloseChar)
                {
                    int num7 = (num2 ?? this._currentIndex) - num;
                    if (list != null)
                    {
                        if (num7 == 0)
{
                            throw new JsonException("Array index expected.");
                        }
                        int num8 = Convert.ToInt32(this._expression.Substring(num, num7), CultureInfo.InvariantCulture);
                        list.Add(num8);
                        return new ArrayMultipleIndexFilter
{
                            Indexes = list
                        };
                    }
                    else
                    {
                        if (num3 > 0)
{
                            if (num7 > 0)
{
                                int num9 = Convert.ToInt32(this._expression.Substring(num, num7), CultureInfo.InvariantCulture);
                                if (num3 == 1)
{
                                    num5 = new int?(num9);
                                }
                                else
{
                                    num6 = new int?(num9);
                                }
                            }
                            return new ArraySliceFilter
{
                                Start = num4,
                                End = num5,
                                Step = num6
                            };
                        }
                        if (num7 == 0)
{
                            throw new JsonException("Array index expected.");
                        }
                        int num10 = Convert.ToInt32(this._expression.Substring(num, num7), CultureInfo.InvariantCulture);
                        return new ArrayIndexFilter
{
                            Index = new int?(num10)
                        };
                    }
                }
                else if (c == ',')
                {
                    int num11 = (num2 ?? this._currentIndex) - num;
                    if (num11 == 0)
                    {
                        throw new JsonException("Array index expected.");
                    }
                    if (list == null)
                    {
                        list = new List<int>();
                    }
                    string text = this._expression.Substring(num, num11);
                    list.Add(Convert.ToInt32(text, CultureInfo.InvariantCulture));
                    this._currentIndex++;
                    this.EatWhitespace();
                    num = this._currentIndex;
                    num2 = default(int?);
                }
                else if (c == '*')
                {
                    this._currentIndex++;
                    this.EnsureLength("Path ended with open indexer.");
                    this.EatWhitespace();
                    if (this._expression.get_Chars(this._currentIndex) != indexerCloseChar)
                    {
                        throw new JsonException("Unexpected character while parsing path indexer: " + c.ToString());
                    }
                    return new ArrayIndexFilter();
                }
                else if (c == ':')
                {
                    int num12 = (num2 ?? this._currentIndex) - num;
                    if (num12 > 0)
                    {
                        int num13 = Convert.ToInt32(this._expression.Substring(num, num12), CultureInfo.InvariantCulture);
                        if (num3 == 0)
{
                            num4 = new int?(num13);
                        }
                        else if (num3 == 1)
{
                            num5 = new int?(num13);
                        }
                        else
{
                            num6 = new int?(num13);
                        }
                    }
                    num3++;
                    this._currentIndex++;
                    this.EatWhitespace();
                    num = this._currentIndex;
                    num2 = default(int?);
                }
                else
                {
                    if (!char.IsDigit(c) && c != '-')
                    {
                        throw new JsonException("Unexpected character while parsing path indexer: " + c.ToString());
                    }
                    if (num2 != null)
                    {
                        throw new JsonException("Unexpected character while parsing path indexer: " + c.ToString());
                    }
                    this._currentIndex++;
                }
            }
            throw new JsonException("Path ended with open indexer.");
        }
References Newtonsoft.Json.Linq.JsonPath.JPath._currentIndex, Newtonsoft.Json.Linq.JsonPath.JPath._expression, Newtonsoft.Json.Linq.JsonPath.JPath.EatWhitespace(), System.End, Newtonsoft.Json.Linq.JsonPath.JPath.EnsureLength(), System.Globalization.CultureInfo.InvariantCulture, System.list, Newtonsoft.Json.Start, System.text, and System.Convert.ToInt32().
Referenced by Newtonsoft.Json.Linq.JsonPath.JPath.ParseIndexer().