Terraria Decompiled: System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive
ThrowLastBytesRecursive()
void System.Text.DecoderFallbackBuffer.ThrowLastBytesRecursive (byte[] bytesUnknown) inline package
Definition at line 129 of file DecoderFallbackBuffer.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(bytesUnknown.Length * 3);
            int num = 0;
            while (num < bytesUnknown.Length && num < 20)
            {
                if (stringBuilder.Length > 0)
                {
                    stringBuilder.Append(' ');
                }
                stringBuilder.AppendFormat(CultureInfo.InvariantCulture, "\\x{0:X2}", bytesUnknown[num]);
                num++;
            }
            if (num == 20)
            {
                stringBuilder.Append(" ...");
            }
            throw new ArgumentException(SR.Format("Recursive fallback not allowed for bytes {0}.", stringBuilder.ToString()), "bytesUnknown");
        }
References System.Text.StringBuilder.Append(), System.Text.StringBuilder.AppendFormat(), SR.Format(), System.Globalization.CultureInfo.InvariantCulture, System.Text.StringBuilder.Length, and System.Text.StringBuilder.ToString().