Terraria Decompiled: Terraria.GameContent.NetModules.NetParticlesModule.Serialize
Serialize()
static NetPacket Terraria.GameContent.NetModules.NetParticlesModule.Serialize (ParticleOrchestraType particleType, ParticleOrchestraSettings settings) inline static
Definition at line 12 of file NetParticlesModule.cs.
        {
            NetPacket netPacket = NetModule.CreatePacket<NetParticlesModule>(22);
            netPacket.Writer.Write((byte)particleType);
            settings.Serialize(netPacket.Writer);
            return netPacket;
        }
References Terraria.GameContent.Drawing.ParticleOrchestraSettings.Serialize(), System.IO.BinaryWriter.Write(), and Terraria.Net.NetPacket.Writer.
Referenced by Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastOrRequestParticleSpawn(), Terraria.GameContent.Drawing.ParticleOrchestrator.BroadcastParticleSpawn(), Terraria.GameContent.NetModules.NetParticlesModule.Deserialize(), and Terraria.GameContent.Drawing.ParticleOrchestrator.RequestParticleSpawn().