Terraria Decompiled: System.Runtime.Serialization.ObjectCloneHelper.PrepareConstructorArgs
PrepareConstructorArgs()
static SerializationInfo System.Runtime.Serialization.ObjectCloneHelper.PrepareConstructorArgs (object serObj, string[] fieldNames, object[] fieldValues, out StreamingContext context) inline static package
Definition at line 66 of file ObjectCloneHelper.cs.
        {
            SerializationInfo serializationInfo = null;
            if (serObj is ISerializable)
            {
                serializationInfo = new SerializationInfo(serObj.GetType(), ObjectCloneHelper.s_converter);
                for (int i = 0; i < fieldNames.Length; i++)
                {
                    if (fieldNames[i] != null)
                    {
                        serializationInfo.AddValue(fieldNames[i], fieldValues[i]);
                    }
                }
            }
            else
            {
                Hashtable hashtable = new Hashtable();
                int j = 0;
                int num = 0;
                while (j < fieldNames.Length)
                {
                    if (fieldNames[j] != null)
                    {
                        hashtable[fieldNames[j]] = fieldValues[j];
                        num++;
                    }
                    j++;
                }
                MemberInfo[] serializableMembers = FormatterServices.GetSerializableMembers(serObj.GetType());
                for (int k = 0; k < serializableMembers.Length; k++)
                {
                    string name = serializableMembers[k].Name;
                    if (!hashtable.Contains(name))
                    {
                        object[] customAttributes = serializableMembers[k].GetCustomAttributes(typeof(OptionalFieldAttribute), false);
                        if (customAttributes == null || customAttributes.Length == 0)
{
                            throw new SerializationException(Environment.GetResourceString("Member '{0}' in class '{1}' is not present in the serialized stream and is not marked with {2}.", new object[]
{
                                serializableMembers[k],
                                serObj.GetType(),
                                typeof(OptionalFieldAttribute).FullName
                            }));
                        }
                    }
                    else
                    {
                        object obj = hashtable[name];
                        FormatterServices.SerializationSetValue(serializableMembers[k], serObj, obj);
                    }
                }
            }
            context = ObjectCloneHelper.s_cloneContext;
            return serializationInfo;
        }
References System.Runtime.Serialization.SerializationInfo.AddValue(), System.Collections.Hashtable.Contains(), System.Reflection.MemberInfo.GetCustomAttributes(), System.Environment.GetResourceString(), System.Runtime.Serialization.FormatterServices.GetSerializableMembers(), System.name, System.Reflection.MemberInfo.Name, System.obj, System.Runtime.Serialization.ObjectCloneHelper.s_cloneContext, System.Runtime.Serialization.ObjectCloneHelper.s_converter, and System.Runtime.Serialization.FormatterServices.SerializationSetValue().