Terraria Decompiled: Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Update
Update()
void Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Update (BestiaryUICollectionInfo providedInfo, Rectangle hitbox, EntryIconDrawSettings settings) inline
Implements Terraria.GameContent.Bestiary.IEntryIcon.
Definition at line 36 of file UnlockableNPCEntryIcon.cs.
        {
            Vector2 vector = default(Vector2);
            int? num = null;
            int? num2 = null;
            int? num3 = null;
            bool flag = false;
            float num4 = 0f;
            Asset<Texture2D> asset = null;
            NPCID.Sets.NPCBestiaryDrawModifiers npcbestiaryDrawModifiers;
            if (NPCID.Sets.NPCBestiaryDrawOffset.TryGetValue(this._npcNetId, out npcbestiaryDrawModifiers))
            {
                this._npcCache.rotation = npcbestiaryDrawModifiers.Rotation;
                this._npcCache.scale = npcbestiaryDrawModifiers.Scale;
                if (npcbestiaryDrawModifiers.PortraitScale != null && settings.IsPortrait)
                {
                    this._npcCache.scale = npcbestiaryDrawModifiers.PortraitScale.Value;
                }
                vector = npcbestiaryDrawModifiers.Position;
                num = npcbestiaryDrawModifiers.Frame;
                num2 = npcbestiaryDrawModifiers.Direction;
                num3 = npcbestiaryDrawModifiers.SpriteDirection;
                num4 = npcbestiaryDrawModifiers.Velocity;
                flag = npcbestiaryDrawModifiers.IsWet;
                if (npcbestiaryDrawModifiers.PortraitPositionXOverride != null && settings.IsPortrait)
                {
                    vector.X = npcbestiaryDrawModifiers.PortraitPositionXOverride.Value;
                }
                if (npcbestiaryDrawModifiers.PortraitPositionYOverride != null && settings.IsPortrait)
                {
                    vector.Y = npcbestiaryDrawModifiers.PortraitPositionYOverride.Value;
                }
                if (npcbestiaryDrawModifiers.CustomTexturePath != null)
                {
                    asset = Main.Assets.Request<Texture2D>(npcbestiaryDrawModifiers.CustomTexturePath, 1);
                }
                if (asset != null && asset.IsLoaded)
                {
                    this._customTexture = asset;
                }
            }
            this._positionOffsetCache = vector;
            this.UpdatePosition(settings);
            if (NPCID.Sets.TrailingMode[this._npcCache.type] != -1)
            {
                for (int i = 0; i < this._npcCache.oldPos.Length; i++)
                {
                    this._npcCache.oldPos[i] = this._npcCache.position;
                }
            }
            this._npcCache.direction = (this._npcCache.spriteDirection = ((num2 != null) ? num2.Value : (-1)));
            if (num3 != null)
            {
                this._npcCache.spriteDirection = num3.Value;
            }
            this._npcCache.wet = flag;
            this.AdjustSpecialSpawnRulesForVisuals(settings);
            this.SimulateFirstHover(num4);
            if (num == null && (settings.IsPortrait || settings.IsHovered))
            {
                this._npcCache.velocity.X = (float)this._npcCache.direction * num4;
                this._npcCache.FindFrame();
                return;
            }
            if (num != null)
            {
                this._npcCache.FindFrame();
                this._npcCache.frame.Y = this._npcCache.frame.Height * num.Value;
            }
        }
References Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon._npcCache, Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.AdjustSpecialSpawnRulesForVisuals(), Terraria.Main.Assets, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.CustomTexturePath, Terraria.Entity.direction, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.Direction, Terraria.NPC.FindFrame(), Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.Frame, Terraria.GameContent.Bestiary.EntryIconDrawSettings.IsHovered, ReLogic.Content.Asset< T >.IsLoaded, Terraria.GameContent.Bestiary.EntryIconDrawSettings.IsPortrait, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.IsWet, Microsoft.Xna.Framework.Vector2.Length(), Terraria.ID.NPCID.Sets.NPCBestiaryDrawOffset, Terraria.NPC.oldPos, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.PortraitPositionXOverride, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.PortraitPositionYOverride, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.PortraitScale, Terraria.Entity.position, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.Position, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.Rotation, Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.Scale, Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.SimulateFirstHover(), Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.SpriteDirection, Terraria.ID.NPCID.Sets.TrailingMode, Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.UpdatePosition(), and Terraria.ID.NPCID.Sets.NPCBestiaryDrawModifiers.Velocity.