Terraria Decompiled: Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.AdjustSpecialSpawnRulesForVisuals
AdjustSpecialSpawnRulesForVisuals()
void Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.AdjustSpecialSpawnRulesForVisuals (EntryIconDrawSettings settings) inline private
Definition at line 122 of file UnlockableNPCEntryIcon.cs.
        {
            int num;
            if (NPCID.Sets.SpecialSpawningRules.TryGetValue(this._npcNetId, out num) && num == 0)
            {
                Point point = (this._npcCache.position - this._npcCache.rotation.ToRotationVector2() * -1600f).ToTileCoordinates();
                this._npcCache.ai[0] = (float)point.X;
                this._npcCache.ai[1] = (float)point.Y;
            }
            int npcNetId = this._npcNetId;
            if (npcNetId <= 539)
            {
                if (npcNetId <= 330)
                {
                    if (npcNetId == 244)
                    {
                        this._npcCache.AI_001_SetRainbowSlimeColor();
                        return;
                    }
                    if (npcNetId == 299)
                    {
                        goto IL_0135;
                    }
                    if (npcNetId != 330)
                    {
                        return;
                    }
                }
                else
                {
                    if (npcNetId == 356)
                    {
                        this._npcCache.ai[2] = 1f;
                        return;
                    }
                    if (npcNetId != 372)
                    {
                        if (npcNetId - 538 > 1)
{
                            return;
                        }
                        goto IL_0135;
                    }
                }
            }
            else if (npcNetId <= 636)
            {
                if (npcNetId - 586 > 1 && npcNetId - 619 > 1)
                {
                    if (npcNetId != 636)
                    {
                        return;
                    }
                    this._npcCache.Opacity = 1f;
                    float[] localAI = this._npcCache.localAI;
                    int num2 = 0;
                    float num3 = localAI[num2] + 1f;
                    localAI[num2] = num3;
                    if (num3 >= 44f)
                    {
                        this._npcCache.localAI[0] = 0f;
                        return;
                    }
                    return;
                }
            }
            else
            {
                if (npcNetId - 639 <= 6)
                {
                    goto IL_0135;
                }
                if (npcNetId == 656)
                {
                    this._npcCache.townNpcVariationIndex = 1;
                    return;
                }
                if (npcNetId != 670)
                {
                    return;
                }
                this._npcCache.townNpcVariationIndex = 0;
                return;
            }
            this._npcCache.alpha = 0;
            return;
            IL_0135:
            if (settings.IsPortrait && this._npcCache.frame.Y == 0)
            {
                this._npcCache.frame.Y = this._npcCache.frame.Height;
                return;
            }
        }
References Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon._npcCache, Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon._npcNetId, Terraria.NPC.ai, Terraria.NPC.AI_001_SetRainbowSlimeColor(), Terraria.NPC.frame, Microsoft.Xna.Framework.Rectangle.Height, Terraria.GameContent.Bestiary.EntryIconDrawSettings.IsPortrait, Terraria.NPC.localAI, Terraria.NPC.rotation, Terraria.ID.NPCID.Sets.SpecialSpawningRules, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.GameContent.Bestiary.UnlockableNPCEntryIcon.Update().