Terraria Decompiled: Terraria.UI.AchievementAdvisor.DrawMouseHover
DrawMouseHover()
void Terraria.UI.AchievementAdvisor.DrawMouseHover () inline
Definition at line 127 of file AchievementAdvisor.cs.
        {
            if (this._hoveredCard == null)
            {
                return;
            }
            Main.spriteBatch.End();
            Main.spriteBatch.Begin(SpriteSortMode.Deferred, null, null, null, null, null, Main.UIScaleMatrix);
            PlayerInput.SetZoom_UI();
            Item item = Main.DisplayAndGetFakeItem(ItemRarityColor.StrongRed10);
            item.SetNameOverride(this._hoveredCard.achievement.FriendlyName.Value);
            item.ToolTip = ItemTooltip.FromLanguageKey(this._hoveredCard.achievement.Description.Key);
        }
References Terraria.UI.AchievementAdvisor._hoveredCard, Terraria.UI.AchievementAdvisorCard.achievement, Microsoft.Xna.Framework.Graphics.SpriteBatch.Begin(), Terraria.Achievements.Achievement.Description, Terraria.Main.DisplayAndGetFakeItem(), Microsoft.Xna.Framework.Graphics.SpriteBatch.End(), Terraria.Achievements.Achievement.FriendlyName, Terraria.UI.ItemTooltip.FromLanguageKey(), System.item, Terraria.Item.SetNameOverride(), Terraria.GameInput.PlayerInput.SetZoom_UI(), Terraria.Main.spriteBatch, and Terraria.Main.UIScaleMatrix.
Referenced by Terraria.Main.DrawMouseOver().