Terraria Decompiled: Terraria.UI.AchievementAdvisor.DrawCard
DrawCard()
void Terraria.UI.AchievementAdvisor.DrawCard (AchievementAdvisorCard card, SpriteBatch spriteBatch, Vector2 position, float scale, out bool hovered) inline private
Definition at line 142 of file AchievementAdvisor.cs.
        {
            hovered = false;
            if (Main.MouseScreen.Between(position, position + card.frame.Size() * scale) && !PlayerInput.IgnoreMouseInterface)
            {
                Main.LocalPlayer.mouseInterface = true;
                hovered = true;
            }
            Color white = Color.White;
            if (!hovered)
            {
                white = new Color(220, 220, 220, 220);
            }
            Vector2 vector = new Vector2(-4f) * scale;
            Vector2 vector2 = new Vector2(-8f) * scale;
            Texture2D texture2D = this._achievementsBorderMouseHoverFatTexture.Value;
            if (scale > 0.5f)
            {
                texture2D = this._achievementsBorderMouseHoverThinTexture.Value;
                vector2 = new Vector2(-5f) * scale;
            }
            Rectangle frame = card.frame;
            frame.X += 528;
            spriteBatch.Draw(this._achievementsTexture.Value, position, new Rectangle?(frame), white, 0f, Vector2.Zero, scale, SpriteEffects.None, 0f);
            spriteBatch.Draw(this._achievementsBorderTexture.Value, position + vector, null, white, 0f, Vector2.Zero, scale, SpriteEffects.None, 0f);
            if (hovered)
            {
                spriteBatch.Draw(texture2D, position + vector2, null, Main.OurFavoriteColor, 0f, Vector2.Zero, scale, SpriteEffects.None, 0f);
            }
        }
References Terraria.UI.AchievementAdvisor._achievementsBorderMouseHoverFatTexture, Terraria.UI.AchievementAdvisor._achievementsBorderMouseHoverThinTexture, Terraria.UI.AchievementAdvisor._achievementsBorderTexture, Terraria.UI.AchievementAdvisor._achievementsTexture, Microsoft.Xna.Framework.Graphics.Color, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.UI.AchievementAdvisorCard.frame, Terraria.GameInput.PlayerInput.IgnoreMouseInterface, Terraria.Main.MouseScreen, Terraria.Main.OurFavoriteColor, ReLogic.Content.Asset< T >.Value, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, and Microsoft.Xna.Framework.Vector2.Zero.
Referenced by Terraria.UI.AchievementAdvisor.DrawOneAchievement(), and Terraria.UI.AchievementAdvisor.DrawOptionsPanel().