Terraria Decompiled: Terraria.UI.AchievementAdvisor.DrawOptionsPanel
DrawOptionsPanel()
void Terraria.UI.AchievementAdvisor.DrawOptionsPanel (SpriteBatch spriteBatch, Vector2 leftPosition, Vector2 rightPosition) inline
Definition at line 84 of file AchievementAdvisor.cs.
        {
            List<AchievementAdvisorCard> bestCards = this.GetBestCards(10);
            this._hoveredCard = null;
            int num = bestCards.Count;
            if (num > 5)
            {
                num = 5;
            }
            for (int i = 0; i < num; i++)
            {
                bool flag;
                this.DrawCard(bestCards[i], spriteBatch, leftPosition + new Vector2((float)(42 * i), 0f), 0.5f, out flag);
                if (flag)
                {
                    this._hoveredCard = bestCards[i];
                }
            }
            for (int j = 5; j < bestCards.Count; j++)
            {
                bool flag;
                this.DrawCard(bestCards[j], spriteBatch, rightPosition + new Vector2((float)(42 * j), 0f), 0.5f, out flag);
                if (flag)
                {
                    this._hoveredCard = bestCards[j];
                }
            }
            if (this._hoveredCard != null)
            {
                if (this._hoveredCard.achievement.IsCompleted)
                {
                    this._hoveredCard = null;
                    return;
                }
                if (Main.mouseLeft && Main.mouseLeftRelease)
                {
                    Main.ingameOptionsWindow = false;
                    IngameFancyUI.OpenAchievementsAndGoto(this._hoveredCard.achievement);
                }
            }
        }
References Terraria.UI.AchievementAdvisor._hoveredCard, Terraria.UI.AchievementAdvisorCard.achievement, System.Collections.Generic.List< T >.Count, Terraria.UI.AchievementAdvisor.DrawCard(), Terraria.UI.AchievementAdvisor.GetBestCards(), Terraria.Achievements.Achievement.IsCompleted, Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.UI.IngameFancyUI.OpenAchievementsAndGoto(), and Microsoft.Xna.Framework.Graphics.Vector2.