Terraria Decompiled: Terraria.UI.AchievementAdvisor.DrawOneAchievement
DrawOneAchievement()
void Terraria.UI.AchievementAdvisor.DrawOneAchievement (SpriteBatch spriteBatch, Vector2 position, bool large) inline
Definition at line 48 of file AchievementAdvisor.cs.
        {
            List<AchievementAdvisorCard> bestCards = this.GetBestCards(1);
            if (bestCards.Count < 1)
            {
                return;
            }
            AchievementAdvisorCard achievementAdvisorCard = bestCards[0];
            float num = 0.35f;
            if (large)
            {
                num = 0.75f;
            }
            this._hoveredCard = null;
            bool flag;
            this.DrawCard(bestCards[0], spriteBatch, position + new Vector2(8f) * num, num, out flag);
            if (flag)
            {
                this._hoveredCard = achievementAdvisorCard;
                if (Main.mouseLeft && Main.mouseLeftRelease)
                {
                    Main.ingameOptionsWindow = false;
                    IngameFancyUI.OpenAchievementsAndGoto(this._hoveredCard.achievement);
                    SoundEngine.PlaySound(12, -1, -1, 1, 1f, 0f);
                }
            }
            Main.DoStatefulTickSound(ref Main.achievementAdvisorMouseOver, flag);
        }
References Terraria.UI.AchievementAdvisor._hoveredCard, Terraria.UI.AchievementAdvisorCard.achievement, Terraria.Main.achievementAdvisorMouseOver, System.Collections.Generic.List< T >.Count, Terraria.Main.DoStatefulTickSound(), Terraria.UI.AchievementAdvisor.DrawCard(), Terraria.UI.AchievementAdvisor.GetBestCards(), Terraria.Main.mouseLeft, Terraria.Main.mouseLeftRelease, Terraria.UI.IngameFancyUI.OpenAchievementsAndGoto(), Terraria.Audio.SoundEngine.PlaySound(), and Microsoft.Xna.Framework.Graphics.Vector2.