Terraria Decompiled: Terraria.GameContent.Drawing.WallDrawing.FullTile
FullTile()
bool Terraria.GameContent.Drawing.WallDrawing.FullTile (int x, int y) inline protected
Definition at line 252 of file WallDrawing.cs.
        {
            if (this._tileArray[x - 1, y] == null || this._tileArray[x - 1, y].blockType() != 0 || this._tileArray[x + 1, y] == null || this._tileArray[x + 1, y].blockType() != 0)
            {
                return false;
            }
            Tile tile = this._tileArray[x, y];
            if (tile == null)
            {
                return false;
            }
            if (tile.active())
            {
                if (Main.tileFrameImportant[(int)tile.type] || TileID.Sets.DrawsWalls[(int)tile.type])
                {
                    return false;
                }
                if (tile.invisibleBlock() && !this._shouldShowInvisibleWalls)
                {
                    return false;
                }
                if (DebugOptions.ShowUnbreakableWall && tile.wall == 350)
                {
                    return false;
                }
                if (tile.type == 740)
                {
                    short frameX = tile.frameX;
                    short frameY = tile.frameY;
                    if ((frameX == 180 || frameX == 198) && frameY >= 0 && frameY <= 36)
                    {
                        return false;
                    }
                    if (frameX >= 108 && frameX <= 144 && (frameY == 18 || frameY == 36))
                    {
                        return false;
                    }
                }
                if (Main.tileSolid[(int)tile.type] && !Main.tileSolidTop[(int)tile.type])
                {
                    int frameX2 = (int)tile.frameX;
                    int frameY2 = (int)tile.frameY;
                    if (Main.tileLargeFrames[(int)tile.type] > 0)
                    {
                        if (frameY2 == 18 || frameY2 == 108)
{
                            if (frameX2 >= 18 && frameX2 <= 54)
{
                                return true;
                            }
                            if (frameX2 >= 108 && frameX2 <= 144)
{
                                return true;
                            }
                        }
                    }
                    else if (frameY2 == 0)
                    {
                        if (frameX2 >= 180 && frameX2 <= 198)
{
                            return true;
                        }
                    }
                    else if (frameY2 == 18)
                    {
                        if (frameX2 >= 18 && frameX2 <= 54)
{
                            return true;
                        }
                        if (frameX2 >= 108 && frameX2 <= 144)
{
                            return true;
                        }
                        if (frameX2 >= 180 && frameX2 <= 198)
{
                            return true;
                        }
                    }
                    else if (frameY2 == 36)
                    {
                        if (frameX2 >= 108 && frameX2 <= 144)
{
                            return true;
                        }
                        if (frameX2 >= 180 && frameX2 <= 198)
{
                            return true;
                        }
                    }
                    else if (frameY2 >= 90 && frameY2 <= 180)
                    {
                        if (frameX2 <= 54)
{
                            return true;
                        }
                        if (frameX2 >= 144 && frameX2 <= 216)
{
                            return true;
                        }
                    }
                    else if (frameY2 == 198 && frameX2 >= 108 && frameX2 <= 144)
                    {
                        return true;
                    }
                }
            }
            return false;
        }
References Terraria.GameContent.Drawing.WallDrawing._tileArray, Terraria.Tile.active(), Terraria.ID.TileID.Sets.DrawsWalls, Terraria.Tile.frameX, Terraria.Tile.frameY, int, Terraria.Tile.invisibleBlock(), Terraria.Testing.DebugOptions.ShowUnbreakableWall, Terraria.Main.tileFrameImportant, Terraria.Main.tileLargeFrames, Terraria.Main.tileSolid, Terraria.Main.tileSolidTop, Terraria.Tile.type, and Terraria.Tile.wall.
Referenced by Terraria.GameContent.Drawing.WallDrawing.DrawWalls().