Terraria Decompiled: ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Render
Render()
override void ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Render (IEnumerable< RgbKey > keys) inline
Definition at line 18 of file RazerKeyboard.cs.
        {
            foreach (RgbKey rgbKey in keys)
            {
                RazerKey razerKey;
                if (RazerKeyboard.XnaKeyToChromaKey.TryGetValue(rgbKey.Key, ref razerKey))
                {
                    uint num = RazerHelper.XnaColorToDeviceColor(base.ProcessLedColor(rgbKey.CurrentColor));
                    this._pendingKeys.Add(Tuple.Create<RazerKey, uint>(razerKey, num));
                }
            }
        }
References ReLogic.Peripherals.RGB.Razer.RazerKeyboard._pendingKeys, System.Collections.Generic.List< T >.Add(), ReLogic.Peripherals.RGB.RgbKey.CurrentColor, ReLogic.Peripherals.RGB.RgbKey.Key, System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), ReLogic.Peripherals.RGB.Razer.RazerHelper.XnaColorToDeviceColor(), and ReLogic.Peripherals.RGB.Razer.RazerKeyboard.XnaKeyToChromaKey.