Terraria Decompiled: ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Present
Present()
override void ReLogic.Peripherals.RGB.Razer.RazerKeyboard.Present () inline
Definition at line 32 of file RazerKeyboard.cs.
        {
            for (int i = 0; i < this._effect.Color.Length; i++)
            {
                this._effect.Color[i] = 0U;
                this._effect.Key[i] = 0U;
            }
            for (int j = 0; j < base.LedCount; j++)
            {
                this._effect.Color[j] = RazerHelper.Vector4ToDeviceColor(base.GetProcessedLedColor(j));
                this._effect.Key[j] = this._effect.Color[j] & 16777215U;
            }
            for (int k = 0; k < this._pendingKeys.Count; k++)
            {
                int num = (int)this._pendingKeys[k].Item1;
                num = (num >> 8) * 22 + (num & 255);
                this._effect.Key[num] = this._pendingKeys[k].Item2 | 16777216U;
            }
            this._pendingKeys.Clear();
            this._handle.SetAsKeyboardEffect(ref this._effect);
            this._handle.Apply();
        }
References ReLogic.Peripherals.RGB.Razer.RazerKeyboard._effect, ReLogic.Peripherals.RGB.Razer.RazerKeyboard._handle, ReLogic.Peripherals.RGB.Razer.RazerKeyboard._pendingKeys, ReLogic.Peripherals.RGB.Razer.EffectHandle.Apply(), System.Collections.Generic.List< T >.Clear(), System.Collections.Generic.List< T >.Count, int, ReLogic.Peripherals.RGB.Razer.EffectHandle.SetAsKeyboardEffect(), ReLogic.Peripherals.RGB.Razer.U, and ReLogic.Peripherals.RGB.Razer.RazerHelper.Vector4ToDeviceColor().