Terraria Decompiled: ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.UpdateVisibility
UpdateVisibility()
void ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.UpdateVisibility (float timeElapsed) inline
Definition at line 136 of file ShaderSelector.cs.
            {
                this.IsActive = this.Condition.IsActive();
                if (this.IsActive)
                {
                    this.Opacity = Math.Min(1f, this.Opacity + timeElapsed);
                    return;
                }
                this.Opacity = Math.Max(0f, this.Opacity - timeElapsed);
            }
References ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.Condition, ReLogic.Peripherals.RGB.ChromaCondition.IsActive(), ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.IsActive, System.Math.Max(), System.Math.Min(), and ReLogic.Peripherals.RGB.ShaderSelector.ConditionalShader.Opacity.