Terraria Decompiled: System.Security.Cryptography.HashAlgorithm.ComputeHash
ComputeHash() [3/3]
byte[] System.Security.Cryptography.HashAlgorithm.ComputeHash (Stream inputStream) inline
Definition at line 121 of file HashAlgorithm.cs.
        {
            if (this._disposed)
            {
                throw new ObjectDisposedException(null);
            }
            byte[] array = ArrayPool<byte>.Shared.Rent(4096);
            byte[] array2;
            try
            {
                int num;
                while ((num = inputStream.Read(array, 0, array.Length)) > 0)
                {
                    this.HashCore(array, 0, num);
                }
                array2 = this.CaptureHashCodeAndReinitialize();
            }
            finally
            {
                CryptographicOperations.ZeroMemory(array);
                ArrayPool<byte>.Shared.Return(array, false);
            }
            return array2;
        }
References System.Security.Cryptography.HashAlgorithm._disposed, System.array, System.Security.Cryptography.HashAlgorithm.CaptureHashCodeAndReinitialize(), System.Security.Cryptography.HashAlgorithm.HashCore(), System.IO.Stream.Read(), System.Buffers.ArrayPool< T >.Shared, and System.Security.Cryptography.CryptographicOperations.ZeroMemory().