Terraria Decompiled: System.Security.Cryptography.HashAlgorithm.ComputeHash
ComputeHash() [1/3]
byte[] System.Security.Cryptography.HashAlgorithm.ComputeHash (byte[] buffer) inline
Definition at line 57 of file HashAlgorithm.cs.
        {
            if (this._disposed)
            {
                throw new ObjectDisposedException(null);
            }
            if (buffer == null)
            {
                throw new ArgumentNullException("buffer");
            }
            this.HashCore(buffer, 0, buffer.Length);
            return this.CaptureHashCodeAndReinitialize();
        }
References System.Security.Cryptography.HashAlgorithm._disposed, System.Security.Cryptography.HashAlgorithm.CaptureHashCodeAndReinitialize(), and System.Security.Cryptography.HashAlgorithm.HashCore().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.ComputeBaseValue(), System.Security.Policy.Hash.GenerateHash(), Mono.Security.Cryptography.DSAManaged.GenerateParams(), Mono.Security.Cryptography.PKCS1.GetEmptyHash(), System.IO.IsolatedStorage.IsolatedStorageFile.GetNameFromIdentity(), System.Security.Cryptography.DSACryptoServiceProvider.HashData(), System.Security.Cryptography.RSACryptoServiceProvider.HashData(), System.Security.Cryptography.DSACryptoServiceProvider.HashData(), System.Security.Cryptography.RSACryptoServiceProvider.HashData(), System.Security.Cryptography.HMAC.InitializeKey(), Mono.Security.Cryptography.PKCS1.MGF1(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), System.Security.Cryptography.DSACryptoServiceProvider.SignData(), System.Security.Cryptography.RSACryptoServiceProvider.SignData(), Mono.Security.StrongName.StrongHash(), System.Security.Cryptography.RSACryptoServiceProvider.VerifyData(), and System.Security.Cryptography.DSACryptoServiceProvider.VerifyData().