Terraria Decompiled: System.Security.Cryptography.HashAlgorithm.TransformFinalBlock
TransformFinalBlock()
byte[] System.Security.Cryptography.HashAlgorithm.TransformFinalBlock (byte[] inputBuffer, int inputOffset, int inputCount) inline
Implements System.Security.Cryptography.ICryptoTransform.
Definition at line 231 of file HashAlgorithm.cs.
        {
            this.ValidateTransformBlock(inputBuffer, inputOffset, inputCount);
            this.HashCore(inputBuffer, inputOffset, inputCount);
            this.HashValue = this.CaptureHashCodeAndReinitialize();
            byte[] array;
            if (inputCount != 0)
            {
                array = new byte[inputCount];
                Buffer.BlockCopy(inputBuffer, inputOffset, array, 0, inputCount);
            }
            else
            {
                array = Array.Empty<byte>();
            }
            this.State = 0;
            return array;
        }
References System.array, System.Buffer.BlockCopy(), System.Security.Cryptography.HashAlgorithm.CaptureHashCodeAndReinitialize(), System.Security.Cryptography.HashAlgorithm.HashCore(), and System.Security.Cryptography.HashAlgorithm.ValidateTransformBlock().
Referenced by System.Security.Cryptography.PasswordDeriveBytes.ComputeBaseValue(), Mono.Security.Cryptography.HMACAlgorithm.Final(), and System.Security.Cryptography.HMAC.HashFinal().