Terraria Decompiled: System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes
GetPseudoCustomAttributes()
object[] System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributes () inline package
Definition at line 430 of file RuntimeMethodInfo.cs.
        {
            int num = 0;
            MonoMethodInfo methodInfo = MonoMethodInfo.GetMethodInfo(this.mhandle);
            if ((methodInfo.iattrs & MethodImplAttributes.PreserveSig) != MethodImplAttributes.IL)
            {
                num++;
            }
            if ((methodInfo.attrs & MethodAttributes.PinvokeImpl) != MethodAttributes.PrivateScope)
            {
                num++;
            }
            if (num == 0)
            {
                return null;
            }
            object[] array = new object[num];
            num = 0;
            if ((methodInfo.iattrs & MethodImplAttributes.PreserveSig) != MethodImplAttributes.IL)
            {
                array[num++] = new PreserveSigAttribute();
            }
            if ((methodInfo.attrs & MethodAttributes.PinvokeImpl) != MethodAttributes.PrivateScope)
            {
                array[num++] = DllImportAttribute.GetCustomAttribute(this);
            }
            return array;
        }
References System.array, System.Reflection.MonoMethodInfo.attrs, System.Runtime.InteropServices.DllImportAttribute.GetCustomAttribute(), System.Reflection.MonoMethodInfo.GetMethodInfo(), System.Reflection.MonoMethodInfo.iattrs, and System.Reflection.RuntimeMethodInfo.mhandle.
Referenced by System.MonoCustomAttrs.GetPseudoCustomAttributes().