Terraria Decompiled: System.Reflection.RuntimeMethodInfo.GetDllImportAttributeData
GetDllImportAttributeData()
CustomAttributeData System.Reflection.RuntimeMethodInfo.GetDllImportAttributeData () inline private
Definition at line 490 of file RuntimeMethodInfo.cs.
        {
            if ((this.Attributes & MethodAttributes.PinvokeImpl) == MethodAttributes.PrivateScope)
            {
                return null;
            }
            string text = null;
            PInvokeAttributes pinvokeAttributes = PInvokeAttributes.CharSetNotSpec;
            string text2;
            this.GetPInvoke(out pinvokeAttributes, out text2, out text);
            CharSet charSet;
            switch (pinvokeAttributes & PInvokeAttributes.CharSetMask)
            {
            case PInvokeAttributes.CharSetNotSpec:
                charSet = CharSet.None;
                goto IL_005C;
            case PInvokeAttributes.CharSetAnsi:
                charSet = CharSet.Ansi;
                goto IL_005C;
            case PInvokeAttributes.CharSetUnicode:
                charSet = CharSet.Unicode;
                goto IL_005C;
            case PInvokeAttributes.CharSetMask:
                charSet = CharSet.Auto;
                goto IL_005C;
            }
            charSet = CharSet.None;
            IL_005C:
            PInvokeAttributes pinvokeAttributes2 = pinvokeAttributes & PInvokeAttributes.CallConvMask;
            CallingConvention callingConvention;
            if (pinvokeAttributes2 <= PInvokeAttributes.CallConvCdecl)
            {
                if (pinvokeAttributes2 == PInvokeAttributes.CallConvWinapi)
                {
                    callingConvention = global::System.Runtime.InteropServices.CallingConvention.Winapi;
                    goto IL_00BB;
                }
                if (pinvokeAttributes2 == PInvokeAttributes.CallConvCdecl)
                {
                    callingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl;
                    goto IL_00BB;
                }
            }
            else
            {
                if (pinvokeAttributes2 == PInvokeAttributes.CallConvStdcall)
                {
                    callingConvention = global::System.Runtime.InteropServices.CallingConvention.StdCall;
                    goto IL_00BB;
                }
                if (pinvokeAttributes2 == PInvokeAttributes.CallConvThiscall)
                {
                    callingConvention = global::System.Runtime.InteropServices.CallingConvention.ThisCall;
                    goto IL_00BB;
                }
                if (pinvokeAttributes2 == PInvokeAttributes.CallConvFastcall)
                {
                    callingConvention = global::System.Runtime.InteropServices.CallingConvention.FastCall;
                    goto IL_00BB;
                }
            }
            callingConvention = global::System.Runtime.InteropServices.CallingConvention.Cdecl;
            IL_00BB:
            bool flag = (pinvokeAttributes & PInvokeAttributes.NoMangle) > PInvokeAttributes.CharSetNotSpec;
            bool flag2 = (pinvokeAttributes & PInvokeAttributes.SupportsLastError) > PInvokeAttributes.CharSetNotSpec;
            bool flag3 = (pinvokeAttributes & PInvokeAttributes.BestFitMask) == PInvokeAttributes.BestFitEnabled;
            bool flag4 = (pinvokeAttributes & PInvokeAttributes.ThrowOnUnmappableCharMask) == PInvokeAttributes.ThrowOnUnmappableCharEnabled;
            bool flag5 = (this.GetMethodImplementationFlags() & MethodImplAttributes.PreserveSig) > MethodImplAttributes.IL;
            CustomAttributeTypedArgument[] array = new CustomAttributeTypedArgument[]
            {
                new CustomAttributeTypedArgument(typeof(string), text)
            };
            Type typeFromHandle = typeof(DllImportAttribute);
            CustomAttributeNamedArgument[] array2 = new CustomAttributeNamedArgument[]
            {
                new CustomAttributeNamedArgument(typeFromHandle.GetField("EntryPoint"), text2),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("CharSet"), charSet),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("ExactSpelling"), flag),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("SetLastError"), flag2),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("PreserveSig"), flag5),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("CallingConvention"), callingConvention),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("BestFitMapping"), flag3),
                new CustomAttributeNamedArgument(typeFromHandle.GetField("ThrowOnUnmappableChar"), flag4)
            };
            return new CustomAttributeData(typeFromHandle.GetConstructor(new Type[] { typeof(string) }), array, array2);
        }
References System.array, System.Reflection.RuntimeMethodInfo.Attributes, System.Type.GetConstructor(), System.Type.GetField(), System.Reflection.RuntimeMethodInfo.GetMethodImplementationFlags(), System.Reflection.RuntimeMethodInfo.GetPInvoke(), and System.text.
Referenced by System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributesData().