Terraria Decompiled: System.Reflection.RuntimeMethodInfo.GetParametersInternal
GetParametersInternal()
override ParameterInfo[] System.Reflection.RuntimeMethodInfo.GetParametersInternal () inline package virtual
Reimplemented from System.Reflection.MethodBase.
Definition at line 232 of file RuntimeMethodInfo.cs.
        {
            return MonoMethodInfo.GetParametersInfo(this.mhandle, this);
        }
References System.Reflection.MonoMethodInfo.GetParametersInfo(), and System.Reflection.RuntimeMethodInfo.mhandle.
Referenced by System.Runtime.Remoting.Messaging.MonoMethodMessage.InitMessage(), and System.Reflection.RuntimeMethodInfo.Invoke().