Terraria Decompiled: System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributesData
GetPseudoCustomAttributesData()
CustomAttributeData[] System.Reflection.RuntimeMethodInfo.GetPseudoCustomAttributesData () inline package
Definition at line 460 of file RuntimeMethodInfo.cs.
        {
            int num = 0;
            MonoMethodInfo methodInfo = MonoMethodInfo.GetMethodInfo(this.mhandle);
            if ((methodInfo.iattrs & MethodImplAttributes.PreserveSig) != MethodImplAttributes.IL)
            {
                num++;
            }
            if ((methodInfo.attrs & MethodAttributes.PinvokeImpl) != MethodAttributes.PrivateScope)
            {
                num++;
            }
            if (num == 0)
            {
                return null;
            }
            CustomAttributeData[] array = new CustomAttributeData[num];
            num = 0;
            if ((methodInfo.iattrs & MethodImplAttributes.PreserveSig) != MethodImplAttributes.IL)
            {
                array[num++] = new CustomAttributeData(typeof(PreserveSigAttribute).GetConstructor(Type.EmptyTypes));
            }
            if ((methodInfo.attrs & MethodAttributes.PinvokeImpl) != MethodAttributes.PrivateScope)
            {
                array[num++] = this.GetDllImportAttributeData();
            }
            return array;
        }
References System.array, System.Reflection.MonoMethodInfo.attrs, System.Type.EmptyTypes, System.Reflection.RuntimeMethodInfo.GetDllImportAttributeData(), System.Reflection.MonoMethodInfo.GetMethodInfo(), System.Reflection.MonoMethodInfo.iattrs, and System.Reflection.RuntimeMethodInfo.mhandle.
Referenced by System.MonoCustomAttrs.GetPseudoCustomAttributesData().