Terraria Decompiled: ReLogic.OS.Linux.PathService.MoveToRecycleBin
MoveToRecycleBin()
override void ReLogic.OS.Linux.PathService.MoveToRecycleBin (string path) inline
Definition at line 34 of file PathService.cs.
        {
            string text = Environment.GetEnvironmentVariable("XDG_DATA_HOME");
            if (string.IsNullOrEmpty(text))
            {
                text = Path.Combine(Environment.GetFolderPath(40), ".local", "share");
            }
            string text2 = Path.Combine(text, "Trash", "files");
            string text3 = Path.Combine(text, "Trash", "info");
            Directory.CreateDirectory(text2);
            Directory.CreateDirectory(text3);
            string fileName = Path.GetFileName(path);
            string text4 = Path.Combine(text2, fileName);
            int num = 1;
            while (File.Exists(text4))
            {
                text4 = Path.Combine(text2, string.Concat(new object[]
                {
                    Path.GetFileNameWithoutExtension(fileName),
                    "_",
                    num++,
                    Path.GetExtension(fileName)
                }));
            }
            string text5 = Path.Combine(text3, Path.GetFileName(text4) + ".trashinfo");
            string text6 = DateTime.UtcNow.ToString("yyyy-MM-ddTHH:mm:ss");
            File.WriteAllText(text5, string.Concat(new string[] { "[Trash Info]\nPath=", path, "\nDeletionDate=", text6, "\n" }));
            File.Move(path, text4);
        }
References System.IO.Path.Combine(), System.IO.Directory.CreateDirectory(), System.IO.File.Exists(), System.IO.Path.GetExtension(), System.IO.Path.GetFileName(), System.IO.Path.GetFileNameWithoutExtension(), System.IO.File.Move(), System.text, System.DateTime.ToString(), System.DateTime.UtcNow, and System.IO.File.WriteAllText().