Terraria Decompiled: System.Reflection.RuntimeMethodInfo.Invoke
Invoke()
override object System.Reflection.RuntimeMethodInfo.Invoke (object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture) inline
Implements System.Runtime.InteropServices._MethodInfo.
Definition at line 250 of file RuntimeMethodInfo.cs.
        {
            if (!base.IsStatic && !this.DeclaringType.IsInstanceOfType(obj))
            {
                if (obj == null)
                {
                    throw new TargetException("Non-static method requires a target.");
                }
                throw new TargetException("Object does not match target type.");
            }
            else
            {
                if (binder == null)
                {
                    binder = Type.DefaultBinder;
                }
                ParameterInfo[] parametersInternal = this.GetParametersInternal();
                RuntimeMethodInfo.ConvertValues(binder, parameters, parametersInternal, culture, invokeAttr);
                if (this.ContainsGenericParameters)
                {
                    throw new InvalidOperationException("Late bound operations cannot be performed on types or methods for which ContainsGenericParameters is true.");
                }
                object obj2 = null;
                Exception ex;
                if ((invokeAttr & BindingFlags.DoNotWrapExceptions) == BindingFlags.Default)
                {
                    try
                    {
                        obj2 = this.InternalInvoke(obj, parameters, out ex);
                        goto IL_0090;
                    }
                    catch (ThreadAbortException)
                    {
                        throw;
                    }
                    catch (OverflowException)
                    {
                        throw;
                    }
                    catch (Exception ex2)
                    {
                        throw new TargetInvocationException(ex2);
                    }
                }
                obj2 = this.InternalInvoke(obj, parameters, out ex);
                IL_0090:
                if (ex != null)
                {
                    throw ex;
                }
                return obj2;
            }
        }
References System.Reflection.RuntimeMethodInfo.ContainsGenericParameters, System.Reflection.RuntimeMethodInfo.ConvertValues(), System.culture, System.Type.DefaultBinder, System.Reflection.RuntimeMethodInfo.GetParametersInternal(), System.Reflection.RuntimeMethodInfo.InternalInvoke(), and System.obj.
Referenced by System.Reflection.Emit.DynamicMethod.Invoke().