Terraria Decompiled: System.Reflection.RuntimeMethodInfo.FormatNameAndSig
FormatNameAndSig()
override string System.Reflection.RuntimeMethodInfo.FormatNameAndSig (bool serialization) inline package virtual
Reimplemented from System.Reflection.MethodBase.
Definition at line 50 of file RuntimeMethodInfo.cs.
        {
            StringBuilder stringBuilder = new StringBuilder(this.Name);
            TypeNameFormatFlags typeNameFormatFlags = (serialization ? TypeNameFormatFlags.FormatSerialization : TypeNameFormatFlags.FormatBasic);
            if (this.IsGenericMethod)
            {
                stringBuilder.Append(RuntimeMethodHandle.ConstructInstantiation(this, typeNameFormatFlags));
            }
            stringBuilder.Append("(");
            RuntimeParameterInfo.FormatParameters(stringBuilder, this.GetParametersNoCopy(), this.CallingConvention, serialization);
            stringBuilder.Append(")");
            return stringBuilder.ToString();
        }
References System.Text.StringBuilder.Append(), System.Reflection.RuntimeMethodInfo.CallingConvention, System.RuntimeMethodHandle.ConstructInstantiation(), System.Reflection.RuntimeParameterInfo.FormatParameters(), System.Reflection.MethodBase.GetParametersNoCopy(), System.Reflection.RuntimeMethodInfo.IsGenericMethod, System.Reflection.RuntimeMethodInfo.Name, and System.Text.StringBuilder.ToString().
Referenced by System.Reflection.RuntimeMethodInfo.SerializationToString(), and System.Reflection.RuntimeMethodInfo.ToString().