Terraria Decompiled: ReLogic.Content.Sources.ZipContentSource.GetExtension
GetExtension()
string ReLogic.Content.Sources.ZipContentSource.GetExtension (string assetName) inline
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 87 of file ZipContentSource.cs.
        {
            ZipEntry zipEntry;
            if (!this._entries.TryGetValue(assetName, ref zipEntry))
            {
                throw AssetLoadException.FromMissingAsset(assetName, null);
            }
            return Path.GetExtension(zipEntry.FileName) ?? "";
        }
References ReLogic.Content.Sources.ZipContentSource._entries, Ionic.Zip.ZipEntry.FileName, ReLogic.Content.AssetLoadException.FromMissingAsset(), System.IO.Path.GetExtension(), and System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue().