Terraria Decompiled: ReLogic.Content.Sources.ZipContentSource.Refresh
Refresh()
void ReLogic.Content.Sources.ZipContentSource.Refresh () inline
Implements ReLogic.Content.Sources.IContentSource.
Definition at line 112 of file ZipContentSource.cs.
        {
            this._entries.Clear();
            foreach (ZipEntry zipEntry in Enumerable.Where<ZipEntry>(this._zipFile.Entries, (ZipEntry entry) => !entry.IsDirectory && entry.FileName.StartsWith(this._basePath)))
            {
                string fileName = zipEntry.FileName;
                string text = Path.GetExtension(fileName) ?? "";
                string text2 = fileName.Substring(this._basePath.Length, fileName.Length - text.Length - this._basePath.Length);
                text2 = AssetPathHelper.CleanPath(text2);
                this._entries[text2] = zipEntry;
            }
        }
References ReLogic.Content.Sources.ZipContentSource._basePath, ReLogic.Content.Sources.ZipContentSource._entries, ReLogic.Content.AssetPathHelper.CleanPath(), System.Collections.Generic.Dictionary< TKey, TValue >.Clear(), Ionic.Zip.ZipEntry.FileName, System.IO.Path.GetExtension(), Ionic.Zip.ZipEntry.IsDirectory, and System.text.
Referenced by ReLogic.Content.Sources.ZipContentSource.ZipContentSource().