var ContentSerializerCollectionItemNameAttribute_8cs =
[
    [ "Microsoft.Xna.Framework.Content.ContentSerializerCollectionItemNameAttribute", "d3/d0e/classMicrosoft_1_1Xna_1_1Framework_1_1Content_1_1ContentSerializerCollectionItemNameAttribute.html", "d3/d0e/classMicrosoft_1_1Xna_1_1Framework_1_1Content_1_1ContentSerializerCollectionItemNameAttribute" ]
];