Terraria Decompiled: System.Collections.Concurrent.ConcurrentStack.TryPopCore
TryPopCore() [1/2]
int System.Collections.Concurrent.ConcurrentStack< T >.TryPopCore (int count, out ConcurrentStack< T >::Node poppedHead) inline private
Definition at line 278 of file ConcurrentStack.cs.
        {
            SpinWait spinWait = default(SpinWait);
            int num = 1;
            Random random = null;
            ConcurrentStack<T>.Node head;
            int num2;
            for (;;)
            {
                head = this._head;
                if (head == null)
                {
                    break;
                }
                ConcurrentStack<T>.Node node = head;
                num2 = 1;
                while (num2 < count && node._next != null)
                {
                    node = node._next;
                    num2++;
                }
                if (Interlocked.CompareExchange<ConcurrentStack<T>.Node>(ref this._head, node._next, head) == head)
                {
                    goto Block_5;
                }
                for (int i = 0; i < num; i++)
                {
                    spinWait.SpinOnce();
                }
                if (spinWait.NextSpinWillYield)
                {
                    if (random == null)
                    {
                        random = new Random();
                    }
                    num = random.Next(1, 8);
                }
                else
                {
                    num *= 2;
                }
            }
            if (count == 1 && CDSCollectionETWBCLProvider.Log.IsEnabled())
            {
                CDSCollectionETWBCLProvider.Log.ConcurrentStack_FastPopFailed(spinWait.Count);
            }
            poppedHead = null;
            return 0;
            Block_5:
            if (count == 1 && CDSCollectionETWBCLProvider.Log.IsEnabled())
            {
                CDSCollectionETWBCLProvider.Log.ConcurrentStack_FastPopFailed(spinWait.Count);
            }
            poppedHead = head;
            return num2;
        }
References System.Collections.Concurrent.ConcurrentStack< T >._head, System.Threading.Interlocked.CompareExchange(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentStack_FastPopFailed(), System.count, System.Threading.SpinWait.Count, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.Log, System.Random.Next(), System.Threading.SpinWait.NextSpinWillYield, and System.Threading.SpinWait.SpinOnce().