Terraria Decompiled: System.Collections.Concurrent.ConcurrentStack.PushCore
PushCore()
void System.Collections.Concurrent.ConcurrentStack< T >.PushCore (ConcurrentStack< T >::Node head, ConcurrentStack< T >::Node tail) inline private
Definition at line 163 of file ConcurrentStack.cs.
        {
            SpinWait spinWait = default(SpinWait);
            do
            {
                spinWait.SpinOnce();
                tail._next = this._head;
            }
            while (Interlocked.CompareExchange<ConcurrentStack<T>.Node>(ref this._head, head, tail._next) != tail._next);
            if (CDSCollectionETWBCLProvider.Log.IsEnabled())
            {
                CDSCollectionETWBCLProvider.Log.ConcurrentStack_FastPushFailed(spinWait.Count);
            }
        }
References System.Collections.Concurrent.ConcurrentStack< T >._head, System.Threading.Interlocked.CompareExchange(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.ConcurrentStack_FastPushFailed(), System.Threading.SpinWait.Count, System.Diagnostics.Tracing.EventSource.IsEnabled(), System.Collections.Concurrent.CDSCollectionETWBCLProvider.Log, and System.Threading.SpinWait.SpinOnce().
Referenced by System.Collections.Concurrent.ConcurrentStack< T >.Push(), and System.Collections.Concurrent.ConcurrentStack< T >.PushRange().