Terraria Decompiled: CsvHelper.TypeConversion.TypeConverterOptions.Merge
Merge()
static TypeConverterOptions CsvHelper.TypeConversion.TypeConverterOptions.Merge (params TypeConverterOptions[] sources) inline static
Definition at line 118 of file TypeConverterOptions.cs.
        {
            TypeConverterOptions typeConverterOptions = new TypeConverterOptions();
            foreach (TypeConverterOptions typeConverterOptions2 in sources)
            {
                if (typeConverterOptions2 != null)
                {
                    if (typeConverterOptions2.CultureInfo != null)
                    {
                        typeConverterOptions.CultureInfo = typeConverterOptions2.CultureInfo;
                    }
                    if (typeConverterOptions2.DateTimeStyle != null)
                    {
                        typeConverterOptions.DateTimeStyle = typeConverterOptions2.DateTimeStyle;
                    }
                    if (typeConverterOptions2.TimeSpanStyle != null)
                    {
                        typeConverterOptions.TimeSpanStyle = typeConverterOptions2.TimeSpanStyle;
                    }
                    if (typeConverterOptions2.NumberStyle != null)
                    {
                        typeConverterOptions.NumberStyle = typeConverterOptions2.NumberStyle;
                    }
                    if (typeConverterOptions2.Format != null)
                    {
                        typeConverterOptions.Format = typeConverterOptions2.Format;
                    }
                    if (!Enumerable.SequenceEqual<string>(typeConverterOptions.booleanTrueValues, typeConverterOptions2.booleanTrueValues))
                    {
                        typeConverterOptions.booleanTrueValues.Clear();
                        typeConverterOptions.booleanTrueValues.AddRange(typeConverterOptions2.booleanTrueValues);
                    }
                    if (!Enumerable.SequenceEqual<string>(typeConverterOptions.booleanFalseValues, typeConverterOptions2.booleanFalseValues))
                    {
                        typeConverterOptions.booleanFalseValues.Clear();
                        typeConverterOptions.booleanFalseValues.AddRange(typeConverterOptions2.booleanFalseValues);
                    }
                }
            }
            return typeConverterOptions;
        }
References CsvHelper.TypeConversion.TypeConverterOptions.booleanFalseValues, CsvHelper.TypeConversion.TypeConverterOptions.booleanTrueValues, CsvHelper.TypeConversion.TypeConverterOptions.CultureInfo, CsvHelper.TypeConversion.TypeConverterOptions.DateTimeStyle, CsvHelper.TypeConversion.TypeConverterOptions.Format, CsvHelper.TypeConversion.TypeConverterOptions.NumberStyle, CsvHelper.TypeConversion.TypeConverterOptions.TimeSpanStyle, and CsvHelper.TypeConversion.TypeConverterOptions.TypeConverterOptions().
Referenced by CsvHelper.CsvReader.AddPropertyBindings(), and CsvHelper.CsvWriter.CreateActionForObject().