Terraria Decompiled: Microsoft.Xna.Framework.BoundingSphere.Transform
Transform() [2/2]
void Microsoft.Xna.Framework.BoundingSphere.Transform (ref Matrix matrix, out BoundingSphere result) inline
Definition at line 51 of file BoundingSphere.cs.
        {
            result.Center = Vector3.Transform(this.Center, matrix);
            result.Radius = this.Radius * (float)Math.Sqrt((double)Math.Max(matrix.M11 * matrix.M11 + matrix.M12 * matrix.M12 + matrix.M13 * matrix.M13, Math.Max(matrix.M21 * matrix.M21 + matrix.M22 * matrix.M22 + matrix.M23 * matrix.M23, matrix.M31 * matrix.M31 + matrix.M32 * matrix.M32 + matrix.M33 * matrix.M33)));
        }
References Microsoft.Xna.Framework.BoundingSphere.Center, System.Math.Max(), System.Math.Sqrt(), and Microsoft.Xna.Framework.Vector3.Transform().