Terraria Decompiled: Microsoft.Xna.Framework.BoundingSphere.CreateFromPoints
CreateFromPoints()
static BoundingSphere Microsoft.Xna.Framework.BoundingSphere.CreateFromPoints (IEnumerable< Vector3 > points) inline static
Definition at line 208 of file BoundingSphere.cs.
        {
            if (points == null)
            {
                throw new ArgumentNullException("points");
            }
            Vector3 vector = new Vector3(float.MaxValue, float.MaxValue, float.MaxValue);
            Vector3 vector2 = -vector;
            Vector3 vector3 = vector;
            Vector3 vector4 = -vector;
            Vector3 vector5 = vector;
            Vector3 vector6 = -vector;
            int num = 0;
            foreach (Vector3 vector7 in points)
            {
                num++;
                if (vector7.X < vector.X)
                {
                    vector = vector7;
                }
                if (vector7.X > vector2.X)
                {
                    vector2 = vector7;
                }
                if (vector7.Y < vector3.Y)
                {
                    vector3 = vector7;
                }
                if (vector7.Y > vector4.Y)
                {
                    vector4 = vector7;
                }
                if (vector7.Z < vector5.Z)
                {
                    vector5 = vector7;
                }
                if (vector7.Z > vector6.Z)
                {
                    vector6 = vector7;
                }
            }
            if (num == 0)
            {
                throw new ArgumentException("You should have at least one point in points.");
            }
            float num2 = Vector3.DistanceSquared(vector2, vector);
            float num3 = Vector3.DistanceSquared(vector4, vector3);
            float num4 = Vector3.DistanceSquared(vector6, vector5);
            Vector3 vector8 = vector;
            Vector3 vector9 = vector2;
            if (num3 > num2 && num3 > num4)
            {
                vector9 = vector4;
                vector8 = vector3;
            }
            if (num4 > num2 && num4 > num3)
            {
                vector9 = vector6;
                vector8 = vector5;
            }
            Vector3 vector10 = (vector8 + vector9) * 0.5f;
            float num5 = Vector3.Distance(vector9, vector10);
            float num6 = num5 * num5;
            foreach (Vector3 vector11 in points)
            {
                Vector3 vector12 = vector11 - vector10;
                float num7 = vector12.LengthSquared();
                if (num7 > num6)
                {
                    float num8 = (float)Math.Sqrt((double)num7);
                    Vector3 vector13 = vector12 / num8;
                    vector10 = (vector10 - num5 * vector13 + vector11) / 2f;
                    num5 = Vector3.Distance(vector11, vector10);
                    num6 = num5 * num5;
                }
            }
            return new BoundingSphere(vector10, num5);
        }
References Microsoft.Xna.Framework.BoundingSphere.BoundingSphere(), Microsoft.Xna.Framework.Vector3.Distance(), Microsoft.Xna.Framework.Vector3.DistanceSquared(), Microsoft.Xna.Framework.Vector3.LengthSquared(), System.Math.Sqrt(), Microsoft.Xna.Framework.Vector3.X, Microsoft.Xna.Framework.Vector3.Y, and Microsoft.Xna.Framework.Vector3.Z.
Referenced by Microsoft.Xna.Framework.BoundingSphere.CreateFromFrustum().