Terraria Decompiled: rail.IRailVoiceHelperImpl.GetVoiceCaptureSpecification
GetVoiceCaptureSpecification()
virtual RailResult rail.IRailVoiceHelperImpl.GetVoiceCaptureSpecification (RailVoiceCaptureSpecification spec) inline virtual
Implements rail.IRailVoiceHelper.
Definition at line 156 of file IRailVoiceHelperImpl.cs.
        {
            IntPtr intPtr = ((spec == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailVoiceCaptureSpecification__SWIG_0());
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailVoiceHelper_GetVoiceCaptureSpecification(this.swigCPtr_, intPtr);
            }
            finally
            {
                if (spec != null)
                {
                    RailConverter.Cpp2Csharp(intPtr, spec);
                }
                RAIL_API_PINVOKE.delete_RailVoiceCaptureSpecification(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Cpp2Csharp(), rail.RAIL_API_PINVOKE.delete_RailVoiceCaptureSpecification(), rail.RAIL_API_PINVOKE.IRailVoiceHelper_GetVoiceCaptureSpecification(), rail.RAIL_API_PINVOKE.new_RailVoiceCaptureSpecification__SWIG_0(), and System.IntPtr.Zero.