Terraria Decompiled: Terraria.GameContent.UI.CustomCurrencyManager.BuyItem
BuyItem()
static bool Terraria.GameContent.UI.CustomCurrencyManager.BuyItem (Player player, long price, int currencyIndex) inline static
Definition at line 81 of file CustomCurrencyManager.cs.
        {
            CustomCurrencySystem customCurrencySystem = CustomCurrencyManager._currencies[currencyIndex];
            bool flag;
            long num = customCurrencySystem.CountCurrency(out flag, player.inventory, new int[] { 58, 57, 56, 55, 54 });
            long num2 = customCurrencySystem.CountCurrency(out flag, player.bank.item, new int[0]);
            long num3 = customCurrencySystem.CountCurrency(out flag, player.bank2.item, new int[0]);
            long num4 = customCurrencySystem.CountCurrency(out flag, player.bank3.item, new int[0]);
            long num5 = customCurrencySystem.CountCurrency(out flag, player.bank4.item, new int[0]);
            if (customCurrencySystem.CombineStacks(out flag, new long[] { num, num2, num3, num4, num5 }) < price)
            {
                return false;
            }
            List<Item[]> list = new List<Item[]>();
            Dictionary<int, List<int>> dictionary = new Dictionary<int, List<int>>();
            List<Point> list2 = new List<Point>();
            List<Point> list3 = new List<Point>();
            List<Point> list4 = new List<Point>();
            List<Point> list5 = new List<Point>();
            List<Point> list6 = new List<Point>();
            List<Point> list7 = new List<Point>();
            list.Add(player.inventory);
            list.Add(player.bank.item);
            list.Add(player.bank2.item);
            list.Add(player.bank3.item);
            list.Add(player.bank4.item);
            for (int i = 0; i < list.Count; i++)
            {
                dictionary[i] = new List<int>();
            }
            dictionary[0] = new List<int> { 58, 57, 56, 55, 54 };
            for (int j = 0; j < list.Count; j++)
            {
                for (int k = 0; k < list[j].Length; k++)
                {
                    if (!dictionary[j].Contains(k) && customCurrencySystem.Accepts(list[j][k]))
                    {
                        list3.Add(new Point(j, k));
                    }
                }
            }
            CustomCurrencyManager.FindEmptySlots(list, dictionary, list2, 0);
            CustomCurrencyManager.FindEmptySlots(list, dictionary, list4, 1);
            CustomCurrencyManager.FindEmptySlots(list, dictionary, list5, 2);
            CustomCurrencyManager.FindEmptySlots(list, dictionary, list6, 3);
            CustomCurrencyManager.FindEmptySlots(list, dictionary, list7, 4);
            return customCurrencySystem.TryPurchasing(price, list, list3, list2, list4, list5, list6, list7);
        }
References Terraria.GameContent.UI.CustomCurrencyManager._currencies, Terraria.GameContent.UI.CustomCurrencySystem.Accepts(), System.Collections.Generic.List< T >.Add(), Terraria.Player.bank, Terraria.Player.bank2, Terraria.Player.bank3, Terraria.Player.bank4, Terraria.GameContent.UI.CustomCurrencySystem.CombineStacks(), Microsoft.Xna.Framework.Contains, Terraria.GameContent.UI.CustomCurrencySystem.CountCurrency(), System.dictionary, Terraria.GameContent.UI.CustomCurrencyManager.FindEmptySlots(), Terraria.Player.inventory, Terraria.Chest.item, System.list, Microsoft.Xna.Framework.Graphics.Point, and Terraria.GameContent.UI.CustomCurrencySystem.TryPurchasing().
Referenced by Terraria.Player.BuyItem().