Terraria Decompiled: System.Collections.Generic.GenericArraySortHelper.PickPivotAndPartition
PickPivotAndPartition() [2/2]
static int System.Collections.Generic.GenericArraySortHelper< T >.PickPivotAndPartition (TKey[] keys, TValue[] values, int lo, int hi) inline static private
Definition at line 118 of file GenericArraySortHelper.2.cs.
        {
            int num = lo + (hi - lo) / 2;
            GenericArraySortHelper<TKey, TValue>.SwapIfGreaterWithItems(keys, values, lo, num);
            GenericArraySortHelper<TKey, TValue>.SwapIfGreaterWithItems(keys, values, lo, hi);
            GenericArraySortHelper<TKey, TValue>.SwapIfGreaterWithItems(keys, values, num, hi);
            TKey tkey = keys[num];
            GenericArraySortHelper<TKey, TValue>.Swap(keys, values, num, hi - 1);
            int i = lo;
            int j = hi - 1;
            while (i < j)
            {
                if (tkey == null)
                {
                    while (i < hi - 1 && keys[++i] == null)
                    {
                    }
                    while (j > lo)
                    {
                        if (keys[--j] == null)
{
                            break;
                        }
                    }
                }
                else
                {
                    while (tkey.CompareTo(keys[++i]) > 0)
                    {
                    }
                    while (tkey.CompareTo(keys[--j]) < 0)
                    {
                    }
                }
                if (i >= j)
                {
                    break;
                }
                GenericArraySortHelper<TKey, TValue>.Swap(keys, values, i, j);
            }
            GenericArraySortHelper<TKey, TValue>.Swap(keys, values, i, hi - 1);
            return i;
        }
References System.Collections.Generic.GenericArraySortHelper< T >.Swap(), System.Collections.Generic.GenericArraySortHelper< T >.SwapIfGreaterWithItems(), and System.values.
Referenced by System.Collections.Generic.GenericArraySortHelper< T >.IntroSort(), and System.Collections.Generic.GenericArraySortHelper< T >.IntroSort().