Terraria Decompiled: System.Collections.Generic.GenericArraySortHelper.Sort
Sort() [2/2]
void System.Collections.Generic.GenericArraySortHelper< T >.Sort (TKey[] keys, TValue[] values, int index, int length, IComparer< TKey > comparer) inline
Definition at line 10 of file GenericArraySortHelper.2.cs.
        {
            try
            {
                if (comparer == null || comparer == Comparer<TKey>.Default)
                {
                    GenericArraySortHelper<TKey, TValue>.IntrospectiveSort(keys, values, index, length);
                }
                else
                {
                    ArraySortHelper<TKey, TValue>.IntrospectiveSort(keys, values, index, length, comparer);
                }
            }
            catch (IndexOutOfRangeException)
            {
                IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(comparer);
            }
            catch (ThreadAbortException)
            {
                throw;
            }
            catch (Exception ex)
            {
                throw new InvalidOperationException("Failed to compare two elements in the array.", ex);
            }
        }
References System.comparer, System.Default, System.index, System.Collections.Generic.GenericArraySortHelper< T >.IntrospectiveSort(), System.Collections.Generic.ArraySortHelper< T >.IntrospectiveSort(), System.length, System.Collections.Generic.IntrospectiveSortUtilities.ThrowOrIgnoreBadComparer(), and System.values.