Terraria Decompiled: rail.IRailGameServerHelperImpl.AsyncRemoveFavoriteGameServer
AsyncRemoveFavoriteGameServer() [1/2]
virtual RailResult rail.IRailGameServerHelperImpl.AsyncRemoveFavoriteGameServer (RailID game_server_id) inline virtual
Implements rail.IRailGameServerHelper.
Definition at line 213 of file IRailGameServerHelperImpl.cs.
        {
            IntPtr intPtr = ((game_server_id == null) ? IntPtr.Zero : RAIL_API_PINVOKE.new_RailID__SWIG_0());
            if (game_server_id != null)
            {
                RailConverter.Csharp2Cpp(game_server_id, intPtr);
            }
            RailResult railResult;
            try
            {
                railResult = (RailResult)RAIL_API_PINVOKE.IRailGameServerHelper_AsyncRemoveFavoriteGameServer__SWIG_1(this.swigCPtr_, intPtr);
            }
            finally
            {
                RAIL_API_PINVOKE.delete_RailID(intPtr);
            }
            return railResult;
        }
References rail.RailConverter.Csharp2Cpp(), rail.RAIL_API_PINVOKE.delete_RailID(), rail.RAIL_API_PINVOKE.IRailGameServerHelper_AsyncRemoveFavoriteGameServer__SWIG_1(), rail.RAIL_API_PINVOKE.new_RailID__SWIG_0(), and System.IntPtr.Zero.