Terraria Decompiled: FullSerializer.Internal.fsTypeCache.fsTypeCache
fsTypeCache()
static FullSerializer.Internal.fsTypeCache.fsTypeCache () inline static private
Definition at line 11 of file fsTypeCache.cs.
        {
            foreach (Assembly assembly in AppDomain.CurrentDomain.GetAssemblies())
            {
                fsTypeCache._assembliesByName[assembly.FullName] = assembly;
                fsTypeCache._assembliesByIndex.Add(assembly);
            }
            fsTypeCache._cachedTypes = new Dictionary<string, Type>();
            AppDomain.CurrentDomain.AssemblyLoad += new AssemblyLoadEventHandler(fsTypeCache.OnAssemblyLoaded);
        }
References FullSerializer.Internal.fsTypeCache._assembliesByIndex, FullSerializer.Internal.fsTypeCache._assembliesByName, System.Collections.Generic.List< T >.Add(), System.AssemblyLoadEventHandler(), System.AppDomain.CurrentDomain, System.Reflection.Assembly.FullName, System.AppDomain.GetAssemblies(), and FullSerializer.Internal.fsTypeCache.OnAssemblyLoaded().