Terraria Decompiled: FullSerializer.Internal.fsTypeCache.GetType
GetType() [2/2]
static Type FullSerializer.Internal.fsTypeCache.GetType (string name, string assemblyHint) inline static
Definition at line 80 of file fsTypeCache.cs.
        {
            if (string.IsNullOrEmpty(name))
            {
                return null;
            }
            Type type;
            if (!fsTypeCache._cachedTypes.TryGetValue(name, ref type))
            {
                if (!fsTypeCache.TryDirectTypeLookup(assemblyHint, name, out type))
                {
                    fsTypeCache.TryIndirectTypeLookup(name, out type);
                }
                fsTypeCache._cachedTypes[name] = type;
            }
            return type;
        }
References FullSerializer.Internal.fsTypeCache._cachedTypes, System.name, FullSerializer.Internal.fsTypeCache.TryDirectTypeLookup(), System.Collections.Generic.Dictionary< TKey, TValue >.TryGetValue(), and FullSerializer.Internal.fsTypeCache.TryIndirectTypeLookup().