Terraria Decompiled: Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.EdgePlacement
EdgePlacement()
void Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.EdgePlacement (Vector2 mouse) inline private
Definition at line 912 of file CaptureInterface.cs.
            {
                if (CaptureInterface.JustActivated)
                {
                    return;
                }
                Point point;
                if (!Main.mapFullscreen)
                {
                    if (Main.mouseLeft)
                    {
                        CaptureInterface.EdgeAPinned = true;
                        CaptureInterface.EdgeA = Main.MouseWorld.ToTileCoordinates();
                    }
                    if (Main.mouseRight)
                    {
                        CaptureInterface.EdgeBPinned = true;
                        CaptureInterface.EdgeB = Main.MouseWorld.ToTileCoordinates();
                    }
                }
                else if (CaptureInterface.GetMapCoords((int)mouse.X, (int)mouse.Y, 0, out point))
                {
                    if (Main.mouseLeft)
                    {
                        CaptureInterface.EdgeAPinned = true;
                        CaptureInterface.EdgeA = point;
                    }
                    if (Main.mouseRight)
                    {
                        CaptureInterface.EdgeBPinned = true;
                        CaptureInterface.EdgeB = point;
                    }
                }
                CaptureInterface.ConstraintPoints();
            }
References Terraria.Graphics.Capture.CaptureInterface.ConstraintPoints(), Terraria.Graphics.Capture.CaptureInterface.GetMapCoords(), Terraria.Graphics.Capture.CaptureInterface.JustActivated, Terraria.Main.mapFullscreen, Terraria.Main.mouseLeft, Terraria.Main.mouseRight, Terraria.Main.MouseWorld, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.Graphics.Capture.CaptureInterface.ModeEdgeSelection.Update().