Terraria Decompiled: Terraria.GameContent.Skies.MartianSky.Draw
Draw()
override void Terraria.GameContent.Skies.MartianSky.Draw (SpriteBatch spriteBatch, float minDepth, float maxDepth) inline
Definition at line 53 of file MartianSky.cs.
        {
            if (Main.screenPosition.Y > 10000f)
            {
                return;
            }
            int num = -1;
            int num2 = 0;
            for (int i = 0; i < this._ufos.Length; i++)
            {
                float depth = this._ufos[i].Depth;
                if (num == -1 && depth < maxDepth)
                {
                    num = i;
                }
                if (depth <= minDepth)
                {
                    break;
                }
                num2 = i;
            }
            if (num == -1)
            {
                return;
            }
            Color color = new Color(Main.ColorOfTheSkies.ToVector4() * 0.9f + new Vector4(0.1f));
            Vector2 vector = Main.screenPosition + new Vector2((float)(Main.screenWidth >> 1), (float)(Main.screenHeight >> 1));
            Rectangle rectangle = new Rectangle(-1000, -1000, Main.screenWidth + 1000, Main.screenHeight + 1000);
            for (int j = num; j < num2; j++)
            {
                Vector2 vector2 = new Vector2(1f / this._ufos[j].Depth, 0.9f / this._ufos[j].Depth);
                Vector2 vector3 = this._ufos[j].Position;
                vector3 = (vector3 - vector) * vector2 + vector - Main.screenPosition;
                if (this._ufos[j].IsActive && rectangle.Contains((int)vector3.X, (int)vector3.Y))
                {
                    spriteBatch.Draw(this._ufos[j].Texture, vector3, new Rectangle?(this._ufos[j].GetSourceRectangle()), color * this._ufos[j].Opacity, this._ufos[j].Rotation, Vector2.Zero, vector2.X * 5f * this._ufos[j].Scale, SpriteEffects.None, 0f);
                    if (this._ufos[j].GlowTexture != null)
                    {
                        spriteBatch.Draw(this._ufos[j].GlowTexture, vector3, new Rectangle?(this._ufos[j].GetSourceRectangle()), Color.White * this._ufos[j].Opacity, this._ufos[j].Rotation, Vector2.Zero, vector2.X * 5f * this._ufos[j].Scale, SpriteEffects.None, 0f);
                    }
                }
            }
        }
References Terraria.GameContent.Skies.MartianSky._ufos, Microsoft.Xna.Framework.Graphics.Color, Terraria.Main.ColorOfTheSkies, Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Graphics.Depth, Microsoft.Xna.Framework.Graphics.SpriteBatch.Draw(), Terraria.GameContent.Skies.MartianSky.IsActive(), Terraria.Graphics.Effects.GameEffect.Opacity, Terraria.Main.screenHeight, Terraria.Main.screenPosition, Terraria.Main.screenWidth, Microsoft.Xna.Framework.Graphics.Vector2, Microsoft.Xna.Framework.Color.White, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector2.Y, and Microsoft.Xna.Framework.Vector2.Zero.