Terraria Decompiled: System.TimeSpan.ValidateStyles
ValidateStyles()
static void System.TimeSpan.ValidateStyles (TimeSpanStyles style, string parameterName) inline static private
Definition at line 357 of file TimeSpan.cs.
        {
            if (style != TimeSpanStyles.None && style != TimeSpanStyles.AssumeNegative)
            {
                throw new ArgumentException("An undefined TimeSpanStyles value is being used.", parameterName);
            }
        }
Referenced by System.TimeSpan.ParseExact(), System.TimeSpan.ParseExact(), System.TimeSpan.ParseExact(), System.TimeSpan.ParseExact(), System.TimeSpan.TryParseExact(), System.TimeSpan.TryParseExact(), System.TimeSpan.TryParseExact(), and System.TimeSpan.TryParseExact().