Terraria Decompiled: System.TimeSpan.Negate
Negate()
TimeSpan System.TimeSpan.Negate () inline
Definition at line 295 of file TimeSpan.cs.
        {
            if (this.Ticks == TimeSpan.MinValue.Ticks)
            {
                throw new OverflowException("Negating the minimum value of a twos complement number is invalid.");
            }
            return new TimeSpan(-this._ticks);
        }
References System.TimeSpan._ticks, System.TimeSpan.MinValue, System.TimeSpan.Ticks, and System.TimeSpan.TimeSpan().
Referenced by System.TimeZoneInfo.ConvertToFromUtc(), System.Runtime.Remoting.Metadata.W3cXsd2001.SoapDuration.ToString(), Newtonsoft.Json.Utilities.DateTimeUtils.TryReadOffset(), System.TimeZoneInfo.TZif_CreateAdjustmentRuleForPosixFormat(), and System.TimeZoneInfo.TZif_ParseOffsetString().