Terraria Decompiled: System.TimeSpan.Interval
Interval()
static TimeSpan System.TimeSpan.Interval (double value, int scale) inline static private
Definition at line 268 of file TimeSpan.cs.
        {
            if (double.IsNaN(value))
            {
                throw new ArgumentException("TimeSpan does not accept floating point Not-a-Number values.");
            }
            double num = value * (double)scale + ((value >= 0.0) ? 0.5 : (-0.5));
            if (num > 922337203685477.0 || num < -922337203685477.0)
            {
                throw new OverflowException("TimeSpan overflowed because the duration is too long.");
            }
            return new TimeSpan((long)num * 10000L);
        }
References System.L, System.TimeSpan.TimeSpan(), and System.value.
Referenced by System.TimeSpan.FromDays(), System.TimeSpan.FromHours(), System.TimeSpan.FromMilliseconds(), System.TimeSpan.FromMinutes(), and System.TimeSpan.FromSeconds().