Terraria Decompiled: System.IO.StreamReader.d__69.MoveNext
MoveNext()
void IAsyncStateMachine. System.IO.StreamReader.d__69.MoveNext () inline
Implements System.Runtime.CompilerServices.IAsyncStateMachine.
Definition at line 1800 of file StreamReader.cs.
            {
                int num2;
                int num = num2;
                StreamReader streamReader = this;
                int num3;
                try
                {
                    ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter2;
                    ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter configuredValueTaskAwaiter;
                    if (num == 0)
                    {
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        goto IL_00EC;
                    }
                    if (num == 1)
                    {
                        configuredValueTaskAwaiter = configuredValueTaskAwaiter2;
                        configuredValueTaskAwaiter2 = default(ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter);
                        num2 = -1;
                        goto IL_01E0;
                    }
                    streamReader._charLen = 0;
                    streamReader._charPos = 0;
                    tmpByteBuffer = streamReader._byteBuffer;
                    tmpStream = streamReader._stream;
                    if (!streamReader._checkPreamble)
                    {
                        streamReader._byteLen = 0;
                    }
                    IL_0050:
                    if (streamReader._checkPreamble)
                    {
                        int bytePos = streamReader._bytePos;
                        configuredValueTaskAwaiter = tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer, bytePos, tmpByteBuffer.Length - bytePos), default(CancellationToken)).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num2 = 0;
                            configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, StreamReader.<ReadBufferAsync>d__69>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                    }
                    else
                    {
                        configuredValueTaskAwaiter = tmpStream.ReadAsync(new Memory<byte>(tmpByteBuffer), default(CancellationToken)).ConfigureAwait(false).GetAwaiter();
                        if (!configuredValueTaskAwaiter.IsCompleted)
{
                            num2 = 1;
                            configuredValueTaskAwaiter2 = configuredValueTaskAwaiter;
                            this.<>t__builder.AwaitUnsafeOnCompleted<ConfiguredValueTaskAwaitable<int>.ConfiguredValueTaskAwaiter, StreamReader.<ReadBufferAsync>d__69>(ref configuredValueTaskAwaiter, ref this);
                            return;
                        }
                        goto IL_01E0;
                    }
                    IL_00EC:
                    int result = configuredValueTaskAwaiter.GetResult();
                    if (result == 0)
                    {
                        if (streamReader._byteLen > 0)
{
                            streamReader._charLen += streamReader._decoder.GetChars(tmpByteBuffer, 0, streamReader._byteLen, streamReader._charBuffer, streamReader._charLen);
                            streamReader._bytePos = 0;
                            streamReader._byteLen = 0;
                        }
                        num3 = streamReader._charLen;
                        goto IL_02A6;
                    }
                    streamReader._byteLen += result;
                    goto IL_0205;
                    IL_01E0:
                    int result2 = configuredValueTaskAwaiter.GetResult();
                    streamReader._byteLen = result2;
                    if (streamReader._byteLen == 0)
                    {
                        num3 = streamReader._charLen;
                        goto IL_02A6;
                    }
                    IL_0205:
                    streamReader._isBlocked = streamReader._byteLen < tmpByteBuffer.Length;
                    if (!streamReader.IsPreamble())
                    {
                        if (streamReader._detectEncoding && streamReader._byteLen >= 2)
{
                            streamReader.DetectEncoding();
                        }
                        streamReader._charLen += streamReader._decoder.GetChars(tmpByteBuffer, 0, streamReader._byteLen, streamReader._charBuffer, streamReader._charLen);
                    }
                    if (streamReader._charLen == 0)
                    {
                        goto IL_0050;
                    }
                    num3 = streamReader._charLen;
                }
                catch (Exception ex)
                {
                    num2 = -2;
                    tmpByteBuffer = null;
                    tmpStream = null;
                    this.<>t__builder.SetException(ex);
                    return;
                }
                IL_02A6:
                num2 = -2;
                tmpByteBuffer = null;
                tmpStream = null;
                this.<>t__builder.SetResult(num3);
            }
References System.IO.StreamReader._byteBuffer, System.IO.StreamReader._byteLen, System.IO.StreamReader._bytePos, System.IO.StreamReader._charBuffer, System.IO.StreamReader._charLen, System.IO.StreamReader._checkPreamble, System.IO.StreamReader._decoder, System.IO.StreamReader._detectEncoding, System.IO.StreamReader._stream, System.IO.StreamReader.DetectEncoding(), System.Text.Decoder.GetChars(), System.IO.StreamReader.IsPreamble(), and System.IO.StreamReader.ReadBufferAsync().