Terraria Decompiled: System.Reflection.RuntimeModule.resolve_token_exception
resolve_token_exception()
static Exception System.Reflection.RuntimeModule.resolve_token_exception (string name, int metadataToken, ResolveTokenError error, string tokenType) inline static package
Definition at line 400 of file RuntimeModule.cs.
        {
            if (error == ResolveTokenError.OutOfRange)
            {
                return new ArgumentOutOfRangeException("metadataToken", string.Format("Token 0x{0:x} is not valid in the scope of module {1}", metadataToken, name));
            }
            return new ArgumentException(string.Format("Token 0x{0:x} is not a valid {1} token in the scope of module {2}", metadataToken, tokenType, name), "metadataToken");
        }
References System.Format, and System.Reflection.RuntimeModule.name.
Referenced by System.Reflection.RuntimeModule.ResolveField(), System.Reflection.RuntimeModule.ResolveMember(), System.Reflection.RuntimeModule.ResolveMethod(), System.Reflection.Emit.ModuleBuilder.ResolveOrGetRegisteredToken(), System.Reflection.RuntimeModule.ResolveSignature(), System.Reflection.RuntimeModule.ResolveString(), and System.Reflection.RuntimeModule.ResolveType().