Terraria Decompiled: System.Reflection.RuntimeModule.ResolveType
ResolveType() [2/2]
static Type System.Reflection.RuntimeModule.ResolveType (Module module, IntPtr monoModule, int metadataToken, Type[] genericTypeArguments, Type[] genericMethodArguments) inline static package
Definition at line 309 of file RuntimeModule.cs.
        {
            ResolveTokenError resolveTokenError;
            IntPtr intPtr = RuntimeModule.ResolveTypeToken(monoModule, metadataToken, RuntimeModule.ptrs_from_types(genericTypeArguments), RuntimeModule.ptrs_from_types(genericMethodArguments), out resolveTokenError);
            if (intPtr == IntPtr.Zero)
            {
                throw RuntimeModule.resolve_token_exception(module.Name, metadataToken, resolveTokenError, "Type");
            }
            return Type.GetTypeFromHandle(new RuntimeTypeHandle(intPtr));
        }
References System.Type.GetTypeFromHandle(), System.Reflection.Module.Name, System.Reflection.RuntimeModule.ptrs_from_types(), System.Reflection.RuntimeModule.resolve_token_exception(), System.Reflection.RuntimeModule.ResolveTypeToken(), and System.IntPtr.Zero.