Terraria Decompiled: Terraria.WorldItem.MoveInWorld
MoveInWorld()
void Terraria.WorldItem.MoveInWorld (float gravity, float maxFallSpeed, ref Vector2 wetVelocity, int i) inline private
Definition at line 1086 of file WorldItem.cs.
        {
            if (!this.shimmered && ItemID.Sets.ItemNoGravity[this.type])
            {
                this.velocity.X = this.velocity.X * 0.95f;
                if ((double)this.velocity.X < 0.1 && (double)this.velocity.X > -0.1)
                {
                    this.velocity.X = 0f;
                }
                this.velocity.Y = this.velocity.Y * 0.95f;
                if ((double)this.velocity.Y < 0.1 && (double)this.velocity.Y > -0.1)
                {
                    this.velocity.Y = 0f;
                }
            }
            else
            {
                bool flag = false;
                if (this.shimmered && this.active)
                {
                    int num = 50;
                    for (int j = 0; j < 400; j++)
                    {
                        if (i != j && Main.item[j].active && Main.item[j].shimmered)
{
                            if (num-- <= 0)
{
                                break;
                            }
                            float num2 = (float)((this.width + Main.item[j].width) / 2);
                            if (Math.Abs(base.Center.X - Main.item[j].Center.X) <= num2 && Math.Abs(base.Center.Y - Main.item[j].Center.Y) <= num2)
{
                                flag = true;
                                float num3 = Vector2.Distance(base.Center, Main.item[j].Center);
                                num2 /= num3;
                                if (num2 > 10f)
{
                                    num2 = 10f;
                                }
                                if (base.Center.X < Main.item[j].Center.X)
{
                                    if (this.velocity.X > -3f * num2)
{
                                        this.velocity.X = this.velocity.X - 0.1f * num2;
                                    }
                                    if (Main.item[j].velocity.X < 3f)
{
                                        WorldItem worldItem = Main.item[j];
                                        worldItem.velocity.X = worldItem.velocity.X + 0.1f * num2;
                                    }
                                }
                                else if (base.Center.X > Main.item[j].Center.X)
{
                                    if (this.velocity.X < 3f * num2)
{
                                        this.velocity.X = this.velocity.X + 0.1f * num2;
                                    }
                                    if (Main.item[j].velocity.X > -3f)
{
                                        WorldItem worldItem2 = Main.item[j];
                                        worldItem2.velocity.X = worldItem2.velocity.X - 0.1f * num2;
                                    }
                                }
                                else if (i < j)
{
                                    if (this.velocity.X > -3f * num2)
{
                                        this.velocity.X = this.velocity.X - 0.1f * num2;
                                    }
                                    if (Main.item[j].velocity.X < 3f * num2)
{
                                        WorldItem worldItem3 = Main.item[j];
                                        worldItem3.velocity.X = worldItem3.velocity.X + 0.1f * num2;
                                    }
                                }
                            }
                        }
                    }
                }
                this.velocity.Y = this.velocity.Y + gravity;
                if (this.velocity.Y > maxFallSpeed)
                {
                    this.velocity.Y = maxFallSpeed;
                }
                this.velocity.X = this.velocity.X * 0.95f;
                if ((double)this.velocity.X < 0.1 && (double)this.velocity.X > -0.1)
                {
                    this.velocity.X = 0f;
                }
                if (flag)
                {
                    this.velocity.X = this.velocity.X * 0.8f;
                }
            }
            this.onConveyor = Collision.ApplyConveyorBeltMovementToVelocity(this, ref this.velocity);
            bool flag2 = Collision.LavaCollision(this.position, this.width, this.height);
            if (flag2)
            {
                this.lavaWet = true;
            }
            bool flag3 = Collision.WetCollision(this.position, this.width, this.height);
            if (Collision.honey)
            {
                this.honeyWet = true;
            }
            if (Collision.shimmer)
            {
                this.shimmerWet = true;
            }
            if (flag3)
            {
                if (!this.wet)
                {
                    if (this.wetCount == 0)
                    {
                        this.wetCount = 20;
                        if (!flag2)
{
                            if (this.shimmerWet)
{
                                for (int k = 0; k < 10; k++)
{
                                    int num4 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, 308, 0f, 0f, 0, default(Color), 1f);
                                    Dust dust = Main.dust[num4];
                                    dust.velocity.Y = dust.velocity.Y - 4f;
                                    Dust dust2 = Main.dust[num4];
                                    dust2.velocity.X = dust2.velocity.X * 2.5f;
                                    Main.dust[num4].scale = 0.8f;
                                    Main.dust[num4].noGravity = true;
                                    int num5 = Main.rand.Next(6);
                                    if (num5 == 0)
{
                                        Main.dust[num4].color = new Color(255, 255, 210);
                                    }
                                    else if (num5 == 1)
{
                                        Main.dust[num4].color = new Color(190, 245, 255);
                                    }
                                    else if (num5 == 2)
{
                                        Main.dust[num4].color = new Color(255, 150, 255);
                                    }
                                    else
{
                                        Main.dust[num4].color = new Color(190, 175, 255);
                                    }
                                }
                                SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 4, 1f, 0f);
                            }
                            else if (this.honeyWet)
{
                                for (int l = 0; l < 5; l++)
{
                                    int num6 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, 152, 0f, 0f, 0, default(Color), 1f);
                                    Dust dust3 = Main.dust[num6];
                                    dust3.velocity.Y = dust3.velocity.Y - 1f;
                                    Dust dust4 = Main.dust[num6];
                                    dust4.velocity.X = dust4.velocity.X * 2.5f;
                                    Main.dust[num6].scale = 1.3f;
                                    Main.dust[num6].alpha = 100;
                                    Main.dust[num6].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                            else
{
                                for (int m = 0; m < 10; m++)
{
                                    int num7 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, Dust.dustWater(), 0f, 0f, 0, default(Color), 1f);
                                    Dust dust5 = Main.dust[num7];
                                    dust5.velocity.Y = dust5.velocity.Y - 4f;
                                    Dust dust6 = Main.dust[num7];
                                    dust6.velocity.X = dust6.velocity.X * 2.5f;
                                    Main.dust[num7].scale *= 0.8f;
                                    Main.dust[num7].alpha = 100;
                                    Main.dust[num7].noGravity = true;
                                }
                                SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                            }
                        }
                        else
{
                            for (int n = 0; n < 5; n++)
{
                                int num8 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, 35, 0f, 0f, 0, default(Color), 1f);
                                Dust dust7 = Main.dust[num8];
                                dust7.velocity.Y = dust7.velocity.Y - 1.5f;
                                Dust dust8 = Main.dust[num8];
                                dust8.velocity.X = dust8.velocity.X * 2.5f;
                                Main.dust[num8].scale = 1.3f;
                                Main.dust[num8].alpha = 100;
                                Main.dust[num8].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        }
                    }
                    this.wet = true;
                }
            }
            else if (this.wet)
            {
                this.wet = false;
                if (this.wetCount == 0)
                {
                    this.wetCount = 20;
                    if (!this.lavaWet)
                    {
                        if (this.shimmerWet)
{
                            for (int num9 = 0; num9 < 10; num9++)
{
                                int num10 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, 308, 0f, 0f, 0, default(Color), 1f);
                                Dust dust9 = Main.dust[num10];
                                dust9.velocity.Y = dust9.velocity.Y - 4f;
                                Dust dust10 = Main.dust[num10];
                                dust10.velocity.X = dust10.velocity.X * 2.5f;
                                Main.dust[num10].scale = 0.8f;
                                Main.dust[num10].noGravity = true;
                                int num11 = Main.rand.Next(6);
                                if (num11 == 0)
{
                                    Main.dust[num10].color = new Color(255, 255, 210);
                                }
                                else if (num11 == 1)
{
                                    Main.dust[num10].color = new Color(190, 245, 255);
                                }
                                else if (num11 == 2)
{
                                    Main.dust[num10].color = new Color(255, 150, 255);
                                }
                                else
{
                                    Main.dust[num10].color = new Color(190, 175, 255);
                                }
                            }
                            SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 5, 1f, 0f);
                        }
                        else if (this.honeyWet)
{
                            for (int num12 = 0; num12 < 5; num12++)
{
                                int num13 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, 152, 0f, 0f, 0, default(Color), 1f);
                                Dust dust11 = Main.dust[num13];
                                dust11.velocity.Y = dust11.velocity.Y - 1f;
                                Dust dust12 = Main.dust[num13];
                                dust12.velocity.X = dust12.velocity.X * 2.5f;
                                Main.dust[num13].scale = 1.3f;
                                Main.dust[num13].alpha = 100;
                                Main.dust[num13].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        }
                        else
{
                            for (int num14 = 0; num14 < 10; num14++)
{
                                int num15 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2)), this.width + 12, 24, Dust.dustWater(), 0f, 0f, 0, default(Color), 1f);
                                Dust dust13 = Main.dust[num15];
                                dust13.velocity.Y = dust13.velocity.Y - 4f;
                                Dust dust14 = Main.dust[num15];
                                dust14.velocity.X = dust14.velocity.X * 2.5f;
                                Main.dust[num15].scale *= 0.8f;
                                Main.dust[num15].alpha = 100;
                                Main.dust[num15].noGravity = true;
                            }
                            SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                        }
                    }
                    else
                    {
                        for (int num16 = 0; num16 < 5; num16++)
{
                            int num17 = Dust.NewDust(new Vector2(this.position.X - 6f, this.position.Y + (float)(this.height / 2) - 8f), this.width + 12, 24, 35, 0f, 0f, 0, default(Color), 1f);
                            Dust dust15 = Main.dust[num17];
                            dust15.velocity.Y = dust15.velocity.Y - 1.5f;
                            Dust dust16 = Main.dust[num17];
                            dust16.velocity.X = dust16.velocity.X * 2.5f;
                            Main.dust[num17].scale = 1.3f;
                            Main.dust[num17].alpha = 100;
                            Main.dust[num17].noGravity = true;
                        }
                        SoundEngine.PlaySound(19, (int)this.position.X, (int)this.position.Y, 1, 1f, 0f);
                    }
                }
            }
            if (!this.wet)
            {
                this.lavaWet = false;
                this.honeyWet = false;
                this.shimmerWet = false;
            }
            if (this.wetCount > 0)
            {
                this.wetCount -= 1;
            }
            if (this.wet)
            {
                if (this.wet)
                {
                    Vector2 velocity = this.velocity;
                    this.velocity = Collision.TileCollision(this.position, this.velocity, this.width, this.height, false, false, 1, false, true, true);
                    if (this.velocity.X != velocity.X)
                    {
                        wetVelocity.X = this.velocity.X;
                    }
                    if (this.velocity.Y != velocity.Y)
                    {
                        wetVelocity.Y = this.velocity.Y;
                    }
                }
            }
            else
            {
                this.velocity = Collision.TileCollision(this.position, this.velocity, this.width, this.height, false, false, 1, false, true, true);
            }
            this.ApplyMovement(ref wetVelocity);
            Vector4 vector = Collision.SlopeCollision(this.position, this.velocity, this.width, this.height, gravity, false, true);
            this.position.X = vector.X;
            this.position.Y = vector.Y;
            this.velocity.X = vector.Z;
            this.velocity.Y = vector.W;
        }
References System.Math.Abs(), Terraria.WorldItem.active, Terraria.Dust.alpha, Terraria.Collision.ApplyConveyorBeltMovementToVelocity(), Terraria.WorldItem.ApplyMovement(), Terraria.Entity.Center, Terraria.Dust.color, Microsoft.Xna.Framework.Vector2.Distance(), Terraria.Main.dust, Terraria.Dust.dustWater(), Terraria.Entity.height, Terraria.Collision.honey, Terraria.Entity.honeyWet, Terraria.Main.item, Terraria.ID.ItemID.Sets.ItemNoGravity, Terraria.Collision.LavaCollision(), Terraria.Entity.lavaWet, Terraria.Dust.NewDust(), Terraria.Dust.noGravity, Terraria.Audio.SoundEngine.PlaySound(), Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.Collision.shimmer, Terraria.WorldItem.shimmered, Terraria.Entity.shimmerWet, Terraria.Collision.SlopeCollision(), Terraria.Collision.TileCollision(), Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector4.W, Terraria.Entity.wet, Terraria.Collision.WetCollision(), Terraria.Entity.wetCount, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, Microsoft.Xna.Framework.Vector4.X, Microsoft.Xna.Framework.Vector2.Y, Microsoft.Xna.Framework.Vector4.Y, and Microsoft.Xna.Framework.Vector4.Z.
Referenced by Terraria.WorldItem.UpdateItem().