Terraria Decompiled: Terraria.WorldItem.CheckLavaDeath
CheckLavaDeath()
void Terraria.WorldItem.CheckLavaDeath (int i) inline private
Definition at line 961 of file WorldItem.cs.
        {
            if (this.type == 267)
            {
                if (Main.netMode != 1)
                {
                    int num = this.stack;
                    this.TurnToAir(false);
                    bool flag = false;
                    for (int j = 0; j < Main.maxNPCs; j++)
                    {
                        if (Main.npc[j].active && Main.npc[j].type == 22)
{
                            int num2 = -Main.npc[j].direction;
                            if (Main.npc[j].IsNPCValidForBestiaryKillCredit())
{
                                Main.BestiaryTracker.Kills.RegisterKill(Main.npc[j]);
                            }
                            Main.npc[j].StrikeNPCNoInteraction(9999, 10f, -num2, false, false, false);
                            num--;
                            flag = true;
                            if (Main.netMode == 2)
{
                                NetMessage.SendData(28, -1, -1, null, j, 9999f, 10f, (float)(-(float)num2), 0, 0, 0);
                            }
                            NPC.SpawnWOF(this.position);
                        }
                    }
                    if (flag)
                    {
                        List<int> list = new List<int>();
                        for (int k = 0; k < Main.maxNPCs; k++)
{
                            if (num <= 0)
{
                                break;
                            }
                            NPC npc = Main.npc[k];
                            if (npc.active && npc.isLikeATownNPC)
{
                                list.Add(k);
                            }
                        }
                        while (num > 0 && list.Count > 0)
{
                            int num3 = Main.rand.Next(list.Count);
                            int num4 = list[num3];
                            list.RemoveAt(num3);
                            int num5 = -Main.npc[num4].direction;
                            if (Main.npc[num4].IsNPCValidForBestiaryKillCredit())
{
                                Main.BestiaryTracker.Kills.RegisterKill(Main.npc[num4]);
                            }
                            Main.npc[num4].StrikeNPCNoInteraction(9999, 10f, -num5, false, false, false);
                            num--;
                            if (Main.netMode == 2)
{
                                NetMessage.SendData(28, -1, -1, null, num4, 9999f, 10f, (float)(-(float)num5), 0, 0, 0);
                            }
                        }
                    }
                    NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                    return;
                }
            }
            else if (this.playerIndexTheItemIsReservedFor == Main.myPlayer)
            {
                if (this.type <= 0 && this.type >= (int)ItemID.Count)
                {
                    return;
                }
                if ((this.rare != 0 && this.rare != -1) || ItemID.Sets.IsLavaImmuneRegardlessOfRarity[this.type])
                {
                    return;
                }
                this.TurnToAir(false);
                if (Main.netMode != 0)
                {
                    NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.NPC.active, Terraria.Main.BestiaryTracker, Terraria.ID.ItemID.Count, Terraria.Entity.direction, Terraria.ID.ItemID.Sets.IsLavaImmuneRegardlessOfRarity, Terraria.NPC.isLikeATownNPC, Terraria.NPC.IsNPCValidForBestiaryKillCredit(), System.list, Terraria.Main.maxNPCs, Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.Main.npc, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.Main.rand, Terraria.WorldItem.rare, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnWOF(), Terraria.WorldItem.stack, Terraria.NPC.StrikeNPCNoInteraction(), Terraria.WorldItem.TurnToAir(), Terraria.NPC.type, and Terraria.WorldItem.type.
Referenced by Terraria.WorldItem.UpdateItem().