Terraria Decompiled: Terraria.WorldItem.DespawnIfMeetingConditions
DespawnIfMeetingConditions()
void Terraria.WorldItem.DespawnIfMeetingConditions (int i) inline private
Definition at line 909 of file WorldItem.cs.
        {
            if (this.type == 75 && Main.dayTime && !Main.remixWorld && !this.shimmered && !this.beingGrabbed)
            {
                for (int j = 0; j < 10; j++)
                {
                    Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X, this.velocity.Y, 150, default(Color), 1.2f);
                }
                for (int k = 0; k < 3; k++)
                {
                    Gore.NewGore(this.position, new Vector2(this.velocity.X, this.velocity.Y), Main.rand.Next(16, 18), 1f);
                }
                this.TurnToAir(false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                }
            }
            if (this.type == 4143 && this.timeSinceItemSpawned > 300)
            {
                for (int l = 0; l < 20; l++)
                {
                    Dust.NewDust(this.position, this.width, this.height, 15, this.velocity.X, this.velocity.Y, 150, Color.Lerp(Color.CornflowerBlue, Color.Indigo, Main.rand.NextFloat()), 1.2f);
                }
                this.TurnToAir(false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                }
            }
            if (this.type == 3822 && !DD2Event.Ongoing)
            {
                int num = Main.rand.Next(18, 24);
                for (int m = 0; m < num; m++)
                {
                    int num2 = Dust.NewDust(base.Center, 0, 0, 61, 0f, 0f, 0, default(Color), 1.7f);
                    Main.dust[num2].velocity *= 8f;
                    Dust dust = Main.dust[num2];
                    dust.velocity.Y = dust.velocity.Y - 1f;
                    Main.dust[num2].position = Vector2.Lerp(Main.dust[num2].position, base.Center, 0.5f);
                    Main.dust[num2].noGravity = true;
                    Main.dust[num2].noLight = true;
                }
                this.TurnToAir(false);
                if (Main.netMode == 2)
                {
                    NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Microsoft.Xna.Framework.Color.CornflowerBlue, Terraria.Main.dayTime, Terraria.Main.dust, Terraria.Entity.height, Microsoft.Xna.Framework.Color.Indigo, Microsoft.Xna.Framework.Color.Lerp(), Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.Main.netMode, Terraria.Dust.NewDust(), Terraria.Gore.NewGore(), Terraria.Dust.noGravity, Terraria.Dust.noLight, Terraria.GameContent.Events.DD2Event.Ongoing, Terraria.Dust.position, Terraria.Entity.position, Terraria.Main.rand, Terraria.Main.remixWorld, Terraria.NetMessage.SendData(), Terraria.WorldItem.timeSinceItemSpawned, Terraria.WorldItem.TurnToAir(), Terraria.WorldItem.type, Terraria.Dust.velocity, Terraria.Entity.velocity, Terraria.Entity.width, and Microsoft.Xna.Framework.Vector2.X.
Referenced by Terraria.WorldItem.UpdateItem().