Terraria Decompiled: Terraria.WorldItem.GetPickedUpByMonsters_Special
GetPickedUpByMonsters_Special()
void Terraria.WorldItem.GetPickedUpByMonsters_Special (int i) inline private
Definition at line 1422 of file WorldItem.cs.
        {
            bool flag = false;
            bool flag2 = false;
            int type = this.type;
            if ((type == 89 || type == 3507) && !NPC.unlockedSlimeCopperSpawn)
            {
                flag = true;
                flag2 = true;
            }
            if (!flag2)
            {
                return;
            }
            bool flag3 = false;
            Rectangle hitbox = base.Hitbox;
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.active && flag && npc.type >= 0 && npc.type < (int)NPCID.Count && NPCID.Sets.CanConvertIntoCopperSlimeTownNPC[npc.type] && hitbox.Intersects(npc.Hitbox))
                {
                    flag3 = true;
                    NPC.TransformCopperSlime(j);
                    break;
                }
            }
            if (flag3)
            {
                this.TurnToAir(true);
                NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
            }
        }
References Terraria.NPC.active, Terraria.ID.NPCID.Sets.CanConvertIntoCopperSlimeTownNPC, Terraria.ID.NPCID.Count, Terraria.Entity.Hitbox, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.Main.maxNPCs, Terraria.Main.npc, Terraria.NetMessage.SendData(), Terraria.NPC.TransformCopperSlime(), Terraria.WorldItem.TurnToAir(), Terraria.NPC.type, Terraria.WorldItem.type, and Terraria.NPC.unlockedSlimeCopperSpawn.
Referenced by Terraria.WorldItem.UpdateItem().