Terraria Decompiled: Terraria.WorldItem.SetDefaults
SetDefaults()
void Terraria.WorldItem.SetDefaults (int type) inline
Definition at line 388 of file WorldItem.cs.
        {
            this.ResetStats(type);
            this.inner.SetDefaults(type, null);
            this.UpdateEntityFields();
        }
References Terraria.WorldItem.inner, Terraria.WorldItem.ResetStats(), Terraria.Item.SetDefaults(), and Terraria.WorldItem.UpdateEntityFields().
Referenced by Terraria.MessageBuffer.GetData(), Terraria.WorldItem.GetShimmered(), Terraria.GameContent.Tile_Entities.TEDeadCellsDisplayJar.TryPlacing(), Terraria.GameContent.Tile_Entities.TEFoodPlatter.TryPlacing(), Terraria.GameContent.Tile_Entities.TEItemFrame.TryPlacing(), Terraria.GameContent.Tile_Entities.TEWeaponsRack.TryPlacing(), and Terraria.WorldItem.UpdateItem().