Terraria Decompiled: Terraria.WorldItem.SpawnShimmeredItem
SpawnShimmeredItem()
void Terraria.WorldItem.SpawnShimmeredItem (short idToCheck, bool splitToSides, int numberOfItems) inline private
Definition at line 883 of file WorldItem.cs.
        {
            int num = Item.NewItem(this.GetItemSource_Misc(ItemSourceID.Shimmer), (int)this.position.X, (int)this.position.Y, this.width, this.height, (int)idToCheck, 1, false, 0, false);
            WorldItem worldItem = Main.item[num];
            worldItem.stack = 1;
            worldItem.shimmerTime = 1f;
            worldItem.shimmered = true;
            worldItem.shimmerWet = true;
            worldItem.wet = true;
            worldItem.velocity *= 0.1f;
            worldItem.playerIndexTheItemIsReservedFor = Main.myPlayer;
            if (splitToSides)
            {
                worldItem.velocity.X = 1f * (float)numberOfItems;
                WorldItem worldItem2 = worldItem;
                worldItem2.velocity.X = worldItem2.velocity.X * (1f + (float)numberOfItems * 0.05f);
                if (numberOfItems % 2 == 0)
                {
                    WorldItem worldItem3 = worldItem;
                    worldItem3.velocity.X = worldItem3.velocity.X * -1f;
                }
            }
            NetMessage.SendData(145, -1, -1, null, num, 1f, 0f, 0f, 0, 0, 0);
        }
References Terraria.WorldItem.GetItemSource_Misc(), Terraria.Main.item, Terraria.Main.myPlayer, Terraria.Item.NewItem(), Terraria.NetMessage.SendData(), and Terraria.ID.ItemSourceID.Shimmer.
Referenced by Terraria.WorldItem.TryGrantingMakeAWishSet().