Terraria Decompiled: Terraria.WorldItem.ShimmerEffect
ShimmerEffect()
static void Terraria.WorldItem.ShimmerEffect (Vector2 shimmerPositon) inline static
Definition at line 2113 of file WorldItem.cs.
        {
            SoundEngine.PlaySound(SoundID.Item176, (int)shimmerPositon.X, (int)shimmerPositon.Y, 0f, 1f);
            for (int i = 0; i < 20; i++)
            {
                int num = Dust.NewDust(shimmerPositon, 1, 1, 309, 0f, 0f, 0, default(Color), 1f);
                Main.dust[num].scale *= 1.2f;
                int num2 = Main.rand.Next(6);
                if (num2 == 0)
                {
                    Main.dust[num].color = new Color(255, 255, 210);
                }
                else if (num2 == 1)
                {
                    Main.dust[num].color = new Color(190, 245, 255);
                }
                else if (num2 == 2)
                {
                    Main.dust[num].color = new Color(255, 150, 255);
                }
                else
                {
                    Main.dust[num].color = new Color(190, 175, 255);
                }
            }
        }
References Terraria.Dust.color, Terraria.Main.dust, Terraria.ID.SoundID.Item176, Terraria.Dust.NewDust(), Terraria.Audio.SoundEngine.PlaySound(), Terraria.Main.rand, Terraria.Dust.scale, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.NPC.GetShimmered(), and Terraria.WorldItem.GetShimmered().