Terraria Decompiled: Terraria.WorldItem.TurnToAir
TurnToAir()
void Terraria.WorldItem.TurnToAir (bool fullReset = false) inline
Definition at line 396 of file WorldItem.cs.
        {
            this.inner.TurnToAir(fullReset);
            this.UpdateEntityFields();
        }
References Terraria.WorldItem.inner, Terraria.Item.TurnToAir(), and Terraria.WorldItem.UpdateEntityFields().
Referenced by Terraria.WorldItem.CheckInWorld(), Terraria.WorldItem.CheckLavaDeath(), Terraria.GameContent.Events.DD2Event.ClearAllDD2EnergyCrystalsInGame(), Terraria.WorldItem.ClearOut(), Terraria.WorldItem.DespawnIfMeetingConditions(), Terraria.GameContent.EmergencyStacking.DoTransfer(), Terraria.NPC.DropItemInstanced(), Terraria.GameContent.ItemDropRules.CommonCode.DropItemLocalPerClientAndSetNPCMoneyTo0(), Terraria.WorldItem.GetPickedUpByMonsters_Money(), Terraria.WorldItem.GetPickedUpByMonsters_Special(), Terraria.WorldItem.GetShimmered(), Terraria.Wiring.TryAddingToEmptySlot(), Terraria.Wiring.TryAddingToStack(), Terraria.WorldItem.TryCombiningIntoNearbyItems(), Terraria.WorldItem.TryGrantingMakeAWishSet(), and Terraria.WorldItem.UpdateItem().