Terraria Decompiled: Terraria.WorldItem.Shimmering
Shimmering()
void Terraria.WorldItem.Shimmering () inline private
Definition at line 1045 of file WorldItem.cs.
        {
            if (this.inner.CanShimmer())
            {
                int num = (int)(base.Center.X / 16f);
                int num2 = (int)(this.position.Y / 16f - 1f);
                Tile tile = Main.tile[num, num2];
                if (WorldGen.InWorld(num, num2, 0) && tile != null && tile.liquid > 0 && tile.shimmer())
                {
                    if (this.playerIndexTheItemIsReservedFor == Main.myPlayer && Main.netMode != 1)
                    {
                        this.shimmerTime += 0.01f;
                        if (this.shimmerTime > 0.9f)
{
                            this.shimmerTime = 0.9f;
                            this.GetShimmered();
                            return;
                        }
                    }
                    else
                    {
                        this.shimmerTime += 0.01f;
                        if (this.shimmerTime > 1f)
{
                            this.shimmerTime = 1f;
                        }
                    }
                    return;
                }
            }
            if (this.shimmerTime > 0f)
            {
                this.shimmerTime -= 0.01f;
                if (this.shimmerTime < 0f)
                {
                    this.shimmerTime = 0f;
                }
            }
        }
References Terraria.Item.CanShimmer(), Terraria.WorldItem.GetShimmered(), Terraria.WorldItem.inner, int, Terraria.WorldGen.InWorld(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.Tile.shimmer(), Terraria.WorldItem.shimmerTime, Terraria.Main.tile, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.UpdateItem().