Terraria Decompiled: Terraria.WorldItem.GetPickedUpByMonsters_Money
GetPickedUpByMonsters_Money()
void Terraria.WorldItem.GetPickedUpByMonsters_Money (int i) inline private
Definition at line 1456 of file WorldItem.cs.
        {
            Rectangle rectangle = new Rectangle((int)this.position.X, (int)this.position.Y, this.width, this.height);
            for (int j = 0; j < Main.maxNPCs; j++)
            {
                NPC npc = Main.npc[j];
                if (npc.active && npc.lifeMax > 5 && !npc.friendly && !npc.immortal && !npc.dontTakeDamage && !npc.SpawnedFromStatue && !NPCID.Sets.CantTakeLunchMoney[npc.type])
                {
                    float num = (float)this.stack;
                    float num2 = 1f;
                    if (this.type == 72)
                    {
                        num2 = 100f;
                    }
                    if (this.type == 73)
                    {
                        num2 = 10000f;
                    }
                    if (this.type == 74)
                    {
                        num2 = 1000000f;
                    }
                    num *= num2;
                    float num3 = (float)npc.extraValue;
                    int num4 = npc.realLife;
                    NPC npc2 = npc;
                    if (num4 >= 0 && Main.npc[num4].active)
                    {
                        npc2 = Main.npc[num4];
                        num3 = (float)npc2.extraValue;
                    }
                    else
                    {
                        num4 = -1;
                    }
                    if (num3 < num && num3 + num < 999000000f)
                    {
                        Rectangle rectangle2 = new Rectangle((int)npc.position.X, (int)npc.position.Y, npc.width, npc.height);
                        if (rectangle.Intersects(rectangle2))
{
                            float num5 = (float)Main.rand.Next(50, 76) * 0.01f;
                            if (this.type == 71)
{
                                num5 += (float)Main.rand.Next(51) * 0.01f;
                            }
                            if (this.type == 72)
{
                                num5 += (float)Main.rand.Next(26) * 0.01f;
                            }
                            if (num5 > 1f)
{
                                num5 = 1f;
                            }
                            int num6 = (int)((float)this.stack * num5);
                            if (num6 < 1)
{
                                num6 = 1;
                            }
                            if (num6 > this.stack)
{
                                num6 = this.stack;
                            }
                            this.stack -= num6;
                            int num7 = (int)((float)num6 * num2);
                            int num8 = j;
                            if (num4 >= 0)
{
                                num8 = num4;
                            }
                            npc2.extraValue += num7;
                            if (Main.netMode == 0)
{
                                npc2.moneyPing(this.position);
                            }
                            else
{
                                NetMessage.SendData(92, -1, -1, null, num8, (float)num7, this.position.X, this.position.Y, 0, 0, 0);
                            }
                            if (this.stack <= 0)
{
                                this.TurnToAir(true);
                            }
                            NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                        }
                    }
                }
            }
        }
References Terraria.NPC.active, Terraria.ID.NPCID.Sets.CantTakeLunchMoney, Terraria.NPC.dontTakeDamage, Terraria.NPC.extraValue, Terraria.NPC.friendly, Terraria.Entity.height, Terraria.NPC.immortal, int, Microsoft.Xna.Framework.Rectangle.Intersects(), Terraria.NPC.lifeMax, Terraria.Main.maxNPCs, Terraria.NPC.moneyPing(), Terraria.Main.netMode, Terraria.Main.npc, Terraria.Entity.position, Terraria.Main.rand, Terraria.NPC.realLife, Terraria.NetMessage.SendData(), Terraria.NPC.SpawnedFromStatue, Terraria.WorldItem.stack, Terraria.WorldItem.TurnToAir(), Terraria.NPC.type, Terraria.WorldItem.type, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.UpdateItem().