Terraria Decompiled: Terraria.WorldItem.UpdateItem_VisualEffects
UpdateItem_VisualEffects()
void Terraria.WorldItem.UpdateItem_VisualEffects () inline private
Definition at line 1546 of file WorldItem.cs.
        {
            if (this.type == 5043)
            {
                float num = (float)Main.rand.Next(90, 111) * 0.01f;
                num *= (Main.essScale + 0.5f) / 2f;
                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.25f * num, 0.25f * num, 0.25f * num);
                return;
            }
            if (this.type == 116)
            {
                float num2 = (float)Main.rand.Next(95, 106) * 0.01f;
                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.56f * num2, 0.43f * num2, 0.15f * num2);
                if (Main.rand.Next(250) == 0)
                {
                    int num3 = Dust.NewDust(this.position, this.width, this.height, 6, 0f, 0f, 0, default(Color), (float)Main.rand.Next(3));
                    if (Main.dust[num3].scale > 1f)
                    {
                        Main.dust[num3].noGravity = true;
                        return;
                    }
                }
            }
            else
            {
                if (this.type == 3191)
                {
                    float num4 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num4 *= (Main.essScale + 0.5f) / 2f;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.3f * num4, 0.1f * num4, 0.25f * num4);
                    return;
                }
                if (this.type == 520 || this.type == 3454)
                {
                    float num5 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num5 *= Main.essScale;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.5f * num5, 0.1f * num5, 0.25f * num5);
                    return;
                }
                if (this.type == 521 || this.type == 3455)
                {
                    float num6 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num6 *= Main.essScale;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.25f * num6, 0.1f * num6, 0.5f * num6);
                    return;
                }
                if (this.type == 547 || this.type == 3453)
                {
                    float num7 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num7 *= Main.essScale;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.5f * num7, 0.3f * num7, 0.05f * num7);
                    return;
                }
                if (this.type == 548)
                {
                    float num8 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num8 *= Main.essScale;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.1f * num8, 0.1f * num8, 0.6f * num8);
                    return;
                }
                if (this.type == 575)
                {
                    float num9 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num9 *= Main.essScale;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.1f * num9, 0.3f * num9, 0.5f * num9);
                    return;
                }
                if (this.type == 549)
                {
                    float num10 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num10 *= Main.essScale;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.1f * num10, 0.5f * num10, 0.2f * num10);
                    return;
                }
                if (this.type == 58 || this.type == 1734 || this.type == 1867)
                {
                    float num11 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num11 *= Main.essScale * 0.5f;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.5f * num11, 0.1f * num11, 0.1f * num11);
                    return;
                }
                if (this.type == 184 || this.type == 1735 || this.type == 1868 || this.type == 4143)
                {
                    float num12 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num12 *= Main.essScale * 0.5f;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.1f * num12, 0.1f * num12, 0.5f * num12);
                    return;
                }
                if (this.type == 522)
                {
                    float num13 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num13 *= Main.essScale * 0.2f;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.5f * num13, 1f * num13, 0.1f * num13);
                    return;
                }
                if (this.type == 1332)
                {
                    float num14 = (float)Main.rand.Next(90, 111) * 0.01f;
                    num14 *= Main.essScale * 0.2f;
                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f * num14, 1f * num14, 0.1f * num14);
                    return;
                }
                if (this.type == 3456)
                {
                    Lighting.AddLight(base.Center, new Vector3(0.2f, 0.4f, 0.5f) * Main.essScale);
                    return;
                }
                if (this.type == 3457)
                {
                    Lighting.AddLight(base.Center, new Vector3(0.4f, 0.2f, 0.5f) * Main.essScale);
                    return;
                }
                if (this.type == 3458)
                {
                    Lighting.AddLight(base.Center, new Vector3(0.5f, 0.4f, 0.2f) * Main.essScale);
                    return;
                }
                if (this.type == 3459)
                {
                    Lighting.AddLight(base.Center, new Vector3(0.2f, 0.2f, 0.5f) * Main.essScale);
                    return;
                }
                if (this.type == 501)
                {
                    if (Main.rand.Next(6) == 0)
                    {
                        int num15 = Dust.NewDust(this.position, this.width, this.height, 55, 0f, 0f, 200, this.color, 1f);
                        Main.dust[num15].velocity *= 0.3f;
                        Main.dust[num15].scale *= 0.5f;
                        return;
                    }
                }
                else
                {
                    if (this.type == 3822)
                    {
                        Lighting.AddLight(base.Center, 0.1f, 0.3f, 0.1f);
                        return;
                    }
                    if (this.type == 1970)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.75f, 0f, 0.75f);
                        return;
                    }
                    if (this.type == 1972)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0f, 0f, 0.75f);
                        return;
                    }
                    if (this.type == 1971)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.75f, 0.75f, 0f);
                        return;
                    }
                    if (this.type == 1973)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0f, 0.75f, 0f);
                        return;
                    }
                    if (this.type == 1974)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.75f, 0f, 0f);
                        return;
                    }
                    if (this.type == 1975)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.75f, 0.75f, 0.75f);
                        return;
                    }
                    if (this.type == 1976)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.75f, 0.375f, 0f);
                        return;
                    }
                    if (this.type == 2679)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.6f, 0f, 0.6f);
                        return;
                    }
                    if (this.type == 2687)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0f, 0f, 0.6f);
                        return;
                    }
                    if (this.type == 2689)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.6f, 0.6f, 0f);
                        return;
                    }
                    if (this.type == 2683)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0f, 0.6f, 0f);
                        return;
                    }
                    if (this.type == 2685)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.6f, 0f, 0f);
                        return;
                    }
                    if (this.type == 2681)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.6f, 0.6f, 0.6f);
                        return;
                    }
                    if (this.type == 2677)
                    {
                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.6f, 0.375f, 0f);
                        return;
                    }
                    if (this.type == 105)
                    {
                        if (!this.wet)
{
                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f, 0.95f, 0.8f);
                            return;
                        }
                    }
                    else
                    {
                        if (this.type == 2701)
{
                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.7f, 0.65f, 0.55f);
                            return;
                        }
                        if (this.createTile == 4)
{
                            int placeStyle = this.placeStyle;
                            if ((!this.wet && ItemID.Sets.Torches[this.type]) || ItemID.Sets.WaterTorches[this.type])
{
                                Lighting.AddLight(base.Center, placeStyle);
                                return;
                            }
                        }
                        else if (this.type == 3114)
{
                            if (!this.wet)
{
                                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f, 0f, 1f);
                                return;
                            }
                        }
                        else if (this.type == 1245)
{
                            if (!this.wet)
{
                                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f, 0.5f, 0f);
                                return;
                            }
                        }
                        else if (this.type == 433)
{
                            if (!this.wet)
{
                                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.5f * Main.demonTorch + 1f * (1f - Main.demonTorch), 0.3f, 1f * Main.demonTorch + 0.5f * (1f - Main.demonTorch));
                                return;
                            }
                        }
                        else
{
                            if (this.type == 523)
{
                                Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.85f, 1.2f, 0.7f);
                                return;
                            }
                            if (this.type == 974)
{
                                if (!this.wet)
{
                                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.75f, 0.85f, 1.4f);
                                    return;
                                }
                            }
                            else
{
                                if (this.type == 1333)
{
                                    Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1.25f, 1.25f, 0.7f);
                                    return;
                                }
                                if (this.type == 4383)
{
                                    if (!this.wet)
{
                                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1.4f, 0.85f, 0.55f);
                                        return;
                                    }
                                }
                                else if (this.type == 5293)
{
                                    if (!this.wet)
{
                                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.25f, 0.65f, 1f);
                                        return;
                                    }
                                }
                                else if (this.type == 5353)
{
                                    if (!this.wet)
{
                                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.81f, 0.72f, 1f);
                                        return;
                                    }
                                }
                                else
{
                                    if (this.type == 4384)
{
                                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.25f, 1.3f, 0.8f);
                                        return;
                                    }
                                    if (this.type == 3045)
{
                                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), (float)Main.DiscoR / 255f, (float)Main.DiscoG / 255f, (float)Main.DiscoB / 255f);
                                        return;
                                    }
                                    if (this.type == 3004)
{
                                        Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.95f, 0.65f, 1.3f);
                                        return;
                                    }
                                    if (this.type == 2274)
{
                                        float num16 = 0.75f;
                                        float num17 = 1.3499999f;
                                        float num18 = 1.5f;
                                        if (!this.wet)
{
                                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), num16, num17, num18);
                                            return;
                                        }
                                    }
                                    else if (this.type >= 427 && this.type <= 432)
{
                                        if (!this.wet)
{
                                            float num19 = 0f;
                                            float num20 = 0f;
                                            float num21 = 0f;
                                            int num22 = this.type - 426;
                                            if (num22 == 1)
{
                                                num19 = 0.1f;
                                                num20 = 0.2f;
                                                num21 = 1.1f;
                                            }
                                            if (num22 == 2)
{
                                                num19 = 1f;
                                                num20 = 0.1f;
                                                num21 = 0.1f;
                                            }
                                            if (num22 == 3)
{
                                                num19 = 0f;
                                                num20 = 1f;
                                                num21 = 0.1f;
                                            }
                                            if (num22 == 4)
{
                                                num19 = 0.9f;
                                                num20 = 0f;
                                                num21 = 0.9f;
                                            }
                                            if (num22 == 5)
{
                                                num19 = 1.3f;
                                                num20 = 1.3f;
                                                num21 = 1.3f;
                                            }
                                            if (num22 == 6)
{
                                                num19 = 0.9f;
                                                num20 = 0.9f;
                                                num21 = 0f;
                                            }
                                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), num19, num20, num21);
                                            return;
                                        }
                                    }
                                    else
{
                                        if (this.type == 2777 || this.type == 2778 || this.type == 2779 || this.type == 2780 || this.type == 2781 || this.type == 2760 || this.type == 2761 || this.type == 2762 || this.type == 3524)
{
                                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.4f, 0.16f, 0.36f);
                                            return;
                                        }
                                        if (this.type == 2772 || this.type == 2773 || this.type == 2774 || this.type == 2775 || this.type == 2776 || this.type == 2757 || this.type == 2758 || this.type == 2759 || this.type == 3523)
{
                                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0f, 0.36f, 0.4f);
                                            return;
                                        }
                                        if (this.type == 2782 || this.type == 2783 || this.type == 2784 || this.type == 2785 || this.type == 2786 || this.type == 2763 || this.type == 2764 || this.type == 2765 || this.type == 3522)
{
                                            Lighting.AddLight((int)((this.position.X + (float)(this.width / 2)) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.5f, 0.25f, 0.05f);
                                            return;
                                        }
                                        if (this.type == 3462 || this.type == 3463 || this.type == 3464 || this.type == 3465 || this.type == 3466 || this.type == 3381 || this.type == 3382 || this.type == 3383 || this.type == 3525)
{
                                            Lighting.AddLight(base.Center, 0.3f, 0.3f, 0.2f);
                                            return;
                                        }
                                        if (this.type == 41)
{
                                            if (!this.wet)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f, 0.75f, 0.55f);
                                                return;
                                            }
                                        }
                                        else if (this.type == 988)
{
                                            if (!this.wet)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.35f, 0.65f, 1f);
                                                return;
                                            }
                                        }
                                        else
{
                                            if (this.type == 1326)
{
                                                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 1f, 0.1f, 0.8f);
                                                return;
                                            }
                                            if (this.type == 5335)
{
                                                Lighting.AddLight((int)base.Center.X / 16, (int)base.Center.Y / 16, 0.85f, 0.1f, 0.8f);
                                                return;
                                            }
                                            if (this.type >= 5140 && this.type <= 5146)
{
                                                float num23 = 1f;
                                                float num24 = 1f;
                                                float num25 = 1f;
                                                switch (this.type)
{
                                                case 5140:
                                                    num23 *= 0.9f;
                                                    num24 *= 0.8f;
                                                    num25 *= 0.1f;
                                                    break;
                                                case 5141:
                                                    num23 *= 0.25f;
                                                    num24 *= 0.1f;
                                                    num25 *= 0f;
                                                    break;
                                                case 5142:
                                                    num23 *= 0f;
                                                    num24 *= 0.25f;
                                                    num25 *= 0f;
                                                    break;
                                                case 5143:
                                                    num23 *= 0f;
                                                    num24 *= 0.16f;
                                                    num25 *= 0.34f;
                                                    break;
                                                case 5144:
                                                    num23 *= 0.3f;
                                                    num24 *= 0f;
                                                    num25 *= 0.17f;
                                                    break;
                                                case 5145:
                                                    num23 *= 0.3f;
                                                    num24 *= 0f;
                                                    num25 *= 0.35f;
                                                    break;
                                                case 5146:
                                                    num23 *= (float)Main.DiscoR / 255f;
                                                    num24 *= (float)Main.DiscoG / 255f;
                                                    num25 *= (float)Main.DiscoB / 255f;
                                                    break;
                                                }
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), num23, num24, num25);
                                                return;
                                            }
                                            if (this.type == 282)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.7f, 1f, 0.8f);
                                                return;
                                            }
                                            if (this.type == 286)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.7f, 0.8f, 1f);
                                                return;
                                            }
                                            if (this.type == 3112)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1f, 0.6f, 0.85f);
                                                return;
                                            }
                                            if (this.type == 4776)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.7f, 0f, 1f);
                                                return;
                                            }
                                            if (this.type == 3002)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 1.05f, 0.95f, 0.55f);
                                                return;
                                            }
                                            if (this.type == 5643)
{
                                                float num26 = (float)Main.DiscoR / 255f;
                                                float num27 = (float)Main.DiscoG / 255f;
                                                float num28 = (float)Main.DiscoB / 255f;
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), num26, num27, num28);
                                                return;
                                            }
                                            if (this.type == 331)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.55f, 0.75f, 0.6f);
                                                return;
                                            }
                                            if (this.type == 183)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.15f, 0.45f, 0.9f);
                                                return;
                                            }
                                            if (this.type == 75)
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.8f, 0.7f, 0.1f);
                                                if (this.timeSinceItemSpawned % 12 == 0)
{
                                                    Dust dust = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)this.height * 0.2f) + Main.rand.NextVector2CircularEdge((float)this.width, (float)this.height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 228, new Vector2?(new Vector2(0f, -Main.rand.NextFloat() * 0.3f - 1.5f)), 127, default(Color), 1f);
                                                    dust.scale = 0.5f;
                                                    dust.fadeIn = 1.1f;
                                                    dust.noGravity = true;
                                                    dust.noLight = true;
                                                    return;
                                                }
                                            }
                                            else if (ItemID.Sets.BossBag[this.type])
{
                                                Lighting.AddLight((int)((this.position.X + (float)this.width) / 16f), (int)((this.position.Y + (float)(this.height / 2)) / 16f), 0.4f, 0.4f, 0.4f);
                                                if (this.timeSinceItemSpawned % 12 == 0)
{
                                                    Dust dust2 = Dust.NewDustPerfect(base.Center + new Vector2(0f, (float)this.height * -0.1f) + Main.rand.NextVector2CircularEdge((float)this.width * 0.6f, (float)this.height * 0.6f) * (0.3f + Main.rand.NextFloat() * 0.5f), 279, new Vector2?(new Vector2(0f, -Main.rand.NextFloat() * 0.3f - 1.5f)), 127, default(Color), 1f);
                                                    dust2.scale = 0.5f;
                                                    dust2.fadeIn = 1.1f;
                                                    dust2.noGravity = true;
                                                    dust2.noLight = true;
                                                    dust2.alpha = 0;
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
References Terraria.Lighting.AddLight(), Terraria.ID.ItemID.Sets.BossBag, Terraria.WorldItem.color, Terraria.WorldItem.createTile, Terraria.Main.demonTorch, Terraria.Main.DiscoB, Terraria.Main.DiscoG, Terraria.Main.DiscoR, Terraria.Main.dust, Terraria.Main.essScale, Terraria.Entity.height, int, Terraria.Dust.NewDust(), Terraria.Dust.NewDustPerfect(), Terraria.Dust.noGravity, Terraria.WorldItem.placeStyle, Terraria.Entity.position, Terraria.Main.rand, Terraria.Dust.scale, Terraria.WorldItem.timeSinceItemSpawned, Terraria.ID.ItemID.Sets.Torches, Terraria.WorldItem.type, Terraria.Dust.velocity, Terraria.ID.ItemID.Sets.WaterTorches, Terraria.Entity.wet, Terraria.Entity.width, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.UpdateItem().