Terraria Decompiled: Terraria.WorldItem.SyncItemsInSection
SyncItemsInSection()
static void Terraria.WorldItem.SyncItemsInSection (int toClient, Point sectionCoordinates) inline static private
Definition at line 2349 of file WorldItem.cs.
        {
            Rectangle rectangle = new Rectangle(sectionCoordinates.X * 200 * 16, sectionCoordinates.Y * 150 * 16, 3200, 2400);
            rectangle.Inflate(16, 16);
            for (int i = 0; i < 400; i++)
            {
                WorldItem worldItem = Main.item[i];
                if (worldItem.active && rectangle.Contains(worldItem.Center.ToPoint()))
                {
                    NetMessage.SendData(160, toClient, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                }
            }
        }
References Terraria.WorldItem.active, Terraria.Entity.Center, Microsoft.Xna.Framework.Rectangle.Contains(), Microsoft.Xna.Framework.Rectangle.Inflate(), Terraria.Main.item, Terraria.NetMessage.SendData(), Microsoft.Xna.Framework.Point.X, and Microsoft.Xna.Framework.Point.Y.
Referenced by Terraria.WorldItem.WorldItem().