Terraria Decompiled: Terraria.WorldItem.TryCombiningIntoNearbyItems
TryCombiningIntoNearbyItems()
void Terraria.WorldItem.TryCombiningIntoNearbyItems (int myItemIndex) inline
Definition at line 434 of file WorldItem.cs.
        {
            if (this.playerIndexTheItemIsReservedFor != Main.myPlayer)
            {
                return;
            }
            if (!this.inner.CanPassivelyStackInWorld())
            {
                return;
            }
            if (this.stack >= this.maxStack)
            {
                return;
            }
            int num = 30;
            for (int i = myItemIndex + 1; i < 400; i++)
            {
                WorldItem worldItem = Main.item[i];
                if (!worldItem.IsAir && Item.CanStack(this.inner, worldItem.inner) && worldItem.shimmered == this.shimmered && worldItem.playerIndexTheItemIsReservedFor == this.playerIndexTheItemIsReservedFor && Math.Abs(this.position.X - worldItem.position.X) + Math.Abs(this.position.Y - worldItem.position.Y) <= (float)num)
                {
                    int num2 = Math.Min(worldItem.stack, this.maxStack - this.stack);
                    worldItem.stack -= num2;
                    this.stack += num2;
                    float num3 = (float)num2 / (float)this.stack;
                    this.position = Vector2.Lerp(worldItem.position, this.position, num3);
                    this.velocity = Vector2.Lerp(worldItem.velocity, this.velocity, num3);
                    if (worldItem.stack <= 0)
                    {
                        worldItem.TurnToAir(false);
                    }
                    if (Main.netMode != 0)
                    {
                        NetMessage.SendData(21, -1, -1, null, myItemIndex, 0f, 0f, 0f, 0, 0, 0);
                        NetMessage.SendData(21, -1, -1, null, i, 0f, 0f, 0f, 0, 0, 0);
                    }
                }
            }
        }
References System.Math.Abs(), Terraria.Item.CanPassivelyStackInWorld(), Terraria.Item.CanStack(), Terraria.WorldItem.inner, Terraria.WorldItem.IsAir, Terraria.Main.item, Microsoft.Xna.Framework.Vector2.Lerp(), Terraria.WorldItem.maxStack, System.Math.Min(), Terraria.Main.myPlayer, Terraria.Main.netMode, Terraria.WorldItem.playerIndexTheItemIsReservedFor, Terraria.Entity.position, Terraria.NetMessage.SendData(), Terraria.WorldItem.shimmered, Terraria.WorldItem.stack, Terraria.WorldItem.TurnToAir(), Terraria.Entity.velocity, Microsoft.Xna.Framework.Vector2.X, and Microsoft.Xna.Framework.Vector2.Y.
Referenced by Terraria.WorldItem.UpdateItem().